### PR TITLE
{tools}[GCCcore/13.2.0] JupyterHub v4.1.5, bcrypt v4.1.3, configurable-http-proxy v4.6.1, ...

### PR DESCRIPTION
**Pull request by lexming**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by lexming** [comment]
@boegelbot: please test @ generoso

**Comment by lexming** [comment]
@boegelbot please test @ jsc-zen3

**Review by migueldiascosta — APPROVED** [review]
lgtm

**Comment by migueldiascosta** [comment]
Going in, thanks @lexming!

**Pull request merged**
