### PR TITLE
ImageMagick R dep PR 8333

### PR DESCRIPTION
**Pull request by fizwit**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by Micket** [comment]
Test report by @Micket
**SUCCESS**
Build succeeded for 4 out of 4 (1 easyconfigs in this PR)
hebbe-s1.int.private - Linux centos 6.10, Intel(R) Xeon(R) CPU E5-2650 v3 @ 2.30GHz, Python 2.7.14
See https://gist.github.com/c612b92b85614639890463e59a8ede05 for a full test report.

**Comment by Micket** [comment]
Test report by @Micket
**SUCCESS**
Build succeeded for 3 out of 3 (1 easyconfigs in this PR)
vera-c1 - Linux centos linux 7.6.1810, Intel Xeon Processor (Skylake), Python 2.7.5
See https://gist.github.com/65156ae38aabce6183b585d24ec0efe4 for a full test report.

**Comment by Micket** [comment]
So, 7.0.8-46 was released a few hours ago. Do we update? I'm not sure I care. I tried to see if there was a changelog, but apparently, the developers don't even write commit messages (ouch).

**Comment by fizwit** [comment]
Closing this PR and will open new PR with the new filename.

**Comment by boegel** [comment]
replaced with #8374

**Pull request closed without merging**
