### PR TITLE
added a bunch of dependencies for Dolfin, including new python and perl (WIP)

### PR DESCRIPTION
**Pull request by JensTimmerman**
with foss-2014b toolchain

### CODE REVIEW

**Comment by JensTimmerman** [comment]
broken up a bit: from 61 ec's to 47 :-)

**Comment by JensTimmerman** [comment]
jenkins test this please

**Comment by JensTimmerman** [comment]
jenkins please test this

**Comment by boegel** [comment]
Jenkins: test this please

**Comment by boegel** [comment]
@JensTimmerman: Jenkins refuses to pick up the last commit, but this is too big to go in anyway, please split up in separate PRs

**Comment by boegel** [comment]
with support for DOLFIN 1.6.0 already merged, I propose we close this... 

thoughts @JensTimmerman?

**Comment by migueldiascosta** [comment]
@JensTimmerman, this PR is being closed for the following reason(s): no activity for > 6 months, obsoleted by more recent PRs for newer versions.
Please don't hesitate to reopen this PR or add a comment if you feel this contribution is still relevant.
For more information on our policy w.r.t. closing PRs, see https://easybuild.readthedocs.io/en/latest/Contributing.html#why-a-pull-request-may-be-closed-by-a-maintainer

**Pull request closed without merging**
