### PR TITLE
{bio}[foss/2018b] ChimPipe v0.9.5

### PR DESCRIPTION
**Pull request by SethosII**
(created using `eb --new-pr`)

This needs either ~~https://github.com/easybuilders/easybuild-easyconfigs/pull/7379~~ or ~~https://github.com/easybuilders/easybuild-easyconfigs/pull/7540~~.

### CODE REVIEW

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
node2565.golett.os - Linux centos linux 7.6.1810, Intel(R) Xeon(R) CPU E5-2680 v3 @ 2.50GHz, Python 2.7.5
See https://gist.github.com/ecdc7086dbbca451a70ddde29bf8b894 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
node2031.delcatty.os - Linux centos linux 7.6.1810, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.7.5
See https://gist.github.com/1e43de5683e9a1f5d1c17d4707a4ec69 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
node3100.skitty.os - Linux centos linux 7.6.1810, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz, Python 2.7.5
See https://gist.github.com/086217122d1c68053f3a636a3e88b520 for a full test report.

**Comment by SethosII** [comment]
@boegel This one also has `BLAST+ 2.8.1` as a dependency. Should this be replaced with a new easyconfig for `2.7.1` for `foss/2018b`?

**Comment by SethosII** [comment]
@boegel ping

**Comment by boegel** [comment]
@SethosII Unless there's a strong reason that `BLAST+` 2.8.1 is needed, stick with `BLAST+` 2.7.1 instead; otherwise, this easyconfig file will be incompatible with any easyconfig using a `2018b` toolchain that also requires `BLAST+`...

**Comment by SethosII** [comment]
@boegel I changed the dependency to `BLAST+` 2.7.1.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
node2448.golett.os - Linux centos linux 7.6.1810, Intel(R) Xeon(R) CPU E5-2680 v3 @ 2.50GHz, Python 2.7.5
See https://gist.github.com/1f3e0b9f437d6a015e938f08fe7a6c5c for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
node3121.skitty.os - Linux centos linux 7.6.1810, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz, Python 2.7.5
See https://gist.github.com/817bb61d9e44aa3d4a755838725aa927 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
node2013.delcatty.os - Linux centos linux 7.6.1810, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.7.5
See https://gist.github.com/18a077233a652a640543df20b06aafcd for a full test report.

**Comment by boegel** [comment]
Going in, thanks @SethosII!

**Pull request merged**
