### PR TITLE
use latest CMake 3.9.x as build dep for Eigen

### PR DESCRIPTION
**Pull request by boegel**
I've removed the `CMake-3.12.1.eb` easyconfig that @jhein32 added in #6770, since it fails to build on older operating systems like CentOS 6 (cfr. @migueldiascosta's test report at https://github.com/easybuilders/easybuild-easyconfigs/pull/6770#issuecomment-416799669).

@jhein32 Please let us know if you're OK with this change and the removal of `CMake-3.12.1.eb`

### CODE REVIEW

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 3 out of 3 (3 easyconfigs in this PR)
node2062.delcatty.os - Linux centos linux 7.5.1804, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.7.5
See https://gist.github.com/11c20b249d466c167e38074534dcba53 for a full test report.

**Comment by migueldiascosta** [comment]
Test report by @migueldiascosta
**SUCCESS**
Build succeeded for 3 out of 3 (3 easyconfigs in this PR)
grc-cluster1 - Linux centos 6.9, Intel(R) Xeon(R) CPU E5-2640 0 @ 2.50GHz, Python 2.7.14
See https://gist.github.com/de7c2bca9c4975816adf9e3506e1f963 for a full test report.

**Comment by jhein32** [comment]
If CMake 3.9.x is good enough to build Eigen 3.3.5, this makes sense to me.  Using a version that does the trick but can easily be deployed very widely.

I would keep the 3.12.1 in dummy as well.  We have examples of software (e.g. latest Boost) that will not build with CMake below 3.12.0 (or there about, 3.11.4 is not good enough).  We should have a comment in the config that this will not compile with the system compiler of old Linux distributions.  I am keen to have modern CMake versions in dummy to supply them to my users (CentOS 7 here) and I assume many others with modern OS distributions are as well. 

So my vote: Keep CMake 3.12.1 (add a comment though), add CMake 3.9.6 and change the Eigen configs to CMake 3.9.6.

**Comment by boegel** [comment]
Thanks for the feedback @jhein32, I've restored the `CMake-3.12.1.eb` easyconfig and added the proposed comment.

@vanzod Can you give this a test as well, and then merge unless you have any concerns?

**Comment by akesandgren** [comment]
Since Boost is built with GCCcore or higher (except for the rather old Boost-1.55.0.eb), that reason for keeping CMake 3.12 in dummy is void.

**Comment by boegel** [comment]
@akesandgren That's true, but @jhein32 also mentioned that he wants to provide the latest `CMake` to his users, presumably in a way that is compatible with multiple toolchains. With that in mind, restoring the `CMake-3.12.1.eb` easyconfig makes sense...

**Comment by jhein32** [comment]
@akesandgren @bogel This is not about using CMake within EB.  It is about users wanting to build all sort of things on the system (there are still some users that compile things on their own).  I had requests for CMake updates for building software with the system compiler in the past.    

J.

**Comment by boegel** [comment]
@jhein32 Not sure who @bogel is, but he/she is going to be very confused now. ;)

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 4 out of 4 (4 easyconfigs in this PR)
node3170.skitty.os - Linux centos linux 7.4.1708, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz, Python 2.7.5
See https://gist.github.com/174ae1396aa2e575b17aaa3850238b41 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 4 out of 4 (4 easyconfigs in this PR)
node3170.skitty.os - Linux centos linux 7.4.1708, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz, Python 2.7.5
See https://gist.github.com/50185f095d9a8473520d8da7e938c575 for a full test report.

**Comment by vanzod** [comment]
Test report by @vanzod
**SUCCESS**
Build succeeded for 4 out of 4 (4 easyconfigs in this PR)
cermis - Linux debian 9.4, Intel(R) Xeon(R) CPU           E5620  @ 2.40GHz, Python 2.7.13
See https://gist.github.com/38c4637a35f536eb18662facd2fc67fd for a full test report.

**Comment by vanzod** [comment]
Going in, thanks @boegel!

**Pull request merged**
