### PR TITLE
{data}[foss/2017b] pyshp v1.2.12

### PR DESCRIPTION
**Pull request by arielzn**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by migueldiascosta** [comment]
Test report by @migueldiascosta
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
grc-s05 - Linux centos 6.9, Intel(R) Xeon(R) CPU E5-4640 0 @ 2.40GHz, Python 2.6.6
See https://gist.github.com/defa634ce34eeb5268c65485bb4d1c6b for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
node2602.swalot.os - Linux centos linux 7.4.1708, Intel(R) Xeon(R) CPU E5-2660 v3 @ 2.60GHz, Python 2.7.5
See https://gist.github.com/5d3e0e178e8db30407f71786908a814c for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
node2058.delcatty.os - Linux centos linux 7.4.1708, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.7.5
See https://gist.github.com/c685fcc152f4df0ae9f82e36cf0c0c87 for a full test report.

**Comment by migueldiascosta** [comment]
Going in, thanks @arielzn!

**Pull request merged**
