### PR TITLE
{system}[system/system] CUDAcore v11.5.1

### PR DESCRIPTION
**Pull request by mustafabar**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by mustafabar** [comment]
Test report by @mustafabar
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
alvis-c1 - Linux centos linux 7.9.2009, x86_64, Intel Xeon Processor (Skylake), Python 3.6.8
See https://gist.github.com/09f9398362837255af59989fbca7238f for a full test report.

**Comment by migueldiascosta** [comment]
@boegelbot please test @ generoso

**Review by migueldiascosta — APPROVED** [review]
lgtm

**Comment by migueldiascosta** [comment]
Going in, thanks @mustafabar!

**Pull request merged**
