### PR TITLE
{chem,math}[gomkl/2023a] FDMNES v2024-02-29, MUMPS v5.6.2 w/ metis seq

### PR DESCRIPTION
**Pull request by PetrKralCZ**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by verdurin** [comment]
@PetrKralCZ the test error is:
```
AssertionError: Should not have multiple variants of dependencies.
Found 2 variants of 'MUMPS' dependency in easyconfigs using '2023a' toolchain generation
* version: 5.6.1; versionsuffix: -metis as dep for {'SLEPc-3.20.1-foss-2023a.eb', 'MODFLOW-6.4.4-foss-2023a.eb', 'snakemake-8.4.2-foss-2023a.eb', 'phyluce-1.7.3-foss-2023a.eb', 'Clp-1.17.9-foss-2023a.eb', 'PuLP-2.8.0-foss-2023a.eb', 'Cbc-2.10.11-foss-2023a.eb', 'deal.II-9.5.2-foss-2023a.eb', 'PETSc-3.20.3-foss-2023a.eb', 'Cgl-0.60.8-foss-2023a.eb'}
  * version: 5.6.2; versionsuffix: -metis-seq as dep for {'FDMNES-2024-02-29-gomkl-2023a.eb'}
```
Could you downgrade MUMPS to `5.6.1`?

**Comment by verdurin** [comment]
Thanks. 
Now it's complaining about `METIS`:
```
Found 2 variants of 'MUMPS' dependency in easyconfigs using '2023a' toolchain generation
* version: 5.6.1; versionsuffix: -metis as dep for {'phyluce-1.7.3-foss-2023a.eb', 'Clp-1.17.9-foss-2023a.eb', 'PETSc-3.20.3-foss-2023a.eb', 'Cgl-0.60.8-foss-2023a.eb', 'MODFLOW-6.4.4-foss-2023a.eb', 'PuLP-2.8.0-foss-2023a.eb', 'SLEPc-3.20.1-foss-2023a.eb', 'Cbc-2.10.11-foss-2023a.eb', 'deal.II-9.5.2-foss-2023a.eb', 'snakemake-8.4.2-foss-2023a.eb'}
  * version: 5.6.1; versionsuffix: -metis-seq as dep for {'FDMNES-2024-02-29-gomkl-2023a.eb'}
```
That's clearly something you've deliberately added, so we'll need to add an exception to the tests here.

**Comment by boegel** [comment]
@boegelbot please test @ generoso

**Comment by boegel** [comment]
@boegelbot please test @ jsc-zen3

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 3 out of 3 (2 easyconfigs in total)
node3113.skitty.os - Linux RHEL 8.8, x86_64, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz, Python 3.6.8
See https://gist.github.com/boegel/2c0358d9c4fefc8347379413ae1b4ece for a full test report.

**Review by boegel — APPROVED** [review]
lgtm

**Pull request merged**
