### PR TITLE
{bio}[foss/2018a] Stacks v2.3b

### PR DESCRIPTION
**Pull request by bedroge**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by bedroge** [comment]
I've removed the dependencies on sparsehash and SAMtools: the latter seems to be included with the Stacks source tarball (and there are no configure options to specify its location anyway), while --enable-sparsehash gave a warning during the configuration:
`configure: WARNING: unrecognized options: --enable-sparsehash`

And according to this post, they indeed don't support sparsehash anymore:
https://groups.google.com/d/msg/stacks-users/JAs16qz6R1I/nzc6LNSQAwAJ

**Comment by zao** [comment]
Test report by @zao
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
freja - Linux ubuntu 18.04, AMD Ryzen 7 1700 Eight-Core Processor, Python 2.7.15rc1
See https://gist.github.com/7bf7c5b2207679fd019de1a4bfcebe5a for a full test report.

**Comment by vanzod** [comment]
Test report by @vanzod
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
cermis - Linux debian 9.7, Intel(R) Xeon(R) CPU           X5670  @ 2.93GHz, Python 2.7.13
See https://gist.github.com/92b4f8f186a0754e118f7fe6be91e04d for a full test report.

**Comment by vanzod** [comment]
Going in, thanks @bedroge!

**Pull request merged**
