### PR TITLE
{chem}[foss/2019a,intel/2019a] ASAP3 v3.11.9, kim-api v2.0.2, openkim-models v20190331 w/ Python 3.7.2

### PR DESCRIPTION
**Pull request by schiotz**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by schiotz** [comment]
Hi Ryan @ellio167

OpenKIM for the 2019a toolchain is included here.

**Comment by smoors** [comment]
checking with @boegel here, don't think it is a good idea to change from existing easyconfigs with name `OpenKIM-API` to `kim-api`.

**Comment by schiotz** [comment]
I think the name should be fixed as soon as possible - it is better to do it now than to wait until it is being actively used by many groups.  So far, I think ASAP is the only easybuild package using OpenKIM.

Also, the switch from OpenKIM version 1 to OpenKIM version two was a major one, the OpenKIM developers elected to change package name then to make both versions coexist (but have now dropped that idea as so few was using version 1).

But it may make sense to rename old versions from the 2016 and 2017 toolchains.  Perhaps.

**Comment by schiotz** [comment]
This PR will conflict with #8768 as it uses a different version of ASE.  I will make a new release of Asap and then replace this with a new PR using the same version of ASE as in #8768 and also the newest version of the kim-api package.

**Comment by schiotz** [comment]
This PR has been made obsolete by #8786 which uses the same ASE version as #8768 and also includes a newer KIM-API than this one.

**Pull request closed without merging**
