### PR TITLE
{data}[gompi/2022b,iimpi/2022b] HDF5 v1.14.0, netCDF v4.9.0

### PR DESCRIPTION
**Pull request by jfgrimm**
we'll have to see if packages support 1.14, according to the documentation:
> Applications that were created with earlier HDF5 releases may not compile with 1.14 by default.
>
>The [API Compatibility Macros](https://portal.hdfgroup.org/display/HDF5/API+Compatibility+Macros) in HDF5 allow users to work around this issue. Users can specify a  compatibility macro mapping for the version of HDF5 that an application  was built with. For example, a 1.10 application can be built with 1.14  using either an application or library mapping as follows:
>* To compile an application built with a version of HDF5 that includes deprecated symbols (the default), specify: `-DH5_USE_110_API` (autotools) or `-DH5_USE_110_API:BOOL=ON` (CMake)
>* To build an HDF5 library with the 1.10 APIs specify `--with-default-api-version=v110` (Autotools) or `-DDEFAULT_API_VERSION:STRING=v110` (CMake). 
>
>However, users will not be able to take advantage of some of the new features in 1.14 if using these compatibility mappings.

requires:
- [x] #17113

(created using `eb --new-pr`)

### CODE REVIEW

**Comment by branfosj** [comment]
See the netCDF issues in #16834

**Comment by jfgrimm** [comment]
split `Szip` into its own PR

**Comment by verdurin** [comment]
@jfgrimm is this at all affected by the discussion today about `HDF5`?

**Comment by jfgrimm** [comment]
> @jfgrimm is this at all affected by the discussion today about `HDF5`?

No, only #17093

**Comment by boegel** [comment]
@boegelbot please test @ generoso

**Comment by boegel** [comment]
Same problems with the tests as in #16834 ... :-/

```
The following tests FAILED:
	161 - nc_test4_run_par_test (Timeout)
```

**Comment by jfgrimm** [comment]
> 

do you know exactly where in that it hangs? `nc_test4_run_par_test` runs several tests:
```
tst_mpi_parallel
tst_parallel
tst_parallel3
tst_parallel4
tst_parallel5
tst_parallel6
tst_parallel_zlib
tst_parallel_compress
tst_nc4perf
tst_mode
tst_simplerw_coll_r
tst_quantize_par
```

**Comment by jfgrimm** [comment]
@boegelbot please test @ generoso

**Comment by jfgrimm** [comment]
@boegelbot please test @ generoso

**Comment by jfgrimm** [comment]
@boegelbot please test @ generoso
EB_ARGS=netCDF-4.9.0-gompi-2022b.eb

**Comment by jfgrimm** [comment]
@boegelbot please test @ generoso
EB_ARGS=netCDF-4.9.0-gompi-2022b.eb

**Comment by jfgrimm** [comment]
@boegelbot please test @ jsc-zen2

**Comment by zao** [comment]
Test report by @zao
**SUCCESS**
Build succeeded for 4 out of 4 (4 easyconfigs in total)
eb-u2204 - Linux Ubuntu 22.04, x86_64, AMD Ryzen 9 3900X 12-Core Processor, Python 3.10.6
See https://gist.github.com/b9d241657288c4f081757fa4d65ba6d1 for a full test report.

**Comment by boegel** [comment]
@jfgrimm What's the plan with this (from failed test report on `jsc-zen2`):
```
The following tests FAILED:
	161 - nc_test4_run_par_test (Timeout)
```

**Comment by jfgrimm** [comment]
@boegelbot please test @ jsc-zen2
EB_ARGS=netCDF-4.9.0-iimpi-2022b.eb

**Comment by jfgrimm** [comment]
@boegel should be good to go now, tests problematic for generoso/jsc-zen2 are now skipped in both `gompi` and `iimpi` variants

**Comment by verdurin** [comment]
Test report by @verdurin
**SUCCESS**
Build succeeded for 10 out of 10 (4 easyconfigs in total)
easybuild-c7.novalocal - Linux CentOS Linux 7.9.2009, x86_64, Intel Xeon Processor (Skylake, IBRS), Python 3.6.8
See https://gist.github.com/960f005a78b8e44b1c81ed7c7db2ba8a for a full test report.

**Review by boegel — APPROVED** [review]
lgtm

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 4 out of 4 (4 easyconfigs in total)
node3104.skitty.os - Linux RHEL 8.6, x86_64, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz (skylake_avx512), Python 3.6.8
See https://gist.github.com/df413c8ba036e97b0e4ee69eefe16912 for a full test report.

**Pull request merged**
