### PR TITLE
{bio}[intel/2017b] RSEM v1.3.0

### PR DESCRIPTION
**Pull request by boegel**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
gligar02.gligar.os - Linux centos linux 7.4.1708, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.7.5
See https://gist.github.com/79957efe9832a1c5798a6d80e7ebdc6f for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
node2407.golett.os - Linux centos linux 7.4.1708, Intel(R) Xeon(R) CPU E5-2680 v3 @ 2.50GHz, Python 2.7.5
See https://gist.github.com/aa7df86afc8957fbf5adbb39ce0fa385 for a full test report.

**Comment by verdurin** [comment]
Test report by @verdurin
**FAILED**
Build succeeded for 0 out of 1 (1 easyconfigs in this PR)
rescomp2 - Linux centos 6.8, Intel(R) Xeon(R) CPU E5-2650 v2 @ 2.60GHz, Python 2.7.11
See https://gist.github.com/0dd5b4a3338a1350fe3b92b247bf84bb for a full test report.

**Comment by verdurin** [comment]
@boegel - checksum problem?

**Comment by boegel** [comment]
@verdurin Hmm, that's very strange, I'm also getting a different checksum now when I force a re-download. I hope this isn't a repetition of the mess we went through in #5151...

**Comment by boegel** [comment]
OK, it seems this is an actual sneaky re-release under the same `1.3.0` version number (so not a repetition of #5151), see also https://github.com/spack/spack/pull/6650, in particular https://github.com/spack/spack/pull/6650#issuecomment-354929097 .

My download was from Dec 15th 2016, so I still had the old `1.3.0` release...

Fixed checksum(s) coming in.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 3 out of 3 (3 easyconfigs in this PR)
gligar01.gligar.os - Linux centos linux 7.4.1708, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.7.5
See https://gist.github.com/66ccdd0613f3a8ea6963e180ad015d10 for a full test report.

**Comment by verdurin** [comment]
Test report by @verdurin
**FAILED**
Build succeeded for 1 out of 5 (1 easyconfigs in this PR)
rescomp2 - Linux centos 6.8, Intel(R) Xeon(R) CPU E5-2650 v2 @ 2.60GHz, Python 2.7.11
See https://gist.github.com/f2a2cde2585b2b775ddaeff8aeca0f35 for a full test report.

**Comment by verdurin** [comment]
@boegel problem building the docs:
```
Writing index file refman.idx
No file refman.aux.
(/usr/share/texmf/tex/latex/base/ts1cmr.fd)
(/usr/share/texmf/tex/latex/psnfss/t1ptm.fd)In file included from /dev/shm/JasPer/2.0.12/intel-2017a/jasper-2.0.12/src/libjasper/include/jasper/jas_seq.h(83),
                 from /dev/shm/JasPer/2.0.12/intel-2017a/jasper-2.0.12/src/libjasper/jpc/jpc_mct.c(76):
/dev/shm/JasPer/2.0.12/intel-2017a/jasper-2.0.12/src/libjasper/include/jasper/jas_math.h(125): warning #1292: unknown attribute "no_sanitize_undefined"
  JAS_ATTRIBUTE_DISABLE_USAN
  ^

In file included from /dev/shm/JasPer/2.0.12/intel-2017a/jasper-2.0.12/src/libjasper/include/jasper/jas_seq.h(83),
                 from /dev/shm/JasPer/2.0.12/intel-2017a/jasper-2.0.12/src/libjasper/jpc/jpc_mct.c(76):
/dev/shm/JasPer/2.0.12/intel-2017a/jasper-2.0.12/src/libjasper/include/jasper/jas_math.h(138): warning #1292: unknown attribute "no_sanitize_undefined"
  JAS_ATTRIBUTE_DISABLE_USAN
  ^

In file included from /dev/shm/JasPer/2.0.12/intel-2017a/jasper-2.0.12/src/libjasper/include/jasper/jas_seq.h(83),
                 from /dev/shm/JasPer/2.0.12/intel-2017a/jasper-2.0.12/src/libjasper/jpc/jpc_mct.c(76):
/dev/shm/JasPer/2.0.12/intel-2017a/jasper-2.0.12/src/libjasper/include/jasper/jas_math.h(151): warning #1292: unknown attribute "no_sanitize_undefined"
  JAS_ATTRIBUTE_DISABLE_USAN
  ^

In file included from /dev/shm/JasPer/2.0.12/intel-2017a/jasper-2.0.12/src/libjasper/include/jasper/jas_seq.h(83),
                 from /dev/shm/JasPer/2.0.12/intel-2017a/jasper-2.0.12/src/libjasper/jpc/jpc_mct.c(76):
/dev/shm/JasPer/2.0.12/intel-2017a/jasper-2.0.12/src/libjasper/include/jasper/jas_math.h(164): warning #1292: unknown attribute "no_sanitize_undefined"
  JAS_ATTRIBUTE_DISABLE_USAN
  ^


(/usr/share/texmf/tex/latex/hyperref/nameref.sty
(/usr/share/texmf/tex/latex/oberdiek/refcount.sty)) [1{/var/lib/texmf/fonts/map
/pdftex/updmap/pdftex.map}] [2] [1] [2]
Chapter 1.
(./main.tex (/usr/share/texmf/tex/latex/psnfss/t1pcr.fd) [1]
Overfull \hbox (5.40022pt too wide) in paragraph at lines 35--35
[]\T1/pcr/m/n/8 EVENT SHALL THE COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, OR A
NY SPECIAL[]

Overfull \hbox (5.40022pt too wide) in paragraph at lines 45--45
[]\T1/pcr/m/n/8 GRANTED HEREUNDER, EACH USER HEREBY ASSUMES SOLE RESPONSIBILITY
 TO SECURE[]
) [2]
Chapter 2.
[3] (./getting_started.tex (/usr/share/texmf/tex/latex/psnfss/ts1ptm.fd)
Overfull \hbox (0.60022pt too wide) in paragraph at lines 29--29
[]\T1/pcr/m/n/8 where $OPTIONS corresponds to zero or more -D options as descri
bed below[]

Overfull \hbox (10.20023pt too wide) in paragraph at lines 37--37
[]\T1/pcr/m/n/8 4) Build the code using the make utility.  To do this, invoke t
he command:[]
[4]
Overfull \hbox (0.60022pt too wide) in paragraph at lines 76--76
[]\T1/pcr/m/n/8 2) Generate the project file needed to build the software with
Microsoft[]

Overfull \hbox (5.40022pt too wide) in paragraph at lines 79--79
[]    \T1/pcr/m/n/8 cmake -G "Visual Studio 12 2013 Win64" -H%SOURCE_DIR% -B%BU
ILD_DIR% ^[]

Overfull \hbox (10.20023pt too wide) in paragraph at lines 93--93
[]\T1/pcr/m/n/8 The option OPTION can be set to the value VALUE with a command-
line option[]

Underfull \vbox (badness 10000) has occurred while \output is active [5]
Overfull \hbox (0.60022pt too wide) in paragraph at lines 138--138
[]\T1/pcr/m/n/8 DO NOT RELY ON THIS OPTION, AS IT IS LIKELY TO BE REMOVED IN TH
E FUTURE.[]
) [6]
Chapter 3.
[7] (./faq.tex

! LaTeX Error: Something's wrong--perhaps a missing \item.

See the LaTeX manual or LaTeX Companion for explanation.
Type  H <return>  for immediate help.
 ...

l.5 \end{DoxyItemize}

?
! Emergency stop.
 ...

l.5 \end{DoxyItemize}

!  ==> Fatal error occurred, no output PDF file produced!
Transcript written on refman.log.
make[2]: *** [doc/CMakeFiles/manual_pdf] Error 1
make[2]: Leaving directory `/dev/shm/JasPer/2.0.12/intel-2017a/easybuild_obj'
make[1]: *** [doc/CMakeFiles/manual_pdf.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
```

**Comment by boegel** [comment]
I don't think it's worth putting more effort in this PR:

* we have more recent easyconfigs for RSEM: `RSEM-1.3.1-intel-2018a.eb`
* in recent `JasPer` easyconfigs, we use `-DJAS_ENABLE_DOC=OFF` as configure option to avoid the problem that @verdurin ran into

**Pull request closed without merging**
