### PR TITLE
{vis}[GCCcore/13.3.0] Kaleido v0.2.1, plotly.py v5.24.1, QCG-PilotJob v0.14.1 ...

### PR DESCRIPTION
**Pull request by maxim-masterov**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by maxim-masterov** [comment]
Test report by @maxim-masterov
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
tcn482.local.snellius.surf.nl - Linux RHEL 9.4, x86_64, AMD EPYC 7H12 64-Core Processor, Python 3.9.18
See https://gist.github.com/maxim-masterov/84f9e52382ab2e29272edd41faed0604 for a full test report.

**Comment by smoors** [comment]
@boegelbot: please test @ generoso

**Comment by smoors** [comment]
@boegelbot please test @ jsc-zen3

**Comment by smoors** [comment]
Going in, thanks @maxim-masterov!

**Pull request merged**
