### PR TITLE
+download URL for imkl 2018.3 - imkl-iompi

### PR DESCRIPTION
**Pull request by jose-d**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by jose-d** [comment]
Test report by @jose-d
**FAILED**
Build succeeded for 0 out of 1 (1 easyconfigs in this PR)
koios1 - Linux centos linux 7.3.1611, Intel(R) Xeon(R) Gold 6130 CPU @ 2.10GHz, Python 2.7.5
See https://gist.github.com/8d9ad54d4ef2b1489a734458483b0779 for a full test report.

**Comment by jose-d** [comment]
Test report by @jose-d
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
koios1 - Linux centos linux 7.5.1804, Intel(R) Xeon(R) Gold 6130 CPU @ 2.10GHz, Python 2.7.5
See https://gist.github.com/beb80de60d53e5b7d35ccfc60d3c15dc for a full test report.

**Comment by jose-d** [comment]
CI problem?
```
AssertionError: No multi-variant deps found for '^.*-(?P<tc_gen>201[89][ab]).*\.eb$' easyconfigs:

found 2 variants of 'PyQt5' dependency in easyconfigs using '2018a' toolchain generation
* version: 5.10.1; versionsuffix: -Python-3.6.4 as dep for set(['AFNI-18.1.09-intel-2018a-Python-3.6.4.eb'])
* version: 5.9.2; versionsuffix: -Python-3.6.4 as dep for set(['Spyder-3.3.1-foss-2018a-Python-3.6.4.eb'])
```

**Comment by boegel** [comment]
Going in, thanks @jose-d!

**Pull request merged**
