### PR TITLE
Added config for Nextflow 23.04.2

### PR DESCRIPTION
**Pull request by lasseringstedmark**
Added support for nextflow 23.04.2

### CODE REVIEW

**Comment by smoors** [comment]
Test report by @smoors
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
node318.hydra.os - Linux CentOS Linux 7.9.2009, x86_64, Intel(R) Xeon(R) Gold 6148 CPU @ 2.40GHz (skylake_avx512), Python 3.6.8
See https://gist.github.com/smoors/87f25534d4c913e09dd1737963460bc4 for a full test report.

**Comment by smoors** [comment]
@lasseringstedmark i added a newline char to the end of the file to make the github checks pass.

**Comment by smoors** [comment]
@boegelbot: please test @ generoso

**Comment by smoors** [comment]
@boegelbot please test @ jsc-zen2

**Review by smoors — APPROVED** [review]
lgtm

**Comment by smoors** [comment]
Going in, thanks @lasseringstedmark!

**Comment by lasseringstedmark** [comment]
It is me who thanks @smoors :)

**Pull request merged**
