### PR TITLE
promote Python to runtime dependency for Ninja + add 'ninja --version' as sanity check command

### PR DESCRIPTION
**Pull request by boegel**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by boegel** [comment]
@boegelbot please test @ generoso
EB_ARGS="Ninja-1.10.0-GCCcore-9.3.0.eb Ninja-1.10.1-GCCcore-10.2.0.eb Ninja-1.10.2-GCCcore-10.3.0.eb Ninja-1.8.2-foss-2018b.eb Ninja-1.8.2-fosscuda-2018b.eb Ninja-1.9.0-GCCcore-8.2.0.eb Ninja-1.9.0-GCCcore-8.3.0.eb Ninja-1.9.0-foss-2018b.eb"

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 11 out of 11 (11 easyconfigs in total)
node2618.swalot.os - Linux centos linux 7.9.2009, x86_64, Intel(R) Xeon(R) CPU E5-2660 v3 @ 2.60GHz (haswell), Python 3.6.8
See https://gist.github.com/29e667ffb2ad436a5ee7fe78e3a353cf for a full test report.

**Comment by boegel** [comment]
Ouch, tests are failing because this requires that a `-Python-*` verionsuffix is added, which implies changing about 240 easyconfigs that have `Ninja` listed as a build dependency...

`Ninja` is always combined with `Meson`, so the `Python` dependency required for `Ninja` is always there in practice.

Do we escape here by making an exception in the tests to not require a `Python` versionsuffix for `Ninja` despite it having `Python` as a dependency?

Or do we tweak the `Ninja` build dependency specificiation by adding the `versionsuffix` in all those easyconfigs?

Since this doesn't affect anything in the installation of `Ninja` itself, there's no strict need to retest all those easyconfigs...

**Comment by Micket** [comment]
Can ninja be multideps for at least some of the older stuff?

**Comment by boegel** [comment]
> Can python be multideps for at least some of the older stuff?

I don't think that makes sense here, since a `ninja` command is involved, which can only use one of both Python versions?

**Comment by Micket** [comment]
Then I'd say lets add an exception in the tests for verssion <= 1.9.0. Nothing terrible happens if we miss a suffix, and for 2020b onwards we won't need it anyway.

**Comment by Micket** [comment]
> Conflict found for dependencies of Meson-0.48.1-intel-2018a-Python-3.6.4: Python-2.7.14-intel-2018a vs Python-3.6.4-intel-2018a

Oh crap. I guess we have been sloppy with Ninja, mixing python 2 and 3 indirectly.
But, since that works, can't it be multideps then?
Actually, the installed version is just a single binary that doesn't seem to link to any libpython. In what way does this use python?

**Comment by boegel** [comment]
I'm not sure there's a easy way out, like this one for example:
```
Conflict found for dependencies of Qt5-5.15.2-GCCcore-10.3.0: Python-2.7.18-GCCcore-10.3.0-bare vs Python-3.9.5-GCCcore-10.3.0 
```

Even `multi_deps` wouldn't help us here (unless we switch to the non-bare `Python` 2.x as build dep for Qt5, perhaps)

**Comment by Micket** [comment]
But first of all, in what way does ninja rely on python? There are no python scripts and no libpython linking in the installations i got.

**Comment by boegel** [comment]
> But first of all, in what way does ninja rely on python? There are no python scripts and no libpython linking in the installations i got.

I ran into trouble running `ninja`, it was failing because `libpython3.*.so` wasn't found.
But I'm having trouble reproducing that now, even when considering different `Ninja` versions... 😕

**Comment by boegel** [comment]
I must have mixed up things here, I can't find a runtime dependency on Python for Ninja when checking again...

I've copying the good stuff from here in #13222

**Pull request closed without merging**
