### PR TITLE
{data}[foss/2018a] netcdf4-python v1.4.2 w/ Python 3.6.4

### PR DESCRIPTION
**Pull request by boegel**
(created using `eb --new-pr`)
requires ~~https://github.com/easybuilders/easybuild-easyblocks/pull/1578~~

### CODE REVIEW

**Comment by migueldiascosta** [comment]
hm, #7817 got merged ahead of this one... is the goal to use `PythonBundle` from now on?

**Comment by boegel** [comment]
@migueldiascosta Using `PythonBundle` makes more sense, avoids introducing modules for all dependencies if they're simply Python packages...

**Comment by boegel** [comment]
(close/re-open to pick up new Travis tests)

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
node3118.skitty.os - Linux centos linux 7.6.1810, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz, Python 2.7.5
See https://gist.github.com/d3e0c1618cd756d7182464c3ec2a8498 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
node2006.delcatty.os - Linux centos linux 7.6.1810, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.7.5
See https://gist.github.com/b079579d0f4bbd1b00e651b6e291ff5b for a full test report.

**Comment by vanzod** [comment]
Test report by @vanzod
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
cermis - Linux debian 9.9, Intel(R) Xeon(R) CPU           X5670  @ 2.93GHz, Python 2.7.13
See https://gist.github.com/c82747c85f34125a81172db50676c481 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
node2406.golett.os - Linux centos linux 7.6.1810, Intel(R) Xeon(R) CPU E5-2680 v3 @ 2.50GHz, Python 2.7.5
See https://gist.github.com/23399b80e67ffff2e506af9bd9b70c6d for a full test report.

**Comment by vanzod** [comment]
Going in, thanks @boegel!

**Pull request merged**
