### PR TITLE
{vis}[foss/2016a] PyBERT 1.7.9 w/Python-2.7.11 (WIP)

### PR DESCRIPTION
**Pull request by hajgato**

### CODE REVIEW

**Comment by boegel** [comment]
lgtm

**Comment by boegel** [comment]
Test report by @boegel
**FAILED**
Build succeeded for 5 out of 6 (6 easyconfigs in this PR)
node2427.golett.os - Linux centos linux 7.2.1511, Intel(R) Xeon(R) CPU E5-2680 v3 @ 2.50GHz, Python 2.7.5
See https://gist.github.com/ed0a2baa931bc4487f20e6d0759185bf for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**FAILED**
Build succeeded for 4 out of 6 (6 easyconfigs in this PR)
node2062.delcatty.os - Linux SL 6.8, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.6.6
See https://gist.github.com/9d2825ff9596c769fd0607d543591f35 for a full test report.

**Comment by boegel** [comment]
@hajgato hmm, looks like a missing dep, maybe?

```
== 2016-08-29 17:36:20,701 run.py:395 DEBUG cmd " /user/scratch/gent/vsc400/vsc40023/easybuild_REGTEST/CO7/haswell-ib/software/Python/2.7.11-foss-2016a/bin/python setup.py build " exited with exitcode 1 and output:
Traceback (most recent call last):
  File "setup.py", line 194, in <module>
    write_version_py(filename='enable/_version.py')
  File "setup.py", line 98, in write_version_py
    from kiva._version import git_revision, full_version
  File "/tmp/vsc40023/easybuild_build/PyBERT/1.7.9/foss-2016a-Python-2.7.11/enable/enable-4.5.1/kiva/__init__.py", line 21, in <module>
    from fonttools import Font
  File "/tmp/vsc40023/easybuild_build/PyBERT/1.7.9/foss-2016a-Python-2.7.11/enable/enable-4.5.1/kiva/fonttools/__init__.py", line 1, in <module>
    from font import Font, str_to_font
  File "/tmp/vsc40023/easybuild_build/PyBERT/1.7.9/foss-2016a-Python-2.7.11/enable/enable-4.5.1/kiva/fonttools/font.py", line 11, in <module>
    from .font_manager import FontProperties, fontManager
  File "/tmp/vsc40023/easybuild_build/PyBERT/1.7.9/foss-2016a-Python-2.7.11/enable/enable-4.5.1/kiva/fonttools/font_manager.py", line 1420, in <module>
    _rebuild()
  File "/tmp/vsc40023/easybuild_build/PyBERT/1.7.9/foss-2016a-Python-2.7.11/enable/enable-4.5.1/kiva/fonttools/font_manager.py", line 1369, in _rebuild
    fontManager = FontManager()
  File "/tmp/vsc40023/easybuild_build/PyBERT/1.7.9/foss-2016a-Python-2.7.11/enable/enable-4.5.1/kiva/fonttools/font_manager.py", line 1080, in __init__
    self.defaultFont['ttf'] = self.ttffiles[0]
IndexError: list index out of range
```

**Comment by hajgato** [comment]
@boegel In the first test `PyQt` fails because `Qt` can work only with the bundled `phonon`. At your site `phonon` is installed, and interferes with `PyQt` (see http://python.6.x6.nabble.com/Compiling-PyQt-4-10-3-with-SIP-4-15-4-td5046633.html). We have to prevent PyQt to use the local `phonon`.

**Comment by boegel** [comment]
@hajgato Could be right (but only on SL6, the CentOS7 problem is different):

```
$ rpm -qa | grep phonon
phonon-backend-gstreamer-4.6.2-28.el6_5.x86_64
```

Any idea on how to prevent that the local `phonon` is used?

**Comment by hajgato** [comment]
@boegel no idea. I did not find any info, but I suspect that it should be solved at `Qt` level. 
For us (without system `phonon`), `Qt::phonon` is not installed. For sure `PyQt` makes the `phonon` modules even without system installed `phonon`, I do not know why. Maybe we have to disable `phonon` for `PyQt`, as it is rare that somebody would use a `KDE` environment on HPC....

For sure, `PyQt` takes the info from `Qt`. (see `configure-ng.py`:
```
'phonon':           ModuleMetadata(qmake_QT=['phonon'])
```

**Comment by hajgato** [comment]
@boegel Sorry, I messed up, we have to disable `phonon` for `Qt`, using `-no-phonon --no-phonon-backend` configopts. (But I am not able to predict the consequences...)

**Comment by boegel** [comment]
@hajgato does it make sense to add our own `phonon` as a dep to `Qt` instead?

**Comment by hajgato** [comment]
@boegel: The solution for the second problem is to use the env variable `TTFPATH` pointing to `matplotlib`'s `mpl_data` directory (Where a couple of TrueType fonts are located. (see http://osdir.com/ml/python-enthought-devel/2007-03/msg00351.html). 

I tried in the `PyBERT` easyconfig to add a `prebuildopts` for `enable`, but it did not worked:
```
   ('enable', '4.5.1', {
        'source_urls': ['https://pypi.python.org/packages/source/e/enable/'],
        'patches': ['enable-4.5.1_numpy.patch'],
        #http://osdir.com/ml/python-enthought-devel/2007-03/msg00351.html
        'prebuildopts': 'env TTFPATH=$EBROOTMATPLOTLIB/lib/python%s/site-packages/matplotlib-%s-py%s-linux-x86_64.egg/matplotlib/mpl_data &&' % (pyshortver, mpl_version, pyshortver),
    }),
```

**Comment by hajgato** [comment]
@boegel: `phonon` could be add as dep. It needs `Qt`, `extra-cmake-modules` from `KDE`, and `GLib`. I am not sure that its worth to bother with it, as it only needs when you want sound or embedded multimedia (like video) in `Qt` apps. I do not see the reality of it via `X11` in HPC environment.... For sure, I will not do it. (`CMake` and `extra-cmake-modules`  versions should be carefully chosen for `Qt` versions, if somebody interested in this project...)

**Comment by hajgato** [comment]
@boegel Can you check this on `golett`, to see whether adding `TTFPATH` solved the one of the problems. Only if you have time, because the PR should wait until the `Qt` issue will be solved

**Comment by boegel** [comment]
Test report by @boegel
**FAILED**
Build succeeded for 5 out of 6 (6 easyconfigs in this PR)
node2646.swalot.os - Linux centos linux 7.2.1511, Intel(R) Xeon(R) CPU E5-2660 v3 @ 2.60GHz, Python 2.7.5
See https://gist.github.com/99756a2916bd31070b36321f41fd3fe2 for a full test report.

**Comment by hajgato** [comment]
@boegel Can you check this again? I added two more deps.

Additionally, I think `Lmod` has problem with 
```
modtclfooter = "prepend-path        TTFPATH $::env(EBROOTMATPLOTLIB)/%s" % ttfpath
```

**Comment by boegel** [comment]
@hajgato test report coming up (using Lua as modules syntax)

Did you run into an actual error with that `modtclfooter` and Lmod?

**Comment by boegel** [comment]
Test report by @boegel
**FAILED**
Build succeeded for 5 out of 6 (6 easyconfigs in this PR)
node2585.golett.os - Linux centos linux 7.2.1511, Intel(R) Xeon(R) CPU E5-2680 v3 @ 2.50GHz, Python 2.7.5
See https://gist.github.com/fdac347addf03fd633e23c682f3b938d for a full test report.

**Comment by hajgato** [comment]
@boegel  I did not run into any `Lua` error. (I do not have `Lua` installed). Anyway, I do not understand the error that you get. I do not have ideas anymore.

**Comment by hajgato** [comment]
@boegel Not to mention the `phonon` issue. I give this PR up.

**Comment by migueldiascosta** [comment]
@hajgato, this PR is being closed for the following reason(s): no activity for > 6 months.
Please don't hesitate to reopen this PR or add a comment if you feel this contribution is still relevant.
For more information on our policy w.r.t. closing PRs, see https://easybuild.readthedocs.io/en/latest/Contributing.html#why-a-pull-request-may-be-closed-by-a-maintainer

**Pull request closed without merging**
