### PR TITLE
{bio}[iccifort/2019.5.281] lancet v1.1.0, BamTools v2.5.1

### PR DESCRIPTION
**Pull request by boegel**
(created using `eb --new-pr`)
requires #10006 (HTSlib)

### CODE REVIEW

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in this PR)
node3117.skitty.os - Linux centos linux 7.7.1908, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz, Python 3.6.8
See https://gist.github.com/b2fa0239216e6dd7b6794346d53025de for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in this PR)
generoso - Linux centos linux 7.6.1810, Intel(R) Xeon(R) CPU E5-2660 v4 @ 2.00GHz, Python 3.6.8
See https://gist.github.com/f09ad4a21fe1d2c07a3e5097ffa89941 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in this PR)
node2549.golett.os - Linux centos linux 7.7.1908, Intel(R) Xeon(R) CPU E5-2680 v3 @ 2.50GHz, Python 2.7.5
See https://gist.github.com/0178b270ea5b8816a7e004026d28aaa9 for a full test report.

**Comment by Micket** [comment]
Can't see any other option for re-triggering tests.

**Comment by Micket** [comment]
Going in, thanks @boegel!

**Pull request merged**
