### PR TITLE
{bio,devel}[foss/2020b] ABySS-2.2.5, sparsehash-2.0.4, VCFtools-0.1.16

### PR DESCRIPTION
**Pull request by eylenth**

### CODE REVIEW

**Comment by branfosj** [comment]
Test report by @branfosj
**FAILED**
Build succeeded for 2 out of 3 (3 easyconfigs in total)
bear-pg0211u03a.bear.cluster - Linux centos linux 7.8.2003, x86_64, Intel(R) Xeon(R) Gold 6248 CPU @ 2.50GHz (cascadelake), Python 3.6.8
See https://gist.github.com/39d85ab2e12f3c45a642f9b9897a5d99 for a full test report.

**Comment by branfosj** [comment]
Hi @eylenth,

Thanks for the contribution. sparsehash and VCFtools are fine.
However, I am hitting a build error with ABySS - related to Boost. See https://gist.github.com/branfosj/196035c2a79ad5b3669e42362c6b4082#file-abyss-2-2-5-foss-2020b_partial-log-L374 for the partial build log.

**Comment by eylenth** [comment]
@branfosj 
Do you know what is going wrong ?
it seems some functions of boost are deprecated for abyss 2.2.5.
Should I use a newer version of Boost ? or downgrade abyss a little bit so it is alligned with the current boost version of the 2020b toolstack.

**Comment by Micket** [comment]
Without digging to deep, i think this might be a the newer GCC complaining about some deprecated C++ feature.
Adding `-Wno-error=deprecated-copy` might be appropriate here. It might just be a boost "bug".

**Comment by branfosj** [comment]
Yes, it builds when `-Wno-error=deprecated-copy` is added to the `CXXFLAGS`.

**Comment by eylenth** [comment]
what is the best way to add `-Wno-error=deprecated-copy` to the `CXXFLAGS` in the easyconfig file of ABySS ?

I was thinking of the following option:
`configopts = 'CFLAGS="$CFLAGS -Wno-error=deprecated-copy"'`

**Comment by branfosj** [comment]
It would have to be added to `CXXFLAGS` and not `CFLAGS`.

You can use `'extra_cxxflags': '-Wno-error=deprecated-copy'` in `toolchainopts`. However we added a fix for this feature recently (https://github.com/easybuilders/easybuild-framework/pull/3571 - this will be in the next EB release), so it may not work for you. If not, then use `configopts = 'CXXFLAGS="$CXXFLAGS -Wno-error=deprecated-copy"'`.

**Comment by eylenth** [comment]
I have added the `configopts = 'CXXFLAGS="$CXXFLAGS -Wno-error=deprecated-copy"'` in the easyconfig file of abyss 2.2.5

**Comment by branfosj** [comment]
@boegelbot please test @ generoso

**Comment by branfosj** [comment]
Test report by @branfosj
**SUCCESS**
Build succeeded for 3 out of 3 (3 easyconfigs in total)
bear-pg0211u03a.bear.cluster - Linux centos linux 7.8.2003, x86_64, Intel(R) Xeon(R) Gold 6248 CPU @ 2.50GHz (cascadelake), Python 3.6.8
See https://gist.github.com/0ff846f6b4839d1eb3f692900686097f for a full test report.

**Comment by branfosj** [comment]
Test report by @branfosj
**SUCCESS**
Build succeeded for 3 out of 3 (3 easyconfigs in total)
bear-pg0211u15a.bear.cluster - Linux Ubuntu 20.04, x86_64, Intel(R) Xeon(R) Gold 6248 CPU @ 2.50GHz (cascadelake), Python 3.8.5
See https://gist.github.com/5902edbb72fe90bc2b5410dc759b77fd for a full test report.

**Review by branfosj — APPROVED** [review]
lgtm

**Comment by branfosj** [comment]
Going in, thanks @eylenth!

**Pull request merged**
