### PR TITLE
{tools}[gfbf/2023a] llama-cpp-python v0.3.2 w/ CUDA 12.1.1

### PR DESCRIPTION
**Pull request by pavelToman**
(created using `eb --new-pr`)
resolves https://github.com/vscentrum/vsc-software-stack/issues/250

### CODE REVIEW

**Comment by pavelToman** [comment]
Test report by @pavelToman
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in total)
node4007.donphan.os - Linux RHEL 8.8, x86_64, Intel(R) Xeon(R) Gold 6240 CPU @ 2.60GHz, 1 x NVIDIA NVIDIA A2, 545.23.08, Python 3.6.8
See https://gist.github.com/pavelToman/ad0ecb2faacff4e03d65159adfe2014c for a full test report.

**Comment by pavelToman** [comment]
@boegelbot please test @ jsc-zen3-a100

**Comment by pavelToman** [comment]
Test report by @pavelToman
**FAILED**
Build succeeded for 2 out of 3 (2 easyconfigs in total)
node4220.shinx.os - Linux RHEL 9.4, x86_64, AMD EPYC 9654 96-Core Processor, Python 3.9.18
See https://gist.github.com/pavelToman/cc3c7854520a974e695231a97e64a76e for a full test report.

**Comment by pavelToman** [comment]
> Test report by @boegelbot **FAILED** Build succeeded for 1 out of 2 (2 easyconfigs in total) cns1 - Linux Rocky Linux 8.9, x86_64, Intel(R) Xeon(R) CPU E5-2667 v3 @ 3.20GHz (haswell), Python 3.6.8 See https://gist.github.com/boegelbot/ab57868a366f4005deb78ac750a2f5cb for a full test report.

CUDA version needs nvidia gpu and drivers to be build. There are no gpu on generoso cns1.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in total)
node3900.accelgor.os - Linux RHEL 9.4, x86_64, AMD EPYC 7413 24-Core Processor (zen3), 1 x NVIDIA NVIDIA A100-SXM4-80GB, 555.42.06, Python 3.9.18
See https://gist.github.com/boegel/7f165e8eca608be8a24731ae30b39bd8 for a full test report.

**Review by boegel — APPROVED** [review]
lgtm

**Comment by boegel** [comment]
Going in, thanks @pavelToman!

**Pull request merged**
