### PR TITLE
add Qt support to VTK 9.3.0

### PR DESCRIPTION
**Pull request by pavelToman**
(created using `eb --new-pr`)

### CODE REVIEW

**Review by boegel — CHANGES_REQUESTED** [review]
@pavelToman Please make the same changes to `VTK-9.3.0-foss-2023b.eb`, to keep things consistent.

**Comment by pavelToman** [comment]
@boegelbot please test @ jsc-zen3

**Review by boegel — APPROVED** [review]
lgtm

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in total)
node3150.skitty.os - Linux RHEL 8.8, x86_64, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz, Python 3.6.8
See https://gist.github.com/boegel/e2d0b96ec087dc128eaf1aa6d74dab36 for a full test report.

**Pull request merged**
