### PR TITLE
fix dependency on FOX Toolkit in SUMO

### PR DESCRIPTION
**Pull request by lexming**
(created using `eb --new-pr`)

The package`FoX` is not related to the FOX toolkit needed by SUMO. This PR adds easyconfigs for the actual FOX toolkit and fixes the dependency in SUMO.

There is also a missing build dependency on Java and the homepage redirects to a new URL.

I'm also adding an updated easyconfig for the last release of SUMO v1.14.1

### CODE REVIEW

**Comment by lexming** [comment]
@boegelbot: please test @ generoso

**Comment by lexming** [comment]
@boegelbot: please test @ generoso

**Comment by SebastianAchilles** [comment]
@boegelbot please test @ jsc-zen2
EB_ARGS="FOX-Toolkit-1.6.57-GCCcore-11.2.0.eb"

**Comment by SebastianAchilles** [comment]
Going in, thanks @lexming!

**Pull request merged**
