### PR TITLE
{lib}[GCCcore/8.2.0] SDL2 v2.0.9

### PR DESCRIPTION
**Pull request by akesandgren**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by akesandgren** [comment]
Test report by @akesandgren
**FAILED**
Build succeeded for 0 out of 1 (1 easyconfigs in this PR)
b-an03.hpc2n.umu.se - Linux ubuntu 16.04, Intel(R) Xeon(R) CPU E5-2690 v4 @ 2.60GHz, Python 2.7.12
See https://gist.github.com/dcf76d93cc47eaa9a77e7aa47a341075 for a full test report.

**Comment by akesandgren** [comment]
Test report by @akesandgren
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
b-an03.hpc2n.umu.se - Linux ubuntu 16.04, Intel(R) Xeon(R) CPU E5-2690 v4 @ 2.60GHz, Python 2.7.12
See https://gist.github.com/90bd35b080dcfb41a00e4e5d80741067 for a full test report.

**Comment by bartoldeman** [comment]
Test report by @bartoldeman
**FAILED**
Build succeeded for 6 out of 11 (1 easyconfigs in this PR)
lg-1r17-n06 - Linux centos 6.6, Intel(R) Xeon(R) CPU E5-2650 0 @ 2.00GHz, Python 2.6.6
See https://gist.github.com/74edab45e2fb38104e9f3b151ade44d3 for a full test report.

**Comment by bartoldeman** [comment]
There are still some issues downloading on CentOS-6. I just did a manual
`wget http://www.freedesktop.org/software/fontconfig/release/fontconfig-2.13.1.tar.gz`
and restarted the build.

**Comment by akesandgren** [comment]
That's weird... Aren't we doing a simple wget too? (or curl or so)

**Comment by bartoldeman** [comment]
Test report by @bartoldeman
**SUCCESS**
Build succeeded for 5 out of 5 (1 easyconfigs in this PR)
lg-1r17-n06 - Linux centos 6.6, Intel(R) Xeon(R) CPU E5-2650 0 @ 2.00GHz, Python 2.6.6
See https://gist.github.com/08cca2ee6cdef52f56535d715067b00b for a full test report.

**Comment by bartoldeman** [comment]
@akesandgren wget is a bit more thorough with SSL, and uses different libraries. I've done some framework changes, but it's a bit of a time sink, for an OS that is getting a bit old (ie. doing the manual wgets takes less time than adapting the framework)

**Comment by bartoldeman** [comment]
Going in, thanks @akesandgren!

**Pull request merged**
