### PR TITLE
{bio}[gompi/2021b,gompi/2022b] AMRFinderPlus v3.11.18

### PR DESCRIPTION
**Pull request by verdurin**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by verdurin** [comment]
Test report by @verdurin
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in total)
easybuild-c7.novalocal - Linux CentOS Linux 7.9.2009, x86_64, Intel Xeon Processor (Skylake, IBRS), Python 3.6.8
See https://gist.github.com/verdurin/db988d560d2282c6f25d547255ada154 for a full test report.

**Comment by verdurin** [comment]
@boegelbot please test @ generoso

**Comment by verdurin** [comment]
@boegelbot please test @ jsc-zen2

**Comment by casparvl** [comment]
Test report by @casparvl
**SUCCESS**
Build succeeded for 7 out of 7 (2 easyconfigs in total)
tcn1.local.snellius.surf.nl - Linux RHEL 8.6, x86_64, AMD EPYC 7H12 64-Core Processor, Python 3.6.8
See https://gist.github.com/casparvl/3af9c1f4c4fc9a76cf990cd5cc0ef3b7 for a full test report.

**Review by casparvl — COMMENTED** [review]
I had to think a bit about what this did:
```
modextrapaths = {'PATH': ''}
```
Initially I thought: is he trying to clear out the `PATH`? That doesn't work, since it prepends... But checking the module file, I realized that EasyBuild expects the relative directory there compared to the root of the installation. I.e. this _adds_ the root of the installation.

Maybe it's good to just add that as a comment, something like:
"# Binaries get installed to the root of the installation, so add that root to the PATH:"

Not essential though, if you feel like leaving it like this, I'm also fine with that.

**Comment by verdurin** [comment]
Adding the explanation makes sense, so that's now done.

**Comment by casparvl** [comment]
Test report by @casparvl
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in total)
tcn1.local.snellius.surf.nl - Linux RHEL 8.6, x86_64, AMD EPYC 7H12 64-Core Processor, Python 3.6.8
See https://gist.github.com/casparvl/94771c1bb419ddeb643d15bddfb2aaa2 for a full test report.

**Review by casparvl — APPROVED** [review]

**Comment by casparvl** [comment]
Going in, thanks @verdurin!

**Pull request merged**
