### PR TITLE
[GCCcore/10.2.0] groff requires makeinfo as a build dep, which requires Perl, which requires groff. Break cyclic redundancy by adding Perl-minimal and makeinfo-minimal.

### PR DESCRIPTION
**Pull request by akesandgren**
(created using `eb --new-pr`)

Depends on https://github.com/easybuilders/easybuild-easyblocks/pull/2474

### CODE REVIEW

**Comment by akesandgren** [comment]
Test report by @akesandgren
Using easyblocks from PR(s) https://github.com/easybuilders/easybuild-easyblocks/pull/2474
**SUCCESS**
Build succeeded for 9 out of 9 (9 easyconfigs in total)
b-an02.hpc2n.umu.se - Linux Ubuntu 20.04, x86_64, Intel(R) Xeon(R) CPU E5-2690 v4 @ 2.60GHz, Python 3.8.5
See https://gist.github.com/75d572ebf96d9aa46a97190f51a70562 for a full test report.

**Comment by SebastianAchilles** [comment]
Test report by @sebastianachilles
Using easyblocks from PR(s) https://github.com/easybuilders/easybuild-easyblocks/pull/2474
**SUCCESS**
Build succeeded for 9 out of 9 (9 easyconfigs in total)
centos8-eb - Linux centos linux 8.3.2011, x86_64, Intel(R) Core(TM) i7-8700 CPU @ 3.20GHz (skylake) (skylake), Python 3.6.8
See https://gist.github.com/ff791d0eca1744743cbfe5870eb4c52d for a full test report.

**Comment by SebastianAchilles** [comment]
Test report by @sebastianachilles
Using easyblocks from PR(s) https://github.com/easybuilders/easybuild-easyblocks/pull/2474
**SUCCESS**
Build succeeded for 9 out of 9 (9 easyconfigs in total)
rocky8-eb - Linux rocky linux 8.4, x86_64, Intel(R) Core(TM) i7-6900K CPU @ 3.20GHz (broadwell) (broadwell), Python 3.6.8
See https://gist.github.com/75a985e181808966dfd4182fd84d9632 for a full test report.

**Comment by verdurin** [comment]
Test report by @verdurin
**SUCCESS**
Build succeeded for 3 out of 3 (3 easyconfigs in total)
easybuild-c7.novalocal - Linux centos linux 7.9.2009, x86_64, Intel Xeon Processor (Skylake, IBRS), Python 3.6.8
See https://gist.github.com/5be9e1cde8c011720d4ee27f848be099 for a full test report.

**Review by SebastianAchilles — APPROVED** [review]
lgtm

**Comment by SebastianAchilles** [comment]
@boegelbot please test @ generoso

**Review by SebastianAchilles — APPROVED** [review]
lgtm

**Comment by SebastianAchilles** [comment]
Going in, thanks @akesandgren!

**Pull request merged**
