### PR TITLE
{bio}[foss/2021a] EMBOSS v6.6.0

### PR DESCRIPTION
**Pull request by smoretti**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by boegel** [comment]
@smoors Can you clarify why you closed this?

**Comment by smoretti** [comment]
Sorry, it needs first the libharu update #13939

**Comment by boegel** [comment]
@smoretti It's fine to keep this PR open even if it needs other PRs to be merged first: just mention the required PRs in the PR description, and let the tests fail (and ignore the bot).

Once #13939 is merged, you can update this PR easily (and re-trigger the tests) using `eb --sync-pr-with-develop`

**Comment by smoretti** [comment]
We have removed the branch related to the PR on our side, and I cannot reopen this PR.

I will open a new one

**Comment by boegel** [comment]
@smoretti No problem!

(follow-up in #13944)

**Pull request closed without merging**
