### PR TITLE
{vis}[foss/2018b] FFmpeg v3.4.5

### PR DESCRIPTION
**Pull request by jose-d**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by jose-d** [comment]
Test report by @jose-d
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
koios2 - Linux centos linux 7.3.1611, Intel(R) Xeon(R) Gold 6130 CPU @ 2.10GHz, Python 2.7.5
See https://gist.github.com/dca6391c303eb67a579ea75db17e93ed for a full test report.

**Comment by jose-d** [comment]
_..motivation for this PR is actually `OpenCV` module for foss2018b.._

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
node3136.skitty.os - Linux centos linux 7.5.1804, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz, Python 2.7.5
See https://gist.github.com/3172ca189c71048133ed24485e971ee0 for a full test report.

**Comment by boegel** [comment]
Going in, thanks @jose-d!

**Comment by jose-d** [comment]
> @jose-d This looks good to go, but isn't`OpenCV` compatible yet with `FFmpeg` 4.1?

@boegel: most likely yes. But as it would be AFAIK first `OpenCV` + `FFmpeg` v4+ easybuild here AND I saw the openCV usage in project of my ${user} is quite limited, I was not brave enough to go with new major release and claim it as working.

**Comment by boegel** [comment]
@jose-d Based on https://github.com/opencv/opencv/commit/d4f038dfcc69e3941a92cf76b72e294c0412867a, FFmpeg 4.1 should work fine with OpenCV 4.0.1 or more recent

**Pull request merged**
