### PR TITLE
Fix TensorFlow 2.7.1 on POWER

### PR DESCRIPTION
**Pull request by Flamefire**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by Flamefire** [comment]
Test report by @Flamefire
**FAILED**
Build succeeded for 0 out of 2 (2 easyconfigs in total)
taurusml3 - Linux RHEL 7.6, POWER, 8335-GTX (power9le), 6 x NVIDIA Tesla V100-SXM2-32GB, 440.64.00, Python 2.7.5
See https://gist.github.com/36447fbd11f7e039ad569ef28d0e76f5 for a full test report.

**Comment by Flamefire** [comment]
Test report by @Flamefire
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in total)
taurusi8003 - Linux CentOS Linux 7 (Core), x86_64, AMD EPYC 7352 24-Core Processor, 8 x NVIDIA NVIDIA A100-SXM4-40GB, 470.57.02, Python 3.10.4
See https://gist.github.com/05783d4bf30b9af751f7a30716130eb4 for a full test report.

**Comment by Flamefire** [comment]
Test report by @Flamefire
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in total)
taurusa12 - Linux CentOS Linux 7.7.1908, x86_64, Intel(R) Xeon(R) CPU E5-2603 v4 @ 1.70GHz (broadwell), 3 x NVIDIA GeForce GTX 1080 Ti, 460.32.03, Python 2.7.5
See https://gist.github.com/976d5f02eaa3a8626476c2dda3ea0ce6 for a full test report.

**Comment by Flamefire** [comment]
Test report by @Flamefire
**FAILED**
Build succeeded for 1 out of 2 (2 easyconfigs in total)
taurusml24 - Linux RHEL 7.6, POWER, 8335-GTX (power9le), 6 x NVIDIA Tesla V100-SXM2-32GB, 440.64.00, Python 2.7.5
See https://gist.github.com/0863e186d4f413b3f9369615b6c11f05 for a full test report.

**Comment by Flamefire** [comment]
Test report by @Flamefire
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in total)
taurusi8003 - Linux CentOS Linux 7.9.2009, x86_64, AMD EPYC 7352 24-Core Processor (zen2), 8 x NVIDIA NVIDIA A100-SXM4-40GB, 470.57.02, Python 2.7.5
See https://gist.github.com/82a6c976b93a943e18d33dd33fae0156 for a full test report.

**Comment by Flamefire** [comment]
Test report by @Flamefire
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in total)
taurusi8006 - Linux CentOS Linux 7.9.2009, x86_64, AMD EPYC 7352 24-Core Processor (zen2), 8 x NVIDIA NVIDIA A100-SXM4-40GB, 470.57.02, Python 2.7.5
See https://gist.github.com/c868d5c8a5c2b3a9702414c404bc859e for a full test report.

**Comment by Flamefire** [comment]
Test report by @Flamefire
**FAILED**
Build succeeded for 0 out of 2 (2 easyconfigs in total)
taurusml20 - Linux RHEL 7.6, POWER, 8335-GTX (power9le), 6 x NVIDIA Tesla V100-SXM2-32GB, 440.64.00, Python 2.7.5
See https://gist.github.com/7673bd767c52989b22d3d8bf87fd6fac for a full test report.

**Comment by Flamefire** [comment]
Test report by @Flamefire
**FAILED**
Build succeeded for 1 out of 2 (2 easyconfigs in total)
taurusa12 - Linux CentOS Linux 7.7.1908, x86_64, Intel(R) Xeon(R) CPU E5-2603 v4 @ 1.70GHz (broadwell), 3 x NVIDIA GeForce GTX 1080 Ti, 460.32.03, Python 2.7.5
See https://gist.github.com/b6ea494014a6a03b7c17ebc70ee4c3b2 for a full test report.

**Comment by Flamefire** [comment]
@boegel I'd really love to get this into the next release as it was a lot of time spent and this is now the latest version of TensorFlow working on PPC. 2.8.4 doesn't has a CUDA version and doesn't work on PPC and 2.9 isn't ready yet.

Test report coming up, need to install to /tmp as our clusters filesystem got full hence the (now deleted) failed test reports. But I tested it manually already so I expect no failures.

**Comment by Flamefire** [comment]
Test report by @Flamefire
Using easyblocks from PR(s) https://github.com/easybuilders/easybuild-easyblocks/pull/2854
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in total)
taurusml5 - Linux RHEL 7.6, POWER, 8335-GTX (power9le), 6 x NVIDIA Tesla V100-SXM2-32GB, 440.64.00, Python 2.7.5
See https://gist.github.com/dca0a36498f60e13fc50c62ee493894c for a full test report.

**Comment by Mohammedalanizi92** [comment]
> (created using `eb --new-pr`)

**Comment by Mohammedalanizi92** [comment]
> (created using `eb --new-pr`)

**Comment by Flamefire** [comment]
@boegel What is missing here that it gets postponed again and again? https://github.com/easybuilders/easybuild-easyconfigs/pull/16795#issuecomment-1373561015 shows it is working on PPC which is the purpose of this PR and the patches only affect the PPC build.

**Comment by branfosj** [comment]
Test report by @branfosj
**FAILED**
Build succeeded for 1 out of 2 (2 easyconfigs in total)
bear-pg0203u29a.bear.cluster - Linux RHEL 8.6, x86_64, Intel(R) Xeon(R) Platinum 8360Y CPU @ 2.40GHz (icelake), 1 x NVIDIA NVIDIA A100-SXM4-80GB, 520.61.05, Python 3.6.8
See https://gist.github.com/branfosj/75b2224e9359a85b84d3424f6fa94c47 for a full test report.

**Comment by Flamefire** [comment]
> Test report by @branfosj **FAILED**

-->
`ERROR: /dev/shm/branfosj/build-up-EL8/TensorFlow/2.7.1/foss-2021b/TensorFlow/bazel-root/2b861e6b2b884d30743b7f211eb4a8d3/external/rules_cuda/cuda/BUILD:130:20: every rule of type cuda_toolchain_info implicitly depends upon the target '@local_cuda//:cuda/bin/nvcc', but this target could not be found because of: no such target '@local_cuda//:cuda/bin/nvcc': target 'cuda/bin/nvcc' not declared in package '' defined by /dev/shm/branfosj/build-up-EL8/TensorFlow/2.7.1/foss-2021b/TensorFlow/bazel-root/2b861e6b2b884d30743b7f211eb4a8d3/external/local_cuda/BUILD`

This doesn't make sense for the non-cuda build. Some left-overs from another build or other temporary failure? Or space issue in /dev/shm building 2 TFs?

**Review by branfosj — APPROVED** [review]
I've tested the CPU-only version again and it failed on a GPU node (fresh login to the node). I also have a build running on a CPU-only node and it has not had the same issue. Testing further, this fault also occurs without the changes in this PR, which is not a surprise. So, I'm happy to approve this.

**Comment by branfosj** [comment]
Test report by @branfosj
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
bear-pg0105u03a.bear.cluster - Linux RHEL 8.6, x86_64, Intel(R) Xeon(R) Platinum 8360Y CPU @ 2.40GHz (icelake), Python 3.6.8
See https://gist.github.com/branfosj/fb7b88fb634c21ab235d24d31e3b883e for a full test report.

**Comment by branfosj** [comment]
Going in, thanks @Flamefire!

**Pull request merged**
