### PR TITLE
use new custom easyblock in CMake easyconfigs

### PR DESCRIPTION
**Pull request by Flamefire**
(created using `eb --new-pr`)

- [x] needs https://github.com/easybuilders/easybuild-easyblocks/pull/1974

### CODE REVIEW

**Comment by Flamefire** [comment]
Test report by @Flamefire
**SUCCESS**
Build succeeded for 66 out of 66 (66 easyconfigs in this PR)
taurusi6605.taurus.hrsk.tu-dresden.de - Linux RHEL 7.7, Intel(R) Xeon(R) CPU E5-2680 v3 @ 2.50GHz, Python 2.7.5
See https://gist.github.com/cb127b68076ac6fb4b50fafadc9a812e for a full test report.

**Comment by Flamefire** [comment]
@boegel Thanks for the additions. You may want to simply revert https://github.com/easybuilders/easybuild-easyconfigs/pull/9923/commits/ca79a3f41298fa18fc7c63879eb402db680e606d instead of https://github.com/easybuilders/easybuild-easyconfigs/pull/9923/commits/8708dfef91e9e02cbdf5c7f5ce86769532fce60d

I removed it because of the deprecated toolchains

**Comment by boegel** [comment]
> @boegel Thanks for the additions. You may want to simply revert [ca79a3f](https://github.com/easybuilders/easybuild-easyconfigs/commit/ca79a3f41298fa18fc7c63879eb402db680e606d) instead of [8708dfe](https://github.com/easybuilders/easybuild-easyconfigs/commit/8708dfef91e9e02cbdf5c7f5ce86769532fce60d)
> 
> I removed it because of the deprecated toolchains

I overlooked the checksums in those two old `CMake` easyconfigs, added them back.

I'll also get a full test report uploaded, it'll take a while but it should work fine...

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 68 out of 68 (68 easyconfigs in this PR)
node2412.golett.os - Linux centos linux 7.7.1908, Intel(R) Xeon(R) CPU E5-2680 v3 @ 2.50GHz, Python 2.7.5
See https://gist.github.com/78190b70e1a825bd056bba9537b5bb1f for a full test report.

**Comment by boegel** [comment]
Going in, thanks @Flamefire!

**Pull request merged**
