### PR TITLE
{devel}[gompi/2023a] amdahl v0.3.1

### PR DESCRIPTION
**Pull request by ocaisa**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by ocaisa** [comment]
@boegelbot please test @ generoso

**Comment by ocaisa** [comment]
@boegelbot please test @ jsc-zen3

**Comment by ocaisa** [comment]
@boegelbot please test @ jsc-zen3

**Comment by ocaisa** [comment]
@boegelbot please test @ generoso

**Comment by ocaisa** [comment]
@boegelbot please test @ jsc-zen3

**Review by boegel — APPROVED** [review]
lgtm

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
node3117.skitty.os - Linux RHEL 8.8, x86_64, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz, Python 3.6.8
See https://gist.github.com/boegel/2a7290ceb66d2c0e7642085f3e340f9d for a full test report.

**Comment by boegel** [comment]
Going in, thanks @ocaisa!

**Pull request merged**
