### PR TITLE
{math}[system/system] Mathematica v13.1.0

### PR DESCRIPTION
**Pull request by boegel**
(created using `eb --new-pr`)
requires:
* https://github.com/easybuilders/easybuild-easyblocks/pull/2896

### CODE REVIEW

**Comment by boegel** [comment]
Test report by @boegel
Using easyblocks from PR(s) https://github.com/easybuilders/easybuild-easyblocks/pull/2896
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
node3704.slaking.os - Linux RHEL 8.6, x86_64, Intel(R) Xeon(R) CPU E5-2680 v3 @ 2.50GHz (haswell), Python 3.6.8
See https://gist.github.com/08aec4338033d01c65a882fe45274d92 for a full test report.

**Review by Micket — APPROVED** [review]
lgtm

**Comment by verdurin** [comment]
Going in, thanks @boegel!

**Comment by Micket** [comment]
Just so you know, the easyblock isn't merged yet (and it had failing older builds from @boegel)

**Comment by verdurin** [comment]
Okay, assumed it was fine from the comment. Should have noticed that the easyblock wasn't purple yet.

**Pull request merged**
