### PR TITLE
{lib}[fosscuda/2019b] CuPy v8.2.0 w/ Python 3.7.4

### PR DESCRIPTION
**Pull request by boegel**
(created using `eb --new-pr`)

requires #11914 (cuTENSOR)

### CODE REVIEW

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
node3300.joltik.os - Linux centos linux 7.9.2009, x86_64, Intel(R) Xeon(R) Gold 6242 CPU @ 2.80GHz (cascadelake), Python 3.6.8
See https://gist.github.com/4b7f13888ce9757371b90586aa869a37 for a full test report.

**Review by branfosj — CHANGES_REQUESTED** [review]
As we have cuDNN and NCCL available should we have them as dependencies?
```
  Modules:
    cuda      : Yes (version 10010)
    cusolver  : Yes
    cudnn     : No
      -> Include files not found: ['cudnn.h']
      -> Check your CFLAGS environment variable.
    nccl      : No
      -> Include files not found: ['nccl.h']
      -> Check your CFLAGS environment variable.
    nvtx      : Yes
    cutensor  : No
      -> Include files not found: ['cutensor.h']
      -> Check your CFLAGS environment variable.
    cub       : Yes (version <unknown>)
    thrust    : Yes (version 100906)
  
  WARNING: Some modules could not be configured.
  CuPy will be installed without these modules.
  Please refer to the Installation Guide for details:
  https://docs.cupy.dev/en/stable/install.html
```

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
node3300.joltik.os - Linux centos linux 7.9.2009, x86_64, Intel(R) Xeon(R) Gold 6242 CPU @ 2.80GHz (cascadelake), Python 3.6.8
See https://gist.github.com/a38ea632bcf951145c5678595aad0826 for a full test report.

**Review by branfosj — DISMISSED** [review]
lgtm

**Comment by boegel** [comment]
With the `cuTENSOR` dep added:

```
    Modules:
      cuda      : Yes (version 10010)
      cusolver  : Yes
      cudnn     : Yes (version 7604)
      nccl      : Yes (version 2408)
      nvtx      : Yes
      cutensor  : Yes (version 1202)
      cub       : Yes (version <unknown>)
      thrust    : Yes (version 100906)
```

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
node3300.joltik.os - Linux centos linux 7.9.2009, x86_64, Intel(R) Xeon(R) Gold 6242 CPU @ 2.80GHz (cascadelake), Python 3.6.8
See https://gist.github.com/b8a505659b1ac0b7b9771efbf87d1cc3 for a full test report.

**Comment by branfosj** [comment]
closing / reopening to rerun the tests now that #11914 is merged.

**Review by branfosj — APPROVED** [review]
lgtm

**Comment by branfosj** [comment]
Test report by @branfosj
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
bear-pg0212u15b.bear.cluster - Linux centos linux 8.2.2004, x86_64, Intel(R) Xeon(R) CPU E5-2640 v4 @ 2.40GHz (broadwell), Python 3.6.8
See https://gist.github.com/41ef550dd4866c2e3668265ac52e585a for a full test report.

**Comment by branfosj** [comment]
Going in, thanks @boegel!

**Pull request merged**
