### PR TITLE
{bio}[foss/2019b] FSL v6.0.4 w/ Python 3.7.4

### PR DESCRIPTION
**Pull request by hrnagel**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by lexming** [comment]
Test report by @lexming
**SUCCESS**
Build succeeded for 6 out of 6 (1 easyconfigs in total)
node371.hydra.os - Linux centos linux 7.9.2009, x86_64, Intel(R) Xeon(R) Gold 6148 CPU @ 2.40GHz, Python 2.7.5
See https://gist.github.com/0827806c71d367cf602ccb88de43ba4d for a full test report.

**Comment by migueldiascosta** [comment]
@boegelbot please test @ generoso

**Comment by hrnagel** [comment]
There is something that the tests don't catch. Because of the way that FSL and the easyblock is designed, the install-dir also becomes the build-dir. This results in the build-dir for fslpy to be left in the install-dir, after the installation is complete. EasyBuild also creates the lib/python3.7/site-packages directories in the install-dir, even though these should actually be created inside of the fsl directory. The fix_build patch therefore adds code to make certain that these directories exist inside of the fsl directory. After fslpy has been installed, there is no "hook" in the FSL easyblock to add code for removing the unnecessary fslpy build directory and the empty lib/python3.7/site-packages directory in install-dir, so they get left behind in install-dir.

**Comment by verdurin** [comment]
Test report by @verdurin
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
nuc.lan - Linux Fedora 33, x86_64, Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz, Python 3.9.2
See https://gist.github.com/692a8c3d8c51e97a0f9b037c34ac5a62 for a full test report.

**Comment by mboisson** [comment]
Thanks to the patches in this PR, I wrote this recipe on Compute Canada's stack (Relies on python wheels). If this can be useful, feel free to reuse: 

https://github.com/ComputeCanada/easybuild-easyconfigs/commit/34e68c8f773047e0d1af39f77457d13faedd1197

https://github.com/ComputeCanada/easybuild-easyblocks/commit/4a1c0e6cc051546a302ef8a19d108c7324f11185

**Comment by hrnagel** [comment]
> Thanks to the patches in this PR, I wrote this recipe on Compute Canada's stack (Relies on python wheels). If this can be useful, feel free to reuse:
> 
> [ComputeCanada@34e68c8](https://github.com/ComputeCanada/easybuild-easyconfigs/commit/34e68c8f773047e0d1af39f77457d13faedd1197)
> 
> [ComputeCanada/easybuild-easyblocks@4a1c0e6](https://github.com/ComputeCanada/easybuild-easyblocks/commit/4a1c0e6cc051546a302ef8a19d108c7324f11185)

Thank you for your contribution. While trying to port these files to standard EasyBuild, I ran into 2 problems:

1. When trying to use fosscuda/2020a: there is no GCC 9.3.0 version of wxWidgets in
https://github.com/easybuilders/easybuild-easyconfigs/tree/develop/easybuild/easyconfigs/w/wxWidgets

2. When trying to use fosscuda/2020b: there is no fosscuda/2020b version of VTK in
https://github.com/easybuilders/easybuild-easyconfigs/tree/develop/easybuild/easyconfigs/v/VTK

**Review by verdurin — APPROVED** [review]
Looks fine.
Looks fine.

**Comment by verdurin** [comment]
I see no reason not to merge this - I think I just lost track of it.
In fact, I would like to create an updated version.

**Comment by verdurin** [comment]
Going in, thanks @hrnagel!

**Pull request merged**
