### PR TITLE
Use modextrapaths instead of modextravars in OpenMM easyconfig

### PR DESCRIPTION
**Pull request by pescobar**

### CODE REVIEW

**Comment by verdurin** [comment]
@pescobar tried to run a test build of this, and the building of the dependency `OpenBLAS/0.2.6-gompi-1.4.10-LAPACK-3.4.2` failed...

**Comment by verdurin** [comment]
Test report by @verdurin
**FAILED**
Build succeeded for 4 out of 18 (1 easyconfigs in this PR)
ca014.camp.thecrick.org - Linux centos linux 7.3.1611, Intel(R) Xeon(R) CPU E5-2640 v3 @ 2.60GHz, Python 2.7.5
See https://gist.github.com/8339437fea3e690b489212e18256462c for a full test report.

**Comment by boegel** [comment]
@verdurin Yes, that's probably because that version of OpenBLAS is too old for the processor architecture of your system... We should deprecate/archive `goolf/1.4.10` soon.

This change makes perfect sense though, and it doesn't affect the build itself, only the generated module, so testing with `--module-only --force` is actually sufficient here.

(full) test report from our Sandy Bridge-based cluster coming up...

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
node2073.delcatty.os - Linux centos linux 7.3.1611, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.7.5
See https://gist.github.com/58fa418cdb9c59e1cb92c20c75e38588 for a full test report.

**Comment by boegel** [comment]
Going in, thanks @pescobar!

**Pull request merged**
