### PR TITLE
{chem}[intel/2021a] CP2K v9.1

### PR DESCRIPTION
**Pull request by branfosj**
(created using `eb --new-pr`)

Draft while we check the tests and dependencies.

### CODE REVIEW

**Comment by branfosj** [comment]
Test report by @branfosj
**SUCCESS**
Build succeeded for 4 out of 4 (1 easyconfigs in total)
bear-pg0211u08b.bear.cluster - Linux RHEL 8.5, x86_64, Intel(R) Xeon(R) Gold 6248 CPU @ 2.50GHz (cascadelake), Python 3.6.8
See https://gist.github.com/4ec91af68a42e55c2fbbf92d80b67611 for a full test report.

**Comment by boegel** [comment]
@branfosj Any updates on this?

**Comment by branfosj** [comment]
```
--------------------------------- Summary --------------------------------
Number of FAILED  tests 3621
Number of WRONG   tests 0
Number of CORRECT tests 7
Total number of   tests 3628
--------------------------------------------------------------------------
Number of memory  leaks 0
--------------------------------------------------------------------------
GREPME 3621 0 7 0 3628

Summary: correct: 7 / 3628; failed: 3621; 70min
Status: FAILED
```

Here I am seeing an issue with OpenMP jobs and the FFTW we build. If we remove the EB built FFTW dependency then I see:

```
--------------------------------- Summary --------------------------------
Number of FAILED  tests 1
Number of WRONG   tests 5
Number of CORRECT tests 3622
Total number of   tests 3628
--------------------------------------------------------------------------
Number of memory  leaks 0
--------------------------------------------------------------------------
GREPME 1 5 3622 0 3628

Summary: correct: 3622 / 3628; wrong: 5; failed: 1; 225min
Status: FAILED
```

The wrong results ones are similar to the foss version, with the tolerances being missed by about the same amounts.

**Comment by branfosj** [comment]
I'm not working on this, so I've closed the PR.

**Pull request closed without merging**
