### PR TITLE
also define $JUPYTER_CONFIG_PATH in IPython and JupyterLab easyconfigs

### PR DESCRIPTION
**Pull request by lexming**
(created using `eb --new-pr`)

`JUPYTER_CONFIG_PATH` has to be populated with all `etc/jupyter` folders. The config files in there are needed to initialize any notebook extensions.
See https://docs.jupyter.org/en/latest/use/jupyter-directories.html#envvar-JUPYTER_CONFIG_PATH

### CODE REVIEW

**Comment by lexming** [comment]
@boegelbot: please test @ generoso

**Comment by lexming** [comment]
Updated to also include JupyterLab

**Comment by lexming** [comment]
@boegelbot: please test @ generoso

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 6 out of 6 (6 easyconfigs in total)
node3103.skitty.os - Linux RHEL 8.6, x86_64, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz (skylake_avx512), Python 3.6.8
See https://gist.github.com/3966e002743db032b751a1a8cefc0e2c for a full test report.

**Comment by boegel** [comment]
Going in, thanks @lexming!

**Pull request merged**
