### PR TITLE
{tools}[GCCcore/10.2.0] Archive-Zip v1.68

### PR DESCRIPTION
**Pull request by lexming**
(created using `eb --new-pr`)

Needed by https://github.com/easybuilders/easybuild-easyconfigs/pull/12553

### CODE REVIEW

**Review by Micket — DISMISSED** [review]
lgtm

**Comment by Micket** [comment]
Was both this and #12627 both needed for VEP?

**Comment by lexming** [comment]
Test report by @lexming
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
node374.hydra.os - Linux centos linux 7.9.2009, x86_64, Intel(R) Xeon(R) Gold 6148 CPU @ 2.40GHz, Python 2.7.5
See https://gist.github.com/6c534c543ce47b255378c123748c2887 for a full test report.

**Comment by lexming** [comment]
@Micket yes, both PRs are needed by VEP v103.1

**Comment by Micket** [comment]
Test report by @Micket
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
vera-c1 - Linux centos linux 7.9.2009, x86_64, Intel Xeon Processor (Skylake), Python 2.7.5
See https://gist.github.com/849d2fc34de0a0ab177176c154e992d2 for a full test report.

**Comment by Micket** [comment]
@boegelbot please test @ generoso

**Review by Micket — APPROVED** [review]
lgtm

**Comment by Micket** [comment]
Going in, thanks @lexming!

**Pull request merged**
