### PR TITLE
{lang}[gompi/2020a] SOCI v4.0.1

### PR DESCRIPTION
**Pull request by branfosj**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by migueldiascosta** [comment]
@branfosj I suppose this is using `gompi` only because of `Boost`? If so, what about
```diff
--- SOCI-4.0.1-gompi-2020a.eb	2021-01-26 10:19:12.351218377 +0800
+++ SOCI-4.0.1-GCCcore-9.3.0.eb	2021-01-26 10:21:50.369736807 +0800
@@ -7,16 +7,19 @@
 description = """SOCI is a database access library for C++ that makes the illusion of embedding SQL queries in the
  regular C++ code, staying entirely within the Standard C++."""
 
-toolchain = {'name': 'gompi', 'version': '2020a'}
+toolchain = {'name': 'GCCcore', 'version': '9.3.0'}
 
 source_urls = ['https://github.com/SOCI/soci/archive']
 sources = ['v%(version)s.tar.gz']
 checksums = ['1979b4084ba644125da29dbfbd132798f7742a56caf5a0edb16756a5dbad0f31']
 
-builddependencies = [('CMake', '3.16.4')]
+builddependencies = [
+    ('binutils', '2.34'),
+    ('CMake', '3.16.4'),
+]
 
 dependencies = [
-    ('Boost', '1.72.0'),
+    ('Boost', '1.72.0', '-no_mpi'),
     ('SQLite', '3.31.1'),
     ('PostgreSQL', '12.4'),
 ]
```

**Comment by branfosj** [comment]
> @branfosj I suppose this is using `gompi` only because of `Boost`? If so, what about

Yes, that should work. We'll also have to switch the new RStudio-Server (#12044) to use that Boost variant, as this is required as a dependency.

**Comment by branfosj** [comment]
Test report by @branfosj
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
bear-pg0211u03a.bear.cluster - Linux centos linux 7.8.2003, x86_64, Intel(R) Xeon(R) Gold 6248 CPU @ 2.50GHz (cascadelake), Python 3.6.8
See https://gist.github.com/739a480c13d68cb9b5f85bf0519f0551 for a full test report.

**Comment by migueldiascosta** [comment]
Test report by @migueldiascosta
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
sms - Linux centos linux 7.6.1810, x86_64, AMD EPYC 7601 32-Core Processor (zen), Python 2.7.5
See https://gist.github.com/ffdfccf30aa037308286df1a5175945f for a full test report.

**Comment by migueldiascosta** [comment]
@boegelbot please test @ generoso

**Review by migueldiascosta — APPROVED** [review]
lgtm

**Comment by migueldiascosta** [comment]
Going in, thanks @branfosj!

**Pull request merged**
