### PR TITLE
{chem,data,math}[iomkl/2019b] QuantumESPRESSO v6.7, HDF5 v1.10.5, ELPA v2019.11.001

### PR DESCRIPTION
**Pull request by branfosj**
(created using `eb --new-pr`)

`iomkl` version of QuantumESPRESSO, with deps.

### CODE REVIEW

**Comment by branfosj** [comment]
@boegelbot please test @ generoso

**Comment by branfosj** [comment]
Test report by @branfosj
**SUCCESS**
Build succeeded for 3 out of 3 (3 easyconfigs in total)
bear-pg0211u38b.bear.cluster - Linux centos linux 8.2.2004, x86_64, Intel(R) Xeon(R) Gold 6248 CPU @ 2.50GHz (cascadelake), Python 3.6.8
See https://gist.github.com/b2cd15a6121dc646c908ac22baee44a4 for a full test report.

**Review by migueldiascosta — APPROVED** [review]
lgtm

**Comment by migueldiascosta** [comment]
Going in, thanks @branfosj!

**Pull request merged**
