### PR TITLE
{bio}[system/system] Schrodinger v2022-3

### PR DESCRIPTION
**Pull request by Micket**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by Micket** [comment]
Test report by @Micket
**FAILED**
Build succeeded for 0 out of 1 (1 easyconfigs in total)
alvis-c1 - Linux Rocky Linux 8.5, x86_64, Intel Xeon Processor (Skylake), Python 3.6.8
See https://gist.github.com/5a15cb95fdb8f15323b86fd6bdda8391 for a full test report.

**Comment by Micket** [comment]
Test report by @Micket
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
alvis-c1 - Linux Rocky Linux 8.5, x86_64, Intel Xeon Processor (Skylake), Python 3.6.8
See https://gist.github.com/a5f891806dec0d3278f0d3d2a736750e for a full test report.

**Comment by Micket** [comment]
Seems to be tripping up on libnsl.so. It used to be part of glibc, but in Rocky 8 it's a separate package (libnsl).
I suppose this should just be viewed as a standard OS dependency then. I can't really put that into osdeps though since that it's not the same on CentOS7

**Comment by boegel** [comment]
> Seems to be tripping up on libnsl.so. It used to be part of glibc, but in Rocky 8 it's a separate package (libnsl). I suppose this should just be viewed as a standard OS dependency then. I can't really put that into osdeps though since that it's not the same on CentOS7

Let's just add a comment in the easyconfig file on this then, to at least leave some sort of clue?

**Comment by Micket** [comment]
Test report by @Micket
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
alvis-c1 - Linux Rocky Linux 8.5, x86_64, Intel Xeon Processor (Skylake), Python 3.6.8
See https://gist.github.com/762978f99df685cd0db18e479d2e60a0 for a full test report.

**Review by boegel — APPROVED** [review]
lgtm

**Comment by boegel** [comment]
Going in, thanks @Micket!

**Pull request merged**
