### PR TITLE
{lib}[GCCcore/9.3.0] libfabric v1.10.1

### PR DESCRIPTION
**Pull request by bartoldeman**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by bartoldeman** [comment]
Note that unlike the 1.9.1 easyconfig this uses the official release tarball instead of the automatically generated github tarball, and so autoconf is not necessary.

**Comment by verdurin** [comment]
Test report by @verdurin
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
easybuild.novalocal - Linux centos linux 7.8.2003, Intel Xeon Processor (Skylake, IBRS), Python 2.7.5
See https://gist.github.com/e6d0956de247e53efea532ebf307d329 for a full test report.

**Comment by verdurin** [comment]
@bartoldeman any chance of a test report?

**Comment by Micket** [comment]
Test report by @Micket
**SUCCESS**
Build succeeded for 2 out of 2 (1 easyconfigs in this PR)
hebbe-c1 - Linux centos linux 7.7.1908, Intel Core Processor (Haswell, no TSX), Python 2.7.5
See https://gist.github.com/98a53b41ee3db8d7ff26d2a5b4ae3109 for a full test report.

**Comment by bartoldeman** [comment]
Test report by @bartoldeman
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
build-node.computecanada.ca - Linux centos linux 7.8.2003, Intel Xeon Processor (Skylake, IBRS), Python 3.7.7
See https://gist.github.com/5000128983b9dbac67b8854827bd6fbd for a full test report.

**Comment by verdurin** [comment]
Going in, thanks @bartoldeman!

**Pull request merged**
