### PR TITLE
[QCA 2.1.0] Update source URLs as old ones are not available anymore

### PR DESCRIPTION
**Pull request by Flamefire**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by smoors** [comment]
@crubb just curious, why such an old version and toolchain?

**Comment by Flamefire** [comment]
I'm currently testing all CMake based ECs. This is where I detected this error. Alternative would be to remove this EC. But the fix is easy, so...

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in this PR)
node2461.golett.os - Linux centos linux 7.7.1908, Intel(R) Xeon(R) CPU E5-2680 v3 @ 2.50GHz, Python 2.7.5
See https://gist.github.com/e139c8b37f99a8b61212e8be661e7738 for a full test report.

**Comment by boegel** [comment]
Going in, thanks @Flamefire!

**Pull request merged**
