### PR TITLE
fix GBprocesS easyconfig by switching to source tarball created using git_config

### PR DESCRIPTION
**Pull request by boegel**
(created using `eb --new-pr`)

fix for:

```
LookupError: setuptools-scm was unable to detect version for '/tmp/eb-bu9xgdr0/pip-req-build-80eo7sp5'.
```

I think this is caused by starting to use `pip` to install all extensions included with `Python` (see #12650)

### CODE REVIEW

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
node3103.skitty.os - Linux CentOS Linux 7.9.2009, x86_64, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz, Python 3.6.8
See https://gist.github.com/a03534583dcf47f6f715b08e9e6600ea for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
node3524.doduo.os - Linux RHEL 8.4, x86_64, AMD EPYC 7552 48-Core Processor (zen2), Python 3.6.8
See https://gist.github.com/c8fc98c5c126e9bd826b0000dfd0dda8 for a full test report.

**Comment by boegel** [comment]
@boegelbot please test @ generoso

**Comment by boegel** [comment]
@boegelbot please test @ generoso

**Comment by boegel** [comment]
> @boegel what's the difference between the commit and the archive? also, can you add a comment saying why the archive does not work?

@smoors fixed in 961f3a2

**Comment by smoors** [comment]
Test report by @smoors
**SUCCESS**
Build succeeded for 3 out of 3 (1 easyconfigs in total)
node305.hydra.os - Linux CentOS Linux 7.9.2009, x86_64, Intel(R) Xeon(R) Gold 6148 CPU @ 2.40GHz (skylake_avx512), Python 2.7.5
See https://gist.github.com/d81abf921c809a9001a85caebe1003fb for a full test report.

**Review by smoors — APPROVED** [review]
lgtm

**Pull request merged**
