### PR TITLE
{bio}[foss/2016b] Sailfish 0.10.1

### PR DESCRIPTION
**Pull request by SethosII**
This adds the current version of `Sailfish` for the `foss-2016b` toolchain.

### CODE REVIEW

**Comment by verdurin** [comment]
@SethosII please check the `Jellyfish` dependency:
```
ERROR: Irresolvable dependencies encountered: Jellyfish/2.2.6-foss-2016b
```

**Comment by SethosII** [comment]
@verdurin This EasyConfig was added just recently with https://github.com/easybuilders/easybuild-easyconfigs/pull/4810, so maybe you need to update your development branch?

**Comment by verdurin** [comment]
@SethosII yes, so I see. Will update and re-run the test.

**Comment by verdurin** [comment]
Test report by @verdurin
**SUCCESS**
Build succeeded for 4 out of 4 (2 easyconfigs in this PR)
ca022.camp.thecrick.org - Linux centos linux 7.3.1611, Intel(R) Xeon(R) CPU E5-2640 v3 @ 2.60GHz, Python 2.7.5
See https://gist.github.com/059c5d825f3cff78b86858a2c0261de1 for a full test report.

**Comment by verdurin** [comment]
Merging - thanks, @SethosII

**Pull request merged**
