### PR TITLE
PyTorch, TensorFlow, Theano: Use a cuDNN version that has support for the CUDA version in fosscuda/2019a (CUDA 10.1)

### PR DESCRIPTION
**Pull request by akesandgren**
Also fixes incorrect postinstallcmds for both foss and fosscuda versions.

requires ~~#9108~~ (`cuDNN`)

### CODE REVIEW

**Comment by akesandgren** [comment]
Test report by @akesandgren
**FAILED**
Build succeeded for 0 out of 1 (1 easyconfigs in this PR)
b-an03.hpc2n.umu.se - Linux ubuntu 16.04, Intel(R) Xeon(R) CPU E5-2690 v4 @ 2.60GHz, Python 2.7.12
See https://gist.github.com/1dd6c848632daed7192be6b37c6f966e for a full test report.

**Comment by akesandgren** [comment]
Test report by @akesandgren
**FAILED**
Build succeeded for 0 out of 1 (1 easyconfigs in this PR)
b-an03.hpc2n.umu.se - Linux ubuntu 16.04, Intel(R) Xeon(R) CPU E5-2690 v4 @ 2.60GHz, Python 2.7.12
See https://gist.github.com/0a96d7379e18029cb91ef15fad14c300 for a full test report.

**Comment by akesandgren** [comment]
The cuDNN version problem will of course go away once all 4 of the cuDNN version bugfixes are merged.

**Comment by akesandgren** [comment]
Test report by @akesandgren
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in this PR)
b-an03.hpc2n.umu.se - Linux ubuntu 16.04, Intel(R) Xeon(R) CPU E5-2690 v4 @ 2.60GHz, Python 2.7.12
See https://gist.github.com/cff6bb22978b1f40ac7224a50cfb3ecd for a full test report.

**Comment by boegel** [comment]
@akesandgren This is difficult to merge because of the broken tests, why not collapse all 4 PRs into one (here for example), so the tests pass?

That makes it a bit more painful w.r.t. submitting a test report, but it's a lot easier to get it merged...

**Comment by akesandgren** [comment]
Merged the fix for PR #9113, #9114, and #9115 into this one to make merging into develop possible, avoiding cuDNN version problems.

**Comment by akesandgren** [comment]
Test report in progress

**Comment by akesandgren** [comment]
Test report by @akesandgren
**SUCCESS**
Build succeeded for 5 out of 5 (5 easyconfigs in this PR)
b-an03.hpc2n.umu.se - Linux ubuntu 16.04, Intel(R) Xeon(R) CPU E5-2690 v4 @ 2.60GHz, Python 2.7.12
See https://gist.github.com/7c54a7edb467212187da8064ea8afed4 for a full test report.

**Comment by zao** [comment]
Test report by @zao
**SUCCESS**
Build succeeded for 7 out of 7 (5 easyconfigs in this PR)
freja - Linux ubuntu 18.04, Intel(R) Core(TM) i7-8700K CPU @ 3.70GHz, Python 2.7.15+
See https://gist.github.com/23d87d527d854fbc390ba74d793a8bef for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 5 out of 5 (5 easyconfigs in this PR)
node3301.joltik.os - Linux centos linux 7.6.1810, Intel(R) Xeon(R) Gold 6242 CPU @ 2.80GHz, Python 2.7.5
See https://gist.github.com/dbce7a6f1e7403d285321a63b681d56a for a full test report.

**Comment by boegel** [comment]
Going in, thanks @akesandgren!

**Pull request merged**
