### PR TITLE
{bio}[fosscuda/2019b] CuCLARK v1.1

### PR DESCRIPTION
**Pull request by boegel**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by migueldiascosta** [comment]
Test report by @migueldiascosta
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
generoso - Linux centos linux 7.6.1810, Intel(R) Xeon(R) CPU E5-2660 v4 @ 2.00GHz, Python 3.6.8
See https://gist.github.com/71ce52604731e890b5522fcc84dd62b4 for a full test report.

**Review by migueldiascosta — DISMISSED** [review]
lgtm

**Comment by migueldiascosta** [comment]
ah, sorry, missed the "WIP" in the title. Is is still?

**Comment by boegel** [comment]
I guess it's good enough to go in as is...

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
node3302.joltik.os - Linux centos linux 7.9.2009, x86_64, Intel(R) Xeon(R) Gold 6242 CPU @ 2.80GHz (cascadelake), Python 3.6.8
See https://gist.github.com/eab212ba7a0f3efa05663356e179d66e for a full test report.

**Comment by boegel** [comment]
@boegelbot please test @ generoso

**Comment by akesandgren** [comment]
Test report by @akesandgren
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
b-cn1501.hpc2n.umu.se - Linux Ubuntu 20.04, x86_64, Intel(R) Xeon(R) Gold 6132 CPU @ 2.60GHz, 2 x NVIDIA Tesla V100-PCIE-16GB, 470.182.03, Python 3.8.10
See https://gist.github.com/akesandgren/ae033dbe013b040c182a4ef256eb1be2 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
node3901.accelgor.os - Linux RHEL 8.6, x86_64, AMD EPYC 7413 24-Core Processor (zen3), 1 x NVIDIA NVIDIA A100-SXM4-80GB, 530.30.02, Python 3.6.8
See https://gist.github.com/boegel/e4791cbc112648b4d1e3ed3f777fc293 for a full test report.

**Review by akesandgren — APPROVED** [review]
LGTM

**Pull request merged**
