### PR TITLE
Scipion 1.2 (WIP)

### PR DESCRIPTION
**Pull request by akesandgren**
(created using `eb --new-pr`)
Scipion is an image processing framework to obtain 3D models of macromolecular complexes using Electron Microscopy (3DEM)

Requires scipion easyblock, https://github.com/easybuilders/easybuild-easyblocks/pull/1447

### CODE REVIEW

**Comment by akesandgren** [comment]
Dropping this in favor of a Scipion 2.0 easyconfig.

**Comment by nortex** [comment]
Hi,

Is there a Scipion easyconfig available somewhere?

**Comment by akesandgren** [comment]
@nortex Yes I have 2.0.0 installed
unfortunately I haven't had time to work on the version 3

The latest we have as a PR (not merged yet for various reasons) is available at https://github.com/easybuilders/easybuild-easyconfigs/pull/9813

**Comment by nortex** [comment]
> @nortex Yes I have 2.0.0 installed unfortunately I haven't had time to work on the version 3
> 
> The latest we have as a PR (not merged yet for various reasons) is available at #9813

I see, thanks! would be great if version 3 was available...

**Pull request closed without merging**
