### PR TITLE
{vis}[intelcuda/2020a] matplotlib v3.2.1 w/ Python 3.8.2

### PR DESCRIPTION
**Pull request by Micket**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by Micket** [comment]
@boegelbot please test @ generoso

**Review by boegel — APPROVED** [review]
lgtm

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
node3303.joltik.os - Linux centos linux 7.9.2009, x86_64, Intel(R) Xeon(R) Gold 6242 CPU @ 2.80GHz (cascadelake), Python 3.6.8
See https://gist.github.com/906bdbedc7b53b4387b3d657a2f8b396 for a full test report.

**Comment by boegel** [comment]
Going in, thanks @Micket!

**Pull request merged**
