### PR TITLE
{bio}[foss/2016b] Biopython v1.68 w/Python 3.5.2(REVIEW)

### PR DESCRIPTION
**Pull request by jrbosch**

### CODE REVIEW

**Comment by verdurin** [comment]
Test report by @verdurin
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
ca022.camp.thecrick.org - Linux centos linux 7.3.1611, Intel(R) Xeon(R) CPU E5-2640 v3 @ 2.60GHz, Python 2.7.5
See https://gist.github.com/5c9defc97c171f7b932cdeef64f90d4a for a full test report.

**Comment by verdurin** [comment]
@jrbosch Please use the new URL in the header - `https://github.com/easybuilders/easybuild`

**Comment by boegel** [comment]
lgtm

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
node2567.golett.os - Linux centos linux 7.3.1611, Intel(R) Xeon(R) CPU E5-2680 v3 @ 2.50GHz, Python 2.7.5
See https://gist.github.com/4f0896eda14e460503a456af41d0f189 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
node2143.delcatty.os - Linux centos linux 7.3.1611, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.7.5
See https://gist.github.com/e2df2009806f679cf0c3bbf0c9781377 for a full test report.

**Comment by boegel** [comment]
Going in, thanks @jrbosch!

**Comment by boegel** [comment]
Going in, thanks @jrbosch!

**Comment by boegel** [comment]
Going in, thanks @jrbosch!

**Pull request merged**
