### PR TITLE
{numlib}[intel/2020a] FFTW v3.3.8

### PR DESCRIPTION
**Pull request by ocaisa**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by ocaisa** [comment]
Test report by @ocaisa
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
generoso - Linux centos linux 7.6.1810, Intel(R) Xeon(R) CPU E5-2660 v4 @ 2.00GHz, Python 3.6.8
See https://gist.github.com/bc848003866d2edc27d2c9723d77dbe2 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
node3100.skitty.os - Linux centos linux 7.7.1908, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz, Python 3.6.8
See https://gist.github.com/2f497fd497d1323231763eec90e2a224 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
node2479.golett.os - Linux centos linux 7.7.1908, Intel(R) Xeon(R) CPU E5-2680 v3 @ 2.50GHz, Python 2.7.5
See https://gist.github.com/618a0a8f5a349d2331dbc6c64635524e for a full test report.

**Comment by boegel** [comment]
The segmentation fault issues that arose when testing FFTW via #10189 were likely due to memory limits that were in place, it seems like running the FFTW MPI tests requires quite a bit of memory... Apparently ~46GB of memory is not enough when using 9 cores on Intel Skylake.

**Comment by boegel** [comment]
Going in, thanks @ocaisa!

**Pull request merged**
