### PR TITLE
{devel}[GCCcore/10.2.0] Bazel v3.7.1

### PR DESCRIPTION
**Pull request by Micket**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by Micket** [comment]
Test report by @Micket
**FAILED**
Build succeeded for 0 out of 1 (1 easyconfigs in total)
vera-c1 - Linux centos linux 7.8.2003, x86_64, Intel Xeon Processor (Skylake), Python 2.7.5
See https://gist.github.com/af9032fe190890bbf8a49e576df8ba29 for a full test report.

**Comment by Micket** [comment]
```
/local/EB/build/eb-5ELu_U/bazel_x5LRfhQ7/out/execroot/io_bazel/bazel-out/host/bin/external/com_google_protobuf/protoc: /lib64/libstdc++.so.6: version `CXXABI_1.3.8' not found (required by /local/EB/build/eb-5ELu_U/bazel_x5LRfhQ7/out/execroot/io_bazel/bazel-out/host/bin/external/com_google_protobuf/protoc
```
Well crap, usual nonsense issues here that i was hoping to skip for once.

**Comment by Flamefire** [comment]
I got a patch for that:
```
diff --git a/third_party/protobuf/3.13.0.patch b/third_party/protobuf/3.13.0.patch
index bde8684b82..3336ef4024 100644
--- a/third_party/protobuf/3.13.0.patch
+++ b/third_party/protobuf/3.13.0.patch
@@ -38,3 +38,15 @@ index cfdb28e2e..3705fdbe3 100644
 +        "@io_bazel//third_party:gson",
      ],
  )
+diff --git a/protobuf.bzl b/protobuf.bzl
+index 050eafc54..12d3edb94 100644
+--- a/protobuf.bzl
++++ b/protobuf.bzl
+@@ -352,6 +352,7 @@ def _internal_gen_well_known_protos_java_impl(ctx):
+         inputs = descriptors,
+         outputs = [srcjar],
+         arguments = [args],
++        use_default_shell_env = True,
+     )
+ 
+     return [

```

This also needs the static linking of process-wrapper

**Comment by boegel** [comment]
@Micket Please let us know if you're up for looking into applying that patch to fix the issue, or if someone should take over from you.

**Comment by Micket** [comment]
I haven't had time to think about this. Please feel free to steal this work from me :)

**Comment by Flamefire** [comment]
Also requires https://github.com/easybuilders/easybuild-easyblocks/pull/2285 (mentioned above, just adding the link for reference)

**Comment by branfosj** [comment]
@Micket We've merged #12148 which includes `Bazel-3.7.2-GCCcore-10.2.0.eb` so I've closed this PR.

**Comment by Flamefire** [comment]
Ah, sorry forgot about this PR

**Pull request closed without merging**
