### PR TITLE
{vis}[foss/2023a] nellie v0.3.1 w/ CUDA 12.1.1

### PR DESCRIPTION
**Pull request by pavelToman**
(created using `eb --new-pr`)
resolves https://github.com/vscentrum/vsc-software-stack/issues/359
Tested on donphan desktop cluster + nvidia-smi

### CODE REVIEW

**Comment by pavelToman** [comment]
@boegelbot please test @ generoso

**Comment by boegel** [comment]
failing tests on `generoso` for `CuPy` dependency are most likely due to lack of GPU drivers there, so ignoring that...

**Comment by boegel** [comment]
@boegelbot please test @ jsc-zen3-a100

**Review by boegel — APPROVED** [review]
lgtm

**Comment by boegel** [comment]
Going in, thanks @pavelToman!

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
node3300.joltik.os - Linux RHEL 8.8, x86_64, Intel(R) Xeon(R) Gold 6242 CPU @ 2.80GHz, 1 x NVIDIA Tesla V100-SXM2-32GB, 545.23.08, Python 3.6.8
See https://gist.github.com/boegel/00b55ee5248d3f8a146120f7d8c62134 for a full test report.

**Pull request merged**
