### PR TITLE
{lib}[foss/2021a] flair-NLP v0.11.3, gensim v4.2.0, Hyperopt v0.2.7, SentencePiece v0.1.96 w/ Python 3.9.5

### PR DESCRIPTION
**Pull request by boegel**
(created using `eb --new-pr`)
requires:
* #15587

### CODE REVIEW

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 4 out of 4 (4 easyconfigs in total)
node3162.skitty.os - Linux RHEL 8.4, x86_64, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz, Python 3.6.8
See https://gist.github.com/64cdd7986e10571efb3b6b7f48a73234 for a full test report.

**Comment by boegel** [comment]
@boegelbot please test @ generoso

**Comment by lexming** [comment]
@boegelbot: please test @ generoso

**Comment by lexming** [comment]
Going in, thanks @boegel !

**Pull request merged**
