### PR TITLE
fix build of Bison using older GCC

### LINKED ISSUE #12202: Bison 3.5.3 fails to install with older GCC
(Reported on slack)

https://github.com/easybuilders/easybuild-easyconfigs/blob/develop/easybuild/easyconfigs/b/Bison/Bison-3.5.3.eb fails to install on older GCC (i.e. 4.4.6 on CentOS 6). Error is:
```
src/InadequacyList.c: In function 'InadequacyList__new_conflict':
src/InadequacyList.c:37: error: #pragma GCC diagnostic not allowed inside functions
src/InadequacyList.c:37: error: #pragma GCC diagnostic not allowed inside functions
src/InadequacyList.c:40: error: #pragma GCC diagnostic not allowed inside functions
make: *** [src/bison-InadequacyList.o] Error 1
```

I think git.savannah.gnu.org/cgit/bison.git/commit/?id=6e89bc0fd27ee8bf1095544504c6970530e9527c is the fix for this.

### PR DESCRIPTION
**Pull request by branfosj**
(created using `eb --new-pr`)

fixes #12202

I do not have a sufficiently old GCC to be able to test this fixes the issue.

### CODE REVIEW

**Comment by branfosj** [comment]
Test report by @branfosj
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
bear-pg0211u03a.bear.cluster - Linux centos linux 7.8.2003, x86_64, Intel(R) Xeon(R) Gold 6248 CPU @ 2.50GHz (cascadelake), Python 3.6.8
See https://gist.github.com/38bfa0d4e7e68255c494517d3fbcdfbd for a full test report.

**Review by boegel — CHANGES_REQUESTED** [review]
@branfosj It doesn't make sense to use this patch for `Bison-3.5.3-GCCcore-9.3.0.eb`, but patching `Bison-3.5.3.eb` does make sense?

**Comment by branfosj** [comment]
> @branfosj It doesn't make sense to use this patch for `Bison-3.5.3-GCCcore-9.3.0.eb`, but patching `Bison-3.5.3.eb` does make sense?

Fixed in c3ba286

**Comment by boegel** [comment]
@boegelbot please test @ generoso

**Review by boegel — APPROVED** [review]

**Comment by boegel** [comment]
I tested (manually) building Bison 3.5.3 in an old SL6 Singularity container, fails without the patch as reported in #12202, works with the patch:

```
Singularity> bison --version
bison (GNU Bison) 3.5.3

Singularity> cat /etc/redhat-release
Scientific Linux release 6.9 (Carbon)

Singularity> gcc --version
gcc (GCC) 4.4.7 20120313 (Red Hat 4.4.7-18)
```

**Comment by branfosj** [comment]
Test report by @branfosj
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
bear-pg0211u03a.bear.cluster - Linux centos linux 7.8.2003, x86_64, Intel(R) Xeon(R) Gold 6248 CPU @ 2.50GHz (cascadelake), Python 3.6.8
See https://gist.github.com/d32ad9179ce162951cc41fb4a4ec4c10 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
node3101.skitty.os - Linux centos linux 7.9.2009, x86_64, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz, Python 3.6.8
See https://gist.github.com/02c40970aff8592a6ee4e53c4de3474d for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
node3503.doduo.os - Linux RHEL 8.2, x86_64, AMD EPYC 7552 48-Core Processor (zen2), Python 3.6.8
See https://gist.github.com/f5298aea2361a9875de5f17cb968e637 for a full test report.

**Comment by boegel** [comment]
Going in, thanks @branfosj!

**Comment by branfosj** [comment]
Test report by @branfosj
**SUCCESS**
Build succeeded for 4 out of 4 (4 easyconfigs in total)
bear-pg0211u03a.bear.cluster - Linux centos linux 7.8.2003, x86_64, Intel(R) Xeon(R) Gold 6248 CPU @ 2.50GHz (cascadelake), Python 3.6.8
See https://gist.github.com/94764ca6baaa231a73a128baa4ef1d28 for a full test report.

**Pull request merged**
