### PR TITLE
add patch to fix version for bam-readcount 0.8.0

### PR DESCRIPTION
**Pull request by SethosII**
`bam-readcount` uses `git` to insert the version during configuration with `CMake` but in the release archives there is no such thing, this results in the following output:

```
> bam-readcount -v
bam-readcount version: unstable (commit nogit)
```

With this patch it displays the version as if it would be build from a `git clone`:

```
> ./bam-readcount --version
bam-readcount version: 0.8.0 (commit dea4199)
```

### CODE REVIEW

**Comment by smoors** [comment]
Test report by @smoors
**FAILED**
Build succeeded for 0 out of 2 (2 easyconfigs in total)
node375.hydra.os - Linux centos linux 7.9.2009, x86_64, Intel(R) Xeon(R) Gold 6148 CPU @ 2.40GHz (skylake_avx512), Python 2.7.5
See https://gist.github.com/f916385292eea0e1c4d85156762d3988 for a full test report.

**Comment by smoors** [comment]
@SethosII is the checksum correct for the patch?

**Comment by boegel** [comment]
Can't this be done via "runtime patching", using a `sed` command (for lack of a better option), just to avoid having to maintain a patch?

**Comment by SethosII** [comment]
@smoors Oh sorry, I changed the formatting before creating the pull request but I didn't change the patch checksum. Now it should be correct.

@boegel I don't think so, because the version also contains the git commit hash. I don't know of a way to get this automated with the release archive. Also, I don't think that the patch needs a lot of maintenance. Their last release was in 2016 (with 7 commits since than) and before that in 2014, so there probably won't be a lot in the future.

**Comment by smoors** [comment]
@SethosII the easiest is to just not fix the commit hash (that should be ok since it's a release version).
alternatively you can define the commit hash in the easyconfig:
```
local_commit = 'dea4199'
local_versionfile = '%(builddir)s/%(name)s*/version/version.h.in'
preconfigopts = "sed -i -e 's/@FULL_VERSION@/%%(version)s/' %s && " % local_versionfile
preconfigopts += "sed -i -e 's/@COMMIT_HASH@/%s/' %s && " % (local_commit, local_versionfile)
```

**Comment by SethosII** [comment]
@smoors I changed it as you suggested.

**Comment by smoors** [comment]
Test report by @smoors
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in total)
node379.hydra.os - Linux centos linux 7.9.2009, x86_64, Intel(R) Xeon(R) Gold 6148 CPU @ 2.40GHz (skylake_avx512), Python 2.7.5
See https://gist.github.com/dd455d2f14206ffe028a8d219a468326 for a full test report.

**Review by smoors — APPROVED** [review]
lgtm

**Comment by smoors** [comment]
Going in, thanks @SethosII!

**Comment by boegel** [comment]
It would make sense to enhance the sanity check commands, to catch issues like this going forward.

Essentially (also) run `bam-readcount --version | grep 'version: %(version)s '`.

**Comment by boegel** [comment]
Enhanced sanity check added in #12092

**Pull request merged**
