### PR TITLE
{lang}[GCCcore/9.3.0] SBCL v2.0.9

### PR DESCRIPTION
**Pull request by lexming**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by lexming** [comment]
Test report by @lexming
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
node379.hydra.os - Linux centos linux 7.7.1908, x86_64, Intel(R) Xeon(R) Gold 6148 CPU @ 2.40GHz, Python 2.7.5
See https://gist.github.com/6986e30b0b788e21b62053202ed2dd4f for a full test report.

**Comment by lexming** [comment]
Test report by @lexming
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
node101.hydra.os - Linux centos linux 7.7.1908, x86_64, Intel(R) Xeon(R) CPU E5-2680 v2 @ 2.80GHz, Python 2.7.5
See https://gist.github.com/f1ad5fb663dcc8da3fc0953e99c83503 for a full test report.

**Comment by smoors** [comment]
this uses ConfigureMake, but skips the configure step and has custom build and install commands.
so it's not actually doing ConfigureMake anymore, which is ok for me, but I wonder why you're not using CmdCp instead?

**Comment by lexming** [comment]
The problem with `CmdCp` is that it needs `files_to_copy`, but in this case there are none because the software provides an installation script.

**Comment by smoors** [comment]
@boegelbot please test @ generoso

**Comment by smoors** [comment]
ok, another option could have been this: `files_to_copy = [([''], '')]`
but with ConfigureMake there are separate of build and install steps, I prefer that.

**Review by smoors — APPROVED** [review]
lgtm

**Comment by smoors** [comment]
Going in, thanks @lexming!

**Pull request merged**
