### PR TITLE
{tools}[GCCcore/7.2.0] Ninja v1.8.2

### PR DESCRIPTION
**Pull request by rubendibattista**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by pescobar** [comment]
why are you using `GCCcore/7.2.0`? This one is not sub-toolchain of any other toolchain

wouldn't make more sense to use `GCCcore/7.3.0` (subtoolchain of `foss/2018b`) or `GCCcore/8.2.0` (subtoolchain of `foss/2019b`)?

**Comment by rubendibattista** [comment]
It's a long story, but I'm using a custom version of `gmpich` and `gmpolf`.

I'll switch to `foss2019a`. The time has come. 🔥

**Comment by pescobar** [comment]
thanks for you PR. We will be happy to merge your contribution once it's aligned with one of the common toolchains

**Comment by pescobar** [comment]
btw, just to make it clear, it's not mandatory to align all your PR with a common toolchain. Strictly speaking your PR is valid and can be merged upstream so if you are interested feel free to reopen it.

I asked why you se `7.2.0` just out of curiosity because most of the easybuild users use common toolchains and using them makes things simpler (more easyconfigs available)

**Comment by rubendibattista** [comment]
Don't worry @pescobar I get it :)

It's time to align with the common toolchains even because I always find myself updating all the dependency graph by myself. I need help. HELP! HELP ME!.

So I switch to foss2019a. :)

**Pull request closed without merging**
