### PR TITLE
move `setuptools_scm` from `hatchling` to Python easyconfig

### PR DESCRIPTION
**Pull request by lexming**
(created using `eb --new-pr`)

There is software that uses `setuptools_scm` without `hatchling`. In those cases the build will not fail, but generate packages with version `0.0.0`.

Example is `mapclassify`, see https://github.com/pysal/mapclassify/blob/9953271bcc90ffb4e6c54d3c5a0ff48010dcb9be/pyproject.toml#L2

Therefore, I propose to ship `setuptools_scm` together with `setuptools` in the base easyconfig of Python.

### CODE REVIEW

**Comment by lexming** [comment]
@boegelbot: please test @ generoso

**Comment by lexming** [comment]
@boegelbot please test @ jsc-zen3

**Review by boegel — DISMISSED** [review]
lgtm

**Review by boegel — APPROVED** [review]
lgtm

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 6 out of 6 (6 easyconfigs in total)
node3129.skitty.os - Linux RHEL 8.8, x86_64, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz (skylake_avx512), Python 3.6.8
See https://gist.github.com/boegel/ed933aa0a3ac512131adc9bad8b98c77 for a full test report.

**Comment by boegel** [comment]
Going in, thanks @lexming!

**Pull request merged**
