### PR TITLE
{bio}[foss/2022a] ColabFold v1.5.2, AlphaFold v2.3.4 w/ Python 3.10.4

### PR DESCRIPTION
**Pull request by lexming**
(created using `eb --new-pr`)

ColabFold relies on its own fork of AlphaFold. This PR adds:
* easyconfigs for this AlphaFold fork with an extra `-ColabFold` versionsuffix
* easyconfigs for the actual package of ColabFold

Depends on:
* https://github.com/easybuilders/easybuild-easyconfigs/pull/17752

### CODE REVIEW

**Comment by lexming** [comment]
@boegelbot please test @ jsc-zen2

**Comment by lexming** [comment]
Test report by @lexming
**SUCCESS**
Build succeeded for 4 out of 4 (4 easyconfigs in total)
node401.hydra.os - Linux CentOS Linux 7.9.2009, x86_64, AMD EPYC 7282 16-Core Processor (zen2), 1 x NVIDIA NVIDIA A100-PCIE-40GB, 515.48.07, Python 3.6.8
See https://gist.github.com/lexming/d259af1c2d7ef689d5551e60431b8e61 for a full test report.

**Review by Micket — APPROVED** [review]
lgtm

**Comment by Micket** [comment]
@boegelbot please test @ generoso
EB_ARGS="AlphaFold-2.3.4-foss-2022a-ColabFold.eb ColabFold-1.5.2-foss-2022a.eb"

**Comment by Micket** [comment]
Test report by @Micket
**SUCCESS**
Build succeeded for 3 out of 3 (2 easyconfigs in total)
vera-c1 - Linux Rocky Linux 8.6, x86_64, Intel Xeon Processor (Skylake), Python 3.6.8
See https://gist.github.com/Micket/c7b5617c28917ccd2d053d7e238520c4 for a full test report.

**Comment by verdurin** [comment]
Going in, thanks @lexming!

**Pull request merged**
