### PR TITLE
{compiler}[intel-compilers/2021.2.0] impi v2021.2.0

### PR DESCRIPTION
**Pull request by bartoldeman**
(created using `eb --new-pr`)

requires ~~#12765~~ (intel-compilers), https://github.com/easybuilders/easybuild-easyblocks/pull/2405

### CODE REVIEW

**Comment by boegel** [comment]
Test report by @boegel
**FAILED**
Build succeeded for 0 out of 1 (1 easyconfigs in total)
node3598.doduo.os - Linux RHEL 8.2, x86_64, AMD EPYC 7552 48-Core Processor (zen2), Python 3.6.8
See https://gist.github.com/a731eb2a96a4aed83635ecab8d55b27c for a full test report.

**Comment by boegel** [comment]
@bartoldeman Did this work for you? Sanity check is failing for me (see upcoming test report...)

**Comment by verdurin** [comment]
Test report by @verdurin
**FAILED**
Build succeeded for 0 out of 1 (1 easyconfigs in total)
nuc.lan - Linux Fedora 33, x86_64, Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz, Python 3.9.2
See https://gist.github.com/5b96fa7d7c973ae41aa51ecee1482720 for a full test report.

**Comment by verdurin** [comment]
Test report by @verdurin
**FAILED**
Build succeeded for 0 out of 1 (1 easyconfigs in total)
nuc.lan - Linux Fedora 33, x86_64, Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz, Python 3.9.2
See https://gist.github.com/f25b28c6864ad4bc5a7ea66c11650c97 for a full test report.

**Comment by bartoldeman** [comment]
@boegel it actually failed but I thought this was just our nonstandard environment for now.
I'll have a look, perhaps the easyblock needs changing first

**Comment by bartoldeman** [comment]
it seems to have something to do with FI_PROVIDER_PATH not being set in the modulefile. I'll check again tomorrow for more debugging...

**Comment by bartoldeman** [comment]
@boegelbot please test @ generoso
EB_ARGS="--include-easyblocks-from-pr 2405"

**Comment by boegel** [comment]
Test report by @boegel
Using easyblocks from PR(s) https://github.com/easybuilders/easybuild-easyblocks/pull/2405
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
node3501.doduo.os - Linux RHEL 8.2, x86_64, AMD EPYC 7552 48-Core Processor (zen2), Python 3.6.8
See https://gist.github.com/c85a334233f0939d68abc3c7e983032a for a full test report.

**Review by boegel — APPROVED** [review]
lgtm

**Pull request merged**
