### PR TITLE
{math,numlib,vis}[intel/2020b] Octave v6.2.0, arpack-ng v3.8.0, GraphicsMagick v1.3.36

### PR DESCRIPTION
**Pull request by SimonPinches**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by casparvl** [comment]
@boegelbot please test @ jsc-zen2

**Comment by casparvl** [comment]
Oh yeah, older intel toolchains are not present on `jsc-zen2`, we can ignore that failure... I'll try to upload a test report from my local system, but need to build this toolchain :)

**Comment by casparvl** [comment]
Test report by @casparvl
**FAILED**
Build succeeded for 2 out of 3 (3 easyconfigs in total)
tcn37.local.snellius.surf.nl - Linux Rocky Linux 8.7, x86_64, AMD EPYC 7H12 64-Core Processor, Python 3.6.8
See https://gist.github.com/casparvl/a473a44a6eefb4aa9ccbd715a10da352 for a full test report.

**Comment by casparvl** [comment]
I'm hitting a build issue. No clue why - or why it works on Generoso. Is it possible that a Qt5 is picked up from somewhere else than the one installed by EasyBuild on your system? I've checked, and the Qt 5.15 symbols are indeed not in the libQt5Core.so.5 installation on my machine. Could you check if they are there in your module? (i.e. see if `readelf -a /path/to/software/Qt5/5.14.2-GCCcore-10.2.0/lib/libQt5Core.so.5 | grep Qt_5\.15` returns something. For me, I _do_ see something for `Qt_5\.14`, but not for `Qt_5\.15`).
It also makes sense: the Qt dependency in your EasyConfig is for version 5.14. I'm really not sure what this `uic-qt5` is, my guess is that it is installed along with Octave, but requires a newer Qt5?

Another thing you could look at is the output from the configure. I see

``` 
checking for x86_64-pc-linux-gnu-uic-qt5... no
checking for uic-qt5... uic-qt5
```
And then later on in the summary:
``` 
  Qt CPPFLAGS:                   -I/scratch-nvme/1/casparl/generic/software/Qt5/5.14.2-GCCcore-10.2.0/include/QtNetwork -I/scratch-nvme/1/casparl/generic/software/Qt5/5.14.2-GCCcore-10.2.0/include/QtPrintSupport -I/scratch-nvme/1/casparl/generic/software/Qt5/5.14.2-GCCcore-10.2.0/include/QtHelp -I/scratch-nvme/1/casparl/generic/software/Qt5/5.14.2-GCCcore-10.2.0/include/QtWidgets -I/scratch-nvme/1/casparl/generic/software/Qt5/5.14.2-GCCcore-10.2.0/include/QtGui -I/scratch-nvme/1/casparl/generic/software/Qt5/5.14.2-GCCcore-10.2.0/include/QtSql -I/scratch-nvme/1/casparl/generic/software/Qt5/5.14.2-GCCcore-10.2.0/include/QtXml -I/scratch-nvme/1/casparl/generic/software/Qt5/5.14.2-GCCcore-10.2.0/include/QtCore
  Qt LDFLAGS:                    -L/scratch-nvme/1/casparl/generic/software/Qt5/5.14.2-GCCcore-10.2.0/lib
  Qt GUI libraries:              -lQt5Network -lQt5PrintSupport -lQt5Help -lQt5Widgets -lQt5Gui -lQt5Sql -lQt5Xml -lQt5Core
  Qt OpenGL libraries:           -lQt5OpenGL -lQt5Widgets -lQt5Gui -lQt5Core
  Qt moc:                        moc-qt5
  Qt uic:                        uic-qt5
  Qt rcc:                        rcc-qt5
  Qt lrelease:                   /scratch-nvme/1/casparl/generic/software/Qt5/5.14.2-GCCcore-10.2.0/bin/lrelease
  Qt qcollectiongenerator:       qcollectiongenerator
  Qt qhelpgenerator:             qhelpgenerator
``` 
Maybe it decides to build this uic-qt5 on my system, because it is not there, and maybe on your system it finds one already present?

**Comment by boegel** [comment]
closing this since `intel/2020b` is deprecated, see https://docs.easybuild.io/policies/toolchains

**Pull request closed without merging**
