### PR TITLE
Checksum of new source tarball added, next to original one, URL updated

### PR DESCRIPTION
**Pull request by sassy-crick**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by Micket** [comment]
So, this is more a case where the old sources have been removed, and this is the new, "upcoming" oneapi stuff. Are we sure it's just a directory name change?

**Comment by sassy-crick** [comment]
@Micket It was @boegel who told me about the different directories and I just took his word for granted here as I did not have any older source file to confirm this. Maybe speak to him and let me know?

**Comment by Flamefire** [comment]
Yes @boegel wrote that in Slack. 

@sassy-crick Could you include the name of the software you are updating in the PR? Like `[tbb] Describe what you did`? I just searched for "tbb" to find this but could not. For this time there is an "Edit" button on the top right here to change that, next time you can use that in `--pr-commit-msg` :)

**Comment by lexming** [comment]
Test report by @lexming
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
node365.hydra.os - Linux centos linux 7.7.1908, Intel(R) Xeon(R) Gold 6148 CPU @ 2.40GHz, Python 2.7.5
See https://gist.github.com/38e6124d4dc7938a4246319a02adfa26 for a full test report.

**Comment by lexming** [comment]
Going in, thanks @sassy-crick !

**Pull request merged**
