### PR TITLE
{data}[foss/2017b,intel/2017b] ANTs v2.3.0

### PR DESCRIPTION
**Pull request by vanzod**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by vanzod** [comment]
Test report by @vanzod
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in this PR)
cermis - Linux debian 9.8, Intel(R) Xeon(R) CPU           X5670  @ 2.93GHz, Python 2.7.13
See https://gist.github.com/e048862e2bbdb7d6b70aaf972ffdc0a0 for a full test report.

**Comment by verdurin** [comment]
Test report by @verdurin
**FAILED**
Build succeeded for 3 out of 5 (2 easyconfigs in this PR)
rescomp2 - Linux centos linux 7.3.1611, Intel(R) Xeon(R) Gold 6126 CPU @ 2.60GHz, Python 2.7.5
See https://gist.github.com/c7a83c80f110fcef3b3b2966986101c2 for a full test report.

**Comment by vanzod** [comment]
@verdurin Unfortunately from the log snippet it is not clear what is the issue you had with `VTK`. Is there anything more complete in the full log?

**Comment by verdurin** [comment]
```
-- Found object: "/dev/shm/adamh/VTK/8.0.1/foss-2017b-Python-2.7.14/VTK-8.0.1/.ExternalData/MD5/7dc839fb2825efa8c55e4275fee02a75"
[  0%] Building C object ThirdParty/zlib/vtkzlib/CMakeFiles/vtkzlib.dir/compress.o
cd /dev/shm/adamh/VTK/8.0.1/foss-2017b-Python-2.7.14/VTK-8.0.1/ThirdParty/zlib/vtkzlib && /well/rescomp/eb/software/OpenMPI/2.1.1-GCC-6.4.0-2.28/bin/mpicc -DVTK_IN_VTK -DZLIB_DLL -D_LARGEFILE64_SOURCE=1 -I/dev/shm/adamh/VTK/8.0.1/foss-2017b-Python-2.7.14/VTK-8.0.1/ThirdParty/zlib -I/dev/shm/adamh/VTK/8.0.1/foss-2017b-Python-2.7.14/VTK-8.0.1/ThirdParty/zlib/vtkzlib -I/dev/shm/adamh/VTK/8.0.1/foss-2017b-Python-2.7.14/VTK-8.0.1  -O2 -ftree-vectorize -march=native -fno-math-errno  -w -w -g -fPIC   -o CMakeFiles/vtkzlib.dir/compress.o   -c /dev/shm/adamh/VTK/8.0.1/foss-2017b-Python-2.7.14/VTK-8.0.1/ThirdParty/zlib/vtkzlib/compress.c
/dev/shm/adamh/VTK/8.0.1/foss-2017b-Python-2.7.14/VTK-8.0.1/ThirdParty/hdf5/vtkhdf5/src/H5detect.c:87:19: error: unknown type name <E2><80><98>sigjmp_buf<E2><80><99>
 #define H5JMP_BUF sigjmp_buf
                   ^
/dev/shm/adamh/VTK/8.0.1/foss-2017b-Python-2.7.14/VTK-8.0.1/ThirdParty/hdf5/vtkhdf5/src/H5detect.c:163:8: note: in expansion of macro <E2><80><98>H5JMP_BUF<E2><80><99>
 static H5JMP_BUF jbuf_g;
        ^~~~~~~~~
```

**Comment by vanzod** [comment]
@verdurin It looks like this is an old friend of yours:
https://github.com/easybuilders/easybuild-easyconfigs/issues/6488

**Comment by verdurin** [comment]
Test report by @verdurin
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in this PR)
rescomp2 - Linux centos linux 7.3.1611, Intel(R) Xeon(R) Gold 6126 CPU @ 2.60GHz, Python 2.7.5
See https://gist.github.com/6b97be2ecb4d99430874d139ef037b75 for a full test report.

**Comment by verdurin** [comment]
Test report by @verdurin
**SUCCESS**
Build succeeded for 4 out of 4 (1 easyconfigs in this PR)
dell.lan - Linux fedora 29, Intel(R) Core(TM) i7-4600U CPU @ 2.10GHz, Python 2.7.15
See https://gist.github.com/ba3c7d44268cd21dc04049129ae06ef6 for a full test report.

**Comment by verdurin** [comment]
Going in, thanks @vanzod!

**Pull request merged**
