### PR TITLE
add patch for GCCcore 6.4.0 to fix compilation problems on glibc 2.26 systems

### PR DESCRIPTION
**Pull request by boegel**
cfr. https://github.com/easybuilders/easybuild-easyconfigs/issues/6374#issuecomment-392257938

cc @geimer

### CODE REVIEW

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
node2530.golett.os - Linux centos linux 7.4.1708, Intel(R) Xeon(R) CPU E5-2680 v3 @ 2.50GHz, Python 2.7.5
See https://gist.github.com/336dab70f6347ba8e1873e386215d894 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
node2010.delcatty.os - Linux centos linux 7.4.1708, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.7.5
See https://gist.github.com/23748392856af6b5fb169b09178b404a for a full test report.

**Comment by verdurin** [comment]
Test report by @verdurin
**SUCCESS**
Build succeeded for 0 out of 0 (1 easyconfigs in this PR)
rescomp2 - Linux centos 6.8, Intel(R) Xeon(R) CPU E5-2650 v2 @ 2.60GHz, Python 2.7.14
See https://gist.github.com/13390a357ab03e7a52e3a8ed708c5d6e for a full test report.

**Comment by verdurin** [comment]
Test report by @verdurin
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
rescomp2 - Linux centos 6.8, Intel(R) Xeon(R) CPU E5-2650 v2 @ 2.60GHz, Python 2.7.14
See https://gist.github.com/73d1a6b48267f5272ce55031c47d16df for a full test report.

**Comment by verdurin** [comment]
@boegel Works fine for me. Did you want someone running Debian to test too?

**Comment by boegel** [comment]
@vanzod Please test?

**Comment by vanzod** [comment]
Test report by @vanzod
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
cermis - Linux debian 9.4, Intel(R) Xeon(R) CPU           E5620  @ 2.40GHz, Python 2.7.13
See https://gist.github.com/69cfbcf05614fcdfcfd7e5c2a6a0530b for a full test report.

**Comment by vanzod** [comment]
Going in, thanks @boegel!

**Comment by geimer** [comment]
May I suggest to include the full patch from upstream?  While many of the more exotic platforms aren't supported by EasyBuild yet, Aarch64 is...

**Comment by boegel** [comment]
@geimer You're right, I was cutting corners here since it wasn't trivial to grab the whole patch in one go... Fixed in #6495, thanks for pointing that out!

**Pull request merged**
