### PR TITLE
update homepage and source_urls for SPAdes

### PR DESCRIPTION
**Pull request by branfosj**
(created using `eb --new-pr`)

### CODE REVIEW

**Review by Micket — APPROVED** [review]
Lgtm

**Comment by branfosj** [comment]
Test report by @branfosj
**SUCCESS**
Build succeeded for 9 out of 9 (9 easyconfigs in total)
bb-pg-login04.bb2.cluster - Linux RHEL 8.6, x86_64, Intel(R) Xeon(R) CPU E5-2620 v4 @ 2.10GHz (broadwell), Python 3.6.8
See https://gist.github.com/branfosj/14e6d15aac358888917038ee6e8dbaa1 for a full test report.

**Comment by Micket** [comment]
Test report by @Micket
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
vera-skylake-build - Linux Rocky Linux 8.9, x86_64, Intel Xeon Processor (Skylake, IBRS, no TSX), Python 3.6.8
See https://gist.github.com/Micket/afef6118abb8be19039b79ffc07353bb for a full test report.

**Comment by Micket** [comment]
Going in, thanks @branfosj!

**Pull request merged**
