### PR TITLE
Add OpenBLAS patches to disable FMA in [cz]cal and fix crash in zdot

### PR DESCRIPTION
**Pull request by bartoldeman**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by bartoldeman** [comment]
Fixes #16387

The patch disable FMA generation for cscal and zscal avoids some LAPACK test failures for Haswell, and has been accepted upstream.
For the crash the GCC issue (https://gcc.gnu.org/bugzilla/show_bug.cgi?id=107451) is worked around by asking it to avoid using YMM (256-bit) registers for the offending function, so it's still vectorized using 128-bit XMM registers.

**Review by akesandgren — APPROVED** [review]
LGTM

**Comment by akesandgren** [comment]
This fixes the number of fails from >230 on our KNL's to <= 150 as the limit is set in the easyconfiog files.
Proper test report coming up on KNL.

**Comment by akesandgren** [comment]
Test report by @akesandgren
**SUCCESS**
Build succeeded for 4 out of 4 (4 easyconfigs in total)
b-cn1204.hpc2n.umu.se - Linux Ubuntu 20.04, x86_64, Intel(R) Xeon Phi(TM) CPU 7250 @ 1.40GHz, Python 3.8.10
See https://gist.github.com/0a5bb1e8540cb4c2552b7f6b339f47cd for a full test report.

**Comment by akesandgren** [comment]
Going in, thanks @bartoldeman!

**Comment by boegel** [comment]
@boegelbot please test @ generoso

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 4 out of 4 (4 easyconfigs in total)
node3109.skitty.os - Linux RHEL 8.4, x86_64, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz (skylake_avx512), Python 3.6.8
See https://gist.github.com/1172228519e137acc024069c69cea721 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 4 out of 4 (4 easyconfigs in total)
fair-mastodon-c6g-2xlarge-0001 - Linux Rocky Linux 8.5, AArch64, ARM UNKNOWN (graviton2), Python 3.6.8
See https://gist.github.com/ef533ad1b112b0377007dee70937336f for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 4 out of 4 (4 easyconfigs in total)
easybuild2.novalocal - Linux CentOS Stream 8, POWER, IBM pSeries (emulated by qemu) (power9le), Python 3.6.8
See https://gist.github.com/ee77c9cd29547876552c400adba118f2 for a full test report.

**Comment by boegel** [comment]
@boegelbot please test @ jsc-zen2

**Pull request merged**
