### PR TITLE
don't include unversioned go-basic.odo and goslin_generic.odo files in GOATOOLS installation (renamed from goatools)

### PR DESCRIPTION
**Pull request by boegel**
follow-up for #13364

The original easyconfig is already broken because `go-basic.odo` was updated in place, and there's no versioned download available.

These files don't need to be part of the installation itself, they just need to be available in the current working directory, so and end user can download these easily themselves...

### CODE REVIEW

**Comment by boegel** [comment]
@boegelbot please test @ generoso

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
node3146.skitty.os - Linux centos linux 7.9.2009, x86_64, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz, Python 3.6.8
See https://gist.github.com/415cb0dc40dd77aec9dc6f280a8688f9 for a full test report.

**Review by branfosj — APPROVED** [review]
lgtm

**Comment by branfosj** [comment]
Test report by @branfosj
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
bear-pg0211u12b.bear.cluster - Linux RHEL 8.3, x86_64, Intel(R) Xeon(R) Gold 6248 CPU @ 2.50GHz (cascadelake), Python 3.6.8
See https://gist.github.com/58d2334ba2de40c4fa19963a72a4e042 for a full test report.

**Comment by branfosj** [comment]
Going in, thanks @boegel!

**Pull request merged**
