### PR TITLE
{geo}[foss/2023a] wrf-python v1.3.4.1, basemap v1.3.9

### PR DESCRIPTION
**Pull request by boegel**
(created using `eb --new-pr`)
requires:
* #19474

### CODE REVIEW

**Comment by boegel** [comment]
@boegelbot please test @ generoso

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
node3123.skitty.os - Linux RHEL 8.8, x86_64, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz (skylake_avx512), Python 3.6.8
See https://gist.github.com/boegel/e1b6c7ad0fa315e6fe4f4902e9ff5093 for a full test report.

**Comment by boegel** [comment]
@boegelbot please test @ jsc-zen2

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in total)
node3123.skitty.os - Linux RHEL 8.8, x86_64, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz (skylake_avx512), Python 3.6.8
See https://gist.github.com/boegel/76e1e5e472354daf67412f4fb80a6645 for a full test report.

**Comment by akesandgren** [comment]
@boegelbot Please test @ jsc_zen2

**Comment by akesandgren** [comment]
@boegelbot Please test @ jsc-zen2

**Review by akesandgren — APPROVED** [review]
LGTM

**Comment by akesandgren** [comment]
Going in, thanks @boegel!

**Pull request merged**
