### PR TITLE
{vis}[foss/2019a] matplotlib v3.1.1 w/ Python 3.7.4

### PR DESCRIPTION
**Pull request by henkela**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by Micket** [comment]
I'm confused. It almost seems like you inteded to make PR #8632 #8631 for GCCcore 8.2.0? Because you are trying to use it through foss/2019a here.

And, even if you were, we avoid multiple version of libraries within the same toolchain, unless there is a good reason. Seeing how the 2019b toolchains are close, it seems much more sensible to target those?

**Comment by henkela** [comment]
> I'm confused. It almost seems like you inteded to make PR #8632 #8631 for GCCcore 8.2.0? Because you are trying to use it through foss/2019a here.
> 
> And, even if you were, we avoid multiple version of libraries within the same toolchain, unless there is a good reason. Seeing how the 2019b toolchains are close, it seems much more sensible to target those?

Sorry, messed with the toolchains. Locally, I bumped 2019a already to GCC 8.3.0

**Comment by Micket** [comment]
Ouch.. I don't think that was a good idea. It's going to cause you some headaches as 2019b is going to use 8.3.0 by default as well. 

It's going to be pretty hard for you to contribute anything upstream like this. This would probably be good for 2019b, but, there are still lots of deps missing from there.

**Comment by henkela** [comment]
That’s ok. I’ve done that ever since starting with easybuild

Am 26.07.2019 um 17:40 schrieb Mikael Öhman <notifications@github.com<mailto:notifications@github.com>>:


Ouch.. I don't think that was a good idea. It's going to cause you some headaches as 2019b is going to use 8.3.0 by default as well.

It's going to be pretty hard for you to contribute anything upstream like this. This would probably be good for 2019b, but, there are still lots of deps missing from there.

**Comment by boegel** [comment]
We bumped into this while revisiting old PRs: I think it's a good idea to avoid adding additional `matplotlib` versions to the `2019a` generation of easyconfigs. And since this PR is failing in CI, it's a good candidate for closing.

@henkela I hope this doesn't discourage you from making contributions in the future, we're doing what we can to keep up with incoming contributions...

**Comment by henkela** [comment]
@boegel Don't worry. We are sticking more to the upstream toolchains lately - I guess contributions might by easier then.

**Comment by henkela** [comment]
@boegel Don't worry. We are sticking more to the upstream toolchains lately - I guess contributions might by easier then.

**Pull request closed without merging**
