### PR TITLE
{devel,lib}[GCCcore/12.2.0] TensorFlow v2.13.0, dill v0.3.7, nsync v1.26.0, ...

### PR DESCRIPTION
**Pull request by Flamefire**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by boegel** [comment]
@Flamefire Does this require https://github.com/easybuilders/easybuild-easyblocks/pull/2982?

**Comment by Flamefire** [comment]
Yes it does. However this doesn't work yet due to an issue with Bazel 6 leading to https://github.com/tensorflow/tensorflow/issues/60326

**Comment by Flamefire** [comment]
Test report by @Flamefire
**SUCCESS**
Build succeeded for 6 out of 6 (6 easyconfigs in total)
taurusml30 - Linux RHEL 7.6, POWER, 8335-GTX (power9le), 6 x NVIDIA Tesla V100-SXM2-32GB, 440.64.00, Python 2.7.5
See https://gist.github.com/Flamefire/635665e7bdba61aa2777eb9658266e4d for a full test report.

**Comment by Flamefire** [comment]
Test report by @Flamefire
**SUCCESS**
Build succeeded for 6 out of 6 (6 easyconfigs in total)
taurusi8019 - Linux CentOS Linux 7.9.2009, x86_64, AMD EPYC 7352 24-Core Processor (zen2), 8 x NVIDIA NVIDIA A100-SXM4-40GB, 470.57.02, Python 2.7.5
See https://gist.github.com/Flamefire/5cee75a584c2c21107a4bab8787c12f2 for a full test report.

**Comment by branfosj** [comment]
@boegelbot please test @ jsc-zen2
CORE_CNT=16

**Comment by branfosj** [comment]
@boegelbot please test @ generoso
CORE_CNT=16

**Comment by branfosj** [comment]
Test report by @branfosj
**SUCCESS**
Build succeeded for 8 out of 8 (6 easyconfigs in total)
bear-pg0105u03a.bear.cluster - Linux RHEL 8.6, x86_64, Intel(R) Xeon(R) Platinum 8360Y CPU @ 2.40GHz (icelake), Python 3.6.8
See https://gist.github.com/branfosj/301513464123f44f6751181f9b946af6 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**FAILED**
Build succeeded for 3 out of 6 (6 easyconfigs in total)
node3116.skitty.os - Linux RHEL 8.6, x86_64, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz (skylake_avx512), Python 3.6.8
See https://gist.github.com/boegel/961487fdf9324c66e8ec7af8fdbe033e for a full test report.

**Comment by boegel** [comment]
failed test report is because fix from https://github.com/easybuilders/easybuild-easyblocks/pull/2993 is missing

**Comment by branfosj** [comment]
@boegelbot please test @ generoso
EB_ARGS="--sanity-check-only"

**Comment by branfosj** [comment]
@boegelbot please test @ jsc-zen2
EB_ARGS="--sanity-check-only"

**Review by branfosj — APPROVED** [review]

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 6 out of 6 (6 easyconfigs in total)
node3116.skitty.os - Linux RHEL 8.6, x86_64, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz (skylake_avx512), Python 3.6.8
See https://gist.github.com/boegel/109399d352249709831d158cc875bb6c for a full test report.

**Comment by boegel** [comment]
Going in, thanks @Flamefire!

**Pull request merged**
