### PR TITLE
{numlib}[foss/2016a,intel/2016a] SuperLU v4.3, SuperLU v4.3

### PR DESCRIPTION
**Pull request by besserox**
(created using `eb --new-pr`)
Add easyconfigs for SuperLU 4.3 based on ConfigureMake easyblock (the SuperLU easyblock only works for SuperLU >= 5)

### CODE REVIEW

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in this PR)
node2414.golett.os - Linux centos linux 7.2.1511, Intel(R) Xeon(R) CPU E5-2680 v3 @ 2.50GHz, Python 2.7.5
See https://gist.github.com/c237178f6d83c153a784e84c8f19443b for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in this PR)
node2046.delcatty.os - Linux SL 6.7, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.6.6
See https://gist.github.com/0fbe043b0babbdc2d15c888640df048b for a full test report.

**Comment by boegel** [comment]
@besserox wouldn't it make sense to update the easyblock instead for SuperLU 4.x ?

There's quite a bit of 'magic' in these easyconfigs, not a big fan of that especially since there is an easyblock already...

**Comment by besserox** [comment]
@boegel Starting version 5, SuperLU changed its build system. It is now based on CMake, before it was just Makefiles.

I think it would be easier, and cleaner to have 2 different easyblocks, one for versions <= 4, and one for versions >= 5.

On the other hand, I don't have much time to spend on this.

**Comment by migueldiascosta** [comment]
@besserox, this PR is being closed for the following reason(s): no activity for > 6 months, obsoleted by more recent PRs.
Please don't hesitate to reopen this PR or add a comment if you feel this contribution is still relevant.
For more information on our policy w.r.t. closing PRs, see https://easybuild.readthedocs.io/en/latest/Contributing.html#why-a-pull-request-may-be-closed-by-a-maintainer

**Pull request closed without merging**
