### PR TITLE
{bio}[GCC/12.2.0, GCC/11.3.0] SpaceRanger v2.1.0, bcl2fastq2 v2.20.0

### PR DESCRIPTION
**Pull request by verdurin**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by verdurin** [comment]
@boegelbot please test @ generoso

**Comment by verdurin** [comment]
Can't test this easily on `generoso` or `jsc-zen2` owing to the need for manual downloads.

**Comment by branfosj** [comment]
> Can't test this easily on `generoso` or `jsc-zen2` owing to the need for manual downloads.

We can test the `bcl2fastq2` parts.

**Comment by branfosj** [comment]
@boegelbot please test @ generoso / jsc-zen2
EB_ARGS="bcl2fastq2-2.20.0-GCC-12.2.0.eb bcl2fastq2-2.20.0-GCC-11.3.0.eb"

**Comment by branfosj** [comment]
@boegelbot please test @ jsc-zen2
EB_ARGS="bcl2fastq2-2.20.0-GCC-12.2.0.eb bcl2fastq2-2.20.0-GCC-11.3.0.eb"

**Comment by branfosj** [comment]
Test report by @branfosj
**SUCCESS**
Build succeeded for 4 out of 4 (4 easyconfigs in total)
bear-pg0105u03a.bear.cluster - Linux RHEL 8.6, x86_64, Intel(R) Xeon(R) Platinum 8360Y CPU @ 2.40GHz (icelake), Python 3.6.8
See https://gist.github.com/branfosj/0f260c264445697114c23abdd42a29fd for a full test report.

**Comment by branfosj** [comment]
@boegelbot please test @ jsc-zen2
EB_ARGS="bcl2fastq2-2.20.0-GCC-12.2.0.eb bcl2fastq2-2.20.0-GCC-11.3.0.eb --sanity-check-only"

**Review by branfosj — APPROVED** [review]

**Comment by branfosj** [comment]
Going in, thanks @verdurin!

**Pull request merged**
