### PR TITLE
remove modextrapaths to add top-level install directory to $PATH for recent InterProScan easyconfigs (now done by default by Binary easyblock)

### PR DESCRIPTION
**Pull request by Ghepardo**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by boegel** [comment]
@boegelbot please test @ generoso

**Comment by boegel** [comment]
Test report by @boegel
**FAILED**
Build succeeded for 1 out of 2 (2 easyconfigs in total)
node3100.skitty.os - Linux RHEL 8.4, x86_64, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz (skylake_avx512), Python 3.6.8
See https://gist.github.com/0e32e7221c7002e617e85dc052d7b027 for a full test report.

**Comment by Ghepardo** [comment]
That test failure looks as though it was for a different InterProScan version, for some reason (5.52-86 instead of 5.55.88).  Is any action required of me here?

**Comment by boegel** [comment]
@Ghepardo I was trying to make the fix a bit more consistent, by also updating the older InterProScan in the same way.

I'll look into the failing test, no action needed from you

**Comment by boegel** [comment]
Ah, the problem is that `InterProScan-5.52-86.0-GCCcore-10.3.0.eb` uses the `Tarball` easyblock, where the `modextrapaths` is actually still needed (it's only done automatically when the `Binary` easyblock is used, which is only the case for `InterProScan-5.55-88.0-foss-2021a.eb`).

**Comment by boegel** [comment]
@boegelbot please test @ jsc-zen2

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in total)
node3151.skitty.os - Linux RHEL 8.4, x86_64, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz (skylake_avx512), Python 3.6.8
See https://gist.github.com/9fddfc8a6ca30d9d04df0287e9471eb3 for a full test report.

**Review by boegel — APPROVED** [review]
lgtm

**Comment by boegel** [comment]
Going in, thanks @Ghepardo!

**Pull request merged**
