### PR TITLE
{bio}[foss/2019b] CaSpER v2.0

### PR DESCRIPTION
**Pull request by smoors**
(created using `eb --new-pr`)

this needs a recently updated R-3.6.2-foss-2019b.eb

### CODE REVIEW

**Comment by smoors** [comment]
Test report by @smoors
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
node317.hydra.os - Linux centos linux 7.7.1908, x86_64, Intel(R) Xeon(R) Gold 6148 CPU @ 2.40GHz (skylake_avx512), Python 2.7.5
See https://gist.github.com/931b1410823cc3ac3bc3390b819d96de for a full test report.

**Comment by smoors** [comment]
Test report by @smoors
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
node317.hydra.os - Linux centos linux 7.7.1908, x86_64, Intel(R) Xeon(R) Gold 6148 CPU @ 2.40GHz (skylake_avx512), Python 2.7.5
See https://gist.github.com/33cb1becd674e7f38d0ceaa18dd35b86 for a full test report.

**Comment by verdurin** [comment]
Test report by @verdurin
**SUCCESS**
Build succeeded for 5 out of 5 (1 easyconfigs in this PR)
easybuild.novalocal - Linux centos linux 7.8.2003, Intel Xeon Processor (Skylake, IBRS), Python 2.7.5
See https://gist.github.com/553f2e4a1dfd471e4fae669fbed7d3d0 for a full test report.

**Comment by verdurin** [comment]
Going in, thanks @smoors!

**Pull request merged**
