### PR TITLE
Rename CVS to ConcurrentVersionsSystem

### PR DESCRIPTION
**Pull request by Micket**
Due to Python not liking directories named CVS.

I thought we had an issue open on this somewhere but couldn't find it. Mentioned in the notes: https://github.com/easybuilders/easybuild/wiki/Conference-call-notes-20231011

### CODE REVIEW

**Comment by Micket** [comment]
Test report by @Micket
**FAILED**
Build succeeded for 0 out of 1 (1 easyconfigs in total)
alvis-c1 - Linux Rocky Linux 8.8, x86_64, Intel Xeon Processor (Skylake), Python 3.6.8
See https://gist.github.com/Micket/0b32a751fda13df17f139be38f149842 for a full test report.

**Comment by Micket** [comment]
Test report by @Micket
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
alvis-c1 - Linux Rocky Linux 8.8, x86_64, Intel Xeon Processor (Skylake), Python 3.6.8
See https://gist.github.com/Micket/ca62abc83704b8295ef33a7cb5bbef7d for a full test report.

**Comment by Micket** [comment]
@boeglebot please test @ generoso
EB_ARGS="ConcurrentVersionsSystem-1.11.23-GCCcore-11.2.0.eb"

**Comment by Micket** [comment]
@boegelbot please test @ jsc-zen2
EB_ARGS="ConcurrentVersionsSystem-1.11.23-GCCcore-11.2.0.eb"

**Review by boegel — APPROVED** [review]
lgtm

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
node3100.skitty.os - Linux RHEL 8.8, x86_64, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz (skylake_avx512), Python 3.6.8
See https://gist.github.com/boegel/78963205242864a3fa20d10aa3354f4e for a full test report.

**Pull request merged**
