### PR TITLE
{phys}[GCC/10.2.0] Geant4 v10.7.1 add missing cmake option to actually use external CLHEP

### PR DESCRIPTION
**Pull request by arielzn**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by arielzn** [comment]
on #12541 was pushed this Geant4 easyconfig together with CLHEP 

But in order to enable the Geant4 build to use the external CLHEP lib the  `-DCLHEP_ROOT_DIR=$EBROOTCLHEP`  option is required.

@bedroge  details of this can be [found here](https://github.com/Geant4/geant4/blob/3dfcdb544e19888c7a5979720ae09596207436f2/cmake/Modules/G4OptionalComponents.cmake#L29)

**Comment by lexming** [comment]
Test report by @lexming
**SUCCESS**
Build succeeded for 2 out of 2 (1 easyconfigs in total)
node381.hydra.os - Linux centos linux 7.9.2009, x86_64, Intel(R) Xeon(R) Gold 6148 CPU @ 2.40GHz, Python 2.7.5
See https://gist.github.com/a1e8adcb057b737d5a24dc88bf2d3347 for a full test report.

**Review by lexming — APPROVED** [review]
LGTM

**Comment by lexming** [comment]
Going in, thanks @arielzn !

**Pull request merged**
