### PR TITLE
{lib}[GCCcore/12.3.0] CharLS v2.4.2, jxrlib v1.1, libavif v1.0.4, ...

### PR DESCRIPTION
**Pull request by WilleBell**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by bedroge** [comment]
Test report by @bedroge
**FAILED**
Build succeeded for 5 out of 6 (5 easyconfigs in total)
interactive2 - Linux Rocky Linux 8.9, x86_64, AMD EPYC-Milan Processor (zen2), Python 3.6.8
See https://gist.github.com/bedroge/fe65ff6b72882a1d66454eba39d7e12b for a full test report.

**Comment by bedroge** [comment]
Test report by @bedroge
**FAILED**
Build succeeded for 9 out of 10 (5 easyconfigs in total)
bob-Latitude-5300 - Linux Ubuntu 22.04, x86_64, Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz, Python 3.10.12
See https://gist.github.com/bedroge/d2772d8875cf064f4f59eb63f6b6cfb4 for a full test report.

**Comment by bedroge** [comment]
On both systems I'm getting this error:
```
/data/apps/software/binutils/2.40-GCCcore-12.3.0/bin/ld: /data/apps/software/libwebp/1.3.1-GCCcore-12.3.0/lib/libsharpyuv.a(libsharpyuv_la-sharpyuv_csp.o): relocation R_X86_64_32S against `.rodata' can not be used when making a PIE object; recompile with -fPIE
/data/apps/software/binutils/2.40-GCCcore-12.3.0/bin/ld: failed to set dynamic section sizes: bad value
```
It does already seem to use `-fPIE` though...

**Comment by WilleBell** [comment]
> On both systems I'm getting this error:
> 
> ```
> /data/apps/software/binutils/2.40-GCCcore-12.3.0/bin/ld: /data/apps/software/libwebp/1.3.1-GCCcore-12.3.0/lib/libsharpyuv.a(libsharpyuv_la-sharpyuv_csp.o): relocation R_X86_64_32S against `.rodata' can not be used when making a PIE object; recompile with -fPIE
> /data/apps/software/binutils/2.40-GCCcore-12.3.0/bin/ld: failed to set dynamic section sizes: bad value
> ```
> 
> It does already seem to use `-fPIE` though...


> On both systems I'm getting this error:
> 
> ```
> /data/apps/software/binutils/2.40-GCCcore-12.3.0/bin/ld: /data/apps/software/libwebp/1.3.1-GCCcore-12.3.0/lib/libsharpyuv.a(libsharpyuv_la-sharpyuv_csp.o): relocation R_X86_64_32S against `.rodata' can not be used when making a PIE object; recompile with -fPIE
> /data/apps/software/binutils/2.40-GCCcore-12.3.0/bin/ld: failed to set dynamic section sizes: bad value
> ```
> 
> It does already seem to use `-fPIE` though...

My bad, I included the fix in a different PR (#20663), I moved it here now.

**Comment by bedroge** [comment]
Test report by @bedroge
**SUCCESS**
Build succeeded for 6 out of 6 (6 easyconfigs in total)
interactive1 - Linux Rocky Linux 8.9, x86_64, AMD EPYC-Milan Processor (zen2), Python 3.6.8
See https://gist.github.com/bedroge/5a36939c6f1a3387a9c47e9910193f7f for a full test report.

**Comment by bedroge** [comment]
Test report by @bedroge
**SUCCESS**
Build succeeded for 6 out of 6 (6 easyconfigs in total)
bob-Latitude-5300 - Linux Ubuntu 22.04, x86_64, Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz, Python 3.10.12
See https://gist.github.com/bedroge/cad7b63cf1d0c6ac9a37f647eab0621e for a full test report.

**Comment by bedroge** [comment]
@boegelbot please test @ generoso

**Comment by bedroge** [comment]
@boegelbot please test @ jsc-zen3

**Review by bedroge — APPROVED** [review]
Looks good to me.

**Comment by bedroge** [comment]
Going in, thanks @WilleBell!

**Comment by pavelToman** [comment]
> > On both systems I'm getting this error:
> > ```
> > /data/apps/software/binutils/2.40-GCCcore-12.3.0/bin/ld: /data/apps/software/libwebp/1.3.1-GCCcore-12.3.0/lib/libsharpyuv.a(libsharpyuv_la-sharpyuv_csp.o): relocation R_X86_64_32S against `.rodata' can not be used when making a PIE object; recompile with -fPIE
> > /data/apps/software/binutils/2.40-GCCcore-12.3.0/bin/ld: failed to set dynamic section sizes: bad value
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > It does already seem to use `-fPIE` though...
> 
> > On both systems I'm getting this error:
> > ```
> > /data/apps/software/binutils/2.40-GCCcore-12.3.0/bin/ld: /data/apps/software/libwebp/1.3.1-GCCcore-12.3.0/lib/libsharpyuv.a(libsharpyuv_la-sharpyuv_csp.o): relocation R_X86_64_32S against `.rodata' can not be used when making a PIE object; recompile with -fPIE
> > /data/apps/software/binutils/2.40-GCCcore-12.3.0/bin/ld: failed to set dynamic section sizes: bad value
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > It does already seem to use `-fPIE` though...
> 
> My bad, I included the fix in a different PR (#20663), I moved it here now.

I hit the same error with `libjxl` due to `libwebp` and the fix was: `toolchainopts = {'extra_cflags': '-fPIE'}`

**Pull request merged**
