### PR TITLE
{chem}[foss/2018b,intel/2017b] Amber v18

### PR DESCRIPTION
**Pull request by akesandgren**
(created using `eb --new-pr`)
Amber 18.8 AmberTools 18.10. Needs patches from PR ~~#7092~~. Amber 18 complains and refuses to build if one uses Intel 2018 so only intel/2017b used here.

### CODE REVIEW

**Comment by akesandgren** [comment]
Test report by @akesandgren
**SUCCESS**
Build succeeded for 4 out of 4 (4 easyconfigs in this PR)
b-an02.hpc2n.umu.se - Linux ubuntu 16.04, Intel(R) Xeon(R) CPU E5-2690 v4 @ 2.60GHz, Python 2.7.12
See https://gist.github.com/801e8daadf69aeb803ad23f318124c09 for a full test report.

**Comment by vanzod** [comment]
Test report by @vanzod
**FAILED**
Build succeeded for 6 out of 8 (4 easyconfigs in this PR)
cermis - Linux debian 9.5, Intel(R) Xeon(R) CPU           E5620  @ 2.40GHz, Python 2.7.13
See https://gist.github.com/34616d61fcc4de93894d1f0a32b191e4 for a full test report.

**Comment by branfosj** [comment]
#### Test result
Build succeeded for 2 out of 2

#### Overview of tested easyconfigs (in order)
 * **SUCCESS** _Boost.Python-1.67.0-foss-2018b-Python-2.7.15.eb_ 
 * **SUCCESS** _Amber-18-foss-2018b-AmberTools-18-patchlevel-10-8.eb_ 

https://gist.github.com/branfosj/3f94bdb9140660077dd3a03fa67b001d

**Comment by boegel** [comment]
(close/open to re-trigger Travis)

**Comment by akesandgren** [comment]
Test report by @akesandgren
**FAILED**
Build succeeded for 2 out of 4 (4 easyconfigs in this PR)
b-cn0315.hpc2n.umu.se - Linux ubuntu 16.04, Intel(R) Xeon(R) CPU E5-2690 v4 @ 2.60GHz, Python 2.7.12
See https://gist.github.com/5320225c255889b3ec999d81a892a956 for a full test report.

**Comment by akesandgren** [comment]
Test report by @akesandgren
**SUCCESS**
Build succeeded for 4 out of 4 (4 easyconfigs in this PR)
b-cn0315.hpc2n.umu.se - Linux ubuntu 16.04, Intel(R) Xeon(R) CPU E5-2690 v4 @ 2.60GHz, Python 2.7.12
See https://gist.github.com/892513a0570fbf6f9fd01b202d97ebc4 for a full test report.

**Comment by vanzod** [comment]
Test report by @vanzod
**FAILED**
Build succeeded for 2 out of 4 (4 easyconfigs in this PR)
cermis - Linux debian 9.7, Intel(R) Xeon(R) CPU           X5670  @ 2.93GHz, Python 2.7.13
See https://gist.github.com/5f0a8b0e0fd8123e49a08827e1776730 for a full test report.

**Comment by vanzod** [comment]
Test report coming soon

**Comment by vanzod** [comment]
Test report by @vanzod
**FAILED**
Build succeeded for 2 out of 4 (4 easyconfigs in this PR)
cermis - Linux debian 9.7, Intel(R) Xeon(R) CPU           X5670  @ 2.93GHz, Python 2.7.13
See https://gist.github.com/5d77a55741389e087f857f4499cf9ec3 for a full test report.

**Comment by vanzod** [comment]
Test report by @vanzod
**SUCCESS**
Build succeeded for 4 out of 4 (4 easyconfigs in this PR)
cermis - Linux debian 9.7, Intel(R) Xeon(R) CPU           X5670  @ 2.93GHz, Python 2.7.13
See https://gist.github.com/2268a8cd788b0d3455e64bdd21b3e879 for a full test report.

**Comment by akesandgren** [comment]
@boegel anything else??

**Comment by boegel** [comment]
Going in, thanks @akesandgren!

**Pull request merged**
