### PR TITLE
{bio}[GCC/11.2.0] RNA-Bloom-1.4.3

### PR DESCRIPTION
**Pull request by wdlingit**
added RNA-Bloom-1.4.3-GCC-11.2.0.eb

### CODE REVIEW

**Comment by wdlingit** [comment]
This one is depending on #15378

**Comment by migueldiascosta** [comment]
@boegelbot please test @ generoso

**Review by migueldiascosta — APPROVED** [review]
lgtm

**Comment by migueldiascosta** [comment]
Going in, thanks @wdlingit!

**Pull request merged**
