### PR TITLE
{bio}[foss/2021b] DROP v1.1.1, tMAE v1.0.1 w/ Python 3.9.6

### PR DESCRIPTION
**Pull request by zemu-unile**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by zemu-unile** [comment]
Depens on wget #14864 and graphviz #14863

**Comment by lexming** [comment]
Test report by @lexming
**FAILED**
Build succeeded for 34 out of 40 (2 easyconfigs in total)
node305.hydra.os - Linux centos linux 7.9.2009, x86_64, Intel(R) Xeon(R) Gold 6148 CPU @ 2.40GHz, Python 2.7.5
See https://gist.github.com/19941282304ca411361c80d70bd8d341 for a full test report.

**Comment by lexming** [comment]
@boegelbot: please test @ generoso

**Review by lexming — APPROVED** [review]
LGTM

**Comment by lexming** [comment]
Going in, thanks @zemu-unile !

**Pull request merged**
