### PR TITLE
{bio}[GCCcore/8.2.0] BEDTools v2.28.0

### PR DESCRIPTION
**Pull request by murfreesboro**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by murfreesboro** [comment]
Test report by @murfreesboro
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
dev806.vampire - Linux centos linux 7.4.1708, Intel(R) Xeon(R) CPU           E5620  @ 2.40GHz, Python 2.7.5
See https://gist.github.com/4efe1afaa587e3ef64db2ad416f97c0a for a full test report.

**Comment by vanzod** [comment]
Test report by @vanzod
**FAILED**
Build succeeded for 0 out of 1 (1 easyconfigs in this PR)
cermis - Linux debian 9.9, Intel(R) Xeon(R) CPU           X5670  @ 2.93GHz, Python 2.7.13
See https://gist.github.com/a371af70c334e7a26f82560eaec84700 for a full test report.

**Comment by vanzod** [comment]
@murfreesboro It looks like the required `bzip2` dependency is missing.

**Comment by vanzod** [comment]
@murfreesboro Since `BEDTools` is performance oriented, it may be a good thing to build it with `GCC` and `iccifort` instead of `GCCcore` to take advantage of potential compiler optimizations.

**Comment by verdurin** [comment]
Test report by @verdurin
**FAILED**
Build succeeded for 0 out of 1 (1 easyconfigs in this PR)
easybuild.novalocal - Linux centos linux 7.6.1810, Intel Xeon Processor (Skylake, IBRS), Python 2.7.5
See https://gist.github.com/d8591c35af9bf8d2dbbfe43a4524340c for a full test report.

**Comment by verdurin** [comment]
@murfreesboro Just to confirm, here is the build error because `bzip2` is missing:
```
- Building in src/intersectFile
  * compiling intersectHelp.cpp
gcc -g -Wall -O2 -I.  -c -o cram/cram_io.o cram/cram_io.c
cram/cram_io.c:57:10: fatal error: bzlib.h: No such file or directory
 #include <bzlib.h>
          ^~~~~~~~~
compilation terminated.
make[1]: *** [cram/cram_io.o] Error 1
make[1]: *** Waiting for unfinished jobs....
  * compiling intersectFile.cpp
make: *** [src/utils/htslib] Error 2
make: *** Waiting for unfinished jobs....
```

**Comment by murfreesboro** [comment]
Test report by @murfreesboro
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in this PR)
dev806.vampire - Linux centos linux 7.4.1708, Intel(R) Xeon(R) CPU           E5620  @ 2.40GHz, Python 2.7.5
See https://gist.github.com/b9d13e7ebf1a10c611c647dea3f7fee5 for a full test report.

**Comment by murfreesboro** [comment]
GCC version already exist. Let me delete the GCC one

**Comment by murfreesboro** [comment]
by the way, it seems BAMTools is included as dependency. I checked the codes it seems to have the bam file conversion part. So I will include the bamtools dependency as well.

**Comment by murfreesboro** [comment]
Test report by @murfreesboro
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
dev806.vampire - Linux centos linux 7.4.1708, Intel(R) Xeon(R) CPU           E5620  @ 2.40GHz, Python 2.7.5
See https://gist.github.com/ccaac6fdb3b70aedc129743e7bbc0bad for a full test report.

**Comment by vanzod** [comment]
Test report by @vanzod
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
cermis - Linux debian 9.9, Intel(R) Xeon(R) CPU           X5670  @ 2.93GHz, Python 2.7.13
See https://gist.github.com/74011fbb7f13fb3a3feb449fb6d57578 for a full test report.

**Comment by vanzod** [comment]
Going in, thanks @murfreesboro!

**Pull request merged**
