### PR TITLE
{bio,devel}[foss/2023a] DeepLoc v2.0, ONNX-Runtime v1.19.2 w/ CUDA 12.1.1

### PR DESCRIPTION
**Pull request by boegel**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in total)
node3900.accelgor.os - Linux RHEL 8.8, x86_64, AMD EPYC 7413 24-Core Processor, 1 x NVIDIA NVIDIA A100-SXM4-80GB, 545.23.08, Python 3.6.8
See https://gist.github.com/boegel/a57ff50e55b0c2b41c2ae4f07769fa5b for a full test report.

**Comment by boegel** [comment]
When testing this, `pip check` was failing in the sanity check for `DeepLoc` with:
```
fastapi 0.110.0 has requirement typing-extensions>=4.8.0, but you have typing-extensions 4.6.3
```

I had to reinstall both `expecttest/0.1.5-GCCcore-12.3.0` and `BeautifulSoup/4.12.3-GCCcore-13.3.0` to fix this, because the modules I had in place still had `poetry` or `hatchling` as runtime dependency, which was fixed in:
* #19675
* #20546

**Comment by boegel** [comment]
@boegelbot please test @ jsc-zen3-a100

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in total)
node3309.joltik.os - Linux RHEL 8.8, x86_64, Intel(R) Xeon(R) Gold 6242 CPU @ 2.80GHz, 1 x NVIDIA Tesla V100-SXM2-32GB, 545.23.08, Python 3.6.8
See https://gist.github.com/boegel/1342db4299599943c67539fe90b4066b for a full test report.

**Review by laraPPr — APPROVED** [review]
lgtm

**Comment by laraPPr** [comment]
Going in, thanks @boegel!

**Pull request merged**
