### PR TITLE
Remove dead dotNET codes.

### PR DESCRIPTION
**Pull request by Micket**
Net-core, dotNET-Core-Runtime, dotNET-SDK are replaced with "dotNET-Core"  https://github.com/easybuilders/easybuild-easyconfigs/pull/20256

These software packages are abandoned, or not running on a supported dotNET 6.0 or newer.

Needs adding to archive repo, but i'm not sure how to preserve history.

More details on:
https://github.com/easybuilders/easybuild-easyconfigs/issues/11504#issuecomment-2028825827

New MetaMorpheus:
- https://github.com/easybuilders/easybuild-easyconfigs/pull/20258
Rest of the software was adbandoned and won't run on a supported dotNET SDK.

Someone with access to sources should attempt a new MaxQuant-2.5.1.0 (either using Mono or dotNET 6.0 or 8.0)

### CODE REVIEW

**Comment by boegel** [comment]
@lexming Can you help with adding these to the easyconfigs archive, with history preserved?

**Review by lexming — CHANGES_REQUESTED** [review]
Wait until PR to archive repo is open. Otherwise it is a bit more work to move these easyconfigs there.

**Review by lexming — APPROVED** [review]
Archival in https://github.com/easybuilders/easybuild-easyconfigs-archive/pull/4

LGTM

**Comment by lexming** [comment]
Merging, thanks @Micket !

**Pull request merged**
