### PR TITLE
{bio}[foss/2023a] CheckM2 v1.0.2

### PR DESCRIPTION
**Pull request by boegel**
(created using `eb --new-pr`)
requires:
* #20391

### CODE REVIEW

**Comment by boegel** [comment]
@boegelbot please test @ generoso

**Comment by boegel** [comment]
@boegelbot please test @ jsc-zen3

**Comment by pavelToman** [comment]
Have you try to download database ($ checkm2 database –download –path $EBROOTCHECKM2) and run the $ checkm2 testrun? It hits a lot of errors for me like:
```
File "/apps/gent/RHEL8/cascadelake-ib/software/SciPy-bundle/2023.07-gfbf-2023a/lib/python3.11/site-packages/pandas/core/strings/accessor.py", line 129, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: StringMethods.split() takes from 1 to 2 positional arguments but 3 positional arguments (and 1 keyword-only argument) were given
```
-> seems the version of pandas should be v1.4.0 not v2.0.3
```
Traceback (most recent call last):
  File "/scratch/gent/vo/001/gvo00117/easybuild/RHEL8/cascadelake-ampere-ib/software/CheckM2/1.0.2-foss-2023a/bin/checkm2", line 267, in <module>
    predictor.prediction_wf(False, 'auto', False, False, False)
  File "/scratch/gent/vo/001/gvo00117/easybuild/RHEL8/cascadelake-ampere-ib/software/CheckM2/1.0.2-foss-2023a/lib/python3.11/site-packages/checkm2/predictQuality.py", line 204, in prediction_wf
    vector_array = feature_vectors.iloc[:, 1:].values.astype(np.float)
                                                             ^^^^^^^^
  File "/apps/gent/RHEL8/cascadelake-ib/software/SciPy-bundle/2023.07-gfbf-2023a/lib/python3.11/site-packages/numpy/__init__.py", line 313, in __getattr__
    raise AttributeError(__former_attrs__[attr])
    AttributeError: module 'numpy' has no attribute 'float'.
    `np.float` was a deprecated alias for the builtin `float`. To avoid this error in existing code, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
```
-> it needs to patch the np.float: sed /np.float/float/ in checkm2/predictQuality.py
```
[04/11/2024 04:44:24 PM] INFO: Predicting completeness and contamination using ML models.
Traceback (most recent call last):
  File "/scratch/gent/vo/001/gvo00117/easybuild/RHEL8/cascadelake-ampere-ib/software/CheckM2/1.0.2-foss-2023a/bin/checkm2", line 267, in <module>
    predictor.prediction_wf(False, 'auto', False, False, False)
  File "/scratch/gent/vo/001/gvo00117/easybuild/RHEL8/cascadelake-ampere-ib/software/CheckM2/1.0.2-foss-2023a/lib/python3.11/site-packages/checkm2/predictQuality.py", line 214, in prediction_wf
    specific_result_comp, scaled_features = modelProc.run_prediction_specific(vector_array, specific_model_vector_len)
                                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/scratch/gent/vo/001/gvo00117/easybuild/RHEL8/cascadelake-ampere-ib/software/CheckM2/1.0.2-foss-2023a/lib/python3.11/site-packages/checkm2/modelProcessing.py", line 68, in run_prediction_specific
    scaled_vector = self.minmax_scaler.transform(vector_array)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/scratch/gent/vo/001/gvo00117/easybuild/RHEL8/cascadelake-ampere-ib/software/scikit-learn/1.3.1-gfbf-2023a/lib/python3.11/site-packages/sklearn/utils/_set_output.py", line 157, in wrapped
    data_to_wrap = f(self, X, *args, **kwargs)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/scratch/gent/vo/001/gvo00117/easybuild/RHEL8/cascadelake-ampere-ib/software/scikit-learn/1.3.1-gfbf-2023a/lib/python3.11/site-packages/sklearn/preprocessing/_data.py", line 525, in transform
    if self.clip:
       ^^^^^^^^^
AttributeError: 'MinMaxScaler' object has no attribute 'clip'
```
-> there is too new version (v1.3.1) of sklearn, it needs old one v0.23.2
AND finally:
```
Traceback (most recent call last):
  File "/scratch/gent/vo/001/gvo00117/easybuild/RHEL8/cascadelake-ampere-ib/software/CheckM2/1.0.2-foss-2023a/bin/checkm2", line 267, in <module>
    predictor.prediction_wf(False, 'auto', False, False, False)
  File "/scratch/gent/vo/001/gvo00117/easybuild/RHEL8/cascadelake-ampere-ib/software/CheckM2/1.0.2-foss-2023a/lib/python3.11/site-packages/checkm2/predictQuality.py", line 227, in prediction_wf
    final_comp, final_cont, model_chosen, csm_array = postProcessor.calculate_general_specific_ratio(
                                                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/scratch/gent/vo/001/gvo00117/easybuild/RHEL8/cascadelake-ampere-ib/software/CheckM2/1.0.2-foss-2023a/lib/python3.11/site-packages/checkm2/modelPostprocessing.py", line 110, in calculate_general_specific_ratio
    comp_results = pd.DataFrame({'General': general_comp,
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/scratch/gent/vo/001/gvo00117/easybuild/RHEL8/cascadelake-ampere-ib/software/CheckM2/1.0.2-foss-2023a/lib/python3.11/site-packages/pandas/core/frame.py", line 637, in __init__
    mgr = dict_to_mgr(data, index, columns, dtype=dtype, copy=copy, typ=manager)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/scratch/gent/vo/001/gvo00117/easybuild/RHEL8/cascadelake-ampere-ib/software/CheckM2/1.0.2-foss-2023a/lib/python3.11/site-packages/pandas/core/internals/construction.py", line 502, in dict_to_mgr
    return arrays_to_mgr(arrays, columns, index, dtype=dtype, typ=typ, consolidate=copy)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/scratch/gent/vo/001/gvo00117/easybuild/RHEL8/cascadelake-ampere-ib/software/CheckM2/1.0.2-foss-2023a/lib/python3.11/site-packages/pandas/core/internals/construction.py", line 125, in arrays_to_mgr
    arrays = _homogenize(arrays, index, dtype)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/scratch/gent/vo/001/gvo00117/easybuild/RHEL8/cascadelake-ampere-ib/software/CheckM2/1.0.2-foss-2023a/lib/python3.11/site-packages/pandas/core/internals/construction.py", line 625, in _homogenize
    val = sanitize_array(
          ^^^^^^^^^^^^^^^
  File "/scratch/gent/vo/001/gvo00117/easybuild/RHEL8/cascadelake-ampere-ib/software/CheckM2/1.0.2-foss-2023a/lib/python3.11/site-packages/pandas/core/construction.py", line 588, in sanitize_array
    data = list(data)
File "/apps/gent/RHEL8/cascadelake-ib/software/SciPy-bundle/2023.07-gfbf-2023a/lib/python3.11/site-packages/scipy/sparse/_base.py", line 252, in __iter__
yield self[r, :]
  ~~~~^^^^^^
TypeError: 'coo_matrix' object is not subscriptable
```
-> this one is from Scipy and I was unable to fix, it needs probably scipy 1.8.x
So I went for foss/2022a toolchain and the testrun passed.

**Comment by pavelToman** [comment]
I try to do `testrun` with your easyconfig and hit: `[04/19/2024 01:09:08 PM] ERROR: Make sure prodigal is on your system path.` seems prodigal dependency is missing.

**Comment by boegel** [comment]
closing this, superseded by #20399

**Pull request closed without merging**
