### PR TITLE
add patches for Ambertools 21 to Amber 20.11 to work with new easyblock

### PR DESCRIPTION
**Pull request by zemu-unile**
(created using `eb --new-pr`)
Patches were taken from #16151

### CODE REVIEW

**Comment by zemu-unile** [comment]
I am not sure why, but the patches were not required for the fosscuda variant https://github.com/zemu-unile/easybuild-easyconfigs/blob/20220930160030_new_pr_Amber2011/easybuild/easyconfigs/a/Amber/Amber-20.11-fosscuda-2020b-AmberTools-21.3.eb

**Comment by zemu-unile** [comment]
Tests depend on #16245

**Comment by akesandgren** [comment]
> I am not sure why, but the patches were not required for the fosscuda variant https://github.com/zemu-unile/easybuild-easyconfigs/blob/20220930160030_new_pr_Amber2011/easybuild/easyconfigs/a/Amber/Amber-20.11-fosscuda-2020b-AmberTools-21.3.eb

That's because that specific easyconfig doesn't run the tests at all.

**Review by akesandgren — DISMISSED** [review]
LGTM

**Comment by akesandgren** [comment]
Test report by @akesandgren
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
b-an02.hpc2n.umu.se - Linux Ubuntu 20.04, x86_64, Intel(R) Xeon(R) CPU E5-2690 v4 @ 2.60GHz, Python 3.8.10
See https://gist.github.com/5ff6ec9a51c7d0c67b75b383b716a452 for a full test report.

**Comment by akesandgren** [comment]
We need https://github.com/easybuilders/easybuild-framework/pull/4093 to make alt_location and patch checksumming work for Amber since there are old versions of at least one patch still in Amber while we now use the one from AmberTools.

**Review by akesandgren — APPROVED** [review]
LGTM

**Pull request merged**
