### PR TITLE
fix failing 'make check' for MPFR 4.x when installing with 'eb --rpath'

### PR DESCRIPTION
**Pull request by boegel**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 5 out of 5 (5 easyconfigs in this PR)
node3170.skitty.os - Linux centos linux 7.8.2003, x86_64, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz (skylake_avx512), Python 3.6.8
See https://gist.github.com/a07ea83403cfcbad9575604ee5f1e3f0 for a full test report.

**Comment by boegel** [comment]
@boegelbot please test @ generoso
EB_ARGS="MPFR-4.0.1-GCCcore-7.3.0.eb MPFR-4.0.2-GCCcore-8.2.0.eb MPFR-4.0.2-GCCcore-8.3.0.eb MPFR-4.0.2-GCCcore-9.3.0.eb --rpath -f --installpath /tmp/pr11187"

**Comment by boegel** [comment]
Don't merge this yet please, needs more love...

**Comment by boegel** [comment]
Should be good to go now...

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 5 out of 5 (5 easyconfigs in this PR)
node3108.skitty.os - Linux centos linux 7.8.2003, x86_64, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz (skylake_avx512), Python 3.6.8
See https://gist.github.com/0485b42e474649ee86febaaf1162d5c8 for a full test report.

**Review by smoors — APPROVED** [review]
lgtm

**Comment by smoors** [comment]
Going in, thanks @boegel!

**Pull request merged**
