### PR TITLE
{bio}[foss/2020b] carputils v20210513, openCARP v6.0, meshtool v16, meshalyzer v2.2 w/ Python 3.8.6

### PR DESCRIPTION
**Pull request by boegel**
(created using `eb --new-pr`)
requires ~~#12461~~ (VTK)

### CODE REVIEW

**Comment by boegel** [comment]
@boegelbot please test @ generoso

**Comment by verdurin** [comment]
Test report by @verdurin
**FAILED**
Build succeeded for 11 out of 18 (7 easyconfigs in total)
nuc.lan - Linux Fedora 33, x86_64, Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz, Python 3.9.2
See https://gist.github.com/68cb895c6989b9ff42104e80f94df030 for a full test report.

**Comment by boegel** [comment]
@verdurin Test failed with `No space left on device`, can you try again?

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 7 out of 7 (7 easyconfigs in total)
node3552.doduo.os - Linux RHEL 8.2, x86_64, AMD EPYC 7552 48-Core Processor (zen2), Python 3.6.8
See https://gist.github.com/beecdf2226f1a3666dc4d9d68730ae4c for a full test report.

**Comment by verdurin** [comment]
Test report by @verdurin
**FAILED**
Build succeeded for 0 out of 7 (7 easyconfigs in total)
nuc.lan - Linux Fedora 33, x86_64, Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz, Python 3.9.2
See https://gist.github.com/6ce891f2460a8d68cca3bccd85f7cc75 for a full test report.

**Comment by verdurin** [comment]
Test report by @verdurin
**SUCCESS**
Build succeeded for 20 out of 20 (7 easyconfigs in total)
easybuild-c7.novalocal - Linux centos linux 7.9.2009, x86_64, Intel Xeon Processor (Skylake, IBRS), Python 3.6.8
See https://gist.github.com/4b907ada7eef8dc65cd530db600c9e86 for a full test report.

**Comment by verdurin** [comment]
Test report by @verdurin
**FAILED**
Build succeeded for 4 out of 7 (7 easyconfigs in total)
nuc.lan - Linux Fedora 33, x86_64, Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz, Python 3.9.2
See https://gist.github.com/6f07306200261eb47b3de0c9385c198c for a full test report.

**Comment by boegel** [comment]
@verdurin Hmm, VTK failed with:

```
-- Could NOT find Python3 (missing: Development.Module) (found suitable version "3.9.2", minimum required is "3.2")
CMake Error at CMake/vtkModule.cmake:4145 (message):
  Could not find the Python3 external dependency.
  ```

But we include `Python` 3.8.6 as a dependency, so I don't see how that can fail.

Can you check what went wrong there, and perhaps open an issue on it?

**Comment by boegel** [comment]
@boegelbot please test @ generoso

**Comment by boegel** [comment]
I marked this as WIP because the researcher reported some problems with this installation.

It's unclear whether the issue is with carputils or with the openCARP 5.0 dependency at this point, hopefully we'll get a better view on that soon...

The software is functional, but seems to be producing slightly incorrect results.

**Comment by boegel** [comment]
@boegelbot please test @ generoso

**Comment by boegel** [comment]
Updated to latest `openCARP` and `carputils` versions, keeping as WIP for now until I hear back from the researchers to see if these versions work as expected...

**Comment by boegel** [comment]
The researchers have confirmed that the installations provided via these easyconfigs work as expected, so this should be good to go now...

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 7 out of 7 (7 easyconfigs in total)
node3561.doduo.os - Linux RHEL 8.2, x86_64, AMD EPYC 7552 48-Core Processor (zen2), Python 3.6.8
See https://gist.github.com/09638f4d048d7f6f5896ba0bbc961207 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 7 out of 7 (7 easyconfigs in total)
select-pika-c6gd-2xlarge-0002 - Linux centos linux 8.3.2011, AArch64, ARM UNKNOWN (graviton2), Python 3.6.8
See https://gist.github.com/1fb3464930772f9e5ed4d2c8e69caba7 for a full test report.

**Comment by verdurin** [comment]
Test report by @verdurin
**SUCCESS**
Build succeeded for 3 out of 3 (7 easyconfigs in total)
easybuild-c7.novalocal - Linux centos linux 7.9.2009, x86_64, Intel Xeon Processor (Skylake, IBRS), Python 3.6.8
See https://gist.github.com/01fbd09a338d66e21ef7dc0882253bf3 for a full test report.

**Review by verdurin — APPROVED** [review]
Looks fine.

**Comment by verdurin** [comment]
Going in, thanks @boegel!

**Pull request merged**
