### PR TITLE
{perf}[GCCcore/12.2.0] Score-P v8.1, SIONlib v1.7.7, PDT v3.25.1, ... w/ CUDA 12.0.0, tools

### PR DESCRIPTION
**Pull request by Flamefire**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by Flamefire** [comment]
Test report by @Flamefire
**SUCCESS**
Build succeeded for 12 out of 12 (9 easyconfigs in total)
taurusml4 - Linux RHEL 7.6, POWER, 8335-GTX (power9le), 6 x NVIDIA Tesla V100-SXM2-32GB, 440.64.00, Python 2.7.5
See https://gist.github.com/Flamefire/25aed844f068af570e99e99fdc25eb1a for a full test report.

**Comment by casparvl** [comment]
@boegelbot please test @ generoso

**Comment by casparvl** [comment]
Test report by @casparvl
**FAILED**
Build succeeded for 8 out of 9 (9 easyconfigs in total)
tcn445.local.snellius.surf.nl - Linux RHEL 8.6, x86_64, AMD EPYC 7H12 64-Core Processor, Python 3.6.8
See https://gist.github.com/casparvl/c38ed0f2222465c7077b4da4d55e0816 for a full test report.

**Comment by casparvl** [comment]
Ignore that failure, it was a lock file hanging around from a build that was interrupted...

**Comment by casparvl** [comment]
@boegelbot please test @ jsc-zen2

**Review by casparvl — APPROVED** [review]
Lgtm!

**Comment by casparvl** [comment]
Going in, thanks @Flamefire!

**Pull request merged**
