### PR TITLE
{math}[foss/2019b] Octave v5.1.0

### PR DESCRIPTION
**Pull request by furstj**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by verdurin** [comment]
@furstj Does `Octave` need the newer version of `ICU`? Or could it use the same as everything else?

**Comment by furstj** [comment]
@verdurin the ICU version goes down to HarfBuzz. Is it possible to downgrade ICU in already merged HarfBuzz? How can I do it?

**Comment by boegel** [comment]
Issue with ICU dependency fixed in #9842

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
node2411.golett.os - Linux centos linux 7.7.1908, Intel(R) Xeon(R) CPU E5-2680 v3 @ 2.50GHz, Python 2.7.5
See https://gist.github.com/11e98b79758bce487e6e8db5a097171c for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
generoso-1 - Linux centos linux 7.6.1810, Intel(R) Xeon(R) CPU E5-2660 v4 @ 2.00GHz, Python 3.6.8
See https://gist.github.com/9cca0f0d7cb38e303d84d13d0bc80a9a for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 4 out of 4 (1 easyconfigs in this PR)
node3134.skitty.os - Linux centos linux 7.7.1908, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz, Python 3.6.8
See https://gist.github.com/8ec16bd942b9e541578a8678b7a9b203 for a full test report.

**Comment by boegel** [comment]
Going in, thanks @furstj!

**Pull request merged**
