### PR TITLE
{cae}[foss/2022b] OpenFOAM vv2306

### PR DESCRIPTION
**Pull request by Micket**
(created using `eb --new-pr`)

- [x] #18351

### CODE REVIEW

**Comment by furstj** [comment]
Hi,

there is an improved patch OpenFOAM-v2212-wmake-OpenMPI.patch in #17496. Can you try/update it also for this OF version?

**Comment by Micket** [comment]
Test report by @Micket
**FAILED**
Build succeeded for 0 out of 1 (1 easyconfigs in total)
vera-c1 - Linux Rocky Linux 8.7, x86_64, Intel Xeon Processor (Skylake), Python 3.6.8
See https://gist.github.com/Micket/a2627f11693b60799508879fdd03fc44 for a full test report.

**Comment by dilasgoi** [comment]
Using the patch mentioned by @furstj in #17496 (only a path adjustment to OpenFOAM's topdir is needed to match the version) and compiling the code with the C++14 standard, the code compiles without error on my Rocky 8.7 platform:

```
toolchainopts = {'usempi': True, 'cstd': 'c++14', 'vectorize': False}
```

I have not tested it further.

**Comment by Micket** [comment]
Test report by @Micket
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
vera-c1 - Linux Rocky Linux 8.7, x86_64, Intel Xeon Processor (Skylake), Python 3.6.8
See https://gist.github.com/Micket/cb91b417fd5436ea4855098510bedf95 for a full test report.

**Comment by branfosj** [comment]
@boegelbot please test @ generoso
CORE_CNT=16

**Comment by branfosj** [comment]
@boegelbot please test @ jsc-zen2
CORE_CNT=16

**Comment by branfosj** [comment]
Going in, thanks @Micket!

**Pull request merged**
