### PR TITLE
add GCCcore-13.2.0_fix-unguarded-is_convertible-builtin.patch

### PR DESCRIPTION
**Pull request by Louwrensth**
(created using `eb --new-pr`)

### CODE REVIEW

**Review by Micket — APPROVED** [review]
lgtm, but the issue seems to indicate that this is only a problem is one is using an older icc? But maybe "older" is relative here, our intel toolchains shouldn't be particularly old.

**Comment by Micket** [comment]
@boegelbot please test @ generoso

**Comment by Micket** [comment]
@boegelbot please test @ jsc-zen3

**Comment by Louwrensth** [comment]
> lgtm, but the issue seems to indicate that this is only a problem is one is using an older icc? But maybe "older" is relative here, our intel toolchains shouldn't be particularly old.

I stumbled upon the problem (while hacking for #20213) that `icc` from 2023b broke with this `GCCcore-13.2.0`, it is probably related to:
> Note: Intel® C++ Compiler Classic doesn't support GCC 13 compatibility mode. For GCC 13 compatibility mode, please transition to Intel®  oneAPI DPC++/C++ Compiler. 
(https://www.intel.com/content/www/us/en/developer/articles/release-notes/oneapi-c-compiler-release-notes.html)

From https://gcc.gnu.org/bugzilla/show_bug.cgi?id=113241 it is considered a bug in the GCC repo. I might be the only one going against the warning above and expecting the `intel/2023b` (without OneAPI selected) to work with GCC 13.2.0, but who knows? 😁

Thanks for reviewing!

**Comment by Micket** [comment]
Test report by @Micket
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
vera-skylake-build - Linux Rocky Linux 8.9, x86_64, Intel Xeon Processor (Skylake, IBRS, no TSX), Python 3.6.8
See https://gist.github.com/Micket/ae575ea6f7c71d04fbffcf5ae954236e for a full test report.

**Pull request merged**
