### PR TITLE
{data,vis}[GCCcore/9.3.0,foss/2020a] econml v0.8.0b1, Graphviz v2.44.1 w/ Python 3.8.2

### PR DESCRIPTION
**Pull request by smoors**
(created using `eb --new-pr`)

depends on ~~#11763~~

### CODE REVIEW

**Comment by verdurin** [comment]
@smoors missing `GTS`?

**Comment by smoors** [comment]
> @smoors missing `GTS`?

indeed, now added.

**Comment by boegel** [comment]
Test report by @boegel
**FAILED**
Build succeeded for 2 out of 3 (3 easyconfigs in total)
node3575.doduo.os - Linux RHEL 8.2, x86_64, AMD EPYC 7552 48-Core Processor (zen2), Python 3.6.8
See https://gist.github.com/1c55da5bfb11ec0f1068d49895a4518f for a full test report.

**Comment by boegel** [comment]
@smoors `pip check` fails:

```
econml 0.8.0b1 has requirement tensorflow<2.3,>1.10, but you have tensorflow 2.3.1.
```

Maybe check with `econml` whether that version restriction is a bit too strict?

**Comment by smoors** [comment]
filed issue for this: https://github.com/microsoft/EconML/issues/352

**Review by jfgrimm — COMMENTED** [review]
As decided in issue #16330, we have deprecated the use of `True` to signify a system-toolchain dependency (#16384), in favour of the more intuitive `SYSTEM` template constant. Due to the change in the test suite, please run `eb --sync-pr-with-develop 11765` and update the PR to use `SYSTEM` instead.

**Comment by smoors** [comment]
old version, not gonna work on this anymore, closing

**Pull request closed without merging**
