### PR TITLE
{math}[foss/2022a] rustworkx v0.12.1 w/ Python 3.10.4

### PR DESCRIPTION
**Pull request by Micket**
(created using `eb --new-pr`)

- [x] new cargo easyblock https://github.com/easybuilders/easybuild-easyblocks/pull/2902
- [x] https://github.com/easybuilders/easybuild-easyblocks/pull/2934

### CODE REVIEW

**Comment by verdurin** [comment]
Test report by @verdurin
Using easyblocks from PR(s) https://github.com/easybuilders/easybuild-easyblocks/pull/2902
**FAILED**
Build succeeded for 0 out of 1 (1 easyconfigs in total)
easybuild-c7.novalocal - Linux CentOS Linux 7.9.2009, x86_64, Intel Xeon Processor (Skylake, IBRS), Python 3.6.8
See https://gist.github.com/verdurin/f3c25caad0fb66f3949b8933e863f56c for a full test report.

**Comment by verdurin** [comment]
```
 error: failed to get `ahash` as a dependency of package `rustworkx-core v0.12.1 (/dev/shm/rustworkx/0.12.1/foss-2022a/rustworkx-0.12.1/rustworkx-core)`

  Caused by:
    failed to load source for dependency `ahash`

  Caused by:
    Unable to update registry `crates-io`

  Caused by:
    failed to update replaced source registry `crates-io`

  Caused by:
    failed to read root of directory source: /dev/shm/rustworkx/0.12.1/foss-2022a/vendored-sources

  Caused by:
    No such file or directory (os error 2)
```

**Comment by Micket** [comment]
@verdurin could you do me a favor and check what you have in
```
ls -a /dev/shm/rustworkx/0.12.1/foss-2022a/
```
and
```
cat /dev/shm/rustworkx/0.12.1/foss-2022a/.cargo/config.toml
```

**Comment by verdurin** [comment]
```
$ ls -a /dev/shm/rustworkx/0.12.1/foss-2022a/
.                        fixedbitset-0.4.2     memchr-2.5.0        parking_lot_core-0.8.5      rand-0.8.5            serde_derive-1.0.145
..                       getrandom-0.2.6       memoffset-0.6.5     petgraph-0.6.2              rand_chacha-0.3.1     serde_json-1.0.89
ahash-0.7.6              hashbrown-0.11.2      ndarray-0.13.1      ppv-lite86-0.2.16           rand_core-0.6.3       smallvec-1.8.0
autocfg-1.1.0            hermit-abi-0.1.19     num-bigint-0.4.3    priority-queue-1.2.0        rand_pcg-0.3.1        syn-1.0.96
bitflags-1.3.2           indexmap-1.7.0        num-complex-0.2.4   proc-macro2-1.0.39          rawpointer-0.2.1      target-lexicon-0.12.4
.cargo                   indoc-1.0.6           num-complex-0.4.1   pyo3-0.17.3                 rayon-1.5.3           unicode-ident-1.0.0
cfg-if-1.0.0             instant-0.1.12        num_cpus-1.13.1     pyo3-build-config-0.17.3    rayon-core-1.9.3      unindent-0.1.9
crossbeam-channel-0.5.4  itoa-1.0.2            num-integer-0.1.45  pyo3-ffi-0.17.3             redox_syscall-0.2.13  version_check-0.9.4
crossbeam-deque-0.8.1    lazy_static-1.4.0     numpy-0.17.2        pyo3-macros-0.17.3          rustworkx-0.12.1      wasi-0.10.2+wasi-snapshot-preview1
crossbeam-epoch-0.9.8    libc-0.2.126          num-traits-0.2.15   pyo3-macros-backend-0.17.3  ryu-1.0.10            winapi-0.3.9
crossbeam-utils-0.8.8    lock_api-0.4.7        once_cell-1.12.0    quick-xml-0.22.0            scopeguard-1.1.0      winapi-i686-pc-windows-gnu-0.4.0
either-1.6.1             matrixmultiply-0.2.4  parking_lot-0.11.2  quote-1.0.18                serde-1.0.145         winapi-x86_64-pc-windows-gnu-0.4.0
```

**Comment by verdurin** [comment]
```
$ cat /dev/shm/rustworkx/0.12.1/foss-2022a/.cargo/config.toml
[source.vendored-sources]
directory = "/dev/shm/rustworkx/0.12.1/foss-2022a"

[source.crates-io]
directory = "vendored-sources"
```

**Comment by Micket** [comment]
Test report by @Micket
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
vera-c1 - Linux Rocky Linux 8.7, x86_64, Intel Xeon Processor (Skylake), Python 3.6.8
See https://gist.github.com/Micket/b7888d1ee415c13835f359a7f4cf58d8 for a full test report.

**Comment by Micket** [comment]
Test report by @Micket
Using easyblocks from PR(s) https://github.com/easybuilders/easybuild-easyblocks/pull/2902
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
vera-c1 - Linux Rocky Linux 8.7, x86_64, Intel Xeon Processor (Skylake), Python 3.6.8
See https://gist.github.com/Micket/8a9ac32cc23f31674543f16151821c4e for a full test report.

**Comment by Micket** [comment]
@verdurin easyblock had a bug i introduced, fixed now. `directory = "vendored-sources"` should have been `replace-with = "vendored-sources"`

**Comment by Micket** [comment]
Test report by @Micket
Using easyblocks from PR(s) https://github.com/easybuilders/easybuild-easyblocks/pull/2902
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
vera-c1 - Linux Rocky Linux 8.7, x86_64, Intel Xeon Processor (Skylake), Python 3.6.8
See https://gist.github.com/Micket/7ba5783587904c958c190e0e756eec24 for a full test report.

**Comment by jfgrimm** [comment]
Test report by @jfgrimm
Using easyblocks from PR(s) https://github.com/easybuilders/easybuild-easyblocks/pull/2902
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
node068.pri.viking.alces.network - Linux CentOS Linux 7.9.2009, x86_64, Intel(R) Xeon(R) Gold 6138 CPU @ 2.00GHz (skylake_avx512), Python 3.6.8
See https://gist.github.com/jfgrimm/6224db96843d98bc753d5670b9779c55 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
Using easyblocks from PR(s) https://github.com/easybuilders/easybuild-easyblocks/pull/2902
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
node3165.skitty.os - Linux RHEL 8.6, x86_64, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz (skylake_avx512), Python 3.6.8
See https://gist.github.com/boegel/c4152221e9a367ad6f14457a892450a9 for a full test report.

**Comment by boegel** [comment]
@boegelbot please test @ generoso
EB_ARGS="--include-easyblocks-from-pr 2934"

**Review by boegel — APPROVED** [review]
lgtm

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
node3165.skitty.os - Linux RHEL 8.6, x86_64, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz (skylake_avx512), Python 3.6.8
See https://gist.github.com/boegel/7ffa0ec072864b91d43c74dba5693238 for a full test report.

**Comment by boegel** [comment]
Going in, thanks @Micket!

**Pull request merged**
