### PR TITLE
{bio}[foss/2018b] sciClone v1.1

### PR DESCRIPTION
**Pull request by smoors**
(created using `eb --new-pr`)
needs ~~#7807~~

### CODE REVIEW

**Comment by smoors** [comment]
Test report by @smoors
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
nic26 - Linux centos linux 7.5.1804, Intel(R) Xeon(R) Gold 6148 CPU @ 2.40GHz, Python 2.7.5
See https://gist.github.com/30bac259931b72da6cbc6683f48fcc43 for a full test report.

**Comment by smoors** [comment]
closing and reopening to retrigger travis

**Comment by smoors** [comment]
Test report by @smoors
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
nic410 - Linux centos linux 7.5.1804, Intel(R) Xeon(R) Gold 6148 CPU @ 2.40GHz, Python 2.7.5
See https://gist.github.com/dbba2667828d47cf9394fb93538790ad for a full test report.

**Comment by migueldiascosta** [comment]
Test report by @migueldiascosta
**FAILED**
Build succeeded for 0 out of 1 (1 easyconfigs in this PR)
sms - Linux centos linux 7.6.1810, AMD EPYC 7601 32-Core Processor, Python 2.7.5
See https://gist.github.com/2fed3a652ee8ae17d7f3ab4173852d15 for a full test report.

**Comment by migueldiascosta** [comment]
can't find `MKmisc` source?

**Comment by migueldiascosta** [comment]
Test report by @migueldiascosta
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
sms - Linux centos linux 7.6.1810, AMD EPYC 7601 32-Core Processor, Python 2.7.5
See https://gist.github.com/bd79cba2722a8d3fbf5eda3d9c3dbb00 for a full test report.

**Comment by smoors** [comment]
Test report by @smoors
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
node308.hydra.os - Linux centos linux 7.6.1810, Intel(R) Xeon(R) Gold 6148 CPU @ 2.40GHz, Python 2.7.5
See https://gist.github.com/24d27698a8c71a44d8c9b6d1d64f2d91 for a full test report.

**Comment by migueldiascosta** [comment]
Going in, thanks @smoors!

**Pull request merged**
