### PR TITLE
{tools}[GCCcore/10.3.0] jupyterlab-lmod v1.0.2, jupyterlmod v3.0.0, jupyter-server v1.13.4 + add jupyter-server dependency to JupyterLab

### PR DESCRIPTION
**Pull request by lexming**
(created using `eb --new-pr`)

Depends on:
* [x] #16529

Soft dependency for consistency:
* #16556

### CODE REVIEW

**Comment by lexming** [comment]
@boegelbot: please test @ generoso

**Comment by boegel** [comment]
@lexming PR title suggests changes to IPython, but only JupyterLab easyconfig is touched?

**Comment by lexming** [comment]
@boegel the Lmod extensions have their own easyconfigs:
* jupyterlmod-3.0.0-GCCcore-10.3.0.eb is for IPython
* jupyterlab-lmod-1.0.2-GCCcore-10.3.0.eb is for JupyterLab

**Comment by lexming** [comment]
@boegel after the sync with `develop`, the only extra thing that remains in JupyterLab is the split of `jupyter-server` into its own easyconfig. This is harmless and I did it to keep parity with newer toolchains, we already have the same arrangement in `GCCcore/11.3.0`. If you prefer a different PR for that change let me know.

**Comment by boegel** [comment]
@lexming Wasn't it your intention of adding `jupyterlmod` as a dependency to `IPython`?

**Comment by lexming** [comment]
@boegel `jupyterlmod` depends on IPython because it's an extension of IPython, it works without JupyterLab.

**Comment by boegel** [comment]
Test report by @boegel
**FAILED**
Build succeeded for 3 out of 4 (4 easyconfigs in total)
node3100.skitty.os - Linux RHEL 8.6, x86_64, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz (skylake_avx512), Python 3.6.8
See https://gist.github.com/6c78da6fe71d7e0656539be1909176be for a full test report.

**Comment by lexming** [comment]
@boegel that's a weird issue, the permission error happens inside the installation directory of `jupyterlab-lmod` during its `postinstall` step. So it should already exist and be writable. Did something else fail before that point?

**Comment by boegel** [comment]
> @boegel that's a weird issue, the permission error happens inside the installation directory of `jupyterlab-lmod` during its `postinstall` step. So it should already exist and be writable. Did something else fail before that point?

That setup is configured with `--read-only-installdir`, that's likely related...

**Comment by lexming** [comment]
Superseded by #17888

**Pull request closed without merging**
