### PR TITLE
{lib}[GCC/11.3.0] nghttp2 v0.7.0

### PR DESCRIPTION
**Pull request by iotaka**
requires:
* #16972
* #16974

### CODE REVIEW

**Comment by iotaka** [comment]
requires:
* #16972
* #16974
* #16973

**Review by smoors — CHANGES_REQUESTED** [review]
@iotaka please add back the author comment, see `ngtcp2-0.7.0-GCC-11.2.0.eb`

**Comment by iotaka** [comment]
re added

# Author: J. Sassmannshausen (Imperial College London/UK)

**Comment by smoors** [comment]
@boegelbot: please test @ generoso

**Comment by smoors** [comment]
@boegelbot please test @ jsc-zen2

**Review by smoors — APPROVED** [review]
lgtm

**Comment by smoors** [comment]
Going in, thanks @iotaka!

**Comment by branfosj** [comment]
Test report by @branfosj
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
bear-pg0105u03a.bear.cluster - Linux RHEL 8.6, x86_64, Intel(R) Xeon(R) Platinum 8360Y CPU @ 2.40GHz (icelake), Python 3.6.8
See https://gist.github.com/branfosj/fb7b88fb634c21ab235d24d31e3b883e for a full test report.

**Pull request merged**
