### PR TITLE
{bio}[GCC/11.3.0,GCCcore/11.3.0,foss/2022a] PIPITS v3.0, ITSx v1.1.3, FASTX-Toolkit v0.0.14 w/ Python 3.10.4

### PR DESCRIPTION
**Pull request by bedroge**
(created using `eb --new-pr`)

I've added a bunch of sanity check commands for `FASTX-Toolkit`, which immediately revealed an issue:
```
$ fasta_clipping_histogram.pl -h
Can't locate GD/Graph/bars.pm in @INC (you may need to install the GD::Graph::bars module)
```
Fixed this by adding `GDGraph` as dependency.

### CODE REVIEW

**Comment by bedroge** [comment]
Test report by @bedroge
**SUCCESS**
Build succeeded for 4 out of 4 (3 easyconfigs in total)
bob-Latitude-5300 - Linux Ubuntu 22.04, x86_64, Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz, Python 3.10.6
See https://gist.github.com/1e24e2c86e72ca9649e832c9ec2064aa for a full test report.

**Comment by bedroge** [comment]
@boegelbot please test @ generoso

**Comment by bedroge** [comment]
> Test report by @casparvl **FAILED** Build succeeded for 2 out of 5 (3 easyconfigs in total) tcn493.local.snellius.surf.nl - Linux Rocky Linux 8.7, x86_64, AMD EPYC 7H12 64-Core Processor, Python 3.6.8 See https://gist.github.com/c1f0438024d7f6fda478f105cc2c744b for a full test report.

```
Sanity check failed: No '(RPATH)' found in 'readelf -d' output for /scratch-nvme/1/casparl/generic/software/SeqKit/2.3.1/bin/seqkit: 
Dynamic section at offset 0xb1d020 contains 19 entries:
  Tag        Type                         Name/Value
 0x0000000000000004 (HASH)               0xbceb80
 0x0000000000000006 (SYMTAB)             0xbcf0c0
 0x000000000000000b (SYMENT)             24 (bytes)
 0x0000000000000005 (STRTAB)             0xbcee60
 0x000000000000000a (STRSZ)              591 (bytes)
 0x0000000000000007 (RELA)               0xbce718
 0x0000000000000008 (RELASZ)             24 (bytes)
 0x0000000000000009 (RELAENT)            24 (bytes)
 0x0000000000000003 (PLTGOT)             0xf1d160
 0x0000000000000015 (DEBUG)              0x0
 0x0000000000000001 (NEEDED)             Shared library: [libpthread.so.0]
 0x0000000000000001 (NEEDED)             Shared library: [libc.so.6]
 0x000000006ffffffe (VERNEED)            0xbceac0
 0x000000006fffffff (VERNEEDNUM)         2
 0x000000006ffffff0 (VERSYM)             0xbceb20
 0x0000000000000014 (PLTREL)             RELA
 0x0000000000000002 (PLTRELSZ)           912 (bytes)
 0x0000000000000017 (JMPREL)             0xbce730
 0x0000000000000000 (NULL)               0x0
```

This again :-) But do you know how this works for binaries compiled with Go?

**Comment by bedroge** [comment]
@boegelbot please test @ generoso

**Comment by bedroge** [comment]
Test report by @bedroge
**SUCCESS**
Build succeeded for 3 out of 3 (3 easyconfigs in total)
bob-Latitude-5300 - Linux Ubuntu 22.04, x86_64, Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz, Python 3.10.6
See https://gist.github.com/2b56eb18f4366043766092d9b2e06a66 for a full test report.

**Comment by bedroge** [comment]
/
@boegelbot please test @ generoso

**Comment by casparvl** [comment]
> This again :-) But do you know how this works for binaries compiled with Go?

My colleague reported this _other_ issue https://github.com/easybuilders/easybuild-easyconfigs/issues/17516
I checked the GoPackage EasyBlock, and it doesn't skip the RPATH check. The only thing I cannot confirm (because I didn't dive into it) is that GoPackage _should_ skip the RPATH check. I know too little about Go packages... Are these essentially binary installs?

**Comment by casparvl** [comment]
@boegelbot please test @ jsc-zen2

**Comment by casparvl** [comment]
Test report by @casparvl
**SUCCESS**
Build succeeded for 3 out of 3 (3 easyconfigs in total)
tcn480.local.snellius.surf.nl - Linux Rocky Linux 8.7, x86_64, AMD EPYC 7H12 64-Core Processor, Python 3.6.8
See https://gist.github.com/casparvl/e9cbbda183337739a3bfc2308be8c36b for a full test report.

**Review by casparvl — APPROVED** [review]
Lgtm!

**Comment by casparvl** [comment]
Going in, thanks @bedroge!

**Pull request merged**
