### PR TITLE
{data,lib}[foss/2023b,gompi/2023b] netcdf4-python v1.6.5, mpi4py v3.1.5

### PR DESCRIPTION
**Pull request by SimonPinches**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by SimonPinches** [comment]
This PR depends upon PR #19535.

**Comment by smoors** [comment]
@boegelbot: please test @ generoso

**Comment by smoors** [comment]
@boegelbot please test @ jsc-zen2

**Review by smoors — APPROVED** [review]
lgtm

**Comment by smoors** [comment]
Going in, thanks @SimonPinches!

**Pull request merged**
