### PR TITLE
use correct Matlab Runtime Compiler (v8.4) for FreeSurfer v7.1.1

### PR DESCRIPTION
**Pull request by btlindert**
(created using `eb --new-pr`)

### CODE REVIEW

**Review by Micket — DISMISSED** [review]
ok, i guess this looks good to me. 
Normally, modifying existing easyconfigs is something to strive to avoid. Perhaps this is a case where the runtime version should be added as a suffix to the easyconfig, to allow it to be distinguished. Though, reading the homepage, it seems like it should have been version 8.4 all along? I'm not entirely sure here.

**Comment by Micket** [comment]
any opinion on this @sassy-crick ?

**Comment by sassy-crick** [comment]
Looking at the [documentation](https://surfer.nmr.mgh.harvard.edu/fswiki/MatlabRuntime) it looks like the correct MCR is 8.4. I guess that would qualify as a patch-fix. There was no particular reason for me to pick the older version, I probably have just used the already existing EC file as a template and did not dig any deeper as it all was "working" for me. 
Maybe we should add a comment that the MCR and FeeSurfer versions are linked?

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 3 out of 3 (3 easyconfigs in total)
node3100.skitty.os - Linux RHEL 8.4, x86_64, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz (skylake_avx512), Python 3.6.8
See https://gist.github.com/edecbbe2784e78d86a060d4aa2855e46 for a full test report.

**Review by boegel — APPROVED** [review]
lgtm

**Comment by boegel** [comment]
Going in, thanks @btlindert!

**Pull request merged**
