### PR TITLE
{bio}[gompi/2023a] Kraken2 v2.1.3

### PR DESCRIPTION
**Pull request by PetrKralCZ**
(created using `eb --new-pr`)
resolves https://github.com/vscentrum/vsc-software-stack/issues/434

### CODE REVIEW

**Comment by PetrKralCZ** [comment]
@boegelbot please test @ generoso

**Comment by PetrKralCZ** [comment]
@boegelbot please test @ generoso

**Comment by PetrKralCZ** [comment]
@boegelbot please test @ jsc-zen3

**Comment by verdurin** [comment]
Test report by @verdurin
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
easybuild-el8.cloud.in.bmrc.ox.ac.uk - Linux Rocky Linux 8.10, x86_64, Intel Xeon Processor (Skylake, IBRS), Python 3.6.8
See https://gist.github.com/verdurin/e458e13a32a41e60d44644631ab868ba for a full test report.

**Review by verdurin — APPROVED** [review]
Looks fine.

**Comment by verdurin** [comment]
Going in, thanks @PetrKralCZ!

**Pull request merged**
