### PR TITLE
{bio}[GCCcore/13.2.0] CapnProto v1.0.1.1

### PR DESCRIPTION
**Pull request by SimonPinches**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by jfgrimm** [comment]
@boegelbot: please test @ generoso

**Comment by jfgrimm** [comment]
Test report by @jfgrimm
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
node099.viking2.yor.alces.network - Linux Rocky Linux 8.8, x86_64, AMD EPYC 7643 48-Core Processor, Python 3.6.8
See https://gist.github.com/jfgrimm/d9f4822a5fd39ef80f8897f16c97b5bb for a full test report.

**Comment by jfgrimm** [comment]
@boegelbot: please test @ jsc-zen2

**Review by akesandgren — APPROVED** [review]
LGTM

**Comment by akesandgren** [comment]
Going in, thanks @SimonPinches!

**Pull request merged**
