### PR TITLE
{astro}[system/system] CASA v6.5.5-21

### PR DESCRIPTION
**Pull request by Micket**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by Micket** [comment]
So, just like stuff like matlab etc. this probably has like a million OS dependencies. Only expect this to work on RHEL8 derivatives. Not really any feasible way to add osdeps for this

**Comment by Micket** [comment]
Test report by @Micket
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
vera-c1 - Linux Rocky Linux 8.7, x86_64, Intel Xeon Processor (Skylake), Python 3.6.8
See https://gist.github.com/Micket/024dab481f95ca1440d4de2f0e6468f5 for a full test report.

**Comment by casparvl** [comment]
@boegelbot please test @ generoso

**Comment by casparvl** [comment]
Test report by @casparvl
**SUCCESS**
Build succeeded for 0 out of 0 (1 easyconfigs in total)
tcn399.local.snellius.surf.nl - Linux Rocky Linux 8.7, x86_64, AMD EPYC 7H12 64-Core Processor, Python 3.6.8
See https://gist.github.com/casparvl/7d0b32c1ffbc8d8e28e27cf0d34bd8ea for a full test report.

**Comment by casparvl** [comment]
Test report by @casparvl
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
tcn399.local.snellius.surf.nl - Linux Rocky Linux 8.7, x86_64, AMD EPYC 7H12 64-Core Processor, Python 3.6.8
See https://gist.github.com/casparvl/36f419e3c6f3d8fa1507b946b2002d06 for a full test report.

**Comment by casparvl** [comment]
@boegelbot please test @ jsc-zen2

**Comment by casparvl** [comment]
@boegelbot please test @ jsc-zen2

**Comment by Micket** [comment]
```
== 2023-06-08 12:02:21,784 filetools.py:838 WARNING IOError occurred while trying to download https://casa.nrao.edu/download/distro/casa/release/rhel/casa-6.5.5-21-py3.8.tar.xz to /project/def-maintainers/boegelbot/sources/c/CASA/casa-6.5.5-21-py3.8.tar.xz: <urlopen error _ssl.c:880: The handshake operation timed out>
```

this is new to me

**Comment by casparvl** [comment]
How about this: what if you put in a comment above the `source_url` line saying that _on some systems_ the download might result in error XYZ, reference the failed `jsc-zen2` test, and suggest to try with `wget` or from a different machine? And then we just merge the PR like that?

At least that way we'll leave a hint if others run into this issue.

**Review by casparvl — APPROVED** [review]
Lgtm!

**Comment by casparvl** [comment]
Going in, thanks @Micket!

**Pull request merged**
