### PR TITLE
{bio}[system/system] CellRanger v9.0.0

### PR DESCRIPTION
**Pull request by PhoenixEmik**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by PhoenixEmik** [comment]
Test report by @PhoenixEmik
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
rocky-8-build - Linux Rocky Linux 8.10, x86_64, AMD Ryzen 7 7840HS w/ Radeon 780M Graphics, Python 3.6.8
See https://gist.github.com/PhoenixEmik/e69d41bae8a46368eca93b71f0cd674e for a full test report.

**Comment by verdurin** [comment]
Test report by @verdurin
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
easybuild-el8.cloud.in.bmrc.ox.ac.uk - Linux Rocky Linux 8.10, x86_64, Intel Xeon Processor (Skylake, IBRS), Python 3.6.8
See https://gist.github.com/verdurin/fe5cadf4138e9751edde9cdfa2b5f584 for a full test report.

**Review by verdurin — APPROVED** [review]
Looks fine.

**Comment by verdurin** [comment]
Going in, thanks @PhoenixEmik!

**Pull request merged**
