### PR TITLE
{devel}[foss/2019b] PyTorch v1.3.1 w/ Python 3.7.4

### PR DESCRIPTION
**Pull request by branfosj**
(created using `eb --new-pr`)

requires ~~#9282~~ (SciPy-bundle), ~~#9269~~ (PyYAML), ~~#9316~~ (glog), ~~#9315~~ (gflags), ~~#9317~~ (hypothesis)

### CODE REVIEW

**Comment by branfosj** [comment]
Test report by @branfosj
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
bear-pg0211u03a.bear.cluster - Linux centos linux 7.6.1810, Intel(R) Xeon(R) Gold 6248 CPU @ 2.50GHz, Python 2.7.5
See https://gist.github.com/652c6fd1e8528ab2d08ee16c769436e9 for a full test report.

**Comment by branfosj** [comment]
Test report by @branfosj
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
bber0501u03a.bb2.cluster - Linux centos linux 7.6.1810, Intel(R) Xeon(R) CPU E5-2690 v3 @ 2.60GHz, Python 2.7.5
See https://gist.github.com/58ace4befe039a172495b02d6a731196 for a full test report.

**Comment by branfosj** [comment]
Test report by @branfosj
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
bb2c1a09.bb2.cluster - Linux centos linux 7.6.1810, Intel(R) Xeon(R) CPU E5-2660 0 @ 2.20GHz, Python 2.7.5
See https://gist.github.com/1ca58677d59680dbac9151c7f5473b24 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
node3156.skitty.os - Linux centos linux 7.7.1908, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz, Python 3.6.8
See https://gist.github.com/633659932c4c75924916139d1713c705 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
generoso - Linux centos linux 7.6.1810, Intel(R) Xeon(R) CPU E5-2660 v4 @ 2.00GHz, Python 3.6.8
See https://gist.github.com/851be2a99927dd2d5333af123087a90b for a full test report.

**Comment by boegel** [comment]
@branfosj Looks good to go, but needs a sync with `develop` now ~~#9317~~ is merged

**Comment by branfosj** [comment]
I slipped the sync with develop in while generating test reports - https://github.com/easybuilders/easybuild-easyconfigs/pull/9320/commits/f6748fff09872f3603e18d09467837f52dccdd06

```
$ git pull github_easybuilders develop
From http://github.com/easybuilders/easybuild-easyconfigs
 * branch            develop    -> FETCH_HEAD
Already up-to-date.
$ git push origin 20191117122216_new_pr_PyTorch131
Username for 'http://github.com': branfosj
Password for 'http://branfosj@github.com': 
Everything up-to-date
```

**Comment by boegel** [comment]
> I slipped the sync with develop in while generating test reports - [f6748ff](https://github.com/easybuilders/easybuild-easyconfigs/commit/f6748fff09872f3603e18d09467837f52dccdd06)

My apologies, completely overlooked that! Thanks!

**Comment by boegel** [comment]
Going in, thanks @branfosj!

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
node3302.joltik.os - Linux centos linux 7.7.1908, Intel(R) Xeon(R) Gold 6242 CPU @ 2.80GHz, Python 2.7.5
See https://gist.github.com/736cd2673fc0a626e6a4f2edf81f352b for a full test report.

**Pull request merged**
