### PR TITLE
{lib}[intel/2017b] mkl-dnn v0.11

### PR DESCRIPTION
**Pull request by boegel**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in this PR)
node2707.swalot.os - Linux centos linux 7.4.1708, Intel(R) Xeon(R) CPU E5-2660 v3 @ 2.60GHz, Python 2.7.5
See https://gist.github.com/97bce1c3fe2715f7431ac49dde8a8376 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in this PR)
node2042.delcatty.os - Linux centos linux 7.4.1708, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.7.5
See https://gist.github.com/873abf3033a454cebc8b80527d5db54d for a full test report.

**Comment by verdurin** [comment]
Going in, thanks @boegel!

**Comment by boegel** [comment]
I tried also enabling `make test` for this, and saw that one of the tests is failing, also when I set the `precise` or disable the `optarch` toolchain options...

**Comment by boegel** [comment]
Follow up on failing test in https://github.com/01org/mkl-dnn/issues/151; I can't get it to pass, even by disabling `optarch` and enabling `precise` and `lowopt` toolchain options...

**Pull request merged**
