### PR TITLE
{bio}[foss/2023a] OpenMM v8.0.0 w/ CUDA 12.1.1

### PR DESCRIPTION
**Pull request by jfgrimm**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by migueldiascosta** [comment]
@boegelbot please test @ jsc-zen3

**Comment by jfgrimm** [comment]
Test report by @jfgrimm
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
gpu25.viking2.yor.alces.network - Linux Rocky Linux 8.9, x86_64, AMD EPYC 7413 24-Core Processor, 1 x NVIDIA NVIDIA H100 PCIe, 535.161.08, Python 3.6.8
See https://gist.github.com/jfgrimm/c38876c07299d8939ace95dbf9b34216 for a full test report.

**Comment by boegel** [comment]
All CUDA tests on `jsc-zen3` failed, no surprise since there's no CUDA drivers:
```
Error initializing CUDA: CUDA erro
```

**Review by boegel — APPROVED** [review]
lgtm

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
node3906.accelgor.os - Linux RHEL 8.8, x86_64, AMD EPYC 7413 24-Core Processor, 4 x NVIDIA NVIDIA A100-SXM4-80GB, 545.23.08, Python 3.6.8
See https://gist.github.com/boegel/b19012d035a615ecc461561e0ace7c6b for a full test report.

**Comment by boegel** [comment]
One failing test on our V100 system, but:

```
257/295 Test #257: TestCudaDrudeNoseHooverSingle .............***Failed   14.52 sec
exception: Assertion failure at TestDrudeNoseHoover.h:293.  Expected 1, found 0.989693 (This test is stochastic and may occasionally fail)
```

So looks good to ignore...

**Comment by boegel** [comment]
Going in, thanks @jfgrimm!

**Pull request merged**
