### PR TITLE
{compiler}[GCCcore/7.2.0] LLVM 7.0.0

### PR DESCRIPTION
**Pull request by rubendibattista**

### CODE REVIEW

**Comment by boegel** [comment]
(close/re-open to pick up updated tests in Travis, since it's been a while...)

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 6 out of 6 (6 easyconfigs in this PR)
node3118.skitty.os - Linux centos linux 7.6.1810, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz, Python 2.7.5
See https://gist.github.com/5315afc4d76181a69f2c952e6d79cb29 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 6 out of 6 (6 easyconfigs in this PR)
node2406.golett.os - Linux centos linux 7.6.1810, Intel(R) Xeon(R) CPU E5-2680 v3 @ 2.50GHz, Python 2.7.5
See https://gist.github.com/0d6613e854b93a822178f4ec036fca41 for a full test report.

**Comment by boegel** [comment]
Going in, thanks @rubendibattista!

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 6 out of 6 (6 easyconfigs in this PR)
node2039.delcatty.os - Linux centos linux 7.6.1810, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.7.5
See https://gist.github.com/da886cfb51b490b7b61145eb64fbe291 for a full test report.

**Comment by Flamefire** [comment]
@rubendibattista Where did all the CMake configure arguments came from? They were not included in the older CMake ECs and may cause problems.

**Comment by rubendibattista** [comment]
@Flamefire I don't remember why, but I think it was selfcompiling the dependent libraries instead of using the already compiled ones...

**Comment by Flamefire** [comment]
Yes this is possible because modules do not set CMAKE_PREFIX_PATH yet (see https://github.com/easybuilders/easybuild-framework/issues/2624). Can you check if https://github.com/easybuilders/easybuild-easyblocks/pull/1936 would work for you when you remove the `easyblock =` line and all `configopts` line from your cmake EC? That EB should be superior as it allows very short ECs for CMake.

Another Idea I had: In the CMakeMake EB add all dependencies to CMAKE_PREFIX_PATH if they are not already in there. Basically what I'm doing in the CMake EB too.

**Comment by rubendibattista** [comment]
I think it would work... At the moment I have no time to check that, but I guess adding deps to the cmake prefix should work. The only thing is to be sure that the building environment is well isolated from the system (such that it cannot get system installed stuff before the ones in the CMAKE_PREFIX_PATH)

**Comment by Flamefire** [comment]
According to https://cmake.org/cmake/help/latest/command/find_library.html it does work: The only thing coming before CMAKE_PREFIX_PATH is <Package>_ROOT

**Pull request merged**
