### PR TITLE
{chem}[GCC/10.3.0] Libint v2.6.0

### PR DESCRIPTION
**Pull request by robert-mijakovic**
(created using `eb --new-pr`)
Depends on
- [x] https://github.com/easybuilders/easybuild-easyconfigs/pull/12977

### CODE REVIEW

**Comment by robert-mijakovic** [comment]
@boegelbot please test @ generoso EB_ARGS="--include-easyconfigs-from-pr 12977"

**Comment by robert-mijakovic** [comment]
@boegelbot please test @ generoso

**Comment by SebastianAchilles** [comment]
Test report by @sebastianachilles
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
jsfc061 - Linux centos linux 7.9.2009, x86_64, AMD EPYC 7742 64-Core Processor, Python 3.6.8
See https://gist.github.com/aac689841148bf995ff5fbd1be82c090 for a full test report.

**Review by SebastianAchilles — APPROVED** [review]
lgtm

**Comment by SebastianAchilles** [comment]
Going in, thanks @robert-mijakovic!

**Comment by SebastianAchilles** [comment]
Going in, thanks @robert-mijakovic!

**Pull request merged**
