### PR TITLE
{chem}[intel/2023a] NWChem v7.2.2

### PR DESCRIPTION
**Pull request by smoors**
(created using `eb --new-pr`)

depends on
- https://github.com/easybuilders/easybuild-easyblocks/pull/3049

### CODE REVIEW

**Comment by smoors** [comment]
@boegelbot: please test @ generoso
EB_ARGS="--include-easyblocks-from-pr=3049"

**Comment by smoors** [comment]
@boegelbot please test @ jsc-zen2
EB_ARGS="--include-easyblocks-from-pr=3049"

**Comment by branfosj** [comment]
Test report by @branfosj
Using easyblocks from PR(s) https://github.com/easybuilders/easybuild-easyblocks/pull/3049
**SUCCESS**
Build succeeded for 2 out of 2 (1 easyconfigs in total)
bear-pg0105u03a - Linux RHEL 8.6, x86_64, Intel(R) Xeon(R) Platinum 8360Y CPU @ 2.40GHz (icelake), Python 3.6.8
See https://gist.github.com/branfosj/085c8ca8d3b890d783f5a16061897596 for a full test report.

**Comment by smoors** [comment]
Test report by @smoors
Using easyblocks from PR(s) https://github.com/easybuilders/easybuild-easyblocks/pull/3049
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
node300.hydra.os - Linux Rocky Linux 8.8, x86_64, Intel(R) Xeon(R) Gold 6148 CPU @ 2.40GHz (skylake_avx512), Python 3.6.8
See https://gist.github.com/smoors/562d885544faa76df71940ef80c2682e for a full test report.

**Comment by smoors** [comment]
@boegelbot please test @ jsc-zen2
EB_ARGS="--include-easyblocks-from-pr=3049 --ignore-locks"

**Comment by smoors** [comment]
@boegelbot: please test @ generoso
 EB_ARGS="--include-easyblocks-from-pr=3049"

**Comment by smoors** [comment]
@boegelbot please test @ jsc-zen2
EB_ARGS="--include-easyblocks-from-pr=3049"

**Comment by branfosj** [comment]
Test report by @branfosj
Using easyblocks from PR(s) https://github.com/easybuilders/easybuild-easyblocks/pull/3049
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
bear-pg0105u03b - Linux RHEL 8.6, x86_64, Intel(R) Xeon(R) Platinum 8360Y CPU @ 2.40GHz (icelake), Python 3.6.8
See https://gist.github.com/branfosj/979bd8f1c2abb9a9681548a181e85242 for a full test report.

**Review by branfosj — APPROVED** [review]

**Comment by branfosj** [comment]
Going in, thanks @smoors!

**Pull request merged**
