### PR TITLE
also define $AUGUSTUS_BIN_PATH and $AUGUSTUS_SCRIPTS_PATH in generated module file for AUGUSTUS

### PR DESCRIPTION
**Pull request by boegel**

### CODE REVIEW

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 7 out of 7 (7 easyconfigs in this PR)
node2412.golett.os - Linux centos linux 7.7.1908, Intel(R) Xeon(R) CPU E5-2680 v3 @ 2.50GHz, Python 2.7.5
See https://gist.github.com/ddf05c815b5c2c4cc5bb4548af7ca81f for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
node2412.golett.os - Linux centos linux 7.7.1908, Intel(R) Xeon(R) CPU E5-2680 v3 @ 2.50GHz, Python 2.7.5
See https://gist.github.com/fcb5e99ad048a44fd14f4be0a0cb088e for a full test report.

**Comment by akesandgren** [comment]
Travis hung, kicking

**Comment by akesandgren** [comment]
Travis kicked

**Comment by akesandgren** [comment]
@boegel travis has gotten hung two times in a row now. Check the output. No idea why this one doesn't work.

**Comment by akesandgren** [comment]
Test report by @akesandgren
**FAILED**
Build succeeded for 34 out of 35 (7 easyconfigs in this PR)
b-an03.hpc2n.umu.se - Linux ubuntu 16.04, Intel(R) Xeon(R) CPU E5-2690 v4 @ 2.60GHz, Python 2.7.12
See https://gist.github.com/faf03fdefad99295b5cb781adc88b0d2 for a full test report.

**Comment by akesandgren** [comment]
Test report by @akesandgren
**FAILED**
Build succeeded for 0 out of 1 (7 easyconfigs in this PR)
b-an03.hpc2n.umu.se - Linux ubuntu 16.04, Intel(R) Xeon(R) CPU E5-2690 v4 @ 2.60GHz, Python 2.7.12
See https://gist.github.com/73f3747835db155674cb7bfaa996b56b for a full test report.

**Comment by akesandgren** [comment]
I think I found the problem.
All augustus easyconfigs must have both binaries/ and binaries/old as source_urls.
The current, and only, version in binaries/ is 3.3.3

**Comment by akesandgren** [comment]
Test report by @akesandgren
**SUCCESS**
Build succeeded for 7 out of 7 (7 easyconfigs in this PR)
b-an03.hpc2n.umu.se - Linux ubuntu 16.04, Intel(R) Xeon(R) CPU E5-2690 v4 @ 2.60GHz, Python 2.7.12
See https://gist.github.com/9a5d6d1b1411684922a6f8aeadbc8984 for a full test report.

**Comment by migueldiascosta** [comment]
closing and reopening to trigger travis

**Comment by boegel** [comment]
I'll close this PR and open a new one from the same branch (after rebasing it on current `develop`), it makes no sense that Travis is stuck on this...

**Comment by boegel** [comment]
new PR at #9579...

**Pull request closed without merging**
