### PR TITLE
committing Armadillo 8.300.1 for foss/2017b

### PR DESCRIPTION
**Pull request by murfreesboro**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by murfreesboro** [comment]
Test report by @murfreesboro
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
dev806.vampire - Linux centos linux 7.4.1708, Intel(R) Xeon(R) CPU           E5620  @ 2.40GHz, Python 2.7.5
See https://gist.github.com/432c3044968b475976dd8696935afa0b for a full test report.

**Comment by verdurin** [comment]
Test report by @verdurin
**SUCCESS**
Build succeeded for 4 out of 4 (1 easyconfigs in this PR)
easybuild.novalocal - Linux centos linux 7.5.1804, Intel Xeon E312xx (Sandy Bridge), Python 2.7.5
See https://gist.github.com/1f699a1329bfa1c38ce97173c08314be for a full test report.

**Comment by verdurin** [comment]
@murfreesboro welcome, and thanks for your contribution.

**Comment by verdurin** [comment]
Going in, thanks @murfreesboro!

**Pull request merged**
