### PR TITLE
{math}[foss/2022.05] Hypre v2.24.0, METIS v5.1.0, MPFR v4.1.0, ... w/ Python 3.10.4

### PR DESCRIPTION
**Pull request by jfgrimm**
requires:

- [x] #15561
- [x] #15563
- [x] #15572 

(created using `eb --new-pr`)

### CODE REVIEW

**Comment by jfgrimm** [comment]
Test report by @jfgrimm
**FAILED**
Build succeeded for 3 out of 7 (7 easyconfigs in total)
himem06.pri.viking.alces.network - Linux CentOS Linux 7.9.2009, x86_64, Intel(R) Xeon(R) Platinum 8160 CPU @ 2.10GHz (skylake_avx512), Python 3.6.8
See https://gist.github.com/9174f70e03bdc22da65b572881ef6b23 for a full test report.

**Comment by jfgrimm** [comment]
Test report by @jfgrimm
**FAILED**
Build succeeded for 5 out of 7 (7 easyconfigs in total)
himem06.pri.viking.alces.network - Linux CentOS Linux 7.9.2009, x86_64, Intel(R) Xeon(R) Platinum 8160 CPU @ 2.10GHz (skylake_avx512), Python 3.6.8
See https://gist.github.com/2a41752f1d8f33a24ac71ca2bfa77393 for a full test report.

**Comment by boegel** [comment]
@jfgrimm With the different failures, and the fact that we should maybe fatten up the PETSc installation a bit (like in #15519), it's probably better to break this apart into smaller PRs?

**Comment by satishskamath** [comment]
SuiteSparse build fails and because SuiteSparse fails, PetSc also fails.
Reason:
There is a step to copy this folder `GraphBLAS` in the SuiteSparse repo during the installation step:
```
SuiteSparse-5.12.0/GraphBLAS/CUDA/test
```
. This folder looks like this:

```
```

**Comment by boegel** [comment]
It sounds like we'll need to make sure that symlinks are not being resolved when files are being copied during the installation step. Copying a symlink itself should never cause trouble, the issue here is that the symlink is being *resolved*.

The `SuiteSparse` easyblock is still using `shutil.copytree` and `shutil.copy2`, rather than our own `copy_dir` and `copy_file` (available in `easybuild.tools.filetools`). You can pass a `symlinks=True` to `copy_dir` to avoid trouble with broken symlinks, so that should be used in the `SuiteSparse` easyblock...

**Comment by Wahid612** [comment]
@boegel That's indeed a better way. I'll test it and let you know. Should I open an issue for that modification?

**Comment by satishskamath** [comment]
https://github.com/easybuilders/easybuild-easyblocks/pull/2790 Made a PR for the suitesparse easyblock.

**Comment by satishskamath** [comment]
https://github.com/easybuilders/easybuild-easyconfigs/pull/16275 There is already SuiteSparse 5.13.0 for foss 2022a. Should the dependency list here be upgraded for PETSc?

**Comment by satishskamath** [comment]
https://github.com/easybuilders/easybuild-easyconfigs/pull/16354

**Pull request closed without merging**
