### PR TITLE
{bio}[gompi/2021a] DaliLite v4.1

### PR DESCRIPTION
**Pull request by lexming**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by verdurin** [comment]
Test report by @verdurin
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
easybuild-c7.novalocal - Linux CentOS Linux 7.9.2009, x86_64, Intel Xeon Processor (Skylake, IBRS), Python 3.6.8
See https://gist.github.com/verdurin/07d48297a91c93ad7be455c1c9910ea9 for a full test report.

**Comment by verdurin** [comment]
@boegelbot please test @ jsc-zen2

**Review by verdurin — DISMISSED** [review]
Looks fine.

**Comment by verdurin** [comment]
@lexming - any idea why those MPI errors are reported on `jsczen2`?

**Comment by branfosj** [comment]
> @lexming - any idea why those MPI errors are reported on `jsczen2`?

The MPI messages are only warnings.The error is
```
f951: Fatal Error: Cannot rename module file wolf.mod0 to wolf.mod: No such file or directory
compilation terminated.
```

**Comment by verdurin** [comment]
@lexming any thoughts on the error above?

**Comment by lexming** [comment]
@boegelbot: please test @ generoso

**Comment by lexming** [comment]
@verdurin the failed test is fixed :slightly_smiling_face:

**Review by verdurin — APPROVED** [review]
Looks fine.

**Comment by verdurin** [comment]
Going in, thanks @lexming!

**Pull request merged**
