### PR TITLE
{vis}[foss/2019b] matplotlib v3.1.1, Tkinter v3.7.4, Tk v8.6.9 w/ Python 3.7.4

### PR DESCRIPTION
**Pull request by schiotz**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by schiotz** [comment]
It looks like ``eb --new-pr`` incorrectly identified this as belonging to the ``GCCcore/8.3.0`` toolchain, but matplotlib belongs to ``foss/2019b``.  I'll edit the title manually.

**Comment by boegel** [comment]
> It looks like `eb --new-pr` incorrectly identified this as belonging to the `GCCcore/8.3.0` toolchain, but matplotlib belongs to `foss/2019b`. I'll edit the title manually.

`eb --new-pr` does a majority vote, it picked `GCCcore` over `foss` because it was 2 easyconfigs vs 1.

Editing the PR title makes sense though, thanks for that. :)

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 3 out of 3 (3 easyconfigs in this PR)
generoso-1 - Linux centos linux 7.6.1810, Intel(R) Xeon(R) CPU E5-2660 v4 @ 2.00GHz, Python 3.6.8
See https://gist.github.com/f7c39b7282a5cce19506b63b9093022b for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 3 out of 3 (3 easyconfigs in this PR)
node2405.golett.os - Linux centos linux 7.7.1908, Intel(R) Xeon(R) CPU E5-2680 v3 @ 2.50GHz, Python 2.7.5
See https://gist.github.com/ee07ab27c77dae9a2134b8009d1612d2 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 3 out of 3 (3 easyconfigs in this PR)
node3142.skitty.os - Linux centos linux 7.7.1908, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz, Python 3.6.8
See https://gist.github.com/47ce1e0e4a352a50ab92ff9841881bf3 for a full test report.

**Comment by boegel** [comment]
Going in, thanks @schiotz!

**Pull request merged**
