### PR TITLE
Add missing pkgconf dep to libxslt

### LINKED ISSUE #17202: libxslt-1.1.34-GCCcore-11.3.0.eb fails on RHEL9 due to missing pkgconf dependency
This happened on a RHEL9 (9.1 Plow) system for me and in a Ubuntu-focal Singularity container for @sassy-crick 

`libxslt-1.1.34-GCCcore-11.3.0.eb` fails with this output in the log:

```bash
checking for x86_64-pc-linux-gnu-xml2-config... no
checking for xml2-config... /scratch/palrosen/.local/easybuild/software/libxml2/2.9.13-GCCcore-11.3.0/bin/xml2-config
checking for LIBXML... no
./configure: line 14833: --static: command not found
configure: error: Could not find libxml2 anywhere, check ftp://xmlsoft.org/.
 (at easybuild/software/EasyBuild/4.6.0/lib/python3.9/site-packages/easybuild/tools/run.py:618 in parse_cmd_output)
```
I couldn't find any other issues about this problem here and not on the EasyBuild Slack either. The `1.1.34` version has been used since GCC 8.3.0 and is still used in the latest ebconfig.
After updating to `libxslt-1.1.37-GCCcore-11.3.0.eb` configure works again and the build finishes:

```bash
checking for x86_64-pc-linux-gnu-xml2-config... no
checking for xml2-config... /lsc/easybuild/software/libxml2/2.9.13-GCCcore-11.3.0/bin/xml2-config
checking for LIBXML... no
checking for libxml libraries >= 2.6.27... 2.9.13 found
checking whether shared libraries will be built (required for plugins)... yes
checking libxml2 module support... yes
checking that generated files are newer than configure... done
configure: creating ./config.status
```

### PR DESCRIPTION
**Pull request by Micket**
(created using `eb --new-pr`)
Fixes #17202

### CODE REVIEW

**Comment by Micket** [comment]
Test report by @Micket
**SUCCESS**
Build succeeded for 10 out of 10 (6 easyconfigs in total)
alvis-c1 - Linux Rocky Linux 8.6, x86_64, Intel Xeon Processor (Skylake), Python 3.6.8
See https://gist.github.com/dd8aef654db38ddc2d1b08c46491253b for a full test report.

**Comment by branfosj** [comment]
Test report by @branfosj
**SUCCESS**
Build succeeded for 9 out of 9 (7 easyconfigs in total)
bear-pg0211u03a.bear.cluster - Linux RHEL 8.6, x86_64, Intel(R) Xeon(R) Gold 6248 CPU @ 2.50GHz (cascadelake), Python 3.6.8
See https://gist.github.com/a77963be1305a0fc81286c5f71f4d5b4 for a full test report.

**Review by branfosj — APPROVED** [review]

**Comment by branfosj** [comment]
@boegelbot please test @ generoso

**Comment by branfosj** [comment]
@boegelbot please test @ jsc-zen2

**Comment by branfosj** [comment]
Going in, thanks @Micket!

**Pull request merged**
