### PR TITLE
{bio}[GCC/11.2.0] Pysam v0.18.0 w/ Python 3.9.6

### PR DESCRIPTION
**Pull request by Ghepardo**
Update for Pysam 0.18.0.

### CODE REVIEW

**Comment by migueldiascosta** [comment]
@boegelbot please test @ generoso

**Comment by migueldiascosta** [comment]
@boegelbot please test @ jsc-zen2

**Comment by migueldiascosta** [comment]
Test report by @migueldiascosta
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
c2dhpc - Linux CentOS Linux 7.6.1810, x86_64, AMD EPYC 7601 32-Core Processor (zen), Python 2.7.5
See https://gist.github.com/f5a24d201f0c8de039a7c415d9cbe2e2 for a full test report.

**Review by migueldiascosta — APPROVED** [review]
lgtm

**Comment by migueldiascosta** [comment]
Going in, thanks @Ghepardo!

**Comment by migueldiascosta** [comment]
@Ghepardo you may want to have a look at https://docs.easybuild.io/en/latest/Integration_with_GitHub.html#submitting-new-and-updating-pull-requests-new-pr-update-pr, if you haven't already

**Comment by Ghepardo** [comment]
Thanks @migueldiascosta , I'll look at that for my next submission.

**Pull request merged**
