### PR TITLE
{numlib}[system/system] CUDA v11.8.0, cuDNN v8.6.0.163

### PR DESCRIPTION
**Pull request by robogast**
(created using `eb --new-pr`)

Todo:
- [x] add checksums for CUDA ppc64le & sbsa
- [x] add checksums for cuDNN ppc64le & sbsa

### CODE REVIEW

**Comment by robogast** [comment]
Test report by @robogast
**SUCCESS**
Build succeeded for 5 out of 5 (5 easyconfigs in total)
gcn2.local.snellius.surf.nl - Linux RHEL 8.4, x86_64, Intel(R) Xeon(R) Platinum 8360Y CPU @ 2.40GHz, 4 x NVIDIA NVIDIA A100-SXM4-40GB, 515.43.04, Python 3.6.8
See https://gist.github.com/d49eb09d2d59837abaabf74b20391374 for a full test report.

**Comment by jfgrimm** [comment]
hmm, looking at https://docs.nvidia.com/cuda/cuda-installation-guide-linux/index.html#system-requirements it doesn't look like this CUDA toolkit version has been tested against GCC 12.x compilers yet

**Comment by robogast** [comment]
Hi @jfgrimm, you're absolutely right -- I also specifically compiled NCCL with `-allow-unsupported-compiler` to make the build happen.
I did compile/run all non-libGLU tests from https://github.com/nvidia/cuda-samples with GCCCore 12.2.0 (because libGLU is way too much work to update for now) --  with two failures, see below.
```
Error: Condition (allocation_cb == 1) failed at cuHook.cpp:116
cuHook sample failed (Didn't receive the allocation callback)

checkCudaErrors() Driver API error = 0222 "the provided PTX was compiled with an unsupported toolchain." from file <memMapIpc.cpp>, line 292.
> findModulePath found file at <./memMapIpc_kernel64.ptx>
```

But maybe I should just stick to GCCCore 11.3 :)

**Comment by robogast** [comment]
I've removed NCCL, UCX-CUDA, and GDCopy, as that leaved CUDA 11.8 and cuDNN 8.6 which are toolchain independent

**Comment by robogast** [comment]
Test report by @robogast
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in total)
gcn2.local.snellius.surf.nl - Linux RHEL 8.4, x86_64, Intel(R) Xeon(R) Platinum 8360Y CPU @ 2.40GHz, 4 x NVIDIA NVIDIA A100-SXM4-40GB, 515.43.04, Python 3.6.8
See https://gist.github.com/81bcefa2e7dd5c627e5cc27d83bc3117 for a full test report.

**Comment by jfgrimm** [comment]
@boegelbot please test @ jsc-zen2

**Review by jfgrimm — APPROVED** [review]
LGTM

I think it's sensible to hold off on the GCC 12 based CUDA stuff until there is some degree of support, to avoid future headaches

**Comment by jfgrimm** [comment]
@boegelbot please test @ generoso

**Comment by jfgrimm** [comment]
Test report by @jfgrimm
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in total)
node069.pri.viking.alces.network - Linux CentOS Linux 7.9.2009, x86_64, Intel(R) Xeon(R) Gold 6138 CPU @ 2.00GHz (skylake_avx512), Python 3.6.8
See https://gist.github.com/c7d28154e020864a901c89ba74e0833c for a full test report.

**Comment by jfgrimm** [comment]
Going in, thanks @robogast!

**Pull request merged**
