### PR TITLE
{chem}[gompi/2023a] OpenBabel v3.1.1

### PR DESCRIPTION
**Pull request by sassy-crick**
(created using `eb --new-pr`)

Requires:
- [x] PR #20211
- [x] PR #20210
- [x] PR #20209

### CODE REVIEW

**Comment by akesandgren** [comment]
@boegelbot Please test @ jsc-zen2

**Comment by sassy-crick** [comment]
I looked at the unit tests and why the failed so I decided to try out `RapidJSON-1.1.0-20230928-GCCcore-12.3.0.eb` as that has been used in other EC files. However, as seen [here](https://gist.github.com/sassy-crick/e20c0c3b9c2bc9aa77996a3cf5056260) one test job fails. 
I would suggest to stick with the version which is working, and I would appreciated if others could test the `RapidJSON-1.1.0-20230928-GCCcore-12.3.0.eb` version as well to see if that is an issue with my laptop, or a real problem.

**Comment by akesandgren** [comment]
@boegelbot Please test @ jsc-zen3

**Comment by akesandgren** [comment]
Those "errors" are likely caused by the developers being sloppy and expecting numerically exact results for things that varies depending on FMA and/or compiler optimizations. It does look like they are doing "diff" instead of a numerical comparison.

**Comment by akesandgren** [comment]
Test report by @akesandgren
**SUCCESS**
Build succeeded for 6 out of 6 (1 easyconfigs in total)
b-cn1603.hpc2n.umu.se - Linux Ubuntu 22.04, x86_64, AMD EPYC 7313 16-Core Processor, 1 x NVIDIA NVIDIA A100 80GB PCIe, 545.29.06, Python 3.10.12
See https://gist.github.com/akesandgren/00f5c348bf39860e7cd30f1b7ad5fe74 for a full test report.

**Comment by akesandgren** [comment]
As for the errors when using RapidJSON-1.1.0-20230928-GCCcore-12.3.0.eb I see exactly the same on an AMD Zen3 and on a Broadwell.

**Comment by akesandgren** [comment]
[OpenBabel-3.1.1_disable_bad_tests.patch.gz](https://github.com/easybuilders/easybuild-easyconfigs/files/14769603/OpenBabel-3.1.1_disable_bad_tests.patch.gz)

@sassy-crick  Here is a patch that fixes the problem with the bad tests.

**Comment by sassy-crick** [comment]
@boegelbot Please test @ jsc-zen3

**Comment by akesandgren** [comment]
Test report by @akesandgren
**SUCCESS**
Build succeeded for 6 out of 6 (1 easyconfigs in total)
b-cn1603.hpc2n.umu.se - Linux Ubuntu 22.04, x86_64, AMD EPYC 7313 16-Core Processor, 1 x NVIDIA NVIDIA A100 80GB PCIe, 545.29.06, Python 3.10.12
See https://gist.github.com/akesandgren/41553705da8feb1fe76270d61fe0d6f0 for a full test report.

**Review by akesandgren — APPROVED** [review]
LGTM

**Comment by akesandgren** [comment]
Going in, thanks @sassy-crick!

**Pull request merged**
