### PR TITLE
{lib}[foss/2021a] TensorFlow v2.6.0 w/ Python 3.9.5

### PR DESCRIPTION
**Pull request by Flamefire**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by Flamefire** [comment]
Test report by @Flamefire
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
taurusi8010 - Linux centos linux 7.9.2009, x86_64, AMD EPYC 7352 24-Core Processor (zen2), Python 2.7.5
See https://gist.github.com/499a990ea2850a0f62b2804d8d06a59f for a full test report.

**Comment by Flamefire** [comment]
Test report by @Flamefire
**FAILED**
Build succeeded for 23 out of 26 (1 easyconfigs in total)
taurusml10 - Linux RHEL 7.6, POWER, 8335-GTX (power9le), Python 2.7.5
See https://gist.github.com/18d49ae180967ffe7c15bdb560af5eed for a full test report.

**Comment by boegel** [comment]
@boegelbot please test @ generoso
CORE_CNT=16

**Review by boegel — APPROVED** [review]
lgtm

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
node3559.doduo.os - Linux RHEL 8.2, x86_64, AMD EPYC 7552 48-Core Processor (zen2), Python 3.6.8
See https://gist.github.com/367eda7209f669c594ac4404077775b0 for a full test report.

**Comment by Flamefire** [comment]
Test report by @Flamefire
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
taurusa4 - Linux centos linux 7.7.1908, x86_64, Intel(R) Xeon(R) CPU E5-2603 v4 @ 1.70GHz (broadwell), Python 2.7.5
See https://gist.github.com/6e8907e8c87cc4caad260829d0cdcfb9 for a full test report.

**Comment by boegel** [comment]
Going in, thanks @Flamefire!

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
node3159.skitty.os - Linux centos linux 7.9.2009, x86_64, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz, Python 3.6.8
See https://gist.github.com/cd890faa1374818e4e664b8634c67245 for a full test report.

**Comment by branfosj** [comment]
Test report by @branfosj
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
bear-pg0306u15a.bear.cluster - Linux RHEL 8.4, POWER, 8335-GTX (power9le), Python 3.6.8
See https://gist.github.com/3d7295a7bb5a9c2164737dc5fb09e188 for a full test report.

**Comment by Flamefire** [comment]
@boegel Just for reference: Is there already an issue for the SciPy-Bundle failure on POWER?
```
linalg/tests/test_regression.py Fatal Python error: Aborted

Current thread 0x00002000000489e0 (most recent call first):
  File "/tmp/easybuild-tmp/eb-71Hmx5/tmph1LACD/lib/python3.9/site-packages/numpy/linalg/linalg.py", line 1323 in eig
  File "<__array_function__ internals>", line 5 in eig
```
I guess that was the FlexiBLAS issue? Any (merged) solution yet?

**Comment by branfosj** [comment]
@Flamefire #12968 

My successful build was using #13836 and the linked framework change.

**Pull request merged**
