### PR TITLE
tweak non-MPI DIRAC 19.0 easyconfig to use CMakeMake easyblock + add MPI version of DIRAC 19.0

### PR DESCRIPTION
**Pull request by hajgato**
Change the sequential version to work with native CMakeMake easyblock, and add mpi version.
Also, the unnecessary dependencies were removed (they only needed if PCMSOLVER is built)

PS: Dirac does not have `https` homepage

### CODE REVIEW

**Comment by boegel** [comment]
Test report by @boegel
**FAILED**
Build succeeded for 0 out of 2 (2 easyconfigs in this PR)
node3502.doduo.os - Linux RHEL 8.2, x86_64, AMD EPYC 7302P 16-Core Processor (zen2), Python 3.6.8
See https://gist.github.com/85421e7152165aa9ae7ae6503b31ec82 for a full test report.

**Comment by hajgato** [comment]
@boegel on `doduo` do not forget `--optarch="Intel:march=core-avx2`

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in this PR)
node3404.kirlia.os - Linux centos linux 7.8.2003, x86_64, Intel(R) Xeon(R) Gold 6240 CPU @ 2.60GHz (cascadelake), Python 2.7.5
See https://gist.github.com/3612576d35f9559b1dfdce3cb2637032 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in this PR)
node2604.swalot.os - Linux centos linux 7.8.2003, x86_64, Intel(R) Xeon(R) CPU E5-2660 v3 @ 2.60GHz (haswell), Python 2.7.5
See https://gist.github.com/a06c70c77a257de963e8678e07db3c11 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in this PR)
node3134.skitty.os - Linux centos linux 7.8.2003, x86_64, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz, Python 3.6.8
See https://gist.github.com/850cca30d78bb710b9e7ec02694c0591 for a full test report.

**Comment by boegel** [comment]
> @boegel on `doduo` do not forget `--optarch="Intel:march=core-avx2`

Thanks, re-running the test with that in place...

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in this PR)
node3502.doduo.os - Linux RHEL 8.2, x86_64, AMD EPYC 7302P 16-Core Processor (zen2), Python 3.6.8
See https://gist.github.com/207dce442f19ef95a9045b34423644df for a full test report.

**Review by boegel — APPROVED** [review]
lgtm

**Comment by boegel** [comment]
Going in, thanks @hajgato!

**Comment by Flamefire** [comment]
Test report by @Flamefire
**FAILED**
Build succeeded for 1 out of 2 (2 easyconfigs in total)
taurusi6605.taurus.hrsk.tu-dresden.de - Linux RHEL 7.9, x86_64, Intel(R) Xeon(R) CPU E5-2680 v3 @ 2.50GHz (haswell), Python 2.7.5
See https://gist.github.com/30e61c8cdce6bdefe37a6b2a8956a3d9 for a full test report.

**Comment by Flamefire** [comment]
Test report by @Flamefire
**FAILED**
Build succeeded for 0 out of 2 (2 easyconfigs in total)
taurusi8001 - Linux centos linux 7.9.2009, x86_64, AMD EPYC 7352 24-Core Processor (zen2), Python 2.7.5
See https://gist.github.com/4e56a4ab2b335c44648132d45fb22137 for a full test report.

**Comment by Flamefire** [comment]
Test report by @Flamefire
**FAILED**
Build succeeded for 2 out of 9 (2 easyconfigs in total)
taurusml10 - Linux RHEL 7.6, POWER, 8335-GTX (power9le), Python 2.7.5
See https://gist.github.com/8f15b816a8fa8c435b87c8735b99edb9 for a full test report.

**Comment by hajgato** [comment]
@Flamefire on zen2, you should use `--optarch="Intel:march=core-avx2`

**Comment by Flamefire** [comment]
@hajgato Thanks. Any way we can fix that generically?

**Comment by hajgato** [comment]
Intel compilers fall back on mmx/sse with `xHost` with AMD (since around intel 2014-15, as far as I remember well). I think it is a desired behavior of intel compilers, so you have to set the opt arch for AMD cpus by hand, so we cannot do too much.
As far as I now EB (right now) cannot detect the CPU architecture, so we solve it setting `EASYBUILD_OPTARCH="Intel:march=core-avx2"` on AMD Rome/zen2 nodes for the install user. 
something like this in the bashrc:
```
# DODUO/DOTRIO
# make sure to use --optarch="Intel:march=core-avx2" on doduo/dotrio (AMD Rome, zen2)
# beacuse AMD CPUs are not correctly recognised by -xHost option
if [[ $(hostname) =~ 'doduo' || $(hostname) =~ 'dotrio' ]]; then
    export EASYBUILD_OPTARCH="Intel:march=core-avx2"
fi
```
 
On AMD cpus, hard coded `-xHost` cause speed decreases, we try to find those cases and make patches.

**Comment by Flamefire** [comment]
Hm, for test reports we have info like `AMD EPYC` and especially with archspec we have the zen2 info. Maybe we could adapt the default optarch for intel compilers if we are on an AMD?

**Comment by hajgato** [comment]
No idea about that.

**Comment by Flamefire** [comment]
Test report by @Flamefire
**FAILED**
Build succeeded for 1 out of 2 (2 easyconfigs in total)
taurusi6605.taurus.hrsk.tu-dresden.de - Linux RHEL 7.9, x86_64, Intel(R) Xeon(R) CPU E5-2680 v3 @ 2.50GHz (haswell), Python 2.7.5
See https://gist.github.com/b6753d291a8fb8dfc0a3b05b5e855b39 for a full test report.

**Comment by Flamefire** [comment]
Test report by @Flamefire
**FAILED**
Build succeeded for 1 out of 2 (2 easyconfigs in total)
taurusi8001 - Linux centos linux 7.9.2009, x86_64, AMD EPYC 7352 24-Core Processor (zen2), Python 2.7.5
See https://gist.github.com/4c9b69e6fcce50fef7b612c8e659b0ea for a full test report.

**Comment by Flamefire** [comment]
Test report by @Flamefire
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in total)
taurusi6605.taurus.hrsk.tu-dresden.de - Linux RHEL 7.9, x86_64, Intel(R) Xeon(R) CPU E5-2680 v3 @ 2.50GHz (haswell), Python 2.7.5
See https://gist.github.com/8b859660abbf915acd8a55984aba0fe3 for a full test report.

**Comment by Flamefire** [comment]
Test report by @Flamefire
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in total)
taurusi8001 - Linux centos linux 7.9.2009, x86_64, AMD EPYC 7352 24-Core Processor (zen2), Python 2.7.5
See https://gist.github.com/ed094ab5e72af991ba8b8ba47fa89cad for a full test report.

**Comment by Flamefire** [comment]
Ok, so in essence the MPI test fail if `--default-opt-level=opt` is given but passes for `--default-opt-level=defaultopt` -.-
This looks very much like a bug in the software or (less likely) a bug in the compiler.

**Comment by hajgato** [comment]
Intel FORTRAN compilers (post ~2016 versions) use very aggressive optimization techniques with `-O3`. over-optimized code gives  often incorrect results for not cleanly written FORTRAN codes. (do not forget that those codes manly written by scientists not programmers....)

**Comment by Flamefire** [comment]
Sure, that would hence be a bug in the software we could likely patch if found
However in this case the MPI version only fails with everything else being the same.

**Pull request merged**
