### PR TITLE
{bio}[foss/2022a] biobakery-workflows v3.1

### PR DESCRIPTION
**Pull request by deniskristak**
adding easyconfigs: anadama2-0.10.0-foss-2022a.eb, biobakery-workflows-3.1-foss-2022a.eb, kneaddata-0.12.0-foss-2022a.eb, LevelDB-1.22-GCCcore-11.3.0.eb

based on https://github.com/vscentrum/vsc-software-stack/issues/138

### CODE REVIEW

**Comment by verdurin** [comment]
Test report by @verdurin
**SUCCESS**
Build succeeded for 13 out of 13 (4 easyconfigs in total)
easybuild-c7.novalocal - Linux CentOS Linux 7.9.2009, x86_64, Intel Xeon Processor (Skylake, IBRS), Python 3.6.8
See https://gist.github.com/verdurin/749d9d6d65c7064760fb0311f8e7ead4 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 4 out of 4 (4 easyconfigs in total)
node3157.skitty.os - Linux RHEL 8.6, x86_64, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz (skylake_avx512), Python 3.6.8
See https://gist.github.com/boegel/0509f751b6a20f291bdc3f6e1a80ca54 for a full test report.

**Review by boegel — APPROVED** [review]

**Comment by boegel** [comment]
@boegelbot please test @ generoso

**Comment by boegel** [comment]
@boegelbot please test @ jsc-zen2

**Comment by boegel** [comment]
Going in, thanks @deniskristak!

**Pull request merged**
