### PR TITLE
{vis}[foss/2018a] opencv_contrib v3.4.1: rename and update to OpenCV v3.4.1 with contrib versionsuffix

### PR DESCRIPTION
**Pull request by lexming**
(created using `eb --new-pr`)

`opencv_contrib-3.4.1-foss-2018a-Python-3.6.4.eb` provides **both** OpenCV and the extra modules from `opencv_contrib`. Therefore, it should use `OpenCV` as package name to disallow loading this easyconfig at the same time than any other `OpenCV` in this toolchain.

This PR renames it to `OpenCV-3.4.1-foss-2018a-Python-3.6.4-contrib.eb`, which provides an equivalent build to the old one:
* uses the same sources
* uses the same dependencies
* changes name to `OpenCV` plus `-contrib` in `versionsuffix`
* uses the `opencv` easyblock instead of `CMakeMake`

### CODE REVIEW

**Comment by lexming** [comment]
Test report by @lexming
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
node381.hydra.os - Linux centos linux 7.9.2009, x86_64, Intel(R) Xeon(R) Gold 6148 CPU @ 2.40GHz, Python 2.7.5
See https://gist.github.com/e03381870c4b0f3eca5d3f0ae6367c17 for a full test report.

**Review by boegel — APPROVED** [review]
lgtm

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
node2637.swalot.os - Linux centos linux 7.9.2009, x86_64, Intel(R) Xeon(R) CPU E5-2660 v3 @ 2.60GHz (haswell), Python 3.6.8
See https://gist.github.com/c35104382683e2c889dcb45cbeb73518 for a full test report.

**Comment by lexming** [comment]
Test report by @lexming
Using easyblocks from PR(s) https://github.com/easybuilders/easybuild-easyblocks/pull/2346
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
node381.hydra.os - Linux centos linux 7.9.2009, x86_64, Intel(R) Xeon(R) Gold 6148 CPU @ 2.40GHz, Python 2.7.5
See https://gist.github.com/b52059e06efd6bb157891c657a4078da for a full test report.

**Comment by lexming** [comment]
Test report by @lexming
Using easyblocks from PR(s) https://github.com/easybuilders/easybuild-easyblocks/pull/2346
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
node376.hydra.os - Linux centos linux 7.9.2009, x86_64, Intel(R) Xeon(R) Gold 6148 CPU @ 2.40GHz, Python 2.7.5
See https://gist.github.com/a72d90bda320dcc7e9cc2b3f3b22c82d for a full test report.

**Comment by verdurin** [comment]
Going in, thanks @lexming!

**Pull request merged**
