### PR TITLE
{geo}[foss/2017b] SpiceyPy v2.1.0

### PR DESCRIPTION
**Pull request by boegel**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by verdurin** [comment]
Test report by @verdurin
**FAILED**
Build succeeded for 0 out of 2 (1 easyconfigs in this PR)
dell.lan - Linux fedora 27, Intel(R) Core(TM) i7-4600U CPU @ 2.10GHz, Python 2.7.14
See https://gist.github.com/709dd6d46c6a68a788beb6c2a7090707 for a full test report.

**Comment by boegel** [comment]
@verdurin Failed to install `Python` due to:

```
== 2017-12-12 19:50:52,635 run.py:478 DEBUG cmd "rpm -q libopenssl-devel" exited with exitcode 1 and output:
rpm: /home/huffmaa/.local/easybuild/software/XZ/5.2.3-GCCcore-6.4.0/lib/liblzma.so.5: version `XZ_5.2' not found (required by /lib64/librpmio.so.8)
```

Is this another issue very similar to #4036?

Can you retry with `--ignore-osdeps` to dance around it, and open a separate issue for it?

**Comment by verdurin** [comment]
Test report by @verdurin
**SUCCESS**
Build succeeded for 2 out of 2 (1 easyconfigs in this PR)
dell.lan - Linux fedora 27, Intel(R) Core(TM) i7-4600U CPU @ 2.10GHz, Python 2.7.14
See https://gist.github.com/a9bdefbd0e3429f903ceb7f77e40c896 for a full test report.

**Comment by verdurin** [comment]
That successful build was, as @boegel suggested, with `--ignore-osdeps`.

**Comment by verdurin** [comment]
Going in, thanks @boegel!

**Pull request merged**
