### PR TITLE
{data,math}[iccifort/2020.4.304,intel/2020b] GDAL v3.2.1, GEOS v3.9.1 w/ Python 3.8.6

### PR DESCRIPTION
**Pull request by zao**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by zao** [comment]
Test report by @zao
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in total)
eb-rocky8 - Linux UNKNOWN UNKNOWN, x86_64, Intel(R) Core(TM) i7-8700K CPU @ 3.70GHz, Python 3.9.2
See https://gist.github.com/20e07e471fe89754301164b4787699dd for a full test report.

**Comment by zao** [comment]
Test report by @zao
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in total)
eb-u2004 - Linux Ubuntu 20.04, x86_64, Intel(R) Core(TM) i7-8700K CPU @ 3.70GHz, Python 3.8.10
See https://gist.github.com/e169b9cfd2393a927f97254997d37280 for a full test report.

**Comment by verdurin** [comment]
@boegelbot please test @ generoso

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in total)
node3502.doduo.os - Linux RHEL 8.2, x86_64, AMD EPYC 7552 48-Core Processor (zen2), Python 3.6.8
See https://gist.github.com/649953732338ffbec0c0013bb971a138 for a full test report.

**Review by boegel — APPROVED** [review]
lgtm

**Comment by boegel** [comment]
Going in, thanks @zao!

**Pull request merged**
