### PR TITLE
{chem}[foss/2022a] Amber v22.4 with AmberTools v22.5 + CUDA 11.7.0

### PR DESCRIPTION
**Pull request by DirectorSloan**
- Successfully build at our site
- replaces https://github.com/easybuilders/easybuild-easyconfigs/pull/17824

### CODE REVIEW

**Comment by casparvl** [comment]
@boegelbot please test @ generoso

**Comment by casparvl** [comment]
Test report by @casparvl
**FAILED**
Build succeeded for 1 out of 2 (1 easyconfigs in total)
tcn497.local.snellius.surf.nl - Linux RHEL 8.6, x86_64, AMD EPYC 7H12 64-Core Processor, Python 3.6.8
See https://gist.github.com/casparvl/d1e1871b1e29a79571a360f0c54e2009 for a full test report.

**Review by boegel — APPROVED** [review]
lgtm

**Comment by boegel** [comment]
Going in, thanks @DirectorSloan!

**Pull request merged**
