### PR TITLE
{numlib}[iimpi/2022a] FFTW v3.3.10

### PR DESCRIPTION
**Pull request by schiotz**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by schiotz** [comment]
This is a simple update from the 2021b to 2022a toolchain.  However, I am not 100% sure this is useful.  FFTW for the intel toolchain could be useful because MKL only provides an incomplete FFTW API.  Somebody made a libxcvdw package for intel/2021b using the iimpi/2021b version of FFTW, and I therefore updated both libvdwxc and FFTW to 2022a assuming that the issues of mixing FFTW and MKL had been solved.  However, libvdwxc can be build with both intel/2021b and intel/2022a but it cannot be used with either, as it coredumps due to symbol conflicts/mismatches in the libraries.

Possibly, FFTW might be useful for other packages, so I uploaded it, feel free to include it or reject it.  I will not upload the broken libvdwxc.

**Comment by smoors** [comment]
doesn't hurt to add as long as it works properly.
might be useful if nothing else for performance comparison with MKL.

**Comment by smoors** [comment]
@boegelbot please test @ jsc-zen2

**Comment by smoors** [comment]
@boegelbot: please test @ generoso

**Review by smoors — APPROVED** [review]
lgtm

**Comment by smoors** [comment]
Going in, thanks @schiotz!

**Pull request merged**
