### PR TITLE
fix download for python-parasail 1.3.4 by adding missing source URL

### PR DESCRIPTION
**Pull request by boegel**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by boegel** [comment]
@boegelbot please test @ generoso
EB_ARGS="--force-download"

**Comment by Micket** [comment]
I thought this was somehow the default in PythonPackage already?

**Comment by boegel** [comment]
> I thought this was somehow the default in PythonPackage already?

It is, but not in this case because we're using `name = 'python-parasail'`, and the source URL uses `parasail` (not `python-parasail`)

**Review by Micket — APPROVED** [review]
lgtm

**Pull request merged**
