### PR TITLE
{tools}[foss/2021b] Ray-project v1.9.2 w/ Python 3.9.6

### PR DESCRIPTION
**Pull request by lexming**
(created using `eb --new-pr`)

Depends on:
- [x] #14837 
- [x] #14784 
- [x] #14783 
- [x] #14781 
- [x] #14780 
- [x] #14779 
- [x] #14778 
- [x] #14774 
- [x] #14782

### CODE REVIEW

**Comment by lexming** [comment]
@boegelbot: please test @ generoso

**Comment by lexming** [comment]
Test report by @lexming
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
node300.hydra.os - Linux CentOS Linux 7.9.2009, x86_64, Intel(R) Xeon(R) Gold 6148 CPU @ 2.40GHz, Python 2.7.5
See https://gist.github.com/53af6fca0c561685982b3aab6a6f714b for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**FAILED**
Build succeeded for 0 out of 1 (1 easyconfigs in total)
node3120.skitty.os - Linux CentOS Linux 7.9.2009, x86_64, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz, Python 3.6.8
See https://gist.github.com/3f192e57e5ac7d52970db6881d9c42a1 for a full test report.

**Comment by lexming** [comment]
@boegelbot: please test @ generoso

**Comment by lexming** [comment]
@boegelbot since version 0.12 `maturin` does some kind of auditing of libraries in the system, so it tries to open and sometimes modify library files (*eg* rpaths). I disables that feature in https://github.com/easybuilders/easybuild-easyconfigs/pull/14838/commits/b0f8c605b218b021903a089151985d75d39848b3

**Comment by lexming** [comment]
Test report by @lexming
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
node300.hydra.os - Linux CentOS Linux 7.9.2009, x86_64, Intel(R) Xeon(R) Gold 6148 CPU @ 2.40GHz, Python 2.7.5
See https://gist.github.com/2e734e89b1f334977ae3db98031b7525 for a full test report.

**Comment by verdurin** [comment]
Test report by @verdurin
**SUCCESS**
Build succeeded for 18 out of 18 (1 easyconfigs in total)
easybuild-c7.novalocal - Linux CentOS Linux 7.9.2009, x86_64, Intel Xeon Processor (Skylake, IBRS), Python 3.6.8
See https://gist.github.com/727448d02777bb748f2ce083eb64c3c9 for a full test report.

**Review by verdurin — APPROVED** [review]
Looks fine.

**Comment by verdurin** [comment]
Going in, thanks @lexming!

**Pull request merged**
