### PR TITLE
{math}[foss/2019a,gompi/2019a] lrslib v7.0a, gap v4.11.0

### PR DESCRIPTION
**Pull request by lexming**
(created using `eb --new-pr`)

gap v4.11.0 and dependencies:
* lrslib v7.0a

Depends on PR #10431 for
* 4ti2 v1.6.9
* Singular v4.1.2

Depends on PR #10429  for
* cddlib v0.94i
* Normaliz v3.7.4

### CODE REVIEW

**Comment by lexming** [comment]
Test report by @lexming
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in this PR)
node122.hydra.os - Linux centos linux 7.7.1908, Intel(R) Xeon(R) CPU E5-2680 v2 @ 2.80GHz, Python 2.7.5
See https://gist.github.com/977de20873b0d73df9b397e590ccee2b for a full test report.

**Comment by Micket** [comment]
Test report by @Micket
**SUCCESS**
Build succeeded for 6 out of 6 (2 easyconfigs in this PR)
hebbe-c1 - Linux centos linux 7.7.1908, Intel Core Processor (Haswell, no TSX), Python 2.7.5
See https://gist.github.com/5260dd7cc2c626d3a459bb7f4b7e318d for a full test report.

**Comment by Micket** [comment]
Test report by @Micket
**SUCCESS**
Build succeeded for 7 out of 7 (2 easyconfigs in this PR)
vera-c1 - Linux centos linux 7.7.1908, Intel Xeon Processor (Skylake), Python 2.7.5
See https://gist.github.com/f0938c314f365aca77ac421ddf1af40f for a full test report.

**Comment by Micket** [comment]
Going in, thanks @lexming!

**Pull request merged**
