### PR TITLE
{vis}[fosscuda/2020b] PyOpenCL v2021.1.2

### PR DESCRIPTION
**Pull request by zdemat**

### CODE REVIEW

**Comment by robert-mijakovic** [comment]
@boegelbot please test @ generoso@boegelbot please test @ generoso

**Comment by robert-mijakovic** [comment]
Test report by @robert-mijakovic
**FAILED**
Build succeeded for 60 out of 61 (1 easyconfigs in total)
mel0398 - Linux centos linux 8.4.2105, x86_64, AMD EPYC 7H12 64-Core Processor (zen2), Python 3.6.8
See https://gist.github.com/5e38fe350335fd09fd85f09e42d3adb1 for a full test report.

**Comment by zdemat** [comment]
So it builds on (Rocky) Xeon E5-2667, which is similar to what I am using, but fails on (CentOs) EPYC 7H12 with an error:
```
build_log.py:169 ERROR EasyBuild crashed with an error (at easybuild/release/2021.3/software/EasyBuild/4.5.0/lib/python3.6/site-packages/easybuild/base/exceptions.py:124 in __init__): Failed to create directory /apps/sources/p/PyOpenCL: [Errno 13] Permission denied: '/apps/sources/p/PyOpenCL' (at easybuild/release/2021.3/software/EasyBuild/4.5.0/lib/python3.6/site-packages/easybuild/tools/filetools.py:1882 in mkdir)
```

I can look for information but it may be complicated for me to reproduce that error.

**Comment by zdemat** [comment]
@robert-mijakovic 

the build fails on creating directory '/apps/sources/p' by EasyBuild itself. That path is in Easybuild configuration `--sourcepath='/apps/sources'`. Is it not just some permission/configuration issue on the test instance? The build with Xeon passes.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
node3309.joltik.os - Linux centos linux 7.9.2009, x86_64, Intel(R) Xeon(R) Gold 6242 CPU @ 2.80GHz (cascadelake), 1 x NVIDIA NVIDIA Tesla V100-SXM2-32GB, 465.19.01, Python 3.6.8
See https://gist.github.com/70016f3f556a726765e25c9117c8d60b for a full test report.

**Comment by boegel** [comment]
@zdemat I think it's pretty clear that the problem with @robert-mijakovic's test report is not due to the contents of the easyconfig file, so I'll proceed with getting this merged...

**Review by boegel — APPROVED** [review]
lgtm

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
node3122.skitty.os - Linux centos linux 7.9.2009, x86_64, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz (skylake_avx512), Python 3.6.8
See https://gist.github.com/4babcad3181e17677983de3c91fbfdad for a full test report.

**Comment by boegel** [comment]
Going in, thanks @zdemat!

**Pull request merged**
