### PR TITLE
{phys}[foss/2016a] pyBERT/20161007 (REVIEW)

### PR DESCRIPTION
**Pull request by hajgato**

### CODE REVIEW

**Comment by boegel** [comment]
Test report by @boegel
**FAILED**
Build succeeded for 2 out of 3 (3 easyconfigs in this PR)
node2598.golett.os - Linux centos linux 7.2.1511, Intel(R) Xeon(R) CPU E5-2680 v3 @ 2.50GHz, Python 2.7.5
See https://gist.github.com/ba07641076a7cd124ce360ddc00409bf for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**FAILED**
Build succeeded for 2 out of 3 (3 easyconfigs in this PR)
node2075.delcatty.os - Linux SL 6.8, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.6.6
See https://gist.github.com/f7d027ccb4792a3eafde3c958af2f187 for a full test report.

**Comment by hajgato** [comment]
@boegel still work in progress.....

**Comment by boegel** [comment]
@hajgato I know, sorry, I only noticed it was tagged as `(WIP)` after submitting the test jobs; I let them run anyway because they may provide useful information ;-)

**Comment by hajgato** [comment]
@boegel This is now in `REVIEW`
`pyGIMLi` is changed, so it have to be rebuilt.

**Comment by boegel** [comment]
Test report by @boegel
**FAILED**
Build succeeded for 0 out of 3 (3 easyconfigs in this PR)
node2098.delcatty.os - Linux SL 6.8, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.6.6
See https://gist.github.com/748c22499f110d7afdd80a66671a644b for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**FAILED**
Build succeeded for 2 out of 3 (3 easyconfigs in this PR)
node2569.golett.os - Linux centos linux 7.2.1511, Intel(R) Xeon(R) CPU E5-2680 v3 @ 2.50GHz, Python 2.7.5
See https://gist.github.com/d7f20282f6eb1f61e748ee43fa14f185 for a full test report.

**Comment by hajgato** [comment]
@boegel I think you need access to `pyBERT` gitlab

**Comment by migueldiascosta** [comment]
@hajgato, this PR is being closed for the following reason(s): no activity for > 1 year.
Please don't hesitate to reopen this PR or add a comment if you feel this contribution is still relevant.
For more information on our policy w.r.t. closing PRs, see https://easybuild.readthedocs.io/en/latest/Contributing.html#why-a-pull-request-may-be-closed-by-a-maintainer

**Pull request closed without merging**
