### PR TITLE
{vis}[GCCcore/6.4.0] X11 v20170805 (w/ Python 3.6.2)

### PR DESCRIPTION
**Pull request by JackPerdue**
(created using `eb --new-pr`)
depends on PR #4975

### CODE REVIEW

**Comment by JackPerdue** [comment]
Someone will have to clarify what Travis is trying to tell me

**Comment by boegel** [comment]
@JackPerdue The problem is with the backticks in `preconfigopts` in the X11 easyconfig, that's not being digested well...

What's going on there exactly? We need a better way of dealing with whatever is going on there.

Also, is it worth installing X11 on top of two different Python versions (Python 3.6.2 here and 2.7.13 in #4979)? Why not just let it pick up the system Python?

**Comment by JackPerdue** [comment]
Whoever thought this was a good idea should be shot.

# Python is required for xcb-proto
allow_system_deps = [('Python', SYS_PYTHON_VERSION)]
pyshortver = '.'.join(SYS_PYTHON_VERSION.split('.')[0:2])

**Comment by JackPerdue** [comment]
Yes we need a version for each Python given the naming scheme:

/sw/eb/sw/X11/20170805-GCCcore-6.4.0-Python-3.6.2-bare/lib/python3.6/site-packages/xcbgen/

SYS_PYTHON_VERSION will not end up with lib/python3.6/site-packages

**Comment by boegel** [comment]
@JackPerdue Do you have any idea if the Python modules installed for xcbgen are at all relevant to us? Are they actually used/required by something, or are they rather just some kind of development tools (in which case we don't really care)?

**Comment by migueldiascosta** [comment]
@JackPerdue, this PR is being closed for the following reason(s): no activity for > 1 year.
Please don't hesitate to reopen this PR or add a comment if you feel this contribution is still relevant.
For more information on our policy w.r.t. closing PRs, see https://easybuild.readthedocs.io/en/latest/Contributing.html#why-a-pull-request-may-be-closed-by-a-maintainer

**Pull request closed without merging**
