### PR TITLE
[GCCCore/8.3.0] add Perl as a build dependency for Autoconf/Automake

### PR DESCRIPTION
**Pull request by JensTimmerman**
needed for https://github.com/easybuilders/easybuild-easyconfigs/issues/8704

### CODE REVIEW

**Comment by JensTimmerman** [comment]
This is probably needed on more easyconfigs

**Comment by JensTimmerman** [comment]
also fixes https://github.com/easybuilders/easybuild-easyconfigs/issues/1822

**Comment by verdurin** [comment]
Test report by @verdurin
**SUCCESS**
Build succeeded for 0 out of 0 (2 easyconfigs in this PR)
easybuild.novalocal - Linux centos linux 7.7.1908, Intel Xeon Processor (Skylake, IBRS), Python 2.7.5
See https://gist.github.com/8681973329c8828a2fab283166a28abf for a full test report.

**Comment by verdurin** [comment]
Test report by @verdurin
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in this PR)
easybuild.novalocal - Linux centos linux 7.7.1908, Intel Xeon Processor (Skylake, IBRS), Python 2.7.5
See https://gist.github.com/b222889e3e65ad4348002614f19770ee for a full test report.

**Comment by verdurin** [comment]
@JensTimmerman could you submit your own test report please?

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in this PR)
generoso-4 - Linux centos linux 7.6.1810, Intel(R) Xeon(R) CPU E5-2660 v4 @ 2.00GHz, Python 3.6.8
See https://gist.github.com/b55df167c91618f63c53d2503fb201f7 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in this PR)
node2420.golett.os - Linux centos linux 7.7.1908, Intel(R) Xeon(R) CPU E5-2680 v3 @ 2.50GHz (haswell), Python 2.7.5
See https://gist.github.com/85e51d59188462c43d77ad99343c5100 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in this PR)
node3126.skitty.os - Linux centos linux 7.7.1908, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz (skylake_avx512), Python 3.6.8
See https://gist.github.com/436fbbdb70319e0c806d570e7a437f5f for a full test report.

**Comment by zao** [comment]
Test report by @zao
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in this PR)
freja - Linux Ubuntu 20.04, Intel(R) Core(TM) i7-8700K CPU @ 3.70GHz, Python 3.8.2
See https://gist.github.com/0958ea9a5d1df3b1e2759473d295b2e3 for a full test report.

**Comment by boegel** [comment]
Going in, thanks @JensTimmerman!

**Pull request merged**
