### PR TITLE
{chem}[foss/2016b] GAMESS-US v20180214-R1

### PR DESCRIPTION
**Pull request by SethosII**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by pescobar** [comment]
Test report by @pescobar
**FAILED**
Build succeeded for 0 out of 2 (2 easyconfigs in this PR)
worker01.cluster.bc2.ch - Linux centos linux 7.3.1611, Intel(R) Xeon(R) CPU E5-2630 v4 @ 2.20GHz, Python 2.7.5
See https://gist.github.com/f9c7a09462be113f8f4ad5f953e94fab for a full test report.

**Comment by SethosII** [comment]
@pescobar The build failed because the source files can't be downloaded directly. Do you have access to them?

**Comment by boegel** [comment]
@SethosII `20180214-R1` is not available for download anymore, there's a new release `20180802-R2`... Maybe just bump the version for this PR?

**Comment by SethosII** [comment]
@boegel I currently don't have the new version but I can request it and see if the easyconfig works for this as well.

**Comment by SethosII** [comment]
@boegel I got `20180802-R2` but it doesn't work like `20180214-R1`.

For one they added OpenBLAS as an math library option, but only partially (only some messages include it ...). I got this to work with a small patch based on the existing OpenBLAS patch. Then I got an error because the questions have changed. I added the question to the easyblock but now the build fails with a linking error:

```
/easybuild/test/software/OpenBLAS/0.2.18-GCC-5.4.0-2.26-LAPACK-3.6.1/lib/libopenblas.a(memory.o):memory.c:function openblas_fork_handler: error: undefined reference to 'pthread_atfork'
collect2: error: ld returned 1 exit status
```

Did someone encounter this before?

**Comment by vanzod** [comment]
Test report by @vanzod
**FAILED**
Build succeeded for 0 out of 2 (2 easyconfigs in this PR)
cermis - Linux debian 9.4, Intel(R) Xeon(R) CPU           E5620  @ 2.40GHz, Python 2.7.13
See https://gist.github.com/3985bd3b7060eaaeb615f781342ddaa7 for a full test report.

**Comment by vanzod** [comment]
Test report by @vanzod
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in this PR)
cermis - Linux debian 9.4, Intel(R) Xeon(R) CPU           E5620  @ 2.40GHz, Python 2.7.13
See https://gist.github.com/92ef6ff81411d3d3e390493fe9aabc45 for a full test report.

**Comment by vanzod** [comment]
@boegel I would go ahead and merge this PR. We can work on an easyconfig for a newer version in a more recent toolchain. Agree?

**Comment by boegel** [comment]
Going in, thanks @SethosII!

**Pull request merged**
