### PR TITLE
GC3Pie/2.5.0 - Add missing dependencies

### PR DESCRIPTION
**Pull request by vanzod**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by vanzod** [comment]
Test report by @vanzod
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
cermis - Linux debian 9.5, Intel(R) Xeon(R) CPU           E5620  @ 2.40GHz, Python 2.7.13
See https://gist.github.com/5530d63931ad4ac194d07d8a867ce66f for a full test report.

**Comment by boegel** [comment]
Hmm, how come we missed this with `exts_download_dep_fail = True` set?

**Comment by vanzod** [comment]
@boegel That's because it is built with the system Python. If you have those packages already installed they are not downloaded at build time. This is the case of my dev box, but I noticed the issue on the production cluster where those packages are not installed from the OS repo.

**Comment by boegel** [comment]
@vanzod `GC3Pie-2.5.0.eb:142:6: E201 whitespace after '('` ;)

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
node3101.skitty.os - Linux centos linux 7.5.1804, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz, Python 2.7.5
See https://gist.github.com/b3047ecb293df16760e5f6abd2851b4d for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
node2683.swalot.os - Linux centos linux 7.5.1804, Intel(R) Xeon(R) CPU E5-2660 v3 @ 2.60GHz, Python 2.7.5
See https://gist.github.com/b3a67567315872cb67b84d1bf759c565 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
node2007.delcatty.os - Linux centos linux 7.5.1804, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.7.5
See https://gist.github.com/9278717e4743893c4b6077a96fd6cf5b for a full test report.

**Comment by boegel** [comment]
@vanzod If @riccardomurri's patch from https://github.com/easybuilders/easybuild-framework/issues/2632 checks out, maybe we should apply it in this easyconfig as well (in a follow-up PR)?

**Comment by boegel** [comment]
Going in, thanks @vanzod!

**Pull request merged**
