### PR TITLE
add PCRE2 and SSL dependencies to MariaDB/10.5.8 easyconfig

### PR DESCRIPTION
**Pull request by sassy-crick**
(created using `eb --new-pr`)

see also #14296

### CODE REVIEW

**Comment by migueldiascosta** [comment]
@sassy-crick are you up to making this consistent across the other easyconfigs, and also add the sanity check commands?

**Comment by sassy-crick** [comment]
@migueldiascosta  I can do that. How far do you want me to go back? I would suggest up to and include `MariaDB-10.3.14-foss-2019a.eb` but I am open here, within reasons.

**Comment by migueldiascosta** [comment]
@sassy-crick sounds good to me

**Comment by boegel** [comment]
@sassy-crick Any updates on this PR?

**Comment by sassy-crick** [comment]
@boegel 
> @sassy-crick Any updates on this PR?

Yes. I looked into the more recent, i.e. `GCC` versions, added an alternative URL, zstd, pkgconf and OpenSSL where required. So that hopefully has now all relevant dependencies from EasyBuild.

**Comment by boegel** [comment]
@sassy-crick Is this still relevant?

If so, please fix the merge conflicts

**Comment by sassy-crick** [comment]
I will close that PR as it is going back to 2021. If that is still required, I think it is better to look into that again with a pair of fresh eyes.

**Pull request closed without merging**
