### PR TITLE
{toolchain}[system/system] intelcuda v2020b, CUDA v11.1.1, iccifortcuda v2020b, impi v2019.9.304, ...

### PR DESCRIPTION
**Pull request by Micket**
(created using `eb --new-pr`)

disclaimer: No idea if these are even compatible. I just bumped versions.

### CODE REVIEW

**Comment by boegel** [comment]
@boegelbot please test @ generoso

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 6 out of 6 (6 easyconfigs in total)
node3104.skitty.os - Linux centos linux 7.8.2003, x86_64, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz, Python 3.6.8
See https://gist.github.com/63ed3667cf797cf97b7132e1bcd6ed75 for a full test report.

**Comment by Micket** [comment]
Test report by @Micket
**SUCCESS**
Build succeeded for 6 out of 6 (6 easyconfigs in total)
alvis-c1 - Linux centos linux 7.8.2003, x86_64, Intel Xeon Processor (Skylake), Python 3.6.8
See https://gist.github.com/5998b3613b651418b87aba5446ea7a4a for a full test report.

**Comment by bartoldeman** [comment]
ICC 19.1 is listed as a supported compiler for CUDA 11.1 so this is supposed to work

**Comment by lexming** [comment]
Test report by @lexming
**SUCCESS**
Build succeeded for 7 out of 7 (6 easyconfigs in total)
node154.hydra.os - Linux centos linux 7.9.2009, x86_64, Intel(R) Xeon(R) CPU E5-2680 v2 @ 2.80GHz, Python 2.7.5
See https://gist.github.com/7c681288146282bfbe3680231bc42b9a for a full test report.

**Review by lexming — APPROVED** [review]
LGTM

**Comment by lexming** [comment]
Going in, thanks @Micket !

**Pull request merged**
