### PR TITLE
{bio}[GCC/10.2.0] VEP 103.1

### PR DESCRIPTION
**Pull request by fizwit**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by migueldiascosta** [comment]
@boegelbot please test @ generoso

**Review by lexming — CHANGES_REQUESTED** [review]
I got some fixes for the issues with this PR:

* The tests of VEP have been fixed in v103.1. We can update to this bugfix release and re-enable the tests.
* The toolchain can be lowered to `GCC/10.2.0`

Please check https://github.com/fizwit/easybuild-easyconfigs/pull/8, it has the previous 2 changes.

Moreover, VEP now needs `Archive::Zip` and a recent `Compress:Raw:Zlib`. I made those changes directly in the Perl easyconfig as those are quite generic packages. See #12627

**Comment by lexming** [comment]
Depends on https://github.com/easybuilders/easybuild-easyconfigs/pull/12651 and https://github.com/easybuilders/easybuild-easyconfigs/pull/12627

**Comment by lexming** [comment]
Test report by @lexming
**SUCCESS**
Build succeeded for 2 out of 2 (1 easyconfigs in total)
node350.hydra.os - Linux centos linux 7.9.2009, x86_64, Intel(R) Xeon(R) Gold 6148 CPU @ 2.40GHz, Python 2.7.5
See https://gist.github.com/ad93368770cb5476fb5165bcfa03c819 for a full test report.

**Review by lexming — APPROVED** [review]
LGTM

**Comment by boegel** [comment]
@boegelbot please test @ generoso

**Comment by boegel** [comment]
@lexming Test installation fails with:
```
Compress::Raw::Zlib version 2.096 required--this is only version 2.093
```

**Comment by lexming** [comment]
@boegel that was fixed in https://github.com/easybuilders/easybuild-easyconfigs/pull/12627

**Comment by verdurin** [comment]
Test report by @verdurin
**FAILED**
Build succeeded for 6 out of 7 (1 easyconfigs in total)
easybuild-c7.novalocal - Linux centos linux 7.9.2009, x86_64, Intel Xeon Processor (Skylake, IBRS), Python 3.6.8
See https://gist.github.com/23c159f32e42fdb06788f4119349c58a for a full test report.

**Comment by boegel** [comment]
> @boegel that was fixed in #12627

Not really, see also https://github.com/easybuilders/easybuild-easyconfigs/pull/12627#issuecomment-823171915

**Comment by verdurin** [comment]
Test report by @verdurin
**FAILED**
Build succeeded for 0 out of 1 (1 easyconfigs in total)
easybuild-c7.novalocal - Linux centos linux 7.9.2009, x86_64, Intel Xeon Processor (Skylake, IBRS), Python 3.6.8
See https://gist.github.com/5c9ec251ab534dff35dc551a7a0da0b8 for a full test report.

**Comment by lexming** [comment]
Test report by @lexming
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
node373.hydra.os - Linux centos linux 7.9.2009, x86_64, Intel(R) Xeon(R) Gold 6148 CPU @ 2.40GHz, Python 2.7.5
See https://gist.github.com/7deb3d880b4bbde56c0cefd7491febd3 for a full test report.

**Review by lexming — DISMISSED** [review]
Now that the issue with `Compress::Raw::Zlib` has been fixed in #12681, we can just include it in the VEP easyconfig.

LGTM

**Comment by verdurin** [comment]
@boegelbot please test @ generoso

**Comment by verdurin** [comment]
Test report by @verdurin
**SUCCESS**
Build succeeded for 7 out of 7 (1 easyconfigs in total)
nuc.lan - Linux Fedora 33, x86_64, Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz, Python 3.9.4
See https://gist.github.com/441d1ab914f1febc16b22a41c4d316a0 for a full test report.

**Review by verdurin — APPROVED** [review]
Looks fine.

**Comment by boegel** [comment]
Install test by bot failed with `Compress::Raw::Zlib version 2.096 required--this is only version 2.093`

@lexming What are we missing here? An update for `$PERL5LIB` via `modextrapaths`?

**Comment by branfosj** [comment]
> Install test by bot failed with `Compress::Raw::Zlib version 2.096 required--this is only version 2.093`
> 
> @lexming What are we missing here? An update for `$PERL5LIB` via `modextrapaths`?

The failure is because the VEP tests that are failing are run before we install the extensions. That, however, leaves me confused as to why it passes.

**Comment by lexming** [comment]
I finally found the actual issue here. It was more complicated than expected and it is *not* related to VEP actually.

VEP has no requirement on Compress::Raw::Zlib. The error
```
Compress::Raw::Zlib version 2.096 required--this is only version 2.093
```
stems from a Compress::Zlib module in the base Perl easyconfig. The funny part is that `Perl-5.32.0-GCCcore-10.2.0.eb` does have **two** Compress::Zlib :
* `$EBROOTPERL/lib/perl5/5.32.0/Compress/Zlib.pm` is the regular one found in the sources of Perl and needs Compress::Raw::Zlib 2.093
* `$EBROOTPERL/lib/perl5/site_perl/5.32.0/Compress/Zlib.pm` is an extra module and the one requiring Compress::Raw::Zlib 2.096

The problem is that Perl 5.32.0 ships with Compress::Raw::Zlib 2.093.

The origin of this extra Compress::Zlib is the extension IO::Compress::Bzip2 v2.096, which installs the whole IO::Compress sources, including Compress::Zlib v2.096. This extension was a [later addition](https://github.com/easybuilders/easybuild-easyconfigs/commit/68da71c5c0230181a58134e556c7490f3c282aae) to `Perl-5.32.0-GCCcore-10.2.0.eb` and my installation of Perl does not have it. This explains why my tests passed.

It should be easy to fix...

**Comment by lexming** [comment]
Test report by @lexming
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in total)
node377.hydra.os - Linux centos linux 7.9.2009, x86_64, Intel(R) Xeon(R) Gold 6148 CPU @ 2.40GHz, Python 2.7.5
See https://gist.github.com/51bca4cdad489ec20cc8dfe37ea68644 for a full test report.

**Comment by verdurin** [comment]
@boegelbot please test @ generoso

**Comment by verdurin** [comment]
Test report by @verdurin
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
easybuild-c7.novalocal - Linux centos linux 7.9.2009, x86_64, Intel Xeon Processor (Skylake, IBRS), Python 3.6.8
See https://gist.github.com/613dc7a62dd8783d1d59a24b9225537e for a full test report.

**Comment by verdurin** [comment]
Test report by @verdurin
**FAILED**
Build succeeded for 0 out of 1 (2 easyconfigs in total)
easybuild-c7.novalocal - Linux centos linux 7.9.2009, x86_64, Intel Xeon Processor (Skylake, IBRS), Python 3.6.8
See https://gist.github.com/d7fdc94f7c00df3274110f94c5bd7ec0 for a full test report.

**Comment by verdurin** [comment]
Test report by @verdurin
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in total)
easybuild-c7.novalocal - Linux centos linux 7.9.2009, x86_64, Intel Xeon Processor (Skylake, IBRS), Python 3.6.8
See https://gist.github.com/3ce9e6459d0448d721a264b25c164c18 for a full test report.

**Comment by verdurin** [comment]
Test report by @verdurin
**SUCCESS**
Build succeeded for 3 out of 3 (2 easyconfigs in total)
nuc.lan - Linux Fedora 33, x86_64, Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz, Python 3.9.5
See https://gist.github.com/36a25f87c92501eff945a1a9f1fd57bd for a full test report.

**Review by verdurin — APPROVED** [review]
Looks fine.

**Comment by verdurin** [comment]
@lexming thanks for tracking down the problem. I can't merge owing to change requests from you, apparently.

**Review by lexming — APPROVED** [review]
LGTM

**Comment by lexming** [comment]
@verdurin approved my own changes 🙂

**Comment by verdurin** [comment]
Going in, thanks @fizwit!

**Comment by fizwit** [comment]
Wow, great work to track this down!

John Dey
***@***.***

**Pull request merged**
