### PR TITLE
define `foss/2024a` toolchain (copy of `foss/2024.05`)

### PR DESCRIPTION
**Pull request by bartoldeman**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by bartoldeman** [comment]
@boegelbot please test @ generoso

**Comment by bartoldeman** [comment]
psm3 reared its ugly head again on generoso, which caused a failure in Open MPI

**Comment by bartoldeman** [comment]
@boegelbot please test @ jsc-zen3

**Comment by branfosj** [comment]
@boegelbot please test @ generoso

**Comment by branfosj** [comment]
@boegelbot please test @ jsc-zen3

**Comment by branfosj** [comment]
Test report by @branfosj
**SUCCESS**
Build succeeded for 8 out of 8 (8 easyconfigs in total)
bear-pg0211u03a.bear.cluster - Linux RHEL 8.6, x86_64, Intel(R) Xeon(R) Gold 6248 CPU @ 2.50GHz (cascadelake), Python 3.6.8
See https://gist.github.com/branfosj/3f9d08920234c0f1130fddce52f3939a for a full test report.

**Comment by branfosj** [comment]
Test report by @branfosj
**SUCCESS**
Build succeeded for 8 out of 8 (8 easyconfigs in total)
bear-pg0210u03a.bear.cluster - Linux RHEL 8.6, x86_64, Intel(R) Xeon(R) Platinum 8480CL (sapphirerapids), Python 3.6.8
See https://gist.github.com/branfosj/bfdef82d084256c941d36cdaf1be17ef for a full test report.

**Comment by branfosj** [comment]
Test report by @branfosj
**SUCCESS**
Build succeeded for 81 out of 81 (8 easyconfigs in total)
bear-pg0105u03a - Linux RHEL 8.6, x86_64, Intel(R) Xeon(R) Platinum 8360Y CPU @ 2.40GHz (icelake), Python 3.6.8
See https://gist.github.com/branfosj/2d007c2dc77b60471139679478d2c396 for a full test report.

**Comment by boegel** [comment]
@boegelbot please test @ generoso

**Comment by bartoldeman** [comment]
> Test report by @boegelbot **FAILED** Build succeeded for 8 out of 9 (8 easyconfigs in total) cns1 - Linux Rocky Linux 8.9, x86_64, Intel(R) Xeon(R) CPU E5-2667 v3 @ 3.20GHz (haswell), Python 3.6.8 See https://gist.github.com/boegelbot/ea31d2daf9117641ec306d4c3874ec52 for a full test report.

seems this failure is caused by a stale lock file for scipy bundle, nothing serious

**Comment by boegel** [comment]
> > Test report by @boegelbot **FAILED** Build succeeded for 8 out of 9 (8 easyconfigs in total) cns1 - Linux Rocky Linux 8.9, x86_64, Intel(R) Xeon(R) CPU E5-2667 v3 @ 3.20GHz (haswell), Python 3.6.8 See https://gist.github.com/boegelbot/ea31d2daf9117641ec306d4c3874ec52 for a full test report.
> 
> seems this failure is caused by a stale lock file for scipy bundle, nothing serious

Lock file removed, was there since 5 Aug'24.

**Comment by boegel** [comment]
@boegelbot please test @ generoso
EB_ARGS="SciPy-bundle-2024.05-gfbf-2024a.eb"

**Review by boegel — APPROVED** [review]
lgtm

**Pull request merged**
