### PR TITLE
{bio,lib}[GCCcore/11.2.0] vcflib v1.0.3, tabixpp v1.1.0, fastahack v1.0.0, ... w/ Python 3.9.6

### PR DESCRIPTION
**Pull request by SethosII**
(created using `eb --new-pr`)

Needs 
- [x] https://github.com/easybuilders/easybuild-easyconfigs/pull/14853
- [x] https://github.com/easybuilders/easybuild-easyconfigs/pull/14854.

### CODE REVIEW

**Comment by jfgrimm** [comment]
Test report by @jfgrimm
**SUCCESS**
Build succeeded for 9 out of 9 (6 easyconfigs in total)
node121.pri.viking.alces.network - Linux UNKNOWN UNKNOWN, x86_64, Intel(R) Xeon(R) Gold 6138 CPU @ 2.00GHz (skylake_avx512), Python 3.6.8
See https://gist.github.com/196914653d14ff36732565a4f938a393 for a full test report.

**Comment by lexming** [comment]
@boegelbot: please test @ generoso

**Comment by lexming** [comment]
Test report by @lexming
**SUCCESS**
Build succeeded for 6 out of 6 (6 easyconfigs in total)
node300.hydra.os - Linux centos linux 7.9.2009, x86_64, Intel(R) Xeon(R) Gold 6148 CPU @ 2.40GHz, Python 2.7.5
See https://gist.github.com/9e69cfd37d32f09a8f7c00c209e76228 for a full test report.

**Review by lexming — APPROVED** [review]
LGTM

**Comment by lexming** [comment]
Going in, thanks @SethosII !

**Pull request merged**
