### PR TITLE
{ai}[foss/2022a] dice-ml v0.9 w/ Python 3.10.4

### PR DESCRIPTION
**Pull request by deniskristak**
new easyconfig as per issue https://github.com/vscentrum/vsc-software-stack/issues/117

### CODE REVIEW

**Comment by deniskristak** [comment]
@boegel I think [this](https://github.com/easybuilders/easybuild-easyconfigs/blob/7681207439fe2712b0a68a3785b1ab4459a0404e/easybuild/easyconfigs/d/DiCE-ML/DiCE-ML-0.9-foss-2022a.eb) is your first draft on the easyconfig :-)

**Comment by boegel** [comment]
@deniskristak Duplicate of https://github.com/easybuilders/easybuild-easyconfigs/pull/17591?

**Comment by deniskristak** [comment]
@boegel yeaah, you were first ;-)

**Comment by boegel** [comment]
@deniskristak OK, let's close then

**Pull request closed without merging**
