### PR TITLE
{data}[foss/2023a] netcdf4-python v1.6.4

### PR DESCRIPTION
**Pull request by stefan-wolfsheimer**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by SebastianAchilles** [comment]
@boegelbot please test @ jsc-zen2

**Comment by SebastianAchilles** [comment]
@boegelbot please test @ generoso

**Comment by SebastianAchilles** [comment]
Test report by @sebastianachilles
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
bwd-rockylinux-92 - Linux Rocky Linux 9.2 (Blue Onyx), x86_64, Intel(R) Core(TM) i7-6900K CPU @ 3.20GHz (broadwell), Python 3.9.16
See https://gist.github.com/SebastianAchilles/c4fc6a8f815235474de8bf5cad151406 for a full test report.

**Comment by SebastianAchilles** [comment]
@boegelbot please test @ generoso

**Comment by boegel** [comment]
@boegelbot please test @ generoso

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
node3144.skitty.os - Linux RHEL 8.6, x86_64, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz (skylake_avx512), Python 3.6.8
See https://gist.github.com/boegel/5fd814325e0f8902d02e60c878811d34 for a full test report.

**Comment by boegel** [comment]
killed job `11825` on `generoso`, let's see if it still takes hours to install `netcdf4-python` there...

**Comment by boegel** [comment]
@boegelbot please test @ generoso

**Comment by boegel** [comment]
Hmm, there were no problem with testing previous versions of `netcdf4-python` on `generoso` (cfr. #16329 and #17822)...

**Comment by boegel** [comment]
Test job is *still* hanging on `generoso`, it's been like this for over 72h now, it's pretty clear it won't finish...

```
$ squeue
             JOBID PARTITION                                               NAME     USER    STATE       TIME TIME_LIMI  NODES   CPUS  NODELIST(REASON) MIN_MEMORY
             11831    normal                                      test_PR_18731 boegelbo  RUNNING 3-03:22:09 4-04:00:00      1      4              cns1 4000M
```

```
boegelb+ 3776650  0.0  0.4 536320 71348 ?        Sl   Oct02   2:59      \_ python3 -m easybuild.main --from-pr 18731 --debug --rebuild --robot --upload-test-report --download-timeout=1000
boegelb+ 3776985  0.0  0.1 180820 19456 ?        Sl   Oct02   0:03          \_ mpirun -n 1 /project/boegelbot/Rocky8/haswell/software/Python/3.11.3-GCCcore-12.3.0/bin/python run_all.py
boegelb+ 3776989  0.0  0.3 1026756 51436 ?       Sl   Oct02   0:00              \_ /project/boegelbot/Rocky8/haswell/software/Python/3.11.3-GCCcore-12.3.0/bin/python run_all.py
```

**Comment by boegel** [comment]
By suggestion of @branfosj, I did a manual installation of this on `generoso` with having `$FI_PROVIDER` defined, which seems to help:

```
export FI_PROVIDER="udp,tcp"
```

**Comment by boegel** [comment]
@boegelbot please test @ generoso
EB_ARGS="--module-only"

**Comment by boegel** [comment]
Cancelled job 11860, trying again after putting workaround in place on `generoso` for hanging `MPI_Init_thread` (cfr. https://github.com/boegel/boegelbot/pull/28)...

**Comment by boegel** [comment]
@boegelbot please test @ generoso

**Review by branfosj — APPROVED** [review]

**Comment by branfosj** [comment]
Going in, thanks @stefan-wolfsheimer!

**Pull request merged**
