### PR TITLE
{vis}[intel/2018a, foss/2018b] fix source URL for Graphviz v2.40.1

### PR DESCRIPTION
**Pull request by lexming**
(created using `eb --new-pr`)

The download URL from fossies.org no longer exists. Since the official download still lacks versioning, I propose to use the same solution from our friends in Spack (I won't say it too loud) and take the sources from the release commit of v2.40.1 in the project's gitlab.

I modified the easyconfig so that it works with both the old sources from fossies and the new ones from gitlab. Checksums for both tarballs are present and the `extract_cmd` ensures that patches do not get confused.

The updated patch file removes changes related to a `Makefile.in` generated by autotools. That file is overwritten by `autogen.sh` in the original sources (no need to patch) and it does not exists in the sources from gitlab.

### CODE REVIEW

**Comment by lexming** [comment]
Test report by @lexming
**FAILED**
Build succeeded for 6 out of 9 (3 easyconfigs in this PR)
node123.hydra.os - Linux centos linux 7.7.1908, x86_64, Intel(R) Xeon(R) CPU E5-2680 v2 @ 2.80GHz, Python 2.7.5
See https://gist.github.com/ccedb439cbe29f7082a2123518e88e9c for a full test report.

**Comment by lexming** [comment]
Test report by @lexming
**SUCCESS**
Build succeeded for 3 out of 3 (3 easyconfigs in this PR)
node125.hydra.os - Linux centos linux 7.7.1908, x86_64, Intel(R) Xeon(R) CPU E5-2680 v2 @ 2.80GHz, Python 2.7.5
See https://gist.github.com/09561953d2a2e71063f45ef4ec856fb6 for a full test report.

**Comment by boegel** [comment]
@boegelbot please test @ generoso

**Review by boegel — APPROVED** [review]
lgtm

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 3 out of 3 (3 easyconfigs in this PR)
node3109.skitty.os - Linux centos linux 7.8.2003, x86_64, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz (skylake_avx512), Python 3.6.8
See https://gist.github.com/a001e3b84de3629e3331b10289f486f8 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 3 out of 3 (3 easyconfigs in this PR)
node2403.golett.os - Linux centos linux 7.8.2003, x86_64, Intel(R) Xeon(R) CPU E5-2680 v3 @ 2.50GHz (haswell), Python 2.7.5
See https://gist.github.com/7b049cd589f60dda87859288b434c006 for a full test report.

**Comment by verdurin** [comment]
Going in, thanks @lexming!

**Pull request merged**
