### PR TITLE
add patches for Boost 1.64.0 to fix known issues

### PR DESCRIPTION
**Pull request by boegel**
fix for #5146

@jhein32 Can you check whether this fixes the problem you were seeing?

### CODE REVIEW

**Comment by boegel** [comment]
@jhein32 To rebuild Boost 1.64.0 with the patch included, you can use `eb --from-pr 5148 --force`

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
node2038.delcatty.os - Linux centos linux 7.3.1611, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.7.5
See https://gist.github.com/e86893d2deebcab48919fc0b220080fd for a full test report.

**Comment by jhein32** [comment]
No joy I am afraid.  I did a:

      nohup eb Boost-1.64.0-intel-2017a.eb --robot --use-existing-modules --from-pr 5148 &> Output-Easybuild/building-boost-1.64.0-intel-2017a-pr5148.out &

no need to force anything since we don't have a Boost.  Issue is still there.  There is a file 

     /tmp/eb-hxMgrg/files_pr5148/b/Boost/Boost-1.64.0_fix-include-array_wrapper.patch 

inside the /tmp directory.  So the download from github seems to work.

**Comment by boegel** [comment]
@jhein32 Can you upload the (debug) build log (preferably via https://gist.github.com/), or show us how you reproduced the problem that is still there?

**Comment by jhein32** [comment]
I sent you the file by email.  Somehow it will not want me to upload it here.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
node2609.swalot.os - Linux centos linux 7.3.1611, Intel(R) Xeon(R) CPU E5-2660 v3 @ 2.60GHz, Python 2.7.5
See https://gist.github.com/d0c3e30eac487cdbf4d20fa8bd7d615b for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
node2098.delcatty.os - Linux centos linux 7.3.1611, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.7.5
See https://gist.github.com/d13cfd7558d6b0d5678f9cd75be9988e for a full test report.

**Comment by boegel** [comment]
@jhein32 based on your log file, this is the issue you're hitting:

```
./boost/mpi/detail/mpi_datatype_primitive.hpp(28): catastrophic error: cannot open source file "boost/serialization/detail/get_data.hpp"
```

This is known issue with Boost 1.64.0, which requires an extra patch, see https://github.com/boostorg/mpi/pull/49.

Now included in this PR, so please try again?

**Comment by jhein32** [comment]
Thanks. That builds without issue.

J.

**Comment by boegel** [comment]
@jhein32 And does it also resolve the problem you had with `MariaDB` & `DBD-mysql`?

**Comment by jhein32** [comment]
The download link for the MariaDB is broken.  Is that some thing that should be fixed?

**Comment by jhein32** [comment]
The DBD-mysql builds (after manual download of MariaDB sources).

**Comment by boegel** [comment]
@jhein32 Seems like they did a great job of screwing up automatic downloads of MariaDB source tarballs... Please open a separate issue on that?

**Pull request merged**
