### PR TITLE
{math}[system/system] Mathematica v12.1.1

### PR DESCRIPTION
**Pull request by terjekv**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by smoors** [comment]
Test report by @smoors
**FAILED**
Build succeeded for 0 out of 1 (1 easyconfigs in this PR)
node381.hydra.os - Linux centos linux 7.7.1908, x86_64, Intel(R) Xeon(R) Gold 6148 CPU @ 2.40GHz (skylake_avx512), Python 2.7.5
See https://gist.github.com/c0515f51c4a93e428ea72e5f43e255f8 for a full test report.

**Comment by boegel** [comment]
@terjekv How about exposing their screw-up a bit, and adding an easyconfig file with a `-orig` versionsuffix that has the old checksum?

**Comment by boegel** [comment]
> @terjekv How about exposing their screw-up a bit, and adding an easyconfig file with a `-orig` versionsuffix that has the old checksum?

Additional easyconfig with original Mathematica 12.1.1 release in #10846

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
node2441.golett.os - Linux centos linux 7.8.2003, x86_64, Intel(R) Xeon(R) CPU E5-2680 v3 @ 2.50GHz (haswell), Python 2.7.5
See https://gist.github.com/fac7c9fb2f0f28ef19d819475977757d for a full test report.

**Comment by boegel** [comment]
Going in, thanks @terjekv!

**Pull request merged**
