### PR TITLE
{chem}[iimpi/2020a] OpenBabel v3.1.1 w/ Python 3.8.2

### PR DESCRIPTION
**Pull request by boegel**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by boegel** [comment]
@boegelbot please test @ generoso

**Comment by boegel** [comment]
Test report by @boegel
**FAILED**
Build succeeded for 0 out of 1 (1 easyconfigs in total)
node3594.doduo.os - Linux RHEL 8.2, x86_64, AMD EPYC 7552 48-Core Processor (zen2), Python 3.6.8
See https://gist.github.com/2d00a9122e82142200e1f70444f7037d for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**FAILED**
Build succeeded for 0 out of 1 (1 easyconfigs in total)
node2717.swalot.os - Linux centos linux 7.9.2009, x86_64, Intel(R) Xeon(R) CPU E5-2660 v3 @ 2.60GHz (haswell), Python 3.6.8
See https://gist.github.com/da0c4d6d6e8d525413359433549bab17 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
node2717.swalot.os - Linux centos linux 7.9.2009, x86_64, Intel(R) Xeon(R) CPU E5-2660 v3 @ 2.60GHz (haswell), Python 3.6.8
See https://gist.github.com/aebcc3040275d042957e3a2cfb0ded2e for a full test report.

**Comment by boegel** [comment]
For some reason that's not entirely clear to me yet, the installation sometimes fails when running `make install` with:

```
make[2]: *** No rule to make target `/user/gent/400/vsc40023/eb_scratch/CO7/haswell-ib/software/OpenBabel/3.1.1-iimpi-2020a-Python-3.8.2/lib/libmaeparser.so', needed by `lib/libopenbabel.so.7.0.0'.  Stop.
```

Also happens with `eb --parallel 1` (which doesn't have any effect on `make install` anyway), so it's not the usual breaking when building with too many cores...

**Comment by boegel** [comment]
The problem seems to be that the installation directory already gets (partially?) populated in the build step somehow, so `make -j X` is already *installing* stuff, rather than just building...
If the (complete) OpenBabel installation was already there, then things get messed up, and `make install` gets very confused.

Luckily CMake is involved, so this should be easy to figure out </sarcasm>

**Comment by boegel** [comment]
> The problem seems to be that the installation directory already gets (partially?) populated in the build step somehow, so `make -j X` is already _installing_ stuff, rather than just building... If the (complete) OpenBabel installation was already there, then things get messed up, and `make install` gets very confused.
> 
> Luckily CMake is involved, so this should be easy to figure out

Hmm, seems like that's not actually correct, I've also seen the installation directory remain empty after the `build` step...
This is getting weirder by each try.

**Comment by smoors** [comment]
Test report by @smoors
**SUCCESS**
Build succeeded for 2 out of 2 (1 easyconfigs in total)
node369.hydra.os - Linux centos linux 7.9.2009, x86_64, Intel(R) Xeon(R) Gold 6148 CPU @ 2.40GHz (skylake_avx512), Python 2.7.5
See https://gist.github.com/1e49ce57cc89e7f396067a2afc8773dd for a full test report.

**Comment by boegel** [comment]
@boegelbot please test @ generoso

**Comment by boegel** [comment]
> @boegel could it be a filesystem issue?

I don't think so, it's reproducible on `generoso` too...

@smoors What happens if you try to reinstall this easyconfig, with the existing installation already in place?

**Comment by branfosj** [comment]
From a clean build:
```
-- maeparser include dir set as 'maeparser_INCLUDE_DIRS-NOTFOUND'
-- maeparser libraries set as 'maeparser_LIBRARIES-NOTFOUND'
-- Downloaded MaeParser 'v1.2.3' to /dev/shm/build-branfosj-admin/branfosj-admin-up/OpenBabel/3.1.1/iimpi-2020a-Python-3.8.2/openbabel-openbabel-3-1-1/external/maeparser-v1.2.3.
-- Found Boost: /rds/bear-apps/devel/eb-sjb-up/EL8/EL8-cas/software/Boost/1.72.0-iimpi-2020a/lib64/cmake/Boost-1.72.0/BoostConfig.cmake (found version "1.72.0") found components: iostreams 
-- Using zlib library for iostreams dependency.
-- Maestro formats will be supported. Using MaeParser 'v1.2.3' at /dev/shm/build-branfosj-admin/branfosj-admin-up/OpenBabel/3.1.1/iimpi-2020a-Python-3.8.2/openbabel-openbabel-3-1-1/external/maeparser-v1.2.3
```

From a rebuild:
```
-- maeparser include dir set as '/rds/bear-apps/devel/eb-sjb-up/EL8/EL8-cas/software/OpenBabel/3.1.1-iimpi-2020a-Python-3.8.2/include'
-- maeparser libraries set as '/rds/bear-apps/devel/eb-sjb-up/EL8/EL8-cas/software/OpenBabel/3.1.1-iimpi-2020a-Python-3.8.2/lib/libmaeparser.so'
-- Maestro formats will be supported. Using MaeParser libraries at /rds/bear-apps/devel/eb-sjb-up/EL8/EL8-cas/software/OpenBabel/3.1.1-iimpi-2020a-Python-3.8.2/lib/libmaeparser.so.
```

I.e. in the rebuild it detects the `libmaeparser.so` from the first build and uses it. However, that will be deleted during the install step of the rebuild.


There is also:
```
-- Downloaded Coordgen 'master' to /dev/shm/build-branfosj-admin/branfosj-admin-up/OpenBabel/3.1.1/iimpi-2020a-Python-3.8.2/openbabel-openbabel-3-1-1/external/coordgen-master.
-- Found PkgConfig: /usr/bin/pkg-config (found version "1.4.2")
```

**Comment by branfosj** [comment]
Looking at the CMakeLists.txt we should add
* `maeparser` as a dependency. OpenBabel 3.1.1 downloads version 1.2.3
* `CoordgenLibs` as a dependency. OpenBabel 3.1.1 downloads the git master
* `pkg-config` as a builddependency

**Comment by boegel** [comment]
> Looking at the CMakeLists.txt we should add
> 
>     * `maeparser` as a dependency. OpenBabel 3.1.1 downloads version 1.2.3
> 
>     * `CoordgenLibs` as a dependency. OpenBabel 3.1.1 downloads the git master
> 
>     * `pkg-config` as a builddependency

Oh boy, OK... Thanks a lot for the deep dive here @branfosj!

**Comment by boegel** [comment]
@boegelbot please test @ generoso
CORE_CNT=16

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 3 out of 3 (3 easyconfigs in total)
node3114.skitty.os - Linux RHEL 8.4, x86_64, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz (skylake_avx512), Python 3.6.8
See https://gist.github.com/48561e47142cbe15f3940bd2d4979d23 for a full test report.

**Comment by boegel** [comment]
@boegelbot please test @ generoso
CORE_CNT=16

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 3 out of 3 (3 easyconfigs in total)
node3114.skitty.os - Linux RHEL 8.4, x86_64, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz (skylake_avx512), Python 3.6.8
See https://gist.github.com/2eed134f8bac49ff1fc8d11dad9d7ff0 for a full test report.

**Review by verdurin — APPROVED** [review]
Looks fine.

**Comment by verdurin** [comment]
Going in, thanks @boegel!

**Comment by verdurin** [comment]
Going in, thanks @boegel!

**Comment by verdurin** [comment]
Going in, thanks @boegel!

**Comment by verdurin** [comment]
Going in, thanks @boegel!

**Pull request merged**
