### PR TITLE
{bio}[fosscuda/2019b] RoseTTAFold v1.0.0 w/ Python 3.7.4

### PR DESCRIPTION
**Pull request by zemu-unile**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by zemu-unile** [comment]
Depends on #13794 #13793 #13792

**Comment by zemu-unile** [comment]
Test report by @zemu-unile
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
login01.sc.uni-leipzig.de - Linux centos linux 7.9.2009, x86_64, AMD EPYC 7551P 32-Core Processor, Python 3.6.8
See https://gist.github.com/791d88cbfeb3c8e7cfbe0a73cc8a62c4 for a full test report.

**Comment by SebastianAchilles** [comment]
@boegelbot please test @ generoso

**Comment by SebastianAchilles** [comment]
@boegelbot please test @ generoso

> Test report by @boegelbot
> **FAILED**
> Build succeeded for 9 out of 14 (1 easyconfigs in total)
> cnx1 - Linux rocky linux 8.4, x86_64, Intel(R) Xeon(R) CPU E5-2690 v3 @ 2.60GHz (haswell), Python 3.6.8
> See https://gist.github.com/820decc93a153891a7a3ceae18c2477c for a full test report.

Failed with `SIGKILL` in `PyTorch-1.8.1-fosscuda-2019b-Python-3.7.4.eb`.
https://gist.github.com/boegelbot/92e258ef2737604701192ebb01cdd6b3#file-pytorch-1-8-1-fosscuda-2019b-python-3-7-4_partial-log-L491

**Comment by SebastianAchilles** [comment]
@boegelbot please test @ generoso
CORE_CNT=16

**Comment by SebastianAchilles** [comment]
> Test report by @boegelbot
> **FAILED**
> Build succeeded for 3 out of 5 (1 easyconfigs in total)
> cnx2 - Linux rocky linux 8.4, x86_64, Intel(R) Xeon(R) CPU E5-2660 v4 @ 2.00GHz (broadwell), Python 3.6.8
> See https://gist.github.com/5f3580ce243719e888d996883a7225ea for a full test report.

Failed because generoso has no sources for `PyRosetta` (no license).

**Review by jfgrimm — COMMENTED** [review]
As decided in issue #16330, we have deprecated the use of `True` to signify a system-toolchain dependency (#16384), in favour of the more intuitive `SYSTEM` template constant. Due to the change in the test suite, please run `eb --sync-pr-with-develop 13795` and update the PR to use `SYSTEM` instead.

**Comment by boegel** [comment]
closing this since `fosscuda/2019b` is no longer supported, see https://docs.easybuild.io/policies/toolchains

**Pull request closed without merging**
