### PR TITLE
{bio}[GCCcore/8.3.0,GCCcore/9.3.0] pyEGA3 v3.4.0 w/ Python 3.7.4 + 3.8.2

### PR DESCRIPTION
**Pull request by verdurin**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by verdurin** [comment]
Test report by @verdurin
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in this PR)
easybuild.novalocal - Linux centos linux 7.8.2003, x86_64, Intel Xeon Processor (Skylake, IBRS), Python 2.7.5
See https://gist.github.com/a6305e03f88e0e33e5d28707f0c7bb9f for a full test report.

**Comment by mboisson** [comment]
Why not make this a single recipe with `multi_deps` ?

**Comment by mboisson** [comment]
Oh, nevermind... I just saw there's a mapping between python version and GCCcore versions.

**Comment by smoors** [comment]
Test report by @smoors
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in total)
node201.hydra.os - Linux centos linux 7.7.1908, x86_64, Intel(R) Xeon(R) CPU E5-2680 v4 @ 2.40GHz (broadwell), Python 2.7.5
See https://gist.github.com/4c8c69493b3d75e1fcbcdeec8941622d for a full test report.

**Comment by smoors** [comment]
@boegelbot please test @ generoso

**Review by smoors — APPROVED** [review]
lgtm

**Comment by smoors** [comment]
Going in, thanks @verdurin!

**Pull request merged**
