### PR TITLE
{cae}[intel/2020a] gmsh v4.4.0

### PR DESCRIPTION
**Pull request by ekieffer**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by ekieffer** [comment]
Test report by @ULHPC
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
iris-002 - Linux centos linux 7.8.2003, x86_64, Intel(R) Xeon(R) CPU E5-2680 v4 @ 2.40GHz, Python 3.6.8
See https://gist.github.com/efc8b21c99a702e3bf4547ec171e3ce1 for a full test report.

**Comment by lexming** [comment]
Test report by @lexming
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
node374.hydra.os - Linux centos linux 7.7.1908, x86_64, Intel(R) Xeon(R) Gold 6148 CPU @ 2.40GHz, Python 2.7.5
See https://gist.github.com/77419feccd4387c222028b9befd42da4 for a full test report.

**Review by lexming — CHANGES_REQUESTED** [review]
This PR works, but it is always desirable to build the software from sources instead of installing pre-compiled binaries. Please check the existing easyconfigs of `gmsh`, such as `gmsh-4.5.6-intel-2019b-Python-2.7.16.eb` and update this PR accordingly to build `gmsh` from sources.

**Comment by Falkor** [comment]
Superseeded by https://github.com/easybuilders/easybuild-easyconfigs/pull/12276 thus I suggest you close the PR

**Comment by boegel** [comment]
> Superseeded by #12276 thus I suggest you close the PR

Makes sense, I'll close this.

**Pull request closed without merging**
