### PR TITLE
{bio}[foss/2020b] BUSCO v4.0.6 w/ Python 3.8.6

### PR DESCRIPTION
**Pull request by boegel**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
node3134.skitty.os - Linux CentOS Linux 7.9.2009, x86_64, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz, Python 3.6.8
See https://gist.github.com/2ba773ae57e71ec289320f2f768c2271 for a full test report.

**Comment by casparvl** [comment]
@boegelbot please test @generoso

**Review by casparvl — APPROVED** [review]
Looks good to me, no surprising changes in the `--review-pr`

**Comment by casparvl** [comment]
Going in, thanks @boegel!

**Pull request merged**
