### PR TITLE
{math}[GCC/8.3.0] GEOS v3.8.0

### PR DESCRIPTION
**Pull request by alexandermichels**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by boegel** [comment]
@alexandermichels Just wondering: is there any reason you can't or don't want to use the existing `GEOS-3.8.0-GCC-8.3.0-Python-3.7.4.eb`, which also includes the Python bindings?

**Comment by alexandermichels** [comment]
We are using Easybuild to help provide user kernels on a JupyterHub instance, so the user environment is modules plus a Anaconda environment. We decided to strip out the Python just in case it caused issues with the environment.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 2 out of 2 (1 easyconfigs in total)
node2673.swalot.os - Linux CentOS Linux 7.9.2009, x86_64, Intel(R) Xeon(R) CPU E5-2660 v3 @ 2.60GHz (haswell), Python 3.6.8
See https://gist.github.com/67929c29c46380550996e7d93f6008ff for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
node3512.doduo.os - Linux RHEL 8.4, x86_64, AMD EPYC 7552 48-Core Processor (zen2), Python 3.6.8
See https://gist.github.com/094da730350fb093343e477b743c5f40 for a full test report.

**Review by boegel — APPROVED** [review]
lgtm

**Comment by boegel** [comment]
Going in, thanks @alexandermichels!

**Pull request merged**
