### PR TITLE
{bio}[foss/2018b] AFNI v18.3.00, tcsh v6.20.00

### PR DESCRIPTION
**Pull request by boegel**
(created using `eb --new-pr`)
requires ~~#6996~~ (motif) + ~~#6266~~ (for AFNI patch file)

edit: ~~#7249~~ should go in first, since that includes an alternate/better easyconfig for `PyQt5`

### CODE REVIEW

**Comment by boegel** [comment]
Test report by @boegel
**FAILED**
Build succeeded for 7 out of 11 (4 easyconfigs in this PR)
node2512.golett.os - Linux centos linux 7.5.1804, Intel(R) Xeon(R) CPU E5-2680 v3 @ 2.50GHz, Python 2.7.5
See https://gist.github.com/c403324743c52830106534bb2318c707 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**FAILED**
Build succeeded for 3 out of 4 (4 easyconfigs in this PR)
node2002.delcatty.os - Linux centos linux 7.5.1804, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.7.5
See https://gist.github.com/18b674b8a9b9ca8d141c2987dfab6b36 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 4 out of 4 (4 easyconfigs in this PR)
node2010.delcatty.os - Linux centos linux 7.5.1804, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.7.5
See https://gist.github.com/c97028235695669269df977058ffbefc for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**FAILED**
Build succeeded for 2 out of 5 (4 easyconfigs in this PR)
node2485.golett.os - Linux centos linux 7.5.1804, Intel(R) Xeon(R) CPU E5-2680 v3 @ 2.50GHz, Python 2.7.5
See https://gist.github.com/a78b37d086b0f963fca173789ee0fc39 for a full test report.

**Comment by boegel** [comment]
@vanzod Why did you close this? It's still relevant imho (in part as a dep for #7059), but the `PyQt5` easyconfig from #7249 should get preference.

**Comment by vanzod** [comment]
I was going to re-trigger Travis but I was also waiting for #7249 to be merged.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in this PR)
node2655.swalot.os - Linux centos linux 7.5.1804, Intel(R) Xeon(R) CPU E5-2660 v3 @ 2.60GHz, Python 2.7.5
See https://gist.github.com/3ac15b419384654b4296508c65c2b362 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in this PR)
node2001.delcatty.os - Linux centos linux 7.5.1804, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.7.5
See https://gist.github.com/257922e0f4d69c945f2b505f1b7f3171 for a full test report.

**Comment by vanzod** [comment]
Test report by @vanzod
**FAILED**
Build succeeded for 3 out of 4 (2 easyconfigs in this PR)
cermis - Linux debian 9.6, Intel(R) Xeon(R) CPU           E5620  @ 2.40GHz, Python 2.7.13
See https://gist.github.com/f2a692fb0b3bc089f979833b787743cc for a full test report.

**Comment by vanzod** [comment]
@boegel It looks like `AFNI` needs `libXp`

**Comment by boegel** [comment]
@vanzod `libXp` is already included in `X11` since #6873, you probably just need to reinstall the `X11` bundle? Make sure you're also using https://github.com/easybuilders/easybuild-easyblocks/pull/1598 (to build the `X11` components in parallel).

**Comment by vanzod** [comment]
Test report by @vanzod
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in this PR)
cermis - Linux debian 9.6, Intel(R) Xeon(R) CPU           E5620  @ 2.40GHz, Python 2.7.13
See https://gist.github.com/e9762d19b7101733ea2b74a7ae001e62 for a full test report.

**Comment by vanzod** [comment]
Going in, thanks @boegel!

**Pull request merged**
