### PR TITLE
{bio}[foss/2016b] fastq-tools 0.8

### PR DESCRIPTION
**Pull request by SethosII**
This adds fastq-tools.

I had one issue with the easyconfig during the build. The `LIBS` variable somehow becomes `LIBS = -lm -lpthread-lm` and this obviously results in `error: cannot find -lpthread-lm` during linking. Here is the log of the build: [easybuild-fastq-tools-0.8-20171123.134323.HYgMZ.log](https://github.com/easybuilders/easybuild-easyconfigs/files/1499421/easybuild-fastq-tools-0.8-20171123.134323.HYgMZ.log)

### CODE REVIEW

**Comment by SethosII** [comment]
Hm, the travis build succeded, so I guess the issue with the `LIBS` variable has something to do with my system?

**Comment by boegel** [comment]
@SethosII The problem is caused by the `configure` script not taking into account that `$LIBS` may be already defined in the environment; it's defined by EasyBuild as `-lm -lpthread`.

This seems to fix the issue:

```python
preconfigopts = './autogen.sh && unset LIBS && '
```

**Comment by SethosII** [comment]
@boegel Thanks! The [configure template](https://github.com/dcjones/fastq-tools/blob/master/configure.ac#L56) just adds `-lm` regardless of what `LIBS` is. I changed it in the easyconfig, so it works now.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 2 out of 2 (1 easyconfigs in this PR)
node2598.golett.os - Linux centos linux 7.4.1708, Intel(R) Xeon(R) CPU E5-2680 v3 @ 2.50GHz, Python 2.7.5
See https://gist.github.com/bb819fc12b20c4202fbc1c6735c45267 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
gligar02.gligar.os - Linux centos linux 7.4.1708, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.7.5
See https://gist.github.com/9107fedc92d98f6c6e4954cd875a7345 for a full test report.

**Comment by boegel** [comment]
Going in, thanks @SethosII!

**Pull request merged**
