### PR TITLE
{chem}[foss/2023a] QuantumESPRESSO v7.2

### PR DESCRIPTION
**Pull request by maxim-masterov**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by branfosj** [comment]
@boegelbot please test @ jsc-zen2

**Comment by branfosj** [comment]
Test report by @branfosj
**SUCCESS**
Build succeeded for 2 out of 2 (1 easyconfigs in total)
bear-pg0105u03a.bear.cluster - Linux RHEL 8.6, x86_64, Intel(R) Xeon(R) Platinum 8360Y CPU @ 2.40GHz (icelake), Python 3.6.8
See https://gist.github.com/branfosj/b284bbb3e77ad6c6758cf0106d90065b for a full test report.

**Review by branfosj — APPROVED** [review]

**Comment by branfosj** [comment]
@boegelbot please test @ generoso

**Comment by branfosj** [comment]
@boegelbot please test @ generoso
CORE_CNT=16

**Comment by branfosj** [comment]
@boegelbot please test @ jsc-zen2
CORE_CNT=16

**Comment by SebastianAchilles** [comment]
Test report by @sebastianachilles
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
bwd-rockylinux-92 - Linux Rocky Linux 9.2 (Blue Onyx), x86_64, Intel(R) Core(TM) i7-6900K CPU @ 3.20GHz (broadwell), Python 3.9.16
See https://gist.github.com/SebastianAchilles/0636d1f043597441882b6cce7589b1ce for a full test report.

**Comment by branfosj** [comment]
@boegelbot please test @ jsc-zen2
CORE_CNT=16

**Comment by maxim-masterov** [comment]
This PR was merged, but I do not see `QuantumESPRESSO-7.2-foss-2023a.eb` in the develop branch and somehow can't use `--from-pr` in the local installation. Did something go wrong?

**Comment by maxim-masterov** [comment]
@SebastianAchilles Done: PR #18916

**Pull request merged**
