### PR TITLE
use proper dependency for tensorboard in easyconfigs for TensorFlow v2.15.1

### PR DESCRIPTION
**Pull request by lexming**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by boegel** [comment]
@Flamefire Thoughts on this?

**Comment by Flamefire** [comment]
Haven't checked that all current packages are contained in the tensorboard EC but if they are I see no issue here so that's good for reuse in other ECs. That is if that works with the versions for TensorFlow used in TensorBoard.

**Comment by lexming** [comment]
Sorry I forgot to explain my motivation. The reason for this is to be able to apply fixes for `tensorboard` without having to rebuild `TensorFlow`. Specifically #20823. And since we already have a standalone `tensorboard` it's easy to split it out to simplify the maintenance.

**Comment by lexming** [comment]
@boegelbot: please test @ generoso
EB_ARGS="TensorFlow-2.15.1-foss-2023a.eb"

**Review by boegel — APPROVED** [review]
lgtm

**Comment by boegel** [comment]
@boegelbot: please test @ jsc-zen3-a100
EB_ARGS="TensorFlow-2.15.1-foss-2023a-CUDA-12.1.1.eb"
CORE_CNT=16

**Comment by boegel** [comment]
Going in, thanks @lexming!

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in total)
node3309.joltik.os - Linux RHEL 8.8, x86_64, Intel(R) Xeon(R) Gold 6242 CPU @ 2.80GHz, 1 x NVIDIA Tesla V100-SXM2-32GB, 545.23.08, Python 3.6.8
See https://gist.github.com/boegel/32facf099f2023d29757318422538c2d for a full test report.

**Pull request merged**
