### PR TITLE
{chem,phys}[GCCcore/10.2.0] ASAP3 v3.12.2, kim-api v2.2.1, openkim-models v20190725 w/ Python 3.8.6

### PR DESCRIPTION
**Pull request by schiotz**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by schiotz** [comment]
Test report by @schiotz
**SUCCESS**
Build succeeded for 5 out of 5 (4 easyconfigs in total)
svol.fysik.dtu.dk - Linux centos linux 7.9.2009, x86_64, Intel(R) Xeon(R) Gold 6148 CPU @ 2.40GHz, Python 2.7.5
See https://gist.github.com/0e218a81384d187f3c5319872ef10e73 for a full test report.

**Comment by schiotz** [comment]
Test report by @schiotz
**SUCCESS**
Build succeeded for 5 out of 5 (4 easyconfigs in total)
slid.fysik.dtu.dk - Linux centos linux 7.9.2009, x86_64, Intel(R) Xeon(R) CPU E5-2650 v4 @ 2.20GHz, Python 2.7.5
See https://gist.github.com/61ac02f7152256c1e103645522a85556 for a full test report.

**Comment by smoors** [comment]
Test report by @smoors
**SUCCESS**
Build succeeded for 18 out of 18 (4 easyconfigs in total)
node369.hydra.os - Linux centos linux 7.9.2009, x86_64, Intel(R) Xeon(R) Gold 6148 CPU @ 2.40GHz (skylake_avx512), Python 2.7.5
See https://gist.github.com/c4e7885fd9bb0f26ae2b09faab199ba5 for a full test report.

**Comment by smoors** [comment]
@boegelbot: please test @ generoso

**Review by smoors — APPROVED** [review]
lgtm

**Comment by smoors** [comment]
Going in, thanks @schiotz!

**Pull request merged**
