### PR TITLE
{lang}[system/system] Java v1.8.0_241

### PR DESCRIPTION
**Pull request by Falkor**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by Falkor** [comment]
Test report by @ULHPC
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
iris-005 - Linux centos linux 7.7.1908, Intel(R) Xeon(R) CPU E5-2680 v4 @ 2.40GHz, Python 3.7.4
See https://gist.github.com/475f9ccba62a0960d4969507935bdd06 for a full test report.

**Comment by Falkor** [comment]
some checks are failing yet at the ' install OS & Python packages' step (caching of some packages fail and thus a timeout was reached upon `apt-get install` step). 
Is there a way to force the tests ?

**Comment by lexming** [comment]
@Falkor I re-triggered the checks

**Comment by lexming** [comment]
Test report by @lexming
**FAILED**
Build succeeded for 0 out of 2 (2 easyconfigs in this PR)
node352.hydra.os - Linux centos linux 7.7.1908, Intel(R) Xeon(R) Gold 6148 CPU @ 2.40GHz, Python 2.7.5
See https://gist.github.com/cbfc396e0e56e329ac3b5eba0584a7d0 for a full test report.

**Comment by lexming** [comment]
Test report by @lexming
**FAILED**
Build succeeded for 0 out of 2 (2 easyconfigs in this PR)
node376.hydra.os - Linux centos linux 7.7.1908, Intel(R) Xeon(R) Gold 6148 CPU @ 2.40GHz, Python 2.7.5
See https://gist.github.com/1f5934a3222c57c4abd782f08bdecd1f for a full test report.

**Comment by lexming** [comment]
Test report by @lexming
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in this PR)
node376.hydra.os - Linux centos linux 7.7.1908, Intel(R) Xeon(R) Gold 6148 CPU @ 2.40GHz, Python 2.7.5
See https://gist.github.com/adfc3c475708ceca22fc0c7b1e98f5c0 for a full test report.

**Comment by lexming** [comment]
Going in, thanks @Falkor !

**Pull request merged**
