### PR TITLE
{bio}[foss/2020b] MultiQC v1.11 w/ Python 3.8.6

### PR DESCRIPTION
**Pull request by genio0815**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by lexming** [comment]
@boegelbot: please test @ generoso

**Comment by lexming** [comment]
Test report by @lexming
**FAILED**
Build succeeded for 0 out of 1 (1 easyconfigs in total)
node301.hydra.os - Linux centos linux 7.9.2009, x86_64, Intel(R) Xeon(R) Gold 6148 CPU @ 2.40GHz, Python 2.7.5
See https://gist.github.com/7a464e3f9032c73f3d31b829704f23f6 for a full test report.

**Review by lexming — CHANGES_REQUESTED** [review]
Thanks for your contribution @genio0815 . This version of MultiQC should use a newer toolchain than `2020b`. It depends on netwrokx>=2.5.1 but `foss/2020b` is restricted to netwrokx==2.5.

We have a rule for all easyconfigs in this repository that limits the versions used as dependencies on each toolchain to only one.

I suggest to use `foss/2021a` instead, is that suitable for you?

**Comment by genio0815** [comment]
Hi,

right, MultiQC 1.11 requires networkx>=2.5.1 (https://github.com/ewels/MultiQC/blob/v1.11/setup.py#L41). As in  `foss/2020b` a matching version  [2.6.2](https://github.com/easybuilders/easybuild-easyconfigs/blob/develop/easybuild/easyconfigs/n/networkx/networkx-2.6.2-foss-2020b.eb) of networkx is available I used it.
Currently we don't have `foss/2021a` implemented yet but will update the easyconfig and update the PR!

**Comment by bedroge** [comment]
@genio0815 now that 1.11 with foss 2021a was merged in https://github.com/easybuilders/easybuild-easyconfigs/pull/14599, I guess this PR is not relevant anymore?

**Comment by genio0815** [comment]
Hi, right, so closing, thx for the effort and checks!

**Pull request closed without merging**
