### PR TITLE
{vis}[foss/2023a] MONAI v1.3.0 w/ CUDA 12.1.1

### PR DESCRIPTION
**Pull request by PetrKralCZ**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by PetrKralCZ** [comment]
Needs:
- https://github.com/easybuilders/easybuild-easyconfigs/pull/20493

**Comment by PetrKralCZ** [comment]
@boegelbot please test @ generoso

**Comment by smoors** [comment]
@boegelbot please test @ jsc-zen3

**Review by smoors — APPROVED** [review]
lgtm

**Comment by smoors** [comment]
Going in, thanks @PetrKralCZ!

**Pull request merged**
