### PR TITLE
{lib}[system/system] IJulia v1.23.3

### PR DESCRIPTION
**Pull request by lexming**
(created using `eb --new-pr`)

Depends on:
* [ ] https://github.com/easybuilders/easybuild-easyblocks/pull/2816

### CODE REVIEW

**Comment by lexming** [comment]
Test report by @lexming
Using easyblocks from PR(s) https://github.com/easybuilders/easybuild-easyblocks/pull/2816
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
login2.cerberus.os - Linux CentOS Linux 7.9.2009, x86_64, Intel(R) Xeon(R) Gold 6126 CPU @ 2.60GHz, Python 3.6.8
See https://gist.github.com/b84b13ee72bd88e3d3a40e2eb69e3e89 for a full test report.

**Comment by lexming** [comment]
@boegelbot: please test @ generoso
EB_ARGS="--include-easyblocks-from-pr 2816"

**Comment by lexming** [comment]
@boegelbot: please test @ generoso
EB_ARGS="--include-easyblocks-from-pr 2816"

**Comment by boegel** [comment]
Test report by @boegel
Using easyblocks from PR(s) https://github.com/easybuilders/easybuild-easyblocks/pull/2816
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
node3139.skitty.os - Linux RHEL 8.4, x86_64, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz (skylake_avx512), Python 3.6.8
See https://gist.github.com/bcd08093751cf3707b71dcb37e00e5fc for a full test report.

**Pull request merged**
