### PR TITLE
{ai}[foss/2022a] Ultralytics v8.0.92 w/ Python 3.10.4

### PR DESCRIPTION
**Pull request by Micket**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by verdurin** [comment]
```
== 2023-05-18 18:40:17,683 build_log.py:171 ERROR EasyBuild crashed with an error (at easybuild/base/exceptions.py:126 in __init__): `/eb/maint/software/Python/3.10.4-GCCcore-11.3.0/bin/python -m pip check` failed:
ultralytics 8.0.92 requires opencv-contrib-python, which is not installed.
 (at easybuild/easyblocks/generic/pythonpackage.py:918 in sanity_check_step)
 ```
 
 Do I need to rebuild something to pick up this dep, or is it genuinely missing?

**Comment by Micket** [comment]
> Do I need to rebuild something to pick up this dep

Yes
https://github.com/easybuilders/easybuild-easyconfigs/pull/17779

**Comment by verdurin** [comment]
Test report by @verdurin
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
easybuild-c7.novalocal - Linux CentOS Linux 7.9.2009, x86_64, Intel Xeon Processor (Skylake, IBRS), Python 3.6.8
See https://gist.github.com/verdurin/2276ab67664f5598ad97dfb55b144646 for a full test report.

**Comment by verdurin** [comment]
@boegelbot please test @ jsc-zen2

**Comment by akesandgren** [comment]
Test report by @akesandgren
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
b-cn1603.hpc2n.umu.se - Linux Ubuntu 22.04, x86_64, AMD EPYC 7313 16-Core Processor, 1 x NVIDIA NVIDIA A100 80GB PCIe, 525.105.17, Python 3.10.6
See https://gist.github.com/akesandgren/d3988c1882bdd96e260a1833bbf461a8 for a full test report.

**Review by akesandgren — APPROVED** [review]
LGTM

**Comment by akesandgren** [comment]
Going in, thanks @Micket!

**Pull request merged**
