### PR TITLE
{data}[GCCcore/13.3.0] XML-Parser v2.47 w/ Perl 5.38.2

### PR DESCRIPTION
**Pull request by maxim-masterov**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by maxim-masterov** [comment]
Test report by @maxim-masterov
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
tcn482.local.snellius.surf.nl - Linux RHEL 9.4, x86_64, AMD EPYC 7H12 64-Core Processor, Python 3.9.18
See https://gist.github.com/maxim-masterov/c1eecefadc3d1dcf46641a57bdcf77e9 for a full test report.

**Comment by smoors** [comment]
@boegelbot: please test @ generoso

**Review by smoors — APPROVED** [review]
lgtm

**Comment by smoors** [comment]
Going in, thanks @maxim-masterov!

**Pull request merged**
