### PR TITLE
add Perl build dependency to recent Clang easyconfigs

### LINKED ISSUE #13734: Clang 10.0.1 (2020a) building stage fails due to missing perl libarary
Whilst building TRIQS, as supplied in this repo, in a fresh CentOS 7.9 environment Clang failed with:

```
Can't locate Data/Dumper.pm in @INC
```

Missing build dependency on Perl?  (This module is provided by Perl-5.30.2-GCCcore-9.3.0 in my EB environment but Clang does not list Perl as a dep/builddep).

### PR DESCRIPTION
**Pull request by boegel**
(created using `eb --new-pr`)
fixes #13734

### CODE REVIEW

**Comment by boegel** [comment]
@boegelbot please test @ generoso
CORE_CNT=16

**Comment by branfosj** [comment]
The five that failed all failed with:
```
 Can't build Clang with CUDA support without specifying 'cuda-compute-capabilities' (at easybuild/easybuild-easyblocks/easybuild/easyblocks/c/clang.py:327 in configure_step)
```

I understand that for `Clang-11.0.1-gcccuda-2020b.eb`, `Clang-8.0.1-GCC-8.3.0-CUDA-10.1.243.eb`, and `Clang-9.0.1-GCC-8.3.0-CUDA-10.1.243.eb`.

I do not understand that for `Clang-12.0.1-GCCcore-10.3.0.eb` and `Clang-9.0.1-GCCcore-8.3.0.eb` and I cannot reproduce this error locally.

**Comment by boegel** [comment]
@branfosj I see this in the build log for `Clang-12.0.1-GCCcore-10.3.0.eb`:

```
== 2021-08-14 16:09:36,408 clang.py:202 DEBUG Using ['X86', 'NVPTX'] as default build targets for CPU/GPU architecture x86_64.
```

But that can only occur when `$EBROOTCUDA` is set... 🤔 

The only way I see that happening is if the build environment from the previous (failed) build of `Clang-11.0.1-gcccuda-2020b.eb` is leaking in...

**Comment by boegel** [comment]
```
$ eb --from-pr 13746 Clang-11.0.1-gcccuda-2020b.eb Clang-12.0.1-GCCcore-10.3.0.eb -f --installpath /tmp/$USER --debug --dump-test-report
...
== Build succeeded for 0 out of 2


$ egrep "processing EasyBuild easyconfig|Resetting|default build targets|FAILED.*build failed|EBROOTCUDA" /tmp/eb-z9wh3ure/easybuild-oxfdi6k7.log
== 2021-08-18 12:13:32,895 build_log.py:265 INFO processing EasyBuild easyconfig /tmp/eb-z9wh3ure/files_pr13746/c/Clang/Clang-11.0.1-gcccuda-2020b.eb
== 2021-08-18 12:13:32,896 easyblock.py:3649 INFO Resetting environment
os.environ["EBROOTCUDA"] = "/users/boegelbot/CentOS8/haswell/software/CUDAcore/11.1.1";
os.environ["EBROOTCUDACORE"] = "/users/boegelbot/CentOS8/haswell/software/CUDAcore/11.1.1";
== 2021-08-18 12:13:52,643 clang.py:202 DEBUG Using ['X86', 'NVPTX'] as default build targets for CPU/GPU architecture x86_64.
== 2021-08-18 12:13:52,711 build_log.py:265 INFO FAILED: Installation ended unsuccessfully (build directory: /tmp/boegelbot/Clang/11.0.1/gcccuda-2020b): build failed (first 300 chars): Can't build Clang with CUDA support without specifying 'cuda-compute-capabilities' (took 19 secs)
== 2021-08-18 12:13:52,713 build_log.py:265 INFO processing EasyBuild easyconfig /tmp/eb-z9wh3ure/files_pr13746/c/Clang/Clang-12.0.1-GCCcore-10.3.0.eb
== 2021-08-18 12:13:52,713 easyblock.py:3649 INFO Resetting environment
== 2021-08-18 12:13:52,716 environment.py:170 DEBUG Key in old environment found that is not in new one: EBROOTCUDA (/users/boegelbot/CentOS8/haswell/software/CUDAcore/11.1.1)
== 2021-08-18 12:13:52,716 environment.py:170 DEBUG Key in old environment found that is not in new one: EBROOTCUDACORE (/users/boegelbot/CentOS8/haswell/software/CUDAcore/11.1.1)
== 2021-08-18 12:14:10,608 clang.py:202 DEBUG Using ['X86', 'NVPTX'] as default build targets for CPU/GPU architecture x86_64.
== 2021-08-18 12:14:10,641 build_log.py:265 INFO FAILED: Installation ended unsuccessfully (build directory: /tmp/boegelbot/Clang/12.0.1/GCCcore-10.3.0): build failed (first 300 chars): Can't build Clang with CUDA support without specifying 'cuda-compute-capabilities' (took 17 secs)
```

So, the environment is properly reset, no leakage of a loaded `CUDA` module based on this...

**Comment by SebastianAchilles** [comment]
@boegelbot please test @ generoso
EB_ARGS="Clang-9.0.1-GCCcore-8.3.0.eb Clang-10.0.0-GCCcore-8.3.0.eb Clang-10.0.0-GCCcore-9.3.0.eb Clang-10.0.1-GCCcore-9.3.0.eb Clang-11.0.0-GCCcore-9.3.0.eb Clang-11.0.1-GCCcore-10.2.0.eb Clang-12.0.1-GCCcore-10.3.0.eb"
CORE_CNT=16

**Comment by SebastianAchilles** [comment]
@boegelbot please test @ generoso
EB_ARGS="--cuda-compute-capabilities 7.0 Clang-8.0.1-GCC-8.3.0-CUDA-10.1.243.eb Clang-9.0.1-GCC-8.3.0-CUDA-10.1.243.eb Clang-11.0.1-gcccuda-2020b.eb"
CORE_CNT=16

**Comment by SebastianAchilles** [comment]
Test report by @sebastianachilles
**SUCCESS**
Build succeeded for 5 out of 5 (5 easyconfigs in total)
rocky8-eb - Linux rocky linux 8.4, x86_64, Intel(R) Core(TM) i7-6900K CPU @ 3.20GHz (broadwell), Python 3.6.8
See https://gist.github.com/beab8b5c4f1283b26f82c1574b4f911f for a full test report.

**Comment by SebastianAchilles** [comment]
@boegelbot please test @ generoso
EB_ARGS="Clang-9.0.1-GCCcore-8.3.0.eb Clang-10.0.0-GCCcore-8.3.0.eb Clang-10.0.0-GCCcore-9.3.0.eb Clang-10.0.1-GCCcore-9.3.0.eb Clang-11.0.0-GCCcore-9.3.0.eb Clang-11.0.1-GCCcore-10.2.0.eb Clang-12.0.1-GCCcore-10.3.0.eb"
CORE_CNT=16

**Comment by boegel** [comment]
Test report by @boegel
**FAILED**
Build succeeded for 8 out of 10 (10 easyconfigs in total)
node3132.skitty.os - Linux centos linux 7.9.2009, x86_64, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz, Python 3.6.8
See https://gist.github.com/61e1f6d71abeab4735e557fd19aa6ce4 for a full test report.

**Comment by boegel** [comment]
@boegelbot please test @ generoso
EB_ARGS="--include-easyblocks-from-pr 2556 Clang-11.0.1-gcccuda-2020b.eb Clang-12.0.1-GCCcore-10.3.0.eb Clang-8.0.1-GCC-8.3.0-CUDA-10.1.243.eb"

**Review by branfosj — APPROVED** [review]
lgtm

**Comment by boegel** [comment]
Note: the requested test build on `generoso` are going to fail, because `--cuda-compute-capabilities` is not specified, but the installation of `Clang-12.0.1-GCCcore-10.3.0.eb` should work now than to the fix in https://github.com/easybuilders/easybuild-easyblocks/pull/2556 (while it failed earlier after a failing Clang installation that included CUDA).

A full test report for all 10 easyconfigs is also coming up, but that will take a while (~10h)

**Comment by boegel** [comment]
Test report by @boegel
Using easyblocks from PR(s) https://github.com/easybuilders/easybuild-easyblocks/pull/2556
**SUCCESS**
Build succeeded for 10 out of 10 (10 easyconfigs in total)
node3108.skitty.os - Linux centos linux 7.9.2009, x86_64, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz, Python 3.6.8
See https://gist.github.com/324b0a6d00513d1f3da814d6801bff06 for a full test report.

**Comment by branfosj** [comment]
Going in, thanks @boegel!

**Comment by branfosj** [comment]
@boegelbot please test @ generoso
EB_ARGS="--cuda-compute-capabilities 7.0 Clang-11.0.1-gcccuda-2020b.eb Clang-8.0.1-GCC-8.3.0-CUDA-10.1.243.eb Clang-9.0.1-GCC-8.3.0-CUDA-10.1.243.eb "
CORE_CNT=16

**Pull request merged**
