### PR TITLE
{lib}[SYSTEM] ffnvcodec v11.1.5.2 + add it as dependency in FFmpeg 5.0.1

### PR DESCRIPTION
**Pull request by Micket**
(created using `eb --new-pr`)

I also need to test this as an optional dependency to ffmpeg.

### CODE REVIEW

**Comment by Micket** [comment]
I wasn't sure if to call this ffnvcodec or nv-codec-headers.

**Comment by Micket** [comment]
Test report by @Micket
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
vera-c2 - Linux Rocky Linux 8.6, x86_64, Intel Xeon Processor (Skylake), Python 3.6.8
See https://gist.github.com/37cac73034b94eceda85511bece60c3d for a full test report.

**Comment by Micket** [comment]
So, ffnvcodec are just headers, and ffmpeg should do runtime checks. I think this will just build FFmpeg with support for nvenc, similar to how we do with OpenMPI's cuda support.
There is basically minimal impact (except for a few seconds of build time?) for those who don't have nvidia GPUs.

It doesn't seem to care about CUDA runtime either, the actual codec libraries are part of the drivers. So, that's great. No need to make CUDA suffix variants of FFmpeg for this feature i think. 

But it needs to be tested to ensure it has no negative impact on systems without nvidia gpus (or drivers)

**Comment by Micket** [comment]
Test report by @Micket
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in total)
vera-c2 - Linux Rocky Linux 8.6, x86_64, Intel Xeon Processor (Skylake), Python 3.6.8
See https://gist.github.com/bdfd05ed7ec3c622c01a9862bb78166c for a full test report.

**Comment by zao** [comment]
Test report by @zao
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in total)
eb-rocky8 - Linux Rocky Linux 8.6, x86_64, AMD Ryzen 9 3900X 12-Core Processor, Python 3.9.7
See https://gist.github.com/e29910a21cd90a279645bc9d7a9aae97 for a full test report.

**Comment by Micket** [comment]
Test report by @Micket
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in total)
vera-c2 - Linux Rocky Linux 8.6, x86_64, Intel Xeon Processor (Skylake), Python 3.6.8
See https://gist.github.com/dc59ef0f865da9df3c6f6b8341351199 for a full test report.

**Comment by Micket** [comment]
Tested to confirm that it builds fine even if you lack cuda and gpu (and such a build will work at runtime from a machine with nvidia gpu). We should be able to apply this to all FFmpegs going forward.

I'm not sure how to interpret the different versions of ffnvcodec though, or what the compatibility with nvidia drivers and/or FFmpeg is.

**Comment by Micket** [comment]
@boegelbot please test @ generoso

**Review by boegel — APPROVED** [review]
lgtm

**Comment by boegel** [comment]
@boegelbot please test @ generoso

**Comment by boegel** [comment]
@boegelbot please test @ jsc-zen2

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in total)
node3158.skitty.os - Linux RHEL 8.6, x86_64, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz (skylake_avx512), Python 3.6.8
See https://gist.github.com/924b7608faf1ad3eb3627db3479c8239 for a full test report.

**Pull request merged**
