### PR TITLE
{perf}[gompi/2023b] Score-P v8.4 w/ CUDA 12.4.0

### PR DESCRIPTION
**Pull request by Flamefire**
(created using `eb --new-pr`)

Requires:
- [x]  https://github.com/easybuilders/easybuild-easyconfigs/pull/19832
- [x] https://github.com/easybuilders/easybuild-easyconfigs/pull/20107

If the build fails with

> configure: WARNING: nvcc -ccbin mpicxx compilation failed. Disabling CUDA support.

the cause is very likely a missing `include-fixed` folder for GCC 13, see https://github.com/easybuilders/easybuild-easyblocks/pull/3254. So either rename the include-fixed folder renamed by easybuild or regenerate it with `$EBROOTGCC/libexec/gcc/x86_64-pc-linux-gnu/13.2.0/install-tools/mkheaders`

### CODE REVIEW

**Comment by Thyre** [comment]
Score-P v8.4 has released with SHA256: 7bbde9a0721d27cc6205baf13c1626833bcfbabb1f33b325a2d67976290f7f8a

**Comment by Flamefire** [comment]
Test report by @Flamefire
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
i8001 - Linux Rocky Linux 8.7 (Green Obsidian), x86_64, AMD EPYC 7352 24-Core Processor (zen2), 8 x NVIDIA NVIDIA A100-SXM4-40GB, 545.23.08, Python 3.8.13
See https://gist.github.com/Flamefire/573cc81749d2902ccbfc4f4d7a74d5e0 for a full test report.

**Comment by Flamefire** [comment]
Test report by @Flamefire
**FAILED**
Build succeeded for 0 out of 2 (1 easyconfigs in total)
i8001 - Linux Rocky Linux 8.7 (Green Obsidian), x86_64, AMD EPYC 7352 24-Core Processor (zen2), 8 x NVIDIA NVIDIA A100-SXM4-40GB, 545.23.08, Python 3.8.13
See https://gist.github.com/Flamefire/4b9cfb6b0c5001cf5d04fb4edca03bec for a full test report.

**Comment by Flamefire** [comment]
Test report by @Flamefire
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
i8001 - Linux Rocky Linux 8.7 (Green Obsidian), x86_64, AMD EPYC 7352 24-Core Processor (zen2), 8 x NVIDIA NVIDIA A100-SXM4-40GB, 545.23.08, Python 3.8.13
See https://gist.github.com/Flamefire/ba67de400919dc6a6e38f3aa0bc5f1a8 for a full test report.

**Comment by casparvl** [comment]
Test report by @casparvl
**FAILED**
Build succeeded for 2 out of 3 (1 easyconfigs in total)
tcn1.local.snellius.surf.nl - Linux RHEL 8.6, x86_64, AMD EPYC 7H12 64-Core Processor, Python 3.6.8
See https://gist.github.com/casparvl/4d88c97cb88fbb32e1a7367e1217f513 for a full test report.

**Comment by casparvl** [comment]
Hm, not sure if this needs an actual GPU node, I'll try rebuilding on one...

**Comment by casparvl** [comment]
Test report by @casparvl
**FAILED**
Build succeeded for 0 out of 1 (1 easyconfigs in total)
gcn6.local.snellius.surf.nl - Linux RHEL 8.6, x86_64, Intel(R) Xeon(R) Platinum 8360Y CPU @ 2.40GHz, 4 x NVIDIA NVIDIA A100-SXM4-40GB, 545.23.08, Python 3.6.8
See https://gist.github.com/casparvl/d931df82a4b888163a7213f45718577d for a full test report.

**Comment by Thyre** [comment]
> Hm, not sure if this needs an actual GPU node, I'll try rebuilding on one...

Score-P shouldn't require any GPU being present when building. From the logs, it looks like `nvcc -ccbin mpicxx` failed. 

```
configure: WARNING: nvcc -ccbin mpicxx compilation failed. Disabling CUDA support.
configure: error: could not fulfill requested support for CUDA.
configure: error: ./configure failed for build-mpi
```

Unfortunately, I cannot say what exactly did go wrong without looking at `build-mpi/config.log`. The provided configure options look reasonable.

**Comment by Flamefire** [comment]
No the issue is a "broken" GCC installation: GCC13 is just compatible with CUDA and requires fixed includes. I added that information to the description.

**Comment by Thyre** [comment]
This makes sense, since OpenMPI is built with GCC 13. `configure` would probably fail without MPI later on as well when checking CUDA just with the backend compiler.

**Comment by casparvl** [comment]
Ah clear, thanks. Ok... I'll get back to this tomorrow :)

**Comment by casparvl** [comment]
Test report by @casparvl
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
tcn1.local.snellius.surf.nl - Linux RHEL 8.6, x86_64, AMD EPYC 7H12 64-Core Processor, Python 3.6.8
See https://gist.github.com/casparvl/4cc37e81a7cff0519f70ac45f933647c for a full test report.

**Review by casparvl — APPROVED** [review]
Lgtm!

**Comment by casparvl** [comment]
Going in, thanks @Flamefire!

**Comment by Flamefire** [comment]
> UCX-CUDA for the 2023b toolchain contains CUDA 12.3.0 as a dependency. Any reasons for not using that here and using 12.4.0?

Because CUDA 12.3.0 does not support GCC 13. That EC should be removed.

**Comment by Flamefire** [comment]
@casparvl Can you also take a look at the related PR #19524

**Pull request merged**
