### PR TITLE
{bio,lib}[GCCcore/8.3.0,foss/2019b] nifti2dicom v0.4.11, TCLAP v1.2.2

### PR DESCRIPTION
**Pull request by crubb**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by crubb** [comment]
Test report by @crubb
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in this PR)
radbert - Linux ubuntu 18.04, Intel(R) Xeon(R) CPU E5-2687W v4 @ 3.00GHz, Python 2.7.17
See https://gist.github.com/384f30b7f4a0025ea7f19d61884971ef for a full test report.

**Comment by verdurin** [comment]
Test report by @verdurin
**FAILED**
Build succeeded for 2 out of 3 (2 easyconfigs in this PR)
easybuild.novalocal - Linux centos linux 7.8.2003, Intel Xeon Processor (Skylake, IBRS), Python 2.7.5
See https://gist.github.com/d92944fd1fe4ef6e4d02e2d59ab10a23 for a full test report.

**Comment by Micket** [comment]
Test report by @Micket
**FAILED**
Build succeeded for 1 out of 2 (2 easyconfigs in this PR)
hebbe-c1 - Linux centos linux 7.7.1908, Intel Core Processor (Haswell, no TSX), Python 2.7.5
See https://gist.github.com/37eb7a44813d65738f9f2d7c2e48c954 for a full test report.

**Comment by Micket** [comment]
I think this needs a configure flag to zlib. It ends up trying to link to system zlib for me.

**Comment by crubb** [comment]
Hey @verdurin, @Micket,

thanks for testing! In both failed builds this is related to `libpng`:

`/apps/Hebbe7/software/Compiler/GCCcore/8.3.0/libpng/1.6.37/lib/libpng.so: error: undefined reference to 'inflateValidate', version 'ZLIB_1.2.9'`

and

`/eb/maint/software/libpng/1.6.37-GCCcore-8.3.0/lib/libpng.so: error: undefined reference to 'inflateValidate', version 'ZLIB_1.2.9'`

Per https://github.com/easybuilders/easybuild-easyconfigs/issues/5033 I added `zlib/1.2.11` as dependency for `nifti2dicom`. Can you check? Thanks!

Best,
crubb

**Comment by crubb** [comment]
Test report by @crubb
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in this PR)
radbert - Linux ubuntu 18.04, Intel(R) Xeon(R) CPU E5-2687W v4 @ 3.00GHz, Python 2.7.17
See https://gist.github.com/7179c1b5abfbcd4366def5afe332e9d3 for a full test report.

**Comment by Micket** [comment]
Test report by @Micket
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in this PR)
hebbe-c1 - Linux centos linux 7.7.1908, Intel Core Processor (Haswell, no TSX), Python 2.7.5
See https://gist.github.com/992d62168c5e45b6f598eab23683a609 for a full test report.

**Comment by Micket** [comment]
Going in, thanks @crubb!

**Pull request merged**
