### PR TITLE
{bio}[intel/2018b] RNAmmer v1.2 w/ Perl 5.28.0

### PR DESCRIPTION
**Pull request by boegel**
(created using `eb --new-pr`)

requires ~~https://github.com/easybuilders/easybuild-framework/pull/2686~~ (but only if `compress` is not installed) + ~~#7279~~ (HMMER)

### CODE REVIEW

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in this PR)
node2086.delcatty.os - Linux centos linux 7.5.1804, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.7.5
See https://gist.github.com/01732bc6d43790ec5e904d757ee2b611 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in this PR)
node3120.skitty.os - Linux centos linux 7.5.1804, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz, Python 2.7.5
See https://gist.github.com/8818b6727e26a49d56cb6dbd05ba0073 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in this PR)
node2082.delcatty.os - Linux centos linux 7.5.1804, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.7.5
See https://gist.github.com/92bfd8a9889b45d71e1886ea60293e03 for a full test report.

**Comment by boegel** [comment]
fleshed out HMMER to #7279

**Comment by akesandgren** [comment]
@boegel The new fix-bang stuff should be usable here right?

**Comment by casparvl** [comment]
Test report by @casparvl
**FAILED**
Build succeeded for 2 out of 3 (1 easyconfigs in total)
tcn900.bullx - Linux RHEL 7.8, x86_64, Intel(R) Xeon(R) CPU E5-2690 v3 @ 2.60GHz, Python 2.7.5
See https://gist.github.com/0e61167b2a3fe3742ef5b7463b7e259f for a full test report.

**Comment by casparvl** [comment]
Test report by @casparvl
**FAILED**
Build succeeded for 0 out of 1 (1 easyconfigs in total)
tcn900.bullx - Linux RHEL 7.8, x86_64, Intel(R) Xeon(R) CPU E5-2690 v3 @ 2.60GHz, Python 2.7.5
See https://gist.github.com/1cb46a9b240459b333a67c121c0826cd for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
node3409.kirlia.os - Linux centos linux 7.9.2009, x86_64, Intel(R) Xeon(R) Gold 6240 CPU @ 2.60GHz (cascadelake), Python 3.6.8
See https://gist.github.com/8515d355f688e6ffb431a95a770085cb for a full test report.

**Comment by branfosj** [comment]
Latest download gets `rnammer-1.2.src.tar.gz` and the .tar.Z does not seem to be available.

Checksum is `7bef4565370923a8356f655a3e2c33ab47097579a90c025f2f7c44b91737892e`

**Comment by branfosj** [comment]
Test report by @branfosj
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
bear-pg0211u03a.bear.cluster - Linux centos linux 7.8.2003, x86_64, Intel(R) Xeon(R) Gold 6248 CPU @ 2.50GHz (cascadelake), Python 3.6.8
See https://gist.github.com/7a1927c68876f0ce77bccc549aa16aa9 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
node3409.kirlia.os - Linux centos linux 7.9.2009, x86_64, Intel(R) Xeon(R) Gold 6240 CPU @ 2.60GHz (cascadelake), Python 3.6.8
See https://gist.github.com/0d528ed1c7726d025f3b08b97407f981 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
node2707.swalot.os - Linux centos linux 7.9.2009, x86_64, Intel(R) Xeon(R) CPU E5-2660 v3 @ 2.60GHz (haswell), Python 3.6.8
See https://gist.github.com/cb69c09cf8bcaa6962ebf47bd7de74b0 for a full test report.

**Comment by casparvl** [comment]
Well, if that ain't enough green checkmarks, I don't know what is. Going in! Thanks @boegel !

**Review by casparvl — APPROVED** [review]
Fixed all issues there were to fix already 👍

**Pull request merged**
