### PR TITLE
{bio}[GCCcore/10.3.0] tabix v0.2.6

### PR DESCRIPTION
**Pull request by pberthier**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by pberthier** [comment]
Test report by @pberthier
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
softdev8.ibu.internal - Linux Rocky Linux 8.8 (Green Obsidian), x86_64, AMD EPYC 7742 64-Core Processor, Python 3.11.2
See https://gist.github.com/pberthier/7d91f4086ccd34ab30e60845fcef0c5e for a full test report.

**Comment by branfosj** [comment]
@boegelbot please test @ generoso

**Comment by branfosj** [comment]
Test report by @branfosj
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
bear-pg0105u03a.bear.cluster - Linux RHEL 8.6, x86_64, Intel(R) Xeon(R) Platinum 8360Y CPU @ 2.40GHz (icelake), Python 3.6.8
See https://gist.github.com/branfosj/f0c166c5bd4807f8b5afdc833e2f37ea for a full test report.

**Comment by branfosj** [comment]
@boegelbot please test @ jsc-zen2

**Review by branfosj — APPROVED** [review]

**Comment by branfosj** [comment]
Going in, thanks @pberthier!

**Pull request merged**
