### PR TITLE
{numlib}[foss/2018b] Armadillo v9.600.5

### PR DESCRIPTION
**Pull request by tstrempel**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by tstrempel** [comment]
The patch is needed, because if you have mkl installed in /opt or a standard location, mkl will be chosen above OpenBLAS.

**Comment by smoors** [comment]
@tstrempel is this patch needed for the more recent versions as well?
Armadillo-9.700.2-foss-2019a.eb, Armadillo-9.880.1-foss-2020a.eb

if so, would you mind updating those easyconfigs as well?

**Comment by tstrempel** [comment]
@smoors Yes, it is needed. I'll also provide a version for 2019b. I just didn't want to commit the same path file 4 times as I didn't know how this would be handeled.
Is it allowed to commit multiple EasyConfigs in one pull request?

**Comment by smoors** [comment]
> Is it allowed to commit multiple EasyConfigs in one pull request?

yes, you can upload multiple easyconfigs in one PR, although it's a good idea to limit the number of easyconfigs to max 10 to ease the review process.

**Comment by smoors** [comment]
@tstrempel protip: it looks like you are manually updating the checksums?
that's not needed, you can let EB do it for you:
```
eb --inject-checksums --force Armadillo-9.880.1-foss-2020a.eb
```

**Comment by smoors** [comment]
Test report by @smoors
**SUCCESS**
Build succeeded for 8 out of 8 (4 easyconfigs in this PR)
node358.hydra.os - Linux centos linux 7.7.1908, x86_64, Intel(R) Xeon(R) Gold 6148 CPU @ 2.40GHz (skylake_avx512), Python 2.7.5
See https://gist.github.com/d6e185c32515dec8aa7ba1e3ee98e7f1 for a full test report.

**Comment by smoors** [comment]
Going in, thanks @tstrempel!

**Pull request merged**
