### PR TITLE
{lib}[foss/2021a] PyTorch-Geometric v2.1.0 w/ Python 3.9.5

### PR DESCRIPTION
**Pull request by Micket**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by Micket** [comment]
Test report by @Micket
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
alvis3-04 - Linux Rocky Linux 8.5, x86_64, Intel(R) Xeon(R) Gold 6338 CPU @ 2.00GHz, 4 x NVIDIA NVIDIA A100-SXM4-40GB, 510.73.08, Python 3.6.8
See https://gist.github.com/9193fd5107757781f9463b6d908c468a for a full test report.

**Comment by Micket** [comment]
Test report by @Micket
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
alvis2-11 - Linux Rocky Linux 8.5, x86_64, Intel(R) Xeon(R) Gold 6226R CPU @ 2.90GHz, 8 x NVIDIA Tesla T4, 520.61.05, Python 3.6.8
See https://gist.github.com/2acb6ced3c24b191d60b4a9d01ead785 for a full test report.

**Review by branfosj — APPROVED** [review]

**Comment by branfosj** [comment]
Test report by @branfosj
**SUCCESS**
Build succeeded for 5 out of 5 (1 easyconfigs in total)
bear-pg0103u14a.bear.cluster - Linux RHEL 8.5, x86_64, Intel(R) Xeon(R) Gold 6330 CPU @ 2.00GHz (icelake), 1 x NVIDIA NVIDIA A30, 470.57.02, Python 3.6.8
See https://gist.github.com/3c2cb5be52c9c37e95148f87ec455479 for a full test report.

**Comment by branfosj** [comment]
Going in, thanks @Micket!

**Pull request merged**
