### PR TITLE
use new DualSPHysics easyblock

### PR DESCRIPTION
**Pull request by jfgrimm**
requires:
- [x] https://github.com/easybuilders/easybuild-easyblocks/pull/3050

When building with EasyBuild configured to use rpath, the sanity checks for the existing easyconfig fail because some prebuilt binaries and libraries are bundled in the tarball, and these don't have an RPATH section. The new easyblock runs `patchelf` to add a corresponding entry.

(created using `eb --new-pr`)

### CODE REVIEW

**Comment by jfgrimm** [comment]
Test report by @jfgrimm
Using easyblocks from PR(s) https://github.com/easybuilders/easybuild-easyblocks/pull/3050
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
node030.viking2.yor.alces.network - Linux Rocky Linux 8.8, x86_64, AMD EPYC 7643 48-Core Processor, Python 3.6.8
See https://gist.github.com/jfgrimm/854a04c4dfaf6e552abd9334c677388b for a full test report.

**Comment by jfgrimm** [comment]
Test report by @jfgrimm
Using easyblocks from PR(s) https://github.com/easybuilders/easybuild-easyblocks/pull/3050
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
node099.viking2.yor.alces.network - Linux Rocky Linux 8.8, x86_64, AMD EPYC 7643 48-Core Processor, Python 3.6.8
See https://gist.github.com/jfgrimm/44b940c660ae2a387e618962409e7c9e for a full test report.

**Comment by akesandgren** [comment]
@boegelbot Please test @ generoso

**Comment by akesandgren** [comment]
@boegelbot please test @ jsc_zen2
EB_ARGS='--rpath'

**Comment by akesandgren** [comment]
@boegelbot Please test @ generoso

**Comment by akesandgren** [comment]
@boegelbot Please test @ generoso
EB_ARGS='--rpath --rebuild'

**Review by akesandgren — APPROVED** [review]
LGTM

**Comment by akesandgren** [comment]
Going in, thanks @jfgrimm!

**Pull request merged**
