### PR TITLE
{bio}[foss/2019b] medaka v1.1.1, edlib v1.3.8.post1, Pysam v0.16.0.1 w/ Python 2.7.16 + 3.7.4

### PR DESCRIPTION
**Pull request by boegel**
(created using `eb --new-pr`)
requires ~~#11438~~ (pyspoa)

### CODE REVIEW

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 3 out of 3 (3 easyconfigs in this PR)
node3404.kirlia.os - Linux centos linux 7.8.2003, x86_64, Intel(R) Xeon(R) Gold 6240 CPU @ 2.60GHz (cascadelake), Python 2.7.5
See https://gist.github.com/7af721122f69c7c3cd7ddfd95547b74b for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 3 out of 3 (3 easyconfigs in this PR)
node3139.skitty.os - Linux centos linux 7.8.2003, x86_64, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz, Python 3.6.8
See https://gist.github.com/d60a973f1435bc81709e9ebde62d0d17 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 3 out of 3 (3 easyconfigs in this PR)
node2611.swalot.os - Linux centos linux 7.8.2003, x86_64, Intel(R) Xeon(R) CPU E5-2660 v3 @ 2.60GHz (haswell), Python 2.7.5
See https://gist.github.com/a4e277ebd81752460fc97b2230042d27 for a full test report.

**Comment by verdurin** [comment]
Test report by @verdurin
**SUCCESS**
Build succeeded for 3 out of 3 (3 easyconfigs in this PR)
easybuild.novalocal - Linux centos linux 7.8.2003, x86_64, Intel Xeon Processor (Skylake, IBRS), Python 2.7.5
See https://gist.github.com/cc967b2e47bd2be6ef7e16e26a166d48 for a full test report.

**Comment by verdurin** [comment]
Test report by @verdurin
**FAILED**
Build succeeded for 11 out of 13 (3 easyconfigs in this PR)
nuc.lan - Linux Fedora 32, x86_64, Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz, Python 3.8.5
See https://gist.github.com/a49041fff2765d2f53e5f0c9d3997e09 for a full test report.

**Comment by boegel** [comment]
@verdurin Problem during installation of `TensorFlow` 2.2.0 (a dep of `medaka`):
```
ERROR: An error occurred during the fetch of repository 'fft2d':
   java.io.IOException: thread interrupted
```

Try again?

**Comment by verdurin** [comment]
Test report by @verdurin
**FAILED**
Build succeeded for 1 out of 2 (3 easyconfigs in this PR)
nuc.lan - Linux Fedora 32, x86_64, Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz, Python 3.8.5
See https://gist.github.com/5f9720976286ac4ffddd1654731b5673 for a full test report.

**Comment by zao** [comment]
Test report by @zao
**SUCCESS**
Build succeeded for 3 out of 3 (3 easyconfigs in this PR)
freja - Linux Ubuntu 20.04, x86_64, Intel(R) Core(TM) i7-8700K CPU @ 3.70GHz, Python 3.8.5
See https://gist.github.com/ecbbc6b474a9c5e6a002d1445dc0641f for a full test report.

**Comment by verdurin** [comment]
Missing autotools deps?:
```
Unable to find parasail configure script
  Prepending /usr/bin to PATH
    Running autoreconf -fi from ./parasail-master
  b'This is perl 5, version 30, subversion 3 (v5.30.3) built for x86_64-linux-thread-multi'
  b'm4 (GNU M4) 1.4.18'
  autoconf not found
  automake not found
  libtoolize not found
  autoreconf not found
  Prepending /tmp/eb-i4n45vmp/pip-req-build-y6xtapj2/autotools/bin to PATH
 <snip>
  Building autotools
  Downloading http://ftp.gnu.org/gnu/m4/m4-1.4.17.tar.gz
  Expanding m4-1.4.17.tar.gz
  configuring m4
  making and installing m4
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/tmp/eb-i4n45vmp/pip-req-build-y6xtapj2/setup.py", line 463, in <module>
      install_requires=INSTALL_REQUIRES,
    File "/mnt/ds918plus/eb/nuc-fedora32/software/Python/3.7.4-GCCcore-8.3.0/lib/python3.7/site-packages/setuptools/__init__.py", line 145, in setup
      return distutils.core.setup(**attrs)
    File "/mnt/ds918plus/eb/nuc-fedora32/software/Python/3.7.4-GCCcore-8.3.0/lib/python3.7/distutils/core.py", line 148, in setup
      dist.run_commands()
    File "/mnt/ds918plus/eb/nuc-fedora32/software/Python/3.7.4-GCCcore-8.3.0/lib/python3.7/distutils/dist.py", line 966, in run_commands
      self.run_command(cmd)
    File "/mnt/ds918plus/eb/nuc-fedora32/software/Python/3.7.4-GCCcore-8.3.0/lib/python3.7/distutils/dist.py", line 985, in run_command
      cmd_obj.run()
    File "/tmp/eb-i4n45vmp/pip-req-build-y6xtapj2/setup.py", line 425, in run
      prepare_shared_lib()
    File "/tmp/eb-i4n45vmp/pip-req-build-y6xtapj2/setup.py", line 419, in prepare_shared_lib
      build_parasail(libname)
    File "/tmp/eb-i4n45vmp/pip-req-build-y6xtapj2/setup.py", line 306, in build_parasail
      build_autotools()
    File "/tmp/eb-i4n45vmp/pip-req-build-y6xtapj2/setup.py", line 247, in build_autotools
      raise RuntimeError("make of {} failed".format(tool))
  RuntimeError: make of m4 failed
  Building wheel for parasail (setup.py): finished with status 'error'
  ERROR: Failed building wheel for parasail
  Running setup.py clean for parasail
  Running command /mnt/ds918plus/eb/nuc-fedora32/software/Python/3.7.4-GCCcore-8.3.0/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/eb-i4n45vmp/pip-req-build-y6xtapj2/setup.py'"'"'; __file__='"'"'/tmp/eb-i4n45vmp/pip-req-build-y6xtapj2/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' clean --all
  running clean
  'build/lib' does not exist -- can't clean it
  'build/bdist.linux-x86_64' does not exist -- can't clean it
  'build/scripts-3.7' does not exist -- can't clean it
Failed to build parasail
```

**Comment by boegel** [comment]
@verdurin Please re-test?

**Comment by verdurin** [comment]
Test report by @verdurin
**SUCCESS**
Build succeeded for 1 out of 1 (3 easyconfigs in this PR)
nuc.lan - Linux Fedora 32, x86_64, Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz, Python 3.8.5
See https://gist.github.com/d2032582a31e23b039e33517113cfacf for a full test report.

**Review by verdurin — APPROVED** [review]
Looks fine.

**Comment by verdurin** [comment]
Test failure, which seems to be unrelated to this PR:
```
ERROR: Build of /home/runner/work/easybuild-easyconfigs/easybuild-easyconfigs/easybuild/easyconfigs/m/M4/M4-1.4.18.eb failed (err: "build failed (first 300 chars): Unexpected error occurred when trying to download https://ftpmirror.gnu.org/gnu/m4/m4-1.4.18.tar.gz to /tmp/runner/8b1a7c2bc9cfce2067005fca449fef24929578ad/sources/m/M4/m4-1.4.18.tar.gz: hostname 'gnu.mirror.constant.com' doesn't match 'arch.mirror.constant.com'")
```

**Comment by boegel** [comment]
> Test failure, which seems to be unrelated to this PR:
> 
> ```
> ERROR: Build of /home/runner/work/easybuild-easyconfigs/easybuild-easyconfigs/easybuild/easyconfigs/m/M4/M4-1.4.18.eb failed (err: "build failed (first 300 chars): Unexpected error occurred when trying to download https://ftpmirror.gnu.org/gnu/m4/m4-1.4.18.tar.gz to /tmp/runner/8b1a7c2bc9cfce2067005fca449fef24929578ad/sources/m/M4/m4-1.4.18.tar.gz: hostname 'gnu.mirror.constant.com' doesn't match 'arch.mirror.constant.com'")
> ```

@verdurin That issue is now fixed via #11469

**Comment by verdurin** [comment]
Going in, thanks @boegel!

**Comment by verdurin** [comment]
Going in, thanks @boegel!

**Comment by verdurin** [comment]
Going in, thanks @boegel!

**Pull request merged**
