### PR TITLE
JupyterHub v4.0.2: replace SQLAlchemy extension with regular dependency

### PR DESCRIPTION
**Pull request by lexming**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by lexming** [comment]
@boegelbot: please test @ generoso

**Comment by lexming** [comment]
@boegelbot please test @ jsc-zen3

**Comment by verdurin** [comment]
@lexming is this just for consistency? Or is it fixing any bugs?

**Comment by lexming** [comment]
@verdurin just consistency and a bit of efficiency avoiding duplicate installations of the same software

**Review by smoors — APPROVED** [review]
lgtm

**Comment by smoors** [comment]
Going in, thanks @lexming!

**Comment by jfgrimm** [comment]
Test report by @jfgrimm
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
node017.viking2.yor.alces.network - Linux Rocky Linux 8.9, x86_64, AMD EPYC 7643 48-Core Processor, Python 3.6.8
See https://gist.github.com/jfgrimm/72f4247fe370b8c8e22dcf628cf159d1 for a full test report.

**Pull request merged**
