### PR TITLE
add patch to fix for libarchive to fix error reporting in tar

### PR DESCRIPTION
**Pull request by boegel**
This is more out of abundance of caution than anything else, there's a link here to the [XZ backdoor situation](https://boehs.org/node/everything-i-know-about-the-xz-backdoor)

### CODE REVIEW

**Comment by boegel** [comment]
@boegelbot please test @ generoso

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 5 out of 5 (5 easyconfigs in total)
node3125.skitty.os - Linux RHEL 8.8, x86_64, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz, Python 3.6.8
See https://gist.github.com/boegel/3dab4709f45741d72f3ca85e33834230 for a full test report.

**Review by jfgrimm — APPROVED** [review]

**Review by branfosj — APPROVED** [review]

**Comment by branfosj** [comment]
@boegelbot please test @ jsc-zen3

**Comment by branfosj** [comment]
Test report by @branfosj
**SUCCESS**
Build succeeded for 6 out of 6 (5 easyconfigs in total)
bear-pg0105u03a - Linux RHEL 8.6, x86_64, Intel(R) Xeon(R) Platinum 8360Y CPU @ 2.40GHz (icelake), Python 3.6.8
See https://gist.github.com/branfosj/c2e808f19ca54067730260dfe7161c1a for a full test report.

**Comment by branfosj** [comment]
@boegelbot please test @ jsc-zen3

**Comment by branfosj** [comment]
Going in, thanks @boegel!

**Pull request merged**
