### PR TITLE
replace src include path with installation dir for HDF5 (intel)

### PR DESCRIPTION
**Pull request by smoors**
(created using `eb --new-pr`)

intel version of #17469

### CODE REVIEW

**Comment by jfgrimm** [comment]
@boegelbot: please test @ jsc-zen2

**Comment by jfgrimm** [comment]
Test report by @jfgrimm
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
himem04.pri.viking.alces.network - Linux CentOS Linux 7.9.2009, x86_64, Intel(R) Xeon(R) Gold 6230 CPU @ 2.10GHz (cascadelake), Python 3.6.8
See https://gist.github.com/f6499fced7ff8d326b4d56aabec391e0 for a full test report.

**Review by jfgrimm — APPROVED** [review]
lgtm

**Comment by jfgrimm** [comment]
Going in, thanks @smoors!

**Comment by hattom** [comment]
Should this regex go into the EasyBlock in future?

**Comment by jfgrimm** [comment]
@hattom I believe it should be getting fixed upstream (see https://github.com/HDFGroup/hdf5/issues/2422)

**Pull request merged**
