### PR TITLE
{lang,vis}[GCCcore/13.2.0] Tk v8.6.13, Tkinter v3.11.5

### PR DESCRIPTION
**Pull request by Micket**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by Micket** [comment]
@boegelbot please test @ generoso

**Comment by Micket** [comment]
Test report by @Micket
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in total)
alvis-c1 - Linux Rocky Linux 8.8, x86_64, Intel Xeon Processor (Skylake), Python 3.6.8
See https://gist.github.com/Micket/60cbcf4b6af87c21fec4897ab0186934 for a full test report.

**Comment by Micket** [comment]
@boegelbot please test @ jsc-zen2

**Comment by verdurin** [comment]
Test report by @verdurin
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in total)
easybuild-c7.novalocal - Linux CentOS Linux 7.9.2009, x86_64, Intel Xeon Processor (Skylake, IBRS), Python 3.6.8
See https://gist.github.com/verdurin/ec722caf7436a06ec8ea6beda75255f7 for a full test report.

**Comment by boegel** [comment]
@SebastianAchilles X11 build failed for you on RHEL9 with:

```
/home/easybuild/.local/easybuild/software/gettext/0.22-GCCcore-13.2.0/bin/msgfmt: Cannot convert from "ISO-8859-1" to "UTF-8". msgfmt relies on iconv(). This version was built without iconv().
```

That's not related to this PR directly, so let's open an issue for that to follow up?

**Comment by SebastianAchilles** [comment]
> @SebastianAchilles X11 build failed for you on RHEL9 with:
> 
> ```
> /home/easybuild/.local/easybuild/software/gettext/0.22-GCCcore-13.2.0/bin/msgfmt: Cannot convert from "ISO-8859-1" to "UTF-8". msgfmt relies on iconv(). This version was built without iconv().
> ```
> 
> That's not related to this PR directly, so let's open an issue for that to follow up?

Yes, this should not block merging this PR. I will open an issue for this.

**Review by boegel — APPROVED** [review]
lgtm

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in total)
node3100.skitty.os - Linux RHEL 8.8, x86_64, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz (skylake_avx512), Python 3.6.8
See https://gist.github.com/boegel/cf183ffa7ced179d5d3fd1a3fa7327c2 for a full test report.

**Comment by boegel** [comment]
Going in, thanks @Micket!

**Pull request merged**
