### PR TITLE
{lib}[foss/2023a] flash-attention v2.6.3 w/ CUDA 12.1.1

### PR DESCRIPTION
**Pull request by pavelToman**
(created using `eb --new-pr`)
resolves https://github.com/vscentrum/vsc-software-stack/issues/258

requires: 
- https://github.com/easybuilders/easybuild-easyconfigs/pull/21184

### CODE REVIEW

**Comment by pavelToman** [comment]
@boegelbot please test @ generoso

**Comment by pavelToman** [comment]
@boegelbot please test @ jsc-zen3

**Comment by verdurin** [comment]
Test report by @verdurin
**FAILED**
Build succeeded for 27 out of 28 (1 easyconfigs in total)
easybuild-el8.cloud.in.bmrc.ox.ac.uk - Linux Rocky Linux 8.10, x86_64, Intel Xeon Processor (Skylake, IBRS), Python 3.6.8
See https://gist.github.com/verdurin/2fa5466554ae2a4e7b19e92c4b00aac2 for a full test report.

**Comment by verdurin** [comment]
```
Processing /dev/shm/flashattention/2.6.3/foss-2023a-CUDA-12.1.1/flashattention/flash-attention-2.6.3
  Preparing metadata (setup.py): started
  Running command python setup.py egg_info
  No CUDA runtime is found, using CUDA_HOME='/apps/eb/el8/upstream/software/CUDA/12.1.1'
  fatal: not a git repository (or any parent up to mount point /dev)
  Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
  /apps/eb/el8/upstream/software/Python/3.11.3-GCCcore-12.3.0/lib/python3.11/site-packages/setuptools/__init__.py:84: _DeprecatedInstaller: setuptools.installer and fetch_build_eggs are deprecated.
  !!

          ********************************************************************************
          Requirements should be satisfied by a PEP 517 installer.
          If you are using pip, you can try `pip install --use-pep517`.
          ********************************************************************************

  !!
    dist.fetch_build_eggs(dist.setup_requires)


  torch.__version__  = 2.1.2


  running egg_info
  creating /tmp/eb-lsqh835v/pip-pip-egg-info-cal0mavz/flash_attn.egg-info
  writing /tmp/eb-lsqh835v/pip-pip-egg-info-cal0mavz/flash_attn.egg-info/PKG-INFO
  writing dependency_links to /tmp/eb-lsqh835v/pip-pip-egg-info-cal0mavz/flash_attn.egg-info/dependency_links.txt
  writing requirements to /tmp/eb-lsqh835v/pip-pip-egg-info-cal0mavz/flash_attn.egg-info/requires.txt
  writing top-level names to /tmp/eb-lsqh835v/pip-pip-egg-info-cal0mavz/flash_attn.egg-info/top_level.txt
  writing manifest file '/tmp/eb-lsqh835v/pip-pip-egg-info-cal0mavz/flash_attn.egg-info/SOURCES.txt'
  listing git files failed - pretending there aren't any
  reading manifest file '/tmp/eb-lsqh835v/pip-pip-egg-info-cal0mavz/flash_attn.egg-info/SOURCES.txt'
  reading manifest template 'MANIFEST.in'
  warning: no files found matching '*.cu' under directory 'flash_attn'
  warning: no files found matching '*.h' under directory 'flash_attn'
  warning: no files found matching '*.cuh' under directory 'flash_attn'
  warning: no files found matching '*.cpp' under directory 'flash_attn'
  warning: no files found matching '*.hpp' under directory 'flash_attn'
  adding license file 'LICENSE'
  adding license file 'AUTHORS'
  writing manifest file '/tmp/eb-lsqh835v/pip-pip-egg-info-cal0mavz/flash_attn.egg-info/SOURCES.txt'
  Preparing metadata (setup.py): finished with status 'done'
  ```

**Comment by verdurin** [comment]
```
Building wheels for collected packages: flash-attn
  Building wheel for flash-attn (setup.py): started
  Running command python setup.py bdist_wheel
  No CUDA runtime is found, using CUDA_HOME='/apps/eb/el8/upstream/software/CUDA/12.1.1'
  fatal: not a git repository (or any parent up to mount point /dev)
  Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).


  torch.__version__  = 2.1.2


  /apps/eb/el8/upstream/software/Python/3.11.3-GCCcore-12.3.0/lib/python3.11/site-packages/setuptools/__init__.py:84: _DeprecatedInstaller: setuptools.installer and fetch_build_eggs are deprecated.
  !!

          ********************************************************************************
          Requirements should be satisfied by a PEP 517 installer.
          If you are using pip, you can try `pip install --use-pep517`.
          ********************************************************************************

  !!
    dist.fetch_build_eggs(dist.setup_requires)
  running bdist_wheel
  Guessing wheel URL:  https://github.com/Dao-AILab/flash-attention/releases/download/v2.6.3/flash_attn-2.6.3+cu123torch2.1cxx11abiTRUE-cp311-cp311-linux_x86_64.whl
  Raw wheel path /tmp/eb-lsqh835v/pip-wheel-teg_ahm9/flash_attn-2.6.3-cp311-cp311-linux_x86_64.whl
  error: [Errno 18] Invalid cross-device link: 'flash_attn-2.6.3+cu123torch2.1cxx11abiTRUE-cp311-cp311-linux_x86_64.whl' -> '/tmp/eb-lsqh835v/pip-wheel-teg_ahm9/flash_attn-2.6.3-cp311-cp311-linux_x86_64.whl'
  error: subprocess-exited-with-error

   python setup.py bdist_wheel did not run successfully.
   exit code: 1
  > See above for output.
```

**Comment by boegel** [comment]
@verdurin ` error: [Errno 18] Invalid cross-device link` => that looks weird to me, can you provide some more info on your system setup here, in particular which filesystem you're using for EasyBuild build directories?

**Comment by laraPPr** [comment]
@boegel the testresults of job 4621 have still not come in and it was submitted 5 days ago is this normal?

**Comment by fizwit** [comment]
I get the same build errors that @verdurin had reported.  Adding `--use-pep517` to build command does not help.
I have also tested with older version of flash-attn with the same errors.

```
Building wheels for collected packages: flash-attn
  Building wheel for flash-attn (setup.py): started
  Building wheel for flash-attn (setup.py): finished with status 'error'
  error: subprocess-exited-with-error

   python setup.py bdist_wheel did not run successfully.
   exit code: 1
  > [21 lines of output]
      fatal: not a git repository (or any parent up to mount point /)
      Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).


      torch.__version__  = 2.1.2


      /app/software/Python/3.11.3-GCCcore-12.3.0/lib/python3.11/site-packages/setuptools/__init__.py:84: _DeprecatedInstaller: setuptools.installer and fetch_build_eggs are deprecated.
      !!

              ********************************************************************************
              Requirements should be satisfied by a PEP 517 installer.
              If you are using pip, you can try `pip install --use-pep517`.
              ********************************************************************************

      !!
        dist.fetch_build_eggs(dist.setup_requires)
      running bdist_wheel
      Guessing wheel URL:  https://github.com/Dao-AILab/flash-attention/releases/download/v2.6.3/flash_attn-2.6.3+cu123torch2.1cxx11abiTRUE-cp311-cp311-linux_x86_64.whl
      Raw wheel path /tmp/eb-5w60321o/pip-wheel-4tip0_4n/flash_attn-2.6.3-cp311-cp311-linux_x86_64.whl
      error: [Errno 18] Invalid cross-device link: 'flash_attn-2.6.3+cu123torch2.1cxx11abiTRUE-cp311-cp311-linux_x86_64.whl' -> '/tmp/eb-5w60321o/pip-wheel-4tip0_4n/flash_attn-2.6.3-cp311-cp311-linux_x86_64.whl'
```

**Comment by pavelToman** [comment]
seems others has the same problem: https://github.com/Dao-AILab/flash-attention/issues/875

**Comment by pavelToman** [comment]
@fizwit @verdurin could you please test it again? Invalid cross-device link error should be fixed

**Comment by pavelToman** [comment]
@boegelbot please test @ jsc-zen3

**Comment by fizwit** [comment]
@pavelToman re-tested with your excellent patch and got much further.  This fatal error happened, then I added CUTLASS-3.4.0-foss-2023a-CUDA-12.1.1.eb as a dep, and it builds!  See PR #21184



```     
 g++ -MMD -MF /build/flashattention/2.6.3/foss-2023a-CUDA-12.1.1/flashattention/flash-attention-2.6.3/build/temp.linux-x86_64-cpython-311/csrc/flash_attn/flash_api.o.d -DNDEBUG -g -fwrapv -O3 -Wall -O2 -ftree-vectorize -march=native -fno-math-errno -fPIC -O2 -ftree-vectorize -march=native -fno-math-errno -fPIC -O2 -ftree-vectorize -march=native -fno-math-errno -I/app/software/FFTW/3.3.10-GCC-12.3.0/include -I/app/software/FlexiBLAS/3.3.1-GCC-12.3.0/include -I/app/software/FlexiBLAS/3.3.1-GCC-12.3.0/include/flexiblas -fPIC -I/build/flashattention/2.6.3/foss-2023a-CUDA-12.1.1/flashattention/flash-attention-2.6.3/csrc/flash_attn -I/build/flashattention/2.6.3/foss-2023a-CUDA-12.1.1/flashattention/flash-attention-2.6.3/csrc/flash_attn/src -I/build/flashattention/2.6.3/foss-2023a-CUDA-12.1.1/flashattention/flash-attention-2.6.3/csrc/cutlass/include -I/app/software/PyTorch/2.1.2-foss-2023a-CUDA-12.1.1/lib/python3.11/site-packages/torch/include -I/app/software/PyTorch/2.1.2-foss-2023a-CUDA-12.1.1/lib/python3.11/site-packages/torch/include/torch/csrc/api/include -I/app/software/PyTorch/2.1.2-foss-2023a-CUDA-12.1.1/lib/python3.11/site-packages/torch/include/TH -I/app/software/PyTorch/2.1.2-foss-2023a-CUDA-12.1.1/lib/python3.11/site-packages/torch/include/THC -I/app/software/CUDA/12.1.1/include -I/app/software/Python/3.11.3-GCCcore-12.3.0/include/python3.11 -c -c /build/flashattention/2.6.3/foss-2023a-CUDA-12.1.1/flashattention/flash-attention-2.6.3/csrc/flash_attn/flash_api.cpp -o /build/flashattention/2.6.3/foss-2023a-CUDA-12.1.1/flashattention/flash-attention-2.6.3/build/temp.linux-x86_64-cpython-311/csrc/flash_attn/flash_api.o -O3 -std=c++17 -DTORCH_API_INCLUDE_EXTENSION_H '-DPYBIND11_COMPILER_TYPE="_gcc"' '-DPYBIND11_STDLIB="_libstdcpp"' '-DPYBIND11_BUILD_ABI="_cxxabi1017"' -DTORCH_EXTENSION_NAME=flash_attn_2_cuda -D_GLIBCXX_USE_CXX11_ABI=1
      /build/flashattention/2.6.3/foss-2023a-CUDA-12.1.1/flashattention/flash-attention-2.6.3/csrc/flash_attn/flash_api.cpp:11:10: fatal error: cutlass/numeric_types.h: No such file or directory
         11 | #include <cutlass/numeric_types.h>
            |          ^~~~~~~~~~~~~~~~~~~~~~~~~
      compilation terminated.
      ninja: build stopped: subcommand failed.
```

**Review by boegel — APPROVED** [review]
lgtm

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
node3304.joltik.os - Linux RHEL 8.8, x86_64, Intel(R) Xeon(R) Gold 6242 CPU @ 2.80GHz, 1 x NVIDIA Tesla V100-SXM2-32GB, 545.23.08, Python 3.6.8
See https://gist.github.com/boegel/f0b637f363a0d92541468076edda9c03 for a full test report.

**Comment by boegel** [comment]
@boegelbot please test @ generoso

**Comment by boegel** [comment]
@boegelbot please test @ jsc-zen3

**Comment by boegel** [comment]
Going in, thanks @pavelToman!

**Pull request merged**
