### PR TITLE
{bio}[dummy/dummy] Kent_tools v20180716

### PR DESCRIPTION
**Pull request by vanzod**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by vanzod** [comment]
Test report by @vanzod
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
cermis - Linux debian 9.4, Intel(R) Xeon(R) CPU           E5620  @ 2.40GHz, Python 2.7.13
See https://gist.github.com/267816a99fd8c563c3e67e87f7ead862 for a full test report.

**Comment by verdurin** [comment]
Test report by @verdurin
**FAILED**
Build succeeded for 0 out of 1 (1 easyconfigs in this PR)
rescomp2 - Linux centos 6.8, Intel(R) Xeon(R) CPU E5-2650 v2 @ 2.60GHz, Python 2.7.11
See https://gist.github.com/25aaf55d0a91f6d40597bca4349f7240 for a full test report.

**Comment by verdurin** [comment]
@vanzod Please update the download instructions to use the timestamp you're expecting.
Also seeing a checksum error.

**Comment by vanzod** [comment]
@verdurin I have created a new sources archive but still my checksum does not match yours.

**Comment by verdurin** [comment]
@vanzod Sigh. Please make a note of this in the sources comment, so it doesn't surprise future builders.

**Comment by verdurin** [comment]
Going in, thanks @vanzod!

**Comment by verdurin** [comment]
@boegel We haven't added a checksum requirement to the tests yet then?

**Comment by boegel** [comment]
No (it's still on my TODO, cfr. #5005) , and when we do, we will definitely need to be able to make exceptions through some kind of whitelist when `Kent_tools` would be on (probably `MATLAB` too).

**Comment by boegel** [comment]
checksum removed in follow-up PR #6715

**Pull request merged**
