### PR TITLE
{data}[foss/2020b] update ROOT 6.24.00

### PR DESCRIPTION
**Pull request by rarensu**
Update ROOT and dep GL2PS to foss-2020b toolchain. Fix previous ROOT config opts which were incorrect.

Refers to issue #12830 

Depends on PR #12106 and PR ~~#12576~~

### CODE REVIEW

**Comment by boegel** [comment]
@rarensu Sorry for the delay in picking up on this...

I think it's worth opening a separate PR for tweaking the configure options for the existing ROOT easyconfigs (which would close #12830), do you think that makes sense?

It would make sense to include a brief description in the PR body to clarify the changes, like why it's OK to drop `-Dpython=ON -Dpython3=ON -Dpcre=ON -Dzlib=ON`, etc.

**Comment by rarensu** [comment]
I have overridden the head of this branch with a commit that does not contain the config opt fixes. Those fixes have been put on another branch which is now also a pull request.

**Review by Red3amer — COMMENTED** [review]
``

**Comment by boegel** [comment]
closing this since `foss/2020b` is deprecated, see https://docs.easybuild.io/policies/toolchains

**Pull request closed without merging**
