### PR TITLE
Add Java version 8u402b06

### PR DESCRIPTION
**Pull request by Turakar**
This PR adds Java version 8 patch 402 build 06 based on the easyconfig file for the previous version.

### CODE REVIEW

**Comment by Turakar** [comment]
ping :slightly_smiling_face:

**Review by Micket — APPROVED** [review]
lgtm

**Comment by Micket** [comment]
@boegelbot please test @ generoso

**Comment by Micket** [comment]
Test report by @Micket
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
alvis2-05 - Linux Rocky Linux 8.9, x86_64, Intel(R) Xeon(R) Gold 6226R CPU @ 2.90GHz, 8 x NVIDIA Tesla T4, 550.54.14, Python 3.6.8
See https://gist.github.com/Micket/42d76bdd8910c925564980add4b426b6 for a full test report.

**Comment by Micket** [comment]
@boegelbot please test @ jsc-zen3

**Comment by Micket** [comment]
For future reference, if you update Java, please also update the wrapper to point to the new version. I did so with #20261 now

**Pull request merged**
