### PR TITLE
{cae}[foss/2019b] OpenFOAM 7

### PR DESCRIPTION
**Pull request by furstj**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by boegel** [comment]
Test report by @boegel
**FAILED**
Build succeeded for 0 out of 1 (1 easyconfigs in this PR)
node3153.skitty.os - Linux centos linux 7.7.1908, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz, Python 3.6.8
See https://gist.github.com/35b0bf38c96af2a155d57726e438ab56 for a full test report.

**Comment by lexming** [comment]
Test report by @lexming
**FAILED**
Build succeeded for 0 out of 1 (1 easyconfigs in this PR)
login2.cerberus.os - Linux centos linux 7.6.1810, Intel(R) Xeon(R) Gold 6126 CPU @ 2.60GHz, Python 2.7.5
See https://gist.github.com/13f5a8e12d1e4e2988449f5cd38a5067 for a full test report.

**Comment by lexming** [comment]
My failed test seems to be related to https://bugs.openfoam.org/view.php?id=3303 and the changes in https://github.com/OpenFOAM/OpenFOAM-7/commit/9980357df166e81b5d67fe6de33f9fff7869e373

**Comment by furstj** [comment]
@lexming it seems that OF7 already includes changes related to OF bug no. 3301. Nevertheless, I inclded also a patch related to OF bug 3303 (bashrc, wclean, wrmdep).

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
node2470.golett.os - Linux centos linux 7.7.1908, Intel(R) Xeon(R) CPU E5-2680 v3 @ 2.50GHz, Python 2.7.5
See https://gist.github.com/8478fa351f2368ee228f72f446f30756 for a full test report.

**Comment by boegel** [comment]
@lexming Can you also re-test this PR?

**Comment by boegel** [comment]
Test report by @boegel
**FAILED**
Build succeeded for 0 out of 1 (1 easyconfigs in this PR)
generoso-2 - Linux centos linux 7.6.1810, Intel(R) Xeon(R) CPU E5-2660 v4 @ 2.00GHz, Python 3.6.8
See https://gist.github.com/04f6cd66fb6e5506ef7eb2a26d94c568 for a full test report.

**Comment by boegel** [comment]
@furstj Any idea on this? Looks related to `Mesa`, which provides `GL/gl.h`, not sure why it expects it to be in the `libdrm` install dir?

```
CMake Error at /work/maintainers/CO7/broadwell/software/Qt5/5.13.1-GCCcore-8.3.0/lib/cmake/Qt5Gui/Qt5GuiConfigExtras.cmake:9 (message):
  Failed to find "GL/gl.h" in
  "/work/maintainers/CO7/broadwell/software/libdrm/2.4.99-GCCcore-8.3.0/include/libdrm".
Call Stack (most recent call first):
  /work/maintainers/CO7/broadwell/software/Qt5/5.13.1-GCCcore-8.3.0/lib/cmake/Qt5Gui/Qt5GuiConfig.cmake:187 (include)
  /work/maintainers/CO7/broadwell/software/Qt5/5.13.1-GCCcore-8.3.0/lib/cmake/Qt5Widgets/Qt5WidgetsConfig.cmake:100 (find_package)
  /work/maintainers/CO7/broadwell/software/Qt5/5.13.1-GCCcore-8.3.0/lib/cmake/Qt5/Qt5Config.cmake:28 (find_package)
  /work/maintainers/CO7/broadwell/software/ParaView/5.6.2-foss-2019b-Python-3.7.4-mpi/lib/cmake/paraview-5.6/ParaViewQt.cmake:71 (find_package)
  /work/maintainers/CO7/broadwell/software/ParaView/5.6.2-foss-2019b-Python-3.7.4-mpi/lib/cmake/paraview-5.6/Modules/pqApplicationComponents.cmake:12 (pv_find_package_qt)
  /work/maintainers/CO7/broadwell/software/ParaView/5.6.2-foss-2019b-Python-3.7.4-mpi/lib/cmake/paraview-5.6/vtkModuleAPI.cmake:45 (include)
  /work/maintainers/CO7/broadwell/software/ParaView/5.6.2-foss-2019b-Python-3.7.4-mpi/lib/cmake/paraview-5.6/vtkModuleAPI.cmake:15 (vtk_module_load)
  /work/maintainers/CO7/broadwell/software/ParaView/5.6.2-foss-2019b-Python-3.7.4-mpi/lib/cmake/paraview-5.6/vtkModuleAPI.cmake:152 (_vtk_module_config_recurse)
  /work/maintainers/CO7/broadwell/software/ParaView/5.6.2-foss-2019b-Python-3.7.4-mpi/lib/cmake/paraview-5.6/VTKConfig.cmake:143 (vtk_module_config)
  /work/maintainers/CO7/broadwell/software/ParaView/5.6.2-foss-2019b-Python-3.7.4-mpi/lib/cmake/paraview-5.6/ParaViewConfig.cmake:75 (include)
  CMakeLists.txt:4 (FIND_PACKAGE)
```

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
node3169.skitty.os - Linux centos linux 7.7.1908, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz, Python 3.6.8
See https://gist.github.com/be47f02ecd17a33ceb9870604bd4d7d9 for a full test report.

**Comment by furstj** [comment]
@boegel I have no idea why it failed due to GL/gl.h. It compiles on my system without problems and you were able to compile it to in your last test. Interesting is that Qt or ParaView compile well (and both use OpenGL too). Do you have any idea wht is the difference between your systems or build environments at node3169.skitty.os and generoso-2?  

My latest version uses several patches for OpenFOAM build system (wmake) which are connected to problems with compiling in directories with symlinks. Do you mean that there is any difference between generoso-2 and node3169 related to symlinks?

**Comment by lexming** [comment]
@furstj yep, I also saw that some patches for OF bug 3303 are already merged in version 7 and it seems that the expansion of `$WM_PROJECT_DIR` is the intended behavior moving forward. So I took a different approach to solve this issue and updated the easyblock for OpenFOAM to expand `$WM_PROJECT_DIR` from version 7 onward.

My changes are in https://github.com/lexming/easybuild-easyblocks/commit/a6292b3372d8e87287eadee9c4b90789203d2f6c

I would say that maintaining the code in the easyblock might be easier than having an additional patch, but honestly, I'm not familiar with the development of OpenFOAM, so I'm not sure which solution is best moving forward. Let me know what you think. I'll only open a PR in easyblock, if you and @boegel prefer that.

**Comment by lexming** [comment]
Test report by @lexming
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
login2.cerberus.os - Linux centos linux 7.6.1810, Intel(R) Xeon(R) Gold 6126 CPU @ 2.60GHz, Python 2.7.5
See https://gist.github.com/777b53a22981e6f75d95d9cd4ac7296e for a full test report.

**Comment by lexming** [comment]
The previous test report is with this easyconfig for `OpenFOAM-7` and the easyblock for `OpenFOAM` in current `develop` branch.

**Comment by boegel** [comment]
@furstj On all systems I tested except `generoso` we have `mesa-libGL-devel` installed in the OS, which provides `/usr/include/GL/gl.h`.
`mesa-libGL-devel` is not there on `generoso` (only `mesa-libGL`), so `GL/gl.h` can't be found in the OS on that system.

**Comment by boegel** [comment]
@furstj Can you open an issue on that problem?

I don't think it should block this PR (since it's not specific to this particular OpenFOAM version, I think), but it would be nice to get it fixed (and not having an open issue for it means we'll forget about it).

**Comment by akesandgren** [comment]
Why is OpenFOAM pulling in MESA in the first place? Did they add a GUI?

**Comment by boegel** [comment]
@akesandgren As a dep for `ParaView`, which is a dep for `OpenFOAM` (for `paraFoam`, I think)

**Comment by furstj** [comment]
@boegel I will try to compile this EB on a machine without mesa-devel package and we will see.

@akesandgren OF compiles also some plugins to ParaView (e.g. specific openfoam readers). I guess that it needs whole ParaView stack in order to compile these plugins (i.e. ParaView, Qt, Mesa, ...)

@lexming I agree with you that corrected easyblock is much better solution than a mega-patch. However I think that the problem is in OpenFOAM build scripts (I mean in wmake) and it will hurt also all non-easybuild OpenFoamers. Moreover, patches for OpenFOAM 3303 bug are already included in OpenFOAM-dev version, so the current EB patch for 3303 is only temporary solution. I hope that the OpenFOAM-8 (when it will be released) will solve the problem. 
Therefore my preference is to use ugly patch for OF7 and to leave easyblock untouched.

**Comment by lexming** [comment]
@furstj if this patchset is already part of OpenFOAM-dev, then this is indeed the best solution.

**Comment by furstj** [comment]
@boegel I tried a compilation on a system without mesa-devel and it failed with missing GL/gl.h too. After some analysis I found that the problem is quite complicated and it probably goes through Qt5 down to pkg-config. The "pkg-config --cflags gl" returns wrong include path! It then goes to Qt5 (it can be found in Qt5GuiConfigExtras.cmake) and finally breaks the OpenFOAM compilation.

It is very interesting that the pkg-config from OpenSUSE Leap distribution reports also wrong path with libdrm and the Qt5GuiConfigExtras.cmake from standard distribution contains the wrong path too.

There are several possibilities for dealing with this issue:

1. one can replace the wrong path in Qt5GuiConfigExtras.cmake using a postinstallcmd in Qt5 easyconfig (I have done this on my computer and it seems to work - I was able to compile ParaView and OpenFOAM)

1. one can patch OpenFOAM's compilation scripts in order to look for GL/gl.h in correct places (I didn't try it yet but I hope that it should be possible)

1. one can correct the pkg-config (or at least Mesa pkg-config) in order to give right answer to "--cflags gl"

1. put "mesa-devel" in osdependencies for OpenFOAM

Under my opinion the least distracting is the option 1. It is sufficient to recompile Qt5 and that's all. 
The second option isolates the changes to OpenFOAM package, so it does not solve the problem for other packages using Qt5.
The option 3 is very dangerous. There are plenty of packages depending on pkg-config. So any change in pkg-config could break a tons of software packages. 
The option 4 is safe but we then use gl.h from different mesa version. What is your opinion?

**Comment by akesandgren** [comment]
Note that pkg-config --cflags gl returns the wrong include path in Ubuntu too, so this is not a EasyBuild specific problem.

**Comment by akesandgren** [comment]
This looks more like a bug in how pkg-config works to me.

**Comment by akesandgren** [comment]
The gl.pc pkgconfig file (from both Ubuntu and EasyBuild) is technically correct. But pkg-config is not returning what you'd expect.

Try
```
pkg-config --debug --cflags gl 2>&1 | less
```
And look at what it really does...

**Comment by akesandgren** [comment]
Actually, this is a bug in pkg-config 0.29.2...
0.29.1 returns the correct answers

I'll try to chase it down

**Comment by furstj** [comment]
On my centos 6 machine the pkg-config from standard distribution (i.e. version 0.23) returns 

sgi1:~$ /usr/bin/pkg-config --cflags gl
-I/opt/easybuild/software/Mesa/18.1.1-foss-2018b/include -I/opt/easybuild/software/X11/20180604-GCCcore-7.3.0/include  

whereas 0.29.2 gives wrong path.

So it seems that it confirms your finding concerning the bug in 0.29.2.

**Comment by akesandgren** [comment]
Yeah, Ubuntu 0.29.1 version gives me:
```
/usr/bin/pkg-config --cflags gl
-I/hpc2n/eb/software/MPI/GCC/6.4.0-2.28/OpenMPI/2.1.2/Mesa/17.3.6/include -I/hpc2n/eb/software/Compiler/GCCcore/6.4.0/X11/20180131/include
```
while easybuild 0.29.2 returns nothing
and easybuilds 0.29.1 returns
```
pkg-config --cflags gl
-I/hpc2n/eb/software/MPI/GCC/6.4.0-2.28/OpenMPI/2.1.2/Mesa/17.3.6/include -I/hpc2n/eb/software/Compiler/GCCcore/6.4.0/X11/20180131/include
```

**Comment by akesandgren** [comment]
0.29.2 returns the correct thing with
env PKG_CONFIG_ALLOW_SYSTEM_CFLAGS=1 pkg-config --cflags gl

**Comment by furstj** [comment]
Hmm, then I will try to compile Qt5 with PKG_CONFIG_ALLOW_SYSTEM_CFLAGS=1 and we will see.

**Comment by akesandgren** [comment]
The reason is a resent change that made it consider CPATH for removals.
I.e. since we do set CPATH to everything with an include dir it will be removed from pkg-config output.

At the moment it removes paths from CPATH, C_INCLUDE_PATH, and CPP_INCLUDE_PATH

So not a bug as such, just a sometimes problematic behaviour.

**Comment by boegel** [comment]
@akesandgren So, what's the best way to deal with this then, taking into account @furstj's overview in https://github.com/easybuilders/easybuild-easyconfigs/pull/9390#issuecomment-560392025?

**Comment by akesandgren** [comment]
I'd wait for his results from rebuilding Qt5 first.

We may, worst case, have to add that env setting to pkg-config itself.
We may get away with adding it only when it's really needed...

**Comment by akesandgren** [comment]
The main problem with PKG_CONFIG_ALLOW_SYSTEM_CFLAGS is that it would leave /usr/include, if anything points ot it, in the output which we do NOT want.

**Comment by furstj** [comment]
Qt5 still picks wrong path even with PKG_CONFIG_ALLOW_SYSTEM_CFLAGS=1 :(. However the pkg-config provides correct path now, the configure script still picks the wrong one (probably the last one).

So what shall we do? I vote for solution 1 from my previous post: just to replace the wrong path in Qt5GuiConfigExtras.cmake by the correct one using postinstallcmd.

**Comment by akesandgren** [comment]
Let me take a look...

**Comment by furstj** [comment]
Similar problem was reported in https://bugreports.qt.io/browse/QTBUG-43445, but the patch there does not solve our troubles.

**Comment by akesandgren** [comment]
The problem is technically not that Qt5GuiConfigExtras.cmake contains that libdrm path.
The find_path below it should still use CMAKE_INCLUDE_PATH to find gl.h.
So the question is rather, has Qt5 removed things from CMAKE_INCLUDE_PATH ?? Which EB sets up to contain everything in CPATH.

Exactly what did you build? And where did it blow up? I'd like to check...

**Comment by akesandgren** [comment]
BTW, the patch in QTBUG-43445 is already in Qt5 5.12.1 and later, so it is irrelevant.

**Comment by furstj** [comment]
@akesandgren To recap:
- the problem shows up only when the machine does not have /usr/include/GL/gl.h (i.e. without mesa-devel or similar package)
- I tried to compile OpenFOAM using eb --from-pr 9030 -r (see boegel's failed test report at https://gist.github.com/04f6cd66fb6e5506ef7eb2a26d94c568).
- all dependencies were compiled without problem (including e.g. ParaView)
- compilation of OpenFOAM failed by not founding the GL/gl.h

If I replaced the libdrm path in Qt5GuiConfigExtras.cmake by adding 

postinstallcmds = [
    "sed -i -e 's|libdrm/2.4.99-GCCcore-8.3.0/include/libdrm|Mesa/19.1.7-GCCcore-8.3.0/include|' %(installdir)s/lib/cmake/Qt5Gui/Qt5GuiConfigExtras.cmake",
]

into Qt5-5.13.1-GCCcore-8.3.0.eb (and recompiled Qt), everything went OK.

**Comment by akesandgren** [comment]
Hmmm, I had no problems building 9390... without changes to Qt5

**Comment by akesandgren** [comment]
I'll have to do this in our cleanroom setup to double check.

**Comment by akesandgren** [comment]
Hmmm, my cleanroom install do fail on GL/gl.h

**Comment by furstj** [comment]
@akesandgren Yes, exactly what happens to me and boegel. It fails when there is no /usr/include/GL/gl.h.

I did try also OpenFOAM-v1906 and it compiles fine. Therefore it should be possible to patch OpenFOAM-7 too. The question is then if I should modify OpenFOAM-7 easyconfig letting Qt intact, or if (me someone else?) will modify Qt in order to replace librm path by path to mesa. Both options are feasible. What is your opinion?

**Comment by boegel** [comment]
It's still not clear to me where the bug/breakage is actually taking place...

Is the `Qt5GuiConfigExtras.cmake` in the `Qt5` installation buggy, or is OpenFOAM 7 making incorrect assumptions somewhere?
A clear answer to that question could indicate the right place to fix the issue, I think...

Also note that `OpenFOAM-6-foss-2018b.eb` built fine on the exact same system (without `GL/gl.h` available in the OS), not sure if that helps at all to pinpoint the problem...

**Comment by akesandgren** [comment]
Something in either Qt5 or OpenFOAM has to be setting some variable that forces find_path to NOT look in CMAKE_INCLUDE_DIRS, or unsetting CMAKE_INCLUDE_DIRS.

**Comment by akesandgren** [comment]
I'll be chasing this down (I hope) so hang in there...

**Comment by furstj** [comment]
I'm able to patch OF7 compilation now. If we replace

cmake ../..

by 

cmake -D_qt5gui_OPENGL_INCLUDE_DIR=$EBROOTMESA/include ../..

in applications/utilities/postProcessing/graphics/PVReaders/Allwmake, the OF compiles.

**Comment by akesandgren** [comment]
Yeah, the reason it doesn't work as we expected it to, is that OpenFOAM is not using the cmakemake easyblock. That's where it is setting CMAKE_INCLUDE_PATH=CPPPATHS+CPATHS.

So there are one fairly simple way out and that is to set CMAKE_INCLUDE_PATH the same way we do in cmakemake.py in the OpenFOAM easyblock, or let openfoam.py inherit cmakemake.
We should probably make sure CMAKE_C_COMPILER etc are also correctly set in openfoam.py...

**Comment by akesandgren** [comment]
I have a potential fix involving cmakemake.py and openfoam.py that fixes this in a slightly more generic way.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
generoso-2 - Linux centos linux 7.6.1810, Intel(R) Xeon(R) CPU E5-2660 v4 @ 2.00GHz, Python 3.6.8
See https://gist.github.com/9d018e73f209b3e13f764bd8396fc5b3 for a full test report.

**Comment by boegel** [comment]
Test report on `generoso` was on top of https://github.com/easybuilders/easybuild-easyblocks/pull/1869... :+1:

**Comment by akesandgren** [comment]
with or without the patch to work around the GL/gl.h problem? I.e. with or without 0efd968f2846d7649cb686bf64c5baae8abc0434

**Comment by boegel** [comment]
Test report by @boegel
**FAILED**
Build succeeded for 0 out of 1 (1 easyconfigs in this PR)
node3109.skitty.os - Linux centos linux 7.7.1908, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz, Python 3.6.8
See https://gist.github.com/78d79dbd1d79a0a5d13bc42b14c6f13b for a full test report.

**Comment by boegel** [comment]
> with or without the patch to work around the GL/gl.h problem? I.e. with or without [0efd968](https://github.com/easybuilders/easybuild-easyconfigs/commit/0efd968f2846d7649cb686bf64c5baae8abc0434)

Test report was with the last commit included (so not really testing https://github.com/easybuilders/easybuild-easyblocks/pull/1869 I guess).

But we get another opportunity for that in #9440...

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
node3109.skitty.os - Linux centos linux 7.7.1908, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz, Python 3.6.8
See https://gist.github.com/d1482fc927ce2465fe187d94c7afff1b for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
node2704.swalot.os - Linux centos linux 7.7.1908, Intel(R) Xeon(R) CPU E5-2660 v3 @ 2.60GHz, Python 2.7.5
See https://gist.github.com/ba07928db1cf0e2ff1c40e2788e9d6d0 for a full test report.

**Comment by akesandgren** [comment]
@furstj with the updated easyblock for cmakemake and openfoam in https://github.com/easybuilders/easybuild-easyblocks/pull/1869 you can remove the patch that sets
-D_qt5gui_OPENGL_INCLUDE_DIR=$EBROOTMESA/include 

Although they did not make it into EB 4.1.0

**Comment by furstj** [comment]
@akesandgren I have just tested easyblopck #1869 without -D_qt5.... and it works. Next commit removes the -D_qt5gui... Thanx a lot for more systematic solution.

**Comment by lexming** [comment]
Test report by @lexming
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
login2.cerberus.os - Linux centos linux 7.6.1810, Intel(R) Xeon(R) Gold 6126 CPU @ 2.60GHz, Python 2.7.5
See https://gist.github.com/7f37148f74e7d4b53b33e092d565c286 for a full test report.

**Comment by lexming** [comment]
Tested on top of https://github.com/easybuilders/easybuild-easyblocks/pull/1869

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
generoso-1 - Linux centos linux 7.6.1810, Intel(R) Xeon(R) CPU E5-2660 v4 @ 2.00GHz, Python 3.6.8
See https://gist.github.com/086f5b2515fa992d61390e8e560db30c for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
node3112.skitty.os - Linux centos linux 7.7.1908, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz, Python 3.6.8
See https://gist.github.com/4afdaccb9453ae7b8f7e4526c9e224f0 for a full test report.

**Comment by boegel** [comment]
Going in, thanks @furstj!

**Pull request merged**
