### PR TITLE
disable auto-vectorizer (`-ftree-vectorize`) for OpenFOAM v10 + v11 when using toolchain that with GCC >= 11

### LINKED ISSUE #20927: incorrect results for OpenFOAM v10 + v11 when built with GCC 11.3.0 or 12.3.0 and `-ftree-vectorize`
We got a report that installations of OpenFOAM (`OpenFOAM-10-foss-2022a.eb`, `OpenFOAM-10-foss-2023a.eb`, `OpenFOAM-11-foss-2023a.eb`) produce incorrect results, see also https://bugs.openfoam.org/view.php?id=4076 .

After a lot of digging, we figured out that this problem is caused by a compiler bug: if these easyconfigs are changed to avoid the use of the `-ftree-vectorize` compiler option, the problem is resolved:

```python
toolchainopts = {'vectorize': False}
```

### PR DESCRIPTION
**Pull request by boegel**
(created using `eb --new-pr`)
fixes #20927

### CODE REVIEW

**Comment by boegel** [comment]
Although @Micket mentioned that using `-O3` (with `-ftree-vectorize`) may also work to circumvent the problem reported in #20927, I still feel the change being made here makes sense, since we already disable `-ftree-vectorize` for the other OpenFOAM variant since:
* #15495

**Comment by boegel** [comment]
@boegelbot please test @ jsc-zen3
CORE_CNT=16

**Comment by boegel** [comment]
@boegelbot please test @ generoso
CORE_CNT=16

**Comment by boegel** [comment]
> Test report by @boegelbot **FAILED** Build succeeded for 3 out of 6 (6 easyconfigs in total) jsczen3c2.int.jsc-zen3.fz-juelich.de - Linux Rocky Linux 9.4, x86_64, AMD EPYC-Milan Processor (zen3), Python 3.9.18 See https://gist.github.com/boegelbot/d936ff97c42576d451b85dc84950c5a5 for a full test report.

Tests for `OpenFOAM-10-foss-2022a*eb` failed because of interference of #20949 where the `OpenMPI` component of `foss/2022a` was being rebuilt.

**Comment by boegel** [comment]
@boegelbot please test @ jsc-zen3
CORE_CNT=16
EB_ARGS="OpenFOAM-10-foss-2022a-20230119-int64.eb OpenFOAM-10-foss-2022a-20230119.eb OpenFOAM-10-foss-2022a.eb"

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 6 out of 6 (6 easyconfigs in total)
node3158.skitty.os - Linux RHEL 8.8, x86_64, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz, Python 3.6.8
See https://gist.github.com/boegel/9dafcbcf1266a8cfd969372eeb9cc8c0 for a full test report.

**Review by jfgrimm — APPROVED** [review]

**Pull request merged**
