### PR TITLE
{vis}[GCCcore/8.2.0] Graphviz v2.40.1, GTS v0.7.6

### PR DESCRIPTION
**Pull request by vanzod**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by vanzod** [comment]
Test report by @vanzod
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in this PR)
cermis - Linux debian 9.9, Intel(R) Xeon(R) CPU           X5670  @ 2.93GHz, Python 2.7.13
See https://gist.github.com/eb7e856c256eba2f6bd46dbe0e0e2513 for a full test report.

**Comment by vanzod** [comment]
Test report by @vanzod
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in this PR)
cermis - Linux debian 9.9, Intel(R) Xeon(R) CPU           X5670  @ 2.93GHz, Python 2.7.13
See https://gist.github.com/31e48d0d000cdb0ae7f5c44579f15960 for a full test report.

**Comment by smoors** [comment]
Test report by @smoors
**FAILED**
Build succeeded for 1 out of 2 (2 easyconfigs in this PR)
nic402 - Linux centos linux 7.5.1804, Intel(R) Xeon(R) Gold 6148 CPU @ 2.40GHz, Python 2.7.5
See https://gist.github.com/fb75486d7c65b48591e5397c8c535486 for a full test report.

**Comment by smoors** [comment]
@vanzod here is the error:
```
../../plugin/pango/.libs/libgvplugin_pango.so: error: undefined reference to 'g_object_unref'
../../plugin/pango/.libs/libgvplugin_pango.so: error: undefined reference to 'g_type_name'
../../plugin/pango/.libs/libgvplugin_pango.so: error: undefined reference to 'g_type_check_instance_cast'
collect2: error: ld returned 1 exit status
make[3]: *** [dot_builtins] Error 1
make[3]: Leaving directory `/tmp/smoors.2319221/tmp/smoors/build/Graphviz/2.40.1/GCCcore-8.2.0/graphviz-2.40.1/cmd/dot'
make[2]: *** [all-recursive] Error 1
make[2]: Leaving directory `/tmp/smoors.2319221/tmp/smoors/build/Graphviz/2.40.1/GCCcore-8.2.0/graphviz-2.40.1/cmd'
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory `/tmp/smoors.2319221/tmp/smoors/build/Graphviz/2.40.1/GCCcore-8.2.0/graphviz-2.40.1'
make: *** [all] Error 2
```

**Comment by boegel** [comment]
This doesn't look it's worth pursuing further, so closing...

**Pull request closed without merging**
