### PR TITLE
{tools}[GCCcore/11.2.0] GCAM-model-interfaces v5.1

### PR DESCRIPTION
**Pull request by sassy-crick**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by migueldiascosta** [comment]
even though there's nothing being built, this needs either an exception in the easyconfig tests or `binutils` as a builddep

**Comment by sassy-crick** [comment]
> even though there's nothing being built, this needs either an exception in the easyconfig tests or `binutils` as a builddep

I can add the `binutils` to the EC file. However, as that is part of the PR #15398 build, is there a better way of doing it? I was thinking along the lines like the Python bundle installations. So instead of having this EC and the one coming from PR #15398, we can include it in PR #15398 and remove that one. I could not find a good way of doing it though.

**Comment by migueldiascosta** [comment]
> However, as that is part of the PR https://github.com/easybuilders/easybuild-easyconfigs/pull/15398 build, is there a better way of doing it? I was thinking along the lines like the Python bundle installations. So instead of having this EC and the one coming from PR https://github.com/easybuilders/easybuild-easyconfigs/pull/15398, we can include it in PR https://github.com/easybuilders/easybuild-easyconfigs/pull/15398 and remove that one. I could not find a good way of doing it though.

well, yes, you can turn the `GCAM` easyconfig into a `Bundle`, which means that you'll need to install `GCAM` itself as a component (see for instance the EMAN2 easyconfig in https://github.com/easybuilders/easybuild-easyconfigs/pull/14641). Is that what you meant?

**Comment by sassy-crick** [comment]
I will close this PR as the `GCAM-model-interfaces` has been included as a bundle in PR #15398.
Thanks for your help!

**Pull request closed without merging**
