### PR TITLE
{lang}[GCCcore/8.3.0] SIP v4.19.22 w/ Python 3.7.4

### PR DESCRIPTION
**Pull request by smoors**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by smoors** [comment]
Test report by @smoors
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
node363.hydra.os - Linux centos linux 7.7.1908, x86_64, Intel(R) Xeon(R) Gold 6148 CPU @ 2.40GHz (skylake_avx512), Python 2.7.5
See https://gist.github.com/4cf37ea88e7f7f1a65b2b3493e2e7e6e for a full test report.

**Comment by lexming** [comment]
Test report by @lexming
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
node104.hydra.os - Linux centos linux 7.7.1908, x86_64, Intel(R) Xeon(R) CPU E5-2680 v2 @ 2.80GHz, Python 2.7.5
See https://gist.github.com/79830ecba355f560b63caaaba09a6e7a for a full test report.

**Comment by smoors** [comment]
Not sure if it is useful to have SIP separatly or not. I'm happy to close this PR if you think it's not useful.

I created the easyconfig, and later realized I didn't actually needed it..

**Comment by lexming** [comment]
Since it's already provided by PyQt5 and nothing else is currently using it, I would avoid the confusion of having `sip` in two different places.

**Pull request closed without merging**
