### PR TITLE
Update easyconfigs.py - add exception for VTK-9.2.6

### PR DESCRIPTION
**Pull request by pavelToman**
for https://github.com/easybuilders/easybuild-easyconfigs/pull/20981
resolves https://github.com/vscentrum/vsc-software-stack/issues/349

### CODE REVIEW

**Review by verdurin — APPROVED** [review]
Looks fine.

**Comment by verdurin** [comment]
@pavelToman it's easier to test this along with the application itself, so please add this change to #20981 and close this PR.

**Comment by pavelToman** [comment]
> @pavelToman it's easier to test this along with the application itself, so please add this change to #20981 and close this PR.

That was my intent, but I was unable to add it to https://github.com/easybuilders/easybuild-easyconfigs/pull/20981, could you hint me how please?

**Comment by verdurin** [comment]
@pavelToman can't you just add it as a new file, the same way you might do if you had forgotten to include a new patch file (for example)?

**Comment by pavelToman** [comment]
> @pavelToman can't you just add it as a new file, the same way you might do if you had forgotten to include a new patch file (for example)?

Normally I add the file by `eb --update-pr` but I can not do it with this file. I had to find it here on GitHub and modify it

**Comment by pavelToman** [comment]
This commit was add to https://github.com/easybuilders/easybuild-easyconfigs/pull/20981

**Pull request closed without merging**
