### PR TITLE
{vis}[fosscuda/2018b] VTK v8.1.1 w/ Python 3.6.6

### PR DESCRIPTION
**Pull request by dithwick**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by dithwick** [comment]
Looks like the Python 2.6 check failed because it couldn't download the python archive

```
2.6 is not installed; attempting download
Downloading archive: https://storage.googleapis.com/travis-ci-language-archives/python/binaries/ubuntu/16.04/x86_64/python-2.6.tar.bz2
0.15s$ curl -sSf -o python-2.6.tar.bz2 ${archive_url}
curl: (22) The requested URL returned error: 404 Not Found
Unable to download 2.6 archive. The archive may not exist. Please consider a different version.
```

**Comment by dithwick** [comment]
Test report by @dithwick
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
login2 - Linux centos 6.10, Intel(R) Xeon(R) CPU E5-2630 v3 @ 2.40GHz, Python 2.6.6
See https://gist.github.com/644b7b3f727462e61773d25a5df6c99d for a full test report.

**Comment by Micket** [comment]
kicking travis

**Comment by Micket** [comment]
travis kicked

**Comment by smoors** [comment]
Test report by @smoors
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
nic427 - Linux centos linux 7.5.1804, Intel(R) Xeon(R) Gold 6148 CPU @ 2.40GHz, Python 2.7.5
See https://gist.github.com/22bfabbd18c805e8025ac8357a3bf491 for a full test report.

**Comment by smoors** [comment]
Going in, thanks @dithwick!

**Pull request merged**
