### PR TITLE
{compiler}[dummy/] GCCcore v6.3.0

### PR DESCRIPTION
**Pull request by JackPerdue**
(created using `eb --new-pr`)
What GCCcore with system binutils should look like

### CODE REVIEW

**Comment by boegel** [comment]
relates to discussion in #4235

**Comment by JackPerdue** [comment]
Howdy akesandgren... can you recommend names for Ubuntu/Debian?  Is there a cross-reference for different distributions/versions?   In some of my other packages I did the same and only put "zlib-devel" (RH RPM) where in others I also included "zlib1g-dev" (which I just assume is the Debian name).

**Comment by akesandgren** [comment]
gcc-c++ -> g++
glibc-devel -> libc6-dev

**Comment by migueldiascosta** [comment]
@JackPerdue, this PR is being closed for the following reason(s): no activity for > 1 year.
Please don't hesitate to reopen this PR or add a comment if you feel this contribution is still relevant.
For more information on our policy w.r.t. closing PRs, see https://easybuild.readthedocs.io/en/latest/Contributing.html#why-a-pull-request-may-be-closed-by-a-maintainer

**Pull request closed without merging**
