### PR TITLE
{tools}[system/system] vsc-mympirun v5.1.0

### PR DESCRIPTION
**Pull request by boegel**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
node2448.golett.os - Linux centos linux 7.8.2003, x86_64, Intel(R) Xeon(R) CPU E5-2680 v3 @ 2.50GHz (haswell), Python 2.7.5
See https://gist.github.com/2e3776f985d48a3cc98660dd0725970f for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
node3165.skitty.os - Linux centos linux 7.8.2003, x86_64, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz (skylake_avx512), Python 3.6.8
See https://gist.github.com/740c019334a3e3a4aeefd0037df26c4e for a full test report.

**Comment by smoors** [comment]
Test report by @smoors
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
node378.hydra.os - Linux centos linux 7.7.1908, x86_64, Intel(R) Xeon(R) Gold 6148 CPU @ 2.40GHz (skylake_avx512), Python 2.7.5
See https://gist.github.com/ade155bd5ef6798df18f7422ee978316 for a full test report.

**Comment by smoors** [comment]
@boegel I did a small test and this version seems to work with the MPI version in intel/2020a.
However, I get this message at startup, apparently I_MPI_MPD_TMPDIR is no longer supported:
"""
> [0] MPI startup(): I_MPI_MPD_TMPDIR environment variable is not supported.
> [0] MPI startup(): Similar variables:
>          I_MPI_TMPDIR
> [0] MPI startup(): To check the list of supported variables, use the impi_info utility or refer to https://software.intel.com/en-us/mpi-library/documentation/get-started.
"""

**Comment by boegel** [comment]
@smoors Please open an issue at https://github.com/hpcugent/vsc-mympirun/issues for that, this is not a blocker for this PR imho...

**Comment by lexming** [comment]
Test report by @lexming
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
node369.hydra.os - Linux centos linux 7.7.1908, x86_64, Intel(R) Xeon(R) Gold 6148 CPU @ 2.40GHz, Python 2.7.5
See https://gist.github.com/257d06978ed6e54bbe5e988be3712901 for a full test report.

**Comment by lexming** [comment]
Test report by @lexming
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
node127.hydra.os - Linux centos linux 7.7.1908, x86_64, Intel(R) Xeon(R) CPU E5-2680 v2 @ 2.80GHz, Python 2.7.5
See https://gist.github.com/87dfb1d2aeb6af6f5b64cca13b020c80 for a full test report.

**Comment by smoors** [comment]
@boegel ok done, see https://github.com/hpcugent/vsc-mympirun/issues/169

**Comment by lexming** [comment]
Going in since @smoors opened an issue upstream. Thanks @boegel !

**Pull request merged**
