### PR TITLE
{numlib}[foss/2022.05] HPL v2.3 (incl. FFTW.MPI v3.3.10 + ScaLAPACK v2.2.0)

### PR DESCRIPTION
**Pull request by bartoldeman**
(created using `eb --new-pr`)

requires:
* https://github.com/easybuilders/easybuild-easyblocks/pull/2724

### CODE REVIEW

**Comment by bartoldeman** [comment]
@kehoste some comments on FFTW.MPI.

This is doing everything in the easyconfig, but some of it could be moved to the easyblock.
Do you prefer in that case a seperate `EB_FFTW_period_MPI` easyblock, or use if statements in `EB_FFTW`?

The way it works is that it builds serial and MPI components (since in the build MPI depends on serial) but not threads/openmpi, and no quadruple since quadruple precision isn't supported by MPI.

Then it removes almost everything except for the MPI libraries (libfftw3*_mpi*) and all headers, i.e.:
```$ ls -l $EBROOTFFTWMPI/include
total 205
-rw-r--r-- 1 oldeman oldeman  2447 May 25 14:44 fftw3.f
-rw-r--r-- 1 oldeman oldeman 55032 May 25 14:44 fftw3.f03
-rw-r--r-- 1 oldeman oldeman 31986 May 25 14:44 fftw3.h
-rw-r--r-- 1 oldeman oldeman 27203 May 25 14:44 fftw3l.f03
-rw-r--r-- 1 oldeman oldeman 18678 May 25 14:44 fftw3l-mpi.f03
-rw-r--r-- 1 oldeman oldeman 36969 May 25 14:44 fftw3-mpi.f03
-rw-r--r-- 1 oldeman oldeman  9624 May 25 14:44 fftw3-mpi.h
-rw-r--r-- 1 oldeman oldeman 25902 May 25 14:44 fftw3q.f03
```
vs
```
$ ls -l $EBROOTFFTW/include
total 141
-rw-r--r-- 1 oldeman oldeman  2447 May 11 14:27 fftw3.f
-rw-r--r-- 1 oldeman oldeman 55032 May 11 14:27 fftw3.f03
-rw-r--r-- 1 oldeman oldeman 31986 May 11 14:27 fftw3.h
-rw-r--r-- 1 oldeman oldeman 27203 May 11 14:27 fftw3l.f03
-rw-r--r-- 1 oldeman oldeman 25902 May 11 14:27 fftw3q.f03
```

Why keep all headers thereby duplicating some headers in the serial MPI, but don't do the same for libraries you ask?

Well first of all libraries are needed both at runtime and compile time, even if the libraries are 100% identical it's confusing to have them in two different paths.

For headers this is not as important since it's compile time only, and secondly, having all the headers under a single include path simplifies some cases, e.g. `FFT_INC_DIR` can only be a single path.

Framework PR https://github.com/easybuilders/easybuild-framework/pull/4012 sets FFT_INC_DIR to the MPI path only if MPI is used. Now the FFTW (non-MPI) module will also set the non-MPI path in `CPATH`, but this only helps C, not Fortran.

During link time the non-MPI path is in `LIBRARY_PATH` so the library `-lfftw` will be found anyway, unless the build procedure uses special tricks (which should be rare and easily worked around).

**Comment by bartoldeman** [comment]
Now depends on https://github.com/easybuilders/easybuild-easyblocks/pull/2724 for custom easyblock for FFTW.MPI

**Comment by bartoldeman** [comment]
@boegelbot Please test @ generoso
EB_ARGS='--include-easyblocks-from-pr 2724'

**Comment by SebastianAchilles** [comment]
@boegelbot please test @ jsc-zen2
EB_ARGS='--include-easyblocks-from-pr 2724'

**Comment by SebastianAchilles** [comment]
Test report by @sebastianachilles
Using easyblocks from PR(s) https://github.com/easybuilders/easybuild-easyblocks/pull/2724
**SUCCESS**
Build succeeded for 4 out of 4 (4 easyconfigs in total)
zen2-ubuntu-eb - Linux Ubuntu 22.04, x86_64, AMD EPYC 7452 32-Core Processor (zen2), Python 3.10.4
See https://gist.github.com/04968d8e4643818460b104e6c3dc9289 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
Using easyblocks from PR(s) https://github.com/easybuilders/easybuild-easyblocks/pull/2724
**SUCCESS**
Build succeeded for 4 out of 4 (4 easyconfigs in total)
node3502.doduo.os - Linux RHEL 8.4, x86_64, AMD EPYC 7552 48-Core Processor (zen2), Python 3.6.8
See https://gist.github.com/1b957895d99047b7371fa29d58868dc2 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
Using easyblocks from PR(s) https://github.com/easybuilders/easybuild-easyblocks/pull/2724
**SUCCESS**
Build succeeded for 4 out of 4 (4 easyconfigs in total)
node3108.skitty.os - Linux RHEL 8.4, x86_64, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz, Python 3.6.8
See https://gist.github.com/74aa527972a80682c88c43af01bef324 for a full test report.

**Comment by boegel** [comment]
@boegelbot Please test @ generoso
EB_ARGS='--include-easyblocks-from-pr 2724'

**Review by boegel — APPROVED** [review]
lgtm

**Comment by boegel** [comment]
Going in, thanks @bartoldeman!

**Pull request merged**
