### PR TITLE
{bio}[foss/2020b] shovill v1.1.0, Velvet v1.2.10, FLASH v1.2.11, ... w/ Python 3.8.6

### PR DESCRIPTION
**Pull request by verdurin**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by verdurin** [comment]
Not yet found any indication that it works with the newer version of `FLASH`. Also, stuck with `Python/2.7.18` thanks to `MEGAHIT`.

**Comment by verdurin** [comment]
I don't understand what that "conflicts" test is reporting...

**Comment by branfosj** [comment]
> I don't understand what that "conflicts" test is reporting...

`KMC` depends on Python 3.8.6. `shovill` depends on Python 2.7.18, but has `KMC` as a dependency as well.

**Comment by verdurin** [comment]
I don't understand what that "conflicts" test is reporting...

> > I don't understand what that "conflicts" test is reporting...
> 
> `KMC` depends on Python 3.8.6. `shovill` depends on Python 2.7.18, but has `KMC` as a dependency as well.

I could add a Python 3.8.6 build of `shovill` but it won't work, as far as I can tell. Open to suggestions...

**Comment by nortex** [comment]
Has anyone succeeded compiling shovill v1.1.0 ? will there be easyconfig anytime ?

**Review by jfgrimm — COMMENTED** [review]
As decided in issue #16330, we have deprecated the use of `True` to signify a system-toolchain dependency (#16384), in favour of the more intuitive `SYSTEM` template constant. Due to the change in the test suite, please run `eb --sync-pr-with-develop 13801` and update the PR to use `SYSTEM` instead.

**Comment by boegel** [comment]
closing this since `foss/2020b` is deprecated, see https://docs.easybuild.io/policies/toolchains

**Pull request closed without merging**
