### PR TITLE
{bio}[foss/2023b] GROMACS v2024.4 w/ CUDA 12.4.0

### PR DESCRIPTION
**Pull request by bedroge**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by bedroge** [comment]
@boegelbot please test @ jsc-zen3-a100
CORE_CNT=16

**Comment by bedroge** [comment]
> Test report by @boegelbot **FAILED** Build succeeded for 0 out of 1 (1 easyconfigs in total) jsczen3g1.int.jsc-zen3.fz-juelich.de - Linux Rocky Linux 9.4, x86_64, AMD EPYC-Milan Processor (zen3), 1 x NVIDIA NVIDIA A100 80GB PCIe, 555.42.06, Python 3.9.18 See https://gist.github.com/boegelbot/24f794ba165927e21003f359aeaa4f3d for a full test report.


```
Fatal error:
wrong string length 0 for string buf (source
/tmp/boegelbot/GROMACS/2024.3/foss-2023b-CUDA-12.4.0/gromacs-2024.3/src/gromacs/fileio/gmxfio_xdr.cpp,
line 890)
```

**Comment by bedroge** [comment]
@boegelbot please test @ jsc-zen3-a100
CORE_CNT=16

**Review by boegel — APPROVED** [review]
lgtm

**Comment by boegel** [comment]
Test report by @boegel
**FAILED**
Build succeeded for 0 out of 1 (1 easyconfigs in total)
node3900.accelgor.os - Linux RHEL 8.8, x86_64, AMD EPYC 7413 24-Core Processor, 1 x NVIDIA NVIDIA A100-SXM4-80GB, 545.23.08, Python 3.6.8
See https://gist.github.com/boegel/7844f12ec11f2538a1606f946aa31eec for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**FAILED**
Build succeeded for 0 out of 1 (1 easyconfigs in total)
node3301.joltik.os - Linux RHEL 8.8, x86_64, Intel(R) Xeon(R) Gold 6242 CPU @ 2.80GHz, 1 x NVIDIA Tesla V100-SXM2-32GB, 545.23.08, Python 3.6.8
See https://gist.github.com/boegel/0101c64327caf4ddc8e16177fda92aa7 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**FAILED**
Build succeeded for 0 out of 1 (1 easyconfigs in total)
node3904.accelgor.os - Linux RHEL 8.8, x86_64, AMD EPYC 7413 24-Core Processor, 1 x NVIDIA NVIDIA A100-SXM4-80GB, 545.23.08, Python 3.6.8
See https://gist.github.com/boegel/bafc4ab2f0149f9ff7769b1b4e998257 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**FAILED**
Build succeeded for 0 out of 1 (1 easyconfigs in total)
node3904.accelgor.os - Linux RHEL 8.8, x86_64, AMD EPYC 7413 24-Core Processor, 4 x NVIDIA NVIDIA A100-SXM4-80GB, 545.23.08, Python 3.6.8
See https://gist.github.com/boegel/e9a9cce0d9b57369b20447431e26b4f8 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**FAILED**
Build succeeded for 0 out of 1 (1 easyconfigs in total)
node3305.joltik.os - Linux RHEL 8.8, x86_64, Intel(R) Xeon(R) Gold 6242 CPU @ 2.80GHz, 1 x NVIDIA Tesla V100-SXM2-32GB, 545.23.08, Python 3.6.8
See https://gist.github.com/boegel/2b85b3f4a6c24216735ea10eb144a30e for a full test report.

**Comment by boegel** [comment]
I keep seeing hang in the GROMACS test suite on our GPU systems, even when running outside of Slurm environment (and unsetting `$OMP_PROC_BIND`).

https://gitlab.com/gromacs/gromacs/-/issues/5185 suggests that this may be due to a bug in GROMACS, so I've opened a detailed bug report at https://gitlab.com/gromacs/gromacs/-/issues/5187

cc @mabraham

**Comment by bedroge** [comment]
Test report by @bedroge
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
gpu1 - Linux Rocky Linux 8.9, x86_64, Intel(R) Xeon(R) Gold 6150 CPU @ 2.70GHz (skylake_avx512), 1 x NVIDIA GRID V100D-32Q, 535.161.07, Python 3.6.8
See https://gist.github.com/bedroge/1b32bbf8132b3f547e97e678a1153db4 for a full test report.

**Comment by bedroge** [comment]
@boegelbot please test @ jsc-zen3-a100
CORE_CNT=16

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
node3306.joltik.os - Linux RHEL 9.4, x86_64, Intel(R) Xeon(R) Gold 6242 CPU @ 2.80GHz (cascadelake), 1 x NVIDIA Tesla V100-SXM2-32GB, 555.42.06, Python 3.9.18
See https://gist.github.com/boegel/a060a366c3acc7a3a116e879ea069e19 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**FAILED**
Build succeeded for 0 out of 1 (1 easyconfigs in total)
node3902.accelgor.os - Linux RHEL 9.4, x86_64, AMD EPYC 7413 24-Core Processor (zen3), 1 x NVIDIA NVIDIA A100-SXM4-80GB, 555.42.06, Python 3.9.18
See https://gist.github.com/boegel/7cf9c45bc9d4651b61e0ae9a1bfe2ce4 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
node3902.accelgor.os - Linux RHEL 9.4, x86_64, AMD EPYC 7413 24-Core Processor (zen3), 1 x NVIDIA NVIDIA A100-SXM4-80GB, 555.42.06, Python 3.9.18
See https://gist.github.com/boegel/a986672e84135c0f2b5446c7496071c1 for a full test report.

**Comment by boegel** [comment]
@bedroge CI is failing now because the easyconfig file needs to be renamed to `GROMACS-2024.4-foss-2023b-CUDA-12.4.0.eb` after the version bump , I'll push in the fix for that...

**Review by boegel — APPROVED** [review]
lgtm

**Comment by boegel** [comment]
Going in, thanks @bedroge!

**Pull request merged**
