### PR TITLE
use upstream patch for symbol compatibility in XZ 5.2.5

### LINKED ISSUE #14991: XZ: patch for symbols still needed?
In https://github.com/easybuilders/easybuild-easyconfigs/issues/4036 an issue was identified with CentOS 7.3 due to certain missing version symbols in the XZ library. A [patch](https://github.com/easybuilders/easybuild-easyconfigs/blob/develop/easybuild/easyconfigs/x/XZ/XZ-5.2.2_compat-libs.patch) was then included in the XZ easyconfigs that removes the `XZ_5.2` symbol, tweaks the `XZ_5.0` symbol, and adds `XZ_5.1.2alpha` and `XZ_5.2.2` symbols. This patch is still applied in the most current easyconfig, for XZ 5.2.5. This patch have fixed the issue for CentOS, but on RHEL 8.4 this now causes an issue with system-wide libarchive.so (and we had it on our earlier system as well):

```
snellius paulm@int3 12:22 ~$ cmake --version
cmake version 3.18.2

CMake suite maintained and supported by Kitware (kitware.com/cmake).
snellius paulm@int3 12:22 ~$ module load 2021 XZ/5.2.5-GCCcore-10.3.0
snellius paulm@int3 12:23 ~$ cmake --version
cmake: /sw/arch/Centos8/EB_production/2021/software/XZ/5.2.5-GCCcore-10.3.0/lib/liblzma.so.5: version `XZ_5.2' not found (required by /lib64/libarchive.so.13)
```

This is caused by the system liblzma.so.5 including the symbols for 5.0 and 5.2:

```
snellius paulm@int3 12:25 ~$ nm -D /lib64/liblzma.so.5 | grep XZ
0000000000000000 A XZ_5.0
0000000000000000 A XZ_5.2
```

While the (patched) EB library is missing the XZ_5.2 one:

```
snellius paulm@int3 12:25 ~$ nm -D /sw/arch/Centos8/EB_production/2021/software/XZ/5.2.5-GCCcore-10.3.0/lib/liblzma.so.5 | grep XZ
0000000000000000 A XZ_5.0
0000000000000000 A XZ_5.1.2alpha
0000000000000000 A XZ_5.2.2
```

Having system-wide binaries getting broken due loading an EB module isn't very nice. In this case I wonder if the XZ symbol patch is still needed? Also, because removing the `XZ_5.2` symbol as it does, while leaving `XZ_5.0` in place, feels very wrong.

### PR DESCRIPTION
**Pull request by branfosj**
(created using `eb --new-pr`)

fixes #14991

See https://github.com/easybuilders/easybuild-easyconfigs/issues/14991#issuecomment-1247353981, with the patch being https://git.tukaani.org/?p=xz.git;a=commitdiff;h=31d80c6b261b24220776dfaeb8a04f80f80e0a24 which is the 5.2.x branch version of the commits linked in that message.

With the old patch (OS `cmake`):
```
$ cmake --version
cmake: symbol lookup error: /lib64/libarchive.so.13: undefined symbol: lzma_cputhreads, version XZ_5.2
```

With this patch:
```
$ cmake --version
cmake version 3.20.2

CMake suite maintained and supported by Kitware (kitware.com/cmake).
```

### CODE REVIEW

**Comment by branfosj** [comment]
Test report by @branfosj
**SUCCESS**
Build succeeded for 5 out of 5 (5 easyconfigs in total)
bear-pg0105u03a.bear.cluster - Linux RHEL 8.6, x86_64, Intel(R) Xeon(R) Platinum 8360Y CPU @ 2.40GHz (icelake), Python 3.6.8
See https://gist.github.com/branfosj/bcd782d297ddb748755fe7422e2f1b4f for a full test report.

**Comment by SebastianAchilles** [comment]
Test report by @sebastianachilles
**FAILED**
Build succeeded for 0 out of 4 (4 easyconfigs in total)
zen2-rockylinux-88 - Linux Rocky Linux 8.8, x86_64, AMD EPYC 7452 32-Core Processor (zen2), Python 3.6.8
See https://gist.github.com/SebastianAchilles/3eefb58026037faf563061460e8318fb for a full test report.

**Comment by SebastianAchilles** [comment]
I think a `Autotools` builddependecy is missing.

**Comment by jfgrimm** [comment]
I'm also seeing failures, likewise autotools-related

**Comment by branfosj** [comment]
Argh, we are stuck with a circular dependency :(

**Comment by jfgrimm** [comment]
do we need system-level autotools?

**Comment by branfosj** [comment]
@SebastianAchilles and @jfgrimm can you retest?

**Comment by branfosj** [comment]
Test report by @branfosj
**SUCCESS**
Build succeeded for 5 out of 5 (5 easyconfigs in total)
bear-pg0105u03a.bear.cluster - Linux RHEL 8.6, x86_64, Intel(R) Xeon(R) Platinum 8360Y CPU @ 2.40GHz (icelake), Python 3.6.8
See https://gist.github.com/branfosj/11080c0d49cf31b142f9875a9b4259c2 for a full test report.

**Comment by jfgrimm** [comment]
I've got a test report in progress that looks good so far

**Comment by SebastianAchilles** [comment]
Test report by @sebastianachilles
**SUCCESS**
Build succeeded for 4 out of 4 (4 easyconfigs in total)
zen2-rockylinux-88 - Linux Rocky Linux 8.8, x86_64, AMD EPYC 7452 32-Core Processor (zen2), Python 3.6.8
See https://gist.github.com/SebastianAchilles/dfde9f19c827269daab58267d359c740 for a full test report.

**Comment by SebastianAchilles** [comment]
Test report by @sebastianachilles
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
zen2-ubuntu-2304 - Linux Ubuntu 23.04 (Lunar Lobster), x86_64, AMD EPYC 7452 32-Core Processor (zen2), Python 3.11.2
See https://gist.github.com/SebastianAchilles/3193b512e881138a968e096a19ceab6f for a full test report.

**Comment by SebastianAchilles** [comment]
Test report by @sebastianachilles
**SUCCESS**
Build succeeded for 6 out of 6 (6 easyconfigs in total)
bwd-rockylinux-92 - Linux Rocky Linux 9.2 (Blue Onyx), x86_64, Intel(R) Core(TM) i7-6900K CPU @ 3.20GHz (broadwell), 2 x NVIDIA NVIDIA GeForce GTX 1060 6GB, 525.105.17, Python 3.9.16
See https://gist.github.com/SebastianAchilles/2a1bdd44164d86c22fe2848fa5d31cb8 for a full test report.

**Comment by branfosj** [comment]
Test report by @branfosj
**SUCCESS**
Build succeeded for 13 out of 13 (6 easyconfigs in total)
bear-pg0105u03a.bear.cluster - Linux RHEL 8.6, x86_64, Intel(R) Xeon(R) Platinum 8360Y CPU @ 2.40GHz (icelake), Python 3.6.8
See https://gist.github.com/branfosj/067b208398a3c18541dc97299e40307e for a full test report.

**Comment by SebastianAchilles** [comment]
Test report by @sebastianachilles
**SUCCESS**
Build succeeded for 5 out of 5 (5 easyconfigs in total)
skl-centos-79 - Linux CentOS Linux 7.9.2009, x86_64, Intel(R) Core(TM) i7-8700 CPU @ 3.20GHz (skylake), Python 3.6.8
See https://gist.github.com/SebastianAchilles/2c18994811ca82f505a994bcd2ecee38 for a full test report.

**Comment by jfgrimm** [comment]
Test report by @jfgrimm
**SUCCESS**
Build succeeded for 15 out of 15 (6 easyconfigs in total)
node063.pri.viking.alces.network - Linux CentOS Linux 7.9.2009, x86_64, Intel(R) Xeon(R) Gold 6138 CPU @ 2.00GHz (skylake_avx512), Python 3.6.8
See https://gist.github.com/jfgrimm/ed4d7c2413e89f9561c46e4d0491511d for a full test report.

**Review by jfgrimm — APPROVED** [review]
lgtm

**Comment by branfosj** [comment]
@boegelbot please test @ generoso

**Comment by branfosj** [comment]
@boegelbot please test @ jsc-zen2

**Pull request merged**
