### PR TITLE
{bio}[GCC/10.3.0] gffread v0.12.6

### PR DESCRIPTION
**Pull request by SethosII**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by SethosII** [comment]
Test report by @SethosII
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
ribnode012 - Linux Ubuntu 20.04, x86_64, Intel(R) Xeon(R) CPU E5-2640 v2 @ 2.00GHz, Python 3.8.10
See https://gist.github.com/a3a822385fe03c840fd656364afb7747 for a full test report.

**Comment by verdurin** [comment]
Test report by @verdurin
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
nuc.lan - Linux Fedora 33, x86_64, Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz, Python 3.9.5
See https://gist.github.com/6638cecd82a390b7d242ce14cd0c3425 for a full test report.

**Comment by verdurin** [comment]
@boegelbot please test @ generoso

**Comment by lexming** [comment]
Test report by @lexming
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
node379.hydra.os - Linux centos linux 7.9.2009, x86_64, Intel(R) Xeon(R) Gold 6148 CPU @ 2.40GHz, Python 2.7.5
See https://gist.github.com/cece4027bb558deb2931104e8efcc762 for a full test report.

**Comment by lexming** [comment]
Test report by @lexming
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
node115.hydra.os - Linux centos linux 7.9.2009, x86_64, Intel(R) Xeon(R) CPU E5-2680 v2 @ 2.80GHz, Python 2.7.5
See https://gist.github.com/61fdcfe07003fe359eeafd0919b98775 for a full test report.

**Review by lexming — APPROVED** [review]
@SethosII Thanks for the update. I made a minor additional change to this PR to avoid the need for a `modextrapath` by copying `gffread` into `bin`. I hope that you don't mind.

LGTM

**Comment by lexming** [comment]
Going in, thanks @SethosII !

**Comment by SethosII** [comment]
@lexming No problem, thanks!

**Pull request merged**
