### PR TITLE
{geo}[foss/2023a] CESM-deps v2

### PR DESCRIPTION
**Pull request by lexming**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by lexming** [comment]
@boegelbot: please test @ generoso

**Comment by laraPPr** [comment]
Test report by @laraPPr
**FAILED**
Build succeeded for 0 out of 1 (1 easyconfigs in total)
node5006.dodrio.os - Linux RHEL 8.8 (Ootpa), x86_64, AMD EPYC 7H12 64-Core Processor, Python 3.11.3
See https://gist.github.com/laraPPr/4bca5a0f4eee170dd114b1637e3db5ff for a full test report.

**Comment by laraPPr** [comment]
Test report by @laraPPr
**SUCCESS**
Build succeeded for 7 out of 7 (1 easyconfigs in total)
node5006.dodrio.os - Linux RHEL 8.8 (Ootpa), x86_64, AMD EPYC 7H12 64-Core Processor, Python 3.11.3
See https://gist.github.com/laraPPr/08b03251aec2488564fe0799623007da for a full test report.

**Review by boegel — APPROVED** [review]
lgtm

**Pull request merged**
