### PR TITLE
{vis}[system] Fiji v20170530, Fiji v20191119-2057

### PR DESCRIPTION
**Pull request by lexming**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by lexming** [comment]
Test report by @lexming
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in this PR)
login2.cerberus.os - Linux centos linux 7.6.1810, Intel(R) Xeon(R) Gold 6126 CPU @ 2.60GHz, Python 2.7.5
See https://gist.github.com/985287cf5ff2722cd1b528d4eba86909 for a full test report.

**Comment by lexming** [comment]
The checksum for `fiji/20190803` is quite useless because there are no sane releases of its sources. The only available tarball is on a constantly changing *latest* version. So it is very probable that you won't be able to test it.

**Comment by lexming** [comment]
Test report by @lexming
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in this PR)
login2.cerberus.os - Linux centos linux 7.6.1810, Intel(R) Xeon(R) Gold 6126 CPU @ 2.60GHz, Python 2.7.5
See https://gist.github.com/d3cae64aeec0320b40fbfa94dfd54185 for a full test report.

**Comment by smoors** [comment]
Test report by @smoors
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in this PR)
node321.hydra.os - Linux centos linux 7.6.1810, Intel(R) Xeon(R) Gold 6148 CPU @ 2.40GHz, Python 2.7.5
See https://gist.github.com/8ae86bbf05a08b2fd7e254d6b8941bdd for a full test report.

**Comment by boegel** [comment]
@lexming Is it worth contacting the authors about this malpractice?

While the easyconfig file for `fiji` 20190803 will work for now, it won't anymore when they do an in-place update...

**Comment by lexming** [comment]
@boegel There is an issue opened for `fiji` about the lack of reproducible releases (https://github.com/fiji/fiji/issues/223), but it has not received any traction sadly.
So I propose to stick to `fiji/20170530` until that issue is fixed. I have added some comments in the easyconfig in case anybody needs the latest version.

**Comment by lexming** [comment]
Test report by @lexming
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
login2.cerberus.os - Linux centos linux 7.6.1810, Intel(R) Xeon(R) Gold 6126 CPU @ 2.60GHz, Python 2.7.5
See https://gist.github.com/991eb336ea727b3acf87e013f7c92f6f for a full test report.

**Comment by smoors** [comment]
@lexming there is now an archive available here:
https://downloads.imagej.net/fiji/archive/

can you update the easyconfig with a more recent version?

**Comment by lexming** [comment]
@smoors fixed, thanks for the update :+1:

**Comment by lexming** [comment]
Test report by @lexming
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in this PR)
login1.cerberus.os - Linux centos linux 7.6.1810, Intel(R) Xeon(R) Gold 6126 CPU @ 2.60GHz, Python 2.7.5
See https://gist.github.com/a0a1f0d13713aff4e138a09e1a9dbe7e for a full test report.

**Comment by smoors** [comment]
Going in, thanks @lexming!

**Pull request merged**
