### PR TITLE
{system}[system/system] CUDA v12.1.0

### PR DESCRIPTION
**Pull request by robogast**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by robogast** [comment]
Test report by @robogast
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
gcn3.local.snellius.surf.nl - Linux Rocky Linux 8.7, x86_64, Intel(R) Xeon(R) Platinum 8360Y CPU @ 2.40GHz, 4 x NVIDIA NVIDIA A100-SXM4-40GB, 515.86.01, Python 3.6.8
See https://gist.github.com/4c83aaa72e3f4126a4097f5441cfbf30 for a full test report.

**Review by casparvl — APPROVED** [review]
Standard update, lgtm!

**Comment by casparvl** [comment]
@boegelbot please test @ generoso

**Comment by casparvl** [comment]
@boegelbot please test @ jsc-zen2

**Comment by casparvl** [comment]
Going in, thanks @robogast!

**Pull request merged**
