### PR TITLE
fix source URLs for ParMGridGen easyconfigs

### LINKED ISSUE #9837: ParMGridGen download broken
So, ParMGridGen homepage seems to be gone. Can't be downloaded from there anymore either.

I got a suggestion that this link works:
http://www.mgnet.org/mgnet/Codes/parmgridgen/ParMGridGen-1.0.tar.gz
which, while it works, doesn't seem super-reliable either, considering the dead links on http://www.mgnet.org/mgnet-codes-parmgridgen.html

I also found https://github.com/mrklein/ParMGridGen, though, it doesn't have a 1.0 release https://github.com/mrklein/ParMGridGen/issues/2

Should we just switch to that working link for now?

### PR DESCRIPTION
**Pull request by boegel**
(created using `eb --new-pr`)
(fixes #9837)

### CODE REVIEW

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 4 out of 4 (4 easyconfigs in this PR)
node2428.golett.os - Linux centos linux 7.7.1908, Intel(R) Xeon(R) CPU E5-2680 v3 @ 2.50GHz, Python 2.7.5
See https://gist.github.com/c33ab1e306a208914e50cbac5f9e1a41 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 4 out of 4 (4 easyconfigs in this PR)
node2428.golett.os - Linux centos linux 7.7.1908, Intel(R) Xeon(R) CPU E5-2680 v3 @ 2.50GHz, Python 2.7.5
See https://gist.github.com/b31fe06f14650b5f4110c40af2e53f7a for a full test report.

**Comment by zao** [comment]
Test report by @zao
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
freja - Linux ubuntu 18.04, Intel(R) Core(TM) i7-8700K CPU @ 3.70GHz, Python 2.7.17
See https://gist.github.com/ef3046a3a8d5c117e0be88a15050fdd8 for a full test report.

**Comment by zao** [comment]
Going in, thanks @boegel!

**Pull request merged**
