### PR TITLE
CLISP: Update PCRE version to 8.44

### PR DESCRIPTION
**Pull request by akesandgren**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by lexming** [comment]
Test report by @lexming
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
login2.cerberus.os - Linux centos linux 7.7.1908, Intel(R) Xeon(R) Gold 6126 CPU @ 2.60GHz, Python 2.7.5
See https://gist.github.com/9357ac25a985fc00f69d9d3296d5c436 for a full test report.

**Comment by zao** [comment]
Test report by @zao
**SUCCESS**
Build succeeded for 2 out of 2 (1 easyconfigs in this PR)
freja - Linux ubuntu 18.04, Intel(R) Core(TM) i7-8700K CPU @ 3.70GHz, Python 2.7.17
See https://gist.github.com/f72c7749c09580f542b51e8ee4497d60 for a full test report.

**Comment by lexming** [comment]
Going in, thanks @akesandgren !

**Comment by akesandgren** [comment]
Test report by @akesandgren
**SUCCESS**
Build succeeded for 4 out of 4 (1 easyconfigs in this PR)
generoso - Linux centos linux 7.6.1810, Intel(R) Xeon(R) CPU E5-2660 v4 @ 2.00GHz, Python 3.6.8
See https://gist.github.com/47fb9d258370f5070e40d8644f3c66db for a full test report.

**Comment by akesandgren** [comment]
Need to make a single PR for the PCRE 8.43 -> 8.44 update, closing

**Comment by akesandgren** [comment]
Replaced with #10169

**Pull request closed without merging**
