### PR TITLE
rename libpsml for consistency with libPSML

### PR DESCRIPTION
**Pull request by branfosj**
for https://github.com/easybuilders/easybuild-easyconfigs/issues/11824

### CODE REVIEW

**Comment by branfosj** [comment]
Test report by @branfosj
**SUCCESS**
Build succeeded for 8 out of 8 (8 easyconfigs in total)
bear-pg0211u08b.bear.cluster - Linux RHEL 8.6, x86_64, Intel(R) Xeon(R) Gold 6248 CPU @ 2.50GHz (cascadelake), Python 3.6.8
See https://gist.github.com/d3ea4614496bae5919c5ce0df4d94bfa for a full test report.

**Comment by branfosj** [comment]
The test report covers all apart from the `2016b` and `2017a` easyconfigs.

**Comment by Micket** [comment]
Right so this is probably the most controversial change. Though it isn't used as a dependency in other stuff much, someone still felt the need to update it to pretty recent GCCcore's, so i assume it's used by users in some way still?

Probably still alright to rename it i.m.h.o. to just get this issue over with

**Comment by branfosj** [comment]
If we do the change the other way round (#17353) we alter fewer easyconfigs, but the `libPSML` capitalisation is also a dependency. These are recent enough easyconfigs that we cannot use the archive approach.

So, yes this is not a great option. However, I see no better one to avoid this `libpsml` / `libPSML` problem remaining.

**Comment by jfgrimm** [comment]
@boegelbot please test @ generoso

**Comment by Micket** [comment]
I think the oldest ones here is to old for generoso as well

**Comment by jfgrimm** [comment]
> I think the oldest ones here is to old for generoso as well

whoops, looks like the oldest toolchain it has is 2018b...

**Comment by Micket** [comment]
@boegelbot please test @ generoso
EB_ARGS="libPSML-1.1.10-GCC-10.3.0.eb libPSML-1.1.10-GCC-10.2.0.eb libPSML-1.1.10-GCC-11.2.0.eb libPSML-1.1.10-iccifort-2020.4.304.eb libPSML-1.1.10-intel-compilers-2021.2.0.eb libPSML-1.1.10-intel-compilers-2021.4.0.eb ESL-Bundle-0.6.1-intel-2020b.eb ESL-Bundle-0.6.1-foss-2020b.eb"

**Comment by branfosj** [comment]
@boegelbot please test @ generoso
EB_ARGS="--filter-ecs=*2016b*,*2017a*"

**Review by lexming — APPROVED** [review]
LGTM

**Comment by lexming** [comment]
Going in, thanks @branfosj !

**Pull request merged**
