### PR TITLE
{devel}[GCCcore/6.4.0] likwid v4.3.2

### PR DESCRIPTION
**Pull request by Helios07**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by pescobar** [comment]
Test report by @pescobar
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
login20.cluster.bc2.ch - Linux centos linux 7.3.1611, Intel(R) Xeon(R) CPU E5-2670 v2 @ 2.50GHz, Python 2.7.5
See https://gist.github.com/62ebda95b77ffbb5af951ce3178bf1b9 for a full test report.

**Comment by boegel** [comment]
@Helios07 Please take a look at the differences with the easyconfig that got merged via #6320, I overlooked this... `eb --review-pr 6320` may come in handy here, see also https://easybuild.readthedocs.io/en/latest/Contributing.html#contributing-review-process-review-pr

**Comment by Helios07** [comment]
The URL of the project is outdated in the other config file. Apart from that, we may close this one, the patch does not seem to be necessary.

**Comment by akesandgren** [comment]
Homepage info updated in PR #8846
Closing this one

**Pull request closed without merging**
