### PR TITLE
{bio}[GCC/11.2.0] Jasmine v1.1.4

### PR DESCRIPTION
**Pull request by zemu-unile**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by zemu-unile** [comment]
depends on #14788

**Comment by migueldiascosta** [comment]
@boegelbot please test @ generoso

**Review by migueldiascosta — APPROVED** [review]
lgtm

**Comment by migueldiascosta** [comment]
Going in, thanks @zemu-unile!

**Pull request merged**
