### PR TITLE
in-place update of TensorFlow 2.3.0 easyconfigs to version 2.3.1

### PR DESCRIPTION
**Pull request by Flamefire**
Contains security fixes
Removes the superflous keras-applications package and scipy package

edit (@boegel): OK because TensorFlow 2.3.0 easyconfigs have only been merged very recently into `develop` via #11040...

### CODE REVIEW

**Comment by Flamefire** [comment]
Test report by @Flamefire
**FAILED**
Build succeeded for 2 out of 3 (3 easyconfigs in this PR)
taurusml3 - Linux RHEL 7.6, POWER, 8335-GTX, Python 2.7.5
See https://gist.github.com/cfd01771b6106380b7f6f37875fdcc44 for a full test report.

**Comment by Flamefire** [comment]
Test report by @Flamefire
**SUCCESS**
Build succeeded for 3 out of 3 (3 easyconfigs in this PR)
taurusi5196.taurus.hrsk.tu-dresden.de - Linux RHEL 7.8, x86_64, Intel(R) Xeon(R) CPU E5-2680 v3 @ 2.50GHz, Python 2.7.5
See https://gist.github.com/3ac6fe27d1d954b0ad727964feffd717 for a full test report.

**Comment by boegel** [comment]
@Flamefire Again trouble on POWER?

**Comment by Flamefire** [comment]
Yes -.- Although it looks like a flake in the filesystem. Restarted the build but it's been running for 2 hrs now

**Comment by lexming** [comment]
Test report by @lexming
**FAILED**
Build succeeded for 6 out of 9 (3 easyconfigs in this PR)
node375.hydra.os - Linux centos linux 7.7.1908, x86_64, Intel(R) Xeon(R) Gold 6148 CPU @ 2.40GHz, Python 2.7.5
See https://gist.github.com/6774d91ddf80b76e8885b23fe77443bf for a full test report.

**Comment by boegel** [comment]
@boegelbot please test @ generoso

**Comment by Flamefire** [comment]
@lexming please rebuild double-conversion

**Comment by Flamefire** [comment]
Test report by @Flamefire
**FAILED**
Build succeeded for 2 out of 3 (3 easyconfigs in this PR)
taurusml21 - Linux RHEL 7.6, POWER, 8335-GTX, Python 2.7.5
See https://gist.github.com/ea1fa002035b7dee585a72be9bbb4986 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**FAILED**
Build succeeded for 9 out of 12 (3 easyconfigs in this PR)
node3162.skitty.os - Linux centos linux 7.8.2003, x86_64, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz, Python 3.6.8
See https://gist.github.com/f721507b109546e0009afd0e44fac959 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 3 out of 3 (3 easyconfigs in this PR)
node3407.kirlia.os - Linux centos linux 7.8.2003, x86_64, Intel(R) Xeon(R) Gold 6240 CPU @ 2.60GHz (cascadelake), Python 2.7.5
See https://gist.github.com/1baa102fa06b0afc4d985b4c6148334e for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 3 out of 3 (3 easyconfigs in this PR)
node2706.swalot.os - Linux centos linux 7.8.2003, x86_64, Intel(R) Xeon(R) CPU E5-2660 v3 @ 2.60GHz (haswell), Python 2.7.5
See https://gist.github.com/d57da72dce96f15e3ee67aef7c12a3d2 for a full test report.

**Comment by lexming** [comment]
Test report by @lexming
**FAILED**
Build succeeded for 1 out of 3 (3 easyconfigs in this PR)
node157.hydra.os - Linux centos linux 7.7.1908, x86_64, Intel(R) Xeon(R) CPU E5-2680 v2 @ 2.80GHz, Python 2.7.5
See https://gist.github.com/8838d994f39f4eb2a319fb642b47306d for a full test report.

**Comment by Flamefire** [comment]
@lexming 
> ModuleNotFoundError: No module named 'google.protobuf'

That is strange. You can try loading the build environment and check that this works? If it doesn't there is likely another `google` folder in your `PYTHONPATH`(`=/user/brussel/101/vsc10122/.local/easybuild-ivybridge/software/TensorFlow/2.3.1-foss-2019b-Python-3.7.4/lib/python3.7/site-packages:/user/brussel/101/vsc10122/.local/easybuild-ivybridge/software/TensorFlow/2.3.1-foss-2019b-Python-3.7.4/lib/python3.7/site-packages:/apps/brussel/CO7/ivybridge-ib/software/protobuf-python/3.10.0-foss-2019b-Python-3.7.4/lib/python3.7/site-packages:/apps/brussel/CO7/ivybridge-ib/software/h5py/2.10.0-foss-2019b-Python-3.7.4/lib/python3.7/site-packages:/apps/brussel/CO7/ivybridge-ib/software/SciPy-bundle/2019.10-foss-2019b-Python-3.7.4/lib/python3.7/site-packages:/apps/brussel/CO7/ivybridge-ib/software/Python/3.7.4-GCCcore-8.3.0/easybuild/python`)

Check each of those for a `google/__init__.py` which is what mostly prevents finding other google packages

**Comment by boegel** [comment]
@Flamefire Is this related to https://github.com/easybuilders/easybuild-easyconfigs/pull/11143?

@lexming Try re-installing `protobuf-python-3.10.0-fosscuda-2019b-Python-3.7.4.eb` and `protobuf-python-3.10.0-foss-2019b-Python-3.7.4.eb` with latest `develop` branch or EasyBuild v4.3.0?

**Comment by Flamefire** [comment]
Ah, yes exactly. That was the reason for the breaking change with the downloaded archive

**Comment by lexming** [comment]
@Flamefire @boegel thanks for the feedback, testing again

**Review by lexming — CHANGES_REQUESTED** [review]
Horovod fails to detect NCCL in our system
```
     -- Linking against static NCCL library
     CMake Error at /theia/home/apps/CO7/skylake/software/CMake/3.15.3-GCCcore-8.3.0/share/cmake-3.15/Modules/FindPackageHandleStandardArgs    .cmake:137 (message):
       Could NOT find NCCL (missing: NCCL_INCLUDE_DIR NCCL_LIBRARY)
     Call Stack (most recent call first):
       /theia/home/apps/CO7/skylake/software/CMake/3.15.3-GCCcore-8.3.0/share/cmake-3.15/Modules/FindPackageHandleStandardArgs.cmake:378 (_    FPHSA_FAILURE_MESSAGE)
       cmake/Modules/FindNCCL.cmake:42 (find_package_handle_standard_args)
       CMakeLists.txt:174 (find_package)
  
     
     -- Configuring incomplete, errors occurred!
```
I fixed it by adding `pkg-config` as a build dependency of Horovod

**Comment by Flamefire** [comment]
Hm, that doesn't make sense, that module doesn't use pkg-config at all so adding it shouldn't change anything.

Can you check `ml show NCCL/2.4.8-gcccuda-2019b` that it contains `CMAKE_PREFIX_PATH`? Can you also check what loading pkg-config changes? Maybe append the output of >`ml show` on that and from the succeeding build check the `Found NCCL` line and paste that (should have a location)

**Comment by lexming** [comment]
Test report by @lexming
**FAILED**
Build succeeded for 2 out of 3 (3 easyconfigs in this PR)
node375.hydra.os - Linux centos linux 7.7.1908, x86_64, Intel(R) Xeon(R) Gold 6148 CPU @ 2.40GHz, Python 2.7.5
See https://gist.github.com/a28d152c7d3eee7e39f9a28d9ec07956 for a full test report.

**Comment by lexming** [comment]
Test report by @lexming
**SUCCESS**
Build succeeded for 3 out of 3 (3 easyconfigs in this PR)
node101.hydra.os - Linux centos linux 7.7.1908, x86_64, Intel(R) Xeon(R) CPU E5-2680 v2 @ 2.80GHz, Python 2.7.5
See https://gist.github.com/95b7aa64e77dc9b1d0f9174f0a276856 for a full test report.

**Comment by boegel** [comment]
@Flamefire I would update Horovod in a follow-up PR, let's try and get this one merged first...

**Comment by boegel** [comment]
@lexming The failing test report on node375 is due to a missing `$CMAKE_PREFIX_PATH` update in the NCCL module?

**Comment by lexming** [comment]
@Flamefire @boegel the real issue is indeed the lack of `$CMAKE_PREFIX_PATH` in our deployment of `NCCL`. It should be completely fixed now. Submitting one final test to counter the failed test.

**Comment by lexming** [comment]
Test report by @lexming
**SUCCESS**
Build succeeded for 3 out of 3 (3 easyconfigs in this PR)
node358.hydra.os - Linux centos linux 7.7.1908, x86_64, Intel(R) Xeon(R) Gold 6148 CPU @ 2.40GHz, Python 2.7.5
See https://gist.github.com/8a0c0dd41bbccbc594c348771d10bc71 for a full test report.

**Review by lexming — APPROVED** [review]
LGTM

**Comment by lexming** [comment]
Going in, thanks @Flamefire !

**Pull request merged**
