### PR TITLE
add patch to disable flaky DDRGES3 LAPACK test in OpenBLAS 0.3.23 + 0.3.24

### PR DESCRIPTION
**Pull request by boegel**
(created using `eb --new-pr`)

see also https://github.com/OpenMathLib/OpenBLAS/issues/4032

### CODE REVIEW

**Comment by boegel** [comment]
@boegelbot please test @ generoso

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in total)
fair-mastodon-c7g-4xlarge-0001 - Linux Rocky Linux 8.7, AArch64, ARM UNKNOWN (neoverse_n1), Python 3.6.8
See https://gist.github.com/boegel/c847a2e67a6e57613ecfded2a0412d55 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in total)
easybuild2.novalocal - Linux CentOS Stream 8, POWER, IBM pSeries (emulated by qemu) (power9le), Python 3.6.8
See https://gist.github.com/boegel/b3079dc5c24066e35f589c5a6505d88d for a full test report.

**Comment by boegel** [comment]
@boegelbot please test @ jsc-zen2

**Comment by casparvl** [comment]
Test report by @casparvl
**FAILED**
Build succeeded for 1 out of 2 (2 easyconfigs in total)
tcn1.local.snellius.surf.nl - Linux RHEL 8.6, x86_64, AMD EPYC 7H12 64-Core Processor, Python 3.6.8
See https://gist.github.com/casparvl/a2ea89e3c9b0c20a792891b60f2ee9a4 for a full test report.

**Comment by casparvl** [comment]
Test report by @casparvl
**SUCCESS**
Build succeeded for 3 out of 3 (2 easyconfigs in total)
tcn1.local.snellius.surf.nl - Linux RHEL 8.6, x86_64, AMD EPYC 7H12 64-Core Processor, Python 3.6.8
See https://gist.github.com/casparvl/fc48e6e08b80905cea51204645132a28 for a full test report.

**Comment by boegel** [comment]
@casparvl https://github.com/EESSI/software-layer/pull/334#issuecomment-1740493522 shows that this patch indeed fixes the problem we were seeing for `x86_64/generic` in EESSI 2023.06

**Review by casparvl — APPROVED** [review]
Lgtm!

**Comment by casparvl** [comment]
Going in, thanks @boegel!

**Pull request merged**
