### PR TITLE
{bio}[foss/2022b] nichenetr v2.0.4 w/ R 4.2.2

### PR DESCRIPTION
**Pull request by boegel**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by boegel** [comment]
@boegelbot please test @ generoso

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
node3147.skitty.os - Linux RHEL 8.8, x86_64, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz (skylake_avx512), Python 3.6.8
See https://gist.github.com/boegel/5f2185f786da0e7dd5231e86def4344e for a full test report.

**Comment by boegel** [comment]
@boegelbot please test @ jsc-zen2

**Comment by branfosj** [comment]
@boegelbot please test @ jsc-zen2
EB_ARGS="--sanity-check-only"

**Comment by branfosj** [comment]
Test report by @branfosj
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
bear-pg0105u03a - Linux RHEL 8.6, x86_64, Intel(R) Xeon(R) Platinum 8360Y CPU @ 2.40GHz (icelake), Python 3.6.8
See https://gist.github.com/branfosj/c3458deb1a0851a486d4a341ae95e91e for a full test report.

**Comment by branfosj** [comment]
```
== 2024-01-14 19:24:13,672 build_log.py:171 ERROR EasyBuild crashed with an error (at easybuild/easybuild-framework/easybuild/base/exceptions.py:126 in __init__): Sanity check failed: command "R -q --no-save" (stdin: "library(nichenetr)") failed; output:
/bin/bash: R: command not found (at easybuild/easybuild-framework/easybuild/framework/easyblock.py:3661 in _sanity_check_step)
```

I'm confused.

**Comment by boegel** [comment]
> ```
> == 2024-01-14 19:24:13,672 build_log.py:171 ERROR EasyBuild crashed with an error (at easybuild/easybuild-framework/easybuild/base/exceptions.py:126 in __init__): Sanity check failed: command "R -q --no-save" (stdin: "library(nichenetr)") failed; output:
> /bin/bash: R: command not found (at easybuild/easybuild-framework/easybuild/framework/easyblock.py:3661 in _sanity_check_step)
> ```
> 
> I'm confused.

known bug, see https://github.com/easybuilders/easybuild-easyblocks/issues/2986

**Comment by branfosj** [comment]
@boegelbot please test @ jsc-zen2

**Review by branfosj — APPROVED** [review]

**Comment by branfosj** [comment]
Going in, thanks @boegel!

**Pull request merged**
