### PR TITLE
specify that --build option should not be set by ConfigureMake in Hypre easyconfigs (WIP)

### PR DESCRIPTION
**Pull request by boegel**
fix for #6922

requires https://github.com/easybuilders/easybuild-easyblocks/pull/1531

### CODE REVIEW

**Comment by vanzod** [comment]
Test report by @vanzod
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
cermis - Linux debian 9.5, Intel(R) Xeon(R) CPU           E5620  @ 2.40GHz, Python 2.7.13
See https://gist.github.com/998b5a68252618bcc4bac3fa85a4ff5b for a full test report.

**Comment by vanzod** [comment]
I could test only one toolchain but LGTM.

**Comment by boegel** [comment]
@vanzod This is `WIP`, please don't merge, I think the proper fix may be to also set `--host`, see the discussion in #6922

**Comment by boegel** [comment]
Superseded by cleaner fix in `ConfigureMake`, cfr. https://github.com/easybuilders/easybuild-easyblocks/pull/1532

**Pull request closed without merging**
