### PR TITLE
fix homepage and source_urls for GLIMMER 3.02b

### PR DESCRIPTION
**Pull request by SethosII**
(created using `eb --new-pr`)

The url changed but there is a working redirection.

### CODE REVIEW

**Comment by boegel** [comment]
@SethosII We enforce that SHA256 checksums are in place for all easyconfigs that are touched in PRs, can you add the missing ones? `eb --inject-checksums` is your friend here...

**Comment by SethosII** [comment]
Hm, the checksums changed :( A diff between them gave this result:
```
> diff -ru glimmer302b-old/glimmer3.02/ glimmer302b-new/glimmer3.02/
Only in glimmer302b-new/glimmer3.02/: README
```

**Comment by SethosII** [comment]
How do we want to proceed with this? The homepage and download changed from `cbcb.umd.edu` to `ccb.jhu.edu` but a working redirect is in place. However the new location has a slightly different tar archive with a `README` in it. The old URL still gives the old archive without the `README`. If it ain't broke, don't fix it?

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in total)
node2604.swalot.os - Linux centos linux 7.9.2009, x86_64, Intel(R) Xeon(R) CPU E5-2660 v3 @ 2.60GHz (haswell), Python 3.6.8
See https://gist.github.com/c9f85c2be3dc11094710ad3350850b6a for a full test report.

**Comment by boegel** [comment]
@SethosII My apologies for not following up on this...

The right way forward here is to accept both the original and the current source tarball as valid, since there's no difference in the source code. That can be done by listing both checksums as a tuple value, like I've done in e0ed983.

This PR should be good to merge now, test report coming up...

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in total)
node2604.swalot.os - Linux centos linux 7.9.2009, x86_64, Intel(R) Xeon(R) CPU E5-2660 v3 @ 2.60GHz (haswell), Python 3.6.8
See https://gist.github.com/d9007443d229e3c82709dde8afabc4a4 for a full test report.

**Review by boegel — APPROVED** [review]
lgtm

**Comment by boegel** [comment]
Going in, thanks @SethosII!

**Pull request merged**
