### PR TITLE
{phys}[intel/2022a] BerkeleyGW v3.1.0

### PR DESCRIPTION
**Pull request by migueldiascosta**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by migueldiascosta** [comment]
@boegelbot please test @ jsc-zen2 EB_ARGS="--include-easyblocks-from-pr 2836"

**Comment by migueldiascosta** [comment]
@boegelbot please test @ jsc-zen2 EB_ARGS="--include-easyblocks-from-pr 2836"

**Comment by akesandgren** [comment]
Test report by @akesandgren
**FAILED**
Build succeeded for 2 out of 5 (1 easyconfigs in total)
b-cn1603.hpc2n.umu.se - Linux Ubuntu 22.04, x86_64, AMD EPYC 7313 16-Core Processor, 1 x NVIDIA NVIDIA A100 80GB PCIe, 525.147.05, Python 3.10.12
See https://gist.github.com/akesandgren/2b26f50ff694e28aa7b8b93281e6aead for a full test report.

**Comment by akesandgren** [comment]
Test report by @akesandgren
**SUCCESS**
Build succeeded for 4 out of 4 (1 easyconfigs in total)
b-an02.hpc2n.umu.se - Linux Ubuntu 20.04, x86_64, Intel(R) Xeon(R) CPU E5-2690 v4 @ 2.60GHz, Python 3.8.10
See https://gist.github.com/akesandgren/94367df3e9cb1379261966a1d8af566c for a full test report.

**Comment by akesandgren** [comment]
@boegelbot Please test @ generoso

**Comment by zao** [comment]
Test report by @zao
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
eb-mix.zao.se - Linux Ubuntu 22.04.3 LTS (Jammy Jellyfish), x86_64, AMD Ryzen 9 3900X 12-Core Processor (zen2), Python 3.10.12
See https://gist.github.com/zao/d00b3337c4254eaa884204f0fd047b03 for a full test report.

**Comment by zao** [comment]
Test report by @zao
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
eb-mix.zao.se - Linux Rocky Linux 9.2 (Blue Onyx), x86_64, AMD Ryzen 9 3900X 12-Core Processor (zen2), Python 3.9.16
See https://gist.github.com/zao/5020f9f3237fab617768308c7b8cbd96 for a full test report.

**Review by akesandgren — APPROVED** [review]
LGTM

**Comment by akesandgren** [comment]
Going in, thanks @migueldiascosta!

**Pull request merged**
