### PR TITLE
{lib}[GCCcore/12.2.0] json-fortran v8.3.0

### PR DESCRIPTION
**Pull request by sassy-crick**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by sassy-crick** [comment]
@boegelbot please test @ generoso

**Comment by zao** [comment]
Test report by @zao
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
eb-mix.zao.se - Linux Ubuntu 22.04.3 LTS (Jammy Jellyfish), x86_64, AMD Ryzen 9 3900X 12-Core Processor (zen2), Python 3.10.12
See https://gist.github.com/zao/e0bed99594be1701797d81265fde69b7 for a full test report.

**Review by smoors — APPROVED** [review]
lgtm

**Comment by smoors** [comment]
@boegelbot please test @ jsc-zen2

**Comment by smoors** [comment]
Going in, thanks @sassy-crick!

**Pull request merged**
