### PR TITLE
{devel}[GCCcore/8.3.0] texinfo v6.7

### PR DESCRIPTION
**Pull request by furstj**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by verdurin** [comment]
Test report by @verdurin
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
easybuild.novalocal - Linux centos linux 7.7.1908, Intel Xeon Processor (Skylake, IBRS), Python 2.7.5
See https://gist.github.com/23004907ad8bcc2990f0c29fd965888b for a full test report.

**Comment by verdurin** [comment]
@furstj please submit a test build

**Comment by furstj** [comment]
Test report by @furstj
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
pc-12101-fuji - Linux UNKNOWN UNKNOWN, Intel(R) Xeon(R) CPU E3-1241 v3 @ 3.50GHz, Python 3.6.9
See https://gist.github.com/021e0c9791616538da28123b23f44835 for a full test report.

**Comment by verdurin** [comment]
Going in, thanks @furstj!

**Pull request merged**
