### PR TITLE
{cae}[foss/2018a] CFDEMcoupling v3.8.0

### PR DESCRIPTION
**Pull request by boegel**
(created using `eb --new-pr`)
requires ~~https://github.com/easybuilders/easybuild-easyblocks/pull/1439~~ + ~https://github.com/easybuilders/easybuild-easyconfigs/pull/6460~ (MPI libraries in VTK 8.1.0)

### CODE REVIEW

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
node2034.delcatty.os - Linux centos linux 7.4.1708, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.7.5
See https://gist.github.com/4b37b2b088ef1a852726114c90525592 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
node2411.golett.os - Linux centos linux 7.4.1708, Intel(R) Xeon(R) CPU E5-2680 v3 @ 2.50GHz, Python 2.7.5
See https://gist.github.com/df99bcb934461212dfb65ae974ec5e97 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
Using easyblocks from https://github.com/easybuilders/easybuild-easyblocks/pull/1439
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
node2445.golett.os - Linux centos linux 7.8.2003, x86_64, Intel(R) Xeon(R) CPU E5-2680 v3 @ 2.50GHz (haswell), Python 2.7.5
See https://gist.github.com/0d31c35f095d1f5b60c5963528bdef27 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
Using easyblocks from https://github.com/easybuilders/easybuild-easyblocks/pull/1439
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
node2445.golett.os - Linux centos linux 7.8.2003, x86_64, Intel(R) Xeon(R) CPU E5-2680 v3 @ 2.50GHz (haswell), Python 2.7.5
See https://gist.github.com/8a066ecd2dce1ccd540b2380d9fb0f2b for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
node2445.golett.os - Linux centos linux 7.8.2003, x86_64, Intel(R) Xeon(R) CPU E5-2680 v3 @ 2.50GHz (haswell), Python 2.7.5
See https://gist.github.com/f551947ad4de6c9a62a691b300489c30 for a full test report.

**Review by akesandgren — APPROVED** [review]
LGTM

**Comment by akesandgren** [comment]
Going in, thanks @boegel!

**Pull request merged**
