### PR TITLE
{lib}[GCC/11.3.0] nghttp2 v1.48.0

### PR DESCRIPTION
**Pull request by iotaka**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by iotaka** [comment]
require
* #16974 
* #16972 
* #16975

**Comment by iotaka** [comment]
require
* #16974 
* #16972 
* #16975
* #16973

**Review by bedroge — CHANGES_REQUESTED** [review]
Could you please add back the author comment from `nghttp2-1.48.0-GCC-11.2.0.eb`?

**Comment by iotaka** [comment]
> @iotaka Could you please add back the author comment from `nghttp2-1.48.0-GCC-11.2.0.eb`?

did it

**Comment by bedroge** [comment]
@boegelbot please test @ jsc-zen2

**Comment by bedroge** [comment]
Test report by @bedroge
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
bob-Latitude-5300 - Linux Ubuntu 22.04, x86_64, Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz, Python 3.10.6
See https://gist.github.com/65af2cf6e87c0aa44b814ffc13a6a0f1 for a full test report.

**Comment by bedroge** [comment]
Going in, thanks @iotaka!

**Pull request merged**
