### PR TITLE
Create libsigsegv-2.13-GCCcore-10.2.0.eb

### PR DESCRIPTION
**Pull request by levlafayette**
New version, new compiler, new binutils

### CODE REVIEW

**Review by Micket — APPROVED** [review]
lgtm

**Comment by Micket** [comment]
@boegelbot please test @ generoso

**Comment by Micket** [comment]
Test report by @Micket
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
alvis-c1 - Linux centos linux 7.9.2009, x86_64, Intel Xeon Processor (Skylake), Python 3.6.8
See https://gist.github.com/351d6596c5371421371afdb48fdaf562 for a full test report.

**Comment by verdurin** [comment]
Going in, thanks @levlafayette!

**Pull request merged**
