### PR TITLE
{tools}[foss/2022a] Arcade-Learning-Environment v0.8.1, OpenAI-Gym v0.26.2 w/ Python 3.10.4

### PR DESCRIPTION
**Pull request by WilleBell**
(created using `eb --new-pr`)  
Depends on:  
* [x] #18252
* [x] #18253

### CODE REVIEW

**Comment by verdurin** [comment]
Test report by @verdurin
**SUCCESS**
Build succeeded for 14 out of 14 (2 easyconfigs in total)
easybuild-c7.novalocal - Linux CentOS Linux 7.9.2009, x86_64, Intel Xeon Processor (Skylake, IBRS), Python 3.6.8
See https://gist.github.com/verdurin/e48928943bbc0cb48dda2f5460e2eb53 for a full test report.

**Comment by verdurin** [comment]
@boegelbot please test @ generoso

**Comment by WilleBell** [comment]
Test report by @WilleBell
**FAILED**
Build succeeded for 0 out of 2 (2 easyconfigs in total)
node301.hydra.os - Linux CentOS Linux 7.9.2009, x86_64, Intel(R) Xeon(R) Gold 6148 CPU @ 2.40GHz, Python 3.6.8
See https://gist.github.com/WilleBell/44331c3f7ad155bc53cf5136c7220e5f for a full test report.

**Comment by WilleBell** [comment]
Test report by @WilleBell
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in total)
node302.hydra.os - Linux CentOS Linux 7.9.2009, x86_64, Intel(R) Xeon(R) Gold 6148 CPU @ 2.40GHz, Python 3.6.8
See https://gist.github.com/WilleBell/4c7f5fd43be194ca1d0df693fcf13cf2 for a full test report.

**Review by boegel — APPROVED** [review]
lgtm

**Comment by boegel** [comment]
@boegelbot please test @ jsc-zen2

**Comment by boegel** [comment]
@boegelbot please test @ jsc-zen2

**Comment by boegel** [comment]
Going in, thanks @WilleBell!

**Pull request merged**
