### PR TITLE
Boost.Python: Boost is moving download location as bintray is closing

### PR DESCRIPTION
**Pull request by branfosj**
(created using `eb --new-pr`)

part of #12099 - see https://lists.boost.org/Archives/boost/2021/04/251458.php

### CODE REVIEW

**Comment by branfosj** [comment]
Test report by @branfosj
**SUCCESS**
Build succeeded for 7 out of 7 (7 easyconfigs in total)
bb-pg-login02.bear.cluster - Linux RHEL 8.3, x86_64, Intel(R) Xeon(R) CPU E5-2620 v4 @ 2.10GHz (broadwell), Python 3.6.8
See https://gist.github.com/7346497dd623e40db7a209eee4c7990e for a full test report.

**Review by boegel — APPROVED** [review]
lgtm

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 7 out of 7 (7 easyconfigs in total)
node2704.swalot.os - Linux centos linux 7.9.2009, x86_64, Intel(R) Xeon(R) CPU E5-2660 v3 @ 2.60GHz (haswell), Python 3.6.8
See https://gist.github.com/eff1740b8458444c937854f0972f560a for a full test report.

**Comment by boegel** [comment]
Going in, thanks @branfosj!

**Pull request merged**
