### PR TITLE
{devel}[intel/2019.01] Boost v1.67.0

### PR DESCRIPTION
**Pull request by sassy-crick**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by boegel** [comment]
@sassy-crick Any specific reason for this old version (there's a Boost 1.70.0 already), or for not using the existing easyconfigs we have for the `iimpi/2019a` subtoolchain of `intel/2019a` (which is pretty much equivalent with `intel/2019.01`)?

**Comment by sassy-crick** [comment]
@boegel that dates back from the pubtcrs-f30b96a-intel-2019.01.eb build file (PR #7500) where at the time I used that BOOST. So for completion, I thought I upload that as well. I guess what one could do is drop that BOOST version in favour of the latest one and update PR #7500 to the latest BOOST as well, assuming that is not causing problems with the pubtcrs.

**Comment by boegel** [comment]
@sassy-crick I would favor the latter, and maybe also move the `toolchain` in #7500 to `intel/2019a`?

**Comment by sassy-crick** [comment]
@boegel I have updated #7500 to intel/2019a and BOOST-1.70.0 so we can close this PR if you are happy with this.

**Comment by migueldiascosta** [comment]
@sassy-crick, this PR is being closed for the following reason(s): obsoleted by more recent PRs.
Please don't hesitate to reopen this PR or add a comment if you feel this contribution is still relevant.
For more information on our policy w.r.t. closing PRs, see https://easybuild.readthedocs.io/en/latest/Contributing.html#why-a-pull-request-may-be-closed-by-a-maintainer

**Pull request closed without merging**
