### PR TITLE
+download URL for ifort 2018.3

### PR DESCRIPTION
**Pull request by jose-d**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by jose-d** [comment]
Test report by @jose-d
**FAILED**
Build succeeded for 0 out of 1 (1 easyconfigs in this PR)
koios1 - Linux centos linux 7.3.1611, Intel(R) Xeon(R) Gold 6130 CPU @ 2.10GHz, Python 2.7.5
See https://gist.github.com/65273fd8fdbba2a5c5f225e58d4e52ab for a full test report.

**Comment by jose-d** [comment]
Test report by @jose-d
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
koios1 - Linux centos linux 7.3.1611, Intel(R) Xeon(R) Gold 6130 CPU @ 2.10GHz, Python 2.7.5
See https://gist.github.com/57afd8e671b015a0c7d4b4537c2933ef for a full test report.

**Comment by jose-d** [comment]
```
found 2 variants of 'PyQt5' dependency in easyconfigs using '2018a' toolchain generation
* version: 5.10.1; versionsuffix: -Python-3.6.4 as dep for set(['AFNI-18.1.09-intel-2018a-Python-3.6.4.eb'])
* version: 5.9.2; versionsuffix: -Python-3.6.4 as dep for set(['Spyder-3.3.1-foss-2018a-Python-3.6.4.eb'])
```

CI bug?

**Comment by boegel** [comment]
@jose-d That issue is fixed in #7294, has nothing to do with this PR obviously. I'll retrigger the tests once #7294 is merged

**Comment by boegel** [comment]
Going in, thanks @jose-d!

**Pull request merged**
