### PR TITLE
{bio}[GCCcore/12.3.0] tbl2asn v20230713

### PR DESCRIPTION
**Pull request by laraPPr**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by laraPPr** [comment]
Test report by @laraPPr
**SUCCESS**
Build succeeded for 0 out of 0 (1 easyconfigs in total)
node3113.skitty.os - Linux RHEL 9.4 (Plow), x86_64, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz, Python 3.9.18
See https://gist.github.com/laraPPr/815fcf046f3f84b89a20ab8ea57558d4 for a full test report.

**Comment by laraPPr** [comment]
Test report by @laraPPr
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
node3113.skitty.os - Linux RHEL 9.4 (Plow), x86_64, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz, Python 3.9.18
See https://gist.github.com/laraPPr/1f15b7fa9e73263c841edd4afcf1c6c1 for a full test report.

**Comment by laraPPr** [comment]
Test report by @laraPPr
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
gligar07.gastly.os - Linux RHEL 8.8, x86_64, AMD EPYC 7532 32-Core Processor, Python 3.6.8
See https://gist.github.com/laraPPr/277de65ba58834b7a155bccf5d8aa9f3 for a full test report.

**Comment by laraPPr** [comment]
@boegelbot please test @ generoso

**Comment by laraPPr** [comment]
@boegelbot please test @ jsc-zen3

**Comment by verdurin** [comment]
Test report by @verdurin
**FAILED**
Build succeeded for 0 out of 1 (1 easyconfigs in total)
easybuild-el8.cloud.in.bmrc.ox.ac.uk - Linux Rocky Linux 8.10, x86_64, Intel Xeon Processor (Skylake, IBRS), Python 3.6.8
See https://gist.github.com/verdurin/19e9c7ebcda8ae07c6b83e87ff794789 for a full test report.

**Comment by verdurin** [comment]
```
== 2024-10-31 17:19:22,718 run.py:181 DEBUG run_cmd: Output of "if %(rpath_enabled)s; then   patchelf --force-rpath --set-rpath %(installdir)s/lib %(installdir)s/bin/tbl2asn;fi" will be logged to /tmp/eb-1suco5j6/easybuild-run_cmd-rhk2otbl.log
== 2024-10-31 17:19:22,721 run.py:222 DEBUG run_cmd: running cmd if %(rpath_enabled)s; then   patchelf --force-rpath --set-rpath %(installdir)s/lib %(installdir)s/bin/tbl2asn;fi (in /dev/shm/tbl2asn/20230713/GCCcore-12.3.0)
== 2024-10-31 17:19:22,721 run.py:251 INFO Using /bin/bash as shell for running cmd: if %(rpath_enabled)s; then   patchelf --force-rpath --set-rpath %(installdir)s/lib %(installdir)s/bin/tbl2asn;fi
== 2024-10-31 17:19:22,721 run.py:260 INFO running cmd: if %(rpath_enabled)s; then   patchelf --force-rpath --set-rpath %(installdir)s/lib %(installdir)s/bin/tbl2asn;fi
== 2024-10-31 17:19:22,745 build_log.py:171 ERROR EasyBuild crashed with an error (at easybuild/base/exceptions.py:126 in __init__): cmd "if %(rpath_enabled)s; then   patchelf --force-rpath --set-rpath %(installdir)s/lib %(installdir)s/bin/tbl2asn;fi" exited with exit code 1 and output:
/bin/bash: -c: line 0: syntax error near unexpected token `rpath_enabled'
/bin/bash: -c: line 0: `if %(rpath_enabled)s; then   patchelf --force-rpath --set-rpath %(installdir)s/lib %(installdir)s/bin/tbl2asn;fi'
 (at easybuild/tools/run.py:695 in parse_cmd_output)
 ```

**Comment by laraPPr** [comment]
> ```
> 
> == 2024-10-31 17:19:22,718 run.py:181 DEBUG run_cmd: Output of "if %(rpath_enabled)s; then   patchelf --force-rpath --set-rpath %(installdir)s/lib %(installdir)s/bin/tbl2asn;fi" will be logged to /tmp/eb-1suco5j6/easybuild-run_cmd-rhk2otbl.log
> 
> == 2024-10-31 17:19:22,721 run.py:222 DEBUG run_cmd: running cmd if %(rpath_enabled)s; then   patchelf --force-rpath --set-rpath %(installdir)s/lib %(installdir)s/bin/tbl2asn;fi (in /dev/shm/tbl2asn/20230713/GCCcore-12.3.0)
> 
> == 2024-10-31 17:19:22,721 run.py:251 INFO Using /bin/bash as shell for running cmd: if %(rpath_enabled)s; then   patchelf --force-rpath --set-rpath %(installdir)s/lib %(installdir)s/bin/tbl2asn;fi
> 
> == 2024-10-31 17:19:22,721 run.py:260 INFO running cmd: if %(rpath_enabled)s; then   patchelf --force-rpath --set-rpath %(installdir)s/lib %(installdir)s/bin/tbl2asn;fi
> 
> == 2024-10-31 17:19:22,745 build_log.py:171 ERROR EasyBuild crashed with an error (at easybuild/base/exceptions.py:126 in __init__): cmd "if %(rpath_enabled)s; then   patchelf --force-rpath --set-rpath %(installdir)s/lib %(installdir)s/bin/tbl2asn;fi" exited with exit code 1 and output:
> 
> /bin/bash: -c: line 0: syntax error near unexpected token `rpath_enabled'
> 
> /bin/bash: -c: line 0: `if %(rpath_enabled)s; then   patchelf --force-rpath --set-rpath %(installdir)s/lib %(installdir)s/bin/tbl2asn;fi'
> 
>  (at easybuild/tools/run.py:695 in parse_cmd_output)
> 
>  ```

You have to use the develop branch of framework for it to know 'rpath_enabled'

**Comment by verdurin** [comment]
Test report by @verdurin
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
easybuild-el8.cloud.in.bmrc.ox.ac.uk - Linux Rocky Linux 8.10, x86_64, Intel Xeon Processor (Skylake, IBRS), Python 3.6.8
See https://gist.github.com/verdurin/ae55a95ae0387a2256753476173dc6cc for a full test report.

**Review by verdurin — APPROVED** [review]
Looks fine.

**Pull request merged**
