### PR TITLE
{numlib,toolchain}[gompi/2022a,system/system] imkl v2022.1.0, gomkl v2022a

### PR DESCRIPTION
**Pull request by smoors**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by smoors** [comment]
@boegelbot: please test @ generoso

**Comment by smoors** [comment]
@boegelbot please test @ jsc-zen2

**Comment by jfgrimm** [comment]
Test report by @jfgrimm
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in total)
himem04.pri.viking.alces.network - Linux CentOS Linux 7.9.2009, x86_64, Intel(R) Xeon(R) Gold 6230 CPU @ 2.10GHz (cascadelake), Python 3.6.8
See https://gist.github.com/75ed58118ced2288b4eb830666bb6543 for a full test report.

**Comment by boegel** [comment]
@smoors Please add an `HPL` easyconfig using this toolchain, which can serve as a test for this toolchain?

**Comment by sassy-crick** [comment]
Test report by @sassy-crick
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in total)
hp - Linux Debian GNU/Linux 11, x86_64, 11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz, Python 3.9.2
See https://gist.github.com/a5f3587a0d6ba3a33361e3ee2c6e7f1d for a full test report.

**Comment by smoors** [comment]
@boegelbot: please test @ generoso EB_ARGS="HPL-2.3-gomkl-2022a.eb"

**Review by boegel — APPROVED** [review]
lgtm

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 3 out of 3 (3 easyconfigs in total)
node3154.skitty.os - Linux RHEL 8.6, x86_64, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz (skylake_avx512), Python 3.6.8
See https://gist.github.com/60fe9e0ec9b85723ff49b03c182aa1ab for a full test report.

**Comment by jfgrimm** [comment]
Test report by @jfgrimm
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
himem04.pri.viking.alces.network - Linux CentOS Linux 7.9.2009, x86_64, Intel(R) Xeon(R) Gold 6230 CPU @ 2.10GHz (cascadelake), Python 3.6.8
See https://gist.github.com/5b1f15859180d4cf7a32cb09f9a1d3f0 for a full test report.

**Comment by boegel** [comment]
Going in, thanks @smoors!

**Pull request merged**
