### PR TITLE
{chem}[foss/2023a] waLBerla v6.1 w/ CUDA 12.1.1

### PR DESCRIPTION
**Pull request by Neves-P**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by Neves-P** [comment]
Test report by @Neves-P
**FAILED**
Build succeeded for 0 out of 1 (1 easyconfigs in total)
WKS058930 - Linux Ubuntu 22.04, x86_64, 12th Gen Intel(R) Core(TM) i7-1260P, Python 3.10.12
See https://gist.github.com/Neves-P/c99cb2ebb2867831b49e28b23d183908 for a full test report.

**Comment by Neves-P** [comment]
> Test report by @Neves-P **FAILED** Build succeeded for 0 out of 1 (1 easyconfigs in total) WKS058930 - Linux Ubuntu 22.04, x86_64, 12th Gen Intel(R) Core(TM) i7-1260P, Python 3.10.12 See https://gist.github.com/Neves-P/c99cb2ebb2867831b49e28b23d183908 for a full test report.

Well, that was never going to work on a system that doesn't `CUDA` 🤦 
Trying again.

**Comment by Neves-P** [comment]
Test report by @Neves-P
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
WKS058930 - Linux Ubuntu 22.04, x86_64, 12th Gen Intel(R) Core(TM) i7-1260P, Python 3.10.12
See https://gist.github.com/Neves-P/715472d59941bebefe9629566839d11b for a full test report.

**Comment by boegel** [comment]
@boegelbot please test @ jsc-zen3-a100

**Review by boegel — APPROVED** [review]
lgtm

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 2 out of 2 (1 easyconfigs in total)
node3901.accelgor.os - Linux RHEL 8.8, x86_64, AMD EPYC 7413 24-Core Processor, 1 x NVIDIA NVIDIA A100-SXM4-80GB, 545.23.08, Python 3.6.8
See https://gist.github.com/boegel/50b138337edf667abb06cc345ad4a941 for a full test report.

**Comment by boegel** [comment]
Going in, thanks @Neves-P!

**Pull request merged**
