### PR TITLE
{bio}[foss/2018b,foss/2019b] EIGENSOFT v7.2.1

### PR DESCRIPTION
**Pull request by tstrempel**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by smoors** [comment]
@tstrempel there are many differences between these 2 easyconfigs, it's not clear why you are doing that?

**Comment by tstrempel** [comment]
@smoors I can't really say why, because I wrote them a long time ago. I simply commited them when I saw there weren't here yet.
I'll update these to better match each other.

**Comment by tstrempel** [comment]
@smoors Now everything is unified

**Comment by smoors** [comment]
Test report by @smoors
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in this PR)
node375.hydra.os - Linux centos linux 7.7.1908, x86_64, Intel(R) Xeon(R) Gold 6148 CPU @ 2.40GHz (skylake_avx512), Python 2.7.5
See https://gist.github.com/7a3adafe447616ca4f576b2cbd2dd481 for a full test report.

**Comment by smoors** [comment]
Going in, thanks @tstrempel!

**Pull request merged**
