### PR TITLE
{lib}[foss/2023a] Phonopy-Spectroscopy v20240308

### PR DESCRIPTION
**Pull request by WilleBell**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by WilleBell** [comment]
Test report by @WilleBell
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
node611.hydra.os - Linux Rocky Linux 8.10, x86_64, AMD EPYC 9384X 32-Core Processor, Python 3.6.8
See https://gist.github.com/WilleBell/a6b83610f579fddca5af22b5a5ed6f86 for a full test report.

**Comment by WilleBell** [comment]
Test report by @WilleBell
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
node611.hydra.os - Linux Rocky Linux 8.10, x86_64, AMD EPYC 9384X 32-Core Processor, Python 3.6.8
See https://gist.github.com/WilleBell/aced4fc3088c49495be5e6ce59ca62b3 for a full test report.

**Comment by bedroge** [comment]
`phonopy-ir --help` shows that it also depends on `h5py`:
```
ModuleNotFoundError: No module named 'h5py'
```

**Comment by WilleBell** [comment]
> `phonopy-ir --help` shows that it also depends on `h5py`:
> 
> ```
> ModuleNotFoundError: No module named 'h5py'
> ```

In their [readme](https://github.com/skelton-group/Phonopy-Spectroscopy?tab=readme-ov-file#installation) I understood `phonopy` (and `h5py`) is only needed for the Phonopy interface, so I went for the minimal requirements, but I have to say I am not sure if it is the right choice. I can add phonopy as a dependency to avoid complications if needed.

**Comment by smoors** [comment]
@boegelbot: please test @ generoso

**Comment by smoors** [comment]
@boegelbot please test @ jsc-zen3

**Review by smoors — APPROVED** [review]
lgtm

**Comment by smoors** [comment]
Going in, thanks @WilleBell!

**Pull request merged**
