### PR TITLE
{bio}[GCCcore/11.2.0,foss/2021b] SEPP v4.5.0, DendroPy v4.5.2 w/ Python 3.9.6

### PR DESCRIPTION
**Pull request by manifestoso**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by manifestoso** [comment]
{bio} version update

**Comment by lexming** [comment]
@boegelbot: please test @ generoso

**Comment by lexming** [comment]
Test report by @lexming
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in total)
node305.hydra.os - Linux centos linux 7.9.2009, x86_64, Intel(R) Xeon(R) Gold 6148 CPU @ 2.40GHz, Python 2.7.5
See https://gist.github.com/35b804089cfb1ec2fed152f96d2a1770 for a full test report.

**Review by lexming — DISMISSED** [review]
LGTM

**Comment by lexming** [comment]
@boegelbot: please test @ generoso

**Comment by lexming** [comment]
Going in, thanks @manifestoso !

**Review by lexming — APPROVED** [review]
Now it really LGTM. I just found out that DendroPy has its own homepage at dendropy.org, so I replaced the URL to PyPI with it.

**Comment by lexming** [comment]
@boegelbot: please test @ generoso

**Comment by lexming** [comment]
Going in, thanks @manifestoso !

**Pull request merged**
