### PR TITLE
{bio}[GCC/8.3.0,foss/2019b] STAR-Fusion v1.8.1, STAR v2.7.2b w/ Python 3.7.4

### PR DESCRIPTION
**Pull request by lexming**
(created using `eb --new-pr`)

Relevant changes:
* depends on `STAR-2.7.2b-GCC-8.3.0` instead of the already available `STAR-2.7.3a-GCC-8.3.0`. The dependency between `STAR-Fusion` and `STAR` is very tight and has to follow the specification in https://github.com/STAR-Fusion/STAR-Fusion/wiki/STAR-Fusion-release-and-CTAT-Genome-Lib-Compatibility-Matrix
* ~~Perl packages `URI::Escape` and `Set::IntervalTree` are added to the main Perl installation as these packages are used by other easyconfigs~~

### CODE REVIEW

**Comment by lexming** [comment]
Depends on #9957 and #9977

**Comment by lexming** [comment]
Test report by @lexming
**SUCCESS**
Build succeeded for 3 out of 3 (3 easyconfigs in this PR)
login2.cerberus.os - Linux centos linux 7.7.1908, Intel(R) Xeon(R) Gold 6126 CPU @ 2.60GHz, Python 2.7.5
See https://gist.github.com/a766e50f0d29b89c22689ded41e4f7b7 for a full test report.

**Comment by lexming** [comment]
Depends on #10049

**Comment by lexming** [comment]
Since this is an easyconfig for Python 3, it should be able to depend on a dependency with a Python 3 `versionsuffix` instead of a non-Python one, isn't it?

**Comment by boegel** [comment]
@lexming The issue is that this introduces two different variants of Trinity that are used as a dependency.

In this specific case, it's a bit silly because of the different Python versions (where we do allow a Python 2.x and 3.x), but the checks currently aren't smart enough to make that distinction...

**Comment by lexming** [comment]
Test report by @lexming
**SUCCESS**
Build succeeded for 4 out of 4 (4 easyconfigs in this PR)
node375.hydra.os - Linux centos linux 7.7.1908, Intel(R) Xeon(R) Gold 6148 CPU @ 2.40GHz, Python 2.7.5
See https://gist.github.com/d8af98a0492d3e91dde7f77fc09b6082 for a full test report.

**Comment by lexming** [comment]
@boegel This can still be fixed before next release, `SECAPR-1.1.15-foss-2019b-Python-2.7.16.eb` has not hit master yet.
To solve this issue I added a Trinity easyconfig using Python 2 for version 2.9.1, which still supports it. Then, SECAPR can depend on `Trinity-2.9.1-foss-2019b-Python-2.7.16.eb` and STAR-Fusion on `Trinity-2.9.1-foss-2019b-Python-3.7.4.eb` and the tests are happy.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 4 out of 4 (4 easyconfigs in this PR)
node2622.swalot.os - Linux centos linux 7.7.1908, Intel(R) Xeon(R) CPU E5-2660 v3 @ 2.60GHz (haswell), Python 2.7.5
See https://gist.github.com/9bb64a9679c7c6901b528fd57a2c8345 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 4 out of 4 (4 easyconfigs in this PR)
generoso - Linux centos linux 7.6.1810, Intel(R) Xeon(R) CPU E5-2660 v4 @ 2.00GHz, Python 3.6.8
See https://gist.github.com/b4a5b44f21872538b1ea561509ce2f2a for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 4 out of 4 (4 easyconfigs in this PR)
node3109.skitty.os - Linux centos linux 7.7.1908, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz (skylake_avx512), Python 3.6.8
See https://gist.github.com/03ff512466bd6b8bdce34924b41dd54e for a full test report.

**Comment by boegel** [comment]
Going in, thanks @lexming!

**Pull request merged**
