### PR TITLE
{bio}[dummy/] MSPC v3.3.1

### PR DESCRIPTION
**Pull request by pescobar**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by pescobar** [comment]
it's expected that travis complains about missing deps. 

This PR depends in the net-core easyconfig in https://github.com/easybuilders/easybuild-easyconfigs/pull/8530

**Comment by migueldiascosta** [comment]
closing and reopening to trigger travis

**Comment by migueldiascosta** [comment]
Test report by @migueldiascosta
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
sms - Linux centos linux 7.6.1810, AMD EPYC 7601 32-Core Processor, Python 2.7.5
See https://gist.github.com/7d79ba843bf803dfafb038861dedcef0 for a full test report.

**Comment by migueldiascosta** [comment]
Going in, thanks @pescobar!

**Pull request merged**
