### PR TITLE
{chem}[intel/2018a] PLUMED v2.5b w/ Python 2.7.14

### PR DESCRIPTION
**Pull request by boegel**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
node2093.delcatty.os - Linux centos linux 7.5.1804, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.7.5
See https://gist.github.com/5b60b44008b9438f1222ac1360554cee for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**FAILED**
Build succeeded for 0 out of 1 (1 easyconfigs in this PR)
node3146.skitty.os - Linux centos linux 7.5.1804, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz, Python 2.7.5
See https://gist.github.com/7bfeb434e75371ff7486ad928e5ee330 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
node3106.skitty.os - Linux centos linux 7.5.1804, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz, Python 2.7.5
See https://gist.github.com/a44d81ec9dc8b8169f173e4957b68505 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**FAILED**
Build succeeded for 0 out of 1 (1 easyconfigs in this PR)
node2595.golett.os - Linux centos linux 7.5.1804, Intel(R) Xeon(R) CPU E5-2680 v3 @ 2.50GHz, Python 2.7.5
See https://gist.github.com/8cc265c14c03246e71b59a0a85c0b96a for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
node2573.golett.os - Linux centos linux 7.5.1804, Intel(R) Xeon(R) CPU E5-2680 v3 @ 2.50GHz, Python 2.7.5
See https://gist.github.com/264a4a813fb2375cd87eb811a3fc1f01 for a full test report.

**Comment by vanzod** [comment]
Test report by @vanzod
**FAILED**
Build succeeded for 2 out of 5 (1 easyconfigs in this PR)
cermis - Linux debian 9.5, Intel(R) Xeon(R) CPU           E5620  @ 2.40GHz, Python 2.7.13
See https://gist.github.com/5fd17650014daffb11de76688b2224c7 for a full test report.

**Comment by vanzod** [comment]
There are some issued building `Guile`...

**Comment by boegel** [comment]
@vanzod This seems to be the issue:

```
filesys.c: In function 'scm_readdir':
filesys.c:921:5: error: 'readdir64_r' is deprecated [-Werror=deprecated-declarations]
     SCM_SYSCALL (readdir_r_or_readdir64_r (ds, (struct dirent_or_dirent64 *) buf, &rdent));
     ^~~~~~~~~~~
In file included from filesys.c:122:0:
/usr/include/dirent.h:201:12: note: declared here
 extern int readdir64_r (DIR *__restrict __dirp,
^~~~~~~~~~~
```

That's a warning being promoted to an error. It seems like we should be able to dance around this by including `-Werror=deprecated-declarations` in `$CFLAGS` in the `Guile` easyconfig.

What I don't understand is why this is a problem for you, and not for me... Any ideas?

**Comment by akesandgren** [comment]
Test report by @akesandgren
**FAILED**
Build succeeded for 0 out of 1 (1 easyconfigs in this PR)
t-an01.hpc2n.umu.se - Linux ubuntu 16.04, AMD Opteron(TM) Processor 6238, Python 2.7.12
See https://gist.github.com/09ab4d7fd85938635ba4fcbd1845693f for a full test report.

**Comment by akesandgren** [comment]
Test report by @akesandgren
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
b-an02.hpc2n.umu.se - Linux ubuntu 16.04, Intel(R) Xeon(R) CPU E5-2690 v4 @ 2.60GHz, Python 2.7.12
See https://gist.github.com/e7c1cf508f6414fb40a87bac1ed2f8d4 for a full test report.

**Pull request merged**
