### PR TITLE
update Java/1.8 to Java/1.8.0_231 (for x86_64)

### PR DESCRIPTION
**Pull request by jakevc**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by jakevc** [comment]
Will pass when #9584 is merged

**Comment by boegel** [comment]
@jakevc Thanks a lot for looking into this!

It would have been easier if you packed #9584 and this change in the same PR, but we'll get this merged anyway, it's not a huge problem. :)

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
generoso - Linux centos linux 7.6.1810, Intel(R) Xeon(R) CPU E5-2660 v4 @ 2.00GHz, Python 3.6.8
See https://gist.github.com/58260faa78ac26abd2037f8677a351ad for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
node3144.skitty.os - Linux centos linux 7.7.1908, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz, Python 3.6.8
See https://gist.github.com/0b88c1a3183ac6fa7127b92a40495ecb for a full test report.

**Comment by boegel** [comment]
Going in, thanks @jakevc!

**Pull request merged**
