### PR TITLE
enable running of tests for MEME with gompi/2021b

### PR DESCRIPTION
**Pull request by boegel**
(created using `eb --new-pr`)
requires:
* https://github.com/easybuilders/easybuild-easyconfigs/pull/15190

### CODE REVIEW

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
node3164.skitty.os - Linux CentOS Linux 7.9.2009, x86_64, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz, Python 3.6.8
See https://gist.github.com/dc2d1cfc618526ca1839bbce3d90660c for a full test report.

**Comment by branfosj** [comment]
@boegelbot please test @ generoso

**Comment by branfosj** [comment]
Test report by @branfosj
**SUCCESS**
Build succeeded for 3 out of 3 (1 easyconfigs in total)
bear-pg0211u03a.bear.cluster - Linux RHEL 8.5, x86_64, Intel(R) Xeon(R) Gold 6248 CPU @ 2.50GHz (cascadelake), Python 3.6.8
See https://gist.github.com/1dd45855ef14f150e9e330677a797d02 for a full test report.

**Comment by branfosj** [comment]
```
Operating system identified as: 'Linux'. Native driver can not be loaded: Error loading Sys::Info::Driver::Linux::Device::CPU: Can't locate Sys/Info/Driver/Linux/Device/CPU.pm in @INC (you may need to install the Sys::Info::Driver::Linux::Device::CPU module) (@INC contains: /dev/shm/build-branfosj-admin/branfosj-admin-up/MEME/5.4.1/gompi-2021b-Python-2.7.18/meme-5.4.1/scripts /rds/bear-apps/devel/eb-sjb-up/EL8/EL8-cas/software/XML-Compile/1.63-GCCcore-11.2.0/lib/perl5/site_perl/5.34.0/x86_64-linux-thread-multi /rds/bear-apps/devel/eb-sjb-up/EL8/EL8-cas/software/XML-Compile/1.63-GCCcore-11.2.0/lib/perl5/site_perl/5.34.0 /rds/bear-apps/devel/eb-sjb-up/EL8/EL8-cas/software/XML-LibXML/2.0207-GCCcore-11.2.0/lib/perl5/site_perl/5.34.0/x86_64-linux-thread-multi /rds/bear-apps/devel/eb-sjb-up/EL8/EL8-cas/software/XML-LibXML/2.0207-GCCcore-11.2.0/lib/perl5/site_perl/5.34.0 /rds/bear-apps/devel/eb-sjb-up/EL8/EL8-cas/software/Perl/5.34.0-GCCcore-11.2.0/lib/perl5/site_perl/5.34.0/x86_64-linux-thread-multi /rds/bear-apps/devel/eb-sjb-up/EL8/EL8-cas/software/Perl/5.34.0-GCCcore-11.2.0/lib/perl5/site_perl/5.34.0 /rds/bear-apps/devel/eb-sjb-up/EL8/EL8-cas/software/Perl/5.34.0-GCCcore-11.2.0/lib/perl5/5.34.0/x86_64-linux-thread-multi /rds/bear-apps/devel/eb-sjb-up/EL8/EL8-cas/software/Perl/5.34.0-GCCcore-11.2.0/lib/perl5/5.34.0) at /rds/bear-apps/devel/eb-sjb-up/EL8/EL8-cas/software/Perl/5.34.0-GCCcore-11.2.0/lib/perl5/site_perl/5.34.0/Sys/Info/Base.pm line 45.
 at /rds/bear-apps/devel/eb-sjb-up/EL8/EL8-cas/software/Perl/5.34.0-GCCcore-11.2.0/lib/perl5/site_perl/5.34.0/Sys/Info/Device/CPU.pm line 9.
. Falling back to compatibility mode
```

While it is not a required Perl module, should we be adding this in #15190 as well?

**Comment by boegel** [comment]
@boegelbot please test @ generoso

**Comment by boegel** [comment]
> ```
> Operating system identified as: 'Linux'. Native driver can not be loaded: Error loading Sys::Info::Driver::Linux::Device::CPU: Can't locate Sys/Info/Driver/Linux/Device/CPU.pm in @INC (you may need to install the Sys::Info::Driver::Linux::Device::CPU module) (@INC contains: /dev/shm/build-branfosj-admin/branfosj-admin-up/MEME/5.4.1/gompi-2021b-Python-2.7.18/meme-5.4.1/scripts /rds/bear-apps/devel/eb-sjb-up/EL8/EL8-cas/software/XML-Compile/1.63-GCCcore-11.2.0/lib/perl5/site_perl/5.34.0/x86_64-linux-thread-multi /rds/bear-apps/devel/eb-sjb-up/EL8/EL8-cas/software/XML-Compile/1.63-GCCcore-11.2.0/lib/perl5/site_perl/5.34.0 /rds/bear-apps/devel/eb-sjb-up/EL8/EL8-cas/software/XML-LibXML/2.0207-GCCcore-11.2.0/lib/perl5/site_perl/5.34.0/x86_64-linux-thread-multi /rds/bear-apps/devel/eb-sjb-up/EL8/EL8-cas/software/XML-LibXML/2.0207-GCCcore-11.2.0/lib/perl5/site_perl/5.34.0 /rds/bear-apps/devel/eb-sjb-up/EL8/EL8-cas/software/Perl/5.34.0-GCCcore-11.2.0/lib/perl5/site_perl/5.34.0/x86_64-linux-thread-multi /rds/bear-apps/devel/eb-sjb-up/EL8/EL8-cas/software/Perl/5.34.0-GCCcore-11.2.0/lib/perl5/site_perl/5.34.0 /rds/bear-apps/devel/eb-sjb-up/EL8/EL8-cas/software/Perl/5.34.0-GCCcore-11.2.0/lib/perl5/5.34.0/x86_64-linux-thread-multi /rds/bear-apps/devel/eb-sjb-up/EL8/EL8-cas/software/Perl/5.34.0-GCCcore-11.2.0/lib/perl5/5.34.0) at /rds/bear-apps/devel/eb-sjb-up/EL8/EL8-cas/software/Perl/5.34.0-GCCcore-11.2.0/lib/perl5/site_perl/5.34.0/Sys/Info/Base.pm line 45.
>  at /rds/bear-apps/devel/eb-sjb-up/EL8/EL8-cas/software/Perl/5.34.0-GCCcore-11.2.0/lib/perl5/site_perl/5.34.0/Sys/Info/Device/CPU.pm line 9.
> . Falling back to compatibility mode
> ```
> 
> While it is not a required Perl module, should we be adding this in #15190 as well?

Done in https://github.com/easybuilders/easybuild-easyconfigs/pull/15190/commits/e4db0bf72d943c08f63ca246916095fe730bf65d in #15190

**Comment by branfosj** [comment]
Test report by @branfosj
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
bear-pg0211u03a.bear.cluster - Linux RHEL 8.5, x86_64, Intel(R) Xeon(R) Gold 6248 CPU @ 2.50GHz (cascadelake), Python 3.6.8
See https://gist.github.com/a0bd045ac67870a19150509c838c2279 for a full test report.

**Comment by branfosj** [comment]
```
Operating system identified as: 'Linux'. Native driver can not be loaded: Error loading Sys::Info::Driver::Linux::Device::CPU: Can't locate Unix/Processors.pm in @INC (you may need to install the Unix::Proc
essors module)
```

See https://github.com/easybuilders/easybuild-easyconfigs/pull/15190#discussion_r836198510

**Review by branfosj — APPROVED** [review]
lgtm

**Comment by branfosj** [comment]
Test report by @branfosj
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
bear-pg0211u03a.bear.cluster - Linux RHEL 8.5, x86_64, Intel(R) Xeon(R) Gold 6248 CPU @ 2.50GHz (cascadelake), Python 3.6.8
See https://gist.github.com/13ccb7bde9c7d19d2ff22da3d6db1aad for a full test report.

**Comment by branfosj** [comment]
Going in, thanks @boegel!

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
node3112.skitty.os - Linux CentOS Linux 7.9.2009, x86_64, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz, Python 3.6.8
See https://gist.github.com/4106d14c1194266382b68721e7a3e48c for a full test report.

**Pull request merged**
