### PR TITLE
Use external deps for safetensors and tokenizers in Transformers-4.30.2

### PR DESCRIPTION
**Pull request by Micket**
(created using `eb --new-pr`)

see https://github.com/easybuilders/easybuild-easyconfigs/issues/20718

### CODE REVIEW

**Comment by Micket** [comment]
@boegelbot please test @ generoso

**Comment by Micket** [comment]
Test report by @Micket
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in total)
vera-skylake-build - Linux Rocky Linux 8.9, x86_64, Intel Xeon Processor (Skylake, IBRS, no TSX), Python 3.6.8
See https://gist.github.com/Micket/f8eeb627cd59c6785a11280ad1913907 for a full test report.

**Comment by Micket** [comment]
@boegelbot please test @ jsc-zen3

**Review by lexming — APPROVED** [review]
LGTM

**Comment by lexming** [comment]
Merging, thanks @Micket !

**Pull request merged**
