### PR TITLE
{tools}[foss/2018a] ZeroMQ 4.2.5, PyZMQ 17.0.0

### PR DESCRIPTION
**Pull request by jhein32**

### CODE REVIEW

**Comment by jhein32** [comment]
@boegel Should I now remove the util-linux 2.32 from this PR, since nobody can reasonably use it in a foss/2018a context?

**Comment by boegel** [comment]
@jhein32 I'm ok with it if you leave it there, it's possible that `GCCcore/6.4.0` will be the base compiler for the upcoming `2018b` common toolchains as well, and then that `util-linux` easyconfig will be useful.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 5 out of 5 (5 easyconfigs in this PR)
node2691.swalot.os - Linux centos linux 7.4.1708, Intel(R) Xeon(R) CPU E5-2660 v3 @ 2.60GHz, Python 2.7.5
See https://gist.github.com/d46f8ea53a7df6edb109f38faf160293 for a full test report.

**Comment by boegel** [comment]
Going in, thanks @jhein32!

**Pull request merged**
