### PR TITLE
{tools}[GCCcore/13.2.0] jupyter-collaboration v2.1.1

### PR DESCRIPTION
**Pull request by lexming**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by verdurin** [comment]
@lexming looks like you're missing `hatch-jupyter-builder/0.9.1-GCCcore-12.3.0`

**Comment by lexming** [comment]
@verdurin right, I mixed branches, that is only needed in `GCCcore/13.2.0`. Fixed

**Comment by lexming** [comment]
@boegelbot: please test @ generoso

**Comment by lexming** [comment]
@boegelbot: please test @ generoso

**Review by smoors — APPROVED** [review]
lgtm

**Comment by smoors** [comment]
Going in, thanks @lexming!

**Pull request merged**
