### PR TITLE
{numlib}[foss/2021a] PETSc v3.15.1 w/ Python 3.9.5

### PR DESCRIPTION
**Pull request by robert-mijakovic**
(created using `eb --new-pr`)
Depends on
- [x] https://github.com/easybuilders/easybuild-easyconfigs/pull/12977

### CODE REVIEW

**Comment by robert-mijakovic** [comment]
@boegelbot please test @ generoso EB_ARGS="--from-pr 12977"

**Comment by robert-mijakovic** [comment]
@boegelbot please test @ generoso

**Comment by verdurin** [comment]
Test report by @verdurin
**SUCCESS**
Build succeeded for 5 out of 5 (1 easyconfigs in total)
nuc.lan - Linux Fedora 33, x86_64, Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz, Python 3.9.5
See https://gist.github.com/54d2ba8436055133cb8870c0e1fa4311 for a full test report.

**Comment by robert-mijakovic** [comment]
Test report by @robert-mijakovic
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
login01.meluxina.lxp.lu - Linux RHEL 8.3, x86_64, AMD EPYC 7452 32-Core Processor (zen2), Python 3.6.8
See https://gist.github.com/40c1b5a0786f073e83d77721d09eddf0 for a full test report.

**Review by verdurin — APPROVED** [review]
Looks fine.

**Comment by verdurin** [comment]
Going in, thanks @robert-mijakovic!

**Pull request merged**
