### PR TITLE
{vis}[GCCcore/10.3.0] tesseract v4.1.0

### PR DESCRIPTION
**Pull request by verdurin**
(created using `eb --new-pr`)

I did look at updating to the newer release, but that will require a completely new patch, and I ran out of time.

### CODE REVIEW

**Comment by verdurin** [comment]
@boegelbot please test @ generoso

**Comment by verdurin** [comment]
@boegelbot please test @ generoso

**Comment by smoors** [comment]
@verdurin wrong checksum?

**Comment by verdurin** [comment]
Test report by @verdurin
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
easybuild-c7.novalocal - Linux CentOS Linux 7.9.2009, x86_64, Intel Xeon Processor (Skylake, IBRS), Python 3.6.8
See https://gist.github.com/72a0919615b9fca726b92965ab11f01b for a full test report.

**Comment by verdurin** [comment]
@smoors could you try a test build? I see the same checksum on two different machines.

**Comment by smoors** [comment]
Test report by @smoors
**SUCCESS**
Build succeeded for 2 out of 2 (1 easyconfigs in total)
node307.hydra.os - Linux CentOS Linux 7.9.2009, x86_64, Intel(R) Xeon(R) Gold 6148 CPU @ 2.40GHz (skylake_avx512), Python 2.7.5
See https://gist.github.com/d03a1e0a13bfabae74adbd26453a4558 for a full test report.

**Comment by smoors** [comment]
in the failed generoso test, the checksums for both 4.1.0.tar.gz and tessdata-4.1.0.tar.gz  were the same, so clearly something must have gone wrong there.
perhaps because you launched a second test before the first results were in?

anyway, all's fine now.

**Review by smoors — APPROVED** [review]
lgtm

**Comment by smoors** [comment]
Going in, thanks @verdurin!

**Pull request merged**
