### PR TITLE
{bio}[foss/2019a,fosscuda/2019a] mhcflurry v1.2.4 w/ Python 3.7.2

### PR DESCRIPTION
**Pull request by lexming**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by lexming** [comment]
Test report by @lexming
**SUCCESS**
Build succeeded for 3 out of 3 (3 easyconfigs in this PR)
login1.cerberus.os - Linux centos linux 7.6.1810, Intel(R) Xeon(R) Gold 6126 CPU @ 2.60GHz, Python 2.7.5
See https://gist.github.com/4008218af3aa4d1c87385d692fb62a61 for a full test report.

**Comment by migueldiascosta** [comment]
@lexming moslty out of curiosity, why the downgrade of `mhcflurry`?

**Comment by migueldiascosta** [comment]
Test report by @migueldiascosta
**FAILED**
Build succeeded for 2 out of 5 (3 easyconfigs in this PR)
generoso - Linux centos linux 7.6.1810, Intel(R) Xeon(R) CPU E5-2660 v4 @ 2.00GHz, Python 3.6.8
See https://gist.github.com/871c1aa2a192cb8eb8486d71fa6eed41 for a full test report.

**Comment by migueldiascosta** [comment]
failure is not related to this PR, it's from TF on generoso...

**Comment by lexming** [comment]
@migueldiascosta version `1.4.0` depends on `Keras-2.2.5`, but we only have `2.2.4` in this toolchain. So I'll keep it in the drawer for the moment :smiley:

**Comment by boegel** [comment]
> failure is not related to this PR, it's from TF on generoso...

```
error while loading shared libraries: libcuda.so.1: cannot open shared object file: No such file or directory
```

There are no GPUs in `generoso`, so no CUDA drivers installed in the OS.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 3 out of 3 (3 easyconfigs in this PR)
node3159.skitty.os - Linux centos linux 7.7.1908, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz, Python 3.6.8
See https://gist.github.com/8a361740e3e889d1255eba59b7a4c6c1 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 3 out of 3 (3 easyconfigs in this PR)
node2587.golett.os - Linux centos linux 7.7.1908, Intel(R) Xeon(R) CPU E5-2680 v3 @ 2.50GHz, Python 2.7.5
See https://gist.github.com/42797a6459b63449bc8a475f68f5e780 for a full test report.

**Comment by boegel** [comment]
Going in, thanks @lexming!

**Pull request merged**
