### PR TITLE
patch upb CopyFrom error in protobuf-python 4.24.0

### PR DESCRIPTION
**Pull request by jfgrimm**
fixes the issue seen in https://github.com/protocolbuffers/protobuf/issues/13485

(created using `eb --new-pr`)

### CODE REVIEW

**Comment by jfgrimm** [comment]
@boegelbot: please test @ jsc-zen3

**Comment by jfgrimm** [comment]
@boegelbot: please test @ generoso

**Comment by jfgrimm** [comment]
Test report by @jfgrimm
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
gpu07.viking2.yor.alces.network - Linux Rocky Linux 8.8, x86_64, AMD EPYC 7643 48-Core Processor, 2 x NVIDIA NVIDIA A40, 535.86.10, Python 3.6.8
See https://gist.github.com/jfgrimm/a1c498f52f07cc0073f83df9b928e8ce for a full test report.

**Review by bedroge — APPROVED** [review]
Lgtm

**Comment by bedroge** [comment]
Test report by @bedroge
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
interactive1 - Linux Rocky Linux 8.9, x86_64, AMD EPYC-Milan Processor (zen2), Python 3.6.8
See https://gist.github.com/bedroge/eb0ddaf1155c0ac2907397d28e797c5a for a full test report.

**Comment by bedroge** [comment]
Going in, thanks @jfgrimm!

**Pull request merged**
