### PR TITLE
bump async-timeout to 4.0.3 in aiohttp 3.8.5

### PR DESCRIPTION
**Pull request by jfgrimm**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by jfgrimm** [comment]
this matches the version used in `SQLAlchemy`, and thus avoids the issue seen in https://github.com/easybuilders/easybuild-easyconfigs/pull/19664

**Comment by jfgrimm** [comment]
Test report by @jfgrimm
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
node017.viking2.yor.alces.network - Linux Rocky Linux 8.9, x86_64, AMD EPYC 7643 48-Core Processor, Python 3.6.8
See https://gist.github.com/jfgrimm/57bfb645edcc712c0239c004628afbb5 for a full test report.

**Comment by jfgrimm** [comment]
@boegelbot: please test @ generoso

**Comment by jfgrimm** [comment]
@boegelbot: please test @ jsc-zen3

**Comment by smoors** [comment]
Going in, thanks @jfgrimm!

**Pull request merged**
