### PR TITLE
Enforce using internal boost for bcl2fastq2

### LINKED ISSUE #14149: bcl2fastq2 fails during configuring, picks up system Boost
I tried to build `bcl2fastq2-2.20.0-GCC-10.3.0.eb` but it failed during the configuration step:

```
CMake Error at /usr/lib/x86_64-linux-gnu/cmake/Boost-1.71.0/BoostConfig.cmake:117 (find_package):
  Could not find a package configuration file provided by "boost_chrono"
  (requested version 1.71.0) with any of the following names:

    boost_chronoConfig.cmake
    boost_chrono-config.cmake

  Add the installation prefix of "boost_chrono" to CMAKE_PREFIX_PATH or set
  "boost_chrono_DIR" to a directory containing one of the above files.  If
  "boost_chrono" provides a separate development package or SDK, be sure it
  has been installed.
Call Stack (most recent call first):
  /usr/lib/x86_64-linux-gnu/cmake/Boost-1.71.0/BoostConfig.cmake:182 (boost_find_component)
  /mnt/software/easybuild/20.04/software/CMake/3.20.1-GCCcore-10.3.0/share/cmake-3.20/Modules/FindBoost.cmake:594 (fin
d_package)
  cmake/boost.cmake:85 (find_package)
  cmake/cxxConfigure.cmake:88 (bcl2fastq_find_boost)
  cxx/CMakeLists.txt:33 (include)


-- Configuring incomplete, errors occurred!
```

It should use the included Boost (1.54) but it picks up the Boost from the system (1.71, Ubuntu 18.04). The patch `bcl2fastq2-2.20.0-find-boost.patch` should take care of it but it seems like that's not enough, allthough it uses the included Boost for something as the log shows this beforehand:

```
-- Boost 1.54.0 not found. Boost will be built from the distribution...
Decompressing /dev/shm/bcl2fastq2/2.20.0/GCC-10.3.0/bcl2fastq/src/../redist/boost_1_54_0.tar.bz2
```

### PR DESCRIPTION
**Pull request by akesandgren**
(created using `eb --new-pr`)

Fixes #14149

### CODE REVIEW

**Comment by akesandgren** [comment]
@boegelbot Please test @ generoso

**Comment by akesandgren** [comment]
Test report by @akesandgren
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in total)
b-an02.hpc2n.umu.se - Linux Ubuntu 20.04, x86_64, Intel(R) Xeon(R) CPU E5-2690 v4 @ 2.60GHz, Python 3.8.10
See https://gist.github.com/4fe2413fb4ee1d452258f92b18b25358 for a full test report.

**Comment by lexming** [comment]
Test report by @lexming
**SUCCESS**
Build succeeded for 4 out of 4 (2 easyconfigs in total)
node321.hydra.os - Linux centos linux 7.9.2009, x86_64, Intel(R) Xeon(R) Gold 6148 CPU @ 2.40GHz, Python 2.7.5
See https://gist.github.com/e72706247fca416774200c04227d162c for a full test report.

**Comment by verdurin** [comment]
Test report by @verdurin
**SUCCESS**
Build succeeded for 4 out of 4 (2 easyconfigs in total)
centos7.lan - Linux centos linux 7.9.2009, x86_64, Intel Core Processor (Skylake, IBRS), Python 3.6.8
See https://gist.github.com/2c513881031ca3ca219b6766c7f22dcb for a full test report.

**Review by verdurin — APPROVED** [review]
Looks fine.

**Comment by verdurin** [comment]
Going in, thanks @akesandgren!

**Pull request merged**
