### PR TITLE
add geex and momentfit extensions for R v4.1.x

### PR DESCRIPTION
**Pull request by boegel**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in total)
node2618.swalot.os - Linux centos linux 7.9.2009, x86_64, Intel(R) Xeon(R) CPU E5-2660 v3 @ 2.60GHz (haswell), Python 3.6.8
See https://gist.github.com/2c46978ad5801db5e72ed7e5639e1fdf for a full test report.

**Comment by boegel** [comment]
@boegelbot please test @ generoso
EB_ARGS="--skip"

**Review by branfosj — APPROVED** [review]
lgtm

(Using this to test https://github.com/easybuilders/easybuild-framework/pull/3890)

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in total)
node3528.doduo.os - Linux RHEL 8.2, x86_64, AMD EPYC 7552 48-Core Processor (zen2), Python 3.6.8
See https://gist.github.com/436eeb1d8d5e21c9a7e88efbb98a1e4c for a full test report.

**Comment by branfosj** [comment]
Going in, thanks @boegel!

**Pull request merged**
