### PR TITLE
{ai}[foss/2023b] PyTorch v2.1.2

### PR DESCRIPTION
**Pull request by Flamefire**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by Micket** [comment]
Don't we want to start working with pytorch 2.2?

**Comment by Flamefire** [comment]
> Don't we want to start working with pytorch 2.2?

Indeed. However with https://github.com/easybuilders/easybuild-easyconfigs/pull/20156 we have just fixed the tests for this version so I started porting this to 2023b and see if anything goes wrong. If not, we can update to 2.2.1 and see what new stuff breaks there. I had bad experiences with updating the version and the toolchain at the same time

**Comment by casparvl** [comment]
Test report by @casparvl
**FAILED**
Build succeeded for 18 out of 19 (1 easyconfigs in total)
tcn1.local.snellius.surf.nl - Linux RHEL 8.6, x86_64, AMD EPYC 7H12 64-Core Processor, Python 3.6.8
See https://gist.github.com/casparvl/0c768aa7d7be73121dfeb55dcc3db58a for a full test report.

**Comment by casparvl** [comment]
@boegelbot please test @ generoso
CORE_CNT=16

**Comment by casparvl** [comment]
So, the three errors I see are all of the form:
```
FAILED [2.5679s] test_jit_legacy.py::TestScript::test_file_reader_no_memory_leak - AssertionError
=============================== 1 failed, 2336 passed, 151 skipped, 12 xfailed, 2 rerun in 135.92s (0:02:15) ===============================
FINISHED PRINTING LOG FILE of test_jit_legacy 1/1 (/gpfs/nvme1/1/casparl/ebbuildpath/PyTorch/2.1.2/foss-2023b/pytorch-v2.1.2/test/test-reports/test_jit_legacy_8xqb7dp6.log)

test_jit_legacy 1/1 failed!
Running test_jit_profiling 1/1 ... [2024-03-21 20:33:19.721374]
Executing ['/scratch-nvme/1/casparl/generic/software/Python/3.11.5-GCCcore-13.2.0/bin/python', '-bb', 'test_jit_profiling.py', '--shard-id=0', '--num-shards=1', '-v', '-vv', '-rfEX', '-p', 'no:xdist', '--use-pytest', '--reruns=2'] ... [2024-03-21 20:33:19.721709]

Expand the folded group to see the beginning of the log file of test_jit_profiling 1/1
##[group]PRINTING BEGINNING OF LOG FILE of test_jit_profiling 1/1 (/gpfs/nvme1/1/casparl/ebbuildpath/PyTorch/2.1.2/foss-2023b/pytorch-v2.1.2/test/test-reports/test_jit_profiling_5ic2kydo.log)
CUDA not available, skipping tests
monkeytype is not installed. Skipping tests for Profile-Directed Typing
=========================================================== test session starts ============================================================
```
I'm not sure if that's something you recognize. It _might_ be an issue on our system though: since recently, we have an issue with a memory leak in the kernel :\

**Comment by casparvl** [comment]
Also, even though this counts as three failures, they all seem to be identical, just in different test files. So... I'm actually not to concerned with this - I consider it to be one failure, note three, and there's a reasonable chance it's due to our kernel.

**Comment by casparvl** [comment]
Just to double check: do you recognize this error @Flamefire ?

**Comment by casparvl** [comment]
@boegelbot please test @ jsc-zen3
CORE_CNT=16

**Comment by casparvl** [comment]
> I'll (re)start the tests for this on our systems and if I don't see it on either I'd either increase the number of allowed failures or leave it to your site to ignore it.

Ok. Either way is fine by me btw. Let's see how things go on the test clusters. If those pass with the current amount of `max_failed_tests`, I propose to leave it as is. It's easy for us to increase it with a hook if needed.

**Comment by Flamefire** [comment]
Test report by @Flamefire
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
n1420 - Linux RHEL 8.7 (Ootpa), x86_64, Intel(R) Xeon(R) Platinum 8470 (icelake), Python 3.8.13
See https://gist.github.com/Flamefire/46a17d478eb15aa6bb2392a1921f3502 for a full test report.

**Review by casparvl — APPROVED** [review]
Lgtm!

**Comment by casparvl** [comment]
Going in, thanks @Flamefire!

**Comment by Flamefire** [comment]
Test report by @Flamefire
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
i8024 - Linux Rocky Linux 8.7 (Green Obsidian), x86_64, AMD EPYC 7352 24-Core Processor (zen2), 8 x NVIDIA NVIDIA A100-SXM4-40GB, 545.23.08, Python 3.8.13
See https://gist.github.com/Flamefire/1ebab8dc07a572b5d66adbddf95632bc for a full test report.

**Pull request merged**
