### PR TITLE
Adding easyconfig for FreeSurfer version 7.1.1 - Centos 7

### PR DESCRIPTION
**Pull request by rtripath89**

### CODE REVIEW

**Comment by verdurin** [comment]
@rtripath89 Is there an `https` version of the MCR link?

**Comment by rtripath89** [comment]
> @rtripath89 Is there an `https` version of the MCR link?

@verdurin : It looks like the same link works for both http and https. I have pushed the change.

**Comment by boegel** [comment]
@verdurin Looks like this is superseded by #12450?

**Comment by verdurin** [comment]
@boegel yes, my fault for not checking on the older PR first. Hopefully you're pleased it's available, @rtripath89

**Comment by rtripath89** [comment]
No worry Adam, till the time it’s available for me to use in Easybuild framework, for me to use in future, it works for me. :) 

Thanks.

Ravi Tripathi

**Pull request closed without merging**
