### PR TITLE
{bio,lib}[fosscuda/2020a] scikit-build v0.10.0, GROMACS v2020.5 w/ Python 3.8.2

### PR DESCRIPTION
**Pull request by dithwick**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by dithwick** [comment]
I'm just flagging up that this didn't work for me yesterday (kept getting gmxapi test errors) but worked fine for me today with no changes. No idea why but there aren't a lot of differences between this and the foss version so fingers crossed ;-)

**Comment by smoors** [comment]
@boegelbot please test @ generoso

**Comment by lexming** [comment]
Test report by @lexming
**FAILED**
Build succeeded for 2 out of 3 (2 easyconfigs in total)
node153.hydra.os - Linux centos linux 7.9.2009, x86_64, Intel(R) Xeon(R) CPU E5-2680 v2 @ 2.80GHz, Python 2.7.5
See https://gist.github.com/9eae851244c3ec79815554258cca1006 for a full test report.

**Comment by lexming** [comment]
Test report by @lexming
**FAILED**
Build succeeded for 2 out of 3 (2 easyconfigs in total)
node152.hydra.os - Linux centos linux 7.9.2009, x86_64, Intel(R) Xeon(R) CPU E5-2680 v2 @ 2.80GHz, Python 2.7.5
See https://gist.github.com/6db5713eafe49c5009d60d9707ab6f0d for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**FAILED**
Build succeeded for 1 out of 2 (2 easyconfigs in total)
node3301.joltik.os - Linux centos linux 7.9.2009, x86_64, Intel(R) Xeon(R) Gold 6242 CPU @ 2.80GHz (cascadelake), Python 3.6.8
See https://gist.github.com/bd557a98676c080a51f529bf107260fd for a full test report.

**Comment by lexming** [comment]
I have a weird issue with `test_ensemble_potential_nompi`. This test consistently fails when executed from within EB, but I cannot manually reproduce the failure in the same machine.

`test_ensemble_potential_nompi` passes if I manually load the build environment and re-run the whole `make check` or just the `sample_restraint` tests 

```
===================================== test session starts ======================================
platform linux -- Python 3.8.2, pytest-5.4.1, py-1.8.1, pluggy-0.13.1
rootdir: /theia/scratch/brussel/vo/000/bvo00005/vsc10122/easybuild/ib/build/GROMACS/2020.4/fosscuda-2020a-Python-3.8.2/gromacs-2020.4/python_packaging/sample_restraint/tests, inifile: pytest.ini
collected 3 items                                                                              

../../gromacs-2020.4/python_packaging/sample_restraint/tests/test_binding.py::test_import PASSED [ 33%]
../../gromacs-2020.4/python_packaging/sample_restraint/tests/test_binding.py::test_ensemble_potential_nompi PASSED [ 66%]
../../gromacs-2020.4/python_packaging/sample_restraint/tests/test_binding.py::test_ensemble_potential_withmpi SKIPPED [100%]

================================= 2 passed, 1 skipped in 3.07s =================================
```

I do not yet know why it fails in EB as I'm executing the exact same commands, so it must be something in the environment. In any case, if nobody else is getting such issues, please feel free to ignore my failed test report.

**Comment by dithwick** [comment]
@lexming did you test the build on a node with a GPU? Just wondering if that might be the issue.

**Comment by lexming** [comment]
@dithwick yes, it was in a node with a GPU, both with EB and running the test manually

**Comment by dithwick** [comment]
Not sure where to go with this one.  2020.5 is now available but it comes with the same version of gmxapi (1.0.1) which looks to me may have been the problem for @boegel. Should I withdraw this and try with 2020.5 instead? There is also gmxapi 0.2.0a1 pre-release available from pypi so I guess I could try that with 2020.4.

**Comment by boegel** [comment]
@dithwick I would definitely go ahead and update this PR to GROMACS 2020.5.

I'm not sure what was causing the failing tests, but I'm happy to try again and try and weed out what the issue is exactly.

**Comment by dithwick** [comment]
@boegel just tried 2020.5 and it now fails for me in the same spot as it did for you:

```
[ 72%] Building CXX object src/gromacs/mdlib/tests/CMakeFiles/mdlib-test.dir/energyoutput.cpp.o
cd /tmp/pfsxns/easybuild/GROMACS/2020.5/fosscuda-2020a-Python-3.8.2/easybuild_obj/src/gromacs/mdlib/tests && /home/csc/pfsxns/.local/easybuild/desktop/2018/software/OpenMPI/4.0.3-gcccuda-2020a/bin/mpic
make[3]: *** [python_packaging/sample_restraint/tests/CMakeFiles/gmxapi_extension_pytest] Error 1
make[3]: Leaving directory `/tmp/pfsxns/easybuild/GROMACS/2020.5/fosscuda-2020a-Python-3.8.2/easybuild_obj'
make[2]: *** [python_packaging/sample_restraint/tests/CMakeFiles/gmxapi_extension_pytest.dir/all] Error 2
make[2]: *** Waiting for unfinished jobs....
make[3]: *** [python_packaging/src/test/CMakeFiles/gmxapi_pytest] Error 1
make[3]: Leaving directory `/tmp/pfsxns/easybuild/GROMACS/2020.5/fosscuda-2020a-Python-3.8.2/easybuild_obj'
make[2]: *** [python_packaging/src/test/CMakeFiles/gmxapi_pytest.dir/all] Error 2
```

Maybe it's trying to test the extension before it is installed. Not sure why it worked for me on 2020.4 though.

**Comment by dithwick** [comment]
I found out what the problem is. The gmxapi tests are running mdrun and these are failing immediately on systems with GMX_THREAD_MPI enabled and GPUs present because OMP_NUM_THREADS is being set by the easyblock and "-ntmpi" isn't provided mdrun (same issue as in PR11440). I've provided a new patch that does seem to fix this but have also updated to GROMACS 2020.5 at the same time.

**Comment by lexming** [comment]
Test report by @lexming
**FAILED**
Build succeeded for 1 out of 2 (2 easyconfigs in total)
node250.hydra.os - Linux centos linux 7.9.2009, x86_64, Intel(R) Xeon(R) CPU E5-2650 v4 @ 2.20GHz, Python 2.7.5
See https://gist.github.com/9980843d63252e4c2099fba15c8662f8 for a full test report.

**Comment by smoors** [comment]
@lexming I've seen the failing HardwareTopologyTest before when running inside a job with only part of the node allocated. requesting a full node fixed it for me.

**Comment by lexming** [comment]
@smoors ah nice, thanks for the info! I'll try that to test this PR. Alternatively, I made a patch to disable those topology tests in GROMACS (https://github.com/lexming/easybuild-easyconfigs/blob/chem/easybuild/easyconfigs/g/GROMACS/GROMACS-2020_disable_hardware_topology_tests.patch). That can be useful to actually deploy it in the cluster. Those failed tests seem to be harmless.

**Comment by dithwick** [comment]
@lexming Would it be easier if I just grab your patch and add it to this PR?

**Comment by lexming** [comment]
@dithwick sure, IMO those tests are not useful as the hardware configuration used at build time can be rather different than at run time. If you agree to disable them, please go ahead and grab my patch.

**Comment by dithwick** [comment]
@lexming Will do. Also debating whether to up this to fosscuda 2020b. I'll do a bit of testing and will come back with something.

**Comment by lexming** [comment]
@dithwick since we do not have any GROMACS for `fosscuda/2020a`, I think it is good to add this one in it. You can also add this version to `fosscuda/2020b`, but I would do that in another PR.

**Comment by dithwick** [comment]
No worries, will do this one first.

**Comment by lexming** [comment]
Test report by @lexming
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in total)
node250.hydra.os - Linux centos linux 7.9.2009, x86_64, Intel(R) Xeon(R) CPU E5-2650 v4 @ 2.20GHz, Python 2.7.5
See https://gist.github.com/bc865785b7b76f6230c9495497ccb9e2 for a full test report.

**Review by lexming — APPROVED** [review]
LGTM

**Comment by lexming** [comment]
Going in, thanks @dithwick !

**Pull request merged**
