### PR TITLE
use MCR dependency in FreeSurfer 7.3.2 and 7.4.0

### PR DESCRIPTION
**Pull request by branfosj**
(created using `eb --new-pr`)

See discussion in #18300 and the enhanced easyblock https://github.com/easybuilders/easybuild-easyblocks/pull/2962 to catch the wrong MCR version issue.

### CODE REVIEW

**Comment by branfosj** [comment]
Test report by @branfosj
Using easyblocks from PR(s) https://github.com/easybuilders/easybuild-easyblocks/pull/2962
**SUCCESS**
Build succeeded for 5 out of 5 (5 easyconfigs in total)
bear-pg0105u03a.bear.cluster - Linux RHEL 8.6, x86_64, Intel(R) Xeon(R) Platinum 8360Y CPU @ 2.40GHz (icelake), Python 3.6.8
See https://gist.github.com/branfosj/2b77e5a9f10c0bee53c84eee5e43b037 for a full test report.

**Comment by migueldiascosta** [comment]
@boegelbot please test @ generoso EB_ARGS="--include-easyblocks-from-pr 2962"

**Comment by migueldiascosta** [comment]
@boegelbot please test @ jsc-zen2 EB_ARGS="--include-easyblocks-from-pr 2962"

**Review by migueldiascosta — APPROVED** [review]
lgtm

**Comment by migueldiascosta** [comment]
Going in, thanks @branfosj!

**Pull request merged**
