### PR TITLE
add missing Python dependency for WIEN2k 21.1 + patch to fix build failure for lapw0_mpi with libxc

### PR DESCRIPTION
**Pull request by akesandgren**
(created using `eb --new-pr`)

Depends on https://github.com/easybuilders/easybuild-easyblocks/pull/2572

### CODE REVIEW

**Comment by hajgato** [comment]
I recently had a problem running `WIEN2k-19.2-intel-2020b.eb` with slurm on multi-node environment. It still looks for `pbsdsh` or `pbsssh` (like torque/moab would be hard-coded). Would this version solve that problem (with the EasyBlock)?

**Comment by akesandgren** [comment]
The easyblock doesn't, but check the settings in the corresponding WIEN2k-21.1-intel-2021a.eb starting with the commented remote line

**Comment by hajgato** [comment]
But that's my problem. Leaving commented, it looks for `pdsdsh`, (and obviously if I comment it out, it looks for `pbsssh`)

**Comment by akesandgren** [comment]
Test report by @akesandgren
Using easyblocks from PR(s) https://github.com/easybuilders/easybuild-easyblocks/pull/2572
**FAILED**
Build succeeded for 0 out of 1 (1 easyconfigs in total)
b-an02.hpc2n.umu.se - Linux Ubuntu 20.04, x86_64, Intel(R) Xeon(R) CPU E5-2690 v4 @ 2.60GHz, Python 3.8.5
See https://gist.github.com/3cf78797ace848ba47288dc02dcbe68c for a full test report.

**Comment by akesandgren** [comment]
Bummer libxc version hickup for lapw0 trying to fix per their instructions...

**Comment by akesandgren** [comment]
Test report by @akesandgren
Using easyblocks from PR(s) https://github.com/easybuilders/easybuild-easyblocks/pull/2572
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
b-an02.hpc2n.umu.se - Linux Ubuntu 20.04, x86_64, Intel(R) Xeon(R) CPU E5-2690 v4 @ 2.60GHz, Python 3.8.5
See https://gist.github.com/5508c33c42813f0206edf6ef24099973 for a full test report.

**Comment by akesandgren** [comment]
@hajgato I haven't really tested it with multi node runs yet. Basically just set it up so one of our users can use it. But I do have his test case and will check how it works on...

**Review by boegel — APPROVED** [review]
lgtm

**Comment by boegel** [comment]
Going in, thanks @akesandgren!

**Pull request merged**
