### PR TITLE
add spdep extension to R-bundle-CRAN v2023.12

### PR DESCRIPTION
**Pull request by boegel**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by boegel** [comment]
@boegelbot please test @ generoso
EB_ARGS="--skip"

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
node3128.skitty.os - Linux RHEL 8.8, x86_64, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz (skylake_avx512), Python 3.6.8
See https://gist.github.com/boegel/b2adf1fae1f4cc33428564a13ed9cfe1 for a full test report.

**Comment by boegel** [comment]
@boegelbot please test @ jsc-zen3
EB_ARGS="--skip"

**Review by smoors — APPROVED** [review]

**Comment by smoors** [comment]
Going in, thanks @boegel!

**Pull request merged**
