### PR TITLE
use custom easyblock for installing CMake in easyconfig for CMake 3.15.3

### PR DESCRIPTION
**Pull request by Flamefire**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by Flamefire** [comment]
Test report by @Flamefire
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
taurusa3 - Linux centos linux 7.6.1810, Intel(R) Xeon(R) CPU E5-2603 v4 @ 1.70GHz, Python 2.7.5
See https://gist.github.com/91227a7fe75496e071e514ccd0a97643 for a full test report.

**Comment by boegel** [comment]
(close/re-open now https://github.com/easybuilders/easybuild-easyblocks/pull/1936 is merged)

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
generoso - Linux centos linux 7.6.1810, Intel(R) Xeon(R) CPU E5-2660 v4 @ 2.00GHz, Python 3.6.8
See https://gist.github.com/20eddb3797d741269e29943433b0a5be for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
node3102.skitty.os - Linux centos linux 7.7.1908, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz, Python 3.6.8
See https://gist.github.com/0a93d78560ed4f20aaae276cfca32aec for a full test report.

**Comment by boegel** [comment]
Going in, thanks @Flamefire!

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
node2403.golett.os - Linux centos linux 7.7.1908, Intel(R) Xeon(R) CPU E5-2680 v3 @ 2.50GHz, Python 2.7.5
See https://gist.github.com/7b9290480732677439aebb67c389e0b1 for a full test report.

**Comment by Flamefire** [comment]
I'll convert the other CMake ECs soon to have this uniform (besides that this approach is superior as the correct modules will be used even for the older ECs that are written differently and there is less code)

**Pull request merged**
