### PR TITLE
Add CPU/GPU builds for GROMACS/2019.4 with PLUMED/2.5.4

### PR DESCRIPTION
**Pull request by zao**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by zao** [comment]
This might supersede #9432 as this also contains a non-PLUMED GPU build which the PLUMED one is based on.

**Comment by zao** [comment]
Suffix is explicitly PLUMED-2.5.4 because the current version is 2.6.0 and this was a version explicitly requested by an user.

**Comment by zao** [comment]
Test report by @zao
**SUCCESS**
Build succeeded for 5 out of 5 (5 easyconfigs in this PR)
freja - Linux ubuntu 18.04, Intel(R) Core(TM) i7-8700K CPU @ 3.70GHz, Python 2.7.17
See https://gist.github.com/87d18811bde87bf53fa6a262059f7f05 for a full test report.

**Comment by jhein32** [comment]
May I ask, why this didn't make it into production?

**Comment by akesandgren** [comment]
Test report by @akesandgren
**FAILED**
Build succeeded for 3 out of 5 (5 easyconfigs in total)
b-an02.hpc2n.umu.se - Linux Ubuntu 20.04, x86_64, Intel(R) Xeon(R) CPU E5-2690 v4 @ 2.60GHz, Python 3.8.10
See https://gist.github.com/akesandgren/2a664676268576163f03f3f97390cb2b for a full test report.

**Comment by akesandgren** [comment]
Test report by @akesandgren
**SUCCESS**
Build succeeded for 5 out of 5 (5 easyconfigs in total)
b-an02.hpc2n.umu.se - Linux Ubuntu 20.04, x86_64, Intel(R) Xeon(R) CPU E5-2690 v4 @ 2.60GHz, Python 3.8.10
See https://gist.github.com/akesandgren/a959d705ad3a52b6743d3e790f79a31b for a full test report.

**Review by akesandgren — APPROVED** [review]
LGTM

**Comment by akesandgren** [comment]
Going in, thanks @zao!

**Pull request merged**
