### PR TITLE
{vis}[foss/2020b] ncview v2.1.7

### PR DESCRIPTION
**Pull request by DirectorSloan**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by verdurin** [comment]
@boegelbot please test @ generoso

**Comment by verdurin** [comment]
Test report by @verdurin
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
easybuild-c7.novalocal - Linux CentOS Linux 7.9.2009, x86_64, Intel Xeon Processor (Skylake, IBRS), Python 3.6.8
See https://gist.github.com/bafe7139fd40123a8c96a1ffaf7bee69 for a full test report.

**Comment by bedroge** [comment]
@boegelbot please test @ jsc-zen2

**Comment by bedroge** [comment]
Test report by @bedroge
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
pg-interactive.hpc.rug.nl - Linux CentOS Linux 7.9.2009, x86_64, Intel(R) Xeon(R) CPU E5-2680 v3 @ 2.50GHz, Python 3.6.8
See https://gist.github.com/9a4cff5568a5cc324ce997c6b2b10f4e for a full test report.

**Review by bedroge — COMMENTED** [review]
Was there a particular reason to promote this to the `foss` toolchain? The most recent versions of `ncview` are built with `gompi` toolchain (which is a subtoolchain of `foss`), see https://github.com/easybuilders/easybuild-easyconfigs/tree/develop/easybuild/easyconfigs/n/ncview/

**Comment by boegel** [comment]
Closing this, doesn't make sense to have this at `foss/2020b` indeed.

@DirectorSloan If this is still relevant, please re-open with `gompi/2020b` toolchain instead (and maybe bump to `2.1.8`, cfr. `ncview-2.1.8-gompi-2020a.eb` contributed in #12626

**Pull request closed without merging**
