### PR TITLE
{lang}[foss/2018b] Tkinter v3.7.0

### PR DESCRIPTION
**Pull request by jose-d**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by jose-d** [comment]
Test report by @jose-d
**FAILED**
Build succeeded for 0 out of 1 (1 easyconfigs in this PR)
koios2 - Linux centos linux 7.3.1611, Intel(R) Xeon(R) Gold 6130 CPU @ 2.10GHz, Python 2.7.5
See https://gist.github.com/761f6a060717677282b6abbe96322b1f for a full test report.

**Comment by jose-d** [comment]
> Test report by @jose-d
> **FAILED**

..

`cmd "tar xzf ~/.config/easybuild/t/Tkinter/Python-3.7.0.tgz" exited with exit code 2`

smth cheesy here.. I'm on it..

**Comment by jose-d** [comment]
Test report by @jose-d
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
koios2 - Linux centos linux 7.3.1611, Intel(R) Xeon(R) Gold 6130 CPU @ 2.10GHz, Python 2.7.5
See https://gist.github.com/f8b0e5fe9f71185454a65871af1f7633 for a full test report.

**Comment by jose-d** [comment]
@boegel when you'd have some time, could you pls. check this case of @boegelbot? 
I don't see anything wrong here*
* last famous words.

**Comment by boegel** [comment]
@jose-d There's no problem with @boegelbot, it's correctly reporting a failing test.

The test fail because you have introduced an additional `Python` version that is used as a dependency in easyconfigs using a `2018b` toolchain. We only allow 2 versions (Python 2.x & 3.x), to maximize compatibility between easyconfigs that use a `2018b` toolchain.

For the `2018b` generation of easyconfigs, we're sticking to Python 3.6.6 because we ran into problems with Python 3.7.0 due to backwards-incompatible changes that were not taken into account yet by several Python packages, see #6682 for more information.

If you're adding this `Tkinter` easyconfig because you need it as a dependency for something else, please stick to the existing `Tkinter` 3.6.6 instead for the `2018b` generation of easyconfigs.

**Comment by jose-d** [comment]
ah, thx,

> as a dependency for something else, please stick to the existing Tkinter 3.6.6 instead for the 2018b generation of easyconfigs.

..yes, for `matplotlib` in Py3.7 project. 
So let's keep it out from the upstream till `foss2019(a|b)` will be out.

**Pull request closed without merging**
