### PR TITLE
{tools}[system/system] VTune v2023.2.0

### PR DESCRIPTION
**Pull request by xinan1911**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by xinan1911** [comment]
"--accept-eula-for=Intel-oneAPI" is needed when run eb command to solve the intel license

**Comment by branfosj** [comment]
@boegelbot please test @ generoso

**Comment by branfosj** [comment]
Test report by @branfosj
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
bear-pg0105u03a.bear.cluster - Linux RHEL 8.6, x86_64, Intel(R) Xeon(R) Platinum 8360Y CPU @ 2.40GHz (icelake), Python 3.6.8
See https://gist.github.com/branfosj/45096e338bfed40f57aa53c5727b4888 for a full test report.

**Review by branfosj — APPROVED** [review]

**Comment by branfosj** [comment]
Going in, thanks @xinan1911!

**Pull request merged**
