### PR TITLE
{perf}[foss/2019a] Paraver v4.8.1

### PR DESCRIPTION
**Pull request by boegel**
(created using `eb --new-pr`)
requires https://github.com/easybuilders/easybuild-easyblocks/pull/1790

### CODE REVIEW

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
node3129.skitty.os - Linux centos linux 7.6.1810, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz, Python 2.7.5
See https://gist.github.com/7f88e4c36469901ae1296f60e821181b for a full test report.

**Comment by lexming** [comment]
Test report by @lexming
**FAILED**
Build succeeded for 19 out of 20 (1 easyconfigs in this PR)
login2.cerberus.os - Linux centos linux 7.6.1810, Intel(R) Xeon(R) Gold 6126 CPU @ 2.60GHz, Python 2.7.5
See https://gist.github.com/6394eddd1547e08c3d9b1e573d543d91 for a full test report.

**Comment by lexming** [comment]
Fails at configure step with `Failed to move to ptools_common_files: [Errno 2] No such file or directory: 'ptools_common_files'`

**Comment by lexming** [comment]
Test report by @lexming
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
login2.cerberus.os - Linux centos linux 7.6.1810, Intel(R) Xeon(R) Gold 6126 CPU @ 2.60GHz, Python 2.7.5
See https://gist.github.com/37aed7d8a774fb28e19855ff2a6aa024 for a full test report.

**Comment by lexming** [comment]
The updated `paraver` easyblock works :+1:

**Comment by smoors** [comment]
Going in, thanks @boegel!

**Pull request merged**
