### PR TITLE
{numlib}[foss/2021a] SuiteSparse v5.10.1

### PR DESCRIPTION
**Pull request by smoors**
(created using `eb --new-pr`)
depends on easyblock PR:
- [x] https://github.com/easybuilders/easybuild-easyblocks/pull/2627

### CODE REVIEW

**Comment by smoors** [comment]
@boegelbot: please test @ generoso EB_ARGS="--include-easyblocks-from-pr 2627"

**Comment by smoors** [comment]
Test report by @smoors
Using easyblocks from PR(s) https://github.com/easybuilders/easybuild-easyblocks/pull/2627
**SUCCESS**
Build succeeded for 2 out of 2 (1 easyconfigs in total)
node250.hydra.os - Linux centos linux 7.9.2009, x86_64, Intel(R) Xeon(R) CPU E5-2650 v4 @ 2.20GHz (broadwell), 1 x NVIDIA Tesla P100-PCIE-16GB, 470.82.01, Python 2.7.5
See https://gist.github.com/ec6b7fd9e23046b615376d2d8b9281af for a full test report.

**Review by branfosj — APPROVED** [review]
lgtm

**Comment by branfosj** [comment]
Test report by @branfosj
**SUCCESS**
Build succeeded for 2 out of 2 (1 easyconfigs in total)
bear-pg0212u17a.bear.cluster - Linux RHEL 8.5, x86_64, Intel(R) Xeon(R) CPU E5-2640 v4 @ 2.40GHz (broadwell), 1 x NVIDIA Tesla P100-PCIE-16GB, 470.57.02, Python 3.6.8
See https://gist.github.com/4a5dfb58ea25e3e5df408820db824375 for a full test report.

**Comment by branfosj** [comment]
Test report by @branfosj
**SUCCESS**
Build succeeded for 2 out of 2 (1 easyconfigs in total)
bear-pg0103u04a.bear.cluster - Linux RHEL 8.5, x86_64, Intel(R) Xeon(R) Gold 6330 CPU @ 2.00GHz (icelake), 2 x NVIDIA NVIDIA A30, 470.57.02, Python 3.6.8
See https://gist.github.com/4cbbbbbfc4d7c5d7ab057ca2705f0ca1 for a full test report.

**Comment by branfosj** [comment]
Going in, thanks @smoors!

**Pull request merged**
