### PR TITLE
{bio}[intel/2017a] AUGUSTUS 3.2.3 source_urls corrected (REVIEW)

### PR DESCRIPTION
**Pull request by hajgato**

### CODE REVIEW

**Comment by verdurin** [comment]
Traceback I saw during a test build:
```
Traceback (most recent call last):
  File "/usr/lib64/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib64/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/camp/apps/eb/software/EasyBuild/3.2.1/lib/python2.7/site-packages/easybuild_framework-3.2.1-py2.7.egg/easybuild/main.py", line 475, in <module>
    main()
  File "/camp/apps/eb/software/EasyBuild/3.2.1/lib/python2.7/site-packages/easybuild_framework-3.2.1-py2.7.egg/easybuild/main.py", line 456, in main
    test_report_msg = overall_test_report(ecs_with_res, len(paths), overall_success, success_msg, init_session_state)
  File "/camp/apps/eb/software/EasyBuild/3.2.1/lib/python2.7/site-packages/easybuild_framework-3.2.1-py2.7.egg/easybuild/tools/testing.py", line 298, in overall_test_report
    txt = post_easyconfigs_pr_test_report(pr_nr, test_report, msg, init_session_state, success)
  File "/camp/apps/eb/software/EasyBuild/3.2.1/lib/python2.7/site-packages/easybuild_framework-3.2.1-py2.7.egg/easybuild/tools/testing.py", line 274, in post_easyconfigs_pr_test_report
    post_comment_in_issue(pr_nr, comment, github_user=user)
  File "/camp/apps/eb/software/EasyBuild/3.2.1/lib/python2.7/site-packages/easybuild_framework-3.2.1-py2.7.egg/easybuild/tools/github.py", line 451, in post_comment_in_issue
    status, data = pr_url.comments.post(body={'body': txt})
  File "/camp/apps/eb/software/EasyBuild/3.2.1/lib/python2.7/site-packages/vsc_base-2.5.8-py2.7.egg/vsc/utils/rest.py", line 144, in post
    return self.request(self.POST, url, json.dumps(body), headers, content_type='application/json')
  File "/camp/apps/eb/software/EasyBuild/3.2.1/lib/python2.7/site-packages/vsc_base-2.5.8-py2.7.egg/vsc/utils/rest.py", line 175, in request
    conn = self.get_connection(method, url, body, headers)
  File "/camp/apps/eb/software/EasyBuild/3.2.1/lib/python2.7/site-packages/vsc_base-2.5.8-py2.7.egg/vsc/utils/rest.py", line 206, in get_connection
    connection = self.opener.open(request)
  File "/usr/lib64/python2.7/urllib2.py", line 437, in open
    response = meth(req, response)
  File "/usr/lib64/python2.7/urllib2.py", line 550, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib64/python2.7/urllib2.py", line 469, in error
    result = self._call_chain(*args)
  File "/usr/lib64/python2.7/urllib2.py", line 409, in _call_chain
    result = func(*args)
  File "/usr/lib64/python2.7/urllib2.py", line 635, in http_error_302
    new = self.redirect_request(req, fp, code, msg, headers, newurl)
  File "/usr/lib64/python2.7/urllib2.py", line 596, in redirect_request
    raise HTTPError(req.get_full_url(), code, msg, headers, fp)
urllib2.HTTPError: HTTP Error 307: Temporary Redirect
```

**Comment by hajgato** [comment]
@verdurin I do not understand why. For me it worked, and clearly old versions are in the `old` directory. (Only the current version is in the original directory)

**Comment by verdurin** [comment]
Test report by @verdurin
**SUCCESS**
Build succeeded for 0 out of 0 (1 easyconfigs in this PR)
ca021.camp.thecrick.org - Linux centos linux 7.3.1611, Intel(R) Xeon(R) CPU E5-2640 v3 @ 2.60GHz, Python 2.7.5
See https://gist.github.com/1f79eb41c1c5c2890c8caa4c79aee8b6 for a full test report.

**Comment by verdurin** [comment]
Test report by @verdurin
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
ca021.camp.thecrick.org - Linux centos linux 7.3.1611, Intel(R) Xeon(R) CPU E5-2640 v3 @ 2.60GHz, Python 2.7.5
See https://gist.github.com/6579adf30530655b69ca5eabe72503f7 for a full test report.

**Comment by verdurin** [comment]
Going in, thanks @hajgato!

**Pull request merged**
