### PR TITLE
{vis}[foss/2019b] Ferret v7.5.0

### PR DESCRIPTION
**Pull request by smoors**
(created using `eb --new-pr`)

depends updated easyblock ~~https://github.com/easybuilders/easybuild-easyblocks/pull/1956~~

### CODE REVIEW

**Comment by smoors** [comment]
Test report by @smoors
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
node369.hydra.os - Linux centos linux 7.7.1908, Intel(R) Xeon(R) Gold 6148 CPU @ 2.40GHz, Python 2.7.5
See https://gist.github.com/4fa2d2090d7ea286fc6fe25c323e1894 for a full test report.

**Comment by verdurin** [comment]
Test report by @verdurin
**FAILED**
Build succeeded for 0 out of 1 (1 easyconfigs in this PR)
generoso - Linux centos linux 7.6.1810, Intel(R) Xeon(R) CPU E5-2660 v4 @ 2.00GHz, Python 3.6.8
See https://gist.github.com/ef1f2646a7e3394b4f1a0debda6d5317 for a full test report.

**Comment by verdurin** [comment]
Test report by @verdurin
**FAILED**
Build succeeded for 0 out of 1 (1 easyconfigs in this PR)
easybuild.novalocal - Linux centos linux 7.7.1908, Intel Xeon Processor (Skylake, IBRS), Python 2.7.5
See https://gist.github.com/ecc8557ff7ffef6d3cea9aaaead1fd12 for a full test report.

**Comment by verdurin** [comment]
@smoors When I try to test this it complains that it's missing `netCDF-Fortran/4.5.2-foss-2019b`

**Comment by verdurin** [comment]
Test report by @verdurin
**FAILED**
Build succeeded for 5 out of 6 (1 easyconfigs in this PR)
easybuild.novalocal - Linux centos linux 7.7.1908, Intel Xeon Processor (Skylake, IBRS), Python 2.7.5
See https://gist.github.com/90f856a5c3241cc30a592fb3782e173c for a full test report.

**Comment by verdurin** [comment]
@smoors Here is the build error:
```
make[2]: Entering directory `/eb/maint/build/Ferret/7.5.0/foss-2019b/Ferret-7.5.0/fer'
mv ferret_c ferret_c_`ls -l ferret_c | awk '{print $6"_"$7}' | tr [A-Z] [a-z]`
ls: cannot access ferret_c: No such file or directory
mv: cannot stat 'ferret_c': No such file or directory
make[2]: [update] Error 1 (ignored)
make update_date DATE=`/bin/date +%D`
make[3]: Entering directory `/eb/maint/build/Ferret/7.5.0/foss-2019b/Ferret-7.5.0/fer'
rm -f special/xmake_date_data.[Ffo]
sed "s&xxxxxxxx&02/25/20&" <special/xmake_date_data.template >special/xmake_date_data.F
make[3]: Leaving directory `/eb/maint/build/Ferret/7.5.0/foss-2019b/Ferret-7.5.0/fer'
rm -f special/xrevision_type_data.[Ffo]
sed -e 's&mmmmmmmm&(optimized/)&' -e 's&(/&(&' -e 's&/)&)&' < special/xrevision_type_data.template > special/xrevision_type_data.F
rm -f special/xplatform_type_data.[Ffo]
sed -e 's&mmmmmmmm&Linux 3.10.0-1062.4.1.el7.x86_64 64-bit&' -e 's&(/&(&' -e 's&/)&)&' < special/xplatform_type_data.template > special/xplatform_type_data.F
(cd special; make)
make[3]: Entering directory `/eb/maint/build/Ferret/7.5.0/foss-2019b/Ferret-7.5.0/fer/special'
/eb/maint/software/GCCcore/8.3.0/bin/gcc -m64 -fPIC -Dcrptd_cat_argument -Ddouble_p -Dgfortran -Dreclen_in_bytes -Dunix -Dxgks -DG77 -DG77_SIGNAL -DINTERNAL_READ_FORMAT_BUG -DMANDATORY_FORMAT_WIDTHS -DNEED_IAND -DNO_DOUBLE_ESCAPE_SLASH -DNO_OPEN_CARRIAGECONTROL -DNO_OPEN_SHARED -DNO_OPEN_READONLY -DNO_OPEN_RECORDTYPE -DNO_PASSED_CONCAT -DNO_PREPEND_STRING -DSTAR_1_SUPPORTED -DX_REFRESH -I. -I/eb/maint/software/netCDF/4.7.1-gompi-2019b/../include -I/eb/maint/build/Ferret/7.5.0/foss-2019b/Ferret-7.5.0//fer/common -I/eb/maint/build/Ferret/7.5.0/foss-2019b/Ferret-7.5.0//fmt/cmn -I/eb/maint/build/Ferret/7.5.0/foss-2019b/Ferret-7.5.0//ppl/tmap_inc -I/eb/maint/build/Ferret/7.5.0/foss-2019b/Ferret-7.5.0//ppl/include -I/eb/maint/build/Ferret/7.5.0/foss-2019b/Ferret-7.5.0//xgks/src/lib -I/eb/maint/build/Ferret/7.5.0/foss-2019b/Ferret-7.5.0//xgks/port -O -DNDEBUG -I/eb/maint/software/Java/11.0.2/include -I/eb/maint/software/libreadline/8.0-GCCcore-8.3.0/include -I/eb/maint/software/ncurses/6.1-GCCcore-8.3.0/include -I/eb/maint/software/cURL/7.66.0-GCCcore-8.3.0/include -I/eb/maint/software/Szip/2.1.1-GCCcore-8.3.0/include -I/eb/maint/software/zlib/1.2.11-GCCcore-8.3.0/include -I/eb/maint/software/HDF5/1.10.5-gompi-2019b/include -I/eb/maint/software/netCDF-Fortran/4.5.2-gompi-2019b/include -I/eb/maint/software/netCDF/4.7.1-gompi-2019b/include -I/eb/maint/software/X11/20190717-GCCcore-8.3.0/include -I/eb/maint/software/FFTW/3.3.8-gompi-2019b/include -I/eb/maint/software/ScaLAPACK/2.0.2-gompi-2019b/include -I/eb/maint/software/OpenBLAS/0.3.7-GCC-8.3.0/include  -c -o FerMem_routines.o FerMem_routines.c
/eb/maint/software/GCCcore/8.3.0/bin/gfortran -m64 -fPIC -fno-automatic -fno-second-underscore -fdollar-ok -ffixed-line-length-132 -ffpe-trap=overflow -fimplicit-none -fdefault-real-8 -fdefault-double-8 -Dcrptd_cat_argument -Ddouble_p -Dgfortran -Dreclen_in_bytes -Dunix -Dxgks -DG77 -DG77_SIGNAL -DINTERNAL_READ_FORMAT_BUG -DMANDATORY_FORMAT_WIDTHS -DNEED_IAND -DNO_DOUBLE_ESCAPE_SLASH -DNO_OPEN_CARRIAGECONTROL -DNO_OPEN_SHARED -DNO_OPEN_READONLY -DNO_OPEN_RECORDTYPE -DNO_PASSED_CONCAT -DNO_PREPEND_STRING -DSTAR_1_SUPPORTED -DX_REFRESH -I. -I/eb/maint/software/netCDF/4.7.1-gompi-2019b/../include -I/eb/maint/build/Ferret/7.5.0/foss-2019b/Ferret-7.5.0//fer/common -I/eb/maint/build/Ferret/7.5.0/foss-2019b/Ferret-7.5.0//fmt/cmn -I/eb/maint/build/Ferret/7.5.0/foss-2019b/Ferret-7.5.0//ppl/tmap_inc -I/eb/maint/build/Ferret/7.5.0/foss-2019b/Ferret-7.5.0//ppl/include -I/eb/maint/build/Ferret/7.5.0/foss-2019b/Ferret-7.5.0//xgks/src/lib -I/eb/maint/build/Ferret/7.5.0/foss-2019b/Ferret-7.5.0//xgks/port -O -DNDEBUG -c aix_routines.F -o aix_routines.o
f951: Warning: Nonexistent include directory '/eb/maint/software/netCDF/4.7.1-gompi-2019b/../include' [-Wmissing-include-dirs]
/eb/maint/software/GCCcore/8.3.0/bin/gfortran -m64 -fPIC -fno-automatic -fno-second-underscore -fdollar-ok -ffixed-line-length-132 -ffpe-trap=overflow -fimplicit-none -fdefault-real-8 -fdefault-double-8 -Dcrptd_cat_argument -Ddouble_p -Dgfortran -Dreclen_in_bytes -Dunix -Dxgks -DG77 -DG77_SIGNAL -DINTERNAL_READ_FORMAT_BUG -DMANDATORY_FORMAT_WIDTHS -DNEED_IAND -DNO_DOUBLE_ESCAPE_SLASH -DNO_OPEN_CARRIAGECONTROL -DNO_OPEN_SHARED -DNO_OPEN_READONLY -DNO_OPEN_RECORDTYPE -DNO_PASSED_CONCAT -DNO_PREPEND_STRING -DSTAR_1_SUPPORTED -DX_REFRESH -I. -I/eb/maint/software/netCDF/4.7.1-gompi-2019b/../include -I/eb/maint/build/Ferret/7.5.0/foss-2019b/Ferret-7.5.0//fer/common -I/eb/maint/build/Ferret/7.5.0/foss-2019b/Ferret-7.5.0//fmt/cmn -I/eb/maint/build/Ferret/7.5.0/foss-2019b/Ferret-7.5.0//ppl/tmap_inc -I/eb/maint/build/Ferret/7.5.0/foss-2019b/Ferret-7.5.0//ppl/include -I/eb/maint/build/Ferret/7.5.0/foss-2019b/Ferret-7.5.0//xgks/src/lib -I/eb/maint/build/Ferret/7.5.0/foss-2019b/Ferret-7.5.0//xgks/port -O -DNDEBUG -c fake_gks.F -o fake_gks.o
f951: Warning: Nonexistent include directory '/eb/maint/software/netCDF/4.7.1-gompi-2019b/../include' [-Wmissing-include-dirs]
/eb/maint/software/GCCcore/8.3.0/bin/gfortran -m64 -fPIC -fno-automatic -fno-second-underscore -fdollar-ok -ffixed-line-length-132 -ffpe-trap=overflow -fimplicit-none -fdefault-real-8 -fdefault-double-8 -Dcrptd_cat_argument -Ddouble_p -Dgfortran -Dreclen_in_bytes -Dunix -Dxgks -DG77 -DG77_SIGNAL -DINTERNAL_READ_FORMAT_BUG -DMANDATORY_FORMAT_WIDTHS -DNEED_IAND -DNO_DOUBLE_ESCAPE_SLASH -DNO_OPEN_CARRIAGECONTROL -DNO_OPEN_SHARED -DNO_OPEN_READONLY -DNO_OPEN_RECORDTYPE -DNO_PASSED_CONCAT -DNO_PREPEND_STRING -DSTAR_1_SUPPORTED -DX_REFRESH -I. -I/eb/maint/software/netCDF/4.7.1-gompi-2019b/../include -I/eb/maint/build/Ferret/7.5.0/foss-2019b/Ferret-7.5.0//fer/common -I/eb/maint/build/Ferret/7.5.0/foss-2019b/Ferret-7.5.0//fmt/cmn -I/eb/maint/build/Ferret/7.5.0/foss-2019b/Ferret-7.5.0//ppl/tmap_inc -I/eb/maint/build/Ferret/7.5.0/foss-2019b/Ferret-7.5.0//ppl/include -I/eb/maint/build/Ferret/7.5.0/foss-2019b/Ferret-7.5.0//xgks/src/lib -I/eb/maint/build/Ferret/7.5.0/foss-2019b/Ferret-7.5.0//xgks/port -O -DNDEBUG -c fake_ppl.F -o fake_ppl.o
f951: Warning: Nonexistent include directory '/eb/maint/software/netCDF/4.7.1-gompi-2019b/../include' [-Wmissing-include-dirs]
/eb/maint/software/GCCcore/8.3.0/bin/gfortran -m64 -fPIC -fno-automatic -fno-second-underscore -fdollar-ok -ffixed-line-length-132 -ffpe-trap=overflow -fimplicit-none -fdefault-real-8 -fdefault-double-8 -Dcrptd_cat_argument -Ddouble_p -Dgfortran -Dreclen_in_bytes -Dunix -Dxgks -DG77 -DG77_SIGNAL -DINTERNAL_READ_FORMAT_BUG -DMANDATORY_FORMAT_WIDTHS -DNEED_IAND -DNO_DOUBLE_ESCAPE_SLASH -DNO_OPEN_CARRIAGECONTROL -DNO_OPEN_SHARED -DNO_OPEN_READONLY -DNO_OPEN_RECORDTYPE -DNO_PASSED_CONCAT -DNO_PREPEND_STRING -DSTAR_1_SUPPORTED -DX_REFRESH -I. -I/eb/maint/software/netCDF/4.7.1-gompi-2019b/../include -I/eb/maint/build/Ferret/7.5.0/foss-2019b/Ferret-7.5.0//fer/common -I/eb/maint/build/Ferret/7.5.0/foss-2019b/Ferret-7.5.0//fmt/cmn -I/eb/maint/build/Ferret/7.5.0/foss-2019b/Ferret-7.5.0//ppl/tmap_inc -I/eb/maint/build/Ferret/7.5.0/foss-2019b/Ferret-7.5.0//ppl/include -I/eb/maint/build/Ferret/7.5.0/foss-2019b/Ferret-7.5.0//xgks/src/lib -I/eb/maint/build/Ferret/7.5.0/foss-2019b/Ferret-7.5.0//xgks/port -O -DNDEBUG -c fake_tmio.F -o fake_tmio.o
f951: Warning: Nonexistent include directory '/eb/maint/software/netCDF/4.7.1-gompi-2019b/../include' [-Wmissing-include-dirs]
/eb/maint/software/GCCcore/8.3.0/bin/gfortran -m64 -fPIC -fno-automatic -fno-second-underscore -fdollar-ok -ffixed-line-length-132 -ffpe-trap=overflow -fimplicit-none -fdefault-real-8 -fdefault-double-8 -Dcrptd_cat_argument -Ddouble_p -Dgfortran -Dreclen_in_bytes -Dunix -Dxgks -DG77 -DG77_SIGNAL -DINTERNAL_READ_FORMAT_BUG -DMANDATORY_FORMAT_WIDTHS -DNEED_IAND -DNO_DOUBLE_ESCAPE_SLASH -DNO_OPEN_CARRIAGECONTROL -DNO_OPEN_SHARED -DNO_OPEN_READONLY -DNO_OPEN_RECORDTYPE -DNO_PASSED_CONCAT -DNO_PREPEND_STRING -DSTAR_1_SUPPORTED -DX_REFRESH -I. -I/eb/maint/software/netCDF/4.7.1-gompi-2019b/../include -I/eb/maint/build/Ferret/7.5.0/foss-2019b/Ferret-7.5.0//fer/common -I/eb/maint/build/Ferret/7.5.0/foss-2019b/Ferret-7.5.0//fmt/cmn -I/eb/maint/build/Ferret/7.5.0/foss-2019b/Ferret-7.5.0//ppl/tmap_inc -I/eb/maint/build/Ferret/7.5.0/foss-2019b/Ferret-7.5.0//ppl/include -I/eb/maint/build/Ferret/7.5.0/foss-2019b/Ferret-7.5.0//xgks/src/lib -I/eb/maint/build/Ferret/7.5.0/foss-2019b/Ferret-7.5.0//xgks/port -O -DNDEBUG -c fakes3.F -o fakes3.o
f951: Warning: Nonexistent include directory '/eb/maint/software/netCDF/4.7.1-gompi-2019b/../include' [-Wmissing-include-dirs]
/eb/maint/software/GCCcore/8.3.0/bin/gfortran -m64 -fPIC -fno-automatic -fno-second-underscore -fdollar-ok -ffixed-line-length-132 -ffpe-trap=overflow -fimplicit-none -fdefault-real-8 -fdefault-double-8 -Dcrptd_cat_argument -Ddouble_p -Dgfortran -Dreclen_in_bytes -Dunix -Dxgks -DG77 -DG77_SIGNAL -DINTERNAL_READ_FORMAT_BUG -DMANDATORY_FORMAT_WIDTHS -DNEED_IAND -DNO_DOUBLE_ESCAPE_SLASH -DNO_OPEN_CARRIAGECONTROL -DNO_OPEN_SHARED -DNO_OPEN_READONLY -DNO_OPEN_RECORDTYPE -DNO_PASSED_CONCAT -DNO_PREPEND_STRING -DSTAR_1_SUPPORTED -DX_REFRESH -I. -I/eb/maint/software/netCDF/4.7.1-gompi-2019b/../include -I/eb/maint/build/Ferret/7.5.0/foss-2019b/Ferret-7.5.0//fer/common -I/eb/maint/build/Ferret/7.5.0/foss-2019b/Ferret-7.5.0//fmt/cmn -I/eb/maint/build/Ferret/7.5.0/foss-2019b/Ferret-7.5.0//ppl/tmap_inc -I/eb/maint/build/Ferret/7.5.0/foss-2019b/Ferret-7.5.0//ppl/include -I/eb/maint/build/Ferret/7.5.0/foss-2019b/Ferret-7.5.0//xgks/src/lib -I/eb/maint/build/Ferret/7.5.0/foss-2019b/Ferret-7.5.0//xgks/port -O -DNDEBUG -c ferret_dispatch.F -o ferret_dispatch.o
f951: Warning: Nonexistent include directory '/eb/maint/software/netCDF/4.7.1-gompi-2019b/../include' [-Wmissing-include-dirs]
/eb/maint/software/GCCcore/8.3.0/bin/gfortran -m64 -fPIC -fno-automatic -fno-second-underscore -fdollar-ok -ffixed-line-length-132 -ffpe-trap=overflow -fimplicit-none -fdefault-real-8 -fdefault-double-8 -Dcrptd_cat_argument -Ddouble_p -Dgfortran -Dreclen_in_bytes -Dunix -Dxgks -DG77 -DG77_SIGNAL -DINTERNAL_READ_FORMAT_BUG -DMANDATORY_FORMAT_WIDTHS -DNEED_IAND -DNO_DOUBLE_ESCAPE_SLASH -DNO_OPEN_CARRIAGECONTROL -DNO_OPEN_SHARED -DNO_OPEN_READONLY -DNO_OPEN_RECORDTYPE -DNO_PASSED_CONCAT -DNO_PREPEND_STRING -DSTAR_1_SUPPORTED -DX_REFRESH -I. -I/eb/maint/software/netCDF/4.7.1-gompi-2019b/../include -I/eb/maint/build/Ferret/7.5.0/foss-2019b/Ferret-7.5.0//fer/common -I/eb/maint/build/Ferret/7.5.0/foss-2019b/Ferret-7.5.0//fmt/cmn -I/eb/maint/build/Ferret/7.5.0/foss-2019b/Ferret-7.5.0//ppl/tmap_inc -I/eb/maint/build/Ferret/7.5.0/foss-2019b/Ferret-7.5.0//ppl/include -I/eb/maint/build/Ferret/7.5.0/foss-2019b/Ferret-7.5.0//xgks/src/lib -I/eb/maint/build/Ferret/7.5.0/foss-2019b/Ferret-7.5.0//xgks/port -O -DNDEBUG -c gui_fakes.F -o gui_fakes.o
f951: Warning: Nonexistent include directory '/eb/maint/software/netCDF/4.7.1-gompi-2019b/../include' [-Wmissing-include-dirs]
/eb/maint/software/GCCcore/8.3.0/bin/gfortran -m64 -fPIC -fno-automatic -fno-second-underscore -fdollar-ok -ffixed-line-length-132 -ffpe-trap=overflow -fimplicit-none -fdefault-real-8 -fdefault-double-8 -Dcrptd_cat_argument -Ddouble_p -Dgfortran -Dreclen_in_bytes -Dunix -Dxgks -DG77 -DG77_SIGNAL -DINTERNAL_READ_FORMAT_BUG -DMANDATORY_FORMAT_WIDTHS -DNEED_IAND -DNO_DOUBLE_ESCAPE_SLASH -DNO_OPEN_CARRIAGECONTROL -DNO_OPEN_SHARED -DNO_OPEN_READONLY -DNO_OPEN_RECORDTYPE -DNO_PASSED_CONCAT -DNO_PREPEND_STRING -DSTAR_1_SUPPORTED -DX_REFRESH -I. -I/eb/maint/software/netCDF/4.7.1-gompi-2019b/../include -I/eb/maint/build/Ferret/7.5.0/foss-2019b/Ferret-7.5.0//fer/common -I/eb/maint/build/Ferret/7.5.0/foss-2019b/Ferret-7.5.0//fmt/cmn -I/eb/maint/build/Ferret/7.5.0/foss-2019b/Ferret-7.5.0//ppl/tmap_inc -I/eb/maint/build/Ferret/7.5.0/foss-2019b/Ferret-7.5.0//ppl/include -I/eb/maint/build/Ferret/7.5.0/foss-2019b/Ferret-7.5.0//xgks/src/lib -I/eb/maint/build/Ferret/7.5.0/foss-2019b/Ferret-7.5.0//xgks/port -O -DNDEBUG -c linux_routines.F -o linux_routines.o
f951: Warning: Nonexistent include directory '/eb/maint/software/netCDF/4.7.1-gompi-2019b/../include' [-Wmissing-include-dirs]
/eb/maint/software/GCCcore/8.3.0/bin/gfortran -m64 -fPIC -fno-automatic -fno-second-underscore -fdollar-ok -ffixed-line-length-132 -ffpe-trap=overflow -fimplicit-none -fdefault-real-8 -fdefault-double-8 -Dcrptd_cat_argument -Ddouble_p -Dgfortran -Dreclen_in_bytes -Dunix -Dxgks -DG77 -DG77_SIGNAL -DINTERNAL_READ_FORMAT_BUG -DMANDATORY_FORMAT_WIDTHS -DNEED_IAND -DNO_DOUBLE_ESCAPE_SLASH -DNO_OPEN_CARRIAGECONTROL -DNO_OPEN_SHARED -DNO_OPEN_READONLY -DNO_OPEN_RECORDTYPE -DNO_PASSED_CONCAT -DNO_PREPEND_STRING -DSTAR_1_SUPPORTED -DX_REFRESH -I. -I/eb/maint/software/netCDF/4.7.1-gompi-2019b/../include -I/eb/maint/build/Ferret/7.5.0/foss-2019b/Ferret-7.5.0//fer/common -I/eb/maint/build/Ferret/7.5.0/foss-2019b/Ferret-7.5.0//fmt/cmn -I/eb/maint/build/Ferret/7.5.0/foss-2019b/Ferret-7.5.0//ppl/tmap_inc -I/eb/maint/build/Ferret/7.5.0/foss-2019b/Ferret-7.5.0//ppl/include -I/eb/maint/build/Ferret/7.5.0/foss-2019b/Ferret-7.5.0//xgks/src/lib -I/eb/maint/build/Ferret/7.5.0/foss-2019b/Ferret-7.5.0//xgks/port -O -DNDEBUG -c xmake_date_data.F -o xmake_date_data.o
f951: Warning: Nonexistent include directory '/eb/maint/software/netCDF/4.7.1-gompi-2019b/../include' [-Wmissing-include-dirs]
/eb/maint/software/GCCcore/8.3.0/bin/gfortran -m64 -fPIC -fno-automatic -fno-second-underscore -fdollar-ok -ffixed-line-length-132 -ffpe-trap=overflow -fimplicit-none -fdefault-real-8 -fdefault-double-8 -Dcrptd_cat_argument -Ddouble_p -Dgfortran -Dreclen_in_bytes -Dunix -Dxgks -DG77 -DG77_SIGNAL -DINTERNAL_READ_FORMAT_BUG -DMANDATORY_FORMAT_WIDTHS -DNEED_IAND -DNO_DOUBLE_ESCAPE_SLASH -DNO_OPEN_CARRIAGECONTROL -DNO_OPEN_SHARED -DNO_OPEN_READONLY -DNO_OPEN_RECORDTYPE -DNO_PASSED_CONCAT -DNO_PREPEND_STRING -DSTAR_1_SUPPORTED -DX_REFRESH -I. -I/eb/maint/software/netCDF/4.7.1-gompi-2019b/../include -I/eb/maint/build/Ferret/7.5.0/foss-2019b/Ferret-7.5.0//fer/common -I/eb/maint/build/Ferret/7.5.0/foss-2019b/Ferret-7.5.0//fmt/cmn -I/eb/maint/build/Ferret/7.5.0/foss-2019b/Ferret-7.5.0//ppl/tmap_inc -I/eb/maint/build/Ferret/7.5.0/foss-2019b/Ferret-7.5.0//ppl/include -I/eb/maint/build/Ferret/7.5.0/foss-2019b/Ferret-7.5.0//xgks/src/lib -I/eb/maint/build/Ferret/7.5.0/foss-2019b/Ferret-7.5.0//xgks/port -O -DNDEBUG -c xrevision_type_data.F -o xrevision_type_data.o
f951: Warning: Nonexistent include directory '/eb/maint/software/netCDF/4.7.1-gompi-2019b/../include' [-Wmissing-include-dirs]
/eb/maint/software/GCCcore/8.3.0/bin/gfortran -m64 -fPIC -fno-automatic -fno-second-underscore -fdollar-ok -ffixed-line-length-132 -ffpe-trap=overflow -fimplicit-none -fdefault-real-8 -fdefault-double-8 -Dcrptd_cat_argument -Ddouble_p -Dgfortran -Dreclen_in_bytes -Dunix -Dxgks -DG77 -DG77_SIGNAL -DINTERNAL_READ_FORMAT_BUG -DMANDATORY_FORMAT_WIDTHS -DNEED_IAND -DNO_DOUBLE_ESCAPE_SLASH -DNO_OPEN_CARRIAGECONTROL -DNO_OPEN_SHARED -DNO_OPEN_READONLY -DNO_OPEN_RECORDTYPE -DNO_PASSED_CONCAT -DNO_PREPEND_STRING -DSTAR_1_SUPPORTED -DX_REFRESH -I. -I/eb/maint/software/netCDF/4.7.1-gompi-2019b/../include -I/eb/maint/build/Ferret/7.5.0/foss-2019b/Ferret-7.5.0//fer/common -I/eb/maint/build/Ferret/7.5.0/foss-2019b/Ferret-7.5.0//fmt/cmn -I/eb/maint/build/Ferret/7.5.0/foss-2019b/Ferret-7.5.0//ppl/tmap_inc -I/eb/maint/build/Ferret/7.5.0/foss-2019b/Ferret-7.5.0//ppl/include -I/eb/maint/build/Ferret/7.5.0/foss-2019b/Ferret-7.5.0//xgks/src/lib -I/eb/maint/build/Ferret/7.5.0/foss-2019b/Ferret-7.5.0//xgks/port -O -DNDEBUG -c xplatform_type_data.F -o xplatform_type_data.o
f951: Warning: Nonexistent include directory '/eb/maint/software/netCDF/4.7.1-gompi-2019b/../include' [-Wmissing-include-dirs]
make[3]: Leaving directory `/eb/maint/build/Ferret/7.5.0/foss-2019b/Ferret-7.5.0/fer/special'
make -C ../fmt/src
make[3]: Entering directory `/eb/maint/build/Ferret/7.5.0/foss-2019b/Ferret-7.5.0/fmt/src'
/eb/maint/software/GCCcore/8.3.0/bin/gfortran -m64 -fPIC -fno-automatic -fno-second-underscore -fdollar-ok -ffixed-line-length-132 -ffpe-trap=overflow -fimplicit-none -fdefault-real-8 -fdefault-double-8 -Dcrptd_cat_argument -Ddouble_p -Dgfortran -Dreclen_in_bytes -Dunix -Dxgks -DG77 -DG77_SIGNAL -DINTERNAL_READ_FORMAT_BUG -DMANDATORY_FORMAT_WIDTHS -DNEED_IAND -DNO_DOUBLE_ESCAPE_SLASH -DNO_OPEN_CARRIAGECONTROL -DNO_OPEN_SHARED -DNO_OPEN_READONLY -DNO_OPEN_RECORDTYPE -DNO_PASSED_CONCAT -DNO_PREPEND_STRING -DSTAR_1_SUPPORTED -DX_REFRESH -I. -I/eb/maint/software/netCDF/4.7.1-gompi-2019b/../include -I/eb/maint/build/Ferret/7.5.0/foss-2019b/Ferret-7.5.0//fer/common -I/eb/maint/build/Ferret/7.5.0/foss-2019b/Ferret-7.5.0//fmt/cmn -I/eb/maint/build/Ferret/7.5.0/foss-2019b/Ferret-7.5.0//ppl/tmap_inc -I/eb/maint/build/Ferret/7.5.0/foss-2019b/Ferret-7.5.0//ppl/include -I/eb/maint/build/Ferret/7.5.0/foss-2019b/Ferret-7.5.0//xgks/src/lib -I/eb/maint/build/Ferret/7.5.0/foss-2019b/Ferret-7.5.0//xgks/port -O -DNDEBUG -c cd_1d_line_from_2d.F -o cd_1d_line_from_2d.o
f951: Warning: Nonexistent include directory '/eb/maint/software/netCDF/4.7.1-gompi-2019b/../include' [-Wmissing-include-dirs]
cd_1d_line_from_2d.F:49: Error: Can't open included file 'netcdf.inc'
make[3]: *** [cd_1d_line_from_2d.o] Error 1
make[3]: Leaving directory `/eb/maint/build/Ferret/7.5.0/foss-2019b/Ferret-7.5.0/fmt/src'
make[2]: *** [fmt_libraries] Error 2
make[2]: Leaving directory `/eb/maint/build/Ferret/7.5.0/foss-2019b/Ferret-7.5.0/fer'
make[1]: *** [ncdf4] Error 2
make[1]: Leaving directory `/eb/maint/build/Ferret/7.5.0/foss-2019b/Ferret-7.5.0/fer'
make: *** [optimized] Error 2
```

**Comment by smoors** [comment]
@verdurin did you use the updated easyblock in your test report (see above)?

**Comment by verdurin** [comment]
Test report by @verdurin
**FAILED**
Build succeeded for 0 out of 1 (1 easyconfigs in this PR)
easybuild.novalocal - Linux centos linux 7.7.1908, Intel Xeon Processor (Skylake, IBRS), Python 2.7.5
See https://gist.github.com/0909056862989af154fefb4dde983bd3 for a full test report.

**Comment by verdurin** [comment]
@verdurin remembered to include it this time, and see a different error:
```
== 2020-02-26 19:19:56,790 build_log.py:169 ERROR EasyBuild crashed with an error (at easybuild/base/exceptions.py:124 in __init__): cmd " make install " exited with exit code 2 and output:
rm -f fer_environment.tar.gz
bin/make_environment_tar . . -y
make: bin/make_environment_tar: Command not found
make: *** [install_env] Error 127
 (at easybuild/tools/run.py:529 in parse_cmd_output)
```

**Comment by smoors** [comment]
@verdurin that's weird. do you have any idea what could be the cause?

it says it cannot find `bin/make_environment_tar` but this executable is present in the sources.
EB also seems to be in the right (root) directory `/eb/maint/build/Ferret/7.5.0/foss-2019b/Ferret-7.5.0` so it should find it..

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 4 out of 4 (1 easyconfigs in this PR)
giove-1 - Linux centos linux 7.7.1908, Intel(R) Xeon(R) CPU E5-2660 v4 @ 2.00GHz, Python 3.6.8
See https://gist.github.com/7a485ddb71ae19107afd3aa746832533 for a full test report.

**Comment by boegel** [comment]
Maybe `make_environment_tar` is trying to use a command that is not installed? Like... `tar`?!

**Comment by verdurin** [comment]
`tar` is installed...

**Comment by boegel** [comment]
@verdurin Can you check the log file for more mentions of `make_environment_tar` (or upload the log file somewhere for us to look at)?

**Comment by verdurin** [comment]
@boegel those are the only mentions in the whole log file...

**Comment by verdurin** [comment]
That file *does* exist in `/eb/maint/build/Ferret/7.5.0/foss-2019b/Ferret-7.5.0/bin/

**Comment by boegel** [comment]
@verdurin So, is `bin/make_environment_tar` there in `/eb/maint/build/Ferret/7.5.0/foss-2019b/Ferret-7.5.0`?

If so, any trace of commands that are not installed?

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
node3131.skitty.os - Linux centos linux 7.7.1908, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz, Python 3.6.8
See https://gist.github.com/07138886196b6d3c2488e257ec4d35fc for a full test report.

**Comment by verdurin** [comment]
@boegel I think this is because that file requires `/bin/csh` and I don't have that installed.

**Comment by boegel** [comment]
@verdurin That doesn't seem like something we can fix via a build dependency either, unless we also patch the `Makefile` to use `csh bin/make_environment_tar . . -y`?

**Comment by smoors** [comment]
@verdurin do you have a machine with `csh` installed to test this?

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
node2402.golett.os - Linux centos linux 7.7.1908, Intel(R) Xeon(R) CPU E5-2680 v3 @ 2.50GHz, Python 2.7.5
See https://gist.github.com/c04e6d5920fe1a47fa4ed05f247ea16a for a full test report.

**Comment by boegel** [comment]
@smoors I don't think we need to hold this back any further, the problem is quite clear, and the added OS dep ensures people won't have to try and figure out the cryptic errors that @verdurin was running into...

**Comment by boegel** [comment]
Going in, thanks @smoors!

**Pull request merged**
