### PR TITLE
{bio}[foss/2022a] e3nn v0.3.3 w/ PyTorch 1.13.1 CUDA 11.7.0

### PR DESCRIPTION
**Pull request by sassy-crick**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by sassy-crick** [comment]
@boegelbot please test @ generoso

**Comment by sassy-crick** [comment]
@boegelbot please test @ generoso

**Review by Micket — APPROVED** [review]
lgtm

**Comment by Micket** [comment]
@boegelbot please test @ jsc-zen3

**Comment by Micket** [comment]
Test report by @Micket
**FAILED**
Build succeeded for 7 out of 9 (1 easyconfigs in total)
alvis2-04 - Linux Rocky Linux 8.9, x86_64, Intel(R) Xeon(R) Gold 6226R CPU @ 2.90GHz, 8 x NVIDIA Tesla T4, 550.54.14, Python 3.6.8
See https://gist.github.com/Micket/b3afdbfa2aba69ff235a07cf885ee17f for a full test report.

**Comment by sassy-crick** [comment]
The test build fails as `PyTorch` does not build. Has that something to do with my PR? I cannot see why as I am pulling in an existing `PyTorch` build.

**Comment by akesandgren** [comment]
Test report by @akesandgren
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
b-cn1603.hpc2n.umu.se - Linux Ubuntu 22.04, x86_64, AMD EPYC 7313 16-Core Processor, 1 x NVIDIA NVIDIA A100 80GB PCIe, 545.29.06, Python 3.10.12
See https://gist.github.com/akesandgren/c6effae663fbd478fef6a3af50936e05 for a full test report.

**Review by akesandgren — APPROVED** [review]
LGTM

**Comment by akesandgren** [comment]
Going in, thanks @sassy-crick!

**Pull request merged**
