### PR TITLE
{devel}[system] CMake 3.18.4

### PR DESCRIPTION
**Pull request by sassy-crick**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by jfgrimm** [comment]
Test report by @jfgrimm
**FAILED**
Build succeeded for 0 out of 1 (1 easyconfigs in total)
himem05.pri.viking.alces.network - Linux CentOS Linux 7.9.2009, x86_64, Intel(R) Xeon(R) Gold 6230 CPU @ 2.10GHz (cascadelake), Python 3.6.8
See https://gist.github.com/84e804192bda08fc2393878ec5843c4d for a full test report.

**Comment by jfgrimm** [comment]
@sassy-crick I think `OpenSSL` has to be a runtime dependency, it's dynamically linked

**Comment by sassy-crick** [comment]
> @sassy-crick I think `OpenSSL` has to be a runtime dependency, it's dynamically linked

@jfgrimm Yes, of course you are right! I have updated the file. Thanks!

**Comment by jfgrimm** [comment]
Test report by @jfgrimm
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
node094.pri.viking.alces.network - Linux CentOS Linux 7.9.2009, x86_64, Intel(R) Xeon(R) Gold 6138 CPU @ 2.00GHz (skylake_avx512), Python 3.6.8
See https://gist.github.com/f36e2264878513436cb3cb5889011949 for a full test report.

**Comment by jfgrimm** [comment]
@boegelbot : please test @ generoso

**Comment by jfgrimm** [comment]
Going in, thanks @sassy-crick!

**Pull request merged**
