### PR TITLE
{data}[foss/2022a] HDF5 v1.13.1

### PR DESCRIPTION
**Pull request by garadar**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by garadar** [comment]
> /home/runner/work/easybuild-easyconfigs/easybuild-easyconfigs/easybuild/easyconfigs/h/HDF5/HDF5-1.13.1-foss-2022a.eb:12:121: E501 line too long (135 > 120 characters)


@boegel , this is the line with the source link, I don't think I can reduce the length.

**Comment by bedroge** [comment]
@garadar There's already an easyconfig for HDF5 1.13.1 with `gompi/2022a`, which is a subtoolchain of `foss/2022a` (which means you can use it with anything else that depends on either `gompi` or `foss`). So, I don't think there is a need for this?

**Comment by boegel** [comment]
In addition, HDF5 1.13.x are *experimental* releases, so they should be used with care, cfr. https://www.hdfgroup.org/2021/12/hdf5-1-13-0-introducing-experimental-releases and #16153

**Comment by boegel** [comment]
Since HDF5 1.13.x is an experimental releases, and sources will disappear upstream eventually, I think it makes sense to closer this PR rather than make an effort in getting it merged (since it'll mostly lead to confusion, for very little benefit)...

Do let us know if you disagree @garadar!

**Pull request closed without merging**
