### PR TITLE
{phys}[GCC/12.3.0] LoopTools v2.15

### PR DESCRIPTION
**Pull request by APN-Pucky**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by jfgrimm** [comment]
@boegelbot: please test @ jsc-zen2

**Comment by jfgrimm** [comment]
Test report by @jfgrimm
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
node076.viking2.yor.alces.network - Linux Rocky Linux 8.8, x86_64, AMD EPYC 7643 48-Core Processor, Python 3.6.8
See https://gist.github.com/jfgrimm/a19dc8205537aa7a6597ad0157af81e7 for a full test report.

**Comment by jfgrimm** [comment]
@boegelbot: please test @ generoso

**Comment by jfgrimm** [comment]
Going in, thanks @APN-Pucky!

**Comment by APN-Pucky** [comment]
Thanks!

**Pull request merged**
