### PR TITLE
gcsfs v2023.12.2.post1: move poetry to builddeps and bump poetry version

### PR DESCRIPTION
**Pull request by pavelToman**

### CODE REVIEW

**Comment by pavelToman** [comment]
@boegelbot please test @ generoso

**Comment by pavelToman** [comment]
@boegelbot please test @ jsc-zen3

**Comment by jfgrimm** [comment]
Test report by @jfgrimm
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
node074.viking2.yor.alces.network - Linux Rocky Linux 8.8, x86_64, AMD EPYC 7643 48-Core Processor, Python 3.6.8
See https://gist.github.com/jfgrimm/a4bc571a2b527ba0a6f2fe941a203724 for a full test report.

**Review by jfgrimm — APPROVED** [review]
lgtm

**Pull request merged**
