### PR TITLE
{bio,tools}[GCCcore/10.2.0,gompi/2020b] RAxML-NG v1.0.2, googletest v1.10.0

### PR DESCRIPTION
**Pull request by tardigradus**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by smoors** [comment]
@boegelbot: please test @ generoso

**Comment by smoors** [comment]
Test report by @smoors
**FAILED**
Build succeeded for 1 out of 2 (2 easyconfigs in total)
node361.hydra.os - Linux centos linux 7.9.2009, x86_64, Intel(R) Xeon(R) Gold 6148 CPU @ 2.40GHz (skylake_avx512), Python 2.7.5
See https://gist.github.com/39920fc9f1c059c578a7f732c055c957 for a full test report.

**Comment by smoors** [comment]
@tardigradus is the checksum correct?
```
== 2021-04-26 18:14:22,846 easyblock.py:3416 WARNING build failed (first 300 chars): Checksum verification for /scratch/brussel/100/vsc10009/sources/r/RAxML-NG/pll-modules-1.0.2.tar.gz using 0cc5dbff2d0be777191191fb531f1ec86de08664130b2ff3556b6b7fc7a09ae5 failed.
```

**Review by smoors — CHANGES_REQUESTED** [review]
checksum

**Comment by tardigradus** [comment]
OK, sorry.  I initially hadn't spotted the dependencies being downloaded via a specific commit.  My first attempt must have downloaded the old files but updated the version in the name.  These old version were then subsequently used.  I should start using the ```--force-download``` flag.  I'll update the PR.

**Comment by smoors** [comment]
@boegelbot: please test @ generoso

**Comment by smoors** [comment]
Test report by @smoors
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in total)
node374.hydra.os - Linux centos linux 7.9.2009, x86_64, Intel(R) Xeon(R) Gold 6148 CPU @ 2.40GHz (skylake_avx512), Python 2.7.5
See https://gist.github.com/4a06ee74b6ea4cd7e0afff18f0c270fb for a full test report.

**Review by smoors — APPROVED** [review]
lgtm

**Comment by smoors** [comment]
Going in, thanks @tardigradus!

**Pull request merged**
