### PR TITLE
{lib}[GCCcore/13.2.0] ISA-L v2.31.0, python-isal v1.6.1

### PR DESCRIPTION
**Pull request by Flamefire**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by zao** [comment]
Test report by @zao
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in total)
eb-mix.zao.se - Linux Ubuntu 24.04 (Noble Numbat), x86_64, AMD Ryzen 9 3900X 12-Core Processor (zen2), Python 3.12.2
See https://gist.github.com/zao/f83bb8022036cfba2d1df24a33786fc8 for a full test report.

**Review by Micket — APPROVED** [review]
lgtm

**Comment by Micket** [comment]
@boegelbot please test @ generoso

**Comment by Micket** [comment]
@boegelbot please test @ jsc-zen3

**Comment by Micket** [comment]
Test report by @Micket
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in total)
vera-skylake-build - Linux Rocky Linux 8.9, x86_64, Intel Xeon Processor (Skylake, IBRS, no TSX), Python 3.6.8
See https://gist.github.com/Micket/547518aa64501ff3792fb9fd6152ef0a for a full test report.

**Comment by Micket** [comment]
Going in, thanks @Flamefire!

**Pull request merged**
