### PR TITLE
{astro}[foss/2018b,intel/2018b] emcee v2.2.1

### PR DESCRIPTION
**Pull request by jose-d**
(created using `eb --new-pr`)

dependency of  `ngmix` I'd like to _easybuildize_ too.

### CODE REVIEW

**Comment by jose-d** [comment]
Test report by @jose-d
**SUCCESS**
Build succeeded for 4 out of 4 (4 easyconfigs in this PR)
koios1 - Linux centos linux 7.6.1810, Intel(R) Xeon(R) Gold 6130 CPU @ 2.10GHz, Python 2.7.5
See https://gist.github.com/8fc97af35cb41193dce5d2714c6e8ad0 for a full test report.

**Comment by jose-d** [comment]
mhmm, ```
======================================================================
ERROR: test_conflicts (test.easyconfigs.easyconfigs.EasyConfigTest)
Check whether any conflicts occur in software dependency graphs.
----------------------------------------------------------------------
``` I'm not fully convinced that I have conflict there..

**Comment by boegel** [comment]
@jose-d You're definitely missing `download_dep_fail = True` (that's automatic for `PythonBundle`, not for `PythonPackage`).

The other issue is strange, looking into that...

**Comment by boegel** [comment]
@jose-d The problem with the failing conflicts test is a bug in framework, it's triggered by merging #7921 which relies on the new `multi_deps` feature implemented in https://github.com/easybuilders/easybuild-framework/pull/2813, which apparently breaks `--check-conflicts`

**Comment by boegel** [comment]
@jose-d Bug is squashed in https://github.com/easybuilders/easybuild-framework/pull/2825, the failing conflicts test should pass after that PR is merged and the tests are re-triggered (@vanzod: please follow up)

**Comment by vanzod** [comment]
Re-trigger Travis after fix

**Comment by jose-d** [comment]
@boegel:
perhaps we're lucky and found another one:

```
List of changed easyconfig files in this PR: emcee-2.2.1-foss-2018b-Python-2.7.15.eb
...
emcee-2.2.1-intel-2018b-Python-3.6.6.eb
.Conflict found for dependencies of SciPy-bundle-2019.03-foss-2019a: Python-2.7.15-GCCcore-8.2.0 vs Python-3.7.2-GCCcore-8.2.0 
	Python-2.7.15-GCCcore-8.2.0 as dep of: SciPy-bundle-2019.03-foss-2019a, SciPy-bundle-2019.03-intel-2019a
```

**Comment by boegel** [comment]
@jose-d "Lucky" indeed... Problem was really fixed in https://github.com/easybuilders/easybuild-framework/pull/2826

**Comment by akesandgren** [comment]
Test report by @akesandgren
**SUCCESS**
Build succeeded for 5 out of 5 (4 easyconfigs in this PR)
b-an03.hpc2n.umu.se - Linux ubuntu 16.04, Intel(R) Xeon(R) CPU E5-2690 v4 @ 2.60GHz, Python 2.7.12
See https://gist.github.com/1af06802a6b3dcf9dcf3f65278524d7e for a full test report.

**Comment by akesandgren** [comment]
Going in, thanks @jose-d!

**Pull request merged**
