### PR TITLE
{tools}[system/system] code-server v4.21.1

### PR DESCRIPTION
**Pull request by Micket**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by Micket** [comment]
Test report by @Micket
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
vera-skylake-build - Linux Rocky Linux 8.9, x86_64, Intel Xeon Processor (Skylake, IBRS, no TSX), Python 3.6.8
See https://gist.github.com/Micket/14c248ca23a281221d513d04c61ea152 for a full test report.

**Comment by Micket** [comment]
@boegelbot please test @ generoso

**Comment by Micket** [comment]
@boegelbot please test @ jsc-zen3

**Comment by verdurin** [comment]
Test report by @verdurin
**FAILED**
Build succeeded for 0 out of 1 (1 easyconfigs in total)
easybuild-c7.novalocal - Linux CentOS Linux 7.9.2009, x86_64, Intel Xeon Processor (Skylake, IBRS), Python 3.6.8
See https://gist.github.com/verdurin/e8a4e32ecb8ce3012fa2557a32ce6322 for a full test report.

**Comment by verdurin** [comment]
This is the one that doesn't work with CentOS 7, so can't use my primary build server.
Assuming it's fine.

**Comment by verdurin** [comment]
@Micket Is it worth adding a comment about the incompatibility with CentOS 7? Or a module load message?

Yes, everyone should upgrade, but...

**Review by akesandgren — APPROVED** [review]
LGTM

**Pull request merged**
