### PR TITLE
{bio}[intel/2018a] update SOAPdenovo2-r241

### PR DESCRIPTION
**Pull request by michaelkarlcoleman**
Note that latest source is now on github.  Killed 'optarch' (which
defaults to True anyway?) and 'pic' (seems unnecessary).

### CODE REVIEW

**Comment by tutufan** [comment]
Also, confirmed that parallel build is broken.

**Comment by migueldiascosta** [comment]
@JensTimmerman it seems you added the original easyconfig, was there a reason to use `pic`? (e.g., use as a library?)

**Comment by michaelkarlcoleman** [comment]
Hi @migueldiascosta, unfortunately it's been too long, and I no longer recall the details.  I think I zapped `pic` as it seemed unnecessary, but perhaps I was missing something.  Consider it a hint, but use your best judgement.  Cheers!

**Comment by JensTimmerman** [comment]
@migueldiascosta I believe this was added at a time where we had some conflicts between pic and non pic code, but I belive these have since been fixed in the toolchains.
If there are no dependencies in the easyconfigs tree I see no reason to still have pic enabled.

**Comment by migueldiascosta** [comment]
Test report by @migueldiascosta
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
grc-cluster1 - Linux centos 6.10, Intel(R) Xeon(R) CPU E5-2640 0 @ 2.50GHz, Python 2.7.14
See https://gist.github.com/472f8181b2e452b7fb1e9b7e43301a40 for a full test report.

**Comment by migueldiascosta** [comment]
Going in, thanks @michaelkarlcoleman!

**Pull request merged**
