### PR TITLE
Add git as build dependency to x265

### PR DESCRIPTION
**Pull request by dithwick**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by dithwick** [comment]
To give some context to this, if you build x265 on a system without git installed then it will build successfully, and install the binary and static library but not the shared library (git is found in `source/cmake/Version.cmake`). Without git, during the config stage you get:

```
-- HG LIVE REPO STATUS CHECK DONE
-- X265 RELEASE VERSION unknown
-- Looking for strtok_r
-- Looking for strtok_r - found
-- Looking for include file getopt.h
-- Looking for include file getopt.h - found
-- Configuring done
-- Generating done
```

and easybuild fails on the sanity check (missing .so file). With git you get:

```
-- GIT_EXECUTABLE /usr/bin/git
-- SOURCE CODE IS FROM x265 GIT ARCHIVED ZIP OR TAR BALL
-- GIT ARCHIVAL INFORMATION PROCESSED
-- X265 RELEASE VERSION 3.5+1-f0c1022b6
-- Looking for strtok_r
-- Looking for strtok_r - found
-- Looking for include file getopt.h
-- Looking for include file getopt.h - found
-- Configuring done
-- Generating done
```

and both the static and shared libraries are installed.

**Comment by bedroge** [comment]
I can reproduce the issue (by temporarily moving my `/usr/bin/git` executable), but I was a bit surprised that it doesn't work, as it doesn't actually seem to use `git` anywhere in the build process. Digging a bit further, I found this:
https://bitbucket.org/multicoreware/x265_git/src/f0c1022b6be121a753ff02853fbe33da71988656/source/cmake/Version.cmake#lines-51
It seems that it does look for `git`, but when it actually finds it, it does another check for the existence of a `.git` dir in the source tree; if it's there, it's assuming this is a git checkout, and otherwise it's assuming this is a downloaded archive. In the first case, it does use the `git` command later on (see https://bitbucket.org/multicoreware/x265_git/src/f0c1022b6be121a753ff02853fbe33da71988656/source/cmake/Version.cmake#lines-143), but in the latter it doesn't (see https://bitbucket.org/multicoreware/x265_git/src/f0c1022b6be121a753ff02853fbe33da71988656/source/cmake/Version.cmake#lines-109).

This made me wonder if we can force the check to assume that it's a downloaded archive, as we know this in advance. So I added `configopts = '-DGIT_ARCHETYPE=1'` to the easyconfig, and that seems to work fine. I think I'd prefer that over adding a build dependency that is not actually used?

**Comment by dithwick** [comment]
That works for me, I agree it's better not to have the dependency in there if we can avoid it.

**Comment by bedroge** [comment]
@boegelbot please test @ generoso

**Comment by bedroge** [comment]
Test report by @bedroge
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
bob-Latitude-5300 - Linux Ubuntu 20.04, x86_64, Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz, Python 3.8.10
See https://gist.github.com/b28271902ecb3be185af5fb883f2c402 for a full test report.

**Comment by bedroge** [comment]
Test report by @bedroge
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
bob-Latitude-5300 - Linux Ubuntu 20.04, x86_64, Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz, Python 3.8.10
See https://gist.github.com/594a49250b7dfc7fcd5a4e452eca7fdb for a full test report.

**Comment by bedroge** [comment]
Test report by @bedroge
**SUCCESS**
Build succeeded for 2 out of 2 (1 easyconfigs in total)
pg-interactive.hpc.rug.nl - Linux centos linux 7.9.2009, x86_64, Intel(R) Xeon(R) CPU E5-2680 v3 @ 2.50GHz, Python 3.6.8
See https://gist.github.com/64766cd4dad224e310b3231d409db96c for a full test report.

**Comment by bedroge** [comment]
This doesn't seem to affect version 3.3. But we do have another easyconfig for version 3.5 in the easyconfigs repo:
https://github.com/easybuilders/easybuild-easyconfigs/blob/develop/easybuild/easyconfigs/x/x265/x265-3.5-GCCcore-11.2.0.eb
@dithwick would you be up for patching that one too in this PR?

**Comment by dithwick** [comment]
Yes of course, no problem!

**Comment by bedroge** [comment]
@boegelbot please test @ generoso

**Comment by bedroge** [comment]
Test report by @bedroge
**SUCCESS**
Build succeeded for 3 out of 3 (2 easyconfigs in total)
bob-Latitude-5300 - Linux Ubuntu 20.04, x86_64, Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz, Python 3.8.10
See https://gist.github.com/843ebf14acdb240b57c1ca1bc92d03ba for a full test report.

**Comment by bedroge** [comment]
Test report by @bedroge
**SUCCESS**
Build succeeded for 3 out of 3 (2 easyconfigs in total)
pg-interactive.hpc.rug.nl - Linux centos linux 7.9.2009, x86_64, Intel(R) Xeon(R) CPU E5-2680 v3 @ 2.50GHz, Python 3.6.8
See https://gist.github.com/67acbbc80533823d1307bff422a25034 for a full test report.

**Comment by bedroge** [comment]
Test report by @bedroge
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in total)
bob-Latitude-5300 - Linux Ubuntu 20.04, x86_64, Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz, Python 3.8.10
See https://gist.github.com/730855e4ea886add954a98b222570529 for a full test report.

**Review by bedroge — APPROVED** [review]
Lgtm, thanks a lot for fixing this issue @dithwick!

**Comment by dithwick** [comment]
No problem :-)

**Comment by bedroge** [comment]
Going in, thanks @dithwick!

**Pull request merged**
