### PR TITLE
{lib}[GCCcore/6.4.0,GCCcore/7.3.0,GCCcore/8.2.0] PMIx v3.1.1

### PR DESCRIPTION
**Pull request by akesandgren**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by akesandgren** [comment]
Test report by @akesandgren
**SUCCESS**
Build succeeded for 4 out of 4 (4 easyconfigs in this PR)
b-an03.hpc2n.umu.se - Linux ubuntu 16.04, Intel(R) Xeon(R) CPU E5-2690 v4 @ 2.60GHz, Python 2.7.12
See https://gist.github.com/17e76afcf6ce550c8148e5ad947ae0a5 for a full test report.

**Comment by akesandgren** [comment]
Test report by @akesandgren
**SUCCESS**
Build succeeded for 4 out of 4 (4 easyconfigs in this PR)
b-an03.hpc2n.umu.se - Linux ubuntu 16.04, Intel(R) Xeon(R) CPU E5-2690 v4 @ 2.60GHz, Python 2.7.12
See https://gist.github.com/df73c1c80824641bf60ea37861b78cf0 for a full test report.

**Comment by verdurin** [comment]
Test report by @verdurin
**SUCCESS**
Build succeeded for 41 out of 41 (4 easyconfigs in this PR)
easybuild.novalocal - Linux centos linux 7.6.1810, Intel Xeon Processor (Skylake, IBRS), Python 2.7.5
See https://gist.github.com/3c8c95e6b75892b4980cebbf1a449a0e for a full test report.

**Comment by smoors** [comment]
Test report by @smoors
**SUCCESS**
Build succeeded for 4 out of 4 (3 easyconfigs in this PR)
node357.hydra.os - Linux centos linux 7.6.1810, Intel(R) Xeon(R) Gold 6148 CPU @ 2.40GHz, Python 2.7.5
See https://gist.github.com/87d1a655d1edf4bd4f339bcb6ab948dc for a full test report.

**Comment by smoors** [comment]
Going in, thanks @akesandgren!

**Pull request merged**
