### PR TITLE
{vis}[GCCcore/12.2.0] Mesa v22.2.4, Mako v1.2.4, libglvnd v1.6.0, libdrm v2.4.114, libunwind v1.6.2

### PR DESCRIPTION
**Pull request by boegel**
(created using `eb --new-pr`)
requires:
* #16725

### CODE REVIEW

**Comment by boegel** [comment]
@boegelbot please test @ generoso
CORE_CNT=16

**Comment by boegel** [comment]
@boegelbot please test @ generoso
CORE_CNT=16

**Comment by SebastianAchilles** [comment]
Test report by @sebastianachilles
**SUCCESS**
Build succeeded for 5 out of 5 (5 easyconfigs in total)
bwd-rockylinux-90 - Linux Rocky Linux 9.0 (Blue Onyx), x86_64, Intel(R) Core(TM) i7-6900K CPU @ 3.20GHz (broadwell), Python 3.9.10
See https://gist.github.com/cf020451f3c8820886cdbebb09a2e7b1 for a full test report.

**Comment by SebastianAchilles** [comment]
@boegelbot please test @ jsc-zen2
CORE_CNT=16

**Review by SebastianAchilles — APPROVED** [review]
lgtm

**Comment by SebastianAchilles** [comment]
Going in, thanks @boegel!

**Pull request merged**
