### PR TITLE
{bio}[GCCcore/12.2.0] EDirect v20.5.20231006

### PR DESCRIPTION
**Pull request by verdurin**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by verdurin** [comment]
Test report by @verdurin
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
easybuild-c7.novalocal - Linux CentOS Linux 7.9.2009, x86_64, Intel Xeon Processor (Skylake, IBRS), Python 3.6.8
See https://gist.github.com/verdurin/a0905c938e828c14b253d7c7ddd31a3a for a full test report.

**Comment by verdurin** [comment]
@boegelbot please test @ jsc-zen3

**Review by jfgrimm — APPROVED** [review]
lgtm

**Comment by jfgrimm** [comment]
Going in, thanks @verdurin!

**Pull request merged**
