### PR TITLE
{bio}[foss/2021a] SEACells v20230731

### PR DESCRIPTION
**Pull request by boegel**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by boegel** [comment]
@boegelbot please test @ generoso

**Comment by boegel** [comment]
@boegelbot please test @ generoso
EB_ARGS="--sanity-check-only"

**Review by verdurin — APPROVED** [review]
Looks fine.

**Comment by SebastianAchilles** [comment]
Test report by @sebastianachilles
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
zen2-rockylinux-89 - Linux Rocky Linux 8.9, x86_64, AMD EPYC 7452 32-Core Processor (zen2), Python 3.6.8
See https://gist.github.com/SebastianAchilles/4eebc0de25801d2747c7c9e8b6418726 for a full test report.

**Review by SebastianAchilles — APPROVED** [review]
Lots of successful builds from different systems.
LGTM

**Comment by SebastianAchilles** [comment]
Going in, thanks @boegel!

**Pull request merged**
