### PR TITLE
{lib}[GCCcore/8.3.0] libreadline v8.0

### PR DESCRIPTION
**Pull request by Micket**
(created using `eb --new-pr`)

depends on ~#8616~

### CODE REVIEW

**Comment by Micket** [comment]
Test report by @Micket
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
vera-c1 - Linux centos linux 7.6.1810, Intel Xeon Processor (Skylake), Python 2.7.5
See https://gist.github.com/390767fb527109457cbbf322f4e3f13e for a full test report.

**Comment by Micket** [comment]
Kicking Travis

**Comment by Micket** [comment]
Travis kicked

**Comment by vanzod** [comment]
Test report by @vanzod
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
cermis - Linux debian 9.9, Intel(R) Xeon(R) CPU           X5670  @ 2.93GHz, Python 2.7.13
See https://gist.github.com/816ab65839bd53ee3086f10efe24352e for a full test report.

**Comment by vanzod** [comment]
Going in, thanks @Micket!

**Pull request merged**
