### PR TITLE
{chem}[gompi/2021a] ORCA v5.0.1

### PR DESCRIPTION
**Pull request by lexming**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by lexming** [comment]
Test report by @lexming
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in total)
node369.hydra.os - Linux centos linux 7.9.2009, x86_64, Intel(R) Xeon(R) Gold 6148 CPU @ 2.40GHz, Python 2.7.5
See https://gist.github.com/3022bc480a7d832ba285fdb115a756b8 for a full test report.

**Comment by robert-mijakovic** [comment]
@boegelbot please test @ generoso

**Comment by lexming** [comment]
@robert-mijakovic sources of ORCA are not publicly available

**Comment by robert-mijakovic** [comment]
I noticed that once I submitted a request to bogelbot. I have registered now and wait for it to be approved. It seems it will take some time until it is done.

**Comment by branfosj** [comment]
Test report by @branfosj
**FAILED**
Build succeeded for 1 out of 2 (2 easyconfigs in total)
bear-pg0211u03a.bear.cluster - Linux RHEL 8.3, x86_64, Intel(R) Xeon(R) Gold 6248 CPU @ 2.50GHz (cascadelake), Python 3.6.8
See https://gist.github.com/c7fb2cceb354baa26e9e7c729d174b05 for a full test report.

**Comment by branfosj** [comment]
Test report by @branfosj
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in total)
bear-pg0211u03a.bear.cluster - Linux RHEL 8.3, x86_64, Intel(R) Xeon(R) Gold 6248 CPU @ 2.50GHz (cascadelake), Python 3.6.8
See https://gist.github.com/91be44024c896ce2496b0a3e301ea483 for a full test report.

**Review by branfosj — APPROVED** [review]
lgtm

**Comment by branfosj** [comment]
Going in, thanks @lexming!

**Pull request merged**
