### PR TITLE
Fix confgure options in GRASS

### PR DESCRIPTION
**Pull request by Flamefire**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by Flamefire** [comment]
Test report by @Flamefire
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
n1493 - Linux RHEL 8.7 (Ootpa), x86_64, Intel(R) Xeon(R) Platinum 8470 (icelake), Python 3.8.13
See https://gist.github.com/Flamefire/03d1b21462d4426092e8e1f2ad763c78 for a full test report.

**Review by Micket — APPROVED** [review]
lgtm

**Comment by Micket** [comment]
@boegelbot please test @ generoso
EB_ARGS="GRASS-8.2.0-foss-2021b.eb"

**Comment by Micket** [comment]
Going in, thanks @Flamefire!

**Pull request merged**
