### PR TITLE
{chem}[foss/2022a] xtb v6.6.0

### PR DESCRIPTION
**Pull request by nd996**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by jfgrimm** [comment]
@boegelbot please test @ jsc-zen2

**Comment by jfgrimm** [comment]
Test report by @jfgrimm
**FAILED**
Build succeeded for 0 out of 1 (1 easyconfigs in total)
node063.pri.viking.alces.network - Linux CentOS Linux 7.9.2009, x86_64, Intel(R) Xeon(R) Gold 6138 CPU @ 2.00GHz (skylake_avx512), Python 3.6.8
See https://gist.github.com/jfgrimm/e53218b0aadd1629a30d7058bc358fc3 for a full test report.

**Comment by jfgrimm** [comment]
Test report by @jfgrimm
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
node063.pri.viking.alces.network - Linux CentOS Linux 7.9.2009, x86_64, Intel(R) Xeon(R) Gold 6138 CPU @ 2.00GHz (skylake_avx512), Python 3.6.8
See https://gist.github.com/jfgrimm/669bd79bee356d100f0b566830507d34 for a full test report.

**Comment by jfgrimm** [comment]
hmm, test timeout might be too short for the jsc bot

**Comment by jfgrimm** [comment]
@boegelbot please test @ jsc-zen2
EB_ARGS="--try-amend=testopts='test -C %(builddir)s/easybuild_obj -t 360'"

**Comment by jfgrimm** [comment]
@boegelbot please test @ jsc-zen2
EB_ARGS="--try-amend=testopts='test -C %(builddir)s/easybuild_obj -t 360'"

**Comment by boegel** [comment]
@boegelbot please test @ jsc-zen2

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
node3100.skitty.os - Linux RHEL 8.8, x86_64, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz (skylake_avx512), Python 3.6.8
See https://gist.github.com/boegel/b7cd140c6f3fee568899c6af16efc404 for a full test report.

**Review by boegel — APPROVED** [review]
lgtm

**Pull request merged**
