### PR TITLE
{bio}[GCCcore/8.2.0] SRPRISM v3.1.1

### PR DESCRIPTION
**Pull request by Darkless012**
(created using `eb --new-pr`)
requires ~~#9158~~ (NGS)

### CODE REVIEW

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
node3141.skitty.os - Linux centos linux 7.6.1810, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz, Python 3.6.8
See https://gist.github.com/b04833d13d2b984d44b4cb61e7b2ebef for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
node2401.golett.os - Linux centos linux 7.6.1810, Intel(R) Xeon(R) CPU E5-2680 v3 @ 2.50GHz, Python 2.7.5
See https://gist.github.com/f8733ba5651496bce22504c802749ebc for a full test report.

**Comment by boegel** [comment]
Going in, thanks @Darkless012!

**Comment by verdurin** [comment]
Test report by @verdurin
**SUCCESS**
Build succeeded for 4 out of 4 (1 easyconfigs in this PR)
easybuild.novalocal - Linux centos linux 7.7.1908, Intel Xeon Processor (Skylake, IBRS), Python 2.7.5
See https://gist.github.com/9f4ec1c627e2742d0a126cddfb7b4628 for a full test report.

**Pull request merged**
