### PR TITLE
{math}[system/system] Mathematica v12.1.0

### PR DESCRIPTION
**Pull request by terjekv**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by smoors** [comment]
@terjekv you submitted the same PR twice, can we close this one?

**Comment by terjekv** [comment]
> @terjekv you submitted the same PR twice, can we close this one?

They're not the same, they're 12.1.0 and 12.1.1.  :-)

**Comment by smoors** [comment]
> > @terjekv you submitted the same PR twice, can we close this one?
> 
> They're not the same, they're 12.1.0 and 12.1.1. :-)

OK, my bad :)

**Comment by boegel** [comment]
Since this PR is quite old, no test reports, and #10836 was merged already, I'll go ahead and close this...

**Pull request closed without merging**
