### PR TITLE
fix PyTorch-1.12.1-foss-2022a.eb for Linux 6+

### PR DESCRIPTION
**Pull request by Flamefire**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by Flamefire** [comment]
I added the patch skipping the (single!) failing test as the error is exactly the same as mentioned in the patch. Also allowing 2 failures just in case there is a random fluke. But it should pass without any failures.

**Comment by Flamefire** [comment]
Test report by @Flamefire
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
n1438 - Linux RHEL 8.7 (Ootpa), x86_64, Intel(R) Xeon(R) Platinum 8470 (icelake), Python 3.8.13
See https://gist.github.com/Flamefire/e575db1403cf32d9b6fa101bec8a4265 for a full test report.

**Comment by casparvl** [comment]
Test report by @casparvl
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
tcn1.local.snellius.surf.nl - Linux RHEL 8.6, x86_64, AMD EPYC 7H12 64-Core Processor, Python 3.6.8
See https://gist.github.com/casparvl/e1f5b5e88ae22a0f85a3d9c98683551f for a full test report.

**Comment by casparvl** [comment]
@boegelbot please test @ generoso
CORE_CNT=16

**Comment by casparvl** [comment]
@boegelbot please test @ jsc-zen3
CORE_CNT=16

**Review by casparvl — APPROVED** [review]

**Comment by casparvl** [comment]
Going in, thanks @Flamefire!

**Pull request merged**
