### PR TITLE
Add decoupleR package to R-bundle-Bioconductor easyconfig as extension

### PR DESCRIPTION
**Pull request by WilleBell**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by verdurin** [comment]
Test report by @verdurin
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
easybuild-c7.novalocal - Linux CentOS Linux 7.9.2009, x86_64, Intel Xeon Processor (Skylake, IBRS), Python 3.6.8
See https://gist.github.com/verdurin/7f06eb3dcc050f93fd2f66a3f1730878 for a full test report.

**Comment by verdurin** [comment]
@boegelbot please test @ generoso
EB_ARGS="--skip"

**Comment by verdurin** [comment]
@boegelbot please test @ jsc-zen2
EB_ARGS="--skip"

**Comment by casparvl** [comment]
Test report by @casparvl
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
tcn1.local.snellius.surf.nl - Linux RHEL 8.6, x86_64, AMD EPYC 7H12 64-Core Processor, Python 3.6.8
See https://gist.github.com/casparvl/219ff1adc35974570c6ef3467fda6d3b for a full test report.

**Review by casparvl — APPROVED** [review]
Lgtm!

**Comment by casparvl** [comment]
Going in, thanks @WilleBell!

**Pull request merged**
