### PR TITLE
{chem}[foss/2018b] ASAP3 v3.10.10, ASE v3.16.2, matplotlib v3.0.0, ...

### PR DESCRIPTION
**Pull request by schiotz**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by schiotz** [comment]
Newest version of ASE and ASAP3 with the foss/2018b toolchain.
Also contains matplotlib and Tkinter, as they were missing.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 5 out of 5 (5 easyconfigs in this PR)
node3104.skitty.os - Linux centos linux 7.5.1804, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz, Python 2.7.5
See https://gist.github.com/8f444a68abf03324e783af51177b849e for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 5 out of 5 (5 easyconfigs in this PR)
node2717.swalot.os - Linux centos linux 7.5.1804, Intel(R) Xeon(R) CPU E5-2660 v3 @ 2.60GHz, Python 2.7.5
See https://gist.github.com/bb9057c8ed14b9d18afa3282a03e2bb1 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 5 out of 5 (5 easyconfigs in this PR)
node2081.delcatty.os - Linux centos linux 7.5.1804, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.7.5
See https://gist.github.com/1727358d7bdb8e44868fdc64620992d9 for a full test report.

**Comment by boegel** [comment]
Going in, thanks @schiotz!

**Comment by schiotz** [comment]
@boegel Thanks for merging this lightning-fast.  I am now making builds for GPAW on top of this patch, but I need to do some testing before submitting it.

CC @OleHolmNielsen @mikstr

**Pull request merged**
