### PR TITLE
{*}[foss/2021b] leidenalg v0.8.8, python-igraph v0.9.8, arpack-ng v3.8.0, PyCairo v1.20.1 (+ deps) w/ Python 3.9.6

### PR DESCRIPTION
**Pull request by boegel**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by boegel** [comment]
@boegelbot please test @ generoso
CORE_CNT=16

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 6 out of 6 (6 easyconfigs in total)
node3144.skitty.os - Linux centos linux 7.9.2009, x86_64, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz (skylake_avx512), Python 3.6.8
See https://gist.github.com/8593b2bbdcaa13518102a9dfd4aeb245 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 6 out of 6 (6 easyconfigs in total)
node3605.doduo.os - Linux RHEL 8.2, x86_64, AMD EPYC 7552 48-Core Processor (zen2), Python 3.6.8
See https://gist.github.com/553d4766d2f667e681fea4c804dd5885 for a full test report.

**Review by hajgato — APPROVED** [review]

**Comment by hajgato** [comment]
Test report by @hajgato
**FAILED**
Build succeeded for 3 out of 6 (6 easyconfigs in total)
node3402.kirlia.os - Linux centos linux 7.9.2009, x86_64, Intel(R) Xeon(R) Gold 6240 CPU @ 2.60GHz, Python 3.6.8
See https://gist.github.com/9979b836b614ba327ab5d25152832366 for a full test report.

**Comment by hajgato** [comment]
Test report by @hajgato
**FAILED**
Build succeeded for 4 out of 7 (6 easyconfigs in total)
node3408.kirlia.os - Linux centos linux 7.9.2009, x86_64, Intel(R) Xeon(R) Gold 6240 CPU @ 2.60GHz, Python 3.6.8
See https://gist.github.com/9fc1c8b64278edd3c64b7b4892617f9c for a full test report.

**Review by lexming — APPROVED** [review]
LGTM

**Comment by lexming** [comment]
Going in, thanks @boegel !

**Comment by hajgato** [comment]
Test report by @hajgato
**SUCCESS**
Build succeeded for 6 out of 6 (6 easyconfigs in total)
node3209.victini.os - Linux centos linux 7.9.2009, x86_64, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz, Python 3.6.8
See https://gist.github.com/161318e0536911011d4c72bed86bbf8b for a full test report.

**Pull request merged**
