### PR TITLE
{tools}[dummy/] worker v1.6.8

### PR DESCRIPTION
**Pull request by boegel**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
node3163.skitty.os - Linux centos linux 7.5.1804, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz, Python 2.7.5
See https://gist.github.com/b9289cc4c5c568a5ce0435d49be3899d for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
node2626.swalot.os - Linux centos linux 7.5.1804, Intel(R) Xeon(R) CPU E5-2660 v3 @ 2.60GHz, Python 2.7.5
See https://gist.github.com/c8911c80c5bf8c09f90f1e4910805543 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
node2062.delcatty.os - Linux centos linux 7.5.1804, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.7.5
See https://gist.github.com/58c6b71679f354692befd910504ba19c for a full test report.

**Comment by akesandgren** [comment]
This one is odd...

Why at dummy toolchain and then intel as builddep?
What is the reasoning here?

**Comment by akesandgren** [comment]
Then it would still be somewhat better to set intel as toolchain. I think this may cause problems if someone loads foss and then worker...

**Comment by akesandgren** [comment]
Going in, thanks @boegel!

**Pull request merged**
