### PR TITLE
{data}[foss/2018b] HDF5 v1.8.13

### PR DESCRIPTION
**Pull request by sassy-crick**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by Micket** [comment]
You uploaded both 1.8.12 and 1.8.13. Do you really need both?

**Comment by sassy-crick** [comment]
@Micket As I said to Boegel as well: this is more for completion so we got all versions, in case somebody needs a particular version. I leave it up to Boegel to decided whether he wants the older version as well or not.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
node3150.skitty.os - Linux centos linux 7.6.1810, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz, Python 2.7.5
See https://gist.github.com/fa23cee5eb9fcc280bc70a099172f6f9 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
node2454.golett.os - Linux centos linux 7.6.1810, Intel(R) Xeon(R) CPU E5-2680 v3 @ 2.50GHz, Python 2.7.5
See https://gist.github.com/40f5961186f563faa425edc52b546302 for a full test report.

**Comment by boegel** [comment]
Going in, thanks @sassy-crick!

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
node2081.delcatty.os - Linux centos linux 7.6.1810, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.7.5
See https://gist.github.com/4f0ceba962add6df04c64e58a71da11b for a full test report.

**Pull request merged**
