### PR TITLE
{lib, numlib, devel, vis, data, tools}[GCCcore/13.3.0] LMDB-0.9.31, NLopt-2.7.1, nsync-1.29.2, OpenEXR-3.2.4, PostgreSQL-16.4, pkgconfig-1.5.5, popt-1.19

### PR DESCRIPTION
**Pull request by ankekreuzer**
Continuing updating the GCCcore 13.3.0 toolchain with packages from JSC.

Needs `Imath` from #21170

### CODE REVIEW

**Comment by ankekreuzer** [comment]
Test report by @ankekreuzer
**SUCCESS**
Build succeeded for 7 out of 7 (7 easyconfigs in total)
zam329 - Linux Rocky Linux 9.4 (Blue Onyx), x86_64, Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz, Python 3.9.18
See https://gist.github.com/ankekreuzer/95e3f97fb618d6d06d7dec770a46ea78 for a full test report.

**Comment by SebastianAchilles** [comment]
@boegelbot please test @ jsc-zen3

**Comment by SebastianAchilles** [comment]
@boegelbot please test @ generoso

**Comment by SebastianAchilles** [comment]
Test report by @sebastianachilles
**SUCCESS**
Build succeeded for 7 out of 7 (7 easyconfigs in total)
bwd-rockylinux-94 - Linux Rocky Linux 9.4 (Blue Onyx), x86_64, Intel(R) Core(TM) i7-6900K CPU @ 3.20GHz (broadwell), Python 3.9.18
See https://gist.github.com/SebastianAchilles/cf7a368b29d0860ccdfff94a9bfef5ff for a full test report.

**Comment by SebastianAchilles** [comment]
Test report by @sebastianachilles
**SUCCESS**
Build succeeded for 7 out of 7 (7 easyconfigs in total)
zen2-rockylinux-810 - Linux Rocky Linux 8.10, x86_64, AMD EPYC 7452 32-Core Processor (zen2), Python 3.6.8
See https://gist.github.com/SebastianAchilles/4387ad94eedc00fb2bb3c532b169139a for a full test report.

**Review by SebastianAchilles — APPROVED** [review]
lgtm

**Comment by SebastianAchilles** [comment]
Going in, thanks @ankekreuzer!

**Pull request merged**
