### PR TITLE
{lib,vis}[GCCcore/11.3.0,foss/2022a] ACTC v1.1, VMD v1.9.4a57 w/ Python 3.10.4

### PR DESCRIPTION
**Pull request by Micket**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by Micket** [comment]
Test report by @Micket
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in total)
vera-c2 - Linux Rocky Linux 8.5, x86_64, Intel Xeon Processor (Skylake), Python 3.6.8
See https://gist.github.com/2ae7b2de9d6f23cd6ef92138a290d90a for a full test report.

**Comment by Micket** [comment]
Test report by @Micket
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in total)
alvis-c1 - Linux Rocky Linux 8.5, x86_64, Intel Xeon Processor (Skylake), Python 3.6.8
See https://gist.github.com/502aba34961825238e3ca58023c333e1 for a full test report.

**Comment by Micket** [comment]
Test report by @Micket
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in total)
vera-c2 - Linux Rocky Linux 8.5, x86_64, Intel Xeon Processor (Skylake), Python 3.6.8
See https://gist.github.com/28a1647310d94967f13865c542982cea for a full test report.

**Comment by casparvl** [comment]
Test report by @casparvl
**FAILED**
Build succeeded for 4 out of 5 (2 easyconfigs in total)
gcn2 - Linux RHEL 8.4, x86_64, Intel(R) Xeon(R) Platinum 8360Y CPU @ 2.40GHz, 4 x NVIDIA NVIDIA A100-SXM4-40GB, 515.43.04, Python 3.6.8
See https://gist.github.com/4920e742dd29c6384449159a3b024f81 for a full test report.

**Comment by casparvl** [comment]
Hm, the failure comes from a failure to download the source tarball for `stride.tar.gz`:
```
== 2022-10-13 15:44:41,578 filetools.py:840 WARNING IOError occurred while trying to download https://webclu.bio.wzw.tum.de/stride/stride.tar.gz to /home/casparl/.local/easybuild/sources/v/VMD/stride.tar.gz: <urlopen error [SSL: UNSUPPORTED_PROTOCOL] unsupported protocol (_ssl.c:897)>
== 2022-10-13 15:44:41,579 filetools.py:849 INFO Attempt 1 of downloading https://webclu.bio.wzw.tum.de/stride/stride.tar.gz to /home/casparl/.local/easybuild/sources/v/VMD/stride.tar.gz failed, trying again...
== 2022-10-13 15:44:41,626 filetools.py:840 WARNING IOError occurred while trying to download https://webclu.bio.wzw.tum.de/stride/stride.tar.gz to /home/casparl/.local/easybuild/sources/v/VMD/stride.tar.gz: <urlopen error [SSL: UNSUPPORTED_PROTOCOL] unsupported protocol (_ssl.c:897)>
== 2022-10-13 15:44:41,626 filetools.py:849 INFO Attempt 2 of downloading https://webclu.bio.wzw.tum.de/stride/stride.tar.gz to /home/casparl/.local/easybuild/sources/v/VMD/stride.tar.gz failed, trying again...
== 2022-10-13 15:44:41,673 filetools.py:840 WARNING IOError occurred while trying to download https://webclu.bio.wzw.tum.de/stride/stride.tar.gz to /home/casparl/.local/easybuild/sources/v/VMD/stride.tar.gz: <urlopen error [SSL: UNSUPPORTED_PROTOCOL] unsupported protocol (_ssl.c:897)>
``` 
On a `wget` I get:
```
wget https://webclu.bio.wzw.tum.de/stride/stride.tar.gz
--2022-10-13 15:46:42--  https://webclu.bio.wzw.tum.de/stride/stride.tar.gz
Resolving webclu.bio.wzw.tum.de (webclu.bio.wzw.tum.de)... 141.40.43.212
Connecting to webclu.bio.wzw.tum.de (webclu.bio.wzw.tum.de)|141.40.43.212|:443... connected.
GnuTLS: A packet with illegal or unsupported version was received.
Unable to establish SSL connection.
```

**Comment by casparvl** [comment]
Test report by @casparvl
**FAILED**
Build succeeded for 3 out of 5 (2 easyconfigs in total)
software2.lisa.surfsara.nl - Linux debian 10.13, x86_64, Intel(R) Xeon(R) Bronze 3104 CPU @ 1.70GHz, 4 x NVIDIA NVIDIA TITAN V, 470.103.01, Python 3.7.3
See https://gist.github.com/31b7cc452773886b5a12e6cca1ba5fac for a full test report.

**Comment by Micket** [comment]
My setup probably had this cached since ages ago. trying wget i do see the same issue

**Review by casparvl — COMMENTED** [review]
Changes look ok, no surprises in this update. Only problem is with the failing download of `stride.tar.gz`. Once resolved, and tested, this PR is good to go imho.

**Comment by Micket** [comment]
Test report by @Micket
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
vera-c2 - Linux Rocky Linux 8.5, x86_64, Intel Xeon Processor (Skylake), Python 3.6.8
See https://gist.github.com/8756237a09e7c610732000ba588992e0 for a full test report.

**Comment by casparvl** [comment]
Test report by @casparvl
**FAILED**
Build succeeded for 1 out of 2 (2 easyconfigs in total)
software1.lisa.surfsara.nl - Linux debian 10.13, x86_64, Intel(R) Xeon(R) Silver 4110 CPU @ 2.10GHz, Python 3.7.3
See https://gist.github.com/dbda974fefa1530d63d70b7c96ed3140 for a full test report.

**Comment by casparvl** [comment]
Test report by @casparvl
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in total)
tcn1.local.snellius.surf.nl - Linux RHEL 8.4, x86_64, AMD EPYC 7H12 64-Core Processor, Python 3.6.8
See https://gist.github.com/02fdd115557366ea2f3ddc5028e71cf9 for a full test report.

**Comment by casparvl** [comment]
Test report by @casparvl
**FAILED**
Build succeeded for 1 out of 3 (2 easyconfigs in total)
software1.lisa.surfsara.nl - Linux debian 10.13, x86_64, Intel(R) Xeon(R) Silver 4110 CPU @ 2.10GHz, Python 3.7.3
See https://gist.github.com/6b78b1fb5663df20babe27a810786606 for a full test report.

**Comment by Micket** [comment]
/usr/include/OpenEXR/ImathMatrix.h looks like additional os devel packages break the POV-Ray build

**Comment by casparvl** [comment]
I think you're right. I think that means that the POV-Ray EasyConfig should really list OpenEXR as a dependency, shouldn't it?

**Comment by casparvl** [comment]
Test report by @casparvl
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in total)
software1.lisa.surfsara.nl - Linux debian 10.13, x86_64, Intel(R) Xeon(R) Silver 4110 CPU @ 2.10GHz, Python 3.7.3
See https://gist.github.com/604b67891ba28315bbbb99c80ba4b4c5 for a full test report.

**Review by casparvl — APPROVED** [review]
Looks good to me!

**Comment by casparvl** [comment]
Going in, thanks @Micket!

**Pull request merged**
