### PR TITLE
{bio}[GCC/12.3.0] chopper v0.9.0

### PR DESCRIPTION
**Pull request by PetrKralCZ**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by PetrKralCZ** [comment]
@boegelbot please test @ generoso

**Comment by PetrKralCZ** [comment]
@boegelbot please test @ jsc-zen3

**Comment by smoors** [comment]
missing checksums?
>Checksums missing for one or more sources/patches in chopper-0.9.0-GCC-12.3.0.eb: found 267 sources + 0 patches vs 134 checksums

**Comment by boegel** [comment]
> missing checksums?
> 
> > Checksums missing for one or more sources/patches in chopper-0.9.0-GCC-12.3.0.eb: found 267 sources + 0 patches vs 134 checksums

No, caused by a bug that was fixed with https://github.com/easybuilders/easybuild-easyblocks/pull/3448

**Comment by boegel** [comment]
duplicate of:
* #21418

I'll favor that one, since it includes a patch to fix the incorrect version for chopper in `Cargo.lock`

**Pull request closed without merging**
