### PR TITLE
{numlib}[system/system] cuDNN v8.4.1.50

### PR DESCRIPTION
**Pull request by casparvl**
(created using `eb --new-pr`)

Note, this requires the EasyBlock from https://github.com/easybuilders/easybuild-easyblocks/pull/2728

@branfosj feel like one more trivial merge? It's a minor version update from the one you just merged... :)

### CODE REVIEW

**Comment by casparvl** [comment]
Test report by @casparvl
**FAILED**
Build succeeded for 0 out of 1 (1 easyconfigs in total)
software1.lisa.surfsara.nl - Linux debian 10.12, x86_64, Intel(R) Xeon(R) Silver 4110 CPU @ 2.10GHz, Python 2.7.16
See https://gist.github.com/45269c46dff1e174658071153d14ceee for a full test report.

**Comment by casparvl** [comment]
Test report by @casparvl
Using easyblocks from PR(s) https://github.com/easybuilders/easybuild-easyblocks/pull/2728
**FAILED**
Build succeeded for 0 out of 1 (1 easyconfigs in total)
gcn1 - Linux RHEL 8.4, x86_64, Intel(R) Xeon(R) Platinum 8360Y CPU @ 2.40GHz, 4 x NVIDIA NVIDIA A100-SXM4-40GB, 515.43.04, Python 3.6.8
See https://gist.github.com/e754381f81cc90eb91e27dc54a0f709b for a full test report.

**Comment by casparvl** [comment]
Test report by @casparvl
Using easyblocks from PR(s) https://github.com/easybuilders/easybuild-easyblocks/pull/2728
**SUCCESS**
Build succeeded for 2 out of 2 (1 easyconfigs in total)
gcn1 - Linux RHEL 8.4, x86_64, Intel(R) Xeon(R) Platinum 8360Y CPU @ 2.40GHz, 4 x NVIDIA NVIDIA A100-SXM4-40GB, 515.43.04, Python 3.6.8
See https://gist.github.com/3365c178f213f24280570b087e51fe4c for a full test report.

**Comment by branfosj** [comment]
Test report by @branfosj
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
bear-pg0105u36b.bear.cluster - Linux RHEL 8.6, x86_64, Intel(R) Xeon(R) Platinum 8360Y CPU @ 2.40GHz (icelake), Python 3.6.8
See https://gist.github.com/1ecad58938ce1e7f5b3c181609adf4bf for a full test report.

**Comment by branfosj** [comment]
Test report by @branfosj
**SUCCESS**
Build succeeded for 2 out of 2 (1 easyconfigs in total)
bear-pg0305u15a.bear.cluster - Linux RHEL 8.5, POWER, 8335-GTX (power9le), 1 x NVIDIA Tesla V100-SXM2-16GB, 470.57.02, Python 3.6.8
See https://gist.github.com/6064dc2ff796eb15d34d46a9312726e0 for a full test report.

**Review by branfosj — APPROVED** [review]
lgtm

**Comment by branfosj** [comment]
Going in, thanks @casparvl!

**Pull request merged**
