### PR TITLE
{lib}[GCC/10.2.0] FSON v1.0.5

### PR DESCRIPTION
**Pull request by DirectorSloan**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by jfgrimm** [comment]
@DirectorSloan can you remove the `foss` version from this PR?

**Comment by DirectorSloan** [comment]
> @DirectorSloan can you remove the `foss` version from this PR?

Renamed it (opened with `eb --new-pr`) Was this enough or did I miss something?

**Comment by jfgrimm** [comment]
@boegelbot please test @ jsc-zen2

**Comment by jfgrimm** [comment]
Test report by @jfgrimm
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
himem02.pri.viking.alces.network - Linux CentOS Linux 7.9.2009, x86_64, Intel(R) Xeon(R) Gold 6130 CPU @ 2.10GHz (skylake_avx512), Python 3.6.8
See https://gist.github.com/fe8e605c783fe4bffd04b35b003e2d62 for a full test report.

**Review by jfgrimm — APPROVED** [review]
LGTM

**Comment by jfgrimm** [comment]
Going in, thanks @DirectorSloan!

**Pull request merged**
