### PR TITLE
{lib} [GCCcore/6.4.0] libxcb v1.13

### PR DESCRIPTION
**Pull request by SimonPinches**
Note, I had to remove the sanity checks on `libxcb-xevie.a` and `libxcb-xprint.a` since I couldn't figure out why they weren't built :-(

### CODE REVIEW

**Comment by migueldiascosta** [comment]
closing and reopening o trigger tests (it's been a while, new tests were added)

**Comment by akesandgren** [comment]
Test report by @akesandgren
**SUCCESS**
Build succeeded for 4 out of 4 (4 easyconfigs in total)
b-an03.hpc2n.umu.se - Linux ubuntu 16.04, x86_64, Intel(R) Xeon(R) CPU E5-2690 v4 @ 2.60GHz, Python 2.7.12
See https://gist.github.com/5e285b08b85fad524b1161a7e630c814 for a full test report.

**Review by akesandgren — DISMISSED** [review]
LGTM

**Comment by akesandgren** [comment]
Test report by @akesandgren
**SUCCESS**
Build succeeded for 4 out of 4 (4 easyconfigs in total)
b-an03.hpc2n.umu.se - Linux ubuntu 16.04, x86_64, Intel(R) Xeon(R) CPU E5-2690 v4 @ 2.60GHz, Python 2.7.12
See https://gist.github.com/fe4bc5f39a5c99466f62d621ab37b0a2 for a full test report.

**Review by akesandgren — APPROVED** [review]
LGTM

**Comment by akesandgren** [comment]
Going in, thanks @SimonPinches!

**Pull request merged**
