### PR TITLE
{debugger}[GCCcore/8.3.0] GDB v9.1 w/ Python 3.7.4

### PR DESCRIPTION
**Pull request by furstj**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by verdurin** [comment]
Test report by @verdurin
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
generoso - Linux centos linux 7.6.1810, Intel(R) Xeon(R) CPU E5-2660 v4 @ 2.00GHz, Python 3.6.8
See https://gist.github.com/6b970fea81fd2bb3a8aeb35b23cf0779 for a full test report.

**Comment by verdurin** [comment]
@furstj any chance of submitting a test report for this?

**Comment by furstj** [comment]
Test report by @furstj
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
pc-12101-fuji - Linux UNKNOWN UNKNOWN, Intel(R) Xeon(R) CPU E3-1241 v3 @ 3.50GHz, Python 3.6.10
See https://gist.github.com/2329f39667881d0ad1e6661dea8e2402 for a full test report.

**Comment by verdurin** [comment]
Going in, thanks @furstj!

**Pull request merged**
