### PR TITLE
Pylipid 1.5.14 foss 2021b

### PR DESCRIPTION
**Pull request by jkuhl-uni**
#19421
#19427

### CODE REVIEW

**Comment by jkuhl-uni** [comment]
This needs the PRs
- [ ] #19421
- [ ] #19427
to install pylipid.

**Comment by casparvl** [comment]
You're running into the CI check that checks if only a single dependency version is used within a toolchain:

```
FAIL: test_dep_versions_per_toolchain_generation (test.easyconfigs.easyconfigs.EasyConfigTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/runner/work/easybuild-easyconfigs/easybuild-easyconfigs/test/easyconfigs/easyconfigs.py", line 891, in test_dep_versions_per_toolchain_generation
    self.fail('Should not have multiple variants of dependencies.\n' + multi_dep_vars_msg)
AssertionError: Should not have multiple variants of dependencies.
Found 3 variants of 'scikit-learn' dependency in easyconfigs using '2021b' toolchain generation
* version: 0.20.4; versionsuffix: -Python-2.7.18 as dep for {'CIRIquant-1.1.2-20221201-foss-2021b-Python-2.7.18.eb'}
  * version: 1.0.1; versionsuffix:  as dep for {'spektral-1.1.0-foss-2021b-CUDA-11.4.1.eb', 'kb-python-0.27.3-foss-2021b.eb', 'category_encoders-2.4.1-foss-2021b.eb', 'scikit-bio-0.5.7-foss-2021b.eb', 'NLTK-3.7-foss-2021b.eb', 'geopandas-0.11.0-foss-2021b.eb', 'regionmask-0.9.0-foss-2021b.eb', 'umap-learn-0.5.3-foss-2021b.eb', 'imbalanced-learn-0.9.0-foss-2021b.eb', 'infercnvpy-0.4.0-foss-2021b.eb', 'SimPEG-0.18.1-intel-2021b.eb', 'pangolin-3.1.16-foss-2021b-pangoLEARN-2021-10-18.eb', 'scanpy-1.8.2-foss-2021b.eb', 'sklearn-pandas-2.2.0-foss-2021b.eb', 'Optuna-2.10.0-foss-2021b.eb', 'PyCalib-0.1.0.dev0-foss-2021b.eb', 'panaroo-1.3.2-foss-2021b.eb', 'scanpy-1.9.1-foss-2021b.eb', 'Squidpy-1.2.2-foss-2021b.eb', 'CellTypist-1.0.0-foss-2021b.eb', 'Albumentations-1.1.0-foss-2021b.eb', 'SimPEG-0.18.1-foss-2021b.eb', 'funannotate-1.8.13-foss-2021b.eb', 'TOBIAS-0.12.12-foss-2021b.eb', 'uncertainty-calibration-0.0.9-foss-2021b.eb', 'pangolin-3.1.16-foss-2021b-pangoLEARN-2021-11-25.eb'}
  * version: 1.0.2; versionsuffix:  as dep for {'pylipid-1.5.14-foss-2021b.eb'}
```
While there are a few exceptions to this rule (e.g. when software really only works with a particular version of a dependency, or when it has proven performance benefit), I think here you should just downgrade to `scikit-learn` version `1.0.1`, as is used in the rest of this toolchain.

**Comment by jkuhl-uni** [comment]
Hey, I just commented it out. If the tests go through, I can just remove the line :)

**Comment by casparvl** [comment]
I'm confused now: does Pylipid depend on scikit-learn, or doesn't it? :D

**Comment by jkuhl-uni** [comment]
Hi, yes, it depends on scikit-learn (twice, in fact). Sorry, I misread the error you reported.
I changed the version number.
Is this a problem because with two versions coming up, it is possible that the python environment does not work properly?
I was not aware that this would be an issue (for EasyBuild, the python part is very apparent), since there are two versions of scikit-learn available in this toolchain.

**Comment by casparvl** [comment]
@boegelbot please test @ generoso

**Comment by casparvl** [comment]
@boegelbot please test @ jsc-zen2

**Comment by casparvl** [comment]
Test report by @casparvl
**FAILED**
Build succeeded for 7 out of 11 (1 easyconfigs in total)
tcn1.local.snellius.surf.nl - Linux RHEL 8.6, x86_64, AMD EPYC 7H12 64-Core Processor, Python 3.6.8
See https://gist.github.com/casparvl/8b0b2c160b8b45605e08afe7ba32d8b0 for a full test report.

**Comment by casparvl** [comment]
Ignore that failure, I seem to miss some dependencies here. I'll install those and try again.

**Comment by casparvl** [comment]
Test report by @casparvl
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
tcn1.local.snellius.surf.nl - Linux RHEL 8.6, x86_64, AMD EPYC 7H12 64-Core Processor, Python 3.6.8
See https://gist.github.com/casparvl/2b6204c8b538c14f623a874328f39f6c for a full test report.

**Review by casparvl — APPROVED** [review]
Lgtm!

**Comment by casparvl** [comment]
Going in, thanks @jkuhl-uni!

**Pull request merged**
