### PR TITLE
{chem,math}[foss/2023a,gfbf/2023a] sPyRMSD v0.8.0, rustworkx v0.15.1

### PR DESCRIPTION
**Pull request by WilleBell**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by WilleBell** [comment]
Test report by @WilleBell
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in total)
node600.hydra.os - Linux Rocky Linux 8.10, x86_64, AMD EPYC 9384X 32-Core Processor, Python 3.6.8
See https://gist.github.com/WilleBell/158bd16a927997e619e81a747b22fad5 for a full test report.

**Comment by lexming** [comment]
@boegelbot: please test @ generoso

**Comment by lexming** [comment]
@boegelbot please test @ jsc-zen3

**Review by lexming — APPROVED** [review]

**Comment by lexming** [comment]
Merging, thanks @WilleBell !

**Pull request merged**
