### PR TITLE
{data}[foss/2020b,fosscuda/2020b,intel/2020b,intelcuda/2020b] scikit-learn v0.23.2 w/ Python 3.8.6

### PR DESCRIPTION
**Pull request by Micket**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by Micket** [comment]
bah, we don't have a `modulename` parameter for python packages? How do we usually fix the module name/name mismatch?

**Comment by Micket** [comment]
@boegelbot please test @ generoso

**Comment by boegel** [comment]
Test report by @boegel
**FAILED**
Build succeeded for 9 out of 13 (4 easyconfigs in total)
node3303.joltik.os - Linux centos linux 7.9.2009, x86_64, Intel(R) Xeon(R) Gold 6242 CPU @ 2.80GHz (cascadelake), Python 3.6.8
See https://gist.github.com/04992f7cc9de22448bc2a81263559011 for a full test report.

**Review by boegel — APPROVED** [review]
lgtm

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 4 out of 4 (4 easyconfigs in total)
node3303.joltik.os - Linux centos linux 7.9.2009, x86_64, Intel(R) Xeon(R) Gold 6242 CPU @ 2.80GHz (cascadelake), Python 3.6.8
See https://gist.github.com/3aa533222b757943e464d7d4b6e6aff1 for a full test report.

**Comment by boegel** [comment]
Going in, thanks @Micket!

**Pull request merged**
