### PR TITLE
remove `CMAKE_INSTALL_LIBDIR` settings from `configopts` + add test to enfore use of `install_libdir` instead

### PR DESCRIPTION
**Pull request by lexming**
Depends on:
* [x] https://github.com/easybuilders/easybuild-easyblocks/pull/3227

### CODE REVIEW

**Comment by lexming** [comment]
@boegelbot please test @ jsc-zen3

**Comment by lexming** [comment]
@boegelbot please test @ jsc-zen3

**Comment by lexming** [comment]
@boegelbot: please test @ generoso
EB_ARGS="Arrow-0.17.1-foss-2020a-Python-3.8.2.eb Arrow-0.17.1-foss-2020b.eb Arrow-0.17.1-fosscuda-2020b.eb Arrow-0.17.1-intel-2020a-Python-3.8.2.eb Arrow-0.17.1-intel-2020b.eb Arrow-11.0.0-gfbf-2022b.eb Arrow-14.0.1-gfbf-2023a.eb Arrow-6.0.0-foss-2021a.eb Arrow-6.0.0-foss-2021b.eb Arrow-6.0.1-foss-2021a.eb Arrow-8.0.0-foss-2021a.eb Arrow-8.0.0-foss-2021b.eb Arrow-8.0.0-foss-2022.05.eb Arrow-8.0.0-foss-2022a.eb"

**Comment by lexming** [comment]
@boegelbot: please test @ generoso
EB_ARGS="Arrow-0.17.1-foss-2020a-Python-3.8.2.eb Arrow-0.17.1-foss-2020b.eb Arrow-0.17.1-intel-2020a-Python-3.8.2.eb Arrow-0.17.1-intel-2020b.eb Arrow-11.0.0-gfbf-2022b.eb Arrow-14.0.1-gfbf-2023a.eb Arrow-6.0.0-foss-2021a.eb Arrow-6.0.0-foss-2021b.eb Arrow-6.0.1-foss-2021a.eb Arrow-8.0.0-foss-2021a.eb Arrow-8.0.0-foss-2021b.eb Arrow-8.0.0-foss-2022.05.eb Arrow-8.0.0-foss-2022a.eb"

**Comment by lexming** [comment]
@boegelbot: please test @ generoso
EB_ARGS="arpack-ng-3.7.0-intel-2020a.eb Brunsli-0.1-GCCcore-10.2.0.eb Brunsli-0.1-GCCcore-10.3.0.eb Brunsli-0.1-GCCcore-11.3.0.eb Brunsli-0.1-GCCcore-12.2.0.eb Brunsli-0.1-GCCcore-12.3.0.eb"

**Comment by lexming** [comment]
@boegelbot: please test @ generoso
EB_BRANCH="5.0.x"
EB_ARGS="arpack-ng-3.7.0-intel-2020a.eb Brunsli-0.1-GCCcore-10.2.0.eb Brunsli-0.1-GCCcore-10.3.0.eb Brunsli-0.1-GCCcore-11.3.0.eb Brunsli-0.1-GCCcore-12.2.0.eb Brunsli-0.1-GCCcore-12.3.0.eb"

**Comment by lexming** [comment]
@boegelbot please test @ jsc-zen3
EB_BRANCH="5.0.x"
EB_ARGS="arpack-ng-3.7.0-intel-2020a.eb Brunsli-0.1-GCCcore-10.2.0.eb Brunsli-0.1-GCCcore-10.3.0.eb Brunsli-0.1-GCCcore-11.3.0.eb Brunsli-0.1-GCCcore-12.2.0.eb Brunsli-0.1-GCCcore-12.3.0.eb"

**Comment by lexming** [comment]
@boegelbot please test @ jsc-zen3
EB_ARGS="arpack-ng-3.7.0-intel-2020a.eb Brunsli-0.1-GCCcore-10.2.0.eb Brunsli-0.1-GCCcore-10.3.0.eb Brunsli-0.1-GCCcore-11.3.0.eb Brunsli-0.1-GCCcore-12.2.0.eb Brunsli-0.1-GCCcore-12.3.0.eb"
EB_BRANCH="5.0.x"

**Comment by lexming** [comment]
@boegelbot please test @ jsc-zen3
EB_ARGS="arpack-ng-3.7.0-intel-2020a.eb Brunsli-0.1-GCCcore-10.2.0.eb Brunsli-0.1-GCCcore-10.3.0.eb Brunsli-0.1-GCCcore-11.3.0.eb Brunsli-0.1-GCCcore-12.2.0.eb Brunsli-0.1-GCCcore-12.3.0.eb"
EB_BRANCH="5.0.x"

**Comment by lexming** [comment]
@boegelbot please test @ jsc-zen3
EB_ARGS="Arrow-11.0.0-gfbf-2022b.eb Arrow-14.0.1-gfbf-2023a.eb Arrow-8.0.0-foss-2022.05.eb Arrow-8.0.0-foss-2022a.eb Brunsli-0.1-GCCcore-11.3.0.eb Brunsli-0.1-GCCcore-12.2.0.eb Brunsli-0.1-GCCcore-12.3.0.eb flatbuffers-2.0.7-GCCcore-11.3.0.eb LERC-4.0.0-GCCcore-11.3.0.eb LERC-4.0.0-GCCcore-12.2.0.eb LERC-4.0.0-GCCcore-12.3.0.eb LERC-4.0.0-GCCcore-13.2.0.eb Lab-Streaming-Layer-1.16.2-GCCcore-12.3.0.eb libjpeg-turbo-2.1.3-GCCcore-11.3.0.eb  libjpeg-turbo-2.1.4-GCCcore-12.2.0.eb libjpeg-turbo-2.1.5.1-GCCcore-12.3.0.eb libjpeg-turbo-3.0.1-GCCcore-13.2.0.eb OpenMEEG-2.5.7-foss-2023a.eb VTK-9.2.2-foss-2022a.eb VTK-9.2.6-foss-2022b.eb  VTK-9.3.0-foss-2023a.eb VTK-9.3.0-foss-2023b.eb"
EB_BRANCH=5.0.x

**Review by boegel — APPROVED** [review]

**Comment by boegel** [comment]
Going in, thanks @lexming!

**Pull request merged**
