### PR TITLE
{vis}[GCCcore/8.3.0] fontconfig v2.13.1

### PR DESCRIPTION
**Pull request by Micket**
(created using `eb --new-pr`)

depends on ~#8621~ ~#8622~ ~#8624~ ~#8625~ ~#8626~

### CODE REVIEW

**Comment by Micket** [comment]
Test report by @Micket
**SUCCESS**
Build succeeded for 0 out of 0 (1 easyconfigs in this PR)
vera-c1 - Linux centos linux 7.6.1810, Intel Xeon Processor (Skylake), Python 2.7.5
See https://gist.github.com/97f9df9762c3670d4c5e7c0c8f1f6f1d for a full test report.

**Comment by Micket** [comment]
Test report by @Micket
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
vera-c1 - Linux centos linux 7.6.1810, Intel Xeon Processor (Skylake), Python 2.7.5
See https://gist.github.com/67c9dc10a10256b61bd8cf3645015264 for a full test report.

**Comment by vanzod** [comment]
Re-trigger Travis

**Comment by vanzod** [comment]
Test report by @vanzod
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
cermis - Linux debian 9.9, Intel(R) Xeon(R) CPU           X5670  @ 2.93GHz, Python 2.7.13
See https://gist.github.com/dec8a9610202398861b8f31276de018f for a full test report.

**Comment by vanzod** [comment]
Going in, thanks @Micket!

**Pull request merged**
