### PR TITLE
{bio}[gompi/2020a] mauveAligner v4736

### PR DESCRIPTION
**Pull request by hajgato**
build without a GUI

Binary tests are not possible as all the commands exit with non-zero exit-code without proper input file(s) (and sometimes parameter(s))

### CODE REVIEW

**Comment by hajgato** [comment]
No checksum can be provided on the sources.

**Comment by smoors** [comment]
Test report by @smoors
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
node374.hydra.os - Linux centos linux 7.7.1908, x86_64, Intel(R) Xeon(R) Gold 6148 CPU @ 2.40GHz (skylake_avx512), Python 2.7.5
See https://gist.github.com/3117e87a32997a036c84afac338254cf for a full test report.

**Review by smoors — APPROVED** [review]
lgtm

**Comment by smoors** [comment]
Going in, thanks @hajgato!

**Pull request merged**
