### PR TITLE
Adds MCR 2019b and 2020a/b, updates 2019a with the latest update, 9.

### PR DESCRIPTION
**Pull request by robert-mijakovic**
(created using `eb --new-pr`)

### CODE REVIEW

**Review by branfosj — CHANGES_REQUESTED** [review]
Based on the discussion on Slack, these should change so that the update number is part of the version or a versionsuffix. The old `MCR-R2019a.eb` should be left as it is and a new one with the new name added. The R2020a and R2020b ones can be renamed as we only added these a few days ago.

**Comment by robert-mijakovic** [comment]
@branfosj Forgot to say that this is done

**Comment by verdurin** [comment]
@branfosj are you happy with these now?

**Review by branfosj — APPROVED** [review]
lgtm

**Comment by branfosj** [comment]
@boegelbot please test @ generoso

**Comment by branfosj** [comment]
Test report by @branfosj
**SUCCESS**
Build succeeded for 4 out of 4 (4 easyconfigs in total)
bear-pg0206u40a.bear.cluster - Linux RHEL 8.3, x86_64, Intel(R) Xeon(R) Gold 6248 CPU @ 2.50GHz (cascadelake), Python 3.6.8
See https://gist.github.com/780ef58404140d6b260e9667c9586e0d for a full test report.

**Comment by branfosj** [comment]
Going in, thanks @robert-mijakovic!

**Pull request merged**
