### PR TITLE
{vis}[fosscuda/2018b] OpenCV v3.4.5

### PR DESCRIPTION
**Pull request by akesandgren**
(created using `eb --new-pr`)
Depends on ~~https://github.com/easybuilders/easybuild-easyconfigs/pull/7658, https://github.com/easybuilders/easybuild-easyconfigs/pull/7650~~

### CODE REVIEW

**Comment by akesandgren** [comment]
Test report by @akesandgren
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
b-an03.hpc2n.umu.se - Linux ubuntu 16.04, Intel(R) Xeon(R) CPU E5-2690 v4 @ 2.60GHz, Python 2.7.12
See https://gist.github.com/295bcf77a2f33569bb56e68eb7ab9b78 for a full test report.

**Comment by boegel** [comment]
kicking Travis...

**Comment by akesandgren** [comment]
The main reason for using GTK+ 3.x is that WebKitGTK+ #7677 requires GTK+ 3 and they are both dependencies of #7680 

So @boegel suggestions for moving forward? target this for a 2019a toolchain where we switch to GTK+ 3 or making an exception?

**Comment by akesandgren** [comment]
OpenCV and a lot of others should be brought down to GCC level or maybe GCCcore...

**Comment by boegel** [comment]
@akesandgren Strictly speaking `fosscuda/2018b` is deprecated now.

Should we put more effort in this, or just close it (as well as the PRs that depend on it)?

**Comment by boegel** [comment]
deprecated toolchain, and we already have OpenCV easyconfigs merged (see https://github.com/easybuilders/easybuild-easyconfigs/pull/9191 for example), so closing this...

**Pull request closed without merging**
