### PR TITLE
add aarch64 and ppc64le checksums to NVHPC 23.7

### PR DESCRIPTION
**Pull request by SebastianAchilles**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by SebastianAchilles** [comment]
@boegelbot please test @ jsc-zen2
EB_ARGS="--fetch"

**Comment by SebastianAchilles** [comment]
@boegelbot please test @ generoso
EB_ARGS="--fetch"

**Review by smoors — APPROVED** [review]
lgtm

**Comment by smoors** [comment]
Going in, thanks @SebastianAchilles!

**Pull request merged**
