### PR TITLE
{bio}[foss/2021a] GROMACS v2021.3 w/ Python 3.9.5 + CUDA 11.3.1 + PLUMED v2.7.2

### PR DESCRIPTION
**Pull request by smoors**
(created using `eb --new-pr`)

depends on easyblock PR
- [x] https://github.com/easybuilders/easybuild-easyblocks/pull/2621

### CODE REVIEW

**Comment by smoors** [comment]
@boegelbot please test @ generoso EB_ARGS="--include-easyblocks-from-pr 2621"

**Comment by smoors** [comment]
Test report by @smoors
**FAILED**
Build succeeded for 0 out of 1 (1 easyconfigs in total)
node400.hydra.os - Linux centos linux 7.9.2009, x86_64, AMD EPYC 7282 16-Core Processor (zen2), 1 x NVIDIA A100-PCIE-40GB, 460.73.01, Python 2.7.5
See https://gist.github.com/77ab007c141c7270ccf6db7a71eb005c for a full test report.

**Comment by smoors** [comment]
Test report by @smoors
Using easyblocks from PR(s) https://github.com/easybuilders/easybuild-easyblocks/pull/2621
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
node400.hydra.os - Linux centos linux 7.9.2009, x86_64, AMD EPYC 7282 16-Core Processor (zen2), 2 x NVIDIA A100-PCIE-40GB, 460.73.01, Python 2.7.5
See https://gist.github.com/5a972259194b0a442397eda31ceff576 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
Using easyblocks from PR(s) https://github.com/easybuilders/easybuild-easyblocks/pull/2621
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
node3152.skitty.os - Linux centos linux 7.9.2009, x86_64, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz (skylake_avx512), Python 3.6.8
See https://gist.github.com/c86a297609912711f95eea4e8bc20c23 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
Using easyblocks from PR(s) https://github.com/easybuilders/easybuild-easyblocks/pull/2621
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
node3302.joltik.os - Linux centos linux 7.9.2009, x86_64, Intel(R) Xeon(R) Gold 6242 CPU @ 2.80GHz (cascadelake), 4 x NVIDIA NVIDIA Tesla V100-SXM2-32GB, 465.19.01, Python 3.6.8
See https://gist.github.com/d09896962dafaff4d0f943eb047c246a for a full test report.

**Review by boegel — APPROVED** [review]
lgtm

**Comment by boegel** [comment]
Going in, thanks @smoors!

**Pull request merged**
