### PR TITLE
{vis}[intel/2017b] Ferret 7.3 (REVIEW)

### PR DESCRIPTION
**Pull request by hajgato**
Needs ~~https://github.com/easybuilders/easybuild-easyblocks/pull/1349~~

replaces ~~https://github.com/easybuilders/easybuild-easyconfigs/pull/4633~~

### CODE REVIEW

**Comment by verdurin** [comment]
Test report by @verdurin
**SUCCESS**
Build succeeded for 4 out of 4 (1 easyconfigs in this PR)
rescomp2 - Linux centos 6.8, Intel(R) Xeon(R) CPU E5-2650 v2 @ 2.60GHz, Python 2.7.11
See https://gist.github.com/1c9dcf7d8d0a2965b2108559f5028457 for a full test report.

**Comment by verdurin** [comment]
I won't merge until https://github.com/easybuilders/easybuild-easyblocks/pull/1349 is merged - @boegel ?

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
node2021.delcatty.os - Linux centos linux 7.6.1810, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.7.5
See https://gist.github.com/894897afd4deef9459cd0226188ab0a4 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
node2409.golett.os - Linux centos linux 7.6.1810, Intel(R) Xeon(R) CPU E5-2680 v3 @ 2.50GHz, Python 2.7.5
See https://gist.github.com/5625c0f4b56bcea8188c2015e1c78a71 for a full test report.

**Comment by boegel** [comment]
Going in, thanks @hajgato!

**Pull request merged**
