### PR TITLE
{ai,lib}[foss/2023a,gfbf/2023a] RAPIDS v24.4, CUDA-Python v12.1.0 w/ CUDA 12.1.1

### PR DESCRIPTION
**Pull request by lexming**
(created using `eb --new-pr`)

Depends on:

* [x] https://github.com/easybuilders/easybuild-easyconfigs/pull/21056

:warning: this needs an actual Nvidia GPU device to pass the sanity checks, and it has to be Volta or newer

### CODE REVIEW

**Comment by lexming** [comment]
Test report by @lexming
**SUCCESS**
Build succeeded for 4 out of 4 (2 easyconfigs in total)
node403.hydra.os - Linux Rocky Linux 8.10, x86_64, AMD EPYC 7282 16-Core Processor (zen2), 1 x NVIDIA NVIDIA A100-PCIE-40GB, 550.90.07, Python 3.6.8
See https://gist.github.com/lexming/878bc1b22d4964b9e5203298c8a56c9e for a full test report.

**Comment by VRehnberg** [comment]
Test report by @VRehnberg
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
alvis1-06 - Linux Rocky Linux 8.9, x86_64, Intel(R) Xeon(R) Gold 6244 CPU @ 3.60GHz, 1 x NVIDIA Tesla V100-SXM2-32GB, 550.54.14, Python 3.6.8
See https://gist.github.com/VRehnberg/9e66063671585fa966cda7d1ca88bec0 for a full test report.

**Comment by VRehnberg** [comment]
Test report by @VRehnberg
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
alvis1-06 - Linux Rocky Linux 8.9, x86_64, Intel(R) Xeon(R) Gold 6244 CPU @ 3.60GHz, 1 x NVIDIA Tesla V100-SXM2-32GB, 550.54.14, Python 3.6.8
See https://gist.github.com/VRehnberg/bedbdd2d519a1fcbb26a6ed8f3d39619 for a full test report.

**Comment by VRehnberg** [comment]
Test report by @VRehnberg
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
alvis1-06 - Linux Rocky Linux 8.9, x86_64, Intel(R) Xeon(R) Gold 6244 CPU @ 3.60GHz, 1 x NVIDIA Tesla V100-SXM2-32GB, 550.54.14, Python 3.6.8
See https://gist.github.com/VRehnberg/8ab750090d92370d20ffdc05953e02c0 for a full test report.

**Comment by VRehnberg** [comment]
Test report by @VRehnberg
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
alvis1-06 - Linux Rocky Linux 8.9, x86_64, Intel(R) Xeon(R) Gold 6244 CPU @ 3.60GHz, 1 x NVIDIA Tesla V100-SXM2-32GB, 550.54.14, Python 3.6.8
See https://gist.github.com/VRehnberg/b7f37707afc9014a518dfc625e78fe29 for a full test report.

**Comment by VRehnberg** [comment]
Test report by @VRehnberg
**FAILED**
Build succeeded for 0 out of 1 (1 easyconfigs in total)
alvis1-06 - Linux Rocky Linux 8.9, x86_64, Intel(R) Xeon(R) Gold 6244 CPU @ 3.60GHz, 1 x NVIDIA Tesla V100-SXM2-32GB, 550.54.14, Python 3.6.8
See https://gist.github.com/VRehnberg/16b3ace385760c9341362e0bd71279a5 for a full test report.

**Comment by boegel** [comment]
@VRehnberg Last attempt failed with "`ModuleNotFoundError: No module named 'pyarrow._orc'`" because changes in https://github.com/easybuilders/easybuild-easyconfigs/pull/21056 were not taken into account?

**Comment by VRehnberg** [comment]
Probably. Will try to remember to do a rerun tomorrow.

**Comment by lexming** [comment]
Synced with current develop branch, which will help with those issues.

**Comment by boegel** [comment]
@boegelbot please test @ jsc-zen3-a100

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in total)
node3306.joltik.os - Linux RHEL 8.8, x86_64, Intel(R) Xeon(R) Gold 6242 CPU @ 2.80GHz, 1 x NVIDIA Tesla V100-SXM2-32GB, 545.23.08, Python 3.6.8
See https://gist.github.com/boegel/5306bfd109aa242df97cf6d5e0e11a11 for a full test report.

**Review by boegel — APPROVED** [review]
lgtm

**Comment by boegel** [comment]
Going in, thanks @lexming!

**Comment by boegel** [comment]
Going in, thanks @lexming!

**Pull request merged**
