### PR TITLE
{chem}[foss/2017b,intel/2017b] Amber v16-AT-17

### PR DESCRIPTION
**Pull request by vanzod**
Requires:
~#7751~ (Amber-16-AT-17_fix_fixed_size_cmd_in_nab.patch)

### CODE REVIEW

**Comment by vanzod** [comment]
Test report by @vanzod
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in this PR)
cermis - Linux debian 9.7, Intel(R) Xeon(R) CPU           X5670  @ 2.93GHz, Python 2.7.13
See https://gist.github.com/8589cd23449e7cc8ce0960af962b97fe for a full test report.

**Comment by akesandgren** [comment]
Does this include the new nab fix? i.e. checksum-wise Or perhaps handle that when the cuda version is merged?

**Comment by vanzod** [comment]
No, this one went smooth with the old patches. Let me update it

**Comment by akesandgren** [comment]
Yeah, FLIBS is small enough when not using intelcuda probably.

**Comment by vanzod** [comment]
Test report by @vanzod
**FAILED**
Build succeeded for 0 out of 2 (2 easyconfigs in this PR)
cermis - Linux debian 9.7, Intel(R) Xeon(R) CPU           X5670  @ 2.93GHz, Python 2.7.13
See https://gist.github.com/c5d2f79682ff4e503f033aa7d62bb9de for a full test report.

**Comment by akesandgren** [comment]
Throw in a new test report? I'll see if i can get one running before i give up...

**Comment by vanzod** [comment]
It has been running for 4 hours now...

**Comment by vanzod** [comment]
Test report by @vanzod
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in this PR)
cermis - Linux debian 9.8, Intel(R) Xeon(R) CPU           X5670  @ 2.93GHz, Python 2.7.13
See https://gist.github.com/476f43fa628ca282056fcf0b8a2b236b for a full test report.

**Comment by akesandgren** [comment]
Going in, thanks @vanzod!

**Pull request merged**
