### PR TITLE
{math}[foss/2021a] CVXOPT v1.2.6 w/ Python 3.9.5

### PR DESCRIPTION
**Pull request by Micket**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by Micket** [comment]
Test report by @Micket
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
alvis-c1 - Linux centos linux 7.9.2009, x86_64, Intel Xeon Processor (Skylake), Python 3.6.8
See https://gist.github.com/8f8fe23dfd17d8a2992f1f598778ce00 for a full test report.

**Comment by lexming** [comment]
Test report by @lexming
**SUCCESS**
Build succeeded for 3 out of 3 (1 easyconfigs in total)
node378.hydra.os - Linux centos linux 7.9.2009, x86_64, Intel(R) Xeon(R) Gold 6148 CPU @ 2.40GHz, Python 2.7.5
See https://gist.github.com/31d2f8fe8d2978345c6a289e87e759e5 for a full test report.

**Review by lexming — APPROVED** [review]
LGTM

**Comment by lexming** [comment]
Going in, thanks @Micket !

**Comment by Flamefire** [comment]
This fails for me to build the umfpack extension because it tries to access a file from the SuiteSPARSE sources while we point it to the install dir. In Particular:
https://github.com/cvxopt/cvxopt/blob/1.2.6/setup.py#L201

How did this work for you?

**Pull request merged**
