### PR TITLE
fix pkgconfig moduleclass, 'data' doesn't make much sense

### PR DESCRIPTION
**Pull request by boegel**
fix for #5816

cc @verdurin

### CODE REVIEW

**Comment by verdurin** [comment]
@boegel - this is such a trivial change, I won't bother trying to build them all.

**Comment by boegel** [comment]
@verdurin Makes perfect sense for this one, of course.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 17 out of 17 (17 easyconfigs in this PR)
node2035.delcatty.os - Linux centos linux 7.4.1708, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.7.5
See https://gist.github.com/c3f93cc736687aae0d46c89497101266 for a full test report.

**Comment by migueldiascosta** [comment]
Going in, thanks @boegel!

**Pull request merged**
