### PR TITLE
{chem}[foss/2023b] pyMBE v0.8.0

### PR DESCRIPTION
**Pull request by bedroge**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by bedroge** [comment]
Test report by @bedroge
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
bob-Latitude-5300 - Linux Ubuntu 22.04, x86_64, Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz, Python 3.10.12
See https://gist.github.com/bedroge/05a138d9859a4f109d3a92a5375d8887 for a full test report.

**Comment by bedroge** [comment]
Test report by @bedroge
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
bob-Latitude-5300 - Linux Ubuntu 22.04, x86_64, Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz, Python 3.10.12
See https://gist.github.com/bedroge/7f0701d48ae5ed922f7360a74130f4e2 for a full test report.

**Comment by jngrad** [comment]
Thank you for adding pyMBE to EasyBuild! Notifying @pm-blanco.

In the next release of pyMBE, we will re-organize the Python files into a neater folder structure, so that the pyMBE Python module can be deployed on Pypi without the testsuite and other auxiliary files (https://github.com/pyMBE-dev/pyMBE/issues/13). Let us know if the current structure of pyMBE is causing you trouble.

**Comment by pm-blanco** [comment]
Let me join @jngrad  in thanking you for adding pyMBE to EasyBuild :smile:  Many of our users use pyMBE in their simulation scripts in HPC centers and it will be very useful that they can load pyMBE directly as a module. 

As @jngrad said, we are underway of refactoring the folder structure of pyMBE to make its installation easier. Hopefully, this will avoid the need of the work around you mentioned @bedroge and make the installation cleaner in further releases of the module.

**Comment by bedroge** [comment]
Test report by @bedroge
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
interactive1 - Linux Rocky Linux 8.9, x86_64, AMD EPYC-Milan Processor (zen3), Python 3.6.8
See https://gist.github.com/bedroge/5280a99e74ae8d6cdfe52dec1266cbb6 for a full test report.

**Comment by jngrad** [comment]
@bedroge Maybe something like `rsync -a pyMBE.py pyMBE visualization lib parameters easybuild_destination_path` would help reduce noise?

**Comment by bedroge** [comment]
> @bedroge Maybe something like `rsync -a pyMBE.py pyMBE visualization lib parameters easybuild_destination_path` would help reduce noise?

I'm not sure if I can easily change that (the required easyblock that offers such functionality doesn't seem to be supported for extensions), though I could remove the files that are not really required. On the other hand, the current installation takes up about 12 MB, so maybe we shouldn't have to worry about this (and plenty of other packages also include tests, examples, etc).

**Comment by bedroge** [comment]
@boegelbot please test @ generoso

**Comment by jngrad** [comment]
> @bedroge Maybe something like `rsync -a pyMBE.py pyMBE visualization lib parameters easybuild_destination_path` would help reduce noise?

Nevermind, this doesn't actually work, because we use our custom path detection tool to locate test files relative to pyMBeE. In the next release of pyMBE, we will use the standard path detection tool based on modules relative paths.

> I've now worked around it by just copying the contents of the tarball to the installation directory, and setting `$PYTHONPATH` to this directory. As far as I can tell, things seem to work fine now, but if you think this may break anything, do let me know.

That should work. Our users achieve the same result by setting the path to the installation directory in a `.pth` file in their conda or venv environment, which is equivalent to adding the installation directory to the `$PYTHONPATH`.

By the way, once we re-organize pyMBE as a standard Python package, the testsuite will still be part of the release tarball but will no longer be deployed. Will this be an issue when adding pyMBE to EESSI? EESSI needs a testsuite to verify the app works on all HPC architectures.

**Comment by bedroge** [comment]
> > I've now worked around it by just copying the contents of the tarball to the installation directory, and setting `$PYTHONPATH` to this directory. As far as I can tell, things seem to work fine now, but if you think this may break anything, do let me know.
> 
> That should work. Our users achieve the same result by setting the path to the installation directory in a `.pth` file in their conda or venv environment, which is equivalent to adding the installation directory to the `$PYTHONPATH`.
> 

Okay, thanks!

> By the way, once we re-organize pyMBE as a standard Python package, the testsuite will still be part of the release tarball but will no longer be deployed. Will this be an issue when adding pyMBE to EESSI? EESSI needs a testsuite to verify the app works on all HPC architectures.

That shouldn't cause any issues. We can perhaps still add some simple/short test to the sanity check of the easyconfig (it would be convenient if any required files are part of the package, but otherwise it could still fetch them from somewhere else), and if we want to add a ReFrame test to the EESSI test suite, we can include the required files with the test or let the test itself fetch all the required input files.

**Comment by bedroge** [comment]
@boegelbot please test @ jsc-zen3

**Comment by jngrad** [comment]
> We can perhaps still add some simple/short test to the sanity check of the easyconfig (it would be convenient if any required files are part of the package, but otherwise it could still fetch them from somewhere else), and if we want to add a ReFrame test to the EESSI test suite, we can include the required files with the test or let the test itself fetch all the required input files.

Alright! The testsuite is currently controlled via the Makefile. Command `make unit_tests` runs the testsuite sequentially and takes about 2 min. We run these on every commit. Command  `make functional_tests` runs extremely long simulations (40 min), for example the Beyer et al. 2024 paper simulations, to make sure the published data is reproducible. We run those once every 2 weeks and on every release. Command `make tests` runs the two previous commands and is only there for backward compatibility with our developers (muscle memory).

**Review by ocaisa — APPROVED** [review]
LGTM

**Pull request merged**
