### PR TITLE
add sanity check commands for recent GDB versions

### PR DESCRIPTION
**Pull request by boegel**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by boegel** [comment]
@boegelbot please test @ generoso
EB_ARGS="--sanity-check-only"

**Review by Micket — APPROVED** [review]
lgtm

**Comment by Micket** [comment]
Test report by @Micket
**SUCCESS**
Build succeeded for 19 out of 19 (6 easyconfigs in total)
alvis-c1 - Linux Rocky Linux 8.8, x86_64, Intel Xeon Processor (Skylake), Python 3.6.8
See https://gist.github.com/Micket/7179a98f3baf6494c89035891b786595 for a full test report.

**Comment by Micket** [comment]
Going in, thanks @boegel!

**Pull request merged**
