### PR TITLE
{chem}[fosscuda/2017b,intelcuda/2017b] Amber v16-AT-17

### PR DESCRIPTION
**Pull request by vanzod**
Depends on:
~#7720~ (HDF5)

### CODE REVIEW

**Comment by vanzod** [comment]
@akesandgren Could you please test the `intelcuda` easyconfig file? For some reason on my box I get the following segfault:
```
ranlib /opt/easybuild/software/MPI/intel-CUDA/2017.4.196-GCC-6.4.0-2.28-9.0.176/impi/2017.3.196/Amber/16-AmberTools-17-patchlevel-10-15/lib/libnab.a
/opt/easybuild/software/MPI/intel-CUDA/2017.4.196-GCC-6.4.0-2.28-9.0.176/impi/2017.3.196/Amber/16-AmberTools-17-patchlevel-10-15/bin/nab -c matextract.nab
/opt/easybuild/software/MPI/intel-CUDA/2017.4.196-GCC-6.4.0-2.28-9.0.176/impi/2017.3.196/Amber/16-AmberTools-17-patchlevel-10-15/bin/nab -o matextract matextract.o -fopenmp
Segmentation fault
Makefile:57: recipe for target 'matextract' failed
make[2]: *** [matextract] Error 139
```

**Comment by akesandgren** [comment]
The HDF5 for fosscuda/2017b and deps, is that coming from another PR or did you just forget about them?

**Comment by akesandgren** [comment]
Test report by @akesandgren
**FAILED**
Build succeeded for 28 out of 29 (1 easyconfigs in this PR)
b-an03.hpc2n.umu.se - Linux ubuntu 16.04, Intel(R) Xeon(R) CPU E5-2690 v4 @ 2.60GHz, Python 2.7.12
See https://gist.github.com/d2675fc11f706ad45f2b546d59275e1b for a full test report.

**Comment by akesandgren** [comment]
I'm getting the same segfault. I'll try to take a look.

**Comment by akesandgren** [comment]
Found the problem, testing a better patch for nab.c

**Comment by vanzod** [comment]
@akesandgren Thanks. I have updated the deps list in the first comment. Thanks for pointing it out

**Comment by akesandgren** [comment]
Found more problems... testing a new patch. Why do people insist on using fixed sized buffers without checking that they stay within their boundaries.

**Comment by akesandgren** [comment]
Bug in nab fixed, see PR to this PR.

It still fails for intelcuda with
error: identifier "__float128" is undefined

**Comment by vanzod** [comment]
@akesandgren It looks like your patch update fixed the `intelcuda` build but now `fosscuda` fails because of a type issue
```
mpicc -DCC='"mpicc"' -DFLIBS='"-lsff -lpbsa -lrism -L/opt/easybuild/software/MPI/GCC-CUDA/6.4.0-2.28-9.0.176/OpenMPI/2.1.1/FFTW/3.3.6/lib -lfftw3 -larpack -lopenblas -lgfortran -lpthread  -L/opt/easybuild/software/MPI/GCC-CUDA/6.4.0-2.28-9.0.176/OpenMPI/2.1.1/netCDF/4.4.1.1/lib -lnetcdf  -lgfortran -w "' \
	 -fPIC -O2 -ftree-vectorize -march=native -fno-math-errno -fopenmp -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -DBINTRAJ -DHASGZ -DHASBZ2  -fopenmp    \
	-fopenmp   -o /opt/easybuild/software/MPI/GCC-CUDA/6.4.0-2.28-9.0.176/OpenMPI/2.1.1/Amber/16-AmberTools-17-patchlevel-10-15/bin/nab nab.c
nab.c: In function ‘n2c’:
nab.c:172:26: warning: passing argument 2 of ‘split’ from incompatible pointer type [-Wincompatible-pointer-types]
    nfields = split( cmd, &fields, " " );
                          ^
nab.c:25:12: note: expected ‘char **’ but argument is of type ‘char ***’
 static int split( char [], char *[], char * );
            ^~~~~
nab.c:208:26: warning: passing argument 2 of ‘split’ from incompatible pointer type [-Wincompatible-pointer-types]
    nfields = split( cmd, &fields, " " );
                          ^
nab.c:25:12: note: expected ‘char **’ but argument is of type ‘char ***’
 static int split( char [], char *[], char * );
            ^~~~~
nab.c: In function ‘cc’:
nab.c:315:23: warning: passing argument 2 of ‘split’ from incompatible pointer type [-Wincompatible-pointer-types]
  nfields = split(cmd, &fields, " ");
                       ^
nab.c:25:12: note: expected ‘char **’ but argument is of type ‘char ***’
 static int split( char [], char *[], char * );
            ^~~~~
nab.c: At top level:
nab.c:327:12: error: conflicting types for ‘split’
 static int split( char str[], char ***fields, char *fsep )
            ^~~~~
nab.c:25:12: note: previous declaration of ‘split’ was here
 static int split( char [], char *[], char * );
            ^~~~~
nab.c:25:12: warning: ‘split’ used but never defined
```

**Comment by akesandgren** [comment]
Oops, sorry, split should be
static int split( char str[], char ***fields, char *fsep )
I forgot the initial declaration.

Please fix...

**Comment by vanzod** [comment]
Test report by @vanzod
**SUCCESS**
Build succeeded for 7 out of 7 (7 easyconfigs in this PR)
cermis - Linux debian 9.7, Intel(R) Xeon(R) CPU           X5670  @ 2.93GHz, Python 2.7.13
See https://gist.github.com/12fae14c7efa32a3069968a5c74a4652 for a full test report.

**Comment by akesandgren** [comment]
Test report by @akesandgren
**SUCCESS**
Build succeeded for 7 out of 7 (7 easyconfigs in this PR)
b-an03.hpc2n.umu.se - Linux ubuntu 16.04, Intel(R) Xeon(R) CPU E5-2690 v4 @ 2.60GHz, Python 2.7.12
See https://gist.github.com/7fd5320d4c8385071bcc6110dab51c12 for a full test report.

**Comment by akesandgren** [comment]
Happy with this now @vanzod ? If so remove the "WIP"

**Comment by akesandgren** [comment]
Going in, thanks @vanzod!

**Pull request merged**
