### PR TITLE
{vis}[intel/2018a] VTK v8.1.1 w/ MPI support

### PR DESCRIPTION
**Pull request by boegel**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by boegel** [comment]
One option here is to always enable MPI support in `VTK`... Thoughts @wpoely86?

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
node2645.swalot.os - Linux centos linux 7.4.1708, Intel(R) Xeon(R) CPU E5-2660 v3 @ 2.60GHz, Python 2.7.5
See https://gist.github.com/898b668c9749dcde4f5ff1528619cc1d for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
node2109.delcatty.os - Linux centos linux 7.4.1708, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.7.5
See https://gist.github.com/342554b20c62c55dbeb3d416769599fb for a full test report.

**Comment by wpoely86** [comment]
Not sure if that is a good or bad idea. What else except ParaView is using this?

**Comment by boegel** [comment]
@wpoely86 In ParaView, we don't list VTK as a dependency, we currently let ParaView install its own VTK (and that one gets built with `-DVTK_Group_MPI:BOOL=ON`).

I need a MPI-able VTK build as a dependency for `CFDEMcoupling` (https://github.com/CFDEMproject/CFDEMcoupling-PUBLIC).

I think it's OK to always enable MPI support in VTK, it's just making the VTK installation more capable?

**Comment by verdurin** [comment]
Test report by @verdurin
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
rescomp2 - Linux centos 6.8, Intel(R) Xeon(R) CPU E5-2650 v2 @ 2.60GHz, Python 2.7.11
See https://gist.github.com/d363bc8031e38c270030a20e57f33984 for a full test report.

**Pull request merged**
