### PR TITLE
fix BLAS/Lapack linking for Hypre

### PR DESCRIPTION
**Pull request by Micket**
(created using `eb --new-pr`)

Depends on https://github.com/easybuilders/easybuild-easyblocks/pull/1885

### CODE REVIEW

**Comment by boegel** [comment]
@Micket Does this also apply to older/newer versions of Hypre?

**Comment by boegel** [comment]
Test report by @boegel
**FAILED**
Build succeeded for 0 out of 2 (2 easyconfigs in this PR)
node3105.skitty.os - Linux centos linux 7.7.1908, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz, Python 3.6.8
See https://gist.github.com/6dad45818fb091bfb248bc06fd7a00bb for a full test report.

**Comment by boegel** [comment]
@Micket @lexming Is still still relevant now https://github.com/easybuilders/easybuild-easyblocks/pull/1885 is merged?

**Comment by Micket** [comment]
Nope.  Not really sure it ever was. Static linking just ignores everything anyway and just leaves it up to whoever links to HYPRE to know that it requires external symbols (static libraries are the worst thing ever), and for dynamic libraries, it just does a lot of hacks with macros so it's own "blas" is just ignored garbage in the final library anyway.

**Pull request closed without merging**
