### PR TITLE
{data, tools}[foss/2023a] Hydra v1.3.2, optuna v2.10.1

### PR DESCRIPTION
**Pull request by ItIsI-Orient**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by smoors** [comment]
@ItIsI-Orient the list of extensions is quite long, please split Optuna into its own easyconfig?

**Comment by smoors** [comment]
@ItIsI-Orient is it really needed to use the old `2.10.1` version of optuna here?
optuna is already at version `3.4.0`, there is already `Optuna-3.1.0-foss-2022a.eb` in the EB repo.
the latter easyconfig also contains a lot less extensions.

**Comment by ItIsI-Orient** [comment]
@smoors `hydra-optuna-sweeper` has a requirement of `optuna<3.0.0` and `2.10.1` is the most recent stable release, that meets the requirement. I haven't tried to bypass the requirements because I am not sure about the functionality/stability of the final build. Should I still try to bypass them?

**Comment by pavelToman** [comment]
PR to replace this one:
- https://github.com/easybuilders/easybuild-easyconfigs/pull/21977

**Pull request closed without merging**
