### PR TITLE
{tools}[GCCcore/13.3.0] GLPK v5.0

### PR DESCRIPTION
**Pull request by branfosj**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by branfosj** [comment]
@boegelbot please test @ jsc-zen3

**Comment by branfosj** [comment]
Test report by @branfosj
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
bear-pg0210u03a.bear.cluster - Linux RHEL 8.6, x86_64, Intel(R) Xeon(R) Platinum 8480CL (sapphirerapids), Python 3.6.8
See https://gist.github.com/branfosj/913ba8acf7806f3cf0064ebd52b9b042 for a full test report.

**Comment by branfosj** [comment]
@boegelbot please test @ generoso

**Comment by smoors** [comment]
Going in, thanks @branfosj!

**Pull request merged**
