### PR TITLE
{phys}[system/system] optiSLang v2024R1

### PR DESCRIPTION
**Pull request by appolloford**
(created using `eb --new-pr`)

Depends on:
* [x] https://github.com/easybuilders/easybuild-easyblocks/pull/3300

### CODE REVIEW

**Comment by appolloford** [comment]
Test report by @appolloford
Using easyblocks from PR(s) https://github.com/easybuilders/easybuild-easyblocks/pull/3300
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
vera40-1 - Linux Rocky Linux 8.9, x86_64, Intel(R) Xeon(R) Gold 6130 CPU @ 2.10GHz, 1 x NVIDIA Tesla T4, 550.54.14, Python 3.6.8
See https://gist.github.com/appolloford/677f3417a9636bf8559188c14bcab38c for a full test report.

**Comment by smoors** [comment]
@appolloford can you please re-run a test job with the updated easyblock?

**Comment by appolloford** [comment]
Test report by @appolloford
Using easyblocks from PR(s) https://github.com/easybuilders/easybuild-easyblocks/pull/3300
**FAILED**
Build succeeded for 0 out of 1 (1 easyconfigs in total)
vera-skylake-build - Linux Rocky Linux 8.9, x86_64, Intel Xeon Processor (Skylake, IBRS, no TSX), Python 3.6.8
See https://gist.github.com/appolloford/5067d3004d6c5bb0939062e34c4a30e3 for a full test report.

**Comment by appolloford** [comment]
I built on a wrong node where I did not install required system packages: `fontconfig`, `libICE`, `libSM`,  `libxkbcommon-x11`, `xcb-util`, `xcb-util-image`, `xcb-util-keysyms`, `xcb-util-renderutil`, `xcb-util-wm`. I will upload another test on the correct node.

**Comment by appolloford** [comment]
Test report by @appolloford
Using easyblocks from PR(s) https://github.com/easybuilders/easybuild-easyblocks/pull/3300
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
vera40-1 - Linux Rocky Linux 8.9, x86_64, Intel(R) Xeon(R) Gold 6130 CPU @ 2.10GHz, 1 x NVIDIA Tesla T4, 550.54.14, Python 3.6.8
See https://gist.github.com/appolloford/328f8cf797c3d3da9ce57cd5b16636e5 for a full test report.

**Comment by appolloford** [comment]
@smoors Could you also review the easyconfig?

**Comment by smoors** [comment]
Going in, thanks @appolloford!

**Pull request merged**
