### PR TITLE
{data}[gfbf/2023a] polars v0.19.19

### PR DESCRIPTION
**Pull request by lexming**
(created using `eb --new-pr`)

This PR is for v0.19.19 instead of the more recent v0.20.x because the latter need nightly features in Rust that are not yet available in Rust v1.75.

Depends on:
* [x] https://github.com/easybuilders/easybuild-framework/pull/4248
* [x] https://github.com/easybuilders/easybuild-easyblocks/pull/3118
* [x] #19758 
* [x] https://github.com/easybuilders/easybuild-framework/pull/4517

### CODE REVIEW

**Comment by lexming** [comment]
Test report by @lexming
**FAILED**
Build succeeded for 0 out of 1 (1 easyconfigs in total)
node301.hydra.os - Linux Rocky Linux 8.8, x86_64, Intel(R) Xeon(R) Gold 6148 CPU @ 2.40GHz (skylake_avx512), Python 3.6.8
See https://gist.github.com/lexming/473d85488bbc985ed5832b88f4fb1a09 for a full test report.

**Comment by lexming** [comment]
Test report by @lexming
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
node301.hydra.os - Linux Rocky Linux 8.8, x86_64, Intel(R) Xeon(R) Gold 6148 CPU @ 2.40GHz (skylake_avx512), Python 3.6.8
See https://gist.github.com/lexming/0b32ad1d8a6765776ad556c86727af19 for a full test report.

**Comment by lexming** [comment]
@boegelbot: please test @ generoso

**Comment by boegel** [comment]
@lexming failing checksum for `jsonpath_lib-0.3.0.tar.gz`?

**Comment by lexming** [comment]
@boegel Indeed, `jsonpath_lib` has to be pulled from a git repo, so this PR needs a solution to https://github.com/easybuilders/easybuild-framework/pull/4248

**Comment by akesandgren** [comment]
Superseeded by #20275

**Comment by lexming** [comment]
@akesandgren I would still like to get this merged, we are using this version in our clusters

**Comment by lexming** [comment]
@boegelbot: please test @ generoso

**Comment by lexming** [comment]
@boegelbot: please test @ generoso
EB_ARGS="--force-download"

**Comment by lexming** [comment]
the bot cannot use the `5.0.x` branch, so we wait

**Comment by boegel** [comment]
@boegelbot please test @ jsc-zen3
EB_ARGS="--force-download"
EB_BRANCH=5.0.x

**Comment by lexming** [comment]
I cannot reproduce the failures with the checksum of `jsonpath_lib-0.3.0.tar.gz`. I did an installation of polars v0.19.19 on a new system of ours and EB 5.0.x generated a tarball with checksum `f91c11e6f2dd81ddfdde101e4d65e6cebc4cf9a4c18f9e4fbb4400df2fdccabc` as expected.

I'll see if can inspect the tarball in the bot systems.

**Comment by lexming** [comment]
@boegelbot please test @ generoso
EB_ARGS="--force-download"
EB_BRANCH=5.0.x

**Comment by lexming** [comment]
@boegel found the issue with all the failed tests for this PR, fix in https://github.com/easybuilders/easybuild-framework/pull/4517

**Comment by lexming** [comment]
@boegelbot please test @ generoso
EB_ARGS="--force-download"
EB_BRANCH=5.0.x

**Comment by lexming** [comment]
The `5.0.x` used by generoso is outdated. The generated tarball has wrong permissions and timestamps.
@boegel does the bot sync pull the branch from the remote repo, or just checkout?

**Comment by lexming** [comment]
@boegelbot please test @ jsc-zen3

**Comment by lexming** [comment]
@boegelbot please test @ jsc-zen3
EB_ARGS="--force-download"
EB_BRANCH=5.0.x

**Comment by lexming** [comment]
Test report by @lexming
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
node601.hydra.os - Linux Rocky Linux 8.9, x86_64, AMD EPYC 9384X 32-Core Processor (x86_64_v4), Python 3.6.8
See https://gist.github.com/lexming/644fba85b10f1a135530f8ec4f1b1353 for a full test report.

**Comment by lexming** [comment]
@boegel all tests are good with most recent `5.0.x`, this is ready

**Review by jfgrimm — APPROVED** [review]
lgtm

**Pull request merged**
