### PR TITLE
{bio}[GCC/12.3.0] phasius v0.2.0

### PR DESCRIPTION
**Pull request by PetrKralCZ**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by PetrKralCZ** [comment]
@boegelbot please test @ generoso

**Comment by PetrKralCZ** [comment]
@boegelbot please test @ jsc-zen3

**Comment by PetrKralCZ** [comment]
@boegelbot please test @ jsc-zen3

**Comment by smoors** [comment]
@PetrKralCZ a number of checksums appear missing:
>Checksums missing for one or more sources/patches in phasius-0.2.0-GCC-12.3.0.eb: found 353 sources + 0 patches vs 177 checksums

**Comment by boegel** [comment]
> @PetrKralCZ a number of checksums appear missing:
> 
> > Checksums missing for one or more sources/patches in phasius-0.2.0-GCC-12.3.0.eb: found 353 sources + 0 patches vs 177 checksums

No, caused by a bug fixed in 21388

**Review by boegel — APPROVED** [review]
lgtm

**Comment by boegel** [comment]
@boegelbot please test @ generoso

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
node3105.skitty.os - Linux RHEL 8.8, x86_64, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz, Python 3.6.8
See https://gist.github.com/boegel/b6e2f6a071f34f38c7f80a76581d5e07 for a full test report.

**Comment by boegel** [comment]
Going in, thanks @PetrKralCZ!

**Pull request merged**
