### PR TITLE
{chem}[foss/2023a,gfbf/2023a] MDTraj v1.9.9, nglview v3.1.2

### PR DESCRIPTION
**Pull request by lexming**
(created using `eb --new-pr`)

Changelog:
* updated extension list of MDTraj (based on its current requirements)
* move nodejs to a build dep of nglview
* replace dep on JupyterLab to JupyterNotebook of nglview (based in its current requirements)
* add `ase` and `mdtraj` extras to nglview

### CODE REVIEW

**Comment by lexming** [comment]
@boegelbot: please test @ generoso

**Comment by bedroge** [comment]
Test report by @bedroge
**SUCCESS**
Build succeeded for 9 out of 9 (2 easyconfigs in total)
interactive1 - Linux Rocky Linux 8.9, x86_64, AMD EPYC-Milan Processor (zen2), Python 3.6.8
See https://gist.github.com/bedroge/82a0d64f14764e352a0316ab6195ce37 for a full test report.

**Comment by bedroge** [comment]
Test report by @bedroge
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in total)
interactive1 - Linux Rocky Linux 8.9, x86_64, AMD EPYC-Milan Processor (zen2), Python 3.6.8
See https://gist.github.com/bedroge/4c4348b98b2093c164609bf3506c4ca6 for a full test report.

**Comment by bedroge** [comment]
Test report by @bedroge
**FAILED**
Build succeeded for 8 out of 11 (2 easyconfigs in total)
bob-Latitude-5300 - Linux Ubuntu 22.04, x86_64, Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz, Python 3.10.12
See https://gist.github.com/bedroge/10e38de1afc88342483fba4948ba0a79 for a full test report.

**Comment by bedroge** [comment]
Test report by @bedroge
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in total)
bob-Latitude-5300 - Linux Ubuntu 22.04, x86_64, Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz, Python 3.10.12
See https://gist.github.com/bedroge/3c927dbf51a21ddd9bb3ee24d975aad9 for a full test report.

**Review by bedroge — APPROVED** [review]
Lgtm

**Comment by bedroge** [comment]
Going in, thanks @lexming!

**Pull request merged**
