### PR TITLE
{devel}[GCCcore/9.3.0] Bazel v0.29.1

### PR DESCRIPTION
**Pull request by ekieffer**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by ekieffer** [comment]
jdk1.8 is needed for Bazel-0.29.1 (see https://docs.bazel.build/versions/0.29.1/install-compile-source.html)

**Comment by boegel** [comment]
@ekieffer Do you have a specific use case for this old Bazel version? See #11543 for latest Bazel with `GCCcore/9.3.0`.

We should probably add `-Java-1.8` as a versionsuffix here, which will silence the failing tests.

**Comment by boegel** [comment]
@ekieffer Added versionsuffix in https://github.com/ULHPC/easybuild-easyconfigs/pull/3

**Comment by boegel** [comment]
@boegelbot please test @ generoso
CORE_CNT=16

**Review by boegel — APPROVED** [review]
lgtm

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
node2605.swalot.os - Linux centos linux 7.9.2009, x86_64, Intel(R) Xeon(R) CPU E5-2660 v3 @ 2.60GHz (haswell), Python 3.6.8
See https://gist.github.com/f7bb4f5057714c31e039c30f5b9b9d8c for a full test report.

**Comment by boegel** [comment]
Going in, thanks @ekieffer!

**Pull request merged**
