### PR TITLE
{chem,lib,math}[foss/2018a,intel/2018a] yaff v1.4.2, molmod v1.4.4, future v0.16.0

### PR DESCRIPTION
**Pull request by boegel**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by migueldiascosta** [comment]
@boegel hm... I think I didn't merge this at the time because I assumed you'd still submit your own test reports (?)

**Comment by boegel** [comment]
@migueldiascosta There might be a reason for the missing test reports, but I'll look into it...

**Comment by boegel** [comment]
After trying it again, I remember: installing `yaff-1.4.2-intel-2018a-Python-2.7.14.eb` hangs for me while running the tests, haven't figured out why yet (but it's likely it has something to do with `h5py` doing an MPI init, cfr. https://github.com/h5py/h5py/issues/917).

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 6 out of 6 (6 easyconfigs in this PR)
node2421.golett.os - Linux centos linux 7.5.1804, Intel(R) Xeon(R) CPU E5-2680 v3 @ 2.50GHz, Python 2.7.5
See https://gist.github.com/c7d272d189b545c4ce20bcbacf537b1f for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 6 out of 6 (6 easyconfigs in this PR)
node2113.delcatty.os - Linux centos linux 7.5.1804, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.7.5
See https://gist.github.com/7536c84ad354c35f528729ee17c785ab for a full test report.

**Comment by boegel** [comment]
@verdurin Since you merged #7329 which is a more recent version of this, do you mind also taking a look at this one? Unless @migueldiascosta beats you to it... ;)

**Comment by boegel** [comment]
Test report by @boegel
**FAILED**
Build succeeded for 13 out of 14 (6 easyconfigs in this PR)
node3111.skitty.os - Linux centos linux 7.6.1810, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz, Python 2.7.5
See https://gist.github.com/25fea09e130df1935d8cd04faea7cda2 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 6 out of 6 (6 easyconfigs in this PR)
node3111.skitty.os - Linux centos linux 7.6.1810, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz, Python 2.7.5
See https://gist.github.com/5853f7bbce3329f6117fd350967fca70 for a full test report.

**Comment by verdurin** [comment]
Test report by @verdurin
**FAILED**
Build succeeded for 11 out of 20 (6 easyconfigs in this PR)
rescomp2 - Linux centos linux 7.3.1611, Intel(R) Xeon(R) Gold 6126 CPU @ 2.60GHz, Python 2.7.5
See https://gist.github.com/4e0c35063b3da2849081cd246d3b3a9b for a full test report.

**Comment by verdurin** [comment]
@boegel probably some strange local problem:
```
== 2019-01-13 10:39:21,580 modules.py:726 DEBUG Running module command '/mgmt/modules/Modules/3.2.10/bin/modulecmd python load ncurses/6.0-golf-2018a' from /dev/shm/Python/2.7.14/foss-2018a/Python-2.7.14
== 2019-01-13 10:39:21,589 modules.py:732 DEBUG Output of module command '/mgmt/modules/Modules/3.2.10/bin/modulecmd python load ncurses/6.0-golf-2018a': stdout: ; stderr: ncurses/6.0-golf-2018a(25):ERROR:150: Module 'ncurses/6.0-golf-2018a' conflicts with the currently loaded module(s) 'ncurses/6.0-GCCcore-6.4.0'
ncurses/6.0-golf-2018a(25):ERROR:102: Tcl command execution failed: conflict ncurses
```

**Comment by boegel** [comment]
@verdurin There's no `ncurses-6.0-golf-2018a.eb` in the local repository, which may explain why this only pops up for you. Via `libreadline`, the `ncurses` module built with `GCCcore` is already loaded, so that's why things go side-ways.

Why do you have `ncurses/6.0-golf-2018a` installed, where does it come from?

**Comment by verdurin** [comment]
@boegel yes, it's the result of a bodge from last year. Would be best for someone else to take over.

**Comment by boegel** [comment]
Maybe @migueldiascosta can finish up this one?

**Comment by migueldiascosta** [comment]
@boegel so, the MPI hang is specific to Intel MPI under Slurm?

**Comment by boegel** [comment]
@migueldiascosta I only run into MPI hang issues with SLURM when using an interactive job, or I did at some point (we fixed a problem there recently).
The test report from the skitty node was done on a SLURM system, so this PR is good to go imho...

**Comment by migueldiascosta** [comment]
Test report by @migueldiascosta
**SUCCESS**
Build succeeded for 6 out of 6 (6 easyconfigs in this PR)
grc-cluster1 - Linux centos 6.10, Intel(R) Xeon(R) CPU E5-2640 0 @ 2.50GHz, Python 2.7.14
See https://gist.github.com/1f952b6ea0fa58a9a370bc39305e9d5d for a full test report.

**Comment by migueldiascosta** [comment]
Going in, thanks @boegel!

**Pull request merged**
