### PR TITLE
add SSL OS dependencies for GDAL 3.0.0

### PR DESCRIPTION
**Pull request by smoors**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by smoors** [comment]
Test report by @smoors
**SUCCESS**
Build succeeded for 5 out of 5 (4 easyconfigs in this PR)
node374.hydra.os - Linux centos linux 7.7.1908, Intel(R) Xeon(R) Gold 6148 CPU @ 2.40GHz, Python 2.7.5
See https://gist.github.com/a4b8f30bd15f34dd44de574448f0d07a for a full test report.

**Comment by boegel** [comment]
@smoors Is this new for GDAL 3.0.0, or does it also apply to older GDAL versions?

**Comment by smoors** [comment]
@boegel it applies to all versions starting from at least 2.0.2
would you like to have this fix for the other versions too?

**Comment by boegel** [comment]
@smoors Yes, but I would let that block this PR...

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 5 out of 5 (4 easyconfigs in this PR)
generoso-1 - Linux centos linux 7.6.1810, Intel(R) Xeon(R) CPU E5-2660 v4 @ 2.00GHz, Python 3.6.8
See https://gist.github.com/96c6ebf1653e29d5608b57c3b1710a68 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 4 out of 4 (4 easyconfigs in this PR)
node3133.skitty.os - Linux centos linux 7.7.1908, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz, Python 3.6.8
See https://gist.github.com/1de5d4e627b18c59a3adf4fe544be90a for a full test report.

**Comment by migueldiascosta** [comment]
@boegel did you mean you **wouldn't** let that block this PR?

**Comment by boegel** [comment]
@migueldiascosta Exactly (edited my comment).

**Comment by boegel** [comment]
Going in, thanks @smoors!

**Pull request merged**
