### PR TITLE
consistently apply patch for mapDamage 2.2.1 to use external seqtk

### PR DESCRIPTION
**Pull request by boegel**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in total)
node3523.doduo.os - Linux RHEL 8.2, x86_64, AMD EPYC 7552 48-Core Processor (zen2), Python 3.6.8
See https://gist.github.com/8613f246fd7b83edf5b80999995b772f for a full test report.

**Comment by boegel** [comment]
@boegelbot please test @ generoso

**Comment by boegel** [comment]
@boegelbot please test @ jsc-zen2

**Comment by jfgrimm** [comment]
Test report by @jfgrimm
**FAILED**
Build succeeded for 1 out of 3 (2 easyconfigs in total)
node084.pri.viking.alces.network - Linux UNKNOWN UNKNOWN, x86_64, Intel(R) Xeon(R) Gold 6138 CPU @ 2.00GHz (skylake_avx512), Python 3.6.8
See https://gist.github.com/06032dd12e3a5de8726b1faba0868149 for a full test report.

**Comment by jfgrimm** [comment]
@boegel [RcppGSL-0.3.8-foss-2020b-R-4.0.4.eb#L16](https://github.com/easybuilders/easybuild-easyconfigs/blob/develop/easybuild/easyconfigs/r/RcppGSL/RcppGSL-0.3.8-foss-2020b-R-4.0.4.eb#L16) has a typo in the templating

**Comment by boegel** [comment]
> @boegel [RcppGSL-0.3.8-foss-2020b-R-4.0.4.eb#L16](https://github.com/easybuilders/easybuild-easyconfigs/blob/develop/easybuild/easyconfigs/r/RcppGSL/RcppGSL-0.3.8-foss-2020b-R-4.0.4.eb#L16) has a typo in the templating (it uses `$(name)s` instead of `%(name)s`)

Ugh, ok, let's fix that in another PR?

**Comment by jfgrimm** [comment]
yeah I'll open one in a sec

**Comment by jfgrimm** [comment]
Test report by @jfgrimm
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in total)
node084.pri.viking.alces.network - Linux UNKNOWN UNKNOWN, x86_64, Intel(R) Xeon(R) Gold 6138 CPU @ 2.00GHz (skylake_avx512), Python 3.6.8
See https://gist.github.com/742f9aaeea3f23cb2832b4e8309fad27 for a full test report.

**Comment by jfgrimm** [comment]
@boegel I've opened #14962 to address the source url issue

**Comment by jfgrimm** [comment]
Going in, thanks @boegel!

**Pull request merged**
