### PR TITLE
{bio}[foss/2020a] Cogent v8.0.0 -- requires PR #14277, #14276, #14245, #14279

### PR DESCRIPTION
**Pull request by manifestoso**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by robqiao** [comment]
requires PR #14277, #14276, #14245

**Comment by manifestoso** [comment]
@boegelbot please test @ generoso

**Comment by manifestoso** [comment]
@boegelbot please test @ generoso

**Comment by manifestoso** [comment]
@smoors @verdurin proofread this PR?

**Comment by manifestoso** [comment]
deps PR #14526

**Comment by manifestoso** [comment]
@smoors @verdurin proofread this PR?

**Comment by manifestoso** [comment]
Test report by @robqiao
**SUCCESS**
Build succeeded for 3 out of 3 (3 easyconfigs in total)
hpc-head01 - Linux UNKNOWN UNKNOWN, x86_64, Intel(R) Xeon(R) Gold 6130 CPU @ 2.10GHz, Python 3.9.6
See https://gist.github.com/72279f02f54345583ab7be1d048bd07b for a full test report.

**Comment by manifestoso** [comment]
> deps PR #14526

deps PR #14581

**Comment by manifestoso** [comment]
@smoors @lexming proofread this PR?

**Comment by manifestoso** [comment]
> > deps PR #14526
> 
> deps PR ~~#14581~~

**Comment by manifestoso** [comment]
> > > deps PR ~~#14526~~
> > 
> > 
> > deps PR ~#14581~

**Comment by manifestoso** [comment]
Test report by @robqiao
**SUCCESS**
Build succeeded for 3 out of 3 (3 easyconfigs in total)
hpc-head01 - Linux UNKNOWN UNKNOWN, x86_64, Intel(R) Xeon(R) Gold 6130 CPU @ 2.10GHz, Python 3.9.0
See https://gist.github.com/18ce23e1d6bdd38ce550511282b6c9f5 for a full test report.

**Comment by verdurin** [comment]
Test report by @verdurin
**SUCCESS**
Build succeeded for 19 out of 19 (3 easyconfigs in total)
centos7.lan - Linux centos linux 7.9.2009, x86_64, Intel Core Processor (Skylake, IBRS), Python 3.6.8
See https://gist.github.com/3decded44ff3bf2c31c65bc0646a26f7 for a full test report.

**Comment by verdurin** [comment]
@boegelbot please test @ generoso

**Review by verdurin — APPROVED** [review]
Looks fine.

**Comment by verdurin** [comment]
Going in, thanks @manifestoso!

**Pull request merged**
