### PR TITLE
{lib}[foss/2023a] ALL v0.9.2

### PR DESCRIPTION
**Pull request by bedroge**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by bedroge** [comment]
@boegelbot please test @ generoso

**Review by casparvl — APPROVED** [review]
Straightforward update, no surprises. Lgtm!

**Comment by casparvl** [comment]
Test report by @casparvl
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
tcn1.local.snellius.surf.nl - Linux RHEL 8.6, x86_64, AMD EPYC 7H12 64-Core Processor, Python 3.6.8
See https://gist.github.com/casparvl/51b8a52bf92215d4e06b7975e434d01c for a full test report.

**Comment by casparvl** [comment]
Going in, thanks @bedroge!

**Pull request merged**
