### PR TITLE
{lang}[GCCcore/12.3.0] Python v2.7.18

### PR DESCRIPTION
**Pull request by stefan-wolfsheimer**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by casparvl** [comment]
@boegelbot please test @ generoso

**Comment by casparvl** [comment]
Test report by @casparvl
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
tcn1.local.snellius.surf.nl - Linux RHEL 8.6, x86_64, AMD EPYC 7H12 64-Core Processor, Python 3.6.8
See https://gist.github.com/casparvl/5f2cc305a421bca3918990676b9c82da for a full test report.

**Comment by casparvl** [comment]
@boegelbot please test @ jsc-zen2

**Comment by verdurin** [comment]
Test report by @verdurin
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
easybuild-c7.novalocal - Linux CentOS Linux 7.9.2009, x86_64, Intel Xeon Processor (Skylake, IBRS), Python 3.6.8
See https://gist.github.com/verdurin/f39fba82d09f4f6085147ec138ebdb84 for a full test report.

**Review by casparvl — CHANGES_REQUESTED** [review]
@stefan-wolfsheimer : as you may have noticed, we don't do `-bare` and fat builds of Python anymore, but just one that is _almost_ 'bare'. We do have a few key packages that we include there (see the `Python-3.11.3-GCCcore-12.3.0.eb` EasyConfig). Please at the same here.

On a different note: a discussion got triggered amongst the maintainers whether we should keep supporting Python 2.X. My personal view is that this would not be the only EasyConfig for software that isn't actively maintained/supported anymore, and accept PRs for others. But, we'll try to reach some consensus there amongst the maintainers before we merge this. One question that came up is if there was a particular reason for still needing this (e.g. as a dependency for something that has no Python 3 support). Is there?

**Review by boegel — DISMISSED** [review]
missing extensions: `setuptools`, `pip`, `wheel`

**Comment by casparvl** [comment]
@boegelbot please test @ generoso

**Comment by casparvl** [comment]
Test report by @casparvl
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
tcn1.local.snellius.surf.nl - Linux RHEL 8.6, x86_64, AMD EPYC 7H12 64-Core Processor, Python 3.6.8
See https://gist.github.com/casparvl/9869b77a7317cf7d388fcca67e19ae9f for a full test report.

**Comment by casparvl** [comment]
@boegelbot please test @ jsc-zen2

**Review by casparvl — APPROVED** [review]

**Comment by casparvl** [comment]
Going in, thanks @stefan-wolfsheimer!

**Pull request merged**
