### PR TITLE
{devel}[GCCcore/10.3.0] pkgconf v1.8.0

### PR DESCRIPTION
**Pull request by pberthier**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by pberthier** [comment]
Test report by @pberthier
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
softdev8.ibu.internal - Linux Rocky Linux 8.8 (Green Obsidian), x86_64, AMD EPYC 7742 64-Core Processor, Python 3.11.2
See https://gist.github.com/pberthier/11943f8d56f6fbca5bf11acdd32f3fb5 for a full test report.

**Comment by SebastianAchilles** [comment]
@boegelbot please test @ generoso

**Comment by SebastianAchilles** [comment]
@boegelbot please test @ jsc-zen2

**Comment by SebastianAchilles** [comment]
Test report by @sebastianachilles
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
bwd-rockylinux-92 - Linux Rocky Linux 9.2 (Blue Onyx), x86_64, Intel(R) Core(TM) i7-6900K CPU @ 3.20GHz (broadwell), Python 3.9.16
See https://gist.github.com/SebastianAchilles/d04fed6bb56aba4e00a99d99e78454ac for a full test report.

**Review by SebastianAchilles — APPROVED** [review]
lgtm

**Comment by SebastianAchilles** [comment]
Going in, thanks @pberthier!

**Pull request merged**
