### PR TITLE
use original sources for enchant-2

### PR DESCRIPTION
**Pull request by WilleBell**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by WilleBell** [comment]
> @WilleBell i can still download the sources at https://github.com/AbiWord/enchant/archive/refs/tags/v2.6.5.tar.gz
> 
> what's the difference between the original and the fork?

The checksum of that source is different (but very probably ok too, I didn't check). No difference between the original and the fork afaik. Doesn't it make sense to take the source at the original repo then?

**Comment by smoors** [comment]
@boegelbot please test @ jsc-zen3

**Review by smoors — APPROVED** [review]
lgtm

**Comment by smoors** [comment]
Going in, thanks @WilleBell!

**Pull request merged**
