### PR TITLE
{data,tools}[foss/2019b] ITK v5.0.1, SimpleITK v1.2.4 w/ Python 3.7.4

### PR DESCRIPTION
**Pull request by orbsmiv**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by orbsmiv** [comment]
Test report by @orbsmiv
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in this PR)
bear-pg0211u03a.bear.cluster - Linux centos linux 7.7.1908, Intel(R) Xeon(R) Gold 6248 CPU @ 2.50GHz, Python 2.7.5
See https://gist.github.com/d689779b4aea4796aeb77bcf156a1ef1 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**FAILED**
Build succeeded for 1 out of 2 (2 easyconfigs in this PR)
generoso-1 - Linux centos linux 7.6.1810, Intel(R) Xeon(R) CPU E5-2660 v4 @ 2.00GHz, Python 3.6.8
See https://gist.github.com/833a9b3263e99d04fe68c5b689920c91 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in this PR)
node2462.golett.os - Linux centos linux 7.7.1908, Intel(R) Xeon(R) CPU E5-2680 v3 @ 2.50GHz, Python 2.7.5
See https://gist.github.com/10b4031732d481043740f7e82c9fdc37 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in this PR)
node3118.skitty.os - Linux centos linux 7.7.1908, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz, Python 3.6.8
See https://gist.github.com/a0335bc5451cb85fedc573cc08df4ae1 for a full test report.

**Comment by orbsmiv** [comment]
We have Lua 5.1.4 installed at system level. Tried building with Lua 5.3.5 but get the following...
```
-- Found Lua: /rds/bear-apps/devel/2019b/carpenjj-eb-1/EL7/EL7-cascadelake/software/Lua/5.3.5-GCCcore-8.3.0/bin/lua
CMake Error at CMake/sitkGenerateFilterSource.cmake:51 (message):
  Lua version 5.1 is required for SimpleITK_LUA_EXECUTABLE_VERSION.
```

Trying with this version instead: https://github.com/easybuilders/easybuild-easyconfigs/blob/develop/easybuild/easyconfigs/l/Lua/Lua-5.1.4-8.eb

**Comment by boegel** [comment]
Yeah, I think we really need to include `Lua` as a (build?) dep...

For `SimpleITK-1.1.0-foss-2018b-Python-2.7.15.eb` this was done via `Lua-5.1.5-GCCcore-7.3.0.eb`

**Comment by orbsmiv** [comment]
Okay, in which case I'll bump 5.1.5 to GCCcore-8.3.0...

**Comment by boegel** [comment]
Test report by @boegel
**FAILED**
Build succeeded for 1 out of 3 (3 easyconfigs in this PR)
gligar04.gastly.os - Linux centos linux 7.7.1908, Intel(R) Xeon(R) Gold 6130 CPU @ 2.10GHz, Python 2.7.5
See https://gist.github.com/b2971e233adab2dbc044432db749e2e2 for a full test report.

**Comment by orbsmiv** [comment]
Test report by @orbsmiv
**SUCCESS**
Build succeeded for 3 out of 3 (3 easyconfigs in this PR)
bear-pg0211u03a.bear.cluster - Linux centos linux 7.7.1908, Intel(R) Xeon(R) Gold 6248 CPU @ 2.50GHz, Python 2.7.5
See https://gist.github.com/9c6bb54889b57daa2921871353ed449c for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 3 out of 3 (3 easyconfigs in this PR)
node3118.skitty.os - Linux centos linux 7.7.1908, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz, Python 3.6.8
See https://gist.github.com/b345fdbd7bcc838bad5935ab895e15ce for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 3 out of 3 (3 easyconfigs in this PR)
generoso-1 - Linux centos linux 7.6.1810, Intel(R) Xeon(R) CPU E5-2660 v4 @ 2.00GHz, Python 3.6.8
See https://gist.github.com/fafcadba5448c9abc7ec4ccbcb353353 for a full test report.

**Comment by boegel** [comment]
Going in, thanks @orbsmiv!

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 3 out of 3 (3 easyconfigs in this PR)
node2462.golett.os - Linux centos linux 7.7.1908, Intel(R) Xeon(R) CPU E5-2680 v3 @ 2.50GHz, Python 2.7.5
See https://gist.github.com/56a161c2a71f0e364a620bdc111126e8 for a full test report.

**Pull request merged**
