### PR TITLE
{bio}[foss/2021b] SignalP v6.0g w/ Python 3.9.6

### PR DESCRIPTION
**Pull request by boegel**
(created using `eb --new-pr`)
requires:
* #17153

### CODE REVIEW

**Comment by boegel** [comment]
@boegelbot please test @ jsc-zen2

**Comment by boegel** [comment]
Sources are not freely available...

**Comment by verdurin** [comment]
Test report by @verdurin
**SUCCESS**
Build succeeded for 2 out of 2 (1 easyconfigs in total)
easybuild-c7.novalocal - Linux CentOS Linux 7.9.2009, x86_64, Intel Xeon Processor (Skylake, IBRS), Python 3.6.8
See https://gist.github.com/verdurin/f00063c91d433d50a5ae70a95cc58a19 for a full test report.

**Comment by verdurin** [comment]
@boegel note the test failure re. `matplotlib`.

**Review by verdurin — APPROVED** [review]
Looks fine.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
node3101.skitty.os - Linux RHEL 8.6, x86_64, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz (skylake_avx512), Python 3.6.8
See https://gist.github.com/boegel/59a5f3531036595942c6312fc400db12 for a full test report.

**Pull request merged**
