### PR TITLE
{lang,lib,math,vis}[GCCcore/10.2.0] gnuplot v5.4.1, libcerf v1.14, libgd v2.3.0, ...

### PR DESCRIPTION
**Pull request by Mormacill**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by Mormacill** [comment]
Test report by @Mormacill
**SUCCESS**
Build succeeded for 4 out of 4 (4 easyconfigs in total)
node03.mebus - Linux centos linux 7.9.2009, x86_64, Intel(R) Xeon(R) CPU           X5560  @ 2.80GHz, Python 3.6.8
See https://gist.github.com/0b4199a4ed220ef4def05f5678d636b3 for a full test report.

**Comment by verdurin** [comment]
Test report by @verdurin
**SUCCESS**
Build succeeded for 6 out of 6 (4 easyconfigs in total)
nuc.lan - Linux Fedora 32, x86_64, Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz, Python 3.8.7
See https://gist.github.com/39db4fc1ffa8748d0f383de7e895ced6 for a full test report.

**Comment by verdurin** [comment]
@boegelbot please test @ generoso

**Comment by Mormacill** [comment]
Forgot changing to non-ssl according to #12047

**Comment by Mormacill** [comment]
Test report by @Mormacill
**SUCCESS**
Build succeeded for 4 out of 4 (4 easyconfigs in total)
node03.mebus - Linux centos linux 7.9.2009, x86_64, Intel(R) Xeon(R) CPU           X5560  @ 2.80GHz, Python 3.6.8
See https://gist.github.com/338200f5a95fc912e7521bb0907bb248 for a full test report.

**Comment by verdurin** [comment]
Test report by @verdurin
**SUCCESS**
Build succeeded for 4 out of 4 (4 easyconfigs in total)
nuc.lan - Linux Fedora 32, x86_64, Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz, Python 3.8.7
See https://gist.github.com/e0822da675f306c5f21564fbc8015d97 for a full test report.

**Review by verdurin — APPROVED** [review]
Looks fine.

**Comment by verdurin** [comment]
Going in, thanks @Mormacill!

**Pull request merged**
