### PR TITLE
{chem}[foss/2019b] Atomistica v0.10.1, LAMMPS v7Aug2019 w/ Python 3.7.4

### PR DESCRIPTION
**Pull request by lexming**
(created using `eb --new-pr`)
Depend on https://github.com/easybuilders/easybuild-easyblocks/pull/2035 to build  LAMMPS with Atomistica.

This PR contains the following builds of Atomistica:
* `Atomistica-0.10.1-foss-2019b.eb` provides the standalone build that can be used through the experimental `mdcore` executable.
* `Atomistica-0.10.1-foss-2019b-Python-3.7.4.eb` provides the Python interface that integrates with ASE.
* `Atomistica-0.10.1-foss-2019b-LAMMPS.eb` provides libs and files needed to integrate Atomistica into LAMMPS. This build is not usable on its own. LAMMPS has to be built on top of it.

Notes:
* ~~All three easyconfigs of Atomistica are independent from each other.~~
* Only the standalone build supports using an external `dftd3-lib` library.
* ~~I made a new easyconfig for the build of LAMMPS integrating Atomistica with its own `versionsuffix`. However, it only really differs in adding the dependency to Atomistica. We could also consider updating the regular easyconfig of LAMMPS instead.~~

**Update**: all three easyconfigs are now bundled into a single one providing the same features.

**Update 2**: The CMake build of LAMMPS needs patching to detect and properly link with Atomistica. I'm adding that patch for LAMMPS v7Aug2019. I made the easyconfig of LAMMPS including Atomistica with its own `versionsuffix` to keep it separate from the *standard* LAMMPS. Nonetheless, the patch checks for Atomistica being in the list of `user_packages`, so if Atomistica is removed from it, the build of LAMMPS will become the *standard* one.

### CODE REVIEW

**Comment by lexming** [comment]
Test report by @lexming
**SUCCESS**
Build succeeded for 4 out of 4 (4 easyconfigs in this PR)
node121.hydra.os - Linux centos linux 7.7.1908, Intel(R) Xeon(R) CPU E5-2680 v2 @ 2.80GHz, Python 2.7.5
See https://gist.github.com/c6a262489b7605d8ab1ce042bbf1f0db for a full test report.

**Comment by ocaisa** [comment]
@lexming I was starting to look at #2035 and I was wondering if it wouldn't be better to bundle these 3 different builds together? From a naive look at the sanity checks they wouldn't seem to step on each others toes.

**Comment by ocaisa** [comment]
Something like https://github.com/easybuilders/easybuild-easyconfigs/blob/develop/easybuild/easyconfigs/s/SpliceMap/SpliceMap-3.3.5.2-GCC-7.3.0-2.30.eb

**Comment by lexming** [comment]
@ocaisa that's indeed a good point... but it's also quite some work... :slightly_smiling_face:  I'll try to combine them in a single Bundle 
(btw I contributed that easyconfig for SpliceMap, a piece of art :heart: )

**Comment by ocaisa** [comment]
@lexming Thanks for doing this, having a non-functional version just so you could build LAMMPS support was off-putting for me, this approach is way cleaner IMHO

**Comment by lexming** [comment]
@ocaisa I also like it more now.  I tested it and there aren't any downsides compared to having three different easyconfigs. Test reports will be incoming...

**Comment by lexming** [comment]
Test report by @lexming
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in this PR)
node363.hydra.os - Linux centos linux 7.7.1908, x86_64, Intel(R) Xeon(R) Gold 6148 CPU @ 2.40GHz, Python 2.7.5
See https://gist.github.com/589a70fafcbd25d0d318f94952594839 for a full test report.

**Comment by lexming** [comment]
Test report by @lexming
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in this PR)
node153.hydra.os - Linux centos linux 7.7.1908, x86_64, Intel(R) Xeon(R) CPU E5-2680 v2 @ 2.80GHz, Python 2.7.5
See https://gist.github.com/739021bdd2f5e35ba83ff5298abd2a0f for a full test report.

**Comment by lexming** [comment]
Previous build is with https://github.com/easybuilders/easybuild-easyblocks/pull/2035 (commit https://github.com/easybuilders/easybuild-easyblocks/pull/2035/commits/d3933d114f1cee315d0d730cec5745ffefb42c37)

**Comment by lexming** [comment]
Added cURL to the easyconfig of LAMMPS following https://github.com/easybuilders/easybuild-easyconfigs/pull/10527

**Comment by lexming** [comment]
Test report by @lexming
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in this PR)
node154.hydra.os - Linux centos linux 7.7.1908, x86_64, Intel(R) Xeon(R) CPU E5-2680 v2 @ 2.80GHz, Python 2.7.5
See https://gist.github.com/9c3471b80a8301a68159cb2c3f11b342 for a full test report.

**Comment by ocaisa** [comment]
There's a problem with downloading the sources here, if the source doesn't exist it will first attempt to download from `Atomistica-ASE` which will fail:
```
Trying to download file 0.10.1.tar.gz from https://github.com/Atomistica/Atomistica-ASE/archive/0.10.1.tar.gz to /work/main
tainers/sources/a/Atomistica/0.10.1.tar.gz
```
reversing the component order would fix this but probably a good idea to comment that this ordering is essential.

**Comment by ocaisa** [comment]
Test report by @ocaisa
**FAILED**
Build succeeded for 0 out of 2 (2 easyconfigs in this PR)
generoso - Linux centos linux 7.6.1810, x86_64, Intel(R) Xeon(R) CPU E5-2660 v4 @ 2.00GHz, Python 3.6.8
See https://gist.github.com/364f94f099c921e979741aef1f3d36c8 for a full test report.

**Comment by ocaisa** [comment]
@lexming I reordered the components to sidestep my problem (since I know you are probably busy with something a little more important). I thought it would be a quick and easy fix but I'm still getting an error when building `Atomistica` (well two, but only I is fatal):
```
gfortran -DNO_BIND_C_OPTIONAL -g -O3 -funroll-loops -fbacktrace   -DHAVE_DFTD3  -I -ffree-form -ffree-line-length-none -x f95-cpp-input -I. -I../src -I../src/support -I../src/potentials -c ../src/potentials/dispersion/dispdftd3.f90 -o dispdftd3.o
f951: Warning: Nonexistent include directory -ffree-form [-Wmissing-include-dirs]
../src/potentials/dispersion/dispdftd3.f90:52:6:

   use dftd3_api
      1
Fatal Error: Can't open module file dftd3_api.mod for reading at (1): No such file or directory
compilation terminated.
make: *** [dispdftd3.o] Error 1
```
It looks like a problem with how DFTD3 is included in the patch (which shouldn't even be necessary since the fortran module is available in `CPATH`).

The non-fatal error is
```
which: no nf-config in (/work/maintainers/CO7/broadwell/software/dftd3-lib/0.9-GCC-8.3.0/bin:/work/maintainers/CO7/broadwell/software/ASE/3.19 (took 1 min 40 sec)
```

**Comment by Flamefire** [comment]
@ocaiso: There is a bug with the includes. `-DHAVE_DFTD3  -I -ffree-form`

This looks like a shell expansion of a variable that turned out to be empty but isn't supposed to. Any idea which one that is?

**Comment by ocaisa** [comment]
@Flamefire I think it is inside the patch at https://github.com/easybuilders/easybuild-easyconfigs/pull/10433/files#diff-77be4875f9c1d2e0c35cd0816b74a3caR209 but I don't know why that is coming in blank

**Comment by jakub-xen** [comment]
@Flamefire In case you haven't been able to compile this yet. I ended up making this change:
```
        #'prebuildopts': "cp Makefile.gnu Makefile &&", 
        'prebuildopts': "sed \"s/^DFTD3_PATH =.*/DFTD3_PATH = \$(EBROOTDFTD3MINLIB)\/include/\" Makefile.gnu | sed \"s/-llapack -lblas/-lopenblas/\" > Makefile &&",
```
the copy of Makefile.gnu causes the DFTD3_PATH to not be set. I also have an issue with openblas.

**Review by jfgrimm — COMMENTED** [review]
As decided in issue #16330, we have deprecated the use of `True` to signify a system-toolchain dependency (#16384), in favour of the more intuitive `SYSTEM` template constant. Due to the change in the test suite, please run `eb --sync-pr-with-develop ${pr}` and update the PR to use `SYSTEM` instead.

**Comment by lexming** [comment]
Abandoned. These easyconfigs will stay available at https://github.com/lexming/easybuild-easyconfigs/tree/vub-hpc/easybuild/easyconfigs/a/Atomistica

**Pull request closed without merging**
