### PR TITLE
correct the python building of DGL, requires static libs

### PR DESCRIPTION
**Pull request by akesandgren**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by akesandgren** [comment]
@boegelbot Please test @ generoso

**Review by Micket — APPROVED** [review]
lgtm

**Comment by Micket** [comment]
Test report by @Micket
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
alvis1-07 - Linux Rocky Linux 8.6, x86_64, Intel(R) Xeon(R) Gold 6244 CPU @ 3.60GHz, 1 x NVIDIA Tesla V100-SXM2-32GB, 520.61.05, Python 3.6.8
See https://gist.github.com/Micket/737527eaf72711137b4b3865e1a06b2c for a full test report.

**Comment by Micket** [comment]
Test report by @Micket
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
alvis9-03 - Linux Rocky Linux 8.6, x86_64, Intel(R) Xeon(R) Gold 6338 CPU @ 2.00GHz, 4 x NVIDIA NVIDIA A40, 520.61.05, Python 3.6.8
See https://gist.github.com/Micket/064d1eb5389a096cc4e1c4a5b9933230 for a full test report.

**Comment by Micket** [comment]
Generoso doesn't have a GPU so i'm going to ignore that last failure to build DGL

**Comment by Micket** [comment]
Going in, thanks @akesandgren!

**Pull request merged**
