### PR TITLE
{bio}[foss/2018b] fumi_tools v0.18.2 w/ Python 3.6.6

### PR DESCRIPTION
**Pull request by SethosII**
(created using `eb --new-pr`)

As of https://ccb-gitlab.cs.uni-saarland.de/tobias/fumi_tools/-/blob/master/CMakeLists.txt#L73-77 there are additional dependencies, which aren't included in the EasyConfig and bundled with the source code.

### CODE REVIEW

**Comment by SethosII** [comment]
Test report by @SethosII
**SUCCESS**
Build succeeded for 2 out of 2 (1 easyconfigs in total)
ribnode015 - Linux ubuntu 18.04, x86_64, Intel(R) Xeon(R) CPU           E5645  @ 2.40GHz, Python 2.7.17
See https://gist.github.com/2bb0a8d87db9950ebe00b27a0459eb4d for a full test report.

**Comment by verdurin** [comment]
@boegelbot please test @ generoso

**Comment by verdurin** [comment]
Test report by @verdurin
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
easybuild-c7.novalocal - Linux centos linux 7.9.2009, x86_64, Intel Xeon Processor (Skylake, IBRS), Python 3.6.8
See https://gist.github.com/c67d8ccca5dee97a799e704f56caac02 for a full test report.

**Review by verdurin — APPROVED** [review]
Looks fine.

**Comment by verdurin** [comment]
Going in, thanks @SethosII!

**Pull request merged**
