### PR TITLE
{tools}[GCCcore/12.3.0] pdsh v2.34

### PR DESCRIPTION
**Pull request by laraPPr**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by laraPPr** [comment]
Test report by @laraPPr
**FAILED**
Build succeeded for 0 out of 1 (1 easyconfigs in total)
node3558.doduo.os - Linux RHEL 8.6 (Ootpa), x86_64, AMD EPYC 7552 48-Core Processor (zen2), Python 3.10.8
See https://gist.github.com/laraPPr/7f1e06d0d086f47e9f9af2fbdff5ddc7 for a full test report.

**Comment by laraPPr** [comment]
Failed due to conflict with the keyring that I use

**Review by boegel — APPROVED** [review]
lgtm

**Comment by boegel** [comment]
@boegelbot please test @ jsc-zen2

**Comment by boegel** [comment]
Going in, thanks @laraPPr!

**Pull request merged**
