### PR TITLE
{devel}[intel/2017a] Tensorflow v1.3.0, protobuf-python v3.4.0, protobuf v3.4.0

### PR DESCRIPTION
**Pull request by boegel**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 3 out of 3 (3 easyconfigs in this PR)
node2700.swalot.os - Linux centos linux 7.3.1611, Intel(R) Xeon(R) CPU E5-2660 v3 @ 2.60GHz, Python 2.7.5
See https://gist.github.com/407a7483643009ab95d88c2ff8425156 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 3 out of 3 (3 easyconfigs in this PR)
node2011.delcatty.os - Linux centos linux 7.3.1611, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.7.5
See https://gist.github.com/eb853596787c5a865b1fb84126df2c7f for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 5 out of 5 (5 easyconfigs in this PR)
node2011.delcatty.os - Linux centos linux 7.3.1611, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.7.5
See https://gist.github.com/308140a6b159b1ebc683b741c5a16149 for a full test report.

**Comment by verdurin** [comment]
Test report by @verdurin
**FAILED**
Build succeeded for 4 out of 5 (5 easyconfigs in this PR)
ca022.camp.thecrick.org - Linux centos linux 7.3.1611, Intel(R) Xeon(R) CPU E5-2640 v3 @ 2.60GHz, Python 2.7.5
See https://gist.github.com/b9d0d4aed18650de28190c7bf7f81b1d for a full test report.

**Comment by verdurin** [comment]
@boegel I think we've seen an error like this before, with SSL hash algorithms?:
```
ERROR:root:code for hash sha3_224 was not found.
Traceback (most recent call last):
  File "/camp/apps/eb/review/software/Python/3.6.1-intel-2017a/lib/python3.6/hashlib.py", line 121, in __get_openssl_constructor
    f = getattr(_hashlib, 'openssl_' + name)
AttributeError: module '_hashlib' has no attribute 'openssl_sha3_224'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/camp/apps/eb/review/software/Python/3.6.1-intel-2017a/lib/python3.6/hashlib.py", line 243, in <module>
    globals()[__func_name] = __get_hash(__func_name)
  File "/camp/apps/eb/review/software/Python/3.6.1-intel-2017a/lib/python3.6/hashlib.py", line 128, in __get_openssl_constructor
    return __get_builtin_constructor(name)
  File "/camp/apps/eb/review/software/Python/3.6.1-intel-2017a/lib/python3.6/hashlib.py", line 113, in __get_builtin_constructor
    raise ValueError('unsupported hash type ' + name)
ValueError: unsupported hash type sha3_224
ERROR:root:code for hash sha3_256 was not found.
Traceback (most recent call last):
  File "/camp/apps/eb/review/software/Python/3.6.1-intel-2017a/lib/python3.6/hashlib.py", line 121, in __get_openssl_constructor
    f = getattr(_hashlib, 'openssl_' + name)
AttributeError: module '_hashlib' has no attribute 'openssl_sha3_256'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/camp/apps/eb/review/software/Python/3.6.1-intel-2017a/lib/python3.6/hashlib.py", line 243, in <module>
    globals()[__func_name] = __get_hash(__func_name)
  File "/camp/apps/eb/review/software/Python/3.6.1-intel-2017a/lib/python3.6/hashlib.py", line 128, in __get_openssl_constructor
    return __get_builtin_constructor(name)
  File "/camp/apps/eb/review/software/Python/3.6.1-intel-2017a/lib/python3.6/hashlib.py", line 113, in __get_builtin_constructor
    raise ValueError('unsupported hash type ' + name)
ValueError: unsupported hash type sha3_256
ERROR:root:code for hash sha3_384 was not found.
Traceback (most recent call last):
  File "/camp/apps/eb/review/software/Python/3.6.1-intel-2017a/lib/python3.6/hashlib.py", line 121, in __get_openssl_constructor
    f = getattr(_hashlib, 'openssl_' + name)
AttributeError: module '_hashlib' has no attribute 'openssl_sha3_384'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/camp/apps/eb/review/software/Python/3.6.1-intel-2017a/lib/python3.6/hashlib.py", line 243, in <module>
    globals()[__func_name] = __get_hash(__func_name)
  File "/camp/apps/eb/review/software/Python/3.6.1-intel-2017a/lib/python3.6/hashlib.py", line 128, in __get_openssl_constructor
    return __get_builtin_constructor(name)
  File "/camp/apps/eb/review/software/Python/3.6.1-intel-2017a/lib/python3.6/hashlib.py", line 113, in __get_builtin_constructor
    raise ValueError('unsupported hash type ' + name)
ValueError: unsupported hash type sha3_384
ERROR:root:code for hash sha3_512 was not found.
Traceback (most recent call last):
  File "/camp/apps/eb/review/software/Python/3.6.1-intel-2017a/lib/python3.6/hashlib.py", line 121, in __get_openssl_constructor
    f = getattr(_hashlib, 'openssl_' + name)
AttributeError: module '_hashlib' has no attribute 'openssl_sha3_512'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/camp/apps/eb/review/software/Python/3.6.1-intel-2017a/lib/python3.6/hashlib.py", line 243, in <module>
    globals()[__func_name] = __get_hash(__func_name)
  File "/camp/apps/eb/review/software/Python/3.6.1-intel-2017a/lib/python3.6/hashlib.py", line 128, in __get_openssl_constructor
    return __get_builtin_constructor(name)
  File "/camp/apps/eb/review/software/Python/3.6.1-intel-2017a/lib/python3.6/hashlib.py", line 113, in __get_builtin_constructor
    raise ValueError('unsupported hash type ' + name)
ValueError: unsupported hash type sha3_512
ERROR:root:code for hash shake_128 was not found.
Traceback (most recent call last):
  File "/camp/apps/eb/review/software/Python/3.6.1-intel-2017a/lib/python3.6/hashlib.py", line 121, in __get_openssl_constructor
    f = getattr(_hashlib, 'openssl_' + name)
AttributeError: module '_hashlib' has no attribute 'openssl_shake_128'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/camp/apps/eb/review/software/Python/3.6.1-intel-2017a/lib/python3.6/hashlib.py", line 243, in <module>
    globals()[__func_name] = __get_hash(__func_name)
  File "/camp/apps/eb/review/software/Python/3.6.1-intel-2017a/lib/python3.6/hashlib.py", line 128, in __get_openssl_constructor
    return __get_builtin_constructor(name)
  File "/camp/apps/eb/review/software/Python/3.6.1-intel-2017a/lib/python3.6/hashlib.py", line 113, in __get_builtin_constructor
    raise ValueError('unsupported hash type ' + name)
ValueError: unsupported hash type shake_128
ERROR:root:code for hash shake_256 was not found.
Traceback (most recent call last):
  File "/camp/apps/eb/review/software/Python/3.6.1-intel-2017a/lib/python3.6/hashlib.py", line 121, in __get_openssl_constructor
    f = getattr(_hashlib, 'openssl_' + name)
AttributeError: module '_hashlib' has no attribute 'openssl_shake_256'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/camp/apps/eb/review/software/Python/3.6.1-intel-2017a/lib/python3.6/hashlib.py", line 243, in <module>
    globals()[__func_name] = __get_hash(__func_name)
  File "/camp/apps/eb/review/software/Python/3.6.1-intel-2017a/lib/python3.6/hashlib.py", line 128, in __get_openssl_constructor
    return __get_builtin_constructor(name)
  File "/camp/apps/eb/review/software/Python/3.6.1-intel-2017a/lib/python3.6/hashlib.py", line 113, in __get_builtin_constructor
    raise ValueError('unsupported hash type ' + name)
ValueError: unsupported hash type shake_256
pip 9.0.1 from /camp/apps/eb/review/software/Python/3.6.1-intel-2017a/lib/python3.6/site-packages (python 3.6)

== 2017-09-18 17:57:01,863 run.py:508 DEBUG Using default regular expression: (?<![(,-]|\w)(?:error|segmentation fault|failed)(?![(,-]|\.?\w)
== 2017-09-18 17:57:01,863 run.py:525 INFO parse_log_for_error msg: Command used: pip --version
== 2017-09-18 17:57:01,864 run.py:527 INFO parse_log_for_error (some may be harmless) regExp (?<![(,-]|\w)(?:error|segmentation fault|failed)(?![(,-]|\.?\w) found:
ERROR:root:code for hash sha3_224 was not found.
ERROR:root:code for hash sha3_256 was not found.
ERROR:root:code for hash sha3_384 was not found.
ERROR:root:code for hash sha3_512 was not found.
ERROR:root:code for hash shake_128 was not found.
ERROR:root:code for hash shake_256 was not found.
== 2017-09-18 17:57:01,864 run.py:484 WARNING Found 6 errors in command output (output: ERROR:root:code for hash sha3_224 was not found., ERROR:root:code for hash sha3_256 was not found., ERROR:root:code for hash sha3_384 was not found., ERROR:root:code for hash sha3_512 was not found., ERROR:root:code for hash shake_128 was not found., ERROR:root:code for hash shake_256 was not found.)
```

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 6 out of 6 (5 easyconfigs in this PR)
node2700.swalot.os - Linux centos linux 7.3.1611, Intel(R) Xeon(R) CPU E5-2660 v3 @ 2.60GHz, Python 2.7.5
See https://gist.github.com/e4fed9c78280d6299c9abab15689a365 for a full test report.

**Comment by wpoely86** [comment]
Test report by @wpoely86
**SUCCESS**
Build succeeded for 5 out of 5 (5 easyconfigs in this PR)
nic68 - Linux centos linux 7.3.1611, Intel(R) Xeon(R) CPU E5-2680 v4 @ 2.40GHz, Python 2.7.5
See https://gist.github.com/d223d01b41cf509a45dabe0a1ed68da3 for a full test report.

**Comment by wpoely86** [comment]
Test report by @wpoely86
**SUCCESS**
Build succeeded for 5 out of 5 (5 easyconfigs in this PR)
nic68 - Linux centos linux 7.3.1611, Intel(R) Xeon(R) CPU E5-2680 v4 @ 2.40GHz, Python 2.7.5
See https://gist.github.com/e919b03aafc5b458021ea0463b78a9ec for a full test report.

**Pull request merged**
