### PR TITLE
{cae}[system/system] FLUENT v2021R1

### PR DESCRIPTION
**Pull request by boegel**
(created using `eb --new-pr`)
requires https://github.com/easybuilders/easybuild-easyblocks/pull/2334

### CODE REVIEW

**Comment by boegel** [comment]
Test report by @boegel
Using easyblocks from PR(s) https://github.com/easybuilders/easybuild-easyblocks/pull/2334
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
node3100.skitty.os - Linux centos linux 7.9.2009, x86_64, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz, Python 3.6.8
See https://gist.github.com/f68f1dd167b6519c8a06e87efa09b3b0 for a full test report.

**Review by Micket — APPROVED** [review]
lgtm

**Comment by Micket** [comment]
I'll have to trust your build as I don't have the software

**Comment by Micket** [comment]
Going in, thanks @boegel!

**Pull request merged**
