### PR TITLE
{math}[foss/2016b] sympy v1.0

### PR DESCRIPTION
**Pull request by verdurin**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by boegel** [comment]
@verdurin 

```
ERROR: Irresolvable dependencies encountered: mpmath/0.19-foss-2016b-Python-2.7.12
```

**Comment by boegel** [comment]
Test report by @boegel
**FAILED**
Build succeeded for 1 out of 2 (2 easyconfigs in this PR)
node2453.golett.os - Linux centos linux 7.2.1511, Intel(R) Xeon(R) CPU E5-2680 v3 @ 2.50GHz, Python 2.7.5
See https://gist.github.com/7273c83ee8bce8a936a4b76987a0dd66 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in this PR)
node2140.delcatty.os - Linux SL 6.8, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.6.6
See https://gist.github.com/67b8d49185681940025c055e6ae22c5b for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**FAILED**
Build succeeded for 1 out of 2 (2 easyconfigs in this PR)
node2693.swalot.os - Linux centos linux 7.3.1611, Intel(R) Xeon(R) CPU E5-2660 v3 @ 2.60GHz, Python 2.7.5
See https://gist.github.com/e0782b54349cfd639511df4ea1a73a43 for a full test report.

**Comment by boegel** [comment]
@verdurin sympy tests fail on CentOS7.3/Haswell...

Maybe compiling with higher precision could fix this issue?

**Comment by boegel** [comment]
@verdurin Ping, any idea on failing tests?

**Comment by migueldiascosta** [comment]
@verdurin, this PR is being closed for the following reason(s): obsoleted by more recent PRs.
Please don't hesitate to reopen this PR or add a comment if you feel it is still relevant.
For more information on our policy w.r.t. closing PRs, see https://easybuild.readthedocs.io/en/latest/Contributing.html#why-a-pull-request-may-be-closed-by-a-maintainer

**Pull request closed without merging**
