### PR TITLE
{lib}[intel/2019a] pyFFTW v0.11.1 w/ Python 3.7.2 + 2.7.15

### PR DESCRIPTION
**Pull request by boegel**
(created using `eb --new-pr`)

requires ~#8194~ (FFTW)

### CODE REVIEW

**Comment by vanzod** [comment]
Triggering Travis after merging #8194

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
node3119.skitty.os - Linux centos linux 7.6.1810, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz, Python 2.7.5
See https://gist.github.com/5996933d8879d9ee12b4ee0d5e67261d for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
node2506.golett.os - Linux centos linux 7.6.1810, Intel(R) Xeon(R) CPU E5-2680 v3 @ 2.50GHz, Python 2.7.5
See https://gist.github.com/c51ae907980736f0fe5772466674fa6c for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
node2066.delcatty.os - Linux centos linux 7.6.1810, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.7.5
See https://gist.github.com/698ef76e01b1431aec93d0edc328c109 for a full test report.

**Comment by vanzod** [comment]
Test report by @vanzod
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
cermis - Linux debian 9.9, Intel(R) Xeon(R) CPU           X5670  @ 2.93GHz, Python 2.7.13
See https://gist.github.com/804c7f3d06c70b0e75a920e9f86a9e7b for a full test report.

**Comment by vanzod** [comment]
Going in, thanks @boegel!

**Pull request merged**
