### PR TITLE
update version, add ABSL replace PR #17862

### PR DESCRIPTION
**Pull request by fizwit**
(created using `eb --new-pr`)

### CODE REVIEW

**Review by Micket — CHANGES_REQUESTED** [review]
looks like protobuf 23.0 was finally released yesterday actually. includes a fix rendering the patch needless as well, so i think it would be good to grab that one instead.

**Comment by fizwit** [comment]
Ok, working on 23.0 now, but running into some CMake issues

**Comment by fizwit** [comment]
@Micket updated to version 23.0

**Comment by jfgrimm** [comment]
@boegelbot please test @ generoso

**Comment by jfgrimm** [comment]
@boegelbot please test @ jsc-zen2

**Comment by jfgrimm** [comment]
Test report by @jfgrimm
**SUCCESS**
Build succeeded for 3 out of 3 (2 easyconfigs in total)
node068.pri.viking.alces.network - Linux CentOS Linux 7.9.2009, x86_64, Intel(R) Xeon(R) Gold 6138 CPU @ 2.00GHz (skylake_avx512), Python 3.6.8
See https://gist.github.com/jfgrimm/b8f75bbdb2e7b6e51bed002bb9530a04 for a full test report.

**Review by jfgrimm — APPROVED** [review]
lgtm

**Pull request merged**
