### PR TITLE
{bio}[foss/2017a] FVCOM v3.2

### PR DESCRIPTION
**Pull request by dplacencia**
Support for FVCOM

### CODE REVIEW

**Comment by boegel** [comment]
I've registered to get access to the sources, to try and test this...

**Comment by lexming** [comment]
@boegel I also requested access and I got a user account on their website, but login to their gitlab never worked

**Comment by boegel** [comment]
OK, I think I'll go ahead and close this one, since:

* Sources are not freely available, and getting a hold of them is proving to be problematic
* Very old toolchain
* Easyconfig needs work
* No test reports yet

My apologies for not picking up on this sooner @dplacencia, I hope this doesn't discourage you from making more contributions...

**Comment by jfgrimm** [comment]
as reported on slack, looks like the sources are available on github now: https://github.com/FVCOM-GitHub/FVCOM

**Pull request closed without merging**
