### PR TITLE
seed in PCRE2 sources to fix broken MariaDB 10.5.8 + 10.6.4 easyconfigs

### PR DESCRIPTION
**Pull request by boegel**
(created using `eb --new-pr`)

fix for:

```
CMake Error at pcre2-stamp/download-pcre2.cmake:159 (message):
  Each download failed!

    error: downloading 'http://ftp.pcre.org/pub/pcre/pcre2-10.34.zip' failed
         status_code: 28
         status_string: "Timeout was reached"
```

### CODE REVIEW

**Comment by boegel** [comment]
@boegelbot please test @ generoso
CORE_CNT=16

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in total)
node3105.skitty.os - Linux centos linux 7.9.2009, x86_64, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz (skylake_avx512), Python 3.6.8
See https://gist.github.com/1b0a1f5be9ce6024212d250dafe524c6 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in total)
node3508.doduo.os - Linux RHEL 8.2, x86_64, AMD EPYC 7552 48-Core Processor (zen2), Python 3.6.8
See https://gist.github.com/30d3b6b2b2cd4b691f2f27a268b05af8 for a full test report.

**Review by Micket — APPROVED** [review]
lgtm

**Pull request merged**
