### PR TITLE
{astro}[foss/2022a] emcee v3.1.4

### PR DESCRIPTION
**Pull request by jose-d**
(created using `eb --new-pr`)

..toolchain bump for https://pypi.org/project/emcee/ / https://github.com/easybuilders/easybuild-easyconfigs/tree/develop/easybuild/easyconfigs/e/emcee

### CODE REVIEW

**Comment by jose-d** [comment]
Test report by @jose-d
**FAILED**
Build succeeded for 0 out of 1 (1 easyconfigs in total)
cvmfs1.koios.lan - Linux Rocky Linux 8.8 (Green Obsidian), x86_64, Intel(R) Xeon(R) Gold 6130 CPU @ 2.10GHz, Python 3.11.2
See https://gist.github.com/jose-d/b5dde75513af3995a6e8ea1e9f101dd0 for a full test report.

**Comment by migueldiascosta** [comment]
@jose-d it's common practice to leave the explicit Python dependency, even though it's implicitly there via `SciPy-bundle`, if nothing else because the explicit dependency allows the use of the python version templates (e.g. `%(pyshortver)s` instead of `3.10` in the sanity check dirs)

**Comment by jose-d** [comment]
Test report by @jose-d
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
cvmfs1.koios.lan - Linux Rocky Linux 8.8 (Green Obsidian), x86_64, Intel(R) Xeon(R) Gold 6130 CPU @ 2.10GHz, Python 3.11.2
See https://gist.github.com/jose-d/7a891528e2b062070ec55be44e7ebc11 for a full test report.

**Comment by jose-d** [comment]
> explicit dependency allows the use of the python version templates (e.g. %(pyshortver)s

@migueldiascosta oh, thanks!

This explains why the template wasn't working for me. 

I added the dependency now, and changed back the hard-coded python version string to - now working - `%(pyshortver)s`.

**Comment by migueldiascosta** [comment]
@boegelbot please test @ generoso

**Comment by migueldiascosta** [comment]
@boegelbot please test @ jsc-zen2

**Review by migueldiascosta — APPROVED** [review]
lgtm (ignoring the "astro" moduleclass since that what's being used for the existing easyconfigs and would likely be more confusing to change it now...)

**Comment by migueldiascosta** [comment]
Going in, thanks @jose-d!

**Pull request merged**
