### PR TITLE
{bio}[foss/2019a] R-bundle-Bioconductor v3.9: Add ATACseqQC, motifStack, ChIPpeakAnno,  Mmusculus.UCSC.mm10, GenomicScores and dependencies

### PR DESCRIPTION
**Pull request by lexming**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by lexming** [comment]
This PR also updates the URL to bioconductor.org and takes the description of the package from there.

**Comment by lexming** [comment]
Test report by @lexming
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
login2.cerberus.os - Linux centos linux 7.6.1810, Intel(R) Xeon(R) Gold 6126 CPU @ 2.60GHz, Python 2.7.5
See https://gist.github.com/f7d3e548916366b527c164f4c2ba5ce1 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
node3138.skitty.os - Linux centos linux 7.6.1810, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz, Python 3.6.8
See https://gist.github.com/28fa47fee7179e1e32545416672c8239 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
generoso - Linux centos linux 7.6.1810, Intel(R) Xeon(R) CPU E5-2660 v4 @ 2.00GHz, Python 3.6.8
See https://gist.github.com/9b8e7f8e1da9c5a3f3e440e662a6d13e for a full test report.

**Comment by boegel** [comment]
Going in, thanks @lexming!

**Pull request merged**
