### PR TITLE
Fix geotiff configure option in GDAL 2.2.3

### PR DESCRIPTION
**Pull request by Flamefire**
(created using `eb --new-pr`)

same as #19999

### CODE REVIEW

**Comment by verdurin** [comment]
Test report by @verdurin
**FAILED**
Build succeeded for 5 out of 21 (4 easyconfigs in total)
easybuild-c7.novalocal - Linux CentOS Linux 7.9.2009, x86_64, Intel Xeon Processor (Skylake, IBRS), Python 3.6.8
See https://gist.github.com/verdurin/7d9d5e28a342765926b48e50571d9b3a for a full test report.

**Comment by verdurin** [comment]
I think that's as many as I can build locally.

**Comment by verdurin** [comment]
@boegelbot please test @ generoso

**Comment by Flamefire** [comment]
The toolchain is to old I guess. But this is for https://github.com/easybuilders/easybuild-easyblocks/pull/3025 and the same change was done in #19999 and some of the GDAL ECs from this PR succeeded in the above reports, so the others should be fine without the need for further tests given the source is the same.

**Review by boegel — APPROVED** [review]

**Comment by boegel** [comment]
Toolchains are no longer supported, so I won't go through the trouble of trying to upload test reports, especially since the changes are identical to #19999

**Pull request merged**
