### PR TITLE
{lang}[foss/2020a] R v4.0.4

### PR DESCRIPTION
**Pull request by robert-mijakovic**
Hi guys,

this pull request consists of R 4.0.4.

Best regards,
Robert

### CODE REVIEW

**Comment by verdurin** [comment]
Test report by @verdurin
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
nuc.lan - Linux Fedora 32, x86_64, Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz, Python 3.8.7
See https://gist.github.com/0cf79233ea52f7e212a4aca357b245a8 for a full test report.

**Comment by verdurin** [comment]
@robert-mijakovic thanks for working on one of the most troublesome `easyconfigs`. Output from `review-pr` suggests that the `linkcomm` extension has been removed, perhaps inadvertently. 

Could you check, please?

**Comment by robert-mijakovic** [comment]
@verdurin You are welcome. I don't see the extension in any of the EasyBuild's provided easyconfigs for R.
```
/var/lib/localadmin/install/EasyBuild/software/EasyBuild/4.3.3/easybuild/easyconfigs/r/R
[localadmin@login03 R]$ grep -rn "linkcomm" *
[localadmin@login03 R]$ 
```
If you prefer to have it in 4.0.4, I can put it in there.

**Comment by branfosj** [comment]
It got added to the R 4.0.3 in #12311 after the EB 4.3.3 release.

**Comment by robert-mijakovic** [comment]
Ok, done. I'm just updating packages to the newest releases. Once it is done, I will update the pull request. @verdurin Thanks for noticing. @branfosj Thanks for letting me know that I forgot to check the newest stuff from the repo.

**Comment by branfosj** [comment]
@boegelbot please test @ generoso

**Comment by verdurin** [comment]
Test report by @verdurin
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
nuc.lan - Linux Fedora 32, x86_64, Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz, Python 3.8.7
See https://gist.github.com/fa15b7d885dd81b654b26f1984ec0c5b for a full test report.

**Review by verdurin — APPROVED** [review]
Looks fine.

**Comment by verdurin** [comment]
Going in, thanks @robert-mijakovic

**Comment by boegel** [comment]
+1, thanks a lot for looking into this @robert-mijakovic!

**Comment by robert-mijakovic** [comment]
It was a pleasure.

**Pull request merged**
