### PR TITLE
{numlib}[GCC/10.2.0] BLIS v0.8.0, fix missing Perl dep.

### PR DESCRIPTION
**Pull request by akesandgren**
(created using `eb --new-pr`)

Fixes https://github.com/easybuilders/easybuild-easyconfigs/issues/12145

### CODE REVIEW

**Comment by akesandgren** [comment]
Test report by @akesandgren
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
b-an02.hpc2n.umu.se - Linux ubuntu 16.04, x86_64, Intel(R) Xeon(R) CPU E5-2690 v4 @ 2.60GHz, Python 2.7.12
See https://gist.github.com/ea3cddc7972dcf9fabd9269e0e079ef0 for a full test report.

**Review by boegel — CHANGES_REQUESTED** [review]
~~@akesandgren Please apply same fix to `BLIS-0.8.0-GCC-9.3.0.eb` too...~~

eidt: fixed it myself in c03f6e7024

**Comment by boegel** [comment]
@boegelbot please test @ generoso

**Comment by akesandgren** [comment]
Good thing I didn't see your "fixed it myself" since that was incorrect...

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in total)
node3107.skitty.os - Linux centos linux 7.9.2009, x86_64, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz, Python 3.6.8
See https://gist.github.com/a85211337f62c39569ec3fc017a7fabc for a full test report.

**Comment by akesandgren** [comment]
Test report by @akesandgren
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in total)
b-an02.hpc2n.umu.se - Linux ubuntu 16.04, x86_64, Intel(R) Xeon(R) CPU E5-2690 v4 @ 2.60GHz, Python 2.7.12
See https://gist.github.com/adf73937aed16955a05168a7bc74b063 for a full test report.

**Review by boegel — APPROVED** [review]

**Comment by boegel** [comment]
Going in, thanks @akesandgren!

**Pull request merged**
