### PR TITLE
{devel,phys,vis}[GCCcore/12.3.0] MuJoCo v3.1.4, glew v2.2.0, GLFW v3.4 w/ osmesa

### PR DESCRIPTION
**Pull request by WilleBell**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by bedroge** [comment]
@WilleBell In a previous PR you added separate easyconfigs for MuJoCo and its Python bindings: https://github.com/easybuilders/easybuild-easyconfigs/pull/18253. 
Is there a particular reason why you're now bundling them? Otherwise I'd propose to take the same approach as in that PR.

**Comment by WilleBell** [comment]
> @WilleBell In a previous PR you added separate easyconfigs for MuJoCo and its Python bindings: #18253. Is there a particular reason why you're now bundling them? Otherwise I'd propose to take the same approach as in that PR.

For some reason I thought that for the newer version, the bindings installation was modifying the MuJoCo directory, but it seems it only needs the paths to MuJoCo and their plugins directory to be set. I made a new commit following the previous approach.

**Comment by bedroge** [comment]
@boegelbot please test @ jsc-zen3

**Comment by bedroge** [comment]
Test report by @bedroge
**SUCCESS**
Build succeeded for 4 out of 4 (4 easyconfigs in total)
interactive2 - Linux Rocky Linux 8.9, x86_64, AMD EPYC-Milan Processor (zen2), Python 3.6.8
See https://gist.github.com/bedroge/9ac28dd82a60231ee7812638187c05e7 for a full test report.

**Review by bedroge — APPROVED** [review]
Looks good to me.

**Comment by bedroge** [comment]
Going in, thanks @WilleBell!

**Pull request merged**
