### PR TITLE
{data}[foss/2019b] Fiona v1.8.13 w/ Python 3.7.4

### PR DESCRIPTION
**Pull request by lexming**
(created using `eb --new-pr`)

Depends on #10309

### CODE REVIEW

**Comment by Micket** [comment]
Couldn't see a way to re-trigger the travis build

**Comment by lexming** [comment]
Test report by @lexming
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
login2.cerberus.os - Linux centos linux 7.7.1908, Intel(R) Xeon(R) Gold 6126 CPU @ 2.60GHz, Python 2.7.5
See https://gist.github.com/a122034d72ad293891b0131f7f0795cc for a full test report.

**Comment by Micket** [comment]
how did i manage to make duplicate GHA's here?

**Comment by Micket** [comment]
Going in, thanks @lexming!

**Pull request merged**
