### PR TITLE
copy missing `rsem_perl_utils.pm` in DETONATE, since it's required by `rsem-eval-calculate-score` command

### PR DESCRIPTION
**Pull request by boegel**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by boegel** [comment]
@boegelbot please test @ generoso

**Comment by boegel** [comment]
@boegelbot please test @ jsc-zen3

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
node3101.skitty.os - Linux RHEL 8.8, x86_64, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz, Python 3.6.8
See https://gist.github.com/boegel/792cd009abcf717b341dfe171c183371 for a full test report.

**Comment by verdurin** [comment]
Appears that the sanity test command failed on `jsczen3` - not immediately sure why.

**Comment by verdurin** [comment]
Test report by @verdurin
**FAILED**
Build succeeded for 5 out of 6 (1 easyconfigs in total)
easybuild-el8.cloud.in.bmrc.ox.ac.uk - Linux Rocky Linux 8.10, x86_64, Intel Xeon Processor (Skylake, IBRS), Python 3.6.8
See https://gist.github.com/verdurin/33ab9769e1cacd7c631e142b9319a331 for a full test report.

**Comment by boegel** [comment]
Problem on `jsc-zen3` is this:

```
[boegelbot@jsczen3c1 ~]$ rsem-eval-calculate-score --help
Can't locate Env.pm in @INC (you may need to install the Env module) (@INC contains: /tmp/boegelbot/software/DETONATE/1.11-GCC-12.3.0/bin /usr/local/lib64/perl5/5.32 /usr/local/share/perl5/5.32 /usr/lib64/perl5/vendor_perl /usr/share/perl5/vendor_perl /usr/lib64/perl5 /usr/share/perl5) at /tmp/boegelbot/software/DETONATE/1.11-GCC-12.3.0/bin/rsem-eval-calculate-score line 12.
```

This shows we're missing a `Perl` dependency here too...

**Comment by boegel** [comment]
@boegelbot please test @ jsc-zen3

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
node3144.skitty.os - Linux RHEL 8.8, x86_64, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz, Python 3.6.8
See https://gist.github.com/boegel/2b1d61a068494192908ff46bb73ebd09 for a full test report.

**Comment by boegel** [comment]
@boegelbot please test @ generoso

**Review by bedroge — APPROVED** [review]

**Pull request merged**
