### PR TITLE
{bio}[gfbf/2023a] freebayes v1.3.7, vcflib v1.0.9 w/ R 4.3.2

### PR DESCRIPTION
**Pull request by akesandgren**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by akesandgren** [comment]
@boegelbot Please test @ jsc-zen2

**Comment by akesandgren** [comment]
Test report by @akesandgren
**SUCCESS**
Build succeeded for 16 out of 16 (14 easyconfigs in total)
b-an02.hpc2n.umu.se - Linux Ubuntu 20.04, x86_64, Intel(R) Xeon(R) CPU E5-2690 v4 @ 2.60GHz, Python 3.8.10
See https://gist.github.com/akesandgren/a87e8028579ba8d41320c4486808bc40 for a full test report.

**Comment by akesandgren** [comment]
@boegelbot Please test @ jsc-zen2

**Comment by jfgrimm** [comment]
Test report by @jfgrimm
**SUCCESS**
Build succeeded for 17 out of 17 (14 easyconfigs in total)
node051.viking2.yor.alces.network - Linux Rocky Linux 8.8, x86_64, AMD EPYC 7643 48-Core Processor, Python 3.6.8
See https://gist.github.com/jfgrimm/5bf648b1cb178fd226ed1a2ab92a83f6 for a full test report.

**Review by jfgrimm — APPROVED** [review]
lgtm

**Comment by jfgrimm** [comment]
Going in, thanks @akesandgren!

**Pull request merged**
