### PR TITLE
{lib}[GCCcore/10.2.0] SUMO v1.9.0, Xerces-C++ v3.2.3, GL2PS v1.4.2, ... w/ Python 3.8.6

### PR DESCRIPTION
**Pull request by lexming**
(created using `eb --new-pr`)

The easyconfig of SUMO v1.9.0 depends on https://github.com/easybuilders/easybuild-easyblocks/pull/2318

### CODE REVIEW

**Review by Micket — APPROVED** [review]
lgtm

**Comment by Micket** [comment]
@boegelbot please test @ generoso

**Comment by Micket** [comment]
@boegelbot please test @ generoso
EB_ARGS="--include-easyblocks-from-pr=2318"

**Comment by lexming** [comment]
Superseded by #15986

**Pull request closed without merging**
