### PR TITLE
fix for dependencies was set twice in OpenMPI 3.0.0 easyconfig

### PR DESCRIPTION
**Pull request by ocaisa**
so hwloc was being ignored

edit: depends on #5623

### CODE REVIEW

**Comment by ocaisa** [comment]
@boegel This correction is not enough, the `hwloc` easyconfig is actually completely missing

**Comment by boegel** [comment]
@ocaisa Nice catch...

Missing deps added in https://github.com/ocaisa/easybuild-easyconfigs/pull/27 + https://github.com/easybuilders/easybuild-easyconfigs/pull/5623

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 4 out of 4 (3 easyconfigs in this PR)
node2430.golett.os - Linux centos linux 7.4.1708, Intel(R) Xeon(R) CPU E5-2680 v3 @ 2.50GHz, Python 2.7.5
See https://gist.github.com/7e5438dc736c7ce005d5156ee623d8f1 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 3 out of 3 (3 easyconfigs in this PR)
node2021.delcatty.os - Linux centos linux 7.4.1708, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.7.5
See https://gist.github.com/8326e3d02fee343c2430656525797cd5 for a full test report.

**Comment by vanzod** [comment]
Test report by @vanzod
**SUCCESS**
Build succeeded for 3 out of 3 (3 easyconfigs in this PR)
cermis - Linux debian 9.3, Intel(R) Xeon(R) CPU           E5620  @ 2.40GHz, Python 2.7.13
See https://gist.github.com/3582b0d99ee2091b18e18af8a355ede1 for a full test report.

**Comment by vanzod** [comment]
Going in, thanks @ocaisa!

**Pull request merged**
