### PR TITLE
{phys}[Cray*,foss/2019b,intel/2019b,iomkl/2019b] CASTEP v21.1.1

### PR DESCRIPTION
**Pull request by krefson**
…yGNU-19.06.eb, CASTEP-21.1.1-foss-2019b.eb, CASTEP-21.1.1-intel-2019b.eb, CASTEP-21.1.1-iomkl-2019b.eb

### CODE REVIEW

**Comment by migueldiascosta** [comment]
thanks for your contribution @krefson!

we'll likely need a test report from you, it would be good if you could set up easybuild's github integration (https://docs.easybuild.io/en/latest/Integration_with_GitHub.html, it will also help with other stuff) and submit one

regarding the failing tests, you can check them locally with `--check-contrib` (https://docs.easybuild.io/en/latest/Contributing.html) - it's basically a few style issues and missing checksums, which you can add automatically with `--inject-checksums` (https://docs.easybuild.io/en/latest/Writing_easyconfig_files.html#adding-or-replacing-checksums-using-inject-checksums)

do reach out here or on slack if you need any help

**Comment by krefson** [comment]
Test report by @krefson
**FAILED**
Build succeeded for 0 out of 3 (5 easyconfigs in total)
cn1052.scarf.rl.ac.uk - Linux CentOS Linux 7 (Core), x86_64, AMD EPYC 7502P 32-Core Processor, 1 x NVIDIA Tesla T4, 460.73.01, Python 3.9.5
See https://gist.github.com/3f2af7bd2e9d4098a68133b250cf31a5 for a full test report.

**Comment by krefson** [comment]
Test report by @krefson
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
cn1052.scarf.rl.ac.uk - Linux CentOS Linux 7 (Core), x86_64, AMD EPYC 7502P 32-Core Processor, 1 x NVIDIA Tesla T4, 460.73.01, Python 3.9.5
See https://gist.github.com/533392666ba4fd04d04eb7656b35459d for a full test report.

**Comment by krefson** [comment]
Test report by @krefson
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
cn1052.scarf.rl.ac.uk - Linux CentOS Linux 7 (Core), x86_64, AMD EPYC 7502P 32-Core Processor, 1 x NVIDIA Tesla T4, 460.73.01, Python 3.9.5
See https://gist.github.com/78ba82de6d65f75a03446e387fe657eb for a full test report.

**Comment by krefson** [comment]
Test report by @krefson
**FAILED**
Build succeeded for 0 out of 1 (1 easyconfigs in total)
cn1052.scarf.rl.ac.uk - Linux CentOS Linux 7 (Core), x86_64, AMD EPYC 7502P 32-Core Processor, 1 x NVIDIA Tesla T4, 460.73.01, Python 3.9.5
See https://gist.github.com/7205e811e6dcd8f875816c84a5e8ec19 for a full test report.

**Comment by krefson** [comment]
As far as I am concerned, this is ready to go.  

The build failure with the iomlk toolchain was a consequence of a failure of the Intel toolchain to actually run on the AMD processor. I can not test the Cray builds directly as the Cray I have access to does not have Easybuild installed.  However the build commands certainly do work on it, and the EasyBuild configuration files differ only in the toolchain chosen.

**Comment by krefson** [comment]
Test report by @krefson
**SUCCESS**
Build succeeded for 0 out of 0 (1 easyconfigs in total)
cn1052.scarf.rl.ac.uk - Linux CentOS Linux 7 (Core), x86_64, AMD EPYC 7502P 32-Core Processor, 1 x NVIDIA Tesla T4, 460.73.01, Python 3.9.5
See https://gist.github.com/f68b9933a4974c8a692ada88be81c069 for a full test report.

**Comment by krefson** [comment]
Test report by @krefson
**SUCCESS**
Build succeeded for 0 out of 0 (1 easyconfigs in total)
cn1052.scarf.rl.ac.uk - Linux CentOS Linux 7 (Core), x86_64, AMD EPYC 7502P 32-Core Processor, 1 x NVIDIA Tesla T4, 460.73.01, Python 3.9.5
See https://gist.github.com/844697c95fb0e13195f19edd1c9d2413 for a full test report.

**Comment by jfgrimm** [comment]
Test report by @jfgrimm
**SUCCESS**
Build succeeded for 3 out of 3 (3 easyconfigs in total)
node032.pri.viking.alces.network - Linux UNKNOWN UNKNOWN, x86_64, Intel(R) Xeon(R) Gold 6138 CPU @ 2.00GHz (skylake_avx512), Python 3.6.8
See https://gist.github.com/fbc7b71bdc67818fc4f98580ff5aa1cc for a full test report.

**Comment by dquigley-warwick** [comment]
Hi @krefson. 

Long time no see.

See also #7209.

Very happy for that (closed) PR to be superseded, but note the comments about difficulty validating the PR due to lack of source code access. You'll be in an better position than me to address that of course!

**Comment by krefson** [comment]
Test report by @krefson
**SUCCESS**
Build succeeded for 0 out of 0 (1 easyconfigs in total)
cn1052.scarf.rl.ac.uk - Linux CentOS Linux 7 (Core), x86_64, AMD EPYC 7502P 32-Core Processor, 1 x NVIDIA Tesla T4, 460.73.01, Python 3.9.5
See https://gist.github.com/d429a5bcfd9bd4906ec2ecf60a4a4c5d for a full test report.

**Comment by krefson** [comment]
Test report by @krefson
**SUCCESS**
Build succeeded for 0 out of 0 (1 easyconfigs in total)
cn1052.scarf.rl.ac.uk - Linux CentOS Linux 7 (Core), x86_64, AMD EPYC 7502P 32-Core Processor, 1 x NVIDIA Tesla T4, 460.73.01, Python 3.9.5
See https://gist.github.com/86a9892928e8d5e83f5a3536f4c3fa48 for a full test report.

**Comment by krefson** [comment]
Test report by @krefson
**SUCCESS**
Build succeeded for 0 out of 0 (1 easyconfigs in total)
cn1052.scarf.rl.ac.uk - Linux CentOS Linux 7 (Core), x86_64, AMD EPYC 7502P 32-Core Processor, 1 x NVIDIA Tesla T4, 460.73.01, Python 3.9.5
See https://gist.github.com/c2ddc1a794aa1dfd6b1f958ad2d4a6ff for a full test report.

**Comment by jfgrimm** [comment]
Test report by @jfgrimm
**FAILED**
Build succeeded for 0 out of 3 (3 easyconfigs in total)
node084.pri.viking.alces.network - Linux UNKNOWN UNKNOWN, x86_64, Intel(R) Xeon(R) Gold 6138 CPU @ 2.00GHz (skylake_avx512), Python 3.6.8
See https://gist.github.com/fd248be54f03efd8511787001a680035 for a full test report.

**Comment by jfgrimm** [comment]
Test report by @jfgrimm
**SUCCESS**
Build succeeded for 3 out of 3 (3 easyconfigs in total)
node084.pri.viking.alces.network - Linux UNKNOWN UNKNOWN, x86_64, Intel(R) Xeon(R) Gold 6138 CPU @ 2.00GHz (skylake_avx512), Python 3.6.8
See https://gist.github.com/eae2338d5aba10503a94ab12eb9e2196 for a full test report.

**Review by jfgrimm — APPROVED** [review]

**Comment by jfgrimm** [comment]
Going in, thanks @krefson!

**Pull request merged**
