### PR TITLE
{lang}[GCCcore/8.2.0] Tkinter v2.7.15, Tkinter v3.7.2

### PR DESCRIPTION
**Pull request by Micket**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by Micket** [comment]
Test report by @Micket
**FAILED**
Build succeeded for 1 out of 2 (2 easyconfigs in this PR)
hebbe-s1.int.private - Linux centos 6.10, Intel(R) Xeon(R) CPU E5-2650 v3 @ 2.30GHz, Python 2.7.14
See https://gist.github.com/028aff7644482737f90caed3847f4968 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**FAILED**
Build succeeded for 12 out of 13 (2 easyconfigs in this PR)
node3101.skitty.os - Linux centos linux 7.6.1810, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz, Python 2.7.5
See https://gist.github.com/4e568eed2a4fdd95c46bda7d4f590c8f for a full test report.

**Comment by akesandgren** [comment]
Test report by @akesandgren
**SUCCESS**
Build succeeded for 3 out of 3 (2 easyconfigs in this PR)
b-an03.hpc2n.umu.se - Linux ubuntu 16.04, Intel(R) Xeon(R) CPU E5-2690 v4 @ 2.60GHz, Python 2.7.12
See https://gist.github.com/57f2e5f7eb054135b6099f47a3d2018d for a full test report.

**Comment by boegel** [comment]
@Micket I've relaxed the check for `-Python-*` in `versionsuffix` to add `Tkinter` as an exception in https://github.com/Micket/easybuild-easyconfigs/pull/1, please merge that PR to update this one...

**Comment by boegel** [comment]
@Micket Please also fix the trivial code style issues:

```
$ eb --check-contrib --from-pr 8066
== temporary log file in case of crash /Users/kehoste/work/TMP/eb-ufLIBd/easybuild-hfuHik.log

Running style check on 2 easyconfig(s)...

/Users/kehoste/work/TMP/eb-ufLIBd/files_pr8066/t/Tkinter/Tkinter-2.7.15-GCCcore-8.2.0.eb:23:1: W391 blank line at end of file
[FAIL] /Users/kehoste/work/TMP/eb-ufLIBd/files_pr8066/t/Tkinter/Tkinter-2.7.15-GCCcore-8.2.0.eb
/Users/kehoste/work/TMP/eb-ufLIBd/files_pr8066/t/Tkinter/Tkinter-3.7.2-GCCcore-8.2.0.eb:26:1: W391 blank line at end of file
[FAIL] /Users/kehoste/work/TMP/eb-ufLIBd/files_pr8066/t/Tkinter/Tkinter-3.7.2-GCCcore-8.2.0.eb

>> One or more style checks FAILED!

Checking for SHA256 checksums in 2 easyconfig(s)...

[PASS] /Users/kehoste/work/TMP/eb-ufLIBd/files_pr8066/t/Tkinter/Tkinter-2.7.15-GCCcore-8.2.0.eb
[PASS] /Users/kehoste/work/TMP/eb-ufLIBd/files_pr8066/t/Tkinter/Tkinter-3.7.2-GCCcore-8.2.0.eb

>> All SHA256 checksums checks PASSed!

ERROR: One or more contribution checks FAILED!
```

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in this PR)
node3103.skitty.os - Linux centos linux 7.6.1810, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz, Python 2.7.5
See https://gist.github.com/b94cb30369dbf7bd8626024d2bfe3733 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in this PR)
node2001.delcatty.os - Linux centos linux 7.6.1810, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.7.5
See https://gist.github.com/4c03ba1f501539e1e646bf92b6cc2c88 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in this PR)
node2610.swalot.os - Linux centos linux 7.6.1810, Intel(R) Xeon(R) CPU E5-2660 v3 @ 2.60GHz, Python 2.7.5
See https://gist.github.com/d5f118b5778d9575914ddd7609f73123 for a full test report.

**Comment by boegel** [comment]
Going in, thanks @Micket!

**Pull request merged**
