### PR TITLE
{data}[iimkl/2023a] scikit-learn v1.3.1

### PR DESCRIPTION
**Pull request by schiotz**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by schiotz** [comment]
This depends on PR #18875

**Comment by schiotz** [comment]
Closing and reopening to run test suite after #18875 was merged.

**Comment by schiotz** [comment]
Test report by @schiotz
**FAILED**
Build succeeded for 0 out of 1 (1 easyconfigs in total)
svol.fysik.dtu.dk - Linux CentOS Linux 7.9.2009, x86_64, Intel(R) Xeon(R) Gold 6148 CPU @ 2.40GHz, Python 3.6.8
See https://gist.github.com/schiotz/7a8c889af4e3054e2843fcb9aff3ddad for a full test report.

**Comment by schiotz** [comment]
Test report by @schiotz
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
svol.fysik.dtu.dk - Linux CentOS Linux 7.9.2009, x86_64, Intel(R) Xeon(R) Gold 6148 CPU @ 2.40GHz, Python 3.6.8
See https://gist.github.com/schiotz/6c18fa6f3e2cfd131db13db1dea2afd7 for a full test report.

**Comment by schiotz** [comment]
Test report by @schiotz
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
slid.fysik.dtu.dk - Linux CentOS Linux 7.9.2009, x86_64, Intel(R) Xeon(R) CPU E5-2650 v4 @ 2.20GHz, Python 3.6.8
See https://gist.github.com/schiotz/de2c6ccdef64ea1293fc0e6959ffcb47 for a full test report.

**Comment by branfosj** [comment]
@boegelbot please test @ generoso

**Comment by branfosj** [comment]
Test report by @branfosj
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
bear-pg0207u28a.bear.cluster - Linux RHEL 8.6, x86_64, AMD EPYC 9554 64-Core Processor (zen4), Python 3.6.8
See https://gist.github.com/branfosj/c0c389e5ba85c3f866625c9e347399ad for a full test report.

**Comment by branfosj** [comment]
Test report by @branfosj
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
bear-pg0207u20a - Linux RHEL 8.6, x86_64, Intel(R) Xeon(R) Platinum 8480CL (sapphirerapids), Python 3.6.8
See https://gist.github.com/branfosj/f3ed2ad2407c9455b08528754c808697 for a full test report.

**Review by branfosj — APPROVED** [review]

**Comment by branfosj** [comment]
Test report by @branfosj
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
bear-pg0105u03a - Linux RHEL 8.6, x86_64, Intel(R) Xeon(R) Platinum 8360Y CPU @ 2.40GHz (icelake), Python 3.6.8
See https://gist.github.com/branfosj/ba4b4da4668e7ebeb168c13dce49058e for a full test report.

**Comment by branfosj** [comment]
@boegelbot please test @ jsc-zen3

**Comment by branfosj** [comment]
Going in, thanks @schiotz!

**Pull request merged**
