### PR TITLE
VMD 1.9.3: Adding patches for Surf and Stride

### PR DESCRIPTION
**Pull request by akesandgren**
(created using `eb --new-pr`)
VMD 1.9.3 with Surf and Stride

To match easyblock PR ~~https://github.com/easybuilders/easybuild-easyblocks/pull/1314~~

### CODE REVIEW

**Comment by vanzod** [comment]
@akesandgren Can the conflicts be resolved?

**Comment by akesandgren** [comment]
@vanzod merged with develop...

**Comment by vanzod** [comment]
@akesandgren It looks like the `VMD` source archive has a different checksum than the one in the easyconfig files here. Can you please check and update?

**Comment by akesandgren** [comment]
@vanzod updated.

**Comment by akesandgren** [comment]
They might be producing it on the fly. The one in the change is what i got yesterday.

**Comment by vanzod** [comment]
@akesandgren It looks like the archive downloaded without the registration is different. `vmd-1.9.3/lib/surf/surf.tar.Z` must be extracted before applying `VMD-1.9.3_surf_Makefile.patch`

**Comment by akesandgren** [comment]
@vanzod Gah must have forgotten to PR my easyblock changes for that...

**Comment by akesandgren** [comment]
Nope, it's there just haven't been merged yet.
https://github.com/easybuilders/easybuild-easyblocks/pull/1314

**Comment by akesandgren** [comment]
And it says so in the description :-)

**Comment by boegel** [comment]
Re-testing on top of https://github.com/easybuilders/easybuild-easyblocks/pull/1314...

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 4 out of 4 (4 easyconfigs in this PR)
node2006.delcatty.os - Linux centos linux 7.6.1810, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.7.5
See https://gist.github.com/e05247f228a821f4ce3094c57ab8b50f for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 3 out of 3 (3 easyconfigs in this PR)
node3118.skitty.os - Linux centos linux 7.6.1810, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz, Python 2.7.5
See https://gist.github.com/b34479203b7a32e51fb9a1c706bdb248 for a full test report.

**Comment by boegel** [comment]
Going in, thanks @akesandgren!

**Pull request merged**
