### PR TITLE
{bio}[GCC/10.3.0] TRF v4.09.1

### PR DESCRIPTION
**Pull request by garadar**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by garadar** [comment]
Hi @boegel,

If all test succeeded , could re-run check for  https://github.com/easybuilders/easybuild-easyconfigs/pull/17010. Kneadata need this version of TRF 

Thank You

**Comment by smoors** [comment]
@boegelbot: please test @ generoso

**Comment by smoors** [comment]
@boegelbot please test @ jsc-zen2

**Review by smoors — APPROVED** [review]
lgtm

**Comment by smoors** [comment]
Going in, thanks @garadar!

**Pull request merged**
