### PR TITLE
{tools}[system/system] ANSYS v2023R1

### PR DESCRIPTION
**Pull request by Micket**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by Micket** [comment]
Test report by @Micket
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
vera-c2 - Linux Rocky Linux 8.6, x86_64, Intel Xeon Processor (Skylake), Python 3.6.8
See https://gist.github.com/cd0f3da164ef638b4aa7a03ad88c78dc for a full test report.

**Comment by Micket** [comment]
Note: filenames as i obtained them was with "DISK" instead of "Disk". Not sure if that's original or if they for some reason was modified on the way as i got them via a user.

**Review by akesandgren — APPROVED** [review]
LGTM

**Comment by akesandgren** [comment]
Going in, thanks @Micket!

**Pull request merged**
