### PR TITLE
Contrib POV-RAY & many more bits (WIP)

### PR DESCRIPTION
**Pull request by fgeorgatos**
Signed-off-by: Fotis Georgatos

### CODE REVIEW

**Comment by boegel** [comment]
@fgeorgatos: ping on this?

I'm cleaning up the oldest PRs, in an effort to reduce the pile of open PRs.

Is this still relevant? Any idea of the amount of extra effort required to get it ready for merge?

**Comment by fgeorgatos** [comment]
this was working fine on my end but not for others;
I guess recycling it over a rhel6 build would be preferred.
(good example of why building across both debian and rhel would be preferred)

**Comment by boegel** [comment]
@fgeorgatos I had a (potential) need for POV-Ray, so I picked up your easyconfig from here, and revamped it a bit until it worked, see #3551 

Do we still want to put effort into this one, or shall we consider it obsolete?

**Comment by migueldiascosta** [comment]
@fgeorgatos, this PR is being closed for the following reason(s): obsolete, inactive.
Please don't hesitate to reopen this PR or add a comment if you feel this contribution is still relevant.
For more information on our policy w.r.t. closing PRs, see https://easybuild.readthedocs.io/en/latest/Contributing.html#why-a-pull-request-may-be-closed-by-a-maintainer

**Pull request closed without merging**
