### PR TITLE
{lib}[GCCcore/8.3.0] GitPython v3.1.0 w/ Python 3.7.4

### PR DESCRIPTION
**Pull request by lexming**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by lexming** [comment]
Test report by @lexming
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
node376.hydra.os - Linux centos linux 7.7.1908, Intel(R) Xeon(R) Gold 6148 CPU @ 2.40GHz, Python 2.7.5
See https://gist.github.com/5218de64dea45ec4fa97c53746f1a55f for a full test report.

**Comment by migueldiascosta** [comment]
Test report by @migueldiascosta
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
sms - Linux centos linux 7.6.1810, AMD EPYC 7601 32-Core Processor (zen), Python 2.7.5
See https://gist.github.com/838d2cf1fa5e3dd6dc715c25fda4e677 for a full test report.

**Comment by verdurin** [comment]
Test report by @verdurin
**SUCCESS**
Build succeeded for 0 out of 0 (1 easyconfigs in this PR)
generoso - Linux centos linux 7.6.1810, Intel(R) Xeon(R) CPU E5-2660 v4 @ 2.00GHz, Python 3.6.8
See https://gist.github.com/ed11cd409d1da0ff1b3d464bb46d194f for a full test report.

**Comment by verdurin** [comment]
Test report by @verdurin
**FAILED**
Build succeeded for 0 out of 1 (1 easyconfigs in this PR)
easybuild.novalocal - Linux centos linux 7.7.1908, Intel Xeon Processor (Skylake, IBRS), Python 2.7.5
See https://gist.github.com/7f92d13565bac8bd0ceb9bb62f49c075 for a full test report.

**Comment by verdurin** [comment]
```
== FAILED: Installation ended unsuccessfully (build directory: /eb/maint/build/GitPython/3.1.0/GCCcore-8.3.0-Python-3.7.4): build failed (first 300 chars): cmd "pip check" exited with exit code 1 and output:
sphinx 2.2.0 requires sphinxcontrib-applehelp, which is not installed.
sphinx 2.2.0 requires sphinxcontrib-devhelp, which is not installed.
sphinx 2.2.0 requires sphinxcontrib-htmlhelp, which is not installed.
sphinx 2.2.0 requires sphinxcontrib-js (took 9 sec)
```

**Comment by lexming** [comment]
@verdurin This is very strange, `sphinx` is not used anywhere in `GitPython`. For instance, see the `setup.py` for instance: https://github.com/gitpython-developers/GitPython/blob/master/setup.py
Do you have something specific in your system to build documentation that might be missing those dependencies?

**Comment by Micket** [comment]
Test report by @Micket
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
vera-c1 - Linux centos linux 7.7.1908, Intel Xeon Processor (Skylake), Python 2.7.5
See https://gist.github.com/29ccd29001c19cd386180ebc6b7c343b for a full test report.

**Comment by verdurin** [comment]
@lexming Not knowingly. There's nothing with `sphinx` in the name installed on the system.

**Comment by Micket** [comment]
@verdurin I suspect that the issue might be some changes to Python package and that you need to do a `--skip --rebuild`, because the problem you see seems to be in simply doing;

```
$ ml GCCcore/8.3.0 Python
$ pip check
```
In my Python package, I have those sphinx packages:

```
$ ml GCCcore/8.3.0 Python
$ pip list | grep sphinx
sphinxcontrib-applehelp       1.0.1    
sphinxcontrib-devhelp         1.0.1    
sphinxcontrib-htmlhelp        1.0.2    
sphinxcontrib-jsmath          1.0.1    
sphinxcontrib-qthelp          1.0.2    
sphinxcontrib-serializinghtml 1.1.3    
sphinxcontrib-websupport      1.1.2
```

**Comment by verdurin** [comment]
Test report by @verdurin
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
easybuild.novalocal - Linux centos linux 7.7.1908, Intel Xeon Processor (Skylake, IBRS), Python 2.7.5
See https://gist.github.com/cc0204e3c02b5dabaa02bb03f3ac7541 for a full test report.

**Comment by verdurin** [comment]
@Micket thanks for the hint - rebuilding my `Python/3.7.4` fixed the `sphinx` anomaly.

**Comment by verdurin** [comment]
Going in, thanks @lexming!

**Pull request merged**
