### PR TITLE
add dependencies on numexpr and Bottleneck to SciPy-bundle v2020.03

### PR DESCRIPTION
**Pull request by lexming**
(created using `eb --new-pr`)

Follow up of https://github.com/easybuilders/easybuild-easyconfigs/pull/11315

### CODE REVIEW

**Comment by lexming** [comment]
@boegel test fail with `Maximum loop cnt 10000 reached, so quitting`, is this a bug?

**Comment by lexming** [comment]
Test report by @lexming
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in this PR)
node381.hydra.os - Linux centos linux 7.7.1908, x86_64, Intel(R) Xeon(R) Gold 6148 CPU @ 2.40GHz, Python 2.7.5
See https://gist.github.com/350d59dfa057a28f5087371247cd0cbd for a full test report.

**Comment by lexming** [comment]
Test report by @lexming
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in this PR)
node125.hydra.os - Linux centos linux 7.7.1908, x86_64, Intel(R) Xeon(R) CPU E5-2680 v2 @ 2.80GHz, Python 2.7.5
See https://gist.github.com/2a59cf2479fab28e34b7722644dcebc8 for a full test report.

**Comment by boegel** [comment]
@lexming Both `numexpr` and `Bottleneck` depend on `SciPy-bundle`, so you're introducing a cyclic dependency...

**Comment by lexming** [comment]
@boegel omg, I'm so blind :smile: this was a very bad idea then...

**Comment by boegel** [comment]
Yeah, this is not going to work unless we add `numexpr` and `Bottleneck` to `SciPy-bundle` as extensions...

**Comment by lexming** [comment]
@boegel yeah, I think that's the best way forward then. PR updated

**Comment by boegel** [comment]
This makes sense, but it has a downside as well for people who already have `SciPy-bundle` 2020.03 installed (they'll have to run `eb --skip --rebuild` on it to add the missing parts)...

**Comment by lexming** [comment]
Test report by @lexming
**SUCCESS**
Build succeeded for 7 out of 7 (7 easyconfigs in this PR)
node308.hydra.os - Linux centos linux 7.7.1908, x86_64, Intel(R) Xeon(R) Gold 6148 CPU @ 2.40GHz, Python 2.7.5
See https://gist.github.com/c3c345611a1eaafe90bbdd5c54bd383b for a full test report.

**Comment by lexming** [comment]
Test report by @lexming
**SUCCESS**
Build succeeded for 7 out of 7 (7 easyconfigs in this PR)
node127.hydra.os - Linux centos linux 7.7.1908, x86_64, Intel(R) Xeon(R) CPU E5-2680 v2 @ 2.80GHz, Python 2.7.5
See https://gist.github.com/c2fbac3cde981f1900ca7b09da325a16 for a full test report.

**Comment by lexming** [comment]
@boegel That's true, probably it's less troublesome to make this change in `2020b`

**Comment by lexming** [comment]
In such a case I'm closing this PR. I opened issue #11363 instead to not forget about this change for `2020b`.

**Comment by boegel** [comment]
:+1:

**Pull request closed without merging**
