### PR TITLE
{vis}[foss/2019b] matplotlib v2.2.5 w/ Python 2.7.16

### PR DESCRIPTION
**Pull request by lexming**
(created using `eb --new-pr`)
Matplotlib LTS version for Python 2

### CODE REVIEW

**Comment by lexming** [comment]
Test report by @lexming
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
login2.cerberus.os - Linux centos linux 7.7.1908, Intel(R) Xeon(R) Gold 6126 CPU @ 2.60GHz, Python 2.7.5
See https://gist.github.com/29ffd051872e6af24186b1190815c163 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
generoso - Linux centos linux 7.6.1810, Intel(R) Xeon(R) CPU E5-2660 v4 @ 2.00GHz, Python 3.6.8
See https://gist.github.com/a6f717478654db406fcaa94f4beff66c for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
node3142.skitty.os - Linux centos linux 7.7.1908, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz, Python 3.6.8
See https://gist.github.com/c9ddfb3c04c8b5090e56818f358f4489 for a full test report.

**Comment by boegel** [comment]
Going in, thanks @lexming!

**Pull request merged**
