### PR TITLE
{bio}[GCCcore/12.3.0] GeneMark-ET v4.72

### PR DESCRIPTION
**Pull request by PetrKralCZ**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by PetrKralCZ** [comment]
@boegelbot please test @ generoso

**Comment by PetrKralCZ** [comment]
The file `gmes_linux_64-4.72.tar.gz` needs to be obtained manually by filling a form https://genemark.bme.gatech.edu/GeneMark/license_download.cgi

**Comment by PetrKralCZ** [comment]
Test report by @PetrKralCZ
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
node4002.donphan.os - Linux RHEL 8.8, x86_64, Intel(R) Xeon(R) Gold 6240 CPU @ 2.60GHz, 1 x NVIDIA NVIDIA A2, 545.23.08, Python 3.6.8
See https://gist.github.com/PetrKralCZ/6dc9e71c75dd6086fc4d3499fda92ca0 for a full test report.

**Review by smoors — APPROVED** [review]
lgtm

**Comment by smoors** [comment]
Going in, thanks @PetrKralCZ!

**Comment by laraPPr** [comment]
@smoors you merged this but it had failed building on generoso

**Comment by PetrKralCZ** [comment]
> @smoors you merged this but it had failed building on generoso. And I'm now also running into this problem in this pr #21705

@laraPPr  I explained this here: https://github.com/easybuilders/easybuild-easyconfigs/pull/21529#issuecomment-2391477456
The tarball needs to be downloaded to the sources directory on generoso. @boegel

**Comment by laraPPr** [comment]
Ah ok I'll bother him on it.

**Pull request merged**
