### PR TITLE
{lib}[foss/2022b] CuPy v12.1.0 w/ Python 3.10.8 + CUDA 12.0.0

### PR DESCRIPTION
**Pull request by Micket**
(created using `eb --new-pr`)
- [x] #18074

### CODE REVIEW

**Comment by Micket** [comment]
Test report by @Micket
**FAILED**
Build succeeded for 0 out of 1 (1 easyconfigs in total)
vera-r08-01 - Linux Rocky Linux 8.7, x86_64, Intel(R) Xeon(R) Platinum 8358 CPU @ 2.60GHz, 4 x NVIDIA NVIDIA A100-PCIE-40GB, 520.61.05, Python 3.6.8
See https://gist.github.com/Micket/c23cd2dcc6d78e2442a60d85d730c31d for a full test report.

**Comment by Micket** [comment]
Test report by @Micket
**FAILED**
Build succeeded for 0 out of 1 (1 easyconfigs in total)
vera-gpu1 - Linux Rocky Linux 8.7, x86_64, Intel(R) Xeon(R) Gold 6130 CPU @ 2.10GHz, 1 x NVIDIA Tesla V100-SXM2-32GB, 525.85.12, Python 3.6.8
See https://gist.github.com/Micket/aa5678a63db1001ca45ee48a1eed14be for a full test report.

**Comment by Micket** [comment]
Test report by @Micket
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
vera41-1 - Linux Rocky Linux 8.7, x86_64, Intel(R) Xeon(R) Gold 6130 CPU @ 2.10GHz, 1 x NVIDIA Tesla T4, 525.85.12, Python 3.6.8
See https://gist.github.com/Micket/bb67f246270e09c0661c0b27b37e800e for a full test report.

**Comment by SebastianAchilles** [comment]
@boegelbot please test @ jsc-zen2

**Comment by Micket** [comment]
huh
```
ImportError: libcuda.so.1: cannot open shared object file: No such file or directory
```

**Comment by SebastianAchilles** [comment]
Test report by @sebastianachilles
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
skl-rockylinux-88 - Linux Rocky Linux 8.8, x86_64, Intel(R) Core(TM) i7-10700 CPU @ 2.90GHz (skylake), 1 x NVIDIA NVIDIA RTX A4000, 530.30.02, Python 3.6.8
See https://gist.github.com/SebastianAchilles/7d2a399ffc137151e101f0abe342b783 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
node3305.joltik.os - Linux RHEL 8.8, x86_64, Intel(R) Xeon(R) Gold 6242 CPU @ 2.80GHz (cascadelake), 1 x NVIDIA Tesla V100-SXM2-32GB, 535.104.12, Python 3.6.8
See https://gist.github.com/boegel/0576446edeca6eabd869bb7486a17c27 for a full test report.

**Review by boegel — APPROVED** [review]
lgtm

**Comment by boegel** [comment]
Going in, thanks @Micket!

**Comment by Flamefire** [comment]
Test report by @Flamefire
**FAILED**
Build succeeded for 0 out of 1 (total: 1 hour 37 mins 32 secs) (1 easyconfigs in total)
c128 - Linux Rocky Linux 9.6, x86_64, AMD EPYC 9334 32-Core Processor (zen4), 4 x NVIDIA NVIDIA H100, 580.65.06, Python 3.9.21
See https://gist.github.com/Flamefire/d173e9a103fdc984300e489b87a64535 for a full test report.

**Pull request merged**
