### PR TITLE
{bio}[foss/2019a,fosscuda/2019a] mhcnuggets v2.3 w/ Python 3.7.2

### PR DESCRIPTION
**Pull request by lexming**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by lexming** [comment]
Test report by @lexming
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in this PR)
login2.cerberus.os - Linux centos linux 7.7.1908, Intel(R) Xeon(R) Gold 6126 CPU @ 2.60GHz, Python 2.7.5
See https://gist.github.com/cedfabdafc5f63136a980d6dde152759 for a full test report.

**Comment by Micket** [comment]
Test report by @Micket
**SUCCESS**
Build succeeded for 8 out of 8 (2 easyconfigs in this PR)
hebbe-c1 - Linux centos linux 7.7.1908, Intel Core Processor (Haswell, no TSX), Python 2.7.5
See https://gist.github.com/a48f4e6a4e134889cd290ad90aa71d94 for a full test report.

**Comment by lexming** [comment]
@Micket since your test was successful, could you merge this PR? :slightly_smiling_face:

**Comment by Micket** [comment]
Going in, thanks @lexming!

**Pull request merged**
