### PR TITLE
{perf}[gompi/2023b] OSU-Micro-Benchmarks v7.5 w/ CUDA 12.4.0

### PR DESCRIPTION
**Pull request by bedroge**
(created using `eb --new-pr`)

Requires https://github.com/easybuilders/easybuild-easyconfigs/pull/21565.

### CODE REVIEW

**Comment by bedroge** [comment]
@boegelbot please test @ jsc-zen3-a100

**Comment by bedroge** [comment]
Test report by @bedroge
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
bob-Latitude-5300 - Linux Ubuntu 24.04.1 LTS (Noble Numbat), x86_64, Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz, Python 3.12.3
See https://gist.github.com/bedroge/3b9ea15b30aa3f5f62a9b467c1a23a1f for a full test report.

**Comment by bedroge** [comment]
Test report by @bedroge
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
l40sgpu1 - Linux Rocky Linux 8.10, x86_64, Intel(R) Xeon(R) Gold 6240R CPU @ 2.40GHz (cascadelake), 1 x NVIDIA NVIDIA L40S, 555.42.06, Python 3.6.8
See https://gist.github.com/bedroge/4d679e24de5f1b30acc6af1a940c555b for a full test report.

**Comment by bedroge** [comment]
@boegelbot please test @ generoso

**Review by ocaisa — APPROVED** [review]
LGTM

**Pull request merged**
