### PR TITLE
{lang}[dummy/dummy] Java v1.8.0_221

### PR DESCRIPTION
**Pull request by Micket**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by migueldiascosta** [comment]
Test report by @migueldiascosta
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
generoso - Linux centos linux 7.6.1810, Intel(R) Xeon(R) CPU E5-2660 v4 @ 2.00GHz, Python 3.6.8
See https://gist.github.com/82481cda23c203db7df2a6b4552a4301 for a full test report.

**Comment by migueldiascosta** [comment]
Going in, thanks @Micket!

**Comment by boegel** [comment]
@Micket You should also update the `Java/1.8` wrapper accordingly?

**Comment by boegel** [comment]
done in #9038

**Pull request merged**
