### PR TITLE
{lib}[foss/2022a] Tensorflow v2.9.1

### PR DESCRIPTION
**Pull request by alinelena**
it builds some test are failing mainly by missing some module portpicker

### CODE REVIEW

**Comment by Flamefire** [comment]
Test report by @Flamefire
**FAILED**
Build succeeded for 2 out of 3 (3 easyconfigs in total)
taurusml11 - Linux RHEL 7.6, POWER, 8335-GTX (power9le), 6 x NVIDIA Tesla V100-SXM2-32GB, 440.64.00, Python 2.7.5
See https://gist.github.com/7b90c8d42824f384231f193c6ee37b5e for a full test report.

**Comment by Flamefire** [comment]
Test report by @Flamefire
**SUCCESS**
Build succeeded for 4 out of 4 (3 easyconfigs in total)
taurusi8012 - Linux CentOS Linux 7.9.2009, x86_64, AMD EPYC 7352 24-Core Processor (zen2), 8 x NVIDIA NVIDIA A100-SXM4-40GB, 470.57.02, Python 2.7.5
See https://gist.github.com/603c17e8fdc17c4cf7b73a100c671408 for a full test report.

**Comment by Flamefire** [comment]
Test report by @Flamefire
**SUCCESS**
Build succeeded for 3 out of 3 (3 easyconfigs in total)
taurusa15 - Linux CentOS Linux 7.7.1908, x86_64, Intel(R) Xeon(R) CPU E5-2603 v4 @ 1.70GHz (broadwell), 3 x NVIDIA GeForce GTX 1080 Ti, 460.32.03, Python 2.7.5
See https://gist.github.com/8a2da79d93a2bdf54f29b4e990d61c31 for a full test report.

**Comment by seb45tian** [comment]
Test report by @seb45tian
**SUCCESS**
Build succeeded for 34 out of 34 (3 easyconfigs in total)
r12n08.palma.wwu - Linux CentOS Linux 7.9.2009, x86_64, Intel(R) Xeon(R) CPU E5-2683 v4 @ 2.10GHz, Python 3.6.8
See https://gist.github.com/6f5c27375c862ec672a3216ed23e5365 for a full test report.

**Comment by boegel** [comment]
@alinelena Can you look into the failing tests?
```
FAIL: test_dep_versions_per_toolchain_generation (test.easyconfigs.easyconfigs.EasyConfigTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test/easyconfigs/easyconfigs.py", line 844, in test_dep_versions_per_toolchain_generation
    self.assertFalse(multi_dep_vars, error_msg)
AssertionError: No multi-variant deps found for '^.*-(?P<tc_gen>20(1[89]|[2-9][0-9])[ab]).*\.eb$' easyconfigs:

found 2 variants of 'flatbuffers-python' dependency in easyconfigs using '2022a' toolchain generation
* version: 1.12.1; versionsuffix:  as dep for set(['TensorFlow-2.9.1-foss-2022a.eb'])
* version: 2.0; versionsuffix:  as dep for set(['jax-0.3.14-foss-2022a-CUDA-11.7.0.eb'])


======================================================================
FAIL: test_style_conformance (test.easyconfigs.styletests.StyleTest)
Check the easyconfigs for style
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test/easyconfigs/styletests.py", line 68, in test_style_conformance
    self.assertEqual(result, 0, error_msg)
  File "/opt/hostedtoolcache/Python/2.7.18/x64/lib/python2.7/site-packages/easybuild/base/testing.py", line 116, in assertEqual
    raise AssertionError("%s:\nDIFF%s:\n%s" % (msg, limit, ''.join(diff[:self.ASSERT_MAX_DIFF])))
AssertionError: There shouldn't be any code style errors (and/or warnings), found 2:
/home/runner/work/easybuild-easyconfigs/easybuild-easyconfigs/easybuild/easyconfigs/t/TensorFlow/TensorFlow-2.9.1-foss-2022a.eb:164:121: E501 line too long (127 > 120 characters)
/home/runner/work/easybuild-easyconfigs/easybuild-easyconfigs/easybuild/easyconfigs/t/TensorFlow/TensorFlow-2.9.1-foss-2022a.eb:185:121: E501 line too long (143 > 120 characters)
```

**Comment by surak** [comment]
how about a cuda version?

**Comment by surak** [comment]
This fails with ```
== 2022-11-03 13:17:23,758 run.py:658 WARNING Found 3 errors in command output (output: WARNING: Download from https://storage.googleapis.com/mirror.tensorflow.org/github.com/tensorflow/runtime/archive/093ed77f7d50f75b376f40a71ea86e08cedb8b80.tar.gz failed: class java.io.FileNotFoundException GET returned 404 Not Found
```

**Comment by VRehnberg** [comment]
I'm working on CUDA version here https://github.com/easybuilders/easybuild-easyconfigs/pull/16620

**Comment by branfosj** [comment]
Sorry for not following up on this PR. We merged `TensorFlow-2.9.1-foss-2022a.eb` in #17092, so I'll close this PR.

**Pull request closed without merging**
