### PR TITLE
{math}[foss/2018b] numpy v1.15.0 w/ Python 3.6.6

### PR DESCRIPTION
**Pull request by kelseymh**
(copied title from closed PR #10335 )

Update to latest version of Numpy for users tied to foss-2018b toolchain.  This version of Numpy requires Cython 0.29.14 or later, so this branch also includes a Cython-0.29.16 build with the same toolchain and Python.

Resubmitted per comments from @boegel in closed PR #10334 .

### CODE REVIEW

**Comment by kelseymh** [comment]
I still don't understand how to fix the failing test.  The reported error doesn't even seem to be local to this .eb file:

> AssertionError: ['pytest'] is not false : No multi-variant deps found for '^.*-(?P<tc_gen>201[89][ab]).*\.eb$' easyconfigs:
found 3 variants of 'pytest' dependency in easyconfigs using '2018b' toolchain generation
* version: 3.8.2; versionsuffix: -Python-2.7.15 as dep for {'PSI4-1.2.1-intel-2018b-Python-2.7.15-maxam8.eb', 'PSI4-1.2.1-intel-2018b-Python-2.7.15.eb'}
* version: 3.8.2; versionsuffix: -Python-3.6.6 as dep for {'CITE-seq-Count-1.4.3-foss-2018b-Python-3.6.6.eb', 'ProjectQ-0.4.2-intel-2018b-Python-3.6.6.eb'}
* version: 4.4.0; versionsuffix: -Python-3.6.6 as dep for {'numpy-1.18.2-foss-2018b-Python-3.6.6.eb'}

I'd be happy to back up to version 3.8.2 (which is available for foss-2018b-Python-3.6.6), but I think I'd still get the error above, just without the third bullet.

Advice?

**Comment by kelseymh** [comment]
Related issue: #6493 .  It seems like a _lot_ of pull requests have failed due to this test -- 87 pull requests matched a search for "multi-variant dep", in addition to this one.  I'm going to try pulling my numpy back to pytest 3.8.2 (I don't have any reason not to do so).  

It really would help if either the documentation, or the test output, could provide some guidance to writers on what they should do to address this.  This test doesn't appear to get run by `--check-contrib`, so we can't even experiment locally before submitting.

**Comment by kelseymh** [comment]
Woo hoo!  So backing up to the same pytest 3.8.2 worked.  Now we wait :-)

**Comment by smoors** [comment]
@kelseymh the reason for the failed check is that, in the official repo, only one version of a given software can be used as dependency for other softwares (with some exceptions). pytest-3.8.2 is already used as a dep, so 4.4.0 is not allowed.
ideally the same checks should indeed be performed by `--check-contrib`.

**Comment by kelseymh** [comment]
@smoors wrote:
> ideally the same checks should indeed be performed by `--check-contrib`.

Agreed!  But they aren't, at least not with the EB installation at Texas A&M HPRC (which is currently using EasyBuild/2020a_sprint).  Should I create an issue ticket requesting this feature?

**Comment by lexming** [comment]
@kelseymh thanks for updating the PR but `numpy` v1.15.0 is already provided by `Python-3.6.6-foss-2018b.eb`. Sorry for the confusion. The way we handle it has changed a lot in the last toolchains, from having its own easyconfig to be bundled into Python to now be part of `Scipy-bundle`. I think that we can close this PR and focus on #10424 .

**Pull request closed without merging**
