### PR TITLE
disable building of manpages for GDCM to fix installation problem with docbook

### PR DESCRIPTION
**Pull request by boegel**
(created using `eb --new-pr`)
fix for:
```
warning: failed to load external entity http://docbook.sourceforge.net/release/xsl-ns/current/manpages/pi.xsl                                                                                                                                                                 compilation error: file http://docbook.sourceforge.net/release/xsl-ns/current/manpages/docbook.xsl line 42 element include                                                                                                                                                      xsl:include : unable to load http://docbook.sourceforge.net/release/xsl-ns/current/manpages/pi.xsl                                                                                                                                                                              compilation error: file /tmp/vsc40023/easybuild_build/GDCM/3.0.5/GCCcore-8.3.0/easybuild_obj/Utilities/doxygen/gdcm2pnm.xml line 4 element refentry                                                                                                                             xsltParseStylesheetProcess : document is not a styleshee
```

### CODE REVIEW

**Comment by boegel** [comment]
@boegelbot please test @ generoso

**Comment by boegel** [comment]
@boegelbot please test @ generoso
EB_ARGS="GDCM-2.8.9-GCCcore-7.3.0.eb  GDCM-3.0.4-GCCcore-8.2.0.eb GDCM-3.0.5-GCCcore-8.3.0.eb"

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 4 out of 4 (4 easyconfigs in total)
node3129.skitty.os - Linux centos linux 7.9.2009, x86_64, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz, Python 3.6.8
See https://gist.github.com/377100d4176eb3c1216bd25d8469446f for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 4 out of 4 (4 easyconfigs in total)
node2707.swalot.os - Linux centos linux 7.9.2009, x86_64, Intel(R) Xeon(R) CPU E5-2660 v3 @ 2.60GHz (haswell), Python 3.6.8
See https://gist.github.com/0e4b495b146fd7eaeca4152c9c068514 for a full test report.

**Comment by verdurin** [comment]
Test report by @verdurin
**SUCCESS**
Build succeeded for 1 out of 1 (4 easyconfigs in total)
easybuild-c7.novalocal - Linux centos linux 7.9.2009, x86_64, Intel Xeon Processor (Skylake, IBRS), Python 3.6.8
See https://gist.github.com/92f474dedf0fb0244431186d3a324576 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 4 out of 4 (4 easyconfigs in total)
node3409.kirlia.os - Linux centos linux 7.9.2009, x86_64, Intel(R) Xeon(R) Gold 6240 CPU @ 2.60GHz (cascadelake), Python 3.6.8
See https://gist.github.com/c333ef1fdfb66ada36801af607e14517 for a full test report.

**Review by Micket — APPROVED** [review]
lgtm (so many builds but no review!)

**Comment by Micket** [comment]
Going in, thanks @boegel!

**Pull request merged**
