### PR TITLE
use minimal makeinfo (+ Perl) as build dep for groff with GCCcore/8.3.0

### PR DESCRIPTION
**Pull request by boegel**
(created using `eb --new-pr`)
cfr. #13163

### CODE REVIEW

**Review by branfosj — APPROVED** [review]
lgtm

**Comment by branfosj** [comment]
Test report by @branfosj
**SUCCESS**
Build succeeded for 3 out of 3 (3 easyconfigs in total)
bb-pg-login03.bb2.cluster - Linux RHEL 8.6, x86_64, Intel(R) Xeon(R) CPU E5-2690 v4 @ 2.60GHz (broadwell), Python 3.6.8
See https://gist.github.com/41f320c07685f196e00ad87ec46f8d0f for a full test report.

**Comment by boegel** [comment]
@boegelbot please test @ generoso

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 3 out of 3 (3 easyconfigs in total)
node2621.swalot.os - Linux CentOS Linux 7.9.2009, x86_64, Intel(R) Xeon(R) CPU E5-2660 v3 @ 2.60GHz (haswell), Python 2.7.5
See https://gist.github.com/b69b790f58b6ebed57175d41bc890271 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 3 out of 3 (3 easyconfigs in total)
node3162.skitty.os - Linux RHEL 8.4, x86_64, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz, Python 3.6.8
See https://gist.github.com/025119c5a15d8f54b6d3efd86d75df5b for a full test report.

**Comment by branfosj** [comment]
Going in, thanks @boegel!

**Pull request merged**
