### PR TITLE
Move snakemake patch to the right location

### PR DESCRIPTION
**Pull request by branfosj**
In #12557 this patch was added in the top level directory. This moves it to the right place.

### CODE REVIEW

**Comment by branfosj** [comment]
Test report by @branfosj
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
bear-pg0211u03a.bear.cluster - Linux RHEL 8.3, x86_64, Intel(R) Xeon(R) Gold 6248 CPU @ 2.50GHz (cascadelake), Python 3.6.8
See https://gist.github.com/c0fdfc10813a83d14fb46d3a431a4d84 for a full test report.

**Review by ocaisa — APPROVED** [review]
Good catch

**Comment by ocaisa** [comment]
Test report by @ocaisa
**SUCCESS**
Build succeeded for 0 out of 0 (1 easyconfigs in total)
generoso - Linux centos linux 8.2.2004, x86_64, Intel(R) Xeon(R) CPU E5-2667 v3 @ 3.20GHz, Python 3.6.8
See https://gist.github.com/d43111d9570160d9665222b842457a86 for a full test report.

**Comment by ocaisa** [comment]
Test report by @ocaisa
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
generoso - Linux centos linux 8.2.2004, x86_64, Intel(R) Xeon(R) CPU E5-2667 v3 @ 3.20GHz, Python 3.6.8
See https://gist.github.com/2fda13ac589dbce5045f406a2975100d for a full test report.

**Comment by boegel** [comment]
Ah, the patch is commented out...

**Pull request merged**
