### PR TITLE
{toolchain} foss/2023b

### PR DESCRIPTION
**Pull request by boegel**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by boegel** [comment]
@boegelbot please test @ generoso
CORE_CNT=16

**Comment by boegel** [comment]
@boegelbot please test @ generoso
CORE_CNT=16

**Comment by boegel** [comment]
@boegelbot please test @ jsc-zen2
CORE_CNT=16

**Comment by branfosj** [comment]
Test report by @branfosj
**SUCCESS**
Build succeeded for 8 out of 8 (8 easyconfigs in total)
bear-pg0105u03a - Linux RHEL 8.6, x86_64, Intel(R) Xeon(R) Platinum 8360Y CPU @ 2.40GHz (icelake), Python 3.6.8
See https://gist.github.com/branfosj/68827e60da497e8b5775d98b1fbef41c for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 8 out of 8 (8 easyconfigs in total)
node3109.skitty.os - Linux RHEL 8.8, x86_64, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz (skylake_avx512), Python 3.6.8
See https://gist.github.com/boegel/e0c5118c1550648a5058ceb723e49fbc for a full test report.

**Comment by branfosj** [comment]
Test report by @branfosj
**SUCCESS**
Build succeeded for 16 out of 16 (8 easyconfigs in total)
bear-pg0207u28a.bear.cluster - Linux RHEL 8.6, x86_64, AMD EPYC 9554 64-Core Processor (zen4), Python 3.6.8
See https://gist.github.com/branfosj/c4dc88fd9546a5ad6363a54478b9ad45 for a full test report.

**Comment by branfosj** [comment]
Test report by @branfosj
**SUCCESS**
Build succeeded for 16 out of 16 (8 easyconfigs in total)
bear-pg0207u20a - Linux RHEL 8.6, x86_64, Intel(R) Xeon(R) Platinum 8480CL (sapphirerapids), Python 3.6.8
See https://gist.github.com/branfosj/1d0190b1e5fe8d5a24c18cd6fdc0668a for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**FAILED**
Build succeeded for 74 out of 75 (8 easyconfigs in total)
aarch64-neoverse-n1-node1.int.aws-rocky88-202310.eessi.io - Linux Rocky Linux 8.8, AArch64, ARM UNKNOWN (neoverse_n1), Python 3.6.8
See https://gist.github.com/boegel/0f3bdcb7c67a839dddbc47450c86b370 for a full test report.

**Comment by branfosj** [comment]
Test report by @branfosj
**SUCCESS**
Build succeeded for 59 out of 59 (8 easyconfigs in total)
bear-pg0211u08b.bear.cluster - Linux RHEL 8.6, x86_64, Intel(R) Xeon(R) Gold 6248 CPU @ 2.50GHz (cascadelake), Python 3.6.8
See https://gist.github.com/branfosj/8f2696dc194054df050874299967e1f2 for a full test report.

**Comment by jfgrimm** [comment]
Test report by @jfgrimm
**FAILED**
Build succeeded for 50 out of 58 (8 easyconfigs in total)
himem02.viking2.yor.alces.network - Linux Rocky Linux 8.8, x86_64, AMD EPYC 7643 48-Core Processor, Python 3.6.8
See https://gist.github.com/jfgrimm/36eaebaa68c4e48a33f6c8768f9bfce0 for a full test report.

**Comment by boegel** [comment]
@jfgrimm Any idea what this is about in your test report?
```
checking for MCA component pmix:pmix3x compile mode... dso
configure: WARNING: Found configure shell variable clash at line 175707!
configure: WARNING: OPAL_VAR_SCOPE_PUSH called on "PMIX_VERSION",
configure: WARNING: but it is already defined with value "4.2.6"
configure: WARNING: This usually indicates an error in configure.
configure: error: Cannot continue
```

**Comment by jfgrimm** [comment]
> @jfgrimm Any idea what this is about in your test report?
> 
> ```
> checking for MCA component pmix:pmix3x compile mode... dso
> configure: WARNING: Found configure shell variable clash at line 175707!
> configure: WARNING: OPAL_VAR_SCOPE_PUSH called on "PMIX_VERSION",
> configure: WARNING: but it is already defined with value "4.2.6"
> configure: WARNING: This usually indicates an error in configure.
> configure: error: Cannot continue
> ```

no idea, haven't seen that before. Could be hook related I suppose, will need to have a look

**Comment by boegel** [comment]
@jfgrimm Since this could be hook related, and we're not seeing this anywhere else, I suggest that we don't let this block this PR?

**Comment by jfgrimm** [comment]
> @jfgrimm Since this could be hook related, and we're not seeing this anywhere else, I suggest that we don't let this block this PR?

absolutely

**Comment by jfgrimm** [comment]
Test report by @jfgrimm
**FAILED**
Build succeeded for 2 out of 9 (8 easyconfigs in total)
himem02.viking2.yor.alces.network - Linux Rocky Linux 8.8, x86_64, AMD EPYC 7643 48-Core Processor, Python 3.6.8
See https://gist.github.com/jfgrimm/ccaded0b7178279483f34b3c7cb3fa21 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
Using easyblocks from PR(s) https://github.com/easybuilders/easybuild-easyblocks/pull/3041
**SUCCESS**
Build succeeded for 8 out of 8 (8 easyconfigs in total)
aarch64-neoverse-n1-node1.int.aws-rocky88-202310.eessi.io - Linux Rocky Linux 8.8, AArch64, ARM UNKNOWN (neoverse_n1), Python 3.6.8
See https://gist.github.com/boegel/54219fc38fa18a0faffd07a4dcf10db3 for a full test report.

**Comment by jfgrimm** [comment]
@boegel figured it out, it's not hook related. We have `MpiDefault=pmix` in `slurm.conf` and `PMIx 4.2.6` installed, so the job I was building in already have `PMIX_*` env vars set...

**Comment by jfgrimm** [comment]
Test report by @jfgrimm
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
himem02.viking2.yor.alces.network - Linux Rocky Linux 8.8, x86_64, AMD EPYC 7643 48-Core Processor, Python 3.6.8
See https://gist.github.com/jfgrimm/6d4dadd2199dee1364e127e6b8e33650 for a full test report.

**Review by jfgrimm — APPROVED** [review]

**Comment by jfgrimm** [comment]
Test report by @jfgrimm
**SUCCESS**
Build succeeded for 6 out of 6 (3 easyconfigs in total)
himem02.viking2.yor.alces.network - Linux Rocky Linux 8.8, x86_64, AMD EPYC 7643 48-Core Processor, Python 3.6.8
See https://gist.github.com/jfgrimm/f4b523d461d22326cd7f66a6f211f980 for a full test report.

**Comment by jfgrimm** [comment]
Going in, thanks @boegel!

**Comment by SebastianAchilles** [comment]
Test report by @sebastianachilles
**SUCCESS**
Build succeeded for 8 out of 8 (8 easyconfigs in total)
jscclxc1.int.jsc-clx.fz-juelich.de - Linux Rocky Linux 9.3, x86_64, Intel Xeon Processor (Cascadelake) (cascadelake), Python 3.9.18
See https://gist.github.com/SebastianAchilles/85478015a0ca8d11aa467a0d4c615ccf for a full test report.

**Comment by SebastianAchilles** [comment]
Test report by @sebastianachilles
**SUCCESS**
Build succeeded for 8 out of 8 (8 easyconfigs in total)
jsczen3c1.int.jsc-zen3.fz-juelich.de - Linux Rocky Linux 9.3, x86_64, AMD EPYC-Milan Processor (zen3), Python 3.9.18
See https://gist.github.com/SebastianAchilles/212289b60af3fc3b3d7989130d0e201a for a full test report.

**Pull request merged**
