### PR TITLE
{tools}[system/system] vsc-mympirun v5.2.10

### PR DESCRIPTION
**Pull request by boegel**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
node2603.swalot.os - Linux CentOS Linux 7.9.2009, x86_64, Intel(R) Xeon(R) CPU E5-2660 v3 @ 2.60GHz (haswell), Python 3.6.8
See https://gist.github.com/4ac947916f0580ec00e61a7f187b8e48 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
node3506.doduo.os - Linux RHEL 8.4, x86_64, AMD EPYC 7552 48-Core Processor (zen2), Python 3.6.8
See https://gist.github.com/31f72386fa99dfdb96a9b844eaa378ba for a full test report.

**Comment by casparvl** [comment]
@boegelbot please test @ generoso

**Review by casparvl — APPROVED** [review]
LGTM! No unexpected changes when checking with `--review-pr` either.

**Comment by casparvl** [comment]
Going in, thanks @boegel!

**Pull request merged**
