### PR TITLE
{ai}[foss/2023a] gym-pybullet-drones v2.0.0-3d7b12

### PR DESCRIPTION
**Pull request by akesandgren**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by akesandgren** [comment]
Test report by @akesandgren
**SUCCESS**
Build succeeded for 0 out of 0 (1 easyconfigs in total)
b-cn1602.hpc2n.umu.se - Linux Ubuntu 22.04, x86_64, AMD EPYC 9454 48-Core Processor, 4 x NVIDIA NVIDIA H100 80GB HBM3, 555.58.02, Python 3.10.12
See https://gist.github.com/akesandgren/2a98b85b944e1f91e38191f9a1ffde27 for a full test report.

**Review by Micket — CHANGES_REQUESTED** [review]
Maybe we can just stick to "3d7b12e" for the commit? It's quite common (github even just displays the short part most of the times. 

Downloading still works
wget https://github.com/utiasDSL/gym-pybullet-drones/archive/3d7b12e.tar.gz

**Comment by akesandgren** [comment]
One could but I always prefer full commit id's

**Comment by akesandgren** [comment]
I could make the versionsuffix use a shorter one however and still use the full one internally...

**Comment by Micket** [comment]
well at least do that.

**Comment by akesandgren** [comment]
versionsuffix shortened

**Comment by akesandgren** [comment]
Test report by @akesandgren
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
b-cn1602.hpc2n.umu.se - Linux Ubuntu 22.04, x86_64, AMD EPYC 9454 48-Core Processor, 4 x NVIDIA NVIDIA H100 80GB HBM3, 555.58.02, Python 3.10.12
See https://gist.github.com/akesandgren/d146f32c8f483c90cc2cd93b6f386738 for a full test report.

**Review by Micket — APPROVED** [review]
lgtm

**Comment by Micket** [comment]
@boegelbot please test @ jsc-zen3

**Comment by Micket** [comment]
```
/home/runner/work/easybuild-easyconfigs/easybuild-easyconfigs/easybuild/easyconfigs/g/gym-pybullet-drones/gym-pybullet-drones-2.0.0-3d7b12e-foss-2023a.eb:11:14: E201 whitespace after '{'
/home/runner/work/easybuild-easyconfigs/easybuild-easyconfigs/easybuild/easyconfigs/g/gym-pybullet-drones/gym-pybullet-drones-2.0.0-3d7b12e-foss-2023a.eb:11:49: E202 whitespace before '}'
/home/runner/work/easybuild-easyconfigs/easybuild-easyconfigs/easybuild/easyconfigs/g/gym-pybullet-drones/gym-pybullet-drones-2.0.0-3d7b12e-foss-2023a.eb:35:121: E501 line too long (132 > 120 characters)
```
needs fixing

**Review by Micket — DISMISSED** [review]
lgtm

**Comment by Micket** [comment]
Test report by @Micket
**FAILED**
Build succeeded for 1 out of 2 (1 easyconfigs in total)
alvis-skylake-build - Linux Rocky Linux 8.9, x86_64, Intel Xeon Processor (Skylake, IBRS, no TSX), Python 3.6.8
See https://gist.github.com/Micket/662b657a73da7f83ccdc025834b8cf20 for a full test report.

**Comment by Micket** [comment]
Hm
```
== 2024-09-27 16:09:04,545 run.py:251 INFO Using /bin/bash as shell for running cmd: sed -i -e 's/gymnasium.*/gymnasium="*"/'
                             -e 's/transforms3d.*/transforms3d="*"/' pyproject.toml &&  /apps/Test2/software/Python/3.11.3-GCCcore-12.3.0/bin/python -m pip install --prefix=/apps/Test2/software/gym-pybullet-drones/2.0.0-3d7b12e-foss-2023a  --no-deps  --ignore-installed  --no-index  --no-build-isolation  .
== 2024-09-27 16:09:04,545 run.py:260 INFO running cmd: sed -i -e 's/gymnasium.*/gymnasium="*"/'
                             -e 's/transforms3d.*/transforms3d="*"/' pyproject.toml &&  /apps/Test2/software/Python/3.11.3-GCCcore-12.3.0/bin/python -m pip install --prefix=/apps/Test2/software/gym-pybullet-drones/2.0.0-3d7b12e-foss-2023a  --no-deps  --ignore-installed  --no-index  --no-build-isolation  . 
== 2024-09-27 16:09:04,831 build_log.py:171 ERROR EasyBuild crashed with an error (at easybuild/base/exceptions.py:126 in __init__): cmd "sed -i -e 's/gymnasium.*/gymnasium="*"/'
                             -e 's/transforms3d.*/transforms3d="*"/' pyproject.toml &&  /apps/Test2/software/Python/3.11.3-GCCcore-12.3.0/bin/python -m pip install --prefix=/apps/Test2/software/gym-pybullet-drones/2.0.0-3d7b12e-foss-2023a  --no-deps  --ignore-installed  --no-index  --no-build-isolation  ." exited with exit code 127 and output:
sed: no input files
/bin/bash: line 1: -e: command not found
```
no time to debug this right now

**Comment by branfosj** [comment]
It does not like the new line break in
```
        'preinstallopts': """sed -i -e 's/gymnasium.*/gymnasium="*"/'
                             -e 's/transforms3d.*/transforms3d="*"/' pyproject.toml && """,
```

**Comment by akesandgren** [comment]
@boegelbot Please test @ jsc-zen3

**Comment by Micket** [comment]
Test report by @Micket
**FAILED**
Build succeeded for 0 out of 1 (1 easyconfigs in total)
alvis-skylake-build - Linux Rocky Linux 8.9, x86_64, Intel Xeon Processor (Skylake, IBRS, no TSX), Python 3.6.8
See https://gist.github.com/Micket/cf3fcb40ece4e1730f57f5d10a9dc1ff for a full test report.

**Review by Micket — APPROVED** [review]
lgtm

**Pull request merged**
