### PR TITLE
{data}[foss/2017b,intel/2017b] ITK v4.13.1

### PR DESCRIPTION
**Pull request by vanzod**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by vanzod** [comment]
Test report by @vanzod
**FAILED**
Build succeeded for 1 out of 2 (2 easyconfigs in this PR)
cermis - Linux debian 9.7, Intel(R) Xeon(R) CPU           X5670  @ 2.93GHz, Python 2.7.13
See https://gist.github.com/d8e6c0caccf11958e9cf849f9a39d0fc for a full test report.

**Comment by vanzod** [comment]
For some reason that is not yet clear to me, building ITK with the Intel compiler fails with:
```
In file included from /tmp/ITK/4.13.1/intel-2017b-Python-2.7.14/ITK-4.13.1/Modules/Core/Common/include/itkNumericTraits.h:54:
/opt/easybuild/software/Core/icc/2017.4.196-GCC-6.4.0-2.28/compilers_and_libraries_2017.4.196/linux/compiler/include/complex:69:24: error: '_M_value' is a private member of 'std::complex<double>'
        _M_value = __z._M_value;
                       ^
/opt/easybuild/software/Core/GCCcore/6.4.0/include/c++/6.4.0/complex:1344:17: note: declared private here
      _ComplexT _M_value;
```

@boegel Could you please test `ITK-4.13.1-intel-2017b-Python-2.7.14.eb`? I need to understand if the issue is local or not.

**Comment by boegel** [comment]
Test report by @boegel
**FAILED**
Build succeeded for 15 out of 23 (2 easyconfigs in this PR)
node3100.skitty.os - Linux centos linux 7.6.1810, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz, Python 2.7.5
See https://gist.github.com/8bc18625c047166d7cad231d381f50db for a full test report.

**Comment by boegel** [comment]
@vanzod Same issue here, see upcoming test report...

**Comment by boegel** [comment]
Test report by @boegel
**FAILED**
Build succeeded for 1 out of 2 (2 easyconfigs in this PR)
node3110.skitty.os - Linux centos linux 7.6.1810, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz, Python 2.7.5
See https://gist.github.com/296f4da4c7e1ec9ccb04d6c8f3f81255 for a full test report.

**Comment by murfreesboro** [comment]
> For some reason that is not yet clear to me, building ITK with the Intel compiler fails with:
> 
> ```
> In file included from /tmp/ITK/4.13.1/intel-2017b-Python-2.7.14/ITK-4.13.1/Modules/Core/Common/include/itkNumericTraits.h:54:
> /opt/easybuild/software/Core/icc/2017.4.196-GCC-6.4.0-2.28/compilers_and_libraries_2017.4.196/linux/compiler/include/complex:69:24: error: '_M_value' is a private member of 'std::complex<double>'
>         _M_value = __z._M_value;
>                        ^
> /opt/easybuild/software/Core/GCCcore/6.4.0/include/c++/6.4.0/complex:1344:17: note: declared private here
>       _ComplexT _M_value;
> ```
> @boegel Could you please test `ITK-4.13.1-intel-2017b-Python-2.7.14.eb`? I need to understand if the issue is local or not.

What I am guessing is that Intel compiler did not use the correct STD library from the GCC. Somehow they do not match with each other.

**Comment by boegel** [comment]
@vanzod Since this PR is for an ancient ITK version and a now deprecated EasyBuild toolchain (see https://docs.easybuild.io/en/latest/Deprecated-easyconfigs.html#deprecated-toolchains), I'll go ahead and close this PR...

**Pull request closed without merging**
