### PR TITLE
{bio}[GCCcore/12.3.0] NextPolish v1.4.1

### PR DESCRIPTION
**Pull request by pavelToman**
(created using `eb --new-pr`)
resolves https://github.com/vscentrum/vsc-software-stack/issues/398

### CODE REVIEW

**Comment by pavelToman** [comment]
@boegelbot please test @ generoso

**Comment by pavelToman** [comment]
@boegelbot please test @ jsc-zen3

**Comment by laraPPr** [comment]
Test report by @laraPPr
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
node3501.doduo.os - Linux RHEL 8.8, x86_64, AMD EPYC 7552 48-Core Processor, Python 3.11.3
See https://gist.github.com/laraPPr/9a4280c80b653d19a45e2d3bfc9b02d3 for a full test report.

**Review by laraPPr — APPROVED** [review]
lgtm

**Comment by pavelToman** [comment]
This should be remove - instead a new easyconfig for NextPolish is ready: https://github.com/easybuilders/easybuild-easyconfigs/pull/21588

**Pull request merged**
