### PR TITLE
{bio}[GCCcore/9.3.0] minimap2 v2.17

### PR DESCRIPTION
**Pull request by bedroge**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by verdurin** [comment]
Test report by @verdurin
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
easybuild.novalocal - Linux centos linux 7.8.2003, Intel Xeon Processor (Skylake, IBRS), Python 2.7.5
See https://gist.github.com/2c427c402ffc7de2896aea305d846ab9 for a full test report.

**Comment by verdurin** [comment]
@bedroge - any chance of a test report from you too?

**Comment by bedroge** [comment]
Test report by @bedroge
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
build.hpc.rug.nl - Linux centos linux 7.4.1708, Intel(R) Xeon(R) CPU E5-2660 0 @ 2.20GHz, Python 2.7.5
See https://gist.github.com/866eea101678f9d36daf81b37f9f4766 for a full test report.

**Comment by bedroge** [comment]
Was planning to do that, but forgot about it ;-). Here it is.

**Comment by verdurin** [comment]
Going in, thanks @bedroge!

**Pull request merged**
