### PR TITLE
disable usNIC by default in libfabric to avoid problems due to linking to both libnl and libnl-3

### PR DESCRIPTION
**Pull request by ocaisa**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by ocaisa** [comment]
This results in identical configuration on Generoso:
```
*** Built-in providers: hook_debug perf rstream shm rxd mrail rxm tcp udp verbs
```
so I can't test the impact of this.

**Review by Micket — APPROVED** [review]
lgtm

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 5 out of 5 (5 easyconfigs in total)
node2601.swalot.os - Linux centos linux 7.9.2009, x86_64, Intel(R) Xeon(R) CPU E5-2660 v3 @ 2.60GHz (haswell), Python 3.6.8
See https://gist.github.com/9546bdda802c551ef1f987c42b6bae2a for a full test report.

**Comment by boegel** [comment]
Before these changes, on a system that includes `libnl3-devel`, `fi_info -l` produced output like:

```
$ fi_info -l
usnic:
    version: 1.0
verbs:
    version: 111.0
...
```

With this change, the `usnic` entry is no longer there.

**Comment by boegel** [comment]
@boegelbot please test @ generoso

**Review by boegel — APPROVED** [review]
lgtm

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 5 out of 5 (5 easyconfigs in total)
node3506.doduo.os - Linux RHEL 8.2, x86_64, AMD EPYC 7552 48-Core Processor (zen2), Python 3.6.8
See https://gist.github.com/a33b35c88097689d4f99ccf88d01e7a6 for a full test report.

**Comment by boegel** [comment]
Going in, thanks @ocaisa!

**Pull request merged**
