### PR TITLE
rename tornado-timeouts.patch and add missing authorship

### PR DESCRIPTION
**Pull request by lexming**

### CODE REVIEW

**Comment by lexming** [comment]
@boegelbot: please test @ generoso

**Comment by lexming** [comment]
@boegelbot please test @ jsc-zen3

**Review by boegel — APPROVED** [review]
lgtm

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in total)
node3117.skitty.os - Linux RHEL 8.8, x86_64, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz, Python 3.6.8
See https://gist.github.com/boegel/a5cfa2bd52f34909b18bd34b8d87b26d for a full test report.

**Comment by boegel** [comment]
Going in, thanks @lexming!

**Pull request merged**
