### PR TITLE
{vis}[foss/2017b,intel/2017b] Nilearn v0.5.2 w/ Python 2.7.14 + 3.6.3

### PR DESCRIPTION
**Pull request by vanzod**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by vanzod** [comment]
Test report by @vanzod
**SUCCESS**
Build succeeded for 4 out of 4 (4 easyconfigs in this PR)
cermis - Linux debian 9.9, Intel(R) Xeon(R) CPU           X5670  @ 2.93GHz, Python 2.7.13
See https://gist.github.com/e80cdae4bbd2056f00866afb7f9683d3 for a full test report.

**Comment by smoors** [comment]
Test report by @smoors
**FAILED**
Build succeeded for 13 out of 15 (4 easyconfigs in this PR)
nic414 - Linux centos linux 7.5.1804, Intel(R) Xeon(R) Gold 6148 CPU @ 2.40GHz, Python 2.7.5
See https://gist.github.com/1a89fea19eb15b93a48e9c626a448cd2 for a full test report.

**Comment by smoors** [comment]
Test report by @smoors
**SUCCESS**
Build succeeded for 15 out of 15 (4 easyconfigs in this PR)
nic426 - Linux centos linux 7.5.1804, Intel(R) Xeon(R) Gold 6148 CPU @ 2.40GHz, Python 2.7.5
See https://gist.github.com/3a7b3729cee011368cea910381823c92 for a full test report.

**Comment by smoors** [comment]
Going in, thanks @vanzod!

**Pull request merged**
