### PR TITLE
{bio}[GCCcore/10.3.0] NGS v2.10.9

### PR DESCRIPTION
**Pull request by pberthier**
(created using `eb --new-pr`)

### CODE REVIEW

**Review by Micket — DISMISSED** [review]
Why not update the version as well?
https://github.com/ncbi/ngs/releases/tag/2.11.2

**Comment by pberthier** [comment]
Version upgraded to 2.11.2

**Comment by pberthier** [comment]
would be good to keep both versions as I might need version NGS-2.10.9 for this other PR #15602

**Comment by pberthier** [comment]
should I in principle submit two PR, one for each version?

**Comment by pberthier** [comment]
Test report by @pberthier
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
softdev.binf.unibe.ch - Linux CentOS Linux 7.9.2009, x86_64, Intel(R) Xeon(R) Gold 6240 CPU @ 2.60GHz, Python 3.6.8
See https://gist.github.com/e5df58e3e0064bbc5c0e20535e5b96f7 for a full test report.

**Review by boegel — APPROVED** [review]
lgtm

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
node3108.skitty.os - Linux RHEL 8.4, x86_64, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz (skylake_avx512), Python 3.6.8
See https://gist.github.com/dffa373ca1df8ee94038ac04539d930b for a full test report.

**Comment by boegel** [comment]
Going in, thanks @pberthier!

**Pull request merged**
