### PR TITLE
Fix template bug in Qt5-5.15.2-GCCcore-11.2.0.eb.

### LINKED ISSUE #17463: Template error in Qt5-5.15.2-GCCcore-11.2.0.eb.
When building breakpad in Qt5-5.15.2-GCCcore-11.2.0.eb newer GCCs throw a template error. See https://github.com/pytorch/pytorch/issues/70392#issuecomment-1003488196 for one solution. @zao explained it as such:

> Like std::min<unsigned long>(16384, SIGSTKSZ) or std::min(16384L, SIGSTKSZ) or similar ways of making the types the same like casts, that is.
You've got a function like std::min<T>(T& a, T& b) and if you pass in values of different types, it won't be able to infer what the common type is supposed to be. The rest of the noise is how it also doesn't fit any of the other versions of the function template that takes fancier things like sequences or initializer lists.

The error is:

```
[3883/22428] CXX obj/third_party/breakpad/client/exception_handler.o
FAILED: obj/third_party/breakpad/client/exception_handler.o
/tmp/terjekv/tmp-installs/libWallModelledLES-0.6.1-foss-2021b.eb/software/GCCcore/11.2.0/bin/g++ -MMD -MF obj/third_party/breakpad/client/exception_handler.o.d -DUSE_UDEV -DU
SE_AURA=1 -DUSE_NSS_CERTS=1 -DUSE_OZONE=1 -DOFFICIAL_BUILD -DTOOLKIT_QT -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -D_LARGEFILE64_SOURCE -DNO_UNWIND_TABLES -DNDEBUG -DNVALGRI
ND -DDYNAMIC_ANNOTATIONS_ENABLED=0 -I../../3rdparty/chromium/third_party/breakpad -I../../3rdparty/chromium/third_party/breakpad/breakpad/src -I../../3rdparty/chromium/third_
party/breakpad/breakpad/src/client -I../../3rdparty/chromium/third_party/breakpad/breakpad/src/third_party/linux/include -Igen -I../../3rdparty/chromium -I../../3rdparty/chro
mium/third_party/breakpad/breakpad/src -fno-strict-aliasing --param=ssp-buffer-size=4 -fstack-protector -fno-unwind-tables -fno-asynchronous-unwind-tables -fPIC -pipe -pthrea
d -m64 -O2 -fno-ident -fdata-sections -ffunction-sections -fno-omit-frame-pointer -g0 -fvisibility=hidden -Wno-unused-local-typedefs -Wno-maybe-uninitialized -Wno-deprecated-
declarations -fno-delete-null-pointer-checks -Wno-comments -Wno-packed-not-aligned -Wno-dangling-else -Wno-missing-field-initializers -Wno-unused-parameter -std=gnu++14 -fno-
exceptions -fno-rtti -fvisibility-inlines-hidden -Wno-narrowing -Wno-class-memaccess -Wno-attributes -Wno-class-memaccess -Wno-subobject-linkage -Wno-invalid-offsetof -Wno-re
turn-type -Wno-deprecated-copy -c ../../3rdparty/chromium/third_party/breakpad/breakpad/src/client/linux/handler/exception_handler.cc -o obj/third_party/breakpad/client/excep
tion_handler.o
../../3rdparty/chromium/third_party/breakpad/breakpad/src/client/linux/handler/exception_handler.cc: In function void google_breakpad::{anonymous}::InstallAlternateStackLocke
d():
../../3rdparty/chromium/third_party/breakpad/breakpad/src/client/linux/handler/exception_handler.cc:141:49: error: no matching function for call to max(int, long int)
  141 |   static const unsigned kSigStackSize = std::max(16384, SIGSTKSZ);
      |                                         ~~~~~~~~^~~~~~~~~~~~~~~~~
In file included from /tmp/terjekv/tmp-installs/libWallModelledLES-0.6.1-foss-2021b.eb/software/GCCcore/11.2.0/include/c++/11.2.0/bits/char_traits.h:39,
                 from /tmp/terjekv/tmp-installs/libWallModelledLES-0.6.1-foss-2021b.eb/software/GCCcore/11.2.0/include/c++/11.2.0/string:40,
                 from ../../3rdparty/chromium/third_party/breakpad/breakpad/src/client/linux/handler/exception_handler.h:38,
                 from ../../3rdparty/chromium/third_party/breakpad/breakpad/src/client/linux/handler/exception_handler.cc:66:
/tmp/terjekv/tmp-installs/libWallModelledLES-0.6.1-foss-2021b.eb/software/GCCcore/11.2.0/include/c++/11.2.0/bits/stl_algobase.h:254:5: note: candidate: template<class _Tp> co
nstexpr const _Tp& std::max(const _Tp&, const _Tp&)
  254 |     max(const _Tp& __a, const _Tp& __b)
      |     ^~~
/tmp/terjekv/tmp-installs/libWallModelledLES-0.6.1-foss-2021b.eb/software/GCCcore/11.2.0/include/c++/11.2.0/bits/stl_algobase.h:254:5: note:   template argument deduction/sub
stitution failed:
../../3rdparty/chromium/third_party/breakpad/breakpad/src/client/linux/handler/exception_handler.cc:141:49: note:   deduced conflicting types for parameter const _Tp (int and
 long int)
  141 |   static const unsigned kSigStackSize = std::max(16384, SIGSTKSZ);
      |                                         ~~~~~~~~^~~~~~~~~~~~~~~~~
In file included from /tmp/terjekv/tmp-installs/libWallModelledLES-0.6.1-foss-2021b.eb/software/GCCcore/11.2.0/include/c++/11.2.0/bits/char_traits.h:39,
                 from /tmp/terjekv/tmp-installs/libWallModelledLES-0.6.1-foss-2021b.eb/software/GCCcore/11.2.0/include/c++/11.2.0/string:40,
                 from ../../3rdparty/chromium/third_party/breakpad/breakpad/src/client/linux/handler/exception_handler.h:38,
                 from ../../3rdparty/chromium/third_party/breakpad/breakpad/src/client/linux/handler/exception_handler.cc:66:
/tmp/terjekv/tmp-installs/libWallModelledLES-0.6.1-foss-2021b.eb/software/GCCcore/11.2.0/include/c++/11.2.0/bits/stl_algobase.h:300:5: note: candidate: template<class _Tp, cl
ass _Compare> constexpr const _Tp& std::max(const _Tp&, const _Tp&, _Compare)
  300 |     max(const _Tp& __a, const _Tp& __b, _Compare __comp)
      |     ^~~
/tmp/terjekv/tmp-installs/libWallModelledLES-0.6.1-foss-2021b.eb/software/GCCcore/11.2.0/include/c++/11.2.0/bits/stl_algobase.h:300:5: note:   template argument deduction/sub
stitution failed:
../../3rdparty/chromium/third_party/breakpad/breakpad/src/client/linux/handler/exception_handler.cc:141:49: note:   deduced conflicting types for parameter const _Tp (int and
 long int)
  141 |   static const unsigned kSigStackSize = std::max(16384, SIGSTKSZ);
      |                                         ~~~~~~~~^~~~~~~~~~~~~~~~~
In file included from /tmp/terjekv/tmp-installs/libWallModelledLES-0.6.1-foss-2021b.eb/software/GCCcore/11.2.0/include/c++/11.2.0/algorithm:62,
                 from ../../3rdparty/chromium/third_party/breakpad/breakpad/src/client/linux/handler/exception_handler.cc:86:
/tmp/terjekv/tmp-installs/libWallModelledLES-0.6.1-foss-2021b.eb/software/GCCcore/11.2.0/include/c++/11.2.0/bits/stl_algo.h:3461:5: note: candidate: template<class _Tp> const
expr _Tp std::max(std::initializer_list<_Tp>)
 3461 |     max(initializer_list<_Tp> __l)
      |     ^~~
/tmp/terjekv/tmp-installs/libWallModelledLES-0.6.1-foss-2021b.eb/software/GCCcore/11.2.0/include/c++/11.2.0/bits/stl_algo.h:3461:5: note:   template argument deduction/substi
tution failed:
../../3rdparty/chromium/third_party/breakpad/breakpad/src/client/linux/handler/exception_handler.cc:141:49: note:   mismatched types std::initializer_list<_Tp> and int
  141 |   static const unsigned kSigStackSize = std::max(16384, SIGSTKSZ);
      |                                         ~~~~~~~~^~~~~~~~~~~~~~~~~
In file included from /tmp/terjekv/tmp-installs/libWallModelledLES-0.6.1-foss-2021b.eb/software/GCCcore/11.2.0/include/c++/11.2.0/algorithm:62,
                 from ../../3rdparty/chromium/third_party/breakpad/breakpad/src/client/linux/handler/exception_handler.cc:86:
/tmp/terjekv/tmp-installs/libWallModelledLES-0.6.1-foss-2021b.eb/software/GCCcore/11.2.0/include/c++/11.2.0/bits/stl_algo.h:3467:5: note: candidate: template<class _Tp, class
 _Compare> constexpr _Tp std::max(std::initializer_list<_Tp>, _Compare)
 3467 |     max(initializer_list<_Tp> __l, _Compare __comp)
      |     ^~~
/tmp/terjekv/tmp-installs/libWallModelledLES-0.6.1-foss-2021b.eb/software/GCCcore/11.2.0/include/c++/11.2.0/bits/stl_algo.h:3467:5: note:   template argument deduction/substi
tution failed:
../../3rdparty/chromium/third_party/breakpad/breakpad/src/client/linux/handler/exception_handler.cc:141:49: note:   mismatched types std::initializer_list<_Tp> and int
  141 |   static const unsigned kSigStackSize = std::max(16384, SIGSTKSZ);
      |                                         ~~~~~~~~^~~~~~~~~~~~~~~~~
```

### PR DESCRIPTION
**Pull request by terjekv**
(created using `eb --new-pr`)

Fixes #17463

### CODE REVIEW

**Review by Micket — APPROVED** [review]
lgtm

**Review by SebastianAchilles — COMMENTED** [review]
I think the patch in this PR and the patch https://github.com/easybuilders/easybuild-easyconfigs/blob/develop/easybuild/easyconfigs/q/Qt5/Qt5-5.15.2_fix-qtwebengine-breakpad-glibc-2.34.patch are fixing the same issues. However the later one was only added to the easyconfig `Qt5-5.15.5-GCCcore-11.3.0.eb` (https://github.com/easybuilders/easybuild-easyconfigs/blob/develop/easybuild/easyconfigs/q/Qt5/Qt5-5.15.5-GCCcore-11.3.0.eb#L24) but not to `Qt5-5.15.2-GCCcore-11.2.0.eb`.
In case `Qt5-5.15.2_fix-qtwebengine-breakpad-glibc-2.34.patch` works for `Qt5-5.15.2-GCCcore-11.2.0.eb` as well, I would prefer to use this patch here as well.

**Comment by Micket** [comment]
I did work.

I see another patch as well which also fixes the same type of issue, but despite it being named Qt5-5.15.2 it's actually for 5.15.5, and we annoyingly need to backport the patch.. which i'm now not sure what to call,  ugh

**Comment by terjekv** [comment]
Gah, I looked for the same fix, and didn't find the one solving it slightly differently. Grrr. We should stick with the one already there, for sure. Sorry. :(

**Comment by Micket** [comment]
If "backported" the other patch as well (as far as i can tell, that patch should also be necessary?) I can push those changes to this PR if you want

**Comment by terjekv** [comment]
That works for me, thanks!

**Comment by SebastianAchilles** [comment]
I am seeing this:
```
Can't determine patch level for patch /tmp/eb-39sevvhn/files_pr17464/q/Qt5/Qt5-5.15.2b_fix-qtwebengine-abs
eil-cpp-glibc-2.34.patch from directory /dev/shm/easybuilder/Qt5/5.15.2/GCCcore-11.2.0/qt-everywhere-src-5.15.2
```
I will adjust the path in the patch.

**Comment by SebastianAchilles** [comment]
I will trigger test reports on three systems:
- `generoso` / `jsc-zen2`: they are using an older `glibc` version 2.28 and did not run into the issue before,
- Ubuntu 22.10 VM: this is using a newer `glibc` 2.36 and did run into the issue. Failing test report from before can be found here: https://gist.github.com/SebastianAchilles/81efd41e8285b1ec8bdfc8e63b0ca3a9

**Comment by SebastianAchilles** [comment]
@boegelbot please test @ jsc-zen2
CORE_CNT=16
EB_ARGS="--installpath /tmp/$USER/pr17464"

**Comment by SebastianAchilles** [comment]
Test report by @sebastianachilles
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
zen2-ubuntu-2210 - Linux Ubuntu 22.10 (Kinetic Kudu), x86_64, AMD EPYC 7452 32-Core Processor (zen2), Python 3.10.7
See https://gist.github.com/88b40e7d2338603a9a3f85b00ed4d9ac for a full test report.

**Comment by SebastianAchilles** [comment]
@boegelbot please test @ generoso
CORE_CNT=16
EB_ARGS="--installpath /tmp/$USER/pr17464"

**Review by SebastianAchilles — APPROVED** [review]
lgtm

**Comment by SebastianAchilles** [comment]
Going in, thanks @terjekv!

**Pull request merged**
