### PR TITLE
{data}[foss/2019b] netcdf4-python v1.5.3 w/ Python 3.7.4 and Python 2.7.16

### PR DESCRIPTION
**Pull request by lexming**
(created using `eb --new-pr`)

netcdf4-python v1.5.3 supports both Python 2 and 3, but due to the dependency on SciPy-bundle it is not possible to use `multi_deps`.

### CODE REVIEW

**Comment by lexming** [comment]
Test report by @lexming
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in this PR)
node377.hydra.os - Linux centos linux 7.7.1908, Intel(R) Xeon(R) Gold 6148 CPU @ 2.40GHz, Python 2.7.5
See https://gist.github.com/702a6db4cb8996f45dd2e013e7d80347 for a full test report.

**Comment by Micket** [comment]
@lexming Looks like another PR already created intel and foss version for python 3.7.4 so there is a conflict here now.
I think those in develop right now specify a pointless source_urls. Should we update this PR so that they are all consistent?

**Comment by lexming** [comment]
Test report by @lexming
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in this PR)
node125.hydra.os - Linux centos linux 7.7.1908, x86_64, Intel(R) Xeon(R) CPU E5-2680 v2 @ 2.80GHz, Python 2.7.5
See https://gist.github.com/fd6f51bf2523da20bf477372f3e121c9 for a full test report.

**Comment by lexming** [comment]
Test report by @lexming
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in this PR)
node378.hydra.os - Linux centos linux 7.7.1908, x86_64, Intel(R) Xeon(R) Gold 6148 CPU @ 2.40GHz, Python 2.7.5
See https://gist.github.com/1f2ad8a928f32b9f1cd56f5a457814ce for a full test report.

**Comment by lexming** [comment]
@Micket I fixed the conflicts and, as suggested, made a little bit of cleanup in the existing easyconfig.

**Comment by boegel** [comment]
@boegelbot please test @ generoso

**Review by boegel — APPROVED** [review]
lgtm

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in total)
node3545.doduo.os - Linux RHEL 8.2, x86_64, AMD EPYC 7552 48-Core Processor (zen2), Python 3.6.8
See https://gist.github.com/487aa0c861ae636cfc871d8ace6f0279 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in total)
node2608.swalot.os - Linux centos linux 7.9.2009, x86_64, Intel(R) Xeon(R) CPU E5-2660 v3 @ 2.60GHz (haswell), Python 3.6.8
See https://gist.github.com/bc4af8240970a9bef6cea1ebe0cdac0b for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in total)
node3106.skitty.os - Linux centos linux 7.9.2009, x86_64, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz, Python 3.6.8
See https://gist.github.com/cfdb4e94b8e2e1fbbb4dac62e4c38cd1 for a full test report.

**Comment by boegel** [comment]
Going in, thanks @lexming!

**Pull request merged**
