### PR TITLE
{data}[GCCcore/8.3.0] openpyxl v3.0.3 w/ Python 3.7.4

### PR DESCRIPTION
**Pull request by crubb**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by crubb** [comment]
Test report by @crubb
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
radbert - Linux ubuntu 18.04, Intel(R) Xeon(R) CPU E5-2687W v4 @ 3.00GHz, Python 2.7.17
See https://gist.github.com/65185830c46613d6c6f40edf28d1529a for a full test report.

**Comment by crubb** [comment]
Test report by @crubb
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
radbert - Linux ubuntu 18.04, Intel(R) Xeon(R) CPU E5-2687W v4 @ 3.00GHz, Python 2.7.17
See https://gist.github.com/7d38892fb54e3e8b3f400a1e50e93acb for a full test report.

**Comment by crubb** [comment]
Test report by @crubb
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
radbert - Linux ubuntu 18.04, Intel(R) Xeon(R) CPU E5-2687W v4 @ 3.00GHz, Python 2.7.17
See https://gist.github.com/a779041758528e43c05b9c1ca6577c94 for a full test report.

**Comment by Micket** [comment]
Test report by @Micket
**SUCCESS**
Build succeeded for 3 out of 3 (1 easyconfigs in this PR)
hebbe-c1 - Linux centos linux 7.7.1908, Intel Core Processor (Haswell, no TSX), Python 2.7.5
See https://gist.github.com/9f608340af331bae8093b81679be3941 for a full test report.

**Comment by Micket** [comment]
Going in, thanks @crubb!

**Pull request merged**
