### PR TITLE
{math}[gompi/2022b] KaHIP v3.14

### PR DESCRIPTION
**Pull request by furstj**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by terjekv** [comment]
Test report by @terjekv
**SUCCESS**
Build succeeded for 40 out of 40 (1 easyconfigs in total)
ninhursaga.uio.no - Linux RHEL 9.1 (Plow), x86_64, Intel(R) Xeon(R) Silver 4216 CPU @ 2.10GHz, Python 3.9.14
See https://gist.github.com/87b04df005e61b1fdb0d2bed46643de1 for a full test report.

**Comment by jfgrimm** [comment]
@boegelbot please test @ generoso

**Comment by jfgrimm** [comment]
@boegelbot please test @ jsc-zen2

**Review by jfgrimm — APPROVED** [review]
lgtm

**Comment by jfgrimm** [comment]
Going in, thanks @furstj!

**Pull request merged**
