### PR TITLE
{vis}[GCCcore/13.2.0] pixman v0.42.2, GLib v2.78.1, cairo v1.18.0, ...

### PR DESCRIPTION
**Pull request by Micket**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by Micket** [comment]
Test report by @Micket
**SUCCESS**
Build succeeded for 4 out of 4 (4 easyconfigs in total)
vera-c1 - Linux Rocky Linux 8.8, x86_64, Intel Xeon Processor (Skylake), Python 3.6.8
See https://gist.github.com/Micket/302329da3d236559fe0802c84e1cd115 for a full test report.

**Comment by Micket** [comment]
@boegelbot please test @ generoso

**Comment by Micket** [comment]
@boegelbot please test @ jsc-zen2

**Comment by bedroge** [comment]
Test report by @bedroge
**FAILED**
Build succeeded for 15 out of 20 (4 easyconfigs in total)
interactive1 - Linux Rocky Linux 8.8, x86_64, AMD EPYC-Milan Processor (zen2), Python 3.6.8
See https://gist.github.com/bedroge/bd62def7e4a9641f2b339d6ac0bb6235 for a full test report.

**Comment by Micket** [comment]
> I can not open file /etc/fstab for reading: No such file or directory at /home1/p251204/easybuildinstall/software/Perl-bundle-CPAN/5.38.0-GCCcore-13.2.0/lib/perl5/site_perl/5.38.0/Test/Sys/Info/Driver.pm line 91.

so, liike like a test we should disable in perl. but also, you don't have a /etc/fstab???

**Comment by bedroge** [comment]
> > I can not open file /etc/fstab for reading: No such file or directory at /home1/p251204/easybuildinstall/software/Perl-bundle-CPAN/5.38.0-GCCcore-13.2.0/lib/perl5/site_perl/5.38.0/Test/Sys/Info/Driver.pm line 91.
> 
> so, liike like a test we should disable in perl. but also, you don't have a /etc/fstab???

This was in an Apptainer container, which apparently doesn't have `/etc/fstab`.

**Review by branfosj — APPROVED** [review]

**Comment by SebastianAchilles** [comment]
> > > I can not open file /etc/fstab for reading: No such file or directory at /home1/p251204/easybuildinstall/software/Perl-bundle-CPAN/5.38.0-GCCcore-13.2.0/lib/perl5/site_perl/5.38.0/Test/Sys/Info/Driver.pm line 91.
> > 
> > 
> > so, liike like a test we should disable in perl. but also, you don't have a /etc/fstab???
> 
> This was in an Apptainer container, which apparently doesn't have `/etc/fstab`.

I have seen this before, as I am also using containers to produce test reports. If I remember correctly I used `touch /etc/fstab` inside the container to make the Perl test pass.

**Comment by SebastianAchilles** [comment]
Test report by @sebastianachilles
**SUCCESS**
Build succeeded for 4 out of 4 (4 easyconfigs in total)
zen2-ubuntu-2310 - Linux Ubuntu 23.10 (Mantic Minotaur), x86_64, AMD EPYC 7452 32-Core Processor (zen2), Python 3.11.6
See https://gist.github.com/SebastianAchilles/6454797a9cbcb2e5be289983a2c37c4c for a full test report.

**Comment by branfosj** [comment]
Test report by @branfosj
**SUCCESS**
Build succeeded for 18 out of 18 (4 easyconfigs in total)
bear-pg0105u03a - Linux RHEL 8.6, x86_64, Intel(R) Xeon(R) Platinum 8360Y CPU @ 2.40GHz (icelake), Python 3.6.8
See https://gist.github.com/branfosj/38f4b5637efbf4b684273b3679a1daf9 for a full test report.

**Comment by branfosj** [comment]
Going in, thanks @Micket!

**Pull request merged**
