### PR TITLE
{tools}[foss/2017b,intel/2017b] IRkernel v0.8.15

### PR DESCRIPTION
**Pull request by vanzod**
Requires:
~~#8049~~ (IPython)

### CODE REVIEW

**Comment by vanzod** [comment]
Test report by @vanzod
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in this PR)
cermis - Linux debian 9.8, Intel(R) Xeon(R) CPU           X5670  @ 2.93GHz, Python 2.7.13
See https://gist.github.com/7c8e9938d7e124c0c9dfb359021906b0 for a full test report.

**Comment by migueldiascosta** [comment]
closing and reopening to trigger travis

**Comment by vanzod** [comment]
@migueldiascosta Good to go?

**Comment by migueldiascosta** [comment]
Test report by @migueldiascosta
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in this PR)
grc-cluster1 - Linux centos 6.10, Intel(R) Xeon(R) CPU E5-2640 0 @ 2.50GHz, Python 2.7.14
See https://gist.github.com/72eebf539437fc5fe7c6eab988473079 for a full test report.

**Comment by migueldiascosta** [comment]
Going in, thanks @vanzod!

**Pull request merged**
