### PR TITLE
Add GenABEL to R-bundle-Bioconductor

### PR DESCRIPTION
**Pull request by verdurin**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by boegel** [comment]
@boegelbot please test @ generoso
EB_ARGS="--skip"

**Comment by Micket** [comment]
@boegel How is this order dependency going to affect your changes to build extensions in parallel?

**Comment by boegel** [comment]
> @boegel How is this order dependency going to affect your changes to build extensions in parallel?

It won't. The order in `exts_list` is largely irrelevant when the R extensions are installed in parallel, because the installation of E is only started when the required extensions for E are installed already. See the `required_deps` method in https://github.com/easybuilders/easybuild-easyblocks/pull/2408 (which should be reworked into a standalone function, so it can be unit tested and used by other easyblocks).

**Comment by boegel** [comment]
@lexming Any idea what caused this?

```
** byte-compile and prepare package for lazy loading
sh: line 1:  3339 Killed                  R_TESTS= '/user/brussel/101/vsc10122/.local/easybuild-skylake/software/R/4.0.3-foss-2020b/lib64/R/bin/R' --no-save --no-restore --no-echo 2>&1 < '/user/brussel/101/vsc10122/.local/easybuild-skylake/tmp/eb-S60DbH/RtmpjfMv1K/filec7565034ebf'
ERROR: lazy loading failed for package conumee
```

**Comment by boegel** [comment]
@boegelbot please test @ generoso
EB_ARGS="--skip"

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
node3153.skitty.os - Linux centos linux 7.9.2009, x86_64, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz, Python 3.6.8
See https://gist.github.com/c8ac6c160f6b28151bac4136565f5455 for a full test report.

**Review by boegel — APPROVED** [review]
lgtm

**Comment by boegel** [comment]
Going in, thanks @verdurin!

**Pull request merged**
