### PR TITLE
{bio}[foss/2021a] ConnectomeWorkbench v1.5.0

### PR DESCRIPTION
**Pull request by jose-d**
(created using `eb --new-pr`)

new workbench build with recent toolchain, I used previous version a an template.

on top of older easyconfig "template", I added make `test step`, seems to be ok:

```Running tests...
/sw/apps/2021a/software/CMake/3.20.1-GCCcore-10.3.0/bin/ctest --force-new-ctest-process 
Test project /sw/apps/2021a/build/ConnectomeWorkbench/1.5.0/foss-2021a/easybuild_obj
      Start  1: command_help
 1/11 Test  #1: command_help .....................   Passed    2.29 sec
      Start  2: timer
 2/11 Test  #2: timer ............................   Passed    1.16 sec
      Start  3: progress
 3/11 Test  #3: progress .........................   Passed    0.13 sec
      Start  4: volumefile
 4/11 Test  #4: volumefile .......................   Passed    0.09 sec
      Start  5: heap
 5/11 Test  #5: heap .............................   Passed    0.09 sec
      Start  6: pointer
 6/11 Test  #6: pointer ..........................   Passed    0.10 sec
      Start  7: statistics
 7/11 Test  #7: statistics .......................   Passed    0.22 sec
      Start  8: quaternion
 8/11 Test  #8: quaternion .......................   Passed    0.09 sec
      Start  9: mathexpression
 9/11 Test  #9: mathexpression ...................   Passed    0.10 sec
      Start 10: lookup
10/11 Test #10: lookup ...........................   Passed    0.09 sec
      Start 11: dotsimd
11/11 Test #11: dotsimd ..........................   Passed    0.11 sec

100% tests passed, 0 tests failed out of 11

Total Test time (real) =   4.55 sec
```

### CODE REVIEW

**Comment by jose-d** [comment]
Test report by @jose-d
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
sup200.ad.nudz.cz - Linux UNKNOWN UNKNOWN, x86_64, Intel(R) Xeon(R) Gold 6244 CPU @ 3.60GHz, 1 x NVIDIA NVIDIA A100-PCIE-40GB, 470.94, Python 3.6.8
See https://gist.github.com/5a086e56443e11d66c93d09a8860d772 for a full test report.

**Comment by jose-d** [comment]
Test report by @jose-d
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
sup200.ad.nudz.cz - Linux UNKNOWN UNKNOWN, x86_64, Intel(R) Xeon(R) Gold 6244 CPU @ 3.60GHz, 1 x NVIDIA NVIDIA A100-PCIE-40GB, 470.94, Python 3.6.8
See https://gist.github.com/b3a8be9734684263806fee4109232afe for a full test report.

**Comment by lexming** [comment]
@boegelbot: please test @ generoso

**Review by lexming — DISMISSED** [review]
@jose-d thanks for your contribution. I just made a very minor change removing the release build type option. That is default with the `CMakeMake` easyblock.

LGTM

**Comment by lexming** [comment]
@boegelbot: please test @ generoso

**Comment by lexming** [comment]
Test report by @lexming
**FAILED**
Build succeeded for 0 out of 1 (1 easyconfigs in total)
node316.hydra.os - Linux centos linux 7.9.2009, x86_64, Intel(R) Xeon(R) Gold 6148 CPU @ 2.40GHz, Python 2.7.5
See https://gist.github.com/603986386a55615bb244c8eec272abf0 for a full test report.

**Comment by lexming** [comment]
@boegelbot: please test @ generoso

**Comment by lexming** [comment]
@boegelbot: please test @ generoso

**Comment by lexming** [comment]
Test report by @lexming
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
node301.hydra.os - Linux centos linux 7.9.2009, x86_64, Intel(R) Xeon(R) Gold 6148 CPU @ 2.40GHz, Python 2.7.5
See https://gist.github.com/697fe77f3a7a3c6baf26a8d6ee8b628b for a full test report.

**Review by lexming — APPROVED** [review]
@jose-d  after further inspection, I moved this easyconfig down to `GCCcore` because Connectome Workbench does not need MPI or BLAS/LAPACK. 

LGTM

**Comment by lexming** [comment]
Going in, thanks @jose-d !

**Pull request merged**
