### PR TITLE
Fix to make sure symlinks in bin are not broken

### PR DESCRIPTION
**Pull request by sassy-crick**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by boegel** [comment]
@sassy-crick You're adding a new easyconfig here, rather than fixing an existing one like the PR title suggests.

Do you mind pointing out what should be fixed in the existing `KronaTools` easyconfig(s)?

**Comment by sassy-crick** [comment]
Updated the GCC version to 8.2.0 for KronaTools version 2.7.1 so it is really a bug fix as intended and consequently I removed the KronaTools-2.7.1-GCCcore-7.3.0.eb build file. 
Added KronaTools-2.7-GCCcore-7.3.0.eb as a bug fix as well. 
Note: KronaTools-2.7-GCCcore-8.2.0.eb is handled at PR #8514

**Comment by vanzod** [comment]
Test report by @vanzod
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in this PR)
cermis - Linux debian 9.9, Intel(R) Xeon(R) CPU           X5670  @ 2.93GHz, Python 2.7.13
See https://gist.github.com/2088578bc1540b7e5bce5e03d9da5bf1 for a full test report.

**Comment by vanzod** [comment]
Going in, thanks @sassy-crick!

**Pull request merged**
