### PR TITLE
consistently use NanoFilt capitalisation

### PR DESCRIPTION
**Pull request by branfosj**
`NanoFilt` capitalisation looks right to me.

for #11824

### CODE REVIEW

**Comment by branfosj** [comment]
@boegelbot please test @ generoso

**Review by Micket — APPROVED** [review]
lgtm

**Comment by Micket** [comment]
Do we care to test build these? toolchains are older than what i have in my test tree so i don't wanna

**Comment by branfosj** [comment]
> Do we care to test build these? toolchains are older than what i have in my test tree so i don't wanna

I've set a build off and will see how it goes. The starting point is "0 out of 72 easyconfigs done", so not as bad as I feared. However, we'll have to see if I can build all the dependencies in these older toolchains.

**Comment by verdurin** [comment]
Test report by @verdurin
**FAILED**
Build succeeded for 8 out of 16 (4 easyconfigs in total)
easybuild-c7.novalocal - Linux CentOS Linux 7.9.2009, x86_64, Intel Xeon Processor (Skylake, IBRS), Python 3.6.8
See https://gist.github.com/a6b58379e5bf80410d2d46afec1ddbaa for a full test report.

**Comment by branfosj** [comment]
Test report by @branfosj
**SUCCESS**
Build succeeded for 4 out of 4 (4 easyconfigs in total)
bear-pg0211u08b.bear.cluster - Linux RHEL 8.6, x86_64, Intel(R) Xeon(R) Gold 6248 CPU @ 2.50GHz (cascadelake), Python 3.6.8
See https://gist.github.com/471c61356c50b39b2e238faac1a6830d for a full test report.

**Comment by Micket** [comment]
Good enough for me!

**Pull request merged**
