### PR TITLE
{lang}[foss/2020a] RStudio-Server v1.4.1103 - WIP

### PR DESCRIPTION
**Pull request by verdurin**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by verdurin** [comment]
Test report by @verdurin
**FAILED**
Build succeeded for 1 out of 2 (1 easyconfigs in total)
nuc.lan - Linux Fedora 32, x86_64, Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz, Python 3.8.7
See https://gist.github.com/34bb2410807fe9fbae60590f1d5f37bd for a full test report.

**Comment by branfosj** [comment]
I took a quick look at this last week, but I'd failed to complete the install.

I've PR-ed the SOCI ec that I made in https://github.com/easybuilders/easybuild-easyconfigs/pull/12045 but RStudio-Server fails later on with a problem due to `nodejs` and a hard-coded path that I've not had time to investigate.

RStudio-Server addition:
```
configopts += "-DSOCI_CORE_LIB=$EBROOTSOCI/lib/libsoci_core.a "
configopts += "-DSOCI_POSTGRESQL_LIB=$EBROOTSOCI/lib/libsoci_postgresql.a "
configopts += "-DSOCI_SQLITE_LIB=$EBROOTSOCI/lib/libsoci_sqlite3.a "
```

**Comment by verdurin** [comment]
@branfosj yes, I think it needs something Postgres-related too.

**Comment by benczaja** [comment]
@branfosj  I created a pr for the foss-2021a version of this easyconfig. I had a similar issue with the nodejs paths. the install-npm-dependencies solved it for me. maybe you can see if #13763 will help.

**Review by jfgrimm — COMMENTED** [review]
As decided in issue #16330, we have deprecated the use of `True` to signify a system-toolchain dependency (#16384), in favour of the more intuitive `SYSTEM` template constant. Due to the change in the test suite, please run `eb --sync-pr-with-develop 12044` and update the PR to use `SYSTEM` instead.

**Comment by branfosj** [comment]
As this PR is WIP or draft and has not been updated in over a year I have closed it. If you work on this again then please reopen the PR.

**Pull request closed without merging**
