### PR TITLE
{devel}[system] ReFrame v3.5.0

### PR DESCRIPTION
**Pull request by teojgo**
Closes https://github.com/eth-cscs/reframe/issues/1853

### CODE REVIEW

**Comment by branfosj** [comment]
@boegelbot please test @ generoso

**Review by branfosj — APPROVED** [review]
lgtm

**Comment by branfosj** [comment]
Going in, thanks @teojgo!

**Comment by migueldiascosta** [comment]
Test report by @migueldiascosta
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in total)
sms - Linux centos linux 7.6.1810, x86_64, AMD EPYC 7601 32-Core Processor (zen) (zen), Python 2.7.5
See https://gist.github.com/f7ce195142d0abcef62d6149c1df5e80 for a full test report.

**Pull request merged**
