### PR TITLE
fix incorrect module load message and update morphology plugin of ImageJ 1.51k

### PR DESCRIPTION
**Pull request by boegel**
(created using `eb --new-pr`)
cfr. https://github.com/easybuilders/easybuild-easyconfigs/pull/9197#issuecomment-546434401

### CODE REVIEW

**Comment by lexming** [comment]
Test report by @lexming
**FAILED**
Build succeeded for 2 out of 3 (1 easyconfigs in total)
node300.hydra.os - Linux centos linux 7.9.2009, x86_64, Intel(R) Xeon(R) Gold 6148 CPU @ 2.40GHz, Python 2.7.5
See https://gist.github.com/c7cb681ed0dcea00f5f52c14c9105efb for a full test report.

**Comment by branfosj** [comment]
> @boegel The morphology plugin from `http://www.mecourse.com/landinig/software/` does not exist any more. Should we update this easyconfig to use the same morphology plugin as `ImageJ-1.52q-Java-1.8.eb`? At first sight it should work with this version of ImageJ as well.

That makes sense to me, but with the suggested alteration I've put in https://github.com/easybuilders/easybuild-easyconfigs/pull/14163 to allow us to have it 'versioned' by using the git hash.

**Comment by boegel** [comment]
@boegelbot please test @ generoso

**Comment by lexming** [comment]
Test report by @lexming
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
node300.hydra.os - Linux centos linux 7.9.2009, x86_64, Intel(R) Xeon(R) Gold 6148 CPU @ 2.40GHz, Python 2.7.5
See https://gist.github.com/37d88a87f0efaaaef79b687c593ffc7c for a full test report.

**Comment by lexming** [comment]
Going in, thanks @boegel !

**Pull request merged**
