### PR TITLE
Update loompy builddep - use poetry 1.5.1 to not have a conflict with other modules

### PR DESCRIPTION
**Pull request by pavelToman**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by pavelToman** [comment]
@boegelbot please test @ generoso

**Comment by pavelToman** [comment]
@boegelbot please test @ jsc-zen3

**Review by casparvl — COMMENTED** [review]
While I'm happy to merge this, I don't really understand the issue this would solve. Since poetry is only a build dependency, it will never conflict with other modules, as it won't be loaded at runtime. Using multiple versions as buildtime dependencies is therefore allowed by our CI. Am I misssing something here?

**Comment by casparvl** [comment]
Test report by @casparvl
**SUCCESS**
Build succeeded for 4 out of 4 (1 easyconfigs in total)
tcn1.local.snellius.surf.nl - Linux RHEL 8.6, x86_64, AMD EPYC 7H12 64-Core Processor, Python 3.6.8
See https://gist.github.com/casparvl/f353a60b92bd35134469152b2e724ce4 for a full test report.

**Comment by pavelToman** [comment]
> While I'm happy to merge this, I don't really understand the issue this would solve. Since poetry is only a build dependency, it will never conflict with other modules, as it won't be loaded at runtime. Using multiple versions as buildtime dependencies is therefore allowed by our CI. Am I misssing something here?

I try to solve this problem: https://github.com/easybuilders/easybuild-easyconfigs/pull/20115#issuecomment-2000369854
Do you think it will not fix it or is there a better solution?

**Comment by casparvl** [comment]
I indeed think it won't solve it, the version of `poetry` used for `loompy` will not be loaded during the build of #20115 , since it is a build dependency, it is _only_ loaded during build time when building `loompy` itself.

I'll comment in the other ticket, but I'll close this PR as I don't think this is the solution (if needed, we can always reopen again).

**Pull request closed without merging**
