### PR TITLE
add kedd extensions to R 3.6.0 easyconfigs

### PR DESCRIPTION
**Pull request by boegel**

### CODE REVIEW

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
node3303.joltik.os - Linux centos linux 7.7.1908, Intel(R) Xeon(R) Gold 6242 CPU @ 2.80GHz, Python 2.7.5
See https://gist.github.com/dfcd0eb96bdf22064bc2aa176ca8e29c for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in this PR)
node2449.golett.os - Linux centos linux 7.7.1908, Intel(R) Xeon(R) CPU E5-2680 v3 @ 2.50GHz, Python 2.7.5
See https://gist.github.com/25b7a02fe0f15b221824d43edc221d8e for a full test report.

**Comment by boegel** [comment]
Test reports are split across two different systems since the R 3.6.0 easyconfig using `fosscuda` needs to be tested on a GPU system, but all easyconfigs are covered now by the test reports...

**Comment by Micket** [comment]
Going in, thanks @boegel!

**Comment by smoors** [comment]
Test report by @smoors
**FAILED**
Build succeeded for 2 out of 3 (3 easyconfigs in this PR)
node354.hydra.os - Linux centos linux 7.6.1810, Intel(R) Xeon(R) Gold 6148 CPU @ 2.40GHz, Python 2.7.5
See https://gist.github.com/a4937c13ffdef59598d146571f3ad021 for a full test report.

**Pull request merged**
