### PR TITLE
add patch for FFTW 3.3.8 to avoid use of -no-gcc when building with Intel compilers, to fix installation on CentOS 8 (cfr. #10932)

### PR DESCRIPTION
**Pull request by boegel**
(created using `eb --new-pr`)

cfr. #10932

### CODE REVIEW

**Comment by boegel** [comment]
@boegelbot please test @ generoso

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 3 out of 3 (3 easyconfigs in this PR)
node3401.kirlia.os - Linux centos linux 7.8.2003, x86_64, Intel(R) Xeon(R) Gold 6240 CPU @ 2.60GHz (cascadelake), Python 2.7.5
See https://gist.github.com/453cc08c054917e6c3e52f58f73cfc6c for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 3 out of 3 (3 easyconfigs in this PR)
node3116.skitty.os - Linux centos linux 7.8.2003, x86_64, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz (skylake_avx512), Python 3.6.8
See https://gist.github.com/c3aa7921de9f0cebf5254d1709aae337 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 3 out of 3 (3 easyconfigs in this PR)
node2402.golett.os - Linux centos linux 7.8.2003, x86_64, Intel(R) Xeon(R) CPU E5-2680 v3 @ 2.50GHz (haswell), Python 2.7.5
See https://gist.github.com/dc6983bbfb0809f01b5fb921978e01bc for a full test report.

**Comment by casparvl** [comment]
The patch looks fine to me. Also, at IDRIS, they already removed the `-no-gcc` some time ago and have no issues (according to https://github.com/FFTW/fftw3/issues/184), so that seems to support this approach.

One question: on the same issue, it was mentioned that failures occured regardless of Intel Compiler version, as long as the GCC in the path was <= 6.5.0. There are a number of EasyConfigs that use `FFTW-3.3.8` with the `2018b` toolchain generation. Did you try those on CentOS 8.2? Do they work?

And, does this also apply to older `FFTW` versions? I'm not saying we should backport everything, everywhere. But maybe we can log it in your issue (along with the ones we DID patch, for clarity) https://github.com/easybuilders/easybuild-easyconfigs/issues/10932

**Comment by casparvl** [comment]
> but I'm not sure if it's worth the trouble to try and fix the installation of older FFTW versions too?

No, I agree. And with your argument that `glibc` also breaks for those older toolchains, there's no use fixing the `FFTW`s anyway.

**Comment by casparvl** [comment]
Test report by @casparvl
**FAILED**
Build succeeded for 0 out of 1 (1 easyconfigs in this PR)
tcn900.bullx - Linux RHEL 7.7, x86_64, Intel(R) Xeon(R) CPU E5-2690 v3 @ 2.60GHz, Python 2.7.5
See https://gist.github.com/45d4a862974ad5acd657e13070d81a2e for a full test report.

**Comment by casparvl** [comment]
Test report by @casparvl
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
software1.lisa.surfsara.nl - Linux debian 10.5, x86_64, Intel(R) Xeon(R) Silver 4110 CPU @ 2.10GHz, Python 2.7.16
See https://gist.github.com/c6ae0ac8a8646ab554a60acd61051b82 for a full test report.

**Comment by casparvl** [comment]
Test report by @casparvl
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
tcn900.bullx - Linux RHEL 7.7, x86_64, Intel(R) Xeon(R) CPU E5-2690 v3 @ 2.60GHz, Python 2.7.5
See https://gist.github.com/4c727e68cbb02fc3d56e4b7f27125c87 for a full test report.

**Comment by casparvl** [comment]
Failing test was because of the fact that FFTW doesn't like an optarch that doesn't match the AVX capability of the host. That has been a (minor) issue for a long time; not relevant in the context of this PR. Time to merge! Thanks @boegel

**Comment by klust** [comment]
The patch does not only solve problems on CentOS 8. Compiling FFTW 3.3.8 with Intel 2020 update 2 also failed on CentOS 7.8 (where update 1 still worked) but at a different point then on CentOS 8. However, this patch also solved that problem.

**Pull request merged**
