### PR TITLE
Fix Highway 1.0.3 on some systems by disabling `AVX3_DL`

### PR DESCRIPTION
**Pull request by Flamefire**
(created using `eb --new-pr`)

Using AVX3_DL in the baseline doesn't work in 1.0.3 causing the build to fail with
> #error "Logic error: best baseline should be included in dynamic targets"

This is caused by using a wrong defined and fixed by
https://github.com/google/highway/commit/f0f688b6d6d1ec94489cc989ccb9729b0342aa58
However that the leads to a test failure:
> HwyConvertTestGroup/HwyConvertTest.TestAllTruncate/AVX3_DL
> u8x16 expect [0+ ->]:
>   0x00,0x01,0x02,0x03,0x04,0x05,0x06,
> u8x16 actual [0+ ->]:
>   0x00,0x1A,0x02,0x1A,0x04,0x1A,0x06,
> Abort at .../hwy/tests/convert_test.cc:386: AVX3_DL, u8x16 lane 1 mismatch: expected '0x01', got '0x1A'.

Hence AVX3_DL in 1.0.3 seems to be broken and must not be used.
This patch disables it by making the condition always false.

**Note**: Strange thing here is that this seems to have worked at some point and broke after some change possibly unrelated to EasyBuild. I guess some change in libc or so that enabled the missing defines that made Highway enable AVX3_DL

### CODE REVIEW

**Comment by Flamefire** [comment]
Test report by @Flamefire
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
n1441 - Linux RHEL 8.7 (Ootpa), x86_64, Intel(R) Xeon(R) Platinum 8470 (icelake), Python 3.8.13
See https://gist.github.com/Flamefire/de041d737e320ef786acf5ca187015a6 for a full test report.

**Comment by Flamefire** [comment]
Test report by @Flamefire
**SUCCESS**
Build succeeded for 2 out of 2 (1 easyconfigs in total)
i8022 - Linux Rocky Linux 8.7 (Green Obsidian), x86_64, AMD EPYC 7352 24-Core Processor (zen2), 8 x NVIDIA NVIDIA A100-SXM4-40GB, 545.23.08, Python 3.8.13
See https://gist.github.com/Flamefire/a622a2295161cd693048049b4bbb796d for a full test report.

**Comment by Flamefire** [comment]
Test report by @Flamefire
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in total)
n1441 - Linux RHEL 8.7 (Ootpa), x86_64, Intel(R) Xeon(R) Platinum 8470 (icelake), Python 3.8.13
See https://gist.github.com/Flamefire/393a8b3181bb8f557d7880a7a8e53937 for a full test report.

**Comment by Flamefire** [comment]
Test report by @Flamefire
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in total)
i8022 - Linux Rocky Linux 8.7 (Green Obsidian), x86_64, AMD EPYC 7352 24-Core Processor (zen2), 8 x NVIDIA NVIDIA A100-SXM4-40GB, 545.23.08, Python 3.8.13
See https://gist.github.com/Flamefire/e62402e8e6cd36769ebd8f29079dbb0f for a full test report.

**Review by Micket — APPROVED** [review]
lgtm

**Comment by verdurin** [comment]
Test report by @verdurin
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in total)
easybuild-c7.novalocal - Linux CentOS Linux 7.9.2009, x86_64, Intel Xeon Processor (Skylake, IBRS), Python 3.6.8
See https://gist.github.com/verdurin/f77ce85ceacc35d8ca2c89fac50c4214 for a full test report.

**Comment by verdurin** [comment]
Going in, thanks @Flamefire!

**Comment by Flamefire** [comment]
@verdurin This merge didn't go through it seems

**Comment by Flamefire** [comment]
@verdurin Can you redo the merge?

**Review by boegel — APPROVED** [review]
lgtm

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in total)
node3117.skitty.os - Linux RHEL 8.8, x86_64, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz, Python 3.6.8
See https://gist.github.com/boegel/f8623b8054ca5ce123b03b5f8ff44460 for a full test report.

**Comment by boegel** [comment]
Going in, thanks @Flamefire!

**Pull request merged**
