### PR TITLE
{bio}[foss/2019b] Kent_tools v401 (built from source)

### PR DESCRIPTION
**Pull request by boegel**
(created using `eb --new-pr`)
requires ~~#11061~~ (MariaDB)

### CODE REVIEW

**Comment by boegel** [comment]
@boegelbot please test @ generoso

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
node3136.skitty.os - Linux centos linux 7.8.2003, x86_64, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz (skylake_avx512), Python 3.6.8
See https://gist.github.com/3293a802a317f863fa280b140fa53ed9 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
node3411.kirlia.os - Linux centos linux 7.8.2003, x86_64, Intel(R) Xeon(R) Gold 6240 CPU @ 2.60GHz (cascadelake), Python 2.7.5
See https://gist.github.com/5996311e5164a8e1fa6d093d00624760 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
node2611.swalot.os - Linux centos linux 7.8.2003, x86_64, Intel(R) Xeon(R) CPU E5-2660 v3 @ 2.60GHz (haswell), Python 2.7.5
See https://gist.github.com/da8b68dfc2c6a3832396de9494fb1a88 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
gligar04.gastly.os - Linux centos linux 7.8.2003, x86_64, Intel(R) Xeon(R) Gold 6130 CPU @ 2.10GHz (skylake_avx512), Python 2.7.5
See https://gist.github.com/1213169c01f1f7655883a13dd7f31c0a for a full test report.

**Comment by zao** [comment]
Test report by @zao
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
freja - Linux ubuntu 18.04, x86_64, Intel(R) Core(TM) i7-8700K CPU @ 3.70GHz, Python 2.7.17
See https://gist.github.com/d274a4688065e265cb6b3d30715b0fa0 for a full test report.

**Comment by verdurin** [comment]
Test report by @verdurin
**FAILED**
Build succeeded for 6 out of 7 (1 easyconfigs in this PR)
easybuild.novalocal - Linux centos linux 7.8.2003, x86_64, Intel Xeon Processor (Skylake, IBRS), Python 2.7.5
See https://gist.github.com/8f13c29e1a8c1aaeaa8ecdc5225aac96 for a full test report.

**Comment by verdurin** [comment]
```
== 2020-08-18 10:15:19,020 easyblock.py:3031 INFO Running method build_step part of step build
== 2020-08-18 10:15:19,020 run.py:203 DEBUG run_cmd: running cmd  make -j 4  (in /eb/maint/build/Kent_tools/401/gompi-2019b/userApps)
== 2020-08-18 10:15:19,020 run.py:222 INFO running cmd:  make -j 4
== 2020-08-18 10:15:46,738 build_log.py:169 ERROR EasyBuild crashed with an error (at easybuild/base/exceptions.py:124 in __init__): cmd " make -j 4 " exited with exit code 2 and output:
cd kent/src && make userApps
/bin/sh: libpng-config: command not found
/bin/sh: libpng-config: command not found
make[1]: Entering directory `/eb/maint/build/Kent_tools/401/gompi-2019b/userApps/kent/src'
mkdir -p /eb/maint/build/Kent_tools/401/gompi-2019b/userApps//bin
cd hg/lib && make
cd lib && make
/bin/sh: libpng-config: command not found
/bin/sh: libpng-config: command not found
/bin/sh: libpng-config: command not found
/bin/sh: libpng-config: command not found
```

**Comment by boegel** [comment]
@boegelbot please test @ generoso

@verdurin please re-test?

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
node3416.kirlia.os - Linux centos linux 7.8.2003, x86_64, Intel(R) Xeon(R) Gold 6240 CPU @ 2.60GHz (cascadelake), Python 2.7.5
See https://gist.github.com/3c0f2c91c33f8d100fb56031c57aff3f for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
node2450.golett.os - Linux centos linux 7.8.2003, x86_64, Intel(R) Xeon(R) CPU E5-2680 v3 @ 2.50GHz (haswell), Python 2.7.5
See https://gist.github.com/065c0fade031f875aa36f77a84dfb6e9 for a full test report.

**Comment by verdurin** [comment]
Test report by @verdurin
**FAILED**
Build succeeded for 0 out of 1 (1 easyconfigs in this PR)
easybuild.novalocal - Linux centos linux 7.8.2003, x86_64, Intel Xeon Processor (Skylake, IBRS), Python 2.7.5
See https://gist.github.com/865f87595259f604702ea1bbfa746d62 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
node3157.skitty.os - Linux centos linux 7.8.2003, x86_64, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz (skylake_avx512), Python 3.6.8
See https://gist.github.com/e14058db85204aa8f50bb5b0b23788f8 for a full test report.

**Comment by verdurin** [comment]
```
In file included from uuid.c:9:
../inc/uuid.h:8:10: fatal error: uuid/uuid.h: No such file or directory
 #include <uuid/uuid.h>
          ^~~~~~~~~~~~~
compilation terminated.
make[2]: *** [uuid.o] Error 1
make[2]: *** Waiting for unfinished jobs....
```

**Comment by boegel** [comment]
@verdurin Again?

**Comment by verdurin** [comment]
```
ERROR: Missing dependencies: util-linux/2.35-gompi-2019b (no easyconfig file or existing module found)
```

**Comment by boegel** [comment]
I managed to fat finger the wrong `util-linux` version, fixed now... @verdurin try again?

**Comment by verdurin** [comment]
Test report by @verdurin
**SUCCESS**
Build succeeded for 41 out of 41 (1 easyconfigs in this PR)
nuc.localdomain - Linux Fedora 32, x86_64, Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz, Python 3.8.5
See https://gist.github.com/ae92c2fbc8aa5bf98d3ef8c60227ebe6 for a full test report.

**Comment by boegel** [comment]
@boegelbot please test @ generoso

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
node3141.skitty.os - Linux centos linux 7.8.2003, x86_64, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz (skylake_avx512), Python 3.6.8
See https://gist.github.com/c1620c7190d6c315339edd15218c1e28 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
node3407.kirlia.os - Linux centos linux 7.8.2003, x86_64, Intel(R) Xeon(R) Gold 6240 CPU @ 2.60GHz (cascadelake), Python 2.7.5
See https://gist.github.com/8b56e3cb8f03ba1b0a1012a082345941 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
node2711.swalot.os - Linux centos linux 7.8.2003, x86_64, Intel(R) Xeon(R) CPU E5-2660 v3 @ 2.60GHz (haswell), Python 2.7.5
See https://gist.github.com/a2feb40ecbd54b58fbbd5bde4db60f20 for a full test report.

**Comment by verdurin** [comment]
Going in, thanks @boegel!

**Pull request merged**
