### PR TITLE
{vis}[foss/2020a, intel/2020a] ParaView v5.8.0 

### PR DESCRIPTION
**Pull request by maxim-masterov**
CMake options for the v5.8 significantly diverge from the previous v5.6. I've removed much of the deprecated options, including those that are inherited from the really old EB-configs. Also, there is no `VTKData` rule in the makefile anymore, so it is removed as well.

An important thing to mention: there seems to be a bug in the intel compiler. ParaView does not compile with `-ipo` option, throwing an error: `icpc: error #10014: problem during multi-file optimization compilation (code 4)`. Thus, for the intel toolchain, the compilation is set using `-no-ipo` option.

### CODE REVIEW

**Comment by boegel** [comment]
@maxim-masterov I took the liberty of tweaking this a little bit, mostly to fix the `XZ` dependency (see #10407), but also to prevent the hardcoded `-O3` when building with `intel/2020a`.

Both easyconfigs work, I'll get test reports submitted for them, so we can get this merged.

We're collapsing the easyconfigs from the `2020a` branch into `develop`, we're getting close to completing that effort (see https://github.com/easybuilders/easybuild-easyconfigs/issues?q=label%3A2020a+milestone%3A%22next+release+(4.2.1%3F)%22+is%3Aopen)

**Comment by maxim-masterov** [comment]
@boegel Thanks!

**Comment by boegel** [comment]
Test report by @boegel
**FAILED**
Build succeeded for 1 out of 2 (2 easyconfigs in this PR)
generoso-2 - Linux centos linux 7.6.1810, x86_64, Intel(R) Xeon(R) CPU E5-2660 v4 @ 2.00GHz, Python 3.6.8
See https://gist.github.com/ca7051bd68c5e332e0a9efdf90e895a1 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**FAILED**
Build succeeded for 1 out of 2 (2 easyconfigs in this PR)
node2422.golett.os - Linux centos linux 7.7.1908, x86_64, Intel(R) Xeon(R) CPU E5-2680 v3 @ 2.50GHz (haswell), Python 2.7.5
See https://gist.github.com/68614672f3046480d7667dec7dd210ca for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**FAILED**
Build succeeded for 1 out of 2 (2 easyconfigs in this PR)
node3404.kirlia.os - Linux centos linux 7.7.1908, x86_64, Intel(R) Xeon(R) Gold 6240 CPU @ 2.60GHz (cascadelake), Python 2.7.5
See https://gist.github.com/225d16cfcfa63bc02c4b74ae8a0e24c7 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in this PR)
node3151.skitty.os - Linux centos linux 7.7.1908, x86_64, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz (skylake_avx512), Python 3.6.8
See https://gist.github.com/88f488d54923302d31d85a8fa17f8d3e for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in this PR)
generoso-2 - Linux centos linux 7.6.1810, x86_64, Intel(R) Xeon(R) CPU E5-2660 v4 @ 2.00GHz, Python 3.6.8
See https://gist.github.com/aff9ef7b92577f3e9760c1c31113a0b1 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in this PR)
node3402.kirlia.os - Linux centos linux 7.7.1908, x86_64, Intel(R) Xeon(R) Gold 6240 CPU @ 2.60GHz (cascadelake), Python 2.7.5
See https://gist.github.com/dd6771b352f5e7103122cd0c3c2c9e46 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in this PR)
node2697.swalot.os - Linux centos linux 7.7.1908, x86_64, Intel(R) Xeon(R) CPU E5-2660 v3 @ 2.60GHz (haswell), Python 2.7.5
See https://gist.github.com/3622674362973e37df5ea92e8fff65ed for a full test report.

**Comment by boegel** [comment]
Going in, thanks @maxim-masterov!

**Pull request merged**
