### PR TITLE
{system}[GCC/8.3.0] CUDA v10.2.89

### PR DESCRIPTION
**Pull request by boegel**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by boegel** [comment]
@branfosj Please test from a POWER system? The checksum should be correct...

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
generoso-1 - Linux centos linux 7.6.1810, Intel(R) Xeon(R) CPU E5-2660 v4 @ 2.00GHz, Python 3.6.8
See https://gist.github.com/8b7f55b5045c69fea426f029283248a4 for a full test report.

**Comment by branfosj** [comment]
Test report by @branfosj
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
bear-pg0305u05a.bear.cluster - Linux RHEL 7.6, 8335-GTX, Python 2.7.5
See https://gist.github.com/c44abb5539b9798058210d5f4d50d590 for a full test report.

**Comment by branfosj** [comment]
Test report by @branfosj
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
bear-pg0212u17a.bear.cluster - Linux centos linux 7.6.1810, Intel(R) Xeon(R) CPU E5-2640 v4 @ 2.40GHz, Python 2.7.5
See https://gist.github.com/e30d686bb89f43588c48d7c05ef3cf61 for a full test report.

**Comment by branfosj** [comment]
@boegel The first of the test reports is the one from POWER and all looks fine to me.

**Comment by migueldiascosta** [comment]
Test report by @migueldiascosta
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
sms - Linux centos linux 7.6.1810, AMD EPYC 7601 32-Core Processor, Python 2.7.5
See https://gist.github.com/8f40aa0234d88997e6bb9fb9799c94fb for a full test report.

**Comment by migueldiascosta** [comment]
Going in, thanks @boegel!

**Comment by terjekv** [comment]
Test report by @terjekv
**SUCCESS**
Build succeeded for 17 out of 17 (1 easyconfigs in this PR)
ninhursaga.uio.no - Linux RHEL 8.1, Intel(R) Xeon(R) Silver 4216 CPU @ 2.10GHz, Python 2.7.16
See https://gist.github.com/0b5c40f78263582ba66bec77e3a40c2e for a full test report.

**Comment by Flamefire** [comment]
Is this used anywhere already or is a fosscuda toolchain using this defined yet? This is needed for power where fosscuda/2019[ab] can't be installed

**Comment by boegel** [comment]
@Flamefire The most recent `fosscuda/2019b` (which was defined on Oct 3rd) still uses `CUDA` 10.1.243.

There's an opportunity to define a new "common" version of `fosscuda` early next year (`fosscuda/2020a`), but in the mean time you can define another non-common version already (say `fosscuda/2019.11`).

EasyBuild doesn't care about the toolchain version at all, only about the version of the individual components.

**Comment by Flamefire** [comment]
>EasyBuild doesn't care about the toolchain version at all, only about the version of the individual components.

Really? https://github.com/easybuilders/easybuild-easyconfigs/blob/develop/easybuild/easyconfigs/t/TensorFlow/TensorFlow-2.0.0-fosscuda-2019b-Python-3.7.4.eb#L10

Don't I have to create ECs for all dependencies with that toolchain version?

**Comment by boegel** [comment]
> Don't I have to create ECs for all dependencies with that toolchain version?

You do, that's not what I was referring to. EasyBuild doesn't care whether the toolchain version is `foss/2019b`, `foss/2019.12` or `foss/whatever`, that's all I was saying. :)

**Comment by Flamefire** [comment]
Ah sure. It's just a pain to create all those ECs Gotta try `--try-toolchain` and see what it makes out of all those TF2 dependencies

**Pull request merged**
