### PR TITLE
{cae}[intel/2018a] OpenFOAM v3.0.1

### PR DESCRIPTION
**Pull request by boegel**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
node3159.skitty.os - Linux centos linux 7.6.1810, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz, Python 2.7.5
See https://gist.github.com/8d43465829ffb74fca58a7c1f585758b for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
node2093.delcatty.os - Linux centos linux 7.6.1810, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.7.5
See https://gist.github.com/b6ec8a0cae52fd6fbd2d6ac84a293e20 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 2 out of 2 (1 easyconfigs in this PR)
node2093.delcatty.os - Linux centos linux 7.6.1810, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.7.5
See https://gist.github.com/6ddafc6b87f39d9562131579f1a469f9 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
node2669.swalot.os - Linux centos linux 7.6.1810, Intel(R) Xeon(R) CPU E5-2660 v3 @ 2.60GHz, Python 2.7.5
See https://gist.github.com/9c6975e0a3e895b640b65f967bd3a921 for a full test report.

**Comment by akesandgren** [comment]
We used c++14 and the fix_isnan.patch we have for 3.0.1 with intel/2017a.

I'll do some testing of this before merging.

**Comment by akesandgren** [comment]
Test report by @akesandgren
**FAILED**
Build succeeded for 0 out of 1 (1 easyconfigs in this PR)
b-cn0315.hpc2n.umu.se - Linux ubuntu 16.04, Intel(R) Xeon(R) CPU E5-2690 v4 @ 2.60GHz, Python 2.7.12
See https://gist.github.com/67cf366659b742a5434c0288ca9d1b98 for a full test report.

**Comment by akesandgren** [comment]
Test report by @akesandgren
**FAILED**
Build succeeded for 0 out of 1 (1 easyconfigs in this PR)
b-cn0315.hpc2n.umu.se - Linux ubuntu 16.04, Intel(R) Xeon(R) CPU E5-2690 v4 @ 2.60GHz, Python 2.7.12
See https://gist.github.com/d8319451909aded6d0f090e7265811bc for a full test report.

**Comment by akesandgren** [comment]
Yep. it fails on isnan
ensight/part/ensightPart.C(54): error: identifier "isnan" is undefined
              if (id >= field.size() || isnan(field[id]))

Pr to your PR coming up.

**Comment by boegel** [comment]
@akesandgren Why am I not seeing this on CentOS 7? Is this problem somehow OS-specific?

**Comment by akesandgren** [comment]
Don't know. It's compiler specific as far as i know.

**Comment by akesandgren** [comment]
What does your build log say on that, warning?

**Comment by akesandgren** [comment]
Unless it picks up c++ include files from /usr/include/c++, but it shouldn't really since that is /usr/include/c++/5

**Comment by boegel** [comment]
No `isnan` found in my build log, so no warnings it seems.

**Comment by akesandgren** [comment]
Here it picks it up from Core/GCCcore/6.4.0/bin/../
include/c++/6.4.0/cmath

verified by looking at mpiicpc -E output compiling that file.

**Comment by akesandgren** [comment]
anyway std::isnan is the correct way of doing this, one should never just do isnan.

**Comment by akesandgren** [comment]
Test report by @akesandgren
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
b-cn0315.hpc2n.umu.se - Linux ubuntu 16.04, Intel(R) Xeon(R) CPU E5-2690 v4 @ 2.60GHz, Python 2.7.12
See https://gist.github.com/11e65a2831e3f918c1e2997621c83671 for a full test report.

**Comment by akesandgren** [comment]
Going in, thanks @boegel!

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
node2594.golett.os - Linux centos linux 7.6.1810, Intel(R) Xeon(R) CPU E5-2680 v3 @ 2.50GHz, Python 2.7.5
See https://gist.github.com/250464a90db56abd2f1a1480cabab2a6 for a full test report.

**Pull request merged**
