### PR TITLE
{numlib}[GCC/9.3.0] MiniSat v20130925, MiniSat v2.2.0

### PR DESCRIPTION
**Pull request by lexming**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by verdurin** [comment]
Test report by @verdurin
**FAILED**
Build succeeded for 1 out of 2 (2 easyconfigs in total)
easybuild-c7.novalocal - Linux centos linux 7.9.2009, x86_64, Intel Xeon Processor (Skylake, IBRS), Python 3.6.8
See https://gist.github.com/69ba27f1571d0006cf48788d2242ec91 for a full test report.

**Comment by verdurin** [comment]
Problems with the older version:
```
Compiling: build/dynamic/minisat/utils/System.o
In file included from ./minisat/core/Solver.h:29,
                 from minisat/core/Solver.cc:26:
[snip]
Linking Shared Library: build/dynamic/lib/libminisat.so.2.1.0
Linking Static Library: build/release/lib/libminisat.a
Linking Binary: build/release/bin/minisat
/eb/maint/software/binutils/2.34-GCCcore-9.3.0/bin/ld.gold: error: cannot find -lc
/eb/maint/software/binutils/2.34-GCCcore-9.3.0/bin/ld.gold: error: cannot find -lm
/lib/../lib64/crt1.o(.text+0x12): error: undefined reference to '__libc_csu_fini'
/lib/../lib64/crt1.o(.text+0x19): error: undefined reference to '__libc_csu_init'
/lib/../lib64/crt1.o(.text+0x25): error: undefined reference to '__libc_start_main'
minisat/simp/Main.cc:44: error: undefined reference to 'putchar'
minisat/simp/Main.cc:44: error: undefined reference to 'puts'
minisat/simp/Main.cc:47: error: undefined reference to 'putchar'
minisat/simp/Main.cc:47: error: undefined reference to 'puts'
minisat/simp/Main.cc:48: error: undefined reference to '_exit'
./minisat/utils/ParseUtils.h:96: error: undefined reference to 'stderr'
./minisat/utils/ParseUtils.h:96: error: undefined reference to 'fprintf'
./minisat/utils/ParseUtils.h:96: error: undefined reference to 'exit'
./minisat/mtl/Vec.h:129: error: undefined reference to 'free'
```
followed by lots of similar errors, then
```
/eb/maint/software/zlib/1.2.11-GCCcore-9.3.0/lib/libz.a(gzlib.o):gzlib.c:function gzoffset64: error: undefined reference to 'lseek64'
/eb/maint/software/zlib/1.2.11-GCCcore-9.3.0/lib/libz.a(gzlib.o):gzlib.c:function gz_error: error: undefined reference to 'strlen'
/eb/maint/software/zlib/1.2.11-GCCcore-9.3.0/lib/libz.a(gzlib.o):gzlib.c:function gz_error: error: undefined reference to 'strlen'
/eb/maint/software/zlib/1.2.11-GCCcore-9.3.0/lib/libz.a(gzlib.o):gzlib.c:function gz_error: error: undefined reference to 'malloc'
```
etc. and
```
/eb/maint/build/GCCcore/9.3.0/system-system/gcc-9.3.0/libstdc++-v3/../libgcc/unwind-pe.h:260: error: undefined reference to 'abort'
/eb/maint/build/GCCcore/9.3.0/system-system/gcc-9.3.0/libstdc++-v3/../libgcc/unwind-pe.h:88: error: undefined reference to 'abort'
/eb/maint/build/GCCcore/9.3.0/system-system/gcc-9.3.0/libstdc++-v3/../libgcc/unwind-pe.h:120: error: undefined reference to 'abort'
../../../../libstdc++-v3/libsupc++/eh_terminate.cc:52: error: undefined reference to 'abort'
../../../../libstdc++-v3/libsupc++/guard.cc:302: error: undefined reference to 'syscall'
../../../../libstdc++-v3/libsupc++/guard.cc:361: error: undefined reference to 'syscall'
../../../../libstdc++-v3/libsupc++/guard.cc:401: error: undefined reference to 'syscall'
``` plus more.

**Comment by lexming** [comment]
@verdurin the binary was statically linking with everything, including `glibc` in the host system. I happen to have `glibc-static` installed. Regardless, it is preferable to disable the indiscriminate static linking. It should work in your case with https://github.com/easybuilders/easybuild-easyconfigs/pull/11962/commits/8017c305fa739324e7e982fa95a01137724b68d4.

**Comment by lexming** [comment]
Test report by @lexming
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in total)
node376.hydra.os - Linux centos linux 7.9.2009, x86_64, Intel(R) Xeon(R) Gold 6148 CPU @ 2.40GHz, Python 2.7.5
See https://gist.github.com/780b1d479a13adead8381850bada88bf for a full test report.

**Comment by lexming** [comment]
Test report by @lexming
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in total)
node113.hydra.os - Linux centos linux 7.9.2009, x86_64, Intel(R) Xeon(R) CPU E5-2680 v2 @ 2.80GHz, Python 2.7.5
See https://gist.github.com/5ca511e7f203a217d703c6d5034dfdee for a full test report.

**Comment by verdurin** [comment]
Test report by @verdurin
**SUCCESS**
Build succeeded for 1 out of 1 (2 easyconfigs in total)
easybuild-c7.novalocal - Linux centos linux 7.9.2009, x86_64, Intel Xeon Processor (Skylake, IBRS), Python 3.6.8
See https://gist.github.com/c39c2201ca5391ffaedc6b36c197cc80 for a full test report.

**Comment by verdurin** [comment]
@boegelbot please test @ generoso

**Review by verdurin — APPROVED** [review]
Looks fine.

**Comment by verdurin** [comment]
Going in, thanks @lexming!

**Pull request merged**
