### PR TITLE
{numlib}[GCCcore/10.2.0] BLIS v3.0.1

### PR DESCRIPTION
**Pull request by robert-mijakovic**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by robert-mijakovic** [comment]
@boegelbot please test @ generoso

**Comment by robert-mijakovic** [comment]
Test report by @robert-mijakovic
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
login01.meluxina.lxp.lu - Linux RHEL 8.3, x86_64, AMD EPYC 7452 32-Core Processor (zen2), Python 3.6.8
See https://gist.github.com/c1d4e3e3733ab0bd143f8ca4eb0d7a70 for a full test report.

**Comment by lexming** [comment]
Test report by @lexming
**FAILED**
Build succeeded for 0 out of 1 (1 easyconfigs in total)
node356.hydra.os - Linux centos linux 7.9.2009, x86_64, Intel(R) Xeon(R) Gold 6148 CPU @ 2.40GHz, Python 2.7.5
See https://gist.github.com/916a539f39177f57cd553956b997f421 for a full test report.

**Comment by robert-mijakovic** [comment]
```
bash: line 2: 133373 Floating point exception(core dumped) ./test_libblis.x -g ./testsuite/input.general.fast -o ./testsuite/input.operations.fast > output.testsuite
make: *** [testsuite-run-fast] Error 136
 (at easybuild/tools/run.py:577 in parse_cmd_output)
== 2021-07-28 13:04:34,672 build_log.py:265 INFO ... (took 16 secs)
== 2021-07-28 13:04:34,672 filetools.py:1883 INFO Removing lock /user/brussel/101/vsc10122/.local/easybuild-skylake/software/.locks/_user_brussel_101_vsc10122_.local_easybuild-skylake_software_BLIS_3.0.1-GCCcore-10.2.0-amd.lock...
== 2021-07-28 13:04:34,676 filetools.py:358 INFO Path /user/brussel/101/vsc10122/.local/easybuild-skylake/software/.locks/_user_brussel_101_vsc10122_.local_easybuild-skylake_software_BLIS_3.0.1-GCCcore-10.2.0-amd.lock successfully removed.
== 2021-07-28 13:04:34,676 filetools.py:1887 INFO Lock removed: /user/brussel/101/vsc10122/.local/easybuild-skylake/software/.locks/_user_brussel_101_vsc10122_.local_easybuild-skylake_software_BLIS_3.0.1-GCCcore-10.2.0-amd.lock
== 2021-07-28 13:04:34,676 easyblock.py:3704 WARNING build failed (first 300 chars): cmd " make check " exited with exit code 2 and output:
```

**Comment by lexming** [comment]
Test report by @lexming
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
node226.hydra.os - Linux centos linux 7.9.2009, x86_64, Intel(R) Xeon(R) CPU E5-2680 v4 @ 2.40GHz, Python 2.7.5
See https://gist.github.com/cf73dd7ea1b4fa6d08ab573e36734239 for a full test report.

**Comment by lexming** [comment]
This version of the AMD fork does not like AVX512 (surprise). Same story as with v3.0.0: https://github.com/easybuilders/easybuild-easyconfigs/pull/13057#issuecomment-855243126

**Review by lexming — APPROVED** [review]
LGTM

**Comment by lexming** [comment]
Going in, thanks @robert-mijakovic !

**Pull request merged**
