### PR TITLE
OpenBLAS: build with -fno-tree-vectorize (asm constraint bugs for <0.3.6)

### PR DESCRIPTION
**Pull request by bartoldeman**
cfr. https://github.com/easybuilders/easybuild-easyconfigs/issues/7180

### CODE REVIEW

**Comment by bartoldeman** [comment]
Test report by @bartoldeman
**FAILED**
Build succeeded for 8 out of 9 (9 easyconfigs in this PR)
lg-1r17-n06 - Linux centos 6.6, Intel(R) Xeon(R) CPU E5-2650 0 @ 2.00GHz, Python 2.6.6
See https://gist.github.com/6794ab7be8c3645d57d9807422a431ac for a full test report.

**Comment by bartoldeman** [comment]
Test report by @bartoldeman
**SUCCESS**
Build succeeded for 10 out of 10 (9 easyconfigs in this PR)
lg-1r17-n06 - Linux centos 6.6, Intel(R) Xeon(R) CPU E5-2650 0 @ 2.00GHz, Python 2.6.6
See https://gist.github.com/c24a21bad5b7d5c2ec48cf2841edc276 for a full test report.

**Comment by boegel** [comment]
checksum problems fixed in #7793

**Comment by boegel** [comment]
merged via #7793

**Pull request merged**
