### PR TITLE
{bio}[foss/2018b] HISAT2 v2.1.0

### PR DESCRIPTION
**Pull request by SethosII**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by SethosII** [comment]
Test report by @SethosII
**SUCCESS**
Build succeeded for 4 out of 4 (1 easyconfigs in this PR)
ribnode015 - Linux ubuntu 18.04, Intel(R) Xeon(R) CPU           E5645  @ 2.40GHz, Python 2.7.15rc1
See https://gist.github.com/70b142b6da3d075a9a22e2d02ad0c140 for a full test report.

**Comment by vanzod** [comment]
Test report by @vanzod
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
cermis - Linux debian 9.8, Intel(R) Xeon(R) CPU           X5670  @ 2.93GHz, Python 2.7.13
See https://gist.github.com/e67f728e7a4eaab97b60faa0990c3d7f for a full test report.

**Comment by vanzod** [comment]
Going in, thanks @SethosII!

**Comment by SethosII** [comment]
@vanzod I just noticed that the `NGS` dependency has a `Java` version suffix, should this be propagated to `HISAT2` as @boegel mentioned here with `Python`: https://github.com/easybuilders/easybuild-easyconfigs/pull/7702#discussion_r259056683?

**Comment by boegel** [comment]
@SethosII The `versionsuffix` is far less important for `Java` than it is for `Python`, since we stick to a single `Java` version per toolchain generation (the `1.8` wrapper version), while we have *two* `Python` versions (2.x & 3.x).

**Pull request merged**
