### PR TITLE
{devel, tools, lib}[GCCcore/13.3.0] ConcurrentVersionsSystem-1.11.23, DBus-1.15.8, ecBuild-3.8.5, FLAC-1.4.3, flatbuffers-24.3.25, flatbuffers-python-24.3.25 

### PR DESCRIPTION
**Pull request by ankekreuzer**
These packages are used in the new SW stage at JSC and were more or less version bumps from earlier toolchains

### CODE REVIEW

**Comment by ankekreuzer** [comment]
Test report by @ankekreuzer
**SUCCESS**
Build succeeded for 7 out of 7 (7 easyconfigs in total)
zam329 - Linux Rocky Linux 9.4 (Blue Onyx), x86_64, Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz, Python 3.9.18
See https://gist.github.com/ankekreuzer/3d61e882ca61d804734d7c19bc035849 for a full test report.

**Comment by smoors** [comment]
@boegelbot: please test @ generoso

**Comment by smoors** [comment]
@boegelbot please test @ jsc-zen3

**Review by smoors — APPROVED** [review]
lgtm

**Comment by smoors** [comment]
Going in, thanks @ankekreuzer!

**Pull request merged**
