### PR TITLE
add 'ninja --version' as sanity check command in Ninja easyconfigs

### PR DESCRIPTION
**Pull request by boegel**
(created using `eb --new-pr`)
closes #13219

### CODE REVIEW

**Comment by boegel** [comment]
@boegelbot please test @ generoso
EB_ARGS="Ninja-1.10.0-GCCcore-9.3.0.eb Ninja-1.10.1-GCCcore-10.2.0.eb Ninja-1.10.2-GCCcore-10.3.0.eb Ninja-1.8.2-foss-2018b.eb Ninja-1.8.2-fosscuda-2018b.eb Ninja-1.9.0-GCCcore-8.2.0.eb Ninja-1.9.0-GCCcore-8.3.0.eb Ninja-1.9.0-foss-2018b.eb"

**Comment by SebastianAchilles** [comment]
Test report by @sebastianachilles
**SUCCESS**
Build succeeded for 3 out of 3 (3 easyconfigs in total)
rocky8-eb - Linux rocky linux 8.4, x86_64, Intel(R) Core(TM) i7-6900K CPU @ 3.20GHz (broadwell), Python 3.6.8
See https://gist.github.com/00bcae8ad373dabd57a3e22835400f88 for a full test report.

**Comment by SebastianAchilles** [comment]
Test report by @sebastianachilles
**SUCCESS**
Build succeeded for 3 out of 3 (3 easyconfigs in total)
centos8-eb - Linux centos linux 8.3.2011, x86_64, Intel(R) Core(TM) i7-8700 CPU @ 3.20GHz (skylake), Python 3.6.8
See https://gist.github.com/5f86340c1158ef27f57bf49385fbff59 for a full test report.

**Review by SebastianAchilles — APPROVED** [review]
lgtm

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 11 out of 11 (11 easyconfigs in total)
node2618.swalot.os - Linux centos linux 7.9.2009, x86_64, Intel(R) Xeon(R) CPU E5-2660 v3 @ 2.60GHz (haswell), Python 3.6.8
See https://gist.github.com/a758089419968c4baea3f03deb7bfbf7 for a full test report.

**Comment by SebastianAchilles** [comment]
Going in, thanks @boegel!

**Pull request merged**
