### PR TITLE
{bio}[foss/2017b] CONCOCT v1.0.0

### PR DESCRIPTION
**Pull request by vanzod**
Depends on:
~~#8055~~ (MEGAHIT)
~~#8056~~ (parallel)
~~#8057~~ (CheckM)

### CODE REVIEW

**Comment by vanzod** [comment]
Test report by @vanzod
**SUCCESS**
Build succeeded for 5 out of 5 (5 easyconfigs in this PR)
cermis - Linux debian 9.8, Intel(R) Xeon(R) CPU           X5670  @ 2.93GHz, Python 2.7.13
See https://gist.github.com/da55f6241db74dd5f51d074067ffba43 for a full test report.

**Comment by migueldiascosta** [comment]
Test report by @migueldiascosta
**SUCCESS**
Build succeeded for 5 out of 5 (5 easyconfigs in this PR)
grc-cluster1 - Linux centos 6.10, Intel(R) Xeon(R) CPU E5-2640 0 @ 2.50GHz, Python 2.7.14
See https://gist.github.com/90bdbec0798251fcc544d5b6da13f62f for a full test report.

**Comment by migueldiascosta** [comment]
@vanzod why the `new` label?

**Comment by vanzod** [comment]
@migueldiascosta I did not see that Kenneth already added `CONCOCT`. Let me sync my PR with his EC file.

**Comment by vanzod** [comment]
Test report by @vanzod
**SUCCESS**
Build succeeded for 3 out of 3 (3 easyconfigs in this PR)
cermis - Linux debian 9.8, Intel(R) Xeon(R) CPU           X5670  @ 2.93GHz, Python 2.7.13
See https://gist.github.com/d88369ba7e79593561e3cf18a008baf4 for a full test report.

**Comment by migueldiascosta** [comment]
Test report by @migueldiascosta
**SUCCESS**
Build succeeded for 3 out of 3 (3 easyconfigs in this PR)
grc-cluster1 - Linux centos 6.10, Intel(R) Xeon(R) CPU E5-2640 0 @ 2.50GHz, Python 2.7.14
See https://gist.github.com/0a07d81837a4d2fc7e1e70ad34ec8376 for a full test report.

**Comment by migueldiascosta** [comment]
closing and reopening to trigger travis

**Comment by migueldiascosta** [comment]
Going in, thanks @vanzod!

**Pull request merged**
