### PR TITLE
Add zlib dependency to YODA and Rivet

### PR DESCRIPTION
**Pull request by APN-Pucky**
Problem in EESSI https://github.com/EESSI/software-layer/pull/418
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by casparvl** [comment]
I can confirm that it is now picking up the correct `zlib` for regular EB useage (i.e. without `--filter-deps=zlib`). We already confirmed it works _with_ `--filter-deps=zlib` [in this build for EESSI](https://github.com/EESSI/software-layer/pull/418#issuecomment-1907768107).

I'll upload a test report from my regular cluster.

**Comment by casparvl** [comment]
@boegelbot please test @ generoso

**Comment by APN-Pucky** [comment]
This is unfortunately a problem with hepforge.org, it is occasionally not available or takes a bit long to respond. As seen in end of the partial log here https://gist.github.com/boegelbot/8403a94ae031e40ad037ffcb415c5313

**Comment by casparvl** [comment]
Hm, yeah, I had the same problem locally. Then I downloaded it with `wget` manually and it worked on the second try...

I'm not quite sure why it fails with EasyBuild, I seem to have consistent failures for Rivet 3.1.9 on my local system, and consistent successes when I try with `wget`. Well, anyway, I'll try to trigger the bot a few more times, see if we randomly get a succes. It should at least cache the sources, so the 2 that already succeeeded should keep succeeding :)

**Comment by casparvl** [comment]
@boegelbot please test @ jsc-zen3

**Comment by casparvl** [comment]
@boegelbot please test @ jsc-zen3

**Comment by casparvl** [comment]
Test report by @casparvl
**SUCCESS**
Build succeeded for 4 out of 4 (4 easyconfigs in total)
gcn6.local.snellius.surf.nl - Linux RHEL 8.6, x86_64, Intel(R) Xeon(R) Platinum 8360Y CPU @ 2.40GHz, 4 x NVIDIA NVIDIA A100-SXM4-40GB, 545.23.08, Python 3.6.8
See https://gist.github.com/casparvl/8f0626a697d27d257da1ea69a3175e4e for a full test report.

**Review by casparvl — APPROVED** [review]
Lgtm!

**Comment by jfgrimm** [comment]
Test report by @jfgrimm
**SUCCESS**
Build succeeded for 13 out of 13 (4 easyconfigs in total)
gpu07.viking2.yor.alces.network - Linux Rocky Linux 8.8, x86_64, AMD EPYC 7643 48-Core Processor, 2 x NVIDIA NVIDIA A40, 535.86.10, Python 3.6.8
See https://gist.github.com/jfgrimm/df88c4ae56668cf442f2d2742f1cd60e for a full test report.

**Comment by casparvl** [comment]
Going in, thanks @APN-Pucky!

**Pull request merged**
