### PR TITLE
add Python 3 build dep for HMMER 3.3.x test step

### LINKED ISSUE #12108: Python 3 required for testing of HMMER
I found that I needed to load a `Python/3.x` module for the `testing` phase of a build of `HMMER` to work.
This was on a `CentOS 7.8` node.

The specific error was:
```
== FAILED: Installation ended unsuccessfully (build directory: /dev/shm/HMMER/3.3.2/gompi-2019b): build failed (first 300 chars): cmd " make check " exited with exit code 2 and output:
python3 is required for 'make check', but is not in your PATH. Aborting.
make: *** [check] Error 1
 (took 13 sec)
 ```

Would a `builddep` be appropriate here?

### PR DESCRIPTION
**Pull request by boegel**
(created using `eb --new-pr`)

fixes #12108

### CODE REVIEW

**Comment by boegel** [comment]
@boegelbot please test @ generoso

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 5 out of 5 (5 easyconfigs in total)
node3507.doduo.os - Linux RHEL 8.2, x86_64, AMD EPYC 7552 48-Core Processor (zen2), Python 3.6.8
See https://gist.github.com/3262e435f8d6cf3830a3c3aa93c13c4f for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 5 out of 5 (5 easyconfigs in total)
node2700.swalot.os - Linux centos linux 7.9.2009, x86_64, Intel(R) Xeon(R) CPU E5-2660 v3 @ 2.60GHz (haswell), Python 3.6.8
See https://gist.github.com/d350ef302fff92c45ada2af60ef4d167 for a full test report.

**Review by branfosj — APPROVED** [review]
lgtm

**Comment by branfosj** [comment]
Test report by @branfosj
**SUCCESS**
Build succeeded for 5 out of 5 (5 easyconfigs in total)
bear-pg0206u16a.bear.cluster - Linux RHEL 8.3, x86_64, Intel(R) Xeon(R) Gold 6248 CPU @ 2.50GHz (cascadelake), Python 3.6.8
See https://gist.github.com/4904e6c910f6d13019cd0ee4bdeb0972 for a full test report.

**Comment by branfosj** [comment]
Going in, thanks @boegel!

**Pull request merged**
