### PR TITLE
Fix alignment bug in patchelf 0.18.0 by adding patch

### PR DESCRIPTION
**Pull request by pavelToman**
(created using `eb --new-pr`)
For https://github.com/easybuilders/easybuild-easyconfigs/pull/21588

### CODE REVIEW

**Comment by boegel** [comment]
@boegelbot please test @ jsc-zen3

**Comment by pavelToman** [comment]
@boegelbot please test @ generoso

**Comment by pavelToman** [comment]
@boegelbot please test @ jsc-zen3

**Comment by boegel** [comment]
Going in, thanks @pavelToman!

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 17 out of 17 (3 easyconfigs in total)
node3124.skitty.os - Linux RHEL 9.4, x86_64, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz (skylake_avx512), Python 3.9.18
See https://gist.github.com/boegel/054452f6275442c4fba54acbddb20bc2 for a full test report.

**Pull request merged**
