### PR TITLE
Added TAMU XLC XLF compiler configs

### PR DESCRIPTION
**Pull request by chwilk**
I've started merging @JackPerdue 's changes into a fork of the current develop branch. Hopefully this is just a bunch of simple adds for now.

### CODE REVIEW

**Comment by pforai** [comment]
@chwilk could you shove what @JackPerdue has done on the framework side of things into a branch and open a PR as well?

**Comment by boegel** [comment]
Wow, this is *big*... We'll need to cut this into chunks to make this manageable (although the upcoming `--review-pr` cmdline option for `eb` will be a great help here).

One main issue is: how are we going to test this...

**Comment by chwilk** [comment]
@pforal: Coming soon.
@boegel: That's not the half of it :-) If I better understood what's required, I think I could swing dedicating a small VM on our master node to testing builds with your framework.

**Comment by migueldiascosta** [comment]
@chwilk, this PR is being closed for the following reason(s): no activity for > 1 year.
Please don't hesitate to reopen this PR or add a comment if you feel this contribution is still relevant.
For more information on our policy w.r.t. closing PRs, see https://easybuild.readthedocs.io/en/latest/Contributing.html#why-a-pull-request-may-be-closed-by-a-maintainer

**Pull request closed without merging**
