### PR TITLE
{bio}[foss/2018b] TM-align v20180426

### PR DESCRIPTION
**Pull request by pescobar**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by verdurin** [comment]
Test report by @verdurin
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
rescomp2 - Linux centos linux 7.3.1611, Intel(R) Xeon(R) Gold 6126 CPU @ 2.60GHz, Python 2.7.5
See https://gist.github.com/5bf5b86cef2141a602aa328eff3946e9 for a full test report.

**Comment by verdurin** [comment]
@pescobar Could you submit a test report for this please?

**Comment by pescobar** [comment]
Test report by @pescobar
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
login20.cluster.bc2.ch - Linux centos linux 7.5.1804, Intel(R) Xeon(R) CPU E5-2670 v2 @ 2.50GHz, Python 2.7.5
See https://gist.github.com/1b3c2f01abf3c583e42705e47fb3780f for a full test report.

**Comment by verdurin** [comment]
Going in, thanks @pescobar!

**Pull request merged**
