### PR TITLE
{bio}[foss/2016b] tCONCOORD v1.0, GROMACS v3.3.3

### PR DESCRIPTION
**Pull request by verdurin**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by verdurin** [comment]
The only reason this is `foss` is for compatibility with other modules. If there's a cleaner way of providing that specific old version of `GROMACS` in a way that doesn't clash, I'm open to suggestions. The binary of `tCONCOORD` is an old one, sadly. It requires #4469 owing to the linking of the binary.

**Comment by migueldiascosta** [comment]
closing and reopening to trigger travis

**Comment by boegel** [comment]
@verdurin Is it worth trying to get this one merged?

**Comment by boegel** [comment]
ping @verdurin?

**Comment by verdurin** [comment]
@boegel This one isn't relevant for me anymore.

**Pull request closed without merging**
