### PR TITLE
{vis}[GCCcore/13.3.0] TurboVNC v3.1.2

### PR DESCRIPTION
**Pull request by paulmelis**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by paulmelis** [comment]
Depends on https://github.com/easybuilders/easybuild-easyconfigs/pull/21380 for libGLU

**Comment by smoors** [comment]
@boegelbot: please test @ generoso

**Comment by smoors** [comment]
@boegelbot please test @ jsc-zen3

**Review by smoors — APPROVED** [review]
lgtm

**Comment by smoors** [comment]
Going in, thanks @paulmelis!

**Pull request merged**
