### PR TITLE
{lib}[GCCcore/9.3.0] pybind11 v2.4.3 w/ Python 3.8.2

### PR DESCRIPTION
**Pull request by akesandgren**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by akesandgren** [comment]
This is the last PR before the foss/2020a-rc3 -> foss/2020a PR

**Comment by akesandgren** [comment]
Test report by @akesandgren
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in this PR)
b-an04.hpc2n.umu.se - Linux ubuntu 16.04, Intel(R) Xeon(R) CPU E5-2690 v4 @ 2.60GHz, Python 2.7.12
See https://gist.github.com/7ad96b278a53e2cd919403e6072d507a for a full test report.

**Comment by lexming** [comment]
Test report by @lexming
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in this PR)
login2.cerberus.os - Linux centos linux 7.7.1908, Intel(R) Xeon(R) Gold 6126 CPU @ 2.60GHz, Python 2.7.5
See https://gist.github.com/6d3b3d9084343c215bf0aed9c69575e0 for a full test report.

**Comment by akesandgren** [comment]
@lexming I just copied the already existing, merged into 2020a, Python.3.8.2-GCCcore-9.2.0 and changed it to 9.3.0

**Comment by akesandgren** [comment]
@lexming See #9949 for the initial PR for it.

**Comment by boegel** [comment]
> For the record, list of modules moving in/out of base Python installation:
> 
>     * Added python modules
>       
>       * toml-0.10.0
>       * appdirs-1.4.3
>       * distlib-0.3.0
>       * filelock-3.0.12
> 
>     * Removed python modules
>       
>       * deap-1.3.0
> 
> 
> @akesandgren is there a reason to remove `deap`, it seems to be actively developed and supports Python v3.8

Here's the reason `deap` was dropped from the `Python` easyconfig, `pip check` fails with this error if it's included:

```
deap 1.3.1 requires numpy, which is not installed
```

So, we should move `deap` to `SciPy-bundle`...

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in this PR)
node2491.golett.os - Linux centos linux 7.7.1908, Intel(R) Xeon(R) CPU E5-2680 v3 @ 2.50GHz, Python 2.7.5
See https://gist.github.com/a00c39167de87c188c4817243cd53aa4 for a full test report.

**Comment by boegel** [comment]
Going in, thanks @akesandgren!

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in this PR)
generoso-3 - Linux centos linux 7.6.1810, Intel(R) Xeon(R) CPU E5-2660 v4 @ 2.00GHz, Python 3.6.8
See https://gist.github.com/52b6ba6dfe48a95452206df03c00ff4f for a full test report.

**Comment by migueldiascosta** [comment]
Test report by @migueldiascosta
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in this PR)
sms - Linux centos linux 7.6.1810, AMD EPYC 7601 32-Core Processor, Python 2.7.5
See https://gist.github.com/8b9b6609503bde65f9408118778d16c2 for a full test report.

**Pull request merged**
