### PR TITLE
{bio}[GCCcore/13.3.0] PRSice v2.3.5

### PR DESCRIPTION
**Pull request by maxim-masterov**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by SebastianAchilles** [comment]
@boegelbot please test @ jsc-zen3

**Comment by SebastianAchilles** [comment]
`NAMD-3.0-foss-2024a-mpi.eb` was already merged in https://github.com/easybuilders/easybuild-easyconfigs/pull/21732
I think this is why we have a merge conflict in this PR.

**Comment by maxim-masterov** [comment]
@SebastianAchilles Should be fixed now. Also, I merged this branch with `develop`

**Comment by SebastianAchilles** [comment]
@boegelbot please test @ generoso

**Pull request merged**
