### PR TITLE
{bio}[GCC/11.3.0] FastQ_Screen v0.14.0, GDGraph v1.56

### PR DESCRIPTION
**Pull request by boegel**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by boegel** [comment]
@boegelbot please test @ generoso

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 3 out of 3 (3 easyconfigs in total)
node3127.skitty.os - Linux RHEL 8.6, x86_64, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz (skylake_avx512), Python 3.6.8
See https://gist.github.com/a025d62b29f726d15723522720ec784c for a full test report.

**Comment by boegel** [comment]
@boegelbot please test @ jsc-zen2

**Comment by bedroge** [comment]
Synced the PR, because Bowtie was already part of PR https://github.com/easybuilders/easybuild-easyconfigs/pull/17383, which was merged yesterday.

**Comment by bedroge** [comment]
Test report by @bedroge
**SUCCESS**
Build succeeded for 6 out of 6 (2 easyconfigs in total)
bob-Latitude-5300 - Linux Ubuntu 22.04, x86_64, Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz, Python 3.10.6
See https://gist.github.com/f769ae616b75e284c83b0f22473f589e for a full test report.

**Comment by bedroge** [comment]
Test report by @bedroge
**SUCCESS**
Build succeeded for 7 out of 7 (2 easyconfigs in total)
pg-interactive.hpc.rug.nl - Linux CentOS Linux 7.9.2009, x86_64, Intel(R) Xeon(R) CPU E5-2680 v3 @ 2.50GHz, Python 3.6.8
See https://gist.github.com/51baf4b40362fed0029c11298bb6b8c4 for a full test report.

**Review by bedroge — APPROVED** [review]
lgtm

**Comment by bedroge** [comment]
Going in, thanks @boegel!

**Pull request merged**
