### PR TITLE
define $JUPYTER_PATH via modextrapaths rather than modextravars for IRkernel 1.x

### PR DESCRIPTION
**Pull request by branfosj**
(created using `eb --new-pr`)

Picked up at https://github.com/easybuilders/easybuild-easyconfigs/pull/15774#discussion_r907366869

`JUPYTER_PATH` documentation: https://docs.jupyter.org/en/latest/use/jupyter-directories.html#envvar-JUPYTER_PATH

### CODE REVIEW

**Comment by smoors** [comment]
@boegelbot: please test @ generoso

**Comment by verdurin** [comment]
@branfosj are the `2019b` versions just too old for this now?
Or is there a specific problem to be resolved there?

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 5 out of 5 (5 easyconfigs in total)
node3300.joltik.os - Linux RHEL 8.4, x86_64, Intel(R) Xeon(R) Gold 6242 CPU @ 2.80GHz (cascadelake), 1 x NVIDIA Tesla V100-SXM2-32GB, 520.61.05, Python 3.6.8
See https://gist.github.com/acccf3a762512e8851b235c9d17071a5 for a full test report.

**Review by boegel — APPROVED** [review]
lgtm

**Comment by boegel** [comment]
Going in, thanks @branfosj!

**Pull request merged**
