### PR TITLE
debugger,devel}[GCCcore/11.2.0] GDB v11.1, makeinfo v6.8 w/ Python 3.9.6

### PR DESCRIPTION
**Pull request by damianam**

### CODE REVIEW

**Comment by SebastianAchilles** [comment]
Test report by @sebastianachilles
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in total)
jsfc01.int.jusuf.sebastian.cluster - Linux rocky linux 8.4, x86_64, AMD EPYC 7742 64-Core Processor (zen2), 1 x NVIDIA GRID V100-4C, 460.73.01, Python 3.6.8
See https://gist.github.com/59e7707db488c408beb447377b06db5e for a full test report.

**Comment by SebastianAchilles** [comment]
@boegelbot please test @ generoso

**Review by migueldiascosta — APPROVED** [review]
lgtm

**Comment by migueldiascosta** [comment]
Going in, thanks @damianam!

**Pull request merged**
