### PR TITLE
{bio}[foss/2022a,foss/2022b] GEM v1.5.1

### PR DESCRIPTION
**Pull request by sassy-crick**
(created using `eb --new-pr`)

I tried to replace the `thirdparty/plink` with one from EasyBuild as well but I failed to resolve the 'undefined reference' problem I am getting. I am not sure which version of `PLINK` they were using.

### CODE REVIEW

**Comment by sassy-crick** [comment]
@boegelbot please test @ generoso

**Comment by verdurin** [comment]
Test report by @verdurin
**SUCCESS**
Build succeeded for 3 out of 3 (2 easyconfigs in total)
easybuild-c7.novalocal - Linux CentOS Linux 7.9.2009, x86_64, Intel Xeon Processor (Skylake, IBRS), Python 3.6.8
See https://gist.github.com/verdurin/76e0750f24e56d0e3953777e23437a3c for a full test report.

**Review by smoors — APPROVED** [review]
lgtm

**Review by smoors — APPROVED** [review]

**Comment by smoors** [comment]
Going in, thanks @sassy-crick!

**Pull request merged**
