### PR TITLE
{devel}[GCCcore/10.3.0,GCCcore/11.3.0] texinfo v6.8

### PR DESCRIPTION
**Pull request by boegel**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 3 out of 3 (3 easyconfigs in total)
node3127.skitty.os - Linux RHEL 8.4, x86_64, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz (skylake_avx512), Python 3.6.8
See https://gist.github.com/ce9ed38e53fe22f4f76326a8e66ed222 for a full test report.

**Comment by branfosj** [comment]
Test report by @branfosj
**FAILED**
Failed during parsing of the easyconfigs, so no ecs were built (2 easyconfigs in total)
bear-pg0103u11a.bear.cluster - Linux RHEL 8.5, x86_64, Intel(R) Xeon(R) Gold 6330 CPU @ 2.00GHz (icelake), 1 x NVIDIA NVIDIA A100-PCIE-40GB, 470.57.02, Python 3.6.8
See https://gist.github.com/f24731792c986dfb027f01be5be3f346 for a full test report.

**Comment by lexming** [comment]
@boegel why are these easyconfigs in `GCCcore` toolchains? the only dependency is an `osdependency` on `texlive. So this seems to better fit `SYSTEM`.

**Comment by boegel** [comment]
closing this, not planning to pursue it

In general, `makeinfo` is probably what you want, instead of `texinfo` (since the `texlive` OS dependency is a PITA)

**Pull request closed without merging**
