### PR TITLE
promote pybind11 to runtime dependency for CPPE (to fix `pip check` failure)

### PR DESCRIPTION
**Pull request by boegel**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by boegel** [comment]
@boegelbot please test @ generoso

**Comment by boegel** [comment]
@boegelbot please test @ jsc-zen3
EB_BRANCH=5.0.x

**Comment by boegel** [comment]
Need to check whether this could fallout, and whether `pybind11` really is a runtime dependency, or if it's just faulty packaging...

**Comment by boegel** [comment]
Asked upstream to make sure: https://github.com/maxscheurer/cppe/issues/47

**Comment by jfgrimm** [comment]
The build system got overhauled since the 0.3.1 release (which is from 2020). See:
https://github.com/maxscheurer/cppe/commit/1d2d0be8ed8b22e737c024dde75a055ddb21799f

We could probably just move to using 0.3.3a instead?

**Comment by boegel** [comment]
Requiring `pybind11` as a runtime dependency is most likely a packaging mistake, but promoting it to a runtime dependency should have no real downsides (especially since we currently have `pybind11` (incorrectly) as a runtime dependency of `SciPy-bundle` already), so I'm in favor of just merging this since it fixes a real problem that people will hit when installing these `CPPE` easyconfigs with EasyBuild 5.0, where `pip check` fails unless `pybind11` is a runtime dependency.

**Comment by boegel** [comment]
@boegelbot please test @ generoso

**Comment by boegel** [comment]
Testing this on `generoso` doesn't work because of the `5.0.x` target branch:
```
ERROR: Framework (4.9.5.dev0-rd700144108b3a5508659a4d957c7594d35033e62) is a different major version than used in easybuilders/easybuild-easyconfigs PR #21564 (5.0.0.dev0)
```

@jfgrimm With that, I think we can merge this...

**Review by Micket — APPROVED** [review]
lgtm (reluctantly, as this actually really isn't a builddep and it's just the devs that made a mistakes in their old build scripts)

**Comment by Micket** [comment]
Test report by @Micket
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in total)
vera-skylake-build - Linux Rocky Linux 8.9, x86_64, Intel Xeon Processor (Skylake, IBRS, no TSX), Python 3.6.8
See https://gist.github.com/Micket/cce62e8e2ac10be93f03332192e9db82 for a full test report.

**Pull request merged**
