### PR TITLE
Build PyCUDA with OpenGL support

### PR DESCRIPTION
**Pull request by VRehnberg**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by VRehnberg** [comment]
A PyTorch3D easyconfig I'm working has some functionality that requires this. Let me know if this instead should be a new ec with an extra versionsuffix.

**Comment by Micket** [comment]
Test report by @Micket
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
alvis7-01 - Linux Rocky Linux 8.9, x86_64, Intel(R) Xeon(R) Gold 6338 CPU @ 2.00GHz, 1 x NVIDIA NVIDIA A40, 560.35.03, Python 3.6.8
See https://gist.github.com/Micket/b303573f4bfecb365211295fcd28902e for a full test report.

**Comment by Micket** [comment]
Since it would be a complete mess to introduce another easyconfig for this, and this feature should definitely had been included in here, I'll merge this. It's not a core package used everywhere, so rebuilding it in production would probably not have a huge impact. It only took 2 minutes to build.

**Comment by Micket** [comment]
Going in, thanks @VRehnberg!

**Pull request merged**
