### PR TITLE
{bio}[system/system] bcl-convert v4.0.3-2

### PR DESCRIPTION
**Pull request by boegel**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
node3118.skitty.os - Linux RHEL 8.4, x86_64, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz (skylake_avx512), Python 3.6.8
See https://gist.github.com/ee7400fc1186c3452a802fa9daab08a8 for a full test report.

**Comment by verdurin** [comment]
Test report by @verdurin
**FAILED**
Build succeeded for 0 out of 1 (1 easyconfigs in total)
easybuild-c7.novalocal - Linux CentOS Linux 7.9.2009, x86_64, Intel Xeon Processor (Skylake, IBRS), Python 3.6.8
See https://gist.github.com/ca3b5e8e69faf66d2ec535e371270174 for a full test report.

**Comment by lexming** [comment]
Test report by @lexming
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
login2.cerberus.os - Linux CentOS Linux 7.9.2009, x86_64, Intel(R) Xeon(R) Gold 6126 CPU @ 2.60GHz, Python 3.6.8
See https://gist.github.com/c52e695c39c3f484b869a43f6d6c1709 for a full test report.

**Review by lexming — APPROVED** [review]
LGTM

**Comment by lexming** [comment]
Tests failed due to lack of `rpmrebuild` in build system, which is needed by `Rpm` easyblock.

Going in, thanks @boegel !

**Pull request merged**
