### PR TITLE
{data,lang,tools}[foss/2021a] SimpleITK v2.1.1, ITK v5.2.1 w/ Python 3.9.5

### PR DESCRIPTION
**Pull request by crubb**
(created using `eb --new-pr`)

... for @vacmar01 ;)

### CODE REVIEW

**Comment by lexming** [comment]
@boegelbot: please test @ generoso

**Comment by lexming** [comment]
Test report by @lexming
**FAILED**
Build succeeded for 2 out of 3 (2 easyconfigs in total)
node302.hydra.os - Linux centos linux 7.9.2009, x86_64, Intel(R) Xeon(R) Gold 6148 CPU @ 2.40GHz, Python 2.7.5
See https://gist.github.com/378c3de9c1f816e1f8eb2f188195442f for a full test report.

**Comment by verdurin** [comment]
Test report by @verdurin
**FAILED**
Build succeeded for 1 out of 3 (2 easyconfigs in total)
easybuild-c7.novalocal - Linux UNKNOWN UNKNOWN, x86_64, Intel Xeon Processor (Skylake, IBRS), Python 3.6.8
See https://gist.github.com/75708fc4c8907ad57096f75f10e73bf5 for a full test report.

**Comment by verdurin** [comment]
Test report by @verdurin
**FAILED**
Build succeeded for 1 out of 2 (2 easyconfigs in total)
easybuild-c7.novalocal - Linux UNKNOWN UNKNOWN, x86_64, Intel Xeon Processor (Skylake, IBRS), Python 3.6.8
See https://gist.github.com/bfcaace8c41656c7dcd09916adb932a5 for a full test report.

**Comment by verdurin** [comment]
@crubb I saw this build error:
```
-- Performing Test Weak Link MODULE -> SHARED (gnu_ld_ignore) - Success
-- Found PythonInterp: /eb/maint/software/Python/3.9.5-GCCcore-10.3.0/bin/python (found version "3.9.5") 
-- Found Tclsh: /eb/maint/software/Tcl/8.6.11-GCCcore-10.3.0/bin/tclsh (found version "8.6") 
-- Found LuaInterp: /bin/lua (Required is at least version "5.3") 
CMake Error at CMake/sitkGenerateFilterSource.cmake:52 (message):
  Lua version 5.3 is required for SimpleITK_LUA_EXECUTABLE_VERSION.
Call Stack (most recent call first):
  Code/BasicFilters/CMakeLists.txt:4 (include)


-- Processing json files...
CMake Warning at CMake/sitkGenerateFilterSource.cmake:78 (message):
  /bin/lua:
  /dev/shm/SimpleITK/2.1.1/foss-2021a/SimpleITK-2.1.1/ExpandTemplateGenerator/json.lua:308:
  bad argument #1 to 'load' (function expected, got string)

  stack traceback:

        [C]: in function 'load'

  
        /dev/shm/SimpleITK/2.1.1/foss-2021a/SimpleITK-2.1.1/ExpandTemplateGenerator/json.lua:308:
  in function
  </dev/shm/SimpleITK/2.1.1/foss-2021a/SimpleITK-2.1.1/ExpandTemplateGenerator/json.lua:283>
```
followed by lots of traceback detail.

Looks like you need to add `Lua` as a dependency?

**Comment by verdurin** [comment]
Test report by @verdurin
**FAILED**
Build succeeded for 3 out of 4 (2 easyconfigs in total)
centos7.lan - Linux UNKNOWN UNKNOWN, x86_64, Intel Core Processor (Skylake, IBRS), Python 3.6.8
See https://gist.github.com/7406e6674403156fe69044ba248277ed for a full test report.

**Comment by crubb** [comment]
@verdurin It turned out to be a little more complicated than that ;)

Code generation in the configuration step of `SimpleITK` uses `Lua`. However, `SimpleITK` v2.1.1 requires `Lua` v5.3 (apparently my system's version) and the `foss/2021a` toolchain is limited to `Lua` v5.4. I added a patch to allow the configuration step to use v5.4, which so far works fine.

NB: `SimpleITK`'s `Lua` "wrapping" has been disabled in the existing `SimpleITK` easyconfigs.

Could you give it another spin? Thank you!

**Comment by verdurin** [comment]
Test report by @verdurin
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in total)
easybuild-c7.novalocal - Linux UNKNOWN UNKNOWN, x86_64, Intel Xeon Processor (Skylake, IBRS), Python 3.6.8
See https://gist.github.com/423a3a418adc2890554bcedf3f75fe61 for a full test report.

**Comment by verdurin** [comment]
Test report by @verdurin
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in total)
centos7.lan - Linux UNKNOWN UNKNOWN, x86_64, Intel Core Processor (Skylake, IBRS), Python 3.6.8
See https://gist.github.com/b977462bd6ee1aa687b2b37cd6b71c50 for a full test report.

**Review by verdurin — APPROVED** [review]
Looks fine.

**Comment by verdurin** [comment]
Going in, thanks @crubb!

**Pull request merged**
