### PR TITLE
{chem}[gfbf/2023b] ASE v3.23.0

### PR DESCRIPTION
**Pull request by tanmoy1989**
(created using `eb --new-pr`)
- [x] Requires https://github.com/easybuilders/easybuild-easyconfigs/pull/21081

### CODE REVIEW

**Comment by tanmoy1989** [comment]
@smoors: Any updates on this, please?

**Comment by smoors** [comment]
@boegelbot please test @ jsc-zen3

**Comment by smoors** [comment]
@boegelbot: please test @ generoso

**Review by smoors — APPROVED** [review]
lgtm

**Comment by smoors** [comment]
Going in, thanks @tanmoy1989!

**Pull request merged**
