### PR TITLE
{devel,tools,vis}[fosscuda/2020b] hypothesis v4.53.1, PyTorch v1.3.1, torchvision v0.4.2 w/ Python 3.8.6

### PR DESCRIPTION
**Pull request by Flamefire**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by terjekv** [comment]
Test report by @terjekv
**SUCCESS**
Build succeeded for 4 out of 4 (3 easyconfigs in total)
ninhursaga.uio.no - Linux RHEL 8.4, x86_64, Intel(R) Xeon(R) Silver 4216 CPU @ 2.10GHz (cascadelake), Python 3.6.8
See https://gist.github.com/df8e0d5c99579ebc3d6f9bc229ca3ece for a full test report.

**Comment by Flamefire** [comment]
Test report by @Flamefire
**FAILED**
Build succeeded for 1 out of 3 (3 easyconfigs in total)
taurusa7 - Linux centos linux 7.7.1908, x86_64, Intel(R) Xeon(R) CPU E5-2603 v4 @ 1.70GHz (broadwell), Python 2.7.5
See https://gist.github.com/e5ac6566e66cd76966e2b753e73a1988 for a full test report.

**Comment by Flamefire** [comment]
Test report by @Flamefire
**SUCCESS**
Build succeeded for 3 out of 3 (3 easyconfigs in total)
taurusa7 - Linux centos linux 7.7.1908, x86_64, Intel(R) Xeon(R) CPU E5-2603 v4 @ 1.70GHz (broadwell), Python 2.7.5
See https://gist.github.com/1399bcecc25a3427eae3af8f6d4d6fd1 for a full test report.

**Comment by Flamefire** [comment]
Test report by @Flamefire
**SUCCESS**
Build succeeded for 3 out of 3 (3 easyconfigs in total)
taurusi8025 - Linux centos linux 7.9.2009, x86_64, AMD EPYC 7352 24-Core Processor (zen2), Python 2.7.5
See https://gist.github.com/b4c5f9f41a0516edc5021fe48dfa84cf for a full test report.

**Comment by Flamefire** [comment]
@terjekv @verdurin This is ready now. Passes even on our A100 system and the segfault seems to be gone too.

**Comment by terjekv** [comment]
Running one last test then :)

**Comment by terjekv** [comment]
Test report by @terjekv
**SUCCESS**
Build succeeded for 4 out of 4 (3 easyconfigs in total)
ninhursaga.uio.no - Linux RHEL 8.4, x86_64, Intel(R) Xeon(R) Silver 4216 CPU @ 2.10GHz (cascadelake), Python 3.6.8
See https://gist.github.com/12907b2dbdd7690699c8d1cf981336bc for a full test report.

**Comment by branfosj** [comment]
Test report by @branfosj
**FAILED**
Build succeeded for 1 out of 3 (3 easyconfigs in total)
bask-pg0309u11a - Linux RHEL 8.4, x86_64, Intel(R) Xeon(R) Platinum 8360Y CPU @ 2.40GHz (icelake), Python 3.6.8
See https://gist.github.com/cf4e44ae9a6adb739cd83af490687c68 for a full test report.

**Comment by Flamefire** [comment]
@branfosj https://github.com/pytorch/pytorch/issues/47281 https://github.com/marian-nmt/marian-dev/issues/709 and fix https://github.com/marian-nmt/marian-dev/pull/836 I'll see what I can do here.

**Comment by Flamefire** [comment]
@branfosj Please try again now, included the upstream patch but can't test it myself as the CPU needs VNNI support to trigger this issue

**Comment by branfosj** [comment]
Test report by @branfosj
**SUCCESS**
Build succeeded for 3 out of 3 (3 easyconfigs in total)
bask-pg0309u09a - Linux RHEL 8.4, x86_64, Intel(R) Xeon(R) Platinum 8360Y CPU @ 2.40GHz (icelake), Python 3.6.8
See https://gist.github.com/7c437a65879d0fdf48d3463e01a6465e for a full test report.

**Review by branfosj — APPROVED** [review]

**Comment by branfosj** [comment]
Going in, thanks @Flamefire!

**Pull request merged**
