### PR TITLE
in-place update of easyconfig Horovod v0.20.0 to v0.20.3

### PR DESCRIPTION
**Pull request by Flamefire**
Follow-up to https://github.com/easybuilders/easybuild-easyconfigs/pull/11375 using an updated horovod as the 0.20.0 had usability issues (some parts were unusable)

### CODE REVIEW

**Comment by Flamefire** [comment]
Test report by @Flamefire
**FAILED**
Build succeeded for 0 out of 1 (1 easyconfigs in this PR)
taurusml2 - Linux RHEL 7.6, POWER, 8335-GTX, Python 2.7.5
See https://gist.github.com/2bc586369aafd8d5741769902a5b5f7e for a full test report.

**Comment by Flamefire** [comment]
Test report by @Flamefire
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
taurusi6381.taurus.hrsk.tu-dresden.de - Linux RHEL 7.8, x86_64, Intel(R) Xeon(R) CPU E5-2680 v3 @ 2.50GHz, Python 2.7.5
See https://gist.github.com/0dff4c47ba5fffecf696dc9c72b8d7e9 for a full test report.

**Comment by zao** [comment]
Test report by @zao
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
freja - Linux Ubuntu 20.04, x86_64, Intel(R) Core(TM) i7-8700K CPU @ 3.70GHz, Python 3.8.2
See https://gist.github.com/dd4b238a296654d045a1905bd81281e4 for a full test report.

**Comment by Flamefire** [comment]
Test report by @Flamefire
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
taurusml22 - Linux RHEL 7.6, POWER, 8335-GTX, Python 2.7.5
See https://gist.github.com/dac9f1c4ae6001a98674065976eaa45a for a full test report.

**Comment by verdurin** [comment]
Test report by @verdurin
**SUCCESS**
Build succeeded for 22 out of 22 (1 easyconfigs in this PR)
nuc.lan - Linux Fedora 32, x86_64, Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz, Python 3.8.5
See https://gist.github.com/a8f7faa8dfff011ed3ee47a065318b7a for a full test report.

**Comment by verdurin** [comment]
@boegelbot please test @ generoso

**Review by verdurin — APPROVED** [review]
Looks fine.

**Review by boegel — APPROVED** [review]
lgtm

ok to do in-place update because the Horovod 0.20.0 easyconfig was added recently (see #11359), not included in an EasyBuild release yet...

**Comment by verdurin** [comment]
Going in, thanks @Flamefire!

**Pull request merged**
