### PR TITLE
{bio}[GCC/8.3.0] Exonerate v2.4.0

### PR DESCRIPTION
**Pull request by smoors**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by smoors** [comment]
Test report by @smoors
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
node305.hydra.os - Linux centos linux 7.6.1810, Intel(R) Xeon(R) Gold 6148 CPU @ 2.40GHz, Python 2.7.5
See https://gist.github.com/97682609b2c455cdbc892143fb5a7c18 for a full test report.

**Comment by Micket** [comment]
Test report by @Micket
**SUCCESS**
Build succeeded for 5 out of 5 (1 easyconfigs in this PR)
vera-c1 - Linux centos linux 7.6.1810, Intel Xeon Processor (Skylake), Python 2.7.5
See https://gist.github.com/e9af3811db4fb4b1376c48ef868eb78b for a full test report.

**Comment by Micket** [comment]
Going in, thanks @smoors!

**Comment by Micket** [comment]
Going in, thanks @smoors!

**Pull request merged**
