### PR TITLE
update TensorFlow 1.14.0/2.0.0 CUDA patch to handle compiler wrappers like ccache

### PR DESCRIPTION
**Pull request by Flamefire**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by Flamefire** [comment]
This is supposed to fix https://github.com/easybuilders/easybuild-easyconfigs/issues/9325 @boegel Can you give it a spin to see if it works for you? Running the TF2 build here ATM

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in this PR)
node3300.joltik.os - Linux centos linux 7.7.1908, Intel(R) Xeon(R) Gold 6242 CPU @ 2.80GHz, Python 2.7.5
See https://gist.github.com/da38734d7aee01174077a8513f098505 for a full test report.

**Comment by Flamefire** [comment]
Test report by @Flamefire
**FAILED**
Build succeeded for 2 out of 6 (2 easyconfigs in this PR)
taurusi5036.taurus.hrsk.tu-dresden.de - Linux RHEL 7.4, Intel(R) Xeon(R) CPU E5-2680 v3 @ 2.50GHz, Python 2.7.5
See https://gist.github.com/259afedfef941579bc2b1492912a11b7 for a full test report.

**Comment by boegel** [comment]
@Flamefire Missing "source" file for Java (`jdk-8u221-linux-x64.tar.gz`), which you need to download manually due to licensing stuff.

**Comment by Flamefire** [comment]
This is new... Damn, who builds a build system based on Java? -.-

**Comment by Flamefire** [comment]
Test report by @Flamefire
**FAILED**
Build succeeded for 2 out of 6 (2 easyconfigs in this PR)
taurusi5036.taurus.hrsk.tu-dresden.de - Linux RHEL 7.4, Intel(R) Xeon(R) CPU E5-2680 v3 @ 2.50GHz, Python 2.7.5
See https://gist.github.com/5ef88678bf16734daf129d4d12ad8378 for a full test report.

**Comment by boegel** [comment]
@Flamefire Google does! ;)

**Comment by Flamefire** [comment]
Test report by @Flamefire
**SUCCESS**
Build succeeded for 5 out of 5 (2 easyconfigs in this PR)
taurusi5036.taurus.hrsk.tu-dresden.de - Linux RHEL 7.4, Intel(R) Xeon(R) CPU E5-2680 v3 @ 2.50GHz, Python 2.7.5
See https://gist.github.com/1970669caf99870177a2bf58b25367df for a full test report.

**Comment by boegel** [comment]
Going in, thanks @Flamefire!

**Pull request merged**
