### PR TITLE
add patches to fix PyTorch 1.13.1 w/ foss/2022a on POWER + fix flaky `test_jit_legacy` test

### PR DESCRIPTION
**Pull request by Flamefire**
(created using `eb --new-pr`)

Adds the updated patch from #18489 and another one similar to #18490

### CODE REVIEW

**Comment by boegel** [comment]
@boegelbot please test @ generoso
CORE_CNT=16

**Review by boegel — APPROVED** [review]
lgtm

**Comment by boegel** [comment]
@boegelbot please test @ jsc-zen2
CORE_CNT=16

**Comment by Flamefire** [comment]
Test report by @Flamefire
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
taurusml24 - Linux RHEL 7.6, POWER, 8335-GTX (power9le), 6 x NVIDIA Tesla V100-SXM2-32GB, 440.64.00, Python 2.7.5
See https://gist.github.com/Flamefire/653574b428b9ab6ae556aef59c2c2d16 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
node3115.skitty.os - Linux RHEL 8.6, x86_64, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz (skylake_avx512), Python 3.6.8
See https://gist.github.com/boegel/06c529b35468c5489f6b6d98b313ed14 for a full test report.

**Comment by Flamefire** [comment]
Test report by @Flamefire
**FAILED**
Build succeeded for 0 out of 1 (1 easyconfigs in total)
taurusi8031 - Linux CentOS Linux 7.9.2009, x86_64, AMD EPYC 7352 24-Core Processor (zen2), 8 x NVIDIA NVIDIA A100-SXM4-40GB, 470.57.02, Python 2.7.5
See https://gist.github.com/Flamefire/2ae197940ca00755731d0950d6464c9d for a full test report.

**Comment by boegel** [comment]
@Flamefire Last test report failed due to a lock being found, I won't let that block this PR since there's various other tests on Intel/AMD

**Comment by boegel** [comment]
Going in, thanks @Flamefire!

**Pull request merged**
