### PR TITLE
add an additional env variable $GRACE_HOME to Grace easyconfigs, so that font dir can be located

### PR DESCRIPTION
**Pull request by murfreesboro**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by migueldiascosta** [comment]
Test report by @migueldiascosta
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in this PR)
grc-cluster1 - Linux centos 6.10, Intel(R) Xeon(R) CPU E5-2640 0 @ 2.50GHz, Python 2.7.14
See https://gist.github.com/73e01e7842ad8309d45031797d536226 for a full test report.

**Comment by migueldiascosta** [comment]
@murfreesboro might as well also fix the older easyconfig, `Grace-5.1.25-foss-2018a-5build1.eb`?

@hajgato that one was contributed by you in #6036, any objections?

**Comment by murfreesboro** [comment]
@migueldiascosta yeah I agree. We may also need to fix the 2018a version, too.

**Comment by hajgato** [comment]
@murfreesboro @migueldiascosta Go ahead!

**Comment by boegel** [comment]
@murfreesboro Please make the same change to `Grace-5.1.25-foss-2018a-5build1.eb` so we can go ahead and merge this?

**Comment by murfreesboro** [comment]
OK @boegel will do it on Monday.

**Comment by murfreesboro** [comment]
@boegel the change for 2018a is in.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 3 out of 3 (3 easyconfigs in this PR)
node2006.delcatty.os - Linux centos linux 7.6.1810, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.7.5
See https://gist.github.com/dcb456b676261a77b3b06f8e47828364 for a full test report.

**Comment by boegel** [comment]
Going in, thanks @murfreesboro!

**Pull request merged**
