### PR TITLE
add missing (optional) dependency cp2k-input-tools to phonopy 2.20.0

### PR DESCRIPTION
**Pull request by boegel**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by boegel** [comment]
@boegelbot please test @ generoso

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in total)
node4012.donphan.os - Linux RHEL 8.8, x86_64, Intel(R) Xeon(R) Gold 6240 CPU @ 2.60GHz, 1 x NVIDIA NVIDIA A2, 545.23.08, Python 3.6.8
See https://gist.github.com/boegel/e72dd78c848ff7ea5122a371ff90db26 for a full test report.

**Comment by boegel** [comment]
@boegelbot please test @ jsc-zen3
@boegelbot please test @ jsc-zen3

**Review by laraPPr — APPROVED** [review]
lgtm

**Pull request merged**
