### PR TITLE
{math,tools}[GCCcore/13.2.0] lcalc v2.0.5, gengetopt v2.23

### PR DESCRIPTION
**Pull request by PetrKralCZ**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by PetrKralCZ** [comment]
needs:
- https://github.com/easybuilders/easybuild-easyconfigs/pull/20478

**Review by smoors — APPROVED** [review]
lgtm

**Review by smoors — APPROVED** [review]

**Comment by smoors** [comment]
@boegelbot: please test @ generoso

**Comment by smoors** [comment]
@boegelbot please test @ jsc-zen3

**Comment by smoors** [comment]
Going in, thanks @PetrKralCZ!

**Pull request merged**
