### PR TITLE
{lang}[GCC/11.3.0,foss/2022a] RStudio-Server v2022.07.2-576, SOCI v4.0.3

### PR DESCRIPTION
**Pull request by kosl**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by verdurin** [comment]
@kosl it looks like adding `quarto` is doing lots of unpleasant things, such as checking out `yaml-cpp` via Git and building that, rather than using our easyconfig, and building `node`, which again is available as an easyconfig.

The specific crash is caused by missing `jq`:

```
Downloading node-v16.14.0-linux-x64 from https://nodejs.org/dist/v16.14.0/node-v16.14.0-linux-x64.tar.gz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
^M  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0^M  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0^M100 31.2M  100 31.2M    0     0  38.0M      0 --:--:-- --:--:-- --:--:-- 38.0M
ESC[1mESC[36m==>ESC[39m Installing yarnESC[0m
yarn 1.22.15 already installed at '/home/software/.yarn/bin/yarn'
yarn config v1.22.15
success Set "ignore-engines" to "true".
Done in 0.04s.
yarn install v1.22.15
[1/4] Resolving packages...
[2/4] Fetching packages...
info fsevents@1.2.11: The platform "linux" is incompatible with this module.
info "fsevents@1.2.11" is an optional dependency and failed compatibility check. Excluding it from installation.
[3/4] Linking dependencies...
warning "prosemirror-dev-tools > react-dock@0.2.4" has unmet peer dependency "babel-runtime@^6.3.13".
warning "prosemirror-dev-tools > react-emotion@9.2.12" has incorrect peer dependency "react@15.x || 16.x".
warning "prosemirror-dev-tools > react-json-tree@0.11.2" has incorrect peer dependency "react@^15.0.0 || ^16.0.0".
warning "prosemirror-dev-tools > react-json-tree@0.11.2" has incorrect peer dependency "react-dom@^15.0.0 || ^16.0.0".
warning "prosemirror-dev-tools > unstated@2.1.1" has incorrect peer dependency "react@^15.0.0 || ^16.0.0".
warning "prosemirror-dev-tools > unstated > create-react-context@0.1.6" has incorrect peer dependency "react@^14.0.0 || ^15.0.0 || ^16.0.0".
warning " > prosemirror-utils@0.9.6" has incorrect peer dependency "prosemirror-tables@^0.9.1".
warning " > tslint-react@5.0.0" has incorrect peer dependency "tslint@^6.0.0".
[4/4] Building fresh packages...
Done in 10.35s.
ESC[1mESC[36m==>ESC[39m Installing QuartoESC[0m
./install-quarto: line 30: jq: command not found
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
^M  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0^M 88  9606   88  8496    0     0  25803      0 --:--:-- --:--:-- --:--:-- 25823
curl: (23) Failure writing output to destination
 (at easybuild/tools/run.py:641 in parse_cmd_output)
 ```

**Comment by kosl** [comment]
I was trying to build with new EB yaml-cpp but failed to build without patching. 
Will try harder.

**Comment by verdurin** [comment]
@kosl might be worth looking at #15967 for inspiration.

**Comment by kosl** [comment]
> @kosl might be worth looking at #15967 for inspiration.

Missed  #15967 as I was in a hurry to get RStudio Server running. 
I guess we can obsolete this PR if  #15967 will be upgraded and hunks realigned?

**Comment by Flamefire** [comment]
I opened #16478 with this version of RStudio, #15967 is also still there.

**Pull request closed without merging**
