### PR TITLE
{lib}[GCCcore/10.3.0] libedit v20210910

### PR DESCRIPTION
**Pull request by jessie828**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by akesandgren** [comment]
@boegelbot Please test @ jsc-zen2

**Comment by akesandgren** [comment]
The 20221030 version is probably excessive since we only have 20210910 for GCCcore/11.2.0 and would thus never use 20221030 for anything related to GCCcore/10.3.0. It would make more sense to have 20221030 (or later) for newer toolchains like 11.3.0 or later. Feel free to change that if you have time.

**Comment by jessie828** [comment]
I tend to agree with you.
The reason I included it is because I need it on a project I am working on where we are still using GCCcore/10.3.0.  👎🏽 
We are planning on moving towards GCCcore 12.3.0 soon but would like to start moving our build over to using modules.

I will probably be ok with downgrading to libedit 20210910 on my end and upgrade back to 20221030 once we also upgrade our toolchain. That will enable me getting rid of 20221030  built with GCCcore/10.3.0

@akesandgren  Would that be acceptable for you?

**Comment by akesandgren** [comment]
For now it would then be enough to just drop the 2022 version from this PR (eb --update-pr 18586 :libedit-20221030-GCCcore-10.3.0.eb), then we can merge this with just the 2019 version. You can of course keep the 2022 version locally.

**Comment by boegel** [comment]
@boegelbot please test @ generoso

**Review by boegel — APPROVED** [review]
lgtm

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
node3102.skitty.os - Linux RHEL 8.6, x86_64, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz (skylake_avx512), Python 3.6.8
See https://gist.github.com/boegel/2befe07c3d89e3ec8eb58a6366f9e654 for a full test report.

**Comment by boegel** [comment]
Going in, thanks @jessie828!

**Pull request merged**
