### PR TITLE
add patch to fix missing sync in LINCS and SETTLE CUDA kernels for GROMACS 2020 versions

### PR DESCRIPTION
**Pull request by branfosj**
(created using `eb --new-pr`)

Patch based off https://gitlab.com/gromacs/gromacs/-/merge_requests/2499, with change to reflect the difference in filenames, and see discussion in https://gitlab.com/gromacs/gromacs/-/issues/4393

### CODE REVIEW

**Comment by SebastianAchilles** [comment]
@boegelbot please test @ generoso
CORE_CNT=16

**Comment by branfosj** [comment]
Test report by @branfosj
**SUCCESS**
Build succeeded for 3 out of 3 (3 easyconfigs in total)
bber0501u03b.bb2.cluster - Linux RHEL 8.6, x86_64, Intel(R) Xeon(R) CPU E5-2690 v3 @ 2.60GHz (haswell), Python 3.6.8
See https://gist.github.com/80a516f8cb05c83361e4cd5f8a60faf6 for a full test report.

**Comment by branfosj** [comment]
```
The following tests FAILED:
	 34 - Pdb2gmx3Test (Timeout)
```
That is the @boegelbot failure. That cannot be related to the change here, as the patch only touches GPU code and there were no GPUs available during that test build.

**Review by SebastianAchilles — APPROVED** [review]
lgtm

**Comment by SebastianAchilles** [comment]
Going in, thanks @branfosj!

**Pull request merged**
