### PR TITLE
{math}[gfbf/2022a] giac v1.9.0-69

### PR DESCRIPTION
**Pull request by migueldiascosta**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by migueldiascosta** [comment]
@boegelbot please test @ generoso

**Comment by migueldiascosta** [comment]
@boegelbot please test @ jsc-zen2

**Comment by migueldiascosta** [comment]
@boegelbot please test @ jsc-zen2

**Comment by jfgrimm** [comment]
Test report by @jfgrimm
**SUCCESS**
Build succeeded for 12 out of 12 (4 easyconfigs in total)
node040.viking2.yor.alces.network - Linux Rocky Linux 8.8, x86_64, AMD EPYC 7643 48-Core Processor, Python 3.6.8
See https://gist.github.com/jfgrimm/e7202839b8d99f3d19f173c674326992 for a full test report.

**Comment by jfgrimm** [comment]
@migueldiascosta the `M4` builddep needs to be in `GMP-ECM`

**Review by jfgrimm — APPROVED** [review]
lgtm

**Pull request merged**
