### PR TITLE
{chem}[iomkl/2018.02] ASE v3.16.2

### PR DESCRIPTION
**Pull request by schiotz**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by schiotz** [comment]
This depends on PR #6447 which will cause the Travis test to fail until #6447 is merged.

**Comment by schiotz** [comment]
Kicking Travis now that #6447 has been merged.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
node2476.golett.os - Linux centos linux 7.4.1708, Intel(R) Xeon(R) CPU E5-2680 v3 @ 2.50GHz, Python 2.7.5
See https://gist.github.com/34eb2b539fbebad11fee4805a211b71e for a full test report.

**Comment by schiotz** [comment]
@boegel 
I have no clue what the error from Travis means.  Have I done something wrong in a weird way?

**Comment by boegel** [comment]
@schiotz The problem is not related to your PRs, it's caused by merging of https://github.com#5983.

The tests have been extended significantly since that PR was opened, and the green light for that PR was given too long ago.

See also #6491 which should fix the problem, I'll retrigger the tests for this PR once the problem is solved.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
node3102.skitty.os - Linux centos linux 7.4.1708, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz, Python 2.7.5
See https://gist.github.com/703dfd4f4fe2e14fe2d6a28bc4a3c283 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
gligar02.gligar.os - Linux centos linux 7.4.1708, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.7.5
See https://gist.github.com/579c7ac10206f4aba79619a6441beb36 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
node3102.skitty.os - Linux centos linux 7.4.1708, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz, Python 2.7.5
See https://gist.github.com/3f2b28f119ecd6aff0c8f40e38b25571 for a full test report.

**Comment by boegel** [comment]
Going in, thanks @schiotz!

**Pull request merged**
