### PR TITLE
update netCDF to 4.7.4 for 2020a easyconfigs

### PR DESCRIPTION
**Pull request by boegel**

### CODE REVIEW

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 6 out of 6 (6 easyconfigs in this PR)
node3401.kirlia.os - Linux centos linux 7.7.1908, x86_64, Intel(R) Xeon(R) Gold 6240 CPU @ 2.60GHz (cascadelake), Python 2.7.5
See https://gist.github.com/9de2fcbd0b429de95efd2f77f3a8f237 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**FAILED**
Build succeeded for 8 out of 11 (11 easyconfigs in this PR)
generoso-3 - Linux centos linux 7.6.1810, x86_64, Intel(R) Xeon(R) CPU E5-2660 v4 @ 2.00GHz, Python 3.6.8
See https://gist.github.com/1f687668180d0724740a53bf5cf3619c for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**FAILED**
Build succeeded for 32 out of 34 (11 easyconfigs in this PR)
node2607.swalot.os - Linux centos linux 7.7.1908, x86_64, Intel(R) Xeon(R) CPU E5-2660 v3 @ 2.60GHz (haswell), Python 2.7.5
See https://gist.github.com/00edd9ce251395b439d1616722d63080 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 11 out of 11 (11 easyconfigs in this PR)
generoso-1 - Linux centos linux 7.6.1810, x86_64, Intel(R) Xeon(R) CPU E5-2660 v4 @ 2.00GHz, Python 3.6.8
See https://gist.github.com/2252ddf56731d6ee75c265ffec162b3c for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**FAILED**
Build succeeded for 15 out of 16 (11 easyconfigs in this PR)
node3401.kirlia.os - Linux centos linux 7.7.1908, x86_64, Intel(R) Xeon(R) Gold 6240 CPU @ 2.60GHz (cascadelake), Python 2.7.5
See https://gist.github.com/34a6c425eb767a275d6065c703fe9a30 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**FAILED**
Build succeeded for 11 out of 12 (11 easyconfigs in this PR)
node2607.swalot.os - Linux centos linux 7.7.1908, x86_64, Intel(R) Xeon(R) CPU E5-2660 v3 @ 2.60GHz (haswell), Python 2.7.5
See https://gist.github.com/54f1b7336184fb9b1319a7f4aeefa8fb for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**FAILED**
Build succeeded for 36 out of 39 (11 easyconfigs in this PR)
node3128.skitty.os - Linux centos linux 7.7.1908, x86_64, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz (skylake_avx512), Python 3.6.8
See https://gist.github.com/1d49519d6fc19d402a86c042abc755c7 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 13 out of 13 (11 easyconfigs in this PR)
node3156.skitty.os - Linux centos linux 7.7.1908, x86_64, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz (skylake_avx512), Python 3.6.8
See https://gist.github.com/d6c1f5834908781f2af685b7412d61fd for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 11 out of 11 (11 easyconfigs in this PR)
node3403.kirlia.os - Linux centos linux 7.7.1908, x86_64, Intel(R) Xeon(R) Gold 6240 CPU @ 2.60GHz (cascadelake), Python 2.7.5
See https://gist.github.com/6f0fe89035e03b9fa525fda0e24f7d0f for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 11 out of 11 (11 easyconfigs in this PR)
node2660.swalot.os - Linux centos linux 7.7.1908, x86_64, Intel(R) Xeon(R) CPU E5-2660 v3 @ 2.60GHz (haswell), Python 2.7.5
See https://gist.github.com/8502664cc79c7daba731cb196693a203 for a full test report.

**Comment by akesandgren** [comment]
Test report by @akesandgren
**FAILED**
Build succeeded for 29 out of 30 (11 easyconfigs in this PR)
b-an03.hpc2n.umu.se - Linux ubuntu 16.04, x86_64, Intel(R) Xeon(R) CPU E5-2690 v4 @ 2.60GHz, Python 2.7.12
See https://gist.github.com/433d207c23f8f9f8c3b081fea2455967 for a full test report.

**Comment by boegel** [comment]
@akesandgren Can you re-test just the `LAMMPS` easyconfig with `eb --from-pr 10506 LAMMPS-3Mar2020-foss-2020a-Python-3.8.2-kokkos.eb`, to rule this out as a fluke?

```
WARNING: There was an error initializing an OpenFabrics device.

  Local host:   b-an03
  Local device: mlx5_0
--------------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/a/ake/Public/easybuild/software/MPI/GCC/9.3.0/OpenMPI/4.0.3/LAMMPS/3Mar2020-Python-3.8.2-kokkos/lib/python3.8/site-packages/lammps.py", line 152, in __init__
    if not name: self.lib = CDLL(join(modpath,"liblammps" + lib_ext),RTLD_GLOBAL)
  File "/home/a/ake/Public/easybuild/software/Compiler/GCCcore/9.3.0/Python/3.8.2/lib/python3.8/ctypes/__init__.py", line 373, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: /home/a/ake/Public/easybuild/software/MPI/GCC/9.3.0/OpenMPI/4.0.3/LAMMPS/3Mar2020-Python-3.8.2-kokkos/lib/python3.8/site-packages/liblammps.so: cannot open shared object file: No such file or directory
```

**Comment by akesandgren** [comment]
There is a dependency problem with LAMMPS, it needs cURL.

```
ldd /home/a/ake/Public/easybuild/software/MPI/GCC/9.3.0/OpenMPI/4.0.3/LAMMPS/3Mar2020-Python-3.8.2-kokkos/lib/liblammps.so | grep curl
        libcurl.so.4 => /usr/lib/x86_64-linux-gnu/libcurl.so.4 (0x00007f91f3cdf000)
```
(And it's directly from liblammps.so)

And during sanity
```
python -c 'from lammps import lammps; l=lammps(); l.file("/scratch/eb-ak
e/LAMMPS/3Mar2020/foss-2020a-Python-3.8.2-kokkos/lammps-stable_3Mar2020/examples
/atm/in.atm")' exited with code 1 (output: -------------------------------------
-------------------------------------
WARNING: There was an error initializing an OpenFabrics device.

  Local host:   b-an03
  Local device: mlx5_0
--------------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/a/ake/Public/easybuild/software/MPI/GCC/9.3.0/OpenMPI/4.0.3/LAMMPS
/3Mar2020-Python-3.8.2-kokkos/lib/python3.8/site-packages/lammps.py", line 152,
in __init__
    if not name: self.lib = CDLL(join(modpath,"liblammps" + lib_ext),RTLD_GLOBAL
) 
  File "/home/a/ake/Public/easybuild/software/Compiler/GCCcore/9.3.0/Python/3.8.
2/lib/python3.8/ctypes/__init__.py", line 373, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: /home/a/ake/Public/easybuild/software/MPI/GCC/9.3.0/OpenMPI/4.0.3/LAMMPS/3Mar2020-Python-3.8.2-kokkos/lib/python3.8/site-packages/liblammps.so: cannot open shared object file: No such file or directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/a/ake/Public/easybuild/software/MPI/GCC/9.3.0/OpenMPI/4.0.3/LAMMPS/3Mar2020-Python-3.8.2-kokkos/lib/python3.8/site-packages/lammps.py", line 156, in __init__
    if not name: self.lib = CDLL("liblammps" + lib_ext,RTLD_GLOBAL)
  File "/home/a/ake/Public/easybuild/software/Compiler/GCCcore/9.3.0/Python/3.8.2/lib/python3.8/ctypes/__init__.py", line 373, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: /home/a/ake/Public/easybuild/software/Compiler/GCCcore/9.3.0/cURL/7.69.1/lib/libcurl.so.4: version `CURL_OPENSSL_3' not found (required by /home/a/ake/Public/easybuild/software/MPI/GCC/9.3.0/OpenMPI/4.0.3/LAMMPS/3Mar2020-Python-3.8.2-kokkos/lib/liblammps.so)
```

**Comment by akesandgren** [comment]
The creation of liblammps.so does not contain the -Lpath to EB's cURL, but it does have -lcurl

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
node3102.skitty.os - Linux centos linux 7.7.1908, x86_64, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz (skylake_avx512), Python 3.6.8
See https://gist.github.com/b838aad32e8e9906db88c2968ccd879f for a full test report.

**Comment by akesandgren** [comment]
Test report by @akesandgren
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
b-an03.hpc2n.umu.se - Linux ubuntu 16.04, x86_64, Intel(R) Xeon(R) CPU E5-2690 v4 @ 2.60GHz, Python 2.7.12
See https://gist.github.com/ee338352f150ca959310edb4142e169b for a full test report.

**Comment by akesandgren** [comment]
Going in, thanks @boegel!

**Pull request merged**
