### PR TITLE
{cae}[foss/2020a] OpenFOAM v8

### PR DESCRIPTION
**Pull request by furstj**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by smoors** [comment]
Test report by @smoors
**SUCCESS**
Build succeeded for 6 out of 6 (1 easyconfigs in this PR)
node317.hydra.os - Linux centos linux 7.7.1908, x86_64, Intel(R) Xeon(R) Gold 6148 CPU @ 2.40GHz (skylake_avx512), Python 2.7.5
See https://gist.github.com/2af6bf387f2c9b74971c984f38e208d8 for a full test report.

**Comment by furstj** [comment]
Test report by @furstj
**SUCCESS**
Build succeeded for 0 out of 0 (1 easyconfigs in this PR)
kronos.fsik.cvut.cz - Linux centos linux 7.8.2003, x86_64, Intel(R) Xeon(R) CPU           E5620  @ 2.40GHz, Python 3.6.8
See https://gist.github.com/c31db8820823f00fcfd1679964491431 for a full test report.

**Comment by furstj** [comment]
Test report by @furstj
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
kronos.fsik.cvut.cz - Linux centos linux 7.8.2003, x86_64, Intel(R) Xeon(R) CPU           E5620  @ 2.40GHz, Python 3.6.8
See https://gist.github.com/780a7306911da0b52561575cce13f1df for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
node3401.kirlia.os - Linux centos linux 7.8.2003, x86_64, Intel(R) Xeon(R) Gold 6240 CPU @ 2.60GHz (cascadelake), Python 2.7.5
See https://gist.github.com/ba2b539ae33ac7628fa1be7646ce59e9 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
generoso-x-5 - Linux centos linux 8.2.2004, x86_64, Intel(R) Xeon(R) CPU E5-2667 v3 @ 3.20GHz (haswell), Python 3.6.8
See https://gist.github.com/562dad7fe70f7f9636fa4c4917a2d8f3 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
node3119.skitty.os - Linux centos linux 7.8.2003, x86_64, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz (skylake_avx512), Python 3.6.8
See https://gist.github.com/a0f52cd5512280b6b2d30a8b775f72a1 for a full test report.

**Comment by boegel** [comment]
Going in, thanks @furstj!

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 3 out of 3 (1 easyconfigs in this PR)
node2672.swalot.os - Linux centos linux 7.8.2003, x86_64, Intel(R) Xeon(R) CPU E5-2660 v3 @ 2.60GHz (haswell), Python 2.7.5
See https://gist.github.com/d9dc7acd52f9bffcda4624ced3afd6c9 for a full test report.

**Pull request merged**
