### PR TITLE
{tools}[foss/2022a] Horovod v0.28.1 w/ PyTorch

### PR DESCRIPTION
**Pull request by Flamefire**
(created using `eb --new-pr`)

Add Horovod for all PyTorch versions where we don't have one yet.

### CODE REVIEW

**Comment by Flamefire** [comment]
Test report by @Flamefire
**SUCCESS**
Build succeeded for 6 out of 6 (6 easyconfigs in total)
taurusi8015 - Linux CentOS Linux 7.9.2009, x86_64, AMD EPYC 7352 24-Core Processor (zen2), Python 2.7.5
See https://gist.github.com/Flamefire/7d58b0d4a3d86dface39c83bf73e5a7d for a full test report.

**Comment by Flamefire** [comment]
Test report by @Flamefire
**SUCCESS**
Build succeeded for 6 out of 6 (6 easyconfigs in total)
taurusml4 - Linux RHEL 7.6, POWER, 8335-GTX (power9le), 6 x NVIDIA Tesla V100-SXM2-32GB, 440.64.00, Python 2.7.5
See https://gist.github.com/Flamefire/0ded4e313b97e46e416530edb6eba63b for a full test report.

**Review by branfosj — APPROVED** [review]

**Comment by branfosj** [comment]
Test report by @branfosj
**SUCCESS**
Build succeeded for 6 out of 6 (6 easyconfigs in total)
bear-pg0203u29a.bear.cluster - Linux RHEL 8.6, x86_64, Intel(R) Xeon(R) Platinum 8360Y CPU @ 2.40GHz (icelake), 1 x NVIDIA NVIDIA A100-SXM4-80GB, 520.61.05, Python 3.6.8
See https://gist.github.com/branfosj/b887c015def9eda4cb29ea1003a26392 for a full test report.

**Comment by branfosj** [comment]
Going in, thanks @Flamefire!

**Pull request merged**
