### PR TITLE
{lib}[GCC/9.3.0] Kent_tools v415, Boost v1.72.0, Judy v1.0.5, ...

### PR DESCRIPTION
**Pull request by verdurin**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by bartoldeman** [comment]
@boegelbot please test @ generoso

**Comment by bartoldeman** [comment]
Test report by @bartoldeman
**FAILED**
Build succeeded for 2 out of 4 (5 easyconfigs in total)
build-node.computecanada.ca - Linux centos linux 7.9.2009, x86_64, Intel Xeon Processor (Skylake, IBRS), Python 3.7.7
See https://gist.github.com/29da250f2d39d49c7452a002c8fa05db for a full test report.

**Comment by bartoldeman** [comment]
Test report by @bartoldeman
**SUCCESS**
Build succeeded for 4 out of 4 (5 easyconfigs in total)
build-node.computecanada.ca - Linux centos linux 7.9.2009, x86_64, Intel Xeon Processor (Skylake, IBRS), Python 3.7.7
See https://gist.github.com/56e9b234cd55c69d773237551b4e7076 for a full test report.

**Review by bartoldeman — CHANGES_REQUESTED** [review]
Since there's already `Boost-1.72.0-GCCcore-9.3.0-no_mpi.eb` why not use that instead?
I know for newer toolchains this is consistent though.

**Comment by verdurin** [comment]
> Since there's already `Boost-1.72.0-GCCcore-9.3.0-no_mpi.eb` why not use that instead?
> I know for newer toolchains this is consistent though.

It's a fair point, I think at the time I wondered whether it was just an oversight that there was no "normal" Boost EC for that toolchain and this release.

**Comment by boegel** [comment]
> > Since there's already `Boost-1.72.0-GCCcore-9.3.0-no_mpi.eb` why not use that instead?
> > I know for newer toolchains this is consistent though.
> 
> It's a fair point, I think at the time I wondered whether it was just an oversight that there was no "normal" Boost EC for that toolchain and this release.

Using the existing `no_mpi` one makes sense (like we already do in `SOCI-4.0.1-GCCcore-9.3.0.eb`)?

**Comment by boegel** [comment]
closing this since `GCC/9.3.0` is deprecated, see https://docs.easybuild.io/policies/toolchains

**Pull request closed without merging**
