### PR TITLE
{vis}[GCCcore/11.3.0] Graphviz v5.0.0 w/ Python 3.10.4

### PR DESCRIPTION
**Pull request by sassy-crick**
(created using `eb --new-pr`)

Requires:
- [x] PR #15947
- [x] PR #15951
- [x] PR #15952

### CODE REVIEW

**Comment by sassy-crick** [comment]
@jfgrimm  I think we got all the dependencies now. Could you just start the tests again please? Thanks.

**Comment by Micket** [comment]
@sassy-crick tip:
```
eb --sync-pr-with-develop 15953
```
will retrigger tests.
I have it set as an alias
```
alias ebsync='eb --sync-pr-with-develop '
```
since we maintainers do this a lot to everyones PRs

**Comment by Micket** [comment]
Test report by @Micket
**SUCCESS**
Build succeeded for 2 out of 2 (1 easyconfigs in total)
alvis-c1 - Linux Rocky Linux 8.5, x86_64, Intel Xeon Processor (Skylake), Python 3.6.8
See https://gist.github.com/099203ac4617e7780ddfabb162e4301f for a full test report.

**Review by boegel — APPROVED** [review]
lgtm

**Comment by boegel** [comment]
@boegelbot please test @ generoso

**Comment by boegel** [comment]
Test report by @boegel
**FAILED**
Build succeeded for 0 out of 1 (1 easyconfigs in total)
node3100.skitty.os - Linux RHEL 8.4, x86_64, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz (skylake_avx512), Python 3.6.8
See https://gist.github.com/189fa2263eef5137e0854d3dccec2f2d for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
node3100.skitty.os - Linux RHEL 8.4, x86_64, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz (skylake_avx512), Python 3.6.8
See https://gist.github.com/5fb08ec7fc3da005922d792829458026 for a full test report.

**Comment by boegel** [comment]
Going in, thanks @sassy-crick!

**Pull request merged**
