### PR TITLE
{geo,tools}[GCCcore/10.3.0,foss/2021a] tcsh v6.22.04, WRF v4.3

### PR DESCRIPTION
**Pull request by maxim-masterov**
(created using `eb --new-pr`)

### CODE REVIEW

**Review by branfosj — CHANGES_REQUESTED** [review]

**Comment by SebastianAchilles** [comment]
Test report by @sebastianachilles
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in total)
rocky8-eb - Linux rocky linux 8.4, x86_64, Intel(R) Core(TM) i7-6900K CPU @ 3.20GHz (broadwell), Python 3.6.8
See https://gist.github.com/c84ae75d9252a183e808ffa874b7bee3 for a full test report.

**Comment by branfosj** [comment]
@boegelbot please test @ generoso

**Comment by branfosj** [comment]
Test report by @branfosj
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in total)
bear-pg0211u03a.bear.cluster - Linux RHEL 8.3, x86_64, Intel(R) Xeon(R) Gold 6248 CPU @ 2.50GHz (cascadelake), Python 3.6.8
See https://gist.github.com/2cbd2acd4673cfe29e93e1453a5815ce for a full test report.

**Review by maxim-masterov — COMMENTED** [review]
Added the description, based on the previous patch WRFv4_netCDF-Fortran_separate_path.patch

**Review by branfosj — APPROVED** [review]

**Comment by branfosj** [comment]
Going in, thanks @maxim-masterov!

**Pull request merged**
