### PR TITLE
{bio}[foss/2022a] plot1cell v0.0.1, DoubletFinder v2.0.3-20230131, loomR v0.2.0-20180425 w/ R.4.2.1

### PR DESCRIPTION
**Pull request by boegel**
(created using `eb --new-pr`)

requires:
* #17493
* #17494

### CODE REVIEW

**Comment by boegel** [comment]
@boegelbot please test @ generoso

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 3 out of 3 (3 easyconfigs in total)
node3135.skitty.os - Linux RHEL 8.6, x86_64, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz (skylake_avx512), Python 3.6.8
See https://gist.github.com/025fb90b73dd0bea878c7f0d6a4a4cfa for a full test report.

**Comment by casparvl** [comment]
@boegelbot please test @ jsc-zen2

**Review by casparvl — APPROVED** [review]
No surprises, lgtm!

**Comment by casparvl** [comment]
Going in, thanks @boegel!

**Pull request merged**
