### PR TITLE
{bio}[gompi/2023b] ABRicate v1.0.0, BLAST+ v2.16.0, BWA v0.7.18, ... w/ _saute.1.3.0_2

### PR DESCRIPTION
**Pull request by akesandgren**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by akesandgren** [comment]
@boegelbot Please test @ jsc-zen3

**Comment by verdurin** [comment]
@boegelbot please test @ generoso

**Review by verdurin — APPROVED** [review]
Looks fine.

**Comment by verdurin** [comment]
Going in, thanks @akesandgren!

**Pull request merged**
