### PR TITLE
{data}[foss/2017b,intel/2017b] RStan v2.18.2 w/ R 3.4.3

### PR DESCRIPTION
**Pull request by vanzod**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by vanzod** [comment]
Test report by @vanzod
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in this PR)
cermis - Linux debian 9.8, Intel(R) Xeon(R) CPU           X5670  @ 2.93GHz, Python 2.7.13
See https://gist.github.com/b06ab657e8f6a96feec6073e4d7f956a for a full test report.

**Comment by boegel** [comment]
(close/re-open to let Travis pick up latest `develop` for framework)

**Comment by vanzod** [comment]
@boegel Can you run some tests please?

**Comment by verdurin** [comment]
Test report by @verdurin
**FAILED**
Build succeeded for 14 out of 18 (2 easyconfigs in this PR)
rescomp2 - Linux centos linux 7.3.1611, Intel(R) Xeon(R) Gold 6126 CPU @ 2.60GHz, Python 2.7.5
See https://gist.github.com/81b27a74c603cbf7a5090cd704b06cbe for a full test report.

**Comment by verdurin** [comment]
@vanzod I tried and (inevitably) some of the package checksums have changed for `R/3.4.3`.

**Comment by boegel** [comment]
@verdurin You should re-download the `boot` tarball, since it changed upstream (the checksum we have currently is the right one), see also #8054

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in this PR)
node2003.delcatty.os - Linux centos linux 7.6.1810, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.7.5
See https://gist.github.com/8940ebe5345ab21e4dd35ac6fcf69b38 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in this PR)
node2410.golett.os - Linux centos linux 7.6.1810, Intel(R) Xeon(R) CPU E5-2680 v3 @ 2.50GHz, Python 2.7.5
See https://gist.github.com/db4d2054b0d61dc971927fa3f1eacdf8 for a full test report.

**Comment by boegel** [comment]
Going in, thanks @vanzod!

**Pull request merged**
