### PR TITLE
{bio}[GCC/10.3.0] BLAT v3.7

### PR DESCRIPTION
**Pull request by pberthier**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by pberthier** [comment]
Test report by @pberthier
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
softdev8.ibu.internal - Linux Rocky Linux 8.8 (Green Obsidian), x86_64, AMD EPYC 7742 64-Core Processor, Python 3.11.2
See https://gist.github.com/pberthier/933eb244f1f0f31f6160b07be8246291 for a full test report.

**Comment by SebastianAchilles** [comment]
@boegelbot please test @ generoso

**Comment by SebastianAchilles** [comment]
@boegelbot please test @ jsc-zen2

**Review by SebastianAchilles — APPROVED** [review]
lgtm

**Comment by SebastianAchilles** [comment]
Going in, thanks @pberthier!

**Pull request merged**
