### PR TITLE
WIP {bio}[foss/2021a] GROMACS v2021.2 w/ Python 3.9.5

### PR DESCRIPTION
**Pull request by robert-mijakovic**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by robert-mijakovic** [comment]
@boegelbot: please test @ generoso

**Comment by robert-mijakovic** [comment]
Test report by @robert-mijakovic
**FAILED**
Build succeeded for 1 out of 2 (1 easyconfigs in total)
login01.meluxina.lxp.lu - Linux RHEL 8.3, x86_64, AMD EPYC 7452 32-Core Processor (zen2), Python 3.6.8
See https://gist.github.com/9d4730b58190d62a92c530385085b571 for a full test report.

**Comment by robert-mijakovic** [comment]
@boegelbot: please test @ generoso

**Comment by robert-mijakovic** [comment]
GROMACS EB assumes the existence of a static FlexiBLAS library which doesn't hold, thus, it throws the following error:
```
-- Checking that user BLAS library /home/apps/USE/easybuild/staging/2021.1/software/FlexiBLAS/3.0.4-GCC-10.3.0/lib/libflexiblas.a works
-- Looking for dgemm_
-- Looking for dgemm_ - not found
CMake Warning at cmake/gmxManageLinearAlgebraLibraries.cmake:78 (message):
  GMX_BLAS_USER library
  /home/apps/USE/easybuild/staging/2021.1/software/FlexiBLAS/3.0.4-GCC-10.3.0/lib/libflexiblas.a
  was specified, but it may not provide BLAS.  We are proceeding by assuming
  you know what you are doing and that linking F77-style to this library will
  work.
```

**Comment by branfosj** [comment]
https://github.com/easybuilders/easybuild-easyblocks/pull/2552 added FlexiBLAS support in the GROMACS easyblock. As we've got 2021.3 easyconfigs in foss/2021a I'll close this.

**Pull request closed without merging**
