### PR TITLE
consistently use ON/OFF for -DBUILD_SHARED_LIBS

### PR DESCRIPTION
**Pull request by Flamefire**
CMake defines options as uppercase:
> True if the constant is 1, ON, YES, TRUE, Y, or a non-zero number
> False if the constant is 0, OFF, NO, FALSE, N, IGNORE, NOTFOUND, the empty string, or ends in the suffix -NOTFOUND

Although it (now?) says "Named boolean constants are case-insensitive." this may not have always been the case.
So make all values for `-DBUILD_SHARED_LIBS`  ON/OFF to be consistent.

### CODE REVIEW

**Comment by Flamefire** [comment]
Test report by @Flamefire
**FAILED**
Build succeeded for 28 out of 51 (22 easyconfigs in total)
taurusml5 - Linux RHEL 7.6, POWER, 8335-GTX (power9le), 6 x NVIDIA Tesla V100-SXM2-32GB, 440.64.00, Python 2.7.5
See https://gist.github.com/Flamefire/2cf8af6634c481527d0de528dcee5a63 for a full test report.

**Comment by Flamefire** [comment]
Test report by @Flamefire
**SUCCESS**
Build succeeded for 21 out of 21 (21 easyconfigs in total)
taurusml5 - Linux RHEL 7.6, POWER, 8335-GTX (power9le), 6 x NVIDIA Tesla V100-SXM2-32GB, 440.64.00, Python 2.7.5
See https://gist.github.com/Flamefire/669653ba8620e3968003fc6aa21fae37 for a full test report.

**Review by boegel — APPROVED** [review]
lgtm

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 22 out of 22 (22 easyconfigs in total)
node3102.skitty.os - Linux RHEL 8.6, x86_64, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz (skylake_avx512), Python 3.6.8
See https://gist.github.com/boegel/ed962a90dae9d7799372ddab79e52b2f for a full test report.

**Comment by boegel** [comment]
Going in, thanks @Flamefire!

**Pull request merged**
