### PR TITLE
{lang}[GCCcore/7.3.0] Guile v2.2.4

### PR DESCRIPTION
**Pull request by juriroemer**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by boegel** [comment]
@juriroemer Why did you remove `gc-7.6.4-GCCcore-7.3.0.eb`?

**Comment by juriroemer** [comment]
@boegel because it already was in the development branche, I just hadn't seen it (and I did some weird hard coding thing by accident, so the existing version was better).

**Comment by boegel** [comment]
@juriroemer Seems like you accidentally removed the one that's in `develop`, see https://github.com/easybuilders/easybuild-easyconfigs/pull/6705/files

**Comment by juriroemer** [comment]
@boegel oh sorry, that wasn't my intention, I wanted to delete my version

**Comment by boegel** [comment]
@juriroemer The easiest way forward is probably to open a new PR with the easyconfig file for `Guile` (and close this one), or to copy back the original `gc-7.6.4-GCCcore-7.3.0.eb` (which you can grab from https://github.com/easybuilders/easybuild-easyconfigs/blob/master/easybuild/easyconfigs/g/gc/gc-7.6.0-GCCcore-6.4.0.eb.

No harm done for now, as long as we don't merge this PR (which we can't since the tests are failing), so don't worry about it. :)

**Comment by juriroemer** [comment]
@boegel alright I'll open a new PR when I'm in the office tomorrow :)

**Pull request closed without merging**
