### PR TITLE
{bio}[foss/2021a] RELION v4.0_beta.2022.04.20

### PR DESCRIPTION
**Pull request by jfgrimm**
(created using `eb --new-pr`)

draft for now, one of our academics reported an issue with building RELION with this CUDA version: https://github.com/3dem/relion/issues/893

easyblock PR: https://github.com/easybuilders/easybuild-easyblocks/pull/2773

### CODE REVIEW

**Comment by mtwest2718** [comment]
Testing out this PR on the system here in Exeter. Of the 11 missing modules, the only one that gives me pause is the CUDA/11.3.1 requirement. We currently just have K80s in our system and from my parsing of the [release notes](https://docs.nvidia.com/deploy/cuda-compatibility/index.html), these cards are not supported in CUDA 11.

**Comment by mtwest2718** [comment]
In addition, is it worth adding the other libraries mentioned in the [installation doc](https://relion.readthedocs.io/en/release-4.0/Installation.html) as requirements to the explicit dependencies list?
- MPI
- CTFFIND
- Ghostscript
- FFTW
- libpng
Also, X11 and FLTK are listed as dependencies even though those are only for GUI work.

**Comment by jfgrimm** [comment]
> Testing out this PR on the system here in Exeter. Of the 11 missing modules, the only one that gives me pause is the CUDA/11.3.1 requirement. We currently just have K80s in our system and from my parsing of the [release notes](https://docs.nvidia.com/deploy/cuda-compatibility/index.html), these cards are not supported in CUDA 11.

CUDA/11.3.1 is the default CUDA version throughout the foss/2021a toolchain; if this is problematic for your site you could consider replacing all instances of this with an older CUDA using a hook for example.

**Comment by mruetter** [comment]
May I ask where you define the configopts and if you have build for single or double precision GPU? We have it running on our A100 SXM with CUDA 11.x and the configopts `...-DDoublePrec_CPU=ON -DDoublePrec_GPU=ON -DCUDA_ARCH='89'...` without issues so far.

**Comment by jfgrimm** [comment]
@mruetter in the complementary easyblock PR: https://github.com/easybuilders/easybuild-easyblocks/pull/2773

**Review by jfgrimm — COMMENTED** [review]
As decided in issue #16330, we have deprecated the use of `True` to signify a system-toolchain dependency (#16384), in favour of the more intuitive `SYSTEM` template constant. Due to the change in the test suite, please run `eb --sync-pr-with-develop 16022` and update the PR to use `SYSTEM` instead.

**Comment by cjroberts** [comment]
Hello, I am trying to use a minimally altered version of the non-CUDA EasyConfig from this PR to install RELION 4.0.0 on our systems in Oxford now it has been released. May I ask why there is a line to use the CMakeMake EasyBlock rather than the associated custom RELION EasyBlock? The sanity checks fail for me with this line in place, but if I remove it the software builds successfully.

**Comment by jfgrimm** [comment]
> Hello, I am trying to use a minimally altered version of the non-CUDA EasyConfig from this PR to install RELION 4.0.0 on our systems in Oxford now it has been released. May I ask why there is a line to use the CMakeMake EasyBlock rather than the associated custom RELION EasyBlock? The sanity checks fail for me with this line in place, but if I remove it the software builds successfully.


Oversight on my part, it should indeed be removed. I'll try and find some time to take another look at this to get it ready for review

**Pull request closed without merging**
