### PR TITLE
fix checksum for mgcv extension in R 3.5.* easyconfigs

### PR DESCRIPTION
**Pull request by boegel**
Another in-place update of an R package, hooray...

This has happened before for a previous version of this same package `mgcv`, see #6502 .

cc @JoFAM

### CODE REVIEW

**Comment by ocaisa** [comment]
Waiting on a test report for the merge

**Comment by ocaisa** [comment]
@boegel Sorry, should've waited for a test report (just in case)

**Comment by boegel** [comment]
diff between old and new tarball is (again) only in the package description:

```diff
$ diff -ru mgcv.new mgcv.old
diff -ru mgcv.new/DESCRIPTION mgcv.old/DESCRIPTION
--- mgcv.new/DESCRIPTION        2018-06-23 18:07:43.000000000 +0200
+++ mgcv.old/DESCRIPTION        2018-06-18 21:07:59.000000000 +0200
@@ -20,4 +20,4 @@
 NeedsCompilation: yes
 Packaged: 2018-06-18 13:08:20 UTC; sw283
 Repository: CRAN
-Date/Publication: 2018-06-23 16:07:43 UTC
+Date/Publication: 2018-06-18 19:07:59 UTC
diff -ru mgcv.new/MD5 mgcv.old/MD5
--- mgcv.new/MD5        2018-06-23 18:07:43.000000000 +0200
+++ mgcv.old/MD5        2018-06-18 21:07:59.000000000 +0200
@@ -1,5 +1,5 @@
 3d3df9183a9b061dc8c4fce64fc30fef *ChangeLog
-c3ebcf3c3ee052794c3b0c7a4d5b84b5 *DESCRIPTION
+57abeb2a1390e7e8d3727fa3d69b589f *DESCRIPTION
 eb723b61539feef013de476e68b5c50a *GPL-2
 723a559e94082d3a7c70651cbcb08dd8 *NAMESPACE
 6e5f0f0d0b69f7082e9ecd4aad1f1374 *R/bam.r
```

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 3 out of 3 (3 easyconfigs in this PR)
node2060.delcatty.os - Linux centos linux 7.5.1804, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.7.5
See https://gist.github.com/6168e5ee2132eaa1b99198882f01db99 for a full test report.

**Comment by JoFAM** [comment]
@boegel reported -again- to R core. But I have little hope they're going to change something in the near future...

https://stat.ethz.ch/pipermail/r-devel/2018-November/077016.html

**Comment by boegel** [comment]
@JoFAM Thanks!

**Pull request merged**
