### PR TITLE
{chem}[foss/2016b] NAMD v2.12

### PR DESCRIPTION
**Pull request by jrbosch**
Add NAMD easyconfig file with gpu support.

### CODE REVIEW

**Comment by jrbosch** [comment]
I couldn't use CUDA v 9, because I thing NAMD 2.12 use some cuda functions that were declared deprecated in this cuda version. I am waiting for some tests form one user to I change it from wip to review state.

**Comment by boegel** [comment]
@akesandgren Thoughts on NAMD 2.12 vs CUDA 9?

**Comment by akesandgren** [comment]
No idea about that combo yet.

**Comment by jrbosch** [comment]
@akesandgren @boegel I think this is ok. Here Charm++ is compiled for multicore-linux64 arch, that is for a single node, maybe the versionsuffix should be single-node-cuda or something like this ?, since there can be a multi-node version too. Regards.

**Comment by migueldiascosta** [comment]
@jrbosch is this still relevant?

**Comment by lexming** [comment]
Test report by @lexming
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
node154.hydra.os - Linux centos linux 7.7.1908, x86_64, Intel(R) Xeon(R) CPU E5-2680 v2 @ 2.80GHz, Python 2.7.5
See https://gist.github.com/ded338dec1f4a35d4b61f1595f3023e2 for a full test report.

**Review by lexming — DISMISSED** [review]
Ideally, this easyconfig should use `gcccuda/2016.10` because it does not require MPI. However, that toolchain is already archived and switching to it would need new easyconfigs for Tcl and serial  FFTW. Therefore, using `foss` with the added `CUDA` is a good solution.

**Comment by lexming** [comment]
Test report by @lexming
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
node154.hydra.os - Linux centos linux 7.7.1908, x86_64, Intel(R) Xeon(R) CPU E5-2680 v2 @ 2.80GHz, Python 2.7.5
See https://gist.github.com/e45e10025a855fbd71daf77658a7ec13 for a full test report.

**Review by lexming — APPROVED** [review]
LGTM

**Comment by boegel** [comment]
Test report by @boegel
**FAILED**
Build succeeded for 0 out of 1 (1 easyconfigs in total)
node2603.swalot.os - Linux centos linux 7.8.2003, x86_64, Intel(R) Xeon(R) CPU E5-2660 v3 @ 2.60GHz (haswell), Python 2.7.5
See https://gist.github.com/5bea592080e701290034c3697b9c7010 for a full test report.

**Comment by boegel** [comment]
Ah, no GPUs on that box...

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
node3305.joltik.os - Linux centos linux 7.8.2003, x86_64, Intel(R) Xeon(R) Gold 6242 CPU @ 2.80GHz (cascadelake), Python 3.6.8
See https://gist.github.com/a118cb542884b6de9c2d8eba9427edc9 for a full test report.

**Comment by boegel** [comment]
Going in, thanks @jrbosch!

**Comment by jrbosch** [comment]
> Going in, thanks @jrbosch!

Thank you very much @boegel @migueldiascosta @lexming , sorry not to contribute more to you with this, I am currently a bit out of this matter. Regards!!!!

**Pull request merged**
