### PR TITLE
{phys}[intel/2018a] FDS v6.7.0

### PR DESCRIPTION
**Pull request by boegel**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
node3150.skitty.os - Linux centos linux 7.4.1708, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz, Python 2.7.5
See https://gist.github.com/9be1644b743b21f18caafa6aae2d05af for a full test report.

**Comment by verdurin** [comment]
Test report by @verdurin
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
rescomp2 - Linux centos 6.8, Intel(R) Xeon(R) CPU E5-2650 v2 @ 2.60GHz, Python 2.7.11
See https://gist.github.com/2af1fdf4ae3a9223ec6b03dbbc8a6ca7 for a full test report.

**Comment by verdurin** [comment]
@boegel policy query - what's the current policy on making an update like this within a toolchain release?

**Comment by boegel** [comment]
@verdurin We don't have restrictions in place for "end-user applications" like `FDS`, only for things that are (commonly) used as dependencies, since the latter helps a lot with avoiding to introduce version conflicts when multiple modules built with the same toolchain are loaded together.

**Comment by verdurin** [comment]
Going in, thanks @boegel!

**Pull request merged**
