### PR TITLE
{tools}[foss/2020a,fosscuda/2020a] Horovod v0.21.0 w/ Python 3.8.2

### PR DESCRIPTION
**Pull request by casparvl**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by casparvl** [comment]
Could anyone review this, maybe @Flamefire ? I think it should be pretty straightforward for you :)

**Comment by Flamefire** [comment]
I would suggest using 0.21.3, which is the latest release. Also for fosscuda the `parallel = 1` is likely still required. See my PR for 2020b: https://github.com/easybuilders/easybuild-easyconfigs/pull/12473

In that I also added the explicit NCCL dependency (before it was implicit through TF, but better do it explicit)

**Comment by casparvl** [comment]
Ok, I made the changes you suggested :)

**Comment by Flamefire** [comment]
Test report by @Flamefire
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in total)
taurusml2 - Linux RHEL 7.6, POWER, 8335-GTX (power9le), Python 2.7.5
See https://gist.github.com/a3dc55f9904dab7b0338682c02387ccb for a full test report.

**Comment by casparvl** [comment]
@boegelbot Please test @ generoso

**Comment by lexming** [comment]
Test report by @lexming
**FAILED**
Build succeeded for 1 out of 2 (2 easyconfigs in total)
node226.hydra.os - Linux centos linux 7.9.2009, x86_64, Intel(R) Xeon(R) CPU E5-2680 v4 @ 2.40GHz, Python 2.7.5
See https://gist.github.com/7b43f6fbfcc5326bf5d7c33732e09b0e for a full test report.

**Comment by Flamefire** [comment]
@lexming 
> Lmod has detected the following error: A different version of the 'NCCL'
module is already loaded (see output of 'ml').
You should load another 'TensorFlow' module that is compatible with the
currently loaded version of 'NCCL'.

Have you modified your TF EC?

**Comment by lexming** [comment]
@Flamefire yes :slightly_smiling_face: I always forget about it

**Comment by lexming** [comment]
Test report by @lexming
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in total)
node222.hydra.os - Linux centos linux 7.9.2009, x86_64, Intel(R) Xeon(R) CPU E5-2680 v4 @ 2.40GHz, Python 2.7.5
See https://gist.github.com/a01ce1b1527b8a941596332cabc2662f for a full test report.

**Review by lexming — APPROVED** [review]
LGTM

**Comment by lexming** [comment]
Going in, thanks @casparvl !

**Pull request merged**
