### PR TITLE
{vis}[dummy/dummy] Tigervnc v1.9.0

### PR DESCRIPTION
**Pull request by sassy-crick**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by sassy-crick** [comment]
Test report by @sassy-crick
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
login002.camp.thecrick.org - Linux RHEL 7.3, Intel(R) Xeon(R) CPU E5-2640 v3 @ 2.60GHz, Python 2.7.5
See https://gist.github.com/72aeb4dc4abf769bb4e8115b494c139c for a full test report.

**Comment by sassy-crick** [comment]
@boegel sanity_check_paths added. Lets see if Travis is having issues with the format of the script.

**Comment by vanzod** [comment]
Test report by @vanzod
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
cermis - Linux debian 9.7, Intel(R) Xeon(R) CPU           X5670  @ 2.93GHz, Python 2.7.13
See https://gist.github.com/dc0c2ca843253ab713fc25ee12959d1f for a full test report.

**Comment by vanzod** [comment]
@sassy-crick The problem I have seen is that if you run this `Tigervnc` on a machine with a minimal OS (hence without X11), it will fail with the error log below. Unfortunately I cannot find the directories it is looking for in the EB installed X11, so adding X11 as a dependency may not help here.
@boegel Suggestions? Maybe add an `osdeps`?

```
davide@cermis:~$ vncserver -depth 24
Could not start Xvnc.


Xvnc TigerVNC 1.9.0 - built Jul 16 2018 14:18:04
Copyright (C) 1999-2018 TigerVNC Team and many others (see README.rst)
See http://www.tigervnc.org for information on TigerVNC.
Underlying X server release 11400000, The X.Org Foundation

Initializing built-in extension VNC-EXTENSION
Initializing built-in extension Generic Event Extension
Initializing built-in extension SHAPE
Initializing built-in extension MIT-SHM
Initializing built-in extension XInputExtension
Initializing built-in extension XTEST
Initializing built-in extension BIG-REQUESTS
Initializing built-in extension SYNC
Initializing built-in extension XKEYBOARD
Initializing built-in extension XC-MISC
Initializing built-in extension XINERAMA
Initializing built-in extension XFIXES
Initializing built-in extension RENDER
Initializing built-in extension RANDR
Initializing built-in extension COMPOSITE
Initializing built-in extension DAMAGE
Initializing built-in extension MIT-SCREEN-SAVER
Initializing built-in extension DOUBLE-BUFFER
Initializing built-in extension RECORD
Initializing built-in extension DPMS
Initializing built-in extension X-Resource
Initializing built-in extension XVideo
Initializing built-in extension XVideo-MotionCompensation
Initializing built-in extension GLX

Wed Feb 20 09:46:10 2019
 vncext:      VNC extension running!
 vncext:      Listening for VNC connections on all interface(s), port 5901
 vncext:      created VNC server for screen 0
[dix] Could not init font path element catalogue:/etc/X11/fontpath.d, removing from list!
[dix] Could not init font path element /usr/share/X11/fonts/misc, removing from list!
[dix] Could not init font path element /usr/share/X11/fonts/75dpi, removing from list!
[dix] Could not init font path element /usr/share/X11/fonts/100dpi, removing from list!
[dix] Could not init font path element /usr/share/X11/fonts/Type1, removing from list!
[dix] Could not init font path element /usr/share/X11/fonts/TTF, removing from list!
[dix] Could not init font path element /usr/share/fonts/default/Type1, removing from list!
[dix] Could not init font path element /usr/share/fonts/X11/misc, removing from list!
[dix] Could not init font path element /usr/share/fonts/X11/Type1, removing from list!
[dix] Could not init font path element /usr/share/fonts/misc, removing from list!
[dix] Could not init font path element /usr/share/fonts/75dpi, removing from list!
[dix] Could not init font path element /usr/share/fonts/100dpi, removing from list!
[dix] Could not init font path element /usr/share/fonts/Type1, removing from list!
[dix] Could not init font path element /usr/share/fonts/URW, removing from list!
[dix] Could not init font path element /usr/share/fonts/Speedo, removing from list!
[dix] Could not init font path element /usr/share/fonts/cyrillic, removing from list!
[dix] Could not init font path element /usr/share/fonts/truetype, removing from list!
[dix] Could not init font path element /usr/share/fonts/misc, removing from list!
sh: 1: /usr/bin/xkbcomp: not found
sh: 1: /usr/bin/xkbcomp: not found
XKB: Failed to compile keymap
Keyboard initialization failed. This could be a missing or incorrect setup of xkeyboard-config.

Fatal server error:
Failed to activate core devices.
```

**Comment by akesandgren** [comment]
Does this really belong under EasyBuild? I would classify this as a typical system software.

**Comment by vanzod** [comment]
@akesandgren Good point

**Comment by sassy-crick** [comment]
@boegel sanity_check_paths added. Lets see if Travis is having issues with the format of the script.

**Comment by sassy-crick** [comment]
@akesandgren good question. As we are installing everything but the OS with EasyBuild, I had to create a build script and I thought I am simply sharing this. I will not be mortally offended if @boegel  decides we do not need to have a build script here.

**Comment by sassy-crick** [comment]
@akesandgren good question. As we are installing everything but the OS with EasyBuild, I had to create a build script and I thought I am simply sharing this. I will not be mortally offended if @boegel  decides we do not need to have a build script here.

**Comment by sassy-crick** [comment]
Further the last comment: as we have our software stack centrally installed, we don't need to install TigerVNC on each and every node we use. I leave this, together with VirtualGL (PR 8008) up to @boegel  to decide what he wants to do with it.

**Comment by boegel** [comment]
Well, since this one seems a bit problematic as @vanzod pointed out, it would certainly need more work before we can merge it in.

My feeling is that this isn't worth the effort, seems out of scope for EasyBuild...

@sassy-crick If you agree, please close.

**Comment by sassy-crick** [comment]
Further the last comment: as we have our software stack centrally installed, we don't need to install TigerVNC on each and every node we use. I leave this, together with VirtualGL (PR 8008) up to @boegel  to decide what he wants to do with it.

**Comment by sassy-crick** [comment]
I guess it is one of these borderline-cases where you could argue in either directions. We build X11 for example and here you could argue it is system as well. :-)
Having said this I am also happy to close it which is what I am doing. 
Thanks for your help here!

**Pull request closed without merging**
