### PR TITLE
add NSS dependency to recent Python 3 easyconfigs

### PR DESCRIPTION
**Pull request by jfgrimm**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by boegel** [comment]
@boegelbot please test @ generoso

**Comment by boegel** [comment]
@jfgrimm Hmm, any idea if this could be tied to adding `NSS` as a dependency?

```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/project/boegelbot/Rocky8/haswell/software/Python/3.7.4-GCCcore-8.3.0/lib/python3.7/site-packages/cryptography/hazmat/bindings/openssl/binding.py", line 15, in <module>
    from cryptography.hazmat.bindings._openssl import ffi, lib
ImportError: /project/boegelbot/Rocky8/haswell/software/Python/3.7.4-GCCcore-8.3.0/lib/python3.7/site-packages/cryptography/hazmat/bindings/_openssl.abi3.so: undefined symbol: SSL_ctrl
```

**Comment by jfgrimm** [comment]
@boegel I don't get that error, mine builds successfully (CentOS 7, using the OpenSSL installed through the wrapper).

**Comment by jfgrimm** [comment]
@boegelbot please test @ generoso

**Comment by boegel** [comment]
`Python` easyconfigs not using our `OpenSSL` wrapper are now failing sanity check on `cryptography`:

```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/project/boegelbot/Rocky8/haswell/software/Python/3.7.4-GCCcore-8.3.0/lib/python3.7/site-packages/cryptography/hazmat/bindings/openssl/binding.py", line 15, in <module>
    from cryptography.hazmat.bindings._openssl import ffi, lib
ImportError: /project/boegelbot/Rocky8/haswell/software/Python/3.7.4-GCCcore-8.3.0/lib/python3.7/site-packages/cryptography/hazmat/bindings/_openssl.abi3.so: undefined symbol: SSL_ctrl
```

**Review by jfgrimm — COMMENTED** [review]
As decided in issue #16330, we have deprecated the use of `True` to signify a system-toolchain dependency (#16384), in favour of the more intuitive `SYSTEM` template constant. Due to the change in the test suite, please run `eb --sync-pr-with-develop 15695` and update the PR to use `SYSTEM` instead.

**Pull request closed without merging**
