### PR TITLE
{chem}[intel-compilers/2023.1.0] libxc v6.2.2

### PR DESCRIPTION
**Pull request by schiotz**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by schiotz** [comment]
Test report by @schiotz
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
sylg.fysik.dtu.dk - Linux CentOS Linux 7.9.2009, x86_64, Intel(R) Xeon(R) CPU E5-2650 v4 @ 2.20GHz, Python 3.6.8
See https://gist.github.com/schiotz/c1c4180931ac43d402b48679858a7470 for a full test report.

**Comment by bedroge** [comment]
@boegelbot please test @ generoso

**Comment by bedroge** [comment]
@boegelbot please test @ jsc-zen2

**Comment by bedroge** [comment]
Going in, thanks @schiotz!

**Pull request merged**
