### PR TITLE
{lib}[GCCcore/12.3.0] libaio v0.3.113

### PR DESCRIPTION
**Pull request by laraPPr**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by laraPPr** [comment]
Test report by @laraPPr
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
gligar07.gastly.os - Linux RHEL 8.6 (Ootpa), x86_64, AMD EPYC 7532 32-Core Processor, Python 3.11.3
See https://gist.github.com/laraPPr/bc6aa00a18c18d7f51c2b38187542179 for a full test report.

**Comment by laraPPr** [comment]
Test report by @laraPPr
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
node3507.doduo.os - Linux RHEL 8.6 (Ootpa), x86_64, AMD EPYC 7552 48-Core Processor, Python 3.11.3
See https://gist.github.com/laraPPr/d61a1142aff4ceb86efa47a4c2991355 for a full test report.

**Comment by laraPPr** [comment]
@boegelbot please test @ generoso

**Comment by laraPPr** [comment]
@boegelbot please test @ jsc-zen2

**Review by branfosj — APPROVED** [review]

**Comment by branfosj** [comment]
Test report by @branfosj
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
bear-pg0105u03a.bear.cluster - Linux RHEL 8.6, x86_64, Intel(R) Xeon(R) Platinum 8360Y CPU @ 2.40GHz (icelake), Python 3.6.8
See https://gist.github.com/branfosj/2ed76481bde5bb5780f18ef24656bb7d for a full test report.

**Comment by branfosj** [comment]
Going in, thanks @laraPPr!

**Pull request merged**
