### PR TITLE
Remove mpi configure option from libfdf 0.2.2

### PR DESCRIPTION
**Pull request by Flamefire**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by jfgrimm** [comment]
@boegelbot: please test @ generoso
CORE_CNT=16

**Review by Micket — APPROVED** [review]
lgtm

**Comment by Micket** [comment]
Test report by @Micket
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in total)
vera-gpu1 - Linux Rocky Linux 8.9, x86_64, Intel(R) Xeon(R) Gold 6130 CPU @ 2.10GHz, 1 x NVIDIA Tesla V100-SXM2-32GB, 545.23.08, Python 3.6.8
See https://gist.github.com/Micket/8a86f58b1711f54c5dd93d7f88f3839b for a full test report.

**Comment by Micket** [comment]
I don't think the error on generoso failure is relevant here, definitely not caused by this change, so i'm ignoring it.

**Comment by Micket** [comment]
@boegelbot: please test @ jsc-zen3
EB_ARGS="libfdf-0.2.2-GCC-11.2.0-serial.eb libfdf-0.2.2-intel-compilers-2021.4.0-serial.eb"

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 6 out of 6 (6 easyconfigs in total)
node3118.skitty.os - Linux RHEL 8.8, x86_64, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz, Python 3.6.8
See https://gist.github.com/boegel/15a8d91faf006a1019a86bb25909ef0a for a full test report.

**Pull request merged**
