### PR TITLE
{bio}[foss/2018b] GROMACS v2018.1 with PLUMED 2.4.2

### PR DESCRIPTION
**Pull request by akesandgren**
(created using `eb --new-pr`)
GROMACS 2018.1 with PLUMED 2.4.2 for foss/2018b. Depends on PR ~~#6657~~

### CODE REVIEW

**Comment by jhein32** [comment]
I could build a Gromacs with the provided config on our own cluster, using a Plumed build with my own configs (should be identically to the ones in #6657

**Comment by verdurin** [comment]
Test report by @verdurin
**SUCCESS**
Build succeeded for 7 out of 7 (1 easyconfigs in this PR)
easybuild.novalocal - Linux centos linux 7.5.1804, Intel Xeon E312xx (Sandy Bridge), Python 2.7.5
See https://gist.github.com/9ea598191200038af75b97276f089c21 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
gligar02.gligar.os - Linux centos linux 7.4.1708, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.7.5
See https://gist.github.com/f07f056e7c1485f3944f3220067e0a76 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
node2532.golett.os - Linux centos linux 7.4.1708, Intel(R) Xeon(R) CPU E5-2680 v3 @ 2.50GHz, Python 2.7.5
See https://gist.github.com/f523904589919cd51d569065e6a73d30 for a full test report.

**Comment by boegel** [comment]
@verdurin Good to go?

**Comment by verdurin** [comment]
Going in, thanks @akesandgren!

**Pull request merged**
