### PR TITLE
Remove git version check and fix test command for molmod 1.4.8

### PR DESCRIPTION
**Pull request by Flamefire**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by Flamefire** [comment]
Test report by @Flamefire
**SUCCESS**
Build succeeded for 4 out of 4 (4 easyconfigs in total)
n1234 - Linux RHEL 8.7 (Ootpa), x86_64, Intel(R) Xeon(R) Platinum 8470 (icelake), Python 3.8.13
See https://gist.github.com/Flamefire/c5488359f54bf4d661cef66dc67c22a6 for a full test report.

**Comment by jfgrimm** [comment]
@boegelbot: please test @ generoso

**Comment by jfgrimm** [comment]
Test report by @jfgrimm
**SUCCESS**
Build succeeded for 4 out of 4 (4 easyconfigs in total)
node029.viking2.yor.alces.network - Linux Rocky Linux 8.8, x86_64, AMD EPYC 7643 48-Core Processor, Python 3.6.8
See https://gist.github.com/jfgrimm/eb6ca5bb9caad3e1aaf43182b4eca322 for a full test report.

**Comment by jfgrimm** [comment]
@boegelbot please test @ jsc-zen3

**Comment by Flamefire** [comment]
> Test report by @boegelbot **FAILED** Build succeeded for 3 out of 15 (4 easyconfigs in total) jsczen3c1.int.jsc-zen3.fz-juelich.de - Linux Rocky Linux 9.3, x86_64, AMD EPYC-Milan Processor (zen3), Python 3.9.18 See https://gist.github.com/boegelbot/3def03672610bfdd24c18f7b9c33c52e for a full test report.


Similar failure as in the TAMkin PR with Python3 failing to install due to (system?) OpenSSL 3 if I read that error right.

**Comment by jfgrimm** [comment]
looks like it

**Review by jfgrimm — APPROVED** [review]

**Comment by jfgrimm** [comment]
Going in, thanks @Flamefire!

**Pull request merged**
