### PR TITLE
{bio}[GCC/12.3.0] ModelTest-NG v0.2.0-dev_20220721

### PR DESCRIPTION
**Pull request by smoors**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by smoors** [comment]
Test report by @smoors
**SUCCESS**
Build succeeded for 3 out of 3 (3 easyconfigs in total)
node320.hydra.os - Linux Rocky Linux 8.8, x86_64, Intel(R) Xeon(R) Gold 6148 CPU @ 2.40GHz (skylake_avx512), Python 3.6.8
See https://gist.github.com/smoors/94a87c296af47f0f28385dfaabf2c76d for a full test report.

**Comment by smoors** [comment]
@boegelbot: please test @ generoso

**Comment by verdurin** [comment]
Test report by @verdurin
**SUCCESS**
Build succeeded for 3 out of 3 (3 easyconfigs in total)
easybuild-c7.novalocal - Linux CentOS Linux 7.9.2009, x86_64, Intel Xeon Processor (Skylake, IBRS), Python 3.6.8
See https://gist.github.com/verdurin/4652f8c3bb02c7b99e67303bf4813af7 for a full test report.

**Comment by verdurin** [comment]
@boegelbot please test @ jsc-zen3

**Comment by verdurin** [comment]
@smoors this was the error on `jsc-zen3`:
```
== 2024-01-23 15:01:22,062 build_log.py:171 ERROR EasyBuild crashed with an error (at easybuild/easybuild-framework/easybuild/base/exceptions.py:126 in __init__): cmd "libtoolize && ./autogen.sh &&  ./configure --prefix=/project/def-maintainers/boegelbot/rocky9/zen3/software/PLL-modules/0.4.1-GCC-12.3.0 CPPFLAGS="$CPPFLAGS -I$EBROOTLIBPLLMIN2/include/libpll"" exited with exit code 127 and output:
/bin/bash: line 1: libtoolize: command not found
 (at easybuild/easybuild-framework/easybuild/tools/run.py:682 in parse_cmd_output)
 ```

**Comment by smoors** [comment]
Test report by @smoors
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
node300.hydra.os - Linux Rocky Linux 8.8, x86_64, Intel(R) Xeon(R) Gold 6148 CPU @ 2.40GHz (skylake_avx512), Python 3.6.8
See https://gist.github.com/smoors/16d15cb54eed16af3c49277a3c5f4b6c for a full test report.

**Comment by smoors** [comment]
@boegelbot please test @ jsc-zen3

**Comment by smoors** [comment]
@boegelbot: please test @ generoso

**Review by lexming — APPROVED** [review]
LGTM

**Comment by lexming** [comment]
Merging, thanks @smoors !

**Pull request merged**
