### PR TITLE
{chem,lib}[intel/2022a] GlobalArrays v5.8.1, NWChem v7.0.2 w/ Python 3.10.4

### PR DESCRIPTION
**Pull request by maxim-masterov**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by anselmicz** [comment]
Test report by @anselmicz
**SUCCESS**
Build succeeded for 1 out of 1 (2 easyconfigs in total)
login4.karolina.it4i.cz - Linux CentOS Linux 7 (Core), x86_64, AMD EPYC 7452 32-Core Processor, Python 3.10.4
See https://gist.github.com/7b40b478cca7169cd42e0510da9760e6 for a full test report.

**Comment by akesandgren** [comment]
For no other reason then the fact that i recently submitted it, I'd suggest changing this to use Globalarrays/5.8.2, see #16767

**Comment by maxim-masterov** [comment]
@akesandgren We already have NWChem installed on all our systems with Globalarrays-5.8.1. Changing the dependency is, of course, possible but unwanted. Wouldn't it be better to use Globalarrays-5.8.2 with the newer NWChem release, or in the next 2022b toolchain?

**Comment by akesandgren** [comment]
Ok then :-) I was just lazy and wanted to avoid changing my own PR :-)

**Review by akesandgren — APPROVED** [review]
LGTM

**Comment by akesandgren** [comment]
@boegelbot Please test @ generoso

**Comment by akesandgren** [comment]
Going in, thanks @maxim-masterov!

**Pull request merged**
