### PR TITLE
{devel,lang}{dummy/}ReFrame-HPC v2.18, Python-bare v3.6.8

### PR DESCRIPTION
**Pull request by rsarm**

### CODE REVIEW

**Comment by boegel** [comment]
@rsarm Making `ReFrame` depend on a `Python-bare` is going to limit its usefulness quite a bit I think.

Wouldn't it make more sense to specify an OS dependency on `python3` instead, much like we do for EasyBuild itself (cfr. https://github.com/easybuilders/easybuild-easyconfigs/blob/master/easybuild/easyconfigs/e/EasyBuild/EasyBuild-3.9.0.eb#L43)?

**Comment by vkarak** [comment]
@boegel Good point, thank you!

**Comment by vkarak** [comment]
@boegel Is there a way to check in the EB recipe if a specific OS version of python is available?

**Comment by vkarak** [comment]
@boegel You may close this PR cos it's replaced by #8481.

**Pull request closed without merging**
