### PR TITLE
{compiler}[system/system] GCC v10.1.0

### PR DESCRIPTION
**Pull request by boegel**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 8 out of 8 (8 easyconfigs in this PR)
node3413.kirlia.os - Linux centos linux 7.7.1908, x86_64, Intel(R) Xeon(R) Gold 6240 CPU @ 2.60GHz (cascadelake), Python 2.7.5
See https://gist.github.com/e9eff551fa4aea8f5e958249d4a23fe6 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 8 out of 8 (8 easyconfigs in this PR)
generoso-1 - Linux centos linux 7.6.1810, x86_64, Intel(R) Xeon(R) CPU E5-2660 v4 @ 2.00GHz, Python 3.6.8
See https://gist.github.com/9a5a21fafa9e50af335aa98f492b23fd for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 8 out of 8 (8 easyconfigs in this PR)
node3110.skitty.os - Linux centos linux 7.7.1908, x86_64, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz (skylake_avx512), Python 3.6.8
See https://gist.github.com/f27c833b383242a501e57b91dc2c818c for a full test report.

**Comment by terjekv** [comment]
Test report by @terjekv
**SUCCESS**
Build succeeded for 10 out of 10 (8 easyconfigs in this PR)
ninhursaga.uio.no - Linux RHEL 8.2, Intel(R) Xeon(R) Silver 4216 CPU @ 2.10GHz, Python 3.6.8
See https://gist.github.com/ac95d5c5f34da1a2ab937817616d2b39 for a full test report.

**Comment by rjeschmi** [comment]
Test report by @rjeschmi
**FAILED**
Build succeeded for 0 out of 8 (8 easyconfigs in this PR)
ryzen37 - Linux Ubuntu 20.04, x86_64, AMD Ryzen 7 3700X 8-Core Processor, Python 3.8.2
See https://gist.github.com/d20b23c4bc92b3fa40a6203221127bbf for a full test report.

**Comment by rjeschmi** [comment]
Test report by @rjeschmi
**SUCCESS**
Build succeeded for 15 out of 15 (8 easyconfigs in this PR)
ryzen37 - Linux Ubuntu 20.04, x86_64, AMD Ryzen 7 3700X 8-Core Processor, Python 3.8.2
See https://gist.github.com/f4b3722b46a4626b09e0f29e1a3b5533 for a full test report.

**Comment by rjeschmi** [comment]
Test report by @rjeschmi
**SUCCESS**
Build succeeded for 15 out of 15 (8 easyconfigs in this PR)
ubuntu - Linux Ubuntu 20.04, x86_64, AMD Ryzen 5 1600 Six-Core Processor, Python 3.8.2
See https://gist.github.com/86364906c93610c8d49020950af330c6 for a full test report.

**Comment by Micket** [comment]
Test report by @Micket
**SUCCESS**
Build succeeded for 8 out of 8 (8 easyconfigs in this PR)
hebbe-c1 - Linux centos linux 7.7.1908, Intel Core Processor (Haswell, no TSX), Python 2.7.5
See https://gist.github.com/76aae6daa6eb5a9b601a20ac39f41b8d for a full test report.

**Comment by akesandgren** [comment]
Test report by @akesandgren
**SUCCESS**
Build succeeded for 8 out of 8 (8 easyconfigs in this PR)
b-an03.hpc2n.umu.se - Linux ubuntu 16.04, x86_64, Intel(R) Xeon(R) CPU E5-2690 v4 @ 2.60GHz, Python 2.7.12
See https://gist.github.com/3ee3c297a2e5ff8a66360318de61ea8c for a full test report.

**Comment by verdurin** [comment]
@akesandgren you mentioned that a specific patch was needed for this. Is it included now?

**Comment by akesandgren** [comment]
@verdurin Nah, it still doesn't produce infinitely fast code nor does it fix broken code :-)

**Comment by boegel** [comment]
> @akesandgren you mentioned that a specific patch was needed for this. Is it included now?

That was a joke. :)

This is good to merge imho.

**Comment by verdurin** [comment]
Test report by @verdurin
**SUCCESS**
Build succeeded for 8 out of 8 (8 easyconfigs in this PR)
easybuild.novalocal - Linux centos linux 7.8.2003, Intel Xeon Processor (Skylake, IBRS), Python 2.7.5
See https://gist.github.com/123dceaa040fccc95980ac96d58cd9d4 for a full test report.

**Comment by verdurin** [comment]
Going in, thanks @boegel!

**Pull request merged**
