### PR TITLE
Add freetype as dependency to OpenImageIO, as otherwise the build can pick up the system-wide library

### PR DESCRIPTION
**Pull request by paulmelis**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by migueldiascosta** [comment]
@paulmelis thanks for your contribution, hopefully the first of many :)

although you are only adding a dependency, the tests now require using https for files touched by PRs, please update it (you can do so with `--update-pr`)

**Comment by paulmelis** [comment]
> although you are only adding a dependency, the tests now require using https for files touched by PRs, please update it (you can do so with `--update-pr`)

I'll fix it, but find it a bit surprising:

- I based this easyconfig on the version in the official repos, none of which use https for the versions of OpenImageIO in the repo, which where updated last 11 months ago. Was the https-check added after that?
- Why not also do this check and others as part of the `--new-pr` command? Might save quite a few unnecessary work cycles for some people, including submitters.

**Comment by migueldiascosta** [comment]
@paulmelis yes, the https check was added after that

the CI tests are much more extensive tham what can be done at `--new-pr`. You are right that it could do a bit more, but it would also require more dependencies to be installed (see, for instance, https://github.com/easybuilders/easybuild-framework/pull/2987)

**Comment by migueldiascosta** [comment]
Test report by @migueldiascosta
**FAILED**
Build succeeded for 0 out of 1 (1 easyconfigs in this PR)
generoso - Linux centos linux 7.6.1810, Intel(R) Xeon(R) CPU E5-2660 v4 @ 2.00GHz, Python 3.6.8
See https://gist.github.com/d3b5f3c8893cd79b2fba0357cd31f5b2 for a full test report.

**Comment by migueldiascosta** [comment]
Test report by @migueldiascosta
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
generoso - Linux centos linux 7.6.1810, Intel(R) Xeon(R) CPU E5-2660 v4 @ 2.00GHz, Python 3.6.8
See https://gist.github.com/fb1f10351941a6f0194b46c3c3055ef7 for a full test report.

**Comment by migueldiascosta** [comment]
@paulmelis this was indeed a problem and your PR fixes it, thanks again

would you consider also fixing the other `OpenImageIO` easyconfigs?

**Comment by migueldiascosta** [comment]
Going in, thanks @paulmelis!

**Comment by boegel** [comment]
This should definitely also be fixed in `OpenImageIO-1.8.16-intel-2018b.eb` to keep things consistent...

**Comment by boegel** [comment]
Ah, that was done in #9152, my apologies. :)

**Pull request merged**
