### PR TITLE
bump JasPer version to latest 2.0.24 for 2020b generation of easyconfigs + remove easyconfigs for ancient JasPer 2.0.1.4 with GCCcore/10.2.0

### PR DESCRIPTION
**Pull request by boegel**
While working on OpenCV for `foss/2020b` (#12265), I noticed we're (probably by accident) using an ancient version of JasPer for the `2020b` generation of easyconfigs...

JasPer 2.0.14 was released Sept'17 (see https://www.ece.uvic.ca/~frodo/jasper/#download), and there are several more recent releases available through https://github.com/jasper-software/jasper/releases . In addition, we already have an easyconfig for JasPer 2.0.24 with `GCCcore/10.2.0` (see #12077), so we really should be using that instead.

The fact that only old releases are mentioned at https://www.ece.uvic.ca/~frodo/jasper/#download is probably what caused this.

Fallout is relatively limited for now, but it does involve `Qt5`, so people who already have it installed will have to rebuild it to avoid running into surprises...

### CODE REVIEW

**Comment by boegel** [comment]
@boegelbot please test @ generoso
CORE_CNT=16

**Comment by branfosj** [comment]
I did a test build, but forgot the upload. I error out with:
```
qjp2handler.cpp: In member function bool Jpeg2000JasperReader::write(const QImage&, int):
qjp2handler.cpp:855:41: error: pow was not declared in this scope
  855 |     const double jasperRate = minRate + pow((double(quality) / double(maxQuality)), 2) * maxRate;
      |                                         ^~~
make[5]: *** [.obj/qjp2handler.o] Error 1
```

Which leads me to https://github.com/qt/qtimageformats/commit/704868db61be1542c2d9e2b75ead00c45c56cc36

**Comment by boegel** [comment]
@boegelbot please test @ generoso
CORE_CNT=16

**Comment by branfosj** [comment]
Test report by @branfosj
**SUCCESS**
Build succeeded for 3 out of 3 (3 easyconfigs in total)
bear-pg0206u03a.bear.cluster - Linux centos linux 7.8.2003, x86_64, Intel(R) Xeon(R) Gold 6248 CPU @ 2.50GHz (cascadelake), Python 3.6.8
See https://gist.github.com/5c8effad3854d14a38295e0693578754 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 3 out of 3 (3 easyconfigs in total)
node2685.swalot.os - Linux centos linux 7.9.2009, x86_64, Intel(R) Xeon(R) CPU E5-2660 v3 @ 2.60GHz (haswell), Python 3.6.8
See https://gist.github.com/9e900ef4509bae8892905acf2b77bca8 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 3 out of 3 (3 easyconfigs in total)
node3521.doduo.os - Linux RHEL 8.2, x86_64, AMD EPYC 7552 48-Core Processor (zen2), Python 3.6.8
See https://gist.github.com/bcf4af5ff0abb9d4055128c797f5936a for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 3 out of 3 (3 easyconfigs in total)
node3152.skitty.os - Linux centos linux 7.9.2009, x86_64, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz, Python 3.6.8
See https://gist.github.com/5064e66af1ce2414b28a6edacc1860d8 for a full test report.

**Comment by branfosj** [comment]
Test report by @branfosj
**SUCCESS**
Build succeeded for 3 out of 3 (3 easyconfigs in total)
bear-pg0306u19a - Linux RHEL 8.2, POWER, 8335-GTX (power9le), Python 3.6.8
See https://gist.github.com/a8b23101f0f442328538fe4f44096474 for a full test report.

**Review by branfosj — APPROVED** [review]
lgtm

**Comment by branfosj** [comment]
Going in, thanks @boegel!

**Pull request merged**
