### PR TITLE
{vis}[gfbf/2024a] matplotlib-3.9.2 (plus missing dependencies)

### PR DESCRIPTION
**Pull request by ankekreuzer**
Added matplotlib to the `gfbf-2024a` toolchain.

Needs
- `libwebp` from #21288 and
- `LittleCMS` from #21295

### CODE REVIEW

**Comment by ankekreuzer** [comment]
Test report by @ankekreuzer
**SUCCESS**
Build succeeded for 6 out of 6 (6 easyconfigs in total)
zam329 - Linux Rocky Linux 9.4 (Blue Onyx), x86_64, Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz, Python 3.9.18
See https://gist.github.com/ankekreuzer/5b5d28a29d03d51468d802cb1d3c6a5c for a full test report.

**Comment by SebastianAchilles** [comment]
@boegelbot please test @ jsc-zen3

**Comment by SebastianAchilles** [comment]
Test report by @sebastianachilles
**SUCCESS**
Build succeeded for 6 out of 6 (6 easyconfigs in total)
bwd-rockylinux-94 - Linux Rocky Linux 9.4 (Blue Onyx), x86_64, Intel(R) Core(TM) i7-6900K CPU @ 3.20GHz (broadwell), Python 3.9.18
See https://gist.github.com/SebastianAchilles/13e09479321d7ca6c0dd011dc99ab40f for a full test report.

**Comment by SebastianAchilles** [comment]
Test report by @sebastianachilles
**SUCCESS**
Build succeeded for 6 out of 6 (6 easyconfigs in total)
zen2-rockylinux-810 - Linux Rocky Linux 8.10, x86_64, AMD EPYC 7452 32-Core Processor (zen2), Python 3.6.8
See https://gist.github.com/SebastianAchilles/1b5482e345d57f734e467933ba3f7a17 for a full test report.

**Comment by SebastianAchilles** [comment]
@boegelbot please test @ generoso

**Review by smoors — APPROVED** [review]
lgtm

**Comment by smoors** [comment]
Going in, thanks @ankekreuzer!

**Pull request merged**
