### PR TITLE
skip `Test::Sys::Info` test that expects `/etc/fstab` in Perl-bundle-CPAN

### LINKED ISSUE #19439: Perl `make test` failure on `foss/2023a` in a CentOS 7.9 container
In a CentOS 7.9 build container:
```
== 2023-12-18 10:08:58,985 build_log.py:171 ERROR EasyBuild crashed with an error (at easybuild/base/exceptions.py:126 in __init__): cmd "make test" exited with exit code 2 and output:
PERL_DL_NONLAZY=1 "/apps/eb/el7/2023a/skylake/software/Perl/5.36.1-GCCcore-12.3.0/bin/perl" "-MExtUtils::Command::MM" "-MTest::Harness" "-e" "undef *Test::Harness::Switches; test_harness(0, 'blib/lib', 'blib/arch')" t/*.t
t/00-compile.t ........... ok
#
# Versions for all modules listed in MYMETA.json (including optional ones):
#
# === Configure Requires ===
#
#     Module              Want Have
#     ------------------- ---- ----
#     ExtUtils::MakeMaker  any 7.70
#
# === Build Requires ===
#
#     Module              Want Have
#     ------------------- ---- ----
#     ExtUtils::MakeMaker  any 7.70
#
# === Test Requires ===
#
#     Module              Want     Have
#     ------------------- ---- --------
#     ExtUtils::MakeMaker  any     7.70
#     File::Spec           any     3.75
#     IO::Handle           any     1.51
#     IPC::Open3           any     1.22
#     Test::More           any 1.302195
#     Test::Sys::Info     0.20     0.23
#
# === Test Recommends ===
#
#     Module         Want     Have
#     ---------- -------- --------
#     CPAN::Meta 2.120900 2.150010
#
# === Runtime Requires ===
#
#     Module             Want   Have
#     ---------------- ------ ------
#     Config::General     any   2.65
#     Sys::Info::Base  0.7801 0.7807
#     Unix::Processors    any  2.046
#
t/00-report-prereqs.t .... ok
UNAME: Linux compe055.hpc.in.bmrc.ox.ac.uk 3.10.0-1160.102.1.el7.x86_64 #1 SMP Tue Oct 17 15:42:21 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux

I can not open file /etc/fstab for reading: No such file or directory at /apps/eb/el7/2023a/skylake/software/Perl-bundle-CPAN/5.36.1-GCCcore-12.3.0/lib/perl5/site_perl/5.36.1/Test/Sys/Info/Driver.pm line 91.
# Looks like your test exited with 2 just after 64.
t/03-basic.t .............
Dubious, test returned 2 (wstat 512, 0x200)
All 64 subtests passed
# $VAR1 = {
#           'name' => 'Centos Linux',
#           'version' => '7.9.2009',
#           'distro' => bless( {
#                                'release_file' => 'os-release',
#                                'DISTRIB_RELEASE' => 'centos linux 7 (core)',
#                                'RESULTS' => {
#                                               'raw_name' => 'centos',
#                                               'edition' => undef,
#                                               'version' => '7.9.2009',
#                                               'name' => 'Centos Linux'
#                                             },
#                                'DISTRIB_DESCRIPTION' => '',
#                                'PROBE' => {
#                                             'kernel' => '3.10.0-1160.102.1.el7.x86_64',
#                                             'build_date' => 1697553741,
#                                             'build' => 'Tue Oct 17 15:42:21 2023',
#                                             'version' => 'Linux version 3.10.0-1160.102.1.el7.x86_64 (mockbuild@kbuilder.bsys.centos.org) (gcc version 4.8.5 20150623 (Red Hat 4.8.5-44) (GCC) ) #1 SMP Tue Oct 17 15:42:21 UTC 2023',
#                                             'distro' => 'Linux'
#                                           },
#                                'DISTRIB_ID' => 'centos',
#                                'DISTRIB_NAME' => '',
#                                'pattern' => 'CentOS(?: Linux)? release (.*) \\(',
#                                'DISTRIB_CODENAME' => '',
#                                'etc_dir' => '/etc'
#                              }, 'Sys::Info::Driver::Linux::OS::Distribution' )
#         };
t/04-distribution.t ...... ok
t/author-pod-coverage.t .. skipped: these tests are for testing by the author
t/author-pod-syntax.t .... skipped: these tests are for testing by the author
t/release-distmeta.t ..... skipped: these tests are for release candidate testing

Test Summary Report
-------------------
t/03-basic.t           (Wstat: 512 (exited 2) Tests: 64 Failed: 0)
  Non-zero exit status: 2
Files=7, Tests=75,  0 wallclock secs ( 0.03 usr  0.01 sys +  0.48 cusr  0.16 csys =  0.68 CPU)
Result: FAIL
Failed 1/7 test programs. 0/75 subtests failed.
make: *** [test_dynamic] Error 255
 (at easybuild/tools/run.py:681 in parse_cmd_output)
 ```

### PR DESCRIPTION
**Pull request by branfosj**
(created using `eb --new-pr`)

fixes #19439 (hopefully!)

### CODE REVIEW

**Comment by branfosj** [comment]
Test report by @branfosj
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in total)
bear-pg0105u03a - Linux RHEL 8.6, x86_64, Intel(R) Xeon(R) Platinum 8360Y CPU @ 2.40GHz (icelake), Python 3.6.8
See https://gist.github.com/branfosj/2e04698687532fc8a2aebc93e29c0577 for a full test report.

**Comment by verdurin** [comment]
Test report by @verdurin
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in total)
easybuild-c7.novalocal - Linux CentOS Linux 7.9.2009, x86_64, Intel Xeon Processor (Skylake, IBRS), Python 3.6.8
See https://gist.github.com/verdurin/7ed3d8cd9524eafe1e0e4dc2f684d607 for a full test report.

**Comment by verdurin** [comment]
@boegelbot please test @ generoso

**Comment by verdurin** [comment]
@boegelbot please test @ jsc-zen2

**Review by verdurin — APPROVED** [review]
Looks fine.

**Pull request merged**
