### PR TITLE
[devel]{GCCcore-6.4.0} git v2.14.1

### PR DESCRIPTION
**Pull request by jhein32**
Configfile to build git 2.14.1 in GCCcore 6.4.0 (to be accessible from the new 2017b) toolchains

### CODE REVIEW

**Comment by jhein32** [comment]
I checked the the workaround mentioned is still needed.  The build fails is if that is commented.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
gligar03.gligar.os - Linux centos linux 7.3.1611, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.7.5
See https://gist.github.com/a379165ead422869bdab3789eaf5144b for a full test report.

**Comment by jhein32** [comment]
@boegel Can you test that this git can actually do something useful?  The user I have build that for has not yet done so.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
node2510.golett.os - Linux centos linux 7.3.1611, Intel(R) Xeon(R) CPU E5-2680 v3 @ 2.50GHz, Python 2.7.5
See https://gist.github.com/c689946edb6b49b0b044df1057d4c295 for a full test report.

**Comment by boegel** [comment]
@jhein32 Quick check (`git clone`, `git status`, `git log`, ...) shows that it works fine.

Next time, please test yourself...

**Comment by jhein32** [comment]
I am not using git so much on the machine I used to build this and had no repository at hand.  Would have taken me way more than the 2 mins it took you ;)

I hope it is ok.

Joachim



On 22 Sep 2017, at 16:20, Kenneth Hoste <notifications@github.com<mailto:notifications@github.com>> wrote:


@jhein32<https://github.com/jhein32> Quick check (git clone, git status, git log, ...) shows that it works fine.

Next time, please test yourself...

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
node2510.golett.os - Linux centos linux 7.3.1611, Intel(R) Xeon(R) CPU E5-2680 v3 @ 2.50GHz, Python 2.7.5
See https://gist.github.com/5dc3ee5fce3fcf2d2152b0f4493974e6 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
gligar03.gligar.os - Linux centos linux 7.3.1611, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.7.5
See https://gist.github.com/96d07cbe6370972a3fca80c826b563f3 for a full test report.

**Comment by boegel** [comment]
@jhein32 Small style issue that needs to be fixed:

```
$ eb --check-style --from-pr 5161
== temporary log file in case of crash /tmp/eb-LMQVUa/easybuild-A0azMN.log

*** WARNING: Using easyconfigs from unstable (pending/failed tests or merge conflict) PR #5161 ***

Running style check on 1 easyconfig(s)...
/tmp/eb-LMQVUa/files_pr5161/g/git/git-2.14.1-GCCcore-6.4.0.eb:16:20: E222 multiple spaces after operator
[FAIL] /tmp/eb-LMQVUa/files_pr5161/g/git/git-2.14.1-GCCcore-6.4.0.eb
ERROR: One or more style checks FAILED!
```

**Comment by jhein32** [comment]
Done.

Best wishes
   Joachim

On 22 Sep 2017, at 17:19, Kenneth Hoste <notifications@github.com<mailto:notifications@github.com>> wrote:


@jhein32<https://github.com/jhein32> Small style issue that needs to be fixed:

$ eb --check-style --from-pr 5161
== temporary log file in case of crash /tmp/eb-LMQVUa/easybuild-A0azMN.log

*** WARNING: Using easyconfigs from unstable (pending/failed tests or merge conflict) PR #5161 ***

Running style check on 1 easyconfig(s)...
/tmp/eb-LMQVUa/files_pr5161/g/git/git-2.14.1-GCCcore-6.4.0.eb:16:20: E222 multiple spaces after operator
[FAIL] /tmp/eb-LMQVUa/files_pr5161/g/git/git-2.14.1-GCCcore-6.4.0.eb
ERROR: One or more style checks FAILED!

**Comment by boegel** [comment]
Going in, thanks @jhein32!

**Pull request merged**
