### PR TITLE
{cae,numlib,phys}[intel/2017b] GATE v8.0, Geant4 v10.04, CLHEP v2.4.0.0

### PR DESCRIPTION
**Pull request by boegel**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 3 out of 3 (3 easyconfigs in this PR)
node2603.swalot.os - Linux centos linux 7.4.1708, Intel(R) Xeon(R) CPU E5-2660 v3 @ 2.60GHz, Python 2.7.5
See https://gist.github.com/2aaba769d3705fdca40d9a6b0bb0a336 for a full test report.

**Comment by verdurin** [comment]
Test report by @verdurin
**FAILED**
Build succeeded for 7 out of 9 (3 easyconfigs in this PR)
rescomp2 - Linux centos 6.8, Intel(R) Xeon(R) CPU E5-2650 v2 @ 2.60GHz, Python 2.7.11
See https://gist.github.com/627de6f279d3cfe4f6785092d1d19f4d for a full test report.

**Comment by boegel** [comment]
```
../../lib/libAfterImage.a(export.o): In function `ASImage2png_int':
export.c:(.text+0x1bc4): undefined reference to `png_set_longjmp_fn'
../../lib/libAfterImage.a(import.o): In function `png2ASImage_int':
import.c:(.text+0x2879): undefined reference to `png_set_longjmp_fn'
make[2]: *** [lib/libASImage.so] Error 1
make[2]: Leaving directory `/dev/shm/ROOT/6.10.08/intel-2017b-Python-2.7.14/easybuild_obj'
make[1]: *** [graf2d/asimage/CMakeFiles/ASImage.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
```

This may be due to a missed `libpng` dependency in the `ROOT` easyconfig?

**Comment by boegel** [comment]
@verdurin Please check if #5595 fixes your issue?

**Comment by verdurin** [comment]
Test report by @verdurin
**SUCCESS**
Build succeeded for 1 out of 1 (3 easyconfigs in this PR)
rescomp2 - Linux centos 6.8, Intel(R) Xeon(R) CPU E5-2650 v2 @ 2.60GHz, Python 2.7.11
See https://gist.github.com/391311ade02740b5bf9b5ceb07ca3020 for a full test report.

**Comment by boegel** [comment]
@verdurin \o/

**Comment by verdurin** [comment]
Going in, thanks @boegel!

**Pull request merged**
