### PR TITLE
{bio,devel}[foss/2018b] Sailfish v0.10.1, g2log v1.0

### PR DESCRIPTION
**Pull request by SethosII**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by vanzod** [comment]
@SethosII Since `g2log` has no dependencies other than `CMake` and its performance is not critical, how about demoting it from `foss` to the `GCCcore` toolchain?

**Comment by SethosII** [comment]
@vanzod I moved `g2log` to `GCCcore.`

**Comment by vanzod** [comment]
@SethosII It looks like `Sailfish` requires additional dependencies like `libgff`, `jemalloc` and maybe others. In the current state it will attempt to download and build itself. Can you see if there is a way to provide them as dependencies?

**Comment by boegel** [comment]
Test report by @boegel
**FAILED**
Build succeeded for 0 out of 2 (2 easyconfigs in total)
node2689.swalot.os - Linux centos linux 7.8.2003, x86_64, Intel(R) Xeon(R) CPU E5-2660 v3 @ 2.60GHz (haswell), Python 2.7.5
See https://gist.github.com/70a14e72051c84bf0309693f1dbf3a4c for a full test report.

**Comment by verdurin** [comment]
@SethosII thanks for submitting this. We can't merge it at the moment owing to problems with `g2log`, in turn caused by the end of Bitbucket.

`Sailfish` is available in newer toolchains e.g. `gompi-2019b`, which is hopefully still useful.

In the interests of reducing the backlog of pull requests, I'm going to close this one.

We will look at fixing `g2log` now that there is a mirror on GitHub.

Thanks again for the contribution.

**Pull request closed without merging**
