### PR TITLE
{bio}[GCC/11.2.0] PRANK v170427

### PR DESCRIPTION
**Pull request by zemu-unile**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by jfgrimm** [comment]
Test report by @jfgrimm
**FAILED**
Build succeeded for 0 out of 1 (1 easyconfigs in total)
node024.pri.viking.alces.network - Linux UNKNOWN UNKNOWN, x86_64, Intel(R) Xeon(R) Gold 6138 CPU @ 2.00GHz (skylake_avx512), Python 3.6.8
See https://gist.github.com/53358a0de2910e0fb346532628b03f1d for a full test report.

**Comment by jfgrimm** [comment]
Test report by @jfgrimm
**SUCCESS**
Build succeeded for 2 out of 2 (1 easyconfigs in total)
node024.pri.viking.alces.network - Linux UNKNOWN UNKNOWN, x86_64, Intel(R) Xeon(R) Gold 6138 CPU @ 2.00GHz (skylake_avx512), Python 3.6.8
See https://gist.github.com/b7acf1678be1002e3f7dc792eb737568 for a full test report.

**Comment by jfgrimm** [comment]
@boegelbot: please test @ generoso

**Comment by zemu-unile** [comment]
Lazy bot ;-)

**Comment by SebastianAchilles** [comment]
@boegelbot: please test @ generoso

**Comment by jfgrimm** [comment]
@boegelbot: please test @ jsc-zen2

**Review by jfgrimm — APPROVED** [review]
LGTM

**Comment by jfgrimm** [comment]
Going in, thanks @zemu-unile!

**Pull request merged**
