### PR TITLE
$GI_TYPELIB_PATH must be set for GTK+

### PR DESCRIPTION
**Pull request by akesandgren**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by akesandgren** [comment]
Test report by @akesandgren
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
b-an03.hpc2n.umu.se - Linux ubuntu 16.04, Intel(R) Xeon(R) CPU E5-2690 v4 @ 2.60GHz, Python 2.7.12
See https://gist.github.com/b45d86a1c662552cc1112fc21aa05586 for a full test report.

**Comment by migueldiascosta** [comment]
@akesandgren should the other `GTK+3` easyconfig also be changed?

**Comment by akesandgren** [comment]
Probably, I just forgot to do it.

**Comment by akesandgren** [comment]
Done on the same ones as i did in #8089

**Comment by migueldiascosta** [comment]
Test report by @migueldiascosta
**SUCCESS**
Build succeeded for 13 out of 13 (13 easyconfigs in this PR)
grc-cluster1 - Linux centos 6.10, Intel(R) Xeon(R) CPU E5-2640 0 @ 2.50GHz, Python 2.7.14
See https://gist.github.com/1f9013910ae157616d3142ee8420492a for a full test report.

**Comment by migueldiascosta** [comment]
Going in, thanks @akesandgren!

**Pull request merged**
