### PR TITLE
{tools}[GCCcore/11.3.0] cysignals v1.11.2, ppl v1.2, pplpy v0.8.9

### PR DESCRIPTION
**Pull request by migueldiascosta**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by migueldiascosta** [comment]
@boegelbot please test @ generoso

**Comment by migueldiascosta** [comment]
@boegelbot please test @ jsc-zen2

**Comment by migueldiascosta** [comment]
@boegelbot please test @ jsc-zen2

**Comment by migueldiascosta** [comment]
@boegelbot please test @ jsc-zen2

**Comment by migueldiascosta** [comment]
@boegelbot please test @ generoso

**Comment by verdurin** [comment]
Test report by @verdurin
**SUCCESS**
Build succeeded for 4 out of 4 (3 easyconfigs in total)
easybuild-c7.novalocal - Linux CentOS Linux 7.9.2009, x86_64, Intel Xeon Processor (Skylake, IBRS), Python 3.6.8
See https://gist.github.com/verdurin/95f7aa74617b1df10a0626b6aa0e428b for a full test report.

**Review by verdurin — APPROVED** [review]
Looks fine.

**Comment by verdurin** [comment]
Going in, thanks @migueldiascosta!

**Pull request merged**
