### PR TITLE
{math}[system/system] MATLAB v2021b

### PR DESCRIPTION
**Pull request by Micket**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by Micket** [comment]
Test report by @Micket
**FAILED**
Build succeeded for 0 out of 1 (1 easyconfigs in total)
alvis-c1 - Linux centos linux 7.9.2009, x86_64, Intel Xeon Processor (Skylake), Python 3.6.8
See https://gist.github.com/3f9c867fe60459656a982bedd830f121 for a full test report.

**Review by lexming — APPROVED** [review]
I cannot send a test report for this due to its `osdependencies`, but we already have this MATLAB version installed and I can confirm the checksum and that this easyconfig works.

LGTM

**Comment by Micket** [comment]
my build failed because I hadn't updated the key yet. I'll upload a proper test later.

**Comment by Micket** [comment]
Test report by @Micket
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
alvis-c1 - Linux centos linux 7.9.2009, x86_64, Intel Xeon Processor (Skylake), Python 3.6.8
See https://gist.github.com/4690fc42cf8c319ba2a8f6340e0a0276 for a full test report.

**Comment by lexming** [comment]
Going in, thanks @Micket !

**Pull request merged**
