### PR TITLE
{bio}[GCCcore/11.3.0,foss/2022a] Roary v3.13.0, Kraken v1.1.1

### PR DESCRIPTION
**Pull request by lexming**
(created using `eb --new-pr`)

Depends on:
* [x] #17268

### CODE REVIEW

**Comment by lexming** [comment]
@boegelbot: please test @ generoso

**Comment by lexming** [comment]
@boegelbot please test @ jsc-zen2

**Review by bedroge — APPROVED** [review]
lgtm

**Comment by bedroge** [comment]
Going in, thanks @lexming!

**Pull request merged**
