### PR TITLE
also define $AUGUSTUS_BIN_PATH and $AUGUSTUS_SCRIPTS_PATH in generated module file for AUGUSTUS

### PR DESCRIPTION
**Pull request by boegel**

### CODE REVIEW

**Comment by boegel** [comment]
Same issue again as in #9396, tests in Travis fail to complete... :-/

**Comment by boegel** [comment]
Hmm, maybe that's because `https://bioinf.uni-greifswald.de/augustus/binaries/` hangs, so the `https` check which tries to use the `https://` URL rather than `http://` gets stuck...

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 7 out of 7 (7 easyconfigs in this PR)
node2405.golett.os - Linux centos linux 7.7.1908, Intel(R) Xeon(R) CPU E5-2680 v3 @ 2.50GHz, Python 2.7.5
See https://gist.github.com/80681e3d8377e1c131e60e1c7c0640f1 for a full test report.

**Comment by migueldiascosta** [comment]
Going in, thanks @boegel!

**Pull request merged**
