### PR TITLE
{bio}[foss/2021b] GUSH v2020-09-28

### PR DESCRIPTION
**Pull request by deniskristak**

### CODE REVIEW

**Comment by smoors** [comment]
@boegelbot: please test @ generoso

**Comment by smoors** [comment]
@boegelbot please test @ jsc-zen2

**Comment by smoors** [comment]
@deniskristak the sanity_check_commands downloads stuff with wget.
is there another command that we can use instead that doesn't download?

>     ./gushr.py -t example/augustus.gtf -b example/RNAseq.bam -g example/genome.fa -o utrs exited with code 1 (output: ./download_rnaseq.sh: line 1: wget: command not found

**Comment by boegel** [comment]
> @deniskristak the sanity_check_commands downloads stuff with wget. is there another command that we can use instead that doesn't download?
> 
> > ```
> > ./gushr.py -t example/augustus.gtf -b example/RNAseq.bam -g example/genome.fa -o utrs exited with code 1 (output: ./download_rnaseq.sh: line 1: wget: command not found
> > ```

One option here could be to pre-download whatever is being pulled in via `sources`, and then seeding that into the right place when running the sanity check command...

**Comment by smoors** [comment]
@boegelbot please test @ jsc-zen2

**Review by smoors — APPROVED** [review]
lgtm

**Comment by smoors** [comment]
Going in, thanks @deniskristak!

**Pull request merged**
