### PR TITLE
{math}[GCCcore/10.2.0] Eigen v3.4.0

### PR DESCRIPTION
**Pull request by smoors**
(created using `eb --new-pr`)
depends on easyblock
* [ ] https://github.com/easybuilders/easybuild-easyblocks/pull/2633

### CODE REVIEW

**Comment by smoors** [comment]
@boegelbot: please test @ generoso EB_ARGS="--include-easyblocks-from-pr=2633"

**Comment by smoors** [comment]
Test report by @smoors
Using easyblocks from PR(s) https://github.com/easybuilders/easybuild-easyblocks/pull/2633
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
node300.hydra.os - Linux centos linux 7.9.2009, x86_64, Intel(R) Xeon(R) Gold 6148 CPU @ 2.40GHz (skylake_avx512), Python 2.7.5
See https://gist.github.com/b133ed4e4bc08f4c826c340c09876d97 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
Using easyblocks from PR(s) https://github.com/easybuilders/easybuild-easyblocks/pull/2633
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
node3105.skitty.os - Linux centos linux 7.9.2009, x86_64, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz (skylake_avx512), Python 3.6.8
See https://gist.github.com/a00f26e19edd7fb154ce0d934f3c55d6 for a full test report.

**Comment by boegel** [comment]
@boegelbot please test @ generoso
EB_ARGS="--include-easyblocks-from-pr=2633 Eigen-3.4.0-GCCcore-10.2.0.eb Eigen-3.3.4.eb Eigen-3.3.5.eb Eigen-3.3.7-GCCcore-9.3.0.eb Eigen-3.3.7.eb Eigen-3.3.8-GCCcore-10.2.0.eb Eigen-3.3.9-GCCcore-10.2.0.eb Eigen-3.3.9-GCCcore-10.3.0.eb Eigen-3.3.9-GCCcore-11.2.0.eb"

**Review by boegel — APPROVED** [review]
lgtm

**Comment by boegel** [comment]
Going in, thanks @smoors!

**Pull request merged**
