### PR TITLE
Fix miscomputation in OpenBLAS on POWER

### PR DESCRIPTION
**Pull request by Flamefire**
(created using `eb --new-pr`)

See https://github.com/xianyi/OpenBLAS/issues/2923#issuecomment-1238125378

### CODE REVIEW

**Comment by Flamefire** [comment]
Test report by @Flamefire
**SUCCESS**
Build succeeded for 4 out of 4 (4 easyconfigs in total)
taurusml25 - Linux RHEL 7.6, POWER, 8335-GTX (power9le), 6 x NVIDIA Tesla V100-SXM2-32GB, 440.64.00, Python 2.7.5
See https://gist.github.com/3e0e61935afee1f938a1c520ff5a4109 for a full test report.

**Comment by Flamefire** [comment]
Tested with an installed `PyTorch/1.6.0-fosscuda-2019b-Python-3.7.4` via:

- `eb PyTorch-1.6.0-fosscuda-2019b-Python-3.7.4.eb --rebuild --installpath=/tmp --stop=patch`
- `ml PyTorch/1.6.0-fosscuda-2019b-Python-3.7.4`
- `cd /dev/shm/s3248973-EasyBuild/PyTorch/1.6.0/fosscuda-2019b-Python-3.7.4/pytorch-1.6.0/test`
- `for i in OpenBLAS/0.3.7-GCC-8.3.0 OpenBLAS/0.3.8-GCC-9.2.0 OpenBLAS/0.3.9-GCC-9.3.0 OpenBLAS/0.3.12-GCC-10.2.0; do echo $i; ml $i && python test_nn.py TestNNDeviceTypeCPU.test_conv_large_cpu; done`

Prior to this PR it failed, after the PR it succeeded.

**Comment by Flamefire** [comment]
Note that the patch differs slightly from upstream as I needed to backport it:

Until 0.3.11 there was no #ifdef branch for POWER10 (introduced with https://github.com/xianyi/OpenBLAS/pull/2686) so up until 0.3.10 the only required patch is for POWER9, i.e. https://github.com/xianyi/OpenBLAS/blob/v0.3.10/param.h#L2263

For 0.3.12 POWER9 and POWER10 used the same values, so there is also only 1 change required: https://github.com/xianyi/OpenBLAS/blob/v0.3.12/param.h#L2391

In 0.3.14 and above the issue is fixed upstream by the linked PR.

**Review by akesandgren — APPROVED** [review]
LGTM

**Comment by akesandgren** [comment]
Going in, thanks @Flamefire!

**Comment by boegel** [comment]
@boegelbot please test @ generoso

**Pull request merged**
