### PR TITLE
{bio}[system/system] snpEff v4.3t

### PR DESCRIPTION
**Pull request by SethosII**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by SethosII** [comment]
Test report by @SethosII
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
ribnode015 - Linux ubuntu 18.04, Intel(R) Xeon(R) CPU           E5645  @ 2.40GHz, Python 2.7.17
See https://gist.github.com/214ca0d2867e86f8eb9f97dc626af244 for a full test report.

**Comment by Micket** [comment]
Test report by @Micket
**FAILED**
Build succeeded for 0 out of 1 (1 easyconfigs in this PR)
vera-c1 - Linux centos linux 7.8.2003, x86_64, Intel Xeon Processor (Skylake), Python 2.7.5
See https://gist.github.com/fe9bb8e83adaa091785cb46d52d13b51 for a full test report.

**Comment by Micket** [comment]
Test report by @Micket
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
vera-c1 - Linux centos linux 7.8.2003, x86_64, Intel Xeon Processor (Skylake), Python 2.7.5
See https://gist.github.com/e4a212305908c868348a6e05ced1e800 for a full test report.

**Comment by Micket** [comment]
Going in, thanks @SethosII!

**Pull request merged**
