### PR TITLE
fix configure step for ELSI 2.5.0+ (and add missing foss versions)

### LINKED ISSUE #17259: ELSI fails to build with latest EasyBuild releases
While trying to install ELSI-2.7.1-foss-2021a-PEXSI.eb I get the following error:

```
CMake Error at CMakeLists.txt:59 (MESSAGE):
  ESC[35mFortran compiler must be setESC[m


-- Configuring incomplete, errors occurred!
```

Indeed the ELSI CMakeLists.txt has the following code:
```
IF(NOT DEFINED CMAKE_Fortran_COMPILER)
  MESSAGE(FATAL_ERROR "${MAGENTA}Fortran compiler must be set${COLORRESET}")
ENDIF()
ENABLE_LANGUAGE(Fortran
```

and it seems that `CMAKE_Fortran_COMPILER` is not set anymore since these changes were introduced: https://github.com/easybuilders/easybuild-easyblocks/pull/2514

Now what's the best way to fix this?

### PR DESCRIPTION
**Pull request by Flamefire**
(created using `eb --new-pr`)

fixes #17259

### CODE REVIEW

**Comment by Flamefire** [comment]
Test report by @Flamefire
**SUCCESS**
Build succeeded for 4 out of 4 (4 easyconfigs in total)
taurusi6607.taurus.hrsk.tu-dresden.de - Linux RHEL 7.9, x86_64, Intel(R) Xeon(R) CPU E5-2680 v3 @ 2.50GHz (haswell), Python 2.7.5
See https://gist.github.com/c6408759d6854d0bd84c3ea38d5e0707 for a full test report.

**Comment by boegel** [comment]
@boegelbot please test @ generoso

**Comment by Flamefire** [comment]
@boegel I see the same (or similar, not sure) errors during the tests so I disabled testing for my reports as the build is what was broken and manual investigation shows the correct compilers were used as far as I could tell.

**Review by Micket — APPROVED** [review]
Going through everything marked for 4.7.2

Two of the 2019b failures comes from missing MUMPS module, which, i'm really not sure what happened. Something must be broken in the module tree on generoso, or someone was rebuilding those ancient MUMPS packages at the same time, which seems unlikely. The last failure is the PEXSI variant which had a lot of segfaults. 

2019b is to old for my own test tree, and I really don't think we want to hold back on the fixes for the more recent easyconfigs as a result of those old broken ones, which almost certainly were broken before this PR as far as i can tell.
I'm willing to accept this PR as is.

**Comment by Micket** [comment]
Test report by @Micket
**SUCCESS**
Build succeeded for 6 out of 6 (2 easyconfigs in total)
vera-c1 - Linux Rocky Linux 8.6, x86_64, Intel Xeon Processor (Skylake), Python 3.6.8
See https://gist.github.com/Micket/b3087679e1877f0a5b0a2387003aa4a1 for a full test report.

**Comment by Micket** [comment]
Going in, thanks @Flamefire!

**Pull request merged**
