### PR TITLE
{chem}[gompi/2021a] ORCA v5.0.2

### PR DESCRIPTION
**Pull request by zao**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by zao** [comment]
@lexming The `-static` build here of 5.0.2 doesn't install properly due to the tar archives have subdirectories for each part that need to be stripped away somewhere.
```
== 2021-12-09 09:41:40,331 makecp.py:106 WARNING No files matching 'auto*' found in start dir /import/easybuild/amd64_ubuntu2004_zn2/tmp/eb-build/ORCA/5.0.2/gompi-2021a-static/orca_5_0_2_linux_x86-64_openmpi411_part1/
```

Should this be fixed in the easyblock or the easyconfig somehow?

```
$ tar tf orca_5_0_1_linux_x86-64_openmpi411_part1.tar.xz | head -n2
autoci_fic_mrcc
autoci_ficmrci_ddci4_density
$ tar tf orca_5_0_2_linux_x86-64_openmpi411_part1.tar.xz | head -n2
orca_5_0_2_linux_x86-64_openmpi411_part1/
orca_5_0_2_linux_x86-64_openmpi411_part1/orca_anoint
$ tar tf orca_5_0_1_linux_x86-64_shared_openmpi411.tar.xz | head -n2
orca_5_0_1_linux_x86-64_shared_openmpi411/
orca_5_0_1_linux_x86-64_shared_openmpi411/autoci_rohf_denom_BO
$ tar tf orca_5_0_2_linux_x86-64_shared_openmpi411.tar.xz | head -n2
orca_5_0_2_linux_x86-64_shared_openmpi411/
orca_5_0_2_linux_x86-64_shared_openmpi411/autoci_rohf_denom_BO
```

**Comment by zao** [comment]
Test report by @zao
**FAILED**
Build succeeded for 0 out of 1 (1 easyconfigs in total)
eb-u2004 - Linux Ubuntu 20.04, x86_64, AMD Ryzen 9 3900X 12-Core Processor (zen2), Python 3.8.10
See https://gist.github.com/ed759ae905dbf5ead1590172ae9b0e6f for a full test report.

**Comment by zao** [comment]
Test report by @zao
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
eb-u2004 - Linux Ubuntu 20.04, x86_64, AMD Ryzen 9 3900X 12-Core Processor (zen2), Python 3.8.10
See https://gist.github.com/0fcae2be371f024e4694726776dd5a97 for a full test report.

**Comment by dithwick** [comment]
> @lexming The `-static` build here of 5.0.2 doesn't install properly due to the tar archives have subdirectories for each part that need to be stripped away somewhere.
> 
> ```
> == 2021-12-09 09:41:40,331 makecp.py:106 WARNING No files matching 'auto*' found in start dir /import/easybuild/amd64_ubuntu2004_zn2/tmp/eb-build/ORCA/5.0.2/gompi-2021a-static/orca_5_0_2_linux_x86-64_openmpi411_part1/
> ```
> 
> Should this be fixed in the easyblock or the easyconfig somehow?
> 
> ```
> $ tar tf orca_5_0_1_linux_x86-64_openmpi411_part1.tar.xz | head -n2
> autoci_fic_mrcc
> autoci_ficmrci_ddci4_density
> $ tar tf orca_5_0_2_linux_x86-64_openmpi411_part1.tar.xz | head -n2
> orca_5_0_2_linux_x86-64_openmpi411_part1/
> orca_5_0_2_linux_x86-64_openmpi411_part1/orca_anoint
> $ tar tf orca_5_0_1_linux_x86-64_shared_openmpi411.tar.xz | head -n2
> orca_5_0_1_linux_x86-64_shared_openmpi411/
> orca_5_0_1_linux_x86-64_shared_openmpi411/autoci_rohf_denom_BO
> $ tar tf orca_5_0_2_linux_x86-64_shared_openmpi411.tar.xz | head -n2
> orca_5_0_2_linux_x86-64_shared_openmpi411/
> orca_5_0_2_linux_x86-64_shared_openmpi411/autoci_rohf_denom_BO
> ```

I borrowed your static easyconfig and added:

`unpack_options = '--strip-components=1'
`

to it and it seemed to work for me.

**Comment by zao** [comment]
Test report by @zao
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in total)
eb-u2004 - Linux Ubuntu 20.04, x86_64, AMD Ryzen 9 3900X 12-Core Processor (zen2), Python 3.8.10
See https://gist.github.com/4604e5961407fc5753527c5d96c4b1cf for a full test report.

**Comment by branfosj** [comment]
Test report by @branfosj
**FAILED**
Build succeeded for 1 out of 2 (2 easyconfigs in total)
bear-pg0211u08b.bear.cluster - Linux RHEL 8.3, x86_64, Intel(R) Xeon(R) Gold 6248 CPU @ 2.50GHz (cascadelake), Python 3.6.8
See https://gist.github.com/656aba77c00d451513ff436a14172752 for a full test report.

**Comment by branfosj** [comment]
Test report by @branfosj
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in total)
bear-pg0211u08b.bear.cluster - Linux RHEL 8.3, x86_64, Intel(R) Xeon(R) Gold 6248 CPU @ 2.50GHz (cascadelake), Python 3.6.8
See https://gist.github.com/fce85a0a44bfbfb2f0aa1dccfee3a87b for a full test report.

**Comment by lexming** [comment]
Test report by @lexming
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in total)
node303.hydra.os - Linux centos linux 7.9.2009, x86_64, Intel(R) Xeon(R) Gold 6148 CPU @ 2.40GHz, Python 2.7.5
See https://gist.github.com/1641711f6110d288af7ba04152cccad2 for a full test report.

**Review by lexming — APPROVED** [review]
The extra subdirectory is probably an oversight in the packaging of this version. Fixing the extraction in the easyconfig instead of updating the easyblock seems the good solution to me.

LGTM

**Comment by lexming** [comment]
Going in, thanks @zao and @dithwick !

**Pull request merged**
