### PR TITLE
{lib}[GCCcore/13.3.0] psycopg v3.2.3

### PR DESCRIPTION
**Pull request by lcniel**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by lcniel** [comment]
Test report by @lcniel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
vera35-1 - Linux Rocky Linux 8.9, x86_64, Intel(R) Xeon(R) Gold 6130 CPU @ 2.10GHz, Python 3.6.8
See https://gist.github.com/lcniel/0be5b3ed555d6a16cdd65c934c0fbcad for a full test report.

**Comment by SebastianAchilles** [comment]
@boegelbot please test @ jsc-zen3

**Comment by SebastianAchilles** [comment]
@boegelbot please test @ generoso

**Review by SebastianAchilles — APPROVED** [review]
lgtm

**Comment by SebastianAchilles** [comment]
Going in, thanks @lcniel!

**Pull request merged**
