### PR TITLE
enhance ESM-2 for esmfold

### PR DESCRIPTION
**Pull request by smoors**
(created using `eb --new-pr`)

### CODE REVIEW

**Review by lexming — CHANGES_REQUESTED** [review]
Please also update the non-CUDA easyconfig of ESM

**Review by lexming — CHANGES_REQUESTED** [review]
Java is a dependency of omegaconf:
```
Building wheels for collected packages: omegaconf
  Created temporary directory: /tmp/eb-d425a19m/pip-wheel-sk_x6obf
  Destination directory: /tmp/eb-d425a19m/pip-wheel-sk_x6obf
  Building wheel for omegaconf (PEP 517): started
  Running command /project/boegelbot/Rocky8/haswell/software/Python/3.9.5-GCCcore-10.3.0/bin/python /project/boegelbot/Rocky8/haswell/software/Python/3.9.5-GCCcore-10.3.0/lib/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py build_wheel /tmp/eb-d425a19m/tmpugz0xg9_
  running bdist_wheel
  running build
  running build_py
  running clean
  Generating parsers with antlr4
  running antlr
  Generating parser for Python3: ['java', '-jar', '/tmp/eb-d425a19m/pip-req-build-7f0_qqfe/build_helpers/bin/antlr-4.9.3-complete.jar', '-Dlanguage=Python3', '-o', '/tmp/eb-d425a19m/pip-req-build-7f0_qqfe/omegaconf/grammar/gen', '-Xexact-output-dir', '-visitor', '/tmp/eb-d425a19m/pip-req-build-7f0_qqfe/omegaconf/grammar/OmegaConfGrammarLexer.g4']
  ===========================================================================
  | Unable to generate parsers: [Errno 2] No such file or directory: 'java' |
  ===========================================================================
  Building wheel for omegaconf (PEP 517): finished with status 'error'
  ERROR: Failed building wheel for omegaconf
```

**Comment by smoors** [comment]
@boegelbot: please test @ generoso

**Review by lexming — APPROVED** [review]
LGTM

**Comment by lexming** [comment]
Going in, thanks @smoors !

**Pull request merged**
