### PR TITLE
{vis}[GCCcore/8.3.0] ATK v2.34.1, at-spi2-core v2.34.0, at-spi2-atk v2.34.1

### PR DESCRIPTION
**Pull request by lexming**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by lexming** [comment]
Test report by @lexming
**SUCCESS**
Build succeeded for 3 out of 3 (3 easyconfigs in this PR)
login2.cerberus.os - Linux centos linux 7.7.1908, Intel(R) Xeon(R) Gold 6126 CPU @ 2.60GHz, Python 2.7.5
See https://gist.github.com/806aa0b0639c3d57ec002156d29c0851 for a full test report.

**Comment by bartoldeman** [comment]
Test report by @bartoldeman
**FAILED**
Build succeeded for 6 out of 9 (3 easyconfigs in this PR)
lg-1r17-n02 - Linux centos 6.6, Intel(R) Xeon(R) CPU E5-2650 0 @ 2.00GHz, Python 2.6.6
See https://gist.github.com/465ff15690bfc62f55170ef843ea73da for a full test report.

**Comment by lexming** [comment]
@bartoldeman Your system seems to be missing `DBus/1.13.12-GCCcore-8.3.0` from #9009

**Comment by bartoldeman** [comment]
@lexming no it fails to build (segfault in xmlto). This is a CentOS 6 system so a bit of an edge case but good for finding weird corner cases.

**Comment by bartoldeman** [comment]
Test report by @bartoldeman
**FAILED**
Build succeeded for 0 out of 3 (3 easyconfigs in this PR)
lg-1r17-n02 - Linux centos 6.6, Intel(R) Xeon(R) CPU E5-2650 0 @ 2.00GHz, Python 2.6.6
See https://gist.github.com/42541315ea356f8e2dee89a86b1b2711 for a full test report.

**Comment by bartoldeman** [comment]
Test report by @bartoldeman
**FAILED**
Build succeeded for 0 out of 3 (3 easyconfigs in this PR)
lg-1r17-n02 - Linux centos 6.6, Intel(R) Xeon(R) CPU E5-2650 0 @ 2.00GHz, Python 2.6.6
See https://gist.github.com/cb1c5586f9146c82e0c39f7755e72b07 for a full test report.

**Comment by bartoldeman** [comment]
Test report by @bartoldeman
**SUCCESS**
Build succeeded for 3 out of 3 (3 easyconfigs in this PR)
lg-1r17-n02 - Linux centos 6.6, Intel(R) Xeon(R) CPU E5-2650 0 @ 2.00GHz, Python 2.6.6
See https://gist.github.com/7edaa4dbfca0f8a3347529a12689448a for a full test report.

**Comment by bartoldeman** [comment]
Going in, thanks @lexming!

**Comment by bartoldeman** [comment]
@lexming I rebuilt DBus without docs locally and since this review is not about DBus I left it at that.

**Comment by lexming** [comment]
@bartoldeman thanks for the feedback, I was curious about how you fixed it

**Pull request merged**
