### PR TITLE
{cae,vis}[GCCcore/8.3.0,foss/2019b] occt v7.3.0p4, FreeImage v3.18.0

### PR DESCRIPTION
**Pull request by furstj**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by verdurin** [comment]
Test report by @verdurin
**FAILED**
Build succeeded for 0 out of 1 (2 easyconfigs in this PR)
generoso - Linux centos linux 7.6.1810, Intel(R) Xeon(R) CPU E5-2660 v4 @ 2.00GHz, Python 3.6.8
See https://gist.github.com/21e19ab0dfe5a85336a6753d5021ccbd for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**FAILED**
Build succeeded for 1 out of 2 (2 easyconfigs in this PR)
generoso - Linux centos linux 7.6.1810, Intel(R) Xeon(R) CPU E5-2660 v4 @ 2.00GHz, Python 3.6.8
See https://gist.github.com/874b02961d323f4b7c3f00f014065347 for a full test report.

**Comment by boegel** [comment]
@furstj Actual compilation error indicates a missing dep (`Mesa`?)

```
In file included from /tmp/kehoste/easybuild/build/occt/7.3.0p4/foss-2019b/easybuild_obj/include/opencascade/InterfaceGraphic.hxx:1,
                 from /tmp/kehoste/easybuild/build/occt/7.3.0p4/foss-2019b/opencascade-7.3.0p4/src/Aspect/Aspect_DisplayConnection.hxx:24,
                 from /tmp/kehoste/easybuild/build/occt/7.3.0p4/foss-2019b/easybuild_obj/include/opencascade/Aspect_DisplayConnection.hxx:1,
                 from /tmp/kehoste/easybuild/build/occt/7.3.0p4/foss-2019b/opencascade-7.3.0p4/src/Aspect/Aspect_DisplayConnection.cxx:14:
                 /tmp/kehoste/easybuild/build/occt/7.3.0p4/foss-2019b/opencascade-7.3.0p4/src/InterfaceGraphic/InterfaceGraphic.hxx:41:10:
fatal error: GL/glx.h: No such file or directory
#include <GL/glx.h>                                                                                                                                                                                                  
^~~~~~~~~~                                                                                                                                                                                        
compilation terminated.
make[2]: *** [src/TKService/CMakeFiles/TKService.dir/__/Aspect/Aspect_DisplayConnection.cxx.o] 
Error 1
```

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in this PR)
generoso-1 - Linux centos linux 7.6.1810, Intel(R) Xeon(R) CPU E5-2660 v4 @ 2.00GHz, Python 3.6.8
See https://gist.github.com/a04ee3092c5d07f3e4ceedb9500e0f05 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in this PR)
node2548.golett.os - Linux centos linux 7.7.1908, Intel(R) Xeon(R) CPU E5-2680 v3 @ 2.50GHz, Python 2.7.5
See https://gist.github.com/89ae3d88267a507b3bd15796fb585577 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in this PR)
node3101.skitty.os - Linux centos linux 7.7.1908, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz, Python 3.6.8
See https://gist.github.com/7e45cc44d7241f91e551d6d45f4b927e for a full test report.

**Comment by boegel** [comment]
Going in, thanks @furstj!

**Pull request merged**
