### PR TITLE
{vis}[foss/2020b] OVITO v3.5.3 w/ Python 3.8.6

### PR DESCRIPTION
**Pull request by robert-mijakovic**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by robert-mijakovic** [comment]
@boegelbot: please test @ generoso

**Review by smoors — CHANGES_REQUESTED** [review]

**Comment by smoors** [comment]
@robert-mijakovic should Qt be added as a dependency?

**Comment by verdurin** [comment]
@robert-mijakovic any comment on the question from @smoors about `Qt`?

**Comment by robert-mijakovic** [comment]
> @robert-mijakovic should Qt be added as a dependency?

Doesn't PySide2 provide it?

**Comment by verdurin** [comment]
Test report by @verdurin
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
nuc.lan - Linux Fedora 33, x86_64, Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz, Python 3.9.5
See https://gist.github.com/94f4a31cebb25a0dfb8efa0ce3975277 for a full test report.

**Comment by verdurin** [comment]
This is another PR with `PySide2` as a bundled extension. Nothing inherently wrong with that, but just feels as though it could be handled better.

**Comment by boegel** [comment]
closing this since `foss/2020b` is deprecated, see https://docs.easybuild.io/policies/toolchains

see also:
* #16811

**Pull request closed without merging**
