### PR TITLE
{math}[gfbf/2023b] LinBox v1.7.0, IML v1.0.5, FFLAS-FFPACK v2.5.0, ...

### PR DESCRIPTION
**Pull request by PetrKralCZ**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by PetrKralCZ** [comment]
@boegelbot please test @ generoso

**Comment by PetrKralCZ** [comment]
@boegelbot please test @ jsc-zen3

**Review by smoors — APPROVED** [review]
lgtm

**Comment by smoors** [comment]
Going in, thanks @PetrKralCZ!

**Pull request merged**
