### PR TITLE
{bio}[gompi/2019b] RAxML-NG v1.0.1

### PR DESCRIPTION
**Pull request by branfosj**
(created using `eb --new-pr`)

Differences to `sources` and removal of `preconfigopts` (compared to https://github.com/easybuilders/easybuild-easyconfigs/blob/develop/easybuild/easyconfigs/r/RAxML-NG/RAxML-NG-0.9.0-gompi-2019b.eb) are based on review comments in #10363

### CODE REVIEW

**Comment by branfosj** [comment]
Test report by @branfosj
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
bear-pg0211u38b.bear.cluster - Linux centos linux 8.2.2004, x86_64, Intel(R) Xeon(R) Gold 6248 CPU @ 2.50GHz (cascadelake), Python 3.6.8
See https://gist.github.com/df80715ed4ef5705f618cfc1c6bb99da for a full test report.

**Comment by branfosj** [comment]
Test report by @branfosj
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
bear-pg0211u03a.bear.cluster - Linux centos linux 7.8.2003, x86_64, Intel(R) Xeon(R) Gold 6248 CPU @ 2.50GHz (cascadelake), Python 3.6.8
See https://gist.github.com/eb9ebe94b5bb91c4fd55d6ebddd744db for a full test report.

**Comment by lexming** [comment]
Test report by @lexming
**SUCCESS**
Build succeeded for 2 out of 2 (1 easyconfigs in total)
node128.hydra.os - Linux centos linux 7.9.2009, x86_64, Intel(R) Xeon(R) CPU E5-2680 v2 @ 2.80GHz, Python 2.7.5
See https://gist.github.com/87b34b3390ef783d5074a849f55327f9 for a full test report.

**Comment by lexming** [comment]
Test report by @lexming
**SUCCESS**
Build succeeded for 2 out of 2 (1 easyconfigs in total)
node376.hydra.os - Linux centos linux 7.9.2009, x86_64, Intel(R) Xeon(R) Gold 6148 CPU @ 2.40GHz, Python 2.7.5
See https://gist.github.com/c758118933b2082d2c4a0a3de75647eb for a full test report.

**Review by lexming — APPROVED** [review]
@branfosj thanks for moving the code placing the sources from `preconfigopts` to the `extract` step. It's a nice improvement.

LGTM

**Comment by lexming** [comment]
Going in, thanks @branfosj !

**Comment by boegel** [comment]
I ran into a confusing build failure with this one when building on our 96-core AMD systems, which also applies to other RAxML-NG easyconfigs:

```
I ran into a build failure that took me a while to figure out:

```
$ make -j 96
make[2]: Leaving directory '/tmp//RAxMLNG/0.9.0/GCC-8.3.0/easybuild_obj'
make[1]: *** [CMakeFiles/Makefile2:822: test/src/CMakeFiles/raxml_test_module.dir/all] Error 2                                                                                                             
make[1]: *** Waiting for unfinished jobs....                                                                                                                                                                
make[2]: Leaving directory '/tmp//RAxMLNG/0.9.0/GCC-8.3.0/easybuild_obj'                                                                                                            
make[1]: *** [CMakeFiles/Makefile2:771: src/CMakeFiles/raxml_module.dir/all] Error 2                                                                                                                        
make[1]: Leaving directory '/tmp//RAxMLNG/0.9.0/GCC-8.3.0/easybuild_obj'
make: *** [Makefile:144: all] Error 2
```

The actual (esay to miss...) problem was higher up:

```
make[2]: *** No rule to make target 'localdeps/lib/libterraces.a', needed by '/tmp/RAxMLNG/0.9.0/GCC-8.3.0/raxml-ng-0.9.0/bin/raxml-ng'.  Stop.
make[2]: *** Waiting for unfinished jobs....                                                                                                                                                                
make[2]: *** No rule to make target 'localdeps/lib/libterraces.a', needed by '/tmp/RAxMLNG/0.9.0/GCC-8.3.0/raxml-ng-0.9.0/test/bin/raxml_test'.  Stop.
make[2]: *** Waiting for unfinished jobs....
```

Reported upstream via https://github.com/amkozlov/raxml-ng/issues/108, workaround (`maxparallel = 10`) added in #10363 .

**Pull request merged**
