### PR TITLE
{math}[foss/2019b] spatialreg v1.1-5

### PR DESCRIPTION
**Pull request by orbsmiv**
Requires ~~#9745~~

(created using `eb --new-pr`)

### CODE REVIEW

**Comment by orbsmiv** [comment]
Test report by @orbsmiv
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
bear-pg0211u03a.bear.cluster - Linux centos linux 7.7.1908, Intel(R) Xeon(R) Gold 6248 CPU @ 2.50GHz, Python 2.7.5
See https://gist.github.com/6261fa5cf3d7ba0964259c4e49b437dd for a full test report.

**Comment by migueldiascosta** [comment]
closing and reopening to trigger tests

**Comment by migueldiascosta** [comment]
Test report by @migueldiascosta
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
generoso - Linux centos linux 7.6.1810, Intel(R) Xeon(R) CPU E5-2660 v4 @ 2.00GHz, Python 3.6.8
See https://gist.github.com/5fdde16c578320ba75b46d1d28665412 for a full test report.

**Comment by migueldiascosta** [comment]
Going in, thanks @orbsmiv!

**Pull request merged**
