### PR TITLE
{bio}[foss/2023a] Trinotate v4.0.2, TransDecoder v5.7.1, PyBioLib v1.1.2250

### PR DESCRIPTION
**Pull request by pavelToman**
(created using `eb --new-pr`)
resolves https://github.com/vscentrum/vsc-software-stack/issues/444
required Trinity + eggnog-mapper + Infernal from PR:
- https://github.com/easybuilders/easybuild-easyconfigs/pull/21705/

### CODE REVIEW

**Comment by pavelToman** [comment]
@boegelbot please test @ generoso

**Comment by pavelToman** [comment]
@boegelbot please test @ jsc-zen3

**Review by boegel — APPROVED** [review]
lgtm

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 5 out of 5 (3 easyconfigs in total)
node3121.skitty.os - Linux RHEL 9.4, x86_64, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz (skylake_avx512), Python 3.9.18
See https://gist.github.com/boegel/2e43a6ddb20a41c78fb5203a8050958a for a full test report.

**Comment by boegel** [comment]
Going in, thanks @pavelToman!

**Pull request merged**
