### PR TITLE
Make TensorFlow 1.7.0 work for AMD CPUs

### PR DESCRIPTION
**Pull request by smoors**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by akesandgren** [comment]
@smoors Is this still relevant?

**Comment by smoors** [comment]
@akesandgren we still have users of this module, but if you prefer not to merge it, that's fine too for me.

**Comment by akesandgren** [comment]
I just wanted to know if it was still relevant, and apparently it is :-)
So let's see what changes, if anything, it needs.

**Comment by akesandgren** [comment]
Rekicking Travis due to changes in EasyBuild testing

**Comment by akesandgren** [comment]
Travis kicked

**Comment by akesandgren** [comment]
@smoors Can you add a test report on an AMD system?

**Comment by akesandgren** [comment]
Test report by @akesandgren
**FAILED**
Build succeeded for 2 out of 3 (1 easyconfigs in this PR)
b-an03.hpc2n.umu.se - Linux ubuntu 16.04, Intel(R) Xeon(R) CPU E5-2690 v4 @ 2.60GHz, Python 2.7.12
See https://gist.github.com/0194917edfaf0659a304e6e3b8416d8e for a full test report.

**Comment by akesandgren** [comment]
Test report by @akesandgren
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
b-an03.hpc2n.umu.se - Linux ubuntu 16.04, Intel(R) Xeon(R) CPU E5-2690 v4 @ 2.60GHz, Python 2.7.12
See https://gist.github.com/666f1633402436a6c6e6f68dc42b99fc for a full test report.

**Comment by smoors** [comment]
Test report by @smoors
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
nic9 - Linux centos linux 7.5.1804, AMD Opteron(tm) Processor 6134, Python 2.7.5
See https://gist.github.com/05d3e3fc4d98dea54f564bc69d2dc34d for a full test report.

**Comment by akesandgren** [comment]
Going in, thanks @smoors!

**Pull request merged**
