### PR TITLE
{vis}[GCCcore/10.3.0,foss/2021a] grace v5.1.25, motif v2.3.8

### PR DESCRIPTION
**Pull request by furstj**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by SebastianAchilles** [comment]
Test report by @sebastianachilles
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in total)
rocky8-eb - Linux rocky linux 8.4, x86_64, Intel(R) Core(TM) i7-6900K CPU @ 3.20GHz (broadwell), Python 3.6.8
See https://gist.github.com/289735d0427586558436347f33e94e4a for a full test report.

**Comment by SebastianAchilles** [comment]
@boegelbot please test @ generoso

**Comment by migueldiascosta** [comment]
@boegelbot please test @ generoso

**Review by migueldiascosta — APPROVED** [review]
lgtm

**Comment by migueldiascosta** [comment]
Going in, thanks @furstj!

**Comment by migueldiascosta** [comment]
I just realized that most of the recent easyconfigs are under `Grace`, not `grace`, so I should have asked to rename the easyconfig in this PR

@boegel shall I open a PR to rename this latest easyconfig and maybe archive the older `grace` ones?

**Pull request merged**
