### PR TITLE
{compiler}[dummy/dummy] icc v2019.5.281

### PR DESCRIPTION
**Pull request by puttsk**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by boegel** [comment]
@puttsk Thank you very much for your contribution!

An easyconfig file equivalent to yours has already been merged in the `develop` branch however (to be included with the upcoming EasyBuild v4.0.0), via https://github.com/easybuilders/easybuild-easyconfigs/pull/8681 .

The only difference is that we no longer include a `versionsuffix` (while `GCCcore` & `binutils` are still dependencies), since we stick to a single `GCC`/`binutils` version anyway as base for `iccifort` toolchains.

**Comment by boegel** [comment]
Oh, and in addition we've also bundled up `icc` and `ifort` in a single `iccifort` installation, which makes things easier in some contents (like when a hierarchical module naming scheme is used).

**Comment by puttsk** [comment]
@boegel Thanks. Then, I'll use the new `iccifort` for our `intel/2019` installation.

**Comment by boegel** [comment]
@puttsk Excellent, so this PR and #8932 can be closed?

**Comment by puttsk** [comment]
@boegel  Yes, both can be closed. Thanks.

**Pull request closed without merging**
