### PR TITLE
{lang}[foss/2020a] R v4.0.3

### PR DESCRIPTION
**Pull request by terjekv**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by zao** [comment]
Test report by @zao
**FAILED**
Build succeeded for 0 out of 1 (1 easyconfigs in this PR)
freja - Linux Ubuntu 20.04, x86_64, Intel(R) Core(TM) i7-8700K CPU @ 3.70GHz, Python 3.8.5
See https://gist.github.com/25a9ef2537d7df36c423246dc96056e0 for a full test report.

**Comment by boegel** [comment]
@terjekv Were packages updated too? The comment above `exts_list` suggests it wasn't, but maybe that wasn't updated?

**Comment by terjekv** [comment]
> @terjekv Were packages updated too? The comment above `exts_list` suggests it wasn't, but maybe that wasn't updated?

Packages were not updated. I didn't dare with trying to get this to work on aarch64. Should I give a full update a stab?

**Comment by boegel** [comment]
@terjekv I don't think it's worth merging this without also updating the packages...

**Comment by terjekv** [comment]
> @terjekv I don't think it's worth merging this without also updating the packages...

I will... Poke the R.

**Comment by smoors** [comment]
@terjekv why not use `foss/2020b`?

**Comment by verdurin** [comment]
@terjekv any updates on this one?

**Comment by terjekv** [comment]
Nope, haven't had time to look at it, but I should! I have a few days off now, so maybe. :)

**Comment by boegel** [comment]
@terjekv I took your easyconfig, updated it for `foss/2020b`, and did another round of updating the extensions (+ re-ordering and adding additional now required ones), result is in #11663.

So this PR should be closed?

**Comment by terjekv** [comment]
Yes!

**Pull request closed without merging**
