### PR TITLE
{math}[foss/2018a] Octave 4.2.1 + deps

### PR DESCRIPTION
**Pull request by boegel**
(created using `eb --new-pr`)
depends on ~~#5955~~

### CODE REVIEW

**Comment by boegel** [comment]
With a bit of patching, we can probably get Octave 4.2.1 to build on top of HDF5 1.10.1, see https://savannah.gnu.org/bugs/?47858...

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 10 out of 10 (10 easyconfigs in this PR)
node2036.delcatty.os - Linux centos linux 7.4.1708, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.7.5
See https://gist.github.com/ede61d42677505798e990cf2196fd345 for a full test report.

**Comment by migueldiascosta** [comment]
Test report by @migueldiascosta
**FAILED**
Build succeeded for 14 out of 16 (10 easyconfigs in this PR)
grc-cluster1 - Linux centos 6.9, Intel(R) Xeon(R) CPU E5-2640 0 @ 2.50GHz, Python 2.6.6
See https://gist.github.com/419fba76175c3c58fc3c5baefc2e38a4 for a full test report.

**Comment by boegel** [comment]
@migueldiascosta Can you check whether you can get around this by defining `$CPPFLAGS` in `prebuildopts` (maybe also in `preconfigopts`), cfr. https://stackoverflow.com/questions/21545076/libpng-png-set-longjmp-fn-not-found

**Comment by migueldiascosta** [comment]
@boegel hm, no, nothing like this seems to work,

```python
preconfigopts = 'CPPFLAGS="-I$EBROOTLIBPNG/include $CPPFLAGS" '
preconfigopts += 'LDFLAGS="-L$EBROOTLIBPNG/lib $LDFLAGS" '

configopts = '--enable-shared --enable-threads --enable-xft'

prebuildopts = 'CPPFLAGS="-I$EBROOTLIBPNG/include $CPPFLAGS" '
prebuildopts += 'LDFLAGS="-L$EBROOTLIBPNG/lib $LDFLAGS" '
```

removing the system `libpng-devel` does work, but it should be possible to make the easybuild one take preference...

**Comment by boegel** [comment]
@migueldiascosta Can you try again (without `CPPFLAGS`), with the following patch applied for `FLTK` so we see the full link line that fails?

```diff
--- fltk-1.3.4/src/Makefile.orig        2018-03-20 12:17:26.072745146 +0100
+++ fltk-1.3.4/src/Makefile     2018-03-20 12:17:32.532860144 +0100
@@ -347,6 +347,7 @@

 libfltk_images.so.$(FL_DSO_VERSION): $(IMGOBJECTS) libfltk.so.$(FL_DSO_VERSION)
        echo $(DSOCOMMAND) $@ ...
+       echo $(DSOCOMMAND) $@ $(IMGOBJECTS) -L. $(IMAGELIBS) -lfltk $(LDLIBS)
        $(DSOCOMMAND) $@ $(IMGOBJECTS) -L. $(IMAGELIBS) -lfltk $(LDLIBS)
        $(RM) libfltk_images.so
        $(LN) libfltk_images.so.$(FL_DSO_VERSION) libfltk_images.so
```

**Comment by migueldiascosta** [comment]
```bash
g++ -L. -Wl,-no-undefined -Wl,-Bsymbolic-functions -Wl,-gc-sections -Wl,-soname,libfltk_images.so.1.3 -lXrender -lXcursor -lXfixes -lXext  -lXft -lfontconfig -lXinerama -lpthread -ldl -lm -lpthread -lX11 -shared -fPIC -o libfltk_images.so.1.3 fl_images_core.o Fl_BMP_Image.o Fl_File_Icon2.o Fl_GIF_Image.o Fl_Help_Dialog.o Fl_JPEG_Image.o Fl_PNG_Image.o Fl_PNM_Image.o -L. -L../lib -lpng -lz -ljpeg -lfltk -lXrender -lXcursor -lXfixes -lXext -lXft -lfontconfig -lXinerama -lpthread -ldl -lm -lpthread -lX11
```
setting `CPPFLAGS` and/or `LDFLAGS` doesn't change this. 

Additionally, it is strange that in `fltk-config` the variable `LDLIBS` contains the environment inherited `LDFLAGS`, but it gets overriden by `makeinclude`.

Patching `makeinclude.in` works:

``` diff
--- makeinclude.in.orig	2018-03-21 10:46:28.685115000 +0800
+++ makeinclude.in	2018-03-21 10:46:45.429413816 +0800
@@ -93,7 +93,7 @@
 CAIROFLAGS	= @CAIROFLAGS@
 DSOFLAGS	= -L. @DSOFLAGS@
 LDFLAGS	= $(OPTIM) @LDFLAGS@
-LDLIBS		= @LIBS@
+LDLIBS		= @LDFLAGS@ @LIBS@
 GLDLIBS	= @GLLIB@ @LIBS@
 LINKFLTK	= @LINKFLTK@
 LINKFLTKGL	= @LINKFLTKGL@
```

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 10 out of 10 (10 easyconfigs in this PR)
node2462.golett.os - Linux centos linux 7.4.1708, Intel(R) Xeon(R) CPU E5-2680 v3 @ 2.50GHz, Python 2.7.5
See https://gist.github.com/d07a2f22c316384368fc3f39bddeca6e for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 10 out of 10 (10 easyconfigs in this PR)
node2072.delcatty.os - Linux centos linux 7.4.1708, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.7.5
See https://gist.github.com/8d563bff37557fa9e992ff9a5c449487 for a full test report.

**Comment by migueldiascosta** [comment]
Test report by @migueldiascosta
**SUCCESS**
Build succeeded for 10 out of 10 (10 easyconfigs in this PR)
grc-cluster1 - Linux centos 6.9, Intel(R) Xeon(R) CPU E5-2640 0 @ 2.50GHz, Python 2.6.6
See https://gist.github.com/2c0b57bd662929d7a335d39cb15d8636 for a full test report.

**Comment by migueldiascosta** [comment]
Going in, thanks @boegel!

**Pull request merged**
