### PR TITLE
{lang}[GCCcore/8.3.0] Rust v1.37.0

### PR DESCRIPTION
**Pull request by boegel**
(created using `eb --new-pr`)
requires ~~#8962~~ (CMake)

### CODE REVIEW

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
node3151.skitty.os - Linux centos linux 7.6.1810, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz, Python 3.6.8
See https://gist.github.com/016b7cd6565645913fe386fe893cb636 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
node2455.golett.os - Linux centos linux 7.6.1810, Intel(R) Xeon(R) CPU E5-2680 v3 @ 2.50GHz, Python 2.7.5
See https://gist.github.com/4440d52b32c736c1e395eda077b2cfea for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
node2065.delcatty.os - Linux centos linux 7.6.1810, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.7.5
See https://gist.github.com/720f71c6ef72ec085e9e2abce8291b27 for a full test report.

**Comment by Micket** [comment]
Test report by @Micket
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
vera-c1 - Linux centos linux 7.6.1810, Intel Xeon Processor (Skylake), Python 2.7.5
See https://gist.github.com/f30bf410982fca46b3b11ba5215f3708 for a full test report.

**Comment by Micket** [comment]
@boegel Do we not need llvm support in rust anymore (did they change it)?

**Comment by boegel** [comment]
@Micket Hmm, wasn't there in the easyconfig for Rust 1.30.1 or 1.35.0, so I just overlooked it...

Will look into adding it back.

**Comment by boegel** [comment]
@Micket Tried using LLVM 9.0.0 from #8964, but that failed miserably.

Based on https://rust-lang.github.io/rustc-guide/codegen/updating-llvm.html, it seems like they vendor a specific version of LLVM and also patch it, so it doesn't seem wise to try and provide our own version taking that into account...

**Comment by boegel** [comment]
FWIW, here's the error I ran into with LLVM 9.0.0 as dep:

```
cargo:warning=../rustllvm/PassWrapper.cpp: In function LLVMRustThinLTOData* LLVMRustCreateThinLTOData(LLVMRustThinLTOModule*, int, const char**, int):
cargo:warning=../rustllvm/PassWrapper.cpp:917:77: error: too few arguments to function void llvm::thinLTOResolvePrevailingInIndex(llvm::ModuleSummaryIndex&, llvm::function_ref<bool(long unsigned int, const llvm::GlobalValueSummary*)>, llvm::function_ref<void(llvm::StringRef, long unsigned int, llvm::GlobalValue::LinkageTypes)>, const llvm::DenseSet<long unsigned int>&)
cargo:warning=   thinLTOResolvePrevailingInIndex(Ret->Index, isPrevailing, recordNewLinkage);
cargo:warning=
```

**Comment by Micket** [comment]
@boegel so it builds it's own llvm when you don't specify anything?

**Comment by boegel** [comment]
@Micket Exactly, they shipped their own (patched) copy of LLVM

**Comment by Micket** [comment]
Going in, thanks @boegel!

**Comment by akesandgren** [comment]
Rust requires XML-RPC which we don't have in EB.
Did you have this from the OS when trying to build?

**Comment by Micket** [comment]
@akesandgren I didn't have xmlrpc installed on the system i build the module on. I also can't find any references to it in the build log. Rust itself did download lots of things though, but, I can only find jsonrpc-core in there.

**Comment by akesandgren** [comment]
Ok, here we have libxmlrpc-core-c3-dev installed (at the moment) and then it finds /usr/include/XmlRpcCpp.h (which is a softlink to an include file that doesn't exist so it explodes)

Haven't had time to check without that -dev package yet.

**Comment by akesandgren** [comment]
Yep without that OS -dev package stuff builds ok.

**Comment by akesandgren** [comment]
However, Rust abuses $HOME/.cargo so we need to fix that somehow...

**Comment by zao** [comment]
@akesandgren The culprit regarding XmlRpcCpp.h isn't specific to that library, it triggers on any broken header link in /usr/include, thanks to that LLVM globs system headers and puts them all as sources in targets.

I guess this might be a naive way to rebuild themselves on changes made to the system?

```
/hp/eb/build/Rust/1.35.0/GCCcore-8.2.0/rustc-1.35.0-src/src/llvm-project/llvm/cmake/modules/LLVMProcessSources.cmake(41):  add_header_files_for_glob(hds /usr/include/*.h )
/hp/eb/build/Rust/1.35.0/GCCcore-8.2.0/rustc-1.35.0-src/src/llvm-project/llvm/cmake/modules/LLVMProcessSources.cmake(43):  add_header_files_for_glob(hds /usr/include/*.inc )
```

**Comment by zao** [comment]
@akesandgren The problem with XmlRpcCpp.h isn't specific to that library, it triggers on any broken header link in /usr/include, thanks to that LLVM globs system headers and puts them all as sources in targets.

I guess this might be a naive way to rebuild themselves on changes made to the system?

```
/hp/eb/build/Rust/1.35.0/GCCcore-8.2.0/rustc-1.35.0-src/src/llvm-project/llvm/cmake/modules/LLVMProcessSources.cmake(41):  add_header_files_for_glob(hds /usr/include/*.h )
/hp/eb/build/Rust/1.35.0/GCCcore-8.2.0/rustc-1.35.0-src/src/llvm-project/llvm/cmake/modules/LLVMProcessSources.cmake(43):  add_header_files_for_glob(hds /usr/include/*.inc )
```

**Pull request merged**
