### PR TITLE
{bio}[foss/2018a] BCFtools 1.9

### PR DESCRIPTION
**Pull request by bedroge**

### CODE REVIEW

**Comment by bedroge** [comment]
I guess this means that I have to change the version of HTSlib to 1.8?

**Comment by boegel** [comment]
Strictly speaking, yes, but does it make sense to combine `HTSlib` 1.8 with `BCFtools` 1.9?

@verdurin Thoughts?

**Comment by jdemeul** [comment]
See also #6734. 

I changed it to 1.8, but also think it makes more sense to keep the versions of BCFtools, SAMtools and HTSlib synced.

**Comment by bedroge** [comment]
I'll close this one, since it's the same as #6734.

**Comment by boegel** [comment]
:+1:, thanks for following up @bedroge!

**Pull request closed without merging**
