### PR TITLE
{vis}[GCC/10.2.0] GST-plugins-base v1.18.4

### PR DESCRIPTION
**Pull request by akesandgren**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by akesandgren** [comment]
@boegelbot Please test @ generoso

**Comment by Micket** [comment]
Note: this was also part of #12537 already.

(In that PR i also question whether this needs to be in GCC rather than GCCcore)

**Comment by akesandgren** [comment]
Dohh, didn't remember to check incoming PR's..

**Comment by akesandgren** [comment]
And no, can't drop down to GCCcore. GStreamer uses GSL which is at GCC and GSL is performance important.

This is also a somewhat newer version of GStreamer/GST-... than in #12537

**Comment by akesandgren** [comment]
@boegelbot Please test @ generoso

**Review by Micket — APPROVED** [review]
lgtm

**Comment by Micket** [comment]
Test report by @Micket
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in total)
vera-c1 - Linux centos linux 7.9.2009, x86_64, Intel Xeon Processor (Skylake), Python 2.7.5
See https://gist.github.com/2e7b5f56a8b6771cb6ec3334f6075ce7 for a full test report.

**Comment by Micket** [comment]
Going in, thanks @akesandgren!

**Pull request merged**
