### PR TITLE
rename R bindings for Arrow to arrow-R, so it can be used in a lowercase module naming scheme

### PR DESCRIPTION
**Pull request by boegel**

### CODE REVIEW

**Comment by boegel** [comment]
@boegelbot please test @ generoso

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
node2607.swalot.os - Linux centos linux 7.9.2009, x86_64, Intel(R) Xeon(R) CPU E5-2660 v3 @ 2.60GHz (haswell), Python 3.6.8
See https://gist.github.com/d12b100229b13d8ef58f6c507be18563 for a full test report.

**Comment by branfosj** [comment]
Test report by @branfosj
**FAILED**
Build succeeded for 0 out of 2 (1 easyconfigs in total)
bear-pg0211u08b.bear.cluster - Linux RHEL 8.3, x86_64, Intel(R) Xeon(R) Gold 6248 CPU @ 2.50GHz (cascadelake), Python 3.6.8
See https://gist.github.com/8ccd24d3f5f17e7663d150f953f3f140 for a full test report.

**Comment by branfosj** [comment]
> Test report by @branfosj **FAILED** Build succeeded for 0 out of 2 (1 easyconfigs in total) bear-pg0211u08b.bear.cluster - Linux RHEL 8.3, x86_64, Intel(R) Xeon(R) Gold 6248 CPU @ 2.50GHz (cascadelake), Python 3.6.8 See https://gist.github.com/8ccd24d3f5f17e7663d150f953f3f140 for a full test report.

Fix, for Arrow, in https://github.com/easybuilders/easybuild-easyconfigs/pull/14263

**Comment by branfosj** [comment]
Test report by @branfosj
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
bear-pg0211u03a.bear.cluster - Linux RHEL 8.3, x86_64, Intel(R) Xeon(R) Gold 6248 CPU @ 2.50GHz (cascadelake), Python 3.6.8
See https://gist.github.com/2116365eb0aed659436a14b7bebce274 for a full test report.

**Review by branfosj — APPROVED** [review]
lgtm

**Comment by verdurin** [comment]
Going in, thanks @boegel!

**Pull request merged**
