### PR TITLE
{tools}[foss/2019a] NCO v4.8.1, ANTLR 2.7.7

### PR DESCRIPTION
**Pull request by branfosj**

### CODE REVIEW

**Comment by branfosj** [comment]
Test report by @branfosj
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in this PR)
bear-pg0211u03a.bear.cluster - Linux centos linux 7.6.1810, Intel(R) Xeon(R) Gold 6248 CPU @ 2.50GHz, Python 2.7.5
See https://gist.github.com/a73e5f500dfe10ec4604ddedc8dab8ea for a full test report.

**Comment by branfosj** [comment]
Test report by @branfosj
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in this PR)
bber0501u03a.bb2.cluster - Linux centos linux 7.6.1810, Intel(R) Xeon(R) CPU E5-2690 v3 @ 2.60GHz, Python 2.7.5
See https://gist.github.com/154b7176801f74b7a30d8372e592b4e4 for a full test report.

**Comment by branfosj** [comment]
I think the CI failure is coming from the Java dependency in https://github.com/easybuilders/easybuild-easyconfigs/blob/master/easybuild/easyconfigs/a/ANTLR/ANTLR-2.7.7-GCCcore-8.2.0.eb - so I am not sure what I should do to fix it.

**Comment by zao** [comment]
I would expect that this libdap also would need the update done in #8792 to make it build on newer glibc.

**Comment by zao** [comment]
Test report by @zao
**FAILED**
Build succeeded for 1 out of 3 (2 easyconfigs in this PR)
freja - Linux fedora 30, Intel(R) Core(TM) i7-8700K CPU @ 3.70GHz, Python 2.7.16
See https://gist.github.com/fb6d725ece580c81c2842d8439756c77 for a full test report.

**Comment by branfosj** [comment]
Thanks for the pointer @zao - I've added libtirpc.

**Comment by branfosj** [comment]
Test report by @branfosj
**SUCCESS**
Build succeeded for 3 out of 3 (3 easyconfigs in this PR)
bear-pg0211u03a.bear.cluster - Linux centos linux 7.6.1810, Intel(R) Xeon(R) Gold 6248 CPU @ 2.50GHz, Python 2.7.5
See https://gist.github.com/5d83dc3a2be5d2597c221656af603069 for a full test report.

**Comment by branfosj** [comment]
Test report by @branfosj
**SUCCESS**
Build succeeded for 3 out of 3 (3 easyconfigs in this PR)
bber0501u03a.bb2.cluster - Linux centos linux 7.6.1810, Intel(R) Xeon(R) CPU E5-2690 v3 @ 2.60GHz, Python 2.7.5
See https://gist.github.com/0af07429ea3ae67e15523c568bb9bf20 for a full test report.

**Comment by boegel** [comment]
@branfosj The tests are failing because we're introducing `Java/1.8` as a dependency in the `2019a` generation of easyconfig files (via `NCO` -> `ANTLR` `2.7.7`).

We have two major options:

* add another easyconfig for `ANTLR` `2.7.7` that depends on `Java/11` instead (and has `-Java-11` as `versionsuffix`)
* see if we can use a more recent version of `ANTLR` as dependency for `NCO` (v4.7.2 is latest, see https://www.antlr.org/), and if so, add an easyconfig file for that using `Java/11` as dependency

**Comment by branfosj** [comment]
Test report by @branfosj
**SUCCESS**
Build succeeded for 4 out of 4 (4 easyconfigs in this PR)
bear-pg0211u03a.bear.cluster - Linux centos linux 7.6.1810, Intel(R) Xeon(R) Gold 6248 CPU @ 2.50GHz, Python 2.7.5
See https://gist.github.com/3dcc7e076b87ab15cfd1daffda366a51 for a full test report.

**Comment by branfosj** [comment]
Test report by @branfosj
**SUCCESS**
Build succeeded for 4 out of 4 (4 easyconfigs in this PR)
bber0501u03a.bb2.cluster - Linux centos linux 7.6.1810, Intel(R) Xeon(R) CPU E5-2690 v3 @ 2.60GHz, Python 2.7.5
See https://gist.github.com/6ded180493ebd4e6e515e19e6a3243f6 for a full test report.

**Comment by branfosj** [comment]
@boegel I added a `ANTLR-2.7.7-GCCcore-8.2.0-Java-11.eb` but the CI checks is still failing. Should this have been `ANTLR-2.7.7-foss-2019a-Java-11.eb` instead?

**Comment by branfosj** [comment]
Test report by @branfosj
**SUCCESS**
Build succeeded for 4 out of 4 (4 easyconfigs in this PR)
bb2c1a09.bb2.cluster - Linux centos linux 7.6.1810, Intel(R) Xeon(R) CPU E5-2660 0 @ 2.20GHz, Python 2.7.5
See https://gist.github.com/221877429e4bb07896a8222e3123c12f for a full test report.

**Comment by branfosj** [comment]
Test report by @branfosj
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in this PR)
bear-pg0211u03a.bear.cluster - Linux centos linux 7.6.1810, Intel(R) Xeon(R) Gold 6248 CPU @ 2.50GHz, Python 2.7.5
See https://gist.github.com/2d294c1bcb6198c8142f92268983f255 for a full test report.

**Comment by branfosj** [comment]
Test report by @branfosj
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in this PR)
bber0501u03a.bb2.cluster - Linux centos linux 7.6.1810, Intel(R) Xeon(R) CPU E5-2690 v3 @ 2.60GHz, Python 2.7.5
See https://gist.github.com/4c7aabf36127852f5620ce36808a8129 for a full test report.

**Comment by branfosj** [comment]
Test report by @branfosj
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in this PR)
bb2c1a09.bb2.cluster - Linux centos linux 7.6.1810, Intel(R) Xeon(R) CPU E5-2660 0 @ 2.20GHz, Python 2.7.5
See https://gist.github.com/a4d02cf48c366b03d83ee57cf2cf31c7 for a full test report.

**Comment by boegel** [comment]
Close+re-open to re-trigger Travis...

The issue with `Java` in the tests is probably fixed in #9041...

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in this PR)
node3100.skitty.os - Linux centos linux 7.6.1810, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz, Python 3.6.8
See https://gist.github.com/060c099920ac860c4dd0c18b588a805c for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in this PR)
node2675.swalot.os - Linux centos linux 7.6.1810, Intel(R) Xeon(R) CPU E5-2660 v3 @ 2.60GHz, Python 2.7.5
See https://gist.github.com/91adecff9d21d941a6415b4e1203eb3d for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in this PR)
node2093.delcatty.os - Linux centos linux 7.6.1810, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.7.5
See https://gist.github.com/a2b5f48370fc0ca51bcb6bc83a7bc89a for a full test report.

**Comment by boegel** [comment]
Going in, thanks @branfosj!

**Pull request merged**
