### PR TITLE
{data}[intel/2017a] PyTables v3.4.2 w/ Python 3.6.1

### PR DESCRIPTION
**Pull request by boegel**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by boegel** [comment]
Test report by @boegel
**FAILED**
Build succeeded for 2 out of 3 (3 easyconfigs in this PR)
node2121.delcatty.os - Linux centos linux 7.4.1708, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.7.5
See https://gist.github.com/757d7233329b79989136ab1e28e4ba5c for a full test report.

**Comment by verdurin** [comment]
I see errors like this:
```
[ 91%] Building C object tests/CMakeFiles/test_shuffle_roundtrip_generic.dir/test_shuffle_roundtrip_generic.c.o
cd /dev/shm/Blosc/1.12.1/intel-2017a/c-blosc-1.12.1/tests && /users/rescomp/adamh/.local/easybuild/software/icc/2017.1.132-GCC-6.3.0-2.27/compilers_and_libraries_2017.1.132/linux/bin/intel64/icc -DBLOSC_TESTING -DSHUFFLE_SSE2_ENABLED -I/d
ev/shm/Blosc/1.12.1/intel-2017a/c-blosc-1.12.1/blosc  -O2 -xHost -ftz -fp-speculation=safe -fp-model source -O3 -DNDEBUG   -o CMakeFiles/test_shuffle_roundtrip_generic.dir/test_shuffle_roundtrip_generic.c.o   -c /dev/shm/Blosc/1.12.1/inte
l-2017a/c-blosc-1.12.1/tests/test_shuffle_roundtrip_generic.c
In file included from /dev/shm/Blosc/1.12.1/intel-2017a/c-blosc-1.12.1/tests/test_getitem.c(12):
/dev/shm/Blosc/1.12.1/intel-2017a/c-blosc-1.12.1/tests/test_common.h(67): warning #266: function "aligned_alloc" declared implicitly
    block = aligned_alloc(alignment, size);
            ^

In file included from /dev/shm/Blosc/1.12.1/intel-2017a/c-blosc-1.12.1/tests/test_getitem.c(12):
/dev/shm/Blosc/1.12.1/intel-2017a/c-blosc-1.12.1/tests/test_common.h(67): warning #556: a value of type "int" cannot be assigned to an entity of type "void *"
    block = aligned_alloc(alignment, size);
          ^
```
followed by:
```
[ 98%] Linking C executable test_compressor
cd /dev/shm/Blosc/1.12.1/intel-2017a/c-blosc-1.12.1/tests && /gpfs2/well/rescomp/eb/software/CMake/3.9.1-GCCcore-6.3.0/bin/cmake -E cmake_link_script CMakeFiles/test_compressor.dir/link.txt --verbose=1
/users/rescomp/adamh/.local/easybuild/software/icc/2017.1.132-GCC-6.3.0-2.27/compilers_and_libraries_2017.1.132/linux/bin/intel64/icc -O2 -xHost -ftz -fp-speculation=safe -fp-model source -O3 -DNDEBUG  -L/users/rescomp/adamh/.local/easybuild/software/icc/2017.1.132-GCC-6.3.0-2.27/lib/intel64 -L/users/rescomp/adamh/.local/easybuild/software/imkl/2017.1.132-iimpi-2017a/lib -L/users/rescomp/adamh/.local/easybuild/software/imkl/2017.1.132-iimpi-2017a/mkl/lib/intel64 -L/users/rescomp/adamh/.local/easybuild/software/imkl/2017.1.132-iimpi-2017a/lib -rdynamic CMakeFiles/test_compressor.dir/test_compressor.c.o  -o test_compressor  -L/dev/shm/Blosc/1.12.1/intel-2017a/c-blosc-1.12.1/blosc -Wl,-rpath,/dev/shm/Blosc/1.12.1/intel-2017a/c-blosc-1.12.1/blosc -lblosc_testing
CMakeFiles/test_getitem.dir/test_getitem.c.o: In function `main':
test_getitem.c:(.text+0x31d): undefined reference to `aligned_alloc'
test_getitem.c:(.text+0x374): undefined reference to `aligned_alloc'
test_getitem.c:(.text+0x3b6): undefined reference to `aligned_alloc'
CMakeFiles/test_noinit.dir/test_noinit.c.o: In function `main':
test_noinit.c:(.text+0x71): undefined reference to `aligned_alloc'
test_noinit.c:(.text+0xae): undefined reference to `aligned_alloc'
test_noinit.c:(.text+0xef): undefined reference to `aligned_alloc'
test_noinit.c:(.text+0x12c): undefined reference to `aligned_alloc'
CMakeFiles/test_shuffle_roundtrip_generic.dir/test_shuffle_roundtrip_generic.c.o: In function `main':
test_shuffle_roundtrip_generic.c:(.text+0x138): undefined reference to `aligned_alloc'
test_shuffle_roundtrip_generic.c:(.text+0x165): undefined reference to `aligned_alloc'
test_shuffle_roundtrip_generic.c:(.text+0x191): undefined reference to `aligned_alloc'
CMakeFiles/test_compressor.dir/test_compressor.c.o: In function `main':
test_compressor.c:(.text+0x64): undefined reference to `aligned_alloc'
test_compressor.c:(.text+0xa1): undefined reference to `aligned_alloc'
test_compressor.c:(.text+0xe2): undefined reference to `aligned_alloc'
test_compressor.c:(.text+0x11f): undefined reference to `aligned_alloc'
make[2]: *** [tests/test_getitem] Error 1
make[2]: Leaving directory `/dev/shm/Blosc/1.12.1/intel-2017a/c-blosc-1.12.1'
make[1]: *** [tests/CMakeFiles/test_getitem.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
make[2]: *** [tests/test_noinit] Error 1
```

**Comment by boegel** [comment]
Test report by @boegel
**FAILED**
Build succeeded for 2 out of 3 (3 easyconfigs in this PR)
node2639.swalot.os - Linux centos linux 7.4.1708, Intel(R) Xeon(R) CPU E5-2660 v3 @ 2.60GHz, Python 2.7.5
See https://gist.github.com/92ec5770dd8c96ee275125e6233a2b47 for a full test report.

**Comment by boegel** [comment]
@verdurin Which OS? Works fine for me on CentOS 7.4.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 3 out of 3 (3 easyconfigs in this PR)
node2682.swalot.os - Linux centos linux 7.4.1708, Intel(R) Xeon(R) CPU E5-2660 v3 @ 2.60GHz, Python 2.7.5
See https://gist.github.com/76c6327ff54b54c9ea29099ebfbdc92f for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 3 out of 3 (3 easyconfigs in this PR)
node2121.delcatty.os - Linux centos linux 7.4.1708, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.7.5
See https://gist.github.com/9ce69261670c851b50b5076770120337 for a full test report.

**Comment by verdurin** [comment]
@boegel CentOS 6.8.

**Comment by boegel** [comment]
@verdurin Which `glibc` version is that? See also https://github.com/shadow/shadow/issues/148 .

We may need a patch to fix the installation of `Blosc` 1.12.1 on CentOS 6.x...

**Comment by boegel** [comment]
@verdurin It seems like it's just a matter of incorrect detection whether or not `aligned_alloc` is supported in the `Blosc` tests, see https://github.com/Blosc/c-blosc/blob/master/tests/test_common.h#L65. That's the only place `aligned_alloc` occurs.

This seems relevant: https://github.com/Blosc/bloscpack/issues/50.

In the code itself, they're only using `aligned_malloc` (extra `m`) when building with MingW (i.e. on Windows), so my guess is the tests should be doing something similar...

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 3 out of 3 (3 easyconfigs in this PR)
node2410.golett.os - Linux centos linux 7.4.1708, Intel(R) Xeon(R) CPU E5-2680 v3 @ 2.50GHz, Python 2.7.5
See https://gist.github.com/a35bb2037c985e2f044cf6fe6396155a for a full test report.

**Comment by boegel** [comment]
@verdurin Please retest on CentOS 6?

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 3 out of 3 (3 easyconfigs in this PR)
node2085.delcatty.os - Linux centos linux 7.4.1708, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.7.5
See https://gist.github.com/bbdd0efbd44a1f2eb0c8786028d74d01 for a full test report.

**Comment by migueldiascosta** [comment]
Test report by @migueldiascosta
**SUCCESS**
Build succeeded for 7 out of 7 (3 easyconfigs in this PR)
grc-cluster1 - Linux centos 6.9, Intel(R) Xeon(R) CPU E5-2640 0 @ 2.50GHz, Python 2.6.6
See https://gist.github.com/65bb15f8d82a371603347f904d75b200 for a full test report.

**Comment by verdurin** [comment]
Test report by @verdurin
**SUCCESS**
Build succeeded for 5 out of 5 (3 easyconfigs in this PR)
rescomp2 - Linux centos 6.8, Intel(R) Xeon(R) CPU E5-2650 v2 @ 2.60GHz, Python 2.7.14
See https://gist.github.com/0bc837c7c3cc9ffd3dda5dad31367655 for a full test report.

**Comment by verdurin** [comment]
Going in, thanks @boegel!

**Pull request merged**
