### PR TITLE
{bio}[foss/2018b] BlobTools v20180528

### PR DESCRIPTION
**Pull request by smoors**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by verdurin** [comment]
Test report by @verdurin
**SUCCESS**
Build succeeded for 3 out of 3 (1 easyconfigs in this PR)
rescomp2 - Linux centos linux 7.3.1611, Intel(R) Xeon(R) Gold 6126 CPU @ 2.60GHz, Python 2.7.5
See https://gist.github.com/f5b1e357a962999e13f1ec5d7ed505fb for a full test report.

**Comment by boegel** [comment]
@smoors Sanity check fails for me because of missing `data/nodesDB.txt`, any idea why?

**Comment by boegel** [comment]
Test report by @boegel
**FAILED**
Build succeeded for 0 out of 1 (1 easyconfigs in this PR)
node3100.skitty.os - Linux centos linux 7.6.1810, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz, Python 2.7.5
See https://gist.github.com/6c87543c16e27298b7724d3a179e331b for a full test report.

**Comment by smoors** [comment]
@boegel the `install` script downloads `taxdump.tar.gz`,
unpacks it into `nodes.dmp` and `names.dmp`,
and converts these to `nodesDB.txt` with the `blobtools` program itself (after its own installation).

Not sure where it went wrong in your case, you should check the `build_step` in your logs.

**Comment by boegel** [comment]
@smoors This explains it (`ftp` is blocked on our systems):

```
[+] Downloading NCBI taxdump from ftp://ftp.ncbi.nlm.nih.gov/pub/taxonomy/taxdump.tar.gz ...FAIL.                                                                                                     [X] - Could not download NCBI taxdump. Please follow installation steps on https://blobtools.readme.io/
```

Can we pre-download `taxdump.tar.gz` ourselves, and seed it in?

**Comment by smoors** [comment]
@boegel see https://github.com/easybuilders/easybuild-easyconfigs/pull/7583

**Pull request merged**
