### PR TITLE
{bio}[GCC/9.3.0] BLAT v3.5

### PR DESCRIPTION
**Pull request by boegel**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
node3141.skitty.os - Linux centos linux 7.8.2003, x86_64, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz, Python 3.6.8
See https://gist.github.com/b49a19fef3095e27d898d1a30740b028 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
node3406.kirlia.os - Linux centos linux 7.8.2003, x86_64, Intel(R) Xeon(R) Gold 6240 CPU @ 2.60GHz (cascadelake), Python 2.7.5
See https://gist.github.com/a628c2699ebf4f1b592c876cacf9a633 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
node2434.golett.os - Linux centos linux 7.8.2003, x86_64, Intel(R) Xeon(R) CPU E5-2680 v3 @ 2.50GHz (haswell), Python 2.7.5
See https://gist.github.com/a5b7e6a0382639f33e10ab1806f832c5 for a full test report.

**Comment by verdurin** [comment]
Test report by @verdurin
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
nuc.lan - Linux Fedora 32, x86_64, Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz, Python 3.8.5
See https://gist.github.com/e6abe463c81fbc6dbc790ff19dcfd594 for a full test report.

**Comment by verdurin** [comment]
@boegel this looks okay, but isn't `BLAT` included in the whole of `Kent tools`?

**Comment by boegel** [comment]
> @boegel this looks okay, but isn't `BLAT` included in the whole of `Kent tools`?

Maybe, but do we have to pull in the full `Kent_tools` stack when only `BLAT` is required (either directly or as a dep)?

**Comment by verdurin** [comment]
> > @boegel this looks okay, but isn't `BLAT` included in the whole of `Kent tools`?
> 
> Maybe, but do we have to pull in the full `Kent_tools` stack when only `BLAT` is required (either directly or as a dep)?

If the latter then fine. Just didn't want to duplicate unnecessarily.

**Review by verdurin — APPROVED** [review]
Looks fine.

**Comment by verdurin** [comment]
Going in, thanks @boegel!

**Pull request merged**
