### PR TITLE
{data}[gmpolf/2017.10] HDF5 v1.8.20

### PR DESCRIPTION
**Pull request by t0rrant**

### CODE REVIEW

**Comment by akesandgren** [comment]
Rekicking Travis due to changes in EasyBuild testing.

**Comment by akesandgren** [comment]
Travis kicked

**Review by boegel — APPROVED** [review]
lgtm

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in total)
node2707.swalot.os - Linux centos linux 7.9.2009, x86_64, Intel(R) Xeon(R) CPU E5-2660 v3 @ 2.60GHz (haswell), Python 3.6.8
See https://gist.github.com/3e81a732f3b8e37959307f71432b0db4 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in total)
node3129.skitty.os - Linux centos linux 7.9.2009, x86_64, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz, Python 3.6.8
See https://gist.github.com/2eb9fcec21ab9195d972a9f55e2c261a for a full test report.

**Comment by boegel** [comment]
Sorry for the long delay in getting this merged @t0rrant...

We're in the middle of a merge sprint, tackling the current oldest open PRs, happy to see it was trivial to get this ready for merging with minimal effort.

**Comment by t0rrant** [comment]
Np, I resorted to local setup at the time. Glad to see it was easy 😀

**Pull request merged**
