### PR TITLE
{lib}[foss/2021a] imagecodecs v2022.9.26 w/ Python 3.9.5

### PR DESCRIPTION
**Pull request by ThomasHoffmann77**
(created using `eb --new-pr`)
requires:
* #16537
* #16538
* #16539
* #16540
* #16541
* #16542
* #16543
* #16544
* #16545
* #16546
* #16547
*  #16548

### CODE REVIEW

**Comment by verdurin** [comment]
@ThomasHoffmann77 any thoughts on how to handle the `HDF5` version discrepancy?

**Comment by ThomasHoffmann77** [comment]
> @ThomasHoffmann77 any thoughts on how to handle the `HDF5` version discrepancy?
@verdurin  changed to 1.10.7

**Comment by boegel** [comment]
@boegelbot please test @ generoso

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
node3106.skitty.os - Linux RHEL 8.4, x86_64, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz (skylake_avx512), Python 3.6.8
See https://gist.github.com/c287687b07f0d1a24ba0be9e251715e8 for a full test report.

**Review by boegel — APPROVED** [review]
lgtm

**Comment by boegel** [comment]
Going in, thanks @ThomasHoffmann77!

**Pull request merged**
