### PR TITLE
{bio}[foss/2015b] KMC 2.3 (WIP)

### PR DESCRIPTION
**Pull request by nathanhaigh**
Easyconfig for KMC; a "Fast and frugal disk based k-mer counter.".

### CODE REVIEW

**Comment by nathanhaigh** [comment]
@boegel I could do with some guidance getting this one up-to-scratch. As it stands, this "works" but is using statically linked binaries and is using dependencies shipped as binaries with the tool itself.

- KMC's tarball comes with it's dependencies (`asmlib`, `libbzip2` and `zlib`) included as binaries (compiled for x86). I assume we really want these to be easyconfigs themselves and have them defined as dependencies?
- I think the `makefile` also needs modifying since it's using `-static` for building. There maybe other things which might need changing.

**Comment by boegel** [comment]
Jenkins: ok to test

**Comment by boegel** [comment]
@nathanhaigh: using EB-provided dependencies is preferably, yes, you'll have to dive in and see how difficult that's going to be; the build procedure may not be prepared for that

W.r.t. `-static`: there may be a good reason why this tools prefers being built statically?
Anyway, since you're likely going to patch the `Makefile` anyway, it doesn't hurt to flesh out the hardcoding of `-static` and putting that under control of EasyBuild.

**Comment by migueldiascosta** [comment]
@nathanhaigh, this PR is being closed for the following reason(s): no activity for > 1 year.
Please don't hesitate to reopen this PR or add a comment if you feel this contribution is still relevant.
For more information on our policy w.r.t. closing PRs, see https://easybuild.readthedocs.io/en/latest/Contributing.html#why-a-pull-request-may-be-closed-by-a-maintainer

**Pull request closed without merging**
