### PR TITLE
{lib}[fosscuda/2020b] TensorFlow v2.4.1 w/ Python 3.8.6

### PR DESCRIPTION
**Pull request by Flamefire**
(created using `eb --new-pr`)

- [x] Requires dependencies from #12148
- [x] Requires easybuilders/easybuild-easyblocks#2312

Similar to #11637. If that changes this must change too.

So this is testing support for CUDA 11 / CCC 8.0

### CODE REVIEW

**Review by boegel — CHANGES_REQUESTED** [review]
@Flamefire Can't test this due to two missing patches:

* `h5py-2.10.0_avoid-mpi-init.patch`
* `TensorFlow-2.4.1_include-ptx-code-for-latest-arch.patch`

**Comment by Flamefire** [comment]
Seems there is a bug in EB: `eb --update-pr 12149 --pr-commit-msg "Add patches" easybuild/easyconfigs/t/TensorFlow/h5py-2.10.0_avoid-mpi-init.patch`
-->
> == copying patch files to /tmp/easybuild-tmp/eb-uXME3O/git-working-dir5rFYdz/easybuild-easyconfigs...
> ERROR: No changed files found when comparing to current develop branch. Refused to make empty pull request.


Did that manually now

**Comment by boegel** [comment]
@Flamefire Please open an issue on that problem with `--update-pr` in https://github.com/easybuilders/easybuild-framework/issues

**Comment by boegel** [comment]
Test report by @boegel
**FAILED**
Build succeeded for 6 out of 7 (1 easyconfigs in total)
node3309.joltik.os - Linux centos linux 7.9.2009, x86_64, Intel(R) Xeon(R) Gold 6242 CPU @ 2.80GHz (cascadelake), Python 3.6.8
See https://gist.github.com/efa0dd146bfb5c781d19aa3758e8985c for a full test report.

**Comment by branfosj** [comment]
Test report by @branfosj
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
bear-pg0212u15b.bear.cluster - Linux centos linux 8.2.2004, x86_64, Intel(R) Xeon(R) CPU E5-2640 v4 @ 2.40GHz (broadwell), Python 3.6.8
See https://gist.github.com/a4244838403aca431f0c9a8c44dd0461 for a full test report.

**Comment by Flamefire** [comment]
Test report by @Flamefire
**FAILED**
Build succeeded for 15 out of 16 (1 easyconfigs in total)
taurusa4 - Linux centos linux 7.7.1908, x86_64, Intel(R) Xeon(R) CPU E5-2603 v4 @ 1.70GHz (broadwell), Python 2.7.5
See https://gist.github.com/5b7085e227b4e19c2d38ed7b86ff8172 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
node3302.joltik.os - Linux centos linux 7.9.2009, x86_64, Intel(R) Xeon(R) Gold 6242 CPU @ 2.80GHz (cascadelake), Python 3.6.8
See https://gist.github.com/ade4d2b9697da8725e427ab5fa845009 for a full test report.

**Comment by boegel** [comment]
@boegelbot please test @ generoso
CORE_CNT=16

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
node3570.doduo.os - Linux RHEL 8.2, x86_64, AMD EPYC 7552 48-Core Processor (zen2), Python 3.6.8
See https://gist.github.com/6cc08b542a996700bb77ff6b85c5e0a2 for a full test report.

**Review by boegel — APPROVED** [review]

**Comment by boegel** [comment]
Going in, thanks @Flamefire!

**Pull request merged**
