### PR TITLE
Create tmux-3.2-GCCcore-10.2.0.eb

### PR DESCRIPTION
**Pull request by Ghepardo**
New easyconfig for tmux 3.2.

### CODE REVIEW

**Comment by Micket** [comment]
Test report by @Micket
**SUCCESS**
Build succeeded for 2 out of 2 (1 easyconfigs in total)
vera-c1 - Linux centos linux 7.9.2009, x86_64, Intel Xeon Processor (Skylake), Python 2.7.5
See https://gist.github.com/a133f01aff080c95195844e42c346e73 for a full test report.

**Review by Micket — APPROVED** [review]
lgtm

It seems have have used all kinds of deps and builddeps throughout the different versions. Since you changed them, I assume you have looked over what is actually needed here?

**Review by Micket — CHANGES_REQUESTED** [review]
You need to open the PR against the develop branch

**Comment by Ghepardo** [comment]
@Micket Yes, I noticed that too.  For this one, I've gone strictly by the requirements on the tmux build instructions GitHub page.

**Comment by Micket** [comment]
New PR open

**Pull request closed without merging**
