### PR TITLE
{math,vis}[GCCcore/13.2.0] gnuplot v6.0.1, libcerf v2.4

### PR DESCRIPTION
**Pull request by PetrKralCZ**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by PetrKralCZ** [comment]
@boegelbot please test @ generoso

**Comment by PetrKralCZ** [comment]
@boegelbot please test @ generoso

**Comment by PetrKralCZ** [comment]
@boegelbot please test @ generoso

**Comment by boegel** [comment]
@PetrKralCZ Looks like there's a `-liconv` missing in the link command?

The configure output includes:
```
checking for library containing iconv_open... none required
```

I'm not sure why it makes that conclusion, it's obviously wrong since building fails with
```
/project/boegelbot/Rocky8/haswell/software/binutils/2.40-GCCcore-13.2.0/bin/ld: encoding.o: in function `init_special_chars':
encoding.c:(.text+0x22f): undefined reference to `libiconv_open'
```

Or maybe it's a problem with `iconv_open` vs `libiconv_open`, did those symbols/functions get renamed perhaps?

**Comment by boegel** [comment]
Overlaps with #20834, which has a fix for the linking issue, so closing this...

**Pull request closed without merging**
