### PR TITLE
{tools}[GCCcore/8.3.0] gettext v0.20.1

### PR DESCRIPTION
**Pull request by Micket**
(created using `eb --new-pr`)

depends on ~#8616~

### CODE REVIEW

**Comment by Micket** [comment]
Test report by @Micket
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
vera-c1 - Linux centos linux 7.6.1810, Intel Xeon Processor (Skylake), Python 2.7.5
See https://gist.github.com/3ffb383ecbb327e864370ceb616cc68f for a full test report.

**Comment by Micket** [comment]
Kicking travis

**Comment by Micket** [comment]
Travis kicked

**Comment by vanzod** [comment]
Test report by @vanzod
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
cermis - Linux debian 9.9, Intel(R) Xeon(R) CPU           X5670  @ 2.93GHz, Python 2.7.13
See https://gist.github.com/80af4ca13a38fc16aef5ce8f04ab7896 for a full test report.

**Comment by vanzod** [comment]
Going in, thanks @Micket!

**Pull request merged**
