### PR TITLE
consistently add maeparser + CoordgenLibs dependencies to OpenBabel v3.1.1 easyconfigs

### PR DESCRIPTION
**Pull request by boegel**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by boegel** [comment]
@boegelbot please test @ generoso

**Comment by boegel** [comment]
@boegelbot please test @ jsc-zen2

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 11 out of 11 (9 easyconfigs in total)
node3114.skitty.os - Linux RHEL 8.4, x86_64, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz (skylake_avx512), Python 3.6.8
See https://gist.github.com/9e23f9765bcf017fc4a8b5a5f5917fe1 for a full test report.

**Comment by boegel** [comment]
@boegelbot please test @ jsc-zen2
CORE_CNT=16

**Comment by verdurin** [comment]
Test report by @verdurin
**FAILED**
Build succeeded for 18 out of 38 (9 easyconfigs in total)
centos7.lan - Linux CentOS Linux 7.9.2009, x86_64, Intel Core Processor (Skylake, IBRS), Python 3.6.8
See https://gist.github.com/f4a0a0d64fd3d9c49afd86826c4f3e8c for a full test report.

**Comment by boegel** [comment]
@verdurin Test report failed with `No space left on device`

**Review by Micket — APPROVED** [review]
lgtm (another PR to strip out the likely misleading optional comments for Boost, which doesn't seem to be optional after all)

**Comment by Micket** [comment]
Going in, thanks @boegel!

**Pull request merged**
