### PR TITLE
switch to github.com source URL for MetaPhlAn

### PR DESCRIPTION
**Pull request by boegel**
(created using `eb --new-pr`)
fixes part of #10868

### CODE REVIEW

**Comment by boegel** [comment]
Different checksum, but no source file changes, so can retain both SHA256 checksums as valid:

```
$ diff -ru biobakery-metaphlan2-9760413b180f MetaPhlAn-2.7.8
Only in biobakery-metaphlan2-9760413b180f: .hg_archival.txt
Only in biobakery-metaphlan2-9760413b180f: .hgtags
```

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in this PR)
node2405.golett.os - Linux centos linux 7.8.2003, x86_64, Intel(R) Xeon(R) CPU E5-2680 v3 @ 2.50GHz (haswell), Python 2.7.5
See https://gist.github.com/61a038b710f6dea90aae8f9aa7f5bd97 for a full test report.

**Comment by boegel** [comment]
> > Different checksum, but no source file changes, so can retain both SHA256 checksums as valid:
> 
> Shouldn't both checksums be present in the easyconfigs then?

Yup, totally. I had it set up to do that at first, but overlooked retaining that when I had to add the patch, fixing that now...

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in this PR)
node2405.golett.os - Linux centos linux 7.8.2003, x86_64, Intel(R) Xeon(R) CPU E5-2680 v3 @ 2.50GHz (haswell), Python 2.7.5
See https://gist.github.com/b133e51fac1c3d74622c81deee215df4 for a full test report.

**Comment by zao** [comment]
Style check has opinions about your indentation.

**Comment by zao** [comment]
Going in, thanks @boegel!

**Pull request merged**
