### PR TITLE
{lib}[foss/2019b] igraph v0.8.0, python-igraph v0.8.0 w/ Python 2.7.16 + 3.7.4

### PR DESCRIPTION
**Pull request by lexming**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by lexming** [comment]
Test report by @lexming
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in this PR)
login2.cerberus.os - Linux centos linux 7.7.1908, Intel(R) Xeon(R) Gold 6126 CPU @ 2.60GHz, Python 2.7.5
See https://gist.github.com/1c6c09f53fb888e613bcdc3143a33bd9 for a full test report.

**Comment by migueldiascosta** [comment]
Test report by @migueldiascosta
**FAILED**
Build succeeded for 1 out of 2 (2 easyconfigs in this PR)
generoso - Linux centos linux 7.6.1810, Intel(R) Xeon(R) CPU E5-2660 v4 @ 2.00GHz, Python 3.6.8
See https://gist.github.com/c0c59e98dcc467336593fc7170be2003 for a full test report.

**Comment by migueldiascosta** [comment]
@lexming I suppose (b)yacc is installed on your test system (?)

**Comment by lexming** [comment]
@migueldiascosta `igraph` does not need `yacc`, it seems that the configure went wrong in that build. However, your build of `igraph` was successful, what failed is `python-igraph`. It seems that it is rebuilding a bundled `igraph`...

**Comment by lexming** [comment]
yes it comes with a bundled `igraph` in `builddir/vendor/igraph` /facepalm

**Comment by lexming** [comment]
@migueldiascosta it should be fixed with last commit :slightly_smiling_face:

**Comment by lexming** [comment]
Test report by @lexming
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in this PR)
login2.cerberus.os - Linux centos linux 7.7.1908, Intel(R) Xeon(R) Gold 6126 CPU @ 2.60GHz, Python 2.7.5
See https://gist.github.com/c01bd58134128f780417a87c9cd10a77 for a full test report.

**Comment by migueldiascosta** [comment]
Test report by @migueldiascosta
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in this PR)
generoso - Linux centos linux 7.6.1810, Intel(R) Xeon(R) CPU E5-2660 v4 @ 2.00GHz, Python 3.6.8
See https://gist.github.com/7db05f7b584733c5c566dbaae0569432 for a full test report.

**Comment by migueldiascosta** [comment]
Going in, thanks @lexming!

**Pull request merged**
