### PR TITLE
{lib}[GCC/11.2.0] FlexiBLAS v3.1.3

### PR DESCRIPTION
**Pull request by bartoldeman**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by bartoldeman** [comment]
Needs https://github.com/easybuilders/easybuild-easyblocks/pull/2694 since it does not list `imkl` as dependency.
Also depends on #15092 for updated OpenBLAS.

**Comment by bartoldeman** [comment]
please test @generoso EB_ARGS="--include-easyblocks-from-pr=2694"

**Comment by bartoldeman** [comment]
@boegelbot `please test @generoso EB_ARGS=--include-easyblocks-from-pr=2684`

**Comment by bartoldeman** [comment]
@boegelbot please test @ generoso EB_ARGS=--include-easyblocks-from-pr=2694

**Comment by bartoldeman** [comment]
Test report by @bartoldeman
Using easyblocks from PR(s) https://github.com/easybuilders/easybuild-easyblocks/pull/2694
**FAILED**
Build succeeded for 0 out of 1 (1 easyconfigs in total)
build-node.computecanada.ca - Linux CentOS Linux 7.9.2009, x86_64, Intel Xeon Processor (Skylake, IBRS), Python 3.7.7
See https://gist.github.com/55c4f8a4bd42e60e7253b8a6c3a1455e for a full test report.

**Comment by bartoldeman** [comment]
Test report by @bartoldeman
Using easyblocks from PR(s) https://github.com/easybuilders/easybuild-easyblocks/pull/2694
**SUCCESS**
Build succeeded for 2 out of 2 (1 easyconfigs in total)
build-node.computecanada.ca - Linux CentOS Linux 7.9.2009, x86_64, Intel Xeon Processor (Skylake, IBRS), Python 3.7.7
See https://gist.github.com/a019170e1f9b74852250a35bc3378e74 for a full test report.

**Comment by bartoldeman** [comment]
@boegelbot please test @ generoso

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 2 out of 2 (1 easyconfigs in total)
node3112.skitty.os - Linux CentOS Linux 7.9.2009, x86_64, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz, Python 3.6.8
See https://gist.github.com/bb5e0f3bd4eddf040e394cf8d289d040 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 2 out of 2 (1 easyconfigs in total)
node3575.doduo.os - Linux RHEL 8.4, x86_64, AMD EPYC 7552 48-Core Processor (zen2), Python 3.6.8
See https://gist.github.com/e8d07542ce2e9405d9df3419e383fb8d for a full test report.

**Comment by boegel** [comment]
Going in, thanks @bartoldeman!

**Pull request merged**
