### PR TITLE
{lib}[foss/2020b] dm-reverb v0.2.0 w/ Python 3.8.6

### PR DESCRIPTION
**Pull request by lexming**
(created using `eb --new-pr`)

Depends on https://github.com/easybuilders/easybuild-easyblocks/pull/2413

### CODE REVIEW

**Comment by lexming** [comment]
Test report by @lexming
Using easyblocks from PR(s) https://github.com/easybuilders/easybuild-easyblocks/pull/2413
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
node381.hydra.os - Linux centos linux 7.9.2009, x86_64, Intel(R) Xeon(R) Gold 6148 CPU @ 2.40GHz, Python 2.7.5
See https://gist.github.com/ede9ab6b3fee57d4f8d9ed55a7db0b50 for a full test report.

**Comment by Micket** [comment]
@boegelbot please test @ generoso
EB_ARGS="--include-easyblocks-from-pr=2413"

**Review by Micket — DISMISSED** [review]
lgtm

**Comment by Micket** [comment]
Well that wasn't what i was hoping to see
```
ERROR: /tmp/boegelbot/dmreverb/0.2.0/foss-2020b/easybuild_obj/0da5ac30722e994767df782a97d19dd3/external/com_google_protobuf/BUILD:53:11: @com_google_protobuf//:protobuf_lite: missing input file 'external/com_google_protobuf/protobuf/lib/libprotobuf-lite.so', owner: '@com_google_protobuf//:protobuf/lib/libprotobuf-lite.so'
```
any ideas?

**Comment by lexming** [comment]
@Micket that should be a link to `$EBROOTPROTOBUF/lib/libprotobuf-lite.so`, is that file missing in the test system?

**Comment by branfosj** [comment]
I tested and my first attempt failed to build with the same issue as seen on generoso. I rebuilt protobuf and then the build of dm-reverb succeeds. The difference between the two protobuf builds was the new install includes a `lib -> lib64` symlink - so https://github.com/easybuilders/easybuild-framework/pull/3580

**Comment by lexming** [comment]
@branfosj nice, that confirms my suspicion. Thanks for the feedback!

**Comment by Micket** [comment]
Should this then have a dependency on `protobuf-2.5.0-GCCcore-10.2.0.eb` (or protobuf-python)?

**Comment by Micket** [comment]
@boegelbot please test @ generoso
EB_ARGS="--include-easyblocks-from-pr=2413 protobuf-2.5.0-GCCcore-10.2.0.eb dm-reverb-0.2.0-foss-2020b.eb"

**Comment by Micket** [comment]
@boegelbot please test @ generoso
EB_ARGS="--include-easyblocks-from-pr=2413 protobuf-3.14.0-GCCcore-10.2.0.eb dm-reverb-0.2.0-foss-2020b.eb"

**Review by Micket — APPROVED** [review]
lgtm

**Comment by Micket** [comment]
Going in, thanks @lexming!

**Pull request merged**
