### PR TITLE
{chem}[GCC/8.3.0] DFT-D3 v3.2.0

### PR DESCRIPTION
**Pull request by lexming**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by lexming** [comment]
Test report by @lexming
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
node150.hydra.os - Linux centos linux 7.7.1908, Intel(R) Xeon(R) CPU E5-2680 v2 @ 2.80GHz, Python 2.7.5
See https://gist.github.com/b12487b13d7a1c7fe71cf8811eae2467 for a full test report.

**Comment by lexming** [comment]
Test report by @lexming
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
node150.hydra.os - Linux centos linux 7.7.1908, Intel(R) Xeon(R) CPU E5-2680 v2 @ 2.80GHz, Python 2.7.5
See https://gist.github.com/dc28a32c518e59c8b6b380223ea40ccb for a full test report.

**Comment by lexming** [comment]
Switching to `GCC/8.3.0` as DFT-D3 does not use BLAS/LAPACK or MPI.

**Comment by lexming** [comment]
Test report by @lexming
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
login2.cerberus.os - Linux centos linux 7.7.1908, Intel(R) Xeon(R) Gold 6126 CPU @ 2.60GHz, Python 2.7.5
See https://gist.github.com/5ca4d8ec5ff4ea5ee7783d8313782eff for a full test report.

**Comment by Micket** [comment]
Test report by @Micket
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
vera-c1 - Linux centos linux 7.7.1908, Intel Xeon Processor (Skylake), Python 2.7.5
See https://gist.github.com/409cd8681f0b32ec2689ba3096253a73 for a full test report.

**Comment by Micket** [comment]
Test report by @Micket
**FAILED**
Build succeeded for 0 out of 1 (1 easyconfigs in this PR)
hebbe-c1 - Linux centos linux 7.7.1908, Intel Core Processor (Haswell, no TSX), Python 2.7.5
See https://gist.github.com/322be6d614471302ef4f32f20e2940c8 for a full test report.

**Comment by Micket** [comment]
Huh, I'm a bit at a loss here, not sure why one of my builds failed completely here
```
gfortran -static dftd3.o copyc6.o   -lm -lpthread -o dftd3
/apps/Hebbe7/software/Compiler/GCCcore/8.3.0/binutils/2.32/bin/ld.gold: error: cannot find -lm
...
```
:(

**Comment by lexming** [comment]
@Micket can you check if that system has `glibc-static` installed?

**Comment by Micket** [comment]
It didn't.

**Comment by Micket** [comment]
Test report by @Micket
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
hebbe-c1 - Linux centos linux 7.7.1908, Intel Core Processor (Haswell, no TSX), Python 2.7.5
See https://gist.github.com/aa81d58eddafe275401abed304b7f2ba for a full test report.

**Comment by Micket** [comment]
Going in, thanks @lexming!

**Pull request merged**
