### PR TITLE
{tools}[intel/2015G] HPL v2.2

### PR DESCRIPTION
**Pull request by JackPerdue**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by JackPerdue** [comment]
I guess I'm just tossing this out as example of where I want to go.

1) GCCcore version(suffix) needs binutils ver else I can't both GCCcore/4.9.4-2.25 and GCCcore/4.9.4-2.26 coexit (name collision)
2) I promoted GCC from Bundle to Toolchain so I can use it as a base toolchain with --minimal-toolchains (using GCCcore required adding binutils as a build dep to everything)
3) (tried to) explicitly list the easyblock used in every easyconfig
4) (tried to) make the easyconfigs mostly pep8 compliant

Anyway... another iteration.  Thought best to use the super fantastic --new-pr thingie to dump them here for reference

Thoughts?  Criticisms?  

NOTE: I'm still testing, but my use of binutils 2.25 with this toolchain may be the root of my problems buiilding Python on RHEL 7.3 (it now ships with 2251 [with RH patches]).   I had naming collisions with GCCcore.  If this will work, I think its much cleaner.

**Comment by JackPerdue** [comment]
Oh yeah... I added a lot of osdependencies to make it clearer during each step.  Kenneth suggested adding a check for gcc/gcc-devel/glibc-devel at EB install time but I don't think that's enough... I could easily install EB and then uninstall those packages and run into confusing issues when I actually go to build the packages (the first binutils) that needs them.   So I think the osdependencies should live in the easyconfigs they are need in and not assumed/presumed to be perpetual from EB install time.

**Comment by JackPerdue** [comment]
Another thing is migrating to the system zlib.  If EB is going to (quite rightfully) rely upon the distro OpenSSL then it should rely upon the the zlib it depends on.

**Comment by JackPerdue** [comment]
Additional note:  This is primary as reference as a way of doing things.  Since I don't really think its up to par yet (still have some things to clean up), I'm closing as a PR.   But I wanted to get some feedback on the above.

**Comment by JackPerdue** [comment]
Alright.... at the end of the day I tried to build a Python using this (binutils-2.25) and a intel/2015H I put together using binutils-2.26... still ended up with fails on building Python.

Beyond that, I obviously cheated by hacking iccifort.py.  How would I can I (or can I? write in EB Python:

if HMNS then
  SUBTOOLCHAIN = GCCcore.NAME
else
  SUBTOOLCHAIN = GccToolchain.NAME
endif

I understand the need to use core for HMNS but it precludes reusing modules buit with GCC for both iompi and iimpi when using a flat MNS   Since we are still flat, we'd like to do that (if viable).

**Comment by boegel** [comment]
@JackPerdue This is getting quite dated now...

If this just meant to share these easyconfigs without the intention to actually get them merged, please close this PR?

**Pull request closed without merging**
