### PR TITLE
{lib,vis}[intel/2017a] libepoxy v1.4.3, Mesa v17.1.6

### PR DESCRIPTION
**Pull request by boegel**
(created using `eb --new-pr`)
requires ~~#5034~~

### CODE REVIEW

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 4 out of 4 (4 easyconfigs in this PR)
node2066.delcatty.os - Linux centos linux 7.3.1611, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.7.5
See https://gist.github.com/cdf55b952f664f9df30cdf3ee0d8c562 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 4 out of 4 (4 easyconfigs in this PR)
node2572.golett.os - Linux centos linux 7.3.1611, Intel(R) Xeon(R) CPU E5-2680 v3 @ 2.50GHz, Python 2.7.5
See https://gist.github.com/671341cbd9b22477dd045e9a119bd682 for a full test report.

**Comment by verdurin** [comment]
@boegel Build failure:
```
checking for EGL... no
configure: error: Package requirements (egl) were not met:

No package 'egl' found

Consider adjusting the PKG_CONFIG_PATH environment variable if you
installed software in a non-standard prefix.

Alternatively, you may set the environment variables EGL_CFLAGS
and EGL_LIBS to avoid the need to call pkg-config.
See the pkg-config man page for more details.
 (at easybuild/tools/run.py:444 in parse_cmd_output)
```

**Comment by boegel** [comment]
No longer relevant, so closing this...

**Pull request closed without merging**
