### PR TITLE
{math}[goolfc/2017b] Keras v2.1.5

### PR DESCRIPTION
**Pull request by jhein32**
Fileset (incl h5py and HDF5 as well as PyYAM) to install Keras 2.1.5
with a GPU-Tensorflow 2.1.5.  This Tensorflow version is part of EasyBuild for some time.

### CODE REVIEW

**Comment by jhein32** [comment]
@boegel Kenneth, there is one failure here, which going by the error is quite likely an issue with the particular test hardware - the other checks passed.   Is there a way to manually restart the test, to see whether it goes through the second time?

Also, please let me know whether you think this is interesting for EB - it is a bit an odd-ball.  The TF is a bit old, but I needed something quickly for a user wanting a GPU Keras and a TF 1.5. backend was good for them.

**Comment by boegel** [comment]
@jhein32 Indeed looks like a fluke for that particular test, I've re-started it.

For future occurrences: feel free to close & re-open the PR, which should make Travis retrigger (all) tests.

**Comment by boegel** [comment]
lgtm, other than the indeed old TF version, why not update to 1.7 while you're at it (cfr. #6098)?
Using an old version of TF with the latest Keras is a bit of shame, no?

I can't do a test install of this (no GPU nodes available to me), maybe @akesandgren can take care of that?

**Comment by jhein32** [comment]
The TF 1.7 is a CPU version as far as I can make out.  The TF 1.5 I am using is the most modern CUDA TF in master.  There is a TF 1.6 with CUDA in the dev-branch.  Once this released I could easily build a Keras based on this one.  Any ETA for the next EB release?

**Comment by boegel** [comment]
@jhein32 Indeed, but it shouldn't be too much effort to update the TF 1.5 with `goolfc` to TF 1.7?

ETA for EB v3.6.0 is mid April.

**Comment by akesandgren** [comment]
I'm just about to produce Keras latest with goolfc/2018a using CUDA 9.1, and all the latest deep learning tools it needs. So i'll skip testing this.

**Comment by jhein32** [comment]
@akesandgren Sounds reasonable to me.  Please give me a heads up when you do the PR.

@boegel Do we close this or keep as a reminder?

**Comment by akesandgren** [comment]
@jhein32 https://github.com/easybuilders/easybuild-easyconfigs/pull/6133
Needs https://github.com/easybuilders/easybuild-easyconfigs/pull/6129 (already in develop) and Bazel 0.11.1-GCCcore-6.4.0 from develop.

**Comment by jhein32** [comment]
Do we want to progress this or do we abandon this?

**Comment by boegel** [comment]
@jhein32 #6133 is a better/more recent version of this imho, so I'm OK if we abandon this (but I'll leave it up to you to close the PR)

**Comment by jhein32** [comment]
Outdated

**Pull request closed without merging**
