### PR TITLE
{lang}[foss/2018b,intel/2018b] Python v3.7.0

### PR DESCRIPTION
**Pull request by boegel**
(created using `eb --new-pr`)
depends on ~~#6473~~ (ncurses), ~~#6474~~ (bzip2), ~~#6479~~ (GMP, SQLite, ...), ~~#6409~~ (`intel/2018b`), ~~#6424~~ (`foss/2018b`)

### CODE REVIEW

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in this PR)
node3159.skitty.os - Linux centos linux 7.4.1708, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz, Python 2.7.5
See https://gist.github.com/f5abed935161871db0283443c2cf9e46 for a full test report.

**Comment by vanzod** [comment]
Test report by @vanzod
**FAILED**
Build succeeded for 1 out of 3 (2 easyconfigs in this PR)
cermis - Linux debian 9.4, Intel(R) Xeon(R) CPU           E5620  @ 2.40GHz, Python 2.7.13
See https://gist.github.com/a81a1dde7744b49ee141cae610b105db for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in this PR)
node2054.delcatty.os - Linux centos linux 7.4.1708, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.7.5
See https://gist.github.com/6a4cc2b65869403df20eb6d5148b73d2 for a full test report.

**Comment by boegel** [comment]
@vanzod Actual problem isn't caught in the partial log included in the test report, please provide a full (debug) log?

**Comment by wpoely86** [comment]
Test report by @wpoely86
**SUCCESS**
Build succeeded for 39 out of 39 (2 easyconfigs in this PR)
nic92 - Linux centos linux 7.5.1804, Intel(R) Xeon(R) Gold 6148 CPU @ 2.40GHz, Python 2.7.5
See https://gist.github.com/1a5cde8bfdcc78b05b88dd9b683f7ad9 for a full test report.

**Comment by migueldiascosta** [comment]
Test report by @migueldiascosta
**FAILED**
Build succeeded for 0 out of 2 (2 easyconfigs in this PR)
grc-cluster1 - Linux centos 6.9, Intel(R) Xeon(R) CPU E5-2640 0 @ 2.50GHz, Python 2.7.14
See https://gist.github.com/e750ff3ea615f772460aca2db491abe3 for a full test report.

**Comment by migueldiascosta** [comment]
CentOS 6.x system OpenSSL is too old for python 3.7.0:
```
Could not build the ssl module!
Python requires an OpenSSL 1.0.2 or 1.1 compatible libssl with X509_VERIFY_PARAM_set1_host().
```
which then leads to https download errors (see test report)

Maybe update the OpenSSL dependency comment so that people are aware?

**Comment by boegel** [comment]
@migueldiascosta How specifically would you update that comment?

Also, I'm not sure if that's going to make much of a difference, do you think people will look at comments in the easyconfig when try run into a build failure like that for Python 3.7.0?

**Comment by vanzod** [comment]
@boegel Here is the full debug log: https://gist.github.com/e1a7f1c5c417d559764fdae547ad3a31

It seems a problem with related to building `_ctypes` but I cannot see where and how.

**Comment by boegel** [comment]
@vanzod I think this is the culprit: `INFO: Could not locate ffi libs and/or headers`, see also https://bugs.python.org/issue31710.

So maybe including `$EBROOTLIBFFI/include` to `$CPPFLAGS` fixes the issue? Can you test that?

(the one about `tcl/tk` is harmless I think, I see that one too on our systems, that's probably because we deliberately don't provide `Tk` as a dependency)

**Comment by vanzod** [comment]
@boegel After rebuilding `libffi` as in #6565 and adding

```preconfigopts = 'env CPPFLAGS=-I${EBROOTLIBFFI}/include &&'```

The build terminates successfully.

**Comment by boegel** [comment]
@vanzod Extending `$CPPFLAGS` shouldn't be required if the `libffi` `include` directory is at a standard location, that's done automatically by EasyBuild when setting up the build environment for all listed dependencies.

**Comment by boegel** [comment]
Test report by @boegel
**FAILED**
Build succeeded for 0 out of 2 (2 easyconfigs in this PR)
node3158.skitty.os - Linux centos linux 7.4.1708, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz, Python 2.7.5
See https://gist.github.com/d62c75b9d511bcec62b24b1bfebfde91 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**FAILED**
Build succeeded for 0 out of 2 (2 easyconfigs in this PR)
node2403.golett.os - Linux centos linux 7.4.1708, Intel(R) Xeon(R) CPU E5-2680 v3 @ 2.50GHz, Python 2.7.5
See https://gist.github.com/ee132d0476495fcced3e6246b207a59e for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**FAILED**
Build succeeded for 0 out of 2 (2 easyconfigs in this PR)
node2001.delcatty.os - Linux centos linux 7.4.1708, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.7.5
See https://gist.github.com/8585a9db900be002c84ac3fa30df507b for a full test report.

**Comment by verdurin** [comment]
Test report by @verdurin
**FAILED**
Build succeeded for 13 out of 14 (1 easyconfigs in this PR)
easybuild.novalocal - Linux centos linux 7.5.1804, Intel Xeon E312xx (Sandy Bridge), Python 2.7.5
See https://gist.github.com/92ce12f1af6c52e11158776f1ed0dc89 for a full test report.

**Comment by boegel** [comment]
After noticing that there was an update for `pandas` (0.23.2) which claimed to be the first version to support Python 3.7.0, I figured we should update it...

As it turns out, this makes the installation of `pandas` fail, I didn't see that problem with pandas 0.23.1, which is quite weird.
I reported the problem upstream: https://github.com/pandas-dev/pandas/issues/21785

**Comment by verdurin** [comment]
Test report by @verdurin
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
easybuild.novalocal - Linux centos linux 7.5.1804, Intel Xeon E312xx (Sandy Bridge), Python 2.7.5
See https://gist.github.com/0b02b80294f22e853bb3020ff22a9fdd for a full test report.

**Comment by migueldiascosta** [comment]
@boegel w.r.t. to the OpenSSL comment, something like "Python 3.7 requires OpenSSL >= 1.0.2, uncomment dependency if OS version is too old"? with #6567, it works for me

(regarding people not reading the comment anyway, would it be feasible to enhance `osdependencies` to check for a minimum version? Then at least it would fail immediately with a meaningful message...)

in any case, I don't think any of this should block merging this PR

**Comment by Micket** [comment]
My plan was to do with this PR as i did with p27 in #6537. Should I wait for this to be accepted, or just submit something now and then rebase? (or should I not bother at all in case noone is interested in accepting #6537 )

**Comment by boegel** [comment]
@Micket Let's see if we can get #6537 merged first

**Comment by bartoldeman** [comment]
Test report by @bartoldeman
**FAILED**
Build succeeded for 7 out of 19 (2 easyconfigs in this PR)
aw-4r14-n02 - Linux centos 6.6, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.6.6
See https://gist.github.com/df429d0055bc73d861382311c44d1a9f for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in this PR)
node2404.golett.os - Linux centos linux 7.4.1708, Intel(R) Xeon(R) CPU E5-2680 v3 @ 2.50GHz, Python 2.7.5
See https://gist.github.com/0b9d5a5aef8020d37a165ecef7a51271 for a full test report.

**Comment by bartoldeman** [comment]
Test report by @bartoldeman
**FAILED**
Build succeeded for 0 out of 1 (1 easyconfigs in this PR)
aw-4r14-n02 - Linux centos 6.6, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.6.6
See https://gist.github.com/f709bc7fabe8b1a07463a8f8e496be66 for a full test report.

**Comment by bartoldeman** [comment]
Test report by @bartoldeman
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
aw-4r14-n02 - Linux centos 6.6, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.6.6
See https://gist.github.com/72c9ea15b193794cf5d6b7fad0a3dd7e for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 5 out of 5 (2 easyconfigs in this PR)
node3119.skitty.os - Linux centos linux 7.4.1708, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz, Python 2.7.5
See https://gist.github.com/c0916f9f7a02a6180d7096cde55029fa for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in this PR)
node2005.delcatty.os - Linux centos linux 7.4.1708, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.7.5
See https://gist.github.com/f85301866b427265c675b56fdb29cd9e for a full test report.

**Comment by vanzod** [comment]
Test report by @vanzod
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in this PR)
cermis - Linux debian 9.4, Intel(R) Xeon(R) CPU           E5620  @ 2.40GHz, Python 2.7.13
See https://gist.github.com/7bd94c161cc2bac20ac360aaf3480e9c for a full test report.

**Comment by bartoldeman** [comment]
Ok. Looks good to me. Plenty of test reports, thanks everyone. @boegel proposed merging, I will do it.

**Pull request merged**
