### PR TITLE
update easyconfigs to use `SYSTEM` template constant instead of `True` in dependencies

### PR DESCRIPTION
**Pull request by jfgrimm**
see #16330 and #16384

for reference, the substitution pattern used: `sed -i "s|', True)|', SYSTEM)|g"`
haven't spotted any cases where this caused an issue

### CODE REVIEW

**Review by casparvl — APPROVED** [review]
It's a ton of EasyConfigs, but I've scrolled through the changes and haven't spotted anything unintended. It's an approval from me, but since this affects so many EasyConfigs, I'll ask at least one other maintainer to also look at this :)

**Review by boegel — APPROVED** [review]
lgtm after visual review, test suite is happy, so no reason to hold this back...

Thanks for the effort on this @jfgrimm!

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 14 out of 14 (14 easyconfigs in total)
node3102.skitty.os - Linux RHEL 8.4, x86_64, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz (skylake_avx512), Python 3.6.8
See https://gist.github.com/1574ae2ac46f61d56b40693c2b9761dd for a full test report.

**Comment by boegel** [comment]
Going in, thanks @jfgrimm!

**Pull request merged**
