### PR TITLE
remove superflous -DCMAKE_BUILD_TYPE=Release, use of 'build_type = Release', or enabling separate_build_dir from easyconfigs using CMakeMake easyblock

### PR DESCRIPTION
**Pull request by Flamefire**
This is the default for a few releases now and may lead to confusion or bugs.

Examples:
- `RELEASE` used instead of `Release` -> confusing
- `ON` used in 1 place -> bug

Bonus: CMakeMake reacts on toolchainopts.debug to set the build type correctly which works now after this change

Dependend on:

- [x] https://github.com/easybuilders/easybuild-easyconfigs/pull/13613
- [x] https://github.com/easybuilders/easybuild-easyconfigs/pull/13614
- [x] https://github.com/easybuilders/easybuild-easyconfigs/pull/13615
- [x] https://github.com/easybuilders/easybuild-easyconfigs/pull/13616
- [x] https://github.com/easybuilders/easybuild-easyconfigs/pull/13617
- [x] https://github.com/easybuilders/easybuild-easyconfigs/pull/13619
- [x] https://github.com/easybuilders/easybuild-easyconfigs/pull/13620
- [x] https://github.com/easybuilders/easybuild-easyconfigs/pull/13621
- [x] https://github.com/easybuilders/easybuild-easyconfigs/pull/13623
- [x] https://github.com/easybuilders/easybuild-easyconfigs/pull/13624
- [x] https://github.com/easybuilders/easybuild-easyconfigs/pull/13456
- [x] https://github.com/easybuilders/easybuild-easyconfigs/pull/13434

### CODE REVIEW

**Comment by Flamefire** [comment]
Test report by @Flamefire
**FAILED**
Build succeeded for 71 out of 80 (75 easyconfigs in total)
taurusi5525.taurus.hrsk.tu-dresden.de - Linux RHEL 7.9, x86_64, Intel(R) Xeon(R) CPU E5-2680 v3 @ 2.50GHz (haswell), Python 2.7.5
See https://gist.github.com/704edb5c88d5b42084535aac5a222f6c for a full test report.

**Comment by Flamefire** [comment]
Test report by @Flamefire
**SUCCESS**
Build succeeded for 75 out of 75 (75 easyconfigs in total)
taurusi5027.taurus.hrsk.tu-dresden.de - Linux RHEL 7.9, x86_64, Intel(R) Xeon(R) CPU E5-2680 v3 @ 2.50GHz (haswell), Python 2.7.5
See https://gist.github.com/78d27869af1428bc1412cbb637ccfde8 for a full test report.

**Comment by Flamefire** [comment]
@Micket Rebuild the whole lot that I still can build (i.e. Intel 2017 doesn't work due to licenses)
As you can see from the commits it also reenables building certain older ECs that are currently broken, at least in some environments.

Would be great if this could be merged soon so future ECs can use the new style/don't C&P old stuff.

**Comment by Micket** [comment]
This is all caught up now, so a rebase is the next step?

**Comment by Flamefire** [comment]
Test report by @Flamefire
**FAILED**
Build succeeded for 87 out of 90 (54 easyconfigs in total)
taurusi6276.taurus.hrsk.tu-dresden.de - Linux RHEL 7.9, x86_64, Intel(R) Xeon(R) CPU E5-2680 v3 @ 2.50GHz (haswell), Python 2.7.5
See https://gist.github.com/037a07ddfd6fcee3270b2da9b4029bb5 for a full test report.

**Comment by boegel** [comment]
@Flamefire Do you think it makes sense to add a check in the easyconfigs test suite to avoid that new easyconfigs re-introduce the use of `-DCMAKE_BUILD_TYPE=Release`?

This is still a huge PR to get merged btw, but we'll try...

**Comment by Flamefire** [comment]
I'll add a CI check soonish.

And yeah, it's big: 64 ECs :/ But the changes are trivial after fleshing out the other PRs.

**Comment by Flamefire** [comment]
Test report by @Flamefire
**FAILED**
Build succeeded for 53 out of 54 (54 easyconfigs in total)
taurusi5570.taurus.hrsk.tu-dresden.de - Linux RHEL 7.9, x86_64, Intel(R) Xeon(R) CPU E5-2680 v3 @ 2.50GHz (haswell), Python 2.7.5
See https://gist.github.com/1e4b408fb98f93c81dbb48dc4398a42b for a full test report.

**Comment by Flamefire** [comment]
CI check added by https://github.com/easybuilders/easybuild-easyconfigs/pull/14008

**Comment by Flamefire** [comment]
Racon failure fixed with https://github.com/easybuilders/easybuild-easyconfigs/pull/14010

**Comment by Flamefire** [comment]
Rebased to resolve conflicts and remove the changes done in the other PRs.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 12 out of 12 (12 easyconfigs in total)
node2678.swalot.os - Linux RHEL 8.4, x86_64, Intel(R) Xeon(R) CPU E5-2660 v3 @ 2.60GHz (haswell), Python 3.6.8
See https://gist.github.com/d768fb474640994004a7f2b44e1fa119 for a full test report.

**Review by boegel — APPROVED** [review]
I gave this a thorough review, and submitted a test report for a bunch of recent easyconfigs touched in this PR, looks good to go, thanks for your efforts here @Flamefire!

As next step, we should add a check to the easyconfigs test suite to avoid that easyconfigs being contributed still specify `-DCMAKE_BUILD_TYPE` in `configopts`, or set `build_type` to `Release`, or enable `separate_build_dir`...

**Comment by boegel** [comment]
Going in, thanks @Flamefire!

**Comment by Flamefire** [comment]
> [boegel](https://github.com/boegel) changed the title Remove superflous -DCMAKE_BUILD_TYPE remove superflous -DCMAKE_BUILD_TYPE=Release, use of 'build_type = Release', or enabling separate_build_dir from easyconfigs using CMakeMake easyblock

I usually use plain sentences to describe changes which yields the PR title, i.e. it starts with uppercase. What is the reason for the change to lowercase and do you want that for future PRs?

**Comment by boegel** [comment]
@Flamefire It's mainly because the PR titles go straight into the release notes, where they're in a list, see https://docs.easybuild.io/en/latest/Release_notes.html

I often reword PR titles if I feel they're not clear enough, or to make PRs easier to find, to avoid having to do that when composing the release notes...

**Pull request merged**
