### PR TITLE
{devel}[GCCcore/13.2.0] pydantic v2.6.4, Rust v1.76.0, maturin v1.5.0, ... w/ Rust 1.76.0

### PR DESCRIPTION
**Pull request by pavelToman**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by pavelToman** [comment]
@boegelbot please test @ generoso

**Review by Micket — APPROVED** [review]
lgtm

**Comment by Micket** [comment]
Test report by @Micket
**SUCCESS**
Build succeeded for 4 out of 4 (4 easyconfigs in total)
vera-skylake-build - Linux Rocky Linux 8.9, x86_64, Intel Xeon Processor (Skylake, IBRS, no TSX), Python 3.6.8
See https://gist.github.com/Micket/2b8e8d4380ad0f916292e9cf9f1ba38d for a full test report.

**Comment by Micket** [comment]
@boegelbot please test @ jsc-zen3
CORE_CNT=16

**Comment by casparvl** [comment]
Test report by @casparvl
**SUCCESS**
Build succeeded for 4 out of 4 (4 easyconfigs in total)
tcn1.local.snellius.surf.nl - Linux RHEL 8.6, x86_64, AMD EPYC 7H12 64-Core Processor, Python 3.6.8
See https://gist.github.com/casparvl/48c7d83d594ed26e5dfb6d4394df8e49 for a full test report.

**Comment by casparvl** [comment]
Going in, thanks @pavelToman!

**Pull request merged**
