### PR TITLE
stick to PyQt5 5.9.2 as dep for AFNI 18.1.09

### PR DESCRIPTION
**Pull request by boegel**
fixes a conflict between PyQt5 versions in the `2018a` generation of easyconfigs, introduced via #6266, which is caught when the easyconfig tests are run on a PR:

```
FAIL: test_dep_versions_per_toolchain_generation (test.easyconfigs.easyconfigs.EasyConfigTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/easybuilders/easybuild-easyconfigs/test/easyconfigs/easyconfigs.py", line 299, in test_dep_versions_per_toolchain_generation
    self.assertFalse(multi_dep_vars, error_msg)
AssertionError: No multi-variant deps found for '^.*-(?P<tc_gen>201[89][ab]).*\.eb$' easyconfigs:

found 2 variants of 'PyQt5' dependency in easyconfigs using '2018a' toolchain generation
* version: 5.10.1; versionsuffix: -Python-3.6.4 as dep for set(['AFNI-18.1.09-intel-2018a-Python-3.6.4.eb'])
* version: 5.9.2; versionsuffix: -Python-3.6.4 as dep for set(['Spyder-3.3.1-foss-2018a-Python-3.6.4.eb'])


----------------------------------------------------------------------
```

### CODE REVIEW

**Comment by vanzod** [comment]
Test report by @vanzod
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in this PR)
cermis - Linux debian 9.5, Intel(R) Xeon(R) CPU           E5620  @ 2.40GHz, Python 2.7.13
See https://gist.github.com/09ac893fd3e9ca3e22e7cf3617b47092 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in this PR)
node3102.skitty.os - Linux centos linux 7.5.1804, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz, Python 2.7.5
See https://gist.github.com/ace8e6170d8fae008ed990c8313e6aa5 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in this PR)
node2082.delcatty.os - Linux centos linux 7.5.1804, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.7.5
See https://gist.github.com/929ea4b03b715a1274fff5f34d75ae11 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in this PR)
node2601.swalot.os - Linux centos linux 7.5.1804, Intel(R) Xeon(R) CPU E5-2660 v3 @ 2.60GHz, Python 2.7.5
See https://gist.github.com/fdef22b90b2fa4a8516538d097cc2a73 for a full test report.

**Pull request merged**
