### PR TITLE
{chem}[foss/2021a] NAMD v2.14 w/ CUDA v11.3.1

### PR DESCRIPTION
**Pull request by smoors**
(created using `eb --new-pr`)

depends on easyblock PR:
- [x] https://github.com/easybuilders/easybuild-easyblocks/pull/2654

### CODE REVIEW

**Comment by smoors** [comment]
@boegelbot: please test @ generoso EB_ARGS="--include-easyblocks-from-pr 2654"

**Comment by smoors** [comment]
Test report by @smoors
Using easyblocks from PR(s) https://github.com/easybuilders/easybuild-easyblocks/pull/2654
**FAILED**
Build succeeded for 1 out of 2 (1 easyconfigs in total)
node305.hydra.os - Linux centos linux 7.9.2009, x86_64, Intel(R) Xeon(R) Gold 6148 CPU @ 2.40GHz (skylake_avx512), Python 2.7.5
See https://gist.github.com/62e2446a4f3935cd2bb2fa8945c01c2a for a full test report.

**Comment by smoors** [comment]
Test report by @smoors
Using easyblocks from PR(s) https://github.com/easybuilders/easybuild-easyblocks/pull/2654
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
node250.hydra.os - Linux centos linux 7.9.2009, x86_64, Intel(R) Xeon(R) CPU E5-2650 v4 @ 2.20GHz (broadwell), 1 x NVIDIA Tesla P100-PCIE-16GB, 470.82.01, Python 2.7.5
See https://gist.github.com/599f44998a31060721996f823b6449df for a full test report.

**Comment by smoors** [comment]
boegelbot failed because you need a GPU

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
node3302.joltik.os - Linux RHEL 8.4, x86_64, Intel(R) Xeon(R) Gold 6242 CPU @ 2.80GHz (cascadelake), 1 x NVIDIA Tesla V100-SXM2-32GB, 520.61.05, Python 3.6.8
See https://gist.github.com/199958ec4ef021cd510971794ba052b3 for a full test report.

**Review by boegel — APPROVED** [review]
lgtm

**Comment by boegel** [comment]
Going in, thanks @smoors!

**Pull request merged**
