### PR TITLE
{bio}[foss/2023a] CellRank v2.0.2

### PR DESCRIPTION
**Pull request by pavelToman**
(created using `eb --new-pr`)

- [x] depends on #20002
- [x] waiting for #20148

### CODE REVIEW

**Comment by pavelToman** [comment]
@boegelbot please test @ generoso

**Comment by pavelToman** [comment]
@boegelbot please test @ jsc-zen3

**Comment by verdurin** [comment]
Here's the error I saw:
```
== FAILED: Installation ended unsuccessfully (build directory: /dev/shm/CellRank/2.0.2/foss-2023a): build failed (first 300 chars): `/eb/maint/software/Python/3.11.3-GCCcore-12.3.0/bin/python -m pip check` failed:
botocore 1.34.51 has requirement urllib3<2.1,>=1.25.4; python_version >= "3.10", but you have urllib3 2.1.0.
poetry 1.5.1 has requirement urllib3<2.0.0,>=1.26.0, but you have urllib3 2.1.0.
```
Do I need to rebuild something?

**Comment by pavelToman** [comment]
> Here's the error I saw:
> 
> ```
> == FAILED: Installation ended unsuccessfully (build directory: /dev/shm/CellRank/2.0.2/foss-2023a): build failed (first 300 chars): `/eb/maint/software/Python/3.11.3-GCCcore-12.3.0/bin/python -m pip check` failed:
> botocore 1.34.51 has requirement urllib3<2.1,>=1.25.4; python_version >= "3.10", but you have urllib3 2.1.0.
> poetry 1.5.1 has requirement urllib3<2.0.0,>=1.26.0, but you have urllib3 2.1.0.
> ```
> 
> Do I need to rebuild something?

Could it be caused by Poetry? https://github.com/easybuilders/easybuild-easyconfigs/blob/develop/easybuild/easyconfigs/p/poetry/poetry-1.7.1-GCCcore-12.3.0.eb
It imports urllib3 2.1.0. It comes from scVelo and loompy dependencies I hope.

**Comment by verdurin** [comment]
Test report by @verdurin
**FAILED**
Build succeeded for 0 out of 1 (1 easyconfigs in total)
easybuild-c7.novalocal - Linux CentOS Linux 7.9.2009, x86_64, Intel Xeon Processor (Skylake, IBRS), Python 3.6.8
See https://gist.github.com/verdurin/5804ecb714839c996c60d5dd14b401e9 for a full test report.

**Comment by verdurin** [comment]
Yes, I think it is `poetry`.

**Comment by pavelToman** [comment]
- https://github.com/easybuilders/easybuild-easyconfigs/pull/20148

**Comment by casparvl** [comment]
Since there was some discussion on #20148 (and I don't think that PR is needed):

```
== FAILED: Installation ended unsuccessfully (build directory: /dev/shm/CellRank/2.0.2/foss-2023a): build failed (first 300 chars): `/eb/maint/software/Python/3.11.3-GCCcore-12.3.0/bin/python -m pip check` failed:
botocore 1.34.51 has requirement urllib3<2.1,>=1.25.4; python_version >= "3.10", but you have urllib3 2.1.0.
poetry 1.5.1 has requirement urllib3<2.0.0,>=1.26.0, but you have urllib3 2.1.0.
```
basically means that the `poetry` version in this PR (i.e. #20115) requires an `urllib3` that is _older_ than what we already have in the environment. I don't know which of your dependencies provides `urllib3`, but it provides version `2.1.0`, while `poetry-1.5.1` only supports versions smaller than 2.0.0. The same goes for `botocore` (not sure where that comes in? I don't see it in this PR as a seperate extension).

The solution here would probably be to pick a _newer_ version of `poetry` that _does_ support `urllib3-2.1.0`. Probably, you also need to pick a newer `botocore` version (if that exists), but as said, I don't immediately see where that is coming from. Maybe just upgrade the `poetry` version first, and take it from there...

**Comment by casparvl** [comment]
Ah, `botocore` comes in through `PyTorch-Lightning`. `urllib3` comes in through `wandb`. I'm not sure what the most elegant way is to resolve this conflict...
- Option 1: downgrade the `urllib3` version used in `wandb`
- Option 2: upgrade the version of `botocore` in PyTorch-Lightning
- Option 3: install a newer botocore with `CellRank` (I think this will take priority over the one that comes with PyTorch-Lightning, but you'll see it from the `pip check`) and hope that PyTorch-Lightning is ok with that newer version
- Option 4: install an older version of `ulrllib3` with `CellRank` and hope that `wandb` is ok with that newer version

Welcome to dependency hell :) I'm not a big fan of Option 1 and 2 because they change existing recipes btw, but that's my personal opinion.

@verdurin any opinion on this?

**Comment by verdurin** [comment]
I think I would go with option 3 first, then option 4 if that doesn't work.

**Comment by pavelToman** [comment]
wandb not using urllib3 anymore: https://github.com/easybuilders/easybuild-easyconfigs/commit/9f6ea8613e63d3250db26353dfdc58177c385a86 
Could you try to reinstall it and it should be ok?

**Comment by laraPPr** [comment]
I tried to add botocore to the extension list with different versions but got these errors.
- with `1.34.52`: `python -m pip check` failed: aiobotocore 2.12.1 has requirement botocore<1.34.52,>=1.34.41, but you have botocore 1.34.52.`
- with `1.34.81`: `python -m pip check` failed: aiobotocore 2.12.1 has requirement botocore<1.34.52,>=1.34.41, but you have botocore 1.34.81.`

**Comment by verdurin** [comment]
Test report by @verdurin
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
easybuild-c7.novalocal - Linux CentOS Linux 7.9.2009, x86_64, Intel Xeon Processor (Skylake, IBRS), Python 3.6.8
See https://gist.github.com/verdurin/9598f6c5627734dd34efcac8931c2bf5 for a full test report.

**Comment by verdurin** [comment]
My local build is working now that I've rebuilt `wandb`.

**Review by boegel — APPROVED** [review]
lgtm

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
node3113.skitty.os - Linux RHEL 8.8, x86_64, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz, Python 3.6.8
See https://gist.github.com/boegel/46b832d1901fce6d343694d825458dc7 for a full test report.

**Comment by boegel** [comment]
Going in, thanks @pavelToman!

**Pull request merged**
