### PR TITLE
{lib}[foss/2023a] phonopy v2.20.0

### PR DESCRIPTION
**Pull request by jkuhl-uni**
Hi, in this PR I add Phonopy on foss 2023a. I intend to use this for Phono3py later on.

### CODE REVIEW

**Comment by smoors** [comment]
@boegelbot: please test @ generoso

**Review by smoors — APPROVED** [review]
lgtm

**Comment by smoors** [comment]
Going in, thanks @jkuhl-uni!

**Comment by jkuhl-uni** [comment]
Hi, thank you, that was fast :)

**Pull request merged**
