### PR TITLE
{bio}[GCCcore/7.3.0] Seeder v0.01

### PR DESCRIPTION
**Pull request by JackPerdue**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by verdurin** [comment]
Test report by @verdurin
**SUCCESS**
Build succeeded for 6 out of 6 (6 easyconfigs in this PR)
rescomp2 - Linux centos linux 7.3.1611, Intel(R) Xeon(R) Gold 6126 CPU @ 2.60GHz, Python 2.7.5
See https://gist.github.com/2acd0b93be5d810f2f1431d4f823f46e for a full test report.

**Comment by verdurin** [comment]
@JackPerdue Could you submit your own build reports too please?

**Comment by vanzod** [comment]
Test report by @vanzod
**SUCCESS**
Build succeeded for 6 out of 6 (6 easyconfigs in this PR)
cermis - Linux debian 9.9, Intel(R) Xeon(R) CPU           X5670  @ 2.93GHz, Python 2.7.13
See https://gist.github.com/4d70fd7105c0815697b7f823d29a8109 for a full test report.

**Comment by vanzod** [comment]
@JackPerdue The problem is that there is already a `BioPerl-1.7.2` easyconfig available with the `foss-2018b` toolchain. If we merge this PR it would result in a toolchain conflict since the same software is installed both at `foss` and `GCCcore`. The solution is then to remove the `BioPerl` easyconfig and build `Seeder` with the `foss-2018b` toolchain to use the existing `BioPerl` easyconfig.

**Comment by JackPerdue** [comment]
What need does BioPython have of MPI or linear algebra?

**Comment by vanzod** [comment]
@JackPerdue I agree that `BioPerl` could be built with a more simpler toolchain. However, as I said before, the `2018b` toolchains which sit on top of `GCCcore-7.3.0` already have an easyconfig file for `BioPerl-1.7.2`. Hence the `BioPerl` easyconfig provided in this PR would create a resolution conflict if merged as is. So the only option to get this PR merged is to build `Seeder` against the already existent `BioPerl` easyconfig files.
We should consider building `BioPerl` with a simpler toolchain in `2019a`.

One other concern is related to having modules like `Math-Derivative`, `Math-Spline` and `Math-Utils` built with the `GCCcore` toolchain instead of `GCC` and `iccifort`. Since those modules provide compute intensive functions, it may be better to build them with different compilers in order to take advantage of potential different optimizations.

**Comment by vanzod** [comment]
@JackPerdue With #8582 `BioPerl` is now built with `GCCcore` for the 2019a toolchains. Do you want to fix this PR or do you prefer to close it and open one for `GCC-8.2.0`?

**Comment by boegel** [comment]
superseded by #9057

**Pull request closed without merging**
