### PR TITLE
add missing patch to iccifort libxc easyconfigs

### LINKED ISSUE #9917: failing installation of QuantumESPRESSO 6.5 with intel/2019a
The installation of `QuantumESPRESSO-6.5-intel-2019a.eb` (added in #9840) is failing for me, despite using the updated easyblock from https://github.com/easybuilders/easybuild-easyblocks/pull/1947.

```
mpiifort -L/user/gent/400/vsc40023/eb_phanpyscratch/CO7/skylake-ib/software/libxc/4.3.4-iccifort-2019.1.144-GCC-8.2.0-2.31.1/lib64 -L/user/gent/400/vsc40023/eb_phanpyscratch/CO7/skylake-ib/software/ELPA/2018.11.001-intel-2019a/lib -L/user/gent/400/vsc40023/eb_phanpyscratch/CO7/skylake-ib/software/HDF5/1.10.5-iimpi-2019a/lib -L/user/gent/400/vsc40023/eb_phanpyscratch/CO7/skylake-ib/software/imkl/2019.1.144-iimpi-2019a/lib -L/user/gent/400/vsc40023/eb_phanpyscratch/CO7/skylake-ib/software/imkl/2019.1.144-iimpi-2019a/lib -L/user/gent/400/vsc40023/eb_phanpyscratch/CO7/skylake-ib/software/imkl/2019.1.144-iimpi-2019a/mkl/lib/intel64 -L/user/gent/400/vsc40023/eb_phanpyscratch/CO7/skylake-ib/software/imkl/2019.1.144-iimpi-2019a/lib/intel64 -L/user/gent/400/vsc40023/eb_phanpyscratch/CO7/skylake-ib/software/icc/2019.1.144-GCC-8.2.0-2.31.1/lib/intel64 -fopenmp -o iotk_print_kinds.x iotk_print_kinds.o libiotk.a   -lxcf90 -lxcf03 -lxc -liomp5 -lpthread
ld: /user/gent/400/vsc40023/eb_phanpyscratch/CO7/skylake-ib/software/libxc/4.3.4-iccifort-2019.1.144-GCC-8.2.0-2.31.1/lib64/libxcf03.so: undefined reference to `xc_func_reference_get_bibtex'
ld: /user/gent/400/vsc40023/eb_phanpyscratch/CO7/skylake-ib/software/libxc/4.3.4-iccifort-2019.1.144-GCC-8.2.0-2.31.1/lib64/libxcf03.so: undefined reference to `xc_func_reference_get_doi'
ld: /user/gent/400/vsc40023/eb_phanpyscratch/CO7/skylake-ib/software/libxc/4.3.4-iccifort-2019.1.144-GCC-8.2.0-2.31.1/lib64/libxcf03.so: undefined reference to `xc_func_reference_get_ref'
make[2]: *** [iotk_print_kinds.x] Error 1
make[2]: Leaving directory `/tmp/vsc40023/easybuild_build/QuantumESPRESSO/6.5/intel-2019a/qe-6.5/S3DE/iotk/src'
```

I'm seeing this both on our Skylake and Haswell systems at HPC-UGent, as well as on `generoso`.

See also uploaded test report at https://github.com/easybuilders/easybuild-easyconfigs/pull/9840#issuecomment-590080171

Any ideas on this @migueldiascosta?

### PR DESCRIPTION
**Pull request by migueldiascosta**
(created using `eb --new-pr`)

fixes #9917

### CODE REVIEW

**Comment by migueldiascosta** [comment]
Test report by @migueldiascosta
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in this PR)
generoso - Linux centos linux 7.6.1810, Intel(R) Xeon(R) CPU E5-2660 v4 @ 2.00GHz, Python 3.6.8
See https://gist.github.com/fb909f17cdce9e78d1daecab672d7b3d for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in this PR)
node3104.skitty.os - Linux centos linux 7.7.1908, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz, Python 3.6.8
See https://gist.github.com/4a3b10fa04688f13a4f612e3f4e402bb for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**FAILED**
Build succeeded for 1 out of 2 (2 easyconfigs in this PR)
node2401.golett.os - Linux centos linux 7.7.1908, Intel(R) Xeon(R) CPU E5-2680 v3 @ 2.50GHz, Python 2.7.5
See https://gist.github.com/cef795850f3e3ac6c0da5b11e254f4d3 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in this PR)
node2401.golett.os - Linux centos linux 7.7.1908, Intel(R) Xeon(R) CPU E5-2680 v3 @ 2.50GHz, Python 2.7.5
See https://gist.github.com/00c5f18410941d31553b4274eb0c1827 for a full test report.

**Comment by boegel** [comment]
Going in, thanks @migueldiascosta!

**Pull request merged**
