### PR TITLE
{tools}[foss/2018b] Spyder v3.3.2 w/ Python 3.6.6

### PR DESCRIPTION
**Pull request by boegel**
(created using `eb --new-pr`)
~~#7248~~ (IPython), ~~#7249~~ (PyQt5)

### CODE REVIEW

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
node2401.golett.os - Linux centos linux 7.6.1810, Intel(R) Xeon(R) CPU E5-2680 v3 @ 2.50GHz, Python 2.7.5
See https://gist.github.com/aa2154e4d4ab0be71007455a6facb23d for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
node3102.skitty.os - Linux centos linux 7.6.1810, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz, Python 2.7.5
See https://gist.github.com/deddc81b51d3158509a5607a984efb93 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
node2004.delcatty.os - Linux centos linux 7.6.1810, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.7.5
See https://gist.github.com/9c1461ebdac93726a55722405381b979 for a full test report.

**Comment by vanzod** [comment]
Test report by @vanzod
**FAILED**
Build succeeded for 5 out of 7 (1 easyconfigs in this PR)
cermis - Linux debian 9.6, Intel(R) Xeon(R) CPU           E5620  @ 2.40GHz, Python 2.7.13
See https://gist.github.com/e94ea85111abaa226934e89474042b99 for a full test report.

**Comment by vanzod** [comment]
Test report by @vanzod
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
cermis - Linux debian 9.6, Intel(R) Xeon(R) CPU           E5620  @ 2.40GHz, Python 2.7.13
See https://gist.github.com/92399265253d73846d8301351c226410 for a full test report.

**Comment by vanzod** [comment]
Although the build completes correctly, I get this error when I try to run it:
```
$ spyder3 
Traceback (most recent call last):
  File "/opt/easybuild/software/MPI/GCC/7.3.0-2.30/OpenMPI/3.1.1/Spyder/3.3.2-Python-3.6.6/bin/spyder3", line 11, in <module>
    sys.exit(main())
  File "/opt/easybuild/software/MPI/GCC/7.3.0-2.30/OpenMPI/3.1.1/Spyder/3.3.2-Python-3.6.6/lib/python3.6/site-packages/spyder/app/start.py", line 178, in main
    from spyder.app import mainwindow
  File "/opt/easybuild/software/MPI/GCC/7.3.0-2.30/OpenMPI/3.1.1/Spyder/3.3.2-Python-3.6.6/lib/python3.6/site-packages/spyder/app/mainwindow.py", line 49, in <module>
    requirements.check_spyder_kernels()
  File "/opt/easybuild/software/MPI/GCC/7.3.0-2.30/OpenMPI/3.1.1/Spyder/3.3.2-Python-3.6.6/lib/python3.6/site-packages/spyder/requirements.py", line 66, in check_spyder_kernels
    % actual_ver)
  File "/opt/easybuild/software/MPI/GCC/7.3.0-2.30/OpenMPI/3.1.1/Spyder/3.3.2-Python-3.6.6/lib/python3.6/site-packages/spyder/requirements.py", line 24, in show_warning
    raise RuntimeError(message)
RuntimeError: Please check Spyder installation requirements:
spyder-kernels < 1.0 is required (found 1.1.0).
```

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
node2456.golett.os - Linux centos linux 7.6.1810, Intel(R) Xeon(R) CPU E5-2680 v3 @ 2.50GHz, Python 2.7.5
See https://gist.github.com/b1baa3187bbad0509c53fe2658cad7b3 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
node3115.skitty.os - Linux centos linux 7.6.1810, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz, Python 2.7.5
See https://gist.github.com/e1346a2ce59e458d136552f5f25817f3 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
node2096.delcatty.os - Linux centos linux 7.6.1810, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.7.5
See https://gist.github.com/b0167e44700a55fe0ebc7c3651ebdd72 for a full test report.

**Comment by vanzod** [comment]
Test report by @vanzod
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
cermis - Linux debian 9.7, Intel(R) Xeon(R) CPU           X5670  @ 2.93GHz, Python 2.7.13
See https://gist.github.com/7189ce076eb3057e9afb74a41f14b93d for a full test report.

**Comment by vanzod** [comment]
Going in, thanks @boegel!

**Pull request merged**
