### PR TITLE
add alternate checksum for LaplacesDemon in R 3.6.2 easyconfigs

### PR DESCRIPTION
**Pull request by Serpens**
Checksum for LaplacesDemon CRAN package has changed. Probably some changes considered minor by the authors, and "not enough" for a version bump.

### CODE REVIEW

**Comment by boegel** [comment]
@Serpens Thank you very much for issuing this PR.

I took a look at what has changed:

```diff
diff -ru LaplacesDemon.old/DESCRIPTION LaplacesDemon/DESCRIPTION
--- LaplacesDemon.old/DESCRIPTION	2018-06-30 19:19:43.000000000 +0200
+++ LaplacesDemon/DESCRIPTION	2020-02-03 09:35:49.000000000 +0100
@@ -32,6 +32,12 @@
   Stephane Laurent [ctb],
   Quentin F. Gronau [ctb],
   Henrik Singmann [cre]
-Maintainer: Henrik Singmann <singmann+LaplacesDemon@gmail.com>
+Maintainer: ORPHANED
 Repository: CRAN
 Date/Publication: 2018-06-30 17:19:43 UTC
+X-CRAN-Original-Maintainer: Henrik Singmann
+        <singmann+LaplacesDemon@gmail.com>
+X-CRAN-Comment: Orphaned on 2020-02-03 as check issues were not
+        corrected in time.
+ .
+ Fails on MKL as has badly-written numerical linear algebra code
diff -ru LaplacesDemon.old/MD5 LaplacesDemon/MD5
--- LaplacesDemon.old/MD5	2018-06-30 19:19:44.000000000 +0200
+++ LaplacesDemon/MD5	2020-02-03 09:35:49.000000000 +0100
@@ -1,5 +1,5 @@
 7b8a8d0d7a19b32d45f0816fd1d2b0ef *CHANGELOG
-2eef9c30888b7c87d733af6155bbf9c0 *DESCRIPTION
+e219538158cc7a0e70e478cb81630875 *DESCRIPTION
 c3cc24977ea0e5e80769e2e325f7d3dd *LICENSE
 e539630e54f7c3a13050b5e65cf2911f *NAMESPACE
 c27d786c909d4ef57c05712d9c9bf726 *R/ABB.R
```

Since only the package description has changed (no code changes), we should accept both source tarballs (and hence both checksums), like we already do for several other R packages (see #9789 for example).

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in this PR)
node2403.golett.os - Linux centos linux 7.7.1908, Intel(R) Xeon(R) CPU E5-2680 v3 @ 2.50GHz, Python 2.7.5
See https://gist.github.com/1b0e42e7502232bf43079bbe31832655 for a full test report.

**Comment by boegel** [comment]
@Serpens I prefer fixing this ASAP, so I've made the additional change to add the alternate checksum rather than replacing the existing one...

**Comment by boegel** [comment]
Going in, thanks @Serpens!

**Comment by Flamefire** [comment]
>  Fails on MKL as has badly-written numerical linear algebra code

Straight up and honest :D

**Pull request merged**
