### PR TITLE
{bio}[foss/2021a] cDNA_Cupcake v26.0.0 w/ Python 3.9.5

### PR DESCRIPTION
**Pull request by manifestoso**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by manifestoso** [comment]
Test report by @robqiao
**FAILED**
Build succeeded for 0 out of 1 (1 easyconfigs in total)
hpc-head01 - Linux UNKNOWN UNKNOWN, x86_64, Intel(R) Xeon(R) Gold 6130 CPU @ 2.10GHz, Python 3.9.6
See https://gist.github.com/b17233fda51d6ccf8efed7a202c952f7 for a full test report.

**Comment by manifestoso** [comment]
Test report by @robqiao
**FAILED**
Build succeeded for 0 out of 1 (1 easyconfigs in total)
hpc-head01 - Linux UNKNOWN UNKNOWN, x86_64, Intel(R) Xeon(R) Gold 6130 CPU @ 2.10GHz, Python 3.9.6
See https://gist.github.com/f3d216de590ba0a2cabd7f0e23cd3c12 for a full test report.

**Comment by manifestoso** [comment]
Test report by @robqiao
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
hpc-head01 - Linux UNKNOWN UNKNOWN, x86_64, Intel(R) Xeon(R) Gold 6130 CPU @ 2.10GHz, Python 3.9.6
See https://gist.github.com/f0abf167d8bdfa9b3c4fba0093781c2f for a full test report.

**Comment by lexming** [comment]
Test report by @lexming
**FAILED**
Build succeeded for 1 out of 4 (1 easyconfigs in total)
node300.hydra.os - Linux centos linux 7.9.2009, x86_64, Intel(R) Xeon(R) Gold 6148 CPU @ 2.40GHz, Python 2.7.5
See https://gist.github.com/3e4e555027237c5156b41362ad7d95b5 for a full test report.

**Comment by lexming** [comment]
Test report by @lexming
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
node300.hydra.os - Linux centos linux 7.9.2009, x86_64, Intel(R) Xeon(R) Gold 6148 CPU @ 2.40GHz, Python 2.7.5
See https://gist.github.com/de1867d285074fce8addaaf32976ccfd for a full test report.

**Review by lexming — APPROVED** [review]
LGTM

**Comment by lexming** [comment]
@boegelbot: please test @ generoso

**Comment by lexming** [comment]
Going in, thanks @manifestoso !

**Pull request merged**
