### PR TITLE
{math}[intel/2018a] Sympy 1.3 w/ Python 2.7.14 (REVIEW)

### PR DESCRIPTION
**Pull request by hajgato**

### CODE REVIEW

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in this PR)
node3151.skitty.os - Linux centos linux 7.5.1804, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz, Python 2.7.5
See https://gist.github.com/b6f66e1de99b2c76b0d2ca74b15d4ec9 for a full test report.

**Comment by hajgato** [comment]
@boegel done

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in this PR)
node3124.skitty.os - Linux centos linux 7.5.1804, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz, Python 2.7.5
See https://gist.github.com/4c356b90f3e4ff7732c4f5039214d03e for a full test report.

**Comment by boegel** [comment]
@hajgato It looks like the failing tests are caused by having `$TMPDIR` defined to a (relatively) long (but existing) location. The errors for the failing tests included messages like:

```
IOError: [Errno 2] No such file or directory: '/local/1234567.master.example.gent.vsc/eb-Jx7NUo/tmpgc9xje/_newton.c'
```

Can you check if you can reproduce this? Just run `export TMPDIR=...` before running `eb`.

If you can reproduce it, maybe we should change the `runtest` command to something like:

```python
# use custom (short) value for $TMPDIR to avoid breaking some tests >_<
runtest = "TMPDIR=$(mktemp -d -p /tmp) python setup.py test && rm -rf $TMPDIR"

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in this PR)
node2404.golett.os - Linux centos linux 7.5.1804, Intel(R) Xeon(R) CPU E5-2680 v3 @ 2.50GHz, Python 2.7.5
See https://gist.github.com/cf6c687faa077a6b9af735d23802cd1e for a full test report.

**Comment by hajgato** [comment]
@boegel I tried to reinstall `sympy` with 
```
 export TMPDIR=/tmp/hajgato/long_but_existing_directory_to_test/annoying_software
 mkdir -p $TMPDIR 
 eb sympy-1.3-intel-2018a-Python-2.7.14.eb --force 
```
And it worked.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in this PR)
node2091.delcatty.os - Linux centos linux 7.5.1804, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.7.5
See https://gist.github.com/156ef8be1ba808598cb9ecbf179c493b for a full test report.

**Comment by boegel** [comment]
@hajgato Maybe it's not the length of the path, but symlinking that is the actual issue?

Here's what it fails with for me:

```
$ echo $TMPDIR
/local/4801144.master15.delcatty.gent.vsc
$ ls -ld /local/4801144.master15.delcatty.gent.vsc
drwxr-xr-x 3 me me 4096 Sep 27 08:59 /local/4801144.master15.delcatty.gent.vsc
$ ls -l /local
lrwxrwxrwx 1 root root 4 Jan 24  2017 /local -> /tmp
$ file /local
/local: symbolic link to `/tmp'
$ file /tmp
/tmp: sticky directory
$ file /tmp/4801144.master15.delcatty.gent.vsc
/tmp/4801144.master15.delcatty.gent.vsc: directory
```

**Comment by hajgato** [comment]
@boegel let me try with a symlink. Although it will nor be easy to find a directory that it is for sure not a symlink. (Perhaps `/dev/shm`?)

**Comment by boegel** [comment]
@hajgato If we can confirm the problem, we can either report it upstream and find a temporary workaround (`unset TMPDIR` may work...), or we patch the tests to take into account that the location may be a symlink...

**Comment by hajgato** [comment]
@boegel Yep, its the symlink.

**Comment by hajgato** [comment]
@boegel probably we should. But we have to find a solution as well. Honestly, I am not in a favor of writing a patch. Should I try unsetting `TMPDIR`?

**Comment by boegel** [comment]
@hajgato Let's indeed try with `unset TMPDIR && python setup.py test`, and add a comment above to explain the `unset TMPDIR` (preferably with a link to the reported issue included).

That will make the tests use `/tmp`, which is not a symlink, so it works (I'll verify that in an environment where `$TMPDIR` is set as before).

**Comment by hajgato** [comment]
@boegel `unset TMPDIR` does not solve the problem, as the tests are made in the current directory. (Which should be the output/temporary dir of `EasyBuild`.

**Comment by hajgato** [comment]
@boegel What I do not understand, that I have a missing file in the path of `/tmp/hajgato/link/eb-6klLPH/tmp4V6DAS/`. This is suppoded to be the `EasyBuild` temporary dir, so I do not understand why the file should be there? (ANd for sure it is not influenced by the `$TMPDIR` as it is `$TMPDIR/eb-{random}`.

**Comment by hajgato** [comment]
In other words, `$TMPDIR` have to be changed before `eb` is executed, or I have to find the reason why is `sympy` puts it files in the `eb` temporary directory.

**Comment by hajgato** [comment]
@boegel Can you try my solution? It does not solve the core of the problem, but it works.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in this PR)
node3101.skitty.os - Linux centos linux 7.5.1804, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz, Python 2.7.5
See https://gist.github.com/42d99a365c805bedf6cd989308b7d1e5 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in this PR)
node2101.delcatty.os - Linux centos linux 7.5.1804, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.7.5
See https://gist.github.com/d99fc424f8ff110b0431f5b918754288 for a full test report.

**Comment by boegel** [comment]
Going in, thanks @hajgato!

**Pull request merged**
