### PR TITLE
update to libjxl 0.5 + disable building of man pages

### LINKED ISSUE #13827: libjxl easyconfig fails to install if asciidoc is installed in OS
`libjxl` added in #13453 fails for me with:

```
  File "/usr/bin/a2x", line 76
    print '%s: %s' % (PROG,msg)
                 ^
SyntaxError: invalid syntax
```

```
$ rpm -qf /usr/bin/a2x
asciidoc-8.6.8-5.el7.noarch
```

### PR DESCRIPTION
**Pull request by boegel**
fixes #13827

### CODE REVIEW

**Comment by Micket** [comment]
Seems to be confirmed as a bug.
1. We could use skcms instead. It's a lot messier, in particular because there is no way to download the skcms sources with a predictable checksum.
2. We could remove libjxl for the next release, making it easier to switch to a good version in the future.
3. Skip this failing test and release as is

**Comment by boegel** [comment]
@boegelbot please test @ generoso
CORE_CNT=16

**Review by Micket — APPROVED** [review]
looks good enough to me, lets hope that one test is very niche

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
node3129.skitty.os - Linux centos linux 7.9.2009, x86_64, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz, Python 3.6.8
See https://gist.github.com/ebcdc11b2a98179016e343890abb90f6 for a full test report.

**Comment by Micket** [comment]
Test report by @Micket
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
vera-c1 - Linux centos linux 7.9.2009, x86_64, Intel Xeon Processor (Skylake), Python 3.6.8
See https://gist.github.com/4c20783dff55dd80767d74eba8dc1cbb for a full test report.

**Comment by Micket** [comment]
Going in, thanks @boegel!

**Pull request merged**
