### PR TITLE
update source URL for isl in GCCcore easyconfigs

### PR DESCRIPTION
**Pull request by SebastianAchilles**
(created using `eb --new-pr`)
Adding new mirror for `isl` since http://gcc.cybermirror.org/infrastructure/ and http://isl.gforge.inria.fr/ are down

### CODE REVIEW

**Comment by SebastianAchilles** [comment]
@boegelbot please test @ generoso
EB_ARGS="--fetch --force-download --sourcepath /tmp/$USER/pr15320"

**Comment by SebastianAchilles** [comment]
@boegelbot please test @ generoso
EB_ARGS="--stop source --force-download --sourcepath /tmp/$USER/pr15320"

**Comment by SebastianAchilles** [comment]
Test report by @sebastianachilles
**FAILED**
Build succeeded for 24 out of 25 (25 easyconfigs in total)
zen2-ubuntu-eb - Linux Ubuntu 22.04, x86_64, AMD EPYC 7452 32-Core Processor (zen2), Python 3.10.4
See https://gist.github.com/58d33fea6b7250d30ffbda7b7926398e for a full test report.

**Comment by SebastianAchilles** [comment]
@boegelbot please test @ jsc-zen2
EB_ARGS="--stop source --force-download --sourcepath /tmp/$USER/pr15320 --installpath /tmp/$USER/pr15320"

**Review by boegel — CHANGES_REQUESTED** [review]
@SebastianAchilles We should also update the oldest `GCCcore` easyconfigs to use SHA256 checksums, to make the test suite pass.

Done in https://github.com/SebastianAchilles/easybuild-easyconfigs/pull/1, so just merging that should suffice...

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 25 out of 25 (25 easyconfigs in total)
node2607.swalot.os - Linux CentOS Linux 7.9.2009, x86_64, Intel(R) Xeon(R) CPU E5-2660 v3 @ 2.60GHz (haswell), Python 3.6.8
See https://gist.github.com/4e27555c8d41d6caf62312f170db305c for a full test report.

**Comment by boegel** [comment]
Going in, thanks @SebastianAchilles!

**Pull request merged**
