### PR TITLE
{lib}[foss/2020b,fosscuda/2020b] Boost.Python (w/ NumPy extension) v1.74.0 w/ Python 3.8.6

### PR DESCRIPTION
**Pull request by ThomasHoffmann77**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by migueldiascosta** [comment]
@boegelbot please test @ generoso

**Comment by migueldiascosta** [comment]
@ThomasHoffmann77 there is a concern that this additional variant using a full toolchain would create confusion and be hard to maintain moving forward

if there's a single use case, `EMAN2`, it may be simpler to turn `EMAN2` into a bundle and add this variant of `Boost.Python` as a component there (we'd help you with that if necessary)

or do you already foresee other use cases for this variant?

**Comment by ThomasHoffmann77** [comment]
@migueldiascosta 
> @ThomasHoffmann77 there is a concern that this additional variant using a full toolchain would create confusion and be hard to maintain moving forward
> 
> if there's a single use case, `EMAN2`, it may be simpler to turn `EMAN2` into a bundle and add this variant of `Boost.Python` as a component there (we'd help you with that if necessary)

no problem.

> 
> or do you already foresee other use cases for this variant?

so far I have no other use case in mind

**Comment by ThomasHoffmann77** [comment]
> @migueldiascosta
> 
> > @ThomasHoffmann77 there is a concern that this additional variant using a full toolchain would create confusion and be hard to maintain moving forward
> > if there's a single use case, `EMAN2`, it may be simpler to turn `EMAN2` into a bundle and add this variant of `Boost.Python` as a component there (we'd help you with that if necessary)
> 
> no problem.
> 
> > or do you already foresee other use cases for this variant?
> 
> so far I have no other use case in mind



> @ThomasHoffmann77 there is a concern that this additional variant using a full toolchain would create confusion and be hard to maintain moving forward
> 
> if there's a single use case, `EMAN2`, it may be simpler to turn `EMAN2` into a bundle and add this variant of `Boost.Python` as a component there (we'd help you with that if necessary)
> 
> or do you already foresee other use cases for this variant?

@migueldiascosta done

**Comment by ThomasHoffmann77** [comment]
@migueldiascosta Could you please assist how to handle Boost-1.71.0_fix-Python3.patch in #14641. Should the file be duplicated?

**Comment by migueldiascosta** [comment]
@ThomasHoffmann77 indeed, that came up when @boegel and I discussed this a few weeks ago, and the conclusion then was that it had to be (unfortunately, I'd say)

@boegel, second thoughts/alternatives?

**Comment by boegel** [comment]
I guess a symbolic link is another option, I don't have a better alternative right now.
Maybe we should keep a central `patches` directory in this repository, not sure that would be better.

Patches rarely need to be edited, so duplicating a patch file is not a disaster I think...

**Comment by migueldiascosta** [comment]
opened https://github.com/easybuilders/easybuild-easyconfigs/issues/14983 to keep track of the options for handling of duplicated patches

just for future reference, an alternative in this particular case would be to rename this `Boost.Python` `-numpy` variant to, e.g., `Boost.Numpy`, which would be placed in a separate folder, avoiding the confusion regarding toolchain levels for `Boost.Python`

**Comment by boegel** [comment]
closing this since `foss/2020b` is deprecated, see https://docs.easybuild.io/policies/toolchains

**Pull request closed without merging**
