### PR TITLE
Files for building recent NWChem releases with EasyBuild, and patches for same

### PR DESCRIPTION
**Pull request by valtandor**
Depends on https://github.com/hpcugent/easybuild-easyblocks/pull/834 and https://github.com/hpcugent/easybuild-framework/pull/1623

### CODE REVIEW

**Comment by boegel** [comment]
Jenkins: ok to test

**Comment by boegel** [comment]
@valtandor:

```
AssertionError: Filename '/data/jenkins/workspace/easybuild-easyconfigs-pr-builder@2/easybuild/easyconfigs/n/NWChem/NWChem-6.6.revision27844-intel-2015a-Python-2.7.9.eb' of parsed easyconfig matches expected filename 'NWChem-6.6-intel-2015a-Python-2.7.9.eb'
```

**Comment by scroogie** [comment]
Seems this PR had a newer revision of NWChem than the latest. 
@valtandor Did you abandon this?

**Comment by migueldiascosta** [comment]
@valtandor, this PR is being closed for the following reason(s): no activity for > 1 year.
Please don't hesitate to reopen this PR or add a comment if you feel this contribution is still relevant.
For more information on our policy w.r.t. closing PRs, see https://easybuild.readthedocs.io/en/latest/Contributing.html#why-a-pull-request-may-be-closed-by-a-maintainer

**Pull request closed without merging**
