### PR TITLE
SWIG: Update PCRE version to 8.44

### PR DESCRIPTION
**Pull request by akesandgren**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by lexming** [comment]
Test report by @lexming
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
login2.cerberus.os - Linux centos linux 7.7.1908, Intel(R) Xeon(R) Gold 6126 CPU @ 2.60GHz, Python 2.7.5
See https://gist.github.com/02ed3694ea6c0b14f9d5e2e4bccf1bb1 for a full test report.

**Comment by zao** [comment]
Test report by @zao
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
freja - Linux ubuntu 18.04, Intel(R) Core(TM) i7-8700K CPU @ 3.70GHz, Python 2.7.17
See https://gist.github.com/c2ad8cafcbb41d2866cfa7b0484f9a9d for a full test report.

**Comment by akesandgren** [comment]
Need to make a single PR for the PCRE 8.43 -> 8.44 update, closing

**Comment by akesandgren** [comment]
Replaced with #10169

**Pull request closed without merging**
