### PR TITLE
{lib}[foss/2020b,fosscuda/2020b] PyTorch-Geometric v1.7.0 w/ Python 3.8.6

### PR DESCRIPTION
**Pull request by boegel**
(created using `eb --new-pr`)
requires:
* #13118

### CODE REVIEW

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 14 out of 14 (2 easyconfigs in total)
node2617.swalot.os - Linux centos linux 7.9.2009, x86_64, Intel(R) Xeon(R) CPU E5-2660 v3 @ 2.60GHz (haswell), Python 3.6.8
See https://gist.github.com/db93f7691cc6e22fbe21a88d94465b00 for a full test report.

**Comment by SebastianAchilles** [comment]
@boegel Do we want to add an exception for `numba` in `test/easyconfigs/easyconfigs.py` to fix the failing test?

**Comment by boegel** [comment]
@SebastianAchilles Tests pass now

**Comment by boegel** [comment]
@boegelbot please test @ generoso

**Comment by surak** [comment]
should we even push for such old software?

**Comment by boegel** [comment]
closing this since `foss/2022b` is no longer supported, see https://docs.easybuild.io/policies/toolchains

**Pull request closed without merging**
