### PR TITLE
{chem}[intel/2019a] critic2 v1.0stable

### PR DESCRIPTION
**Pull request by soheil-soltani**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by migueldiascosta** [comment]
Test report by @migueldiascosta
**FAILED**
Build succeeded for 0 out of 1 (1 easyconfigs in this PR)
generoso - Linux centos linux 7.6.1810, Intel(R) Xeon(R) CPU E5-2660 v4 @ 2.00GHz, Python 3.6.8
See https://gist.github.com/511a9c63774724b6ea80bad6a49a1281 for a full test report.

**Comment by migueldiascosta** [comment]
@soheil-soltani you can check the style issues with `--check-contrib` and add the checksums with `--inject-checksums`

**Comment by migueldiascosta** [comment]
regarding the failing test, it works with `parallel = 1`

**Comment by verdurin** [comment]
@soheil-soltani any updates here? (and welcome to EasyBuild...)

**Comment by boegel** [comment]
No reply for over 2 years on requested changes, so closing this PR...

**Pull request closed without merging**
