### PR TITLE
{bio}[foss/2017a] GEMMA v0.97

### PR DESCRIPTION
**Pull request by timeu**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by akesandgren** [comment]
You can drop the easyconfig for Eigen, we have Eigen-3.3.3 for GCCcore-6.3.0 which is what foss/2017a is based on.

**Comment by timeu** [comment]
Ping

**Comment by migueldiascosta** [comment]
Test report by @migueldiascosta
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
generoso - Linux centos linux 7.6.1810, Intel(R) Xeon(R) CPU E5-2660 v4 @ 2.00GHz, Python 3.6.8
See https://gist.github.com/457cf81cda7d2619ca468ddacece1562 for a full test report.

**Comment by migueldiascosta** [comment]
Going in, thanks @timeu!

**Pull request merged**
