### PR TITLE
{data}[GCCcore/10.2.0] HDF-EOS v2.20, h4toh5 v2.2.3

### PR DESCRIPTION
**Pull request by tstrempel**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by verdurin** [comment]
Test report by @verdurin
**FAILED**
Build succeeded for 0 out of 3 (3 easyconfigs in total)
nuc.lan - Linux Fedora 33, x86_64, Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz, Python 3.9.5
See https://gist.github.com/e18084a9b29f2af09ce16ce19d49c886 for a full test report.

**Comment by verdurin** [comment]
Test report by @verdurin
**FAILED**
Build succeeded for 0 out of 3 (3 easyconfigs in total)
easybuild-c7.novalocal - Linux centos linux 7.9.2009, x86_64, Intel Xeon Processor (Skylake, IBRS), Python 3.6.8
See https://gist.github.com/a91b488fb1a2710aa2d96e327cf4cb1d for a full test report.

**Comment by verdurin** [comment]
@tstrempel I'm seeing source download errors down to the failed SSL certificate verification:
```
== 2021-06-23 12:10:18,621 filetools.py:785 WARNING IOError occurred while trying to download https://observer.gsfc.nasa.gov/ftp/edhs/hdfeos/latest_release/HDF-EOS2.20v1.00.tar.Z to /mnt/ds918plus/eb/common/sources/h/HDF-EOS/HDF-EOS2.20v1.00.tar.Z: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1129)>
```

**Comment by tstrempel** [comment]
I will fix it soon

**Comment by tstrempel** [comment]
should work now

**Comment by verdurin** [comment]
Test report by @verdurin
**SUCCESS**
Build succeeded for 3 out of 3 (3 easyconfigs in total)
nuc.lan - Linux Fedora 33, x86_64, Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz, Python 3.9.5
See https://gist.github.com/7f4065cea2d6693b3790ef9e84cb46e3 for a full test report.

**Review by verdurin — APPROVED** [review]
Looks fine.

**Comment by verdurin** [comment]
Going in, thanks @tstrempel!

**Pull request merged**
