### PR TITLE
add gnuplot dependency for OpenFOAM v1606 to v2006

### PR DESCRIPTION
**Pull request by lexming**
(created using `eb --new-pr`)

Follow up on https://github.com/easybuilders/easybuild-easyconfigs/pull/11770
Needed by https://github.com/easybuilders/easybuild-easyblocks/pull/2256

### CODE REVIEW

**Comment by lexming** [comment]
Test report by @lexming
Using easyblocks from PR(s) https://github.com/easybuilders/easybuild-easyblocks/pull/2256
**FAILED**
Build succeeded for 4 out of 5 (2 easyconfigs in total)
node376.hydra.os - Linux centos linux 7.9.2009, x86_64, Intel(R) Xeon(R) Gold 6148 CPU @ 2.40GHz, Python 2.7.5
See https://gist.github.com/40dd7602af011891c10afa07b344dcfa for a full test report.

**Comment by lexming** [comment]
Test report by @lexming
Using easyblocks from PR(s) https://github.com/easybuilders/easybuild-easyblocks/pull/2256
**FAILED**
Build succeeded for 0 out of 2 (2 easyconfigs in total)
node378.hydra.os - Linux centos linux 7.9.2009, x86_64, Intel(R) Xeon(R) Gold 6148 CPU @ 2.40GHz, Python 2.7.5
See https://gist.github.com/ec133509a84c271b0b3570283e227639 for a full test report.

**Comment by lexming** [comment]
Test report by @lexming
Using easyblocks from PR(s) https://github.com/easybuilders/easybuild-easyblocks/pull/2256
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in total)
node378.hydra.os - Linux centos linux 7.9.2009, x86_64, Intel(R) Xeon(R) Gold 6148 CPU @ 2.40GHz, Python 2.7.5
See https://gist.github.com/24ca14d08b12cb50e808bb69f95bfc76 for a full test report.

**Comment by lexming** [comment]
Test report by @lexming
Using easyblocks from PR(s) https://github.com/easybuilders/easybuild-easyblocks/pull/2256
**FAILED**
Build succeeded for 6 out of 10 (2 easyconfigs in total)
node377.hydra.os - Linux centos linux 7.9.2009, x86_64, Intel(R) Xeon(R) Gold 6148 CPU @ 2.40GHz, Python 2.7.5
See https://gist.github.com/999de14dd09c3b1518ca13489001e976 for a full test report.

**Comment by lexming** [comment]
Test report by @lexming
Using easyblocks from PR(s) https://github.com/easybuilders/easybuild-easyblocks/pull/2256
**SUCCESS**
Build succeeded for 3 out of 3 (2 easyconfigs in total)
node379.hydra.os - Linux centos linux 7.9.2009, x86_64, Intel(R) Xeon(R) Gold 6148 CPU @ 2.40GHz, Python 2.7.5
See https://gist.github.com/e0a5794b7912027ba55e6fa58d339da7 for a full test report.

**Comment by boegel** [comment]
@boegelbot please test @ generoso
EB_ARGS=" --include-easyblocks-from-pr 2256 OpenFOAM-v1906-foss-2019b.eb OpenFOAM-v1912-foss-2019b.eb OpenFOAM-v1912-intel-2019b.eb OpenFOAM-v2006-foss-2020a.eb "
CORE_CNT=16

**Comment by boegel** [comment]
Test report by @boegel
Using easyblocks from PR(s) https://github.com/easybuilders/easybuild-easyblocks/pull/2256
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in total)
node3132.skitty.os - Linux centos linux 7.9.2009, x86_64, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz, Python 3.6.8
See https://gist.github.com/67c7d6f04e2a1938b3f791d8038545b3 for a full test report.

**Review by boegel — APPROVED** [review]
lgtm

**Comment by boegel** [comment]
Going in, thanks @lexming!

**Comment by lexming** [comment]
Test report by @lexming
Using easyblocks from PR(s) https://github.com/easybuilders/easybuild-easyblocks/pull/2256
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in total)
node381.hydra.os - Linux centos linux 7.9.2009, x86_64, Intel(R) Xeon(R) Gold 6148 CPU @ 2.40GHz, Python 2.7.5
See https://gist.github.com/71625a671ebe9bd18643a66933b749a1 for a full test report.

**Comment by lexming** [comment]
Test report by @lexming
Using easyblocks from PR(s) https://github.com/easybuilders/easybuild-easyblocks/pull/2256
**SUCCESS**
Build succeeded for 6 out of 6 (3 easyconfigs in total)
node379.hydra.os - Linux centos linux 7.9.2009, x86_64, Intel(R) Xeon(R) Gold 6148 CPU @ 2.40GHz, Python 2.7.5
See https://gist.github.com/1281168dc4354df01c72be8efeaa4f1e for a full test report.

**Comment by lexming** [comment]
Test report by @lexming
Using easyblocks from PR(s) https://github.com/easybuilders/easybuild-easyblocks/pull/2256
**SUCCESS**
Build succeeded for 3 out of 3 (1 easyconfigs in total)
node381.hydra.os - Linux centos linux 7.9.2009, x86_64, Intel(R) Xeon(R) Gold 6148 CPU @ 2.40GHz, Python 2.7.5
See https://gist.github.com/8030ae8f6c4d009cd74f7bff62653a10 for a full test report.

**Comment by lexming** [comment]
Recap of my tests:
v1606+, v1612+: https://github.com/easybuilders/easybuild-easyconfigs/pull/11800#issuecomment-738500153
v1712: https://github.com/easybuilders/easybuild-easyconfigs/pull/11800#issuecomment-738872099
v1806, v1812: https://github.com/easybuilders/easybuild-easyconfigs/pull/11800#issuecomment-739929955
v1906, v1912: https://github.com/easybuilders/easybuild-easyconfigs/pull/11800#issuecomment-740188235
v2006: https://github.com/easybuilders/easybuild-easyconfigs/pull/11800#issuecomment-740344798

**Pull request merged**
