### PR TITLE
{chem,devel}[GCCcore/11.3.0,gompi/2022a] OpenBabel v3.1.1, w/ Python 3.10.4

### PR DESCRIPTION
**Pull request by maxim-masterov**
(created using `eb --new-pr`)

### CODE REVIEW

**Review by Micket — APPROVED** [review]
lgtm

**Comment by Micket** [comment]
@boegelbot please test @ generoso

**Comment by Micket** [comment]
Test report by @Micket
**FAILED**
Build succeeded for 2 out of 3 (1 easyconfigs in total)
alvis-c1 - Linux Rocky Linux 8.5, x86_64, Intel Xeon Processor (Skylake), Python 3.6.8
See https://gist.github.com/a3664b629613c58c2e1c0132d5e9b6f4 for a full test report.

**Comment by akesandgren** [comment]
@boegelbot Please test @ jsc-zen2

**Pull request merged**
