### PR TITLE
add hwloc dependency to easyconfig for tbb v2021.4.0

### PR DESCRIPTION
**Pull request by jfgrimm**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by jfgrimm** [comment]
assuming old versions also affected, will need to double-check hwloc version requirements

**Comment by jfgrimm** [comment]
Test report by @jfgrimm
**FAILED**
Build succeeded for 1 out of 2 (2 easyconfigs in total)
node133.pri.viking.alces.network - Linux CentOS Linux 7.9.2009, x86_64, Intel(R) Xeon(R) Gold 6138 CPU @ 2.00GHz (skylake_avx512), Python 3.6.8
See https://gist.github.com/e542dbb7fbb29b7540f406f5485ad882 for a full test report.

**Comment by jfgrimm** [comment]
> @jfgrimm `Salmon` failed with `error: cannot find -lzstd`, but that has nothing to do with the change being made here, I think?
yeah I clearly overlooked that in the `Salmon` log. 
Nonetheless, we're not building the `TBBBind` library at all in the current configuration unless the OS supplies a suitable `hwloc`, so this is still meaningful (and e.g. `Salmon` does check for it)

**Comment by boegel** [comment]
@boegelbot please test @ generoso

**Comment by SebastianAchilles** [comment]
@boegelbot please test @ jsc-zen2

**Review by boegel — APPROVED** [review]
lgtm

**Comment by boegel** [comment]
Going in, thanks @jfgrimm!

**Pull request merged**
