### PR TITLE
{chem}[foss/2022a, GCCcore/11.3.0] ESPResSo v4.2.1, Pint v0.22

### PR DESCRIPTION
**Pull request by maxim-masterov**
Two separate easyconfigs for ESPResSo build with GPU and no-GPU support

### CODE REVIEW

**Comment by casparvl** [comment]
@boegelbot please test @ generoso

**Review by casparvl — COMMENTED** [review]
EasyConfigs lgtm, awaiting succesful tests

**Comment by casparvl** [comment]
@boegelbot please test @ jsc-zen2

**Comment by verdurin** [comment]
Test report by @verdurin
**SUCCESS**
Build succeeded for 4 out of 4 (3 easyconfigs in total)
easybuild-c7.novalocal - Linux CentOS Linux 7.9.2009, x86_64, Intel Xeon Processor (Skylake, IBRS), Python 3.6.8
See https://gist.github.com/verdurin/e9d7bf0abe55d33ca21effb2891ed6b8 for a full test report.

**Review by verdurin — APPROVED** [review]
Looks fine.

**Comment by verdurin** [comment]
Going in, thanks @maxim-masterov!

**Pull request merged**
