### PR TITLE
{lib}[GCC/8.3.0] WebKitGTK+ v2.27.4

### PR DESCRIPTION
**Pull request by smoors**
(created using `eb --new-pr`)
depends on #10768 #10766 #10765 #10764

### CODE REVIEW

**Comment by lexming** [comment]
Test report by @lexming
**FAILED**
Build succeeded for 0 out of 1 (1 easyconfigs in this PR)
node112.hydra.os - Linux centos linux 7.7.1908, x86_64, Intel(R) Xeon(R) CPU E5-2680 v2 @ 2.80GHz, Python 2.7.5
See https://gist.github.com/40e71776146c9d32b02b0294d86078cd for a full test report.

**Comment by smoors** [comment]
@lexming it looks like you're hitting the same issue as here:
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=923476
https://bugs.webkit.org/show_bug.cgi?id=195251

from the bug report I understand that this can occur with `make -j 1`
can you try again with higher parallelism, eg. `parallel = 4`?

**Comment by smoors** [comment]
@lexming it looks like you're hitting the same issue as here:
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=923476
https://bugs.webkit.org/show_bug.cgi?id=195251

from the bug report I understand that this can occur with `make -j 1`
can you try again with higher parallelism, eg. `parallel = 4`?

**Comment by smoors** [comment]
@lexming it looks like you're hitting the same issue as here:
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=923476
https://bugs.webkit.org/show_bug.cgi?id=195251

from the bug report I understand that this can occur with `make -j 1`
can you try again with higher parallelism, eg. `parallel = 4`?

**Comment by lexming** [comment]
@smoors this is the first time I see a build fail in serial :open_mouth: I'll try with more cores :+1:

**Comment by lexming** [comment]
Test report by @lexming
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
node126.hydra.os - Linux centos linux 7.7.1908, x86_64, Intel(R) Xeon(R) CPU E5-2680 v2 @ 2.80GHz, Python 2.7.5
See https://gist.github.com/920f6b7b7759a4fd766100297b0665c9 for a full test report.

**Comment by smoors** [comment]
> @smoors indeed the build does not work with a single core. Since there is no `minparallel`, could you add a comment in the easyconfig with a warning?

ok, done :+1:

**Comment by lexming** [comment]
Test report by @lexming
**FAILED**
Build succeeded for 0 out of 1 (1 easyconfigs in this PR)
node127.hydra.os - Linux centos linux 7.7.1908, x86_64, Intel(R) Xeon(R) CPU E5-2680 v2 @ 2.80GHz, Python 2.7.5
See https://gist.github.com/359ff24937b7c8ea8305834136cdcb1a for a full test report.

**Comment by smoors** [comment]
@lexming you used `--parallel = 1` again .. interesting to know if fails consistently :)

**Comment by lexming** [comment]
Test report by @lexming
**FAILED**
Build succeeded for 0 out of 1 (1 easyconfigs in this PR)
node118.hydra.os - Linux centos linux 7.7.1908, x86_64, Intel(R) Xeon(R) CPU E5-2680 v2 @ 2.80GHz, Python 2.7.5
See https://gist.github.com/fc4f84738577cbb592ca95ae8013e568 for a full test report.

**Comment by lexming** [comment]
@smoors I actually tried to build it with `parallel = 1` on purpose because the bug reports seemed to say that this error should not happen with `ninja`, so I wanted to try that :smile:

**Comment by smoors** [comment]
oops my mistake..

**Comment by lexming** [comment]
Test report by @lexming
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
node108.hydra.os - Linux centos linux 7.7.1908, x86_64, Intel(R) Xeon(R) CPU E5-2680 v2 @ 2.80GHz, Python 2.7.5
See https://gist.github.com/99ac53e0fa27e43c8faddfd9247d0292 for a full test report.

**Comment by lexming** [comment]
Going in, thanks @smoors !

**Pull request merged**
