### PR TITLE
{bio}[foss/2023a] UMI-tools v1.1.4

### PR DESCRIPTION
**Pull request by zao**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by zao** [comment]
Test report by @zao
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in total)
eb-mix.zao.se - Linux Ubuntu 22.04.3 LTS (Jammy Jellyfish), x86_64, AMD Ryzen 9 3900X 12-Core Processor (zen2), Python 3.10.12
See https://gist.github.com/zao/97e94fd36ceb77a8b5b698a0aa031b82 for a full test report.

**Comment by verdurin** [comment]
@zao please fix the permissions of the `Pysam` EC.

**Review by Micket — APPROVED** [review]
lgtm

**Comment by Micket** [comment]
oh there was a conflict, please fix.

**Comment by zao** [comment]
Someone had snuck in a Pysam-0.22.0 easyconfig while this PR was pending, removing Pysam in lieu of that PR.

**Review by Micket — APPROVED** [review]
lgtm

**Comment by Micket** [comment]
Test report by @Micket
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
vera-skylake-build - Linux Rocky Linux 8.9, x86_64, Intel Xeon Processor (Skylake, IBRS, no TSX), Python 3.6.8
See https://gist.github.com/Micket/faf5f9b66670d4faadc2841c57e10bc2 for a full test report.

**Comment by Micket** [comment]
@boegelbot please test @ generoso

**Comment by Micket** [comment]
Going in, thanks @zao!

**Pull request merged**
