### PR TITLE
{bio,lib}[GCCcore/8.3.0,gompi/2019b] BLAST+ v2.9.0, LMDB v0.9.24

### PR DESCRIPTION
**Pull request by smoors**
(created using `eb --new-pr`)
depends on ~~#8978~~

### CODE REVIEW

**Comment by smoors** [comment]
@boegel I think this spanking new https check is overly enthusiastic here.
maybe skip commented lines, or do the regex on the parsed easyconfig?

**Comment by boegel** [comment]
@smoors I agree it's borderline, but why not just use `https://hpcbios.readthedocs.org/en/latest/HPCBIOS_2012-94.html`?

**Comment by smoors** [comment]
@boegel I can do that, but I don't feel comfortable changing copyright headers of other people.
In most case it will not matter, but you never know. Or am I being paranoid here?

**Comment by boegel** [comment]
@smoors I think you're being paranoid, I don't see how they could object against changing a `http://` URL to `https://`...

Also this is @fgeorgatos we're talking about. He's chill. ;)

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 3 out of 3 (2 easyconfigs in this PR)
node2700.swalot.os - Linux centos linux 7.6.1810, Intel(R) Xeon(R) CPU E5-2660 v3 @ 2.60GHz, Python 2.7.5
See https://gist.github.com/6ecc6a4c7b1191b5cfc96082569ae66c for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in this PR)
node3116.skitty.os - Linux centos linux 7.6.1810, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz, Python 3.6.8
See https://gist.github.com/5cffa92a1046cdbf466fdeefce1a3d5f for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in this PR)
node2065.delcatty.os - Linux centos linux 7.6.1810, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.7.5
See https://gist.github.com/444565e990f0b4446228a1d54c97a735 for a full test report.

**Comment by boegel** [comment]
Going in, thanks @smoors!

**Pull request merged**
