### PR TITLE
enable building of QtWebEngine in Qt5 easyconfig using foss/2017b or intel/2017b

### PR DESCRIPTION
**Pull request by vanzod**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by vanzod** [comment]
In order to build `QtWebEngine` in `Qt5/5.8.0` the `libpci` library is required from `pciutils`. I am now having hard times to let it see it...

**Comment by akesandgren** [comment]
Kicking Travis due to changes in EasyBuild testing.

**Comment by akesandgren** [comment]
Travis kicked

**Comment by akesandgren** [comment]
@vanzod Is this still to be considered WIP? Looks fairly similar to later Qt5 easyconfigs

**Comment by lexming** [comment]
Test report by @lexming
**FAILED**
Build succeeded for 0 out of 2 (1 easyconfigs in total)
node365.hydra.os - Linux centos linux 7.9.2009, x86_64, Intel(R) Xeon(R) Gold 6148 CPU @ 2.40GHz, Python 2.7.5
See https://gist.github.com/b60ef0411081c8a8d2a207748459f6c3 for a full test report.

**Comment by lexming** [comment]
Test report by @lexming
**FAILED**
Build succeeded for 2 out of 4 (1 easyconfigs in total)
node367.hydra.os - Linux centos linux 7.9.2009, x86_64, Intel(R) Xeon(R) Gold 6148 CPU @ 2.40GHz, Python 2.7.5
See https://gist.github.com/f7eb71a85b19bdeb9a54667f3e10ecd4 for a full test report.

**Comment by lexming** [comment]
Test report by @lexming
**FAILED**
Build succeeded for 0 out of 1 (1 easyconfigs in total)
node356.hydra.os - Linux centos linux 7.9.2009, x86_64, Intel(R) Xeon(R) Gold 6148 CPU @ 2.40GHz, Python 2.7.5
See https://gist.github.com/0759690b0155a000899db52ba7c0d529 for a full test report.

**Comment by lexming** [comment]
@vanzod as part of the merge sprint I have reviewed this PR and made the necessary changes to allow its merge:
* added the missing dependency on libpci, as already mentioned in previous comments
* fixed the homepage URLs

I hope that you agree with these changes.
This PR now depends on https://github.com/easybuilders/easybuild-easyconfigs/pull/11871

**Comment by lexming** [comment]
Test report by @lexming
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
node381.hydra.os - Linux centos linux 7.9.2009, x86_64, Intel(R) Xeon(R) Gold 6148 CPU @ 2.40GHz, Python 2.7.5
See https://gist.github.com/6c2d981052012ede426bdb00ca050d64 for a full test report.

**Comment by lexming** [comment]
Test report by @lexming
**FAILED**
Build succeeded for 0 out of 1 (1 easyconfigs in total)
node381.hydra.os - Linux centos linux 7.9.2009, x86_64, Intel(R) Xeon(R) Gold 6148 CPU @ 2.40GHz, Python 2.7.5
See https://gist.github.com/44c52292e64032fe57a842b8e44cef8f for a full test report.

**Comment by lexming** [comment]
One final change: `Qt5-5.8.0-intel-2017b.eb` cannot be built with WebEngine because it requires `gcc`:
```
Using gcc version ., but at least gcc version 4.7 is required to build Qt WebEngine.                                  
QtWebEngine will not be built.
```

**Comment by lexming** [comment]
Test report by @lexming
**FAILED**
Build succeeded for 0 out of 1 (1 easyconfigs in total)
node361.hydra.os - Linux centos linux 7.9.2009, x86_64, Intel(R) Xeon(R) Gold 6148 CPU @ 2.40GHz, Python 2.7.5
See https://gist.github.com/6fa230532135c7c1aff9492f5657d8b2 for a full test report.

**Comment by lexming** [comment]
Test report by @lexming
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
node361.hydra.os - Linux centos linux 7.9.2009, x86_64, Intel(R) Xeon(R) Gold 6148 CPU @ 2.40GHz, Python 2.7.5
See https://gist.github.com/284b17232184bd827783f0791800339e for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in total)
node2710.swalot.os - Linux centos linux 7.9.2009, x86_64, Intel(R) Xeon(R) CPU E5-2660 v3 @ 2.60GHz (haswell), Python 3.6.8
See https://gist.github.com/e3691c04084172d3ec9c1ae5a882f885 for a full test report.

**Review by boegel — APPROVED** [review]
lgtm

**Comment by boegel** [comment]
Going in, thanks @vanzod!

**Pull request merged**
