### PR TITLE
{chem}[foss/2023a] RDKit v2024.03.3

### PR DESCRIPTION
**Pull request by pavelToman**
(created using `eb --new-pr`)
resolves https://github.com/vscentrum/vsc-software-stack/issues/328

Requires Boost.python from:
- [x] #20636

### CODE REVIEW

**Review by boegel — APPROVED** [review]
lgtm

**Review by boegel — DISMISSED** [review]
lgtm

**Comment by boegel** [comment]
@boegelbot please test @ generoso

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
node3107.skitty.os - Linux RHEL 8.8, x86_64, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz, Python 3.6.8
See https://gist.github.com/boegel/af7a2b4ec0f21f2db259e44e989f37e8 for a full test report.

**Comment by boegel** [comment]
@boegelbot please test @ jsc-zen3

**Comment by pavelToman** [comment]
@boegelbot please test @ jsc-zen3

**Comment by boegel** [comment]
Details on failing test below.

@pavelToman Can you check if you can find a clue as to why this is failing, maybe there's patch available?

```
        Start  27: pyForceFieldConstraints
 27/221 Test  #27: pyForceFieldConstraints ................***Failed    1.04 sec
...[09:07:46] Molecule does not have explicit Hs. Consider calling AddHs()
[09:07:46]

****
Invariant Violation
bad direction in linearSearch
Violation occurred on line 240 in file /dev/shm/boegelbot/RDKit/2024.03.3/foss-2023a/rdkit-Release_2024_03_3/Code/Numerics/Optimizer/BFGSOpt.h
Failed Expression: status >= 0
```
```
======================================================================
FAIL: testUFFAngleConstraints (__main__.TestCase.testUFFAngleConstraints)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/dev/shm/boegelbot/RDKit/2024.03.3/foss-2023a/rdkit-Release_2024_03_3/Code/ForceField/Wrap/testConstraints.py", line 164, in testUFFAngleConstraints
    self.assertTrue(r == 0)
AssertionError: False is not true

----------------------------------------------------------------------
Ran 12 tests in 0.633s

FAILED (failures=1)
```

detailed stracktrace:

<details>

```
----------
Stacktrace:
 0# Invar::Invariant::toString[abi:cxx11]() const in /dev/shm/boegelbot/RDKit/2024.03.3/foss-2023a/easybuild_obj/lib/libRDKitRDGeneral.so.1
 1# Invar::operator<<(std::ostream&, Invar::Invariant const&) in /dev/shm/boegelbot/RDKit/2024.03.3/foss-2023a/easybuild_obj/lib/libRDKitRDGeneral.so.1
 2# ForceFields::ForceField::minimize(unsigned int, std::vector<RDKit::Snapshot, std::allocator<RDKit::Snapshot> >*, unsigned int, double, double) in /dev/shm/boegelbot/RDKit/2024.03.3/foss-2023a/easybuild_obj/lib/libRDKitForceField.so.1
 3# boost::python::objects::caller_py_function_impl<boost::python::detail::caller<int (ForceFields::PyForceField::*)(int, double, double), boost::python::default_call_policies, boost::mpl::vector5<int, ForceFields::PyForceField&, int, double, double> > >::operator()(_object*, _object*) in /dev/shm/boegelbot/RDKit/2024.03.3/foss-2023a/easybuild_obj/rdkit/ForceField/rdForceField.so
 4# boost::python::objects::function::call(_object*, _object*) const in /project/def-maintainers/boegelbot/rocky9/zen3/software/Boost.Python/1.82.0-GCC-12.3.0/lib/libboost_python311-mt-x64.so.1.82.0
 5# 0x000014988C0A08C8 in /project/def-maintainers/boegelbot/rocky9/zen3/software/Boost.Python/1.82.0-GCC-12.3.0/lib/libboost_python311-mt-x64.so.1.82.0
 6# boost::python::detail::exception_handler::operator()(boost::function0<void> const&) const in /project/def-maintainers/boegelbot/rocky9/zen3/software/Boost.Python/1.82.0-GCC-12.3.0/lib/libboost_python311-mt-x64.so.1.82.0
 7# boost::detail::function::function_obj_invoker2<boost::_bi::bind_t<bool, boost::python::detail::translate_exception<RDKit::FileParseException, void (*)(RDKit::FileParseException const&)>, boost::_bi::list3<boost::arg<1>, boost::arg<2>, boost::_bi::value<void (*)(RDKit::FileParseException const&)> > >, bool, boost::python::detail::exception_handler const&, boost::function0<void> const&>::invoke(boost::detail::function::function_buffer&, boost::python::detail::exception_handler const&, boost::function0<void> const&) in /dev/shm/boegelbot/RDKit/2024.03.3/foss-2023a/easybuild_obj/rdkit/Chem/rdmolfiles.so
 8# boost::detail::function::function_obj_invoker2<boost::_bi::bind_t<bool, boost::python::detail::translate_exception<RDKit::BadFileException, void (*)(RDKit::BadFileException const&)>, boost::_bi::list3<boost::arg<1>, boost::arg<2>, boost::_bi::value<void (*)(RDKit::BadFileException const&)> > >, bool, boost::python::detail::exception_handler const&, boost::function0<void> const&>::invoke(boost::detail::function::function_buffer&, boost::python::detail::exception_handler const&, boost::function0<void> const&) in /dev/shm/boegelbot/RDKit/2024.03.3/foss-2023a/easybuild_obj/rdkit/Chem/rdmolfiles.so
 9# boost::detail::function::function_obj_invoker2<boost::_bi::bind_t<bool, boost::python::detail::translate_exception<RDKit::CIPLabeler::MaxIterationsExceeded, void (*)(RDKit::CIPLabeler::MaxIterationsExceeded const&)>, boost::_bi::list3<boost::arg<1>, boost::arg<2>, boost::_bi::value<void (*)(RDKit::CIPLabeler::MaxIterationsExceeded const&)> > >, bool, boost::python::detail::exception_handler const&, boost::function0<void> const&>::invoke(boost::detail::function::function_buffer&, boost::python::detail::exception_handler const&, boost::function0<void> const&) in /dev/shm/boegelbot/RDKit/2024.03.3/foss-2023a/easybuild_obj/rdkit/Chem/rdCIPLabeler.so
10# boost::detail::function::function_obj_invoker2<boost::_bi::bind_t<bool, boost::python::detail::translate_exception<RDKit::ConformerException, void (*)(RDKit::ConformerException const&)>, boost::_bi::list3<boost::arg<1>, boost::arg<2>, boost::_bi::value<void (*)(RDKit::ConformerException const&)> > >, bool, boost::python::detail::exception_handler const&, boost::function0<void> const&>::invoke(boost::detail::function::function_buffer&, boost::python::detail::exception_handler const&, boost::function0<void> const&) in /dev/shm/boegelbot/RDKit/2024.03.3/foss-2023a/easybuild_obj/rdkit/Chem/rdchem.so
11# 0x0000149807DE039C in /dev/shm/boegelbot/RDKit/2024.03.3/foss-2023a/easybuild_obj/rdkit/Chem/rdchem.so
12# 0x0000149807DE037C in /dev/shm/boegelbot/RDKit/2024.03.3/foss-2023a/easybuild_obj/rdkit/Chem/rdchem.so
13# 0x0000149807DE035C in /dev/shm/boegelbot/RDKit/2024.03.3/foss-2023a/easybuild_obj/rdkit/Chem/rdchem.so
14# 0x0000149807DE033C in /dev/shm/boegelbot/RDKit/2024.03.3/foss-2023a/easybuild_obj/rdkit/Chem/rdchem.so
15# 0x0000149807DE031C in /dev/shm/boegelbot/RDKit/2024.03.3/foss-2023a/easybuild_obj/rdkit/Chem/rdchem.so
16# boost::detail::function::function_obj_invoker2<boost::_bi::bind_t<bool, boost::python::detail::translate_exception<Invar::Invariant, void (*)(Invar::Invariant const&)>, boost::_bi::list3<boost::arg<1>, boost::arg<2>, boost::_bi::value<void (*)(Invar::Invariant const&)> > >, bool, boost::python::detail::exception_handler const&, boost::function0<void> const&>::invoke(boost::detail::function::function_buffer&, boost::python::detail::exception_handler const&, boost::function0<void> const&) in /dev/shm/boegelbot/RDKit/2024.03.3/foss-2023a/easybuild_obj/rdkit/rdBase.so
17# boost::detail::function::function_obj_invoker2<boost::_bi::bind_t<bool, boost::python::detail::translate_exception<KeyErrorException, void (*)(KeyErrorException const&)>, boost::_bi::list3<boost::arg<1>, boost::arg<2>, boost::_bi::value<void (*)(KeyErrorException const&)> > >, bool, boost::python::detail::exception_handler const&, boost::function0<void> const&>::invoke(boost::detail::function::function_buffer&, boost::python::detail::exception_handler const&, boost::function0<void> const&) in /dev/shm/boegelbot/RDKit/2024.03.3/foss-2023a/easybuild_obj/rdkit/rdBase.so
18# boost::detail::function::function_obj_invoker2<boost::_bi::bind_t<bool, boost::python::detail::translate_exception<ValueErrorException, void (*)(ValueErrorException const&)>, boost::_bi::list3<boost::arg<1>, boost::arg<2>, boost::_bi::value<void (*)(ValueErrorException const&)> > >, bool, boost::python::detail::exception_handler const&, boost::function0<void> const&>::invoke(boost::detail::function::function_buffer&, boost::python::detail::exception_handler const&, boost::function0<void> const&) in /dev/shm/boegelbot/RDKit/2024.03.3/foss-2023a/easybuild_obj/rdkit/rdBase.so
19# boost::detail::function::function_obj_invoker2<boost::_bi::bind_t<bool, boost::python::detail::translate_exception<IndexErrorException, void (*)(IndexErrorException const&)>, boost::_bi::list3<boost::arg<1>, boost::arg<2>, boost::_bi::value<void (*)(IndexErrorException const&)> > >, bool, boost::python::detail::exception_handler const&, boost::function0<void> const&>::invoke(boost::detail::function::function_buffer&, boost::python::detail::exception_handler const&, boost::function0<void> const&) in /dev/shm/boegelbot/RDKit/2024.03.3/foss-2023a/easybuild_obj/rdkit/rdBase.so
20# boost::python::handle_exception_impl(boost::function0<void>) in /project/def-maintainers/boegelbot/rocky9/zen3/software/Boost.Python/1.82.0-GCC-12.3.0/lib/libboost_python311-mt-x64.so.1.82.0
21# 0x000014988C09E272 in /project/def-maintainers/boegelbot/rocky9/zen3/software/Boost.Python/1.82.0-GCC-12.3.0/lib/libboost_python311-mt-x64.so.1.82.0
22# _PyObject_MakeTpCall in /project/def-maintainers/boegelbot/rocky9/zen3/software/Python/3.11.3-GCCcore-12.3.0/lib/libpython3.11.so.1.0
23# _PyEval_EvalFrameDefault in /project/def-maintainers/boegelbot/rocky9/zen3/software/Python/3.11.3-GCCcore-12.3.0/lib/libpython3.11.so.1.0
24# 0x000014988CD295AA in /project/def-maintainers/boegelbot/rocky9/zen3/software/Python/3.11.3-GCCcore-12.3.0/lib/libpython3.11.so.1.0
25# 0x000014988CD66CE6 in /project/def-maintainers/boegelbot/rocky9/zen3/software/Python/3.11.3-GCCcore-12.3.0/lib/libpython3.11.so.1.0
26# _PyEval_EvalFrameDefault in /project/def-maintainers/boegelbot/rocky9/zen3/software/Python/3.11.3-GCCcore-12.3.0/lib/libpython3.11.so.1.0
27# 0x000014988CD295AA in /project/def-maintainers/boegelbot/rocky9/zen3/software/Python/3.11.3-GCCcore-12.3.0/lib/libpython3.11.so.1.0
28# _PyObject_FastCallDictTstate in /project/def-maintainers/boegelbot/rocky9/zen3/software/Python/3.11.3-GCCcore-12.3.0/lib/libpython3.11.so.1.0
29# 0x000014988CD52362 in /project/def-maintainers/boegelbot/rocky9/zen3/software/Python/3.11.3-GCCcore-12.3.0/lib/libpython3.11.so.1.0
30# 0x000014988CD24E3B in /project/def-maintainers/boegelbot/rocky9/zen3/software/Python/3.11.3-GCCcore-12.3.0/lib/libpython3.11.so.1.0
31# _PyObject_MakeTpCall in /project/def-maintainers/boegelbot/rocky9/zen3/software/Python/3.11.3-GCCcore-12.3.0/lib/libpython3.11.so.1.0
32# _PyEval_EvalFrameDefault in /project/def-maintainers/boegelbot/rocky9/zen3/software/Python/3.11.3-GCCcore-12.3.0/lib/libpython3.11.so.1.0
33# 0x000014988CD295AA in /project/def-maintainers/boegelbot/rocky9/zen3/software/Python/3.11.3-GCCcore-12.3.0/lib/libpython3.11.so.1.0
34# 0x000014988CD66CE6 in /project/def-maintainers/boegelbot/rocky9/zen3/software/Python/3.11.3-GCCcore-12.3.0/lib/libpython3.11.so.1.0
35# _PyEval_EvalFrameDefault in /project/def-maintainers/boegelbot/rocky9/zen3/software/Python/3.11.3-GCCcore-12.3.0/lib/libpython3.11.so.1.0
36# 0x000014988CD295AA in /project/def-maintainers/boegelbot/rocky9/zen3/software/Python/3.11.3-GCCcore-12.3.0/lib/libpython3.11.so.1.0
37# _PyObject_FastCallDictTstate in /project/def-maintainers/boegelbot/rocky9/zen3/software/Python/3.11.3-GCCcore-12.3.0/lib/libpython3.11.so.1.0
38# _PyObject_Call_Prepend in /project/def-maintainers/boegelbot/rocky9/zen3/software/Python/3.11.3-GCCcore-12.3.0/lib/libpython3.11.so.1.0
39# 0x000014988CDF1260 in /project/def-maintainers/boegelbot/rocky9/zen3/software/Python/3.11.3-GCCcore-12.3.0/lib/libpython3.11.so.1.0
40# _PyObject_MakeTpCall in /project/def-maintainers/boegelbot/rocky9/zen3/software/Python/3.11.3-GCCcore-12.3.0/lib/libpython3.11.so.1.0
41# _PyEval_EvalFrameDefault in /project/def-maintainers/boegelbot/rocky9/zen3/software/Python/3.11.3-GCCcore-12.3.0/lib/libpython3.11.so.1.0
42# 0x000014988CD295AA in /project/def-maintainers/boegelbot/rocky9/zen3/software/Python/3.11.3-GCCcore-12.3.0/lib/libpython3.11.so.1.0
43# 0x000014988CD66CE6 in /project/def-maintainers/boegelbot/rocky9/zen3/software/Python/3.11.3-GCCcore-12.3.0/lib/libpython3.11.so.1.0
44# _PyEval_EvalFrameDefault in /project/def-maintainers/boegelbot/rocky9/zen3/software/Python/3.11.3-GCCcore-12.3.0/lib/libpython3.11.so.1.0
45# 0x000014988CD295AA in /project/def-maintainers/boegelbot/rocky9/zen3/software/Python/3.11.3-GCCcore-12.3.0/lib/libpython3.11.so.1.0
46# _PyObject_FastCallDictTstate in /project/def-maintainers/boegelbot/rocky9/zen3/software/Python/3.11.3-GCCcore-12.3.0/lib/libpython3.11.so.1.0
47# _PyObject_Call_Prepend in /project/def-maintainers/boegelbot/rocky9/zen3/software/Python/3.11.3-GCCcore-12.3.0/lib/libpython3.11.so.1.0
48# 0x000014988CDF1260 in /project/def-maintainers/boegelbot/rocky9/zen3/software/Python/3.11.3-GCCcore-12.3.0/lib/libpython3.11.so.1.0
49# _PyObject_MakeTpCall in /project/def-maintainers/boegelbot/rocky9/zen3/software/Python/3.11.3-GCCcore-12.3.0/lib/libpython3.11.so.1.0
50# _PyEval_EvalFrameDefault in /project/def-maintainers/boegelbot/rocky9/zen3/software/Python/3.11.3-GCCcore-12.3.0/lib/libpython3.11.so.1.0
51# 0x000014988CD295AA in /project/def-maintainers/boegelbot/rocky9/zen3/software/Python/3.11.3-GCCcore-12.3.0/lib/libpython3.11.so.1.0
52# 0x000014988CD66CE6 in /project/def-maintainers/boegelbot/rocky9/zen3/software/Python/3.11.3-GCCcore-12.3.0/lib/libpython3.11.so.1.0
53# _PyEval_EvalFrameDefault in /project/def-maintainers/boegelbot/rocky9/zen3/software/Python/3.11.3-GCCcore-12.3.0/lib/libpython3.11.so.1.0
54# 0x000014988CD295AA in /project/def-maintainers/boegelbot/rocky9/zen3/software/Python/3.11.3-GCCcore-12.3.0/lib/libpython3.11.so.1.0
55# _PyObject_FastCallDictTstate in /project/def-maintainers/boegelbot/rocky9/zen3/software/Python/3.11.3-GCCcore-12.3.0/lib/libpython3.11.so.1.0
56# _PyObject_Call_Prepend in /project/def-maintainers/boegelbot/rocky9/zen3/software/Python/3.11.3-GCCcore-12.3.0/lib/libpython3.11.so.1.0
57# 0x000014988CDF1260 in /project/def-maintainers/boegelbot/rocky9/zen3/software/Python/3.11.3-GCCcore-12.3.0/lib/libpython3.11.so.1.0
58# _PyObject_MakeTpCall in /project/def-maintainers/boegelbot/rocky9/zen3/software/Python/3.11.3-GCCcore-12.3.0/lib/libpython3.11.so.1.0
59# _PyEval_EvalFrameDefault in /project/def-maintainers/boegelbot/rocky9/zen3/software/Python/3.11.3-GCCcore-12.3.0/lib/libpython3.11.so.1.0
60# 0x000014988CD295AA in /project/def-maintainers/boegelbot/rocky9/zen3/software/Python/3.11.3-GCCcore-12.3.0/lib/libpython3.11.so.1.0
61# _PyObject_FastCallDictTstate in /project/def-maintainers/boegelbot/rocky9/zen3/software/Python/3.11.3-GCCcore-12.3.0/lib/libpython3.11.so.1.0
62# 0x000014988CD52362 in /project/def-maintainers/boegelbot/rocky9/zen3/software/Python/3.11.3-GCCcore-12.3.0/lib/libpython3.11.so.1.0
63# 0x000014988CD24E3B in /project/def-maintainers/boegelbot/rocky9/zen3/software/Python/3.11.3-GCCcore-12.3.0/lib/libpython3.11.so.1.0
64# _PyObject_MakeTpCall in /project/def-maintainers/boegelbot/rocky9/zen3/software/Python/3.11.3-GCCcore-12.3.0/lib/libpython3.11.so.1.0
65# _PyEval_EvalFrameDefault in /project/def-maintainers/boegelbot/rocky9/zen3/software/Python/3.11.3-GCCcore-12.3.0/lib/libpython3.11.so.1.0
66# 0x000014988CD295AA in /project/def-maintainers/boegelbot/rocky9/zen3/software/Python/3.11.3-GCCcore-12.3.0/lib/libpython3.11.so.1.0
67# PyEval_EvalCode in /project/def-maintainers/boegelbot/rocky9/zen3/software/Python/3.11.3-GCCcore-12.3.0/lib/libpython3.11.so.1.0
68# 0x000014988CDCDB33 in /project/def-maintainers/boegelbot/rocky9/zen3/software/Python/3.11.3-GCCcore-12.3.0/lib/libpython3.11.so.1.0
69# 0x000014988CDCA3BA in /project/def-maintainers/boegelbot/rocky9/zen3/software/Python/3.11.3-GCCcore-12.3.0/lib/libpython3.11.so.1.0
70# 0x000014988CDEE7E1 in /project/def-maintainers/boegelbot/rocky9/zen3/software/Python/3.11.3-GCCcore-12.3.0/lib/libpython3.11.so.1.0
71# _PyRun_SimpleFileObject in /project/def-maintainers/boegelbot/rocky9/zen3/software/Python/3.11.3-GCCcore-12.3.0/lib/libpython3.11.so.1.0
72# _PyRun_AnyFileObject in /project/def-maintainers/boegelbot/rocky9/zen3/software/Python/3.11.3-GCCcore-12.3.0/lib/libpython3.11.so.1.0
73# Py_RunMain in /project/def-maintainers/boegelbot/rocky9/zen3/software/Python/3.11.3-GCCcore-12.3.0/lib/libpython3.11.so.1.0
74# Py_BytesMain in /project/def-maintainers/boegelbot/rocky9/zen3/software/Python/3.11.3-GCCcore-12.3.0/lib/libpython3.11.so.1.0
75# 0x000014988C829590 in /lib64/libc.so.6
76# __libc_start_main in /lib64/libc.so.6
77# _start in /project/def-maintainers/boegelbot/rocky9/zen3/software/Python/3.11.3-GCCcore-12.3.0/bin/python
```

</details>

**Comment by boegel** [comment]
This seems relevant: https://github.com/rdkit/rdkit/issues/5252

Maybe that fix never actually made it in a release? 🤔

**Comment by branfosj** [comment]
> This seems relevant: [rdkit/rdkit#5252](https://github.com/rdkit/rdkit/issues/5252)
> 
> Maybe that fix never actually made it in a release? 🤔

That fix is in the code. The failure is further on in the test.

**Comment by pavelToman** [comment]
Open discussion: https://github.com/rdkit/rdkit/discussions/7588

**Comment by pavelToman** [comment]
@boegelbot please test @ jsc-zen3

**Review by ocaisa — APPROVED** [review]

**Pull request merged**
