### PR TITLE
{chem}[system/system] MaterialsStudio v2020

### PR DESCRIPTION
**Pull request by Micket**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by Micket** [comment]
Test report by @Micket
**SUCCESS**
Build succeeded for 0 out of 0 (1 easyconfigs in this PR)
vera-c1 - Linux centos linux 7.8.2003, x86_64, Intel Xeon Processor (Skylake), Python 2.7.5
See https://gist.github.com/6b3be45f0e56cec70962eb0f38e4226c for a full test report.

**Comment by migueldiascosta** [comment]
@Micket I based #16573 on this but it seems there is at least one step missing, running `share/Install/Scripts/ConfigureMaterialsStudio.pl`?

(Alternatively, and instead of unpacking and copying the rpms manually, one can run the `install` script non-interactively, but I did need to patch it because it was not accepting `--batch` and `--installroot` together)

**Comment by migueldiascosta** [comment]
@Micket e.g. see https://github.com/easybuilders/easybuild-easyconfigs/pull/16573/commits/e519caf5b8f71d69195e9d7948deded05ed25972. 

Still WIP, it would be good if you could review and/or test.

**Comment by migueldiascosta** [comment]
actually, https://github.com/easybuilders/easybuild-easyconfigs/pull/16573/commits/a42a3c4b61e38973c512eeb8e48435db0b852d28

**Comment by migueldiascosta** [comment]
https://github.com/easybuilders/easybuild-easyconfigs/pull/16573/commits/96bf0b6974990a99e670e1e41ac93decdfff36fb is probably clearer and cleaner

**Comment by boegel** [comment]
Maybe we should just close this, since it's superseded by #16573 ?

@Micket Thoughts?

**Pull request closed without merging**
