### PR TITLE
{chem}[intel/2017b] CASTEP v18.1

### PR DESCRIPTION
**Pull request by dquigley-warwick**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by dquigley-warwick** [comment]
Test report by @dquigley-warwick
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
brigitte.csc.warwick.ac.uk - Linux centos linux 7.5.1804, Intel(R) Xeon(R) CPU E5-2620 v3 @ 2.40GHz, Python 2.7.5
See https://gist.github.com/e22aedf234d435c42e77c100d29b155f for a full test report.

**Comment by dquigley-warwick** [comment]
Check's are obviously failing because the source code is not available for automated download without a license to use the software. This will need test reports from other licensed sites if anyone can contribute them.

**Comment by verdurin** [comment]
Hi @dquigley-warwick and welcome to EasyBuild.
I can't test this because I'm not already registered on CCPForge and they are not registering new users, given that it is closing at the end of the year.
Has CASTEP perhaps migrated to hosting elsewhere?

**Comment by verdurin** [comment]
@dquigley-warwick looking at http://www.castep.org/CASTEP/GettingCASTEP - maybe not yet.

**Comment by dquigley-warwick** [comment]
@verdurin - indeed. It may be best to sit on this until the licensing is sorted out and new hosting arrangements are in place. However the source tarball will still be behind some kind of login for licensed users only.

**Comment by boegel** [comment]
@dquigley-warwick Any updates on this?

**Comment by dquigley-warwick** [comment]
@boegel nothing that I'm aware of yet. However I'm sure any new licence will be free only to UK-based academics. I doubt we'll ever get to a point where Travis CI builds will have access to the source.

**Comment by dquigley-warwick** [comment]
There is now an update on licensing for CASTEP. Any academic user (UK or otherwise) should be able to get access to the source, but there is some paperwork involved. 

http://www.castep.org/CASTEP/GettingCASTEP

(18.1 is also no longer the latest veresion).

**Comment by boegel** [comment]
@dquigley-warwick Given the not-so-easy availability of the source code, and the fact that this is using an ancient toolchain (which is now deprecated, see https://docs.easybuild.io/en/latest/Deprecated-easyconfigs.html#deprecated-toolchains), I'll go ahead and close this PR.

If adding support for CASTEP would still be useful, please open a new PR with a more recent toolchain.

**Pull request closed without merging**
