### PR TITLE
{tools}[fosscuda/2019b] Horovod v0.20.0 w/ Python 3.7.4 + TensorFlow v2.3.0

### PR DESCRIPTION
**Pull request by Flamefire**
(created using `eb --new-pr`)

- [x] Requires ~~#11040~~

### CODE REVIEW

**Comment by boegel** [comment]
@boegelbot please test @ generoso

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
node3408.kirlia.os - Linux centos linux 7.8.2003, x86_64, Intel(R) Xeon(R) Gold 6240 CPU @ 2.60GHz (cascadelake), Python 2.7.5
See https://gist.github.com/03019b1d8bbe3bc2ec1947824f8a328d for a full test report.

**Comment by Flamefire** [comment]
Synced with master to fix CI

**Comment by boegel** [comment]
@Flamefire I had already restarted the checks in CI, which should be sufficient to make the tests pass, but fine ;)

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
node2636.swalot.os - Linux centos linux 7.8.2003, x86_64, Intel(R) Xeon(R) CPU E5-2660 v3 @ 2.60GHz (haswell), Python 2.7.5
See https://gist.github.com/cd68b28e0feb2dca6f43ab4ecc6e8636 for a full test report.

**Review by boegel — APPROVED** [review]
lgtm

**Comment by boegel** [comment]
Going in, thanks @Flamefire!

**Pull request merged**
