### PR TITLE
{mpi}[iccifort/2020.0.166] impi v2019.6.166

### PR DESCRIPTION
**Pull request by bartoldeman**
(created using `eb --new-pr`)

edit: requires https://github.com/easybuilders/easybuild-easyblocks/pull/1896

### CODE REVIEW

**Comment by bartoldeman** [comment]
Test report by @bartoldeman
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
build-node.computecanada.ca - Linux centos linux 7.7.1908, Intel Xeon Processor (Skylake, IBRS), Python 3.7.5
See https://gist.github.com/b5c3a03e39e8a7f72468917d8c397008 for a full test report.

**Comment by bartoldeman** [comment]
Needs https://github.com/easybuilders/easybuild-easyblocks/pull/1896

**Comment by boegel** [comment]
@bartoldeman Any idea if there's a 2020 release of Intel MPI coming up too?

**Comment by bartoldeman** [comment]
I have no idea but for some reason this impi is part of the 2020 MPI cluster release and you can see that from the directories inside it:
```
$ ls $EBROOTIMPI |cat
benchmarks
bin
binding
compilers_and_libraries
compilers_and_libraries_2020
compilers_and_libraries_2020.0.166
conda_channel
documentation_2020
easybuild
imb
intel64
man
parallel_studio_xe_2020
parallel_studio_xe_2020.0.088
samples_2020
test
uninstall
uninstall.sh
```
it has the `166` in common with the 2020.0 (or 19.1.0.166 - from icc itself) compiler too.

**Comment by bartoldeman** [comment]
Test report by @bartoldeman
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in this PR)
build-node.computecanada.ca - Linux centos linux 7.7.1908, Intel Xeon Processor (Skylake, IBRS), Python 3.7.5
See https://gist.github.com/6de159f0b1d938843af3c082ac64f487 for a full test report.

**Comment by boegel** [comment]
> I have no idea but for some reason this impi is part of the 2020 MPI cluster release

Intel and sane software versioning, they'll never agree...

**Comment by boegel** [comment]
Test report by @boegel
**FAILED**
Build succeeded for 0 out of 2 (2 easyconfigs in this PR)
node3168.skitty.os - Linux centos linux 7.7.1908, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz, Python 3.6.8
See https://gist.github.com/85122f15482e9b958e2e94ae7e8e8e21 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**FAILED**
Build succeeded for 8 out of 10 (2 easyconfigs in this PR)
node2412.golett.os - Linux centos linux 7.7.1908, Intel(R) Xeon(R) CPU E5-2680 v3 @ 2.50GHz, Python 2.7.5
See https://gist.github.com/bbe1da3fd8640de2525d35d51b0e3784 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in this PR)
node3168.skitty.os - Linux centos linux 7.7.1908, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz, Python 3.6.8
See https://gist.github.com/0509a000992ecd89efb3e219b969796d for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in this PR)
node2412.golett.os - Linux centos linux 7.7.1908, Intel(R) Xeon(R) CPU E5-2680 v3 @ 2.50GHz, Python 2.7.5
See https://gist.github.com/a03aec4709a7803b439c3106b59ba6f2 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in this PR)
generoso - Linux centos linux 7.6.1810, Intel(R) Xeon(R) CPU E5-2660 v4 @ 2.00GHz, Python 3.6.8
See https://gist.github.com/b9c74713d0d0f8ca31951c71fc545e4e for a full test report.

**Comment by boegel** [comment]
Going in, thanks @bartoldeman!

**Pull request merged**
