### PR TITLE
{bio}[foss/2018b] Trim_Galore v0.6.1

### PR DESCRIPTION
**Pull request by sassy-crick**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by migueldiascosta** [comment]
Test report by @migueldiascosta
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
grc-cluster1 - Linux centos 6.10, Intel(R) Xeon(R) CPU E5-2640 0 @ 2.50GHz, Python 2.7.14
See https://gist.github.com/c76ddbec4c4998ddb50980bfb13c9daa for a full test report.

**Comment by migueldiascosta** [comment]
@sassy-crick shouldn't `Perl` be a dependency then?

**Comment by sassy-crick** [comment]
@migueldiascosta 
We had some discussion around that here:
https://github.com/easybuilders/easybuild-easyconfigs/pull/7815
I basically took the Trim_Galore-0.5.0-foss-2018b.eb build file but instead of doing this:
postinstallcmds = [
    "chmod +x %(installdir)s/%(namelower)s",
    "sed -i '1 i#!/usr/bin/env perl' %(installdir)s/%(namelower)s",
]
I simply added a patch file. Again, this goes back to the Trim_Galore-0.6.0.eb I submitted. 
Happy to remove the patch and include the script as above. 
However, the already existing build file does not have a perl dependency in it at all. 
I have no opinion here and leave that to those who are more familiar with Easybuild to advice me here. 
:-)

**Comment by boegel** [comment]
@sassy-crick This one can be closed, already handled via #8279?

**Pull request closed without merging**
