### PR TITLE
{bio}[foss/2019b] medaka v1.1.3 w/ Python 3.7.4

### PR DESCRIPTION
**Pull request by boegel**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by boegel** [comment]
@boegelbot please test @ generoso

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
node3109.skitty.os - Linux centos linux 7.8.2003, x86_64, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz, Python 3.6.8
See https://gist.github.com/27ab7433fc0fc66b9ff8002300163c8c for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
node2476.golett.os - Linux centos linux 7.8.2003, x86_64, Intel(R) Xeon(R) CPU E5-2680 v3 @ 2.50GHz (haswell), Python 2.7.5
See https://gist.github.com/60ac30cc81e25e0d6160f1798e6cd42d for a full test report.

**Comment by smoors** [comment]
Test report by @smoors
**FAILED**
Build succeeded for 11 out of 13 (1 easyconfigs in total)
node201.hydra.os - Linux centos linux 7.7.1908, x86_64, Intel(R) Xeon(R) CPU E5-2680 v4 @ 2.40GHz (broadwell), Python 2.7.5
See https://gist.github.com/313878e861823ca7df5ebb9bde45f536 for a full test report.

**Comment by boegel** [comment]
@smoors You need to reinstall `pybind11-2.4.3-GCCcore-8.3.0-Python-3.7.4.eb` (because of the changes in #11091)

**Review by Micket — APPROVED** [review]
lgtm

**Comment by Micket** [comment]
Test report by @Micket
**FAILED**
Build succeeded for 6 out of 8 (1 easyconfigs in this PR)
vera-c1 - Linux centos linux 7.8.2003, x86_64, Intel Xeon Processor (Skylake), Python 2.7.5
See https://gist.github.com/55cf4dbd5bab7c744ca3f024a3f6757a for a full test report.

**Comment by Micket** [comment]
Ah, rebuild with updated easyblock, sigh

**Comment by smoors** [comment]
only because pip check will find it?
that's it, im moving to spock

**Comment by smoors** [comment]
Test report by @smoors
**SUCCESS**
Build succeeded for 13 out of 13 (1 easyconfigs in total)
node378.hydra.os - Linux centos linux 7.7.1908, x86_64, Intel(R) Xeon(R) Gold 6148 CPU @ 2.40GHz (skylake_avx512), Python 2.7.5
See https://gist.github.com/bad9198136b6016d94ae3d0928a5e78f for a full test report.

**Review by smoors — APPROVED** [review]
lgtm

**Comment by smoors** [comment]
Going in, thanks @boegel!

**Comment by smoors** [comment]
Going in, thanks @boegel!

**Comment by boegel** [comment]
> only because pip check will find it?
> that's it, im moving to spock

Blame `pip` or `pybind11` or `CMake`, in this case...

**Pull request merged**
