### PR TITLE
update cuDNN 7.6.4.38 easyconfigs to support both x86_64 and ppc64le

### PR DESCRIPTION
**Pull request by branfosj**
(created using `eb --new-pr`)

This is to show that the change I propose in https://github.com/easybuilders/easybuild-easyblocks/pull/1855 works.

### CODE REVIEW

**Comment by branfosj** [comment]
Test report by @branfosj
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
bear-pg0305u03a.bear.cluster - Linux RHEL 7.6, 8335-GTX, Python 2.7.5
See https://gist.github.com/ba2214a7e16e87d1848ab7dda4c4cab4 for a full test report.

**Comment by branfosj** [comment]
Test report by @branfosj
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
bear-pg0212u15b.bear.cluster - Linux centos linux 7.6.1810, Intel(R) Xeon(R) CPU E5-2640 v4 @ 2.40GHz, Python 2.7.5
See https://gist.github.com/8d187d2465e0557b1293758ad1fe6042 for a full test report.

**Comment by Flamefire** [comment]
:+1: While you are at it, care to provide the same for NCCL? Name for x86 is `nccl_2.4.2-1+cuda10.1_x86_64.txz` though. Hooray for consistency, we now have `['', 'x64', 'x86_64' ]`...

**Comment by branfosj** [comment]
I've just added the equivaent for NCCL in https://github.com/easybuilders/easybuild-easyconfigs/pull/9336

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
generoso - Linux centos linux 7.6.1810, Intel(R) Xeon(R) CPU E5-2660 v4 @ 2.00GHz, Python 3.6.8
See https://gist.github.com/aabf4bfa412022654c978171c697b5ea for a full test report.

**Comment by branfosj** [comment]
Test report by @branfosj
**FAILED**
Build succeeded for 1 out of 2 (2 easyconfigs in this PR)
bear-pg0305u03a.bear.cluster - Linux RHEL 7.6, 8335-GTX, Python 2.7.5
See https://gist.github.com/088b4ed161592c4ddd9e2c22efc45b13 for a full test report.

**Comment by branfosj** [comment]
The failed test report was on:
```
== 2019-11-20 13:31:55,027 build_log.py:164 ERROR EasyBuild crashed with an error (at easybuild/base/exceptions.py:124 in __init__): utility.c(2245):ERROR:50: Cannot open file '/rds/bear-apps/devel/2019b/branfosj-eb-1/EL7/EL7-power9/modules//numlib/cuDNN/7.6.4.38-gcccuda-2019b' for 'reading' (at easybuild/tools/modules.py:783 in run_module)
```
which is odd. I'll set the test off again.

**Comment by branfosj** [comment]
Test report by @branfosj
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in this PR)
bear-pg0212u15b.bear.cluster - Linux centos linux 7.6.1810, Intel(R) Xeon(R) CPU E5-2640 v4 @ 2.40GHz, Python 2.7.5
See https://gist.github.com/69a170d7db1052ae0e77697e45a42e7b for a full test report.

**Comment by branfosj** [comment]
Test report by @branfosj
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in this PR)
bear-pg0305u03a.bear.cluster - Linux RHEL 7.6, 8335-GTX, Python 2.7.5
See https://gist.github.com/ae4d51f9184ef3cea9af4c6ed3854b77 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in this PR)
node2406.golett.os - Linux centos linux 7.7.1908, Intel(R) Xeon(R) CPU E5-2680 v3 @ 2.50GHz, Python 2.7.5
See https://gist.github.com/64ba3cf72775f85ddedb1492bab4c3b4 for a full test report.

**Comment by boegel** [comment]
Going in, thanks @branfosj!

**Pull request merged**
