### PR TITLE
{bio}[foss/2018b] pizzly v0.37.3

### PR DESCRIPTION
**Pull request by SethosII**
(created using `eb --new-pr`)

The install target patch is currently not in a release but in the master branch.

### CODE REVIEW

**Comment by verdurin** [comment]
Test report by @verdurin
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
rescomp2 - Linux centos linux 7.3.1611, Intel(R) Xeon(R) Gold 6126 CPU @ 2.60GHz, Python 2.7.5
See https://gist.github.com/e7a39a457900b774b67cc690602f3320 for a full test report.

**Comment by verdurin** [comment]
@SethosII Looks good but could you provide some test reports too?

**Comment by SethosII** [comment]
Test report by @SethosII
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
ribnode015 - Linux ubuntu 18.04, Intel(R) Xeon(R) CPU           E5645  @ 2.40GHz, Python 2.7.15rc1
See https://gist.github.com/54beeb8f6f3ac9ed23b5dd6b7c22d2a8 for a full test report.

**Comment by SethosII** [comment]
@verdurin Never looked into this before but the Github integration makes this fairly easy :) I will do so in the future.

**Comment by verdurin** [comment]
Going in, thanks @SethosII!

**Pull request merged**
