### PR TITLE
{tools}[foss/2023a] rhandsontable v0.3.8 w/ R 4.3.2

### PR DESCRIPTION
**Pull request by PetrKralCZ**

### CODE REVIEW

**Comment by PetrKralCZ** [comment]
@boegelbot please test @ generoso

**Comment by PetrKralCZ** [comment]
@boegelbot please test @ jsc-zen3

**Review by smoors — APPROVED** [review]
lgtm

**Comment by smoors** [comment]
Going in, thanks @PetrKralCZ!

**Pull request merged**
