### PR TITLE
CLHEP: Remove superflous configopts and add sanity-checks/checksums

### PR DESCRIPTION
**Pull request by Flamefire**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by Flamefire** [comment]
Test report by @Flamefire
**SUCCESS**
Build succeeded for 4 out of 4 (4 easyconfigs in total)
taurusi6605.taurus.hrsk.tu-dresden.de - Linux RHEL 7.9, x86_64, Intel(R) Xeon(R) CPU E5-2680 v3 @ 2.50GHz (haswell), Python 2.7.5
See https://gist.github.com/b5fb1d5cfb53be52ab4d0aeeed3ec002 for a full test report.

**Review by Micket — APPROVED** [review]
lgtm

**Comment by Micket** [comment]
Test report by @Micket
**SUCCESS**
Build succeeded for 4 out of 4 (4 easyconfigs in total)
vera-c1 - Linux centos linux 7.9.2009, x86_64, Intel Xeon Processor (Skylake), Python 3.6.8
See https://gist.github.com/1ca27c5245ac7fe2c31d4b3234655e56 for a full test report.

**Review by Micket — APPROVED** [review]
(apparently i forgot to press approve)

**Comment by Micket** [comment]
Going in, thanks @Flamefire!

**Pull request merged**
