### PR TITLE
{math}[system/system] Gurobi v9.0.0

### PR DESCRIPTION
**Pull request by boegel**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
node3112.skitty.os - Linux centos linux 7.7.1908, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz, Python 3.6.8
See https://gist.github.com/05daf0d038884a7d5518a1dbe76e1c3a for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
node2536.golett.os - Linux centos linux 7.7.1908, Intel(R) Xeon(R) CPU E5-2680 v3 @ 2.50GHz, Python 2.7.5
See https://gist.github.com/cf1ec44f0427f05c662bb3c8717bb399 for a full test report.

**Comment by verdurin** [comment]
Test report by @verdurin
**FAILED**
Build succeeded for 0 out of 1 (1 easyconfigs in this PR)
easybuild.novalocal - Linux centos linux 7.7.1908, Intel Xeon Processor (Skylake, IBRS), Python 2.7.5
See https://gist.github.com/afcd0393a2f89237a960cb4e37cae84a for a full test report.

**Comment by verdurin** [comment]
@boegel What is the licensing situation here? Is the "free trial" sufficient for a test build?

**Comment by boegel** [comment]
@verdurin I'm not sure if it is, I guess it only would be if the SHA256 checksum is identical too...

Since it's a fairly straightforward binary installation, I don't think that this PR should be blocked if whoever is testing it doesn't have access to a Gurobi license. We have other easyconfigs merged for which only some people have a license (see `Amber` for example).

**Comment by migueldiascosta** [comment]
Test report by @migueldiascosta
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
generoso - Linux centos linux 7.6.1810, Intel(R) Xeon(R) CPU E5-2660 v4 @ 2.00GHz, Python 3.6.8
See https://gist.github.com/54d573b6ea9e16ccdad9891296c623f0 for a full test report.

**Comment by migueldiascosta** [comment]
well, in order for `gurobi_cl --help` to run it's actually enough for the license file to exist, so maybe the easyconfig can create an empty one if it doesn't?

**Comment by boegel** [comment]
@migueldiascosta I don't think it's a good idea to let an easyconfig (or even easyblock) create an empty license file...

If the license file doesn't exist, you'll get a pretty clear error.

For testing purposes (like on `generoso`), we can create an empty license file manually?

**Comment by smoors** [comment]
Test report by @smoors
**FAILED**
Build succeeded for 0 out of 1 (1 easyconfigs in this PR)
node366.hydra.os - Linux centos linux 7.7.1908, Intel(R) Xeon(R) Gold 6148 CPU @ 2.40GHz, Python 2.7.5
See https://gist.github.com/5a76ed6b114612e2d8ac6000825179c0 for a full test report.

**Comment by boegel** [comment]
@smoors Try again after creating an empty `$HOME/licenses/Gurobi/gurobi.lic`?

**Comment by smoors** [comment]
Test report by @smoors
**FAILED**
Build succeeded for 0 out of 1 (1 easyconfigs in this PR)
node374.hydra.os - Linux centos linux 7.7.1908, Intel(R) Xeon(R) Gold 6148 CPU @ 2.40GHz, Python 2.7.5
See https://gist.github.com/1844e24f6ab21ee68b2456a4cee3dab4 for a full test report.

**Comment by smoors** [comment]
we have a license file for Gurobi, but it was in a different location..

**Comment by smoors** [comment]
Test report by @smoors
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
node374.hydra.os - Linux centos linux 7.7.1908, Intel(R) Xeon(R) Gold 6148 CPU @ 2.40GHz, Python 2.7.5
See https://gist.github.com/e5d642136b69e9ef79b8295b5435f053 for a full test report.

**Comment by smoors** [comment]
Going in, thanks @boegel!

**Pull request merged**
