### PR TITLE
Update libvdwxc webpage as old URL has been taken over by evildoers.

### PR DESCRIPTION
**Pull request by schiotz**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by schiotz** [comment]
Updated the project webpage of libvdwxc, as the project webpage has moved, and somebody has taken over the old domain and put up a mock copy of the old webpage with a link to a financial scam inserted.

Fortunately, the dowload URL is not affected as it is on another domain (launchpad.net), and anyway the SHA hash would have protected us.

CC: @askhl

**Review by Micket — APPROVED** [review]
lgtm

**Comment by Micket** [comment]
I'm not going to force a build triggered for this, since it's just metadata

**Comment by askhl** [comment]
Thanks a lot for taking care of this.

Am Mi., 6. Nov. 2024 um 19:01 Uhr schrieb Mikael Öhman <
***@***.***>:

**Pull request merged**
