### PR TITLE
{bio}[foss/2018b] OpenMS v2.4.0

### PR DESCRIPTION
**Pull request by tstrempel**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by lexming** [comment]
Test report by @lexming
**FAILED**
Build succeeded for 8 out of 9 (6 easyconfigs in this PR)
node373.hydra.os - Linux centos linux 7.7.1908, x86_64, Intel(R) Xeon(R) Gold 6148 CPU @ 2.40GHz, Python 2.7.5
See https://gist.github.com/e11fcc0bd4ee6b661e2863e953dbac54 for a full test report.

**Comment by lexming** [comment]
Test report by @lexming
**FAILED**
Build succeeded for 8 out of 9 (6 easyconfigs in this PR)
node122.hydra.os - Linux centos linux 7.7.1908, x86_64, Intel(R) Xeon(R) CPU E5-2680 v2 @ 2.80GHz, Python 2.7.5
See https://gist.github.com/012f80a4e19702c2acf5003f82a7d983 for a full test report.

**Comment by tstrempel** [comment]
I have no clue, why it doesn't build with Python 3.6, but with 2.7...

**Comment by lexming** [comment]
@tstrempel my failed tests were caused by `LIBSVM`, I'm running further tests

**Comment by tstrempel** [comment]
Now it (somehow) works, I removed an unused configopt.

**Comment by lexming** [comment]
@tstrempel I got OpenMS built and installed on my side. The issue with `LIBSVM` was due to a very old installation on our system and was easily fixed. I hit other issues though. I made PR https://github.com/tstrempel/easybuild-easyconfigs/pull/1 into this PR with the following changes
* Convert the easyconfig to `CMakeMake`: the only thing needed from `seqan` are the header files at build time. Therefore, there is no need to install them in the system. We can just download the sources into `builddir`, use them and be gone.
* Disable building the documentation of OpenMS as it needs an active X screen
* Disable building the tutorials as those need LaTeX
* Make the submission of stats to remote servers and update checks and opt-in feature (disabled by default)
* Adding the extra `CPATHS` to coin-or packages is a good idea. My PR updates those packages removing the explicit include paths in `configopts` as well.
Please check it out and let me know if you agree with those changes.

**Comment by lexming** [comment]
BTW `python` was not used at all, so there is nothing to do on that regard as far as I can tell

**Comment by tstrempel** [comment]
@lexming Thanks for the help, finally it is done.

**Comment by lexming** [comment]
Test report by @lexming
**FAILED**
Build succeeded for 8 out of 9 (9 easyconfigs in this PR)
node128.hydra.os - Linux centos linux 7.7.1908, x86_64, Intel(R) Xeon(R) CPU E5-2680 v2 @ 2.80GHz, Python 2.7.5
See https://gist.github.com/f62e4d3a10a12597831123b1021dc0d6 for a full test report.

**Comment by lexming** [comment]
Test report by @lexming
**SUCCESS**
Build succeeded for 9 out of 9 (9 easyconfigs in this PR)
node377.hydra.os - Linux centos linux 7.7.1908, x86_64, Intel(R) Xeon(R) Gold 6148 CPU @ 2.40GHz, Python 2.7.5
See https://gist.github.com/69ba168c0292717cf92dd9c031012a15 for a full test report.

**Comment by lexming** [comment]
Test report by @lexming
**SUCCESS**
Build succeeded for 9 out of 9 (9 easyconfigs in this PR)
node126.hydra.os - Linux centos linux 7.7.1908, x86_64, Intel(R) Xeon(R) CPU E5-2680 v2 @ 2.80GHz, Python 2.7.5
See https://gist.github.com/ca33fbbddb4104686a559fb8cb2db4ef for a full test report.

**Comment by lexming** [comment]
Going in, thanks @tstrempel !

**Pull request merged**
