### PR TITLE
add missing libiconv build dep in recent Doxygen easyconfigs

### PR DESCRIPTION
**Pull request by boegel**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 8 out of 8 (8 easyconfigs in this PR)
node3108.skitty.os - Linux centos linux 7.8.2003, x86_64, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz (skylake_avx512), Python 3.6.8
See https://gist.github.com/12a7c2da2b279783d078fe073ccafe55 for a full test report.

**Comment by smoors** [comment]
EB_ARGS="--force --debug" @boegelbot please test @ generoso

**Comment by smoors** [comment]
Test report by @smoors
**FAILED**
Build succeeded for 7 out of 21 (8 easyconfigs in this PR)
node254.hydra.os - Linux centos linux 7.7.1908, x86_64, Intel(R) Xeon(R) CPU E5-2683 v4 @ 2.10GHz (broadwell), Python 2.7.5
See https://gist.github.com/317e38d78c2e51442172c34b1f20a644 for a full test report.

**Comment by smoors** [comment]
Test report by @smoors
**SUCCESS**
Build succeeded for 7 out of 7 (6 easyconfigs in this PR)
node254.hydra.os - Linux centos linux 7.7.1908, x86_64, Intel(R) Xeon(R) CPU E5-2683 v4 @ 2.10GHz (broadwell), Python 2.7.5
See https://gist.github.com/553bede6a03c2387a7e076ff0f2f26a7 for a full test report.

**Comment by smoors** [comment]
build of Doxygen-1.8.14-GCCcore-7.2.0.eb failed due to failing build of GCCcore-7.2.0.eb,
which should be handled in a different PR.

**Review by smoors — APPROVED** [review]
lgtm

**Comment by smoors** [comment]
Going in, thanks @boegel!

**Comment by boegel** [comment]
@smoors GCC 7.2.0 is not compatible anymore with CentOS 8, so that's probably a lost cause...

**Pull request merged**
