### PR TITLE
{numlib}[system/system] imkl v2024.0.0, imkl-FFTW v2024.0.0, intel v2023.11

### PR DESCRIPTION
**Pull request by bartoldeman**
(created using `eb --new-pr`)
- [x] #19314

### CODE REVIEW

**Comment by bartoldeman** [comment]
Needs:
#19314
easybuilders/easybuild-easyblocks#3042

**Comment by bartoldeman** [comment]
@boegelbot please test @ generoso
EB_ARGS="--include-easyblocks-from-pr 3039,3042"

**Comment by bartoldeman** [comment]
@boegelbot please test @ generoso
EB_ARGS="--include-easyblocks-from-pr 3042"

**Comment by bartoldeman** [comment]
Test report by @bartoldeman
**SUCCESS**
Build succeeded for 3 out of 3 (3 easyconfigs in total)
build-node2.computecanada.ca - Linux CentOS Linux 7 (Core), x86_64, Intel Xeon Processor (Skylake, IBRS) (skylake_avx512), Python 3.11.4
See https://gist.github.com/bartoldeman/545c925058a953445d6edcd051fb3dff for a full test report.

**Comment by bartoldeman** [comment]
I'm not sure why `--include-easyblocks-from-pr 3039,3042` didn't work but once 3039 was merged, it's working with
`--include-easyblocks-from-pr 3042` so that's good.

**Comment by bartoldeman** [comment]
@boegelbot please test @ jsc-zen2
EB_ARGS="--include-easyblocks-from-pr 3042"

**Comment by boegel** [comment]
Test report by @boegel
Using easyblocks from PR(s) https://github.com/easybuilders/easybuild-easyblocks/pull/3042
**FAILED**
Build succeeded for 1 out of 5 (3 easyconfigs in total)
node3109.skitty.os - Linux RHEL 8.8, x86_64, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz (skylake_avx512), Python 3.6.8
See https://gist.github.com/boegel/19429b8e0215969b6d180d8b18a75806 for a full test report.

**Comment by bartoldeman** [comment]
@boegel `no file found at 'mpi/2021.11.0/bin/mpiicpc'` probably means you are using an outdated `intelbase.py` as it should be `2021.11`

**Comment by boegel** [comment]
> @boegel `no file found at 'mpi/2021.11.0/bin/mpiicpc'` probably means you are using an outdated `intelbase.py` as it should be `2021.11`

I was using an old `impi.py` easyblock, indeed, that explains the problem with installing `impi/2021.11.0-intel-compilers-2024.0.0`

**Comment by boegel** [comment]
Test report by @boegel
Using easyblocks from PR(s) https://github.com/easybuilders/easybuild-easyblocks/pull/3042
**SUCCESS**
Build succeeded for 5 out of 5 (3 easyconfigs in total)
node3109.skitty.os - Linux RHEL 8.8, x86_64, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz (skylake_avx512), Python 3.6.8
See https://gist.github.com/boegel/cb85e9eb51937ac181491bc47c4d1a9f for a full test report.

**Review by boegel — APPROVED** [review]
lgtm

**Comment by boegel** [comment]
Going in, thanks @bartoldeman!

**Pull request merged**
