### PR TITLE
update SCOTCH 6.0.5 easyconfigs in-place to 6.0.6 to fix wrong download URL

### PR DESCRIPTION
**Pull request by boegel**
fix for problem reported by @smoors in #7154

see also enhanced `SCOTCH` easyblock in ~~https://github.com/easybuilders/easybuild-easyblocks/pull/1580~~

WIP since needs thorough testing (which is under way); test reports welcome!

### CODE REVIEW

**Comment by smoors** [comment]
Test report by @smoors
**FAILED**
Build succeeded for 41 out of 45 (11 easyconfigs in this PR)
nic420 - Linux centos linux 7.5.1804, Intel(R) Xeon(R) Gold 6148 CPU @ 2.40GHz, Python 2.7.5
See https://gist.github.com/f305a069642fa1e9312d53af6542dec6 for a full test report.

**Comment by boegel** [comment]
@smoors:

* `Trilinos` failed because the required source tarball could not be downloaded because of `https` issues, you may need to download it manually?

* similar issue for `SUNDIALS`

* `patchelf` failed with `bootstrap.sh: line 2: autoreconf: command not found`, that looks like a missing build dep on `Autotools`, are you up for opening a PR to fix that?

**Comment by smoors** [comment]
sure, will be for next week, though.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 11 out of 11 (11 easyconfigs in this PR)
node2726.swalot.os - Linux centos linux 7.5.1804, Intel(R) Xeon(R) CPU E5-2660 v3 @ 2.60GHz, Python 2.7.5
See https://gist.github.com/da2e2aea77521fd8c1173d03eb70abee for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 12 out of 12 (11 easyconfigs in this PR)
node2079.delcatty.os - Linux centos linux 7.5.1804, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.7.5
See https://gist.github.com/eaf8d94268a1f0f16a88e294587da2bb for a full test report.

**Comment by verdurin** [comment]
@smoors ping on the fixes for this one?

**Comment by smoors** [comment]
fix for Trilinos: #7197 
fix for patchelf: #7175 
downloading SUNDIALS appears work again

**Comment by smoors** [comment]
Test report by @smoors
**FAILED**
Build succeeded for 8 out of 13 (11 easyconfigs in this PR)
nic5 - Linux centos linux 7.5.1804, AMD Opteron(tm) Processor 6134, Python 2.7.5
See https://gist.github.com/e7afca71c3f76eafad0ecba0178b8ddd for a full test report.

**Comment by smoors** [comment]
I think I have been mixing AMD and intel builds. you can ignore the last report, I will try again.

**Comment by smoors** [comment]
Test report by @smoors
**FAILED**
Build succeeded for 11 out of 13 (11 easyconfigs in this PR)
nic400 - Linux centos linux 7.5.1804, Intel(R) Xeon(R) Gold 6148 CPU @ 2.40GHz, Python 2.7.5
See https://gist.github.com/50743e863b8ff012cae2e440e1c68bc1 for a full test report.

**Comment by smoors** [comment]
seems to be a memory issue, will try once more.

**Comment by migueldiascosta** [comment]
with current `develop` here, `--from-pr` for this PR fails with 

```
ERROR: Couldn't find path to patched file /dev/shm/tmp/eb-FlHmx/files_pr7159/s/SCOTCH/SCOTCH-6.0.6-foss-2018a.eb
``` 

It works in `3.7.1` though...

**Comment by boegel** [comment]
@migueldiascosta Problem should be fixed with https://github.com/easybuilders/easybuild-framework/pull/2680

**Comment by migueldiascosta** [comment]
Going in, thanks @boegel!

**Pull request merged**
