### PR TITLE
{numlib,toolchain,tools}[iimpi/2024.06,intel/2024.06,system/system] imkl-FFTW v2024.2.0, intel v2024.06, HPL v2.3

### PR DESCRIPTION
**Pull request by bartoldeman**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by bartoldeman** [comment]
Needs #20919 and a framework PR (TBD)

**Comment by bartoldeman** [comment]
Framework PR: easybuilders/easybuild-framework#4570

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 3 out of 3 (3 easyconfigs in total)
node3158.skitty.os - Linux RHEL 8.8, x86_64, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz, Python 3.6.8
See https://gist.github.com/boegel/a23552469ece91bddc7fb7c4ae8bca8b for a full test report.

**Comment by boegel** [comment]
@boegelbot please test @ generoso

**Comment by boegel** [comment]
@boegelbot please test @ jsc-zen3

**Review by boegel — APPROVED** [review]
lgtm

**Comment by boegel** [comment]
Going in, thanks @bartoldeman!

**Pull request merged**
