### PR TITLE
add missing groff build dependency for Perl 5.30.0 and 5.32.0

### LINKED ISSUE #10552: Perl-5.30.0-GCCcore-8.3.0.eb fails in the sanity check stage
Perl (Perl-5.30.0-GCCcore-8.3.0.eb) fails in the sanity check stage complaining about a non-empty directory.

```
== installing extension Object::InsideOut 4.05 (294/296)...
== installing extension Thread::Queue 3.13 (295/296)...
== installing extension Time::HiRes 1.9760 (296/296)...
== restore after iterating...
== postprocessing...
== sanity checking...
== FAILED: Installation ended unsuccessfully (build directory: /app/build/Perl/5.30.0/GCCcore-8.3.0): build failed (first 300 chars): Sanity check failed: no (non-empty) directory found at 'man' in /app/software/Perl/5.30.0-GCCcore-8.3.0 (took 21 min 44 sec)
== Results of the build can be found in the log file(s) /tmp/eb-tItOil/easybuild-Perl-5.30.0-20200430.215813.QWMtZ.log
ERROR: Build of /app/software/EasyBuild/4.1.1/easybuild/easyconfigs/p/Perl/Perl-5.30.0-GCCcore-8.3.0.eb failed (err: "build failed (first 300 chars): Sanity check failed: no (non-empty) directory found at 'man' in /app/software/Perl/5.30.0-GCCcore-8.3.0")
```
```
== 2020-04-30 22:19:57,596 build_log.py:169 ERROR EasyBuild crashed with an error (at easybuild/base/exceptions.py:124 in __init__): Sanity check failed: no (non-empty) directory found at 'man' in /app/software/Perl/5.30.0-GCCcore-8.3.0 (at easybuild/framework/easyblock.py:2596 in _sanity_check_step)
== 2020-04-30 22:19:57,596 easyblock.py:3109 WARNING build failed (first 300 chars): Sanity check failed: no (non-empty) directory found at 'man' in /app/software/Perl/5.30.0-GCCcore-8.3.0
```
The following modification in the [EasyBlock](https://github.com/easybuilders/easybuild-easyblocks/blob/develop/easybuild/easyblocks/p/perl.py#L118) avoids to check the missing folder:

``` 
            +'dirs': ['lib/perl%s/%s' % (majver, self.version)]
            -'dirs': ['lib/perl%s/%s' % (majver, self.version), 'man']
```

I haven't had a chance to investigate it deeper. It takes ~22minutes compiling the whole thing.

### PR DESCRIPTION
**Pull request by Mormacill**
(created using `eb --new-pr`)

edit (by @boegel): fixes #10552

### CODE REVIEW

**Comment by Mormacill** [comment]
You might link issue #10552, this pr should solve this.

**Comment by boegel** [comment]
@boegelbot please test @ generoso

**Review by boegel — APPROVED** [review]
lgtm

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 5 out of 5 (4 easyconfigs in total)
node3101.skitty.os - Linux centos linux 7.9.2009, x86_64, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz, Python 3.6.8
See https://gist.github.com/12b1fb3ea2e3aa487e3534b3d66e80da for a full test report.

**Comment by boegel** [comment]
Going in, thanks @Mormacill!

**Comment by akesandgren** [comment]
Unfortunately this isn't that easy.
We have a cyclic dependency here:
Perl deps on groff which deps on makeinfo which deps on perl.

I have a potential fix for this which includes making a minimal perl only used for building a minimal makeinfo which is only a builddep for groff.

@boegel This was discussed a bit in the slack but never decided on.

**Comment by boegel** [comment]
@akesandgren Ugh, totally overlooked that.

Please open an issue on this, using a `bare` Perl as build dep for `makeinfo` makes sense, I guess.

Also, ideally, the test suite would have caught this, but I'm not sure how easy it is to check for a cycle in the dep graph...

**Comment by boegel** [comment]
@akesandgren Hold on, currently the `makeinfo` easyconfigs don't depend on Perl at all (which may explain why the test suite didn't trip over this).

Are you saying they should?

**Comment by akesandgren** [comment]
See, https://github.com/easybuilders/easybuild-easyconfigs/issues/12067

**Pull request merged**
