### PR TITLE
{tools}[fosscuda/2020b] Horovod v0.23.0 w/ Python 3.8.6 + TensorFlow 2.5.0

### PR DESCRIPTION
**Pull request by surak**
Version bump, users' request.

### CODE REVIEW

**Review by SebastianAchilles — DISMISSED** [review]

**Comment by SebastianAchilles** [comment]
@boegelbot please test @ generoso
CORE_CNT=16

**Comment by SebastianAchilles** [comment]
Test report by @sebastianachilles
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
jsfc01.int.jusuf.sebastian.cluster - Linux rocky linux 8.4, x86_64, AMD EPYC 7742 64-Core Processor (zen2), 1 x NVIDIA GRID V100-4C, 460.73.01, Python 3.6.8
See https://gist.github.com/382e2a55c6b079eecfbad6078be50801 for a full test report.

**Review by boegel — APPROVED** [review]
lgtm

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
node3309.joltik.os - Linux centos linux 7.9.2009, x86_64, Intel(R) Xeon(R) Gold 6242 CPU @ 2.80GHz (cascadelake), 1 x NVIDIA NVIDIA Tesla V100-SXM2-32GB, 465.19.01, Python 3.6.8
See https://gist.github.com/fc46d1a2ed71a59dc7d5772d70a9b1ae for a full test report.

**Comment by boegel** [comment]
Going in, thanks @surak!

**Pull request merged**
