### PR TITLE
{devel}[fosscuda/2019b] PyTorch v1.3.1 w/ Python 3.7.4

### PR DESCRIPTION
**Pull request by branfosj**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by boegel** [comment]
Test report by @boegel
**FAILED**
Build succeeded for 0 out of 1 (1 easyconfigs in this PR)
node3302.joltik.os - Linux centos linux 7.7.1908, Intel(R) Xeon(R) Gold 6242 CPU @ 2.80GHz, Python 2.7.5
See https://gist.github.com/aeed668f919455805d54db9db3075d3d for a full test report.

**Comment by branfosj** [comment]
Test report by @branfosj
**FAILED**
Build succeeded for 0 out of 1 (1 easyconfigs in this PR)
bear-pg0305u05a.bear.cluster - Linux RHEL 7.6, 8335-GTX, Python 2.7.5
See https://gist.github.com/5becb619ecd866c3cbec7274406954d7 for a full test report.

**Comment by branfosj** [comment]
Test report by @branfosj
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
bear-pg0212u25a.bear.cluster - Linux centos linux 7.6.1810, Intel(R) Xeon(R) CPU E5-2640 v4 @ 2.40GHz, Python 2.7.5
See https://gist.github.com/9f6d0e2dd3ebd345bd43fd4e7e479af2 for a full test report.

**Comment by boegel** [comment]
@branfosj Any idea what went wrong with the failed test report?

I have one coming up too...

**Comment by branfosj** [comment]
It failed complaining that `build/nccl/include/nccl.h` was missing. That file is generated in there during the early stages of the build. I restarted the build and it has got past this point, so I think that it is possible, in a parallel build, for this file to not be in place soon enough.

**Comment by boegel** [comment]
@branfosj That sounds like a bug we should report upstream?

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
node3302.joltik.os - Linux centos linux 7.7.1908, Intel(R) Xeon(R) Gold 6242 CPU @ 2.80GHz, Python 2.7.5
See https://gist.github.com/8c01061d2fb2e7579afd622aa453a20e for a full test report.

**Comment by branfosj** [comment]
Test report by @branfosj
**FAILED**
Build succeeded for 0 out of 1 (1 easyconfigs in this PR)
bear-pg0305u05a.bear.cluster - Linux RHEL 7.6, 8335-GTX, Python 2.7.5
See https://gist.github.com/a5a72f5e087cd4899afaebf40f71238a for a full test report.

**Comment by branfosj** [comment]
Test report by @branfosj
**FAILED**
Build succeeded for 0 out of 1 (1 easyconfigs in this PR)
bear-pg0305u05a.bear.cluster - Linux RHEL 7.6, 8335-GTX, Python 2.7.5
See https://gist.github.com/ef311956412af9401ec9a428c2d04636 for a full test report.

**Comment by branfosj** [comment]
The first of the test failure reports was caused by:
```
TimeoutError: [Errno 110] Connection timed out
```
during the testing stage and is in a test called `test_download_url_to_file`. That looks like a temporary issue.

The second was a repeat of the build failure I saw earlier and it does seem to be as I suspected. We see the error
```
include/group.h:10:10: fatal error: nccl.h: No such file or directory
```
first at https://gist.github.com/branfosj/ecfeebcf324942fe001cf1ec82ef6490#file-pytorch-1-3-1-fosscuda-2019b-python-3-7-4_partial-log-L221 but `nccl.h` is generated by
```
Generating nccl.h.in                           > /dev/shm/build-branfosj-admin/branfosj-admin-1/PyTorch/1.3.1/fosscuda-2019b-Python-3.7.4/pytorch-1.3.1/build/nccl/include/nccl.h
```
a few lines later at https://gist.github.com/branfosj/ecfeebcf324942fe001cf1ec82ef6490#file-pytorch-1-3-1-fosscuda-2019b-python-3-7-4_partial-log-L232

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
node3156.skitty.os - Linux centos linux 7.7.1908, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz, Python 3.6.8
See https://gist.github.com/916bd8775cd99f538f5c48291448fe66 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
generoso - Linux centos linux 7.6.1810, Intel(R) Xeon(R) CPU E5-2660 v4 @ 2.00GHz, Python 3.6.8
See https://gist.github.com/fc32acbbaa878d7ac64c0e561f0cce30 for a full test report.

**Comment by boegel** [comment]
@branfosj Should we block this PR over the `nccl.h` issue?

Somehow I didn't manage to trigger it, but it seems like you're testing on a box with 144 cores, which is way more than I have (36 max.)... :)

**Comment by akesandgren** [comment]
PyTorch should have a dependency for NCCL, set USE_SYSTEM_NCCL=1, and finally remove nccl from the souces list. That's what we had to do here to get it to work.

**Comment by boegel** [comment]
@branfosj The suggestion made by @akesandgren sounds good to me?

**Comment by branfosj** [comment]
Yes, that looks sensible to me as well. I'll get on with that soon.

**Comment by branfosj** [comment]
I've changed to using a separate NCCL easyconfig and setting `USE_SYSTEM_NCCL=1` (and removed the NCCL download block). A quick test suggests that we also need to add `NCCL_INCLUDE_DIR=$EBROOTNCCL/include`. I've set my test build going, so the reports will turn up at some point.

**Comment by akesandgren** [comment]
That's a bit odd, we didn't have to add any NCCL_INCLUDE_DIR

**Comment by branfosj** [comment]
In our log we had two sections where CMake talks about finding NCCL appears:
```
-- Added CUDA NVCC flags for: -gencode;arch=compute_35,code=sm_35;-gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_52,code=sm_52;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_61,code=sm_
61;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_72,code=sm_72;-gencode;arch=compute_75,code=sm_75
-- Found NCCL: /rds/bear-apps/devel/2019b/branfosj-eb-1/EL7/EL7-power9/software/NCCL/2.4.8-gcccuda-2019b/include  
-- Determining NCCL version from /rds/bear-apps/devel/2019b/branfosj-eb-1/EL7/EL7-power9/software/NCCL/2.4.8-gcccuda-2019b/include/nccl.h...
-- Looking for NCCL_VERSION_CODE
-- Looking for NCCL_VERSION_CODE - found
-- NCCL version: 2.4.8

-- Found NCCL (include: /rds/bear-apps/devel/2019b/branfosj-eb-1/EL7/EL7-power9/software/NCCL/2.4.8-gcccuda-2019b/include, library: /rds/bear-apps/devel/2019b/branfosj-eb-1/EL7/EL7-power9/software/NCCL/2.4.8
-gcccuda-2019b/lib/libnccl.so)
```
and
```
-- Found CUDA: /rds/bear-apps/devel/2019b/branfosj-eb-1/EL7/EL7-power9/software/CUDA/10.1.243 (found suitable version "10.1", minimum required is "7.0") 
-- CUDA detected: 10.1
-- Could NOT find NCCL (missing: NCCL_INCLUDE_DIR) 
CMake Warning at third_party/gloo/cmake/Dependencies.cmake:96 (message):
  Not compiling with NCCL support.  Suppress this warning with
  -DUSE_NCCL=OFF.
Call Stack (most recent call first):
  third_party/gloo/CMakeLists.txt:56 (include)
```

Setting `NCCL_INCLUDE_DIR` changes the second to be:
```
-- Found CUDA: /rds/bear-apps/devel/2019b/branfosj-eb-1/EL7/EL7-power9/software/CUDA/10.1.243 (found suitable version "10.1", minimum required is "7.0") 
-- CUDA detected: 10.1
-- Determining NCCL version from the header file: /rds/bear-apps/devel/2019b/branfosj-eb-1/EL7/EL7-power9/software/NCCL/2.4.8-gcccuda-2019b/include/nccl.h
-- NCCL_MAJOR_VERSION: 2
-- Found NCCL (include: /rds/bear-apps/devel/2019b/branfosj-eb-1/EL7/EL7-power9/software/NCCL/2.4.8-gcccuda-2019b/include, library: /rds/bear-apps/devel/2019b/branfosj-eb-1/EL7/EL7-power9/software/NCCL/2.4.8
-gcccuda-2019b/lib/libnccl.so)
```

**Comment by akesandgren** [comment]
Ohhh, you're quite right. So do we. Didn't notice when i checked it.

**Comment by branfosj** [comment]
Test report by @branfosj
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
bear-pg0305u05a.bear.cluster - Linux RHEL 7.6, 8335-GTX, Python 2.7.5
See https://gist.github.com/349514c3f79cf25a7b84e6731d162e83 for a full test report.

**Comment by branfosj** [comment]
Test report by @branfosj
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
bear-pg0212u25a.bear.cluster - Linux centos linux 7.6.1810, Intel(R) Xeon(R) CPU E5-2640 v4 @ 2.40GHz, Python 2.7.5
See https://gist.github.com/b0150e354c261b6df3b322c43f3c8654 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
node3302.joltik.os - Linux centos linux 7.7.1908, Intel(R) Xeon(R) Gold 6242 CPU @ 2.80GHz, Python 2.7.5
See https://gist.github.com/a7be94fd88171a53260e6ff6f9595ba2 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 2 out of 2 (1 easyconfigs in this PR)
node3100.skitty.os - Linux centos linux 7.7.1908, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz, Python 3.6.8
See https://gist.github.com/714f5a7cf7b5ee1166aee0d9aec29877 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
generoso-1 - Linux centos linux 7.6.1810, Intel(R) Xeon(R) CPU E5-2660 v4 @ 2.00GHz, Python 3.6.8
See https://gist.github.com/47c90c225139d71aed00dc5c357f0935 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 9 out of 9 (1 easyconfigs in this PR)
node2404.golett.os - Linux centos linux 7.7.1908, Intel(R) Xeon(R) CPU E5-2680 v3 @ 2.50GHz, Python 2.7.5
See https://gist.github.com/6166ca2c5debf685a2d780113a707c49 for a full test report.

**Comment by boegel** [comment]
Going in, thanks @branfosj!

**Pull request merged**
