### PR TITLE
{devel}[gompi/2020b,iimpi/2020b] Boost.MPI v1.74.0

### PR DESCRIPTION
**Pull request by boegel**
(created using `eb --new-pr`)
requires ~~#11642~~ (Boost)

### CODE REVIEW

**Comment by Micket** [comment]
Do we know of any libraries that depend on Boost.MPI? 
My expectation is configuration scripts will rely on one singular `BOOST_ROOT` from where it expects to find all the boost component it needs.

So, with the current approach, Boost, Boost.Python, Boost.MPI  would mean that anything that depends on components from 2 or even all 3, would struggle.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in total)
node3624.doduo.os - Linux RHEL 8.2, x86_64, AMD EPYC 7552 48-Core Processor (zen2), Python 3.6.8
See https://gist.github.com/dcd3359ae3ee904d038b50b150f0e83e for a full test report.

**Comment by boegel** [comment]
@boegelbot please test @ generoso

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in total)
node2708.swalot.os - Linux centos linux 7.8.2003, x86_64, Intel(R) Xeon(R) CPU E5-2660 v3 @ 2.60GHz (haswell), Python 2.7.5
See https://gist.github.com/a488cf337fc1fe1a3e3ab36a0209a9de for a full test report.

**Comment by akesandgren** [comment]
@boegel why isn't this one done the same way that #15757 is, i.e. shadowing Boost?

**Comment by boegel** [comment]
closing this since `foss/2020b` is deprecated, see https://docs.easybuild.io/policies/toolchains

**Pull request closed without merging**
