### PR TITLE
{tools}[foss/2020a] Spyder v4.1.5 w/ Python 3.8.2

### PR DESCRIPTION
**Pull request by boegel**
(created using `eb --new-pr`)
~~#11470~~ (geopandas), ~~#11503~~ (PyQt5)

### CODE REVIEW

**Comment by Micket** [comment]
@boegel Having just worked through the list of python packages for GCC 10.2.0, a lot of the stuff that Spyder includes should already be in IPython

**Comment by boegel** [comment]
> @boegel Having just worked through the list of python packages for GCC 10.2.0, a lot of the stuff that Spyder includes should already be in IPython

:+1:

**Comment by Micket** [comment]
> > @boegel Having just worked through the list of python packages for GCC 10.2.0, a lot of the stuff that Spyder includes should already be in IPython
> 
> +1

I think you might have misunderstood me? I meant you can remove a lot of extensions from Spyder since they are duplicates, like defusedxml  etc.

**Comment by boegel** [comment]
@Micket Ah, I overlooked the `I` in `IPython`...

I thought you were referring to the additional extensions you've included in Python 3.8.6, which would allow us to clean up Spyder on top of that.

I'll revisit this and clean it up based on what's already there in IPython, thanks.

**Comment by boegel** [comment]
@Micket I cleaned up the extensions as well as I could, but I had to keep `jedi` and `jupyter-client` which are also in the `IPython` easyconfig to avoid trouble with `pip check`:
```
spyder 4.1.5 has requirement jedi==0.17.1, but you have jedi 0.17.0.
nbclient 0.5.1 has requirement jupyter-client>=6.1.5, but you have jupyter-client 6.1.3.
```

**Comment by boegel** [comment]
@boegelbot please test @ generoso

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
node3411.kirlia.os - Linux centos linux 7.8.2003, x86_64, Intel(R) Xeon(R) Gold 6240 CPU @ 2.60GHz (cascadelake), Python 2.7.5
See https://gist.github.com/9c98df37a560428e16ccd02b9ec299ed for a full test report.

**Comment by Micket** [comment]
Test report by @Micket
**FAILED**
Build succeeded for 8 out of 9 (1 easyconfigs in this PR)
hebbe-c1 - Linux centos linux 7.8.2003, x86_64, Intel Core Processor (Haswell, no TSX), Python 2.7.5
See https://gist.github.com/56a22737c59ee12624e45617209bd355 for a full test report.

**Comment by Micket** [comment]
Sneaky additions to Python 3.8.4. Rebuilding.

**Comment by Micket** [comment]
Test report by @Micket
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
hebbe-c1 - Linux centos linux 7.8.2003, x86_64, Intel Core Processor (Haswell, no TSX), Python 2.7.5
See https://gist.github.com/ae9612d5193235ae8b7345ab8911fa3d for a full test report.

**Review by Micket — APPROVED** [review]
lgtm

**Comment by Micket** [comment]
Going in, thanks @boegel!

**Pull request merged**
