### PR TITLE
{chem}[foss/2021a] GPAW v21.6.0, ASE v3.22.0, libvdwxc v0.4.0, ... w/ Python 3.9.5

### PR DESCRIPTION
**Pull request by schiotz**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by schiotz** [comment]
GPAW and ASE for the foss/2021a toolchain, including dependencies like matplotlib and Tkinter.

The intel/2021a versions await SciPy-bundle.

**Comment by verdurin** [comment]
Test report by @verdurin
**SUCCESS**
Build succeeded for 9 out of 9 (8 easyconfigs in total)
nuc.lan - Linux Fedora 33, x86_64, Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz, Python 3.9.5
See https://gist.github.com/e7d0b08af44792710b728965ce5bd328 for a full test report.

**Comment by verdurin** [comment]
@boegelbot please test @ generoso

**Review by verdurin — APPROVED** [review]
Looks fine.

**Comment by verdurin** [comment]
Going in, thanks @schiotz!

**Comment by branfosj** [comment]
@boegelbot please test @ jsc-zen3
EB_ARGS="Tkinter-3.9.5-GCCcore-10.3.0.eb"

**Pull request merged**
