### PR TITLE
{data}[foss/2018b] ANTs v2.3.1, ITK v5.0b01 w/ Python 3.6.6 (REVIEW)

### PR DESCRIPTION
**Pull request by boegel**
(created using `eb --new-pr`)
requires ~~#6997~~ (VTK)

edit: original plan was to use `ITK` v5.0b01 as a dependency for `ANTs`, but apparently that doesn't work and you *have* to let `ANTs` download & build a very specific `ITK` commit (see also https://sourceforge.net/p/advants/discussion/840261/thread/9ea892278a/).

### CODE REVIEW

**Comment by boegel** [comment]
Test report by @boegel
**FAILED**
Build succeeded for 0 out of 2 (2 easyconfigs in this PR)
node2401.golett.os - Linux centos linux 7.5.1804, Intel(R) Xeon(R) CPU E5-2680 v3 @ 2.50GHz, Python 2.7.5
See https://gist.github.com/2d28f50cae86ac96c3b5dbf7b650f837 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**FAILED**
Build succeeded for 0 out of 2 (2 easyconfigs in this PR)
node2006.delcatty.os - Linux centos linux 7.5.1804, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.7.5
See https://gist.github.com/bb3fbef44a5140064008f8cb70e12c88 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**FAILED**
Build succeeded for 1 out of 2 (2 easyconfigs in this PR)
node2609.swalot.os - Linux centos linux 7.5.1804, Intel(R) Xeon(R) CPU E5-2660 v3 @ 2.60GHz, Python 2.7.5
See https://gist.github.com/d7242fa37818d2aae5ee96e9ae07cad9 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in this PR)
node2038.delcatty.os - Linux centos linux 7.5.1804, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.7.5
See https://gist.github.com/11ed453da71119f2aa44b2461771494c for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**FAILED**
Build succeeded for 1 out of 2 (2 easyconfigs in this PR)
node2692.swalot.os - Linux centos linux 7.5.1804, Intel(R) Xeon(R) CPU E5-2660 v3 @ 2.60GHz, Python 2.7.5
See https://gist.github.com/f91a56552d3738e3b9a3ec16629f3cd5 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**FAILED**
Build succeeded for 1 out of 2 (2 easyconfigs in this PR)
node3120.skitty.os - Linux centos linux 7.5.1804, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz, Python 2.7.5
See https://gist.github.com/89a0c0de71a24d1fcd4bebba803174c2 for a full test report.

**Comment by boegel** [comment]
Hmm, it seems like the `cp -a * %(installdir)s` command that is being glued to the `make` command fails sometimes because of permission issues:

```
cp: cannot create regular file ‘/user/home/gent/vsc400/vsc40023/eb_phanpyscratch/CO7/skylake-ib/software/ANTs/2.3.1-foss-2018b-Python-3.6.6/ITKv5/Modules/Remote/MGHIO/.git/objects/pack/pack-19089643ef25059e3c0e1deb38fa6bc4a3c117df.idx’: Permission denied
cp: cannot create regular file ‘/user/home/gent/vsc400/vsc40023/eb_phanpyscratch/CO7/skylake-ib/software/ANTs/2.3.1-foss-2018b-Python-3.6.6/ITKv5/Modules/Remote/MGHIO/.git/objects/pack/pack-19089643ef25059e3c0e1deb38fa6bc4a3c117df.pack’: Permission denied
```

That's a bit strange though, it looks like those files are being copied twice and then (sometimes?!) the `cp` fails because these `.git` files don't have the write permission bit set?

```
$ ls -l ITKv5/Modules/Remote/MGHIO/.git/objects/pack
total 192
-r--r--r-- 1 vsc40023 vsc40023  8100 Oct 17 16:34 pack-19089643ef25059e3c0e1deb38fa6bc4a3c117df.idx
-r--r--r-- 1 vsc40023 vsc40023 60424 Oct 17 16:34 pack-19089643ef25059e3c0e1deb38fa6bc4a3c117df.pack
```

**Comment by boegel** [comment]
Test report by @boegel
**FAILED**
Build succeeded for 1 out of 2 (2 easyconfigs in this PR)
node3108.skitty.os - Linux centos linux 7.5.1804, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz, Python 2.7.5
See https://gist.github.com/b6588d632b67b5a29a53adff3ea24887 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**FAILED**
Build succeeded for 1 out of 2 (2 easyconfigs in this PR)
node2400.golett.os - Linux centos linux 7.5.1804, Intel(R) Xeon(R) CPU E5-2680 v3 @ 2.50GHz, Python 2.7.5
See https://gist.github.com/7993f6d7ab688a6da29c5897409b106f for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**FAILED**
Build succeeded for 1 out of 2 (2 easyconfigs in this PR)
node2032.delcatty.os - Linux centos linux 7.5.1804, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.7.5
See https://gist.github.com/1a8d8ae5a7d8f9ade6382a8bbe97b098 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**FAILED**
Build succeeded for 1 out of 2 (2 easyconfigs in this PR)
node3146.skitty.os - Linux centos linux 7.5.1804, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz, Python 2.7.5
See https://gist.github.com/2def56cb1e29e2a8cb3d8402a35ee5e7 for a full test report.

**Comment by verdurin** [comment]
@boegel - any update here?

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in this PR)
node3169.skitty.os - Linux centos linux 7.5.1804, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz, Python 2.7.5
See https://gist.github.com/9e2f5cecee5dea4a415aef273ea9483f for a full test report.

**Comment by vanzod** [comment]
Test report by @vanzod
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in this PR)
cermis - Linux debian 9.6, Intel(R) Xeon(R) CPU           E5620  @ 2.40GHz, Python 2.7.13
See https://gist.github.com/4d9394d76aee0120fe1805aa78ae6149 for a full test report.

**Comment by vanzod** [comment]
Going in, thanks @boegel!

**Pull request merged**
