### PR TITLE
{chem}[foss/2022a] spglib v2.0.2, ShengBTE v1.5.0, thirdorder v1.1.1 w/ Python 3.10.4

### PR DESCRIPTION
**Pull request by akesandgren**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by akesandgren** [comment]
@boegelbot Please test @ jsc-zen2

**Comment by verdurin** [comment]
@boegelbot please test @ generoso

**Comment by verdurin** [comment]
Test report by @verdurin
**SUCCESS**
Build succeeded for 3 out of 3 (3 easyconfigs in total)
easybuild-c7.novalocal - Linux CentOS Linux 7.9.2009, x86_64, Intel Xeon Processor (Skylake, IBRS), Python 3.6.8
See https://gist.github.com/verdurin/e612c47543ce0a27fbbfb22e4e5bf2fe for a full test report.

**Review by Micket — APPROVED** [review]
lgtm

**Comment by verdurin** [comment]
Going in, thanks @akesandgren!

**Pull request merged**
