### PR TITLE
{data,numlib}[foss/2024a] Armadillo v14.0.3, arpack-ng v3.9.1

### PR DESCRIPTION
**Pull request by maxim-masterov**
(created using `eb --new-pr`)

Depends on:
- HDF5-1.14.5 #21570

The following dependencies were only needed for GDAL (removed from this PR in favor of https://github.com/easybuilders/easybuild-easyconfigs/pull/21907):
- <s> Szip-2.1.1 #21510 </s>
- <s> Xerces-C++-3.2.5 #21417 </s>
- <s> netCDF-4.9.2 #21578 </s>
- <s> netCDF-4.9.2 #21862 </s>
- <s> PCRE-8.45 #21282 </s>
- <s> GEOS-3.13.0 #21561 </s>
- <s> libtirpc-1.3.5 #21282 </s>
- <s> LERC-4.0.0 #21282 </s>
- <s> libgeotiff-1.7.3 #21433 </s>
- <s> HDF #21433 </s>

### CODE REVIEW

**Comment by verdurin** [comment]
There's also the `giflib` version issue - could it use `5.2.1` instead?

**Comment by maxim-masterov** [comment]
@smoors I can switch to GDAL v3.10.0, no problem. Only Fiona from https://github.com/easybuilders/easybuild-easyconfigs/pull/21614 needs to be updated.

@verdurin What's the problem with giflib 5.2.2? I see that https://github.com/easybuilders/easybuild-easyconfigs/pull/21907 also uses v5.2.2.

**Comment by smoors** [comment]
> @verdurin What's the problem with giflib 5.2.2? I see that #21907 also uses v5.2.2.

see the failing check:
>AssertionError: Should not have multiple variants of dependencies.
Found 2 variants of 'giflib' dependency in easyconfigs using '2024a' toolchain generation
>* version: 5.2.1; versionsuffix:  as dep for {'ASE-3.23.0-gfbf-2024a.eb', 'matplotlib-3.9.2-gfbf-2024a.eb', 'modin-0.32.0-foss-2024a.eb', 'GPAW-24.6.0-foss-2024a.eb', 'Seaborn-0.13.2-gfbf-2024a.eb', 'dask-2024.9.1-gfbf-2024a.eb', 'bokeh-3.6.0-gfbf-2024a.eb', 'nf-core-2.14.1-foss-2024a.eb'}
>  * version: 5.2.2; versionsuffix:  as dep for {'GDAL-3.9.2-foss-2024a.eb'}

**Comment by maxim-masterov** [comment]
@smoors I see, I will remove GDAL from this PR in favor of https://github.com/easybuilders/easybuild-easyconfigs/pull/21907. Then #21907 needs to update `giflib`.

**Comment by smoors** [comment]
@boegelbot please test @ jsc-zen3

**Comment by smoors** [comment]
@boegelbot: please test @ generoso

**Review by smoors — APPROVED** [review]
lgtm

**Comment by smoors** [comment]
Going in, thanks @maxim-masterov!

**Pull request merged**
