### PR TITLE
{tools}[GCCcore/8.3.0] Sumo v1.3.1 w/ Python 3.7.4

### PR DESCRIPTION
**Pull request by ekieffer**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by ekieffer** [comment]
Test report by @ULHPC
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
iris-001 - Linux centos linux 7.8.2003, x86_64, Intel(R) Xeon(R) CPU E5-2680 v4 @ 2.40GHz, Python 3.6.8
See https://gist.github.com/47728bc674766efa2a4c3dde114b0491 for a full test report.

**Comment by casparvl** [comment]
Let's see if I can command boeglebot too to test this, otherwise I do one of my own :)

**Comment by casparvl** [comment]
@boegelbot please test @ generoso

**Comment by casparvl** [comment]
Test report by @casparvl
**FAILED**
Build succeeded for 0 out of 1 (1 easyconfigs in this PR)
software1.lisa.surfsara.nl - Linux debian 10.5, x86_64, Intel(R) Xeon(R) Silver 4110 CPU @ 2.10GHz, Python 2.7.16
See https://gist.github.com/c93178fee7336f5db6482af64e8574fa for a full test report.

**Comment by casparvl** [comment]
Something seems to be wrong with the source link. EB looks at

`https://iweb.dl.sourceforge.net/project/sumo/sumo/version%201.3.1/sumo-src-1.3.1.tar.gz`

If I try to `wget` from there, I also get nothing.

Any chance you could check the link @ekieffer , is it as you intended?

**Comment by ekieffer** [comment]
* The link seems to work

```bash
 wget https://iweb.dl.sourceforge.net/project/sumo/sumo/version%201.3.1/sumo-src-1.3.1.tar.gz                           SIGINT(2) ↵  15:16:48  
--2020-08-11 15:16:52--  https://iweb.dl.sourceforge.net/project/sumo/sumo/version%201.3.1/sumo-src-1.3.1.tar.gz
Resolving iweb.dl.sourceforge.net (iweb.dl.sourceforge.net)... 192.175.120.182, 2607:f748:10:12::5f:2
Connecting to iweb.dl.sourceforge.net (iweb.dl.sourceforge.net)|192.175.120.182|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 19562599 (19M) [application/x-gzip]
Saving to: ‘sumo-src-1.3.1.tar.gz.1’

sumo-src-1.3.1.tar.gz.1                        100%[=================================================================================================>]  18,66M  3,46MB/s    in 10s     

2020-08-11 15:17:02 (1,82 MB/s) - ‘sumo-src-1.3.1.tar.gz.1’ saved [19562599/19562599]



```

**Comment by casparvl** [comment]
Test report by @casparvl
**FAILED**
Build succeeded for 0 out of 1 (1 easyconfigs in this PR)
software1.lisa.surfsara.nl - Linux debian 10.5, x86_64, Intel(R) Xeon(R) Silver 4110 CPU @ 2.10GHz, Python 2.7.16
See https://gist.github.com/316cf6f6582563a4e07a4461dca0b4f8 for a full test report.

**Comment by smoors** [comment]
@casparvl you should probably have added `--robot` to install missing dependencies as well (gtest).

**Comment by smoors** [comment]
@boegelbot please test @ generoso

**Comment by smoors** [comment]
Test report by @smoors
**SUCCESS**
Build succeeded for 3 out of 3 (1 easyconfigs in this PR)
node254.hydra.os - Linux centos linux 7.7.1908, x86_64, Intel(R) Xeon(R) CPU E5-2683 v4 @ 2.10GHz (broadwell), Python 2.7.5
See https://gist.github.com/0bc84dd888b9149e9962725de04eff04 for a full test report.

**Comment by smoors** [comment]
Going in, thanks @ekieffer!

**Comment by casparvl** [comment]
> @casparvl you should probably have added `--robot` to install missing dependencies as well (gtest).

Lol, sorry about that. I got distracted by other things again. Anyway, I see that you already did a test and did not hit the sources issue, so I assume that was a hickup in my first test.

**Comment by boegel** [comment]
Note: the `gtest` dependency in the `Sumo` easyconfig was renamed to `googletest` as a part of #11082 (which is an effort to avoid using both the `gtest` and `googletest` names for the same thing).

**Pull request merged**
