### PR TITLE
{lib}[foss/2021a] OpenFace v2.2.0, dlib v19.22

### PR DESCRIPTION
**Pull request by zarybnicky**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by zarybnicky** [comment]
Requires model files from https://github.com/TadasBaltrusaitis/OpenFace/wiki/Model-download - that is, from Dropbox, Google Drive, or OneDrive.

**Comment by boegel** [comment]
> Requires model files from https://github.com/TadasBaltrusaitis/OpenFace/wiki/Model-download - that is, from Dropbox, Google Drive, or OneDrive.

It looks like those must be part of the installation itself?!

Any idea how difficult it would be to come up with a patch to allow specifying an alternate location for those huge model files at runtime, for example through an environment variable?

**Comment by zarybnicky** [comment]
Ok, so it seems that models do not, in fact, have to be downloaded into the installation directory, that's just the default location.

- https://github.com/TadasBaltrusaitis/OpenFace/issues/387
- https://github.com/TadasBaltrusaitis/OpenFace/wiki/Command-line-arguments#common-parameters-for-all

The way to go for local models would, IMO, be:

1. Copy the directory $EBROOT/software/OpenFace/2.2.0-foss-2021a-CUDA-11.3.1/etc/OpenFace/model/ to a local directory.
2. Follow the instructions on https://github.com/TadasBaltrusaitis/OpenFace/wiki/Model-download to download the missing patches into `model/patch_experts`.
3. When using OpenFace, either
    1. have the directory `model/` in the current working directory, so that autodetection works,
    2. or specify the model file with each invocation using the `-mloc` parameter (e.g. `-mloc ../model/main_clm_general.txt`)

With this resolved, I think this PR is ready for review, I just need to replace the sanity check command with one that will work without the model files

**Comment by lexming** [comment]
Test report by @lexming
**SUCCESS**
Build succeeded for 26 out of 26 (4 easyconfigs in total)
node200.hydra.os - Linux centos linux 7.9.2009, x86_64, Intel(R) Xeon(R) CPU E5-2680 v4 @ 2.40GHz, Python 2.7.5
See https://gist.github.com/1154d044318a006376389b91cc41ee8e for a full test report.

**Review by lexming — COMMENTED** [review]
Thanks for the update @zarybnicky . I only have one minor remark to be able to merge it, please add a description and author to the patch file `OpenFace-2.2.0-use_FlexiBLAS.patch`

**Comment by boegel** [comment]
@boegelbot please test @ generoso

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 4 out of 4 (4 easyconfigs in total)
node3122.skitty.os - Linux centos linux 7.9.2009, x86_64, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz (skylake_avx512), Python 3.6.8
See https://gist.github.com/65c2dd847e46a3623778919b005565c4 for a full test report.

**Review by lexming — APPROVED** [review]
LGTM

**Comment by lexming** [comment]
Going in, thanks @zarybnicky and @boegel !

**Pull request merged**
