### PR TITLE
Add patches for PyTorch 1.7.1 avoiding failures on POWER and A100

### PR DESCRIPTION
**Pull request by Flamefire**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by Flamefire** [comment]
Test report by @Flamefire
**FAILED**
Build succeeded for 1 out of 3 (3 easyconfigs in total)
taurusml13 - Linux RHEL 7.6, POWER, 8335-GTX (power9le), Python 2.7.5
See https://gist.github.com/ef4b2bf2195b615cb3a7b1ee03383a9b for a full test report.

**Comment by Flamefire** [comment]
Test report by @Flamefire
**FAILED**
Build succeeded for 16 out of 18 (2 easyconfigs in total)
taurusi8029 - Linux centos linux 7.9.2009, x86_64, AMD EPYC 7352 24-Core Processor (zen2), Python 2.7.5
See https://gist.github.com/07b00975ca023db1c7ac1f64f9f5e292 for a full test report.

**Comment by Flamefire** [comment]
Test report by @Flamefire
**FAILED**
Build succeeded for 0 out of 1 (1 easyconfigs in total)
taurusml22 - Linux RHEL 7.6, POWER, 8335-GTX (power9le), Python 2.7.5
See https://gist.github.com/0bca1343f75cb24d54a547d2ba44beb9 for a full test report.

**Comment by Flamefire** [comment]
Test report by @Flamefire
**FAILED**
Build succeeded for 0 out of 1 (1 easyconfigs in total)
taurusml28 - Linux RHEL 7.6, POWER, 8335-GTX (power9le), Python 2.7.5
See https://gist.github.com/29289c25383c913b17b5241baaba63f3 for a full test report.

**Comment by Flamefire** [comment]
Failures on 2020 due to missing CUDA 11 drivers. Running the test locally fails with the same error and "CUDA initialization: CUDA driver initialization failed, you might not have a CUDA gpu"-warning

**Comment by boegel** [comment]
@boegelbot please test @ generoso
EB_ARGS="PyTorch-1.7.1-foss-2020b.eb"
CORE_COUNT=16

**Comment by Flamefire** [comment]
Test report by @Flamefire
**FAILED**
Build succeeded for 10 out of 14 (2 easyconfigs in total)
taurusi8028 - Linux centos linux 7.9.2009, x86_64, AMD EPYC 7352 24-Core Processor (zen2), Python 2.7.5
See https://gist.github.com/ba1b1a16cbb238823d0421fa2ace660b for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**FAILED**
Build succeeded for 2 out of 3 (3 easyconfigs in total)
node3300.joltik.os - Linux centos linux 7.9.2009, x86_64, Intel(R) Xeon(R) Gold 6242 CPU @ 2.80GHz (cascadelake), Python 3.6.8
See https://gist.github.com/4f3971033005d330fbad209ad8bcbc8e for a full test report.

**Comment by Flamefire** [comment]
Test report by @Flamefire
**FAILED**
Build succeeded for 0 out of 3 (1 easyconfigs in total)
taurusi8028 - Linux centos linux 7.9.2009, x86_64, AMD EPYC 7352 24-Core Processor (zen2), Python 2.7.5
See https://gist.github.com/60bdb6dbc977198c2296edcfbf1442ea for a full test report.

**Comment by boegel** [comment]
I was running my last test build on a node that has the latest CUDA driver (465.19.01), which seems to have impact on the tests for `PyTorch-1.7.1-fosscuda-2020b.eb`?
I'm not seeing those failing tests on a node that didn't get the CUDA driver update yet (still running 455.23.05)...

```
FAIL: test_adadelta (__main__.TestOptim)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/tmp/eb-4st2qifr/tmp_vktr7wn/lib/python3.8/site-packages/torch/testing/_internal/common_utils.py", line 396, in wrapper
    fn(*args, **kwargs)
  File "test_optim.py", line 491, in test_adadelta
    self._test_basic_cases(
  File "test_optim.py", line 204, in _test_basic_cases
    self._test_state_dict(
  File "test_optim.py", line 192, in _test_state_dict
    self.assertEqual(weight, weight_cuda)
  File "/tmp/eb-4st2qifr/tmp_vktr7wn/lib/python3.8/site-packages/torch/testing/_internal/common_utils.py", line 1136, in assertEqual
    self.assertTrue(result, msg=msg)
AssertionError: False is not true : Tensors failed to compare as equal! With rtol=1.3e-06 and atol=1e-05, found 2 element(s) (out of 50) whose difference(s) exceeded the margin of error (including 0 nan comparisons). The greatest difference was 1.2218952178955078e-05 (-0.7925083041191101 vs. -0.7924960851669312), which occurred at index (9, 1).

----------------------------------------------------------------------
Ran 103 tests in 72.666s

FAILED (failures=1)
```

Ever seen something like that @Flamefire? Perhaps the test is just unstable, and it was bad luck?

**Comment by Flamefire** [comment]
Test report by @Flamefire
**SUCCESS**
Build succeeded for 3 out of 3 (1 easyconfigs in total)
taurusi8028 - Linux centos linux 7.9.2009, x86_64, AMD EPYC 7352 24-Core Processor (zen2), Python 2.7.5
See https://gist.github.com/5f178669ba2ded440a4d0c8f9f5efd6e for a full test report.

**Comment by Flamefire** [comment]
I guess my test just finished, that is on AMD with A100s, so no haven't seen that

Was your update to CUDA 11.2? The PyTorch guys have seen those: https://github.com/pytorch/pytorch/pull/51905

**Comment by Flamefire** [comment]
Test report by @Flamefire
**FAILED**
Build succeeded for 0 out of 1 (1 easyconfigs in total)
taurusi8031 - Linux centos linux 7.9.2009, x86_64, AMD EPYC 7352 24-Core Processor (zen2), Python 2.7.5
See https://gist.github.com/be521fc4f00ac893db632cae31515948 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
node3300.joltik.os - Linux centos linux 7.9.2009, x86_64, Intel(R) Xeon(R) Gold 6242 CPU @ 2.80GHz (cascadelake), Python 3.6.8
See https://gist.github.com/2e3c2453ed2e744ce302dea6809f385f for a full test report.

**Comment by verdurin** [comment]
Test failure on `ppc64le`:
```
======================================================================
FAIL: test_norm_matrix_cpu_float64 (__main__.TestLinalgCPU)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/tmp/eb-zf1wbxny/tmpbooavsxk/lib/python3.7/site-packages/torch/testing/_internal/common_device_type.py", line 273, in instantiated_test
    result = test_fn(self, *args)
  File "/tmp/eb-zf1wbxny/tmpbooavsxk/lib/python3.7/site-packages/torch/testing/_internal/common_device_type.py", line 508, in dep_fn
    return fn(slf, device, *args, **kwargs)
  File "test_linalg.py", line 314, in test_norm_matrix
    run_test_case(input, ord, dim, keepdim)
  File "test_linalg.py", line 289, in run_test_case
    self.assertEqual(result, result_numpy, msg=msg)
  File "/tmp/eb-zf1wbxny/tmpbooavsxk/lib/python3.7/site-packages/torch/testing/_internal/common_utils.py", line 1162, in assertEqual
    exact_dtype=exact_dtype, exact_device=exact_device)
  File "/tmp/eb-zf1wbxny/tmpbooavsxk/lib/python3.7/site-packages/torch/testing/_internal/common_utils.py", line 1162, in assertEqual
    exact_dtype=exact_dtype, exact_device=exact_device)
  File "/tmp/eb-zf1wbxny/tmpbooavsxk/lib/python3.7/site-packages/torch/testing/_internal/common_utils.py", line 1058, in assertEqual
    exact_dtype=exact_dtype, exact_device=exact_device)
  File "/tmp/eb-zf1wbxny/tmpbooavsxk/lib/python3.7/site-packages/torch/testing/_internal/common_utils.py", line 1173, in assertEqual
    self.assertTrue(result, msg=msg)
AssertionError: False is not true : input.size()=torch.Size([1000, 1000]), ord=-2, dim=None, keepdim=True, dtype=torch.float64
```

Driver version is `440.118.02`.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 3 out of 3 (3 easyconfigs in total)
node3300.joltik.os - Linux centos linux 7.9.2009, x86_64, Intel(R) Xeon(R) Gold 6242 CPU @ 2.80GHz (cascadelake), Python 3.6.8
See https://gist.github.com/db6c727c6719225627d9046e43f9ede0 for a full test report.

**Comment by Flamefire** [comment]
Test report by @Flamefire
**FAILED**
Build succeeded for 0 out of 1 (1 easyconfigs in total)
taurusi8028 - Linux centos linux 7.9.2009, x86_64, AMD EPYC 7352 24-Core Processor (zen2), Python 2.7.5
See https://gist.github.com/7444d3c63482ac1565bb481189778606 for a full test report.

**Comment by boegel** [comment]
@Flamefire Fix with latest CUDA drivers confirmed, but trouble on other systems?

**Comment by Flamefire** [comment]
@verdurin Does that system has the latest patches for OpenBLAS? Because that is a CPU test failure which works on our POWER system.

@boegel IIRC it did never work on our A100 system (the previous was foss test only) FWIW the upstream issue is https://github.com/pytorch/pytorch/issues/52278

Maybe I'll just disable `test_nn` for 2020b?

**Comment by sassy-crick** [comment]
> I was running my last test build on a node that has the latest CUDA driver (465.19.01), which seems to have impact on the tests for `PyTorch-1.7.1-fosscuda-2020b.eb`?
> I'm not seeing those failing tests on a node that didn't get the CUDA driver update yet (still running 455.23.05)...

> Ever seen something like that @Flamefire? Perhaps the test is just unstable, and it was bad luck?
> 
> edit: This also happens without the extra patches being added here BTW...

@boegel If it helps, I got that currently installed on the AMD EPYC 7552 48-Core Processo machine I got access to:
`NVIDIA-SMI 460.32.03    Driver Version: 460.32.03    CUDA Version: 11.2`

**Comment by verdurin** [comment]
@Flamefire this is the same node I mentioned recently. It has the following patches:
```
OpenBLAS-0.3.7_fix-build-on-arm-tsv110.patch
OpenBLAS-0.3.7_fix-missing-sync-on-power.patch
OpenBLAS-0.3.7_fix-possible-memory-leak-after-fork.patch
OpenBLAS-0.3.7_reinit-threads-after-fork.patch
OpenBLAS-0.3.8_fix-dscal-inline-asm.patch
```

**Comment by Flamefire** [comment]
Test report by @Flamefire
**FAILED**
Build succeeded for 1 out of 2 (2 easyconfigs in total)
taurusml20 - Linux RHEL 7.6, POWER, 8335-GTX (power9le), Python 2.7.5
See https://gist.github.com/00814f9299a9d697aec2a6747bf15899 for a full test report.

**Comment by Flamefire** [comment]
Test report by @Flamefire
**FAILED**
Build succeeded for 0 out of 1 (1 easyconfigs in total)
taurusml20 - Linux RHEL 7.6, POWER, 8335-GTX (power9le), Python 2.7.5
See https://gist.github.com/99818b322c357a18b81a8f787580c05a for a full test report.

**Comment by Flamefire** [comment]
Test report by @Flamefire
**FAILED**
Build succeeded for 0 out of 1 (1 easyconfigs in total)
taurusml23 - Linux RHEL 7.6, POWER, 8335-GTX (power9le), Python 2.7.5
See https://gist.github.com/1d7f5de66fafcda2d2edba2dd68a3d78 for a full test report.

**Comment by Flamefire** [comment]
Test report by @Flamefire
**FAILED**
Build succeeded for 0 out of 1 (1 easyconfigs in total)
taurusml20 - Linux RHEL 7.6, POWER, 8335-GTX (power9le), Python 2.7.5
See https://gist.github.com/b61c71011808e661d7049267fca2a584 for a full test report.

**Comment by Flamefire** [comment]
Test report by @Flamefire
**SUCCESS**
Build succeeded for 16 out of 16 (2 easyconfigs in total)
taurusml13 - Linux RHEL 7.6, POWER, 8335-GTX (power9le), Python 2.7.5
See https://gist.github.com/4cb3e4a1164017b0c2ab72b431a6bdeb for a full test report.

**Comment by branfosj** [comment]
Test report by @branfosj
**FAILED**
Build succeeded for 0 out of 1 (1 easyconfigs in total)
bask-pg0309u25a - Linux RHEL 8.3, x86_64, Intel(R) Xeon(R) Platinum 8358P CPU @ 2.60GHz (icelake), Python 3.6.8
See https://gist.github.com/f8c92f2e5ea97526fba6ffde80e1201a for a full test report.

**Comment by Flamefire** [comment]
@branfosj 
> what():  CUDA error: uncorrectable NVLink error detected during the execution

I've seen that for PyTorch 1.8.1 on our A100 GPUs but never on the older ones. Maybe that is CUDA driver version related? Still got to check if I see this on our new partition with this EC here too. Might be that our (EB) NCCL is faulty.

**Comment by branfosj** [comment]
> @branfosj
> 
> > what():  CUDA error: uncorrectable NVLink error detected during the execution
> 
> I've seen that for PyTorch 1.8.1 on our A100 GPUs but never on the older ones. Maybe that is CUDA driver version related? Still got to check if I see this on our new partition with this EC here too. Might be that our (EB) NCCL is faulty.

The failed test was also with A100s. NVidia driver 460.73.01.

I have this built fine on a system with a single P100 - NVidia driver 460.32.03.

PyTorch 1.8.1 failed on the A100s with the same problem that you have reported to PyTorch. That also failed with a self-built NCCL 2.9.8.

**Comment by Flamefire** [comment]
> That also failed with a self-built NCCL 2.9.8.

Confirmed also with PyTorch 1.8.1 fosscuda/2020b and their submodule NCCL (2.7.8)

**Comment by boegel** [comment]
@boegelbot please test @ generoso
CORE_CNT=16

**Comment by Flamefire** [comment]
Test report by @Flamefire
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in total)
taurusml4 - Linux RHEL 7.6, POWER, 8335-GTX (power9le), Python 2.7.5
See https://gist.github.com/7ff4ca773bf0621e4829253d878785dc for a full test report.

**Comment by Flamefire** [comment]
Test report by @Flamefire
**FAILED**
Build succeeded for 1 out of 2 (2 easyconfigs in total)
taurusa4 - Linux centos linux 7.7.1908, x86_64, Intel(R) Xeon(R) CPU E5-2603 v4 @ 1.70GHz (broadwell), Python 2.7.5
See https://gist.github.com/8ec1f1b47ced050a742842d085f1e5fe for a full test report.

**Comment by branfosj** [comment]
Test report by @branfosj
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
bear-pg0211u13a.bear.cluster - Linux RHEL 8.3, x86_64, Intel(R) Xeon(R) Gold 6248 CPU @ 2.50GHz (cascadelake), Python 3.6.8
See https://gist.github.com/14cea78c30fb1f83200be1af0c1ab7d3 for a full test report.

**Comment by branfosj** [comment]
Test report by @branfosj
**SUCCESS**
Build succeeded for 3 out of 3 (3 easyconfigs in total)
bear-pg0212u15b.bear.cluster - Linux RHEL 8.3, x86_64, Intel(R) Xeon(R) CPU E5-2640 v4 @ 2.40GHz (broadwell), Python 3.6.8
See https://gist.github.com/0af507f398d3918bdbe9ddd1b5ccc155 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 3 out of 3 (3 easyconfigs in total)
node3302.joltik.os - Linux centos linux 7.9.2009, x86_64, Intel(R) Xeon(R) Gold 6242 CPU @ 2.80GHz (cascadelake), Python 3.6.8
See https://gist.github.com/e1a6c67d1f21a63b28ce877458461ba0 for a full test report.

**Comment by Flamefire** [comment]
Test report by @Flamefire
**FAILED**
Build succeeded for 0 out of 1 (1 easyconfigs in total)
taurusa7 - Linux centos linux 7.7.1908, x86_64, Intel(R) Xeon(R) CPU E5-2603 v4 @ 1.70GHz (broadwell), Python 2.7.5
See https://gist.github.com/8a4e86dfcedde1e7eec268336ded2c88 for a full test report.

**Comment by Flamefire** [comment]
The failed tests are the bottleneck_test which will be disabled by https://github.com/easybuilders/easybuild-easyblocks/pull/2450 and a flaky test with fosscuda-2020b where a timeout is reached to early, i.e. all are non-critical.
The latter is annoying though and might be related to me seeing increased test times for 2020b over 2020a over 2019b which I'm still investigating.

**Comment by boegel** [comment]
> The failed tests are the bottleneck_test which will be disabled by [easybuilders/easybuild-easyblocks#2450](https://github.com/easybuilders/easybuild-easyblocks/pull/2450) and a flaky test with fosscuda-2020b where a timeout is reached to early, i.e. all are non-critical.
> The latter is annoying though and might be related to me seeing increased test times for 2020b over 2020a over 2019b which I'm still investigating.

OK, thanks for clarifying @Flamefire!

**Review by boegel — APPROVED** [review]
lgtm

**Comment by boegel** [comment]
Going in, thanks @Flamefire!

**Pull request merged**
