### PR TITLE
{devel}[foss/2020b] Spark 3.1.1

### PR DESCRIPTION
**Pull request by fizwit**
(created using `eb --new-pr`)
sans Cuda is needed, sometimes you just need the Spark libraries.  requirement for pySpark.

### CODE REVIEW

**Comment by Falkor** [comment]
Build of Arrow fails on my side: 
```
== FAILED: Installation ended unsuccessfully (build directory: /dev/shm/Arrow/0.17.1/foss-2020b): build failed (first 300 chars): cmd " cmake -DCMAKE_INSTALL_PREFIX=/opt/apps/resif/aion/2020b/epyc/software/Arrow/0.17.1-foss-2020b -DCMAKE_INSTALL_LOCALSTATEDIR=/opt/apps/resif/aion/2020b/epyc/software/Arrow/0.17.1-foss-2020b/var -DCMAKE_INSTALL_RUNSTATEDIR=/opt/apps/resif/aion/2020b/epyc/software/Arrow/0.17.1-foss-2020b/var/run  (took 5 secs)
== Results of the build can be found in the log file(s) /mnt/irisgpfs/users/resif/git/gitlab.uni.lu/ULHPC/sw/logs/easybuild/easybuild-Arrow-0.17.1-20211118.123224.hDkWr.log
ERROR: Build of /mnt/irisgpfs/users/resif/git/gitlab.uni.lu/ULHPC/sw/easyconfigs/a/Arrow/Arrow-0.17.1-foss-2020b.eb failed (err: 'build failed (first 300 chars): cmd " cmake -DCMAKE_INSTALL_PREFIX=/opt/apps/resif/aion/2020b/epyc/software/Arrow/0.17.1-foss-2020b -DCMAKE_INSTALL_LOCALSTATEDIR=/opt/apps/resif/aion/2020b/epyc/software/Arrow/0.17.1-foss-2020b/var -DCMAKE_INSTALL_RUNSTATEDIR=/opt/apps/resif/aion/2020b/epyc/software/Arrow/0.17.1-foss-2020b/var/run ')
```
In details: 
```
-- Could NOT find Thrift: Found unsuitable version "", but required is at least "0.11.0" (found THRIFT_STATIC_LIB-NOTFOUND)
-- Found Boost: /opt/apps/resif/aion/2020b/epyc/software/Boost/1.74.0-GCC-10.2.0/lib64/cmake/Boost-1.74.0/BoostConfig.cmake (found suitable version "1.74.0", minimum required is "1.58") found components: regex system filesystem
-- Boost include dir: /mnt/irisgpfs/apps/resif/aion/2020b/epyc/software/Boost/1.74.0-GCC-10.2.0/include
-- Boost libraries: Boost::system;Boost::filesystem
-- Could NOT find SnappyAlt (missing: Snappy_LIB Snappy_INCLUDE_DIR)
-- Building snappy from source
-- Building without OpenSSL support. Minimum OpenSSL version 1.0.2 required.
Building Apache Thrift from source
-- Building (vendored) jemalloc from source
-- Could NOT find RapidJSONAlt (missing: RAPIDJSON_INCLUDE_DIR) (Required is at least version "1.1.0")
-- Building rapidjson from source
-- Found hdfs.h at: /dev/shm/Arrow/0.17.1/foss-2020b/apache-arrow-0.17.1/cpp/thirdparty/hadoop/include/hdfs.h
-- CMAKE_C_FLAGS: -O2 -ftree-vectorize -march=native -fno-math-errno -O3 -DNDEBUG   -Wall -msse4.2
-- CMAKE_CXX_FLAGS:  -Wno-noexcept-type -O2 -ftree-vectorize -march=native -fno-math-errno -fdiagnostics-color=always -O3 -DNDEBUG  -Wall -msse4.2
-- Looking for backtrace
-- Looking for backtrace - found
-- backtrace facility detected in default set of libraries
-- Found Backtrace: /usr/include
CMake Error at /mnt/irisgpfs/apps/resif/aion/2020b/epyc/software/CMake/3.18.4-GCCcore-10.2.0/share/cmake-3.18/Modules/FindPackageHandleStandardArgs.cmake:165 (message):
  Could NOT find Python3 (missing: Python3_NumPy_INCLUDE_DIRS NumPy) (found
  version "3.6.8")
Call Stack (most recent call first):
  /mnt/irisgpfs/apps/resif/aion/2020b/epyc/software/CMake/3.18.4-GCCcore-10.2.0/share/cmake-3.18/Modules/FindPackageHandleStandardArgs.cmake:458 (_FPHSA_FAILURE_MESSAGE)
  /mnt/irisgpfs/apps/resif/aion/2020b/epyc/software/CMake/3.18.4-GCCcore-10.2.0/share/cmake-3.18/Modules/FindPython/Support.cmake:2984 (find_package_handle_standard_args)
  /mnt/irisgpfs/apps/resif/aion/2020b/epyc/software/CMake/3.18.4-GCCcore-10.2.0/share/cmake-3.18/Modules/FindPython3.cmake:389 (include)
  cmake_modules/FindPython3Alt.cmake:46 (find_package)
  src/arrow/python/CMakeLists.txt:22 (find_package)
```

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in total)
node3108.skitty.os - Linux centos linux 7.9.2009, x86_64, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz (skylake_avx512), Python 3.6.8
See https://gist.github.com/f4aceecd82e437a6e192dde9f43520e7 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in total)
node2651.swalot.os - Linux centos linux 7.9.2009, x86_64, Intel(R) Xeon(R) CPU E5-2660 v3 @ 2.60GHz (haswell), Python 3.6.8
See https://gist.github.com/789514ac37e633425692512eed7c2863 for a full test report.

**Comment by boegel** [comment]
@boegelbot please test @ generoso

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in total)
node3104.skitty.os - Linux centos linux 7.9.2009, x86_64, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz (skylake_avx512), Python 3.6.8
See https://gist.github.com/23ff08b2df7005238e3672a9d84a0e6d for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in total)
node3513.doduo.os - Linux RHEL 8.2, x86_64, AMD EPYC 7552 48-Core Processor (zen2), Python 3.6.8
See https://gist.github.com/5ba0ea82c6313cb65bfd3fe75e35b486 for a full test report.

**Comment by boegel** [comment]
@Falkor The problem you ran into must be a local problem somehow, since `numpy` is provided by `SciPy-bundle` which is listed correctly as dependency for `Arrow`...

**Review by boegel — APPROVED** [review]
lgtm

**Comment by boegel** [comment]
Going in, thanks @fizwit!

**Pull request merged**
