### PR TITLE
{tools}[gfbf/2024a] networkx v3.4.2

### PR DESCRIPTION
**Pull request by Micket**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by Micket** [comment]
@ocaisa somehow the permissions still aren't enough despite it being merged already.

> Failed to post comment: 403, {"message":"Resource not accessible by integration","documentation_url":"https://docs.github.com/rest/issues/comments#create-an-issue-comment","status":"403"}

Can you check the permissions on the easybuilders/easybuiöd-easyconfigs itself? I don't have those permissions.

**Comment by verdurin** [comment]
Test report by @verdurin
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
easybuild-el8.cloud.in.bmrc.ox.ac.uk - Linux Rocky Linux 8.10, x86_64, Intel Xeon Processor (Skylake, IBRS), Python 3.6.8
See https://gist.github.com/verdurin/cd737c59959f9bd64766b82f143c9ee3 for a full test report.

**Comment by verdurin** [comment]
@boegelbot please test @ generoso

**Comment by smoors** [comment]
@boegelbot please test @ jsc-zen3

**Review by smoors — APPROVED** [review]
lgtm

**Comment by smoors** [comment]
Going in, thanks @Micket!

**Pull request merged**
