### PR TITLE
fix homepage + source URL for ELPA (due to switch to new domain)

### PR DESCRIPTION
**Pull request by boegel**
(created using `eb --new-pr`)

partial fix for #17162 (other ELPA easyconfigs also need changed homepage)

no change in checksums

### CODE REVIEW

**Comment by boegel** [comment]
@boegelbot please test @ generoso
EB_ARGS="--sourcepath /tmp/$USER/pr17357 --force-download --stop source"

**Comment by verdurin** [comment]
@boegel from a quick look it appears the failures relate to the older Intel toolchains, and can probably be ignored?

**Comment by branfosj** [comment]
@boegelbot please test @ generoso
EB_ARGS="ELPA-2020.11.001-foss-2020b.eb ELPA-2020.11.001-intel-2020b.eb"

**Comment by branfosj** [comment]
[Those rebuilds](https://github.com/easybuilders/easybuild-easyconfigs/pull/17357#issuecomment-1435534189) were for missing modules while testing #17359

**Review by Micket — APPROVED** [review]
lgtm

**Comment by Micket** [comment]
Going in, thanks @boegel!

**Pull request merged**
