### PR TITLE
{tools}[foss/2020a] IPython v7.15.0 w/ Python 3.8.2

### PR DESCRIPTION
**Pull request by SimonPinches**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by verdurin** [comment]
Test report by @verdurin
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
easybuild.novalocal - Linux centos linux 7.8.2003, x86_64, Intel Xeon Processor (Skylake, IBRS), Python 2.7.5
See https://gist.github.com/46a1ac353ed06878ffa583b898407ec7 for a full test report.

**Comment by verdurin** [comment]
@SimonPinches Any chance of a test report from you?

**Comment by Micket** [comment]
Test report by @Micket
**SUCCESS**
Build succeeded for 7 out of 7 (1 easyconfigs in this PR)
hebbe-c1 - Linux centos linux 7.7.1908, x86_64, Intel Core Processor (Haswell, no TSX), Python 2.7.5
See https://gist.github.com/5c94b0f7f670504b16624d78d49b2588 for a full test report.

**Comment by Micket** [comment]
Test report by @Micket
**SUCCESS**
Build succeeded for 5 out of 5 (1 easyconfigs in this PR)
vera-c1 - Linux centos linux 7.7.1908, x86_64, Intel Xeon Processor (Skylake), Python 2.7.5
See https://gist.github.com/1eb0d9e52bfc3abf7756b0f32e10cc45 for a full test report.

**Comment by verdurin** [comment]
Going in, thanks @SimonPinches!

**Pull request merged**
