### PR TITLE
{tools}[fosscuda/2017b,intelcuda/2017b] wheel v0.30.0

### PR DESCRIPTION
**Pull request by vanzod**
Depends on #7594

### CODE REVIEW

**Comment by vanzod** [comment]
Test report by @vanzod
**SUCCESS**
Build succeeded for 4 out of 4 (4 easyconfigs in this PR)
cermis - Linux debian 9.7, Intel(R) Xeon(R) CPU           X5670  @ 2.93GHz, Python 2.7.13
See https://gist.github.com/b24718dec48291de6594de54b28ca11c for a full test report.

**Comment by akesandgren** [comment]
Kicking travis

**Comment by akesandgren** [comment]
Travis kicked

**Comment by akesandgren** [comment]
Going in, thanks @vanzod!

**Pull request merged**
