### PR TITLE
{vis}[foss/2018b] gnuplot v5.2.5

### PR DESCRIPTION
**Pull request by boegel**
(created using `eb --new-pr`)

edit: requires ~~#7369~~ (`FriBidi` dep for `Pango` dep of `gnuplot`)

### CODE REVIEW

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in this PR)
node2482.golett.os - Linux centos linux 7.5.1804, Intel(R) Xeon(R) CPU E5-2680 v3 @ 2.50GHz, Python 2.7.5
See https://gist.github.com/aaebac6c99effe0b19b87bc1b8b20c66 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in this PR)
node3152.skitty.os - Linux centos linux 7.5.1804, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz, Python 2.7.5
See https://gist.github.com/253a47cd2b9ba56c449681995f260889 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in this PR)
node3152.skitty.os - Linux centos linux 7.5.1804, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz, Python 2.7.5
See https://gist.github.com/50539d3542bf98bb5f7aa098f30d0fd1 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in this PR)
node2002.delcatty.os - Linux centos linux 7.5.1804, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.7.5
See https://gist.github.com/88e68514edc30eb7d275693a81f95187 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in this PR)
node2533.golett.os - Linux centos linux 7.5.1804, Intel(R) Xeon(R) CPU E5-2680 v3 @ 2.50GHz, Python 2.7.5
See https://gist.github.com/3e497afc186d7863c08b32d0750bb1d0 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in this PR)
node3136.skitty.os - Linux centos linux 7.5.1804, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz, Python 2.7.5
See https://gist.github.com/55fc692ebaad8f46f5a60fdf19087311 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in this PR)
node2118.delcatty.os - Linux centos linux 7.5.1804, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.7.5
See https://gist.github.com/cf1629a9aa8ab858613e708c3775c592 for a full test report.

**Comment by verdurin** [comment]
Test report by @verdurin
**FAILED**
Build succeeded for 8 out of 12 (2 easyconfigs in this PR)
rescomp2 - Linux centos linux 7.3.1611, Intel(R) Xeon(R) Gold 6126 CPU @ 2.60GHz, Python 2.7.5
See https://gist.github.com/9c6777b6faced3d3c211c867e714cbea for a full test report.

**Comment by verdurin** [comment]
```
  CCLD     libcmph.la
scannerlexer.c: In function 'yy_get_next_buffer':
scannerlexer.c:1270:18: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
   for ( n = 0; n < max_size && \
                  ^
scannerlexer.c:2472:3: note: in expansion of macro 'YY_INPUT'
   YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
   ^~~~~~~~
giscanner/giscannermodule.c:59:26: warning: '_PyGISourceType_methods' defined but not used [-Wunused-const-variable=]
 static const PyMethodDef _Py##cname##_methods[num_methods];    \
                          ^
giscanner/giscannermodule.c:95:1: note: in expansion of macro 'NEW_CLASS'
 NEW_CLASS (PyGISourceType, "SourceType", GISourceType, 9);
 ^~~~~~~~~
giscanner/giscannermodule.c:59:26: warning: '_PyGISourceSymbol_methods' defined but not used [-Wunused-const-variable=]
 static const PyMethodDef _Py##cname##_methods[num_methods];    \
                          ^
giscanner/giscannermodule.c:94:1: note: in expansion of macro 'NEW_CLASS'
 NEW_CLASS (PyGISourceSymbol, "SourceSymbol", GISourceSymbol, 10);
 ^~~~~~~~~
  CCLD     gi-dump-types
  CCLD     libgirepository-gthash.la
  CCLD     libgirepository-1.0.la
  CCLD     libgiscanner.la
  CCLD     _giscanner.la
  CCLD     libgirepository-internals.la
  CCLD     g-ir-inspect
  CCLD     glib-print
  CCLD     g-ir-compiler
  CCLD     g-ir-generate
  GEN      g-ir-scanner
  GEN      g-ir-annotation-tool
  GICOMP   gir/DBus-1.0.gir
  GICOMP   gir/fontconfig-2.0.gir
  GICOMP   gir/freetype2-2.0.gir
  GICOMP   gir/xrandr-1.3.gir
  GICOMP   gir/GL-1.0.gir
  GICOMP   gir/xlib-2.0.gir
  GICOMP   gir/cairo-1.0.gir
  GICOMP   gir/libxml2-2.0.gir
  GICOMP   gir/xft-2.0.gir
  GICOMP   gir/win32-1.0.gir
  GICOMP   gir/xfixes-4.0.gir
  GISCAN   GLib-2.0.gir
Traceback (most recent call last):
  File "./g-ir-scanner", line 65, in <module>
    from giscanner.scannermain import scanner_main
  File "./giscanner/scannermain.py", line 41, in <module>
    from giscanner.dumper import compile_introspection_binary
  File "./giscanner/dumper.py", line 35, in <module>
    from .gdumpparser import IntrospectionBinary
  File "./giscanner/gdumpparser.py", line 36, in <module>
    from .transformer import TransformerException
  File "./giscanner/transformer.py", line 34, in <module>
    from .girparser import GIRParser
  File "./giscanner/girparser.py", line 31, in <module>
    from .girwriter import COMPATIBLE_GIR_VERSION
  File "./giscanner/girwriter.py", line 29, in <module>
    from .xmlwriter import XMLWriter
  File "./giscanner/xmlwriter.py", line 44, in <module>
    from _giscanner import collect_attributes
  File "./giscanner/libtoolimporter.py", line 68, in load_module
    mod = imp.load_module(name, open(realpath), realpath, suffix)
ImportError: /mgmt/modules/eb/software/LibUUID/1.0.3-GCCcore-7.3.0/lib/libuuid.so.1: version `UUID_1.0' not found (required by /mgmt/modules/eb/software/util-linux/2.32-GCCcore-7.3.0/lib/libblkid.so.1)
make[2]: *** [GLib-2.0.gir] Error 1
make[2]: Leaving directory `/dev/shm/GObjectIntrospection/1.54.1/foss-2018b-Python-2.7.15/gobject-introspection-1.54.1'
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory `/dev/shm/GObjectIntrospection/1.54.1/foss-2018b-Python-2.7.15/gobject-introspection-1.54.1'
make: *** [all] Error 2
 (at easybuild/tools/run.py:501 in parse_cmd_output)
== 2019-01-07 09:01:33,631 easyblock.py:2864 WARNING build failed (first 300 chars): cmd " make -j 24 PYTHON=python" exited with exit code 2 and output:
[ -d gir ] || /usr/bin/mkdir -p gir ; \
sed \
-e s,%CAIRO_SHARED_LIBRARY%,libcairo-gobject.so.2, \
-e s,%CAIRO_GIR_PACKAGE%,cairo-gobject, \
< gir/cairo-1.0.gir.in > gir/cairo-1.0.gir.tmp && mv gir/cairo-1.0.gir.tmp gir/cairo-1.0.gi
```

**Comment by boegel** [comment]
@verdurin You'll need to recompile `cairo`, see #7253

**Comment by verdurin** [comment]
@boegel do you mean `cairo`, or `GObject-Introspection`?

**Comment by boegel** [comment]
@verdurin Potentially both, but certainly `cairo`

**Comment by verdurin** [comment]
Test report by @verdurin
**SUCCESS**
Build succeeded for 1 out of 1 (2 easyconfigs in this PR)
rescomp2 - Linux centos linux 7.3.1611, Intel(R) Xeon(R) Gold 6126 CPU @ 2.60GHz, Python 2.7.5
See https://gist.github.com/d8d315db84e6b824ec01fd2a84f5bc67 for a full test report.

**Comment by verdurin** [comment]
Well, that was quite an adventure.

**Comment by verdurin** [comment]
Going in, thanks @boegel!

**Comment by boegel** [comment]
@verdurin So, what did you need to rebuild in the end? Just `cairo` and `Pango`?

**Comment by mstud** [comment]
@boegel: I ran into the same issue and had to recompile libgd and X11, too, because there were some LibUUID paths in the *.la files there that libtool picked up.

**Pull request merged**
