### PR TITLE
{tools}[GCCcore/13.2.0] mold v2.3.1

### PR DESCRIPTION
**Pull request by Micket**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by Micket** [comment]
@boegelbot please test @ jsc-zen2

**Comment by Micket** [comment]
@boegelbot please test @ generoso

**Comment by Micket** [comment]
Test report by @Micket
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
alvis-c1 - Linux Rocky Linux 8.8, x86_64, Intel Xeon Processor (Skylake), Python 3.6.8
See https://gist.github.com/Micket/1561e4652e553b2e91e9088228d4f158 for a full test report.

**Comment by verdurin** [comment]
Test report by @verdurin
**FAILED**
Build succeeded for 0 out of 1 (1 easyconfigs in total)
easybuild-c7.novalocal - Linux CentOS Linux 7.9.2009, x86_64, Intel Xeon Processor (Skylake, IBRS), Python 3.6.8
See https://gist.github.com/verdurin/62a061094317b2b7e599ae53400a980c for a full test report.

**Comment by verdurin** [comment]
```
The following tests FAILED:
        114 - x86_64-gdb-index-compress-output (Failed)
        118 - x86_64-gdb-index-dwarf5 (Failed)
        119 - x86_64-gdb-index-dwarf64 (Failed)
```
```
114/334 Test #114: x86_64-gdb-index-compress-output ........***Failed    0.20 sec
8<
>8
+ cc -c -o out/test/elf/x86_64/gdb-index-compress-output/c.o -fPIC -g -ggnu-pubnames -gdwarf-4 -xc - -gz
+ cc -B. -o out/test/elf/x86_64/gdb-index-compress-output/exe out/test/elf/x86_64/gdb-index-compress-output/b.so out/test/elf/x86_64/gdb-index-compress-output/c.o -Wl,--gdb-index -Wl,--compress-debug-sections=zlib
+ readelf -WS out/test/elf/x86_64/gdb-index-compress-output/exe
+ grep -Fq .gdb_index
+ out/test/elf/x86_64/gdb-index-compress-output/exe
+ grep -q 'Hello world'
+ DEBUGINFOD_URLS=
+ gdb out/test/elf/x86_64/gdb-index-compress-output/exe -nx -batch -ex 'b main' -ex r -ex 'b trap' -ex c -ex bt -ex quit
+ grep -q 'hello () at .*<stdin>:7' out/test/elf/x86_64/gdb-index-compress-output/log
++ on_error 43
++ code=1
++ echo 'command failed: 43: grep -q '\''hello () at .*<stdin>:7'\'' $t/log'
command failed: 43: grep -q 'hello () at .*<stdin>:7' $t/log
++ trap - EXIT
++ exit 1
```

The others are similar:
```
+ gdb out/test/elf/x86_64/gdb-index-dwarf5/exe -nx -batch -ex 'b main' -ex r -ex 'b trap' -ex c -ex bt -ex quit
+ grep -q 'fn8 () at .*/d.c:6' out/test/elf/x86_64/gdb-index-dwarf5/log
++ on_error 85
++ code=1
++ echo 'command failed: 85: grep -q '\''fn8 () at .*/d.c:6'\'' $t/log'
command failed: 85: grep -q 'fn8 () at .*/d.c:6' $t/log
```
and
```
+ cc -B. -o out/test/elf/x86_64/gdb-index-dwarf64/exe2 out/test/elf/x86_64/gdb-index-dwarf64/f.so out/test/elf/x86_64/gdb-index-dwarf64/g.o -Wl,--gdb-index
+ readelf -WS out/test/elf/x86_64/gdb-index-dwarf64/exe2
+ grep -Fq .gdb_index
+ out/test/elf/x86_64/gdb-index-dwarf64/exe2
+ grep -q 'Hello world'
+ DEBUGINFOD_URLS=
+ gdb out/test/elf/x86_64/gdb-index-dwarf64/exe2 -nx -batch -ex 'b main' -ex r -ex 'b trap' -ex c -ex bt -ex quit
+ grep -q 'fn8 () at .*/d.c:6' out/test/elf/x86_64/gdb-index-dwarf64/log2
++ on_error 94
++ code=1
++ echo 'command failed: 94: grep -q '\''fn8 () at .*/d.c:6'\'' $t/log2'
command failed: 94: grep -q 'fn8 () at .*/d.c:6' $t/log2
++ trap - EXIT
++ exit 1
```

This is on a CentOS 7 build host.

**Comment by SebastianAchilles** [comment]
Test report by @sebastianachilles
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
bwd-rockylinux-92 - Linux Rocky Linux 9.2 (Blue Onyx), x86_64, Intel(R) Core(TM) i7-6900K CPU @ 3.20GHz (broadwell), 2 x NVIDIA NVIDIA GeForce GTX 1060 6GB, 535.104.12, Python 3.9.16
See https://gist.github.com/SebastianAchilles/5c12a49d441a13a21b80a093c6997b91 for a full test report.

**Comment by SebastianAchilles** [comment]
Test report by @sebastianachilles
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
skl-centos-79 - Linux CentOS Linux 7.9.2009, x86_64, Intel(R) Core(TM) i7-8700 CPU @ 3.20GHz (skylake), Python 3.6.8
See https://gist.github.com/SebastianAchilles/b82b32e94e27b07a48eb1aeba6d1a312 for a full test report.

**Comment by boegel** [comment]
@verdurin Can you open an issue on that, so we can follow up on that in a separate PR (especially since @SebastianAchilles didn't see the problems on CentOS 7)

**Review by boegel — APPROVED** [review]
lgtm

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
node3100.skitty.os - Linux RHEL 8.8, x86_64, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz (skylake_avx512), Python 3.6.8
See https://gist.github.com/boegel/cb68a39c8af90ece32d20a06852bc96f for a full test report.

**Comment by boegel** [comment]
Going in, thanks @Micket!

**Pull request merged**
