### PR TITLE
Add buildenv-default for 2020a and 2020b toolchains

### PR DESCRIPTION
**Pull request by Micket**

### CODE REVIEW

**Review by akesandgren — APPROVED** [review]
LGTM

**Comment by Micket** [comment]
Test report by @Micket
**SUCCESS**
Build succeeded for 6 out of 6 (6 easyconfigs in total)
vera-c1 - Linux centos linux 7.9.2009, x86_64, Intel Xeon Processor (Skylake), Python 2.7.5
See https://gist.github.com/e852c11de54b7e7b18c1cb7e3539bc9c for a full test report.

**Comment by Micket** [comment]
Test report by @Micket
**SUCCESS**
Build succeeded for 4 out of 4 (4 easyconfigs in total)
alvis-c1 - Linux centos linux 7.9.2009, x86_64, Intel Xeon Processor (Skylake), Python 3.6.8
See https://gist.github.com/4d0016dacd45ac143c8d87932793cedf for a full test report.

**Comment by Micket** [comment]
re-trigger github actions

**Comment by akesandgren** [comment]
@boegelbot please test @ generoso

**Comment by akesandgren** [comment]
Re-trigger test

**Comment by boegel** [comment]
Going in, thanks @Micket!

**Pull request merged**
