### PR TITLE
{chem}[foss/2019b,intel/2019b] kim-api v2.1.3, openkim-models v20190725

### PR DESCRIPTION
**Pull request by schiotz**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by migueldiascosta** [comment]
Test report by @migueldiascosta
**SUCCESS**
Build succeeded for 4 out of 4 (4 easyconfigs in this PR)
generoso - Linux centos linux 7.6.1810, Intel(R) Xeon(R) CPU E5-2660 v4 @ 2.00GHz, Python 3.6.8
See https://gist.github.com/b5468b31cb440938911f0d9de3980044 for a full test report.

**Comment by migueldiascosta** [comment]
can't these be moved to lower subtoolchains? nothing requires MPI or math libraries, does it?

At least the API could be moved to `GCCcore`, the models probably could to, unless using different compilers result in a significant performance difference, in which case they could be moved to `GCC` and `iccifort`

**Comment by schiotz** [comment]
@migueldiascosta Good point.  I will try it out.

**Comment by schiotz** [comment]
@migueldiascosta 
The performance benefit of keeping the models in the Intel toolchains is minor, there are a few models that gain significantly, most do not care.  However, placing it all in GCCcore does not work.

With the api and the models in GCCcore, the some of the models cannot load into a simulator built with intel/2019b.  I am not sure why.

Having the api in GCCcore and the models in iccifort/intel does not work at all.  When compiling the Fortran models, the compiler complains that "some modules were not built with this version of the compiler" or something like that.

It is therefore necessary to keep both the API and the models in both toolchains.  The remaining question is whether they should be moved to GCCcore and iccifort, or stay in foss and intel.  Both work, but moving them up runs the risk of the models being built only with GCCcore and then loaded into an Intel-compiled simulator and fail mysteriously.  Keeping them in foss/intel prevents that, but may force dependencies up into the same toolchains (except that there are no such dependencies, at present).

What is your opinion?

**Comment by migueldiascosta** [comment]
@schiotz I suppose in this case we can simply stay in foss and intel, but I've also seen that "some modules were not built with this version of the compiler" with 2019b and I think that's a regression the way Intel compiler wrappers check compiler versions (@boegel ?)

**Comment by schiotz** [comment]
@migueldiascosta Thanks!  Then let us stay with foss and intel, i.e. the current version of this PR.

**Comment by migueldiascosta** [comment]
Going in, thanks @schiotz!

**Pull request merged**
