### PR TITLE
{bio}[foss/2018b] iCount v20180820, psutil v5.4.7, pybedtools v0.7.10 & more w/ Python 3.6.6

### PR DESCRIPTION
**Pull request by smoors**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by bartoldeman** [comment]
@boegel should Sphinx in here now be converted to your new PythonBundle easyblock? Otherwise this looks good to me.

**Comment by boegel** [comment]
@bartoldeman It would be nice if people picked up on `PythonPackage`, but there's no point in blocking PRs over it unless we make the tests fail over it imho... I'll look into that, but perhaps only after the release of EasyBuild v3.8.0 which includes the `PythonBundle` easyblock...

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 6 out of 6 (6 easyconfigs in this PR)
node3111.skitty.os - Linux centos linux 7.5.1804, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz, Python 2.7.5
See https://gist.github.com/81977de6afc2f859e5e921afa4ee8dd7 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 6 out of 6 (6 easyconfigs in this PR)
node2007.delcatty.os - Linux centos linux 7.5.1804, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.7.5
See https://gist.github.com/515dd7da4946a298cc99ef234f5179a4 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 10 out of 10 (6 easyconfigs in this PR)
node2699.swalot.os - Linux centos linux 7.5.1804, Intel(R) Xeon(R) CPU E5-2660 v3 @ 2.60GHz, Python 2.7.5
See https://gist.github.com/eb529a557f4e1ff0e71e5140cc68e725 for a full test report.

**Comment by boegel** [comment]
Going in, thanks @smoors!

**Pull request merged**
