### PR TITLE
{bio}[foss/2018b] Trim_Galore v0.6.2 w/ Python 3.6.6

### PR DESCRIPTION
**Pull request by sassy-crick**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by boegel** [comment]
@sassy-crick duplicate of #8280?

**Comment by sassy-crick** [comment]
@boegel nope. This version is using Python-3.6.6. whereas PR 8280 is using 2.7.15. Please double check in case I missed out something. Thanks.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
node3115.skitty.os - Linux centos linux 7.6.1810, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz, Python 2.7.5
See https://gist.github.com/096384e0e60ae6318b84da52c94db075 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
node2402.golett.os - Linux centos linux 7.6.1810, Intel(R) Xeon(R) CPU E5-2680 v3 @ 2.50GHz, Python 2.7.5
See https://gist.github.com/57781ad5e23079a3c4d06cee4324e222 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
node2006.delcatty.os - Linux centos linux 7.6.1810, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.7.5
See https://gist.github.com/0bbeec2dce22263a9011d23f0ce14786 for a full test report.

**Comment by boegel** [comment]
@sassy-crick Thanks for clarifying!

The enhancement made in https://github.com/easybuilders/easybuild-framework/pull/2863 (to be included with the upcoming EasyBuild v3.9.1) will make this harder to miss in the future.

Don't hesitate to pack two similar easyconfigs like these in a single PR next time though...

**Comment by boegel** [comment]
Going in, thanks @sassy-crick!

**Pull request merged**
