### PR TITLE
{lib}[GCCcore/10.2.0] MariaDB v10.5.8, MariaDB-connector-c v3.1.11, Judy v1.0.5, ...

### PR DESCRIPTION
**Pull request by zao**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by zao** [comment]
Test report by @zao
**SUCCESS**
Build succeeded for 4 out of 4 (4 easyconfigs in total)
eb-u2004 - Linux Ubuntu 20.04, x86_64, Intel(R) Core(TM) i7-8700K CPU @ 3.70GHz, Python 3.8.5
See https://gist.github.com/77386767ec680cae20f2720f7882231e for a full test report.

**Comment by lexming** [comment]
Test report by @lexming
**SUCCESS**
Build succeeded for 6 out of 6 (4 easyconfigs in total)
node374.hydra.os - Linux centos linux 7.9.2009, x86_64, Intel(R) Xeon(R) Gold 6148 CPU @ 2.40GHz, Python 2.7.5
See https://gist.github.com/ea070f507969aeaf6c6a3a5021dd5a2b for a full test report.

**Comment by lexming** [comment]
Test report by @lexming
**FAILED**
Build succeeded for 7 out of 8 (4 easyconfigs in total)
node100.hydra.os - Linux centos linux 7.9.2009, x86_64, Intel(R) Xeon(R) CPU E5-2680 v2 @ 2.80GHz, Python 2.7.5
See https://gist.github.com/c21565c142a61008cca3dd32ca6cc8a7 for a full test report.

**Comment by zao** [comment]
@lexming That FAILED report is odd, a transient problem on the node or something actually wrong?

**Comment by lexming** [comment]
Test report by @lexming
**FAILED**
Build succeeded for 3 out of 4 (4 easyconfigs in total)
node114.hydra.os - Linux centos linux 7.9.2009, x86_64, Intel(R) Xeon(R) CPU E5-2680 v2 @ 2.80GHz, Python 2.7.5
See https://gist.github.com/ab8fb3dabf2bdd952cfaea4e7f51a60e for a full test report.

**Comment by lexming** [comment]
Test report by @lexming
**SUCCESS**
Build succeeded for 4 out of 4 (4 easyconfigs in total)
node108.hydra.os - Linux centos linux 7.9.2009, x86_64, Intel(R) Xeon(R) CPU E5-2680 v2 @ 2.80GHz, Python 2.7.5
See https://gist.github.com/c8d092da21f6b267b23e4e5048900269 for a full test report.

**Review by lexming — APPROVED** [review]
@zao fixed my test, the node was grumpy :slightly_smiling_face: 

LGTM

**Pull request merged**
