### PR TITLE
{lang}[foss/2016b] Python 3.6.0 (w/ lots of extensions)

### PR DESCRIPTION
**Pull request by fizwit**
Python 3.6.0  This is a fat Python with lots of packages.

### CODE REVIEW

**Comment by boegel** [comment]
@fizwit I changed the target branch to `develop`, otherwise this is impossible to review/merge :)

**Comment by boegel** [comment]
@fizwit This is a lot fatter than what we usually go with in the central repo...
We usually try to limit the dependencies to those that are required for Python itself (not for particular extensions).

There are several extensions that are commented out, is there a good reason for that?

This looks more like a site-specific version of a Python easyconfig to me, since including this would be a switch in 'policy' for central Python easyconfigs...

Thoughts?

**Comment by boegel** [comment]
@fizwit Also, do you mind changing the PR title a bit to better reflect the contents of the PR?

**Comment by fizwit** [comment]
Sure Like Python3.6.0

**Comment by fizwit** [comment]
What about Python-3.6.0-foss-2016b-bio for a new naming concept?  We have tried to incorporate all the module from anaconda into our local build.

**Comment by boegel** [comment]
@fizwit Using a `-bio` versionsuffix may make sense, yes.
But it may also complicate things, e.g. if you start including this Python variant as a dependency in other easyconfigs...

In any case, the currently commented our extensions (including useful ones like `scikit-*`) should be resolved (i.e. either removed or decommented).

**Pull request closed without merging**
