### PR TITLE
add missing GCCcore-6.3.0_fix-sanitizer_linux.patch in GCCcore 6.4.0 easyconfig

### LINKED ISSUE #9345: GCCcore-6.4.0
Dear Easy-Builders,

I try to build the quite old compiler gcc-6.4.0 using

> eb GCCcore-6.4.0.eb

and that build fails. But the logfile, which is appended to the issue, contains only the first 300 characters, which show no error at all. Therefore I went to the corresponding build directory, run make again, and get the compiler error:

> ../../../../libsanitizer/sanitizer_common/sanitizer_stoptheworld_linux_libcdep.cc: In function ‘int __sanitizer::TracerThread(void*)’:
../../../../libsanitizer/sanitizer_common/sanitizer_stoptheworld_linux_libcdep.cc:270:22: error: aggregate ‘sigaltstack handler_stack’ has incomplete type and cannot be defined
   struct sigaltstack handler_stack;

What puzzles me, is that there is already a [patch for that problem](https://gist.github.com/froland/322a3320fcabd46a5702bd4a2a228198) and the patch is there. The logfile also states, that it applies the patch.

Do you have any hints, what I could do to correct that, or what I do wrong?

I see also a small relation to the [issue easybuilders/easybuild-easyblocks#495 on easybuild](https://github.com/easybuilders/easybuild/issues/495), which got a response stating, that gcc 8.2 might lead to problems with binutils 2.30. My system has installed the gcc-7.4.0, which is also newer than the gcc-6.4.0. 

My easybuild-version is:

> eb --version
This is EasyBuild 4.0.1 (framework: 4.0.1, easyblocks: 4.0.1) on host moivre.

[easybuild-nEWZ6N.log](https://github.com/easybuilders/easybuild-easyblocks/files/3870451/easybuild-nEWZ6N.log)

### PR DESCRIPTION
**Pull request by boegel**
fixes #9345 reported by @ANaumann85

### CODE REVIEW

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
node3157.skitty.os - Linux centos linux 7.7.1908, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz, Python 3.6.8
See https://gist.github.com/6b00a8de19ea89a76e56217b14fdf218 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
generoso-1 - Linux centos linux 7.6.1810, Intel(R) Xeon(R) CPU E5-2660 v4 @ 2.00GHz, Python 3.6.8
See https://gist.github.com/717e096582b0a155e7563f116760aa9b for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
node2652.swalot.os - Linux centos linux 7.7.1908, Intel(R) Xeon(R) CPU E5-2660 v3 @ 2.60GHz, Python 2.7.5
See https://gist.github.com/3687ab5ca3a10a14b4bd09f7c018a598 for a full test report.

**Comment by migueldiascosta** [comment]
Going in, thanks @boegel!

**Pull request merged**
