### PR TITLE
{astro}[foss/2020a] CRPropa v3.1.6 w/ Python 3.8.2

### PR DESCRIPTION
**Pull request by jose-d**
(created using `eb --new-pr`)

there is new release of CRPropa there at https://github.com/CRPropa/CRPropa3/releases, so let's have it available in Easybuild too for recent toolchain.

### CODE REVIEW

**Comment by jose-d** [comment]
Test report by @jose-d
**SUCCESS**
Build succeeded for 0 out of 0 (1 easyconfigs in this PR)
koiosvm1 - Linux centos linux 7.8.2003, x86_64, Intel Xeon Processor (Skylake, IBRS), Python 2.7.5
See https://gist.github.com/485db3aedff206f46e5cb6ddd3112f7e for a full test report.

**Comment by jose-d** [comment]
Test report by @jose-d
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
koiosvm1 - Linux centos linux 7.8.2003, x86_64, Intel Xeon Processor (Skylake, IBRS), Python 2.7.5
See https://gist.github.com/88ea0af33b821c5df51837ddbdf48814 for a full test report.

**Comment by jose-d** [comment]
I see.. 
`found 2 variants of 'HDF5' dependency in easyconfigs using '2020a' toolchain generation`

**Comment by jose-d** [comment]
Test report by @jose-d
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
koiosvm1 - Linux centos linux 7.8.2003, x86_64, Intel Xeon Processor (Skylake, IBRS), Python 2.7.5
See https://gist.github.com/2322d21b1906ecf9acb790a3cc8f2b45 for a full test report.

**Comment by verdurin** [comment]
Test report by @verdurin
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
easybuild.novalocal - Linux centos linux 7.8.2003, x86_64, Intel Xeon Processor (Skylake, IBRS), Python 2.7.5
See https://gist.github.com/6158ce59e615d1e7abff33e6134a398a for a full test report.

**Comment by verdurin** [comment]
Going in, thanks @jose-d!

**Pull request merged**
