### PR TITLE
{phys}[foss/2019b,intel/2019b] BerkeleyGW v2.1.0 w/ Python 3.7.4

### PR DESCRIPTION
**Pull request by migueldiascosta**
(created using `eb --new-pr`)

requires ~~https://github.com/easybuilders/easybuild-easyblocks/pull/1951~~

### CODE REVIEW

**Comment by migueldiascosta** [comment]
Test report by @migueldiascosta
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in this PR)
sms - Linux centos linux 7.6.1810, AMD EPYC 7601 32-Core Processor, Python 2.7.5
See https://gist.github.com/da3b75e76e37214c35e39b0182f60fbe for a full test report.

**Comment by boegel** [comment]
(close/re-open now https://github.com/easybuilders/easybuild-easyblocks/pull/1951 is merged)

@migueldiascosta Is this still WIP?

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in this PR)
generoso-1 - Linux centos linux 7.6.1810, Intel(R) Xeon(R) CPU E5-2660 v4 @ 2.00GHz, Python 3.6.8
See https://gist.github.com/1de81b6360317492e93f144e9541025e for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in this PR)
node3131.skitty.os - Linux centos linux 7.7.1908, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz, Python 3.6.8
See https://gist.github.com/fc1b2d592f9db3fbcb86973720c4534b for a full test report.

**Comment by migueldiascosta** [comment]
with the caveat that not all tests pass, it seems to be good enough...

**Comment by migueldiascosta** [comment]
Test report by @migueldiascosta
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in this PR)
generoso - Linux centos linux 7.6.1810, Intel(R) Xeon(R) CPU E5-2660 v4 @ 2.00GHz, Python 3.6.8
See https://gist.github.com/b02d4ff525b55cca3a492d638cf3abb0 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in this PR)
node3109.skitty.os - Linux centos linux 7.7.1908, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz, Python 3.6.8
See https://gist.github.com/ea61575eb7438e2fc8dede197206c448 for a full test report.

**Comment by boegel** [comment]
Going in, thanks @migueldiascosta!

**Pull request merged**
