### PR TITLE
Fix order of cffi in Python ECs

### PR DESCRIPTION
**Pull request by Flamefire**
(created using `eb --new-pr`)

cryptography requires cffi and hence fails to install otherwise

### CODE REVIEW

**Comment by Flamefire** [comment]
Test report by @Flamefire
**FAILED**
Build succeeded for 2 out of 12 (3 easyconfigs in total)
taurusa4 - Linux centos linux 7.7.1908, x86_64, Intel(R) Xeon(R) CPU E5-2603 v4 @ 1.70GHz (broadwell), Python 2.7.5
See https://gist.github.com/7b0cb9f69344eaca66545ec3edd2af56 for a full test report.

**Review by Micket — APPROVED** [review]
lgtm

**Comment by Micket** [comment]
You seem to be having license issues.  Not sure I can easily provide test reports for those old intel versions either

**Comment by Flamefire** [comment]
> You seem to be having license issues. Not sure I can easily provide test reports for those old intel versions either

True. Already filtered out the older ones but missed intelcuda as the name. As the change is the same I'd say keep it. No idea how to get the new licenses working for 2017...

**Comment by Flamefire** [comment]
Test report by @Flamefire
**FAILED**
Build succeeded for 0 out of 1 (1 easyconfigs in total)
taurusa4 - Linux centos linux 7.7.1908, x86_64, Intel(R) Xeon(R) CPU E5-2603 v4 @ 1.70GHz (broadwell), Python 2.7.5
See https://gist.github.com/6d37e555e0ac24d703d6199a6471c656 for a full test report.

**Comment by Flamefire** [comment]
Test report by @Flamefire
**FAILED**
Build succeeded for 0 out of 1 (1 easyconfigs in total)
taurusa4 - Linux centos linux 7.7.1908, x86_64, Intel(R) Xeon(R) CPU E5-2603 v4 @ 1.70GHz (broadwell), Python 2.7.5
See https://gist.github.com/b56c66e2f9ac15ce19495743ea24d0bb for a full test report.

**Comment by Flamefire** [comment]
Test report by @Flamefire
**FAILED**
Build succeeded for 0 out of 1 (1 easyconfigs in total)
taurusa4 - Linux centos linux 7.7.1908, x86_64, Intel(R) Xeon(R) CPU E5-2603 v4 @ 1.70GHz (broadwell), Python 2.7.5
See https://gist.github.com/dcf6f0cc573cbca981c5121f323f2f45 for a full test report.

**Comment by Flamefire** [comment]
Test report by @Flamefire
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
taurusa4 - Linux centos linux 7.7.1908, x86_64, Intel(R) Xeon(R) CPU E5-2603 v4 @ 1.70GHz (broadwell), Python 2.7.5
See https://gist.github.com/81241b5f1002468ca9a4676be3aa389f for a full test report.

**Comment by Micket** [comment]
Test report by @Micket
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in total)
alvis-c1 - Linux centos linux 7.9.2009, x86_64, Intel Xeon Processor (Skylake), Python 3.6.8
See https://gist.github.com/6fa2f104419311c329703f890b7e3f30 for a full test report.

**Review by Micket — APPROVED** [review]
lgtm

**Comment by Micket** [comment]
Test report by @Micket
**FAILED**
Build succeeded for 1 out of 2 (2 easyconfigs in total)
alvis-c1 - Linux centos linux 7.9.2009, x86_64, Intel Xeon Processor (Skylake), Python 3.6.8
See https://gist.github.com/e1d4d7b41c7df262f3b6afb95b895e52 for a full test report.

**Comment by Flamefire** [comment]
@Micket Build failure looks unrelated to this change. Some options set somewhere maybe? See https://stackoverflow.com/questions/27290086/gcc-canaries-undefined-reference-to-stack-chk-guard

**Comment by Micket** [comment]
Test report by @Micket
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in total)
alvis-c1 - Linux centos linux 7.9.2009, x86_64, Intel Xeon Processor (Skylake), Python 3.6.8
See https://gist.github.com/3c6b82c35d669391aa7534328bf55b06 for a full test report.

**Comment by Micket** [comment]
I'm not sure what happened to those 2 easyconfigs. They took forever to build, and, basically 0 load on the build node as well. I suspect filesystem issues. Retrying them,

**Comment by Micket** [comment]
Going in, thanks @Flamefire!

**Pull request merged**
