### PR TITLE
update $R_LIBS_SITE rather than $R_LIBS in easyconfigs installing R packages

### PR DESCRIPTION
**Pull request by boegel**
companion PR for https://github.com/easybuilders/easybuild-easyblocks/pull/2326

### CODE REVIEW

**Comment by boegel** [comment]
Hmm, I'm not sure it's worth adding the missing checksums for those ancient easyconfigs (but I do want to change the `R_LIBS` to `R_LIBS_SITE` there)...

Full list of touched easyconfigs with missing checksums:

```
OOMPA-3.1.2-intel-2016b-R-3.3.1.eb
R-bundle-Bioconductor-3.2-foss-2016a-R-3.2.3.eb
R-bundle-Bioconductor-3.2-intel-2016a-R-3.2.3.eb
R-bundle-Bioconductor-3.3-intel-2016b-R-3.3.1.eb
R-bundle-Bioconductor-3.5-intel-2017a-R-3.4.0.eb
evmix-2.6-intel-2016b-R-3.3.1.eb
spectral.methods-0.7.2.133-intel-2017b-R-3.4.3.eb
spectral.methods-0.7.2.133-intel-2018a-R-3.4.4.eb
```

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 30 out of 30 (30 easyconfigs in total)
node2700.swalot.os - Linux centos linux 7.9.2009, x86_64, Intel(R) Xeon(R) CPU E5-2660 v3 @ 2.60GHz (haswell), Python 3.6.8
See https://gist.github.com/ff1a7f2224590fba0b1f52c127b68150 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 4 out of 4 (4 easyconfigs in total)
node2700.swalot.os - Linux centos linux 7.9.2009, x86_64, Intel(R) Xeon(R) CPU E5-2660 v3 @ 2.60GHz (haswell), Python 3.6.8
See https://gist.github.com/e5ad1ffc882ebb23cc723e1ffcc432e1 for a full test report.

**Review by branfosj — APPROVED** [review]
lgtm

**Comment by branfosj** [comment]
Going in, thanks @boegel!

**Pull request merged**
