### PR TITLE
add patch to fix tree-optimization bug in GCC 13.2.0 for ARM architectures with SVE support

### PR DESCRIPTION
**Pull request by casparvl**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by casparvl** [comment]
Fixes the error encountered at https://github.com/EESSI/software-layer/pull/479#issuecomment-1957091774 and described at https://gitlab.com/eessi/support/-/issues/52 . 

I found this upstream bug reporting the same issue https://gcc.gnu.org/bugzilla/show_bug.cgi?id=111478 . The patch included in this PR also comes from upstream:  https://gcc.gnu.org/git/gitweb.cgi?p=gcc.git;h=e5f1956498251a4973d52c8aad3faf34d0443169 and was amended with a commit this commit https://github.com/gcc-mirror/gcc/commit/c39cdd9e654540f74cd2478019c40f1611554a44 as that implements an operator used in the patch.

With the attached GCCcore easyconfig, I was able to build the `casacore` software, which triggered the original bug.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
node3129.skitty.os - Linux RHEL 8.8, x86_64, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz, Python 3.6.8
See https://gist.github.com/boegel/a51c9ff45f1af01d2859a44072e98915 for a full test report.

**Comment by boegel** [comment]
@boegelbot please test @ jsc-zen3
CORE_CNT=16

**Comment by boegel** [comment]
@boegelbot please test @ generoso
CORE_CNT=16

**Comment by jfgrimm** [comment]
Test report by @jfgrimm
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
node091.viking2.yor.alces.network - Linux Rocky Linux 8.8, x86_64, AMD EPYC 7643 48-Core Processor, Python 3.6.8
See https://gist.github.com/jfgrimm/0ccca9b5abcdfa9d80405c0ce3f8519d for a full test report.

**Review by boegel — APPROVED** [review]
lgtm

**Comment by boegel** [comment]
Going in, thanks @casparvl!

**Pull request merged**
