### PR TITLE
add missing moduleclass in UCLUST easyconfig

### PR DESCRIPTION
**Pull request by FokkeDijkstra**
(created using `eb --new-pr`)

### CODE REVIEW

**Review by Micket — CHANGES_REQUESTED** [review]
Could you please also fix the urls to https so that the test suite is happy?

**Comment by verdurin** [comment]
@FokkeDijkstra any update on this one?

**Comment by FokkeDijkstra** [comment]
This slipped from my attention. I will update the PR.

**Comment by verdurin** [comment]
Test report by @verdurin
**FAILED**
Build succeeded for 0 out of 1 (1 easyconfigs in total)
nuc.lan - Linux Fedora 32, x86_64, Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz, Python 3.8.6
See https://gist.github.com/8a786794f824dce9585116c89fe4e734 for a full test report.

**Review by boegel — APPROVED** [review]
lgtm

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
node3600.doduo.os - Linux RHEL 8.2, x86_64, AMD EPYC 7552 48-Core Processor (zen2), Python 3.6.8
See https://gist.github.com/22a2738c0bde31f61a986668965833b3 for a full test report.

**Comment by boegel** [comment]
Going in, thanks @FokkeDijkstra!

**Pull request merged**
