### PR TITLE
{bio}[gompi/2019b] NGS v2.10.4, ncbi-vdb v2.10.4, SRA-Toolkit v2.10.4, ... w/ Python 2.7.16

### PR DESCRIPTION
**Pull request by lexming**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by lexming** [comment]
Test report by @lexming
**SUCCESS**
Build succeeded for 5 out of 5 (5 easyconfigs in this PR)
login2.cerberus.os - Linux centos linux 7.7.1908, Intel(R) Xeon(R) Gold 6126 CPU @ 2.60GHz, Python 2.7.5
See https://gist.github.com/c1415fd085b114a748c69d5c42184800 for a full test report.

**Comment by zao** [comment]
Test report by @zao
**SUCCESS**
Build succeeded for 5 out of 5 (5 easyconfigs in this PR)
freja - Linux ubuntu 18.04, Intel(R) Core(TM) i7-8700K CPU @ 3.70GHz, Python 2.7.17
See https://gist.github.com/5f1b027e50685232bfa452830655b2b6 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**FAILED**
Build succeeded for 1 out of 5 (5 easyconfigs in this PR)
node3129.skitty.os - Linux centos linux 7.7.1908, x86_64, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz (skylake_avx512), Python 3.6.8
See https://gist.github.com/82fa40bde943e5327d06d39190b2ebe1 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**FAILED**
Build succeeded for 1 out of 5 (5 easyconfigs in this PR)
node3401.kirlia.os - Linux centos linux 7.7.1908, x86_64, Intel(R) Xeon(R) Gold 6240 CPU @ 2.60GHz (cascadelake), Python 2.7.5
See https://gist.github.com/ebf8dbd31a3faceb1041c23b8ced2772 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**FAILED**
Build succeeded for 1 out of 5 (5 easyconfigs in this PR)
node2401.golett.os - Linux centos linux 7.7.1908, x86_64, Intel(R) Xeon(R) CPU E5-2680 v3 @ 2.50GHz (haswell), Python 2.7.5
See https://gist.github.com/74e4098589853903376b7fb4031a4ec8 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**FAILED**
Build succeeded for 1 out of 5 (5 easyconfigs in this PR)
node3401.kirlia.os - Linux centos linux 7.7.1908, x86_64, Intel(R) Xeon(R) Gold 6240 CPU @ 2.60GHz (cascadelake), Python 2.7.5
See https://gist.github.com/31773b8c54449da9961570c312ce72fa for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**FAILED**
Build succeeded for 1 out of 5 (5 easyconfigs in this PR)
node2401.golett.os - Linux centos linux 7.7.1908, x86_64, Intel(R) Xeon(R) CPU E5-2680 v3 @ 2.50GHz (haswell), Python 2.7.5
See https://gist.github.com/05de218d3cfa61de3c2b33f7fa60835c for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**FAILED**
Build succeeded for 1 out of 5 (5 easyconfigs in this PR)
node3129.skitty.os - Linux centos linux 7.7.1908, x86_64, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz (skylake_avx512), Python 3.6.8
See https://gist.github.com/4297ed6a30e1e6b58027a298acecbedc for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 5 out of 5 (5 easyconfigs in this PR)
generoso-3 - Linux centos linux 7.6.1810, x86_64, Intel(R) Xeon(R) CPU E5-2660 v4 @ 2.00GHz, Python 3.6.8
See https://gist.github.com/b0d968308dcc5c974df209b0e761b3e2 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**FAILED**
Build succeeded for 4 out of 5 (5 easyconfigs in this PR)
node3401.kirlia.os - Linux centos linux 7.7.1908, x86_64, Intel(R) Xeon(R) Gold 6240 CPU @ 2.60GHz (cascadelake), Python 2.7.5
See https://gist.github.com/ac848c1a9ed36e864c07cbc6943dd907 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**FAILED**
Build succeeded for 4 out of 5 (5 easyconfigs in this PR)
node2401.golett.os - Linux centos linux 7.7.1908, x86_64, Intel(R) Xeon(R) CPU E5-2680 v3 @ 2.50GHz (haswell), Python 2.7.5
See https://gist.github.com/5d032980abba814d526b92b907333f65 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 5 out of 5 (5 easyconfigs in this PR)
node3129.skitty.os - Linux centos linux 7.7.1908, x86_64, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz (skylake_avx512), Python 3.6.8
See https://gist.github.com/4978f2b908ea34617b3b5f842fead2e5 for a full test report.

**Comment by boegel** [comment]
@lexming This looks like a genuine problem to me...

```
make[2]: Entering directory `/tmp/easybuild_build/SRAToolkit/2.10.4/gompi-2019b/sra-tools-2.10.4/tools/bam-loader'
/software/binutils/2.32-GCCcore-8.3.0/bin/ld.gold: error: cannot find -ltk-version
rcexplain.o:rcexplain.c:function Usage: error: undefined reference to 'KAppVersion'
/tmp/easybuild_build/SRAToolkit/2.10.4/gompi-2019b/ncbi-vdb/linux/gcc/x86_64/rel/ilib/libkapp.a(main.o):main.c:function KMane: error: undefined reference to 'KAppVersion'
/tmp/easybuild_build/SRAToolkit/2.10.4/gompi-2019b/ncbi-vdb/linux/gcc/x86_64/rel/ilib/libkapp.a(args.o):args.c:function ArgsHandleVersion.part.12: error: undefined reference to 'KAppVersion'
collect2: error: ld returned 1 exit status
make[3]: *** [/tmp/easybuild_build/SRAToolkit/2.10.4/gompi-2019b/sra-tools/linux/gcc/x86_64/rel/bin/rcexplain] Error 1
```

**Comment by boegel** [comment]
@lexming Maybe it requires `parallel = 1` (or a patch) to always build correctly?

**Comment by lexming** [comment]
Test report by @lexming
**SUCCESS**
Build succeeded for 5 out of 5 (5 easyconfigs in this PR)
node150.hydra.os - Linux centos linux 7.7.1908, x86_64, Intel(R) Xeon(R) CPU E5-2680 v2 @ 2.80GHz, Python 2.7.5
See https://gist.github.com/62451b96843a05b1a0953450fbf55075 for a full test report.

**Comment by lexming** [comment]
@boegel previous test is with 12 cores and it succeeded. I might be something different, I'll take a closer look at your failed test.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 5 out of 5 (5 easyconfigs in this PR)
node3401.kirlia.os - Linux centos linux 7.7.1908, x86_64, Intel(R) Xeon(R) Gold 6240 CPU @ 2.60GHz (cascadelake), Python 2.7.5
See https://gist.github.com/8fc442083b3df7cceda352b08b5e135a for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 5 out of 5 (5 easyconfigs in this PR)
node2401.golett.os - Linux centos linux 7.7.1908, x86_64, Intel(R) Xeon(R) CPU E5-2680 v3 @ 2.50GHz (haswell), Python 2.7.5
See https://gist.github.com/a262c5e156dd763cf9687d0642204f35 for a full test report.

**Comment by boegel** [comment]
Going in, thanks @lexming!

**Pull request merged**
