### PR TITLE
fix failing cryptography/PyNaCl/bcrypt/pluggy installation with Python 3.7.2 because of missing build-backend in pyproject.toml

### PR DESCRIPTION
**Pull request by boegel**
(created using `eb --new-pr`)
see also #16490

### CODE REVIEW

**Comment by boegel** [comment]
@boegelbot please test @ generoso

**Comment by boegel** [comment]
@boegelbot please test @ jsc-zen2

**Comment by casparvl** [comment]
Test report by @casparvl
**FAILED**
Build succeeded for 0 out of 1 (1 easyconfigs in total)
tcn2.local.snellius.surf.nl - Linux Rocky Linux 8.7, x86_64, AMD EPYC 7H12 64-Core Processor, Python 3.6.8
See https://gist.github.com/c07c976eaf7f97dc82acff39dcb5c91b for a full test report.

**Comment by boegel** [comment]
easyconfigs using `GCCcore/8.2.0` toolchain have been archived in `5.0.x` branch, so not going to follow up on this; see also https://docs.easybuild.io/policies/toolchains

**Pull request closed without merging**
