### PR TITLE
update to LAPACK 3.9.1 for goblf/2020b

### PR DESCRIPTION
**Pull request by boegel**
This was merged very recently in `develop` (see #12381), not included yet with an EasyBuild release...

### CODE REVIEW

**Comment by boegel** [comment]
@boegelbot please test @ generoso
EB_ARGS="ScaLAPACK-2.1.0-gompi-2020b-bl.eb goblf-2020b.eb LAPACK-3.9.1-GCC-10.2.0.eb HPL-2.3-goblf-2020b.eb"

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 4 out of 4 (4 easyconfigs in total)
node3507.doduo.os - Linux RHEL 8.2, x86_64, AMD EPYC 7552 48-Core Processor (zen2), Python 3.6.8
See https://gist.github.com/7e6dfa0390d40492bade15680baf5bc7 for a full test report.

**Review by akesandgren — APPROVED** [review]
LGTM

**Comment by akesandgren** [comment]
Going in, thanks @boegel!

**Pull request merged**
