### PR TITLE
{bio}[GCCcore/10.2.0] cutadapt v2.10 w/ Python 3.8.6

### PR DESCRIPTION
**Pull request by DirectorSloan**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by verdurin** [comment]
@boegelbot please test @ generoso

**Comment by verdurin** [comment]
Test report by @verdurin
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
easybuild-c7.novalocal - Linux CentOS Linux 7.9.2009, x86_64, Intel Xeon Processor (Skylake, IBRS), Python 3.6.8
See https://gist.github.com/verdurin/6709cdb607094ff47037f6a46f058b72 for a full test report.

**Comment by Micket** [comment]
Any particular reason to hold this back to version 2.10 since there are many newer versions available and it doesn't seem to have any strict dependencies on old packages.

**Comment by verdurin** [comment]
@DirectorSloan any thoughts about updating the version of `cutadapt` as suggested by @Micket ?

**Comment by boegel** [comment]
Probably because it's based on `cutadapt-2.10-GCCcore-9.3.0-Python-3.8.2.eb`, and `cutadapt-3.4-GCCcore-10.2.0.eb` doesn't work for some reason (due to major version bump).

No need to hold this back imho...

**Comment by boegel** [comment]
@boegelbot please test @ jsc-zen2

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
node3143.skitty.os - Linux RHEL 8.6, x86_64, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz (skylake_avx512), Python 3.6.8
See https://gist.github.com/boegel/2115bd91991abff181bcf4705275941a for a full test report.

**Review by boegel — APPROVED** [review]
lgtm

**Comment by boegel** [comment]
Going in, thanks @DirectorSloan!

**Pull request merged**
