### PR TITLE
{numlib,toolchain}[foss/2016c] Bowtie v1.1.2, Chimera v1.11.2, CMake v3.5.2, ...

### PR DESCRIPTION
**Pull request by shahzebsiddiqui**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by boegel** [comment]
@shahzebsiddiqui as mentioned in https://github.com/hpcugent/easybuild-easyconfigs/pull/3912, the `foss/<year>{letter}` naming scheme is 'reserved' for the common toolchains, which are updated twice a year (`a` and `b`)

Including additional versions of the `foss` toolchain that expand this scheme would lead to confusion.

If you want to include a custom version of the `foss` toolchain, please use a `foss/<year>.<month>` naming scheme, where `<year>.<month>` is determined by the release date of the most recent component in the toolchain.

Besides that, this PR is way too big (and Travis is indicating something is wrong with it, since the test suite is failing)...

If you want to proceed with this, please contribute the custom version of the `foss` toolchain in a separate PR, without only the easyconfigs for the toolchain itself, preferably with an easyconfig for `HPL` as a testcase.
Next to that, this PR should be broken up in preferably logically connected easyconfigs, with ~5 (max. 10) easyconfigs per PR max.

**Comment by shahzebsiddiqui** [comment]
Okay, so I will try to commit the foss toolchain and I will name it foss-2016.12.eb which will use GCC-5.2.0.
I am assuming to minimize easybuild dependency (i.e changing dependencies to osdependencies) because we don't want to clutter the module environment with useless stuff. You are welcome to change that but for now I will try to do stick to this convention.

**Comment by boegel** [comment]
@shahzebsiddiqui the usual approach is the exact opposite: to try and ensure that the list of dependencies is complete, and as much as possible is provided via EasyBuild (to avoid having to rely on the OS too heavily)

I suggest you take a look at http://easybuild.readthedocs.io/en/latest/Manipulating_dependencies.html#filtering-out-dependencies-using-filter-deps and/or if you want to avoid cluttering your modules tree too much: http://easybuild.readthedocs.io/en/latest/Manipulating_dependencies.html#installing-dependencies-as-hidden-modules-using-hide-deps

**Comment by shahzebsiddiqui** [comment]
For Foss toolchain I should submit easyconfig for GCC, OpenMPI, OpenBLAS, gompi, FFTW, ScaLAPACK, LAPACK, and some package built with foss. Is that correct.

Should I built GCC, OpenMPI, and gompi toolchain in one PR and use another pr to reference gompi toolchain. Will Travis CI work in referencing other PR?

**Comment by boegel** [comment]
@shahzebsiddiqui for the PR contributing back `foss`, include all the easyconfigs that are required for that toolchain in the same PR (that includes `gompi` as well) + add an easyconfig for HPL built with the `foss` toolchain

Travis will not test different PRs in the right order, that's something we need to trigger (e.g. by merging the `foss`PR first, and then revisiting other PRs that require it).

I'm not sure what the best version would be for your toolchain... The most recent component (OpenBLAS 0.2.19) seems to be from Sept 1st 2016, but we already have a toolchain named `foss/2016.09`...

Versioning it as `foss/2016.12` seems confusing, since there are updates to the components that are more recent than the versions you are using (GCC 5.4, OpenMPI 2.0.1, FFTW 3.3.5)...

**Comment by shahzebsiddiqui** [comment]
We can close this request and I will try to do commit them individually. As for the foss toolchain name, you can name it whatever you want. It should work. I noticed there wasn't a foss toolchain with GCC-5.2.0 so if you want to make it foss-2016.08 that would be a name change.

**Pull request closed without merging**
