### PR TITLE
{lib}[dummy/dummy] Catch2 v2.9.1

### PR DESCRIPTION
**Pull request by cmeesters**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by cmeesters** [comment]
note: header-only library for C++ unit tests

**Comment by cmeesters** [comment]
I do not know how and when: But installing onto a 2nd cluster showed there sneaked a typo in the config, which made the sanity test fail --- arrrrgh.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
node2031.delcatty.os - Linux centos linux 7.6.1810, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.7.5
See https://gist.github.com/315b9508007fd8286cd409ba623a7847 for a full test report.

**Comment by boegel** [comment]
Going in, thanks @cmeesters!

**Pull request merged**
