### PR TITLE
{bio}[system/system] CellRanger v3.1.0

### PR DESCRIPTION
**Pull request by smoors**
(created using `eb --new-pr`)

I removed the `Java` dep because it does not seem to be used at all.

### CODE REVIEW

**Comment by verdurin** [comment]
Test report by @verdurin
**FAILED**
Build succeeded for 0 out of 1 (1 easyconfigs in this PR)
easybuild.novalocal - Linux centos linux 7.7.1908, Intel Xeon Processor (Skylake, IBRS), Python 2.7.5
See https://gist.github.com/05a2c50afdeaa929bf46670ce0583dce for a full test report.

**Comment by smoors** [comment]
@verdurin sources need to be downloaded manually.

**Comment by smoors** [comment]
Test report by @smoors
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
node226.hydra.os - Linux centos linux 7.6.1810, Intel(R) Xeon(R) CPU E5-2680 v4 @ 2.40GHz, Python 2.7.5
See https://gist.github.com/7a139bf6428b6c8fac03cafd7a22edec for a full test report.

**Comment by verdurin** [comment]
Test report by @verdurin
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
generoso - Linux centos linux 7.6.1810, Intel(R) Xeon(R) CPU E5-2660 v4 @ 2.00GHz, Python 3.6.8
See https://gist.github.com/67dea8cea00e14fdaac0d16262c0db00 for a full test report.

**Comment by verdurin** [comment]
> @verdurin sources need to be downloaded manually.

I'm a sort of build first, ask questions later person...

**Comment by verdurin** [comment]
Going in, thanks @smoors!

**Pull request merged**
