### PR TITLE
Add missing patches to PyTorch-1.12.0-foss-2022a

### PR DESCRIPTION
**Pull request by Flamefire**
(created using `eb --new-pr`)

Patches taken from 1.12.1 ECs

I noticed this doesn't build correctly (at least on PPC) when testing it for https://github.com/easybuilders/easybuild-easyblocks/pull/2968 (i.e. it failed even without that new easyblock)

### CODE REVIEW

**Comment by casparvl** [comment]
@boegelbot please test @ generoso

**Comment by casparvl** [comment]
@boegelbot please test @ generoso
CORE_CNT=16

**Comment by Flamefire** [comment]
Test report by @Flamefire
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
taurusml24 - Linux RHEL 7.6, POWER, 8335-GTX (power9le), 6 x NVIDIA Tesla V100-SXM2-32GB, 440.64.00, Python 2.7.5
See https://gist.github.com/Flamefire/c722005e001161f7310fd4776fa34a65 for a full test report.

**Comment by Flamefire** [comment]
Test report by @Flamefire
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
taurusi8033 - Linux CentOS Linux 7.9.2009, x86_64, AMD EPYC 7352 24-Core Processor (zen2), 8 x NVIDIA NVIDIA A100-SXM4-40GB, 470.57.02, Python 2.7.5
See https://gist.github.com/Flamefire/05a0c0f401c8b0ef98d9773ea037286d for a full test report.

**Comment by casparvl** [comment]
Test report by @casparvl
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
gcn31.local.snellius.surf.nl - Linux RHEL 8.6, x86_64, Intel(R) Xeon(R) Platinum 8360Y CPU @ 2.40GHz, 1 x NVIDIA NVIDIA A100-SXM4-40GB, 520.61.05, Python 3.6.8
See https://gist.github.com/casparvl/67dc22b2f77743c3ba9dc34847d82c47 for a full test report.

**Comment by casparvl** [comment]
Going in, thanks @Flamefire!

**Pull request merged**
