### PR TITLE
add missing libpng dependency in ROOT 6.10.08 easyconfigs

### PR DESCRIPTION
**Pull request by boegel**

### CODE REVIEW

**Comment by verdurin** [comment]
@boegel - change looks trivial. Could you submit some test runs?

**Comment by boegel** [comment]
@verdurin I will, but since I'm making this change to try and fix the issue you ran into in #5524, maybe you should too? :)

**Comment by verdurin** [comment]
@boegel - of course, but currently I don't have a single system that can build both those toolchains...

**Comment by boegel** [comment]
@verdurin Just testing one of them is fine imho (see http://easybuild.readthedocs.io/en/latest/Integration_with_GitHub.html#specifying-particular-easyconfig-files)

**Comment by verdurin** [comment]
@boegel - nifty - didn't know that. `foss` version is building now.

**Comment by verdurin** [comment]
Test report by @verdurin
**FAILED**
Build succeeded for 6 out of 23 (2 easyconfigs in this PR)
dell.lan - Linux fedora 27, Intel(R) Core(TM) i7-4600U CPU @ 2.10GHz, Python 2.7.14
See https://gist.github.com/39c42d81f8e3f01c5e1493649260ac2d for a full test report.

**Comment by boegel** [comment]
@verdurin You will need to make sure the necessary installation files for `intel/2017b` are available...

**Comment by verdurin** [comment]
@boegel - yes, I know - that's the machine that doesn't have `intel`

**Comment by verdurin** [comment]
Test report by @verdurin
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
rescomp2 - Linux centos 6.8, Intel(R) Xeon(R) CPU E5-2650 v2 @ 2.60GHz, Python 2.7.11
See https://gist.github.com/5f49b6a8a4c4c0c58b2ac7a11d67df4b for a full test report.

**Comment by verdurin** [comment]
Going in, thanks @boegel!

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in this PR)
node2020.delcatty.os - Linux centos linux 7.4.1708, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.7.5
See https://gist.github.com/b82652351ae384a58e0d0bc5238a6f2a for a full test report.

**Pull request merged**
