### PR TITLE
{devel,lib}{GCCcore/13.3.0} Add GOTCHA v1.0.7, Check v0.15.2

### PR DESCRIPTION
**Pull request by Thyre**
Add GOTCHA, a library which helps to wrap function calls. This will get relevant for tools like Score-P.
The build itself is straight-forward, but parallel builds need to be disabled due to issues when enabling tests. 
This is not a huge problem though, as the library builds quickly (~20 seconds on my machine).

### CODE REVIEW

**Comment by Thyre** [comment]
Test report by @Thyre
**SUCCESS**
Build succeeded for 0 out of 0 (1 easyconfigs in total)
Linux - Linux EndeavourOS UNKNOWN, x86_64, AMD Ryzen 7 7800X3D 8-Core Processor, 1 x NVIDIA NVIDIA GeForce RTX 3070, 560.35.03, Python 3.12.6
See https://gist.github.com/Thyre/81b9a140c25976beec6c7eef3fd7a0c0 for a full test report.

**Comment by Thyre** [comment]
Test report by @Thyre
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
Linux - Linux EndeavourOS UNKNOWN, x86_64, AMD Ryzen 7 7800X3D 8-Core Processor, 1 x NVIDIA NVIDIA GeForce RTX 3070, 560.35.03, Python 3.12.6
See https://gist.github.com/Thyre/b5e50dab0ae8d5fc81430f99ee5c5c1b for a full test report.

**Comment by Thyre** [comment]
Test report by @Thyre
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
Linux - Linux EndeavourOS UNKNOWN, x86_64, AMD Ryzen 7 7800X3D 8-Core Processor, 1 x NVIDIA NVIDIA GeForce RTX 3070, 560.35.03, Python 3.12.6
See https://gist.github.com/Thyre/518c6f2f7b71ee6cc61a37646a07381e for a full test report.

**Comment by smoors** [comment]
@boegelbot: please test @ generoso

**Comment by Thyre** [comment]
> Test report by @boegelbot **FAILED** Build succeeded for 0 out of 1 (1 easyconfigs in total) cns3 - Linux Rocky Linux 8.9, x86_64, Intel(R) Xeon(R) CPU E5-2667 v3 @ 3.20GHz (haswell), Python 3.6.8 See https://gist.github.com/boegelbot/590cfb7a9d64621b76e9f817c0353ed1 for a full test report.

Interesting. This looks like linking the downloaded library for the tests failed. Since parallel also causes issues with the tests, disabling the tests might be worth it...

**Comment by smoors** [comment]
Test report by @smoors
**FAILED**
Build succeeded for 20 out of 21 (1 easyconfigs in total)
node300.hydra.os - Linux Rocky Linux 8.10, x86_64, Intel(R) Xeon(R) Gold 6148 CPU @ 2.40GHz (skylake_avx512), Python 3.6.8
See https://gist.github.com/smoors/ef7d8cb1b6bfa770d2dba27cc94b3f35 for a full test report.

**Comment by Thyre** [comment]
Test report by @Thyre
**FAILED**
Failed during parsing of the easyconfigs, so no ecs were built (1 easyconfigs in total)
Linux - Linux EndeavourOS UNKNOWN, x86_64, AMD Ryzen 7 7800X3D 8-Core Processor, 1 x NVIDIA NVIDIA GeForce RTX 3070, 560.35.03, Python 3.12.6
See https://gist.github.com/Thyre/1f97de90bc5c1097d3f38ccf31304100 for a full test report.

**Comment by Thyre** [comment]
Test report by @Thyre
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in total)
Linux - Linux EndeavourOS UNKNOWN, x86_64, AMD Ryzen 7 7800X3D 8-Core Processor, 1 x NVIDIA NVIDIA GeForce RTX 3070, 560.35.03, Python 3.12.6
See https://gist.github.com/Thyre/e9c5d561752c46f52d6eaa14efa05868 for a full test report.

**Comment by SebastianAchilles** [comment]
Test report by @sebastianachilles
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in total)
skl-rockylinux-810 - Linux Rocky Linux 8.10, x86_64, Intel(R) Core(TM) i7-10700 CPU @ 2.90GHz (skylake), 1 x NVIDIA NVIDIA RTX A4000, 555.42.06, Python 3.6.8
See https://gist.github.com/SebastianAchilles/a018630e7aaecdec4ea4df9b9fcccefc for a full test report.

**Comment by SebastianAchilles** [comment]
@boegelbot please test @ jsc-zen3

**Comment by SebastianAchilles** [comment]
@boegelbot please test @ generoso

**Review by smoors — APPROVED** [review]
lgtm

**Comment by smoors** [comment]
Going in, thanks @Thyre!

**Pull request merged**
