### PR TITLE
{lib}[system/system] IJulia v1.24.0

### PR DESCRIPTION
**Pull request by lexming**
(created using `eb --new-pr`)

Depends on:
* [x] https://github.com/easybuilders/easybuild-framework/pull/4196

### CODE REVIEW

**Comment by lexming** [comment]
Test report by @lexming
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
node300.hydra.os - Linux CentOS Linux 7.9.2009, x86_64, Intel(R) Xeon(R) Gold 6148 CPU @ 2.40GHz, Python 3.6.8
See https://gist.github.com/4fa24e6878e66dd160ea14e7f31f5a24 for a full test report.

**Comment by terjekv** [comment]
Test report by @terjekv
**FAILED**
Build succeeded for 1 out of 2 (1 easyconfigs in total)
ninhursaga.uio.no - Linux RHEL 9.1 (Plow), x86_64, Intel(R) Xeon(R) Silver 4216 CPU @ 2.10GHz, 1 x NVIDIA Tesla T4, 525.60.13, Python 3.9.14
See https://gist.github.com/fcee976b83439365c89fdf38ca5ddc62 for a full test report.

**Comment by ocaisa** [comment]
@boegelbot: please test @ generoso

**Comment by ocaisa** [comment]
@boegelbot: please test @ jsc-zen2

**Review by ocaisa — APPROVED** [review]

**Comment by ocaisa** [comment]
LGTM, going in @lexming !

**Pull request merged**
