### PR TITLE
{bio}[foss/2023a] GROMACS v2023.4

### PR DESCRIPTION
**Pull request by bedroge**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by bedroge** [comment]
@boegelbot please test @ generoso
CORE_CNT=16

**Comment by jfgrimm** [comment]
Test report by @jfgrimm
**FAILED**
Build succeeded for 0 out of 1 (1 easyconfigs in total)
node115.viking2.yor.alces.network - Linux Rocky Linux 8.8, x86_64, AMD EPYC 7643 48-Core Processor, Python 3.6.8
See https://gist.github.com/jfgrimm/da9c3ec1d205091149b93294aada3e79 for a full test report.

**Comment by bedroge** [comment]
> Test report by @boegelbot **FAILED** Build succeeded for 0 out of 1 (1 easyconfigs in total) cnx1 - Linux Rocky Linux 8.5, x86_64, Intel(R) Xeon(R) CPU E5-2667 v3 @ 3.20GHz (haswell), Python 3.6.8 See https://gist.github.com/boegelbot/ea0f22210966a6db62f0287691f3dd94 for a full test report.

This is the same failure as in #19321. We also saw that failure for EESSI, but it seemed to work fine with `2023.4` when I just tested that interactively... Let me start some test builds with the EESSI bot.

**Comment by jfgrimm** [comment]
Test report by @jfgrimm
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
node115.viking2.yor.alces.network - Linux Rocky Linux 8.8, x86_64, AMD EPYC 7643 48-Core Processor, Python 3.6.8
See https://gist.github.com/jfgrimm/cd3486616471cba7bb41e1adbf305f03 for a full test report.

**Comment by verdurin** [comment]
Test report by @verdurin
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
easybuild-c7.novalocal - Linux CentOS Linux 7.9.2009, x86_64, Intel Xeon Processor (Skylake, IBRS), Python 3.6.8
See https://gist.github.com/verdurin/91715051c6ada39cef098144a2a728d2 for a full test report.

**Comment by boegel** [comment]
@boegelbot please test @ jsc-zen3

**Comment by boegel** [comment]
> > Test report by @boegelbot **FAILED** Build succeeded for 0 out of 1 (1 easyconfigs in total) cnx1 - Linux Rocky Linux 8.5, x86_64, Intel(R) Xeon(R) CPU E5-2667 v3 @ 3.20GHz (haswell), Python 3.6.8 See https://gist.github.com/boegelbot/ea0f22210966a6db62f0287691f3dd94 for a full test report.
> 
> This is the same failure as in #19321. We also saw that failure for EESSI, but it seemed to work fine with `2023.4` when I just tested that interactively... Let me start some test builds with the EESSI bot.

More info in https://gitlab.com/eessi/support/-/issues/47#note_1759974438

**Comment by ocaisa** [comment]
@boegelbot please test @ generoso
CORE_CNT=16

**Comment by ocaisa** [comment]
The failure on Generoso seems to have been fixed by our [bugfix to OpenMPI](https://github.com/easybuilders/easybuild-easyconfigs/pull/19940), this is good to merge now @boegel but I wonder if we should instead focus on [2024.1](#20102) now?

**Comment by casparvl** [comment]
Strange, in the CUDA build it still failed on Generoso, with the error from before... https://gist.github.com/boegelbot/53a6c09141e2998ae5db6704104f56fe

**Comment by boegel** [comment]
@boegelbot please test @ generoso
CORE_CNT=16

**Review by boegel — APPROVED** [review]
lgtm

**Comment by boegel** [comment]
Going in, thanks @bedroge!

**Pull request merged**
