### PR TITLE
Consistently use pip to install Python packages in recent Python easyconfigs

### PR DESCRIPTION
**Pull request by Flamefire**
(created using `eb --new-pr`)

This fixes a wrong pip version, see https://github.com/easybuilders/easybuild-easyblocks/issues/2389 and uses pip for all packages.

To note:

- Some packages require poetry to install but are dependencies of poetry itself. Hence use the whl files from PyPi
- Similarly some packages of Python-2.7.18-GCCcore-10.2.0.eb require flit but we don't install that there, so use the whl
- wheel depends on setuptools and pip depends on both, hence upgrade pip after the other 2
- The `install_pip = True` changes in the Python 2 ECs are nice to have, those in Python 3 are required (breaking change of https://github.com/easybuilders/easybuild-easyblocks/pull/2388)

- [x] Requires ~~https://github.com/easybuilders/easybuild-easyblocks/pull/2366~~ for the whl file support
- [ ] Requires https://github.com/easybuilders/easybuild-easyblocks/pull/2388 for the pip support in Python 2 and `install_pip`

### CODE REVIEW

**Comment by Flamefire** [comment]
Test report by @Flamefire
Using easyblocks from PR(s) https://github.com/easybuilders/easybuild-easyblocks/pull/2366
**FAILED**
Build succeeded for 2 out of 8 (8 easyconfigs in total)
taurusi8030 - Linux centos linux 7.9.2009, x86_64, AMD EPYC 7352 24-Core Processor (zen2), Python 2.7.5
See https://gist.github.com/952ccf6f88e1872db6764868b1b4f144 for a full test report.

**Comment by Flamefire** [comment]
Test report by @Flamefire
Using easyblocks from PR(s) https://github.com/easybuilders/easybuild-easyblocks/pull/2366
**FAILED**
Build succeeded for 5 out of 9 (8 easyconfigs in total)
taurusi8029 - Linux centos linux 7.9.2009, x86_64, AMD EPYC 7352 24-Core Processor (zen2), Python 2.7.5
See https://gist.github.com/cb92b29660570e5ed37ea6db614c18b8 for a full test report.

**Comment by Flamefire** [comment]
Test report by @Flamefire
Using easyblocks from PR(s) https://github.com/easybuilders/easybuild-easyblocks/pull/2366
**FAILED**
Build succeeded for 4 out of 8 (8 easyconfigs in total)
taurusml23 - Linux RHEL 7.6, POWER, 8335-GTX (power9le), Python 2.7.5
See https://gist.github.com/6550367a8c7e740a165cb3405ff571ac for a full test report.

**Comment by Flamefire** [comment]
Test report by @Flamefire
Using easyblocks from PR(s) https://github.com/easybuilders/easybuild-easyblocks/pull/2388, https://github.com/easybuilders/easybuild-easyblocks/pull/2366
**FAILED**
Build succeeded for 7 out of 8 (8 easyconfigs in total)
taurusi8028 - Linux centos linux 7.9.2009, x86_64, AMD EPYC 7352 24-Core Processor (zen2), Python 2.7.5
See https://gist.github.com/d254b796f10707c70d78233847749819 for a full test report.

**Comment by Flamefire** [comment]
Test report by @Flamefire
Using easyblocks from PR(s) https://github.com/easybuilders/easybuild-easyblocks/pull/2388, https://github.com/easybuilders/easybuild-easyblocks/pull/2366
**SUCCESS**
Build succeeded for 8 out of 8 (8 easyconfigs in total)
taurusml11 - Linux RHEL 7.6, POWER, 8335-GTX (power9le), Python 2.7.5
See https://gist.github.com/160f0a84d2a93adca4247a0d7165af7c for a full test report.

**Comment by Flamefire** [comment]
Test report by @Flamefire
Using easyblocks from PR(s) https://github.com/easybuilders/easybuild-easyblocks/pull/2388, https://github.com/easybuilders/easybuild-easyblocks/pull/2366
**SUCCESS**
Build succeeded for 2 out of 2 (1 easyconfigs in total)
taurusi8028 - Linux centos linux 7.9.2009, x86_64, AMD EPYC 7352 24-Core Processor (zen2), Python 2.7.5
See https://gist.github.com/bc50acce59453ac7598228965d786adc for a full test report.

**Comment by Flamefire** [comment]
Test report by @Flamefire
Using easyblocks from PR(s) https://github.com/easybuilders/easybuild-easyblocks/pull/2388
**SUCCESS**
Build succeeded for 8 out of 8 (8 easyconfigs in total)
taurusi6343.taurus.hrsk.tu-dresden.de - Linux RHEL 7.9, x86_64, Intel(R) Xeon(R) CPU E5-2680 v3 @ 2.50GHz (haswell), Python 2.7.5
See https://gist.github.com/0ec7ec8a06ccebb5338fd1067f97973b for a full test report.

**Review by boegel — APPROVED** [review]
lgtm

**Comment by boegel** [comment]
@boegelbot please test @ generoso
EB_ARGS="--include-easyblocks-from-pr 2388"
CORE_CNT=16

**Comment by Flamefire** [comment]
Test report by @Flamefire
Using easyblocks from PR(s) https://github.com/easybuilders/easybuild-easyblocks/pull/2388
**SUCCESS**
Build succeeded for 8 out of 8 (8 easyconfigs in total)
taurusi8005 - Linux centos linux 7.9.2009, x86_64, AMD EPYC 7352 24-Core Processor (zen2), Python 2.7.5
See https://gist.github.com/aa390612e669417edbda8df452349e44 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
Using easyblocks from PR(s) https://github.com/easybuilders/easybuild-easyblocks/pull/2388
**SUCCESS**
Build succeeded for 8 out of 8 (8 easyconfigs in total)
node3171.skitty.os - Linux centos linux 7.9.2009, x86_64, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz, Python 3.6.8
See https://gist.github.com/dd05c98d1886c142aafdab985c9a023d for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
Using easyblocks from PR(s) https://github.com/easybuilders/easybuild-easyblocks/pull/2388
**SUCCESS**
Build succeeded for 8 out of 8 (8 easyconfigs in total)
node3510.doduo.os - Linux RHEL 8.2, x86_64, AMD EPYC 7552 48-Core Processor (zen2), Python 3.6.8
See https://gist.github.com/f98a52f4e90ab124ce71badd404416fe for a full test report.

**Pull request merged**
