### PR TITLE
{chem}[foss/2023a] waLBerla v6.1

### PR DESCRIPTION
**Pull request by Neves-P**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by Neves-P** [comment]
Test report by @Neves-P
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
WKS058930 - Linux Ubuntu 22.04, x86_64, 12th Gen Intel(R) Core(TM) i7-1260P, Python 3.10.12
See https://gist.github.com/Neves-P/9dd979e421c68ae6a0dcdb5dbd17d1cc for a full test report.

**Comment by boegel** [comment]
@boegelbot please test @ generoso

**Review by boegel — APPROVED** [review]
lgtm

**Comment by boegel** [comment]
@boegelbot please test @ generoso

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 2 out of 2 (1 easyconfigs in total)
node3159.skitty.os - Linux RHEL 9.4, x86_64, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz (skylake_avx512), Python 3.9.18
See https://gist.github.com/boegel/ab143e031ef83f70eeab058f876419cc for a full test report.

**Comment by boegel** [comment]
Going in, thanks @Neves-P!

**Pull request merged**
