### PR TITLE
Fix source for SQLite 3.31.1

### PR DESCRIPTION
**Pull request by Micket**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by Micket** [comment]
@boegelbot please test @ generoso

**Comment by lexming** [comment]
Test report by @lexming
**FAILED**
Build succeeded for 0 out of 1 (1 easyconfigs in total)
node101.hydra.os - Linux centos linux 7.7.1908, x86_64, Intel(R) Xeon(R) CPU E5-2680 v2 @ 2.80GHz, Python 2.7.5
See https://gist.github.com/e6aa010890e3d56d34faf8a829d436bc for a full test report.

**Comment by lexming** [comment]
Test report by @lexming
**FAILED**
Build succeeded for 0 out of 1 (1 easyconfigs in total)
node379.hydra.os - Linux centos linux 7.7.1908, x86_64, Intel(R) Xeon(R) Gold 6148 CPU @ 2.40GHz, Python 2.7.5
See https://gist.github.com/551ff5f432a42d58a98a40887d787901 for a full test report.

**Comment by Micket** [comment]
Seems like my filename pattern failed in this case.. in fact, i'm not sure what the filename ought to be

**Comment by lexming** [comment]
@Micket this is the URL for v3.31.1: https://www.sqlite.org/2020/sqlite-autoconf-3310100.tar.gz
So it is more complicated than a simple `join`, each subversion uses 2 digits in the name of the tarball.

**Comment by lexming** [comment]
@Micket something like this would do the conversion
```
'{:d}{:02d}{:02d}000'.format(*[int(v) for v in '%(version)s'.split('.')])
```

**Comment by Micket** [comment]
@lexming @boegel downvoted my suggested
```
local_filename_version = '{0}{1:>02}{2:>02}{3:>02}'.format(*(version.split('.')+ [0]))
```
(which would also handle the case of a sub-patch release they sometimes have for the last 2 digits)

So, hardcoded string + sanity check it is

**Comment by lexming** [comment]
Test report by @lexming
**FAILED**
Build succeeded for 0 out of 1 (1 easyconfigs in total)
node381.hydra.os - Linux centos linux 7.7.1908, x86_64, Intel(R) Xeon(R) Gold 6148 CPU @ 2.40GHz, Python 2.7.5
See https://gist.github.com/12e89637accb0ea41c32861ab72cccd0 for a full test report.

**Comment by lexming** [comment]
Test report by @lexming
**FAILED**
Build succeeded for 0 out of 1 (1 easyconfigs in total)
node101.hydra.os - Linux centos linux 7.7.1908, x86_64, Intel(R) Xeon(R) CPU E5-2680 v2 @ 2.80GHz, Python 2.7.5
See https://gist.github.com/b539c7d48db821a1b29a6583e743b234 for a full test report.

**Comment by Micket** [comment]
Totally forgot that the checksum is (of course) wrong

**Comment by boegel** [comment]
@boegelbot please test @ generoso

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
node2645.swalot.os - Linux centos linux 7.8.2003, x86_64, Intel(R) Xeon(R) CPU E5-2660 v3 @ 2.60GHz (haswell), Python 2.7.5
See https://gist.github.com/3328edfa50a7cf1d8eb9486d13fe9704 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
node3109.skitty.os - Linux centos linux 7.8.2003, x86_64, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz, Python 3.6.8
See https://gist.github.com/085da2e7b75cae8dc3c0b149e7ad87b9 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
node3502.doduo.os - Linux RHEL 8.2, x86_64, AMD EPYC 7302P 16-Core Processor (zen2), Python 3.6.8
See https://gist.github.com/9692a06d0096f457e149795a77780430 for a full test report.

**Review by boegel — APPROVED** [review]
lgtm

**Comment by boegel** [comment]
@Micket Do you think it's worth it to backport the sanity check command to older SQLite easyconfigs?

**Comment by Micket** [comment]
@boegel My vote is no, not worth it

**Pull request merged**
