### PR TITLE
{vis}[foss/2020a] GTS v0.7.6

### PR DESCRIPTION
**Pull request by SimonPinches**
(created using `eb --new-pr`)

### CODE REVIEW

**Review by Micket — DISMISSED** [review]
lgtm

**Comment by Micket** [comment]
Test report by @Micket
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
hebbe-c1 - Linux centos linux 7.7.1908, x86_64, Intel Core Processor (Haswell, no TSX), Python 2.7.5
See https://gist.github.com/19de405d63854570623f8fb0470fa3d1 for a full test report.

**Comment by Micket** [comment]
@SimonPinches  I'm not sure why the test behave like this; could you please try to rebase this PR on develop to see if it resolves it?

**Comment by SimonPinches** [comment]
@Micket I've just rebased on top of `develop` as you suggested.  Let me know if anything else is needed.

**Comment by Micket** [comment]
@SimonPinches ouch, 25 files were just added to this PR, so something must have gone terribly wrong when you tried to rebase

**Comment by Micket** [comment]
@SimonPinches Perhaps just do a --new-pr since this is a bit broken now?

**Comment by verdurin** [comment]
@SimonPinches are you going to replace this PR with a new one, per @Micket's suggestion?

**Comment by boegel** [comment]
Rebasing often ends in tears (in this case, it causes conflicts because there were outdated `WHAM` easyconfigs in the branch).

I've fixed this myself, should be good to go now...

Commit-wise it looks a bit messy, but meh. :)

**Comment by Micket** [comment]
@boegel I'll be squashing these commits.

**Review by boegel — APPROVED** [review]
lgtm

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
node3402.kirlia.os - Linux centos linux 7.8.2003, x86_64, Intel(R) Xeon(R) Gold 6240 CPU @ 2.60GHz (cascadelake), Python 2.7.5
See https://gist.github.com/46e8a0ddeda23fa81c506581418a8cad for a full test report.

**Comment by SimonPinches** [comment]
@boegel, @Micket Sorry for not reacting quicker and sorting out this mess with the rebase and thanks for taking care of things.

**Comment by smoors** [comment]
Going in, thanks @SimonPinches!

**Pull request merged**
