### PR TITLE
{lib}[GCCcore/9.3.0] fmt v6.2.1

### PR DESCRIPTION
**Pull request by mboisson**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by Micket** [comment]
Do we need both this and #11502 ?

**Comment by mboisson** [comment]
They are both the latest minor version of a major version, which is why I installed both on our systems.

**Comment by smoors** [comment]
Test report by @smoors
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
node201.hydra.os - Linux centos linux 7.7.1908, x86_64, Intel(R) Xeon(R) CPU E5-2680 v4 @ 2.40GHz (broadwell), Python 2.7.5
See https://gist.github.com/92359e79240946ee2c55e61d7ae61fe9 for a full test report.

**Comment by smoors** [comment]
@boegelbot please test @ generoso

**Review by smoors — APPROVED** [review]
lgtm

**Comment by smoors** [comment]
Going in, thanks @mboisson!

**Pull request merged**
