### PR TITLE
{devel}[gompi/2021b] NVSHMEM v2.4.1

### PR DESCRIPTION
**Pull request by SebastianAchilles**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by SebastianAchilles** [comment]
Test report by @sebastianachilles
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
jsfc01.int.jusuf.sebastian.cluster - Linux UNKNOWN UNKNOWN, x86_64, AMD EPYC 7742 64-Core Processor (zen2), 1 x NVIDIA GRID V100-4C, 460.73.01, Python 3.6.8
See https://gist.github.com/8cd2127b77560d1cf0a83b0d2c294ab9 for a full test report.

**Comment by migueldiascosta** [comment]
@boegelbot please test @ generoso

**Comment by AndiH** [comment]
The sources of NVSHMEM can be downloaded at Nvidia's when you've signed up for their (free) developer program: https://developer.nvidia.com/nvshmem-downloads

I am not sure how this could be reflected in the CI job…

**Comment by SebastianAchilles** [comment]
The source file needs to be downloaded manually: https://github.com/easybuilders/easybuild-easyconfigs/pull/14832/files#diff-56f442328ca14cb81e4d577f25b4e3842c2467c9f18d59772f9effab71ce08b9R17

Therefore this PR is not suited to be tested on `generoso` or `jsc-zen2` since they require automated source downloading.

**Comment by SebastianAchilles** [comment]
Test report by @sebastianachilles
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
bdw-opensuse-154 - Linux openSUSE Leap 15.4, x86_64, Intel(R) Core(TM) i7-6900K CPU @ 3.20GHz (broadwell), 2 x NVIDIA NVIDIA GeForce GTX 1060 6GB, 510.85.02, Python 3.6.15
See https://gist.github.com/e61daffc59bd2d81cfef17fe1305b66b for a full test report.

**Review by jfgrimm — COMMENTED** [review]
As decided in issue #16330, we have deprecated the use of `True` to signify a system-toolchain dependency (#16384), in favour of the more intuitive `SYSTEM` template constant. Due to the change in the test suite, please run `eb --sync-pr-with-develop 14832` and update the PR to use `SYSTEM` instead.

**Comment by SebastianAchilles** [comment]
Test report by @sebastianachilles
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
bwd-opensuse-154 - Linux openSUSE Leap 15.4, x86_64, Intel(R) Core(TM) i7-6900K CPU @ 3.20GHz (broadwell), 2 x NVIDIA NVIDIA GeForce GTX 1060 6GB, 515.86.01, Python 3.6.15
See https://gist.github.com/89f725a477a241533a0e6563bed08bf2 for a full test report.

**Comment by SebastianAchilles** [comment]
Test report by @sebastianachilles
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
jsfc061 - Linux Rocky Linux 8.6, x86_64, AMD EPYC 7742 64-Core Processor (zen2), 1 x NVIDIA Tesla V100-PCIE-16GB, 515.65.01, Python 3.6.8
See https://gist.github.com/b5ccca80e2ed1c2389e052e0b706ede7 for a full test report.

**Review by boegel — APPROVED** [review]
lgtm

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
node3901.accelgor.os - Linux RHEL 8.6, x86_64, AMD EPYC 7413 24-Core Processor (zen3), 1 x NVIDIA NVIDIA A100-SXM4-80GB, 520.61.05, Python 3.6.8
See https://gist.github.com/82e02c9167cc6c2bca33d27e16b85cd4 for a full test report.

**Comment by boegel** [comment]
Going in, thanks @SebastianAchilles!

**Pull request merged**
