### PR TITLE
fix installation of Python 2.7.18 with GCCcore/11.2.0

### LINKED ISSUE #16467: 'pip check' fails for Python 2.7.18 with GCCcore/11.2.0
Due to the changes in https://github.com/easybuilders/easybuild-easyblocks/pull/2807, we're now running `python -m pip check` rather than `pip check`, which makes sure that the correct `python` is being used to run the check.

This revealed a problem with the Python 2.x easyconfigs, where `pip check` fails because the `backports.*` extensions get installed with a `0.0.0` version...

```
== 2022-10-21 10:16:20,191 build_log.py:169 ERROR EasyBuild crashed with an error (at easybuild/easybuild-framework/easybuild/base/exceptions.py:124 in __init__): `/tmp/boegelbot/tests/software/Python/2.7.18-GCCcore-11.2.0/bin/python -m pip check` failed:
DEPRECATION: Python 2.7 reached the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 is no longer maintained. pip 21.0 will drop support for Python 2.7 in January 2021. More details about Python 2 support in pip can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support pip 21.0 will remove support for this functionality.
virtualenv 20.7.0 has requirement backports.entry-points-selectable>=1.0.4, but you have backports-entry-points-selectable 0.0.0.
wcwidth 0.2.5 has requirement backports.functools-lru-cache>=1.2.1; python_version < "3.2", but you have backports-functools-lru-cache 0.0.0.
```

edit: it seems like only `Python-2.7.18-GCCcore-11.2.0.eb` is affected by this, probably because that uses a more recent `setuptools` version than other easyconfigs for `Python` 2.7.18

### PR DESCRIPTION
**Pull request by boegel**
(created using `eb --new-pr`)
fixes #16467

### CODE REVIEW

**Comment by smoors** [comment]
@boegelbot: please test @ generoso

**Comment by smoors** [comment]
Test report by @smoors
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
node316.hydra.os - Linux CentOS Linux 7.9.2009, x86_64, Intel(R) Xeon(R) Gold 6148 CPU @ 2.40GHz (skylake_avx512), Python 2.7.5
See https://gist.github.com/7fb56697dbbc206ec6712402de63be8c for a full test report.

**Review by smoors — APPROVED** [review]
lgtm

**Comment by smoors** [comment]
Going in, thanks @boegel!

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
node3106.skitty.os - Linux RHEL 8.4, x86_64, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz (skylake_avx512), Python 3.6.8
See https://gist.github.com/a3b6f25ed4785888a5dd8f32050f2780 for a full test report.

**Pull request merged**
