### PR TITLE
Fix BLIS build on PPC

### PR DESCRIPTION
**Pull request by Flamefire**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by Flamefire** [comment]
Test report by @Flamefire
**FAILED**
Build succeeded for 7 out of 11 (11 easyconfigs in total)
taurusi8030 - Linux CentOS Linux 7.9.2009, x86_64, AMD EPYC 7352 24-Core Processor (zen2), 8 x NVIDIA NVIDIA A100-SXM4-40GB, 470.57.02, Python 2.7.5
See https://gist.github.com/019d724bd063bc38579d8456c7b7ef6b for a full test report.

**Comment by jfgrimm** [comment]
Test report by @jfgrimm
**FAILED**
Build succeeded for 6 out of 10 (10 easyconfigs in total)
node022.pri.viking.alces.network - Linux CentOS Linux 7.9.2009, x86_64, Intel(R) Xeon(R) Gold 6138 CPU @ 2.00GHz (skylake_avx512), Python 3.6.8
See https://gist.github.com/d3b672008e0c9fbc04c2c60da0b51b4c for a full test report.

**Comment by Flamefire** [comment]
Test report by @Flamefire
**SUCCESS**
Build succeeded for 10 out of 10 (10 easyconfigs in total)
taurusa11 - Linux CentOS Linux 7.7.1908, x86_64, Intel(R) Xeon(R) CPU E5-2603 v4 @ 1.70GHz (broadwell), 3 x NVIDIA GeForce GTX 1080 Ti, 460.32.03, Python 2.7.5
See https://gist.github.com/23f746f0845ef4d83a822b0fac88b40f for a full test report.

**Comment by jfgrimm** [comment]
@boegelbot please test @ generoso

**Comment by jfgrimm** [comment]
I'm still seeing test failures on my machine:
```
% blis_<dt><op>_<params>_<stor>      m     k   gflops   resid      result                                               
blis_sgemmt_lnn_rrr                100   100    37.48   5.39e-02   FAILURE                                              
blis_sgemmt_unn_rrr                100   100    40.96   6.05e-02   FAILURE
```
although I think that's unrelated to the changes in this PR, so shouldn't block this

**Review by jfgrimm — APPROVED** [review]
LGTM

**Comment by jfgrimm** [comment]
Going in, thanks @Flamefire!

**Comment by Flamefire** [comment]
Seems like I introduced a bug here for 2.2 and 3.0: They don't support POWER10 so the code doesn't compile on any PPC. Fix included in #15889

This still doesn't fully solve the BLIS build on PPC due to segfaults in 0.9.0 (https://github.com/flame/blis/issues/621) and timeouts during tests in 3.0.1

**Pull request merged**
