### PR TITLE
{toolchain} intel/2018.01

### PR DESCRIPTION
**Pull request by boegel**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 8 out of 8 (8 easyconfigs in this PR)
node2686.swalot.os - Linux centos linux 7.4.1708, Intel(R) Xeon(R) CPU E5-2660 v3 @ 2.60GHz, Python 2.7.5
See https://gist.github.com/79ffd63caac2554a05d936eb0b59fd6d for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 8 out of 8 (8 easyconfigs in this PR)
node2154.delcatty.os - Linux centos linux 7.4.1708, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.7.5
See https://gist.github.com/0560ee8e32fdd38ed3d6d6f7aa05d7c5 for a full test report.

**Comment by wpoely86** [comment]
no GCC 7.x yet?

**Comment by boegel** [comment]
@wpoely86 Not officially supported yet by Intel, I asked them for an update on that (but the release notes for 2018 update 1 only mention up to GCC 6.3).

**Pull request merged**
