### PR TITLE
netCDF:add patch fixing MPI_Info_f2c OpenMPI issue

### PR DESCRIPTION
**Pull request by bartoldeman**
This affects versions 4.6.2 to 4.7.4, see
https://github.com/Unidata/netcdf-c/pull/1957

### CODE REVIEW

**Comment by bartoldeman** [comment]
@boegelbot please test @ generoso

**Comment by lexming** [comment]
Test report by @lexming
**FAILED**
Build succeeded for 5 out of 6 (6 easyconfigs in total)
node308.hydra.os - Linux centos linux 7.9.2009, x86_64, Intel(R) Xeon(R) Gold 6148 CPU @ 2.40GHz, Python 2.7.5
See https://gist.github.com/f5200d10e146074b33dd0ec7127346e6 for a full test report.

**Comment by lexming** [comment]
Test report by @lexming
**SUCCESS**
Build succeeded for 6 out of 6 (6 easyconfigs in total)
node220.hydra.os - Linux centos linux 7.9.2009, x86_64, Intel(R) Xeon(R) CPU E5-2680 v4 @ 2.40GHz, Python 2.7.5
See https://gist.github.com/67572b35148df4cb327ccd12d67ba0f9 for a full test report.

**Review by lexming — APPROVED** [review]
LGTM

**Comment by lexming** [comment]
Going in, thanks @bartoldeman !

**Pull request merged**
