### PR TITLE
fix Score-P configure when install paths contains 'yes/no'

### PR DESCRIPTION
**Pull request by Flamefire**
(created using `eb --new-pr`)

### CODE REVIEW

**Review by Micket — APPROVED** [review]
lgtm

**Comment by Micket** [comment]
@boegelbot please test @ generoso
EB_ARGS="Score-P-8.4-gompi-2024a.eb"

**Comment by Flamefire** [comment]
> Test report by @boegelbot **FAILED** Build succeeded for 0 out of 2 (1 easyconfigs in total) cns1 - Linux Rocky Linux 8.9, x86_64, Intel(R) Xeon(R) CPU E5-2667 v3 @ 3.20GHz (haswell), Python 3.6.8 See https://gist.github.com/boegelbot/5d72b79601e20e5e1dedd7d7446ac660 for a full test report.

Sources for PDT are missing

**Comment by Flamefire** [comment]
Test report by @Flamefire
**FAILED**
Build succeeded for 30 out of 33 (13 easyconfigs in total)
i7025 - Linux Rocky Linux 8.9 (Green Obsidian), x86_64, AMD EPYC 7702 64-Core Processor (zen2), Python 3.8.17
See https://gist.github.com/Flamefire/d85da477818c718dad39f3a9eae9b21d for a full test report.

**Comment by bedroge** [comment]
@Flamefire This looks like the same fix as https://github.com/easybuilders/easybuild-easyblocks/pull/3496?

**Comment by Flamefire** [comment]
> @Flamefire it looks like this is fixing the same issue as [easybuilders/easybuild-easyblocks#3496](https://github.com/easybuilders/easybuild-easyblocks/pull/3496)?

Indeed, haven't seen that you ran into this before. Given the number of files requiring this patch it might make sense to use the easyblock

**Pull request closed without merging**
