### PR TITLE
Fix broken homepage from older SCOTCH easyconfigs

### PR DESCRIPTION
**Pull request by Micket**
(created using `eb --new-pr`)
Just sick and tired of an old issue #14098 so i decided to clean out these broken urls.

This just replaces the dead homepage with the one used in the more recent easyconfigs. I went back to 2021a toolchains.

### CODE REVIEW

**Comment by Micket** [comment]
Test report by @Micket
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
vera-skylake-build - Linux Rocky Linux 8.9, x86_64, Intel Xeon Processor (Skylake, IBRS, no TSX), Python 3.6.8
See https://gist.github.com/Micket/d9d53b6aed0fbf8c113b0b6702815533 for a full test report.

**Comment by Micket** [comment]
@boegelbot please test @ generoso

**Comment by casparvl** [comment]
@boegelbot please test @ jsc-zen3

**Comment by casparvl** [comment]
Test report by @casparvl
**SUCCESS**
Build succeeded for 4 out of 4 (4 easyconfigs in total)
tcn1.local.snellius.surf.nl - Linux RHEL 8.6, x86_64, AMD EPYC 7H12 64-Core Processor, Python 3.6.8
See https://gist.github.com/casparvl/15e262e5c159da8b1a44ac2ad7d59d9c for a full test report.

**Review by casparvl — APPROVED** [review]
Lgtm!

**Comment by casparvl** [comment]
Going in, thanks @Micket!

**Comment by casparvl** [comment]
Failures on jsczen3 were for the intel toolchain. That makes sense, that's not there on jsczen3. Should have excluded those in the test. No matter...

**Pull request merged**
