### PR TITLE
{lib}[GCCcore/10.3.0] tokenizers v0.12.1 w/ Python 3.9.5

### PR DESCRIPTION
**Pull request by boegel**
(created using `eb --new-pr`)
requires:
* #15586

An older version of Rust doesn't work, because new language features are used (with Rust 1.52.1 I was hitting https://github.com/rust-lang/rust/issues/81119)

### CODE REVIEW

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
node3162.skitty.os - Linux RHEL 8.4, x86_64, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz, Python 3.6.8
See https://gist.github.com/3d3214ca98372c09df98613e4938b8f9 for a full test report.

**Comment by jfgrimm** [comment]
Test report by @jfgrimm
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
himem06.pri.viking.alces.network - Linux CentOS Linux 7.9.2009, x86_64, Intel(R) Xeon(R) Platinum 8160 CPU @ 2.10GHz (skylake_avx512), Python 3.6.8
See https://gist.github.com/61a59e663421ac6387ad72a84aae4d3e for a full test report.

**Comment by boegel** [comment]
@boegelbot please test @ generoso

**Comment by Micket** [comment]
A dry run revealed that we are not actually in a position to having to build 2 rusts in order to build this (we should really solve the cryptography issue in Python...)

```
 * [x] /apps/easybuild-easyconfigs/easybuild/easyconfigs/r/Rust/Rust-1.52.1-GCCcore-10.3.0.eb (module: Rust/1.52.1-GCCcore-10.3.0)
 * [ ] /apps/easybuild-easyconfigs/easybuild/easyconfigs/r/Rust/Rust-1.60.0-GCCcore-10.3.0.eb (module: Rust/1.60.0-GCCcore-10.3.0)
```

Do we care? Ann alternative would be to stick to using 1.52.1 Rust for GCC 10.3.0 era packages.

**Comment by boegel** [comment]
@Micket As mentioned in the PR description, Rust 1.52.1 is not recent enough for `tokenenizers`.

If we want to avoid two Rust versions, we would need to bump Rust 1.52.1 to 1.60.0 as a build dependency everywhere for the `2021a` generation of easyconfigs. That seems more pain than it's worth, just because one specific package requires a more recent `Rust`...

**Comment by lexming** [comment]
@boegelbot: please test @ generoso

**Review by lexming — APPROVED** [review]
LGTM

**Comment by lexming** [comment]
Going in, thanks @boegel !

**Pull request merged**
