### PR TITLE
add missing brotli dependency to freetype

### PR DESCRIPTION
**Pull request by zemu-unile**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by zemu-unile** [comment]
Without this fontconfig builds fail on debian 11:
```
checking for FREETYPE... no
configure: error: Package requirements (freetype2 >= 21.0.15) were not met:

Package 'libbrotlidec', required by 'freetype2', not found

Consider adjusting the PKG_CONFIG_PATH environment variable if you
installed software in a non-standard prefix.

Alternatively, you may set the environment variables FREETYPE_CFLAGS
and FREETYPE_LIBS to avoid the need to call pkg-config.
See the pkg-config man page for more details.
```
Brotli support got introduced with freetype 2.10.2, toolchains older than 2020b are fine.

**Comment by zemu-unile** [comment]
Test report by @zemu-unile
**SUCCESS**
Build succeeded for 3 out of 3 (3 easyconfigs in total)
debian - Linux Debian GNU/Linux unstable, x86_64, Intel(R) Core(TM) i7-10510U CPU @ 1.80GHz, Python 3.9.7
See https://gist.github.com/d06b90149d8f3dc18679b7416e518530 for a full test report.

**Comment by verdurin** [comment]
@boegelbot please test @ generoso

**Comment by verdurin** [comment]
Test report by @verdurin
**SUCCESS**
Build succeeded for 1 out of 1 (3 easyconfigs in total)
nuc.lan - Linux Fedora 33, x86_64, Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz, Python 3.9.6
See https://gist.github.com/7ed931b21313c8eb3f64ba2d49dc11c8 for a full test report.

**Review by verdurin — APPROVED** [review]
Looks fine.

**Comment by verdurin** [comment]
Going in, thanks @zemu-unile!

**Pull request merged**
