### PR TITLE
{compiler,mpi,toolchain}[system/system] nvompic v2021a, NVHPC v21.7, OpenMPI v4.1.1

### PR DESCRIPTION
**Pull request by Micket**
(created using `eb --new-pr`)
Companion to #14006
It's different from #13107 since we avoid the compiler level "CUDA" package and use a versionsuffix instead. It's also using a different CUDA version from the NVHPC-default, I'm not sure if that is even allowed?

A quick test failed a OpenMPI test though, external32

### CODE REVIEW

**Comment by Micket** [comment]
Turns out there is a compiler bug in `nvc` really breaks some fundamental arrays datastructures OpenMPI;
https://github.com/open-mpi/ompi/issues/9402

**Comment by Micket** [comment]
Test report by @Micket
**SUCCESS**
Build succeeded for 3 out of 3 (3 easyconfigs in total)
alvis-c1 - Linux centos linux 7.9.2009, x86_64, Intel Xeon Processor (Skylake), Python 3.6.8
See https://gist.github.com/b16141bf389b8f894695febe0614997d for a full test report.

**Comment by SebastianAchilles** [comment]
Test report by @sebastianachilles
**SUCCESS**
Build succeeded for 3 out of 3 (3 easyconfigs in total)
rocky8-eb - Linux rocky linux 8.4, x86_64, Intel(R) Core(TM) i7-6900K CPU @ 3.20GHz (broadwell), Python 3.6.8
See https://gist.github.com/5238ebad8aec55d58c5c30b25036739f for a full test report.

**Comment by SebastianAchilles** [comment]
Test report by @sebastianachilles
**SUCCESS**
Build succeeded for 3 out of 3 (3 easyconfigs in total)
jsfc061 - Linux centos linux 7.9.2009, x86_64, AMD EPYC 7742 64-Core Processor, Python 3.6.8
See https://gist.github.com/291219721531ab9f07fcef9872d0834f for a full test report.

**Comment by Micket** [comment]
I'm unsuccessfull trying to build OSU-Micro-Benchmarks on top of this
```
mpicc -DPACKAGE_NAME=\"OSU-Micro-Benchmarks\" -DPACKAGE_TARNAME=\"osu-micro-benchmarks\" -DPACKAGE_VERSION=\"5.7.1\" -DPACKAGE_STRING=\"OSU-Micro-Benchmarks\ 5.7.1\" -DPACKAGE_BUGREPORT=\"mvapich-discuss@cse.ohio-state.edu\" -DPACKAGE=\"osu-micro-benchmarks\" -DVERSION=\"5.7.1\" -DSTDC_HEADERS=1 -DHAVE_SYS_TYPES_H=1 -DHAVE_SYS_STAT_H=1 -DHAVE_STDLIB_H=1 -DHAVE_STRING_H=1 -DHAVE_MEMORY_H=1 -DHAVE_STRINGS_H=1 -DHAVE_INTTYPES_H=1 -DHAVE_STDINT_H=1 -DHAVE_UNISTD_H=1 -DHAVE_DLFCN_H=1 -DLT_OBJDIR=\".libs/\" -DHAVE_STDLIB_H=1 -DHAVE_STRING_H=1 -DHAVE_SYS_TIME_H=1 -DHAVE_UNISTD_H=1 -DHAVE_GETPAGESIZE=1 -DHAVE_GETTIMEOFDAY=1 -DHAVE_MEMSET=1 -DHAVE_SQRT=1 -DHAVE_CUDA_H=1 -D_ENABLE_CUDA_=1 -D_ENABLE_CUDA_KERNEL_=1 -DFIELD_WIDTH=18 -DFLOAT_PRECISION=2 -I.   -I/apps/Test2/software/CUDA/11.3.1/include   -O2 -tp=host -Mflushz -c -o ../../util/kernel.o ../../util/kernel.cpp
"/apps/Test2/software/NVHPC/21.7-CUDA-11.3.1/Linux_x86_64/21.7/compilers/include/_cplus_preinclude.h", line 28: error: identifier "__va_list_tag" is undefined
  typedef __va_list_tag __pgi_va_list[1];
```
mpicc is correctly using nvcc, and it is having trouble with it's own headerfile. And looking in that headerfile, I don't see any obvious way it could ever have  __va_list_tag undefined.

**Review by jfgrimm — COMMENTED** [review]
As decided in issue #16330, we have deprecated the use of `True` to signify a system-toolchain dependency (#16384), in favour of the more intuitive `SYSTEM` template constant. Due to the change in the test suite, please run `eb --sync-pr-with-develop 14039` and update the PR to use `SYSTEM` instead.

**Comment by Micket** [comment]
nvompi/2022.07 replaced this

**Pull request closed without merging**
