### PR TITLE
deprecate ITK 4.13.0 easyconfigs, update ITK 4.13.0 dependencies to 4.13.1

### LINKED ISSUE #7128: ITK 4.13.0 (foss/2018a) can not download castxml-linux.tar.gz - v4.13.1 seems to work
When building ITK 4.13.0 (foss/2018a) I got a file not found error (404) on https://midas3.kitware.com/midas/api/rest?method=midas.bitstream.download&checksum=84c2851a4df419b5834114bbfafa8d3e&name=castxml-linux.tar.gz which the build procedure wants to download.  If I --try-software-version=4.13.1 I managed to build an ITK.

### PR DESCRIPTION
**Pull request by boegel**
fixes #7128

### CODE REVIEW

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in this PR)
node2006.delcatty.os - Linux centos linux 7.5.1804, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.7.5
See https://gist.github.com/b21a31e3b1e34beeaa09f637caa74871 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in this PR)
node3136.skitty.os - Linux centos linux 7.5.1804, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz, Python 2.7.5
See https://gist.github.com/d372711f20a595c0564629f120be4765 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in this PR)
node2672.swalot.os - Linux centos linux 7.5.1804, Intel(R) Xeon(R) CPU E5-2660 v3 @ 2.60GHz, Python 2.7.5
See https://gist.github.com/3f6fe9cf65fc7f494b1a96ce875548db for a full test report.

**Comment by bartoldeman** [comment]
Test report by @bartoldeman
**FAILED**
Build succeeded for 2 out of 8 (4 easyconfigs in this PR)
lg-1r17-n06 - Linux centos 6.6, Intel(R) Xeon(R) CPU E5-2650 0 @ 2.00GHz, Python 2.6.6
See https://gist.github.com/1f0fbd2eaaa93617211236cd9ea14c0c for a full test report.

**Comment by bartoldeman** [comment]
Odd issue for ITK 4.13.1: 
```
../../Generators/CastXML/castxml/bin/castxml: /lib64/libc.so.6: version `GLIBC_2.15' not found (required by ../../Generators/CastXML/castxml/bin/castxml)
../../Generators/CastXML/castxml/bin/castxml: /lib64/libc.so.6: version `GLIBC_2.14' not found (required by ../../Generators/CastXML/castxml/bin/castxml)
make[2]: *** [Wrapping/itkFixedArray.xml] Error 1
```
looks like castxml may have been precompiled, and does not run on CentOS 6. Will investigate more later.

**Comment by bartoldeman** [comment]
I had a look at `ITK-4.13.1/Wrapping/Generators/CastXML/CMakeLists.txt` in the source code. It downloads binaries for castxml in there. There is however an option `-DITK_USE_SYSTEM_CASTXML=ON` which would use a system castxml. There is an easyconfig for that, although a little bit older: https://github.com/easybuilders/easybuild-easyconfigs/blob/master/easybuild/easyconfigs/c/CastXML/CastXML-20160617-foss-2016a.eb which could probably be used as a build? dependency if updated.

**Comment by boegel** [comment]
@bartoldeman Indeed, there's a lot of downloading going on in ITK, and we should probably deal with that properly.

That's actually a way in which we can fix ITK 4.13.0 rather than deprecating it and updating the ITK dependencies in place, see also the discussion in https://github.com/InsightSoftwareConsortium/ITK/issues/145.

I'll try and took a look at how difficult that would be. It seems like ITK is also downloading FFTW and building it from source, which is definitely NOT ok...

**Comment by boegel** [comment]
superseded by #7196, turns out the installation of ITK 4.13.0 can be fixed by providing dependencies ourselves

**Pull request closed without merging**
