### PR TITLE
{bio}[GCCcore/10.2.0] prodigal v2.6.3

### PR DESCRIPTION
**Pull request by boegel**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
node3544.doduo.os - Linux RHEL 8.2, x86_64, AMD EPYC 7552 48-Core Processor (zen2), Python 3.6.8
See https://gist.github.com/b23d8560191c0c63e45167bca35da547 for a full test report.

**Comment by boegel** [comment]
@boegelbot please test @ generoso

**Review by Micket — COMMENTED** [review]
lgtm

**Comment by Micket** [comment]
Test report by @Micket
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
vera-c1 - Linux centos linux 7.9.2009, x86_64, Intel Xeon Processor (Skylake), Python 2.7.5
See https://gist.github.com/e5e20e2e137497eebda1c1d7ca6b5dd2 for a full test report.

**Review by Micket — APPROVED** [review]
forgot to actually select approve

**Pull request merged**
