### PR TITLE
add patch for Kent_tools v422 to ensure OpenSSL dependency is used + add missing freetype dependency

### PR DESCRIPTION
**Pull request by sassy-crick**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by zao** [comment]
Test report by @zao
**FAILED**
Build succeeded for 0 out of 1 (1 easyconfigs in total)
eb-rocky8 - Linux UNKNOWN UNKNOWN, x86_64, AMD Ryzen 9 3900X 12-Core Processor, Python 3.9.2
See https://gist.github.com/d2d1964360a23bef6c827adefe6bafed for a full test report.

**Comment by sassy-crick** [comment]
@zao If you want to test it again, I corrected the checksum. Sorry for that and thanks for testing.

**Comment by zao** [comment]
Test report by @zao
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
eb-rocky8 - Linux UNKNOWN UNKNOWN, x86_64, AMD Ryzen 9 3900X 12-Core Processor, Python 3.9.2
See https://gist.github.com/3a61e8ca3ba923d664dbff8a452f5617 for a full test report.

**Comment by zao** [comment]
Test report by @zao
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
eb-u1604 - Linux ubuntu 16.04, x86_64, AMD Ryzen 9 3900X 12-Core Processor, Python 2.7.12
See https://gist.github.com/6e94fbbe8c49991ec0509250495c0d20 for a full test report.

**Comment by boegel** [comment]
@boegelbot please test @ generoso
CORE_CNT=16

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
node3103.skitty.os - Linux centos linux 7.9.2009, x86_64, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz (skylake_avx512), Python 3.6.8
See https://gist.github.com/777aa4da35866a9f97705baa0c1984a0 for a full test report.

**Review by boegel — APPROVED** [review]
lgtm

**Comment by boegel** [comment]
Going in, thanks @sassy-crick!

**Pull request merged**
