### PR TITLE
use custom easyblock for Rust 1.70.0

### PR DESCRIPTION
**Pull request by boegel**
(created using `eb --new-pr`)

requires:
* #18169 
* https://github.com/easybuilders/easybuild-easyblocks/pull/2952

### CODE REVIEW

**Comment by boegel** [comment]
@boegelbot please test @ generoso
CORE_CNT=16
EB_ARGS="--include-easyblocks-from-pr 2952"

**Comment by boegel** [comment]
@boegelbot please test @ generoso
CORE_CNT=16
EB_ARGS="--include-easyblocks-from-pr 2952 --rpath --installpath /tmp/$USER/pr18167-rpath"

**Comment by casparvl** [comment]
Test report by @casparvl
Using easyblocks from PR(s) https://github.com/easybuilders/easybuild-easyblocks/pull/2952
**SUCCESS**
Build succeeded for 2 out of 2 (1 easyconfigs in total)
tcn352.local.snellius.surf.nl - Linux Rocky Linux 8.8, x86_64, AMD EPYC 7H12 64-Core Processor, Python 3.6.8
See https://gist.github.com/casparvl/3d009701a2d6a2769dc32166038727ce for a full test report.

**Review by casparvl — APPROVED** [review]
Lgtm!

**Comment by casparvl** [comment]
Going in, thanks @boegel!

**Pull request merged**
