### PR TITLE
{bio}[foss-2015a] RELION 1.4 (double- and single-precision support)

### PR DESCRIPTION
**Pull request by riccardomurri**
Add EB configs for building RELION 1.4, in double (default) and single precision mode.

### CODE REVIEW

**Comment by verdurin** [comment]
@riccardomurri - would be interesting to compare with #2653

**Comment by riccardomurri** [comment]
@verdurin Well, this one is just the existing RELION-1.3 `.eb` file, with version number umped +  `--enable-float` for the singleprecision flavor.  I understand that a big part of #2653 is providing sane FLTK and X11 easyconfigs, which I didn't care much about as I rely on OS-provided packages for that part.

**Comment by riccardomurri** [comment]
I'll be glad to merge the two, anyway :-)

**Comment by migueldiascosta** [comment]
@riccardomurri, this PR is being closed for the following reason(s): no activity for > 1 year.
Please don't hesitate to reopen this PR or add a comment if you feel this contribution is still relevant.
For more information on our policy w.r.t. closing PRs, see https://easybuild.readthedocs.io/en/latest/Contributing.html#why-a-pull-request-may-be-closed-by-a-maintainer

**Pull request closed without merging**
