### PR TITLE
added easyconfig for miniconda

### PR DESCRIPTION
**Pull request by pescobar**
this one depends on https://github.com/easybuilders/easybuild-easyblocks/pull/1210

### CODE REVIEW

**Comment by boegel** [comment]
@pescobar please replace `Miniconda` with `Miniconda2` in the filename (and directory name) to make Travis happy

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
node2085.delcatty.os - Linux centos linux 7.3.1611, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.7.5
See https://gist.github.com/50a00d845cd10be748c860f250cf81c3 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
node2400.golett.os - Linux centos linux 7.3.1611, Intel(R) Xeon(R) CPU E5-2680 v3 @ 2.50GHz, Python 2.7.5
See https://gist.github.com/f18c6057631ceb08abbfa5adef032624 for a full test report.

**Comment by pescobar** [comment]
@boegel I have renamed the files as requested

**Pull request merged**
