### PR TITLE
{bio}[GCC/8.3.0] bcl2fastq2 v2.20.0

### PR DESCRIPTION
**Pull request by boegel**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
node3401.kirlia.os - Linux centos linux 7.7.1908, x86_64, Intel(R) Xeon(R) Gold 6240 CPU @ 2.60GHz (cascadelake), Python 2.7.5
See https://gist.github.com/eb8d9ff67e16c02b16b7c87fd2c02ebb for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
node2537.golett.os - Linux centos linux 7.7.1908, x86_64, Intel(R) Xeon(R) CPU E5-2680 v3 @ 2.50GHz (haswell), Python 2.7.5
See https://gist.github.com/8dbbfe24a83a336a0a5328f22927dcac for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
node3149.skitty.os - Linux centos linux 7.7.1908, x86_64, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz (skylake_avx512), Python 3.6.8
See https://gist.github.com/96a459813360a7424b4f8f114a91115c for a full test report.

**Comment by verdurin** [comment]
@boegel why is it complaining about `GraphViz` in the unit tests?

**Comment by verdurin** [comment]
@boegel could you take a look at the test failures? Or do I just need to re-trigger?

**Comment by Micket** [comment]
re-try the checks as they didn't make much sense

**Comment by Micket** [comment]
Test report by @Micket
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
hebbe-c1 - Linux centos linux 7.7.1908, Intel Core Processor (Haswell, no TSX), Python 2.7.5
See https://gist.github.com/9d1db39fdc45db8cf133d37b07fdca17 for a full test report.

**Comment by Micket** [comment]
Going in, thanks @boegel!

**Pull request merged**
