### PR TITLE
{bio}[GCC/8.2.0-2.31.1] STAR-Fusion v1.6.0

### PR DESCRIPTION
**Pull request by lexming**
(created using `eb --new-pr`)
Update of STAR-Fusion to version 1.6.0. Adds dependency with SAMTools and the Perl module URL::Escape. Compared to PR #8640, this build has a more exhaustive list of Perl modules.

### CODE REVIEW

**Comment by lexming** [comment]
Test report by @lexming
**FAILED**
Build succeeded for 1 out of 3 (1 easyconfigs in this PR)
login2.cerberus.os - Linux centos linux 7.6.1810, Intel(R) Xeon(R) Gold 6126 CPU @ 2.60GHz, Python 2.7.5
See https://gist.github.com/f78bcaef802614533b20ad06944024e8 for a full test report.

**Comment by lexming** [comment]
Test report by @lexming
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
login2.cerberus.os - Linux centos linux 7.6.1810, Intel(R) Xeon(R) Gold 6126 CPU @ 2.60GHz, Python 2.7.5
See https://gist.github.com/afaf9c3a32d8d81c91f03365725b5116 for a full test report.

**Comment by lexming** [comment]
Do *not* merge this PR. Just received a bug related to it.

**Comment by lexming** [comment]
The provided genome for `STAR-Fusion-1.6.0` is based on `STAR-2.7.0`, so it does not work with `STAR-2.7.1a`. I added `STAR/2.7.0f-GCC-8.2.0-2.31.1` and downgraded the dependency of `STAR-Fusion-1.6.0`. However, I do not know what should be done with `STAR-2.7.1a`, should it be removed from the repository or can it stay?
I also added a dependency on `Python-3.7.2` as it is needed by the inspector tool.

**Comment by lexming** [comment]
> AssertionError: '-Python-%(pyver)s' included in versionsuffix in STAR-Fusion-1.6.0-GCC-8.2.0-2.31.1-Perl-5.28.1.eb

I was told that we were dropping versionsuffixes for Python.

**Comment by Micket** [comment]
> I was told that we were dropping versionsuffixes for Python.

Only when we can support both using `multi_deps`.

**Comment by lexming** [comment]
Thanks for the clarification :+1: Fixed

**Comment by smoors** [comment]
Going in, thanks @lexming!

**Pull request merged**
