### PR TITLE
fix source URLs for Boost 1.71.0 - 1.74.0 easyconfigs (Boost is moving download location as bintray is closing)

### PR DESCRIPTION
**Pull request by branfosj**
(created using `eb --new-pr`)

part of #12099 - see https://lists.boost.org/Archives/boost/2021/04/251458.php

### CODE REVIEW

**Comment by branfosj** [comment]
Test report by @branfosj
**SUCCESS**
Build succeeded for 9 out of 9 (9 easyconfigs in total)
bb-pg-login02.bear.cluster - Linux RHEL 8.3, x86_64, Intel(R) Xeon(R) CPU E5-2620 v4 @ 2.10GHz (broadwell), Python 3.6.8
See https://gist.github.com/51b2c1a4a301389c6417b8784c210da6 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 9 out of 9 (9 easyconfigs in total)
node2704.swalot.os - Linux centos linux 7.9.2009, x86_64, Intel(R) Xeon(R) CPU E5-2660 v3 @ 2.60GHz (haswell), Python 3.6.8
See https://gist.github.com/16599b9dd6dcb460e24fde5685c01c77 for a full test report.

**Review by boegel — APPROVED** [review]
lgtm

**Comment by boegel** [comment]
Going in, thanks @branfosj!

**Pull request merged**
