### PR TITLE
{data}[intel/2022a] scikit-learn v1.1.2 w/ Python 3.10.4

### PR DESCRIPTION
**Pull request by schiotz**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by schiotz** [comment]
This is a trivial port from foss/2022a to intel/2022a.

**Comment by Micket** [comment]
@boegelbot please test @ generoso

**Comment by Micket** [comment]
Test report by @Micket
**FAILED**
Build succeeded for 0 out of 2 (1 easyconfigs in total)
vera-c2 - Linux Rocky Linux 8.4, x86_64, Intel Xeon Processor (Skylake), Python 3.6.8
See https://gist.github.com/801813a8c9cb4b59b9e80a1158134105 for a full test report.

**Comment by schiotz** [comment]
The failed test by @Micket seems to be a "No space left on device" while building Scipy-bundle.

**Review by Micket — APPROVED** [review]
lgtm

**Comment by Micket** [comment]
Test report by @Micket
**SUCCESS**
Build succeeded for 2 out of 2 (1 easyconfigs in total)
vera-c2 - Linux Rocky Linux 8.4, x86_64, Intel Xeon Processor (Skylake), Python 3.6.8
See https://gist.github.com/ffa209610fe5e1aba301c8213b55e907 for a full test report.

**Comment by Micket** [comment]
Going in, thanks @schiotz!

**Pull request merged**
