### PR TITLE
{vis}[GCCcore/12.3.0] GLib v2.77.1

### PR DESCRIPTION
**Pull request by stefan-wolfsheimer**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by verdurin** [comment]
Test report by @verdurin
**FAILED**
Build succeeded for 15 out of 17 (1 easyconfigs in total)
easybuild-c7.novalocal - Linux CentOS Linux 7.9.2009, x86_64, Intel Xeon Processor (Skylake, IBRS), Python 3.6.8
See https://gist.github.com/verdurin/8a4299e5c56ab41d00a5f40576d790d8 for a full test report.

**Comment by casparvl** [comment]
@boegelbot please test @ generoso

**Comment by casparvl** [comment]
@boegelbot please test @ jsc-zen2

**Comment by verdurin** [comment]
Here's the error I saw:
```
  CC       lib/eject-monotonic.o
sys-utils/setarch.c:90:7: error: PER_LINUX_FDPIC undeclared here (not in a function); did you mean PER_LINUX_32BIT?
   90 |     X(PER_LINUX_FDPIC) \
      |       ^~~~~~~~~~~~~~~
sys-utils/setarch.c:345:27: note: in definition of macro X
  345 | #define X(opt) { .value = opt, .name = #opt },
      |                           ^~~
sys-utils/setarch.c:346:9: note: in expansion of macro ALL_PERSONALITIES
  346 |         ALL_PERSONALITIES
      |         ^~~~~~~~~~~~~~~~~
make[2]: *** [sys-utils/setarch.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[2]: Leaving directory `/dev/shm/utillinux/2.39/GCCcore-12.3.0/util-linux-2.39'
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory `/dev/shm/utillinux/2.39/GCCcore-12.3.0/util-linux-2.39'
make: *** [all] Error 2
```

**Comment by verdurin** [comment]
@casparvl yes, fine to ignore that error for this PR.

**Comment by casparvl** [comment]
Ok, issue created here https://github.com/easybuilders/easybuild-easyconfigs/issues/18519 for reference

**Comment by casparvl** [comment]
Going in, thanks @stefan-wolfsheimer!

**Pull request merged**
