### PR TITLE
{lang,lib}[GCCcore/13.3.0] Python v3.12.3, libreadline v8.2, Tcl v8.6.14, libffi v3.4.5, SQLite v3.45.3

### PR DESCRIPTION
**Pull request by SebastianAchilles**
(created using `eb --new-pr`)
Based on https://github.com/easybuilders/easybuild-easyconfigs/pull/20407 from @branfosj

Depends on:
- https://github.com/easybuilders/easybuild-easyconfigs/pull/20574

### CODE REVIEW

**Comment by SebastianAchilles** [comment]
Test report by @sebastianachilles
**SUCCESS**
Build succeeded for 5 out of 5 (5 easyconfigs in total)
jscclxc1.int.jsc-clx.fz-juelich.de - Linux Rocky Linux 9.4, x86_64, Intel Xeon Processor (Cascadelake) (cascadelake), Python 3.9.18
See https://gist.github.com/SebastianAchilles/df53a146122ecc11ac2865efba55f1e7 for a full test report.

**Comment by lexming** [comment]
@boegelbot: please test @ generoso

**Comment by boegel** [comment]
@boegelbot please test @ jsc-zen3

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 7 out of 7 (5 easyconfigs in total)
aarch64-neoverse-n1-node1.int.aws-rocky88-202310.eessi.io - Linux Rocky Linux 8.9, AArch64, ARM UNKNOWN (neoverse_n1), Python 3.6.8
See https://gist.github.com/boegel/ace855434ac0e95c47674cc08556f606 for a full test report.

**Comment by bedroge** [comment]
Test report by @bedroge
**SUCCESS**
Build succeeded for 5 out of 5 (5 easyconfigs in total)
bob-Latitude-5300 - Linux Ubuntu 22.04, x86_64, Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz, Python 3.10.12
See https://gist.github.com/bedroge/eda5533ea3730bca33ef7dc3cae99474 for a full test report.

**Comment by bedroge** [comment]
Test report by @bedroge
**SUCCESS**
Build succeeded for 5 out of 5 (5 easyconfigs in total)
interactive1 - Linux Rocky Linux 8.9, x86_64, AMD EPYC-Milan Processor (zen2), Python 3.6.8
See https://gist.github.com/bedroge/21346f072c7482dcf45f6e5ab13cd6fe for a full test report.

**Review by boegel — APPROVED** [review]
lgtm

**Comment by boegel** [comment]
Going in, thanks @SebastianAchilles!

**Comment by branfosj** [comment]
Test report by @branfosj
**FAILED**
Build succeeded for 4 out of 5 (5 easyconfigs in total)
bear-pg0105u03a - Linux RHEL 8.6, x86_64, Intel(R) Xeon(R) Platinum 8360Y CPU @ 2.40GHz (icelake), Python 3.6.8
See https://gist.github.com/branfosj/a55d5e83886cb27c174716b59e6b9412 for a full test report.

**Comment by branfosj** [comment]
```
/usr/bin/install: cannot stat 'Modules/_tkinter.cpython-312-x86_64-linux-gnu.so': No such file or directory
make: *** [Makefile:2083: sharedinstall] Error 1
```

This is consistent with the issue I had in #20407 that lead me to adding `Tk` as a dep.

**Comment by branfosj** [comment]
Test report by @branfosj
**SUCCESS**
Build succeeded for 5 out of 5 (5 easyconfigs in total)
bear-pg0207u28a.bear.cluster - Linux RHEL 8.6, x86_64, AMD EPYC 9554 64-Core Processor (zen4), Python 3.6.8
See https://gist.github.com/branfosj/4b8e04e17cc03992124bf7dbf5ddb8ee for a full test report.

**Comment by SebastianAchilles** [comment]
> This is consistent with the issue I had in #20407 that lead me to adding `Tk` as a dep.

The problem with adding `Tk` as a dep would be that we would create a circular dependency chain:

`libpciaccess/0.18.1` updated the build system to Meson, c.f. https://github.com/easybuilders/easybuild-easyconfigs/pull/20580

Python -> Tk, Tk -> X11, X11 -> libpciaccess, libpciaccess -> Meson, Meson -> Python

**Comment by branfosj** [comment]
Test report by @branfosj
**FAILED**
Build succeeded for 4 out of 5 (5 easyconfigs in total)
bear-pg0211u03a.bear.cluster - Linux RHEL 8.6, x86_64, Intel(R) Xeon(R) Gold 6248 CPU @ 2.50GHz (cascadelake), Python 3.6.8
See https://gist.github.com/branfosj/b7dc321df1c163eced9524cac36c0130 for a full test report.

**Comment by branfosj** [comment]
Test report by @branfosj
**SUCCESS**
Build succeeded for 5 out of 5 (5 easyconfigs in total)
bear-pg0207u20a - Linux RHEL 8.6, x86_64, Intel(R) Xeon(R) Platinum 8480CL (sapphirerapids), Python 3.6.8
See https://gist.github.com/branfosj/b8a98586b72756db4692b59dcffc3138 for a full test report.

**Comment by branfosj** [comment]
> > This is consistent with the issue I had in #20407 that lead me to adding `Tk` as a dep.
> 
> The problem with adding `Tk` as a dep would be that we would create a circular dependency chain:
> 
> `libpciaccess/0.18.1` updated the build system to Meson, c.f. #20580
> 
> Python -> Tk, Tk -> X11, X11 -> libpciaccess, libpciaccess -> Meson, Meson -> Python

See #20630

**Pull request merged**
