### PR TITLE
remove unused WITH_BLAS and WITH_LAPACK options for CGAL 5

### LINKED ISSUE #15040: CGAL does not use BLAS/LAPACK anymore
https://github.com/CGAL/cgal/issues/4267#issuecomment-537855196

This makes this line moot: https://github.com/easybuilders/easybuild-easyconfigs/blob/e2996415381814d40e99e299f07043b9a9b24199/easybuild/easyconfigs/c/CGAL/CGAL-5.2-gompi-2020b.eb#L36

### PR DESCRIPTION
**Pull request by branfosj**
(created using `eb --new-pr`)

fixes #15040

### CODE REVIEW

**Comment by branfosj** [comment]
@boegelbot please test @ generoso

**Comment by branfosj** [comment]
Test report by @branfosj
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
bear-pg0211u03a.bear.cluster - Linux RHEL 8.6, x86_64, Intel(R) Xeon(R) Gold 6248 CPU @ 2.50GHz (cascadelake), Python 3.6.8
See https://gist.github.com/776e77afb818d63d0750c888df65d3c1 for a full test report.

**Review by boegel — APPROVED** [review]
lgtm

**Comment by boegel** [comment]
@boegelbot please test @ generoso
EB_ARGS="--include-easyblocks-from-pr 2736"

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
node3502.doduo.os - Linux RHEL 8.4, x86_64, AMD EPYC 7552 48-Core Processor (zen2), Python 3.6.8
See https://gist.github.com/729a8b7ccd73474992f1cef8ce624d7c for a full test report.

**Comment by boegel** [comment]
Going in, thanks @branfosj!

**Pull request merged**
