### PR TITLE
add patch for Bison 3.7.1 to fix build error on old OS versions 

### PR DESCRIPTION
**Pull request by patbel-pwr**
Bison-3.7.1.eb was crashing on Scientific Linux 6.10 with following error:
`src/parse-simulation.c:61: error: redefinition of typedef 'parse_state'
src/parse-simulation.h:74: note: previous declaration of 'parse_state' was here`
fix is to change the definition in `parse_simulation.c` to be of just the struct.

Patch is commented out in Bison-3.7.1.eb with comment above on when to uncomment.

There was no issue created for this as we discussed it and I received help @ slack.

### CODE REVIEW

**Comment by boegel** [comment]
If this patch won't cause problems on other operating systems, why not simply always apply it?

@zao Thoughts?

**Comment by zao** [comment]
It could indeed be unconditional.

**Comment by zao** [comment]
I've verified this assumption by successfully building on Ubuntu 20.04 with their 9.3.0 system compiler, still good.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
node3147.skitty.os - Linux RHEL 8.8, x86_64, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz (skylake_avx512), Python 3.6.8
See https://gist.github.com/boegel/c7b41a821a54575225e3daf93a9ef0f5 for a full test report.

**Comment by boegel** [comment]
@boegelbot please test @ generoso

**Comment by boegel** [comment]
@boegelbot please test @ jsc-zen2

**Review by boegel — APPROVED** [review]
lgtm

**Comment by boegel** [comment]
Going in, thanks @patbel-pwr!

**Pull request merged**
