### PR TITLE
{bio}[gompi/2019a] prokka v1.14.5

### PR DESCRIPTION
**Pull request by boegel**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
node3112.skitty.os - Linux centos linux 7.7.1908, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz, Python 3.6.8
See https://gist.github.com/9c8117b9f8b3154ebf6bc7d565506fda for a full test report.

**Comment by boegel** [comment]
The `tbl2asn` binary included with `prokka` 1.13.7 refuses to run because it considers itself too old (see also https://github.com/tseemann/prokka/issues/444).

Easiest way out is to install the latest available `prokka` release which includes a newer version of `tbl2asn` (which is also already outdated though...).

**Comment by migueldiascosta** [comment]
Test report by @migueldiascosta
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
generoso - Linux centos linux 7.6.1810, Intel(R) Xeon(R) CPU E5-2660 v4 @ 2.00GHz, Python 3.6.8
See https://gist.github.com/fbcca7e33c374043b90323baf5009258 for a full test report.

**Comment by migueldiascosta** [comment]
Going in, thanks @boegel!

**Pull request merged**
