### PR TITLE
skip flaky test in PyTorch 1.9.0

### LINKED ISSUE #16233: Failing test_autograd in `PyTorch/1.9.0-fosscuda-2020b` + `PyTorch-1.9.0-fosscuda-2020b-imkl.eb` on Intel Cascade Lake V100 system
One failing test for `PyTorch/1.9.0-fosscuda-2020b` + `PyTorch-1.9.0-fosscuda-2020b-imkl.eb` on our Intel Cascade Lake V100 system (test report coming up), perhaps this one is also flaky: `test_autograd`

```
======================================================================
FAIL: test_thread_shutdown (__main__.TestAutograd)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_autograd.py", line 4360, in test_thread_shutdown
    self.assertRegex(s, "PYTORCH_API_USAGE torch.autograd.thread_shutdown")
AssertionError: Regex didn't match: 'PYTORCH_API_USAGE torch.autograd.thread_shutdown' not found in 'PYTORCH_API_USAGE torch.python.import\nPYTORCH_API_USAGE c10d.python.import\nPYTORCH_API_USAGE tensor.create\n'

----------------------------------------------------------------------
Ran 951 tests in 23.361s

FAILED (failures=1, skipped=312, expected failures=1)
test_autograd failed!
```

_Originally posted by @boegel in https://github.com/easybuilders/easybuild-easyconfigs/issues/15919#issuecomment-1242759805_

### PR DESCRIPTION
**Pull request by Flamefire**
(created using `eb --new-pr`)

Fixes #16233 reported by @boegel

### CODE REVIEW

**Comment by Flamefire** [comment]
Test report by @Flamefire
**SUCCESS**
Build succeeded for 1 out of 1 (3 easyconfigs in total)
taurusml4 - Linux RHEL 7.6, POWER, 8335-GTX (power9le), 6 x NVIDIA Tesla V100-SXM2-32GB, 440.64.00, Python 2.7.5
See https://gist.github.com/351863c598c86532998f088a17161605 for a full test report.

**Comment by Flamefire** [comment]
Test report by @Flamefire
**SUCCESS**
Build succeeded for 3 out of 3 (3 easyconfigs in total)
taurusml4 - Linux RHEL 7.6, POWER, 8335-GTX (power9le), 6 x NVIDIA Tesla V100-SXM2-32GB, 440.64.00, Python 2.7.5
See https://gist.github.com/aa1b09974b95129791bc10e9cf8e3763 for a full test report.

**Comment by boegel** [comment]
@Flamefire Seems like this is also relevant for PyTorch 1.11.0, see https://github.com/easybuilders/easybuild-easyblocks/pull/2794#issuecomment-1271857600 (although there we do allow a minimal number of failing tests).

Let's change the PyTorch 1.11.0 easyconfigs in a separate PR though, so the test reports are more feasible, successful test report from my side is imminent for this PR...

**Comment by Flamefire** [comment]
Possible actual fix has been pushed to PyTorch: https://github.com/pytorch/pytorch/pull/86464

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 3 out of 3 (3 easyconfigs in total)
node3305.joltik.os - Linux RHEL 8.4, x86_64, Intel(R) Xeon(R) Gold 6242 CPU @ 2.80GHz (cascadelake), 1 x NVIDIA Tesla V100-SXM2-32GB, 510.85.02, Python 3.6.8
See https://gist.github.com/caa47e4756bf572ebe2422fead5537ac for a full test report.

**Review by boegel — APPROVED** [review]
lgtm

**Comment by boegel** [comment]
Going in, thanks @Flamefire!

**Pull request merged**
