### PR TITLE
{bio}[intel-2018a] trimAl v1.4.1

### PR DESCRIPTION
**Pull request by pescobar**

### CODE REVIEW

**Comment by akesandgren** [comment]
Since goolf is deprecated, how do we move forward with this one? @boegel @pescobar

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
node3402.kirlia.os - Linux centos linux 7.8.2003, x86_64, Intel(R) Xeon(R) Gold 6240 CPU @ 2.60GHz (cascadelake), Python 2.7.5
See https://gist.github.com/53b3fb3cb485645ba9034f9644587297 for a full test report.

**Review by boegel — APPROVED** [review]
lgtm

**Comment by boegel** [comment]
Going in, thanks @pescobar!

**Pull request merged**
