### PR TITLE
{vis}[GCCcore/11.2.0] Graphviz v2.50.0 w/ Python 3.9.6

### PR DESCRIPTION
**Pull request by zemu-unile**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by zemu-unile** [comment]
Removed lefty from the sanity check as it is not built by default anymore.

https://gitlab.com/graphviz/graphviz/-/blob/main/CHANGELOG.md#2492-2021-10-16

> Lefty is disabled by default in the Autotools build system. To re-enable it,
pass --enable-lefty to ./configure. In a future release, Lefty will be
removed.

**Comment by lexming** [comment]
@boegelbot: please test @ generoso

**Comment by lexming** [comment]
Test report by @lexming
**SUCCESS**
Build succeeded for 4 out of 4 (1 easyconfigs in total)
node304.hydra.os - Linux centos linux 7.9.2009, x86_64, Intel(R) Xeon(R) Gold 6148 CPU @ 2.40GHz, Python 2.7.5
See https://gist.github.com/2d961c443a433ce156bf62a0b1c4648e for a full test report.

**Review by lexming — APPROVED** [review]
LGTM

**Comment by lexming** [comment]
Going in, thanks @zemu-unile !

**Pull request merged**
