### PR TITLE
{bio}[foss/2019b] Telescope v1.0.3 w/ Python 3.7.4

### PR DESCRIPTION
**Pull request by lexming**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by lexming** [comment]
Test report by @lexming
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
node381.hydra.os - Linux centos linux 7.7.1908, x86_64, Intel(R) Xeon(R) Gold 6148 CPU @ 2.40GHz, Python 2.7.5
See https://gist.github.com/34942b06284e3946bff3808941aa27eb for a full test report.

**Comment by lexming** [comment]
Test report by @lexming
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
node110.hydra.os - Linux centos linux 7.7.1908, x86_64, Intel(R) Xeon(R) CPU E5-2680 v2 @ 2.80GHz, Python 2.7.5
See https://gist.github.com/4e0887f5f4cc0eb8c7f8c005d81f3acd for a full test report.

**Comment by verdurin** [comment]
Test report by @verdurin
**SUCCESS**
Build succeeded for 2 out of 2 (1 easyconfigs in this PR)
easybuild.novalocal - Linux centos linux 7.8.2003, x86_64, Intel Xeon Processor (Skylake, IBRS), Python 2.7.5
See https://gist.github.com/7564fb14592885ea565dc0ca00c09721 for a full test report.

**Comment by verdurin** [comment]
@lexming I just had to include `sortedcontainers` and `intervaltree` in a bundle. Perhaps they should be added to the main `Python`?

**Comment by lexming** [comment]
@verdurin that's indeed a good idea, I'll update this PR

**Comment by lexming** [comment]
@verdurin I just checked and there are several packages bundling `intervaltree` and `sortedcontainers`. It will be messy to update this PR. Can you merge it and then I'll make a new one updating Python and all easyconfigs with those packages?

**Comment by verdurin** [comment]
@lexming yes, of course - I didn't mean fixing it all in this PR.

**Comment by verdurin** [comment]
Going in, thanks @lexming!

**Pull request merged**
