### PR TITLE
add patch for OpenBLAS 0.3.15 to fix failing numpy tests on aarch64

### LINKED ISSUE #11959: failing numpy test(s) in SciPy-bundle with foss toolchain on (some) Arm CPUs (aarch64)
When installing `SciPy-bundle-2020.03-foss-2020a-Python-3.8.2.eb` with `eb --optarch=GENERIC` on Arm Graviton2 (AWS), a single numpy test is failing:

```
=================================== FAILURES ===================================
____________________ TestEinsum.test_index_transformations _____________________

self = <numpy.core.tests.test_einsum.TestEinsum object at 0xffff9825d460>

    def test_index_transformations(self):
        # Simple index transformation cases
        self.optimize_compare('ea,fb,gc,hd,abcd->efgh')
>       self.optimize_compare('ea,fb,abcd,gc,hd->efgh')

self       = <numpy.core.tests.test_einsum.TestEinsum object at 0xffff9825d460>

/tmp/eb-dk3pzk_h/tmpz9oszsac/lib/python3.8/site-packages/numpy/core/tests/test_einsum.py:775:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
/tmp/eb-dk3pzk_h/tmpz9oszsac/lib/python3.8/site-packages/numpy/core/tests/test_einsum.py:763: in optimize_compare
    assert_almost_equal(opt, noopt)
        args       = ['ea,fb,abcd,gc,hd->efgh', array([[0.65346152, 0.97957568],
       [0.0948278 , 0.04640728],
       [0.37502837, 0.579...    7.78283412e-01],
       [2.59291967e-01, 1.92160156e-01, 3.45901939e-01, 1.99300172e-02,
        5.78772218e-01]])]
        dims       = [6, 5]
        noopt      = array([[[[ 5.40056697, 11.07472405,  4.65352273,  6.29894419,
           6.04342205,  4.06487333],
         [ 5.290337...42,  1.55698052],
         [ 2.06246446,  4.25820419,  1.79936898,  2.43354334,
           2.34070224,  1.56586802]]]])
        operands   = None
        opt        = array([[[[nan, nan, nan, nan, nan, nan],
         [nan, nan, nan, nan, nan, nan]],

        [[nan, nan, nan, nan, nan,... [nan, nan, nan, nan, nan, nan]],

        [[nan, nan, nan, nan, nan, nan],
         [nan, nan, nan, nan, nan, nan]]]])
        self       = <numpy.core.tests.test_einsum.TestEinsum object at 0xffff9825d460>
        subscripts = 'ea,fb,abcd,gc,hd->efgh'
        term       = 'hd'
        terms      = ['ea', 'fb', 'abcd', 'gc', 'hd']
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
...
>           raise AssertionError(msg)
E           AssertionError:
E           Arrays are not almost equal to 7 decimals
E
E           x and y nan location mismatch:
E            x: array([[[[nan, nan, nan, nan, nan, nan],
E                    [nan, nan, nan, nan, nan, nan]],
E           ...
E            y: array([[[[ 5.400567 , 11.0747241,  4.6535227,  6.2989442,  6.0434221,
E                      4.0648733],
E                    [ 5.2903379, 11.0452866,  4.6875647,  6.2371511,  6.0661887,...
```

This problem does not occur when building without `--optarch=GENERIC` (so using `-march=native`) on the same system...

We've built SciPy-bundle 2020.03 with `foss/2020a` before in the same setup, but then the failing test went unnoticed (see https://github.com/easybuilders/easybuild-easyblocks/pull/2238).

### PR DESCRIPTION
**Pull request by boegel**
(created using `eb --new-pr`)

fixes #11959

### CODE REVIEW

**Comment by boegel** [comment]
@boegelbot please test @ generoso
EB_ARGS="OpenBLAS-0.3.15-GCC-10.3.0.eb SciPy-bundle-2021.05-foss-2021a.eb"

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in total)
select-pika-c6gd-2xlarge-0001 - Linux centos linux 8.3.2011, AArch64, ARM UNKNOWN (graviton2), Python 3.6.8
See https://gist.github.com/8831f0279ec028984dfa19aaecd153c0 for a full test report.

**Comment by lexming** [comment]
Test report by @lexming
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
node381.hydra.os - Linux centos linux 7.9.2009, x86_64, Intel(R) Xeon(R) Gold 6148 CPU @ 2.40GHz, Python 2.7.5
See https://gist.github.com/8a4feb665d1cfa4964f2de00dfdeb393 for a full test report.

**Review by lexming — APPROVED** [review]
LGTM

**Comment by lexming** [comment]
Going in, thanks @boegel !

**Comment by lexming** [comment]
Test report by @lexming
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
node107.hydra.os - Linux centos linux 7.9.2009, x86_64, Intel(R) Xeon(R) CPU E5-2680 v2 @ 2.80GHz, Python 2.7.5
See https://gist.github.com/be33d9ab97fe3e2ae59713188601b58b for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 14 out of 14 (2 easyconfigs in total)
node2625.swalot.os - Linux centos linux 7.9.2009, x86_64, Intel(R) Xeon(R) CPU E5-2660 v3 @ 2.60GHz (haswell), Python 3.6.8
See https://gist.github.com/eb46b73f7003d84807e88bbd89332c00 for a full test report.

**Pull request merged**
