### PR TITLE
{lib}[foss/2023a] SIRIUS v7.5.2, Umpire v2024.02.1, COSTA v2.2.2, ...

### PR DESCRIPTION
**Pull request by pavelToman**
(created using `eb --new-pr`)
resolves https://github.com/vscentrum/vsc-software-stack/issues/297

### CODE REVIEW

**Comment by pavelToman** [comment]
@boegelbot please test @ generoso

**Comment by pavelToman** [comment]
@boegelbot please test @ jsc-zen3

**Comment by verdurin** [comment]
Test report by @verdurin
**FAILED**
Build succeeded for 5 out of 8 (6 easyconfigs in total)
easybuild-el8.cloud.in.bmrc.ox.ac.uk - Linux Rocky Linux 8.10, x86_64, Intel Xeon Processor (Skylake, IBRS), Python 3.6.8
See https://gist.github.com/verdurin/437f2bf684d25b2124ac85d037856673 for a full test report.

**Comment by pavelToman** [comment]
> Test report by @verdurin **FAILED** Build succeeded for 5 out of 8 (6 easyconfigs in total) easybuild-el8.cloud.in.bmrc.ox.ac.uk - Linux Rocky Linux 8.10, x86_64, Intel Xeon Processor (Skylake, IBRS), Python 3.6.8 See https://gist.github.com/verdurin/437f2bf684d25b2124ac85d037856673 for a full test report.

checksums seems fine, some problem on your node?

**Comment by verdurin** [comment]
@pavelToman I've tried two different nodes and they both show the same checksum, which isn't the one in the easyconfig.

**Comment by verdurin** [comment]
Test report by @verdurin
**FAILED**
Build succeeded for 4 out of 7 (6 easyconfigs in total)
easybuild-el8.cloud.in.bmrc.ox.ac.uk - Linux Rocky Linux 8.10, x86_64, Intel Xeon Processor (Skylake, IBRS), Python 3.6.8
See https://gist.github.com/verdurin/fce59c2ec37b720943df051771d0c86d for a full test report.

**Comment by branfosj** [comment]
```
$ wget https://github.com/spglib/spglib/archive/v2.5.0.tar.gz
$ sha256sum v2.5.0.tar.gz
b6026f5e85106c0c9ee57e54b9399890d0f29982e20e96ede0428b3efbe6b914  v2.5.0.tar.gz
```

And that matches what @verdurin sees in the failed test report.

**Comment by branfosj** [comment]
```
$ sha256sum v2.5.0.*
b6026f5e85106c0c9ee57e54b9399890d0f29982e20e96ede0428b3efbe6b914  v2.5.0.new.tar.gz
80c060b1a606a76b15f2cc708e9fdd4a83479924ebff9ac16ed26a87a0eac1a9  v2.5.0.old.tar.gz
```

```
$ diff -r spglib-2.5.0.old spglib-2.5.0.new
diff -r spglib-2.5.0.old/example/python_api/example.py spglib-2.5.0.new/example/python_api/example.py
1a2
>
diff -r spglib-2.5.0.old/.git_archival.txt spglib-2.5.0.new/.git_archival.txt
1,2c1,2
< node: a15ae720b8c4e43d69b7afddc1f9de79c9fc83fe
< node-date: 2024-07-09T13:53:20+09:00
---
> node: e4531bb49371dce3e807c2095a4d9d9b7245c524
> node-date: 2024-07-11T17:36:56+09:00
Only in spglib-2.5.0.new/.github: renovate.json
diff -r spglib-2.5.0.old/.github/workflows/release.yaml spglib-2.5.0.new/.github/workflows/release.yaml
54c54
<       - uses: softprops/action-gh-release@v1
---
>       - uses: softprops/action-gh-release@v2
diff -r spglib-2.5.0.old/.github/workflows/step_build-wheel.yaml spglib-2.5.0.new/.github/workflows/step_build-wheel.yaml
32c32
<         uses: docker/setup-qemu-action@v2
---
>         uses: docker/setup-qemu-action@v3
36c36
<         uses: pypa/cibuildwheel@v2.17
---
>         uses: pypa/cibuildwheel@v2.19
diff -r spglib-2.5.0.old/.github/workflows/step_coverage.yaml spglib-2.5.0.new/.github/workflows/step_coverage.yaml
27c27
<         uses: lukka/run-cmake@v10.3
---
>         uses: lukka/run-cmake@v10.7
52c52
<       - uses: actions/setup-python@v4
---
>       - uses: actions/setup-python@v5
diff -r spglib-2.5.0.old/.github/workflows/step_pre-commit.yaml spglib-2.5.0.new/.github/workflows/step_pre-commit.yaml
17c17
<       - uses: actions/setup-python@v4
---
>       - uses: actions/setup-python@v5
20c20
<       - uses: pre-commit/action@v3.0.0
---
>       - uses: pre-commit/action@v3.0.1
diff -r spglib-2.5.0.old/.github/workflows/step_test-docs.yaml spglib-2.5.0.new/.github/workflows/step_test-docs.yaml
26c26
<       - uses: actions/setup-python@v4
---
>       - uses: actions/setup-python@v5
diff -r spglib-2.5.0.old/.pre-commit-config.yaml spglib-2.5.0.new/.pre-commit-config.yaml
10c10
<     rev: v1.9.5
---
>     rev: v1.9.6
26c26
<     rev: v4.5.0
---
>     rev: v4.6.0
33c33
<     rev: v0.1.13
---
>     rev: v0.5.1
39c39
<     rev: v1.8.0
---
>     rev: v1.10.1
63c63
<     rev: 0.27.3
---
>     rev: 0.29.0
74c74
<     rev: "v2.2.6"
---
>     rev: "v2.3.0"
diff -r spglib-2.5.0.old/pyproject.toml spglib-2.5.0.new/pyproject.toml
103a104,108
> before-build = [
>     "cmake -B _build -DSPGLIB_WITH_TESTS=OFF -DCMAKE_BUILD_TYPE=Release",
>     "cmake --build _build --config Release",
>     "cmake --install _build --config Release --prefix {project}/_install",
> ]
106,108c111,116
< # TODO: auditwheel fails if LD_LIBRARY_PATH is not set correctly. Not sure about apprropriate value to set to
< #repair-wheel-command = "LD_LIBRARY_PATH=. auditwheel repair --lib-sdir . -w {dest_dir} {wheel}"
< repair-wheel-command = ""
---
> before-build = [
>     "cmake -B _build -DSPGLIB_WITH_TESTS=OFF -DCMAKE_BUILD_TYPE=Release",
>     "cmake --build _build",
>     "cmake --install _build",
> ]
> repair-wheel-command = "auditwheel repair -w {dest_dir} {wheel}"
111,113c119
< # TODO: similar to above
< #repair-wheel-command = "DYLD_LIBRARY_PATH=. delocate-wheel --require-archs {delocate_archs} -w {dest_dir} -v {wheel}"
< repair-wheel-command = ""
---
> repair-wheel-command = "DYLD_LIBRARY_PATH=_install/lib delocate-wheel --require-archs {delocate_archs} -w {dest_dir} -v {wheel}"
130a137,141
> exclude = [
>     "database/*"
> ]
>
> [tool.ruff.lint]
185c196
<     "D203",  # Confilct with D211
---
>     "D203",  # Conflict with D211
diff -r spglib-2.5.0.old/python/spglib/__init__.py spglib-2.5.0.new/python/spglib/__init__.py
36d35
<
diff -r spglib-2.5.0.old/python/spglib/spglib.py spglib-2.5.0.new/python/spglib/spglib.py
752a753
>
908a910
>
1262a1265
>
1370a1374
>
1415a1420
>
1457a1463
>
1494a1501
>
1536a1544
>
1962a1971
>
2023a2033
>
2046a2057
>
diff -r spglib-2.5.0.old/test/example/python_api/example.py spglib-2.5.0.new/test/example/python_api/example.py
1a2
>
diff -r spglib-2.5.0.old/test/functional/python/conftest.py spglib-2.5.0.new/test/functional/python/conftest.py
1a2
>
diff -r spglib-2.5.0.old/test/functional/python/test_hall_number_from_symmetry.py spglib-2.5.0.new/test/functional/python/test_hall_number_from_symmetry.py
1a2
>
diff -r spglib-2.5.0.old/test/functional/python/test_niggli_delaunay.py spglib-2.5.0.new/test/functional/python/test_niggli_delaunay.py
1a2
>
diff -r spglib-2.5.0.old/test/functional/python/test_spacegrouop_type_from_symmetry.py spglib-2.5.0.new/test/functional/python/test_spacegrouop_type_from_symmetry.py
1a2
>

```

**Comment by pavelToman** [comment]
Yes, you are right, seems my downloaded tarball was bed. Will change it to `b6026f5e85106c0c9ee57e54b9399890d0f29982e20e96ede0428b3efbe6b914`

**Comment by verdurin** [comment]
Test report by @verdurin
**FAILED**
Build succeeded for 5 out of 7 (6 easyconfigs in total)
easybuild-el8.cloud.in.bmrc.ox.ac.uk - Linux Rocky Linux 8.10, x86_64, Intel Xeon Processor (Skylake, IBRS), Python 3.6.8
See https://gist.github.com/verdurin/d5eebf75273ae4af23f289184b293534 for a full test report.

**Comment by verdurin** [comment]
Ugh, my build is failing because of the already known problem with `libxc` checksums...

**Comment by pavelToman** [comment]
@boegelbot please test @ jsc-zen3

**Comment by verdurin** [comment]
Test report by @verdurin
**FAILED**
Build succeeded for 5 out of 7 (6 easyconfigs in total)
easybuild-el8.cloud.in.bmrc.ox.ac.uk - Linux Rocky Linux 8.10, x86_64, Intel Xeon Processor (Skylake, IBRS), Python 3.6.8
See https://gist.github.com/verdurin/72471bb99b8053beaabf0e34466ba177 for a full test report.

**Comment by pavelToman** [comment]
@boegelbot please test @ generoso

**Comment by boegel** [comment]
@pavelToman I've renamed the existing `sources/s/spglib/v2.5.0.tar.gz` to ``sources/s/spglib/v2.5.0.tar.gz.old.bk` (SHA256 checksum: `80c060b1a606a76b15f2cc708e9fdd4a83479924ebff9ac16ed26a87a0eac1a9`) on both `generoso` and `jsc-zen3`, so you can try again now

**Comment by pavelToman** [comment]
@boegelbot please test @ generoso

**Comment by pavelToman** [comment]
@boegelbot please test @ jsc-zen3

**Review by boegel — APPROVED** [review]
lgtm

**Comment by boegel** [comment]
Going in, thanks @pavelToman!

**Pull request merged**
