### PR TITLE
{bio}[foss/2022b] tRNAscan-SE v2.0.12

### PR DESCRIPTION
**Pull request by Ghepardo**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by Ghepardo** [comment]
The automatic tests have failed, because they cannot see the dependency Infernal/1.1.4-foss-2022b.  A build for this has been submitted under the separate PR 17797.  I am not clear how to overcome this.  

I did try the following, quoting the branch that was automatically created for PR 17797:

```
eb --new-pr-from-branch=20230425153819_new_pr_Infernal114 tRNAscan-SE-2.0.12-foss-2022b.eb
== Temporary log file in case of crash /tmp/eb-b0gy9bc3/easybuild-zm4vmwn1.log
== found valid index for /home/apps/eb/software/EasyBuild/4.7.1/easybuild/easyconfigs, so using it...
== found valid index for /home/apps/eb/software/EasyBuild/4.7.1/easybuild/easyconfigs, so using it...
Please enter password for encrypted keyring:
== fetching branch '20230425153819_new_pr_Infernal114' from https://github.com/Ghepardo/easybuild-easyconfigs.git...
== syncing '20230425153819_new_pr_Infernal114' with current 'easybuilders/develop' branch...
== pulling latest version of 'develop' branch from easybuilders/easybuild-easyconfigs...
== merging 'develop' branch into PR branch '20230425153819_new_pr_Infernal114'...
== checking out target branch 'easybuilders/develop'...
== determining metadata for pull request based on changed files...
== found 1 changed file(s) in 'Ghepardo/20230425153819_new_pr_Infernal114' relative to 'easybuilders/develop':
* 1 new/changed easyconfig file(s):
  easybuild/easyconfigs/i/Infernal/Infernal-1.1.4-foss-2022b.eb
== checking out PR branch 'Ghepardo/20230425153819_new_pr_Infernal114'...

Opening pull request
* target: easybuilders/easybuild-easyconfigs:develop
* from: Ghepardo/easybuild-easyconfigs:20230425153819_new_pr_Infernal114
* title: "{bio}[foss/2022b] Infernal v1.1.4"
* labels: update
* description:
"""
(created using `eb --new-pr`)

"""
* overview of changes:
 .../i/Infernal/Infernal-1.1.4-foss-2022b.eb        | 39 ++++++++++++++++++++++
 1 file changed, 39 insertions(+)

Traceback (most recent call last):
  File "/usr/lib64/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib64/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/apps/eb/software/EasyBuild/4.7.1/lib/python3.6/site-packages/easybuild/main.py", line 734, in <module>
    main()
  File "/home/apps/eb/software/EasyBuild/4.7.1/lib/python3.6/site-packages/easybuild/main.py", line 724, in main
    hooks, do_build)
  File "/home/apps/eb/software/EasyBuild/4.7.1/lib/python3.6/site-packages/easybuild/main.py", line 478, in process_eb_args
    new_pr_from_branch(options.new_pr_from_branch)
  File "/home/apps/eb/software/EasyBuild/4.7.1/lib/python3.6/site-packages/easybuild/tools/github.py", line 1770, in new_pr_from_branch
    status, data = pulls_url.post(body=body)
  File "/home/apps/eb/software/EasyBuild/4.7.1/lib/python3.6/site-packages/easybuild/base/rest.py", line 139, in post
    return self.request(self.POST, url, json.dumps(body), headers, content_type='application/json')
  File "/home/apps/eb/software/EasyBuild/4.7.1/lib/python3.6/site-packages/easybuild/base/rest.py", line 176, in request
    conn = self.get_connection(method, url, body, headers)
  File "/home/apps/eb/software/EasyBuild/4.7.1/lib/python3.6/site-packages/easybuild/base/rest.py", line 217, in get_connection
    connection = self.opener.open(request)
  File "/usr/lib64/python3.6/urllib/request.py", line 532, in open
    response = meth(req, response)
  File "/usr/lib64/python3.6/urllib/request.py", line 642, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib64/python3.6/urllib/request.py", line 570, in error
    return self._call_chain(*args)
  File "/usr/lib64/python3.6/urllib/request.py", line 504, in _call_chain
    result = func(*args)
  File "/usr/lib64/python3.6/urllib/request.py", line 650, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 422: Unprocessable Entity
```

I'm afraid I have no idea what to make of those error messages.

**Comment by verdurin** [comment]
@boegelbot please test @ generoso

**Comment by verdurin** [comment]
Test report by @verdurin
**SUCCESS**
Build succeeded for 2 out of 2 (1 easyconfigs in total)
easybuild-c7.novalocal - Linux CentOS Linux 7.9.2009, x86_64, Intel Xeon Processor (Skylake, IBRS), Python 3.6.8
See https://gist.github.com/verdurin/0970a335407665a92b2df830a2cdd33a for a full test report.

**Comment by verdurin** [comment]
Going in, thanks @Ghepardo!

**Pull request merged**
