### PR TITLE
add additional valid checksum for norm 1.0-9.5 extension in R 4.1.0 and 4.1.2 easyconfigs

### PR DESCRIPTION
**Pull request by SebastianAchilles**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by boegel** [comment]
Again?!

@SebastianAchilles Did you diff the old vs new source tarball?

**Comment by SebastianAchilles** [comment]
> Again?!

This time it is a different extension though. :wink: 

> @SebastianAchilles Did you diff the old vs new source tarball?

There are no code changes, the only difference is the description and the MD5 file:

```
$ diff -ru norm_1.0-9.5_old norm_1.0-9.5
diff -ru norm_1.0-9.5_old/DESCRIPTION norm_1.0-9.5/DESCRIPTION
--- norm_1.0-9.5_old/DESCRIPTION        2013-03-01 14:30:31.000000000 +0100
+++ norm_1.0-9.5/DESCRIPTION    2022-02-09 15:35:29.000000000 +0100
@@ -17,3 +17,4 @@
 Packaged: 2013-02-27 19:16:19 UTC; rforge
 NeedsCompilation: yes
 License_restricts_use: no
+License_is_FOSS: yes
diff -ru norm_1.0-9.5_old/MD5 norm_1.0-9.5/MD5
--- norm_1.0-9.5_old/MD5        2013-03-01 14:30:31.000000000 +0100
+++ norm_1.0-9.5/MD5    2022-02-09 15:35:29.000000000 +0100
@@ -1,4 +1,4 @@
-66fded5989915184abb853d93a5f527f *DESCRIPTION
+384fddd8bb692a8332ba2d750d7b4a3a *DESCRIPTION
 d867862f44296b2c82a2bd967ad9455e *INDEX
 00586c4834941a13260ef2c23c1df3f6 *LICENSE
 4076ba3a74509a4ddec12c0ca583e1f2 *NAMESPACE
 ```
 
Therefore, it makes sense to keep accepting both the old and the new SHA256 checksum, since it doesn't really matter which source tarball you use.

**Review by akesandgren — APPROVED** [review]
LGTM

**Comment by akesandgren** [comment]
Going in, thanks @SebastianAchilles!

**Pull request merged**
