### PR TITLE
{vis}[GCCcore/13.3.0] ATK-2.38.0, Gdk-Pixbuf-2.42.11

### PR DESCRIPTION
**Pull request by ankekreuzer**
Added ATK and Gdk-Pixbuf after the GObject-Introspection fix (part of the SW stage at JSC)

### CODE REVIEW

**Comment by ankekreuzer** [comment]
Test report by @ankekreuzer
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in total)
zam329 - Linux Rocky Linux 9.4 (Blue Onyx), x86_64, Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz, Python 3.9.18
See https://gist.github.com/ankekreuzer/5d715caf7dc846709f0376ea47c9db91 for a full test report.

**Comment by SebastianAchilles** [comment]
@boegelbot please test @ jsc-zen3

**Comment by SebastianAchilles** [comment]
@boegelbot please test @ generoso

**Review by smoors — APPROVED** [review]
lgtm

**Comment by smoors** [comment]
Going in, thanks @ankekreuzer!

**Pull request merged**
