### PR TITLE
{bio}[intel/2017b] canu v1.8

### PR DESCRIPTION
**Pull request by murfreesboro**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by murfreesboro** [comment]
Test report by @murfreesboro
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
dev806.vampire - Linux centos linux 7.4.1708, Intel(R) Xeon(R) CPU           E5620  @ 2.40GHz, Python 2.7.5
See https://gist.github.com/25360c40a95b108f5fe7a9e032ce3460 for a full test report.

**Comment by vanzod** [comment]
Test report by @vanzod
**FAILED**
Build succeeded for 0 out of 1 (1 easyconfigs in this PR)
cermis - Linux debian 9.9, Intel(R) Xeon(R) CPU           X5670  @ 2.93GHz, Python 2.7.13
See https://gist.github.com/2b1655295c5c875492640e27de064465 for a full test report.

**Comment by vanzod** [comment]
@fenglai It looks like that with the Intel compiler it is necessary to rely on an external installation of `Boost`. This issue was for version 1.5 but it seems that is still valid:
https://github.com/marbl/canu/issues/516#issuecomment-306571518

@boegel Do you think it would be worth adding the `Boost` dependency to the easyconfig that builds with the `foss` toolchain for consistency?

**Comment by vanzod** [comment]
Test report by @vanzod
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
cermis - Linux debian 9.9, Intel(R) Xeon(R) CPU           X5670  @ 2.93GHz, Python 2.7.13
See https://gist.github.com/e64d519a22342b30b7156496f0367b59 for a full test report.

**Comment by boegel** [comment]
@vanzod Using `Boost` provided via EasyBuild should be preferred whenever possible

**Comment by smoors** [comment]
Test report by @smoors
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
nic412 - Linux centos linux 7.5.1804, Intel(R) Xeon(R) Gold 6148 CPU @ 2.40GHz, Python 2.7.5
See https://gist.github.com/7cac3560b7a69b08d182f1de3c006e18 for a full test report.

**Comment by smoors** [comment]
Going in, thanks @murfreesboro!

**Pull request merged**
