### PR TITLE
{phys}[gompi/2022a] Rivet v3.1.7 w/ Python 3.10.4

### PR DESCRIPTION
**Pull request by APN-Pucky**
(created using `eb --new-pr`)

Requires:

- [ ] https://github.com/easybuilders/easybuild-easyconfigs/pull/17377
- [ ] https://github.com/easybuilders/easybuild-easyconfigs/pull/17367
- [ ] https://github.com/easybuilders/easybuild-easyconfigs/pull/17343

### CODE REVIEW

**Comment by verdurin** [comment]
@boegelbot please test @ jsc-zen2

**Comment by verdurin** [comment]
Test report by @verdurin
**SUCCESS**
Build succeeded for 2 out of 2 (1 easyconfigs in total)
easybuild-c7.novalocal - Linux CentOS Linux 7.9.2009, x86_64, Intel Xeon Processor (Skylake, IBRS), Python 3.6.8
See https://gist.github.com/eded4da2c287104a4dd9ab6a392e382b for a full test report.

**Review by verdurin — APPROVED** [review]
Looks fine.

**Comment by verdurin** [comment]
Going in, thanks @APN-Pucky!

**Comment by APN-Pucky** [comment]
Thanks for this and its dependencies!

**Pull request merged**
