### PR TITLE
{lang}[system/system] Java v21.0.2

### PR DESCRIPTION
**Pull request by Turakar**
Like #19709

### CODE REVIEW

**Comment by jfgrimm** [comment]
@boegelbot: please test @ generoso

**Comment by jfgrimm** [comment]
Test report by @jfgrimm
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
node115.viking2.yor.alces.network - Linux Rocky Linux 8.8, x86_64, AMD EPYC 7643 48-Core Processor, Python 3.6.8
See https://gist.github.com/jfgrimm/742d2045bf4651531869721f349e9c39 for a full test report.

**Comment by jfgrimm** [comment]
@boegelbot: please test @ jsc-zen3

**Comment by Turakar** [comment]
Anything blocking this?

**Comment by jfgrimm** [comment]
> Anything blocking this?

nope, meant to revisit this PR but just haven't had much time

**Comment by jfgrimm** [comment]
Going in, thanks @Turakar!

**Pull request merged**
