### PR TITLE
{bio,data}[foss/2023a] OPERA-MS v0.9.0-20240703, Statistics-R v0.34

### PR DESCRIPTION
**Pull request by pavelToman**
(created using `eb --new-pr`)
resolves https://github.com/vscentrum/vsc-software-stack/issues/443

### CODE REVIEW

**Comment by pavelToman** [comment]
@boegelbot please test @ generoso

**Comment by pavelToman** [comment]
@boegelbot please test @ jsc-zen3

**Comment by pavelToman** [comment]
@boegelbot please test @ jsc-zen3

**Comment by pavelToman** [comment]
Tests failed on the same step either on `shinx` and `skitty`

**Comment by laraPPr** [comment]
Test report by @laraPPr
**FAILED**
Build succeeded for 1 out of 2 (2 easyconfigs in total)
node3116.skitty.os - Linux RHEL 9.4, x86_64, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz, Python 3.11.3
See https://gist.github.com/laraPPr/71c147dd92f1e0194ac8a6eea323866d for a full test report.

**Comment by laraPPr** [comment]
Test report by @laraPPr
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in total)
node4004.donphan.os - Linux RHEL 8.8, x86_64, Intel(R) Xeon(R) Gold 6240 CPU @ 2.60GHz, 1 x NVIDIA NVIDIA A2, 545.23.08, Python 3.11.3
See https://gist.github.com/laraPPr/65af6d7e944236898cd20bcb00327fc3 for a full test report.

**Comment by pavelToman** [comment]
The error: `error while loading shared libraries: libncurses.so.5: cannot open shared object file: No such file or directory`

**Comment by laraPPr** [comment]
Than it is probably something R-PATH related as on shinx and skittty that is enabled. I had the same for https://github.com/easybuilders/easybuild-easyconfigs/pull/21756.

**Comment by laraPPr** [comment]
Ah skitty (and probably shinx as well) only libncurses.so.6 is their. This might also be the case on JSC so than you are missing a dependecy

**Comment by pavelToman** [comment]
Yes, on donphan there is ncurses-5.9 but not on shinx, there is onli v6. I tried to add `('ncurses', '5.9', '', SYSTEM)` as a dependency but it can not be build on shinx - failed on make step

**Comment by pavelToman** [comment]
ncurses problem should be fixed by adding SAMtools as a dependency

**Comment by pavelToman** [comment]
@boegelbot please test @ jsc-zen3

**Comment by pavelToman** [comment]
@boegelbot please test @ generoso

**Comment by verdurin** [comment]
Test report by @verdurin
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in total)
easybuild-el8.cloud.in.bmrc.ox.ac.uk - Linux Rocky Linux 8.10, x86_64, Intel Xeon Processor (Skylake, IBRS), Python 3.6.8
See https://gist.github.com/verdurin/cb8d81d11b57f12414e3b39526c65076 for a full test report.

**Review by verdurin — APPROVED** [review]
Looks fine.

**Comment by verdurin** [comment]
Going in, thanks @pavelToman!

**Pull request merged**
