### PR TITLE
Fix Racon-1.4.7-gcccuda-2019b.eb

### PR DESCRIPTION
**Pull request by Flamefire**
https://github.com/clara-genomics/ClaraGenomicsAnalysis Repo was renamed to https://github.com/clara-parabricks/GenomeWorks making checksum and source move fail

Move to same approach as pytorch

### CODE REVIEW

**Comment by Flamefire** [comment]
Test report by @Flamefire
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
taurusi6607.taurus.hrsk.tu-dresden.de - Linux RHEL 7.9, x86_64, Intel(R) Xeon(R) CPU E5-2680 v3 @ 2.50GHz (haswell), Python 2.7.5
See https://gist.github.com/89cb28ef617df9e8c2d1ac8615a612a2 for a full test report.

**Review by Micket — APPROVED** [review]
lgtm

**Comment by Micket** [comment]
Test report by @Micket
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
alvis-c1 - Linux centos linux 7.9.2009, x86_64, Intel Xeon Processor (Skylake), Python 3.6.8
See https://gist.github.com/eafb9aa825c05078e1f5687cb29666e8 for a full test report.

**Comment by Micket** [comment]
Going in, thanks @Flamefire!

**Pull request merged**
