### PR TITLE
remove trailing whitespace from easyconfigs

### PR DESCRIPTION
**Pull request by Flamefire**
Same as the long-standing PR https://github.com/easybuilders/easybuild-easyconfigs/pull/11148 but targetting 5.x

Note that `git diff 5.0.x --ignore-space-at-eol` turns up empty

### CODE REVIEW

**Review by Micket — DISMISSED** [review]
lgtm

**Comment by Flamefire** [comment]
Reminder that this is still open and a bit annoying to keep fixing for new ECs

**Comment by Flamefire** [comment]
@Micket ready :)

**Review by Micket — APPROVED** [review]
lgtm

**Pull request merged**
