### PR TITLE
{lib}[foss/2018b] future v0.16.0 w/ Python 2.7.15

### PR DESCRIPTION
**Pull request by smoors**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by boegel** [comment]
@smoors What do you need this for exactly? It's a bit strange to have this stand-alone I think...

**Comment by smoors** [comment]
@boegel its needed for OptiType (coming up in a bit). I agree, it would probably sit better in the default Python module, but a different version of the `future` module was already present (contributed by you :) :) :)

**Comment by boegel** [comment]
@smoors Is `OptiType` a Python package? If so, you could make it a `Bundle` easyconfig?

If not, then a separate easyconfig to include as a dep or including it in the `Python` easyconfig is the only way...

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
gligar03.gligar.os - Linux centos linux 7.5.1804, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.7.5
See https://gist.github.com/ea3b8ae72b77a045c0db54e8275ef4a8 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
node3115.skitty.os - Linux centos linux 7.5.1804, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz, Python 2.7.5
See https://gist.github.com/115710b1a7e8607a6dbeae5241152790 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
node2602.swalot.os - Linux centos linux 7.5.1804, Intel(R) Xeon(R) CPU E5-2660 v3 @ 2.60GHz, Python 2.7.5
See https://gist.github.com/1ad836a8289ba6a70ec9c4880916ab25 for a full test report.

**Comment by boegel** [comment]
based on #6924, it's the latter, so let's get this merged, not sure including `future` in the `Python` easyconfig is a good way forward...

**Comment by boegel** [comment]
Going in, thanks @smoors!

**Pull request merged**
