### PR TITLE
{lang}[GCC/11.3.0] CUDA-Samples v11.8, CUDA-Samples v12.2 w/ CUDA 11.7.0, CUDA 12.2.0

### PR DESCRIPTION
**Pull request by casparvl**
(created using `eb --new-pr`)

Replaces https://github.com/easybuilders/easybuild-easyconfigs/pull/18395 and updates existing easyconfigs.

Depends on:
- https://github.com/easybuilders/easybuild-framework/pull/4583

### CODE REVIEW

**Comment by casparvl** [comment]
Test report by @casparvl
**SUCCESS**
Build succeeded for 5 out of 5 (5 easyconfigs in total)
gcn6.local.snellius.surf.nl - Linux RHEL 8.6, x86_64, Intel(R) Xeon(R) Platinum 8360Y CPU @ 2.40GHz, 4 x NVIDIA NVIDIA A100-SXM4-40GB, 545.23.08, Python 3.6.8
See https://gist.github.com/casparvl/d4a548690bcbe8e0988896868a587037 for a full test report.

**Comment by casparvl** [comment]
Test report by @casparvl
**SUCCESS**
Build succeeded for 5 out of 5 (5 easyconfigs in total)
gcn6.local.snellius.surf.nl - Linux RHEL 8.6, x86_64, Intel(R) Xeon(R) Platinum 8360Y CPU @ 2.40GHz, 4 x NVIDIA NVIDIA A100-SXM4-40GB, 545.23.08, Python 3.6.8
See https://gist.github.com/casparvl/48348677eda8e7a162cc6f2af1c1554b for a full test report.

**Comment by casparvl** [comment]
Building with the bots will probably fail, just as it did in https://github.com/easybuilders/easybuild-easyconfigs/pull/18395 , but let's see. I think that failure was maybe due to too old CUDA CC? Let's see...

**Comment by casparvl** [comment]
@boegelbot please test @ generoso
EB_ARGS="--cuda-compute-capabilities=8.0"

**Comment by casparvl** [comment]
@boegelbot please test  @ generoso
EB_ARGS="--cuda-compute-capabilities=8.0 --force-download"

**Comment by casparvl** [comment]
@boegelbot please test @ jsc-zen4
EB_ARGS="--cuda-compute-capabilities=8.0 --force-download"

**Review by verdurin — APPROVED** [review]
Looks fine.

**Comment by verdurin** [comment]
Going in, thanks @casparvl!

**Pull request merged**
