### PR TITLE
{bio}[foss/2020a] WisecondorX v1.1.6 w/ Python 3.8.2

### PR DESCRIPTION
**Pull request by boegel**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by boegel** [comment]
@boegelbot please test @ generoso

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
node3125.skitty.os - Linux centos linux 7.8.2003, x86_64, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz, Python 3.6.8
See https://gist.github.com/b4f4d8c5613865abaa032e5e1c435eb8 for a full test report.

**Comment by smoors** [comment]
@boegel generoso says `scikit-learn 0.23.1 requires threadpoolctl, which is not installed`
you probably need to reinstall scikit-learn with the updated easyconfig?

**Comment by smoors** [comment]
Test report by @smoors
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
node376.hydra.os - Linux centos linux 7.7.1908, x86_64, Intel(R) Xeon(R) Gold 6148 CPU @ 2.40GHz (skylake_avx512), Python 2.7.5
See https://gist.github.com/959db0be5cd48f62b14abdad07b638f5 for a full test report.

**Review by smoors — APPROVED** [review]
lgtm

**Comment by boegel** [comment]
@smoors done!

@boegelbot please test @ generoso

**Comment by smoors** [comment]
Going in, thanks @boegel!

**Pull request merged**
