### PR TITLE
{math}[intel/2022a] sympy v1.11.1, gmpy2 v2.1.5 w/ Python 3.10.4

### PR DESCRIPTION
**Pull request by boegel**
(created using `eb --new-pr`)

* requires that `numexpr` in `SciPy-bundle/2022.05-intel-2022a` is rebuilt with https://github.com/easybuilders/easybuild-easyblocks/pull/2897

### CODE REVIEW

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in total)
node3104.skitty.os - Linux RHEL 8.6, x86_64, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz (skylake_avx512), Python 3.6.8
See https://gist.github.com/13149420eda9629a2c0644068a38be3c for a full test report.

**Comment by boegel** [comment]
I've reinstalled the `numexpr` in both `SciPy-bundle/2021.10-intel-2021b` and `SciPy-bundle/2022.05-intel-2022a`, on both `generoso` and `jsc-zen2`, so tests should pass for this PR now...

**Comment by boegel** [comment]
@boegelbot please test @ jsc-zen2

**Comment by verdurin** [comment]
Test report by @verdurin
**SUCCESS**
Build succeeded for 3 out of 3 (2 easyconfigs in total)
easybuild-c7.novalocal - Linux CentOS Linux 7.9.2009, x86_64, Intel Xeon Processor (Skylake, IBRS), Python 3.6.8
See https://gist.github.com/acf24a313537d59bebacc724c0c7632b for a full test report.

**Review by verdurin — APPROVED** [review]
Looks fine.

**Comment by verdurin** [comment]
Going in, thanks @boegel!

**Pull request merged**
