### PR TITLE
{chem} [intel/2017b] QuantumESPRESSO v6.2

### PR DESCRIPTION
**Pull request by Micket**
New config for 6.2. Dropped several previously used third party modules as they didn't immediately build cleanly, and the person requesting the installation didn't have any interest in them.

Downloads are problematic, and requires manual downloading to work due to easybuilders/easybuild#390

edit: depends on ~~#5496~~

### CODE REVIEW

**Comment by migueldiascosta** [comment]
@Micket this, with less changes from previsous easyconfigs, worked for me: [QuantumESPRESSO-6.2-intel-2017b.eb](https://github.com/migueldiascosta/my_eb_files/blob/master/intel-2017b/QuantumESPRESSO-6.2-intel-2017b.eb)

I didn't submit it because I didn't understand why I had to patch `FoX` and didn't see anyone in the pw-forum complaining: [QuantumESPRESSO-6.2_fox_libs.patch](https://github.com/migueldiascosta/my_eb_files/blob/master/intel-2017b/QuantumESPRESSO-6.2_fox_libs.patch)

Also had problems with `want` and `west` but the rest seems ok. 

Just in case it helps.

**Comment by Micket** [comment]
Hi @migueldiascosta 
I didn't have to do any patching for the FoX dependency, but I did create a separate config for it, see #5496 
which I use as a dependency. It seems your version has no explicit dependency, so I'm not sure how you manage this?

I also dropped Yambo when it didn't immediately build, as it seems this version (with it's patch) is getting fairly old. Our users also didn't need it.

**Comment by migueldiascosta** [comment]
@Micket they bundled it in qe-6.2/archive/fox.tgz (so it's even stranger that I had to patch it), but if as an external dependency works, I suppose that's better

**Comment by boegel** [comment]
Test report by @boegel
**FAILED**
Build succeeded for 0 out of 1 (1 easyconfigs in this PR)
node2060.delcatty.os - Linux centos linux 7.4.1708, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.7.5
See https://gist.github.com/b59d7a5d88d766537cee021819009122 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**FAILED**
Build succeeded for 0 out of 1 (1 easyconfigs in this PR)
node2554.golett.os - Linux centos linux 7.4.1708, Intel(R) Xeon(R) CPU E5-2680 v3 @ 2.50GHz, Python 2.7.5
See https://gist.github.com/668b39793033ef9d0486d3acdc1129d4 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
node2560.golett.os - Linux centos linux 7.4.1708, Intel(R) Xeon(R) CPU E5-2680 v3 @ 2.50GHz, Python 2.7.5
See https://gist.github.com/fc0bd07b120be952c0d38154219acc3e for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
node2044.delcatty.os - Linux centos linux 7.4.1708, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.7.5
See https://gist.github.com/da5e5e207131f5386b76903691aef7a1 for a full test report.

**Comment by migueldiascosta** [comment]
@Micket, @boegel if `FoX` is to be used as an easybuild dependency, wouldn't it be cleaner to link (in the `qe` easyblock?) `$TOPDIR/FoX` to `$EBROOTFOX`, in order to prevent the build triggered by this test in the [extlibs_makefile](https://github.com/QEF/q-e/blob/0e436e24d4338ddccb4904358d6a10ae20c52d05/install/extlibs_makefile#L79)?

For me, the internal `FoX` build fails if unpatched, and later the easybuild `FoX` is picked up, but if the internal succeeds I don't know which would be used. The link would solve this.

**Comment by Micket** [comment]
@migueldiascosta I never actually realized that QE tried to bundle FoX (I dislike when software does this), but your solution would only risk making it worse; the libfox target should never even be called by QE.

I haven't had time to try out a new build yet, but I think it might work just to make the internal libfox target a no-op:
```diff
--- Makefile.orig       2018-01-03 16:24:07.174670644 +0100
+++ Makefile    2018-01-03 16:24:44.492428006 +0100
@@ -204,7 +204,7 @@
 libiotk: touch-dummy
        cd install ; $(MAKE) -f extlibs_makefile $@
 libfox: touch-dummy
-       cd install ; $(MAKE) -f extlibs_makefile $@
+       echo "External module used"
 
 # In case of trouble with iotk and compilers, add
 # FFLAGS="$(FFLAGS_NOOPT)" after $(MFLAGS)
```

**Comment by migueldiascosta** [comment]
@Micket sure - note that `$(TOPDIR)/FoX` appears in other places, although as far as I can see only in `-I` and `-L` flags, so it should be ok

still, shouldn't disabling the `libfox` target be done in the easyblock, using `get_software_root('FoX')` to check if the external module is present?

**Comment by Micket** [comment]
@migueldiascosta The FoX module sets the appropriate environment variables, so there is no need to add any -L or -I flags at all.
Preventing the build of the internal FoX, leaving QE to add the (then) dead -I and -L flags should still work, as would removing those flags all together. 

Best would be if QE exposed a flag to disable to internal FoX trivially, or better yet, just stop bundling other software into their own already convoluted build.
But until then, patching out the FoX build target (and it's flags, if we want) in the block would probably be a good idea.

**Comment by migueldiascosta** [comment]
@Micket regarding the flags, yes, that's what I meant with "should be ok" :)

regarding what QE should do, I tend to agree, but that's at least outside the scope of this PR, even though easybuild(ers) can (and do) exert some pressure for better practices on upstream projects

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
node2441.golett.os - Linux centos linux 7.4.1708, Intel(R) Xeon(R) CPU E5-2680 v3 @ 2.50GHz, Python 2.7.5
See https://gist.github.com/0f82a5cd67497ea5aaaefc621ee47ee7 for a full test report.

**Comment by boegel** [comment]
Tested on top of https://github.com/easybuilders/easybuild-easyblocks/pull/1333, so both that and this PR look good to go.

Thanks for your efforts @Micket and @migueldiascosta!

**Comment by boegel** [comment]
Going in, thanks @Micket!

**Pull request merged**
