### PR TITLE
fix build problems with make 4.2.1 on RHEL8

### PR DESCRIPTION
**Pull request by hajgato**
edit (by @boegel): this fixes the following installation failure:

```
glob/libglob.a(glob.o):glob.c:function glob_in_dir: error: undefined reference to '__alloca'
```

### CODE REVIEW

**Comment by boegel** [comment]
@boegelbot please test @ generoso

**Review by boegel — APPROVED** [review]
lgtm

@hajgato Maybe include a reference to the link that helped you pinpoint the cause of this problem?

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 4 out of 4 (4 easyconfigs in this PR)
node2412.golett.os - Linux centos linux 7.8.2003, x86_64, Intel(R) Xeon(R) CPU E5-2680 v3 @ 2.50GHz (haswell), Python 2.7.5
See https://gist.github.com/1f57f5ab205f0619347de900c9293515 for a full test report.

**Comment by boegel** [comment]
Going in, thanks @hajgato!

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 20 out of 20 (4 easyconfigs in this PR)
node3404.kirlia.os - Linux centos linux 7.8.2003, x86_64, Intel(R) Xeon(R) Gold 6240 CPU @ 2.60GHz (cascadelake), Python 2.7.5
See https://gist.github.com/a8e8f3bad8f10756714fa4d37720aadd for a full test report.

**Comment by hajgato** [comment]
this still core dumps in real life situation.

**Comment by hajgato** [comment]
the real solution is here: https://github.com/easybuilders/easybuild-easyconfigs/pull/11371

**Pull request merged**
