### PR TITLE
add coloc, Exact, lmom, gld, and DescTools extensions to R-4.0.0

### PR DESCRIPTION
**Pull request by verdurin**
(created using `eb --new-pr`)
~~depends on #11586~~

### CODE REVIEW

**Comment by verdurin** [comment]
I will probably alter this one so that it spreads the changes over both `R` and `R-bundle-Bioconductor`.

**Comment by lexming** [comment]
@verdurin this cannot depend on https://github.com/easybuilders/easybuild-easyconfigs/pull/11586 because `R` does not depends on `R-bundle-Bioconductor`. Is it the other way around maybe?

**Comment by boegel** [comment]
@boegelbot please test @ generoso
EB_ARGS="--skip --rebuild"

**Review by boegel — APPROVED** [review]
lgtm (not sure why this is still WIP)

**Comment by verdurin** [comment]
@boegel yes, I think it's fine to merge now.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
node3575.doduo.os - Linux RHEL 8.2, x86_64, AMD EPYC 7552 48-Core Processor (zen2), Python 3.6.8
See https://gist.github.com/f3e5cf54bddab67ab24ff1c04e3564ca for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
node3401.kirlia.os - Linux centos linux 7.8.2003, x86_64, Intel(R) Xeon(R) Gold 6240 CPU @ 2.60GHz (cascadelake), Python 2.7.5
See https://gist.github.com/0d3b64c36d9533eec00a60015cb376ca for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
node3104.skitty.os - Linux centos linux 7.8.2003, x86_64, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz, Python 3.6.8
See https://gist.github.com/86d7a586b408c1b3d71baacf5810069f for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
node2407.golett.os - Linux centos linux 7.8.2003, x86_64, Intel(R) Xeon(R) CPU E5-2680 v3 @ 2.50GHz (haswell), Python 2.7.5
See https://gist.github.com/aca5ad870f72f4ad3073672466b015bc for a full test report.

**Comment by boegel** [comment]
Going in, thanks @verdurin!

**Pull request merged**
