### PR TITLE
{bio}[foss/2019a,intel/2019a] PheWAS v0.99.5-2

### PR DESCRIPTION
**Pull request by murfreesboro**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by murfreesboro** [comment]
Test report by @murfreesboro
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in this PR)
dev806.vampire - Linux centos linux 7.4.1708, Intel(R) Xeon(R) CPU           E5620  @ 2.40GHz, Python 2.7.5
See https://gist.github.com/3f93934ce02c9d0f280190842317e0ac for a full test report.

**Comment by vanzod** [comment]
@murfreesboro The following libraries are already included in the `R-3.6.0.*2019a` installations with a matching version, hence they can be removed from the easyconfig files in your PR:
```
'crayon', '1.3.4'
'cli', '1.1.0'
'utf8', '1.1.4'
'tibble', '2.1.3'
'ggrepel', '0.8.1'
'R6', '2.4.0'
'crosstalk', '1.0.0'
'htmltools', '0.3.6'
'htmlwidgets', '1.3'
```

For those ones instead the version is different than the one installed with `R`. 
Is there a specific compatibility reason for building them with a different version?
```
'Rcpp', '1.0.2'
'rlang', '0.4.0'
'pillar', '1.4.2'
'ggplot2', '3.2.1'
'DT', '0.8'
```

**Comment by murfreesboro** [comment]
OK I will take a look and modify.

**Comment by murfreesboro** [comment]
Test report by @murfreesboro
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in this PR)
dev806.vampire - Linux centos linux 7.4.1708, Intel(R) Xeon(R) CPU           E5620  @ 2.40GHz, Python 2.7.5
See https://gist.github.com/e2fdd8880934777461dbb222685db05d for a full test report.

**Comment by boegel** [comment]
@murfreesboro Ignore those failing tests, that obviously has nothing to do with your PR.

The tests got a bit stricter after collapsing the `4.x` branch into `develop`, in preparation for the upcoming EasyBuild v4.0.0 release, in particular w.r.t. the `'dummy` toolchain (should now be `system`), and the naming of local variables in easyconfig files (see https://easybuild.readthedocs.io/en/4.x/Easyconfig-files-local-variables.html).

A couple of easyconfigs in `develop` were not fixed yet to pass these tests, those were fixed in #8822, so I've re-triggered the tests for this PR.

**Comment by vanzod** [comment]
Test report by @vanzod
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in this PR)
cermis - Linux debian 9.9, Intel(R) Xeon(R) CPU           X5670  @ 2.93GHz, Python 2.7.13
See https://gist.github.com/1fc306eb7e4f64bf690cb1dd03993ad1 for a full test report.

**Comment by vanzod** [comment]
Going in, thanks @murfreesboro!

**Pull request merged**
