### PR TITLE
fix source URL in UDUNITS easyconfigs + add sources.easybuild.io fallback source URL

### LINKED ISSUE #11951: download of sources for UDUNITS v2.2.26 no longer works
https://www.unidata.ucar.edu/downloads/udunits/udunits-2.2.26.tar.gz yields a `403 Forbidden`...

### PR DESCRIPTION
**Pull request by boegel**
(created using `eb --new-pr`)

fixes #11951

### CODE REVIEW

**Comment by boegel** [comment]
@boegelbot please test @ generoso
EB_ARGS="--fetch --force-download --sourcepath /tmp/boegelbot/pr12156"

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 16 out of 16 (16 easyconfigs in total)
node2603.swalot.os - Linux centos linux 7.9.2009, x86_64, Intel(R) Xeon(R) CPU E5-2660 v3 @ 2.60GHz (haswell), Python 3.6.8
See https://gist.github.com/4b6c8d0d00a5bde969bc86c131e0c806 for a full test report.

**Review by branfosj — APPROVED** [review]
lgtm

**Comment by branfosj** [comment]
Test report by @branfosj
**SUCCESS**
Build succeeded for 16 out of 16 (16 easyconfigs in total)
bb-pg-login02.bear.cluster - Linux centos linux 7.8.2003, x86_64, Intel(R) Xeon(R) CPU E5-2620 v4 @ 2.10GHz (broadwell), Python 3.6.8
See https://gist.github.com/5c642940a147e6e2570badca5a80e7f5 for a full test report.

**Comment by branfosj** [comment]
Going in, thanks @boegel!

**Pull request merged**
