### PR TITLE
{bio,lang}[GCCcore/8.3.0] Longshot v0.4.1, Rust v1.42.0

### PR DESCRIPTION
**Pull request by boegel**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by verdurin** [comment]
Test report by @verdurin
**FAILED**
Build succeeded for 2 out of 3 (2 easyconfigs in this PR)
easybuild.novalocal - Linux centos linux 7.7.1908, Intel Xeon Processor (Skylake, IBRS), Python 2.7.5
See https://gist.github.com/32aa8b6ca92508cbc732295be7442783 for a full test report.

**Comment by verdurin** [comment]
```
running: "ar" "crs" "/eb/maint/build/Longshot/0.4.1/GCCcore-8.3.0/longshot-0.4.1/target/release/build/rust-htslib-a9951c9ef562d284/out/libwrapper.a" "/eb/maint/build/Longshot/0.4.1/GCCcore-8.3.0/longshot-0.4.1/target/release/build/rust-htslib-a9951c9ef562d284/out/wrapper.o"
exit code: 0
cargo:rustc-link-lib=static=wrapper
cargo:rustc-link-search=native=/eb/maint/build/Longshot/0.4.1/GCCcore-8.3.0/longshot-0.4.1/target/release/build/rust-htslib-a9951c9ef562d284/out
cargo:warning=couldn't execute `llvm-config --prefix` (exit code: exit code: 127)
cargo:warning=set the LLVM_CONFIG_PATH environment variable to a valid `llvm-config` executable

--- stderr
thread 'main' panicked at 'Unable to find libclang: "the `libclang` shared library at /eb/maint/software/Clang/9.0.1-GCCcore-8.3.0/lib/libclang.so.9 could not be opened: libncurses.so.6: cannot open shared object file: No such file or directory"', /home/software/.cargo/registry/src/github.com-1ecc6299db9ec823/bindgen-0.51.1/src/lib.rs:1731:13
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

 (at easybuild/tools/run.py:533 in parse_cmd_output)
```

**Comment by verdurin** [comment]
@boegel Any ideas on what's wrong here? Is it a local problem? Do I need to rebuild a dependency to pick up bugfixes?

**Comment by boegel** [comment]
@verdurin Are we missing an `ncurses` dep in `Clang`?

**Comment by boegel** [comment]
@verdurin The `ncurses` dep issue for `Clang` should be fixed with #11415, can you please revisit this after making sure `ncurses` is included as a dep for `Clang` on your test system?

**Comment by verdurin** [comment]
Test report by @verdurin
**SUCCESS**
Build succeeded for 1 out of 1 (2 easyconfigs in this PR)
easybuild.novalocal - Linux centos linux 7.8.2003, x86_64, Intel Xeon Processor (Skylake, IBRS), Python 2.7.5
See https://gist.github.com/55889521dd52efae484db4034b91c755 for a full test report.

**Review by verdurin — APPROVED** [review]
Looks fine.

**Comment by verdurin** [comment]
Going in, thanks @boegel!

**Pull request merged**
