### PR TITLE
{chem}[intel/2022a] xtb v6.6.0

### PR DESCRIPTION
**Pull request by sassy-crick**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by sassy-crick** [comment]
I removed `xtb-6.6.1-intel-2022b.eb` as here I was not relying on the automated download of the dependencies but explicitly build them. However, for the then required `tblite-0.3.0-intel-2022b.eb` a number of test jobs failed with seg-faults. 
For the `xtb-6.6.1-intel-2022a.eb` I did not do that as the `foss-2022a` one did not explicitly use these dependencies. 
It might be a good idea when going forward to actually use dependencies and run the test jobs for them, maybe.

**Comment by sassy-crick** [comment]
@boegelbot please test @ generoso

**Comment by casparvl** [comment]
Test report by @casparvl
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
tcn1.local.snellius.surf.nl - Linux RHEL 8.6, x86_64, AMD EPYC 7H12 64-Core Processor, Python 3.6.8
See https://gist.github.com/casparvl/937362131a8efbde4ffd2a19505c84aa for a full test report.

**Review by casparvl — APPROVED** [review]
Lgtm!

**Comment by casparvl** [comment]
Going in, thanks @sassy-crick!

**Pull request merged**
