### PR TITLE
add missing zstd dep to Boost

### PR DESCRIPTION
**Pull request by smoors**
(created using `eb --new-pr`)

fixes linking errors such as seen for openMVS:
```
../../lib/libMVS.a(Scene.cpp.o):Scene.cpp:function boost::detail::sp_counted_impl_p<boost::iostreams::symmetric_filter<boost::iostreams::detail::zstd_decompressor_impl<std::allocator<char> >, std::allocator<char> >::impl>::dispose(): error: undefined reference to 'boost::iostreams::detail::zstd_base::reset(bool, bool)'
```

### CODE REVIEW

**Comment by SebastianAchilles** [comment]
@boegelbot please test @ jsc-zen2
EB_ARGS="--filter-ecs=*2019*,*iimpi-2020a*,*iccifort-2020.4.304*,*gompic-2020a* --installpath /tmp/$USER/pr17482"

**Comment by SebastianAchilles** [comment]
@boegelbot please test @ generoso
EB_ARGS="--installpath /tmp/$USER/pr17482"

**Comment by SebastianAchilles** [comment]
Test report by @sebastianachilles
**SUCCESS**
Build succeeded for 7 out of 7 (7 easyconfigs in total)
zen2-ubuntu-2210 - Linux Ubuntu 22.10 (Kinetic Kudu), x86_64, AMD EPYC 7452 32-Core Processor (zen2), Python 3.10.7
See https://gist.github.com/0d2aa0c8cc9c761c9952ce2493da088e for a full test report.

**Comment by SebastianAchilles** [comment]
Test report by @sebastianachilles
**SUCCESS**
Build succeeded for 7 out of 7 (7 easyconfigs in total)
bwd-rockylinux-91 - Linux Rocky Linux 9.1 (Blue Onyx), x86_64, Intel(R) Core(TM) i7-6900K CPU @ 3.20GHz (broadwell), Python 3.9.14
See https://gist.github.com/30986a6b55589d654fbd5d247d5148c4 for a full test report.

**Comment by SebastianAchilles** [comment]
Test report by @sebastianachilles
**SUCCESS**
Build succeeded for 7 out of 7 (7 easyconfigs in total)
skl-opensuse-154 - Linux openSUSE Leap 15.4, x86_64, Intel(R) Core(TM) i7-8700 CPU @ 3.20GHz (skylake), Python 3.6.15
See https://gist.github.com/cd9191ce19d45abcb1c2a1bfa21f3bee for a full test report.

**Review by SebastianAchilles — APPROVED** [review]
lgtm

**Comment by SebastianAchilles** [comment]
Going in, thanks @smoors!

**Comment by boegel** [comment]
@boegelbot please test @ generoso

**Pull request merged**
