### PR TITLE
{phys}[foss/2022b] mumott v2.1

### PR DESCRIPTION
**Pull request by lcniel**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by lcniel** [comment]
Test report by @lcniel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
vera54-1 - Linux Rocky Linux 8.9, x86_64, Intel(R) Xeon(R) Gold 6130 CPU @ 2.10GHz, 1 x NVIDIA Tesla T4, 550.54.14, Python 3.6.8
See https://gist.github.com/lcniel/99aa0e45ee471a2e267447a439ba6d49 for a full test report.

**Comment by lcniel** [comment]
Full disclosure: I am (or was) the principal developer of this package.

GPU support is entirely via numba-CUDA, so it should be installation-independent.

There is a big test suite, but one of the GPU tests would need to be excluded (`test_cupy`, which is more for checking that the CI is future-proofed). One could also run only the tests in `cpu_tests` or `cpu_tests/unit_tests`. However, this would require the use of `pytest`, not sure if you typically do this.

**Comment by lcniel** [comment]
Test report by @lcniel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
vera-r07-01 - Linux Rocky Linux 8.9, x86_64, Intel(R) Xeon(R) Gold 6338 CPU @ 2.00GHz, 1 x NVIDIA NVIDIA A40, 550.54.14, Python 3.6.8
See https://gist.github.com/lcniel/addbcfde4b732eada0f55954bfb07ce9 for a full test report.

**Comment by lcniel** [comment]
Test report by @lcniel
**SUCCESS**
Build succeeded for 3 out of 3 (1 easyconfigs in total)
vera40-1 - Linux Rocky Linux 8.9, x86_64, Intel(R) Xeon(R) Gold 6130 CPU @ 2.10GHz, 1 x NVIDIA Tesla T4, 550.54.14, Python 3.6.8
See https://gist.github.com/lcniel/0616d34a5f27bc7e229bf74ceec2c8b5 for a full test report.

**Comment by lcniel** [comment]
Also tested that it works when loaded with JupyterLab 4.0.3 and CUDA 12.4.0. No real reason to make a separate CUDA version since it all goes via Numba.

**Review by Micket — APPROVED** [review]
lgtm

**Comment by Micket** [comment]
@boegelbot please test @ generoso

**Comment by Micket** [comment]
@boegelbot please test @ jsc-zen3

**Comment by Micket** [comment]
@boegelbot please test @ jsc-zen3

**Comment by zao** [comment]
Test report by @zao
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
eb-mix.zao.se - Linux Ubuntu 24.04 LTS (Noble Numbat), x86_64, AMD Ryzen 9 3900X 12-Core Processor (zen2), Python 3.12.3
See https://gist.github.com/zao/fbd700a1a9d7bb0081e53c650a6416f7 for a full test report.

**Comment by verdurin** [comment]
Going in, thanks @lcniel!

**Pull request merged**
