### PR TITLE
{vis}[foss/2017b,intel/2017b] ciftify v2.3.2.post1 w/ Python 3.6.3

### PR DESCRIPTION
**Pull request by vanzod**
Depends on ~#8450~ (Nilearn)

### CODE REVIEW

**Comment by vanzod** [comment]
Test report by @vanzod
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in this PR)
cermis - Linux debian 9.9, Intel(R) Xeon(R) CPU           X5670  @ 2.93GHz, Python 2.7.13
See https://gist.github.com/68aaf33272d5d5c2be1a22964c89e469 for a full test report.

**Comment by smoors** [comment]
closing-reopening to trigger travis

**Comment by smoors** [comment]
Test report by @smoors
**FAILED**
Build succeeded for 8 out of 10 (2 easyconfigs in this PR)
nic406 - Linux centos linux 7.5.1804, Intel(R) Xeon(R) Gold 6148 CPU @ 2.40GHz, Python 2.7.5
See https://gist.github.com/2b1623b19a8bdbfaddac4045d5c5e8f6 for a full test report.

**Comment by vanzod** [comment]
@smoors It seems a more safe approach to just go ahead and add `m2r` than assuming `utf-8` encoding and patching `setup.py`.

**Comment by vanzod** [comment]
Test report by @vanzod
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in this PR)
cermis - Linux debian 9.9, Intel(R) Xeon(R) CPU           X5670  @ 2.93GHz, Python 2.7.13
See https://gist.github.com/8de68cef7b504919f588cc33d409e3b5 for a full test report.

**Comment by smoors** [comment]
Test report by @smoors
**SUCCESS**
Build succeeded for 10 out of 10 (2 easyconfigs in this PR)
nic400 - Linux centos linux 7.5.1804, Intel(R) Xeon(R) Gold 6148 CPU @ 2.40GHz, Python 2.7.5
See https://gist.github.com/17ca15b107f040414e986f3d82e22668 for a full test report.

**Comment by smoors** [comment]
Going in, thanks @vanzod!

**Pull request merged**
