### PR TITLE
{tools}[system/system] VTune v2025.0.0

### PR DESCRIPTION
**Pull request by Thyre**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by Thyre** [comment]
@boegelbot please test @ jsc-zen3

**Review by Micket — APPROVED** [review]
lgtm

**Comment by Micket** [comment]
@boegelbot please test @ generoso

**Comment by Micket** [comment]
Test report by @Micket
**FAILED**
Build succeeded for 0 out of 1 (1 easyconfigs in total)
alvis-skylake-build - Linux Rocky Linux 8.9, x86_64, Intel Xeon Processor (Skylake, IBRS, no TSX), Python 3.6.8
See https://gist.github.com/Micket/0a751283bcf0d2a65a0064ff57479f66 for a full test report.

**Comment by Micket** [comment]
Reminder for everyone else: this also needs `--include-easyblocks-from-pr 3465`

**Comment by Micket** [comment]
Test report by @Micket
Using easyblocks from PR(s) https://github.com/easybuilders/easybuild-easyblocks/pull/3465
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
alvis-skylake-build - Linux Rocky Linux 8.9, x86_64, Intel Xeon Processor (Skylake, IBRS, no TSX), Python 3.6.8
See https://gist.github.com/Micket/255ae692d37e1ea5c3e9e17ebe22cced for a full test report.

**Pull request merged**
