### PR TITLE
{bio}[GCC/10.2.0] segemehl v0.3.4

### PR DESCRIPTION
**Pull request by boegel**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by boegel** [comment]
@boegelbot please test @ generoso

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
node2606.swalot.os - Linux centos linux 7.9.2009, x86_64, Intel(R) Xeon(R) CPU E5-2660 v3 @ 2.60GHz (haswell), Python 3.6.8
See https://gist.github.com/07345fe58a7e15e11127d8b8d023f9b1 for a full test report.

**Comment by verdurin** [comment]
Test report by @verdurin
**FAILED**
Build succeeded for 0 out of 1 (1 easyconfigs in total)
nuc.lan - Linux Fedora 33, x86_64, Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz, Python 3.9.2
See https://gist.github.com/5bad928b3b7ee21613ba7453049660e3 for a full test report.

**Comment by verdurin** [comment]
Various problems here on Fedora 32:

These ones appear throughout:
```
gcc -O2 -ftree-vectorize -march=native -fno-math-errno -Wall -pedantic -std=c99 -g -O3 -DSORTEDUNMAPPED -D_LARGEFILE_
SOURCE -D_FILE_OFFSET_BITS=64 -DDBGNFO -DSHOWALIGN -DDBGLEVEL=0 -DPROGNFO -Ilibs -Ilibs/sufarray -Isamtools `pkg-conf
ig --cflags htslib` -I include -c -o build/multicharseq.o libs/multicharseq.c
rpm: /mnt/ds918plus/eb/nuc-fedora32/software/XZ/5.2.5-GCCcore-10.2.0/lib/liblzma.so.5: version `XZ_5.2' not found (re
quired by /lib64/librpmio.so.9)
/usr/bin/pkg-config: line 8: /usr/bin/-pkg-config: No such file or directory
```
then this error at the end:
```
inking haarz
gcc build/md5.o build/vstack.o build/queryalign.o build/annotation.o build/biofiles.o build/bitVector.o build/locus.o build/seqclip.o build/debug.o build/merge.o build/kdseed.o build/stack.o build/bamio.o build/vqueue.o build/aluruSort.o build/segemehl_helper.o build/bitArray.o build/samheader.o build/sw.o build/fileio.o build/kdchain.o build/vtprogressbar.o build/karlin.o build/bgzip.o build/gzidx.o build/portable_endian.o build/container.o build/bedfiles.o build/memory.o build/junctions.o build/pigeon.o build/radixsort.o build/sort.o build/match.o build/charsequence.o build/stringutils.o build/samio.o build/manout.o build/brendel.o build/info.o build/gzip.o build/sufarray.o build/fileBins.o build/splitalign.o build/iupac.o build/bitvectoralg.o build/intervaltree.o build/manopt.o build/mathematics.o build/multicharseq.o build/filebuffer.o build/mapfrag.o build/mappingqual.o build/nw.o build/alignment.o build/matealign.o build/haarz.o -o ./haarz.x -lm -lpthread -lz -lncurses -L libs -lform -lmenu -L/usr/local/lib/ `pkg-config --libs htslib` "-Wl,-rpath,`pkg-config --variable=libdir htslib`" -L/mnt/ds918plus/eb/nuc-fedora32/software/zlib/1.2.11-GCCcore-10.2.0/lib64 -L/mnt/ds918plus/eb/nuc-fedora32/software/zlib/1.2.11-GCCcore-10.2.0/lib -L/mnt/ds918plus/eb/nuc-fedora32/software/ncurses/6.2-GCCcore-10.2.0/lib64 -L/mnt/ds918plus/eb/nuc-fedora32/software/ncurses/6.2-GCCcore-10.2.0/lib -L/mnt/ds918plus/eb/nuc-fedora32/software/HTSlib/1.11-GCC-10.2.0/lib64 -L/mnt/ds918plus/eb/nuc-fedora32/software/HTSlib/1.11-GCC-10.2.0/lib -L/mnt/ds918plus/eb/nuc-fedora32/software/GCCcore/10.2.0/lib64 -L/mnt/ds918plus/eb/nuc-fedora32/software/GCCcore/10.2.0/lib
rpm: /mnt/ds918plus/eb/nuc-fedora32/software/XZ/5.2.5-GCCcore-10.2.0/lib/liblzma.so.5: version `XZ_5.2' not found (required by /lib64/librpmio.so.9)
rpm: /mnt/ds918plus/eb/nuc-fedora32/software/XZ/5.2.5-GCCcore-10.2.0/lib/liblzma.so.5: version `XZ_5.2' not found (required by /lib64/librpmio.so.9)
/usr/bin/pkg-config: line 8: /usr/bin/-pkg-config: No such file or directory
/usr/bin/pkg-config: line 8: /usr/bin/-pkg-config: No such file or directory
rpm: /mnt/ds918plus/eb/nuc-fedora32/software/XZ/5.2.5-GCCcore-10.2.0/lib/liblzma.so.5: version `XZ_5.2' not found (required by /lib64/librpmio.so.9)
rpm: /mnt/ds918plus/eb/nuc-fedora32/software/XZ/5.2.5-GCCcore-10.2.0/lib/liblzma.so.5: version `XZ_5.2' not found (required by /lib64/librpmio.so.9)
/usr/bin/pkg-config: line 8: /usr/bin/-pkg-config: No such file or directory
/usr/bin/pkg-config: line 8: /usr/bin/-pkg-config: No such file or directory
libs/bamio.c:208: error: undefined reference to 'seq_nt16_str'
libs/bamio.c:208: error: undefined reference to 'seq_nt16_str'
libs/bamio.c:210: error: undefined reference to 'seq_nt16_str'
libs/bamio.c:210: error: undefined reference to 'seq_nt16_str'
libs/bamio.c:212: error: undefined reference to 'seq_nt16_str'
libs/bamio.c:212: error: undefined reference to 'seq_nt16_str'
libs/bamio.c:241: error: undefined reference to 'seq_nt16_table'
libs/bamio.c:241: error: undefined reference to 'seq_nt16_table'
libs/bamio.c:244: error: undefined reference to 'seq_nt16_table'
libs/bamio.c:244: error: undefined reference to 'seq_nt16_table'
libs/bamio.c:369: error: undefined reference to 'seq_nt16_str'
libs/bamio.c:369: error: undefined reference to 'seq_nt16_str'
libs/bamio.c:494: error: undefined reference to 'seq_nt16_table'
libs/bamio.c:494: error: undefined reference to 'seq_nt16_table'
libs/bamio.c:496: error: undefined reference to 'seq_nt16_table'
libs/bamio.c:496: error: undefined reference to 'seq_nt16_table'
/mnt/ds918plus/eb/nuc-fedora32/software/HTSlib/1.11-GCC-10.2.0/include/htslib/sam.h:1296: error: undefined reference 
to 'hts_itr_next'
/mnt/ds918plus/eb/nuc-fedora32/software/HTSlib/1.11-GCC-10.2.0/include/htslib/sam.h:1296: error: undefined reference 
to 'hts_itr_next'
/mnt/ds918plus/eb/nuc-fedora32/software/HTSlib/1.11-GCC-10.2.0/include/htslib/sam.h:1285: error: undefined reference 
to 'hts_log'
/mnt/ds918plus/eb/nuc-fedora32/software/HTSlib/1.11-GCC-10.2.0/include/htslib/sam.h:1285: error: undefined reference 
to 'hts_log'
/mnt/ds918plus/eb/nuc-fedora32/software/HTSlib/1.11-GCC-10.2.0/include/htslib/sam.h:1294: error: undefined reference 
to 'hts_itr_multi_next'
/mnt/ds918plus/eb/nuc-fedora32/software/HTSlib/1.11-GCC-10.2.0/include/htslib/sam.h:1294: error: undefined reference 
to 'hts_itr_multi_next'
/mnt/ds918plus/eb/nuc-fedora32/software/HTSlib/1.11-GCC-10.2.0/include/htslib/sam.h:1289: error: undefined reference 
to 'hts_log'
/mnt/ds918plus/eb/nuc-fedora32/software/HTSlib/1.11-GCC-10.2.0/include/htslib/sam.h:1289: error: undefined reference 
to 'hts_log'
libs/bamio.c:643: error: undefined reference to 'sam_format1'
libs/bamio.c:643: error: undefined reference to 'sam_format1'
libs/bamio.c:703: error: undefined reference to 'bam_aux_get'
libs/bamio.c:703: error: undefined reference to 'bam_aux_get'
libs/bamio.c:708: error: undefined reference to 'bam_aux2Z'
libs/bamio.c:708: error: undefined reference to 'bam_aux2Z'
libs/bamio.c:727: error: undefined reference to 'bam_cigar2rlen'
libs/bamio.c:727: error: undefined reference to 'bam_cigar2rlen'
libs/bamio.c:835: error: undefined reference to 'bam_aux_get'
libs/bamio.c:835: error: undefined reference to 'bam_aux_get'
libs/bamio.c:836: error: undefined reference to 'bam_aux2i'
libs/bamio.c:836: error: undefined reference to 'bam_aux2i'
libs/bamio.c:840: error: undefined reference to 'bam_aux_get'
libs/bamio.c:840: error: undefined reference to 'bam_aux_get'
libs/bamio.c:841: error: undefined reference to 'bam_aux_get'
libs/bamio.c:841: error: undefined reference to 'bam_aux_get'
libs/bamio.c:844: error: undefined reference to 'bam_aux2i'
libs/bamio.c:844: error: undefined reference to 'bam_aux2i'
libs/bamio.c:849: error: undefined reference to 'bam_aux2Z'
libs/bamio.c:849: error: undefined reference to 'bam_aux2Z'
libs/bamio.c:1017: error: undefined reference to 'sam_itr_queryi'
libs/bamio.c:1017: error: undefined reference to 'sam_itr_queryi'
libs/bamio.c:1027: error: undefined reference to 'faidx_fetch_seq'
libs/bamio.c:1027: error: undefined reference to 'faidx_fetch_seq'
libs/bamio.c:1047: error: undefined reference to 'hts_itr_destroy'
libs/bamio.c:1047: error: undefined reference to 'hts_itr_destroy'
libs/bamio.c:1078: error: undefined reference to 'sam_itr_queryi'
libs/bamio.c:1078: error: undefined reference to 'sam_itr_queryi'
libs/bamio.c:1083: error: undefined reference to 'faidx_fetch_seq'
libs/bamio.c:1083: error: undefined reference to 'faidx_fetch_seq'
libs/bamio.c:1091: error: undefined reference to 'hts_itr_destroy'
libs/bamio.c:1091: error: undefined reference to 'hts_itr_destroy'
libs/bamio.c:1104: error: undefined reference to 'hts_open'
libs/bamio.c:1104: error: undefined reference to 'hts_open'
libs/bamio.c:1110: error: undefined reference to 'sam_hdr_read'
libs/bamio.c:1110: error: undefined reference to 'sam_hdr_read'
libs/bamio.c:1114: error: undefined reference to 'sam_index_load'
libs/bamio.c:1114: error: undefined reference to 'sam_index_load'
libs/bamio.c:1120: error: undefined reference to 'fai_load'
libs/bamio.c:1120: error: undefined reference to 'fai_load'
libs/bamio.c:1132: error: undefined reference to 'fai_destroy'
libs/bamio.c:1132: error: undefined reference to 'fai_destroy'
/mnt/ds918plus/eb/nuc-fedora32/software/HTSlib/1.11-GCC-10.2.0/include/htslib/sam.h:391: error: undefined reference t
o 'sam_hdr_destroy'
/mnt/ds918plus/eb/nuc-fedora32/software/HTSlib/1.11-GCC-10.2.0/include/htslib/sam.h:391: error: undefined reference t
o 'sam_hdr_destroy'
libs/bamio.c:1134: error: undefined reference to 'hts_idx_destroy'
libs/bamio.c:1134: error: undefined reference to 'hts_idx_destroy'
libs/bamio.c:1157: error: undefined reference to 'sam_hdr_parse'
libs/bamio.c:1157: error: undefined reference to 'sam_hdr_parse'
libs/bamio.c:1180: error: undefined reference to 'bam_init1'
libs/bamio.c:1180: error: undefined reference to 'bam_init1'
libs/bamio.c:1183: error: undefined reference to 'ksprintf'
libs/bamio.c:1183: error: undefined reference to 'ksprintf'
libs/bamio.c:1187: error: undefined reference to 'ksprintf'
libs/bamio.c:1187: error: undefined reference to 'ksprintf'
libs/bamio.c:1192: error: undefined reference to 'ksprintf'
libs/bamio.c:1192: error: undefined reference to 'ksprintf'
libs/bamio.c:1196: error: undefined reference to 'ksprintf'
libs/bamio.c:1196: error: undefined reference to 'ksprintf'
libs/bamio.c:1200: error: undefined reference to 'sam_parse1'
libs/bamio.c:1200: error: undefined reference to 'sam_parse1'
libs/bamio.c:1229: error: undefined reference to 'sam_write1'
libs/bamio.c:1229: error: undefined reference to 'sam_write1'
libs/bamio.c:1254: error: undefined reference to 'hts_open'
libs/bamio.c:1254: error: undefined reference to 'hts_open'
libs/bamio.c:1258: error: undefined reference to 'hts_set_cache_size'
libs/bamio.c:1135: error: undefined reference to 'hts_close'
libs/bamio.c:1258: error: undefined reference to 'hts_set_cache_size'
libs/bamio.c:1237: error: undefined reference to 'bam_destroy1'
libs/bamio.c:1135: error: undefined reference to 'hts_close'
libs/bamio.c:1237: error: undefined reference to 'bam_destroy1'
libs/manout.c:701: error: undefined reference to 'sam_hdr_write'
libs/manout.c:709: error: undefined reference to 'sam_hdr_write'
libs/manout.c:701: error: undefined reference to 'sam_hdr_write'
libs/manout.c:841: error: undefined reference to 'hts_close'
/mnt/ds918plus/eb/nuc-fedora32/software/HTSlib/1.11-GCC-10.2.0/include/htslib/sam.h:391: error: undefined reference t
o 'sam_hdr_destroy'
libs/manout.c:709: error: undefined reference to 'sam_hdr_write'
libs/manout.c:841: error: undefined reference to 'hts_close'
/mnt/ds918plus/eb/nuc-fedora32/software/HTSlib/1.11-GCC-10.2.0/include/htslib/sam.h:391: error: undefined reference t
o 'sam_hdr_destroy'
collect2: error: ld returned 1 exit status
make: *** [Makefile:33: haarz] Error 1
make: *** Waiting for unfinished jobs....
```

**Comment by smoors** [comment]
@verdurin this seems to be an issue with your installation of `XZ/5.2.5-GCCcore-10.2.0`, which will need an update to  `XZ-5.2.2_compat-libs.patch`.

Can you check if your `rpm` is working when the XZ module is loaded?

**Comment by verdurin** [comment]
Test report by @verdurin
**FAILED**
Build succeeded for 0 out of 1 (1 easyconfigs in total)
nuc.lan - Linux Fedora 33, x86_64, Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz, Python 3.9.2
See https://gist.github.com/6a241420978aa15cb3cdc26c38813177 for a full test report.

**Comment by verdurin** [comment]
Test report by @verdurin
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
easybuild-c7.novalocal - Linux centos linux 7.9.2009, x86_64, Intel Xeon Processor (Skylake, IBRS), Python 3.6.8
See https://gist.github.com/7e3372ecc207b95423016e4a0e115a0c for a full test report.

**Comment by verdurin** [comment]
@smoors the `XZ` rebuild made no difference - it's a Fedora build node, so perhaps extra fixes would be needed.
Fine on `CentOS`, so I'm happy for this PR to be merged.

**Comment by boegel** [comment]
@verdurin Can you try again on Fedora now that I've included `pkg-config` as a build dep?

**Comment by boegel** [comment]
@boegelbot please test @ generoso

**Comment by verdurin** [comment]
Test report by @verdurin
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
nuc.lan - Linux Fedora 33, x86_64, Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz, Python 3.9.2
See https://gist.github.com/da9162fb820c8cb5111e61dae76fea1f for a full test report.

**Review by verdurin — APPROVED** [review]
Looks fine.

**Comment by verdurin** [comment]
Going in, thanks @boegel!

**Pull request merged**
