### PR TITLE
{devel}[GCCcore/10.3.0] Autotools v20210128

### PR DESCRIPTION
**Pull request by robert-mijakovic**
(created using `eb --new-pr`)
Depends on Autoconf and Automake (https://github.com/easybuilders/easybuild-easyconfigs/pull/12634, https://github.com/easybuilders/easybuild-easyconfigs/pull/12635).

### CODE REVIEW

**Comment by Micket** [comment]
@robert-mijakovic once we have Perl merged, could you please add Autoconf and Automake to this PR instead so that we can get it all merged quicker (since they all belong together anyway).

**Comment by robert-mijakovic** [comment]
> @robert-mijakovic once we have Perl merged, could you please add Autoconf and Automake to this PR instead so that we can get it all merged quicker (since they all belong together anyway).

Sure, I can.

**Comment by Micket** [comment]
@robert-mijakovic Please update this PR with your Autoconf and Automake now that Perl is merged.

**Comment by robert-mijakovic** [comment]
> @robert-mijakovic Please update this PR with your Autoconf and Automake now that Perl is merged.

Done!

**Review by boegel — APPROVED** [review]
lgtm

**Comment by boegel** [comment]
@boegelbot please test @ generoso

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 4 out of 4 (4 easyconfigs in total)
node3512.doduo.os - Linux RHEL 8.2, x86_64, AMD EPYC 7552 48-Core Processor (zen2), Python 3.6.8
See https://gist.github.com/05465cab61b9b681a0433ae27c2d4658 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 4 out of 4 (4 easyconfigs in total)
node3169.skitty.os - Linux centos linux 7.9.2009, x86_64, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz, Python 3.6.8
See https://gist.github.com/b9aaa5b8ceb1023b4ea477fe8ddfc365 for a full test report.

**Comment by boegel** [comment]
Going in, thanks @robert-mijakovic!

**Pull request merged**
