### PR TITLE
add Perl build dep for Autoconf/Automake using GCCcore/7.3.0 and GCCcore/8.2.0 toolchains

### LINKED ISSUE #1822: automake 1.15 build fails if PERL's `Thread::Queue` is not available
When trying to build `automake` (as a dependency to build `R` with the `foss-2015a` toolchain), I ran into an error stating that "help2man cannot run automake-1.15 --help".

It turned out that a previous "make bootstrap" phase had failed, because PERL module `Thread::Queue` was not installed on the system, and autoconf/autom4te depends on it.

### LINKED ISSUE #8704: Autoconf/2.69 requires perl-Data-Dumper
Just installed EasyBuild on a fresh CentOS 7.6 installation and tried to do some installation, but it failed at Autoconf-2.69-GCCcore-8.2.0.eb:

```
autom4te_perllibdir='..'/lib AUTOM4TE_CFG='../lib/autom4te.cfg'         ../bin/autom4te -B '..'/lib -B '..'/lib         --language M4sh --cache '' --melt ./autoconf.as -o autoconf.in
mv autoupdate.tmp autoupdate
Can't locate Data/Dumper.pm in @INC (@INC contains: ../lib /usr/local/lib64/perl5 /usr/local/share/perl5 /usr/lib64/perl5/vendor_perl /usr/share/perl5/vendor_perl /usr/lib64/perl5 /usr/share/perl5 .) at ../lib/Autom4te/C4che.pm line 33.
BEGIN failed--compilation aborted at ../lib/Autom4te/C4che.pm line 33.
```

Installing the yum package `perl-Data-Dumper` resolved it, so maybe this should be added as an osdependency?

### PR DESCRIPTION
**Pull request by boegel**
(created using `eb --new-pr`)

fixes #1822, fixes #8704

### CODE REVIEW

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 4 out of 4 (4 easyconfigs in this PR)
generoso - Linux centos linux 7.6.1810, Intel(R) Xeon(R) CPU E5-2660 v4 @ 2.00GHz, Python 3.6.8
See https://gist.github.com/4610a418296a83e6a99c71d49874d616 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 4 out of 4 (4 easyconfigs in this PR)
node2454.golett.os - Linux centos linux 7.7.1908, Intel(R) Xeon(R) CPU E5-2680 v3 @ 2.50GHz (haswell), Python 2.7.5
See https://gist.github.com/0a6e8854a90a751accac57eda3706771 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 4 out of 4 (4 easyconfigs in this PR)
node3126.skitty.os - Linux centos linux 7.7.1908, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz (skylake_avx512), Python 3.6.8
See https://gist.github.com/9fe4f345abb276b8b532d2e003889b06 for a full test report.

**Comment by verdurin** [comment]
Test report by @verdurin
**SUCCESS**
Build succeeded for 0 out of 0 (4 easyconfigs in this PR)
easybuild.novalocal - Linux centos linux 7.7.1908, Intel Xeon Processor (Skylake, IBRS), Python 2.7.5
See https://gist.github.com/daa73b02b26afa36e1e9175f6e388e00 for a full test report.

**Comment by verdurin** [comment]
Test report by @verdurin
**SUCCESS**
Build succeeded for 4 out of 4 (4 easyconfigs in this PR)
easybuild.novalocal - Linux centos linux 7.7.1908, Intel Xeon Processor (Skylake, IBRS), Python 2.7.5
See https://gist.github.com/1506d157a217c5e5bb0d2ed9d1dca1de for a full test report.

**Comment by boegel** [comment]
@verdurin Good to go now?

**Comment by verdurin** [comment]
Going in, thanks @boegel!

**Pull request merged**
