### PR TITLE
{bio}[foss/2022a] RFdiffusion v1.1.0, e3nn v0.3.3 w/ CUDA 11.7.0

### PR DESCRIPTION
**Pull request by VRehnberg**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by VRehnberg** [comment]
Test report by @VRehnberg
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in total)
alvis2-02 - Linux Rocky Linux 8.8, x86_64, Intel(R) Xeon(R) Gold 6226R CPU @ 2.90GHz, 1 x NVIDIA Tesla T4, 535.104.05, Python 3.6.8
See https://gist.github.com/VRehnberg/78ae4fd0be3033b7c776bd24c718d652 for a full test report.

**Comment by VRehnberg** [comment]
Possibly add a sanity check that GPU is actually used with this version

**Comment by smoors** [comment]
> Possibly add a sanity check that GPU is actually used with this version

that would be useful, but then the test on generoso (and jsc-zen2?) will fail as it doesn't have a GPU
maybe add it comment out?

**Comment by smoors** [comment]
@boegelbot: please test @ generoso

**Comment by smoors** [comment]
the failed generoso test is because generoso is currently rebuilding NCCL for another PR..

**Comment by smoors** [comment]
@boegelbot: please test @ generoso

**Review by smoors — APPROVED** [review]
lgtm

**Comment by smoors** [comment]
Going in, thanks @VRehnberg!

**Comment by ThomasHoffmann77** [comment]
@smoors @VRehnberg As far as I remember RFdiffusion does not work without DGL and without Hydra. See #18359

**Comment by smoors** [comment]
@ThomasHoffmann77 sorry, i didn't see your PR and it looks like you are right.
i'll review if you fix the conflicts. please also check https://github.com/easybuilders/easybuild-easyconfigs/pull/19095

**Pull request merged**
