### PR TITLE
{lang}[foss/2020a] numba v0.52.0 w/ Python 3.8.2

### PR DESCRIPTION
**Pull request by bedroge**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by bedroge** [comment]
Test report by @bedroge
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
pg-interactive.hpc.rug.nl - Linux centos linux 7.9.2009, x86_64, Intel(R) Xeon(R) CPU E5-2680 v3 @ 2.50GHz, Python 3.6.8
See https://gist.github.com/4ef2c03840db97165d104207eac897be for a full test report.

**Comment by Micket** [comment]
Perhaps a better fit for 2020b toolchains that still lack a numba package?

**Comment by bedroge** [comment]
We don't have 2020b on our cluster yet, and we got a request for this specific numba version. But if it doesn't make sense to have this next to the existing one (0.50.0) for 2020a, feel free to close it :-)

**Comment by smoors** [comment]
Test report by @smoors
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
node369.hydra.os - Linux centos linux 7.9.2009, x86_64, Intel(R) Xeon(R) Gold 6148 CPU @ 2.40GHz (skylake_avx512), Python 2.7.5
See https://gist.github.com/5068d9b0c65d88045ad9b3c6efbdfe01 for a full test report.

**Comment by smoors** [comment]
it's perfectly fine to have 2 versions in the same toolchain, but be aware that only one version can be used as a dependency for other easyconfigs in the official repo.

**Comment by smoors** [comment]
@boegelbot: please test @ generoso

**Review by smoors — APPROVED** [review]
lgtm

**Comment by smoors** [comment]
Going in, thanks @bedroge!

**Pull request merged**
