### PR TITLE
[foss/2023a] PLINK-2.00a3.7 bugfix

### PR DESCRIPTION
**Pull request by keenandr**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by keenandr** [comment]
Changing test invocation from sh to bash to support the pipefail option for systems that link sh to dash

**Comment by bedroge** [comment]
Thanks for your contribution!

I had a look at other PLINK versions for which we have an easyconfig, and only https://github.com/easybuilders/easybuild-easyconfigs/blob/develop/easybuild/easyconfigs/p/PLINK/PLINK-2.00a3.7-foss-2022a.eb seems to include the same command. Could you perhaps fix that one as well in this PR, so we keep things consistent?

**Comment by boegel** [comment]
@boegelbot please test @ generoso

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in total)
node3117.skitty.os - Linux RHEL 8.8, x86_64, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz, Python 3.6.8
See https://gist.github.com/boegel/f9b05cd016bab7da55b85687149e48c6 for a full test report.

**Review by boegel — APPROVED** [review]
lgtm

**Comment by boegel** [comment]
Going in, thanks @keenandr!

**Pull request merged**
