### PR TITLE
{bio,lang}[GCC/12.3.0,GCCcore/12.3.0] mosdepth v0.3.9, Nim v2.2.0

### PR DESCRIPTION
**Pull request by PetrKralCZ**
(created using `eb --new-pr`)
resolves https://github.com/vscentrum/vsc-software-stack/issues/449

### CODE REVIEW

**Comment by PetrKralCZ** [comment]
@boegelbot please test @ generoso

**Comment by PetrKralCZ** [comment]
@boegelbot please test @ jsc-zen3

**Comment by laraPPr** [comment]
Test report by @laraPPr
**FAILED**
Build succeeded for 0 out of 2 (2 easyconfigs in total)
node4008.donphan.os - Linux RHEL 8.8, x86_64, Intel(R) Xeon(R) Gold 6240 CPU @ 2.60GHz, 1 x NVIDIA NVIDIA A2, 545.23.08, Python 3.11.3
See https://gist.github.com/laraPPr/03545b4780798151a432604db89f1e2b for a full test report.

**Comment by laraPPr** [comment]
Test report by @laraPPr
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in total)
node3103.skitty.os - Linux RHEL 9.4, x86_64, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz, Python 3.11.3
See https://gist.github.com/laraPPr/8ad28fce1cf567c69bfe018b5f9fa416 for a full test report.

**Comment by laraPPr** [comment]
@PetrKralCZ where did you test it because Nim is failing on donphan. And I can't really find what might have trigerred it.

**Comment by PetrKralCZ** [comment]
Test report by @PetrKralCZ
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in total)
node4010.donphan.os - Linux RHEL 8.8, x86_64, Intel(R) Xeon(R) Gold 6240 CPU @ 2.60GHz, 1 x NVIDIA NVIDIA A2, 545.23.08, Python 3.6.8
See https://gist.github.com/PetrKralCZ/9a2b8230bf17732268c75b10ce65b709 for a full test report.

**Comment by PetrKralCZ** [comment]
> @PetrKralCZ where did you test it because Nim is failing on donphan. And I can't really find what might have trigerred it.

It works for me on donphan: https://github.com/easybuilders/easybuild-easyconfigs/pull/21782#issuecomment-2460013769

**Review by laraPPr — APPROVED** [review]
lgtm

**Comment by laraPPr** [comment]
Going in, thanks @PetrKralCZ!

**Comment by laraPPr** [comment]
Going in, thanks @PetrKralCZ!

**Comment by laraPPr** [comment]
Going in, thanks @PetrKralCZ!

**Pull request merged**
