### PR TITLE
{cae}[foss/2020a] SU2 v7.0.6 w/ Python 3.8.2

### PR DESCRIPTION
**Pull request by alirezaghavaminia**
Hello,

I have created SU2-7.0.6-foss-2020a-Python-3.8.2.eb and also fixed the issues from the previous PR. Please consider this new PR.

Best wishes,
Alireza

### CODE REVIEW

**Comment by verdurin** [comment]
Test report by @verdurin
**FAILED**
Build succeeded for 14 out of 15 (1 easyconfigs in this PR)
nuc.lan - Linux Fedora 32, x86_64, Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz, Python 3.8.5
See https://gist.github.com/2d8d7fc0887d5cf47b131cbd5950172c for a full test report.

**Comment by verdurin** [comment]
Here is the actual error:
```
== 2020-10-09 21:46:38,374 run.py:222 INFO running cmd: ./bootstrap && ./configure --prefix=/mnt/ds918plus/eb/nuc-fedora32/software/SU2/7.0.6-foss-2020a-Python-3.8.2 CXXFLAGS="$CXXFLAGS" --enable-mpi --with-cc=mpicc --with-cxx=mpicxx
== 2020-10-09 21:47:18,971 build_log.py:169 ERROR EasyBuild crashed with an error (at easybuild/base/exceptions.py:124 in __init__): cmd "./bootstrap && ./configure --prefix=/mnt/ds918plus/eb/nuc-fedora32/software/SU2/7.0.6-foss-2020a-Python-3.8.2 CXXFLAGS="$CXXFLAGS" --enable-mpi --with-cc=mpicc --with-cxx=mpicxx" exited with exit code 127 and output:
Inadequate autotools in your path, I'll build new ones...
  building autoconf-2.69 in /mnt/ds918plus/eb/nuc-fedora32/build/SU2/7.0.6/foss-2020a-Python-3.8.2/SU2-7.0.6/externals/autotools
  building automake-1.15.1 in /mnt/ds918plus/eb/nuc-fedora32/build/SU2/7.0.6/foss-2020a-Python-3.8.2/SU2-7.0.6/externals/autotools
help2man: can't get `--help' info from automake-1.15
Try `--no-discard-stderr' if option outputs to stderr
make: *** [Makefile:3689: doc/automake-1.15.1] Error 2
  building libtool-2.4.2 in /mnt/ds918plus/eb/nuc-fedora32/build/SU2/7.0.6/foss-2020a-Python-3.8.2/SU2-7.0.6/externals/autotools
autoreconf: Entering directory `.'
autoreconf: configure.ac: not using Gettext
autoreconf: running: aclocal ${ACLOCAL_FLAGS} -I m4 --output=aclocal.m4t
sh: aclocal: command not found
autoreconf: aclocal failed with exit status: 127
/bin/bash: ./configure: No such file or directory
 (at easybuild/tools/run.py:533 in parse_cmd_output)
```

Looks like you need to include `Autotools` as a build-dependency.

**Review by boegel — CHANGES_REQUESTED** [review]
@alirezaghavaminia I tweaked this easyconfig file a bit, see https://github.com/alirezaghavaminia/easybuild-easyconfigs/pull/1 .

It seems like the `$SU2_RUN` environment variable should be defined?

**Comment by boegel** [comment]
@boegelbot please test @ generoso

**Comment by alirezaghavaminia** [comment]
> @alirezaghavaminia I tweaked this easyconfig file a bit, see [alirezaghavaminia#1](https://github.com/alirezaghavaminia/easybuild-easyconfigs/pull/1) .
> 
> It seems like the `$SU2_RUN` environment variable should be defined?

Thank you for your help. 
According to the [su2 documentation](https://su2code.github.io/docs/Build-from-Source/) 

> `$SU2_RUN` should point to the folder where all binaries and python scripts were installed (by default, in a folder named bin/ 
>
> within your chosen install location from `--prefix`). `$SU2_HOME` should point to the root directory of your SU2 source distribution.
> 
> For example, add these lines to your `~/.bashrc` (linux) or `~/.bash_profile` (macosx) file:
> 
> ```bash
> export SU2_RUN="your/prefix/bin"
> export SU2_HOME="/path/to/SU2"
> export PATH=$SU2_RUN:$PATH
> ```
> If you plan to use the Python scripts for parallel calculations or design and optimization tasks, you may also want to include `$SU2_RUN` in your Python path:
> 
> ```bash
> export PYTHONPATH=$SU2_RUN:$PYTHONPATH
> ```

and [here](https://su2code.github.io/docs/Simple-Build/)

> Make sure to note the SU2_RUN and SU2_HOME environment variables displayed at the conclusion of configure. It is recommended that you add the SU2_RUN and SU2_HOME variables to your ~/.bashrc file and update your PATH variable to include the install location ($SU2_RUN, specified by --prefix).


The generated module file already puts the `SU2_RUN` executables into the `PATH`. But I don't know whether this environment variable is required or not? My best guess is that it is not required.


Regarding the `SU2_CFD.py --help` error, I think that's due to the lack of python wrapper build flags, which are optional. [Link to python wrapper build documentation](https://su2code.github.io/docs/Python-Wrapper-Build/)

**Comment by smoors** [comment]
@alirezaghavaminia you can add the missing environment variables like this:
```
modextrapaths = {
    'SU2_RUN': 'bin',
    'SU2_HOME': '',
}
```

to enable the python wrapper, you can probably add `--enable-PY_WRAPPER` to your `configopts`, and add `SWIG` to your `builddependencies`.

that said, the build instructions have changed since version 7 (using meson/ninja), although the old method may still work.
see: https://su2code.github.io/docs_v7/Build-SU2-Linux-MacOS/

**Comment by alirezaghavaminia** [comment]
> @alirezaghavaminia you can add the missing environment variables like this:
> 
> ```
> modextrapaths = {
>     'SU2_RUN': 'bin',
>     'SU2_HOME': '',
> }
> ```
> 
> to enable the python wrapper, you can probably add `--enable-PY_WRAPPER` to your `configopts`, and add `SWIG` to your `builddependencies`.
> 
> that said, the build instructions have changed since version 7 (using meson/ninja), although the old method may still work.
> see: https://su2code.github.io/docs_v7/Build-SU2-Linux-MacOS/

Unfortunately, I do not have access to the easybuild right now. Can you perform the changes?

**Comment by akesandgren** [comment]
Closing this PR, since it (only) uses deprecated toolchain versions,
see https://docs.easybuild.io/policies/toolchains .

**Comment by nikishe** [comment]
Hey @alirezaghavaminia I have been trying to install your config but failed horribly. Can I pick your brain

**Comment by alirezaghavaminia** [comment]
Sorry for the late reply. Unfortunately I am not able to answer your questions since I have no access to an active installation of easybuild right now. You can ask your questions and I am sure there will be se active members who can answer you. Best wishes AlirezaSent from my Galaxy
-------- Original message --------From: nikishe ***@***.***> Date: 4/12/24  10:58  (GMT+03:30) To: easybuilders/easybuild-easyconfigs ***@***.***> Cc: Alireza Ghavaminia ***@***.***>, Mention ***@***.***> Subject: Re: [easybuilders/easybuild-easyconfigs] {cae}[foss/2020a] SU2 v7.0.6 w/ Python 3.8.2 (#11446) 
Hey @alirezaghavaminia I have been trying to install your config but failed horribly. Can I pick your brain

**Pull request closed without merging**
