### PR TITLE
{vis}[foss/2020b,intel/2020b] VisPy v0.6.6 w/ Python 3.8.6

### PR DESCRIPTION
**Pull request by SimonPinches**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by robert-mijakovic** [comment]
`AssertionError: 'source_urls' should not be defined in exts_default_options when using the default value in VisPy-0.6.6-foss-2020b.eb
'source_urls' should not be defined in exts_default_options when using the default value in VisPy-0.6.6-intel-2020b.eb`

**Comment by SimonPinches** [comment]
@robert-mijakovic I've fixed the error mentioned (I think!).

**Comment by lexming** [comment]
Test report by @lexming
**SUCCESS**
Build succeeded for 3 out of 3 (2 easyconfigs in total)
node375.hydra.os - Linux centos linux 7.9.2009, x86_64, Intel(R) Xeon(R) Gold 6148 CPU @ 2.40GHz, Python 2.7.5
See https://gist.github.com/b8ac4e94e60d21b5537849082e3a86f9 for a full test report.

**Review by lexming — APPROVED** [review]
LGTM

**Comment by lexming** [comment]
Going in, thanks @SimonPinches !

**Pull request merged**
