### PR TITLE
{compiler,tools}[GCCcore/12.3.0] Clang v16.0.6, Z3 v4.12.2

### PR DESCRIPTION
**Pull request by boegel**
(created using `eb --new-pr`)

Needs: https://github.com/easybuilders/easybuild-easyblocks/pull/2929

### CODE REVIEW

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 3 out of 3 (2 easyconfigs in total)
node3116.skitty.os - Linux RHEL 8.6, x86_64, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz (skylake_avx512), Python 3.6.8
See https://gist.github.com/boegel/4db56a5ed74642952fdbe0c466642459 for a full test report.

**Comment by casparvl** [comment]
Test report by @casparvl
**FAILED**
Build succeeded for 1 out of 2 (2 easyconfigs in total)
tcn1.local.snellius.surf.nl - Linux RHEL 8.6, x86_64, AMD EPYC 7H12 64-Core Processor, Python 3.6.8
See https://gist.github.com/casparvl/a0ef7f07ee869466e0684b115c79ca51 for a full test report.

**Comment by SebastianAchilles** [comment]
Test report by @sebastianachilles
Using easyblocks from PR(s) https://github.com/easybuilders/easybuild-easyblocks/pull/2929
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in total)
zen2-ubuntu-2304 - Linux Ubuntu 23.04 (Lunar Lobster), x86_64, AMD EPYC 7452 32-Core Processor (zen2), Python 3.11.2
See https://gist.github.com/SebastianAchilles/021f14cd9c05a51b0ed75ec7b480e8b0 for a full test report.

**Comment by casparvl** [comment]
Test report by @casparvl
**FAILED**
Build succeeded for 1 out of 2 (2 easyconfigs in total)
tcn1.local.snellius.surf.nl - Linux RHEL 8.6, x86_64, AMD EPYC 7H12 64-Core Processor, Python 3.6.8
See https://gist.github.com/casparvl/1811e08ccea01021054b451f1c8d2f9c for a full test report.

**Comment by casparvl** [comment]
Well, at least without the `-funroll-all-loops` this config test:
```
-- Performing Test CXX_SUPPORTS_FNO_EXCEPTIONS_FLAG
-- Performing Test CXX_SUPPORTS_FNO_EXCEPTIONS_FLAG - Success
```
Now succeeds just fine. The new error is now in the sanity check:
``` 
= 2023-08-16 18:32:21,326 build_log.py:171 ERROR EasyBuild crashed with an error (at easybuild/base/exceptions.py:126 in __init__): Sanity check failed: no file found at 'lib/clang/16.0.4/include/stddef.h' in /scratch-nvme/1/casparl/generic/software/Clang/16.0.4-GCCcore-12.2.0
no file found at 'lib/clang/16.0.4/include/omp.h' in /scratch-nvme/1/casparl/generic/software/Clang/16.0.4-GCCcore-12.2.0
no (non-empty) directory found at 'lib/clang/16.0.4/lib' in /scratch-nvme/1/casparl/generic/software/Clang/16.0.4-GCCcore-12.2.0 (at easybuild/framework/easyblock.py:3639 in _sanity_check_step)
```

**Comment by casparvl** [comment]
Interesting, for me the `omp.h` does exist, but in a slightly different directory that does _not_ include the version and revision:
```
/scratch-nvme/1/casparl/generic/software/Clang/16.0.4-GCCcore-12.2.0/lib/clang/16/include/omp.h
```
The only thing that tends to be different for us than for others is that we build with `RPATH` support... I'm not sure how that would impact the version dir that this gets installed in, but... ?

**Comment by casparvl** [comment]
Test report by @casparvl
Using easyblocks from PR(s) https://github.com/easybuilders/easybuild-easyblocks/pull/2929
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in total)
tcn1.local.snellius.surf.nl - Linux RHEL 8.6, x86_64, AMD EPYC 7H12 64-Core Processor, Python 3.6.8
See https://gist.github.com/casparvl/8241b3a8d4519da25c4f5365352c919a for a full test report.

**Review by casparvl — APPROVED** [review]

**Comment by casparvl** [comment]
Going in, thanks @boegel!

**Pull request merged**
