### PR TITLE
add AICcmodavg and biomod2 extensions to R-4.0.0-foss-2020a easyconfig

### PR DESCRIPTION
**Pull request by arielzn**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by arielzn** [comment]
For some reason Travis keeps timing out for Python 3.6 checks

**Comment by boegel** [comment]
@verdurin Close re-open is not good enough to get rid of Travis, you need to sync with current `develop` branch now #11055 is merged.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
generoso - Linux centos linux 8.2.2004, x86_64, Intel(R) Xeon(R) CPU E5-2667 v3 @ 3.20GHz (haswell), Python 3.6.8
See https://gist.github.com/914670a50fe53d99393672422f1b9767 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
node3401.kirlia.os - Linux centos linux 7.8.2003, x86_64, Intel(R) Xeon(R) Gold 6240 CPU @ 2.60GHz (cascadelake), Python 2.7.5
See https://gist.github.com/ceb9cdfba27e4d00353eb8afb379ecd5 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
node2421.golett.os - Linux centos linux 7.8.2003, x86_64, Intel(R) Xeon(R) CPU E5-2680 v3 @ 2.50GHz (haswell), Python 2.7.5
See https://gist.github.com/62fd15ed15342eda87127c195fe6d6b7 for a full test report.

**Comment by verdurin** [comment]
Test report by @verdurin
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
easybuild.novalocal - Linux centos linux 7.8.2003, x86_64, Intel Xeon Processor (Skylake, IBRS), Python 2.7.5
See https://gist.github.com/b209d383eff350bf03dd4484d7a0b6bb for a full test report.

**Comment by boegel** [comment]
Agreed, so let's merge :)

**Comment by boegel** [comment]
Going in, thanks @arielzn!

**Pull request merged**
