### PR TITLE
Drop help2man from flex at SYSTEM level. help2man depends on Perl and we do not want Perl at SYSTEM level.

### PR DESCRIPTION
**Pull request by akesandgren**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by akesandgren** [comment]
Test report by @akesandgren
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in total)
b-an02.hpc2n.umu.se - Linux Ubuntu 20.04, x86_64, Intel(R) Xeon(R) CPU E5-2690 v4 @ 2.60GHz, Python 3.8.5
See https://gist.github.com/44b678d4fec56c2466601a9050f1a2e4 for a full test report.

**Comment by Micket** [comment]
Old checksum needs updating to sha256

**Comment by akesandgren** [comment]
@boegelbot Please test @ generoso

**Review by Micket — APPROVED** [review]
lgtm. In fact, I think we should disable manpages almost everywhere when we can, since we are typically exceeding the max length for MANPATH. I think we should just refer users to the many online documentations for all these softwares instead /rant)

**Comment by Micket** [comment]
Test report by @Micket
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in total)
alvis-c1 - Linux centos linux 7.9.2009, x86_64, Intel Xeon Processor (Skylake), Python 3.6.8
See https://gist.github.com/b7bdbae1cdbec2c346bf057e342cab38 for a full test report.

**Comment by Micket** [comment]
Going in, thanks @akesandgren!

**Pull request merged**
