### PR TITLE
Ensure Bazel 3.7.2 respects $TMPDIR

### PR DESCRIPTION
**Pull request by jfgrimm**
Haven't checked older versions; I assume that most versions will probably be affected

(created using `eb --new-pr`)

### CODE REVIEW

**Comment by jfgrimm** [comment]
@boegelbot: please test @ generoso

**Comment by branfosj** [comment]
> Haven't checked older versions; I assume that most versions will probably be affected

0.20.0 and 2.0.0 both have the same line, but, annoyingly, the patch does not work for either. I am thinking that it would be better to fix this in the easyblock.

**Comment by jfgrimm** [comment]
> > Haven't checked older versions; I assume that most versions will probably be affected
> 
> 0.20.0 and 2.0.0 both have the same line, but, annoyingly, the patch does not work for either. I am thinking that it would be better to fix this in the easyblock.

Makes sense, I'll have a look at the easyblock tomorrow

**Comment by jfgrimm** [comment]
@branfosj I've opened an easyblocks PR https://github.com/easybuilders/easybuild-easyblocks/pull/2703

**Pull request closed without merging**
