### PR TITLE
{bio}[foss/2020a] immunedeconv v2.0.2 w/ R 4.0.0

### PR DESCRIPTION
**Pull request by smoors**
(created using `eb --new-pr`)
depends on ~#11135~ and easyblock PR ~~https://github.com/easybuilders/easybuild-easyblocks/pull/2125~~

### CODE REVIEW

**Comment by smoors** [comment]
Test report by @smoors
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
node254.hydra.os - Linux centos linux 7.7.1908, x86_64, Intel(R) Xeon(R) CPU E5-2683 v4 @ 2.10GHz (broadwell), Python 2.7.5
See https://gist.github.com/06d3598c57b85463b304910b5f51a25e for a full test report.

**Comment by smoors** [comment]
@boegelbot please test @ generoso EB_ARGS="--include-easyblocks-from-pr=2125"

**Comment by smoors** [comment]
@boegelbot please test @ generoso
EB_ARGS=--include-easyblocks-from-pr 2125

**Comment by verdurin** [comment]
Test report by @verdurin
**FAILED**
Build succeeded for 0 out of 2 (1 easyconfigs in this PR)
nuc.localdomain - Linux Fedora 32, x86_64, Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz, Python 3.8.5
See https://gist.github.com/cd9992478e0ab227a765ab33e8d9cf0e for a full test report.

**Comment by boegel** [comment]
@smoors First job submitted by @boegelbot failed hard, it's not very robust yet:

```
[boegelbot@generoso boegelbot]$ cat slurm-5066.out
ERROR: Can't find path /tmp/eb-91c818xe/tmpjzdve_t9/easybuilders/"--include-easyblocks-from-pr=2125"
== temporary log file in case of crash /tmp/eb-91c818xe/easybuild-n35x645f.log
```

**Comment by verdurin** [comment]
Test report by @verdurin
**FAILED**
Build succeeded for 0 out of 1 (1 easyconfigs in this PR)
easybuild.novalocal - Linux centos linux 7.8.2003, x86_64, Intel Xeon Processor (Skylake, IBRS), Python 2.7.5
See https://gist.github.com/ed558be0d6e1053bc4709eb8104982b4 for a full test report.

**Comment by verdurin** [comment]
Test report by @verdurin
**FAILED**
Build succeeded for 0 out of 1 (1 easyconfigs in this PR)
easybuild.novalocal - Linux centos linux 7.8.2003, x86_64, Intel Xeon Processor (Skylake, IBRS), Python 2.7.5
See https://gist.github.com/ada5ced0f4a17d78a2457c0c043bdd16 for a full test report.

**Comment by verdurin** [comment]
```
== 2020-08-20 06:59:03,193 run.py:222 INFO running cmd:  R CMD INSTALL /eb/maint/build/immunedeconv/2.0.2/foss-2020a-R-4.0.0/immunedeconv/immunedeconv-2.0.2   --library=/eb/maint/software/immunedeconv/2.0.2-foss-2020a-R-4.0.0/ --no-clean-on-error
== 2020-08-20 06:59:03,446 build_log.py:169 ERROR EasyBuild crashed with an error (at easybuild/base/exceptions.py:124 in __init__): cmd " R CMD INSTALL /eb/maint/build/immunedeconv/2.0.2/foss-2020a-R-4.0.0/immunedeconv/immunedeconv-2.0.2   --library=/eb/maint/software/immunedeconv/2.0.2-foss-2020a-R-4.0.0/ --no-clean-on-error " exited with exit code 1 and output:
ERROR: dependencies testit, data.tree are not available for package immunedeconv
 (at easybuild/tools/run.py:533 in parse_cmd_output)
```

Suppose I need to rebuild my local `Bioconductor`?

**Comment by verdurin** [comment]
Test report by @verdurin
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
easybuild.novalocal - Linux centos linux 7.8.2003, x86_64, Intel Xeon Processor (Skylake, IBRS), Python 2.7.5
See https://gist.github.com/6f8b7ae2a9ca97cde20ec65ed358ffa9 for a full test report.

**Comment by smoors** [comment]
@zao I think you forgot to include the easyblock PR (see first comment)?

**Comment by zao** [comment]
Test report by @zao
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
freja - Linux Ubuntu 20.04, x86_64, Intel(R) Core(TM) i7-8700K CPU @ 3.70GHz, Python 3.8.2
See https://gist.github.com/323590b66202ae5977d337224588ca92 for a full test report.

**Comment by zao** [comment]
@smoors You are correct :)

**Comment by smoors** [comment]
Test report by @smoors
**FAILED**
Build succeeded for 0 out of 1 (1 easyconfigs in this PR)
node226.hydra.os - Linux centos linux 7.7.1908, x86_64, Intel(R) Xeon(R) CPU E5-2680 v4 @ 2.40GHz (broadwell), Python 2.7.5
See https://gist.github.com/8e16a246f7516091211f4a25b77c7783 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 0 out of 0 (1 easyconfigs in this PR)
node3106.skitty.os - Linux centos linux 7.8.2003, x86_64, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz (skylake_avx512), Python 3.6.8
See https://gist.github.com/49a046f0d957abf1284a548182cf40e2 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
node3106.skitty.os - Linux centos linux 7.8.2003, x86_64, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz (skylake_avx512), Python 3.6.8
See https://gist.github.com/2ea514b29ab7d6759c50f74017d62c7b for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
node2411.golett.os - Linux centos linux 7.8.2003, x86_64, Intel(R) Xeon(R) CPU E5-2680 v3 @ 2.50GHz (haswell), Python 2.7.5
See https://gist.github.com/a6959393a0600838cd513c2f2bacb245 for a full test report.

**Comment by boegel** [comment]
@boegelbot please test @ generoso

**Review by boegel — APPROVED** [review]
lgtm

**Comment by boegel** [comment]
Going in, thanks @smoors!

**Pull request merged**
