### PR TITLE
{lib}[foss/2019b] DMCfun v1.3.0 w/ R 3.6.2

### PR DESCRIPTION
**Pull request by boegel**
(created using `eb --new-pr`)

Related to #12409, where `DMCfun` is added as an extension to the most recent `R` easyconfigs.

`DMCfun` was requested specifically for this old version of `R`, which is not easy to do because some extension versions are too old.

### CODE REVIEW

**Comment by boegel** [comment]
@boegelbot please test @ generoso

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
node2602.swalot.os - Linux centos linux 7.9.2009, x86_64, Intel(R) Xeon(R) CPU E5-2660 v3 @ 2.60GHz (haswell), Python 3.6.8
See https://gist.github.com/61881a4ac20e830a13e5a354f424c7b0 for a full test report.

**Review by branfosj — APPROVED** [review]
lgtm

**Comment by branfosj** [comment]
Test report by @branfosj
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
bear-pg0211u03a.bear.cluster - Linux centos linux 7.8.2003, x86_64, Intel(R) Xeon(R) Gold 6248 CPU @ 2.50GHz (cascadelake), Python 3.6.8
See https://gist.github.com/6fabf63ec096e4d008de3ace77b889a2 for a full test report.

**Comment by branfosj** [comment]
Going in, thanks @boegel!

**Pull request merged**
