### PR TITLE
symlink FastTreeMP to FastTree binary for FastTree 2.1.11

### PR DESCRIPTION
**Pull request by smoors**
(created using `eb --new-pr`)

required for QIIME2

### CODE REVIEW

**Comment by smoors** [comment]
@boegelbot: please test @ generoso

**Review by Micket — APPROVED** [review]
lgtm

**Comment by smoors** [comment]
@boegelbot please test @ jsc-zen2

**Comment by verdurin** [comment]
Test report by @verdurin
**SUCCESS**
Build succeeded for 4 out of 4 (4 easyconfigs in total)
easybuild-c7.novalocal - Linux CentOS Linux 7.9.2009, x86_64, Intel Xeon Processor (Skylake, IBRS), Python 3.6.8
See https://gist.github.com/verdurin/5442d31532abe2eb2bfc23c37fec9862 for a full test report.

**Comment by verdurin** [comment]
Going in, thanks @smoors!

**Pull request merged**
