### PR TITLE
{vis}[foss/2018b,intel/2018b] Mesa-18.1.1: add patch to detect MIT-SHM

### PR DESCRIPTION
**Pull request by bartoldeman**
Query MIT-SHM before using it, to avoid issues with MobaXterm/Xming.
See also patch submitted upstream here:
https://gitlab.freedesktop.org/mesa/mesa/merge_requests/200

### CODE REVIEW

**Comment by vanzod** [comment]
@bartoldeman How hard would it be to apply it to the older versions of `Mesa`?

**Comment by vanzod** [comment]
Test report by @vanzod
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in this PR)
cermis - Linux debian 9.7, Intel(R) Xeon(R) CPU           X5670  @ 2.93GHz, Python 2.7.13
See https://gist.github.com/9e3afc73581e84ced94c524b33fe3d43 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in this PR)
node3105.skitty.os - Linux centos linux 7.6.1810, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz, Python 2.7.5
See https://gist.github.com/39577ccfde4b90d3f8e92cdaff0fe3e9 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in this PR)
node2402.golett.os - Linux centos linux 7.6.1810, Intel(R) Xeon(R) CPU E5-2680 v3 @ 2.50GHz, Python 2.7.5
See https://gist.github.com/48fff5938c96d0bf30f09b7565effe15 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in this PR)
node2034.delcatty.os - Linux centos linux 7.6.1810, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.7.5
See https://gist.github.com/55d273195eaa3e81ca20aa70daddb2db for a full test report.

**Comment by bartoldeman** [comment]
This patch can be applied to many mesa's going a long way back.@vanzod

**Comment by bartoldeman** [comment]
It can be removed for Mesa 18.3.4 and up, as it was accepted upstream:
https://www.mesa3d.org/relnotes/18.3.4.html

**Comment by boegel** [comment]
@vanzod Backporting this to older `Mesa` versions should be done in a separate PR (to avoid making this one more demanding w.r.t. submitting test reports).

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 3 out of 3 (3 easyconfigs in this PR)
node3105.skitty.os - Linux centos linux 7.6.1810, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz, Python 2.7.5
See https://gist.github.com/63f37f5f4dcfd587126b52bad00a2e71 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**FAILED**
Build succeeded for 2 out of 3 (3 easyconfigs in this PR)
node2034.delcatty.os - Linux centos linux 7.6.1810, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.7.5
See https://gist.github.com/9208a5d31bb51ee7efb4fdc53f935a70 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 4 out of 4 (3 easyconfigs in this PR)
node2402.golett.os - Linux centos linux 7.6.1810, Intel(R) Xeon(R) CPU E5-2680 v3 @ 2.50GHz, Python 2.7.5
See https://gist.github.com/a7b8f41ac3197c0a47578b560df93e31 for a full test report.

**Comment by boegel** [comment]
Going in, thanks @bartoldeman!

**Pull request merged**
