### PR TITLE
{bio}[dummy/dummy] BLAST v2.8.1

### PR DESCRIPTION
**Pull request by murfreesboro**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by murfreesboro** [comment]
Test report by @murfreesboro
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
dev806.vampire - Linux centos linux 7.4.1708, Intel(R) Xeon(R) CPU           E5620  @ 2.40GHz, Python 2.7.5
See https://gist.github.com/e27efe51d3b2e1be2d561e7e0941cb81 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
node3100.skitty.os - Linux centos linux 7.6.1810, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz, Python 2.7.5
See https://gist.github.com/3f84126c2296d0c69713d74f17519f6d for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
node2083.delcatty.os - Linux centos linux 7.6.1810, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.7.5
See https://gist.github.com/8fec3b93e5b70fe31dc5e5e2a5cd0fdc for a full test report.

**Comment by boegel** [comment]
@murfreesboro No strong objections on merging this since we already have `BLAST+` easyconfigs for pre-built binaries, but any particular reason you prefer this over a from-source build?

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
node2404.golett.os - Linux centos linux 7.6.1810, Intel(R) Xeon(R) CPU E5-2680 v3 @ 2.50GHz, Python 2.7.5
See https://gist.github.com/b684f7f52ef8c8c09ca78377e333e78c for a full test report.

**Comment by murfreesboro** [comment]
@boegel from the official download page for BLAST I was directed to this binary, so I just chose this from-binary build.

**Comment by boegel** [comment]
Going in, thanks @murfreesboro!

**Pull request merged**
