### PR TITLE
don't skip source step in FastTree easyconfigs + fix SHA256 checksum for FastTree 2.1.11

### PR DESCRIPTION
**Pull request by boegel**
(created using `eb --new-pr`)

This faulty checksum went undetected because these easyconfigs use `skipsteps = ['source']`, so the checksums never get validated... 🤦

### CODE REVIEW

**Comment by boegel** [comment]
@boegelbot please test @ generoso

**Comment by boegel** [comment]
We should probably introduce a big fat warning when `skipsteps = ['source']` is used, or perhaps disallow it, and definitely avoid using it in easyconfigs in the central repo...

**Comment by branfosj** [comment]
To have the checksums are validated:
* `sources = [{'filename': '%(name)s-%(version)s.c', 'extract_cmd': 'cp %s FastTree.c'}]`
* Remove `skipsteps = ['source']`
* `cmds_map = [('%(name)s-%(version)s.c', '$CC -DOPENMP $CFLAGS $LIBS %(name)s.c -o %(name)s')]`

**Comment by boegel** [comment]
@boegelbot please test @ generoso
EB_ARGS="FastTree-2.1.10-foss-2018b.eb FastTree-2.1.11-GCCcore-8.2.0.eb FastTree-2.1.11-GCCcore-8.3.0.eb FastTree-2.1.11-GCCcore-9.3.0.eb"

**Comment by boegel** [comment]
@boegelbot please test @ generoso
EB_ARGS="FastTree-2.1.10-foss-2018b.eb FastTree-2.1.11-GCCcore-8.2.0.eb FastTree-2.1.11-GCCcore-8.3.0.eb FastTree-2.1.11-GCCcore-9.3.0.eb"

**Comment by boegel** [comment]
@boegelbot please test @ generoso
EB_ARGS="FastTree-2.1.10-foss-2018b.eb FastTree-2.1.11-GCCcore-8.2.0.eb FastTree-2.1.11-GCCcore-8.3.0.eb FastTree-2.1.11-GCCcore-9.3.0.eb"

**Review by branfosj — APPROVED** [review]
lgtm

**Comment by branfosj** [comment]
Going in, thanks @boegel!

**Pull request merged**
