### PR TITLE
{data}[gompi/2023a,iimpi/2023a] HDF5 v1.14.0, netCDF v4.9.2

### PR DESCRIPTION
**Pull request by SebastianAchilles**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by SebastianAchilles** [comment]
Test report by @sebastianachilles
**SUCCESS**
Build succeeded for 4 out of 4 (4 easyconfigs in total)
zen2-ubuntu-2304 - Linux Ubuntu 23.04 (Lunar Lobster), x86_64, AMD EPYC 7452 32-Core Processor (zen2), Python 3.11.2
See https://gist.github.com/SebastianAchilles/d8e835dc4fbc64d2813a114f564ecf23 for a full test report.

**Comment by SebastianAchilles** [comment]
@boegelbot please test @ generoso
CORE_CNT=16

**Comment by SebastianAchilles** [comment]
@boegelbot please test @ jsc-zen2
CORE_CNT=16

**Comment by SebastianAchilles** [comment]
@boegelbot please test @ jsc-zen2
EB_ARGS=netCDF-4.9.2-iimpi-2023a.eb

**Comment by SebastianAchilles** [comment]
When building `netCDF-4.9.2-iimpi-2023a.eb` in an interactive shell on `jsc-zen2` I cannot reproduce the error. One difference I can think of is that I use `--buildpath=/dev/shm/$USER`. boebelbot uses `--buildpath=/tmp/$USER` instead.

**Comment by SebastianAchilles** [comment]
@boegelbot please test @ jsc-zen2
EB_ARGS="--tmp-logdir=$HOME/PR18523 netCDF-4.9.2-iimpi-2023a.eb"

**Comment by SebastianAchilles** [comment]
Test report by @sebastianachilles
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
jsczen2c1.int.jsc-zen2.easybuild-test.cluster - Linux Rocky Linux 8.5, x86_64, AMD EPYC 7742 64-Core Processor (zen2), Python 3.6.8
See https://gist.github.com/SebastianAchilles/0c75208a9fc218d0747ea7d4102d89f2 for a full test report.

**Comment by SebastianAchilles** [comment]
@boegelbot please test @ jsc-zen2
EB_ARGS="--buildpath=/dev/shm/$USER netCDF-4.9.2-iimpi-2023a.eb"

**Comment by SebastianAchilles** [comment]
The `netCDF` test hangs in `@MPIEXEC@ -n 16 ./tst_parallel3` on `jsc-zen2` when using `--buildpath=/tmp/$USER`.

**Comment by SebastianAchilles** [comment]
@boegelbot please test @ jsc-zen2

**Comment by SebastianAchilles** [comment]
@boegelbot please test @ jsc-zen2

**Comment by SebastianAchilles** [comment]
The last two build on `jsc-zen2` were successful, however bot time uploading the test report failed with `HTTP Error 403: Forbidden`, c.f.: https://github.com/easybuilders/easybuild-framework/issues/3934

**Comment by SebastianAchilles** [comment]
@boegelbot please test @ jsc-zen2
CORE_CNT=16

**Review by boegel — APPROVED** [review]
lgtm

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 4 out of 4 (4 easyconfigs in total)
node3104.skitty.os - Linux RHEL 8.6, x86_64, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz (skylake_avx512), Python 3.6.8
See https://gist.github.com/boegel/e8c77ffccc388a8b598982e259c75f5d for a full test report.

**Comment by boegel** [comment]
Going in, thanks @SebastianAchilles!

**Pull request merged**
