### PR TITLE
{devel,tools,lib,compiler}[system/system,GCCcore/14.2.0] Add pkgconf 2.3.0, XZ 5.6.3, ncurses 6.5, libxml 2.13.4, AOCC 5.0.0

### PR DESCRIPTION
**Pull request by Thyre**
Add AOCC 5.0.0 and required dependencies to GCCcore 14.2.0. I chose the newest toolchain, as there's #21343 for GCCcore/13.3.0 already.

Requires https://github.com/easybuilders/easybuild-easyblocks/pull/3480 for compilers to work correctly.

### CODE REVIEW

**Comment by Thyre** [comment]
Test report by @Thyre
**SUCCESS**
Build succeeded for 6 out of 6 (6 easyconfigs in total)
Linux - Linux EndeavourOS UNKNOWN, x86_64, AMD Ryzen 7 7800X3D 8-Core Processor, 1 x NVIDIA NVIDIA GeForce RTX 3070, 560.35.03, Python 3.12.7
See https://gist.github.com/Thyre/27e52c07480cf9293d71b84dd32a0908 for a full test report.

**Comment by Thyre** [comment]
AOCC 5.0.0 seems to fail to link `libstdc++` for `clang++` in the current configuration. This should be solvable, but I have to build a nice solution first.

I'll also check if this happens due to our EasyBlock or if this is broken in general.

**Comment by Thyre** [comment]
> AOCC 5.0.0 seems to fail to link `libstdc++` for `clang++` in the current configuration. This should be solvable, but I have to build a nice solution first. The same error occurs with the `[x].orig` compilers.
> 
> I'll also check if this happens due to our EasyBlock or if this is broken in general.

The error occurs because we're renaming the compilers.

In a base AOCC installation (without EasyBuild):

```
$ cat test.cpp
#include <iostream>

int main( int argc, char** argv )
{
    std::cout << "Hello World" << std::endl;
}
$ ./bin/clang++ test.cpp && echo "Success"
Success
$ mv ./bin/clang++ ./bin/clang++.orig
$ ./bin/clang++.orig test.cpp && echo "Success"
ld.lld: error: undefined symbol: std::cout
>>> referenced by test.cpp
>>>               /tmp/test-85d59c.o:(main)
>>> referenced by test.cpp
>>>               /tmp/test-85d59c.o:(main)

ld.lld: error: undefined symbol: std::basic_ostream<char, std::char_traits<char>>& std::__ostream_insert<char, std::char_traits<char>>(std::basic_ostream<char, std::char_traits<char>>&, char const*, long)
>>> referenced by test.cpp
>>>               /tmp/test-85d59c.o:(main)

ld.lld: error: undefined symbol: std::ctype<char>::_M_widen_init() const
>>> referenced by test.cpp
>>>               /tmp/test-85d59c.o:(main)

ld.lld: error: undefined symbol: std::ostream::put(char)
>>> referenced by test.cpp
>>>               /tmp/test-85d59c.o:(main)

ld.lld: error: undefined symbol: std::ostream::flush()
>>> referenced by test.cpp
>>>               /tmp/test-85d59c.o:(main)

ld.lld: error: undefined symbol: std::__throw_bad_cast()
>>> referenced by test.cpp
>>>               /tmp/test-85d59c.o:(main)
clang++: error: linker command failed with exit code 1 (use -v to see invocation)
```

**Comment by Thyre** [comment]
Test report by @Thyre
Using easyblocks from PR(s) https://github.com/easybuilders/easybuild-easyblocks/pull/3480
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
Linux - Linux EndeavourOS UNKNOWN, x86_64, AMD Ryzen 7 7800X3D 8-Core Processor, 1 x NVIDIA NVIDIA GeForce RTX 3070, 560.35.03, Python 3.12.7
See https://gist.github.com/Thyre/d8c1a24eca2e69a65f4e7d90ff38b22f for a full test report.

**Comment by Thyre** [comment]
Even with the PR, `flang` fails to work correctly. When using the wrapper, `flang` fails to compile a basic test program. Renaming `flang.orig` to `flang` (i.e removing the wrapper) everything works again, but the wrong GCC is used. A `flang.cfg` is not picked up. Investigating...

**Comment by Thyre** [comment]
Test report by @Thyre
Using easyblocks from PR(s) https://github.com/easybuilders/easybuild-easyblocks/pull/3480
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
Linux - Linux EndeavourOS UNKNOWN, x86_64, AMD Ryzen 7 7800X3D 8-Core Processor, 1 x NVIDIA NVIDIA GeForce RTX 3070, 560.35.03, Python 3.12.7
See https://gist.github.com/Thyre/3b990f98dac8e19fa41d1960f0406d5f for a full test report.

**Comment by SebastianAchilles** [comment]
@boegelbot please test @ generoso
EB_ARGS="--include-easyblocks-from-pr 3480"

**Review by SebastianAchilles — APPROVED** [review]
lgtm

**Comment by SebastianAchilles** [comment]
Going in, thanks @Thyre!

**Pull request merged**
