### PR TITLE
Add support for building OpenBLAS on ARM TSV110 with GCC 8.3

### PR DESCRIPTION
**Pull request by Flamefire**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by Flamefire** [comment]
This should fix the issue from https://github.com/easybuilders/easybuild-easyconfigs/pull/11251#issuecomment-704389043

@terjekv Please test

**Comment by terjekv** [comment]
Will test, thanks! My test box needs the entire stack before `GCC-8.3.0.eb` but that shouldn't take too long.

**Review by boegel — APPROVED** [review]
lgtm

**Comment by boegel** [comment]
@boegelbot please test @ generoso

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
node3404.kirlia.os - Linux centos linux 7.8.2003, x86_64, Intel(R) Xeon(R) Gold 6240 CPU @ 2.60GHz (cascadelake), Python 2.7.5
See https://gist.github.com/f2973f27a2a7fb33611e5f4951a2af54 for a full test report.

**Comment by terjekv** [comment]
Test report by @terjekv
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
arm2 - Linux ubuntu 18.04, AArch64, UNKNOWN, Python 3.6.9
See https://gist.github.com/831277169024cfcad0d0413022e662dc for a full test report.

**Comment by boegel** [comment]
Going in, thanks @Flamefire!

**Pull request merged**
