### PR TITLE
Add Amber14 easyconfig and patch

### PR DESCRIPTION
**Pull request by thiell**
Work with EB available at ~~https://github.com/hpcugent/easybuild-easyblocks/pull/878~~ ~~https://github.com/hpcugent/easybuild-easyblocks/pull/958~~

### CODE REVIEW

**Comment by boegel** [comment]
@thiell I'm playing with this, how long does this need to install, including tests?

**Comment by thiell** [comment]
@boegel  I checked the easybuild log and it took me ~2h45 to install and test

**Comment by boegel** [comment]
@thiell hmm, for me `make test` seems to be hanging, or at least taking a *long* time (>9 hours)... Did you ever see a problem like that?

**Comment by boegel** [comment]
Some more details on the hang...

One of the (serial) tests hangs, more specifically `/Test.1p7e`:

```
vsc40023  86483  0.0  0.0 261168 40372 pts/1    S+   15:04   0:04          \_ python2 -m easybuild.main Amber-14-AmberTools-15-intel-2016a.eb -d --include-easyblocks /user/home/gent/vsc400/vsc40023/data/amber.py -f
vsc40023  29559  0.0  0.0 101364  1192 pts/1    S+   15:43   0:00              \_ make test
vsc40023  29564  0.0  0.0 106240  1476 pts/1    S+   15:43   0:00                  \_ /bin/sh -c (cd AmberTools/test && make test)
vsc40023  29565  0.0  0.0 106240   972 pts/1    S+   15:43   0:00                      \_ /bin/sh -c (cd AmberTools/test && make test)
vsc40023  29566  0.0  0.0 101364  1248 pts/1    S+   15:43   0:00                          \_ make test
vsc40023  29567  0.0  0.0 106376  1708 pts/1    S+   15:43   0:00                              \_ /bin/sh ./test_at_serial.sh
vsc40023  29579  0.0  0.0 101344  1268 pts/1    S+   15:44   0:00                                  \_ make -k -f Makefile test.serial
vsc40023  38674  0.0  0.0 106240  1572 pts/1    S+   15:53   0:00                                  |   \_ /bin/sh -c cd mdgx/1p7e && ./Test.1p7e
vsc40023  38675  0.0  0.0 106240  1644 pts/1    S+   15:53   0:00                                  |       \_ /bin/bash ./Test.1p7e
vsc40023  38680  100  0.3 396884 222228 pts/1   R+   15:53  44:54                                  |           \_ /<prefix>/software/Amber/14-intel-2016a/bin/mdgx -O -i mdgx.in
vsc40023  29580  0.0  0.0 100960   724 pts/1    S+   15:44   0:00                                  \_ tee /<prefix>/software/Amber/14-intel-2016a/logs/test_at_serial/2016-06-08_15-43-55.log
```

`mdgx` is writing to a log file in `<prefix>/software/Amber/14-intel-2016a/logs/test_at_serial/2016-06-08_15-43-55.log` that contains this:

```
<++>-----------------------------------------------------------------------<++>
<++> mdgx: A molecular dynamics engine in the AMBER suite of programs      <++>
<++>                                                                       <++>
<++> Written by David S. Cerutti, Case Group (2009)                        <++>
<++>-----------------------------------------------------------------------<++>

Run on Wed Jun  8 15:53:52 2016

INPUT FILE ASSIGNMENTS:
 Designation         Base name                                       Suffix
 -----------------   ---------------------------------------------   ----------
 Input File          mdgx.in                                         NONE
 Input Coordinates   inpcrd                                          NONE
 Topology            prmtop                                          NONE

OUTPUT FILE ASSIGNMENTS:
 Designation         Base name                                       Suffix
 -----------------   ---------------------------------------------   ----------
 State Information   gb3                                             .out    
 Restart file        gb3                                             .rst    

!!! Output overwriting is ENABLED !!!
<++>-----------------------------------------------------------------------<++>

INPUT LINE TEXT:

/user/scra

```

followed by a gazillion empty lines (after running for 45m):

```
$ wc -l /user/scratchdelcatty/gent/gvo000/gvo00002/vsc40023/easybuild_REGTEST/SL6/sandybridge/software/Amber/14-intel-2016a/AmberTools/test/mdgx/1p7e/gb30.out
16869489392 

$ ls -lh /user/scratchdelcatty/gent/gvo000/gvo00002/vsc40023/easybuild_REGTEST/SL6/sandybridge/software/Amber/14-intel-2016a/AmberTools/test/mdgx/1p7e/gb30.out
-rw-rw-r-- 1 vsc40023 vsc40023 16G Jun  8 16:43 /user/scratchdelcatty/gent/gvo000/gvo00002/vsc40023/easybuild_REGTEST/SL6/sandybridge/software/Amber/14-intel-2016a/AmberTools/test/mdgx/1p7e/gb30.out
```

I'm only seeing this when installing Amber on our GPFS filesystem, **not** when installing to `/dev/shm`.

This may be related to long path, since Amber has had problems with that before (cfr. http://dev-archive.ambermd.org/201003/0322.html), but also to an issue with our GPFS filesystem (wouldn't be the first time).

I'm not sure how to fix this (other than not installing to GPFS, maybe)...

**Comment by boegel** [comment]
I just tried installing Amber to a very long path in `/dev/shm`, and I'm seeing the same problem with the hanging test producing tons of output (well, empty lines). So, this is not related to installing to GPFS, but to installing to a long(ish) path.

On the other hand, the full path to the test log isn't *that* long...

```
$ export FULLPATH=/user/scratchdelcatty/gent/gvo000/gvo00002/vsc40023/easybuild_REGTEST/SL6/sandybridge/software/Amber/14-intel-2016a/AmberTools/test/mdgx/1p7e/gb30.out
$ echo $FULLPATH | wc -c
151
```

**Comment by boegel** [comment]
Valgrind output for the hanging test on a debug build of Amber:

```
cd mdgx/1p7e && ./Test.1p7e
==91097== Memcheck, a memory error detector
==91097== Copyright (C) 2002-2013, and GNU GPL'd, by Julian Seward et al.
==91097== Using Valgrind-3.9.0 and LibVEX; rerun with -h for copyright info
==91097== Command: /dev/shm/vsc40023/thisisareallylongpaththatshouldmakeoneofthetestsfailoratleasthangabit/software/Amber/14-intel-2016a/bin/mdgx -O -i mdgx.in
==91097==
==91097== Conditional jump or move depends on uninitialised value(s)
==91097==    at 0x4C2923A: strncpy (mc_replace_strmem.c:477)
==91097==    by 0x4FA3DB: PrintParagraph (Manual.c:156)
==91097==    by 0x43C6A0: OpenDiagnosticsFile (Trajectory.c:636)
==91097==    by 0x43EFBF: WriteDiagnostics (Trajectory.c:1235)
==91097==    by 0x4F48C4: WriteTrajFiles (Integrator.c:561)
==91097==    by 0x4F5F7E: InitVelocities (Integrator.c:749)
==91097==    by 0x55487B: main (mdgx.c:693)
==91097==
==91097== Conditional jump or move depends on uninitialised value(s)
==91097==    at 0x4C2928D: strncpy (mc_replace_strmem.c:120)
==91097==    by 0x4FA3DB: PrintParagraph (Manual.c:156)
==91097==    by 0x43C6A0: OpenDiagnosticsFile (Trajectory.c:636)
==91097==    by 0x43EFBF: WriteDiagnostics (Trajectory.c:1235)
==91097==    by 0x4F48C4: WriteTrajFiles (Integrator.c:561)
==91097==    by 0x4F5F7E: InitVelocities (Integrator.c:749)
==91097==    by 0x55487B: main (mdgx.c:693)
==91097==
==91097== Conditional jump or move depends on uninitialised value(s)
==91097==    at 0x4C292FA: strncpy (mc_replace_strmem.c:477)
==91097==    by 0x4FA3DB: PrintParagraph (Manual.c:156)
==91097==    by 0x43C6A0: OpenDiagnosticsFile (Trajectory.c:636)
==91097==    by 0x43EFBF: WriteDiagnostics (Trajectory.c:1235)
==91097==    by 0x4F48C4: WriteTrajFiles (Integrator.c:561)
==91097==    by 0x4F5F7E: InitVelocities (Integrator.c:749)
==91097==    by 0x55487B: main (mdgx.c:693)
==91097==
==91097== Use of uninitialised value of size 8
==91097==    at 0x4FA3F1: PrintParagraph (Manual.c:157)
==91097==    by 0x43C6A0: OpenDiagnosticsFile (Trajectory.c:636)
==91097==    by 0x43EFBF: WriteDiagnostics (Trajectory.c:1235)
==91097==    by 0x4F48C4: WriteTrajFiles (Integrator.c:561)
==91097==    by 0x4F5F7E: InitVelocities (Integrator.c:749)
==91097==    by 0x55487B: main (mdgx.c:693)
==91097==
==91097== Use of uninitialised value of size 8
==91097==    at 0x4FA36A: PrintParagraph (Manual.c:146)
==91097==    by 0x43C6A0: OpenDiagnosticsFile (Trajectory.c:636)
==91097==    by 0x43EFBF: WriteDiagnostics (Trajectory.c:1235)
==91097==    by 0x4F48C4: WriteTrajFiles (Integrator.c:561)
==91097==    by 0x4F5F7E: InitVelocities (Integrator.c:749)
==91097==    by 0x55487B: main (mdgx.c:693)
==91097==
==91097== Use of uninitialised value of size 8
==91097==    at 0x4FA397: PrintParagraph (Manual.c:150)
==91097==    by 0x43C6A0: OpenDiagnosticsFile (Trajectory.c:636)
==91097==    by 0x43EFBF: WriteDiagnostics (Trajectory.c:1235)
==91097==    by 0x4F48C4: WriteTrajFiles (Integrator.c:561)
==91097==    by 0x4F5F7E: InitVelocities (Integrator.c:749)
==91097==    by 0x55487B: main (mdgx.c:693)
==91097==
==91097==
==91097== More than 10000000 total errors detected.  I'm not reporting any more.
==91097== Final error counts will be inaccurate.  Go fix your program!
==91097== Rerun with --error-limit=no to disable this cutoff.  Note
==91097== that errors may occur in your program without prior warning from
==91097== Valgrind, because errors are no longer being displayed.
==91097== 
```

**Comment by thiell** [comment]
@boegel that's a bummer, but I haven't seen this problem (using /dev/shm and/or nfs share)

**Comment by boegel** [comment]
@thiell I'm discussing this with one of the AmberTools devs after I reported it on the Amber mailing list, he looking into a fix as we speak...

**Comment by boegel** [comment]
The bug is resolved using this patch:

```diff
--- amber14/AmberTools/src/mdgx/Manual.c.orig	2016-06-10 11:39:47.719576723 +0200
+++ amber14/AmberTools/src/mdgx/Manual.c	2016-06-10 11:41:16.670677715 +0200
@@ -142,9 +142,10 @@
   endfound = 0;
   j = 0;
   while (endfound == 0) {
+    vpivot = j + width;
     for (i = 0; i < width; i++) {
       if (vpar[j+i] == ' ') {
-	i++;
+        i++;
         vpivot = j+i;
       }
       if (vpar[j+i] == '\0') {
```

**Comment by boegel** [comment]
@thiell Amber easyblock is meged (cfr. https://github.com/hpcugent/easybuild-easyblocks/pull/958) and my version of this using `intel/2016a` is merged (cfr. #3200)

Shall we try and get this PR merged in too?

First step is the sync this with current `develop`, you'll probably run into a trivial conflict on the Amber patches, since I added some comments on top.

**Comment by boegel** [comment]
@thiell ping?

**Comment by migueldiascosta** [comment]
@thiell, this PR is being closed for the following reason(s): no activity for > 6 months, obsoleted by more recent PRs.
Please don't hesitate to reopen this PR or add a comment if you feel this contribution is still relevant.
For more information on our policy w.r.t. closing PRs, see https://easybuild.readthedocs.io/en/latest/Contributing.html#why-a-pull-request-may-be-closed-by-a-maintainer

**Pull request closed without merging**
