### PR TITLE
{bio}[GCC/12.3.0,gompi/2023a] EvidentialGene v2023.07.15, Exonerate v2.4.0

### PR DESCRIPTION
**Pull request by pavelToman**
(created using `eb --new-pr`)
resolves https://github.com/vscentrum/vsc-software-stack/issues/367

Requires CD-HIT from:
- [x] https://github.com/easybuilders/easybuild-easyconfigs/pull/21016 

resolves https://github.com/vscentrum/vsc-software-stack/issues/367

### CODE REVIEW

**Comment by pavelToman** [comment]
@boegelbot please test @ generoso

**Comment by pavelToman** [comment]
@boegelbot please test @ jsc-zen3

**Comment by laraPPr** [comment]
Test report by @laraPPr
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in total)
node3541.doduo.os - Linux RHEL 8.8, x86_64, AMD EPYC 7552 48-Core Processor, Python 3.11.3
See https://gist.github.com/laraPPr/a1e2739fb0d173502ed5252c3f86445a for a full test report.

**Review by laraPPr — APPROVED** [review]
lgtm

**Comment by laraPPr** [comment]
Going in, thanks @pavelToman!

**Pull request merged**
