### PR TITLE
{lang}[foss/2019b and fosscuda/2019b] R v3.6.2, added rstan as a core package.

### PR DESCRIPTION
**Pull request by terjekv**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by terjekv** [comment]
Sigh. Due to CRAN some other checksums got updated. Sorry. :-(

**Comment by lexming** [comment]
@terjekv I've synced your PR with current `develop` to proceed with the tests

**Comment by lexming** [comment]
LGTM

**Comment by lexming** [comment]
Test report by @lexming
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
login2.cerberus.os - Linux centos linux 7.7.1908, Intel(R) Xeon(R) Gold 6126 CPU @ 2.60GHz, Python 2.7.5
See https://gist.github.com/cfc8a0df7f35de43ac115ede1ada8d12 for a full test report.

**Comment by lexming** [comment]
Test report by @lexming
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
node254.hydra.os - Linux centos linux 7.7.1908, Intel(R) Xeon(R) CPU E5-2683 v4 @ 2.10GHz, Python 2.7.5
See https://gist.github.com/4b6740d0fef42b628529c6bbaaa025a9 for a full test report.

**Comment by lexming** [comment]
Going in, thanks @terjekv !

**Pull request merged**
