### PR TITLE
Update LAMMPS 23Jun2022 for latest bugfix sources

### PR DESCRIPTION
**Pull request by ocaisa**
We haven't made a release yet and the first update for the latest stable version of LAMMPS has landed, so makes sense to update the sources

### CODE REVIEW

**Comment by SebastianAchilles** [comment]
@boegelbot please test @ jsc-zen2

**Comment by ocaisa** [comment]
Test report by @ocaisa
Using easyblocks from PR(s) https://github.com/easybuilders/easybuild-easyblocks/pull/2765
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in total)
login1 - Linux Rocky Linux 8.5, x86_64, Intel(R) Xeon(R) CPU E5-2690 v3 @ 2.60GHz, Python 3.6.8
See https://gist.github.com/d844f4543fd95453f4c984983d25e034 for a full test report.

**Review by SebastianAchilles — APPROVED** [review]
lgtm

**Comment by SebastianAchilles** [comment]
Going in, thanks @ocaisa!

**Comment by boegel** [comment]
Test report by @boegel
**FAILED**
Build succeeded for 0 out of 10 (2 easyconfigs in total)
node3131.skitty.os - Linux CentOS Linux 7.9.2009, x86_64, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz (skylake_avx512), Python 2.7.5
See https://gist.github.com/e7119e15a7887082e5edffe9001b1992 for a full test report.

**Pull request merged**
