### PR TITLE
{tools}[GCCcore/12.3.0] Parsl v2024.4.22

### PR DESCRIPTION
**Pull request by smoors**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by smoors** [comment]
Test report by @smoors
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
node300.hydra.os - Linux Rocky Linux 8.8, x86_64, Intel(R) Xeon(R) Gold 6148 CPU @ 2.40GHz (skylake_avx512), Python 3.6.8
See https://gist.github.com/smoors/833d833b8aeecd0db3e48e205fa4cf88 for a full test report.

**Comment by smoors** [comment]
@boegelbot: please test @ generoso

**Comment by smoors** [comment]
@boegelbot please test @ jsc-zen3

**Review by lexming — APPROVED** [review]
LGTM

**Comment by lexming** [comment]
Merging, thanks @smoors !

**Pull request merged**
