### PR TITLE
{bio}[foss/2019a] Biopython v1.74 w/ Python 2.7.15 + 3.7.2

### PR DESCRIPTION
**Pull request by Darkless012**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by Darkless012** [comment]
Test report by @Darkless012
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
node3241.victini.os - Linux centos linux 7.6.1810, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz, Python 2.7.5
See https://gist.github.com/9719a23eca4abdaefe09b875eb2415d9 for a full test report.

**Comment by Darkless012** [comment]
I will update also the source_urls. Can't find the example but I would swear that one of the homepages from this batch had self-signed cert.

**Comment by migueldiascosta** [comment]
@Darkless012 following up on @Micket's comments on slack, if this only depends on `Python`, it could be moved down to `GCCcore`... but its documentation says it uses `numpy`, in which case it should depend on `Scipy-Bundle` and hence remain in `foss`... (?)

`multi_deps` for Python 2 and 3 seems to be an option, but then again, if it is to depend on `Scipy-Bundle`, its use of `multi_deps` moving forward is not yet clear... (?)

**Comment by Darkless012** [comment]
Inclusion of `SciPy-bundle` will make run more tests to actually run. Although Numpy is optional dependency, it seems that lot of the functionality is supported with Numpy included. With that mentioned I should probably use foss-2019a with multideps, which compiled OK and could be used in CONCOCT as dep.

**Comment by Micket** [comment]
Test report by @Micket
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
vera-c1 - Linux centos linux 7.7.1908, Intel Xeon Processor (Skylake), Python 2.7.5
See https://gist.github.com/9f6551dd8cefba528d976138fcae370f for a full test report.

**Comment by Micket** [comment]
Going in, thanks @Darkless012!

**Pull request merged**
