### PR TITLE
{lib}[GCCcore/13.3.0] SQLAlchemy v2.0.36

### PR DESCRIPTION
**Pull request by lcniel**
(created using `eb --new-pr`)

Requires:
- [x] #21818
- [x] #21820

### CODE REVIEW

**Comment by lcniel** [comment]
Test report by @lcniel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
vera06-4 - Linux Rocky Linux 8.9, x86_64, Intel(R) Xeon(R) Gold 6130 CPU @ 2.10GHz, Python 3.6.8
See https://gist.github.com/lcniel/170354e2d56856cd252a3e56d3502eca for a full test report.

**Comment by SebastianAchilles** [comment]
@boegelbot please test @ jsc-zen3

**Comment by SebastianAchilles** [comment]
@boegelbot please test @ generoso

**Comment by SebastianAchilles** [comment]
Going in, thanks @lcniel!

**Pull request merged**
