### PR TITLE
{math}[foss/2022a] ExtremeLy v2.3.0, lmoments3 v1.0.6, scikit-extremes v2022.4.10

### PR DESCRIPTION
**Pull request by pavelToman**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by pavelToman** [comment]
@boegelbot please test @ generoso

**Comment by pavelToman** [comment]
@boegelbot please test @ jsc-zen3

**Review by boegel — APPROVED** [review]
lgtm

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 3 out of 3 (3 easyconfigs in total)
node3129.skitty.os - Linux RHEL 8.8, x86_64, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz, Python 3.6.8
See https://gist.github.com/boegel/e44ac5d3b3cc9c34657ed11c193aae09 for a full test report.

**Comment by boegel** [comment]
Going in, thanks @pavelToman!

**Pull request merged**
