### PR TITLE
{vis}[foss/2021a] Nipype v1.8.5, RDFlib v6.2.0 w/ Python 3.9.5

### PR DESCRIPTION
**Pull request by boegel**
(created using `eb --new-pr`)

WIP, need to update this to latest Nipype 1.8.5, but the new `looseversion` required dependency is causing trouble (see https://github.com/effigies/looseversion/issues/7)

### CODE REVIEW

**Comment by boegel** [comment]
@boegelbot please test @ generoso

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in total)
node3145.skitty.os - Linux RHEL 8.4, x86_64, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz (skylake_avx512), Python 3.6.8
See https://gist.github.com/e2174ba40d2a90ebc5b7c07b7f790b81 for a full test report.

**Comment by jfgrimm** [comment]
Test report by @jfgrimm
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in total)
node109.pri.viking.alces.network - Linux CentOS Linux 7.9.2009, x86_64, Intel(R) Xeon(R) Gold 6138 CPU @ 2.00GHz (skylake_avx512), Python 3.6.8
See https://gist.github.com/c563a3f769a9591c9943b64ebc1aae17 for a full test report.

**Comment by verdurin** [comment]
Test report by @verdurin
**SUCCESS**
Build succeeded for 3 out of 3 (2 easyconfigs in total)
easybuild-c7.novalocal - Linux CentOS Linux 7.9.2009, x86_64, Intel Xeon Processor (Skylake, IBRS), Python 3.6.8
See https://gist.github.com/db898ba2d017bc010182e9634c5c6b8f for a full test report.

**Review by verdurin — APPROVED** [review]
Looks fine.

**Comment by verdurin** [comment]
@boegel the `zen2` test didn't appear to run - I'm happy to merge anyway, but let me know if you prefer to see a successful build there.

**Comment by boegel** [comment]
@boegelbot please test @ jsc-zen2

**Comment by boegel** [comment]
> @boegel the `zen2` test didn't appear to run - I'm happy to merge anyway, but let me know if you prefer to see a successful build there.

@verdurin That was probably just a Gremlin biting the cables (everything actually got installed, but the test report didn't make it through)

**Comment by verdurin** [comment]
Going in, thanks @boegel!

**Pull request merged**
