### PR TITLE
add Zip as build dependency for recent Bazel versions

### LINKED ISSUE #9962: Bazel-0.26.1-GCCcore-8.3.0.eb missing zip as dependency
Bazel-0.26.1-GCCcore-8.3.0.eb fails with the following error:
```
^MESC[1AESC[KESC[31mESC[1mERROR: ESC[0m/trinity/shared/easybuild/build/Bazel/0.26.1/GCCcore-8.3.0/src/BUILD:339:2: Executing genrule //src:package-zip_nojdk failed (Exit 127): bash failed: error executing command
  (cd /tmp/eb-0CJXT7/bazel_M82PHrmR/out/execroot/io_bazel && \
  exec env - \
    LD_LIBRARY_PATH=/trinity/shared/easybuild/software/Java/1.8.0_192/lib:/trinity/shared/easybuild/software/Python/3.7.4-GCCcore-8.3.0/lib:/trinity/shared/easybuild/software/libffi/3.2.1-GCCcore-8.3.0/lib64:/trinity/shared/easybuild/software/libffi/3.2.1-GCCcore-8.3.0/lib:/trinity/shared/easybuild/software/GMP/6.1.2-GCCcore-8.3.0/lib:/trinity/shared/easybuild/software/XZ/5.2.4-GCCcore-8.3.0/lib:/trinity/shared/easybuild/software/SQLite/3.29.0-GCCcore-8.3.0/lib:/trinity/shared/easybuild/software/Tcl/8.6.9-GCCcore-8.3.0/lib:/trinity/shared/easybuild/software/libreadline/8.0-GCCcore-8.3.0/lib:/trinity/shared/easybuild/software/ncurses/6.1-GCCcore-8.3.0/lib:/trinity/shared/easybuild/software/bzip2/1.0.8-GCCcore-8.3.0/lib:/trinity/shared/easybuild/software/binutils/2.32-GCCcore-8.3.0/lib:/trinity/shared/easybuild/software/zlib/1.2.11-GCCcore-8.3.0/lib:/trinity/shared/easybuild/software/GCCcore/8.3.0/lib/gcc/x86_64-pc-linux-gnu/8.3.0:/trinity/shared/easybuild/software/GCCcore/8.3.0/lib64:/trinity/shared/easybuild/software/GCCcore/8.3.0/lib \
    PATH=/trinity/shared/easybuild/software/Java/1.8.0_192:/trinity/shared/easybuild/software/Java/1.8.0_192/bin:/trinity/shared/easybuild/software/Python/3.7.4-GCCcore-8.3.0/bin:/trinity/shared/easybuild/software/XZ/5.2.4-GCCcore-8.3.0/bin:/trinity/shared/easybuild/software/SQLite/3.29.0-GCCcore-8.3.0/bin:/trinity/shared/easybuild/software/Tcl/8.6.9-GCCcore-8.3.0/bin:/trinity/shared/easybuild/software/ncurses/6.1-GCCcore-8.3.0/bin:/trinity/shared/easybuild/software/bzip2/1.0.8-GCCcore-8.3.0/bin:/trinity/shared/easybuild/software/binutils/2.32-GCCcore-8.3.0/bin:/trinity/shared/easybuild/software/GCCcore/8.3.0/bin:/trinity/shared/easybuild/software/EasyBuild/4.1.1/bin:/trinity/shared/zedat/bin:/usr/local/bin:/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/usr/bin/syscfg:/trinity/home/build/.local/bin:/trinity/home/build/bin \
  /bin/bash -c 'source external/bazel_tools/tools/genrule/genrule-setup.sh; src/package-bazel.sh bazel-out/k8-opt/bin/src/package_nojdk.zip  bazel-out/k8-opt/bin/src/embedded_tools_nojdk.zip bazel-out/k8-opt/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar bazel-out/k8-opt/bin/src/install_base_key_nojdk bazel-out/k8-opt/bin/src/main/native/libunix.so bazel-out/k8-opt/bin/src/main/tools/build-runfiles bazel-out/k8-opt/bin/src/main/tools/process-wrapper src/main/tools/jdk.BUILD bazel-out/k8-opt/bin/src/main/tools/linux-sandbox bazel-out/k8-opt/bin/tools/osx/xcode-locator bazel-out/k8-opt/bin/src/main/tools/daemonize')
Execution platform: @bazel_tools//platforms:host_platform
ESC[32m[1,793 / 1,794]ESC[0m checking cached actions
^MESC[1AESC[Ksrc/package-bazel.sh: line 42: zip: command not found
```
Thus, zip should be added as a dependency.

### PR DESCRIPTION
**Pull request by boegel**
fixes #9962

requires ~~#9958~~ + ~~#9971~~ for `Zip`

### CODE REVIEW

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 7 out of 7 (7 easyconfigs in this PR)
node2569.golett.os - Linux centos linux 7.7.1908, Intel(R) Xeon(R) CPU E5-2680 v3 @ 2.50GHz, Python 2.7.5
See https://gist.github.com/96dda21fb9d99a2dc1ff836bdf8f35f2 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 7 out of 7 (7 easyconfigs in this PR)
node3104.skitty.os - Linux centos linux 7.7.1908, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz, Python 3.6.8
See https://gist.github.com/8121e302ff9c3fd0cf925bd47b008aea for a full test report.

**Comment by lexming** [comment]
Test report by @lexming
**SUCCESS**
Build succeeded for 7 out of 7 (7 easyconfigs in this PR)
login2.cerberus.os - Linux centos linux 7.7.1908, Intel(R) Xeon(R) Gold 6126 CPU @ 2.60GHz, Python 2.7.5
See https://gist.github.com/bb94c432836083e105740c2df4efdac2 for a full test report.

**Comment by lexming** [comment]
Going in, thanks @boegel !

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 8 out of 8 (7 easyconfigs in this PR)
generoso-1 - Linux centos linux 7.6.1810, Intel(R) Xeon(R) CPU E5-2660 v4 @ 2.00GHz, Python 3.6.8
See https://gist.github.com/0e96244ba454a302f7ecda6381da77db for a full test report.

**Pull request merged**
