### PR TITLE
{data}[gompi/2022a] netCDF-Fortran v4.6.0 

### PR DESCRIPTION
**Pull request by sassy-crick**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by sassy-crick** [comment]
I marked it as WIB as it is building ok on my laptop (11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz) yet it fails to build on both `11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz` and `AMD EPYC 7742 64-Core Processor` with:
> checking size of off_t... configure: error: in `/dev/shm/jsassman/netCDFFortran/4.6.0/gompi-2022a/netcdf-fortran-4.6.0':
configure: error: cannot compute sizeof (off_t)
See `config.log' for more details
 (at easybuild/tools/run.py:618 in parse_cmd_output)

`config.log` contains:
>  static long int longval (void) { return (long int) (sizeof (off_t)); }
| static unsigned long int ulongval (void) { return (long int) (sizeof (off_t)); }
| #include <stdio.h>
| #include <stdlib.h>
| int
| main (void)
| {
| 
|   FILE *f = fopen ("conftest.val", "w");
|   if (! f)
|     return 1;
|   if (((long int) (sizeof (off_t))) < 0)
|     {
|       long int i = longval ();
|       if (i != ((long int) (sizeof (off_t))))
|       return 1;
|       fprintf (f, "%ld", i);
|     }
|   else
|     {
|       unsigned long int i = ulongval ();
|       if (i != ((long int) (sizeof (off_t))))
|       return 1;
|       fprintf (f, "%lu", i);
|     }
|   /* Do not output a trailing newline, as this causes \r\n confusion
|      on some platforms.  */
|   return ferror (f) || fclose (f) != 0;
| 
|   ;
|   return 0;
| }
configure:25119: error: in `/dev/shm/jsassman/netCDFFortran/4.6.0/gompi-2022a/netcdf-fortran-4.6.0':
configure:25121: error: cannot compute sizeof (off_t)
See `config.log' for more details

Can somebody confirm that or is that my setup? Note: it fails both within and outside the Singularity container.

**Comment by sassy-crick** [comment]
As suggested by @branfosj `bzip2` is required which sorts this problem. WIP removed as it builds now.

**Comment by SebastianAchilles** [comment]
@boegelbot please test @ generoso

**Comment by SebastianAchilles** [comment]
@boegelbot please test @ jsc-zen2

**Comment by SebastianAchilles** [comment]
Test report by @sebastianachilles
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
bdw-opensuse-154 - Linux openSUSE Leap 15.4, x86_64, Intel(R) Core(TM) i7-6900K CPU @ 3.20GHz (broadwell), Python 3.6.15
See https://gist.github.com/496a67316f75c67e1ebb60ad0aa89a0e for a full test report.

**Review by SebastianAchilles — APPROVED** [review]
lgtm

**Comment by SebastianAchilles** [comment]
Going in, thanks @sassy-crick!

**Pull request merged**
