### PR TITLE
{bio}[GCCcore/12.2.0] NanoCaller v3.6.0, WFA2 v2.3.4, vcflib v1.0.9, ... w/ R 4.2.2

### PR DESCRIPTION
**Pull request by verdurin**
(created using `eb --new-pr`)

Apologies for the number of easyconfigs - thought it would overall be less work than lots of PRs, given they're mostly simple backports.

### CODE REVIEW

**Comment by verdurin** [comment]
Test report by @verdurin
**SUCCESS**
Build succeeded for 10 out of 10 (10 easyconfigs in total)
easybuild-c7.novalocal - Linux CentOS Linux 7.9.2009, x86_64, Intel Xeon Processor (Skylake, IBRS), Python 3.6.8
See https://gist.github.com/verdurin/1739ec3573d46f5b17551d97978b9fab for a full test report.

**Comment by smoors** [comment]
@boegelbot: please test @ generoso

**Comment by smoors** [comment]
@boegelbot please test @ jsc-zen3

**Review by smoors — APPROVED** [review]
lgtm

**Comment by smoors** [comment]
Going in, thanks @verdurin!

**Pull request merged**
