### PR TITLE
{bio}[GCCcore/12.2.0,foss/2022b] HMMER v3.3.2, BUSCO v5.4.7, prodigal v2.6.3, ... w/ Python 3.10.8

### PR DESCRIPTION
**Pull request by eylenth**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by eylenth** [comment]
see #18096, #18094 and #18099 for missing dependencies.

**Comment by eylenth** [comment]
missing dependencies are now available

**Comment by smoors** [comment]
@boegelbot: please test @ generoso

**Comment by smoors** [comment]
@boegelbot please test @ jsc-zen2

**Review by smoors — APPROVED** [review]
lgtm

**Pull request merged**
