### PR TITLE
Enable LittleCMS2 and WebP support in recent Pillow

### LINKED ISSUE #14505: Pillow has no support for WEBP
`/easybuild/2020/software/Pillow/8.0.1-GCCcore-10.2.0/lib/python3.8/site-packages/PIL/Image.py:2942: UserWarning: image file could not be identified because WEBP support not installed`

That's actually important when using PIL on machine learning and scraping the web.

### PR DESCRIPTION
**Pull request by Micket**
(created using `eb --new-pr`)

Because why not; we already have this deps to adding it was trivial (I have confirmed it's working as well).

Fixes #14505

### CODE REVIEW

**Comment by Micket** [comment]
@boegelbot please test @ generoso

**Comment by Micket** [comment]
Test report by @Micket
**SUCCESS**
Build succeeded for 3 out of 3 (3 easyconfigs in total)
alvis-skylake-build - Linux Rocky Linux 8.9, x86_64, Intel Xeon Processor (Skylake, IBRS, no TSX), Python 3.6.8
See https://gist.github.com/Micket/606bb8c11a2b6d6f0c0b89fdf6423734 for a full test report.

**Comment by Micket** [comment]
@boegelbot please test @ jsc-zen3

**Review by casparvl — APPROVED** [review]
Lgtm!

**Comment by casparvl** [comment]
Test report by @casparvl
**SUCCESS**
Build succeeded for 8 out of 8 (3 easyconfigs in total)
tcn1.local.snellius.surf.nl - Linux RHEL 8.6, x86_64, AMD EPYC 7H12 64-Core Processor, Python 3.6.8
See https://gist.github.com/casparvl/1e687510e06315ebe5a62e3abaef140d for a full test report.

**Comment by casparvl** [comment]
Going in, thanks @Micket!

**Pull request merged**
