### PR TITLE
{tools}[dummy] GC3Pie 2.5.0 + deps

### PR DESCRIPTION
**Pull request by boegel**
(created using `eb --new-pr`)

cc @@riccardomurri :)

### CODE REVIEW

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 5 out of 5 (5 easyconfigs in this PR)
node3170.skitty.os - Linux centos linux 7.4.1708, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz, Python 2.7.5
See https://gist.github.com/11609d5d51d694bf417f268ec5f4f3ed for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 5 out of 5 (5 easyconfigs in this PR)
node2426.golett.os - Linux centos linux 7.4.1708, Intel(R) Xeon(R) CPU E5-2680 v3 @ 2.50GHz, Python 2.7.5
See https://gist.github.com/4827303eebad1f76ba6313a8d6be36df for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 5 out of 5 (5 easyconfigs in this PR)
node2062.delcatty.os - Linux centos linux 7.5.1804, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.7.5
See https://gist.github.com/7af1adae73c3ed7a4c2cfb0a53aecd72 for a full test report.

**Comment by akesandgren** [comment]
Test report by @akesandgren
**FAILED**
Build succeeded for 4 out of 5 (5 easyconfigs in this PR)
b-cn1522.hpc2n.umu.se - Linux ubuntu 16.04, Intel(R) Xeon(R) Gold 6132 CPU @ 2.60GHz, Python 2.7.12
See https://gist.github.com/8565a469fb9c722c2e209878a8cff0dd for a full test report.

**Comment by migueldiascosta** [comment]
Test report by @migueldiascosta
**FAILED**
Build succeeded for 3 out of 5 (5 easyconfigs in this PR)
grc-cluster1 - Linux centos 6.9, Intel(R) Xeon(R) CPU E5-2640 0 @ 2.50GHz, Python 2.7.14
See https://gist.github.com/a00df5a552d629ed53ac3aa4fa8a3dcd for a full test report.

**Comment by migueldiascosta** [comment]
the problem in my test report may be too site specific - I'm running easybuild with python 2.7 but the system python is 2.6...

**Comment by vanzod** [comment]
Test report by @vanzod
**FAILED**
Build succeeded for 4 out of 5 (5 easyconfigs in this PR)
cermis - Linux debian 9.4, Intel(R) Xeon(R) CPU           E5620  @ 2.40GHz, Python 2.7.13
See https://gist.github.com/4a5c201f98855b479422b04bc0b00ace for a full test report.

**Comment by vanzod** [comment]
`python-daemon` requires `docutils` Python package. Maybe add a `osdependencies` check?
```
Traceback (most recent call last):
  File "setup.py", line 102, in <module>
    setup(**setup_kwargs)
  File "/usr/lib/python2.7/distutils/core.py", line 111, in setup
    _setup_distribution = dist = klass(attrs)
  File "/mnt/ramdisk/GC3Pie/2.5.0/dummy-/pythondaemon/python-daemon-2.2.0/version.py", line 652, in __init__
    super(ChangelogAwareDistribution, self).__init__(*args, **kwargs)
  File "build/bdist.linux-x86_64/egg/setuptools/dist.py", line 269, in __init__
  File "build/bdist.linux-x86_64/egg/setuptools/dist.py", line 313, in fetch_build_eggs
  File "build/bdist.linux-x86_64/egg/pkg_resources/__init__.py", line 826, in resolve
  File "build/bdist.linux-x86_64/egg/pkg_resources/__init__.py", line 1092, in best_match
  File "build/bdist.linux-x86_64/egg/pkg_resources/__init__.py", line 1104, in obtain
  File "build/bdist.linux-x86_64/egg/setuptools/dist.py", line 378, in fetch_build_egg
  File "/usr/lib/python2.7/distutils/cmd.py", line 109, in ensure_finalized
    self.finalize_options()
  File "build/bdist.linux-x86_64/egg/setuptools/command/easy_install.py", line 239, in finalize_options
    
  File "/mnt/ramdisk/GC3Pie/2.5.0/dummy-/pythondaemon/python-daemon-2.2.0/version.py", line 671, in get_version
    version_info = self.get_version_info()
  File "/mnt/ramdisk/GC3Pie/2.5.0/dummy-/pythondaemon/python-daemon-2.2.0/version.py", line 667, in get_version_info
    version_info = generate_version_info_from_changelog(changelog_path)
  File "/mnt/ramdisk/GC3Pie/2.5.0/dummy-/pythondaemon/python-daemon-2.2.0/version.py", line 495, in generate_version_info_from_changelog
    versions_all_json = changelog_to_version_info_collection(infile)
  File "/mnt/ramdisk/GC3Pie/2.5.0/dummy-/pythondaemon/python-daemon-2.2.0/version.py", line 450, in changelog_to_version_info_collection
    import docutils.core
ImportError: No module named docutils.core
```

**Comment by akesandgren** [comment]
Since python-daemon is in the ext-list for gc3pie, docutils should probably be there too if that is the solution.

**Comment by boegel** [comment]
@migueldiascosta For you it fails because there's no `lib*/python2.7/site-packages` in `/opt/apps/util/easybuild/software/PyYAML/3.13`, instead it's generating `lib/python2.6/site-packages`.

I'm trying to wrap my head around how this happen, ... Can you upload a full debug log for `PyYAML`?

@akesandgren, @vanzod: missing `docutils` (which we apparently have system-wide) has been added, please try again?

**Comment by akesandgren** [comment]
Test report by @akesandgren
**FAILED**
Build succeeded for 0 out of 1 (5 easyconfigs in this PR)
b-cn1522.hpc2n.umu.se - Linux ubuntu 16.04, Intel(R) Xeon(R) Gold 6132 CPU @ 2.60GHz, Python 2.7.12
See https://gist.github.com/2c529d9105da438cf678ff19061b71e7 for a full test report.

**Comment by vanzod** [comment]
Test report by @vanzod
**FAILED**
Build succeeded for 4 out of 5 (5 easyconfigs in this PR)
cermis - Linux debian 9.4, Intel(R) Xeon(R) CPU           E5620  @ 2.40GHz, Python 2.7.13
See https://gist.github.com/9c80728325620e9ebb564dd568a31dde for a full test report.

**Comment by akesandgren** [comment]
I think that libkrb5-dev (where gssapi.h comes from) should preferably be an os dep due to security concerns. Or one could try to disable the use of python-gssapi?

**Comment by boegel** [comment]
GSS support in paramiko is indeed optional, and it's probably not a bad idea anyway to disable it (see https://github.com/paramiko/paramiko/issues/584 + https://github.com/paramiko/paramiko/pull/861, which hasn't been merged after almost 2 years...).

@riccardomurri Any idea if GC3Pie relies on GSS support in `paramiko` in any way?

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 5 out of 5 (5 easyconfigs in this PR)
node2596.golett.os - Linux centos linux 7.5.1804, Intel(R) Xeon(R) CPU E5-2680 v3 @ 2.50GHz, Python 2.7.5
See https://gist.github.com/91ae18b3b63a114f4fb1d7c3237d4884 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 5 out of 5 (5 easyconfigs in this PR)
node3115.skitty.os - Linux centos linux 7.4.1708, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz, Python 2.7.5
See https://gist.github.com/c648ab08bb63509f4ca8ec4139a03300 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 5 out of 5 (5 easyconfigs in this PR)
node2061.delcatty.os - Linux centos linux 7.5.1804, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.7.5
See https://gist.github.com/9bb8131301093f5b813ff45badc3f8e2 for a full test report.

**Comment by akesandgren** [comment]
Test report by @akesandgren
**SUCCESS**
Build succeeded for 1 out of 1 (5 easyconfigs in this PR)
b-cn1522.hpc2n.umu.se - Linux ubuntu 16.04, Intel(R) Xeon(R) Gold 6132 CPU @ 2.60GHz, Python 2.7.12
See https://gist.github.com/13b5615a3c1ffbe8ab61527b69dd6ee7 for a full test report.

**Comment by riccardomurri** [comment]
> Any idea if GC3Pie relies on GSS support in paramiko in any way?

GC3Pie has no special reliance on GSSAPI support.  

GSSAPI is however, an authentication option for SSH (enabled by default on Debian/Ubuntu, disabled on other distros) so building Paramiko without GSSAPI support will lock you out of sites which *require* GSSAPI auth (which, I think, means they are using Kerberos 5 exclusively).  

I have never seen such a site. My guess is that GSSAPI is not a popular choice and the few sites using it can customize the `.eb` file to re-enable GSSAPI support; the rest of us has probably a easier time just disabling it and forgetting about the additional required C header files...

**Comment by akesandgren** [comment]
Test report by @akesandgren
**SUCCESS**
Build succeeded for 5 out of 5 (5 easyconfigs in this PR)
b-cn1522.hpc2n.umu.se - Linux ubuntu 16.04, Intel(R) Xeon(R) Gold 6132 CPU @ 2.60GHz, Python 2.7.12
See https://gist.github.com/422c02af486db962296079af184e3674 for a full test report.

**Comment by boegel** [comment]
@migueldiascosta That signals a bug, the path checked during the sanity check should be for the `python` that is used to the the installation (the `python` used to run EB shouldn't affect that).

Please open an issue for this in the easyblocks repo, it's a problem in `PythonPackage` that we should fix (but it shouldn't block this PR, you'll hit this with any `PythonPackage` easyconfig?).

**Comment by boegel** [comment]
@riccardomurri Thanks for clarifying. The `GSS` support in `paramiko` is messy because the latest `paramiko` version doesn't support the newer Python `GSS` bindings yet, see https://github.com/paramiko/paramiko/pull/861, so it makes sense to me to (temporarily?) disable those. Indeed, this can be rectified for sites that really need to have this.

**Comment by akesandgren** [comment]
Going in, thanks @boegel

**Pull request merged**
