### PR TITLE
update build dependencies for binutils 2.37 with system toolchain

### LINKED ISSUE #14727: GCC/11.2.0 does not compile on newer OS with glibc 2.34 due to M4/1.4.18
Bootstrapping `GCC/11.2.0` does not work on a Ubuntu 22.04 container with a new `glibc` version 2.34 due to a problem in `M4/1.4.18`. `M4/1.4.18` is currently a dependency for bootstrapping:
```
$ eb GCC-11.2.0.eb --robot -D
/usr/local/lib/python3.9/dist-packages/pep8.py:110: FutureWarning: Possible nested set at position 1
  EXTRANEOUS_WHITESPACE_REGEX = re.compile(r'[[({] | []}),;:]')
== Temporary log file in case of crash /tmp/eb-6_zucurc/easybuild-r1q36chv.log
Dry run: printing build status of easyconfigs and dependencies
CFGS=/easybuild/software/EasyBuild/20220114-dev/easybuild/easyconfigs
 * [ ] $CFGS/m/M4/M4-1.4.19.eb (module: M4/1.4.19)
 * [ ] $CFGS/z/zlib/zlib-1.2.11.eb (module: zlib/1.2.11)
 * [ ] $CFGS/m/M4/M4-1.4.18.eb (module: M4/1.4.18)
 * [ ] $CFGS/b/Bison/Bison-3.7.6.eb (module: Bison/3.7.6)
 * [ ] $CFGS/b/Bison/Bison-3.5.3.eb (module: Bison/3.5.3)
 * [ ] $CFGS/f/flex/flex-2.6.4.eb (module: flex/2.6.4)
 * [ ] $CFGS/b/binutils/binutils-2.37.eb (module: binutils/2.37)
 * [ ] $CFGS/g/GCCcore/GCCcore-11.2.0.eb (module: GCCcore/11.2.0)
 * [ ] $CFGS/z/zlib/zlib-1.2.11-GCCcore-11.2.0.eb (module: zlib/1.2.11-GCCcore-11.2.0)
 * [ ] $CFGS/h/help2man/help2man-1.48.3-GCCcore-11.2.0.eb (module: help2man/1.48.3-GCCcore-11.2.0)
 * [ ] $CFGS/m/M4/M4-1.4.19-GCCcore-11.2.0.eb (module: M4/1.4.19-GCCcore-11.2.0)
 * [ ] $CFGS/b/Bison/Bison-3.7.6-GCCcore-11.2.0.eb (module: Bison/3.7.6-GCCcore-11.2.0)
 * [ ] $CFGS/f/flex/flex-2.6.4-GCCcore-11.2.0.eb (module: flex/2.6.4-GCCcore-11.2.0)
 * [ ] $CFGS/b/binutils/binutils-2.37-GCCcore-11.2.0.eb (module: binutils/2.37-GCCcore-11.2.0)
 * [ ] $CFGS/g/GCC/GCC-11.2.0.eb (module: GCC/11.2.0)
 ```

The error is
```
In file included from /usr/include/signal.h:328,
                 from ./signal.h:52,
                 from c-stack.c:49:
c-stack.c:55:26: error: missing binary operator before token "("
   55 | #elif HAVE_LIBSIGSEGV && SIGSTKSZ < 16384
      |                          ^~~~~~~~
make[3]: *** [Makefile:1910: c-stack.o] Error 1
```

Test report: https://gist.github.com/cea16239037b480f4c37c8ffcee67be9

Related discussion: https://lists.gnu.org/archive/html/bug-m4/2021-03/msg00000.html

Patch (`04-fix-sigstksz.patch`) for `M4/1.4.18` is available in https://launchpad.net/ubuntu/+archive/primary/+sourcefiles/m4/1.4.18-5ubuntu1/m4_1.4.18-5ubuntu1.debian.tar.xz

Alternative solution would be to use `M4/1.4.19`.

System info:
```
$ eb --show-system-info
/usr/local/lib/python3.9/dist-packages/pep8.py:110: FutureWarning: Possible nested set at position 1
  EXTRANEOUS_WHITESPACE_REGEX = re.compile(r'[[({] | []}),;:]')
System information (zen2-ubuntu-eb):

* OS:
  -> name: Ubuntu
  -> type: Linux
  -> version: 22.04
  -> platform name: x86_64-unknown-linux

* CPU:
  -> vendor: AMD
  -> architecture: x86_64
  -> family: AMD
  -> arch name: zen2
  -> model: AMD EPYC 7452 32-Core Processor
  -> speed: 2350.0
  -> cores: 128
  -> features: 3dnowprefetch,abm,adx,aes,aperfmperf,apic,arat,avic,avx,avx2,bmi1,bmi2,bpext,cat_l3,cdp_l3,clflush,clflushopt,clwb,clzero,cmov,cmp_legacy,constant_tsc,cpb,cpuid,cqm,cqm_llc,cqm_mbm_local,cqm_mbm_total,cqm_occup_llc,cr8_legacy,cx16,cx8,de,decodeassists,extapic,extd_apicid,f16c,flushbyasid,fma,fpu,fsgsbase,fxsr,fxsr_opt,ht,hw_pstate,ibpb,ibrs,ibs,irperf,lahf_lm,lbrv,lm,mba,mca,mce,misalignsse,mmx,mmxext,monitor,movbe,msr,mtrr,mwaitx,nonstop_tsc,nopl,npt,nrip_save,nx,osvw,overflow_recov,pae,pat,pausefilter,pclmulqdq,pdpe1gb,perfctr_core,perfctr_llc,perfctr_nb,pfthreshold,pge,pni,popcnt,pse,pse36,rdpid,rdrand,rdseed,rdt_a,rdtscp,rep_good,sep,sev,sha_ni,skinit,smap,smca,sme,smep,ssbd,sse,sse2,sse4_1,sse4_2,sse4a,ssse3,stibp,succor,svm,svm_lock,syscall,tce,topoext,tsc,tsc_scale,umip,v_vmsave_vmload,vgif,vmcb_clean,vme,vmmcall,wbnoinvd,wdt,x2apic,xgetbv1,xsave,xsavec,xsaveerptr,xsaveopt,xsaves

* software:
  -> glibc version: 2.34
  -> Python binary: /usr/bin/python3
  -> Python version: 3.9.9
  ```

### PR DESCRIPTION
**Pull request by boegel**
(created using `eb --new-pr`)
fixes #14727

### CODE REVIEW

**Comment by boegel** [comment]
Before these changes:

```
$ eb binutils-2.37.eb -D
...
 * [ ] $CFGS/z/zlib/zlib-1.2.11.eb (module: zlib/1.2.11)
 * [ ] $CFGS/m/M4/M4-1.4.18.eb (module: M4/1.4.18)
 * [ ] $CFGS/b/Bison/Bison-3.7.6.eb (module: Bison/3.7.6)
 * [ ] $CFGS/b/Bison/Bison-3.5.3.eb (module: Bison/3.5.3)
 * [ ] $CFGS/f/flex/flex-2.6.4.eb (module: flex/2.6.4)
 * [ ] $CFGS/b/binutils/binutils-2.37.eb (module: binutils/2.37)
```

With these changes:

```
$ eb binutils-2.37.eb -D
...
 * [ ] $CFGS/z/zlib/zlib-1.2.11.eb (module: zlib/1.2.11)
 * [ ] $CFGS/m/M4/M4-1.4.19.eb (module: M4/1.4.19)
 * [ ] $CFGS/b/Bison/Bison-3.8.2.eb (module: Bison/3.8.2)
 * [ ] $CFGS/f/flex/flex-2.6.4.eb (module: flex/2.6.4)
 * [ ] $CFGS/b/binutils/binutils-2.37.eb (module: binutils/2.37)
 ```

**Comment by boegel** [comment]
@boegelbot please test @ generoso

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 3 out of 3 (3 easyconfigs in total)
node2643.swalot.os - Linux centos linux 7.9.2009, x86_64, Intel(R) Xeon(R) CPU E5-2660 v3 @ 2.60GHz (haswell), Python 3.6.8
See https://gist.github.com/69c9b792e68057095222ae3a8ed6f6aa for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 3 out of 3 (3 easyconfigs in total)
node3502.doduo.os - Linux RHEL 8.2, x86_64, AMD EPYC 7552 48-Core Processor (zen2), Python 3.6.8
See https://gist.github.com/66e84ad93398ab12ae6c37fe3aedd5d2 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 3 out of 3 (3 easyconfigs in total)
fair-mastodon-c6g-2xlarge-0001 - Linux rocky linux 8.5, AArch64, ARM UNKNOWN (graviton2), Python 3.6.8
See https://gist.github.com/bccdfc6a78e0486a71ed506f9a98473b for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 3 out of 3 (3 easyconfigs in total)
easybuild2.novalocal - Linux centos stream 8, POWER, IBM pSeries (emulated by qemu) (power9le), Python 3.6.8
See https://gist.github.com/2c2eb1bb9b521290d4ac4911e49d078d for a full test report.

**Comment by SebastianAchilles** [comment]
Test report by @sebastianachilles
**SUCCESS**
Build succeeded for 3 out of 3 (3 easyconfigs in total)
zen2-ubuntu-eb - Linux Ubuntu 22.04, x86_64, AMD EPYC 7452 32-Core Processor (zen2), Python 3.9.9
See https://gist.github.com/fc9cb678d0b24185f372a4ba2c2b1d14 for a full test report.

**Review by SebastianAchilles — APPROVED** [review]
lgtm

**Comment by SebastianAchilles** [comment]
Going in, thanks @boegel!

**Comment by boegel** [comment]
@SebastianAchilles We should consider doing the same for older binutils versions as well?

**Comment by SebastianAchilles** [comment]
@boegelbot please test @ jsc-zen2

**Pull request merged**
