### PR TITLE
{base,bio}[GCC/11.3.0] bamFilters v2022-06-30, SAMtools v1.13

### PR DESCRIPTION
**Pull request by PetrKralCZ**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by PetrKralCZ** [comment]
Test report by @PetrKralCZ
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
node3701.slaking.os - Linux RHEL 8.4, x86_64, Intel(R) Xeon(R) CPU E5-2680 v3 @ 2.50GHz, Python 3.6.8
See https://gist.github.com/d15f895effb7368c7dcc6f02c31e45ef for a full test report.

**Comment by PetrKralCZ** [comment]
Test report by @PetrKralCZ
**FAILED**
Build succeeded for 0 out of 1 (1 easyconfigs in total)
node3701.slaking.os - Linux RHEL 8.4, x86_64, Intel(R) Xeon(R) CPU E5-2680 v3 @ 2.50GHz, Python 3.6.8
See https://gist.github.com/efc226a4f02f283dc42a7b21bcf6f6a4 for a full test report.

**Comment by PetrKralCZ** [comment]
Test report by @PetrKralCZ
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
node3701.slaking.os - Linux RHEL 8.4, x86_64, Intel(R) Xeon(R) CPU E5-2680 v3 @ 2.50GHz, Python 3.6.8
See https://gist.github.com/8446f8a6907d6ce049e109c75fbe0ca8 for a full test report.

**Comment by zao** [comment]
Test report by @zao
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in total)
eb-rocky9.zao.se - Linux Rocky Linux 9.0 (Blue Onyx), x86_64, AMD Ryzen 9 3900X 12-Core Processor, Python 3.9.10
See https://gist.github.com/e075f0558540dabb54dc63c821c61fbe for a full test report.

**Comment by boegel** [comment]
@boegelbot please test @ generoso

**Comment by boegel** [comment]
Going in, thanks @PetrKralCZ!

**Pull request merged**
