### PR TITLE
{lang}[foss/2020a] R v4.0.0

### PR DESCRIPTION
**Pull request by boegel**
(created using `eb --new-pr`)
requires #10505 (various deps)

marked as WIP, because list of extensions should get another update round...

### CODE REVIEW

**Comment by lexming** [comment]
@boegel Updated list of extension in https://github.com/boegel/easybuild-easyconfigs/pull/61

**Comment by Flamefire** [comment]
Test report by @Flamefire
**FAILED**
Build succeeded for 50 out of 51 (1 easyconfigs in this PR)
taurusml3 - Linux RHEL 7.6, POWER, 8335-GTX, Python 2.7.5
See https://gist.github.com/800bce73665f64656ab0ddbdd4841267 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**FAILED**
Build succeeded for 0 out of 1 (1 easyconfigs in this PR)
generoso-1 - Linux centos linux 7.6.1810, x86_64, Intel(R) Xeon(R) CPU E5-2660 v4 @ 2.00GHz, Python 3.6.8
See https://gist.github.com/d90bb88c833db66f80cbdb4081d293ba for a full test report.

**Comment by boegel** [comment]
@lexming is looking into the extra extensions that are required after the update round in 
1409b99 ...

**Comment by Flamefire** [comment]
Test report by @Flamefire
**FAILED**
Build succeeded for 23 out of 24 (1 easyconfigs in this PR)
taurusi6284.taurus.hrsk.tu-dresden.de - Linux RHEL 7.7, x86_64, Intel(R) Xeon(R) CPU E5-2680 v3 @ 2.50GHz, Python 2.7.5
See https://gist.github.com/43bcd07b2b352dc54a8510d61c8ce8a5 for a full test report.

**Comment by verdurin** [comment]
Test report by @verdurin
**FAILED**
Build succeeded for 10 out of 11 (1 easyconfigs in this PR)
easybuild.novalocal - Linux centos linux 7.8.2003, Intel Xeon Processor (Skylake, IBRS), Python 2.7.5
See https://gist.github.com/60af6716688ea599bcec978921339197 for a full test report.

**Comment by lexming** [comment]
Actually, there are no new dependencies from updated packages missing in the easyconfig, but existing ones have to be moved to fulfil new requirements. Which is more complicated to detect as the extensions are already there. I think that https://github.com/boegel/easybuild-easyconfigs/pull/62 covers all of them, but I have a build still running.

**Comment by boegel** [comment]
@Flamefire @verdurin Please retest?

**Comment by boegel** [comment]
Test report by @boegel
**FAILED**
Build succeeded for 0 out of 1 (1 easyconfigs in this PR)
node2707.swalot.os - Linux centos linux 7.7.1908, x86_64, Intel(R) Xeon(R) CPU E5-2660 v3 @ 2.60GHz (haswell), Python 2.7.5
See https://gist.github.com/4cf435705d721a1faf690417ddadea9f for a full test report.

**Comment by verdurin** [comment]
Test report by @verdurin
**FAILED**
Build succeeded for 0 out of 1 (1 easyconfigs in this PR)
easybuild.novalocal - Linux centos linux 7.8.2003, Intel Xeon Processor (Skylake, IBRS), Python 2.7.5
See https://gist.github.com/7b0c9045f3e6606080b645d8254c4fea for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**FAILED**
Build succeeded for 0 out of 1 (1 easyconfigs in this PR)
generoso-1 - Linux centos linux 7.6.1810, x86_64, Intel(R) Xeon(R) CPU E5-2660 v4 @ 2.00GHz, Python 3.6.8
See https://gist.github.com/a32d9d2f9c124292e00a105c1a33a81e for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**FAILED**
Build succeeded for 0 out of 1 (1 easyconfigs in this PR)
node3149.skitty.os - Linux centos linux 7.7.1908, x86_64, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz (skylake_avx512), Python 3.6.8
See https://gist.github.com/ce4e3a0a4f6940795053e62af77be7c0 for a full test report.

**Comment by boegel** [comment]
More missing extensions...

```
ERROR: dependencies ROI, ROI.plugin.glpk are not available for package spaMM
```

**Comment by boegel** [comment]
And now the `Rglpk` extension fails with:

```
== 2020-04-30 08:17:55,243 build_log.py:169 ERROR EasyBuild crashed with an error (at easybuild/base/exceptions.py:124 in __init__): cmd " R CMD INSTALL /data/gent/400/vsc40023/EasyBuild/sources/r/R/extensions/Rglpk_0.6-4.tar.gz   --library=/user/gent/400/vsc40023/eb_phanpyscratch/CO7/skylake-ib/software/R/4.0.0-foss-2020a/lib64/R/library --no-clean-on-error " exited with exit code 1 and output:          * installing *source* package Rglpk ...
** package Rglpk successfully unpacked and MD5 sums checked
** using staged installation
** libs
/bin/sh: line 0: cd: GLPK: No such file or directory
make: *** [GLPK.ts] Error 1                                                                                                                                                                                 ERROR: compilation failed for package Rglpk
```

The fun never ends...

**Comment by boegel** [comment]
Should be good to go now, it ran to completion installing all extensions when using `--skip`, full test reports starting from scratch coming up...

**Comment by boegel** [comment]
Test report by @boegel
**FAILED**
Build succeeded for 1 out of 2 (2 easyconfigs in this PR)
node3402.kirlia.os - Linux centos linux 7.7.1908, x86_64, Intel(R) Xeon(R) Gold 6240 CPU @ 2.60GHz (cascadelake), Python 2.7.5
See https://gist.github.com/9b445d5b132011d5efe2ef2cce065f12 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**FAILED**
Build succeeded for 1 out of 2 (2 easyconfigs in this PR)
node3149.skitty.os - Linux centos linux 7.7.1908, x86_64, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz (skylake_avx512), Python 3.6.8
See https://gist.github.com/624cceab79294fbb9ea2437c6518215d for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**FAILED**
Build succeeded for 1 out of 2 (2 easyconfigs in this PR)
node3158.skitty.os - Linux centos linux 7.7.1908, x86_64, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz (skylake_avx512), Python 3.6.8
See https://gist.github.com/5c4bd101fc32640376573748c1508c50 for a full test report.

**Comment by verdurin** [comment]
Test report by @verdurin
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in this PR)
easybuild.novalocal - Linux centos linux 7.8.2003, Intel Xeon Processor (Skylake, IBRS), Python 2.7.5
See https://gist.github.com/eb7e466e8047fbb79b5af25bc9214d60 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in this PR)
node3402.kirlia.os - Linux centos linux 7.7.1908, x86_64, Intel(R) Xeon(R) Gold 6240 CPU @ 2.60GHz (cascadelake), Python 2.7.5
See https://gist.github.com/f1120c9edf957bf6a007787afccd256d for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in this PR)
node3149.skitty.os - Linux centos linux 7.7.1908, x86_64, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz (skylake_avx512), Python 3.6.8
See https://gist.github.com/8a0ecf21fb9fa3d0f5ac84ee4937d895 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in this PR)
generoso-1 - Linux centos linux 7.6.1810, x86_64, Intel(R) Xeon(R) CPU E5-2660 v4 @ 2.00GHz, Python 3.6.8
See https://gist.github.com/0311c62a0e11db8fed648eb53d530a6a for a full test report.

**Comment by lexming** [comment]
Test report by @lexming
**FAILED**
Build succeeded for 1 out of 2 (2 easyconfigs in this PR)
node150.hydra.os - Linux centos linux 7.7.1908, x86_64, Intel(R) Xeon(R) CPU E5-2680 v2 @ 2.80GHz, Python 2.7.5
See https://gist.github.com/975c21bbb0ef78ca6294fccdc60c6608 for a full test report.

**Comment by lexming** [comment]
Test report by @lexming
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in this PR)
node150.hydra.os - Linux centos linux 7.7.1908, x86_64, Intel(R) Xeon(R) CPU E5-2680 v2 @ 2.80GHz, Python 2.7.5
See https://gist.github.com/0bd9d2c188858980813a0c40f67a7a3d for a full test report.

**Comment by lexming** [comment]
Going in, thanks @boegel !

**Pull request merged**
