### PR TITLE
{lang,tools}[GCC/11.3.0] OCaml v4.14.0, snape-pooled v20150707

### PR DESCRIPTION
**Pull request by WilleBell**
(created using `eb --new-pr`)

Depends on:
* [ ] https://github.com/easybuilders/easybuild-easyblocks/pull/3235

### CODE REVIEW

**Comment by jfgrimm** [comment]
Test report by @jfgrimm
Using easyblocks from PR(s) https://github.com/easybuilders/easybuild-easyblocks/pull/3235
**FAILED**
Build succeeded for 0 out of 2 (2 easyconfigs in total)
himem01.viking2.yor.alces.network - Linux Rocky Linux 8.8, x86_64, AMD EPYC 7643 48-Core Processor, Python 3.6.8
See https://gist.github.com/jfgrimm/e419b278b4368f9b84670f8fc90a3d82 for a full test report.

**Comment by boegel** [comment]
@jfgrimm I took a quick look at how that RPATH sanity check failure could be resolved, and it doesn't seem easy...

I'm in favor of merging this (and https://github.com/easybuilders/easybuild-easyblocks/pull/3235) as is, and opening an issue to follow up, thoughts?

**Comment by boegel** [comment]
@boegelbot please test @ jsc-zen3
EB_ARGS=" --include-easyblocks-from-pr 3235"

**Comment by boegel** [comment]
Test report by @boegel
Using easyblocks from PR(s) https://github.com/easybuilders/easybuild-easyblocks/pull/3235
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in total)
node3102.skitty.os - Linux RHEL 8.8, x86_64, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz, Python 3.6.8
See https://gist.github.com/boegel/8f66e4b061b0495ff931f8686ac855c7 for a full test report.

**Comment by jfgrimm** [comment]
@boegel sounds good to me

**Comment by jfgrimm** [comment]
@boegel I've opened https://github.com/easybuilders/easybuild-easyconfigs/issues/20021

**Comment by jfgrimm** [comment]
which turned out to be a duplicate -- https://github.com/easybuilders/easybuild-easyblocks/issues/3247

**Pull request merged**
