### PR TITLE
{bio,devel}[foss/2018b] MetaBAT v2.12.1 w/ Python 2.7.15

### PR DESCRIPTION
**Pull request by boegel**
(created using `eb --new-pr`)

~~edit: #7753 should get merged first, after which this PR should be rebased on `develop`...~~

### CODE REVIEW

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in this PR)
node3110.skitty.os - Linux centos linux 7.6.1810, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz, Python 2.7.5
See https://gist.github.com/8fc736e88102c5571dab4aa6d885851c for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in this PR)
node2524.golett.os - Linux centos linux 7.6.1810, Intel(R) Xeon(R) CPU E5-2680 v3 @ 2.50GHz, Python 2.7.5
See https://gist.github.com/a31505978cafaecac7894fa41745949f for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in this PR)
node2005.delcatty.os - Linux centos linux 7.6.1810, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.7.5
See https://gist.github.com/dbc0ff4b510542083290f1e7eb164e67 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
node3146.skitty.os - Linux centos linux 7.6.1810, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz, Python 2.7.5
See https://gist.github.com/47208fb96f8f85681b4839ee3ae0d084 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
node2562.golett.os - Linux centos linux 7.6.1810, Intel(R) Xeon(R) CPU E5-2680 v3 @ 2.50GHz, Python 2.7.5
See https://gist.github.com/c26d262b6c2fd6c08c2b52ca878439c6 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
node2025.delcatty.os - Linux centos linux 7.6.1810, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.7.5
See https://gist.github.com/706f8ab1b8def41fd2c7b6a9ce765a50 for a full test report.

**Comment by wpoely86** [comment]
Test report by @wpoely86
**FAILED**
Build succeeded for 1 out of 2 (1 easyconfigs in this PR)
nic406 - Linux centos linux 7.5.1804, Intel(R) Xeon(R) Gold 6148 CPU @ 2.40GHz, Python 2.7.5
See https://gist.github.com/4398d71130b5cea0d5a2a4cb88fb8893 for a full test report.

**Comment by boegel** [comment]
@wpoely86 Is the `SAMtools` installation on which this builds on top of what it should be?

**Comment by wpoely86** [comment]
We're missing the directory `include/htslib` in our SAMtools install (which is just the repo easyconfig). No clue why that is.

**Comment by boegel** [comment]
I've just rebuilt `SAMtools-1.9-foss-2018b.eb`, and then the `include/htslib` is also missing there.

But, after also reinstalling `MetaBAT`, it's there again.

So somehow the`MetaBAT` installation is doing that, that's clearly not good...

**Comment by wpoely86** [comment]
Test report by @wpoely86
**FAILED**
Build succeeded for 1 out of 2 (1 easyconfigs in this PR)
nic2 - Linux centos linux 7.5.1804, AMD Opteron(tm) Processor 6134, Python 2.7.5
See https://gist.github.com/209bfbc24165186636b3372a1dab11bd for a full test report.

**Comment by wpoely86** [comment]
Almost there:

```
g++ -o contigOverlaps -lstdc++ -lm -fopenmp -static -static-libgcc -static-libstdc++ -pthread src/contigOverlaps.o /apps/brussel/CO7/magnycours-ib/software/Boost/1.67.0-foss-2018b/lib/libboost_system.a samtools/lib/libbam.a samtools/lib/libhts.a -lz
samtools/lib/libhts.a(cram_io.o):cram_io.c:function lzma_mem_deflate: error: undefined reference to 'lzma_stream_buffer_bound'
samtools/lib/libhts.a(cram_io.o):cram_io.c:function lzma_mem_deflate: error: undefined reference to 'lzma_easy_buffer_encode'
samtools/lib/libhts.a(cram_io.o):cram_io.c:function cram_compress_by_method: error: undefined reference to 'BZ2_bzBuffToBuffCompress'
samtools/lib/libhts.a(cram_io.o):cram_io.c:function cram_uncompress_block: error: undefined reference to 'BZ2_bzBuffToBuffDecompress'
samtools/lib/libhts.a(cram_io.o):cram_io.c:function cram_uncompress_block: error: undefined reference to 'lzma_easy_decoder_memusage'
samtools/lib/libhts.a(cram_io.o):cram_io.c:function cram_uncompress_block: error: undefined reference to 'lzma_stream_decoder'
samtools/lib/libhts.a(cram_io.o):cram_io.c:function cram_uncompress_block: error: undefined reference to 'lzma_code'
samtools/lib/libhts.a(cram_io.o):cram_io.c:function cram_uncompress_block: error: undefined reference to 'lzma_code'
samtools/lib/libhts.a(cram_io.o):cram_io.c:function cram_uncompress_block: error: undefined reference to 'lzma_end'
```

Apparently samtools links to lzma and bzip2 but MetaBAT doesn't?

**Pull request merged**
