### PR TITLE
{data}[intel/2017b foss/2017b] HDF5 1.10.1 configs

### PR DESCRIPTION
**Pull request by jhein32**

### CODE REVIEW

**Comment by boegel** [comment]
Test report by @boegel
**FAILED**
Build succeeded for 1 out of 2 (2 easyconfigs in this PR)
node2024.delcatty.os - Linux centos linux 7.3.1611, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.7.5
See https://gist.github.com/f9ab445ea873980a0c2512251ab1f6bb for a full test report.

**Comment by boegel** [comment]
@jhein32 Ignore the failing test report, `FFTW/3.3.6-gompi-2017b` module was missing and hence `foss/2017b` was broken, will submit new test report after correcting this issue...

**Comment by jhein32** [comment]
@boegel Before seeing your comment I looked into this and noticed, we don't have a FFTW/3.3.6-gompi-2017b module.  Our installation has created a FFTW/3.3.6 which gets used in foss/2017b.  I checked the changes on github and there doesn't seem to be a last minute change to foss/2017b that could have caused such a difference.

**Comment by boegel** [comment]
@jhein32 That's because you are using a different module naming scheme, e.g. `HierarchicalMNS`, while I'm using the default `EasyBuildMNS` which is flat rather than hierarchical.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in this PR)
node2550.golett.os - Linux centos linux 7.3.1611, Intel(R) Xeon(R) CPU E5-2680 v3 @ 2.50GHz, Python 2.7.5
See https://gist.github.com/f36bb2309da8c69bf6b232e35711040e for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in this PR)
node2024.delcatty.os - Linux centos linux 7.3.1611, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.7.5
See https://gist.github.com/144ec78cae5221cae5a1144b321bc730 for a full test report.

**Comment by boegel** [comment]
Going in, thanks @jhein32!

**Pull request merged**
