### PR TITLE
{tools}[GCCcore/11.2.0] ROCm v4.5.0

### PR DESCRIPTION
**Pull request by nordmoen**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by nordmoen** [comment]
This requires #14354, #14327 and easybuilders/easybuild-easyblocks#2617

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
pg-lab02 - Linux centos linux 8.3.2011, x86_64, AMD EPYC 7542 32-Core Processor (zen2), Python 3.6.8
See https://gist.github.com/0bfdc4673dd40872ae5b08c9765e6c3e for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**FAILED**
Build succeeded for 0 out of 1 (1 easyconfigs in total)
pg-lab02 - Linux centos linux 8.3.2011, x86_64, AMD EPYC 7542 32-Core Processor (zen2), Python 3.6.8
See https://gist.github.com/7153c3dcf662bb91188d8b5f4450347a for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
pg-lab02 - Linux centos linux 8.3.2011, x86_64, AMD EPYC 7542 32-Core Processor (zen2), Python 3.6.8
See https://gist.github.com/b3f63213e991729adeab756ea007d26b for a full test report.

**Review by boegel — APPROVED** [review]
lgtm

**Comment by boegel** [comment]
Going in, thanks @nordmoen!

**Pull request merged**
