### PR TITLE
[gompi/2020a] Score-P 6.0: Add patch to support libbfd 2.34 API change

### LINKED ISSUE #11105: Scorep 6.0 in gompi 2020a doesn't work with binutils 2.34
The current Score-P-6.0-gompi-2020a.eb required for Scalasca doesn't work with the binutils 2.34 in gompi 2020a, the `bfd_get_section_flags` et.al. depreciation issue. 

Hear say has it, that this will be fixed in the next Score-P release.  As a bug fix we need to move the Score-P version in 2020a once the new version (or a beta) becomes publicly available.

Perhaps it is an idea to retire Score-P/Scalasca from the current distribution until the fix is available.

### PR DESCRIPTION
**Pull request by geimer**
Fixes #11105 

@jhein32 Please test - works for me.

### CODE REVIEW

**Comment by jhein32** [comment]
@geimer

Hi Markus.  

The builds on our system using the --from-pr=11123 option.  I can use the scorep to instrument a simple OpenMP test code, which wouldn't link without the patch.  I can examine the resulting profile using the cube browser.  No issues at all.

I am happy for the issue report https://github.com/easybuilders/easybuild-easyconfigs/issues/11105 to be closed.

Thanks for your effort.

**Comment by boegel** [comment]
@boegelbot please test @ generoso

**Review by boegel — APPROVED** [review]
lgtm

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
node3157.skitty.os - Linux centos linux 7.8.2003, x86_64, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz (skylake_avx512), Python 3.6.8
See https://gist.github.com/b1a4fad48d7d1f00d2cbd152017c4d88 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
node2450.golett.os - Linux centos linux 7.8.2003, x86_64, Intel(R) Xeon(R) CPU E5-2680 v3 @ 2.50GHz (haswell), Python 2.7.5
See https://gist.github.com/adbe92800413e7d714f0fa4f0a2fdffe for a full test report.

**Comment by boegel** [comment]
Going in, thanks @geimer!

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
node3416.kirlia.os - Linux centos linux 7.8.2003, x86_64, Intel(R) Xeon(R) Gold 6240 CPU @ 2.60GHz (cascadelake), Python 2.7.5
See https://gist.github.com/0ee2302b054ba257d79a1ad6507416ea for a full test report.

**Pull request merged**
