### PR TITLE
{cae}[foss/2021b] OpenFAST v3.0.0

### PR DESCRIPTION
**Pull request by Micket**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by jfgrimm** [comment]
@boegelbot: please test @ generoso

**Comment by jfgrimm** [comment]
```== sanity checking...
  >> file 'bin/openfast' found: OK
  >> file 'bin/FAST.Farm' found: OK
  >> file 'lib/libopenfastlib.a' found: OK
  >> file 'libopenfast_prelib.a' found: FAILED
  >> file 'lib/libopenfast_postlib.a' found: OK
  >> (non-empty) directory 'include/openfast' found: OK
  >> loading modules: cae/OpenFAST/3.0.0-foss-2021b...
== ... (took 8 secs)
== FAILED: Installation ended unsuccessfully (build directory: /tmp/jfg508/OpenFAST/3.0.0/foss-2021b): build
failed (first 300 chars): Sanity check failed: no file found at 'libopenfast_prelib.a' in
/users/jfg508/scratch/easybuild-dev/software/OpenFAST/3.0.0-foss-2021b (took 32 mins 9 secs)
```

**Comment by jfgrimm** [comment]
Test report by @jfgrimm
**FAILED**
Build succeeded for 1 out of 2 (2 easyconfigs in total)
node148.pri.viking.alces.network - Linux CentOS Linux 7.9.2009, x86_64, Intel(R) Xeon(R) Gold 6138 CPU @ 2.00GHz (skylake_avx512), Python 3.6.8
See https://gist.github.com/faed771182578ab360066f7246881ff0 for a full test report.

**Comment by Micket** [comment]
intel-2021b build just get stuck forever

**Comment by jfgrimm** [comment]
yup, seeing the same issue

**Comment by Micket** [comment]
Test report by @Micket
**FAILED**
Build succeeded for 1 out of 2 (2 easyconfigs in total)
vera-c1 - Linux CentOS Linux 7.9.2009, x86_64, Intel Xeon Processor (Skylake), Python 3.6.8
See https://gist.github.com/4ae35472cc60f183b8f0ecddd85eef6f for a full test report.

**Comment by Micket** [comment]
tried intel 2021a, 2020b, 2020a, and they all got stuck on the same file. Giving up on the intel build.

**Comment by SebastianAchilles** [comment]
Test report by @sebastianachilles
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
skylake-alma8-eb - Linux AlmaLinux 8.5, x86_64, Intel(R) Core(TM) i7-8700 CPU @ 3.20GHz (skylake), Python 3.6.8
See https://gist.github.com/1c4a09be43ed1f8c4ce6fe5a41846daf for a full test report.

**Comment by SebastianAchilles** [comment]
Test report by @sebastianachilles
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
zen2-ubuntu-eb - Linux Ubuntu 22.04, x86_64, AMD EPYC 7452 32-Core Processor (zen2), Python 3.9.10
See https://gist.github.com/c00ba89ae55bbc44f0c353886e2905ae for a full test report.

**Comment by SebastianAchilles** [comment]
@boegelbot please test @ generoso

**Comment by Micket** [comment]
Test report by @Micket
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
vera-c2 - Linux Rocky Linux 8.4, x86_64, Intel Xeon Processor (Skylake), Python 3.6.8
See https://gist.github.com/a28e57378063c696ee0c99cb3465e8d7 for a full test report.

**Comment by verdurin** [comment]
Test report by @verdurin
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
centos7.lan - Linux CentOS Linux 7.9.2009, x86_64, Intel Core Processor (Skylake, IBRS), Python 3.6.8
See https://gist.github.com/c8a2e0eb18651c57ae279294a5315403 for a full test report.

**Review by verdurin — APPROVED** [review]
Looks fine.

**Comment by verdurin** [comment]
Going in, thanks @Micket!

**Pull request merged**
