### PR TITLE
Switch to using new spaces as delimiters for TCLLIBPATH

### LINKED ISSUE #849: tk should set TCLLIBPATH
TCLLIBPATH should be set to $root/lib in all tk easyconfig's, 
so probably use modextrapaths

### PR DESCRIPTION
**Pull request by Micket**
Fixes #849

Requires 
- [x] https://github.com/easybuilders/easybuild-framework/pull/4687

### CODE REVIEW

**Comment by Micket** [comment]
@boegelbot please test @ jsc-zen3
EB_ARGS="--module-only BLT-20181223-GCCcore-11.2.0.eb bwidget-1.9.15-GCCcore-11.3.0.eb Graphviz-8.1.0-GCCcore-12.3.0.eb Tk-8.6.14-GCCcore-13.3.0.eb"
EB_BRANCH=5.0.x

**Comment by Micket** [comment]
@boegelbot please test @ jsc-zen3
EB_ARGS="BLT-20181223-GCCcore-11.2.0.eb bwidget-1.9.15-GCCcore-11.3.0.eb Graphviz-8.1.0-GCCcore-12.3.0.eb Tk-8.6.14-GCCcore-13.3.0.eb"
EB_BRANCH=5.0.x

**Comment by Micket** [comment]
Test report by @Micket
**FAILED**
Build succeeded for 0 out of 1 (1 easyconfigs in total)
vera-skylake-build - Linux Rocky Linux 8.9, x86_64, Intel Xeon Processor (Skylake, IBRS, no TSX), Python 3.6.8
See https://gist.github.com/Micket/66c363b914860bb59cbcaebf06980509 for a full test report.

**Comment by Micket** [comment]
Test report by @Micket
**FAILED**
Build succeeded for 0 out of 1 (1 easyconfigs in total)
vera-skylake-build - Linux Rocky Linux 8.9, x86_64, Intel Xeon Processor (Skylake, IBRS, no TSX), Python 3.6.8
See https://gist.github.com/Micket/5200fa301ae6d3ea518e49e3250618b7 for a full test report.

**Comment by Micket** [comment]
Test report by @Micket
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
vera-skylake-build - Linux Rocky Linux 8.9, x86_64, Intel Xeon Processor (Skylake, IBRS, no TSX), Python 3.6.8
See https://gist.github.com/Micket/410b36ba10f25fc1f4e2fa3feb2928d2 for a full test report.

**Comment by Micket** [comment]
Test report by @Micket
**FAILED**
Build succeeded for 6 out of 7 (4 easyconfigs in total)
vera-skylake-build - Linux Rocky Linux 8.9, x86_64, Intel Xeon Processor (Skylake, IBRS, no TSX), Python 3.6.8
See https://gist.github.com/Micket/a14372466007a762f2266788714534c5 for a full test report.

**Comment by Micket** [comment]
BLT source download failing, and I don't see how to obtain it.

**Review by lexming — APPROVED** [review]
LGTM

**Comment by branfosj** [comment]
> @Micket you can go to https://sourceforge.net/p/blt/src/ci/b8cdc6c2cd8edba06ad53a5d56e961d35b07af28/tree/ and click on "Download snapshot"

I think sourceforge has caching on the generation of the zip file for download. If I try
```
wget https://sourceforge.net/code-snapshots/git/b/bl/blt/src.git/blt-src-b8cdc6c2cd8edba06ad53a5d56e961d35b07af28.zip
```
then that currently works. But I tried that 15 minutes ago and it failed.

**Comment by branfosj** [comment]
Test report by @branfosj
**FAILED**
Build succeeded for 0 out of 1 (1 easyconfigs in total)
bear-pg0105u03a - Linux RHEL 8.10, x86_64, Intel(R) Xeon(R) Platinum 8360Y CPU @ 2.40GHz (icelake), Python 3.6.8
See https://gist.github.com/branfosj/3412bedd0f2c1f64faf4c8c0b76a8347 for a full test report.

**Review by boegel — APPROVED** [review]
lgtm

**Comment by boegel** [comment]
There's a broader problem with BLT, it fails in the RPATH sanity check:
```
== FAILED: Installation ended unsuccessfully: Sanity check failed: Library Tcl30.so not found for
/software/BLT/20181223-GCCcore-11.2.0/lib/libBltTk30.so
```

Indeed:
```
ldd /software/BLT/20181223-GCCcore-11.2.0/lib64/libBltTk30.so | grep 'not found'
        Tcl30.so => not found
```

That has nothing to do with the changes in this PR though, so it's not a blocker

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 18 out of 18 (18 easyconfigs in total)
node3509.doduo.os - Linux RHEL 8.8, x86_64, AMD EPYC 7552 48-Core Processor, Python 3.6.8
See https://gist.github.com/boegel/ae27c178f8e8ae69e44700ada9adc4b3 for a full test report.

**Pull request merged**
