### PR TITLE
{phys}[foss/2017b,foss/2018a,foss/2018b] Octopus-8.2

### PR DESCRIPTION
**Pull request by micaeljtoliveira**
(created using `eb --new-pr`)

Requires ~~#6889~~ ~~#6888~~ and ~~#6886~~

### CODE REVIEW

**Comment by boegel** [comment]
Test report by @boegel
**FAILED**
Build succeeded for 0 out of 1 (1 easyconfigs in this PR)
node3115.skitty.os - Linux centos linux 7.5.1804, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz, Python 2.7.5
See https://gist.github.com/b9f47e7e8defa8d63681c65e9f8398a5 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**FAILED**
Build succeeded for 0 out of 3 (3 easyconfigs in this PR)
node2059.delcatty.os - Linux centos linux 7.5.1804, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.7.5
See https://gist.github.com/816b3ed95628f913f902afab6c74a3b2 for a full test report.

**Comment by migueldiascosta** [comment]
Test report by @migueldiascosta
**SUCCESS**
Build succeeded for 3 out of 3 (3 easyconfigs in this PR)
grc-cluster1 - Linux centos 6.10, Intel(R) Xeon(R) CPU E5-2640 0 @ 2.50GHz, Python 2.7.14
See https://gist.github.com/886cc8d73a3cb427c406a945f6f958c8 for a full test report.

**Comment by migueldiascosta** [comment]
@boegel you're latest test at least was because of insufficient slots?

**Comment by micaeljtoliveira** [comment]
Last month I finally had some time to look at this more in detail, as at first I was not able to reproduce the problem. It seems the testsuite fails when using more than one OpenMP thread. Since the code is compiled with OpenMP disabled, this means that the problem must come from one of the libraries (OpenBLAS or FFTW are the obvious candidates). The fact that it fails only for the foss/2018b toolchain somehow confirms this.

Since this might take some time to resolve, I would like to know if it would be okay to split the PR so that the easyconfigs for the foss/2017b and foss/2018a toolchains can be merged ASAP.

**Comment by boegel** [comment]
@micaeljtoliveira Splitting the PR makes sense to me. Please flesh out the working easyconfigs to a new PR, and then sync this PR with `develop` once that PR is merged (don't manually remove the easyconfigs from this PR, since that will result in actually removing the easyconfig files merged in the new PR).

**Comment by micaeljtoliveira** [comment]
@boegel The new PR for the foss/2017b and foss/2018a is #7404. Once that it's in I will sync this one.

**Comment by migueldiascosta** [comment]
I'm closing this PR since #7404 was closed by @micaeljtoliveira

**Pull request closed without merging**
