### PR TITLE
OpenFoam-Extend sync with block

### PR DESCRIPTION
**Pull request by wpoely86**
For hpcugent/easybuild-easyblocks#780

### CODE REVIEW

**Comment by wpoely86** [comment]
Test report by @wpoely86
**FAILED**
Build succeeded for 7 out of 28 (4 easyconfigs in this PR)
node2540.golett.os - Linux centos linux 7.2.1511, Intel(R) Xeon(R) CPU E5-2680 v3 @ 2.50GHz, Python 2.7.5
See https://gist.github.com/e0eccc8f5a8f21de951824bd8f1b6707 for a full test report.

**Comment by boegel** [comment]
@wpoely86 testing this on Haswell isn't going to work out...

**Comment by wpoely86** [comment]
Test report by @wpoely86
**SUCCESS**
Build succeeded for 23 out of 23 (4 easyconfigs in this PR)
node2107.delcatty.os - Linux SL 6.7, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.6.6
See https://gist.github.com/89e63971ec04c5e47ff782b95c0176a7 for a full test report.

**Comment by migueldiascosta** [comment]
@wpoely86, this PR is being closed for the following reason(s): no activity for > 1 year.
Please don't hesitate to reopen this PR or add a comment if you feel this contribution is still relevant.
For more information on our policy w.r.t. closing PRs, see https://easybuild.readthedocs.io/en/latest/Contributing.html#why-a-pull-request-may-be-closed-by-a-maintainer

**Pull request closed without merging**
