### PR TITLE
{vis}[intel/2018b] basemap v1.2.0 w/ Python 3.6.6 (+ deps)

### PR DESCRIPTION
**Pull request by boegel**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 3 out of 3 (3 easyconfigs in this PR)
node3146.skitty.os - Linux centos linux 7.6.1810, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz, Python 2.7.5
See https://gist.github.com/e5d5ec8c4896f78bf88a66d5c215dbc4 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 3 out of 3 (3 easyconfigs in this PR)
node2562.golett.os - Linux centos linux 7.6.1810, Intel(R) Xeon(R) CPU E5-2680 v3 @ 2.50GHz, Python 2.7.5
See https://gist.github.com/31a1fc8f4bd5a51370d1defde446e8c0 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 3 out of 3 (3 easyconfigs in this PR)
node2025.delcatty.os - Linux centos linux 7.6.1810, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.7.5
See https://gist.github.com/ba8f8b4dcd90b40f2b158f86e278c8be for a full test report.

**Comment by boegel** [comment]
I was tripping over something tricky while putting this together, so I'll document it here for all eternity...

`matplotlib` which is a dependency for `basemap` was installed using `pip install` (via `use_pip = True` in the `matplotlib` easyconfig), and hence the `mpl_toolkits` directory included in the `matplotlib` installation did not have a `__init__py` to declare the `mpl_toolkits` namespace.
That's fine, since Python 3.3+ has support for so-called "native namespace packages" (a.k.a "implicit namespace packages"), see https://packaging.python.org/guides/packaging-namespace-packages/#native-namespace-packages .

However when installing `basemap` without `pip` (i.e. without using `use_pip = True`), the sanity check for `basemap` was failing on the `import mpl_toolkits.basemap` test:

```
== 2019-02-27 18:39:03,805 extension.py:187 WARNING Sanity check for 'basemap' extension failed: command "/prefix/software/Python/3.6.6-intel-2018b/bin/python -c "import mpl_toolkits.basemap"" failed; output:
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'mpl_toolkits.basemap'
```

That happened because when `basemap` was being installed with `setup.py install` rather than `pip install`, the `mpl_toolkits/__init__.py` file was installed in the `basemap` installation directory. This `__init__.py` includes a `declare_namespace` statement, following the alternative way of declaring namespaces, see https://packaging.python.org/guides/packaging-namespace-packages/#pkg-resources-style-namespace-packages .

Apparently this mixing of namespace package declaration mechanism doesn't work, in the sense that only the `mpl_toolkits` that is part of `matplotlib` was considered, and the `basemap` one was being ignored...
See also the warning in https://packaging.python.org/guides/packaging-namespace-packages/#native-namespace-packages:

```
It is extremely important that every distribution that uses the namespace package omits the __init__.py or uses a pkgutil-style __init__.py. If any distribution does not, it will cause the namespace logic to fail and the other sub-packages will not be importable.
```

This puzzled me quite a bit, but the solution in the end was to make sure that both `matplotlib` and `basemap` were installed using `pip install`, and then all is well.

@boegel: If you hit this same problem again, and you hit this comment when spending some time Googling trying to figure out wth is going on, increase this counter: 0 .

**Comment by akesandgren** [comment]
Going in, thanks @boegel!

**Pull request merged**
