### PR TITLE
{bio}[goolf/1.7.20] KmerGenie v1.7016

### PR DESCRIPTION
**Pull request by pescobar**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by boegel** [comment]
@pescobar missing dep: `Irresolvable dependencies encountered: R/3.3.1-goolf-1.7.20`

**Comment by pescobar** [comment]
@boegel I will close this one. I have no time to provide a R/3.3.1-goolf-1.7.20 which fits upstream

**Comment by pescobar** [comment]
as quicker workaorund I changed the deps to `R/3.2.0-goolf-1.7.20` which is already available upstream

If someone wants to use a different R version can tweak the easyconfig

**Comment by boegel** [comment]
@pescobar and now you have a version conflict on `Tk`...

```
Conflict found for dependencies of KmerGenie-1.7016-goolf-1.7.20-Python-2.7.11-R-3.2.0: Tk-8.6.4-goolf-1.7.20 vs Tk-8.6.4-goolf-1.7.20-no-X11 
	Tk-8.6.4-goolf-1.7.20 as dep of: Cookiecutter-1.4.0-goolf-1.7.20-Python-2.7.11, IPython-4.2.0-goolf-1.7.20-Python-2.7.11, KmerGenie-1.7016-goolf-1.7.20-Python-2.7.11-R-3.2.0, PyZMQ-15.2.0-goolf-1.7.20-Python-2.7.11-zmq4, Pysam-0.9.0-goolf-1.7.20-Python-2.7.11, Python-2.7.11-goolf-1.7.20, pip-8.1.2-goolf-1.7.20-Python-2.7.11, testpath-0.3-goolf-1.7.20-Python-2.7.11
	Tk-8.6.4-goolf-1.7.20-no-X11 as dep of: Boost-1.58.0-goolf-1.7.20-Python-2.7.10, KmerGenie-1.7016-goolf-1.7.20-Python-2.7.11-R-3.2.0, Python-2.7.10-goolf-1.7.20, R-3.2.0-goolf-1.7.20, R-bundle-Bioconductor-3.1-goolf-1.7.20-R-3.2.0
```

**Comment by migueldiascosta** [comment]
@pescobar, this PR is being closed for the following reason(s): no activity for > 6 months, obsoleted by more recent PRs.
Please don't hesitate to reopen this PR or add a comment if you feel this contribution is still relevant.
For more information on our policy w.r.t. closing PRs, see https://easybuild.readthedocs.io/en/latest/Contributing.html#why-a-pull-request-may-be-closed-by-a-maintainer

**Pull request closed without merging**
