### PR TITLE
add dependency on PycURL to JupyterHub-3.0.0-GCCcore-11.3.0.eb

### PR DESCRIPTION
**Pull request by lexming**
(created using `eb --new-pr`)

see https://github.com/jupyterhub/jupyterhub/blob/24506888ea4904be97197426e42083a4769789c2/jupyterhub/app.py#L2730-L2739

### CODE REVIEW

**Comment by lexming** [comment]
@boegelbot: please test @ generoso

**Comment by lexming** [comment]
@boegelbot please test @ jsc-zen2

**Comment by verdurin** [comment]
Test report by @verdurin
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in total)
easybuild-c7.novalocal - Linux CentOS Linux 7.9.2009, x86_64, Intel Xeon Processor (Skylake, IBRS), Python 3.6.8
See https://gist.github.com/verdurin/8ed24e26e32a153f6c1296079ffccdb6 for a full test report.

**Review by verdurin — APPROVED** [review]
Looks fine.

**Comment by verdurin** [comment]
Going in, thanks @lexming!

**Pull request merged**
