### PR TITLE
{tools}[foss/2021a] jax v0.3.9 w/ Python 3.9.5

### PR DESCRIPTION
**Pull request by branfosj**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by branfosj** [comment]
Test report by @branfosj
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
bear-pg0105u36b.bear.cluster - Linux RHEL 8.5, x86_64, Intel(R) Xeon(R) Platinum 8360Y CPU @ 2.40GHz (icelake), Python 3.6.8
See https://gist.github.com/13aa7b480c98de685cf30e61eca2897d for a full test report.

**Comment by branfosj** [comment]
Test report by @branfosj
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
bear-pg0211u03a.bear.cluster - Linux RHEL 8.5, x86_64, Intel(R) Xeon(R) Gold 6248 CPU @ 2.50GHz (cascadelake), Python 3.6.8
See https://gist.github.com/c05399122f84ba242e2339564c95e5bd for a full test report.

**Comment by verdurin** [comment]
@boegelbot please test @ generoso

**Comment by verdurin** [comment]
Test report by @verdurin
**FAILED**
Build succeeded for 4 out of 5 (1 easyconfigs in total)
easybuild-c7.novalocal - Linux CentOS Linux 7.9.2009, x86_64, Intel Xeon Processor (Skylake, IBRS), Python 3.6.8
See https://gist.github.com/7998053597e91455f10e3508dcd429fe for a full test report.

**Comment by verdurin** [comment]
Here's the error, on a CentOS 7 build node:

```
Downloading bazel from: https://github.com/bazelbuild/bazel/releases/download/5.1.1/bazel-5.1.1-linux-x86_64
Traceback (most recent call last):
  File "/eb/maint/software/Python/3.9.5-GCCcore-10.3.0/lib/python3.9/urllib/request.py", line 1346, in do_open
    h.request(req.get_method(), req.selector, req.data, headers,
  File "/eb/maint/software/Python/3.9.5-GCCcore-10.3.0/lib/python3.9/http/client.py", line 1253, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/eb/maint/software/Python/3.9.5-GCCcore-10.3.0/lib/python3.9/http/client.py", line 1299, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/eb/maint/software/Python/3.9.5-GCCcore-10.3.0/lib/python3.9/http/client.py", line 1248, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/eb/maint/software/Python/3.9.5-GCCcore-10.3.0/lib/python3.9/http/client.py", line 1008, in _send_output
    self.send(msg)
  File "/eb/maint/software/Python/3.9.5-GCCcore-10.3.0/lib/python3.9/http/client.py", line 948, in send
    self.connect()
  File "/eb/maint/software/Python/3.9.5-GCCcore-10.3.0/lib/python3.9/http/client.py", line 1422, in connect
    self.sock = self._context.wrap_socket(self.sock,
  File "/eb/maint/software/Python/3.9.5-GCCcore-10.3.0/lib/python3.9/ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
  File "/eb/maint/software/Python/3.9.5-GCCcore-10.3.0/lib/python3.9/ssl.py", line 1040, in _create
    self.do_handshake()
  File "/eb/maint/software/Python/3.9.5-GCCcore-10.3.0/lib/python3.9/ssl.py", line 1309, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1129)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/dev/shm/jax/0.3.9/foss-2021a/jax-jaxlib-v0.3.7/build/build.py", line 527, in <module>
    main()
  File "/dev/shm/jax/0.3.9/foss-2021a/jax-jaxlib-v0.3.7/build/build.py", line 436, in main
    bazel_path, bazel_version = get_bazel_path(args.bazel_path)
  File "/dev/shm/jax/0.3.9/foss-2021a/jax-jaxlib-v0.3.7/build/build.py", line 195, in get_bazel_path
    for path in filter(None, get_bazel_paths(bazel_path_flag)):
  File "/dev/shm/jax/0.3.9/foss-2021a/jax-jaxlib-v0.3.7/build/build.py", line 183, in get_bazel_paths
    yield download_and_verify_bazel()
  File "/dev/shm/jax/0.3.9/foss-2021a/jax-jaxlib-v0.3.7/build/build.py", line 150, in download_and_verify_bazel
    tmp_path, _ = urlretrieve(uri, None,
  File "/eb/maint/software/Python/3.9.5-GCCcore-10.3.0/lib/python3.9/urllib/request.py", line 239, in urlretrieve
    with contextlib.closing(urlopen(url, data)) as fp:
  File "/eb/maint/software/Python/3.9.5-GCCcore-10.3.0/lib/python3.9/urllib/request.py", line 214, in urlopen
    return opener.open(url, data, timeout)
  File "/eb/maint/software/Python/3.9.5-GCCcore-10.3.0/lib/python3.9/urllib/request.py", line 517, in open
    response = self._open(req, data)
  File "/eb/maint/software/Python/3.9.5-GCCcore-10.3.0/lib/python3.9/urllib/request.py", line 534, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
  File "/eb/maint/software/Python/3.9.5-GCCcore-10.3.0/lib/python3.9/urllib/request.py", line 494, in _call_chain
    result = func(*args)
  File "/eb/maint/software/Python/3.9.5-GCCcore-10.3.0/lib/python3.9/urllib/request.py", line 1389, in https_open
    return self.do_open(http.client.HTTPSConnection, req,
  File "/eb/maint/software/Python/3.9.5-GCCcore-10.3.0/lib/python3.9/urllib/request.py", line 1349, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1129)>
 (at easybuild/tools/run.py:618 in parse_cmd_output)
 ```
 
 Do I perhaps need to rebuild `Python/3.9.5` to pick up a recent fix?

**Comment by bedroge** [comment]
> Here's the error, on a CentOS 7 build node:
> 
> ```
> Downloading bazel from: https://github.com/bazelbuild/bazel/releases/download/5.1.1/bazel-5.1.1-linux-x86_64
> Traceback (most recent call last):
>   File "/eb/maint/software/Python/3.9.5-GCCcore-10.3.0/lib/python3.9/urllib/request.py", line 1346, in do_open
>     h.request(req.get_method(), req.selector, req.data, headers,
>   File "/eb/maint/software/Python/3.9.5-GCCcore-10.3.0/lib/python3.9/http/client.py", line 1253, in request
>     self._send_request(method, url, body, headers, encode_chunked)
>   File "/eb/maint/software/Python/3.9.5-GCCcore-10.3.0/lib/python3.9/http/client.py", line 1299, in _send_request
>     self.endheaders(body, encode_chunked=encode_chunked)
>   File "/eb/maint/software/Python/3.9.5-GCCcore-10.3.0/lib/python3.9/http/client.py", line 1248, in endheaders
>     self._send_output(message_body, encode_chunked=encode_chunked)
>   File "/eb/maint/software/Python/3.9.5-GCCcore-10.3.0/lib/python3.9/http/client.py", line 1008, in _send_output
>     self.send(msg)
>   File "/eb/maint/software/Python/3.9.5-GCCcore-10.3.0/lib/python3.9/http/client.py", line 948, in send
>     self.connect()
>   File "/eb/maint/software/Python/3.9.5-GCCcore-10.3.0/lib/python3.9/http/client.py", line 1422, in connect
>     self.sock = self._context.wrap_socket(self.sock,
>   File "/eb/maint/software/Python/3.9.5-GCCcore-10.3.0/lib/python3.9/ssl.py", line 500, in wrap_socket
>     return self.sslsocket_class._create(
>   File "/eb/maint/software/Python/3.9.5-GCCcore-10.3.0/lib/python3.9/ssl.py", line 1040, in _create
>     self.do_handshake()
>   File "/eb/maint/software/Python/3.9.5-GCCcore-10.3.0/lib/python3.9/ssl.py", line 1309, in do_handshake
>     self._sslobj.do_handshake()
> ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1129)
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/dev/shm/jax/0.3.9/foss-2021a/jax-jaxlib-v0.3.7/build/build.py", line 527, in <module>
>     main()
>   File "/dev/shm/jax/0.3.9/foss-2021a/jax-jaxlib-v0.3.7/build/build.py", line 436, in main
>     bazel_path, bazel_version = get_bazel_path(args.bazel_path)
>   File "/dev/shm/jax/0.3.9/foss-2021a/jax-jaxlib-v0.3.7/build/build.py", line 195, in get_bazel_path
>     for path in filter(None, get_bazel_paths(bazel_path_flag)):
>   File "/dev/shm/jax/0.3.9/foss-2021a/jax-jaxlib-v0.3.7/build/build.py", line 183, in get_bazel_paths
>     yield download_and_verify_bazel()
>   File "/dev/shm/jax/0.3.9/foss-2021a/jax-jaxlib-v0.3.7/build/build.py", line 150, in download_and_verify_bazel
>     tmp_path, _ = urlretrieve(uri, None,
>   File "/eb/maint/software/Python/3.9.5-GCCcore-10.3.0/lib/python3.9/urllib/request.py", line 239, in urlretrieve
>     with contextlib.closing(urlopen(url, data)) as fp:
>   File "/eb/maint/software/Python/3.9.5-GCCcore-10.3.0/lib/python3.9/urllib/request.py", line 214, in urlopen
>     return opener.open(url, data, timeout)
>   File "/eb/maint/software/Python/3.9.5-GCCcore-10.3.0/lib/python3.9/urllib/request.py", line 517, in open
>     response = self._open(req, data)
>   File "/eb/maint/software/Python/3.9.5-GCCcore-10.3.0/lib/python3.9/urllib/request.py", line 534, in _open
>     result = self._call_chain(self.handle_open, protocol, protocol +
>   File "/eb/maint/software/Python/3.9.5-GCCcore-10.3.0/lib/python3.9/urllib/request.py", line 494, in _call_chain
>     result = func(*args)
>   File "/eb/maint/software/Python/3.9.5-GCCcore-10.3.0/lib/python3.9/urllib/request.py", line 1389, in https_open
>     return self.do_open(http.client.HTTPSConnection, req,
>   File "/eb/maint/software/Python/3.9.5-GCCcore-10.3.0/lib/python3.9/urllib/request.py", line 1349, in do_open
>     raise URLError(err)
> urllib.error.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1129)>
>  (at easybuild/tools/run.py:618 in parse_cmd_output)
> ```
> 
> Do I perhaps need to rebuild `Python/3.9.5` to pick up a recent fix?

This is probably related to your OpenSSL installation, see PR https://github.com/easybuilders/easybuild-easyblocks/pull/2683 and issues https://github.com/easybuilders/easybuild-easyblocks/issues/2674 and https://github.com/easybuilders/easybuild-easyconfigs/issues/14901.

**Comment by verdurin** [comment]
Test report by @verdurin
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
easybuild-c7.novalocal - Linux CentOS Linux 7.9.2009, x86_64, Intel Xeon Processor (Skylake, IBRS), Python 3.6.8
See https://gist.github.com/2b836dba4e2dc4c4798f1c89eb0c8d95 for a full test report.

**Review by verdurin — APPROVED** [review]
Looks fine.

**Comment by verdurin** [comment]
Going in, thanks @branfosj!

**Pull request merged**
