### PR TITLE
add neuralnet extension to recent R 4.x easyconfigs

### PR DESCRIPTION
**Pull request by boegel**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by boegel** [comment]
@boegelbot please test @ generoso
EB_ARGS="R-4.0.3-foss-2020b.eb R-4.0.4-foss-2020b.eb R-4.0.5-foss-2020b.eb R-4.1.0-foss-2021a.eb --skip"

**Comment by boegel** [comment]
Test report by @boegel
**FAILED**
Build succeeded for 0 out of 4 (4 easyconfigs in total)
node2669.swalot.os - Linux centos linux 7.9.2009, x86_64, Intel(R) Xeon(R) CPU E5-2660 v3 @ 2.60GHz (haswell), Python 3.6.8
See https://gist.github.com/3a4dd0503a943730a8d4acfcfe672d66 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 7 out of 7 (7 easyconfigs in total)
node3302.joltik.os - Linux centos linux 7.9.2009, x86_64, Intel(R) Xeon(R) Gold 6242 CPU @ 2.80GHz (cascadelake), Python 3.6.8
See https://gist.github.com/fe9932a37eb3658152602fd5cdfe5655 for a full test report.

**Review by branfosj — APPROVED** [review]

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 4 out of 4 (4 easyconfigs in total)
node2669.swalot.os - Linux centos linux 7.9.2009, x86_64, Intel(R) Xeon(R) CPU E5-2660 v3 @ 2.60GHz (haswell), Python 3.6.8
See https://gist.github.com/2bcf372f67e39d4b0887eb36c30dd363 for a full test report.

**Pull request merged**
