### PR TITLE
{compiler}[intel-compilers/2021.1.2] impi v2021.1.1

### PR DESCRIPTION
**Pull request by boegel**
(created using `eb --new-pr`)
requires:
* [x] ~~https://github.com/easybuilders/easybuild-framework/pull/3581~~ + ~~https://github.com/easybuilders/easybuild-framework/pull/3582~~ (`intel-compilers` toolchain support) 
* [x] ~~https://github.com/easybuilders/easybuild-easyblocks/pull/2313~~ (updated `impi` easyblock)
* [x] ~~#11982~~ (`intel-compilers` toolchain)

### CODE REVIEW

**Comment by boegel** [comment]
Test report by @boegel
Using easyblocks from PR(s) https://github.com/easybuilders/easybuild-easyblocks/pull/2313
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
node2610.swalot.os - Linux centos linux 7.9.2009, x86_64, Intel(R) Xeon(R) CPU E5-2660 v3 @ 2.60GHz (haswell), Python 3.6.8
See https://gist.github.com/a9454905fc12d2c519017c0e3eab862b for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
Using easyblocks from PR(s) https://github.com/easybuilders/easybuild-easyblocks/pull/2313
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
node2610.swalot.os - Linux centos linux 7.9.2009, x86_64, Intel(R) Xeon(R) CPU E5-2660 v3 @ 2.60GHz (haswell), Python 3.6.8
See https://gist.github.com/846c1244a60d80ab9cec8b492ddd2b2e for a full test report.

**Comment by bartoldeman** [comment]
@boegelbot please test @ generoso
EB_ARGS="--include-easyblocks-from-pr 2313"

**Comment by bartoldeman** [comment]
@boegelbot please test @ generoso
EB_ARGS="--include-easyblocks-from-pr 2313 --accept-eula=Intel-oneAPI"

**Comment by bartoldeman** [comment]
Test report by @bartoldeman
Using easyblocks from PR(s) https://github.com/easybuilders/easybuild-easyblocks/pull/2313
**FAILED**
Build succeeded for 0 out of 2 (1 easyconfigs in total)
build-node.computecanada.ca - Linux centos linux 7.9.2009, x86_64, Intel Xeon Processor (Skylake, IBRS), Python 3.7.7
See https://gist.github.com/1c65269624188c417b35e857e449f8f9 for a full test report.

**Comment by bartoldeman** [comment]
Test report by @bartoldeman
Using easyblocks from PR(s) https://github.com/easybuilders/easybuild-easyblocks/pull/2313
**FAILED**
Build succeeded for 1 out of 2 (1 easyconfigs in total)
build-node.computecanada.ca - Linux centos linux 7.9.2009, x86_64, Intel Xeon Processor (Skylake, IBRS), Python 3.7.7
See https://gist.github.com/18072da0818d3cbfd47c355d482b6598 for a full test report.

**Comment by bartoldeman** [comment]
Test report by @bartoldeman
Using easyblocks from PR(s) https://github.com/easybuilders/easybuild-easyblocks/pull/2313
**FAILED**
Build succeeded for 0 out of 1 (1 easyconfigs in total)
build-node.computecanada.ca - Linux centos linux 7.9.2009, x86_64, Intel Xeon Processor (Skylake, IBRS), Python 3.7.7
See https://gist.github.com/685a75f07a9601735128f5f99359903b for a full test report.

**Comment by bartoldeman** [comment]
Test report by @bartoldeman
Using easyblocks from PR(s) https://github.com/easybuilders/easybuild-easyblocks/pull/2313
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
build-node.computecanada.ca - Linux centos linux 7.9.2009, x86_64, Intel Xeon Processor (Skylake, IBRS), Python 3.7.7
See https://gist.github.com/020043b8e6e107005325b0d971dd186a for a full test report.

**Review by bartoldeman — APPROVED** [review]
My test reports were ok, just initially failing because of local oddities with hooks that no longer work with this versions.

So approved.

**Pull request merged**
