### PR TITLE
update source url for pkgconf

### PR DESCRIPTION
**Pull request by branfosj**
(created using `eb --new-pr`)

see https://github.com/pkgconf/pkgconf/issues/302

### CODE REVIEW

**Comment by branfosj** [comment]
Test report by @branfosj
**SUCCESS**
Build succeeded for 6 out of 6 (6 easyconfigs in total)
bb-pg-login02.bb2.cluster - Linux RHEL 8.6, x86_64, Intel(R) Xeon(R) CPU E5-2620 v4 @ 2.10GHz (broadwell), Python 3.6.8
See https://gist.github.com/branfosj/d69d0a5727f416e70bfb8fac0f75e1cb for a full test report.

**Comment by boegel** [comment]
@boegelbot please test @ generoso
EB_ARGS="--force-download --sourcepath /tmp/$USER/pr18271/sources --installpath /tmp/$USER/pr18271"

**Review by boegel — APPROVED** [review]
lgtm

**Comment by boegel** [comment]
Going in, thanks @branfosj!

**Pull request merged**
