### PR TITLE
{lib, tools}[gompi/2024a] dtcmp-1.1.5, libcircle-0.3, lwgrp-1.0.6, maeparser-1.3.1, mpifileutils-0.11.1

### PR DESCRIPTION
**Pull request by ankekreuzer**
This PR adds some files to the gompi-2024a toolchain from the new SW stage at JSC.

### CODE REVIEW

**Comment by ankekreuzer** [comment]
Test report by @ankekreuzer
**SUCCESS**
Build succeeded for 5 out of 5 (5 easyconfigs in total)
zam329 - Linux Rocky Linux 9.4 (Blue Onyx), x86_64, Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz, Python 3.9.18
See https://gist.github.com/ankekreuzer/52cd4c1634aa346b2a0810006645af46 for a full test report.

**Comment by smoors** [comment]
@boegelbot please test @ jsc-zen3

**Comment by smoors** [comment]
@boegelbot: please test @ generoso

**Review by smoors — APPROVED** [review]
lgtm

**Comment by smoors** [comment]
Going in, thanks @ankekreuzer!

**Pull request merged**
