### PR TITLE
allow external tools to be located elsewhere for ETE

### PR DESCRIPTION
**Pull request by smoors**
(created using `eb --new-pr`)

### CODE REVIEW

**Review by Micket — APPROVED** [review]
lgtm

**Comment by Micket** [comment]
got any of those fancy test reports?

**Comment by smoors** [comment]
@boegelbot: please test @ generoso

**Comment by Micket** [comment]
Test report by @Micket
**SUCCESS**
Build succeeded for 22 out of 22 (1 easyconfigs in total)
alvis-c1 - Linux Rocky Linux 8.5, x86_64, Intel Xeon Processor (Skylake), Python 3.6.8
See https://gist.github.com/97a20a828e909e2b3ab962eda505a941 for a full test report.

**Pull request merged**
