### PR TITLE
{lib}[GCCcore/10.2.0] OpenVR v1.0.17

### PR DESCRIPTION
**Pull request by ThomasHoffmann77**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by verdurin** [comment]
Test report by @verdurin
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
nuc.lan - Linux Fedora 33, x86_64, Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz, Python 3.9.5
See https://gist.github.com/fbba902b212987b566f38eff9caf8cef for a full test report.

**Comment by verdurin** [comment]
Test report by @verdurin
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
easybuild-c7.novalocal - Linux centos linux 7.9.2009, x86_64, Intel Xeon Processor (Skylake, IBRS), Python 3.6.8
See https://gist.github.com/c22794579e41a09ab25d8f3697a7fc5b for a full test report.

**Comment by verdurin** [comment]
@boegelbot please test @ generoso

**Comment by boegel** [comment]
closing this since `GCC/10.2.0` is deprecated, see https://docs.easybuild.io/policies/toolchains

@ThomasHoffmann77 Sorry for not following up on this :(

If `OpenVR` is still relevant, please consider opening a new pull request with a more recent toolchain

**Pull request closed without merging**
