### PR TITLE
{devel}[GCCcore/12.2.0] libnsl v2.0.0

### PR DESCRIPTION
**Pull request by garadar**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by garadar** [comment]
I created this PR for compiling Bowtie2 but I needed libsnl: https://github.com/easybuilders/easybuild-easyconfigs/pull/18097#issuecomment-1632100463

**Review by branfosj — APPROVED** [review]

**Comment by branfosj** [comment]
@boegelbot please test @ generoso

**Comment by branfosj** [comment]
@boegelbot please test @ jsc-zen2

**Comment by branfosj** [comment]
Test report by @branfosj
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
bear-pg0105u03a.bear.cluster - Linux RHEL 8.6, x86_64, Intel(R) Xeon(R) Platinum 8360Y CPU @ 2.40GHz (icelake), Python 3.6.8
See https://gist.github.com/branfosj/042eb8210f6d13850ed845b05f32d502 for a full test report.

**Comment by branfosj** [comment]
Going in, thanks @garadar!

**Pull request merged**
