### PR TITLE
{bio}[foss/2017b,intel/2017b] RSEM v1.3.1

### PR DESCRIPTION
**Pull request by vanzod**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by vanzod** [comment]
Test report by @vanzod
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in this PR)
cermis - Linux debian 9.7, Intel(R) Xeon(R) CPU           X5670  @ 2.93GHz, Python 2.7.13
See https://gist.github.com/93e03d78078edbe18bbc913f4cb0f9d3 for a full test report.

**Comment by smoors** [comment]
Test report by @smoors
**FAILED**
Build succeeded for 5 out of 8 (2 easyconfigs in this PR)
nic411 - Linux centos linux 7.5.1804, Intel(R) Xeon(R) Gold 6148 CPU @ 2.40GHz, Python 2.7.5
See https://gist.github.com/f83a89e931585a8faad9ee822b3ec79e for a full test report.

**Comment by smoors** [comment]
@vanzod my bad, I should have checked that I actually have the R modules installed..
Probably easiest if you or someone else (re-)generate the test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in this PR)
node2077.delcatty.os - Linux centos linux 7.6.1810, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.7.5
See https://gist.github.com/37e6db5ddc77c23b3d9dbfac42638b8f for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in this PR)
node2402.golett.os - Linux centos linux 7.6.1810, Intel(R) Xeon(R) CPU E5-2680 v3 @ 2.50GHz, Python 2.7.5
See https://gist.github.com/14d8403caebf9caac15a7f692310432e for a full test report.

**Comment by boegel** [comment]
Going in, thanks @vanzod!

**Pull request merged**
