### PR TITLE
{vis}[GCCcore/10.3.0] bashplotlib v0.6.5 w/ Python 3.9.5

### PR DESCRIPTION
**Pull request by migueldiascosta**
(created using `eb --new-pr`)

(just because it's neat :) )

### CODE REVIEW

**Comment by migueldiascosta** [comment]
@boegelbot please test @ generoso

**Review by boegel — CHANGES_REQUESTED** [review]
@migueldiascosta I think it makes sense to customize the sanity check a bit more, to also check for `bin/hist` and `bin/scatter`, and to run `--help` on both as sanity check commands

**Comment by migueldiascosta** [comment]
@boegelbot please test @ generoso

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
node3103.skitty.os - Linux centos linux 7.9.2009, x86_64, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz, Python 3.6.8
See https://gist.github.com/6e11436dded8327d8ef633726b2c11d5 for a full test report.

**Review by boegel — APPROVED** [review]

**Comment by boegel** [comment]
Going in, thanks @migueldiascosta!

**Pull request merged**
