### PR TITLE
{vis}[GCCcore/8.2.0] GLib v2.60.1, GObject-Introspection v1.60.1, cairo v1.16.0

### PR DESCRIPTION
**Pull request by Micket**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by akesandgren** [comment]
Test report by @akesandgren
**SUCCESS**
Build succeeded for 2 out of 2 (3 easyconfigs in this PR)
b-an03.hpc2n.umu.se - Linux ubuntu 16.04, Intel(R) Xeon(R) CPU E5-2690 v4 @ 2.60GHz, Python 2.7.12
See https://gist.github.com/2b4ade87ae4524f7cdfba4910284bc0c for a full test report.

**Comment by akesandgren** [comment]
Test report by @akesandgren
**SUCCESS**
Build succeeded for 3 out of 3 (3 easyconfigs in this PR)
b-an03.hpc2n.umu.se - Linux ubuntu 16.04, Intel(R) Xeon(R) CPU E5-2690 v4 @ 2.60GHz, Python 2.7.12
See https://gist.github.com/5fa1c3680a2648a79f1058736047ff19 for a full test report.

**Comment by verdurin** [comment]
@Micket could you provide a test report for this?

**Comment by akesandgren** [comment]
Going in, thanks @Micket!

**Comment by verdurin** [comment]
Test report by @verdurin
**FAILED**
Build succeeded for 13 out of 19 (3 easyconfigs in this PR)
rescomp2 - Linux centos linux 7.3.1611, Intel(R) Xeon(R) Gold 6126 CPU @ 2.60GHz, Python 2.7.5
See https://gist.github.com/bbd9b3edaf6c5ff90514f3e0c9dbd804 for a full test report.

**Pull request merged**
