### PR TITLE
add libvdwxc-0.4.0-foss-2020a.eb

### PR DESCRIPTION
**Pull request by xwuupb**

### CODE REVIEW

**Comment by xwuupb** [comment]
libvdwxc-0.4.0-foss-2020a.eb is ready to be merged.

**Review by Micket — APPROVED** [review]
lgtm

**Comment by Micket** [comment]
Test report by @Micket
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
vera-c1 - Linux centos linux 7.9.2009, x86_64, Intel Xeon Processor (Skylake), Python 2.7.5
See https://gist.github.com/d70caf3c03c0a667140ee9af0d4e4eea for a full test report.

**Comment by Micket** [comment]
Going in, thanks @xwuupb!

**Pull request merged**
