### PR TITLE
Pandoc version 2.10

### PR DESCRIPTION
**Pull request by sassy-crick**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by sassy-crick** [comment]
I am not sure why @boegelbot is picking up the https bit as the EC file has been changed yesterday and he only reports it today.

**Comment by boegel** [comment]
@sassy-crick The bot picked up the failing tests for commit 2cc8997, saw that the PR is still not passing all tests with the latest commit (because tests are failing in Travis), and thus proceeds to submit the comment.

It should only do so when the failing workflow in GitHub Actions was for the most recent commit in the PR, I'll fix that logic...

**Comment by boegel** [comment]
@sassy-crick That issue should be fixed now, @boegelbot will now ignore failing workflows if they were not run for the most recent commit of a PR...

**Comment by smoors** [comment]
Test report by @smoors
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
node350.hydra.os - Linux centos linux 7.7.1908, x86_64, Intel(R) Xeon(R) Gold 6148 CPU @ 2.40GHz (skylake_avx512), Python 2.7.5
See https://gist.github.com/ce2c29a47d85c1461d1bd74f41471969 for a full test report.

**Comment by smoors** [comment]
one Travis test failed because of >10 minutes timeout.
will merge manually.

**Pull request merged**
