### PR TITLE
{lang}[GCCcore/11.3.0] CUnit v2.1.3

### PR DESCRIPTION
**Pull request by iotaka**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by smoors** [comment]
@boegelbot: please test @ generoso

**Comment by smoors** [comment]
@boegelbot: please test @ generoso

**Comment by smoors** [comment]
@boegelbot please test @ jsc-zen2

**Review by smoors — APPROVED** [review]
lgtm

**Comment by smoors** [comment]
Going in, thanks @iotaka!

**Comment by iotaka** [comment]
wrong name i nthe title for CUnit v2.1.3  is 2.1**-3**

https://sourceforge.net/projects/cunit/files/CUnit/2.1-3/

**Pull request merged**
