### PR TITLE
{phys}[GCC/12.3.0] YODA v1.9.9

### PR DESCRIPTION
**Pull request by APN-Pucky**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by APN-Pucky** [comment]
@boegelbot please test @ generoso

**Comment by boegel** [comment]
@boegelbot please test @ generoso

**Review by boegel — APPROVED** [review]
lgtm

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
node3138.skitty.os - Linux RHEL 8.8, x86_64, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz (skylake_avx512), Python 3.6.8
See https://gist.github.com/boegel/e384915d5c9d6c2b4883e6867928b8bb for a full test report.

**Comment by boegel** [comment]
@boegelbot please test @ jsc-zen2

**Comment by boegel** [comment]
@boegelbot please test @ jsc-zen2

**Comment by boegel** [comment]
Going in, thanks @APN-Pucky!

**Pull request merged**
