### PR TITLE
{tools}[foss/2022a] umap-learn v0.5.3 w/ Python 3.10.4

### PR DESCRIPTION
**Pull request by migueldiascosta**
(created using `eb --new-pr`)

requires:
* #17148

### CODE REVIEW

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
node3129.skitty.os - Linux RHEL 8.6, x86_64, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz (skylake_avx512), Python 3.6.8
See https://gist.github.com/e582e482b5f210ea59472e628797b3af for a full test report.

**Comment by boegel** [comment]
@boegelbot please test @ generoso

**Comment by boegel** [comment]
Since #17148 is merged, I think we can go ahead with this one too.

@migueldiascosta Is there a particular reason this is still marked as WIP?

**Comment by migueldiascosta** [comment]
> Since #17148 is merged, I think we can go ahead with this one too.
> 
> @migueldiascosta Is there a particular reason this is still marked as WIP?

I think it was because the PRs I had linked to had only CUDA versions of numba, but with #17148 that's solved, so removing the WIP

**Comment by boegel** [comment]
@boegelbot please test @ jsc-zen2

**Review by boegel — APPROVED** [review]
lgtm

**Comment by boegel** [comment]
Going in, thanks @migueldiascosta!

**Pull request merged**
