### PR TITLE
fix build of OpenBLAS 0.3.24 on A64FX

### PR DESCRIPTION
**Pull request by boegel**
(created using `eb --new-pr`)

fix for:
```
make[1]: *** No rule to make target '../kernel/arm64/sgemm_ncopy_sve_v1.c', needed by 'sgemm_incopy.o'.  Stop.
make[1]: *** Waiting for unfinished jobs....
make[1]: Leaving directory '/tmp/kehoste/easybuild/build/OpenBLAS/0.3.24/GCC-13.2.0/OpenBLAS-0.3.24/kernel'
```

### CODE REVIEW

**Comment by boegel** [comment]
@boegelbot please test @ generoso
EB_ARGS="--installpath /tmp/$USER/pr20820"

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
node3111.skitty.os - Linux RHEL 8.8, x86_64, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz, Python 3.6.8
See https://gist.github.com/boegel/37cc783e5405aaceda3b7e3e1f911639 for a full test report.

**Comment by boegel** [comment]
@boegelbot please test @ jsc-zen3
EB_ARGS="--installpath /tmp/$USER/pr20820"

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
aarch64-neoverse-n1-node1.int.aws-rocky88-202310.eessi.io - Linux Rocky Linux 8.8, AArch64, ARM UNKNOWN (neoverse_n1), Python 3.6.8
See https://gist.github.com/boegel/bb16743258ecf8ae6935151ecb477134 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**FAILED**
Build succeeded for 2 out of 22 (1 easyconfigs in total)
cna0794.deucalion.macc.fccn.pt - Linux Rocky Linux 8.5, AArch64, UNKNOWN (a64fx), Python 3.6.8
See https://gist.github.com/boegel/dca32eec14b74b79492dcc02259a9f7a for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
cna1188.deucalion.macc.fccn.pt - Linux Rocky Linux 8.5, AArch64, UNKNOWN (a64fx), Python 3.6.8
See https://gist.github.com/boegel/c0ab77add7aa4dd26099bcfc89991d5c for a full test report.

**Review by ocaisa — APPROVED** [review]
LGTM

**Pull request merged**
