### PR TITLE
{ai}[GCCcore/11.3.0,foss/2022a] PyTorchVideo v0.1.5, PyAV v10.0.0, parameterized v0.9.0 w/ PyTorch 1.12.0, PyTorch 1.12.0 CUDA 11.7.0

### PR DESCRIPTION
**Pull request by lexming**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by lexming** [comment]
@boegelbot: please test @ generoso

**Comment by lexming** [comment]
@boegelbot: please test @ generoso

**Review by smoors — APPROVED** [review]
lgtm

**Comment by smoors** [comment]
Going in, thanks @lexming!

**Pull request merged**
