### PR TITLE
Version 1.47 of Stacks using the foss-2016a toolchain.

### PR DESCRIPTION
**Pull request by FokkeDijkstra**
Version 1.47 of Stacks using the foss-2016a toolchain. hstacks and estacks are no longer included in this version.

### CODE REVIEW

**Comment by verdurin** [comment]
Test report by @verdurin
**FAILED**
Build succeeded for 6 out of 26 (1 easyconfigs in this PR)
dell.lan - Linux fedora 26, Intel(R) Core(TM) i7-4600U CPU @ 2.10GHz, Python 2.7.13
See https://gist.github.com/7898f8db3073a36361e3726dd239da63 for a full test report.

**Comment by boegel** [comment]
@verdurin Hmm, for some reason `GCCcore` 4.9.3 failed to build on your test system? Seems like an issue with your system compiler:

```
configure: error: C compiler cannot create executables
See `config.log' for more details.
```

**Comment by verdurin** [comment]
@boegel I suspect it's because the system `gcc` is too new - `7.2.1` on `Fedora 26`.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
node2129.delcatty.os - Linux centos linux 7.4.1708, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.7.5
See https://gist.github.com/fe6313ecbf65f1edc472cc18f0e1a89a for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 14 out of 14 (1 easyconfigs in this PR)
node2627.swalot.os - Linux centos linux 7.4.1708, Intel(R) Xeon(R) CPU E5-2660 v3 @ 2.60GHz, Python 2.7.5
See https://gist.github.com/33bdfd6cd6f1c457cf7ba7683761b1a4 for a full test report.

**Comment by boegel** [comment]
Going in, thanks @FokkeDijkstra!

**Pull request merged**
