### PR TITLE
{bio}[GCCcore/11.2.0] MinPath v1.6 w/ Python 3.9.6

### PR DESCRIPTION
**Pull request by ItIsI-Orient**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by ItIsI-Orient** [comment]
Test report by @ItIsI-Orient
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
node3202.victini.os - Linux UNKNOWN UNKNOWN, x86_64, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz, Python 3.6.8
See https://gist.github.com/6741b69034043615d8b7f256b422ff6c for a full test report.

**Review by boegel — CHANGES_REQUESTED** [review]
@ItIsI-Orient We should also remove the `MinPath` easyconfig that uses `intel/2021b` that was added in #14700, since that doesn't make much sense anymore?

This then essentially become a rename + toolchain switch from `MinPath-1.6-intel-2021b.eb` to `MinPath-1.6-GCCcore-11.2.0.eb` (which makes sense imho)

**Review by boegel — APPROVED** [review]

**Comment by boegel** [comment]
@boegelbot please test @ generoso

**Comment by boegel** [comment]
@boegelbot please test @ jsc-zen2

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
node2607.swalot.os - Linux UNKNOWN UNKNOWN, x86_64, Intel(R) Xeon(R) CPU E5-2660 v3 @ 2.60GHz (haswell), Python 3.6.8
See https://gist.github.com/cc4f3b1110fb9be01743702a078be5de for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
node3526.doduo.os - Linux UNKNOWN UNKNOWN, x86_64, AMD EPYC 7552 48-Core Processor (zen2), Python 3.6.8
See https://gist.github.com/0d51c477a3d27770c704235c8d3c0682 for a full test report.

**Comment by boegel** [comment]
@boegelbot please test @ jsc-zen2

**Comment by boegel** [comment]
Going in, thanks @ItIsI-Orient!

**Comment by boegel** [comment]
Going in, thanks @ItIsI-Orient!

**Pull request merged**
