### PR TITLE
{bio}[foss/2018b] PyNAST v1.2.2, PyCogent v1.9

### PR DESCRIPTION
**Pull request by SethosII**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by vanzod** [comment]
@SethosII Please add the following to both easyconfig files for consistency with the way in which we install Python packages:
```
download_dep_fail = True
use_pip = True
```

**Comment by SethosII** [comment]
@vanzod I changed the easyconfigs to use pip.

**Comment by vanzod** [comment]
Test report by @vanzod
**SUCCESS**
Build succeeded for 3 out of 3 (2 easyconfigs in this PR)
cermis - Linux debian 9.7, Intel(R) Xeon(R) CPU           E5620  @ 2.40GHz, Python 2.7.13
See https://gist.github.com/2f3e98d8bbe031c4e9acba1e131ab655 for a full test report.

**Comment by vanzod** [comment]
Going in, thanks @SethosII!

**Pull request merged**
