### PR TITLE
{bio}[GCC/11.3.0] samblaster v0.1.26

### PR DESCRIPTION
**Pull request by verdurin**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by verdurin** [comment]
Test report by @verdurin
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
easybuild-c7.novalocal - Linux CentOS Linux 7.9.2009, x86_64, Intel Xeon Processor (Skylake, IBRS), Python 3.6.8
See https://gist.github.com/verdurin/7ea093b9ee5e5954b91972b69b4e3d10 for a full test report.

**Comment by verdurin** [comment]
@boegelbot please test @ generoso

**Comment by verdurin** [comment]
@boegelbot please test @ jsc-zen2

**Review by casparvl — APPROVED** [review]
Straightforward update, only thing updated was the toolchain. So: no surprises here. Only the test from `jsc-zen2` didn't come back. I'll see if I can try this locally to get one more test report in. Otherwise: lgtm!

**Comment by casparvl** [comment]
Test report by @casparvl
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
tcn453.local.snellius.surf.nl - Linux Rocky Linux 8.7, x86_64, AMD EPYC 7H12 64-Core Processor, Python 3.6.8
See https://gist.github.com/casparvl/30d3f75e3772c2fdaffc78104a3adfb3 for a full test report.

**Comment by casparvl** [comment]
Going in, thanks @verdurin!

**Pull request merged**
