### PR TITLE
{tools}[GCC/11.2.0] mctc-lib v0.3.1

### PR DESCRIPTION
**Pull request by sassy-crick**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by SebastianAchilles** [comment]
@boegelbot please test @ generoso

**Comment by bedroge** [comment]
@sassy-crick I just found another PR that includes `mctc-lib`: #16760. That one uses `GCCcore`, is there a good reason for using `GCC`? 
There's some other things from that PR that I'd prefer to use as well, e.g. the sanity check command and building shared libraries. The `chem` module class is maybe also more appropriate?

**Comment by sassy-crick** [comment]
> @sassy-crick I just found another PR that includes `mctc-lib`: #16760. That one uses `GCCcore`, is there a good reason for using `GCC`? There's some other things from that PR that I'd prefer to use as well, e.g. the sanity check command and building shared libraries. The `chem` module class is maybe also more appropriate?

Agreed. I will close that PR in favour of #16760.

**Comment by sassy-crick** [comment]
Duplicate of #16760, closed

**Pull request closed without merging**
