### PR TITLE
{lib}[GCCcore/8.3.0] CIF2Cell v1.2.10 w/ Python 2.7.16

### PR DESCRIPTION
**Pull request by akesandgren**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by akesandgren** [comment]
Test report by @akesandgren
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in total)
b-an02.hpc2n.umu.se - Linux ubuntu 16.04, x86_64, Intel(R) Xeon(R) CPU E5-2690 v4 @ 2.60GHz, Python 2.7.12
See https://gist.github.com/31ebf7ca12ed9a764eb5c14e25bee1d7 for a full test report.

**Comment by akesandgren** [comment]
@boegelbot please test @ generoso

**Comment by akesandgren** [comment]
@boegelbot please test @ generoso

**Review by Micket — APPROVED** [review]
lgtm

**Comment by Micket** [comment]
Test report by @Micket
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in total)
hebbe-c1 - Linux centos linux 7.9.2009, x86_64, Intel Core Processor (Haswell, no TSX), Python 2.7.5
See https://gist.github.com/331a2e0f6f0640ba49384b12564a7b4a for a full test report.

**Comment by verdurin** [comment]
Going in, thanks @akesandgren!

**Pull request merged**
