### PR TITLE
{phys}[foss/2023a] CASTEP v23.1

### PR DESCRIPTION
**Pull request by Micket**
(created using `eb --new-pr`)

I see no reason not to include python and numpy as a dep.

### CODE REVIEW

**Comment by Micket** [comment]
Test report by @Micket
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
vera-skylake-build - Linux Rocky Linux 8.8, x86_64, Intel Xeon Processor (Skylake, IBRS, no TSX), Python 3.6.8
See https://gist.github.com/Micket/aae8b1d3e84fb7618e3fc0743977194e for a full test report.

**Comment by Micket** [comment]
Test report by @Micket
**SUCCESS**
Build succeeded for 7 out of 7 (1 easyconfigs in total)
vera-icelake-build - Linux Rocky Linux 8.8, x86_64, Intel(R) Xeon(R) Silver 4316 CPU @ 2.30GHz, Python 3.6.8
See https://gist.github.com/Micket/81d0bed16d47b7f2c9a1d7c02f8a1b21 for a full test report.

**Comment by Micket** [comment]
Test report by @Micket
**SUCCESS**
Build succeeded for 7 out of 7 (1 easyconfigs in total)
vera-skylake-build - Linux Rocky Linux 8.8, x86_64, Intel Xeon Processor (Skylake, IBRS, no TSX), Python 3.6.8
See https://gist.github.com/Micket/5f7fbee8c724c3d95d7dc22ae4be163b for a full test report.

**Comment by casparvl** [comment]
@boegelbot please test @ generoso

**Review by casparvl — APPROVED** [review]
Can't really test this since it is properietary software, but just reviewing the EasyConfig it looks reasonable engouh. Also, plenty of test reports already by @Micket , so fine by me.

**Comment by casparvl** [comment]
Going in, thanks @Micket!

**Pull request merged**
