### PR TITLE
don't use harmful patch for h5py 2.10.0 with foss/2020a + pull out h5py 2.10.0 easyconfig using intel/2020a

### PR DESCRIPTION
**Pull request by boegel**
The saga continues...

The patch added in #10626 isn't working out well, since it has the nasty side-effect of changing the default auto-`MPI_Init` behavior of `mpi4py`, which causes surprises for any Python scripts using both `h5py` and `mpi4py`.

A better fix that doesn't involve disabling the auto-init done by `mpi4py` (just postponing it until actual MPI features are being used) is being discussed in https://github.com/h5py/h5py/pull/1544, but it doesn't seem like it will be a trivial change.

Since the problem only presents itself when using `intel/2020a`

### CODE REVIEW

**Comment by verdurin** [comment]
Test report by @verdurin
**SUCCESS**
Build succeeded for 0 out of 0 (1 easyconfigs in this PR)
easybuild.novalocal - Linux centos linux 7.8.2003, Intel Xeon Processor (Skylake, IBRS), Python 2.7.5
See https://gist.github.com/676217e0da7c9b80ef7ff1f04c31ea96 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
generoso - Linux centos linux 7.6.1810, x86_64, Intel(R) Xeon(R) CPU E5-2660 v4 @ 2.00GHz, Python 3.6.8
See https://gist.github.com/7fd1237930ea90a2b3c5f586739204c3 for a full test report.

**Comment by verdurin** [comment]
Test report by @verdurin
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
easybuild.novalocal - Linux centos linux 7.8.2003, Intel Xeon Processor (Skylake, IBRS), Python 2.7.5
See https://gist.github.com/e0d3a3c0615a5361aaef1c9d856c7e59 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
node3407.kirlia.os - Linux centos linux 7.7.1908, x86_64, Intel(R) Xeon(R) Gold 6240 CPU @ 2.60GHz (cascadelake), Python 2.7.5
See https://gist.github.com/f99ac7c6b6739a72f741a98188f4d35e for a full test report.

**Comment by casparvl** [comment]
Test report by @casparvl
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
tcn900.bullx - Linux RHEL 7.7, x86_64, Intel(R) Xeon(R) CPU E5-2690 v3 @ 2.60GHz, Python 2.7.5
See https://gist.github.com/539dfa9af82ff17a0c8efda08deacc0f for a full test report.

**Comment by akesandgren** [comment]
Test report by @akesandgren
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
b-an03.hpc2n.umu.se - Linux ubuntu 16.04, x86_64, Intel(R) Xeon(R) CPU E5-2690 v4 @ 2.60GHz, Python 2.7.12
See https://gist.github.com/8a342adcce3099b26a59c917d72edb49 for a full test report.

**Pull request merged**
