### PR TITLE
{bio,lib}[GCC/11.2.0,GCCcore/11.2.0] Clustal-Omega v1.2.4, argtable v2.13

### PR DESCRIPTION
**Pull request by SethosII**
(created using `eb --new-pr`)

The argtables homepage changed. I opened another pull request for the existing easyconfigs: https://github.com/easybuilders/easybuild-easyconfigs/pull/19551.

### CODE REVIEW

**Comment by smoors** [comment]
@boegelbot please test @ jsc-zen2

**Comment by smoors** [comment]
@boegelbot: please test @ generoso

**Review by Micket — APPROVED** [review]
lgtm

**Comment by Micket** [comment]
Test report by @Micket
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in total)
alvis2-05 - Linux Rocky Linux 8.9, x86_64, Intel(R) Xeon(R) Gold 6226R CPU @ 2.90GHz, 8 x NVIDIA Tesla T4, 550.54.14, Python 3.6.8
See https://gist.github.com/Micket/ed63b78eb9ff600b542c84717b95092f for a full test report.

**Comment by Micket** [comment]
Going in, thanks @SethosII!

**Pull request merged**
