### PR TITLE
{vis}[foss/2021b] matplotlib v3.5.2 w/ Python 3.9.6

### PR DESCRIPTION
**Pull request by ThomasHoffmann77**
(created using `eb --new-pr`)
requires:
* #16969

### CODE REVIEW

**Comment by smoors** [comment]
@ThomasHoffmann77 sorry I forgot about this, but you have to add Pillow as an extension to this matplotlib.

**Comment by ThomasHoffmann77** [comment]
> @ThomasHoffmann77 sorry I forgot about this, but you have to add Pillow as an extension to this matplotlib.
@smoors instead of loading Pillow/9.1.1 as a dependency?

**Comment by smoors** [comment]
@boegelbot: please test @ generoso

**Comment by smoors** [comment]
@boegelbot please test @ jsc-zen2

**Review by smoors — APPROVED** [review]
lgtm

**Comment by smoors** [comment]
Going in, thanks @ThomasHoffmann77!

**Pull request merged**
