### PR TITLE
{lib}[foss/2018b] imgaug v0.2.8

### PR DESCRIPTION
**Pull request by smoors**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by smoors** [comment]
Test report by @smoors
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in this PR)
nic407 - Linux centos linux 7.5.1804, Intel(R) Xeon(R) Gold 6148 CPU @ 2.40GHz, Python 2.7.5
See https://gist.github.com/03eb4dc94fe26b4a9c41aea6963bcc55 for a full test report.

**Comment by akesandgren** [comment]
OpenCV in this one should be dropped now that #7953 has been merged.
They looked identical when i checked.

**Comment by akesandgren** [comment]
Test report by @akesandgren
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
b-an03.hpc2n.umu.se - Linux ubuntu 16.04, Intel(R) Xeon(R) CPU E5-2690 v4 @ 2.60GHz, Python 2.7.12
See https://gist.github.com/2473f3b361525258035f970c7b85cc7c for a full test report.

**Comment by akesandgren** [comment]
Going in, thanks @smoors!

**Pull request merged**
