### PR TITLE
{phys}[foss/2023b] CASTEP v24.1

### PR DESCRIPTION
**Pull request by tanmoy1989**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by tanmoy1989** [comment]
Can we have an update on this, please?

**Comment by branfosj** [comment]
Test report by @branfosj
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
bear-pg0105u03a - Linux RHEL 8.6, x86_64, Intel(R) Xeon(R) Platinum 8360Y CPU @ 2.40GHz (icelake), Python 3.6.8
See https://gist.github.com/branfosj/4e5330ea328beaa2d864b1daed6ac504 for a full test report.

**Review by branfosj — APPROVED** [review]

**Comment by branfosj** [comment]
Test report by @branfosj
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
bear-pg0210u03a.bear.cluster - Linux RHEL 8.6, x86_64, Intel(R) Xeon(R) Platinum 8480CL (sapphirerapids), Python 3.6.8
See https://gist.github.com/branfosj/9c1276b62b02849d589a63121bb58c3b for a full test report.

**Comment by branfosj** [comment]
Going in, thanks @tanmoy1989!

**Pull request merged**
