### PR TITLE
{data,tools,vis}[foss/2020b,intel/2020b] scikit-image v0.18.1, dask v2021.2.0, bokeh v2.2.3 w/ Python 3.8.6

### PR DESCRIPTION
**Pull request by schiotz**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by schiotz** [comment]
Scikit-image and dependencies.

**Comment by boegel** [comment]
@schiotz I've pushed a couple of (fairly minor) changes to this PR, I was working on the same thing (at least for `foss/2020b`) in parallel, and overlooked this PR at first (see #12267).

It boils down to leveraging existing easyconfigs where appropriate (for `networkx` and `typing-extensions`), enhancing the sanity checks a bit (by running a short command), some trivial extension updates in the `dask` easyconfigs, and a patch for `scikit-image` to fix a problem I ran into when using `eb --read-only-installdir` (cfr. https://github.com/scikit-image/scikit-image/pull/5249 and https://github.com/easybuilders/easybuild-easyconfigs/pull/12267#issuecomment-785312993).

**Comment by boegel** [comment]
@boegelbot please test @ generoso

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 7 out of 7 (7 easyconfigs in total)
node3152.skitty.os - Linux centos linux 7.9.2009, x86_64, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz, Python 3.6.8
See https://gist.github.com/89566b745a8560050124589f3f927360 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 7 out of 7 (7 easyconfigs in total)
node3521.doduo.os - Linux RHEL 8.2, x86_64, AMD EPYC 7552 48-Core Processor (zen2), Python 3.6.8
See https://gist.github.com/4857bc0ec2094d424bdb0559bed0acd5 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 7 out of 7 (7 easyconfigs in total)
node2685.swalot.os - Linux centos linux 7.9.2009, x86_64, Intel(R) Xeon(R) CPU E5-2660 v3 @ 2.60GHz (haswell), Python 3.6.8
See https://gist.github.com/38f6addc0951b44d1621646f48f854c4 for a full test report.

**Comment by verdurin** [comment]
Test report by @verdurin
**SUCCESS**
Build succeeded for 4 out of 4 (3 easyconfigs in total)
nuc.lan - Linux Fedora 32, x86_64, Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz, Python 3.8.7
See https://gist.github.com/4c066338bbe7e4c8088ebca435165db8 for a full test report.

**Comment by schiotz** [comment]
@boegel 
Thanks for approving and improving my PR!  :-)

**Comment by verdurin** [comment]
Test report by @verdurin
**SUCCESS**
Build succeeded for 17 out of 17 (3 easyconfigs in total)
easybuild-c7.novalocal - Linux centos linux 7.9.2009, x86_64, Intel Xeon Processor (Skylake, IBRS), Python 3.6.8
See https://gist.github.com/87a507e458e06e017bb80a700e7d1c09 for a full test report.

**Review by verdurin — APPROVED** [review]
Looks fine.

**Comment by verdurin** [comment]
Going in, thanks @schiotz!

**Pull request merged**
