### PR TITLE
{vis}[GCC/10.2.0] wxWidgets v3.1.4

### PR DESCRIPTION
**Pull request by akesandgren**
(created using `eb --new-pr`)

Depends on ~~#12584~~

### CODE REVIEW

**Comment by akesandgren** [comment]
@boegelbot Please test @ generoso

**Review by boegel — APPROVED** [review]
lgtm

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 3 out of 3 (1 easyconfigs in total)
node3532.doduo.os - Linux RHEL 8.2, x86_64, AMD EPYC 7552 48-Core Processor (zen2), Python 3.6.8
See https://gist.github.com/123b07cf4a35ad1617e15aa4c306c6ee for a full test report.

**Comment by boegel** [comment]
Going in, thanks @akesandgren!

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 14 out of 14 (1 easyconfigs in total)
node3104.skitty.os - Linux centos linux 7.9.2009, x86_64, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz, Python 3.6.8
See https://gist.github.com/fd2fe1349a0fb2ec93951223e10a9277 for a full test report.

**Pull request merged**
