### PR TITLE
{devel}[GCCcore/10.2.0] Qt5 v5.14.2

### PR DESCRIPTION
**Pull request by Micket**
(created using `eb --new-pr`)
depends on ~~#11536~~

### CODE REVIEW

**Comment by Micket** [comment]
Test report by @Micket
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
vera-c1 - Linux centos linux 7.8.2003, x86_64, Intel Xeon Processor (Skylake), Python 2.7.5
See https://gist.github.com/af0f9b39ec8ccc26d7efd1f59ee883da for a full test report.

**Review by boegel — DISMISSED** [review]
lgtm

**Comment by boegel** [comment]
@boegelbot please test @ generoso

**Comment by Micket** [comment]
Note: I tried to build PyQt on top of this without success, but I can't spot anything wrong with this particular build, so, maybe it's some lack of support in PyQt yet(?)

**Comment by boegel** [comment]
@Micket Any log you can share?

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 13 out of 13 (1 easyconfigs in total)
node3401.kirlia.os - Linux centos linux 7.8.2003, x86_64, Intel(R) Xeon(R) Gold 6240 CPU @ 2.60GHz (cascadelake), Python 2.7.5
See https://gist.github.com/460a6cb35133bd8ddf7aef54a06bf7e2 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 13 out of 13 (1 easyconfigs in total)
node2452.golett.os - Linux centos linux 7.8.2003, x86_64, Intel(R) Xeon(R) CPU E5-2680 v3 @ 2.50GHz (haswell), Python 2.7.5
See https://gist.github.com/1954d3d5f7da6fb18ca92ec83c4cc165 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 13 out of 13 (1 easyconfigs in total)
node3109.skitty.os - Linux centos linux 7.8.2003, x86_64, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz, Python 3.6.8
See https://gist.github.com/46f3e9898e9f4a3a9b27bb7df80edd11 for a full test report.

**Comment by smoors** [comment]
Test report by @smoors
**SUCCESS**
Build succeeded for 23 out of 23 (1 easyconfigs in total)
node378.hydra.os - Linux centos linux 7.7.1908, x86_64, Intel(R) Xeon(R) Gold 6148 CPU @ 2.40GHz (skylake_avx512), Python 2.7.5
See https://gist.github.com/6491a8ec79f47e35d05fa5c77ab32f48 for a full test report.

**Comment by zao** [comment]
Test report by @zao
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
freja - Linux Ubuntu 20.04, x86_64, Intel(R) Core(TM) i7-8700K CPU @ 3.70GHz (skylake), Python 3.8.5
See https://gist.github.com/e913422b7e2b76fbc42cf4980a439dda for a full test report.

**Review by lexming — DISMISSED** [review]
LGTM

**Comment by Micket** [comment]
So, how do we deal with the CentOS7 (and similarly old) OS'es. Let them opt in to use the OpenSSL dependency? It's going to quietly "fail" and just skip the components that need OpenSSL, so people are going to discovered they needed to modify the easyconfig when they get around to building PyQt5, which sucks.

There is also a openssl11 package in CentOS7, so, we could try to get it to use that with some extra build flags maybe to make it work by default for everyone, but, again, the dynamic behavior here is annoying. Customize easyblock to support openssl11?

Should we introduce a "OS_PKG_OPENSSL11_DEV" ? Hard to find an optimal solution here.

**Comment by lexming** [comment]
I think that we have two options:
1. Make OpenSSL v1.1 mandatory for Qt5 and update the `qt` easyblock to check the OpenSSL v1.1 support, either through an EB dependency or through an OS dependency.
2. Make the PyQt5 easyconfig check beforehand for support of OpenSSL in QtConfig and fail the build otherwise (or disable PyQtWebEngine). This option needs writing a small Qt program to check QtConfig and ship that in the easyconfig of PyQt5. Not a lot of work, but adds maintenance burden.

My vote goes for option 1.

**Comment by boegel** [comment]
The discussion is a bit split between this PR and #11563, but taking into account both I'm not sure what our best way forward is here...

If we go with Qt5 5.15.1 then we should consider it incompatible with CentOS 7, where OpenSSL 1.0.x is provided by the OS...

I don't consider using an OpenSSL 1.1.x provided as dependency via EasyBuild a good idea with security in mind, even if we only used it as a build dependency and statically link it in to Qt5.

One option could be creating an `OpenSSL/1.1` wrapper, so the underlying installation can be updated in place (similar to `Java`, see https://easybuild.readthedocs.io/en/latest/Wrapping_dependencies.html), but even then I'm reluctant to start doing this.

Is this a good enough reason to stick to Qt5 5.14.x in the 2020b generation of easyconfigs?
That's just postponing the problem though, it'll resurface again...

**Comment by Micket** [comment]
If we downgrade to 5.14.x again, and postpone this until 2021, then we could consider actually start to *always* build OpenSSL by default, using a wrapper. This would be easier if everything under GCCcore started to link with an EB-provided OpenSSL by default. 
Those who prefer the OS-dependency would simply have to opt out with filter-deps.

**Comment by zao** [comment]
From an armchair security perspective, I'd expect that TLS support in scientific software would be more for client-initiated connections and less about serving as it's quite unlikely that anything has actual certificates anyway, reducing the attack surface greatly as there's no real secrets to leak.

How up to date does a client TLS stack have to be? It would assumedly still use the distro's CA certificate collection?

**Comment by Micket** [comment]
I think the pain point right now is mostly about ABI compatibility of OpenSSL 1.0 vs 1.1, even if we didn't care about keeping it updated, it wouldn't solve the issue we are facing here:
1. We don't want a gimped Qt5 without QtNetwork
2. We don't want to introduce OpenSSL 1.1 just for this library, and have all other libraries link to 1.0 since it would make linking to both hard/impossible
So, it just really sucks for CentOS7 and other older OS'es to update to 5.15

Regarding security, i think it's more about CVE's rather than updated certificates(?)

**Comment by zao** [comment]
> Regarding security, i think it's more about CVE's rather than updated certificates(?)

The point I tried to make there is that there's not that many CVEs that affect client software that make controlled outgoing connections.

**Comment by Micket** [comment]
Test report by @Micket
**FAILED**
Build succeeded for 0 out of 1 (1 easyconfigs in total)
vera-c1 - Linux centos linux 7.8.2003, x86_64, Intel Xeon Processor (Skylake), Python 2.7.5
See https://gist.github.com/e282c688f306f8c15a78189800543d81 for a full test report.

**Comment by Micket** [comment]
Test report by @Micket
**FAILED**
Build succeeded for 0 out of 1 (1 easyconfigs in total)
vera-c1 - Linux centos linux 7.8.2003, x86_64, Intel Xeon Processor (Skylake), Python 2.7.5
See https://gist.github.com/1404bf840719f426d878b21e480d9faa for a full test report.

**Comment by Micket** [comment]
Test report by @Micket
**FAILED**
Build succeeded for 0 out of 1 (1 easyconfigs in total)
vera-c1 - Linux centos linux 7.8.2003, x86_64, Intel Xeon Processor (Skylake), Python 2.7.5
See https://gist.github.com/d63b7324252b2b7afa443d14d6bbc0ea for a full test report.

**Comment by boegel** [comment]
@boegelbot please test @ generoso

**Comment by Micket** [comment]
Test report by @Micket
**SUCCESS**
Build succeeded for 22 out of 22 (1 easyconfigs in total)
alvis-c1 - Linux centos linux 7.8.2003, x86_64, Intel Xeon Processor (Skylake), Python 3.6.8
See https://gist.github.com/a74c31faa364c7005829122998762e77 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**FAILED**
Build succeeded for 0 out of 1 (1 easyconfigs in total)
node3573.doduo.os - Linux RHEL 8.2, x86_64, AMD EPYC 7552 48-Core Processor (zen2), Python 3.6.8
See https://gist.github.com/342283ee9c3961375c25ae691a4cd452 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
node3403.kirlia.os - Linux centos linux 7.8.2003, x86_64, Intel(R) Xeon(R) Gold 6240 CPU @ 2.60GHz (cascadelake), Python 3.6.8
See https://gist.github.com/e9c1bf62d65fdc0da8d383b99a948e92 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
node2610.swalot.os - Linux centos linux 7.8.2003, x86_64, Intel(R) Xeon(R) CPU E5-2660 v3 @ 2.60GHz (haswell), Python 3.6.8
See https://gist.github.com/763a0868250866830ae1e2b67ce412e0 for a full test report.

**Comment by boegel** [comment]
@boegelbot please test @ generoso

**Comment by boegel** [comment]
Test report by @boegel
**FAILED**
Build succeeded for 0 out of 1 (1 easyconfigs in total)
node3163.skitty.os - Linux centos linux 7.8.2003, x86_64, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz, Python 3.6.8
See https://gist.github.com/9a6a79e6cd36d60aeb87bdc0db49f9cf for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
node3551.doduo.os - Linux RHEL 8.2, x86_64, AMD EPYC 7552 48-Core Processor (zen2), Python 3.6.8
See https://gist.github.com/12ce7f44b164014e5142bd43a3df129e for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
node3410.kirlia.os - Linux centos linux 7.8.2003, x86_64, Intel(R) Xeon(R) Gold 6240 CPU @ 2.60GHz (cascadelake), Python 3.6.8
See https://gist.github.com/fa6e0ec54245a7a78ed3b664afa902eb for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
node3170.skitty.os - Linux centos linux 7.8.2003, x86_64, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz, Python 3.6.8
See https://gist.github.com/bccaa5f8e34cfd4c91e62763859feb02 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
node2628.swalot.os - Linux centos linux 7.8.2003, x86_64, Intel(R) Xeon(R) CPU E5-2660 v3 @ 2.60GHz (haswell), Python 3.6.8
See https://gist.github.com/3143d79e33ba3e06b378300efba2f1dd for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**FAILED**
Build succeeded for 39 out of 40 (1 easyconfigs in total)
node3204.victini.os - Linux centos linux 7.8.2003, x86_64, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz (skylake_avx512), Python 3.6.8
See https://gist.github.com/eb7d5e16470f91b395c91967ea7d963b for a full test report.

**Comment by Micket** [comment]
> Test report by @boegel
> **FAILED**
> Build succeeded for 39 out of 40 (1 easyconfigs in total)
> node3204.victini.os - Linux centos linux 7.8.2003, x86_64, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz (skylake_avx512), Python 3.6.8
> See https://gist.github.com/eb7d5e16470f91b395c91967ea7d963b for a full test report.

oh what the heck is this now

**Comment by Micket** [comment]
Test report by @Micket
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
hebbe-c1 - Linux centos linux 7.8.2003, x86_64, Intel Core Processor (Haswell, no TSX), Python 2.7.5
See https://gist.github.com/718b5132874a09069c791bd73f5cd58f for a full test report.

**Comment by Micket** [comment]
Test report by @Micket
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
vera-c1 - Linux centos linux 7.8.2003, x86_64, Intel Xeon Processor (Skylake), Python 2.7.5
See https://gist.github.com/934902004dea55dbc74579107b6dba2a for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
node3210.victini.os - Linux centos linux 7.8.2003, x86_64, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz (skylake_avx512), Python 3.6.8
See https://gist.github.com/480d7816da26adde5542ff56d8ab0f44 for a full test report.

**Review by boegel — APPROVED** [review]
lgtm

**Comment by boegel** [comment]
Going in, thanks @Micket!

**Pull request merged**
