### PR TITLE
Amber: update urls, use variables and add checksums

### PR DESCRIPTION
**Pull request by SethosII**
Replacement for https://github.com/easybuilders/easybuild-easyconfigs/pull/8404.

### CODE REVIEW

**Comment by SethosII** [comment]
Should I include Python in the `versionsuffix` and easyconfig name?

**Comment by SethosII** [comment]
I added Python to the versionsuffix where it was missing.

I don't know where the certificate errors are coming from.

**Comment by zao** [comment]
@SethosII Browsers also complain about their certificate and if you force it through, the website you end up on is for Institute for Quantitative Biomedicine (IQB), not Amber.

Upstream has broken itself :tada:

**Comment by akesandgren** [comment]
The "home" url is wrong, it should only be http://ambermd.org/ (and please don't use %(name)s in the home url)

The problem here is that easybuild's tests check for the existence of a working https://... url and ambermd.org's certificate lacks the required SAN for ambermd.org

I'll poke them a bit to see if they can fix that.

**Comment by akesandgren** [comment]
Amber devs poked.

**Comment by zao** [comment]
An EB workaround would be to add the software to the whitelist in https://github.com/easybuilders/easybuild-easyconfigs/blob/develop/test/easyconfigs/easyconfigs.py#L463

**Comment by SethosII** [comment]
@akesandgren What is problematic about using variables in the `homepage`? I think that's what they are there for? And why not use a more specific URL? In case of Amber and AmberTools they would have the same `homepage`, but there are specific ones available.

**Comment by akesandgren** [comment]
the "problem" is that it is rarely usable and when trying to check things before making a new easyconfig one would like to just copy&paste the home page url from an earlier easyconfig without having to manually convert %(name)s.

As for Amber, the ambermd.org IS the home page for amber and ambertools, it clearly says so on the page. The others are for the current version of the packages. And http://ambermd.org/AmberMD.php clearly says that "Amber Home" is http://ambermd.org

**Comment by SethosII** [comment]
@akesandgren Ok, I will change this. Should we wait for the amber devs to decide whether to use https or not?

**Comment by akesandgren** [comment]
Amber now has a functioning cert for their https://

**Comment by boegel** [comment]
This PR only touches easyconfigs with a now [deprecated toolchain](https://docs.easybuild.io/en/latest/Deprecated-easyconfigs.html#deprecated-toolchains), so closing this...

**Pull request closed without merging**
