### PR TITLE
{lib}[GCCcore/13.2.0] Mesa v23.19, libunwind v1.6.2, LLVM v17.0.3, libdrm v2.4.117, libGLU v9.0.3, libglvnd v1.7.0

### PR DESCRIPTION
**Pull request by Micket**
(created using `eb --new-pr`)
- [x] requires #19056

### CODE REVIEW

**Comment by Micket** [comment]
Test report by @Micket
**FAILED**
Build succeeded for 4 out of 6 (6 easyconfigs in total)
alvis-c1 - Linux Rocky Linux 8.8, x86_64, Intel Xeon Processor (Skylake), Python 3.6.8
See https://gist.github.com/Micket/73a2d389a0f86c0ba357e52faf1fadeb for a full test report.

**Comment by Micket** [comment]
This mesa and LLVM wasn't compatible it seems. Decisions decisions.. wait for mesa or roll back LLVM?

**Comment by boegel** [comment]
@Micket We would need to stick to LLVM 16.x? That may be beneficial also for `numba`, perhaps...

**Comment by Micket** [comment]
Done (numba has always a pain anyway though, i wonder if we should just stick to letting llvmlite build it's own custom patched llvm like it wants)

**Comment by Micket** [comment]
Test report by @Micket
**SUCCESS**
Build succeeded for 6 out of 6 (6 easyconfigs in total)
alvis-c1 - Linux Rocky Linux 8.8, x86_64, Intel Xeon Processor (Skylake), Python 3.6.8
See https://gist.github.com/Micket/1721bc51b23a764d543694726b45cd93 for a full test report.

**Comment by Micket** [comment]
@boegelbot please test @ generoso

**Comment by Micket** [comment]
@boegelbot please test @ jsc-zen2

**Comment by verdurin** [comment]
Test report by @verdurin
**FAILED**
Build succeeded for 24 out of 56 (6 easyconfigs in total)
easybuild-c7.novalocal - Linux CentOS Linux 7.9.2009, x86_64, Intel Xeon Processor (Skylake, IBRS), Python 3.6.8
See https://gist.github.com/verdurin/e5246e48caaf64e1945ee0337d9a42e5 for a full test report.

**Comment by Micket** [comment]
@verdurin your checksum is off? try downloading again util-linux again maybe
```
== 2023-10-24 13:46:41,136 build_log.py:171 ERROR EasyBuild crashed with an error (at easybuild/base/exceptions.py:126 in __init__): Checksum verification for /eb/maint/sources/u/util-linux/util-linux-2.39.tar.gz using {'util-linux-2.39.tar.gz': 'b1f597ad172a2ee17b0a7ae4be7ab7e1b1a6f9394ddbd3d8ec90ae4ed7333579'} failed. (at easybuild/framework/easyblock.py:2457 in checksum_step)
``

**Comment by verdurin** [comment]
Test report by @verdurin
**SUCCESS**
Build succeeded for 9 out of 9 (6 easyconfigs in total)
easybuild-c7.novalocal - Linux CentOS Linux 7.9.2009, x86_64, Intel Xeon Processor (Skylake, IBRS), Python 3.6.8
See https://gist.github.com/verdurin/35a008e00be2ab823d338241485fde44 for a full test report.

**Review by verdurin — APPROVED** [review]
Looks fine.

**Comment by verdurin** [comment]
Going in, thanks @Micket!

**Pull request merged**
