### PR TITLE
{tools}[foss/2019b,fosscuda/2019b] torchaudio v0.5.0 w/ Python 3.7.4

### PR DESCRIPTION
**Pull request by arielzn**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by arielzn** [comment]
This fails because of not having some kind of `multideps PyTorch [1.3.1 , 1.4.0]` ?

**Comment by Micket** [comment]
It wants you to add a versionsuffix specifying which one of *PyTorch* you are using here.
Compare with torchvision that uses 1.4.0 as well

https://github.com/easybuilders/easybuild-easyconfigs/blob/develop/easybuild/easyconfigs/t/torchvision/torchvision-0.5.0-fosscuda-2019b-Python-3.7.4-PyTorch-1.4.0.eb

(normally, we try to stick to, 1 version per toolchain for dependencies, but since PyTorch is moving fast, a second version, 1.4.0, was added into 2019b, which we need to signal with a suffix)

**Comment by Micket** [comment]
Test report by @Micket
**SUCCESS**
Build succeeded for 3 out of 3 (2 easyconfigs in this PR)
vera-c1 - Linux centos linux 7.7.1908, Intel Xeon Processor (Skylake), Python 2.7.5
See https://gist.github.com/a10a8850626a0420df9f315cd9c775e5 for a full test report.

**Comment by Micket** [comment]
Test report by @Micket
**SUCCESS**
Build succeeded for 4 out of 4 (2 easyconfigs in this PR)
hebbe-c1 - Linux centos linux 7.7.1908, Intel Core Processor (Haswell, no TSX), Python 2.7.5
See https://gist.github.com/ed3de03e59ebff39e1a5ecc62fab0cce for a full test report.

**Comment by Micket** [comment]
Going in, thanks @arielzn!

**Pull request merged**
