### PR TITLE
Easyconfig for R-3.4.1 with updated packages

### PR DESCRIPTION
**Pull request by jdemeul**
Added easyconfig for current R-3.4.1 release and updated package versions as well as order

### CODE REVIEW

**Comment by verdurin** [comment]
Test report by @verdurin
**FAILED**
Build succeeded for 0 out of 1 (1 easyconfigs in this PR)
ca003.camp.thecrick.org - Linux centos linux 7.3.1611, Intel(R) Xeon(R) CPU E5-2640 v3 @ 2.60GHz, Python 2.7.5
See https://gist.github.com/aeb529b040f31787dabd80035a47c62e for a full test report.

**Comment by jdemeul** [comment]
@verdurin, I'll give compilation a go again as well.
RWekajars (and RWeka) have previously compiled successfully here multiple times, so not really sure what's going on. Hope the source is still the same. If it still fails, I'm inclined to remove both packages, as nothing else seems to depend on them (also from the Bioconductor packages).

**Comment by verdurin** [comment]
Test report by @verdurin
**FAILED**
Build succeeded for 0 out of 1 (1 easyconfigs in this PR)
ca005.camp.thecrick.org - Linux centos linux 7.3.1611, Intel(R) Xeon(R) CPU E5-2640 v3 @ 2.60GHz, Python 2.7.5
See https://gist.github.com/942af0b1aff872ab652a550cfd8baa5c for a full test report.

**Comment by boegel** [comment]
@jdemeul @verdurin You're probably hitting a recent kernel bug, see #4833

**Comment by jdemeul** [comment]
Seems to be fixed/fine on a CentOS 7.3.1611 instance (kernel release: 3.10.0-514.16.1.el7.x86_64):


#### Test result
Successfully built /home/centos/easyconfigs/R-3.4.1-foss-2016b-X11-20160819.eb

#### Overview of tested easyconfigs (in order)
 * **SUCCESS** _R-3.4.1-foss-2016b-X11-20160819.eb_

#### Time info
 * start: Tue, 05 Sep 2017 13:51:58 +0000 (UTC)
 * end: Tue, 05 Sep 2017 19:01:22 +0000 (UTC)

#### EasyBuild info
 * easybuild-framework version: 3.3.1
 * easybuild-easyblocks version: 3.3.1
 * command line:
```
eb R-3.4.1-foss-2016b-X11-20160819.eb -r --robot-paths :/home/centos/easyconfigs/
```
 * full configuration (includes defaults):
```
--add-dummy-to-minimal-toolchains
--allow-loaded-modules='EasyBuild'
--buildpath='/tmp'
--check-ebroot-env-vars='warn'
--cleanup-builddir
--cleanup-easyconfigs
--cleanup-tmpdir
--color='auto'
--configfiles='/etc/easybuild.cfg'
--default-opt-level='defaultopt'
--detect-loaded-modules='warn'
--disable-allow-modules-tool-mismatch
--disable-allow-use-as-root-and-accept-consequences
--disable-avail-cfgfile-constants
--disable-avail-easyconfig-constants
--disable-avail-easyconfig-licenses
--disable-avail-easyconfig-params
--disable-avail-easyconfig-templates
--disable-avail-module-naming-schemes
--disable-avail-modules-tools
--disable-avail-repositories
--disable-check-conflicts
--disable-check-github
--disable-check-style
--disable-consider-archived-easyconfigs
--disable-debug
--disable-debug-lmod
--disable-devel
--disable-dry-run
--disable-dry-run-short
--disable-dump-autopep8
--disable-dump-env-script
--disable-enforce-checksums
--disable-experimental
--disable-extended-dry-run
--disable-fixed-installdir-naming-scheme
--disable-force
--disable-hidden
--disable-ignore-osdeps
--disable-info
--disable-install-github-token
--disable-install-latest-eb-release
--disable-job
--disable-last-log
--disable-list-toolchains
--disable-logtostdout
--disable-minimal-toolchains
--disable-module-only
--disable-new-pr
--disable-package
--disable-pretend
--disable-quiet
--disable-read-only-installdir
--disable-rebuild
--disable-recursive-module-unload
--disable-regtest
--disable-rpath
--disable-sequential
--disable-set-default-module
--disable-show-config
--disable-show-default-configfiles
--disable-show-default-moduleclasses
--disable-show-full-config
--disable-skip
--disable-skip-test-cases
--disable-sticky-bit
--disable-terse
--disable-update-modules-tool-cache
--disable-upload-test-report
--disable-use-existing-modules
--disable-verify-easyconfig-filenames
--extended-dry-run-ignore-errors
--group-writable-installdir
--group='easybuild'
--ignore-dirs='.git,.svn'
--include-easyblocks=''
--include-module-naming-schemes=''
--include-toolchains=''
--installpath='/srv/sw/eb'
--job-backend='GC3Pie'
--job-max-walltime='24'
--job-output-dir='/home/centos'
--job-polling-interval='30.0'
--logfile-format='easybuild,easybuild-%(name)s-%(version)s-%(date)s.%(time)s.log'
--max-fail-ratio-adjust-permissions='0.5'
--module-naming-scheme='EasyBuildMNS'
--module-syntax='Lua'
--moduleclasses='base,bio,cae,chem,compiler,data,debugger,devel,geo,ide,lang,lib,math,mpi,numlib,perf,phys,system,toolchain,tools,vis'
--modules-tool='Lmod'
--mpi-tests
--optarch='GENERIC'
--output-format='txt'
--package-naming-scheme='EasyBuildPNS'
--package-release='1'
--package-tool-options=''
--package-tool='fpm'
--package-type='rpm'
--packagepath='/home/centos/.local/easybuild/packages'
--pr-target-account='easybuilders'
--pr-target-branch='develop'
--pr-target-repo='easybuild-easyconfigs'
--repository='FileRepository'
--repositorypath='/srv/sw/eb/ebfiles'
--robot-paths=':/home/centos/easyconfigs'
--robot='/srv/sw/eb/software/EasyBuild/3.3.1/lib/python2.7/site-packages/easybuild_easyconfigs-3.3.1-py2.7.egg/easybuild/easyconfigs:/home/centos/easyconfigs'
--set-gid-bit
--sourcepath='/srv/sw/eb/sources'
--strict='warn'
--subdir-modules='modules'
--subdir-software='software'
--suffix-modules-path='all'
--umask='002'
--use-ccache='False'
--use-f90cache='False'
````

#### System info
 * _core count:_ 8
 * _cpu model:_ Intel Xeon E3-12xx v2 (Ivy Bridge)
 * _cpu speed:_ 2399.998
 * _cpu vendor:_ Intel
 * _gcc version:_ Using built-in specs.; COLLECT_GCC=gcc; COLLECT_LTO_WRAPPER=/usr/libexec/gcc/x86_64-redhat-linux/4.8.5/lto-wrapper; Target: x86_64-redhat-linux; Configured with: ../configure --prefix=/usr --mandir=/usr/share/man --infodir=/usr/share/info --with-bugurl=http://bugzilla.redhat.com/bugzilla --enable-bootstrap --enable-shared --enable-threads=posix --enable-checking=release --with-system-zlib --enable-__cxa_atexit --disable-libunwind-exceptions --enable-gnu-unique-object --enable-linker-build-id --with-linker-hash-style=gnu --enable-languages=c,c++,objc,obj-c++,java,fortran,ada,go,lto --enable-plugin --enable-initfini-array --disable-libgcj --with-isl=/builddir/build/BUILD/gcc-4.8.5-20150702/obj-x86_64-redhat-linux/isl-install --with-cloog=/builddir/build/BUILD/gcc-4.8.5-20150702/obj-x86_64-redhat-linux/cloog-install --enable-gnu-indirect-function --with-tune=generic --with-arch_32=x86-64 --build=x86_64-redhat-linux; Thread model: posix; gcc version 4.8.5 20150623 (Red Hat 4.8.5-11) (GCC) ;
 * _glibc version:_ 2.17
 * _hostname:_ frontend001
 * _os name:_ centos linux
 * _os type:_ Linux
 * _os version:_ 7.3.1611
 * _platform name:_ x86_64-unknown-linux
 * _python version:_ 2.7.5 (default, Nov  6 2016, 00:28:07) ; [GCC 4.8.5 20150623 (Red Hat 4.8.5-11)]
 * _system gcc path:_ /usr/bin/gcc
 * _system python path:_ /usr/bin/python
 * _total memory:_ 48140

#### List of loaded modules
 * EasyBuild/3.3.1

#### Environment
```
BASH_ENV = /opt/lmod/lmod/init/bash
BASH_FUNC_ml() = () {  eval $($LMOD_DIR/ml_cmd "$@")
}
BASH_FUNC_module() = () {  eval $($LMOD_CMD bash "$@");
 [ $? = 0 ] && eval $(${LMOD_SETTARG_CMD:-:} -s sh)
}
CPATH = /usr/include/x86_64-linux-gnu
EASYBUILD_CONFIGFILES = /etc/easybuild.cfg
EBDEVELEASYBUILD = /srv/sw/eb/software/EasyBuild/3.3.1/easybuild/EasyBuild-3.3.1-easybuild-devel
EBROOTEASYBUILD = /srv/sw/eb/software/EasyBuild/3.3.1
EBVERSIONEASYBUILD = 3.3.1
FANCYLOGGER_IGNORE_MPI4PY = 1
HOME = /home/centos
LANG = en_GB.UTF-8
LC_CTYPE = en_GB.UTF-8
LESSOPEN = ||/usr/bin/lesspipe.sh %s
LMOD_CMD = /opt/lmod/lmod/libexec/lmod
LMOD_COLORIZE = yes
LMOD_DIR = /opt/lmod/lmod/libexec
LMOD_FULL_SETTARG_SUPPORT = no
LMOD_PKG = /opt/lmod/lmod
LMOD_PREPEND_BLOCK = normal
LMOD_SETTARG_CMD = :
LMOD_SYSTEM_DEFAULT_MODULES = EasyBuild
LMOD_VERSION = 7.0
LMOD_arch = x86_64
LMOD_sys = Linux
LOADEDMODULES = EasyBuild/3.3.1
LOGNAME = centos
LUA_CPATH = /usr/lib/lua/5.1/?.so;;
LUA_PATH = /usr/share/lua/5.1/?.so;;
MAIL = /var/mail/centos
MANPATH = /opt/lmod/lmod/share/man::
MODULEPATH = /srv/sw/eb/modules/all:/etc/modulefiles/Linux:/etc/modulefiles/Core:/opt/lmod/lmod/modulefiles/Core
MODULEPATH_ROOT = /etc/modulefiles
MODULESHOME = /opt/lmod/lmod
PATH = /srv/sw/eb/software/EasyBuild/3.3.1/bin:/usr/local/bin:/usr/bin
PDSH_RCMD_TYPE = ssh
PWD = /home/centos
PYTHONOPTIMIZE = 1
PYTHONPATH = /srv/sw/eb/software/EasyBuild/3.3.1/lib/python2.7/site-packages
SELINUX_LEVEL_REQUESTED =
SELINUX_ROLE_REQUESTED =
SELINUX_USE_CURRENT_RANGE =
SHELL = /bin/bash
SHLVL = 3
SSH_CLIENT = 192.168.24.10 46968 22
SSH_CONNECTION = 192.168.24.10 46968 192.168.24.26 22
USER = centos
XDG_RUNTIME_DIR = /run/user/1000
XDG_SESSION_ID = 4
_ = /usr/bin/python2
_LMFILES_ = /srv/sw/eb/modules/all/EasyBuild/3.3.1.lua
_ModuleTable001_ = X01vZHVsZVRhYmxlXz17WyJNVHZlcnNpb24iXT0zLFsiY19yZWJ1aWxkVGltZSJdPWZhbHNlLFsiY19zaG9ydFRpbWUiXT1mYWxzZSxkZXB0aFQ9e30sZmFtaWx5PXt9LG1UPXtFYXN5QnVpbGQ9e1siZm4iXT0iL3Nydi9zdy9lYi9tb2R1bGVzL2FsbC9FYXN5QnVpbGQvMy4zLjEubHVhIixbImZ1bGxOYW1lIl09IkVhc3lCdWlsZC8zLjMuMSIsWyJsb2FkT3JkZXIiXT0xLHByb3BUPXt9LFsic3RhdHVzIl09ImFjdGl2ZSIsWyJ1c2VyTmFtZSJdPSJFYXN5QnVpbGQiLH0sfSxtcGF0aEE9eyIvc3J2L3N3L2ViL21vZHVsZXMvYWxsIiwiL2V0Yy9tb2R1bGVmaWxlcy9MaW51eCIsIi9ldGMvbW9kdWxlZmlsZXMvQ29yZSIsIi9vcHQvbG1vZC9sbW9kL21vZHVsZWZpbGVzL0NvcmUi
_ModuleTable002_ = LH0sWyJzeXN0ZW1CYXNlTVBBVEgiXT0iL3Nydi9zdy9lYi9tb2R1bGVzL2FsbDovZXRjL21vZHVsZWZpbGVzL0xpbnV4Oi9ldGMvbW9kdWxlZmlsZXMvQ29yZTovb3B0L2xtb2QvbG1vZC9tb2R1bGVmaWxlcy9Db3JlIix9
_ModuleTable_Sz_ = 2
__Lmod_Init_Default_Modules = 1
```

**Comment by verdurin** [comment]
@jdemeul Yes, I think that's an earlier kernel. If you update then re-run the build, you'll encounter the same problem I saw.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
node2047.delcatty.os - Linux centos linux 7.4.1708, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.7.5
See https://gist.github.com/532bd90804b8ac48049946e61d48dec1 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 37 out of 37 (1 easyconfigs in this PR)
node2605.swalot.os - Linux centos linux 7.4.1708, Intel(R) Xeon(R) CPU E5-2660 v3 @ 2.60GHz, Python 2.7.5
See https://gist.github.com/d4b8a33ae69489c8d24b21fbdae529ba for a full test report.

**Comment by boegel** [comment]
Going in, thanks @jdemeul!

**Comment by jdemeul** [comment]
Great, thanks for following up @boegel!

**Pull request merged**
