### PR TITLE
add gnuplot dependency for OpenFOAM from v2.4.0 to v6

### PR DESCRIPTION
**Pull request by lexming**
(created using `eb --new-pr`)

Follow up on ~~#11770~~
Needed by https://github.com/easybuilders/easybuild-easyblocks/pull/2256

### CODE REVIEW

**Comment by lexming** [comment]
Test report by @lexming
Using easyblocks from PR(s) https://github.com/easybuilders/easybuild-easyblocks/pull/2256
**SUCCESS**
Build succeeded for 9 out of 9 (2 easyconfigs in total)
node376.hydra.os - Linux centos linux 7.9.2009, x86_64, Intel(R) Xeon(R) Gold 6148 CPU @ 2.40GHz, Python 2.7.5
See https://gist.github.com/678edd3c9aa0a817f8c65d1558bea634 for a full test report.

**Comment by lexming** [comment]
Test report by @lexming
Using easyblocks from PR(s) https://github.com/easybuilders/easybuild-easyblocks/pull/2256
**FAILED**
Build succeeded for 16 out of 19 (2 easyconfigs in total)
node379.hydra.os - Linux centos linux 7.9.2009, x86_64, Intel(R) Xeon(R) Gold 6148 CPU @ 2.40GHz, Python 2.7.5
See https://gist.github.com/4e7bfd6e45ea88a597441925e984c39e for a full test report.

**Comment by lexming** [comment]
Test report by @lexming
Using easyblocks from PR(s) https://github.com/easybuilders/easybuild-easyblocks/pull/2256
**SUCCESS**
Build succeeded for 3 out of 3 (2 easyconfigs in total)
node376.hydra.os - Linux centos linux 7.9.2009, x86_64, Intel(R) Xeon(R) Gold 6148 CPU @ 2.40GHz, Python 2.7.5
See https://gist.github.com/0e8bae7c697e748ca3b067c1503046dd for a full test report.

**Comment by boegel** [comment]
@boegelbot please test @ generoso
EB_ARGS=" --include-easyblocks-from-pr 2256 OpenFOAM-6-foss-2019b.eb "
CORE_CNT=16

**Comment by lexming** [comment]
Test report by @lexming
Using easyblocks from PR(s) https://github.com/easybuilders/easybuild-easyblocks/pull/2256
**FAILED**
Build succeeded for 6 out of 12 (2 easyconfigs in total)
node379.hydra.os - Linux centos linux 7.9.2009, x86_64, Intel(R) Xeon(R) Gold 6148 CPU @ 2.40GHz, Python 2.7.5
See https://gist.github.com/ee297e721ee970f019ccd0112b047225 for a full test report.

**Comment by lexming** [comment]
Test report by @lexming
Using easyblocks from PR(s) https://github.com/easybuilders/easybuild-easyblocks/pull/2256
**FAILED**
Build succeeded for 6 out of 12 (2 easyconfigs in total)
node379.hydra.os - Linux centos linux 7.9.2009, x86_64, Intel(R) Xeon(R) Gold 6148 CPU @ 2.40GHz, Python 2.7.5
See https://gist.github.com/31480258e5e856a2aafb5fd42ebc93ac for a full test report.

**Comment by lexming** [comment]
Test report by @lexming
Using easyblocks from PR(s) https://github.com/easybuilders/easybuild-easyblocks/pull/2256
**FAILED**
Build succeeded for 0 out of 2 (2 easyconfigs in total)
node378.hydra.os - Linux centos linux 7.9.2009, x86_64, Intel(R) Xeon(R) Gold 6148 CPU @ 2.40GHz, Python 2.7.5
See https://gist.github.com/5602a8adf42a0b6da5a8ff63b0b9657f for a full test report.

**Comment by boegel** [comment]
@lexming What's up with the failing test reports?

**Comment by lexming** [comment]
@boegel all easyconfigs in `foss/2016b` failed because we have a different version of `zlib` in our toolchain. Re-running...

**Comment by lexming** [comment]
Test report by @lexming
Using easyblocks from PR(s) https://github.com/easybuilders/easybuild-easyblocks/pull/2256
**FAILED**
Build succeeded for 1 out of 6 (2 easyconfigs in total)
node381.hydra.os - Linux centos linux 7.9.2009, x86_64, Intel(R) Xeon(R) Gold 6148 CPU @ 2.40GHz, Python 2.7.5
See https://gist.github.com/1062ad7fe921fb3061d09b3d8f53c96e for a full test report.

**Comment by lexming** [comment]
Test report by @lexming
Using easyblocks from PR(s) https://github.com/easybuilders/easybuild-easyblocks/pull/2256
**FAILED**
Build succeeded for 0 out of 5 (2 easyconfigs in total)
node379.hydra.os - Linux centos linux 7.9.2009, x86_64, Intel(R) Xeon(R) Gold 6148 CPU @ 2.40GHz, Python 2.7.5
See https://gist.github.com/45215698a7b0191063e9f1f8a6c0a98d for a full test report.

**Comment by lexming** [comment]
Test report by @lexming
Using easyblocks from PR(s) https://github.com/easybuilders/easybuild-easyblocks/pull/2256
**FAILED**
Build succeeded for 1 out of 5 (2 easyconfigs in total)
node381.hydra.os - Linux centos linux 7.9.2009, x86_64, Intel(R) Xeon(R) Gold 6148 CPU @ 2.40GHz, Python 2.7.5
See https://gist.github.com/5ca24f6d7322d3ad340ebce2f8750567 for a full test report.

**Comment by lexming** [comment]
Test report by @lexming
Using easyblocks from PR(s) https://github.com/easybuilders/easybuild-easyblocks/pull/2256
**FAILED**
Build succeeded for 1 out of 5 (2 easyconfigs in total)
node381.hydra.os - Linux centos linux 7.9.2009, x86_64, Intel(R) Xeon(R) Gold 6148 CPU @ 2.40GHz, Python 2.7.5
See https://gist.github.com/d3ee3d1b6a5bb4e169dc8f051445d392 for a full test report.

**Comment by lexming** [comment]
Test report by @lexming
Using easyblocks from PR(s) https://github.com/easybuilders/easybuild-easyblocks/pull/2256
**FAILED**
Build succeeded for 1 out of 2 (2 easyconfigs in total)
node381.hydra.os - Linux centos linux 7.9.2009, x86_64, Intel(R) Xeon(R) Gold 6148 CPU @ 2.40GHz, Python 2.7.5
See https://gist.github.com/d518d383284f1646aac6105981112d3a for a full test report.

**Comment by lexming** [comment]
Test report by @lexming
Using easyblocks from PR(s) https://github.com/easybuilders/easybuild-easyblocks/pull/2256
**FAILED**
Build succeeded for 1 out of 2 (2 easyconfigs in total)
node381.hydra.os - Linux centos linux 7.9.2009, x86_64, Intel(R) Xeon(R) Gold 6148 CPU @ 2.40GHz, Python 2.7.5
See https://gist.github.com/d677beabbf9ce92c000aeb3eb447fa62 for a full test report.

**Comment by lexming** [comment]
Test report by @lexming
Using easyblocks from PR(s) https://github.com/easybuilders/easybuild-easyblocks/pull/2256
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in total)
node355.hydra.os - Linux centos linux 7.9.2009, x86_64, Intel(R) Xeon(R) Gold 6148 CPU @ 2.40GHz, Python 2.7.5
See https://gist.github.com/f4420aa9f223523c84a5c060049f88a2 for a full test report.

**Comment by lexming** [comment]
Test report by @lexming
Using easyblocks from PR(s) https://github.com/easybuilders/easybuild-easyblocks/pull/2256
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in total)
node356.hydra.os - Linux centos linux 7.9.2009, x86_64, Intel(R) Xeon(R) Gold 6148 CPU @ 2.40GHz, Python 2.7.5
See https://gist.github.com/94d846491607de4d2a0b918091c19570 for a full test report.

**Comment by lexming** [comment]
Test report by @lexming
Using easyblocks from PR(s) https://github.com/easybuilders/easybuild-easyblocks/pull/2256
**FAILED**
Build succeeded for 1 out of 3 (3 easyconfigs in total)
node319.hydra.os - Linux centos linux 7.9.2009, x86_64, Intel(R) Xeon(R) Gold 6148 CPU @ 2.40GHz, Python 2.7.5
See https://gist.github.com/b8620fb85ae6d13feadd0468981b3e2a for a full test report.

**Comment by lexming** [comment]
Test report by @lexming
Using easyblocks from PR(s) https://github.com/easybuilders/easybuild-easyblocks/pull/2256
**FAILED**
Build succeeded for 3 out of 5 (3 easyconfigs in total)
node356.hydra.os - Linux centos linux 7.9.2009, x86_64, Intel(R) Xeon(R) Gold 6148 CPU @ 2.40GHz, Python 2.7.5
See https://gist.github.com/161b3fdea1fc786c2bf41de50d2e9c01 for a full test report.

**Comment by lexming** [comment]
Test report by @lexming
Using easyblocks from PR(s) https://github.com/easybuilders/easybuild-easyblocks/pull/2256
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in total)
node356.hydra.os - Linux centos linux 7.9.2009, x86_64, Intel(R) Xeon(R) Gold 6148 CPU @ 2.40GHz, Python 2.7.5
See https://gist.github.com/09155f42b7906d840a7c85dfa3138ab4 for a full test report.

**Comment by lexming** [comment]
Test report by @lexming
Using easyblocks from PR(s) https://github.com/easybuilders/easybuild-easyblocks/pull/2256
**FAILED**
Build succeeded for 1 out of 3 (3 easyconfigs in total)
node381.hydra.os - Linux centos linux 7.9.2009, x86_64, Intel(R) Xeon(R) Gold 6148 CPU @ 2.40GHz, Python 2.7.5
See https://gist.github.com/23b564b779eef81c1e18f98ed8209f89 for a full test report.

**Comment by lexming** [comment]
Test report by @lexming
Using easyblocks from PR(s) https://github.com/easybuilders/easybuild-easyblocks/pull/2256
**FAILED**
Build succeeded for 2 out of 3 (3 easyconfigs in total)
node381.hydra.os - Linux centos linux 7.9.2009, x86_64, Intel(R) Xeon(R) Gold 6148 CPU @ 2.40GHz, Python 2.7.5
See https://gist.github.com/d1388163576865e06e56b56ada745a5a for a full test report.

**Comment by lexming** [comment]
OpenFOAM v5 are failing due to a version conflict between Qt4 from ParaView and Qt5 from gnuplot

```
CMake Error at /theia/home/apps/CO7/skylake/software/CMake/3.10.1-GCCcore-6.4.0/share/cmake-3.10/Modules/FindQt4.cmake:1320 (message):
  Found unsuitable Qt version "5.8.0" from
  /apps/brussel/CO7/skylake/software/Qt5/5.8.0-intel-2017b/bin/qmake, this
  code requires Qt 4.x
Call Stack (most recent call first):
  /user/brussel/101/vsc10122/.local/easybuild-skylake/software/ParaView/5.4.1-intel-2017b-mpi/lib64/cmake/paraview-5.4/ParaViewQt.cmake:87 (find_package)
  /user/brussel/101/vsc10122/.local/easybuild-skylake/software/ParaView/5.4.1-intel-2017b-mpi/lib/cmake/paraview-5.4/Modules/pqApplicationComponents.cmake:11 (pv_find_package_qt)
  /user/brussel/101/vsc10122/.local/easybuild-skylake/software/ParaView/5.4.1-intel-2017b-mpi/lib/cmake/paraview-5.4/vtkModuleAPI.cmake:45 (include)
  /user/brussel/101/vsc10122/.local/easybuild-skylake/software/ParaView/5.4.1-intel-2017b-mpi/lib/cmake/paraview-5.4/vtkModuleAPI.cmake:15 (vtk_module_load)
  /user/brussel/101/vsc10122/.local/easybuild-skylake/software/ParaView/5.4.1-intel-2017b-mpi/lib/cmake/paraview-5.4/vtkModuleAPI.cmake:132 (_vtk_module_config_recurse)
  /user/brussel/101/vsc10122/.local/easybuild-skylake/software/ParaView/5.4.1-intel-2017b-mpi/lib64/cmake/paraview-5.4/VTKConfig.cmake:135 (vtk_module_config)
  /user/brussel/101/vsc10122/.local/easybuild-skylake/software/ParaView/5.4.1-intel-2017b-mpi/lib64/cmake/paraview-5.4/ParaViewConfig.cmake:51 (include)
  CMakeLists.txt:4 (FIND_PACKAGE)


-- Configuring incomplete, errors occurred!
```

**Comment by lexming** [comment]
https://github.com/easybuilders/easybuild-easyconfigs/pull/11801/commits/d75a3c70262f88213726e12edb633fedc4da8570 fixes the aforementioned issue due to mixing of dependencies with Qt4 and Qt5. The solution is to guarantee that dependencies loading Qt4 are **last** in the list, so that Qt4 has precedende over Qt5. Otherwise the build will fail as described. This problem only happens in the few easyconfigs where ParaView and CGAL depend on Qt4 while gnuplot already uses Qt5.

**Comment by lexming** [comment]
Test report by @lexming
Using easyblocks from PR(s) https://github.com/easybuilders/easybuild-easyblocks/pull/2256
**FAILED**
Build succeeded for 2 out of 3 (3 easyconfigs in total)
node372.hydra.os - Linux centos linux 7.9.2009, x86_64, Intel(R) Xeon(R) Gold 6148 CPU @ 2.40GHz, Python 2.7.5
See https://gist.github.com/a2cd60cafc49241d92f6ddec21103801 for a full test report.

**Comment by lexming** [comment]
Test report by @lexming
Using easyblocks from PR(s) https://github.com/easybuilders/easybuild-easyblocks/pull/2256
**FAILED**
Build succeeded for 2 out of 3 (3 easyconfigs in total)
node381.hydra.os - Linux centos linux 7.9.2009, x86_64, Intel(R) Xeon(R) Gold 6148 CPU @ 2.40GHz, Python 2.7.5
See https://gist.github.com/d71a7d0d7e6826c89504f5be205ed452 for a full test report.

**Comment by lexming** [comment]
Test report by @lexming
Using easyblocks from PR(s) https://github.com/easybuilders/easybuild-easyblocks/pull/2256
**FAILED**
Build succeeded for 2 out of 3 (3 easyconfigs in total)
node360.hydra.os - Linux centos linux 7.9.2009, x86_64, Intel(R) Xeon(R) Gold 6148 CPU @ 2.40GHz, Python 2.7.5
See https://gist.github.com/acd4fd661f25a7ae45c4f51e1b08c2e4 for a full test report.

**Comment by lexming** [comment]
Test report by @lexming
Using easyblocks from PR(s) https://github.com/easybuilders/easybuild-easyblocks/pull/2256
**SUCCESS**
Build succeeded for 3 out of 3 (3 easyconfigs in total)
node360.hydra.os - Linux centos linux 7.9.2009, x86_64, Intel(R) Xeon(R) Gold 6148 CPU @ 2.40GHz, Python 2.7.5
See https://gist.github.com/e7559bb54a60b547b3ca105bb4ae062a for a full test report.

**Review by boegel — APPROVED** [review]
lgtm

**Comment by boegel** [comment]
Going in, thanks @lexming!

**Pull request merged**
