### PR TITLE
{data}[CrayGNU]HDF5{WIP}

### PR DESCRIPTION
**Pull request by pforai**
Needs https://github.com/boegel/easybuild-framework/pull/9

### CODE REVIEW

**Comment by pforai** [comment]
Test report by @pforai
**SUCCESS**
Build succeeded for 0 out of 0 (3 easyconfigs in this PR)
Linux SLES 11_SP2, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.6.9
See https://gist.github.com/3177caf645506997fabf for a full test report.

**Comment by pforai** [comment]
Test report by @pforai
**SUCCESS**
Build succeeded for 3 out of 3 (3 easyconfigs in this PR)
Linux SLES 11_SP2, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.6.9
See https://gist.github.com/cc784281b5821422fd03 for a full test report.

**Comment by pforai** [comment]
Test report by @pforai
**SUCCESS**
Build succeeded for 3 out of 3 (3 easyconfigs in this PR)
Linux SLES 11_SP2, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.6.9
See https://gist.github.com/c14127222603b1b06bc0 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**FAILED**
Build succeeded for 2 out of 3 (3 easyconfigs in this PR)
Linux SLES 11_SP2, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.6.9
See https://gist.github.com/3ad5b1c65f71a0fdf1c3 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**FAILED**
Build succeeded for 2 out of 3 (3 easyconfigs in this PR)
Linux SLES 11_SP2, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.6.9
See https://gist.github.com/2ae3537658685db0b11a for a full test report.

**Comment by boegel** [comment]
building HDF5 on top of a 'clean' environment (i.e. after `module purge`) doesn't work, probably because we're not loading the `cray-mpich` module?

**Comment by migueldiascosta** [comment]
@pforai, this PR is being closed for the following reason(s): no activity for > 6 months, obsoleted by more recent PRs.
Please don't hesitate to reopen this PR or add a comment if you feel this contribution is still relevant.
For more information on our policy w.r.t. closing PRs, see https://easybuild.readthedocs.io/en/latest/Contributing.html#why-a-pull-request-may-be-closed-by-a-maintainer

**Pull request closed without merging**
