### PR TITLE
{bio}[gompi/2020a,iimpi/2020a] TopHat v2.1.2

### PR DESCRIPTION
**Pull request by boegel**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by boegel** [comment]
@boegelbot please test @ generoso

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in total)
node2620.swalot.os - Linux centos linux 7.9.2009, x86_64, Intel(R) Xeon(R) CPU E5-2660 v3 @ 2.60GHz (haswell), Python 3.6.8
See https://gist.github.com/07cb5b2fd142fa2ffa8934bcc8d2ead8 for a full test report.

**Review by Micket — CHANGES_REQUESTED** [review]
I suspect this doens't use MPI, just needs Boost, which we now have at compiler level.

**Comment by boegel** [comment]
> I suspect this doens't use MPI, just needs Boost, which we now have at compiler level.

I made that change, but for the `2020a` generation we didn't have `Boost` as compiler-only level yet, see `Boost-1.72.0-gompi-2020a.eb` and `Boost-1.72.0-iimpi-2020a.eb`.

So I'll change it back...

**Comment by boegel** [comment]
@boegelbot please test @ generoso

**Comment by boegel** [comment]
@boegelbot please test @ jsc-zen2

**Review by branfosj — APPROVED** [review]

**Comment by branfosj** [comment]
Test report by @branfosj
**SUCCESS**
Build succeeded for 3 out of 3 (2 easyconfigs in total)
bear-pg0211u03a.bear.cluster - Linux RHEL 8.6, x86_64, Intel(R) Xeon(R) Gold 6248 CPU @ 2.50GHz (cascadelake), Python 3.6.8
See https://gist.github.com/branfosj/735761f6f19824927fcfaae0403eb944 for a full test report.

**Comment by branfosj** [comment]
Going in, thanks @boegel!

**Pull request merged**
