### PR TITLE
{math}[intel/2021a] numexpr v2.8.1 w/ Python 3.9.5

### PR DESCRIPTION
**Pull request by SebastianAchilles**
(created using `eb --new-pr`)

- [ ] Depends on https://github.com/easybuilders/easybuild-easyblocks/pull/2678

### CODE REVIEW

**Comment by SebastianAchilles** [comment]
Test report by @sebastianachilles
Using easyblocks from PR(s) https://github.com/easybuilders/easybuild-easyblocks/pull/2678
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
jscskxl1.int.jsc-skx.easybuild-test.cluster - Linux Rocky Linux 8.5, x86_64, Intel Xeon Processor (Skylake, IBRS) (skylake_avx512), Python 3.6.8
See https://gist.github.com/da5b515c477823ecfe2d371980736a4c for a full test report.

**Comment by SebastianAchilles** [comment]
Test report by @SebastianAchilles
Using easyblocks from PR(s) https://github.com/easybuilders/easybuild-easyblocks/pull/2678
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
login1 - Linux Rocky Linux 8.5, x86_64, Intel(R) Xeon(R) CPU E5-2690 v3 @ 2.60GHz (haswell), Python 3.6.8
See https://gist.github.com/d51db5bf74dbd6f39ae4570f8dbb71cd for a full test report.

**Review by branfosj — APPROVED** [review]
lgtm

**Comment by branfosj** [comment]
@boegelbot please test @ generoso

**Comment by branfosj** [comment]
Test report by @branfosj
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
bear-pg0211u03a.bear.cluster - Linux RHEL 8.5, x86_64, Intel(R) Xeon(R) Gold 6248 CPU @ 2.50GHz (cascadelake), Python 3.6.8
See https://gist.github.com/46f8db8d7b7675073097ddcd15f1a795 for a full test report.

**Comment by branfosj** [comment]
Going in, thanks @SebastianAchilles!

**Pull request merged**
