### PR TITLE
Qiime with newer anaconda

### PR DESCRIPTION
**Pull request by pescobar**
When trying to install the QIIME easyconfig I got this error:

```
Traceback (most recent call last):
  File "/test-installs/apps/QIIME/1.9.1/bin/print_qiime_config.py", line 4, in <module>
    __import__('pkg_resources').run_script('qiime==1.9.1', 'print_qiime_config.py')
  File "build/bdist.linux-x86_64/egg/pkg_resources/__init__.py", line 2927, in <module>
  File "build/bdist.linux-x86_64/egg/pkg_resources/__init__.py", line 2913, in _call_aside
  File "build/bdist.linux-x86_64/egg/pkg_resources/__init__.py", line 2940, in _initialize_master_working_set
  File "build/bdist.linux-x86_64/egg/pkg_resources/__init__.py", line 635, in _build_master
  File "build/bdist.linux-x86_64/egg/pkg_resources/__init__.py", line 943, in require
  File "build/bdist.linux-x86_64/egg/pkg_resources/__init__.py", line 829, in resolve
pkg_resources.DistributionNotFound: The 'backports.shutil-get-terminal-size; python_version == "2.7"' distribution was not found and is required by IPython
```
I could workaround the issue by installing QIIME with the latest anaconda version . This PR provides the latest Anaconda esyconfig and the updated QIIME easyconfig to use it

### CODE REVIEW

**Comment by boegel** [comment]
@pescobar Hmm, on my end it fails too, but for a different reason:

```
pkg_resources.DistributionNotFound: The 'pytz>=2011k' distribution was not found and is required by pandas
```

Any idea why this is happening @jerowe? Isn't everything supposed to be fixed so the installation is reproducible? Apparently that's not the case here...

**Comment by jerowe** [comment]
`channels = [ 'r' , 'default' , 'conda-forge',  'bioconda']` might fix it. Let me do some testing here.

**Comment by jerowe** [comment]
I hate to be the 'it works for me' person, but it does.

```
== Results of the build can be found in the log file(s) /home/jillian/.eb/software/Anaconda2/5.0.1/easybuild/easybuild-Anaconda2-5.0.1-20171106.121428.log
== processing EasyBuild easyconfig /home/jillian/Dropbox/projects/easybuild/jerowe-easybuild-myconfigs-3.0.2/QIIME-1.9.1.eb
== building and installing QIIME/1.9.1...
== fetching files...
== creating build dir, resetting environment...
== unpacking...
== patching...
== preparing...
== configuring...
== building...
== testing...
== installing...








== taking care of extensions...
== postprocessing...
== sanity checking...
== cleaning up...
== creating module...
== permissions...
== packaging...
== COMPLETED: Installation ended successfully
== Results of the build can be found in the log file(s) /home/jillian/.eb/software/QIIME/1.9.1/easybuild/easybuild-QIIME-1.9.1-20171106.123948.log
== Build succeeded for 2 out of 2
== Temporary log file(s) /tmp/eb-RBzt4s/easybuild-FZJjn4.log* have been removed.
== Temporary directory /tmp/eb-RBzt4s has been removed.
```

**Comment by migueldiascosta** [comment]
@pescobar, this PR is being closed for the following reason(s): no activity for > 1 year.
Please don't hesitate to reopen this PR or add a comment if you feel this contribution is still relevant.
For more information on our policy w.r.t. closing PRs, see https://easybuild.readthedocs.io/en/latest/Contributing.html#why-a-pull-request-may-be-closed-by-a-maintainer

**Pull request closed without merging**
