### PR TITLE
{bio}[system/system] T-Coffee v13.45.61.3c310a9

### PR DESCRIPTION
**Pull request by smoors**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by smoors** [comment]
Test report by @smoors
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
node308.hydra.os - Linux CentOS Linux 7.9.2009, x86_64, Intel(R) Xeon(R) Gold 6148 CPU @ 2.40GHz (skylake_avx512), Python 3.6.8
See https://gist.github.com/smoors/ccc538f85587c6a935f659cbc06dfa76 for a full test report.

**Comment by verdurin** [comment]
Test report by @verdurin
**FAILED**
Build succeeded for 0 out of 1 (1 easyconfigs in total)
easybuild-c7.novalocal - Linux CentOS Linux 7.9.2009, x86_64, Intel Xeon Processor (Skylake, IBRS), Python 3.6.8
See https://gist.github.com/verdurin/5fa3bfae96b0d3b0640b20636c1e5d29 for a full test report.

**Comment by verdurin** [comment]
@smoors hmm, checksum error here:
```
== 2023-05-19 12:23:24,787 filetools.py:1313 DEBUG Computed sha256 checksum for /eb/maint/sources/t/T-Coffee/T-COFFEE_installer_Version_13.45.61.3c310a9_linux_x64.tar.gz: 194b89107ac31467f8a0221bd621c652d6a485a1886a65ef5d567699876429d4 (correct checksum: 8bc60336f5c203d4a20cc8c9e0ba10c5f4275a11ccfd15a0dd26a03510314513)
== 2023-05-19 12:23:24,790 build_log.py:171 ERROR EasyBuild crashed with an error (at easybuild/base/exceptions.py:126 in __init__): Checksum verification for /eb/maint/sources/t/T-Coffee/T-COFFEE_installer_Version_13.45.61.3c310a9_linux_x64.tar.gz using 8bc60336f5c203d4a20cc8c9e0ba10c5f4275a11ccfd15a0dd26a03510314513 failed. (at easybuild/framework/easyblock.py:2420 in checksum_step)
```

**Comment by smoors** [comment]
> @smoors hmm, checksum error here:
> 
> ```
> == 2023-05-19 12:23:24,787 filetools.py:1313 DEBUG Computed sha256 checksum for /eb/maint/sources/t/T-Coffee/T-COFFEE_installer_Version_13.45.61.3c310a9_linux_x64.tar.gz: 194b89107ac31467f8a0221bd621c652d6a485a1886a65ef5d567699876429d4 (correct checksum: 8bc60336f5c203d4a20cc8c9e0ba10c5f4275a11ccfd15a0dd26a03510314513)
> == 2023-05-19 12:23:24,790 build_log.py:171 ERROR EasyBuild crashed with an error (at easybuild/base/exceptions.py:126 in __init__): Checksum verification for /eb/maint/sources/t/T-Coffee/T-COFFEE_installer_Version_13.45.61.3c310a9_linux_x64.tar.gz using 8bc60336f5c203d4a20cc8c9e0ba10c5f4275a11ccfd15a0dd26a03510314513 failed. (at easybuild/framework/easyblock.py:2420 in checksum_step)
> ```

ugh. a diff between the old and new tarballs spits 20,000 lines.
issue opened https://github.com/cbcrg/tcoffee/issues/57

**Comment by SebastianAchilles** [comment]
Test report by @sebastianachilles
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
skl-centos-79 - Linux CentOS Linux 7.9.2009, x86_64, Intel(R) Core(TM) i7-8700 CPU @ 3.20GHz (skylake), Python 3.6.8
See https://gist.github.com/SebastianAchilles/2cc1b6bcaade8df70eb2467c69d43610 for a full test report.

**Comment by SebastianAchilles** [comment]
@boegelbot please test @ generoso

**Comment by smoors** [comment]
```
--ERROR: MAX_N_PID exceded -- Recompile changing the value of MAX_N_PID (current: 260000 Requested: 552029) OR setenv MAX_N_PID_4_TCOFFEE=552029
```

**Comment by lexming** [comment]
@boegelbot: please test @ generoso

**Comment by lexming** [comment]
@boegelbot: please test @ generoso

**Comment by lexming** [comment]
@boegelbot please test @ jsc-zen2

**Review by lexming — APPROVED** [review]
Fixed the issue with max PID number.

LGTM

**Comment by lexming** [comment]
Going in, thanks @smoors !

**Pull request merged**
