### PR TITLE
Philosopher 3.2.9

### PR DESCRIPTION
**Pull request by fizwit**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by migueldiascosta** [comment]
@fizwit I have no experience with Go but could the new (since eb 4.2.1) `GoPackage` easyblock (https://github.com/easybuilders/easybuild-easyblocks/pull/2042) be used here, instead of the binary tarball?

cc @Darkless012

**Comment by Darkless012** [comment]
Yup, GoPackage is way to go. Unfortunately I wasn't able to build the package. I'm including easyconfig used and error message.
```
easyblock = 'GoPackage'

name = 'philosopher'
version = '3.2.9'

homepage = 'https://github.com/Nesvilab/philosopher/wiki'
description = """Philosopher provides easy access to third-party tools and custom algorithms
 allowing users to develop proteomics analysis, from Peptide Spectrum Matching to annotated
 protein reports. Philosopher is also tuned for Open Search analysis, providing a modified
 version of the prophets for peptide validation and protein inference. To this date, Philosopher
 is the only proteomics toolkit that allows you to process and analyze close and
 open search results."""

toolchain = SYSTEM

# https://github.com/Nesvilab/philosopher
github_account = 'Nesvilab'
source_urls = [GITHUB_SOURCE]
sources = ['v%(version)s.tar.gz']
checksums = ['767cba171ed2792952603e20570a1fec367b3311d61e025b8a1c00e79ef6f9a0']

builddependencies = [
    ('Go', '1.14.1'),
]
dependencies = [('Java', '1.8')]

moduleclass = 'bio'
```

**ERROR:**
```
== FAILED: Installation ended unsuccessfully (build directory: /tmp/vsc43143/easybuild/build/philosopher/3.2.9/system-system): build failed (first 300 chars): cmd " go install " exited with exit code 2 and output:
# philosopher/lib/ext/cdhit/unix
lib/ext/cdhit/unix/unix.go:15:13: undefined: Asset
# philosopher/lib/ext/peptideprophet/unix
lib/ext/peptideprophet/unix/unix.go:14:13: undefined: Asset
...
```

**Comment by Darkless012** [comment]
Tarball can be easier option, but it is compiled binary with all its pros and cons.

**Comment by Darkless012** [comment]
Apparently it has its own build procedure:
https://github.com/Nesvilab/philosopher/blob/8f389e2fd53dafde5fdcb16d7c5703e0b8f7326a/.github/workflows/go.yml

...with copying stuff here and there :-1: ...

**Comment by Micket** [comment]
Just a comment, either approach we go for, should have a `-Java-%(javaver)s` versionsuffix. If we start having gopackages outside toolchains as well, then the same applies there, we should probably need a `-Go-XXX` suffix as well.

**Comment by Darkless012** [comment]
Gopackage is outside of toolchain (`SYSTEM`), but Go is needed only on build time. Then it should be just executable. 
Having -Go-XXX suffix, would sign, two different go versions can't be combined, but this is not true, since only binaries are left?

**Comment by fizwit** [comment]
Instructions for building from philosopher from source were just published. I am resubmitting the EasyConfig.

**Comment by fizwit** [comment]
Philosopher does not need a --Go-XX suffix.  Go is only a build dependency that creates a binary.

**Comment by Micket** [comment]
Does Go not have any standard library that it links to?

**Comment by fizwit** [comment]
Philosopher 4 has changed significantly. I will work on a newer easyconfig for v4.

**Pull request closed without merging**
