### PR TITLE
{tools}[intel/2018a] pytest v3.8.0 w/ Python 3.6.4

### PR DESCRIPTION
**Pull request by SimonPinches**

### CODE REVIEW

**Comment by boegel** [comment]
@SimonPinches Ignore the failing tests, that obviously has nothing to do with your PR.

The tests got a bit stricter after collapsing the `4.x` branch into `develop`, in preparation for the upcoming EasyBuild v4.0.0 release, in particular w.r.t. the `'dummy` toolchain (should now be `system`), and the naming of local variables in easyconfig files (see https://easybuild.readthedocs.io/en/4.x/Easyconfig-files-local-variables.html).

A couple of easyconfigs in `develop` were not fixed yet to pass these tests, those were fixed in #8822, so I've re-triggered the tests for this PR.

**Comment by migueldiascosta** [comment]
Test report by @migueldiascosta
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
sms - Linux centos linux 7.6.1810, AMD EPYC 7601 32-Core Processor, Python 2.7.5
See https://gist.github.com/e33bf7befa873c07f429ac9c27298097 for a full test report.

**Review by migueldiascosta — APPROVED** [review]
lgtm

**Comment by migueldiascosta** [comment]
Going in, thanks @SimonPinches!

**Pull request merged**
