### PR TITLE
{math}[gompi/2019a,iimpi/2019a] SCOTCH v6.0.6

### PR DESCRIPTION
**Pull request by Micket**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by akesandgren** [comment]
If you put SCOTCH at gompi, you should put it in iimpi and not intel to keep them at the same level.

**Comment by Micket** [comment]
Yup, I missed changing the actual compiler in the config

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in this PR)
node2039.delcatty.os - Linux centos linux 7.6.1810, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.7.5
See https://gist.github.com/57724d9e09b23d0c7fcdc7ad549894f9 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in this PR)
node3110.skitty.os - Linux centos linux 7.6.1810, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz, Python 2.7.5
See https://gist.github.com/01c10512eabf12ed719e1a2ddc64e174 for a full test report.

**Comment by boegel** [comment]
Going in, thanks @Micket!

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in this PR)
node2411.golett.os - Linux centos linux 7.6.1810, Intel(R) Xeon(R) CPU E5-2680 v3 @ 2.50GHz, Python 2.7.5
See https://gist.github.com/d62ff07e89a4f16ec51fe457d791ba8a for a full test report.

**Pull request merged**
