### PR TITLE
Chombo and BISICLES easyconfigs

### PR DESCRIPTION
**Pull request by hajgato**
Needs https://github.com/hpcugent/easybuild-easyblocks/pull/464

### CODE REVIEW

**Comment by boegel** [comment]
Jenkins: test this please

**Comment by hajgato** [comment]
@boegel They needs the easyblocks (#464)

**Comment by boegel** [comment]
let's get this merged next week?

**Comment by hajgato** [comment]
@boegel: fine for me.

**Comment by migueldiascosta** [comment]
@hajgato, this PR is being closed for the following reason(s): no activity for > 6 months.
Please don't hesitate to reopen this PR or add a comment if you feel this contribution is still relevant.
For more information on our policy w.r.t. closing PRs, see https://easybuild.readthedocs.io/en/latest/Contributing.html#why-a-pull-request-may-be-closed-by-a-maintainer

**Pull request closed without merging**
