### PR TITLE
Fix potential memory leak in OpenBLAS 0.3.12

### PR DESCRIPTION
**Pull request by Flamefire**
(created using `eb --new-pr`)

### CODE REVIEW

**Review by Micket — APPROVED** [review]
lgtm
So, did we just miss applying this to 0.3.12 from the start (oversight when the PRs got merged in parallel maybe?

**Comment by Micket** [comment]
@boegelbot please test @ generoso

**Comment by Flamefire** [comment]
Test report by @Flamefire
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
taurusa4 - Linux centos linux 7.7.1908, x86_64, Intel(R) Xeon(R) CPU E5-2603 v4 @ 1.70GHz (broadwell), Python 2.7.5
See https://gist.github.com/62be5245c28ec6ab6c7438a11433ca92 for a full test report.

**Comment by Flamefire** [comment]
Test report by @Flamefire
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
taurusml22 - Linux RHEL 7.6, POWER, 8335-GTX (power9le), Python 2.7.5
See https://gist.github.com/5a6a42a293bb187b7076ef6ef59b7694 for a full test report.

**Comment by Micket** [comment]
Going in, thanks @Flamefire!

**Pull request merged**
