### PR TITLE
{math}[gfbf/2022a] Singular v4.3.2p10

### PR DESCRIPTION
**Pull request by migueldiascosta**
(created using `eb --new-pr`)

requires:
- [x] #19192
- [x] #19193

### CODE REVIEW

**Comment by boegel** [comment]
@boegelbot please test @ generoso

**Comment by boegel** [comment]
@boegelbot please test @ jsc-zen2

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
node3149.skitty.os - Linux RHEL 8.8, x86_64, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz (skylake_avx512), Python 3.6.8
See https://gist.github.com/boegel/255dcd9d783ad3de366c9588674d7f32 for a full test report.

**Comment by smoors** [comment]
@boegelbot please test @ jsc-zen2 EB_ARGS="--module-only"

**Comment by smoors** [comment]
@boegelbot: please test @ generoso EB_ARGS="--module-only"

**Review by smoors — APPROVED** [review]
lgtm

**Comment by smoors** [comment]
Going in, thanks @migueldiascosta!

**Pull request merged**
