### PR TITLE
{tools}[GCC/6.4.0-2.28,iccifort/2017.4.196-GCC-6.4.0-2.28] p7zip v16.02

### PR DESCRIPTION
**Pull request by murfreesboro**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by murfreesboro** [comment]
Test report by @murfreesboro
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in this PR)
dev806.vampire - Linux centos linux 7.4.1708, Intel(R) Xeon(R) CPU           E5620  @ 2.40GHz, Python 2.7.5
See https://gist.github.com/3c5f1c08ccec333fd8af30c64408772c for a full test report.

**Comment by vanzod** [comment]
@murfreesboro Does it need specific libraries in `foss` and `intel` toolchains? Otherwise, I would recommend building it with a lower toolchain like `GCC` and `iccifort`.

**Comment by murfreesboro** [comment]
downgraded the toolchain.

**Comment by vanzod** [comment]
Test report by @vanzod
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in this PR)
cermis - Linux debian 9.9, Intel(R) Xeon(R) CPU           X5670  @ 2.93GHz, Python 2.7.13
See https://gist.github.com/9c363d3552931063ab19cba3f4ba5b8f for a full test report.

**Comment by vanzod** [comment]
Going in, thanks @murfreesboro!

**Pull request merged**
