### PR TITLE
{bio}[foss/2023a] Seurat v5.1.0 w/ R 4.3.2

### PR DESCRIPTION
**Pull request by verdurin**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by verdurin** [comment]
@boegelbot please test @ generoso

**Comment by verdurin** [comment]
Test report by @verdurin
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
easybuild-c7.novalocal - Linux CentOS Linux 7.9.2009, x86_64, Intel Xeon Processor (Skylake, IBRS), Python 3.6.8
See https://gist.github.com/verdurin/ff83a0fea14d3037f4e9d1325e6a1747 for a full test report.

**Comment by verdurin** [comment]
@boegelbot please test @ jsc-zen3

**Review by bedroge — APPROVED** [review]
Lgtm

**Comment by bedroge** [comment]
Test report by @bedroge
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
interactive2 - Linux Rocky Linux 8.9, x86_64, AMD EPYC-Milan Processor (zen2), Python 3.6.8
See https://gist.github.com/bedroge/5dd06f3711acdb3cb61f8990a6d0e2fa for a full test report.

**Comment by bedroge** [comment]
Going in, thanks @verdurin!

**Pull request merged**
