### PR TITLE
add patches to fix PyTorch-1.12.1 w/ foss/2022a + CUDA v11.7.0 on POWER

### PR DESCRIPTION
**Pull request by Flamefire**
(created using `eb --new-pr`)

Same as #18490 but for the CUDA version (single EC changed due to time it takes for testing the CUDA version)

### CODE REVIEW

**Comment by Flamefire** [comment]
Test report by @Flamefire
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
taurusml24 - Linux RHEL 7.6, POWER, 8335-GTX (power9le), 6 x NVIDIA Tesla V100-SXM2-32GB, 440.64.00, Python 2.7.5
See https://gist.github.com/Flamefire/a73d4119146b3c1e6efabdbd1b48f77c for a full test report.

**Comment by Flamefire** [comment]
Test report by @Flamefire
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
taurusi8004 - Linux CentOS Linux 7.9.2009, x86_64, AMD EPYC 7352 24-Core Processor (zen2), 8 x NVIDIA NVIDIA A100-SXM4-40GB, 470.57.02, Python 2.7.5
See https://gist.github.com/Flamefire/71fb08e9a3211a2d7cff8208e5d721a2 for a full test report.

**Comment by Flamefire** [comment]
Accidentally added a wrong EC, hence the force-push to remove that commit.

**Comment by akesandgren** [comment]
Test report by @akesandgren
**FAILED**
Build succeeded for 0 out of 1 (1 easyconfigs in total)
b-cn1601.hpc2n.umu.se - Linux Ubuntu 22.04, x86_64, AMD EPYC 7413 24-Core Processor, 2 x NVIDIA NVIDIA A100 80GB PCIe, 525.125.06, Python 3.10.6
See https://gist.github.com/akesandgren/e153050c1f6be8ea1d824664f146d599 for a full test report.

**Comment by akesandgren** [comment]
Test report by @akesandgren
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
b-cn1601.hpc2n.umu.se - Linux Ubuntu 22.04, x86_64, AMD EPYC 7413 24-Core Processor, 2 x NVIDIA NVIDIA A100 80GB PCIe, 525.125.06, Python 3.10.6
See https://gist.github.com/akesandgren/52d21905884f3017d2580a667196d739 for a full test report.

**Comment by akesandgren** [comment]
@boegel any idea on why it failed for you?

**Comment by akesandgren** [comment]
Test report by @akesandgren
Using easyblocks from PR(s) https://github.com/easybuilders/easybuild-easyblocks/pull/2983
**FAILED**
Build succeeded for 0 out of 3 (1 easyconfigs in total)
b-cn1501.hpc2n.umu.se - Linux Ubuntu 20.04, x86_64, Intel(R) Xeon(R) Gold 6132 CPU @ 2.60GHz, 2 x NVIDIA Tesla V100-PCIE-16GB, 470.199.02, Python 3.8.10
See https://gist.github.com/akesandgren/1f3824780c04492e9999b4dd65cba9e5 for a full test report.

**Comment by branfosj** [comment]
Test report by @branfosj
Using easyblocks from PR(s) https://github.com/easybuilders/easybuild-easyblocks/pull/2983
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
bear-pg0208u23a - Linux RHEL 8.6, x86_64, Intel(R) Xeon(R) Platinum 8360Y CPU @ 2.40GHz (icelake), 1 x NVIDIA NVIDIA A100-SXM4-40GB, 520.61.05, Python 3.6.8
See https://gist.github.com/branfosj/3ee7f76c9445090f03195119d97c32de for a full test report.

**Comment by akesandgren** [comment]
Test report by @akesandgren
Using easyblocks from PR(s) https://github.com/easybuilders/easybuild-easyblocks/pull/2983
**FAILED**
Build succeeded for 0 out of 1 (1 easyconfigs in total)
b-cn1501.hpc2n.umu.se - Linux Ubuntu 20.04, x86_64, Intel(R) Xeon(R) Gold 6132 CPU @ 2.60GHz, 2 x NVIDIA Tesla V100-PCIE-16GB, 470.199.02, Python 3.8.10
See https://gist.github.com/akesandgren/b1195a85a8a38ca7ace5ecc26adfd1b4 for a full test report.

**Comment by Flamefire** [comment]
@akesandgren Looks like an issue with your (not) existing modules?
```
== 2023-08-25 11:46:36,693 modules.py:647 INFO Module magma/2.6.2-CUDA-11.7.0 not found via module avail/show, checking whether it is a wrapper
== 2023-08-25 11:46:36,697 modules.py:654 INFO Result for existence check of magma/2.6.2-CUDA-11.7.0 module: False
== 2023-08-25 11:46:37,083 build_log.py:171 ERROR EasyBuild crashed with an error (at easybuild/base/exceptions.py:126 in __init__): Can't get value from a non-existing module magma/2.6.2-CUDA-11.7.0 (at easybuild/tools/modules.py:743 in get_value_from_modulefile)
== 2023-08-25 11:46:37,084 easyblock.py:3519 WARNING Sanity check: loading fake module failed: "Can't get value from a non-existing module magma/2.6.2-CUDA-11.7.0"
```

@boegel Another instance of "EasyBuild crashed with an error" which is later "downgraded" to a warning due to `EasyBuildError` logging itself on construction

**Comment by akesandgren** [comment]
Test report by @akesandgren
Using easyblocks from PR(s) https://github.com/easybuilders/easybuild-easyblocks/pull/2983
**SUCCESS**
Build succeeded for 3 out of 3 (1 easyconfigs in total)
b-cn1501.hpc2n.umu.se - Linux Ubuntu 20.04, x86_64, Intel(R) Xeon(R) Gold 6132 CPU @ 2.60GHz, 2 x NVIDIA Tesla V100-PCIE-16GB, 470.199.02, Python 3.8.10
See https://gist.github.com/akesandgren/c92d5a86298af5052f89a6349a0a5db7 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
node3308.joltik.os - Linux RHEL 8.6, x86_64, Intel(R) Xeon(R) Gold 6242 CPU @ 2.80GHz (cascadelake), 1 x NVIDIA Tesla V100-SXM2-32GB, 530.30.02, Python 3.6.8
See https://gist.github.com/boegel/7d17e0133f68237659a5dfdf9e3826da for a full test report.

**Review by boegel — APPROVED** [review]
lgtm

**Comment by boegel** [comment]
Going in, thanks @Flamefire!

**Pull request merged**
