### PR TITLE
fix Togl configure patch so that it completely ignores TCL_SRC_DIR and TK_SRC_DIR

### PR DESCRIPTION
**Pull request by migueldiascosta**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by migueldiascosta** [comment]
Test report by @migueldiascosta
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
sms - Linux centos linux 7.6.1810, x86_64, AMD EPYC 7601 32-Core Processor (zen), Python 2.7.5
See https://gist.github.com/d140eeba38bb6ba5f32c04d898a45f29 for a full test report.

**Comment by smoors** [comment]
@migueldiascosta can you explain a bit which problem is fixed here?

**Comment by migueldiascosta** [comment]
@smoors Togl's `configure` sets `TCL_SRC_DIR` and  `TK_SRC_DIR` to the values obtained from `tclConfig.sh` and `tkConfig.sh` and those point to where `Tcl` and `Tk` where built, not installed. 

But it's actually not necessary, the header files it needs are in the install folders and those are included anyway. 

This PR makes it completely ignore those paths, to fix the problem reported in https://github.com/easybuilders/easybuild-easyconfigs/issues/10657

**Comment by smoors** [comment]
Test report by @smoors
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
node254.hydra.os - Linux centos linux 7.7.1908, x86_64, Intel(R) Xeon(R) CPU E5-2683 v4 @ 2.10GHz (broadwell), Python 2.7.5
See https://gist.github.com/3354dc55ed9f0a360036cede8c08aaaa for a full test report.

**Comment by smoors** [comment]
Going in, thanks @migueldiascosta!

**Pull request merged**
