### PR TITLE
{lang}[GCCcore/8.2.0,GCCcore/8.3.0,GCCcore/9.3.0] Python v2.7.15, Python v2.7.16, Python v2.7.18

### PR DESCRIPTION
**Pull request by jfgrimm**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by jfgrimm** [comment]
@boegelbot: please test @ generoso

**Comment by SebastianAchilles** [comment]
@boegelbot please test @ jsc-zen2
CORE_CNT=16

**Comment by SebastianAchilles** [comment]
Test report by @sebastianachilles
**SUCCESS**
Build succeeded for 3 out of 3 (3 easyconfigs in total)
skylake-alma8-eb - Linux AlmaLinux 8.5, x86_64, Intel(R) Core(TM) i7-8700 CPU @ 3.20GHz (skylake), Python 3.6.8
See https://gist.github.com/f52304f6569aa145e4c0d4a4efd01e54 for a full test report.

**Review by SebastianAchilles — APPROVED** [review]
lgtm

**Comment by SebastianAchilles** [comment]
Going in, thanks @jfgrimm!

**Pull request merged**
