### PR TITLE
{bio}[intel/2019a] mygene v3.1.0 w/ Python 2.7.15 + 3.7.2

### PR DESCRIPTION
**Pull request by Darkless012**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
node2071.delcatty.os - Linux centos linux 7.6.1810, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.7.5
See https://gist.github.com/f34bbd9aa16eface42154c290cc22b5b for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
node2403.golett.os - Linux centos linux 7.6.1810, Intel(R) Xeon(R) CPU E5-2680 v3 @ 2.50GHz, Python 2.7.5
See https://gist.github.com/660f992329f88a6fcaf843c2a6466209 for a full test report.

**Comment by Darkless012** [comment]
Test report by @Darkless012
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
node3209.victini.os - Linux centos linux 7.6.1810, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz, Python 2.7.5
See https://gist.github.com/6df1a4ac83f4aa570b3a28419d3c287d for a full test report.

**Comment by boegel** [comment]
Going in, thanks @Darkless012!

**Pull request merged**
