### PR TITLE
{lang}[system/system] Java v21.0.2, Java v21

### PR DESCRIPTION
**Pull request by branfosj**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by branfosj** [comment]
Test report by @branfosj
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in total)
bear-pg0105u03a - Linux RHEL 8.6, x86_64, Intel(R) Xeon(R) Platinum 8360Y CPU @ 2.40GHz (icelake), Python 3.6.8
See https://gist.github.com/branfosj/2bf80ba8af9e20892827711fed73a3ec for a full test report.

**Review by Micket — DISMISSED** [review]
lgtm

**Comment by Micket** [comment]
Test report by @Micket
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in total)
vera-skylake-build - Linux Rocky Linux 8.9, x86_64, Intel Xeon Processor (Skylake, IBRS, no TSX), Python 3.6.8
See https://gist.github.com/Micket/1f6684d2c3f6700e7d87bd4b96fda999 for a full test report.

**Comment by Micket** [comment]
@boegelbot please test @ generoso

**Comment by jfgrimm** [comment]
sorry, I merged https://github.com/easybuilders/easybuild-easyconfigs/pull/19710

**Comment by branfosj** [comment]
I missed #19710 when creating this. Now this only adds the `Java/21` wrapper and updates the Java homepage.

**Review by Micket — APPROVED** [review]
still lgtm :)

**Comment by Micket** [comment]
@boegelbot please test @ jsc-zen3

**Pull request merged**
