### PR TITLE
{chem}[intel-compilers/2021.4.0] DFT-D3 v3.2.0

### PR DESCRIPTION
**Pull request by bedroge**
(created using `eb --new-pr`)

This uses the new homepage and source url (see #17528, which changes this for all existing easyconfigs).

### CODE REVIEW

**Comment by bedroge** [comment]
Test report by @bedroge
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
bob-Latitude-5300 - Linux Ubuntu 22.04, x86_64, Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz, Python 3.10.6
See https://gist.github.com/a88d623b9490039968663dfce6717ce9 for a full test report.

**Comment by bedroge** [comment]
Test report by @bedroge
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
bob-Latitude-5300 - Linux Ubuntu 22.04, x86_64, Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz, Python 3.10.6
See https://gist.github.com/a64a4dd8ae3b9a276a736cc9a6c6061d for a full test report.

**Comment by bedroge** [comment]
@boegelbot please test @ generoso

**Review by casparvl — APPROVED** [review]
Pretty standard update, plenty of test reports. Lgtm!

**Comment by casparvl** [comment]
Test report by @casparvl
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
tcn1.local.snellius.surf.nl - Linux Rocky Linux 8.7, x86_64, AMD EPYC 7H12 64-Core Processor, Python 3.6.8
See https://gist.github.com/e6f47c6072400b0d6c2c79848ea4857b for a full test report.

**Comment by casparvl** [comment]
Going in, thanks @bedroge!

**Pull request merged**
