### PR TITLE
{tools}[GCCcore/13.3.0] fish v3.7.1

### PR DESCRIPTION
**Pull request by SebastianAchilles**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by SebastianAchilles** [comment]
Test report by @sebastianachilles
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
zen2-rockylinux-810 - Linux Rocky Linux 8.10, x86_64, AMD EPYC 7452 32-Core Processor (zen2), Python 3.6.8
See https://gist.github.com/SebastianAchilles/f5c2b0b7cd053df5002fd2d768d7a331 for a full test report.

**Comment by SebastianAchilles** [comment]
@boegelbot please test @ jsc-zen3

**Comment by SebastianAchilles** [comment]
@boegelbot please test @ generoso

**Review by smoors — APPROVED** [review]
lgtm

**Comment by smoors** [comment]
Going in, thanks @SebastianAchilles!

**Comment by boegel** [comment]
Test report by @boegel
**FAILED**
Build succeeded for 0 out of 1 (1 easyconfigs in total)
node3128.skitty.os - Linux RHEL 8.8, x86_64, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz, Python 3.6.8
See https://gist.github.com/boegel/82762189801f6e573bdba5742ea80a23 for a full test report.

**Comment by boegel** [comment]
@SebastianAchilles Doesn't work for me for some reason:
```
[ 98%] Building man pages with Sphinx
[100%] Building HTML documentation with Sphinx
env PATH="/tmp/vsc40023/easybuild_build/fish/3.7.1/GCCcore-13.3.0/easybuild_obj:$PATH" /usr/bin/sphinx-build -j auto -q -b man -c /tmp/vsc40023/easybuild_build/fish/3.7.1/GCCcore-13.3.0/fish-3.7.1/doc_src -d /tmp/vsc40023/easybuild_build/fish/3.7.1/GCCcore-13.3.0/easybuild_obj/user_doc/.doctrees-man /tmp/vsc40023/easybuild_build/fish/3.7.1/GCCcore-13.3.0/fish-3.7.1/doc_src /tmp/vsc40023/easybuild_build/fish/3.7.1/GCCcore-13.3.0/easybuild_obj/user_doc/man/man1
mkdir -p /tmp/vsc40023/easybuild_build/fish/3.7.1/GCCcore-13.3.0/easybuild_obj/user_doc/html/_static/
env PATH="/tmp/vsc40023/easybuild_build/fish/3.7.1/GCCcore-13.3.0/easybuild_obj:$PATH" /usr/bin/sphinx-build -j auto -q -b html -c /tmp/vsc40023/easybuild_build/fish/3.7.1/GCCcore-13.3.0/fish-3.7.1/doc_src -d /tmp/vsc40023/easybuild_build/fish/3.7.1/GCCcore-13.3.0/easybuild_obj/user_doc/.doctrees-html /tmp/vsc40023/easybuild_build/fish/3.7.1/GCCcore-13.3.0/fish-3.7.1/doc_src /tmp/vsc40023/easybuild_build/fish/3.7.1/GCCcore-13.3.0/easybuild_obj/user_doc/html

Sphinx parallel build error:
AttributeError: 'FishSynopsisDirective' object has no attribute 'env'

Sphinx parallel build error:
AttributeError: 'FishSynopsisDirective' object has no attribute 'env'
make[2]: *** [CMakeFiles/sphinx-manpages.dir/build.make:74: CMakeFiles/sphinx-manpages] Error 2
```

**Comment by SebastianAchilles** [comment]
Oh, that is not good.

I just create again with a minimalist Rocky Linux 8.8 container and tested it again. However, unfortunately I can not reproduce this.

I assume this has to do with building the optional documentation with sphinx. Maybe you have sphinx installed in your OS? Could you test https://github.com/easybuilders/easybuild-easyconfigs/pull/21381

**Pull request merged**
