### PR TITLE
{bio}[gompi/2019b] RMBlast v2.9.0

### PR DESCRIPTION
**Pull request by genio0815**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by genio0815** [comment]
Thanks for taking all the effort of manually checking and pointing out possible issues! According to the hp recent versions of RMBlast are installed as a patch to BLAST+ sources.

**Comment by verdurin** [comment]
@genio0815 any thoughts on the suggestions from @lexming ?

**Comment by genio0815** [comment]
Sry for the late reply - I see your point and totally agree with the suggestions! Unfortunately we don't have toolchain 2019b yet and will most probably implement the 2020a as soon as it becomes available. 
So, we could keep this on hold and I will update the easyconfig, with your suggestions implemented, as soon as we haven the 2020a toolchain installed.

**Comment by lexming** [comment]
@genio0815 thanks for the feedback. Just to be clear, it would also be possible to merge RMBlast-2.9.0 in 2019b even if you don't use it (I will do the tests in any case) and then open a new PR for 2020a when you have that ready. But if you prefer to hold this for 2020a that is also fine.

**Comment by genio0815** [comment]
I assembled a new version 'RMBlast-2.9.0-p2-foss-2019b.eb' with the same dependencies and configure options as the latest easyconfigs for BLAST+-2.9.0 plus the few ones listed on the RMBlast hp. 
We don't have the 2019b toolchain implemented so I could NOT test this! I also skipped the patch for boost > 1.67.0 (RMBlast basically is a patch itself). 
As now the file name changed too, I guess, it's better to open a new PR and close this one.

**Comment by lexming** [comment]
@genio0815 I already did all that work in https://github.com/genio0815/easybuild-easyconfigs/pull/1 . If you merge that PR it will automatically update this one.

**Comment by genio0815** [comment]
sry, should have read more carefully! Done so...

**Comment by lexming** [comment]
Thanks @genio0815 , I'll proceed with the tests for RMBlast v2.9.0
 then. Whenever you have the update for RMBlast v2.10.0 please open a new PR.

**Comment by lexming** [comment]
Test report by @lexming
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
node150.hydra.os - Linux centos linux 7.7.1908, Intel(R) Xeon(R) CPU E5-2680 v2 @ 2.80GHz, Python 2.7.5
See https://gist.github.com/3ce18bd18f0563f76c3d54b85b77d815 for a full test report.

**Comment by lexming** [comment]
@verdurin this PR is ready to be reviewed. I prefer to not merge it myself as I have authored a significant part of the easyconfig.

**Comment by verdurin** [comment]
Test report by @verdurin
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
easybuild.novalocal - Linux centos linux 7.7.1908, Intel Xeon Processor (Skylake, IBRS), Python 2.7.5
See https://gist.github.com/9189eeb501fa85cab8d921e8058bdb89 for a full test report.

**Comment by verdurin** [comment]
Going in, thanks @genio0815!

**Comment by genio0815** [comment]
great and thanks! will submit new PR for version 2.10 in 2020a asap.

**Pull request merged**
