### PR TITLE
Added QuantumESPRESSO easyconfigs for 7.3 (both intel and foss)

### PR DESCRIPTION
**Pull request by Crivella**
Added easyconfig files for QE 7.3 working with new easyblock from [PR-3241](https://github.com/easybuilders/easybuild-easyblocks/pull/3241)

Also ran some performance testing on a workstations with an intel i9-13900k.
After taking into account the presence of both performance and efficiency cores, and running all tests with the same pinning for reproducibility, both the `-O3` and `-ffast-math` do not give any visible improvement at the scale this tests are being ran.

In order to properly compare the efficiency with respect to the EESSI version (compiled with older easyblock), a multi-node heavy run would be needed as what has been fixed is mostly related to Scalapack and ELPA libraries usage.

image

The run reported are generated using the ReFrame test from [PR-3134](https://github.com/reframe-hpc/reframe/pull/3134) with `ecut=100` and `nbnd=100`

### CODE REVIEW

**Comment by ocaisa** [comment]
@boegelbot please test @ generoso
EB_ARGS="--include-easyblocks-from-pr 3241"

**Comment by Crivella** [comment]
Removing the FoX requirment which was causing issues in the compilation for ARM architectures.

**Comment by ocaisa** [comment]
@boegelbot please test @ generoso
EB_ARGS="--include-easyblocks-from-pr 3258"

**Comment by ocaisa** [comment]
@boegelbot please test @ generoso
EB_ARGS="--include-easyblocks-from-pr 3258"

**Comment by ocaisa** [comment]
@boegelbot please test @ jsc-zen3
EB_ARGS="--include-easyblocks-from-pr 3258"

**Review by ocaisa — APPROVED** [review]
These have also been tested extensively in https://github.com/EESSI/software-layer/pull/504

**Pull request merged**
