### PR TITLE
{bio}[foss/2020a] python-parasail v1.2.3 w/ Python 3.8.2

### PR DESCRIPTION
**Pull request by manifestoso**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by robqiao** [comment]
deps on PR #14246

**Comment by verdurin** [comment]
@boegelbot please test @ generoso

**Comment by verdurin** [comment]
Test report by @verdurin
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
centos7.lan - Linux centos linux 7.9.2009, x86_64, Intel Core Processor (Skylake, IBRS), Python 3.6.8
See https://gist.github.com/7bb96a3a7ed0b39cd56420b67e391fc9 for a full test report.

**Review by verdurin — APPROVED** [review]
Looks fine.

**Comment by verdurin** [comment]
@robqiao please use `--sync-pr-with-develop` so we can merge this without complaints from `--merge-pr` about the test suite.

**Pull request merged**
