### PR TITLE
{lang}[GCCcore/12.2.0] nodejs v18.12.1

### PR DESCRIPTION
**Pull request by boegel**
(created using `eb --new-pr`)

### CODE REVIEW

**Review by lexming — COMMENTED** [review]
There are multiple issues with this way of installing nodejs, please check https://github.com/easybuilders/easybuild-easyconfigs/pull/16529

**Comment by boegel** [comment]
> There are multiple issues with this way of installing nodejs, please check #16529

fixed in 46b4c40

**Comment by boegel** [comment]
@boegelbot please test @ generoso
CORE_CNT=16

**Review by lexming — APPROVED** [review]
LGTM

**Comment by lexming** [comment]
Going in, thanks @boegel !

**Pull request merged**
