### PR TITLE
add missMDA extension to R-bundle-CRAN 2024.06

### PR DESCRIPTION
**Pull request by boegel**
(created using `eb --new-pr`)
cfr. #21167

### CODE REVIEW

**Comment by boegel** [comment]
@boegelbot please test @ jsc-zen3
EB_ARGS="--skip"

**Review by laraPPr — APPROVED** [review]
lgtm

**Comment by laraPPr** [comment]
Test report by @laraPPr
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
node3541.doduo.os - Linux RHEL 8.8, x86_64, AMD EPYC 7552 48-Core Processor, Python 3.11.3
See https://gist.github.com/laraPPr/e6799f24693cd2fb276700d5e37e6c84 for a full test report.

**Comment by laraPPr** [comment]
Going in, thanks @boegel!

**Pull request merged**
