### PR TITLE
{devel}[system/system] ReFrame v4.2.0

### PR DESCRIPTION
**Pull request by akesandgren**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by akesandgren** [comment]
Do we need https://github.com/easybuilders/easybuild-easyconfigs/pull/13844 to be sorted out, or is that mote now?

**Comment by smoors** [comment]
> Do we need #13844 to be sorted out, or is that mote now?

IIU @boegel C this is no longer be needed for EESSI (or will no longer be in the near future)

**Comment by boegel** [comment]
I think injecting the `-S` *is* still needed to avoid surprises in certain environments (and the downsides should be very limited).

**Comment by akesandgren** [comment]
@boegel can you provide a change then?

**Comment by smoors** [comment]
@akesandgren he's saying that you don't need to change anything :)

**Comment by smoors** [comment]
@boegelbot: please test @ generoso

**Comment by smoors** [comment]
@boegelbot please test @ jsc-zen2

**Review by smoors — APPROVED** [review]
lgtm

**Comment by casparvl** [comment]
@boegelbot please test @ generoso

**Pull request merged**
