### PR TITLE
{devel}[GCC/9.3.0] Boost.Serial v1.72.0

### PR DESCRIPTION
**Pull request by mboisson**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by mboisson** [comment]
@SimonPinches, this is a change for Boost"-no_mpi" introduced previously. After the EB call today, we are introducing Boost.Serial, instead of having a version suffix.

**Comment by lexming** [comment]
Changed target to [easybuilders:dual_serial_mpi](https://github.com/easybuilders/easybuild-easyconfigs/tree/dual_serial_mpi)

**Comment by lexming** [comment]
Test report by @lexming
**FAILED**
Build succeeded for 0 out of 2 (2 easyconfigs in this PR)
node368.hydra.os - Linux centos linux 7.7.1908, x86_64, Intel(R) Xeon(R) Gold 6148 CPU @ 2.40GHz, Python 2.7.5
See https://gist.github.com/021b1e0b162be6e3a61aa2cd1142f481 for a full test report.

**Comment by lexming** [comment]
Test report by @lexming
**FAILED**
Build succeeded for 0 out of 2 (2 easyconfigs in this PR)
node101.hydra.os - Linux centos linux 7.7.1908, x86_64, Intel(R) Xeon(R) CPU E5-2680 v2 @ 2.80GHz, Python 2.7.5
See https://gist.github.com/6b12c4f3b6f9ad3ee3debe9c3b8ea609 for a full test report.

**Comment by SimonPinches** [comment]
@mboisson thanks for the heads-up regarding the change of suffix name.  I have to say I'm sorry to see the loss of a ` GCCcore` version since this means I'll now need to build at at least two versions of all the libraries that depend upon it :-(   This may even lead to conflicts in some of our mixed compilation workflows but I'll try to work around this.

**Comment by lexming** [comment]
@SimonPinches going down to `GCCcore` level for serial builds is indeed a good point to discuss. I'll add it for the conf call.

**Comment by mboisson** [comment]
@lexming, the reason even Compute Canada did not do that is that we will always want to have a Boost with GCC and one with Intel. Bringing it down to GCCcore means that users run the risk of using GCC-compiled libraries with Intel, or that we need to forgo optimizations brought forward by the Intel compiler (which can be useful for algorithms in Boost).

**Comment by lexming** [comment]
Fixes for the failed tests can be found in https://github.com/easybuilders/easybuild-easyblocks/pull/2167

**Comment by lexming** [comment]
Test report by @lexming
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in this PR)
node381.hydra.os - Linux centos linux 7.7.1908, x86_64, Intel(R) Xeon(R) Gold 6148 CPU @ 2.40GHz, Python 2.7.5
See https://gist.github.com/c1b1130f736fe713e49c91f8a71d5b01 for a full test report.

**Comment by lexming** [comment]
Test report by @lexming
**FAILED**
Build succeeded for 1 out of 2 (2 easyconfigs in this PR)
node128.hydra.os - Linux centos linux 7.7.1908, x86_64, Intel(R) Xeon(R) CPU E5-2680 v2 @ 2.80GHz, Python 2.7.5
See https://gist.github.com/fba8677b708fb04574302a4145c70953 for a full test report.

**Comment by lexming** [comment]
Test report by @lexming
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in this PR)
node116.hydra.os - Linux centos linux 7.7.1908, x86_64, Intel(R) Xeon(R) CPU E5-2680 v2 @ 2.80GHz, Python 2.7.5
See https://gist.github.com/e7063afd680d43861abfc406ddf9349c for a full test report.

**Comment by migueldiascosta** [comment]
Test report by @migueldiascosta
using easyblocks from https://github.com/easybuilders/easybuild-easyblocks/pull/2167
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in this PR)
sms - Linux centos linux 7.6.1810, x86_64, AMD EPYC 7601 32-Core Processor (zen), Python 2.7.5
See https://gist.github.com/c59fb3f979395147e1e31c229508f21b for a full test report.

**Comment by lexming** [comment]
Test report by @lexming
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in this PR)
node377.hydra.os - Linux centos linux 7.7.1908, x86_64, Intel(R) Xeon(R) Gold 6148 CPU @ 2.40GHz, Python 2.7.5
See https://gist.github.com/c651b636cb43ab282caf01919cdee8b9 for a full test report.

**Comment by lexming** [comment]
Test report by @lexming
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in total)
node302.hydra.os - Linux centos linux 7.7.1908, x86_64, Intel(R) Xeon(R) Gold 6148 CPU @ 2.40GHz, Python 2.7.5
See https://gist.github.com/7340253e680975a8341931604cc34480 for a full test report.

**Review by lexming — APPROVED** [review]
LGTM

**Comment by lexming** [comment]
Going in, thanks @mboisson !

**Pull request merged**
