### PR TITLE
{bio}[SYSTEM] SeqKit v0.8.1

### PR DESCRIPTION
**Pull request by bedroge**

### CODE REVIEW

**Comment by boegel** [comment]
@bedroge Any specific reason you're opting for the binary package rather than building from source?

**Comment by bedroge** [comment]
Several installation methods are listed on this page:
https://github.com/shenwei356/seqkit#installation

I tried method 4 (which, I guess, involves building from source), but that did not work, so I just chose the most simple one ;-)
But I think the issue with compiling was related to the version of my Go compiler, so I can try it again with a more recent version.

**Comment by bedroge** [comment]
I tried method 4 (go get -u github.com/shenwei356/seqkit/seqkit) with a newer Go version, and that indeed seems to work. It will take the sources and compile a binary; both were by default stored in ~/go, but this can, apparently, be changed by setting $GOPATH. 

What's the best way to do this? Should this be a new generic easyblock (GoPackage?), can I re-use an existing one, or is the binary version just fine?

**Comment by bedroge** [comment]
I did an attempt to make a GoPackage easyblock, see:
https://github.com/easybuilders/easybuild-easyblocks/pull/1629

**Comment by bedroge** [comment]
@boegel now that there's a GoPackage easyblock, I gave this another shot (after 2 years... ;-) ), and this seems to work well. As a bonus, I also have a working easyconfig for the latest version of SeqKit (0.13.2). Should I add that here or as a separate PR?

**Comment by verdurin** [comment]
Test report by @verdurin
**SUCCESS**
Build succeeded for 2 out of 2 (1 easyconfigs in this PR)
nuc.lan - Linux Fedora 32, x86_64, Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz, Python 3.8.5
See https://gist.github.com/58aa383f2f606a32e9411c96ed62ae93 for a full test report.

**Comment by verdurin** [comment]
@bedroge please add the newer version as a separate PR.

**Comment by verdurin** [comment]
@boegelbot please test @ generoso

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
node3402.kirlia.os - Linux centos linux 7.8.2003, x86_64, Intel(R) Xeon(R) Gold 6240 CPU @ 2.60GHz (cascadelake), Python 2.7.5
See https://gist.github.com/9350a13b15f91031527ec3996afac862 for a full test report.

**Review by boegel — APPROVED** [review]
lgtm

**Comment by boegel** [comment]
Going in, thanks @bedroge!

**Pull request merged**
