### PR TITLE
use skani rather than FastANI as dependency for GTDB-Tk v2.4.0

### PR DESCRIPTION
**Pull request by akesandgren**
(created using `eb --new-pr`)

As per the description of [GTDB-Tk v2.4.0](https://github.com/Ecogenomics/GTDBTk#-new-features):
```
GTDB-Tk v2.4.0+ includes the following new features:

FastANI has been replaced by skani as the primary tool for computing Average Nucleotide Identity (ANI).Users may notice slight variations in the results compared to those obtained using FastANI.
```

### CODE REVIEW

**Comment by akesandgren** [comment]
Description updated

**Comment by boegel** [comment]
@akesandgren So what happens if `skani` is not around, do users see failing runs?

**Comment by boegel** [comment]
@boegelbot please test @ generoso

**Comment by boegel** [comment]
@boegelbot please test @ jsc-zen3

**Review by boegel — APPROVED** [review]
lgtm

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in total)
node3103.skitty.os - Linux RHEL 9.4, x86_64, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz (skylake_avx512), Python 3.9.18
See https://gist.github.com/boegel/f0212581dd3326a2ca5694283746b8a7 for a full test report.

**Comment by boegel** [comment]
Going in, thanks @akesandgren!

**Pull request merged**
