### PR TITLE
{bio}[foss/2020a-rc3] GROMACS v2020.1 (WIP, pending Python binding tests)

### PR DESCRIPTION
**Pull request by akesandgren**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by ocaisa** [comment]
@akesandgren GROMACS now has the Python bindings `gmxapi` (see http://manual.gromacs.org/current/gmxapi/userguide/install.html#install-from-source for installation from GROMACS source tree), should we start including those too?

**Comment by akesandgren** [comment]
Ah yes, I've been ignoring these for as long as I can...
Should clearly look at those now, i'll mark this WIP...

**Comment by akesandgren** [comment]
Test report by @akesandgren
**FAILED**
Build succeeded for 0 out of 1 (1 easyconfigs in this PR)
b-an03.hpc2n.umu.se - Linux ubuntu 16.04, Intel(R) Xeon(R) CPU E5-2690 v4 @ 2.60GHz, Python 2.7.12
See https://gist.github.com/bcf135d49533c262493318e131df145e for a full test report.

**Comment by akesandgren** [comment]
??? I get an Illegal instruction...

**Comment by zao** [comment]
Test report by @zao
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
freja - Linux ubuntu 18.04, Intel(R) Core(TM) i7-8700K CPU @ 3.70GHz, Python 2.7.17
See https://gist.github.com/25a3b6962b7dede73cf31a0fd9257da3 for a full test report.

**Comment by akesandgren** [comment]
Test report by @akesandgren
**FAILED**
Build succeeded for 0 out of 1 (1 easyconfigs in this PR)
b-cn1404.hpc2n.umu.se - Linux ubuntu 16.04, Intel(R) Xeon(R) Gold 6132 CPU @ 2.60GHz, Python 2.7.12
See https://gist.github.com/54c410d045af0430dc72e653ce8ee848 for a full test report.

**Comment by akesandgren** [comment]
Test report by @akesandgren
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
b-an03.hpc2n.umu.se - Linux ubuntu 16.04, Intel(R) Xeon(R) CPU E5-2690 v4 @ 2.60GHz, Python 2.7.12
See https://gist.github.com/15480c0affe52f12f7888fb705f80c6d for a full test report.

**Comment by akesandgren** [comment]
@ocaisa To enable gmxapi we need to turn on -DBUILD_SHARED_LIBS=ON
we currently do -DGMX_PREFER_STATIC_LIBS=ON

Any thoughts on that?
I would prefer to use shared libs for other reasons, like being able to add VMD as a plugin.

**Comment by ocaisa** [comment]
No, no thoughts, I'm no expert on GROMACS at all, it was just that the new bindings caught my eye in the last release.

**Comment by akesandgren** [comment]
I have this sorted in the upcoming easyblock (hopefully)

**Comment by akesandgren** [comment]
Replaced with #10023

**Pull request closed without merging**
