### PR TITLE
{data}[foss/2019a] causalml v0.3.0-20180610 w/ Python 3.7.2

### PR DESCRIPTION
**Pull request by smoors**
(created using `eb --new-pr`)
depends on ~~#8845~~ (statsmodels)

### CODE REVIEW

**Comment by smoors** [comment]
Test report by @smoors
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
nic425 - Linux centos linux 7.5.1804, Intel(R) Xeon(R) Gold 6148 CPU @ 2.40GHz, Python 2.7.5
See https://gist.github.com/67b9df72164db6d157eb5c76ed362f8c for a full test report.

**Comment by migueldiascosta** [comment]
closing and reopening to trigger travis

**Comment by migueldiascosta** [comment]
Test report by @migueldiascosta
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
generoso - Linux centos linux 7.6.1810, Intel(R) Xeon(R) CPU E5-2660 v4 @ 2.00GHz, Python 3.6.8
See https://gist.github.com/e085cc71863256ed2df76fdec0be1e7a for a full test report.

**Comment by migueldiascosta** [comment]
Test report by @migueldiascosta
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
generoso-1 - Linux centos linux 7.6.1810, Intel(R) Xeon(R) CPU E5-2660 v4 @ 2.00GHz, Python 3.6.8
See https://gist.github.com/18bdfc7cc23bca11e6ff5cb0a5eb658a for a full test report.

**Comment by migueldiascosta** [comment]
Going in, thanks @smoors!

**Pull request merged**
