### PR TITLE
{lib}[GCC/8.2.0-2.31.1] WebKitGTK+ v2.24.1

### PR DESCRIPTION
**Pull request by akesandgren**
(created using `eb --new-pr`)
Depends on ~~https://github.com/easybuilders/easybuild-easyconfigs/pull/8122, https://github.com/easybuilders/easybuild-easyconfigs/pull/8112, https://github.com/easybuilders/easybuild-easyconfigs/pull/8113, https://github.com/easybuilders/easybuild-easyconfigs/pull/8114, https://github.com/easybuilders/easybuild-easyconfigs/pull/8115, https://github.com/easybuilders/easybuild-easyconfigs/pull/8116, https://github.com/easybuilders/easybuild-easyconfigs/pull/8117,
https://github.com/easybuilders/easybuild-easyconfigs/pull/8089~~,
~#8226~

### CODE REVIEW

**Comment by akesandgren** [comment]
Test report by @akesandgren
**FAILED**
Build succeeded for 1 out of 2 (1 easyconfigs in this PR)
b-an03.hpc2n.umu.se - Linux ubuntu 16.04, Intel(R) Xeon(R) CPU E5-2690 v4 @ 2.60GHz, Python 2.7.12
See https://gist.github.com/3ec1e4936e11c2f5c4d4c83133d59bd1 for a full test report.

**Comment by akesandgren** [comment]
Test report by @akesandgren
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
b-an03.hpc2n.umu.se - Linux ubuntu 16.04, Intel(R) Xeon(R) CPU E5-2690 v4 @ 2.60GHz, Python 2.7.12
See https://gist.github.com/fb632c4f73059a71d338a9e3544e3886 for a full test report.

**Comment by akesandgren** [comment]
Test report by @akesandgren
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
b-an03.hpc2n.umu.se - Linux ubuntu 16.04, Intel(R) Xeon(R) CPU E5-2690 v4 @ 2.60GHz, Python 2.7.12
See https://gist.github.com/79b9884515c961745300bb81fcc97456 for a full test report.

**Comment by akesandgren** [comment]
Test report by @akesandgren
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
b-an03.hpc2n.umu.se - Linux ubuntu 16.04, Intel(R) Xeon(R) CPU E5-2690 v4 @ 2.60GHz, Python 2.7.12
See https://gist.github.com/f5565dda0c48e88996e97a1d21acd309 for a full test report.

**Comment by vanzod** [comment]
Test report by @vanzod
**FAILED**
Build succeeded for 19 out of 24 (1 easyconfigs in this PR)
cermis - Linux debian 9.9, Intel(R) Xeon(R) CPU           X5670  @ 2.93GHz, Python 2.7.13
See https://gist.github.com/bfbaaef49c7fe29605171bdd5cf3b1a8 for a full test report.

**Comment by vanzod** [comment]
Test report by @vanzod
**FAILED**
Build succeeded for 2 out of 3 (1 easyconfigs in this PR)
cermis - Linux debian 9.9, Intel(R) Xeon(R) CPU           X5670  @ 2.93GHz, Python 2.7.13
See https://gist.github.com/40e34050776bbcb462b306f5a9d5f5cc for a full test report.

**Comment by vanzod** [comment]
@akesandgren It looks like `HarfBuzz` is required as a dependency

**Comment by akesandgren** [comment]
Harfbuzz is already part of the dependency chain:
This is from your test report. Harfbuzz is nr 8 in the list.

Found GDK3: /opt/easybuild/software/Compiler/GCCcore/8.2.0/GTK+/3.24.8/include/gtk-3.0;/opt/easybuild/software/Compiler/GCCcore/8.2.0/FriBidi/1.0.5/include/fribidi;/opt/easybuild/software/Compiler/GCCcore/8.2.0/libepoxy/1.5.3/include;/opt/easybuild/software/Compiler/GCCcore/8.2.0/Mesa/19.0.1/include;/opt/easybuild/software/Compiler/GCCcore/8.2.0/libdrm/2.4.97/include;/opt/easybuild/software/Compiler/GCCcore/8.2.0/libdrm/2.4.97/include/libdrm;/opt/easybuild/software/Compiler/GCCcore/8.2.0/Pango/1.43.0/include/pango-1.0;/opt/easybuild/software/Compiler/GCCcore/8.2.0/HarfBuzz/2.4.0/include/harfbuzz;/opt/easybuild/software/Compiler/GCCcore/8.2.0/Gdk-Pixbuf/2.38.1/include/gdk-pixbuf-2.0;/opt/easybuild/software/Compiler/GCCcore/8.2.0/cairo/1.16.0/include/cairo;/opt/easybuild/software/Compiler/GCCcore/8.2.0/X11/20190311/include;/opt/easybuild/software/Compiler/GCCcore/8.2.0/fontconfig/2.13.1/include;/opt/easybuild/software/Compiler/GCCcore/8.2.0/pixman/0.38.0/include/pixman-1;/opt/easybuild/software/Compiler/GCCcore/8.2.0/freetype/2.9.1/include/freetype2;/opt/easybuild/software/Compiler/GCCcore/8.2.0/libpng/1.6.36/include/libpng16;/opt/easybuild/software/Compiler/GCCcore/8.2.0/GLib/2.60.1/include/gio-unix-2.0;/opt/easybuild/software/Compiler/GCCcore/8.2.0/GLib/2.60.1/include;/opt/easybuild/software/Compiler/GCCcore/8.2.0/GLib/2.60.1/include/glib-2.0;/opt/easybuild/software/Compiler/GCCcore/8.2.0/GLib/2.60.1/lib/glib-2.0/include;/opt/easybuild/software/Compiler/GCCcore/8.2.0/util-linux/2.33/include/libmount;/opt/easybuild/software/Compiler/GCCcore/8.2.0/util-linux/2.33/include/blkid;/opt/easybuild/software/Compiler/GCCcore/8.2.0/util-linux/2.33/include/uuid;/opt/easybuild/software/Compiler/GCCcore/8.2.0/PCRE/8.43/include;/opt/easybuild/software/Compiler/GCCcore/8.2.0/libffi/3.2.1/include;/opt/easybuild/software/Compiler/GCCcore/8.2.0/expat/2.2.6/include;/opt/easybuild/software/Compiler/GCCcore/8.2.0/zlib/1.2.11/include

**Comment by vanzod** [comment]
@akesandgren No, I do not have any `$EBROOTHARFBUZZ/lib/libharfbuzz-icu.so` in my installation.

**Comment by akesandgren** [comment]
Ok, can you check your harbuzz build log to see if it says something about missing stuff?

**Comment by akesandgren** [comment]
That lib needs libicudata.so and friends.
I'll make an update to harfbuzz so it has ICU as dep.

**Comment by vanzod** [comment]
Test report by @vanzod
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
cermis - Linux debian 9.9, Intel(R) Xeon(R) CPU           X5670  @ 2.93GHz, Python 2.7.13
See https://gist.github.com/167f261a12dfee5cc5aa6f3a18c79a0a for a full test report.

**Comment by vanzod** [comment]
Going in, thanks @akesandgren!

**Comment by boegel** [comment]
Test report by @boegel
**FAILED**
Build succeeded for 0 out of 1 (1 easyconfigs in this PR)
node3129.skitty.os - Linux centos linux 7.6.1810, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz, Python 2.7.5
See https://gist.github.com/a0220bcd532f307ac358050ddf27f5d7 for a full test report.

**Comment by boegel** [comment]
@akesandgren Missing `Ruby` dep:

```
-- Could NOT find Ruby (missing: RUBY_EXECUTABLE RUBY_INCLUDE_DIR RUBY_LIBRARY) (Required is at least version "1.9")
```

**Comment by boegel** [comment]
@akesandgren #8239 will come in useless to fix the missing dep...

**Comment by boegel** [comment]
missing `Ruby` dep fixed in #8243

**Pull request merged**
