### PR TITLE
{toolchain} intel/2022.00

### PR DESCRIPTION
**Pull request by boegel**
(created using `eb --new-pr`)

requires:
* https://github.com/easybuilders/easybuild-easyblocks/pull/2644

### CODE REVIEW

**Comment by boegel** [comment]
@boegelbot please test @ generoso
EB_ARGS="--include-easyblocks 2644"

**Comment by boegel** [comment]
Test report by @boegel
Using easyblocks from PR(s) https://github.com/easybuilders/easybuild-easyblocks/pull/2644
**SUCCESS**
Build succeeded for 7 out of 7 (7 easyconfigs in total)
node3513.doduo.os - Linux RHEL 8.2, x86_64, AMD EPYC 7552 48-Core Processor (zen2), Python 3.6.8
See https://gist.github.com/36c85a018e7f245b6f34e6ef434ae925 for a full test report.

**Comment by bedroge** [comment]
Test report by @bedroge
Using easyblocks from PR(s) https://github.com/easybuilders/easybuild-easyblocks/pull/2644
**FAILED**
Build succeeded for 0 out of 7 (7 easyconfigs in total)
bob-Latitude-5300 - Linux Ubuntu 20.04, x86_64, Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz, Python 3.8.10
See https://gist.github.com/9d74cfdd093e9d4c24e74b4f9f0be44b for a full test report.

**Comment by boegel** [comment]
@bedroge You need to use `--accept-eula-for=Intel-oneAPI` :)

**Comment by bedroge** [comment]
Test report by @bedroge
Using easyblocks from PR(s) https://github.com/easybuilders/easybuild-easyblocks/pull/2644
**SUCCESS**
Build succeeded for 7 out of 7 (7 easyconfigs in total)
bob-Latitude-5300 - Linux Ubuntu 20.04, x86_64, Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz, Python 3.8.10
See https://gist.github.com/415085ceb7d9bfa5f3dbfeb1efa5394f for a full test report.

**Review by bedroge — APPROVED** [review]
lgtm

**Comment by bedroge** [comment]
Going in, thanks @boegel!

**Pull request merged**
