### PR TITLE
{vis}[GCCcore/11.3.0] bwidget v1.9.15, Togl v2.0, XCrySDen v1.6.2

### PR DESCRIPTION
**Pull request by anselmicz**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by anselmicz** [comment]
Test report by @anselmicz
**SUCCESS**
Build succeeded for 4 out of 4 (4 easyconfigs in total)
login1.karolina.it4i.cz - Linux CentOS Linux 7 (Core), x86_64, AMD EPYC 7452 32-Core Processor, Python 3.10.4
See https://gist.github.com/c6491813ae3d4623614058d422cc7e15 for a full test report.

**Comment by anselmicz** [comment]
Test report by @anselmicz
**SUCCESS**
Build succeeded for 4 out of 4 (4 easyconfigs in total)
login1.barbora.it4i.cz - Linux RHEL 8.4, x86_64, Intel(R) Xeon(R) Gold 6240 CPU @ 2.60GHz (cascadelake), Python 3.6.8
See https://gist.github.com/5a2cea6d20dfc48a0df00b8be4d21f6d for a full test report.

**Comment by verdurin** [comment]
Test report by @verdurin
**SUCCESS**
Build succeeded for 4 out of 4 (4 easyconfigs in total)
easybuild-c7.novalocal - Linux CentOS Linux 7.9.2009, x86_64, Intel Xeon Processor (Skylake, IBRS), Python 3.6.8
See https://gist.github.com/1f33423170268f4a4ee355cbe655310b for a full test report.

**Comment by verdurin** [comment]
@boegelbot please test @ generoso

**Review by verdurin — APPROVED** [review]
Looks fine.

**Comment by verdurin** [comment]
Going in, thanks @anselmicz!

**Pull request merged**
