### PR TITLE
{lib,lang}[foss/2017b] Boost.Python v1.65.1, PyCUDA v2017.1.1 w/ Python 2.7.14 (+ build Boost with -std=c++11)

### PR DESCRIPTION
**Pull request by boegel**
wrapper PR for #5783

### CODE REVIEW

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 3 out of 3 (3 easyconfigs in total)
node2603.swalot.os - Linux centos linux 7.8.2003, x86_64, Intel(R) Xeon(R) CPU E5-2660 v3 @ 2.60GHz (haswell), Python 2.7.5
See https://gist.github.com/e6c64c0fe5185b3f8a8a9ea3e18a852d for a full test report.

**Review by akesandgren — APPROVED** [review]
LGTM

**Comment by akesandgren** [comment]
Going in, thanks @boegel!

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 3 out of 3 (3 easyconfigs in total)
node2603.swalot.os - Linux centos linux 7.8.2003, x86_64, Intel(R) Xeon(R) CPU E5-2660 v3 @ 2.60GHz (haswell), Python 2.7.5
See https://gist.github.com/427959a310e05395c087d36583110bbb for a full test report.

**Pull request merged**
