### PR TITLE
{tools}[GCCcore/9.3.0] Emacs v27.1

### PR DESCRIPTION
**Pull request by Micket**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by Micket** [comment]
Test report by @Micket
**SUCCESS**
Build succeeded for 12 out of 12 (1 easyconfigs in total)
hebbe-c1 - Linux centos linux 7.9.2009, x86_64, Intel Core Processor (Haswell, no TSX), Python 2.7.5
See https://gist.github.com/da8bdddf79b66e3050164eb433006228 for a full test report.

**Comment by Micket** [comment]
@boegelbot please test @ generoso

**Review by branfosj — APPROVED** [review]
lgtm

**Comment by branfosj** [comment]
Test report by @branfosj
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
bear-pg0211u03a.bear.cluster - Linux centos linux 7.8.2003, x86_64, Intel(R) Xeon(R) Gold 6248 CPU @ 2.50GHz (cascadelake), Python 3.6.8
See https://gist.github.com/677953fccec778ebe0bba97492d70856 for a full test report.

**Comment by branfosj** [comment]
Test report by @branfosj
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
bear-pg0306u19a - Linux RHEL 8.2, POWER, 8335-GTX (power9le), Python 3.6.8
See https://gist.github.com/6ed7ae4ba8a7790fbf30e80f6b761d26 for a full test report.

**Comment by branfosj** [comment]
Going in, thanks @Micket!

**Pull request merged**
