### PR TITLE
{data}[foss/2019b] h5py v2.10.0 w/ Python 3.7.4 (serial)

### PR DESCRIPTION
**Pull request by Micket**
(created using `eb --new-pr`)

- [x] #12829

### CODE REVIEW

**Comment by SebastianAchilles** [comment]
@boegelbot please test @ generoso

**Review by SebastianAchilles — APPROVED** [review]
lgtm

**Comment by SebastianAchilles** [comment]
Test report by @sebastianachilles
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
rocky8-eb - Linux rocky linux 8.4, x86_64, Intel(R) Core(TM) i7-6900K CPU @ 3.20GHz (broadwell), Python 3.6.8
See https://gist.github.com/c81a1dd5eaf7895416e17f608239f4ca for a full test report.

**Review by SebastianAchilles — CHANGES_REQUESTED** [review]
To fix the failing test an exception should be added for `HDF5` with versionsuffix `-serial` in `test/easyconfigs/easyconfigs.py`

**Comment by SebastianAchilles** [comment]
> To fix the failing test an exception should be added for `HDF5` with versionsuffix `-serial` in `test/easyconfigs/easyconfigs.py`

See https://github.com/Micket/easybuild-easyconfigs/pull/6

**Comment by Micket** [comment]
Thanks!

**Review by SebastianAchilles — APPROVED** [review]
lgtm

**Comment by SebastianAchilles** [comment]
Test report by @sebastianachilles
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
rocky8-eb - Linux rocky linux 8.4, x86_64, Intel(R) Core(TM) i7-6900K CPU @ 3.20GHz (broadwell), Python 3.6.8
See https://gist.github.com/4905ac5d2466cd43caaf5e2a1c3c06d9 for a full test report.

**Comment by SebastianAchilles** [comment]
Going in, thanks @Micket!

**Pull request merged**
