### PR TITLE
{lang}[system/system] Julia v1.6.4

### PR DESCRIPTION
**Pull request by hellemo**

### CODE REVIEW

**Comment by bedroge** [comment]
@boegelbot please test @ generoso

**Comment by bedroge** [comment]
Test report by @bedroge
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
bob-Latitude-5300 - Linux Ubuntu 20.04, x86_64, Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz, Python 3.8.10
See https://gist.github.com/8b6e48b2819c273be7b1cb8738a7d6c7 for a full test report.

**Comment by bedroge** [comment]
Test report by @bedroge
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
pg-node165 - Linux centos linux 7.9.2009, x86_64, Intel(R) Xeon(R) CPU E5-2680 v4 @ 2.40GHz, Python 3.6.8
See https://gist.github.com/ca95f574af14b4afd5d6603b52522f9f for a full test report.

**Comment by bedroge** [comment]
@boegelbot please test @ generoso

**Comment by bedroge** [comment]
Test report by @bedroge
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
bob-Latitude-5300 - Linux Ubuntu 20.04, x86_64, Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz, Python 3.8.10
See https://gist.github.com/908d47748856041b17add989aaa89a36 for a full test report.

**Comment by bedroge** [comment]
Test report by @bedroge
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
pg-node165 - Linux centos linux 7.9.2009, x86_64, Intel(R) Xeon(R) CPU E5-2680 v4 @ 2.40GHz, Python 3.6.8
See https://gist.github.com/983989df87aa151279a12e6cd1b8c63c for a full test report.

**Review by bedroge — APPROVED** [review]
@hellemo thanks for your first contribution! I've changed the title of the pull request a bit so that it complies with what we usually use. Note that by using Easybuild's Github integration things like this will be done automatically, so it may be worth checking this out for future pull requests, as it may make contributing even easier:
https://docs.easybuild.io/en/latest/Integration_with_GitHub.html
https://docs.easybuild.io/en/latest/Contributing.html

I've also made a tiny change to the easyconfig by adding a `sanity_check_commands`, which we now try to do for new contributions. This is a list that can contain one or more simple checks to make sure that the installed executable works properly, so often we use something like `--help` or `--version`.

**Comment by bedroge** [comment]
Going in, thanks @hellemo!

**Comment by hellemo** [comment]
@bedroge Thanks! I'll keep the title formatting in mind for next time. 1.7 should be out soon.

**Pull request merged**
