### PR TITLE
Fix gmsh 4.9.0 lib and python bindings

### PR DESCRIPTION
**Pull request by Micket**
(created using `eb --new-pr`)

### CODE REVIEW

**Review by branfosj — DISMISSED** [review]
lgtm

**Comment by branfosj** [comment]
@boegelbot please test @ jsc-zen2

**Comment by branfosj** [comment]
Test report by @branfosj
**FAILED**
Build succeeded for 0 out of 1 (1 easyconfigs in total)
bear-pg0211u03a.bear.cluster - Linux RHEL 8.6, x86_64, Intel(R) Xeon(R) Gold 6248 CPU @ 2.50GHz (cascadelake), Python 3.6.8
See https://gist.github.com/7c5e7bc553318f60c4742b7f0242e85a for a full test report.

**Comment by branfosj** [comment]
Ah, my failure was caused by old options in `~/.gmsh-options` - see https://gitlab.onelab.info/gmsh/gmsh/-/issues/1048

**Comment by branfosj** [comment]
Test report by @branfosj
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
bear-pg0211u03a.bear.cluster - Linux RHEL 8.6, x86_64, Intel(R) Xeon(R) Gold 6248 CPU @ 2.50GHz (cascadelake), Python 3.6.8
See https://gist.github.com/78f1e9f0f0e0c68908c0e1dd68f40806 for a full test report.

**Review by branfosj — APPROVED** [review]
lgtm

**Comment by Micket** [comment]
Test report by @Micket
**SUCCESS**
Build succeeded for 19 out of 19 (1 easyconfigs in total)
alvis-c1 - Linux Rocky Linux 8.5, x86_64, Intel Xeon Processor (Skylake), Python 3.6.8
See https://gist.github.com/3d5037977df4dd35b5f91672bd85f8f3 for a full test report.

**Pull request merged**
