### PR TITLE
{bio}[GCC/8.3.0,foss/2018b] GenomeTools v1.5.10, GenomeTools v1.6.1 w/ Python 2.7.15 + 2.7.16

### PR DESCRIPTION
**Pull request by lexming**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by lexming** [comment]
Test report by @lexming
**SUCCESS**
Build succeeded for 4 out of 4 (4 easyconfigs in this PR)
login2.cerberus.os - Linux centos linux 7.7.1908, Intel(R) Xeon(R) Gold 6126 CPU @ 2.60GHz, Python 2.7.5
See https://gist.github.com/b23113206bae6468afd3b0709ff061e2 for a full test report.

**Comment by verdurin** [comment]
Test report by @verdurin
**SUCCESS**
Build succeeded for 4 out of 4 (4 easyconfigs in this PR)
generoso - Linux centos linux 7.6.1810, Intel(R) Xeon(R) CPU E5-2660 v4 @ 2.00GHz, Python 3.6.8
See https://gist.github.com/ea65005ac72a2d7b299c93c4d09afd52 for a full test report.

**Comment by verdurin** [comment]
@lexming Any specific reason why you need so many different types?

Not that it's a problem, just curious.

**Comment by lexming** [comment]
@verdurin it is not clear to me what you mean by _different types_. Could you clarify it?

**Comment by verdurin** [comment]
@lexming Didn't express myself well. Just thought it odd that you would need two different versions of the application for two different versions of Python.

**Comment by lexming** [comment]
@verdurin Ah ok, the story is that we've had `GenomeTools-1.5.10` for quite some time in `foss/2018b` but for reasons I never pushed it to the repository. Recently we updated it to version 1.6.1 in `foss/2019b` and as a result, I am now PRing both versions as they might be useful for others.

**Comment by verdurin** [comment]
Going in, thanks @lexming!

**Pull request merged**
