### PR TITLE
{bio}[intel/2019a] Red v2015-05-22

### PR DESCRIPTION
**Pull request by bjmoran**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by bjmoran** [comment]
@boegel I've added a commit with your requested changes. Thanks for your review!

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
generoso - Linux centos linux 7.6.1810, Intel(R) Xeon(R) CPU E5-2660 v4 @ 2.00GHz, Python 3.6.8
See https://gist.github.com/c2d8387b8eeb65291eb7363de4089279 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
gligar05.gastly.os - Linux centos linux 7.7.1908, Intel(R) Xeon(R) Gold 6130 CPU @ 2.10GHz, Python 2.7.5
See https://gist.github.com/e90aa7c69a72eb7f5ddb7aac2f3fcbfd for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
node2417.golett.os - Linux centos linux 7.7.1908, Intel(R) Xeon(R) CPU E5-2680 v3 @ 2.50GHz, Python 2.7.5
See https://gist.github.com/ec8604a270cafbedf62c28285dd9a094 for a full test report.

**Comment by boegel** [comment]
Going in, thanks @bjmoran!

**Pull request merged**
