### PR TITLE
{math}[system/system] MCR vR2020b

### PR DESCRIPTION
**Pull request by verdurin**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by verdurin** [comment]
This is affected by https://github.com/easybuilders/easybuild-framework/issues/3455 owing to the large source archive.

**Review by branfosj — APPROVED** [review]
lgtm

**Comment by branfosj** [comment]
Test report by @branfosj
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
bber0501u03a.bb2.cluster - Linux centos linux 7.8.2003, x86_64, Intel(R) Xeon(R) CPU E5-2690 v3 @ 2.60GHz (haswell), Python 3.6.8
See https://gist.github.com/8c8f7a47f0aa65bcdd5485f22fb83b36 for a full test report.

**Comment by branfosj** [comment]
> This is affected by [easybuilders/easybuild-framework#3455](https://github.com/easybuilders/easybuild-framework/issues/3455) owing to the large source archive.

I'll go ahead and merge this and #12332 as it is possible to download the sources outside of EB and it works fine once you have them. We have the framework issue for fixing the underlying problem.

**Comment by branfosj** [comment]
Going in, thanks @verdurin!

**Pull request merged**
