### PR TITLE
{perf}[gompi/2022a,gompi/2022b,gompi/2023a] CubeLib v4.8.2, CubeWriter v4.8.2, Score-P v8.3 w/ CUDA 11.7.0, CUDA 12.0.0, ...

### PR DESCRIPTION
**Pull request by Flamefire**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by Flamefire** [comment]
Test report by @Flamefire
**SUCCESS**
Build succeeded for 16 out of 16 (9 easyconfigs in total)
i8034 - Linux Rocky Linux 8.7, x86_64, AMD EPYC 7352 24-Core Processor (zen2), 8 x NVIDIA NVIDIA A100-SXM4-40GB, 545.23.08, Python 3.6.8
See https://gist.github.com/Flamefire/0244f4c3cf6ec117e79ed2964773b348 for a full test report.

**Comment by satishskamath** [comment]
@Flamefire PAPI-7.1.0 was released in December 2023. Shall I upgrade the dependencies which include PAPI in this PR?

**Comment by Flamefire** [comment]
> @Flamefire PAPI-7.1.0 was released in December 2023. Shall I upgrade the dependencies which include PAPI in this PR?

This PR doesn't add PAPI so we already have a PAPI in the ECs. Adding another version isn't a good idea unless there is a really pressing reason to make an exception. Also I found some issues with PAPI 7.1 at least in the tests: https://github.com/icl-utk-edu/papi/issues/160

**Comment by satishskamath** [comment]
@Flamefire I recently created a PR for PAPI 7.1.0 and have pasted the issue there. We required it because it also introduces support for `zen4`. Therefore creating the PRs. Should that wait then?

**Comment by Flamefire** [comment]
Test report by @Flamefire
**SUCCESS**
Build succeeded for 9 out of 9 (9 easyconfigs in total)
n1227 - Linux RHEL 8.7 (Ootpa), x86_64, Intel(R) Xeon(R) Platinum 8470 (icelake), Python 3.8.13
See https://gist.github.com/Flamefire/04cd0c3b98f01a69e6e6e9c156254f9a for a full test report.

**Comment by Flamefire** [comment]
> @Flamefire I recently created a PR for PAPI 7.1.0 and have pasted the issue there. We required it because it also introduces support for `zen4`. Therefore creating the PRs. Should that wait then?

I just noticed that while I updated Score-P here to 8.4 as requested by @Thyre in #20146 I didn't change the PAPI version used and simply used the existing 7.0.x versions. as per [the reasoning](https://github.com/easybuilders/easybuild-easyconfigs/pull/20081#issuecomment-1991669973) of @casparvl we might want to use PAPI 7.1 here too introducing a second version into those toolchains, but we already needed to add additional versions of the Cube* ECs (required newer versions by Score-P)

**Comment by Flamefire** [comment]
Test report by @Flamefire
**SUCCESS**
Build succeeded for 9 out of 9 (9 easyconfigs in total)
i8001 - Linux Rocky Linux 8.7 (Green Obsidian), x86_64, AMD EPYC 7352 24-Core Processor (zen2), 8 x NVIDIA NVIDIA A100-SXM4-40GB, 545.23.08, Python 3.8.13
See https://gist.github.com/Flamefire/52045eabdc6ba5c9a9b0c75b854829b1 for a full test report.

**Comment by casparvl** [comment]
Ok, I'm a bit confused now with all the version discussion :D 

> as per https://github.com/easybuilders/easybuild-easyconfigs/pull/20081#issuecomment-1991669973 of @casparvl we might want to use PAPI 7.1 here too introducing a second version into those toolchains, but we already needed to add additional versions of the Cube* ECs (required newer versions by Score-P)

Do you mean here that your intention is to get this PR merged _and_ have another PR with newer PAPI 7.1? Or do you plan to bump the PAPI version used _in this PR_ and make a second PR?

**Comment by Flamefire** [comment]
> Do you mean here that your intention is to get this PR merged _and_ have another PR with newer PAPI 7.1? Or do you plan to bump the PAPI version used _in this PR_ and make a second PR?

So basically: Some people need PAPI 7.1. This adds ECs using existing PAPI 7.0 but at the same time adds a 2nd version of another dependency (Cube*)   

So we can either keep this as-is or add PAPI 7.1 to the toolchains used here and update this PR to use PAPI 7.1 instead of 7.0 as dependencies.

So yes: Another PR with PAPI 7.1 and the bump PAPI in this PR before it gets merged.   
Or do nothing and merge as-is.

**Comment by Flamefire** [comment]
@casparvl To get this resolved I updated the used PAPI versions here to 7.1. While we IIRC already have another version in some toolchains Score-P is the only EC using it from our side. So IMO this is the best option

**Comment by Flamefire** [comment]
Test report by @Flamefire
**SUCCESS**
Build succeeded for 12 out of 12 (12 easyconfigs in total)
login3 - Linux RHEL 8.9 (Ootpa), x86_64, Intel(R) Xeon(R) Platinum 8470 (icelake), Python 3.8.17
See https://gist.github.com/Flamefire/f6d1f48c7a5e911840b69e160b1dbb56 for a full test report.

**Comment by Flamefire** [comment]
[CI](https://github.com/easybuilders/easybuild-easyconfigs/actions/runs/11142554991/job/30965766988?pr=19524) doesn't like when I use PAPI 7.1.0 for 2022a, 2022b or 2023a.

So either we add an exception to the CI similar to the Cube* one or accept that zen4 won't be supported until 2023b

**Comment by Flamefire** [comment]
Test report by @Flamefire
**SUCCESS**
Build succeeded for 10 out of 10 (10 easyconfigs in total)
login3 - Linux RHEL 8.9 (Ootpa), x86_64, Intel(R) Xeon(R) Platinum 8470 (icelake), Python 3.8.17
See https://gist.github.com/Flamefire/11cf7d5ad5baf2a3962ffc36388b7c4d for a full test report.

**Comment by Flamefire** [comment]
Test report by @Flamefire
**SUCCESS**
Build succeeded for 12 out of 12 (10 easyconfigs in total)
i7157 - Linux Rocky Linux 8.9 (Green Obsidian), x86_64, AMD EPYC 7702 64-Core Processor (zen2), Python 3.8.17
See https://gist.github.com/Flamefire/857825a0ebd61ae73335fdf2e26b6286 for a full test report.

**Comment by Flamefire** [comment]
Test report by @Flamefire
**SUCCESS**
Build succeeded for 10 out of 10 (10 easyconfigs in total)
i7025 - Linux Rocky Linux 8.9 (Green Obsidian), x86_64, AMD EPYC 7702 64-Core Processor (zen2), Python 3.8.17
See https://gist.github.com/Flamefire/5f268ec1a6b4ab72e390c528f509b0ea for a full test report.

**Comment by Thyre** [comment]
The patch should not be necessary with https://github.com/easybuilders/easybuild-easyblocks/pull/3496 I think.

**Comment by Flamefire** [comment]
> The patch should not be necessary with [easybuilders/easybuild-easyblocks#3496](https://github.com/easybuilders/easybuild-easyblocks/pull/3496) I think.

You are right. I reverted that commit so if anyone runs into the error

> configure: error: Both, --with-libbfd-lib and --with-libbfd-include require a <path>.

might be able to find it.

@bedroge Can you take a look at this PR?

**Comment by Thyre** [comment]
> > The patch should not be necessary with [easybuilders/easybuild-easyblocks#3496](https://github.com/easybuilders/easybuild-easyblocks/pull/3496) I think.
> 
> You are right. I reverted that commit so if anyone runs into the error

I agree. However, looking at the initial patch again, there was also a tiny mistake, that may cause unintended side-effects

```diff
diff -ur scorep-8.0-orig/build-backend/configure scorep-8.0/build-backend/configure
--- scorep-8.0-orig/build-backend/configure	2024-11-28 13:53:42.539876288 +0100
+++ scorep-8.0/build-backend/configure	2024-11-28 13:58:04.917444170 +0100
@@ -37776,7 +37776,7 @@
 esac ;; #(
       set2set3) :
     case ${with_libbfd_lib}${with_libbfd_include} in #(
-  *yes*|*no*) :
+  yes,*|no,*|*,yes|*,no) :
     as_fn_error $? "Both, --with-libbfd-lib and --with-libbfd-include require a <path>." "$LINENO" 5 ;; #(
   *) :
```

The `case` is not entirely correct and should be:
```diff
-case ${with_libbfd_lib}${with_libbfd_include} in #(
+case ${with_libbfd_lib},${with_libbfd_include} in #(
```
Same for the others. We came across the same issue in the EasyBlock PR: https://github.com/easybuilders/easybuild-easyblocks/pull/3496#issuecomment-2443990924. But to be honest, such tiny things are hard to spot 😄

**Comment by Flamefire** [comment]
> I agree. However, looking at the initial patch again, there was also a tiny mistake, that may cause unintended side-effects

Well the intention of the patch was to NOT match the case anymore. The (faulty) patch achieves that ;-) It just never matches now.
I guess it is still save because we always pass both options from the easyblock so it should be practically impossible that the correct case would match.

But Bert just notified me of the same when I copied this patch to our internal repo which doesn't have the easyblock fix yet. I corrected it there but as the patch is removed here I think it doesn't make sense to update it again.

**Comment by bedroge** [comment]
@boegelbot please test @ generoso
CORE_CNT=16

**Comment by bedroge** [comment]
Test report by @bedroge
**SUCCESS**
Build succeeded for 10 out of 10 (10 easyconfigs in total)
node22 - Linux Rocky Linux 8.10, x86_64, AMD EPYC 7763 64-Core Processor (zen3), Python 3.6.8
See https://gist.github.com/bedroge/3f71b301faf496568628836c6ee23a1a for a full test report.

**Review by bedroge — APPROVED** [review]
Looks good to me.

**Pull request merged**
