### PR TITLE
{lib}[GCCcore/8.3.0] ICU v65.1

### PR DESCRIPTION
**Pull request by furstj**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by verdurin** [comment]
Test report by @verdurin
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
generoso - Linux centos linux 7.6.1810, Intel(R) Xeon(R) CPU E5-2660 v4 @ 2.00GHz, Python 3.6.8
See https://gist.github.com/4299c30b6a91c97138b575f02d5a7f19 for a full test report.

**Comment by verdurin** [comment]
@furstj Please submit a test build.

**Comment by furstj** [comment]
Test report by @furstj
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
pc-12101-fuji - Linux UNKNOWN UNKNOWN, Intel(R) Xeon(R) CPU E3-1241 v3 @ 3.50GHz, Python 3.6.9
See https://gist.github.com/3cf71f99181954236bd3ccd6ea96673a for a full test report.

**Comment by verdurin** [comment]
Going in, thanks @furstj!

**Pull request merged**
