### PR TITLE
use OpenSSL wrapper as dependency in easyconfigs using GCCcore/10.3.0 toolchain

### LINKED ISSUE #11895: Use wrappers for OpenSSL starting 2021a
As discussed on biweekly meetings, i figured it would be good to make a ticket for it:

Instead of relying on OS, which is getting more and more painful on older OS'es, we should just build OpenSSL (and friends) in EB and keep updating them. This of course requires wrappers, like we do for Java. So, I would expect there to something like a `OpenSSL-1.1.1x-GCCcore-11.a.b.eb` + `OpenSSL-1.1-GCCcore-11.a.b.eb`-wrapper starting with with the 2021 toolchains.

For those wishing to keep osdependency they can filter OpenSSL. We should also make sure to enhance the PR-testsuite so that we don't miss switching over as we bump new easyconfigs to 2021a.

(We might also want to do so for stuff like `gnutls.`, but I suspect osdep works well there still.)

### PR DESCRIPTION
**Pull request by boegel**
(created using `eb --new-pr`)
requires ~~#12858~~ (OpenSSL wrappers)
fixes #11895

### CODE REVIEW

**Comment by boegel** [comment]
@boegelbot please test @ generoso
CORE_CNT=16

**Comment by boegel** [comment]
Test report by @boegel
**FAILED**
Build succeeded for 6 out of 8 (8 easyconfigs in total)
node2618.swalot.os - Linux centos linux 7.9.2009, x86_64, Intel(R) Xeon(R) CPU E5-2660 v3 @ 2.60GHz (haswell), Python 3.6.8
See https://gist.github.com/c835cff8d63bf2c9a5a4ecc4d83dff37 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 8 out of 8 (8 easyconfigs in total)
node3552.doduo.os - Linux RHEL 8.2, x86_64, AMD EPYC 7552 48-Core Processor (zen2), Python 3.6.8
See https://gist.github.com/6fe5351f8f91fb180e018c87d9c5d8f6 for a full test report.

**Comment by boegel** [comment]
Hmm, the `Net::SSLeay` extension in Perl isn't happy with a wrapper `openssl11` on CentOS 7:

```
perl: symbol lookup error: /software/Perl/5.32.1-GCCcore-10.3.0/lib/perl5/site_perl/5.32.1/x86_64-linux-thread-multi/auto/Net/SSLeay/SSLeay.so:
undefined symbol: OpenSSL_version_num
```

**Comment by boegel** [comment]
@boegelbot please test @ generoso
CORE_CNT=16

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 8 out of 8 (8 easyconfigs in total)
node2618.swalot.os - Linux centos linux 7.9.2009, x86_64, Intel(R) Xeon(R) CPU E5-2660 v3 @ 2.60GHz (haswell), Python 3.6.8
See https://gist.github.com/06cf072e76bda04d70eb5da11cfba830 for a full test report.

**Comment by lexming** [comment]
Test report by @lexming
**SUCCESS**
Build succeeded for 10 out of 10 (8 easyconfigs in total)
node381.hydra.os - Linux centos linux 7.9.2009, x86_64, Intel(R) Xeon(R) Gold 6148 CPU @ 2.40GHz, Python 2.7.5
See https://gist.github.com/e3c88ee1f04e6b6d25ada04bb07aa263 for a full test report.

**Review by lexming — APPROVED** [review]
LGTM

**Comment by lexming** [comment]
Going in, thanks @boegel !

**Pull request merged**
