### PR TITLE
{devel,lib}[GCCcore/10.3.0] wxPython v4.1.1, WebKitGTK+ v2.27.4, GConf v3.2.6, ... w/ Python 3.9.5

### PR DESCRIPTION
**Pull request by orbsmiv**
* [x] https://github.com/easybuilders/easybuild-easyblocks/pull/2689

(created using `eb --new-pr`)

### CODE REVIEW

**Comment by boegel** [comment]
@boegelbot please test @ generoso

**Comment by sassy-crick** [comment]
Test report by @sassy-crick
**SUCCESS**
Build succeeded for 5 out of 5 (5 easyconfigs in total)
hp - Linux Debian GNU/Linux 11, x86_64, 11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz, Python 3.9.2
See https://gist.github.com/bd94b7e28f016fbd5f728dc7d4f8ade4 for a full test report.

**Review by boegel — APPROVED** [review]
lgtm

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 19 out of 19 (5 easyconfigs in total)
node3127.skitty.os - Linux RHEL 8.4, x86_64, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz (skylake_avx512), Python 3.6.8
See https://gist.github.com/291ab3ee08b8badcc7871390df767615 for a full test report.

**Comment by boegel** [comment]
Going in, thanks @orbsmiv!

**Pull request merged**
