### PR TITLE
WIP: {devel}[foss/2020a] PyTorch v1.4.0 w/ Python 3.8.2

### PR DESCRIPTION
**Pull request by branfosj**
(created using `eb --new-pr`)

Requires:
* [x] PyYAML (#10138)
* [x] Pillow (#10137)

This is very much a WIP, since it:
* fails to build on cascadelake
* fails in the tests on everything else

I've generated test reports to allow me to debug.

### CODE REVIEW

**Comment by branfosj** [comment]
Test report by @branfosj
**FAILED**
Build succeeded for 0 out of 1 (1 easyconfigs in this PR)
bear-pg0211u03a.bear.cluster - Linux centos linux 7.7.1908, Intel(R) Xeon(R) Gold 6248 CPU @ 2.50GHz, Python 2.7.5
See https://gist.github.com/be7f8f79a5e6c2bd113b86c2f6577f3e for a full test report.

**Comment by branfosj** [comment]
Test report by @branfosj
**FAILED**
Build succeeded for 0 out of 1 (1 easyconfigs in this PR)
bear-pg0306u03a.bear.cluster - Linux RHEL 7.6, 8335-GTX, Python 2.7.5
See https://gist.github.com/c0eb43e94e79486bfb4e87323426380f for a full test report.

**Comment by zao** [comment]
Test report by @zao
**FAILED**
Build succeeded for 12 out of 13 (1 easyconfigs in this PR)
freja - Linux ubuntu 18.04, Intel(R) Core(TM) i7-8700K CPU @ 3.70GHz, Python 2.7.17
See https://gist.github.com/eb71991086c3caef685472a53e1c6310 for a full test report.

**Comment by branfosj** [comment]
> Test report by @branfosj
> **FAILED**
> Build succeeded for 0 out of 1 (1 easyconfigs in this PR)
> bear-pg0211u03a.bear.cluster - Linux centos linux 7.7.1908, Intel(R) Xeon(R) Gold 6248 CPU @ 2.50GHz, Python 2.7.5
> See https://gist.github.com/be7f8f79a5e6c2bd113b86c2f6577f3e for a full test report.

The CascadeLake build failure is in FBGEMM. The build does not fail if we set `toolchainopts = {'optarch': False}`, so we are back in the `-march=native` causing issues.

(Note that this gets the build part to complete on CascadeLake - we fail in the tests in the same place that all the others were failing.)

**Comment by branfosj** [comment]
PyTorch 1.5 has been released (https://github.com/pytorch/pytorch/releases/tag/v1.5.0). I'll close this off as we should go with that in the 2020a branch.

**Pull request closed without merging**
