### PR TITLE
{devel}[foss/2018a] Boost v1.63.0

### PR DESCRIPTION
**Pull request by smoors**
(created using `eb --new-pr`)
depends on easyblock PR #1434

### CODE REVIEW

**Comment by verdurin** [comment]
This is the easyblock PR link https://github.com/easybuilders/easybuild-easyblocks/pull/1434

**Comment by verdurin** [comment]
Test report by @verdurin
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
easybuild.novalocal - Linux centos linux 7.5.1804, Intel Xeon E312xx (Sandy Bridge), Python 2.7.5
See https://gist.github.com/75c368887b4d08a03987d65add9c5d33 for a full test report.

**Comment by verdurin** [comment]
Going in, thanks @smoors!

**Comment by verdurin** [comment]
Actually, this does depend on the easyblock being merged...

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
node3100.skitty.os - Linux centos linux 7.4.1708, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz, Python 2.7.5
See https://gist.github.com/d2d55ad55cfbcd016dfcbd72ad497ae2 for a full test report.

**Comment by boegel** [comment]
@verdurin https://github.com/easybuilders/easybuild-easyblocks/pull/1434 is merged too now

**Pull request merged**
