### PR TITLE
Pillow-SIMD: respect sysroot when in use

### PR DESCRIPTION
**Pull request by ocaisa**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by ocaisa** [comment]
@boegelbot please test @ generoso

**Comment by ocaisa** [comment]
@boegelbot please test @ jsc-zen3

**Comment by jfgrimm** [comment]
Test report by @jfgrimm
**SUCCESS**
Build succeeded for 7 out of 7 (6 easyconfigs in total)
node091.viking2.yor.alces.network - Linux Rocky Linux 8.8, x86_64, AMD EPYC 7643 48-Core Processor, Python 3.6.8
See https://gist.github.com/jfgrimm/8c4664b54cf4a417365db6f4e4b9ce43 for a full test report.

**Review by jfgrimm — APPROVED** [review]
lgtm
will wait for the bot reports to come in before merging

**Comment by jfgrimm** [comment]
Going in, thanks @ocaisa!

**Pull request merged**
