### PR TITLE
{ai}[foss/2023a] PyTorch-bundle v2.1.2

### PR DESCRIPTION
**Pull request by boegel**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by smoors** [comment]
@boegelbot: please test @ generoso

**Comment by boegel** [comment]
@boegelbot please test @ jsc-zen3

**Comment by boegel** [comment]
@boegelbot: please test @ generoso
CORE_CNT=16

**Comment by boegel** [comment]
Hmm, one test fails on `generoso` (vs 48832 passed...), not sure why...
```
=================================== FAILURES ===================================
__________________ TestResize.test_antialias_default_warning ___________________
test/test_transforms_tensor.py:438: in test_antialias_default_warning
    with pytest.warns(UserWarning, match=match):
E   Failed: DID NOT WARN. No warnings of type (<class 'UserWarning'>,) were emitted.
E   The list of emitted warnings is: [].
```

Looks like a broken test to me, since I see this in the output:

```
  /tmp/eb-3_zwy1_s/tmp8axcge9z/lib/python3.11/site-packages/torchvision/transforms/functional.py:1603: UserWarning: The default value of the antialias parameter of all the resizing transforms (Resize(), RandomResizedCrop(), etc.) will change from None to True in v0.17, in order to be consistent across the PIL and Tensor backends. To suppress this warning, directly pass antialias=True (recommended, future default), antialias=None (current default, which means False for Tensors and True for PIL), or antialias=False (only works on Tensors - PIL will still use antialiasing). This also applies if you are using the inference transforms from the models weights: update the call to weights.transforms(antialias=True).
    warnings.warn(
```

That seems to match what the test is checking for (see also https://github.com/pytorch/vision/pull/7160 where this test was added)

**Comment by boegel** [comment]
@boegelbot please test @ generoso
CORE_CNT=16

**Review by smoors — APPROVED** [review]
lgtm

**Comment by smoors** [comment]
Going in, thanks @boegel!

**Pull request merged**
