### PR TITLE
{lib}[GCCcore/10.3.0] ack v3.5.0, Archive-Zip v1.68, Blosc v1.21.0, ... w/ Python 3.9.5

### PR DESCRIPTION
**Pull request by Micket**
(created using `eb --new-pr`)
Just a bunch of leftover versionbumps i had. I didn't want to create a dozen PRs only bumping versions (if that)

### CODE REVIEW

**Comment by Micket** [comment]
@boegelbot please test @ generoso

**Comment by Micket** [comment]
Test report by @Micket
**SUCCESS**
Build succeeded for 15 out of 15 (15 easyconfigs in total)
alvis-c1 - Linux centos linux 7.9.2009, x86_64, Intel Xeon Processor (Skylake), Python 3.6.8
See https://gist.github.com/878c5024818c61ef2e3e1e981201547a for a full test report.

**Comment by verdurin** [comment]
Test report by @verdurin
**SUCCESS**
Build succeeded for 18 out of 18 (15 easyconfigs in total)
nuc.lan - Linux Fedora 33, x86_64, Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz, Python 3.9.5
See https://gist.github.com/79e92ef10597adff1ea71ce1aee02e73 for a full test report.

**Comment by verdurin** [comment]
Test report by @verdurin
**FAILED**
Build succeeded for 17 out of 18 (15 easyconfigs in total)
easybuild-c7.novalocal - Linux centos linux 7.9.2009, x86_64, Intel Xeon Processor (Skylake, IBRS), Python 3.6.8
See https://gist.github.com/3d27e0b0a24f608af4f2f32741608738 for a full test report.

**Comment by Micket** [comment]
@verdurin just a fluke maybe? 
```
== 2021-07-07 15:54:48,266 filetools.py:785 WARNING IOError occurred while trying to download https://pypi.python.org/packages/44/3e/4a45cb0738da6565f134c01d82ba291c746551b5bc82e781ec876eb20909/yacs-0.1.8.tar.gz to /eb/maint/sources/y/YACS/yacs-0.1.8.tar.gz: <urlopen error [Errno 101] Network is unreachable>
```
it works for me

**Comment by verdurin** [comment]
Test report by @verdurin
**SUCCESS**
Build succeeded for 1 out of 1 (15 easyconfigs in total)
easybuild-c7.novalocal - Linux centos linux 7.9.2009, x86_64, Intel Xeon Processor (Skylake, IBRS), Python 3.6.8
See https://gist.github.com/89544604248efdfa7270a60c6e707e33 for a full test report.

**Review by verdurin — APPROVED** [review]
Looks fine.

**Comment by verdurin** [comment]
Going in, thanks @Micket!

**Pull request merged**
