### PR TITLE
{tools}[system] archspec v0.1.0

### PR DESCRIPTION
**Pull request by boegel**
(created using `eb --new-pr`)

edit: requires #9859 (pip)

### CODE REVIEW

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
generoso - Linux centos linux 7.6.1810, Intel(R) Xeon(R) CPU E5-2660 v4 @ 2.00GHz, Python 3.6.8
See https://gist.github.com/5c53040778eb26bec99532fa47f3fb9c for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
w153h067.wireless.ugent.be - Darwin UNKNOWN UNKNOWN, Intel(R) Core(TM) i5-7360U CPU @ 2.30GHz, Python 2.7.16
See https://gist.github.com/a612bb68f93342e4dd2d2c4c4aaa77d7 for a full test report.

**Comment by verdurin** [comment]
Test report by @verdurin
**FAILED**
Build succeeded for 0 out of 1 (1 easyconfigs in this PR)
epyc000.hpc.in.bmrc.ox.ac.uk - Linux centos linux 7.6.1810, AMD EPYC 7502 32-Core Processor, Python 2.7.5
See https://gist.github.com/8ec678d652cc8306f0bd3f1f5b99cc6f for a full test report.

**Comment by verdurin** [comment]
```
== 2020-02-10 17:34:34,272 easyblock.py:2863 INFO Running method build_step part of step build
== 2020-02-10 17:34:34,272 run.py:200 DEBUG run_cmd: running cmd  /usr/bin/python setup.py build  (in /dev/shm/archspec/0.1.0/dummy-dummy/archspec-0.1.0)
== 2020-02-10 17:34:34,272 run.py:219 INFO running cmd:  /usr/bin/python setup.py build
== 2020-02-10 17:34:34,351 build_log.py:169 ERROR EasyBuild crashed with an error (at easybuild/base/exceptions.py:124 in __init__): cmd " /usr/bin/python setup.py build " exited with exit code 1 and output:
/usr/lib64/python2.7/distutils/dist.py:267: UserWarning: Unknown distribution option: 'python_requires'
  warnings.warn(msg)
running build
running build_py
creating build
creating build/lib
creating build/lib/archspec
copying archspec/__init__.py -> build/lib/archspec
creating build/lib/archspec/cpu
copying archspec/cpu/schema.py -> build/lib/archspec/cpu
copying archspec/cpu/microarchitecture.py -> build/lib/archspec/cpu
copying archspec/cpu/detect.py -> build/lib/archspec/cpu
copying archspec/cpu/alias.py -> build/lib/archspec/cpu
copying archspec/cpu/__init__.py -> build/lib/archspec/cpu
error: can't copy 'archspec/json': doesn't exist or not a regular file
 (at easybuild/tools/run.py:529 in parse_cmd_output)
== 2020-02-10 17:34:34,351 easyblock.py:3109 WARNING build failed (first 300 chars): cmd " /usr/bin/python setup.py build " exited with exit code 1 and output:
/usr/lib64/python2.7/distutils/dist.py:267: UserWarning: Unknown distribution option: 'python_requires'
  warnings.warn(msg)
running build
running build_py
creating build
creating build/lib
creating build/lib/archspec
copying
== 2020-02-10 17:34:34,351 easyblock.py:295 INFO Closing log for application name archspec version 0.1.0
```

**Comment by boegel** [comment]
@verdurin Which `setuptools` version is that?

**Comment by boegel** [comment]
@alalazo Any idea what the issue is in @verdurin's test report?

The `archspec` source tarball from PyPI includes the JSON file, right?

**Comment by verdurin** [comment]
@boegel `python-setuptools-0.9.8-7.el7.noarch`

**Comment by alalazo** [comment]
@verdurin @boegel Are you trying to build from source distribution with setuptools?

**Comment by verdurin** [comment]
Test report by @verdurin
**FAILED**
Build succeeded for 0 out of 1 (1 easyconfigs in this PR)
epyc000.hpc.in.bmrc.ox.ac.uk - Linux centos linux 7.6.1810, AMD EPYC 7502 32-Core Processor, Python 2.7.5
See https://gist.github.com/48f33acd07c629dd18671965b4a0d392 for a full test report.

**Comment by migueldiascosta** [comment]
Test report by @migueldiascosta
**FAILED**
Build succeeded for 0 out of 1 (1 easyconfigs in this PR)
sms - Linux centos linux 7.6.1810, AMD EPYC 7601 32-Core Processor, Python 2.7.5
See https://gist.github.com/faef182b9ec1ef05780abf6850db7444 for a full test report.

**Comment by boegel** [comment]
> @verdurin @boegel Are you trying to build from source distribution with setuptools?

Yes. Is that a no-go? Do we need to enforce the use of `pip`?

**Comment by alalazo** [comment]
> Yes. Is that a no-go? Do we need to enforce the use of pip?

`archspec` doesn't use `setuptools` (i.e. it has no `setup.py`) it uses poetry and `pyproject.toml` to install from the source distribution. Otherwise there are binary wheels available.

**Comment by boegel** [comment]
@alalazo I wonder if that's a good approach, since installing from source when only `pyproject.toml` is there seems to be problematic.

I'm hitting this issue with latest `pip` (and I'm not the only one, it seems, see other projects that tried going `pyproject.toml` only...):

```
$ pip install --prefix=/Users/kehoste/software/archspec/0.1.0  --no-deps  --ignore-installed  --no-build-isolation  .
...
Traceback (most recent call last):
  File "/Users/kehoste/software/pip/20.0.2/lib/python2.7/site-packages/pip-20.0.2-py2.7.egg/pip/_internal/cli/base_command.py", line 186, in _main
    status = self.run(options, args)
  File "/Users/kehoste/software/pip/20.0.2/lib/python2.7/site-packages/pip-20.0.2-py2.7.egg/pip/_internal/commands/install.py", line 331, in run
    resolver.resolve(requirement_set)
  File "/Users/kehoste/software/pip/20.0.2/lib/python2.7/site-packages/pip-20.0.2-py2.7.egg/pip/_internal/legacy_resolve.py", line 177, in resolve
    discovered_reqs.extend(self._resolve_one(requirement_set, req))
  File "/Users/kehoste/software/pip/20.0.2/lib/python2.7/site-packages/pip-20.0.2-py2.7.egg/pip/_internal/legacy_resolve.py", line 333, in _resolve_one
    abstract_dist = self._get_abstract_dist_for(req_to_install)
  File "/Users/kehoste/software/pip/20.0.2/lib/python2.7/site-packages/pip-20.0.2-py2.7.egg/pip/_internal/legacy_resolve.py", line 282, in _get_abstract_dist_for
    abstract_dist = self.preparer.prepare_linked_requirement(req)
  File "/Users/kehoste/software/pip/20.0.2/lib/python2.7/site-packages/pip-20.0.2-py2.7.egg/pip/_internal/operations/prepare.py", line 516, in prepare_linked_requirement
    req, self.req_tracker, self.finder, self.build_isolation,
  File "/Users/kehoste/software/pip/20.0.2/lib/python2.7/site-packages/pip-20.0.2-py2.7.egg/pip/_internal/operations/prepare.py", line 95, in _get_prepared_distribution
    abstract_dist.prepare_distribution_metadata(finder, build_isolation)
  File "/Users/kehoste/software/pip/20.0.2/lib/python2.7/site-packages/pip-20.0.2-py2.7.egg/pip/_internal/distributions/sdist.py", line 40, in prepare_distribution_metadata
    self.req.prepare_metadata()
  File "/Users/kehoste/software/pip/20.0.2/lib/python2.7/site-packages/pip-20.0.2-py2.7.egg/pip/_internal/req/req_install.py", line 564, in prepare_metadata
    self.metadata_directory = self._generate_metadata()
  File "/Users/kehoste/software/pip/20.0.2/lib/python2.7/site-packages/pip-20.0.2-py2.7.egg/pip/_internal/req/req_install.py", line 551, in _generate_metadata
    backend=self.pep517_backend,
  File "/Users/kehoste/software/pip/20.0.2/lib/python2.7/site-packages/pip-20.0.2-py2.7.egg/pip/_internal/operations/build/metadata.py", line 37, in generate_metadata
    metadata_dir
  File "/Users/kehoste/software/pip/20.0.2/lib/python2.7/site-packages/pip-20.0.2-py2.7.egg/pip/_vendor/pep517/wrappers.py", line 170, in prepare_metadata_for_build_wheel
    '_allow_fallback': _allow_fallback,
  File "/Users/kehoste/software/pip/20.0.2/lib/python2.7/site-packages/pip-20.0.2-py2.7.egg/pip/_vendor/pep517/wrappers.py", line 255, in _call_hook
    raise BackendUnavailable(data.get('traceback', ''))
BackendUnavailable
```

**Comment by Flamefire** [comment]
>  raise BackendUnavailable(data.get('traceback', ''))

Is it possible that this is simply the new way of saying: Install what is required? archspec requires poetry as the "backend": https://github.com/archspec/archspec/blob/6fbf84f01137584f47f817457cd3187bf67eb8ef/pyproject.toml#L58-L59

Have you tried installing that first?

**Comment by alalazo** [comment]
@Flamefire That's exactly what I meant by:

> it uses poetry and pyproject.toml to install from the source distribution

Just tried downloading the sdist from PyPI and installing them in a new virtualenv based on Python 3.7:
```console
$ tree archspec-0.1.0
archspec-0.1.0
├── archspec
│   ├── cpu
│   │   ├── alias.py
│   │   ├── detect.py
│   │   ├── __init__.py
│   │   ├── microarchitecture.py
│   │   └── schema.py
│   ├── __init__.py
│   └── json
│       ├── COPYRIGHT
│       ├── cpu
│       │   ├── microarchitectures.json
│       │   └── microarchitectures_schema.json
│       ├── LICENSE-APACHE
│       ├── LICENSE-MIT
│       ├── NOTICE
│       └── README.md
├── LICENSE-APACHE
├── LICENSE-MIT
├── PKG-INFO
├── pyproject.toml
├── README.md
└── setup.py

$ cd archspec-0.1.0/
$ pip install .
Processing /home/culpo/tmp/archspec/PyPI/archspec-0.1.0
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
    Preparing wheel metadata ... done
Collecting six<2.0.0,>=1.13.0 (from archspec==0.1.0)
  Using cached https://files.pythonhosted.org/packages/65/eb/1f97cb97bfc2390a276969c6fae16075da282f5058082d4cb10c6c5c1dba/six-1.14.0-py2.py3-none-any.whl
Building wheels for collected packages: archspec
  Building wheel for archspec (PEP 517) ... done
  Created wheel for archspec: filename=archspec-0.1.0-cp37-none-any.whl size=28550 sha256=be95d20ffcab5b37653a185bd76c3d0e9d0c102eeaf665d8eb7daa9acf489c31
  Stored in directory: /home/culpo/.cache/pip/wheels/89/a9/83/bfb7694e19e66cd50abcc852ea1a1ffd58b03dc2841e825220
Successfully built archspec
Installing collected packages: six, archspec
Successfully installed archspec-0.1.0 six-1.14.0
```

**Comment by verdurin** [comment]
Is there a way forward here?

**Comment by boegel** [comment]
This version of `archspec` is no longer relevant, we have easyconfigs for newer `archspec` versions already with a non-system toolchain, so not going to pursue this one...

**Pull request closed without merging**
