### PR TITLE
fix source URL for Yasm 1.3.0 (+ add missing checksum)

### LINKED ISSUE #13637: Yasm download link fails for Yasm-1.3.0-GCCcore-10.2.0.eb
Hi,

The yasm download link is now failing 

```
FAILED: Installation ended unsuccessfully (build directory: /tmp/easybuild/Yasm/1.3.0/GCCcore-10.2.0): build failed (first 300 chars): Unexpected error occurred when trying to download https://www.tortall.net/projects/yasm/release
s/yasm-1.3.0.tar.gz to {path}/easybuild/sources/y/Yasm/yasm-1.3.0.tar.gz: hostname 'www.tortall.net' doesn't match either of 'tortall.com', 'tortall.net', 'tortall.org' (took 0 secs)
```

The web site now seems to be http://yasm.tortall.net/ however if I submit that change (which I'm happy to do), won't it fail the easyconfig style check as it's an http rather than https web site? The source is also available from github (https://github.com/yasm/yasm/) but that obviously doesn't resolve the home page issue. What's the best solution?

Thanks

### PR DESCRIPTION
**Pull request by boegel**
(created using `eb --new-pr`)
fixes #13637

### CODE REVIEW

**Comment by boegel** [comment]
@boegelbot please test @ generoso
EB_ARGS="--force-download --sourcepath /tmp/$USER/pr13901 Yasm-1.3.0-GCCcore-10.2.0.eb Yasm-1.3.0-GCCcore-10.3.0.eb Yasm-1.3.0-GCCcore-11.2.0.eb Yasm-1.3.0-GCCcore-8.2.0.eb"

**Review by Micket — APPROVED** [review]
lgtm

**Comment by Micket** [comment]
Test report by @Micket
**SUCCESS**
Build succeeded for 9 out of 9 (9 easyconfigs in total)
alvis-c1 - Linux centos linux 7.9.2009, x86_64, Intel Xeon Processor (Skylake), Python 3.6.8
See https://gist.github.com/302d8b84067138a27994b150ba1ffa1b for a full test report.

**Comment by Micket** [comment]
Going in, thanks @boegel!

**Pull request merged**
