### PR TITLE
{lib}[GCC/8.2.0-2.31.1,iccifort-2019.1.144-GCC-8.2.0-2.31.1] OpenMPI v3.1.3: Fix ucx memory leak and init

### PR DESCRIPTION
**Pull request by omula**
Includes:
From 4763822a64c9002f24429aef95d87f6abfc45c06 Mon Sep 17 00:00:00 2001
From: Yossi Itigin <yosefe@mellanox.com>
Date: Tue, 9 Oct 2018 16:38:49 +0300
Subject: [PATCH] pml_ucx: add ompi datatype attribute to release ucp_datatype

From 40ac9e477165616ab98085e2d590dbbbe4874b9f Mon Sep 17 00:00:00 2001
From: Yossi Itigin <yosefe@mellanox.com>
Date: Wed, 10 Oct 2018 12:10:28 +0300
Subject: [PATCH] pml_ucx: fix return code from mca_pml_ucx_init()

### CODE REVIEW

**Comment by akesandgren** [comment]
Please don't merge the two commits into a single patch. It's much better from a tracking point of view to have them separately. Also add the commit message to the head of each patch file so we know where the patches are from.

And if you could describe in this thread or the corresponding issue, if there is any, what prompted you to cherry pick these two patches.

**Comment by omula** [comment]
@akesandgren  the patch comes from https://github.com/open-mpi/ompi/pull/5878. I splitted them original in two files because there were two commits but in fact it is a single patch.

As mentioned in the conference call on 20190123 ucx is needed to work with MOFED 4.4.x. However, there's a memory leak on the ucx framework. It seems it was only backported to version 4.0.x.

**Comment by boegel** [comment]
@omula Patch filename is incorrect?

**Comment by akesandgren** [comment]
Test report by @akesandgren
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in this PR)
t-an01.hpc2n.umu.se - Linux ubuntu 16.04, AMD Opteron(TM) Processor 6238, Python 2.7.12
See https://gist.github.com/9c8fdcf24782d0c142477776f78cff63 for a full test report.

**Comment by akesandgren** [comment]
Going in, thanks @omula!

**Pull request merged**
