### PR TITLE
{bio}[intel/2017b] VEP v94.5 w/ Perl 5.26.0

### PR DESCRIPTION
**Pull request by vanzod**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by vanzod** [comment]
Test report by @vanzod
**SUCCESS**
Build succeeded for 3 out of 3 (3 easyconfigs in this PR)
cermis - Linux debian 9.6, Intel(R) Xeon(R) CPU           E5620  @ 2.40GHz, Python 2.7.13
See https://gist.github.com/26ea057c102fe348a78321a30d04fb43 for a full test report.

**Comment by boegel** [comment]
@vanzod You've introduced a `libxml2` conflict somewhere...

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 6 out of 6 (4 easyconfigs in this PR)
node2537.golett.os - Linux centos linux 7.6.1810, Intel(R) Xeon(R) CPU E5-2680 v3 @ 2.50GHz, Python 2.7.5
See https://gist.github.com/c88ba5274f5e2661bbdb0437bf6a9cf0 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 7 out of 7 (4 easyconfigs in this PR)
node2012.delcatty.os - Linux centos linux 7.6.1810, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.7.5
See https://gist.github.com/63f1ff31530094abc6751f9e1c0ad1fc for a full test report.

**Comment by boegel** [comment]
Going in, thanks @vanzod!

**Pull request merged**
