### PR TITLE
add fallback source URL for recent pigz versions

### LINKED ISSUE #7338: fix the download URL for pigz-2.3.4-GCCcore-6.4.0.eb
The download link in pigz-2.3.4-GCCcore-6.4.0.eb does not exist anymore. However, I found the pigz 2.3.4 is available through the author's github page: https://github.com/madler/pigz/releases/tag/v2.3.4 . Please fix the url.

### PR DESCRIPTION
**Pull request by boegel**
fixes #7338

### CODE REVIEW

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 4 out of 4 (4 easyconfigs in this PR)
node2001.delcatty.os - Linux centos linux 7.5.1804, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.7.5
See https://gist.github.com/9e27354236d5c17f8af6f66c9ebdbb3a for a full test report.

**Comment by bartoldeman** [comment]
Test report by @bartoldeman
**FAILED**
Build succeeded for 1 out of 4 (4 easyconfigs in this PR)
lg-1r17-n06 - Linux centos 6.6, Intel(R) Xeon(R) CPU E5-2650 0 @ 2.00GHz, Python 2.6.6
See https://gist.github.com/92499330b203f7e2c4df4a1744cd55df for a full test report.

**Comment by bartoldeman** [comment]
Test report by @bartoldeman
**FAILED**
Build succeeded for 0 out of 4 (4 easyconfigs in this PR)
lg-1r17-n06 - Linux centos 6.6, Intel(R) Xeon(R) CPU E5-2650 0 @ 2.00GHz, Python 2.6.6
See https://gist.github.com/ed80ba67d1c7de3a492fd88f770a0618 for a full test report.

**Comment by bartoldeman** [comment]
Test report by @bartoldeman
**FAILED**
Build succeeded for 1 out of 4 (4 easyconfigs in this PR)
lg-1r17-n06 - Linux centos 6.6, Intel(R) Xeon(R) CPU E5-2650 0 @ 2.00GHz, Python 2.6.6
See https://gist.github.com/79797fab0b375ad118893aa739ae200b for a full test report.

**Comment by bartoldeman** [comment]
Test report by @bartoldeman
**SUCCESS**
Build succeeded for 4 out of 4 (4 easyconfigs in this PR)
lg-1r17-n06 - Linux centos 6.6, Intel(R) Xeon(R) CPU E5-2650 0 @ 2.00GHz, Python 2.6.6
See https://gist.github.com/83ec60f6c35290edbcbcfde759e82f81 for a full test report.

**Comment by bartoldeman** [comment]
I ran into this: https://github.com/easybuilders/easybuild-easyconfigs/issues/5776
If I create lib64->lib symlinks in relevant $EBROOTZLIB then it compiles ok, otherwise it tries to link to `/usr/lib64/libz.so`

**Comment by boegel** [comment]
@bartoldeman Ugh, thanks for testing and figuring this out, I'm sure that wasn't trivial...

Should this be a blocker for this PR however? It seems like this is a rather obscure problem that doesn't surface often (otherwise more people would be reporting it more frequently), and we should follow up on it via #5776?

**Comment by bartoldeman** [comment]
https://github.com/easybuilders/easybuild-easyconfigs/pull/2266 ran into the same issue...
at least we now know why it happens: if you search for gzopen64 you will find a few other zlib-related failures.

On CentOS7 the system zlib is new enough so you do not get symbol errrors, but still it uses the system zlib at link time and the EB zlib at runtime.

**Comment by boegel** [comment]
@bartoldeman I don't think we can fix this easily in general...

The actual problem here is that `pigz` doesn't include a proper `-L/path/to/zlib` compiler option (which gets preference over the paths listed in `$LIBRARY_PATH`).

So we should look into fixing that?

**Comment by verdurin** [comment]
Test report by @verdurin
**SUCCESS**
Build succeeded for 4 out of 4 (4 easyconfigs in this PR)
rescomp2 - Linux centos linux 7.3.1611, Intel(R) Xeon(R) Gold 6126 CPU @ 2.60GHz, Python 2.7.5
See https://gist.github.com/62872ba3fb681fe2d2b094eb5b20edf9 for a full test report.

**Comment by boegel** [comment]
@bartoldeman Fixed, good to go now?

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 4 out of 4 (4 easyconfigs in this PR)
node2532.golett.os - Linux centos linux 7.5.1804, Intel(R) Xeon(R) CPU E5-2680 v3 @ 2.50GHz, Python 2.7.5
See https://gist.github.com/c2680d6f4063dcb77103d6ea127f0ba1 for a full test report.

**Comment by bartoldeman** [comment]
Test report by @bartoldeman
**SUCCESS**
Build succeeded for 4 out of 4 (4 easyconfigs in this PR)
lg-1r17-n06 - Linux centos 6.6, Intel(R) Xeon(R) CPU E5-2650 0 @ 2.00GHz, Python 2.6.6
See https://gist.github.com/a8bc893b44597da95b9417e546bb1952 for a full test report.

**Comment by bartoldeman** [comment]
Going in, thanks @boegel!

**Pull request merged**
