### PR TITLE
add alternative checksum for source tarball of MONAI 1.3.0

### LINKED ISSUE #20617: invalid checksum for MONAI 1.3.0 due to changes in source tarball served by GitHub
Installing of `MONAI-1.3.0-foss-2023a.eb` or `MONAI-1.3.0-foss-2023a-CUDA-12.1.1.eb` fails on a system where the source tarball for MONAI 1.3.0 itself has not been downloaded yet, with:

```
== FAILED: Installation ended unsuccessfully (build directory: /tmp/vsc40003/easybuild/MONAI/1.3.0/foss-2023a): build failed (first 300 chars): Checksum verification for extension source 1.3.0.tar.gz failed (took 1 secs)
```

The corresponding file https://github.com/Project-MONAI/MONAI/blob/dev/monai/_version.py hasn't actually been updated in two years, and is identical in the `1.3.0` tag (see https://github.com/Project-MONAI/MONAI/blob/1.3.0/monai/_version.py), but the source tarball obtained via https://github.com/Project-MONAI/MONAI/archive/1.3.0.tar.gz is definitely different from before...

Here's a diff between the old copy (checksum `67e0f55678faad4bd38b1ea69d5de94586b20b551b8ad745415623a8b6c1c5e2`) and the new copy (checksum `076d75458d490b4f2dafbf5974fcc8e07a86c03f39f5ef48c6689ab6e4347da9`):

```diff
$ diff -ru MONAI-1.3.0.orig MONAI-1.3.0
diff -ru MONAI-1.3.0.orig/monai/_version.py MONAI-1.3.0/monai/_version.py
--- MONAI-1.3.0.orig/monai/_version.py	2023-10-12 12:51:53
+++ MONAI-1.3.0/monai/_version.py	2023-10-12 12:51:53
@@ -25,7 +25,7 @@
     # setup.py/versioneer.py will grep for the variable names, so they must
     # each be defined on a line of their own. _version.py will just call
     # get_keywords().
-    git_refnames = " (tag: 1.3.0, main)"
+    git_refnames = " (tag: 1.3.0)"
     git_full = "865972f7a791bf7b42efbcd87c8402bd865b329e"
     git_date = "2023-10-12 11:51:53 +0100"
     keywords = {"refnames": git_refnames, "full": git_full, "date": git_date}

### PR DESCRIPTION
**Pull request by boegel**
(created using `eb --new-pr`)
fixes #20617

### CODE REVIEW

**Comment by boegel** [comment]
@boegelbot please test @ generoso
CORE_CNT=16

**Comment by boegel** [comment]
@boegelbot please test @ jsc-zen3
EB_ARGS="--force-download"

**Review by SebastianAchilles — APPROVED** [review]
lgtm

**Comment by SebastianAchilles** [comment]
Going in, thanks @boegel!

**Pull request merged**
