### PR TITLE
{tools}[GCC/11.3.0] SLiM v4.0.1

### PR DESCRIPTION
**Pull request by sassy-crick**
(created using `eb --new-pr`)

This is an update from PR #16110 as the user requested this version. I bumped up the toolchain as well and created PR #17747 . 
I am not insisting on using a newer toolchain, I only thought it might make sense.

### CODE REVIEW

**Comment by sassy-crick** [comment]
@boegelbot please test @ generoso

**Comment by bedroge** [comment]
@boegelbot please test @ jsc-zen2

**Comment by bedroge** [comment]
> @sassy-crick I'll review and merge @akesandgren's PR first, then I guess you could simply use the patch from that PR (I don't see any differences, except in the filename)?

Done! Could you remove the patch from this PR, and use `SLiM-4.0_use_external_zlib_gsl.patch` instead?

**Comment by sassy-crick** [comment]
@boegelbot please test @ generoso

**Comment by bedroge** [comment]
@boegelbot please test @ jsc-zen2

**Comment by bedroge** [comment]
Test report by @bedroge
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
node1 - Linux Rocky Linux 8.7, x86_64, AMD EPYC 7763 64-Core Processor, Python 3.6.8
See https://gist.github.com/bedroge/28d0ddcf95ea958b4b0c6c36ed49f79a for a full test report.

**Review by bedroge — APPROVED** [review]
Lgtm

**Comment by bedroge** [comment]
Going in, thanks @sassy-crick!

**Pull request merged**
