### PR TITLE
{math}[GCCcore/10.3.0] Gurobi v9.5.0 w/ Python 3.9.5

### PR DESCRIPTION
**Pull request by SIB-software**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by SIB-software** [comment]
Test report by @sib-software
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
vitbuild - Linux centos linux 7.9.2009, x86_64, Intel(R) Xeon(R) Gold 6230 CPU @ 2.10GHz, Python 3.6.8
See https://gist.github.com/0f4682913d9bae47b5e2a5ac3e581bb3 for a full test report.

**Comment by smoretti** [comment]
In fact the license file is required for the installation

**Review by boegel — APPROVED** [review]
lgtm

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
node3108.skitty.os - Linux centos linux 7.9.2009, x86_64, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz (skylake_avx512), Python 3.6.8
See https://gist.github.com/9abb20ac5bd96a0ac1bd321bc9ae741f for a full test report.

**Comment by boegel** [comment]
Going in, thanks @SIB-software!

**Pull request merged**
