### PR TITLE
build both API62 and API80 for libjpeg

### PR DESCRIPTION
**Pull request by pescobar**
Reasons for this PR are detailed in this issue: #3829

I think this won't break backward compatibility in any case because the latest configure-make-makeinstall cycle is still using the option `--with-jpeg8` which was the default before this PR

### CODE REVIEW

**Comment by pescobar** [comment]
More info can be found here: 
https://github.com/libjpeg-turbo/libjpeg-turbo#using-libjpeg-turbo

It seems that using `--with-jpeg8` only the TurboJPEG API is built. Applying this PR the libjpeg API is also built.

**Comment by boegel** [comment]
@pescobar see https://github.com/hpcugent/easybuild-easyconfigs/issues/3829#issuecomment-261766069, this is not fully installing the most recent version of the API, since some files will get overwritten in the 2nd cycle.

As you have done it here, it's OK though, since we're not breaking backward-compatibility (the install cycle using `--with-jpeg8` is done last, so it still 'wins').

But I'm not sure this is actually what we want...
Thougths?

**Comment by pescobar** [comment]
@boegel I think you are right and this is now what we want.

I have been looking at how other package managers handle this and I have seen that in ubuntu you can find two packages: `libjpeg-turbo8` and `libjpeg62`. Those two packages can be installed together. These are the provided libraries:

http://packages.ubuntu.com/xenial/amd64/libjpeg62/filelist
```
/usr/lib/x86_64-linux-gnu/libjpeg.so.62
/usr/lib/x86_64-linux-gnu/libjpeg.so.62.0.0
```

http://packages.ubuntu.com/xenial/amd64/libjpeg-turbo8/filelist
```
/usr/lib/x86_64-linux-gnu/libjpeg.so.8
/usr/lib/x86_64-linux-gnu/libjpeg.so.8.0.2
```

The problem appears with the devel packages. Both `libjpeg-turbo8-dev` and `libjpeg62-dev` provide a static lib `/usr/lib/x86_64-linux-gnu/libjpeg.a` so both are incompatible. You cannot install both packages together.

http://packages.ubuntu.com/xenial/amd64/libjpeg-turbo8-dev/filelist
http://packages.ubuntu.com/xenial/amd64/libjpeg62-dev/filelist

to be honest I don't know what would be the right approach to handle this :?

**Comment by migueldiascosta** [comment]
@pescobar, this PR is being closed for the following reason(s): no activity for > 1 year.
Please don't hesitate to reopen this PR or add a comment if you feel this contribution is still relevant.
For more information on our policy w.r.t. closing PRs, see https://easybuild.readthedocs.io/en/latest/Contributing.html#why-a-pull-request-may-be-closed-by-a-maintainer

**Pull request closed without merging**
