### PR TITLE
{lib}[foss/2023a] PyTorch-Lightning v2.2.1, deepdiff v6.7.1, tensorboardX v2.6.2.2

### PR DESCRIPTION
**Pull request by boegel**
(created using `eb --new-pr`)
requires:
* ~#19647~
* #19716

### CODE REVIEW

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 3 out of 3 (3 easyconfigs in total)
node3138.skitty.os - Linux RHEL 8.8, x86_64, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz (skylake_avx512), Python 3.6.8
See https://gist.github.com/boegel/2cecaf668d3e38b76aff570940b1c7ba for a full test report.

**Comment by boegel** [comment]
@boegelbot please test @ generoso

**Comment by boegel** [comment]
@boegelbot please test @ generoso

**Comment by boegel** [comment]
@boegelbot please test @ generoso

**Comment by boegel** [comment]
@boegelbot please test @ jsc-zen3

**Comment by smoors** [comment]
@boegelbot: please test @ generoso

**Comment by smoors** [comment]
@boegelbot please test @ jsc-zen3

**Comment by smoors** [comment]
@boegelbot please test @ jsc-zen3

**Comment by smoors** [comment]
```
test_sparse_csr 1/1 failed! Received signal: SIGKILL

== 2024-03-12 16:32:55,976 filetools.py:383 INFO Path /tmp/eb-i_0oel8s/tmp38x074ai successfully removed.
== 2024-03-12 16:32:59,450 build_log.py:171 ERROR EasyBuild crashed with an error (at easybuild/easybuild-framework/easybuild/base/exceptions.py:126 in __init__): Test ended with failures! Exit code: 1
Failed tests (suites/files):
+ test_sparse_csr 1/1 (at easybuild/easybuild-easyblocks/easybuild/easyblocks/p/pytorch.py:523 in test_step)
```

**Review by smoors — APPROVED** [review]
lgtm

**Comment by smoors** [comment]
Going in, thanks @boegel!

**Pull request merged**
