### PR TITLE
fix PyTorch-1.13.1-foss-2022a.eb for Linux 6+

### PR DESCRIPTION
**Pull request by Flamefire**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by Flamefire** [comment]
Test report by @Flamefire
**FAILED**
Build succeeded for 0 out of 1 (1 easyconfigs in total)
n1038 - Linux RHEL 8.7 (Ootpa), x86_64, Intel(R) Xeon(R) Platinum 8470 (icelake), Python 3.8.13
See https://gist.github.com/Flamefire/505df91653e3a62ced77a5e81ac2f6d0 for a full test report.

**Comment by Flamefire** [comment]
Test report by @Flamefire
**FAILED**
Build succeeded for 0 out of 1 (1 easyconfigs in total)
n1444 - Linux RHEL 8.7 (Ootpa), x86_64, Intel(R) Xeon(R) Platinum 8470 (icelake), Python 3.8.13
See https://gist.github.com/Flamefire/2583676245f77b8e4938b517fab4674d for a full test report.

**Comment by Flamefire** [comment]
Test report by @Flamefire
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
n1444 - Linux RHEL 8.7 (Ootpa), x86_64, Intel(R) Xeon(R) Platinum 8470 (icelake), Python 3.8.13
See https://gist.github.com/Flamefire/5ba8f61e2b83e1c788d7576d3f76ad56 for a full test report.

**Comment by casparvl** [comment]
Test report by @casparvl
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
tcn1.local.snellius.surf.nl - Linux RHEL 8.6, x86_64, AMD EPYC 7H12 64-Core Processor, Python 3.6.8
See https://gist.github.com/casparvl/e4b5157f3492c95d026c0dac8d0fa55a for a full test report.

**Comment by casparvl** [comment]
@boegelbot please test @ jsc-zen3
CORE_CNT=16

**Comment by casparvl** [comment]
@boegelbot please test @ jsc-zen3
CORE_CNT=16

**Comment by casparvl** [comment]
@boegelbot please test @ generoso
CORE_CNT=16

**Review by casparvl — APPROVED** [review]

**Comment by casparvl** [comment]
Going in, thanks @Flamefire!

**Pull request merged**
