### PR TITLE
{lib}[foss/2020b] imagecodecs v2021.8.26 + dependencies (Blosc2, Brunsli, CFITSIO, jxrlib, LERC, libaer)

### PR DESCRIPTION
**Pull request by deniskristak**
adding easyconfigs: libaec-1.0.6-foss-2020b.eb, lerc-3.0-foss-2020b.eb, jxrlib-1.1-foss-2020b.eb, CFITSIO-3.49-GCCcore-10.2.0.eb, brunsli-0.1-foss-2020b.eb, Blosc2-2.0.3-GCCcore-10.2.0.eb, imagecodecs-2021.8.26-foss-2020b.eb

edit (by @boegel): requires ~#14246~ (dependencies for `imagecodecs`)

### CODE REVIEW

**Review by Micket — DISMISSED** [review]

**Comment by boegel** [comment]
@boegelbot please test @ generoso
CORE_CNT=16

**Review by boegel — APPROVED** [review]
lgtm

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 7 out of 7 (7 easyconfigs in total)
node3116.skitty.os - Linux centos linux 7.9.2009, x86_64, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz (skylake_avx512), Python 3.6.8
See https://gist.github.com/bb02e9d14c609bb98dcaaf974baecac6 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 10 out of 10 (7 easyconfigs in total)
node3518.doduo.os - Linux RHEL 8.2, x86_64, AMD EPYC 7552 48-Core Processor (zen2), Python 3.6.8
See https://gist.github.com/b0aa7f2ac466195e711526d90d5f83be for a full test report.

**Comment by boegel** [comment]
Going in, thanks @deniskristak!

**Pull request merged**
