### PR TITLE
fix PyTorch-1.12.0-foss-2022a for Linux 6+

### PR DESCRIPTION
**Pull request by Flamefire**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by Flamefire** [comment]
Test report by @Flamefire
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
n1227 - Linux RHEL 8.7 (Ootpa), x86_64, Intel(R) Xeon(R) Platinum 8470 (icelake), Python 3.8.13
See https://gist.github.com/Flamefire/22983353609697e131837e4545e41bd0 for a full test report.

**Comment by casparvl** [comment]
Test report by @casparvl
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
tcn1.local.snellius.surf.nl - Linux RHEL 8.6, x86_64, AMD EPYC 7H12 64-Core Processor, Python 3.6.8
See https://gist.github.com/casparvl/5285d519f77587aceffa40d4ec731907 for a full test report.

**Comment by casparvl** [comment]
@boegelbot please test @ generoso
CORE_CNT=16

**Review by casparvl — APPROVED** [review]

**Comment by casparvl** [comment]
Going in, thanks @Flamefire!

**Pull request merged**
