### PR TITLE
{tools}[foss/2017A,intel/2017A] HPL v2.2, HPL v2.2

### PR DESCRIPTION
**Pull request by JackPerdue**
(created using `eb --new-pr`)
our new toolchain on terra... just a demonstration

### CODE REVIEW

**Comment by JackPerdue** [comment]
First and foremost, I have no expectation that this will be accepted at this point due to the conflict in the definition of GCCcore.  In the future, I would recommend EB tag the GCCcore version with the binutils used (if using a non-system binutils) so that that the non-subversioned GCCcore using the system binutils (like GCCcore above) won't conflict.  It also allows for GCCcore-6.3.0-2.24, GCCcore-6.3.0-2.25, GCCcore-6.3.0-2.26, etc.

We are struggling on a RH7.3 with Intel's new OmniPath Architecture and trying to pin things down.  So we are running with this for now (unless there is a reason we shouldn't).

**Comment by JackPerdue** [comment]
more here..... GCCcore-6.3.0 and 2017A are the new stuff (there is a lot of failed trash as well)

http://www.siliconslick.com/easybuild/easyconfigs/terra/

**Comment by JackPerdue** [comment]
Things of note:

1) I explicitly list the name of the Python easyblock in each easyconfig
2) I provide a line between homepage/description just for clarity
3) I tried to make the descriptions for each use the same format....  single line use a single double-quote, multi-line use triple-double-quotes
4) tried to make pep8 happy as much as possible
5) last, but not least, I'm trying a different approach.  For every case where I think I safely replace a builddependency with an osdependency, I'm doing it.   My heuristic (rule of thumb) for the moment that any package that is only one name (binutils, make, cmake, autoconf, automake, libtool, pkgconfig, etc).. I am using the OS version.  Anything with "-devel" should be a module EXCEPT openssl/zlib (zlib is a dependency of openssl) and RPMs need for MPI fabric (e.g libibverbs-devel).    There are some cases (LLVM) where a newer CMake is required but for the most part this (with --minimal-toolchains) allows us to cut down on a significant number of (unnecessary?) modules

**Comment by boegel** [comment]
Unless you intend to get this merged, please close?

**Pull request closed without merging**
