### PR TITLE
New download urls for SCOTCH 6.1.0

### PR DESCRIPTION
**Pull request by Micket**
(created using `eb --new-pr`)
Only sources available on the new gitlab page.

Partly addresses #14098

### CODE REVIEW

**Comment by Micket** [comment]
@boegelbot please test @ generoso

**Comment by Micket** [comment]
Test report by @Micket
**SUCCESS**
Build succeeded for 3 out of 3 (3 easyconfigs in total)
vera-c1 - Linux centos linux 7.9.2009, x86_64, Intel Xeon Processor (Skylake), Python 3.6.8
See https://gist.github.com/7ace054602f44fb2382ff2a2958f7d74 for a full test report.

**Comment by SebastianAchilles** [comment]
Test report by @sebastianachilles
**SUCCESS**
Build succeeded for 3 out of 3 (3 easyconfigs in total)
rocky8-eb - Linux rocky linux 8.4, x86_64, Intel(R) Core(TM) i7-6900K CPU @ 3.20GHz (broadwell), Python 3.6.8
See https://gist.github.com/bb7f0bae09b37c8ce4fb405693aaaa9a for a full test report.

**Comment by Micket** [comment]
generoso seems to be missing the intel license.

**Comment by SebastianAchilles** [comment]
@boegelbot please test @ generoso

**Comment by SebastianAchilles** [comment]
Going in, thanks @Micket!

**Pull request merged**
