### PR TITLE
{base}[foss/2020a] lipsia v3.1.0

### PR DESCRIPTION
**Pull request by kErica**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by verdurin** [comment]
@boegelbot please test @ generoso

**Comment by verdurin** [comment]
Test report by @verdurin
**FAILED**
Build succeeded for 0 out of 1 (1 easyconfigs in total)
easybuild-c7.novalocal - Linux centos linux 7.9.2009, x86_64, Intel Xeon Processor (Skylake, IBRS), Python 3.6.8
See https://gist.github.com/77bf9cae92b04513a4d9d72c9a9b9d57 for a full test report.

**Comment by kErica** [comment]
@verdurin is there something more that I can do to make the _generoso_ test pass?
best

**Comment by kErica** [comment]
Dear all, 
this is still pending. Is there anything else I can do? 
I am not sure if the generoso is not passing because of the checksums - as this is using a specific commit from a github repo.

cheers

**Comment by boegel** [comment]
closing this since `foss/2020a` is deprecated, see https://docs.easybuild.io/policies/toolchains

@kErica Sorry for not getting back to this...

If `lipsia` is still relevant, please consider opening a new PR with a more recent toolchain

**Pull request closed without merging**
