### PR TITLE
use patch to fix flaky test optim test in PyTorch 1.12.1 w/ foss/2021b

### PR DESCRIPTION
**Pull request by branfosj**
(created using `eb --new-pr`)

add patch from #17726 - using separate PRs for each easyconfig

### CODE REVIEW

**Comment by branfosj** [comment]
Test report by @branfosj
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
bear-pg0104u17a.bear.cluster - Linux RHEL 8.6, x86_64, Intel(R) Xeon(R) Platinum 8360Y CPU @ 2.40GHz (icelake), Python 3.6.8
See https://gist.github.com/branfosj/c72a289a5950d1270ee1a9a3706a6577 for a full test report.

**Review by boegel — APPROVED** [review]
lgtm

**Comment by boegel** [comment]
Going in, thanks @branfosj!

**Comment by branfosj** [comment]
See #17737

**Pull request merged**
