### PR TITLE
{lang}[intel/2017b] R 3.4.3 (REVIEW)

### PR DESCRIPTION
**Pull request by boegel**
requires ~~https://github.com/easybuilders/easybuild-framework/pull/2345~~ and ~~#5328, #5334, #5336 , #5341, #5337, #5343, #5346~~

now also requires updates to R easyblock: ~~https://github.com/easybuilders/easybuild-easyblocks/pull/1292, https://github.com/easybuilders/easybuild-easyblocks/pull/1297, https://github.com/easybuilders/easybuild-easyblocks/pull/1300~~

### CODE REVIEW

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
node2612.swalot.os - Linux centos linux 7.4.1708, Intel(R) Xeon(R) CPU E5-2660 v3 @ 2.60GHz, Python 2.7.5
See https://gist.github.com/956a89e44f325e93ecb01ac3f9392437 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
node2080.delcatty.os - Linux centos linux 7.4.1708, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.7.5
See https://gist.github.com/4be52396a35c29052d83e3255e75b0ca for a full test report.

**Comment by verdurin** [comment]
Test report by @verdurin
**FAILED**
Build succeeded for 35 out of 42 (1 easyconfigs in this PR)
rescomp1 - Linux centos 6.8, Intel(R) Xeon(R) CPU E5-2650 v2 @ 2.60GHz, Python 2.7.14
See https://gist.github.com/e1dbf24c5a845468ae997af5e1c4c6a9 for a full test report.

**Comment by boegel** [comment]
@verdurin `util-linux` failed with `sys-utils/rfkill.c:67:12: error: 'RFKILL_TYPE_FM' undeclared here (not in a function)`, `Java` because of missing source tarball

**Comment by boegel** [comment]
I made this `WIP` since I plan to go over the open issues related to R first before we merge this...

**Comment by hajgato** [comment]
`R 3.4.3` soon?

**Comment by boegel** [comment]
@hajgato Hmm, ok, maybe I'll give this another update then, thanks for the info!

This got blocked due to updates to the R easyblock (and a total lack of time from my end to follow up on this).

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
node2404.golett.os - Linux centos linux 7.4.1708, Intel(R) Xeon(R) CPU E5-2680 v3 @ 2.50GHz, Python 2.7.5
See https://gist.github.com/803e704b7551bee2e9edd296d2e0cc26 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
node2004.delcatty.os - Linux centos linux 7.4.1708, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.7.5
See https://gist.github.com/243111dd99c5c34a5003a696eef57378 for a full test report.

**Comment by wpoely86** [comment]
Test report by @wpoely86
**FAILED**
Build succeeded for 24 out of 25 (1 easyconfigs in this PR)
nic200 - Linux centos linux 7.4.1708, Intel(R) Xeon(R) CPU E7-8891 v4 @ 2.80GHz, Python 2.7.5
See https://gist.github.com/f1f9b670260c530d53af6f6a51692a5b for a full test report.

**Comment by boegel** [comment]
@wpoely86 You'll need to (re)move the existing tarball for `Rmpi` 0.6-6, seems like it was changed in place...

**Comment by wpoely86** [comment]
Test report by @wpoely86
**FAILED**
Build succeeded for 21 out of 22 (1 easyconfigs in this PR)
nic167 - Linux centos linux 7.4.1708, Intel(R) Xeon(R) CPU E5-2650 v4 @ 2.20GHz, Python 2.7.5
See https://gist.github.com/ba957a586627fc41440e400e2111673e for a full test report.

**Comment by wpoely86** [comment]
Test report by @wpoely86
**FAILED**
Build succeeded for 20 out of 21 (1 easyconfigs in this PR)
nic167 - Linux centos linux 7.4.1708, Intel(R) Xeon(R) CPU E5-2650 v4 @ 2.20GHz, Python 2.7.5
See https://gist.github.com/c7015ebf85bfcd6b8d22e4f654d17f05 for a full test report.

**Comment by wpoely86** [comment]
Test report by @wpoely86
**FAILED**
Build succeeded for 9 out of 10 (1 easyconfigs in this PR)
nic167 - Linux centos linux 7.4.1708, Intel(R) Xeon(R) CPU E5-2650 v4 @ 2.20GHz, Python 2.7.5
See https://gist.github.com/10c337ad49e8fa3731ef2a807fc2e8ad for a full test report.

**Comment by verdurin** [comment]
Test report by @verdurin
**FAILED**
Build succeeded for 0 out of 6 (1 easyconfigs in this PR)
rescomp2 - Linux centos 6.8, Intel(R) Xeon(R) CPU E5-2650 v2 @ 2.60GHz, Python 2.7.14
See https://gist.github.com/7bec9e4dc60fa7612c7ea10b9ae9b214 for a full test report.

**Comment by boegel** [comment]
@verdurin Can you check whether the `LLVM` you're using (`LLVM/5.0.0-intel-2017b`) had this enabled? https://github.com/easybuilders/easybuild-easyconfigs/pull/5321/commits/1b43ffcf6cbe4c15424b4a3d02ab412a2a78e1f0

That should explain the `undefined reference` errors you're seeing for `Mesa`.

Still not sure about the `util-linux` issue though...

```
sys-utils/rfkill.c:67:12: error: 'RFKILL_TYPE_FM' undeclared here (not in a function)
```

**Comment by boegel** [comment]
@verdurin For the `util-linux` issue, it seems you need a sufficiently recent kernel headers for that version of `util-linux`...

```
$ grep RFKILL_TYPE_FM  /usr/include/linux/rfkill.h
 * @RFKILL_TYPE_FM: switch is on a FM radio device.
        RFKILL_TYPE_FM,
$ rpm -q --whatprovides /usr/include/linux/rfkill.h
kernel-headers-3.10.0-693.5.2.el7.ug.x86_64
```

So I guess we should downgrade to an older version of `util-linux`?

**Comment by boegel** [comment]
@verdurin `util-linux` problem is hopefully fixed with #5480

**Comment by wpoely86** [comment]
Test report by @wpoely86
**SUCCESS**
Build succeeded for 10 out of 10 (1 easyconfigs in this PR)
nic167 - Linux centos linux 7.4.1708, Intel(R) Xeon(R) CPU E5-2650 v4 @ 2.20GHz, Python 2.7.5
See https://gist.github.com/020a99a80ace8789d4893c6500f2db88 for a full test report.

**Pull request merged**
