### PR TITLE
{chem}[foss/2020b] CP2K v8.1

### PR DESCRIPTION
**Pull request by boegel**
(created using `eb --new-pr`)
requires ~~https://github.com/easybuilders/easybuild-easyblocks/pull/2350~~

### CODE REVIEW

**Comment by boegel** [comment]
@boegelbot please test @ generoso
EB_ARGS="--include-easyblocks-from-pr 2350"
CORE_CNT=16

**Comment by smoors** [comment]
@boegel we used to add a versionsuffix `-psmp` for this type, shouldn't this be added here too?

**Comment by smoors** [comment]
Test report by @smoors
Using easyblocks from PR(s) https://github.com/easybuilders/easybuild-easyblocks/pull/2350
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
node351.hydra.os - Linux centos linux 7.9.2009, x86_64, Intel(R) Xeon(R) Gold 6148 CPU @ 2.40GHz (skylake_avx512), Python 2.7.5
See https://gist.github.com/f7f802c58b86415f9249d22e009151eb for a full test report.

**Comment by smoors** [comment]
--------------------------------- Summary --------------------------------
Number of FAILED  tests 0
Number of WRONG   tests 7
Number of CORRECT tests 3411
Total number of   tests 3418
--------------------------------------------------------------------------
Number of LEAKING tests 0
Number of memory  leaks 0
--------------------------------------------------------------------------
@boegel my tests did even better than  yours :)

**Comment by lexming** [comment]
Test report by @lexming
**FAILED**
Build succeeded for 0 out of 1 (1 easyconfigs in total)
node359.hydra.os - Linux centos linux 7.9.2009, x86_64, Intel(R) Xeon(R) Gold 6148 CPU @ 2.40GHz, Python 2.7.5
See https://gist.github.com/0616424346cf4f878fb63aa93c5dcc1f for a full test report.

**Comment by boegel** [comment]
> @boegel we used to add a versionsuffix `-psmp` for this type, shouldn't this be added here too?

Since `popt` is no longer supported in CP2K 8.1, I don't think it makes sense anymore to have a versionsuffix...

This installation provides both `cp2k.popt` and `cp2k.psmp` commands

**Review by lexming — APPROVED** [review]
LGTM

**Comment by lexming** [comment]
Going in, thanks @boegel !

**Comment by akesandgren** [comment]
Why is FFTW an explicit dep despite is using foss toolchain?

**Comment by boegel** [comment]
@akesandgren There's no need, but I guess it's done to have better symmetry with the easyconfigs using the `intel` toolchain?

There's no negative side effect though, so not a big problem? If you think it is, please open an issue or a PR.

**Comment by akesandgren** [comment]
I just find it ugly :-) so ignore then...

**Pull request merged**
