### PR TITLE
{lib}[GCCcore/11.2.0] libconfig v1.7.3

### PR DESCRIPTION
**Pull request by jose-d**
new easyconfig for old library..

(created using `eb --new-pr`)

### CODE REVIEW

**Comment by jose-d** [comment]
Test report by @jose-d
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
login1.phoebe.lan - Linux Rocky Linux 8.6 (Green Obsidian), x86_64, AMD EPYC 73F3 16-Core Processor, Python 3.9.13
See https://gist.github.com/c7e7e984040ba6ba38c3cd6c28bcecba for a full test report.

**Comment by jose-d** [comment]
Test report by @jose-d
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
koiosvm2 - Linux Rocky Linux 8.6 (Green Obsidian), x86_64, Intel(R) Xeon(R) Gold 6130 CPU @ 2.10GHz, Python 3.9.7
See https://gist.github.com/e382f01f9c7a478d1b1550e1bd88b4fa for a full test report.

**Comment by branfosj** [comment]
@boegelbot please test @ jsc-zen2

**Comment by branfosj** [comment]
Test report by @branfosj
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
bear-pg0105u36b.bear.cluster - Linux RHEL 8.5, x86_64, Intel(R) Xeon(R) Platinum 8360Y CPU @ 2.40GHz (icelake), Python 3.6.8
See https://gist.github.com/c4fcdb1b9e45eba05863b9d09d0e2b1e for a full test report.

**Review by branfosj — APPROVED** [review]

**Comment by branfosj** [comment]
Going in, thanks @jose-d!

**Pull request merged**
