### PR TITLE
{numlib}[GCC/7.3.0-2.30,iccifort/2018.3.222-GCC-7.3.0-2.30] GSL v2.5

### PR DESCRIPTION
**Pull request by vanzod**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by boegel** [comment]
@vanzod Should we remove `GSL-2.5-GCCcore-7.3.0.eb` too?

That's a bit controversial, but I feel it's acceptable if we explain well why, since `GSL` 2.5 is currently only used as a dependency for `BCFtools-1.9-foss-2018b.eb` and `PLUMED-2.4.2-foss-2018b.eb`...

cc @akesandgren

**Comment by vanzod** [comment]
@akesandgren You have already provided `GSL-2.5-GCCcore-7.3.0.eb` in #6657 as dependency for `PLUMED`. As of now that is still the only easyconfig file that has `GSL` as dependency. Replacing the `GCCcore` one with the `GCC`+`iccifort` should be relatively painless. However we would like your feedback on this.

**Comment by boegel** [comment]
@vanzod I overlooked `BCFtools-1.9-foss-2018b.eb` when we discussed this. Still, the impact is fairly minor, so I'm OK with it if this is beneficial w.r.t. performance & doesn't cause any problems (I seem to remember building `GSL` with Intel compilers was troublesome).

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in this PR)
node2628.swalot.os - Linux centos linux 7.5.1804, Intel(R) Xeon(R) CPU E5-2660 v3 @ 2.60GHz, Python 2.7.5
See https://gist.github.com/6028e3fd76fcc7de507219a0969e4df2 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in this PR)
node2076.delcatty.os - Linux centos linux 7.5.1804, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.7.5
See https://gist.github.com/12efd2c9cc4b57af9bf85540e7c1355a for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in this PR)
node3161.skitty.os - Linux centos linux 7.5.1804, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz, Python 2.7.5
See https://gist.github.com/262bfde3c2f268e40740dac5d4cf4e50 for a full test report.

**Comment by migueldiascosta** [comment]
Test report by @migueldiascosta
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in this PR)
grc-cluster1 - Linux centos 6.10, Intel(R) Xeon(R) CPU E5-2640 0 @ 2.50GHz, Python 2.7.14
See https://gist.github.com/a0989eaff406e9c5bf8033e8c44fec79 for a full test report.

**Comment by akesandgren** [comment]
I was just lazy and added it at GCCcore level. It usually don't impact performance that much for higher level codes. But having it at this level is better.

**Comment by boegel** [comment]
Going in, thanks @vanzod!

**Pull request merged**
