### PR TITLE
{phys}[foss/2020a] Siesta v4.1.5

### PR DESCRIPTION
**Pull request by akesandgren**
(created using `eb --new-pr`)

depends on ~https://github.com/easybuilders/easybuild-easyblocks/pull/2553~

### CODE REVIEW

**Comment by akesandgren** [comment]
Test report by @akesandgren
Using easyblocks from PR(s) https://github.com/easybuilders/easybuild-easyblocks/pull/2553
**SUCCESS**
Build succeeded for 0 out of 0 (1 easyconfigs in total)
b-an02.hpc2n.umu.se - Linux Ubuntu 20.04, x86_64, Intel(R) Xeon(R) CPU E5-2690 v4 @ 2.60GHz, Python 3.8.5
See https://gist.github.com/6f24ff9d3d8c187f2dabec2baf19a1b9 for a full test report.

**Comment by akesandgren** [comment]
Test report by @akesandgren
Using easyblocks from PR(s) https://github.com/easybuilders/easybuild-easyblocks/pull/2553
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
b-an02.hpc2n.umu.se - Linux Ubuntu 20.04, x86_64, Intel(R) Xeon(R) CPU E5-2690 v4 @ 2.60GHz, Python 3.8.5
See https://gist.github.com/4b32fa92d29b30a95d26fa6ad68db3a0 for a full test report.

**Comment by Micket** [comment]
Test report by @Micket
Using easyblocks from PR(s) https://github.com/easybuilders/easybuild-easyblocks/pull/2553
**SUCCESS**
Build succeeded for 8 out of 8 (1 easyconfigs in total)
vera-c1 - Linux centos linux 7.9.2009, x86_64, Intel Xeon Processor (Skylake), Python 3.6.8
See https://gist.github.com/1988f4c6de4ddf50dd7cd9312050b6dd for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
Using easyblocks from PR(s) https://github.com/easybuilders/easybuild-easyblocks/pull/2553
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
node3528.doduo.os - Linux RHEL 8.2, x86_64, AMD EPYC 7552 48-Core Processor (zen2), Python 3.6.8
See https://gist.github.com/76d76b2b614b053ce10518c997a220d9 for a full test report.

**Comment by SebastianAchilles** [comment]
@boegelbot please test @ generoso
EB_ARGS="--include-easyblocks-from-pr 2553"

**Comment by SebastianAchilles** [comment]
@boegelbot please test @ generoso

**Review by SebastianAchilles — APPROVED** [review]
lgtm

**Comment by SebastianAchilles** [comment]
Test report by @sebastianachilles
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
jsfc01.int.jusuf.sebastian.cluster - Linux Rocky Linux 8.4, x86_64, AMD EPYC 7742 64-Core Processor (zen2), 1 x NVIDIA GRID V100-4C, 460.73.01, Python 3.6.8
See https://gist.github.com/426d5d553372a0219c3ecd6b60fc8103 for a full test report.

**Comment by SebastianAchilles** [comment]
Going in, thanks @akesandgren!

**Pull request merged**
