### PR TITLE
{cae}[foss/2022a] OpenFOAM v11

### PR DESCRIPTION
**Pull request by branfosj**
(created using `eb --new-pr`)

* [x] https://github.com/easybuilders/easybuild-easyblocks/pull/2978

### CODE REVIEW

**Comment by branfosj** [comment]
@boegelbot please test @ generoso

**Comment by branfosj** [comment]
@boegelbot please test @ generoso
EB_ARGS="--include-easyblocks-from-pr 2978"
CORE_CNT=16

**Comment by branfosj** [comment]
Test report by @branfosj
Using easyblocks from PR(s) https://github.com/easybuilders/easybuild-easyblocks/pull/2978
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
bear-pg0105u03a.bear.cluster - Linux RHEL 8.6, x86_64, Intel(R) Xeon(R) Platinum 8360Y CPU @ 2.40GHz (icelake), Python 3.6.8
See https://gist.github.com/branfosj/fdf2f28e30a0cd1446d6b3798e46a5da for a full test report.

**Comment by branfosj** [comment]
@boegelbot please test @ jsc-zen2
EB_ARGS="--include-easyblocks-from-pr 2978"
CORE_CNT=16

**Comment by ocaisa** [comment]
@boegelbot please test @ generoso
EB_ARGS="--include-easyblocks-from-pr 2978"
CORE_CNT=16

**Review by ocaisa — APPROVED** [review]

**Pull request merged**
