### PR TITLE
{bio}[intel/2020a] chewBBACA v2.5.5, Biopython v1.78, BLAST+ v2.10.1, ... w/ Python 3.8.2

### PR DESCRIPTION
**Pull request by zarybnicky**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by zarybnicky** [comment]
This is WIP, I guess, I'll try and add a test script tomorrow.

**Comment by boegel** [comment]
@boegelbot please test @ generoso

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 6 out of 6 (6 easyconfigs in this PR)
node3112.skitty.os - Linux centos linux 7.8.2003, x86_64, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz, Python 3.6.8
See https://gist.github.com/9242c4f4db3f3b57481cf7c979a1f41e for a full test report.

**Comment by boegel** [comment]
@zarybnicky The sanity check you have in place is good enough for now, I don't think there's an easy way to do a "real" test of chewBBACA in the sanity check that isn't excessive long...

**Review by boegel — APPROVED** [review]

**Comment by boegel** [comment]
Going in, thanks @zarybnicky!

**Pull request merged**
