### PR TITLE
{chem}[foss/2023a] pymatgen v2023.12.18, uncertainties 3.1.7

### PR DESCRIPTION
**Pull request by Flamefire**
Extracted from https://github.com/easybuilders/easybuild-easyconfigs/pull/19398

(created using `eb --new-pr`)

Requires
- [x] https://github.com/easybuilders/easybuild-easyconfigs/pull/19716

### CODE REVIEW

**Comment by Flamefire** [comment]
Test report by @Flamefire
**SUCCESS**
Build succeeded for 3 out of 3 (3 easyconfigs in total)
n1505 - Linux RHEL 8.7 (Ootpa), x86_64, Intel(R) Xeon(R) Platinum 8470 (icelake), Python 3.8.13
See https://gist.github.com/Flamefire/090b348c1ed54704a8696d7eb4f1b9ec for a full test report.

**Comment by Flamefire** [comment]
Test report by @Flamefire
**SUCCESS**
Build succeeded for 3 out of 3 (3 easyconfigs in total)
taurusml3 - Linux RHEL 7.6, POWER, 8335-GTX (power9le), 6 x NVIDIA Tesla V100-SXM2-32GB, 440.64.00, Python 2.7.5
See https://gist.github.com/Flamefire/50d8444087d398a78fd79523c293851d for a full test report.

**Review by ocaisa — APPROVED** [review]

**Comment by ocaisa** [comment]
@boegelbot please test @ generoso

**Comment by ocaisa** [comment]
@boegelbot please test @ jsc-zen3

**Pull request merged**
