### PR TITLE
{phys}[foss/2019a] PRISMS-PF v2.1.1, p4est v2.2, deal.II v9.1.1

### PR DESCRIPTION
**Pull request by boegel**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 3 out of 3 (3 easyconfigs in this PR)
node3151.skitty.os - Linux centos linux 7.6.1810, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz, Python 2.7.5
See https://gist.github.com/e9dfcdb539656766042d0285b872bcac for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 3 out of 3 (3 easyconfigs in this PR)
node2710.swalot.os - Linux centos linux 7.6.1810, Intel(R) Xeon(R) CPU E5-2660 v3 @ 2.60GHz, Python 2.7.5
See https://gist.github.com/ca2c63b6b89a8804b4ff48fb35f3a9a9 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 3 out of 3 (3 easyconfigs in this PR)
node2009.delcatty.os - Linux centos linux 7.6.1810, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.7.5
See https://gist.github.com/e0c4153d1a77ebd3b040d87ec366d533 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 3 out of 3 (3 easyconfigs in this PR)
node2710.swalot.os - Linux centos linux 7.6.1810, Intel(R) Xeon(R) CPU E5-2660 v3 @ 2.60GHz, Python 2.7.5
See https://gist.github.com/4eed25e27378021a30e2680e3b0bba68 for a full test report.

**Review by akesandgren — DISMISSED** [review]
LGTM

**Comment by akesandgren** [comment]
Fails on p4est with:
```
copying selected object files to avoid basename conflicts...
libtool: link: ln /scratch/ake/easybuild/software/Compiler/GCC/8.2.0-2.31.1/OpenBLAS/0.3.5/lib/libopenblas.a src/.libs/libsc.lax/lt1-libopenblas.a || cp /scratch/ake/easybuild/software/Compiler/GCC/8.2.0-2.31.1/OpenBLAS/0.3.5/lib/libopenblas.a src/.libs/libsc.lax/lt1-libopenblas.a
libtool: link: ar cru src/.libs/libsc.a /scratch/ake/easybuild/software/Compiler/GCC/8.2.0-2.31.1/OpenBLAS/0.3.5/lib/libopenblas.a src/.libs/libsc.lax/lt1-libopenblas.a src/libsc_la-sc.o src/libsc_la-sc_mpi.o src/libsc_la-sc_containers.o ...
ar: src/.libs/libsc.lax/lt1-libopenblas.a: No such file or directory
Makefile:1361: recipe for target 'src/libsc.la' failed
```

**Comment by akesandgren** [comment]
Test report by @akesandgren
**FAILED**
Build succeeded for 4 out of 7 (3 easyconfigs in this PR)
b-an03.hpc2n.umu.se - Linux ubuntu 16.04, Intel(R) Xeon(R) CPU E5-2690 v4 @ 2.60GHz, Python 2.7.12
See https://gist.github.com/94ca69097426d1b112d1190baa0a2fc5 for a full test report.

**Comment by vanzod** [comment]
Test report by @vanzod
**SUCCESS**
Build succeeded for 3 out of 3 (3 easyconfigs in this PR)
cermis - Linux debian 9.9, Intel(R) Xeon(R) CPU           X5670  @ 2.93GHz, Python 2.7.13
See https://gist.github.com/fd30a7423bd09de583605f03b5c0366a for a full test report.

**Comment by boegel** [comment]
@akesandgren So, we need a patch here?

**Comment by boegel** [comment]
(re-triggering Travis checks)

**Comment by terjekv** [comment]
`PETSc` now has a versionsuffix. The correct version for this toolchain is `PETSc-3.11.1-intel-2019a-Python-3.7.2.eb`.

**Comment by boegel** [comment]
@akesandgren Does that problem you were hitting persist?

**Comment by boegel** [comment]
@boegelbot please test @ generoso

**Comment by boegel** [comment]
@boegelbot please test @ jsc-zen2
CORE_CNT=16

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 3 out of 3 (3 easyconfigs in total)
node3144.skitty.os - Linux RHEL 8.4, x86_64, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz (skylake_avx512), Python 3.6.8
See https://gist.github.com/b5d319fa6d0453804547dbcbba15c12b for a full test report.

**Review by smoors — APPROVED** [review]
lgtm

**Comment by smoors** [comment]
Going in, thanks @boegel!

**Pull request merged**
