### PR TITLE
{bio}[foss/2018b] Cufflinks v2.2.1

### PR DESCRIPTION
**Pull request by SethosII**
(created using `eb --new-pr`)

The patches are just copied over from https://sources.debian.org/patches/cufflinks/2.2.1+dfsg.1-3/, so I'm unsure about what to write in the author part.

### CODE REVIEW

**Comment by SethosII** [comment]
I can't see where `Boost 1.67` comes from.

**Comment by boegel** [comment]
@SethosII Boost 1.67.0 is the version we're using as a dependency for other easyconfigs using a `2018b` toolchain.

By adding an easyconfig that uses Boost 1.68.0, you're violating the policy we're maintaining where we stick to a single "variant" for software that is used as a dependency.

That way, modules that have a common dependency (like `Boost`), but are not dependent on each other can be used in the same environment without hitting any module conflicts.

So, the easiest way to fix this PR is to drop the easyconfig for Boost 1.68.0, and just stick to Boost 1.67.0 for the `2018b` generation of easyconfigs.

**Comment by SethosII** [comment]
@boegel Thank you for the explanation. I moved `Boost` to `1.67` and removed the conflicting `SAMtools` version.

**Comment by boegel** [comment]
Test report by @boegel
**FAILED**
Build succeeded for 1 out of 2 (2 easyconfigs in this PR)
node2526.golett.os - Linux centos linux 7.6.1810, Intel(R) Xeon(R) CPU E5-2680 v3 @ 2.50GHz, Python 2.7.5
See https://gist.github.com/78e1f21e41068e63cf3636334fbf3daa for a full test report.

**Comment by boegel** [comment]
@SethosII You'll need to run `--inject-checksums` again since the checksum of the patches has changed after you added the description...

**Comment by SethosII** [comment]
@boegel I updated the checksum.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in this PR)
node2444.golett.os - Linux centos linux 7.6.1810, Intel(R) Xeon(R) CPU E5-2680 v3 @ 2.50GHz, Python 2.7.5
See https://gist.github.com/7aa7779fd4d00d2f87fb3ae278afe127 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in this PR)
node2083.delcatty.os - Linux centos linux 7.6.1810, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.7.5
See https://gist.github.com/489f35af656df731312c1961e8cd59cc for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in this PR)
node3102.skitty.os - Linux centos linux 7.6.1810, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz, Python 2.7.5
See https://gist.github.com/158c580ab18e11c02b61e2934067f01b for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in this PR)
node2404.golett.os - Linux centos linux 7.6.1810, Intel(R) Xeon(R) CPU E5-2680 v3 @ 2.50GHz, Python 2.7.5
See https://gist.github.com/0bdea43de3851cf4dcda09569afc02fa for a full test report.

**Comment by boegel** [comment]
Going in, thanks @SethosII!

**Pull request merged**
