### PR TITLE
{mpi}[GCCcore/6.4.0,GCCcore/7.3.0] PMIx v1.2.5, PMIx v2.1.3, PMIx v3.0.1

### PR DESCRIPTION
**Pull request by akesandgren**
(created using `eb --new-pr`)
Process Management for Exascale Environments, https://pmix.org/, for use with OpenMPI and IntelMPI.

### CODE REVIEW

**Comment by migueldiascosta** [comment]
@akesandgren missing checksums on the `PMIx` easyconfigs

(@boegel what was the conclusion on integrating `--check-contrib` with `--new-pr`?)

**Comment by boegel** [comment]
@migueldiascosta The conclusion was that somebody should look into it. ;-)

The biggest issue with always running `--check-contrib` with `--new-pr` is that it requires additional Python packages to be installed for the style checks...

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 7 out of 7 (5 easyconfigs in this PR)
node3101.skitty.os - Linux centos linux 7.5.1804, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz, Python 2.7.5
See https://gist.github.com/476400fed87a5412b280c8b417db1c53 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 6 out of 6 (5 easyconfigs in this PR)
node2406.golett.os - Linux centos linux 7.5.1804, Intel(R) Xeon(R) CPU E5-2680 v3 @ 2.50GHz, Python 2.7.5
See https://gist.github.com/48ef9a34b3516451540c75a778100008 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 5 out of 5 (5 easyconfigs in this PR)
node2027.delcatty.os - Linux centos linux 7.5.1804, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.7.5
See https://gist.github.com/f37df5f1961df5ffb9884ca716a2fb1c for a full test report.

**Comment by migueldiascosta** [comment]
Going in, thanks @akesandgren!

**Pull request merged**
