### PR TITLE
{lang}[foss/2023a] R v4.3.1

### PR DESCRIPTION
**Pull request by stefan-wolfsheimer**
(created using `eb --new-pr`)

Depends on:
- https://github.com/easybuilders/easybuild-easyconfigs/pull/18732
- from-pr=17104,18449,18736,18583,18737,18606,18602,18545,18544,18732 --include-easyblocks-from-pr=2973

### CODE REVIEW

**Comment by SebastianAchilles** [comment]
Test report by @sebastianachilles
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
bwd-rockylinux-92 - Linux Rocky Linux 9.2 (Blue Onyx), x86_64, Intel(R) Core(TM) i7-6900K CPU @ 3.20GHz (broadwell), 2 x NVIDIA NVIDIA GeForce GTX 1060 6GB, 535.104.12, Python 3.9.16
See https://gist.github.com/SebastianAchilles/4d355487c0a5c166c3cdf3551e7d5f18 for a full test report.

**Comment by SebastianAchilles** [comment]
Test report by @sebastianachilles
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
zen2-rockylinux-88 - Linux Rocky Linux 8.8, x86_64, AMD EPYC 7452 32-Core Processor (zen2), Python 3.6.8
See https://gist.github.com/SebastianAchilles/01cae2a2bde390c73ff4e43fba52e82e for a full test report.

**Comment by SebastianAchilles** [comment]
@boegelbot please test @ jsc-zen2
@boegelbot please test @ jsc-zen2

**Comment by SebastianAchilles** [comment]
@boegelbot please test @ generoso

**Review by boegel — CHANGES_REQUESTED** [review]
The plan with `R` is to only use a limited set of R packages as extensions in R itself, and introduce `R-bundle-CRAN`, similar to what we did for `Python` and `Perl`, see also #18221

**Comment by boegel** [comment]
closing, superseded by #19185 + #19170

**Pull request closed without merging**
