### PR TITLE
{tools}[foss/2020a] IRkernel v1.1 w/ Python 3.8.2

### PR DESCRIPTION
**Pull request by branfosj**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by branfosj** [comment]
Test report by @branfosj
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
bber0501u03a.bb2.cluster - Linux centos linux 7.7.1908, Intel(R) Xeon(R) CPU E5-2690 v3 @ 2.60GHz, Python 2.7.5
See https://gist.github.com/760bcb2163d274248dfbf2b55b29cffb for a full test report.

**Comment by branfosj** [comment]
Test report by @branfosj
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
bear-pg0211u03a.bear.cluster - Linux centos linux 7.7.1908, Intel(R) Xeon(R) Gold 6248 CPU @ 2.50GHz, Python 2.7.5
See https://gist.github.com/90f1e49e0e65bb589ffe0006503fa7db for a full test report.

**Comment by branfosj** [comment]
Test report by @branfosj
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
bb2c1a09.bb2.cluster - Linux centos linux 7.7.1908, Intel(R) Xeon(R) CPU E5-2660 0 @ 2.20GHz, Python 2.7.5
See https://gist.github.com/652293ca5145eec16f978a8358f8a070 for a full test report.

**Comment by branfosj** [comment]
Test report by @branfosj
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
bb2c1a09.bb2.cluster - Linux centos linux 7.7.1908, Intel(R) Xeon(R) CPU E5-2660 0 @ 2.20GHz, Python 2.7.5
See https://gist.github.com/3b671410e543401d9ed6573730091fe1 for a full test report.

**Comment by branfosj** [comment]
Test report by @branfosj
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
ubuntu-apps-builder2-its-rescomp-apps - Linux ubuntu 16.04, Intel Core Processor (Broadwell, no TSX) (broadwell), Python 2.7.12
See https://gist.github.com/5af4f54940870bab9fc3822e65ed588f for a full test report.

**Comment by lexming** [comment]
Re-triggering travis...

**Comment by Micket** [comment]
Travis got stuck somehow?

**Comment by branfosj** [comment]
I am not sure what is up with Travis on this. It completes successfully but this is not getting reported back here. I've done a sync with the latest 2020a branch to see if that helps.

**Comment by boegel** [comment]
Hmm, usually I can manually re-trigger Travis builds, which tends to help with the Travis result coming back to GitHub. But now there's no re-trigger button for this one... :-/

**Comment by Micket** [comment]
Not only that, but I only see 1 test for GHA. Shouldn't there be like 10 more?

**Comment by branfosj** [comment]
@Micket There is only one GHA as this is on the 2020a branch.

Do we want to continue trying to get this one to work or should I just create a new PR for this?

**Comment by lexming** [comment]
I'll try to change the target branch to see if that helps...

**Comment by branfosj** [comment]
Finally I've got this to report back correctly from Travis. I'm not sure what exactly was wrong - I did force through a complete resync of the my Travis / GitHub connection, so that may have been the issue.

**Comment by lexming** [comment]
Now Travis is ok but there is a github action waiting... aghhh....
Re-triggering tests yet another time

**Comment by lexming** [comment]
Test report by @lexming
**SUCCESS**
Build succeeded for 7 out of 7 (1 easyconfigs in this PR)
node374.hydra.os - Linux centos linux 7.7.1908, Intel(R) Xeon(R) Gold 6148 CPU @ 2.40GHz, Python 2.7.5
See https://gist.github.com/8d12238d4561c28d91359a8ed4ca26b0 for a full test report.

**Comment by lexming** [comment]
Finally, merging this one before the mood of the tests changes again.

Thanks @branfosj !

**Pull request merged**
