### PR TITLE
PyTorch-1.12.1-foss-2022a-CUDA-11.7.0 fix flaky test optim test

### PR DESCRIPTION
**Pull request by VRehnberg**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by Micket** [comment]
Test report by @Micket
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
alvis3-19 - Linux Rocky Linux 8.6, x86_64, Intel(R) Xeon(R) Gold 6338 CPU @ 2.00GHz, 4 x NVIDIA NVIDIA A100-SXM4-40GB, 520.61.05, Python 3.6.8
See https://gist.github.com/Micket/ddb4cb16374bc7b6bd84b3f946627a8e for a full test report.

**Comment by boegel** [comment]
@VRehnberg Should we also add this patch to the other easyconfigs for PyTorch 1.12.1?
```
PyTorch-1.12.1-foss-2021a-CUDA-11.3.1.eb
PyTorch-1.12.1-foss-2021a.eb
PyTorch-1.12.1-foss-2021b-CUDA-11.5.2.eb
PyTorch-1.12.1-foss-2021b.eb
PyTorch-1.12.1-foss-2022a-CUDA-11.7.0.eb
PyTorch-1.12.1-foss-2022a.eb
```

**Comment by Micket** [comment]
I see no reason not to. Lets merge this first, it takes a million billion years for the test reports as usual

**Review by branfosj — APPROVED** [review]

**Comment by branfosj** [comment]
> I see no reason not to. Lets merge this first, it takes a million billion years for the test reports as usual

I agree. This is changing one test, so I am happy with the one successful test report. I'll follow up with PRs for the other easyconfigs.

**Comment by branfosj** [comment]
Going in, thanks @VRehnberg!

**Comment by boegel** [comment]
> I see no reason not to. Lets merge this first, it takes a million billion years for the test reports as usual

I agree that doing that in a single PR would have been bloody painful w.r.t. testing, that's not was I was suggesting.

Doing it in separate PRs like @branfosj is the other extreme, but it doesn't hurt either. Good for PR stats, that's for sure. ;P

**Comment by branfosj** [comment]
See #17737 - this change looks to be causing issues with other tests in test optim.

**Pull request merged**
