### PR TITLE
{phys}[foss/2022a] BerkeleyGW v3.1.0

### PR DESCRIPTION
**Pull request by migueldiascosta**
(created using `eb --new-pr`)

edit 1: converted to draft because the tarball isn't available at https://files.berkeleygw.org/BerkeleyGW-3.1.0.tar.gz yet (as https://files.berkeleygw.org/BerkeleyGW-3.0.1.tar.gz is), only via https://app.box.com/s/2bik75lrs85zt281ydbup2xa7i5594gy, which requires a manual step...

edit 2: replacing `/s/` with `/shared/static/` and adding the `.gz` extension to the url (e.g. in this case https://app.box.com/shared/static/2bik75lrs85zt281ydbup2xa7i5594gy.gz) allows direct download

requires (not really, but it helps)
- [x] https://github.com/easybuilders/easybuild-easyblocks/pull/2950

### CODE REVIEW

**Comment by migueldiascosta** [comment]
@boegelbot please test @ generoso

**Comment by migueldiascosta** [comment]
@boegelbot please test @ jsc-zen2  EB_ARGS="--include-easyblocks-from-pr 2836"

**Comment by migueldiascosta** [comment]
@boegelbot please test @ generoso EB_ARGS="--include-easyblocks-from-pr 2836"

**Comment by migueldiascosta** [comment]
@boegelbot please test @ jsc-zen2 EB_ARGS="--include-easyblocks-from-pr 2836"

**Comment by akesandgren** [comment]
Test report by @akesandgren
Using easyblocks from PR(s) https://github.com/easybuilders/easybuild-easyblocks/pull/2950
**SUCCESS**
Build succeeded for 3 out of 3 (2 easyconfigs in total)
b-an02.hpc2n.umu.se - Linux Ubuntu 20.04, x86_64, Intel(R) Xeon(R) CPU E5-2690 v4 @ 2.60GHz, Python 3.8.10
See https://gist.github.com/akesandgren/de7d8225f5741333a073e2d67c5c0aa5 for a full test report.

**Comment by akesandgren** [comment]
Going in, thanks @migueldiascosta!

**Pull request merged**
