### PR TITLE
{lib,perf}[intel/2018a] mympingpong v0.8.0, mpi4py v3.0.0

### PR DESCRIPTION
**Pull request by boegel**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by boegel** [comment]
Test report by @boegel
**FAILED**
Build succeeded for 1 out of 2 (2 easyconfigs in this PR)
node2057.delcatty.os - Linux centos linux 7.4.1708, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.7.5
See https://gist.github.com/5abc7b98bd497176831dcfeb9bbdc232 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in this PR)
gligar03.gligar.os - Linux centos linux 7.4.1708, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.7.5
See https://gist.github.com/f102fc0fbececd9ad317fbb3d8b0220c for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 5 out of 5 (2 easyconfigs in this PR)
node2530.golett.os - Linux centos linux 7.4.1708, Intel(R) Xeon(R) CPU E5-2680 v3 @ 2.50GHz, Python 2.7.5
See https://gist.github.com/ce054df579adb1b8c077c4ac814bdc75 for a full test report.

**Comment by verdurin** [comment]
@boegel sanity check error:
```
== 2018-06-10 08:55:59,725 build_log.py:158 ERROR EasyBuild crashed with an error (at ?:124 in __init__): Sanity check failed: sanity check command python -c 'import Tkinter' exited with code 1 (output: Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/well/rescomp/eb/software/Python/2.7.14-intel-2018a/lib/python2.7/lib-tk/Tkinter.py", line 39, in <module>
    import _tkinter # If this fails your Python may not be configured for Tk
ImportError: /well/rescomp/eb/software/Tkinter/2.7.14-intel-2018a-Python-2.7.14/lib/python2.7/_tkinter.so: undefined symbol: PyUnicodeUCS4_DecodeUTF8
```

**Comment by verdurin** [comment]
Test report by @verdurin
**FAILED**
Build succeeded for 7 out of 10 (2 easyconfigs in this PR)
rescomp2 - Linux centos 6.8, Intel(R) Xeon(R) CPU E5-2650 v2 @ 2.60GHz, Python 2.7.14
See https://gist.github.com/aac4eb186d95a3a823ccb422c7fd648e for a full test report.

**Comment by boegel** [comment]
@verdurin That's... strange.

That issue is supposed to handled by https://github.com/easybuilders/easybuild-easyblocks/pull/817, which was incuded in EasyBuild v2.7.0... Can you check which `--enable-unicode` was used to install `Python`?

**Comment by boegel** [comment]
@verdurin Can you confirm that the problem you ran into shouldn't block this PR?

Maybe open a dedicated issue for that problem?

**Comment by verdurin** [comment]
@boegel Itwas compiled with `--enable-unicode=ucs2`

**Comment by verdurin** [comment]
Test report by @verdurin
**SUCCESS**
Build succeeded for 1 out of 1 (2 easyconfigs in this PR)
rescomp2 - Linux centos 6.8, Intel(R) Xeon(R) CPU E5-2650 v2 @ 2.60GHz, Python 2.7.10
See https://gist.github.com/1336a81486c5c49a2a67b2836a766617 for a full test report.

**Pull request merged**
