### PR TITLE
{cae}[foss/2019b] OpenFOAM v7 (20200508)

### PR DESCRIPTION
**Pull request by boegel**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
node3105.skitty.os - Linux centos linux 7.7.1908, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz, Python 3.6.8
See https://gist.github.com/851ab4928f3d3b8fac78c03897bd1a65 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
node2479.golett.os - Linux centos linux 7.7.1908, Intel(R) Xeon(R) CPU E5-2680 v3 @ 2.50GHz, Python 2.7.5
See https://gist.github.com/fdde28a7d24b68edc0a747fc7c7927e2 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
generoso-3 - Linux centos linux 7.6.1810, Intel(R) Xeon(R) CPU E5-2660 v4 @ 2.00GHz, Python 3.6.8
See https://gist.github.com/358bed3f096bbb6e7331c1eb8d8cff38 for a full test report.

**Comment by furstj** [comment]
Test report by @furstj
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
thinkpad - Linux UNKNOWN UNKNOWN, Intel(R) Core(TM) i5-6200U CPU @ 2.30GHz, Python 3.6.10
See https://gist.github.com/8befdf1c11e8ec2c76ace466d21afc7c for a full test report.

**Comment by lexming** [comment]
@boegel  what are the advantages of this unreleased OpenFOAM v7 compared to the standard release?

**Comment by furstj** [comment]
@lexming  this is an official patch release, see https://openfoam.org/news/v7-patch/. The patched version should resolve bug https://bugs.openfoam.org/view.php?id=3389 and issues mesh refinement with snappyHexMesh.

**Comment by lexming** [comment]
@furstj thanks for the clarification! I was not aware of those patched releases.

Looking at the patch releases I see that the last one listed in their website is `20200120`, which links to a tagged tree in Github (https://github.com/OpenFOAM/OpenFOAM-7/releases/tag/20200120 based on commit https://github.com/OpenFOAM/OpenFOAM-7/commit/1ff648926f779ed561f5e40b1c5b51dee1178f57). However, there is no tag for `20200206`. Shouldn't we stick to a known tag instead of picking the last commit in `master`. I'm afraid that this will confuse our users and we might get requests for the listed patch releases.

**Comment by furstj** [comment]
@lexming You are right! I didn't notice that it is a different tag! I think that we should rather stay at officially released patch 20200120.  @boegel what is your opinion?

**Comment by boegel** [comment]
I've updated this to the latest tag for OpenFOAM 7 (20200508)...

**Comment by boegel** [comment]
Test report by @boegel
**FAILED**
Build succeeded for 0 out of 1 (1 easyconfigs in this PR)
node3410.kirlia.os - Linux centos linux 7.8.2003, x86_64, Intel(R) Xeon(R) Gold 6240 CPU @ 2.60GHz (cascadelake), Python 2.7.5
See https://gist.github.com/238bfe193d86620d0edaa01d5a49c1bb for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
node3410.kirlia.os - Linux centos linux 7.8.2003, x86_64, Intel(R) Xeon(R) Gold 6240 CPU @ 2.60GHz (cascadelake), Python 2.7.5
See https://gist.github.com/96914af5cd830e20bc3c93daf13c5f37 for a full test report.

**Comment by lexming** [comment]
Test report by @lexming
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
node381.hydra.os - Linux centos linux 7.7.1908, x86_64, Intel(R) Xeon(R) Gold 6148 CPU @ 2.40GHz, Python 2.7.5
See https://gist.github.com/d3c77c93b0f90f1307e08521937e14f4 for a full test report.

**Comment by lexming** [comment]
Going in, thanks @boegel !

**Pull request merged**
