### PR TITLE
{numlib,phys}[GCC/10.2.0] Geant4 v10.7.1, CLHEP v2.4.4.0

### PR DESCRIPTION
**Pull request by bedroge**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by bedroge** [comment]
Test report by @bedroge
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in total)
pg-interactive.hpc.rug.nl - Linux centos linux 7.9.2009, x86_64, Intel(R) Xeon(R) CPU E5-2680 v3 @ 2.50GHz, Python 3.6.8
See https://gist.github.com/836adb113665d09534eae3b5f7f8ed3b for a full test report.

**Comment by migueldiascosta** [comment]
@boegelbot please test @ generoso

**Comment by migueldiascosta** [comment]
@bedroge can´t this be moved down to GCC level?

**Comment by bedroge** [comment]
I just updated the most recent easyconfig to this version, but I think you're right that it should be possible to use GCC instead of foss. I'll test it, and update the PR.

**Comment by bedroge** [comment]
@migueldiascosta done, seems to work fine.

**Comment by migueldiascosta** [comment]
@boegelbot please test @ generoso

**Review by migueldiascosta — APPROVED** [review]
lgtm

**Comment by migueldiascosta** [comment]
Going in, thanks @bedroge!

**Pull request merged**
