### PR TITLE
{lib}[foss/2022a] Optax v0.1.7

### PR DESCRIPTION
**Pull request by smoors**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by smoors** [comment]
@boegelbot: please test @ generoso

**Comment by smoors** [comment]
@boegelbot please test @ jsc-zen2

**Comment by akesandgren** [comment]
Both dm-haiku and dm-tree exists as standalone easyconfigs, any particular reason you didn't choose to keep them as such?

**Comment by smoors** [comment]
no special reason, i just copied this from alphafold.
i'll use separate easyconfigs for them, no problem

**Comment by akesandgren** [comment]
@boegelbot Please test @ generoso

**Comment by akesandgren** [comment]
So this is the non-CUDA version apparently, does it have a CUDA version?

**Comment by smoors** [comment]
> So this is the non-CUDA version apparently, does it have a CUDA version?

optax itself not, but of course the underlying jax library can use cuda.
should be fairly easy to add a cuda version too, but the user doesn't need it (yet), and i don't really have time to test it.

**Comment by akesandgren** [comment]
Ok, just checking.

**Review by akesandgren — APPROVED** [review]
LGTM

**Pull request merged**
