### PR TITLE
{bio}[foss/2018a] Biopython v1.71 w/ Python 3.6.4

### PR DESCRIPTION
**Pull request by timeu**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
node2602.swalot.os - Linux centos linux 7.4.1708, Intel(R) Xeon(R) CPU E5-2660 v3 @ 2.60GHz, Python 2.7.5
See https://gist.github.com/4a61a5a40fc024c10f796ece38e50552 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
gligar02.gligar.os - Linux centos linux 7.4.1708, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.7.5
See https://gist.github.com/ca455b61f2b74827e6a2d608b5bb68b6 for a full test report.

**Comment by timeu** [comment]
@boegel : I need to close this PR because this is a dependency for [HiCExplorer](https://github.com/deeptools/HiCExplorer) for which @ebirn will submit a separate PR with both easyconfig files

**Comment by boegel** [comment]
@timeu Well, that's not a reason to close this PR, I was about to merge it... :)

If one PR depends on another, just mention this in the PR description, and don't worry too much about failing tests because of missing dependencies, we can re-trigger the tests after PRs that provide dependencies got merged.

**Comment by timeu** [comment]
Sorry ;-) Re-oped it.

**Comment by boegel** [comment]
Going in, thanks @timeu!

**Pull request merged**
