### PR TITLE
{bio}[intel/2016b] QIIME v1.9.1 (WIP)

### PR DESCRIPTION
**Pull request by boegel**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by boegel** [comment]
@verdurin, @RvDijk 

* WIP PR for scikit-bio dep: #3996
* WIP PR for emperor dep: #3997 (requires #3996)
* PR for matplotlib 1.4.3 dep: #3998

**Comment by RvDijk** [comment]
@boegel I'm not so sure about why matplotlib has to be version 1.4.3. E.g. pip install qiime shows that the version of matplotlib only has these requirements:
`Requirement already satisfied (use --upgrade to upgrade): matplotlib!=1.4.2,>=1.1.0 in /software/software/matplotlib/1.5.1-foss-2016a-Python-2.7.11-freetype-2.6.3/lib/python2.7/site-packages/matplotlib-1.5.1-py2.7-linux-x86_64.egg (from qiime)`

**Comment by boegel** [comment]
@RvDijk I don't see a good reason for it either, but it's explicitly specified at https://github.com/biocore/qiime/blob/master/setup.py#L437

**Comment by boegel** [comment]
@RvDijk seems like this was done for compatibility with numpy 1.9.2, see https://github.com/biocore/qiime/commit/e8ca44503438f884efea6e9d621eefcf2227298a

**Comment by boegel** [comment]
No longer relevant, QIIME 1.x has been superseded by QIIME 2 (see http://qiime.org/)

**Pull request closed without merging**
