### PR TITLE
{tools}[foss/2020b, fosscuda/2020b] nanomax-analysis-utils 0.4.3

### PR DESCRIPTION
**Pull request by jhein32**
Version update to existing nanomax-analysis-utils

### CODE REVIEW

**Comment by lexming** [comment]
Test report by @lexming
**FAILED**
Build succeeded for 10 out of 16 (7 easyconfigs in total)
node201.hydra.os - Linux centos linux 7.9.2009, x86_64, Intel(R) Xeon(R) CPU E5-2680 v4 @ 2.40GHz, Python 2.7.5
See https://gist.github.com/106c7e0c8f538a8052a5acedfb0fae5b for a full test report.

**Comment by jhein32** [comment]
> Test report by @lexming **FAILED** Build succeeded for 10 out of 16 (7 easyconfigs in total) node201.hydra.os - Linux centos linux 7.9.2009, x86_64, Intel(R) Xeon(R) CPU E5-2680 v4 @ 2.40GHz, Python 2.7.5 See https://gist.github.com/106c7e0c8f538a8052a5acedfb0fae5b for a full test report.

@lexming Hi Alex, 

Thanks for looking into this.   As far as I can make out, it fails to build clang, which isn't in my PR.   How do we progress this?  Anything we need should do to help it?   

Best wishes
    Joachim

**Comment by lexming** [comment]
Test report by @lexming
**SUCCESS**
Build succeeded for 7 out of 7 (7 easyconfigs in total)
node200.hydra.os - Linux centos linux 7.9.2009, x86_64, Intel(R) Xeon(R) CPU E5-2680 v4 @ 2.40GHz, Python 2.7.5
See https://gist.github.com/0fe0366381ac31a37daa5c07d7a6a8c4 for a full test report.

**Review by lexming — APPROVED** [review]
@jhein32 no problem, I fixed my tests :slightly_smiling_face: 

LGTM

**Comment by lexming** [comment]
Going in, thanks @jhein32 !

**Pull request merged**
