### PR TITLE
fix source URL for segemehl 0.3.4

### PR DESCRIPTION
**Pull request by boegel**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by boegel** [comment]
@boegelbot please test @ generoso
EB_ARGS="--sourcepath /tmp/$USER/pr18878"

**Comment by boegel** [comment]
@boegelbot please test @ jsc-zen2
EB_ARGS="--sourcepath /tmp/$USER/pr18878 segemehl-0.3.4-GCC-10.2.0.eb segemehl-0.3.4-GCC-10.3.0.eb segemehl-0.3.4-GCC-11.2.0.eb segemehl-0.3.4-GCC-8.3.0.eb"

**Review by SebastianAchilles — APPROVED** [review]
lgtm

**Comment by SebastianAchilles** [comment]
Going in, thanks @boegel!

**Pull request merged**
