### PR TITLE
{bio}[GCCcore/11.2.0,foss/2021b] cimfomfa v22.273, MCL v22.282, VirSorter v1.0.6, VirSorter2 v2.2.4

### PR DESCRIPTION
**Pull request by SethosII**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by casparvl** [comment]
@SethosII : the reason the CI is failing is that your `VirSorter-1.0.6-foss-2021b.eb` uses MUSCLE version `5.1` as a dependency, whereas in that toolchain, we already use MUSCLE version `3.8.31` (for `Trycycler-0.5.3-foss-2021b.eb`). Typically, we do not allow mixing different versions of dependencies in the same toolchain, as it would lead to a situation where the modules that have these dependencies (in this case VirSorter 1.0.6 and Trycycler 0.5.3) can not be loaded simultaneously.

The exception to the rule is if your software really is not compatible with the version of MUSCLE that was already used in this toolchain _or_ if there is a (proven) performance benefit to using a newer version. In that case, you can force the CI to make an exception for `VirSorter` [here](https://github.com/easybuilders/easybuild-easyconfigs/blob/313ed74c71ddc7a0605711efb6bda49190d5b5ff/test/easyconfigs/easyconfigs.py#L498). You'd add `MUSCLE` as the key, and set of the MUSCLE version and VirSorter easyconfig name as value (see the other examples there).

The same issue applies to the `snakemake` version you use as dependency by the way.

**Comment by SethosII** [comment]
@casparvl Thank you for the hint. I just took the latest versions available in the toolchain. I changed them now.

**Comment by casparvl** [comment]
@boegelbot please test @ generoso

**Comment by casparvl** [comment]
@boegelbot please test @ jsc-zen2

**Comment by casparvl** [comment]
@boegelbot please test @ generoso

**Review by casparvl — APPROVED** [review]
Lgtm!

**Comment by casparvl** [comment]
Going in, thanks @SethosII!

**Comment by casparvl** [comment]
Test report by @casparvl
**SUCCESS**
Build succeeded for 14 out of 14 (4 easyconfigs in total)
tcn1.local.snellius.surf.nl - Linux RHEL 8.6, x86_64, AMD EPYC 7H12 64-Core Processor, Python 3.6.8
See https://gist.github.com/casparvl/c698a44653a613cc699d177477939b35 for a full test report.

**Pull request merged**
