### PR TITLE
{lang,math}[GCCcore/13.2.0,gfbf/2023b] E-ANTIC v2.0.2, cppyy v3.1.2

### PR DESCRIPTION
**Pull request by PetrKralCZ**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by PetrKralCZ** [comment]
@boegelbot please test @ generoso

**Comment by PetrKralCZ** [comment]
@boegelbot please test @ jsc-zen3

**Review by migueldiascosta — APPROVED** [review]
lgtm

**Comment by migueldiascosta** [comment]
Going in, thanks @PetrKralCZ!

**Pull request merged**
