### PR TITLE
remove PYPI_SOURCE source URL from easyconfigs using GCC(core) 9.3.0 or 10.2.0 as toolchain

### PR DESCRIPTION
**Pull request by Flamefire**
This is no longer required as it became the default with easybuilders/easybuild-easyblocks#2364

Tests should (and mine were) be done with e.g. `eb --from-pr 12453 --rebuild --fetch --force-download --sourcepath=/dev/shm/sources --upload-test-report` to only test the download and of course with latest develop easyblocks

### CODE REVIEW

**Comment by Flamefire** [comment]
Test report by @Flamefire
**FAILED**
Build succeeded for 55 out of 59 (59 easyconfigs in total)
taurusa4 - Linux centos linux 7.7.1908, x86_64, Intel(R) Xeon(R) CPU E5-2603 v4 @ 1.70GHz (broadwell), Python 2.7.5
See https://gist.github.com/364af1eff1239a703b0f57368a70784f for a full test report.

**Comment by Flamefire** [comment]
Test report by @Flamefire
**SUCCESS**
Build succeeded for 55 out of 55 (55 easyconfigs in total)
taurusa4 - Linux centos linux 7.7.1908, x86_64, Intel(R) Xeon(R) CPU E5-2603 v4 @ 1.70GHz (broadwell), Python 2.7.5
See https://gist.github.com/f90de02d4b889c645316381ab252d41d for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 54 out of 54 (54 easyconfigs in total)
node3157.skitty.os - Linux centos linux 7.9.2009, x86_64, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz, Python 3.6.8
See https://gist.github.com/ccd893e4449b7ed558b2eb7022cc0ee6 for a full test report.

**Review by boegel — APPROVED** [review]
lgtm

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 54 out of 54 (54 easyconfigs in total)
node3543.doduo.os - Linux RHEL 8.2, x86_64, AMD EPYC 7552 48-Core Processor (zen2), Python 3.6.8
See https://gist.github.com/62c9aeeebfc0f306bb8667ec35598c3a for a full test report.

**Comment by boegel** [comment]
Going in, thanks @Flamefire!

**Pull request merged**
