### PR TITLE
{bio}[intel/2018a] dxpy v0.266.1 w/ Python 2.7.14

### PR DESCRIPTION
**Pull request by boegel**
(created using `eb --new-pr`)
requires ~https://github.com/easybuilders/easybuild-easyblocks/pull/1553~ (PythonBundle easyblock) + ~#7078~ (FUSE)

### CODE REVIEW

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
node2070.delcatty.os - Linux centos linux 7.5.1804, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.7.5
See https://gist.github.com/545ac6945eaef908c56f64a90510fed4 for a full test report.

**Comment by migueldiascosta** [comment]
closing/reopening to retrigger travis

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 2 out of 2 (1 easyconfigs in this PR)
node2490.golett.os - Linux centos linux 7.6.1810, Intel(R) Xeon(R) CPU E5-2680 v3 @ 2.50GHz, Python 2.7.5
See https://gist.github.com/ca02185432dd8a81aef1b4b8cc7b313e for a full test report.

**Comment by migueldiascosta** [comment]
Going in, thanks @boegel!

**Pull request merged**
