### PR TITLE
{bio}[GCCcore/12.2.0] Gubbins v3.3.5, rapidNJ v2.3.3, FastTree v2.1.11, ...

### PR DESCRIPTION
**Pull request by verdurin**
- [x] #20410 
- [x] #20411
- [x] #20412

### CODE REVIEW

**Comment by verdurin** [comment]
@boegelbot please test @ generoso

**Comment by verdurin** [comment]
@boegelbot please test @ jsc-zen3

**Comment by bedroge** [comment]
Test report by @bedroge
**SUCCESS**
Build succeeded for 5 out of 5 (5 easyconfigs in total)
node2 - Linux Rocky Linux 8.9, x86_64, AMD EPYC 7763 64-Core Processor (zen3), Python 3.6.8
See https://gist.github.com/bedroge/1ca2d395732b2bb2246358c9f01181d4 for a full test report.

**Review by bedroge — APPROVED** [review]
Looks good to me.

**Comment by bedroge** [comment]
Going in, thanks @verdurin!

**Pull request merged**
