### PR TITLE
{math}[foss/2018b] PETSc 3.11.0, SLEPc 3.11.0, gmsh 3.0.6, gmsh 4.2.2

### PR DESCRIPTION
**Pull request by jhein32**
Easyconfigs required to provide gmsh in foss/2018b.  This includes PETSc 3.11.0 and SLEPc 3.11.0

### CODE REVIEW

**Comment by jhein32** [comment]
Python support in gmsh 4 is very different from gmsh 3.  Sanity checks and PYTHON_PATH need fixing for that!  -> work in progress (WIP)

**Comment by jhein32** [comment]
This builds, passes the EB checks.  I checked I can import the python bindings of gmsh 4.2.2 into Python.  Please review and merge.

**Comment by zao** [comment]
Test report by @zao
**SUCCESS**
Build succeeded for 6 out of 6 (4 easyconfigs in this PR)
freja - Linux ubuntu 18.04, AMD Ryzen 7 1700 Eight-Core Processor, Python 2.7.15rc1
See https://gist.github.com/ab034be2198a644b7061efc0070538a1 for a full test report.

**Comment by smoors** [comment]
Test report by @smoors
**SUCCESS**
Build succeeded for 5 out of 5 (4 easyconfigs in this PR)
nic424 - Linux centos linux 7.5.1804, Intel(R) Xeon(R) Gold 6148 CPU @ 2.40GHz, Python 2.7.5
See https://gist.github.com/1ef4d496dfcd45841f1b051a1dbf8201 for a full test report.

**Comment by smoors** [comment]
Going in, thanks @jhein32!

**Pull request merged**
