### PR TITLE
fix the libxml2 dependency (like #13030) which was broken due to #11065

### PR DESCRIPTION
**Pull request by sdx23**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by sdx23** [comment]
Sorry, I'm apparently not familiar enough with --new-pr yet. The commit message should have been

GDAL-3.2.1-foss-2020b - fix libxml2 dependency

I guess.

**Comment by verdurin** [comment]
Test report by @verdurin
**SUCCESS**
Build succeeded for 0 out of 0 (1 easyconfigs in total)
nuc.lan - Linux Fedora 33, x86_64, Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz, Python 3.9.5
See https://gist.github.com/38e370d0b43e964b4b9fd77fb85e917f for a full test report.

**Comment by verdurin** [comment]
Test report by @verdurin
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
easybuild-c7.novalocal - Linux centos linux 7.9.2009, x86_64, Intel Xeon Processor (Skylake, IBRS), Python 3.6.8
See https://gist.github.com/5fde8311652956fa23fdde16d9d8f5ba for a full test report.

**Comment by verdurin** [comment]
Test report by @verdurin
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
nuc.lan - Linux Fedora 33, x86_64, Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz, Python 3.9.5
See https://gist.github.com/c2b53ed4a103a1ddcb33186b0babd93a for a full test report.

**Comment by verdurin** [comment]
@boegelbot please test @ generoso

**Review by Micket — APPROVED** [review]
lgtm

**Comment by Micket** [comment]
Test report by @Micket
**SUCCESS**
Build succeeded for 9 out of 9 (1 easyconfigs in total)
alvis-c1 - Linux centos linux 7.9.2009, x86_64, Intel Xeon Processor (Skylake), Python 3.6.8
See https://gist.github.com/371183cfc8465b6a0c56f2ef65a69864 for a full test report.

**Comment by Micket** [comment]
Going in, thanks @sdx23!

**Pull request merged**
