### PR TITLE
Fix patch name in Perl-bundle-CPAN-5.36.1-GCCcore-12.3.0 and add to GCCcore-13.2.0 version

### PR DESCRIPTION
**Pull request by Flamefire**
Followup to #20536

### CODE REVIEW

**Comment by Flamefire** [comment]
@Micket This could be merged without test reports as the patch is just renamed and used only in that file and in the other the test is (currently) not run. Just did that for possible future updates

**Review by Micket — APPROVED** [review]
lgtm

**Review by Micket — APPROVED** [review]
lgtm

**Comment by Flamefire** [comment]
Why doesn't CI start?

**Comment by Micket** [comment]
Tried a eb --sync-pr now, but it doesn't seem to have woken anything up. I don't know

**Comment by Flamefire** [comment]
The sync doesn't seem to do anything, likely nothing new in develop

I pushed again (taking the opportunity to fix the commits) and it seems to start

**Pull request merged**
