### PR TITLE
re-enable building utils in Siesta 4.1-MaX-1.0 release

### PR DESCRIPTION
**Pull request by migueldiascosta**
(created using `eb --new-pr`)

requires https://github.com/easybuilders/easybuild-easyblocks/pull/1973

### CODE REVIEW

**Comment by migueldiascosta** [comment]
Test report by @migueldiascosta
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in this PR)
sms - Linux centos linux 7.6.1810, AMD EPYC 7601 32-Core Processor, Python 2.7.5
See https://gist.github.com/54c3199576b725aece4bb5b65017eed8 for a full test report.

**Comment by verdurin** [comment]
@migueldiascosta Even with the new easyblock, I see this error when I try to build:
```
 eb --from-pr=9936 --debug --robot --upload-test-report --include-easyblocks=siesta.py
== temporary log file in case of crash /tmp/eb-NmuTYW/easybuild-AvDI3r.log
== resolving dependencies ...
ERROR: Failed to process easyconfig /home/software/src/github/easybuild-easyconfigs/easybuild/easyconfigs/e/ELSI/ELSI-2.5.0-intel-2019b-PEXSI.eb: No software-specific easyblock 'EB_ELSI' found for ELSI
```

Is it relying on something else too?

**Comment by migueldiascosta** [comment]
@verdurin yes, the original PR for those easyconfigs also required https://github.com/easybuilders/easybuild-easyblocks/pull/1883

it seems you're using an up-to-date easyconfigs develop branch but not the easyblocks one?

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in this PR)
node3138.skitty.os - Linux centos linux 7.7.1908, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz, Python 3.6.8
See https://gist.github.com/2df310971538c84ad132f8794f1e04e2 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in this PR)
node2410.golett.os - Linux centos linux 7.7.1908, Intel(R) Xeon(R) CPU E5-2680 v3 @ 2.50GHz, Python 2.7.5
See https://gist.github.com/0682c65eba6c970ea2a1841738b4562e for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in this PR)
generoso - Linux centos linux 7.6.1810, Intel(R) Xeon(R) CPU E5-2660 v4 @ 2.00GHz, Python 3.6.8
See https://gist.github.com/46150ec4cf5e5a4932d4e8eaef4389d1 for a full test report.

**Comment by boegel** [comment]
Going in, thanks @migueldiascosta!

**Pull request merged**
