### PR TITLE
add -GCCcore-9.2.0 versionsuffix for intel/2020.00 components

### PR DESCRIPTION
**Pull request by boegel**
(wrapper PR for #10082, cc @bartoldeman)

### CODE REVIEW

**Comment by akesandgren** [comment]
Test report by @akesandgren
**FAILED**
Build succeeded for 3 out of 4 (4 easyconfigs in this PR)
b-an04.hpc2n.umu.se - Linux ubuntu 16.04, Intel(R) Xeon(R) CPU E5-2690 v4 @ 2.60GHz, Python 2.7.12
See https://gist.github.com/658c76165bc4246675fb85708043e73d for a full test report.

**Comment by boegel** [comment]
@akesandgren Something is funky with your existing `imkl/2020.0.166` module?

You better to a forced reinstall of that too btw, to make sure the FFTW wrappers get built with GCC 9.3

**Comment by akesandgren** [comment]
It's a module load problem...

**Comment by akesandgren** [comment]
For some reason it hadn't built imkl-2020.0.166-iimpi-2020.00.eb as far as I could see

**Comment by akesandgren** [comment]
Ahh, the installpath for the above imkl is: MPI/intel/2020.0.166/impi/2019.6.166/imkl/2020.0.166
which collides with the one for 2020a

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 4 out of 4 (4 easyconfigs in this PR)
node2409.golett.os - Linux centos linux 7.7.1908, Intel(R) Xeon(R) CPU E5-2680 v3 @ 2.50GHz, Python 2.7.5
See https://gist.github.com/40fd281b2bc43cf2dab196fecbb61fb6 for a full test report.

**Comment by akesandgren** [comment]
Test report by @akesandgren
**SUCCESS**
Build succeeded for 5 out of 5 (5 easyconfigs in this PR)
b-an04.hpc2n.umu.se - Linux ubuntu 16.04, Intel(R) Xeon(R) CPU E5-2690 v4 @ 2.60GHz, Python 2.7.12
See https://gist.github.com/d8692c80a1b720cb6290a01280ce8e5e for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**FAILED**
Build succeeded for 1 out of 4 (4 easyconfigs in this PR)
generoso-1 - Linux centos linux 7.6.1810, Intel(R) Xeon(R) CPU E5-2660 v4 @ 2.00GHz, Python 3.6.8
See https://gist.github.com/5d31b8abbde062127532eb6b0086f4ba for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**FAILED**
Build succeeded for 3 out of 4 (4 easyconfigs in this PR)
generoso-3 - Linux centos linux 7.6.1810, Intel(R) Xeon(R) CPU E5-2660 v4 @ 2.00GHz, Python 3.6.8
See https://gist.github.com/9c7e821598a655bf7814edb4c7f3a5ba for a full test report.

**Comment by smoors** [comment]
Going in, thanks @boegel!

**Pull request merged**
