### PR TITLE
{devel}[foss/2020b,fosscuda/2020b] PyTorch v1.9.0 w/ Python 3.8.6

### PR DESCRIPTION
**Pull request by Flamefire**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by branfosj** [comment]
I've set off a test reports.

I did an initial test of the `foss` version, but forgot the upload test report option. In that I saw the `test_lstm` failure in `test_quantization.py`. Originally reported at https://github.com/pytorch/pytorch/issues/43209 and now being tracked in https://github.com/pytorch/pytorch/issues/59098

**Comment by terjekv** [comment]
Test report by @terjekv
**FAILED**
Build succeeded for 1 out of 3 (2 easyconfigs in total)
ninhursaga.uio.no - Linux RHEL 8.4, x86_64, Intel(R) Xeon(R) Silver 4216 CPU @ 2.10GHz (cascadelake), Python 3.6.8
See https://gist.github.com/c93ed8c226efc0af6100ce7e466864ba for a full test report.

**Comment by Flamefire** [comment]
Test report by @Flamefire
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in total)
taurusi8006 - Linux centos linux 7.9.2009, x86_64, AMD EPYC 7352 24-Core Processor (zen2), Python 2.7.5
See https://gist.github.com/372465a746dbc9a8dc00d7d02e37e1fa for a full test report.

**Comment by branfosj** [comment]
Test report by @branfosj
**FAILED**
Build succeeded for 0 out of 1 (1 easyconfigs in total)
bask-pg0309u35a - Linux RHEL 8.4, x86_64, Intel(R) Xeon(R) Platinum 8360Y CPU @ 2.40GHz (icelake), Python 3.6.8
See https://gist.github.com/4ce9516a3230068dccd42e05e7ced77d for a full test report.

**Comment by branfosj** [comment]
Test report by @branfosj
**FAILED**
Build succeeded for 0 out of 1 (1 easyconfigs in total)
bask-pg0308u26a - Linux RHEL 8.4, x86_64, Intel(R) Xeon(R) Platinum 8360Y CPU @ 2.40GHz (icelake), Python 3.6.8
See https://gist.github.com/7811093d15e69fe464776610699113a2 for a full test report.

**Comment by Flamefire** [comment]
Test report by @Flamefire
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in total)
taurusa7 - Linux centos linux 7.7.1908, x86_64, Intel(R) Xeon(R) CPU E5-2603 v4 @ 1.70GHz (broadwell), Python 2.7.5
See https://gist.github.com/733a75f2298a514349e847d491177819 for a full test report.

**Comment by Flamefire** [comment]
@branfosj Thanks for the reminder. Don't really have a Cascadelake machine easily available. I added a patch to skip that test. Can you try that?

@terjekv Something seems odd with your build machine:
> RuntimeError: In operator() at tensorpipe/common/ibv.h:151 "": Cannot allocate memory
> distributed/pipeline/sync/test_transparency.py::test_simple_linears libi40iw-i40iw_ucreate_cq: failed to pin memory for CQ

**Comment by terjekv** [comment]
I don't quite understand how. The machine monitoring suggests that free memory never dropped under 30GB or so. Could we see a spike eat that? :(

**Comment by Flamefire** [comment]
> I don't quite understand how

@terjekv No idea. But seems to be related to Infiniband. It is a call to `ibv_create_cq` which fails (in one case) which is dynamically loaded from libibverbs.so.1

Maybe just a fluke?

**Comment by terjekv** [comment]
I hope so. It could be IB stuff on RHEL8 causing issues? Rerunning stuff to see.

**Comment by Flamefire** [comment]
> Same error. Kinda iffy. The box does not have any IB hardware, but has:

Then that is maybe just unsupported. Please open an issue in the pytorch repo to get them to clarify that.

**Comment by verdurin** [comment]
Test report by @verdurin
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
easybuild-c7.novalocal - Linux centos linux 7.9.2009, x86_64, Intel Xeon Processor (Skylake, IBRS), Python 3.6.8
See https://gist.github.com/ce6e347ad636a9e190afb1d95419d2ce for a full test report.

**Comment by terjekv** [comment]
Test report by @terjekv
**FAILED**
Build succeeded for 0 out of 2 (2 easyconfigs in total)
ninhursaga.uio.no - Linux RHEL 8.4, x86_64, Intel(R) Xeon(R) Silver 4216 CPU @ 2.10GHz (cascadelake), Python 3.6.8
See https://gist.github.com/8ad20fe90fce1ef2e2054bc9b62513f7 for a full test report.

**Comment by branfosj** [comment]
Test report by @branfosj
**FAILED**
Build succeeded for 0 out of 1 (1 easyconfigs in total)
bask-pg0308u26a - Linux RHEL 8.4, x86_64, Intel(R) Xeon(R) Platinum 8360Y CPU @ 2.40GHz (icelake), Python 3.6.8
See https://gist.github.com/bbaa993d257f6103e025eacee01da4b5 for a full test report.

**Comment by branfosj** [comment]
Test report by @branfosj
**FAILED**
Build succeeded for 0 out of 1 (1 easyconfigs in total)
bask-pg0308u26a - Linux RHEL 8.4, x86_64, Intel(R) Xeon(R) Platinum 8360Y CPU @ 2.40GHz (icelake), Python 3.6.8
See https://gist.github.com/ae6843b248484549adf3a5782796db46 for a full test report.

**Comment by branfosj** [comment]
Test report by @branfosj
**FAILED**
Build succeeded for 0 out of 1 (1 easyconfigs in total)
bask-pg0308u26a - Linux RHEL 8.4, x86_64, Intel(R) Xeon(R) Platinum 8360Y CPU @ 2.40GHz (icelake), Python 3.6.8
See https://gist.github.com/6c165029fd2fa326af5ea23b03de734b for a full test report.

**Comment by branfosj** [comment]
Test report by @branfosj
**FAILED**
Build succeeded for 0 out of 1 (1 easyconfigs in total)
bask-pg0308u29a - Linux RHEL 8.4, x86_64, Intel(R) Xeon(R) Platinum 8360Y CPU @ 2.40GHz (icelake), Python 3.6.8
See https://gist.github.com/1ce6af2cdbe1afb582917f2515933542 for a full test report.

**Comment by Flamefire** [comment]
@branfosj Can you check what exactly failed there? It says still test_quantization but that part of the log is missing. And the test_lstm should be fixed...

**Comment by branfosj** [comment]
I'm confused - the failure is as before:

```
======================================================================
FAIL: test_lstm (quantization.test_backward_compatibility.TestSerialization)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/dev/shm/tmp-branfosj-admin-up/eb-se9g9n5f/tmpgv5jwrj6/lib/python3.8/site-packages/torch/testing/_internal/common_quantized.py", line 161, in test_fn
    qfunction(*args, **kwargs)
  File "/dev/shm/build-branfosj-admin-up/PyTorch/1.9.0/foss-2020b/pytorch/test/quantization/test_backward_compatibility.py", line 232, in test_lstm
    self._test_op(mod, input_size=[4, 4, 3], input_quantized=False, generate=False, new_zipfile_serialization=True)
  File "/dev/shm/build-branfosj-admin-up/PyTorch/1.9.0/foss-2020b/pytorch/test/quantization/test_backward_compatibility.py", line 77, in _test_op
    self.assertEqual(qmodule(input_tensor), expected, atol=prec)
  File "/dev/shm/tmp-branfosj-admin-up/eb-se9g9n5f/tmpgv5jwrj6/lib/python3.8/site-packages/torch/testing/_internal/common_utils.py", line 1388, in assertEqual
    self.assertEqual(x_, y_, atol=atol, rtol=rtol, msg=msg,
  File "/dev/shm/tmp-branfosj-admin-up/eb-se9g9n5f/tmpgv5jwrj6/lib/python3.8/site-packages/torch/testing/_internal/common_utils.py", line 1355, in assertEqual
    super().assertTrue(result, msg=self._get_assert_msg(msg, debug_msg=debug_msg))
AssertionError: False is not true : Tensors failed to compare as equal!With rtol=1.3e-06 and atol=1e-05, found 13 element(s) (out of 112) whose difference(s) exceeded the margin of error (including 0 nan comparisons). The greatest difference was 0.9640435565029293 (4.41188467448228e-06 vs. 0.9640479683876038), which occurred at index (3, 0, 6).

----------------------------------------------------------------------
```

**Comment by branfosj** [comment]
I'm setting off a build so I can do some debugging on why that test is not being skipped.

**Comment by Flamefire** [comment]
I didn't actually skip it but marked it as expected failure: https://github.com/easybuilders/easybuild-easyconfigs/pull/13237/commits/74c8c32c6ff15df3f85ae2432f3e4eed50d381c7#diff-de8a49a66cde6fe5e687dac5c654f196ebd0110d55a739b1f57095131f5d471cR22

Not sure why this isn't working

**Comment by Flamefire** [comment]
@branfosj Found it. Currently uploading a new patch. The mark must come first -.-

**Comment by branfosj** [comment]
> @branfosj Found it. Currently uploading a new patch. The mark must come first -.-

Thanks. I'll set off a test report.

**Comment by branfosj** [comment]
Test report by @branfosj
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
bear-pg0206u03a.bear.cluster - Linux RHEL 8.3, x86_64, Intel(R) Xeon(R) Gold 6248 CPU @ 2.50GHz (cascadelake), Python 3.6.8
See https://gist.github.com/83aabfc0ac2ec8bb05232b61e1646237 for a full test report.

**Comment by Flamefire** [comment]
Test report by @Flamefire
**FAILED**
Build succeeded for 0 out of 1 (1 easyconfigs in total)
taurusi8032 - Linux centos linux 7.9.2009, x86_64, AMD EPYC 7352 24-Core Processor (zen2), Python 2.7.5
See https://gist.github.com/34655e94e8bf78f9dafb37f20c51a827 for a full test report.

**Comment by Flamefire** [comment]
@branfosj 
> FAILED (skipped=24, unexpected successes=1)
> test_quantization failed!

I give up and skip that fucking test

**Comment by branfosj** [comment]
Test report by @branfosj
**FAILED**
Build succeeded for 0 out of 1 (1 easyconfigs in total)
bask-pg0308u29a - Linux RHEL 8.4, x86_64, Intel(R) Xeon(R) Platinum 8360Y CPU @ 2.40GHz (icelake), Python 3.6.8
See https://gist.github.com/bb1bc402bacb50ce6ece0a8cd15ddd27 for a full test report.

**Comment by branfosj** [comment]
Test report by @branfosj
**FAILED**
Build succeeded for 0 out of 1 (1 easyconfigs in total)
bask-pg0308u29a - Linux RHEL 8.4, x86_64, Intel(R) Xeon(R) Platinum 8360Y CPU @ 2.40GHz (icelake), Python 3.6.8
See https://gist.github.com/a65af269d2e7dfc2d862b0e5367a9ff5 for a full test report.

**Comment by branfosj** [comment]
Test report by @branfosj
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
bear-pg0206u03a.bear.cluster - Linux RHEL 8.3, x86_64, Intel(R) Xeon(R) Gold 6248 CPU @ 2.50GHz (cascadelake), Python 3.6.8
See https://gist.github.com/e16eb2c0e470f09b733a87fdc0c23db0 for a full test report.

**Comment by branfosj** [comment]
Test report by @branfosj
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
bber0501u03a.bb2.cluster - Linux RHEL 8.3, x86_64, Intel(R) Xeon(R) CPU E5-2690 v3 @ 2.60GHz (haswell), Python 3.6.8
See https://gist.github.com/2e48e045dd2cb324878128df27a8cfa3 for a full test report.

**Comment by Flamefire** [comment]
Test report by @Flamefire
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
taurusi8032 - Linux centos linux 7.9.2009, x86_64, AMD EPYC 7352 24-Core Processor (zen2), Python 2.7.5
See https://gist.github.com/72eb8c9b63bb015a528adf89a167ce5b for a full test report.

**Comment by branfosj** [comment]
Test report by @branfosj
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
bask-pg0308u31a - Linux RHEL 8.4, x86_64, Intel(R) Xeon(R) Platinum 8360Y CPU @ 2.40GHz (icelake), Python 3.6.8
See https://gist.github.com/50dec1b4b4112d43ffeeee7402a2ce27 for a full test report.

**Comment by branfosj** [comment]
Test report by @branfosj
**FAILED**
Build succeeded for 0 out of 1 (1 easyconfigs in total)
bask-pg0308u30a - Linux RHEL 8.4, x86_64, Intel(R) Xeon(R) Platinum 8360Y CPU @ 2.40GHz (icelake), Python 3.6.8
See https://gist.github.com/a5adcff00ca81a93de9065159d179a86 for a full test report.

**Comment by Flamefire** [comment]
@branfosj 
> distributed/test_c10d_nccl failed!

Not sure here... While I do like the option to run all tests and report failure afterwards it makes those test reports hard as the error happens way before. I think I should add some post-processing to the easyblock so it shows the actual failures

**Comment by branfosj** [comment]
The failed test was with 4 GPUs. We are back to NCCL errors:
```
terminate called after throwing an instance of 'c10::CUDAError'
  what():  CUDA error: uncorrectable NVLink error detected during the execution
```

Full output from `distributed/test_c10d_nccl`: https://gist.github.com/branfosj/fd219f55aca2e9f48c1c4cb92531afc8

**Comment by Flamefire** [comment]
Yeah but this time test_broadcast_coalesced_nccl which I haven't seen failing before. Do you use a different NCCL? Have you rebuild NCCL with that patch already (not sure if done automatically)?

**Comment by branfosj** [comment]
NCCL is `NCCL-2.8.3-GCCcore-10.2.0-CUDA-11.1.1.eb` with `NCCL-2.8.3_fix-isend-irecv.patch` - built from #13071

**Comment by Flamefire** [comment]
Hm, I can't see anything wrong with this test so I'd rather not disable it. Maybe just a fluke?
Due to the async nature of CUDA errors the stacktrace doesn't say anything about the actual source of the error.

**Comment by branfosj** [comment]
Test report by @branfosj
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
bask-pg0309u05a - Linux RHEL 8.4, x86_64, Intel(R) Xeon(R) Platinum 8360Y CPU @ 2.40GHz (icelake), Python 3.6.8
See https://gist.github.com/f3bbe8f21aaf4e1f9eb5367d78d20907 for a full test report.

**Comment by Flamefire** [comment]
Test report by @Flamefire
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in total)
taurusa7 - Linux centos linux 7.7.1908, x86_64, Intel(R) Xeon(R) CPU E5-2603 v4 @ 1.70GHz (broadwell), Python 2.7.5
See https://gist.github.com/2194f5d7b97d9714ac453f72d0b05a04 for a full test report.

**Comment by branfosj** [comment]
Test report by @branfosj
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
bask-pg0309u05a - Linux RHEL 8.4, x86_64, Intel(R) Xeon(R) Platinum 8360Y CPU @ 2.40GHz (icelake), Python 3.6.8
See https://gist.github.com/737a9bc8ec068d208504e4ddfc7f5573 for a full test report.

**Comment by branfosj** [comment]
Test report by @branfosj
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
bask-pg0309u10a - Linux RHEL 8.4, x86_64, Intel(R) Xeon(R) Platinum 8360Y CPU @ 2.40GHz (icelake), Python 3.6.8
See https://gist.github.com/609b088ae4b5075e8f2c086eba1535c6 for a full test report.

**Comment by branfosj** [comment]
> Hm, I can't see anything wrong with this test so I'd rather not disable it. Maybe just a fluke?
> Due to the async nature of CUDA errors the stacktrace doesn't say anything about the actual source of the error.

I've run using all 4 GPUs three times:
* Failure: https://github.com/easybuilders/easybuild-easyconfigs/pull/13237#issuecomment-867776557
* Pass in a run where I forgot to set upload test report
* Pass: https://github.com/easybuilders/easybuild-easyconfigs/pull/13237#issuecomment-869058827

So the first one was either a fluke failure or the test is flaky.

**Comment by Flamefire** [comment]
The test shouldn't really be flaky from what I can tell, I guess it is NCCL being the problem here. Hence I'm hesitant disabling this test. FWIW: I reran this test file 5 times without any failure.

My proposal: Include as-is and keep the potential failure as a kind of warning that pytorch might fail in the given environment.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in total)
node3159.skitty.os - Linux centos linux 7.9.2009, x86_64, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz, Python 3.6.8
See https://gist.github.com/8eea43094a796743710c9bfb5ad6d581 for a full test report.

**Review by branfosj — APPROVED** [review]
lgtm

**Comment by branfosj** [comment]
Going in, thanks @Flamefire!

**Pull request merged**
