### PR TITLE
{bio}[intel/2017b] Cufflinks v2.2.1, SAMtools v0.1.20

### PR DESCRIPTION
**Pull request by boegel**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in this PR)
node2500.golett.os - Linux centos linux 7.4.1708, Intel(R) Xeon(R) CPU E5-2680 v3 @ 2.50GHz, Python 2.7.5
See https://gist.github.com/5d4f7a09b7ce37399070699eab378bd5 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in this PR)
node2047.delcatty.os - Linux centos linux 7.4.1708, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.7.5
See https://gist.github.com/789cb1bcefebe7458bc013a2ad041ce1 for a full test report.

**Comment by verdurin** [comment]
Test report by @verdurin
**FAILED**
Build succeeded for 2 out of 3 (2 easyconfigs in this PR)
rescomp1 - Linux centos 6.8, Intel(R) Xeon(R) CPU E5-2650 v2 @ 2.60GHz, Python 2.7.14
See https://gist.github.com/fdef589b4f36311cefc873656ddeb864 for a full test report.

**Comment by boegel** [comment]
Hmm, how is this failing with Boost errors for you if it's working for me?

Maybe it's picking up Boost headers from the OS in my case? :-/

**Comment by verdurin** [comment]
Hmm, `Cufflinks` errors on `CentOS 6.8`:
```
if icpc -DHAVE_CONFIG_H -I. -I. -I..  -I../src  -I/well/rescomp/eb/software/Eigen/3.3.4/include -I/usr/include  -Wall -Wno-strict-aliasing -g -gdwarf-2 -Wunused -Wuninitialized -ftemplate-depth-1024 -m64 -march=nocona -O3 -O2 -xHost -ftz -fp-speculation=safe -fp-model source -fPIC -DNDEBUG  -pthread -I/well/rescomp/eb/software/Boost/1.65.1-intel-2017b/include   -MT sampling.o -MD -MP -MF ".deps/sampling.Tpo" -c -o sampling.o sampling.cpp; \
        then mv -f ".deps/sampling.Tpo" ".deps/sampling.Po"; else rm -f ".deps/sampling.Tpo"; exit 1; fi
icpc: command line warning #10121: overriding '-march=nocona' with '-xHost'
icpc: command line warning #10121: overriding '-march=nocona' with '-xHost'
icpc: command line warning #10121: overriding '-march=nocona' with '-xHost'
icpc: command line warning #10121: overriding '-march=nocona' with '-xHost'
icpc: command line warning #10121: overriding '-march=nocona' with '-xHost'
icpc: command line warning #10121: overriding '-march=nocona' with '-xHost'
icpc: command line warning #10121: overriding '-march=nocona' with '-xHost'
icpc: command line warning #10121: overriding '-march=nocona' with '-xHost'
icpc: command line warning #10121: overriding '-march=nocona' with '-xHost'
icpc: command line warning #10121: overriding '-march=nocona' with '-xHost'
icpc: command line warning #10121: overriding '-march=nocona' with '-xHost'
icpc: command line warning #10121: overriding '-march=nocona' with '-xHost'
icpc: command line warning #10121: overriding '-march=nocona' with '-xHost'
icpc: command line warning #10121: overriding '-march=nocona' with '-xHost'
icpc: command line warning #10121: overriding '-march=nocona' with '-xHost'
icpc: command line warning #10121: overriding '-march=nocona' with '-xHost'
In file included from ./lemon/bits/base_extender.h(23),
                 from ./lemon/smart_graph.h(30),
                 from matching_merge.h(16),
                 from matching_merge.cpp(10):
./lemon/error.h(108): warning #1478: class "std::auto_ptr<std::ostringstream>" (declared at line 87 of "/gpfs0/users/rescomp/adamh/.local/easybuild/software/GCCcore/6.4.0/bin/../include/c++/6.4.0/backward/auto_ptr.h") was declared deprecated
      std::auto_ptr<std::ostringstream> buf;
                                        ^

In file included from ./lemon/bits/base_extender.h(23),
                 from ./lemon/smart_graph.h(30),
                 from matching_merge.h(16),
                 from matching_merge.cpp(10):
./lemon/error.h(93): warning #1478: class "std::auto_ptr<std::__cxx11::string>" (declared at line 87 of "/gpfs0/users/rescomp/adamh/.local/easybuild/software/GCCcore/6.4.0/bin/../include/c++/6.4.0/backward/auto_ptr.h") was declared deprecated
      std::auto_ptr<_Type> ptr;
                           ^
          detected during instantiation of class "lemon::ExceptionMember<_Type> [with _Type=std::__cxx11::string]" at line 248

In file included from ./lemon/bits/base_extender.h(23),
                 from ./lemon/list_graph.h(26),
                 from ./lemon/dfs.h(26),
                 from ./lemon/topology.h(22),
                 from assemble.cpp(19):
./lemon/error.h(108): warning #1478: class "std::auto_ptr<std::ostringstream>" (declared at line 87 of "/gpfs0/users/rescomp/adamh/.local/easybuild/software/GCCcore/6.4.0/bin/../include/c++/6.4.0/backward/auto_ptr.h") was declared deprecated
      std::auto_ptr<std::ostringstream> buf;
                                        ^

In file included from ./lemon/bits/base_extender.h(23),
                 from ./lemon/list_graph.h(26),
                 from ./lemon/dfs.h(26),
                 from ./lemon/topology.h(22),
                 from assemble.cpp(19):
./lemon/error.h(93): warning #1478: class "std::auto_ptr<std::__cxx11::string>" (declared at line 87 of "/gpfs0/users/rescomp/adamh/.local/easybuild/software/GCCcore/6.4.0/bin/../include/c++/6.4.0/backward/auto_ptr.h") was declared deprecated
      std::auto_ptr<_Type> ptr;
                           ^
          detected during instantiation of class "lemon::ExceptionMember<_Type> [with _Type=std::__cxx11::string]" at line 248
if icc -DHAVE_CONFIG_H -I. -I. -I..  -I../src  -I/well/rescomp/eb/software/Eigen/3.3.4/include -I/usr/include  -Wall -Wno-strict-aliasing -g -gdwarf-2 -Wunused -Wuninitialized -ftemplate-depth-1024 -m64 -march=nocona -O3 -O2 -xHost -ftz -fp-speculation=safe -fp-model source -fPIC -DNDEBUG  -MT adap.o -MD -MP -MF ".deps/adap.Tpo" -c -o adap.o `test -f 'locfit/adap.c' || echo './'`locfit/adap.c; \
        then mv -f ".deps/adap.Tpo" ".deps/adap.Po"; else rm -f ".deps/adap.Tpo"; exit 1; fi
icc: command line warning #10121: overriding '-march=nocona' with '-xHost'
locfit/adap.c(29): warning #593: variable "p" was set but never used
  { int i, ii, j, p, p1;
                  ^

locfit/adap.c(157): warning #593: variable "d" was set but never used
    INT i, i0, d, n;
               ^

locfit/adap.c(157): warning #593: variable "n" was set but never used
    INT i, i0, d, n;
                  ^

if icc -DHAVE_CONFIG_H -I. -I. -I..  -I../src  -I/well/rescomp/eb/software/Eigen/3.3.4/include -I/usr/include  -Wall -Wno-strict-aliasing -g -gdwarf-2 -Wunused -Wuninitialized -ftemplate-depth-1024 -m64 -march=nocona -O3 -O2 -xHost -ftz -fp-speculation=safe -fp-model source -fPIC -DNDEBUG  -MT ar_funs.o -MD -MP -MF ".deps/ar_funs.Tpo" -c -o ar_funs.o `test -f 'locfit/ar_funs.c' || echo './'`locfit/ar_funs.c; \
        then mv -f ".deps/ar_funs.Tpo" ".deps/ar_funs.Po"; else rm -f ".deps/ar_funs.Tpo"; exit 1; fi
icc: command line warning #10121: overriding '-march=nocona' with '-xHost'
if icc -DHAVE_CONFIG_H -I. -I. -I..  -I../src  -I/well/rescomp/eb/software/Eigen/3.3.4/include -I/usr/include  -Wall -Wno-strict-aliasing -g -gdwarf-2 -Wunused -Wuninitialized -ftemplate-depth-1024 -m64 -march=nocona -O3 -O2 -xHost -ftz -fp-speculation=safe -fp-model source -fPIC -DNDEBUG  -MT arith.o -MD -MP -MF ".deps/arith.Tpo" -c -o arith.o `test -f 'locfit/arith.c' || echo './'`locfit/arith.c; \
        then mv -f ".deps/arith.Tpo" ".deps/arith.Po"; else rm -f ".deps/arith.Tpo"; exit 1; fi
icc: command line warning #10121: overriding '-march=nocona' with '-xHost'
locfit/arith.c(544): warning #180: argument is incompatible with formal parameter
      va = arbuild(z,0,strlen(z)-1,NULL,1,0);
                       ^

locfit/arith.c(582): warning #180: argument is incompatible with formal parameter
      va = arbuild(z,0,strlen(z)-1,NULL,1,0);
                       ^

if icc -DHAVE_CONFIG_H -I. -I. -I..  -I../src  -I/well/rescomp/eb/software/Eigen/3.3.4/include -I/usr/include  -Wall -Wno-strict-aliasing -g -gdwarf-2 -Wunused -Wuninitialized -ftemplate-depth-1024 -m64 -march=nocona -O3 -O2 -xHost -ftz -fp-speculation=safe -fp-model source -fPIC -DNDEBUG  -MT band.o -MD -MP -MF ".deps/band.Tpo" -c -o band.o `test -f 'locfit/band.c' || echo './'`locfit/band.c; \
        then mv -f ".deps/band.Tpo" ".deps/band.Po"; else rm -f ".deps/band.Tpo"; exit 1; fi
In file included from biascorrection.cpp(10):
biascorrection.h(18): catastrophic error: cannot open source file "boost/tr1/unordered_map.hpp"
  #include <boost/tr1/unordered_map.hpp>
                                        ^

compilation aborted for biascorrection.cpp (code 4)
make[2]: *** [biascorrection.o] Error 1
make[2]: *** Waiting for unfinished jobs....
```
and then loads more of the same.

**Comment by boegel** [comment]
Seems like my suspicion is confirmed:

```
$ find /usr/include/boost/ -name unordered_map.hpp
/usr/include/boost/tr1/unordered_map.hpp
/usr/include/boost/unordered_map.hpp
/usr/include/boost/unordered/unordered_map.hpp
$ rpm -q --whatprovides /usr/include/boost/tr1/unordered_map.hpp
boost-devel-1.53.0-27.el7.x86_64
```

I'll have to revise the included `Boost` dependency, to see which version still provides `boost/tr1/unordered_map.hpp`...

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in this PR)
node2548.golett.os - Linux centos linux 7.4.1708, Intel(R) Xeon(R) CPU E5-2680 v3 @ 2.50GHz, Python 2.7.5
See https://gist.github.com/61d52e7c86a37ef85e3624076ade6a51 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in this PR)
gligar03.gligar.os - Linux centos linux 7.4.1708, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.7.5
See https://gist.github.com/67cee88bf664dfca13ffbe676ba21a89 for a full test report.

**Comment by verdurin** [comment]
Test report by @verdurin
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in this PR)
rescomp2 - Linux centos 6.8, Intel(R) Xeon(R) CPU E5-2650 v2 @ 2.60GHz, Python 2.7.14
See https://gist.github.com/3cfdce7c3f978feb51f4548051b01caa for a full test report.

**Comment by verdurin** [comment]
Going in, thanks @boegel!

**Pull request merged**
