### PR TITLE
use patch to fix flaky test optim test in PyTorch 1.12.1 w/ foss/2021a

### PR DESCRIPTION
**Pull request by branfosj**
(created using `eb --new-pr`)

add patch from #17726 - using separate PRs for each easyconfig

### CODE REVIEW

**Comment by branfosj** [comment]
Test report by @branfosj
**FAILED**
Build succeeded for 0 out of 1 (1 easyconfigs in total)
bear-pg0104u17b.bear.cluster - Linux RHEL 8.6, x86_64, Intel(R) Xeon(R) Platinum 8360Y CPU @ 2.40GHz (icelake), Python 3.6.8
See https://gist.github.com/branfosj/37a02d1c28810475bbe5249da2f1e77f for a full test report.

**Comment by boegel** [comment]
> test_optim failed!

@branfosj 🤔

**Comment by boegel** [comment]
@boegelbot please test @ generoso
CORE_CNT=16

**Comment by branfosj** [comment]
:( 

```
======================================================================
FAIL: test_adagrad (__main__.TestOptim)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/dev/shm/branfosj/build-up-EL8/PyTorch/1.12.1/foss-2021a/pytorch-v1.12.1/test/test_optim.py", line 746, in test_adagrad
    self._test_basic_cases(
  File "/dev/shm/branfosj/build-up-EL8/PyTorch/1.12.1/foss-2021a/pytorch-v1.12.1/test/test_optim.py", line 313, in _test_basic_cases
    self._test_basic_cases_template(
  File "/dev/shm/branfosj/build-up-EL8/PyTorch/1.12.1/foss-2021a/pytorch-v1.12.1/test/test_optim.py", line 141, in _test_basic_cases_template
    self.assertGreater(fn().item(), initial_value)
AssertionError: 0.0 not greater than 0.0

----------------------------------------------------------------------
```

**Comment by branfosj** [comment]
Based on the failures seen, I am closing this and suggesting we revert adding it to the other PyTorch 1.12.1 that we've merged ( #17737)

**Pull request closed without merging**
