### PR TITLE
{cae}[foss/2020b] Salome v9.8.0

### PR DESCRIPTION
**Pull request by Falkor**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by jfgrimm** [comment]
Looking at the resulting installation, specifically the `BINARIES-CO7`directory, I think we should either drop to the `SYSTEM` toolchain and use the bundled dependencies (the easy route), or try and provide all relevant dependencies through easybuild:
```
$ ls $EBROOTSALOME/BINARIES-CO7
ADAO            FMILibrary       JOBMANAGER    openturns      SALOME
ADAO_INTERFACE  freeimage        KERNEL        openVKL        scotch
BLSURFPLUGIN    freetype         lapack        ospray         SHAPER
boost           GEOM             LIBBATCH      ParaView       SHAPERSTUDY
CALCULATOR      GHS3DPLUGIN      libxml2       PARAVIS        sip
CAS             GHS3DPRLPLUGIN   llvm          PARAVISADDONS  SMESH
cgns            gmsh             matplotlib    petsc          SOLVERLAB
cmake           GMSHPLUGIN       MEDCOUPLING   planegcs       StaticMeshPlugin
cminpack        graphviz         medfile       PY2CPP         swig
COMPONENT       GUI              mesa          PYCALCULATOR   system_dep
cppunit         hdf5             MeshGems      PYHELLO        tbb
DOCUMENTATION   HELLO            metis         PyQt           tcl
doxygen         HEXABLOCK        netgen        pyreadline     tk
EFICAS          HEXABLOCKPLUGIN  NETGENPLUGIN  Python         URANIE
EFICAS_TOOLS    HexoticPLUGIN    nlopt         qt             YACS
eigen           HOMARD           omniORB       qwt            YACSGEN
embree          HYBRIDPLUGIN     omniORBpy     rkCommon       YDEFX
FIELDS          ispc             opencv        root

```

**Comment by Falkor** [comment]
The list is just too big... Going to SYSTEM with the dependency on libGLU seems contradictory to me ?

**Comment by jfgrimm** [comment]
> The list is just too big... Going to SYSTEM with (at least) the dependency on libGLU seems contradictory to me ?

does it actually need the libGLU dependency though? It looks like it ships all the libraries it needs, and the `salome`/`mesa_salome` executables aren't dynamically linked

**Comment by Falkor** [comment]
> does it actually need the libGLU dependency though? It looks like it ships all the libraries it needs, and the `salome`/`mesa_salome` executables aren't dynamically linked

I think so - OpenGL is clearly pointed as a common problem. 
With regards the dependencies, I'm worried when looking at the content of `$EBROOTSALOME/env_launch.sh` with the potential side effects.
Nevertheless I'm trying now the build with the following changes: 

```diff 
--- /Users/svarrette/git/github.com/ULHPC/easybuild-easyconfigs/easybuild/easyconfigs/s/Salome/Salome-9.8.0-foss-2020b.eb	2022-04-12 14:54:50.000000000 +0200
+++ easyconfigs/s/Salome/Salome-9.8.0-foss-2020b.eb	2022-04-12 14:46:01.000000000 +0200
@@ -22,7 +22,30 @@
 ]

 dependencies = [
-    ("libGLU", "9.0.1"),
+    # See $EBROOTSALOME/BINARIES-CO7
+    ('Boost', '1.74.0'),
+    ('CMake', '3.20.1'),
+    ('Doxygen', '1.8.20'),
+    ('Eigen', '3.4.0'),
+    ('FreeImage', '3.18.0'),
+    ('freetype', '2.10.3'),
+    # ('gmsh', '4.8.4'), # Uncomment once PR 13905 is accepted
+    ('HDF5', '1.10.7'),
+    ('libGLU', '9.0.1'),
+    ('libxml2', '2.9.10'),
+    ('LLVM', '11.0.0'),
+    ('matplotlib', '3.3.3'),
+    ('METIS', '5.1.0'),
+    ('OpenCV', '4.5.1', '-contrib'),
+    ('ParaView', '5.8.1', '-mpi'),
+    ('PETSc', '3.14.4'),
+    ('Python', '3.8.6'),
+    ('PyQt5', '5.15.1'),
+    ('PyQtGraph', '0.11.1'),
+    ('SCOTCH', '6.1.0'),
+    ('SWIG', '4.0.2'),
+    ('tbb', '2020.3'),
+    ('YACS', '0.1.8')
 ]
```
If the builds succeed and you consider it a better option, I can commit them toward this PR.

**Comment by boegel** [comment]
closing this since `foss/2020b` is deprecated, see https://docs.easybuild.io/policies/toolchains

**Pull request closed without merging**
