### PR TITLE
{tools}[dummy/dummy] EasyBuild v3.3.1

### PR DESCRIPTION
**Pull request by boegel**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
node2570.golett.os - Linux centos linux 7.3.1611, Intel(R) Xeon(R) CPU E5-2680 v3 @ 2.50GHz, Python 2.7.5
See https://gist.github.com/f2cc3be2ae0c4b414b55e0f9a3af7cff for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
localhost - Linux UNKNOWN UNKNOWN, AMD Opteron(tm) Processor 6136, Python 2.7.12
See https://gist.github.com/0464c2a8784d82b2ae8f2263e03d1b34 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
gligar01.gligar.os - Linux centos linux 7.3.1611, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.7.5
See https://gist.github.com/dcfffb0bfc447a9a9df92c3fc8a48bf9 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
ela2 - Linux SLES 11_SP3, Intel(R) Xeon(R) CPU E5-2650 v2 @ 2.60GHz, Python 2.6.9
See https://gist.github.com/c11fb6ab21c48cfc5a84a847af139c53 for a full test report.

**Comment by boegel** [comment]
worth mentioning: I'm not including SHA256 checksums for this one, sort of on purpose.

If I would, only very recent EasyBuild versions (>= 3.3.0) would be able to use this easyconfig file (incl. `eb --install-latest-eb-release`)...

**Comment by verdurin** [comment]
Test report by @verdurin
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
ca024.camp.thecrick.org - Linux centos linux 7.3.1611, Intel(R) Xeon(R) CPU E5-2640 v3 @ 2.60GHz, Python 2.7.5
See https://gist.github.com/d5e57e0ea6340f728d41051248fd1723 for a full test report.

**Comment by migueldiascosta** [comment]
Going in, thanks @boegel!

**Comment by verdurin** [comment]
Looks good to me as well.

**Pull request merged**
