### PR TITLE
{data}[GCCcore/8.3.0] DCMTK v3.6.5

### PR DESCRIPTION
**Pull request by crubb**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by crubb** [comment]
Test report by @crubb
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
radbert - Linux ubuntu 18.04, Intel(R) Xeon(R) CPU E5-2687W v4 @ 3.00GHz, Python 2.7.17
See https://gist.github.com/1ccccf0b5e7f451105674c9474bfbc0b for a full test report.

**Comment by crubb** [comment]
Test report by @crubb
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
radbert - Linux ubuntu 18.04, Intel(R) Xeon(R) CPU E5-2687W v4 @ 3.00GHz, Python 2.7.17
See https://gist.github.com/972cbebd05bb94dd03c01a3d9f227f2f for a full test report.

**Comment by Micket** [comment]
Test report by @Micket
**SUCCESS**
Build succeeded for 2 out of 2 (1 easyconfigs in this PR)
hebbe-c1 - Linux centos linux 7.7.1908, Intel Core Processor (Haswell, no TSX), Python 2.7.5
See https://gist.github.com/4c01c8b8b23584cd45c3852a6ee235d9 for a full test report.

**Comment by Micket** [comment]
Going in, thanks @crubb!

**Pull request merged**
