### PR TITLE
{math}[gompi/2020a,iimpi/2020a] ParMETIS v4.0.3

### PR DESCRIPTION
**Pull request by lexming**
(created using `eb --new-pr`)

This PR depends on https://github.com/easybuilders/easybuild-easyblocks/pull/1774

~~Working on the version for `iimpi`...~~

### CODE REVIEW

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in this PR)
node3112.skitty.os - Linux centos linux 7.7.1908, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz, Python 3.6.8
See https://gist.github.com/c261f99157576f1317c26b91d461670d for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in this PR)
node2491.golett.os - Linux centos linux 7.7.1908, Intel(R) Xeon(R) CPU E5-2680 v3 @ 2.50GHz, Python 2.7.5
See https://gist.github.com/dc8fab0bd3f59e75db94620bd8f15cf6 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in this PR)
generoso - Linux centos linux 7.6.1810, Intel(R) Xeon(R) CPU E5-2660 v4 @ 2.00GHz, Python 3.6.8
See https://gist.github.com/a6282af58721c5244667f83bcc4e3e90 for a full test report.

**Comment by lexming** [comment]
Test report by @lexming
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in this PR)
login2.cerberus.os - Linux centos linux 7.7.1908, Intel(R) Xeon(R) Gold 6126 CPU @ 2.60GHz, Python 2.7.5
See https://gist.github.com/fe3d149bd50e4e2cb2c6e3dcefb09995 for a full test report.

**Comment by boegel** [comment]
Going in, thanks @lexming!

**Pull request merged**
