### PR TITLE
{tools, lib, devel, bio}[GCCcore/13.3.0, gfbf/2024a] ccache-4.10.2, PROJ-9.4.1, protobuf-28.0, protobuf-python-5.28.0, pytest-flakefinder-1.1.0, RDFlib-7.0.0, RapidJSON-1.1.0-20240815, Seaborn-0.13.2

### PR DESCRIPTION
**Pull request by ankekreuzer**
Added a few more packages from the new SW stage at JSC to GCCcore 13.3.0 and gfbf 2024a.

### CODE REVIEW

**Comment by ankekreuzer** [comment]
Test report by @ankekreuzer
**SUCCESS**
Build succeeded for 8 out of 8 (8 easyconfigs in total)
zam329 - Linux Rocky Linux 9.4 (Blue Onyx), x86_64, Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz, Python 3.9.18
See https://gist.github.com/ankekreuzer/d4f7a38f530088a9aef4c3e16675ee7d for a full test report.

**Comment by SebastianAchilles** [comment]
@boegelbot please test @ jsc-zen3

**Comment by SebastianAchilles** [comment]
@boegelbot please test @ generoso

**Comment by smoors** [comment]
Going in, thanks @ankekreuzer!

**Pull request merged**
