### PR TITLE
add additional extensions to R 3.6.2 + R-bundle-Bioconductor 3.10 easyconfigs

### PR DESCRIPTION
**Pull request by boegel**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by boegel** [comment]
Test report by @boegel
**FAILED**
Build succeeded for 2 out of 3 (3 easyconfigs in this PR)
generoso - Linux centos linux 7.6.1810, x86_64, Intel(R) Xeon(R) CPU E5-2660 v4 @ 2.00GHz, Python 3.6.8
See https://gist.github.com/f30a222913c54b291e908d60a049da39 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**FAILED**
Build succeeded for 1 out of 2 (2 easyconfigs in this PR)
node2658.swalot.os - Linux centos linux 7.7.1908, x86_64, Intel(R) Xeon(R) CPU E5-2660 v3 @ 2.60GHz (haswell), Python 2.7.5
See https://gist.github.com/dbfb4f3cf35e72647f8ed92b352eaf82 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in this PR)
node3125.skitty.os - Linux centos linux 7.7.1908, x86_64, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz (skylake_avx512), Python 3.6.8
See https://gist.github.com/3827826fe56a6daeb6bef55ea6a884e3 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 3 out of 3 (3 easyconfigs in this PR)
node3302.joltik.os - Linux centos linux 7.7.1908, x86_64, Intel(R) Xeon(R) Gold 6242 CPU @ 2.80GHz (cascadelake), Python 3.6.8
See https://gist.github.com/205db03b24ac56d42d03601e3d117a25 for a full test report.

**Comment by smoors** [comment]
@boegel while you're at it, could you also add the following extensions to the R easyconfig?
```
    ('findpython', '1.0.5', {
        'checksums': ['3e9a21988cb78833769b02680d128a0cc01bcb41aa9c9725ab1742f349759145'],
    }),
    ('argparse', '2.0.1', {
        'checksums': ['949843920d14fc7c162aedab331a936499541736e7dafbb103fbfd79be8147ab'],
    }),
    ('ggsci', '2.9', {
        'checksums': ['4af14e6f3657134c115d5ac5e65a2ed74596f9a8437c03255447cd959fe9e33c'],
    }),
    ('ggsignif', '0.6.0', {
        'checksums': ['6fe13efda31386483e64d466ba2f5a53a2a235ae04f5c17bba3ccc63d283499e'],
    }),
    ('corrplot', '0.84', {
        'checksums': ['0dce5e628ead9045580a191f60c58fd7c75b4bbfaaa3307678fc9ed550c303cc'],
    }),
    ('rstatix', '0.5.0', {
        'checksums': ['06b2ba1b16698c93203474eb67e59169fa4127283d46cf694e032a5472956b46'],
    }),
    ('ggpubr', '0.3.0', {
        'checksums': ['b82ffc6bd5974c3036d08393fa1f2bafeaf6f567e0b3faf43e38226b19399eb6'],
    }),
    ('intergraph', '2.0-2', {
        'checksums': ['6cbe77f1e87fa1c110db2d46010f2f3ae72bfdb708ce2ca84c1cdc2cd6eb47a1'],
    }),
    ('ggnetwork', '0.5.8', {
        'checksums': ['a8c7c19a2bafce898c95d0b2401ef052925db57b85058c7203f0122b3af7bbbd'],
    }),
```

**Comment by smoors** [comment]
and also add this one to the bioconductor?
```
    ('HMMcopy', '1.28.1', {
        'checksums': ['539f4cbd0e558126a5e529beec8fd4b72a42ff04750d34d24b1ea1e40269d02f'],
    }),
```

many thanks in advance!

**Comment by boegel** [comment]
@smoors done in bca1249

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in this PR)
node3125.skitty.os - Linux centos linux 7.7.1908, x86_64, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz (skylake_avx512), Python 3.6.8
See https://gist.github.com/9696001fbb6127d3b3e5cbfe287decd8 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in this PR)
node2658.swalot.os - Linux centos linux 7.7.1908, x86_64, Intel(R) Xeon(R) CPU E5-2660 v3 @ 2.60GHz (haswell), Python 2.7.5
See https://gist.github.com/5680bb406aaf250b5015a38a4d0d16b8 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 3 out of 3 (3 easyconfigs in this PR)
node3302.joltik.os - Linux centos linux 7.7.1908, x86_64, Intel(R) Xeon(R) Gold 6242 CPU @ 2.80GHz (cascadelake), Python 3.6.8
See https://gist.github.com/9e4f50a915602a711228fd286c16afc0 for a full test report.

**Comment by smoors** [comment]
Test report by @smoors
**FAILED**
Build succeeded for 2 out of 3 (3 easyconfigs in this PR)
node376.hydra.os - Linux centos linux 7.7.1908, x86_64, Intel(R) Xeon(R) Gold 6148 CPU @ 2.40GHz (skylake_avx512), Python 2.7.5
See https://gist.github.com/0509d407940d232b0ba157981269d542 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in this PR)
generoso - Linux centos linux 7.6.1810, x86_64, Intel(R) Xeon(R) CPU E5-2660 v4 @ 2.00GHz, Python 3.6.8
See https://gist.github.com/ff66c965a537f45e6b18eaaeb3f7b6e0 for a full test report.

**Comment by smoors** [comment]
the fail on R-3.6.2-fosscuda-2019b.eb was a mistake on my side.

**Comment by smoors** [comment]
Going in, thanks @boegel!

**Pull request merged**
