### PR TITLE
{tools}[foss/2018a, intel/2018a] ToFu 1.4.1 w/ Python 3.6.4 

### PR DESCRIPTION
**Pull request by Louwrensth**

### CODE REVIEW

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in this PR)
node3138.skitty.os - Linux centos linux 7.6.1810, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz, Python 3.6.8
See https://gist.github.com/4e24be4a2ae66a771a9806c251d67863 for a full test report.

**Comment by Louwrensth** [comment]
> @Louwrensth Any reason why the custom `sanity_check_commands` is no longer included?
Good call. I know of no reason, it was probably forgotten. Fixup!

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in this PR)
node3141.skitty.os - Linux centos linux 7.6.1810, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz, Python 3.6.8
See https://gist.github.com/0e98d88aaa9ecf71f756705e3facd2dc for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in this PR)
node2401.golett.os - Linux centos linux 7.6.1810, Intel(R) Xeon(R) CPU E5-2680 v3 @ 2.50GHz, Python 2.7.5
See https://gist.github.com/1434a2a9a03a544f0095fae84704c217 for a full test report.

**Comment by boegel** [comment]
Going in, thanks @Louwrensth!

**Pull request merged**
