### PR TITLE
{lang} [foss-2016a} R-3.2.5

### PR DESCRIPTION
**Pull request by verdurin**
(created using `eb --new-pr`)
Update R to 3.2.5 for foss-2016a, including plotting-enabled version

### CODE REVIEW

**Comment by boegel** [comment]
@verdurin no update of the extensions themselves? cfr. #3079

**Comment by verdurin** [comment]
@boegel - I was just glad that it built first time and I didn't have to update them...

More seriously, though, this is just a bugfix release in the 3.2 series. Isn't it better to keep extension updates for 3.3?

**Comment by boegel** [comment]
@verdurin I think it would be better to update the extension versions for 3.2.5 too; just copy-paste from #3079?

**Comment by boegel** [comment]
@verdurin I've grabbed the updated extension list from #3079 and slapped it in here + updated versions of `biom`, `geepack`, `lubridate`, `pim` which were added recently in the R 3.2.3 easyconfigs (#3186, #3211, #3275), cfr. https://github.com/verdurin/easybuild-easyconfigs/pull/3

**Comment by boegel** [comment]
Test report by @boegel
**FAILED**
Build succeeded for 0 out of 2 (2 easyconfigs in this PR)
node2055.delcatty.os - Linux SL 6.7, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.6.6
See https://gist.github.com/c142b15097d3b6ef26faca33b2e5956a for a full test report.

**Comment by boegel** [comment]
Hmm...

```
checking cairo.h usability... yes
checking cairo.h presence... yes
checking for cairo.h... yes
checking for PNG support in Cairo... yes
checking for ATS font support in Cairo... no
configure: CAIRO_LIBS=-L/user/scratch/gent/vsc400/vsc40023/easybuild_REGTEST/SL6/sandybridge/software/cairo/1.14.6-foss-2016a/lib -L/user/scratch/gent/vsc400/vsc40023/easybuild_REGTEST/SL6/sandybridge/software/libXext/1.3.3-foss-2016a/lib -L/user/scratch/gent/vsc400/vsc40023/easybuild_REGTEST/SL6/sandybridge/software/libXrender/0.9.9-foss-2016a/lib -L/user/scratch/gent/vsc400/vsc40023/easybuild_REGTEST/SL6/sandybridge/software/freetype/2.6.2-foss-2016a/lib -L/user/scratch/gent/vsc400/vsc40023/easybuild_REGTEST/SL6/sandybridge/software/libpng/1.6.21-foss-2016a/lib -L/user/scratch/gent/vsc400/vsc40023/easybuild_REGTEST/SL6/sandybridge/software/libX11/1.6.3-foss-2016a/lib -lfreetype -lpng16 -lz -lXrender -lcairo -lXext -lX11  
checking for library containing deflate... no
checking whether Cairo programs can be compiled... configure: error: Cannot compile a simple Cairo program. See config.log for details.
ERROR: configuration failed for package ‘Cairo’
```

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in this PR)
node2418.golett.os - Linux centos linux 7.2.1511, Intel(R) Xeon(R) CPU E5-2680 v3 @ 2.50GHz, Python 2.7.5
See https://gist.github.com/e546416b886d5732da19e0f7ae33151e for a full test report.

**Comment by backelj** [comment]
Shouldn't this be fixed for all R-*.eb files which include Cairo?
I've had a similar issue when building R-3.3.1-intel-2016b.eb...

**Comment by boegel** [comment]
@verdurin is this still relevant since we already have `R-3.3.1-foss-2016b.eb`?

**Comment by boegel** [comment]
I consider this obsolete now, let me know if you disagree @valtandor

**Pull request closed without merging**
