### PR TITLE
enable building of dev tools in recent PyQt5 easyconfigs

### PR DESCRIPTION
**Pull request by ThomasHoffmann77**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by jfgrimm** [comment]
Test report by @jfgrimm
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
node115.pri.viking.alces.network - Linux CentOS Linux 7.9.2009, x86_64, Intel(R) Xeon(R) Gold 6138 CPU @ 2.00GHz (skylake_avx512), Python 3.6.8
See https://gist.github.com/ac0e9bfd31cb7c5d89fa8d0d9fb4e4ac for a full test report.

**Comment by jfgrimm** [comment]
@ThomasHoffmann77 can we add a sanity check command for `pyrcc5` as well? maybe something like `pyrcc5 -version | grep 'pyrcc5 v%(version)s'` or similar

if you're up for porting the changes to the other recent-ish easyconfigs as well, that would be great:
 - `PyQt5-5.15.1-GCCcore-9.3.0-Python-3.8.2.eb`
 - `PyQt5-5.15.1-GCCcore-10.2.0.eb`
 - `PyQt5-5.15.4-GCCcore-10.2.0.eb`
 - `PyQt5-5.15.4-GCCcore-10.3.0.eb`

**Comment by verdurin** [comment]
Test report by @verdurin
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
easybuild-c7.novalocal - Linux CentOS Linux 7.9.2009, x86_64, Intel Xeon Processor (Skylake, IBRS), Python 3.6.8
See https://gist.github.com/9c3fb3cad566e6cc8b5b62aa85821381 for a full test report.

**Comment by jfgrimm** [comment]
@boegelbot please test @ generoso
CORE_CNT=16

**Comment by jfgrimm** [comment]
Test report by @jfgrimm
**FAILED**
Build succeeded for 6 out of 7 (4 easyconfigs in total)
node006.pri.viking.alces.network - Linux CentOS Linux 7.9.2009, x86_64, Intel(R) Xeon(R) Gold 6138 CPU @ 2.00GHz (skylake_avx512), Python 3.6.8
See https://gist.github.com/3866e9626284f8ae2fa10ff4576a1aeb for a full test report.

**Comment by verdurin** [comment]
Test report by @verdurin
**FAILED**
Build succeeded for 5 out of 6 (4 easyconfigs in total)
easybuild-c7.novalocal - Linux CentOS Linux 7.9.2009, x86_64, Intel Xeon Processor (Skylake, IBRS), Python 3.6.8
See https://gist.github.com/67e41275e10ef6705f5e7e3092cc51c2 for a full test report.

**Comment by jfgrimm** [comment]
@ThomasHoffmann77 maybe just remove the 5.15.1 one

**Comment by jfgrimm** [comment]
Test report by @jfgrimm
**SUCCESS**
Build succeeded for 3 out of 3 (3 easyconfigs in total)
node124.pri.viking.alces.network - Linux CentOS Linux 7.9.2009, x86_64, Intel(R) Xeon(R) Gold 6138 CPU @ 2.00GHz (skylake_avx512), Python 3.6.8
See https://gist.github.com/68e0fd9ea19348f4a8e3f1f4aa9826d0 for a full test report.

**Review by jfgrimm — APPROVED** [review]
LGTM

**Comment by jfgrimm** [comment]
Going in, thanks @ThomasHoffmann77!

**Pull request merged**
