### PR TITLE
{bio}[foss/2018b] nanopolish v0.10.2 w/ Python 2.7.15

### PR DESCRIPTION
**Pull request by fizwit**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by fizwit** [comment]
diff nanopolish-0.10.2-intel-2018b-Python-2.7.15.eb
```
10c10
< toolchain = {'name': 'intel', 'version': '2018b'}
---
> toolchain = {'name': 'foss', 'version': '2018b'}
28c28
<     ('Eigen', '3.3.4', '', True),
---
>     ('Eigen', '3.3.5', '', True),
```

**Comment by fizwit** [comment]
Eigen-3.3.5 should be the correct version for foss-2018b

**Comment by boegel** [comment]
@fizwit `Eigen` is just a bunch of headers, so it should always be a build dependency (which will effectively eliminate the failing test).

Of course, it's also wrong in the existing `nanopolish-0.10.2-intel-2018b-Python-2.7.15.eb`... I've fixed that in #8448

**Comment by vanzod** [comment]
Test report by @vanzod
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
cermis - Linux debian 9.9, Intel(R) Xeon(R) CPU           X5670  @ 2.93GHz, Python 2.7.13
See https://gist.github.com/8dd92ea6bbd96ab9e2aa7ff5f1343dcf for a full test report.

**Comment by vanzod** [comment]
Going in, thanks @fizwit!

**Pull request merged**
