### PR TITLE
{bio}[fosscuda/2020b] GROMACS v2021.2 w/ Python 3.8.6

### PR DESCRIPTION
**Pull request by boegel**
(created using `eb --new-pr`)

requires ~~https://github.com/easybuilders/easybuild-easyblocks/pull/2391~~

### CODE REVIEW

**Review by Micket — APPROVED** [review]
lgtm

**Comment by Micket** [comment]
Test report by @Micket
**FAILED**
Build succeeded for 2 out of 3 (1 easyconfigs in total)
vera-c1 - Linux centos linux 7.9.2009, x86_64, Intel Xeon Processor (Skylake), Python 2.7.5
See https://gist.github.com/ddfb969e1d00fc89e836bc5d319f08aa for a full test report.

**Comment by Micket** [comment]
Are there framework changes that affect the python package here? Or maybe something I have missed to rebuild?

These warnings are hard to understand
```
== 2021-05-11 12:50:57,524 easyblock.py:2744 WARNING failing sanity check for 'gmxapi' extension: found one or more downloaded dependencies: Collecting install, found one or more downloaded dependencies: Collecting install
== 2021-05-11 12:50:57,524 easyblock.py:2750 WARNING extensions sanity check failed for 1 extensions: 
```
I mean, I'm expecting something like a list of extensions it failed on after the : but there isn't.. It just repeats "Collecting install" ?! whut?

**Comment by Micket** [comment]
So, it's seems like it is literally a python package called "install"
https://pypi.org/project/install/

But I'm unclear to why it works for you

**Comment by boegel** [comment]
@Micket Perhaps you're missing https://github.com/easybuilders/easybuild-easyblocks/pull/2391?

**Comment by branfosj** [comment]
Test report by @branfosj
**SUCCESS**
Build succeeded for 0 out of 0 (1 easyconfigs in total)
bask-pg0309u24a - Linux RHEL 8.3, x86_64, Intel(R) Xeon(R) Platinum 8358P CPU @ 2.60GHz (icelake), Python 3.6.8
See https://gist.github.com/8ebfbda9c7f95db547b4212ff244aefe for a full test report.

**Comment by branfosj** [comment]
Test report by @branfosj
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
bask-pg0309u24a - Linux RHEL 8.3, x86_64, Intel(R) Xeon(R) Platinum 8358P CPU @ 2.60GHz (icelake), Python 3.6.8
See https://gist.github.com/d47c360cdb968a3b8c40b8af6115a15f for a full test report.

**Comment by Micket** [comment]
Test report by @Micket
Using easyblocks from PR(s) https://github.com/easybuilders/easybuild-easyblocks/pull/2391
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
vera-c1 - Linux centos linux 7.9.2009, x86_64, Intel Xeon Processor (Skylake), Python 2.7.5
See https://gist.github.com/05eb224d6027c705a07a121f3378e021 for a full test report.

**Comment by Micket** [comment]
Going in, thanks @boegel!

**Pull request merged**
