### PR TITLE
{devel}[foss/2018a] Qt 4.8.7

### PR DESCRIPTION
**Pull request by RvDijk**

### CODE REVIEW

**Comment by boegel** [comment]
@RvDijk Do you need this as a dependency for something in particular?

We should try and get rid of Qt 4.x (`4.7.8` release was released May 2015)...

**Comment by RvDijk** [comment]
@boegel eventually I want to build a OpenFOAM foss2018a version, so I took #6011 as a starting point. ParaView there still uses this Qt version..

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
node2401.golett.os - Linux centos linux 7.4.1708, Intel(R) Xeon(R) CPU E5-2680 v3 @ 2.50GHz, Python 2.7.5
See https://gist.github.com/02ced0182b12992b4e290401ea6970d9 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
node2099.delcatty.os - Linux centos linux 7.4.1708, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.7.5
See https://gist.github.com/6bacd308fac8ad952c1ab5ea54a1d8c9 for a full test report.

**Comment by boegel** [comment]
@RvDijk OK, I think we're still stuck to Qt 4 for OpenFOAM (don't recall exactly why though...), so OK :)

**Comment by boegel** [comment]
Going in, thanks @RvDijk!

**Pull request merged**
