### PR TITLE
{bio}[gompi/2021a] kallisto v0.48.0

### PR DESCRIPTION
**Pull request by pberthier**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by pberthier** [comment]
Test report by @pberthier
**SUCCESS**
Build succeeded for 0 out of 0 (1 easyconfigs in total)
softdev8.ibu.internal - Linux Rocky Linux 8.8 (Green Obsidian), x86_64, AMD EPYC 7742 64-Core Processor, Python 3.11.2
See https://gist.github.com/pberthier/ae469970a3eb4389bb2cf743721d9702 for a full test report.

**Comment by SebastianAchilles** [comment]
@boegelbot please test @ jsc-zen2

**Comment by SebastianAchilles** [comment]
Test report by @sebastianachilles
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
bwd-rockylinux-92 - Linux Rocky Linux 9.2 (Blue Onyx), x86_64, Intel(R) Core(TM) i7-6900K CPU @ 3.20GHz (broadwell), Python 3.9.16
See https://gist.github.com/SebastianAchilles/c31634e030ae194a876716f02f263bc8 for a full test report.

**Comment by SebastianAchilles** [comment]
Going in, thanks @pberthier!

**Pull request merged**
