### PR TITLE
add git as build dependency to Python 3.8.x and 3.9.x easyconfigs (required for pbr extension)

### PR DESCRIPTION
**Pull request by SebastianAchilles**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by boegel** [comment]
@boegelbot please test @ generoso

**Comment by boegel** [comment]
@SebastianAchilles Maybe it's worth including the error message that you run into when not having `git` installed?

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 4 out of 4 (4 easyconfigs in total)
node2604.swalot.os - Linux centos linux 7.9.2009, x86_64, Intel(R) Xeon(R) CPU E5-2660 v3 @ 2.60GHz (haswell), Python 3.6.8
See https://gist.github.com/6d5e6eb7e1cecacfbd2742969a81d001 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 4 out of 4 (4 easyconfigs in total)
node3501.doduo.os - Linux RHEL 8.2, x86_64, AMD EPYC 7552 48-Core Processor (zen2), Python 3.6.8
See https://gist.github.com/ab10442fae3d649e40b03ca491d0cbfe for a full test report.

**Comment by SebastianAchilles** [comment]
> @SebastianAchilles Maybe it's worth including the error message that you run into when not having `git` installed?

I didn't run into this issue myself. But from https://github.com/easybuilders/easybuild-easyconfigs/issues/13630 it seems like `git` is required as build dependency. I think easyconfigs should be self-contained, i.e. don't depend on OS packages (unless they are specified as `osdependencies`). That is why I opened this PR.

**Comment by SebastianAchilles** [comment]
Test report by @sebastianachilles
**SUCCESS**
Build succeeded for 4 out of 4 (4 easyconfigs in total)
rocky8-eb - Linux rocky linux 8.4, x86_64, Intel(R) Core(TM) i7-6900K CPU @ 3.20GHz (broadwell), Python 3.6.8
See https://gist.github.com/0ba42bf2064e1c509ef4e150e97e23d0 for a full test report.

**Comment by SebastianAchilles** [comment]
Test report by @sebastianachilles
**SUCCESS**
Build succeeded for 4 out of 4 (4 easyconfigs in total)
jsfc01.int.jusuf.sebastian.cluster - Linux rocky linux 8.4, x86_64, AMD EPYC 7742 64-Core Processor (zen2), 1 x NVIDIA GRID V100-4C, 460.73.01, Python 3.6.8
See https://gist.github.com/e1e0ac0c47d92965b8afc41d47235067 for a full test report.

**Review by boegel — APPROVED** [review]
lgtm

**Comment by boegel** [comment]
Going in, thanks @SebastianAchilles!

**Comment by lexming** [comment]
Re-building to fix issue #15857 in generoso.

**Pull request merged**
