### PR TITLE
{tools}[foss/2020{a,b}] mongolite w/ R-4.0.{0,3,4}

### PR DESCRIPTION
**Pull request by hajgato**
Not sure about the security disadvantages to use a non-systems sasl2, but I got  a super-quick super-important request.

### CODE REVIEW

**Comment by Micket** [comment]
I think that looks like an OK use of a os dep. Can you supply a build report?

**Review by boegel — APPROVED** [review]
lgtm

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 3 out of 3 (3 easyconfigs in total)
node3584.doduo.os - Linux RHEL 8.2, x86_64, AMD EPYC 7552 48-Core Processor (zen2), Python 3.6.8
See https://gist.github.com/4458c03fef0b4f97d35f14faf38f941a for a full test report.

**Comment by boegel** [comment]
@boegelbot please test @ generoso

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 3 out of 3 (3 easyconfigs in total)
node2620.swalot.os - Linux centos linux 7.9.2009, x86_64, Intel(R) Xeon(R) CPU E5-2660 v3 @ 2.60GHz (haswell), Python 3.6.8
See https://gist.github.com/c264e3ae274dca1cf223676064890ab8 for a full test report.

**Comment by boegel** [comment]
Going in, thanks @hajgato!

**Pull request merged**
