### PR TITLE
{bio}[foss/2019b] Arlequin v3.5.2.2: add missing moduleclass

### PR DESCRIPTION
**Pull request by FokkeDijkstra**
(created using `eb --new-pr`)

### CODE REVIEW

**Review by Micket — APPROVED** [review]
lgtm

**Comment by Micket** [comment]
Test report by @Micket
**FAILED**
Build succeeded for 3 out of 6 (1 easyconfigs in this PR)
vera-c1 - Linux centos linux 7.8.2003, x86_64, Intel Xeon Processor (Skylake), Python 2.7.5
See https://gist.github.com/89e74e665545a3683056b1483ed858a7 for a full test report.

**Comment by Micket** [comment]
Ugh, R. Can you supply test-reports for these @FokkeDijkstra ?

**Comment by lexming** [comment]
Test report by @lexming
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
node379.hydra.os - Linux centos linux 7.7.1908, x86_64, Intel(R) Xeon(R) Gold 6148 CPU @ 2.40GHz, Python 2.7.5
See https://gist.github.com/8cf259727825504ee4983252051039fd for a full test report.

**Review by lexming — APPROVED** [review]
LGTM

**Comment by lexming** [comment]
@Micket since your failed test is not related to this PR, I think that we can go ahead and merge it.

**Comment by lexming** [comment]
Going in, thanks @FokkeDijkstra !

**Comment by FokkeDijkstra** [comment]
Thanks for merging this. I just wanted to add this small fix, mainly to prevent moduleclass to be also missing in updated versions.

**Pull request merged**
