### PR TITLE
{cae}[intel/2021a] OpenFOAM v9, ParaView v5.9.1, CGAL v4.14.3, SCOTCH v6.1.0

### PR DESCRIPTION
**Pull request by boegel**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by boegel** [comment]
I ran into a confusing error with this, because our `impi/2021.2.0-intel-compilers-2021.2.0` module wasn't correctly setting `$I_MPI_ROOT` yet, see also https://github.com/easybuilders/easybuild-easyblocks/pull/2537

```
CMake Error in /software/OpenFOAM/9-intel-2021a/OpenFOAM-9/applications/utilities/postProcessing/graphics/PVReaders/Make/linux64IccDPInt32Opt/CMakeFiles/CMakeTmp/CMakeLists.txt:
  Imported target "MPI::MPI_C" includes non-existent path

    "/software/impi/2021.2.0-intel-compilers-2021.2.0/include"
```

This issue was fixed after re-generating the `impi` module with the updated `impi` easyblock with `--module-only`

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 11 out of 11 (4 easyconfigs in total)
node3109.skitty.os - Linux RHEL 8.4, x86_64, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz (skylake_avx512), Python 3.6.8
See https://gist.github.com/be35d54f7969f9e824e8c488f333844f for a full test report.

**Comment by migueldiascosta** [comment]
Test report by @migueldiascosta
**FAILED**
Build succeeded for 3 out of 4 (4 easyconfigs in total)
sms - Linux CentOS Linux 7.6.1810, x86_64, AMD EPYC 7601 32-Core Processor (zen), Python 2.7.5
See https://gist.github.com/3cf877fa58737dcc68bd3f51b5789a32 for a full test report.

**Comment by migueldiascosta** [comment]
weird, the test report was for my second build, and the first one had worked...

**Comment by migueldiascosta** [comment]
Test report by @migueldiascosta
**SUCCESS**
Build succeeded for 4 out of 4 (4 easyconfigs in total)
sms - Linux CentOS Linux 7.6.1810, x86_64, AMD EPYC 7601 32-Core Processor (zen), Python 2.7.5
See https://gist.github.com/0455f48810e27a8242c64cb2dcb00a19 for a full test report.

**Comment by migueldiascosta** [comment]
must have been a fluke...

**Review by migueldiascosta — APPROVED** [review]
lgtm

**Comment by migueldiascosta** [comment]
Going in, thanks @boegel!

**Pull request merged**
