### PR TITLE
{astro}[intel/2018b] plc v3.0.1 w/ Python 2.7.15

### PR DESCRIPTION
**Pull request by jose-d**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by jose-d** [comment]
Test report by @jose-d
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
koios1 - Linux centos linux 7.6.1810, Intel(R) Xeon(R) Gold 6130 CPU @ 2.10GHz, Python 2.7.5
See https://gist.github.com/8bce016d46412734a95f700dba3028ff for a full test report.

**Comment by jose-d** [comment]
dedicated PR for easyconfig from #7774 .

**Comment by smoors** [comment]
Test report by @smoors
**SUCCESS**
Build succeeded for 4 out of 4 (1 easyconfigs in this PR)
nic408 - Linux centos linux 7.5.1804, Intel(R) Xeon(R) Gold 6148 CPU @ 2.40GHz, Python 2.7.5
See https://gist.github.com/793dcfdd1b9331c08f8dbe72564a2d1d for a full test report.

**Comment by smoors** [comment]
Going in, thanks @jose-d!

**Pull request merged**
