### PR TITLE
fix ITK easyconfigs: switch to CMakePythonPackage easyblock, also enable -DITK_USE_SYSTEM_HDF5 configuration option, fix download URLs

### PR DESCRIPTION
**Pull request by Flamefire**
(created using `eb --new-pr`)

Having trouble with the ITK ECs. Major issue and workaround was to add `LC_ALL=C` to prebuildopts and using explicit "system" deps, i.e. dependencies installed via EasyBuild.

- fix some URLs (outdated/moved -.-)
- remove `-DCMAKE_BUILD_TYPE`
- use `build_shared_libs`
- don't use `l` as a local variable
- Use CMakePythonPackage as ITK is a prime example for that (no need to manually set PYTONPATH etc)

Requires:
- [x] https://github.com/easybuilders/easybuild-easyblocks/pull/2536

### CODE REVIEW

**Comment by Flamefire** [comment]
Test report by @Flamefire
Using easyblocks from PR(s) https://github.com/easybuilders/easybuild-easyblocks/pull/2536
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
taurusi6606.taurus.hrsk.tu-dresden.de - Linux RHEL 7.9, x86_64, Intel(R) Xeon(R) CPU E5-2680 v3 @ 2.50GHz (haswell), Python 2.7.5
See https://gist.github.com/a4716faa64ea1503ad432875cdfb2182 for a full test report.

**Comment by Flamefire** [comment]
Test report by @Flamefire
Using easyblocks from PR(s) https://github.com/easybuilders/easybuild-easyblocks/pull/2536
**SUCCESS**
Build succeeded for 19 out of 19 (14 easyconfigs in total)
taurusi6459.taurus.hrsk.tu-dresden.de - Linux RHEL 7.9, x86_64, Intel(R) Xeon(R) CPU E5-2680 v3 @ 2.50GHz (haswell), Python 2.7.5
See https://gist.github.com/0c11ce4fed461ac485eca9ddbce80ea4 for a full test report.

**Review by boegel — APPROVED** [review]
lgtm

**Comment by boegel** [comment]
Going in, thanks @Flamefire!

**Pull request merged**
