### PR TITLE
{phys}[foss/2020b] BerkeleyGW v2.1.0

### PR DESCRIPTION
**Pull request by migueldiascosta**
(created using `eb --new-pr`)

requires ~~https://github.com/easybuilders/easybuild-easyblocks/pull/2297~~ and ~~#11944~~

### CODE REVIEW

**Comment by boegel** [comment]
@boegelbot please test @ generoso
EB_ARGS="--include-easyblocks-from-pr 2297"

**Comment by verdurin** [comment]
Test report by @verdurin
Using easyblocks from PR(s) https://github.com/easybuilders/easybuild-easyblocks/pull/2297
**FAILED**
Build succeeded for 7 out of 8 (1 easyconfigs in total)
nuc.lan - Linux Fedora 32, x86_64, Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz, Python 3.8.6
See https://gist.github.com/2bc5f2dccefec9052ffe483d83013648 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
Using easyblocks from PR(s) https://github.com/easybuilders/easybuild-easyblocks/pull/2297
**FAILED**
Build succeeded for 0 out of 1 (1 easyconfigs in total)
node2624.swalot.os - Linux centos linux 7.9.2009, x86_64, Intel(R) Xeon(R) CPU E5-2660 v3 @ 2.60GHz (haswell), Python 3.6.8
See https://gist.github.com/96f78683a87cf62dfede7c292a7fedf7 for a full test report.

**Comment by boegel** [comment]
Failing test:

```

Match Eigenvalue  4 at k-pt 3   :

   Calculated value : 0.6800817811482597
   Reference value  : 0.6800817811482534
   Difference       : 6.32827124036339e-15
   Tolerance        : 6e-15

 Eigenvalue  4 at k-pt 3                : 	 [  FAIL  ] 
 ```

**Comment by migueldiascosta** [comment]
@boegel I'll try to reproduce that error (haswell + centos7 but not haswell + centos8...?), but since it's only slightly above the numerical tolerance, I don't think it's anything to worry about

@verdurin that's indeed a lot of failing tests, but some of them are segmentation faults... is there a stack ulimit, for instance?

**Comment by verdurin** [comment]
Test report by @verdurin
Using easyblocks from PR(s) https://github.com/easybuilders/easybuild-easyblocks/pull/2297
**FAILED**
Build succeeded for 47 out of 58 (1 easyconfigs in total)
easybuild-c7.novalocal - Linux centos linux 7.9.2009, x86_64, Intel Xeon Processor (Skylake, IBRS), Python 3.6.8
See https://gist.github.com/c1cd80395d1b8141431c25b6263d21fb for a full test report.

**Comment by verdurin** [comment]
Test report by @verdurin
Using easyblocks from PR(s) https://github.com/easybuilders/easybuild-easyblocks/pull/2297
**FAILED**
Build succeeded for 10 out of 11 (1 easyconfigs in total)
easybuild-c7.novalocal - Linux centos linux 7.9.2009, x86_64, Intel Xeon Processor (Skylake, IBRS), Python 3.6.8
See https://gist.github.com/6b3016fe99afead5b25cf3582003f324 for a full test report.

**Comment by verdurin** [comment]
@migueldiascosta these are not cluster nodes so don't have any special ulimit settings.

**Comment by migueldiascosta** [comment]
@boegelbot please test @ generoso

**Comment by migueldiascosta** [comment]
@boegel @verdurin can you try again?

**Comment by verdurin** [comment]
Test report by @verdurin
**FAILED**
Build succeeded for 0 out of 1 (1 easyconfigs in total)
nuc.lan - Linux Fedora 32, x86_64, Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz, Python 3.8.7
See https://gist.github.com/0499afe146da2d142c70591c58efa654 for a full test report.

**Comment by migueldiascosta** [comment]
thanks @verdurin - note that although https://github.com/easybuilders/easybuild-easyblocks/pull/2297 is already merged, you still need `--include-easyblocks-from-pr=2297` if you're not using an updated develop branch

**Comment by verdurin** [comment]
Test report by @verdurin
Using easyblocks from PR(s) https://github.com/easybuilders/easybuild-easyblocks/pull/2297
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
nuc.lan - Linux Fedora 32, x86_64, Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz, Python 3.8.7
See https://gist.github.com/b75cc94358dd64b588ca64b85cd825a7 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
node3507.doduo.os - Linux RHEL 8.2, x86_64, AMD EPYC 7552 48-Core Processor (zen2), Python 3.6.8
See https://gist.github.com/d3d34afdec46b63007b5606da41a9b85 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
node2610.swalot.os - Linux centos linux 7.9.2009, x86_64, Intel(R) Xeon(R) CPU E5-2660 v3 @ 2.60GHz (haswell), Python 3.6.8
See https://gist.github.com/99d3e18dae4dc67a3d8dde211b49077d for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
node3112.skitty.os - Linux centos linux 7.9.2009, x86_64, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz, Python 3.6.8
See https://gist.github.com/7c824ffcc7762ba6a11485208cff1e00 for a full test report.

**Comment by boegel** [comment]
@boegelbot PLEASE test @ generoso

**Comment by boegel** [comment]
@boegelbot Please test @ generoso

**Comment by migueldiascosta** [comment]
@boegelbot please test @ jsc-zen2

**Comment by migueldiascosta** [comment]
actually, closing since superseded by https://github.com/easybuilders/easybuild-easyconfigs/pull/14174

**Pull request closed without merging**
