### PR TITLE
{bio}[GCC/10.3.0] fastq-tools v0.8.3

### PR DESCRIPTION
**Pull request by SethosII**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by SethosII** [comment]
Test report by @SethosII
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
ribnode012 - Linux Ubuntu 20.04, x86_64, Intel(R) Xeon(R) CPU E5-2640 v2 @ 2.00GHz, Python 3.8.10
See https://gist.github.com/dcbf3e18e923b31311adcf8bdf1e9cf7 for a full test report.

**Comment by lexming** [comment]
Test report by @lexming
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
node381.hydra.os - Linux centos linux 7.9.2009, x86_64, Intel(R) Xeon(R) Gold 6148 CPU @ 2.40GHz, Python 2.7.5
See https://gist.github.com/c07830821cb8e68bc28a15453123b903 for a full test report.

**Review by lexming — APPROVED** [review]
LGTM

**Comment by lexming** [comment]
Going in, thanks @SethosII !

**Pull request merged**
