### PR TITLE
{bio}[foss/2022a] Trinotate v4.0.1, PyBioLib v1.1.988, MMseqs2 v14-7e284, Transdecoder v5.5.0 ... w/ Python 3.10.4

### PR DESCRIPTION
**Pull request by lexming**
(created using `eb --new-pr`)

## Trinotate + dependencies

New software:
* PyBioLib
* Trinotate

Updates:
* eggnog-mapper
* Infernal
* MMseqs2
* TransDecoder

### CODE REVIEW

**Comment by lexming** [comment]
@boegelbot: please test @ generoso

**Comment by verdurin** [comment]
Test report by @verdurin
**SUCCESS**
Build succeeded for 20 out of 20 (6 easyconfigs in total)
easybuild-c7.novalocal - Linux CentOS Linux 7.9.2009, x86_64, Intel Xeon Processor (Skylake, IBRS), Python 3.6.8
See https://gist.github.com/verdurin/6e5e3b8ec18109e7df5c0beb97c7bd20 for a full test report.

**Review by verdurin — APPROVED** [review]
Looks fine.

**Comment by verdurin** [comment]
Going in, thanks @lexming!

**Pull request merged**
