### PR TITLE
[intel/2018a] [Python/3.6.4] OpenCV-Python v3.4.4.19

### PR DESCRIPTION
**Pull request by SimonPinches**

### CODE REVIEW

**Comment by vanzod** [comment]
Test report by @vanzod
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
cermis - Linux debian 9.5, Intel(R) Xeon(R) CPU           E5620  @ 2.40GHz, Python 2.7.13
See https://gist.github.com/bc87dba4bbefebc88e84efe2f0c8d5d2 for a full test report.

**Comment by vanzod** [comment]
@SimonPinches Is there a specific reason you are installing it from a wheel instead of building it from source as we typically do?

**Comment by SimonPinches** [comment]
@vanzod I installed from a wheel through a combination of ignorance and convenience!  If I find time, I can try and build from scratch but when I started out this way I quickly ran into problems and I needed to to make an installation ASAP for our own internal use.

**Comment by vanzod** [comment]
@boegel Thoughts?

**Comment by SimonPinches** [comment]
I think this PR can be declined / closed since I now agree that it adds nothing that isn't already provided by the `OpenCV` modules.

**Pull request closed without merging**
