### PR TITLE
{perf}[GCCcore/10.3.0] OTF2 v2.3, SIONlib v1.7.6

### PR DESCRIPTION
**Pull request by stefan-wolfsheimer**

### CODE REVIEW

**Comment by robert-mijakovic** [comment]
Test report by @robert-mijakovic
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in total)
login01.meluxina.lxp.lu - Linux RHEL 8.3, x86_64, AMD EPYC 7452 32-Core Processor (zen2), Python 3.6.8
See https://gist.github.com/cef9e92a63eb98d03b67a6bf54b1d5e8 for a full test report.

**Comment by robert-mijakovic** [comment]
@boegelbot please test @ generoso

**Comment by verdurin** [comment]
Test report by @verdurin
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in total)
nuc.lan - Linux Fedora 33, x86_64, Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz, Python 3.9.5
See https://gist.github.com/d7173bc5faaeda799e1e264975888629 for a full test report.

**Review by verdurin — APPROVED** [review]
Looks fine.

**Comment by verdurin** [comment]
Going in, thanks @stefan-wolfsheimer!

**Pull request merged**
