### PR TITLE
[goolf/1.4.10] PyCUDA-2012.1-goolf-1.4.10-Python-2.7.3-CUDA-5.5.22.eb (REVIEW)

### PR DESCRIPTION
**Pull request by fgeorgatos**
If #545 gets supported in the framework, I could provide some more PyCUDA easyconfigs
(@boegel, it worths checking out that one, 'cause I got stuck somewhere in the toolchaining business)

### CODE REVIEW

**Comment by fgeorgatos** [comment]
anybody with GPUs caring to help merging this? (let's say, I have no access to GPUs now :-)
it has been working for me in the past, so any further work should be trivialities...

**Comment by boegel** [comment]
@fgeorgatos: ping on this?

I'm cleaning up the oldest PRs, in an effort to reduce the pile of open PRs.

Is this still relevant? Any idea of the amount of extra effort required to get it ready for merge?

**Comment by fgeorgatos** [comment]
I'm on it

**Comment by fgeorgatos** [comment]
the 2 historic ones of this PR are very stubborn; I even discovered lurking Boost dep;
(I suspect diff between PYPI & github tags, otherwise I cannot explain it any better)

in the meantime, this one works without issues: (for differential debugging)
```
$ time eb --from-pr 571 PyCUDA-2013.1.1-goolf-1.4.10-Python-2.7.3-CUDA-5.5.22.eb --try-software-version=2016.1.1 -f
== temporary log file in case of crash /tmp/eb-brIfKR/easybuild-VAWey8.log
== processing EasyBuild easyconfig /tmp/eb-brIfKR/tweaked_easyconfigs/PyCUDA-2016.1.1-goolf-1.4.10-Python-2.7.3-CUDA-5.5.22.eb
== building and installing PyCUDA/2016.1.1-goolf-1.4.10-Python-2.7.3-CUDA-5.5.22...
== fetching files...
== creating build dir, resetting environment...
== unpacking...
== patching...
== preparing...
== configuring...
== building...
== testing...
== installing...
== taking care of extensions...
== postprocessing...
== sanity checking...
== cleaning up...
== creating module...
== permissions...
== packaging...
== COMPLETED: Installation ended successfully
== Results of the build can be found in the log file /home/fgeorgatos/.local/easybuild/software/PyCUDA/2016.1.1-goolf-1.4.10-Python-2.7.3-CUDA-5.5.22/easybuild/easybuild-PyCUDA-2016.1.1-20160616.203145.log
== Build succeeded for 1 out of 1
== Temporary log file(s) /tmp/eb-brIfKR/easybuild-VAWey8.log* have been removed.
== Temporary directory /tmp/eb-brIfKR has been removed.

real    2m18.661s
user    1m45.819s
sys     0m11.223s
```

**Comment by fgeorgatos** [comment]
this one worked:
`time eb --from-pr 571 PyCUDA-2013.1.1-goolf-1.4.10-Python-2.7.3-CUDA-5.5.22.eb --try-software-version=2016.1.1 -f`

**Comment by fgeorgatos** [comment]
ping on this one? at least one of the easyconfigs should be alright, no?

**Comment by boegel** [comment]
Well, either both easyconfigs should work, or the older one should be removed...

**Comment by fgeorgatos** [comment]
@boegel: could you remove here for me whatever doesn't cut it, and merge the rest?!

**Comment by fgeorgatos** [comment]
@boegel : please merge in the working one and ignore the other!

**Comment by wpoely86** [comment]
Let's close this one in favour of #4523 @fgeorgatos ?

**Comment by boegel** [comment]
+1 on that @fgeorgatos, let us know (or just close)

**Comment by boegel** [comment]
ping @fgeorgatos?

**Comment by rjeschmi** [comment]
Isn't this irrelevant now due to the age of cuda here? CUDA 5 is probably too old to be interesting now, no?

**Comment by migueldiascosta** [comment]
@fgeorgatos, this PR is being closed for the following reason(s): obsolete, no activity.
Please don't hesitate to reopen this PR or add a comment if you feel this contribution is still relevant.
For more information on our policy w.r.t. closing PRs, see https://easybuild.readthedocs.io/en/latest/Contributing.html#why-a-pull-request-may-be-closed-by-a-maintainer

**Pull request closed without merging**
