### PR TITLE
{data}[intel/iomkl 2018b] CDO 1.9.5 and ncview 2.1.7 w/ deps (REVIEW)

### PR DESCRIPTION
**Pull request by hajgato**

### CODE REVIEW

**Comment by smoors** [comment]
Test report by @smoors
**FAILED**
Build succeeded for 8 out of 10 (10 easyconfigs in this PR)
nic412 - Linux centos linux 7.5.1804, Intel(R) Xeon(R) Gold 6148 CPU @ 2.40GHz, Python 2.7.5
See https://gist.github.com/a6483d681fe8f23a87e977b13c303cba for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 10 out of 10 (10 easyconfigs in this PR)
node2119.delcatty.os - Linux centos linux 7.6.1810, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.7.5
See https://gist.github.com/ed64c493fcdb94207f00790669d39f55 for a full test report.

**Comment by boegel** [comment]
@smoors test failed due to download error `HTTP Error 500: Proxy Error`?

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 13 out of 13 (10 easyconfigs in this PR)
node3100.skitty.os - Linux centos linux 7.6.1810, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz, Python 2.7.5
See https://gist.github.com/1f98ee852eb2dfe3c2de4953c4a73469 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 13 out of 13 (10 easyconfigs in this PR)
node2405.golett.os - Linux centos linux 7.6.1810, Intel(R) Xeon(R) CPU E5-2680 v3 @ 2.50GHz, Python 2.7.5
See https://gist.github.com/a5e70bc547b3cab114961fa6ee013753 for a full test report.

**Comment by boegel** [comment]
Going in, thanks @hajgato!

**Comment by smoors** [comment]
@boegel why am I getting a proxy error but you don't?

**Comment by boegel** [comment]
@smoors Must be a local site issue, maybe due to firewall?
Can you reproduce the error with e.g. `curl`?

**Comment by smoors** [comment]
curl does not work either, the error suggests it is a problem at their side.
I've contacted them.

**Pull request merged**
