### PR TITLE
{numlib}[foss/2022a] PETSc v3.17.4 w/ Python 3.10.4

### PR DESCRIPTION
**Pull request by satishskamath**
(created using `eb --new-pr`)

edit: requires https://github.com/easybuilders/easybuild-easyblocks/pull/2796

### CODE REVIEW

**Comment by satishskamath** [comment]
https://github.com/easybuilders/easybuild-easyblocks/pull/2796

**Comment by boegel** [comment]
@boegelbot please test @ generoso
EB_ARGS="--include-easyblocks 2796"

**Comment by boegel** [comment]
Test report by @boegel
Using easyblocks from PR(s) https://github.com/easybuilders/easybuild-easyblocks/pull/2796
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
node3135.skitty.os - Linux RHEL 8.4, x86_64, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz (skylake_avx512), Python 3.6.8
See https://gist.github.com/76e2041db7de6bc3dbcf51fce6593384 for a full test report.

**Review by boegel — APPROVED** [review]
lgtm

**Pull request merged**
