### PR TITLE
Add PMIx and friends as deps to OpenMPI 4.0.3 CUDA variants (and 4.0.5)

### PR DESCRIPTION
**Pull request by Micket**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by Micket** [comment]
@boegelbot please test @ generoso

**Comment by Micket** [comment]
Test report by @Micket
**SUCCESS**
Build succeeded for 7 out of 7 (3 easyconfigs in this PR)
vera-c1 - Linux centos linux 7.8.2003, x86_64, Intel Xeon Processor (Skylake), Python 2.7.5
See https://gist.github.com/e3ce3e24b019e532599034313dc92eac for a full test report.

**Review by bartoldeman — APPROVED** [review]
LGTM

**Comment by bartoldeman** [comment]
Going in, thanks @Micket!

**Pull request merged**
