### PR TITLE
{lib}[GCCcore/10.3.0,system/system] JavaFX v16+8, ControlsFX v11.1.0

### PR DESCRIPTION
**Pull request by jfgrimm**
(created using `eb --new-pr`)
depends on:
- [x] #13891 
- [x] #13892 
- [x] #13893

### CODE REVIEW

**Comment by boegel** [comment]
@boegelbot please test @ generoso

**Comment by jfgrimm** [comment]
hmm, it's failing to build `JavaFX` with `gcc: error trying to exec 'cc1plus': execvp: No such file or directory`

**Comment by boegel** [comment]
> hmm, it's failing to build `JavaFX` with `gcc: error trying to exec 'cc1plus': execvp: No such file or directory`

That looks very strange... Is it confused because GCC is not installed in a standard location?

**Comment by boegel** [comment]
Test report by @boegel
**FAILED**
Build succeeded for 2 out of 3 (2 easyconfigs in total)
node3580.doduo.os - Linux RHEL 8.2, x86_64, AMD EPYC 7552 48-Core Processor (zen2), Python 3.6.8
See https://gist.github.com/3df66c9e621e40c1905710084aad3c5c for a full test report.

**Comment by jfgrimm** [comment]
> That looks very strange... Is it confused because GCC is not installed in a standard location?

I guess? I didn't see the error when building on my system, but it's probably picking up system libraries

**Comment by jfgrimm** [comment]
it's downloading and building some extra dependencies (swt, antlr4) on the fly; I suspect that may be causing some issues

**Review by jfgrimm — COMMENTED** [review]
As decided in issue #16330, we have deprecated the use of `True` to signify a system-toolchain dependency (#16384), in favour of the more intuitive `SYSTEM` template constant. Due to the change in the test suite, please run `eb --sync-pr-with-develop 13894` and update the PR to use `SYSTEM` instead.

**Pull request closed without merging**
