### PR TITLE
{math}[foss/2022a] gkmSVM v0.82.0 w/ R 4.2.1

### PR DESCRIPTION
**Pull request by migueldiascosta**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by migueldiascosta** [comment]
@boegelbot please test @ generoso

**Comment by migueldiascosta** [comment]
@boegelbot please test @ jsc-zen2

**Comment by smoors** [comment]
@boegelbot: please test @ generoso

**Comment by smoors** [comment]
the test on generoso was successful but the report did not come back for some reason
> == COMPLETED: Installation ended successfully (took 1 min 23 secs)
== Results of the build can be found in the log file(s) /project/boegelbot/Rocky8/haswell/software/gkmSVM/0.82.0-foss-2022a-R-4.2.1/easybuild/easybuild-gkmSVM-0.82.0-20230829.141704.log

i am seeing 403 error in the slurm log file, maybe that's related
> $ cat /project/boegelbot/slurmjobs/slurm-11579.out
Traceback (most recent call last):
  File "/usr/lib64/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib64/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/boegelbot/easybuild/easybuild-framework/easybuild/main.py", line 756, in <module>
    main(prepared_cfg_data=(init_session_state, eb_go, cfg_settings))
  File "/home/boegelbot/easybuild/easybuild-framework/easybuild/main.py", line 717, in main
    hooks, do_build)
  File "/home/boegelbot/easybuild/easybuild-framework/easybuild/main.py", line 567, in process_eb_args
    test_report_msg = overall_test_report(ecs_with_res, len(paths), overall_success, success_msg, init_session_state)
  File "/home/boegelbot/easybuild/easybuild-framework/easybuild/tools/testing.py", line 401, in overall_test_report
    success)
  File "/home/boegelbot/easybuild/easybuild-framework/easybuild/tools/testing.py", line 311, in post_pr_test_report
    gist_url = upload_test_report_as_gist(test_report['full'], descr=descr, fn=fn)
  File "/home/boegelbot/easybuild/easybuild-framework/easybuild/tools/testing.py", line 284, in upload_test_report_as_gist
    gist_url = create_gist(test_report, descr=descr, fn=fn, github_user=github_user)
  File "/home/boegelbot/easybuild/easybuild-framework/easybuild/tools/github.py", line 597, in create_gist
    status, data = g.gists.post(body=body)
  File "/home/boegelbot/easybuild/easybuild-framework/easybuild/base/rest.py", line 139, in post
    return self.request(self.POST, url, json.dumps(body), headers, content_type='application/json')
  File "/home/boegelbot/easybuild/easybuild-framework/easybuild/base/rest.py", line 176, in request
    conn = self.get_connection(method, url, body, headers)
  File "/home/boegelbot/easybuild/easybuild-framework/easybuild/base/rest.py", line 217, in get_connection
    connection = self.opener.open(request)
  File "/usr/lib64/python3.6/urllib/request.py", line 532, in open
    response = meth(req, response)
  File "/usr/lib64/python3.6/urllib/request.py", line 642, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib64/python3.6/urllib/request.py", line 570, in error
    return self._call_chain(*args)
  File "/usr/lib64/python3.6/urllib/request.py", line 504, in _call_chain
    result = func(*args)
  File "/usr/lib64/python3.6/urllib/request.py", line 650, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 403: Forbidden
...

**Comment by smoors** [comment]
@boegelbot: please test @ generoso

**Comment by smoors** [comment]
@boegelbot please test @ jsc-zen2

**Comment by smoors** [comment]
Test report by @smoors
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
node378.hydra.os - Linux CentOS Linux 7.9.2009, x86_64, Intel(R) Xeon(R) Gold 6148 CPU @ 2.40GHz (skylake_avx512), Python 3.6.8
See https://gist.github.com/smoors/ad35275ac1bcf134c6ba750a3518e5d9 for a full test report.

**Review by smoors — APPROVED** [review]
lgtm

**Comment by smoors** [comment]
Going in, thanks @migueldiascosta!

**Pull request merged**
