### PR TITLE
[R 3.6.2] Fix build on Power9

### PR DESCRIPTION
**Pull request by Flamefire**
(created using `eb --new-pr`)

For build in Power9 requires:
- [x] #9764
  - [x] https://github.com/easybuilders/easybuild-easyblocks/pull/1892
- [ ] https://github.com/easybuilders/easybuild-easyblocks/pull/1949
- [x] https://github.com/easybuilders/easybuild-easyconfigs/pull/9694

### CODE REVIEW

**Comment by Flamefire** [comment]
Test report by @Flamefire
**FAILED**
Build succeeded for 0 out of 2 (2 easyconfigs in this PR)
taurusml29 - Linux RHEL 7.6, 8335-GTX, Python 2.7.5
See https://gist.github.com/4e686bfd963dff13c2756792a04bb146 for a full test report.

**Comment by Flamefire** [comment]
Test report by @Flamefire
**FAILED**
Build succeeded for 2 out of 4 (2 easyconfigs in this PR)
taurusml30 - Linux RHEL 7.6, 8335-GTX, Python 2.7.5
See https://gist.github.com/ba832ab3af40b1dbc69cf22c78683467 for a full test report.

**Comment by boegel** [comment]
@Flamefire Does this depend on other PRs, or did you accidentally mess up the test environment?

**Comment by Flamefire** [comment]
Depends. It fixes compilation of R as-is. The extensions aren't fixed yet. E.g. liquidSVN needs to be removed: https://github.com/easybuilders/easybuild-easyconfigs/pull/9544/files#r365531097

I updated the initial description with the dependencies for Power9

**Comment by Flamefire** [comment]
@boegel Regarding liquidSVM: It seems it won't use the std flag for cuda which would solve the issue (tried patching it manually)

So either we patch their https://github.com/liquidSVM/liquidSVM/blob/da19280562f443ab2b1fca898862f76c4ebc0bbd/bindings/R/liquidSVM/configure somehow or remove liquidSVM indeed, but that would be hard to argue for (as it works for most). I'm also concerned about it "Using target: generic" (see logs) but that might be R...

**Comment by Flamefire** [comment]
Test report by @Flamefire
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in this PR)
taurusml18 - Linux RHEL 7.6, 8335-GTX, Python 2.7.5
See https://gist.github.com/c9b22d0613fb88f1f8670a2bfaf3bb40 for a full test report.

**Comment by Flamefire** [comment]
@boegel Can this (and the related PRs) be addressed soonish? As per my last test report this makes R build on Power9, so IMO those are good to go :)

@edmondac You might want to give this a spin too. You already have most of the dependencies so you only need the rpackage EB to test this.

**Comment by Flamefire** [comment]
Test report by @Flamefire
**FAILED**
Build succeeded for 1 out of 6 (2 easyconfigs in this PR)
taurusi6124.taurus.hrsk.tu-dresden.de - Linux RHEL 7.7, Intel(R) Xeon(R) CPU E5-2680 v3 @ 2.50GHz, Python 2.7.5
See https://gist.github.com/6bba87ee2353ca59f8abca8a1830f0cd for a full test report.

**Comment by verdurin** [comment]
@Flamefire Would be good to see a test from another POWER9 machine if possible.
I suppose a test from an x86_64 machine would be good too, to show this doesn't break anything there.

**Comment by Flamefire** [comment]
Working on a x86 report. @edmondac can probably provide one from another Power9

**Comment by Flamefire** [comment]
Test report by @Flamefire
**SUCCESS**
Build succeeded for 5 out of 5 (2 easyconfigs in this PR)
taurusi5070.taurus.hrsk.tu-dresden.de - Linux RHEL 7.7, Intel(R) Xeon(R) CPU E5-2680 v3 @ 2.50GHz, Python 2.7.5
See https://gist.github.com/65afd0342680641802988cc9d5f87d0e for a full test report.

**Comment by edmondac** [comment]
Test reports running now...

**Comment by edmondac** [comment]
Test report by @bear-rsg
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in this PR)
bear-pg0212u17a.bear.cluster - Linux centos linux 7.7.1908, Intel(R) Xeon(R) CPU E5-2640 v4 @ 2.40GHz, Python 2.7.5
See https://gist.github.com/7f3f795746c684a2983b96c7860cebe6 for a full test report.

**Comment by edmondac** [comment]
Test report by @bear-rsg
**SUCCESS**
Build succeeded for 10 out of 10 (2 easyconfigs in this PR)
bear-pg0305u11a.bear.cluster - Linux RHEL 7.6, 8335-GTX, Python 2.7.5
See https://gist.github.com/1900f4ff92c3d36fa98c111f5609c16a for a full test report.

**Comment by edmondac** [comment]
@verdurin I've added a test report for x86_64 and another for ppc64le

**Comment by Flamefire** [comment]
@migueldiascosta Can this be merged? Pending the other PRs for fully building, but it does improve it and does not break anything. It just errors at different stages on Power without the other PRs. (Of course would be great to have them merged too, but some are not fully ready yet)

**Comment by migueldiascosta** [comment]
Test report by @migueldiascosta
**FAILED**
Build succeeded for 1 out of 2 (2 easyconfigs in this PR)
generoso-3 - Linux centos linux 7.6.1810, Intel(R) Xeon(R) CPU E5-2660 v4 @ 2.00GHz, Python 3.6.8
See https://gist.github.com/8a5c596b2809d6ca011024ae3e45d7d5 for a full test report.

**Comment by Flamefire** [comment]
@migueldiascosta Failed to remove the folder? The error is way to generic. Better: https://github.com/easybuilders/easybuild-framework/pull/3228

**Comment by zao** [comment]
Test report by @zao
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in this PR)
freja - Linux ubuntu 18.04, Intel(R) Core(TM) i7-8700K CPU @ 3.70GHz, Python 2.7.17
See https://gist.github.com/d4adc9e70e01a3252af3b8db1f34448b for a full test report.

**Comment by Flamefire** [comment]
Rebased to develop, running tests on x86 and Power9 without https://github.com/easybuilders/easybuild-easyblocks/pull/1949 now

**Comment by Flamefire** [comment]
Test report by @Flamefire
**FAILED**
Build succeeded for 8 out of 10 (2 easyconfigs in this PR)
taurusml30 - Linux RHEL 7.6, 8335-GTX, Python 2.7.5
See https://gist.github.com/f722a02ccf19048a97508bd1247bf3ce for a full test report.

**Comment by Flamefire** [comment]
Test report by @Flamefire
**SUCCESS**
Build succeeded for 5 out of 5 (2 easyconfigs in this PR)
taurusi6309.taurus.hrsk.tu-dresden.de - Linux RHEL 7.7, Intel(R) Xeon(R) CPU E5-2680 v3 @ 2.50GHz, Python 2.7.5
See https://gist.github.com/274c03dba2a5a5a6a50032783b38f6c7 for a full test report.

**Comment by Flamefire** [comment]
x86 succeeded and Power failed (as expected)

Running tests with https://github.com/easybuilders/easybuild-easyblocks/pull/1949 now

**Comment by branfosj** [comment]
I've also set off x86 and Power tests of this PR using https://github.com/easybuilders/easybuild-easyblocks/pull/1949

**Comment by branfosj** [comment]
Test report by @branfosj
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
bear-pg0211u03a.bear.cluster - Linux centos linux 7.7.1908, Intel(R) Xeon(R) Gold 6248 CPU @ 2.50GHz (cascadelake), Python 3.6.8
See https://gist.github.com/0767337ba743adc8ac8a4aa8a4549a60 for a full test report.

**Comment by branfosj** [comment]
Test report by @branfosj
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in this PR)
bear-pg0212u15b.bear.cluster - Linux centos linux 7.7.1908, Intel(R) Xeon(R) CPU E5-2640 v4 @ 2.40GHz (broadwell), Python 3.6.8
See https://gist.github.com/5df1b40a1564ecb3130cd1a937ed2680 for a full test report.

**Comment by branfosj** [comment]
Test report by @branfosj
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in this PR)
bear-pg0305u19a.bear.cluster - Linux RHEL 7.6, 8335-GTX (power9le), Python 3.6.8
See https://gist.github.com/51cb983cfd451cd01b2929c5b920d3d6 for a full test report.

**Comment by Flamefire** [comment]
Test report by @Flamefire
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in this PR)
taurusi6205.taurus.hrsk.tu-dresden.de - Linux RHEL 7.7, Intel(R) Xeon(R) CPU E5-2680 v3 @ 2.50GHz, Python 2.7.5
See https://gist.github.com/42bc22a9e2bcc12a99c5d06e8af14bee for a full test report.

**Comment by Flamefire** [comment]
Test report by @Flamefire
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in this PR)
taurusml22 - Linux RHEL 7.6, 8335-GTX, Python 2.7.5
See https://gist.github.com/826a9107bb839d56f1c094020d4a192d for a full test report.

**Comment by lexming** [comment]
Test report by @lexming
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in this PR)
node154.hydra.os - Linux centos linux 7.7.1908, x86_64, Intel(R) Xeon(R) CPU E5-2680 v2 @ 2.80GHz, Python 2.7.5
See https://gist.github.com/92fa6ee533c96608923ab2103da3d0fd for a full test report.

**Comment by lexming** [comment]
Test report by @lexming
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in this PR)
node150.hydra.os - Linux centos linux 7.7.1908, x86_64, Intel(R) Xeon(R) CPU E5-2680 v2 @ 2.80GHz, Python 2.7.5
See https://gist.github.com/2e6e7a4283aa4be7c9503eb36ac4e6a8 for a full test report.

**Comment by lexming** [comment]
Going in, thanks @Flamefire !

**Comment by Flamefire** [comment]
Great! Now only https://github.com/easybuilders/easybuild-easyblocks/pull/1949 is missing for Power support of R. Added the change I was talking about there so should be ready to merge after CI ran through.

**Pull request merged**
