### PR TITLE
{bio}[goolf-1.7.20, goolfc-2.7.11] io_lib 1.14.6 [REVIEW]

### PR DESCRIPTION
**Pull request by npklein**

### CODE REVIEW

**Comment by npklein** [comment]
Test report by @npklein
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
Linux SL 6.7, Intel(R) Xeon(R) CPU E5-2697 v2 @ 2.70GHz, Python 2.7.9
See https://gist.github.com/8eba42bd5132d14e9b51 for a full test report.

**Comment by boegel** [comment]
Jenkins: test this please

**Comment by boegel** [comment]
@npklein: missing toolchain? please open a separate PR for this

```
EasyBuildError: 'Irresolvable dependencies encountered: goolfc/2.7.11'
```

**Comment by migueldiascosta** [comment]
@npklein, this PR is being closed for the following reason(s): no activity for > 6 months, obsoleted by more recent PRs.
Please don't hesitate to reopen this PR or add a comment if you feel this contribution is still relevant.
For more information on our policy w.r.t. closing PRs, see https://easybuild.readthedocs.io/en/latest/Contributing.html#why-a-pull-request-may-be-closed-by-a-maintainer

**Pull request closed without merging**
