### PR TITLE
{phys}[foss/2019a] TRIQS v2.2.3, TRIQS-cthyb v2.2.1, TRIQS-dft_tools v2.2.1 w/ Python 2.7.15

### PR DESCRIPTION
**Pull request by rokzitko**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by rokzitko** [comment]
I need advice on handling this versioning issue. The TRIQS applications are released independently from the main TRIQS library, and they depend on the most recent TRIQS library version at the moment of application release. Should this version information be included in the version suffix or not? E.g.:

name = 'TRIQS-cthyb'
version = '2.2.1'
versionsuffix = '-TRIQS-2.2.3-Python-%(pyver)s'

Are there other ways to handle this?

**Comment by boegel** [comment]
@rokzitko As also explained on the mailing list (see https://lists.ugent.be/wws/arc/easybuild/2020-08/msg00010.html), we'll need to add an exception to the tests for this.

Are you up for looking into this yourself, based on my suggestions in the mailing list?

Do let us know if you need help with this!

**Comment by rokzitko** [comment]
Dear Kenneth,

We are still considering what the best solution would be. The different TRIQS applications should ideally be interoperable, i.e., their modules loaded at the same time, but this could indeed lead to either clashing version of the library or the need for synchronized releases of applications.

Kind regards,
Rok

**Comment by rokzitko** [comment]
Dear Kenneth,

We are still considering what the best solution might be here. The different TRIQS applications should ideally be interoperable, i.e., their modules loaded at the same time, which places some constraints on the best solution. We’ll get back to you if we need help implementing it, once the decision is made.

Kind regards,
Rok

**Comment by rokzitko** [comment]
Agreed, this is no longer relevant. Closing this PR.

**Pull request closed without merging**
