### PR TITLE
{compiler}[GCCcore/8.2.0] Clang v8.0.0 w/ CUDA 10.1.105

### PR DESCRIPTION
**Pull request by ocaisa**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by ocaisa** [comment]
Requires https://github.com/easybuilders/easybuild-easyblocks/pull/1716

**Comment by ocaisa** [comment]
This PR aligns with 2019a toolchains but are not the exact ones at JSC (where I have tested the easyblock). I can upload a test report but it will not be exactly the same easyconfig (but logically the same).

**Comment by Micket** [comment]
Should we include lld in the non-cuda version as well?
Also, like ocaisa said in #8254, it also applies here, so that it becomes a "proper" compiler?

**Comment by ocaisa** [comment]
Test report for the easyblock (but JSC-specific easyconfig) at https://gist.github.com/ocaisa/d3c53e6ee8b4f549a365e8342ffe97ad

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
node2727.swalot.os - Linux centos linux 7.6.1810, Intel(R) Xeon(R) CPU E5-2660 v3 @ 2.60GHz, Python 2.7.5
See https://gist.github.com/0ee8f8d62c2a9fa7107509546581327f for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 2 out of 2 (1 easyconfigs in this PR)
node3101.skitty.os - Linux centos linux 7.6.1810, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz, Python 2.7.5
See https://gist.github.com/e12b4c26b4ee64dc140197baaeace152 for a full test report.

**Comment by boegel** [comment]
@ocaisa let me know if you plan to make more changes w.r.t. using this in a toolchain setting or not...

@Micket I guess enabled the build of `lld` in the non-CUDA version makes sense... Up for issuing a PR for that now https://github.com/easybuilders/easybuild-easyblocks/pull/1716 is merged?

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
node2070.delcatty.os - Linux centos linux 7.6.1810, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.7.5
See https://gist.github.com/7dda0e81521b5607709ed236504904d1 for a full test report.

**Comment by ocaisa** [comment]
This should be replaced by #8284

**Pull request closed without merging**
