### PR TITLE
rename ega-quickview to EGA-QuickView

### PR DESCRIPTION
**Pull request by boegel**
follow-up for #20870

### CODE REVIEW

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
node3104.skitty.os - Linux RHEL 8.8, x86_64, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz, Python 3.6.8
See https://gist.github.com/boegel/02d3323ab752f822454f04cf199d6df0 for a full test report.

**Comment by boegel** [comment]
@boegelbot please test @ generoso

**Review by bedroge — APPROVED** [review]
Lgtm

**Comment by bedroge** [comment]
Going in, thanks @boegel!

**Pull request merged**
