### PR TITLE
{vis}[GCC/10.2.0] VirtualGL v2.6.5

### PR DESCRIPTION
**Pull request by sassy-crick**
(created using `eb --new-pr`)

### CODE REVIEW

**Review by Micket — DISMISSED** [review]
lgtm

**Comment by Micket** [comment]
Test report by @Micket
**FAILED**
Build succeeded for 0 out of 1 (1 easyconfigs in total)
alvis-c1 - Linux centos linux 7.9.2009, x86_64, Intel Xeon Processor (Skylake), Python 3.6.8
See https://gist.github.com/a16e0b901393e1ddeaa19dd0c4229682 for a full test report.

**Comment by sassy-crick** [comment]
It looks like `OpenCL` needs to be installed on the system. Shall I somehow include that, a we do for `ssl` ?

**Comment by boegel** [comment]
@sassy-crick Maybe try using `pocl` as a dependency?

**Comment by sassy-crick** [comment]
Good idea, I have added `pocl` . Lets hope no more issues are popping up. Thanks!

**Comment by boegel** [comment]
closing this since `GCC/10.2.0` is deprecated, see https://docs.easybuild.io/policies/toolchains

**Pull request closed without merging**
