### PR TITLE
{tools}[foss/2017b] NCO v4.7.4, ANTLR v2.7.7, libdap v3.19.1

### PR DESCRIPTION
**Pull request by arielzn**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by arielzn** [comment]
A note on this PR, it seems that the checksum for ` libdap-3.19.1.tar.gz` changed back to the original value,

I had to revert this https://github.com/easybuilders/easybuild-easyconfigs/commit/19d037e91a2edbdd26f87a4797e972bcd50d29e4  when I ported the libdap easyconfig on this PR .

**Comment by boegel** [comment]
@arielzn The `libdap` checksum issue was also raised in #5471, fixed (again) in #6305

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 3 out of 3 (3 easyconfigs in this PR)
node2581.golett.os - Linux centos linux 7.4.1708, Intel(R) Xeon(R) CPU E5-2680 v3 @ 2.50GHz, Python 2.7.5
See https://gist.github.com/ba77e1fa467c90c2c648c5517466c470 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 3 out of 3 (3 easyconfigs in this PR)
node2082.delcatty.os - Linux centos linux 7.4.1708, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.7.5
See https://gist.github.com/7237ec60b79818eb13b3e3dbc8ced094 for a full test report.

**Comment by boegel** [comment]
Going in, thanks @arielzn!

**Pull request merged**
