### PR TITLE
{data}[GCCcore/9.3.0] DB_File v1.835

### PR DESCRIPTION
**Pull request by FokkeDijkstra**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by Micket** [comment]
Test report by @Micket
**FAILED**
Build succeeded for 0 out of 2 (1 easyconfigs in this PR)
hebbe-c1 - Linux centos linux 7.8.2003, x86_64, Intel Core Processor (Haswell, no TSX), Python 2.7.5
See https://gist.github.com/7eb4896df5f0ff4679451f0bc4384623 for a full test report.

**Comment by Micket** [comment]
Well, I didn't realize I needed an oracle registration and manually download berkeley DB. Could you please supply a build report instead?
`eb --from-pr 10780 --upload-test-report --rebuild`

**Comment by lexming** [comment]
Test report by @lexming
**FAILED**
Build succeeded for 0 out of 2 (1 easyconfigs in this PR)
node109.hydra.os - Linux centos linux 7.7.1908, x86_64, Intel(R) Xeon(R) CPU E5-2680 v2 @ 2.80GHz, Python 2.7.5
See https://gist.github.com/d03bd8aa9621e410c086f093783a0433 for a full test report.

**Comment by lexming** [comment]
Test report by @lexming
**SUCCESS**
Build succeeded for 2 out of 2 (1 easyconfigs in this PR)
node100.hydra.os - Linux centos linux 7.7.1908, x86_64, Intel(R) Xeon(R) CPU E5-2680 v2 @ 2.80GHz, Python 2.7.5
See https://gist.github.com/0df31e7756d7c07263fefa714fee7a0c for a full test report.

**Comment by lexming** [comment]
Going in, thanks @FokkeDijkstra !

**Pull request merged**
