### PR TITLE
[GCCcore-8.3.0] Perl-5.30.0: Added Term::ReadLine::Gnu, which requires ncurses as a dependency.

### PR DESCRIPTION
**Pull request by terjekv**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by terjekv** [comment]
Test report by @terjekv
**SUCCESS**
Build succeeded for 0 out of 0 (1 easyconfigs in this PR)
ninhursaga.uio.no - Linux red hat enterprise linux 8.1, Intel(R) Xeon(R) Silver 4216 CPU @ 2.10GHz, Python 3.6.8
See https://gist.github.com/6fbd7e6aaf5dc5941270c8cc39f33c7e for a full test report.

**Comment by terjekv** [comment]
Test report by @terjekv
**FAILED**
Build succeeded for 0 out of 1 (1 easyconfigs in this PR)
ninhursaga.uio.no - Linux red hat enterprise linux 8.1, Intel(R) Xeon(R) Silver 4216 CPU @ 2.10GHz, Python 3.6.8
See https://gist.github.com/d351c85f4277e44b06bc59a01177e6a7 for a full test report.

**Comment by terjekv** [comment]
Test report by @terjekv
**FAILED**
Build succeeded for 0 out of 1 (1 easyconfigs in this PR)
ninhursaga.uio.no - Linux red hat enterprise linux 8.1, Intel(R) Xeon(R) Silver 4216 CPU @ 2.10GHz, Python 3.6.8
See https://gist.github.com/8fd15a7c92913e74453c1dfdc8a370e9 for a full test report.

**Comment by terjekv** [comment]
Test report by @terjekv
**FAILED**
Build succeeded for 0 out of 1 (1 easyconfigs in this PR)
ninhursaga.uio.no - Linux red hat enterprise linux 8.1, Intel(R) Xeon(R) Silver 4216 CPU @ 2.10GHz, Python 3.6.8
See https://gist.github.com/4f78a52690f570e29110cd4c1bed4892 for a full test report.

**Comment by terjekv** [comment]
> Test report by @terjekv
> **FAILED**
> Build succeeded for 0 out of 1 (1 easyconfigs in this PR)
> ninhursaga.uio.no - Linux red hat enterprise linux 8.1, Intel(R) Xeon(R) Silver 4216 CPU @ 2.10GHz, Python 3.6.8
> See https://gist.github.com/4f78a52690f570e29110cd4c1bed4892 for a full test report.

Hm, I have a node with some issues doing parallel building of tests. I'll push a proper test report as soon as a few other jobs finish.

**Comment by terjekv** [comment]
Test report by @terjekv
**SUCCESS**
Build succeeded for 0 out of 0 (1 easyconfigs in this PR)
ninhursaga.uio.no - Linux red hat enterprise linux 8.1, Intel(R) Xeon(R) Silver 4216 CPU @ 2.10GHz, Python 3.6.8
See https://gist.github.com/0d30e49b146a78049693caaf9f94d410 for a full test report.

**Comment by terjekv** [comment]
Test report by @terjekv
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
ninhursaga.uio.no - Linux red hat enterprise linux 8.1, Intel(R) Xeon(R) Silver 4216 CPU @ 2.10GHz, Python 3.6.8
See https://gist.github.com/bb620ebf2f0edea5b1a5aa17fc8587b2 for a full test report.

**Comment by verdurin** [comment]
Test report by @verdurin
**SUCCESS**
Build succeeded for 0 out of 0 (1 easyconfigs in this PR)
easybuild.novalocal - Linux centos linux 7.7.1908, Intel Xeon Processor (Skylake, IBRS), Python 2.7.5
See https://gist.github.com/9f3c97974e75fc555ee58d057624cb79 for a full test report.

**Comment by verdurin** [comment]
Test report by @verdurin
**FAILED**
Build succeeded for 0 out of 1 (1 easyconfigs in this PR)
easybuild.novalocal - Linux centos linux 7.7.1908, Intel Xeon Processor (Skylake, IBRS), Python 2.7.5
See https://gist.github.com/8acafe19b383776efe92517aeb6e174d for a full test report.

**Comment by terjekv** [comment]
> Test report by @verdurin
> **FAILED**
> Build succeeded for 0 out of 1 (1 easyconfigs in this PR)
> easybuild.novalocal - Linux centos linux 7.7.1908, Intel Xeon Processor (Skylake, IBRS), Python 2.7.5
> See https://gist.github.com/8acafe19b383776efe92517aeb6e174d for a full test report.

Missing readline.h? That's... Not good. I'll poke at it.

**Comment by terjekv** [comment]
@verdurin Could you test this again? I have added libreadline as a direct dependency to perl itself in an attempt to fix its cpath.

**Comment by verdurin** [comment]
Test report by @verdurin
**FAILED**
Build succeeded for 0 out of 1 (1 easyconfigs in this PR)
easybuild.novalocal - Linux centos linux 7.7.1908, Intel Xeon Processor (Skylake, IBRS), Python 2.7.5
See https://gist.github.com/bc91cc82308b2d2b031f7be4d89eade6 for a full test report.

**Comment by terjekv** [comment]
> Test report by @verdurin
> **FAILED**
> Build succeeded for 0 out of 1 (1 easyconfigs in this PR)
> easybuild.novalocal - Linux centos linux 7.7.1908, Intel Xeon Processor (Skylake, IBRS), Python 2.7.5
> See https://gist.github.com/bc91cc82308b2d2b031f7be4d89eade6 for a full test report.

```
**FAIL (unhandled exception: [Errno 2] No such file or directory)Traceback (most recent call last): File "/eb/maint/software/EasyBuild/4.1.1/lib/python2.7/site-packages/easybuild/main.py", line 113, in build_and_install_software (ec_res['success'], app_log, err) = build_and_install_one(ec, init_env) File "/eb/maint/software/EasyBuild/4.1.1/lib/python2.7/site-packages/easybuild/framework/easyblock.py", line 3105, in build_and_install_one result = app.run_all_steps(run_test_cases=run_test_cases) File "/eb/maint/software/EasyBuild/4.1.1/lib/python2.7/site-packages/easybuild/framework/easyblock.py", line 3013, in run_all_steps self.run_step(step_name, step_methods) File "/eb/maint/software/EasyBuild/4.1.1/lib/python2.7/site-packages/easybuild/framework/easyblock.py", line 2883, in run_step step_method(self)() File "/eb/maint/software/EasyBuild/4.1.1/lib/python2.7/site-packages/easybuild/easyblocks/generic/configuremake.py", line 318, in install_step (out, _) = run_cmd(cmd, log_all=True, simple=False) File "/eb/maint/software/EasyBuild/4.1.1/lib/python2.7/site-packages/easybuild/tools/run.py", line 88, in cache_aware_func res = func(cmd, *args, **kwargs) File "/eb/maint/software/EasyBuild/4.1.1/lib/python2.7/site-packages/easybuild/tools/run.py", line 145, in run_cmd cwd = os.getcwd() OSError: [Errno 2] No such file or directory ** Perl-5.30.0-GCCcore-8.3.0.eb
```

I literally have no idea.

**Comment by terjekv** [comment]
Test report by @terjekv
**SUCCESS**
Build succeeded for 0 out of 0 (1 easyconfigs in this PR)
ninhursaga.uio.no - Linux red hat enterprise linux 8.1, Intel(R) Xeon(R) Silver 4216 CPU @ 2.10GHz, Python 3.6.8
See https://gist.github.com/8abc08c25c708e6ab62fafd10b3cd52a for a full test report.

**Comment by terjekv** [comment]
Test report by @terjekv
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
ninhursaga.uio.no - Linux red hat enterprise linux 8.1, Intel(R) Xeon(R) Silver 4216 CPU @ 2.10GHz, Python 3.6.8
See https://gist.github.com/c7cebe231dcf0fb790d7903504b3c5f9 for a full test report.

**Comment by verdurin** [comment]
Test report by @verdurin
**SUCCESS**
Build succeeded for 0 out of 0 (1 easyconfigs in this PR)
generoso - Linux centos linux 7.6.1810, Intel(R) Xeon(R) CPU E5-2660 v4 @ 2.00GHz, Python 3.6.8
See https://gist.github.com/98e6c83bb2a85388b1c1a794d9ed1e6a for a full test report.

**Comment by terjekv** [comment]
> Test report by @verdurin
> **SUCCESS**
> Build succeeded for 0 out of 0 (1 easyconfigs in this PR)
> generoso - Linux centos linux 7.6.1810, Intel(R) Xeon(R) CPU E5-2660 v4 @ 2.00GHz, Python 3.6.8
> See https://gist.github.com/98e6c83bb2a85388b1c1a794d9ed1e6a for a full test report.

A missing --force?

**Comment by verdurin** [comment]
Test report by @verdurin
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
generoso - Linux centos linux 7.6.1810, Intel(R) Xeon(R) CPU E5-2660 v4 @ 2.00GHz, Python 3.6.8
See https://gist.github.com/a38617ad163a34a60cd66f4d69af5bc6 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**FAILED**
Build succeeded for 0 out of 1 (1 easyconfigs in this PR)
node3101.skitty.os - Linux centos linux 7.7.1908, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz, Python 3.6.8
See https://gist.github.com/86df417a65f36b22e2ec162018fe721e for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
node2548.golett.os - Linux centos linux 7.7.1908, Intel(R) Xeon(R) CPU E5-2680 v3 @ 2.50GHz, Python 2.7.5
See https://gist.github.com/b9789d7415d6117def420bc282c245ee for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
node3101.skitty.os - Linux centos linux 7.7.1908, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz, Python 3.6.8
See https://gist.github.com/c2241f4085a8f274270c8c69a958c9bb for a full test report.

**Comment by boegel** [comment]
Going in, thanks @terjekv!

**Pull request merged**
