### PR TITLE
{devel,lib,tools}[GCCcore/8.3.0] davix v0.7.5, LibUUID v1.0.3, gSOAP v2.8.100

### PR DESCRIPTION
**Pull request by smoors**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by smoors** [comment]
Test report by @smoors
**SUCCESS**
Build succeeded for 3 out of 3 (3 easyconfigs in this PR)
node301.hydra.os - Linux centos linux 7.7.1908, Intel(R) Xeon(R) Gold 6148 CPU @ 2.40GHz, Python 2.7.5
See https://gist.github.com/78e5361d79305a817dd4e3af8342aa2d for a full test report.

**Comment by lexming** [comment]
Test report by @lexming
**FAILED**
Build succeeded for 2 out of 3 (3 easyconfigs in this PR)
node376.hydra.os - Linux centos linux 7.7.1908, Intel(R) Xeon(R) Gold 6148 CPU @ 2.40GHz, Python 2.7.5
See https://gist.github.com/0e82fecdaa6e6a3bcafd0c5d28184500 for a full test report.

**Comment by smoors** [comment]
> The download URLs for LibUUID do not work any more and it seems that the SourceForge project is quite dead. I think that the best solution is to stop adding easyconfigs for LibUUID and use `libuuid` from `util-linux` which is actively maintained.
> The easyconfigs of `util-linux` already provide `libuuid`, so it is just a matter of changing the dependency of this easyconfig.

The download still works for me but it's indeed better to just use util-linux.

**Comment by smoors** [comment]
Test report by @smoors
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in this PR)
node377.hydra.os - Linux centos linux 7.7.1908, Intel(R) Xeon(R) Gold 6148 CPU @ 2.40GHz, Python 2.7.5
See https://gist.github.com/1bd0c2f644fd286cd6b05e782b21b190 for a full test report.

**Comment by lexming** [comment]
Test report by @lexming
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in this PR)
node376.hydra.os - Linux centos linux 7.7.1908, Intel(R) Xeon(R) Gold 6148 CPU @ 2.40GHz, Python 2.7.5
See https://gist.github.com/a32202b637cb39d04cf5e6ab94416a9b for a full test report.

**Comment by lexming** [comment]
Going in, thanks @smoors !

**Pull request merged**
