### PR TITLE
{bio,lib}[GCC/8.2.0-2.31.1] CNT-ILP v20171031, LEMON v1.3.1

### PR DESCRIPTION
**Pull request by smoors**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by smoors** [comment]
Test report by @smoors
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in this PR)
node319.hydra.os - Linux centos linux 7.6.1810, Intel(R) Xeon(R) Gold 6148 CPU @ 2.40GHz, Python 2.7.5
See https://gist.github.com/c5299f6710c2cc9d7ee3427a4215208c for a full test report.

**Comment by verdurin** [comment]
Test report by @verdurin
**FAILED**
Build succeeded for 1 out of 3 (2 easyconfigs in this PR)
easybuild.novalocal - Linux centos linux 7.7.1908, Intel Xeon Processor (Skylake, IBRS), Python 2.7.5
See https://gist.github.com/1aa87f5ccbea31210e7d3179da1b3548 for a full test report.

**Comment by smoors** [comment]
@verdurin can you manually download the sources for the CPLEX dependency and try again?

**Comment by akesandgren** [comment]
Test report by @akesandgren
**FAILED**
Build succeeded for 1 out of 3 (2 easyconfigs in this PR)
b-an03.hpc2n.umu.se - Linux ubuntu 16.04, Intel(R) Xeon(R) CPU E5-2690 v4 @ 2.60GHz, Python 2.7.12
See https://gist.github.com/cb0585062aa7ce980f29e705eb41f7a3 for a full test report.

**Comment by akesandgren** [comment]
@smoors which version of CPLEX should be downloaded? The academic initiative one or the commumnity edition?

**Comment by smoors** [comment]
@akesandgren I used the academic initiative version (you need to jump through a lot of hoops to get it).
not sure if the community version works or not.

**Comment by migueldiascosta** [comment]
Going in, thanks @smoors!

**Pull request merged**
