### PR TITLE
{lib}[GCCcore/12.2.0,foss/2022b] PyTorch-Lightning v2.1.2, deepdiff v6.7.1, tensorboardX v2.6.2.2, ...

### PR DESCRIPTION
**Pull request by boegel**
(created using `eb --new-pr`)
requires:
* #19510
* #19512

### CODE REVIEW

**Comment by boegel** [comment]
@boegelbot please test @ generoso

**Comment by boegel** [comment]
Test report by @boegel
**FAILED**
Build succeeded for 3 out of 5 (4 easyconfigs in total)
node3123.skitty.os - Linux RHEL 8.8, x86_64, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz (skylake_avx512), Python 3.6.8
See https://gist.github.com/boegel/17255e202ad95d1a2c9a5a58b01227a7 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 4 out of 4 (4 easyconfigs in total)
node3123.skitty.os - Linux RHEL 8.8, x86_64, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz (skylake_avx512), Python 3.6.8
See https://gist.github.com/boegel/0e37d03520a5530429be097268d0ef4d for a full test report.

**Comment by akesandgren** [comment]
@boegel version conflicts, please resolv

**Comment by boegel** [comment]
@akesandgren fixed in e89d81e27f

**Comment by akesandgren** [comment]
@boegelbot Please test @ generoso

**Review by akesandgren — APPROVED** [review]
LGTM

**Comment by akesandgren** [comment]
Going in, thanks @boegel!

**Pull request merged**
