### PR TITLE
{numlib}[intel/2020b] PETSc v3.14.4 w/ Python 3.8.6

### PR DESCRIPTION
**Pull request by SimonPinches**
(created using `eb --new-pr`)

### CODE REVIEW

**Review by Micket — CHANGES_REQUESTED** [review]
You forgot to add MUMPS and SuiteSparse

**Comment by SimonPinches** [comment]
Missing dependencies now added.

**Comment by SimonPinches** [comment]
@Micket Is anything else needed on this PR?

**Review by Micket — APPROVED** [review]
lgtm

**Comment by Micket** [comment]
@boegelbot please test @ generoso

**Comment by Micket** [comment]
Test report by @Micket
**SUCCESS**
Build succeeded for 6 out of 6 (4 easyconfigs in total)
alvis-c1 - Linux centos linux 7.9.2009, x86_64, Intel Xeon Processor (Skylake), Python 3.6.8
See https://gist.github.com/fd5d3d16f4f264e35ba608c678406fa3 for a full test report.

**Comment by Micket** [comment]
Going in, thanks @SimonPinches!

**Pull request merged**
