### PR TITLE
{toolchain} foss/2020b

### PR DESCRIPTION
**Pull request by boegel**
(created using `eb --new-pr`)

Still WIP because:

* maybe we should use OpenBLAS 0.3.12 rather than a patched OpenBLAS 0.3.11?
* ~~ScaLAPACK 2.1.0 doesn't compile with GCC 10.2~~
  * fixed upstream in https://github.com/Reference-ScaLAPACK/scalapack/pull/26, but this relies on building ScaLAPACK with CMake, which we're not doing currently...

requires:

* [x] updated ScaLAPACK easyblock ~~https://github.com/easybuilders/easybuild-easyblocks/pull/2205~~

### CODE REVIEW

**Comment by zao** [comment]
Test report by @zao
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
freja - Linux Ubuntu 20.04, x86_64, Intel(R) Core(TM) i7-8700K CPU @ 3.70GHz (skylake), Python 3.8.5
See https://gist.github.com/0a1e59fadba7ce3b03e82b4679f91f5a for a full test report.

**Comment by bartoldeman** [comment]
Test report by @bartoldeman
**FAILED**
Build succeeded for 0 out of 1 (1 easyconfigs in this PR)
build-node.computecanada.ca - Linux centos linux 7.8.2003, x86_64, Intel Xeon Processor (Skylake, IBRS), Python 3.7.7
See https://gist.github.com/cbc75a5143babbb14cf7a93f2cd60672 for a full test report.

**Comment by branfosj** [comment]
Test report by @branfosj
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
bear-pg0306u19a.bear.cluster - Linux RHEL 8.2, POWER, 8335-GTX (power9le), Python 3.6.8
See https://gist.github.com/f2a7d5aafe02a785b09215796e73f5f5 for a full test report.

**Comment by branfosj** [comment]
Test report by @branfosj
**FAILED**
Build succeeded for 0 out of 1 (1 easyconfigs in total)
bear-pg0211u03a.bear.cluster - Linux centos linux 7.8.2003, x86_64, Intel(R) Xeon(R) Gold 6248 CPU @ 2.50GHz (cascadelake), Python 3.6.8
See https://gist.github.com/3330cb6c8edba715604e49f8b2300f40 for a full test report.

**Comment by boegel** [comment]
@boegelbot please test @ generoso
EB_ARGS="--include-easyblocks-from-pr 2205"

**Comment by boegel** [comment]
Test report by @boegel
Using easyblocks from https://github.com/easybuilders/easybuild-easyblocks/pull/2205
**SUCCESS**
Build succeeded for 6 out of 6 (6 easyconfigs in total)
node3408.kirlia.os - Linux centos linux 7.8.2003, x86_64, Intel(R) Xeon(R) Gold 6240 CPU @ 2.60GHz (cascadelake), Python 2.7.5
See https://gist.github.com/0be2d3306f7784edc220aba20083e9fa for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
Using easyblocks from https://github.com/easybuilders/easybuild-easyblocks/pull/2205
**SUCCESS**
Build succeeded for 6 out of 6 (6 easyconfigs in total)
node2427.golett.os - Linux centos linux 7.8.2003, x86_64, Intel(R) Xeon(R) CPU E5-2680 v3 @ 2.50GHz (haswell), Python 2.7.5
See https://gist.github.com/8d9d5a2805481bd765d78c601b6a8529 for a full test report.

**Comment by zao** [comment]
Test report by @zao
Using easyblocks from https://github.com/easybuilders/easybuild-easyblocks/pull/2205
**SUCCESS**
Build succeeded for 6 out of 6 (6 easyconfigs in total)
freja - Linux Ubuntu 20.04, x86_64, Intel(R) Core(TM) i7-8700K CPU @ 3.70GHz (skylake), Python 3.8.5
See https://gist.github.com/12dd7c982ec5e3dc487cd3f62ef1a98e for a full test report.

**Comment by verdurin** [comment]
Test report by @verdurin
**SUCCESS**
Build succeeded for 27 out of 27 (6 easyconfigs in this PR)
nuc.lan - Linux Fedora 32, x86_64, Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz, Python 3.8.6
See https://gist.github.com/dadb1eaab13f1ac62badb0fc168ee0a2 for a full test report.

**Comment by zao** [comment]
Test report by @zao
**FAILED**
Build succeeded for 29 out of 32 (6 easyconfigs in this PR)
b-cn1203.hpc2n.umu.se - Linux ubuntu 16.04, x86_64, Intel(R) Xeon Phi(TM) CPU 7250 @ 1.40GHz, Python 2.7.12
See https://gist.github.com/9143cfcd091f8a341f652a8c160b3ba2 for a full test report.

**Comment by zao** [comment]
Test report by @zao
**SUCCESS**
Build succeeded for 3 out of 3 (6 easyconfigs in this PR)
b-cn1203.hpc2n.umu.se - Linux ubuntu 16.04, x86_64, Intel(R) Xeon Phi(TM) CPU 7250 @ 1.40GHz, Python 2.7.12
See https://gist.github.com/c87765f7b28154e510b92bf0329865b8 for a full test report.

**Comment by zao** [comment]
KNL test report made in two parts due to https://github.com/easybuilders/easybuild-framework/issues/3476, please consider my two test reports as a cumulative success.

**Comment by bartoldeman** [comment]
Test report by @bartoldeman
**FAILED**
Build succeeded for 4 out of 11 (6 easyconfigs in this PR)
build-node.computecanada.ca - Linux centos linux 7.8.2003, x86_64, Intel Xeon Processor (Skylake, IBRS), Python 3.7.7
See https://gist.github.com/cbec9bab1f3a66494d67dc418b6cc236 for a full test report.

**Comment by bartoldeman** [comment]
Test report by @bartoldeman
**SUCCESS**
Build succeeded for 11 out of 11 (6 easyconfigs in this PR)
build-node.computecanada.ca - Linux centos linux 7.8.2003, x86_64, Intel Xeon Processor (Skylake, IBRS), Python 3.7.7
See https://gist.github.com/baea9a90ca04cf97b6296e817fb35d65 for a full test report.

**Comment by branfosj** [comment]
Test report by @branfosj
**FAILED**
Build succeeded for 0 out of 1 (1 easyconfigs in total)
bear-pg0206u16a.bear.cluster - Linux centos linux 8.2.2004, x86_64, Intel(R) Xeon(R) Gold 6248 CPU @ 2.50GHz (cascadelake), Python 3.6.8
See https://gist.github.com/0b61d22791f7b81dba570cdee7009936 for a full test report.

**Comment by branfosj** [comment]
Test report by @branfosj
**SUCCESS**
Build succeeded for 6 out of 6 (6 easyconfigs in total)
bear-pg0306u19a.bear.cluster - Linux RHEL 8.2, POWER, 8335-GTX (power9le), Python 3.6.8
See https://gist.github.com/21c13f827a274d8cdba194231ec98ede for a full test report.

**Comment by branfosj** [comment]
Test report by @branfosj
**SUCCESS**
Build succeeded for 6 out of 6 (6 easyconfigs in total)
bear-pg0206u16a.bear.cluster - Linux centos linux 8.2.2004, x86_64, Intel(R) Xeon(R) Gold 6248 CPU @ 2.50GHz (cascadelake), Python 3.6.8
See https://gist.github.com/fc5a15837feef5b1289c3fa2dfdf731d for a full test report.

**Comment by bartoldeman** [comment]
Test report by @bartoldeman
**FAILED**
Build succeeded for 0 out of 15 (6 easyconfigs in this PR)
build-node.computecanada.ca - Linux centos linux 7.8.2003, x86_64, Intel Xeon Processor (Skylake, IBRS), Python 3.7.7
See https://gist.github.com/e070f1ee7cfcfc9da971948f1a1fa33c for a full test report.

**Comment by migueldiascosta** [comment]
Test report by @migueldiascosta
Using easyblocks from PR(s) https://github.com/easybuilders/easybuild-easyblocks/pull/2191, https://github.com/easybuilders/easybuild-easyblocks/pull/2205
**SUCCESS**
Build succeeded for 6 out of 6 (6 easyconfigs in total)
sms - Linux centos linux 7.6.1810, x86_64, AMD EPYC 7601 32-Core Processor (zen), Python 2.7.5
See https://gist.github.com/4ea1c3e307c8d8abda9f990d939f2bd5 for a full test report.

**Comment by bartoldeman** [comment]
Test report by @bartoldeman
**SUCCESS**
Build succeeded for 6 out of 6 (6 easyconfigs in this PR)
build-node.computecanada.ca - Linux centos linux 7.8.2003, x86_64, Intel Xeon Processor (Skylake, IBRS), Python 3.7.7
See https://gist.github.com/56b9efa0e5967c7468ab06a59d6266f5 for a full test report.

**Comment by verdurin** [comment]
@boegel what are we waiting for on this one?

**Comment by Micket** [comment]
Test report by @Micket
**SUCCESS**
Build succeeded for 10 out of 10 (6 easyconfigs in total)
vera-c1 - Linux centos linux 7.8.2003, x86_64, Intel Xeon Processor (Skylake), Python 2.7.5
See https://gist.github.com/cfecf95db4e7efe5ab99b594761d0caf for a full test report.

**Comment by boegel** [comment]
> @boegel what are we waiting for on this one?

Testing stuff on top. I was doing that with OpenFOAM 8 today, works fine.

Also tried CP2K 7.1, ran into problems with Libint:

```
python c_to_f.py ../include/libint2.h.i libint2_types_f.h Libint_t
grep '^#' ../include/libint2_types.h | grep -v '#include' > fortran_incldefs.h
FC libint_f.o
../include/libint2/util/generated/libint2_params.h:29:0:
   29 | #    if __has_include(<libint2_params.h>)
      |                                                                                                                                                                                                     Error: missing '(' before "__has_include" operand                                                                                                                                                           ../include/libint2/util/generated/libint2_params.h:29:0: Error: operator "__has_include" requires a header-name
make[1]: *** [../MakeSuffixRules:12: libint_f.o] Error 1
```

That doesn't need to be a blocker though, but it would be nice to have some confirmation about the Fortran aspect of `foss/2020b` too, so maybe via WRF?

**Comment by boegel** [comment]
Libint issue is fixed with patch for GCC 10.2, see #11627

CP2K 7.1 with `foss/2020b` requires using `-fallow-argument-mismatch`, see fix in CP2K easyblock @ https://github.com/easybuilders/easybuild-easyblocks/pull/2223

Similarly building WRF 3.9.1.1 requires both `-fallow-argument-mismatch` and `-fallow-invalid-boz`, see https://github.com/wrf-model/WRF/issues/1250, which is easy to fix with a patch.

**Comment by verdurin** [comment]
Test report by @verdurin
**SUCCESS**
Build succeeded for 1 out of 1 (6 easyconfigs in total)
nuc.lan - Linux Fedora 32, x86_64, Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz, Python 3.8.6
See https://gist.github.com/cc7bacd81289b781449e01160131cbb4 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 6 out of 6 (6 easyconfigs in total)
node3108.skitty.os - Linux centos linux 7.8.2003, x86_64, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz, Python 3.6.8
See https://gist.github.com/876ebf76c9c69039c64ce042fceffec0 for a full test report.

**Comment by Micket** [comment]
Test report by @Micket
**SUCCESS**
Build succeeded for 6 out of 6 (6 easyconfigs in total)
vera-c1 - Linux centos linux 7.8.2003, x86_64, Intel Xeon Processor (Skylake), Python 2.7.5
See https://gist.github.com/61aac51f05062cae63521389a0ecc34d for a full test report.

**Review by Micket — APPROVED** [review]
lgtm

**Comment by Micket** [comment]
Going in, thanks @boegel!

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 6 out of 6 (6 easyconfigs in total)
easybuild1.novalocal - Linux centos linux 8.2.2004, POWER, IBM pSeries (emulated by qemu) (power8le), Python 3.6.8
See https://gist.github.com/c61f1c99b83a04b7c207ac90820eb223 for a full test report.

**Pull request merged**
