### PR TITLE
makeinfo requires Perl as a dependency

### PR DESCRIPTION
**Pull request by akesandgren**
(created using `eb --new-pr`)

Depends on ~#13163, #13164, #13165~ and a rebuild of normal Perl.

### CODE REVIEW

**Comment by SebastianAchilles** [comment]
@boegelbot please test @ generoso
EB_ARGS="makeinfo-6.7-GCCcore-9.3.0.eb makeinfo-6.7-GCCcore-10.2.0.eb makeinfo-6.7-GCCcore-10.3.0.eb Perl-5.30.2-GCCcore-9.3.0.eb Perl-5.32.0-GCCcore-10.2.0.eb Perl-5.32.1-GCCcore-10.3.0.eb"

**Comment by SebastianAchilles** [comment]
Test report by @sebastianachilles
**SUCCESS**
Build succeeded for 6 out of 6 (6 easyconfigs in total)
centos8-eb - Linux centos linux 8.3.2011, x86_64, Intel(R) Core(TM) i7-8700 CPU @ 3.20GHz (skylake), Python 3.6.8
See https://gist.github.com/c5af1e2898597d3d0dcf8fc2def26e0b for a full test report.

**Comment by SebastianAchilles** [comment]
Test report by @sebastianachilles
**SUCCESS**
Build succeeded for 6 out of 6 (6 easyconfigs in total)
rocky8-eb - Linux rocky linux 8.4, x86_64, Intel(R) Core(TM) i7-6900K CPU @ 3.20GHz (broadwell), Python 3.6.8
See https://gist.github.com/8557ac2a433f16c357f2bd0450794a71 for a full test report.

**Review by SebastianAchilles — APPROVED** [review]
lgtm

**Comment by boegel** [comment]
Going in, thanks @akesandgren!

**Pull request merged**
