### PR TITLE
{bio}[foss/2019a] R-bundle-Bioconductor v3.9: Add pRoloc

### PR DESCRIPTION
**Pull request by lexming**
(created using `eb --new-pr`)
Depends on PR #8881

### CODE REVIEW

**Comment by lexming** [comment]
`MSnbase` is not being removed by this PR, it is just a duplicate entry in the extension list.

**Comment by lexming** [comment]
Test report by @lexming
**FAILED**
Build succeeded for 0 out of 1 (1 easyconfigs in this PR)
login2.cerberus.os - Linux centos linux 7.6.1810, Intel(R) Xeon(R) Gold 6126 CPU @ 2.60GHz, Python 2.7.5
See https://gist.github.com/0320960cf35a416b2d12d32efd43b806 for a full test report.

**Comment by lexming** [comment]
Test report by @lexming
**FAILED**
Build succeeded for 0 out of 1 (1 easyconfigs in this PR)
login2.cerberus.os - Linux centos linux 7.6.1810, Intel(R) Xeon(R) Gold 6126 CPU @ 2.60GHz, Python 2.7.5
See https://gist.github.com/d6fb23d35c8a684bfeb90594ac977588 for a full test report.

**Comment by lexming** [comment]
Test report by @lexming
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
login2.cerberus.os - Linux centos linux 7.6.1810, Intel(R) Xeon(R) Gold 6126 CPU @ 2.60GHz, Python 2.7.5
See https://gist.github.com/3d762bddbed350144cc0e351fb69b67a for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
node2628.swalot.os - Linux centos linux 7.6.1810, Intel(R) Xeon(R) CPU E5-2660 v3 @ 2.60GHz, Python 2.7.5
See https://gist.github.com/ed996976115cbd3d67e6f8b8c945cdbd for a full test report.

**Comment by boegel** [comment]
Going in, thanks @lexming!

**Pull request merged**
