### PR TITLE
{geo}[foss/2022a] SciTools-Iris v3.2.1 w/ Python 3.10.4

### PR DESCRIPTION
**Pull request by lexming**
(created using `eb --new-pr`)

Depends on:
* [x] https://github.com/easybuilders/easybuild-easyconfigs/pull/19258

### CODE REVIEW

**Comment by lexming** [comment]
@boegelbot: please test @ generoso

**Comment by lexming** [comment]
@boegelbot please test @ jsc-zen3

**Review by Micket — APPROVED** [review]
lgtm

**Comment by Micket** [comment]
@boegelbot: please test @ jsc-zen3

**Comment by Micket** [comment]
Test report by @Micket
**SUCCESS**
Build succeeded for 18 out of 18 (1 easyconfigs in total)
alvis-skylake-build - Linux Rocky Linux 8.9, x86_64, Intel Xeon Processor (Skylake, IBRS, no TSX), Python 3.6.8
See https://gist.github.com/Micket/4146ffdd0560f1f41c72bf38fc82eb92 for a full test report.

**Comment by verdurin** [comment]
Test report by @verdurin
**SUCCESS**
Build succeeded for 7 out of 7 (1 easyconfigs in total)
easybuild-c7.novalocal - Linux CentOS Linux 7.9.2009, x86_64, Intel Xeon Processor (Skylake, IBRS), Python 3.6.8
See https://gist.github.com/verdurin/47467f0ffdb596332c63ccb143d9a67c for a full test report.

**Comment by verdurin** [comment]
Going in, thanks @lexming!

**Pull request merged**
