### PR TITLE
{bio}[foss/2018b] Trim_Galore v0.6.1 w/ Python 2.7.15 + 3.6.6

### PR DESCRIPTION
**Pull request by sassy-crick**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by boegel** [comment]
@sassy-crick Does it make sense to have both this and the more recent 0.6.2 via #8280?

**Comment by sassy-crick** [comment]
@boegel Some users started off with one version and don't want to jump versions. Also, for completion I thought I might as well upload this one too. Up to you. Thanks.

**Comment by boegel** [comment]
@sassy-crick Yeah, users like to be able to reproduce the buggy results they got with broken old versions of the software... ;)

Doesn't hurt to also get this merged I guess.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in this PR)
node2402.golett.os - Linux centos linux 7.6.1810, Intel(R) Xeon(R) CPU E5-2680 v3 @ 2.50GHz, Python 2.7.5
See https://gist.github.com/b4c7bfcc3881df6bffb22fcc3e74aa28 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in this PR)
node2010.delcatty.os - Linux centos linux 7.6.1810, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.7.5
See https://gist.github.com/ae5c0b16dd41db56ab24b1ae243e9d36 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in this PR)
node3112.skitty.os - Linux centos linux 7.6.1810, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz, Python 2.7.5
See https://gist.github.com/b9ad96ebf0386ce0a4d027f5937e2109 for a full test report.

**Comment by boegel** [comment]
Going in, thanks @sassy-crick!

**Pull request merged**
