### PR TITLE
in-place update to magma 2.5.4 for PyTorch easyconfigs using fosscuda/2019b toolchain

### PR DESCRIPTION
**Pull request by Flamefire**
(created using `eb --new-pr`)

Fixes a known Bug, see https://github.com/easybuilders/easybuild-easyconfigs/pull/11656

### CODE REVIEW

**Comment by boegel** [comment]
The failing tests that complain about introducing two `magma` versions in the `2019b` generation are going to make this difficult to merge, so please merge this PR with #11725 and #11724 . It'll be a bit painful to submit test reports for, but so be it...

Also, please motivate this change, since we usually don't do in-place updates of dependencies, unless there's a very good reason for it.

**Review by boegel — DISMISSED** [review]
lgtm, test report coming up...

**Comment by Flamefire** [comment]
Test report by @Flamefire
**FAILED**
Build succeeded for 2 out of 3 (3 easyconfigs in total)
taurusa6 - Linux centos linux 7.7.1908, x86_64, Intel(R) Xeon(R) CPU E5-2603 v4 @ 1.70GHz, Python 2.7.5
See https://gist.github.com/e12b0ec1d17198e0eb6b476c13c9d915 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**FAILED**
Build succeeded for 2 out of 3 (3 easyconfigs in total)
node3308.joltik.os - Linux centos linux 7.8.2003, x86_64, Intel(R) Xeon(R) Gold 6242 CPU @ 2.80GHz (cascadelake), Python 3.6.8
See https://gist.github.com/5497c880ffe8a38d2643ac953cd537c3 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 3 out of 3 (3 easyconfigs in total)
node3307.joltik.os - Linux centos linux 7.8.2003, x86_64, Intel(R) Xeon(R) Gold 6242 CPU @ 2.80GHz (cascadelake), Python 3.6.8
See https://gist.github.com/c46303adcf2e069750f1c90f41b9ab3d for a full test report.

**Comment by boegel** [comment]
@Flamefire Any idea what went wrong with your test report?

**Comment by Flamefire** [comment]
Yes: I started it before the CUDA 11 patch was added. The failure will be fixed by the patch as shown by the other tests. Shall I rerun the tests?

**Comment by boegel** [comment]
> Yes: I started it before the CUDA 11 patch was added. The failure will be fixed by the patch as shown by the other tests. Shall I rerun the tests?

If it's no too much trouble, yes please.

**Comment by Flamefire** [comment]
Test report by @Flamefire
**SUCCESS**
Build succeeded for 3 out of 3 (3 easyconfigs in total)
taurusa5 - Linux centos linux 7.7.1908, x86_64, Intel(R) Xeon(R) CPU E5-2603 v4 @ 1.70GHz, Python 2.7.5
See https://gist.github.com/fdafa1afad6f548d82b4207549a2844a for a full test report.

**Review by boegel — APPROVED** [review]

**Comment by boegel** [comment]
Going in, thanks @Flamefire!

**Pull request merged**
