### PR TITLE
add VMD 1.9.2 easyconfig with patches

### PR DESCRIPTION
**Pull request by thiell**
- works with EB_VMD https://github.com/hpcugent/easybuild-easyblocks/pull/879
- this easyconfig requires Nvidia OptiX but could work without (#2795)
- originally built successfully with EasyBuild 2.3

### CODE REVIEW

**Comment by verdurin** [comment]
We've had a request for this, but we don't have 'OptiX'.

**Comment by verdurin** [comment]
We would want it for `2016b`.

**Comment by verdurin** [comment]
Actually, our local request is for `1.9.1`, because of specific bugs he wants to avoid in `1.9.2`.
Happy to contribute to this one too, though.

**Comment by boegel** [comment]
@verdurin remarks in easyblock PR (https://github.com/hpcugent/easybuild-easyblocks/pull/879) should be tackled, and this PR should be reviewed & updated too

Making these PRs ready to go could be done via wrapper PRs if @thiell doesn't have time to follow up.

**Comment by boegel** [comment]
@verdurin Easyconfig for VMD 1.9.3 available in #4391, requires #4386 and enhanced VMD easyblock from https://github.com/hpcugent/easybuild-easyblocks/pull/1148

**Comment by boegel** [comment]
@thiell A cleaned up/updated version of this just got merged in #4391, albeit without CUDA/OptiX as dependencies.

Are you up for cleaning this up accordingly?

**Comment by migueldiascosta** [comment]
@thiell, this PR is being closed for the following reason(s): no activity for > 1 year.
Please don't hesitate to reopen this PR or add a comment if you feel this contribution is still relevant.
For more information on our policy w.r.t. closing PRs, see https://easybuild.readthedocs.io/en/latest/Contributing.html#why-a-pull-request-may-be-closed-by-a-maintainer

**Pull request closed without merging**
