### PR TITLE
include tqdm as extension in the idemux bundle to avoid multivariant deps on GCCcore-10.2.0

### PR DESCRIPTION
**Pull request by arielzn**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by arielzn** [comment]
to avoid the issue mentioned on https://github.com/easybuilders/easybuild-easyconfigs/pull/16568#issuecomment-1306087878

**Comment by smoors** [comment]
@boegelbot: please test @ generoso

**Review by smoors — APPROVED** [review]
lgtm

**Comment by smoors** [comment]
Going in, thanks @arielzn!

**Pull request merged**
