### PR TITLE
{tools}[GCCcore/12.2.0] Vim v9.0.1434 w/ Python 3.10.8

### PR DESCRIPTION
**Pull request by anselmicz**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by anselmicz** [comment]
Test report by @anselmicz
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
torrent - Linux Debian GNU/Linux 12, x86_64, AMD Ryzen 5 3600 6-Core Processor (zen2), 1 x NVIDIA NVIDIA GeForce RTX 3070, 525.89.02, Python 3.11.2
See https://gist.github.com/anselmicz/4bf6fc03e939704ce30525e5ea33119c for a full test report.

**Comment by branfosj** [comment]
@boegelbot please test @ generoso

**Comment by branfosj** [comment]
Test report by @branfosj
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
bear-pg0105u03a.bear.cluster - Linux RHEL 8.6, x86_64, Intel(R) Xeon(R) Platinum 8360Y CPU @ 2.40GHz (icelake), Python 3.6.8
See https://gist.github.com/branfosj/0959dd5701c561a36306c70b422e3ee3 for a full test report.

**Comment by branfosj** [comment]
@boegelbot please test @ jsc-zen2

**Review by branfosj — APPROVED** [review]

**Comment by branfosj** [comment]
Going in, thanks @anselmicz!

**Pull request merged**
