### PR TITLE
PMIx 4.1.2: remove unused libfabric dep

### PR DESCRIPTION
**Pull request by bartoldeman**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by bartoldeman** [comment]
Support for `--with-ofi` (which didn't do anything anyway) was removed in https://github.com/openpmix/openpmix/commit/6ddc3a455358630aa76a5ce6376b11c37a0b5451

**Comment by bartoldeman** [comment]
Test report by @bartoldeman
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
build-node.computecanada.ca - Linux CentOS Linux 7.9.2009, x86_64, Intel Xeon Processor (Skylake, IBRS), Python 3.7.7
See https://gist.github.com/387916154843a68f1e26ea5b7ed46e5a for a full test report.

**Comment by jfgrimm** [comment]
Test report by @jfgrimm
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
node066.pri.viking.alces.network - Linux CentOS Linux 7.9.2009, x86_64, Intel(R) Xeon(R) Gold 6138 CPU @ 2.00GHz (skylake_avx512), Python 3.6.8
See https://gist.github.com/8b13c4814a25468392c6092325f074bf for a full test report.

**Comment by jfgrimm** [comment]
@bartoldeman I'm also seeing: `WARNING: unrecognized options: --disable-man-pages ` in the configure log

**Comment by bartoldeman** [comment]
> @bartoldeman I'm also seeing: `WARNING: unrecognized options: --disable-man-pages` in the configure log as well

yes, indeed, removed in https://github.com/openpmix/openpmix/commit/9ac34c26e4578c178465182726e6a1cd56774b74
I'll remove that from the easyconfig as well then.

**Comment by jfgrimm** [comment]
Going in, thanks @bartoldeman!

**Pull request merged**
