### PR TITLE
{math}[foss/2023a] rustworkx v0.12.1

### PR DESCRIPTION
**Pull request by lcniel**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by lcniel** [comment]
Test report by @lcniel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
alvis4-28 - Linux Rocky Linux 8.9, x86_64, Intel(R) Xeon(R) Gold 6338 CPU @ 2.00GHz, 1 x NVIDIA NVIDIA A100-SXM4-40GB, 545.23.08, Python 3.6.8
See https://gist.github.com/lcniel/73808b4bb4919a8faae6fafa73148710 for a full test report.

**Comment by lcniel** [comment]
Not sure what's going on with the checksum issue, it seems like things are being double-counted between crates and sources? Is the easyblock here obsolete?

**Comment by boegel** [comment]
Or it's because of the changes in https://github.com/easybuilders/easybuild-easyconfigs/pull/21143, that's perhaps more likely

**Comment by boegel** [comment]
@boegelbot please test @ generoso

**Comment by boegel** [comment]
Actually, the changes in #21143 probably *fix* the problem in the tests here (that PR was merged after this one was opened), so I think all this needs is a sync with current `develop`... Did just that, let's see if CI agrees

**Comment by boegel** [comment]
@boegelbot please test @ jsc-zen3

**Comment by boegel** [comment]
> Actually, the changes in #21143 probably _fix_ the problem in the tests here (that PR was merged after this one was opened), so I think all this needs is a sync with current `develop`... Did just that, let's see if CI agrees

Still seeing this, so nope:
```
Checksums missing for one or more sources/patches in rustworkx-0.12.1-foss-2023a.eb: found 137 sources + 0 patches vs 69 checksums
```

@Flamefire can maybe shed some light on this...

**Comment by boegel** [comment]
Same problem in:
* #21392

**Comment by lcniel** [comment]
> > Actually, the changes in #21143 probably _fix_ the problem in the tests here (that PR was merged after this one was opened), so I think all this needs is a sync with current `develop`... Did just that, let's see if CI agrees
> 
> Still seeing this, so nope:
> 
> ```
> Checksums missing for one or more sources/patches in rustworkx-0.12.1-foss-2023a.eb: found 137 sources + 0 patches vs 69 checksums
> ```
> 
> @Flamefire can maybe shed some light on this...

I discussed this with @Micket earlier this week, he came to some similar solution and would look into it.

**Comment by Flamefire** [comment]
This shouldn't happen. E.g. I added a copy operation in the checksum step to avoid it modifying the original EC instances. So it seems some other test is also modifying it and needs similar logic. I'm working on it.

**Comment by boegel** [comment]
Problem with incorrect counting of checksums vs sources + patches is fixed in https://github.com/easybuilders/easybuild-easyblocks/pull/3448

That creates another problem with verifying the checksums for patch files which makes the CI fail for `DeltaLake-0.15.1-gfbf-2023a.eb`, which should be fixed with #21416

**Comment by boegel** [comment]
@boegelbot please test @ jsc-zen3

**Review by boegel — APPROVED** [review]
lgtm

**Comment by boegel** [comment]
Going in, thanks @lcniel!

**Pull request merged**
