### PR TITLE
{bio}[GCCcore/12.3.0,gompi/2023a] IQ-TREE v2.2.2.7, LSD2 v2.4.1

### PR DESCRIPTION
**Pull request by smoors**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by smoors** [comment]
@boegelbot please test @ jsc-zen3

**Comment by smoors** [comment]
@boegelbot: please test @ generoso

**Review by bedroge — APPROVED** [review]
Lgtm

**Comment by bedroge** [comment]
Test report by @bedroge
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in total)
bob-Latitude-5300 - Linux Ubuntu 22.04, x86_64, Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz, Python 3.10.12
See https://gist.github.com/bedroge/18e2637e9ba9996ac421745d28913bf4 for a full test report.

**Comment by bedroge** [comment]
Going in, thanks @smoors!

**Pull request merged**
