### PR TITLE
{lib}[foss/2018a] libepoxy v1.5.2

### PR DESCRIPTION
**Pull request by lexming**
Wrapper PR for https://github.com/easybuilders/easybuild-easyconfigs/pull/6487

### CODE REVIEW

**Comment by lexming** [comment]
Test report by @lexming
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
node101.hydra.os - Linux centos linux 7.7.1908, x86_64, Intel(R) Xeon(R) CPU E5-2680 v2 @ 2.80GHz, Python 2.7.5
See https://gist.github.com/290fc2b1d690db68fe520aaea4ac719d for a full test report.

**Review by boegel — APPROVED** [review]
lgtm

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
node2602.swalot.os - Linux centos linux 7.8.2003, x86_64, Intel(R) Xeon(R) CPU E5-2660 v3 @ 2.60GHz (haswell), Python 2.7.5
See https://gist.github.com/1a4db536748dcdd5a5818e22066ce239 for a full test report.

**Comment by boegel** [comment]
Going in, thanks @lexming!

**Pull request merged**
