### PR TITLE
{bio}[GCCcore/8.2.0] KronaTools v2.7

### PR DESCRIPTION
**Pull request by sassy-crick**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by vanzod** [comment]
@sassy-crick There is already a `KronaTools-2.7.1` easyconfig available for this toolchain. Is this older version needed for a specific reason? Moreover, the `install_cmd` in this PR differs from the one in other easyconfig files. Can you clarify on this please?

**Comment by vanzod** [comment]
@sassy-crick Is there a specific reason to add version `2.7` when `2.7.1` is already available with the same toolchain?

**Comment by migueldiascosta** [comment]
Test report by @migueldiascosta
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
sms - Linux centos linux 7.6.1810, AMD EPYC 7601 32-Core Processor, Python 2.7.5
See https://gist.github.com/07b653c3e71de6b14fcdc32079e1730d for a full test report.

**Comment by migueldiascosta** [comment]
@sassy-crick lgtm, but if there is no specific reason, it would be better not to have two versions with the same toolchain

**Comment by sassy-crick** [comment]
@migueldiascosta sorry for not looking into this earlier. The reason why I uploaded that was for completion, in case somebody needs this particular version. We can close this PR in this case though.

**Pull request closed without merging**
