### PR TITLE
fixing: USEARCH-11.0.667-i86linux32.eb . previous version was not downloading from web and had a non-functioning chmod command

### PR DESCRIPTION
**Pull request by scicomp-moffitt**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by SebastianAchilles** [comment]
@boegelbot please test @ generoso

**Comment by smoors** [comment]
Test report by @smoors
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
node350.hydra.os - Linux centos linux 7.9.2009, x86_64, Intel(R) Xeon(R) Gold 6148 CPU @ 2.40GHz (skylake_avx512), Python 2.7.5
See https://gist.github.com/f6a954dfa81ed6951a5a0d9f8c9df901 for a full test report.

**Review by smoors — APPROVED** [review]
lgtm

**Comment by smoors** [comment]
Going in, thanks @scicomp-moffitt!

**Pull request merged**
