### PR TITLE
{bio}[foss/2021a] pyradiomics v3.0.1 w/ Python 3.9.5

### PR DESCRIPTION
**Pull request by crubb**
(created using `eb --new-pr`)

Requires:
* #14949

### CODE REVIEW

**Comment by verdurin** [comment]
Test report by @verdurin
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
centos7.lan - Linux UNKNOWN UNKNOWN, x86_64, Intel Core Processor (Skylake, IBRS), Python 3.6.8
See https://gist.github.com/d6b779c163fe0c1e40065a25086f79ba for a full test report.

**Comment by verdurin** [comment]
Test report by @verdurin
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
easybuild-c7.novalocal - Linux UNKNOWN UNKNOWN, x86_64, Intel Xeon Processor (Skylake, IBRS), Python 3.6.8
See https://gist.github.com/7df9b9c84c95f27b390fc1a7209d8479 for a full test report.

**Comment by verdurin** [comment]
@boegelbot please test @ generoso

**Review by verdurin — APPROVED** [review]
Looks fine.

**Comment by smoors** [comment]
Going in, thanks @crubb!

**Pull request merged**
