### PR TITLE
tbl2asn {v20220427,v20230713} w/ linux64 - fix dependency with libidn.so.11

### PR DESCRIPTION
**Pull request by arielzn**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by arielzn** [comment]
The `tbl2asn` binary is linked to libidn.so.11 , this lib soname was present for the OS package on RHEL7 or Ubuntu 18.04, but it's not the case on RHEL8, or ubuntu 20.04

Trying to execute on these distros results on:

```
$ ml tbl2asn/20220427-linux64
$ tbl2asn
tbl2asn: error while loading shared libraries: libidn.so.11: cannot open shared object file: No such file or directory                       
```

As this is a binary install, In order to keep it at the system level, i propose a fix by using a Bundle building also an expected version of libidn for the binary.

**Comment by jfgrimm** [comment]
Test report by @jfgrimm
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in total)
gpu22.viking2.yor.alces.network - Linux Rocky Linux 8.8, x86_64, AMD EPYC 7413 24-Core Processor, 2 x NVIDIA NVIDIA H100 PCIe, 535.86.10, Python 3.6.8
See https://gist.github.com/jfgrimm/007b1f955b8bb90feaae2871d784ad4c for a full test report.

**Comment by jfgrimm** [comment]
@boegelbot: please test @ jsc-zen3

**Review by jfgrimm — APPROVED** [review]
lgtm

**Comment by jfgrimm** [comment]
Going in, thanks @arielzn!

**Pull request merged**
