### PR TITLE
{bio}[GCCcore/11.3.0] minimap2 v2.24

### PR DESCRIPTION
**Pull request by lexming**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by lexming** [comment]
@boegelbot: please test @ generoso

**Comment by lexming** [comment]
@boegelbot please test @ jsc-zen2

**Comment by casparvl** [comment]
Test report by @casparvl
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
tcn375.local.snellius.surf.nl - Linux Rocky Linux 8.7, x86_64, AMD EPYC 7H12 64-Core Processor, Python 3.6.8
See https://gist.github.com/3cbf3a0e7d909319c2bb3d4ccde51da3 for a full test report.

**Review by casparvl — APPROVED** [review]
Standard update, no surprises. Lgtm!

**Comment by casparvl** [comment]
Going in, thanks @lexming!

**Pull request merged**
