### PR TITLE
{math}[foss/2019b] Dakota v6.11.0 w/ Python 3.7.4

### PR DESCRIPTION
**Pull request by ekieffer**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by ekieffer** [comment]
Test report by @ULHPC
**FAILED**
Build succeeded for 0 out of 1 (1 easyconfigs in this PR)
iris-001 - Linux centos linux 7.8.2003, x86_64, Intel(R) Xeon(R) CPU E5-2680 v4 @ 2.40GHz, Python 3.6.8
See https://gist.github.com/2c02244de81a6eadcc64f2f9e69c9eea for a full test report.

**Comment by ekieffer** [comment]
Test report by @ULHPC
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
iris-001 - Linux centos linux 7.8.2003, x86_64, Intel(R) Xeon(R) CPU E5-2680 v4 @ 2.40GHz, Python 3.6.8
See https://gist.github.com/2db71429d31b8dae04af90593321e35d for a full test report.

**Comment by casparvl** [comment]
Hi Ekieffer, thanks for the PR! The test is failing because your EasyConfig contains a dependency on Python-3.7.4. We always make this explicitely clear by adding the Python version in the suffix. To do so, specify:
```
versionsuffix = '-Python-%(pyver)s'
```

**Comment by smoors** [comment]
@boegelbot please test @ generoso

**Comment by smoors** [comment]
Test report by @smoors
**FAILED**
Build succeeded for 0 out of 1 (1 easyconfigs in this PR)
node254.hydra.os - Linux centos linux 7.7.1908, x86_64, Intel(R) Xeon(R) CPU E5-2683 v4 @ 2.10GHz (broadwell), Python 2.7.5
See https://gist.github.com/95020de633976d90b5d8d1bc20e3f1ba for a full test report.

**Comment by smoors** [comment]
Test report by @smoors
**FAILED**
Build succeeded for 0 out of 1 (1 easyconfigs in this PR)
node362.hydra.os - Linux centos linux 7.7.1908, x86_64, Intel(R) Xeon(R) Gold 6148 CPU @ 2.40GHz (skylake_avx512), Python 2.7.5
See https://gist.github.com/c486faecab62dcabea7682f7868bd1e2 for a full test report.

**Comment by smoors** [comment]
some parallel tests fail for me:
```
The following tests FAILED:
         44 - pdakota_lib_split (Failed)
         52 - pdakota_multistart_ie (Failed)
Errors while running CTest
make: *** [test] Error 8
```

**Comment by lexming** [comment]
Test report by @lexming
**FAILED**
Build succeeded for 0 out of 1 (1 easyconfigs in this PR)
node368.hydra.os - Linux centos linux 7.7.1908, x86_64, Intel(R) Xeon(R) Gold 6148 CPU @ 2.40GHz, Python 2.7.5
See https://gist.github.com/8a84ed0c0fa91412cc2312b83fb41bad for a full test report.

**Comment by lexming** [comment]
Test report by @lexming
**FAILED**
Build succeeded for 0 out of 1 (1 easyconfigs in this PR)
node114.hydra.os - Linux centos linux 7.7.1908, x86_64, Intel(R) Xeon(R) CPU E5-2680 v2 @ 2.80GHz, Python 2.7.5
See https://gist.github.com/d5d6ba5ee9c672355e113729903f1f1f for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
node3521.doduo.os - Linux RHEL 8.2, x86_64, AMD EPYC 7552 48-Core Processor (zen2), Python 3.6.8
See https://gist.github.com/19b06ad0da64f88774c07126529de054 for a full test report.

**Comment by boegel** [comment]
@smoors Did you look into the specifics of those failing tests? Is it reproducible?

**Comment by smoors** [comment]
Test report by @smoors
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
node351.hydra.os - Linux centos linux 7.9.2009, x86_64, Intel(R) Xeon(R) Gold 6148 CPU @ 2.40GHz (skylake_avx512), Python 2.7.5
See https://gist.github.com/f67ee4a27a8e7bb7e58f5272717953c7 for a full test report.

**Comment by smoors** [comment]
Test report by @smoors
**FAILED**
Build succeeded for 0 out of 1 (1 easyconfigs in total)
node374.hydra.os - Linux centos linux 7.9.2009, x86_64, Intel(R) Xeon(R) Gold 6148 CPU @ 2.40GHz (skylake_avx512), Python 2.7.5
See https://gist.github.com/ce5b50adec64b2f1b88ba1477c62d036 for a full test report.

**Comment by smoors** [comment]
@boegel 
the failed reports were with 4 cores allocated, the succeeded report was with all 40 cores of a node allocated.

looking closer at the failed tests it occurs every time `MPIProcs` is set to a value higher than 4, see for example the first failing test below. so, I think it's ok, but I would suggest to add a comment in the easyconfig saying that you need at least 8 cores to run the tests (which is the highest number used in the tests).
```
      Start  44: pdakota_lib_split
 4/16 Test  #44: pdakota_lib_split ..................***Failed    3.22 sec

***
*** PREPROCESS step executing  /theia/home/apps/CO7/skylake/software/CMake/3.15.3-GCCcore-8.3.0/bin/cmake -E remove dakota_pdiffs.out
***


***
*** APPLICATION step executing  /apps/brussel/CO7/skylake/software/Perl/5.30.0-GCCcore-8.3.0/bin/perl /tmp/3768446.master01.hydra.brussel.vsc/Dakota/6.11.0/foss-2019b-Python-3.7.4/easybuild_obj/test/dakota_test.perl --parallel --output-dir=/tmp/3768446.master01.hydra.brussel.vsc/Dakota/6.11.0/foss-2019b-Python-3.7.4/easybuild_obj/test/pdakota_lib_split --bin-dir=/tmp/3768446.master01.hydra.brussel.vsc/Dakota/6.11.0/foss-2019b-Python-3.7.4/easybuild_obj/test dakota_lib_split.in
***

Testing in parallel, mode = run
Testing /tmp/3768446.master01.hydra.brussel.vsc/Dakota/6.11.0/foss-2019b-Python-3.7.4/dakota-6.11.0.src/test/dakota_lib_split.in
Using test option ExecCmd = dakota_library_split
Using test option MPIProcs = 4
Test Number 0 succeeded
<<<<< Function evaluation summary: 56 total (55 new, 1 duplicate)
<<<<< Best parameters          =
                      1.0003666224e+00 x1
                      1.0003666224e+00 x2
                      1.0003666224e+00 x3
<<<<< Best objective function  =
                      5.4199752832e-14
<<<<< Best data captured at function evaluation 55
<<<<< Function evaluation summary: 24 total (24 new, 0 duplicate)
<<<<< Best parameters          =
                      4.9988658610e-01 x1
                      4.9988658610e-01 x2
<<<<< Best objective function  =
                      1.2511345250e-01
<<<<< Best constraint values   =
                     -5.6694089465e-05
                     -5.6694089465e-05
<<<<< Best data captured at function evaluation 22
Using test option ExecCmd = dakota_library_split
Using test option MPIProcs = 6
Test Number 1 failed with exit code 1
Testing Script Complete.
CMake Error at TEST-pdakota_lib_split.cmake:34 (message):
  APPLICATION step failed with exit code 105 (Expected 0)
```

**Comment by smoors** [comment]
Test report by @smoors
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
node374.hydra.os - Linux centos linux 7.9.2009, x86_64, Intel(R) Xeon(R) Gold 6148 CPU @ 2.40GHz (skylake_avx512), Python 2.7.5
See https://gist.github.com/92e21d4f10738171dd5518fad8a40109 for a full test report.

**Comment by smoors** [comment]
the last test was with 8 cores.

**Review by smoors — CHANGES_REQUESTED** [review]
please add a comment in the easyconfig saying that you need at least 8 cores to run the tests

**Comment by boegel** [comment]
Looks like a dependency is missing?
```
-- Looking for pdb.h - not found
...
-- Configuring incomplete, errors occurred!
```

**Comment by boegel** [comment]
Test report by @boegel
**FAILED**
Build succeeded for 0 out of 1 (1 easyconfigs in total)
node3580.doduo.os - Linux RHEL 8.2, x86_64, AMD EPYC 7552 48-Core Processor (zen2), Python 3.6.8
See https://gist.github.com/2be0709d3966e19faf639069c8b6f79a for a full test report.

**Comment by Falkor** [comment]
@boegel sorry I cannot reproduce the missing dependency you met (yet on CentOS 7) 
@smoors your comment was addressed.

**Comment by boegel** [comment]
@boegelbot please test @ generoso
CORE_CNT=16

**Comment by smoors** [comment]
@ekieffer can you please add the following patch, which fixes the configure error from @boegel for me (I tried to upload it myself, but you have disallowed edits by maintainers :)
```
diff -ur dakota-6.11.0.src.orig/CMakeLists.txt dakota-6.11.0.src/CMakeLists.txt
--- dakota-6.11.0.src.orig/CMakeLists.txt       2019-11-08 01:19:53.000000000 +0100
+++ dakota-6.11.0.src/CMakeLists.txt    2022-09-01 16:38:30.349794048 +0200
@@ -360,7 +360,7 @@
   set(Boost_USE_STATIC_LIBS TRUE)
 endif()
 # Dakota requires Boost 1.49 or newer; enforce for all libs in the build
-find_package(Boost 1.49 REQUIRED COMPONENTS "${dakota_boost_components}")
+find_package(Boost 1.49 REQUIRED COMPONENTS ${dakota_boost_components})
 # This cache variable is used to package the Boost liraries on Darwin (see
 # cmake/InstallDarwinDylibs.cmake). The variable Boost_LIBRARY_DIRS is set
 # in this scope by the CMake Boost probe (at least for CMake 3.5.2), but
```

**Comment by deniskristak** [comment]
@smoors thank you for the patch, it seems to have worked...i've opened new PR on more recent toolchain here https://github.com/easybuilders/easybuild-easyconfigs/pull/16190

**Comment by akesandgren** [comment]
Closing since we already have a newer version available, #15883

**Pull request closed without merging**
