### PR TITLE
{bio}[gompi/2021b] Unicycler v0.5.0 w/ Python 3.9.6

### PR DESCRIPTION
**Pull request by SethosII**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by jfgrimm** [comment]
see also: https://github.com/easybuilders/easybuild-easyconfigs/pull/15840#issuecomment-1183321721

**Comment by SethosII** [comment]
@jfgrimm They seem to have relaxed the version requirements in this release: https://github.com/rrwick/Unicycler/commit/6f12fae889d5b37b96e3d5fbd2958454c9993e50.

**Comment by SethosII** [comment]
@jfgrimm I added a test as you proposed in the linked comment.

**Comment by jfgrimm** [comment]
@boegelbot please test @ generoso

**Comment by jfgrimm** [comment]
@boegelbot please test @ jsc-zen2

**Review by jfgrimm — APPROVED** [review]
LGTM

**Comment by jfgrimm** [comment]
Going in, thanks @SethosII!

**Pull request merged**
