### PR TITLE
{debugger}[foss/2017b] GDB v8.0.1 w/ Python 2.7.14 + 3.6.3

### PR DESCRIPTION
**Pull request by murfreesboro**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by murfreesboro** [comment]
the GDB with foss toolchain went through smoothly. However, with the Intel compiler I have the following undefined reference error:
`build-gnulib/import/libgnu.a(glob.o): In function `rpl_glob':
glob.c:(.text+0x17e): undefined reference to `__builtin_add_overflow'
glob.c:(.text+0x52c): undefined reference to `__builtin_add_overflow'
glob.c:(.text+0xf18): undefined reference to `__builtin_add_overflow'
glob.c:(.text+0xfce): undefined reference to `__builtin_add_overflow'
glob.c:(.text+0x1073): undefined reference to `__builtin_add_overflow'
build-gnulib/import/libgnu.a(glob.o):glob.c:(.text+0x11e6): more undefined references to `__builtin_add_overflow' follow
make[2]: *** [gdb] Error 1`

**Comment by murfreesboro** [comment]
Test report by @murfreesboro
**FAILED**
Build succeeded for 2 out of 4 (4 easyconfigs in this PR)
dev806.vampire - Linux centos linux 7.4.1708, Intel(R) Xeon(R) CPU           E5620  @ 2.40GHz, Python 2.7.5
See https://gist.github.com/7a60d066074f904a4cb8a6099f3c09c9 for a full test report.

**Comment by vanzod** [comment]
Test report by @vanzod
**FAILED**
Build succeeded for 2 out of 4 (4 easyconfigs in this PR)
cermis - Linux debian 9.8, Intel(R) Xeon(R) CPU           X5670  @ 2.93GHz, Python 2.7.13
See https://gist.github.com/aeee973cccde3f55401952954aefa975 for a full test report.

**Comment by vanzod** [comment]
@murfreesboro I believe the problem is due to the fact that this version of the Intel compiler does not include such builtin functions. Here is a reference for this problem:
https://software.intel.com/en-us/forums/intel-c-compiler/topic/720757

I took a look at the `GDB` sources and such functions have been introduced in the source from version 8.1, while they are missing from version 8.0.1. I would say it is worth to give it a try with this version and see if the compiler likes it.

**Comment by akesandgren** [comment]
Test report by @akesandgren
**FAILED**
Build succeeded for 4 out of 6 (4 easyconfigs in this PR)
b-an03.hpc2n.umu.se - Linux ubuntu 16.04, Intel(R) Xeon(R) CPU E5-2690 v4 @ 2.60GHz, Python 2.7.12
See https://gist.github.com/d79b473b8833c014d7b2aa5927360416 for a full test report.

**Comment by murfreesboro** [comment]
tested it again now with the lower version it seems passed.

**Comment by murfreesboro** [comment]
Test report by @murfreesboro
**SUCCESS**
Build succeeded for 4 out of 4 (4 easyconfigs in this PR)
dev806.vampire - Linux centos linux 7.4.1708, Intel(R) Xeon(R) CPU           E5620  @ 2.40GHz, Python 2.7.5
See https://gist.github.com/c56cebfcc1cb9c5f4c0d87867c4de4cc for a full test report.

**Comment by akesandgren** [comment]
Btw, GDB belongs at the GCCcore level, it's definitely not performance critical.
Thereby we can bypass the problem with compiling it with intel.

**Comment by boegel** [comment]
+1 on @akesandgren's comment, there's little point in building GDB with Intel compilers...

**Comment by murfreesboro** [comment]
@akesandgren exactly, considering this point actually a GCCcore version of GDB is better.

**Comment by murfreesboro** [comment]
Hi @akesandgren and @boegel, for the GCCcore version of GDB; is there any debugging symbol that GDB can not collect from the binary compiled from Intel compiler?  Just want to make sure GDB works fine with any Intel compiled binary.

**Comment by akesandgren** [comment]
Well, as long as the intel compiler follows the DWARF3 standard (I think that's the one anyway, it's been a while) then GDB can handle it. If they don't then it doesn't matter which compiler you build GDB with.

**Comment by murfreesboro** [comment]
Test report by @murfreesboro
**SUCCESS**
Build succeeded for 4 out of 4 (4 easyconfigs in this PR)
dev806.vampire - Linux centos linux 7.4.1708, Intel(R) Xeon(R) CPU           E5620  @ 2.40GHz, Python 2.7.5
See https://gist.github.com/180f18065ab479976b4c7be523e7a8c5 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**FAILED**
Build succeeded for 2 out of 4 (4 easyconfigs in this PR)
node2472.golett.os - Linux centos linux 7.6.1810, Intel(R) Xeon(R) CPU E5-2680 v3 @ 2.50GHz, Python 2.7.5
See https://gist.github.com/a05d25b1b9108677be9536325bcc0cdd for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**FAILED**
Build succeeded for 2 out of 4 (4 easyconfigs in this PR)
node3147.skitty.os - Linux centos linux 7.6.1810, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz, Python 2.7.5
See https://gist.github.com/059bf046e5b9c58c964445bfd9ae4fb6 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**FAILED**
Build succeeded for 2 out of 4 (4 easyconfigs in this PR)
node2057.delcatty.os - Linux centos linux 7.6.1810, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.7.5
See https://gist.github.com/d9274ab301dc4f94167830154870ca3e for a full test report.

**Comment by murfreesboro** [comment]
I see the failed report, it seems still the same problem due to the incompatibility between GCC and Intel compiler. How about we just drop the Intel version of GDB? @boegel , @vanzod and @akesandgren ?

**Comment by akesandgren** [comment]
I'd drop it. Intel contains its own debugger based on GDB anyway.

**Comment by boegel** [comment]
+1 on dropping GDB built with `intel` toolchain

**Comment by vanzod** [comment]
Test report by @vanzod
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in this PR)
cermis - Linux debian 9.8, Intel(R) Xeon(R) CPU           X5670  @ 2.93GHz, Python 2.7.13
See https://gist.github.com/ba3ed3816b411ffbc5d4bd8c4d020c3c for a full test report.

**Comment by vanzod** [comment]
Going in, thanks @murfreesboro!

**Pull request merged**
