### PR TITLE
{bio}[foss/2018b] pangolin 3.0.5 w/ Python 3.7.0 and dependencies

### PR DESCRIPTION
**Pull request by SethosII**
(created using `eb --new-pr`)

This is my attempt to build pangolin from source.

They don't give instructions to build it from source and suggest to resort to conda: https://cov-lineages.org/pangolin_docs/installation.html. I based my attempt on their [environment.yml](https://github.com/cov-lineages/pangolin/blob/master/environment.yml). Some dependencies are given with fixed and/or more recent versions, than what is currently used in the foss-2018b toolchain therefore the checks are failing.

This replaces #13069.

### CODE REVIEW

**Comment by SethosII** [comment]
Test report by @SethosII
**SUCCESS**
Build succeeded for 17 out of 17 (16 easyconfigs in total)
ribnode015 - Linux ubuntu 18.04, x86_64, Intel(R) Xeon(R) CPU           E5645  @ 2.40GHz, Python 2.7.17
See https://gist.github.com/e37b65d9aea2343d72e8062c6fe5b17a for a full test report.

**Comment by sassy-crick** [comment]
@SethosII I am working on Pangolin-3.1.9. Want to join force? Are you on the EasyBuild Slack?

**Comment by SethosII** [comment]
@sassy-crick Of course, you're welcome! But I'm not on Slack.

I also have an easyconfig for `pangolin/3.1.5` with `foss/2018b`, so it should be only a matter of changing the version numbers and checksums. I haven't created a pull request for it because nobody seemed to be interested in `pangolin` until now :)

What toolchain are you using? I will also create one for `foss/2021a` (or `gompi/2021a`/`GCC-10.3.0` respectively).

**Comment by sassy-crick** [comment]
@SethosII Sounds good to me. I was aiming for the `foss-2021a` or so as well, i.e. the latest one. I was working on `usher-0.4.1` which requires `TBB` as you know and here I hit this [wall](https://github.com/easybuilders/easybuild-easyconfigs/pull/13404) on Friday. This is when I called it a day as it was late. 
I got [Snakemake](https://github.com/easybuilders/easybuild-easyconfigs/pull/13483) and [minimap2](https://github.com/easybuilders/easybuild-easyconfigs/pull/13481) merged and [gofasta](https://github.com/easybuilders/easybuild-easyconfigs/pull/13651) as PR open. I also have `Biopython-1.79` for `foss-2021a` if that helps but not as a PR (see [PR 13574](https://github.com/easybuilders/easybuild-easyconfigs/pull/13574) for discussion).
I might use an earlier version of TBB to get that moving which is not something I would like to do as I prefer to have the latest software if possible when I do EC.
I have not done yet: pangoLEARN, scorpio, constellations, pango-designation
Hope that helps.

**Comment by SethosII** [comment]
@sassy-crick Sorry for the delay. Yes, `TBB` is also needed for other stuff and I'm stuck there as well. I would also prefer the most recent version. A `Biopython-1.79-foss-2021a.eb` EasyConfig already exists. I include `pangoLEARN`, `scorpio`, `constellations` and `pango-designation` as extensions in my `pangolin` EasyConfigs. I will create a new PR for 2021a and link it here.

**Comment by sassy-crick** [comment]
@SethosII That would be great if you can do that! I think we now have all the relavants bits in place apart from the `user` 
If you like, I can finish off my EC I started when I hit the `TBB` problem. Do you happen to know if `TBB` is used in any of the other programs we need for `pangolin` ? I have not seen it but it is better to double check. So, I would suggest given the current stopper to use a slightly older version of `TBB` which does not show that problem so we can move forward. 
All of the programs I mentioned above are merged as far as I can see. 
So if you are happy, I can do the `usher` and you can finish off the `pangolin` ?
I think we are getting there. :+1:

**Comment by SethosII** [comment]
@sassy-crick I created the PR for `pangolin`: https://github.com/easybuilders/easybuild-easyconfigs/pull/13681.

There is no other dependency in `pangolin` that needs `TBB`. I would recommend to create an EasyConfig for `usher` with the current `tbb` version and hope that the PR for `tbb` gets resolved. Maybe we can give a reminder in the `tbb` PR on the importance for other software.

**Comment by sassy-crick** [comment]
@sassy-crick  Many thanks! I have downloaded the PR and I am updating it to the latest toolchain etc.Once done, do you want to upload it as PR or shall I do it? Either way is fine with me.

**Comment by SethosII** [comment]
@sassy-crick Oh, I forgot to change the toolchain to `foss/2021a`, I corrected it. But feel free to change anything you see fit.

**Comment by sassy-crick** [comment]
@SethosII No worries, I was working on that. Did you actually ever manage to install it? I got some problems with `tbb` and `UShER` right now.

**Comment by SethosII** [comment]
@sassy-crick No, I just inserted the version there. What exactly is the issue you have? Can you create a PR for `UShER` and we try to solve it there?

**Comment by sassy-crick** [comment]
@SethosII I uploaded what I have so far to PR [13694](https://github.com/easybuilders/easybuild-easyconfigs/pull/13694)

**Comment by sassy-crick** [comment]
I have created a working version for `UShER` and updated my PR

**Comment by sassy-crick** [comment]
@SethosII I have a working version for `pangolin` as well. Happy to share it with you, given you done the ground work for it. 
Just let me know.

**Comment by SethosII** [comment]
@sassy-crick Just create a PR for it yourself. I'm happy as long as there is a working pangolin in EasyBuild ;)

**Comment by sassy-crick** [comment]
@SethosII Done. I have created PR [13733](https://github.com/easybuilders/easybuild-easyconfigs/pull/13733) and acknowledge you in the header.

**Comment by sassy-crick** [comment]
@SethosII Many thanks for your help for this which I do appreciate and apologies for spelling your name wrong!

**Comment by SethosII** [comment]
@sassy-crick No worries, you're welcome. I'm glad that I could help you.

**Pull request closed without merging**
