### PR TITLE
consistently add libffi + elfutils dependencies to recent Clang easyconfigs

### PR DESCRIPTION
**Pull request by boegel**
(created using `eb --new-pr`)

edit: requires:
* https://github.com/easybuilders/easybuild-easyblocks/pull/2783

### CODE REVIEW

**Comment by boegel** [comment]
@boegelbot please test @ generoso
CORE_CNT=16

**Comment by boegel** [comment]
Sanity check for Clang v11.0.1 failed, see also https://github.com/easybuilders/easybuild-easyblocks/issues/2782

**Comment by boegel** [comment]
@boegelbot please test @ generoso
EB_ARGS="--include-easyblocks-from-pr 2783 --module-only"

**Comment by SebastianAchilles** [comment]
@boegelbot please test @ jsc-zen2
EB_ARGS="--include-easyblocks-from-pr 2783 --module-only"

**Review by SebastianAchilles — APPROVED** [review]
lgtm

**Comment by SebastianAchilles** [comment]
Going in, thanks @boegel!

**Pull request merged**
