### PR TITLE
in-place update for cryoDRGN to v0.3.5 with foss/2021a to fix compatibility issue with PyTorch v1.10

### PR DESCRIPTION
**Pull request by boegel**
cfr. https://github.com/zhonge/cryodrgn/issues/81, which is fixed with https://github.com/zhonge/cryodrgn/commit/80aa37612a5eda018f0553a23a26c8ad38fd2459, which is included in cryoDRGN v0.3.5

### CODE REVIEW

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
node3300.joltik.os - Linux RHEL 8.4, x86_64, Intel(R) Xeon(R) Gold 6242 CPU @ 2.80GHz (cascadelake), Python 3.6.8
See https://gist.github.com/40e8fa7b3f5b53fb413066352396fe3f for a full test report.

**Review by branfosj — APPROVED** [review]
lgtm

**Comment by branfosj** [comment]
Test report by @branfosj
**SUCCESS**
Build succeeded for 8 out of 8 (1 easyconfigs in total)
bear-pg0105u36b.bear.cluster - Linux RHEL 8.6, x86_64, Intel(R) Xeon(R) Platinum 8360Y CPU @ 2.40GHz (icelake), Python 3.6.8
See https://gist.github.com/db5baa1c371d756cccc055446067d4b9 for a full test report.

**Comment by branfosj** [comment]
Going in, thanks @boegel!

**Pull request merged**
