### PR TITLE
{compiler}[GCC/6.4.0-2.28] Clang v5.0.0

### PR DESCRIPTION
**Pull request by boegel**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by boegel** [comment]
Test report by @boegel
**FAILED**
Build succeeded for 0 out of 1 (1 easyconfigs in this PR)
node2414.golett.os - Linux centos linux 7.4.1708, Intel(R) Xeon(R) CPU E5-2680 v3 @ 2.50GHz, Python 2.7.5
See https://gist.github.com/23f29a81f1c23d2692a32590953aa617 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**FAILED**
Build succeeded for 0 out of 1 (1 easyconfigs in this PR)
node2158.delcatty.os - Linux centos linux 7.4.1708, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.7.5
See https://gist.github.com/653e34112f9138002e36b2fe7cfab22e for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
node2121.delcatty.os - Linux centos linux 7.4.1708, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.7.5
See https://gist.github.com/22b5085f329d468a607c9666f4ce9c57 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
node2407.golett.os - Linux centos linux 7.4.1708, Intel(R) Xeon(R) CPU E5-2680 v3 @ 2.50GHz, Python 2.7.5
See https://gist.github.com/26b2331eae2e03562ccc7324a7932838 for a full test report.

**Comment by verdurin** [comment]
Test report by @verdurin
**FAILED**
Build succeeded for 4 out of 5 (1 easyconfigs in this PR)
rescomp2 - Linux centos 6.8, Intel(R) Xeon(R) CPU E5-2650 v2 @ 2.60GHz, Python 2.7.11
See https://gist.github.com/db3de8cf84560a395c9aec4bf372a635 for a full test report.

**Comment by verdurin** [comment]
Still failing for me on `CentOS 6.8`:
```
FAIL: AddressSanitizer-x86_64-linux :: TestCases/Linux/cuda_test.cc (2763 of 35807)
******************** TEST 'AddressSanitizer-x86_64-linux :: TestCases/Linux/cuda_test.cc' FAILED ********************
Script:
--
/dev/shm/Clang/5.0.0/GCC-6.4.0-2.28/llvm.obj.1/./bin/clang --driver-mode=g++ -fsanitize=address -mno-omit-leaf-frame-pointer -fno-omit-frame-pointer -fno-optimize-sibling-calls -gline-tables-only -m64 /dev/shm/Clang/5.0.0/GCC-6.4.0-2.28/llvm-5.0.0.src/projects/compiler-rt/test/asan/TestCases/Linux/cuda_test.cc -o /dev/shm/Clang/5.0.0/GCC-6.4.0-2.28/llvm.obj.1/projects/compiler-rt/test/asan/X86_64LinuxConfig/TestCases/Linux/Output/cuda_test.cc.tmp
not env ASAN_OPTIONS=protect_shadow_gap=1 /dev/shm/Clang/5.0.0/GCC-6.4.0-2.28/llvm.obj.1/projects/compiler-rt/test/asan/X86_64LinuxConfig/TestCases/Linux/Output/cuda_test.cc.tmp 2>&1 | FileCheck /dev/shm/Clang/5.0.0/GCC-6.4.0-2.28/llvm-5.0.0.src/projects/compiler-rt/test/asan/TestCases/Linux/cuda_test.cc  --check-prefix=CHECK-PROTECT1
not                                     /dev/shm/Clang/5.0.0/GCC-6.4.0-2.28/llvm.obj.1/projects/compiler-rt/test/asan/X86_64LinuxConfig/TestCases/Linux/Output/cuda_test.cc.tmp 2>&1 | FileCheck /dev/shm/Clang/5.0.0/GCC-6.4.0-2.28/llvm-5.0.0.src/projects/compiler-rt/test/asan/TestCases/Linux/cuda_test.cc  --check-prefix=CHECK-PROTECT1
not env ASAN_OPTIONS=protect_shadow_gap=0 /dev/shm/Clang/5.0.0/GCC-6.4.0-2.28/llvm.obj.1/projects/compiler-rt/test/asan/X86_64LinuxConfig/TestCases/Linux/Output/cuda_test.cc.tmp 2>&1 | FileCheck /dev/shm/Clang/5.0.0/GCC-6.4.0-2.28/llvm-5.0.0.src/projects/compiler-rt/test/asan/TestCases/Linux/cuda_test.cc  --check-prefix=CHECK-PROTECT0
--
Exit Code: 1

Command Output (stderr):
--
/dev/shm/Clang/5.0.0/GCC-6.4.0-2.28/llvm-5.0.0.src/projects/compiler-rt/test/asan/TestCases/Linux/cuda_test.cc:34:21: error: expected string not found in input
 // CHECK-PROTECT0: AddressSanitizer: use-after-poison on address 0x0002000004d2
                    ^
<stdin>:1:1: note: scanning from here
Error: Segmentation fault
^

--

********************
Testing: 0 .
FAIL: AddressSanitizer-x86_64-linux :: TestCases/Linux/nohugepage_test.cc (2786 of 35807)
******************** TEST 'AddressSanitizer-x86_64-linux :: TestCases/Linux/nohugepage_test.cc' FAILED ********************
Script:
--
/dev/shm/Clang/5.0.0/GCC-6.4.0-2.28/llvm.obj.1/./bin/clang --driver-mode=g++ -fsanitize=address -mno-omit-leaf-frame-pointer -fno-omit-frame-pointer -fno-optimize-sibling-calls -gline-tables-only -m64 -g /dev/shm/Clang/5.0.0/GCC-6.4.0-2.28/llvm-5.0.0.src/projects/compiler-rt/test/asan/TestCases/Linux/nohugepage_test.cc -o /dev/shm/Clang/5.0.0/GCC-6.4.0-2.28/llvm.obj.1/projects/compiler-rt/test/asan/X86_64LinuxConfig/TestCases/Linux/Output/nohugepage_test.cc.tmp
env ASAN_OPTIONS=no_huge_pages_for_shadow=1  /dev/shm/Clang/5.0.0/GCC-6.4.0-2.28/llvm.obj.1/projects/compiler-rt/test/asan/X86_64LinuxConfig/TestCases/Linux/Output/nohugepage_test.cc.tmp 2>&1 | FileCheck /dev/shm/Clang/5.0.0/GCC-6.4.0-2.28/llvm-5.0.0.src/projects/compiler-rt/test/asan/TestCases/Linux/nohugepage_test.cc
/dev/shm/Clang/5.0.0/GCC-6.4.0-2.28/llvm.obj.1/projects/compiler-rt/test/asan/X86_64LinuxConfig/TestCases/Linux/Output/nohugepage_test.cc.tmp 2>&1 | FileCheck /dev/shm/Clang/5.0.0/GCC-6.4.0-2.28/llvm-5.0.0.src/projects/compiler-rt/test/asan/TestCases/Linux/nohugepage_test.cc
--
Exit Code: 1

Command Output (stderr):
--
/dev/shm/Clang/5.0.0/GCC-6.4.0-2.28/llvm-5.0.0.src/projects/compiler-rt/test/asan/TestCases/Linux/nohugepage_test.cc:107:11: error: expected string not found in input
// CHECK: RSS CHANGE IS 3 => 4: LARGE
          ^
<stdin>:4:29: note: scanning from here
RSS CHANGE IS 2 => 3: SMALL (17160 vs 49928)
                            ^
<stdin>:5:1: note: possible intended match here
RSS CHANGE IS 3 => 4: SMALL (49928 vs 49928)
^

--

********************
Testing: 0 .
FAIL: AddressSanitizer-x86_64-linux :: TestCases/Linux/quarantine_size_mb.cc (2796 of 35807)
******************** TEST 'AddressSanitizer-x86_64-linux :: TestCases/Linux/quarantine_size_mb.cc' FAILED ********************
Script:
--
/dev/shm/Clang/5.0.0/GCC-6.4.0-2.28/llvm.obj.1/./bin/clang --driver-mode=g++ -fsanitize=address -mno-omit-leaf-frame-pointer -fno-omit-frame-pointer -fno-optimize-sibling-calls -gline-tables-only -m64  /dev/shm/Clang/5.0.0/GCC-6.4.0-2.28/llvm-5.0.0.src/projects/compiler-rt/test/asan/TestCases/Linux/quarantine_size_mb.cc -o /dev/shm/Clang/5.0.0/GCC-6.4.0-2.28/llvm.obj.1/projects/compiler-rt/test/asan/X86_64LinuxConfig/TestCases/Linux/Output/quarantine_size_mb.cc.tmp
env ASAN_OPTIONS=quarantine_size=10485760:verbosity=1:hard_rss_limit_mb=50  /dev/shm/Clang/5.0.0/GCC-6.4.0-2.28/llvm.obj.1/projects/compiler-rt/test/asan/X86_64LinuxConfig/TestCases/Linux/Output/quarantine_size_mb.cc.tmp  2>&1 | FileCheck /dev/shm/Clang/5.0.0/GCC-6.4.0-2.28/llvm-5.0.0.src/projects/compiler-rt/test/asan/TestCases/Linux/quarantine_size_mb.cc  --check-prefix=Q10
env ASAN_OPTIONS=quarantine_size_mb=10:verbosity=1:hard_rss_limit_mb=50     /dev/shm/Clang/5.0.0/GCC-6.4.0-2.28/llvm.obj.1/projects/compiler-rt/test/asan/X86_64LinuxConfig/TestCases/Linux/Output/quarantine_size_mb.cc.tmp  2>&1 | FileCheck /dev/shm/Clang/5.0.0/GCC-6.4.0-2.28/llvm-5.0.0.src/projects/compiler-rt/test/asan/TestCases/Linux/quarantine_size_mb.cc  --check-prefix=Q10
env ASAN_OPTIONS=quarantine_size_mb=10:quarantine_size=20:verbosity=1  not  /dev/shm/Clang/5.0.0/GCC-6.4.0-2.28/llvm.obj.1/projects/compiler-rt/test/asan/X86_64LinuxConfig/TestCases/Linux/Output/quarantine_size_mb.cc.tmp  2>&1 | FileCheck /dev/shm/Clang/5.0.0/GCC-6.4.0-2.28/llvm-5.0.0.src/projects/compiler-rt/test/asan/TestCases/Linux/quarantine_size_mb.cc  --check-prefix=BOTH
env ASAN_OPTIONS=quarantine_size_mb=1000:hard_rss_limit_mb=50 not   /dev/shm/Clang/5.0.0/GCC-6.4.0-2.28/llvm.obj.1/projects/compiler-rt/test/asan/X86_64LinuxConfig/TestCases/Linux/Output/quarantine_size_mb.cc.tmp          2>&1 | FileCheck /dev/shm/Clang/5.0.0/GCC-6.4.0-2.28/llvm-5.0.0.src/projects/compiler-rt/test/asan/TestCases/Linux/quarantine_size_mb.cc  --check-prefix=RSS_LIMIT
env ASAN_OPTIONS=hard_rss_limit_mb=20                         not   /dev/shm/Clang/5.0.0/GCC-6.4.0-2.28/llvm.obj.1/projects/compiler-rt/test/asan/X86_64LinuxConfig/TestCases/Linux/Output/quarantine_size_mb.cc.tmp          2>&1 | FileCheck /dev/shm/Clang/5.0.0/GCC-6.4.0-2.28/llvm-5.0.0.src/projects/compiler-rt/test/asan/TestCases/Linux/quarantine_size_mb.cc  --check-prefix=RSS_LIMIT
--
Exit Code: 1


********************
Testing: 0 .. 10.. 20.. 30.. 40.. 50.. 60.. 70.. 80.. 90..

1 warning(s) in tests.
Testing Time: 667.92s
********************
Failing Tests (3):
    AddressSanitizer-x86_64-linux :: TestCases/Linux/cuda_test.cc
    AddressSanitizer-x86_64-linux :: TestCases/Linux/nohugepage_test.cc
    AddressSanitizer-x86_64-linux :: TestCases/Linux/quarantine_size_mb.cc

  Expected Passes    : 26655
  Expected Failures  : 113
  Unsupported Tests  : 9036
  Unexpected Failures: 3
```

**Comment by boegel** [comment]
This looks very familiar, I wonder if @wpoely86 still remembers what's this about...

**Comment by wpoely86** [comment]
Yes, the sanitizer tests are tricky. You can disable them without any issue. I think we already disable by default is there is a virtual memory limit set.

**Comment by verdurin** [comment]
@boegel - are you happy to disable those tests by default? Or just refer to the potential problem as a comment in the `easyconfig` and leave them enabled?

**Comment by boegel** [comment]
The Clang easyblock disabling the sanitizer tests automagically under certain conditions, but it seems like the patching it does in `disable_sanitizer_tests` is no longer correct for Clang 5.x, so we'll need to update it...

**Comment by boegel** [comment]
@verdurin Can you give this a try on top of the updated `Clang` easyblock available in https://github.com/easybuilders/easybuild-easyblocks/pull/1327?

**Comment by verdurin** [comment]
Test report by @verdurin
**FAILED**
Build succeeded for 0 out of 1 (1 easyconfigs in this PR)
rescomp2 - Linux centos 6.8, Intel(R) Xeon(R) CPU E5-2650 v2 @ 2.60GHz, Python 2.7.11
See https://gist.github.com/352dcf74ed182215fd396785a3858aea for a full test report.

**Comment by boegel** [comment]
@verdurin Was that last test indeed on top of the updated `Clang` easyblock? If so, would you mind sending me the full debug log?

**Comment by boegel** [comment]
@verdurin The debug log you sent me (thanks!) shows that you have `ulimit -v` set to `unlimited` and `ulimit -s` set to `10240` (i.e. != `unlimited`).

Under those conditions, the Clang easyblock doesn't disable the sanitizer tests, but apparently it should, at least on your system...

Any ideas here @wpoely86?

@verdurin Can you share the output of `ulimit -a` on that system?

**Comment by wpoely86** [comment]
Well, the sanitizers are tricky. I'm not sure about the exact conditions under which they work reliable. Maybe we should try to disable them from being build in the first place? On a ordinary desktop system, they will work fine but under HPC conditions, it's tricky.

**Comment by boegel** [comment]
We could hard set `skip_sanitizer_tests` to `True`, but maybe only for `Clang` 5.0.0?

@verdurin Do you have any problems installing older `Clang` versions on that system?

**Comment by verdurin** [comment]
Test report by @verdurin
**FAILED**
Build succeeded for 0 out of 1 (1 easyconfigs in this PR)
rescomp2 - Linux centos 6.8, Intel(R) Xeon(R) CPU E5-2650 v2 @ 2.60GHz, Python 2.7.11
See https://gist.github.com/6ff3db5887a3e0a64e2a0d61bf40df98 for a full test report.

**Comment by verdurin** [comment]
This for `Clang 3.8.1`:
```
Testing:
FAIL: AddressSanitizer-x86_64-linux :: TestCases/Linux/nohugepage_test.cc (275 of 26702)
******************** TEST 'AddressSanitizer-x86_64-linux :: TestCases/Linux/nohugepage_test.cc' FAILED ********************
Script:
--
/dev/shm/Clang/3.8.1/GCC-5.4.0-2.26/llvm.obj.1/./bin/clang --driver-mode=g++ -fsanitize=address -mno-omit-leaf-frame-pointer -fno-omit-frame-pointer -fn
o-optimize-sibling-calls -gline-tables-only -m64 -g /dev/shm/Clang/3.8.1/GCC-5.4.0-2.26/llvm-3.8.1.src/projects/compiler-rt/test/asan/TestCases/Linux/no
hugepage_test.cc -o /dev/shm/Clang/3.8.1/GCC-5.4.0-2.26/llvm.obj.1/projects/compiler-rt/test/asan/X86_64LinuxConfig/TestCases/Linux/Output/nohugepage_te
st.cc.tmp
env ASAN_OPTIONS=no_huge_pages_for_shadow=1  /dev/shm/Clang/3.8.1/GCC-5.4.0-2.26/llvm.obj.1/projects/compiler-rt/test/asan/X86_64LinuxConfig/TestCases/Linux/Output/nohugepage_test.cc.tmp 2>&1 | FileCheck /dev/shm/Clang/3.8.1/GCC-5.4.0-2.26/llvm-3.8.1.src/projects/compiler-rt/test/asan/TestCases/Linux/nohugepage_test.cc
/dev/shm/Clang/3.8.1/GCC-5.4.0-2.26/llvm.obj.1/projects/compiler-rt/test/asan/X86_64LinuxConfig/TestCases/Linux/Output/nohugepage_test.cc.tmp 2>&1 | FileCheck /dev/shm/Clang/3.8.1/GCC-5.4.0-2.26/llvm-3.8.1.src/projects/compiler-rt/test/asan/TestCases/Linux/nohugepage_test.cc
--
Exit Code: 1

Command Output (stderr):
--
/dev/shm/Clang/3.8.1/GCC-5.4.0-2.26/llvm-3.8.1.src/projects/compiler-rt/test/asan/TestCases/Linux/nohugepage_test.cc:107:11: error: expected string not found in input
// CHECK: RSS CHANGE IS 3 => 4: LARGE
          ^
<stdin>:4:29: note: scanning from here
RSS CHANGE IS 2 => 3: SMALL (8964 vs 41732)
                            ^
<stdin>:5:1: note: possible intended match here
RSS CHANGE IS 3 => 4: SMALL (41732 vs 41732)
^

--

********************
Testing: 0 .. 10.. 20.. 30.. 40.. 50.. 60.. 70.. 80.. 90
FAIL: LeakSanitizer-AddressSanitizer :: TestCases/stale_stack_leak.cc (25120 of 26702)
******************** TEST 'LeakSanitizer-AddressSanitizer :: TestCases/stale_stack_leak.cc' FAILED ********************
Script:
--
LSAN_BASE="report_objects=1:use_registers=0:use_stacks=1"
/dev/shm/Clang/3.8.1/GCC-5.4.0-2.26/llvm.obj.1/./bin/clang --driver-mode=g++ -O0 -m64 -gline-tables-only -fsanitize=address /dev/shm/Clang/3.8.1/GCC-5.4.0-2.26/llvm-3.8.1.src/projects/compiler-rt/test/lsan/TestCases/stale_stack_leak.cc -o /dev/shm/Clang/3.8.1/GCC-5.4.0-2.26/llvm.obj.1/projects/compiler-rt/test/lsan/AsanConfig/TestCases/Output/stale_stack_leak.cc.tmp
LSAN_OPTIONS=$LSAN_BASE not  /dev/shm/Clang/3.8.1/GCC-5.4.0-2.26/llvm.obj.1/projects/compiler-rt/test/lsan/AsanConfig/TestCases/Output/stale_stack_leak.cc.tmp 2>&1 | FileCheck /dev/shm/Clang/3.8.1/GCC-5.4.0-2.26/llvm-3.8.1.src/projects/compiler-rt/test/lsan/TestCases/stale_stack_leak.cc
LSAN_OPTIONS=$LSAN_BASE":exitcode=0"  /dev/shm/Clang/3.8.1/GCC-5.4.0-2.26/llvm.obj.1/projects/compiler-rt/test/lsan/AsanConfig/TestCases/Output/stale_stack_leak.cc.tmp 2>&1 | FileCheck --check-prefix=CHECK-sanity /dev/shm/Clang/3.8.1/GCC-5.4.0-2.26/llvm-3.8.1.src/projects/compiler-rt/test/lsan/TestCases/stale_stack_leak.cc
--
Exit Code: 1

Command Output (stderr):
--
/dev/shm/Clang/3.8.1/GCC-5.4.0-2.26/llvm-3.8.1.src/projects/compiler-rt/test/lsan/TestCases/stale_stack_leak.cc:40:11: error: expected string not found in input
// CHECK: LeakSanitizer: detected memory leaks
          ^
<stdin>:2:1: note: scanning from here
Value after LSan: 0x61a00001f280.
^
<stdin>:2:4: note: possible intended match here
Value after LSan: 0x61a00001f280.
   ^

--

********************
Testing: 0 .. 10.. 20.. 30.. 40.. 50.. 60.. 70.. 80.. 90..
Testing Time: 466.92s
********************
Failing Tests (2):
    AddressSanitizer-x86_64-linux :: TestCases/Linux/nohugepage_test.cc
    LeakSanitizer-AddressSanitizer :: TestCases/stale_stack_leak.cc

  Expected Passes    : 20112
  Expected Failures  : 92
  Unsupported Tests  : 6496
  Unexpected Failures: 2
```

**Comment by boegel** [comment]
OK, I think it makes sense to just disable running those tests by default, easyblock updated in https://github.com/easybuilders/easybuild-easyblocks/pull/1329.

**Comment by boegel** [comment]
@verdurin Please re-test on top of updated `Clang` easyblock from https://github.com/easybuilders/easybuild-easyblocks/pull/1329?

**Comment by verdurin** [comment]
Test report by @verdurin
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
rescomp2 - Linux centos 6.8, Intel(R) Xeon(R) CPU E5-2650 v2 @ 2.60GHz, Python 2.7.11
See https://gist.github.com/ae1fc35d604592ebaa49e78d41de5f7e for a full test report.

**Comment by verdurin** [comment]
@boegel - as you can see, it does build with the sanitizer tests disabled.

**Comment by boegel** [comment]
@verdurin Great, then this is good to go imho?

**Comment by verdurin** [comment]
Going in, thanks @boegel!

**Pull request merged**
