### PR TITLE
enable building ScaLAPACK in parallel with enhanced ScaLAPACK easyblocks

### PR DESCRIPTION
**Pull request by boegel**
requires https://github.com/easybuilders/easybuild-easyblocks/pull/1288

cc @akesandgren

### CODE REVIEW

**Comment by akesandgren** [comment]
LGTM

**Comment by boegel** [comment]
Test report by @boegel
**FAILED**
Build succeeded for 23 out of 24 (24 easyconfigs in this PR)
node2151.delcatty.os - Linux centos linux 7.4.1708, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.7.5
See https://gist.github.com/d250e89c33f9977f40bbb34467aca558 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**FAILED**
Build succeeded for 23 out of 24 (24 easyconfigs in this PR)
node2107.delcatty.os - Linux centos linux 7.4.1708, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.7.5
See https://gist.github.com/b1521d19c3676c69ac97cac132108371 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 24 out of 24 (24 easyconfigs in this PR)
node2038.delcatty.os - Linux centos linux 7.4.1708, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.7.5
See https://gist.github.com/a2c5f41228d048acd7a4da18696bbde0 for a full test report.

**Comment by boegel** [comment]
@easybuilders/easybuild-easyconfigs-maintainers This is good to go now https://github.com/easybuilders/easybuild-easyblocks/pull/1288 is merged.

**Pull request merged**
