### PR TITLE
{bio,lib}[foss/2023a,gfbf/2023a] GROMACS-LS v2016.3, MDStress v20191228

### PR DESCRIPTION
**Pull request by akesandgren**
(created using `eb --new-pr`)

Depends on
- [x] https://github.com/easybuilders/easybuild-easyblocks/pull/3501

### CODE REVIEW

**Comment by akesandgren** [comment]
Test report by @akesandgren
Using easyblocks from PR(s) https://github.com/easybuilders/easybuild-easyblocks/pull/3501
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in total)
b-an02.hpc2n.umu.se - Linux Ubuntu 20.04, x86_64, Intel(R) Xeon(R) CPU E5-2690 v4 @ 2.60GHz, Python 3.8.10
See https://gist.github.com/akesandgren/6dd6ca6c0732d11313f6007fb68db598 for a full test report.

**Comment by Micket** [comment]
@boegelbot please test @ generoso
EB_ARGS="--include-easyblocks-from-pr 3501"

**Comment by akesandgren** [comment]
Test report by @akesandgren
Using easyblocks from PR(s) https://github.com/easybuilders/easybuild-easyblocks/pull/3501
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in total)
b-an02.hpc2n.umu.se - Linux Ubuntu 20.04, x86_64, Intel(R) Xeon(R) CPU E5-2690 v4 @ 2.60GHz, Python 3.8.10
See https://gist.github.com/akesandgren/9bc3a0a6272ef8d00a64e6617a7fee73 for a full test report.

**Review by Micket — APPROVED** [review]
lgtm

**Pull request merged**
