### PR TITLE
{devel}[intel/2018b] Spark v2.4.0

### PR DESCRIPTION
**Pull request by JackPerdue**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by JackPerdue** [comment]
I struggled to figure out how to use a PyPi package.... it used to be so simple....

**Comment by boegel** [comment]
@JackPerdue We've made things a bit more stricter because of problems we ran into when not paying close attention.

You should add this to your easyconfig:

```
exts_default_options = {
    'download_dep_fail': True,
    'use_pip': True,
}
```

The first entry makes sure that no Python packages are being downloaded under the covers, the 2nd specifies to use `pip install` rather than `python setup.py install` (since `pip` is the recommended Python installation tool).

I understand your confusion though, we're (still) missing proper documentation on the best procedure to produce easyconfigs for Python packages... :(

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
node2119.delcatty.os - Linux centos linux 7.6.1810, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.7.5
See https://gist.github.com/eaf6a44a05cc8b6e8f9ece0fd99029e3 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
node3108.skitty.os - Linux centos linux 7.6.1810, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz, Python 2.7.5
See https://gist.github.com/0ac85e962a5116eecb7eb1c5c120daea for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
node2402.golett.os - Linux centos linux 7.6.1810, Intel(R) Xeon(R) CPU E5-2680 v3 @ 2.50GHz, Python 2.7.5
See https://gist.github.com/d23ae3d8fe4ea38a73e2ac17a61ca42e for a full test report.

**Comment by boegel** [comment]
Going in, thanks @JackPerdue!

**Pull request merged**
