### PR TITLE
{lang}[foss/2023a] CVXPY v1.4.2

### PR DESCRIPTION
**Pull request by Micket**
(created using `eb --new-pr`)
- [x] #20149

### CODE REVIEW

**Comment by Micket** [comment]
@boegelbot please test @ generoso

**Comment by Micket** [comment]
Test report by @Micket
**FAILED**
Build succeeded for 1 out of 2 (1 easyconfigs in total)
vera-skylake-build - Linux Rocky Linux 8.9, x86_64, Intel Xeon Processor (Skylake, IBRS, no TSX), Python 3.6.8
See https://gist.github.com/Micket/d90f05170fe1e53ec17591d42c5405ff for a full test report.

**Comment by Micket** [comment]
Test report by @Micket
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
vera-skylake-build - Linux Rocky Linux 8.9, x86_64, Intel Xeon Processor (Skylake, IBRS, no TSX), Python 3.6.8
See https://gist.github.com/Micket/408377fc6b1e5c294db08bcd76841d29 for a full test report.

**Comment by casparvl** [comment]
@boegelbot please test @ generoso

**Comment by casparvl** [comment]
@boegelbot please test @ jsc-zen3

**Comment by casparvl** [comment]
Test report by @casparvl
**FAILED**
Build succeeded for 0 out of 1 (1 easyconfigs in total)
tcn1.local.snellius.surf.nl - Linux RHEL 8.6, x86_64, AMD EPYC 7H12 64-Core Processor, Python 3.6.8
See https://gist.github.com/casparvl/e551084fde272f2d541279d1f7071099 for a full test report.

**Comment by casparvl** [comment]
I'm getting:
```
== 2024-03-19 18:02:10,902 build_log.py:171 ERROR EasyBuild crashed with an error (at easybuild/base/exceptions.py:126 in __init__): `/scratch-nvme/1/casparl/generic/software/Python/3.11.3-GCCcore-12.3.0/bin/python -m pip check` failed:
cvxpy 1.4.2 has requirement osqp>=0.6.2, but you have osqp 0.0.0.

The following Python packages were likely not installed correctly because they show a version of '0.0.0':
osqp
This may be solved by using a *-none-any.whl file as the source instead. See e.g. the SOURCE*_WHL templates.
Otherwise you could check if the package provides a version at all or if e.g. poetry is required (check the source for a pyproject.toml and see PEP517 for details on that). (at easybuild/easyblocks/generic/pythonpackage.py:1076 in sanity_check_step)
```
Any idea?

**Comment by Micket** [comment]
Are you possibly missing a fix for that version 0.0.0 thing with pip? it has been such a reoccuring problem i don't remember when and how it was fixed each time

**Comment by casparvl** [comment]
You mean I probably need to reinstall... something... and didn't do that yet? :D Could be...

**Comment by Micket** [comment]
probably https://github.com/easybuilders/easybuild-easyconfigs/pull/19777

**Comment by casparvl** [comment]
I think you're right. I'll rebuild those and try again :)

**Comment by casparvl** [comment]
@boegelbot please test @ jsc-zen3

**Comment by casparvl** [comment]
> You already built on jsc-zen3 :)

Eh.. It never started there I think, right? I didn't see the report at least, maybe I overlooked :D Waiting for the rebuild on my own system, just to make sure that's it (it almost has to be, but good to be sure). Taking a while though... I'll merge once that is succesful :)

**Comment by casparvl** [comment]
Test report by @casparvl
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
tcn1.local.snellius.surf.nl - Linux RHEL 8.6, x86_64, AMD EPYC 7H12 64-Core Processor, Python 3.6.8
See https://gist.github.com/casparvl/e3eb91dc807edaf3323e05fd59249838 for a full test report.

**Review by casparvl — APPROVED** [review]
Lgtm!

**Comment by casparvl** [comment]
Going in, thanks @Micket!

**Pull request merged**
