### PR TITLE
{ai,lang,vis}[foss/2022a] DeepDRR v1.1.3, PyCUDA v2024.1, PyVista v0.43.8 w/ CUDA 11.7.0

### PR DESCRIPTION
**Pull request by smoors**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by smoors** [comment]
@boegelbot: please test @ generoso

**Comment by smoors** [comment]
@boegelbot please test @ jsc-zen3

**Review by lexming — APPROVED** [review]
LGTM

**Comment by lexming** [comment]
Merging, thanks @smoors !

**Pull request merged**
