### PR TITLE
{bio}[gompi-2019a] Salmon v1.0.0

### PR DESCRIPTION
**Pull request by robqiao**
Salmon-1.0.0

### CODE REVIEW

**Comment by smoors** [comment]
Test report by @smoors
**FAILED**
Build succeeded for 2 out of 3 (3 easyconfigs in this PR)
node375.hydra.os - Linux centos linux 7.6.1810, Intel(R) Xeon(R) Gold 6148 CPU @ 2.40GHz, Python 2.7.5
See https://gist.github.com/28d90ad7e9b2ed826cc24477ad8e97b6 for a full test report.

**Comment by smoors** [comment]
@robqiao here is the error:

== 2019-12-20 18:58:00,387 build_log.py:164 ERROR EasyBuild crashed with an error (at easybuild/base/exceptions.py:124 in __init__): Failed to copy file /tmp/2799137.master01.hydra.brussel.vsc/tmp/vsc10009/build/SAMtools/1.10/GCC-8.2.0-2.31.1/samtools-1.10/sam_header.h to /tmp/vsc10009/ebinstall/9558/software/SAMtools/1.10-GCC-8.2.0-2.31.1/include/bam/sam_header.h: [Errno 2] No such file or directory: '/tmp/2799137.master01.hydra.brussel.vsc/tmp/vsc10009/build/SAMtools/1.10/GCC-8.2.0-2.31.1/samtools-1.10/sam_header.h' (at easybuild/tools/filetools.py:1767 in copy_file)

this probably requires an update of the `samtools.py` easyblock, because `sam_header.h` is no longer present.

**Comment by smoors** [comment]
@robqiao also, why are you submitting easyconfigs twice?
there is also #9557 for SAMtools
and also #9536 for Jellyfish

**Comment by robqiao** [comment]
> @robqiao also, why are you submitting easyconfigs twice?
> there is also #9557 for SAMtools
> and also #9536 for Jellyfish

Thx @smoors for point this out. It seems I forgot to change branch when committing new changes. Do you want me to clean up this branch, but I think when merging to main dev branch it wouldn't matter, see what you think. 

Plus given that the easyblock need to be merged before easyconfig .travis build can pass,  what's the general procedures to submit easyblock, it seems no obvious instructions. Thx

**Comment by boegel** [comment]
@robqiao No worries, we'll get them merged in the order you opened them: first #9536 (`Jellyfish`), then #9557 (`SAMtools`), then this PR for `Salmon`.

We can use `eb --sync-pr-with-develop` in between merges to ensure a clean "diff" in each PR.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
generoso - Linux centos linux 7.6.1810, Intel(R) Xeon(R) CPU E5-2660 v4 @ 2.00GHz, Python 3.6.8
See https://gist.github.com/759ec153495431d83cf9141f4a9d7ac5 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
node3103.skitty.os - Linux centos linux 7.7.1908, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz, Python 3.6.8
See https://gist.github.com/1510894d96dfcb65fd0e0e30589d2b3c for a full test report.

**Comment by boegel** [comment]
Going in, thanks @robqiao!

**Pull request merged**
