### PR TITLE
Add tensorboard profile plugin to TensorFlow 2.3.1

### PR DESCRIPTION
**Pull request by Micket**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by Micket** [comment]
Test report by @Micket
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in total)
alvis-c1 - Linux centos linux 7.9.2009, x86_64, Intel Xeon Processor (Skylake), Python 3.6.8
See https://gist.github.com/6d3aa16ac3205fb69eab7a009f1985ae for a full test report.

**Comment by Micket** [comment]
Test report by @Micket
**FAILED**
Build succeeded for 4 out of 6 (4 easyconfigs in total)
vera-c1 - Linux centos linux 7.9.2009, x86_64, Intel Xeon Processor (Skylake), Python 2.7.5
See https://gist.github.com/ffae7abdda0c68ec1f455d63474f71fb for a full test report.

**Comment by branfosj** [comment]
Test report by @branfosj
**SUCCESS**
Build succeeded for 4 out of 4 (2 easyconfigs in total)
bear-pg0212u17a.bear.cluster - Linux centos linux 8.2.2004, x86_64, Intel(R) Xeon(R) CPU E5-2640 v4 @ 2.40GHz (broadwell), Python 3.6.8
See https://gist.github.com/2a0e27a148d1a2e05a1eedcfff858048 for a full test report.

**Comment by branfosj** [comment]
Test report by @branfosj
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in total)
bear-pg0212u15b.bear.cluster - Linux centos linux 8.2.2004, x86_64, Intel(R) Xeon(R) CPU E5-2640 v4 @ 2.40GHz (broadwell), Python 3.6.8
See https://gist.github.com/c58b56789128f5111e5918f6802ae914 for a full test report.

**Comment by branfosj** [comment]
@boegelbot please test @ generoso
EB_ARGS="--skip"

**Review by branfosj — APPROVED** [review]
> Hm, these seem to be unrelated issues regarding google.protobuf. Perhaps I need to rebuild some stuff (but I don't want to touch this system unnecessarily). So, I would ignore the 2 failures here for the sake of this PR.

Yes, I agree that the failures in the test report look unrelated to the changes here. My test report were fine and the ones from generosa should be along at some point.

**Comment by branfosj** [comment]
Going in, thanks @Micket!

**Pull request merged**
