### PR TITLE
fix LAMMPS 3Mar2020 easyconfigs using intel toolchain on AMD CPUs by patching out hardcoded -xHost

### PR DESCRIPTION
**Pull request by hajgato**

### CODE REVIEW

**Comment by boegel** [comment]
Test report by @boegel
**FAILED**
Build succeeded for 1 out of 2 (2 easyconfigs in total)
node3570.doduo.os - Linux RHEL 8.2, x86_64, AMD EPYC 7552 48-Core Processor (zen2), Python 3.6.8
See https://gist.github.com/9fe4c2e977155154f936e40ea78681ae for a full test report.

**Comment by hajgato** [comment]
@boegel 
```
BlockingIOError: [Errno 11] Resource temporarily unavailable: '/kyukon/home/gent/400/vsc40003/.local/share/virtualenv/seed-app-data/v1.0.1/3.8/image/CopyPipInstall/pip-20.0.2-py2.py3-none-any/pip/_vendor/distlib/w32.exe' -> '/tmp/vsc40003/easybuild/LAMMPS/3Mar2020/intel-2020a-Python-3.8.2-kokkos/easybuild_obj/docenv/lib/python3.8/site-packages/pip/_vendor/distlib/w32.exe'
```

**Comment by hajgato** [comment]
@boegel plus the patch does not work.

**Comment by hajgato** [comment]
@boegel I do not have any ide how could I fix this `BlockingIOError: [Errno 11]`  problem on RHEL8

**Comment by boegel** [comment]
@hajgato My home dir was close to being full, that may be the problem... I'll try again.

**Comment by boegel** [comment]
@boegelbot please test @ generoso

**Comment by hajgato** [comment]
Adding configopts = "-DBUILD_DOC=off " solves the problem. I have the feeling that this problem specifically relates to our system.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in total)
node3407.kirlia.os - Linux centos linux 7.8.2003, x86_64, Intel(R) Xeon(R) Gold 6240 CPU @ 2.60GHz (cascadelake), Python 2.7.5
See https://gist.github.com/b0134cb5b42f8b3d8921866120d781a6 for a full test report.

**Comment by ocaisa** [comment]
[Looks like](https://github.com/lammps/lammps/blob/master/cmake/CMakeLists.txt#L68) there is no need for the patch, you can use the CMake configopt `-DCMAKE_TUNE_DEFAULT=""` should have the same effect

**Comment by boegel** [comment]
@hajgato That `BlockingIOError` is a GPFS bug, for which a workaround is available by patching `Python`, right? Do we have that documented somewhere?

**Comment by hajgato** [comment]
@boegel The workaround is documented in https://github.com/easybuilders/easybuild-easyconfigs/issues/11581

**Comment by boegel** [comment]
@boegelbot please test @ generoso
CORE_CNT=16

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 9 out of 9 (4 easyconfigs in total)
node2605.swalot.os - Linux centos linux 7.9.2009, x86_64, Intel(R) Xeon(R) CPU E5-2660 v3 @ 2.60GHz (haswell), Python 3.6.8
See https://gist.github.com/f45cfd25455bb97d7203e7f71fb291ab for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 8 out of 8 (4 easyconfigs in total)
node3528.doduo.os - Linux RHEL 8.2, x86_64, AMD EPYC 7552 48-Core Processor (zen2), Python 3.6.8
See https://gist.github.com/8c99b8e8e837037d70eb6d2d5ce436d4 for a full test report.

**Review by boegel — APPROVED** [review]
lgtm

**Comment by boegel** [comment]
Going in, thanks @hajgato!

**Pull request merged**
