### PR TITLE
{vis}[foss/2018b] FFmpeg v4.1

### PR DESCRIPTION
**Pull request by boegel**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
node2704.swalot.os - Linux centos linux 7.6.1810, Intel(R) Xeon(R) CPU E5-2660 v3 @ 2.60GHz, Python 2.7.5
See https://gist.github.com/3c4761b3095f6365749496c92f88b739 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
node2052.delcatty.os - Linux centos linux 7.6.1810, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.7.5
See https://gist.github.com/1af51d5b20619b75a73457615f613336 for a full test report.

**Comment by akesandgren** [comment]
Test report by @akesandgren
**FAILED**
Build succeeded for 21 out of 24 (1 easyconfigs in this PR)
janson.hpc2n.umu.se - Linux ubuntu 16.04, Intel(R) Core(TM) i7-5600U CPU @ 2.60GHz, Python 2.7.12
See https://gist.github.com/7eb33c7dfadd84935b88927ff4056530 for a full test report.

**Comment by akesandgren** [comment]
Test report by @akesandgren
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
janson.hpc2n.umu.se - Linux ubuntu 16.04, Intel(R) Core(TM) i7-5600U CPU @ 2.60GHz, Python 2.7.12
See https://gist.github.com/727d78429e713af8e80ab57d1d534f45 for a full test report.

**Comment by akesandgren** [comment]
Going in, thanks @boegel!

**Pull request merged**
