### PR TITLE
{numlib}[intel/2020a] PETSc v3.12.4

### PR DESCRIPTION
**Pull request by MaximeMoge**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by MaximeMoge** [comment]
the dependencies are not merged yet

**Comment by zao** [comment]
Test report by @zao
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
freja - Linux ubuntu 18.04, Intel(R) Core(TM) i7-8700K CPU @ 3.70GHz, Python 2.7.17
See https://gist.github.com/b62573c5a373e8140f28088a605e2741 for a full test report.

**Comment by lexming** [comment]
Test report by @lexming
**FAILED**
Build succeeded for 0 out of 1 (1 easyconfigs in this PR)
login2.cerberus.os - Linux centos linux 7.7.1908, Intel(R) Xeon(R) Gold 6126 CPU @ 2.60GHz, Python 2.7.5
See https://gist.github.com/702978cfcbed1a4bfbe99318292e9310 for a full test report.

**Comment by lexming** [comment]
My test failed due to a broken installation of Hypre. Re-testing again...

**Comment by lexming** [comment]
Test report by @lexming
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
login2.cerberus.os - Linux centos linux 7.7.1908, Intel(R) Xeon(R) Gold 6126 CPU @ 2.60GHz, Python 2.7.5
See https://gist.github.com/212e68f532d8487f4eba0f6ec9d61f8f for a full test report.

**Comment by lexming** [comment]
Going in, thanks @MaximeMoge !

**Pull request merged**
