### PR TITLE
{bio}[fosscuda/2018b] RELION v3.0 (WIP)

### PR DESCRIPTION
**Pull request by akesandgren**
(created using `eb --new-pr`)
Depends on ~~https://github.com/easybuilders/easybuild-easyconfigs/pull/7689~~

### CODE REVIEW

**Comment by akesandgren** [comment]
Test report by @akesandgren
**SUCCESS**
Build succeeded for 2 out of 2 (1 easyconfigs in this PR)
b-an03.hpc2n.umu.se - Linux ubuntu 16.04, Intel(R) Xeon(R) CPU E5-2690 v4 @ 2.60GHz, Python 2.7.12
See https://gist.github.com/7285e507d3d3c57dac302cfc4c6d664e for a full test report.

**Comment by smoors** [comment]
@akesandgren is `tbb` really needed here?
according to the docs, iiuc, it is only needed if you build with CPU acceleration.

**Comment by smoors** [comment]
@akesandgren can the WIP be removed or are there still issues to be resolved first?

**Comment by akesandgren** [comment]
yes, it's only used for CPU altcpu configured builds, I just made a single config to rule them all, sort of.
It's still WIP due to lack of proper batch system support. They made a mess of that...
And due to lack of user testing.

**Comment by akesandgren** [comment]
Obsoleted by #9096, closing

**Pull request closed without merging**
