### PR TITLE
{bio}[foss/2018a] SAMtools v1.9

### PR DESCRIPTION
**Pull request by akesandgren**
(created using `eb --new-pr`)
New version of SAMtools for foss/2018a

### CODE REVIEW

**Comment by akesandgren** [comment]
Test report by @akesandgren
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
b-cn1522.hpc2n.umu.se - Linux ubuntu 16.04, Intel(R) Xeon(R) Gold 6132 CPU @ 2.60GHz, Python 2.7.12
See https://gist.github.com/fca9f1f26a4ee565f7308b70bdfb1920 for a full test report.

**Comment by akesandgren** [comment]
See also https://github.com/easybuilders/easybuild-easyconfigs/pull/6664

**Comment by verdurin** [comment]
@akesandgren Do you want to proceed with this one given the merging of #6664 ?

**Comment by boegel** [comment]
I don't think it makes sense to have both...

**Comment by akesandgren** [comment]
Ahh, that one is on GCC level, not GCCcore... Yeah lets scrap this one.

**Pull request closed without merging**
