### PR TITLE
{bio}[foss/2019b] antiSMASH v5.1.2 w/ Python 3.7.4

### PR DESCRIPTION
**Pull request by boegel**
(created using `eb --new-pr`)
requires #10587 (GlimmerHMM), #10588 (HMMER2)

### CODE REVIEW

**Comment by boegel** [comment]
Test report by @boegel
**FAILED**
Build succeeded for 0 out of 1 (1 easyconfigs in this PR)
generoso - Linux centos linux 7.6.1810, x86_64, Intel(R) Xeon(R) CPU E5-2660 v4 @ 2.00GHz, Python 3.6.8
See https://gist.github.com/6d80d688c9bf78fdef552026d85d8e2d for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
generoso - Linux centos linux 7.6.1810, x86_64, Intel(R) Xeon(R) CPU E5-2660 v4 @ 2.00GHz, Python 3.6.8
See https://gist.github.com/4b0b2641df71c1661265f256f475f6e2 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**FAILED**
Build succeeded for 9 out of 10 (1 easyconfigs in this PR)
node3401.kirlia.os - Linux centos linux 7.7.1908, x86_64, Intel(R) Xeon(R) Gold 6240 CPU @ 2.60GHz (cascadelake), Python 2.7.5
See https://gist.github.com/7c29e3f8aa7e90d29e278fdb0b636e44 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
node3401.kirlia.os - Linux centos linux 7.7.1908, x86_64, Intel(R) Xeon(R) Gold 6240 CPU @ 2.60GHz (cascadelake), Python 2.7.5
See https://gist.github.com/2d3acdd2986c4ebeb71b9be653ef1757 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
node3135.skitty.os - Linux centos linux 7.7.1908, x86_64, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz (skylake_avx512), Python 3.6.8
See https://gist.github.com/f0af550ec30ab69d4fc47e0470977f31 for a full test report.

**Comment by zao** [comment]
Test report by @zao
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
freja - Linux Ubuntu 20.04, x86_64, Intel(R) Core(TM) i7-8700K CPU @ 3.70GHz, Python 3.8.2
See https://gist.github.com/bce16ae615142b395038c13b693ab94b for a full test report.

**Comment by verdurin** [comment]
Test report by @verdurin
**FAILED**
Build succeeded for 7 out of 9 (1 easyconfigs in this PR)
easybuild.novalocal - Linux centos linux 7.8.2003, Intel Xeon Processor (Skylake, IBRS), Python 2.7.5
See https://gist.github.com/663821c2d96c58cb336c436c286ac419 for a full test report.

**Comment by verdurin** [comment]
Hmm, mass of errors at linking stage for `MUSCLE`:
```
/eb/maint/software/binutils/2.32-GCCcore-8.3.0/bin/ld.gold: error: cannot find -lc
/eb/maint/software/binutils/2.32-GCCcore-8.3.0/bin/ld.gold: error: cannot find -lm
/lib/../lib64/crt1.o(.text+0x12): error: undefined reference to '__libc_csu_fini'
/lib/../lib64/crt1.o(.text+0x19): error: undefined reference to '__libc_csu_init'
/lib/../lib64/crt1.o(.text+0x25): error: undefined reference to '__libc_start_main'
aln.o:aln.cpp:function MSA::ToAlnFile(TextFile&) const: error: undefined reference to 'strchr'
aln.o:aln.cpp:function MSA::ToAlnFile(TextFile&) const: error: undefined reference to 'strlen'
aln.o:aln.cpp:function MSA::ToAlnFile(TextFile&) const: error: undefined reference to 'strchr'
aln.o:aln.cpp:function MSA::ToAlnFile(TextFile&) const: error: undefined reference to 'toupper'
aln.o:aln.cpp:function MSA::ToAlnFile(TextFile&) const: error: undefined reference to 'strlen'
alpha.o:alpha.cpp:function SetAlpha(ALPHA): error: undefined reference to 'memset'
alpha.o:alpha.cpp:function SetAlpha(ALPHA): error: undefined reference to 'memset'
alpha.o:alpha.cpp:function SetAlpha(ALPHA): error: undefined reference to 'toupper'
alpha.o:alpha.cpp:function SetAlpha(ALPHA): error: undefined reference to 'tolower'
alpha.o:alpha.cpp:function SetAlpha(ALPHA): error: undefined reference to 'toupper'
alpha.o:alpha.cpp:function SetAlpha(ALPHA): error: undefined reference to 'tolower'
alpha.o:alpha.cpp:function SetAlpha(ALPHA): error: undefined reference to 'toupper'
alpha.o:alpha.cpp:function SetAlpha(ALPHA): error: undefined reference to 'tolower'
alpha.o:alpha.cpp:function SetAlpha(ALPHA): error: undefined reference to 'tolower'
alpha.o:alpha.cpp:function IsNucleo(char): error: undefined reference to 'strchr'
alpha.o:alpha.cpp:function IsDNA(char): error: undefined reference to 'strchr'
clust.o:clust.cpp:function Clust::JoinNodes(unsigned int, unsigned int, float, float, unsigned int): error: undefined reference to 'memcpy'
clust.o:clust.cpp:function Clust::JoinNodes(unsigned int, unsigned int, float, float, unsigned int): error: undefined reference to 'memcpy'
clwwt.o:clwwt.cpp:function CalcClustalWWeights(Tree const&, float*): error: undefined reference to 'memset'
diaglist.o:diaglist.cpp:function DiagList::DeleteIncompatible(): error: undefined reference to 'memcpy'
distfunc.o:distfunc.cpp:function DistFunc::~DistFunc(): error: undefined reference to 'free'
distfunc.o:distfunc.cpp:function DistFunc::VectorIndex(unsigned int, unsigned int) const [clone .part.0]: error: undefined reference to '__assert_fail'
distfunc.o:distfunc.cpp:function DistFunc::SetCount(unsigned int): error: undefined reference to 'memset'
distfunc.o:distfunc.cpp:function DistFunc::SetName(unsigned int, char const*): error: undefined reference to '__assert_fail'
distfunc.o:distfunc.cpp:function DistFunc::SetId(unsigned int, unsigned int): error: undefined reference to '__assert_fail'
distfunc.o:distfunc.cpp:function DistFunc::GetName(unsigned int) const: error: undefined reference to '__assert_fail'
domuscle.o:domuscle.cpp:function DoMuscle(): error: undefined reference to 'getenv'
domuscle.o:domuscle.cpp:function DoMuscle(): error: undefined reference to 'strlen'
domuscle.o:domuscle.cpp:function DoMuscle(): error: undefined reference to 'strlen'
domuscle.o:domuscle.cpp:function DoMuscle(): error: undefined reference to 'sprintf'
domuscle.o:domuscle.cpp:function DoMuscle(): error: undefined reference to 'stderr'
domuscle.o:domuscle.cpp:function DoMuscle(): error: undefined reference to 'fputs'
domuscle.o:domuscle.cpp:function DoMuscle(): error: undefined reference to 'free'
domuscle.o:domuscle.cpp:function DoMuscle(): error: undefined reference to 'free'
```
etc.

Could be a local problem.

**Comment by Micket** [comment]
@verdurin My first guess is that your system is missing glibc-static libs. I'll upload my own test build.

**Comment by Micket** [comment]
Test report by @Micket
**SUCCESS**
Build succeeded for 5 out of 5 (1 easyconfigs in this PR)
hebbe-c1 - Linux centos linux 7.7.1908, Intel Core Processor (Haswell, no TSX), Python 2.7.5
See https://gist.github.com/e1e8999746ee9bc395690da3833d5bbb for a full test report.

**Comment by verdurin** [comment]
@Micket yes, no `glibc-static-*` packages installed.

**Comment by Micket** [comment]
Going in, thanks @boegel!

**Pull request merged**
