### PR TITLE
move make 4.3 easyconfigs to GCCcore toolchain

### PR DESCRIPTION
**Pull request by boegel**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by boegel** [comment]
@boegelbot please test @ generoso

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in total)
node3103.skitty.os - Linux centos linux 7.9.2009, x86_64, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz, Python 3.6.8
See https://gist.github.com/9f9a95390c6fa6d18abc8a533c5c90ea for a full test report.

**Comment by branfosj** [comment]
@boegel can you delete the GCC versions?

**Comment by boegel** [comment]
> @boegel can you delete the GCC versions?

Ugh, overlooked that... Nice catch!

**Review by branfosj — APPROVED** [review]
lgtm

**Comment by branfosj** [comment]
Test report by @branfosj
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in total)
bear-pg0211u03a.bear.cluster - Linux centos linux 7.8.2003, x86_64, Intel(R) Xeon(R) Gold 6248 CPU @ 2.50GHz (cascadelake), Python 3.6.8
See https://gist.github.com/0542ae1ceff5a7817c331b91bde1c31e for a full test report.

**Pull request merged**
