### PR TITLE
{lib}[foss/2022a] TensorFlow v2.9.1 w/ Python 3.10.4

### PR DESCRIPTION
**Pull request by Flamefire**
(created using `eb --new-pr`)

Based on #16008 by @alinelena  and #16620 by @VRehnberg 

- [x] Requires new Easyblock https://github.com/easybuilders/easybuild-easyblocks/pull/2854

Note that there will be
> WARNING: 1 TensorFlow dependencies have not been resolved by EasyBuild. Check the log for details.

This is due to Abseil being a possible `$TF_SYSTEM_LIBS` since 2.9 but it looks like it got broken between when that PR was opened and 2.9 released: https://github.com/tensorflow/tensorflow/pull/53765#issuecomment-1380204771

Might be worth resolving in the EasyBlock

### CODE REVIEW

**Comment by jfgrimm** [comment]
Test report by @jfgrimm
Using easyblocks from PR(s) https://github.com/easybuilders/easybuild-easyblocks/pull/2854
**FAILED**
Build succeeded for 8 out of 10 (2 easyconfigs in total)
himem04.pri.viking.alces.network - Linux CentOS Linux 7.9.2009, x86_64, Intel(R) Xeon(R) Gold 6230 CPU @ 2.10GHz (cascadelake), Python 3.6.8
See https://gist.github.com/c33aaf092e9972d5516ecaa5d2536ffe for a full test report.

**Comment by Flamefire** [comment]
Test report by @Flamefire
Using easyblocks from PR(s) https://github.com/easybuilders/easybuild-easyblocks/pull/2854
**FAILED**
Build succeeded for 1 out of 2 (2 easyconfigs in total)
taurusi8021 - Linux CentOS Linux 7.9.2009, x86_64, AMD EPYC 7352 24-Core Processor (zen2), 8 x NVIDIA NVIDIA A100-SXM4-40GB, 470.57.02, Python 2.7.5
See https://gist.github.com/432bc6438ed3b41437bb95344a4d1a77 for a full test report.

**Comment by Flamefire** [comment]
@jfgrimm I'm a bit surprised of this failure:

```
NodeFileWriterTest.test_simple
...
/python/framework/node_file_writer_test.py", line 142, in test_simple
    self.assertEqual(node_def1.op, 'MatMul')
AssertionError: 
- _MklMatMul
? ----
+ MatMul
```

Also in the source of the failing `testGetMemoryInfoCPU` I see a skip if MKL is enabled (but isn't triggered).

Are you using any modifications to the toolchain or so which pulls in MKL? Or have `mkl-dnn` somewhere loaded? Maybe attach the full log.

**Comment by jfgrimm** [comment]
@Flamefire my site doesn't modify toolchains, and I really shouldn't have any MKL stuff loaded
[TensorFlow-2.9.1-20230112-log.tar.gz](https://github.com/easybuilders/easybuild-easyconfigs/files/10410789/TensorFlow-2.9.1-20230112-log.tar.gz)

**Comment by Flamefire** [comment]
Test report by @Flamefire
Using easyblocks from PR(s) https://github.com/easybuilders/easybuild-easyblocks/pull/2854
**FAILED**
Build succeeded for 0 out of 2 (2 easyconfigs in total)
taurusml5 - Linux RHEL 7.6, POWER, 8335-GTX (power9le), 6 x NVIDIA Tesla V100-SXM2-32GB, 440.64.00, Python 2.7.5
See https://gist.github.com/df4ea1530feb3a0b23cf87e1148da4ad for a full test report.

**Comment by Flamefire** [comment]
Test report by @Flamefire
Using easyblocks from PR(s) https://github.com/easybuilders/easybuild-easyblocks/pull/2854
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in total)
taurusi8019 - Linux CentOS Linux 7.9.2009, x86_64, AMD EPYC 7352 24-Core Processor (zen2), 8 x NVIDIA NVIDIA A100-SXM4-40GB, 470.57.02, Python 2.7.5
See https://gist.github.com/a80859d5c82a34691118b7cda69da3d3 for a full test report.

**Comment by Flamefire** [comment]
Test report by @Flamefire
Using easyblocks from PR(s) https://github.com/easybuilders/easybuild-easyblocks/pull/2854
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in total)
taurusi8021 - Linux CentOS Linux 7.9.2009, x86_64, AMD EPYC 7352 24-Core Processor (zen2), 8 x NVIDIA NVIDIA A100-SXM4-40GB, 470.57.02, Python 2.7.5
See https://gist.github.com/5454c70c2d5d7d4422a73c8e2fe1dac4 for a full test report.

**Comment by Flamefire** [comment]
Test report by @Flamefire
Using easyblocks from PR(s) https://github.com/easybuilders/easybuild-easyblocks/pull/2854
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in total)
taurusml30 - Linux RHEL 7.6, POWER, 8335-GTX (power9le), 6 x NVIDIA Tesla V100-SXM2-32GB, 440.64.00, Python 2.7.5
See https://gist.github.com/e13895b3515f85c08ef1bdfc9dbe277e for a full test report.

**Comment by Flamefire** [comment]
Test report by @Flamefire
Using easyblocks from PR(s) https://github.com/easybuilders/easybuild-easyblocks/pull/2854
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in total)
taurusa12 - Linux CentOS Linux 7.7.1908, x86_64, Intel(R) Xeon(R) CPU E5-2603 v4 @ 1.70GHz (broadwell), 3 x NVIDIA GeForce GTX 1080 Ti, 460.32.03, Python 2.7.5
See https://gist.github.com/4010143d07d606a185997ae46c937929 for a full test report.

**Comment by VRehnberg** [comment]
> I'm a bit surprised of this failure:
> 
> ```
> NodeFileWriterTest.test_simple
> ...
> /python/framework/node_file_writer_test.py", line 142, in test_simple
>     self.assertEqual(node_def1.op, 'MatMul')
> AssertionError: 
> - _MklMatMul
> ? ----
> + MatMul
> ```
> 
> Also in the source of the failing `testGetMemoryInfoCPU` I see a skip if MKL is enabled (but isn't triggered).
> 
> Are you using any modifications to the toolchain or so which pulls in MKL? Or have `mkl-dnn` somewhere loaded? Maybe attach the full log.

I'd just like to second that I'm seeing this same Failure on our system as well.

**Comment by Flamefire** [comment]
Test report by @Flamefire
Using easyblocks from PR(s) https://github.com/easybuilders/easybuild-easyblocks/pull/2854
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in total)
taurusa12 - Linux CentOS Linux 7.7.1908, x86_64, Intel(R) Xeon(R) CPU E5-2603 v4 @ 1.70GHz (broadwell), 3 x NVIDIA GeForce GTX 1080 Ti, 460.32.03, Python 2.7.5
See https://gist.github.com/d5c1a8c8c0eee0548ab1c8eb626d771e for a full test report.

**Comment by SebastianAchilles** [comment]
Test report by @sebastianachilles
Using easyblocks from PR(s) https://github.com/easybuilders/easybuild-easyblocks/pull/2854
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in total)
skl-rockylinux-87 - Linux Rocky Linux 8.7, x86_64, Intel(R) Core(TM) i7-10700 CPU @ 2.90GHz (skylake), 1 x NVIDIA NVIDIA RTX A4000, 525.60.13, Python 3.6.8
See https://gist.github.com/6044f743a8e88aea0e2a9698d7707385 for a full test report.

**Comment by Flamefire** [comment]
> I'd just like to second that I'm seeing this same Failure on our system as well.

I worked with @jfgrimm a bit trying to catch a log of the failing tests but it suddenly succeeded (i.e. no error anymore, all tests green).

So if anyone (@VRehnberg ?)  is seeing those MKL-related failures consistently, maybe he can run a modified version with 
[TF2.9_logging.patch.txt](https://github.com/easybuilders/easybuild-easyconfigs/files/10557063/TF2.9_logging.patch.txt) and send me the logs to have a look at.

I also opened a PR for [TF 2.10.1](https://github.com/easybuilders/easybuild-easyconfigs/pull/17168) and [TF 2.11.0](https://github.com/easybuilders/easybuild-easyconfigs/pull/17241)

The upstream issue I reported is https://github.com/tensorflow/tensorflow/issues/59252

**Comment by jfgrimm** [comment]
yeah no idea what changed, but my builds (both CPU and CUDA) are happy now :shrug:

**Comment by VRehnberg** [comment]
> So if anyone (@VRehnberg ?) is seeing those MKL-related failures consistently, maybe he can run a modified version with
[TF2.9_logging.patch.txt](https://github.com/easybuilders/easybuild-easyconfigs/files/10557063/TF2.9_logging.patch.txt) and send me the logs to have a look at.

I'm rerunning the builds now. Should be finished tomorrow and will try to remember to upload them then.

**Comment by VRehnberg** [comment]
Still getting MKL test failure: 
[easybuild-TensorFlow-2.9.1-20230206.161046.aaEEN.log.gz](https://github.com/easybuilders/easybuild-easyconfigs/files/10674167/easybuild-TensorFlow-2.9.1-20230206.161046.aaEEN.log.gz)

Tried to include the logging patch with `--amend`, not sure if it worked.

**Comment by Flamefire** [comment]
@VRehnberg 
> Tried to include the logging patch with `--amend`, not sure if it worked.

Nope that didn't work. I guess yet another instance of https://github.com/easybuilders/easybuild-framework/issues/3358 / https://github.com/easybuilders/easybuild-framework/issues/2222

Best is to download the files and modify it directly. E.g. via `eb --from-pr 17092 --copy-ec /tmp/foo --stop` (places all files from the PR into `/tmp/foo`)   
Not much hope I can figure out why it doesn't work for you though. But worth a shot.

**Comment by VRehnberg** [comment]
Second attempt at including patch went better, thanks for the tip for easily fetching the relevant files.
[easybuild-TensorFlow-2.9.1-20230207.161810.rDwiP.log.gz](https://github.com/easybuilders/easybuild-easyconfigs/files/10684560/easybuild-TensorFlow-2.9.1-20230207.161810.rDwiP.log.gz)

**Comment by Flamefire** [comment]
@VRehnberg I think I found the issue: They were inconsistent checking for MKL and some place was using a runtime check for CPU features while another place was only checking for defines. This was fixed in TF 2.11 by https://github.com/tensorflow/tensorflow/commit/5ec3d2e626589540bcfbeb7dac40255034e587df

I included the patch in the new commit, so that version should now build for you. Can you verify?

**Comment by VRehnberg** [comment]
A test report will hopefully come in a few hours with the results.

**Comment by VRehnberg** [comment]
Test report by @VRehnberg
**FAILED**
Build succeeded for 1 out of 2 (2 easyconfigs in total)
alvis-c1 - Linux Rocky Linux 8.6, x86_64, Intel Xeon Processor (Skylake), Python 3.6.8
See https://gist.github.com/VRehnberg/274b5ff0ebe9db379fb9dc8ac8465cb8 for a full test report.

**Comment by Flamefire** [comment]
@VRehnberg 
> `fatal error: google/protobuf/port_def.inc: No such file or directory`

That again? Are you using the latest easyblock?

**Comment by Flamefire** [comment]
It looks like some other ECs were merged already using flatbuffers 2.0.6 while TF 2.9 barely worked with 2.0.0. However I was able to backport the changes so it should work now.

**Comment by Flamefire** [comment]
Test report by @Flamefire
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in total)
taurusi7005 - Linux CentOS Linux 7.7.1908, x86_64, AMD EPYC 7702 64-Core Processor (zen2), Python 2.7.5
See https://gist.github.com/Flamefire/45148c23fc982e579e8d154a16f55d52 for a full test report.

**Comment by Flamefire** [comment]
Test report by @Flamefire
**FAILED**
Build succeeded for 0 out of 2 (2 easyconfigs in total)
taurusml5 - Linux RHEL 7.6, POWER, 8335-GTX (power9le), 6 x NVIDIA Tesla V100-SXM2-32GB, 440.64.00, Python 2.7.5
See https://gist.github.com/Flamefire/6c4789f5ba5fab73e4ec23e5adfa400d for a full test report.

**Comment by VRehnberg** [comment]
I'm still seeing the MKL failure on this one. Though, TensorFlow-2.11.0 I don't think had this problem. At least I've installed the CUDA versions on our systems since some time ago.

Log: 
[easybuild-TensorFlow-2.9.1-20230522.170143.PAJqr.log.gz](https://github.com/easybuilders/easybuild-easyconfigs/files/11566282/easybuild-TensorFlow-2.9.1-20230522.170143.PAJqr.log.gz)

**Comment by Flamefire** [comment]
@VRehnberg Looks like this PR wasn't merged yet and your log file looks like you didn't build from this PR so the required patch for the MKL failure isn't included.

TF 2.11 already includes the patch (upstream) but here my backport-patch is required

@boegel Can this be merged?

**Comment by SebastianAchilles** [comment]
Test report by @sebastianachilles
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in total)
skl-rockylinux-88 - Linux Rocky Linux 8.8, x86_64, Intel(R) Core(TM) i7-10700 CPU @ 2.90GHz (skylake), 1 x NVIDIA NVIDIA RTX A4000, 530.30.02, Python 3.6.8
See https://gist.github.com/SebastianAchilles/11e00f03f70b02af5a0707d2b2a499ee for a full test report.

**Review by SebastianAchilles — APPROVED** [review]
lgtm

**Comment by SebastianAchilles** [comment]
Going in, thanks @Flamefire!

**Comment by SebastianAchilles** [comment]
Going in, thanks @Flamefire!

**Pull request merged**
