### PR TITLE
{lang}[GCCcore/12.2.0] Rust v1.65.0

### PR DESCRIPTION
**Pull request by boegel**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by boegel** [comment]
@boegelbot please test @ generoso
CORE_CNT=16

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
node3106.skitty.os - Linux RHEL 8.4, x86_64, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz (skylake_avx512), Python 3.6.8
See https://gist.github.com/6704de291254aefa803646c012955643 for a full test report.

**Comment by boegel** [comment]
@boegelbot please test @ generoso
EB_ARGS="--sanity-check-only"

**Comment by branfosj** [comment]
From the generoso build:
> Time info
>
>    start: Sun, 13 Nov 2022 08:40:15 +0000 (UTC)
>    end: Sun, 13 Nov 2022 08:40:28 +0000 (UTC)

That is a really quick build for Rust?!

**Comment by boegel** [comment]
> From the generoso build:
> 
> > Time info
> > start: Sun, 13 Nov 2022 08:40:15 +0000 (UTC)
> > end: Sun, 13 Nov 2022 08:40:28 +0000 (UTC)
> 
> ~That is a really quick build for Rust?!~
> 
> Oh, it was a `--sanity-check-only` build as the earlier report was missing.

Yes, the original build worked fine, but the test report didn't come back (cfr. https://github.com/easybuilders/easybuild-framework/issues/3934)

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
fair-mastodon-c6g-2xlarge-0001 - Linux Rocky Linux 8.5, AArch64, ARM UNKNOWN (graviton2), Python 3.6.8
See https://gist.github.com/bf54f31b0a2df8f5465991380f32d53f for a full test report.

**Comment by branfosj** [comment]
Test report by @branfosj
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
bear-pg0105u36b.bear.cluster - Linux RHEL 8.7, x86_64, Intel(R) Xeon(R) Platinum 8360Y CPU @ 2.40GHz (icelake), Python 3.6.8
See https://gist.github.com/54410b098fe2338210c680053144c216 for a full test report.

**Review by branfosj — APPROVED** [review]

**Comment by branfosj** [comment]
Test report by @branfosj
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
bear-pg0206u10a.bear.cluster - Linux Ubuntu 20.04.2 LTS (Focal Fossa), x86_64, Intel(R) Xeon(R) Gold 6248 CPU @ 2.50GHz (cascadelake), Python 3.8.5
See https://gist.github.com/2ebc4d38419b6a252203675cb6346b28 for a full test report.

**Comment by branfosj** [comment]
Going in, thanks @boegel!

**Comment by branfosj** [comment]
@boegelbot please test @ jsc-zen2
CORE_CNT=16

**Comment by SebastianAchilles** [comment]
@boegelbot please test @ jsc-zen2
CORE_CNT=16

**Pull request merged**
