### PR TITLE
{tools}[intel/2018a] IPython v5.7.0 w/ Python 2.7.14

### PR DESCRIPTION
**Pull request by boegel**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by boegel** [comment]
This PR takes a different approach compared to the one contributed by @smoors in #6415, and I'm not sure which approach is better...

The differences are, in short:

* no `PyZMQ` dependency (only `ZeroMQ`); `pyzmq` is installed as an extension instead
  * I guess the question here is, is it useful to have `PyZMQ` stand-alone?
* extra `matplotlib` dependency
* `exts_filter` is set (only required to make `--skip` works in case extra Python packages are added later to this `Bundle`)
* extra extensions (which are apparently not be strictly required): `parso`, `jedi`, `futures`, `backcall`
* missing extensions: `ipywidgets`, `widgetsnbextension`, `backports.shutil_get_terminal_size`, `certifi`
* different order of extensions (doesn't matter much, but makes comparison difficult)
* newer versions of extensions left & right (e.g. for `notebook`)
* `configparser-3.5.0_no-backports-namespace.patch` is not used (no longer needed)?
  * or maybe that's because `backports.shutil_get_terminal_size` is not used...
* not using `.whl` for `prompt-toolkit`, no longer needed?
* only run `iptest` in sanity check (`iptest2` is the exact same time, so no need to run it twice)

@smoors Thoughts on this? I'm up for doing the effort to align these easyconfigs, which would be mostly adding the missing extensions to this PR and then open a separate PR to sync up the currently merged `IPython-5.7.0-foss-2018a-Python-2.7.14.eb`...

**Comment by boegel** [comment]
@smoors Done, see additional commit here (7874943) + PR #6801 that tweaks your easyconfig

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
node2689.swalot.os - Linux centos linux 7.4.1708, Intel(R) Xeon(R) CPU E5-2660 v3 @ 2.60GHz, Python 2.7.5
See https://gist.github.com/9224dad5d3179a33949d009297b3aee5 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
node2104.delcatty.os - Linux centos linux 7.5.1804, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.7.5
See https://gist.github.com/bed6c6539a5a618862215af683a704c1 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
node3147.skitty.os - Linux centos linux 7.4.1708, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz, Python 2.7.5
See https://gist.github.com/fdb73a135ca8fa2bd4270f924750b83f for a full test report.

**Comment by migueldiascosta** [comment]
Test report by @migueldiascosta
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
grc-cluster1 - Linux centos 6.9, Intel(R) Xeon(R) CPU E5-2640 0 @ 2.50GHz, Python 2.7.14
See https://gist.github.com/6e7e2dcf35e0a092da91cff431ccfe90 for a full test report.

**Pull request merged**
