### PR TITLE
Use PMIx 4.2.4 in 2023a toolchain

### PR DESCRIPTION
**Pull request by bartoldeman**

### CODE REVIEW

**Comment by bartoldeman** [comment]
@boegelbot please test @ generoso

**Comment by bartoldeman** [comment]
Test report by @bartoldeman
**FAILED**
Build succeeded for 1 out of 2 (2 easyconfigs in total)
build-node.computecanada.ca - Linux CentOS Linux 7.9.2009, x86_64, Intel Xeon Processor (Skylake, IBRS), Python 3.7.7
See https://gist.github.com/bartoldeman/191c61c54cfe27f2e9095fd5c11951ca for a full test report.

**Comment by bartoldeman** [comment]
Test report by @bartoldeman
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in total)
build-node2.computecanada.ca - Linux CentOS Linux 7.9.2009, x86_64, Intel Xeon Processor (Skylake, IBRS), Python 3.7.7
See https://gist.github.com/bartoldeman/5b6983ef09d493e4a3b570df68f40a11 for a full test report.

**Comment by Micket** [comment]
@boegelbot please test @ jsc-zen2

**Review by Micket — APPROVED** [review]
lgtm

**Comment by Micket** [comment]
Test report by @Micket
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in total)
vera-c1 - Linux Rocky Linux 8.7, x86_64, Intel Xeon Processor (Skylake), Python 3.6.8
See https://gist.github.com/Micket/a5a49f1cd5c9de110b0ba25f8c0e9bb5 for a full test report.

**Comment by Micket** [comment]
Going in, thanks @bartoldeman!

**Pull request merged**
