### PR TITLE
fix installation of Python bindings for Arrow 0.17.1 by adding `--no-build-isolation` to `pip install` command

### PR DESCRIPTION
**Pull request by boegel**
(created using `eb --new-pr`)

cfr. https://github.com/easybuilders/easybuild-easyconfigs/issues/18327 + https://github.com/easybuilders/easybuild-easyconfigs/pull/18348

### CODE REVIEW

**Comment by boegel** [comment]
@boegelbot please test @ generoso

**Comment by casparvl** [comment]
@boegelbot please test @ jsc-zen2

**Comment by boegel** [comment]
@casparvl `jsc-zen2` is missing some old toolchains, which explains the failing test report, I don't think it's worth the effort to get those toolchains in place - the test report from `generoso` is sufficient in this case imho

**Review by casparvl — APPROVED** [review]
Lgtm!

**Comment by casparvl** [comment]
Going in, thanks @boegel!

**Pull request merged**
