### PR TITLE
git: include autotools as build dep

### PR DESCRIPTION
**Pull request by smoors**

### CODE REVIEW

**Comment by smoors** [comment]
@wpoely86  review?

**Comment by boegel** [comment]
@smoors Looks good, I made this consistent across recent `git` versions via https://github.com/smoors/easybuild-easyconfigs/pull/2 . That includes a sync with current `develop`, so it's impossible to review, but it basically boils down to the last commit 42b432c

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 5 out of 5 (4 easyconfigs in this PR)
node2316.phanpy.os - Linux centos linux 7.4.1708, Intel(R) Xeon(R) CPU E5-2680 v3 @ 2.50GHz, Python 2.7.5
See https://gist.github.com/32f6f15b7bff4eda2ca4ec2fbb0ef38d for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 6 out of 6 (4 easyconfigs in this PR)
node2111.delcatty.os - Linux centos linux 7.4.1708, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.7.5
See https://gist.github.com/05927bf58a810b9de63f2b24375086c5 for a full test report.

**Comment by boegel** [comment]
Going in, thanks @smoors!

**Pull request merged**
