### PR TITLE
help2man depends on Perl, use EB built Perl.

### PR DESCRIPTION
**Pull request by akesandgren**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by akesandgren** [comment]
@boegelbot Please test @ generoso

**Comment by Micket** [comment]
I would suspect this is leading to circular dependencies, via the GCCcore flex'es

**Comment by akesandgren** [comment]
Yeah, you're right... bummer... closing this for now...

**Comment by Micket** [comment]
I'm perfectly fine with dropping help2man from all flex-versions

**Pull request closed without merging**
