### PR TITLE
{chem}Dalton-2020.0-foss-2020b

### PR DESCRIPTION
**Pull request by LHurst-JM**
Bump of Dalton from 2016 to 2020.0 and build for foss-2020b (only other version in easybuild is for intel-2017b).

Dalton's new (python) configure command seems to fix the issues that needed a lot of patches in 2016.

N.B. This eb takes between 3 and 4.5 hours to build on my cluster (on each of 44-core Skylake, 60-core Zen and 120-core Zen2 nodes).  Most of that time is spent running the test suite.  One test fails on Zen2 due to upstream bug - https://gitlab.com/dalton/dalton/-/issues/183

### CODE REVIEW

**Comment by verdurin** [comment]
@boegelbot please test @ generoso

**Comment by LHurst-JM** [comment]
Checksum failed on the source.  That's definitely the checksum for the source that was used in my testing:
```
$ sha256sum /mnt/devtest-apps/easybuild/2020b/sources/d/Dalton/Dalton-2020.0.tar.gz 
a939dfbf869ef90ea064fa3d00cc1937dd145438947ecf5556f964b38299b34a  /mnt/devtest-apps/easybuild/2020b/sources/d/Dalton/Dalton-2020.0.tar.gz
```

Upstream have not changed the commit the tag points to:
```
 Dalton2020.0 protected
 66052b3a · Merge branch 'bump-version' into 'release/2020' · 10 months ago
 Release Dalton2020.0
```

So I'm not sure why the checksum is different.  I'll delete and re-download the source with --fetch...

**Comment by LHurst-JM** [comment]
Somehow the source checksum has changed upstream since I uploaded the easyconfig.  The tag still points to the same commit, so I really don't understand why?:

```
$ sha256sum /mnt/devtest-apps/easybuild/2020b/sources/d/Dalton/Dalton-2020.0.tar.gz 
5f37133fe9e791351a6578edc62b56f11cd9512344e9d30401cd9d2cac91c848  /mnt/devtest-apps/easybuild/2020b/sources/d/Dalton/Dalton-2020.0.tar.gz
```

**Comment by verdurin** [comment]
Is there any reason not to use one of the upstream tarballs instead, e.g. https://gitlab.com/dalton/dalton/-/archive/Dalton2020.0/dalton-Dalton2020.0.tar.bz2 ?

**Comment by LHurst-JM** [comment]
> Is there any reason not to use one of the upstream tarballs instead, e.g. https://gitlab.com/dalton/dalton/-/archive/Dalton2020.0/dalton-Dalton2020.0.tar.bz2 ?

Only that I did not know they existed ;)

Upstream's website's download link takes you to the 'release/2020' branch HEAD, which is under active development (and therefore unsutable to use as the source).  The tag seems stable and this is exactly how Dalton-2016-intel-2017b-i8.eb, which is the only version currently in EB, fetches it.  I'm still very confused by the tag, which allegedly hasn't changed in 10 months, suddenly resulting in a different checksum for the clones source.

Happy to try the one of those archive links instead.

**Comment by LHurst-JM** [comment]
...so that results in a file with yet another checksum:

```
$ wget https://gitlab.com/dalton/dalton/-/archive/Dalton2020.0/dalton-Dalton2020.0.tar.gz
$ sha256sum dalton-Dalton2020.0.tar.gz 
6b8365874af6c1545db98f6deb0decce97f6a689995b1cc2a57fea4efd399f00  dalton-Dalton2020.0.tar.gz
```

🤦

**Comment by akesandgren** [comment]
Yes, that would be preferable, splitting the submodules out that is, but I haven't had time to look at that...

Also look at https://github.com/easybuilders/easybuild-easyconfigs/pull/14154 and https://github.com/easybuilders/easybuild-easyconfigs/pull/14158
That is how I did things to make it work with tests.
Note that all the patches are necessary, but for pre-2021a toolchains, the flexiblas patch is not needed.

I'm currently running that one with tests on broadwell and zen2

**Comment by akesandgren** [comment]
I get the same error on my zen2 system that you saw with my foss-2021a build.

**Comment by boegel** [comment]
closing this since `foss/2020b` is deprecated, see https://docs.easybuild.io/policies/toolchains

see also:
* #18010

**Pull request closed without merging**
