### PR TITLE
Fix URL for util-macros in X11-20190311

### PR DESCRIPTION
**Pull request by Flamefire**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by smoors** [comment]
Test report by @smoors
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
node377.hydra.os - Linux centos linux 7.6.1810, Intel(R) Xeon(R) Gold 6148 CPU @ 2.40GHz, Python 2.7.5
See https://gist.github.com/09db9ba2f624f80a366a49b0ff83423a for a full test report.

**Comment by Flamefire** [comment]
I'm actually wondering what the correct way to install this is. There is also https://github.com/easybuilders/easybuild-easyconfigs/pull/9477 and its ECs. This should be unified first.

**Comment by Flamefire** [comment]
I created an alternate PR #9546 which removes the package and adds a dependency to the xorg-macros EC. With #9477 that will/should work

**Comment by boegel** [comment]
closing this in favor of #9546...

**Pull request closed without merging**
