### PR TITLE
{phys}[foss/2021a] BAGEL v1.2.2

### PR DESCRIPTION
**Pull request by TopRichard**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by casparvl** [comment]
@boegelbot please test @ generoso

**Comment by casparvl** [comment]
@boegelbot please test @ jsc-zen2

**Comment by casparvl** [comment]
Test report by @casparvl
**FAILED**
Build succeeded for 1 out of 3 (1 easyconfigs in total)
tcn30.local.snellius.surf.nl - Linux RHEL 8.6, x86_64, AMD EPYC 7H12 64-Core Processor, Python 3.6.8
See https://gist.github.com/casparvl/cac682fc7c4b89e0f6630a53302b2944 for a full test report.

**Comment by casparvl** [comment]
@boegelbot please test @ generoso

**Comment by boegel** [comment]
@boegelbot please test @ generoso
EB_ARGS="--sanity-check-only"

**Comment by boegel** [comment]
Test report on `generoso` actually worked, but failed to get posted due to https://github.com/easybuilders/easybuild-framework/issues/3934

**Review by casparvl — APPROVED** [review]
Lgtm!

**Comment by casparvl** [comment]
Going in, thanks @TopRichard!

**Pull request merged**
