### PR TITLE
simplify AlphaFold foss/2021a easyconfigs by using a fleshed out patched OpenMM dependency

### PR DESCRIPTION
**Pull request by migueldiascosta**
(created using `eb --new-pr`)

requires `OpenMM-7.5.1-foss-2021a_AlphaFold.eb` from ~~https://github.com/easybuilders/easybuild-easyconfigs/pull/15971~~

(the patched OpenMM is required by many, if not all, AlphaFold variants and implementations (OpenFold, FastFold, etc.), so it makes sense to build it separately and reuse it)

### CODE REVIEW

**Comment by migueldiascosta** [comment]
moving AlphaFold itself from `components` to `ext_list` would require addressing https://github.com/easybuilders/easybuild-framework/issues/3463

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 4 out of 4 (4 easyconfigs in total)
node3307.joltik.os - Linux RHEL 8.4, x86_64, Intel(R) Xeon(R) Gold 6242 CPU @ 2.80GHz (cascadelake), 1 x NVIDIA Tesla V100-SXM2-32GB, 510.73.08, Python 3.6.8
See https://gist.github.com/dc5d9a1a8984a60d434a5c1dfa385664 for a full test report.

**Review by boegel — APPROVED** [review]
lgtm

**Comment by boegel** [comment]
Going in, thanks @migueldiascosta!

**Pull request merged**
