### PR TITLE
Add alternate download URL for Voro++

### PR DESCRIPTION
**Pull request by ocaisa**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by ocaisa** [comment]
@boegelbot please test @ jsc-zen2 EB_ARGS="--force-download"

**Comment by ocaisa** [comment]
Oh some of these are truly ancient, that was probably a mistake to send to jsc-zen2

**Comment by ocaisa** [comment]
@boegelbot please test @ jsc-zen2 EB_ARGS="--force-download Voro++-0.4.6-GCCcore-10.2.0.eb Voro++-0.4.6-GCCcore-10.3.0.eb Voro++-0.4.6-GCCcore-9.3.0.eb"

**Comment by ocaisa** [comment]
Test report by @ocaisa
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
login1 - Linux Rocky Linux 8.5, x86_64, Intel(R) Xeon(R) CPU E5-2690 v3 @ 2.60GHz, Python 3.6.8
See https://gist.github.com/d268c97d60d5ec8d7375e9b29bb44811 for a full test report.

**Review by branfosj — APPROVED** [review]
lgtm

**Comment by branfosj** [comment]
Test report by @branfosj
**SUCCESS**
Build succeeded for 8 out of 8 (8 easyconfigs in total)
bb-pg-login01.bb2.cluster - Linux RHEL 8.6, x86_64, Intel(R) Xeon(R) CPU E5-2620 v4 @ 2.10GHz (broadwell), Python 3.6.8
See https://gist.github.com/11d5cac68adddb62651195614829d5d7 for a full test report.

**Comment by verdurin** [comment]
Test report by @verdurin
**SUCCESS**
Build succeeded for 4 out of 4 (4 easyconfigs in total)
easybuild-c7.novalocal - Linux CentOS Linux 7.9.2009, x86_64, Intel Xeon Processor (Skylake, IBRS), Python 3.6.8
See https://gist.github.com/a06b0a6bd4018d9579cebc2c0ab42081 for a full test report.

**Review by verdurin — APPROVED** [review]
Looks fine.

**Comment by verdurin** [comment]
Going in, thanks @ocaisa!

**Pull request merged**
