### PR TITLE
fix source URL for DB 18.1.32

### PR DESCRIPTION
**Pull request by boegel**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by boegel** [comment]
@boegelbot please test @ generoso
EB_ARGS="--force-download --sourcepath /tmp/$USER/pr13813"

**Review by branfosj — APPROVED** [review]
lgtm

**Comment by branfosj** [comment]
part of #12099

**Comment by branfosj** [comment]
Test report by @branfosj
**SUCCESS**
Build succeeded for 3 out of 3 (3 easyconfigs in total)
bb-pg-login02.bear.cluster - Linux RHEL 8.3, x86_64, Intel(R) Xeon(R) CPU E5-2620 v4 @ 2.10GHz (broadwell), Python 3.6.8
See https://gist.github.com/8dec83b28669ce516568f64ba91aa55b for a full test report.

**Comment by branfosj** [comment]
Going in, thanks @boegel!

**Pull request merged**
