### PR TITLE
angsd - install misc tools

### PR DESCRIPTION
**Pull request by bedroge**
This modification of the angsd easyconfigs makes sure that the additional tools from the misc dir are also installed.

### CODE REVIEW

**Comment by verdurin** [comment]
Test report by @verdurin
**FAILED**
Build succeeded for 34 out of 36 (2 easyconfigs in this PR)
rescomp2 - Linux centos linux 7.3.1611, Intel(R) Xeon(R) Gold 6126 CPU @ 2.60GHz, Python 2.7.11
See https://gist.github.com/6ff61c5821bf0138253502a31e9244aa for a full test report.

**Comment by verdurin** [comment]
Test report by @verdurin
**FAILED**
Build succeeded for 0 out of 2 (2 easyconfigs in this PR)
rescomp2 - Linux centos linux 7.3.1611, Intel(R) Xeon(R) Gold 6126 CPU @ 2.60GHz, Python 2.7.11
See https://gist.github.com/e1d766fcf826ce2135e46b7c70dec9e3 for a full test report.

**Comment by verdurin** [comment]
Here's the error that's affecting `HTSlib`:
```
== 2018-11-17 10:07:54,675 build_log.py:158 ERROR EasyBuild crashed with an error (at ?:124 in __init__): FFTW/3.3.7-GCC-6.4.0-2.28-serial(23):ERROR:150: Module 'FFTW/3.3.7-GCC-6.4.0-2.28-serial' conflicts with the currently loaded module(s) 'FFTW/3.3.7-gompi-2018a' (at easybuild/tools/modules.py:777 in run_module)
```

**Comment by boegel** [comment]
@verdurin That failure has nothing to do with this PR, there's something fishy going on on your end, let's follow up on that in #7174

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in this PR)
node2006.delcatty.os - Linux centos linux 7.5.1804, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.7.5
See https://gist.github.com/c20fe15c64305020c1d25c2266f4ff08 for a full test report.

**Comment by boegel** [comment]
Going in, thanks @bedroge!

**Pull request merged**
