### PR TITLE
add googletest build dependency for Highway

### LINKED ISSUE #14534: installation of Highway (dependency of Brunsli) is broken due to download of googletest
```
[ 22%] Performing download step (git clone) for 'googletest'
Cloning into 'googletest-src'...
error: pathspec 'master' did not match any file(s) known to git.
CMake Error at googletest-download/googletest-prefix/tmp/googletest-gitclone.cmake:40 (message):
  Failed to checkout tag: 'master'


gmake[2]: *** [googletest-prefix/src/googletest-stamp/googletest-download] Error 1
gmake[1]: *** [CMakeFiles/googletest.dir/all] Error 2
gmake: *** [all] Error 2
CMake Error at CMakeLists.txt:265 (message):
  Build step for googletest failed: 2
```

### PR DESCRIPTION
**Pull request by boegel**
(created using `eb --new-pr`)

fixes #14534

### CODE REVIEW

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in total)
node3105.skitty.os - Linux centos linux 7.9.2009, x86_64, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz (skylake_avx512), Python 3.6.8
See https://gist.github.com/2ab4fe20596b0193d8b638b9a530820b for a full test report.

**Comment by boegel** [comment]
@boegelbot please test @ generoso

**Comment by verdurin** [comment]
Test report by @verdurin
**SUCCESS**
Build succeeded for 4 out of 4 (2 easyconfigs in total)
centos7.lan - Linux centos linux 7.9.2009, x86_64, Intel Core Processor (Skylake, IBRS), Python 3.6.8
See https://gist.github.com/d3aac22b6073e7dbbdccba56cb4b3b7c for a full test report.

**Review by verdurin — APPROVED** [review]
Looks fine.

**Comment by verdurin** [comment]
Going in, thanks @boegel!

**Pull request merged**
