### PR TITLE
add Compress::Raw::Zlib to Perl v5.32.0

### PR DESCRIPTION
**Pull request by lexming**
(created using `eb --new-pr`)

Needed by https://github.com/easybuilders/easybuild-easyconfigs/pull/12553

### CODE REVIEW

**Review by Micket — DISMISSED** [review]
I'm a little concerned we are getting ourselves close to a circular buildep here when we add to much to Perl. It's a dependency for Autotools, so I would be very reluctant to add things to it's dependencies if avoidable.

How about just a separate package for `Archive::Zip` instead?

**Comment by lexming** [comment]
@Micket good point, done in https://github.com/easybuilders/easybuild-easyconfigs/pull/12627/commits/cc831db55e0d1de292ff19519d7ca90e4174eef6

**Comment by Micket** [comment]
So, we have multiple PRs that touch Perl right now so I think I will hold off on this until #12575 is merged

**Comment by lexming** [comment]
Test report by @lexming
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
node372.hydra.os - Linux centos linux 7.9.2009, x86_64, Intel(R) Xeon(R) Gold 6148 CPU @ 2.40GHz, Python 2.7.5
See https://gist.github.com/e866911c2b0044aef753ac39d892e7bf for a full test report.

**Comment by boegel** [comment]
@boegelbot please test @ generoso
EB_ARGS="--skip"

**Comment by boegel** [comment]
@Micket Since this adds a single easyconfig at the end of the list, merging this one shouldn't cause trouble for #12575 imho (and if it doesn, it'll be trivial to fix)

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
node3584.doduo.os - Linux RHEL 8.2, x86_64, AMD EPYC 7552 48-Core Processor (zen2), Python 3.6.8
See https://gist.github.com/2b0cdb57e800ed4fb93d0200e9c3c436 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
node2620.swalot.os - Linux centos linux 7.9.2009, x86_64, Intel(R) Xeon(R) CPU E5-2660 v3 @ 2.60GHz (haswell), Python 3.6.8
See https://gist.github.com/44585f75ad2898cf920dd41659606ed6 for a full test report.

**Review by boegel — APPROVED** [review]
lgtm

**Comment by boegel** [comment]
Going in, thanks @lexming!

**Comment by boegel** [comment]
@lexming This extension doesn't actually get installed when using `eb --skip`, because it's detected as already installed.

Does that imply we should undo this change?

**Comment by lexming** [comment]
@boegel indeed, this extension is unexpectedly included in `perl-5.32.0.tar.gz`, that's why it is not getting installed with `eb --skip`

**Comment by lexming** [comment]
I'll bundle this extension with the easyconfig of `VEP` where it is needed.

**Pull request merged**
