### PR TITLE
Fix detection of CC/CXX compilers for `wmake` in OpenFOAM v2306 + v2312

### PR DESCRIPTION
**Pull request by ocaisa**
(created using `eb --new-pr`)

Depends on:

- https://github.com/easybuilders/easybuild-easyblocks/pull/3328

### CODE REVIEW

**Comment by ocaisa** [comment]
The test suite is not picking up on the updated checksum for the patch in the PR

**Comment by ocaisa** [comment]
@boegelbot please test @ generoso
EB_ARGS="--include-easyblocks-from-pr 3328"

**Comment by boegel** [comment]
Test report by @boegel
Using easyblocks from PR(s) https://github.com/easybuilders/easybuild-easyblocks/pull/3328
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in total)
node3117.skitty.os - Linux RHEL 8.8, x86_64, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz, Python 3.6.8
See https://gist.github.com/boegel/f21dc6a51405327c360f8ace64a1f7b7 for a full test report.

**Review by boegel — APPROVED** [review]
lgtm

**Comment by boegel** [comment]
Going in, thanks @ocaisa!

**Pull request merged**
