### PR TITLE
{bio}[foss/2023a] NECAT v0.0.1

### PR DESCRIPTION
**Pull request by PetrKralCZ**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by PetrKralCZ** [comment]
@boegelbot please test @ generoso

**Comment by PetrKralCZ** [comment]
@boegelbot please test @ jsc-zen3

**Comment by PetrKralCZ** [comment]
@boegelbot please test @ jsc-zen3

**Comment by PetrKralCZ** [comment]
@boegelbot please test @ generoso

**Review by boegel — APPROVED** [review]
lgtm

**Pull request merged**
