### PR TITLE
{chem}[foss/2022a] qforce v0.6.11 w/ Python 3.10.4

### PR DESCRIPTION
**Pull request by WilleBell**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by WilleBell** [comment]
Test report by @WilleBell
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
node300.hydra.os - Linux CentOS Linux 7.9.2009, x86_64, Intel(R) Xeon(R) Gold 6148 CPU @ 2.40GHz, Python 3.6.8
See https://gist.github.com/WilleBell/0855ec60fcd5889cfe92b0c314c84c3c for a full test report.

**Comment by smoors** [comment]
@boegelbot please test @ jsc-zen2

**Comment by smoors** [comment]
@WilleBell looks like the official name is `Q-Force`, should we use that?

**Comment by smoors** [comment]
on the other hand, on pypi it's registered as `qforce`, so for discoverability maybe `qforce` is indeed better.

**Review by smoors — APPROVED** [review]
lgtm

**Comment by smoors** [comment]
Going in, thanks @WilleBell!

**Comment by casparvl** [comment]
Test report by @casparvl
**SUCCESS**
Build succeeded for 6 out of 6 (1 easyconfigs in total)
tcn240.local.snellius.surf.nl - Linux RHEL 8.6, x86_64, AMD EPYC 7H12 64-Core Processor, Python 3.6.8
See https://gist.github.com/casparvl/dd9474883a2c81aacd00398832859286 for a full test report.

**Pull request merged**
