### PR TITLE
{cae}[foss/2019b] OpenFOAM-Extend 4.1-20200408

### PR DESCRIPTION
**Pull request by hajgato**

### CODE REVIEW

**Comment by hajgato** [comment]
@boegel Unfortunately I do not understand this style error. Could you help me a bit?

**Comment by akesandgren** [comment]
You mean the
```
/home/runner/work/easybuild-easyconfigs/easybuild-easyconfigs/easybuild/easyconfigs/p/ParMGridGen/ParMGridGen-1.0-gompi-2019b.eb:17:1: E101 indentation contains mixed spaces and tabs
/home/runner/work/easybuild-easyconfigs/easybuild-easyconfigs/easybuild/easyconfigs/p/ParMGridGen/ParMGridGen-1.0-gompi-2019b.eb:17:1: W191 indentation contains tabs
/home/runner/work/easybuild-easyconfigs/easybuild-easyconfigs/easybuild/easyconfigs/p/ParMGridGen/ParMGridGen-1.0-gompi-2019b.eb:18:1: W191 indentation contains tabs
/home/runner/work/easybuild-easyconfigs/easybuild-easyconfigs/easybuild/easyconfigs/p/ParMGridGen/ParMGridGen-1.0-gompi-2019b.eb:21:1: E101 indentation contains mixed spaces and tabs
```
there should be no tabs in the files, only spaces. Convert the tabs to spaces and you're set.
In vi(m)
:set et

**Comment by hajgato** [comment]
@akesandgren There supposed not to be tabs there....

**Comment by akesandgren** [comment]
Well, line 17 and 18 (the patches lines) in ParMGridGen contains tabs

**Comment by hajgato** [comment]
@akesandgren I know, but in theory they should not be there. Anyway, I fixed it.

**Comment by smoors** [comment]
Test report by @smoors
**SUCCESS**
Build succeeded for 3 out of 3 (2 easyconfigs in this PR)
node366.hydra.os - Linux centos linux 7.7.1908, x86_64, Intel(R) Xeon(R) Gold 6148 CPU @ 2.40GHz (skylake_avx512), Python 2.7.5
See https://gist.github.com/e30682f4af027d95b6dcabf0d198a00b for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 3 out of 3 (2 easyconfigs in this PR)
node3401.kirlia.os - Linux centos linux 7.7.1908, x86_64, Intel(R) Xeon(R) Gold 6240 CPU @ 2.60GHz (cascadelake), Python 2.7.5
See https://gist.github.com/78dddc228e84e121be03cf1bf76ec4f6 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in this PR)
node2445.golett.os - Linux centos linux 7.7.1908, x86_64, Intel(R) Xeon(R) CPU E5-2680 v3 @ 2.50GHz (haswell), Python 2.7.5
See https://gist.github.com/868da96a6e2caa8b8363147ab79f69de for a full test report.

**Comment by boegel** [comment]
Going in, thanks @hajgato!

**Pull request merged**
