### PR TITLE
{lang}[system/system] Java v1.8.0_292

### PR DESCRIPTION
**Pull request by lexming**
(created using `eb --new-pr`)

This is an architecture independent easyconfig for Java using the binaries from AdoptOpenJDK.

Depends on ~https://github.com/easybuilders/easybuild-easyblocks/pull/2472~
requires ~https://github.com/easybuilders/easybuild-framework/pull/3758~

### CODE REVIEW

**Comment by lexming** [comment]
Test report by @lexming
Using easyblocks from PR(s) https://github.com/easybuilders/easybuild-easyblocks/pull/2472
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
node381.hydra.os - Linux centos linux 7.9.2009, x86_64, Intel(R) Xeon(R) Gold 6148 CPU @ 2.40GHz, Python 2.7.5
See https://gist.github.com/826f0546960bb431de2fd7463f0f5c40 for a full test report.

**Comment by boegel** [comment]
@boegelbot please test @ generoso

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
node3533.doduo.os - Linux RHEL 8.2, x86_64, AMD EPYC 7552 48-Core Processor (zen2), Python 3.6.8
See https://gist.github.com/835887e50456bec84964717e7565787d for a full test report.

**Comment by boegel** [comment]
@lexming Tests keep failing, needs some more love?

**Comment by lexming** [comment]
@boegel tests should be fixed in https://github.com/easybuilders/easybuild-framework/pull/3758

**Comment by boegel** [comment]
@boegelbot please test @ generoso

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
easybuild2.novalocal - Linux centos linux 8.3.2011, POWER, IBM pSeries (emulated by qemu) (power9le), Python 3.6.8
See https://gist.github.com/008600ce755413f28047631bda202309 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
select-pika-c6gd-2xlarge-0001 - Linux centos linux 8.3.2011, AArch64, ARM UNKNOWN (graviton2), Python 3.6.8
See https://gist.github.com/e093a3db300d9bb45d50c1f9c44a7fc6 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
node3703.slaking.os - Linux RHEL 8.2, x86_64, Intel(R) Xeon(R) CPU E5-2680 v3 @ 2.50GHz (haswell), Python 3.6.8
See https://gist.github.com/62bb732c0fc567fe0c0e3ed0d4d6bb2d for a full test report.

**Review by boegel — APPROVED** [review]
lgtm

**Comment by boegel** [comment]
Going in, thanks @lexming!

**Comment by lexming** [comment]
@boegel thanks for the fix to the `unlink` command :+1:

**Pull request merged**
