### PR TITLE
disable broken numpy test in SciPy-bundle 2020.11 easyconfig using intel/2020b

### LINKED ISSUE #11789: failing numpy test for some SciPy-bundle easyconfigs
With the enhanced `numpy` easyblock that doesn't ignore failing tests anymore (see https://github.com/easybuilders/easybuild-easyblocks/pull/2238), some `SciPy-bundle` easyconfigs got broken.

For example, there's one failing numpy test in`SciPy-bundle-2020.11-intel-2020b`:

```
============================================= FAILURES ==============================================
_______________________________ TestSystemInfoReading.test_overrides ________________________________

self = <numpy.distutils.tests.test_system_info.TestSystemInfoReading object at 0x2af27b0e0670>

    def test_overrides(self):
        previousDir = os.getcwd()
        cfg = os.path.join(self._dir1, 'site.cfg')
        shutil.copy(self._sitecfg, cfg)
        try:
            os.chdir(self._dir1)
            # Check that the '[ALL]' section does not override
            # missing values from other sections
            info = mkl_info()
            lib_dirs = info.cp['ALL']['library_dirs'].split(os.pathsep)
            assert info.get_lib_dirs() != lib_dirs

            # But if we copy the values to a '[mkl]' section the value
            # is correct
            with open(cfg, 'r') as fid:
                mkl = fid.read().replace('ALL', 'mkl')
            with open(cfg, 'w') as fid:
                fid.write(mkl)
            info = mkl_info()
>           assert info.get_lib_dirs() == lib_dirs
E           AssertionError: assert ['/user/gent/.../tmponjnra2k'] == ['/tmp/eb-co_.../tmponjnra2k']
E             At index 0 diff: '/software/imkl/2020.4.304-iimpi-2020b/mkl' != '/tmp/eb-co_qliaj/eb-35grni_i/tmpgpmlnhpb'
E             Left contains 3 more items, first extra item: '/software/imkl/2020.4.304-iimpi-2020b/mkl/lib'
E             Use -v to get the full diff

cfg        = '/tmp/eb-co_qliaj/eb-35grni_i/tmpgpmlnhpb/site.cfg'
fid        = <_io.TextIOWrapper name='/tmp/eb-co_qliaj/eb-35grni_i/tmpgpmlnhpb/site.cfg' mode='w' encoding='UTF-8'>
info       = <numpy.distutils.system_info.mkl_info object at 0x2af27b0f24f0>
lib_dirs   = ['/tmp/eb-co_qliaj/eb-35grni_i/tmpgpmlnhpb', '/tmp/eb-co_qliaj/eb-35grni_i/tmponjnra2k']
mkl        = '\n[mkl]\nlibrary_dirs = /tmp/eb-co_qliaj/eb-35grni_i/tmpgpmlnhpb:/tmp/eb-co_qliaj/eb-35grni_i/tmponjnra2k\nlibraries ...= /tmp/eb-co_qliaj/eb-35grni_i/tmpgpmlnhpb/libfoo.so\nlibraries = /tmp/eb-co_qliaj/eb-35grni_i/tmponjnra2k/libbar.so\n'
previousDir = '/tmp/easybuild_build/SciPybundle/2020.11/intel-2020b/numpy'
self       = <numpy.distutils.tests.test_system_info.TestSystemInfoReading object at 0x2af27b0e0670>

/tmp/eb-co_qliaj/eb-35grni_i/tmpwt7tzvkh/lib/python3.8/site-packages/numpy/distutils/tests/test_system_info.py:276: AssertionError
```

### PR DESCRIPTION
**Pull request by boegel**
(created using `eb --new-pr`)
fixes #11789

### CODE REVIEW

**Comment by boegel** [comment]
@boegelbot please test @ generoso

**Comment by migueldiascosta** [comment]
Test report by @migueldiascosta
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
sms - Linux centos linux 7.6.1810, x86_64, AMD EPYC 7601 32-Core Processor (zen), Python 2.7.5
See https://gist.github.com/c9b54216caff0ce0d453e7dd01b42efe for a full test report.

**Review by migueldiascosta — APPROVED** [review]
lgtm

**Comment by migueldiascosta** [comment]
Going in, thanks @boegel!

**Pull request merged**
