### PR TITLE
{tools}[foss/2018b] Livy v0.6.0 w/ Python 2.7.15

### PR DESCRIPTION
**Pull request by boegel**
(created using `eb --new-pr`)
requires ~~#9401~~ (Spark) + ~~#9408~~ (`$SPARK_HOME` defined for `Spark`)

### CODE REVIEW

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
generoso - Linux centos linux 7.6.1810, Intel(R) Xeon(R) CPU E5-2660 v4 @ 2.00GHz, Python 3.6.8
See https://gist.github.com/645af0273e4258b5c488972d6583bb3a for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
node2404.golett.os - Linux centos linux 7.7.1908, Intel(R) Xeon(R) CPU E5-2680 v3 @ 2.50GHz, Python 2.7.5
See https://gist.github.com/7f9d697a321bd5ca6b53e955406a3231 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
node2404.golett.os - Linux centos linux 7.7.1908, Intel(R) Xeon(R) CPU E5-2680 v3 @ 2.50GHz, Python 2.7.5
See https://gist.github.com/608a7ab2422e076ed89a08ad75882e27 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 2 out of 2 (1 easyconfigs in this PR)
node3169.skitty.os - Linux centos linux 7.7.1908, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz, Python 3.6.8
See https://gist.github.com/f41daca3c98a4a0937e6661b9584a954 for a full test report.

**Comment by akesandgren** [comment]
Test report by @akesandgren
**FAILED**
Build succeeded for 7 out of 8 (1 easyconfigs in this PR)
b-an03.hpc2n.umu.se - Linux ubuntu 16.04, Intel(R) Xeon(R) CPU E5-2690 v4 @ 2.60GHz, Python 2.7.12
See https://gist.github.com/0d447beec384f7349a29a8db47121f74 for a full test report.

**Comment by akesandgren** [comment]
Test report by @akesandgren
**FAILED**
Build succeeded for 0 out of 1 (1 easyconfigs in this PR)
b-an03.hpc2n.umu.se - Linux ubuntu 16.04, Intel(R) Xeon(R) CPU E5-2690 v4 @ 2.60GHz, Python 2.7.12
See https://gist.github.com/39972bc3de6be1b1e53c07b092939383 for a full test report.

**Comment by boegel** [comment]
@akesandgren Is that a persistent issue?

**Comment by akesandgren** [comment]
testing again...

**Comment by akesandgren** [comment]
Test report by @akesandgren
**FAILED**
Build succeeded for 0 out of 1 (1 easyconfigs in this PR)
b-an03.hpc2n.umu.se - Linux ubuntu 16.04, Intel(R) Xeon(R) CPU E5-2690 v4 @ 2.60GHz, Python 2.7.12
See https://gist.github.com/602886cafa43106712442680dd297112 for a full test report.

**Comment by akesandgren** [comment]
Apparently. would rebuilding spark help?

**Comment by akesandgren** [comment]
Test report by @akesandgren
**FAILED**
Build succeeded for 0 out of 1 (1 easyconfigs in this PR)
b-an03.hpc2n.umu.se - Linux ubuntu 16.04, Intel(R) Xeon(R) CPU E5-2690 v4 @ 2.60GHz, Python 2.7.12
See https://gist.github.com/3e5bb11275a9a5692a72286ff8bb64b4 for a full test report.

**Comment by akesandgren** [comment]
Seems like I get that every time. Was using develop tree for both runs

**Comment by boegel** [comment]
Installation fails for @akesandgren because of a missing dependency when the required Python packages are being installed:

```
src/kerberosbasic.h:17:10: fatal error: gssapi/gssapi.h: No such file or directory
 #include <gssapi/gssapi.h>
```

Proper fix would be to let EasyBuild install the missing required Python packages instead (incl. `requests-kerberos`, `responses`, `future`, `cloudpickle`, `pykerberos`).

Not planning to pursue this for this old toolchain and Python version, so closing this PR, it can serve as a reference for others that want to look into add support for installing `Livy`...

**Pull request closed without merging**
