### PR TITLE
{lib}[system/system] NCCL v2.10.3

### PR DESCRIPTION
**Pull request by robert-mijakovic**
(created using `eb --new-pr`)
Depends on:
- [ ] #13301

### CODE REVIEW

**Comment by robert-mijakovic** [comment]
@boegelbot please test @ generoso EB_ARGS="--from-pr 13301"

**Comment by Micket** [comment]
Not sure we still want the binary version instead of compiling it.

**Comment by robert-mijakovic** [comment]
@Micket Ok. I will prepare the compiled version.

**Comment by Micket** [comment]
Already open https://github.com/easybuilders/easybuild-easyconfigs/pull/13282
Just waiting for the decision on https://github.com/easybuilders/easybuild-easyconfigs/issues/12484

**Comment by Flamefire** [comment]
> Not sure we still want the binary version instead of compiling it.

I'd always go for compiling as it allows adding patches if we need it. Hence my suggestion to close this in favor of https://github.com/easybuilders/easybuild-easyconfigs/pull/13282

**Comment by robert-mijakovic** [comment]
> > Not sure we still want the binary version instead of compiling it.
> 
> I'd always go for compiling as it allows adding patches if we need it. Hence my suggestion to close this in favor of #13282

I agree, thus closing.

**Pull request closed without merging**
