### PR TITLE
add seqPattern, genomation and ChIPseeker to R-bundle-Bioconductor v3.18

### PR DESCRIPTION
**Pull request by PetrKralCZ**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by PetrKralCZ** [comment]
@boegelbot please test @ generoso
EB_ARGS="--skip"

**Comment by PetrKralCZ** [comment]
@boegelbot please test @ jsc-zen3
EB_ARGS="--skip"

**Review by boegel — APPROVED** [review]
lgtm

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
node3123.skitty.os - Linux RHEL 8.8, x86_64, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz, Python 3.6.8
See https://gist.github.com/boegel/3ffcd532ba8b79ba7a70daa8ff2ec55e for a full test report.

**Comment by boegel** [comment]
Going in, thanks @PetrKralCZ!

**Pull request merged**
