### PR TITLE
specify to use Python provided as dependency, remove separate_build_dir, and fix URL in comment for Arrow 0.17.1

### PR DESCRIPTION
**Pull request by branfosj**
(created using `eb --new-pr`)

Mirrors the changes in https://github.com/easybuilders/easybuild-easyconfigs/pull/14259#pullrequestreview-793696936

* Specify to use EB Python (or it picks up the Python from my EB venv)
* fix a URL that is 404-ing
* remove the unneeded `separate_build_dir`

### CODE REVIEW

**Comment by branfosj** [comment]
@boegelbot please test @ generoso

**Comment by branfosj** [comment]
Test report by @branfosj
**FAILED**
Build succeeded for 0 out of 3 (3 easyconfigs in total)
bear-pg0211u03a.bear.cluster - Linux RHEL 8.3, x86_64, Intel(R) Xeon(R) Gold 6248 CPU @ 2.50GHz (cascadelake), Python 3.6.8
See https://gist.github.com/dbfddd65ef37251f9650fc1ffa6ecb3a for a full test report.

**Comment by branfosj** [comment]
Test report by @branfosj
**SUCCESS**
Build succeeded for 3 out of 3 (3 easyconfigs in total)
bear-pg0211u03a.bear.cluster - Linux RHEL 8.3, x86_64, Intel(R) Xeon(R) Gold 6248 CPU @ 2.50GHz (cascadelake), Python 3.6.8
See https://gist.github.com/2e899a1feb77cf74398859e3d2b7fec3 for a full test report.

**Comment by verdurin** [comment]
Test report by @verdurin
**FAILED**
Build succeeded for 2 out of 18 (4 easyconfigs in total)
easybuild-c7.novalocal - Linux centos linux 7.9.2009, x86_64, Intel Xeon Processor (Skylake, IBRS), Python 3.6.8
See https://gist.github.com/7188ba73a7f41119c0428d431b7d7649 for a full test report.

**Comment by boegel** [comment]
@verdurin The failures in that test report are not related to the changes made here (Intel license is missing), so I'll blatantly ignore it...

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 4 out of 4 (4 easyconfigs in total)
node2624.swalot.os - Linux centos linux 7.9.2009, x86_64, Intel(R) Xeon(R) CPU E5-2660 v3 @ 2.60GHz (haswell), Python 3.6.8
See https://gist.github.com/4cc830f614f7069b019174ce7f65e429 for a full test report.

**Review by boegel — APPROVED** [review]
lgtm

**Comment by boegel** [comment]
Going in, thanks @branfosj!

**Pull request merged**
