### PR TITLE
restore ploteig in EIGENSOFT 7.2.1

### PR DESCRIPTION
**Pull request by branfosj**
(created using `eb --new-pr`)

This adds https://github.com/DReichLab/EIG/commit/7a6036bf36d8d2ed038b83d26112cdde4f383747, which is a commit from after 7.2.1 was released.

### CODE REVIEW

**Comment by SebastianAchilles** [comment]
Test report by @sebastianachilles
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
bdw-opensuse-154 - Linux openSUSE Leap 15.4, x86_64, Intel(R) Core(TM) i7-6900K CPU @ 3.20GHz (broadwell), Python 3.6.15
See https://gist.github.com/ccab45acd8e2924b573919eaadb645b1 for a full test report.

**Comment by SebastianAchilles** [comment]
@boegelbot please test @ generoso

**Comment by SebastianAchilles** [comment]
@boegelbot please test @ jsc-zen2
EB_ARGS="EIGENSOFT-7.2.1-foss-2019b.eb EIGENSOFT-7.2.1-foss-2021a.eb"

**Comment by branfosj** [comment]
Test report by @branfosj
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
bear-pg0211u03a.bear.cluster - Linux RHEL 8.6, x86_64, Intel(R) Xeon(R) Gold 6248 CPU @ 2.50GHz (cascadelake), Python 3.6.8
See https://gist.github.com/457e5635c2914575a86c625fafc06219 for a full test report.

**Comment by SebastianAchilles** [comment]
@boegelbot please test @ generoso
EB_ARGS="EIGENSOFT-7.2.1-foss-2019a.eb EIGENSOFT-7.2.1-foss-2019b.eb EIGENSOFT-7.2.1-foss-2021a.eb EIGENSOFT-7.2.1-intel-2019a.eb"

**Comment by SebastianAchilles** [comment]
@boegelbot please test @ jsc-zen2
EB_ARGS="EIGENSOFT-7.2.1-foss-2021a.eb"

**Review by SebastianAchilles — APPROVED** [review]
lgtm

**Comment by SebastianAchilles** [comment]
Going in, thanks @branfosj!

**Pull request merged**
