### PR TITLE
{bio}[foss/2020a] GROMACS v2020.4

### PR DESCRIPTION
**Pull request by dithwick**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by verdurin** [comment]
Test report by @verdurin
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
nuc.lan - Linux Fedora 32, x86_64, Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz, Python 3.8.6
See https://gist.github.com/c6f6a9862cb619ca600373d1af497b44 for a full test report.

**Comment by verdurin** [comment]
Hi @dithwick is there any reason not to include the `gmxapi` extension as per https://github.com/easybuilders/easybuild-easyconfigs/blob/develop/easybuild/easyconfigs/g/GROMACS/GROMACS-2020.1-foss-2020a-Python-3.8.2.eb ?

**Comment by dithwick** [comment]
@verdurin Probably just because our users haven't asked for it (or explicitly stated that they didn't need it). I guess it does also produce a slightly leaner build with fewer dependent modules. However I can either do an additional version with the Python/gmxapi support built in or withdraw this one if you'd prefer?

**Comment by dithwick** [comment]
I forgot to add that I'm building the toolchain to try a fosscuda-2020a version which I'll submit as a separate PR.

**Comment by verdurin** [comment]
@dithwick we already have a bit of proliferation so I would prefer not to have multiple versions. 

Good to hear about the GPU version, too.

**Comment by dithwick** [comment]
No worries, I'll commit a version with gmxapi enabled and remove the other version. I'll make sure to do the same for the fosscuda version as well.

**Comment by Micket** [comment]
Test report by @Micket
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
vera-c1 - Linux centos linux 7.8.2003, x86_64, Intel Xeon Processor (Skylake), Python 2.7.5
See https://gist.github.com/0492ed15c1121c6e4cf301cec53a906e for a full test report.

**Review by Micket — APPROVED** [review]
lgtm

**Comment by Micket** [comment]
Going in, thanks @dithwick!

**Comment by Micket** [comment]
Ugh, sorry, I messed up, totally missed the discussion above trying to multitask

**Comment by dithwick** [comment]
@Micket no worries, I probably should've withdrawn the pull request but got distracted with something else.

**Comment by Micket** [comment]
Addressed in #11640

**Pull request merged**
