### PR TITLE
{tools}[system/system] EasyBuild v4.7.0

### PR DESCRIPTION
**Pull request by boegel**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
nata221.ugent.be - Darwin UNKNOWN UNKNOWN, AArch64, Apple M1, Python 3.9.6
See https://gist.github.com/01b081cbdab1ea91288a83b0fe3286e8 for a full test report.

**Comment by SebastianAchilles** [comment]
@boegelbot please test @ jsc-zen2

**Comment by SebastianAchilles** [comment]
Test report by @sebastianachilles
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
bwd-rockylinux-91 - Linux Rocky Linux 9.1 (Blue Onyx), x86_64, Intel(R) Core(TM) i7-6900K CPU @ 3.20GHz (broadwell), 2 x NVIDIA NVIDIA GeForce GTX 1060 6GB, 515.86.01, Python 3.9.14
See https://gist.github.com/d9d71c8d860fbf068e91d5f73b5f1cc8 for a full test report.

**Comment by SebastianAchilles** [comment]
Test report by @sebastianachilles
**FAILED**
Build succeeded for 0 out of 1 (1 easyconfigs in total)
zen2-ubuntu-2204 - Linux Ubuntu 22.04.1 LTS (Jammy Jellyfish), x86_64, AMD EPYC 7452 32-Core Processor (zen2), Python 3.10.6
See https://gist.github.com/15f27585458692f6aac1b94be699187d for a full test report.

**Comment by boegel** [comment]
> 

@SebastianAchilles This is probably due to https://github.com/easybuilders/easybuild-framework/issues/4128

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
node3168.skitty.os - Linux RHEL 8.6, x86_64, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz (skylake_avx512), Python 3.6.8
See https://gist.github.com/ed340ed3bcb1bc482188c58b32da6d83 for a full test report.

**Comment by SebastianAchilles** [comment]
> > Test report by @SebastianAchilles **FAILED** Build succeeded for 0 out of 1 (1 easyconfigs in total) zen2-ubuntu-2204 - Linux Ubuntu 22.04.1 LTS (Jammy Jellyfish), x86_64, AMD EPYC 7452 32-Core Processor (zen2), Python 3.10.6 See https://gist.github.com/15f27585458692f6aac1b94be699187d for a full test report.
> 
> @SebastianAchilles This is probably due to [easybuilders/easybuild-framework#4128](https://github.com/easybuilders/easybuild-framework/issues/4128)

Indeed, I run this known bug.

**Comment by SebastianAchilles** [comment]
Test report by @sebastianachilles
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
zen2-ubuntu-2204 - Linux Ubuntu 22.04.1 LTS (Jammy Jellyfish), x86_64, AMD EPYC 7452 32-Core Processor (zen2), Python 3.10.6
See https://gist.github.com/564573583aa5d72a3012c81d8a15d3b7 for a full test report.

**Comment by SebastianAchilles** [comment]
@boegelbot please test @ generoso

**Review by SebastianAchilles — APPROVED** [review]
lgtm

**Comment by SebastianAchilles** [comment]
Going in, thanks @boegel!

**Comment by SebastianAchilles** [comment]
Test report by @sebastianachilles
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
eb-riscv - Linux Ubuntu 22.10, RISC-V-64, UNKNOWN (riscv64), Python 3.10.7
See https://gist.github.com/cae3dcc484304726a1a3c08ddf9d513d for a full test report.

**Pull request merged**
