### PR TITLE
in-place update to magma 2.5.4 for PyTorch 1.2.0

### PR DESCRIPTION
**Pull request by Flamefire**
(created using `eb --new-pr`)

Fixes a known Bug, see https://github.com/easybuilders/easybuild-easyconfigs/pull/11656

### CODE REVIEW

**Comment by Flamefire** [comment]
Test report by @Flamefire
**FAILED**
Build succeeded for 0 out of 1 (1 easyconfigs in total)
taurusa5 - Linux centos linux 7.7.1908, x86_64, Intel(R) Xeon(R) CPU E5-2603 v4 @ 1.70GHz, Python 2.7.5
See https://gist.github.com/11289e48a9bca9c8cd7a6e59e4a64c4d for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
node3304.joltik.os - Linux centos linux 7.8.2003, x86_64, Intel(R) Xeon(R) Gold 6242 CPU @ 2.80GHz (cascadelake), Python 3.6.8
See https://gist.github.com/6e7b7107b9f01fb89a3c2d5c2700625a for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
node3405.kirlia.os - Linux centos linux 7.8.2003, x86_64, Intel(R) Xeon(R) Gold 6240 CPU @ 2.60GHz (cascadelake), Python 2.7.5
See https://gist.github.com/7b2ad3d9a605753c20a1b48537516840 for a full test report.

**Comment by boegel** [comment]
> Failure is a flaky (or bad?) test and CUDA 11 issue fixed with PyTorch-1.4.0_add-cuda11-support.patch.
> This patch might apply to 1.2, so we could backport it.

@Flamefire Are you planning to?

**Comment by Flamefire** [comment]
Done, same for 1.3.1 in #11726

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
node3303.joltik.os - Linux centos linux 7.8.2003, x86_64, Intel(R) Xeon(R) Gold 6242 CPU @ 2.80GHz (cascadelake), Python 3.6.8
See https://gist.github.com/d00981ab61ffdc750a7f57657f39cb26 for a full test report.

**Comment by Flamefire** [comment]
Test report by @Flamefire
**FAILED**
Build succeeded for 0 out of 1 (1 easyconfigs in total)
taurusa6 - Linux centos linux 7.7.1908, x86_64, Intel(R) Xeon(R) CPU E5-2603 v4 @ 1.70GHz, Python 2.7.5
See https://gist.github.com/33c500a903460d2297fe03958d788133 for a full test report.

**Comment by boegel** [comment]
@Flamefire 

```
======================================================================
FAIL: test_stream_event_nogil (__main__.TestCuda)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/tmp/s3248973-EasyBuild/PyTorch/1.2.0/fosscuda-2019a-Python-3.7.2/pytorch-1.2.0/test/common_utils.py", line 456, in wrapper
    method(*args, **kwargs)
  File "/tmp/s3248973-EasyBuild/PyTorch/1.2.0/fosscuda-2019a-Python-3.7.2/pytorch-1.2.0/test/common_utils.py", line 206, in wrapper
    fn(*args, **kwargs)
  File "test_cuda.py", line 1925, in test_stream_event_nogil
    self.assertGreater(parent_time + child_time, total_time * 1.4)
AssertionError: 64.6318416595459 not greater than 75.06289291381836

----------------------------------------------------------------------
Ran 2145 tests in 1073.894s

FAILED (failures=1, skipped=150)
```

**Comment by Flamefire** [comment]
Ah, I knew I've seen that: https://github.com/pytorch/pytorch/pull/41398
Adding a patch

**Comment by Flamefire** [comment]
Test report by @Flamefire
**FAILED**
Build succeeded for 0 out of 1 (1 easyconfigs in total)
taurusa4 - Linux centos linux 7.7.1908, x86_64, Intel(R) Xeon(R) CPU E5-2603 v4 @ 1.70GHz, Python 2.7.5
See https://gist.github.com/9456354dab7137709ee78dc737f22825 for a full test report.

**Comment by Flamefire** [comment]
Test report by @Flamefire
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
taurusa4 - Linux centos linux 7.7.1908, x86_64, Intel(R) Xeon(R) CPU E5-2603 v4 @ 1.70GHz, Python 2.7.5
See https://gist.github.com/3d11f56b244b8d6d8923f2c66b8174ff for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**FAILED**
Build succeeded for 0 out of 1 (1 easyconfigs in total)
node3307.joltik.os - Linux centos linux 7.8.2003, x86_64, Intel(R) Xeon(R) Gold 6242 CPU @ 2.80GHz (cascadelake), Python 3.6.8
See https://gist.github.com/1c80c7b61c6d82e0813a51975d74326a for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**FAILED**
Build succeeded for 0 out of 1 (1 easyconfigs in total)
node3307.joltik.os - Linux centos linux 7.8.2003, x86_64, Intel(R) Xeon(R) Gold 6242 CPU @ 2.80GHz (cascadelake), Python 3.6.8
See https://gist.github.com/0b601c6e561a2ad40c2a993750a8a6a9 for a full test report.

**Comment by lexming** [comment]
Test report by @lexming
**SUCCESS**
Build succeeded for 2 out of 2 (1 easyconfigs in total)
node154.hydra.os - Linux centos linux 7.9.2009, x86_64, Intel(R) Xeon(R) CPU E5-2680 v2 @ 2.80GHz, Python 2.7.5
See https://gist.github.com/f99a3f4a15e6578e126b826821408653 for a full test report.

**Comment by boegel** [comment]
@Flamefire Does this test failure ring a bell for you?

```
AssertionError: 1024 not less than or equal to 1e-05 : __main__.TestNN.test_BatchNorm3d_momentum_eval_cuda leaked -1024 bytes CUDA memory on device 0
```

**Comment by Flamefire** [comment]
@boegel Not at all, sorry. Maybe add `-x nn` or so? (or transform this to use the PyTorch EasyBlock which might be easier but well... This shouldn't be something introduced by this change but rather discovered by more testing)

**Review by lexming — APPROVED** [review]
LGTM

**Comment by lexming** [comment]
@boegel I'll leave the final merge up to you

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
node3307.joltik.os - Linux centos linux 7.8.2003, x86_64, Intel(R) Xeon(R) Gold 6242 CPU @ 2.80GHz (cascadelake), Python 3.6.8
See https://gist.github.com/ab701dcaf9b1e0dc0c69c8aca4081570 for a full test report.

**Comment by boegel** [comment]
Going in, thanks @Flamefire!

**Pull request merged**
