### PR TITLE
add UnZip build dep to Python 3.8.2 easyconfig

### PR DESCRIPTION
**Pull request by boegel**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by lexming** [comment]
As I said, I do not see any reason to add `unzip` to this easyconfig. `unzip` is a dependency for Easybuild itself, as documented in https://easybuild.readthedocs.io/en/latest/Installation.html#required-shell-tools. So it should be already available in the system, if that's not the case it is a mistake on the user's side, not on the Easybuild side.

Moreover, why should we add `unzip` only to this easyconfig in particular and not all the others that also deal with zipped sources?

**Comment by boegel** [comment]
@lexming I don't see why not to add `UnZip` as a build dep, if we have the easyconfig for it anyway?

`unzip` is not a strict dep for EasyBuild, it's only really needed when installing something that includes `*.zip` sources (as is the case here).

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in this PR)
node3401.kirlia.os - Linux centos linux 7.7.1908, x86_64, Intel(R) Xeon(R) Gold 6240 CPU @ 2.60GHz (cascadelake), Python 2.7.5
See https://gist.github.com/a661d5bdb5bf0c63f64aedb51d2407c6 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in this PR)
node3128.skitty.os - Linux centos linux 7.7.1908, x86_64, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz (skylake_avx512), Python 3.6.8
See https://gist.github.com/e0e9c79d85f0219ae0a9ca98a75e82d7 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in this PR)
node2528.golett.os - Linux centos linux 7.7.1908, x86_64, Intel(R) Xeon(R) CPU E5-2680 v3 @ 2.50GHz (haswell), Python 2.7.5
See https://gist.github.com/1443c4d4bd838f8ff7871db4ef0ff6fd for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in this PR)
generoso-3 - Linux centos linux 7.6.1810, x86_64, Intel(R) Xeon(R) CPU E5-2660 v4 @ 2.00GHz, Python 3.6.8
See https://gist.github.com/b0d60774191933a6c19b2c601c7dbe17 for a full test report.

**Comment by lexming** [comment]
@boegel Because it's inconsistent and confusing. I don't understand why you are accepting this as an issue for an extension in Python-3.8.2 and not for easyconfigs that have the main sources in zip format. If we would agree that unpacking of sources has to be granted at the easyconfig level, adding unzip as build dep cannot be applied to anything else than `exts_list`. It does not work for the main sources or even the components of a bundle. So this seems more a workaround than a real solution.

I still think that having unzip as a dependency of Easybuild is sufficient.
In my opinion there are only two reasons to use `UnZip` as a dependency:
* in `builddependencies` if the software statically links to it
* in `dependencies` if it is needed at runtime

**Comment by boegel** [comment]
@lexming I guess you're right, I just prefer not depending on stuff provided by the OS when we can.

Using `UnZip` as a build dependency for extracting main sources indeed doesn't work currently, due to https://github.com/easybuilders/easybuild-framework/issues/1376 . Fixing that isn't that trivial though, see comments.

I'm fine with keeping this on hold for now...

**Comment by boegel** [comment]
fixed in #11458

**Pull request closed without merging**
