### PR TITLE
{vis}[GCCcore/10.2.0] FLTK v1.3.5, xprop v1.2.5

### PR DESCRIPTION
**Pull request by Micket**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by Micket** [comment]
Test report by @Micket
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in total)
vera-c1 - Linux centos linux 7.9.2009, x86_64, Intel Xeon Processor (Skylake), Python 2.7.5
See https://gist.github.com/79a5d19b93d44909833234a60224dee1 for a full test report.

**Comment by Micket** [comment]
```
 AssertionError: Invalid checksum for patch file Pindel-0.2.5b9-20170508_fix-ambig-abs-compil-err.patch in Pindel-0.2.5b9-20170508-GCC-6.4.0-2.28.eb: 216ae1145fd1568ac2187a89bf4b95c45d5c02272047a3dd5f9dfbede26c8fec
 ```
huh

**Comment by Micket** [comment]
I'll just retrigger tests

**Comment by Micket** [comment]
@boegelbot please test @ generoso

**Comment by boegel** [comment]
> ```
>  AssertionError: Invalid checksum for patch file Pindel-0.2.5b9-20170508_fix-ambig-abs-compil-err.patch in Pindel-0.2.5b9-20170508-GCC-6.4.0-2.28.eb: 216ae1145fd1568ac2187a89bf4b95c45d5c02272047a3dd5f9dfbede26c8fec
> ```
> 
> huh

Looks like a glitch, since only one of the test configurations failed.
I've restarted the original set of tests (close/re-open creates a *new* set of tests...)

**Comment by zao** [comment]
Test report by @zao
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in total)
eb-u2004 - Linux Ubuntu 20.04, x86_64, Intel(R) Core(TM) i7-8700K CPU @ 3.70GHz, Python 3.8.5
See https://gist.github.com/e2da14ce5c6e5a1634080d69dcab6bf2 for a full test report.

**Comment by verdurin** [comment]
Test report by @verdurin
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in total)
nuc.lan - Linux Fedora 33, x86_64, Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz, Python 3.9.2
See https://gist.github.com/c10f2d8bcd3470b7682a527ce0a0e685 for a full test report.

**Review by verdurin — APPROVED** [review]
Looks fine.

**Comment by verdurin** [comment]
Going in, thanks @Micket!

**Pull request merged**
