### PR TITLE
{lang}[GCCcore/11.3.0] Ruby v3.0.5

### PR DESCRIPTION
**Pull request by iotaka**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by smoors** [comment]
@iotaka thanks for your contributions!

please do not set a custom title for new easyconfigs; they will be set automatically in the correct format

**Comment by iotaka** [comment]
@smoors I have to omit --pr-title  ?

**Comment by jfgrimm** [comment]
> @smoors I have to omit --pr-title ?

yes, if you don't specify `--pr-title` when creating a pull request that adds new easyconfigs, then easybuild will automatically create one -- in this case `{lang}[GCCcore/11.3.0] Ruby v3.0.5`.

**Comment by smoors** [comment]
@boegelbot: please test @ generoso

**Comment by smoors** [comment]
@iotaka it looks like the checksum for the Ruby sources is wrong:

```
== 2022-12-21 13:00:37,066 build_log.py:169 ERROR EasyBuild crashed with an error (at easybuild/easybuild-framework/easybuild/base/exceptions.py:124 in __init__): Checksum verification for /project/boegelbot/sources/r/Ruby/ruby-3.0.5.tar.gz using 3586861cb2df56970287f0fd83f274bd92058872d830d15570b36def7f1a92ac failed. (at easybuild/easybuild-framework/easybuild/framework/easyblock.py:2407 in checksum_step)
```

**Comment by smoors** [comment]
@boegelbot: please test @ generoso

**Comment by smoors** [comment]
@boegelbot please test @ jsc-zen2

**Comment by smoors** [comment]
@boegelbot please test @ jsc-zen2

**Review by smoors — APPROVED** [review]
lgtm

**Comment by smoors** [comment]
Going in, thanks @iotaka!

**Pull request merged**
