### PR TITLE
fix source URLs in Eigen 3.3.* easyconfigs

### PR DESCRIPTION
**Pull request by boegel**
(created using `eb --new-pr`)
fixes part of #10868

### CODE REVIEW

**Comment by boegel** [comment]
Checksums have changed, but actual sources have not:

```
$ diff -ru eigen-eigen-5a0156e40feb eigen-3.3.4
Only in eigen-eigen-5a0156e40feb: .hg_archival.txt
Only in eigen-eigen-5a0156e40feb: .hgtags
$
```

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 8 out of 8 (8 easyconfigs in this PR)
node2400.golett.os - Linux centos linux 7.8.2003, x86_64, Intel(R) Xeon(R) CPU E5-2680 v3 @ 2.50GHz (haswell), Python 2.7.5
See https://gist.github.com/71c6b183f5efd9dadfeb4aeee84ac6c5 for a full test report.

**Comment by zao** [comment]
Going in, thanks @boegel!

**Comment by boegel** [comment]
> Initially wondered if we should keep the original checksum, but the filenames differ so it doesn't matter in this case.

Indeed, that was my initial intention, but it doesn't make sense since the filenames are different.

**Pull request merged**
