### PR TITLE
{tools}[foss/2017b,intel/2017b] Subversion v1.10.0

### PR DESCRIPTION
**Pull request by vanzod**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by vanzod** [comment]
Test report by @vanzod
**SUCCESS**
Build succeeded for 8 out of 8 (8 easyconfigs in this PR)
cermis - Linux debian 9.5, Intel(R) Xeon(R) CPU           E5620  @ 2.40GHz, Python 2.7.13
See https://gist.github.com/a4003fccd67879722b17813565447a8b for a full test report.

**Comment by vanzod** [comment]
Test report by @vanzod
**SUCCESS**
Build succeeded for 8 out of 8 (8 easyconfigs in this PR)
cermis - Linux debian 9.5, Intel(R) Xeon(R) CPU           E5620  @ 2.40GHz, Python 2.7.13
See https://gist.github.com/73f0d8adde9e7183b016a85f91ff8433 for a full test report.

**Comment by boegel** [comment]
@vanzod Conflict on `expat` (like we had before?):

```
$ eb --from-pr 7083 --check-conflicts Subversion-1.10.0-foss-2017b.eb
== temporary log file in case of crash /Users/kehoste/work/TMP/eb-m6FKnl/easybuild-wQJ86U.log
Conflict found for dependencies of Subversion-1.10.0-foss-2017b: expat-2.2.4-GCCcore-6.4.0 vs expat-2.2.5-GCCcore-6.4.0
	expat-2.2.4-GCCcore-6.4.0 as dep of: APR-util-1.6.1-GCCcore-6.4.0, Serf-1.3.9-foss-2017b, Subversion-1.10.0-foss-2017b
	expat-2.2.5-GCCcore-6.4.0 as dep of: Perl-5.26.1-GCCcore-6.4.0, Subversion-1.10.0-foss-2017b
Conflict between (dependencies of) easyconfigs: expat-2.2.4-GCCcore-6.4.0 vs expat-2.2.5-GCCcore-6.4.0
	expat-2.2.4-GCCcore-6.4.0 as dep of: APR-util-1.6.1-GCCcore-6.4.0, Serf-1.3.9-foss-2017b, Subversion-1.10.0-foss-2017b
	expat-2.2.5-GCCcore-6.4.0 as dep of: Perl-5.26.1-GCCcore-6.4.0, Subversion-1.10.0-foss-2017b
ERROR: One or more conflicts detected!
```

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 14 out of 14 (8 easyconfigs in this PR)
node2472.golett.os - Linux centos linux 7.5.1804, Intel(R) Xeon(R) CPU E5-2680 v3 @ 2.50GHz, Python 2.7.5
See https://gist.github.com/c4443ad586cbe3296ef5a23f702609fb for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 8 out of 8 (8 easyconfigs in this PR)
node2095.delcatty.os - Linux centos linux 7.5.1804, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.7.5
See https://gist.github.com/2f36b20f85635c668d2a0cc07bbc6b83 for a full test report.

**Comment by boegel** [comment]
Going in, thanks @vanzod!

**Pull request merged**
