### PR TITLE
{vis}[GCCcore/6.4.0] fontconfig v2.12.1

### PR DESCRIPTION
**Pull request by JackPerdue**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by verdurin** [comment]
Test report by @verdurin
**SUCCESS**
Build succeeded for 5 out of 5 (2 easyconfigs in this PR)
ca014.camp.thecrick.org - Linux centos linux 7.3.1611, Intel(R) Xeon(R) CPU E5-2640 v3 @ 2.60GHz, Python 2.7.5
See https://gist.github.com/d91bf5b933ef788ab3e76f0054be9df8 for a full test report.

**Comment by verdurin** [comment]
Merging, thanks @JackPerdue

**Comment by boegel** [comment]
@JackPerdue Any reason you didn't use the more recent 2.12.4, which was already available at the time of your PR? (cfr. https://www.freedesktop.org/software/fontconfig/release/)

Any objections to bumping this in place to 2.12.4?

**Comment by boegel** [comment]
bumped in ~~#5073~~

**Pull request merged**
