### PR TITLE
{compiler}[GCCcore/10.3.0] Clang v12.0.1

### PR DESCRIPTION
**Pull request by jfgrimm**
(created using `eb --new-pr`)

edit (by @boegel): requires ~https://github.com/easybuilders/easybuild-easyblocks/pull/2540~

### CODE REVIEW

**Comment by Micket** [comment]
cf. #13360 
where I had a compilation error which I never got around to investigate. I see this PR excludes the libunwind part, is that what was required nowdays? I have no problems closing my PR for this if this works

**Comment by jfgrimm** [comment]
ah I missed that PR
I couldn't get Clang to build `lld` without `libunwind`, and I see further errors when using `libunwind` from an existing EC. I've also made an update to the easyblock: https://github.com/easybuilders/easybuild-easyblocks/pull/2540

**Comment by Micket** [comment]
Test report by @Micket
**FAILED**
Build succeeded for 0 out of 1 (1 easyconfigs in total)
alvis-c1 - Linux centos linux 7.9.2009, x86_64, Intel Xeon Processor (Skylake), Python 3.6.8
See https://gist.github.com/a6f97384d169d0a069cd57c2a022df3f for a full test report.

**Comment by SebastianAchilles** [comment]
@boegelbot please test @ generoso
CORE_CNT=16

**Comment by SebastianAchilles** [comment]
@boegelbot please test @ generoso
EB_ARGS="--include-easyblocks-from-pr 2540"
CORE_CNT=16

**Comment by Micket** [comment]
Test report by @Micket
Using easyblocks from PR(s) https://github.com/easybuilders/easybuild-easyblocks/pull/2540
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
alvis-c1 - Linux centos linux 7.9.2009, x86_64, Intel Xeon Processor (Skylake), Python 3.6.8
See https://gist.github.com/6a62f8cefa53f3c0f6e454c641e00a46 for a full test report.

**Review by boegel — APPROVED** [review]
lgtm

**Comment by SebastianAchilles** [comment]
Test report by @sebastianachilles
Using easyblocks from PR(s) https://github.com/easybuilders/easybuild-easyblocks/pull/2540
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
rocky8-eb - Linux rocky linux 8.4, x86_64, Intel(R) Core(TM) i7-6900K CPU @ 3.20GHz (broadwell), Python 3.6.8
See https://gist.github.com/f6cec3b592325e61469614cc91b98640 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
Using easyblocks from PR(s) https://github.com/easybuilders/easybuild-easyblocks/pull/2540
**SUCCESS**
Build succeeded for 3 out of 3 (1 easyconfigs in total)
node3600.doduo.os - Linux RHEL 8.2, x86_64, AMD EPYC 7552 48-Core Processor (zen2), Python 3.6.8
See https://gist.github.com/a91e653096d7cf0b2b14cd273e62c6f8 for a full test report.

**Comment by boegel** [comment]
Going in, thanks @jfgrimm!

**Pull request merged**
