### PR TITLE
{lib}[GCCcore/10.2.0,GCCcore/12.2.0] json-fortran v8.3.0

### PR DESCRIPTION
**Pull request by SimonPinches**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by SimonPinches** [comment]
I've kept the EB file and module names the same as the existing one but would personally have preferred to call them JSON-Fortran as used in the developer's [README](https://github.com/jacobwilliams/json-fortran).

**Comment by SimonPinches** [comment]
Note depending upon the version of pkg-config you use, it may be necessary to install usign the `--filter-env-vars=CPATH` flag to overcome the problem described in https://github.com/easybuilders/easybuild-framework/issues/3331.

**Comment by verdurin** [comment]
@boegelbot please test @ generoso

**Comment by verdurin** [comment]
Test report by @verdurin
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in total)
easybuild-c7.novalocal - Linux CentOS Linux 7.9.2009, x86_64, Intel Xeon Processor (Skylake, IBRS), Python 3.6.8
See https://gist.github.com/verdurin/074f3fc04a7604c287bf050617d36fbe for a full test report.

**Comment by ocaisa** [comment]
This has fortran code, this should be at `GCC` level if it is producing fortran modules to be consumed.

**Comment by ocaisa** [comment]
I've updated the easyconfigs upstream to reflect this: https://github.com/easybuilders/easybuild-easyconfigs/pull/19283

**Comment by ocaisa** [comment]
Ah, you actually made the correction here (apart from removing the versions that already existed upstream)!

**Review by ocaisa — APPROVED** [review]

**Comment by ocaisa** [comment]
@boegelbot please test @ generoso

**Comment by ocaisa** [comment]
@SimonPinches I would agree with you that we should have used `JSON-Fortran` when naming this. If you have the appetite to do rename PR, I would be open to reviewing it

**Comment by ocaisa** [comment]
@boegelbot please test @ generoso

**Comment by ocaisa** [comment]
@boegelbot please test @ jsc-zen2

**Comment by ocaisa** [comment]
@SimonPinches There's no licence file for the intel compilers on generoso, can you submit a test report?

**Comment by branfosj** [comment]
Test report by @branfosj
**SUCCESS**
Build succeeded for 5 out of 5 (4 easyconfigs in total)
bear-pg0105u03a - Linux RHEL 8.6, x86_64, Intel(R) Xeon(R) Platinum 8360Y CPU @ 2.40GHz (icelake), Python 3.6.8
See https://gist.github.com/branfosj/a23dd256cd0e2a0f867ae12263f4aaea for a full test report.

**Comment by ocaisa** [comment]
Thanks @branfosj , that's enough for me!

**Comment by branfosj** [comment]
@boegelbot please test @ generoso

**Comment by branfosj** [comment]
@boegelbot please test @ generoso

**Pull request merged**
