### PR TITLE
{numlib}[foss/2023a] SLEPc v3.20.1

### PR DESCRIPTION
**Pull request by furstj**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by furstj** [comment]
Requires easyblock from pr  #3229

**Comment by boegel** [comment]
@boegelbot please test @ generoso
EB_ARGS="--include-easyblocks-from-pr 3229"

**Review by boegel — APPROVED** [review]
lgtm

**Comment by boegel** [comment]
@boegelbot please test @ jsc-zen3
EB_ARGS="--include-easyblocks-from-pr 3229"

**Comment by boegel** [comment]
Going in, thanks @furstj!

**Pull request merged**
