### PR TITLE
Fix finding tk.tcl for Tk 8.6.13

### LINKED ISSUE #18858: Tkinter does not work in GCCcore/12.3.0
Tkinter does not seem to work with the new foss/2023a (GCCcore/12.3.0) toolchain.  Neither matplotlib nor our own gui works, they both fail with the error:

_tkinter.TclError: Can't find a usable tk.tcl in the following directories:
    /home/niflheim/schiotz/easybuild_2023a/skylake/software/Tcl/8.6.13-GCCcore-12.3.0/lib/tcl8.6/tk8.6 /home/niflheim/schiotz/easybuild_2023a/skylake/software/Tcl/8.6.13-GCCcore-12.3.0/lib/tk8.6 /home/niflheim/schiotz/easybuild_2023a/skylake/software/Python/3.11.3-GCCcore-12.3.0/lib/tk8.6 /home/niflheim/schiotz/easybuild_2023a/skylake/software/Python/3.11.3-GCCcore-12.3.0/lib/tk8.6 /home/niflheim/schiotz/easybuild_2023a/skylake/software/Python/lib/tk8.6 /home/niflheim/schiotz/easybuild_2023a/skylake/software/Python/3.11.3-GCCcore-12.3.0/library

Simple test script (requires that `$MPLBACKEND` is manually unset to reenable the gui):

```
import matplotlib.pyplot as plt
plt.plot([0,1], [0,1])
plt.show()
```

It crashes with the error above with `matplotlib/3.7.2-gfbf-2023a` but works with earlier toolchains.  However, the problem is not in matplotlib as the same error occurs in other programs trying to use TKinter.

### PR DESCRIPTION
**Pull request by Flamefire**
(created using `eb --new-pr`)

Fixes #18858

### CODE REVIEW

**Comment by schiotz** [comment]
I can confirm that this solves issue #18858

**Review by ocaisa — APPROVED** [review]

**Comment by ocaisa** [comment]
@boegelbot please test @ jsc-zen2

**Comment by ocaisa** [comment]
@boegelbot please test @ jsc-zen2

**Comment by boegel** [comment]
@Flamefire Is there a sanity check command we can add to catch this earlier?

**Comment by Flamefire** [comment]
I'm not aware of any as I'm not familiar with Tk

**Pull request merged**
