### PR TITLE
{bio}[foss/2021a] InterProScan_data v5.55-88.0

### PR DESCRIPTION
**Pull request by SIB-software**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by verdurin** [comment]
Test report by @verdurin
**FAILED**
Build succeeded for 0 out of 1 (1 easyconfigs in total)
easybuild-c7.novalocal - Linux CentOS Linux 7.9.2009, x86_64, Intel Xeon Processor (Skylake, IBRS), Python 3.6.8
See https://gist.github.com/35fe4a83b4a7b74571eba10c26449297 for a full test report.

**Comment by verdurin** [comment]
Test report by @verdurin
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
easybuild-c7.novalocal - Linux CentOS Linux 7.9.2009, x86_64, Intel Xeon Processor (Skylake, IBRS), Python 3.6.8
See https://gist.github.com/f6b70117a16da44757a9f9596aeda9f3 for a full test report.

**Review by verdurin — APPROVED** [review]
Looks fine.

**Comment by verdurin** [comment]
Going in, thanks @SIB-software!

**Comment by boegel** [comment]
Test report by @boegel
**FAILED**
Build succeeded for 0 out of 1 (1 easyconfigs in total)
node3138.skitty.os - Linux RHEL 8.4, x86_64, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz (skylake_avx512), Python 3.6.8
See https://gist.github.com/869ce96baa84763214c925a96bc75295 for a full test report.

**Comment by smoretti** [comment]
@boegel I think this is a disk space issue. InterProscan data need more than 100GB

**Comment by boegel** [comment]
@smoretti No, the issue is that `InterProScan_data` is trying to create a symbolic link in the `InterProScan` installation directory.
That fails in my test setup, because I have EasyBuild configured with `--read-only-installdir` (and so the `InterProScan` installation directory was made read-only once the installation completed)

**Comment by smoretti** [comment]
So how to change this?

If you install both `InterProScan` and `InterProScan_data` at the same time, does `--read-only-installdir` apply the read only mode at the end of the whole installation, or at each step?

**Comment by boegel** [comment]
@smoretti The installation directory is made read-only after each installation completes. So as soon as the `InterProScan` installation is done, that install directory will be read-only (when using `--read-only-installdir`).
If `InterProScan_data` then tries to make changes in there, that will fail (and rightfully since, since easyconfig B is not supposed to make changes in the install directory of easyconfig A).

To fix this, we should figure out why `InterProScan_data` is putting the symlink there, see if there's an alternative to doing so, and perhaps consider to bundle together `InterProScan` and `InterProScan_data` into a single easyconfig file instead.

**Comment by smoretti** [comment]
@boegel The goal was to split InterProScan code and data.

InterProScan was only provided as a single tarball with code and data for years. Now it is provided as before (a 7.4G tarball so a lot uncompressed), and as split tarballs for code and data (a request from conda I think).

Some people need the code without the data, some people need both, and some people need extra data not provided in the original tarball (another 1.2T tarball).

I was not aware of the `--read-only-installdir` option. As far as I know the data can be made accessible with a data folder in the `InterProScan` install repository (A symlink is done by `InterProScan_data`), or by updating a configuration file also in the `InterProScan` install repository.


Could you remove an old InterProScan PR #14084 ?

**Comment by boegel** [comment]
So the only way to make the `InterProScan` installation aware of where the data is, is by letting the `InterProScan_data` easyconfig modify the `InterProScan` installation? That's... unfortunate.

Isn't there an environment variable that can be set by `InterProScan_data` to specify the location of the data?
That would be way better...

**Comment by smoretti** [comment]
I checked when I did the easyconfig file if a variable exists but did not find any.

I will ask the InterProScan team...

**Comment by smoretti** [comment]
The InterProScan team told me there is no other ways to define the data directory.

However, InterProScan can load the property file from the command line and overrides the one in the `InterProScan` folder but I don't think it will solve our issue.

Possible solutions I can see, but not super clean:
- `InterProScan` creates the symlink itself to `InterProScan_data` before `InterProScan_data` is installed. It is possible as versions must match.
- `InterProScan_data` can do a chmod u+w on the `InterProScan` folder, creates the symlink, then remove the write right.

**Comment by boegel** [comment]
> The InterProScan team told me there is no other ways to define the data directory.

And are they willing to consider supporting the use of an environment variable like `$INTERPROSCAN_DATA`?

> However, InterProScan can load the property file from the command line and overrides the one in the `InterProScan` folder but I don't think it will solve our issue.

Any more details on that? Can we define an alias in the `InterProScan_data` module for the main InterProScan command that does this, for example?

> 
> Possible solutions I can see, but not super clean:
> 
>     * `InterProScan` creates the symlink itself to `InterProScan_data` before `InterProScan_data` is installed. It is possible as versions must match.

Hmm, that's worth considering I guess... That does make the assumption that both `InterProScan` and `InterProScan_data` are being installed in the same installpath, that's not necessarily true.

>     * `InterProScan_data` can do a chmod u+w on the `InterProScan` folder, creates the symlink, then remove the write right.

I would like to avoid having software A fiddle in the installation directory of software B...
Also, we shouldn't just remove the write permissions afterwards, since read-only installation directories may not be used.

**Pull request merged**
