### PR TITLE
{devel}[system] ReFrame v3.5.2

### PR DESCRIPTION
**Pull request by teojgo**

### CODE REVIEW

**Comment by migueldiascosta** [comment]
@boegelbot please test @ generoso

**Comment by victorusu** [comment]
@migueldiascosta and @boegel, why one cannot use the `source_urls` in the `exts_default_options`?
Is there any reason behind it? What's the alternative? Write the `source_url` in every single entry?  

The issue we are talking about is
```
AssertionError: 'source_urls' should not be defined in exts_default_options when using the default value in ReFrame-3.5.2.eb
```

**Comment by migueldiascosta** [comment]
@victorusu `PYPI_SOURCE` is the default value, you don´t need to set it, and it seems since https://github.com/easybuilders/easybuild-easyconfigs/pull/12456 you actually can´t set it since the tests now check that

**Review by boegel — APPROVED** [review]
lgtm

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
node2640.swalot.os - Linux centos linux 7.9.2009, x86_64, Intel(R) Xeon(R) CPU E5-2660 v3 @ 2.60GHz (haswell), Python 3.6.8
See https://gist.github.com/764fc8979068d2dd5e82afd23ceccd99 for a full test report.

**Comment by boegel** [comment]
Going in, thanks @teojgo!

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
node3100.skitty.os - Linux centos linux 7.9.2009, x86_64, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz, Python 3.6.8
See https://gist.github.com/2b4167e6fcbc7158dcca98bb4df434a8 for a full test report.

**Pull request merged**
