### PR TITLE
{phys}[foss/2019a,intel/2019a] CrystFEL v0.8.0

### PR DESCRIPTION
**Pull request by Micket**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by boegel** [comment]
@Micket Any reason not to move this to `gompi` + `iimpi` toolchains?

**Comment by Micket** [comment]
I had to remind myself what the issue was here; FFTW is at intel level, so iimpi won't work.
Do we still want to drop foss to gompi?

**Comment by boegel** [comment]
@boegelbot please test @ generoso

**Comment by Micket** [comment]
how is there 2 responses from the test build?

**Comment by boegel** [comment]
> how is there 2 responses from the test build?

Good question, I'll check what happened. Maybe the bot picked it up twice or something, it's definitely weird...

**Comment by Micket** [comment]
The failed one just hangs on a lock file though, so this PR should be OK?

**Comment by boegel** [comment]
Looks like the bot thinks the job failed to submit at the first attempt, but it actually did get submitted
```
easybuild.tools.build_log.EasyBuildError: 'cmd "EB_PR=8407 EB_ARGS= /opt/software/slurm/bin/sbatch --job-name test_PR_8407 --ntasks=4 ~/boegelbot/eb_from_pr_upload_generoso.sh" exited with exit code 1 and output:\nsbatch: error: Batch job submission failed: Socket timed out on send/recv operation\n'
```

So it got submitted twice in 5min, which explains why one failed due to a lock. So yes, this PR should be good to go I think...

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in total)
node3131.skitty.os - Linux CentOS Linux 7.9.2009, x86_64, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz (skylake_avx512), Python 2.7.5
See https://gist.github.com/73446607e37b09fb7f03e524e0ce832b for a full test report.

**Comment by boegel** [comment]
@boegelbot please test @ jsc-zen2

**Comment by Micket** [comment]
license issue for intel
== 2022-08-09 14:09:57,268 build_log.py:169 ERROR EasyBuild crashed with an error (at easybuild/easybuild-framework/easybuild/base/exceptions.py:124 in __init__): No viable license specifications found; specify 'license_file', or define $INTEL_LICENSE_FILE or $LM_LICENSE_FILE (at easybuild/easybuild-easyblocks/easybuild/easyblocks/generic/intelbase.py:287 in prepare_step)

**Comment by boegel** [comment]
Ah, right, those older Intel compilers still require a license, which we don't have for `jsc-zen2` (only for `generoso`)

**Review by boegel — APPROVED** [review]
lgtm

**Comment by boegel** [comment]
Going in, thanks @Micket!

**Pull request merged**
