### PR TITLE
remove hardcoded march=native from iq-tree code

### PR DESCRIPTION
**Pull request by mboisson**
(created using `eb --new-pr`)

### CODE REVIEW

**Review by Micket — CHANGES_REQUESTED** [review]
Couldn't you just `configopts = '-DTERRAPHAST_ARCH_NATIVE=OFF'` instead?

**Comment by mboisson** [comment]
Maybe indeed. I noticed that option after opening the PR (the patch wasn't written by me). I'll ask the author of the patch to test and will report.

**Comment by mboisson** [comment]
Confirmed that adding `-DTERRAPHASE_ARCH_NATIVE=OFF` to `configopts` works fine. Closing this PR.

**Comment by boegel** [comment]
@mboisson Should there be a new patch to always build with `-DTERRAPHASE_ARCH_NATIVE=OFF` in `configopts`, so EasyBuild is in control over the compiler options being used?

**Comment by Micket** [comment]
Surely just adding the configopts is worth not having to maintain a patch?

**Comment by mboisson** [comment]
I would just add `-DTERRAPHASE_ARCH_NATIVE=OFF` in the configopts, for each EasyConfigs. ?

**Comment by boegel** [comment]
> I would just add `-DTERRAPHASE_ARCH_NATIVE=OFF` in the configopts, for each EasyConfigs. ?

Yes, that's what I mean.

**Pull request closed without merging**
