### PR TITLE
{perf}[gompic/2020a,iimpic/2020a] OSU-Micro-Benchmarks v5.6.3

### PR DESCRIPTION
**Pull request by lexming**
(created using `eb --new-pr`)

Depends on ~~#11295~~ and ~~#11425~~

### CODE REVIEW

**Comment by verdurin** [comment]
@lexming the easyconfig for `iimpic/2020a` still apears to be missing?

**Comment by bartoldeman** [comment]
@verdurin iimpic 2020a is in #11425

**Review by boegel — APPROVED** [review]
lgtm

**Comment by boegel** [comment]
@boegelbot please test @ generoso

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in this PR)
node3404.kirlia.os - Linux centos linux 7.8.2003, x86_64, Intel(R) Xeon(R) Gold 6240 CPU @ 2.60GHz (cascadelake), Python 2.7.5
See https://gist.github.com/a9f5258a60de63ffa242704983ebc9f5 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in this PR)
node2485.golett.os - Linux centos linux 7.8.2003, x86_64, Intel(R) Xeon(R) CPU E5-2680 v3 @ 2.50GHz (haswell), Python 2.7.5
See https://gist.github.com/a2858aec77578c1b5d074838a4956e5b for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in this PR)
node3126.skitty.os - Linux centos linux 7.8.2003, x86_64, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz, Python 3.6.8
See https://gist.github.com/a6a90965b74f665c04756b0783ac9358 for a full test report.

**Comment by boegel** [comment]
Going in, thanks @lexming!

**Pull request merged**
