### PR TITLE
{vis}[foss/2019a] mayavi v4.7.1 w/ Python 3.7.2

### PR DESCRIPTION
**Pull request by akesandgren**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by akesandgren** [comment]
Test report by @akesandgren
**SUCCESS**
Build succeeded for 0 out of 0 (2 easyconfigs in this PR)
b-an04.hpc2n.umu.se - Linux ubuntu 16.04, Intel(R) Xeon(R) CPU E5-2690 v4 @ 2.60GHz, Python 2.7.12
See https://gist.github.com/7a66ccde1ac29ad25067a42be90b93a6 for a full test report.

**Comment by akesandgren** [comment]
Test report by @akesandgren
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
b-an04.hpc2n.umu.se - Linux ubuntu 16.04, Intel(R) Xeon(R) CPU E5-2690 v4 @ 2.60GHz, Python 2.7.12
See https://gist.github.com/ec5027a0d5c53bc5003190131ebe74a4 for a full test report.

**Comment by verdurin** [comment]
Test report by @verdurin
**FAILED**
Build succeeded for 0 out of 1 (1 easyconfigs in this PR)
generoso - Linux centos linux 7.6.1810, Intel(R) Xeon(R) CPU E5-2660 v4 @ 2.00GHz, Python 3.6.8
See https://gist.github.com/9c995d0d8c85b6b9f7928b7b01586004 for a full test report.

**Comment by verdurin** [comment]
```
    running gen_docs
    qt.qpa.xcb: could not connect to display
    qt.qpa.plugin: Could not load the Qt platform plugin "xcb" in "" even though it was found.
    This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

    Available platform plugins are: linuxfb, minimal, offscreen, vnc, webgl, xcb.

    Running setup.py install for mayavi: finished with status 'error'
Cleaning up...
  Removing source in /tmp/eb-p4z1nsp8/pip-req-build-nas2rn0x
Removed build tracker '/tmp/eb-p4z1nsp8/pip-req-tracker-kfe6glu9'
Command "/work/maintainers/CO7/broadwell/software/Python/3.7.2-GCCcore-8.2.0/bin/python3.7 -u -c "import setuptools, tokenize;__file__='/tmp/eb-p4z1nsp8/pip-req-build-nas2rn0x/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.r
ead().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/eb-p4z1nsp8/pip-record-3zttrcne/install-record.txt --single-version-externally-managed --prefix /work/maintainers/CO7/broadwell/software/ma
yavi/4.7.1-foss-2019a-Python-3.7.2 --compile" failed with error code -6 in /tmp/eb-p4z1nsp8/pip-req-build-nas2rn0x/
Exception information:
Traceback (most recent call last):
  File "/work/maintainers/CO7/broadwell/software/Python/3.7.2-GCCcore-8.2.0/lib/python3.7/site-packages/pip/_internal/cli/base_command.py", line 179, in main
    status = self.run(options, args)
  File "/work/maintainers/CO7/broadwell/software/Python/3.7.2-GCCcore-8.2.0/lib/python3.7/site-packages/pip/_internal/commands/install.py", line 393, in run
    use_user_site=options.use_user_site,
  File "/work/maintainers/CO7/broadwell/software/Python/3.7.2-GCCcore-8.2.0/lib/python3.7/site-packages/pip/_internal/req/__init__.py", line 57, in install_given_reqs
    **kwargs
  File "/work/maintainers/CO7/broadwell/software/Python/3.7.2-GCCcore-8.2.0/lib/python3.7/site-packages/pip/_internal/req/req_install.py", line 945, in install
    spinner=spinner,
  File "/work/maintainers/CO7/broadwell/software/Python/3.7.2-GCCcore-8.2.0/lib/python3.7/site-packages/pip/_internal/utils/misc.py", line 761, in call_subprocess
    % (command_desc, proc.returncode, cwd))
pip._internal.exceptions.InstallationError: Command "/work/maintainers/CO7/broadwell/software/Python/3.7.2-GCCcore-8.2.0/bin/python3.7 -u -c "import setuptools, tokenize;__file__='/tmp/eb-p4z1nsp8/pip-req-build-nas2rn0x/setup.py';f=getatt
r(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/eb-p4z1nsp8/pip-record-3zttrcne/install-record.txt --single-version-externally-managed --prefix
 /work/maintainers/CO7/broadwell/software/mayavi/4.7.1-foss-2019a-Python-3.7.2 --compile" failed with error code -6 in /tmp/eb-p4z1nsp8/pip-req-build-nas2rn0x/
 (at easybuild/tools/run.py:529 in parse_cmd_output)
== 2019-12-10 08:37:44,895 easyblock.py:3094 WARNING build failed (first 300 chars): cmd " pip install --prefix=/work/maintainers/CO7/broadwell/software/mayavi/4.7.1-foss-2019a-Python-3.7.2  --verbose  --no-deps  --ignore-installed  --no-
build-isolation  ." exited with exit code 1 and output:
```

**Comment by akesandgren** [comment]
Need to build it with access to X-display.

**Comment by verdurin** [comment]
@akesandgren please mention that as a comment in the easyconfig

**Comment by akesandgren** [comment]
Hold off on this one a little while...

**Comment by akesandgren** [comment]
Test report by @akesandgren
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
b-an03.hpc2n.umu.se - Linux ubuntu 16.04, Intel(R) Xeon(R) CPU E5-2690 v4 @ 2.60GHz, Python 2.7.12
See https://gist.github.com/802283d7b007e0cf2bf9396b5fa15f71 for a full test report.

**Comment by akesandgren** [comment]
Now it works without connection to X server for installing. HYad forgotten about #7345

**Comment by migueldiascosta** [comment]
Test report by @migueldiascosta
**FAILED**
Build succeeded for 0 out of 1 (1 easyconfigs in this PR)
generoso - Linux centos linux 7.6.1810, Intel(R) Xeon(R) CPU E5-2660 v4 @ 2.00GHz, Python 3.6.8
See https://gist.github.com/80cd5fa7b3d928b2113b4c1b18533b0c for a full test report.

**Comment by migueldiascosta** [comment]
```
cmd "pip check" exited with exit code 1 and output:
mayavi 4.7.1 requires vtk, which is not installed.
```

**Comment by boegel** [comment]
@migueldiascosta Looks like you tested without the fix included in #9386?

**Comment by smoors** [comment]
Test report by @smoors
**SUCCESS**
Build succeeded for 2 out of 2 (1 easyconfigs in this PR)
node375.hydra.os - Linux centos linux 7.7.1908, Intel(R) Xeon(R) Gold 6148 CPU @ 2.40GHz, Python 2.7.5
See https://gist.github.com/62df2cc46669222d2b0b35e0e5cadffb for a full test report.

**Comment by smoors** [comment]
Going in, thanks @akesandgren!

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
node3112.skitty.os - Linux centos linux 7.7.1908, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz, Python 3.6.8
See https://gist.github.com/c6784597a2e8536d691348efe8c7ed62 for a full test report.

**Pull request merged**
