### PR TITLE
{data,lib}[GCCcore/11.2.0,foss/2021b] CFITSIO v3.49, ROOT v6.24.06 w/ Python 3.9.6

### PR DESCRIPTION
**Pull request by ItIsI-Orient**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by ItIsI-Orient** [comment]
Test report by @ItIsI-Orient
**FAILED**
Build succeeded for 1 out of 2 (2 easyconfigs in total)
node3285.victini.os - Linux CentOS Linux 7.9.2009, x86_64, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz, Python 3.6.8
See https://gist.github.com/74a5f93a5a6ad1cd9c2ea0e251c443dd for a full test report.

**Comment by ItIsI-Orient** [comment]
Test report by @ItIsI-Orient
**FAILED**
Build succeeded for 1 out of 2 (2 easyconfigs in total)
node3285.victini.os - Linux CentOS Linux 7.9.2009, x86_64, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz, Python 3.6.8
See https://gist.github.com/537ca6a8f3fc4c2d71c51dc606b7f8c7 for a full test report.

**Comment by ItIsI-Orient** [comment]
Test report by @ItIsI-Orient
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in total)
node3285.victini.os - Linux CentOS Linux 7.9.2009, x86_64, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz, Python 3.6.8
See https://gist.github.com/e9f64c2a88d67281af56cfe07b274720 for a full test report.

**Comment by boegel** [comment]
This may need some more work, to avoid using C++23 standard for GATE in https://github.com/easybuilders/easybuild-easyconfigs/pull/14869

**Review by boegel — APPROVED** [review]
lgtm

**Comment by boegel** [comment]
@boegelbot please test @ generoso
CORE_CNT=16

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 5 out of 5 (2 easyconfigs in total)
node2677.swalot.os - Linux UNKNOWN UNKNOWN, x86_64, Intel(R) Xeon(R) CPU E5-2660 v3 @ 2.60GHz (haswell), Python 3.6.8
See https://gist.github.com/70d35ed6afad80f34d2c25a691667d14 for a full test report.

**Comment by boegel** [comment]
@boegelbot please test @ jsc-zen2

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in total)
node3523.doduo.os - Linux UNKNOWN UNKNOWN, x86_64, AMD EPYC 7552 48-Core Processor (zen2), Python 3.6.8
See https://gist.github.com/a1ee34159e5f06c99259bafdeff469e6 for a full test report.

**Comment by boegel** [comment]
Going in, thanks @ItIsI-Orient!

**Comment by boegel** [comment]
Going in, thanks @ItIsI-Orient!

**Comment by boegel** [comment]
failing installation was due to known issue with ROOT, see https://github.com/easybuilders/easybuild-easyblocks/issues/2023

**Pull request merged**
