### PR TITLE
{data}[fosscuda/2020b] netCDF v4.7.4, GDAL v3.2.1, R v4.0.4 w/ Python 3.8.6

### PR DESCRIPTION
**Pull request by dithwick**
(created using `eb --new-pr`)

### CODE REVIEW

**Review by branfosj — APPROVED** [review]
lgtm

**Comment by branfosj** [comment]
@boegelbot please test @ generoso

**Comment by branfosj** [comment]
I've set off a test report on generoso for this, but this may fail due to a lack of a GPU. I cannot remember if any of the GPU libraries in R needs a GPU during the build process.

**Comment by boegel** [comment]
Test report by @boegel
**FAILED**
Build succeeded for 4 out of 5 (3 easyconfigs in total)
node3301.joltik.os - Linux centos linux 7.9.2009, x86_64, Intel(R) Xeon(R) Gold 6242 CPU @ 2.80GHz (cascadelake), Python 3.6.8
See https://gist.github.com/c9a48b44074c1d4a8530e171a447d039 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 3 out of 3 (3 easyconfigs in total)
node3301.joltik.os - Linux centos linux 7.9.2009, x86_64, Intel(R) Xeon(R) Gold 6242 CPU @ 2.80GHz (cascadelake), Python 3.6.8
See https://gist.github.com/d698bed0ab8e2a20ae82ec889d6c4716 for a full test report.

**Comment by boegel** [comment]
Going in, thanks @dithwick!

**Pull request merged**
