### PR TITLE
rename and update AutoDock-Vina v1.1.2 and v1.2.3

### PR DESCRIPTION
**Pull request by lexming**
(created using `eb --new-pr`)

Update of AutoDock-Vina with builds from source:
* AutoDock-Vina-1.2.3-GCC-10.3.0.eb: provides binaries
* AutoDock-Vina-1.2.3-foss-2021a-Python-3.9.5.eb: provides binaries + python bindings

Existing easyconfig for v1.1.2 renamed to AutoDock-Vina to fit the name upstream and also updated with new sources.

### CODE REVIEW

**Comment by lexming** [comment]
@boegelbot please test @ generoso
EB_ARGS="--insecure-download"

**Comment by lexming** [comment]
Test report by @lexming
**SUCCESS**
Build succeeded for 3 out of 3 (3 easyconfigs in total)
node300.hydra.os - Linux centos linux 7.9.2009, x86_64, Intel(R) Xeon(R) Gold 6148 CPU @ 2.40GHz, Python 2.7.5
See https://gist.github.com/067ff9d9b56fc35746959f5a6799fd09 for a full test report.

**Comment by lexming** [comment]
@boegelbot please test @ generoso
EB_ARGS="--insecure-download"

**Comment by lexming** [comment]
Test report by @lexming
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in total)
node303.hydra.os - Linux centos linux 7.9.2009, x86_64, Intel(R) Xeon(R) Gold 6148 CPU @ 2.40GHz, Python 2.7.5
See https://gist.github.com/13375562327651a77adf7358b45aa0d2 for a full test report.

**Comment by lexming** [comment]
@boegelbot please test @ generoso
EB_ARGS="--insecure-download"

**Comment by lexming** [comment]
Test report by @lexming
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in total)
node303.hydra.os - Linux centos linux 7.9.2009, x86_64, Intel(R) Xeon(R) Gold 6148 CPU @ 2.40GHz, Python 2.7.5
See https://gist.github.com/eec70fc88174f763a2835dde66196ac6 for a full test report.

**Comment by branfosj** [comment]
Test report by @branfosj
**SUCCESS**
Build succeeded for 3 out of 3 (2 easyconfigs in total)
bear-pg0212u15b.bear.cluster - Linux RHEL 8.5, x86_64, Intel(R) Xeon(R) CPU E5-2640 v4 @ 2.40GHz (broadwell), 1 x NVIDIA Tesla P100-PCIE-16GB, 470.57.02, Python 3.6.8
See https://gist.github.com/ccbf5da1b0c5477e8fe4ec45eb4194fa for a full test report.

**Review by branfosj — APPROVED** [review]
lgtm

**Comment by branfosj** [comment]
Going in, thanks @lexming!

**Comment by lexming** [comment]
Test report by @lexming
**FAILED**
Build succeeded for 1 out of 2 (2 easyconfigs in total)
node303.hydra.os - Linux centos linux 7.9.2009, x86_64, Intel(R) Xeon(R) Gold 6148 CPU @ 2.40GHz, Python 2.7.5
See https://gist.github.com/e795d0b8bf3e1aa6bf5218cc31babe11 for a full test report.

**Pull request merged**
