### PR TITLE
{devel}[system/system] ant v1.10.12

### PR DESCRIPTION
**Pull request by SimonPinches**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by SimonPinches** [comment]
I did wonder whether this EB file should just be named `ant-1.10.12.eb` and not have any Java dependency since then there would be no need for `ant-1.10.12-Java-17.eb`?

**Comment by Micket** [comment]
> I did wonder whether this EB file should just be named `ant-1.10.12.eb` and not have any Java dependency since then there would be no need for `ant-1.10.12-Java-17.eb`?

I don't understand what you mean at all here. It does definitely depend on Java? and I see no connection as to how `ant-1.10.12-Java-17.eb` makes any difference one way or another.

**Comment by SimonPinches** [comment]
What I meant is that it does not depend upon a specific version of Java for installation (it's just a PackedBinary).  If this module were just called `ant-1.10.12.eb` then the user could select the version of Java without the need for separate `ant-1.10.12-Java-XX.eb` modules.

**Comment by Micket** [comment]
Right, i see where you are coming from. The same applies to a lot of java apps. 
Skipping the dep means that
1. it won't work for a user that just `module load ant`, not terrible, something we've tried to avoid elsewhere
2. also means we can't do sanity checks of installs. E.g. had `ant` been introduced now, we've probably asked for a sanity_check_command for `ant -h` 

Benefit is not having to double up on these, though in practice, we'll likely just have everything Java-11 as much as possible, until we switch to having Java-17 as much as possible, so..

I'd like other maintainers opinion on this.

**Comment by branfosj** [comment]
I _know_ my users will grumble that that the 'software is broken' if no Java is loaded by `ant`. I am wondering if there is a solution using `multideps`.

**Review by boegel — APPROVED** [review]
lgtm

**Comment by boegel** [comment]
@boegelbot please test @ generoso

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
node3107.skitty.os - Linux RHEL 8.4, x86_64, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz (skylake_avx512), Python 3.6.8
See https://gist.github.com/3ad730a96afd81c34e9357bbccc507d2 for a full test report.

**Comment by boegel** [comment]
Going in, thanks @SimonPinches!

**Pull request merged**
