### PR TITLE
{data}[foss/2021a] deepmedic v0.8.2 w/ Python 3.9.5

### PR DESCRIPTION
**Pull request by crubb**
(created using `eb --new-pr`)

Requires
* #14947

### CODE REVIEW

**Comment by migueldiascosta** [comment]
@boegelbot please test @ generoso

**Comment by migueldiascosta** [comment]
@boegelbot please test @ jsc-zen2

**Comment by crubb** [comment]
I had - and then forgot about it. sanity check added. Thank you!

**Comment by migueldiascosta** [comment]
Test report by @migueldiascosta
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
c2dhpc - Linux CentOS Linux 7.6.1810, x86_64, AMD EPYC 7601 32-Core Processor (zen), Python 2.7.5
See https://gist.github.com/a9b8badc85a89b37ee9a8d1107855f52 for a full test report.

**Review by migueldiascosta — APPROVED** [review]
lgtm

**Comment by migueldiascosta** [comment]
Going in, thanks @crubb!

**Pull request merged**
