### PR TITLE
R-3.5.1-foss-2018b: fix uroot installation

### PR DESCRIPTION
**Pull request by smoors**
(created using `eb --new-pr`)
don't search for cuda if CUDA_HOME is not set

### CODE REVIEW

**Comment by boegel** [comment]
@smoors How did this problem manifest itself exactly?

**Comment by smoors** [comment]
we get this error on our site: `uroot make: /usr/local/cuda-9.2/bin/nvcc: Command not found`.
uroot searches for (and finds) a cuda directory, but nvcc is not in there.
the cuda dir is necessary for Torque.
normally when a CUDA module is loaded, `CUDA_HOME` is set, so there should be no need to set it if CUDA is not loaded.

**Comment by migueldiascosta** [comment]
Test report by @migueldiascosta
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
grc-cluster1 - Linux centos 6.10, Intel(R) Xeon(R) CPU E5-2640 0 @ 2.50GHz, Python 2.7.14
See https://gist.github.com/dd08146c94b37ee6bb0a5443d751ded7 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
node2419.golett.os - Linux centos linux 7.5.1804, Intel(R) Xeon(R) CPU E5-2680 v3 @ 2.50GHz, Python 2.7.5
See https://gist.github.com/d04a40c6d65440ef57aabc66031e44ad for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
node2062.delcatty.os - Linux centos linux 7.5.1804, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.7.5
See https://gist.github.com/e25057a34cd9c2cdc611803807988bee for a full test report.

**Comment by boegel** [comment]
Going in, thanks @smoors!

**Pull request merged**
