### PR TITLE
{data}[foss/2021a] Arrow v8.0.0

### PR DESCRIPTION
**Pull request by pberthier**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by pberthier** [comment]
The ckecks failed because the dependency pkgconf-1.8.0-GCCcore-10.3.0.eb was missing, but this is now in.  However, I cannot find how to re-run the checks.

**Comment by SebastianAchilles** [comment]
The branch this PR is based on does not yet contain `pkgconf` from https://github.com/easybuilders/easybuild-easyconfigs/pull/18799

In order sync the branch with the develop branch you can use this command:
```
eb --sync-pr-with-develop=18800
```

**Comment by SebastianAchilles** [comment]
@boegelbot please test @ jsc-zen2

**Comment by SebastianAchilles** [comment]
@boegelbot please test @ generoso

**Comment by SebastianAchilles** [comment]
Test report by @sebastianachilles
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
zen2-rockylinux-88 - Linux Rocky Linux 8.8, x86_64, AMD EPYC 7452 32-Core Processor (zen2), Python 3.6.8
See https://gist.github.com/SebastianAchilles/b9939a7a5cac168db194e91376327ce0 for a full test report.

**Review by SebastianAchilles — APPROVED** [review]
lgtm

**Comment by SebastianAchilles** [comment]
Going in, thanks @pberthier!

**Pull request merged**
