### PR TITLE
{lib}[GCCcore/12.3.0] geopandas v0.14.2, psycopg2 v2.9.9, SQLAlchemy v2.0.25

### PR DESCRIPTION
**Pull request by lexming**
(created using `eb --new-pr`)

* [x] https://github.com/easybuilders/easybuild-easyconfigs/pull/19777

Notable changes:
* adding (optional) deps for db access to geopandas: psycopg2 and SQLAlchemy
* adding new easyconfig for SQLAlchemy with the usual SQLite backend and another one for PostgreSQL (and by request also `alembic`)

### CODE REVIEW

**Comment by lexming** [comment]
@boegelbot: please test @ generoso

**Comment by lexming** [comment]
@boegelbot please test @ jsc-zen3

**Comment by lexming** [comment]
@boegelbot: please test @ generoso

**Comment by lexming** [comment]
@boegelbot please test @ jsc-zen3

**Comment by lexming** [comment]
@boegelbot: please test @ generoso

**Comment by lexming** [comment]
@boegelbot please test @ jsc-zen3

**Comment by jfgrimm** [comment]
Test report by @jfgrimm
**FAILED**
Build succeeded for 4 out of 6 (3 easyconfigs in total)
gpu22.viking2.yor.alces.network - Linux Rocky Linux 8.8, x86_64, AMD EPYC 7413 24-Core Processor, 2 x NVIDIA NVIDIA H100 PCIe, 535.86.10, Python 3.6.8
See https://gist.github.com/jfgrimm/8b4ead00ca149bc918ee8fbd7e36b8be for a full test report.

**Comment by lexming** [comment]
@jfgrimm your test system is missing the changes from https://github.com/easybuilders/easybuild-easyconfigs/pull/19777

**Comment by verdurin** [comment]
Test report by @verdurin
**SUCCESS**
Build succeeded for 7 out of 7 (3 easyconfigs in total)
easybuild-c7.novalocal - Linux CentOS Linux 7.9.2009, x86_64, Intel Xeon Processor (Skylake, IBRS), Python 3.6.8
See https://gist.github.com/verdurin/f16e13e61e1a7cad93d4e8b8abef4182 for a full test report.

**Comment by lexming** [comment]
@verdurin may I get a merge here, pretty please :)

**Comment by jfgrimm** [comment]
Test report by @jfgrimm
**SUCCESS**
Build succeeded for 3 out of 3 (3 easyconfigs in total)
node113.viking2.yor.alces.network - Linux Rocky Linux 8.8, x86_64, AMD EPYC 7643 48-Core Processor, Python 3.6.8
See https://gist.github.com/jfgrimm/589d1781bee4f134c3741d72c064fb60 for a full test report.

**Review by jfgrimm — APPROVED** [review]
lgtm

**Comment by jfgrimm** [comment]
Going in, thanks @lexming!

**Comment by lexming** [comment]
Thanks!

**Pull request merged**
