### PR TITLE
{math}[GCCcore/11.3.0] SageMath v9.8

### PR DESCRIPTION
**Pull request by terjekv**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by casparvl** [comment]
Test report by @casparvl
**FAILED**
Build succeeded for 0 out of 1 (1 easyconfigs in total)
tcn502.local.snellius.surf.nl - Linux Rocky Linux 8.7, x86_64, AMD EPYC 7H12 64-Core Processor, Python 3.6.8
See https://gist.github.com/21ea24a3f181966a01c0958579d60972 for a full test report.

**Comment by casparvl** [comment]
```
[mpfr-4.0.1.p0] rm -rf $backupdir; exit $rc
[mpfr-4.0.1.p0] /scratch-nvme/1/casparl/generic/software/SageMath/9.8-GCCcore-11.3.0/var/tmp/sage/build/mpfr-4.0.1.p0/src/missing: line 81: makeinfo: command not found
[mpfr-4.0.1.p0] WARNING: 'makeinfo' is missing on your system.
[mpfr-4.0.1.p0]          You should only need it if you modified a '.texi' file, or
[mpfr-4.0.1.p0]          any other file indirectly affecting the aspect of the manual.
[mpfr-4.0.1.p0]          You might want to install the Texinfo package:
[mpfr-4.0.1.p0]          <http://www.gnu.org/software/texinfo/>
[mpfr-4.0.1.p0]          The spurious makeinfo call might also be the consequence of
[mpfr-4.0.1.p0]          using a buggy 'make' (AIX, DU, IRIX), in which case you might
[mpfr-4.0.1.p0]          want to install GNU make:
[mpfr-4.0.1.p0]          <http://www.gnu.org/software/make/>
[mpfr-4.0.1.p0] make[6]: *** [Makefile:379: mpfr.info] Error 127
[mpfr-4.0.1.p0] make[5]: *** [Makefile:498: all-recursive] Error 1
```
I think this should maybe use `texinfo` as build dependency?

**Comment by terjekv** [comment]
Ah, right. I'll make a texinfo update as well.  :)

**Comment by terjekv** [comment]
Requires https://github.com/easybuilders/easybuild-easyconfigs/pull/17543

**Comment by casparvl** [comment]
Errr... now that the `texinfo` thing is no longer a problem, I get a new issue:

```
[mpfr-4.0.1.p0] /usr/bin/ld: /gpfs/admin/_hpc/sw/arch/AMD-ZEN2/RHEL8/EB_production/2022/software/GCCcore/11.3.0/bin/../lib/gcc/x86_64-pc-linux-gnu/11.3.0/libgcc.a(_muldi3.o): unable to initialize dec
ompress status for section .debug_info
[mpfr-4.0.1.p0] /usr/bin/ld: /gpfs/admin/_hpc/sw/arch/AMD-ZEN2/RHEL8/EB_production/2022/software/GCCcore/11.3.0/bin/../lib/gcc/x86_64-pc-linux-gnu/11.3.0/libgcc.a(_muldi3.o): unable to initialize dec
ompress status for section .debug_info
[mpfr-4.0.1.p0] /usr/bin/ld: /gpfs/admin/_hpc/sw/arch/AMD-ZEN2/RHEL8/EB_production/2022/software/GCCcore/11.3.0/bin/../lib/gcc/x86_64-pc-linux-gnu/11.3.0/libgcc.a(addtf3.o): unable to initialize deco
mpress status for section .debug_info
[mpfr-4.0.1.p0] /usr/bin/ld: /gpfs/admin/_hpc/sw/arch/AMD-ZEN2/RHEL8/EB_production/2022/software/GCCcore/11.3.0/bin/../lib/gcc/x86_64-pc-linux-gnu/11.3.0/libgcc.a(addtf3.o): unable to initialize deco
mpress status for section .debug_info
[mpfr-4.0.1.p0] /gpfs/admin/_hpc/sw/arch/AMD-ZEN2/RHEL8/EB_production/2022/software/GCCcore/11.3.0/bin/../lib/gcc/x86_64-pc-linux-gnu/11.3.0/libgcc.a: error adding symbols: File format not recognized
[mpfr-4.0.1.p0] collect2: error: ld returned 1 exit status
[mpfr-4.0.1.p0] make[7]: *** [Makefile:548: libmpfr.la] Error 1
[mpfr-4.0.1.p0] make[6]: *** [Makefile:476: all] Error 2
[mpfr-4.0.1.p0] make[5]: *** [Makefile:498: all-recursive] Error 1
[mpfr-4.0.1.p0] ***************************************************************************************************
[mpfr-4.0.1.p0] Error building mpfr-4.0.1.p0
```

**Comment by casparvl** [comment]
Looking at the configure: is it normal that `SageMath` tries to install almost a full software stack? xD

```
## ----------------------------------------------------------------------- ##
## Build status for each package:                                          ##
## ----------------------------------------------------------------------- ##
4ti2:                           no suitable system package; optional, use "./configure --enable-4ti2" to install SPKG version 1.6.7.p0
admcycles:                      optional pip package; use "./sage -i admcycles" to install
alabaster:                      standard, SPKG version 0.7.12 will be installed
antic:                          optional, use "./configure --enable-antic" to install SPKG version 0.2.5
appdirs:                        no suitable system package; standard, SPKG version 1.4.4 will be installed
appnope:                        standard, SPKG version 0.1.3 will be installed
arb:                            no suitable system package; standard, SPKG version 2.22.1 will be installed
argon2_cffi:                    standard, SPKG version 21.3.0 will be installed
asttokens:                      standard, SPKG version 2.1.0 will be installed
attrs:                          standard, SPKG version 22.1.0 will be installed
auditwheel_or_delocate:         optional pip package; use "./sage -i auditwheel_or_delocate" to install
awali:                          experimental, use "./configure --enable-awali" to install SPKG version 1.0.2-190218
babel:                          standard, SPKG version 2.11.0 will be installed
backcall:                       standard, SPKG version 0.2.0 will be installed
backports_zoneinfo:             standard, SPKG version 0.2.1 will be installed
barvinok:                       experimental, use "./configure --enable-barvinok" to install SPKG version 0.41.1
beautifulsoup4:                 standard, SPKG version 4.11.1 will be installed
beniget:                        standard, SPKG version 0.4.1 will be installed
benzene:                        optional, use "./configure --enable-benzene" to install SPKG version 20130630
biopython:                      optional pip package; use "./sage -i biopython" to install
bleach:                         standard, SPKG version 5.0.1 will be installed
bliss:                          optional, use "./configure --enable-bliss" to install SPKG version 0.73+debian-1+sage-2016-08-02.p0
boost_cropped:                  using system package; SPKG will not be installed
brial:                          no suitable system package; standard, SPKG version 1.2.8 will be installed
buckygen:                       optional, use "./configure --enable-buckygen" to install SPKG version 1.1
bzip2:                          using system package; SPKG will not be installed
cbc:                            no suitable system package; optional, use "./configure --enable-cbc" to install SPKG version 2.9.4.p0
ccache:                         optional, use "./configure --enable-ccache" to install SPKG version 3.3.4
cddlib:                         no suitable system package; standard, SPKG version 0.94m will be installed
certifi:                        standard, SPKG version 2022.9.24 will be installed
cffi:                           standard, SPKG version 1.15.1 will be installed
charset_normalizer:             standard, SPKG version 2.1.1 will be installed
cliquer:                        no suitable system package; standard, SPKG version 1.22 will be installed
cmake:                          using system package; SPKG will not be installed
cocoalib:                       experimental, use "./configure --enable-cocoalib" to install SPKG version 0.99564
combinatorial_designs:          standard, SPKG version 20140630.p0 will be installed
configure:                      base, use "./configure --enable-configure" to install SPKG version 104dde9eaa8231e4f0755c6855c1eabb43239dec
contourpy:                      standard, SPKG version 1.0.6 will be installed
conway_polynomials:             standard, SPKG version 0.5 will be installed
coxeter3:                       no suitable system package; optional, use "./configure --enable-coxeter3" to install SPKG version 8ac9c71723c8ca57a836d6381aed125261e44e9e.p0
cppy:                           standard, SPKG version 1.2.1 will be installed
cryptominisat:                  optional, use "./configure --enable-cryptominisat" to install SPKG version 5.8.0
csdp:                           optional, use "./configure --enable-csdp" to install SPKG version 6.2.p1
cunningham_tables:              optional, use "./configure --enable-cunningham_tables" to install SPKG version 1.0
curl:                           using system package; SPKG will not be installed
cvxopt:                         standard, SPKG version 1.3.0 will be installed
cycler:                         standard, SPKG version 0.11.0 will be installed
cylp:                           optional, use "./configure --enable-cylp" to install SPKG version 0.91.4
cypari:                         standard, SPKG version 2.1.3 will be installed
cysignals:                      standard, SPKG version 1.11.2 will be installed
cython:                         standard, SPKG version 0.29.32.p2 will be installed
...
m4ri:                           no suitable system package; standard, SPKG version 20200115 will be installed
m4rie:                          no suitable system package; standard, SPKG version 20200115 will be installed
markupsafe:                     standard, SPKG version 2.1.1 will be installed
mathics:                        optional, use "./configure --enable-mathics" to install SPKG version 4.0.0
mathics_scanner:                optional, use "./configure --enable-mathics_scanner" to install SPKG version 1.2.4
mathjax:                        standard, SPKG version 3.2.0 will be installed
matplotlib:                     standard, SPKG version 3.6.2 will be installed
matplotlib_inline:              standard, SPKG version 0.1.6 will be installed
maxima:                         standard, SPKG version 5.45.0.p0 will be installed
mcqd:                           optional, use "./configure --enable-mcqd" to install SPKG version 1.0.p0
meataxe:                        optional, use "./configure --enable-meataxe" to install SPKG version 1.0.1
memory_allocator:               standard, SPKG version 0.1.3 will be installed
meson:                          no suitable system package; standard, SPKG version 0.63.3 will be installed
meson_python:                   standard, SPKG version 0.11.0 will be installed
mistune:                        standard, SPKG version 2.0.4 will be installed
modular_decomposition:          experimental, use "./configure --enable-modular_decomposition" to install SPKG version 20100607
modular_resolution:             optional, use "./configure --enable-modular_resolution" to install SPKG version 1.1
mpc:                            no suitable system package; standard, SPKG version 1.1.0 will be installed
mpfi:                           no suitable system package; standard, SPKG version 1.5.2 will be installed
mpfr:                           no suitable system package; standard, SPKG version 4.0.1.p0 will be installed
mpfrcx:                         optional, use "./configure --enable-mpfrcx" to install SPKG version 0.5
mpmath:                         standard, SPKG version 1.2.1 will be installed
msolve:                         optional, use "./configure --enable-msolve" to install SPKG version 0.4.4+sage-2022-09-11
nauty:                          no suitable system package; standard, SPKG version 27r1.p1 will be installed
nbclient:                       standard, SPKG version 0.7.0 will be installed
nbconvert:                      standard, SPKG version 7.2.3 will be installed
nbformat:                       standard, SPKG version 5.7.0 will be installed
ncurses:                        using system package; SPKG will not be installed
nest_asyncio:                   standard, SPKG version 1.5.6 will be installed
networkx:                       standard, SPKG version 2.8.8 will be installed
...
```
I mean, maybe this is where the problem comes from: I'm in a toolchain, and it's just happily building almost a complete other toolchain itself :S

**Comment by casparvl** [comment]
Shouldn't we just provide it with a ton of modules as dependencies...? (including the problematic MPFR)

**Comment by terjekv** [comment]
Sage is very self-contained. It's bioconductor for mathematicians. I wouldn't dare try to reimplement its bindings with external (module-based) dependencies. Sadly. :(

**Comment by casparvl** [comment]
Yeah, that's also true. In that case: any idea what went wrong on my system? I'm assuming it builds for you? Since it's complaining about a static library from GCC, I'm surprised - that should be identical across our two builds (except maybe for optimization options and stuff). I guess I could try to build with a generic optarch or something, just to see if that works. It doesn't really answer _why_ it goes wrong, but still...

**Comment by casparvl** [comment]
Hm, my `ld --version` lists `2.30-117-el8`. Old stuff :) If you add binutils, I'll retry.

**Comment by casparvl** [comment]
Btw, seeing how much is in this build: how long does it take, approximately? :D

**Comment by casparvl** [comment]
Just pushed a binutils to see if it helps (hope you don't mind @terjekv )

**Comment by casparvl** [comment]
Test report by @casparvl
**FAILED**
Build succeeded for 0 out of 1 (1 easyconfigs in total)
tcn80.local.snellius.surf.nl - Linux Rocky Linux 8.7, x86_64, AMD EPYC 7H12 64-Core Processor, Python 3.6.8
See https://gist.github.com/d7124895f71e3f024f56742bdb9e4b8f for a full test report.

**Comment by casparvl** [comment]
Getting further than before, but I think I also need `Automake`...
```
[givaro-4.1.1] /scratch-nvme/1/casparl/generic/software/SageMath/9.8-GCCcore-11.3.0/var/tmp/sage/build/givaro-4.1.1/src/build-aux/missing: line 81: automake-1.15: command not found
[givaro-4.1.1] WARNING: 'automake-1.15' is missing on your system.
[givaro-4.1.1]          You should only need it if you modified 'Makefile.am' or
[givaro-4.1.1]          'configure.ac' or m4 files included by 'configure.ac'.
[givaro-4.1.1]          The 'automake' program is part of the GNU Automake package:
[givaro-4.1.1]          <http://www.gnu.org/software/automake>
[givaro-4.1.1]          It also requires GNU Autoconf, GNU m4 and Perl in order to run:
[givaro-4.1.1]          <http://www.gnu.org/software/autoconf>
[givaro-4.1.1]          <http://www.gnu.org/software/m4/>
[givaro-4.1.1]          <http://www.perl.org/>
```

**Comment by casparvl** [comment]
Test report by @casparvl
**FAILED**
Build succeeded for 0 out of 1 (1 easyconfigs in total)
tcn80.local.snellius.surf.nl - Linux Rocky Linux 8.7, x86_64, AMD EPYC 7H12 64-Core Processor, Python 3.6.8
See https://gist.github.com/c8652dee2cb0b8695340fba7766f3aff for a full test report.

**Comment by casparvl** [comment]
Test report by @casparvl
**FAILED**
Build succeeded for 0 out of 4 (1 easyconfigs in total)
tcn80.local.snellius.surf.nl - Linux Rocky Linux 8.7, x86_64, AMD EPYC 7H12 64-Core Processor, Python 3.6.8
See https://gist.github.com/9513475d5c1edf8b7182fd2d013b4106 for a full test report.

**Comment by casparvl** [comment]
Ugh... Time to call it a night, my Automake gives erros when installing...
```
  GEN      bin/automake
  GEN      bin/aclocal
  GEN      doc/aclocal.1
  GEN      doc/automake.1
  GEN      runtest
  GEN      t/ax/cc-no-c-o
  GEN      t/ax/shell-no-trail-bslash
  GEN      lib/Automake/Config.pm
  GEN      t/ax/test-defs.sh
  GEN      doc/aclocal-1.15.1
  GEN      doc/automake-1.15.1
help2man: can't get `--help' info from aclocal-1.15
Try `--no-discard-stderr' if option outputs to stderr
help2man: can't get `--help' info from automake-1.15
Try `--no-discard-stderr' if option outputs to stderr
make: *** [Makefile:3687: doc/aclocal-1.15.1] Error 127
make: *** Waiting for unfinished jobs....
make: *** [Makefile:3689: doc/automake-1.15.1] Error 127
```

**Comment by terjekv** [comment]
@casparvl What do you want to do with this? (Apart from liberally applying C4). :)

**Comment by casparvl** [comment]
> Apart from liberally applying C4

Haha, yes, this ^^

On a more serious note: I'm not sure. It seems to have a pretty strict dependency on a particular version of binutils, automake, etc. So normally I'd say: those need to come from EasyBuild _or_ we need to be able to specify those as `os_dependencies` (but I don't think we can require particular versions in `os_dependencies`, can we?). However, I haven't ben able to get the first option to work... I'm willing to give it another try, but don't have a _ton_ of time to spend on this. 

In the meantime, maybe we can run some other test reports, see if I'm the odd one out, or you are ;-) I'll trigger the bot. If you have access to other systems from which you can upload test reports, please do.

**Comment by casparvl** [comment]
Aaaargghh, so I build an Automake-1.15.1 (because AM-1.15 wouldn't built with my OS because of https://github.com/easybuilders/easybuild-easyconfigs/issues/1822 ). Now, it continues for longer, but I get:

```
[gengetopt-2.23] /usr/bin/bash: gengetopt: command not found
[gengetopt-2.23] make[5]: *** [Makefile:1250: cmdline.c] Error 127
...
[gengetopt-2.23] ************************************************************************
[gengetopt-2.23] Error building package gengetopt-2.23
[gengetopt-2.23] ************************************************************************
[gengetopt-2.23] Please email sage-devel (http://groups.google.com/group/sage-devel)
[gengetopt-2.23] explaining the problem and including the log files
[gengetopt-2.23]   /gpfs/nvme1/1/casparl/generic/software/SageMath/9.8-GCCcore-11.3.0/sage-9.8/logs/pkgs/gengetopt-2.23.log
[gengetopt-2.23] and
[gengetopt-2.23]   /gpfs/nvme1/1/casparl/generic/software/SageMath/9.8-GCCcore-11.3.0/sage-9.8/config.log
[gengetopt-2.23] Describe your computer, operating system, etc.
[gengetopt-2.23] If you want to try to fix the problem yourself, *don't* just cd to
[gengetopt-2.23] /scratch-nvme/1/casparl/generic/software/SageMath/9.8-GCCcore-11.3.0/var/tmp/sage/build/gengetopt-2.23 and type 'make' or whatever is appropriate.
[gengetopt-2.23] Instead, the following commands setup all environment variables
[gengetopt-2.23] correctly and load a subshell for you to debug the error:
[gengetopt-2.23]   (cd '/scratch-nvme/1/casparl/generic/software/SageMath/9.8-GCCcore-11.3.0/var/tmp/sage/build/gengetopt-2.23' && '/gpfs/nvme1/1/casparl/generic/software/SageMath/9.8-GCCcore-11.3.0/
sage-9.8/sage' --buildsh)
[gengetopt-2.23] When you are done debugging, you can type "exit" to leave the subshell.
```
And then in gengetopt-2.23.log:
```
Building gengetopt-2.23
gengetopt --input cmdline.ggo
/usr/bin/bash: gengetopt: command not found
make[5]: *** [Makefile:1250: cmdline.c] Error 127
```
Well, of course it's not there: it wasn't built yet. I don't understand what's going on here... I give up :( If it works on other systems, fine by me, but it's not going to work on mine :P

**Comment by casparvl** [comment]
@boegelbot please test @ generoso

**Comment by arkdavy** [comment]
Hi, I had a small problem with this installation that users were not able to do pip --user installation of another Python package to use with SageMath since Sage's virtual environment has not allowed doing that. Does anyone have any idea how to solve it?

**Comment by arkdavy** [comment]
small update,

I have managed to fix the issue by using Conda generic easyblock with the following in easyconfig:

```python
dependencies = [
    ('Miniconda3', '4.12.0')
]

channels = ['conda-forge']
requirements =  'sage==%(version)s python=3.10'
```

It allows for both loading the Python-3.10.4 EB modules of Python libs together with SageMath and for doing local pip installs on top

**Comment by terjekv** [comment]
Well, in true open source fashion, this scratched my itch and as that itch is now scratched and I'm unable to reproduce the problems that cause it for others, I'm... not really sure what to do. I think I'd make a lousy doctor. Or considering some of those I've met in that field, this is probably closer to the workflow of some members of their field than I'd like to imagine.

Anyway. We can do either tbh. I don't merging code the a caveat of "it may not build, we don't know why, we tried fixing it and gave up", so maybe we pick the second option?

**Comment by casparvl** [comment]
@boegelbot please test @ generoso

**Comment by casparvl** [comment]
@boegelbot please test @ jsc-zen2

**Comment by terjekv** [comment]
> Test report by @boegelbot
> **FAILED**
> Build succeeded for 0 out of 2 (1 easyconfigs in total)
> jsczen2c1.int.jsc-zen2.easybuild-test.cluster - Linux Rocky Linux 8.5, x86_64, AMD EPYC 7742 64-Core Processor (zen2), Python 3.6.8
> See https://gist.github.com/boegelbot/aaa9b27389c1bc960f59a2c85e7ab7f6 for a full test report.

Seriously?

```
help2man: can't get `--help' info from automake-1.15
Try `--no-discard-stderr' if option outputs to stderr
make: *** [Makefile:3687: doc/automake-1.15.1] Error 255
make: *** Waiting for unfinished jobs....
 (at easybuild/easybuild-framework/easybuild/tools/run.py:643 in parse_cmd_output)
```

I think this PR is cursed.

**Comment by casparvl** [comment]
It is cursed. It seems almost impossible to get any test report from the bot to be uploaded correctly :P Let me retry once more for generoso. But that error on jsc-zen2 looks familiar, it was one of the first I encountered I think, before I started to try to 'fix' things by including dependencies and stuff. But it didn't help me one bit, just went from one error to another...

**Comment by casparvl** [comment]
@boegelbot please test @ generoso

**Comment by casparvl** [comment]
Yep, see https://github.com/easybuilders/easybuild-easyconfigs/pull/17535#issuecomment-1474569857 that was very similar to the error on jsc-zen2...

**Comment by casparvl** [comment]
@terjekv I think you simply have a magic system, the only one in the world that can build this EasyConfig ;-)

**Comment by terjekv** [comment]
For what it's worth, I have only tested this on RHEL9. I suggest we close and point people here if they want to give it a shot, but we don't include it as "supported".

**Pull request closed without merging**
