### PR TITLE
{bio}[foss-2019b] Trinity v2.9.1: add dependencies on Python 3 and SciPy-bundle

### PR DESCRIPTION
**Pull request by lexming**
(created using `eb --new-pr`)

A week ago `Trinity-2.9.0-foss-2019b.eb` was merged into `develop`. However this easyconfig is severely handicapped as it lacks Python and `numpy`, which is needed by several scripts in `Trinity` and are consequently listed as required dependencies for it (https://github.com/trinityrnaseq/trinityrnaseq/wiki/Installing-Trinity).
Moreover, without Python it is impossible to run the test to validate the installation of `Trinity` with the provided sample data.

Since `Trinity-2.9.0-foss-2019b.eb` has not hit any release yet, I propose to update it with Python 3 and `SciPy-bundle`, removing the easyconfig without Python to avoid issues.

The other changes are minor and totally opportunistic
* update to version `2.9.1` as it has some bugfixes
* update version of `Salmon` to 1.1.0 as it also has some bugfixes
* add dependency on `kallisto` as it is used by several scripts in `Trinity`

### CODE REVIEW

**Comment by lexming** [comment]
Depends on #9956

**Comment by lexming** [comment]
Test report by @lexming
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
login2.cerberus.os - Linux centos linux 7.7.1908, Intel(R) Xeon(R) Gold 6126 CPU @ 2.60GHz, Python 2.7.5
See https://gist.github.com/3587d4be9f7a11842629281c0121351d for a full test report.

**Comment by migueldiascosta** [comment]
Test report by @migueldiascosta
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
generoso - Linux centos linux 7.6.1810, Intel(R) Xeon(R) CPU E5-2660 v4 @ 2.00GHz, Python 3.6.8
See https://gist.github.com/22a380acb61cee1c320d390527338cc9 for a full test report.

**Comment by boegel** [comment]
@lexming Why not just add a new easyconfig for `Trinity` 2.9.1 with the additional dependencies, and leave the existing easyconfig for `Trinity` 2.9.0 as is?

If you do strongly favor removing it, I would like to hear from @robqiao who contributed the easyconfig in #9559 whether they're OK with the proposed change.

**Comment by lexming** [comment]
Yes, I strongly favor removing it. Adding the dependency on Python does not have any drawbacks and it will certainly avoid issues and spending time on the errors I encountered.
@robqiao Please let us know if you approve these changes.

**Comment by boegel** [comment]
Test report by @boegel
**FAILED**
Build succeeded for 0 out of 1 (1 easyconfigs in this PR)
node2547.golett.os - Linux centos linux 7.7.1908, Intel(R) Xeon(R) CPU E5-2680 v3 @ 2.50GHz, Python 2.7.5
See https://gist.github.com/941edd6bc6161f4f7d58dc2be2d860fc for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
node2547.golett.os - Linux centos linux 7.7.1908, Intel(R) Xeon(R) CPU E5-2680 v3 @ 2.50GHz, Python 2.7.5
See https://gist.github.com/4fc1ab3b31437ed104832ffec29c5d26 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
node3107.skitty.os - Linux centos linux 7.7.1908, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz, Python 3.6.8
See https://gist.github.com/4563f590bd6ee353cd4a5138f31a1cc3 for a full test report.

**Pull request merged**
