### PR TITLE
fixes "X11 font could not be loaded" R bug by adding Pango dependency

### PR DESCRIPTION
**Pull request by tstrempel**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by tstrempel** [comment]
Before:
```
ml foss/2018b R/3.5.1
R
> png("test.png", width=1800, height=1200, res=300)
> plot(1:100, main="Hallo")
Error in axis(side = side, at = at, labels = labels, ...) : 
  X11 font -adobe-helvetica-%s-%s-*-*-%d-*-*-*-*-*-*-*, face 1 at size 12 could not be loaded
> dev.off()
```

By building with Pango this message will dissappear:
```
ml foss/2018b R/3.5.1-pango
R
> png("test.png", width=1800, height=1200, res=300)
> plot(1:100, main="Hallo")
> dev.off()
```

**Comment by smoors** [comment]
@tstrempel I cannot reproduce the error, probably because I have a system pango installed.
do you really need to build with pango, or is it enough to have the pango module loaded together with R?

**Comment by tstrempel** [comment]
@smoors You need to build with pango (Maybe you had the system pango already installed at the start of the R compilation).
If I load Pango together with an R built without Pango, it throws the same error:
```
module load foss/2019b R/3.6.2-default Pango/1.44.7
R
> png("test.png", width=1800, height=1200, res=300)
> plot(1:100, main="Hallo")
Error in axis(side = side, at = at, labels = labels, ...) : 
  X11 font -adobe-helvetica-%s-%s-*-*-%d-*-*-*-*-*-*-*, face 1 at size 12 could not be loaded
```

**Comment by akesandgren** [comment]
I also see the same problem, so this needs a closer look.

**Comment by boegel** [comment]
@akesandgren Even if we can reproduce this, the fix will need to be applied with more recent `R` easyconfigs, so an issue should be opened until it's clear 1) how to reproduce this, 2) the fix can be applied consistently.

With that in mind, I'll close this, please open an issue to follow up (we shouldn't keep stale PRs open as reminder to fix something).

**Pull request closed without merging**
