### PR TITLE
{chem}[foss/2018b] NAMD v2.13

### PR DESCRIPTION
**Pull request by seb45tian**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by seb45tian** [comment]
Test report by @seb45tian
**FAILED**
Build succeeded for 0 out of 1 (1 easyconfigs in this PR)
hmipc21 - Linux debian buster/sid, Intel(R) Xeon(R) CPU E5-1650 v4 @ 3.60GHz, Python 2.7.15
See https://gist.github.com/ee1488e82037c3b06d9a4c3ea7c99c0a for a full test report.

**Comment by seb45tian** [comment]
Test report by @seb45tian
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
hmipc21 - Linux debian buster/sid, Intel(R) Xeon(R) CPU E5-1650 v4 @ 3.60GHz, Python 2.7.15
See https://gist.github.com/f11875d738c52ca3db07f12d644449aa for a full test report.

**Comment by seb45tian** [comment]
Test report by @seb45tian
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
hmipc21 - Linux debian buster/sid, Intel(R) Xeon(R) CPU E5-1650 v4 @ 3.60GHz, Python 2.7.15
See https://gist.github.com/d691cc641c2c0ec89a77b4c50753c17e for a full test report.

**Comment by verdurin** [comment]
Test report by @verdurin
**FAILED**
Build succeeded for 0 out of 1 (1 easyconfigs in this PR)
rescomp2 - Linux centos linux 7.3.1611, Intel(R) Xeon(R) Gold 6126 CPU @ 2.60GHz, Python 2.7.11
See https://gist.github.com/e59649f5421ec0801f6e9c3d4ce709fc for a full test report.

**Comment by verdurin** [comment]
Test report by @verdurin
**FAILED**
Build succeeded for 0 out of 1 (1 easyconfigs in this PR)
rescomp2 - Linux centos linux 7.3.1611, Intel(R) Xeon(R) Gold 6126 CPU @ 2.60GHz, Python 2.7.11
See https://gist.github.com/5300210cb5a269c36da865246ea98ae1 for a full test report.

**Comment by verdurin** [comment]
Welcome to Easybuild, @seb45tian and thanks for contributing.

In my build test I see a different checksum: `68627891fa34b42814edfe0c0556f22b2e8f5dec9902c1d878c02606544b6fb7`

Could you double-check the checksum at your end? Thanks.

**Comment by seb45tian** [comment]
> Welcome to Easybuild, @seb45tian and thanks for contributing.
> 
> In my build test I see a different checksum: `68627891fa34b42814edfe0c0556f22b2e8f5dec9902c1d878c02606544b6fb7`
> 
> Could you double-check the checksum at your end? Thanks.

@verdurin Thank you. Was irretated by that as well and double checked, the checksum should be correct:

    $ sha256sum NAMD_2.13_Source.tar.gz
    > cb0b43f520ac6be761899326441541aa00de15897986223c8ce2f0f6e42b52bc

Where did you get the source file from? I got mine from [here](https://www.ks.uiuc.edu/Development/Download/download.cgi?PackageName=NAMD) and used the _Source Code_ link of the 2.13 release (of course have to be registered etc). Also re-downloaded to make sure nothing changed, still the same checksum.

Sebastian

**Comment by verdurin** [comment]
@seb45tian The link I used is https://www.ks.uiuc.edu/Development/Download/download.cgi?UserID=&AccessCode=&ArchiveID=1561 which appeared to be the link for `2.13`.

I've just tried again on a different machine and still see the following:
```
$ shasum -a 256 NAMD_2.13_Source.tar.gz
68627891fa34b42814edfe0c0556f22b2e8f5dec9902c1d878c02606544b6fb7  NAMD_2.13_Source.tar.gz
```

**Comment by seb45tian** [comment]
@verdurin So, now I am really confused. I used your link to download the source file (exact same link as I used before btw.) My checksum is still different, also on different machines (but consistent among them)

    $ shasum -a 256 NAMD_2.13_Source.tar.gz
    cb0b43f520ac6be761899326441541aa00de15897986223c8ce2f0f6e42b52bc  NAMD_2.13_Source.tar.gz

Either I am doing something really wrong here, or they are somehow hardcoding your credentials into the package, generating the tgz on the fly and thereby changing the checksum??? I really don't know.

A third person to confirm or not confirm one of the checksums would be really helpful here ...

**Comment by akesandgren** [comment]
This is what i get for a download made just now.
sha256sum NAMD_2.13_Source.tar.gz 
68627891fa34b42814edfe0c0556f22b2e8f5dec9902c1d878c02606544b6fb7  NAMD_2.13_Source.tar.gz

shasum -a 256 NAMD_2.13_Source.tar.gz
68627891fa34b42814edfe0c0556f22b2e8f5dec9902c1d878c02606544b6fb7  NAMD_2.13_Source.tar.gz

**Comment by akesandgren** [comment]
@seb45tian 
ls -l NAMD_2.13_Source.tar.gz 
-rw-r--r-- 1 ake folk 110888960 Nov 28 10:55 NAMD_2.13_Source.tar.gz

What do you get?

**Comment by seb45tian** [comment]
@akesandgren  I think I found my error. It seemed to be a browser issue? I switched from using FireFox to Chrome and voilà:

    $ ls -l NAMD_2.13_Source_*
    -rw-r--r-- 1 sebastian staff 110888960 Nov 28 11:02 NAMD_2.13_Source_Chrome.tar.gz
    -rw-r--r-- 1 sebastian staff  51289185 Nov 28 10:20 NAMD_2.13_Source_FireFox.tar.gz

    $ shasum -a 256 NAMD_2.13_Source_*
    68627891fa34b42814edfe0c0556f22b2e8f5dec9902c1d878c02606544b6fb7  NAMD_2.13_Source_Chrome.tar.gz
    cb0b43f520ac6be761899326441541aa00de15897986223c8ce2f0f6e42b52bc  NAMD_2.13_Source_FireFox.tar.gz

@verdurin Sorry for the mess up, I will update the checksum and PR accordingly. Just wandering how I was able to successfully compile everything with half the archive file size?

**Comment by verdurin** [comment]
Test report by @verdurin
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
rescomp2 - Linux centos linux 7.3.1611, Intel(R) Xeon(R) Gold 6126 CPU @ 2.60GHz, Python 2.7.11
See https://gist.github.com/3bbfe840ed906c2c4fbe663cc2038e43 for a full test report.

**Comment by verdurin** [comment]
Thanks for the fix, @seb45tian 

The other thing I meant to mention is that you have removed the `FFTW` dependency, which makes sense because it is included in the toolchain anyway. Wanted to make sure that change was recorded.

**Comment by verdurin** [comment]
Going in, thanks @seb45tian!

**Comment by seb45tian** [comment]
> The other thing I meant to mention is that you have removed the `FFTW` dependency, which makes sense because it is included in the toolchain anyway. Wanted to make sure that change was recorded.

Yes, I saw this in the last PR. Happy to help out. I was wandering if the filesize/download issue should be somehow mentioned in the config file?

**Comment by verdurin** [comment]
@seb45tian yes, that's a good idea. The comment should mention that Chrome is preferred over Firefox and the expected size of the archive, ideally.

**Comment by akesandgren** [comment]
Hopefully this wlil be a mote problem later in 2018, they claim to be moving to github...

**Comment by boegel** [comment]
Ran into the same download issue, how infuriating...

Can be fixed easily though, even if you download with Firefox which helpfully zips it on download:

```
$ sha256sum NAMD_2.13_Source.tar.gz
cb0b43f520ac6be761899326441541aa00de15897986223c8ce2f0f6e42b52bc  NAMD_2.13_Source.tar.gz

$ gunzip NAMD_2.13_Source.tar.gz
$ mv NAMD_2.13_Source.tar NAMD_2.13_Source.tar.gz

$ sha256sum NAMD_2.13_Source.tar.gz
68627891fa34b42814edfe0c0556f22b2e8f5dec9902c1d878c02606544b6fb7  NAMD_2.13_Source.tar.gz

**Pull request merged**
