### PR TITLE
add gllvm extension (+ deps) to R 3.5.1 easyconfigs

### PR DESCRIPTION
**Pull request by boegel**

### CODE REVIEW

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in this PR)
node2602.swalot.os - Linux centos linux 7.5.1804, Intel(R) Xeon(R) CPU E5-2660 v3 @ 2.60GHz, Python 2.7.5
See https://gist.github.com/d991be2814a684c1752a1fb70d52b017 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in this PR)
node2090.delcatty.os - Linux centos linux 7.5.1804, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.7.5
See https://gist.github.com/1f15f7734e31234ea30947268dab05a3 for a full test report.

**Comment by boegel** [comment]
@ocaisa The order of extensions is not different, there were a couple of extensions missing in one of these (the ones that were added in #6901), I fixed that inconsistency...

```diff
diff -u easybuild/easyconfigs/r/R/R-3.5.1-foss-2018b-Python-2.7.15.eb easybuild/easyconfigs/r/R/R-3.5.1-foss-2018b.eb
--- easybuild/easyconfigs/r/R/R-3.5.1-foss-2018b-Python-2.7.15.eb	2018-11-06 16:39:23.000000000 +0100
+++ easybuild/easyconfigs/r/R/R-3.5.1-foss-2018b.eb	2018-11-06 16:39:23.000000000 +0100
@@ -1,6 +1,5 @@
 name = 'R'
 version = '3.5.1'
-versionsuffix = '-Python-%(pyver)s'

 homepage = 'http://www.r-project.org/'
 description = """R is a free software environment for statistical computing and graphics."""
@@ -15,7 +14,6 @@
     ('pkg-config', '0.29.2'),
 ]
 dependencies = [
-    ('Python', '2.7.15'),
     ('X11', '20180604'),
     ('Mesa', '18.1.1'),
     ('libGLU', '9.0.0'),
@@ -34,7 +32,7 @@
     ('Tk', '8.6.8'),  # for tcltk
     ('cURL', '7.60.0'),  # for RCurl
     ('libxml2', '2.9.8'),  # for XML
-    ('GDAL', '2.2.3', versionsuffix),  # for rgdal
+    ('GDAL', '2.2.3', '-Python-3.6.6'),  # for rgdal
     ('PROJ', '5.0.0'),  # for rgdal
     ('GMP', '6.1.2'),  # for igraph
     ('NLopt', '2.4.2'),  # for nloptr
```

**Comment by ocaisa** [comment]
Ok, thanks for clarifying, I see where the need for the python2 one comes from now too.

**Pull request merged**
