### PR TITLE
{numlib}[foss/2023b] SuiteSparse v7.7.0 w/ METIS 5.1.0

### PR DESCRIPTION
**Pull request by SimonPinches**
(created using `eb --new-pr`)

### CODE REVIEW

**Review by kErica — APPROVED** [review]
lgtm

**Comment by branfosj** [comment]
@boegelbot please test @ generoso

**Comment by branfosj** [comment]
@boegelbot please test @ jsc-zen3

**Comment by branfosj** [comment]
Test report by @branfosj
**SUCCESS**
Build succeeded for 4 out of 4 (1 easyconfigs in total)
bear-pg0105u03b - Linux RHEL 8.6, x86_64, Intel(R) Xeon(R) Platinum 8360Y CPU @ 2.40GHz (icelake), Python 3.6.8
See https://gist.github.com/branfosj/b527d1713d45776eb03d53bfd38ae44d for a full test report.

**Review by branfosj — APPROVED** [review]

**Comment by appolloford** [comment]
Is it true that SuiteSparse uses the external METIS-5.1.0? My understanding is that after v6.0.0, suitesparse only uses the metis built with itself and there is no way to ask it to use another one. At least my easyblock has no mechanism to set any variables for it. Same question for #21132

**Comment by SimonPinches** [comment]
@appolloford, being completely honest, I don't know.  If the external version is not used then it should be removed as a dependency, and looking at the libraries created, I don't spot a dependence upon the external METIS...

**Pull request merged**
