### PR TITLE
{devel}[GCCcore/13.2.0] line_profiler v4.1.2

### PR DESCRIPTION
**Pull request by tanmoy1989**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by verdurin** [comment]
Test report by @verdurin
**SUCCESS**
Build succeeded for 9 out of 9 (1 easyconfigs in total)
easybuild-c7.novalocal - Linux CentOS Linux 7.9.2009, x86_64, Intel Xeon Processor (Skylake, IBRS), Python 3.6.8
See https://gist.github.com/verdurin/60a9d584a3201d815353cfb2b0dfb21f for a full test report.

**Comment by tanmoy1989** [comment]
Hello @verdurin many thanks for taking to review my first ever tiny contribution to EasyBuild (quite exciting for me). I have tried to remove the "executable permission" form the file by doing "chmod 644 line_profiler-4.1.2-GCCcore-13.2.0.eb". Is this the correct way of doing it as I am facing similar problems in my other PRs at EasyBuild? Many thanks!

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
node3117.skitty.os - Linux RHEL 8.8, x86_64, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz, Python 3.6.8
See https://gist.github.com/boegel/89a3a01fc5ef41f688764d4ed7dc4473 for a full test report.

**Comment by boegel** [comment]
@boegelbot please test @ generoso

> Hello @verdurin many thanks for taking time to review my first ever tiny contribution to EasyBuild (quite exciting for me). I have tried to remove the "executable permission" from the file by doing "chmod 644 line_profiler-4.1.2-GCCcore-13.2.0.eb". Is this the correct way of doing it as I am facing similar problems in my other PRs at EasyBuild? Many thanks!

@tanmoy1989 Sorry for not getting back to you on this earlier. Yes, a `chmod 644` works, `chmod a-x` would work too

**Comment by boegel** [comment]
@boegelbot please test @ generoso

**Comment by boegel** [comment]
@boegelbot please test @ jsc-zen3

**Review by boegel — APPROVED** [review]
lgtm

**Comment by boegel** [comment]
Going in, thanks @tanmoy1989!

**Pull request merged**
