### PR TITLE
{toolchain}[system/system] gompi v2021.04

### PR DESCRIPTION
**Pull request by robert-mijakovic**
(created using `eb --new-pr`)
Depends on OpenMPI (~~#12566~~)

### CODE REVIEW

**Review by SebastianAchilles — CHANGES_REQUESTED** [review]
This needs to be updated to OpenMPI v.4.1.1

**Comment by boegel** [comment]
We should also be a bit careful with the `2021a` version, we shouldn't use that in `develop` until we're 100% sure we won't fiddle with the versions of the toolchain components anymore.

For `gompi/2021a`, I think that discussion has settled on GCC 10.3 + OpenMPI 4.1.1, but we still need to test this combination extensively. So I'd rather go with `2021.04` for now, and rename that in place to `2021a` while it's still only in `develop` (i.e. not included in an EasyBuild release) as soon as we're confident there are no (serious) problems with it.

**Comment by boegel** [comment]
As mentioned, I've bumped this to `gompi/2021.04` so we can proceed with merging this + easyconfigs on top like #12747, while avoiding giving the impression that `2021a` is fully set is stone (we're close, but we need some more testing first imho).

**Comment by boegel** [comment]
@boegelbot please test @ generoso

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
node3131.skitty.os - Linux centos linux 7.9.2009, x86_64, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz, Python 3.6.8
See https://gist.github.com/5e62595a15d124989a4fa3fbe3c8341f for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
easybuild2.novalocal - Linux centos linux 8.3.2011, POWER, IBM pSeries (emulated by qemu) (power9le), Python 3.6.8
See https://gist.github.com/5e7706ed5a145edcc463f97fc8d19819 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
select-pika-c6gd-2xlarge-0001 - Linux centos linux 8.3.2011, AArch64, ARM UNKNOWN (graviton2), Python 3.6.8
See https://gist.github.com/cafee89f0cf8e51669eb9b97e08b1d70 for a full test report.

**Comment by branfosj** [comment]
Test report by @branfosj
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
bear-pg0211u08b.bear.cluster - Linux RHEL 8.3, x86_64, Intel(R) Xeon(R) Gold 6248 CPU @ 2.50GHz (cascadelake), Python 3.6.8
See https://gist.github.com/a3eb7b75b709a1f037d351bb7e85c373 for a full test report.

**Review by branfosj — APPROVED** [review]
lgtm

**Comment by branfosj** [comment]
Test report by @branfosj
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
bear-pg0212u15b.bear.cluster - Linux RHEL 8.3, x86_64, Intel(R) Xeon(R) CPU E5-2640 v4 @ 2.40GHz (broadwell), Python 3.6.8
See https://gist.github.com/d5417241e5c21534e50e9b2856d8cfdf for a full test report.

**Pull request merged**
