### PR TITLE
{data}[foss/2018a,intel/2018a] netCDF v4.6.0

### PR DESCRIPTION
**Pull request by boegel**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in this PR)
node2666.swalot.os - Linux centos linux 7.4.1708, Intel(R) Xeon(R) CPU E5-2660 v3 @ 2.60GHz, Python 2.7.5
See https://gist.github.com/3e5238141e3d7d1cce9ddb387a6f166f for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in this PR)
node2034.delcatty.os - Linux centos linux 7.4.1708, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.7.5
See https://gist.github.com/1081895d2893cc1a7e8a3c02cf712670 for a full test report.

**Comment by verdurin** [comment]
Test report by @verdurin
**SUCCESS**
Build succeeded for 6 out of 6 (1 easyconfigs in this PR)
easybuild.novalocal - Linux centos linux 7.4.1708, Intel Xeon E312xx (Sandy Bridge), Python 2.7.5
See https://gist.github.com/eab0034e823a5f1f4df480dae024502d for a full test report.

**Comment by reedts** [comment]
Test report by @reedts
**SUCCESS**
Build succeeded for 4 out of 4 (2 easyconfigs in this PR)
palma003.palma.wwu - Linux centos linux 7.4.1708, Intel(R) Xeon(R) CPU E5-2620 v4 @ 2.10GHz, Python 2.7.5
See https://gist.github.com/d934a9e98f806338d845f8fdb9c2937c for a full test report.

**Comment by verdurin** [comment]
Going in, thanks @boegel!

**Pull request merged**
