### PR TITLE
{devel}[ssytem] CMake v3.15.1

### PR DESCRIPTION
**Pull request by cmeesters**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by verdurin** [comment]
Test report by @verdurin
**FAILED**
Build succeeded for 1 out of 2 (1 easyconfigs in this PR)
dell.lan - Linux fedora 30, Intel(R) Core(TM) i7-4600U CPU @ 2.10GHz, Python 2.7.16
See https://gist.github.com/c70d753f1e38ddd83976a0587c6735bf for a full test report.

**Comment by cmeesters** [comment]
@verdurin
The partial log does not contain any build information (the 'scanning' and 'building' parts are not contained. It is therefore not hard to understand *why* ccmake is not present in this particular build and what to do about it.

**Comment by verdurin** [comment]
Test report by @verdurin
**FAILED**
Build succeeded for 1 out of 2 (1 easyconfigs in this PR)
easybuild.novalocal - Linux centos linux 7.6.1810, Intel Xeon Processor (Skylake, IBRS), Python 2.7.5
See https://gist.github.com/93c05e1c34bd811fcbe21ee9ea7afdb9 for a full test report.

**Comment by verdurin** [comment]
@cmeesters full build log at https://gist.github.com/verdurin/50ad75e6f76c4328af194670010a639c

**Comment by cmeesters** [comment]
@verdurin 

Thank you!

I am not sure what to make of it: Your build log does not state "Scanning dependencies of target ccmake" (not valgrind and a few others).

But am I not sure of the cause. The configure differences state that (note: the same bare system compiler gcc 4.8.5!):

Checking for curses support - Failed 

This is only in your log - yet I do not understand the implication, nor do I see curses anywhere stated as a build dependency for cmake. So I did not make any progress. Ideas?

**Comment by cmeesters** [comment]
@verdurin 

Hm, http://cmake.3232098.n2.nabble.com/ccmake-is-not-getting-installed-td7583001.html and https://askubuntu.com/questions/121797/how-do-i-install-ccmake

and particularly

indicate, that indeed curses support is needed. In that case curses should be a build-dependency of the easyconfig. It was not in my template, but ncurses is in our filter-deps and installed on the system. This, apparently is a problem.

I will test this tomorrow and report back, potentially with an updated pr.

Thanks again for pointing this out!

https://github.com/easybuilders/easybuild-easyconfigs/issues/4171

**Comment by pescobar** [comment]
Test report by @pescobar
**FAILED**
Build succeeded for 1 out of 2 (1 easyconfigs in this PR)
worker01.cluster.bc2.ch - Linux centos linux 7.5.1804, Intel(R) Xeon(R) CPU E5-2630 v4 @ 2.20GHz, Python 2.7.5
See https://gist.github.com/6ed802441e7804de4b11360645e10be2 for a full test report.

**Comment by pescobar** [comment]
my build failed in the sanity_check step

```
: build failed (first 300 chars): Sanity check failed: no file found at 'bin/ccmake'
```

**Comment by cmeesters** [comment]
@pescobar 

Yes, we are at that point - I still did not get a conclusive answer and probably only will find the time to dive into this tomorrow. Any ideas for the underlying reason are highly appreciated. (the curses-idea seems a probable cause).

**Comment by boegel** [comment]
@cmeesters `ncurses` should indeed be included as a (build) dependency in order for `ccmake` to get built, see also other `CMake` easyconfigs that use the `dummy` toolchain, for example https://github.com/easybuilders/easybuild-easyconfigs/blob/master/easybuild/easyconfigs/c/CMake/CMake-3.12.1.eb

**Comment by cmeesters** [comment]
As you can see: the 'ncurses' dependency was already present in the original pr (contrary to my own believe).

The really embarrassing observation for me is: I tested with and without ncurses on a node it build regardless (as 'ncurses' is in our filter-deps we do not provide a module, so eb has no chance to pick up the lib from a module). 

If the missing 'ncurses' leads to the build fails, why then do these build attempts not pick up the requirement and consider it? Anyone?

**Comment by boegel** [comment]
@cmeesters You're being bit by using `dummy` as a toolchain version, which implies *not* loading the dependencies in the build environment; see also https://easybuild.readthedocs.io/en/latest/Writing_easyconfig_files.html#loading-of-modules-for-dependencies-with-a-dummy-toolchain .

We're fully aware that this is weird behavior, and the reason why it was implemented like this originally is lost to the sands of time (the most likely motivation was to discourage the use of the `dummy` toolchain, but that's a weak argument at best).
Hence, we're getting rid of this in the upcoming EasyBuild 4.0, by replacing the `dummy` toolchain with the (better named) `system` toolchain, see https://github.com/easybuilders/easybuild-framework/pull/2877 .

For this PR: just use an empty toolchain version, which will result in loading the `ncurses` dependency in the build environment; that should fix the problem:

```python
toolchain = {'name': 'dummy', 'version': ''}
```

Also note that `ncurses` should only be a *build* dependency and make sure you link statically (using a runtime dependency may cause problems later when this `CMake` is used to build something that depends on `ncurses` with a non-dummy toolchain); see the existing easyconfig https://github.com/easybuilders/easybuild-easyconfigs/blob/master/easybuild/easyconfigs/c/CMake/CMake-3.12.1.eb

**Comment by cmeesters** [comment]
@boegel 
Yes, you mentioned that - and I've forgotten. I'll have time today to give a try and report back. Thanks!

**Comment by cmeesters** [comment]
I updated the pr according to Kenneth's remark - now the behavior is as expected. Please go ahead and test on your systems to be sure.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 2 out of 2 (1 easyconfigs in this PR)
node3103.skitty.os - Linux centos linux 7.6.1810, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz, Python 2.7.5
See https://gist.github.com/423cd7f57cde4a6126d1b43dec7515be for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
node2031.delcatty.os - Linux centos linux 7.6.1810, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.7.5
See https://gist.github.com/c72b3c6e13311b85519f236eb6ab7803 for a full test report.

**Comment by verdurin** [comment]
Test report by @verdurin
**SUCCESS**
Build succeeded for 2 out of 2 (1 easyconfigs in this PR)
rescomp2 - Linux centos linux 7.3.1611, Intel(R) Xeon(R) Gold 6126 CPU @ 2.60GHz, Python 2.7.5
See https://gist.github.com/a2fc8d042b9d6cd19880ca0f5575949a for a full test report.

**Comment by boegel** [comment]
@cmeesters Please make sure `ncurses` is statically linked, by specifying additional configure option, like we do in https://github.com/easybuilders/easybuild-easyconfigs/blob/master/easybuild/easyconfigs/c/CMake/CMake-3.12.1.eb:

```
-DCURSES_FORM_LIBRARY=$EBROOTNCURSES/lib/libform.a -DCURSES_NCURSES_LIBRARY=$EBROOTNCURSES/lib/libncurses.a
```

**Comment by boegel** [comment]
@cmeesters Without static linking, you'll just end up with a broken `ccmake`:

```
$ module load CMake/3.15.1
$ ccmake --version
ccmake: error while loading shared libraries: libncurses.so.6: cannot open shared object file: No such file or directory
$ echo $?
127
$ ldd $(which ccmake) | grep ncurses
        libncurses.so.6 => not found
```

Maybe we should include `ccmake --version` as a sanity check command as well?

**Comment by boegel** [comment]
@boegelbot please test @ generoso

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
node3501.doduo.os - Linux RHEL 8.2, x86_64, AMD EPYC 7552 48-Core Processor (zen2), Python 3.6.8
See https://gist.github.com/9ab83b697db1952ccd538414c4b848d3 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
node2631.swalot.os - Linux centos linux 7.9.2009, x86_64, Intel(R) Xeon(R) CPU E5-2660 v3 @ 2.60GHz (haswell), Python 3.6.8
See https://gist.github.com/b1f86725877322de7ee2113ae596ced5 for a full test report.

**Review by boegel — APPROVED** [review]

**Comment by boegel** [comment]
Going in, thanks @cmeesters!

**Pull request merged**
