### PR TITLE
{mpi}[GCC/9.2.0-2.32] OpenMPI v4.0.2

### PR DESCRIPTION
**Pull request by boegel**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 5 out of 5 (5 easyconfigs in this PR)
node2548.golett.os - Linux centos linux 7.7.1908, Intel(R) Xeon(R) CPU E5-2680 v3 @ 2.50GHz, Python 2.7.5
See https://gist.github.com/b6e4716d21d2372768de1e66ea74e17a for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 5 out of 5 (5 easyconfigs in this PR)
node2519.golett.os - Linux centos linux 7.7.1908, Intel(R) Xeon(R) CPU E5-2680 v3 @ 2.50GHz, Python 2.7.5
See https://gist.github.com/5ee803e8bb2413c19a2596b62bfb7868 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 6 out of 6 (5 easyconfigs in this PR)
generoso-1 - Linux centos linux 7.6.1810, Intel(R) Xeon(R) CPU E5-2660 v4 @ 2.00GHz, Python 3.6.8
See https://gist.github.com/101668669c3293784223519879334690 for a full test report.

**Comment by akesandgren** [comment]
ScaLAPACK still uses old MPI-1.x functions and thus requires OpenMPI to be built with
--enable-mpi1-compatibility

**Comment by verdurin** [comment]
Test report by @verdurin
**SUCCESS**
Build succeeded for 20 out of 20 (5 easyconfigs in this PR)
easybuild.novalocal - Linux centos linux 7.7.1908, Intel Xeon Processor (Skylake, IBRS), Python 2.7.5
See https://gist.github.com/152746a2c4e857864c7eb4a3808899d8 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 6 out of 6 (5 easyconfigs in this PR)
node3102.skitty.os - Linux centos linux 7.7.1908, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz, Python 3.6.8
See https://gist.github.com/8ec67ae11a39e886ecc4bd4376762acb for a full test report.

**Comment by boegel** [comment]
@akesandgren Is there any downside to building `OpenMPI` with `--enable-mpi1-compatibility`?

Also, if the patch is easy/short, why not just patch `ScaLAPACK` instead?

**Comment by akesandgren** [comment]
Patching ScaLAPACK is doable, and I even have the patch available...

**Comment by boegel** [comment]
@akesandgren Do you know of any other software that may require MPI-1 compatibility to be enabled?

**Comment by bartoldeman** [comment]
Scalapack 2.1.0 should be ok: http://netlib.org/scalapack/scalapack-2.1.0.html

**Comment by bartoldeman** [comment]
HDF5 < 1.10.5 is another one.
Valgrind is another one.

For me (I added this switch to our own 4.0.x easyconfigs) it's also about users who may have some old software to compile and don't have time/money to go to the trouble of updating it.

**Comment by akesandgren** [comment]
Ohh, that ScaLAPACK version is spanking new... hadn't even seen it yet. (And our boss usually tells whenever anything happens in the blas/lapack/scalapack world since he's been involved in it since for ever...)

**Comment by akesandgren** [comment]
Besides that I haven't seen anything that has trouble.

**Comment by boegel** [comment]
@bartoldeman Are there any downsides to enabling `--enable-mpi1-compatibility` (other than dragging a dead horse, perhaps)?

**Comment by akesandgren** [comment]
The drawback is allowing people to still use things that got deprecated over 10 years ago...

**Comment by bartoldeman** [comment]
yes exactly what Ake says, it's like enabling the C++ bindings. Some software depends on it but everything can be fixed.

Spack seems to enable both. "Hey my package compiles with Spook but not EB -- EB must suck!"

**Comment by boegel** [comment]
That's what I meant with the dead horse... ;)

Similar discussion in the OpenHPC repo btw, see https://github.com/openhpc/ohpc/issues/1080#issuecomment-572668117

**Comment by smoors** [comment]
Test report by @smoors
**SUCCESS**
Build succeeded for 13 out of 13 (5 easyconfigs in this PR)
node377.hydra.os - Linux centos linux 7.7.1908, Intel(R) Xeon(R) Gold 6148 CPU @ 2.40GHz, Python 2.7.5
See https://gist.github.com/4dcd04f504c34e52f329b23c90a30965 for a full test report.

**Comment by terjekv** [comment]
I thought I'd test this on RHEL8, but I get:

```
terjekv@ninhursaga:~$ MODULEPATH= eb --installpath /tmp/$USER/9636 --from-pr=9636 --upload-test-report --github-user=terjekv --dry-run
[...]
== temporary log file in case of crash /tmp/eb-1tfsufbw/easybuild-p72o01yf.log
ERROR: Missing dependencies: libxml2/2.9.10-GCCcore-9.2.0, Autotools/20180311-GCCcore-9.2.0 (no easyconfig file or existing module found)
terjekv@ninhursaga:~$ eb --version
This is EasyBuild 4.1.0 (framework: 4.1.0, easyblocks: 4.1.0) on host ninhursaga.uio.no.
```
I'm a bit stumped as to what's up here.

**Comment by smoors** [comment]
@terjekv the missing dependencies are in the develop branch. best to always do test reports from an updated develop branch.

**Comment by terjekv** [comment]
I'm a moron. I thought I was in the dev branch.

**Comment by boegel** [comment]
Test report by @boegel
**FAILED**
Build succeeded for 0 out of 5 (5 easyconfigs in this PR)
generoso - Linux centos linux 7.6.1810, Intel(R) Xeon(R) CPU E5-2660 v4 @ 2.00GHz, Python 3.6.8
See https://gist.github.com/1fd9176c0b0bd308ce749f2787f5487e for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 5 out of 5 (5 easyconfigs in this PR)
node2483.golett.os - Linux centos linux 7.7.1908, Intel(R) Xeon(R) CPU E5-2680 v3 @ 2.50GHz, Python 2.7.5
See https://gist.github.com/b3da962bd6de647d2fd5339ee4716002 for a full test report.

**Comment by terjekv** [comment]
This is currently being tested on RHEL8. Apologies for the delay.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 5 out of 5 (5 easyconfigs in this PR)
node3154.skitty.os - Linux centos linux 7.7.1908, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz, Python 3.6.8
See https://gist.github.com/fa6e1ebbe69ff46eadd868e732e9f5e2 for a full test report.

**Comment by terjekv** [comment]
Test report by @terjekv
**SUCCESS**
Build succeeded for 29 out of 29 (5 easyconfigs in this PR)
ninhursaga.uio.no - Linux red hat enterprise linux 8.1, Intel(R) Xeon(R) Silver 4216 CPU @ 2.10GHz, Python 3.6.8
See https://gist.github.com/6d49435d0956aa4070190781d5ce3cab for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 5 out of 5 (5 easyconfigs in this PR)
generoso - Linux centos linux 7.6.1810, Intel(R) Xeon(R) CPU E5-2660 v4 @ 2.00GHz, Python 3.6.8
See https://gist.github.com/ff1d9b25f9994d7e5412fdfbcd997d79 for a full test report.

**Comment by branfosj** [comment]
Test report by @branfosj
**SUCCESS**
Build succeeded for 5 out of 5 (5 easyconfigs in this PR)
bear-pg0305u03a.bear.cluster - Linux RHEL 7.6, 8335-GTX, Python 2.7.5
See https://gist.github.com/026b0dd4621ced3798aff8aa3f9a1837 for a full test report.

**Comment by smoors** [comment]
Test report by @smoors
**SUCCESS**
Build succeeded for 5 out of 5 (5 easyconfigs in this PR)
node376.hydra.os - Linux centos linux 7.7.1908, Intel(R) Xeon(R) Gold 6148 CPU @ 2.40GHz, Python 2.7.5
See https://gist.github.com/283047312d62365fa73ebe3156df0cb3 for a full test report.

**Comment by smoors** [comment]
Going in, thanks @boegel!

**Pull request merged**
