### PR TITLE
{chem}[GCCcore/12.3.0,foss/2023a,gfbf/2023a] GPAW v23.9.1, ASE v3.22.1, libvdwxc v0.4.0, ...

### PR DESCRIPTION
**Pull request by schiotz**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by schiotz** [comment]
Port of GPAW and ASE to the foss/2023a toolchain, including a number of dependencies.

One dependency is new: The latest version of spglib-python builds using ``scikit-build-core``, a python reimplementation of scikit-build.  As it is only required to build, I made it a separate module and included it as a build dependency.

**Comment by schiotz** [comment]
Re-running checks, to see if it is a problem that the ASE file has already been merged in #19040

**Comment by schiotz** [comment]
@boegel @Micket 
Would it be possible to get this one in EasyBuild before the next release.  It should be an uncontroversial update.

**Review by Micket — APPROVED** [review]
lgtm

**Comment by Micket** [comment]
@boegelbot please test @ generoso

**Comment by Micket** [comment]
@boegelbot please test @ jsc-zen2

**Comment by Micket** [comment]
Build on generoso is conflicting with other ongoing builds. Will revisit.

**Comment by Micket** [comment]
Test report by @Micket
**SUCCESS**
Build succeeded for 5 out of 5 (3 easyconfigs in total)
alvis-c1 - Linux Rocky Linux 8.8, x86_64, Intel Xeon Processor (Skylake), Python 3.6.8
See https://gist.github.com/Micket/6402fe740dc03a4d971aea9feeccaf5e for a full test report.

**Comment by Micket** [comment]
@boegelbot please test @ jsc-zen2

**Comment by Micket** [comment]
@boegelbot please test @ generoso

**Comment by schiotz** [comment]
> Test report by @boegelbot
> **FAILED**

It looks like there is a stale file lock from an earlier build that may have crashed.

**Comment by SebastianAchilles** [comment]
@boegelbot please test @ generoso
EB_ARGS="--ignore-locks"

**Comment by Micket** [comment]
Going in, thanks @schiotz!

**Pull request merged**
