### PR TITLE
fix source URL in Doxygen easyconfigs

### PR DESCRIPTION
**Pull request by willfurnass**
Switch to downloading doxygen from doxygen.nl as ftp.stack.nl is dead.

See Issue #7280.

### CODE REVIEW

**Comment by verdurin** [comment]
HI @willfurnass - welcome to EasyBuild, and thanks for the PR.

Looks like you're missing checksums, which you can rectify with the `--inject-checksums` command, cf https://easybuild.readthedocs.io/en/latest/Writing_easyconfig_files.html#adding-or-replacing-checksums-using-inject-checksums

**Comment by willfurnass** [comment]
@verdurin I've switched to downloading from Sourceforge as there's no valid TLS cert for doxygen.nl and have injected SHA256 checksums.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 47 out of 47 (47 easyconfigs in this PR)
node2006.delcatty.os - Linux centos linux 7.5.1804, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.7.5
See https://gist.github.com/d0386abd1900b9dba46da8a7b384e36b for a full test report.

**Comment by boegel** [comment]
Going in, thanks @willfurnass!

**Pull request merged**
