### PR TITLE
{chem}[intel/2018b] Wannier90 v3.0.0

### PR DESCRIPTION
**Pull request by jmbeuken**

### CODE REVIEW

**Comment by boegel** [comment]
@jmbeuken Since you're also changing an existing `ABINIT` easyconfig and added easyconfigs for things other than `Wanner90`, do you mind updating the PR title & description accordingly?

**Comment by jmbeuken** [comment]
This MR #8516 is a config for the last version of Wannier90 v3.0.0 :  this version is **not** specific to ABINIT 
The MR #8506 add last version AtomPAW 4.1.0.6 and Wannier90 v2.0.1.1 as dependencies for ABINIT 8.10.2 and 8.10.3 (this last one is the latest version of the 8.x series)
Maybe we could delete the configuration for ABINIT 8.10.2

**Comment by boegel** [comment]
@jmbeuken The changes in #8506 and this PR (#8516) partially overlop, which makes this confusing...

It looks like #8506 should go in first, but then PR will be broken (or should be closed as a new one for Wannier90 3.0.0 can be opened), since both PRs change `ABINIT-8.10.2-intel-2018b.eb` but differently (see `AtomPAW` version used as dep for `ABINIT`)

Let us know how you'd like to continue...

**Comment by jmbeuken** [comment]
I will reintroduce a PR in a cleaner configuration

**Pull request closed without merging**
