### PR TITLE
add patch for MPFR 4.1.0 to fix failing tsprintf test with glibc >= 2.37

### PR DESCRIPTION
**Pull request by boegel**
(created using `eb --new-pr`)

(WIP, patch doesn't apply cleanly...)

### CODE REVIEW

**Comment by boegel** [comment]
@boegelbot please test @ generoso

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 4 out of 4 (4 easyconfigs in total)
node3109.skitty.os - Linux RHEL 8.6, x86_64, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz (skylake_avx512), Python 3.6.8
See https://gist.github.com/boegel/4005fe76c756caed8ebc69fcb9d873a2 for a full test report.

**Comment by boegel** [comment]
@boegelbot please test @ jsc-zen2

**Review by ocaisa — APPROVED** [review]

**Comment by ocaisa** [comment]
@boegelbot please test @ jsc-zen

**Comment by bedroge** [comment]
Test report by @bedroge
**SUCCESS**
Build succeeded for 4 out of 4 (4 easyconfigs in total)
bob-Latitude-5300 - Linux Ubuntu 22.04, x86_64, Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz, Python 3.10.12
See https://gist.github.com/bedroge/6008364719934e84086717fe397c7f84 for a full test report.

**Comment by verdurin** [comment]
Test report by @verdurin
**SUCCESS**
Build succeeded for 4 out of 4 (4 easyconfigs in total)
easybuild-c7.novalocal - Linux CentOS Linux 7.9.2009, x86_64, Intel Xeon Processor (Skylake, IBRS), Python 3.6.8
See https://gist.github.com/verdurin/c67704e68875f2881a3179df72be9f2a for a full test report.

**Comment by verdurin** [comment]
Going in, thanks @boegel!

**Pull request merged**
