### PR TITLE
{bio}[foss/2017b,iccifort/2017.4.196-GCC-6.4.0-2.28,intel/2017b] HTSlib v1.9, LoFreq v2.1.3.1

### PR DESCRIPTION
**Pull request by murfreesboro**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by murfreesboro** [comment]
LoFreq does not support python 3. Therefore we do not have eb files for python 3.6.3.

**Comment by murfreesboro** [comment]
Test report by @murfreesboro
**SUCCESS**
Build succeeded for 3 out of 3 (3 easyconfigs in this PR)
dev806.vampire - Linux centos linux 7.4.1708, Intel(R) Xeon(R) CPU           E5620  @ 2.40GHz, Python 2.7.5
See https://gist.github.com/61fe6b69821847ca11285a9caf21d2a1 for a full test report.

**Comment by murfreesboro** [comment]
Test report by @murfreesboro
**SUCCESS**
Build succeeded for 3 out of 3 (3 easyconfigs in this PR)
dev806.vampire - Linux centos linux 7.4.1708, Intel(R) Xeon(R) CPU           E5620  @ 2.40GHz, Python 2.7.5
See https://gist.github.com/1f96b61b58dfbb52afc0bd4102dae3dd for a full test report.

**Comment by murfreesboro** [comment]
Test report by @murfreesboro
**SUCCESS**
Build succeeded for 3 out of 3 (3 easyconfigs in this PR)
dev806.vampire - Linux centos linux 7.4.1708, Intel(R) Xeon(R) CPU           E5620  @ 2.40GHz, Python 2.7.5
See https://gist.github.com/766673f5f002f72d0401948603e23eaa for a full test report.

**Comment by akesandgren** [comment]
Going in, thanks @murfreesboro!

**Pull request merged**
