### PR TITLE
Enable tests for most recent Bazel versions (3.x)

### PR DESCRIPTION
**Pull request by Flamefire**
(created using `eb --new-pr`)

- [ ] Requires https://github.com/easybuilders/easybuild-easyblocks/pull/2285

### CODE REVIEW

**Comment by smoors** [comment]
Test report by @smoors
**FAILED**
Build succeeded for 1 out of 3 (2 easyconfigs in total)
node381.hydra.os - Linux centos linux 7.9.2009, x86_64, Intel(R) Xeon(R) Gold 6148 CPU @ 2.40GHz (skylake_avx512), Python 2.7.5
See https://gist.github.com/153b5d510c8aae66e32e70fff4a21822 for a full test report.

**Comment by Flamefire** [comment]
@smoors You need the new Bazel easyblock for this to work

**Comment by smoors** [comment]
Test report by @smoors
Using easyblocks from PR(s) https://github.com/easybuilders/easybuild-easyblocks/pull/2285
**SUCCESS**
Build succeeded for 3 out of 3 (2 easyconfigs in total)
node376.hydra.os - Linux centos linux 7.9.2009, x86_64, Intel(R) Xeon(R) Gold 6148 CPU @ 2.40GHz (skylake_avx512), Python 2.7.5
See https://gist.github.com/3bd8121eebe28530c594a3424fc2d9f2 for a full test report.

**Comment by smoors** [comment]
@boegelbot please test @ generoso EB_ARGS=" --include-easyblocks-from-pr 2285"

**Comment by zao** [comment]
Test report by @zao
Using easyblocks from PR(s) https://github.com/easybuilders/easybuild-easyblocks/pull/2285
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in total)
eb-u1604 - Linux ubuntu 16.04, x86_64, Intel(R) Core(TM) i7-8700K CPU @ 3.70GHz, Python 2.7.12
See https://gist.github.com/7c1b32fbe59e7382f107f5c3fa185b99 for a full test report.

**Comment by verdurin** [comment]
Test report by @verdurin
Using easyblocks from PR(s) https://github.com/easybuilders/easybuild-easyblocks/pull/2285
**SUCCESS**
Build succeeded for 0 out of 0 (2 easyconfigs in total)
nuc.lan - Linux Fedora 32, x86_64, Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz, Python 3.8.6
See https://gist.github.com/47c9d965e7e41228ed8179a8804bafdb for a full test report.

**Comment by verdurin** [comment]
Test report by @verdurin
Using easyblocks from PR(s) https://github.com/easybuilders/easybuild-easyblocks/pull/2285
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in total)
nuc.lan - Linux Fedora 32, x86_64, Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz, Python 3.8.6
See https://gist.github.com/152ffff291b294a8be21137ae73b27cd for a full test report.

**Comment by verdurin** [comment]
@boegelbot please test @ generoso EB_ARGS=" --include-easyblocks-from-pr 2285"

**Comment by boegel** [comment]
Test report by @boegel
Using easyblocks from PR(s) https://github.com/easybuilders/easybuild-easyblocks/pull/2285
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in total)
node3509.doduo.os - Linux RHEL 8.2, x86_64, AMD EPYC 7552 48-Core Processor (zen2), Python 3.6.8
See https://gist.github.com/fd65026f280b97c9a096aa27b51b6c35 for a full test report.

**Review by boegel — APPROVED** [review]
lgtm

**Comment by boegel** [comment]
Going in, thanks @Flamefire!

**Pull request merged**
