### PR TITLE
{vis}[GCCcore/10.2.0] Pango v1.47.0, at-spi2-atk v2.38.0, HarfBuzz v2.6.7, ... w/ Python 3.8.6

### PR DESCRIPTION
**Pull request by Micket**
(created using `eb --new-pr`)
Depends on #11530

### CODE REVIEW

**Comment by Micket** [comment]
Test report by @Micket
**SUCCESS**
Build succeeded for 12 out of 12 (12 easyconfigs in this PR)
vera-c1 - Linux centos linux 7.8.2003, x86_64, Intel Xeon Processor (Skylake), Python 2.7.5
See https://gist.github.com/037f532639464b39380ae7a772f435e3 for a full test report.

**Comment by zao** [comment]
Test report by @zao
**SUCCESS**
Build succeeded for 12 out of 12 (12 easyconfigs in total)
freja - Linux Ubuntu 20.04, x86_64, Intel(R) Core(TM) i7-8700K CPU @ 3.70GHz (skylake), Python 3.8.5
See https://gist.github.com/dd21e9f1362ba8ab3422afac23c7c097 for a full test report.

**Comment by smoors** [comment]
@boegelbot please test @ generoso

**Comment by smoors** [comment]
Test report by @smoors
**SUCCESS**
Build succeeded for 20 out of 20 (12 easyconfigs in total)
node381.hydra.os - Linux centos linux 7.7.1908, x86_64, Intel(R) Xeon(R) Gold 6148 CPU @ 2.40GHz (skylake_avx512), Python 2.7.5
See https://gist.github.com/082fc18c2e63eef02f2a5949ba510d7a for a full test report.

**Comment by Micket** [comment]
trigger tests

**Review by smoors — APPROVED** [review]
lgtm

**Comment by branfosj** [comment]
@boegelbot please test @ generoso
EB_ARGS="LibTIFF-4.1.0-GCCcore-10.2.0.eb"

**Pull request merged**
