### PR TITLE
{chem}[foss/2021b] AmberTools v21.12 w/ Python 3.9.6

### PR DESCRIPTION
**Pull request by akesandgren**
(created using `eb --new-pr`)

Requires ~~https://github.com/easybuilders/easybuild-easyblocks/pull/2781~~

### CODE REVIEW

**Comment by akesandgren** [comment]
Test report by @akesandgren
Using easyblocks from PR(s) https://github.com/easybuilders/easybuild-easyblocks/pull/2781
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
b-an02.hpc2n.umu.se - Linux Ubuntu 20.04, x86_64, Intel(R) Xeon(R) CPU E5-2690 v4 @ 2.60GHz, Python 3.8.10
See https://gist.github.com/e733571ab88dcebd5ac219e4ae4d4c0f for a full test report.

**Comment by boegel** [comment]
@boegelbot please test @ generoso
CORE_CNT=16
EB_ARGS="--include-easyblocks-from-pr 2781"

**Comment by boegel** [comment]
Test report by @boegel
Using easyblocks from PR(s) https://github.com/easybuilders/easybuild-easyblocks/pull/2781
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
node3127.skitty.os - Linux RHEL 8.4, x86_64, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz (skylake_avx512), Python 3.6.8
See https://gist.github.com/95237ffe228087efdd40f879ffc33e58 for a full test report.

**Review by boegel — APPROVED** [review]
lgtm

**Pull request merged**
