### PR TITLE
add missing hatchling build dependency for scArches 0.6.1 w/ foss/2023a

### PR DESCRIPTION
**Pull request by boegel**
(created using `eb --new-pr`)
similar to #21809, caused by changing hatchling to build dep for scanpy in #21657

### CODE REVIEW

**Comment by boegel** [comment]
@boegelbot please test @ jsc-zen3

**Comment by boegel** [comment]
@boegelbot please test @ generoso

**Review by smoors — APPROVED** [review]
lgtm

**Comment by smoors** [comment]
Going in, thanks @boegel!

**Pull request merged**
