### PR TITLE
{cae}[dummy/dummy] FDTD_Solutions v8.20.1731

### PR DESCRIPTION
**Pull request by migueldiascosta**
(created using `eb --new-pr`)

requires ~~https://github.com/easybuilders/easybuild-easyblocks/pull/1307~~

### CODE REVIEW

**Comment by migueldiascosta** [comment]
Test report by @migueldiascosta
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
grc-cluster1 - Linux centos 6.10, Intel(R) Xeon(R) CPU E5-2640 0 @ 2.50GHz, Python 2.7.14
See https://gist.github.com/d22b59cfa0437fa004771d8a5b33bb15 for a full test report.

**Comment by migueldiascosta** [comment]
@akesandgren this comes packaged with `mpich2` libraries, but would need `impi` or `OpenMPI` to be loaded if those are to be used, should I add separate easyconfig files with the respective dependencies? how have you been using it?

**Comment by migueldiascosta** [comment]
hm, I missed #5502, I'll have a look 

(https://github.com/easybuilders/easybuild-easyblocks/pull/1307 is precisely what this was meant to test :) )

**Comment by migueldiascosta** [comment]
added one patch from #5502, the other two don't seem to apply any more

**Comment by migueldiascosta** [comment]
Test report by @migueldiascosta
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
grc-cluster1 - Linux centos 6.10, Intel(R) Xeon(R) CPU E5-2640 0 @ 2.50GHz, Python 2.7.14
See https://gist.github.com/28346923333374a06151f310d6df6f63 for a full test report.

**Comment by boegel** [comment]
@akesandgren Maybe also submit a test report for this (and then merge if it's good to go)?

**Comment by akesandgren** [comment]
We only have 8.16.982 so can't test this one.

**Comment by akesandgren** [comment]
@migueldiascosta doesn't it still hardcode paths to /opt in all the scripts and the python script?

**Comment by migueldiascosta** [comment]
@akesandgren their python script has been fixed. The bundled MPI is now `mpich2/nemesis` and it only ships `mpiexec` binaries and the libraries, no `mpirun` scripts. The `fdtd-run-local.sh` now uses this `mpiexec`. 

For other MPI libraries, it seems we it is now needed to use their own launchers, hence the question I asked at the beginning of this PR about loading `ipmi` or `OpenMPI`.

There is indeed one additional hardcoded path that you fixed in your patch, the one in `templates/fdtd-pbs-template.sh`. Not only is it still hardcoded, it's hardcoded to a now non-existing path, I'll fix that.

**Comment by migueldiascosta** [comment]
Test report by @migueldiascosta
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
grc-cluster1 - Linux centos 6.10, Intel(R) Xeon(R) CPU E5-2640 0 @ 2.50GHz, Python 2.7.14
See https://gist.github.com/e3a8e0c90f5e249920feebdb1b15312f for a full test report.

**Comment by akesandgren** [comment]
Going in, thanks @migueldiascosta!

**Pull request merged**
