### PR TITLE
GRASS: add zstd compression, {lib}[foss/2018b] zstd v1.4.0

### PR DESCRIPTION
**Pull request by smoors**
(created using `eb --new-pr`)

depends on #8090

### CODE REVIEW

**Comment by smoors** [comment]
Test report by @smoors
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in this PR)
nic418 - Linux centos linux 7.5.1804, Intel(R) Xeon(R) Gold 6148 CPU @ 2.40GHz, Python 2.7.5
See https://gist.github.com/cc56675ad4fd7f6b9eb51ba1fe8272b9 for a full test report.

**Comment by migueldiascosta** [comment]
closing and reopening to trigger travis

**Comment by migueldiascosta** [comment]
Test report by @migueldiascosta
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in this PR)
grc-cluster1 - Linux centos 6.10, Intel(R) Xeon(R) CPU E5-2640 0 @ 2.50GHz, Python 2.7.14
See https://gist.github.com/bf8b88b58b3f831b552ef57ba43edea3 for a full test report.

**Comment by migueldiascosta** [comment]
Going in, thanks @smoors!

**Pull request merged**
