### PR TITLE
{bio}[foss/2018b] R-bundle-Bioconductor v3.7 w/ R 3.5.1

### PR DESCRIPTION
**Pull request by boegel**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in this PR)
node2619.swalot.os - Linux centos linux 7.5.1804, Intel(R) Xeon(R) CPU E5-2660 v3 @ 2.60GHz, Python 2.7.5
See https://gist.github.com/1b03bb1c296705d5b48df1928e355ab1 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in this PR)
node2094.delcatty.os - Linux centos linux 7.5.1804, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.7.5
See https://gist.github.com/5bc178fb993ea611743cda914ac308ca for a full test report.

**Comment by verdurin** [comment]
Test report by @verdurin
**FAILED**
Build succeeded for 25 out of 29 (2 easyconfigs in this PR)
easybuild.novalocal - Linux centos linux 7.5.1804, Intel Xeon E312xx (Sandy Bridge), Python 2.7.5
See https://gist.github.com/b81daddab3f5f8abb16ebc038a23c0ab for a full test report.

**Comment by verdurin** [comment]
Trying again to build this one and I'm seeing a problem with the new `Java` support:
```
== resolving dependencies ...
== processing EasyBuild easyconfig /home/centos/src/github/easybuild-easyconfigs/easybuild/easyconfigs/j/Java/Java-1.8.eb
== building and installing Java/1.8...
== fetching files...
== creating build dir, resetting environment...
== unpacking...
== patching...
== preparing...
== configuring...
== building...
== testing...
== installing...
== taking care of extensions...
== postprocessing...
== sanity checking...
== FAILED: Installation ended unsuccessfully (build directory: /home/centos/.local/easybuild/build/Java/1.8/dummy-dummy): build failed (first 300 chars): Module command 'module load Java/1.8' failed with exit code 1; stderr: Lmod has detected the following error: The following module(s) are unknown:
"Java/1.8"

Please check the spelling or version number. Also try "module spider ..."



; stdout: os.environ["LMOD_DEFAULT_MODULEPATH"] = "/tmp/eb-LFYFc
```

This is with both `6.5.1` and the new build `6.6.3` of `Lmod`, on `CentOS 7.5`.

If this is a real bug, I'll report it separately.

**Comment by boegel** [comment]
@verdurin That's a known problem, still working on a fix for that, coming soon...

**Comment by boegel** [comment]
see https://github.com/easybuilders/easybuild/issues/462

**Comment by boegel** [comment]
@verdurin Please retest on top of https://github.com/easybuilders/easybuild-easyblocks/pull/1539 (which requires https://github.com/easybuilders/easybuild-framework/pull/2611)

**Comment by verdurin** [comment]
@boegel is there a nice equivalent of `--include-easyblocks` for testing with `framework` PRs?

**Comment by boegel** [comment]
@verdurin There isn't yet, but that would be a nice feature indeed...

It would be a kind of chicking-egg problem sometimes though, for example when the framework PR adds a new configuration option.

Maybe enhancing `--from-pr` would be possible, but that would involve starting a new EasyBuild session in a sadbox through `eb`, not sure what kind of surprises that would result into...

Let's wait until @vanzod merges https://github.com/easybuilders/easybuild-framework/pull/2611 and https://github.com/easybuilders/easybuild-easyblocks/pull/1539, and then re-test on top of `develop`?

**Comment by vanzod** [comment]
Test report by @vanzod
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in this PR)
cermis - Linux debian 9.5, Intel(R) Xeon(R) CPU           E5620  @ 2.40GHz, Python 2.7.13
See https://gist.github.com/8efc1306aaae7fe3c9e969a1b4fcd1df for a full test report.

**Comment by vanzod** [comment]
FYI, my last test was on top of `develop` after I merged the PRs @boegel mentioned.

**Comment by verdurin** [comment]
@boegel (having updated my shamelessly out of date forks...) I've started it and it's got past the `Java` problem.

**Comment by verdurin** [comment]
Test report by @verdurin
**SUCCESS**
Build succeeded for 4 out of 4 (2 easyconfigs in this PR)
easybuild.novalocal - Linux centos linux 7.5.1804, Intel Xeon E312xx (Sandy Bridge), Python 2.7.5
See https://gist.github.com/4b19f27cdf3cefcec5fe2dbd922ef57a for a full test report.

**Comment by verdurin** [comment]
Going in, thanks @boegel!

**Pull request merged**
