### PR TITLE
{tools}[GCCcore-6.4.0] jq (REVIEW)

### PR DESCRIPTION
**Pull request by hajgato**

### CODE REVIEW

**Comment by migueldiascosta** [comment]
Test report by @migueldiascosta
**FAILED**
Build succeeded for 0 out of 1 (1 easyconfigs in this PR)
grc-cluster1 - Linux centos 6.9, Intel(R) Xeon(R) CPU E5-2640 0 @ 2.50GHz, Python 2.7.14
See https://gist.github.com/c909df0f4c222b96abdae109081da631 for a full test report.

**Comment by migueldiascosta** [comment]
@hajgato seems to need `Bison` >= 3 as a dependency

**Comment by hajgato** [comment]
@migueldiascosta Done!

**Comment by migueldiascosta** [comment]
Test report by @migueldiascosta
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
grc-cluster1 - Linux centos 6.9, Intel(R) Xeon(R) CPU E5-2640 0 @ 2.50GHz, Python 2.7.14
See https://gist.github.com/7cb92c0c4c2e47e14e3b65d566034145 for a full test report.

**Comment by migueldiascosta** [comment]
Going in, thanks @hajgato!

**Pull request merged**
