### PR TITLE
{chem}[foss/2020b,intel/2020b] Wannier90 v3.1.0

### PR DESCRIPTION
**Pull request by schiotz**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by schiotz** [comment]
QA note:

I had to add a compiler option to mpifort when using the foss toolchain, as GCC 10.X is more picky when it comes to calling the same Fortran function multiple times with different argument types - in this case calls to MPI function which are passed a buffer array of different types.

I added the flag to the ``buildopts`` line, is that correct?  Line 21 in ``Wannier90-3.1.0-foss-2020b.eb``

**Review by Micket — APPROVED** [review]
lgtm

**Comment by Micket** [comment]
Test report by @Micket
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in total)
vera-c1 - Linux centos linux 7.9.2009, x86_64, Intel Xeon Processor (Skylake), Python 2.7.5
See https://gist.github.com/88ae894f3c8248e0b198025fdaeca9e5 for a full test report.

**Comment by Micket** [comment]
@boegelbot please test @ generoso

**Comment by Micket** [comment]
Going in, thanks @schiotz!

**Pull request merged**
