### PR TITLE
add pkg-config build dependency to recent Rust easyconfigs

### PR DESCRIPTION
**Pull request by sassy-crick**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by Micket** [comment]
Note: We are waiting until we have a fixed the missing pkgconfig files in OpenSSL

**Comment by boegel** [comment]
> Note: We are waiting until we have a fixed the missing pkgconfig files in OpenSSL

Do we have an issue on that? Is someone already working on it? @lexming?

**Comment by boegel** [comment]
Another (better?) option here could be to point the `openssl` component of Rust to the location where we provide (the wrapper for) OpenSSL: https://docs.rs/openssl/0.10.29/openssl/#manual

That should boil down to setting `$OPENSSL_DIR` to `$EBROOTOPENSSL` (and maybe also define `$OPENSSL_NO_PKG_CONFIG`, but the docs are hazy on that...)

**Comment by sassy-crick** [comment]
> > Note: We are waiting until we have a fixed the missing pkgconfig files in OpenSSL
> 
> Do we have an issue on that? Is someone already working on it? @lexming?

We have one [here](https://github.com/easybuilders/easybuild-easyblocks/issues/2525)

**Comment by boegel** [comment]
Test report by @boegel
**FAILED**
Build succeeded for 0 out of 1 (1 easyconfigs in total)
node3111.skitty.os - Linux centos linux 7.9.2009, x86_64, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz, Python 3.6.8
See https://gist.github.com/44a87a18d603449a42673f82659d0d88 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
node3585.doduo.os - Linux RHEL 8.2, x86_64, AMD EPYC 7552 48-Core Processor (zen2), Python 3.6.8
See https://gist.github.com/84af377b3e54e18116347622a2251ad5 for a full test report.

**Comment by lexming** [comment]
Test report by @lexming
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
node379.hydra.os - Linux centos linux 7.9.2009, x86_64, Intel(R) Xeon(R) Gold 6148 CPU @ 2.40GHz, Python 2.7.5
See https://gist.github.com/37f4671540c0fd706834f5914f7a90a8 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
easybuild2.novalocal - Linux centos linux 8.3.2011, POWER, IBM pSeries (emulated by qemu) (power9le), Python 3.6.8
See https://gist.github.com/41ca8254cc50810d0600d616d4c0cc17 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
node3107.skitty.os - Linux centos linux 7.9.2009, x86_64, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz, Python 3.6.8
See https://gist.github.com/2c423c7ebeb8c40a0251880d4030b802 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in total)
node3107.skitty.os - Linux centos linux 7.9.2009, x86_64, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz, Python 3.6.8
See https://gist.github.com/3bbd6435e691a1316922dfcf4e31bc44 for a full test report.

**Review by boegel — APPROVED** [review]
lgtm

**Comment by boegel** [comment]
Going in, thanks @sassy-crick!

**Pull request merged**
