### PR TITLE
{bio}[GCCcore/8.2.0] Seeder v0.01 w/ Perl/5.28.1

### PR DESCRIPTION
**Pull request by JackPerdue**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by migueldiascosta** [comment]
Test report by @migueldiascosta
**SUCCESS**
Build succeeded for 5 out of 5 (5 easyconfigs in this PR)
generoso - Linux centos linux 7.6.1810, Intel(R) Xeon(R) CPU E5-2660 v4 @ 2.00GHz, Python 3.6.8
See https://gist.github.com/9ea0219fb5275d0d598964075ab88af8 for a full test report.

**Comment by boegel** [comment]
@JackPerdue Why not add all of these (except maybe `Seeder` itself) to the `Perl` easyconfig?

We don't want to start having separate modules for all possible Perl modules I think...

**Comment by verdurin** [comment]
@JackPerdue Any thoughts on @boegel's comment?

**Comment by JackPerdue** [comment]
I think the current R easyconfigs are ridiculous and problematic.   600 modules in the core build is nuts.  I experimented with the opposite approach.

http://www.siliconslick.com/easybuild/R_madness/easyconfigs/

Its a little crazy too but at least you don't have to build 600 modules before failing a sanity check.  And every dependency for R modules are documented.

Anyway... I don't have the energy to try to get a change merged into the core Perl easyconfig.  Y'all do what you like with this.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
node3521.doduo.os - Linux RHEL 8.2, x86_64, AMD EPYC 7552 48-Core Processor (zen2), Python 3.6.8
See https://gist.github.com/5c35cab654cdf4163daf6131693a605d for a full test report.

**Comment by boegel** [comment]
@boegelbot please test @ generoso

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
node2728.swalot.os - Linux centos linux 7.9.2009, x86_64, Intel(R) Xeon(R) CPU E5-2660 v3 @ 2.60GHz (haswell), Python 3.6.8
See https://gist.github.com/1ead0cff13af14274484dfc3dbca8124 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
node3110.skitty.os - Linux centos linux 7.9.2009, x86_64, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz, Python 3.6.8
See https://gist.github.com/f8fc1028b320155c5d57b3323e1bc00f for a full test report.

**Review by boegel — APPROVED** [review]
lgtm

**Comment by boegel** [comment]
Going in, thanks @JackPerdue!

**Pull request merged**
