### PR TITLE
{lang}[foss/2019a,intel/2019a] V8 v2.3

### PR DESCRIPTION
**Pull request by vanzod**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by vanzod** [comment]
Test report by @vanzod
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in this PR)
cermis - Linux debian 9.9, Intel(R) Xeon(R) CPU           X5670  @ 2.93GHz, Python 2.7.13
See https://gist.github.com/bda32618c8eec59cedfba8c7fb46cbd9 for a full test report.

**Comment by terjekv** [comment]
Closing and reopening to restart travis.

**Comment by terjekv** [comment]
Test report by @terjekv
**FAILED**
Build succeeded for 2 out of 14 (2 easyconfigs in this PR)
ninhursaga.uio.no - Linux RHEL 8.2, x86_64, Intel(R) Xeon(R) Silver 4216 CPU @ 2.10GHz (cascadelake), Python 3.6.8
See https://gist.github.com/5a855e95390a7f570bcae9cd6223a9b9 for a full test report.

**Comment by terjekv** [comment]
@vanzod I lack the intel compilers to test that EasyConfig, and the http URLs need to be rewritten for to https. Apart from that it now looks good.

**Review by boegel — APPROVED** [review]
lgtm, test reports coming up

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in this PR)
node3407.kirlia.os - Linux centos linux 7.8.2003, x86_64, Intel(R) Xeon(R) Gold 6240 CPU @ 2.60GHz (cascadelake), Python 2.7.5
See https://gist.github.com/2b4b4ee5246932010fd1825cccf6481c for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in this PR)
node3159.skitty.os - Linux centos linux 7.8.2003, x86_64, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz, Python 3.6.8
See https://gist.github.com/241aa0e35e77847372b161232e955dfb for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in this PR)
node2492.golett.os - Linux centos linux 7.8.2003, x86_64, Intel(R) Xeon(R) CPU E5-2680 v3 @ 2.50GHz (haswell), Python 2.7.5
See https://gist.github.com/7fc3f9fa4f5b833cc3d399f0fa9e6a04 for a full test report.

**Comment by boegel** [comment]
Going in, thanks @vanzod!

**Pull request merged**
