### PR TITLE
{bio}[GCC/10.2.0] bcl2fastq2 v2.20.0

### PR DESCRIPTION
**Pull request by justbennet**
(created using `eb --new-pr`)
New bcl2fastq2 for GCC patched to build own Boost

### CODE REVIEW

**Comment by lexming** [comment]
Test report by @lexming
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
node378.hydra.os - Linux centos linux 7.9.2009, x86_64, Intel(R) Xeon(R) Gold 6148 CPU @ 2.40GHz, Python 2.7.5
See https://gist.github.com/4485d409a43901e2c42bb193b4301119 for a full test report.

**Review by lexming — CHANGES_REQUESTED** [review]
Thanks for updating this easyconfig. I tried to make it work with Boost v1.74.0 (the version in this toolchain) and it's indeed not compatible. Since it's not trivial to fix, I agree on using the bundled Boost sources.

Nonetheless, we can improve the situation with the other bundled dependencies of bcl2fastq2 and make it use CMake, libxml2 and libxslt from EasyBuild. By reviewing this PR, I ended up modifying its cmake build files to work with EB. Please check my PR to this one with my changes: https://github.com/justbennet/easybuild-easyconfigs/pull/1

If you agree with my changes, please just merge it and it will automatically update this PR.

**Comment by lexming** [comment]
Test report by @lexming
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
node381.hydra.os - Linux centos linux 7.9.2009, x86_64, Intel(R) Xeon(R) Gold 6148 CPU @ 2.40GHz, Python 2.7.5
See https://gist.github.com/e612d31baedcde6934f460788ea97a00 for a full test report.

**Review by lexming — APPROVED** [review]
LGTM

**Comment by verdurin** [comment]
@boegelbot please test @ generoso

**Comment by verdurin** [comment]
Test report by @verdurin
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
nuc.lan - Linux Fedora 33, x86_64, Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz, Python 3.9.4
See https://gist.github.com/94c4ce5ddf60f8d83d209ffcc79f9474 for a full test report.

**Review by verdurin — APPROVED** [review]
Looks fine.

**Comment by verdurin** [comment]
Going in, thanks @justbennet!

**Pull request merged**
