### PR TITLE
{compiler}[system/system] iccifort v2020.0.166

### PR DESCRIPTION
**Pull request by bartoldeman**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by bartoldeman** [comment]
This version doesn't seem to be affected by https://github.com/easybuilders/easybuild-easyconfigs/issues/9478

**Comment by bartoldeman** [comment]
closing to retrigger tests

**Comment by bartoldeman** [comment]
Test report by @bartoldeman
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
build-node.computecanada.ca - Linux centos linux 7.7.1908, Intel Xeon Processor (Skylake, IBRS), Python 3.7.5
See https://gist.github.com/66b70027fa03a7c2d7b8280ef378cea5 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
generoso - Linux centos linux 7.6.1810, Intel(R) Xeon(R) CPU E5-2660 v4 @ 2.00GHz, Python 3.6.8
See https://gist.github.com/4f3673396e900f343d4d8d7ab40473b8 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
node3103.skitty.os - Linux centos linux 7.7.1908, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz, Python 3.6.8
See https://gist.github.com/aebc89900b2331826fe27b6a28649187 for a full test report.

**Comment by boegel** [comment]
Going in, thanks @bartoldeman!

**Pull request merged**
