### PR TITLE
add SDL2 dependency for FFmpeg 5.0.1 to build ffplay

### PR DESCRIPTION
**Pull request by hattom**
with `SDL2`, FFmpeg will also install `ffplay`, which allows the playing of videos.

### CODE REVIEW

**Comment by boegel** [comment]
@boegelbot please test @ generoso

**Comment by jfgrimm** [comment]
Test report by @jfgrimm
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
node087.pri.viking.alces.network - Linux CentOS Linux 7.9.2009, x86_64, Intel(R) Xeon(R) Gold 6138 CPU @ 2.00GHz (skylake_avx512), Python 3.6.8
See https://gist.github.com/2e30699bb11bf0f19c3e1f9689e1983f for a full test report.

**Comment by jfgrimm** [comment]
@boegelbot please test @ jsc-zen2

**Review by jfgrimm — APPROVED** [review]
lgtm

**Comment by boegel** [comment]
Going in, thanks @hattom!

**Pull request merged**
