### PR TITLE
{bio}[GCCcore/8.2.0] cutadapt v1.18 w/ Python 2.7.15 + 3.7.2

### PR DESCRIPTION
**Pull request by Darkless012**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by Darkless012** [comment]
Test report by @Darkless012
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
node3241.victini.os - Linux centos linux 7.6.1810, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz, Python 2.7.5
See https://gist.github.com/f7c95d8db41bc1419a81eafa884bcdb4 for a full test report.

**Comment by migueldiascosta** [comment]
@Darkless012 although you're only updating the version, the tests are going to complain about the use of http in the homepage

**Comment by migueldiascosta** [comment]
Test report by @migueldiascosta
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
generoso - Linux centos linux 7.6.1810, Intel(R) Xeon(R) CPU E5-2660 v4 @ 2.00GHz, Python 3.6.8
See https://gist.github.com/14fbfee166fbe3d3c234603b4e78f023 for a full test report.

**Comment by migueldiascosta** [comment]
@Darkless012 this can use `multi_deps` and be moved down to either `GCC` or `GCCcore`, no?

**Comment by boegel** [comment]
@Darkless012 Looks like some existing easyconfigs have `xopen` missing, which is required by `cutadapt.seqio` and `cutadapt.pipeline`, so you should use `PythonBundle` + add `xopen` as extensin, see the existing `cutadapt-1.18-intel-2018b-Python-3.6.6.eb`

**Comment by boegel** [comment]
@Darkless012 The best way to catch this is to add this to the easyconfig:

```python
sanity_check_commands = [
    "cutadapt --help",
    "python -c 'import cutadapt.seqio'",  # requires xopen
]
```

since:

```
$ python -c 'import cutadapt.seqio'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/software/cutadapt/1.18-GCCcore-8.2.0/lib/python3.7/site-packages/cutadapt/seqio.py", line 14, in <module>
    from xopen import xopen
ModuleNotFoundError: No module named 'xopen'
```

**Comment by boegel** [comment]
see also #9219

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
generoso - Linux centos linux 7.6.1810, Intel(R) Xeon(R) CPU E5-2660 v4 @ 2.00GHz, Python 3.6.8
See https://gist.github.com/aeff9c6695b26a1acd897d0a94299c9d for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
node3141.skitty.os - Linux centos linux 7.6.1810, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz, Python 3.6.8
See https://gist.github.com/6b5c2deced1affcfdf8d57f72598666e for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
node2401.golett.os - Linux centos linux 7.6.1810, Intel(R) Xeon(R) CPU E5-2680 v3 @ 2.50GHz, Python 2.7.5
See https://gist.github.com/06e0c6399ae6ae75f76b0d474c8ac302 for a full test report.

**Comment by boegel** [comment]
Going in, thanks @Darkless012!

**Pull request merged**
