### PR TITLE
{devel}[GCCcore/12.3.0] ReFrame v4.6.1

### PR DESCRIPTION
**Pull request by benczaja**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by verdurin** [comment]
Test report by @verdurin
**FAILED**
Build succeeded for 0 out of 1 (1 easyconfigs in total)
easybuild-c7.novalocal - Linux CentOS Linux 7.9.2009, x86_64, Intel Xeon Processor (Skylake, IBRS), Python 3.6.8
See https://gist.github.com/verdurin/7d1bf3ced036d2e6fb9a957cf6ac0c64 for a full test report.

**Comment by verdurin** [comment]
Looks like you need to add `libxml2` and `libxslt` dependencies:
```
== 2024-07-01 10:47:48,023 run.py:221 DEBUG run_cmd: running cmd  /bin/python3 -m pip install --prefix=/eb/maint/software/ReFrame/4.6.1  --verbose  --no-deps  --ignore-installed  --no-index  --no-build-isolation  . (in /dev/shm/ReFrame/4.6.1/system-system/lxml/lxml-5.0.1)
== 2024-07-01 10:47:48,024 run.py:247 INFO running cmd:  /bin/python3 -m pip install --prefix=/eb/maint/software/ReFrame/4.6.1  --verbose  --no-deps  --ignore-installed  --no-index  --no-build-isolation  .
== 2024-07-01 10:47:48,818 build_log.py:171 ERROR EasyBuild crashed with an error (at easybuild/base/exceptions.py:126 in __init__): cmd " /bin/python3 -m pip install --prefix=/eb/maint/software/ReFrame/4.6.1  --verbose  --no-deps  --ignore-installed  --no-index  --no-build-isolation  ." exited with exit code 1 and output:
Using pip 21.3.1 from /eb/maint/software/ReFrame/4.6.1/lib/python3.6/site-packages/pip-21.3.1-py3.6.egg/pip (python 3.6)
Processing /dev/shm/ReFrame/4.6.1/system-system/lxml/lxml-5.0.1
  Preparing metadata (setup.py): started
  Running command python setup.py egg_info
  Building lxml version 5.0.1.
  Building without Cython.
  Error: Please make sure the libxml2 and libxslt development packages are installed.
  Preparing metadata (setup.py): finished with status 'error'
WARNING: Discarding file:///dev/shm/ReFrame/4.6.1/system-system/lxml/lxml-5.0.1. Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
 (at easybuild/tools/run.py:682 in parse_cmd_output)
 ```

**Comment by benczaja** [comment]
@verdurin i have added `libxml2` and `libxslt` dependencies. And I have renamed the easyconfig to `ReFrame-4.6.1-GCCcore-12.3.0.eb` to reflect the new dependencies. 

Please test again

**Comment by laraPPr** [comment]
Test report by @laraPPr
**FAILED**
Build succeeded for 0 out of 1 (1 easyconfigs in total)
node4008.donphan.os - Linux RHEL 8.8 (Ootpa), x86_64, Intel(R) Xeon(R) Gold 6240 CPU @ 2.60GHz, 1 x NVIDIA NVIDIA A2, 545.23.08, Python 3.11.3
See https://gist.github.com/laraPPr/49c7d410c2e43bad3bdbc3bbac453e40 for a full test report.

**Review by laraPPr — CHANGES_REQUESTED** [review]

**Comment by gkaf89** [comment]
I am not sure about the use of `exts_list` to download packages. The ReFrame installer seems to download all the required packages, is it necessary to download the packages again?

I created a [pull request for 4.6.2](https://github.com/easybuilders/easybuild-easyconfigs/pull/21189) that seems to work without downloading any packages.

**Comment by benczaja** [comment]
@casparvl  Yes I agree please close this PR. BTW the use of`%(installdir)/external` in https://github.com/easybuilders/easybuild-easyconfigs/pull/21269 is MUCH better. I guess I shouldn't have brut forced my way through all the python packages. But yes, please close this for https://github.com/easybuilders/easybuild-easyconfigs/pull/21269

**Pull request closed without merging**
