### PR TITLE
{devel}[GCCcore/8.2.0] Bazel v0.26.0

### PR DESCRIPTION
**Pull request by boegel**
(created using `eb --new-pr`)
requires https://github.com/easybuilders/easybuild-easyblocks/pull/1741

### CODE REVIEW

**Comment by boegel** [comment]
I created this in an attempt to replace the Bazel 0.20.0 we're using for building TensorFlow 1.13.1, since that would avoid requiring Java 1.8 (for which we can't auto-download the sources), but that doesn't work because:

i) TensorFlow 1.13.1 requires Bazel < 0.21.0
ii) only sufficiently recent versions of Bazel support Java 11

Could still be useful going forward though...

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
node3151.skitty.os - Linux centos linux 7.6.1810, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz, Python 2.7.5
See https://gist.github.com/2bc8d429e4f476261631ec80dc135560 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
node2009.delcatty.os - Linux centos linux 7.6.1810, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.7.5
See https://gist.github.com/0f5b92f911e2b0ac281a260f096c36cd for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
node2477.golett.os - Linux centos linux 7.6.1810, Intel(R) Xeon(R) CPU E5-2680 v3 @ 2.50GHz, Python 2.7.5
See https://gist.github.com/624e082d08ef1c5f89182c6542678858 for a full test report.

**Comment by akesandgren** [comment]
What about the Java versino conflict? Just ignore and force merge or?

**Comment by boegel** [comment]
@akesandgren That's probably not a good idea, we should stick to a single `Java` version per easyconfigs generation, or we'll have conflicts on our hands in no time...

Since this Bazel version is actually not of much use yet, I'll proceed with closing this; we can make the jump to a more recent Bazel version with `Java/11` for the `2019b` generation (assuming TensorFlow supports a sufficiently recent Bazel)...

**Pull request closed without merging**
