### PR TITLE
{chem,devel,numlib}[GCCcore/13.2.0,foss/2023b,gompi/2023b] ESPResSo v4.2.2, Boost.MPI v1.83.0, Pint v0.24

### PR DESCRIPTION
**Pull request by bedroge**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by bedroge** [comment]
@boegelbot please test @ jsc-zen3

**Comment by bedroge** [comment]
@boegelbot please test @ generoso

**Comment by bedroge** [comment]
Test report by @bedroge
**FAILED**
Build succeeded for 10 out of 11 (3 easyconfigs in total)
interactive1 - Linux Rocky Linux 8.9, x86_64, AMD EPYC-Milan Processor (zen2), Python 3.6.8
See https://gist.github.com/bedroge/b347b07448a5583c971e268f37805a68 for a full test report.

**Review by ocaisa — APPROVED** [review]
LGTM

**Pull request merged**
