### PR TITLE
{compiler}[system/system] intel-compilers v2021.3.0

### PR DESCRIPTION
**Pull request by robert-mijakovic**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by robert-mijakovic** [comment]
@boegelbot please test @ generoso

**Comment by robert-mijakovic** [comment]
Test report by @robert-mijakovic
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
login01.meluxina.lxp.lu - Linux RHEL 8.3, x86_64, AMD EPYC 7452 32-Core Processor (zen2), Python 3.6.8
See https://gist.github.com/be3f0e380cf8a709c1c703f08ecbe269 for a full test report.

**Comment by sassy-crick** [comment]
Test report by @sassy-crick
**FAILED**
Build succeeded for 0 out of 1 (1 easyconfigs in total)
jon-Precision-Tower-7910 - Linux debian 10.10, x86_64, Intel(R) Xeon(R) CPU E5-2623 v3 @ 3.00GHz, Python 3.7.3
See https://gist.github.com/96c53362044c0de24a732c49f55be115 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
node3110.skitty.os - Linux centos linux 7.9.2009, x86_64, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz, Python 3.6.8
See https://gist.github.com/fc0b275ba0b85ed123c04ac074668a3f for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
node3513.doduo.os - Linux RHEL 8.2, x86_64, AMD EPYC 7552 48-Core Processor (zen2), Python 3.6.8
See https://gist.github.com/9e70e62dbd0f32a54bc00fb790755589 for a full test report.

**Comment by boegel** [comment]
@sassy-crick Test report failed because `GCCcore/10.3.0` was missing, so I'll ignore that. :)

**Review by boegel — APPROVED** [review]
lgtm

**Comment by boegel** [comment]
Going in, thanks @robert-mijakovic!

**Comment by sassy-crick** [comment]
> @sassy-crick Test report failed because `GCCcore/10.3.0` was missing, so I'll ignore that. :)

Yes, that was me trying something the wrong way which is why I deleted the wrong report. :)

**Pull request merged**
