### PR TITLE
{vis}[fosscuda/2018b] GST-plugins-base v1.15.1

### PR DESCRIPTION
**Pull request by akesandgren**
(created using `eb --new-pr`)
Depends on ~~https://github.com/easybuilders/easybuild-easyconfigs/pull/7660, https://github.com/easybuilders/easybuild-easyconfigs/pull/7639~~ and ~~https://github.com/easybuilders/easybuild-easyconfigs/pull/7889~~

### CODE REVIEW

**Comment by boegel** [comment]
kicking Travis...

**Comment by boegel** [comment]
Test report by @boegel
**FAILED**
Build succeeded for 0 out of 1 (1 easyconfigs in this PR)
node2012.delcatty.os - Linux centos linux 7.6.1810, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.7.5
See https://gist.github.com/4e4732fdeb417c5af4c931264062fcd2 for a full test report.

**Comment by boegel** [comment]
@akesandgren Hmm, this is not working for me...

```
configure: Package 'libdw', required by 'gstreamer-1.0', not found
configure: error: no gstreamer-1.0 >= 1.15.1 (GStreamer) found
```

from `config.log`:

```
Package libdw was not found in the pkg-config search path.
Perhaps you should add the directory containing `libdw.pc'
to the PKG_CONFIG_PATH environment variable
Package 'libdw', required by 'gstreamer-1.0', not found
configure:25547: $? = 1
Package 'libdw', required by 'gstreamer-1.0', not found
configure:25575: result: no
configure:25579: Package 'libdw', required by 'gstreamer-1.0', not found
configure:25582: error: no gstreamer-1.0 >= 1.15.1 (GStreamer) found
```

**Comment by akesandgren** [comment]
Nah, I had libdw-dev installed when building GStreamer, so the problem isn't here but in GStreamer.

I'll see what i can do about it quickly.

**Comment by akesandgren** [comment]
@boegel don't forget a new test of this one after the GStreamer merge.

**Comment by akesandgren** [comment]
Test report by @akesandgren
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
b-an03.hpc2n.umu.se - Linux ubuntu 16.04, Intel(R) Xeon(R) CPU E5-2690 v4 @ 2.60GHz, Python 2.7.12
See https://gist.github.com/40af74ece1b0b446a7c5b0dae46101be for a full test report.

**Comment by migueldiascosta** [comment]
Test report by @migueldiascosta
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
grc-cluster1 - Linux centos 6.10, Intel(R) Xeon(R) CPU E5-2640 0 @ 2.50GHz, Python 2.7.14
See https://gist.github.com/791e0b62a8332f1f1ecb6ccd0ff63cd0 for a full test report.

**Comment by akesandgren** [comment]
Ignore this for the time being, ,it should be moved down to GCC or GCCcore level.

**Comment by boegel** [comment]
deprecated toolchain, and we already have GST-plugins-base  easyconfigs merged that use GCCcore as toolchain (see #12584 for example), so closing this...

**Pull request closed without merging**
