### PR TITLE
{system}[GCC/10.3.0,system/system] CUDAcore v11.4.0

### PR DESCRIPTION
**Pull request by robert-mijakovic**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by robert-mijakovic** [comment]
@boegelbot please test @ generoso

**Comment by branfosj** [comment]
@boegelbot please test @ generoso

**Comment by branfosj** [comment]
My testing is blocked by https://github.com/easybuilders/easybuild-easyblocks/issues/2497 but this should be fine.

**Comment by Micket** [comment]
I don't think we need or want `CUDA-11.4.0-GCC-10.3.0.eb` since we are planning on merging this info foss.

**Comment by robert-mijakovic** [comment]
Ok, I can remove it.

**Comment by robert-mijakovic** [comment]
@Micket Done!

**Comment by robert-mijakovic** [comment]
@Micket @branfosj I guess, this one is done.

**Comment by verdurin** [comment]
Test report by @verdurin
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
nuc.lan - Linux Fedora 33, x86_64, Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz, Python 3.9.5
See https://gist.github.com/33ec56e8b32311ed51676976f0607550 for a full test report.

**Comment by verdurin** [comment]
Test report by @verdurin
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
easybuild-c7.novalocal - Linux centos linux 7.9.2009, x86_64, Intel Xeon Processor (Skylake, IBRS), Python 3.6.8
See https://gist.github.com/43e3c30fb08ace807060c825d1a534ee for a full test report.

**Comment by boegel** [comment]
@boegelbot please test @ generoso

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
node3148.skitty.os - Linux centos linux 7.9.2009, x86_64, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz (skylake_avx512), Python 3.6.8
See https://gist.github.com/509329ceab19bb4a51f8acbc353844e7 for a full test report.

**Review by boegel — APPROVED** [review]
lgtm

**Comment by boegel** [comment]
Going in, thanks @robert-mijakovic!

**Pull request merged**
