### PR TITLE
{devel}[GCCcore/9.3.0] GObject-Introspection-1.64.0: Missing pkg-conf builddep added

### PR DESCRIPTION
**Pull request by sassy-crick**
(created using `eb --new-pr`)

### CODE REVIEW

**Review by Micket — APPROVED** [review]
lgtm

**Comment by Micket** [comment]
@boegelbot please test @ generoso

**Comment by Micket** [comment]
Test report by @Micket
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
vera-c1 - Linux centos linux 7.9.2009, x86_64, Intel Xeon Processor (Skylake), Python 2.7.5
See https://gist.github.com/4fac25453b76b952575719e543f5592e for a full test report.

**Comment by Micket** [comment]
Actually, can you do the same for 1.63.1 and 1.66.1 as well in this PR?

**Comment by sassy-crick** [comment]
I checked in the latest release of EB (4.3.3) and version 1.66.1 has pkg-config installed. 
The same goes for 1.63.1. It seems like I picked exactly the one which was not fixed. 
Do you want to double check?

**Comment by Micket** [comment]
You are right, i looked at the wrong line. Could you please move it to right under binutils so it's a bit more consistent with the others?

**Comment by sassy-crick** [comment]
Done. Usually I add things to the last line which is why it was there.

**Review by Micket — APPROVED** [review]
lgtm

**Comment by Micket** [comment]
Test report by @Micket
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
vera-c1 - Linux centos linux 7.9.2009, x86_64, Intel Xeon Processor (Skylake), Python 2.7.5
See https://gist.github.com/fed5e6023402870838a2fb335e3ebb50 for a full test report.

**Comment by Micket** [comment]
Going in, thanks @sassy-crick!

**Pull request merged**
