### PR TITLE
{lib}[GCCcore/13.2.0] Brunsli v0.1, GDAL v3.9.0, libgeotiff v1.7.3, ...

### PR DESCRIPTION
**Pull request by Micket**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by bedroge** [comment]
@boegelbot please test @ jsc-zen3

**Comment by bedroge** [comment]
@boegelbot please test @ generoso

**Comment by bedroge** [comment]
@Micket did this work for you? I'm getting this error:
```
[100%] Linking CXX executable cbrunsli
/data/apps/software/CMake/3.27.6-GCCcore-13.2.0/bin/cmake -E cmake_link_script CMakeFiles/cbrunsli.dir/link.txt --verbose=1
/data/apps/software/GCCcore/13.2.0/bin/g++ -O2 -ftree-vectorize -march=native -fno-math-errno -lbrotlienc -lbrotlidec -lbrotlicommon -O3 -DNDEBUG -O2 -L/data/apps/software/Highway/1.0.7-GCCcore-13.2.0/lib64 -L/data/apps/software/Highway/1.0.7-GCCcore-13.2.0/lib -L/data/apps/software/Brotli/1.1.0-GCCcore-13.2.0/lib64 -L/data/apps/software/Brotli/1.1.0-GCCcore-13.2.0/lib -L/data/apps/software/binutils/2.40-GCCcore-13.2.0/lib64 -L/data/apps/software/binutils/2.40-GCCcore-13.2.0/lib -L/data/apps/software/GCCcore/13.2.0/lib64 -L/data/apps/software/GCCcore/13.2.0/lib -rdynamic CMakeFiles/cbrunsli.dir/c/tools/cbrunsli.cc.o -o cbrunsli  libbrunslienc-static.a -lbrotlienc-static libbrunslicommon-static.a 
/data/apps/software/binutils/2.40-GCCcore-13.2.0/bin/ld: cannot find -lbrotlienc-static: No such file or directory
collect2: error: ld returned 1 exit status
```

**Comment by bedroge** [comment]
Same issue is reported in https://github.com/easybuilders/easybuild-easyconfigs/pull/20756, apparently something was changed in Brotli 1.1.0.

**Comment by Micket** [comment]
Sorry, I just bumped these because someone was asking for them in the slack channel, I hadn't had time to test them in depth, yeah, that linking thing needs fixing. dunno about downgrading it for that reason though, I would just have attempted to fix the linking.

**Comment by branfosj** [comment]
Add @Flamefire patch from https://github.com/google/brunsli/pull/145

**Comment by branfosj** [comment]
Though, saying that, I am not seeing any `.a` files in recent Brotli builds.

**Comment by boegel** [comment]
@boegelbot please test @ generoso

**Comment by Micket** [comment]
Test report by @Micket
**FAILED**
Build succeeded for 4 out of 6 (4 easyconfigs in total)
alvis-skylake-build - Linux Rocky Linux 8.9, x86_64, Intel Xeon Processor (Skylake, IBRS, no TSX), Python 3.6.8
See https://gist.github.com/Micket/ec987c8d57b664dd30db7abcbab21316 for a full test report.

**Comment by Micket** [comment]
Test report by @Micket
**SUCCESS**
Build succeeded for 4 out of 4 (4 easyconfigs in total)
alvis-skylake-build - Linux Rocky Linux 8.9, x86_64, Intel Xeon Processor (Skylake, IBRS, no TSX), Python 3.6.8
See https://gist.github.com/Micket/7c436fa5a0955a1760205c3d04bfbfcc for a full test report.

**Comment by Micket** [comment]
@boegelbot please test @ generoso

**Comment by boegel** [comment]
@boegelbot please test @ jsc-zen3

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 4 out of 4 (4 easyconfigs in total)
node3107.skitty.os - Linux RHEL 8.8, x86_64, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz, Python 3.6.8
See https://gist.github.com/boegel/512bab70b027cc7599c8ade2304737d3 for a full test report.

**Review by boegel — APPROVED** [review]
lgtm

**Pull request merged**
