### PR TITLE
[GCCcore/9.3.0] groff requires makeinfo as a build dep, which requires Perl, which requires groff. Break cyclic redundancy by adding Perl-minimal and makeinfo-minimal.

### PR DESCRIPTION
**Pull request by akesandgren**
(created using `eb --new-pr`)

Depends on https://github.com/easybuilders/easybuild-easyblocks/pull/2474

Solves https://github.com/easybuilders/easybuild-easyconfigs/issues/12067

### CODE REVIEW

**Comment by akesandgren** [comment]
Test report by @akesandgren
Using easyblocks from PR(s) https://github.com/easybuilders/easybuild-easyblocks/pull/2474
**SUCCESS**
Build succeeded for 9 out of 9 (9 easyconfigs in total)
b-an02.hpc2n.umu.se - Linux Ubuntu 20.04, x86_64, Intel(R) Xeon(R) CPU E5-2690 v4 @ 2.60GHz, Python 3.8.5
See https://gist.github.com/c64c2a0abc396964484e0f3571594638 for a full test report.

**Comment by SebastianAchilles** [comment]
Test report by @sebastianachilles
Using easyblocks from PR(s) https://github.com/easybuilders/easybuild-easyblocks/pull/2474
**SUCCESS**
Build succeeded for 9 out of 9 (9 easyconfigs in total)
rocky8-eb - Linux rocky linux 8.4, x86_64, Intel(R) Core(TM) i7-6900K CPU @ 3.20GHz (broadwell), Python 3.6.8
See https://gist.github.com/47f53a673229be968c1075cf02a21396 for a full test report.

**Comment by SebastianAchilles** [comment]
Test report by @sebastianachilles
Using easyblocks from PR(s) https://github.com/easybuilders/easybuild-easyblocks/pull/2474
**SUCCESS**
Build succeeded for 9 out of 9 (9 easyconfigs in total)
centos8-eb - Linux centos linux 8.3.2011, x86_64, Intel(R) Core(TM) i7-8700 CPU @ 3.20GHz (skylake), Python 3.6.8
See https://gist.github.com/dc5f6a45de21ea7b4eae4ca04c464392 for a full test report.

**Review by SebastianAchilles — CHANGES_REQUESTED** [review]
@akesandgren to fix the failing test an exception should be added for `Perl` with versionsuffix `-minimal` in `test/easyconfigs/easyconfigs.py`

**Comment by akesandgren** [comment]
Yeah, but I don't know how to write that exception, since it (currently) should only be allowed in makeinfo-minimal.
Trying to figure out the code snippets there...

**Review by SebastianAchilles — APPROVED** [review]
@akesandgren Thanks for adding the exception!
lgtm

**Comment by SebastianAchilles** [comment]
Going in, thanks @akesandgren!

**Comment by SebastianAchilles** [comment]
@boegelbot please test @ generoso

**Pull request merged**
