### PR TITLE
{lang}[GCCcore/11.3.0] cppyy v3.0.0

### PR DESCRIPTION
**Pull request by migueldiascosta**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by migueldiascosta** [comment]
@boegelbot please test @ generoso

**Comment by migueldiascosta** [comment]
@boegelbot please test @ jsc-zen2

**Review by boegel — DISMISSED** [review]
lgtm

**Comment by boegel** [comment]
@migueldiascosta
```
  In file included from /tmp/boegelbot/cppyy/3.0.0/GCCcore-11.3.0/cppyycling/cppyy-cling-6.28.0/src/interpreter/llvm/src/include/llvm/Support/BinaryStreamReader.h:16,
                   from /tmp/boegelbot/cppyy/3.0.0/GCCcore-11.3.0/cppyycling/cppyy-cling-6.28.0/src/interpreter/llvm/src/lib/Support/BinaryStreamReader.cpp:9:
  /tmp/boegelbot/cppyy/3.0.0/GCCcore-11.3.0/cppyycling/cppyy-cling-6.28.0/src/interpreter/llvm/src/include/llvm/Support/BinaryStreamArray.h:331:31: error: expected unqualified-id before const
    331 |   FixedStreamArrayIterator<T>(const FixedStreamArrayIterator<T> &Other)
        |                               ^~~~~
  /tmp/boegelbot/cppyy/3.0.0/GCCcore-11.3.0/cppyycling/cppyy-cling-6.28.0/src/interpreter/llvm/src/include/llvm/Support/BinaryStreamArray.h:331:31: error: expected ) before const
    331 |   FixedStreamArrayIterator<T>(const FixedStreamArrayIterator<T> &Other)
        |                              ~^~~~~
        |                               )
```

**Comment by migueldiascosta** [comment]
> @migueldiascosta
> 
> ```
>   In file included from /tmp/boegelbot/cppyy/3.0.0/GCCcore-11.3.0/cppyycling/cppyy-cling-6.28.0/src/interpreter/llvm/src/include/llvm/Support/BinaryStreamReader.h:16,
>                    from /tmp/boegelbot/cppyy/3.0.0/GCCcore-11.3.0/cppyycling/cppyy-cling-6.28.0/src/interpreter/llvm/src/lib/Support/BinaryStreamReader.cpp:9:
>   /tmp/boegelbot/cppyy/3.0.0/GCCcore-11.3.0/cppyycling/cppyy-cling-6.28.0/src/interpreter/llvm/src/include/llvm/Support/BinaryStreamArray.h:331:31: error: expected unqualified-id before const
>     331 |   FixedStreamArrayIterator<T>(const FixedStreamArrayIterator<T> &Other)
>         |                               ^~~~~
>   /tmp/boegelbot/cppyy/3.0.0/GCCcore-11.3.0/cppyycling/cppyy-cling-6.28.0/src/interpreter/llvm/src/include/llvm/Support/BinaryStreamArray.h:331:31: error: expected ) before const
>     331 |   FixedStreamArrayIterator<T>(const FixedStreamArrayIterator<T> &Other)
>         |                              ~^~~~~
>         |                               )
> ```

weird, I was able to build `cppyy` in the system where I was writing the easyconfigs, but I'm also able to reproduce this error on another, no idea what difference could explain this, will need to dig further later

**Comment by verdurin** [comment]
Test report by @verdurin
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
easybuild-c7.novalocal - Linux CentOS Linux 7.9.2009, x86_64, Intel Xeon Processor (Skylake, IBRS), Python 3.6.8
See https://gist.github.com/verdurin/a144c88bdd9e965527416164c9761dc1 for a full test report.

**Comment by migueldiascosta** [comment]
ffs... in `cppyy-cling`'s `setup.py`:

```python
# get C++ standard to use, if set
        try:
            stdcxx = os.environ['STDCXX']
        except KeyError:
            if is_manylinux():
                stdcxx = '14'
            else:
                stdcxx = '20'
```

```python
_is_manylinux = None
def is_manylinux():
    global _is_manylinux
    if _is_manylinux is None:
        _is_manylinux = False
        try:
            for line in open('/etc/redhat-release').readlines():
              # mark manylinux1, manylinux2010, or manylinux2014
                if 'CentOS release 5.11 (Final)' in line or \
                   'CentOS release 6.10 (Final)' in line or \
                   'CentOS Linux release 7.9.2009 (Core)' in line:
                    _is_manylinux = True
                    break
        except (OSError, IOError):
            pass
    return _is_manylinux
```

so, only those three CentOS versions are `manylinux` (eye roll...)

ok, let's try with

```python
('cppyy-cling', '6.28.0', {
        'modulename': False,
        'preinstallopts': 'export STDCXX=14 && ',
        'checksums': ['ae67fc338510d03b68dde08add5b519e2c6434d40fe07e23e7ebace3caa684e7'],
    }),
```

**Comment by migueldiascosta** [comment]
@boegelbot please test @ generoso

**Comment by zao** [comment]
Test report by @zao
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
eb-mix.zao.se - Linux Ubuntu 22.04.3 LTS (Jammy Jellyfish), x86_64, AMD Ryzen 9 3900X 12-Core Processor (zen2), Python 3.10.12
See https://gist.github.com/zao/6c71a34d3a19710fc0c8017a51c2c9fa for a full test report.

**Comment by migueldiascosta** [comment]
@boegelbot please test @ jsc-zen2

**Comment by migueldiascosta** [comment]
@boegelbot please test @ jsc-zen2 CORE_CNT=16

**Comment by jfgrimm** [comment]
Test report by @jfgrimm
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
node041.viking2.yor.alces.network - Linux Rocky Linux 8.8, x86_64, AMD EPYC 7643 48-Core Processor, Python 3.6.8
See https://gist.github.com/jfgrimm/46b02830801c329bdb2b4d11b8dd9ac7 for a full test report.

**Comment by jfgrimm** [comment]
Going in, thanks @migueldiascosta!

**Pull request merged**
