### PR TITLE
{cae,math,numlib}[gompi/2021b] OpenFOAM vv2112, CGAL v4.14.3, SCOTCH v6.1.2 w/ Python 3.9.6

### PR DESCRIPTION
**Pull request by boegel**
(created using `eb --new-pr`)
requires:
* #14606
* #14635

### CODE REVIEW

**Comment by boegel** [comment]
@boegelbot please test @ generoso
CORE_CNT=16

**Comment by verdurin** [comment]
Test report by @verdurin
**SUCCESS**
Build succeeded for 14 out of 14 (3 easyconfigs in total)
centos7.lan - Linux centos linux 7.9.2009, x86_64, Intel Core Processor (Skylake, IBRS), Python 3.6.8
See https://gist.github.com/d3c58b4b9a8cca36ec78f694307ffa53 for a full test report.

**Review by verdurin — APPROVED** [review]
Looks fine.

**Review by verdurin — APPROVED** [review]
Looks fine.

**Comment by verdurin** [comment]
Going in, thanks @boegel!

**Pull request merged**
