### PR TITLE
Only SAMtools < 1.0 works for ChimPipe

### PR DESCRIPTION
**Pull request by SethosII**
(created using `eb --new-pr`)

The options of `SAMtools` sort subcommand have changed in 1.0 and `ChimPipe` still uses the old options.

### CODE REVIEW

**Comment by verdurin** [comment]
@SethosII Would be useful to add a comment explaining this change of dependencies in the easyconfig itself?

**Comment by verdurin** [comment]
Test report by @verdurin
**FAILED**
Build succeeded for 19 out of 24 (1 easyconfigs in this PR)
easybuild.novalocal - Linux centos linux 7.4.1708, Intel Xeon E312xx (Sandy Bridge), Python 2.7.5
See https://gist.github.com/736dc55c7cd345b8a47c5ae86b8b6537 for a full test report.

**Comment by SethosII** [comment]
Uh, `eb --update-pr` is stuck on my terminal but pushed successfully and garbled the author. Seems to be related to https://github.com/easybuilders/easybuild-framework/issues/2415.

**Comment by SethosII** [comment]
I force-pushed the commit with the correct author.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
gligar02.gligar.os - Linux centos linux 7.4.1708, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.7.5
See https://gist.github.com/9dab3da793da6e7f87b88904d126f051 for a full test report.

**Comment by boegel** [comment]
Going in, thanks @SethosII!

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 3 out of 3 (1 easyconfigs in this PR)
node2524.golett.os - Linux centos linux 7.4.1708, Intel(R) Xeon(R) CPU E5-2680 v3 @ 2.50GHz, Python 2.7.5
See https://gist.github.com/837cb023a50709a0c1c92e6ddf22b84c for a full test report.

**Pull request merged**
