### PR TITLE
{vis}[foss/2017b,intel/2017b] OpenCV v3.3.0

### PR DESCRIPTION
**Pull request by vanzod**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by vanzod** [comment]
Test report by @vanzod
**SUCCESS**
Build succeeded for 4 out of 4 (4 easyconfigs in this PR)
cermis - Linux debian 9.8, Intel(R) Xeon(R) CPU           X5670  @ 2.93GHz, Python 2.7.13
See https://gist.github.com/c1b830b6bb04f4782e874afc739198ea for a full test report.

**Comment by verdurin** [comment]
Test report by @verdurin
**FAILED**
Build succeeded for 6 out of 23 (4 easyconfigs in this PR)
rescomp2 - Linux centos linux 7.3.1611, Intel(R) Xeon(R) Gold 6126 CPU @ 2.60GHz, Python 2.7.5
See https://gist.github.com/439aa62a3a371e5bd4092ce61f8f3c8d for a full test report.

**Comment by boegel** [comment]
@verdurin Any idea what went wrong on your end?

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 27 out of 27 (4 easyconfigs in this PR)
node3109.skitty.os - Linux centos linux 7.6.1810, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz, Python 2.7.5
See https://gist.github.com/94cff8f7ac115e8e0aef144bb372e086 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 12 out of 12 (4 easyconfigs in this PR)
node2400.golett.os - Linux centos linux 7.6.1810, Intel(R) Xeon(R) CPU E5-2680 v3 @ 2.50GHz, Python 2.7.5
See https://gist.github.com/afc7371d6c89781b769d349793f77518 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 4 out of 4 (4 easyconfigs in this PR)
node2002.delcatty.os - Linux centos linux 7.6.1810, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.7.5
See https://gist.github.com/3887b059f53b25471a7793ec5eb83a78 for a full test report.

**Comment by verdurin** [comment]
@boegel It's some local weirdness that I don't quite understand yet, so safe to ignore I think.

**Comment by verdurin** [comment]
Going in, thanks @vanzod!

**Pull request merged**
