### PR TITLE
{lang}[foss/2020a] numba v0.50.1 w/ Python 3.8.2

### PR DESCRIPTION
**Pull request by SimonPinches**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by Micket** [comment]
So, instead of adding LLVM 8, the next release of numba is really close now, and will support LLVM 9
https://github.com/numba/llvmlite/issues/523
It will probably be released before next EB release, so, shall we wait for that instead?

**Comment by SimonPinches** [comment]
@Micket Waiting for LLVM 9 support in numba sounds good to me since it seem imminent...

**Comment by Micket** [comment]
@SimonPinches Actually, looks like 0.50 was released 6 days ago

**Comment by SimonPinches** [comment]
@Micket Here's an updated easyconfig for numba (0.50.0) that uses LLVM 9.  (Pypi doesn't seem to have the tarball for numba/0.50.1 otherwise I've have bumped to that one).

**Comment by SimonPinches** [comment]
@Micket I guess all good things come to those who wait.  Here's `numba` v0.50.1 now.

**Comment by boegel** [comment]
@SimonPinches Apologies for the confusing comment, my bot needs a bit more work to correctly report on failing tests in GitHub Actions... :)

**Comment by Micket** [comment]
Hm, ok, so it seems that some others were quick to already merge a 0.50.0 version into 2020a while we weren't looking https://github.com/easybuilders/easybuild-easyconfigs/pull/10862
and that was already part of the 4.2.2 release.

https://numba.pydata.org/numba-doc/latest/release-notes.html

Do we consider the 0.50.1 fixes to be important enough to motivate including an extra numba into the toolchains?

**Review by boegel — APPROVED** [review]
lgtm

**Comment by boegel** [comment]
@boegelbot please test @ generoso

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
node3148.skitty.os - Linux centos linux 7.9.2009, x86_64, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz (skylake_avx512), Python 3.6.8
See https://gist.github.com/b1f4dbe05225a2e6d42d5d99d660f427 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
node3518.doduo.os - Linux RHEL 8.2, x86_64, AMD EPYC 7552 48-Core Processor (zen2), Python 3.6.8
See https://gist.github.com/97734c495bdcb438615f9deffdf4a907 for a full test report.

**Comment by boegel** [comment]
Going in, thanks @SimonPinches!

**Pull request merged**
