### PR TITLE
Fix p7zip path issues (Issue #13540)

### PR DESCRIPTION
**Pull request by krometis**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by Micket** [comment]
Could you also add the fix to version 17.04?

**Comment by krometis** [comment]
> Could you also add the fix to version 17.04?

Apologies. You beat me to it by a minute or two. This should be done in the commit that I just made.

**Comment by branfosj** [comment]
Can we add a sanity check command to catch this issue? I see this, which lists the problem:
```
$ 7z i

7-Zip [64] 17.04 : Copyright (c) 1999-2021 Igor Pavlov : 2017-08-28
p7zip Version 17.04 (locale=en_GB.UTF-8,Utf16=on,HugeFiles=on,64 bits,80 CPUs x64)

Can't load './7z.dll' (./7z.so: cannot open shared object file: No such file or directory)

Libs:

Formats:

Codecs:

Hashers:
```

The "Can't load" line goes away once we rebuild using the EasyConfigs in this PR.

**Review by Micket — APPROVED** [review]
lgtm, edit: Ah, I forgot about @branfosj  comment while i was reviewing the changes

**Comment by krometis** [comment]
Sorry, was busy with other things yesterday and had to figure out some annoying quote escaping but think the sanity check that I just uploaded catches the previous error. I added it to the old easyconfig and the build failed with
```
== FAILED: Installation ended unsuccessfully (build directory: /dev/shm/jkrometi/build/p7zip/17.03/GCCcore-10.2.0): build failed (first 300 chars): Sanity check failed: sanity check command ! 7z i | grep -q "Can't load" exited with code 1 (output: ) (took 22 sec)
```
and when I ran the new easyconfig (the one that I committed) it completed and the log said
```
== 2021-08-03 11:05:29,876 easyblock.py:3047 INFO sanity check command ! 7z i | grep -q "Can't load" ran successfully! (output: )
```

**Comment by krometis** [comment]
Sorry, I don't know why it's failing to parse - I'm sure it doesn't like how I've done the escaping but EasyBuild built the module just fine for me (after throwing parsing errors at other escape combinations that I attempted). Would someone else please take a look at this?

**Comment by Micket** [comment]
Something is rewriting the string as `"""! 7z i | grep -q "Can't load""""`  (which indeed it incorrect)  then tries to reparse it later on. 
I would suspect this happens whenever the last character is an escaped `"` and `'` is already used. We could add a space at the end of the string to avoid this, probably the easiest way out right now

**Comment by krometis** [comment]
Thanks, that seems to have fixed it. It would have taken me forever to find that/be willing to attempt something so simple.

**Review by Micket — APPROVED** [review]
lgtm

**Comment by Micket** [comment]
@boegelbot please test @ generoso

**Comment by Micket** [comment]
Test report by @Micket
**FAILED**
Build succeeded for 0 out of 2 (2 easyconfigs in total)
alvis-c1 - Linux centos linux 7.9.2009, x86_64, Intel Xeon Processor (Skylake), Python 3.6.8
See https://gist.github.com/43878f45063aaa5b5a996bb3d9fdf8c1 for a full test report.

**Comment by Micket** [comment]
Test report by @Micket
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in total)
alvis-c1 - Linux centos linux 7.9.2009, x86_64, Intel Xeon Processor (Skylake), Python 3.6.8
See https://gist.github.com/8a7e3d8d34313c8ee10371a1b1b0e8b4 for a full test report.

**Comment by Micket** [comment]
Going in, thanks @krometis!

**Pull request merged**
