### PR TITLE
cleanup of easyconfigs for (bundles) of Python packages: remove default PYPI_SOURCE source URLs + use PythonBundle rather than Bundle easyblock

### PR DESCRIPTION
**Pull request by Flamefire**
- Removed PyPi URLs from PythonPackage/PythonBundle ECs
- Convert Bundle -> PythonBundle (checked by CI, reduces amount of code in EC)
- Remove (now) redundant sanity-checks for python-site-packages folder
- Remove redundant (and checked by CI) download_dep_fail (sometimes even duplicated)
- Replace http urls by https as required by CI
- **DISABLE** sanity_pip_check and use_pip CI checks, to be **REMOVED** right after this was merged. Using this would require actually building those ECs
- [x] Requires https://github.com/easybuilders/easybuild-easyblocks/pull/2493
- [x] Requires https://github.com/easybuilders/easybuild-easyblocks/pull/2494

Test plan: Run with `--fetch`

### CODE REVIEW

**Comment by Flamefire** [comment]
Test report by @Flamefire
**FAILED**
Build succeeded for 3396 out of 3756 (1516 easyconfigs in total)
taurusa5 - Linux centos linux 7.7.1908, x86_64, Intel(R) Xeon(R) CPU E5-2603 v4 @ 1.70GHz (broadwell), Python 2.7.5
See https://gist.github.com/d78f8095b5b3a49ab77cc2a66975af02 for a full test report.

**Comment by Flamefire** [comment]
Test report by @Flamefire
**FAILED**
Build succeeded for 3518 out of 3754 (1513 easyconfigs in total)
taurusa5 - Linux centos linux 7.7.1908, x86_64, Intel(R) Xeon(R) CPU E5-2603 v4 @ 1.70GHz (broadwell), Python 2.7.5
See https://gist.github.com/8d5e238b552dcd984d57459800ad16cf for a full test report.

**Comment by Flamefire** [comment]
Test report by @Flamefire
Using easyblocks from PR(s) https://github.com/easybuilders/easybuild-easyblocks/pull/2493
**FAILED**
Build succeeded for 0 out of 1 (1 easyconfigs in total)
taurusa6 - Linux centos linux 7.7.1908, x86_64, Intel(R) Xeon(R) CPU E5-2603 v4 @ 1.70GHz (broadwell), Python 2.7.5
See https://gist.github.com/ffdfe5aaed1214f9bb41bef25bf12b61 for a full test report.

**Comment by Flamefire** [comment]
Test report by @Flamefire
Using easyblocks from PR(s) https://github.com/easybuilders/easybuild-easyblocks/pull/2493
**FAILED**
Build succeeded for 0 out of 1 (1 easyconfigs in total)
taurusa6 - Linux centos linux 7.7.1908, x86_64, Intel(R) Xeon(R) CPU E5-2603 v4 @ 1.70GHz (broadwell), Python 2.7.5
See https://gist.github.com/b4fe164d70e1100bc6486df1227d5c3f for a full test report.

**Comment by Flamefire** [comment]
Test report by @Flamefire
**FAILED**
Build succeeded for 1417 out of 1501 (1501 easyconfigs in total)
taurusa5 - Linux centos linux 7.7.1908, x86_64, Intel(R) Xeon(R) CPU E5-2603 v4 @ 1.70GHz (broadwell), Python 2.7.5
See https://gist.github.com/0fccceca7160349878565837d89aa307 for a full test report.

**Comment by Flamefire** [comment]
Test report by @Flamefire
**FAILED**
Build succeeded for 495 out of 544 (20 easyconfigs in total)
taurusa5 - Linux centos linux 7.7.1908, x86_64, Intel(R) Xeon(R) CPU E5-2603 v4 @ 1.70GHz (broadwell), Python 2.7.5
See https://gist.github.com/2368da2cc582a25ed3411d47a4dd6e5e for a full test report.

**Comment by Flamefire** [comment]
Test report by @Flamefire
Using easyblocks from PR(s) https://github.com/easybuilders/easybuild-easyblocks/pull/2494
**FAILED**
Build succeeded for 3565 out of 3699 (1501 easyconfigs in total)
taurusa4 - Linux centos linux 7.7.1908, x86_64, Intel(R) Xeon(R) CPU E5-2603 v4 @ 1.70GHz (broadwell), Python 2.7.5
See https://gist.github.com/788a1d6438b8a58f3c2570534c943d9c for a full test report.

**Comment by Flamefire** [comment]
Test report by @Flamefire
**FAILED**
Build succeeded for 0 out of 20 (20 easyconfigs in total)
taurusa5 - Linux centos linux 7.7.1908, x86_64, Intel(R) Xeon(R) CPU E5-2603 v4 @ 1.70GHz (broadwell), Python 2.7.5
See https://gist.github.com/5b6d0dea85f59700fbe75e62808a262f for a full test report.

**Comment by Flamefire** [comment]
Test report by @Flamefire
Using easyblocks from PR(s) https://github.com/easybuilders/easybuild-easyblocks/pull/2494
**FAILED**
Build succeeded for 1476 out of 1501 (1501 easyconfigs in total)
taurusa4 - Linux centos linux 7.7.1908, x86_64, Intel(R) Xeon(R) CPU E5-2603 v4 @ 1.70GHz (broadwell), Python 2.7.5
See https://gist.github.com/aeeabcefb1f0ebc1e82aa722377c8f20 for a full test report.

**Comment by Flamefire** [comment]
Test report by @Flamefire
Using easyblocks from PR(s) https://github.com/easybuilders/easybuild-easyblocks/pull/2494
**FAILED**
Build succeeded for 1478 out of 1501 (1501 easyconfigs in total)
taurusa4 - Linux centos linux 7.7.1908, x86_64, Intel(R) Xeon(R) CPU E5-2603 v4 @ 1.70GHz (broadwell), Python 2.7.5
See https://gist.github.com/da7e2e261a4413e13b48f4e6dc797247 for a full test report.

**Comment by Flamefire** [comment]
Test report by @Flamefire
Using easyblocks from PR(s) https://github.com/easybuilders/easybuild-easyblocks/pull/2494
**FAILED**
Build succeeded for 0 out of 23 (23 easyconfigs in total)
taurusa4 - Linux centos linux 7.7.1908, x86_64, Intel(R) Xeon(R) CPU E5-2603 v4 @ 1.70GHz (broadwell), Python 2.7.5
See https://gist.github.com/9a0a0f8eb79963226351b2dd22f37d66 for a full test report.

**Comment by boegel** [comment]
I gave this PR a thorough review, and tested several easyconfigs where I figured it would be useful (I didn't upload test reports though), and I think this is good to go now...
I did include one extra commit to fix a regression in the Spark easyconfigs (although it doesn't matter much since the sources themselves for the old Spark versions don't seem to be available anymore).

Thanks a lot for your efforts on this @Flamefire, I'm sure this was frustrating and time-consuming to work on...

That said, we really need to try and avoid huge PRs like this. Reviewing this PR and assessing whether it made sense to merge this took several hours, and it still a bit of a "risk" because it's impossible to test a PR like this front to back and make sure no regressions are introduced.

For future efforts like this, please try to split this up in multiple smaller PRs, for example one per letter subdirectory, so we can spread the effort of reviewing/testing across multiple maintainers...
Of course, the hacks for test suite you had to include complicate that significantly, I'm aware of that.

**Review by boegel — APPROVED** [review]

**Comment by boegel** [comment]
Going in, thanks @Flamefire!

**Comment by boegel** [comment]
Hacks in test suite are undone in #13295

**Pull request merged**
