### PR TITLE
{compiler}[GCCcore/10.2.0] AOCC v3.0.0

### PR DESCRIPTION
**Pull request by robert-mijakovic**
(created using `eb --new-pr`)

requires https://github.com/easybuilders/easybuild-easyblocks/pull/2362

### CODE REVIEW

**Review by boegel — APPROVED** [review]
lgtm

**Comment by boegel** [comment]
@boegelbot please test @ generoso
CORE_CNT=16

**Comment by boegel** [comment]
Test report by @boegel
**FAILED**
Build succeeded for 0 out of 1 (1 easyconfigs in total)
node3113.skitty.os - Linux centos linux 7.9.2009, x86_64, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz, Python 3.6.8
See https://gist.github.com/a116beb4f4c6b178bd893b6c227b9a6b for a full test report.

**Comment by migueldiascosta** [comment]
@boegelbot please test @ generoso CORE_CNT=16 EB_ARGS="--accept-eula=AOCC"

**Comment by migueldiascosta** [comment]
@boegelbot please test @ generoso CORE_CNT=16 EB_ARGS="--accept-eula=AOCC --include-easyblocks-from-pr 2362"

**Comment by verdurin** [comment]
Test report by @verdurin
Using easyblocks from PR(s) https://github.com/easybuilders/easybuild-easyblocks/pull/2362
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
easybuild-c7.novalocal - Linux centos linux 7.9.2009, x86_64, Intel Xeon Processor (Skylake, IBRS), Python 3.6.8
See https://gist.github.com/e3e000d325c2fa28a23dbd34a4521de4 for a full test report.

**Comment by verdurin** [comment]
Test report by @verdurin
Using easyblocks from PR(s) https://github.com/easybuilders/easybuild-easyblocks/pull/2362
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
nuc.lan - Linux Fedora 33, x86_64, Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz, Python 3.9.2
See https://gist.github.com/265932ec8b44989cbc7941889b6842d2 for a full test report.

**Comment by verdurin** [comment]
Going in, thanks @robert-mijakovic!

**Pull request merged**
