### PR TITLE
{bio}[GCCcore/13.3.0] nf-core v2.14.1, pydantic v2.9.1, pyfaidx v0.8.1.2

### PR DESCRIPTION
**Pull request by Flamefire**
(created using `eb --new-pr`)

Requires:
- [x] #21423 
- [x] #21424 
- [x] #21425

### CODE REVIEW

**Comment by Flamefire** [comment]
Test report by @Flamefire
**SUCCESS**
Build succeeded for 3 out of 3 (3 easyconfigs in total)
i7119 - Linux Rocky Linux 8.9 (Green Obsidian), x86_64, AMD EPYC 7702 64-Core Processor (zen2), Python 3.8.17
See https://gist.github.com/Flamefire/e2e0dca2c59d56cd944962765c01345f for a full test report.

**Comment by Flamefire** [comment]
Test report by @Flamefire
**SUCCESS**
Build succeeded for 4 out of 4 (4 easyconfigs in total)
i7119 - Linux Rocky Linux 8.9 (Green Obsidian), x86_64, AMD EPYC 7702 64-Core Processor (zen2), Python 3.8.17
See https://gist.github.com/Flamefire/a0a6721c3c73b766d5c45e415125dcf3 for a full test report.

**Comment by SebastianAchilles** [comment]
@boegelbot please test @ jsc-zen3

**Comment by smoors** [comment]
@boegelbot please test @ jsc-zen3

**Comment by smoors** [comment]
@boegelbot please test @ jsc-zen3

**Comment by smoors** [comment]
@boegelbot: please test @ generoso

**Comment by Flamefire** [comment]
> error in the sed cmd for pydantic:

t sneaked in while updating the checksums.

**Review by smoors — APPROVED** [review]
lgtm

**Comment by smoors** [comment]
Going in, thanks @Flamefire!

**Pull request merged**
