### PR TITLE
{bio}[GCC/8.2.0-2.31.1] STAR v2.7.1a

### PR DESCRIPTION
**Pull request by lexming**
(created using `eb --new-pr`)
Refresh of STAR-2.7.1a for foss/2019a

### CODE REVIEW

**Comment by vanzod** [comment]
@lexming Is it possible to build it with the `GCC` toolchain or does it need something in the `foss` toolchain?

**Comment by lexming** [comment]
Yes it can be build with `GCC`, it just needs `OpenMP`.

**Comment by vanzod** [comment]
Test report by @vanzod
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
cermis - Linux debian 9.9, Intel(R) Xeon(R) CPU           X5670  @ 2.93GHz, Python 2.7.13
See https://gist.github.com/a83474349f2949c47dc063871cd64c0d for a full test report.

**Comment by verdurin** [comment]
Test report by @verdurin
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
easybuild.novalocal - Linux centos linux 7.6.1810, Intel Xeon Processor (Skylake, IBRS), Python 2.7.5
See https://gist.github.com/f47d48b34aae053a0d569947af7bf885 for a full test report.

**Comment by verdurin** [comment]
Going in, thanks @lexming!

**Pull request merged**
