### PR TITLE
Fix Unicode

### PR DESCRIPTION
**Pull request by SIB-software**
(created using `eb --new-pr`)

### CODE REVIEW

**Review by Micket — APPROVED** [review]
lgtm

**Comment by Flamefire** [comment]
Not sure why this is needed. We have other modules using UTF-8 in their description so why change it here?

**Comment by Micket** [comment]
I just approved it since I just assumed this backtick was causing problems (but I haven't gotten around to testing it yet myself)

**Comment by smoretti** [comment]
Indeed, we have some users who changed the default terminal encoding and the description rendering is weird with the module spider command.

**Comment by Flamefire** [comment]
I don't see any issue with this PR either it is just: Do we want ASCII-only descriptions? Then we should enforce that via CI and consistently especially as this is "usually" undetected given that EB is mainly used on Linux-Systems where UTF-8 is the default and for me it is hard to see why you'd want to change that

**Comment by verdurin** [comment]
I'm going to merge this given it's clearly causing a problem in at least one site.
Agree that we should enforce at the CI level if we adopt this as a policy.

**Comment by SIB-software** [comment]
Test report by @sib-software
**FAILED**
Build succeeded for 0 out of 3 (3 easyconfigs in total)
vitbuild - Linux centos linux 7.9.2009, x86_64, Intel(R) Xeon(R) Gold 6230 CPU @ 2.10GHz, Python 3.6.8
See https://gist.github.com/SIB-software/b2ac347acbe9e388516dc6f880c732d8 for a full test report.

**Comment by SIB-software** [comment]
Test report by @sib-software
**FAILED**
Build succeeded for 0 out of 3 (3 easyconfigs in total)
vitbuild - Linux centos linux 7.9.2009, x86_64, Intel(R) Xeon(R) Gold 6230 CPU @ 2.10GHz, Python 3.6.8
See https://gist.github.com/SIB-software/ca6d08896bd4b3d5c99e2167fda84eb9 for a full test report.

**Comment by SIB-software** [comment]
Test report by @sib-software
**FAILED**
Build succeeded for 2 out of 3 (3 easyconfigs in total)
vitbuild - Linux centos linux 7.9.2009, x86_64, Intel(R) Xeon(R) Gold 6230 CPU @ 2.10GHz, Python 3.6.8
See https://gist.github.com/SIB-software/48260d001945a24ed8ed402df9a8b90d for a full test report.

**Comment by smoretti** [comment]
I have submitted a test-build.
The build of `SMRT-Link-5.1.0.26412-cli-tools-only.eb` failed because the source does not look to be available anymore.

**Comment by verdurin** [comment]
Going in, thanks @SIB-software!

**Pull request merged**
