### PR TITLE
add patch for gettext 0.19.8* to avoid picking up global git config that could break the installation

### PR DESCRIPTION
**Pull request by boegel**
cfr. problem reported by @sgowtham on Slack and via https://twitter.com/sgowtham/status/1175219728329166854

### CODE REVIEW

**Comment by boegel** [comment]
Thanks a lot for confirming the fix @sgowtham!

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 12 out of 12 (12 easyconfigs in this PR)
node2101.delcatty.os - Linux centos linux 7.6.1810, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.7.5
See https://gist.github.com/41574e465b7d3e864820865a33fcdac5 for a full test report.

**Comment by boegel** [comment]
@akesandgren This is a patch from upstream (which is included in `gettext` 0.20.x), so I trust the judgement of the `gettext` developers on this one.

Note that the only reason to unset `$HOME` & co is to avoid picking up a global `.gitignore` (from `$HOME/.gitignore` for example), which could break the installation (depending on the contents).

**Comment by Micket** [comment]
Test report by @Micket
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
vera-c1 - Linux centos linux 7.6.1810, Intel Xeon Processor (Skylake), Python 2.7.5
See https://gist.github.com/84e9719ee85b18f7754b7432a1c9969b for a full test report.

**Comment by Micket** [comment]
Going in, thanks @boegel!

**Pull request merged**
