### PR TITLE
{bio}[foss/2021b] PPanGGOLiN v1.1.136 + dependencies

### PR DESCRIPTION
**Pull request by deniskristak**
adding easyconfigs: ARAGORN-1.2.41-foss-2021b.eb, gmpy2-2.1.0rc1-GCC-11.2.0.eb, Infernal-1.1.4-foss-2021b.eb, MAFFT-7.490-GCC-11.2.0-with-extensions.eb, MMseqs2-13-45111-gompi-2021b.eb, networkx-2.6.3-foss-2021b.eb, plotly.py-5.4.0-GCCcore-11.2.0.eb, PPanGGOLiN-1.1.136-foss-2021b.eb, prodigal-2.6.3-GCCcore-11.2.0.eb, genoPlotR-0.8.11-foss-2020b.eb, rpy2-3.4.5-foss-2021b.eb and patches: PPanGGOLiN-1.1.136_new_compiler_compatibility.patch, rpy2-3.4.5_disable_gui_tests.patch

### CODE REVIEW

**Comment by deniskristak** [comment]
this needs to be merged first: https://github.com/easybuilders/easybuild-easyconfigs/pull/14450

**Comment by boegel** [comment]
@boegelbot please test @ generoso
CORE_CNT=16

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 10 out of 10 (10 easyconfigs in total)
node3510.doduo.os - Linux RHEL 8.2, x86_64, AMD EPYC 7552 48-Core Processor (zen2), Python 3.6.8
See https://gist.github.com/d549837b7323441ebd31554063f81664 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 10 out of 10 (10 easyconfigs in total)
node2631.swalot.os - Linux centos linux 7.9.2009, x86_64, Intel(R) Xeon(R) CPU E5-2660 v3 @ 2.60GHz (haswell), Python 3.6.8
See https://gist.github.com/ffe9359a462d9d3cd2492028f1590b2c for a full test report.

**Review by boegel — APPROVED** [review]
lgtm

**Comment by boegel** [comment]
Going in, thanks @deniskristak!

**Pull request merged**
