### PR TITLE
{numlib}[GCC/11.2.0] OpenBLAS v0.3.20

### PR DESCRIPTION
**Pull request by bartoldeman**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by bartoldeman** [comment]
Test report by @bartoldeman
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
build-node.computecanada.ca - Linux CentOS Linux 7.9.2009, x86_64, Intel Xeon Processor (Skylake, IBRS), Python 3.7.7
See https://gist.github.com/f721c3a48777eeb7a032aa850de8ecfd for a full test report.

**Comment by casparvl** [comment]
@boegelbot please test @ generoso

**Comment by SebastianAchilles** [comment]
Test report by @sebastianachilles
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
zen2-ubuntu-eb - Linux Ubuntu 22.04, x86_64, AMD EPYC 7452 32-Core Processor (zen2), Python 3.10.2
See https://gist.github.com/15a46622c96d651ffdd833d9ed00a718 for a full test report.

**Comment by casparvl** [comment]
Test report by @casparvl
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
tcn1 - Linux RHEL 8.4, x86_64, AMD EPYC 7H12 64-Core Processor, Python 3.6.8
See https://gist.github.com/9615fdcd618b33eb3ed10422cfef35d1 for a full test report.

**Review by casparvl — APPROVED** [review]
The `--review-pr` shows two patches were removed, and this indeed makes sense since both were upstreamed in OpenBLAS. Concluding: looks good to me!

**Comment by casparvl** [comment]
Going in, thanks @bartoldeman!

**Pull request merged**
