### PR TITLE
{geo}[foss/2020b] WPS v3.9.1

### LINKED ISSUE #15770: Problems building specific WPS version (WRF Preprocessing System )
I just installed WRF-3.9.1.1 sucessfully (using WRF-3.9.1.1-foss-2020b-dmpar.eb available with EasyBuild 4.5.5). But I need (as requirement from researchers-users) WPS 3.9.1 for pre-processing data. However, there is no easyconfig file for WPS-3.9.1.

There are significative differences between 3.9.1 versions and newer 4.x versions. Therefore, I chose an older version ( WPS-3.8.0-intel-2016a-dmpar.eb) and I changed toolchain (foss-2020b) and dependencies. When I executed new easyconfig file I got an error in testing step:

`
== configuring...
== ... (took 2 secs)`
`
== building...
== ... (took 43 secs)`
`
== testing...
== ... (took 4 mins 52 secs)`
`
== FAILED: Installation ended unsuccessfully (build directory: /dae/apps/easybuild/modulefiles/easybuild/software/WPS/3.8.0-foss-2020b-dmpar): build failed (first 300 chars): cmd "mpirun -n 1 /dae/apps/easybuild/modulefiles/easybuild/software/WPS/3.8.0-foss-2020b-dmpar/WPS/geogrid.exe" exited with exit code 132 and output:
mpirun was unable to launch the specified application as it could not acces (took 5 mins 45 secs)`
`
== Results of the build can be found in the log file(s) /tmp/eb-BUydHJ/easybuild-WPS-3.8.0-20220623.150942.ErgXf.log
ERROR: Build of /home/administrador/WPS-3.8.0-foss-2020b-dmpar.eb failed (err: 'build failed (first 300 chars): cmd "mpirun -n 1 /dae/apps/easybuild/modulefiles/easybuild/software/WPS/3.8.0-foss-2020b-dmpar/WPS/geogrid.exe" exited with exit code 132 and output:\n--------------------------------------------------------------------------\nmpirun was unable to launch the specified application as it could not acces')
`

Binaries were not created (like geogrid.exe), despite building step is completed..
What can I do to complete WRF installation??
Attached the easyconfig file generated...

Thanks, in advanced for support of this great Easybuild Team
[WPS-3.8.0-foss-2020b-dmpar.zip](https://github.com/easybuilders/easybuild/files/8970404/WPS-3.8.0-foss-2020b-dmpar.zip)

### PR DESCRIPTION
**Pull request by boegel**
(created using `eb --new-pr`)
requires:
* https://github.com/easybuilders/easybuild-easyblocks/pull/2754

fixes #15770

### CODE REVIEW

**Comment by boegel** [comment]
@boegelbot please test @ generoso

**Comment by kabm1979** [comment]
Test report by @kabm1979 
SUCCESS
== Build succeeded for 1 out of 1
Linux 4.18.0-193.el8.x86_64, Intel(R) Xeon(R) CPU E5-2680 v4 @ 2.40GHz (broadwell) , Python 3.6.8.
Thanks to @boegel and EasyBuild Support Team!!!

**Comment by smoors** [comment]
Test report by @smoors
**SUCCESS**
Build succeeded for 4 out of 4 (1 easyconfigs in total)
node312.hydra.os - Linux CentOS Linux 7.9.2009, x86_64, Intel(R) Xeon(R) Gold 6148 CPU @ 2.40GHz (skylake_avx512), Python 2.7.5
See https://gist.github.com/12e9dee9a9ffde805698dfbb9a6ff12e for a full test report.

**Review by smoors — APPROVED** [review]

**Comment by smoors** [comment]
Going in, thanks @boegel!

**Pull request merged**
