### PR TITLE
{cae,numlib,vis}[intel/2019b] OpenFOAM v1912, CGAL v4.14.1, ParaView v5.6.2 w/ Python 3.7.4

### PR DESCRIPTION
**Pull request by furstj**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by boegel** [comment]
Test report by @boegel
**FAILED**
Build succeeded for 1 out of 3 (3 easyconfigs in this PR)
node3108.skitty.os - Linux centos linux 7.7.1908, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz, Python 3.6.8
See https://gist.github.com/ae2705be86b850b224dcac25d0e562ae for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 3 out of 3 (3 easyconfigs in this PR)
node2424.golett.os - Linux centos linux 7.7.1908, Intel(R) Xeon(R) CPU E5-2680 v3 @ 2.50GHz, Python 2.7.5
See https://gist.github.com/4f961a5e1f6fff3d42d3a085f49831aa for a full test report.

**Comment by migueldiascosta** [comment]
Test report by @migueldiascosta
**SUCCESS**
Build succeeded for 3 out of 3 (3 easyconfigs in this PR)
generoso-1 - Linux centos linux 7.6.1810, Intel(R) Xeon(R) CPU E5-2660 v4 @ 2.00GHz, Python 3.6.8
See https://gist.github.com/cd59d2e5f37a2eadb973e9056a4b7078 for a full test report.

**Comment by boegel** [comment]
CGAL installation on Intel Skylake failed with `Error: unsupported instruction `vmovd'`, which is an issue we've seen before, see #8003

**Comment by lexming** [comment]
I confirm the error on Intel Skylake
```
[ 94%] Building CXX object src/CGAL_Qt5/CMakeFiles/CGAL_Qt5.dir/qrc_Triangulation_2.cpp.o
cd /theia/scratch/brussel/101/vsc10122/easybuild-local/build/CGAL/4.14.1/intel-2019b-Python-3.7.4/CGAL-4.14.1/src/CGAL_Qt5 && /apps/brussel/CO7/skylake/software/iccifort/2019.5.281/compilers_and_libraries_2019.5.281/linux/bin/intel64/icpc  -DCGAL_Qt5_EXPORTS -DCGAL_USE_GMPXX=1 -DQT_CORE_LIB -DQT_GUI_LIB -DQT_NO_DEBUG -DQT_OPENGL_LIB -DQT_SVG_LIB -DQT_WIDGETS_LIB -DQT_XML_LIB -I/theia/scratch/brussel/101/vsc10122/easybuild-local/build/CGAL/4.14.1/intel-2019b-Python-3.7.4/CGAL-4.14.1/include -I/theia/scratch/brussel/101/vsc10122/easybuild-local/build/CGAL/4.14.1/intel-2019b-Python-3.7.4/CGAL-4.14.1/src/CGAL_Qt5 -isystem /apps/brussel/CO7/skylake/software/GMP/6.1.2-GCCcore-8.3.0/include -isystem /apps/brussel/CO7/skylake/software/MPFR/4.0.2-GCCcore-8.3.0/include -isystem /user/brussel/101/vsc10122/.local/easybuild/software/Boost/1.71.0-iimpi-2019b/include -isystem /apps/brussel/CO7/skylake/software/Qt5/5.13.1-GCCcore-8.3.0/include -isystem /apps/brussel/CO7/skylake/software/Qt5/5.13.1-GCCcore-8.3.0/include/QtOpenGL -isystem /apps/brussel/CO7/skylake/software/Qt5/5.13.1-GCCcore-8.3.0/include/QtWidgets -isystem /apps/brussel/CO7/skylake/software/Qt5/5.13.1-GCCcore-8.3.0/include/QtGui -isystem /apps/brussel/CO7/skylake/software/Mesa/19.1.7-GCCcore-8.3.0/include -isystem /apps/brussel/CO7/skylake/software/Qt5/5.13.1-GCCcore-8.3.0/include/QtCore -isystem /apps/brussel/CO7/skylake/software/Qt5/5.13.1-GCCcore-8.3.0/./mkspecs/linux-g++-64 -isystem /apps/brussel/CO7/skylake/software/Qt5/5.13.1-GCCcore-8.3.0/include/QtSvg -isystem /apps/brussel/CO7/skylake/software/Qt5/5.13.1-GCCcore-8.3.0/include/QtXml  -O2 -xHost -fp-speculation=strict -fp-model strict -fPIC   -fp-model strict -fPIC -o CMakeFiles/CGAL_Qt5.dir/qrc_Triangulation_2.cpp.o -c /theia/scratch/brussel/101/vsc10122/easybuild-local/build/CGAL/4.14.1/intel-2019b-Python-3.7.4/CGAL-4.14.1/src/CGAL_Qt5/qrc_Triangulation_2.cpp
Command-line warning #1678: cannot enable speculation unless fenv_access and exception_semantics are disabled

Command-line warning #1678: cannot enable speculation unless fenv_access and exception_semantics are disabled

/tmp/eb-5QbIrO/icpcdJB7Yzas_.s: Assembler messages:
/tmp/eb-5QbIrO/icpcdJB7Yzas_.s:106379: Error: unsupported instruction `vmovd'
/tmp/eb-5QbIrO/icpcdJB7Yzas_.s:113180: Error: unsupported instruction `vmovd'
/tmp/eb-5QbIrO/icpcdJB7Yzas_.s:113196: Error: unsupported instruction `vmovd'
/tmp/eb-5QbIrO/icpcdJB7Yzas_.s:113198: Error: unsupported instruction `vmovd'
/tmp/eb-5QbIrO/icpcdJB7Yzas_.s:113199: Error: unsupported instruction `vmovd'
/tmp/eb-5QbIrO/icpcdJB7Yzas_.s:115753: Error: unsupported instruction `vmovd'
/tmp/eb-5QbIrO/icpcdJB7Yzas_.s:115761: Error: unsupported instruction `vmovd'
/tmp/eb-5QbIrO/icpcdJB7Yzas_.s:115811: Error: unsupported instruction `vmovd'
/tmp/eb-5QbIrO/icpcdJB7Yzas_.s:115812: Error: unsupported instruction `vmovd'
make[2]: *** [src/CGAL_Qt5/CMakeFiles/CGAL_Qt5.dir/all_files.cpp.o] Error 1```

**Comment by lexming** [comment]
@boegel based on issue #8003, should we rebuild `binutils` and `intel-2019b` to fix it?

**Comment by lexming** [comment]
Test report by @lexming
**FAILED**
Build succeeded for 1 out of 3 (3 easyconfigs in this PR)
login2.cerberus.os - Linux centos linux 7.7.1908, Intel(R) Xeon(R) Gold 6126 CPU @ 2.60GHz, Python 2.7.5
See https://gist.github.com/3b1744636bc6bc502f9aad6f9c2d4fbc for a full test report.

**Comment by furstj** [comment]
We can also try to patch the easyconfig with --optarch=GENERIC (or something like that). Although the more systematic way is (under my opinion) to improve binutils

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 3 out of 3 (3 easyconfigs in this PR)
node3101.skitty.os - Linux centos linux 7.7.1908, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz, Python 3.6.8
See https://gist.github.com/4c845e8807730bff02a1a0864760361e for a full test report.

**Comment by boegel** [comment]
> @boegel based on issue #8003, should we rebuild `binutils` and `intel-2019b` to fix it?

Indeed, that did the trick for me, see last test report.

**Comment by boegel** [comment]
@lexming I'll go ahead and merge this since it works as expected now for me on Skylake, but do look into confirming the fix with a new test report after rebuilding `binutils` with the changes from #9866...

**Comment by boegel** [comment]
Going in, thanks @furstj!

**Comment by lexming** [comment]
Test report by @lexming
**SUCCESS**
Build succeeded for 3 out of 3 (3 easyconfigs in this PR)
login2.cerberus.os - Linux centos linux 7.7.1908, Intel(R) Xeon(R) Gold 6126 CPU @ 2.60GHz, Python 2.7.5
See https://gist.github.com/353a7ad7e231a53b13b44774444bfced for a full test report.

**Pull request merged**
