### PR TITLE
{bio}[system/system] bcl-convert v4.2.7-2 w/ el7.x86_64

### PR DESCRIPTION
**Pull request by verdurin**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by smoors** [comment]
@boegelbot: please test @ generoso

**Comment by smoors** [comment]
>== 2024-05-13 12:30:40,388 build_log.py:171 ERROR EasyBuild crashed with an error (at easybuild/easybuild-framework/easybuild/base/exceptions.py:126 in __init__): Command 'rpmrebuild' is required but not available. Please add it as a dependency or install it with the OS package manager. (at easybuild/easybuild-easyblocks/easybuild/easyblocks/generic/rpm.py:60 in rebuild_rpm)

can you add `rpmrebuild` as a builddep?

**Comment by verdurin** [comment]
Test report by @verdurin
**SUCCESS**
Build succeeded for 2 out of 2 (1 easyconfigs in total)
easybuild-c7.novalocal - Linux CentOS Linux 7.9.2009, x86_64, Intel Xeon Processor (Skylake, IBRS), Python 3.6.8
See https://gist.github.com/verdurin/b5070073bb3711bff88674dfcd3cbfb9 for a full test report.

**Comment by verdurin** [comment]
@boegelbot please test @ generoso

**Comment by verdurin** [comment]
@smoors I added that, and now this weird error is showing:
`rpm: -bb: unknown option` ?

**Comment by verdurin** [comment]
I don't have any local systems where RPM isn't available in the OS...

**Comment by verdurin** [comment]
I've raised an issue against the `RPM` easyblock at https://github.com/easybuilders/easybuild-easyblocks/issues/3350

**Comment by smoors** [comment]
the issue is that `rpmbuild` is not available in generoso. in that case the `rpmrebuild.sh` script assumes that the rpm version is 3, which is not the case. the `-bb` option is no longer available in, `rpm` it is now in `rpmbuild`.

```bash
function RpmBuild
{
    Debug '(RpmBuild)'
    # rpmrebuild package dependency
    # for rpm 3.x : use rpm
    # for rpm 4.x : use rpmbuild
    local BUILDCMD
    if [ -x /usr/bin/rpmbuild ]
    then
        BUILDCMD=/usr/bin/rpmbuild
    else

        BUILDCMD=rpm
    fi
```

**Comment by verdurin** [comment]
@smoors thanks for diagnosing. I asked about it in the 'test-bots' channel.

Could you submit a test build from one of your local systems in the meantime?

**Comment by smoors** [comment]
Test report by @smoors
**SUCCESS**
Build succeeded for 2 out of 2 (1 easyconfigs in total)
node306.hydra.os - Linux Rocky Linux 8.9, x86_64, Intel(R) Xeon(R) Gold 6148 CPU @ 2.40GHz (skylake_avx512), Python 3.6.8
See https://gist.github.com/smoors/c90ff91b3c3d4a559f0aaa55838cb9d2 for a full test report.

**Comment by smoors** [comment]
@boegelbot please test @ jsc-zen3

**Comment by smoors** [comment]
@boegelbot please test @ jsc-zen3

**Comment by smoors** [comment]
@boegelbot: please test @ generoso

**Review by smoors — APPROVED** [review]
lgtm

**Comment by smoors** [comment]
Going in, thanks @verdurin!

**Pull request merged**
