### PR TITLE
disable optarch when using intel compilers and enable tests in all libxc-2.2.3 easyconfigs

### PR DESCRIPTION
**Pull request by migueldiascosta**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by migueldiascosta** [comment]
Test report by @migueldiascosta
**SUCCESS**
Build succeeded for 3 out of 3 (3 easyconfigs in this PR)
grc-cluster1 - Linux centos 6.9, Intel(R) Xeon(R) CPU E5-2640 0 @ 2.50GHz, Python 2.6.6
See https://gist.github.com/07abc7197279c6b679b11e26046f7445 for a full test report.

**Comment by migueldiascosta** [comment]
Test report by @migueldiascosta
**SUCCESS**
Build succeeded for 3 out of 3 (3 easyconfigs in this PR)
grc-e11 - Linux centos 6.9, Intel(R) Xeon(R) CPU E5-2680 v3 @ 2.50GHz, Python 2.6.6
See https://gist.github.com/37254e70d053948f5da171173d47ce68 for a full test report.

**Comment by verdurin** [comment]
Can't run tests easily at the moment, though...

**Comment by boegel** [comment]
@migueldiascosta optarch is not set to False in 1st easyconfig?

Also, maybe include a comment to mention why it's disabled? I'd mention failing tests on Haswell?

**Comment by migueldiascosta** [comment]
@boegel the tests only fail with optarch True with Intel compilers (-xHost) on Haswell's (and above, I assume, the problem is likely with the avx2 extensions)

I'll add the comment

**Comment by boegel** [comment]
@migueldiascosta AVX2 should also be used when using GCC with `optarch` enabled... But the problem may be specific to Intel compilers, sure.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 3 out of 3 (3 easyconfigs in this PR)
node2045.delcatty.os - Linux centos linux 7.4.1708, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.7.5
See https://gist.github.com/b2ad00b2f6e802884d3b8049eb2565e5 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**FAILED**
Build succeeded for 7 out of 8 (3 easyconfigs in this PR)
node2579.golett.os - Linux centos linux 7.4.1708, Intel(R) Xeon(R) CPU E5-2680 v3 @ 2.50GHz, Python 2.7.5
See https://gist.github.com/4c498b9d34c97e795b9791e9e4cd4dff for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 3 out of 3 (3 easyconfigs in this PR)
node2594.golett.os - Linux centos linux 7.4.1708, Intel(R) Xeon(R) CPU E5-2680 v3 @ 2.50GHz, Python 2.7.5
See https://gist.github.com/b5104c857bc1797f5289379e64a2be6a for a full test report.

**Comment by boegel** [comment]
Going in, thanks @migueldiascosta!

**Pull request merged**
