### PR TITLE
{vis}[GCCcore/11.3.0] py3Dmol v2.0.1.post1 w/ Python 3.10.4

### PR DESCRIPTION
**Pull request by lexming**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by lexming** [comment]
@boegelbot: please test @ generoso

**Comment by lexming** [comment]
@boegelbot please test @ jsc-zen2

**Comment by bedroge** [comment]
Test report by @bedroge
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
bob-Latitude-5300 - Linux Ubuntu 22.04, x86_64, Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz, Python 3.10.6
See https://gist.github.com/bedroge/a30f995260ff8509db77aaea6acb82c8 for a full test report.

**Comment by bedroge** [comment]
Test report by @bedroge
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
node1 - Linux Rocky Linux 8.7, x86_64, AMD EPYC 7763 64-Core Processor, Python 3.6.8
See https://gist.github.com/bedroge/da969c9f7242bf2ee799bc64f5963c8a for a full test report.

**Comment by bedroge** [comment]
Going in, thanks @lexming!

**Pull request merged**
