### PR TITLE
{math}[GCC/11.3.0] BRiAl v1.2.12, m4ri v20200125, m4rie v20200125

### PR DESCRIPTION
**Pull request by migueldiascosta**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by migueldiascosta** [comment]
@boegelbot please test @ generoso

**Comment by smoors** [comment]
> checking for boostlib >= 1.58.0 (105800)... yes
checking whether the Boost::Unit_Test_Framework library is available... yes
configure: error: Could not find a version of the Boost::Unit_Test_Framework library!

**Comment by migueldiascosta** [comment]
@boegelbot please test @ generoso

**Comment by migueldiascosta** [comment]
@boegelbot please test @ jsc-zen2

**Comment by jfgrimm** [comment]
Test report by @jfgrimm
**SUCCESS**
Build succeeded for 4 out of 4 (4 easyconfigs in total)
node041.viking2.yor.alces.network - Linux Rocky Linux 8.8, x86_64, AMD EPYC 7643 48-Core Processor, Python 3.6.8
See https://gist.github.com/jfgrimm/b532c22baf03e3135339692e271c511b for a full test report.

**Review by jfgrimm — APPROVED** [review]
lgtm

**Comment by jfgrimm** [comment]
Going in, thanks @migueldiascosta!

**Pull request merged**
