### PR TITLE
{bio}[system/system] KMCP v0.9.1

### PR DESCRIPTION
**Pull request by smoors**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by smoors** [comment]
@boegelbot: please test @ generoso

**Comment by smoors** [comment]
Test report by @smoors
Using easyblocks from PR(s) https://github.com/easybuilders/easybuild-easyblocks/pull/2878
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
node306.hydra.os - Linux CentOS Linux 7.9.2009, x86_64, Intel(R) Xeon(R) Gold 6148 CPU @ 2.40GHz, Python 3.6.8
See https://gist.github.com/cd4eb588f40a9fa23680f0d9fe9b52c2 for a full test report.

**Comment by lexming** [comment]
@boegelbot please test @ jsc-zen2

**Review by lexming — APPROVED** [review]
LGTM

**Comment by lexming** [comment]
Going in, thanks @smoors !

**Pull request merged**
