### PR TITLE
{vis}[GCCcore/11.2.0] LittleCMS v2.12, Ghostscript v9.54.0, ImageMagick v7.1.0-4

### PR DESCRIPTION
**Pull request by Micket**
(created using `eb --new-pr`)

requires ~~#13738~~ (GLib), ~~#13740~~ (cairo)

### CODE REVIEW

**Comment by SebastianAchilles** [comment]
Test report by @sebastianachilles
**SUCCESS**
Build succeeded for 3 out of 3 (3 easyconfigs in total)
centos8-eb - Linux centos linux 8.3.2011, x86_64, Intel(R) Core(TM) i7-8700 CPU @ 3.20GHz (skylake), Python 3.6.8
See https://gist.github.com/f4fc81fa752584ec6096581833baffcb for a full test report.

**Comment by migueldiascosta** [comment]
@boegelbot please test @ generoso

**Comment by migueldiascosta** [comment]
Test report by @migueldiascosta
**SUCCESS**
Build succeeded for 3 out of 3 (3 easyconfigs in total)
sms - Linux centos linux 7.6.1810, x86_64, AMD EPYC 7601 32-Core Processor (zen), Python 2.7.5
See https://gist.github.com/eec81aac18494fdb93bb4015633355db for a full test report.

**Review by migueldiascosta — APPROVED** [review]
lgtm

**Comment by migueldiascosta** [comment]
Going in, thanks @Micket!

**Pull request merged**
