### PR TITLE
{bio}[foss/2022b] nanoget 1.18.1

### PR DESCRIPTION
**Pull request by jkuhl-uni**
Needed for #20340

### CODE REVIEW

**Comment by verdurin** [comment]
@boegelbot please test @ generoso

**Comment by boegel** [comment]
@boegelbot please test @ generoso

**Comment by verdurin** [comment]
@boegelbot please test @ jsc-zen3

**Review by verdurin — APPROVED** [review]
Looks fine.

**Comment by verdurin** [comment]
Going in, thanks @jkuhl-uni!

**Pull request merged**
