### PR TITLE
{tools}[foss/2021a] snakemake v6.6.1 w/ Python 3.9.5

### PR DESCRIPTION
**Pull request by lexming**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by lexming** [comment]
Test report by @lexming
**FAILED**
Build succeeded for 0 out of 1 (1 easyconfigs in total)
node366.hydra.os - Linux centos linux 7.9.2009, x86_64, Intel(R) Xeon(R) Gold 6148 CPU @ 2.40GHz, Python 2.7.5
See https://gist.github.com/d6e505bb990a5104ff623215ccad7e3f for a full test report.

**Comment by lexming** [comment]
Test report by @lexming
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
node369.hydra.os - Linux centos linux 7.9.2009, x86_64, Intel(R) Xeon(R) Gold 6148 CPU @ 2.40GHz, Python 2.7.5
See https://gist.github.com/6172ade7c52f1dd66a11cb6b7c188c12 for a full test report.

**Comment by Micket** [comment]
Test report by @Micket
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
alvis-c1 - Linux centos linux 7.9.2009, x86_64, Intel Xeon Processor (Skylake), Python 3.6.8
See https://gist.github.com/0026604331502cf2e8cc1886fba44a0e for a full test report.

**Comment by Micket** [comment]
Just noticed there was a duplicate https://github.com/easybuilders/easybuild-easyconfigs/pull/13483

I think the patch needs to be applied still

**Comment by lexming** [comment]
I didn't see the other PR, my bad. Regarding the patch, I'm following what is already done in [snakemake-6.1.0-foss-2020b.eb](https://github.com/easybuilders/easybuild-easyconfigs/blob/develop/easybuild/easyconfigs/s/snakemake/snakemake-6.1.0-foss-2020b.eb). Seems quite site-specific as it is only needed in places where jobs' environment are reset (which is not the case by default in Slurm, for instance).

**Comment by Micket** [comment]
Yes but I don't think the patch causes any harms to others? Otherwise, @smoors is going to have to add it back afterwards

**Comment by lexming** [comment]
@Micket are you sure that the injected command `module load %(module_name)s` will always work? I would say that it can easily fail in HMNS for instance, as it will just load `snakemake` but the modules up the hierarchy might not be loaded.

**Comment by Micket** [comment]
Ugh, I'm just slow. I didn't realize it was commented in the old version as well. Sorry for the noise.

**Review by Micket — APPROVED** [review]
lgtm

**Comment by Micket** [comment]
Going in, thanks @lexming!

**Pull request merged**
