### PR TITLE
{bio}[GCC/10.2.0,GCC/11.2.0,GCC/11.3.0] ProtHint v2.6.0 w/ Python 3.10.4 + 3.8.6 + 3.9.6

### PR DESCRIPTION
**Pull request by boegel**
(created using `eb --new-pr`)
requires:
* #17466

### CODE REVIEW

**Comment by boegel** [comment]
@boegelbot please test @ generoso

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 3 out of 3 (3 easyconfigs in total)
node3118.skitty.os - Linux RHEL 8.6, x86_64, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz (skylake_avx512), Python 3.6.8
See https://gist.github.com/241c19a56738e2c8f11e926794567643 for a full test report.

**Comment by verdurin** [comment]
Trying to build `GeneMark-ET/4.65-GCCcore` as a dep for this, and that may need to be updated with a new version (or I downloaded the wrong thing...)

**Comment by boegel** [comment]
> Trying to build `GeneMark-ET/4.65-GCCcore` as a dep for this, and that may need to be updated with a new version (or I downloaded the wrong thing...)

Can you clarify what problem you're running into? Trouble with the download? Or was there an in-place update?

**Comment by verdurin** [comment]
Now that I've looked more closely, I think it's that I couldn't see a way of downloading the earlier versions from the site in the instructions, and I don't already have them.

**Comment by boegel** [comment]
@boegelbot please test @ jsc-zen2

**Comment by jfgrimm** [comment]
Test report by @jfgrimm
**FAILED**
Build succeeded for 7 out of 11 (3 easyconfigs in total)
himem05.pri.viking.alces.network - Linux CentOS Linux 7.9.2009, x86_64, Intel(R) Xeon(R) Gold 6230 CPU @ 2.10GHz (cascadelake), Python 3.6.8
See https://gist.github.com/367d1f51b207601a6802693c79745fb5 for a full test report.

**Comment by jfgrimm** [comment]
> @boegel any thoughts on how to proceed here, given the problems with downloading `GeneMark-ET`?

I'd suggest making a `GeneMark-ET/4.x` wrapper that installs the latest available version, and depending on that

**Comment by boegel** [comment]
not planning to pursue this (was a dep for #16156)

**Pull request closed without merging**
