### PR TITLE
{lang}[GCCcore/9.3.0] expect v5.45.4

### PR DESCRIPTION
**Pull request by jose-d**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by jose-d** [comment]
Test report by @jose-d
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
koiosvm1 - Linux centos linux 7.8.2003, x86_64, Intel Xeon Processor (Skylake, IBRS), Python 2.7.5
See https://gist.github.com/06dafb03b26136a9437029e47c03de35 for a full test report.

**Comment by jose-d** [comment]
> No output has been received in the last 10m0s, this potentially indicates a stalled build or something wrong with the build itself.

mhmm, some timeout, re-starting the test run..

**Comment by Micket** [comment]
Test report by @Micket
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
hebbe-c1 - Linux centos linux 7.8.2003, x86_64, Intel Core Processor (Haswell, no TSX), Python 2.7.5
See https://gist.github.com/85d2d092c8c1e79914751244d42d4c40 for a full test report.

**Comment by Micket** [comment]
Going in, thanks @jose-d!

**Pull request merged**
