### PR TITLE
{devel}[GCCcore/10.2.0] pkgconfig v1.5.1 w/ Python 3.8.6

### PR DESCRIPTION
**Pull request by Micket**
(created using `eb --new-pr`)
Note: poetry is now part of the Python bundle

### CODE REVIEW

**Comment by Micket** [comment]
Test report by @Micket
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
vera-c1 - Linux centos linux 7.8.2003, x86_64, Intel Xeon Processor (Skylake), Python 2.7.5
See https://gist.github.com/3d34627028ab2637938f5f1be5c09726 for a full test report.

**Comment by Micket** [comment]
Test report by @Micket
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
vera-c1 - Linux centos linux 7.8.2003, x86_64, Intel Xeon Processor (Skylake), Python 2.7.5
See https://gist.github.com/e081a65e320fc3d9f3706177ab59e87b for a full test report.

**Comment by Micket** [comment]
Since we are dropping the -Python-3 versionsuffix, i figured we should add back the "-python" version suffix so that this doesn't get confused with pkg-config.

**Review by migueldiascosta — APPROVED** [review]
lgtm

**Comment by migueldiascosta** [comment]
Going in, thanks @Micket!

**Pull request merged**
