### PR TITLE
{tools}[GCCcore/6.4.0] ExifTool v11.01

### PR DESCRIPTION
**Pull request by paulmelis**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by paulmelis** [comment]
The check in https://github.com/easybuilders/easybuild-easyconfigs/blob/afb34474f4d35d4676b4e5d1cbd94c8e0c978afe/test/easyconfigs/easyconfigs.py#L372 seems a bit strict:
```
    # make sure binutils is included as a build dep if toolchain is GCCcore
    if ec['toolchain']['name'] == 'GCCcore':
        # with 'Tarball' easyblock: only unpacking, no building; Eigen is also just a tarball
        requires_binutils = ec['easyblock'] not in ['Tarball'] and ec['name'] not in ['Eigen']
```

This config has a `PackedBinary` easyblock which also doesn't have any build step, same for `Binary`

**Comment by paulmelis** [comment]
The second fail, due to code style, is somewhat surprising, as I ran `eb --check-style` before submitting this PR and it did not complain (but that's on an EB 3.5.1 installation)

**Comment by ocaisa** [comment]
You can add the exception for `PackedBinary`  in this PR for the line you referenced and that should resolve that issue.

**Comment by boegel** [comment]
@paulmelis The exceptions are made strict on purpose, to avoid stuff passing through that shouldn't.

How about extending the check, as follows:

```python
requires_binutils = ec['easyblock'] not in ['Binary', 'PackedBinary', 'Tarball'] and ...

**Comment by akesandgren** [comment]
Superceeded by #11521

**Pull request closed without merging**
