### PR TITLE
Push FLTK-1.3.5 to GCCcore level

### PR DESCRIPTION
**Pull request by casparvl**
(created using `eb --new-pr`)

As discussed on EB slack, FLTK should really be at GCCcore level. It is visualization, and likely doesn't benefit from e.g. installation at iccifort level. Thus, there is no reason not to push it down to GCCcore

### CODE REVIEW

**Comment by casparvl** [comment]
@boegelbot pleast test @ generoso

**Comment by casparvl** [comment]
@boegelbot please test @ generoso

**Comment by Micket** [comment]
Test report by @Micket
**FAILED**
Build succeeded for 0 out of 1 (1 easyconfigs in this PR)
vera-c1 - Linux centos linux 7.8.2003, x86_64, Intel Xeon Processor (Skylake), Python 2.7.5
See https://gist.github.com/a75af316a6ba4ded847e2016721047b6 for a full test report.

**Review by Micket — CHANGES_REQUESTED** [review]
You'll have to add a build dep on binutils

**Comment by casparvl** [comment]
Yeah, ran into a build error on my system as well, and realized I forgot. Update is coming...

**Comment by smoors** [comment]
Test report by @smoors
**SUCCESS**
Build succeeded for 2 out of 2 (1 easyconfigs in total)
node375.hydra.os - Linux centos linux 7.7.1908, x86_64, Intel(R) Xeon(R) Gold 6148 CPU @ 2.40GHz (skylake_avx512), Python 2.7.5
See https://gist.github.com/9937a05f614158a732205db209b94aaf for a full test report.

**Review by smoors — APPROVED** [review]
lgtm

**Comment by zao** [comment]
Test report by @zao
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
freja - Linux Ubuntu 20.04, x86_64, Intel(R) Core(TM) i7-8700K CPU @ 3.70GHz (skylake), Python 3.8.5
See https://gist.github.com/3f902f1fc3460d0055af5c62e52ee9f3 for a full test report.

**Comment by smoors** [comment]
Going in, thanks @casparvl!

**Comment by smoors** [comment]
Going in, thanks @casparvl!

**Pull request merged**
