### PR TITLE
{tools}[GCCcore/10.2.0] bpytop v1.0.60 w/ Python 3.8.6

### PR DESCRIPTION
**Pull request by Mormacill**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by Mormacill** [comment]
Test report by @Mormacill
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
node03.mebus - Linux centos linux 7.9.2009, x86_64, Intel(R) Xeon(R) CPU           X5560  @ 2.80GHz, Python 3.6.8
See https://gist.github.com/a192e73984f9e17113cdefdfa25a5da2 for a full test report.

**Comment by verdurin** [comment]
Test report by @verdurin
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
nuc.lan - Linux Fedora 32, x86_64, Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz, Python 3.8.7
See https://gist.github.com/914df00efaf9203d36c5aec6f50ea6fb for a full test report.

**Comment by verdurin** [comment]
@boegelbot please test @ generoso

**Review by verdurin — APPROVED** [review]
Looks fine.

**Comment by verdurin** [comment]
Going in, thanks @Mormacill!

**Pull request merged**
