### PR TITLE
{numlib}[GCC/9.3.0] Z3 v4.8.9 w/ Python 3.8.2

### PR DESCRIPTION
**Pull request by lexming**
(created using `eb --new-pr`)

Depends on https://github.com/easybuilders/easybuild-easyblocks/pull/2318

### CODE REVIEW

**Comment by lexming** [comment]
Test report by @lexming
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in total)
node381.hydra.os - Linux centos linux 7.9.2009, x86_64, Intel(R) Xeon(R) Gold 6148 CPU @ 2.40GHz, Python 2.7.5
See https://gist.github.com/bbd61426124f46e840618ef57720a5a8 for a full test report.

**Comment by migueldiascosta** [comment]
@boegelbot please test @ generoso

**Comment by lexming** [comment]
@migueldiascosta perfect, I was expecting that failure :slightly_smiling_face:

**Comment by lexming** [comment]
Test report by @lexming
Using easyblocks from PR(s) https://github.com/easybuilders/easybuild-easyblocks/pull/2318
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in total)
node378.hydra.os - Linux centos linux 7.9.2009, x86_64, Intel(R) Xeon(R) Gold 6148 CPU @ 2.40GHz, Python 2.7.5
See https://gist.github.com/8f5a85680d80d12b6ff3c51e841f274b for a full test report.

**Comment by migueldiascosta** [comment]
Test report by @migueldiascosta
Using easyblocks from PR(s) https://github.com/easybuilders/easybuild-easyblocks/pull/2318
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in total)
sms - Linux centos linux 7.6.1810, x86_64, AMD EPYC 7601 32-Core Processor (zen), Python 2.7.5
See https://gist.github.com/e77977f57b60f29288e9ad97a5080cc6 for a full test report.

**Comment by migueldiascosta** [comment]
@boegelbot please test @ generoso EB_ARGS="--include-easyblocks-from-pr 2318"

**Comment by lexming** [comment]
Test report by @lexming
Using easyblocks from PR(s) https://github.com/easybuilders/easybuild-easyblocks/pull/2318
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
node369.hydra.os - Linux centos linux 7.9.2009, x86_64, Intel(R) Xeon(R) Gold 6148 CPU @ 2.40GHz, Python 2.7.5
See https://gist.github.com/e0e4a120823f6b5fd25a6abffb05957b for a full test report.

**Comment by lexming** [comment]
Abandoned. Easyconfig will stay at https://github.com/lexming/easybuild-easyconfigs/tree/vub-hpc/easybuild/easyconfigs/z/Z3

**Pull request closed without merging**
