### PR TITLE
{math}[foss/2018b] Theano v1.0.4 w/ Python 3.6.6

### PR DESCRIPTION
**Pull request by DirectorSloan**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by DirectorSloan** [comment]
Dear easybuilders contribution team. What can I do to support the merge of this easyconfig? best regards

**Comment by boegel** [comment]
@DirectorSloan `foss` toolchain versions older than `2019a` have been deprecated for a while (cfr. https://docs.easybuild.io/en/latest/Deprecated-easyconfigs.html#deprecated-toolchains), so I'm not sure it makes sense to put more effort into this.

But if the installation with the bot works, I'll go ahead and merge this, for what it's worth...

**Comment by boegel** [comment]
@boegelbot please test @ generoso

**Review by boegel — APPROVED** [review]
lgtm

**Comment by boegel** [comment]
Going in, thanks @DirectorSloan!

**Pull request merged**
