### PR TITLE
{math}[GCC/11.2.0,foss/2021b] sympy v1.9

### PR DESCRIPTION
**Pull request by SebastianAchilles**
(created using `eb --new-pr`)

edit (by @boegel): now requires:
* #15060

### CODE REVIEW

**Comment by migueldiascosta** [comment]
@boegelbot please test @ generoso

**Comment by boegel** [comment]
The warning is actually safe to ignore I think, there's actally failing tests, so that's why the `setup.py test` fails:

```
________________________________________________________________________________
____________ sympy/external/tests/test_pythonmpq.py:test_PythonMPQ _____________
Traceback (most recent call last):
  File "/tmp/vsc40023/easybuild_build/sympy/1.9/foss-2021b/sympy-1.9/sympy/external/tests/test_pythonmpq.py", line 45, in test_PythonMPQ
    assert check_Q(Q(Decimal('0.6'))) == (3, 5)
TypeError: mpq() requires numeric or string argument
________________________________________________________________________________
_____________ sympy/polys/tests/test_ring_series.py:test_nth_root ______________
Traceback (most recent call last):
  File "/tmp/vsc40023/easybuild_build/sympy/1.9/foss-2021b/sympy-1.9/sympy/polys/tests/test_ring_series.py", line 232, in test_nth_root
    assert rs_nth_root(8*x, 3, x, 3) == 2*x**QQ(1, 3)
  File "/tmp/vsc40023/easybuild_build/sympy/1.9/foss-2021b/sympy-1.9/sympy/polys/ring_series.py", line 988, in rs_nth_root
    const = R(c**Rational(1, n))  # exponentiation with mpq object
TypeError: unsupported operand type(s) for ** or pow()

 tests finished: 9762 passed, 318 skipped, 342 expected to fail,
8 expected to fail but passed, 2 exceptions, in 2347.60 seconds
```

The first one may be related to the version of `gmpy2` we're using; see https://github.com/sympy/sympy/issues/23061#issuecomment-1042462374.
It seems like this is cause by using `gmpy2` 2.1.x, see also https://github.com/aleaxit/gmpy/issues/327.

2nd one seems related to `gmpy2` as well, see https://github.com/sympy/sympy/issues/22662.

We're using a release candidate of `gmpy2`, which seems like a bad idea...

**Comment by boegel** [comment]
@boegelbot please test @ generoso

**Comment by SebastianAchilles** [comment]
Test report by @sebastianachilles
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
zen2-ubuntu-eb - Linux Ubuntu 22.04, x86_64, AMD EPYC 7452 32-Core Processor (zen2), Python 3.9.10
See https://gist.github.com/8b95b841bf4f7f64670dab1a7d6e8bc7 for a full test report.

**Comment by SebastianAchilles** [comment]
Test report by @sebastianachilles
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
skylake-alma8-eb - Linux AlmaLinux 8.5, x86_64, Intel(R) Core(TM) i7-8700 CPU @ 3.20GHz (skylake), Python 3.6.8
See https://gist.github.com/42f0b63d055c347719943d03cda0c0d2 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
node3510.doduo.os - Linux RHEL 8.4, x86_64, AMD EPYC 7552 48-Core Processor (zen2), Python 3.6.8
See https://gist.github.com/086fea9aad56d17aa6237013d772462d for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
node2626.swalot.os - Linux CentOS Linux 7.9.2009, x86_64, Intel(R) Xeon(R) CPU E5-2660 v3 @ 2.60GHz (haswell), Python 3.6.8
See https://gist.github.com/b1ecc62d041a4d489825144112d5667c for a full test report.

**Review by boegel — APPROVED** [review]
lgtm

**Comment by boegel** [comment]
Going in, thanks @SebastianAchilles!

**Pull request merged**
