### PR TITLE
WIP (alternate libxc): {chem}[foss/2020b,intel/2020b] GPAW v22.8.0 w/ Python 3.8.6

### PR DESCRIPTION
**Pull request by schiotz**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by schiotz** [comment]
This PR has been marked WIP as it cannot be merged due to using a non-standard version of libxc.  It is still useful for installation with ``eb --from-pr``.

**Comment by boegel** [comment]
@schiotz It looks like this is obsolete now thanks to PR #16267?

**Comment by schiotz** [comment]
> @schiotz It looks like this is obsolete now thanks to PR #16267?

Well, they are different.  This one is GPAW using the newest libxc version in the toolchain (5.1.5), the other one is using the default.  But since libxc is not one of the libraries that are allowed in different versions, this one cannot be merged.  It can, however, be installed with ``--from-pr``.  But maybe I should just close it.

**Comment by boegel** [comment]
@schiotz If we want to get this merged, we should add an exception to the easyconfigs tests to allow for this "deviation" w.r.t. `libxc` version being used as a dependency.
That should probably be done in https://github.com/easybuilders/easybuild-easyconfigs/blob/f5f80e884ee09d72e21b8c95aa4f4c32e21bbad0/test/easyconfigs/easyconfigs.py#L445

**Comment by schiotz** [comment]
> If we want to get this merged, we should add an exception to the easyconfigs tests to allow for this "deviation" w.r.t. `libxc` version being used as a dependency.

I don't think it is worth the trouble.  We need gpaw with a libxc 5.x locally, but now I finally got things to work with the 2022a toolchain, so we will probably just build everything with that toolchain and then I'll close this PR.

**Comment by schiotz** [comment]
I withdraw this PR, number #16267 should be used instead.

**Pull request closed without merging**
