### PR TITLE
{lib,phys}[GCCcore/11.2.0,foss/2021b] GLFW v3.3.4, MuJoCo v2.1.1, mujoco-py v2.1.2.14 w/ Python 3.9.6

### PR DESCRIPTION
**Pull request by lexming**
(created using `eb --new-pr`)

Depends on:
- [x] #14775

### CODE REVIEW

**Comment by verdurin** [comment]
@lexming missing port of `GLFW` to `foss/2021b`?

**Comment by lexming** [comment]
@verdurin you're totally right, thanks for the heads-up :+1:

**Comment by lexming** [comment]
@boegelbot: please test @ generoso

**Comment by lexming** [comment]
Test report by @lexming
**SUCCESS**
Build succeeded for 3 out of 3 (3 easyconfigs in total)
node315.hydra.os - Linux centos linux 7.9.2009, x86_64, Intel(R) Xeon(R) Gold 6148 CPU @ 2.40GHz, Python 2.7.5
See https://gist.github.com/03a10b1eefd48454797d8d91fd42e058 for a full test report.

**Comment by verdurin** [comment]
Test report by @verdurin
**SUCCESS**
Build succeeded for 7 out of 7 (3 easyconfigs in total)
centos7.lan - Linux UNKNOWN UNKNOWN, x86_64, Intel Core Processor (Skylake, IBRS), Python 3.6.8
See https://gist.github.com/2352b4861c3deec1321927fb7e0fc559 for a full test report.

**Review by verdurin — APPROVED** [review]
Looks fine.

**Comment by verdurin** [comment]
Going in, thanks @lexming!

**Pull request merged**
