### PR TITLE
{bio}[foss/2019b] clusTCR v1.0.2

### PR DESCRIPTION
**Pull request by fizwit**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by verdurin** [comment]
@boegelbot please test @ generoso

**Comment by verdurin** [comment]
Test report by @verdurin
**FAILED**
Build succeeded for 0 out of 1 (1 easyconfigs in total)
easybuild-c7.novalocal - Linux CentOS Linux 7.9.2009, x86_64, Intel Xeon Processor (Skylake, IBRS), Python 3.6.8
See https://gist.github.com/927f0b8ae621f29ceb8473be89434903 for a full test report.

**Comment by verdurin** [comment]
```
== 2022-09-09 11:28:39,768 build_log.py:169 ERROR EasyBuild crashed with an error (at easybuild/base/exceptions.py:124 in __init__): cmd " pip install --prefix=/eb/maint/software/clusTCR/1.0.2-foss-2019b-Python-3.7.4  --verbose  --no-deps  --ignore-installed  --no-index  --no-build-isolation  ." exited with exit code 2 and output:
Ignoring indexes: https://pypi.org/simple
Created temporary directory: /tmp/eb-od74g6jz/pip-ephem-wheel-cache-62nuohx1
Created temporary directory: /tmp/eb-od74g6jz/pip-req-tracker-g76kin68
Created requirements tracker '/tmp/eb-od74g6jz/pip-req-tracker-g76kin68'
Created temporary directory: /tmp/eb-od74g6jz/pip-install-ygojqa8p
Processing /dev/shm/clusTCR/1.0.2/foss-2019b-Python-3.7.4/flit_core/flit_core-3.7.1
  Created temporary directory: /tmp/eb-od74g6jz/pip-req-build-zv7gu9qw
  Added file:///dev/shm/clusTCR/1.0.2/foss-2019b-Python-3.7.4/flit_core/flit_core-3.7.1 to build tracker '/tmp/eb-od74g6jz/pip-req-tracker-g76kin68'
    Preparing wheel metadata: started
    Running command /eb/maint/software/Python/3.7.4-GCCcore-8.3.0/bin/python /eb/maint/software/Python/3.7.4-GCCcore-8.3.0/lib/python3.7/site-packages/pip-19.2.3-py3.7.egg/pip/_vendor/pep517/_in_process.py prepare_metadata_for_build_wheel /tmp/eb-od74g6jz/tmpr22mfdec
    Preparing wheel metadata: finished with status 'done'
Cleaning up...
  Removing source in /tmp/eb-od74g6jz/pip-req-build-zv7gu9qw
Removed file:///dev/shm/clusTCR/1.0.2/foss-2019b-Python-3.7.4/flit_core/flit_core-3.7.1 from build tracker '/tmp/eb-od74g6jz/pip-req-tracker-g76kin68'
Removed build tracker '/tmp/eb-od74g6jz/pip-req-tracker-g76kin68'
ERROR: Exception:
Traceback (most recent call last):
  File "/eb/maint/software/Python/3.7.4-GCCcore-8.3.0/lib/python3.7/site-packages/pip-19.2.3-py3.7.egg/pip/_internal/cli/base_command.py", line 188, in main
    status = self.run(options, args)
  File "/eb/maint/software/Python/3.7.4-GCCcore-8.3.0/lib/python3.7/site-packages/pip-19.2.3-py3.7.egg/pip/_internal/commands/install.py", line 345, in run
    resolver.resolve(requirement_set)
  File "/eb/maint/software/Python/3.7.4-GCCcore-8.3.0/lib/python3.7/site-packages/pip-19.2.3-py3.7.egg/pip/_internal/legacy_resolve.py", line 196, in resolve
    self._resolve_one(requirement_set, req)
  File "/eb/maint/software/Python/3.7.4-GCCcore-8.3.0/lib/python3.7/site-packages/pip-19.2.3-py3.7.egg/pip/_internal/legacy_resolve.py", line 359, in _resolve_one
    abstract_dist = self._get_abstract_dist_for(req_to_install)
  File "/eb/maint/software/Python/3.7.4-GCCcore-8.3.0/lib/python3.7/site-packages/pip-19.2.3-py3.7.egg/pip/_internal/legacy_resolve.py", line 307, in _get_abstract_dist_for
    self.require_hashes
  File "/eb/maint/software/Python/3.7.4-GCCcore-8.3.0/lib/python3.7/site-packages/pip-19.2.3-py3.7.egg/pip/_internal/operations/prepare.py", line 215, in prepare_linked_requirement
    finder, self.build_isolation,
  File "/eb/maint/software/Python/3.7.4-GCCcore-8.3.0/lib/python3.7/site-packages/pip-19.2.3-py3.7.egg/pip/_internal/distributions/source.py", line 79, in prepare_distribution_metadata
    self.req.prepare_metadata()
  File "/eb/maint/software/Python/3.7.4-GCCcore-8.3.0/lib/python3.7/site-packages/pip-19.2.3-py3.7.egg/pip/_internal/req/req_install.py", line 549, in prepare_metadata
    self.prepare_pep517_metadata()
  File "/eb/maint/software/Python/3.7.4-GCCcore-8.3.0/lib/python3.7/site-packages/pip-19.2.3-py3.7.egg/pip/_internal/req/req_install.py", line 594, in prepare_pep517_metadata
    metadata_dir
  File "/eb/maint/software/Python/3.7.4-GCCcore-8.3.0/lib/python3.7/site-packages/pip-19.2.3-py3.7.egg/pip/_vendor/pep517/wrappers.py", line 86, in prepare_metadata_for_build_wheel
    'config_settings': config_settings,
  File "/eb/maint/software/Python/3.7.4-GCCcore-8.3.0/lib/python3.7/site-packages/pip-19.2.3-py3.7.egg/pip/_vendor/pep517/wrappers.py", line 162, in _call_hook
    raise BackendUnavailable
pip._vendor.pep517.wrappers.BackendUnavailable
 (at easybuild/tools/run.py:618 in parse_cmd_output)
 ```

**Comment by boegel** [comment]
closing this since `foss/2019b` is no longer supported, see https://docs.easybuild.io/policies/toolchains

**Pull request closed without merging**
