### PR TITLE
include RInside extension in R 3.4.0 easyconfig

### PR DESCRIPTION
**Pull request by boegel**

### CODE REVIEW

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
node2612.swalot.os - Linux centos linux 7.4.1708, Intel(R) Xeon(R) CPU E5-2660 v3 @ 2.60GHz, Python 2.7.5
See https://gist.github.com/215a04de08fe3146fcb035ab07687552 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
node2080.delcatty.os - Linux centos linux 7.4.1708, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.7.5
See https://gist.github.com/c2966a76d09c09969e81baf9250a4525 for a full test report.

**Comment by verdurin** [comment]
Test report by @verdurin
**FAILED**
Build succeeded for 3 out of 6 (1 easyconfigs in this PR)
rescomp1 - Linux centos 6.8, Intel(R) Xeon(R) CPU E5-2650 v2 @ 2.60GHz, Python 2.7.14
See https://gist.github.com/31d9aea3ba6b538901ba7ace965d0c17 for a full test report.

**Comment by boegel** [comment]
@verdurin `JasPer` failed with `! LaTeX Error: Something's wrong--perhaps a missing \item.` :-/

**Comment by wpoely86** [comment]
Test report by @wpoely86
**FAILED**
Build succeeded for 1 out of 2 (1 easyconfigs in this PR)
nic169 - Linux centos linux 7.3.1611, Intel(R) Xeon(R) CPU E5-2650 v4 @ 2.20GHz, Python 2.7.5
See https://gist.github.com/5511ab1b4a2347cac3a635ae45e24784 for a full test report.

**Comment by boegel** [comment]
@wpoely86 I think you're hitting a known issue caused by a kernel bug, see #4833...

**Comment by wpoely86** [comment]
Test report by @wpoely86
**SUCCESS**
Build succeeded for 2 out of 2 (1 easyconfigs in this PR)
nic168 - Linux centos linux 7.3.1611, Intel(R) Xeon(R) CPU E5-2650 v4 @ 2.20GHz, Python 2.7.5
See https://gist.github.com/7a2065ae7c3aa19a652776654a86977b for a full test report.

**Pull request merged**
