### PR TITLE
{tools}[GCCcore/9.3.0] Sumo v1.7.0 w/ Python 3.8.2

### PR DESCRIPTION
**Pull request by ekieffer**
(created using `eb --new-pr`)

requires: [#11370] (Xerces-C++)

### CODE REVIEW

**Comment by ekieffer** [comment]
Test report by @ULHPC
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
iris-002 - Linux centos linux 7.8.2003, x86_64, Intel(R) Xeon(R) CPU E5-2680 v4 @ 2.40GHz, Python 3.6.8
See https://gist.github.com/de06b5cd8c125e60686f46c6121be160 for a full test report.

**Comment by zao** [comment]
Test report by @zao
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
freja - Linux Ubuntu 20.04, x86_64, Intel(R) Core(TM) i7-8700K CPU @ 3.70GHz, Python 3.8.2
See https://gist.github.com/a79a6be8e18816003a7fa2e7168859b4 for a full test report.

**Comment by verdurin** [comment]
Test report by @verdurin
**SUCCESS**
Build succeeded for 2 out of 2 (1 easyconfigs in total)
nuc.lan - Linux Fedora 32, x86_64, Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz, Python 3.8.6
See https://gist.github.com/3cd9cc3987179dd8c2a6768c3081b7c7 for a full test report.

**Comment by verdurin** [comment]
@boegelbot please test @ generoso

**Comment by bartoldeman** [comment]
There is a bit of a clash with https://github.com/easybuilders/easybuild-easyconfigs/pull/11435

**Comment by boegel** [comment]
This is superseded by #11435, which provides a more capable installation (more dependencies included), so I'll close this PR.

**Pull request closed without merging**
