### PR TITLE
{tools}[intel/2021b] YAXT v0.9.2

### PR DESCRIPTION
**Pull request by rungitta**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by rungitta** [comment]
Test report by @rungitta
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
login-2.fram.sigma2.no - Linux UNKNOWN UNKNOWN, x86_64, Intel(R) Xeon(R) CPU E5-2683 v4 @ 2.10GHz, Python 2.7.5
See https://gist.github.com/cbb902a35e23e207e5098bc61634c60f for a full test report.

**Comment by lexming** [comment]
@boegelbot: please test @ generoso

**Comment by lexming** [comment]
Test report by @lexming
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
node301.hydra.os - Linux centos linux 7.9.2009, x86_64, Intel(R) Xeon(R) Gold 6148 CPU @ 2.40GHz, Python 2.7.5
See https://gist.github.com/7e3fa6dff7870f3708cde1cbdc8e15af for a full test report.

**Review by lexming — APPROVED** [review]
LGTM

**Comment by lexming** [comment]
Going in, thanks @rungitta !

**Pull request merged**
