### PR TITLE
update easyconfig for Longshot 0.4.5 to use Cargo easyblock

### PR DESCRIPTION
**Pull request by Micket**
(created using `eb --new-pr`)
- [x] new cargo easyblock https://github.com/easybuilders/easybuild-easyblocks/pull/2902
- [x] https://github.com/easybuilders/easybuild-easyblocks/pull/2934

### CODE REVIEW

**Comment by Micket** [comment]
@boegelbot please test @ generoso
EB_ARGS="--include-easyblocks-from-pr 2902"

**Comment by Micket** [comment]
Test report by @Micket
Using easyblocks from PR(s) https://github.com/easybuilders/easybuild-easyblocks/pull/2902
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
vera-c1 - Linux Rocky Linux 8.6, x86_64, Intel Xeon Processor (Skylake), Python 3.6.8
See https://gist.github.com/Micket/1dd622d9911303ea5047fb41d85b120e for a full test report.

**Comment by Micket** [comment]
Test report by @Micket
Using easyblocks from PR(s) https://github.com/easybuilders/easybuild-easyblocks/pull/2902
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
vera-c1 - Linux Rocky Linux 8.6, x86_64, Intel Xeon Processor (Skylake), Python 3.6.8
See https://gist.github.com/Micket/8481593bceab3a126350755cf5f49b2e for a full test report.

**Comment by Micket** [comment]
Test report by @Micket
Using easyblocks from PR(s) https://github.com/easybuilders/easybuild-easyblocks/pull/2902
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
vera-c1 - Linux Rocky Linux 8.7, x86_64, Intel Xeon Processor (Skylake), Python 3.6.8
See https://gist.github.com/Micket/0ffb99399366eefd10771a675038c497 for a full test report.

**Comment by Micket** [comment]
@boegelbot please test @ generoso
EB_ARGS="--include-easyblocks-from-pr 2902"

**Comment by boegel** [comment]
@boegelbot please test @ jsc-zen2
EB_ARGS="--include-easyblocks-from-pr 2902"

**Comment by Micket** [comment]
ok so, this is that march thing on jsc-zen2 again
```
error: failed to run `rustc` to learn about target-specific information

Caused by:
  process didn't exit successfully: `rustc - --crate-name ___ --print=file-names -C 'target-cpu={'\''Intel'\'':' ''\''march=core-avx2'\''}' --crate-type bin --crate-type rlib --crate-type dylib --crate-type cdylib --crate-type staticlib --crate-type proc-macro --print=sysroot --print=cfg` (exit status: 1)
  --- stderr
  error: multiple input filenames provided (first two filenames are `-` and `'march=core-avx2'}`)
  ```
just like with https://github.com/easybuilders/easybuild-easyblocks/issues/2759

I'm not sure what i should do with that a dictionary here..

**Comment by Micket** [comment]
ok so, this is that march thing on jsc-zen2 again
```
error: failed to run `rustc` to learn about target-specific information

Caused by:
  process didn't exit successfully: `rustc - --crate-name ___ --print=file-names -C 'target-cpu={'\''Intel'\'':' ''\''march=core-avx2'\''}' --crate-type bin --crate-type rlib --crate-type dylib --crate-type cdylib --crate-type staticlib --crate-type proc-macro --print=sysroot --print=cfg` (exit status: 1)
  --- stderr
  error: multiple input filenames provided (first two filenames are `-` and `'march=core-avx2'}`)
  ```
just like with https://github.com/easybuilders/easybuild-easyblocks/issues/2759

I'm not sure what i should do with that a dictionary here..

**Comment by boegel** [comment]
@Micket Let's open an issue on that in the easyblocks repo, we may need to come up with a general approach there that works for OpenCV too...

**Comment by boegel** [comment]
@boegelbot please test @ jsc-zen2
EB_ARGS="--optarch='' "

**Comment by Micket** [comment]
```
'''' is not a recognized processor for this target (ignoring processor)
```
i guess it's assigning a empty string. I can't tell what RUSTFLAS is assigned from that partial log

I would have thought this could be enough to protect against None or empty strings?
```python
        optarch = build_option('optarch')
        if not optarch:
            optarch = 'native'
        env.setvar('RUSTFLAGS', '-C target-cpu=%s' % optarch

**Comment by boegel** [comment]
@Micket `' '` (single space) is not an empty string, and evaluates to `True`?

**Comment by Micket** [comment]
> @Micket `' '` (single space) is not an empty string, and evaluates to `True`?

yes but that's not what we have here? Not indicated by the error message either.
I'd like to get the full log from jsc-zen2 to see what the environment variables actually are set to

Running a local
```
eb --optarch='' Longshot-0.4.5-GCCcore-11.3.0.eb --rebuild
```
i have no issues.

**Comment by boegel** [comment]
@boegelbot please test @ jsc-zen2
EB_ARGS="--logtostdout --debug --optarch='' --include-easyblocks-from-pr 2902"

**Comment by boegel** [comment]
@Micket It works fine if I use `--optarch=''` manually on `jsc-zen2`, so it has something to do with how the bot picks up `EB_ARGS` from the comment...

**Comment by boegel** [comment]
Ah, here's the problem, the single quotes are escaped:

```
== 2023-05-24 06:17:13,131 generaloption.py:1696 DEBUG generate_cmd_line adding optarch value ''
```

So the correct way is to use `--optarch=`, let's try that

**Comment by boegel** [comment]
@boegelbot please test @ jsc-zen2
EB_ARGS="--optarch= --include-easyblocks-from-pr 2902"

**Comment by boegel** [comment]
@boegelbot please test @ generoso
EB_ARGS="--include-easyblocks-from-pr 2934"

**Review by boegel — APPROVED** [review]
lgtm

**Comment by boegel** [comment]
Going in, thanks @Micket!

**Pull request merged**
