### PR TITLE
{bio}[dummy/dummy] PLINK v2.00-alpha2-x86_64

### PR DESCRIPTION
**Pull request by verdurin**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by verdurin** [comment]
Should add that this is the `AVX2` build. They also make a build for older CPUs available.

**Comment by boegel** [comment]
@verdurin Does this deserve a `versionsuffix` like `-avx2`?

**Comment by boegel** [comment]
@verdurin Sure, unless you make come up with a good `versionsuffix` for it...

**Comment by vanzod** [comment]
The same easyconfigs have been merged in #8779

**Pull request closed without merging**
