### PR TITLE
{tools}[GCCcore/11.3.0] nano v7.0

### PR DESCRIPTION
**Pull request by anselmicz**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by anselmicz** [comment]
Test report by @anselmicz
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
login1.karolina.it4i.cz - Linux CentOS Linux 7 (Core), x86_64, AMD EPYC 7452 32-Core Processor, Python 3.10.4
See https://gist.github.com/9cb82732a8c640e85a1bad669cb42b3d for a full test report.

**Comment by anselmicz** [comment]
Test report by @anselmicz
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
login1.barbora.it4i.cz - Linux RHEL 8.4, x86_64, Intel(R) Xeon(R) Gold 6240 CPU @ 2.60GHz (cascadelake), Python 3.6.8
See https://gist.github.com/cea13923299bd14412b87b1b3c4ec6ec for a full test report.

**Comment by branfosj** [comment]
Test report by @branfosj
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
bear-pg0211u03a.bear.cluster - Linux Ubuntu 20.04.2 LTS (Focal Fossa), x86_64, Intel(R) Xeon(R) Gold 6248 CPU @ 2.50GHz (cascadelake), Python 3.8.5
See https://gist.github.com/7823a449a805ba7456299ea53d28b895 for a full test report.

**Review by branfosj — APPROVED** [review]

**Comment by branfosj** [comment]
@boegelbot please test @ jsc-zen2

**Comment by branfosj** [comment]
Test report by @branfosj
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
bear-pg0103u11a.bear.cluster - Linux RHEL 8.5, x86_64, Intel(R) Xeon(R) Gold 6330 CPU @ 2.00GHz (icelake), 1 x NVIDIA NVIDIA A100-PCIE-40GB, 470.57.02, Python 3.6.8
See https://gist.github.com/9da162859242d69bb190ba09c42792ec for a full test report.

**Comment by branfosj** [comment]
Going in, thanks @anselmicz!

**Pull request merged**
