### PR TITLE
{vis}[foss/2023a] OpenCV v4.8.1 w/ contrib

### PR DESCRIPTION
**Pull request by maxim-masterov**
(created using `eb --new-pr`)

Depends on
- PR #18962
- PR #18987

### CODE REVIEW

**Comment by Micket** [comment]
You claim this depends on #18962 but that PR doesn't contain LibTIFF/4.5.1-foss-2023a, OpenEXR/3.1.11-foss-2023a, ant/1.10.14-Java-11, GTK4/4.13.1-foss-2023a (no such PRs?)

**Comment by maxim-masterov** [comment]
@Micket My bad, it should depend on OpenEXR-3.1.7 and LibT?IFF-4.5.0. I've just changed it.

**Comment by maxim-masterov** [comment]
@Micket GTK4 is from PR #18987. I've added missing atn-1.10.14

**Comment by smoors** [comment]
@boegelbot please test @ jsc-zen2

**Comment by smoors** [comment]
@boegelbot: please test @ generoso

**Review by smoors — APPROVED** [review]
lgtm

**Comment by smoors** [comment]
Going in, thanks @maxim-masterov!

**Pull request merged**
