### PR TITLE
{bio}[foss/2018b] Arriba v1.1.0

### PR DESCRIPTION
**Pull request by SethosII**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by SethosII** [comment]
Test report by @SethosII
**SUCCESS**
Build succeeded for 2 out of 2 (1 easyconfigs in this PR)
ribnode015 - Linux ubuntu 18.04, Intel(R) Xeon(R) CPU           E5645  @ 2.40GHz, Python 2.7.15+
See https://gist.github.com/c363d2f86bda49b4b1745eb783514ff5 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
generoso - Linux centos linux 7.6.1810, Intel(R) Xeon(R) CPU E5-2660 v4 @ 2.00GHz, Python 3.6.8
See https://gist.github.com/56e34e920b2ac7e3afaed9ca0044d28f for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
node2409.golett.os - Linux centos linux 7.6.1810, Intel(R) Xeon(R) CPU E5-2680 v3 @ 2.50GHz, Python 2.7.5
See https://gist.github.com/6e8f59323e079f2b8887c6ac21361c6a for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
node3253.victini.os - Linux centos linux 7.6.1810, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz, Python 2.7.5
See https://gist.github.com/98a0cd1743d6e052d323b34c26e07bf3 for a full test report.

**Comment by boegel** [comment]
Going in, thanks @SethosII!

**Comment by JackPerdue** [comment]
Not sure how this made it through testing since it fails here due to not finding lzma.h.   I had to add XZ/5.2.4-GCCcore-7.3.0 to build here.

**Comment by boegel** [comment]
@JackPerdue It passed testing because `xz` is commenly installed in the OS too...

fixed in #9244

**Pull request merged**
