### PR TITLE
{math}[foss/2023a] gmsh v4.12.2

### PR DESCRIPTION
**Pull request by furstj**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by furstj** [comment]
Requires easyconfigs from 
- [  ] #19686 
- [  ] #19863
- [  ] #19686

**Comment by migueldiascosta** [comment]
@boegelbot please test @ generoso

**Comment by migueldiascosta** [comment]
@boegelbot please test @ jsc-zen3

**Review by migueldiascosta — APPROVED** [review]
lgtm

**Comment by migueldiascosta** [comment]
Going in, thanks @furstj!

**Pull request merged**
