### PR TITLE
{bio}[gompi/2023b] file v5.43, ncbi-vdb v3.1.1, SRA-Toolkit v3.1.1

### PR DESCRIPTION
**Pull request by fizwit**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by 7AXEL** [comment]
Check out this project: https://github.com/7AXEL/Web2APK

**Comment by bedroge** [comment]
@boegelbot please test @ generoso

**Comment by bedroge** [comment]
Test report by @bedroge
**SUCCESS**
Build succeeded for 3 out of 3 (3 easyconfigs in total)
interactive1 - Linux Rocky Linux 8.9, x86_64, AMD EPYC-Milan Processor (zen2), Python 3.6.8
See https://gist.github.com/bedroge/c76928798bca7d6ae310b589172d0a48 for a full test report.

**Comment by bedroge** [comment]
Test report by @bedroge
**SUCCESS**
Build succeeded for 3 out of 3 (3 easyconfigs in total)
bob-Latitude-5300 - Linux Ubuntu 22.04, x86_64, Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz, Python 3.10.12
See https://gist.github.com/bedroge/cff11d722cc345019b760cd08e18a885 for a full test report.

**Comment by bedroge** [comment]
@boegelbot please test @ jsc-zen3

**Review by bedroge — APPROVED** [review]
Looks good to me

**Comment by bedroge** [comment]
Going in, thanks @fizwit!

**Pull request merged**
