### PR TITLE
{bio}[foss/2018a,Python/2.7.14] HTSeq v0.10.0 + Pysam v0.14.1

### PR DESCRIPTION
**Pull request by jdemeul**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by verdurin** [comment]
@jdemeul dependency on `lzma` missing:
```
gcc -shared -L/home/centos/.local/easybuild/software/GCCcore/6.4.0/lib64 -L/home/centos/.local/easybuild/software/GCCcore/6.4.0/lib -L/home/centos/.local/easybuild/software/OpenBLAS/0.2.20-GCC-6.4.0-2.28/lib -L/home/centos/.local/easybuild/software/ScaLAPACK/2.0.2-gompi-2018a-OpenBLAS-0.2.20/lib -L/home/centos/.local/easybuild/software/FFTW/3.3.7-gompi-2018a/lib -L/home/centos/.local/easybuild/software/bzip2/1.0.6-GCCcore-6.4.0/lib -L/home/centos/.local/easybuild/software/zlib/1.2.11-GCCcore-6.4.0/lib -L/home/centos/.local/easybuild/software/libreadline/7.0-GCCcore-6.4.0/lib -L/home/centos/.local/easybuild/software/ncurses/6.0-GCCcore-6.4.0/lib -L/home/centos/.local/easybuild/software/SQLite/3.21.0-GCCcore-6.4.0/lib -L/home/centos/.local/easybuild/software/GMP/6.1.2-GCCcore-6.4.0/lib -L/home/centos/.local/easybuild/software/libffi/3.2.1-GCCcore-6.4.0/lib64 -L/home/centos/.local/easybuild/software/libffi/3.2.1-GCCcore-6.4.0/lib -L/home/centos/.local/easybuild/software/GCCcore/6.4.0/lib64 -L/home/centos/.local/easybuild/software/GCCcore/6.4.0/lib -L/home/centos/.local/easybuild/software/OpenBLAS/0.2.20-GCC-6.4.0-2.28/lib -L/home/centos/.local/easybuild/software/ScaLAPACK/2.0.2-gompi-2018a-OpenBLAS-0.2.20/lib -L/home/centos/.local/easybuild/software/FFTW/3.3.7-gompi-2018a/lib -L/home/centos/.local/easybuild/software/Python/2.7.14-foss-2018a/lib -L/home/centos/.local/easybuild/software/ncurses/6.0-GCCcore-6.4.0/lib -L/home/centos/.local/easybuild/software/cURL/7.58.0-GCCcore-6.4.0/lib -O2 -ftree-vectorize -march=native -fno-math-errno -I/home/centos/.local/easybuild/software/OpenBLAS/0.2.20-GCC-6.4.0-2.28/include -I/home/centos/.local/easybuild/software/ScaLAPACK/2.0.2-gompi-2018a-OpenBLAS-0.2.20/include -I/home/centos/.local/easybuild/software/FFTW/3.3.7-gompi-2018a/include -I/home/centos/.local/easybuild/software/Python/2.7.14-foss-2018a/include -I/home/centos/.local/easybuild/software/ncurses/6.0-GCCcore-6.4.0/include -I/home/centos/.local/easybuild/software/cURL/7.58.0-GCCcore-6.4.0/include build/temp.linux-x86_64-2.7/pysam/libchtslib.o build/temp.linux-x86_64-2.7/pysam/htslib_util.o build/temp.linux-x86_64-2.7/htslib/kfunc.o build/temp.linux-x86_64-2.7/htslib/knetfile.o build/temp.linux-x86_64-2.7/htslib/kstring.o build/temp.linux-x86_64-2.7/htslib/bcf_sr_sort.o build/temp.linux-x86_64-2.7/htslib/bgzf.o build/temp.linux-x86_64-2.7/htslib/errmod.o build/temp.linux-x86_64-2.7/htslib/faidx.o build/temp.linux-x86_64-2.7/htslib/hfile.o build/temp.linux-x86_64-2.7/htslib/hfile_net.o build/temp.linux-x86_64-2.7/htslib/hts.o build/temp.linux-x86_64-2.7/htslib/hts_os.o build/temp.linux-x86_64-2.7/htslib/md5.o build/temp.linux-x86_64-2.7/htslib/multipart.o build/temp.linux-x86_64-2.7/htslib/probaln.o build/temp.linux-x86_64-2.7/htslib/realn.o build/temp.linux-x86_64-2.7/htslib/regidx.o build/temp.linux-x86_64-2.7/htslib/sam.o build/temp.linux-x86_64-2.7/htslib/synced_bcf_reader.o build/temp.linux-x86_64-2.7/htslib/vcf_sweep.o build/temp.linux-x86_64-2.7/htslib/tbx.o build/temp.linux-x86_64-2.7/htslib/textutils.o build/temp.linux-x86_64-2.7/htslib/thread_pool.o build/temp.linux-x86_64-2.7/htslib/vcf.o build/temp.linux-x86_64-2.7/htslib/vcfutils.o build/temp.linux-x86_64-2.7/htslib/cram/cram_codecs.o build/temp.linux-x86_64-2.7/htslib/cram/cram_decode.o build/temp.linux-x86_64-2.7/htslib/cram/cram_encode.o build/temp.linux-x86_64-2.7/htslib/cram/cram_external.o build/temp.linux-x86_64-2.7/htslib/cram/cram_index.o build/temp.linux-x86_64-2.7/htslib/cram/cram_io.o build/temp.linux-x86_64-2.7/htslib/cram/cram_samtools.o build/temp.linux-x86_64-2.7/htslib/cram/cram_stats.o build/temp.linux-x86_64-2.7/htslib/cram/files.o build/temp.linux-x86_64-2.7/htslib/cram/mFILE.o build/temp.linux-x86_64-2.7/htslib/cram/open_trace_file.o build/temp.linux-x86_64-2.7/htslib/cram/pooled_alloc.o build/temp.linux-x86_64-2.7/htslib/cram/rANS_static.o build/temp.linux-x86_64-2.7/htslib/cram/sam_header.o build/temp.linux-x86_64-2.7/htslib/cram/string_alloc.o -L/home/centos/.local/easybuild/build/Pysam/0.14.1/foss-2018a-Python-2.7.14/pysam-0.14.1/pysam -L/home/centos/.local/easybuild/build/Pysam/0.14.1/foss-2018a-Python-2.7.14/pysam-0.14.1/pysam -L/home/centos/.local/easybuild/build/Pysam/0.14.1/foss-2018a-Python-2.7.14/pysam-0.14.1 -L/home/centos/.local/easybuild/build/Pysam/0.14.1/foss-2018a-Python-2.7.14/pysam-0.14.1/build/lib.linux-x86_64-2.7/pysam -Lbuild/lib.linux-x86_64-2.7/pysam -L/home/centos/.local/easybuild/software/Python/2.7.14-foss-2018a/lib -lz -lz -lm -lbz2 -llzma -lpython2.7 -o build/lib.linux-x86_64-2.7/pysam/libchtslib.so -Wl,-rpath,$ORIGIN
/home/centos/.local/easybuild/software/binutils/2.28-GCCcore-6.4.0/bin/ld.gold: error: cannot find -llzma
collect2: error: ld returned 1 exit status
error: command 'gcc' failed with exit status 1
 (at easybuild/software/EasyBuild/3.6.2/lib/python2.7/site-packages/easybuild_framework-3.6.2-py2.7.egg/easybuild/tools/run.py:501 in parse_cmd_output)
== 2018-08-17 07:47:27,036 easyblock.py:2776 WARNING build failed (first 300 chars): cmd " /home/centos/.local/easybuild/software/Python/2.7.14-foss-2018a/bin/python setup.py build " exited with exit code 1 and output:
checking for gcc... gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables...
```

The `XZ easyconfig` provides this.

**Comment by verdurin** [comment]
Test report by @verdurin
**FAILED**
Build succeeded for 2 out of 4 (2 easyconfigs in this PR)
easybuild.novalocal - Linux centos linux 7.5.1804, Intel Xeon E312xx (Sandy Bridge), Python 2.7.5
See https://gist.github.com/806e8427538705531c29efaf1577e65b for a full test report.

**Comment by jdemeul** [comment]
Good catch, thanks @verdurin, added the `lzma` dependency now.
Any idea how Pysam compiled correctly before? I guess if XZ is loaded indirectly?

**Comment by verdurin** [comment]
Going in, thanks @jdemeul!

**Pull request merged**
