### PR TITLE
{bio}[foss/2018b] OpenMS v2.4.0

### PR DESCRIPTION
**Pull request by tstrempel**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by tstrempel** [comment]
Why does it throw an error, simply because 2 different versions of a dependency from Core exists? Only one version is used at a time, so this shouldn't be an issue?

> Travis test report: 2/2 runs failed - see https://travis-ci.org/easybuilders/easybuild-easyconfigs/builds/677171013
> 
> Only showing partial log for 1st failed test suite run 21689.1;
> full log at https://travis-ci.org/easybuilders/easybuild-easyconfigs/jobs/677171014
> 
> ```
> ...
> FAIL: test_dep_versions_per_toolchain_generation (test.easyconfigs.easyconfigs.EasyConfigTest)
> ----------------------------------------------------------------------
> Traceback (most recent call last):
>   File "/home/travis/build/easybuilders/easybuild-easyconfigs/test/easyconfigs/easyconfigs.py", line 484, in test_dep_versions_per_toolchain_generation
>     self.assertFalse(multi_dep_vars, error_msg)
> AssertionError: No multi-variant deps found for '^.*-(?P<tc_gen>201[89][ab]).*\.eb$' easyconfigs:
> 
> found 2 variants of 'Eigen' dependency in easyconfigs using '2018b' toolchain generation
> * version: 3.3.4; versionsuffix:  as dep for set(['OpenBabel-2.4.1-intel-2018b-Python-3.6.6.eb', 'OpenBabel-2.4.1-intel-2018b-Python-2.7.15.eb'])
> * version: 3.3.7; versionsuffix:  as dep for set(['OpenMS-2.4.0-foss-2018b.eb'])
> 
> found 2 variants of 'SeqAn' dependency in easyconfigs using '2018b' toolchain generation
> * version: 1.4.2; versionsuffix: -library as dep for set(['OpenMS-2.4.0-foss-2018b.eb'])
> * version: 2.4.0; versionsuffix:  as dep for set(['taxator-tk-1.3.3-foss-2018b.eb', 'OptiType-1.3.2-foss-2018b-Python-3.6.6.eb', 'SCIPhI-0.1.3-intel-2018b.eb', 'OptiType-1.3.2-foss-2018b-Python-2.7.15.eb', 'metaWRAP-1.2-foss-2018b-Python-2.7.15.eb'])
> 
> 
> ----------------------------------------------------------------------
> Ran 9514 tests in 546.161s
> 
> FAILED (failures=1)
> ERROR: Not all tests were successful.
> ```
> 
>     * 21689.2 - errored => https://travis-ci.org/easybuilders/easybuild-easyconfigs/jobs/677171015
> 
> 
> *bleep, bloop, I'm just a bot (boegelbot v20180813.01)*Please talk to my owner @boegel if you notice you me acting stupid),or submit a pull request to https://github.com/boegel/boegelbot fix the problem.

**Comment by tstrempel** [comment]
I think the error message says, I should use Eigen v3.3.4 or am I missing something? Is there documentation, where I can look up which Core-EasyConfigs correspond to the different toolchains?
> Following this rule, the easyconfig for OpenMS should used Eigen v3.3.7 and SeqAn v2.4.0 as all 

I will rewrite the EasyConfig as a bundle as OpenMS needs this old version of SeqAn.

**Comment by lexming** [comment]
The dependencies are determined on-the-fly by checking current easyconfigs on the affected toolchain. So in this case you can verify which versions to use by checking existing easyconfigs in 2018b.

**Comment by tstrempel** [comment]
Hello @lexming,
it finally works! Are there any other style issues I got wrong?

**Comment by lexming** [comment]
Thanks for the update @tstrempel ! At first sight I would say that the sanity checks might need some work, but in general terms seems good. I'm running a test with it right now.

**Comment by lexming** [comment]
Depends on https://github.com/easybuilders/easybuild-easyconfigs/pull/10450

**Comment by lexming** [comment]
Test report by @lexming
**FAILED**
Build succeeded for 4 out of 5 (1 easyconfigs in this PR)
node051.manticore.os - Linux centos linux 7.7.1908, x86_64, Intel(R) Xeon(R) CPU E5-2650L v2 @ 1.70GHz, Python 2.7.5
See https://gist.github.com/fdead63f8839acb2b555ade3acaf27c6 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**FAILED**
Build succeeded for 1 out of 2 (1 easyconfigs in this PR)
generoso - Linux centos linux 7.6.1810, x86_64, Intel(R) Xeon(R) CPU E5-2660 v4 @ 2.00GHz, Python 3.6.8
See https://gist.github.com/c08eb09d94fc024c39938d8f15bcefe6 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**FAILED**
Build succeeded for 0 out of 2 (1 easyconfigs in this PR)
node3149.skitty.os - Linux centos linux 7.7.1908, x86_64, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz (skylake_avx512), Python 3.6.8
See https://gist.github.com/94912588e8615d67ccc1e73516435318 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**FAILED**
Build succeeded for 0 out of 2 (1 easyconfigs in this PR)
node2501.golett.os - Linux centos linux 7.7.1908, x86_64, Intel(R) Xeon(R) CPU E5-2680 v3 @ 2.50GHz (haswell), Python 2.7.5
See https://gist.github.com/8e37e8bc79eafc55d0e8b66f1cf75793 for a full test report.

**Comment by tstrempel** [comment]
coin-or projects were updated elsewhere
I'll open a new pr

**Pull request closed without merging**
