### PR TITLE
{lang}[foss/2020b] R v4.0.3

### PR DESCRIPTION
**Pull request by boegel**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by verdurin** [comment]
Test report by @verdurin
**FAILED**
Build succeeded for 11 out of 13 (1 easyconfigs in total)
nuc.lan - Linux Fedora 32, x86_64, Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz, Python 3.8.6
See https://gist.github.com/fd47c69227f8f6fb3fdf47f289adc457 for a full test report.

**Comment by verdurin** [comment]
The error here was in `nodejs/12.19.0-GCCcore-10.2.0`:
```
== 2020-11-11 16:20:11,708 easyblock.py:3063 INFO Running method configure_step part of step configure
== 2020-11-11 16:20:11,708 run.py:203 DEBUG run_cmd: running cmd  ./configure --prefix=/mnt/ds918plus/eb/nuc-fedora32/software/nodejs/12.19.0-GCCcore-10.2.0 --with-intl=none (in /mnt/ds918plus/eb/nuc-fedora32/build/nodejs/12.19.0/GCCcore-10.2.0/node-v12.19.0)
== 2020-11-11 16:20:11,708 run.py:222 INFO running cmd:  ./configure --prefix=/mnt/ds918plus/eb/nuc-fedora32/software/nodejs/12.19.0-GCCcore-10.2.0 --with-intl=none
== 2020-11-11 16:20:11,825 build_log.py:169 ERROR EasyBuild crashed with an error (at easybuild/base/exceptions.py:124 in __init__): cmd " ./configure --prefix=/mnt/ds918plus/eb/nuc-fedora32/software/nodejs/12.19.0-GCCcore-10.2.0 --with-intl=none" exited with exit code 1 and output:
which: no python2.7 in (/mnt/ds918plus/eb/nuc-fedora32/software/Python/3.8.6-GCCcore-10.2.0/bin:/mnt/ds918plus/eb/nuc-fedora32/software/XZ/5.2.5-GCCcore-10.2.0/bin:/mnt/ds918plus/eb/nuc-fedora32/software/SQLite/3.33.0-GCCcore-10.2.0/bin:/mnt/ds918plus/eb/nuc-fedora32/software/Tcl/8.6.10-GCCcore-10.2.0/bin:/mnt/ds918plus/eb/nuc-fedora32/software/ncurses/6.2-GCCcore-10.2.0/bin:/mnt/ds918plus/eb/nuc-fedora32/software/bzip2/1.0.8-GCCcore-10.2.0/bin:/mnt/ds918plus/eb/nuc-fedora32/software/binutils/2.35-GCCcore-10.2.0/bin:/mnt/ds918plus/eb/nuc-fedora32/software/GCCcore/10.2.0/bin:/mnt/ds918plus/eb/nuc-fedora32/software/EasyBuild/20201110-dev/bin:/home/adam/.local/bin:/home/adam/bin:/usr/lib64/ccache:/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin)
which: no python2 in (/mnt/ds918plus/eb/nuc-fedora32/software/Python/3.8.6-GCCcore-10.2.0/bin:/mnt/ds918plus/eb/nuc-fedora32/software/XZ/5.2.5-GCCcore-10.2.0/bin:/mnt/ds918plus/eb/nuc-fedora32/software/SQLite/3.33.0-GCCcore-10.2.0/bin:/mnt/ds918plus/eb/nuc-fedora32/software/Tcl/8.6.10-GCCcore-10.2.0/bin:/mnt/ds918plus/eb/nuc-fedora32/software/ncurses/6.2-GCCcore-10.2.0/bin:/mnt/ds918plus/eb/nuc-fedora32/software/bzip2/1.0.8-GCCcore-10.2.0/bin:/mnt/ds918plus/eb/nuc-fedora32/software/binutils/2.35-GCCcore-10.2.0/bin:/mnt/ds918plus/eb/nuc-fedora32/software/GCCcore/10.2.0/bin:/mnt/ds918plus/eb/nuc-fedora32/software/EasyBuild/20201110-dev/bin:/home/adam/.local/bin:/home/adam/bin:/usr/lib64/ccache:/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin)
Please use Python 2.7
 (at easybuild/tools/run.py:533 in parse_cmd_output)
```

**Comment by boegel** [comment]
@verdurin Nice catch! Fixed in #11679...

**Comment by verdurin** [comment]
Test report by @verdurin
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
nuc.lan - Linux Fedora 32, x86_64, Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz, Python 3.8.6
See https://gist.github.com/adb69e1f47bacbb6f602d6406bea48c8 for a full test report.

**Comment by boegel** [comment]
@boegelbot please test @ generoso

**Comment by terjekv** [comment]
Test report by @terjekv
**FAILED**
Build succeeded for 0 out of 1 (1 easyconfigs in total)
arm1 - Linux ubuntu 18.04, AArch64, UNKNOWN (aarch64), Python 3.6.9
See https://gist.github.com/0bcf5ba97fcdbb18a8c766f7611d9cb0 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**FAILED**
Build succeeded for 0 out of 1 (1 easyconfigs in total)
node3100.skitty.os - Linux centos linux 7.8.2003, x86_64, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz, Python 3.6.8
See https://gist.github.com/89d40db5b6a8b8df4acd8c2ce571eb5f for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**FAILED**
Build succeeded for 0 out of 1 (1 easyconfigs in total)
node3134.skitty.os - Linux centos linux 7.8.2003, x86_64, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz, Python 3.6.8
See https://gist.github.com/52436a7e90038de10abcdf50f4e729f7 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**FAILED**
Build succeeded for 0 out of 1 (1 easyconfigs in total)
node3134.skitty.os - Linux centos linux 7.8.2003, x86_64, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz, Python 3.6.8
See https://gist.github.com/e253207a33258080fe80e7b713d92e6b for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**FAILED**
Build succeeded for 0 out of 1 (1 easyconfigs in total)
node3134.skitty.os - Linux centos linux 7.8.2003, x86_64, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz, Python 3.6.8
See https://gist.github.com/5fa75a98536b9c00abe3507a146438b1 for a full test report.

**Comment by terjekv** [comment]
Test report by @terjekv
**SUCCESS**
Build succeeded for 94 out of 94 (1 easyconfigs in total)
arm1 - Linux ubuntu 18.04, AArch64, UNKNOWN (aarch64), Python 3.6.9
See https://gist.github.com/3dd9ccc87668c6546af9487059987570 for a full test report.

**Comment by verdurin** [comment]
This is the CentOS 8 failure from `generoso`:
```
* installing *source* package hdf5r ...
** package hdf5r successfully unpacked and MD5 sums checked
** using staged installation
checking for a sed that does not truncate output... /usr/bin/sed
checking for gawk... gawk
checking for grep that handles long lines and -e... /usr/bin/grep
checking for gcc... gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking how to run the C preprocessor... gcc -E
checking for egrep... /usr/bin/grep -E
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking Using provided HDF5 C wrapper... /users/boegelbot/CentOS8/haswell/software/HDF5/1.10.7-gompi-2020b/bin/h5pcc
checking for HDF5 libraries... yes (version 1.10.7)
checking hdf5.h usability... yes
checking hdf5.h presence... yes
checking for hdf5.h... yes
checking for H5Fcreate in -lhdf5... yes
checking for hdf5_hl.h... yes
checking for H5LTpath_valid in -lhdf5_hl... yes
checking for main in -lhdf5_hl... yes
checking for matching HDF5 Fortran wrapper... /users/boegelbot/CentOS8/haswell/software/HDF5/1.10.7-gompi-2020b/bin/h5pfc
Found hdf5 with version: 1.10.7
checking for ggrep... /usr/bin/grep
checking whether /usr/bin/grep accepts -o... yes
configure: creating ./config.status
config.status: creating src/Makevars
** libs
cp 1_10_3/*.c 1_10_3/*.h .

<snip>

installing to /users/boegelbot/CentOS8/haswell/software/R/4.0.3-foss-2020b/lib64/R/library/00LOCK-hdf5r/00new/hdf5r/libs
** R
** inst
** byte-compile and prepare package for lazy loading
** help
*** installing help indices
** building package indices
** installing vignettes
** testing if installed package can be loaded from temporary location
** checking absolute paths in shared objects and dynamic libraries
** testing if installed package can be loaded from final location
Error in base::serialize(base::as.list(base::getNamespace("hdf5r"), all.names = TRUE),  : 
  error writing to connection
Calls: <Anonymous> -> withCallingHandlers -> <Anonymous>
Execution halted
ERROR: loading failed
 (at easybuild/easybuild-framework/easybuild/tools/run.py:533 in parse_cmd_output)
```

**Comment by dithwick** [comment]
Pretty minor comment but in R-4.0.3-foss-2020b.eb:
`# ('OpenSSL', '1.1.1e'),`
should be 
`# ('OpenSSL', '1.1.1h'),`

**Comment by boegel** [comment]
@boegelbot please test @ generoso

**Comment by boegel** [comment]
@boegelbot please test @ generoso

**Comment by boegel** [comment]
Test report by @boegel
**FAILED**
Build succeeded for 0 out of 1 (1 easyconfigs in total)
node3136.skitty.os - Linux centos linux 7.9.2009, x86_64, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz, Python 3.6.8
See https://gist.github.com/9d8bebf4e6a3270e8dea79ebaa52c9a7 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**FAILED**
Build succeeded for 0 out of 1 (1 easyconfigs in total)
node3136.skitty.os - Linux centos linux 7.9.2009, x86_64, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz, Python 3.6.8
See https://gist.github.com/ceeef7250da2b785c661d77a3487c9c3 for a full test report.

**Comment by boegel** [comment]
@boegelbot please test @ generoso

**Comment by boegel** [comment]
There's something fishy going on on our CentOS 7.9 systems:

```
** testing if installed package can be loaded from temporary location                                                                                                                                       
Error: package or namespace load failed for openssl in dyn.load(file, DLLpath = DLLpath, ...):                                                                                                               
unable to load shared object '/software/R/4.0.3-foss-2020b/lib64/R/library/00LOCK-openssl/00new/openssl/libs/openssl.so':      
/software/R/4.0.3-foss-2020b/lib64/R/library/00LOCK-openssl/00new/openssl/libs/openssl.so:
undefined symbol: EVP_CIPHER_CTX_reset                                                                                                                                                                                                       
Error: loading failed                                                                                                                                                                                       
Execution halted                                                                                                                                                                                            
ERROR: loading failed
```

Opened upstream issue: https://github.com/jeroen/openssl/issues/84

**Comment by verdurin** [comment]
Test report by @verdurin
**SUCCESS**
Build succeeded for 0 out of 0 (1 easyconfigs in total)
nuc.lan - Linux Fedora 32, x86_64, Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz, Python 3.8.6
See https://gist.github.com/a2a7e8f1bed86b11c8f4bd7d65b478e8 for a full test report.

**Comment by verdurin** [comment]
Test report by @verdurin
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
nuc.lan - Linux Fedora 32, x86_64, Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz, Python 3.8.6
See https://gist.github.com/5a3072a912aa4fa8c5c1875a1a6e2136 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
node3501.doduo.os - Linux RHEL 8.2, x86_64, AMD EPYC 7552 48-Core Processor (zen2), Python 3.6.8
See https://gist.github.com/5f536f42bb1487f220854649697c2f35 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**FAILED**
Build succeeded for 0 out of 1 (1 easyconfigs in total)
node2728.swalot.os - Linux centos linux 7.9.2009, x86_64, Intel(R) Xeon(R) CPU E5-2660 v3 @ 2.60GHz (haswell), Python 3.6.8
See https://gist.github.com/7b506294a1208e2047b29f1d659b0729 for a full test report.

**Comment by boegel** [comment]
The problems with the `openssl` package on CentOS 7 should be fixed after not including `$EBROOTNODEJS/include/node` in `$CPATH` (cfr. #11845).

The problem boils down to `nodejs` shipping its own copy of the OpenSSL header files, which was messing up the compilation of the `openssl` R package (see discussion in https://github.com/jeroen/openssl/issues/84).

**Comment by boegel** [comment]
@boegelbot please test @ generoso

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
node3501.doduo.os - Linux RHEL 8.2, x86_64, AMD EPYC 7552 48-Core Processor (zen2), Python 3.6.8
See https://gist.github.com/4c3420981f365b0a957abeda68ce97bf for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**FAILED**
Build succeeded for 0 out of 1 (1 easyconfigs in total)
node2638.swalot.os - Linux centos linux 7.9.2009, x86_64, Intel(R) Xeon(R) CPU E5-2660 v3 @ 2.60GHz (haswell), Python 3.6.8
See https://gist.github.com/ea7c0a9e32a79a82c425da4714cbddf2 for a full test report.

**Comment by zao** [comment]
Test report by @zao
**FAILED**
Build succeeded for 0 out of 1 (1 easyconfigs in total)
eb-u1604 - Linux ubuntu 16.04, x86_64, Intel(R) Core(TM) i7-8700K CPU @ 3.70GHz, Python 2.7.12
See https://gist.github.com/04d624cfa9bc8fdfbed05c7d8a239905 for a full test report.

**Comment by boegel** [comment]
@boegelbot please test @ generoso

**Comment by boegel** [comment]
Test report by @boegel
**FAILED**
Build succeeded for 0 out of 1 (1 easyconfigs in total)
node3501.doduo.os - Linux RHEL 8.2, x86_64, AMD EPYC 7552 48-Core Processor (zen2), Python 3.6.8
See https://gist.github.com/4427797977019e8cfd153e9d561f8318 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**FAILED**
Build succeeded for 0 out of 1 (1 easyconfigs in total)
node3575.doduo.os - Linux RHEL 8.2, x86_64, AMD EPYC 7552 48-Core Processor (zen2), Python 3.6.8
See https://gist.github.com/4a3ca58812266cc41c65eff8a8367af3 for a full test report.

**Comment by zao** [comment]
Test report by @zao
**FAILED**
Build succeeded for 0 out of 1 (1 easyconfigs in total)
eb-u2004 - Linux Ubuntu 20.04, x86_64, Intel(R) Core(TM) i7-8700K CPU @ 3.70GHz, Python 3.8.5
See https://gist.github.com/a194bd1d715cb8d7c1c00c166dea5e83 for a full test report.

**Comment by zao** [comment]
Test report by @zao
**FAILED**
Build succeeded for 0 out of 1 (1 easyconfigs in total)
eb-u1604 - Linux ubuntu 16.04, x86_64, Intel(R) Core(TM) i7-8700K CPU @ 3.70GHz, Python 2.7.12
See https://gist.github.com/d3de1532b1c7c30f5046ff38f0af933a for a full test report.

**Comment by zao** [comment]
Test report by @zao
**FAILED**
Build succeeded for 0 out of 1 (1 easyconfigs in total)
eb-u1804 - Linux ubuntu 18.04, x86_64, Intel(R) Core(TM) i7-8700K CPU @ 3.70GHz, Python 2.7.17
See https://gist.github.com/d293e5916aeb125b285ae71f66d32e8e for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
node3575.doduo.os - Linux RHEL 8.2, x86_64, AMD EPYC 7552 48-Core Processor (zen2), Python 3.6.8
See https://gist.github.com/03c62faf5f88b2e41806c5be11e342d4 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
node2658.swalot.os - Linux centos linux 7.9.2009, x86_64, Intel(R) Xeon(R) CPU E5-2660 v3 @ 2.60GHz (haswell), Python 3.6.8
See https://gist.github.com/daefdf8398bdf2000a1431712a6c46cd for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
node3117.skitty.os - Linux centos linux 7.9.2009, x86_64, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz, Python 3.6.8
See https://gist.github.com/e04c4f8d5d37e33f9dcce03f3b1beca1 for a full test report.

**Comment by lexming** [comment]
Test report by @lexming
**SUCCESS**
Build succeeded for 31 out of 31 (1 easyconfigs in total)
node352.hydra.os - Linux centos linux 7.9.2009, x86_64, Intel(R) Xeon(R) Gold 6148 CPU @ 2.40GHz, Python 2.7.5
See https://gist.github.com/1e1c0e927c8d8109c762ec6b11637ba2 for a full test report.

**Comment by branfosj** [comment]
Test report by @branfosj
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
bear-pg0306u11a.bear.cluster - Linux RHEL 8.2, POWER, 8335-GTX (power9le), Python 3.6.8
See https://gist.github.com/f4197565e84c73b765f096cd7c8b838c for a full test report.

**Review by branfosj — APPROVED** [review]
lgtm

**Comment by zao** [comment]
@boegel I'd like to have the `-a` option added to `xvfb-run` as it makes the build pass on my 16.04 system (in conjunction with having the fonts package installed).

**Review by lexming — APPROVED** [review]
LGTM

**Comment by lexming** [comment]
@zao as discusses in Slack, we will merge this PR as it is and follow that issue in https://github.com/easybuilders/easybuild-easyconfigs/issues/11917

**Comment by lexming** [comment]
Going in, thanks @boegel !

**Pull request merged**
