### PR TITLE
{devel}[GCC/11.3.0] texlive v20230313

### PR DESCRIPTION
**Pull request by casparvl**
(created using `eb --new-pr`)

Note that I take suggestions from https://github.com/easybuilders/easybuild-easyconfigs/issues/17871 to create a texlive that is working _today_ and hopefully still _next year_, as this seems to be a challenge... :)

### CODE REVIEW

**Comment by casparvl** [comment]
Test report by @casparvl
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
tcn1.local.snellius.surf.nl - Linux RHEL 8.6, x86_64, AMD EPYC 7H12 64-Core Processor, Python 3.6.8
See https://gist.github.com/casparvl/b9ed271271b482ec19fcdded4d763efb for a full test report.

**Comment by casparvl** [comment]
@boegelbot please test @ jsc-zen2

**Review by branfosj — APPROVED** [review]

**Comment by branfosj** [comment]
Going in, thanks @casparvl!

**Comment by branfosj** [comment]
Test report by @branfosj
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
bear-pg0105u03a.bear.cluster - Linux RHEL 8.6, x86_64, Intel(R) Xeon(R) Platinum 8360Y CPU @ 2.40GHz (icelake), Python 3.6.8
See https://gist.github.com/branfosj/bf9520ce4a4fb78df8d37b8ecd185d2c for a full test report.

**Pull request merged**
