### PR TITLE
{compiler}[system/system] Java 17.0.2

### PR DESCRIPTION
**Pull request by robert-mijakovic**
Java updated to 17.0.2 due to RHSA-2022:0166 CVEs

### CODE REVIEW

**Comment by SebastianAchilles** [comment]
We might also want to update to Java 17.0.2 in the Java 17 wrapper:
https://github.com/easybuilders/easybuild-easyconfigs/blob/develop/easybuild/easyconfigs/j/Java/Java-17.eb#L12

**Comment by robert-mijakovic** [comment]
> We might also want to update to Java 17.0.2 in the Java 17 wrapper: https://github.com/easybuilders/easybuild-easyconfigs/blob/develop/easybuild/easyconfigs/j/Java/Java-17.eb#L12

That is what I did for our installation.

**Comment by SebastianAchilles** [comment]
@boegelbot please test @ generoso

**Comment by SebastianAchilles** [comment]
Test report by @sebastianachilles
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in total)
skylake-alma8-eb - Linux AlmaLinux 8.5, x86_64, Intel(R) Core(TM) i7-8700 CPU @ 3.20GHz (skylake), Python 3.6.8
See https://gist.github.com/458636eaef3cca2e08ba7ea4b648ba50 for a full test report.

**Comment by SebastianAchilles** [comment]
Test report by @sebastianachilles
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in total)
zen2-ubuntu-eb - Linux Ubuntu 22.04, x86_64, AMD EPYC 7452 32-Core Processor (zen2), Python 3.9.10
See https://gist.github.com/2fb78c2c4876cebaa15b18dedb3c58c4 for a full test report.

**Comment by SebastianAchilles** [comment]
@boegelbot please test @ jsc-zen2

**Review by SebastianAchilles — APPROVED** [review]
lgtm

**Comment by SebastianAchilles** [comment]
Going in, thanks @robert-mijakovic!

**Pull request merged**
