### PR TITLE
{numlib}[GCC/11.2.0] OpenBLAS v0.3.17

### PR DESCRIPTION
**Pull request by SebastianAchilles**
(created using `eb --new-pr`)

### CODE REVIEW

**Review by Micket — APPROVED** [review]
LGTM

**Comment by Micket** [comment]
@boegelbot please test @ generoso

**Comment by Micket** [comment]
Test report by @Micket
**FAILED**
Build succeeded for 0 out of 1 (1 easyconfigs in total)
alvis-c1 - Linux centos linux 7.9.2009, x86_64, Intel Xeon Processor (Skylake), Python 3.6.8
See https://gist.github.com/b482c399f56ccbbdf775ea688bb44254 for a full test report.

**Comment by Micket** [comment]
oh-oh, i got precision errors

**Comment by branfosj** [comment]
> oh-oh, i got precision errors

I also see these on my Intel systems. There tests pass on POWER9. We've already built OpenBLAS 0.3.17 (#13421).

**Comment by SebastianAchilles** [comment]
Test report by @sebastianachilles
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
rocky8-eb - Linux rocky linux 8.4, x86_64, Intel(R) Core(TM) i7-6900K CPU @ 3.20GHz (broadwell), Python 3.6.8
See https://gist.github.com/47afbcfddb256aa3ecc9d35e556b93a8 for a full test report.

**Comment by Micket** [comment]
Test report by @Micket
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
alvis-c1 - Linux centos linux 7.9.2009, x86_64, Intel Xeon Processor (Skylake), Python 3.6.8
See https://gist.github.com/7a241491e7e6dd9047d255dead558d84 for a full test report.

**Comment by SebastianAchilles** [comment]
Test report by @sebastianachilles
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
centos8-eb - Linux centos linux 8.3.2011, x86_64, Intel(R) Core(TM) i7-8700 CPU @ 3.20GHz (skylake), Python 3.6.8
See https://gist.github.com/c612f55c49267ab422bf973733be45bc for a full test report.

**Comment by boegel** [comment]
@boegelbot please test @ generoso

**Comment by boegel** [comment]
Test report by @boegel
**FAILED**
Build succeeded for 0 out of 1 (1 easyconfigs in total)
node3107.skitty.os - Linux centos linux 7.9.2009, x86_64, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz, Python 3.6.8
See https://gist.github.com/f0a3460ba0d5a5bfb8b6ec1b47718adf for a full test report.

**Comment by boegel** [comment]
Looks like disabling the use of `-free-vectorize` helps... Does that ring a bell for you @bartoldeman? ;)

@SebastianAchilles Maybe add a comment in the easyconfig to explain why we disable `vectorize`?
Should we open an issue upstream for this?

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
node3542.doduo.os - Linux RHEL 8.2, x86_64, AMD EPYC 7552 48-Core Processor (zen2), Python 3.6.8
See https://gist.github.com/c3c84cef76e38dd359784839422d3ae1 for a full test report.

**Comment by Micket** [comment]
For reference, with vectorization on, I see
```
 ******* FATAL ERROR - COMPUTED RESULT IS LESS THAN HALF ACCURATE *******
                       EXPECTED RESULT                    COMPUTED RESULT
       1  (   0.290119E-01,   0.379002E-01)  (  -0.408423E-01,  -0.319541E-01)
       2  (   0.762275E-02,   0.806386E-02)  (  -0.924949E-02,  -0.880837E-02)
 ******* ZGEMM  FAILED ON CALL NUMBER:
   6457: ZGEMM ('C','N',  2,  1,  1,( 1.0, 0.0), A,  2, B,  2,( 0.0, 0.0), C,  3).

 ZHEMM  PASSED THE COMPUTATIONAL TESTS (  1296 CALLS)

 ZSYMM  PASSED THE COMPUTATIONAL TESTS (  1296 CALLS)

 ******* FATAL ERROR - COMPUTED RESULT IS LESS THAN HALF ACCURATE *******
                       EXPECTED RESULT                    COMPUTED RESULT
       1  (   0.306693    ,   0.242757    )  (   0.306693    ,   0.242757    )
       2  (   0.360524    ,   0.364897    )  (   0.379238    ,   0.383611    )
 ******* ZTRMM  FAILED ON CALL NUMBER:
    950: ZTRMM ('L','U','C','U',  2,  1,( 1.0, 0.0), A,  3, B,  3)               .

 ******* FATAL ERROR - COMPUTED RESULT IS LESS THAN HALF ACCURATE *******
                       EXPECTED RESULT                    COMPUTED RESULT
       1  (   0.306693    ,   0.242757    )  (   0.306693    ,   0.242757    )
       2  (   0.466533    ,   0.306693    )  (   0.447819    ,   0.287979    )
 ******* ZTRSM  FAILED ON CALL NUMBER:
    950: ZTRSM ('L','U','C','U',  2,  1,( 1.0, 0.0), A,  3, B,  3)               .

 ******* FATAL ERROR - COMPUTED RESULT IS LESS THAN HALF ACCURATE *******
                       EXPECTED RESULT                    COMPUTED RESULT
       1  (   0.387794    ,   0.256287E-02)  (   0.246317    ,  -0.138914    )
       2  (   0.227563    ,   0.341716E-01)  (   0.193391    ,    0.00000    )
      THESE ARE THE RESULTS FOR COLUMN   2
 ******* ZHERK  FAILED ON CALL NUMBER:
    490: ZHERK ('U','C',  2,  1, 1.0, A,  2, 0.0, C,  3)                         .

 ZSYRK  PASSED THE COMPUTATIONAL TESTS (  1296 CALLS)

 ******* FATAL ERROR - COMPUTED RESULT IS LESS THAN HALF ACCURATE *******
                       EXPECTED RESULT                    COMPUTED RESULT
       1  (   0.131519    ,  -0.747125E-01)  (   0.182635E-02,  -0.204405    )
       2  (   0.953971E-01,   0.193181    )  (  -0.977843E-01,    0.00000    )
      THESE ARE THE RESULTS FOR COLUMN   2
 ******* ZHER2K FAILED ON CALL NUMBER:
    490: ZHER2K('U','C',  2,  1,( 1.0, 0.0), A,  2, B,  2, 0.0, C,  3)           .

```

```
 ******* FATAL ERROR - COMPUTED RESULT IS LESS THAN HALF ACCURATE *******
                       EXPECTED RESULT                    COMPUTED RESULT
       1  (   0.495928E-01,   0.197144    )  (  -0.176908    ,  -0.293573E-01)
       2  (  -0.154221    ,  -0.169237    )  (   0.179134    ,   0.164118    )
 ******* cblas_zgemm  FAILED ON CALL NUMBER:
   8644: cblas_zgemm ( CblasColMajor,CblasConjTrans,  CblasNoTrans,
            2,  1,  1, ( 1.0, 0.0) , A,  2, B,  2, ( 0.0, 0.0) , C,  3).
 ******* cblas_zgemm  FAILED ON CALL NUMBER:
   4537: cblas_zgemm ( CblasRowMajor,  CblasNoTrans,  CblasNoTrans,
            1,  1,  0, ( 0.0, 0.0) , A,  2, B,  1, ( 0.0, 0.0) , C,  2).
```

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
node3107.skitty.os - Linux centos linux 7.9.2009, x86_64, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz, Python 3.6.8
See https://gist.github.com/bdafec866fb628dece3bb6bce4cff176 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 11 out of 11 (1 easyconfigs in total)
node2609.swalot.os - Linux centos linux 7.9.2009, x86_64, Intel(R) Xeon(R) CPU E5-2660 v3 @ 2.60GHz (haswell), Python 3.6.8
See https://gist.github.com/4b9f177b0de43c320f5b5c010fc9705c for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
select-pika-c6gd-2xlarge-0001 - Linux centos linux 8.3.2011, AArch64, ARM UNKNOWN (graviton2), Python 3.6.8
See https://gist.github.com/cf62ba3e2375f3a24b951ea0dee6eb8c for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
easybuild2.novalocal - Linux centos linux 8.3.2011, POWER, IBM pSeries (emulated by qemu) (power9le), Python 3.6.8
See https://gist.github.com/b4578ce3c743e8a0f84dd7d97768347c for a full test report.

**Review by boegel — APPROVED** [review]
lgtm

**Comment by boegel** [comment]
Going in, thanks @SebastianAchilles!

**Pull request merged**
