### PR TITLE
add escape extesion to Bioconductor 3.16 bundle

### PR DESCRIPTION
**Pull request by boegel**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by boegel** [comment]
@boegelbot please test @ generoso
EB_ARGS="--skip"

**Comment by boegel** [comment]
@boegelbot please test @ jsc-zen2
EB_ARGS="--skip"

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
node3130.skitty.os - Linux RHEL 8.8, x86_64, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz (skylake_avx512), Python 3.6.8
See https://gist.github.com/boegel/7e304a39d83caf109ff4b577e03c499a for a full test report.

**Review by Micket — CHANGES_REQUESTED** [review]
this removes a couple of extensions, i suspect the easyconfig wasn't up to date when the new ones were added

**Comment by boegel** [comment]
@boegelbot please test @ generoso
EB_ARGS="--skip"

**Review by Micket — APPROVED** [review]
lgtm

**Pull request merged**
