### PR TITLE
{devel}[GCCcore/8.2.0] SCons v3.0.5 for Python 3.7.2 + 2.7.15

### PR DESCRIPTION
**Pull request by Micket**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by Micket** [comment]
Note: As far as I can tell, it multi_deps works fine here. The the scripts in bin don't hardcode a python version, and it looked alright.

**Comment by akesandgren** [comment]
Do the scripts use #!/usr/bin/env python ?
If not the easyblock PR #1698 has been merged and can be used to fix this.

**Comment by Micket** [comment]
Yes, `#! /usr/bin/env python` in all of them

**Comment by akesandgren** [comment]
Perfect :-)

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
node3110.skitty.os - Linux centos linux 7.6.1810, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz, Python 2.7.5
See https://gist.github.com/01c3522cd1499b2a7b728865f216c531 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
node2039.delcatty.os - Linux centos linux 7.6.1810, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.7.5
See https://gist.github.com/1235f21c0bfafa4dda069ac48a7a59da for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
node2409.golett.os - Linux centos linux 7.6.1810, Intel(R) Xeon(R) CPU E5-2680 v3 @ 2.50GHz, Python 2.7.5
See https://gist.github.com/043589e7bab3bdc7b9845351b8318647 for a full test report.

**Comment by boegel** [comment]
Going in, thanks @Micket!

**Pull request merged**
