### PR TITLE
{devel}[fosscuda/2019a] PyTorch v1.1.0 (WIP)

### PR DESCRIPTION
**Pull request by akesandgren**
(created using `eb --new-pr`)
This is still WIP.

### CODE REVIEW

**Comment by akesandgren** [comment]
Plan is to check if this should be a CMakePythonPackage to control the cmake invocation directly.

**Comment by branfosj** [comment]
For the version we did, there are some differences:
* In the list of sources we have `asmjit` and `foxi`, but we do not have `onnx-tensorrt`
* In `dependencies` we have added: `psutil` and `FFmpeg`, but we do not have `gflags` or `glog`
* We added `prebuildopts += 'USE_FFMPEG=ON USE_GLOO_IBVERBS=1 '`
* We set `preinstallopts = prebuildopts`.


I also looked at https://github.com/easybuilders/JSC/blob/master/Golden_Repo/2018b/p/PyTorch/PyTorch-1.0.0-gcccoremkl-7.3.0-2019.0.117-GPU-Python-3.6.6.eb and am considering changing
```
pytorchdir = 'pytorch-%(version)s'
```
to be
```
pytorchthirdpartydir = 'pytorch-%(version)s/third_party'
```
which makes the sources section a bit cleaner and adding:
```
mkdir_and_extract_cmd_pattern = "DIR=%s/%s; mkdir -p $DIR; tar -C $DIR --strip-components=1 -xzf %%s"
```
to make the `mklml_lnx_2019.0.3.20190220.tgz` section cleaner


Though I really do like the idea of more directly controlling CMake!

**Comment by akesandgren** [comment]
Yeah, I'm still changing things here, just getting side tracked by security upgrades and high prio user requests...

**Comment by smoors** [comment]
@akesandgren any updates on this?

**Comment by akesandgren** [comment]
Yeah that makes sence. However, I just got back from a long vacation and have a ton of work to catch up on. Probably won't get to doing PR's until next week at the earliest...

**Comment by branfosj** [comment]
I did some initial work on PyTorch 1.2.0 - https://github.com/easybuilders/easybuild-easyconfigs/pull/8753

**Comment by boegel** [comment]
@akesandgren Just merged #8753, I guess we can consider this one obsolete now?

**Comment by boegel** [comment]
Sorry, I meant #8891

**Comment by akesandgren** [comment]
Yep, closing

**Pull request closed without merging**
