### PR TITLE
{bio}[foss/2020a] QIIME2 v2020.8.0 w/ Python 3.8.2 (WIP)

### PR DESCRIPTION
**Pull request by boegel**
(created using `eb --new-pr`)
requires:
* [x] ~~#11654~~ (Perl extensions)
* [x] ~~#11658~~ (alsa-lib)
* [x] ~~#11659~~ (bwidget)
* [x] ~~#11660~~ (scikit-bio)
* [x] ~~#11739~~ (HMMER)
* [x] ~~#11740~~ (IQ-TREE)

still WIP because several dependencies are still missing...

### CODE REVIEW

**Comment by boegel** [comment]
Closing this, not planning to pursue it since this QIIME2 version is already outdated, it can serve as inspiration for someone brave enough to work on a fully working non-system easyconfig for a recent version of QIIME2...

**Comment by migueldiascosta** [comment]
@boegel not sure if brave or stupid, but had a go at it, see #16901

**Comment by migueldiascosta** [comment]
stupid, it turns out - even though https://github.com/easybuilders/easybuild-easyconfigs/pull/16901 builds and passes basic sanity checks, it then fails for instance when reading a `qza` file, and the problem seems to be the Python version, QIIME2 doesn't seem to work with Python >= 3.9 yet, at least not as of QIIME2 version 2022.8 (and indeed, the conda environment files all use py38...)

I can get a similar non-system easyconfig to work with foss/2020b (Python 3.8.6), so I'll run some more tests and open an PR for that toolchain if all is well

**Comment by migueldiascosta** [comment]
@boegel thanks to @smoors being not only brave but also smart, this PR of yours did eventually inspire a working non-system and recent toolchain QIIME2 easyconfig to get merged: https://github.com/easybuilders/easybuild-easyconfigs/pull/18407 :)

**Comment by smoors** [comment]
just standing on the shoulders of giants :smile:

**Pull request closed without merging**
