### PR TITLE
fix building Bison 2.5 on systems with recent glibc

### PR DESCRIPTION
**Pull request by boegel**

### CODE REVIEW

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 6 out of 6 (6 easyconfigs in this PR)
node2109.delcatty.os - Linux centos linux 7.3.1611, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.7.5
See https://gist.github.com/8cdf06c28cf5a6cd81e4c0aa499e3647 for a full test report.

**Comment by verdurin** [comment]
I know my test build is going to fail, because I don't have those old Intel-based toolchains. Looks fine anyway.

**Comment by verdurin** [comment]
Going in, thanks @boegel!

**Comment by verdurin** [comment]
Test report by @verdurin
**FAILED**
Build succeeded for 4 out of 45 (6 easyconfigs in this PR)
ca043.camp.thecrick.org - Linux centos linux 7.3.1611, Intel(R) Xeon(R) CPU E5-2640 v3 @ 2.60GHz, Python 2.7.5
See https://gist.github.com/3fdfb8aca3065f59c085bf99024201a5 for a full test report.

**Pull request merged**
