### PR TITLE
{vis}[foss/2019b] Graphviz v2.42.2 w/ Python 3.7.4

### PR DESCRIPTION
**Pull request by lexming**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by lexming** [comment]
Depends on #9787

**Comment by lexming** [comment]
Depends on #9787

**Comment by lexming** [comment]
Test report by @lexming
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in this PR)
login2.cerberus.os - Linux centos linux 7.7.1908, Intel(R) Xeon(R) Gold 6126 CPU @ 2.60GHz, Python 2.7.5
See https://gist.github.com/22ff88b9417a3aa850d537a3992dfda9 for a full test report.

**Comment by migueldiascosta** [comment]
closing and reopening to trigger tests

**Comment by migueldiascosta** [comment]
closing and reopening to trigger tests

**Comment by lexming** [comment]
1. Java dependency upgraded to `Java/11`. The java package of `Graphviz` builds fine and it imports without issues.
2. @migueldiascosta there is a failed test regarding a dependency on `ICU`, because it hits `ICU-65.1` while the common dependency for this toolchain is `ICU-64.2`. However, these easyconfigs do not directly depend on `ICU`. It hits `ICU` from `Pango/1.44.7-GCCcore-8.3.0` > `HarfBuzz-2.6.4-GCCcore-8.3.0` > `ICU-65.1-GCCcore-8.3.0`. What to do here? Should we fix the dependency in `HarfBuzz-2.6.4-GCCcore-8.3.0`?

**Comment by lexming** [comment]
Removing the `lowopt` option as our tests are not hitting the segfault errors from `Graphviz-2.40.1` in this release.

**Comment by migueldiascosta** [comment]
wondering how the `ICU` mess happened and why... @boegel?

**Comment by lexming** [comment]
@migueldiascosta opened issue #9841 regarding the mess with `ICU`

**Comment by lexming** [comment]
Re-triggering travis.

**Comment by lexming** [comment]
Test report by @lexming
**SUCCESS**
Build succeeded for 3 out of 3 (2 easyconfigs in this PR)
login2.cerberus.os - Linux centos linux 7.7.1908, Intel(R) Xeon(R) Gold 6126 CPU @ 2.60GHz, Python 2.7.5
See https://gist.github.com/db33ebd45e185c1d95d72d45949fb19e for a full test report.

**Comment by migueldiascosta** [comment]
Going in, thanks @lexming!

**Pull request merged**
