### PR TITLE
{devel}[GCCcore/13.3.0] libelf v0.8.13

### PR DESCRIPTION
**Pull request by maxim-masterov**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by smoors** [comment]
it looks like more recent versions can be downloaded from here: https://sourceware.org/git/?p=elfutils.git;a=summary
would you be ok updating to the latest?

**Comment by maxim-masterov** [comment]
I think it's only elfutils, right? Not libelf.

**Comment by smoors** [comment]
elfutils also contains libelf.
i see now that there exist already an elfutils easyconfig for GCCcore/13.3.0
maybe just use that one instead? or do you need the older version for a specific reason?

**Comment by maxim-masterov** [comment]
Good point. Indeed, we can use the one from the `elfutils` distribution. I'll close this PR then.

**Pull request closed without merging**
