### PR TITLE
{bio}[foss/2016a] Adding some working configs for 3.3.2 (WIP)

### PR DESCRIPTION
**Pull request by rjeschmi**
Here is an updated bundle for bioconductor and R 3.3.2

### CODE REVIEW

**Comment by rjeschmi** [comment]
oh I think I left the with-x option. I should split that out. I don't think the no-x option works properly...

**Comment by verdurin** [comment]
@rjeschmi I adapted this for `foss-2016b` and had to update a couple of extensions, will upload somewhere and let you know.

**Comment by verdurin** [comment]
`SuppDist`, `maps` and `TraMineR`.

**Comment by boegel** [comment]
@verdurin @rjeschmi Is this still relevant?

**Comment by migueldiascosta** [comment]
@rjeschmi, this PR is being closed for the following reason(s): no activity for > 1 year.
Please don't hesitate to reopen this PR or add a comment if you feel this contribution is still relevant.
For more information on our policy w.r.t. closing PRs, see https://easybuild.readthedocs.io/en/latest/Contributing.html#why-a-pull-request-may-be-closed-by-a-maintainer

**Pull request closed without merging**
