### PR TITLE
bump versions of `tensorboard v2.15.1` extensions and add reference to `protobuf-python` patch

### PR DESCRIPTION
**Pull request by jfgrimm**
requires: 
- [x] https://github.com/easybuilders/easybuild-easyconfigs/pull/19671

(created using `eb --new-pr`)

### CODE REVIEW

**Comment by jfgrimm** [comment]
@boegelbot: please test @ jsc-zen3

**Comment by jfgrimm** [comment]
^ expected failure since jsc-zen3 hadn't rebuilt protobuf-python with the required patch

**Comment by jfgrimm** [comment]
@boegelbot: please test @ jsc-zen3

**Comment by jfgrimm** [comment]
@boegelbot: please test @ generoso

**Comment by jfgrimm** [comment]
Test report by @jfgrimm
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
gpu07.viking2.yor.alces.network - Linux Rocky Linux 8.8, x86_64, AMD EPYC 7643 48-Core Processor, 2 x NVIDIA NVIDIA A40, 535.86.10, Python 3.6.8
See https://gist.github.com/jfgrimm/5542fc319f55d2a6b71c17d286b18561 for a full test report.

**Comment by jfgrimm** [comment]
@bedroge fixed the conflicts

**Comment by bedroge** [comment]
@boegelbot please test @ generoso

**Comment by bedroge** [comment]
Test report by @bedroge
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
interactive1 - Linux Rocky Linux 8.9, x86_64, AMD EPYC-Milan Processor (zen2), Python 3.6.8
See https://gist.github.com/bedroge/29a9e038e9b0de6f930fc4c248c9902f for a full test report.

**Comment by bedroge** [comment]
@boegelbot please test @ jsc-zen3

**Review by bedroge — APPROVED** [review]
Lgtm

**Comment by bedroge** [comment]
Going in, thanks @jfgrimm!

**Pull request merged**
