### PR TITLE
{chem}[foss/2022a] ESIpy v20240731

### PR DESCRIPTION
**Pull request by WilleBell**
(created using `eb --new-pr`)

This PR removes previous version: `ESIpy-20240709-foss-2022a.eb`, as user reported getting incorrect numbers with version `20240709` when calculating the so-called HOMA aromaticity descriptors:

> This descriptor is dependent on reference values and, recently, a scientific article proposed a new variant of this descriptor with new reference values called HOMER.
> However, this implementation gave weird results for my structures in comparison to their previous Fortran version (ESI-3D: ESI-3D/20230124-intel-compilers-2022.1.0). I asked the developers to check what was going on and they found that the new variant and their reference values is not suitable for what I want to do. So they took the HOMA descriptor from the Fortran code and implemented this in the current version. They have tested my molecules and now the values are indeed similar with this updated version. 

This seems to have been corrected in commit: https://github.com/jgrebol/ESIpy/commit/6785e72c960fca987ecb33ad01d013c3977cb773

### CODE REVIEW

**Comment by WilleBell** [comment]
Test report by @WilleBell
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
node600.hydra.os - Linux Rocky Linux 8.10, x86_64, AMD EPYC 9384X 32-Core Processor, Python 3.6.8
See https://gist.github.com/WilleBell/e32b2d75e96bd51c5cc0840c32d746a2 for a full test report.

**Comment by smoors** [comment]
@boegelbot please test @ jsc-zen3

**Comment by smoors** [comment]
@boegelbot: please test @ generoso

**Review by smoors — APPROVED** [review]
lgtm

**Comment by smoors** [comment]
Going in, thanks @WilleBell!

**Pull request merged**
