### PR TITLE
add various additional extensions to recent R easyconfigs

### PR DESCRIPTION
**Pull request by boegel**
requires https://github.com/easybuilders/easybuild-easyblocks/pull/1513 to ensure that `preinstallopts` for `hdf5r` is picked up

### CODE REVIEW

**Comment by boegel** [comment]
Test report by @boegel
**FAILED**
Build succeeded for 4 out of 5 (5 easyconfigs in this PR)
node2408.golett.os - Linux centos linux 7.5.1804, Intel(R) Xeon(R) CPU E5-2680 v3 @ 2.50GHz, Python 2.7.5
See https://gist.github.com/8051cef8a5fe35889716c77b4e495c31 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**FAILED**
Build succeeded for 4 out of 5 (5 easyconfigs in this PR)
node2408.golett.os - Linux centos linux 7.5.1804, Intel(R) Xeon(R) CPU E5-2680 v3 @ 2.50GHz, Python 2.7.5
See https://gist.github.com/5fe2e498efb6bb407629e322da087978 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**FAILED**
Build succeeded for 4 out of 5 (5 easyconfigs in this PR)
node2051.delcatty.os - Linux centos linux 7.5.1804, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.7.5
See https://gist.github.com/257d6e74fdf6efdda024accbfcb467df for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 5 out of 5 (5 easyconfigs in this PR)
node2051.delcatty.os - Linux centos linux 7.5.1804, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.7.5
See https://gist.github.com/d96ed55b59d31313345c6db785e55a7c for a full test report.

**Comment by vanzod** [comment]
Could you add the following extensions too?
```
('bayesm', '3.1-0.1'), {
    'checksums':['5879823b7fb6e6df0c0fe98faabc1044a4149bb65989062df4ade64e19d26411'],
}),
('compositions', '1.40-2'),
    'checksums':['110d71ae000561987cb73fc76cd953bd69d37562cb401ed3c36dca137d01b78a'],
}),
```

`compositions` requires other extensions that are already in the list. Appending it to the bottom should work.

**Comment by boegel** [comment]
Test report by @boegel
**FAILED**
Build succeeded for 0 out of 5 (5 easyconfigs in this PR)
node2400.golett.os - Linux centos linux 7.5.1804, Intel(R) Xeon(R) CPU E5-2680 v3 @ 2.50GHz, Python 2.7.5
See https://gist.github.com/af8a997befdb4519d1c157e4eb986ce7 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**FAILED**
Build succeeded for 0 out of 5 (5 easyconfigs in this PR)
node2013.delcatty.os - Linux centos linux 7.5.1804, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.7.5
See https://gist.github.com/10f8e2c7418b98743c3324b6af55ad05 for a full test report.

**Comment by migueldiascosta** [comment]
fails for me too, `ERROR: dependency ‘energy’ is not available for package ‘compositions’`

**Comment by boegel** [comment]
/me eyes @vanzod...

@migueldiascosta Please re-test?

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 5 out of 5 (5 easyconfigs in this PR)
node2419.golett.os - Linux centos linux 7.5.1804, Intel(R) Xeon(R) CPU E5-2680 v3 @ 2.50GHz, Python 2.7.5
See https://gist.github.com/a712a68d640e26feaf24966666809284 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 5 out of 5 (5 easyconfigs in this PR)
node2041.delcatty.os - Linux centos linux 7.5.1804, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.7.5
See https://gist.github.com/cf7f9dc4107baeed22539a12f419ad65 for a full test report.

**Comment by migueldiascosta** [comment]
Going in, thanks @boegel!

**Comment by migueldiascosta** [comment]
Test report by @migueldiascosta
**SUCCESS**
Build succeeded for 19 out of 19 (5 easyconfigs in this PR)
grc-cluster1 - Linux centos 6.9, Intel(R) Xeon(R) CPU E5-2640 0 @ 2.50GHz, Python 2.7.14
See https://gist.github.com/5680f7e338a7fb04a833903f9297b369 for a full test report.

**Pull request merged**
