### PR TITLE
libXp and printproto added to X11 bundle

### PR DESCRIPTION
**Pull request by damianam**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
node2404.golett.os - Linux centos linux 7.5.1804, Intel(R) Xeon(R) CPU E5-2680 v3 @ 2.50GHz, Python 2.7.5
See https://gist.github.com/f59d50e7ee71fd4362f56a47bf4e7988 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
node2041.delcatty.os - Linux centos linux 7.5.1804, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.7.5
See https://gist.github.com/dc27c30e1036c04cab9a2e561d6e2fef for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
node3101.skitty.os - Linux centos linux 7.5.1804, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz, Python 2.7.5
See https://gist.github.com/86f56c2a898f93395a6089dd9c8d24d9 for a full test report.

**Comment by damianam** [comment]
🤦 I am sabotaging my own PR with typos in my modules......... I'll reupload in a bit.

**Comment by boegel** [comment]
@damianam Travis isn't happy with the PR either, but that's because of a bug in the tests (probably triggered by the changes made in https://github.com/easybuilders/easybuild-framework/pull/2551, I'll look into fixing that issue...

**Comment by damianam** [comment]
Test report by @damianam
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
jrl01 - Linux centos linux 7.5.1804, Intel(R) Xeon(R) CPU E5-2680 v3 @ 2.50GHz, Python 2.7.5
See https://gist.github.com/b814ab6af611a1d2c53369f39a513155 for a full test report.

**Comment by boegel** [comment]
@damianam This requires https://github.com/damianam/easybuild-easyconfigs/pull/2 to fix the issue with the tests...

**Comment by boegel** [comment]
Going in, thanks @damianam!

**Pull request merged**
