### PR TITLE
{numlib}[GCCcore/12.2.0] CGAL v5.5.2

### PR DESCRIPTION
**Pull request by Micket**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by Micket** [comment]
I haven't tested this out with OpenFOAM and stuff yet, but it should be header only for some time now, so i opted to move it to GCCcore similar to what we do with Eigen since it also needs CMake.

**Comment by Micket** [comment]
Test report by @Micket
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
vera-c1 - Linux Rocky Linux 8.7, x86_64, Intel Xeon Processor (Skylake), Python 3.6.8
See https://gist.github.com/Micket/5cb756db5844ee63c0b80369967a7476 for a full test report.

**Comment by furstj** [comment]
Test report by @furstj
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
think - Linux openSUSE Leap 15.5, x86_64, Intel(R) Core(TM) i7-10700T CPU @ 2.00GHz, 1 x NVIDIA Quadro P1000, 535.86.05, Python 3.11.4
See https://gist.github.com/furstj/61f40e7b5a8f45cd33cc5f86ceb1e540 for a full test report.

**Comment by Micket** [comment]
@boegelbot please test @ generoso

**Comment by Micket** [comment]
@boegelbot please test @ jsc-zen2

**Review by branfosj — APPROVED** [review]

**Comment by branfosj** [comment]
Test report by @branfosj
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
bear-pg0105u03a.bear.cluster - Linux RHEL 8.6, x86_64, Intel(R) Xeon(R) Platinum 8360Y CPU @ 2.40GHz (icelake), Python 3.6.8
See https://gist.github.com/branfosj/6faad7476079d1579b9dadb84f40a014 for a full test report.

**Comment by branfosj** [comment]
Going in, thanks @Micket!

**Pull request merged**
