### PR TITLE
{numlib}[GCC/9.2.0] OpenBLAS v0.3.8

### PR DESCRIPTION
**Pull request by boegel**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in this PR)
generoso - Linux centos linux 7.6.1810, Intel(R) Xeon(R) CPU E5-2660 v4 @ 2.00GHz, Python 3.6.8
See https://gist.github.com/9115aebdd6b362ec3d693138811773df for a full test report.

**Comment by lexming** [comment]
Test report by @lexming
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in this PR)
login2.cerberus.os - Linux centos linux 7.7.1908, Intel(R) Xeon(R) Gold 6126 CPU @ 2.60GHz, Python 2.7.5
See https://gist.github.com/bd720531fa5dfee6a1e234fcae63037e for a full test report.

**Comment by branfosj** [comment]
Test report by @branfosj
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in this PR)
bear-pg0305u05a.bear.cluster - Linux RHEL 7.6, 8335-GTX, Python 2.7.5
See https://gist.github.com/0c96fd40e369d814f4bb33a102e069ff for a full test report.

**Comment by branfosj** [comment]
Test report by @branfosj
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in this PR)
bear-pg0211u03a.bear.cluster - Linux centos linux 7.7.1908, Intel(R) Xeon(R) Gold 6248 CPU @ 2.50GHz, Python 2.7.5
See https://gist.github.com/f26c6ca29dba97794704d919ca66c43a for a full test report.

**Comment by verdurin** [comment]
Test report by @verdurin
**SUCCESS**
Build succeeded for 0 out of 0 (2 easyconfigs in this PR)
epyc000.hpc.in.bmrc.ox.ac.uk - Linux centos linux 7.6.1810, AMD EPYC 7502 32-Core Processor, Python 2.7.5
See https://gist.github.com/ca907fed4504c1e8620af407342ac284 for a full test report.

**Comment by verdurin** [comment]
Test report by @verdurin
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in this PR)
epyc000.hpc.in.bmrc.ox.ac.uk - Linux centos linux 7.6.1810, AMD EPYC 7502 32-Core Processor, Python 2.7.5
See https://gist.github.com/a830b1a57261862a1459e8521cba36ce for a full test report.

**Comment by Micket** [comment]
Test report by @Micket
**SUCCESS**
Build succeeded for 9 out of 9 (2 easyconfigs in this PR)
hebbe-c1 - Linux centos linux 7.7.1908, Intel Core Processor (Haswell, no TSX), Python 2.7.5
See https://gist.github.com/2efc7c837e9f6c7f05d2bc5b1d134612 for a full test report.

**Comment by boegel** [comment]
Based on the test reports, I think this is good to go.

@migueldiascosta Can you look into another test report from you, and then review/merge?

**Comment by verdurin** [comment]
Test report by @verdurin
**SUCCESS**
Build succeeded for 9 out of 9 (2 easyconfigs in this PR)
rescomp2.hpc.in.bmrc.ox.ac.uk - Linux centos linux 7.6.1810, Intel(R) Xeon(R) Gold 6126 CPU @ 2.60GHz, Python 2.7.5
See https://gist.github.com/79477ac27a2ef406f2d6105aed2ef470 for a full test report.

**Comment by Micket** [comment]
Test report by @Micket
**SUCCESS**
Build succeeded for 9 out of 9 (2 easyconfigs in this PR)
vera-c1 - Linux centos linux 7.7.1908, Intel Xeon Processor (Skylake), Python 2.7.5
See https://gist.github.com/6d2300d1e8ae680605de587a517b80af for a full test report.

**Comment by orbsmiv** [comment]
Test report by @orbsmiv
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in this PR)
bear-pg0305u05a.bear.cluster - Linux RHEL 7.6, 8335-GTX, Python 2.7.5
See https://gist.github.com/dbb0d4b2f68b23521cd2b1cba8cc592c for a full test report.

**Comment by zao** [comment]
Test report by @zao
**SUCCESS**
Build succeeded for 9 out of 9 (2 easyconfigs in this PR)
freja - Linux ubuntu 18.04, Intel(R) Core(TM) i7-8700K CPU @ 3.70GHz, Python 2.7.17
See https://gist.github.com/c4d66b4965b518ba75374d94e01a5241 for a full test report.

**Comment by branfosj** [comment]
Test report by @branfosj
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in this PR)
bb2c1a09.bb2.cluster - Linux centos linux 7.7.1908, Intel(R) Xeon(R) CPU E5-2660 0 @ 2.20GHz, Python 2.7.5
See https://gist.github.com/ed97a3137ef0c34daaf382df96555c75 for a full test report.

**Comment by akesandgren** [comment]
Test report by @akesandgren
**SUCCESS**
Build succeeded for 9 out of 9 (2 easyconfigs in this PR)
b-an03.hpc2n.umu.se - Linux ubuntu 16.04, Intel(R) Xeon(R) CPU E5-2690 v4 @ 2.60GHz, Python 2.7.12
See https://gist.github.com/a0b0c9153d3654ac29711ce831069883 for a full test report.

**Comment by terjekv** [comment]
Test report by @terjekv
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in this PR)
ninhursaga.uio.no - Linux red hat enterprise linux 8.1, Intel(R) Xeon(R) Silver 4216 CPU @ 2.10GHz, Python 3.6.8
See https://gist.github.com/1e22d4e1d89f8b5387be2b24de303772 for a full test report.

**Comment by terjekv** [comment]
Builds fine, but is still affected by https://github.com/easybuilders/easybuild-easyconfigs/issues/9754

**Comment by migueldiascosta** [comment]
Test report by @migueldiascosta
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in this PR)
sms - Linux centos linux 7.6.1810, AMD EPYC 7601 32-Core Processor, Python 2.7.5
See https://gist.github.com/5bd2309a9ef83de5f638aaf8aa01b674 for a full test report.

**Comment by migueldiascosta** [comment]
Going in, thanks @boegel!

**Comment by akesandgren** [comment]
Test report by @akesandgren
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in this PR)
b-cn1404.hpc2n.umu.se - Linux ubuntu 16.04, Intel(R) Xeon(R) Gold 6132 CPU @ 2.60GHz, Python 2.7.12
See https://gist.github.com/885410b91aedbe59ea45994cb4b34736 for a full test report.

**Comment by casparvl** [comment]
As @lexming reported in the maintainers channel, there is a problem with this build on Skylake nodes.

The EasyBuild installation completes succesfully, however:

```
== 2020-02-11 14:53:07,807 run.py:589 INFO parse_log_for_error (some may be harmless) regExp (?<![(,-]|\w)(?:error|segmentation fault|failed)(?![(,-]|\.?\w) found:
 2049 |        printf("error code=%d,\trelease->address=%lx\n",errsv,release->address);
 ******* FATAL ERROR - COMPUTED RESULT IS LESS THAN HALF ACCURATE *******
 ******* DGEMV  FAILED ON CALL NUMBER:
 ******* FATAL ERROR - COMPUTED RESULT IS LESS THAN HALF ACCURATE *******
 ******* DGBMV  FAILED ON CALL NUMBER:
 ******* FATAL ERROR - COMPUTED RESULT IS LESS THAN HALF ACCURATE *******
 ******* DSYMV  FAILED ON CALL NUMBER:
 ******* FATAL ERROR - COMPUTED RESULT IS LESS THAN HALF ACCURATE *******
 ******* DSBMV  FAILED ON CALL NUMBER:
 ******* FATAL ERROR - COMPUTED RESULT IS LESS THAN HALF ACCURATE *******
 ******* DSPMV  FAILED ON CALL NUMBER:
 ******* FATAL ERROR - COMPUTED RESULT IS LESS THAN HALF ACCURATE *******
 ******* DGEMV  FAILED ON CALL NUMBER:
 ******* FATAL ERROR - COMPUTED RESULT IS LESS THAN HALF ACCURATE *******
 ******* DGBMV  FAILED ON CALL NUMBER:
 ******* FATAL ERROR - COMPUTED RESULT IS LESS THAN HALF ACCURATE *******
 ******* DSYMV  FAILED ON CALL NUMBER:
 ******* FATAL ERROR - COMPUTED RESULT IS LESS THAN HALF ACCURATE *******
 ******* DSBMV  FAILED ON CALL NUMBER:
 ******* FATAL ERROR - COMPUTED RESULT IS LESS THAN HALF ACCURATE *******
 ******* DSPMV  FAILED ON CALL NUMBER:
 ******* FATAL ERROR - COMPUTED RESULT IS LESS THAN HALF ACCURATE *******
 ******* cblas_dgemv  FAILED ON CALL NUMBER:
 ******* cblas_dgemv  FAILED ON CALL NUMBER:
 ******* FATAL ERROR - TESTS ABANDONED *******
== 2020-02-11 14:53:07,807 run.py:546 WARNING Found 25 errors in command output (output:  2049 |        printf("error code=%d,\trelease->address=%lx\n",errsv,release->address);
         ******* FATAL ERROR - COMPUTED RESULT IS LESS THAN HALF ACCURATE *******
         ******* DGEMV  FAILED ON CALL NUMBER:
         ******* FATAL ERROR - COMPUTED RESULT IS LESS THAN HALF ACCURATE *******
         ******* DGBMV  FAILED ON CALL NUMBER:
         ******* FATAL ERROR - COMPUTED RESULT IS LESS THAN HALF ACCURATE *******
         ******* DSYMV  FAILED ON CALL NUMBER:
         ******* FATAL ERROR - COMPUTED RESULT IS LESS THAN HALF ACCURATE *******
         ******* DSBMV  FAILED ON CALL NUMBER:
         ******* FATAL ERROR - COMPUTED RESULT IS LESS THAN HALF ACCURATE *******
         ******* DSPMV  FAILED ON CALL NUMBER:
         ******* FATAL ERROR - COMPUTED RESULT IS LESS THAN HALF ACCURATE *******
         ******* DGEMV  FAILED ON CALL NUMBER:
         ******* FATAL ERROR - COMPUTED RESULT IS LESS THAN HALF ACCURATE *******
         ******* DGBMV  FAILED ON CALL NUMBER:
         ******* FATAL ERROR - COMPUTED RESULT IS LESS THAN HALF ACCURATE *******
         ******* DSYMV  FAILED ON CALL NUMBER:
         ******* FATAL ERROR - COMPUTED RESULT IS LESS THAN HALF ACCURATE *******
         ******* DSBMV  FAILED ON CALL NUMBER:
         ******* FATAL ERROR - COMPUTED RESULT IS LESS THAN HALF ACCURATE *******
         ******* DSPMV  FAILED ON CALL NUMBER:
         ******* FATAL ERROR - COMPUTED RESULT IS LESS THAN HALF ACCURATE *******
         ******* cblas_dgemv  FAILED ON CALL NUMBER:
         ******* cblas_dgemv  FAILED ON CALL NUMBER:
         ******* FATAL ERROR - TESTS ABANDONED *******)
== 2020-02-11 14:53:07,807 run.py:546 WARNING Found 25 errors in command output (output:  2049 |        printf("error code=%d,\trelease->address=%lx\n",errsv,release->address);
         ******* FATAL ERROR - COMPUTED RESULT IS LESS THAN HALF ACCURATE *******
         ******* DGEMV  FAILED ON CALL NUMBER:
         ******* FATAL ERROR - COMPUTED RESULT IS LESS THAN HALF ACCURATE *******
         ******* DGBMV  FAILED ON CALL NUMBER:
         ******* FATAL ERROR - COMPUTED RESULT IS LESS THAN HALF ACCURATE *******
         ******* DSYMV  FAILED ON CALL NUMBER:
         ******* FATAL ERROR - COMPUTED RESULT IS LESS THAN HALF ACCURATE *******
         ******* DSBMV  FAILED ON CALL NUMBER:
         ******* FATAL ERROR - COMPUTED RESULT IS LESS THAN HALF ACCURATE *******
         ******* DSPMV  FAILED ON CALL NUMBER:
         ******* FATAL ERROR - COMPUTED RESULT IS LESS THAN HALF ACCURATE *******
         ******* DGEMV  FAILED ON CALL NUMBER:
         ******* FATAL ERROR - COMPUTED RESULT IS LESS THAN HALF ACCURATE *******
         ******* DGBMV  FAILED ON CALL NUMBER:
         ******* FATAL ERROR - COMPUTED RESULT IS LESS THAN HALF ACCURATE *******
         ******* DSYMV  FAILED ON CALL NUMBER:
         ******* FATAL ERROR - COMPUTED RESULT IS LESS THAN HALF ACCURATE *******
         ******* DSBMV  FAILED ON CALL NUMBER:
         ******* FATAL ERROR - COMPUTED RESULT IS LESS THAN HALF ACCURATE *******
         ******* DSPMV  FAILED ON CALL NUMBER:
         ******* FATAL ERROR - COMPUTED RESULT IS LESS THAN HALF ACCURATE *******
         ******* cblas_dgemv  FAILED ON CALL NUMBER:
         ******* cblas_dgemv  FAILED ON CALL NUMBER:
         ******* FATAL ERROR - TESTS ABANDONED *******)
```

This was on a ```Intel(R) Xeon(R) Silver 4110 CPU @ 2.10GHz``` optimizing for AVX-512. In other words: we cannot rely on this build in its current state...

Some action points...
- Fix EasyBuild (probably: the OpenBLAS EasyBlock) to make sure the install doesn't complete succesfully for these cases... 
- Try and fix the build
- Contact OpenBLAS devs

**Comment by akesandgren** [comment]
I also get
FATAL ERROR - COMPUTED RESULT IS LESS THAN HALF ACCURATE
on Skylakes, which doesn't cause errors in EB

**Comment by akesandgren** [comment]
See https://github.com/xianyi/OpenBLAS/issues/2408

**Comment by branfosj** [comment]
I'm seeing the same erros on our CascadeLake nodes. (Sandybridge, Haswell, and Power pass the tests.)

**Comment by lexming** [comment]
Quick fix for xianyi/OpenBLAS#2408 if you need to deploy this asap is to add `toolchainopts = {'vectorize': False}` to the easyconfig `OpenBLAS-0.3.8-GCC-9.2.0.eb`

**Comment by akesandgren** [comment]
@lexming can you make a PR for this?

**Comment by lexming** [comment]
@lexming sure, but first we should fix the `openblas` easyblock to properly check such errors. Working on it.

**Comment by akesandgren** [comment]
Test report by @akesandgren
**SUCCESS**
Build succeeded for 0 out of 0 (2 easyconfigs in this PR)
b-an03.hpc2n.umu.se - Linux ubuntu 16.04, Intel(R) Xeon(R) CPU E5-2690 v4 @ 2.60GHz, Python 2.7.12
See https://gist.github.com/c17aa694716b90192dd16e8c073a2417 for a full test report.

**Comment by boegel** [comment]
should be fixed with #9867...

**Comment by Flamefire** [comment]
Test report by @Flamefire
**SUCCESS**
Build succeeded for 9 out of 9 (2 easyconfigs in this PR)
taurusml2 - Linux RHEL 7.6, 8335-GTX, Python 2.7.5
See https://gist.github.com/ed0590e8e91c2f1c42e2696b17c75573 for a full test report.

**Pull request merged**
