### PR TITLE
{bio,lib}[foss/2022a] AlphaPulldown v0.30.7, cctbx-base v2023.5

### PR DESCRIPTION
**Pull request by boegel**
(created using `eb --new-pr`)
requires:
* https://github.com/easybuilders/easybuild-easyconfigs/pull/18505

### CODE REVIEW

**Comment by boegel** [comment]
@boegelbot please test @ generoso

**Comment by boegel** [comment]
@boegelbot please test @ jsc-zen2

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in total)
node3116.skitty.os - Linux RHEL 8.6, x86_64, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz (skylake_avx512), Python 3.6.8
See https://gist.github.com/boegel/f7c0b0675775fa03036dff26ffabf48e for a full test report.

**Comment by ThomasHoffmann77** [comment]
@boegel 

- The bootstrap script downloads plenty of sources on the fly. [cctbx_dnl_sources_2023.6.txt.gz](https://github.com/easybuilders/easybuild-easyconfigs/files/12319721/cctbx_dnl_sources_2023.6.txt.gz)
To avoid this, the libtbx/configure.py could be used with the ConfigureMake easyblock. It would require a patch in order to handle "--prefix". [cctbx-2023.6_configure_prefix.patch.gz](https://github.com/easybuilders/easybuild-easyconfigs/files/12319978/cctbx-2023.6_configure_prefix.patch.gz)
- The test step or sanity check step could contain
 `cd $(mktemp -d) && libtbx.run_tests_parallel module=modulename` with modulename=cctbx (and  mmtbx, libtbx, smtbx, iotbx, ... if installed). Some of these tests will fail due to expecting data in modules/chem_data. Others require regression data only available in the phenix-release sources.
- As far as I understand cctbx requires the build directory at runtime (?) (see site-packages/libtbx/env_config.py line 2993)
-> buildininstalldir = True ? or modify libtbx_env pickle
I still cannot `python -c "import cctbx"`  after loading the cctbx-base module.

**Comment by verdurin** [comment]
Test report by @verdurin
**FAILED**
Build succeeded for 10 out of 11 (2 easyconfigs in total)
easybuild-c7.novalocal - Linux CentOS Linux 7.9.2009, x86_64, Intel Xeon Processor (Skylake, IBRS), Python 3.6.8
See https://gist.github.com/verdurin/fd35081c179af46081d99d3d192569e8 for a full test report.

**Comment by boegel** [comment]
@ThomasHoffmann77 Thanks a lot for the feedback, I clearly overlooked some important details...

Can you share your easyconfig file, even if it's not clean/finished, so we can look into a better approach based on both initial attempts?

**Comment by ThomasHoffmann77** [comment]
cctbx dependency is planned to be replaced by biopython: https://github.com/KosinskiLab/AlphaPulldown/issues/343

**Comment by ThomasHoffmann77** [comment]
> cctbx dependency is planned to be replaced by biopython: [KosinskiLab/AlphaPulldown#343](https://github.com/KosinskiLab/AlphaPulldown/issues/343)

see: https://github.com/KosinskiLab/AlphaPulldown/commit/525feb82f629a8d5e70b06cf954445ae3b8c71dd

**Comment by boegel** [comment]
New PR for latest AlphaPulldown version that doesn't depend on `cctbx-base` anymore:
* #21179

**Pull request closed without merging**
