### PR TITLE
fix Mako easyconfigs using a 2016 & 2017 toolchain

### LINKED ISSUE #10462: installation of older Mako easyconfigs broken because MarkupSafe 2.0.0a1 is picked up
For example, `Mako-1.0.7-intel-2018a-Python-2.7.14.eb` fails with:

```
== 2020-04-23 14:17:13,104 build_log.py:169 ERROR EasyBuild crashed with an error (at easybuild/base/exceptions.py:124 in __init__): cmd " /software/Python/2.7.14-intel-2018a/bin/python setup.py install --prefix=/software/Mako/1.0.7-intel-2018a-Python-2.7.14 " exited with exit code 1 and output:
...
Processing dependencies for Mako==1.0.7
Searching for MarkupSafe>=0.9.2
Reading https://pypi.python.org/simple/MarkupSafe/
Downloading https://files.pythonhosted.org/packages/e0/bf/acc45baeb2d7333ed724c30af188640d9cb0be4b28533edfc3e2ae5aad72/MarkupSafe-2.0.0a1.tar.gz#sha256=beac28ed60c8e838301226a7a85841d0af2068eba2dcb1a58c2d32d6c05e440e
Best match: MarkupSafe 2.0.0a1
Processing MarkupSafe-2.0.0a1.tar.gz
...
ImportError: No module named markupsafe
```

Can be fixed relatively easy by making the broken `Mako` easyconfigs use `PythonBundle`, and adding `MarkupSafe` 1.1.1 as an extension in them.

This doesn't affect recent `Mako` easyconfigs like `Mako-1.0.8-GCCcore-8.2.0.eb` & newer, because the underlying `Python` already includes `MarkupSafe` 1.1.1

### PR DESCRIPTION
**Pull request by boegel**
fixes #10462

### CODE REVIEW

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 8 out of 8 (8 easyconfigs in this PR)
generoso - Linux centos linux 7.6.1810, x86_64, Intel(R) Xeon(R) CPU E5-2660 v4 @ 2.00GHz, Python 3.6.8
See https://gist.github.com/312efd016564abff56da5c39dfe96978 for a full test report.

**Comment by boegel** [comment]
close/re-open to wake up Travis...

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 8 out of 8 (8 easyconfigs in this PR)
node2618.swalot.os - Linux centos linux 7.7.1908, x86_64, Intel(R) Xeon(R) CPU E5-2660 v3 @ 2.60GHz (haswell), Python 2.7.5
See https://gist.github.com/1f7061212129c31ac43bf8ef2674ea0b for a full test report.

**Comment by verdurin** [comment]
Going in, thanks @boegel!

**Pull request merged**
