### PR TITLE
{numlib}[system/system] cuDNN v8.0.5.39

### PR DESCRIPTION
**Pull request by lexming**
(created using `eb --new-pr`)

Nvidia has stopped shipping the version for PPC and instead it now ships a version for ARM. The title of the download section still says "_x86_64 & PPC architecture_" though. So I'm not sure if this is really intended, but right now this is what's available.

### CODE REVIEW

**Comment by lexming** [comment]
Test report by @lexming
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in total)
node154.hydra.os - Linux centos linux 7.9.2009, x86_64, Intel(R) Xeon(R) CPU E5-2680 v2 @ 2.80GHz, Python 2.7.5
See https://gist.github.com/c29c1271524e5fdc24b25772e162f1b5 for a full test report.

**Comment by Micket** [comment]
I don't think we need or want a `gcccuda` versions of this package now that they depend on the same CUDAcore. In fact, I don't think we needed `cuDNN-8.0.4.30-gcccuda-2020a.eb` either, so, in fact I would suggest dropping those before next release. The core-level package should suffice as a dependency, just like with NCCL, and, well, CUDAcore itself.

**Comment by boegel** [comment]
@Micket Can you open a PR to remove `cuDNN-8.0.4.30-gcccuda-2020a.eb`, and tag it for the "next release" milestone, so we don't overlook it?

**Comment by lexming** [comment]
I made this because packages in `fosscuda/2020a` and `fosscuda/2020b` were failing to find this dependencies.

**Comment by lexming** [comment]
So the plan is having to add the `CUDA` versionsuffix for these dependencies? I think that is not ideal, the easyconfig already sets the `fosscuda` toolchain, EB should be able to figure out which dependency to take without me telling (again) the CUDA version of these dependencies.

**Comment by lexming** [comment]
@Micket @boegel removed the easyconfig in `gcccuda`

**Comment by boegel** [comment]
@boegelbot please test @ generoso

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
node3607.doduo.os - Linux RHEL 8.2, x86_64, AMD EPYC 7552 48-Core Processor (zen2), Python 3.6.8
See https://gist.github.com/3a0924a3e12521fb6642d9c8c0c8833b for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
node3106.skitty.os - Linux centos linux 7.9.2009, x86_64, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz, Python 3.6.8
See https://gist.github.com/6c1ec151faf4be2d490cdce1ce8daa98 for a full test report.

**Review by boegel — APPROVED** [review]
lgtm

**Comment by boegel** [comment]
Going in, thanks @lexming!

**Pull request merged**
