### PR TITLE
Disable sanity_pip_check for pydicom v1.4.2

### PR DESCRIPTION
**Pull request by crubb**
(created using `eb --new-pr`)

Error message was: `DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future version of pip will drop support for Python 2.7.` (..)

### CODE REVIEW

**Comment by smoors** [comment]
@crubb the 'error' message is actually a warning, `pip check` should not fail with it.
It tried it myself and the install went perfectly fine. Did it really fail for you?

**Comment by crubb** [comment]
It fails for me with `sanity_pip_check = True`, @smoors:

```
== temporary log file in case of crash /tmp/eb-d7zCPY/easybuild-H3CVC1.log

WARNING: Deprecated functionality, will no longer work in v5.0: Support for Lmod version < 7.0.0 is deprecated, found version 6.6; see http://easybuild.readthedocs.org/en/latest/Deprecated-functionality.html for more information

== resolving dependencies ...
== processing EasyBuild easyconfig /home/rubbert/eb--new-pr/pydicom-1.4.2-GCCcore-8.3.0.eb
== building and installing pydicom/1.4.2-GCCcore-8.3.0...
== fetching files...
== creating build dir, resetting environment...
== starting iteration #0 ...
== unpacking...
== patching...
== preparing...
== configuring...
== building...
== testing...
== installing...
== taking care of extensions...
== creating build dir, resetting environment...
== starting iteration #1 ...
== unpacking...
== patching...
== preparing...
== configuring...
== building...
== testing...
== installing...
== taking care of extensions...
== restore after iterating...
== postprocessing...
== sanity checking...
== FAILED: Installation ended unsuccessfully (build directory: /software/easybuild4/build/pydicom/1.4.2/GCCcore-8.3.0): build failed (first 300 chars): cmd "pip check" exited with exit code 1 and output:
DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future version of pip will drop support for Python 2.7. More details about Python 2 support (took 19 sec)
== Results of the build can be found in the log file(s) /tmp/eb-d7zCPY/easybuild-pydicom-1.4.2-20200413.104636.QhOca.log
ERROR: Build of /home/rubbert/eb--new-pr/pydicom-1.4.2-GCCcore-8.3.0.eb failed (err: 'build failed (first 300 chars): cmd "pip check" exited with exit code 1 and output:\nDEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won\'t be maintained after that date. A future version of pip will drop support for Python 2.7. More details about Python 2 support')
```

**Comment by crubb** [comment]
@smoors Ping? ;)

**Comment by smoors** [comment]
can you show the output of your log file?

**Comment by crubb** [comment]
@smoors Sure! https://gist.github.com/crubb/7831f368512eb85b17385fa06cee469c

**Comment by smoors** [comment]
@crubb the log file is not showing the actual error. could you re-run with `--debug`?

**Comment by crubb** [comment]
Sure: https://gist.github.com/crubb/bab9df328545432210447dac65e74f66 ;)

**Comment by smoors** [comment]
@crubb now we finally have your error:
```
pytest 4.6.5 requires wcwidth, which is not installed.
```
wcwidth is part of the Python easyconfig, but for some reason it's not installed for you?

**Comment by crubb** [comment]
Just  noticed that as well, maybe my Python is older than https://github.com/easybuilders/easybuild-easyconfigs/commit/5d02fc3be7984deb1e5e56b7e1a3efdfa07e9454 - I'm just rebuilding Python.

**Comment by crubb** [comment]
Well, that did the trick. `wcwidth` was missing in my "older" Python install. Thank you for pointing me to `--debug`.

**Pull request closed without merging**
