### PR TITLE
{quantum}[foss/2021a] Qiskit v0.29.0 w/ Python 3.9.5

### PR DESCRIPTION
**Pull request by Micket**
(created using `eb --new-pr`)
Edit: untested yet! and they had looots of changes this time around

### CODE REVIEW

**Comment by Micket** [comment]
Test report by @Micket
**FAILED**
Build succeeded for 0 out of 1 (1 easyconfigs in total)
alvis-c1 - Linux centos linux 7.9.2009, x86_64, Intel Xeon Processor (Skylake), Python 3.6.8
See https://gist.github.com/a7b5fd65e6b090a588ade981ba22c2a6 for a full test report.

**Comment by Micket** [comment]
Test report by @Micket
**FAILED**
Build succeeded for 0 out of 1 (1 easyconfigs in total)
alvis-c1 - Linux centos linux 7.9.2009, x86_64, Intel Xeon Processor (Skylake), Python 3.6.8
See https://gist.github.com/56505dc065004181002a0876ea89b7cf for a full test report.

**Comment by Micket** [comment]
I accidentally make a duplicate.

**Comment by boegel** [comment]
see #13782

**Pull request closed without merging**
