### PR TITLE
use `sysroot` template in `wget` easyconfigs to define `PKG_CONFIG_PATH`

### PR DESCRIPTION
**Pull request by xinan1911**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by xinan1911** [comment]
This pr depends on another pr in easybuild-framework https://github.com/easybuilders/easybuild-framework/pull/4359.

**Comment by casparvl** [comment]
@boegelbot please test @ generoso

**Comment by casparvl** [comment]
Test report by @casparvl
**SUCCESS**
Build succeeded for 6 out of 6 (6 easyconfigs in total)
tcn1.local.snellius.surf.nl - Linux RHEL 8.6, x86_64, AMD EPYC 7H12 64-Core Processor, Python 3.6.8
See https://gist.github.com/casparvl/55f3383c28ba7b3e15ed9abeaf1ab86b for a full test report.

**Comment by casparvl** [comment]
Test report by @casparvl
**SUCCESS**
Build succeeded for 6 out of 6 (6 easyconfigs in total)
tcn1.local.snellius.surf.nl - Linux RHEL 8.6, x86_64, AMD EPYC 7H12 64-Core Processor, Python 3.6.8
See https://gist.github.com/casparvl/d353d58ec68df8f62f4e02f594bde25d for a full test report.

**Comment by casparvl** [comment]
@boegelbot please test @ generoso
EB_ARGS="wget-1.20.1-GCCcore-8.3.0.eb wget-1.20.3-GCCcore-10.2.0.eb wget-1.20.3-GCCcore-9.3.0.eb wget-1.21.1-GCCcore-10.3.0.eb wget-1.21.2-GCCcore-11.2.0.eb wget-1.21.3-GCCcore-11.3.0.eb"

**Comment by casparvl** [comment]
N.B. I'm not testing the oldest `wget`'s, those toolchains are deprecated anyway, and on my local system I couldn't build those toolchains anymore. Maybe that's also why generoso didn't return earlier with a result... hoping this works :)

**Comment by casparvl** [comment]
@boegelbot please test @ jsc-zen2
EB_ARGS="wget-1.20.1-GCCcore-8.3.0.eb wget-1.20.3-GCCcore-10.2.0.eb wget-1.20.3-GCCcore-9.3.0.eb wget-1.21.1-GCCcore-10.3.0.eb wget-1.21.2-GCCcore-11.2.0.eb wget-1.21.3-GCCcore-11.3.0.eb"

**Comment by boegel** [comment]
@boegelbot please test @ jsc-zen2
EB_ARGS="wget-1.20.1-GCCcore-8.3.0.eb wget-1.20.3-GCCcore-10.2.0.eb wget-1.20.3-GCCcore-9.3.0.eb wget-1.21.1-GCCcore-10.3.0.eb wget-1.21.2-GCCcore-11.2.0.eb wget-1.21.3-GCCcore-11.3.0.eb"

**Review by boegel — APPROVED** [review]
lgtm

**Comment by boegel** [comment]
@boegelbot please test @ generoso
EB_ARGS="wget-1.20.1-GCCcore-7.3.0.eb wget-1.20.1-GCCcore-8.3.0.eb wget-1.20.3-GCCcore-10.2.0.eb wget-1.20.3-GCCcore-9.3.0.eb wget-1.21.1-GCCcore-10.3.0.eb wget-1.21.2-GCCcore-11.2.0.eb wget-1.21.3-GCCcore-11.3.0.eb "

**Comment by boegel** [comment]
Test report by @boegel
**FAILED**
Build succeeded for 0 out of 6 (6 easyconfigs in total)
node3100.skitty.os - Linux RHEL 8.8, x86_64, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz (skylake_avx512), Python 3.6.8
See https://gist.github.com/boegel/26ca21092e8f022d1d50af4e24b5b720 for a full test report.

**Comment by boegel** [comment]
I've verified that this works in the EESSI build environment as intended :+1:

**Comment by boegel** [comment]
@boegelbot please test @ generoso
EB_ARGS="wget-1.20.1-GCCcore-7.3.0.eb wget-1.20.1-GCCcore-8.3.0.eb wget-1.20.3-GCCcore-10.2.0.eb wget-1.20.3-GCCcore-9.3.0.eb wget-1.21.1-GCCcore-10.3.0.eb wget-1.21.2-GCCcore-11.2.0.eb wget-1.21.3-GCCcore-11.3.0.eb "

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 6 out of 6 (6 easyconfigs in total)
node3100.skitty.os - Linux RHEL 8.8, x86_64, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz (skylake_avx512), Python 3.6.8
See https://gist.github.com/boegel/920f21f8aebce17bf1fe6f5f40d013c7 for a full test report.

**Comment by boegel** [comment]
Going in, thanks @xinan1911!

**Pull request merged**
