### PR TITLE
{devel,lib,system,tools}[GCCcore/10.2.0] OpenPGM v5.2.122, ZeroMQ v4.3.3, IPython v7.18.1, JupyterLab v2.2.8 ... w/ Python 3.8.6

### PR DESCRIPTION
**Pull request by Micket**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by Micket** [comment]
Test report by @Micket
**FAILED**
Build succeeded for 1 out of 5 (5 easyconfigs in this PR)
vera-c1 - Linux centos linux 7.8.2003, x86_64, Intel Xeon Processor (Skylake), Python 2.7.5
See https://gist.github.com/e43bee6320db90dfc7f17773de9d772b for a full test report.

**Comment by Micket** [comment]
Test report by @Micket
**FAILED**
Build succeeded for 3 out of 5 (5 easyconfigs in this PR)
vera-c1 - Linux centos linux 7.8.2003, x86_64, Intel Xeon Processor (Skylake), Python 2.7.5
See https://gist.github.com/8013f7087e61b946bc5b55e18fc55a7d for a full test report.

**Comment by boegel** [comment]
@Micket Minor issue to fix, see your failing test report:

```
notebook 6.1.4 requires terminado, which is not installed.
```

**Comment by Micket** [comment]
Test report by @Micket
**SUCCESS**
Build succeeded for 5 out of 5 (5 easyconfigs in this PR)
vera-c1 - Linux centos linux 7.8.2003, x86_64, Intel Xeon Processor (Skylake), Python 2.7.5
See https://gist.github.com/e12d678785a6108ef0a9ec3e184b132e for a full test report.

**Comment by Micket** [comment]
@boegelbot please test @ generoso

**Comment by zao** [comment]
Test report by @zao
**SUCCESS**
Build succeeded for 5 out of 5 (5 easyconfigs in total)
freja - Linux Ubuntu 20.04, x86_64, Intel(R) Core(TM) i7-8700K CPU @ 3.70GHz (skylake), Python 3.8.5
See https://gist.github.com/77c9e2f8e0e862e1b53511ccdc65b7c8 for a full test report.

**Comment by smoors** [comment]
Test report by @smoors
**SUCCESS**
Build succeeded for 6 out of 6 (5 easyconfigs in total)
node379.hydra.os - Linux centos linux 7.7.1908, x86_64, Intel(R) Xeon(R) Gold 6148 CPU @ 2.40GHz (skylake_avx512), Python 2.7.5
See https://gist.github.com/2c21f86bc69e55317fe15413fc23923c for a full test report.

**Comment by Micket** [comment]
Test report by @Micket
**SUCCESS**
Build succeeded for 5 out of 5 (5 easyconfigs in this PR)
vera-c1 - Linux centos linux 7.8.2003, x86_64, Intel Xeon Processor (Skylake), Python 2.7.5
See https://gist.github.com/99e03d3965193f1c391c02a203c3f8d0 for a full test report.

**Review by smoors — APPROVED** [review]
lgtm

**Comment by smoors** [comment]
(I had to merge manually because --merge-pr wrongly states that tests are pending)

**Pull request merged**
