### PR TITLE
{bio}[GCC/8.2.0-2.31.1] BamTools v2.5.1, BEDTools v2.28.0, Pysam v0.15.2, ... w/ Python 2.7.15 + 3.7.2

### PR DESCRIPTION
**Pull request by smoors**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by smoors** [comment]
Test report by @smoors
**SUCCESS**
Build succeeded for 4 out of 4 (4 easyconfigs in this PR)
nic423 - Linux centos linux 7.5.1804, Intel(R) Xeon(R) Gold 6148 CPU @ 2.40GHz, Python 2.7.5
See https://gist.github.com/1b038aeb40d96dc3f06c6310ecb717bc for a full test report.

**Comment by verdurin** [comment]
Test report by @verdurin
**FAILED**
Build succeeded for 2 out of 4 (4 easyconfigs in this PR)
easybuild.novalocal - Linux centos linux 7.6.1810, Intel Xeon Processor (Skylake, IBRS), Python 2.7.5
See https://gist.github.com/1d72e6445ee3d792e96cada9fcc8411f for a full test report.

**Comment by verdurin** [comment]
@smoors this looks to be the error:
```
- Building in src/flankBed
gcc -g -Wall -O2 -I.  -c -o cram/cram_io.o cram/cram_io.c
  * compiling flankBedMain.cpp
cram/cram_io.c:61:10: fatal error: lzma.h: No such file or directory
 #include <lzma.h>
          ^~~~~~~~
compilation terminated.
make[1]: *** [cram/cram_io.o] Error 1
make[1]: *** Waiting for unfinished jobs....
```

**Comment by verdurin** [comment]
Test report by @verdurin
**SUCCESS**
Build succeeded for 2 out of 2 (4 easyconfigs in this PR)
easybuild.novalocal - Linux centos linux 7.6.1810, Intel Xeon Processor (Skylake, IBRS), Python 2.7.5
See https://gist.github.com/0101a9d1081d65b23aef8c36e0fb3d58 for a full test report.

**Comment by verdurin** [comment]
Going in, thanks @smoors!

**Pull request merged**
