### PR TITLE
{bio}[foss/2018b] shovill 1.0.4 (+ deps) w/ Python 2.7.15

### PR DESCRIPTION
**Pull request by boegel**
(created using `eb --new-pr`)
requires ~~#7225~~ + ~~#7275~~ (SKESA)

### CODE REVIEW

**Comment by migueldiascosta** [comment]
Test report by @migueldiascosta
**FAILED**
Build succeeded for 10 out of 14 (9 easyconfigs in this PR)
grc-cluster1 - Linux centos 6.10, Intel(R) Xeon(R) CPU E5-2640 0 @ 2.50GHz, Python 2.7.14
See https://gist.github.com/05f09e4db354fe9a44f8c5d7a822cffd for a full test report.

**Comment by boegel** [comment]
now also requires #7275, which fixes a booboo with `SKESA`...

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 10 out of 10 (10 easyconfigs in this PR)
node3102.skitty.os - Linux centos linux 7.5.1804, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz, Python 2.7.5
See https://gist.github.com/7e0a927f6ae00c78ede37dc1b76a604f for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 10 out of 10 (10 easyconfigs in this PR)
node2668.swalot.os - Linux centos linux 7.5.1804, Intel(R) Xeon(R) CPU E5-2660 v3 @ 2.60GHz, Python 2.7.5
See https://gist.github.com/ad1ed3199bcd96c53a269bdedf7c9e7c for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 10 out of 10 (10 easyconfigs in this PR)
node2107.delcatty.os - Linux centos linux 7.5.1804, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.7.5
See https://gist.github.com/95601d15c13e968aca2025ce039ad21d for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 10 out of 10 (10 easyconfigs in this PR)
node3102.skitty.os - Linux centos linux 7.5.1804, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz, Python 2.7.5
See https://gist.github.com/9fdcaf19f5ab741435bced01849c65fb for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 10 out of 10 (10 easyconfigs in this PR)
node2613.swalot.os - Linux centos linux 7.5.1804, Intel(R) Xeon(R) CPU E5-2660 v3 @ 2.60GHz, Python 2.7.5
See https://gist.github.com/52fb9451e37d15813866b729e79a6cb8 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 10 out of 10 (10 easyconfigs in this PR)
node2082.delcatty.os - Linux centos linux 7.5.1804, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.7.5
See https://gist.github.com/557cb7929ae1fa0d967bf00284f20c39 for a full test report.

**Comment by boegel** [comment]
@migueldiascosta Can you try submitting a test report again? I made some changes based on your earlier (failing) test report...

**Comment by migueldiascosta** [comment]
Test report by @migueldiascosta
**FAILED**
Build succeeded for 7 out of 11 (10 easyconfigs in this PR)
grc-cluster1 - Linux centos 6.10, Intel(R) Xeon(R) CPU E5-2640 0 @ 2.50GHz, Python 2.7.14
See https://gist.github.com/cdffbac907af4373af66838e0e5ac39b for a full test report.

**Comment by boegel** [comment]
@migueldiascosta Is this a CentOS 6.x specific issue?

**Comment by migueldiascosta** [comment]
@boegel seems to be another case of too old glibc (e.g. https://stackoverflow.com/a/52777686)

**Comment by boegel** [comment]
Anyone else up for testing this? @verdurin maybe?

**Comment by verdurin** [comment]
Test report by @verdurin
**SUCCESS**
Build succeeded for 20 out of 20 (10 easyconfigs in this PR)
rescomp2 - Linux centos linux 7.3.1611, Intel(R) Xeon(R) Gold 6126 CPU @ 2.60GHz, Python 2.7.5
See https://gist.github.com/8d26cf48fff00131dc2f74e298e4ae6d for a full test report.

**Comment by verdurin** [comment]
Going in, thanks @boegel!

**Pull request merged**
