### PR TITLE
{tools}[intel/2018a] IPython v6.3.1 w/ Python 3.6.4

### PR DESCRIPTION
**Pull request by boegel**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by boegel** [comment]
Test report by @boegel
**FAILED**
Build succeeded for 2 out of 5 (3 easyconfigs in this PR)
node2501.golett.os - Linux centos linux 7.4.1708, Intel(R) Xeon(R) CPU E5-2680 v3 @ 2.50GHz, Python 2.7.5
See https://gist.github.com/28ab5093e5e89a78b472a3ccbac48346 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 3 out of 3 (3 easyconfigs in this PR)
node2501.golett.os - Linux centos linux 7.4.1708, Intel(R) Xeon(R) CPU E5-2680 v3 @ 2.50GHz, Python 2.7.5
See https://gist.github.com/24a3d89b578a202eca3f7fe6db2b5ad7 for a full test report.

**Comment by vanzod** [comment]
Test report by @vanzod
**FAILED**
Build succeeded for 2 out of 3 (3 easyconfigs in this PR)
cermis - Linux debian 9.4, Intel(R) Xeon(R) CPU           E5620  @ 2.40GHz, Python 2.7.13
See https://gist.github.com/03d649a7a472b97531b7b3c27d8e196a for a full test report.

**Comment by vanzod** [comment]
It looks like something does not like `OpenSSL 1.1.0f` in my test machine...

**Comment by migueldiascosta** [comment]
Test report by @migueldiascosta
**SUCCESS**
Build succeeded for 3 out of 3 (3 easyconfigs in this PR)
grc-cluster1 - Linux centos 6.9, Intel(R) Xeon(R) CPU E5-2640 0 @ 2.50GHz, Python 2.7.14
See https://gist.github.com/39d47ad9c36bb8658cf278ae36ac30f8 for a full test report.

**Comment by boegel** [comment]
@vanzod Maybe you should try re-building the Python 3.6.4 module, and then try this again? Did your `OpenSSL` get updated since you built the Python 3.6.4 module?

**Comment by jhein32** [comment]
Zeromq  4.2.5, is that a beta?  According to http://zeromq.org/intro:get-the-software 4.2.3 is the current stable release.

**Comment by verdurin** [comment]
Test report by @verdurin
**FAILED**
Build succeeded for 5 out of 6 (3 easyconfigs in this PR)
rescomp2 - Linux centos 6.8, Intel(R) Xeon(R) CPU E5-2650 v2 @ 2.60GHz, Python 2.7.11
See https://gist.github.com/f8e047405e35e75ff4441789714e273e for a full test report.

**Comment by boegel** [comment]
@jhein32 I don't think so, see https://github.com/zeromq/libzmq/releases. Maybe we should ask them why this is not updated on the ZeroMQ website?

**Comment by verdurin** [comment]
My test build failed because we currently can't reach https://files.pythonhosted.org/packages/source/j/Jinja2/

**Comment by vanzod** [comment]
@boegel It is possible that `OpenSSL` was updated on my system. Let me re-build `Python` and try again

**Comment by boegel** [comment]
@verdurin Hmm, I wonder if that's temporary, downloading via https://pypi.org/project/Jinja2/#files (which points to https://files.pythonhosted.org/packages/56/e6/332789f295cf22308386cf5bbd1f4e00ed11484299c5d7383378cf48ba47/Jinja2-2.10.tar.gz) works fine...

**Comment by boegel** [comment]
@verdurin Ah, you're missing the fix in https://github.com/easybuilders/easybuild-framework/pull/2471

**Comment by boegel** [comment]
@vanzod Can you check whether this is your problem? https://bugs.python.org/issue33174

**Comment by boegel** [comment]
@vanzod ping?

**Comment by verdurin** [comment]
Test report by @verdurin
**SUCCESS**
Build succeeded for 1 out of 1 (3 easyconfigs in this PR)
rescomp2 - Linux centos 6.8, Intel(R) Xeon(R) CPU E5-2650 v2 @ 2.60GHz, Python 2.7.11
See https://gist.github.com/dba38397a847b8b3c2df04de5a989cd1 for a full test report.

**Comment by verdurin** [comment]
Going in, thanks @boegel!

**Pull request merged**
