### PR TITLE
{system,tools}[GCCcore/8.3.0] OpenMPI v4.0.1, hwloc v2.0.3, numactl v2.0.12, ...

### PR DESCRIPTION
**Pull request by boegel**
(created using `eb --new-pr`)
requires ~#7963~ (Autotools)

### CODE REVIEW

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 8 out of 8 (7 easyconfigs in this PR)
node3110.skitty.os - Linux centos linux 7.6.1810, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz, Python 2.7.5
See https://gist.github.com/336203a934b09bbef303241932bd0106 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 7 out of 7 (7 easyconfigs in this PR)
node2092.delcatty.os - Linux centos linux 7.6.1810, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.7.5
See https://gist.github.com/2761bd93c09228425c648eb552671307 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 8 out of 8 (7 easyconfigs in this PR)
node2496.golett.os - Linux centos linux 7.6.1810, Intel(R) Xeon(R) CPU E5-2680 v3 @ 2.50GHz, Python 2.7.5
See https://gist.github.com/608c1b92d6fd12fbc1b827cf6dba9901 for a full test report.

**Comment by vanzod** [comment]
Re-trigger Travis after merging Autotools PR

**Comment by vanzod** [comment]
Test report by @vanzod
**SUCCESS**
Build succeeded for 7 out of 7 (7 easyconfigs in this PR)
cermis - Linux debian 9.8, Intel(R) Xeon(R) CPU           X5670  @ 2.93GHz, Python 2.7.13
See https://gist.github.com/718c2a872e94b25ffbbe6b644ba6c44f for a full test report.

**Comment by vanzod** [comment]
Going in, thanks @boegel!

**Pull request merged**
