### PR TITLE
{bio,data,geo}[foss/2023a] Squidpy v1.4.1, PyGEOS v0.14, zarr v2.17.1

### PR DESCRIPTION
**Pull request by pavelToman**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by pavelToman** [comment]
@boegelbot please test @ generoso

**Comment by pavelToman** [comment]
@boegelbot please test @ jsc-zen3

**Comment by verdurin** [comment]
Test report by @verdurin
**FAILED**
Build succeeded for 4 out of 8 (3 easyconfigs in total)
easybuild-c7.novalocal - Linux CentOS Linux 7.9.2009, x86_64, Intel Xeon Processor (Skylake, IBRS), Python 3.6.8
See https://gist.github.com/verdurin/4b5961e92fdcc34296ba96546b262e87 for a full test report.

**Comment by pavelToman** [comment]
Could be this Clang problem connected with a recent change in Z3? https://github.com/easybuilders/easybuild-easyconfigs/pull/20050

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 3 out of 3 (3 easyconfigs in total)
node3125.skitty.os - Linux RHEL 8.8, x86_64, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz, Python 3.6.8
See https://gist.github.com/boegel/f8dd372b9631b63d5df0d5fac5052a8f for a full test report.

**Comment by boegel** [comment]
@verdurin Can you open an issue on the problem with installing `Clang-16.0.6-GCCcore-12.3.0.eb`?

This seems to be the culprit:

<details>

```
pt: /dev/shm/Clang/16.0.6/GCCcore-12.3.0/llvm-project-16.0.6.src/llvm/lib/Support/StringMap.cpp:185: void llvm::StringMapImpl::RemoveKey(llvm::StringMapEntryBase*): Assertion `V == V2 && "Didn't find key?"' failed.
PLEASE submit a bug report to https://github.com/llvm/llvm-project/issues/ and include the crash backtrace.
Stack dump:
0.	Program arguments: /dev/shm/Clang/16.0.6/GCCcore-12.3.0/llvm.obj.1/bin/opt -O3 -openmp-opt-disable -attributor-enable=module /dev/shm/Clang/16.0.6/GCCcore-12.3.0/llvm.obj.1/runtimes/runtimes-bins/openmp/libomptarget/DeviceRTL/internalized_libomptarget-nvptx-sm_50.bc -o /dev/shm/Clang/16.0.6/GCCcore-12.3.0/llvm.obj.1/runtimes/runtimes-bins/openmp/libomptarget/DeviceRTL/libomptarget-nvptx-sm_50.bc
 #0 0x0000000002084dbe llvm::sys::PrintStackTrace(llvm::raw_ostream&, int) (/dev/shm/Clang/16.0.6/GCCcore-12.3.0/llvm.obj.1/bin/opt+0x2084dbe)
 #1 0x00000000020825eb SignalHandler(int) Signals.cpp:0:0
 #2 0x00007fdfeea45630 __restore_rt sigaction.c:0:0
 #3 0x00007fdfecbc1387 raise (/lib64/libc.so.6+0x36387)
 #4 0x00007fdfecbc2a78 abort (/lib64/libc.so.6+0x37a78)
 #5 0x00007fdfecbba1a6 __assert_fail_base (/lib64/libc.so.6+0x2f1a6)
 #6 0x00007fdfecbba252 (/lib64/libc.so.6+0x2f252)
 #7 0x0000000002014051 llvm::StringMapImpl::RemoveKey(llvm::StringMapEntryBase*) (/dev/shm/Clang/16.0.6/GCCcore-12.3.0/llvm.obj.1/bin/opt+0x2014051)
 #8 0x000000000174d6f3 llvm::Instruction::eraseFromParent() (/dev/shm/Clang/16.0.6/GCCcore-12.3.0/llvm.obj.1/bin/opt+0x174d6f3)
 #9 0x00000000019d65ce runIPSCCP(llvm::Module&, llvm::DataLayout const&, llvm::AnalysisManager<llvm::Function>*, std::function<llvm::TargetLibraryInfo const& (llvm::Function&)>, std::function<llvm::TargetTransformInfo& (llvm::Function&)>, std::function<llvm::AssumptionCache& (llvm::Function&)>, llvm::function_ref<llvm::AnalysisResultsForFn (llvm::Function&)>, bool) SCCP.cpp:0:0
#10 0x00000000019d7bcd llvm::IPSCCPPass::run(llvm::Module&, llvm::AnalysisManager<llvm::Module>&) (/dev/shm/Clang/16.0.6/GCCcore-12.3.0/llvm.obj.1/bin/opt+0x19d7bcd)
#11 0x000000000241b3ed llvm::detail::PassModel<llvm::Module, llvm::IPSCCPPass, llvm::PreservedAnalyses, llvm::AnalysisManager<llvm::Module>>::run(llvm::Module&, llvm::AnalysisManager<llvm::Module>&) (/dev/shm/Clang/16.0.6/GCCcore-12.3.0/llvm.obj.1/bin/opt+0x241b3ed)
#12 0x00000000017e3cb9 llvm::PassManager<llvm::Module, llvm::AnalysisManager<llvm::Module>>::run(llvm::Module&, llvm::AnalysisManager<llvm::Module>&) (/dev/shm/Clang/16.0.6/GCCcore-12.3.0/llvm.obj.1/bin/opt+0x17e3cb9)
#13 0x00000000008073ad llvm::runPassPipeline(llvm::StringRef, llvm::Module&, llvm::TargetMachine*, llvm::TargetLibraryInfoImpl*, llvm::ToolOutputFile*, llvm::ToolOutputFile*, llvm::ToolOutputFile*, llvm::StringRef, llvm::ArrayRef<llvm::PassPlugin>, llvm::opt_tool::OutputKind, llvm::opt_tool::VerifierKind, bool, bool, bool, bool, bool, bool) (/dev/shm/Clang/16.0.6/GCCcore-12.3.0/llvm.obj.1/bin/opt+0x8073ad)
#14 0x000000000075204a main (/dev/shm/Clang/16.0.6/GCCcore-12.3.0/llvm.obj.1/bin/opt+0x75204a)
#15 0x00007fdfecbad555 __libc_start_main (/lib64/libc.so.6+0x22555)
#16 0x00000000007f8ab6 _start (/dev/shm/Clang/16.0.6/GCCcore-12.3.0/llvm.obj.1/bin/opt+0x7f8ab6)
/bin/sh: line 1:  1236 Aborted                 /dev/shm/Clang/16.0.6/GCCcore-12.3.0/llvm.obj.1/bin/opt -O3 -openmp-opt-disable -attributor-enable=module /dev/shm/Clang/16.0.6/GCCcore-12.3.0/llvm.obj.1/runtimes/runtimes-bins/openmp/libomptarget/DeviceRTL/internalized_libomptarget-nvptx-sm_50.bc -o /dev/shm/Clang/16.0.6/GCCcore-12.3.0/llvm.obj.1/runtimes/runtimes-bins/openmp/libomptarget/DeviceRTL/libomptarget-nvptx-sm_50.bc
make[5]: *** [openmp/libomptarget/DeviceRTL/libomptarget-nvptx-sm_50.bc] Error 134
make[5]: Leaving directory `/dev/shm/Clang/16.0.6/GCCcore-12.3.0/llvm.obj.1/runtimes/runtimes-bins'
make[4]: *** [openmp/libomptarget/DeviceRTL/CMakeFiles/omptarget-nvptx-sm_50-bc.dir/all] Error 2
```

</details>

In any case, that problem shouldn't be blocking this PR imho...

**Comment by verdurin** [comment]
My build problem is referred to in https://github.com/easybuilders/easybuild-easyconfigs/issues/19941 including a fix from Miguel.

**Comment by verdurin** [comment]
Test report by @verdurin
**SUCCESS**
Build succeeded for 5 out of 5 (3 easyconfigs in total)
easybuild-c7.novalocal - Linux CentOS Linux 7.9.2009, x86_64, Intel Xeon Processor (Skylake, IBRS), Python 3.6.8
See https://gist.github.com/verdurin/e9286f32c756e50042c8cd3f3def4848 for a full test report.

**Comment by verdurin** [comment]
I built `Clang-16.0.6` using the fix referred to above, then the PR build succeeded.

**Review by verdurin — APPROVED** [review]
Looks fine.

**Comment by verdurin** [comment]
Going in, thanks @pavelToman!

**Comment by verdurin** [comment]
Going in, thanks @pavelToman!

**Comment by verdurin** [comment]
Going in, thanks @pavelToman!

**Pull request merged**
