### PR TITLE
{bio}[foss/2023a] OrthoFinder v2.5.5, BLAST+ v2.14.1, DIAMOND v2.1.8, FastME v2.1.6.3, MCL v22.282, MMseqs2 v14-7e284, cimfomfa v22.273 + enhanced sanity check for LMDB v0.9.31

### PR DESCRIPTION
**Pull request by boegel**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by boegel** [comment]
@boegelbot please test @ generoso

**Comment by boegel** [comment]
@boegelbot please test @ jsc-zen2

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 8 out of 8 (8 easyconfigs in total)
node3159.skitty.os - Linux RHEL 8.8, x86_64, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz (skylake_avx512), Python 3.6.8
See https://gist.github.com/boegel/c39277700e70abf9c86d7050529c79d0 for a full test report.

**Comment by boegel** [comment]
@boegelbot please test @ generoso
EB_ARGS="--sanity-check-only"

**Review by smoors — APPROVED** [review]
lgtm

**Comment by smoors** [comment]
@boegel merge conflict for LMDB

**Comment by boegel** [comment]
@smoors Merge conflict fixed, the easyconfig that got merged in #18997 didn't have the sanity check I was using, so I've retained that part...

**Comment by boegel** [comment]
@boegelbot please test @ jsc-zen2

**Comment by smoors** [comment]
@boegelbot: please test @ generoso

**Review by smoors — APPROVED** [review]
lgtm

**Comment by smoors** [comment]
Going in, thanks @boegel!

**Pull request merged**
