### PR TITLE
{bio}[foss/2022a] oxDNA v3.5.2 w/ Python 3.10.4

### PR DESCRIPTION
**Pull request by migueldiascosta**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by migueldiascosta** [comment]
@boegelbot please test @ jsc-zen2

**Comment by migueldiascosta** [comment]
@boegelbot please test @ generoso

**Comment by migueldiascosta** [comment]
ran https://github.com/lorenzo-rovigatti/oxDNA/tree/master/examples/CUDA_EXAMPLE on a (Volta) GPU node, seems to work fine

**Comment by smoors** [comment]
Test report by @smoors
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
node250.hydra.os - Linux CentOS Linux 7.9.2009, x86_64, Intel(R) Xeon(R) CPU E5-2650 v4 @ 2.20GHz (broadwell), 1 x NVIDIA Tesla P100-PCIE-16GB, 515.48.07, Python 3.6.8
See https://gist.github.com/smoors/94572628ff28459d1859969e775b20b4 for a full test report.

**Review by smoors — APPROVED** [review]
lgtm

**Comment by smoors** [comment]
Going in, thanks @migueldiascosta!

**Pull request merged**
