### PR TITLE
{bio}[foss/2018b] Bismark v0.20.1

### PR DESCRIPTION
**Pull request by haatveit**
Same easyconfig as in #7811 with foss toolchain instead of intel.

### CODE REVIEW

**Comment by verdurin** [comment]
Test report by @verdurin
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
rescomp2 - Linux centos linux 7.3.1611, Intel(R) Xeon(R) Gold 6126 CPU @ 2.60GHz, Python 2.7.5
See https://gist.github.com/39120dc896d45d7725110a5deac732bd for a full test report.

**Comment by verdurin** [comment]
Welcome @haatveit 
Could you submit a test build as well?

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
generoso - Linux centos linux 7.6.1810, Intel(R) Xeon(R) CPU E5-2660 v4 @ 2.00GHz, Python 3.6.8
See https://gist.github.com/5bbfe3fe9b5d4ba2016e186a2741ed48 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
node3133.skitty.os - Linux centos linux 7.6.1810, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz, Python 3.6.8
See https://gist.github.com/9f7c24395aa3b6d2a47427a38dad0019 for a full test report.

**Comment by boegel** [comment]
This is good to go imho.

@haatveit For future PRs, it would help if you can also submit a test report to show that this easyconfig worked for you, using `eb --from-pr 9204 --upload-test-report` (which is specific for this PR, of course).

See https://easybuild.readthedocs.io/en/latest/Integration_with_GitHub.html#uploading-test-reports-upload-test-report for more information.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
node2494.golett.os - Linux centos linux 7.6.1810, Intel(R) Xeon(R) CPU E5-2680 v3 @ 2.50GHz, Python 2.7.5
See https://gist.github.com/f3a517cf46f0c5051245f3c5ec4624e6 for a full test report.

**Comment by boegel** [comment]
Going in, thanks @haatveit!

**Pull request merged**
