### PR TITLE
{perf}[system/system] Advisor v2021.4.0

### PR DESCRIPTION
**Pull request by robert-mijakovic**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by robert-mijakovic** [comment]
Test report by @robert-mijakovic
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
mel0385 - Linux centos linux 8.4.2105, x86_64, AMD EPYC 7H12 64-Core Processor (zen2), Python 3.6.8
See https://gist.github.com/8ac5daa810bc930b7cc4d992441d2aae for a full test report.

**Comment by robert-mijakovic** [comment]
@boegelbot please test @ generoso

**Review by migueldiascosta — APPROVED** [review]
lgtm

**Comment by migueldiascosta** [comment]
Going in, thanks @robert-mijakovic!

**Pull request merged**
