### PR TITLE
{devel}[dummy/dummy] Gradle v4.5.1

### PR DESCRIPTION
**Pull request by froland**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by froland** [comment]
Test report by @froland
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
froland-l-xps15.froland.be - Linux fedora 27, Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz, Python 2.7.14
See https://gist.github.com/3ceb71e6477120824d6e6e9004bf5507 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
gligar01.gligar.os - Linux centos linux 7.4.1708, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.7.5
See https://gist.github.com/6546814d25207002a6786d2386c0290d for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
node2539.golett.os - Linux centos linux 7.4.1708, Intel(R) Xeon(R) CPU E5-2680 v3 @ 2.50GHz, Python 2.7.5
See https://gist.github.com/490904a4411b30158d4f551865e0ea0c for a full test report.

**Comment by boegel** [comment]
Going in, thanks @froland!

**Pull request merged**
