### PR TITLE
{bio}[foss/2018b,fosscuda/2018b] GROMACS v2018.3 with PLUMED 2.5b

### PR DESCRIPTION
**Pull request by akesandgren**
(created using `eb --new-pr`)
GROMACS 2018.3 with PLUMED 2.5b

### CODE REVIEW

**Comment by akesandgren** [comment]
Should upgrade this to PLUMED 2.5 instead of the 2.5b(eta)

**Comment by jhein32** [comment]
According to PLUMED documentation, v 2.5 supports Gromacs 2018.4 not 2018.3, which was used by the beta in this PR.  My proposal is to finalise things on the basis of PR #7478.   I would need some input/review to get that finished.

**Comment by akesandgren** [comment]
Apparently so yes. PLUMED 2.5.0 doesn't have a official patch for Gromacs 2018.3. So there's not much else to do on this PR, except probably adding a exception for PLUMED.

@boegel thoughts on this?

**Comment by boegel** [comment]
Agreed on going through with #7478 instead, so let's close this @akesandgren?

**Comment by akesandgren** [comment]
using #7478 instead, closing

**Pull request closed without merging**
