### PR TITLE
update Meson build dep to 0.55.1 for GLib, X11, Mesa & co to fix aggressive RPATH stripping

### LINKED ISSUE #11177: RPATH sanity check fails for GLib and X11
When installing GLib (`GLib-2.64.1-GCCcore-9.3.0.eb`) or X11 (`X11-20200222-GCCcore-9.3.0.eb`) with `eb --rpath`, the RPATH sanity check fails because the `readelf -d` output shows that there's no `RPATH` section in the resulting libraries:

```
One or more required libraries not found for /software/GLib/2.64.1-GCCcore-9.3.0/lib64/libgio-2.0.so.0.6400.1:    linux-vdso.so.1 (0x00007ffe1842e000)
    libglib-2.0.so.0 => not found
    libgobject-2.0.so.0 => not found
    libgmodule-2.0.so.0 => not found
    libz.so.1 => /usr/lib64/libz.so.1 (0x00007fd6dffa1000)
    libmount.so.1 => /usr/lib64/libmount.so.1 (0x00007fd6dff42000)
    libresolv.so.2 => /lib64/libresolv.so.2 (0x00007fd6dff26000)
    libpthread.so.0 => /lib64/libpthread.so.0 (0x00007fd6dff05000)
    libc.so.6 => /lib64/libc.so.6 (0x00007fd6dfd48000)
    libblkid.so.1 => //usr/lib64/libblkid.so.1 (0x00007fd6dfcf7000)
    /lib64/ld-linux-x86-64.so.2 (0x00007fd6e0190000)

No '(RPATH)' found in 'readelf -d' output for /software/GLib/2.64.1-GCCcore-9.3.0/lib64/libgio-2.0.so.0.6400.1:
Dynamic section at offset 0x1c6c38 contains 36 entries:
  Tag        Type                         Name/Value
 0x0000000000000003 (PLTGOT)             0x1c7fe8
 0x0000000000000002 (PLTRELSZ)           21912 (bytes)
 0x0000000000000017 (JMPREL)             0x38480
 0x0000000000000014 (PLTREL)             RELA
 0x0000000000000007 (RELA)               0x2f750
 0x0000000000000008 (RELASZ)             36144 (bytes)
 0x0000000000000009 (RELAENT)            24 (bytes)
 0x000000006ffffff9 (RELACOUNT)          1474
 0x0000000000000006 (SYMTAB)             0x1c8
 0x000000000000000b (SYMENT)             24 (bytes)
 0x0000000000000005 (STRTAB)             0x117a8
 0x000000000000000a (STRSZ)              82119 (bytes)
 0x000000006ffffef5 (GNU_HASH)           0x25870
 0x0000000000000004 (HASH)               0x29070
 0x0000000000000001 (NEEDED)             Shared library: [libglib-2.0.so.0]
 0x0000000000000001 (NEEDED)             Shared library: [libgobject-2.0.so.0]
 0x0000000000000001 (NEEDED)             Shared library: [libgmodule-2.0.so.0]
 0x0000000000000001 (NEEDED)             Shared library: [libz.so.1]
 0x0000000000000001 (NEEDED)             Shared library: [libmount.so.1]
 0x0000000000000001 (NEEDED)             Shared library: [libresolv.so.2]
 0x0000000000000001 (NEEDED)             Shared library: [libpthread.so.0]
 0x0000000000000001 (NEEDED)             Shared library: [libc.so.6]
 0x000000000000000e (SONAME)             Library soname: [libgio-2.0.so.0]
 0x000000000000000c (INIT)               0x3da18
 0x000000000000000d (FINI)               0x134a80
 0x000000000000001a (FINI_ARRAY)         0x1c7c28
 0x000000000000001c (FINI_ARRAYSZ)       8 (bytes)
 0x0000000000000019 (INIT_ARRAY)         0x1c7c30
 0x000000000000001b (INIT_ARRAYSZ)       8 (bytes)
 0x000000006ffffffb (FLAGS_1)            Flags: NODELETE
 0x000000006ffffff0 (VERSYM)             0x2dedc
 0x000000006ffffffc (VERDEF)             0x2f604
 0x000000006ffffffd (VERDEFNUM)          1
 0x000000006ffffffe (VERNEED)            0x2f620
 0x000000006fffffff (VERNEEDNUM)         5
 0x0000000000000000 (NULL)               0x0
```

The culprit here is the `Meson` build tool that is used for both `GLib` and specific `X11` components (`libxkbcommon`), which was aggressively stripping out the `RPATH` section on installed binaries and libraries, no matter how those paths were injected (Meson injects build directory paths to facilitate testing during the build phase, and was blindly removing all RPATH paths rather than just the ones it added itself).

This was fixed in Meson 0.55.0 (see https://github.com/mesonbuild/meson/issues/2567, https://github.com/mesonbuild/meson/issues/4027, https://github.com/mesonbuild/meson/pull/7103, ), so updating to a newer version of `Meson` fixes the issue (I verified that).

### PR DESCRIPTION
**Pull request by boegel**
(created using `eb --new-pr`)

fixes #11177

### CODE REVIEW

**Comment by boegel** [comment]
@boegelbot please test @ generoso
EB_ARGS="--rpath --installpath /tmp/pr11178"

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 11 out of 11 (11 easyconfigs in this PR)
node3404.kirlia.os - Linux centos linux 7.8.2003, x86_64, Intel(R) Xeon(R) Gold 6240 CPU @ 2.60GHz (cascadelake), Python 2.7.5
See https://gist.github.com/5ff2bb3fc44f9a3fc2f65a43fe7d991a for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 12 out of 12 (11 easyconfigs in this PR)
node2606.swalot.os - Linux centos linux 7.8.2003, x86_64, Intel(R) Xeon(R) CPU E5-2660 v3 @ 2.60GHz (haswell), Python 2.7.5
See https://gist.github.com/0ca89a0bcb419db2cd5e47afcc161350 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 11 out of 11 (11 easyconfigs in this PR)
node3171.skitty.os - Linux centos linux 7.8.2003, x86_64, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz (skylake_avx512), Python 3.6.8
See https://gist.github.com/ef0a0f81992d2553484df5d6e21e9c6b for a full test report.

**Comment by lexming** [comment]
Test report by @lexming
**SUCCESS**
Build succeeded for 12 out of 12 (11 easyconfigs in this PR)
node368.hydra.os - Linux centos linux 7.7.1908, x86_64, Intel(R) Xeon(R) Gold 6148 CPU @ 2.40GHz, Python 2.7.5
See https://gist.github.com/50dff4ced98b51e84bb50f5650184e56 for a full test report.

**Comment by lexming** [comment]
Test report by @lexming
**SUCCESS**
Build succeeded for 12 out of 12 (11 easyconfigs in this PR)
node116.hydra.os - Linux centos linux 7.7.1908, x86_64, Intel(R) Xeon(R) CPU E5-2680 v2 @ 2.80GHz, Python 2.7.5
See https://gist.github.com/e47720e897068ccdd23b45e393df90de for a full test report.

**Review by lexming — APPROVED** [review]
LGTM

**Comment by lexming** [comment]
Going in, thanks @boegel !

**Pull request merged**
