### PR TITLE
add patch to fix vectorization bug in scipy 1.11.1 also to SciPy-bundle 2023.07 w/ iimkl/2023a

### PR DESCRIPTION
**Pull request by boegel**
(created using `eb --new-pr`)

This was missing from #21693...

### CODE REVIEW

**Comment by boegel** [comment]
@boegelbot please test @ generoso

**Comment by boegel** [comment]
@boegelbot please test @ jsc-zen3

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
node3103.skitty.os - Linux RHEL 9.4, x86_64, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz (skylake_avx512), Python 3.9.18
See https://gist.github.com/boegel/00ec7498a5434feb1a9c73feaa85b60a for a full test report.

**Review by laraPPr — APPROVED** [review]
lgtm

**Comment by laraPPr** [comment]
Going in, thanks @boegel!

**Pull request merged**
