### PR TITLE
{ai}[GCCcore/11.3.0] GKlib-METIS v5.1.1

### PR DESCRIPTION
**Pull request by sassy-crick**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by Micket** [comment]
@boegelbot please test @ jsc-zen3

**Comment by Micket** [comment]
Test report by @Micket
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
vera-skylake-build - Linux Rocky Linux 8.9, x86_64, Intel Xeon Processor (Skylake, IBRS, no TSX), Python 3.6.8
See https://gist.github.com/Micket/1431e971542f41028c776df0c4c3ccba for a full test report.

**Review by Micket — CHANGES_REQUESTED** [review]
please add sanity_check_commands

**Comment by zao** [comment]
Test report by @zao
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
eb-mix.zao.se - Linux Ubuntu 24.04 (Noble Numbat), x86_64, AMD Ryzen 9 3900X 12-Core Processor (zen2), Python 3.12.2
See https://gist.github.com/zao/1b7b22f7ac9dbe47e70406691e24481a for a full test report.

**Review by Micket — APPROVED** [review]
lgtm

**Comment by Micket** [comment]
@boegelbot please test @ jsc-zen3

**Comment by Micket** [comment]
Test report by @Micket
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
vera-skylake-build - Linux Rocky Linux 8.9, x86_64, Intel Xeon Processor (Skylake, IBRS, no TSX), Python 3.6.8
See https://gist.github.com/Micket/8150ab5d5d967f633e32298b05514c38 for a full test report.

**Comment by Micket** [comment]
Going in, thanks @sassy-crick!

**Pull request merged**
