### PR TITLE
{math,phys}[foss/2023a] deal.II v9.5.2, p4est v2.8.6

### PR DESCRIPTION
**Pull request by maxim-masterov**
(created using `eb --new-pr`)

- [x] Depends on PETSc from https://github.com/easybuilders/easybuild-easyconfigs/pull/19686

### CODE REVIEW

**Comment by migueldiascosta** [comment]
@boegelbot please test @ generoso

**Review by migueldiascosta — DISMISSED** [review]
lgtm

**Comment by migueldiascosta** [comment]
@maxim-masterov just noticed https://github.com/cburstedde/p4est/releases from two weeks ago, does it make sense to use p4est 2.8.6 instead?

**Comment by maxim-masterov** [comment]
@migueldiascosta Thanks for pointing to the new release. I've updated the easyconfig files.

**Comment by migueldiascosta** [comment]
@boegelbot please test @ jsc-zen3

**Review by migueldiascosta — APPROVED** [review]
lgtm

**Comment by migueldiascosta** [comment]
Going in, thanks @maxim-masterov!

**Pull request merged**
