### PR TITLE
{lang} R: Add dependency cairo to existing R EasyConfigs with the extension Cairo  #3386

### PR DESCRIPTION
**Pull request by haribert**

### CODE REVIEW

**Comment by boegel** [comment]
@haribert The older R easyconfigs indeed implicitly require that X11 is installed in the OS.

Rather than removing `Cairo`, we should list `X11` as an OS dependency?

**Comment by haribert** [comment]
Implementation of my comment in issue #3386:

- Add `cairo` as `dependencies` in the existing EasyConfigs with the `Cairo` extension (`libX11` is a dependency of cairo). Do not add X11 as osdependencies.

**Comment by haribert** [comment]
I will take care of this next Wednesday.

**Comment by migueldiascosta** [comment]
is this still relevant?

**Comment by migueldiascosta** [comment]
@haribert, this PR is being closed for the following reason(s): no activity for > 6 months.
Please don't hesitate to reopen this PR or add a comment if you feel this contribution is still relevant.
For more information on our policy w.r.t. closing PRs, see https://easybuild.readthedocs.io/en/latest/Contributing.html#why-a-pull-request-may-be-closed-by-a-maintainer

**Pull request closed without merging**
