### PR TITLE
{bio}[gcccuda/2019b] Beast v2.6.3, beagle-lib v3.1.2, MrBayes v3.2.7

### PR DESCRIPTION
**Pull request by tstrempel**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by tstrempel** [comment]
Is there anything left to do for me?

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 3 out of 3 (3 easyconfigs in total)
node3302.joltik.os - Linux centos linux 7.9.2009, x86_64, Intel(R) Xeon(R) Gold 6242 CPU @ 2.80GHz (cascadelake), Python 3.6.8
See https://gist.github.com/1799b12fdc3566f58e323197fc2ab792 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 3 out of 3 (3 easyconfigs in total)
node2618.swalot.os - Linux centos linux 7.9.2009, x86_64, Intel(R) Xeon(R) CPU E5-2660 v3 @ 2.60GHz (haswell), Python 3.6.8
See https://gist.github.com/93892b011e3cf2006856eff9278d2ace for a full test report.

**Comment by boegel** [comment]
@tstrempel My apologies for not picking this up earlier, looks like this got snowed under...

I made some minor additional tweaks, should be good to go now!

**Comment by boegel** [comment]
@boegelbot please test @ generoso

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 3 out of 3 (3 easyconfigs in total)
node3600.doduo.os - Linux RHEL 8.2, x86_64, AMD EPYC 7552 48-Core Processor (zen2), Python 3.6.8
See https://gist.github.com/a1bcac5c9512282e06a34c61ae8dac06 for a full test report.

**Comment by boegel** [comment]
Going in, thanks @tstrempel!

**Pull request merged**
