### PR TITLE
{data}[intel/2018b] scikit-learn v0.20.0

### PR DESCRIPTION
**Pull request by schiotz**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by schiotz** [comment]
A comment:

I copied the foss version.  It contains two lines that are not present in the easyconfigs for previous versions:

```
download_dep_fail = True
use_pip = True
```

I am not 100% sure why they have been added, but I assume there is a reason and that keeping them is correct.

**Comment by schiotz** [comment]
Test report by @schiotz
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
thul.fysik.dtu.dk - Linux centos linux 7.5.1804, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.7.5
See https://gist.github.com/d73b1f54c09f7765b89df5ecc86932f1 for a full test report.

**Comment by schiotz** [comment]
Test report by @schiotz
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
fjorm.fysik.dtu.dk - Linux centos linux 7.5.1804, Intel(R) Xeon(R) CPU           X5570  @ 2.93GHz, Python 2.7.5
See https://gist.github.com/29982553be2397c7c347bcf35006d534 for a full test report.

**Comment by boegel** [comment]
@schiotz `download_dep_fail` enables a check to ensure that no additional Python packages are being downloaded from PyPI during the installation, to ensure that the easyconfig can be installed offline and that the installation is fully reproducible (since it forces you to list all required extensions in the easyconfig file or include them as a dependency).

`use_pip` instructs the `PythonPackage` easyblock to use `pip install` rather than `setup.py install`

We want to enable both by default in EasyBuild 4.0, so we're trying to consistently enable those already in new easyconfigs (someday I'll get around to making the tests trip over not having them set).

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 3 out of 3 (1 easyconfigs in this PR)
node2412.golett.os - Linux centos linux 7.5.1804, Intel(R) Xeon(R) CPU E5-2680 v3 @ 2.50GHz, Python 2.7.5
See https://gist.github.com/c83b1be5b39fea0a5b737038ad29df46 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
gligar02.gligar.os - Linux centos linux 7.5.1804, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.7.5
See https://gist.github.com/f9009541a232fde1088fe4ed8c55f569 for a full test report.

**Comment by boegel** [comment]
Going in, thanks @schiotz!

**Pull request merged**
