### PR TITLE
{data}[gompi/2020a,iimpi/2020a] netCDF v4.7.3, netCDF-C++4 v4.3.1, netCDF-Fortran v4.5.2

### PR DESCRIPTION
**Pull request by ocaisa**
(created using `eb --new-pr`)

Still using the HDF5 1.10 APIs until support for 1.12 is added to `netCDF-c`

### CODE REVIEW

**Comment by ocaisa** [comment]
Test report by @ocaisa
**FAILED**
Build succeeded for 0 out of 6 (6 easyconfigs in this PR)
generoso - Linux centos linux 7.6.1810, Intel(R) Xeon(R) CPU E5-2660 v4 @ 2.00GHz, Python 3.6.8
See https://gist.github.com/59c13c56a84cdeb7e01dedffc8d0355e for a full test report.

**Comment by ocaisa** [comment]
Test report by @ocaisa
**FAILED**
Build succeeded for 4 out of 6 (6 easyconfigs in this PR)
generoso - Linux centos linux 7.6.1810, Intel(R) Xeon(R) CPU E5-2660 v4 @ 2.00GHz, Python 3.6.8
See https://gist.github.com/9d0390fed5686962ebf71351a0519289 for a full test report.

**Comment by ocaisa** [comment]
Test report by @ocaisa
**SUCCESS**
Build succeeded for 6 out of 6 (6 easyconfigs in this PR)
generoso - Linux centos linux 7.6.1810, Intel(R) Xeon(R) CPU E5-2660 v4 @ 2.00GHz, Python 3.6.8
See https://gist.github.com/42a1d154ea2285d20fe80183afff0521 for a full test report.

**Comment by lexming** [comment]
Test report by @lexming
**SUCCESS**
Build succeeded for 8 out of 8 (6 easyconfigs in this PR)
login2.cerberus.os - Linux centos linux 7.7.1908, Intel(R) Xeon(R) Gold 6126 CPU @ 2.60GHz, Python 2.7.5
See https://gist.github.com/90121f5f58ff9b3d164429ee8519b1e4 for a full test report.

**Comment by zao** [comment]
Test report by @zao
**SUCCESS**
Build succeeded for 10 out of 10 (6 easyconfigs in this PR)
freja - Linux ubuntu 18.04, Intel(R) Core(TM) i7-8700K CPU @ 3.70GHz, Python 2.7.17
See https://gist.github.com/b8b35ceb7a21f4dbedc148af0925a230 for a full test report.

**Comment by akesandgren** [comment]
Test report by @akesandgren
**FAILED**
Build succeeded for 4 out of 7 (6 easyconfigs in this PR)
skalman.hpc2n.umu.se - Linux ubuntu 18.04, Intel(R) Core(TM) i7-8565U CPU @ 1.80GHz, Python 2.7.17
See https://gist.github.com/ab996b590a8d190daf92e779c4218191 for a full test report.

**Comment by ocaisa** [comment]
@akesandgren Your failing tests are related to licencing for the compiler, can you rerun them?

**Comment by akesandgren** [comment]
Yeah, my flexlm port forwarding ssh lost the connection over to work. (Sitting at home...)
Retrying...

**Comment by akesandgren** [comment]
Test report by @akesandgren
**SUCCESS**
Build succeeded for 6 out of 6 (6 easyconfigs in this PR)
skalman.hpc2n.umu.se - Linux ubuntu 18.04, Intel(R) Core(TM) i7-8565U CPU @ 1.80GHz, Python 2.7.17
See https://gist.github.com/646e16c4ac31064deeef57de892d418f for a full test report.

**Comment by akesandgren** [comment]
Test report by @akesandgren
**SUCCESS**
Build succeeded for 7 out of 7 (6 easyconfigs in this PR)
b-an04.hpc2n.umu.se - Linux ubuntu 16.04, Intel(R) Xeon(R) CPU E5-2690 v4 @ 2.60GHz, Python 2.7.12
See https://gist.github.com/f5fbf8645df315b2bc922fa00e0a9faf for a full test report.

**Comment by lexming** [comment]
Going in, thanks @ocaisa !

**Pull request merged**
