### PR TITLE
{lang}[foss/2018a] Mono v5.18.1.0

### PR DESCRIPTION
**Pull request by Helios07**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by vanzod** [comment]
Re-trigger Travis after fix

**Comment by boegel** [comment]
(close/re-open to let Travis pick up latest `develop` for framework)

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
node3106.skitty.os - Linux centos linux 7.6.1810, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz, Python 2.7.5
See https://gist.github.com/9bbed53754656a8619c07478a120f310 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
node2055.delcatty.os - Linux centos linux 7.6.1810, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.7.5
See https://gist.github.com/640fd247f27424d27172f29d86df6b56 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
node2403.golett.os - Linux centos linux 7.6.1810, Intel(R) Xeon(R) CPU E5-2680 v3 @ 2.50GHz, Python 2.7.5
See https://gist.github.com/23aafc415fc2aa0a7ed4b9a69b80df98 for a full test report.

**Comment by boegel** [comment]
Going in, thanks @Helios07!

**Pull request merged**
