### PR TITLE
Update HTSlib

### PR DESCRIPTION
**Pull request by fizwit**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by fizwit** [comment]
if this looks good I will follow with pr's for bcftools and samtools

**Review by Micket — APPROVED** [review]
lgtm

**Comment by Micket** [comment]
Test report by @Micket
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
vera-c1 - Linux centos linux 7.9.2009, x86_64, Intel Xeon Processor (Skylake), Python 2.7.5
See https://gist.github.com/ded680d5dd4c21e2d318b685ca2717c4 for a full test report.

**Comment by Micket** [comment]
Going in, thanks @fizwit!

**Pull request merged**
