### PR TITLE
{lib}[fosscuda/2017b] TensorFlow v1.8.0

### PR DESCRIPTION
**Pull request by vanzod**
Depends on:
#7594 (Python) 
#7604 (wheel)
#7480 (cuDNN)

### CODE REVIEW

**Comment by akesandgren** [comment]
@vanzod Throw in a build report?

**Comment by vanzod** [comment]
@akesandgren It is coming. Takes a while...

**Comment by akesandgren** [comment]
Kicking travis

**Comment by akesandgren** [comment]
Travis kicked

**Comment by vanzod** [comment]
Test report by @vanzod
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in this PR)
cermis - Linux debian 9.7, Intel(R) Xeon(R) CPU           X5670  @ 2.93GHz, Python 2.7.13
See https://gist.github.com/900668478ef1186dd65f2dd3fe55466e for a full test report.

**Comment by akesandgren** [comment]
Going in, thanks @vanzod!

**Pull request merged**
