### PR TITLE
{lib}[foss/2021b] dm-reverb v0.7.0 w/ Python 3.9.6

### PR DESCRIPTION
**Pull request by lexming**
(created using `eb --new-pr`)

- [x] #14990
- [x] #15099
- [x] #15102 
- [x] #15103

### CODE REVIEW

**Comment by lexming** [comment]
@smoors the update for dm-reverb is ready :slightly_smiling_face:

**Comment by lexming** [comment]
@boegelbot: please test @ generoso

**Comment by smoors** [comment]
@boegelbot please test @ jsc-zen2

**Comment by lexming** [comment]
@boegelbot please test @ jsc-zen2

**Review by smoors — APPROVED** [review]
lgtm

**Comment by smoors** [comment]
Going in, thanks @lexming!

**Pull request merged**
