### PR TITLE
{math}[foss/2022a] SUNDIALS v6.3.0

### PR DESCRIPTION
**Pull request by sassy-crick**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by sassy-crick** [comment]
By the looks of it only the GitHub page is being used for download, so I have removed the 2nd checksum. If I have missed something, just let me know please. Thanks

**Comment by sassy-crick** [comment]
Added an EC for the `foss-2021b` toolchain as well.

**Comment by migueldiascosta** [comment]
@boegelbot please test @ generoso

**Comment by migueldiascosta** [comment]
@boegelbot please test @ jsc-zen2

**Review by migueldiascosta — APPROVED** [review]
lgtm

**Comment by migueldiascosta** [comment]
Going in, thanks @sassy-crick!

**Pull request merged**
