### PR TITLE
set minimal OpenSSL version to 1.1.1 for OpenSSL v1.1 wrapper

### PR DESCRIPTION
**Pull request by lexming**
(created using `eb --new-pr`)

Depends on https://github.com/easybuilders/easybuild-easyblocks/pull/2475

### CODE REVIEW

**Comment by lexming** [comment]
Test report by @lexming
Using easyblocks from PR(s) https://github.com/easybuilders/easybuild-easyblocks/pull/2475
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
login2.cerberus.os - Linux centos linux 7.9.2009, x86_64, Intel(R) Xeon(R) Gold 6126 CPU @ 2.60GHz, Python 2.7.5
See https://gist.github.com/b891dcb2c18e7b4a354e98b6b3a1cc36 for a full test report.

**Comment by lexming** [comment]
Test report by @lexming
Using easyblocks from PR(s) https://github.com/easybuilders/easybuild-easyblocks/pull/2475
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
login3.phoenix.os - Linux centos linux 7.9.2009, x86_64, Intel(R) Xeon(R) Gold 6148 CPU @ 2.40GHz, Python 2.7.5
See https://gist.github.com/629306cd4e14f1455617e1e518700010 for a full test report.

**Comment by lexming** [comment]
Test report by @lexming
Using easyblocks from PR(s) https://github.com/easybuilders/easybuild-easyblocks/pull/2475
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
login3.phoenix.os - Linux centos linux 7.9.2009, x86_64, Intel(R) Xeon(R) Gold 6148 CPU @ 2.40GHz, Python 2.7.5
See https://gist.github.com/a6cbebc6fffdbe57da3631f13419879d for a full test report.

**Comment by lexming** [comment]
Test report by @lexming
Using easyblocks from PR(s) https://github.com/easybuilders/easybuild-easyblocks/pull/2475
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
login3.phoenix.os - Linux centos linux 7.9.2009, x86_64, Intel(R) Xeon(R) Gold 6148 CPU @ 2.40GHz, Python 2.7.5
See https://gist.github.com/550059139eb5b67db9aaef777e4bb1ae for a full test report.

**Review by Micket — APPROVED** [review]
lgtm

**Comment by Micket** [comment]
I tried to sync this pr with develop, with I'm getting a `gitdb.exc.BadObject: BadObject: b'004bee0bbc34fc2144f1bdcd3c54c8d55bce7044'`

**Comment by lexming** [comment]
@Micket synced manually :+1:

**Comment by Micket** [comment]
Test report by @Micket
Using easyblocks from PR(s) https://github.com/easybuilders/easybuild-easyblocks/pull/2475
**SUCCESS**
Build succeeded for 0 out of 0 (1 easyconfigs in total)
alvis-c1 - Linux centos linux 7.9.2009, x86_64, Intel Xeon Processor (Skylake), Python 3.6.8
See https://gist.github.com/15cced55cfac6d96f10904feba09378f for a full test report.

**Comment by Micket** [comment]
Test report by @Micket
Using easyblocks from PR(s) https://github.com/easybuilders/easybuild-easyblocks/pull/2475
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
alvis-c1 - Linux centos linux 7.9.2009, x86_64, Intel Xeon Processor (Skylake), Python 3.6.8
See https://gist.github.com/f4bfe9d1317e1d28ce14f59e22b4cfac for a full test report.

**Comment by Micket** [comment]
Going in, thanks @lexming!

**Pull request merged**
