### PR TITLE
{math}[intel/2021b] ArviZ v0.11.4 w/ Python 3.9.6

### PR DESCRIPTION
**Pull request by ItIsI-Orient**
(created using `eb --new-pr`)
* https://github.com/easybuilders/easybuild-easyconfigs/pull/14809
* https://github.com/easybuilders/easybuild-easyconfigs/pull/14890

### CODE REVIEW

**Comment by ItIsI-Orient** [comment]
Merge first: https://github.com/easybuilders/easybuild-easyconfigs/pull/14809

**Comment by ItIsI-Orient** [comment]
Test report by @ItIsI-Orient
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
node3202.victini.os - Linux UNKNOWN UNKNOWN, x86_64, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz, Python 3.6.8
See https://gist.github.com/43a2d3cb2998bce6e77912a3fdc98c01 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
node3526.doduo.os - Linux UNKNOWN UNKNOWN, x86_64, AMD EPYC 7552 48-Core Processor (zen2), Python 3.6.8
See https://gist.github.com/3d3aa06372ae8cb091ad4f121232f70d for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
node3164.skitty.os - Linux UNKNOWN UNKNOWN, x86_64, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz (skylake_avx512), Python 3.6.8
See https://gist.github.com/5e7e58b3bcb7a4fc00b6d1c4632b0129 for a full test report.

**Comment by boegel** [comment]
@boegelbot please test @ jsc-zen2

**Review by boegel — APPROVED** [review]
lgtm

**Comment by boegel** [comment]
Going in, thanks @ItIsI-Orient!

**Comment by pavelToman** [comment]
@boegelbot please test @ generoso

**Pull request merged**
