### PR TITLE
{lib}[foss/2021a] pygmo v2.18.0, pagmo v2.18.0 w/ Python 3.9.5

### PR DESCRIPTION
**Pull request by Louwrensth**

### CODE REVIEW

**Comment by migueldiascosta** [comment]
@boegelbot please test @ generoso

**Comment by migueldiascosta** [comment]
@boegelbot please test @ generoso

**Review by migueldiascosta — APPROVED** [review]
lgtm

**Comment by migueldiascosta** [comment]
Going in, thanks @Louwrensth!

**Comment by boegel** [comment]
Test report by @boegel
**FAILED**
Build succeeded for 1 out of 2 (2 easyconfigs in total)
node3101.skitty.os - Linux RHEL 8.4, x86_64, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz (skylake_avx512), Python 3.6.8
See https://gist.github.com/d3a917b89e15362ef9b0b3ec92cd61d1 for a full test report.

**Pull request merged**
