### PR TITLE
{chem}[foss/2023a] Cantera v3.0.0, SUNDIALS v6.6.0, HighFive v2.7.1, fmt v10.1.0, pygraphviz v1.11, ruamel.yaml v0.17.32

### PR DESCRIPTION
**Pull request by boegel**
(created using `eb --new-pr`)
requires:
* #18803

### CODE REVIEW

**Comment by boegel** [comment]
@boegelbot please test @ generoso

**Comment by boegel** [comment]
@boegelbot please test @ generoso

**Comment by SebastianAchilles** [comment]
@boegelbot please test @ jsc-zen2

**Comment by SebastianAchilles** [comment]
Test report by @sebastianachilles
**SUCCESS**
Build succeeded for 6 out of 6 (6 easyconfigs in total)
zen2-rockylinux-88 - Linux Rocky Linux 8.8, x86_64, AMD EPYC 7452 32-Core Processor (zen2), Python 3.6.8
See https://gist.github.com/SebastianAchilles/aa1cdfcad622732795d864bfe2b07226 for a full test report.

**Review by SebastianAchilles — APPROVED** [review]
lgtm

**Pull request merged**
