### PR TITLE
{vis}[intel/2022a] matplotlib v3.5.2 w/ Python 3.10.4

### PR DESCRIPTION
**Pull request by schiotz**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by schiotz** [comment]
This is identical to the already existing .eb file for foss/2022a (a part from changing the toolchain name, of course).

**Comment by boegel** [comment]
@boegelbot please test @ generoso

**Review by boegel — APPROVED** [review]
lgtm

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
node3144.skitty.os - Linux RHEL 8.4, x86_64, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz (skylake_avx512), Python 3.6.8
See https://gist.github.com/cac19613b60d21c35748374312b449eb for a full test report.

**Comment by boegel** [comment]
Going in, thanks @schiotz!

**Pull request merged**
