### PR TITLE
{bio}[foss/2021a] dRep v3.0.0 w/ Python 3.9.5

### PR DESCRIPTION
**Pull request by bedroge**
(created using `eb --new-pr`)

Depends on:

- [x] #14473
- [x] #14474
- [x] #14475
- [x] #14476
- [x] #14478
- [x] #14511 
- [x] #14510
- [x] https://github.com/easybuilders/easybuild-easyblocks/pull/2630

### CODE REVIEW

**Comment by bedroge** [comment]
@boegelbot please test @ generoso

**Comment by bedroge** [comment]
Test report by @bedroge
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
bob-Latitude-5300 - Linux Ubuntu 20.04, x86_64, Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz, Python 3.8.10
See https://gist.github.com/2f40dac3dea4b23b40b4d957ca6b753d for a full test report.

**Comment by bedroge** [comment]
Test report by @bedroge
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
pg-interactive.hpc.rug.nl - Linux centos linux 7.9.2009, x86_64, Intel(R) Xeon(R) CPU E5-2680 v3 @ 2.50GHz, Python 3.6.8
See https://gist.github.com/108c351c02f5c6a3acfe0cd63aa98fc9 for a full test report.

**Review by branfosj — APPROVED** [review]
lgtm

**Comment by branfosj** [comment]
Test report by @branfosj
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
bear-pg0211u08b.bear.cluster - Linux RHEL 8.3, x86_64, Intel(R) Xeon(R) Gold 6248 CPU @ 2.50GHz (cascadelake), Python 3.6.8
See https://gist.github.com/5d6904ba8fd4ea4fdf0c53ac8d6dee32 for a full test report.

**Comment by branfosj** [comment]
Going in, thanks @bedroge!

**Pull request merged**
