### PR TITLE
{tools}[GCCcore/11.3.0] jupyterlmod v3.0.0, jupyterlab-lmod v1.0.2 w/ Python 3.10.4

### PR DESCRIPTION
**Pull request by lexming**
(created using `eb --new-pr`)

Depends on:
* [x] #16561 
* [x] #16529

### CODE REVIEW

**Comment by lexming** [comment]
@boegelbot: please test @ generoso

**Comment by casparvl** [comment]
`jupyterlab-lmod` doesn't build for me, and I don't get any proper logs to find out why...

```
== 2023-02-10 17:10:29,688 build_log.py:171 ERROR EasyBuild crashed with an error (at easybuild/base/exceptions.py:126 in __init__): cmd " mkdir -p /home/casparl/.local/easybuild/RHEL8/2022/software/jupyterlab-lmod/1.0.2-GCCcore-11.3.0/share/jupyter/lab && JUPYTERLAB_DIR=/home/casparl/.local/easybuild/RHEL8/2022/software/jupyterlab-lmod/1.0.2-GCCcore-11.3.0/share/jupyter/lab jupyter labextension install jupyterlab-lmod-1.0.2.tgz " exited with exit code 1 and output:
Building jupyterlab assets (production, minimized)
An error occurred.
RuntimeError: JupyterLab failed to build
See the log file for details:  /scratch-shared/casparl/eb-kp55xg0r/jupyterlab-debug-tt0xbht5.log
```
But the ` /scratch-shared/casparl/eb-kp55xg0r/jupyterlab-debug-tt0xbht5.log` logfile is empty...

**Comment by casparvl** [comment]
I managed to get a more extensive error output by dumping the environment script (`--dump-env-script`), going into the builddir, and running 
```
JUPYTERLAB_DIR=/home/casparl/.local/easybuild/RHEL8/2022/software/jupyterlab-lmod/1.0.2-GCCcore-11.3.0/share/jupyter/lab jupyter labextension install --debug jupyterlab-lmod-1.0.2.tgz
```
manually. The `--debug` flag prints debugging output:

```
Yarn configuration loaded.
Building jupyterlab assets (production, minimized)
> node /home/casparl/.local/easybuild/RHEL8/2022/software/JupyterLab/3.5.0-GCCcore-11.3.0/lib/python3.10/site-packages/jupyterlab/staging/yarn.js install --non-interactive
/yarn install v1.21.1
[1/5] Validating package.json...
[2/5] Resolving packages...
success Already up-to-date.
Done in 0.42s.

> node /home/casparl/.local/easybuild/RHEL8/2022/software/JupyterLab/3.5.0-GCCcore-11.3.0/lib/python3.10/site-packages/jupyterlab/staging/yarn.js yarn-deduplicate -s fewer --fail
|yarn run v1.21.1
$ /gpfs/home4/casparl/.local/easybuild/RHEL8/2022/software/jupyterlab-lmod/1.0.2-GCCcore-11.3.0/share/jupyter/lab/staging/node_modules/.bin/yarn-deduplicate -s fewer --fail
Done in 0.27s.

> node /home/casparl/.local/easybuild/RHEL8/2022/software/JupyterLab/3.5.0-GCCcore-11.3.0/lib/python3.10/site-packages/jupyterlab/staging/yarn.js run build:prod:minimize
\yarn run v1.21.1
$ webpack --config webpack.prod.minimize.config.js
[webpack-cli] SyntaxError: Invalid regular expression: /(\p{Uppercase_Letter}+|\p{Lowercase_Letter}|\d)(\p{Uppercase_Letter}+)/: Invalid property name
    at pathToArgumentName (/gpfs/home4/casparl/.local/easybuild/RHEL8/2022/software/jupyterlab-lmod/1.0.2-GCCcore-11.3.0/share/jupyter/lab/staging/node_modules/webpack/lib/cli.js:66:4)
    at addFlag (/gpfs/home4/casparl/.local/easybuild/RHEL8/2022/software/jupyterlab-lmod/1.0.2-GCCcore-11.3.0/share/jupyter/lab/staging/node_modules/webpack/lib/cli.js:170:16)
    at traverse (/gpfs/home4/casparl/.local/easybuild/RHEL8/2022/software/jupyterlab-lmod/1.0.2-GCCcore-11.3.0/share/jupyter/lab/staging/node_modules/webpack/lib/cli.js:243:21)
    at traverse (/gpfs/home4/casparl/.local/easybuild/RHEL8/2022/software/jupyterlab-lmod/1.0.2-GCCcore-11.3.0/share/jupyter/lab/staging/node_modules/webpack/lib/cli.js:299:23)
    at traverse (/gpfs/home4/casparl/.local/easybuild/RHEL8/2022/software/jupyterlab-lmod/1.0.2-GCCcore-11.3.0/share/jupyter/lab/staging/node_modules/webpack/lib/cli.js:248:24)
    at Object.getArguments (/gpfs/home4/casparl/.local/easybuild/RHEL8/2022/software/jupyterlab-lmod/1.0.2-GCCcore-11.3.0/share/jupyter/lab/staging/node_modules/webpack/lib/cli.js:308:2)
    at WebpackCLI.getBuiltInOptions (/gpfs/home4/casparl/.local/easybuild/RHEL8/2022/software/jupyterlab-lmod/1.0.2-GCCcore-11.3.0/share/jupyter/lab/staging/node_modules/webpack-cli/lib/webpack-cli.j
s:681:47)
    at loadCommandByName (/gpfs/home4/casparl/.local/easybuild/RHEL8/2022/software/jupyterlab-lmod/1.0.2-GCCcore-11.3.0/share/jupyter/lab/staging/node_modules/webpack-cli/lib/webpack-cli.js:838:38)
    at Command.<anonymous> (/gpfs/home4/casparl/.local/easybuild/RHEL8/2022/software/jupyterlab-lmod/1.0.2-GCCcore-11.3.0/share/jupyter/lab/staging/node_modules/webpack-cli/lib/webpack-cli.js:1462:23
)
    at Command.listener [as _actionHandler] (/gpfs/home4/casparl/.local/easybuild/RHEL8/2022/software/jupyterlab-lmod/1.0.2-GCCcore-11.3.0/share/jupyter/lab/staging/node_modules/webpack-cli/node_modu
les/commander/index.js:922:31)
error Command failed with exit code 2.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

JupyterLab failed to build
Traceback (most recent call last):

  File "/home/casparl/.local/easybuild/RHEL8/2022/software/JupyterLab/3.5.0-GCCcore-11.3.0/lib/python3.10/site-packages/jupyterlab/debuglog.py", line 47, in debug_logging
    yield

  File "/home/casparl/.local/easybuild/RHEL8/2022/software/JupyterLab/3.5.0-GCCcore-11.3.0/lib/python3.10/site-packages/jupyterlab/labextensions.py", line 153, in start
    build(

  File "/home/casparl/.local/easybuild/RHEL8/2022/software/JupyterLab/3.5.0-GCCcore-11.3.0/lib/python3.10/site-packages/jupyterlab/commands.py", line 506, in build
    return handler.build(

  File "/home/casparl/.local/easybuild/RHEL8/2022/software/JupyterLab/3.5.0-GCCcore-11.3.0/lib/python3.10/site-packages/jupyterlab/commands.py", line 722, in build
    raise RuntimeError(msg)

RuntimeError: JupyterLab failed to build

An error occurred.
```
No clue yet what's wrong. I might try reinstalling `nodejs`, as I think you may have used one of your previous PR's for that - and I'm not sure if we have the same installation for that now (we might have had our own EasyConfig). It doesn't immediately look like a `nodejs` problem though...

**Comment by casparvl** [comment]
Ok, reinstalling `nodejs` helped. Not sure what was wrong in our original installation, but I don't care enough to find out. Anyway, I'll upload a test report for this PR :)

**Comment by casparvl** [comment]
Test report by @casparvl
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in total)
int4 - Linux Rocky Linux 8.7, x86_64, AMD EPYC 7F72 24-Core Processor, Python 3.6.8
See https://gist.github.com/6b575c97253da40359d5b97942797341 for a full test report.

**Review by casparvl — APPROVED** [review]
Looks good to me!

**Comment by casparvl** [comment]
@boegelbot please test @ jsc-zen2

**Comment by casparvl** [comment]
Going in, thanks @lexming!

**Comment by lexming** [comment]
@casparvl your initial error is related to issue https://github.com/jupyterlab/jupyterlab/issues/10487, which we fixed in nodejs #16529 . That's why a rebuild of nodejs solved it.

**Pull request merged**
