### PR TITLE
{bio}[GCCcore/11.2.0] MaxQuant v2.0.3.0

### PR DESCRIPTION
**Pull request by jfgrimm**
(created using `eb --new-pr`)

requires:
- [x] #14823

### CODE REVIEW

**Comment by migueldiascosta** [comment]
@jfgrimm since the sources are not freely available, can you submit a test report?

**Comment by jfgrimm** [comment]
Test report by @jfgrimm
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
node084.pri.viking.alces.network - Linux UNKNOWN UNKNOWN, x86_64, Intel(R) Xeon(R) Gold 6138 CPU @ 2.00GHz (skylake_avx512), Python 3.6.8
See https://gist.github.com/37f8c6e36d1d87edb79ea84f5eb72056 for a full test report.

**Comment by jfgrimm** [comment]
> @jfgrimm since the sources are not freely available, can you submit a test report?

@migueldiascosta done. Although it needs a form to complete, MaxQuant is freeware and their license agreement isn't particularly restrictive

**Review by migueldiascosta — APPROVED** [review]
lgtm

**Comment by migueldiascosta** [comment]
Going in, thanks @jfgrimm!

**Pull request merged**
