### PR TITLE
add Python build dependency to 1.9.x Doxygen

### PR DESCRIPTION
**Pull request by branfosj**
(created using `eb --new-pr`)

Before this it uses the Python from my EB venv:
```
- Found PythonInterp: /rds/projects/2017/branfosj-rse/easybuild/venv-dev-EL8/bin/python (found version "3.6.8")
```

### CODE REVIEW

**Comment by branfosj** [comment]
Test report by @branfosj
**SUCCESS**
Build succeeded for 6 out of 6 (6 easyconfigs in total)
bear-pg0105u03a - Linux RHEL 8.6, x86_64, Intel(R) Xeon(R) Platinum 8360Y CPU @ 2.40GHz (icelake), Python 3.6.8
See https://gist.github.com/branfosj/6d02ddb71145f100e30bb8f9b2835367 for a full test report.

**Comment by bedroge** [comment]
@boegelbot please test @ generoso

**Comment by bedroge** [comment]
@boegelbot please test @ generoso

**Comment by bedroge** [comment]
@boegelbot please test @ jsc-zen3

**Comment by bedroge** [comment]
Going in, thanks @branfosj!

**Pull request merged**
