### PR TITLE
{lib,tools}[GCCcore/11.3.0,foss/2022a] maturin v1.3.2, timm v0.9.7 w/ CUDA 11.7.0

### PR DESCRIPTION
**Pull request by WilleBell**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by smoors** [comment]
@boegelbot: please test @ generoso

**Comment by smoors** [comment]
@boegelbot: please test @ generoso

**Comment by smoors** [comment]
@boegelbot please test @ jsc-zen3

**Comment by smoors** [comment]
the failed PyTorch build seems to be this issue
https://github.com/facebookincubator/gloo/issues/345

**Comment by WilleBell** [comment]
Test report by @WilleBell
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in total)
node400.hydra.os - Linux Rocky Linux 8.8, x86_64, AMD EPYC 7282 16-Core Processor, Python 3.6.8
See https://gist.github.com/WilleBell/38f9387ed6050fe68fd020ba84f8ade2 for a full test report.

**Review by smoors — APPROVED** [review]
lgtm

**Comment by smoors** [comment]
Going in, thanks @WilleBell!

**Pull request merged**
