### PR TITLE
{lang}[system/system] Anaconda3 version 2024.02-1

### PR DESCRIPTION
**Pull request by jhein32**
New easyconfig for Anaconda3 v 2024.02.   It seems support for Power has been dropped by the Anaconda folk.

### CODE REVIEW

**Review by Micket — APPROVED** [review]
lgtm

**Comment by Micket** [comment]
Test report by @Micket
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
vera-skylake-build - Linux Rocky Linux 8.9, x86_64, Intel Xeon Processor (Skylake, IBRS, no TSX), Python 3.6.8
See https://gist.github.com/Micket/d129e02cc42377767f3fdbdc33de77a9 for a full test report.

**Comment by Micket** [comment]
Going in, thanks @jhein32!

**Comment by jhein32** [comment]
@Micket Thanks for reviewing.

**Pull request merged**
