### PR TITLE
{bio}[GCC/10.2.0] MetaEuk v4

### PR DESCRIPTION
**Pull request by boegel**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by boegel** [comment]
@boegelbot please test @ generoso

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
node3544.doduo.os - Linux RHEL 8.2, x86_64, AMD EPYC 7552 48-Core Processor (zen2), Python 3.6.8
See https://gist.github.com/a44edcf846e6481ce0dc3f46cd340efa for a full test report.

**Comment by branfosj** [comment]
The MetaEuk install is hiding away a MMseqs install - https://github.com/soedinglab/metaeuk/tree/master/lib

**Comment by boegel** [comment]
> The MetaEuk install is hiding away a MMseqs install - https://github.com/soedinglab/metaeuk/tree/master/lib

That looks like it difficult to avoid? Is it worth pulling that out? Maybe it's customized, or the code is required for building `MetaEuk`?

**Comment by branfosj** [comment]
> > The MetaEuk install is hiding away a MMseqs install - https://github.com/soedinglab/metaeuk/tree/master/lib
> 
> @branfosj That looks like it difficult to avoid? Is it worth pulling that out? Maybe it's customized, or the code is required for building `MetaEuk`?

On reflection I am happy to accept it. We are getting a committed copy of that code and not having it just pull down the latest, and so potentially changing, version of the MMseqs code into the repository. So, while it annoy me that they are doing it like this, we can go forward here.

**Comment by branfosj** [comment]
Test report by @branfosj
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
bear-pg0211u03a.bear.cluster - Linux centos linux 7.8.2003, x86_64, Intel(R) Xeon(R) Gold 6248 CPU @ 2.50GHz (cascadelake), Python 3.6.8
See https://gist.github.com/c2031c491e2941af698921ff9b9e7ae5 for a full test report.

**Review by branfosj — APPROVED** [review]
lgtm

**Comment by branfosj** [comment]
Going in, thanks @boegel!

**Pull request merged**
