### PR TITLE
{lang}[foss/2020b] R v4.0.4

### PR DESCRIPTION
**Pull request by DirectorSloan**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by jfgrimm** [comment]
Test report by @jfgrimm
**SUCCESS**
Build succeeded for 0 out of 0 (1 easyconfigs in total)
node025.pri.viking.alces.network - Linux CentOS Linux 7.9.2009, x86_64, Intel(R) Xeon(R) Gold 6138 CPU @ 2.00GHz (skylake_avx512), Python 3.6.8
See https://gist.github.com/55c71c5c3141309487e4f2e8fb0a5937 for a full test report.

**Comment by jfgrimm** [comment]
Test report by @jfgrimm
**FAILED**
Build succeeded for 0 out of 1 (1 easyconfigs in total)
node025.pri.viking.alces.network - Linux CentOS Linux 7.9.2009, x86_64, Intel(R) Xeon(R) Gold 6138 CPU @ 2.00GHz (skylake_avx512), Python 3.6.8
See https://gist.github.com/f79c9ba3a89af8c7e5c8c2a8f55f610d for a full test report.

**Comment by verdurin** [comment]
@boegelbot please test @ generoso
EB_ARGS=" --skip --rebuild "

**Comment by verdurin** [comment]
Test report by @verdurin
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
easybuild-c7.novalocal - Linux CentOS Linux 7.9.2009, x86_64, Intel Xeon Processor (Skylake, IBRS), Python 3.6.8
See https://gist.github.com/a9935d13da71705725448ce92fd071ab for a full test report.

**Comment by DirectorSloan** [comment]
Dear easybuilders contribution team. What can I do to support the merge of this easyconfig? best regards

**Comment by DirectorSloan** [comment]
Sorry to may annoy. Is there a date when it's merged into `develop`? What does the *update* label and **4.x** label mean?

**Comment by verdurin** [comment]
Hi @DirectorSloan sorry for the delay on this one.
`update` just means that it's updating an easyconfig that already exists, as opposed to `new` which would be a completely new easyconfig.
The milestone is for progress tracking and release management. It means we expect to merge it soon - at the point of merging, the milestone will be changed e.g. to `4.7.2` for the next release.

I'll try to look at it again this week, though I do wonder whether you wouldn't be better served with one of the newer `R` releases?

**Comment by boegel** [comment]
closing this since `foss/2020b` is deprecated, see https://docs.easybuild.io/policies/toolchains

**Pull request closed without merging**
