### PR TITLE
{bio}[foss/2020b] svist4get v1.3.1 w/ Python 3.8.6 

### PR DESCRIPTION
**Pull request by sassy-crick**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by sassy-crick** [comment]
It looks like it is picking up `freetype` from my build environment which I only spotted when I build inside my container. Adding `    ('freetype', '2.10.3'),` did not fix that.It appears it does not pick up the EasyBuild environment variables and I am currently hunting for ideas. Any suggestions welcome.

**Comment by smoors** [comment]
@boegelbot: please test @ generoso

**Review by smoors — APPROVED** [review]
lgtm

**Comment by smoors** [comment]
Going in, thanks @sassy-crick!

**Pull request merged**
