### PR TITLE
{bio}[foss/2023a] trusTEr v0.1.1-20241025, subset-bam v1.1.0, bamtofastq v1.4.1, ...

### PR DESCRIPTION
**Pull request by pavelToman**
(created using `eb --new-pr`)
resolves https://github.com/vscentrum/vsc-software-stack/issues/453

### CODE REVIEW

**Comment by pavelToman** [comment]
@boegelbot please test @ generoso

**Comment by pavelToman** [comment]
There is a `CellRanger` in dependencies of `trusTEr` which needs to download sources manually - seems bot does not have this files. and can not do tests.

**Comment by pavelToman** [comment]
Test report by @pavelToman
**FAILED**
Build succeeded for 2 out of 4 (4 easyconfigs in total)
node4203.shinx.os - Linux RHEL 9.4, x86_64, AMD EPYC 9654 96-Core Processor, Python 3.11.3
See https://gist.github.com/pavelToman/7cc09720397334a7e794fd0cb7d78bc1 for a full test report.

**Comment by pavelToman** [comment]
Test report by @pavelToman
**SUCCESS**
Build succeeded for 4 out of 4 (4 easyconfigs in total)
node4009.donphan.os - Linux RHEL 8.8, x86_64, Intel(R) Xeon(R) Gold 6240 CPU @ 2.60GHz, 1 x NVIDIA NVIDIA A2, 545.23.08, Python 3.6.8
See https://gist.github.com/pavelToman/62faea282b2df18039f0fee80c961979 for a full test report.

**Comment by pavelToman** [comment]
Test report by @pavelToman
**FAILED**
Build succeeded for 3 out of 4 (4 easyconfigs in total)
node4214.shinx.os - Linux RHEL 9.4, x86_64, AMD EPYC 9654 96-Core Processor, Python 3.9.18
See https://gist.github.com/pavelToman/cacae8895500a694b276aceb4a61c2d6 for a full test report.

**Comment by pavelToman** [comment]
Test report by @pavelToman
**SUCCESS**
Build succeeded for 5 out of 5 (4 easyconfigs in total)
node4214.shinx.os - Linux RHEL 9.4, x86_64, AMD EPYC 9654 96-Core Processor, Python 3.9.18
See https://gist.github.com/pavelToman/d1301d4338c8f8f19236c750e4081978 for a full test report.

**Comment by pavelToman** [comment]
> @pavelToman why the change to `Binary` for `subset-bam`?

For more recent GCC version (since 12.x)  it seems it can not be compiled (even when I use the same version of Rust with 12.x toolchain).  I used precompiled binary for linux then. The `subset-bam` seems is no longer maintained to provide compatibility with new compilers. Especially there is old dependency pined - `rust-htslib == 0.20.0` which can not be compiled.

**Comment by verdurin** [comment]
Test report by @verdurin
**SUCCESS**
Build succeeded for 8 out of 8 (4 easyconfigs in total)
easybuild-el8.cloud.in.bmrc.ox.ac.uk - Linux Rocky Linux 8.10, x86_64, Intel Xeon Processor (Skylake, IBRS), Python 3.6.8
See https://gist.github.com/verdurin/9bdbe83f25146bb7022b55def577e842 for a full test report.

**Review by verdurin — APPROVED** [review]
Looks fine.

**Comment by verdurin** [comment]
Going in, thanks @pavelToman!

**Pull request merged**
