### PR TITLE
{vis}[GCCcore/10.2.0] PyQt5 v5.15.1 w/ Python 3.8.6

### PR DESCRIPTION
**Pull request by Micket**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by Micket** [comment]
depends on #11555 

@boegel Trying to build this I get some problems;
```
== 2020-10-22 13:01:40,626 build_log.py:169 ERROR EasyBuild crashed with an error (at easybuild/base/exceptions.py:124 in __init__): cmd "export PATH=/apps/Vera/software/Compiler/GCCcore/10.2.0/PyQt5/5.15.1-Python-3.8.6/bin:$PATH && export PYTHONPATH=/apps/Vera/software/Compiler/GCCcore/10.2.0/PyQt5/5.15.1-Python-3.8.6/lib/python3.8/site-packages:$PYTHONPATH &&  /apps/Vera/software/Compiler/GCCcore/10.2.0/Python/3.8.6/bin/python configure.py --verbose --destdir=/apps/Vera/software/Compiler/GCCcore/10.2.0/PyQt5/5.15.1-Python-3.8.6/lib/python3.8/site-packages/PyQt5 --apidir=/apps/Vera/software/Compiler/GCCcore/10.2.0/PyQt5/5.15.1-Python-3.8.6/qsci --pyqt-sipdir=/local/EB/build/PyQt5/5.15.1/GCCcore-10.2.0-Python-3.8.6/PyQt5-5.15.1/sip --no-stubs --no-dist-info" exited with exit code 1 and output:
Error: Unable to create the C++ code.
Installing sip.h in
/local/EB/build/PyQt5/5.15.1/GCCcore-10.2.0-Python-3.8.6/PyQtWebEngine-5.15.1/include...
sip-module --sip-h --target-dir /local/EB/build/PyQt5/5.15.1/GCCcore-10.2.0-Python-3.8.6/PyQtWebEngine-5.15.1/include PyQt5.sip
Configuring PyQtWebEngine 5.15.1...
The PyQtWebEngine .sip files will be installed in
/local/EB/build/PyQt5/5.15.1/GCCcore-10.2.0-Python-3.8.6/PyQt5-5.15.1/sip.
PyQtWebEngine will be installed in
/apps/Vera/software/Compiler/GCCcore/10.2.0/PyQt5/5.15.1-Python-3.8.6/lib/python3.8/site-packages/PyQt5.
PyQt 5.15.1 is being used.
Qt 5.15.1 is being used.
sip 5.4.0 is being used.
The sip executable is
/apps/Vera/software/Compiler/GCCcore/10.2.0/PyQt5/5.15.1-Python-3.8.6/bin/sip5.
PyQtWebEngine is being built with 'protected' redefined as 'public'.
The QScintilla API file will be installed in
/apps/Vera/software/Compiler/GCCcore/10.2.0/PyQt5/5.15.1-Python-3.8.6/qsci/api/python.
Generating the C++ source for the QtWebEngine module...
/apps/Vera/software/Compiler/GCCcore/10.2.0/PyQt5/5.15.1-Python-3.8.6/bin/sip5 -I /local/EB/build/PyQt5/5.15.1/GCCcore-10.2.0-Python-3.8.6/PyQtWebEngine-5.15.1/sip -I /local/EB/build/PyQt5/5.15.1/GCCcore-10.2.0-Python-3.8.6/PyQt5-5.15.1/sip -n PyQt5.sip -t Qt_5_15_0 -t WS_X11 -x PyQt_SSL -B Qt_6_0_0 -t QtWebEngine_5_15_0 -a QtWebEngine.api -P -o -c /local/EB/build/PyQt5/5.15.1/GCCcore-10.2.0-Python-3.8.6/PyQtWebEngine-5.15.1/QtWebEngine /local/EB/build/PyQt5/5.15.1/GCCcore-10.2.0-Python-3.8.6/PyQtWebEngine-5.15.1/sip/QtWebEngine/QtWebEnginemod.sip
sip5: QWebEngineClientCertificateStore is undefined
```

**Comment by boegel** [comment]
Test report by @boegel
**FAILED**
Build succeeded for 0 out of 2 (2 easyconfigs in total)
node3401.kirlia.os - Linux centos linux 7.8.2003, x86_64, Intel(R) Xeon(R) Gold 6240 CPU @ 2.60GHz (cascadelake), Python 2.7.5
See https://gist.github.com/d67b92153cca5cf7e53e3c79655493fc for a full test report.

**Comment by zao** [comment]
Test report by @zao
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
freja - Linux Ubuntu 20.04, x86_64, Intel(R) Core(TM) i7-8700K CPU @ 3.70GHz (skylake), Python 3.8.5
See https://gist.github.com/d808004c326a63279a2c6de7cb79efd2 for a full test report.

**Comment by Micket** [comment]
@zao Share the build logs (perhaps both for Qt5 and PyQt5?) so that I can try to spot where it goes wrong for us?

**Comment by Micket** [comment]
Test report by @Micket
**FAILED**
Build succeeded for 1 out of 2 (1 easyconfigs in this PR)
hebbe-c1 - Linux centos linux 7.8.2003, x86_64, Intel Core Processor (Haswell, no TSX), Python 2.7.5
See https://gist.github.com/1ba889d7b1c3543d5901b4615193ba13 for a full test report.

**Comment by branfosj** [comment]
This builds for me on centos 8, but fails on centos 7. I found https://wiki.qt.io/Qt_5.15.0_Known_Issues#OpenSSL whish says that Qt 5.15.0 requires OpenSSL 1.1.1. Based on this I am trying a build of Qt 5.15.1 where I have added OpenSSL 1.1.1h as a dep. Then I'll try building PyQt5.

**Comment by Micket** [comment]
The errors doesn't really hint towards that, but, worth a shot. I'll try with the openssl11 package under CentOS7 to see if that helps.

**Comment by zao** [comment]
@Micket Packed for size, Qt one is a juicy 120 MiB:
https://zao.se/~zao/eb/easybuild-PyQt5-5.15.1-20201022.183709.log.zst
https://zao.se/~zao/eb/easybuild-Qt5-5.15.1-20201022.173203.log.zst

**Comment by branfosj** [comment]
Test report by @branfosj
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
bear-pg0206u16a.bear.cluster - Linux centos linux 8.2.2004, x86_64, Intel(R) Xeon(R) Gold 6248 CPU @ 2.50GHz (cascadelake), Python 3.6.8
See https://gist.github.com/7f4b66d02b076c33d6490ce0103df707 for a full test report.

**Comment by branfosj** [comment]
Yes, sorry - there is an unexplained jump in my logic. I compared the logs of the two builds and noticed the OpenSSL difference.

centos 8:
```
Checking for OpenSSL Headers... yes
  OpenSSL ................................ yes
    Qt directly linked to OpenSSL ........ no
  OpenSSL 1.1 ............................ yes
```

centos 7
```
Checking for OpenSSL Headers... no
  OpenSSL ................................ no
    Qt directly linked to OpenSSL ........ no
  OpenSSL 1.1 ............................ no
```

I also searched for `QWebEngineClientCertificateStore` inside the Qt5 `include` directory and that got me to `${EBROOTQT5}/include/QtWebEngineCore/qwebengineclientcertificatestore.h` which shows that the class definition for `QWebEngineClientCertificateStore` is behind a `#if QT_CONFIG(ssl)`.

**Comment by branfosj** [comment]
Test report by @branfosj
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
bear-pg0206u03a.bear.cluster - Linux centos linux 7.8.2003, x86_64, Intel(R) Xeon(R) Gold 6248 CPU @ 2.50GHz (cascadelake), Python 3.6.8
See https://gist.github.com/72cd105475e53e4a89d0e43b5e46400c for a full test report.

**Comment by Micket** [comment]
So, installing openssl11 rpm wasn't a good option. Still need to add custom link flags to Qt, so, problably just as well to add it via EB.. 

I also looked into the possibility of just turning off this one component, but, looks like it's the entire Qt Network module in that case (unless one goes into patching stuff, probably).

I kind of wanted to avoid this outcome since there are some painful conflicts that occur when you start linking different applications that use. I went down that rabbit hole trying to get some r-plugin linked with a newer openssl on CentOS6, and it just ended with having to rebuilt everything and att the OpenSSL dep everywhere.  I wonder if we can make Qt5 statically link it and leave it out as a dep.

**Comment by smoors** [comment]
>  I wonder if we can make Qt5 statically link it and leave it out as a dep.

Isn't that a security issue?

**Comment by Micket** [comment]
Test report by @Micket
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
vera-c1 - Linux centos linux 7.8.2003, x86_64, Intel Xeon Processor (Skylake), Python 2.7.5
See https://gist.github.com/34f6f2cb5bef9d4a45277a9b14ca91ae for a full test report.

**Review by boegel — APPROVED** [review]
lgtm

**Comment by boegel** [comment]
@boegelbot please test @ generoso

**Comment by verdurin** [comment]
Test report by @verdurin
**SUCCESS**
Build succeeded for 8 out of 8 (1 easyconfigs in total)
nuc.lan - Linux Fedora 32, x86_64, Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz, Python 3.8.6
See https://gist.github.com/ac0331845e34129741e5c239f23c5dfe for a full test report.

**Comment by migueldiascosta** [comment]
Test report by @migueldiascosta
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
sms - Linux centos linux 7.6.1810, x86_64, AMD EPYC 7601 32-Core Processor (zen), Python 2.7.5
See https://gist.github.com/3245f1a18f6d4326045f0b3e7c25677a for a full test report.

**Comment by verdurin** [comment]
Going in, thanks @Micket!

**Pull request merged**
