### PR TITLE
{chem}[intel/2017b] TAMkin 1.4.2

### PR DESCRIPTION
**Pull request by tovrstra**
This easyconfig was originally part of #5317, but was taken out because it was delaying the merge of several other easyconfigs

### CODE REVIEW

**Comment by boegel** [comment]
@tovrstra Does this actually work for you? The tests seem to hang when I try it...

**Comment by tovrstra** [comment]
Oops. It does not! I know how to fix it but ran into another problem on delcatty. (See e-mail to hpc.)

**Comment by tovrstra** [comment]
Forget about the e-mail. I've found what was going wrong. My mistake.

**Comment by tovrstra** [comment]
Fixed! (I just tested it on delcatty.)

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
node2612.swalot.os - Linux centos linux 7.4.1708, Intel(R) Xeon(R) CPU E5-2660 v3 @ 2.60GHz, Python 2.7.5
See https://gist.github.com/068c11546aedd78b8849b5cfc9330771 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
node2080.delcatty.os - Linux centos linux 7.4.1708, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.7.5
See https://gist.github.com/b8c7b648b47c1071488531e8b290bf6e for a full test report.

**Comment by boegel** [comment]
Going in, thanks @tovrstra!

**Comment by boegel** [comment]
Going in, thanks @tovrstra!

**Pull request merged**
