### PR TITLE
{mpi,perf,toolchain}[iimpi/2024.06,intel-compilers/2024.2.0,system/system] impi v2021.13.0, iimpi v2024.06, OSU-Micro-Benchmarks v7.4

### PR DESCRIPTION
**Pull request by bartoldeman**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by bartoldeman** [comment]
@boegelbot please test @ jsc-zen3

**Comment by bartoldeman** [comment]
@boegelbot please test @ generoso

**Comment by bartoldeman** [comment]
Test report by @bartoldeman
**SUCCESS**
Build succeeded for 3 out of 3 (3 easyconfigs in total)
login1.int.archimedes.c3.ca - Linux AlmaLinux 9.4 (Seafoam Ocelot), x86_64, Intel Xeon Processor (Skylake, IBRS) (cascadelake), Python 3.11.4
See https://gist.github.com/bartoldeman/c55054f9532a48a75f910b20f5d671e9 for a full test report.

**Comment by bartoldeman** [comment]
easybuilders/easybuild-easyblocks#3375 is helpful but not necessary here, it just removes some redundant paths from the module

**Comment by bartoldeman** [comment]
@boegelbot please test @ generoso
EB_ARGS="--include-easyblocks-from-pr 3375"

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 4 out of 4 (3 easyconfigs in total)
node3158.skitty.os - Linux RHEL 8.8, x86_64, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz, Python 3.6.8
See https://gist.github.com/boegel/18ad6bb5c018717f131572aa45322cfb for a full test report.

**Review by boegel — APPROVED** [review]
lgtm

**Comment by boegel** [comment]
Going in, thanks @bartoldeman!

**Pull request merged**
