### PR TITLE
update intel/2020a to iccifort & imkl 2020 update 1 + impi 2019 update 7

### PR DESCRIPTION
**Pull request by boegel**

### CODE REVIEW

**Comment by lexming** [comment]
Test report by @lexming
**FAILED**
Build succeeded for 0 out of 8 (8 easyconfigs in this PR)
node318.hydra.os - Linux centos linux 7.7.1908, Intel(R) Xeon(R) Gold 6148 CPU @ 2.40GHz, Python 2.7.5
See https://gist.github.com/7220a39c16decb383cf5f55259c1e24f for a full test report.

**Comment by boegel** [comment]
@lexming You need a license ;)

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 9 out of 9 (9 easyconfigs in this PR)
generoso - Linux centos linux 7.6.1810, Intel(R) Xeon(R) CPU E5-2660 v4 @ 2.00GHz, Python 3.6.8
See https://gist.github.com/0173ae790ae3e2d5290d9bf49dbf81e3 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 9 out of 9 (9 easyconfigs in this PR)
node2627.swalot.os - Linux centos linux 7.7.1908, Intel(R) Xeon(R) CPU E5-2660 v3 @ 2.60GHz, Python 2.7.5
See https://gist.github.com/420dae7a43e84203937e0bf872c1c901 for a full test report.

**Comment by zao** [comment]
Test report by @zao
**FAILED**
Build succeeded for 0 out of 8 (8 easyconfigs in this PR)
freja - Linux ubuntu 18.04, Intel(R) Core(TM) i7-8700K CPU @ 3.70GHz, Python 2.7.17
See https://gist.github.com/ed7199ba417fbe0f0089bc1d93291952 for a full test report.

**Comment by akesandgren** [comment]
Test report by @akesandgren
**FAILED**
Build succeeded for 7 out of 8 (8 easyconfigs in this PR)
b-an03.hpc2n.umu.se - Linux ubuntu 16.04, Intel(R) Xeon(R) CPU E5-2690 v4 @ 2.60GHz, Python 2.7.12
See https://gist.github.com/d741053a5d8526109278ede5d13f72b9 for a full test report.

**Comment by lexming** [comment]
Test report by @lexming
**FAILED**
Build succeeded for 7 out of 8 (8 easyconfigs in this PR)
node318.hydra.os - Linux centos linux 7.7.1908, Intel(R) Xeon(R) Gold 6148 CPU @ 2.40GHz, Python 2.7.5
See https://gist.github.com/102643b250827070d555dca6fb157e22 for a full test report.

**Comment by akesandgren** [comment]
One have to expliticly list intel-2020a.eb iimpi-2020a.eb GSL-2.6-iccifort-2020.1.217.eb GEOS-3.8.1-iccifort-2020.1.217-Python-3.8.2.eb libxc-4.3.4-iccifort-2020.1.217.eb -fru

**Comment by akesandgren** [comment]
Test report by @akesandgren
**FAILED**
Build succeeded for 7 out of 8 (8 easyconfigs in this PR)
b-an03.hpc2n.umu.se - Linux ubuntu 16.04, Intel(R) Xeon(R) CPU E5-2690 v4 @ 2.60GHz, Python 2.7.12
See https://gist.github.com/ee6233bcb8f3fd5901e0842237df583c for a full test report.

**Comment by akesandgren** [comment]
Test report by @akesandgren
**FAILED**
Build succeeded for 7 out of 8 (8 easyconfigs in this PR)
b-an03.hpc2n.umu.se - Linux ubuntu 16.04, Intel(R) Xeon(R) CPU E5-2690 v4 @ 2.60GHz, Python 2.7.12
See https://gist.github.com/bdb14492cfac12d4811c7228671a5522 for a full test report.

**Comment by zao** [comment]
Test report by @zao
**FAILED**
Build succeeded for 7 out of 8 (8 easyconfigs in this PR)
freja - Linux ubuntu 18.04, Intel(R) Core(TM) i7-8700K CPU @ 3.70GHz, Python 2.7.17
See https://gist.github.com/ff2b37acf11bc0d225b21397182b1eb2 for a full test report.

**Comment by lexming** [comment]
Test report by @lexming
**SUCCESS**
Build succeeded for 8 out of 8 (8 easyconfigs in this PR)
node318.hydra.os - Linux centos linux 7.7.1908, Intel(R) Xeon(R) Gold 6148 CPU @ 2.40GHz, Python 2.7.5
See https://gist.github.com/f38d70ad821a44ccf95c854ccf7eb6ab for a full test report.

**Comment by akesandgren** [comment]
It keeps trying to install MPI/intel/2020.0.166/impi/2019.6.166/imkl/2020.1.217

**Comment by akesandgren** [comment]
Test report by @akesandgren
**FAILED**
Build succeeded for 7 out of 8 (8 easyconfigs in this PR)
b-an03.hpc2n.umu.se - Linux ubuntu 16.04, Intel(R) Xeon(R) CPU E5-2690 v4 @ 2.60GHz, Python 2.7.12
See https://gist.github.com/1a971859714e0723e94dc5ce70883791 for a full test report.

**Comment by akesandgren** [comment]
Test report by @akesandgren
**FAILED**
Build succeeded for 0 out of 8 (8 easyconfigs in this PR)
b-an03.hpc2n.umu.se - Linux ubuntu 16.04, Intel(R) Xeon(R) CPU E5-2690 v4 @ 2.60GHz, Python 2.7.12
See https://gist.github.com/d62a205cf0999010b81d4f51a8cde29e for a full test report.

**Comment by Falkor** [comment]
@boegel I'm surprised that the sources for the easyconfigs `iccifort` relies on a single tarball `parallel_studio_xe_%(version_major)s_update%(version_minor)s_composer_edition.tgz` since 2019b -- I was not able to find this single archive: as for 2019a, I can only download the  Intel Parallel Studio XE Composer Edition for C++ and Fortran as separate archives, i.E. `parallel_studio_xe_%(version_major)s_update%(version_minor)s_composer_edition_for_{fortran,cpp}.tgz` -- wheither for 2019 update 5 or 2020 update 1

**Comment by boegel** [comment]
@akesandgren This worked for me (I mostly did this to also re-test `intel/2020a` with HPL):

```
eb -dfr -u --from-pr 10295 iccifort-2020.1.217.eb impi-2019.7.217-iccifort-2020.1.217.eb iimpi-2020a.eb imkl-2020.1.217-iimpi-2020a.eb intel-2020a.eb HPL-2.3-intel-2020a.eb GEOS-3.8.1-iccifort-2020.1.217-Python-3.8.2.eb GSL-2.6-iccifort-2020.1.217.eb libxc-4.3.4-iccifort-2020.1.217.eb
```

**Comment by akesandgren** [comment]
Test report by @akesandgren
**SUCCESS**
Build succeeded for 8 out of 8 (8 easyconfigs in this PR)
b-an03.hpc2n.umu.se - Linux ubuntu 16.04, Intel(R) Xeon(R) CPU E5-2690 v4 @ 2.60GHz, Python 2.7.12
See https://gist.github.com/12deeebfd13f5bb27eb592831781ee1a for a full test report.

**Comment by boegel** [comment]
> @boegel I'm surprised that the sources for the easyconfigs `iccifort` relies on a single tarball `parallel_studio_xe_%(version_major)s_update%(version_minor)s_composer_edition.tgz` since 2019b -- I was not able to find this single archive: as for 2019a, I can only download the Intel Parallel Studio XE Composer Edition for C++ and Fortran as separate archives, i.E. `parallel_studio_xe_%(version_major)s_update%(version_minor)s_composer_edition_for_{fortran,cpp}.tgz` -- wheither for 2019 update 5 or 2020 update 1

The URLs you can download the full `iccifort` package from is in the easyconfig file, you can just `curl` or `wget` it...

**Comment by akesandgren** [comment]
Yeah, for some reason it insisted on picking up the iimpi-2020a.eb from the 2020a tree (develop setup) and not the one from the repo. I do not have ebfiles_repo/ in my robot-paths but I thought it would explicitly use the ones from the PR...

**Comment by lexming** [comment]
Test report by @lexming
**SUCCESS**
Build succeeded for 8 out of 8 (8 easyconfigs in this PR)
login2.cerberus.os - Linux centos linux 7.7.1908, x86_64, Intel(R) Xeon(R) Gold 6126 CPU @ 2.60GHz, Python 2.7.5
See https://gist.github.com/455ad8e3d3e7a8b97dc126e430d0b3eb for a full test report.

**Comment by lexming** [comment]
Going in, thanks @boegel !

**Pull request merged**
