### PR TITLE
{data}[foss/2022a] dask v2022.10.2 w/ Python 3.10.4

### PR DESCRIPTION
**Pull request by sassy-crick**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by verdurin** [comment]
@boegelbot please test @ generoso

**Comment by verdurin** [comment]
Test report by @verdurin
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
easybuild-c7.novalocal - Linux CentOS Linux 7.9.2009, x86_64, Intel Xeon Processor (Skylake, IBRS), Python 3.6.8
See https://gist.github.com/c46eb1363140e92b8bb2010f5af552ab for a full test report.

**Comment by verdurin** [comment]
@boegelbot please test @ jsc-zen2

**Comment by verdurin** [comment]
@sassy-crick this looks fine, I just wonder whether this addition of another minor version of `dask` in the same toolchain will cause problems later? Do the applications using this as a dependent require this minor update?

**Comment by sassy-crick** [comment]
> @sassy-crick this looks fine, I just wonder whether this addition of another minor version of `dask` in the same toolchain will cause problems later? Do the applications using this as a dependent require this minor update?

@verdurin Thanks for looking into that PR. The short answer is: I simply missed the already existing version. That is all. I just have rebuild PR #16637 and that worked fine. So if you want to close that PR I got no objections.

**Comment by lexming** [comment]
@sassy-crick it's already too late to use this version of dask as dependency in this toolchain. There is already `scikit-image-0.19.3-foss-2022a.eb` depending on dask v2022.10.0. I'll close this PR and please update the dependencies on dask on your other open PRs.

**Pull request closed without merging**
