### PR TITLE
{lang}[intel/2019a] SciPy-bundle v2019.10 w/ Python 3.7.2

### PR DESCRIPTION
**Pull request by guacke**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by boegel** [comment]
@guacke We usually stick to a single `SciPy-bundle` version per generation of easyconfigs (`2019a` in this case).

Any reason you can't use the SciPy-bundle 2019.10 bundle for `intel/2019b`?

**Comment by guacke** [comment]
@boegel I want to automate Gaussian calculations using Python scripts that use the subprocess, Numpy and Pandas libraries. The versions of Gaussian installed on hpc-ugent are (currently) only the 2018a and 2019a versions, leading to compatibility errors with the provided SciPy-bundles.

**Comment by boegel** [comment]
@boegelbot please test @ generoso

**Review by boegel — APPROVED** [review]
lgtm, doesn't hurt to have a more recent `SciPy-bundle` in 2019a (but we won't use it as a dependency for other stuff in this generation of easyconfigs)

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
node3402.kirlia.os - Linux centos linux 7.8.2003, x86_64, Intel(R) Xeon(R) Gold 6240 CPU @ 2.60GHz (cascadelake), Python 2.7.5
See https://gist.github.com/6466337fb01b8b51258df70b0b259f57 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
node3134.skitty.os - Linux centos linux 7.8.2003, x86_64, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz, Python 3.6.8
See https://gist.github.com/576b27bad1a2fe4c45838efa810756c5 for a full test report.

**Comment by boegel** [comment]
Going in, thanks @guacke!

**Pull request merged**
