### PR TITLE
use https for UDUNITS fallback source URL

### PR DESCRIPTION
**Pull request by boegel**
(created using `eb --new-pr`)

### CODE REVIEW

**Review by branfosj — APPROVED** [review]
lgtm

**Comment by branfosj** [comment]
Test report by @branfosj
**SUCCESS**
Build succeeded for 16 out of 16 (16 easyconfigs in total)
bb-pg-login02.bear.cluster - Linux centos linux 7.8.2003, x86_64, Intel(R) Xeon(R) CPU E5-2620 v4 @ 2.10GHz (broadwell), Python 3.6.8
See https://gist.github.com/b39e5ffc5d1786a919d0e6e265473d03 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 16 out of 16 (16 easyconfigs in total)
node2614.swalot.os - Linux centos linux 7.9.2009, x86_64, Intel(R) Xeon(R) CPU E5-2660 v3 @ 2.60GHz (haswell), Python 3.6.8
See https://gist.github.com/a24f321460509d040fff1d6b1086a9df for a full test report.

**Comment by branfosj** [comment]
Going in, thanks @boegel!

**Pull request merged**
