### PR TITLE
{vis}[foss/2022a] wxPython v4.2.1

### PR DESCRIPTION
**Pull request by ThomasHoffmann77**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by casparvl** [comment]
@boegelbot please test @ generoso

**Comment by casparvl** [comment]
Test report by @casparvl
**FAILED**
Build succeeded for 18 out of 27 (9 easyconfigs in total)
tcn30.local.snellius.surf.nl - Linux RHEL 8.6, x86_64, AMD EPYC 7H12 64-Core Processor, Python 3.6.8
See https://gist.github.com/casparvl/7dfdac117ec1518a635d39341663f4fb for a full test report.

**Comment by casparvl** [comment]
Test report by @casparvl
**FAILED**
Build succeeded for 8 out of 9 (9 easyconfigs in total)
tcn30.local.snellius.surf.nl - Linux RHEL 8.6, x86_64, AMD EPYC 7H12 64-Core Processor, Python 3.6.8
See https://gist.github.com/casparvl/233a55395dc02f25c6ba10405d5e6f91 for a full test report.

**Comment by ThomasHoffmann77** [comment]
> 



> Test report by @casparvl **FAILED** Build succeeded for 8 out of 9 (9 easyconfigs in total) tcn30.local.snellius.surf.nl - Linux RHEL 8.6, x86_64, AMD EPYC 7H12 64-Core Processor, Python 3.6.8 See https://gist.github.com/casparvl/233a55395dc02f25c6ba10405d5e6f91 for a full test report.

**Comment by ThomasHoffmann77** [comment]
_Test report by @casparvl **FAILED** Build succeeded for 8 out of 9 (9 easyconfigs in total) tcn30.local.snellius.surf.nl - Linux RHEL 8.6, x86_64, AMD EPYC 7H12 64-Core Processor, Python 3.6.8 See https://gist.github.com/casparvl/233a55395dc02f25c6ba10405d5e6f91 for a full test report._

is the failure due to "_scratch-nvme_1_casparl_generic_software_WebKitGTK+_2.40.4-GCC-11.3.0.lock already exists", or do I need to fix something else? @casparvl

**Comment by casparvl** [comment]
@ThomasHoffmann77 yeah, sorry, I had a build that was broken off prematurely (job got killed due to walltime), but forgot to remove the lock file. It's fine: the module built at some point, even if that build did _not_ upload a test report. Plus, there are the two boegelbot builds that were also succesful. Enough to convince me, I'll approve the PR :)

**Review by casparvl — APPROVED** [review]
Lgtm!

**Review by casparvl — APPROVED** [review]

**Comment by casparvl** [comment]
Going in, thanks @ThomasHoffmann77!

**Pull request merged**
