### PR TITLE
Fix new checksum for plot3Drgl

### PR DESCRIPTION
**Pull request by Micket**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by Micket** [comment]
i'm just gonna build R-4.1.0-foss-2021a.eb since that's the one i needed right now

**Comment by branfosj** [comment]
```
$ wget https://cran.r-project.org/src/contrib/Archive/plot3Drgl/plot3Drgl_1.0.2.tar.gz
$ sha256sum plot3Drgl_1.0.2.tar.gz 
805513029895cf5a81f18ede4123ef2525a236cd555437609229fe720c346e14  plot3Drgl_1.0.2.tar.gz
```

So the new checksum is as expected.

**Comment by Micket** [comment]
Test report by @Micket
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
alvis-c1 - Linux Rocky Linux 8.5, x86_64, Intel Xeon Processor (Skylake), Python 3.6.8
See https://gist.github.com/8496c0ced481c1e344bc4935eb575393 for a full test report.

**Review by branfosj — APPROVED** [review]
lgtm

**Comment by branfosj** [comment]
Going in, thanks @Micket!

**Comment by boegel** [comment]
@Micket @branfosj Did you diff the old vs new source tarball?

**Comment by branfosj** [comment]
> @Micket @branfosj Did you diff the old vs new source tarball?

```
-rw-r--r--. 1 simon simon  297277 Jun  4 07:09 plot3Drgl_1.0.2.tar.gz.now
-rwx------. 1 simon simon  297261 Aug  9 19:48 plot3Drgl_1.0.2.tar.gz.old
```

```
$ du -shb plot3Drgl_*
408086  plot3Drgl_now
408086  plot3Drgl_old
```

And diff on them showed them to be identical.

**Pull request merged**
