### PR TITLE
{math}[foss/2021a] Bottleneck v1.3.2 w/ Python 3.9.5

### PR DESCRIPTION
**Pull request by SIB-software**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by jfgrimm** [comment]
Test report by @jfgrimm
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
node021.pri.viking.alces.network - Linux CentOS Linux 7.9.2009, x86_64, Intel(R) Xeon(R) Gold 6138 CPU @ 2.00GHz (skylake_avx512), Python 3.6.8
See https://gist.github.com/3c26b82117a87e82fd33210402e97a09 for a full test report.

**Comment by jfgrimm** [comment]
@boegelbot: please test @ generoso

**Comment by jfgrimm** [comment]
ah, `Bottleneck 1.3.2` is actually already included in `SciPy-bundle-2021.05-foss-2021a.eb`

**Comment by smoretti** [comment]
Ah! I missed that
So should we close the PR?

**Comment by jfgrimm** [comment]
easy to miss, and yes please :)

**Pull request closed without merging**
