### PR TITLE
{lib}[GCCcore/12.3.0] Blosc 1.12.5, Blosc2 2.8.0

### PR DESCRIPTION
**Pull request by Flamefire**
Extracted from https://github.com/easybuilders/easybuild-easyconfigs/pull/19398

### CODE REVIEW

**Comment by Flamefire** [comment]
Test report by @Flamefire
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in total)
n1505 - Linux RHEL 8.7 (Ootpa), x86_64, Intel(R) Xeon(R) Platinum 8470 (icelake), Python 3.8.13
See https://gist.github.com/Flamefire/27d4324ebd35dc63ab2ecf8692ffad23 for a full test report.

**Comment by Flamefire** [comment]
Test report by @Flamefire
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in total)
taurusml3 - Linux RHEL 7.6, POWER, 8335-GTX (power9le), 6 x NVIDIA Tesla V100-SXM2-32GB, 440.64.00, Python 2.7.5
See https://gist.github.com/Flamefire/9e9715d438ac1490c99719d210764602 for a full test report.

**Comment by ocaisa** [comment]
@boegelbot please test @ generoso

**Comment by ocaisa** [comment]
@boegelbot please test @ jsc-zen3

**Comment by ocaisa** [comment]
@boegelbot please test @ jsc-zen3

**Review by ocaisa — APPROVED** [review]

**Pull request merged**
