### PR TITLE
{vis}[GCCcore/11.3.0] xprop v1.2.5, FLTK v1.3.8

### PR DESCRIPTION
**Pull request by Micket**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by Micket** [comment]
Test report by @Micket
**FAILED**
Build succeeded for 1 out of 2 (2 easyconfigs in total)
vera-c2 - Linux Rocky Linux 8.4, x86_64, Intel Xeon Processor (Skylake), Python 3.6.8
See https://gist.github.com/774c2e1ed724771e813cee269fc535ae for a full test report.

**Comment by Micket** [comment]
Test report by @Micket
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in total)
vera-c2 - Linux Rocky Linux 8.4, x86_64, Intel Xeon Processor (Skylake), Python 3.6.8
See https://gist.github.com/4ce5b1aae3ef51701b8274dba7193a57 for a full test report.

**Comment by Micket** [comment]
@boegelbot please test @ generoso

**Comment by smoors** [comment]
@boegelbot please test @ jsc-zen2

**Review by smoors — APPROVED** [review]
lgtm

**Comment by smoors** [comment]
Going in, thanks @Micket!

**Pull request merged**
