### PR TITLE
{tools}[GCCcore/12.3.0] nvtop v3.1.0

### PR DESCRIPTION
**Pull request by VRehnberg**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by VRehnberg** [comment]
Test report by @VRehnberg
**FAILED**
Failed during parsing of the easyconfigs, so no ecs were built (1 easyconfigs in total)
alvis6-07 - Linux Rocky Linux 8.9, x86_64, Intel(R) Xeon(R) Gold 6338 CPU @ 2.00GHz, 1 x NVIDIA NVIDIA A40, 550.54.14, Python 3.6.8
See https://gist.github.com/VRehnberg/fa918ae696ecd7bd19d6e3709a5d610e for a full test report.

**Comment by VRehnberg** [comment]
Test report by @VRehnberg
**FAILED**
Failed during parsing of the easyconfigs, so no ecs were built (1 easyconfigs in total)
alvis6-07 - Linux Rocky Linux 8.9, x86_64, Intel(R) Xeon(R) Gold 6338 CPU @ 2.00GHz, 1 x NVIDIA NVIDIA A40, 550.54.14, Python 3.6.8
See https://gist.github.com/VRehnberg/3b06cb4de45c43e5ca136bc87c9ea01e for a full test report.

**Comment by VRehnberg** [comment]
Test report by @VRehnberg
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
alvis-icelake-build - Linux Rocky Linux 8.9, x86_64, Intel(R) Xeon(R) Silver 4316 CPU @ 2.30GHz, Python 3.6.8
See https://gist.github.com/VRehnberg/773d421de24daecc527757c7397515ac for a full test report.

**Review by Micket — APPROVED** [review]
lgtm

**Comment by Micket** [comment]
Don't think the bots have the OS deps, will have to skip those builds.

**Comment by Micket** [comment]
Test report by @Micket
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
vera-skylake-build - Linux Rocky Linux 8.9, x86_64, Intel Xeon Processor (Skylake, IBRS, no TSX), Python 3.6.8
See https://gist.github.com/Micket/a6714978d4385cb32ede426428e8c4d8 for a full test report.

**Comment by Micket** [comment]
Test report by @Micket
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
vera-icelake-build - Linux Rocky Linux 8.9, x86_64, Intel(R) Xeon(R) Silver 4316 CPU @ 2.30GHz, Python 3.6.8
See https://gist.github.com/Micket/2896fbf5e75660b963d5a8d4082aade3 for a full test report.

**Comment by Micket** [comment]
Going in, thanks @VRehnberg!

**Pull request merged**
