### PR TITLE
{cae}[foss/2022a] ngspice v39

### PR DESCRIPTION
**Pull request by bedroge**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by bedroge** [comment]
Test report by @bedroge
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
bob-Latitude-5300 - Linux Ubuntu 22.04, x86_64, Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz, Python 3.10.6
See https://gist.github.com/e01b64a7aae1ab8726edac6197dbc26c for a full test report.

**Comment by bedroge** [comment]
@boegelbot please test @ generoso

**Comment by emdrago** [comment]
Test report by @emdrago
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
gput052 - Linux RHEL 8.7 (Ootpa), x86_64, Intel(R) Xeon(R) CPU E5-2630 v4 @ 2.20GHz, 1 x NVIDIA NVIDIA GeForce RTX 2080 Ti, 510.47.03, Python 3.9.13
See https://gist.github.com/989cc5f8554fff0652ccaf960137e1a2 for a full test report.

**Comment by branfosj** [comment]
@boegelbot please test @ jsc-zen2

**Comment by branfosj** [comment]
Test report by @branfosj
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
bear-pg0105u03a.bear.cluster - Linux RHEL 8.6, x86_64, Intel(R) Xeon(R) Platinum 8360Y CPU @ 2.40GHz (icelake), Python 3.6.8
See https://gist.github.com/branfosj/f4e7dfcdc50b596a72fd7547f079dd4c for a full test report.

**Review by branfosj — APPROVED** [review]

**Comment by branfosj** [comment]
Going in, thanks @bedroge!

**Comment by branfosj** [comment]
Going in, thanks @bedroge!

**Pull request merged**
