### PR TITLE
{tools}[system/system] Nsight-Systems v2020.5.1

### PR DESCRIPTION
**Pull request by Micket**
(created using `eb --new-pr`)

Note: manual signin and download required

### CODE REVIEW

**Comment by Micket** [comment]
Test report by @Micket
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
alvis-c1 - Linux centos linux 7.9.2009, x86_64, Intel Xeon Processor (Skylake), Python 3.6.8
See https://gist.github.com/22a58f0bc8824c04ed89ee095366dc70 for a full test report.

**Comment by verdurin** [comment]
Test report by @verdurin
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
nuc.lan - Linux Fedora 32, x86_64, Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz, Python 3.8.7
See https://gist.github.com/eafeeab5b2b6fd04c6fa080e3c0a8c6c for a full test report.

**Review by verdurin — APPROVED** [review]
Looks fine.

**Comment by verdurin** [comment]
Going in, thanks @Micket!

**Comment by boegel** [comment]
Installation fails for me with:

```
Can't locate Env.pm in @INC (@INC contains: /usr/local/lib64/perl5 /usr/local/share/perl5 /usr/lib64/perl5/vendor_perl /usr/share/perl5/vendor_perl /usr/lib64/perl5 /usr/share/perl5 .) at ./install-linux.pl line 10.
BEGIN failed--compilation aborted at ./install-linux.pl line 10.
```

Same goes for #12043.

Should we add `Perl` as a build dep?

**Comment by Micket** [comment]
@boegelbot Dang, I really wanted to keep this at SYSTEM level. It would be really inconvenient to move this into a toolchain just for a perl build dep.

**Comment by boegel** [comment]
@Micket You don't have to move it to a different toolchain, you can do this since it's only a build dep:

```python
builddependencies = [('Perl', '5.32.0', '', ('GCCcore', '10.2.0')]

**Comment by Micket** [comment]
Hm, and that works on HMNS as well?

**Comment by boegel** [comment]
@Micket Yes, last bit just specifies toolchain name + version, it doesn't hardcode the module naming scheme in any way.

**Comment by boegel** [comment]
Adding `Perl` as a build dependency won't help much, because the Perl script `install-linux.pl`, which is embedded in the `*.run` "source" file (so not easy to patch) has a hardcoded `#!/usr/bin/perl`... :-/

**Pull request merged**
