### PR TITLE
adding easyconfig for advisor2019u3, +download URL for advisor2019u2

### PR DESCRIPTION
**Pull request by jose-d**
(created using `eb --new-pr`)

requires [easybuild-easyblocks PR#1695](https://github.com/easybuilders/easybuild-easyblocks/pull/1695)

### CODE REVIEW

**Comment by jose-d** [comment]
Test report by @jose-d
**FAILED**
Build succeeded for 1 out of 2 (2 easyconfigs in this PR)
koios1 - Linux centos linux 7.6.1810, Intel(R) Xeon(R) Gold 6130 CPU @ 2.10GHz, Python 2.7.5
See https://gist.github.com/2025a1fcb982cb916f6a49315f53a025 for a full test report.

**Comment by jose-d** [comment]
Test report by @jose-d
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in this PR)
koios1 - Linux centos linux 7.6.1810, Intel(R) Xeon(R) Gold 6130 CPU @ 2.10GHz, Python 2.7.5
See https://gist.github.com/e681f9f940f420f744c8ba6a0e1c18a7 for a full test report.

**Comment by jose-d** [comment]
Test report by @jose-d
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in this PR)
koios1 - Linux centos linux 7.6.1810, Intel(R) Xeon(R) Gold 6130 CPU @ 2.10GHz, Python 2.7.5
See https://gist.github.com/57f3f5fd9ca9810c8efc9da1dd4b0b98 for a full test report.

**Comment by bartoldeman** [comment]
Test report by @bartoldeman
**FAILED**
Build succeeded for 1 out of 2 (2 easyconfigs in this PR)
lg-1r17-n06 - Linux centos 6.6, Intel(R) Xeon(R) CPU E5-2650 0 @ 2.00GHz, Python 2.6.6
See https://gist.github.com/4c61f7620084bd4f3ceaf4919b63149b for a full test report.

**Comment by bartoldeman** [comment]
Test report by @bartoldeman
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
lg-1r17-n06 - Linux centos 6.6, Intel(R) Xeon(R) CPU E5-2650 0 @ 2.00GHz, Python 2.6.6
See https://gist.github.com/ab7f67ffb5fccde0475cad540699da4d for a full test report.

**Comment by bartoldeman** [comment]
Going in, thanks @jose-d!

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in this PR)
node3110.skitty.os - Linux centos linux 7.6.1810, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz, Python 2.7.5
See https://gist.github.com/44860c0b3f7901d15dab950fe32d8036 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in this PR)
node2409.golett.os - Linux centos linux 7.6.1810, Intel(R) Xeon(R) CPU E5-2680 v3 @ 2.50GHz, Python 2.7.5
See https://gist.github.com/868964a74f38fc3a5fe2795b19c5fe6c for a full test report.

**Pull request merged**
