### PR TITLE
{bio}[foss/2022a] Phenoflow v1.1.2-20200917, flowFDA v0.99-20220602

### PR DESCRIPTION
**Pull request by boegel**
(created using `eb --new-pr`)
requires:
* #17493
* #17494

### CODE REVIEW

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in total)
node3135.skitty.os - Linux RHEL 8.6, x86_64, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz (skylake_avx512), Python 3.6.8
See https://gist.github.com/be40a84854c905b03eada2a89a4ac898 for a full test report.

**Comment by boegel** [comment]
@boegelbot please test @ generoso

**Comment by casparvl** [comment]
Test report by @casparvl
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in total)
tcn502.local.snellius.surf.nl - Linux Rocky Linux 8.7, x86_64, AMD EPYC 7H12 64-Core Processor, Python 3.6.8
See https://gist.github.com/3007f07d6c53e96d52980ad7ae58d217 for a full test report.

**Review by casparvl — APPROVED** [review]
Lgtm

**Comment by casparvl** [comment]
Going in, thanks @boegel!

**Pull request merged**
