### PR TITLE
{toolchain}[dummy/dummy] goolfc v2018a

### PR DESCRIPTION
**Pull request by akesandgren**
(created using `eb --new-pr`)
New goolfc version 2018a. Based on foss/2018a + CUDA 9.1

### CODE REVIEW

**Comment by vanzod** [comment]
@akesandgren If this is alligned with `foss`, didn't @boegel agreed to rename the toolchain `fosscuda`?
I know I promised to work on this but I have not had time yet...

**Comment by akesandgren** [comment]
I don't know. I missed the last couple of meetings (and forgot to read the notes).
But since our users are accustomed to using goolfc for this I'll keep it up until told otherwise :-)

**Comment by boegel** [comment]
Rebranding `goolfc` as `fosscuda` makes sense to me...

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 6 out of 6 (6 easyconfigs in this PR)
node2113.delcatty.os - Linux centos linux 7.4.1708, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.7.5
See https://gist.github.com/0039bd4e83ba603dbfdce64de40fc7dc for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 7 out of 7 (6 easyconfigs in this PR)
node2637.swalot.os - Linux centos linux 7.4.1708, Intel(R) Xeon(R) CPU E5-2660 v3 @ 2.60GHz, Python 2.7.5
See https://gist.github.com/5a0679ec8c60e295126c1c1e2efb6e01 for a full test report.

**Comment by boegel** [comment]
I propose we add `fosscuda` equivalents for the "common" `goolfc` versions in a separate PR, by means of transition...

**Comment by boegel** [comment]
Going in, thanks @akesandgren!

**Pull request merged**
