### PR TITLE
Added easyconfig for ELPA-2017.11.001 with intel 2018a. Ported patch.

### PR DESCRIPTION
**Pull request by bartoldeman**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by bartoldeman** [comment]
Asking for feedback from @akesandgren : I simply ported the patch but found that the examples directory was not created at the postinstall stage. Maybe you remember some details about how that should be?

**Comment by akesandgren** [comment]
They have removed installation of the examples. So that stuff can be dropped. Both the patch and the things related to it.

**Comment by boegel** [comment]
@bartoldeman Sanity check fails for me, see also test report; did you see `lib/libelpatest*` still being built on your end?

```
== sanity checking...
  >> file 'lib/libelpa.a' found: OK
  >> file 'lib/libelpa.so' found: OK
  >> file 'lib/libelpa_openmp.a' found: OK
  >> file 'lib/libelpa_openmp.so' found: OK
  >> file 'lib/libelpatest.a' found: FAILED
  >> file 'lib/libelpatest.so' found: FAILED
  >> file 'lib/libelpatest_openmp.a' found: FAILED
  >> file 'lib/libelpatest_openmp.so' found: FAILED
  >> (non-empty) directory 'bin' found: OK
  >> (non-empty) directory 'include/elpa-2017.11.001/elpa' found: OK
  >> (non-empty) directory 'include/elpa-2017.11.001/modules' found: OK
  >> (non-empty) directory 'lib/pkgconfig' found: OK
```

```
$ ls $EASYBUILD_PREFIX/software/ELPA/2017.11.001-intel-2018a/lib
libelpa.a   libelpa_openmp.a   libelpa_openmp.so     libelpa_openmp.so.11.0.0  libelpa.so.11      pkgconfig
libelpa.la  libelpa_openmp.la  libelpa_openmp.so.11  libelpa.so                libelpa.so.11.0.0
```

**Comment by boegel** [comment]
Test report by @boegel
**FAILED**
Build succeeded for 0 out of 1 (1 easyconfigs in this PR)
node2627.swalot.os - Linux centos linux 7.4.1708, Intel(R) Xeon(R) CPU E5-2660 v3 @ 2.60GHz, Python 2.7.5
See https://gist.github.com/d6b959d5ce2b5e83e28bb7a2c07f022b for a full test report.

**Comment by bartoldeman** [comment]
@boegel : I had not properly rechecked after implementing  @akesandgren's suggestion of removing the patch. This means that *_test libraries are no longer built and should be removed from the sanity check. I'll remove those.

**Comment by boegel** [comment]
@bartoldeman Wouldn't it be better to still apply the patch then? Or are the `libelpatest*` libraries no longer relevant?

**Comment by bartoldeman** [comment]
I just followed the advice of @akesandgren. Maybe you can confirm Åke?

**Comment by akesandgren** [comment]
The libelpatest lib are useless in the installdir without the example codes, so there is no need to have the patch. You would get a lib installed that is never used.

**Comment by boegel** [comment]
Thanks for clarifying @akesandgren!

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
node2629.swalot.os - Linux centos linux 7.4.1708, Intel(R) Xeon(R) CPU E5-2660 v3 @ 2.60GHz, Python 2.7.5
See https://gist.github.com/65e4768c2bd7039abd80708050a36aa3 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
node2036.delcatty.os - Linux centos linux 7.4.1708, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.7.5
See https://gist.github.com/7a96fd4d2b6caeae3b6cea65dc7043f0 for a full test report.

**Comment by boegel** [comment]
Going in, thanks @bartoldeman!

**Pull request merged**
