### PR TITLE
{toolchain} foss/2022b

### PR DESCRIPTION
**Pull request by boegel**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by boegel** [comment]
@boegelbot please test @ generoso

**Comment by SebastianAchilles** [comment]
@boegelbot please test @ jsc-zen2

**Comment by SebastianAchilles** [comment]
Test report by @sebastianachilles
**SUCCESS**
Build succeeded for 7 out of 7 (7 easyconfigs in total)
bwd-rockylinux-91 - Linux Rocky Linux 9.1 (Blue Onyx), x86_64, Intel(R) Core(TM) i7-6900K CPU @ 3.20GHz (broadwell), 2 x NVIDIA NVIDIA GeForce GTX 1060 6GB, 515.86.01, Python 3.9.14
See https://gist.github.com/0675d10a3d628db0c0f4115d07891fee for a full test report.

**Comment by SebastianAchilles** [comment]
Test report by @sebastianachilles
**SUCCESS**
Build succeeded for 7 out of 7 (7 easyconfigs in total)
zen2-ubuntu-2210 - Linux Ubuntu 22.10 (Kinetic Kudu), x86_64, AMD EPYC 7452 32-Core Processor (zen2), Python 3.10.7
See https://gist.github.com/f100f2a0c6445add10fe0f89807a6684 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 7 out of 7 (7 easyconfigs in total)
node3104.skitty.os - Linux RHEL 8.6, x86_64, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz (skylake_avx512), Python 3.6.8
See https://gist.github.com/28e1d1688218caac9acd2591848e6685 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 15 out of 15 (7 easyconfigs in total)
fair-mastodon-c6g-2xlarge-0001 - Linux Rocky Linux 8.5, AArch64, ARM UNKNOWN (graviton2), Python 3.6.8
See https://gist.github.com/2d143fd2c1b808d04bd1c6998e805a13 for a full test report.

**Comment by akesandgren** [comment]
Test report by @akesandgren
**FAILED**
Build succeeded for 3 out of 54 (7 easyconfigs in total)
b-an02.hpc2n.umu.se - Linux Ubuntu 20.04, x86_64, Intel(R) Xeon(R) CPU E5-2690 v4 @ 2.60GHz, Python 3.8.10
See https://gist.github.com/1a979271fbf79e05f2fab6b6bfe9a8b9 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 14 out of 14 (7 easyconfigs in total)
easybuild2.novalocal - Linux CentOS Stream 8, POWER, IBM pSeries (emulated by qemu) (power9le), Python 3.6.8
See https://gist.github.com/2c39702b3253ed039c9ce0bb6918036e for a full test report.

**Comment by boegel** [comment]
@akesandgren Your installation failed with:
```
/bin/sh: 1: perl: not found
make: *** [Makefile:118: install] Error 127
```

That's definitely a problem (we silently rely on OS Perl to build `GCCcore`), but that shouldn't be a blocker for this PR imho...

**Comment by akesandgren** [comment]
Test report by @akesandgren
**SUCCESS**
Build succeeded for 51 out of 51 (7 easyconfigs in total)
b-an02.hpc2n.umu.se - Linux Ubuntu 20.04, x86_64, Intel(R) Xeon(R) CPU E5-2690 v4 @ 2.60GHz, Python 3.8.10
See https://gist.github.com/7aa7c30e321268a1752a324017a76f98 for a full test report.

**Review by Micket — APPROVED** [review]
lgtm

**Comment by boegel** [comment]
@Micket I'm confused as to why you're seemingly the only one hitting this with OpenBLAS:

```
Too many LAPACK tests failed due to numerical errors: 1103 (> 150)
```

There's also a problem with FlexiBLAS (but the partial log doesn't show the actual compilation error):
```
make: *** [Makefile:149: all] Error 2
```

**Comment by boegel** [comment]
@Micket My best guess here is that this is somehow self-inflicted via the hooks you're using (`/apps/c3se_hooks.py`)...

Are those available somewhere for closer inspection?

**Comment by Micket** [comment]
incomplete old flexiblas easyconfig in the working directory messed things up. surprised it was built.

**Comment by Micket** [comment]
Test report by @Micket
**FAILED**
Build succeeded for 0 out of 13 (7 easyconfigs in total)
vera-c2 - Linux Rocky Linux 8.6, x86_64, Intel Xeon Processor (Skylake), Python 3.6.8
See https://gist.github.com/bc4cb568d562a8f810c82fe0909add27 for a full test report.

**Comment by boegel** [comment]
@Micket Do make sure your `GCCcore/12.2.0` was installed with the patches from https://github.com/easybuilders/easybuild-easyconfigs/pull/16411, and that you're using the updated `libxml2` easyblock from https://github.com/easybuilders/easybuild-easyblocks/pull/2825 ...

**Comment by migueldiascosta** [comment]
Test report by @migueldiascosta
**SUCCESS**
Build succeeded for 7 out of 7 (7 easyconfigs in total)
sms - Linux CentOS Linux 7.6.1810, x86_64, AMD EPYC 7601 32-Core Processor (zen), Python 2.7.5
See https://gist.github.com/f85b12e050e560803bbb4b2bc07ca28d for a full test report.

**Review by migueldiascosta — APPROVED** [review]
lgtm

**Comment by migueldiascosta** [comment]
Going in, thanks @boegel!

**Pull request merged**
