### PR TITLE
update source to be able to download alsa

### PR DESCRIPTION
**Pull request by pavelToman**
(created using `eb --new-pr`)

www.alsa-project.org does not work now.
Better to download source from GitHub?

### CODE REVIEW

**Comment by pavelToman** [comment]
@boegelbot please test @ generoso

**Comment by pavelToman** [comment]
@boegelbot please test @ jsc-zen3

**Comment by pavelToman** [comment]
@boegelbot please test @ jsc-zen3

**Comment by boegel** [comment]
Looks like this was a temporary problem, download from https://www.alsa-project.org/files/pub/lib/ is working fine (again), so closing this...

**Pull request closed without merging**
