### PR TITLE
remove Highway build dependency in Brunsli easyconfigs, since it's not actually required at all

### PR DESCRIPTION
**Pull request by boegel**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by boegel** [comment]
@boegelbot please test @ generoso

**Comment by bedroge** [comment]
Test report by @bedroge
**SUCCESS**
Build succeeded for 6 out of 6 (5 easyconfigs in total)
bob-Latitude-5300 - Linux Ubuntu 24.04.1 LTS (Noble Numbat), x86_64, Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz, Python 3.12.3
See https://gist.github.com/bedroge/95da45b012c87d82a8bd44ac0f478477 for a full test report.

**Comment by boegel** [comment]
@boegelbot please test @ jsc-zen3

**Comment by ocaisa** [comment]
@boegelbot please test @ jsc-zen3

**Comment by ocaisa** [comment]
@boegelbot please test @ jsc-zen3

**Comment by bedroge** [comment]
Test report by @bedroge
**SUCCESS**
Build succeeded for 7 out of 7 (6 easyconfigs in total)
interactive1 - Linux Rocky Linux 8.9, x86_64, AMD EPYC-Milan Processor (zen3), Python 3.6.8
See https://gist.github.com/bedroge/7867bd4b815caae5b6337e3c4d962f47 for a full test report.

**Comment by boegel** [comment]
> LGTM, no mention of Highway in the Brunsli git repo

Yeah, I couldn't find anything either, also not in EasyBuild log for Brunsli installations (even though I also looked for `-lhwy`, `hwy`, etc.)

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 7 out of 7 (7 easyconfigs in total)
node3116.skitty.os - Linux RHEL 8.8, x86_64, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz, Python 3.6.8
See https://gist.github.com/boegel/f573e171bf5e4c679a62d6e961e9d80c for a full test report.

**Pull request merged**
