### PR TITLE
{vis}[foss/2018b] VV 2018.09.19 w/Python 3.6.6 (REVIEW)

### PR DESCRIPTION
**Pull request by hajgato**

### CODE REVIEW

**Comment by hajgato** [comment]
I am not necessarily want to merge this pull request, I just want to keep for the record (so I am happy to close it, if it is suggested)

**Comment by vanzod** [comment]
@hajgato What does the `Qt5` dependency add compared to the one provided in #7297?

**Comment by hajgato** [comment]
@vanzod It adds a graphical interface. (and unfortunately, it needs `ITK` and `VTK` with `Qt5` extensions in this case) This is the reason why I am not keen to add to the upstream, because it introduces a new version of `ITK` and `VTK` into `foss/2018b` toolchain. From travis:
~~~
found 3 variants of 'ITK' dependency in easyconfigs using '2018b' toolchain generation
* version: 4.13.1; versionsuffix: -Python-2.7.15 as dep for set(['SimpleITK-1.1.0-foss-2018b-Python-2.7.15.eb'])
* version: 4.13.1; versionsuffix: -Python-3.6.6 as dep for set(['SimpleITK-1.1.0-foss-2018b-Python-3.6.6.eb'])
* version: 4.13.1; versionsuffix: -Python-3.6.6-Qt5-5.10.1 as dep for set(['VV-2018.09.19-foss-2018b-Python-3.6.6-Qt5-5.10.1.eb'])

found 3 variants of 'VTK' dependency in easyconfigs using '2018b' toolchain generation
* version: 8.1.1; versionsuffix: -Python-2.7.15 as dep for set(['ITK-4.13.1-foss-2018b-Python-2.7.15.eb', 'SimpleITK-1.1.0-foss-2018b-Python-2.7.15.eb', 'FSL-5.0.11-foss-2018b.eb'])
* version: 8.1.1; versionsuffix: -Python-3.6.6 as dep for set(['FSL-5.0.11-foss-2018b-Python-3.6.6.eb', 'ITK-4.13.1-foss-2018b-Python-3.6.6.eb', 'SimpleITK-1.1.0-foss-2018b-Python-3.6.6.eb'])
* version: 8.1.1; versionsuffix: -Python-3.6.6-Qt5-5.10.1 as dep for set(['ITK-4.13.1-foss-2018b-Python-3.6.6-Qt5-5.10.1.eb', 'VV-2018.09.19-foss-2018b-Python-3.6.6-Qt5-5.10.1.eb'])
~~~

**Comment by vanzod** [comment]
@hajgato Sounds reasonable. However it would be good to use this one instead of the one without the GUI in the 2019a toolchains, especially because the Python dependency management should make everything less messy.

**Pull request closed without merging**
