### PR TITLE
{bio}[GCC/12.3.0] angsd v0.940

### PR DESCRIPTION
**Pull request by WilleBell**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by WilleBell** [comment]
Test report by @WilleBell
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
node314.hydra.os - Linux Rocky Linux 8.8, x86_64, Intel(R) Xeon(R) Gold 6148 CPU @ 2.40GHz, Python 3.6.8
See https://gist.github.com/WilleBell/4974ebd3c1d67747912cb7d45e54b8b0 for a full test report.

**Comment by akesandgren** [comment]
@boegelbot Please test @ jsc-zen2

**Review by akesandgren — APPROVED** [review]
LGTM

**Comment by akesandgren** [comment]
Going in, thanks @WilleBell!

**Pull request merged**
