### PR TITLE
{compiler}[system/system] NVHPC v21.9

### PR DESCRIPTION
**Pull request by robert-mijakovic**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by robert-mijakovic** [comment]
Test report by @robert-mijakovic
**FAILED**
Build succeeded for 0 out of 1 (1 easyconfigs in total)
mel0385 - Linux centos linux 8.4.2105, x86_64, AMD EPYC 7H12 64-Core Processor (zen2), Python 3.6.8
See https://gist.github.com/a0c7dc1f2bcecfe1941d3a21d84a582e for a full test report.

**Comment by robert-mijakovic** [comment]
Test report by @robert-mijakovic
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
mel0237 - Linux centos linux 8.4.2105, x86_64, AMD EPYC 7H12 64-Core Processor (zen2), Python 3.6.8
See https://gist.github.com/6816fa32b9c62a0668c28787da8b2ae1 for a full test report.

**Comment by robert-mijakovic** [comment]
@boegelbot please test @ generoso

**Review by migueldiascosta — APPROVED** [review]
lgtm

**Comment by migueldiascosta** [comment]
Going in, thanks @robert-mijakovic!

**Pull request merged**
