### PR TITLE
move Arb and polymake to gfbf/foss since FLINT is now at gfbf/foss

### PR DESCRIPTION
**Pull request by akesandgren**
(created using `eb --new-pr`)
Due to FLINT having moved up to gfbf/foss, we also need to move Arb and polymake in the same way.

Depends on ~~#17868~~

### CODE REVIEW

**Comment by akesandgren** [comment]
Replaces #17867
This is part 2 of 2

**Comment by jfgrimm** [comment]
Test report by @jfgrimm
**SUCCESS**
Build succeeded for 5 out of 5 (5 easyconfigs in total)
node135.pri.viking.alces.network - Linux CentOS Linux 7.9.2009, x86_64, Intel(R) Xeon(R) Gold 6138 CPU @ 2.00GHz (skylake_avx512), Python 3.6.8
See https://gist.github.com/jfgrimm/e8298e37c85e9327d967258ea66f610c for a full test report.

**Comment by akesandgren** [comment]
Test report by @akesandgren
**FAILED**
Build succeeded for 4 out of 5 (5 easyconfigs in total)
b-an02.hpc2n.umu.se - Linux Ubuntu 20.04, x86_64, Intel(R) Xeon(R) CPU E5-2690 v4 @ 2.60GHz, Python 3.8.10
See https://gist.github.com/akesandgren/ea0186775a34d129507f56b50b96fa66 for a full test report.

**Comment by akesandgren** [comment]
@boegelbot Please test @ jsc-zen2

**Comment by akesandgren** [comment]
Test report by @akesandgren
**SUCCESS**
Build succeeded for 6 out of 6 (5 easyconfigs in total)
b-an02.hpc2n.umu.se - Linux Ubuntu 20.04, x86_64, Intel(R) Xeon(R) CPU E5-2690 v4 @ 2.60GHz, Python 3.8.10
See https://gist.github.com/akesandgren/9d158efca38896a0f83ccfe0541a97da for a full test report.

**Comment by jfgrimm** [comment]
@boegelbot Please test @ generoso

**Comment by verdurin** [comment]
Test report by @verdurin
**SUCCESS**
Build succeeded for 6 out of 6 (5 easyconfigs in total)
easybuild-c7.novalocal - Linux CentOS Linux 7.9.2009, x86_64, Intel Xeon Processor (Skylake, IBRS), Python 3.6.8
See https://gist.github.com/verdurin/d7df4d66fb9e0617b2d025f48589268a for a full test report.

**Review by verdurin — APPROVED** [review]
Looks fine.

**Pull request merged**
