### PR TITLE
{bio,math}[intel/2017a] PHAST v1.4, CLAPACK v3.2.1

### PR DESCRIPTION
**Pull request by boegel**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in this PR)
node2044.delcatty.os - Linux centos linux 7.3.1611, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.7.5
See https://gist.github.com/2a9e184daabc3e988bf98fe211eb54ae for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in this PR)
node2439.golett.os - Linux centos linux 7.3.1611, Intel(R) Xeon(R) CPU E5-2680 v3 @ 2.50GHz, Python 2.7.5
See https://gist.github.com/41a495949f3f1a530e7941302fb1228b for a full test report.

**Comment by verdurin** [comment]
Test report by @verdurin
**FAILED**
Build succeeded for 0 out of 2 (2 easyconfigs in this PR)
ca005.camp.thecrick.org - Linux centos linux 7.3.1611, Intel(R) Xeon(R) CPU E5-2640 v3 @ 2.60GHz, Python 2.7.5
See https://gist.github.com/872c9f755664a0d32580bb3624a60407 for a full test report.

**Comment by boegel** [comment]
@verdurin Hmm...

```
./xeigtstz < nep.in > znep.out 2>&1
/bin/sh: line 1: 17036 Segmentation fault      ./xeigtstz < nep.in > znep.out 2>&1
make[1]: *** [znep.out] Error 139
make[1]: Leaving directory `/camp/apps/eb/review/software/CLAPACK/3.2.1-intel-2017a/TESTING'
make: *** [lapack_testing] Error 2
```

Any clues in the `znep.out` file?

**Comment by verdurin** [comment]
@boegel It's empty, I'm afraid.

**Comment by boegel** [comment]
@verdurin Can you show the output of `ulimit -a` on your end? I suspect there may be a limitation there that may cause this. Here's mine:

```
$ ulimit -a
core file size          (blocks, -c) 0
data seg size           (kbytes, -d) unlimited
scheduling priority             (-e) 0
file size               (blocks, -f) unlimited
pending signals                 (-i) 257452
max locked memory       (kbytes, -l) unlimited
max memory size         (kbytes, -m) unlimited
open files                      (-n) 1024
pipe size            (512 bytes, -p) 8
POSIX message queues     (bytes, -q) 819200
real-time priority              (-r) 0
stack size              (kbytes, -s) unlimited
cpu time               (seconds, -t) unlimited
max user processes              (-u) 4096
virtual memory          (kbytes, -v) unlimited
file locks                      (-x) unlimited

**Comment by verdurin** [comment]
@boegel 
```
[huffmaa@ca005 ~]$ ulimit -a
core file size          (blocks, -c) 0
data seg size           (kbytes, -d) unlimited
scheduling priority             (-e) 0
file size               (blocks, -f) unlimited
pending signals                 (-i) 1027662
max locked memory       (kbytes, -l) unlimited
max memory size         (kbytes, -m) unlimited
open files                      (-n) 100000
pipe size            (512 bytes, -p) 8
POSIX message queues     (bytes, -q) 819200
real-time priority              (-r) 0
stack size              (kbytes, -s) 8192
cpu time               (seconds, -t) unlimited
max user processes              (-u) 4096
virtual memory          (kbytes, -v) unlimited
file locks                      (-x) unlimited
```

**Comment by boegel** [comment]
@verdurin Can you try again after running `ulimit -s unlimited` in that session?

**Comment by wpoely86** [comment]
Test report by @wpoely86
**SUCCESS**
Build succeeded for 3 out of 3 (2 easyconfigs in this PR)
nic68 - Linux centos linux 7.3.1611, Intel(R) Xeon(R) CPU E5-2680 v4 @ 2.40GHz, Python 2.7.5
See https://gist.github.com/f2eddc4d7612551647ff3f817ca6e16b for a full test report.

**Comment by verdurin** [comment]
Test report by @verdurin
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in this PR)
ca005.camp.thecrick.org - Linux centos linux 7.3.1611, Intel(R) Xeon(R) CPU E5-2640 v3 @ 2.60GHz, Python 2.7.5
See https://gist.github.com/d57e42494b94cad16cb0e6006f7c5f9d for a full test report.

**Comment by verdurin** [comment]
Going in, thanks @boegel!

**Comment by boegel** [comment]
@verdurin So, using `ulimit -s unlimited` fixed the segfault on your end?

**Comment by verdurin** [comment]
@boegel yes, hence the successful test report.

**Comment by boegel** [comment]
@verdurin OK, thanks for clarifying!

**Pull request merged**
