### PR TITLE
{bio}[fosscuda/2020b] GROMACS v2021 w/ Python 3.8.6

### PR DESCRIPTION
**Pull request by akesandgren**
(created using `eb --new-pr`)
Requires ~~https://github.com/easybuilders/easybuild-easyblocks/pull/2353~~

### CODE REVIEW

**Comment by akesandgren** [comment]
Test report by @akesandgren
Using easyblocks from PR(s) https://github.com/easybuilders/easybuild-easyblocks/pull/2353
**FAILED**
Build succeeded for 0 out of 1 (1 easyconfigs in total)
b-cn1502.hpc2n.umu.se - Linux Ubuntu 20.04, x86_64, Intel(R) Xeon(R) Gold 6132 CPU @ 2.60GHz, Python 3.8.5
See https://gist.github.com/44620b3c9a1a3e251e76d641a3083564 for a full test report.

**Comment by akesandgren** [comment]
@boegelbot please test @ generoso EB_ARGS="--include-easyblocks-from-pr 2353"

**Comment by akesandgren** [comment]
Test report by @akesandgren
Using easyblocks from PR(s) https://github.com/easybuilders/easybuild-easyblocks/pull/2353
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
b-cn1502.hpc2n.umu.se - Linux Ubuntu 20.04, x86_64, Intel(R) Xeon(R) Gold 6132 CPU @ 2.60GHz, Python 3.8.5
See https://gist.github.com/f2674db29c5b2fef309c6fe80902bbb8 for a full test report.

**Comment by lexming** [comment]
Test report by @lexming
**FAILED**
Build succeeded for 2 out of 3 (1 easyconfigs in total)
node251.hydra.os - Linux centos linux 7.9.2009, x86_64, Intel(R) Xeon(R) CPU E5-2650 v4 @ 2.20GHz, Python 2.7.5
See https://gist.github.com/1a13cad9a5cfadbf02de18d6fca298a0 for a full test report.

**Comment by boegel** [comment]
@lexming Looks like you weren't using https://github.com/easybuilders/easybuild-easyblocks/pull/2353?

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
node3301.joltik.os - Linux centos linux 7.9.2009, x86_64, Intel(R) Xeon(R) Gold 6242 CPU @ 2.80GHz (cascadelake), Python 3.6.8
See https://gist.github.com/92905c65d91e7ff9904078e1bb6e17de for a full test report.

**Review by boegel — APPROVED** [review]
lgtm

**Comment by boegel** [comment]
Going in, thanks @akesandgren!

**Pull request merged**
