### PR TITLE
add extensions cubelyr and broom.mixed for R 4.1.0

### PR DESCRIPTION
**Pull request by smoors**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by smoors** [comment]
@boegelbot: please test @ generoso EB_ARGS="--skip --rebuild"

**Review by boegel — APPROVED** [review]
lgtm

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
node2643.swalot.os - Linux centos linux 7.9.2009, x86_64, Intel(R) Xeon(R) CPU E5-2660 v3 @ 2.60GHz (haswell), Python 3.6.8
See https://gist.github.com/c10cae532194a3b4995ee7eec2c7bc1a for a full test report.

**Comment by boegel** [comment]
Going in, thanks @smoors!

**Pull request merged**
