### PR TITLE
{perf}[GCCcore/10.3.0] CubeWriter v4.6, OPARI2 v2.0.6, PDT v3.25

### PR DESCRIPTION
**Pull request by stefan-wolfsheimer**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by robert-mijakovic** [comment]
@stefan-wolfsheimer There is also PDT 3.25.1. I guess it should be used instead of v3.25.

**Comment by verdurin** [comment]
@stefan-wolfsheimer welcome to EasyBuild and thanks for the contribution.

Do you have any thoughts on the comment above from @robert-mijakovic about a newer version?

**Comment by satishskamath** [comment]
> @stefan-wolfsheimer There is also PDT 3.25.1. I guess it should be used instead of v3.25.

PDT 3.25.1 was released 2 years later I agree with @robert-mijakovic .

**Comment by robert-mijakovic** [comment]
@stefan-wolfsheimer Thanks. Can you change the PR name to PDT 3.25.1?

**Comment by robert-mijakovic** [comment]
Test report by @robert-mijakovic
**SUCCESS**
Build succeeded for 3 out of 3 (3 easyconfigs in total)
login01.meluxina.lxp.lu - Linux RHEL 8.3, x86_64, AMD EPYC 7452 32-Core Processor (zen2), Python 3.6.8
See https://gist.github.com/1b7fa4ccfb9e8f7d1c211d971efe85fd for a full test report.

**Comment by robert-mijakovic** [comment]
@boegelbot please test @ generoso

**Comment by robert-mijakovic** [comment]
@boegelbot please test @ generoso

**Comment by robert-mijakovic** [comment]
lgtm @verdurin Can you check this one and approve it?

**Comment by verdurin** [comment]
Test report by @verdurin
**SUCCESS**
Build succeeded for 3 out of 3 (3 easyconfigs in total)
nuc.lan - Linux Fedora 33, x86_64, Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz, Python 3.9.5
See https://gist.github.com/3f2c038a46ce56ce2fc1217a3d4e881c for a full test report.

**Review by verdurin — APPROVED** [review]
Looks fine.

**Comment by verdurin** [comment]
Going in, thanks @stefan-wolfsheimer!

**Pull request merged**
