### PR TITLE
{vis}[GCCcore/11.3.0] GTK+ v3.24.34

### PR DESCRIPTION
**Pull request by Ghepardo**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by Micket** [comment]
I also made this mistake :) 
https://github.com/easybuilders/easybuild-easyconfigs/pull/16018

Replaced with `GTK3` (so that it can coexist with `GTK4`)

**Comment by Ghepardo** [comment]
Noted @Micket .  Will close.  
It'd be great if we could stick some sort of flag in the directories of deprecated or superseded modules.  Even just a README file would be a help.  Is there a process for requesting enhancements like that?

**Comment by Micket** [comment]
Yes I agree. I'll make a discussion note of this for the next bi-weekly meeting.

**Comment by Ghepardo** [comment]
Closing because GTK+ module has been superseded by GTK3 and GTK4 modules.

**Pull request closed without merging**
