### PR TITLE
{vis}[fosscuda/2019a] OpenCV v3.4.7 w/ Python 2.7.15 + 3.7.2

### PR DESCRIPTION
**Pull request by akesandgren**
(created using `eb --new-pr`)

Depends on ~~#9189~~

### CODE REVIEW

**Comment by akesandgren** [comment]
Test report by @akesandgren
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in this PR)
b-an03.hpc2n.umu.se - Linux ubuntu 16.04, Intel(R) Xeon(R) CPU E5-2690 v4 @ 2.60GHz, Python 2.7.12
See https://gist.github.com/e7b305144192197d940f19213c14c6d9 for a full test report.

**Comment by Micket** [comment]
kick travis

**Comment by Micket** [comment]
Test report by @Micket
**FAILED**
Build succeeded for 0 out of 2 (2 easyconfigs in this PR)
vera-c1 - Linux centos linux 7.7.1908, Intel Xeon Processor (Skylake), Python 2.7.5
See https://gist.github.com/27a5e5fde796559662b738fbbdd1b63b for a full test report.

**Comment by akesandgren** [comment]
@Micket what was the actual error?

**Comment by Micket** [comment]
Test report by @Micket
**FAILED**
Build succeeded for 0 out of 2 (2 easyconfigs in this PR)
vera-c1 - Linux centos linux 7.7.1908, Intel Xeon Processor (Skylake), Python 2.7.5
See https://gist.github.com/22525a0d3746348ff152de7e69d3867d for a full test report.

**Comment by Micket** [comment]
I thought it might be the nvidia drivers, so i updated them and tried again just in case:
```
/local/EB/build/OpenCV/3.4.7/fosscuda-2019a-Python-3.7.2/opencv-3.4.7/modules/cudacodec/src/precomp.hpp:60:18: fatal error: dynlink_nvcuvid.h: No such file or directory
```

**Comment by akesandgren** [comment]
It must be triggering
```
OCV_OPTION(WITH_NVCUVID "Include NVidia Video Decoding library support" WITH_CUDA
  VISIBLE_IF WITH_CUDA
  VERIFY HAVE_NVCUVID)
```
in your case.

**Comment by akesandgren** [comment]
Hmmmm, do you have CUDA 9.x installed from the OS? because if you do it might decide to find nvcuvid library from there and the set HAVE_NVCUVID = 1
causing failure during build

**Comment by Micket** [comment]
@akesandgren I have nvidia drivers installed on the machine that builds. I was under the false(?) impression that I needed the drivers themselves installed when building cuda stuff. 
Looks like the latest drivers do for el7 pulls in a lot of stuff though. `nvidia-driver-latest-dkms -> nvidia-drivers-latest-dkms-devel` installed a `/usr/lib64/libnvcucid.so`. I removed the drivers now (though, still, this is not good if people for example needs to build on a machine that does have a GPU?)

**Comment by Micket** [comment]
Test report by @Micket
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in this PR)
vera-c1 - Linux centos linux 7.7.1908, Intel Xeon Processor (Skylake), Python 2.7.5
See https://gist.github.com/18d525738d1106f95aeddec0dda27cdf for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**FAILED**
Build succeeded for 0 out of 2 (2 easyconfigs in this PR)
node3301.joltik.os - Linux centos linux 7.7.1908, Intel(R) Xeon(R) Gold 6242 CPU @ 2.80GHz, Python 2.7.5
See https://gist.github.com/b94619de8c6046927b582240b0cb2ee5 for a full test report.

**Comment by boegel** [comment]
I'm seeing the same issue that @Micket was seeing, on a GPU system...

**Comment by akesandgren** [comment]
Yeah, we'll probably have to figure out a way to make it only find the one from our CUDA.

**Comment by akesandgren** [comment]
A simple workaround is probably to explicitly turn it off, i.e. WITH_NVCUVID

**Comment by akesandgren** [comment]
Can you try again with
configopts = '-DWITH_NVCUVID=OFF '

**Comment by boegel** [comment]
@akesandgren That seems to do the trick, indeed, `OpenCV-3.4.7-fosscuda-2019a-Python-2.7.15.eb` installed fine with that included.

So, should we add that to the `OpenCV` easyblock?

**Comment by akesandgren** [comment]
Maybe, the thing is that on our Ubuntu build it picks up the correct lib from CUDA, which would make adding that a change to how it works...
I'll ponder this a while to see if I can make it find the one from CUDA only instead.

**Comment by akesandgren** [comment]
Hmmm....
The main problem here is that nvcuvid doesn't at all exist in CUDA 10 (which is used for fosscuda/2019a) so yet, we can definitely just turn it off.

**Comment by akesandgren** [comment]
@Micket , @boegel  Please try a new test report now.

**Comment by boegel** [comment]
Test report by @boegel
**FAILED**
Build succeeded for 0 out of 2 (2 easyconfigs in this PR)
node3305.joltik.os - Linux centos linux 7.7.1908, Intel(R) Xeon(R) Gold 6242 CPU @ 2.80GHz, Python 2.7.5
See https://gist.github.com/103db0353d72ce2418fbd1ebedb0db1e for a full test report.

**Comment by akesandgren** [comment]
Eh, what?? I have no problems on our skylakes

**Comment by akesandgren** [comment]
(And yes that configopts should be moved into the easyblock. but it's faster to test this way.)

**Comment by Micket** [comment]
Test report by @Micket
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in this PR)
vera-c1 - Linux centos linux 7.7.1908, Intel Xeon Processor (Skylake), Python 2.7.5
See https://gist.github.com/94fa012990c948b90d6251b62d1ecc80 for a full test report.

**Comment by akesandgren** [comment]
ok... so why does @boegels build fail?? Any ideas?

**Comment by Micket** [comment]
So, i previously uninstalled all the nvidia drivers, to see if it build without them, and since then just reinstalled the nvidia rpms again. 
But, it seems I installed the `nvidia-driver-latest-devel`, instead of `nvidia-driver-latest-dkms-devel`, and it turns out ths non-dkms package doesn't include `libnvucid.so`.

**Comment by akesandgren** [comment]
Shouldn't matter which one you install, since the current .eb disables nvcuvid
But please do test with the one that contains nvcuvid... although if it does it might be too old for CUDA 10.1.243. That CUDA (probably) requires nvidia driver 418.87 or later.

**Comment by akesandgren** [comment]
Ehum..... the nvcuvid library is available from the Ubuntu packaged nvidia-430 driver, but since there is no include file in that package my build of opencv doesn't find it.

**Comment by Micket** [comment]
Test report by @Micket
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in this PR)
vera-c1 - Linux centos linux 7.7.1908, Intel Xeon Processor (Skylake), Python 2.7.5
See https://gist.github.com/14a890365e9329d16fd80e268bd26a58 for a full test report.

**Comment by boegel** [comment]
@akesandgren Our GPU cluster is Cascade Lake rather than Skylake.

See also https://github.com/opencv/opencv/issues/15501 + fix in https://github.com/opencv/opencv/pull/15646

**Comment by boegel** [comment]
@akesandgren The problem is fixed on our Cascade Lake system with the patch included in https://github.com/akesandgren/easybuild-easyconfigs/pull/13

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in this PR)
node3303.joltik.os - Linux centos linux 7.7.1908, Intel(R) Xeon(R) Gold 6242 CPU @ 2.80GHz, Python 2.7.5
See https://gist.github.com/3b1c41161a0d33cda73e576479042354 for a full test report.

**Comment by Micket** [comment]
Test report by @Micket
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in this PR)
vera-c1 - Linux centos linux 7.7.1908, Intel Xeon Processor (Skylake), Python 2.7.5
See https://gist.github.com/addb859f76c594cd83382f38a73a2647 for a full test report.

**Comment by boegel** [comment]
Going in, thanks @akesandgren!

**Pull request merged**
