### PR TITLE
{data,tools,vis}[foss/2020b] scikit-image v0.18.1, dask v2021.2.0, bokeh v2.2.3 w/ Python 3.8.6

### PR DESCRIPTION
**Pull request by boegel**
(created using `eb --new-pr`)

### CODE REVIEW

**Review by Micket — APPROVED** [review]
lgtm

**Comment by Micket** [comment]
Test report by @Micket
**SUCCESS**
Build succeeded for 5 out of 5 (3 easyconfigs in total)
vera-c1 - Linux centos linux 7.9.2009, x86_64, Intel Xeon Processor (Skylake), Python 2.7.5
See https://gist.github.com/57f507f91ba5626c2916fabe174fb7c7 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 3 out of 3 (3 easyconfigs in total)
node2637.swalot.os - Linux centos linux 7.9.2009, x86_64, Intel(R) Xeon(R) CPU E5-2660 v3 @ 2.60GHz (haswell), Python 3.6.8
See https://gist.github.com/91334329ed8132314ba6248852fd9b26 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**FAILED**
Build succeeded for 2 out of 3 (3 easyconfigs in total)
node3573.doduo.os - Linux RHEL 8.2, x86_64, AMD EPYC 7552 48-Core Processor (zen2), Python 3.6.8
See https://gist.github.com/c10d885adf3a62a531d87de57ce0cf3e for a full test report.

**Comment by boegel** [comment]
Last test report failing during sanity check:

```
failing sanity check for 'scikit-image' extension: command "python -c "import skimage"" failed; output:
...
PermissionError: [Errno 13] Permission denied: '/user/gent/400/vsc40023/.cache/scikit-image/0.18.1/data/README.txt'
```

It seems like an `import skimage` triggers `scikit-image` to try and create `$HOME/.cache/scikit-image/<version>/data`, and then it trips over having that already there?! What the...

**Comment by boegel** [comment]
Ah, look, somebody opened a PR to fix that exact issue just 15min ago!
https://github.com/scikit-image/scikit-image/pull/5249

The problem occurred because I was installing `scikit-image` with EasyBuild being configured with `--read-only-installdir`. Hence, the `README.txt` that gets copied from the installation directory to `$HOME/.cache/scikit-image` also has read-only permissions... 🤦

**Comment by boegel** [comment]
Hmm, this is very very similar to #12116, it's probably better to get that one merged instead...

**Comment by boegel** [comment]
When #12116 gets merged, this PR should get merged automatically (since I collapsed my branch into the branch used by #12116).

**Pull request merged**
