### PR TITLE
{data}[intel/2017a] xarray v0.9.6

### PR DESCRIPTION
**Pull request by boegel**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
node2451.golett.os - Linux centos linux 7.3.1611, Intel(R) Xeon(R) CPU E5-2680 v3 @ 2.50GHz, Python 2.7.5
See https://gist.github.com/448966e58a31d3ffb86a17b19c32741e for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
node2115.delcatty.os - Linux centos linux 7.3.1611, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.7.5
See https://gist.github.com/fc7b869062724da9987932c1105cd59e for a full test report.

**Comment by boegel** [comment]
@easybuilders/easybuild-easyconfigs-maintainers Please review (trivial version bump)

**Comment by vanzod** [comment]
Going in, thanks @boegel!

**Pull request merged**
