### PR TITLE
{numlib}[foss/2022a] Trilinos v13.4.1 w/ Python 3.10.4 Zoltan-F90-API

### PR DESCRIPTION
**Pull request by sassy-crick**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by sassy-crick** [comment]
@boegelbot please test @ generoso

**Comment by sassy-crick** [comment]
Whilst trying to build [fluidity](https://github.com/FluidityProject/fluidity) I noticed I need zoltan for it and the Zoltan homepage suggested to use the Trilinos-package as that version is more up-to-date. However, for the compilation of fluidity `zoltan.mod` is needed and this EC adds the F90 interface, and for good measure I added `ParMETIS` as well.

**Comment by smoors** [comment]
@boegelbot please test @ jsc-zen2

**Comment by smoors** [comment]
@boegelbot please test @ jsc-zen2

**Review by smoors — APPROVED** [review]
lgtm

**Comment by smoors** [comment]
Going in, thanks @sassy-crick!

**Pull request merged**
