### PR TITLE
{bio}[foss/2018b] FMRIprep v1.1.8, C3D v1.0.0, ICA-AROMA v0.4.4-beta

### PR DESCRIPTION
**Pull request by boegel**
(created using `eb --new-pr`)
requires ~~https://github.com/easybuilders/easybuild-easyblocks/pull/1553~~ + #6998 (ANTs), ~~#6999~~ (scikit-learn), ~~#7000~~ (scikit-image), ~~#7001~~ (Nipype), ~~#7002~~ (Seaborn), ~~#7045~~ (FSL), ~~#7058~~ (AFNI)

### CODE REVIEW

**Comment by vanzod** [comment]
Re-trigger Travis after having merged #7058

**Comment by boegel** [comment]
@vanzod Still requires #6998, that has been blocked due to strange permission issues I haven't been able to figure out yet...

**Comment by vanzod** [comment]
Re-trigger Travis after merging #6998

**Comment by vanzod** [comment]
Test report by @vanzod
**SUCCESS**
Build succeeded for 16 out of 16 (3 easyconfigs in this PR)
cermis - Linux debian 9.6, Intel(R) Xeon(R) CPU           E5620  @ 2.40GHz, Python 2.7.13
See https://gist.github.com/e66f55ec382f3f9ea1e4460d5c509c1c for a full test report.

**Comment by vanzod** [comment]
Going in, thanks @boegel!

**Pull request merged**
