### PR TITLE
{data}[GCCcore/11.3.0] SoX w/ GCCcore/11.3.0 - add MAD support

### PR DESCRIPTION
**Pull request by anselmicz**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by anselmicz** [comment]
Test report by @anselmicz
**SUCCESS**
Build succeeded for 0 out of 0 (1 easyconfigs in total)
login1.barbora.it4i.cz - Linux RHEL 8.4, x86_64, Intel(R) Xeon(R) Gold 6240 CPU @ 2.60GHz (cascadelake), Python 3.6.8
See https://gist.github.com/83f7e1e5f6ce999e441f30d93c690f14 for a full test report.

**Comment by anselmicz** [comment]
Test report by @anselmicz
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
login1.barbora.it4i.cz - Linux RHEL 8.4, x86_64, Intel(R) Xeon(R) Gold 6240 CPU @ 2.60GHz (cascadelake), Python 3.6.8
See https://gist.github.com/b49132faf0a617d7c211a508e133ed44 for a full test report.

**Comment by branfosj** [comment]
@boegelbot please test @ jsc-zen2

**Comment by branfosj** [comment]
Test report by @branfosj
**SUCCESS**
Build succeeded for 3 out of 3 (1 easyconfigs in total)
bear-pg0105u36b.bear.cluster - Linux RHEL 8.5, x86_64, Intel(R) Xeon(R) Platinum 8360Y CPU @ 2.40GHz (icelake), Python 3.6.8
See https://gist.github.com/9bf65bc33a397f2fe9ac1722f22484d9 for a full test report.

**Review by branfosj — APPROVED** [review]

**Comment by branfosj** [comment]
Going in, thanks @anselmicz!

**Pull request merged**
