### PR TITLE
add missing pkgconf build dependency for XML-LibXML v2.0208

### LINKED ISSUE #18165: XML-LibXML-2.0208-GCCcore-12.2.0.eb
It does not build with Ubuntu, missing builddependencies pkgconf

### PR DESCRIPTION
**Pull request by fizwit**
(created using `eb --new-pr`)

fixes #18165

### CODE REVIEW

**Comment by smoors** [comment]
@fizwit can you give a bit more info?
also, i cannot find the issue, is the link correct?

**Comment by boegel** [comment]
similar to #18007

issue being referred to is https://github.com/easybuilders/easybuild-framework/issues/4282, which should be moved to easyconfigs repo

**Comment by boegel** [comment]
@boegelbot please test @ jsc-zen2

**Review by boegel — APPROVED** [review]
lgtm

**Comment by boegel** [comment]
Going in, thanks @fizwit!

**Pull request merged**
