### PR TITLE
only use libxsmm as dependency for CP2K 2023.1 on x86_64

### PR DESCRIPTION
**Pull request by laraPPr**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by laraPPr** [comment]
Testing in EESSI/software-layer https://github.com/EESSI/software-layer/pull/630

**Comment by laraPPr** [comment]
@boegelbot please test @ jsc-zen2
CORE_CNT=16

**Comment by laraPPr** [comment]
Test report by @laraPPr
**FAILED**
Build succeeded for 0 out of 1 (1 easyconfigs in total)
node4011.donphan.os - Linux RHEL 8.8 (Ootpa), x86_64, Intel(R) Xeon(R) Gold 6240 CPU @ 2.60GHz, 1 x NVIDIA NVIDIA A2, 545.23.08, Python 3.11.3
See https://gist.github.com/laraPPr/550254e5deaf459701a2fd3d8748b9d4 for a full test report.

**Comment by boegel** [comment]
@laraPPr I've just cancelled job 13885, it has only done ~15% of the test suite in ~24h, so we'll need to resubmit the test build asking for more cores (using `CORE_CNT=16` as 2nd line in comment to request test report from the bot)

**Comment by laraPPr** [comment]
@boegelbot please test @ jsc-zen2
CORE_CNT=16

**Comment by laraPPr** [comment]
@boegelbot please test @ jsc-zen2
CORE_CNT=16

**Comment by laraPPr** [comment]
@boegelbot please test @ generoso
CORE_CNT=16

**Comment by laraPPr** [comment]
@boegelbot please test @ generoso
CORE_CNT=16

**Comment by laraPPr** [comment]
Test report by @laraPPr
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
node4011.donphan.os - Linux RHEL 8.8 (Ootpa), x86_64, Intel(R) Xeon(R) Gold 6240 CPU @ 2.60GHz, 1 x NVIDIA NVIDIA A2, 545.23.08, Python 3.11.3
See https://gist.github.com/laraPPr/1eefc4a6bc74993fcb06a29a10758717 for a full test report.

**Review by boegel — APPROVED** [review]

**Comment by boegel** [comment]
Going in, thanks @laraPPr!

**Pull request merged**
