### PR TITLE
{lib,tools}[GCCcore/8.3.0] NCO v4.9.3, libtirpc v1.2.6, libdap v3.20.6, ...

### PR DESCRIPTION
**Pull request by tstrempel**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by tstrempel** [comment]
@boegel How I'm supposed to handle this?

If I'm specifing Java 1.8, it fails because there are EasyConfigs with Java 11 in the same toolchain generation. But if I'm using Java 11 it fails too, because there are other EasyCOnfigs with Java 1.8 in the same toolchain generation.

**Comment by lexming** [comment]
Test report by @lexming
**SUCCESS**
Build succeeded for 4 out of 4 (4 easyconfigs in this PR)
node368.hydra.os - Linux centos linux 7.7.1908, x86_64, Intel(R) Xeon(R) Gold 6148 CPU @ 2.40GHz, Python 2.7.5
See https://gist.github.com/36546850b7a9ed7e06895b2c9bc71bcf for a full test report.

**Comment by lexming** [comment]
Test report by @lexming
**SUCCESS**
Build succeeded for 4 out of 4 (4 easyconfigs in this PR)
node111.hydra.os - Linux centos linux 7.7.1908, x86_64, Intel(R) Xeon(R) CPU E5-2680 v2 @ 2.80GHz, Python 2.7.5
See https://gist.github.com/efad1e7f309be6e254ba6e0d1f133e2d for a full test report.

**Review by lexming — APPROVED** [review]
`NCO` is going down to `gompi` toolchain as it does not need BLAS/LAPACK.

LGTM

**Comment by lexming** [comment]
Going in, thanks @tstrempel !

**Pull request merged**
