### PR TITLE
Use pip to install h5py 2.10.0

### PR DESCRIPTION
**Pull request by Flamefire**
(created using `eb --new-pr`)
 see https://github.com/easybuilders/easybuild-easyconfigs/issues/11042

### CODE REVIEW

**Comment by Flamefire** [comment]
Test report by @Flamefire
**FAILED**
Build succeeded for 16 out of 83 (6 easyconfigs in this PR)
taurusml29 - Linux RHEL 7.6, POWER, 8335-GTX, Python 2.7.5
See https://gist.github.com/e4ca5f6585ba1352896f45c54a1d8e37 for a full test report.

**Comment by Flamefire** [comment]
Test report by @Flamefire
**FAILED**
Build succeeded for 32 out of 40 (6 easyconfigs in this PR)
taurusi5278.taurus.hrsk.tu-dresden.de - Linux RHEL 7.8, x86_64, Intel(R) Xeon(R) CPU E5-2680 v3 @ 2.50GHz, Python 2.7.5
See https://gist.github.com/8b13a8781086515b29b5172425b617ad for a full test report.

**Comment by Flamefire** [comment]
I could add test reports from Power if I could skip the intel toolchains there as they won't install on Power. Is that possible?

**Comment by Flamefire** [comment]
Test report by @Flamefire
**SUCCESS**
Build succeeded for 8 out of 8 (6 easyconfigs in this PR)
taurusi4248.taurus.hrsk.tu-dresden.de - Linux RHEL 7.8, x86_64, Intel(R) Xeon(R) CPU E5-2680 v4 @ 2.40GHz, Python 2.7.5
See https://gist.github.com/b6c26fc801d55a44e7ac367b4d342b2f for a full test report.

**Comment by boegel** [comment]
> I could add test reports from Power if I could skip the intel toolchains there as they won't install on Power. Is that possible?

Yes, you can specify specific easyconfigs to test with, for example:

```
eb --from-pr 11044 h5py-2.10.0-foss-2019b-Python-3.7.4.eb  h5py-2.10.0-foss-2020a-Python-3.8.2.eb  h5py-2.10.0-fosscuda-2019b-Python-3.7.4.eb
```

**Comment by boegel** [comment]
@boegelbot please test @ generoso

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 6 out of 6 (6 easyconfigs in this PR)
node3401.kirlia.os - Linux centos linux 7.8.2003, x86_64, Intel(R) Xeon(R) Gold 6240 CPU @ 2.60GHz (cascadelake), Python 2.7.5
See https://gist.github.com/745a72f46b93107925605087fe605516 for a full test report.

**Comment by smoors** [comment]
Test report by @smoors
**SUCCESS**
Build succeeded for 15 out of 15 (6 easyconfigs in this PR)
node375.hydra.os - Linux centos linux 7.7.1908, x86_64, Intel(R) Xeon(R) Gold 6148 CPU @ 2.40GHz (skylake_avx512), Python 2.7.5
See https://gist.github.com/9f85e95e93bbc601e5f5a57711250c5b for a full test report.

**Comment by smoors** [comment]
Going in, thanks @Flamefire!

**Pull request merged**
