### PR TITLE
{tools}[system] irodsfs v0.8.9, v0.8.11, v0.8.12

### PR DESCRIPTION
**Pull request by ll4strw**
I am just adding easyconfig files for irodsfs (https://github.com/cyverse/irodsfs/)

### CODE REVIEW

**Comment by jfgrimm** [comment]
Test report by @jfgrimm
**SUCCESS**
Build succeeded for 3 out of 3 (3 easyconfigs in total)
login2.pri.viking.alces.network - Linux CentOS Linux 7.9.2009, x86_64, Intel(R) Xeon(R) Gold 6138 CPU @ 2.00GHz (skylake_avx512), Python 3.6.8
See https://gist.github.com/f5e76496917ace468fbffb0e1fcef6dc for a full test report.

**Review by boegel — APPROVED** [review]
lgtm

**Comment by boegel** [comment]
@boegelbot please test @ generoso

**Comment by boegel** [comment]
Going in, thanks @ll4strw!

**Pull request merged**
