### PR TITLE
fix RepeatMasker-4.1.2-p1 easyconfig by moving the database configure command to postinstallcmds

### PR DESCRIPTION
**Pull request by boegel**
wrapper PR for #15280 by @wdlingit which fixes the trivial code style issues that were introduced

### CODE REVIEW

**Comment by boegel** [comment]
@boegelbot please test @ generoso

**Comment by boegel** [comment]
Hmm, `pkgconf` produces a non-zero exit code if a package is not installed, while `pkg-config` does not...

```
$ module load pkg-config/0.29.2
$ pkg-config --print-requires libcrypto
$ echo $?
0
```
```
$ ml pkgconf/1.8.0
$ pkg-config --print-requires libcrypto
$ echo $?
1
```

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
node3108.skitty.os - Linux RHEL 8.4, x86_64, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz, Python 3.6.8
See https://gist.github.com/b10ed6edbe570671713e1b7731f1c575 for a full test report.

**Review by Micket — APPROVED** [review]
lgtm

**Comment by Micket** [comment]
Going in, thanks @boegel!

**Pull request merged**
