### PR TITLE
bio}[intel/2018b] HDDM v0.6.1 w/ Python 3.6.6

### PR DESCRIPTION
**Pull request by boegel**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
node3156.skitty.os - Linux centos linux 7.6.1810, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz, Python 2.7.5
See https://gist.github.com/d9261b54eab5783c65f1f053091d5dcf for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
node2532.golett.os - Linux centos linux 7.5.1804, Intel(R) Xeon(R) CPU E5-2680 v3 @ 2.50GHz, Python 2.7.5
See https://gist.github.com/7c5ba59475aced9e6da92d27a3557634 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**FAILED**
Build succeeded for 0 out of 4 (1 easyconfigs in this PR)
node2034.delcatty.os - Linux centos linux 7.6.1810, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.7.5
See https://gist.github.com/7e71759481a750e545f6e17d7b4c0885 for a full test report.

**Comment by verdurin** [comment]
```
== 2019-01-10 22:29:22,959 build_log.py:162 ERROR EasyBuild crashed with an error (at ?:124 in __init__): cmd " /well/rescomp/eb/software/Python/3.6.6-intel-2018b/bin/python setup.py build " exited with exit code 1 and output:
running build
running config_cc
unifing config_cc, config, build_clib, build_ext, build commands --compiler options
running config_fc
unifing config_fc, config, build_clib, build_ext, build commands --fcompiler options
running build_src
build_src
building extension "pymc.flib" sources
f2py options: ['skip:ppnd7']
f2py:> build/src.linux-x86_64-3.6/pymc/flibmodule.c
creating build
creating build/src.linux-x86_64-3.6
creating build/src.linux-x86_64-3.6/pymc
IOError: [Errno 2] No such file or directory: 'skip:ppnd7'. Skipping file "skip:ppnd7".
updatevars:gradlike: attempt to change 'dimension(nx)' to 'dimension(na)'. Ignoring.
updatevars:gradlike: attempt to change 'dimension(nx)' to 'dimension(nb)'. Ignoring.
updatevars:gradlike: attempt to change 'dimension (nmu)' to 'dimension(nmu)'. Ignoring.
updatevars:gradlike: attempt to change 'dimension (na)' to 'dimension(na)'. Ignoring.
Reading fortran codes...
        Reading file 'pymc/flib.f' (format:fix,strict)
Traceback (most recent call last):
  File "setup.py", line 167, in <module>
    setup_pymc()
  File "setup.py", line 164, in setup_pymc
    **(config_dict))
  File "/well/rescomp/eb/software/Python/3.6.6-intel-2018b/lib/python3.6/site-packages/numpy-1.15.0-py3.6-linux-x86_64.egg/numpy/distutils/core.py", line 169, in setup
    return old_setup(**new_attr)
  File "/well/rescomp/eb/software/Python/3.6.6-intel-2018b/lib/python3.6/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/well/rescomp/eb/software/Python/3.6.6-intel-2018b/lib/python3.6/distutils/dist.py", line 955, in run_commands
    self.run_command(cmd)
  File "/well/rescomp/eb/software/Python/3.6.6-intel-2018b/lib/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/well/rescomp/eb/software/Python/3.6.6-intel-2018b/lib/python3.6/site-packages/numpy-1.15.0-py3.6-linux-x86_64.egg/numpy/distutils/command/build.py", line 47, in run
    old_build.run(self)
  File "/well/rescomp/eb/software/Python/3.6.6-intel-2018b/lib/python3.6/distutils/command/build.py", line 135, in run
    self.run_command(cmd_name)
  File "/well/rescomp/eb/software/Python/3.6.6-intel-2018b/lib/python3.6/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/well/rescomp/eb/software/Python/3.6.6-intel-2018b/lib/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/well/rescomp/eb/software/Python/3.6.6-intel-2018b/lib/python3.6/site-packages/numpy-1.15.0-py3.6-linux-x86_64.egg/numpy/distutils/command/build_src.py", line 148, in run
    self.build_sources()
  File "/well/rescomp/eb/software/Python/3.6.6-intel-2018b/lib/python3.6/site-packages/numpy-1.15.0-py3.6-linux-x86_64.egg/numpy/distutils/command/build_src.py", line 165, in build_sources
    self.build_extension_sources(ext)
  File "/well/rescomp/eb/software/Python/3.6.6-intel-2018b/lib/python3.6/site-packages/numpy-1.15.0-py3.6-linux-x86_64.egg/numpy/distutils/command/build_src.py", line 327, in build_extension_sources
    sources = self.f2py_sources(sources, ext)
  File "/well/rescomp/eb/software/Python/3.6.6-intel-2018b/lib/python3.6/site-packages/numpy-1.15.0-py3.6-linux-x86_64.egg/numpy/distutils/command/build_src.py", line 564, in f2py_sources
    ['-m', ext_name]+f_sources)
  File "/well/rescomp/eb/software/Python/3.6.6-intel-2018b/lib/python3.6/site-packages/numpy-1.15.0-py3.6-linux-x86_64.egg/numpy/f2py/f2py2e.py", line 408, in run_main
    postlist = callcrackfortran(files, options)
  File "/well/rescomp/eb/software/Python/3.6.6-intel-2018b/lib/python3.6/site-packages/numpy-1.15.0-py3.6-linux-x86_64.egg/numpy/f2py/f2py2e.py", line 329, in callcrackfortran
    postlist = crackfortran.crackfortran(files)
  File "/well/rescomp/eb/software/Python/3.6.6-intel-2018b/lib/python3.6/site-packages/numpy-1.15.0-py3.6-linux-x86_64.egg/numpy/f2py/crackfortran.py", line 3246, in crackfortran
    readfortrancode(files, crackline)
  File "/well/rescomp/eb/software/Python/3.6.6-intel-2018b/lib/python3.6/site-packages/numpy-1.15.0-py3.6-linux-x86_64.egg/numpy/f2py/crackfortran.py", line 363, in readfortrancode
    l = fin.readline()
  File "/well/rescomp/eb/software/Python/3.6.6-intel-2018b/lib/python3.6/fileinput.py", line 299, in readline
    line = self._readline()
  File "/well/rescomp/eb/software/Python/3.6.6-intel-2018b/lib/python3.6/encodings/ascii.py", line 26, in decode
    return codecs.ascii_decode(input, self.errors)[0]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xce in position 5497: ordinal not in range(128)
 (at easybuild/tools/run.py:501 in parse_cmd_output)
```

**Comment by vanzod** [comment]
Test report by @vanzod
**SUCCESS**
Build succeeded for 3 out of 3 (1 easyconfigs in this PR)
cermis - Linux debian 9.6, Intel(R) Xeon(R) CPU           E5620  @ 2.40GHz, Python 2.7.13
See https://gist.github.com/243e47c04ffa78e51bf1f2b3da7cb2e2 for a full test report.

**Comment by vanzod** [comment]
Going in, thanks @boegel!

**Pull request merged**
