### PR TITLE
{lang}[system} Java/8 (OpenJDK)

### PR DESCRIPTION
**Pull request by Micket**
(created using `eb --new-pr`)
Briefly discussed in the last zoom meeting; how about just getting rid of oracle java for 8 as well, since it seems we never stop updating it..

### CODE REVIEW

**Comment by Micket** [comment]
Things got so ugly with the mess of version strings i just went for what they use upstream.

But.. i'm not sure what we should do with the modulerc wrapper things. I just made both variants.

**Comment by Micket** [comment]
So, other maintainers (or anyone else): Please have write your opinions on the naming of these.

**Comment by branfosj** [comment]
I'm happy to go with the `8u345` for the version. I am wondering if we should leave the 1.8 wrapper as Oracle Java and use the 8 wrapper for the OpenJDK variant.

**Comment by Micket** [comment]
Test report by @Micket
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in total)
alvis-c1 - Linux Rocky Linux 8.5, x86_64, Intel Xeon Processor (Skylake), Python 3.6.8
See https://gist.github.com/8fb8175903675a698a1c68a721d29003 for a full test report.

**Comment by boegel** [comment]
@boegelbot please test @ generoso

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in total)
easybuild2.novalocal - Linux CentOS Stream 8, POWER, IBM pSeries (emulated by qemu) (power9le), Python 3.6.8
See https://gist.github.com/af24ef641989de89cb2a5218a702deb4 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in total)
fair-mastodon-c6g-2xlarge-0001 - Linux Rocky Linux 8.5, AArch64, ARM UNKNOWN (graviton2), Python 3.6.8
See https://gist.github.com/c2b1c83a475675d3986a8a84863afafc for a full test report.

**Comment by boegel** [comment]
Going in, thanks @Micket!

**Pull request merged**
