### PR TITLE
{tools}[GCCcore/9.3.0] parallel v20200422

### PR DESCRIPTION
**Pull request by smoors**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by smoors** [comment]
Test report by @smoors
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
node351.hydra.os - Linux centos linux 7.7.1908, x86_64, Intel(R) Xeon(R) Gold 6148 CPU @ 2.40GHz (skylake_avx512), Python 2.7.5
See https://gist.github.com/175fc4fd032dd5ce2789dbe34ae8cd4b for a full test report.

**Comment by Micket** [comment]
re-trigger travis

**Comment by Micket** [comment]
Test report by @Micket
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
hebbe-c1 - Linux centos linux 7.7.1908, Intel Core Processor (Haswell, no TSX), Python 2.7.5
See https://gist.github.com/ac0e4c1ccfec4fe31e0745e69ef771c3 for a full test report.

**Comment by Micket** [comment]
Going in, thanks @smoors!

**Pull request merged**
