### PR TITLE
PyTorch 1.4.0 : Added ibverbs dependencies via constants.

### PR DESCRIPTION
**Pull request by terjekv**
(created using `eb --new-pr`)

Requires ~~https://github.com/easybuilders/easybuild-framework/pull/3309~~

### CODE REVIEW

**Comment by terjekv** [comment]
`Found printed messages in output of test suite\nERROR: test_easyconfig_constants (test.framework.easyconfigparser.EasyConfigParserTest)
File "/tmp/681175494/lib/python2.7/site-packages/easybuild_framework-4.2.1.dev0-py2.7.egg/test/framework/easyconfigparser.py", line 187, in test_easyconfig_constants
self.assertTrue(isinstance(val, (string_type, dict)), "Constant value %s is a string or dict" % val)`

Is this to say that the test of constants in the framework testing script does not allow constants to be lists? If so, that's awkward. It can be wrapped into a dict and then unpacked at some stage, but that just seems wrong.

**Comment by smoors** [comment]
Test report by @smoors
**FAILED**
Build succeeded for 0 out of 2 (2 easyconfigs in this PR)
node314.hydra.os - Linux centos linux 7.7.1908, x86_64, Intel(R) Xeon(R) Gold 6148 CPU @ 2.40GHz (skylake_avx512), Python 2.7.5
See https://gist.github.com/79e3b231b7378e95d8356403416ca668 for a full test report.

**Comment by smoors** [comment]
(out of memory)

**Comment by terjekv** [comment]
> (out of memory)

Ah, the joys of machine learning.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in this PR)
node3300.joltik.os - Linux centos linux 7.7.1908, x86_64, Intel(R) Xeon(R) Gold 6242 CPU @ 2.80GHz (cascadelake), Python 3.6.8
See https://gist.github.com/be27e1367f98fb94826a81d2c5619b64 for a full test report.

**Comment by boegel** [comment]
Going in, thanks @terjekv!

**Pull request merged**
