### PR TITLE
{lang}[foss/2019a,intel/2019a] Amara v1.2.0.2 w/ Python 2.7.15

### PR DESCRIPTION
**Pull request by boegel**

### CODE REVIEW

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
generoso - Linux centos linux 7.6.1810, Intel(R) Xeon(R) CPU E5-2660 v4 @ 2.00GHz, Python 3.6.8
See https://gist.github.com/2172a15f3570ea79fc775122a7c0b29e for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in this PR)
node2595.golett.os - Linux centos linux 7.7.1908, Intel(R) Xeon(R) CPU E5-2680 v3 @ 2.50GHz, Python 2.7.5
See https://gist.github.com/8abfd35d556240f2caa0ab9f43056c6f for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in this PR)
node2595.golett.os - Linux centos linux 7.7.1908, Intel(R) Xeon(R) CPU E5-2680 v3 @ 2.50GHz, Python 2.7.5
See https://gist.github.com/055cd0c0e4f135928557be66f3a8c03c for a full test report.

**Comment by migueldiascosta** [comment]
Test report by @migueldiascosta
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in this PR)
sms - Linux centos linux 7.6.1810, AMD EPYC 7601 32-Core Processor, Python 2.7.5
See https://gist.github.com/055a1c899684e3148e49230120965ac4 for a full test report.

**Comment by migueldiascosta** [comment]
@boegel, this PR is being closed for the following reason(s): closing and reopening to trigger tests.

**Comment by boegel** [comment]
@migueldiascosta Re-triggering tests by close/re-open doesn't work with GitHub CI currently, you'll just spawn another series of tests, and the broken one(s) will stay there.

I'm not sure we can fix this, but we should look into it (see also https://github.community/t5/GitHub-Actions/discarding-old-CI-runs-for-a-commit/m-p/39063#M3647)

**Comment by boegel** [comment]
I've "refreshed" the last commit using `git commit --amend` && `git push --force` (without making any changes), which re-triggers the tests (since it's a different commit that replaces the last commit in this PR).

Another way is to add a merge commit using `eb --sync-pr-with-develop` (see https://github.com/easybuilders/easybuild-framework/pull/3087)

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in this PR)
node3124.skitty.os - Linux centos linux 7.7.1908, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz, Python 3.6.8
See https://gist.github.com/50c23cd2012eabacbbffbee12db502dd for a full test report.

**Comment by migueldiascosta** [comment]
Going in, thanks @boegel!

**Pull request merged**
