### PR TITLE
{lib}[GCCcore/12.3.0] tbb v2021.11.0

### PR DESCRIPTION
**Pull request by smoors**
(created using `eb --new-pr`)

Supersedes https://github.com/easybuilders/easybuild-easyconfigs/pull/18747

### CODE REVIEW

**Comment by smoors** [comment]
@boegelbot: please test @ generoso

**Comment by smoors** [comment]
@boegelbot please test @ jsc-zen2

**Review by lexming — APPROVED** [review]
LGTM

**Comment by lexming** [comment]
Merged, thanks @smoors !

**Pull request merged**
