### PR TITLE
{tools}[foss/2020a,foss/2020b] eccodes-python v1.0.0, eccodes-python v1.1.0 w/ Python 3.8.2 + 3.8.6

### PR DESCRIPTION
**Pull request by lexming**
(created using `eb --new-pr`)

Depends on ~~https://github.com/easybuilders/easybuild-easyconfigs/pull/12082~~

### CODE REVIEW

**Comment by smoors** [comment]
@boegelbot: please test @ generoso

**Comment by lexming** [comment]
Test report by @lexming
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in total)
node381.hydra.os - Linux centos linux 7.9.2009, x86_64, Intel(R) Xeon(R) Gold 6148 CPU @ 2.40GHz, Python 2.7.5
See https://gist.github.com/a99d6299f747097aa84ef87bfe0cd268 for a full test report.

**Comment by smoors** [comment]
Test report by @smoors
**SUCCESS**
Build succeeded for 10 out of 10 (2 easyconfigs in total)
node364.hydra.os - Linux centos linux 7.9.2009, x86_64, Intel(R) Xeon(R) Gold 6148 CPU @ 2.40GHz (skylake_avx512), Python 2.7.5
See https://gist.github.com/484884c7099771f2d3937e7f067a9a4a for a full test report.

**Review by smoors — APPROVED** [review]
lgtm

**Comment by smoors** [comment]
Going in, thanks @lexming!

**Pull request merged**
