### PR TITLE
{bio}[gompi/2021b] BLAST+ v2.12.0

### PR DESCRIPTION
**Pull request by ItIsI-Orient**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by ItIsI-Orient** [comment]
Test report by @ItIsI-Orient
**SUCCESS**
Build succeeded for 0 out of 0 (1 easyconfigs in total)
node3210.victini.os - Linux centos linux 7.9.2009, x86_64, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz, Python 3.6.8
See https://gist.github.com/9a8600d0951b961deb8b383f0a5f21b1 for a full test report.

**Comment by ItIsI-Orient** [comment]
Test report by @ItIsI-Orient
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
node3210.victini.os - Linux centos linux 7.9.2009, x86_64, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz, Python 3.6.8
See https://gist.github.com/2f4d4565d085aa30f4734482b6b4df4c for a full test report.

**Review by boegel — CHANGES_REQUESTED** [review]
@ItIsI-Orient It looks like the `toolchainopts` line was removed, can you please restore it (since it affects which Boost libraries get installed):

```python
toolchainopts = {'usempi': True, 'pic': True}
```

**Comment by SethosII** [comment]
@ItIsI-Orient Version 2.12.0 is available: https://www.ncbi.nlm.nih.gov/books/NBK131777/. Can you update it to this version?

**Comment by ItIsI-Orient** [comment]
@SethosII Done, currently in the process of test building. Will create separate PR for the new version after it finishes.

**Comment by boegel** [comment]
+1 on bumping the version here to 2.12.0, we should always go with the latest release when we can (unless there's a reason not to).

@ItIsI-Orient You can just add an easyconfig for 2.12.0 to this PR, and then remove the one for 2.11.0, both via `--update-pr` (see https://docs.easybuild.io/en/latest/Integration_with_GitHub.html#deleting-easyconfig-files-or-patches)

**Comment by ItIsI-Orient** [comment]
Test report by @ItIsI-Orient
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
node3274.victini.os - Linux centos linux 7.9.2009, x86_64, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz, Python 3.6.8
See https://gist.github.com/8188f736dee0c0d34831b68071c5785f for a full test report.

**Comment by boegel** [comment]
@boegelbot please test @ generoso

**Review by boegel — APPROVED** [review]

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
node3505.doduo.os - Linux RHEL 8.2, x86_64, AMD EPYC 7552 48-Core Processor (zen2), Python 3.6.8
See https://gist.github.com/3edc899a726d4e12ca48b52e0ed9e8c9 for a full test report.

**Pull request merged**
