### PR TITLE
{lib}[GCCcore/6.4.0] glibc v2.26, glibc v2.17

### PR DESCRIPTION
**Pull request by boegel**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in this PR)
node2532.golett.os - Linux centos linux 7.4.1708, Intel(R) Xeon(R) CPU E5-2680 v3 @ 2.50GHz, Python 2.7.5
See https://gist.github.com/ceb9e8675d6faa07a99462cc125c5856 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in this PR)
node2072.delcatty.os - Linux centos linux 7.4.1708, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.7.5
See https://gist.github.com/1471820133dd4c4f4480c2f75431b37c for a full test report.

**Comment by wpoely86** [comment]
I'm not a big fan of adding this.

**Comment by boegel** [comment]
@wpoely86 Why not? Building `glibc` itself can be useful (especially in combination with `patchelf`, see #5427).

Loading the module may get you in trouble though, that's true.

In the long run, we want to look at including `glibc` underneath `GCC(core)` in toolchains (probably optionally), so this is definitely the first step...

**Pull request merged**
