### PR TITLE
require that sanity_pip_check is enabled in new/changed easyconfigs

### PR DESCRIPTION
**Pull request by boegel**
Support for running `pip check` during the sanity check to ensure that all required Python packages are installed was added in EasyBuild v4.1.0 (see #1853).

We should start requiring it in contributed easyconfigs, since it can prevent shipping broken easyconfigs (see https://github.com/easybuilders/easybuild-easyconfigs/issues/9306 for example).

You can enable the running of `pip check` either via:

```python
sanity_pip_check = True
```

or

```python
exts_default_options = {'sanity_pip_check': True}
```

(it can also be enabled for individual extensions, but there's little point in doing that imho, so no need to cover that in the check here)

### CODE REVIEW

**Comment by Flamefire** [comment]
Great! But we should also fix https://github.com/easybuilders/easybuild-easyblocks/issues/1877 to avoid failures due to python using the user home.

**Comment by boegel** [comment]
https://github.com/easybuilders/easybuild-easyblocks/issues/1877 is being fixed with https://github.com/easybuilders/easybuild-easyblocks/pull/1891

@smoors This is good to go imho...

**Comment by Flamefire** [comment]
Thanks, LGTM. However I suggest to rework the assert messages. The current one here is e.g. "sanity_pip_check is enabled in X". So if you see the test failing on travis this will be what is printed. The problem: The opposite is the case: The check failed because it is not enabled. This made me loose some time chasing for the failure because I couldn't understand the message. Better: "sanity_pip_check should be enabled in X" or "sanity_pip_check is not enabled in X"

**Comment by smoors** [comment]
@Flamefire I understand your confusion, but all other error messages are constructed in the same way.
So maybe file an issue on that?

**Comment by Flamefire** [comment]
Ok: https://github.com/easybuilders/easybuild-easyconfigs/issues/9542

**Comment by smoors** [comment]
Test report by @smoors
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
login2.cerberus.os - Linux centos linux 7.6.1810, Intel(R) Xeon(R) Gold 6126 CPU @ 2.60GHz, Python 2.7.5
See https://gist.github.com/c8ff78e72b7d37aa98ea8d20075fff7f for a full test report.

**Comment by smoors** [comment]
Going in, thanks @boegel!

**Pull request merged**
