### PR TITLE
{lib}[intel/2018b] CFITSIO v3.45

### PR DESCRIPTION
**Pull request by jose-d**
- recent cfitsio from `https://heasarc.gsfc.nasa.gov/fitsio/` built with intel2018b toolchain
- added dependency to current cURL for HTTPs support in cfitsio
- added `make shared` statement to produce shared lib too

### CODE REVIEW

**Comment by migueldiascosta** [comment]
Test report by @migueldiascosta
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
grc-cluster1 - Linux centos 6.10, Intel(R) Xeon(R) CPU E5-2640 0 @ 2.50GHz, Python 2.7.14
See https://gist.github.com/d590fbaae9f9d11d1bc0163d4e749e9e for a full test report.

**Comment by migueldiascosta** [comment]
Going in, thanks @jose-d!

**Comment by migueldiascosta** [comment]
thanks @jose-d 

you may want to have a look at https://easybuild.readthedocs.io/en/latest/Integration_with_GitHub.html#submitting-new-and-updating-pull-requests-new-pr-update-pr, it greatly simplifies the contribution process

and note that contributors are encouraged to submit their own test reports, https://easybuild.readthedocs.io/en/latest/Contributing.html#test-reports-for-easyconfig-contributions-upload-test-report

**Comment by jose-d** [comment]
@migueldiascosta 
> `--new-pr` and `--upload-test-report`

thx, I'll try it with next one.

**Pull request merged**
