### PR TITLE
{bio}[GCCcore/10.3.0] alevin-fry v0.6.0

### PR DESCRIPTION
**Pull request by SIB-software**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by verdurin** [comment]
@boegelbot please test @ generoso

**Comment by verdurin** [comment]
Test report by @verdurin
**SUCCESS**
Build succeeded for 2 out of 2 (1 easyconfigs in total)
easybuild-c7.novalocal - Linux CentOS Linux 7.9.2009, x86_64, Intel Xeon Processor (Skylake, IBRS), Python 3.6.8
See https://gist.github.com/44776ac94d5a252e65cb6e4868553ebe for a full test report.

**Comment by smoretti** [comment]
Hi @verdurin what else misses here?

**Comment by smoretti** [comment]
@verdurin Do I have to do something else?

**Comment by boegel** [comment]
@boegelbot please test @ generoso

**Review by boegel — APPROVED** [review]
lgtm

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
node3114.skitty.os - Linux RHEL 8.4, x86_64, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz (skylake_avx512), Python 3.6.8
See https://gist.github.com/82e55c91a078764fb2b25c7a8b021396 for a full test report.

**Comment by boegel** [comment]
Going in, thanks @SIB-software!

**Pull request merged**
