### PR TITLE
{bio}[GCC/9.3.0] BioBloomTools v2.3.2-20200731

### PR DESCRIPTION
**Pull request by mboisson**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by mboisson** [comment]
This recipe can't provide checksums. Also, the missing dependencies are other PRs except for Boost-1.72.0-GCC-9.3.0.eb.  

Should I open a PR for Boost-1.72.0-GCC-9.3.0.eb, or is it frowned upon to install Boost without MPI support ? If I should not, then I won't open more PRs that depend on Boost at compiler level.

@boegel @bartoldeman

**Comment by mboisson** [comment]
In my opinion, installing Boost only at the MPI level of the hierarchy bumps way too many recipes up to the MPI level.

**Comment by mboisson** [comment]
This PR requires https://github.com/easybuilders/easybuild-easyconfigs/pull/11145

**Comment by mboisson** [comment]
This PR also requires https://github.com/easybuilders/easybuild-easyconfigs/pull/11084

**Comment by akesandgren** [comment]
Boost was moved to GCC level some time ago, feel free to updated this to a newer toolchain, this toolchain has been deprecated.

Closing this PR, since it (only) uses deprecated toolchain versions,
see https://docs.easybuild.io/policies/toolchains .

**Pull request closed without merging**
