### PR TITLE
{vis}[foss-2018a] GTK+ 2.24.32 (REVIEW)

### PR DESCRIPTION
**Pull request by hajgato**

### CODE REVIEW

**Comment by hajgato** [comment]
PR #5931 needs this.

**Comment by boegel** [comment]
pretty much a duplicate of #5827

We'll only merge one of both, to avoid version conflicts between modules that include `GTK+`.

cc @RvDijk: How do we proceed? Maybe minor bump of GTK+ version in your PR? Any other changes needed?

**Comment by hajgato** [comment]
in the OpenCV PR he already bumped to  `GTK+ 2.24.32`, but I have time to wait.

**Comment by hajgato** [comment]
In matter of fact in #5827 it is already `GTK+ 2.24.32` I just bumped `ATK` from `2.27.1` to `2.28.1`

**Comment by RvDijk** [comment]
@hajgato @boegel I have updated the title and ATK version.

**Comment by boegel** [comment]
@hajgato This can be closed now since #5827 is merged?

**Comment by hajgato** [comment]
This is the same as PR #5827

**Pull request closed without merging**
