### PR TITLE
{tools}[GCCcore/8.3.0] cadaver v0.23.3

### PR DESCRIPTION
**Pull request by verdurin**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by verdurin** [comment]
Test report by @verdurin
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
easybuild-c7.novalocal - Linux centos linux 7.9.2009, x86_64, Intel Xeon Processor (Skylake, IBRS), Python 3.6.8
See https://gist.github.com/366304212ee7521d6226df57e70a4322 for a full test report.

**Comment by branfosj** [comment]
Test report by @branfosj
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
bear-pg0211u03a.bear.cluster - Linux centos linux 7.8.2003, x86_64, Intel(R) Xeon(R) Gold 6248 CPU @ 2.50GHz (cascadelake), Python 3.6.8
See https://gist.github.com/101be7212f232acbf7fb70b091fcd6a7 for a full test report.

**Comment by branfosj** [comment]
Looking in my build log I see:
```
  Install prefix:        /rds/bear-apps/devel/eb-sjb-up/EL7/EL7-cascadelake/software/cadaver/0.23.3-GCCcore-8.3.0
  Compiler:              gcc
  Neon library:          included libneon (0.29.1)
  XML Parser:            expat
  SSL library:       SSL support is not enabled
  Internationalization:  Built using native support
  GNU readline support:  enabled
```

So, system level `expat` and `libreadline` are being picked up. Use EB versions instead?

**Comment by verdurin** [comment]
@branfosj - yes, this clearly needs more work - thanks for checking.

**Comment by verdurin** [comment]
@branfosj looking at the Fedora source this needs so much patching to build now that I'm lacking motivation to fix it properly: https://src.fedoraproject.org/rpms/cadaver

**Comment by Micket** [comment]
It looks like we want to find to patch it properly? I'll just move this PR to a draft until the motivation is found again :)

**Comment by branfosj** [comment]
As this PR is WIP or draft and has not been updated in over a year I have closed it. If you work on this again then please reopen the PR.

**Pull request closed without merging**
