### PR TITLE
add patch to fix missing sync in LINCS and SETTLE CUDA kernels for GROMACS 2021 versions

### PR DESCRIPTION
**Pull request by branfosj**
(created using `eb --new-pr`)

Patch based off https://gitlab.com/gromacs/gromacs/-/merge_requests/2499 and see discussion in https://gitlab.com/gromacs/gromacs/-/issues/4393

### CODE REVIEW

**Comment by SebastianAchilles** [comment]
@boegelbot please test @ jsc-zen2
CORE_CNT=16

**Comment by branfosj** [comment]
Test report by @branfosj
**FAILED**
Build succeeded for 55 out of 65 (5 easyconfigs in total)
bear-pg0104u09a.bear.cluster - Linux RHEL 8.6, x86_64, Intel(R) Xeon(R) Platinum 8360Y CPU @ 2.40GHz (icelake), Python 3.6.8
See https://gist.github.com/3a55ecf1446088c9264908dcd10c9b06 for a full test report.

**Comment by SebastianAchilles** [comment]
@boegelbot please test @ generoso
CORE_CNT=16

**Comment by branfosj** [comment]
Test report by @branfosj
**SUCCESS**
Build succeeded for 12 out of 12 (5 easyconfigs in total)
bear-pg0104u09a.bear.cluster - Linux RHEL 8.6, x86_64, Intel(R) Xeon(R) Platinum 8360Y CPU @ 2.40GHz (icelake), Python 3.6.8
See https://gist.github.com/34e0ccc9d71d20684bd6238623d65c5e for a full test report.

**Review by SebastianAchilles — APPROVED** [review]
lgtm

**Comment by SebastianAchilles** [comment]
Going in, thanks @branfosj!

**Pull request merged**
