### PR TITLE
{math}[foss/2020b] Clp v1.17.6, Cgl v0.60.3, Cbc v2.10.5, ...

### PR DESCRIPTION
**Pull request by Micket**
(created using `eb --new-pr`)

- [ ] #13702

### CODE REVIEW

**Comment by Micket** [comment]
Test report by @Micket
**FAILED**
Build succeeded for 2 out of 5 (5 easyconfigs in total)
alvis-c1 - Linux centos linux 7.9.2009, x86_64, Intel Xeon Processor (Skylake), Python 3.6.8
See https://gist.github.com/f16b217cdbfe0b0d8eb27ac91ef46da7 for a full test report.

**Comment by Micket** [comment]
Should work now if the MUMPs fix gets in

**Comment by Micket** [comment]
Test report by @Micket
**SUCCESS**
Build succeeded for 5 out of 5 (5 easyconfigs in total)
alvis-c1 - Linux centos linux 7.9.2009, x86_64, Intel Xeon Processor (Skylake), Python 3.6.8
See https://gist.github.com/0f05276e9e9605f846a6dc4fb994e682 for a full test report.

**Comment by SebastianAchilles** [comment]
@boegelbot please test @ generoso

**Review by SebastianAchilles — APPROVED** [review]
lgtm

**Comment by SebastianAchilles** [comment]
Test report by @sebastianachilles
**SUCCESS**
Build succeeded for 5 out of 5 (5 easyconfigs in total)
centos8-eb - Linux centos linux 8.3.2011, x86_64, Intel(R) Core(TM) i7-8700 CPU @ 3.20GHz (skylake), Python 3.6.8
See https://gist.github.com/7c1bf18d67c5c4987fe873aae6e03b8d for a full test report.

**Comment by SebastianAchilles** [comment]
Test report by @sebastianachilles
**SUCCESS**
Build succeeded for 5 out of 5 (5 easyconfigs in total)
rocky8-eb - Linux rocky linux 8.4, x86_64, Intel(R) Core(TM) i7-6900K CPU @ 3.20GHz (broadwell), Python 3.6.8
See https://gist.github.com/b3c8af10a412638da1373754c0c9aca8 for a full test report.

**Comment by SebastianAchilles** [comment]
Going in, thanks @Micket!

**Pull request merged**
