### PR TITLE
add new python-irodsclient easyconfig

### PR DESCRIPTION
**Pull request by jefscheepers**
see #16327

### CODE REVIEW

**Comment by smoors** [comment]
@jefscheepers thanks for the PR.

FYI, it's not required to open a new issue for each new easyconfig.

if you plan on sending in more PRs, I would highly recommend using the github integration that is built into EB, see here for more info: https://docs.easybuild.io/en/latest/Integration_with_GitHub.html

**Comment by smoors** [comment]
@boegelbot: please test @ generoso

**Review by smoors — APPROVED** [review]
lgtm

**Comment by smoors** [comment]
Going in, thanks @jefscheepers!

**Comment by jefscheepers** [comment]
> @jefscheepers thanks for the PR.
> 
> FYI, it's not required to open a new issue for each new easyconfig.
> 
> if you plan on sending in more PRs, I would highly recommend using the github integration that is built into EB, see here for more info: https://docs.easybuild.io/en/latest/Integration_with_GitHub.html

Thanks for the hints, I wasn't sure whether a new issue was needed or not.
No new PR's planned for the moment, but I'll have a look at the Github Integration anyway :)

**Pull request merged**
