### PR TITLE
{vis}[intelcuda/2020b] OpenCV v4.5.1-contrib

### PR DESCRIPTION
**Pull request by zdemat**
based on OpenCV-4.5.1-contrib easyconfig for fosscuda/2020b
- removed **saliency** from cotrib_libs as it does not build with ICC (see [CMakeLists.txt](https://github.com/opencv/opencv_contrib/blob/4fc6995375e384b8e25bd6c8693fa8dd2ed4bb0a/modules/saliency/CMakeLists.txt)) and sanity check fails
- added **Eigen** and **cuDNN** as dependencies
- issues with static libs included in IPP: backported fix from [OpenCV issue 19681](https://github.com/opencv/opencv/pull/19681) as **OpenCV-4.5.1-icc_FindLibsPerf.cmake.patch**. An alternative is to exclude the libraries with `-DOPENCV_FORCE_IPP_EXCLUDE_LIBS=ON`
- added at least a single test: **opencv_test_core**
- issues with **Core_SVD orthogonality test** - fixed by switching to OpenCV default: `-fp-model precise` in toolchainopts

### CODE REVIEW

**Comment by zdemat** [comment]
one more note
- added **opencv_extra** to sources as data from there are needed for 3 tests in opencv_test_core

**Comment by zdemat** [comment]
ping on this issue. Is anything wrong? It got stuck. I remember this one was not trivial.

**Review by jfgrimm — COMMENTED** [review]
As decided in issue #16330, we have deprecated the use of `True` to signify a system-toolchain dependency (#16384), in favour of the more intuitive `SYSTEM` template constant. Due to the change in the test suite, please run `eb --sync-pr-with-develop 12928` and update the PR to use `SYSTEM` instead.

**Comment by boegel** [comment]
closing this since `intelcuda/2020b` is deprecated, see https://docs.easybuild.io/policies/toolchains

**Pull request closed without merging**
