### PR TITLE
add in Boost dependency to canu-1.8-foss easyconfigs

### PR DESCRIPTION
**Pull request by murfreesboro**
see PR https://github.com/easybuilders/easybuild-easyconfigs/pull/8463

### CODE REVIEW

**Comment by murfreesboro** [comment]
Test report by @murfreesboro
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
dev806.vampire - Linux centos linux 7.4.1708, Intel(R) Xeon(R) CPU           E5620  @ 2.40GHz, Python 2.7.5
See https://gist.github.com/1efe78cc73e00bde929c95c06be13e9f for a full test report.

**Comment by smoors** [comment]
@murfreesboro can you please do the same for `canu-1.8-foss-2018b-Perl-5.28.0.eb`?

**Comment by murfreesboro** [comment]
> @murfreesboro can you please do the same for `canu-1.8-foss-2018b-Perl-5.28.0.eb`?

@smoors I can update the file, but I do not have 2018b toolchain with me so I can not test it.

**Comment by vanzod** [comment]
Test report by @vanzod
**SUCCESS**
Build succeeded for 4 out of 4 (2 easyconfigs in this PR)
cermis - Linux debian 9.9, Intel(R) Xeon(R) CPU           X5670  @ 2.93GHz, Python 2.7.13
See https://gist.github.com/1f34d0cc48b726c3d5b285fdbb6e4441 for a full test report.

**Comment by vanzod** [comment]
Going in, thanks @murfreesboro!

**Pull request merged**
