### PR TITLE
{chem}[intel/2017b] QuickFF v2.2.0

### PR DESCRIPTION
**Pull request by boegel**
(created using `eb --new-pr`)
requires #5236

### CODE REVIEW

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
node2430.golett.os - Linux centos linux 7.4.1708, Intel(R) Xeon(R) CPU E5-2680 v3 @ 2.50GHz, Python 2.7.5
See https://gist.github.com/4fcb6158a9f33e7ea8c989c7cac8d5d1 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
node2092.delcatty.os - Linux centos linux 7.4.1708, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.7.5
See https://gist.github.com/05ca4128d0f1765f8aef84bc20df3d9c for a full test report.

**Comment by boegel** [comment]
note: the sources for this version of QuickFF are not publicly available yet, but they will be soon

**Comment by vanzod** [comment]
Going in, thanks @boegel!

**Pull request merged**
