### PR TITLE
{chem}[GCC/8.2.0-2.31.1] libxc v2.2.2

### PR DESCRIPTION
**Pull request by smoors**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by smoors** [comment]
Test report by @smoors
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
nic400 - Linux centos linux 7.5.1804, Intel(R) Xeon(R) Gold 6148 CPU @ 2.40GHz, Python 2.7.5
See https://gist.github.com/4056677f92d20d3b8748c31b425c1f5d for a full test report.

**Comment by vanzod** [comment]
@smoors Is there a specific reason you are pushing this "old" version to the 2019a toolchain?
Moreover, please use the `GCC` toolchain since there is no apparent required dependency in `foss`.

**Comment by smoors** [comment]
@vanzod I need the 2.2.2 version for building horton with the 2019a toolchain generation.
I have changed it to use the GCC toolchain, and added the latest version 4.3.4 as well.

**Comment by smoors** [comment]
Test report by @smoors
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in this PR)
nic97 - Linux centos linux 7.5.1804, Intel(R) Xeon(R) Gold 6148 CPU @ 2.40GHz, Python 2.7.5
See https://gist.github.com/f02db21e1b4d86009195734537360782 for a full test report.

**Comment by Micket** [comment]
@smoors So, I'm a bit curious about the 8.3.0-2.32 choice. So it's not going to any of the 2019a toolchains anymore? I was going to change the title, but I'm not sure if it's intentional.

**Comment by smoors** [comment]
@Micket that was a mistake. I moved to the 2019a compatible GCC-8.2.0-2.31.1
apparently libxc-4.3.4 has already been merged, so I removed it from this PR.

**Comment by smoors** [comment]
github seems to be confused when I try to remove libxc-4.3.4-GCC-8.2.0-2.31.1.eb from this PR.
I will just close and open a new PR.

**Pull request closed without merging**
