### PR TITLE
{bio}[intel/2018b] OrthoFinder v2.3.3 w/ Python 2.7.15 (+ deps)

### PR DESCRIPTION
**Pull request by boegel**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 5 out of 5 (5 easyconfigs in this PR)
node3112.skitty.os - Linux centos linux 7.6.1810, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz, Python 2.7.5
See https://gist.github.com/98e1163e04863179dceb58ae9f73cc81 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 5 out of 5 (5 easyconfigs in this PR)
node2606.swalot.os - Linux centos linux 7.6.1810, Intel(R) Xeon(R) CPU E5-2660 v3 @ 2.60GHz, Python 2.7.5
See https://gist.github.com/aad023756814e78567fadc7891d94557 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 5 out of 5 (5 easyconfigs in this PR)
node2016.delcatty.os - Linux centos linux 7.6.1810, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.7.5
See https://gist.github.com/62b1f1150d0b9265ad9078cea30aca11 for a full test report.

**Comment by vanzod** [comment]
Test report by @vanzod
**FAILED**
Build succeeded for 3 out of 5 (5 easyconfigs in this PR)
cermis - Linux debian 9.9, Intel(R) Xeon(R) CPU           X5670  @ 2.93GHz, Python 2.7.13
See https://gist.github.com/05bc0bbc902fabeca620ec4050021a04 for a full test report.

**Comment by vanzod** [comment]
`MMseqs2` does not like my old test box...

**Comment by boegel** [comment]
@vanzod Your test report is failing with

```
At least SSE4.2 is needed to compile!
```

Not so much we can do about this on the EasyBuild side?

**Comment by verdurin** [comment]
Test report by @verdurin
**SUCCESS**
Build succeeded for 7 out of 7 (5 easyconfigs in this PR)
rescomp2 - Linux centos linux 7.3.1611, Intel(R) Xeon(R) Gold 6126 CPU @ 2.60GHz, Python 2.7.5
See https://gist.github.com/01577deb72a9a7bcd6c554af70d7de90 for a full test report.

**Comment by verdurin** [comment]
Going in, thanks @boegel!

**Comment by vanzod** [comment]
@boegel If we do not want it to fail like that the only way would be to have a CPU feature check in a dedicated easyblock. But it may be a step into over-engineering

**Comment by boegel** [comment]
@vanzod Isn't SSE 4.2 available pretty much everywhere nowadays? WTF kind of test box do you have? :)

**Comment by vanzod** [comment]
@boegel Agree. That is why I said it would be overkill

**Pull request merged**
