### PR TITLE
Add tornado Python module config.

### PR DESCRIPTION
**Pull request by pforai**
This might have a small name clash with something else that we have already in the config tree: "Tornado".

### CODE REVIEW

**Comment by JensTimmerman** [comment]
@pforai can you please redo this pr on develop?

**Comment by migueldiascosta** [comment]
@pforai, this PR is being closed for the following reason(s): inactive.
Please don't hesitate to reopen this PR or add a comment if you feel this contribution is still relevant.
For more information on our policy w.r.t. closing PRs, see https://easybuild.readthedocs.io/en/latest/Contributing.html#why-a-pull-request-may-be-closed-by-a-maintainer

**Comment by JensTimmerman** [comment]
@migueldiascosta This pr should be closed for reason: pr to master instead of develop

**Comment by migueldiascosta** [comment]
@JensTimmerman edited message, thanks!

**Pull request closed without merging**
