### PR TITLE
add rhandsontable extension to R-bundle-CRAN v2023.12

### PR DESCRIPTION
**Pull request by boegel**
(created using `eb --new-pr`)

This removed the dedicated easyconfig for `rhandsontable` that was contributed by @PetrKralCZ in #20537, I don't see a need to have it standalone as opposed to just including it in the existing `R-bundle-CRAN` module...

### CODE REVIEW

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
node3147.skitty.os - Linux RHEL 8.8, x86_64, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz, Python 3.6.8
See https://gist.github.com/boegel/285a7d09be55f6f1c307ad42871d73b5 for a full test report.

**Comment by smoors** [comment]
@boegelbot please test @ jsc-zen3

**Comment by smoors** [comment]
@boegelbot please test @ jsc-zen3  EB_ARGS="--skip"

**Review by smoors — APPROVED** [review]
lgtm

**Comment by smoors** [comment]
Going in, thanks @boegel!

**Pull request merged**
