### PR TITLE
fix broken tests due to multile TensorFlow versions being used as dependency in 2019b generation by using TensorFlow 2.1.0 as dep for PlasFlow

### PR DESCRIPTION
**Pull request by boegel**

### CODE REVIEW

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
node3101.skitty.os - Linux centos linux 7.7.1908, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz, Python 3.6.8
See https://gist.github.com/6e1edb3ce9363ba270b3afdd4d7eb7e9 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
node2548.golett.os - Linux centos linux 7.7.1908, Intel(R) Xeon(R) CPU E5-2680 v3 @ 2.50GHz, Python 2.7.5
See https://gist.github.com/19a06077ae3f67abf7e5ea86e70341e4 for a full test report.

**Comment by migueldiascosta** [comment]
Going in, thanks @boegel!

**Comment by lexming** [comment]
@migueldiascosta have you checked if `PlasFlow` does work with `TensorFlow` v2?

**Comment by migueldiascosta** [comment]
@lexming no, I gathered fixing the easyconfig tests first was more important (?) since it affects everything else, but of course if PlasFlow doesn't work with TensorFlow v2 we'll need to find another solution...

**Comment by boegel** [comment]
Indeed, fixing the tests is more important right now.

I also noticed that PlasFlow mentions TensorFlow 0.10.0 as a dependency, so I have a suspicion it doesn't work with TensorFlow 1.x either, but I'll try and sort that out...

**Comment by lexming** [comment]
IMO this easyconfig is not working as expected, even the dependency on `rpy2` seems to not work. See issue #9951

**Pull request merged**
