### PR TITLE
{tools}[system/system] VTune v2020_update3

### PR DESCRIPTION
**Pull request by boegel**
(created using `eb --new-pr`)
requires ~~https://github.com/easybuilders/easybuild-easyblocks/pull/2359~~

### CODE REVIEW

**Comment by boegel** [comment]
Test report by @boegel
Using easyblocks from PR(s) https://github.com/easybuilders/easybuild-easyblocks/pull/2359
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
node3501.doduo.os - Linux RHEL 8.2, x86_64, AMD EPYC 7552 48-Core Processor (zen2), Python 3.6.8
See https://gist.github.com/909b5056f73ef02cdf9b956635d5cb32 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
Using easyblocks from PR(s) https://github.com/easybuilders/easybuild-easyblocks/pull/2359
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
node3140.skitty.os - Linux centos linux 7.9.2009, x86_64, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz, Python 3.6.8
See https://gist.github.com/8a087c415bcec56c87086c9e55f15bb1 for a full test report.

**Comment by migueldiascosta** [comment]
@boegelbot please test @ generoso

**Comment by migueldiascosta** [comment]
@boegel does it make sense to have an option to install without the GUI component?

**Comment by bartoldeman** [comment]
@migueldiascosta that would be appropriate for the easyblock. There are indeed some libraries (e.. `libXss`) that the GUI component depends on, and if they are not installed on the system the installer refuses to proceed.

**Comment by bartoldeman** [comment]
Test report by @bartoldeman
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
build-node.computecanada.ca - Linux centos linux 7.9.2009, x86_64, Intel Xeon Processor (Skylake, IBRS), Python 3.7.7
See https://gist.github.com/8c494b6799ce9719a323aacac74a5495 for a full test report.

**Review by bartoldeman — APPROVED** [review]
lgtm

**Pull request merged**
