### PR TITLE
use top-level parameters for `use_pip` & co instead of `exts_default_options` for `PythonBundle` easyconfigs

### PR DESCRIPTION
**Pull request by Flamefire**
It is easier in the top-level and might cause confusion with https://github.com/easybuilders/easybuild-easyblocks/pull/3428

### CODE REVIEW

**Comment by Flamefire** [comment]
Test report by @Flamefire
**SUCCESS**
Build succeeded for 18 out of 18 (18 easyconfigs in total)
n1552 - Linux RHEL 8.9 (Ootpa), x86_64, Intel(R) Xeon(R) Platinum 8470 (icelake), Python 3.8.17
See https://gist.github.com/Flamefire/b267a7aab05028cfa5974b7b356c0e6b for a full test report.

**Comment by boegel** [comment]
@boegelbot please test @ generoso

**Review by boegel — APPROVED** [review]
lgtm

**Comment by boegel** [comment]
Going in, thanks @Flamefire!

**Pull request merged**
