### PR TITLE
{debugger}[gompi/2021b,iimpi/2021b] Valgrind v3.18.1

### PR DESCRIPTION
**Pull request by SebastianAchilles**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by SebastianAchilles** [comment]
@boegelbot please test @ generoso

**Comment by SebastianAchilles** [comment]
Test report by @sebastianachilles
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in total)
skylake-alma8-eb - Linux AlmaLinux 8.5, x86_64, Intel(R) Core(TM) i7-8700 CPU @ 3.20GHz (skylake), Python 3.6.8
See https://gist.github.com/5ed7b22e91ad7813b77dec4b6faa1400 for a full test report.

**Comment by lexming** [comment]
@boegelbot: please test @ generoso

**Review by lexming — APPROVED** [review]
@SebastianAchilles I made a minor improvement of the sanity checks based on existing `Valgrind-3.17.0-gompi-2021a.eb`

LGTM

**Comment by lexming** [comment]
Going in, thanks @SebastianAchilles !

**Pull request merged**
