### PR TITLE
remove postinstallcmds from imkl 2020.x easyconfigs, easyblock not installs examples

### PR DESCRIPTION
**Pull request by boegel**
(created using `eb --new-pr`)

requires ~https://github.com/easybuilders/easybuild-easyblocks/pull/2430~

### CODE REVIEW

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 10 out of 10 (10 easyconfigs in total)
node2618.swalot.os - Linux centos linux 7.9.2009, x86_64, Intel(R) Xeon(R) CPU E5-2660 v3 @ 2.60GHz (haswell), Python 3.6.8
See https://gist.github.com/966cd2be5e8ad7973f034d95c030fb2e for a full test report.

**Comment by boegel** [comment]
@boegelbot please test @ generoso
CORE_CNT=16

**Review by verdurin — APPROVED** [review]
Looks fine.

**Comment by verdurin** [comment]
Going in, thanks @boegel!

**Pull request merged**
