### PR TITLE
Add binutils-2.35.2 for SYSTEM and GCCcore-10.2.0

### PR DESCRIPTION
**Pull request by Flamefire**
The least controversial part of https://github.com/easybuilders/easybuild-easyconfigs/pull/12920

With this merged it would be possible to use it as a builddependency for ECs that fail due to the error fixed in 2.35.2

### CODE REVIEW

**Comment by Flamefire** [comment]
Test report by @Flamefire
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in total)
taurusi8029 - Linux centos linux 7.9.2009, x86_64, AMD EPYC 7352 24-Core Processor (zen2), Python 2.7.5
See https://gist.github.com/52b6b15937afb6553b743ed63a49cb27 for a full test report.

**Comment by Flamefire** [comment]
Test report by @Flamefire
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in total)
taurusml17 - Linux RHEL 7.6, POWER, 8335-GTX (power9le), Python 2.7.5
See https://gist.github.com/4588ed8ea0d9526ed5291a6196a826ca for a full test report.

**Comment by Flamefire** [comment]
Test report by @Flamefire
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in total)
taurusa5 - Linux centos linux 7.7.1908, x86_64, Intel(R) Xeon(R) CPU E5-2603 v4 @ 1.70GHz (broadwell), Python 2.7.5
See https://gist.github.com/9ffa8512634a4ccb661a17e649db76c9 for a full test report.

**Comment by boegel** [comment]
Rather than going this route, we could switch to the 2.35.2 sources in `binutils-2.35-GCCcore-10.2.0.eb` (only for POWER), as mentioned in https://github.com/easybuilders/easybuild-easyconfigs/pull/12920#issuecomment-849048717

**Pull request closed without merging**
