### PR TITLE
add geeM extension to R v4.2.0

### PR DESCRIPTION
**Pull request by boegel**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by boegel** [comment]
@boegelbot please test @ generoso
EB_ARGS="--skip"

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
node3507.doduo.os - Linux RHEL 8.4, x86_64, AMD EPYC 7552 48-Core Processor (zen2), Python 3.6.8
See https://gist.github.com/a8fa4fbd966f62fd5750d509f0077a06 for a full test report.

**Comment by SebastianAchilles** [comment]
@boegelbot please test @ jsc-zen2
EB_ARGS="--skip"

**Comment by verdurin** [comment]
Test report by @verdurin
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
centos7.lan - Linux CentOS Linux 7.9.2009, x86_64, Intel Core Processor (Skylake, IBRS), Python 3.6.8
See https://gist.github.com/31f131b7c5f34cb0bb9176cd57c44332 for a full test report.

**Comment by SebastianAchilles** [comment]
> @SebastianAchilles: Request for testing this PR well received on jsczen2l1.int.jsc-zen2.easybuild-test.cluster
> 
> PR test command '`EB_PR=15810 EB_ARGS="--skip" /opt/software/slurm/bin/sbatch --job-name test_PR_15810 --ntasks=8 ~/boegelbot/eb_from_pr_upload_jsc-zen2.sh`' executed!
> 
>     * exit code: 0
> 
>     * output:
> 
> 
> ```
> Submitted batch job 1362
> ```
> 
> Test results coming soon (I hope)...

Uploading the test report failed with: `HTTP Error 403: Forbidden`. But the Installation ended successfully.

**Comment by SebastianAchilles** [comment]
Test report by @sebastianachilles
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
zen2-ubuntu-eb - Linux Ubuntu 22.04, x86_64, AMD EPYC 7452 32-Core Processor (zen2), Python 3.10.4
See https://gist.github.com/4b6ce51e33cc23e8cca4050192f37707 for a full test report.

**Pull request merged**
