### PR TITLE
{bio}[intel/2018a] CNVkit v0.9.3, Biopython v1.71, hmmlearn 0.2.0

### PR DESCRIPTION
**Pull request by boegel**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 4 out of 4 (4 easyconfigs in this PR)
node2646.swalot.os - Linux centos linux 7.4.1708, Intel(R) Xeon(R) CPU E5-2660 v3 @ 2.60GHz, Python 2.7.5
See https://gist.github.com/c74de535bef020200a1586e1c64b7992 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 4 out of 4 (4 easyconfigs in this PR)
node2056.delcatty.os - Linux centos linux 7.4.1708, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.7.5
See https://gist.github.com/95a83dd8221b81c09ac60e824e2a6ba7 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**FAILED**
Build succeeded for 11 out of 13 (4 easyconfigs in this PR)
node3129.skitty.os - Linux centos linux 7.4.1708, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz, Python 2.7.5
See https://gist.github.com/b9dba6d0ebf5bca692069c161fb24ef2 for a full test report.

**Comment by boegel** [comment]
@damianam That's verified automagically by setting `(exts_)download_dep_fail = True` in these easyconfigs (cfr. https://github.com/easybuilders/easybuild-easyblocks/pull/1377)

**Comment by migueldiascosta** [comment]
Test report by @migueldiascosta
**FAILED**
Build succeeded for 7 out of 12 (4 easyconfigs in this PR)
grc-s05 - Linux centos 6.9, Intel(R) Xeon(R) CPU E5-4640 0 @ 2.40GHz, Python 2.6.6
See https://gist.github.com/18278a3ad89675c6386528572892fed2 for a full test report.

**Comment by migueldiascosta** [comment]
Test report by @migueldiascosta
**FAILED**
Build succeeded for 7 out of 11 (8 easyconfigs in this PR)
grc-s05 - Linux centos 6.9, Intel(R) Xeon(R) CPU E5-4640 0 @ 2.40GHz, Python 2.6.6
See https://gist.github.com/1af748f606fb577477c0adb94fd59011 for a full test report.

**Comment by boegel** [comment]
@migueldiascosta Failure with `R` is due to changed checksums, cfr. #6446, you'll need to re-download those source tarballs...

Not sure about the issue with `Pillow` though... Does that ring any bells for you?

**Comment by migueldiascosta** [comment]
@boegel regarding the issue with `Pillow`, a google search shows a few things about a `binutils` 2.28 issue, although that doesn't explain why only I seem to have this problem...

**Comment by boegel** [comment]
@migueldiascosta Can you share a full debug log for the failing `Pillow`? You can obtain it with `eb --from-pr 6445 --debug Pillow-5.0.0-intel-2018a-Python-3.6.4.eb` .

Also, was `LibTIFF/4.0.9-GCCcore-6.4.0` installed with the right `binutils` version?
Is it an option to try and reinstall that to see if that resolves the issue?

**Comment by boegel** [comment]
@migueldiascosta May be related to the fix in #5945, was `LibTIFF` installed with that configure option (`--enable-ld-version-script`) included?

**Comment by migueldiascosta** [comment]
@boegel I did try reinstall `LibTIFF`, `Pillow` still failed although with a slightly different error (different duplicate definition)

at least the second install did have the configure option from #5945 

I'll get the full log

**Comment by migueldiascosta** [comment]
full log at https://gist.github.com/migueldiascosta/366d4ae69daf7c08bc44c14ed756f7d6

**Comment by migueldiascosta** [comment]
added the `LibTIFF` log to the gist

**Comment by akesandgren** [comment]
@boegel Conflicts to be resolved...

**Comment by akesandgren** [comment]
Test report by @akesandgren
**FAILED**
Build succeeded for 12 out of 15 (3 easyconfigs in this PR)
b-an04.hpc2n.umu.se - Linux ubuntu 16.04, x86_64, Intel(R) Xeon(R) CPU E5-2690 v4 @ 2.60GHz, Python 2.7.12
See https://gist.github.com/c5b32456a9ae9164b5e092bd7a969f88 for a full test report.

**Comment by akesandgren** [comment]
Test report by @akesandgren
**FAILED**
Build succeeded for 0 out of 3 (3 easyconfigs in this PR)
b-an04.hpc2n.umu.se - Linux ubuntu 16.04, x86_64, Intel(R) Xeon(R) CPU E5-2690 v4 @ 2.60GHz, Python 2.7.12
See https://gist.github.com/b3b72fb34aae778cfea25d4ea2810d29 for a full test report.

**Comment by akesandgren** [comment]
I get
```
WARNING: Use of 1 unknown easyconfig parameters detected in CNVkit-0.9.3-intel-2018a-Python-3.6.4.eb: full_sanity_check

```

**Comment by akesandgren** [comment]
Test report by @akesandgren
**FAILED**
Build succeeded for 0 out of 3 (3 easyconfigs in total)
b-an04.hpc2n.umu.se - Linux ubuntu 16.04, x86_64, Intel(R) Xeon(R) CPU E5-2690 v4 @ 2.60GHz, Python 2.7.12
See https://gist.github.com/6db90f8d92eccb0d0e44f652315e2ded for a full test report.

**Comment by akesandgren** [comment]
Test report by @akesandgren
**FAILED**
Build succeeded for 0 out of 3 (3 easyconfigs in total)
b-an04.hpc2n.umu.se - Linux ubuntu 16.04, x86_64, Intel(R) Xeon(R) CPU E5-2690 v4 @ 2.60GHz, Python 2.7.12
See https://gist.github.com/266f96c813467e65dfeb83c53eae0de6 for a full test report.

**Comment by akesandgren** [comment]
Test report by @akesandgren
**SUCCESS**
Build succeeded for 5 out of 5 (3 easyconfigs in total)
b-an03.hpc2n.umu.se - Linux ubuntu 16.04, x86_64, Intel(R) Xeon(R) CPU E5-2690 v4 @ 2.60GHz, Python 2.7.12
See https://gist.github.com/de819f1dd6af3d3aa6093fe6e332c456 for a full test report.

**Comment by migueldiascosta** [comment]
Test report by @migueldiascosta
**SUCCESS**
Build succeeded for 3 out of 3 (3 easyconfigs in total)
sms - Linux centos linux 7.6.1810, x86_64, AMD EPYC 7601 32-Core Processor (zen), Python 2.7.5
See https://gist.github.com/d8014dc3dd078b0aed0713163c46c895 for a full test report.

**Comment by migueldiascosta** [comment]
@boegel I think my old failing tests can be ignored, I don't seem to be able to reproduce them even in that old CentOS 6 cluster

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 3 out of 3 (3 easyconfigs in total)
node2707.swalot.os - Linux centos linux 7.9.2009, x86_64, Intel(R) Xeon(R) CPU E5-2660 v3 @ 2.60GHz (haswell), Python 3.6.8
See https://gist.github.com/055720f0bf081b0007c4ca0a5088d96e for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 3 out of 3 (3 easyconfigs in total)
node3129.skitty.os - Linux centos linux 7.9.2009, x86_64, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz, Python 3.6.8
See https://gist.github.com/6d82d485ea495e1d2b9cc1f51568abed for a full test report.

**Review by akesandgren — APPROVED** [review]
LGTM

**Comment by akesandgren** [comment]
Test report by @akesandgren
**SUCCESS**
Build succeeded for 8 out of 8 (3 easyconfigs in total)
b-an04.hpc2n.umu.se - Linux ubuntu 16.04, x86_64, Intel(R) Xeon(R) CPU E5-2690 v4 @ 2.60GHz, Python 2.7.12
See https://gist.github.com/20ee9c162464caae987f1479495c6710 for a full test report.

**Comment by akesandgren** [comment]
Going in, thanks @boegel!

**Pull request merged**
