### PR TITLE
{bio}[foss/2022a] RepeatMasker v4.1.5 w/ Python 3.10.4

### PR DESCRIPTION
**Pull request by bedroge**
(created using `eb --new-pr`)

### CODE REVIEW

**Review by Micket — APPROVED** [review]
lgtm

**Comment by bedroge** [comment]
@boegelbot please test @ generoso

**Comment by Micket** [comment]
Bah, their webpage sucks it seems. I'm struggling to get it to download the sources

**Comment by Micket** [comment]
Test report by @Micket
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
alvis-c1 - Linux Rocky Linux 8.6, x86_64, Intel Xeon Processor (Skylake), Python 3.6.8
See https://gist.github.com/Micket/f5d162a4c688fd85992d04e3431bc5ff for a full test report.

**Comment by Micket** [comment]
Going in, thanks @bedroge!

**Pull request merged**
