### PR TITLE
{data}[GCC/11.2.0] MariaDB v10.6.4

### PR DESCRIPTION
**Pull request by sassy-crick**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by sassy-crick** [comment]
Added `PCRE2-10.37` as build-dependency as download sometimes does not work. Thus changed:
`-DWITH_PCRE=bundle `
to
`-DWITH_PCRE=auto `
so it automatically detects the installed PCRE2. The alternative would be `system`.

**Comment by sassy-crick** [comment]
Requires
- [ ] [Judy](https://github.com/easybuilders/easybuild-easyconfigs/pull/14297)
- [ ]  [libaio](https://github.com/easybuilders/easybuild-easyconfigs/pull/14298)

**Comment by migueldiascosta** [comment]
@boegelbot please test @ generoso

**Comment by migueldiascosta** [comment]
@sassy-crick I suppose `Looking for PCRE2regcomp in pcre2-posix - not found` is not a problem?

Also, running it locally it seems that OpenSSL is a runtime dep for `mysql` and PCRE2 for `mysqltest` (which also points to the need for sanity check commands?)

**Comment by migueldiascosta** [comment]
@sassy-crick yes, that fixes running `mysql`, but I meant that `PCRE2` is needed as a regular dep, not just builddep, at least for running `mysqltest`, so it would be better to move it (?)

**Comment by migueldiascosta** [comment]
thanks @sassy-crick. I would also add `sanity_check_commands = ["mysql --help", "mysqltest --help"]` - it would have caught the problem, and so prevent it from happening again

**Comment by sassy-crick** [comment]
@migueldiascosta Done. Sorry for that!

**Comment by migueldiascosta** [comment]
@boegelbot please test @ generoso

**Review by migueldiascosta — APPROVED** [review]
lgtm

**Comment by migueldiascosta** [comment]
Going in, thanks @sassy-crick!

**Pull request merged**
