### PR TITLE
{devel,numlib}[dummy/dummy,foss/2018a] PyTorch v0.4.1, cuDNN v7.2.1.38

### PR DESCRIPTION
**Pull request by wpoely86**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by wpoely86** [comment]
Test report by @wpoely86
**SUCCESS**
Build succeeded for 3 out of 3 (3 easyconfigs in this PR)
nic419 - Linux centos linux 7.5.1804, Intel(R) Xeon(R) Gold 6148 CPU @ 2.40GHz, Python 2.7.5
See https://gist.github.com/e01091d9563e35376c4b22d4d3e5f598 for a full test report.

**Comment by boegel** [comment]
@wpoely86 The tests still fail, but for good reason now: two different versions of `magma` are being used as a dependency in the same toolchain generation.

Although since they're using different `CUDA` versions too, this may signal that we need to make the exception in the dep variant test a bit smarter?

**Comment by boegel** [comment]
@wpoely86 ping?

**Comment by boegel** [comment]
@lexming This is pretty ancient, my vote goes to just closing this...

**Pull request closed without merging**
