### PR TITLE
{vis}[GCCcore/10.3.0] GTK2 v2.24.33, GTK3 v3.24.29

### PR DESCRIPTION
**Pull request by jfgrimm**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by Micket** [comment]
I actually brought this up to the other maintainers a short while ago; should we separate GTK+ 2 and 3 versions like this, since there could potentially cause a conflict with something that needs both 2, 3 and/or 4 simultaneously.
Turns out there was such a case, so I approve of this. The only tricky part is that we already released stuff using the old method. 

I suppose there wouldn't really be any conflicts since it's the same software regardless, so it should be safe to have both the old and new namings exist for GCCcore 10.3.0. Any particular reson why this is marked as draft?

**Comment by jfgrimm** [comment]
> Any particular reason why this is marked as draft?
I wasn't sure if there was a particular reason for not splitting GTK+ sooner. Was planning on checking on slack, but I suppose that's redundant if it's been brought up before
It feels a bit funny duplicating the GTK builds for this generation (GTK+ and GTK2/3), but I don't think it's worth the effort changing all existing ECs to use GTK2/3 instead of GTK+ since it shouldn't cause any conflicts

**Comment by Micket** [comment]
In 4.4.1 released, nothing used GTK+2, and we didn't even include GTK+3 (for GCCcore 10.3.0).
Even in develop, there are just 4 things that use either. If we're reeaaaally quick we could maybe change it

**Comment by Micket** [comment]
For reference (since I looked this up myself): 
The GTK+ project rebranded as just GTK nowdays, so, skipping the + also makes sense to me, even for version 2 (else it might be a bit confusing with `GTK+2`, `GTK3`, `GTK4` )

**Review by Micket — APPROVED** [review]
lgtm

**Comment by Micket** [comment]
@boegelbot please test @ generoso

**Comment by Micket** [comment]
Test report by @Micket
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in total)
vera-c1 - Linux centos linux 7.9.2009, x86_64, Intel Xeon Processor (Skylake), Python 3.6.8
See https://gist.github.com/f658b5619d489b14ddbd99b5f00ca844 for a full test report.

**Comment by boegel** [comment]
> In 4.4.1 released, nothing used GTK+2, and we didn't even include GTK+3 (for GCCcore 10.3.0).
> Even in develop, there are just 4 things that use either. If we're reeaaaally quick we could maybe change it

Please open new a PR that makes those changes, and mark this PR as required (tests will fail), and mark it with the `4.4.2` milestone, I'll make sure it gets in.

**Comment by boegel** [comment]
@boegelbot please test @ generoso
CORE_CNT=16

**Comment by jfgrimm** [comment]
@Micket @boegel pr #13900 removes the 10.3.0 gen GTK+ easyconfigs, and updates the 4 ECs to use GTK2/GTK3 instead

**Comment by Micket** [comment]
What the heck happened at the generoso build? 
```
== 2021-09-03 15:45:51,835 modules.py:824 DEBUG Output of module command '/apps/modules/lmod/lmod/libexec/lmod python load Gdk-Pixbuf/2.42.6-GCCcore-10.3.0': stdout: _mlstatus = False
; stderr: Lmod has detected the following error: The following module(s) are unknown:
"X11/20210518-GCCcore-10.3.0"

Please check the spelling or version number. Also try "module spider ..."
It is also possible your cache file is out-of-date; it may help to try:
  $ module --ignore-cache load "X11/20210518-GCCcore-10.3.0"

Also make sure that all modulefiles written in TCL start with the string
#%Module

Executing this command requires loading "X11/20210518-GCCcore-10.3.0" which
failed while processing the following module(s):

    Module fullname                   Module Filename
    ---------------                   ---------------
    Gdk-Pixbuf/2.42.6-GCCcore-10.3.0  /users/boegelbot/CentOS8/haswell/modules/all/Gdk-Pixbuf/2.42.6-GCCcore-10.3.0.lua
```

It successfully built, and used, that very X11 for the GTK3 variant?

**Comment by branfosj** [comment]
Broken by the test in https://github.com/easybuilders/easybuild-easyconfigs/pull/13886#issuecomment-912037487 ?

**Comment by boegel** [comment]
I'll figure it out and fix it...

**Comment by boegel** [comment]
@boegelbot please test @ generoso
CORE_CNT=16

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in total)
node3129.skitty.os - Linux centos linux 7.9.2009, x86_64, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz, Python 3.6.8
See https://gist.github.com/d096b142f8a31f81efbc7ca375023fc9 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in total)
node3570.doduo.os - Linux RHEL 8.2, x86_64, AMD EPYC 7552 48-Core Processor (zen2), Python 3.6.8
See https://gist.github.com/019ec807a94bdf49f0eccc17dfbc081a for a full test report.

**Pull request merged**
