### PR TITLE
{bio}[dummy/dummy] I-TASSER v5.1

### PR DESCRIPTION
**Pull request by boegel**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
node2573.golett.os - Linux centos linux 7.3.1611, Intel(R) Xeon(R) CPU E5-2680 v3 @ 2.50GHz, Python 2.7.5
See https://gist.github.com/4b1ffea03117ae5e40c0fea5e69aca5d for a full test report.

**Comment by vanzod** [comment]
Test report by @vanzod
**FAILED**
Build succeeded for 0 out of 1 (1 easyconfigs in this PR)
cermis - Linux debian 8.8, Intel(R) Xeon(R) CPU           E5620  @ 2.40GHz, Python 2.7.9
See https://gist.github.com/f900648d3f760cb3196c3a0fbc3e12a4 for a full test report.

**Comment by boegel** [comment]
@vanzod requires manual download :)

**Comment by vanzod** [comment]
Going in, thanks @boegel!

**Pull request merged**
