### PR TITLE
{lib}[foss/2022a] epct v3.2.0

### PR DESCRIPTION
**Pull request by lexming**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by verdurin** [comment]
@lexming did you forget to add `GDAL/3.3.1` or do you need to adjust the version?

**Comment by lexming** [comment]
@boegelbot: please test @ generoso

**Comment by jfgrimm** [comment]
Test report by @jfgrimm
**FAILED**
Build succeeded for 2 out of 4 (1 easyconfigs in total)
node041.viking2.yor.alces.network - Linux Rocky Linux 8.8, x86_64, AMD EPYC 7643 48-Core Processor, Python 3.6.8
See https://gist.github.com/jfgrimm/2df9fabada2f510ca63731f2dc59ddc4 for a full test report.

**Comment by jfgrimm** [comment]
Test report by @jfgrimm
**SUCCESS**
Build succeeded for 2 out of 2 (1 easyconfigs in total)
node041.viking2.yor.alces.network - Linux Rocky Linux 8.8, x86_64, AMD EPYC 7643 48-Core Processor, Python 3.6.8
See https://gist.github.com/jfgrimm/468cfa8a2a308bd9f19a06ba771dd3b9 for a full test report.

**Review by jfgrimm — APPROVED** [review]
lgtm

**Pull request merged**
