### PR TITLE
Add TCLLIBPATH to Tk

### LINKED ISSUE #849: tk should set TCLLIBPATH
TCLLIBPATH should be set to $root/lib in all tk easyconfig's, 
so probably use modextrapaths

### PR DESCRIPTION
**Pull request by Micket**
(created using `eb --new-pr`)

Fixes #849

Only requires --moduleonly rebuilds.

### CODE REVIEW

**Comment by Micket** [comment]
@boegelbot please test @ jsc-zen3
EB_ARGS="--module-only"

**Comment by Micket** [comment]
@boegelbot please test @ jsc-zen3

**Comment by branfosj** [comment]
I do not think that `modextrapaths` is right for this.

> $[env](https://wiki.tcl-lang.org/page/env)(TCLLIBPATH) is a Tcl [list](https://wiki.tcl-lang.org/page/list), not some platform-specific colon-separated or semi-colon separated format, of paths to prepend to $[auto_path](https://wiki.tcl-lang.org/page/auto%5Fpath).

```
$ echo "puts $::auto_path" | tclsh
/usr/share/tcltk/tcl8.6 /usr/share/tcltk /usr/lib /usr/local/lib/tcltk /usr/local/share/tcltk /usr/lib/tcltk/x86_64-linux-gnu /usr/lib/tcltk /usr/lib/tcltk/tcl8.6

$ echo "puts $::auto_path" | TCLLIBPATH="/tmp/foo" tclsh
/tmp/foo /usr/share/tcltk/tcl8.6 /usr/share/tcltk /usr/lib /usr/local/lib/tcltk /usr/local/share/tcltk /usr/lib/tcltk/x86_64-linux-gnu /usr/lib/tcltk /usr/lib/tcltk/tcl8.6

$ echo "puts $::auto_path" | TCLLIBPATH="/tmp/foo:/tmp/bar" tclsh
/tmp/foo:/tmp/bar /usr/share/tcltk/tcl8.6 /usr/share/tcltk /usr/lib /usr/local/lib/tcltk /usr/local/share/tcltk /usr/lib/tcltk/x86_64-linux-gnu /usr/lib/tcltk /usr/lib/tcltk/tcl8.6

$ echo "puts $::auto_path" | TCLLIBPATH="/tmp/foo /tmp/bar" tclsh
/tmp/foo /tmp/bar /usr/share/tcltk/tcl8.6 /usr/share/tcltk /usr/lib /usr/local/lib/tcltk /usr/local/share/tcltk /usr/lib/tcltk/x86_64-linux-gnu /usr/lib/tcltk /usr/lib/tcltk/tcl8.6
```

**Comment by Micket** [comment]
Crap. Its not like we have any good options here either, since it relies on lmods prepend_path...

**Comment by Micket** [comment]
Ok i guess a framework or easybuild fix that uses the delim parameter for prepend_path?

**Comment by Micket** [comment]
No longer relevant

**Pull request closed without merging**
