### PR TITLE
{chem}[foss/2021a] AmberTools v21 w/ Python 3.9.5

### PR DESCRIPTION
**Pull request by fwautele**
(created using `eb --new-pr`)

### CODE REVIEW

**Review by boegel — CHANGES_REQUESTED** [review]
@fwautele The patch file being added in https://github.com/fwautele/easybuild-easyconfigs/pull/1 + the changes to the Amber easyblock in https://github.com/easybuilders/easybuild-easyblocks/pull/2720 should suffice to make this ready to go...

**Comment by bedroge** [comment]
I installed this easyconfig with the changes from @boegel's PR (and I added CUDA in order to enable GPU support), and using the updated easyblock, and that worked fine for me.

@fwautele are you up for including the changes proposed by @boegel (should be a matter of just merging the PR that he opened on your fork: https://github.com/fwautele/easybuild-easyconfigs/pull/1), so that this easyconfig can be added to the repository?

**Comment by boegel** [comment]
@boegelbot please test @ generoso

**Comment by boegel** [comment]
> I installed this easyconfig with the changes from @boegel's PR (and I added CUDA in order to enable GPU support), and using the updated easyblock, and that worked fine for me.
> 
> @fwautele are you up for including the changes proposed by @boegel (should be a matter of just merging the PR that he opened on your fork: [fwautele#1](https://github.com/fwautele/easybuild-easyconfigs/pull/1)), so that this easyconfig can be added to the repository?

@bedroge I've pushed the changes that I proposed in https://github.com/fwautele/easybuild-easyconfigs/pull/1 into this PR, so it should be ready to go now...

cc @akesandgren

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
node3142.skitty.os - Linux RHEL 8.4, x86_64, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz (skylake_avx512), Python 3.6.8
See https://gist.github.com/8a10443a015fc3a550cdd374c428bae7 for a full test report.

**Review by boegel — APPROVED** [review]

**Comment by boegel** [comment]
@boegelbot please test @ jsc-zen2

**Comment by boegel** [comment]
Going in, thanks @fwautele!

**Pull request merged**
