### PR TITLE
{bio}[foss/2018b] metaWRAP v1.2 w/ Python 2.7.15

### PR DESCRIPTION
**Pull request by boegel**
(created using `eb --new-pr`)
requires ~~#7579~~ (Kraken), ~~#7712~~ (CheckM),  ~~#7713~~ (QUAST), ~~#7721~~ (KronaTools), ~~#7746~~ (MetaBAT), ~~#7767~~ (MaxBin), ~~#7890~~ (bmtagger), ~~#7891~~ (CONCOCT), ~~#7892~~ (prokka) ~~#7893~~ (Trim_Galore), ~~#7894~~ (taxator-tk)

### CODE REVIEW

**Comment by vanzod** [comment]
Test report by @vanzod
**FAILED**
Build succeeded for 11 out of 13 (1 easyconfigs in this PR)
cermis - Linux debian 9.8, Intel(R) Xeon(R) CPU           X5670  @ 2.93GHz, Python 2.7.13
See https://gist.github.com/9da6c04eb52452bba938d7f82d360516 for a full test report.

**Comment by vanzod** [comment]
Test report by @vanzod
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
cermis - Linux debian 9.8, Intel(R) Xeon(R) CPU           X5670  @ 2.93GHz, Python 2.7.13
See https://gist.github.com/93e02a8332ee3ac23709eda4760bfb29 for a full test report.

**Comment by wpoely86** [comment]
Test report by @wpoely86
**FAILED**
Build succeeded for 26 out of 30 (1 easyconfigs in this PR)
nic408 - Linux centos linux 7.5.1804, Intel(R) Xeon(R) Gold 6148 CPU @ 2.40GHz, Python 2.7.5
See https://gist.github.com/52c385be121cab07d9d849055eb71ed5 for a full test report.

**Comment by boegel** [comment]
kicking Travis...

**Comment by boegel** [comment]
@wpoely86 `MetaBAT` failed for you with

```
src/BamUtils.h:21:10: fatal error: htslib/sam.h: No such file or directory
 #include "htslib/sam.h"
^~~~~~~~~~~~~~
```

Can you check if that's reproducible? Maybe you were running multiple tests in parallel?

**Comment by verdurin** [comment]
Test report by @verdurin
**FAILED**
Build succeeded for 38 out of 40 (1 easyconfigs in this PR)
rescomp2 - Linux centos linux 7.3.1611, Intel(R) Xeon(R) Gold 6126 CPU @ 2.60GHz, Python 2.7.5
See https://gist.github.com/b0d30f8da7a3c59923736b152d144ab0 for a full test report.

**Comment by wpoely86** [comment]
Test report by @wpoely86
**FAILED**
Build succeeded for 28 out of 30 (1 easyconfigs in this PR)
nic406 - Linux centos linux 7.5.1804, Intel(R) Xeon(R) Gold 6148 CPU @ 2.40GHz, Python 2.7.5
See https://gist.github.com/594202f979ecee1142356c079a9c1b16 for a full test report.

**Comment by boegel** [comment]
@verdurin checksum for `boot` was updated in #7814, you'll need to re-download that source tarball...

**Comment by boegel** [comment]
@wpoely86 Seems like the actual error is not included in the log for `Salmon-0.12.0-foss-2018b.eb`, can you check the full log (or retry with `eb --parallel 1`)?

**Comment by boegel** [comment]
@wpoely86 ping on this?

**Comment by wpoely86** [comment]
Test report by @wpoely86
**FAILED**
Build succeeded for 27 out of 29 (1 easyconfigs in this PR)
nic426 - Linux centos linux 7.5.1804, Intel(R) Xeon(R) Gold 6148 CPU @ 2.40GHz, Python 2.7.5
See https://gist.github.com/4b0409c03a7ca104a2ff48e21d2faa51 for a full test report.

**Comment by wpoely86** [comment]
Test report by @wpoely86
**SUCCESS**
Build succeeded for 29 out of 29 (1 easyconfigs in this PR)
login2.cerberus.os - Linux centos linux 7.6.1810, Intel(R) Xeon(R) Gold 6126 CPU @ 2.60GHz, Python 2.7.5
See https://gist.github.com/df2081af235c50fb28cff47b1e49d3d7 for a full test report.

**Comment by wpoely86** [comment]
Test report by @wpoely86
**FAILED**
Build succeeded for 27 out of 29 (1 easyconfigs in this PR)
nic4 - Linux centos linux 7.5.1804, AMD Opteron(tm) Processor 6134, Python 2.7.5
See https://gist.github.com/8008a7965eaadc288acc9f6af5df2cb2 for a full test report.

**Comment by wpoely86** [comment]
@boegel:

```
[ 36%] Performing configure step for 'libjemalloc'
cd /dev/shm/vsc10042/eb_sandbox_20190425_17-06-41_9rJAA/Salmon/0.12.0/foss-2018b/salmon-0.12.0/external/jemalloc-5.1.0 && sh -c "CC=/apps/brussel/CO7/magnycou
rs-ib/software/GCCcore/7.3.0/bin/gcc ./autogen.sh --disable-debug --prefix=/dev/shm/vsc10042/eb_sandbox_20190425_17-06-41_9rJAA/Salmon/0.12.0/foss-2018b/salmo
n-0.12.0/external/install"
autoconf
./autogen.sh: line 5: autoconf: command not found
Error 0 in autoconf
make[2]: *** [libjemalloc-prefix/src/libjemalloc-stamp/libjemalloc-configure] Error 1
make[2]: Leaving directory `/dev/shm/vsc10042/eb_sandbox_20190425_17-06-41_9rJAA/Salmon/0.12.0/foss-2018b/salmon-0.12.0'
make[1]: *** [CMakeFiles/libjemalloc.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
-- Performing Test HAVE_GCC_WALL - Success
-- Performing Test HAVE_GCC_FOMIT_FRAME_POINTER
[ 36%] Performing install step for 'libcereal'
```

The node were it worked had autoconf installed. Add as build dep or fix jemalloc?

**Comment by wpoely86** [comment]
sorry, wrong button

**Comment by wpoely86** [comment]
@boegel can you add Autotools as a build dep to `salmon`?

**Comment by boegel** [comment]
@wpoely86 I tried fixing this in #8264 by adding `jemalloc` as a proper dep, but for some reason unclear to me that results in hanging `make test`.

We could simply add `Autotools` as a build dep as an escape hatch of course...

**Comment by boegel** [comment]
@wpoely86 Please re-try now the `Salmon` problem is fixed via #8264?

**Comment by wpoely86** [comment]
Test report by @wpoely86
**FAILED**
Build succeeded for 24 out of 29 (1 easyconfigs in this PR)
nic72 - Linux centos linux 7.5.1804, Intel(R) Xeon(R) CPU E5-2680 v4 @ 2.40GHz, Python 2.7.5
See https://gist.github.com/4319022824be5273295fadd98335022f for a full test report.

**Comment by wpoely86** [comment]
Test report by @wpoely86
**SUCCESS**
Build succeeded for 29 out of 29 (1 easyconfigs in this PR)
nic425 - Linux centos linux 7.5.1804, Intel(R) Xeon(R) Gold 6148 CPU @ 2.40GHz, Python 2.7.5
See https://gist.github.com/aca0a5e6565f6267ba2935a46cf571d6 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
node2070.delcatty.os - Linux centos linux 7.6.1810, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.7.5
See https://gist.github.com/509399c45a57e87b833c170eb5ef8bd3 for a full test report.

**Comment by vanzod** [comment]
Test report by @vanzod
**SUCCESS**
Build succeeded for 2 out of 2 (1 easyconfigs in this PR)
cermis - Linux debian 9.9, Intel(R) Xeon(R) CPU           X5670  @ 2.93GHz, Python 2.7.13
See https://gist.github.com/e95b500d26a4a657469e89745062481b for a full test report.

**Pull request merged**
