### PR TITLE
Adding missing GNU time dependency to WRF 4.0.2 built with foss/2018b

### PR DESCRIPTION
**Pull request by dithwick**
(created using `eb --new-pr`)

### CODE REVIEW

**Review by branfosj — DISMISSED** [review]
lgtm

**Comment by branfosj** [comment]
@boegelbot please test @ generoso

**Comment by branfosj** [comment]
Failure seems to be (unless there was one higher in the log - before the bit we can see):
```
fatal error: rpc/types.h: No such file or directory
```

This suggests needing a dependency on https://github.com/easybuilders/easybuild-easyconfigs/blob/develop/easybuild/easyconfigs/l/libtirpc/libtirpc-1.1.4-GCCcore-7.3.0.eb

I'm currently running a test on CentOS 8 to see if I can confirm.

**Comment by dithwick** [comment]
Thanks @branfosj

**Comment by boegel** [comment]
@branfosj See also https://github.com/easybuilders/easybuild-easyconfigs/pull/11496#issuecomment-708652462

**Comment by dithwick** [comment]
I'll see if the patch with #11496 (comment) works first, if not I'll create one. I'll need someone to test on CentOS 8 though.

**Comment by boegel** [comment]
@boegelbot please test @ generoso

**Comment by boegel** [comment]
Test report by @boegel
**FAILED**
Build succeeded for 4 out of 5 (2 easyconfigs in total)
node3600.doduo.os - Linux RHEL 8.2, x86_64, AMD EPYC 7552 48-Core Processor (zen2), Python 3.6.8
See https://gist.github.com/eb72a0f855e2cbc83c881d6832d964a9 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in total)
node2609.swalot.os - Linux centos linux 7.9.2009, x86_64, Intel(R) Xeon(R) CPU E5-2660 v3 @ 2.60GHz (haswell), Python 3.6.8
See https://gist.github.com/017448ce0298cee537bb5fcfad8adf26 for a full test report.

**Comment by dithwick** [comment]
Hopefully this will work. Also flagging https://github.com/wrf-model/WRF/pull/1072 for reference.

**Comment by branfosj** [comment]
@boegelbot please test @ generoso

**Comment by branfosj** [comment]
Test report by @branfosj
**FAILED**
Build succeeded for 2 out of 3 (3 easyconfigs in total)
bear-pg0211u03a.bear.cluster - Linux centos linux 7.8.2003, x86_64, Intel(R) Xeon(R) Gold 6248 CPU @ 2.50GHz (cascadelake), Python 3.6.8
See https://gist.github.com/19b3009a9da3da9ee53dd1eae12bedff for a full test report.

**Comment by branfosj** [comment]
Test report by @branfosj
**SUCCESS**
Build succeeded for 3 out of 3 (3 easyconfigs in total)
bear-pg0211u03a.bear.cluster - Linux centos linux 7.8.2003, x86_64, Intel(R) Xeon(R) Gold 6248 CPU @ 2.50GHz (cascadelake), Python 3.6.8
See https://gist.github.com/f6d13ecda2bec5c8b07b6826daadd7db for a full test report.

**Review by branfosj — APPROVED** [review]
lgtm

**Comment by branfosj** [comment]
Going in, thanks @dithwick!

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 3 out of 3 (3 easyconfigs in total)
node2719.swalot.os - Linux centos linux 7.9.2009, x86_64, Intel(R) Xeon(R) CPU E5-2660 v3 @ 2.60GHz (haswell), Python 3.6.8
See https://gist.github.com/9cdfdb865b7dc18b485f6d292da534a9 for a full test report.

**Pull request merged**
