### PR TITLE
{bio,tools,vis}[foss/2023a] bin2cell v0.3.2, fastparquet v2024.11.0, stardist v0.8.5

### PR DESCRIPTION
**Pull request by pavelToman**
(created using `eb --new-pr`)
resolves https://github.com/vscentrum/vsc-software-stack/issues/458

### CODE REVIEW

**Comment by pavelToman** [comment]
@boegelbot please test @ generoso

**Comment by pavelToman** [comment]
Test report by @pavelToman
**FAILED**
Build succeeded for 0 out of 3 (3 easyconfigs in total)
node4001.donphan.os - Linux RHEL 8.8, x86_64, Intel(R) Xeon(R) Gold 6240 CPU @ 2.60GHz, 1 x NVIDIA NVIDIA A2, 545.23.08, Python 3.11.3
See https://gist.github.com/pavelToman/bff7517ba12cd4ca07459e21ada5c046 for a full test report.

**Comment by pavelToman** [comment]
Test report by @pavelToman
**SUCCESS**
Build succeeded for 3 out of 3 (3 easyconfigs in total)
node4001.donphan.os - Linux RHEL 8.8, x86_64, Intel(R) Xeon(R) Gold 6240 CPU @ 2.60GHz, 1 x NVIDIA NVIDIA A2, 545.23.08, Python 3.6.8
See https://gist.github.com/pavelToman/e37047a8c4da42adbf885977f676b085 for a full test report.

**Comment by verdurin** [comment]
Problem with `fastparquet`:
```
   checking for x86_64-unknown-linux-gnu-gcc... gcc
    checking whether the C compiler works... no

    --- stderr
    configure.ac:22: installing 'build-aux/compile'
    configure.ac:24: installing 'build-aux/config.guess'
    configure.ac:24: installing 'build-aux/config.sub'
    configure.ac:11: installing 'build-aux/install-sh'
    configure.ac:11: installing 'build-aux/missing'
    Makefile.am: installing 'build-aux/depcomp'
    parallel-tests: installing 'build-aux/test-driver'
    configure: error: in `/dev/shm/fastparquet/2024.11.0/gfbf-2023a/cramjam/cramjam-2.9.0/target/release/build/isal-sys-dec7c49f999ee0e3/out/isa-l':
    configure: error: C compiler cannot create executables
    See `config.log' for more details
    thread 'main' panicked at /dev/shm/fastparquet/2024.11.0/gfbf-2023a/easybuild_vendor/isal-sys-0.5.3+496255c/build.rs:72:17:
    configure failed
    note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
  warning: build failed, waiting for other jobs to finish...
   maturin failed
    Caused by: Failed to build a native library through cargo
    Caused by: Cargo build finished with "exit status: 101": `env -u CARGO PYO3_ENVIRONMENT_SIGNATURE="cpython-3.11-64bit" PYO3_PYTHON="/apps/eb/el8/upstream/software/Python/3.11.3-GCCcore-12.3.0/bin/python" PYTHON_SYS_EXECUTABLE="/apps/eb/el8/upstream/software/Python/3.11.3-GCCcore-12.3.0/bin/python" "cargo" "rustc" "--message-format" "json-render-diagnostics" "--manifest-path" "/dev/shm/fastparquet/2024.11.0/gfbf-2023a/cramjam/cramjam-2.9.0/Cargo.toml" "--release" "--lib" "--" "-C" "link-arg=-s"`
  Error: command ['maturin', 'pep517', 'build-wheel', '-i', '/apps/eb/el8/upstream/software/Python/3.11.3-GCCcore-12.3.0/bin/python', '--compatibility', 'off'] returned non-zero exit status 1
  error: subprocess-exited-with-error

   Building wheel for cramjam (pyproject.toml) did not run successfully.
   exit code: 1
  > See above for output.

  note: This error originates from a subprocess, and is likely not a problem with pip.
  full command: /apps/eb/el8/upstream/software/Python/3.11.3-GCCcore-12.3.0/bin/python /apps/eb/el8/upstream/software/Python/3.11.3-GCCcore-12.3.0/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py build_wheel /tmp/eb-b_l97xv_/tmpe3mssvti
  cwd: /dev/shm/fastparquet/2024.11.0/gfbf-2023a/cramjam/cramjam-2.9.0
  Building wheel for cramjam (pyproject.toml): finished with status 'error'
  ERROR: Failed building wheel for cramjam
Failed to build cramjam
ERROR: Could not build wheels for cramjam, which is required to install pyproject.toml-based projects
```

**Comment by pavelToman** [comment]
Lazy C compiler... could it be connected with lately changes in GCC? https://github.com/easybuilders/easybuild-easyblocks/pull/3254

**Comment by boegel** [comment]
@verdurin Can you check the `config.log` for a clue on why it concludes "`error: C compiler cannot create executables`"?

**Review by boegel — APPROVED** [review]

**Comment by boegel** [comment]
Going in, thanks @pavelToman!

**Comment by Micket** [comment]
for everyones information; the config.log would have revealed that it's definitely this glibc static libraries. I can reproduce this on my Rocky9 system, where i don't have glibc-static installed. 

Generally, not a great idea to statically link glibc, but this check is doing `-static`. I don't remember if EB expresses glibc-static as a OS requirement? It's very very rarely used.

**Comment by sassy-crick** [comment]
To add to this: I can confirm the same problem on both `RHEL-8` and a `Rocky-8.9` singularity container.

**Pull request merged**
