### PR TITLE
fix conflict with easybuild/system curl for SAMtools

### PR DESCRIPTION
**Pull request by SethosII**
(created using `eb --new-pr`)

Fixes https://github.com/easybuilders/easybuild-easyconfigs/issues/8100. Maybe this is also needed for other toolchains/versions.

### CODE REVIEW

**Comment by SethosII** [comment]
Test report by @SethosII
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
ribnode015 - Linux ubuntu 18.04, Intel(R) Xeon(R) CPU           E5645  @ 2.40GHz, Python 2.7.15rc1
See https://gist.github.com/9729a03901376f841da27957361ab717 for a full test report.

**Comment by vanzod** [comment]
@SethosII I went back to all the versions of `SAMtools` supported by EasyBuild and it seems that `cURL` is required starting from `SAMtools-1.4`. It would be nice if you could add this dependency to all the remaining easyconfig files in the PR.

**Comment by SethosII** [comment]
@vanzod I added `cURL` to all easyconfigs from version `1.4` onwards.

**Comment by SethosII** [comment]
I could need some help with the versions. I tried to check what `cURL` versions are used in other easyconfigs with the respective toolchain (`grep cURL easybuild/easyconfigs/*/*/*TOOLCHAIN.eb`) but the test still errors.

**Comment by boegel** [comment]
Fixing this for old `SAMtools` version while trying to avoid introducing conflicts on `cURL` may be more trouble than it's worth...
We've become a lot less careful with using multiple versions of (especially common) dependencies in recent toolchain generations, basically exactly for this reason.

I would stick to fixing this only for the more recent versions (say >= 1.7) in this PR, and maybe make another attempt in a follow-up PR for the older versions if really needed?

**Comment by vanzod** [comment]
@boegel Sounds reasonable.

@SethosII Sorry for the extra trouble I put you through

**Comment by SethosII** [comment]
@boegel I reverted adding `cURL` for versions below 1.7.

@vanzod No big deal.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 7 out of 7 (7 easyconfigs in this PR)
node3118.skitty.os - Linux centos linux 7.6.1810, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz, Python 2.7.5
See https://gist.github.com/17128bde09197052080e0136a6c1956f for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**FAILED**
Build succeeded for 15 out of 16 (16 easyconfigs in this PR)
node2006.delcatty.os - Linux centos linux 7.6.1810, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.7.5
See https://gist.github.com/27331826f68c904ec4a41b5ad916b1ff for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 9 out of 9 (7 easyconfigs in this PR)
node2434.golett.os - Linux centos linux 7.6.1810, Intel(R) Xeon(R) CPU E5-2680 v3 @ 2.50GHz, Python 2.7.5
See https://gist.github.com/99a82cbd88f99db565b65daf4cbab628 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 16 out of 16 (16 easyconfigs in this PR)
node2006.delcatty.os - Linux centos linux 7.6.1810, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.7.5
See https://gist.github.com/66659990b23be7754af9ea2d6bbb2ded for a full test report.

**Comment by boegel** [comment]
Going in, thanks @SethosII!

**Pull request merged**
