### PR TITLE
{lang}[GCCcore/12.2.0] Python v3.11.2-bare

### PR DESCRIPTION
**Pull request by robogast**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by robogast** [comment]
Test report by @robogast
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
gcn3.local.snellius.surf.nl - Linux Rocky Linux 8.7, x86_64, Intel(R) Xeon(R) Platinum 8360Y CPU @ 2.40GHz, 4 x NVIDIA NVIDIA A100-SXM4-40GB, 515.86.01, Python 3.6.8
See https://gist.github.com/829d53f47784014f0e4cc7e7bb13e863 for a full test report.

**Comment by jfgrimm** [comment]
Test report by @jfgrimm
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
himem05.pri.viking.alces.network - Linux CentOS Linux 7.9.2009, x86_64, Intel(R) Xeon(R) Gold 6230 CPU @ 2.10GHz (cascadelake), Python 3.6.8
See https://gist.github.com/e37e1dd6a05e1d1348868b22f8ad0514 for a full test report.

**Comment by sassy-crick** [comment]
Test report by @sassy-crick
**FAILED**
Build succeeded for 0 out of 1 (1 easyconfigs in total)
hp - Linux Debian GNU/Linux 11, x86_64, 11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz, Python 3.9.2
See https://gist.github.com/d8dee527c573474aab745ed881f6debf for a full test report.

**Comment by jfgrimm** [comment]
@boegelbot please test @ generoso

**Comment by sassy-crick** [comment]
Test report by @sassy-crick
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
hp - Linux Debian GNU/Linux 11, x86_64, 11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz, Python 3.9.2
See https://gist.github.com/7ad164cb6a9aa494cbbf87d670c15687 for a full test report.

**Comment by jfgrimm** [comment]
@boegelbot please test @ jsc-zen2

**Review by jfgrimm — APPROVED** [review]
lgtm

**Comment by jfgrimm** [comment]
Going in, thanks @robogast!

**Pull request merged**
