### PR TITLE
{tools}[foss/2021b] OpenAI-Gym v0.21.0 w/ Python 3.9.6

### PR DESCRIPTION
**Pull request by lexming**
(created using `eb --new-pr`)

Depends on:

- [x] #14753 
- [x] #14776 
- [x] #14774 
- [x] #14965

### CODE REVIEW

**Comment by boegel** [comment]
Test report by @boegel
**FAILED**
Build succeeded for 0 out of 1 (1 easyconfigs in total)
node3119.skitty.os - Linux UNKNOWN UNKNOWN, x86_64, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz, Python 3.6.8
See https://gist.github.com/67a5c88672cdfc3194533b335d3e40fa for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
node3523.doduo.os - Linux UNKNOWN UNKNOWN, x86_64, AMD EPYC 7552 48-Core Processor (zen2), Python 3.6.8
See https://gist.github.com/d33d99f6019ebc7d4d65de8f42aeae1b for a full test report.

**Comment by boegel** [comment]
@lexming Failed test report is with read-only install dir configuration, the import check tries to change something in the installation?!

**Comment by lexming** [comment]
soooo... `mujoco-py` tries to create a lock in the library directory of MuJoCo /facepalm

```
builder = Builder(mujoco_path)
cext_so_path = builder.get_so_file_path()

lockpath = os.path.join(os.path.dirname(cext_so_path), 'mujocopy-buildlock')
```
There are already open issues about it at https://github.com/openai/mujoco-py/issues/424 and https://github.com/openai/mujoco-py/issues/533

I'll make a patch to use a temp dir instead

**Comment by lexming** [comment]
@boegel should be fixed in #14965

**Comment by migueldiascosta** [comment]
@boegelbot please test @ generoso

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
node3120.skitty.os - Linux CentOS Linux 7.9.2009, x86_64, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz, Python 3.6.8
See https://gist.github.com/a9c7528375956f853b7557c407e37a6a for a full test report.

**Review by boegel — APPROVED** [review]
lgtm

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
node3623.doduo.os - Linux RHEL 8.4, x86_64, AMD EPYC 7552 48-Core Processor (zen2), Python 3.6.8
See https://gist.github.com/81c303c8e89231ffaaf5d3d82fd8dd7a for a full test report.

**Pull request merged**
