### PR TITLE
{bio} [foss/2018b] pySCENIC 0.9.7

### PR DESCRIPTION
**Pull request by wpoely86**
This needs ~#8029~, #7625

### CODE REVIEW

**Comment by wpoely86** [comment]
Test report by @wpoely86
**SUCCESS**
Build succeeded for 7 out of 7 (7 easyconfigs in this PR)
nic410 - Linux centos linux 7.5.1804, Intel(R) Xeon(R) Gold 6148 CPU @ 2.40GHz, Python 2.7.5
See https://gist.github.com/591dd144a486a2b048e22a5ef9d67dc7 for a full test report.

**Comment by boegel** [comment]
@wpoely86 How do we proceed with this now #7625 got closed?

**Comment by wpoely86** [comment]
I dunno. Moving it over to 2019a is a lot of work with the multidep stuff.

**Comment by boegel** [comment]
@wpoely86 Is this still relevant given #11115 ?

**Comment by wpoely86** [comment]
I guess not if you have a newer version working.

**Pull request closed without merging**
