### PR TITLE
disable optarch when using intel compilers and enable tests in all libxc-3.0.0 easyconfigs

### PR DESCRIPTION
**Pull request by migueldiascosta**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by migueldiascosta** [comment]
Test report by @migueldiascosta
**SUCCESS**
Build succeeded for 4 out of 4 (4 easyconfigs in this PR)
grc-cluster1 - Linux centos 6.9, Intel(R) Xeon(R) CPU E5-2640 0 @ 2.50GHz, Python 2.6.6
See https://gist.github.com/db3d85ee7c22958a9e775730dcad66c0 for a full test report.

**Comment by migueldiascosta** [comment]
Test report by @migueldiascosta
**SUCCESS**
Build succeeded for 4 out of 4 (4 easyconfigs in this PR)
grc-e11 - Linux centos 6.9, Intel(R) Xeon(R) CPU E5-2680 v3 @ 2.50GHz, Python 2.6.6
See https://gist.github.com/263ce4c7298341a6091346452d7c9ebb for a full test report.

**Comment by boegel** [comment]
@migueldiascosta `optarch` is not set to `False` in 1st easyconfig?

Also, maybe include a comment to mention why it's disabled? I'd mention failing tests on Haswell?

**Comment by boegel** [comment]
Test report by @boegel
**FAILED**
Build succeeded for 7 out of 9 (4 easyconfigs in this PR)
node2579.golett.os - Linux centos linux 7.4.1708, Intel(R) Xeon(R) CPU E5-2680 v3 @ 2.50GHz, Python 2.7.5
See https://gist.github.com/5c4b4acf7ec6f9c84bdeb60eb4af7565 for a full test report.

**Comment by boegel** [comment]
@migueldiascosta `test-suite.log` for failing `libxc-3.0.0-intel-2016b.eb` available at https://gist.github.com/boegel/58c420335f9914544ba4633d584000c5

**Comment by boegel** [comment]
Test report by @boegel
**FAILED**
Build succeeded for 3 out of 4 (4 easyconfigs in this PR)
node2594.golett.os - Linux centos linux 7.4.1708, Intel(R) Xeon(R) CPU E5-2680 v3 @ 2.50GHz, Python 2.7.5
See https://gist.github.com/198c98a2ad2a1e53ef6364b8ddb24eca for a full test report.

**Comment by boegel** [comment]
Tests were failing because `intel/2016b` was still using the buggy `libintlc.so.5` which was causing segfaults, cfr. https://github.com/easybuilders/easybuild-easyconfigs/issues/3646#issuecomment-273125319

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 4 out of 4 (4 easyconfigs in this PR)
node2594.golett.os - Linux centos linux 7.4.1708, Intel(R) Xeon(R) CPU E5-2680 v3 @ 2.50GHz, Python 2.7.5
See https://gist.github.com/943189ea21390c57609afecf49d4ac3c for a full test report.

**Comment by boegel** [comment]
Going in, thanks @migueldiascosta!

**Pull request merged**
