### PR TITLE
{lib}[GCCcore/7.3.0] CFITSIO v3.45

### PR DESCRIPTION
**Pull request by dquigley-warwick**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by dquigley-warwick** [comment]
Test report by @dquigley-warwick
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
brigitte.csc.warwick.ac.uk - Linux centos linux 7.6.1810, Intel(R) Xeon(R) CPU E5-2620 v3 @ 2.40GHz, Python 2.7.5
See https://gist.github.com/6976f516599ded2a8c3ab95c5be97855 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
node3102.skitty.os - Linux centos linux 7.6.1810, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz, Python 2.7.5
See https://gist.github.com/e982633a288da1897e382c8b23f26b1e for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
node2594.golett.os - Linux centos linux 7.5.1804, Intel(R) Xeon(R) CPU E5-2680 v3 @ 2.50GHz, Python 2.7.5
See https://gist.github.com/8ecc28e7c8b48d1e233a1ca018632507 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
node2106.delcatty.os - Linux centos linux 7.5.1804, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.7.5
See https://gist.github.com/76c126a1f6ff06f7c74eccc843780211 for a full test report.

**Comment by boegel** [comment]
Going in, thanks @dquigley-warwick!

**Pull request merged**
