### PR TITLE
{bio}[GCCcore/10.3.0,gompi/2021a] IQ-TREE v2.1.3, LSD2 v2.3

### PR DESCRIPTION
**Pull request by manifestoso**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by manifestoso** [comment]
Test report by @robqiao
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in total)
hpc-head01 - Linux UNKNOWN UNKNOWN, x86_64, Intel(R) Xeon(R) Gold 6130 CPU @ 2.10GHz, Python 3.9.0
See https://gist.github.com/7b768d4487557ed65b81c5fd41444011 for a full test report.

**Comment by lexming** [comment]
@boegelbot: please test @ generoso

**Comment by lexming** [comment]
Test report by @lexming
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in total)
node301.hydra.os - Linux centos linux 7.9.2009, x86_64, Intel(R) Xeon(R) Gold 6148 CPU @ 2.40GHz, Python 2.7.5
See https://gist.github.com/3ead38a1808e68c94af04297a546b2e7 for a full test report.

**Review by lexming — APPROVED** [review]
LGTM

**Comment by lexming** [comment]
Going in, thanks @manifestoso !

**Pull request merged**
