### PR TITLE
add missing link to Library Path for Faiss

### PR DESCRIPTION
**Pull request by laraPPr**
(created using `eb --new-pr`)

### CODE REVIEW

**Review by Micket — APPROVED** [review]
lgtm

**Comment by Micket** [comment]
@boegelbot please test @ jsc-zen3

**Comment by laraPPr** [comment]
I'm trying to rebuild it myself but it keeps failing to set the variables in the `cmake` command and I can't figure out why. 
```
== 2024-11-07 15:24:52,624 easyconfig.py:2040 WARNING Unable to resolve template value 
-DCMAKE_INSTALL_PREFIX=/data/gent/vo/000/gvo00002/vsc46128/easybuild/RHEL8/cascadelake-ampere-ib/software/Faiss/1.7.4-foss-2023a-CUDA-12.1.1 
-DCMAKE_BUILD_TYPE=Release 
-DCMAKE_POLICY_DEFAULT_CMP0094=NEW 
-DCMAKE_VERBOSE_MAKEFILE=ON 
-DCMAKE_FIND_USE_PACKAGE_REGISTRY=OFF 
-DFAISS_ENABLE_GPU=ON 
-DFAISS_ENABLE_PYTHON=ON 
-DFAISS_ENABLE_C_API=ON 
-DBUILD_TESTING=ON -DBUILD_SHARED_LIBS=ON     
-DPython_EXECUTABLE="${EBROOTPYTHON}/bin/python" 
-DCUDAToolkit_ROOT="${CUDA_ROOT}" 
-DCMAKE_CUDA_ARCHITECTURES="%(cuda_cc_cmake)s" 
-DCMAKE_INSTALL_LIBDIR=%(installdir)s/lib 
with dict {'arch': 'x86_64', 'sysroot': '', 'software_commit': '', 'nameletter': 'F', 'toolchain_name': 'foss', 'toolchain_version': '2023a', 'version_major': '1', 'version_minor': '7', 'version_major_minor': '1.7', 'cudaver': '12.1.1', 'cudamajver': '12', 'cudaminver': '1', 'cudashortver': '12    .1', 'pyver': '3.11.3', 'pymajver': '3', 'pyminver': '11', 'pyshortver': '3.11', 'bitbucket_account': 'faiss', 'github_account': 'facebookresearch', 'name': 'Faiss', 'version': '1.7.4', 'versionsuffix': '-CUDA-12.1.1', 'versionprefix' : '', 'namelower': 'faiss', 'nameletterlower': 'f', 'mpi_cmd_prefix': 'mpirun -n 1', 'module_name': 'Faiss/1.7.4-foss-2023a-CUDA-12.1.1', 'builddir': '/tmp/vsc46128/Faiss/1.7.4/foss-2023a-CUDA-12.1.1', 'installdir': '/data/gent/vo/000    /gvo00002/vsc46128/easybuild/RHEL8/cascadelake-ampere-ib/software/Faiss/1.7.4-foss-2023a-CUDA-12.1.1', 'start_dir': '/tmp/vsc46128/Faiss/1.7.4/foss-2023a-CUDA-12.1.1/faiss-1.7.4/', 'parallel': '8'}
```
It seems that `cuda_cc_cmake` is missing but I set `cuda_cc` am I missing something else?

**Comment by laraPPr** [comment]
Sorry I thought I was setting the `--cuda-compute-capabilities=xxxx` in a hook but their was a problem their. It is building now.

**Pull request merged**
