### PR TITLE
remove ignored `toolchainopts` from `SYSTEM` toolchain easyconfigs

### PR DESCRIPTION
**Pull request by branfosj**
(created using `eb --new-pr`)

related to https://github.com/easybuilders/easybuild-framework/issues/4584

### CODE REVIEW

**Comment by branfosj** [comment]
Test report by @branfosj
**SUCCESS**
Build succeeded for 15 out of 15 (14 easyconfigs in total)
bear-pg0105u03a - Linux RHEL 8.6, x86_64, Intel(R) Xeon(R) Platinum 8360Y CPU @ 2.40GHz (icelake), Python 3.6.8
See https://gist.github.com/branfosj/b1cc985c819cefe52c39bcbb398a1cc5 for a full test report.

**Review by ocaisa — APPROVED** [review]
This PR means the easyconfigs now reflect reality (the `toolchainopts` were never used)

**Comment by ocaisa** [comment]
@boegelbot please test @ jsc-zen3

**Comment by ocaisa** [comment]
@boegelbot please test @ generoso

**Comment by ocaisa** [comment]
Test report by @ocaisa
**FAILED**
Build succeeded for 13 out of 14 (14 easyconfigs in total)
login1 - Linux Rocky Linux 8.9, x86_64, Intel(R) Xeon(R) CPU E5-2667 v3 @ 3.20GHz, Python 3.6.8
See https://gist.github.com/ocaisa/37b75c6a4faac57fc73ac5e362103eaf for a full test report.

**Comment by ocaisa** [comment]
LGTM, not holding this back because of an existing problem with the `SYSYEM` Perl easyconfig (likely system specific)

**Pull request merged**
