### PR TITLE
{bio}[gompi/2022a] MrBayes v3.2.7

### PR DESCRIPTION
**Pull request by smoors**
(created using `eb --new-pr`)
depends on:
- https://github.com/easybuilders/easybuild-easyconfigs/pull/17361

### CODE REVIEW

**Comment by smoors** [comment]
@boegelbot: please test @ generoso

**Comment by lexming** [comment]
@boegelbot: please test @ generoso

**Comment by Micket** [comment]
Test report by @Micket
**SUCCESS**
Build succeeded for 5 out of 5 (1 easyconfigs in total)
alvis-c1 - Linux Rocky Linux 8.6, x86_64, Intel Xeon Processor (Skylake), Python 3.6.8
See https://gist.github.com/a9538033c8022dd90bd2bfdff8082ca8 for a full test report.

**Review by lexming — APPROVED** [review]
LGTM

**Comment by lexming** [comment]
@boegelbot please test @ jsc-zen2

**Comment by lexming** [comment]
Going in, thanks @smoors !

**Pull request merged**
