### PR TITLE
disable building documentation for libsigc++ 2.10.x

### LINKED ISSUE #18292: libsigc++-2.10.8 requires docbook stylesheet for building the documentation
I ran into the following when building `libsigc++-2.10.8-GCCcore-10.3.0.eb` in a quite minimal Rocky 8 container:
```
make[2]: Entering directory '/dev/shm/p251204/libsigc/2.10.8/GCCcore-10.3.0/libsigc++-2.10.8/docs'
  GEN      reference/libsigc++-2.0.tag
  GEN      manual/html/index.html
warning: Tag 'CLANG_ASSISTED_PARSING' at line 144 of file 'reference/Doxyfile' belongs to an option that was not enabled at compile time.
         To avoid this warning please remove this line from your configuration file or upgrade it using "doxygen -u", or recompile doxygen with this feature enabled.
warning: Tag 'CLANG_OPTIONS' at line 145 of file 'reference/Doxyfile' belongs to an option that was not enabled at compile time.
         To avoid this warning please remove this line from your configuration file or upgrade it using "doxygen -u", or recompile doxygen with this feature enabled.
Variable $SGML_CATALOG_FILES not set
error : Unknown IO error
warning: failed to load external entity "http://docbook.sourceforge.net/release/xsl/current/html/chunk.xsl"
cannot parse http://docbook.sourceforge.net/release/xsl/current/html/chunk.xsl
```

This looked similar to https://github.com/easybuilders/easybuild-easyconfigs/issues/8893, so I tried adding `docbook-style-xsl` to the container, which solved the issue. Disabling the documentation, as was done for #8893 in #13410, is also possible by adding `configopts = "--disable-documentation"`. I'm not sure if `libsigc++ 3` has the same issue.

### PR DESCRIPTION
**Pull request by bedroge**
Fixes #18292.

### CODE REVIEW

**Comment by bedroge** [comment]
@boegelbot please test @ generoso

**Comment by bedroge** [comment]
Test report by @bedroge
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
interactive2 - Linux Rocky Linux 8.7, x86_64, AMD EPYC-Milan Processor (zen2), Python 3.6.8
See https://gist.github.com/bedroge/63256b5ba020ace0f336c819cd8bb275 for a full test report.

**Comment by bedroge** [comment]
@boegelbot please test @ jsc-zen2

**Review by branfosj — APPROVED** [review]

**Comment by branfosj** [comment]
Test report by @branfosj
**SUCCESS**
Build succeeded for 8 out of 8 (4 easyconfigs in total)
bear-pg0211u03a.bear.cluster - Linux RHEL 8.6, x86_64, Intel(R) Xeon(R) Gold 6248 CPU @ 2.50GHz (cascadelake), Python 3.6.8
See https://gist.github.com/branfosj/f52ac65c041b39682a3bb8b2e7d3a76d for a full test report.

**Comment by branfosj** [comment]
Going in, thanks @bedroge!

**Pull request merged**
