### PR TITLE
Disable ParaView tests

### PR DESCRIPTION
**Pull request by hajgato**
The ParaView server can be cranky, test downloads are quite often failing, especially in the case of parallel downloads. This make fail the build. I disabled the tests by default.

### CODE REVIEW

**Comment by boegel** [comment]
@hajgato: please update the description with some motivation, because this is very different from how things are now...

**Comment by hajgato** [comment]
@boegel done

**Comment by boegel** [comment]
@hajgato: I meant the description of the PR itself, but updating the comments is OK too ;)

I won't merge this one for EB v2.5.0 too, too 'dangerous' imho, I'd like to take the time to test this thoroughly (rebuild ParaView + OpenFOAM on top).

**Comment by hajgato** [comment]
@boegel What about with `OpenFOAM`? Will it be merged? Or it has to wait to `ParaView` as well?

**Comment by boegel** [comment]
@hajgato: I'm trying to get the OpenFOAM PRs merged (several already are) for EB v2.5.0, I don't consider this change a blocker, since this is mostly about trying to make the ParaView build more robust 

It works, but not always due to problems with upstream. We can try to be more robust against stuff like that, but it's never going to be perfect, so no reason to block other stuff for it.

**Comment by wpoely86** [comment]
This issue also has been biting me. :+1: for merging

**Comment by boegel** [comment]
test report?

**Comment by wpoely86** [comment]
Test report by @wpoely86
**FAILED**
Build succeeded for 24 out of 28 (4 easyconfigs in this PR)
Linux SL 6.7, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.6.6
See https://gist.github.com/dff846e2b0780d6ab1bd for a full test report.

**Comment by wpoely86** [comment]
@hajgato Can you add the download url for older mesa to the `source_urls` list?
`ftp://ftp.freedesktop.org/pub/mesa/older-versions/10.x/10.5.5/`

**Comment by wpoely86** [comment]
Test report by @wpoely86
**FAILED**
Build succeeded for 24 out of 28 (4 easyconfigs in this PR)
Linux SL 6.7, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.6.6
See https://gist.github.com/c253398d1bce977024c8 for a full test report.

**Comment by wpoely86** [comment]
Test report by @wpoely86
**SUCCESS**
Build succeeded for 28 out of 28 (4 easyconfigs in this PR)
Linux SL 6.7, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.6.6
See https://gist.github.com/522df20dca86eeb595f5 for a full test report.

**Comment by wpoely86** [comment]
@hajgato can you merge develop so that this can be merged?

@boegel good to go

**Comment by boegel** [comment]
@hajgato needs another sync with develop?

**Comment by migueldiascosta** [comment]
@hajgato, this PR is being closed for the following reason(s): no activity for > 6 months, obsoleted by more recent PRs.
Please don't hesitate to reopen this PR or add a comment if you feel this contribution is still relevant.
For more information on our policy w.r.t. closing PRs, see https://easybuild.readthedocs.io/en/latest/Contributing.html#why-a-pull-request-may-be-closed-by-a-maintainer

**Pull request closed without merging**
