### PR TITLE
add bbmle/emdbook/SOAR/rasterVis/tictoc extensions to R 3.6.0 easyconfigs

### PR DESCRIPTION
**Pull request by boegel**

### CODE REVIEW

**Comment by boegel** [comment]
Test report by @boegel
**FAILED**
Build succeeded for 0 out of 2 (2 easyconfigs in this PR)
node3116.skitty.os - Linux centos linux 7.6.1810, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz, Python 3.6.8
See https://gist.github.com/e268bb23026c903b110df8cd4cbb78f1 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**FAILED**
Build succeeded for 1 out of 2 (2 easyconfigs in this PR)
node2065.delcatty.os - Linux centos linux 7.6.1810, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.7.5
See https://gist.github.com/3ce4da966f915cc2f52790feb0ba0c8c for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in this PR)
node2695.swalot.os - Linux centos linux 7.6.1810, Intel(R) Xeon(R) CPU E5-2660 v3 @ 2.60GHz, Python 2.7.5
See https://gist.github.com/5daaf61a9811db5b607e1c18ed1ed072 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in this PR)
node2065.delcatty.os - Linux centos linux 7.6.1810, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.7.5
See https://gist.github.com/2b2ad4d9280c3bc22766ec6cdeba6848 for a full test report.

**Comment by bartoldeman** [comment]
Test report by @bartoldeman
**FAILED**
Build succeeded for 11 out of 16 (1 easyconfigs in this PR)
lg-1r17-n02 - Linux centos 6.6, Intel(R) Xeon(R) CPU E5-2650 0 @ 2.00GHz, Python 2.6.6
See https://gist.github.com/60190e76054ac56a592fd414ac4efa32 for a full test report.

**Comment by bartoldeman** [comment]
Seems my build errored out on `ICU-64.2-GCCcore-8.2.0.eb` which uses system python somewhere.

**Comment by bartoldeman** [comment]
Test report by @bartoldeman
**FAILED**
Build succeeded for 0 out of 1 (1 easyconfigs in this PR)
lg-1r17-n02 - Linux centos 6.6, Intel(R) Xeon(R) CPU E5-2650 0 @ 2.00GHz, Python 2.6.6
See https://gist.github.com/38842650712f621e1860cade7edbc102 for a full test report.

**Comment by bartoldeman** [comment]
next a download issue with h2o, retrying:
```
Performing one-time download of h2o.jar from
     http://s3.amazonaws.com/h2o-release/h2o/rel-xu/1/Rjar/h2o.jar 
(This could take a few minutes, please be patient...)
Warning in download.file(url = h2o_url, destfile = temp_file, mode = "wb",  :
  downloaded length 536189 != reported length 129285791
Warning in download.file(url = h2o_url, destfile = temp_file, mode = "wb",  :
  URL 'http://s3.amazonaws.com/h2o-release/h2o/rel-xu/1/Rjar/h2o.jar': status was 'Failure when receiving data from the peer'
Error in download.file(url = h2o_url, destfile = temp_file, mode = "wb",  : 
  download from 'http://s3.amazonaws.com/h2o-release/h2o/rel-xu/1/Rjar/h2o.jar' failed
Error: unable to load R code in package h2o
Execution halted
```

**Comment by bartoldeman** [comment]
Test report by @bartoldeman
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
lg-1r17-n02 - Linux centos 6.6, Intel(R) Xeon(R) CPU E5-2650 0 @ 2.00GHz, Python 2.6.6
See https://gist.github.com/5958b890d082d4b010cad3540dede8ca for a full test report.

**Comment by bartoldeman** [comment]
Going in, thanks @boegel!

**Pull request merged**
