### PR TITLE
{cae}[foss/2018b] OpenFOAM v1612+

### PR DESCRIPTION
**Pull request by boegel**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
node2608.swalot.os - Linux centos linux 7.6.1810, Intel(R) Xeon(R) CPU E5-2660 v3 @ 2.60GHz, Python 2.7.5
See https://gist.github.com/c33bf5a555330394fadaeba61bbdf6db for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
node3149.skitty.os - Linux centos linux 7.6.1810, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz, Python 2.7.5
See https://gist.github.com/78ce467b2ab56834fdea28977c6a0b5f for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
node2119.delcatty.os - Linux centos linux 7.6.1810, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.7.5
See https://gist.github.com/052da9de640e6328838bf3eb5998c79a for a full test report.

**Comment by bartoldeman** [comment]
Test report by @bartoldeman
**FAILED**
Build succeeded for 6 out of 10 (1 easyconfigs in this PR)
lg-1r17-n06 - Linux centos 6.6, Intel(R) Xeon(R) CPU E5-2650 0 @ 2.00GHz, Python 2.6.6
See https://gist.github.com/a011a2c19859fd60bb0560a804896302 for a full test report.

**Comment by boegel** [comment]
@bartoldeman Any idea why the `libQt5WebEngine.so` part of `Qt5` failed to get built?

**Comment by bartoldeman** [comment]
@boegel Found this in the logs:
```
A suitable version of libc could not be found. See: https://sourceware.org/bugzilla/show_bug.cgi?id=14898
QtWebEngine will not be built.
```

**Comment by boegel** [comment]
@bartoldeman Ah yes, that's an issue on CentOS 6...

You can try to disable checking for the `QtWebEngine` part by using this in the easyconfig file:

```python
check_qtwebengine = False
```

(or just removing that, since the check is not enabled by default)

**Comment by bartoldeman** [comment]
Yes, it's CentOS 6. Same issue happens with `Qt5-5.12.3-GCCcore-8.2.0.eb`

**Comment by bartoldeman** [comment]
Test report by @bartoldeman
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
lg-1r17-n06 - Linux centos 6.6, Intel(R) Xeon(R) CPU E5-2650 0 @ 2.00GHz, Python 2.6.6
See https://gist.github.com/b9e11942cdecef72b1e26b8f4c4a82f7 for a full test report.

**Comment by bartoldeman** [comment]
Going in, thanks @boegel!

**Pull request merged**
