### PR TITLE
{chem}[GCC/13.3.0,foss/2024a] libxc v6.2.2, QuantumESPRESSO v7.3.1

### PR DESCRIPTION
**Pull request by maxim-masterov**
(created using `eb --new-pr`)

Depends on:
- HDF5 from https://github.com/easybuilders/easybuild-easyconfigs/pull/21570
- <s>ELPA from https://github.com/easybuilders/easybuild-easyconfigs/pull/21560</s>

### CODE REVIEW

**Comment by SebastianAchilles** [comment]
Test report by @sebastianachilles
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in total)
skl-rockylinux-810 - Linux Rocky Linux 8.10, x86_64, Intel(R) Core(TM) i7-10700 CPU @ 2.90GHz (skylake), 1 x NVIDIA NVIDIA RTX A4000, 555.42.06, Python 3.6.8
See https://gist.github.com/SebastianAchilles/431d76bc11ab37cd96848828afe5e513 for a full test report.

**Comment by SebastianAchilles** [comment]
@boegelbot please test @ jsc-zen3
CORE_CNT=16

**Comment by SebastianAchilles** [comment]
@boegelbot please test @ generoso
CORE_CNT=16

**Review by smoors — APPROVED** [review]
lgtm

**Comment by smoors** [comment]
Going in, thanks @maxim-masterov!

**Pull request merged**
