### PR TITLE
{devel}[dummy/] ant v1.10.5

### PR DESCRIPTION
**Pull request by smoors**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by boegel** [comment]
@smoors Any reason you're using the binary version rather than building from source?

**Comment by smoors** [comment]
yes, the sources do not build for versions >=1.10.2. it seems that a number of 'optional' libraries are actually required. I gave up after `adding commons-net` and `JSch` to both the easyconfig and easyblock.

**Comment by boegel** [comment]
@smoors We should consider letting `ant` use the `Java` wrapper we're adding in #6712, to make sure this new version is compatible with `*2018b*` easyconfigs.

Also, I wonder whether we should drop the `binary` from the versionsuffix, since the installation is basically a bash script + a `.jar` files (i.e. no actual binaries)...

**Comment by smoors** [comment]
@boegel 
I did not do this because #6712 is not merged yet :)
to be sure I understand how it works: we specify Java 1.8 in the easyconfig, and the (default) exact version is defined in the .modulerc file? can users override this with a ~/.modulerc file?

dropping the `binary`, is fine for me. Java binaries are just bytecode, so the differences with the compiled version are probably minor.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
node3151.skitty.os - Linux centos linux 7.5.1804, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz, Python 2.7.5
See https://gist.github.com/e4abf812c4e12e132714f000568ab2c0 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
node2037.delcatty.os - Linux centos linux 7.5.1804, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.7.5
See https://gist.github.com/d0caabf9a44384e05cf13966eb2659b6 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
node2607.swalot.os - Linux centos linux 7.5.1804, Intel(R) Xeon(R) CPU E5-2660 v3 @ 2.60GHz, Python 2.7.5
See https://gist.github.com/2b0427460a8a3ee48dbcf412c64ad34f for a full test report.

**Comment by boegel** [comment]
Going in, thanks @smoors!

**Pull request merged**
