### PR TITLE
use proper Perl dependency for worker 1.6.12 with foss/2019a (fixes installation on RHEL8 OS)

### PR DESCRIPTION
**Pull request by boegel**
(created using `eb --new-pr`)

cfr. #11498

### CODE REVIEW

**Comment by boegel** [comment]
@boegelbot please test @ generoso

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
node3605.doduo.os - Linux RHEL 8.2, x86_64, AMD EPYC 7552 48-Core Processor (zen2), Python 3.6.8
See https://gist.github.com/d597c220cea073203a9f19e1fc24bc07 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
node3144.skitty.os - Linux centos linux 7.9.2009, x86_64, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz (skylake_avx512), Python 3.6.8
See https://gist.github.com/f21757d5fe060880490ff8c94dbde201 for a full test report.

**Comment by hajgato** [comment]
lgtm

**Comment by hajgato** [comment]
Going in, thanks @boegel

**Review by hajgato — APPROVED** [review]

**Comment by hajgato** [comment]
Going in, thanks @boegel!

**Pull request merged**
