### PR TITLE
{vis}[GCCcore/12.3.0] R-tesseract v5.2.1, tesseract v5.3.4, Leptonica v1.84.1

### PR DESCRIPTION
**Pull request by smoors**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by smoors** [comment]
@boegelbot: please test @ generoso

**Comment by smoors** [comment]
@boegelbot please test @ jsc-zen3

**Review by lexming — APPROVED** [review]
LGTM

**Comment by lexming** [comment]
Merging, thanks @smoors !

**Pull request merged**
