### PR TITLE
add patch to fix compilation of HPDBSCAN 20210826

### PR DESCRIPTION
**Pull request by Flamefire**
(created using `eb --new-pr`)

This became an issue after dropping the numpy includes from the SciPy-bundle module during a module-only rebuild. However the issue is due to a real bug and might hunt us again.

### CODE REVIEW

**Comment by Flamefire** [comment]
Test report by @Flamefire
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
n1616 - Linux RHEL 8.9 (Ootpa), x86_64, Intel(R) Xeon(R) Platinum 8470 (icelake), Python 3.8.17
See https://gist.github.com/Flamefire/1c501e8a53bd5ac8d7754ddefc2b33ff for a full test report.

**Review by boegel — APPROVED** [review]
lgtm

**Comment by boegel** [comment]
@boegelbot please test @ generoso

**Comment by boegel** [comment]
Going in, thanks @Flamefire!

**Pull request merged**
