### PR TITLE
make sure that libjpeg-turbo libraries are installed in 'lib' subdirectory

### PR DESCRIPTION
**Pull request by boegel**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by jfgrimm** [comment]
motivation: https://github.com/easybuilders/easybuild-easyconfigs/issues/16256

**Comment by boegel** [comment]
@boegelbot please test @ generoso

**Comment by jfgrimm** [comment]
Test report by @jfgrimm
**SUCCESS**
Build succeeded for 8 out of 8 (8 easyconfigs in total)
node079.viking2.yor.alces.network - Linux Rocky Linux 8.9, x86_64, AMD EPYC 7643 48-Core Processor, Python 3.6.8
See https://gist.github.com/jfgrimm/56bcb9d51e1de22bb77c679565ab34d4 for a full test report.

**Review by jfgrimm — APPROVED** [review]

**Comment by jfgrimm** [comment]
@boegelbot please test @ jsc-zen3

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 8 out of 8 (8 easyconfigs in total)
node3113.skitty.os - Linux RHEL 8.8, x86_64, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz, Python 3.6.8
See https://gist.github.com/boegel/6adacab9962c1ca7b39b85778f58433f for a full test report.

**Comment by jfgrimm** [comment]
Going in, thanks @boegel!

**Pull request merged**
