### PR TITLE
{bio}[foss/2020b] RepeatModeler v2.0.2a

### PR DESCRIPTION
**Pull request by jfgrimm**
(created using `eb --new-pr`)

Depends on easyconfigs:
- ~#13104~
- ~#13123~
- ~#13124~
- ~#13125~

and the custom easyblock:
- ~https://github.com/easybuilders/easybuild-easyblocks/pull/2470~

### CODE REVIEW

**Comment by verdurin** [comment]
@boegelbot please test @ generoso
EB_ARGS=" --include-easyblocks-from-pr=2470"

**Comment by verdurin** [comment]
On one of my test systems:
```
[compile canvas_cairo_file.o]
In file included from src/annotationsketch/canvas_cairo_context.c:30:
/mnt/ds918plus/eb/nuc-fedora32/build/GenomeTools/1.6.1/GCC-10.2.0/genometools-1.6.1/src/annotationsketch/canvas_cairo_context.h:21:10: fatal error: cairo.h: No such file or directory
   21 | #include <cairo.h>
      |          ^~~~~~~~~
compilation terminated.
In file included from src/annotationsketch/canvas_cairo.c:34:
/mnt/ds918plus/eb/nuc-fedora32/build/GenomeTools/1.6.1/GCC-10.2.0/genometools-1.6.1/src/annotationsketch/graphics_cairo_api.h:21:10: fatal error: cairo.h: No such file or directory
   21 | #include <cairo.h>
      |          ^~~~~~~~~
compilation terminated.
make: *** [Makefile:824: obj/src/annotationsketch/canvas_cairo.o] Error 1
make: *** Waiting for unfinished jobs....
make: *** [Makefile:824: obj/src/annotationsketch/canvas_cairo_context.o] Error 1
In file included from src/annotationsketch/canvas_cairo_file.c:34:
/mnt/ds918plus/eb/nuc-fedora32/build/GenomeTools/1.6.1/GCC-10.2.0/genometools-1.6.1/src/annotationsketch/graphics_cairo_api.h:21:10: fatal error: cairo.h: No such file or directory
   21 | #include <cairo.h>
      |          ^~~~~~~~~
compilation terminated.
make: *** [Makefile:824: obj/src/annotationsketch/canvas_cairo_file.o] Error 1
```

**Comment by jfgrimm** [comment]
@verdurin can you try adding `pkg-config` as a builddep to GenomeTools, to see if that fixes the issue?

**Comment by verdurin** [comment]
Test report by @verdurin
Using easyblocks from PR(s) https://github.com/easybuilders/easybuild-easyblocks/pull/2470
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
nuc.lan - Linux Fedora 33, x86_64, Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz, Python 3.9.6
See https://gist.github.com/7ba78d006044ab7fba2a2cc987a47c59 for a full test report.

**Comment by verdurin** [comment]
@jfgrimm looks like a rebuilt `GenomeTools` with that change did indeed fix the issue for me - thanks.

**Review by boegel — APPROVED** [review]
lgtm

**Comment by boegel** [comment]
Going in, thanks @jfgrimm!

**Pull request merged**
