### PR TITLE
add patch for TensorFlow 2.3.1 to fix installation on Arm64

### PR DESCRIPTION
**Pull request by boegel**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by boegel** [comment]
@boegelbot please test @ generoso

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 3 out of 3 (3 easyconfigs in total)
node3403.kirlia.os - Linux centos linux 7.8.2003, x86_64, Intel(R) Xeon(R) Gold 6240 CPU @ 2.60GHz (cascadelake), Python 2.7.5
See https://gist.github.com/b5bc5598acc452b4e15870fee1e76771 for a full test report.

**Comment by verdurin** [comment]
@boegel do we need a build report from an ARM64 box to check the fix works, as well as that it doesn't break on other architectures?

**Comment by akesandgren** [comment]
Perhaps we should have arch-labels on the PRs which would then require a test report from such an arch to be able to merge?

**Comment by boegel** [comment]
@verdurin Yes, we should have a test report from an Arm64 box here, I'll work on that.

@akesandgren Yeah, we should get a bit more organized there...

**Comment by terjekv** [comment]
Test report by @terjekv
**SUCCESS**
Build succeeded for 46 out of 46 (2 easyconfigs in total)
arm2 - Linux ubuntu 18.04, AArch64, UNKNOWN, Python 3.6.9
See https://gist.github.com/234c896e70529cdeb52aba909fead8ea for a full test report.

**Comment by boegel** [comment]
@verdurin Test report from an Arm64 system done, see @terjekv's test report, so good to go?

**Review by verdurin — APPROVED** [review]
Looks fine.

**Comment by verdurin** [comment]
Going in, thanks @boegel!

**Pull request merged**
