### PR TITLE
{chem}[intel/2019b] PLUMED v2.5.3 w/ Python 3.7.4

### PR DESCRIPTION
**Pull request by boegel**
(created using `eb --new-pr`)
requires ~~#9580~~ (libmatheval)

### CODE REVIEW

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
node3128.skitty.os - Linux centos linux 7.7.1908, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz, Python 3.6.8
See https://gist.github.com/4ddd536e9e0038141591dce8d96b1f87 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
node2405.golett.os - Linux centos linux 7.7.1908, Intel(R) Xeon(R) CPU E5-2680 v3 @ 2.50GHz, Python 2.7.5
See https://gist.github.com/3cba21984ff266481864d400022f73a0 for a full test report.

**Comment by migueldiascosta** [comment]
closing and reopening to trigger travis

**Comment by migueldiascosta** [comment]
Test report by @migueldiascosta
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
generoso - Linux centos linux 7.6.1810, Intel(R) Xeon(R) CPU E5-2660 v4 @ 2.00GHz, Python 3.6.8
See https://gist.github.com/c7f214df305f1ac7e472ed2766bc4edc for a full test report.

**Comment by migueldiascosta** [comment]
hm, `eb --merge-pr 9581 -x` says that the test suite has passed, which means that `status_data['state']` of this PR is `success`, although some tests have failed...

**Comment by boegel** [comment]
> hm, `eb --merge-pr 9581 -x` says that the test suite has passed, which means that `status_data['state']` of this PR is `success`, although some tests have failed...

@migueldiascosta That's because the tests run in GitHub are not required yet for a PR to be mergable (only the tests in Travis are, together with an approved review).
That was done deliberately when we started also running the tests in GitHub to avoid that issues with the tests that only occur in GitHub (due to an issue with running the tests there) would block a PR.

I've changed this just now (in all `easybuild-*` repositories), so if tests fail in GitHub now, you won't be able to merge the PR using `--merge-pr`...

**Comment by smoors** [comment]
Test report by @smoors
**SUCCESS**
Build succeeded for 3 out of 3 (1 easyconfigs in this PR)
node377.hydra.os - Linux centos linux 7.7.1908, Intel(R) Xeon(R) Gold 6148 CPU @ 2.40GHz, Python 2.7.5
See https://gist.github.com/136d252d94d747bc572ea64115ffe028 for a full test report.

**Comment by smoors** [comment]
Going in, thanks @boegel!

**Pull request merged**
