### PR TITLE
{lang}[foss/2017b,intel/2017b] Python v3.6.2, Python v3.6.2

### PR DESCRIPTION
**Pull request by boegel**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in this PR)
node2045.delcatty.os - Linux centos linux 7.3.1611, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.7.5
See https://gist.github.com/53006156ff7583701b39278ac1cd6c6a for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in this PR)
node2553.golett.os - Linux centos linux 7.3.1611, Intel(R) Xeon(R) CPU E5-2680 v3 @ 2.50GHz, Python 2.7.5
See https://gist.github.com/27254e464e927de762b3dda809a1ad31 for a full test report.

**Comment by verdurin** [comment]
Test report by @verdurin
**FAILED**
Build succeeded for 2 out of 3 (2 easyconfigs in this PR)
ca005.camp.thecrick.org - Linux centos linux 7.3.1611, Intel(R) Xeon(R) CPU E5-2640 v3 @ 2.60GHz, Python 2.7.5
See https://gist.github.com/73b17e8f7226b73539a81e876c2a7408 for a full test report.

**Comment by verdurin** [comment]
@boegel problem building `paramiko`:
```
== 2017-09-02 00:17:24,613 run.py:132 DEBUG run_cmd: running cmd python -c "import paramiko" (in /camp/apps/eb/review/software/Python/3.6.2-intel-2017b)
== 2017-09-02 00:17:24,613 run.py:157 INFO running cmd: python -c "import paramiko" 
== 2017-09-02 00:17:25,304 run.py:439 DEBUG cmd "python -c "import paramiko"" exited with exitcode 1 and output:
ERROR:root:code for hash sha3_224 was not found.
Traceback (most recent call last):
  File "/camp/apps/eb/review/software/Python/3.6.2-intel-2017b/lib/python3.6/hashlib.py", line 121, in __get_openssl_constructor
    f = getattr(_hashlib, 'openssl_' + name)
AttributeError: module '_hashlib' has no attribute 'openssl_sha3_224'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/camp/apps/eb/review/software/Python/3.6.2-intel-2017b/lib/python3.6/hashlib.py", line 243, in <module>
    globals()[__func_name] = __get_hash(__func_name)
  File "/camp/apps/eb/review/software/Python/3.6.2-intel-2017b/lib/python3.6/hashlib.py", line 128, in __get_openssl_constructor
    return __get_builtin_constructor(name)
  File "/camp/apps/eb/review/software/Python/3.6.2-intel-2017b/lib/python3.6/hashlib.py", line 113, in __get_builtin_constructor
    raise ValueError('unsupported hash type ' + name)
ValueError: unsupported hash type sha3_224
ERROR:root:code for hash sha3_256 was not found.
Traceback (most recent call last):
  File "/camp/apps/eb/review/software/Python/3.6.2-intel-2017b/lib/python3.6/hashlib.py", line 121, in __get_openssl_constructor
    f = getattr(_hashlib, 'openssl_' + name)
AttributeError: module '_hashlib' has no attribute 'openssl_sha3_256'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/camp/apps/eb/review/software/Python/3.6.2-intel-2017b/lib/python3.6/hashlib.py", line 243, in <module>
    globals()[__func_name] = __get_hash(__func_name)
  File "/camp/apps/eb/review/software/Python/3.6.2-intel-2017b/lib/python3.6/hashlib.py", line 128, in __get_openssl_constructor
    return __get_builtin_constructor(name)
  File "/camp/apps/eb/review/software/Python/3.6.2-intel-2017b/lib/python3.6/hashlib.py", line 113, in __get_builtin_constructor
    raise ValueError('unsupported hash type ' + name)
ValueError: unsupported hash type sha3_256
ERROR:root:code for hash sha3_384 was not found.
Traceback (most recent call last):
  File "/camp/apps/eb/review/software/Python/3.6.2-intel-2017b/lib/python3.6/hashlib.py", line 121, in __get_openssl_constructor
    f = getattr(_hashlib, 'openssl_' + name)
AttributeError: module '_hashlib' has no attribute 'openssl_sha3_384'

During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/camp/apps/eb/review/software/Python/3.6.2-intel-2017b/lib/python3.6/hashlib.py", line 243, in <module>
    globals()[__func_name] = __get_hash(__func_name)
  File "/camp/apps/eb/review/software/Python/3.6.2-intel-2017b/lib/python3.6/hashlib.py", line 128, in __get_openssl_constructor
    return __get_builtin_constructor(name)
  File "/camp/apps/eb/review/software/Python/3.6.2-intel-2017b/lib/python3.6/hashlib.py", line 113, in __get_builtin_constructor
    raise ValueError('unsupported hash type ' + name)
ValueError: unsupported hash type sha3_384
ERROR:root:code for hash sha3_512 was not found.
Traceback (most recent call last):
  File "/camp/apps/eb/review/software/Python/3.6.2-intel-2017b/lib/python3.6/hashlib.py", line 121, in __get_openssl_constructor
    f = getattr(_hashlib, 'openssl_' + name)
AttributeError: module '_hashlib' has no attribute 'openssl_sha3_512'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/camp/apps/eb/review/software/Python/3.6.2-intel-2017b/lib/python3.6/hashlib.py", line 243, in <module>
    globals()[__func_name] = __get_hash(__func_name)
  File "/camp/apps/eb/review/software/Python/3.6.2-intel-2017b/lib/python3.6/hashlib.py", line 128, in __get_openssl_constructor
    return __get_builtin_constructor(name)
  File "/camp/apps/eb/review/software/Python/3.6.2-intel-2017b/lib/python3.6/hashlib.py", line 113, in __get_builtin_constructor
    raise ValueError('unsupported hash type ' + name)
ValueError: unsupported hash type sha3_512
ERROR:root:code for hash shake_128 was not found.
Traceback (most recent call last):
  File "/camp/apps/eb/review/software/Python/3.6.2-intel-2017b/lib/python3.6/hashlib.py", line 121, in __get_openssl_constructor
    f = getattr(_hashlib, 'openssl_' + name)
AttributeError: module '_hashlib' has no attribute 'openssl_shake_128'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/camp/apps/eb/review/software/Python/3.6.2-intel-2017b/lib/python3.6/hashlib.py", line 243, in <module>
    globals()[__func_name] = __get_hash(__func_name)
  File "/camp/apps/eb/review/software/Python/3.6.2-intel-2017b/lib/python3.6/hashlib.py", line 128, in __get_openssl_constructor
    return __get_builtin_constructor(name)
  File "/camp/apps/eb/review/software/Python/3.6.2-intel-2017b/lib/python3.6/hashlib.py", line 113, in __get_builtin_constructor
    raise ValueError('unsupported hash type ' + name)
ValueError: unsupported hash type shake_128
ERROR:root:code for hash shake_256 was not found.
Traceback (most recent call last):
  File "/camp/apps/eb/review/software/Python/3.6.2-intel-2017b/lib/python3.6/hashlib.py", line 121, in __get_openssl_constructor
    f = getattr(_hashlib, 'openssl_' + name)
AttributeError: module '_hashlib' has no attribute 'openssl_shake_256'

During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/camp/apps/eb/review/software/Python/3.6.2-intel-2017b/lib/python3.6/hashlib.py", line 243, in <module>
    globals()[__func_name] = __get_hash(__func_name)
  File "/camp/apps/eb/review/software/Python/3.6.2-intel-2017b/lib/python3.6/hashlib.py", line 128, in __get_openssl_constructor
    return __get_builtin_constructor(name)
  File "/camp/apps/eb/review/software/Python/3.6.2-intel-2017b/lib/python3.6/hashlib.py", line 113, in __get_builtin_constructor
    raise ValueError('unsupported hash type ' + name)
ValueError: unsupported hash type shake_256
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/camp/apps/eb/review/software/Python/3.6.2-intel-2017b/lib/python3.6/site-packages/paramiko-2.2.1-py3.6.egg/paramiko/__init__.py", line 31, in <module>
  File "/camp/apps/eb/review/software/Python/3.6.2-intel-2017b/lib/python3.6/site-packages/paramiko-2.2.1-py3.6.egg/paramiko/transport.py", line 57, in <module>
  File "/camp/apps/eb/review/software/Python/3.6.2-intel-2017b/lib/python3.6/site-packages/paramiko-2.2.1-py3.6.egg/paramiko/ed25519key.py", line 22, in <module>
  File "/camp/apps/eb/review/software/Python/3.6.2-intel-2017b/lib/python3.6/site-packages/PyNaCl-1.1.2-py3.6-linux-x86_64.egg/nacl/signing.py", line 19, in <module>
    import nacl.bindings
  File "/camp/apps/eb/review/software/Python/3.6.2-intel-2017b/lib/python3.6/site-packages/PyNaCl-1.1.2-py3.6-linux-x86_64.egg/nacl/bindings/__init__.py", line 17, in <module>
    from nacl.bindings.crypto_box import (
  File "/camp/apps/eb/review/software/Python/3.6.2-intel-2017b/lib/python3.6/site-packages/PyNaCl-1.1.2-py3.6-linux-x86_64.egg/nacl/bindings/crypto_box.py", line 18, in <module>
    from nacl._sodium import ffi, lib
ImportError: /camp/apps/eb/review/software/Python/3.6.2-intel-2017b/lib/python3.6/site-packages/PyNaCl-1.1.2-py3.6-linux-x86_64.egg/nacl/_sodium.cpython-36m-x86_64-linux-gnu.so: undefined symbol: __stack_chk_guard

== 2017-09-02 00:17:25,304 extension.py:181 WARNING Extension: paramiko failed to install, cmd 'python -c "import paramiko"' (stdin: None) output: ERROR:root:code for hash sha3_224 was not found.
Traceback (most recent call last):
  File "/camp/apps/eb/review/software/Python/3.6.2-intel-2017b/lib/python3.6/hashlib.py", line 121, in __get_openssl_constructor
    f = getattr(_hashlib, 'openssl_' + name)
AttributeError: module '_hashlib' has no attribute 'openssl_sha3_224'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/camp/apps/eb/review/software/Python/3.6.2-intel-2017b/lib/python3.6/hashlib.py", line 243, in <module>
    globals()[__func_name] = __get_hash(__func_name)
  File "/camp/apps/eb/review/software/Python/3.6.2-intel-2017b/lib/python3.6/hashlib.py", line 128, in __get_openssl_constructor
    return __get_builtin_constructor(name)
  File "/camp/apps/eb/review/software/Python/3.6.2-intel-2017b/lib/python3.6/hashlib.py", line 113, in __get_builtin_constructor
    raise ValueError('unsupported hash type ' + name)
ValueError: unsupported hash type sha3_224
ERROR:root:code for hash sha3_256 was not found.
Traceback (most recent call last):
  File "/camp/apps/eb/review/software/Python/3.6.2-intel-2017b/lib/python3.6/hashlib.py", line 121, in __get_openssl_constructor
    f = getattr(_hashlib, 'openssl_' + name)
AttributeError: module '_hashlib' has no attribute 'openssl_sha3_256'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/camp/apps/eb/review/software/Python/3.6.2-intel-2017b/lib/python3.6/hashlib.py", line 243, in <module>
    globals()[__func_name] = __get_hash(__func_name)
  File "/camp/apps/eb/review/software/Python/3.6.2-intel-2017b/lib/python3.6/hashlib.py", line 128, in __get_openssl_constructor
    return __get_builtin_constructor(name)
  File "/camp/apps/eb/review/software/Python/3.6.2-intel-2017b/lib/python3.6/hashlib.py", line 113, in __get_builtin_constructor
    raise ValueError('unsupported hash type ' + name)
ValueError: unsupported hash type sha3_256
ERROR:root:code for hash sha3_384 was not found.
Traceback (most recent call last):
  File "/camp/apps/eb/review/software/Python/3.6.2-intel-2017b/lib/python3.6/hashlib.py", line 121, in __get_openssl_constructor
    f = getattr(_hashlib, 'openssl_' + name)
AttributeError: module '_hashlib' has no attribute 'openssl_sha3_384'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/camp/apps/eb/review/software/Python/3.6.2-intel-2017b/lib/python3.6/hashlib.py", line 243, in <module>
    globals()[__func_name] = __get_hash(__func_name)
  File "/camp/apps/eb/review/software/Python/3.6.2-intel-2017b/lib/python3.6/hashlib.py", line 128, in __get_openssl_constructor
    return __get_builtin_constructor(name)
  File "/camp/apps/eb/review/software/Python/3.6.2-intel-2017b/lib/python3.6/hashlib.py", line 113, in __get_builtin_constructor
    raise ValueError('unsupported hash type ' + name)
ValueError: unsupported hash type sha3_384
ERROR:root:code for hash sha3_512 was not found.
Traceback (most recent call last):
  File "/camp/apps/eb/review/software/Python/3.6.2-intel-2017b/lib/python3.6/hashlib.py", line 121, in __get_openssl_constructor
    f = getattr(_hashlib, 'openssl_' + name)
AttributeError: module '_hashlib' has no attribute 'openssl_sha3_512'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/camp/apps/eb/review/software/Python/3.6.2-intel-2017b/lib/python3.6/hashlib.py", line 243, in <module>
    globals()[__func_name] = __get_hash(__func_name)
  File "/camp/apps/eb/review/software/Python/3.6.2-intel-2017b/lib/python3.6/hashlib.py", line 128, in __get_openssl_constructor
    return __get_builtin_constructor(name)
  File "/camp/apps/eb/review/software/Python/3.6.2-intel-2017b/lib/python3.6/hashlib.py", line 113, in __get_builtin_constructor
    raise ValueError('unsupported hash type ' + name)
ValueError: unsupported hash type sha3_512
ERROR:root:code for hash shake_128 was not found.
Traceback (most recent call last):
  File "/camp/apps/eb/review/software/Python/3.6.2-intel-2017b/lib/python3.6/hashlib.py", line 121, in __get_openssl_constructor
    f = getattr(_hashlib, 'openssl_' + name)
AttributeError: module '_hashlib' has no attribute 'openssl_shake_128'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/camp/apps/eb/review/software/Python/3.6.2-intel-2017b/lib/python3.6/hashlib.py", line 243, in <module>
    globals()[__func_name] = __get_hash(__func_name)
  File "/camp/apps/eb/review/software/Python/3.6.2-intel-2017b/lib/python3.6/hashlib.py", line 128, in __get_openssl_constructor
    return __get_builtin_constructor(name)
  File "/camp/apps/eb/review/software/Python/3.6.2-intel-2017b/lib/python3.6/hashlib.py", line 113, in __get_builtin_constructor
    raise ValueError('unsupported hash type ' + name)
ValueError: unsupported hash type shake_128
ERROR:root:code for hash shake_256 was not found.
Traceback (most recent call last):
  File "/camp/apps/eb/review/software/Python/3.6.2-intel-2017b/lib/python3.6/hashlib.py", line 121, in __get_openssl_constructor
    f = getattr(_hashlib, 'openssl_' + name)
AttributeError: module '_hashlib' has no attribute 'openssl_shake_256'

During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/camp/apps/eb/review/software/Python/3.6.2-intel-2017b/lib/python3.6/hashlib.py", line 243, in <module>
    globals()[__func_name] = __get_hash(__func_name)
  File "/camp/apps/eb/review/software/Python/3.6.2-intel-2017b/lib/python3.6/hashlib.py", line 128, in __get_openssl_constructor
    return __get_builtin_constructor(name)
  File "/camp/apps/eb/review/software/Python/3.6.2-intel-2017b/lib/python3.6/hashlib.py", line 113, in __get_builtin_constructor
    raise ValueError('unsupported hash type ' + name)
ValueError: unsupported hash type shake_256
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/camp/apps/eb/review/software/Python/3.6.2-intel-2017b/lib/python3.6/site-packages/paramiko-2.2.1-py3.6.egg/paramiko/__init__.py", line 31, in <module>
  File "/camp/apps/eb/review/software/Python/3.6.2-intel-2017b/lib/python3.6/site-packages/paramiko-2.2.1-py3.6.egg/paramiko/transport.py", line 57, in <module>
  File "/camp/apps/eb/review/software/Python/3.6.2-intel-2017b/lib/python3.6/site-packages/paramiko-2.2.1-py3.6.egg/paramiko/ed25519key.py", line 22, in <module>
  File "/camp/apps/eb/review/software/Python/3.6.2-intel-2017b/lib/python3.6/site-packages/PyNaCl-1.1.2-py3.6-linux-x86_64.egg/nacl/signing.py", line 19, in <module>
    import nacl.bindings
  File "/camp/apps/eb/review/software/Python/3.6.2-intel-2017b/lib/python3.6/site-packages/PyNaCl-1.1.2-py3.6-linux-x86_64.egg/nacl/bindings/__init__.py", line 17, in <module>
    from nacl.bindings.crypto_box import (
  File "/camp/apps/eb/review/software/Python/3.6.2-intel-2017b/lib/python3.6/site-packages/PyNaCl-1.1.2-py3.6-linux-x86_64.egg/nacl/bindings/crypto_box.py", line 18, in <module>
    from nacl._sodium import ffi, lib
ImportError: /camp/apps/eb/review/software/Python/3.6.2-intel-2017b/lib/python3.6/site-packages/PyNaCl-1.1.2-py3.6-linux-x86_64.egg/nacl/_sodium.cpython-36m-x86_64-linux-gnu.so: undefined symbol: __stack_chk_guard

```
etc.

**Comment by boegel** [comment]
@verdurin Which version of OpenSSL do you have installed locally?

**Comment by boegel** [comment]
@verdurin Also, are you seeing similar problems with `Python-3.6.1*.eb` on this system, or not?

**Comment by verdurin** [comment]
Here are the `OpenSSL` versions:
```
openssl-libs-1.0.1e-60.el7_3.1.x86_64
openssl-1.0.1e-60.el7_3.1.x86_64
openssl-devel-1.0.1e-60.el7_3.1.x86_64
```

**Comment by verdurin** [comment]
Have just started a build of `3.6.1` as a comparison.

**Comment by boegel** [comment]
@verdurin Ping on the 3.6.1 build? I suspect your OS OpenSSL might be too old for the `sha3` & `shake` stuff...

**Comment by wpoely86** [comment]
Test report by @wpoely86
**FAILED**
Build succeeded for 13 out of 14 (2 easyconfigs in this PR)
nic68 - Linux centos linux 7.3.1611, Intel(R) Xeon(R) CPU E5-2680 v4 @ 2.40GHz, Python 2.7.5
See https://gist.github.com/6910354a76c41ab1a8858e9dac26423c for a full test report.

**Comment by boegel** [comment]
Hmm, @wpoely86's test report also includes problems with `paramiko`, albeit different ones...

```
== 2017-09-07 11:38:37,304 run.py:179 INFO running cmd: python -c "import paramiko" 
== 2017-09-07 11:38:37,626 extension.py:181 WARNING Extension: paramiko failed to install, cmd 'python -c "import paramiko"' (stdin: None) output: Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/dev/shm/ward/eb_sandbox_20170907_10-07-21_HoJq6/software/Python/3.6.2-intel-2017b/lib/python3.6/site-packages/paramiko-2.2.1-py3.6.egg/paramiko/__init__.py", line 31, in <module>
  File "/dev/shm/ward/eb_sandbox_20170907_10-07-21_HoJq6/software/Python/3.6.2-intel-2017b/lib/python3.6/site-packages/paramiko-2.2.1-py3.6.egg/paramiko/transport.py", line 57, in <module>
  File "/dev/shm/ward/eb_sandbox_20170907_10-07-21_HoJq6/software/Python/3.6.2-intel-2017b/lib/python3.6/site-packages/paramiko-2.2.1-py3.6.egg/paramiko/ed25519key.py", line 22, in <module>
  File "/dev/shm/ward/eb_sandbox_20170907_10-07-21_HoJq6/software/Python/3.6.2-intel-2017b/lib/python3.6/site-packages/PyNaCl-1.1.2-py3.6-linux-x86_64.egg/nacl/signing.py", line 19, in <module>
    import nacl.bindings
  File "/dev/shm/ward/eb_sandbox_20170907_10-07-21_HoJq6/software/Python/3.6.2-intel-2017b/lib/python3.6/site-packages/PyNaCl-1.1.2-py3.6-linux-x86_64.egg/nacl/bindings/__init__.py", line 17, in <module>
    from nacl.bindings.crypto_box import (
  File "/dev/shm/ward/eb_sandbox_20170907_10-07-21_HoJq6/software/Python/3.6.2-intel-2017b/lib/python3.6/site-packages/PyNaCl-1.1.2-py3.6-linux-x86_64.egg/nacl/bindings/crypto_box.py", line 18, in <module>
    from nacl._sodium import ffi, lib
ImportError: /dev/shm/ward/eb_sandbox_20170907_10-07-21_HoJq6/software/Python/3.6.2-intel-2017b/lib/python3.6/site-packages/PyNaCl-1.1.2-py3.6-linux-x86_64.egg/nacl/_sodium.cpython-36m-x86_64-linux-gnu.so: undefined symbol: __stack_chk_guard
```

**Comment by boegel** [comment]
Hmm, I have the same OpenSSL version as you have:

```
openssl-libs-1.0.1e-60.el7_3.1.i686
openssl-devel-1.0.1e-60.el7_3.1.x86_64
openssl-libs-1.0.1e-60.el7_3.1.x86_64
openssl-1.0.1e-60.el7_3.1.x86_64
```

Works fine for me though?

Any clues in the (debug) build log for Python? Look for anything related to the `hashlib` component, since it seems that's what is crippled.

**Comment by wpoely86** [comment]
Test report by @wpoely86
**FAILED**
Build succeeded for 13 out of 14 (2 easyconfigs in this PR)
nic68 - Linux centos linux 7.3.1611, Intel(R) Xeon(R) CPU E5-2680 v4 @ 2.40GHz, Python 2.7.5
See https://gist.github.com/df48fa6b321d6445e38a8c57460f8d85 for a full test report.

**Comment by boegel** [comment]
@wpoely86 Last test was again without having `glib-static` installed (cfr. #5092)?

**Comment by wpoely86** [comment]
This one was with I believe.

**Comment by boegel** [comment]
@wpoely86 Can you double check?

Exact same problem as in #5092 & https://software.intel.com/en-us/forums/intel-c-compiler/topic/610514:

```
== 2017-09-19 17:25:54,600 extensioneasyblock.py:139 WARNING Sanity check for paramiko failed: paramiko failed to install, cmd 'python -c "import paramiko"' (stdin: None) output: Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/dev/shm/ward/eb_sandbox_20170919_16-14-06_3D9AG/software/Python/3.6.2-intel-2017b/lib/python3.6/site-packages/paramiko-2.2.1-py3.6.egg/paramiko/__init__.py", line 31, in <module>
  File "/dev/shm/ward/eb_sandbox_20170919_16-14-06_3D9AG/software/Python/3.6.2-intel-2017b/lib/python3.6/site-packages/paramiko-2.2.1-py3.6.egg/paramiko/transport.py", line 57, in <module>
  File "/dev/shm/ward/eb_sandbox_20170919_16-14-06_3D9AG/software/Python/3.6.2-intel-2017b/lib/python3.6/site-packages/paramiko-2.2.1-py3.6.egg/paramiko/ed25519key.py", line 22, in <module>
  File "/dev/shm/ward/eb_sandbox_20170919_16-14-06_3D9AG/software/Python/3.6.2-intel-2017b/lib/python3.6/site-packages/PyNaCl-1.1.2-py3.6-linux-x86_64.egg/nacl/signing.py", line 19, in <module>
    import nacl.bindings
  File "/dev/shm/ward/eb_sandbox_20170919_16-14-06_3D9AG/software/Python/3.6.2-intel-2017b/lib/python3.6/site-packages/PyNaCl-1.1.2-py3.6-linux-x86_64.egg/nacl/bindings/__init__.py", line 17, in <module>
    from nacl.bindings.crypto_box import (
  File "/dev/shm/ward/eb_sandbox_20170919_16-14-06_3D9AG/software/Python/3.6.2-intel-2017b/lib/python3.6/site-packages/PyNaCl-1.1.2-py3.6-linux-x86_64.egg/nacl/bindings/crypto_box.py", line 18, in <module>
    from nacl._sodium import ffi, lib
ImportError: /dev/shm/ward/eb_sandbox_20170919_16-14-06_3D9AG/software/Python/3.6.2-intel-2017b/lib/python3.6/site-packages/PyNaCl-1.1.2-py3.6-linux-x86_64.egg/nacl/_sodium.cpython-36m-x86_64-linux-gnu.so: undefined symbol: __stack_chk_guard
```

**Comment by boegel** [comment]
Actually, https://software.intel.com/en-us/forums/intel-c-compiler/topic/610514 suggests that the problem can be fixed by *removing* `glibc-static`?

Works fine for us though, *with* `glibc-static` installed:

```
$ rpm -q glibc-static
glibc-static-2.17-157.el7_3.5.x86_64
```

**Comment by boegel** [comment]
@verdurin This https://github.com/keybase/python-triplesec/issues/13 seems to suggest some part of the Python standard library didn't get build on your system.

Can you upload a (debug) log of your Python 3 installation?

**Comment by verdurin** [comment]
@boegel http://www.hep.ph.ic.ac.uk/~mhuffman/easybuild-Python-3.6.1-20170720.143340.log

**Comment by boegel** [comment]
@verdurin That's a log file for Python 3.6.1 with `foss/2016b`, while the problem above occurred with Python 3.6.2 with `intel/2017b`.

I'm trying to figure out why the missing bits in `hashlib` aren't there, I won't be able to figure that out from a log for a fully working Python 3.6.1 (incl. `paramiko`). ;-)

**Comment by verdurin** [comment]
@boegel serves you right for a wooly request...

Here's the log from one of the failed attempts:

http://www.hep.ph.ic.ac.uk/~mhuffman/easybuild-Python-3.6.2-20170901.162243.VyKfh.log

**Comment by verdurin** [comment]
Test report by @verdurin
**FAILED**
Build succeeded for 0 out of 1 (2 easyconfigs in this PR)
ca022.camp.thecrick.org - Linux centos linux 7.3.1611, Intel(R) Xeon(R) CPU E5-2640 v3 @ 2.60GHz, Python 2.7.5
See https://gist.github.com/2f210a9a26a4a95bd9784e518f003b6f for a full test report.

**Comment by boegel** [comment]
@verdurin OK, closing it, it seems... This is the culprit:

```
icc: error #10106: Fatal error in /camp/apps/eb/review/software/icc/2017.4.196-GCC-6.4.0-2.28/compilers_and_libraries_2017.4.196/linux/bin/intel64/mcpcom, terminated by EMT instruction
compilation aborted for /dev/shm/Python/3.6.2/intel-2017b/Python-3.6.2/Modules/_sha3/sha3module.c (code 1)
```

Next step: figure out what this means, and if we can avoid it...

**Comment by boegel** [comment]
@verdurin Just for kicks, can you try not using `/dev/shm` as build path?

**Comment by boegel** [comment]
Apparently @akesandgren ran into the same problem a while ago (cfr. https://www.snip2code.com/Snippet/1818622/Problems-building-python-3-6-1), and somehow fixed it. Got some feedback from him, he's unsure how he got around this issue.

This is getting more & more intriguing...

**Comment by verdurin** [comment]
Test report by @verdurin
**FAILED**
Build succeeded for 0 out of 1 (2 easyconfigs in this PR)
ca021.camp.thecrick.org - Linux centos linux 7.3.1611, Intel(R) Xeon(R) CPU E5-2640 v3 @ 2.60GHz, Python 2.7.5
See https://gist.github.com/f819537f605d4f543654c8301ae99472 for a full test report.

**Comment by verdurin** [comment]
@boegel Just tried with a normal build path, and it failed the same way.

**Comment by boegel** [comment]
OK, I'm starting to run out of ideas here...

@akesandgren Gave both easyconfigs a try too, they worked fine for him.

@vanzod Can you look into submitting a test report for this one?

**Comment by verdurin** [comment]
Test report by @verdurin
**FAILED**
Build succeeded for 0 out of 1 (2 easyconfigs in this PR)
ca009.camp.thecrick.org - Linux centos linux 7.3.1611, Intel(R) Xeon(R) CPU E5-2640 v3 @ 2.60GHz, Python 2.7.5
See https://gist.github.com/4b2db8d79c0dc1a6239e57ff3a455783 for a full test report.

**Comment by vanzod** [comment]
Test report by @vanzod
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in this PR)
cermis - Linux debian 8.8, Intel(R) Xeon(R) CPU           E5620  @ 2.40GHz, Python 2.7.9
See https://gist.github.com/07f7f9ff131c94e8575578b67cbfea5f for a full test report.

**Comment by wpoely86** [comment]
Test report by @wpoely86
**FAILED**
Build succeeded for 23 out of 37 (2 easyconfigs in this PR)
nic158 - Linux centos linux 7.3.1611, Intel(R) Xeon(R) CPU E5-2680 v2 @ 2.80GHz, Python 2.7.5
See https://gist.github.com/414a9c47b8728e2fbe778dc946b595f2 for a full test report.

**Comment by wpoely86** [comment]
Test report by @wpoely86
**FAILED**
Build succeeded for 30 out of 37 (2 easyconfigs in this PR)
nic154 - Linux centos linux 7.3.1611, Intel(R) Xeon(R) CPU E5-2680 v2 @ 2.80GHz, Python 2.7.5
See https://gist.github.com/54b289f2406221649c6ae7d0e00144b4 for a full test report.

**Comment by wpoely86** [comment]
Test report by @wpoely86
**FAILED**
Build succeeded for 36 out of 37 (2 easyconfigs in this PR)
nic154 - Linux centos linux 7.3.1611, Intel(R) Xeon(R) CPU E5-2680 v2 @ 2.80GHz, Python 2.7.5
See https://gist.github.com/d5238f04db6c0431c1a99b14b6a80a08 for a full test report.

**Comment by wpoely86** [comment]
Test report by @wpoely86
**FAILED**
Build succeeded for 29 out of 37 (2 easyconfigs in this PR)
nic154 - Linux centos linux 7.3.1611, Intel(R) Xeon(R) CPU E5-2680 v2 @ 2.80GHz, Python 2.7.5
See https://gist.github.com/867e12444145750f7eb71369b9b206a7 for a full test report.

**Comment by wpoely86** [comment]
Test report by @wpoely86
**SUCCESS**
Build succeeded for 37 out of 37 (2 easyconfigs in this PR)
nic154 - Linux centos linux 7.3.1611, Intel(R) Xeon(R) CPU E5-2680 v2 @ 2.80GHz, Python 2.7.5
See https://gist.github.com/087f07c16254ab60e103183638a6577f for a full test report.

**Comment by wpoely86** [comment]
De last one was with `glibc-static` installed.

**Pull request merged**
