### PR TITLE
{tools}[system] EasyBuild v0.5.0.0beta1 (initial beta release of EasyBuild v5.0.0)

### PR DESCRIPTION
**Pull request by boegel**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by boegel** [comment]
We should try and avoid that `--install-latest-eb-release` will pick up on this, so we many need to be a bit more creative with the version or the easyconfig filename...

**Comment by boegel** [comment]
@boegelbot please test @ generoso

**Review by jfgrimm — APPROVED** [review]

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
node4002.donphan.os - Linux RHEL 8.8, x86_64, Intel(R) Xeon(R) Gold 6240 CPU @ 2.60GHz, 1 x NVIDIA NVIDIA A2, 545.23.08, Python 3.6.8
See https://gist.github.com/boegel/ad916e9da6878f3982b9e3a734190da0 for a full test report.

**Comment by boegel** [comment]
@boegelbot please test @ jsc-zen3

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
boegels-MBP-M1.local - Darwin UNKNOWN UNKNOWN, AArch64, Apple M1 (m1), Python 3.11.10
See https://gist.github.com/boegel/ce028f1e2f02cfad12f0e5e633cf1540 for a full test report.

**Comment by boegel** [comment]
@boegelbot please test @ jsc-zen3

**Pull request merged**
