### PR TITLE
{chem,math}[intel/2019a] QuantumESPRESSO v6.4.1, ELPA v2018.11.001

### PR DESCRIPTION
**Pull request by Micket**
(created using `eb --new-pr`)

Depends on https://github.com/easybuilders/easybuild-easyblocks/pull/1692

### CODE REVIEW

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in this PR)
node2057.delcatty.os - Linux centos linux 7.6.1810, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.7.5
See https://gist.github.com/cfbc396fb3d5f415e7430f81d7d3633c for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in this PR)
node2400.golett.os - Linux centos linux 7.6.1810, Intel(R) Xeon(R) CPU E5-2680 v3 @ 2.50GHz, Python 2.7.5
See https://gist.github.com/c4636f686ed872bae78c08d6ec50fbd6 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in this PR)
node3129.skitty.os - Linux centos linux 7.6.1810, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz, Python 2.7.5
See https://gist.github.com/803ee5d579e2bbff115889ccd6d999a3 for a full test report.

**Comment by migueldiascosta** [comment]
Test report by @migueldiascosta
**SUCCESS**
Build succeeded for 5 out of 5 (2 easyconfigs in this PR)
sms - Linux centos linux 7.6.1810, AMD EPYC 7601 32-Core Processor, Python 2.7.5
See https://gist.github.com/e3f3dc82e465fd54d02cf038ab3c6c1b for a full test report.

**Comment by migueldiascosta** [comment]
Going in, thanks @Micket!

**Pull request merged**
