### PR TITLE
Fix cwd_enoent test in Perl

### PR DESCRIPTION
**Pull request by Flamefire**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by Flamefire** [comment]
Test report by @Flamefire
**FAILED**
Build succeeded for 9 out of 23 (10 easyconfigs in total)
i7075 - Linux Rocky Linux 8.7 (Green Obsidian), x86_64, AMD EPYC 7702 64-Core Processor (zen2), Python 3.8.13
See https://gist.github.com/Flamefire/3b2836eccfd1b2aaddb462a0db286237 for a full test report.

**Comment by SebastianAchilles** [comment]
Test report by @sebastianachilles
**SUCCESS**
Build succeeded for 9 out of 9 (9 easyconfigs in total)
bwd-rockylinux-94 - Linux Rocky Linux 9.4 (Blue Onyx), x86_64, Intel(R) Core(TM) i7-6900K CPU @ 3.20GHz (broadwell), Python 3.9.18
See https://gist.github.com/SebastianAchilles/8962b0bfcfaec96977d97a27caf0341e for a full test report.

**Comment by SebastianAchilles** [comment]
@boegelbot please test @ jsc-zen3
EB_BRANCH=5.0.x
EB_ARGS="Perl-5.32.1-GCCcore-10.3.0.eb Perl-5.34.0-GCCcore-11.2.0.eb Perl-5.34.1-GCCcore-11.3.0.eb Perl-5.36.0-GCCcore-12.1.0.eb Perl-5.36.0-GCCcore-12.2.0.eb Perl-5.36.1-GCCcore-12.3.0.eb Perl-5.36.1-GCCcore-13.1.0.eb Perl-5.38.0-GCCcore-13.2.0.eb Perl-5.38.0.eb"

**Comment by SebastianAchilles** [comment]
@boegelbot please test @ generoso
CORE_CNT=16
EB_ARGS="Perl-5.32.1-GCCcore-10.3.0.eb Perl-5.34.0-GCCcore-11.2.0.eb Perl-5.34.1-GCCcore-11.3.0.eb Perl-5.36.0-GCCcore-12.1.0.eb Perl-5.36.0-GCCcore-12.2.0.eb Perl-5.36.1-GCCcore-12.3.0.eb Perl-5.36.1-GCCcore-13.1.0.eb Perl-5.38.0-GCCcore-13.2.0.eb Perl-5.38.0.eb"

**Review by boegel — APPROVED** [review]
lgtm

**Comment by boegel** [comment]
Going in, thanks @Flamefire!

**Pull request merged**
