### PR TITLE
add patch to SciPy-bundle 2024.05 that fixes test failure on aarch64

### PR DESCRIPTION
**Pull request by SebastianAchilles**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by boegel** [comment]
@SebastianAchilles Did you check whether this is a known issue upstream? Any reference we can add to an issue to known when this is fixed?

**Comment by SebastianAchilles** [comment]
> @SebastianAchilles Did you check whether this is a known issue upstream? Any reference we can add to an issue to known when this is fixed?

In https://github.com/scipy/scipy/issues/20216 this problem was reported for `macox_arm64` and it was suggested to skip the test. In SciPy 1.14.0 these tests are skipped when running on `darwin`.

**Comment by SebastianAchilles** [comment]
@boegelbot please test @ jsc-zen3

**Comment by SebastianAchilles** [comment]
@boegelbot please test @ generoso

**Comment by SebastianAchilles** [comment]
Test report by @sebastianachilles
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
jrc0900.jureca - Linux Rocky Linux 9.4, AArch64, ARM UNKNOWN (neoverse_v2), 1 x NVIDIA NVIDIA GH200 480GB, 560.35.03, Python 3.9.18
See https://gist.github.com/SebastianAchilles/de5b08157cf18516fd3d679514d89819 for a full test report.

**Comment by SebastianAchilles** [comment]
Test report by @sebastianachilles
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
jrc0870.jureca - Linux Rocky Linux 9.4, AArch64, ARM UNKNOWN (neoverse_n1), 2 x NVIDIA NVIDIA A100-PCIE-40GB, 560.35.03, Python 3.9.18
See https://gist.github.com/SebastianAchilles/530073fe71414dc6f5a6687ca6b3b516 for a full test report.

**Review by boegel — APPROVED** [review]
lgtm

**Comment by boegel** [comment]
Going in, thanks @SebastianAchilles!

**Pull request merged**
