### PR TITLE
{bio}[goolf/1.7.20] SelEstim v1.1.6

### PR DESCRIPTION
**Pull request by pescobar**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by boegel** [comment]
@pescobar We're working towards automated style review (in Travis), you'll need to clean this up a bit to make it eligible for merging...

```
$ eb --from-pr 4759 --check-style
== temporary log file in case of crash /tmp/eb-lEB4n2/easybuild-FQ6JxJ.log
Running style check on 1 easyconfig(s)...
/tmp/eb-lEB4n2/files_pr4759/s/SelEstim/SelEstim-1.1.6-goolf-1.7.20.eb:26:65: W299 trailing whitespace
/tmp/eb-lEB4n2/files_pr4759/s/SelEstim/SelEstim-1.1.6-goolf-1.7.20.eb:27:17: E128 continuation line under-indented for visual indent
/tmp/eb-lEB4n2/files_pr4759/s/SelEstim/SelEstim-1.1.6-goolf-1.7.20.eb:28:17: E128 continuation line under-indented for visual indent
/tmp/eb-lEB4n2/files_pr4759/s/SelEstim/SelEstim-1.1.6-goolf-1.7.20.eb:29:17: E128 continuation line under-indented for visual indent
/tmp/eb-lEB4n2/files_pr4759/s/SelEstim/SelEstim-1.1.6-goolf-1.7.20.eb:30:17: E128 continuation line under-indented for visual indent
/tmp/eb-lEB4n2/files_pr4759/s/SelEstim/SelEstim-1.1.6-goolf-1.7.20.eb:31:17: E128 continuation line under-indented for visual indent
/tmp/eb-lEB4n2/files_pr4759/s/SelEstim/SelEstim-1.1.6-goolf-1.7.20.eb:32:17: E128 continuation line under-indented for visual indent
/tmp/eb-lEB4n2/files_pr4759/s/SelEstim/SelEstim-1.1.6-goolf-1.7.20.eb:33:1: E101 indentation contains mixed spaces and tabs
/tmp/eb-lEB4n2/files_pr4759/s/SelEstim/SelEstim-1.1.6-goolf-1.7.20.eb:33:1: W191 indentation contains tabs
/tmp/eb-lEB4n2/files_pr4759/s/SelEstim/SelEstim-1.1.6-goolf-1.7.20.eb:33:3: E124 closing bracket does not match visual indentation
/tmp/eb-lEB4n2/files_pr4759/s/SelEstim/SelEstim-1.1.6-goolf-1.7.20.eb:36:1: E101 indentation contains mixed spaces and tabs
[FAIL] /tmp/eb-lEB4n2/files_pr4759/s/SelEstim/SelEstim-1.1.6-goolf-1.7.20.eb
ERROR: One or more style checks FAILED!
```

**Comment by verdurin** [comment]
Test report by @verdurin
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
ca004.camp.thecrick.org - Linux centos linux 7.3.1611, Intel(R) Xeon(R) CPU E5-2640 v3 @ 2.60GHz, Python 2.7.5
See https://gist.github.com/8666d2544a70582a9198488d25dc15b5 for a full test report.

**Comment by boegel** [comment]
(close/open to retrigger Travis)

**Comment by migueldiascosta** [comment]
@pescobar, this PR is being closed for the following reason(s): uses a deprecated toolchain.
For more information on deprecated toolchains, see https://easybuild.readthedocs.io/en/latest/Deprecated-easyconfigs.html#deprecated-toolchains.
Please consider reopening or submitting a new PR using a supported toolchain.
For more information on our policy w.r.t. closing PRs, see https://easybuild.readthedocs.io/en/latest/Contributing.html#why-a-pull-request-may-be-closed-by-a-maintainer

**Pull request closed without merging**
