### PR TITLE
{devel}[GCCcore/11.3.0] typing-extensions v4.3.0 w/ Python 3.10.4

### PR DESCRIPTION
**Pull request by casparvl**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by casparvl** [comment]
@boegelbot please test @ generoso

**Comment by casparvl** [comment]
Test report by @casparvl
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
software1.lisa.surfsara.nl - Linux debian 10.12, x86_64, Intel(R) Xeon(R) Silver 4110 CPU @ 2.10GHz, Python 3.7.3
See https://gist.github.com/85397cb7a6bd5a943c6972872bacbad8 for a full test report.

**Comment by casparvl** [comment]
Test report by @casparvl
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
tcn454 - Linux RHEL 8.4, x86_64, AMD EPYC 7H12 64-Core Processor, Python 3.6.8
See https://gist.github.com/977d420acc0dee3916c3817dcf774c0a for a full test report.

**Comment by lexming** [comment]
@casparvl the easyconfig of Python already has `typing-extensions` v4.2.0.
https://github.com/easybuilders/easybuild-easyconfigs/blob/eae39238013a672d22403d88c1d1d55f4def9e13/easybuild/easyconfigs/p/Python/Python-3.10.4-GCCcore-11.3.0.eb#L132

Is that not enough?

**Comment by casparvl** [comment]
Ah, I missed that one. I updated with `--try-update-deps`, but of course, that doesn't take into account extensions - only true 'dependencies' in the EasyBuild sense.

I'll take out the explicit typing-extensions dependency from PyTorch (which is what this was for), so that it'll pick up on the one from Python-3.10.4-GCCcore-11.3.0.eb. Thanks for pointing it out!

**Pull request closed without merging**
