### PR TITLE
{numlib}[GCC/8.2.0-2.31.1] OpenBLAS v0.3.5, disable the AVX512 DGEMM kernel

### PR DESCRIPTION
**Pull request by akesandgren**
(created using `eb --new-pr`)
See, https://github.com/xianyi/OpenBLAS/pull/2061

### CODE REVIEW

**Comment by akesandgren** [comment]
Test report by @akesandgren
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
b-cn1203.hpc2n.umu.se - Linux ubuntu 16.04, Intel(R) Xeon Phi(TM) CPU 7250 @ 1.40GHz, Python 2.7.12
See https://gist.github.com/d1fcf05c1f979aac92aa4a2384c0bb5d for a full test report.

**Comment by Micket** [comment]
Test report by @Micket
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
vera-c1 - Linux centos linux 7.6.1810, Intel Xeon Processor (Skylake), Python 2.7.5
See https://gist.github.com/829d98922c5470ddce3bd78ae2f7bfa4 for a full test report.

**Comment by boegel** [comment]
Also fixes #8197

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
node2567.golett.os - Linux centos linux 7.6.1810, Intel(R) Xeon(R) CPU E5-2680 v3 @ 2.50GHz, Python 2.7.5
See https://gist.github.com/e67a8eb8fe7e69832ea81b1a0ad48959 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
node3115.skitty.os - Linux centos linux 7.6.1810, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz, Python 2.7.5
See https://gist.github.com/6c5ac6834a37312aaa96a1d14ed2ffed for a full test report.

**Comment by boegel** [comment]
Going in, thanks @akesandgren!

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
node2005.delcatty.os - Linux centos linux 7.6.1810, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.7.5
See https://gist.github.com/989c7755dd6f0a387af9f30279f4cbb4 for a full test report.

**Pull request merged**
