### PR TITLE
{lang}[system/system] Mamba v4.14.0-0

### PR DESCRIPTION
**Pull request by casparvl**
(created using `eb --new-pr`)

Requires:
- https://github.com/easybuilders/easybuild-easyblocks/pull/2808

### CODE REVIEW

**Comment by jfgrimm** [comment]
Test report by @jfgrimm
Using easyblocks from PR(s) https://github.com/easybuilders/easybuild-easyblocks/pull/2808
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
node109.pri.viking.alces.network - Linux CentOS Linux 7.9.2009, x86_64, Intel(R) Xeon(R) Gold 6138 CPU @ 2.00GHz (skylake_avx512), Python 3.6.8
See https://gist.github.com/c02045203992d9c06865132d5690cb45 for a full test report.

**Comment by casparvl** [comment]
@jfgrimm even if you're not framework/easyblocks maintainer of the week: mind taking a look at https://github.com/easybuilders/easybuild-easyblocks/pull/2808 ? It's a very minor change compared to the Anaconda EasyBlock from which it inherits. And easy to test, since there are no other Mamba EasyConfigs yet, so it can't break anything existing :)

**Comment by boegel** [comment]
@boegelbot please test @ generoso
EB_ARGS="--include-easyblocks-from-pr 2808"

**Comment by boegel** [comment]
Test report by @boegel
Using easyblocks from PR(s) https://github.com/easybuilders/easybuild-easyblocks/pull/2808
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
easybuild2.novalocal - Linux CentOS Stream 8, POWER, IBM pSeries (emulated by qemu) (power9le), Python 3.6.8
See https://gist.github.com/6f7083793dac3aaf6bcb55d9d8346599 for a full test report.

**Review by boegel — APPROVED** [review]
lgtm

**Comment by boegel** [comment]
Going in, thanks @casparvl!

**Pull request merged**
