### PR TITLE
add missing dependencies and fix incorrect ids in BRAKER v2.1.6

### PR DESCRIPTION
**Pull request by lexming**
(created using `eb --new-pr`)

Changelog:
* add missing dependency on DIAMOND and CDBtools
* backport fix for https://github.com/Gaius-Augustus/BRAKER/issues/354

### CODE REVIEW

**Comment by lexming** [comment]
@boegelbot: please test @ generoso

**Comment by lexming** [comment]
@boegelbot please test @ jsc-zen2

**Comment by lexming** [comment]
@boegelbot please test @ jsc-zen2

**Comment by branfosj** [comment]
Test report by @branfosj
**SUCCESS**
Build succeeded for 6 out of 6 (2 easyconfigs in total)
bear-pg0105u03a.bear.cluster - Linux RHEL 8.6, x86_64, Intel(R) Xeon(R) Platinum 8360Y CPU @ 2.40GHz (icelake), Python 3.6.8
See https://gist.github.com/branfosj/da1d6050ef293b1fffb44a2a83ade60e for a full test report.

**Comment by branfosj** [comment]
Going in, thanks @lexming!

**Pull request merged**
