### PR TITLE
{chem,lib}[gompi/2019b,GCCcore/8.3.0] OpenBabel v3.0.0, RapidJSON v1.1.0 w/ Python 3.7.4

### PR DESCRIPTION
**Pull request by smoors**
(created using `eb --new-pr`)

depends on easyblock ~~https://github.com/easybuilders/easybuild-easyblocks/pull/1992~~

### CODE REVIEW

**Comment by smoors** [comment]
Test report by @smoors
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in this PR)
node376.hydra.os - Linux centos linux 7.7.1908, Intel(R) Xeon(R) Gold 6148 CPU @ 2.40GHz, Python 2.7.5
See https://gist.github.com/8e6c0a42df19ecf4da9646568e238530 for a full test report.

**Comment by zao** [comment]
Test report by @zao
**FAILED**
Build succeeded for 1 out of 2 (2 easyconfigs in this PR)
freja - Linux ubuntu 18.04, Intel(R) Core(TM) i7-8700K CPU @ 3.70GHz, Python 2.7.17
See https://gist.github.com/5170d5378b9ac01a55a2b95523e87d1b for a full test report.

**Comment by zao** [comment]
Seems like there's an unhandled optional dependency on Boost:
```
-- Found Boost: /usr/include (found version "1.65.1") found components:  program_options iostreams regex
```
From `CMakeError.log` when testing for `pthread.h` - seems like `cstd` with a C++11 standard gets into C build flags:
```
/hp/eb/software/GCCcore/8.3.0/bin/gcc   -O2 -ftree-vectorize -mavx2 -fno-math-errno -fPIC -std=c++11 -fopenmp -Werror -fPIE   -o CMakeFiles/cmTC_2867f.dir/CheckIncludeFile.c.o   -c /
hp/eb/build/OpenBabel/3.0.0/GCC-8.3.0-Python-3.7.4/easybuild_obj/CMakeFiles/CMakeTmp/CheckIncludeFile.c
cc1: error: command line option ‘-std=c++11’ is valid for C++/ObjC++ but not for C [-Werror]
```

**Comment by smoors** [comment]
@zao Boost is only needed for supporting Maestro formats; might as well just add it.

the c++11 error you get is due to the `-Werror` flag. This standard is not really needed, so I just removed it.

**Comment by smoors** [comment]
Test report by @smoors
**FAILED**
Build succeeded for 1 out of 2 (2 easyconfigs in this PR)
node372.hydra.os - Linux centos linux 7.7.1908, Intel(R) Xeon(R) Gold 6148 CPU @ 2.40GHz, Python 2.7.5
See https://gist.github.com/6ffa30fd3534f39f3b5c00268a605343 for a full test report.

**Comment by smoors** [comment]
Test report by @smoors
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in this PR)
node376.hydra.os - Linux centos linux 7.7.1908, Intel(R) Xeon(R) Gold 6148 CPU @ 2.40GHz, Python 2.7.5
See https://gist.github.com/1cf3f3948f5138d033de5e092a93f96f for a full test report.

**Comment by zao** [comment]
Test report by @zao
**FAILED**
Build succeeded for 1 out of 2 (2 easyconfigs in this PR)
freja - Linux ubuntu 18.04, Intel(R) Core(TM) i7-8700K CPU @ 3.70GHz, Python 2.7.17
See https://gist.github.com/e2573d66c6355267bd38ba6ae0d3b39b for a full test report.

**Comment by smoors** [comment]
@zao did you use the updated easyblock (see at the top of this PR)?

**Comment by zao** [comment]
Test report by @zao
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in this PR)
freja - Linux ubuntu 18.04, Intel(R) Core(TM) i7-8700K CPU @ 3.70GHz, Python 2.7.17
See https://gist.github.com/6b412c9be2dde1a509f0c4094f441935 for a full test report.

**Comment by zao** [comment]
@smoors Nope, didn't notice :D
Re-running with the easyblock.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in this PR)
node3100.skitty.os - Linux centos linux 7.7.1908, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz (skylake_avx512), Python 3.6.8
See https://gist.github.com/00a846718708d0d9de69888c75d88ce2 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in this PR)
generoso - Linux centos linux 7.6.1810, Intel(R) Xeon(R) CPU E5-2660 v4 @ 2.00GHz, Python 3.6.8
See https://gist.github.com/94a1ebb30f328ff893e57e7bf29569ec for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in this PR)
node2622.swalot.os - Linux centos linux 7.7.1908, Intel(R) Xeon(R) CPU E5-2660 v3 @ 2.60GHz (haswell), Python 2.7.5
See https://gist.github.com/44e71724956cbcf6849e1d9a241a99a0 for a full test report.

**Comment by boegel** [comment]
Going in, thanks @smoors!

**Pull request merged**
