### PR TITLE
{compiler} GCC 10.2.0 + binutils 2.35

### PR DESCRIPTION
**Pull request by boegel**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by casparvl** [comment]
Test report by @casparvl
**FAILED**
Build succeeded for 1 out of 10 (10 easyconfigs in this PR)
tcn180.bullx - Linux RHEL 7.7, x86_64, Intel(R) Xeon(R) CPU E5-2695 v2 @ 2.40GHz, Python 2.7.5
See https://gist.github.com/ed75422ab2486c4c26604a458af2993b for a full test report.

**Comment by boegel** [comment]
@casparvl Test failed because of lock file that is already present...

**Comment by boegel** [comment]
@boegelbot please test @ generoso

**Comment by casparvl** [comment]
> @casparvl Test failed because of lock file that is already present...

You're right, I was trying to build on multiple architectures, but both in my homedir... I forgot about that =)

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 10 out of 10 (10 easyconfigs in this PR)
node3401.kirlia.os - Linux centos linux 7.8.2003, x86_64, Intel(R) Xeon(R) Gold 6240 CPU @ 2.60GHz (cascadelake), Python 2.7.5
See https://gist.github.com/8c2b6c12baa2b23fa4125061016364bd for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 10 out of 10 (10 easyconfigs in this PR)
node3159.skitty.os - Linux centos linux 7.8.2003, x86_64, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz (skylake_avx512), Python 3.6.8
See https://gist.github.com/26dae734d62ebd1a532da20a41848428 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 10 out of 10 (10 easyconfigs in this PR)
node2556.golett.os - Linux centos linux 7.8.2003, x86_64, Intel(R) Xeon(R) CPU E5-2680 v3 @ 2.50GHz (haswell), Python 2.7.5
See https://gist.github.com/45ea2ed24eb0edb56f62a078b0fad83b for a full test report.

**Comment by casparvl** [comment]
Test report by @casparvl
**SUCCESS**
Build succeeded for 10 out of 10 (10 easyconfigs in this PR)
software1.lisa.surfsara.nl - Linux debian 10.5, x86_64, Intel(R) Xeon(R) Silver 4110 CPU @ 2.10GHz, Python 2.7.16
See https://gist.github.com/0082e9bf7ada911a166376cc3382098b for a full test report.

**Comment by casparvl** [comment]
Test report by @casparvl
**SUCCESS**
Build succeeded for 10 out of 10 (10 easyconfigs in this PR)
tcn900.bullx - Linux RHEL 7.7, x86_64, Intel(R) Xeon(R) CPU E5-2690 v3 @ 2.60GHz, Python 2.7.5
See https://gist.github.com/f91075d953b9a788d13de05c209482c0 for a full test report.

**Comment by casparvl** [comment]
Test report by @casparvl
**SUCCESS**
Build succeeded for 10 out of 10 (10 easyconfigs in this PR)
tcn180.bullx - Linux RHEL 7.7, x86_64, Intel(R) Xeon(R) CPU E5-2695 v2 @ 2.40GHz, Python 2.7.5
See https://gist.github.com/e68de362af9373bdbb08a27baf5c7617 for a full test report.

**Pull request merged**
