### PR TITLE
{compiler}[GCCcore/10.2.0, 11.2.0] Clang v11.0.1, v12.0.1

### PR DESCRIPTION
**Pull request by bowentan**
(created using `eb --new-pr`)
Add libffi and elfutils as dependencies

### CODE REVIEW

**Review by Micket — APPROVED** [review]
lgtm (as discussed in slack, this was pretty clear cut; libomptarget.* dynamically links to both libffi and libelf)

**Comment by Micket** [comment]
Test report by @Micket
**SUCCESS**
Build succeeded for 4 out of 4 (2 easyconfigs in total)
alvis-s1 - Linux Rocky Linux 8.5, x86_64, Intel(R) Xeon(R) Silver 4314 CPU @ 2.40GHz, Python 3.6.8
See https://gist.github.com/eca7d5935f8a6db1035dec7c6bb5a013 for a full test report.

**Comment by Micket** [comment]
@boegelbot please test @ generoso

**Comment by Micket** [comment]
Going in, thanks @bowentan!

**Comment by boegel** [comment]
I've made this fix consistent in recent `Clang` easyconfigs in #16225

**Comment by zdemat** [comment]
@boegel Then I am interested in the test result of #16225 for Clang11.0.1 as I reported a possible issue with the easyblock: [fix sanity checks for Clang 11 when built with NVPTX support easyblocks/#2782](https://github.com/easybuilders/easybuild-easyblocks/issues/2782)

**Comment by boegel** [comment]
@zdemat I'll keep an eye out for that, thanks for the PR!

**Pull request merged**
