### PR TITLE
{bio}[foss/2020a] Update GO.db to 3.11.4 in R-bundle-Bioconductor-3.11

### PR DESCRIPTION
**Pull request by verdurin**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by boegel** [comment]
@verdurin Can you clarify why this is needed? The installation shouldn't be broken since sources for Bioconductor extensions are available through an archive no?

Also, why remove several extensions?

**Comment by verdurin** [comment]
@boegel could have been a temporary error. Nevertheless, I found that the old versions didn't download.

Didn't consciously remove any extensions - were they perhaps added after this was created?

**Comment by boegel** [comment]
GO.db 3.11.1 indeed disappeared, so I guess our only option is to bump.

I reached out to the developers via https://github.com/Bioconductor/GO.db/issues/1, let's see if we hear something back...

Can you sync this PR with current `develop` so it's really only a bump of GO.db and nothing else?

**Comment by boegel** [comment]
superseded by #10791

**Pull request closed without merging**
