### PR TITLE
{bio}[GCCcore/11.2.0] canu v2.2

### PR DESCRIPTION
**Pull request by ItIsI-Orient**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by boegel** [comment]
Hmm, the failing tests are due to `Java/15` being used in the Bazel easyconfig that was merged in #14654, we should stick with `Java/11` after all there, for now.

For the `2022a` generation, we can consider going with a more recent Java, but for `2021b` the ship has sailed already actually (also because `R/4.1.2-foss-2021b` depends on `Java/11`).

cc @SebastianAchilles @surak

**Comment by verdurin** [comment]
Test report by @verdurin
**SUCCESS**
Build succeeded for 2 out of 2 (1 easyconfigs in total)
centos7.lan - Linux centos linux 7.9.2009, x86_64, Intel Core Processor (Skylake, IBRS), Python 3.6.8
See https://gist.github.com/28cdf5d08fe117dfe1e4b33458cc39ce for a full test report.

**Comment by verdurin** [comment]
@boegelbot please test @ generoso

**Review by boegel — APPROVED** [review]
lgtm

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
node2643.swalot.os - Linux centos linux 7.9.2009, x86_64, Intel(R) Xeon(R) CPU E5-2660 v3 @ 2.60GHz (haswell), Python 3.6.8
See https://gist.github.com/542d1ed01787fdef4817695256063b53 for a full test report.

**Comment by boegel** [comment]
@boegelbot please test @ jsc-zen2

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
node3502.doduo.os - Linux RHEL 8.2, x86_64, AMD EPYC 7552 48-Core Processor (zen2), Python 3.6.8
See https://gist.github.com/380c1e206791da4cf0adae6f159c05f2 for a full test report.

**Comment by boegel** [comment]
Going in, thanks @ItIsI-Orient!

**Pull request merged**
