### PR TITLE
Arch specific deps fosscuda

### PR DESCRIPTION
**Pull request by edmondac**
(Edited 1 Oct 2019) This now just uses https://github.com/easybuilders/easybuild-easyblocks/pull/1797 for the cudaarch template var. Various changes to frameworks and easyblocks have built towards the final state of this PR.

### CODE REVIEW

**Comment by edmondac** [comment]
This also requires https://github.com/easybuilders/easybuild-easyblocks/pull/1697

**Comment by edmondac** [comment]
The required cuda easyblock changes are in https://github.com/easybuilders/easybuild-easyblocks/pull/1766

**Comment by edmondac** [comment]
`check_sha256_checksums` comes from `easybuild.framework.easyconfig.tools` - so we need https://github.com/easybuilders/easybuild-framework/pull/2940 merging first...

**Comment by edmondac** [comment]
This now needs https://github.com/easybuilders/easybuild-framework/pull/2946 to be merged first...

**Comment by edmondac** [comment]
https://github.com/easybuilders/easybuild-framework/pull/2974 should fix the test failure...

**Comment by edmondac** [comment]
OK - so the reason this test is failing is:

1) The sources list for this easyconfig is:
`sources = ['%%(namelower)s_%%(version)s_%s_linux%%%%(cudaarch)s.run' % local_nv_version] ` - which becomes `['cuda_10.1.105_418.39_linux%(cudaarch)s.run']` when EasyBuild has parsed the easyconfig
2) The cuda easyblock's `fetch_sources` method handles this and substitutes something sensible for `cudaarch`
3) The test just uses the sources straight, and so is looking for `cuda_10.1.105_418.39_linux%(cudaarch)s.run` in the checksum dict.

What should I do to get around this?

**Comment by edmondac** [comment]
Solution (I think) is here: https://github.com/easybuilders/easybuild-easyblocks/pull/1797

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in this PR)
node2694.swalot.os - Linux centos linux 7.6.1810, Intel(R) Xeon(R) CPU E5-2660 v3 @ 2.60GHz, Python 2.7.5
See https://gist.github.com/6a620a1de05b8b18beb927de9ba1d477 for a full test report.

**Comment by edmondac** [comment]
Test report by @bear-software
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in this PR)
bear-pg0305u03a.bear.cluster - Linux RHEL 7.6, 8335-GTX, Python 2.7.5
See https://gist.github.com/d5c372baafb44925dad54aac98bca24d for a full test report.

**Comment by edmondac** [comment]
Test report by @bear-software
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in this PR)
bear-pg0211u03a.bear.cluster - Linux centos linux 7.6.1810, Intel(R) Xeon(R) Gold 6248 CPU @ 2.50GHz, Python 2.7.5
See https://gist.github.com/b8e86fb3e6909cd2830f89d1720f4b9e for a full test report.

**Comment by boegel** [comment]
Thanks for the test report @edmondac! :+1:

**Pull request merged**
