### PR TITLE
{numlib}[GCC/12.3.0] OpenBLAS v0.3.23

### PR DESCRIPTION
**Pull request by bartoldeman**
(created using `eb --new-pr`)

depends on:
* https://github.com/easybuilders/easybuild-easyblocks/pull/2944
* https://github.com/easybuilders/easybuild-easyconfigs/pull/17955

### CODE REVIEW

**Comment by bartoldeman** [comment]
Test report by @bartoldeman
Using easyblocks from PR(s) https://github.com/easybuilders/easybuild-easyblocks/pull/2944
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
build-node.computecanada.ca - Linux CentOS Linux 7.9.2009, x86_64, Intel Xeon Processor (Skylake, IBRS), Python 3.7.7
See https://gist.github.com/bartoldeman/2d6c82c549735d153d40bec198efb908 for a full test report.

**Comment by branfosj** [comment]
Test report by @branfosj
Using easyblocks from PR(s) https://github.com/easybuilders/easybuild-easyblocks/pull/2944
**SUCCESS**
Build succeeded for 3 out of 3 (1 easyconfigs in total)
bear-pg0105u03a.bear.cluster - Linux RHEL 8.6, x86_64, Intel(R) Xeon(R) Platinum 8360Y CPU @ 2.40GHz (icelake), Python 3.6.8
See https://gist.github.com/branfosj/3b651dd0989d293d61f5ce0f8de2987a for a full test report.

**Comment by branfosj** [comment]
@boegelbot please test @ jsc-zen2

**Comment by branfosj** [comment]
Test report by @branfosj
**SUCCESS**
Build succeeded for 19 out of 19 (1 easyconfigs in total)
bear-pg0211u03a.bear.cluster - Linux RHEL 8.6, x86_64, Intel(R) Xeon(R) Gold 6248 CPU @ 2.50GHz (cascadelake), Python 3.6.8
See https://gist.github.com/branfosj/97a85f2bdea1cf98a18de31e8da4a3f4 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**FAILED**
Build succeeded for 1 out of 2 (1 easyconfigs in total)
fair-mastodon-c6g-2xlarge-0003 - Linux Rocky Linux 8.7, AArch64, ARM UNKNOWN (graviton2), Python 3.6.8
See https://gist.github.com/boegel/14686dbfac691670b185ccf7475bb7b0 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
node3159.skitty.os - Linux RHEL 8.6, x86_64, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz (skylake_avx512), Python 3.6.8
See https://gist.github.com/boegel/69c0b92c86ffd16d115cf506ec37d2e5 for a full test report.

**Comment by boegel** [comment]
More info on the failing test on `aarch64`:

```
Testing REAL              Nonsymmetric-Generalized-Eigenvalue-Problem-driver-EIG/xeigtsts < sgd.in > sgd.out  SDRGES3: SGGES3 returned INFO=     9.
  SGS drivers:      1 out of   1555 tests failed to pass the threshold
 passed: 8922
failing to pass the threshold: 1
Info Error: 1
```

and from `lapack-netlib/TESTING/testing_results.txt` in the build directory:

```
 SDRGES3: SGGES3 returned INFO=     9.
         N=     6, JTYPE=    21, ISEED=(3192,1998,1256,3633,

 SGS -- Real Generalized Schur form driver
 Matrix types (see SDRGES3 for details):
 Special Matrices:                       (J'=transposed Jordan block)
   1=(0,0)  2=(I,0)  3=(0,I)  4=(I,I)  5=(J',J')  6=(diag(J',I), diag(I,J'))
 Diagonal Matrices:  ( D=diag(0,1,2,...) )
   7=(D,I)   9=(large*D, small*I)  11=(large*I, small*D)  13=(large*D, large*I)
   8=(I,D)  10=(small*D, large*I)  12=(small*I, large*D)  14=(small*D, small*I)
  15=(D, reversed D)
 Matrices Rotated by Random Orthogonal Matrices U, V:
  16=Transposed Jordan Blocks             19=geometric alpha, beta=0,1
  17=arithm. alpha&beta                   20=arithmetic alpha, beta=0,1
  18=clustered alpha, beta=0,1            21=random alpha, beta=0,1
 Large & Small Matrices:
  22=(large, small)   23=(small,large)    24=(small,small)    25=(large,large)
  26=random O(1) matrices.

 Tests performed:  (S is Schur, T is triangular, Q and Z are orthogonal,
                   l and r are the appropriate left and right
                   eigenvectors, resp., a is alpha, b is beta, and
                   ' means transpose.)
 Without ordering:
  1 = | A - Q S Z' | / ( |A| n ulp )      2 = | B - Q T Z' | / ( |B| n ulp )
  3 = | I - QQ' | / ( n ulp )             4 = | I - ZZ' | / ( n ulp )
  5 = A is in Schur form S
  6 = difference between (alpha,beta) and diagonals of (S,T)
 With ordering:
  7 = | (A,B) - Q (S,T) Z' | / ( |(A,B)| n ulp )
  8 = | I - QQ' | / ( n ulp )            9 = | I - ZZ' | / ( n ulp )
 10 = A is in Schur form S
 11 = difference between (alpha,beta) and diagonals of (S,T)
 12 = SDIM is the correct number of selected eigenvalues


 Tests performed:  (S is Schur, T is triangular, Q and Z are ',
                   l and r are the appropriate left and right
                   eigenvectors, resp., a is alpha, b is beta, and

 Matrix order=    6, type=21, seed=3192,1998,1256,3633, result  7 is 8.389E+06
 SGS drivers:      1 out of   1555 tests failed to pass the threshold
 *** Error code from SDRGES3 =    9
```

Let's not block the merging of this PR over that, since this looks specific to `aarch64`, but we should definitely follow up on it.

I have no idea if `9` as error code means a segfault as it usually does...

@bartoldeman Do you happen have any insight here? I'm hoping you're up for reporting this upstream, since you have more experience with OpenBLAS

**Comment by boegel** [comment]
@boegelbot please test @ generoso

**Comment by boegel** [comment]
Test report by @boegel
**FAILED**
Build succeeded for 0 out of 1 (1 easyconfigs in total)
node4115.gallade.os - Linux RHEL 8.6, x86_64, AMD EPYC 7773X 64-Core Processor (zen3), Python 3.6.8
See https://gist.github.com/boegel/21a0321185ae8ef6556ef8ae29d6f0d4 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**FAILED**
Build succeeded for 0 out of 1 (1 easyconfigs in total)
node3577.doduo.os - Linux RHEL 8.6, x86_64, AMD EPYC 7552 48-Core Processor (zen2), Python 3.6.8
See https://gist.github.com/boegel/74a375ce9f14231616a7f891b4533c26 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**FAILED**
Build succeeded for 0 out of 1 (1 easyconfigs in total)
node2703.swalot.os - Linux RHEL 8.6, x86_64, Intel(R) Xeon(R) CPU E5-2660 v3 @ 2.60GHz (haswell), Python 3.6.8
See https://gist.github.com/boegel/dbbfca4295461c3fc8cc607c9f2714ff for a full test report.

**Comment by boegel** [comment]
Hmm, on our Intel Haswell + AMD Rome & Milan systems, I consistently get this a double precision numerical error:

```
			-->   LAPACK TESTING SUMMARY  <--
SUMMARY             	nb test run 	numerical error   	other error  
================   	===========	=================	================  
REAL             	1328283		0	(0.000%)	0	(0.000%)	
DOUBLE PRECISION	1327545		1	(0.000%)	1	(0.000%)	
COMPLEX          	786943		4	(0.001%)	0	(0.000%)	
COMPLEX16         	786918		21	(0.003%)	0	(0.000%)	

--> ALL PRECISIONS	4229689		26	(0.001%)	1	(0.000%)	
```

Problem on `generoso` seems to be exactly the same?

In all these cases, the updated OpenBLAS from https://github.com/easybuilders/easybuild-easyblocks/pull/2944 was used.

**Comment by boegel** [comment]
> Test report by @branfosj Using easyblocks from PR(s) [easybuilders/easybuild-easyblocks#2944](https://github.com/easybuilders/easybuild-easyblocks/pull/2944) **SUCCESS** Build succeeded for 3 out of 3 (1 easyconfigs in total) bear-pg0105u03a.bear.cluster - Linux RHEL 8.6, x86_64, Intel(R) Xeon(R) Platinum 8360Y CPU @ 2.40GHz (icelake), Python 3.6.8 See https://gist.github.com/branfosj/3b651dd0989d293d61f5ce0f8de2987a for a full test report.
> 
> ```
>             -->   LAPACK TESTING SUMMARY  <--
> SUMMARY                 nb test run     numerical error     other error  
> ================    =========== =================   ================  
> REAL                1328283     0   (0.000%)    0   (0.000%)    
> DOUBLE PRECISION    1325997     12  (0.001%)    0   (0.000%)    
> COMPLEX             785851      13  (0.002%)    0   (0.000%)    
> COMPLEX16           784902      15  (0.002%)    0   (0.000%)    
> 
> --> ALL PRECISIONS  4225033     40  (0.001%)    0   (0.000%)
> ```

@branfosj I'm confused, how can this be a successful test report if there are numerical errors?

**Comment by branfosj** [comment]
> @branfosj I'm confused, how can this be a successful test report if there are numerical errors?

We allow up to 150 failing numerical errors:
```
max_failing_lapack_tests_num_errors = 150
```

But 0 other errors. See also the code in https://github.com/easybuilders/easybuild-easyblocks/blob/develop/easybuild/easyblocks/o/openblas.py#L96

**Comment by bartoldeman** [comment]
ok, it seems to fail on avx2 arches (Haswell, zen2, zen2), but not avx512 *lake. Let me try if I can reproduce that.

**Comment by bartoldeman** [comment]
I've reproduced it locally, will try to debug later.

**Comment by boegel** [comment]
> ok, it seems to fail on avx2 arches (Haswell, zen2, zen2), but not avx512 *lake. Let me try if I can reproduce that.

At first glance it looks like it's the same problem as on `aarch64`, cfr. https://github.com/easybuilders/easybuild-easyconfigs/pull/18012#issuecomment-1574982631

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
easybuild2.novalocal - Linux CentOS Stream 8, POWER, IBM pSeries (emulated by qemu) (power9le), Python 3.6.8
See https://gist.github.com/boegel/61658c7019de5d8981e472ba39f5372f for a full test report.

**Comment by branfosj** [comment]
Test report by @branfosj
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
bear-pg0105u03a.bear.cluster - Linux RHEL 8.6, x86_64, Intel(R) Xeon(R) Platinum 8360Y CPU @ 2.40GHz (icelake), Python 3.6.8
See https://gist.github.com/branfosj/81712cadc8acdac74074fdf566497b65 for a full test report.

**Comment by bartoldeman** [comment]
@boegelbot please test @ generoso

**Comment by branfosj** [comment]
Test report by @branfosj
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
bear-pg0210u06a.bear.cluster - Linux RHEL 8.6, x86_64, Intel(R) Xeon(R) CPU E5-2640 v4 @ 2.40GHz (broadwell), Python 3.6.8
See https://gist.github.com/branfosj/8e2685b52c2b56a60772d274dcecc5fd for a full test report.

**Comment by bartoldeman** [comment]
@akesandgren mentioned some testing routines may be overoptimized.. I'll check if changing that may fix it as well.

**Comment by bartoldeman** [comment]
I tried compiling everything in MATGEN and EIG with -O0, makes no difference, workaround is still necessary, so easiest to just stick with what we have now.

**Comment by casparvl** [comment]
Test report by @casparvl
Using easyblocks from PR(s) https://github.com/easybuilders/easybuild-easyblocks/pull/2944
**SUCCESS**
Build succeeded for 0 out of 0 (1 easyconfigs in total)
tcn2.local.snellius.surf.nl - Linux Rocky Linux 8.7, x86_64, AMD EPYC 7H12 64-Core Processor, Python 3.6.8
See https://gist.github.com/casparvl/eb0cca494078ca7dcc76ea29d24c7b59 for a full test report.

**Comment by casparvl** [comment]
Test report by @casparvl
Using easyblocks from PR(s) https://github.com/easybuilders/easybuild-easyblocks/pull/2944
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
tcn2.local.snellius.surf.nl - Linux Rocky Linux 8.7, x86_64, AMD EPYC 7H12 64-Core Processor, Python 3.6.8
See https://gist.github.com/casparvl/677431ea827f76391cae6e98e28fd6d9 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**FAILED**
Build succeeded for 0 out of 1 (1 easyconfigs in total)
fair-mastodon-c6g-2xlarge-0001 - Linux Rocky Linux 8.7, AArch64, ARM UNKNOWN (graviton2), Python 3.6.8
See https://gist.github.com/boegel/29f8f51e01688c51abe9e836c319d4f3 for a full test report.

**Comment by bartoldeman** [comment]
@boegelbot please test @ generoso

**Comment by bartoldeman** [comment]
Test report by @bartoldeman
**FAILED**
Build succeeded for 0 out of 1 (1 easyconfigs in total)
build-node.computecanada.ca - Linux CentOS Linux 7.9.2009, x86_64, Intel Xeon Processor (Skylake, IBRS), Python 3.7.7
See https://gist.github.com/bartoldeman/1264453d82bc0ca021893eae7323208e for a full test report.

**Comment by bartoldeman** [comment]
Test report by @bartoldeman
Using easyblocks from PR(s) https://github.com/easybuilders/easybuild-easyblocks/pull/2944
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
build-node.computecanada.ca - Linux CentOS Linux 7.9.2009, x86_64, Intel Xeon Processor (Skylake, IBRS), Python 3.7.7
See https://gist.github.com/bartoldeman/7516c02bc5f7307a40bedc79dd8215df for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
fair-mastodon-c6g-2xlarge-0001 - Linux Rocky Linux 8.7, AArch64, ARM UNKNOWN (graviton2), Python 3.6.8
See https://gist.github.com/boegel/fe0621be68693c7330ec69b5d63e5dc2 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
node3534.doduo.os - Linux RHEL 8.6, x86_64, AMD EPYC 7552 48-Core Processor (zen2), Python 3.6.8
See https://gist.github.com/boegel/8078568aa0dafd1f3609ad1a6aad1583 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
node4115.gallade.os - Linux RHEL 8.6, x86_64, AMD EPYC 7773X 64-Core Processor (zen3), Python 3.6.8
See https://gist.github.com/boegel/24da7d792aa32d6f490a1eebdbe5a565 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
node2703.swalot.os - Linux RHEL 8.6, x86_64, Intel(R) Xeon(R) CPU E5-2660 v3 @ 2.60GHz (haswell), Python 3.6.8
See https://gist.github.com/boegel/7262e2472a1b631f1b141b81a214713b for a full test report.

**Review by boegel — APPROVED** [review]
lgtm

**Comment by boegel** [comment]
Test report by @boegel
**FAILED**
Build succeeded for 0 out of 1 (1 easyconfigs in total)
easybuild2.novalocal - Linux CentOS Stream 8, POWER, IBM pSeries (emulated by qemu) (power9le), Python 3.6.8
See https://gist.github.com/boegel/77be984210845996059034cd6702aad6 for a full test report.

**Comment by boegel** [comment]
@bartoldeman Trouble on POWER9 (emulated) now, apparently, while it worked fine before (cfr. https://github.com/easybuilders/easybuild-easyconfigs/pull/18012#issuecomment-1575456223).

I won't this block the merge, if it's worth following up, let's open an issue or follow-up PR...

**Comment by boegel** [comment]
Going in, thanks @bartoldeman!

**Comment by bartoldeman** [comment]
POWER fails in the same place as Haswell without the patch, it's odd indeed.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 20 out of 20 (1 easyconfigs in total)
node4012.donphan.os - Linux RHEL 8.6, x86_64, Intel(R) Xeon(R) Gold 6240 CPU @ 2.60GHz (cascadelake), 1 x NVIDIA NVIDIA A2, 530.30.02, Python 3.6.8
See https://gist.github.com/boegel/b8b7fbfebf9378c5d960a943725ee856 for a full test report.

**Comment by boegel** [comment]
@Flamefire Any thoughts on the failing test on POWER? (if we should follow up on this, please open an issue)

**Comment by Flamefire** [comment]
Failing POWER test fixed in https://github.com/easybuilders/easybuild-easyconfigs/pull/19495

**Pull request merged**
