### PR TITLE
{bio} [Anaconda3] Roary 3.12 

### PR DESCRIPTION
**Pull request by pescobar**

### CODE REVIEW

**Comment by verdurin** [comment]
@pescobar Can you use the upstream `Miniconda3` to remove the conflict?

**Comment by verdurin** [comment]
Test report by @verdurin
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
rescomp2 - Linux centos 6.8, Intel(R) Xeon(R) CPU E5-2650 v2 @ 2.60GHz, Python 2.7.11
See https://gist.github.com/39e64c630a37ed37392b9aa0b8beacee for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
node2537.golett.os - Linux centos linux 7.4.1708, Intel(R) Xeon(R) CPU E5-2680 v3 @ 2.50GHz, Python 2.7.5
See https://gist.github.com/25e7325ad3c18a5a6a586ba6117b4a52 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
node2118.delcatty.os - Linux centos linux 7.4.1708, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.7.5
See https://gist.github.com/12c1aaf931fca6b00a89f98bf05d7ff1 for a full test report.

**Comment by verdurin** [comment]
Going in, thanks @pescobar!

**Pull request merged**
