### PR TITLE
{bio}[system/system] CellRanger-ARC v2.0.2

### PR DESCRIPTION
**Pull request by sassy-crick**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by sassy-crick** [comment]
Test report by @sassy-crick
**FAILED**
Build succeeded for 0 out of 1 (1 easyconfigs in total)
hp - Linux Debian GNU/Linux 12, x86_64, 11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz, Python 3.11.2
See https://gist.github.com/sassy-crick/95c527a246ea5cf123783259648c1662 for a full test report.

**Comment by sassy-crick** [comment]
Test report by @sassy-crick
**FAILED**
Build succeeded for 0 out of 1 (1 easyconfigs in total)
hp - Linux Debian GNU/Linux 12, x86_64, 11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz, Python 3.11.2
See https://gist.github.com/sassy-crick/09fd43be1a521ad92ee3fb685e8c32ab for a full test report.

**Comment by sassy-crick** [comment]
Test report by @sassy-crick
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
hp - Linux Debian GNU/Linux 12, x86_64, 11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz, Python 3.11.2
See https://gist.github.com/sassy-crick/e5b137f3086b2e783b8b125d0dd8d7dc for a full test report.

**Comment by verdurin** [comment]
Test report by @verdurin
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
easybuild-c7.novalocal - Linux CentOS Linux 7.9.2009, x86_64, Intel Xeon Processor (Skylake, IBRS), Python 3.6.8
See https://gist.github.com/verdurin/9a6988a766e1c21b283b3fd30b19a9ee for a full test report.

**Review by verdurin — APPROVED** [review]
Looks fine.

**Pull request merged**
