### PR TITLE
add missing dependencies for ITK 4.13.0 to avoid auto-download/install of dependencies during installation (WIP)

### PR DESCRIPTION
**Pull request by boegel**
fix for #7128 
requires:
* ~~#7307~~ (`double-conversion`)
* ~~#7308~~ (`KWIML`)
* ~~#7309~~ (`VXL`)
* ~~#7310~~ (`GDCM`)
* ~~#7311~~ (`MINC`)
* #11866 (fix for `GDCM`)

### CODE REVIEW

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
node3125.skitty.os - Linux centos linux 7.5.1804, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz, Python 2.7.5
See https://gist.github.com/b282720be18df33a740c264665196891 for a full test report.

**Comment by vanzod** [comment]
Re-trigger Travis

**Comment by vanzod** [comment]
Re-trigger Travis

**Comment by boegel** [comment]
Test report by @boegel
**FAILED**
Build succeeded for 0 out of 1 (1 easyconfigs in total)
node2707.swalot.os - Linux centos linux 7.9.2009, x86_64, Intel(R) Xeon(R) CPU E5-2660 v3 @ 2.60GHz (haswell), Python 3.6.8
See https://gist.github.com/904a6220d9dbdeb4ff43e107ea9b436c for a full test report.

**Comment by boegel** [comment]
Now it's clear why this is still WIP:

```
CMake Error at CMake/ITKDownloadSetup.cmake:14 (message):
  Attempted to download Module_BridgeNumPy when ITK_FORBID_DOWNLOADS is ON
```

```
CMake Error at CMake/ITKModuleRemote.cmake:12 (message):
  Failed to clone repository:
  '://github.com/InsightSoftwareConsortium/ITKBridgeNumPy.git'
```

**Comment by verdurin** [comment]
Test report by @verdurin
**FAILED**
Build succeeded for 14 out of 18 (1 easyconfigs in total)
easybuild-c7.novalocal - Linux centos linux 7.9.2009, x86_64, Intel Xeon Processor (Skylake, IBRS), Python 3.6.8
See https://gist.github.com/475354e7a2e730b82e96b597dfaa82a8 for a full test report.

**Comment by verdurin** [comment]
Test report by @verdurin
**FAILED**
Build succeeded for 2 out of 3 (1 easyconfigs in total)
easybuild-c7.novalocal - Linux centos linux 7.9.2009, x86_64, Intel Xeon Processor (Skylake, IBRS), Python 3.6.8
See https://gist.github.com/0f867304fa1309e2352d2aad91c546c8 for a full test report.

**Comment by boegel** [comment]
Not planning to pursue this, since it concerns a now ancient version of ITK, and the easyconfig uses a deprecated toolchain (see https://docs.easybuild.io/en/latest/Deprecated-easyconfigs.html#deprecated-toolchains)...

**Pull request closed without merging**
