### PR TITLE
{tools}[foss/2021b] jax v0.3.23 w/ Python 3.9.6

### PR DESCRIPTION
**Pull request by ThomasHoffmann77**
(created using `eb --new-pr`)
requires #16970

### CODE REVIEW

**Comment by SebastianAchilles** [comment]
@boegelbot please test @ generoso

**Comment by smoors** [comment]
@ThomasHoffmann77 the `Pillow` version that comes with the `matplotlib` builddep seems too old, it needs to be at least `9.1.0`.
see also https://github.com/python-pillow/Pillow/pull/5954/files
```
    def __getattr__(name):
        if name == "PILLOW_VERSION":
            _raise_version_warning()
            return __version__
        else:
            categories = {"NORMAL": 0, "SEQUENCE": 1, "CONTAINER": 2}
            if name in categories:
                warnings.warn(
                    "Image categories are deprecated and will be removed in Pillow 10 "
                    "(2023-01-02). Use is_animated instead.",
                    DeprecationWarning,
                    stacklevel=2,
                )
                return categories[name]
>       raise AttributeError(f"module '{__name__}' has no attribute '{name}'")
E       AttributeError: module 'PIL.Image' has no attribute 'Resampling'
```

**Comment by ThomasHoffmann77** [comment]
@smoors Would adding matplotlib and Pilllow to the jax exts_list be an appropriate solution? Not sure if we can use a lower version of jax for AlphaFold 2.3.0 #16874 (requirement: jax==0.3.25). Switching AlphaFold 2.3.0 to foss/2022a is blocked due to missing TensorFlow for this toolchain.

**Comment by smoors** [comment]
@ThomasHoffmann77 adding matplotlib and Pilllow to the jax exts_list can potentially create issues for users (for example) loading TensorFlow and matplotlib together. depending on the order of loading, you will get a different version.
also, doing this will change them from build dependencies to normal deps.

as matplotlib and Pillow are only build dependencies, an alternative would be to create easyconfigs for those. there is no single-dep-version rule for builddeps, only for normal deps.

the best solution IMHO would be to get TF 2.9.1 at `2022a` over the finish line, see
https://github.com/easybuilders/easybuild-easyconfigs/pull/16620
https://github.com/easybuilders/easybuild-easyconfigs/pull/16008

**Comment by fizwit** [comment]
@ThomasHoffmann77 @smoors back porting matplotlib-3.5.2 fixed the testing failures at my site and jax is building. Using Pillow-9.1.0 with matplotlib-3.5.2-foss-2021b at my site. I have many copies of Pillow because it is a depenedancy nightmare.  If I was forced to use only one version Pillow per toolbox it would be impossible to deploy software to my customers.

**Comment by smoors** [comment]
@boegelbot: please test @ generoso

**Review by smoors — APPROVED** [review]
lgtm

**Comment by smoors** [comment]
Going in, thanks @ThomasHoffmann77!

**Pull request merged**
