### PR TITLE
{lib}[GCCcore/9.3.0] fix sanity_check_paths of CFITSIO-3.48-GCCcore-9.3.0.eb

### PR DESCRIPTION
**Pull request by lexming**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by lexming** [comment]
Test report by @lexming
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
node125.hydra.os - Linux centos linux 7.7.1908, x86_64, Intel(R) Xeon(R) CPU E5-2680 v2 @ 2.80GHz, Python 2.7.5
See https://gist.github.com/3c3d77a3f074cb5040a94104853a2923 for a full test report.

**Comment by lexming** [comment]
Test report by @lexming
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
node381.hydra.os - Linux centos linux 7.7.1908, x86_64, Intel(R) Xeon(R) Gold 6148 CPU @ 2.40GHz, Python 2.7.5
See https://gist.github.com/4731a7991f33d51067f7ab66040eb197 for a full test report.

**Comment by bartoldeman** [comment]
@lexming just curious what problem does this fix, as the test builds succeeded?

**Comment by lexming** [comment]
@bartoldeman it's a compatibility issue with non-linux systems

**Comment by bartoldeman** [comment]
Test report by @bartoldeman
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
build-node.computecanada.ca - Linux centos linux 7.8.2003, x86_64, Intel Xeon Processor (Skylake, IBRS), Python 3.7.7
See https://gist.github.com/f807306a12e2acd0630df0461030968b for a full test report.

**Comment by bartoldeman** [comment]
Going in, thanks @lexming!

**Pull request merged**
