### PR TITLE
{vis}[GCCcore/13.3.0] libGLU v9.0.3

### PR DESCRIPTION
**Pull request by paulmelis**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by SebastianAchilles** [comment]
@boegelbot please test @ jsc-zen3

**Comment by SebastianAchilles** [comment]
@boegelbot please test @ generoso

**Review by smoors — APPROVED** [review]
lgtm

**Comment by smoors** [comment]
Going in, thanks @paulmelis!

**Pull request merged**
