### PR TITLE
{tools}[GCC/11.2.0] mstore v0.2.0

### PR DESCRIPTION
**Pull request by sassy-crick**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by SebastianAchilles** [comment]
@boegelbot please test @ generoso

**Comment by smoors** [comment]
@boegelbot please test @ jsc-zen2

**Review by smoors — APPROVED** [review]
lgtm

**Comment by smoors** [comment]
Going in, thanks @sassy-crick!

**Comment by smoors** [comment]
@sassy-crick I was a bit too fast in merging this.
would you mind creating a follow-up PR for this with a sanity_check_command added?

```
sanity_check_commands = ['mstore-fortranize --help']
```

**Comment by sassy-crick** [comment]
Done (PR #17029) and assigned to you.

**Pull request merged**
