### PR TITLE
{tools}[GCCcore/9.3.0] patchelf-0.10

### PR DESCRIPTION
**Pull request by maxim-masterov**
Modified patchelf to use GCCcore-9.3.0, binutils-2.34 and Autotools-20180311

### CODE REVIEW

**Comment by maxim-masterov** [comment]
> Please consider adding this patch:
> [NixOS/patchelf@1ecffb6](https://github.com/NixOS/patchelf/commit/1ecffb613d0f60f4a2ced2c9568979277fa7cdac)
> otherwise patchelf is broken if yoy try to set rpath instead of runpath.

Done

**Comment by lexming** [comment]
Test report by @lexming
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
login2.cerberus.os - Linux centos linux 7.7.1908, Intel(R) Xeon(R) Gold 6126 CPU @ 2.60GHz, Python 2.7.5
See https://gist.github.com/160794e6a9d37e106697cda465c8da00 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
node2618.swalot.os - Linux centos linux 7.7.1908, x86_64, Intel(R) Xeon(R) CPU E5-2660 v3 @ 2.60GHz (haswell), Python 2.7.5
See https://gist.github.com/671996a479eab827c54451a57fbd5e66 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
node3407.kirlia.os - Linux centos linux 7.7.1908, x86_64, Intel(R) Xeon(R) Gold 6240 CPU @ 2.60GHz (cascadelake), Python 2.7.5
See https://gist.github.com/9536d27e7619d220cf394a886e1beb75 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
generoso - Linux centos linux 7.6.1810, x86_64, Intel(R) Xeon(R) CPU E5-2660 v4 @ 2.00GHz, Python 3.6.8
See https://gist.github.com/f9c23427298e6e2f0cac2694df3e8ff0 for a full test report.

**Comment by boegel** [comment]
Going in, thanks @maxim-masterov!

**Pull request merged**
