### PR TITLE
{phys}[foss/2023a] ISCE2 v2.6.3

### PR DESCRIPTION
**Pull request by PetrKralCZ**
(created using `eb --new-pr`)
resolves https://github.com/vscentrum/vsc-software-stack/issues/420

### CODE REVIEW

**Comment by PetrKralCZ** [comment]
@boegelbot please test @ generoso

**Comment by PetrKralCZ** [comment]
@boegelbot please test @ jsc-zen3

**Comment by laraPPr** [comment]
Test report by @laraPPr
**FAILED**
Build succeeded for 0 out of 1 (1 easyconfigs in total)
node3533.doduo.os - Linux RHEL 8.8, x86_64, AMD EPYC 7552 48-Core Processor, Python 3.11.3
See https://gist.github.com/laraPPr/f31ddb3e0d73a845cafd68f5e16f3c8c for a full test report.

**Comment by laraPPr** [comment]
forgot `--robot` triggering  again

**Comment by laraPPr** [comment]
Test report by @laraPPr
**SUCCESS**
Build succeeded for 2 out of 2 (1 easyconfigs in total)
node3533.doduo.os - Linux RHEL 8.8, x86_64, AMD EPYC 7552 48-Core Processor, Python 3.11.3
See https://gist.github.com/laraPPr/ef62de94e11f59351b72c4e7839c4e2e for a full test report.

**Comment by laraPPr** [comment]
Going in, thanks @PetrKralCZ!

**Pull request merged**
