### PR TITLE
{devel}[intel/2018a] Boost v1.66.0 (REVIEW)

### PR DESCRIPTION
**Pull request by SimonPinches**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by SimonPinches** [comment]
@boegel, do you have any comments on this one?

**Comment by boegel** [comment]
@SimonPinches This looks good to go, but if this is used as a dependency for something else, it will trigger failures in our new "dependency variants" check (see #5970), since we already use `Boost` with Python bindings enabled in other `2018a` easyconfigs...

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
node2628.swalot.os - Linux centos linux 7.4.1708, Intel(R) Xeon(R) CPU E5-2660 v3 @ 2.60GHz, Python 2.7.5
See https://gist.github.com/fb8b4a6f59b25f806e8de8489c727d62 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
gligar02.gligar.os - Linux centos linux 7.4.1708, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.7.5
See https://gist.github.com/2e4eb8444e2853a65a167763c38fbfca for a full test report.

**Comment by boegel** [comment]
Going in, thanks @SimonPinches!

**Comment by boegel** [comment]
Actually, it's the other way around...

Only `Boost` *without* `Python` bindings is used as a dependency in existing `2018a` easyconfigs, so this is good to have, sorry for the confusion.

There is a `Boost` with Python bindings used as *build* dep for `Libint`, but since that's a build dep there's no risk of introducing conflicts between modules.

**Pull request merged**
