### PR TITLE
Add alternative checksum for AFNI 18.3.00

### PR DESCRIPTION
**Pull request by branfosj**
(created using `eb --new-pr`)

Fix the issue seen in #8719

### CODE REVIEW

**Comment by branfosj** [comment]
Test report by @branfosj
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
bear-pg0211u08b.bear.cluster - Linux RHEL 8.3, x86_64, Intel(R) Xeon(R) Gold 6248 CPU @ 2.50GHz (cascadelake), Python 3.6.8
See https://gist.github.com/60c0d7eadd19db2fe44e5cb53a4e2e0f for a full test report.

**Comment by boegel** [comment]
@boegelbot please test @ generoso
CORE_CNT=16

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
node2631.swalot.os - Linux centos linux 7.9.2009, x86_64, Intel(R) Xeon(R) CPU E5-2660 v3 @ 2.60GHz (haswell), Python 3.6.8
See https://gist.github.com/f6adcbb4272e435898f65c6f28950e90 for a full test report.

**Comment by boegel** [comment]
GDAL issue is unrelated to this change, so merging...

**Review by boegel — APPROVED** [review]

**Comment by boegel** [comment]
For future reference, diff between old and new source tarball for AFNI 18.3.00:

```
$ diff -ru afni-AFNI_18.3.00.old afni-AFNI_18.3.00
Only in afni-AFNI_18.3.00.old/src/faces: face_juliefrost.jpg
Only in afni-AFNI_18.3.00.old/src/ptaylor: FAT_PRE_SCRIPTS_JAN30
```

**Comment by boegel** [comment]
Going in, thanks @branfosj!

**Pull request merged**
