### PR TITLE
{lib}[GCCcore/11.3.0] glib-networking v2.72.1

### PR DESCRIPTION
**Pull request by iotaka**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by iotaka** [comment]
I add a dependencies to     ('zstd', '1.5.2'), becouse  ('GnuTLS', '3.7.8') is bugged not includes zstd as its dependencies.

See Slak with @akesandgren

**Comment by smoors** [comment]
@iotaka as mentioned by @jfgrimm in slack,
we should add both zlib and zstd to `GnuTLS`, not to `glib-networking`

**Comment by smoors** [comment]
> @iotaka as mentioned by @jfgrimm in slack, we should add both zlib and zstd to `GnuTLS`, not to `glib-networking`

PR created: https://github.com/easybuilders/easybuild-easyconfigs/pull/17013

**Comment by smoors** [comment]
@boegelbot: please test @ generoso

**Comment by smoors** [comment]
@boegelbot please test @ jsc-zen2

**Comment by smoors** [comment]
@boegelbot please test @ jsc-zen2

**Review by smoors — APPROVED** [review]
lgtm

**Comment by smoors** [comment]
Going in, thanks @iotaka!

**Pull request merged**
