### PR TITLE
{tools}[dummy/] DMTCP v2.5.1

### PR DESCRIPTION
**Pull request by boegel**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
node2550.golett.os - Linux centos linux 7.3.1611, Intel(R) Xeon(R) CPU E5-2680 v3 @ 2.50GHz, Python 2.7.5
See https://gist.github.com/6828c3fc0da8472cfb38811d4a452e4e for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
node2024.delcatty.os - Linux centos linux 7.3.1611, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.7.5
See https://gist.github.com/3a5fcf203c3a04051ff0c2f7eb8e70e1 for a full test report.

**Comment by wpoely86** [comment]
Test report by @wpoely86
**FAILED**
Build succeeded for 0 out of 1 (1 easyconfigs in this PR)
nic200 - Linux centos linux 7.3.1611, Intel(R) Xeon(R) CPU E7-8891 v4 @ 2.80GHz, Python 2.7.5
See https://gist.github.com/b5c7353e9841577d7db16c3ac176768d for a full test report.

**Comment by wpoely86** [comment]
Test report by @wpoely86
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
nic200 - Linux centos linux 7.3.1611, Intel(R) Xeon(R) CPU E7-8891 v4 @ 2.80GHz, Python 2.7.5
See https://gist.github.com/ced47164fd6a47eb09943859afe21e2a for a full test report.

**Pull request merged**
