### PR TITLE
{math}[system/system] MATLAB v2022b

### PR DESCRIPTION
**Pull request by sassy-crick**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by sassy-crick** [comment]
I have uploaded the test-report [here](https://gist.github.com/sassy-crick/6cdba29a0e0e67edb23e4b7b02cb2241)

**Review by Micket — APPROVED** [review]
lgtm

I don't have access to the sources (yet) as I need to get it from the university IT dep. Would appreciate it if someone else who does could make upload a test report.

**Comment by lexming** [comment]
Test report by @lexming
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
login2.cerberus.os - Linux CentOS Linux 7.9.2009, x86_64, Intel(R) Xeon(R) Gold 6126 CPU @ 2.60GHz, Python 3.6.8
See https://gist.github.com/6896d8abf4132fbc8455815d6f34eea8 for a full test report.

**Review by lexming — APPROVED** [review]
LGTM

**Comment by lexming** [comment]
Going in, thanks @sassy-crick !

**Pull request merged**
