### PR TITLE
{numlib}[system/system] cuDNN v8.7.0.84

### PR DESCRIPTION
**Pull request by robogast**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by robogast** [comment]
Test report by @robogast
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
int2 - Linux RHEL 8.4, x86_64, AMD EPYC 7F32 8-Core Processor, Python 3.6.8
See https://gist.github.com/df3aad99b75f46ce53cb45ea95ac0ba3 for a full test report.

**Comment by robogast** [comment]
@jfgrimm mind taking a look? :)

**Comment by robogast** [comment]
@boegelbot: please test @ generoso

**Comment by robogast** [comment]
@boegelbot please test @ generoso

**Comment by robogast** [comment]
too bad :)

**Comment by akesandgren** [comment]
@boegelbot Please test @ generoso

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 2 out of 2 (1 easyconfigs in total)
node3101.skitty.os - Linux RHEL 8.6, x86_64, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz (skylake_avx512), Python 3.6.8
See https://gist.github.com/a4df86be645ac598f3ede36929d2ef2c for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 2 out of 2 (1 easyconfigs in total)
fair-mastodon-c6g-2xlarge-0001 - Linux Rocky Linux 8.5, AArch64, ARM UNKNOWN (graviton2), Python 3.6.8
See https://gist.github.com/254a3ed34d365b9f8dd91f3a0f61d25a for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 2 out of 2 (1 easyconfigs in total)
easybuild2.novalocal - Linux CentOS Stream 8, POWER, IBM pSeries (emulated by qemu) (power9le), Python 3.6.8
See https://gist.github.com/732b31964b7061307a367d98dd04767e for a full test report.

**Review by boegel — APPROVED** [review]
lgtm

**Comment by boegel** [comment]
Going in, thanks @robogast!

**Pull request merged**
