### PR TITLE
{tools}[GCCcore/11.3.0] rocm-smi v5.6.0

### PR DESCRIPTION
**Pull request by akesandgren**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by akesandgren** [comment]
Test report by @akesandgren
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
b-cn1605.hpc2n.umu.se - Linux Ubuntu 22.04, x86_64, AMD EPYC 7313 16-Core Processor, Python 3.10.6
See https://gist.github.com/akesandgren/3c7b543bbac4f6028e221011510bc7c7 for a full test report.

**Comment by jfgrimm** [comment]
Test report by @jfgrimm
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
node051.viking2.yor.alces.network - Linux Rocky Linux 8.8, x86_64, AMD EPYC 7643 48-Core Processor, Python 3.6.8
See https://gist.github.com/jfgrimm/749b0fd560edbe86ac48186504d184c7 for a full test report.

**Comment by jfgrimm** [comment]
@boegelbot: please test @ generoso

**Review by jfgrimm — DISMISSED** [review]
lgtm

**Comment by jfgrimm** [comment]
@boegelbot: please test @ jsc-zen2

**Comment by boegel** [comment]
Test report by @boegel
**FAILED**
Build succeeded for 0 out of 1 (1 easyconfigs in total)
node3120.skitty.os - Linux RHEL 8.8, x86_64, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz, Python 3.6.8
See https://gist.github.com/boegel/44dc3a6685354f8fd776608e68ae2b08 for a full test report.

**Comment by boegel** [comment]
@akesandgren I'm seeing a build error for `refman.pdf`, which suggests a missing (build) dependency:
```
[ 45%] Generating latex/refman.pdf
cd /tmp/vsc40023/easybuild_build/rocmsmi/5.6.0/GCCcore-11.3.0/easybuild_obj/rocm_smi/latex && make > /dev/null
make[3]: warning: jobserver unavailable: using -j1.  Add '+' to parent make rule.
make[3]: *** [Makefile:6: refman.pdf] Error 1
make[2]: *** [rocm_smi/CMakeFiles/docs.dir/build.make:76: rocm_smi/latex/refman.pdf] Error 2
```

see also https://github.com/ROCm/rocm_smi_lib/issues/93

Any ideas here?

**Comment by boegel** [comment]
> What does your configure_step say about latex ? (probably uppercase)

```
-- Found LATEX: /usr/bin/latex  found components: PDFLATEX
```

**Comment by akesandgren** [comment]
Thought so, my test-env is clean of things like that.

But if it does find both then as far as I can see in the CMakeLists.txt it should do the right thing.

What does the 20 or so lines about the "Generating latex/refman.pdf" say? esp Generating latex/refman.tex and forward.

**Comment by boegel** [comment]
@akesandgren Here's some extra output (obtained using `--parallel 1`), not very helpful I think, we may need to strip out the `> /dev/null` part...

<details>

```
[  3%] Generating latex/refman.tex
cd /tmp/easybuild_build/rocmsmi/5.6.0/GCCcore-11.3.0/easybuild_obj/rocm_smi && /usr/bin/doxygen /tmp/easybuild_build/rocmsmi/5.6.0/GCCcore-11.3.0/easybuild_obj/rocm_smi/Doxyfile
/tmp/easybuild_build/rocmsmi/5.6.0/GCCcore-11.3.0/rocm_smi_lib-rocm-5.6.0/include/rocm_smi/rocm_smi.h:887: warning: Member RSMI_GPU_METRICS_API_CONTENT_VER_1 (macro definition) of file rocm_smi.hh
 is not documented.
/tmp/easybuild_build/rocmsmi/5.6.0/GCCcore-11.3.0/rocm_smi_lib-rocm-5.6.0/include/rocm_smi/rocm_smi.h:888: warning: Member RSMI_GPU_METRICS_API_CONTENT_VER_2 (macro definition) of file rocm_smi.hh
 is not documented.
/tmp/easybuild_build/rocmsmi/5.6.0/GCCcore-11.3.0/rocm_smi_lib-rocm-5.6.0/include/rocm_smi/rocm_smi.h:889: warning: Member RSMI_GPU_METRICS_API_CONTENT_VER_3 (macro definition) of file rocm_smi.hh
 is not documented.
/tmp/easybuild_build/rocmsmi/5.6.0/GCCcore-11.3.0/rocm_smi_lib-rocm-5.6.0/include/rocm_smi/rocm_smi.h:892: warning: Member RSMI_NUM_HBM_INSTANCES (macro definition) of file rocm_smi.h is not docuu
mented.
/tmp/easybuild_build/rocmsmi/5.6.0/GCCcore-11.3.0/rocm_smi_lib-rocm-5.6.0/include/rocm_smi/rocm_smi.h:895: warning: Member CENTRIGRADE_TO_MILLI_CENTIGRADE (macro definition) of file rocm_smi.h iss
 not documented.
/tmp/easybuild_build/rocmsmi/5.6.0/GCCcore-11.3.0/rocm_smi_lib-rocm-5.6.0/include/rocm_smi/rocm_smi.h:2216: warning: Found unknown command `\utilization_counters'
/tmp/easybuild_build/rocmsmi/5.6.0/GCCcore-11.3.0/rocm_smi_lib-rocm-5.6.0/include/rocm_smi/rocm_smi.h:3501: warning: Found unknown command `\accessible'
Searching for include files...
Searching for example files...
Searching for images...
Searching for dot files...
Searching for msc files...
Searching for dia files...
Searching for files to exclude
Searching INPUT for files to process...
Reading and parsing tag files
Parsing files
Reading /tmp/easybuild_build/rocmsmi/5.6.0/GCCcore-11.3.0/rocm_smi_lib-rocm-5.6.0/README.md...
Preprocessing /tmp/easybuild_build/rocmsmi/5.6.0/GCCcore-11.3.0/rocm_smi_lib-rocm-5.6.0/include/rocm_smi/rocm_smi.h...
Parsing file /tmp/easybuild_build/rocmsmi/5.6.0/GCCcore-11.3.0/rocm_smi_lib-rocm-5.6.0/include/rocm_smi/rocm_smi.h...
Building group list...
Building directory list...
Building namespace list...
Building file list...
Building class list...
Associating documentation with classes...
Computing nesting relations for classes...
Building example list...
Searching for enumerations...
Searching for documented typedefs...
Searching for members imported via using declarations...
Searching for included using directives...
Searching for documented variables...
Building interface member list...
Building member list...
Searching for friends...
Searching for documented defines...
Computing class inheritance relations...
Computing class usage relations...
Flushing cached template relations that have become invalid...
Computing class relations...
Add enum values to enums...
Searching for member function documentation...
Creating members for template instances...
Building page list...
Search for main page...
Computing page relations...
Determining the scope of groups...
Sorting lists...
Freeing entry tree
Determining which enums are documented
Computing member relations...
Building full member lists recursively...
Adding members to member groups.
Computing member references...
Inheriting documentation...
Generating disk names...
Adding source references...
Adding xrefitems...
Sorting member lists...
Computing dependencies between directories...
Generating citations page...
Counting data structures...
Resolving user defined references...
Finding anchors and sections in the documentation...
Transferring function references...
Combining using relations...
Adding members to index pages...
Generating style sheet...
Generating search indices...
Generating example documentation...
Generating file sources...
Generating code for file rocm_smi.h...
Generating file documentation...
Generating docs for file rocm_smi.h...
Generating page documentation...
Generating docs for page md__tmp_easybuild_build_rocmsmi_5.6.0_GCCcore-11.3.0_rocm_smi_lib-rocm-5.6.0_README...
Generating docs for page deprecated...
Generating group documentation...
Generating class documentation...
Generating docs for compound id...
Generating docs for compound metrics_table_header_t...
Generating docs for compound rsmi_counter_value_t...
Generating docs for compound rsmi_error_count_t...
Generating docs for compound rsmi_evt_notification_data_t...
Generating docs for compound rsmi_freq_volt_region_t...
Generating docs for compound rsmi_frequencies_t...
Generating docs for compound rsmi_gpu_metrics_t...
Generating docs for compound rsmi_od_vddc_point_t...
Generating docs for compound rsmi_od_volt_curve_t...
Generating docs for compound rsmi_od_volt_freq_data_t...
Generating docs for compound rsmi_pcie_bandwidth_t...
Generating docs for compound rsmi_power_profile_status_t...
Generating docs for compound rsmi_process_info_t...
Generating docs for compound rsmi_range_t...
Generating docs for compound rsmi_retired_page_record_t...
Generating docs for compound rsmi_utilization_counter_t...
Generating docs for compound rsmi_version_t...
Generating namespace index...
Generating graph info page...
Generating directory documentation...
Generating index page...
Generating page index...
Generating module index...
Generating namespace index...
Generating namespace member index...
Generating annotated compound index...
Generating alphabetical compound index...
Generating hierarchical class index...
Generating member index...
Generating file index...
Generating file member index...
Generating example index...
finalizing index lists...
writing tag file...
lookup cache used 367/65536 hits=1962 misses=378
finished...
[  6%] Generating latex/refman.pdf
cd /tmp/easybuild_build/rocmsmi/5.6.0/GCCcore-11.3.0/easybuild_obj/rocm_smi/latex && make > /dev/null
make[3]: *** [Makefile:6: refman.pdf] Error 1
make[2]: *** [rocm_smi/CMakeFiles/docs.dir/build.make:76: rocm_smi/latex/refman.pdf] Error 2
make[2]: Leaving directory '/tmp/easybuild_build/rocmsmi/5.6.0/GCCcore-11.3.0/easybuild_obj'
make[1]: *** [CMakeFiles/Makefile2:372: rocm_smi/CMakeFiles/docs.dir/all] Error 2
make[1]: Leaving directory '/tmp/easybuild_build/rocmsmi/5.6.0/GCCcore-11.3.0/easybuild_obj'
make: *** [Makefile:159: all] Error 2
```

</details>

**Comment by boegel** [comment]
@akesandgren Patching out the `> /dev/null` reveals the actual problem:

```
cd /tmp/easybuild_build/rocmsmi/5.6.0/GCCcore-11.3.0/easybuild_obj/rocm_smi/latex && make
make[3]: Entering directory '/tmp/easybuild_build/rocmsmi/5.6.0/GCCcore-11.3.0/easybuild_obj/rocm_smi/latex'
rm -f *.ps *.dvi *.aux *.toc *.idx *.ind *.ilg *.log *.out *.brf *.blg *.bbl refman.pdf
pdflatex refman
This is pdfTeX, Version 3.14159265-2.6-1.40.19 (TeX Live 2018) (preloaded format=pdflatex)
 restricted \write18 enabled.
entering extended mode
(./refman.tex
LaTeX2e <2017-04-15>
Babel <3.17> and hyphenation patterns for 3 language(s) loaded.
(/usr/share/texlive/texmf-dist/tex/latex/base/book.cls
Document Class: book 2014/09/29 v1.4h Standard LaTeX document class
(/usr/share/texlive/texmf-dist/tex/latex/base/bk10.clo))
(/usr/share/texlive/texmf-dist/tex/latex/base/fixltx2e.sty

Package fixltx2e Warning: fixltx2e is not required with releases after 2015
(fixltx2e)                All fixes are now in the LaTeX kernel.
(fixltx2e)                See the latexrelease package for details.

) (/usr/share/texlive/texmf-dist/tex/latex/tools/calc.sty) (./doxygen.sty
(/usr/share/texlive/texmf-dist/tex/latex/base/alltt.sty)
(/usr/share/texlive/texmf-dist/tex/latex/tools/array.sty)
(/usr/share/texlive/texmf-dist/tex/latex/float/float.sty)
(/usr/share/texlive/texmf-dist/tex/latex/base/ifthen.sty)
(/usr/share/texlive/texmf-dist/tex/latex/tools/verbatim.sty)
(/usr/share/texlive/texmf-dist/tex/latex/xcolor/xcolor.sty
(/usr/share/texlive/texmf-dist/tex/latex/graphics-cfg/color.cfg)
(/usr/share/texlive/texmf-dist/tex/latex/graphics-def/pdftex.def)
(/usr/share/texlive/texmf-dist/tex/latex/colortbl/colortbl.sty))
(/usr/share/texlive/texmf-dist/tex/latex/tools/longtable.sty)

! LaTeX Error: File `tabu.sty' not found.

Type X to quit or <RETURN> to proceed,
or enter new name. (Default extension: sty)

Enter file name:
! Emergency stop.
<read *>

l.14 \RequirePackage
                    {tabularx}^^M
!  ==> Fatal error occurred, no output PDF file produced!
Transcript written on refman.log.
make[3]: *** [Makefile:6: refman.pdf] Error 1
```

This tells me it's better to simply disable building the docs, which may require a patch?

**Comment by akesandgren** [comment]
Yeah will need a patch, fixing it up...

**Comment by akesandgren** [comment]
This should work for you @boegel

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
node3129.skitty.os - Linux RHEL 8.8, x86_64, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz, Python 3.6.8
See https://gist.github.com/boegel/c674914b2598f1ed6a877c8d7789b1bc for a full test report.

**Review by boegel — APPROVED** [review]
lgtm

**Comment by boegel** [comment]
Going in, thanks @akesandgren!

**Pull request merged**
