### PR TITLE
{devel}[GCCcore/9.3.0] sparsehash v2.0.4

### PR DESCRIPTION
**Pull request by mboisson**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by smoors** [comment]
Test report by @smoors
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
node374.hydra.os - Linux centos linux 7.7.1908, x86_64, Intel(R) Xeon(R) Gold 6148 CPU @ 2.40GHz (skylake_avx512), Python 2.7.5
See https://gist.github.com/ab308a08c49f4eb11d50646d86307a3f for a full test report.

**Comment by mboisson** [comment]
Don’t merge this yet. They just made a new release of sparsehash
  

  
  

  
  
>

**Comment by smoors** [comment]
Test report by @smoors
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
node253.hydra.os - Linux centos linux 7.7.1908, x86_64, Intel(R) Xeon(R) CPU E5-2650 v4 @ 2.20GHz (broadwell), Python 2.7.5
See https://gist.github.com/1b7543cf482956044c3ba1e2e61ccd46 for a full test report.

**Comment by smoors** [comment]
Going in, thanks @mboisson!

**Pull request merged**
