### PR TITLE
{bio}[GCCcore/5.4.0] BEDTools 2.26.0 

### PR DESCRIPTION
**Pull request by shahzebsiddiqui**

### CODE REVIEW

**Comment by boegel** [comment]
lgtm

**Comment by boegel** [comment]
Test report by @boegel
**FAILED**
Build succeeded for 0 out of 1 (1 easyconfigs in this PR)
node2577.golett.os - Linux centos linux 7.3.1611, Intel(R) Xeon(R) CPU E5-2680 v3 @ 2.50GHz, Python 2.7.5
See https://gist.github.com/2a38035f248103550439b23cdc7fbc93 for a full test report.

**Comment by boegel** [comment]
@shahzebsiddiqui hmm, missing dep on `zlib` (see failing test report)?

**Comment by boegel** [comment]
Test report by @boegel
**FAILED**
Build succeeded for 0 out of 1 (1 easyconfigs in this PR)
node2046.delcatty.os - Linux centos linux 7.3.1611, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.7.5
See https://gist.github.com/dd805b2e78476d0cb171c9b2ae2f53ea for a full test report.

**Comment by boegel** [comment]
@shahzebsiddiqui ping on missing dep?

**Comment by shahzebsiddiqui** [comment]
@boegel is this ok to be merged or do I need anything to fix something

**Comment by boegel** [comment]
@shahzebsiddiqui My test report shows you a dependency on `zlib` should be included?

**Comment by migueldiascosta** [comment]
@shahzebsiddiqui, this PR is being closed for the following reason(s): no activity for > 6 months, obsoleted by more recent PRs.
Please don't hesitate to reopen this PR or add a comment if you feel this contribution is still relevant.
For more information on our policy w.r.t. closing PRs, see https://easybuild.readthedocs.io/en/latest/Contributing.html#why-a-pull-request-may-be-closed-by-a-maintainer

**Pull request closed without merging**
