### PR TITLE
{chem}[foss,iomkl,intel/2018b] GPAW v1.4.0, GPAW-setups, libxc, libvdwxc

### PR DESCRIPTION
**Pull request by schiotz**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by Micket** [comment]
Just wanted to say thanks for picking up this PR, I have been kept very busy the past few weeks and just haven't had time to pick it up again.

**Comment by migueldiascosta** [comment]
Test report by @migueldiascosta
**SUCCESS**
Build succeeded for 11 out of 11 (11 easyconfigs in this PR)
grc-cluster1 - Linux centos 6.10, Intel(R) Xeon(R) CPU E5-2640 0 @ 2.50GHz, Python 2.7.14
See https://gist.github.com/edb22c522aa14af8d6484962af756467 for a full test report.

**Comment by schiotz** [comment]
@boegel 
In my opinion, this PR is now ready for review.  As mentioned above, GPAW is provided with libvdwxc support in the foss toolchain, but not in the iomkl and intel toolchains, due to incompatibility with the Intel MKL.  This may be solved in future versions of GPAW.  User who need libvdwxc (probably a minority) will have to live with the somewhat worse performance of the foss build.

Thanks to @Micket for laying the ground work for this in his PR.

CC: @mikstr @OleHolmNielsen

**Comment by schiotz** [comment]
@boegel Is there any hope of getting this one into the next EasyBuild release?

**Comment by schiotz** [comment]
@boegel It would be very valuable for us, if this PR could make it into the next EasyBuild release.

Best regards
Jakob

**Comment by migueldiascosta** [comment]
Test report by @migueldiascosta
**SUCCESS**
Build succeeded for 11 out of 11 (11 easyconfigs in this PR)
grc-cluster1 - Linux centos 6.10, Intel(R) Xeon(R) CPU E5-2640 0 @ 2.50GHz, Python 2.7.14
See https://gist.github.com/81937eda0671e63f4e3bd727050765b0 for a full test report.

**Comment by migueldiascosta** [comment]
for me, both serial and parallel tests pass for both `intel` and `foss` toolchains, as well as the serial tests for `iomkl`, but the parallel tests for `iomkl` often hang and/or fail, e.g. with

```gpaw.PoissonConvergenceError: Poisson solver did not converge in 1000 iterations!```

**Comment by schiotz** [comment]
@migueldiascosta 
Yes, we have also observed that the developer version of gpaw often crash in the extended self tests on our own cluster when built with the iomkl toolchain.  There are different crashes, but often it is a core dump in the openmpi libraries.  I am not 100% sure that the openmpi library is behaving well when compiled with the Intel compiler.

Obviously, it could also be some subtle bug in gpaw triggering this crash in openmpi, when built with the more agressively optimizing Intel compiler.  We have just decided locally to only build gpaw with the intel and foss toolchains.  

I think it would be wise to withdraw the easyconfigs for the iomkl toolchain, but will discuss it with my colleagues before doing it.

Thank you very much indeed for testing!

**Comment by schiotz** [comment]
@boegel @migueldiascosta I have withdrawn the iomkl easyconfigs, as GPAW does not work reliably when compiled with that toolchain.  If/when they find out why, I will add iomkl again for later releases of gpaw.  But now that Intel MPI can be used for free, the need for iomkl is less.

**Comment by migueldiascosta** [comment]
Going in, thanks @schiotz!

**Pull request merged**
