### PR TITLE
{tools}[system/system] EasyBuild v4.9.4

### PR DESCRIPTION
**Pull request by boegel**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
boegels-MBP-M1.local - Darwin UNKNOWN UNKNOWN, AArch64, Apple M1, Python 3.11.9
See https://gist.github.com/boegel/ecfc517c19d2b4183d70706bfa97046c for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
node4238.shinx.os - Linux RHEL 9.4, x86_64, AMD EPYC 9654 96-Core Processor (zen4), Python 3.9.18
See https://gist.github.com/boegel/475f639c0abbfe4c5708918fd35b30b7 for a full test report.

**Comment by boegel** [comment]
@boegelbot please test @ generoso

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
node3115.skitty.os - Linux RHEL 8.8, x86_64, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz, Python 3.6.8
See https://gist.github.com/boegel/994c9b444fca42a30d41262b68a3a262 for a full test report.

**Review by ocaisa — APPROVED** [review]
LGTM

**Pull request merged**
