### PR TITLE
{lib}[GCCcore/11.2.0] wpebackend-fdo v1.13.1

### PR DESCRIPTION
**Pull request by sassy-crick**
(created using `eb --new-pr`)
Requires:
- [x] PR #16088
- [x] PR #16085
- [x] PR #16092

### CODE REVIEW

**Comment by zao** [comment]
Test report by @zao
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
eb-u2204 - Linux Ubuntu 22.04, x86_64, AMD Ryzen 9 3900X 12-Core Processor, Python 3.10.4
See https://gist.github.com/6c04ab53ce2f4de96284e4863820f333 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
node3116.skitty.os - Linux RHEL 8.4, x86_64, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz (skylake_avx512), Python 3.6.8
See https://gist.github.com/a3677e19652e6bb7f012214cfcae8bcb for a full test report.

**Review by boegel — DISMISSED** [review]
lgtm

**Comment by boegel** [comment]
@boegelbot please test @ generoso

**Comment by sassy-crick** [comment]
Mh. The tests are not happy as in PR #16088 we opted for the `-egl` variant of `glew`. So that is biting us here again. I am happy to open another PR for the already closed  PR #16088 with `-osmesa` if that helps. That said, in light was we discussed before I am not sure if that is the right way forward. 
@boegel  Maybe something to be discussed in a user-meeting?

**Comment by boegel** [comment]
@sassy-crick We should update the test suite to also allow that the `egl` variant of `glew` is used as an (indirect) dependency of `wpebackend-fdo`, this is no surprise.

**Comment by boegel** [comment]
@boegelbot please test @ jsc-zen2

**Review by boegel — APPROVED** [review]

**Comment by boegel** [comment]
Going in, thanks @sassy-crick!

**Pull request merged**
