### PR TITLE
{data}[GCCcore/11.3.0] bsddb3 v6.2.9 w/ Python 3.10.4

### PR DESCRIPTION
**Pull request by akesandgren**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by akesandgren** [comment]
Test report by @akesandgren
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
b-an02.hpc2n.umu.se - Linux Ubuntu 20.04, x86_64, Intel(R) Xeon(R) CPU E5-2690 v4 @ 2.60GHz, Python 3.8.10
See https://gist.github.com/2762009967d305aa2319ac11813b14b1 for a full test report.

**Comment by branfosj** [comment]
@boegelbot please test @ jsc-zen2

**Comment by branfosj** [comment]
@boegelbot please test @ generoso

**Comment by branfosj** [comment]
I've reported the missing test report problem in https://github.com/easybuilders/easybuild-framework/issues/4102

At least I am guessing that the bot reports are lost for the same reason mine are - i.e. that there are missing OS dependencies.

**Comment by branfosj** [comment]
Test report by @branfosj
**FAILED**
Failed during parsing of the easyconfigs, so no ecs were built (1 easyconfigs in total)
bear-pg0105u36b.bear.cluster - Linux RHEL 8.6, x86_64, Intel(R) Xeon(R) Platinum 8360Y CPU @ 2.40GHz (icelake), Python 3.6.8
See https://gist.github.com/5ef7bd63945e075e350babc079899301 for a full test report.

**Comment by akesandgren** [comment]
@branfosj @boegel Can this move forward or does it need to be held back?

**Comment by branfosj** [comment]
> @branfosj @boegel Can this move forward or does it need to be held back?

Niether myself or boegelbot can build this, as we do not have the required OS dep. Is there an alternative, either to `bsddb3` or to using an OS dep?

**Comment by akesandgren** [comment]
No, EMAN2 needs the bsddb3 python bindings.

**Comment by branfosj** [comment]
#16533 has `bsddb3` with a suitable DB version as a component (instead of OS dep).

**Comment by akesandgren** [comment]
Ah, couldn't find it when I looked for it...

Closing this one then.

**Comment by branfosj** [comment]
Test report by @branfosj
**FAILED**
Failed during parsing of the easyconfigs, so no ecs were built (1 easyconfigs in total)
bear-pg0105u03a.bear.cluster - Linux RHEL 8.6, x86_64, Intel(R) Xeon(R) Platinum 8360Y CPU @ 2.40GHz (icelake), Python 3.6.8
See https://gist.github.com/cad754f8dbdff47c7e0c346e92d6a25f for a full test report.

**Pull request closed without merging**
