### PR TITLE
{lang}[GCCcore/8.2.0] Python v2.7.15 (WIP)

### PR DESCRIPTION
**Pull request by boegel**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by boegel** [comment]
@vanzod @Micket As discussed during the conf call: which additional Python packages should be consider including as well?

`wheel` is already there, I added `pytest` already myself.

I guess `Jinja2` (+ deps) is a good candidate. Anything else?

**Comment by Micket** [comment]
Maybe
* Pylint
* psutil, psrecord
* lxml
* Sphinx 

There are also lots deps from various bundles that could be included as well
* ASE deps: MarkupSafe, Jinja2, Wekzeug, Click, itsdangerous, Flask
* Tensorflow deps: protobuf-python, absl-py, astor, gast, grpcio, Markdown, termcolor, Werkzeug
* Sphinx deps (if we don't include all of sphinx): packaging, MarkupSafe, Pygments, imagesize, Docutils, Jinja2, snowballstemmer, Babel,  typing
pyparsing, Cheetah

**Comment by boegel** [comment]
@Micket I'd only include additional extensions if they're common dependencies for multiple other easyconfigs (`Jinja2` certainly fits, `Click`).
`Sphinx` also makes sense, I guess `pylint` does too (although it's not a common dep).

Not sure about `psutil` & `psrecord`, any reason you'd include those?

`lxml` implies also including `libxml2` and `libxslt` as dependencies.

Not a big fan of including `Flask` and all required packages (since it's a framework for webapps).

Most of the others you mention are only relevant for one or a handful at best of applications?

You also mentioned `pkgconfig` (the Python packages), that should also be included?

**Comment by Micket** [comment]
@boegel Yeah I just looked at some packages that were used by several other bundles. psutil was included in a 9 bundles (with recent easyconfigs). psrecord wasn't (i incorrectly thought it was).
I was basically just `grep foo -R` in the easyconfigs tree to see if there was multiple matches.

I suppose pkgconfig is unnecessary, as it's "just" used during configurations, additional pythonpaths won't matter. 

I don't really have any strong feelings about this, but, at least if it doesn't bring any additional deps, why not?

**Comment by boegel** [comment]
One more to definitely include: `future`.

**Comment by Micket** [comment]
Test report by @Micket
**FAILED**
Build succeeded for 2 out of 4 (4 easyconfigs in this PR)
hebbe-s1.int.private - Linux centos 6.10, Intel(R) Xeon(R) CPU E5-2650 v3 @ 2.30GHz, Python 2.7.14
See https://gist.github.com/1c2ad023901dd177c4402900e90fee9c for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 4 out of 4 (4 easyconfigs in this PR)
node3140.skitty.os - Linux centos linux 7.6.1810, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz, Python 2.7.5
See https://gist.github.com/17b1b9e8cc9560d448e150041d84fe3d for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 4 out of 4 (4 easyconfigs in this PR)
node2523.golett.os - Linux centos linux 7.6.1810, Intel(R) Xeon(R) CPU E5-2680 v3 @ 2.50GHz, Python 2.7.5
See https://gist.github.com/6d8e1f6e8ef3b19385dab922ae1ab978 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 4 out of 4 (4 easyconfigs in this PR)
node2044.delcatty.os - Linux centos linux 7.6.1810, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.7.5
See https://gist.github.com/aa4318e68182428629c3efeae139860c for a full test report.

**Comment by akesandgren** [comment]
Test report by @akesandgren
**SUCCESS**
Build succeeded for 6 out of 6 (4 easyconfigs in this PR)
b-an03.hpc2n.umu.se - Linux ubuntu 16.04, Intel(R) Xeon(R) CPU E5-2690 v4 @ 2.60GHz, Python 2.7.12
See https://gist.github.com/44c20c13a1e8b58facf73f1db5bc1ba5 for a full test report.

**Comment by verdurin** [comment]
Test report by @verdurin
**FAILED**
Build succeeded for 4 out of 8 (4 easyconfigs in this PR)
rescomp2 - Linux centos linux 7.3.1611, Intel(R) Xeon(R) Gold 6126 CPU @ 2.60GHz, Python 2.7.5
See https://gist.github.com/daf2a3e791aee69b3a4666070d34c11d for a full test report.

**Comment by Micket** [comment]
Test report by @Micket
**SUCCESS**
Build succeeded for 4 out of 4 (4 easyconfigs in this PR)
vera-c1 - Linux centos linux 7.6.1810, Intel Xeon Processor (Skylake), Python 2.7.5
See https://gist.github.com/c90ee72e49b2c6d999302da3cb5095c5 for a full test report.

**Comment by boegel** [comment]
@Micket Forgot `--robot` with first attempt?

@verdurin Can you explain this issue?

```
Failed to create directory /dev/shm/ncurses/6.1/GCCcore-8.2.0: [Errno 13] Permission denied: '/dev/shm/ncurses/6.1/GCCcore-8.2.0'
```

**Comment by smoors** [comment]
Test report by @smoors
**FAILED**
Build succeeded for 5 out of 8 (4 easyconfigs in this PR)
nic400 - Linux centos linux 7.5.1804, Intel(R) Xeon(R) Gold 6148 CPU @ 2.40GHz, Python 2.7.5
See https://gist.github.com/ae065f280d21448552a47b050f0c48a5 for a full test report.

**Comment by smoors** [comment]
Test report by @smoors
**SUCCESS**
Build succeeded for 4 out of 4 (4 easyconfigs in this PR)
nic425 - Linux centos linux 7.5.1804, Intel(R) Xeon(R) Gold 6148 CPU @ 2.40GHz, Python 2.7.5
See https://gist.github.com/a52d74463b72b5baa84a25e94e9ea54c for a full test report.

**Comment by verdurin** [comment]
Test report by @verdurin
**FAILED**
Build succeeded for 3 out of 4 (4 easyconfigs in this PR)
rescomp2 - Linux centos linux 7.3.1611, Intel(R) Xeon(R) Gold 6126 CPU @ 2.60GHz, Python 2.7.5
See https://gist.github.com/0a7e227548d2c512bbeae1f22ea13e38 for a full test report.

**Comment by smoors** [comment]
Test report by @smoors
**SUCCESS**
Build succeeded for 4 out of 4 (4 easyconfigs in this PR)
nic406 - Linux centos linux 7.5.1804, Intel(R) Xeon(R) Gold 6148 CPU @ 2.40GHz, Python 2.7.5
See https://gist.github.com/9df9338f17fbbaea05a664695d0101d8 for a full test report.

**Comment by smoors** [comment]
Test report by @smoors
**SUCCESS**
Build succeeded for 4 out of 4 (4 easyconfigs in this PR)
nic421 - Linux centos linux 7.5.1804, Intel(R) Xeon(R) Gold 6148 CPU @ 2.40GHz, Python 2.7.5
See https://gist.github.com/e71cbe0e1ad40ff0c19ff336ad0f483b for a full test report.

**Comment by smoors** [comment]
Test report by @smoors
**SUCCESS**
Build succeeded for 4 out of 4 (4 easyconfigs in this PR)
nic26 - Linux centos linux 7.5.1804, Intel(R) Xeon(R) Gold 6148 CPU @ 2.40GHz, Python 2.7.5
See https://gist.github.com/c1753a6e6d1dc428356cb5b479b3616e for a full test report.

**Comment by boegel** [comment]
@verdurin Does this ring any bells for you?

```
== 2019-03-15 13:58:49,504 build_log.py:162 ERROR EasyBuild crashed with an error (at ?:124 in __init__): Sanity check failed: extensions sanity check failed for 2 extensions: bcrypt, paramiko
failing sanity check for 'bcrypt' extension: command "python -c "import bcrypt"" failed; output:
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/well/rescomp/eb/software/Python/2.7.15-GCCcore-8.2.0/lib/python2.7/site-packages/bcrypt/__init__.py", line 25, in <module>
    from . import _bcrypt
ImportError: /users/rescomp/adamh/.local/lib/python2.7/site-packages/_cffi_backend.so: undefined symbol: PyUnicodeUCS2_FromUnicode, 
```

**Comment by smoors** [comment]
Test report by @smoors
**SUCCESS**
Build succeeded for 4 out of 4 (4 easyconfigs in this PR)
nic75 - Linux centos linux 7.5.1804, Intel(R) Xeon(R) CPU E5-2680 v4 @ 2.40GHz, Python 2.7.5
See https://gist.github.com/bc0cfc8372479a47697649fe0d0f238d for a full test report.

**Comment by smoors** [comment]
Test report by @smoors
**SUCCESS**
Build succeeded for 4 out of 4 (4 easyconfigs in this PR)
nic151 - Linux centos linux 7.5.1804, Intel(R) Xeon(R) CPU E5-2680 v2 @ 2.80GHz, Python 2.7.5
See https://gist.github.com/ff114fd453eeccd0362554eab941da6a for a full test report.

**Comment by verdurin** [comment]
Test report by @verdurin
**SUCCESS**
Build succeeded for 1 out of 1 (4 easyconfigs in this PR)
rescomp2 - Linux centos linux 7.3.1611, Intel(R) Xeon(R) Gold 6126 CPU @ 2.60GHz, Python 2.7.5
See https://gist.github.com/83bd8b9bb02a9441f2beb03884534260 for a full test report.

**Comment by verdurin** [comment]
> @verdurin Does this ring any bells for you?
> 
> ```
> == 2019-03-15 13:58:49,504 build_log.py:162 ERROR EasyBuild crashed with an error (at ?:124 in __init__): Sanity check failed: extensions sanity check failed for 2 extensions: bcrypt, paramiko
> failing sanity check for 'bcrypt' extension: command "python -c "import bcrypt"" failed; output:
> Traceback (most recent call last):
>   File "<string>", line 1, in <module>
>   File "/well/rescomp/eb/software/Python/2.7.15-GCCcore-8.2.0/lib/python2.7/site-packages/bcrypt/__init__.py", line 25, in <module>
>     from . import _bcrypt
> ImportError: /users/rescomp/adamh/.local/lib/python2.7/site-packages/_cffi_backend.so: undefined symbol: PyUnicodeUCS2_FromUnicode, 
> ```

 A local anomaly, now fixed.

**Comment by vanzod** [comment]
Test report by @vanzod
**SUCCESS**
Build succeeded for 6 out of 6 (4 easyconfigs in this PR)
cermis - Linux debian 9.8, Intel(R) Xeon(R) CPU           X5670  @ 2.93GHz, Python 2.7.13
See https://gist.github.com/ef45f75961aebc1be9e1ebbda0eb3c65 for a full test report.

**Comment by vanzod** [comment]
Going in, thanks @boegel!

**Comment by migueldiascosta** [comment]
Test report by @migueldiascosta
**SUCCESS**
Build succeeded for 4 out of 4 (4 easyconfigs in this PR)
grc-cluster1 - Linux centos 6.10, Intel(R) Xeon(R) CPU E5-2640 0 @ 2.50GHz, Python 2.7.14
See https://gist.github.com/3259ca2d26f27d1bda2f926bedc6961b for a full test report.

**Pull request merged**
