### PR TITLE
{bio}[GCCcore/11.2.0] PAML v4.9j

### PR DESCRIPTION
**Pull request by zemu-unile**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by zemu-unile** [comment]
Test report by @zemu-unile
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
login01.sc.uni-leipzig.de - Linux centos linux 7.9.2009, x86_64, AMD EPYC 7551P 32-Core Processor, 1 x NVIDIA NVIDIA GeForce RTX 2080 Ti, 495.29.05, 1 x NVIDIA Tesla V100-PCIE-32GB, 495.29.05, Python 3.6.8
See https://gist.github.com/a53d423b570a5d51557fbe1b38cb08f9 for a full test report.

**Comment by smoors** [comment]
@boegelbot: please test @ generoso

**Comment by smoors** [comment]
Test report by @smoors
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
node301.hydra.os - Linux centos linux 7.9.2009, x86_64, Intel(R) Xeon(R) Gold 6148 CPU @ 2.40GHz (skylake_avx512), Python 2.7.5
See https://gist.github.com/7078a700f931c737742582fa14b21e62 for a full test report.

**Review by smoors — APPROVED** [review]
lgtm

**Comment by smoors** [comment]
Going in, thanks @zemu-unile!

**Pull request merged**
