### PR TITLE
bump UCX to 1.15.0 and PMIx to 4.2.6 in OpenMPI-4.1.6-GCC-13.2.0.eb and impi-2021.10.0-intel-compilers-2023.2.1.eb

### PR DESCRIPTION
**Pull request by SebastianAchilles**
(created using `eb --new-pr`)

Note: UCX 1.15.0-rc4 was introduced in https://github.com/easybuilders/easybuild-easyconfigs/pull/18710, changed to 1.14.1 in https://github.com/easybuilders/easybuild-easyconfigs/pull/18877 and now in this PR updated to UCX 1.15.0.

The source file of UCX 1.15.0-rc4 has the same filename as UCX 1.15.0: `ucx-1.15.0.tar.gz`. That means we need to use `--force-download` on generoso and jsc-zen2

### CODE REVIEW

**Comment by SebastianAchilles** [comment]
@boegelbot please test @ jsc-zen2
EB_ARGS="--force-download"

**Comment by SebastianAchilles** [comment]
@boegelbot please test @ generoso
EB_ARGS="--force-download"

**Comment by SebastianAchilles** [comment]
@boegelbot please test @ jsc-zen2

**Comment by SebastianAchilles** [comment]
Test report by @sebastianachilles
**SUCCESS**
Build succeeded for 5 out of 5 (5 easyconfigs in total)
zen2-ubuntu-2304 - Linux Ubuntu 23.04 (Lunar Lobster), x86_64, AMD EPYC 7452 32-Core Processor (zen2), Python 3.11.2
See https://gist.github.com/SebastianAchilles/6aca149c0a6d72690d7759c7d357337e for a full test report.

**Comment by SebastianAchilles** [comment]
Test report by @sebastianachilles
**SUCCESS**
Build succeeded for 5 out of 5 (5 easyconfigs in total)
bwd-rockylinux-92 - Linux Rocky Linux 9.2 (Blue Onyx), x86_64, Intel(R) Core(TM) i7-6900K CPU @ 3.20GHz (broadwell), Python 3.9.16
See https://gist.github.com/SebastianAchilles/9c5ee77e91199c7a9433c565f3a1de58 for a full test report.

**Comment by SebastianAchilles** [comment]
Test report by @sebastianachilles
**SUCCESS**
Build succeeded for 5 out of 5 (5 easyconfigs in total)
skl-centos-79 - Linux CentOS Linux 7.9.2009, x86_64, Intel(R) Core(TM) i7-8700 CPU @ 3.20GHz (skylake), Python 3.6.8
See https://gist.github.com/SebastianAchilles/a19c2d30df76f6964f9517775a515c36 for a full test report.

**Review by Micket — APPROVED** [review]
lgtm

**Comment by Micket** [comment]
Test report by @Micket
**SUCCESS**
Build succeeded for 5 out of 5 (5 easyconfigs in total)
alvis-c1 - Linux Rocky Linux 8.7, x86_64, Intel Xeon Processor (Skylake), Python 3.6.8
See https://gist.github.com/Micket/044a8751da5a3a329ffded80d56b46ba for a full test report.

**Comment by Micket** [comment]
Going in, thanks @SebastianAchilles!

**Pull request merged**
