### PR TITLE
use new checksum for source tarball of SIONlib 1.7.7

### PR DESCRIPTION
**Pull request by bedroge**
Fixes https://github.com/easybuilders/easybuild-easyconfigs/issues/21747.

### CODE REVIEW

**Comment by bedroge** [comment]
@boegelbot please test @ generoso

**Comment by bedroge** [comment]
@boegelbot please test @ generoso
EB_ARGS="--force-download"

**Comment by bedroge** [comment]
@boegelbot please test @ jsc-zen3
EB_ARGS="--force-download"

**Review by branfosj — APPROVED** [review]

**Comment by branfosj** [comment]
@boegelbot please test @ jsc-zen3

**Comment by branfosj** [comment]
Going in, thanks @bedroge!

**Pull request merged**
