### PR TITLE
{tools}[GCCcore/10.3.0] Subversion v1.14.1

### PR DESCRIPTION
**Pull request by robert-mijakovic**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by verdurin** [comment]
@robert-mijakovic Looks like it needs `SCons` too?

**Comment by robert-mijakovic** [comment]
@verdurin Right, I have just added it.

**Comment by robert-mijakovic** [comment]
@boegelbot please test @ generoso

**Comment by SebastianAchilles** [comment]
Test report by @sebastianachilles
**SUCCESS**
Build succeeded for 6 out of 6 (6 easyconfigs in total)
centos8-eb - Linux centos linux 8.3.2011, x86_64, Intel(R) Core(TM) i7-8700 CPU @ 3.20GHz (skylake), Python 3.6.8
See https://gist.github.com/c7c3bb6e8081d548ed1e066a071d9a66 for a full test report.

**Comment by robert-mijakovic** [comment]
@SebastianAchilles I guess this one is ready to go in.

**Comment by SebastianAchilles** [comment]
@robert-mijakovic This looks good to go in. But I just noticed that the easyconfigs have already been added in https://github.com/easybuilders/easybuild-easyconfigs/pull/13311 
My apologies for overlooking this PR. I will close this PR.

**Pull request closed without merging**
