### PR TITLE
Update hwloc easyconfigs with libxml2 and libpciaccess dependencies.

### PR DESCRIPTION
**Pull request by akesandgren**
(created using `eb --new-pr`)
Update latest hwloc easyconfigs with libxml2 and libpciaccess dependencies and explicitly disable some configure options

edit: fix for #6257

### CODE REVIEW

**Comment by akesandgren** [comment]
Test report by @akesandgren
**FAILED**
Build succeeded for 9 out of 10 (10 easyconfigs in this PR)
b-cn1522.hpc2n.umu.se - Linux ubuntu 16.04, Intel(R) Xeon(R) Gold 6132 CPU @ 2.60GHz, Python 2.7.12
See https://gist.github.com/4e5b4d4429d5406a75d6c1f9f04948c8 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 10 out of 10 (10 easyconfigs in this PR)
gligar03.gligar.os - Linux centos linux 7.4.1708, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.7.5
See https://gist.github.com/8d6cdacd799941906c8c3675c7f121f1 for a full test report.

**Comment by akesandgren** [comment]
Test report by @akesandgren
**SUCCESS**
Build succeeded for 10 out of 10 (10 easyconfigs in this PR)
b-cn1522.hpc2n.umu.se - Linux ubuntu 16.04, Intel(R) Xeon(R) Gold 6132 CPU @ 2.60GHz, Python 2.7.12
See https://gist.github.com/64df06fff15e9fecfa1807c5a2dd07c5 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 10 out of 10 (10 easyconfigs in this PR)
node2603.swalot.os - Linux centos linux 7.4.1708, Intel(R) Xeon(R) CPU E5-2660 v3 @ 2.60GHz, Python 2.7.5
See https://gist.github.com/b545203b4c52a98476bf861918b78fc0 for a full test report.

**Comment by boegel** [comment]
Going in, thanks @akesandgren!

**Comment by akesandgren** [comment]
In the case of hwloc's libxml2 and libpciaccess dependencies, you should only need to rebuild hwloc itself.

**Pull request merged**
