### PR TITLE
{vis}[GCCcore/8.3.0] freetype v2.10.1

### PR DESCRIPTION
**Pull request by Micket**
(created using `eb --new-pr`)

depends on ~#8623~ and ~#8615~

### CODE REVIEW

**Comment by Micket** [comment]
Test report by @Micket
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
vera-c1 - Linux centos linux 7.6.1810, Intel Xeon Processor (Skylake), Python 2.7.5
See https://gist.github.com/5bb34cd3fd51216ba7fd6a0a7d27b5d8 for a full test report.

**Comment by vanzod** [comment]
Re-trigger Travis after dependencies merge

**Comment by vanzod** [comment]
Re-trigger Travis after dependencies merge

**Comment by vanzod** [comment]
Test report by @vanzod
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
cermis - Linux debian 9.9, Intel(R) Xeon(R) CPU           X5670  @ 2.93GHz, Python 2.7.13
See https://gist.github.com/dd4b189754b00a33e4b462f0cb37e8fe for a full test report.

**Comment by vanzod** [comment]
Going in, thanks @Micket!

**Pull request merged**
