### PR TITLE
{compiler}[GCCcore/12.3.0] LLVM v16.0.6

### PR DESCRIPTION
**Pull request by maxim-masterov**
(created using `eb --new-pr`)

requires:
* https://github.com/easybuilders/easybuild-easyblocks/pull/2970

### CODE REVIEW

**Comment by surak** [comment]
```
-- Performing Test HAS_WERROR_GLOBAL_CTORS
-- Performing Test HAS_WERROR_GLOBAL_CTORS - Failed
-- Looking for __x86_64__
-- Looking for __x86_64__ - found
-- Found Git: /usr/bin/git (found version "2.31.1") 
-- Targeting X86
CMake Error at CMakeLists.txt:1171 (add_subdirectory):
  add_subdirectory given source
  "/dev/shm/strube1/juwelsbooster/LLVM/16.0.6/GCCcore-12.3.0/llvm-16.0.6.src/../third-party/unittest"
  which is not an existing directory.
  ```
  
  Does it need a new easyconfig for LLVM? I see that the only difference from the previous one is the removal of the third-party package...

**Comment by maxim-masterov** [comment]
@surak yes, it needs a new easyblock: https://github.com/easybuilders/easybuild-easyblocks/pull/2970

**Comment by SebastianAchilles** [comment]
Test report by @sebastianachilles
Using easyblocks from PR(s) https://github.com/easybuilders/easybuild-easyblocks/pull/2970
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
bwd-rockylinux-92 - Linux Rocky Linux 9.2 (Blue Onyx), x86_64, Intel(R) Core(TM) i7-6900K CPU @ 3.20GHz (broadwell), 2 x NVIDIA NVIDIA GeForce GTX 1060 6GB, 535.54.03, Python 3.9.16
See https://gist.github.com/SebastianAchilles/64cb07ba16ccac456a909cb61fb27558 for a full test report.

**Review by casparvl — COMMENTED** [review]
Lgtm, but is awaiting the merge of https://github.com/easybuilders/easybuild-easyblocks/pull/2970

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
node3142.skitty.os - Linux RHEL 8.6, x86_64, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz (skylake_avx512), Python 3.6.8
See https://gist.github.com/boegel/c486e56c00fbba94aa65595a1fdcbe04 for a full test report.

**Review by boegel — APPROVED** [review]
lgtm

**Comment by boegel** [comment]
Going in, thanks @maxim-masterov!

**Pull request merged**
