### PR TITLE
add missing Python deps and packages in PSI4 1.7

### PR DESCRIPTION
**Pull request by branfosj**
(created using `eb --new-pr`)

noticed while testing in https://github.com/easybuilders/easybuild-easyblocks/pull/3214

### CODE REVIEW

**Comment by branfosj** [comment]
Test report by @branfosj
Using easyblocks from PR(s) https://github.com/easybuilders/easybuild-easyblocks/pull/3214
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
bear-pg0105u03a - Linux RHEL 8.6, x86_64, Intel(R) Xeon(R) Platinum 8360Y CPU @ 2.40GHz (icelake), Python 3.6.8
See https://gist.github.com/branfosj/dd1b3bb9e9254c6a5f042084a1371425 for a full test report.

**Comment by branfosj** [comment]
@boegelbot please test @ jsc-zen3
EB_BRANCH=5.0.x
EB_ARGS="--include-easyblocks-from-pr 3214"

**Comment by boegel** [comment]
@boegelbot please test @ generoso

**Comment by boegel** [comment]
Going in, thanks @branfosj!

**Pull request merged**
