### PR TITLE
{bio}[foss/2019a] kallisto v0.45.1

### PR DESCRIPTION
**Pull request by lexming**
Minor update of `kallisto` to version 0.45.1 with no particular changes.

### CODE REVIEW

**Comment by migueldiascosta** [comment]
Test report by @migueldiascosta
**SUCCESS**
Build succeeded for 0 out of 0 (1 easyconfigs in this PR)
sms - Linux centos linux 7.6.1810, AMD EPYC 7601 32-Core Processor, Python 2.7.5
See https://gist.github.com/e31b8d296d6d5326f594e41b13f5552c for a full test report.

**Comment by migueldiascosta** [comment]
@lexming you may want to have a look at https://easybuild.readthedocs.io/en/latest/Integration_with_GitHub.html, namely `--new-pr` (and `--update-pr`) and `--upload-test-report`

**Comment by migueldiascosta** [comment]
Test report by @migueldiascosta
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
sms - Linux centos linux 7.6.1810, AMD EPYC 7601 32-Core Processor, Python 2.7.5
See https://gist.github.com/8c07c123fa781f01cd363442c0613c95 for a full test report.

**Comment by migueldiascosta** [comment]
Going in, thanks @lexming!

**Comment by lexming** [comment]
> @lexming you may want to have a look at https://easybuild.readthedocs.io/en/latest/Integration_with_GitHub.html, namely `--new-pr` (and `--update-pr`) and `--upload-test-report`

That's very handy, I need to set that up at some point :smiley:

**Pull request merged**
