### PR TITLE
{devel}[system/system] VSCode v1.85.0

### PR DESCRIPTION
**Pull request by laraPPr**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by laraPPr** [comment]
Test report by @laraPPr
**FAILED**
Build succeeded for 0 out of 1 (1 easyconfigs in total)
node3526.doduo.os - Linux RHEL 8.8 (Ootpa), x86_64, AMD EPYC 7552 48-Core Processor, Python 3.11.3
See https://gist.github.com/laraPPr/cac4a55ca40f92f9a32d5bd6646c7577 for a full test report.

**Comment by laraPPr** [comment]
Test report by @laraPPr
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
node3526.doduo.os - Linux RHEL 8.8 (Ootpa), x86_64, AMD EPYC 7552 48-Core Processor, Python 3.11.3
See https://gist.github.com/laraPPr/8e548ac0a02e5320ccb1c32550232bf1 for a full test report.

**Comment by verdurin** [comment]
Test report by @verdurin
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
easybuild-c7.novalocal - Linux CentOS Linux 7.9.2009, x86_64, Intel Xeon Processor (Skylake, IBRS), Python 3.6.8
See https://gist.github.com/verdurin/ab288b860a3e7278c5b0cde67041ac5a for a full test report.

**Comment by verdurin** [comment]
@laraPPr thanks for the contribution. It's complaining about the checksum on `generoso`, though it was fine on my local test build.

**Comment by laraPPr** [comment]
Test report by @laraPPr
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
node3617.doduo.os - Linux RHEL 8.8 (Ootpa), x86_64, AMD EPYC 7552 48-Core Processor, Python 3.11.3
See https://gist.github.com/laraPPr/957c628ffe3e6cf1c878b1fca8b691e0 for a full test report.

**Comment by laraPPr** [comment]
Triggered another installation because I had forgotten to add the checksum when I uploaded the first test-report. But that one now also passed. All the checks also pass. So do not really know what to make of it.

**Comment by laraPPr** [comment]
@boegelbot please test @ generoso

**Comment by laraPPr** [comment]
@verdurin I got it fixed, something weird happened with the sources that I downloaded locally.

**Comment by verdurin** [comment]
Test report by @verdurin
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
easybuild-c7.novalocal - Linux CentOS Linux 7.9.2009, x86_64, Intel Xeon Processor (Skylake, IBRS), Python 3.6.8
See https://gist.github.com/verdurin/59c7c8baba050d17bb2dff1dbdcfb888 for a full test report.

**Comment by casparvl** [comment]
@boegelbot please test @ jsc-zen2

**Comment by casparvl** [comment]
@boegelbot please test @ generoso

**Comment by casparvl** [comment]
Test report by @casparvl
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
tcn1.local.snellius.surf.nl - Linux RHEL 8.6, x86_64, AMD EPYC 7H12 64-Core Processor, Python 3.6.8
See https://gist.github.com/casparvl/89fb3b4dffc67dea769b1c922cbc9311 for a full test report.

**Review by casparvl — APPROVED** [review]
Lgtm!

**Comment by casparvl** [comment]
Going in, thanks @laraPPr!

**Pull request merged**
