### PR TITLE
{bio}[GCCcore/12.3.0,foss/2023a] WhatsHap v2.2, pyfaidx v0.8.1.1

### PR DESCRIPTION
**Pull request by PetrKralCZ**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by PetrKralCZ** [comment]
@boegelbot please test @ generoso

**Review by boegel — APPROVED** [review]
lgtm

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in total)
node3120.skitty.os - Linux RHEL 8.8, x86_64, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz, Python 3.6.8
See https://gist.github.com/boegel/cc93d5b1e8761a3166a30ee07830c587 for a full test report.

**Comment by boegel** [comment]
@boegelbot please test @ jsc-zen3

**Pull request merged**
