### PR TITLE
promote foss/2021.04 to foss/2021a

### PR DESCRIPTION
**Pull request by boegel**

### CODE REVIEW

**Comment by boegel** [comment]
@boegelbot please test @ generoso
CORE_CNT=16

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 8 out of 8 (8 easyconfigs in total)
node2617.swalot.os - Linux centos linux 7.9.2009, x86_64, Intel(R) Xeon(R) CPU E5-2660 v3 @ 2.60GHz (haswell), Python 3.6.8
See https://gist.github.com/b84f8d0a34c60305763c4f297be31cc3 for a full test report.

**Review by branfosj — APPROVED** [review]
lgtm

**Comment by verdurin** [comment]
Going in, thanks @boegel!

**Pull request merged**
