### PR TITLE
{bio}[intel/2017a] KmerGenie v1.7044

### PR DESCRIPTION
**Pull request by smoors**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by verdurin** [comment]
@smoors trying to run a test build of this and having problems with `Jasper`. Once those are fixed, I'll come back to it.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
node2125.delcatty.os - Linux centos linux 7.4.1708, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.7.5
See https://gist.github.com/07ca267eca769f4cb60a6b6f14a4ab05 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
node2478.golett.os - Linux centos linux 7.4.1708, Intel(R) Xeon(R) CPU E5-2680 v3 @ 2.50GHz, Python 2.7.5
See https://gist.github.com/1fd88549c8e42dc5f3dd34009ae20a3d for a full test report.

**Comment by boegel** [comment]
Going in, thanks @smoors!

**Pull request merged**
