### PR TITLE
{lib,vis}[GCCcore/12.3.0] exiv2 v0.28.0, inih v57

### PR DESCRIPTION
**Pull request by surak**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by surak** [comment]
The latest exiv depends on inih and brotli.

**Comment by branfosj** [comment]
@boegelbot please test @ generoso

**Review by branfosj — CHANGES_REQUESTED** [review]

**Review by branfosj — APPROVED** [review]

**Comment by branfosj** [comment]
@boegelbot please test @ generoso

**Comment by branfosj** [comment]
Test report by @branfosj
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in total)
bear-pg0105u03a.bear.cluster - Linux RHEL 8.6, x86_64, Intel(R) Xeon(R) Platinum 8360Y CPU @ 2.40GHz (icelake), Python 3.6.8
See https://gist.github.com/branfosj/0b085388e3f1d6cff135beaee47f6697 for a full test report.

**Comment by branfosj** [comment]
Going in, thanks @surak!

**Pull request merged**
