### PR TITLE
{vis}[fosscuda/2019b] matplotlib v3.1.1 w/ Python 3.7.4

### PR DESCRIPTION
**Pull request by branfosj**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by branfosj** [comment]
Test report by @branfosj
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
bear-pg0305u11a.bear.cluster - Linux RHEL 7.6, 8335-GTX, Python 2.7.5
See https://gist.github.com/9ac12f458dba7d873493ca8414377d20 for a full test report.

**Comment by branfosj** [comment]
Test report by @branfosj
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
bear-pg0210u18a.bear.cluster - Linux centos linux 7.7.1908, Intel(R) Xeon(R) CPU E5-2640 v4 @ 2.40GHz, Python 2.7.5
See https://gist.github.com/9e920d4e74689007c01811dd0f353e41 for a full test report.

**Comment by terjekv** [comment]
Test report by @terjekv
**FAILED**
Build succeeded for 0 out of 2 (1 easyconfigs in this PR)
ninhursaga.uio.no - Linux red hat enterprise linux 8.1, Intel(R) Xeon(R) Silver 4216 CPU @ 2.10GHz, Python 3.6.8
See https://gist.github.com/1dced287ea3bffe725d5d0baca64f2e4 for a full test report.

**Comment by terjekv** [comment]
Test report by @terjekv
**SUCCESS**
Build succeeded for 2 out of 2 (1 easyconfigs in this PR)
ninhursaga.uio.no - Linux red hat enterprise linux 8.1, Intel(R) Xeon(R) Silver 4216 CPU @ 2.10GHz, Python 3.6.8
See https://gist.github.com/bfd78c9a95fd15e6f7790b77e1215d68 for a full test report.

**Comment by terjekv** [comment]
Test report by @terjekv
**SUCCESS**
Build succeeded for 0 out of 0 (1 easyconfigs in this PR)
ninhursaga.uio.no - Linux red hat enterprise linux 8.1, Intel(R) Xeon(R) Silver 4216 CPU @ 2.10GHz, Python 3.6.8
See https://gist.github.com/9af44b6c82911fb4fe6ecb4672760e89 for a full test report.

**Comment by migueldiascosta** [comment]
Test report by @migueldiascosta
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
generoso - Linux centos linux 7.6.1810, Intel(R) Xeon(R) CPU E5-2660 v4 @ 2.00GHz, Python 3.6.8
See https://gist.github.com/0bbf770cc044e9f262cab9e07b1e1903 for a full test report.

**Comment by migueldiascosta** [comment]
Going in, thanks @branfosj!

**Pull request merged**
