### PR TITLE
add dlm extension to R 4.2.1 + 4.2.2

### PR DESCRIPTION
**Pull request by boegel**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by boegel** [comment]
@boegelbot please test @ generoso
EB_ARGS="--skip"

**Comment by branfosj** [comment]
@boegelbot please test @ jsc-zen2
EB_ARGS="--skip"

**Review by branfosj — APPROVED** [review]

**Comment by branfosj** [comment]
Test report by @branfosj
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in total)
bear-pg0105u03a.bear.cluster - Linux RHEL 8.6, x86_64, Intel(R) Xeon(R) Platinum 8360Y CPU @ 2.40GHz (icelake), Python 3.6.8
See https://gist.github.com/branfosj/763752d7887513c68860ff24f40dd89c for a full test report.

**Comment by branfosj** [comment]
Going in, thanks @boegel!

**Pull request merged**
