### PR TITLE
{compiler}[system/system] Go v1.21.2

### PR DESCRIPTION
**Pull request by boegel**
(created using `eb --new-pr`)

### CODE REVIEW

**Review by branfosj — APPROVED** [review]

**Comment by branfosj** [comment]
@boegelbot please test @ generoso

**Comment by branfosj** [comment]
Test report by @branfosj
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
bear-pg0105u03a.bear.cluster - Linux RHEL 8.6, x86_64, Intel(R) Xeon(R) Platinum 8360Y CPU @ 2.40GHz (icelake), Python 3.6.8
See https://gist.github.com/branfosj/d72112a39fbc5fff91c2da67af5b2acd for a full test report.

**Comment by branfosj** [comment]
Checked `aarch64` checksum is correct with:
```
$ wget https://storage.googleapis.com/golang/go1.21.2.linux-arm64.tar.gz
$ sha256sum go1.21.2.linux-arm64.tar.gz 
23e208ca44a3cb46cd4308e48a27c714ddde9c8c34f2e4211dbca95b6d456554  go1.21.2.linux-arm64.tar.gz
```

**Comment by branfosj** [comment]
@boegelbot please test @ jsc-zen2

**Review by branfosj — APPROVED** [review]

**Comment by branfosj** [comment]
Going in, thanks @boegel!

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
fair-mastodon-c7g-4xlarge-0001 - Linux Rocky Linux 8.7, AArch64, ARM UNKNOWN (neoverse_n1), Python 3.6.8
See https://gist.github.com/boegel/8717de5a84e774de25dd97ddd2c3d0c2 for a full test report.

**Pull request merged**
