### PR TITLE
{system}[GCC/6.4.0-2.28] CUDA v9.1.85

### PR DESCRIPTION
**Pull request by froland**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by froland** [comment]
Test report by @froland
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
umons-froland-info-desktop.umons.ac.be - Linux fedora 27, AMD Phenom(tm) II X6 1090T Processor, Python 2.7.14
See https://gist.github.com/1f22e06d081ed346b5d464f67b3b96ed for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
gligar03.gligar.os - Linux centos linux 7.4.1708, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.7.5
See https://gist.github.com/d50fc00fe35095f895ebbdbd36cdd55a for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
node2436.golett.os - Linux centos linux 7.4.1708, Intel(R) Xeon(R) CPU E5-2680 v3 @ 2.50GHz, Python 2.7.5
See https://gist.github.com/3e0aee1562035158b7e1db9e8d594611 for a full test report.

**Comment by boegel** [comment]
Going in, thanks @froland!

**Pull request merged**
