### PR TITLE
{data}[foss/2022b] zarr v2.16.0 w/ Python 3.10.8

### PR DESCRIPTION
**Pull request by laraPPr**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by laraPPr** [comment]
Test report by @laraPPr
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
gligar07.gastly.os - Linux RHEL 8.6 (Ootpa), x86_64, AMD EPYC 7532 32-Core Processor (zen2), Python 3.10.8
See https://gist.github.com/laraPPr/55a65497d85ce5d4c517d86456eb40a6 for a full test report.

**Review by boegel — APPROVED** [review]
lgtm

**Comment by boegel** [comment]
@boegelbot please test @ generoso

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
node3115.skitty.os - Linux RHEL 8.6, x86_64, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz (skylake_avx512), Python 3.6.8
See https://gist.github.com/boegel/1896ef5b584b051920bbc46b5c153967 for a full test report.

**Comment by boegel** [comment]
Going in, thanks @laraPPr!

**Pull request merged**
