### PR TITLE
FLINT needs BLAS so move it up from GCC level

### PR DESCRIPTION
**Pull request by akesandgren**
(created using `eb --new-pr`)
FLINT depends on BLAS so it must be higher than GCC. It also depends on NTL.

### CODE REVIEW

**Comment by akesandgren** [comment]
Replaces #17867
This is part 1 of 2

**Comment by akesandgren** [comment]
@boegelbot Please test @ jsc-zen2

**Comment by akesandgren** [comment]
Checks failing due to FLINT@GCC level being removed while Arb and polymake still wants them.
This is taken care of in #17869

The end result is that this one will probably need to be force merged.

**Comment by akesandgren** [comment]
Test report by @akesandgren
**SUCCESS**
Build succeeded for 4 out of 4 (4 easyconfigs in total)
b-an02.hpc2n.umu.se - Linux Ubuntu 20.04, x86_64, Intel(R) Xeon(R) CPU E5-2690 v4 @ 2.60GHz, Python 3.8.10
See https://gist.github.com/akesandgren/3b93f92e64a9d9a4c94ed2d3c40f42d5 for a full test report.

**Comment by jfgrimm** [comment]
Test report by @jfgrimm
**SUCCESS**
Build succeeded for 5 out of 5 (4 easyconfigs in total)
node088.pri.viking.alces.network - Linux CentOS Linux 7.9.2009, x86_64, Intel(R) Xeon(R) Gold 6138 CPU @ 2.00GHz (skylake_avx512), Python 3.6.8
See https://gist.github.com/jfgrimm/16e48b7f59c617242b4b1de8e904e9c8 for a full test report.

**Comment by verdurin** [comment]
Test report by @verdurin
**SUCCESS**
Build succeeded for 4 out of 4 (4 easyconfigs in total)
easybuild-c7.novalocal - Linux CentOS Linux 7.9.2009, x86_64, Intel Xeon Processor (Skylake, IBRS), Python 3.6.8
See https://gist.github.com/verdurin/6ad8ba23d02d0ad35f28befac0ccb7af for a full test report.

**Comment by jfgrimm** [comment]
@boegelbot Please test @ generoso

**Review by jfgrimm — APPROVED** [review]
lgtm

**Comment by jfgrimm** [comment]
Going in, thanks @akesandgren!

**Pull request merged**
