### PR TITLE
{bio}[foss/2021b] pangolin v3.1.16 w/ Python 3.9.6 + pangoLEARN v2021-10-18 and v2021-11-25

### PR DESCRIPTION
**Pull request by sassy-crick**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by sassy-crick** [comment]
Requires:
- [ ] [Biopython](https://github.com/easybuilders/easybuild-easyconfigs/pull/14308)
- [ ] [Pysam](https://github.com/easybuilders/easybuild-easyconfigs/pull/14309)
- [ ] [snakemake](https://github.com/easybuilders/easybuild-easyconfigs/pull/14306)
- [ ] [UShER](https://github.com/easybuilders/easybuild-easyconfigs/pull/14305)
- [ ] [scikit-learn](https://github.com/easybuilders/easybuild-easyconfigs/pull/14307)
- [ ] [Kent_tools](https://github.com/easybuilders/easybuild-easyconfigs/pull/14300)

**Comment by sassy-crick** [comment]
In light of the recently found omikron-variant of Sars-CoV-2, `pangoLEARN` and `pango-designation` have been updated. In order to keep the current version for comparison, I suggest to use the version prefix of `pangoLEARN` as a unique handle. This way, if and when new variant will come along, a quick update can be undertaken without doing in-place replacing.

**Comment by migueldiascosta** [comment]
> In light of the recently found omikron-variant of Sars-CoV-2, `pangoLEARN` and `pango-designation` have been updated. In order to keep the current version for comparison, I suggest to use the version prefix of `pangoLEARN` as a unique handle. This way, if and when new variant will come along, a quick update can be undertaken without doing in-place replacing.

assuming the version of `pangoLEARN` is only relevant at runtime, couldn't it be a separate module, swapable after `pangolin` is loaded?

**Comment by boegel** [comment]
> > In light of the recently found omikron-variant of Sars-CoV-2, `pangoLEARN` and `pango-designation` have been updated. In order to keep the current version for comparison, I suggest to use the version prefix of `pangoLEARN` as a unique handle. This way, if and when new variant will come along, a quick update can be undertaken without doing in-place replacing.
> 
> assuming the version of `pangoLEARN` is only relevant at runtime, couldn't it be a separate module, swapable after `pangolin` is loaded?

It could be, but this approach makes sense to me too, I think.
In some sense, it's a statement that these particular versions of `pangoLEARN` and `pangolin` are compatible.
If there's only a `pangoLEARN` module, you're left wondering whether you can use that in combination with `pangolin` that was installed with an older `pangoLEARN`.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in total)
node3147.skitty.os - Linux centos linux 7.9.2009, x86_64, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz (skylake_avx512), Python 3.6.8
See https://gist.github.com/d3d38306d9ba983d9a12aab6c691b873 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in total)
node3507.doduo.os - Linux RHEL 8.2, x86_64, AMD EPYC 7552 48-Core Processor (zen2), Python 3.6.8
See https://gist.github.com/cfdd035ff22e6f84fad6dd5148c4bab4 for a full test report.

**Comment by boegel** [comment]
@boegelbot please test @ generoso

**Review by boegel — APPROVED** [review]
lgtm

**Comment by boegel** [comment]
Going in, thanks @sassy-crick!

**Pull request merged**
