### PR TITLE
{chem}[foss/2023a] CREST v3.0.2

### PR DESCRIPTION
**Pull request by WilleBell**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by WilleBell** [comment]
Test report by @WilleBell
**FAILED**
Build succeeded for 0 out of 1 (1 easyconfigs in total)
node600.hydra.os - Linux Rocky Linux 8.10, x86_64, AMD EPYC 9384X 32-Core Processor, Python 3.6.8
See https://gist.github.com/WilleBell/67c4de92dba52033179a6bd222431bd3 for a full test report.

**Comment by WilleBell** [comment]
Test report by @WilleBell
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
node601.hydra.os - Linux Rocky Linux 8.10, x86_64, AMD EPYC 9384X 32-Core Processor, Python 3.6.8
See https://gist.github.com/WilleBell/aeadd7ff773281b370f03e612b00c7c0 for a full test report.

**Review by kErica — APPROVED** [review]

**Comment by WilleBell** [comment]
This removes CREST-3.0pre-20240319-gfbf-2023a.eb because xtb 6.6.0 is no longer compatible (due to tblite) and the installation fails.

**Comment by smoors** [comment]
> This removes CREST-3.0pre-20240319-gfbf-2023a.eb

the problem is CREST downloads a new version of tblite during the build which is no longer compatible so CREST-3.0pre-20240319-gfbf-2023a.eb is broken. as this is a pre-release version, i think it's ok to remove it.

see also https://github.com/easybuilders/easybuild-easyconfigs/pull/21437

error:
```
/tmp/CREST/3.0pre-20240319/gfbf-2023a/crest-2719412edf8bb606cebdd4cd6bbb4cdbd249e1e5/src/calculator/tblite_api.F90:126:46:

  126 |       call new_gfn1_calculator(tbcalc,mctcmol)
      |                                              1
Error: Missing actual argument for argument error at (1)
```

**Comment by smoors** [comment]
@boegelbot: please test @ generoso

**Comment by smoors** [comment]
@boegelbot please test @ jsc-zen3

**Review by smoors — APPROVED** [review]
lgtm

**Comment by smoors** [comment]
Going in, thanks @WilleBell!

**Pull request merged**
