### PR TITLE
{lib}[GCCcore/8.3.0,foss/2019b] pyaml v19.12.0, scikit-optimize v0.7.4 w/ Python 2.7.16 + 3.7.4

### PR DESCRIPTION
**Pull request by lexming**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by lexming** [comment]
Test report by @lexming
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in this PR)
login2.cerberus.os - Linux centos linux 7.7.1908, Intel(R) Xeon(R) Gold 6126 CPU @ 2.60GHz, Python 2.7.5
See https://gist.github.com/39e56ea77c520c4d42d4cdd06107fe24 for a full test report.

**Comment by lexming** [comment]
@smoors good idea, I changed it to `pretty-yaml` following how it is written in their github project

**Comment by smoors** [comment]
Test report by @smoors
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in this PR)
node308.hydra.os - Linux centos linux 7.7.1908, Intel(R) Xeon(R) Gold 6148 CPU @ 2.40GHz, Python 2.7.5
See https://gist.github.com/62e76bf218862b8469876e12342790bf for a full test report.

**Comment by smoors** [comment]
Going in, thanks @lexming!

**Pull request merged**
