### PR TITLE
add patch for Bison 3.0.4 to fix installation on top of glibc 2.28

### PR DESCRIPTION
**Pull request by boegel**
cfr. #8501 & #8673

### CODE REVIEW

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
gligar05.gastly.os - Linux fedora 30, Intel(R) Xeon(R) Gold 6130 CPU @ 2.10GHz, Python 2.7.16
See https://gist.github.com/e8dd3e8d0dab3db57d4aed20a4f6505d for a full test report.

**Comment by vanzod** [comment]
Test report by @vanzod
**SUCCESS**
Build succeeded for 9 out of 9 (7 easyconfigs in this PR)
cermis - Linux debian 9.9, Intel(R) Xeon(R) CPU           X5670  @ 2.93GHz, Python 2.7.13
See https://gist.github.com/747332c7005098ea150daaf1619cf131 for a full test report.

**Comment by vanzod** [comment]
Going in, thanks @boegel!

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 32 out of 32 (32 easyconfigs in this PR)
node2036.delcatty.os - Linux centos linux 7.6.1810, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.7.5
See https://gist.github.com/e565953d44f0c21d94d9c9ec9ec7e54c for a full test report.

**Pull request merged**
