### PR TITLE
{data,devel,math}[foss/2017b] GDAL v2.2.3, GEOS v3.6.2, SWIG v3.0.12

### PR DESCRIPTION
**Pull request by boegel**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 3 out of 3 (3 easyconfigs in this PR)
node2597.golett.os - Linux centos linux 7.4.1708, Intel(R) Xeon(R) CPU E5-2680 v3 @ 2.50GHz, Python 2.7.5
See https://gist.github.com/629cbc8d158a863b64634f3fbf251a4b for a full test report.

**Comment by verdurin** [comment]
Test report by @verdurin
**FAILED**
Build succeeded for 0 out of 7 (3 easyconfigs in this PR)
dell.lan - Linux fedora 27, Intel(R) Core(TM) i7-4600U CPU @ 2.10GHz, Python 2.7.14
See https://gist.github.com/dd38293298b62c833c4af1a8a2af2cea for a full test report.

**Comment by boegel** [comment]
@verdurin Same issue with `Python` as in https://github.com/easybuilders/easybuild-easyconfigs/pull/5516#issuecomment-351313791.

Also, changed checksum for `Szip` 2.1.1? Is that a fresh download, or a very old one?

If I re-download `szip-2.1.1.tar.gz` I'm also seeing a changed checksum compared to previously (grrr....).

**Comment by boegel** [comment]
Looks like they uploaded a cleaned up version of the tarball, here's a comparison between previous `szip-2.1.1.tar.gz` and the current one:

```
$ diff -u szip-2.1.1.orig szip-2.1.1 | grep -A 1 '^diff'
diff --git a/szip-2.1.1.orig/autom4te.cache/output.0 b/szip-2.1.1.orig/autom4te.cache/output.0
deleted file mode 100644
--
diff --git a/szip-2.1.1.orig/autom4te.cache/output.1 b/szip-2.1.1.orig/autom4te.cache/output.1
deleted file mode 100644
--
diff --git a/szip-2.1.1.orig/autom4te.cache/output.2 b/szip-2.1.1.orig/autom4te.cache/output.2
deleted file mode 100644
--
diff --git a/szip-2.1.1.orig/autom4te.cache/requests b/szip-2.1.1.orig/autom4te.cache/requests
deleted file mode 100644
--
diff --git a/szip-2.1.1.orig/autom4te.cache/traces.0 b/szip-2.1.1.orig/autom4te.cache/traces.0
deleted file mode 100644
--
diff --git a/szip-2.1.1.orig/autom4te.cache/traces.1 b/szip-2.1.1.orig/autom4te.cache/traces.1
deleted file mode 100644
--
diff --git a/szip-2.1.1.orig/autom4te.cache/traces.2 b/szip-2.1.1.orig/autom4te.cache/traces.2
deleted file mode 100644
--
diff --git a/szip-2.1.1.orig/src/SZconfig.h.in~ b/szip-2.1.1.orig/src/SZconfig.h.in~
deleted file mode 100644
```

**Comment by boegel** [comment]
Szip checksum issue fixed in #5517

**Comment by verdurin** [comment]
Going in, thanks @boegel!

**Pull request merged**
