### PR TITLE
{lang}[fosscuda/2020b,intelcuda/2020a,intelcuda/2020b] SciPy-bundle v2020.03, SciPy-bundle v2020.11 w/ Python 3.8.2 + 3.8.6

### PR DESCRIPTION
**Pull request by Micket**
(created using `eb --new-pr`)
Just adding the cuda variants.

Note to anyone who will test build this: you need the easyblock fix from https://github.com/easybuilders/easybuild-easyblocks/pull/2022

### CODE REVIEW

**Comment by Micket** [comment]
@boegelbot please test @ generoso

**Comment by Micket** [comment]
Test report by @Micket
Using easyblocks from PR(s) https://github.com/easybuilders/easybuild-easyblocks/pull/2022
**SUCCESS**
Build succeeded for 3 out of 3 (3 easyconfigs in total)
alvis-c1 - Linux centos linux 7.8.2003, x86_64, Intel Xeon Processor (Skylake), Python 3.6.8
See https://gist.github.com/33e41da726787fa423f01bd2b589e54e for a full test report.

**Comment by migueldiascosta** [comment]
Test report by @migueldiascosta
Using easyblocks from PR(s) https://github.com/easybuilders/easybuild-easyblocks/pull/2022
**SUCCESS**
Build succeeded for 3 out of 3 (3 easyconfigs in total)
sms - Linux centos linux 7.6.1810, x86_64, AMD EPYC 7601 32-Core Processor (zen), Python 2.7.5
See https://gist.github.com/bc9be2145dca4adade9941204cff56fd for a full test report.

**Review by migueldiascosta — APPROVED** [review]
lgtm

**Comment by migueldiascosta** [comment]
Going in, thanks @Micket!

**Pull request merged**
