### PR TITLE
Make SOCI a full dep and restore sanity check commands in RStudio-Server 2021/a

### LINKED ISSUE #14107: SOCI should be a dependency, not just builddependency for RStudio-Server
With the latest `RStudio-Server` easyconfig, there is a link error on our systems:
```
 ldd /apps/eb/2020b/skylake/software/RStudio-Server/1.4.1717-foss-2021a-Java-11-R-4.1.0/bin/rserver
        linux-vdso.so.1 =>  (0x00007fffaefc1000)
        libsqlite3.so.0 => /apps/eb/2020b/skylake/software/SQLite/3.35.4-GCCcore-10.3.0/lib/libsqlite3.so.0 (0x00007f87c3e97000)
        libpq.so.5 => not found
```

This appears to be fixed if I load `SOCI`, which is listed as a `builddependency`:
```
 module load SOCI
 ldd /apps/eb/2020b/skylake/software/RStudio-Server/1.4.1717-foss-2021a-Java-11-R-4.1.0/bin/rserver
        linux-vdso.so.1 =>  (0x00007f170eded000)
        libsqlite3.so.0 => /apps/eb/2020b/skylake/software/SQLite/3.35.4-GCCcore-10.3.0/lib/libsqlite3.so.0 (0x00007f170eca8000)
        libpq.so.5 => /apps/eb/2020b/skylake/software/PostgreSQL/13.3-GCCcore-10.3.0/lib/libpq.so.5 (0x00007f170ec5a000)
```

### PR DESCRIPTION
**Pull request by verdurin**
(created using `eb --new-pr`)

Intended to fix #14107

### CODE REVIEW

**Comment by verdurin** [comment]
Test report by @verdurin
**FAILED**
Build succeeded for 3 out of 4 (1 easyconfigs in total)
easybuild-c7.novalocal - Linux centos linux 7.9.2009, x86_64, Intel Xeon Processor (Skylake, IBRS), Python 3.6.8
See https://gist.github.com/c4ba428ca53892e82c188fbab9eb4055 for a full test report.

**Comment by boegel** [comment]
@verdurin Any updates?

**Comment by branfosj** [comment]
No longer needed because of #14275?

**Comment by akesandgren** [comment]
Clearly looks solved in #14275, closing this

**Pull request closed without merging**
