### PR TITLE
{bio}[intel/2019a] MACS2 v2.1.2.1 w/ Python 2.7.15

### PR DESCRIPTION
**Pull request by boegel**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by verdurin** [comment]
Test report by @verdurin
**FAILED**
Build succeeded for 0 out of 3 (1 easyconfigs in this PR)
rescomp2 - Linux centos linux 7.3.1611, Intel(R) Xeon(R) Gold 6126 CPU @ 2.60GHz, Python 2.7.5
See https://gist.github.com/49e5832c4252c85600c2a1aeb10edcb3 for a full test report.

**Comment by verdurin** [comment]
Test report by @verdurin
**FAILED**
Build succeeded for 2 out of 4 (1 easyconfigs in this PR)
rescomp2 - Linux centos linux 7.3.1611, Intel(R) Xeon(R) Gold 6126 CPU @ 2.60GHz, Python 2.7.5
See https://gist.github.com/3d0ab907d35c011966cea7d1758f3d60 for a full test report.

**Comment by migueldiascosta** [comment]
Test report by @migueldiascosta
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
sms - Linux centos linux 7.6.1810, AMD EPYC 7601 32-Core Processor, Python 2.7.5
See https://gist.github.com/62732153153a8f9c411f3c07e5ae5aea for a full test report.

**Comment by migueldiascosta** [comment]
@verdurin your test failure seems to be related to `SciPy-bundle`, is it site specific?

**Comment by verdurin** [comment]
@migueldiascosta yes, it fails when trying to import `numpy` in the `sanity_check` step:
```
== 2019-09-10 12:34:10,873 run.py:542 DEBUG Using default regular expression: (?<![(,-]|\w)(?:error|segmentation fault|failed)(?![(,-]|\.?\w)
== 2019-09-10 12:34:10,873 pythonpackage.py:169 DEBUG Determined pylibdir using 'python -c 'import distutils.sysconfig; print(distutils.sysconfig.get_python_lib(plat_specific=False, prefix="/tmp/"))'': lib/python2.7/site-packages
== 2019-09-10 12:34:10,873 pythonpackage.py:584 INFO Detection of downloaded depenencies enabled, checking output of installation command...
== 2019-09-10 12:34:10,874 easyconfig.py:1612 WARNING Unable to resolve template value python -c "import %(ext_name)s" with dict {'bitbucket_account': 'scipy-bundle', 'nameletterlower': 'n', 'versionsuffix': '', 'toolchain_name': 'intel', 'namelower': 'numpy', 'version_minor': '16', 'arch': 'x86_64', 'name': 'numpy', 'versionprefix': '', 'version_major': '1', 'nameletter': 'n', 'version_major_minor': '1.16', 'version': '1.16.2', 'github_account': 'scipy-bundle', 'toolchain_version': '2019a'}
== 2019-09-10 12:34:10,874 easyconfig.py:1612 WARNING Unable to resolve template value python -c "import %(ext_name)s" with dict {'bitbucket_account': 'scipy-bundle', 'nameletterlower': 'n', 'versionsuffix': '', 'toolchain_name': 'intel', 'namelower': 'numpy', 'version_minor': '16', 'arch': 'x86_64', 'name': 'numpy', 'versionprefix': '', 'version_major': '1', 'nameletter': 'n', 'version_major_minor': '1.16', 'version': '1.16.2', 'github_account': 'scipy-bundle', 'toolchain_version': '2019a'}
== 2019-09-10 12:34:10,874 extensioneasyblock.py:123 DEBUG starting sanity check for extension with filter ('python -c "import %(ext_name)s"', '')
== 2019-09-10 12:34:10,874 extension.py:160 DEBUG modulename found in self.options, using it: numpy
== 2019-09-10 12:34:10,874 run.py:173 DEBUG run_cmd: running cmd python -c "import numpy" (in /gpfs2/well/rescomp/eb/software/SciPy-bundle/2019.03-intel-2019a)
== 2019-09-10 12:34:10,874 run.py:192 INFO running cmd: python -c "import numpy"
== 2019-09-10 12:34:10,896 extension.py:193 WARNING Sanity check for 'numpy' extension failed: command "python -c "import numpy"" failed; output:
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: No module named numpy
```

This is the second iteration, for `Python-2.7.15`.

**Comment by smoors** [comment]
Test report by @smoors
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
node310.hydra.os - Linux centos linux 7.6.1810, Intel(R) Xeon(R) Gold 6148 CPU @ 2.40GHz, Python 2.7.5
See https://gist.github.com/8fdd2090ddfc5adbbf74ac002d30f57a for a full test report.

**Comment by smoors** [comment]
Going in, thanks @boegel!

**Pull request merged**
