### PR TITLE
{math}[system/system] MCR vR2024a w/ .4

### PR DESCRIPTION
**Pull request by branfosj**
(created using `eb --new-pr`)

* [ ] https://github.com/easybuilders/easybuild-easyblocks/pull/3369

### CODE REVIEW

**Comment by branfosj** [comment]
@boegelbot please test @ generoso
EB_ARGS="--include-easyblocks-from-pr 3369"

**Comment by branfosj** [comment]
@boegelbot please test @ jsc-zen3
EB_ARGS="--include-easyblocks-from-pr 3369"

**Comment by branfosj** [comment]
Test report by @branfosj
Using easyblocks from PR(s) https://github.com/easybuilders/easybuild-easyblocks/pull/3369
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
bear-pg0105u03a - Linux RHEL 8.6, x86_64, Intel(R) Xeon(R) Platinum 8360Y CPU @ 2.40GHz (icelake), Python 3.6.8
See https://gist.github.com/branfosj/66620fbad0c3b48efc31ad135796e0aa for a full test report.

**Review by boegel — APPROVED** [review]
lgtm

**Comment by boegel** [comment]
Test report by @boegel
Using easyblocks from PR(s) https://github.com/easybuilders/easybuild-easyblocks/pull/3369
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
node3104.skitty.os - Linux RHEL 8.8, x86_64, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz, Python 3.6.8
See https://gist.github.com/boegel/c092e24062a02fe3b4590fed58f168c3 for a full test report.

**Comment by boegel** [comment]
Going in, thanks @branfosj!

**Pull request merged**
