### PR TITLE
{bio}[intel/2017b] FALCON v1.8.8

### PR DESCRIPTION
**Pull request by boegel**
(created using `eb --new-pr`)

edit: requires https://github.com/easybuilders/easybuild-easyblocks/pull/1285 for per-component checksums to be picked up

### CODE REVIEW

**Comment by boegel** [comment]
(marked as WIP because I'm awaiting feedback from the person who requested this to be installed)

@vanzod, @verdurin: Are you guys up for taking a look at this, and maybe testing it, since it seems to be in the domain your cater to?

I did the best I could to untangle the rather messy installation procedure, and deliberate stayed away from their custom install tool `FALCON-integrate` (which calls `FALCON-make`, etc.)...

**Comment by vanzod** [comment]
Test report by @vanzod
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
cermis - Linux debian 8.8, Intel(R) Xeon(R) CPU           E5620  @ 2.40GHz, Python 2.7.9
See https://gist.github.com/4c5687e686643ba9f121e01e58e7e263 for a full test report.

**Comment by verdurin** [comment]
@boegel style problem:
```
/home/travis/build/easybuilders/easybuild-easyconfigs/easybuild/easyconfigs/f/FALCON/FALCON-1.8.8-intel-2017b.eb:89:110: E261 at least two spaces before inline comment
```

**Comment by boegel** [comment]
@easybuilders/easybuild-easyconfigs-maintainers Should be good to go now..

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
node2404.golett.os - Linux centos linux 7.4.1708, Intel(R) Xeon(R) CPU E5-2680 v3 @ 2.50GHz, Python 2.7.5
See https://gist.github.com/b81fb7573dbb7531f99a0217ba82408e for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
node2029.delcatty.os - Linux centos linux 7.4.1708, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.7.5
See https://gist.github.com/00d0a879fc6b40fc5b378f83a3116855 for a full test report.

**Pull request merged**
