### PR TITLE
{lib}[GCC/10.2.0] librsb v1.3.0.1

### PR DESCRIPTION
**Pull request by michelemartone**
adding file for librsb-1.3.0.1

### CODE REVIEW

**Comment by migueldiascosta** [comment]
is this no longer necessary?

```diff
-# do not rely on `librsb-config --I_opts`, it will inject paths in install dir
-preconfigopts = "sed -i '21,22d' librsbpp/configure.ac && "
-preconfigopts += "autoreconf -fi &&"
-
```

**Comment by michelemartone** [comment]
Hi @migueldiascosta . Not anymore :-)

**Comment by migueldiascosta** [comment]
@boegelbot please test @ generoso

**Review by migueldiascosta — APPROVED** [review]
lgtm

**Comment by migueldiascosta** [comment]
Going in, thanks @michelemartone!

**Pull request merged**
