### PR TITLE
{astro}[GCCcore/8.3.0] HEALPix v3.70

### PR DESCRIPTION
**Pull request by jose-d**
There is new release of HEALPix[2], and as we're used to, the new interactive Q/A configuration script is not compatible with current q/a based easyblock as some questions were slightly modified or reformatted.

As one can find in changelog[3] of `configure` script, finally(!), the combination of `--auto` and `-L` mode is possible, so in my opinion, there is no more need for custom[1] easyblock with hardwired _Q/A_ dictionary.

The only remaining weirdness of `configure` script is actually the `-L` option itself. It configures HEALPix to be installed into _builddir_, while standard `--prefix` option is unknown and when uses, it cause configure script to fail. 
To deal with this, part of this PR is `HEALPIX-3.70-accept_prefix_in_configure.patch` patch, which allows `--configure *` option as dummy option with no meaning.

[1] [easyblocks/h/healpix.py](https://github.com/easybuilders/easybuild-easyblocks/blob/develop/easybuild/easyblocks/h/healpix.py)
[2] [healpix.sourceforge.io: New Features in HEALPix](https://healpix.sourceforge.io/downloads.php)
[3] [Bug corrections and Improvements in Version 3.70](https://healpix.sourceforge.io/downloads.php#SECTION_370_10000000000000000)

(created using `eb --new-pr`)

### CODE REVIEW

**Comment by jose-d** [comment]
Test report by @jose-d
**SUCCESS**
Build succeeded for 0 out of 0 (1 easyconfigs in total)
koiosvm1 - Linux centos linux 7.8.2003, x86_64, Intel Xeon Processor (Skylake, IBRS), Python 2.7.5
See https://gist.github.com/3577214a9c175c09bd2109739cd17404 for a full test report.

**Comment by jose-d** [comment]
Test report by @jose-d
**FAILED**
Build succeeded for 0 out of 1 (1 easyconfigs in total)
koiosvm1 - Linux centos linux 7.8.2003, x86_64, Intel Xeon Processor (Skylake, IBRS), Python 2.7.5
See https://gist.github.com/e8b4ae3449c45d7037f50478a9926073 for a full test report.

**Comment by jose-d** [comment]
Test report by @jose-d
**FAILED**
Build succeeded for 0 out of 1 (1 easyconfigs in total)
koiosvm1 - Linux centos linux 7.8.2003, x86_64, Intel Xeon Processor (Skylake, IBRS), Python 2.7.5
See https://gist.github.com/b4cd6e2689aee8bee4706423165bb6d3 for a full test report.

**Comment by lexming** [comment]
Test report by @lexming
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
node381.hydra.os - Linux centos linux 7.7.1908, x86_64, Intel(R) Xeon(R) Gold 6148 CPU @ 2.40GHz, Python 2.7.5
See https://gist.github.com/bab8f18a85509a4bc3b87ba859a04df0 for a full test report.

**Comment by lexming** [comment]
Test report by @lexming
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
node128.hydra.os - Linux centos linux 7.7.1908, x86_64, Intel(R) Xeon(R) CPU E5-2680 v2 @ 2.80GHz, Python 2.7.5
See https://gist.github.com/951ad492aac0831a12c7d2b54d55f8d7 for a full test report.

**Comment by jose-d** [comment]
Test report by @jose-d
**FAILED**
Build succeeded for 0 out of 1 (1 easyconfigs in total)
koiosvm1 - Linux centos linux 7.8.2003, x86_64, Intel Xeon Processor (Skylake, IBRS), Python 2.7.5
See https://gist.github.com/0fa89e838a5c608225f863cb83ecf544 for a full test report.

**Comment by jose-d** [comment]
I do have some weird problem with build. Almost sure if related to "install in builddir" and our NFS setup.. So files checked by sanity checks are physically there, but sanity check doesn't see them..  Sometimes works, sometimes not..

**Comment by lexming** [comment]
@jose-d  `ConfigureMake` has the option `prefix_opt` which allows to change the name of the prefix option passed to the configure script. Hence, it would be possible to use `prefix_opt = '-L'` by patching the configure script to accept `-L` options with an argument. This would be a better solution because instead of ignoring the prefix set by EB, the installation of HEALPix would be able to follow that prefix. The configure script already handles options with arguments, such as `--auto`, so it might be easy to take that code for the `-L` option.

**Comment by verdurin** [comment]
@jose-d any thoughts on the suggestions from @lexming ?

**Comment by jose-d** [comment]
Test report by @jose-d
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
koiosvm1 - Linux centos linux 7.8.2003, x86_64, Intel Xeon Processor (Skylake, IBRS), Python 2.7.5
See https://gist.github.com/d9a2a2da75178a3ae3cdb3e757bb36e0 for a full test report.

**Comment by jose-d** [comment]
@lexming 

> @jose-d `ConfigureMake` has the option `prefix_opt`  ( .. ) it would be possible to use `prefix_opt = '-L` by patching the configure script to accept `-L` options with an argument. 

done.

> This would be a better solution because instead of ignoring the prefix set by EB

agree.

> the installation of HEALPix would be able to follow that prefix

mhmm, this would need serious patching, mhmm, or rather rewrite the `./configure` script.
And i'm not sure I / we (easybuild contributors) should do it. There was open ticket for it, https://sourceforge.net/p/healpix/bugs/110/, and answer was

> no, currently it is not possible to specify a different location than the source directory to install
the binaries, libs and include files.

**Pull request closed without merging**
