### PR TITLE
{vis}[foss/2019b] pydot v1.4.1 w/ Python 2.7.16 + 3.7.4

### PR DESCRIPTION
**Pull request by lexming**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by verdurin** [comment]
Test report by @verdurin
**FAILED**
Build succeeded for 0 out of 3 (1 easyconfigs in this PR)
generoso - Linux centos linux 7.6.1810, Intel(R) Xeon(R) CPU E5-2660 v4 @ 2.00GHz, Python 3.6.8
See https://gist.github.com/fadb9def383108fd661b2bb97cf68bf3 for a full test report.

**Comment by lexming** [comment]
Test report by @lexming
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
login2.cerberus.os - Linux centos linux 7.7.1908, Intel(R) Xeon(R) Gold 6126 CPU @ 2.60GHz, Python 2.7.5
See https://gist.github.com/d762dff451e717f35b27a1f2f9422985 for a full test report.

**Comment by lexming** [comment]
@verdurin your test failed at building the documentation of `Gdk-Pixbuf`, which is not part of this PR.

**Comment by verdurin** [comment]
@lexming yes, re-running on a different system.

**Comment by verdurin** [comment]
Test report by @verdurin
**SUCCESS**
Build succeeded for 30 out of 30 (1 easyconfigs in this PR)
easybuild.novalocal - Linux centos linux 7.7.1908, Intel Xeon Processor (Skylake, IBRS), Python 2.7.5
See https://gist.github.com/6c99b98d84c3a7cc5a779053cd3917ca for a full test report.

**Comment by verdurin** [comment]
Going in, thanks @lexming!

**Pull request merged**
