### PR TITLE
{bio}[GCC/9.3.0,gompi/2020a] RAxML v8.2.12

### PR DESCRIPTION
**Pull request by lexming**
(created using `eb --new-pr`)
requires:
* https://github.com/easybuilders/easybuild-easyblocks/pull/2180

### CODE REVIEW

**Comment by lexming** [comment]
Test report by @lexming
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in this PR)
node381.hydra.os - Linux centos linux 7.7.1908, x86_64, Intel(R) Xeon(R) Gold 6148 CPU @ 2.40GHz, Python 2.7.5
See https://gist.github.com/56f42f0df1dbf25accc66fcf3453311d for a full test report.

**Comment by lexming** [comment]
@verdurin https://github.com/easybuilders/easybuild-easyblocks/pull/2180 has not been merged yet

**Comment by verdurin** [comment]
> @verdurin [easybuilders/easybuild-easyblocks#2180](https://github.com/easybuilders/easybuild-easyblocks/pull/2180) has not been merged yet

Sorry - excessive zeal.

**Comment by akesandgren** [comment]
Closing this PR, since it (only) uses deprecated toolchain versions,
see https://docs.easybuild.io/policies/toolchains .

We also have RAxML-NG which looks to be a newer code for the same purpose.

**Pull request closed without merging**
