### PR TITLE
add pocl dependency to GDAL easyconfig using fosscuda/2019b toolchain to make sure it builds on POWER

### PR DESCRIPTION
**Pull request by dithwick**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by boegel** [comment]
@dithwick Any chance for a test report from a POWER system?

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
node2412.golett.os - Linux centos linux 7.8.2003, x86_64, Intel(R) Xeon(R) CPU E5-2680 v3 @ 2.50GHz (haswell), Python 2.7.5
See https://gist.github.com/120e3f6fb6c6de22e75df8e1330a4087 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
node3303.joltik.os - Linux centos linux 7.8.2003, x86_64, Intel(R) Xeon(R) Gold 6242 CPU @ 2.80GHz (cascadelake), Python 3.6.8
See https://gist.github.com/5db2616b3263224658df731f76a5831b for a full test report.

**Comment by boegel** [comment]
@boegelbot please test @ generoso

**Comment by dithwick** [comment]
@boegel Would love to do a test report for power but it might take me a while as we only have the one system and it's now very busy ;-)

**Comment by dithwick** [comment]
Test report by @dithwick
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
pnode1.orac.cluster - Linux centos linux 7.6.1810, POWER, 8335-GTB, Python 2.7.5
See https://gist.github.com/4bd55a2a2f6827bf8fd40faa6687740d for a full test report.

**Comment by dithwick** [comment]
@boegel Done! Had a gap in the jobs.

**Review by boegel — APPROVED** [review]
lgtm

**Comment by boegel** [comment]
Going in, thanks @dithwick!

**Pull request merged**
