### PR TITLE
only set flag `--enable-asmjit` for PLUMED when installing on `x86_64`

### PR DESCRIPTION
**Pull request by laraPPr**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by laraPPr** [comment]
Test report by @laraPPr
**SUCCESS**
Build succeeded for 9 out of 9 (7 easyconfigs in total)
node3511.doduo.os - Linux RHEL 8.8, x86_64, AMD EPYC 7552 48-Core Processor, Python 3.6.8
See https://gist.github.com/laraPPr/ef82525946cdb04aad069a49debf21b2 for a full test report.

**Comment by laraPPr** [comment]
@bedroge can you review and add the labels `eessi` and  `bug fìx`?

**Comment by bedroge** [comment]
@boegelbot please test @ generoso

**Comment by bedroge** [comment]
@boegelbot please test @ jsc-zen2

**Review by bedroge — APPROVED** [review]
Looks good to me.

**Comment by bedroge** [comment]
Going in, thanks @laraPPr!

**Pull request merged**
