### PR TITLE
{system}[dummy/dummy] CUDA v10.1.105

### PR DESCRIPTION
**Pull request by sassy-crick**
(created using `eb --new-pr`)

edit: requires https://github.com/easybuilders/easybuild-easyblocks/pull/1654

### CODE REVIEW

**Comment by boegel** [comment]
Test report by @boegel
**FAILED**
Build succeeded for 0 out of 1 (1 easyconfigs in this PR)
node3111.skitty.os - Linux centos linux 7.6.1810, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz, Python 2.7.5
See https://gist.github.com/69f477b725b8010a1e65398c3602779c for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**FAILED**
Build succeeded for 0 out of 1 (1 easyconfigs in this PR)
node2113.delcatty.os - Linux centos linux 7.6.1810, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.7.5
See https://gist.github.com/a86cba06961dbe5a3338784af90c924d for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**FAILED**
Build succeeded for 0 out of 1 (1 easyconfigs in this PR)
node2603.swalot.os - Linux centos linux 7.6.1810, Intel(R) Xeon(R) CPU E5-2660 v3 @ 2.60GHz, Python 2.7.5
See https://gist.github.com/e9f991fdd533a2a0e6b5c02396f61fae for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
node3140.skitty.os - Linux centos linux 7.6.1810, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz, Python 2.7.5
See https://gist.github.com/37c72bce34307c45b1fb72bb1a00a653 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
node2044.delcatty.os - Linux centos linux 7.6.1810, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.7.5
See https://gist.github.com/86df0f39aaaace127ef0c1717634f7f5 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
node2523.golett.os - Linux centos linux 7.6.1810, Intel(R) Xeon(R) CPU E5-2680 v3 @ 2.50GHz, Python 2.7.5
See https://gist.github.com/21c3d6b434c1eabd0e20e99fda44da5b for a full test report.

**Comment by boegel** [comment]
Going in, thanks @sassy-crick!

**Comment by Helios07** [comment]
I cannot install CUDA 10.1 with this config file. It says:
`== FAILED: Installation ended unsuccessfully (build directory: /tmp/CUDA/10.1.105/dummy-dummy): build failed (first 300 chars): Failed to read /tmp/CUDA/10.1.105/dummy-dummy/cuda-installer.pl: [Errno 2] No such file or directory: '/tmp/CUDA/10.1.105/dummy-dummy/cuda-installer.pl'`
In fact there is only /tmp/CUDA/10.1.105/dummy-dummy/cuda-installer (without the .pl)

**Comment by akesandgren** [comment]
As the description at the top says, you need https://github.com/easybuilders/easybuild-easyblocks/pull/1654 to install this.

**Pull request merged**
