### PR TITLE
{vis}[GCCcore/8.2.0] Leptonica v1.78.0, tesseract v4.1.0

### PR DESCRIPTION
**Pull request by murfreesboro**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by murfreesboro** [comment]
Test report by @murfreesboro
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in this PR)
dev806.vampire - Linux centos linux 7.4.1708, Intel(R) Xeon(R) CPU           E5620  @ 2.40GHz, Python 2.7.5
See https://gist.github.com/bf728cadac4d7798ae438554499fd833 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in this PR)
node2713.swalot.os - Linux centos linux 7.6.1810, Intel(R) Xeon(R) CPU E5-2660 v3 @ 2.60GHz, Python 2.7.5
See https://gist.github.com/e6abb150025d6ffcd3cf645a7de57daa for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in this PR)
node2094.delcatty.os - Linux centos linux 7.6.1810, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.7.5
See https://gist.github.com/f335673fe62c45956cbf6d21170bf6d8 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in this PR)
node3133.skitty.os - Linux centos linux 7.6.1810, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz, Python 3.6.8
See https://gist.github.com/3a4ee81d46468e194b63657b493fbeb3 for a full test report.

**Comment by boegel** [comment]
Going in, thanks @murfreesboro!

**Comment by Flamefire** [comment]
This fails for me due to missing requirements like Pango: https://github.com/tesseract-ocr/tesseract/blob/4.1.0/src/training/CMakeLists.txt#L258-L264

I think the cause this worked here is that you don't have a system ICU and the whole block is guarded in `if(ICU_FOUND)`

**Comment by Flamefire** [comment]
And the tessdata download is wrong: https://github.com/easybuilders/easybuild-easyconfigs/pull/9030/files#diff-950ebded0258e5dbe0041f78056ac691R22-R23

It does download the tesseract source instead. Why does EB fall back to global source_urls when local do not work?

Anyway: Fixed in  https://github.com/easybuilders/easybuild-easyconfigs/pull/9650

**Pull request merged**
