### PR TITLE
Rework Mmg-5.6.0 tests, fixes #15662

### LINKED ISSUE #15662: test step for Mmg v5.6.0 fails because ci_tests directory is missing
Pretty much all tests fail for me with errors like:

```
222/245 Test #224: mmg_LeakCheck_args1_mmg3d_O3 ......................***Failed    0.14 sec
  ** /tmp/easybuild_build/Mmg/5.6.0/gompi-2021b/mmg-5.6.0/ci_tests/mmg/LeakCheck_args1/d  NOT FOUND.
  ** UNABLE TO OPEN INPUT FILE.
  -- MMG3D, Release 5.6.0 (Nov. 05, 2021) 
     Copyright (c) Bdx INP/CNRS/Inria/UPMC, 2004-
     Jun 10 2022 21:39:27

  -- INPUT DATA

   ELAPSED TIME  0.000s
```

(see also test report at https://github.com/easybuilders/easybuild-easyconfigs/pull/15622#issuecomment-1152675085)

I'm not sure how this wasn't a problem for others in #15622... Any ideas here @Micket, @SebastianAchilles?

### PR DESCRIPTION
**Pull request by Micket**
Fixes #15691 

I also run the test sequentially now since these are so quick anyway and it's more readable like this.
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by Micket** [comment]
@boegelbot please test @ generoso

**Comment by Micket** [comment]
Test report by @Micket
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
alvis-c1 - Linux Rocky Linux 8.5, x86_64, Intel Xeon Processor (Skylake), Python 3.6.8
See https://gist.github.com/7a8c38dd7e621ae3bf3b812f16dc437d for a full test report.

**Comment by branfosj** [comment]
Test report by @branfosj
**SUCCESS**
Build succeeded for 2 out of 2 (1 easyconfigs in total)
bear-pg0105u36b.bear.cluster - Linux RHEL 8.6, x86_64, Intel(R) Xeon(R) Platinum 8360Y CPU @ 2.40GHz (icelake), Python 3.6.8
See https://gist.github.com/08af719442d8e39b2d5b48bba292f228 for a full test report.

**Comment by branfosj** [comment]
Test report by @branfosj
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
bear-pg0211u03a.bear.cluster - Linux RHEL 8.6, x86_64, Intel(R) Xeon(R) Gold 6248 CPU @ 2.50GHz (cascadelake), Python 3.6.8
See https://gist.github.com/484f0a1701dc64e0155ebf088c67ad3b for a full test report.

**Review by branfosj — APPROVED** [review]
lgtm

**Comment by branfosj** [comment]
Going in, thanks @Micket!

**Pull request merged**
