### PR TITLE
{chem}[foss/2017b,intel/2017b] QuantumESPRESSO v6.3

### PR DESCRIPTION
**Pull request by vanzod**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by vanzod** [comment]
Test report by @vanzod
**FAILED**
Build succeeded for 3 out of 5 (5 easyconfigs in this PR)
cermis - Linux debian 9.8, Intel(R) Xeon(R) CPU           X5670  @ 2.93GHz, Python 2.7.13
See https://gist.github.com/4a29fd8c68c9d4d675dcd5cb433f3b2f for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**FAILED**
Build succeeded for 3 out of 5 (5 easyconfigs in this PR)
node2113.delcatty.os - Linux centos linux 7.6.1810, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.7.5
See https://gist.github.com/31755af67c4efb66840ff33bf1dd914e for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**FAILED**
Build succeeded for 4 out of 6 (5 easyconfigs in this PR)
node3101.skitty.os - Linux centos linux 7.6.1810, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz, Python 2.7.5
See https://gist.github.com/b211e4c55e258156b44b1816adcdfbbe for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**FAILED**
Build succeeded for 4 out of 6 (5 easyconfigs in this PR)
node2426.golett.os - Linux centos linux 7.6.1810, Intel(R) Xeon(R) CPU E5-2680 v3 @ 2.50GHz, Python 2.7.5
See https://gist.github.com/3ce3cc5e7d709eaf3874fa27ae62da66 for a full test report.

**Comment by vanzod** [comment]
Test report by @vanzod
**FAILED**
Build succeeded for 4 out of 5 (5 easyconfigs in this PR)
cermis - Linux debian 9.8, Intel(R) Xeon(R) CPU           X5670  @ 2.93GHz, Python 2.7.13
See https://gist.github.com/d595d52ea3115c81cd57057d2b828bcd for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**FAILED**
Build succeeded for 4 out of 5 (5 easyconfigs in this PR)
node3101.skitty.os - Linux centos linux 7.6.1810, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz, Python 2.7.5
See https://gist.github.com/2430c49b2770d7c9027fd7568e87a3b6 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**FAILED**
Build succeeded for 4 out of 5 (5 easyconfigs in this PR)
node2100.delcatty.os - Linux centos linux 7.6.1810, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.7.5
See https://gist.github.com/41b901771556540a5a215d7857e3891e for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**FAILED**
Build succeeded for 4 out of 5 (5 easyconfigs in this PR)
node2402.golett.os - Linux centos linux 7.6.1810, Intel(R) Xeon(R) CPU E5-2680 v3 @ 2.50GHz, Python 2.7.5
See https://gist.github.com/e2aa8ad29038a063ac059c2c789ab1f7 for a full test report.

**Comment by akesandgren** [comment]
Test report by @akesandgren
**SUCCESS**
Build succeeded for 8 out of 8 (5 easyconfigs in this PR)
b-an03.hpc2n.umu.se - Linux ubuntu 16.04, Intel(R) Xeon(R) CPU E5-2690 v4 @ 2.60GHz, Python 2.7.12
See https://gist.github.com/ce4e7c2697a0e9dc95a092c7a29fb791 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**FAILED**
Build succeeded for 4 out of 5 (5 easyconfigs in this PR)
node2588.golett.os - Linux centos linux 7.6.1810, Intel(R) Xeon(R) CPU E5-2680 v3 @ 2.50GHz, Python 2.7.5
See https://gist.github.com/14262d29fd53a7c715dd442d56408f43 for a full test report.

**Comment by boegel** [comment]
Not sure why this works for you @akesandgren ... :)

**Comment by wpoely86** [comment]
Test report by @wpoely86
**FAILED**
Build succeeded for 4 out of 6 (5 easyconfigs in this PR)
nic402 - Linux centos linux 7.5.1804, Intel(R) Xeon(R) Gold 6148 CPU @ 2.40GHz, Python 2.7.5
See https://gist.github.com/5086ca551950029169b2f2f9a77da8c6 for a full test report.

**Comment by vanzod** [comment]
@wpoely86 For some weird reason `ELPA` seems to be trying to build with GPU acceleration. Can you try to build it again and send me a full log if it fails again?

**Comment by wpoely86** [comment]
@vanzod Most likely there is some CUDA stuff installed on the node which ELPA automatically picks up.

**Comment by vanzod** [comment]
Opened an issue with the QE developers:
https://gitlab.com/QEF/q-e/issues/104

**Comment by akesandgren** [comment]
According to the output from mpifort there, the bug report should go to GCC devs not QE.

**Comment by boegel** [comment]
Ancient (and now [deprecated](https://docs.easybuild.io/en/latest/Deprecated-easyconfigs.html#deprecated-toolchains)) toolchains, and a QuantumESPRESSO version which is likely not relevant anymore (current version is [7.0](https://github.com/QEF/q-e/releases/tag/qe-7.0)), so I'll go ahead and close this...

**Pull request closed without merging**
