### PR TITLE
{lib}[GCCcore/7.3.0] libjpeg-turbo 2.0.0

### PR DESCRIPTION
**Pull request by fizwit**
libjpeg-turbo 2.0 for GCCcore 7.3.0
The buils process has changed from ConfigureMake to CMakeMake

### CODE REVIEW

**Comment by boegel** [comment]
@fizwit I corrected the target branch to `develop` for this PR.

Also `NASM-2.13.03-GCCcore-7.3.0.eb` is not in the right location, should be in `easybuild/easyconfgs/n/NASM`, which is why the tests are failing.

Have you looked at the changelog whether there are any breaking changes API-wise in libjpeg-turbo 2.0 compared to the latest 1.x version? I.e., should be we be able to use this as a dependency where needed in easyconfigs using a `2018b` toolchain?

**Comment by fizwit** [comment]
I will resubmit with NASM.  Yes I plan to use this with 2018b.  I have just finished R-3.5.1 for foss-2018b. I will need to submit about a dozen dependancy packages first.

**Comment by boegel** [comment]
@fizwit Some minor style issues to fix:

```
$ eb --check-style --from-pr 6656
== temporary log file in case of crash /Users/kehoste/work/TMP/eb-HkrJOv/easybuild-0wQVM6.log

*** WARNING: Using easyconfigs from unstable (pending/failed tests or merge conflict) PR #6656 ***

Running style check on 3 easyconfig(s)...
[PASS] /Users/kehoste/work/TMP/eb-HkrJOv/files_pr6656/easybuild/NASM-2.13.03-GCCcore-7.3.0.eb
/Users/kehoste/work/TMP/eb-HkrJOv/files_pr6656/l/libjpeg-turbo/libjpeg-turbo-2.0.0-GCCcore-7.3.0.eb:30:50: W299 trailing whitespace
[FAIL] /Users/kehoste/work/TMP/eb-HkrJOv/files_pr6656/l/libjpeg-turbo/libjpeg-turbo-2.0.0-GCCcore-7.3.0.eb
[PASS] /Users/kehoste/work/TMP/eb-HkrJOv/files_pr6656/n/NASM/NASM-2.13.03-GCCcore-7.3.0.eb
ERROR: One or more style checks FAILED!
```

**Comment by boegel** [comment]
@fizwit https://github.com/fizwit/easybuild-easyconfigs/pull/2 should make this PR good to go, please review & merge it

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in this PR)
node3123.skitty.os - Linux centos linux 7.4.1708, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz, Python 2.7.5
See https://gist.github.com/69cb8ec9fc22667d9d6cbe88e8e684b8 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in this PR)
node2469.golett.os - Linux centos linux 7.4.1708, Intel(R) Xeon(R) CPU E5-2680 v3 @ 2.50GHz, Python 2.7.5
See https://gist.github.com/19a0cc07c7650b0a4afa74e0ce83fee3 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in this PR)
node2110.delcatty.os - Linux centos linux 7.4.1708, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.7.5
See https://gist.github.com/9475bdafccc6bb0f79b9eee1af1fd553 for a full test report.

**Comment by boegel** [comment]
Going in, thanks @fizwit!

**Pull request merged**
