### PR TITLE
{lib}[gompi/2020a,iimpi/2020a] lwgrp v1.0.2

### PR DESCRIPTION
**Pull request by JackPerdue**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by lexming** [comment]
Test report by @lexming
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in this PR)
login2.cerberus.os - Linux centos linux 7.7.1908, Intel(R) Xeon(R) Gold 6126 CPU @ 2.60GHz, Python 2.7.5
See https://gist.github.com/bdea8eb1e0cddece8672b1516ac99e82 for a full test report.

**Comment by zao** [comment]
Test report by @zao
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in this PR)
freja - Linux ubuntu 18.04, Intel(R) Core(TM) i7-8700K CPU @ 3.70GHz, Python 2.7.17
See https://gist.github.com/5abb36ea84a2be98da84b244ddc59741 for a full test report.

**Comment by akesandgren** [comment]
Test report by @akesandgren
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in this PR)
skalman.hpc2n.umu.se - Linux ubuntu 18.04, Intel(R) Core(TM) i7-8565U CPU @ 1.80GHz, Python 2.7.17
See https://gist.github.com/d1464ea6112528d8a9877da5a624b764 for a full test report.

**Comment by akesandgren** [comment]
Going in, thanks @JackPerdue!

**Comment by JackPerdue** [comment]
Why was this and dtcmp not included in EasyBuild/4.2.1?   It says it was merged, but I don't see it.

**Comment by boegel** [comment]
@JackPerdue It was merged to the `2020a` branch, and we still need to collapse the remainder of the `2020a` branch into `develop` (for the next release).

We ran into some blockers (mainly the `MPI_Init` issue with h5py) that prevented us from doing that shortly before the EasyBuild v4.2.1 release...

I've opened #10753 to avoid forgetting about doing so before the next EasyBuild release.

**Pull request merged**
