### PR TITLE
add patch for xtb 6.7.0 to fix build failure due to changes in tblite

### LINKED ISSUE #21243: build of xtb 6.7.0 with `gfbf/2023a` not working
```
[528/898] Compiling Fortran object libxtb.so.6.7.0.p/src_dipro_xtb.F90.o
FAILED: libxtb.so.6.7.0.p/src_dipro_xtb.F90.o libxtb.so.6.7.0.p/xtb_dipro_xtb.mod
gfortran -Ilibxtb.so.6.7.0.p -I. -I../xtb-6.7.0 -I../xtb-6.7.0/include -Isubprojects/mctc-lib/libmctc-lib.a.p -Isubprojects/json-fortran-8.2.5/libjsonfortran.a.p -I../xtb-6.7.0/subprojects/tblite/include -Isubprojects/tblite/libtblite.a.p -Isubprojects/dftd4/libdftd4.a.p -I../xtb-6.7.0/subprojects/dftd4/include -Isubprojects/multicharge/libmulticharge.a.p -Isubprojects/s-dftd3/libs-dftd3.a.p -I../xtb-6.7.0/subprojects/s-dftd3/include -Isubprojects/toml-f/libtoml-f.a.p -Isubprojects/numsa/libnumsa.a.p -Isubprojects/cpx/libcpx.a.p -fdiagnostics-color=always -D_FILE_OFFSET_BITS=64 -Wall -O2 -fdefault-real-8 -fdefault-double-8 -ffree-line-length-none -fbacktrace -O2 -ftree-vectorize -march=native -fno-math-errno -fPIC -fopenmp -pthread -fopenmp -DWITH_TBLITE=1 -DWITH_CPCMX=1 -Jlibxtb.so.6.7.0.p -o libxtb.so.6.7.0.p/src_dipro_xtb.F90.o -c ../xtb-6.7.0/src/dipro/xtb.F90
../xtb-6.7.0/src/dipro/xtb.F90:53:42:

   53 |       call new_gfn2_calculator(xcalc, mol)
      |                                          1
Error: Missing actual argument for argument error at (1)
../xtb-6.7.0/src/dipro/xtb.F90:55:42:

   55 |       call new_gfn1_calculator(xcalc, mol)
      |                                          1
Error: Missing actual argument for argument error at (1)
../xtb-6.7.0/src/dipro/xtb.F90:57:43:

   57 |       call new_ipea1_calculator(xcalc, mol)
      |                                           1
Error: Missing actual argument for argument error at (1)
ninja: build stopped: subcommand failed.
```

I'm a bit confused why this error didn't pop up in #20288...

@WilleBell Can you check if a test install of `xtb-6.7.0-gfbf-2023a.eb` is still working for you?

### PR DESCRIPTION
**Pull request by WilleBell**
(created using `eb --new-pr`)

closes #21243

### CODE REVIEW

**Comment by WilleBell** [comment]
Test report by @WilleBell
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
node605.hydra.os - Linux Rocky Linux 8.10, x86_64, AMD EPYC 9384X 32-Core Processor, Python 3.6.8
See https://gist.github.com/WilleBell/91d2952dd870241f80192787dcc58654 for a full test report.

**Comment by boegel** [comment]
@boegelbot please test @ generoso

**Comment by boegel** [comment]
@boegelbot please test @ jsc-zen3

**Comment by boegel** [comment]
@boegelbot please test @ jsc-zen3

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
node3123.skitty.os - Linux RHEL 8.8, x86_64, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz, Python 3.6.8
See https://gist.github.com/boegel/1ae5d2754140729cb65390ce2fbe4ee8 for a full test report.

**Review by boegel — APPROVED** [review]
lgtm

**Comment by boegel** [comment]
Going in, thanks @WilleBell!

**Pull request merged**
