### PR TITLE
{lib}[GCC/8.3.0 and gcccuda/2019b] pocl v1.4

### PR DESCRIPTION
**Pull request by branfosj**
(created using `eb --new-pr`)

requires:
* [x] Clang (#9589)
* [ ] Clang with CUDA (#9592)

Note that there is an issue to solve over CUDA dependencies - that I've detailed in #9592.

### CODE REVIEW

**Comment by branfosj** [comment]
Patch fixes a bunch of errors with message:
```
/rds/bear-apps/devel/2019b/branfosj-eb-2/EL7/EL7-power9/software/GCCcore/8.3.0/include/c++/8.3.0/cmath:585:31: error: cannot convert int to __vector(4) __bool int in return
   { return __builtin_isinf(__x); }
```
https://bugs.freedesktop.org/show_bug.cgi?id=68504 talks about this bug. Other option is to replace `-std=c++11` with `-std=gnu++11`.

**Comment by branfosj** [comment]
Test report by @branfosj
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
bear-pg0211u03a.bear.cluster - Linux centos linux 7.7.1908, Intel(R) Xeon(R) Gold 6248 CPU @ 2.50GHz, Python 2.7.5
See https://gist.github.com/9eff352ab58a8ca5a8c46f2a8787fd09 for a full test report.

**Comment by branfosj** [comment]
Test report by @branfosj
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in this PR)
bear-pg0305u03a.bear.cluster - Linux RHEL 7.6, 8335-GTX, Python 2.7.5
See https://gist.github.com/b00d7229a94f49e404c20599e9a015e0 for a full test report.

**Comment by branfosj** [comment]
Test report by @branfosj
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in this PR)
bear-pg0212u15b.bear.cluster - Linux centos linux 7.7.1908, Intel(R) Xeon(R) CPU E5-2640 v4 @ 2.40GHz, Python 2.7.5
See https://gist.github.com/83e55e18d8e6bf49a0c0e92d61fc8c90 for a full test report.

**Comment by branfosj** [comment]
Test report by @branfosj
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in this PR)
bear-pg0305u03a.bear.cluster - Linux RHEL 7.6, 8335-GTX, Python 2.7.5
See https://gist.github.com/cec23afc417028b8e6c9132300d0b549 for a full test report.

**Comment by branfosj** [comment]
Test report by @branfosj
**SUCCESS**
Build succeeded for 2 out of 2 (1 easyconfigs in this PR)
bb2c1a09.bb2.cluster - Linux centos linux 7.7.1908, Intel(R) Xeon(R) CPU E5-2660 0 @ 2.20GHz, Python 2.7.5
See https://gist.github.com/023c0b92ba1b3fe74feffd5c87c5f39e for a full test report.

**Comment by boegel** [comment]
> Other option is to replace `-std=c++11` with `-std=gnu++11`.

@branfosj You should be able to do that via `toolchainopts`:

```python
toolchainopts = {'cstd': 'gnu++11'}
```

I think that's better than adding a patch file that we'll need to maintain...

**Comment by branfosj** [comment]
> > Other option is to replace `-std=c++11` with `-std=gnu++11`.
> 
> @branfosj You should be able to do that via `toolchainopts`:
> 
> ```python
> toolchainopts = {'cstd': 'gnu++11'}
> ```
> 
> I think that's better than adding a patch file that we'll need to maintain...

Sadly we are battling some hard-coding. By adding `toolchainopts` I can remove 1/3 of the patch, but the other two sections are still needed.

**Comment by branfosj** [comment]
Test report by @branfosj
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in this PR)
bear-pg0305u05a.bear.cluster - Linux RHEL 7.6, 8335-GTX, Python 2.7.5
See https://gist.github.com/e23b434c2ca716320259c39cd4488374 for a full test report.

**Comment by branfosj** [comment]
Test report by @branfosj
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in this PR)
bear-pg0212u15b.bear.cluster - Linux centos linux 7.7.1908, Intel(R) Xeon(R) CPU E5-2640 v4 @ 2.40GHz, Python 2.7.5
See https://gist.github.com/b6b8ac3ca2e2d4e3ba283da13feb2f4a for a full test report.

**Comment by branfosj** [comment]
OK, I've done some more testing. An alternative patch is:
```patch
diff -aur pocl-1.4.orig/include/CL/cl_platform.h pocl-1.4/include/CL/cl_platform.h
--- pocl-1.4.orig/include/CL/cl_platform.h      2020-01-03 09:55:56.986465000 +0000
+++ pocl-1.4/include/CL/cl_platform.h   2020-01-03 09:59:18.058173021 +0000
@@ -356,6 +356,8 @@
 /* Define basic vector types */
 #if defined( __VEC__ )
    #include <altivec.h>   /* may be omitted depending on compiler. AltiVec spec provides no way to detect whether the header is required. */
+   #undef bool
+   #undef vector
    typedef __vector unsigned char     __cl_uchar16;
    typedef __vector signed char       __cl_char16;
    typedef __vector unsigned short    __cl_ushort8;
```

Using this does also not involve setting `toolchainopts`. This seems a better, as it is a smaller patch. Is this preferable?

**Comment by branfosj** [comment]
Also, upstream bug report: https://github.com/pocl/pocl/issues/800

**Comment by boegel** [comment]
> OK, I've done some more testing. An alternative patch is:
> 
> ```diff
> diff -aur pocl-1.4.orig/include/CL/cl_platform.h pocl-1.4/include/CL/cl_platform.h
> --- pocl-1.4.orig/include/CL/cl_platform.h      2020-01-03 09:55:56.986465000 +0000
> +++ pocl-1.4/include/CL/cl_platform.h   2020-01-03 09:59:18.058173021 +0000
> @@ -356,6 +356,8 @@
>  /* Define basic vector types */
>  #if defined( __VEC__ )
>     #include <altivec.h>   /* may be omitted depending on compiler. AltiVec spec provides no way to detect whether the header is required. */
> +   #undef bool
> +   #undef vector
>     typedef __vector unsigned char     __cl_uchar16;
>     typedef __vector signed char       __cl_char16;
>     typedef __vector unsigned short    __cl_ushort8;
> ```
> 
> Using this does also not involve setting `toolchainopts`. This seems a better, as it is a smaller patch. Is this preferable?

Yeah, let's go with that...

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in this PR)
node2587.golett.os - Linux centos linux 7.7.1908, Intel(R) Xeon(R) CPU E5-2680 v3 @ 2.50GHz, Python 2.7.5
See https://gist.github.com/1024f76a0b45e80f02c920e691197113 for a full test report.

**Comment by branfosj** [comment]
Test report by @branfosj
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in this PR)
bear-pg0306u07a.bear.cluster - Linux RHEL 7.6, 8335-GTX, Python 2.7.5
See https://gist.github.com/77d191fc8b9caf549de1fac9015b052a for a full test report.

**Comment by branfosj** [comment]
Test report by @branfosj
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in this PR)
bear-pg0212u15a.bear.cluster - Linux centos linux 7.7.1908, Intel(R) Xeon(R) CPU E5-2640 v4 @ 2.40GHz, Python 2.7.5
See https://gist.github.com/1b2efb6596be4ca2753afe3a9c9a39e8 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in this PR)
generoso - Linux centos linux 7.6.1810, Intel(R) Xeon(R) CPU E5-2660 v4 @ 2.00GHz, Python 3.6.8
See https://gist.github.com/ebba79be0739fb3a334a24f85b466acd for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in this PR)
node3159.skitty.os - Linux centos linux 7.7.1908, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz, Python 3.6.8
See https://gist.github.com/ac6ff4666cf0089cdcf48e441d2f8fed for a full test report.

**Comment by boegel** [comment]
Going in, thanks @branfosj!

**Pull request merged**
