### PR TITLE
{lib}[GCCcore/12.3.0,gfbf/2023a] multiprocess v0.70.15

### PR DESCRIPTION
**Pull request by NPotvin**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by jfgrimm** [comment]
Test report by @jfgrimm
**FAILED**
Build succeeded for 1 out of 2 (1 easyconfigs in total)
node091.viking2.yor.alces.network - Linux Rocky Linux 8.8, x86_64, AMD EPYC 7643 48-Core Processor, Python 3.6.8
See https://gist.github.com/jfgrimm/404667c4208b3aa654b2fb90b2eb0d66 for a full test report.

**Comment by jfgrimm** [comment]
@NPotvin the `dill` requirement was only bumped to `0.3.8` in `0.70.16` (commit https://github.com/uqfoundation/multiprocess/commit/b3457a5648263c46dcd2c62672f79d9cc73735b5), I would suggest dropping this to `0.70.15` instead

**Comment by jfgrimm** [comment]
Test report by @jfgrimm
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
node091.viking2.yor.alces.network - Linux Rocky Linux 8.8, x86_64, AMD EPYC 7643 48-Core Processor, Python 3.6.8
See https://gist.github.com/jfgrimm/6e1f056b7f558c47eeda8ce8856a7b2c for a full test report.

**Comment by jfgrimm** [comment]
@boegelbot: please test @ jsc-zen3

**Review by Micket — APPROVED** [review]
lgtm

**Comment by Micket** [comment]
@boegelbot: please test @ generoso

**Comment by Micket** [comment]
Test report by @Micket
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
vera-skylake-build - Linux Rocky Linux 8.9, x86_64, Intel Xeon Processor (Skylake, IBRS, no TSX), Python 3.6.8
See https://gist.github.com/Micket/6b32360fa09e7a50c7b6c6e2ceda9999 for a full test report.

**Pull request merged**
