### PR TITLE
{bio}[foss/2019b] RSEM v1.3.3

### PR DESCRIPTION
**Pull request by robqiao**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by verdurin** [comment]
Test report by @verdurin
**SUCCESS**
Build succeeded for 2 out of 2 (1 easyconfigs in this PR)
easybuild.novalocal - Linux centos linux 7.8.2003, x86_64, Intel Xeon Processor (Skylake, IBRS), Python 2.7.5
See https://gist.github.com/455a3cfd62c8536e241879eabb86d934 for a full test report.

**Comment by verdurin** [comment]
@robqiao Looks okay to me. Any specific reason for the "TBC"?

**Comment by verdurin** [comment]
Does look as though some of the download links may need to be updated cf. http://daehwankimlab.github.io/hisat2/download/#version-hisat2-220

**Comment by verdurin** [comment]
@robqiao any updates on the various issues here?

**Comment by robqiao** [comment]
> 
> 
> @robqiao any updates on the various issues here?

@verdurin Thx for the reminder. It seems passing.

**Comment by robqiao** [comment]
> 
> 
> > @robqiao any updates on the various issues here?
> 
> @verdurin Thx for the reminder. It now seems passing.

@verdurin  @smoors do a triggered rebuild on this one?

**Comment by verdurin** [comment]
@robqiao actually I tried your `HISAT2` locally and one of our users has reported that various scripts are missing, namely:
```
extract_exons.py
extract_splice_sites.py
hisat2_extract_exons.py
hisat2_extract_snps_haplotypes_UCSC.py
hisat2_extract_snps_haplotypes_VCF.py
hisat2_extract_splice_sites.py
hisat2_read_statistics.py
hisat2-repeat
hisat2-repeat-debug
hisat2_simulate_reads.py
hisatgenotype_build_genome.py
hisatgenotype_extract_reads.py
hisatgenotype_extract_vars.py
hisatgenotype_hla_cyp.py
hisatgenotype_locus.py
hisatgenotype_modules/
hisatgenotype.py
hisatgenotype_scripts/
scripts/
```

**Comment by verdurin** [comment]
@robqiao see #11564

**Comment by robqiao** [comment]
> 
> 
> @robqiao actually I tried your `HISAT2` locally and one of our users has reported that various scripts are missing, namely:
> 
> ```
> extract_exons.py
> extract_splice_sites.py
> hisat2_extract_exons.py
> hisat2_extract_snps_haplotypes_UCSC.py
> hisat2_extract_snps_haplotypes_VCF.py
> hisat2_extract_splice_sites.py
> hisat2_read_statistics.py
> hisat2-repeat
> hisat2-repeat-debug
> hisat2_simulate_reads.py
> hisatgenotype_build_genome.py
> hisatgenotype_extract_reads.py
> hisatgenotype_extract_vars.py
> hisatgenotype_hla_cyp.py
> hisatgenotype_locus.py
> hisatgenotype_modules/
> hisatgenotype.py
> hisatgenotype_scripts/
> scripts/
> ```

Thx @verdurin. It looks like you have already included those in PR #11564. 
Those are new implementations which included from v2. I should really include those, my apology.

**Comment by robqiao** [comment]
Thx @verdurin.  HISAT2 is now updated with PR#11564

**Comment by boegel** [comment]
@robqiao Please sync your pull request with the current `develop` branch (via `eb --sync-pr-with-develop 10988` for example).
You should also update it to use the HISAT v2.2.1 from #11564, and remove the HISAT 2.2.0 easyconfig file since it serves no purpose anymore?

**Comment by robqiao** [comment]
> 
> 
> @robqiao Please sync your pull request with the current `develop` branch (via `eb --sync-pr-with-develop 10988` for example).
> You should also update it to use the HISAT v2.2.1 from #11564, and remove the HISAT 2.2.0 easyconfig file since it serves no purpose anymore?

Thx @boegel. It seems fixed.

**Comment by robqiao** [comment]
@boegel @smoors Can we check and merge this PR?

**Comment by smoors** [comment]
@boegelbot please test @ generoso

**Comment by smoors** [comment]
Test report by @smoors
**SUCCESS**
Build succeeded for 4 out of 4 (3 easyconfigs in total)
node377.hydra.os - Linux centos linux 7.9.2009, x86_64, Intel(R) Xeon(R) Gold 6148 CPU @ 2.40GHz (skylake_avx512), Python 2.7.5
See https://gist.github.com/7f8a0e687c1ad3361e7ed3c3dd9f3828 for a full test report.

**Review by smoors — APPROVED** [review]
lgtm

**Comment by smoors** [comment]
Going in, thanks @robqiao!

**Pull request merged**
