### PR TITLE
{chem}[foss,intel/2020b] ASE v3.20.1, GPAW v20.10.0, spglib-python v1.16.0, ... w/ Python 3.8.6

### PR DESCRIPTION
**Pull request by schiotz**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by schiotz** [comment]
I have edited the title to show that builds for the Intel toolchain are included as well.

There is a minor difference between the foss and intel versions: GPAW does not link with libwdvxc using the intel toolchain, as libvdwxc is incompatible with the Intel MKL.  It requires a function in FFTW which is not present in MKL, and linking to both libraries cause core dumps, probably due to conflicting names.

Unlike previous versions, this version of ASE depends on spglib-python as some optional functionality in ASE uses spglib.  Normally, I would just have added spglib to the bundle, but as it already exists as an independent .eb I updated it to 2020b.

**Comment by lexming** [comment]
Test report by @lexming
**SUCCESS**
Build succeeded for 14 out of 14 (7 easyconfigs in total)
node352.hydra.os - Linux centos linux 7.9.2009, x86_64, Intel(R) Xeon(R) Gold 6148 CPU @ 2.40GHz, Python 2.7.5
See https://gist.github.com/93615038ea7bfaa6517569ace5faa6da for a full test report.

**Comment by lexming** [comment]
Test report by @lexming
**SUCCESS**
Build succeeded for 18 out of 18 (7 easyconfigs in total)
node114.hydra.os - Linux centos linux 7.9.2009, x86_64, Intel(R) Xeon(R) CPU E5-2680 v2 @ 2.80GHz, Python 2.7.5
See https://gist.github.com/6eb7fe43ba084c2ca5daee26d7efa4d2 for a full test report.

**Review by lexming — CHANGES_REQUESTED** [review]
This PR works well. I have a few suggestion to improve it. Please check my PR https://github.com/schiotz/easybuild-easyconfigs/pull/2 with the following changes
* Add direct dependency on Flask in easyconfigs of ASE, this simplifies a lot the bundle for ASE
* Cleanup of easyconfigs of spglib-python, mainly removing the sanity checks which are default
* Add comment about libvdwxc to GPAW-20.10.0-intel-2020b.eb

**Comment by schiotz** [comment]
@lexming Thank you very much for your contributions!

**Comment by lexming** [comment]
Test report by @lexming
**SUCCESS**
Build succeeded for 8 out of 8 (8 easyconfigs in total)
node367.hydra.os - Linux centos linux 7.9.2009, x86_64, Intel(R) Xeon(R) Gold 6148 CPU @ 2.40GHz, Python 2.7.5
See https://gist.github.com/84676abfe22486cf102b8e8a32acfdfd for a full test report.

**Comment by lexming** [comment]
Test report by @lexming
**SUCCESS**
Build succeeded for 8 out of 8 (8 easyconfigs in total)
node115.hydra.os - Linux centos linux 7.9.2009, x86_64, Intel(R) Xeon(R) CPU E5-2680 v2 @ 2.80GHz, Python 2.7.5
See https://gist.github.com/7882fde0afa3e723b7c99ea15b097e0b for a full test report.

**Review by lexming — APPROVED** [review]
LGTM

**Comment by lexming** [comment]
Going in, thanks @schiotz !

**Pull request merged**
