### PR TITLE
{bio}[system/system] FreeSurfer v7.2.0

### PR DESCRIPTION
**Pull request by sassy-crick**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by robert-mijakovic** [comment]
@boegelbot please test @ generoso

**Comment by robert-mijakovic** [comment]
Test report by @robert-mijakovic
**FAILED**
Build succeeded for 0 out of 3 (3 easyconfigs in total)
mel0429 - Linux centos linux 8.4.2105, x86_64, AMD EPYC 7H12 64-Core Processor (zen2), Python 3.6.8
See https://gist.github.com/14c0b0008ecaebf43771e7b7b6badaf7 for a full test report.

**Comment by robert-mijakovic** [comment]
```
== 2021-12-04 09:16:22,710 easyblock.py:3993 WARNING build failed (first 300 chars): Checksum verification for /project/boegelbot/sources/f/FreeSurfer/freesurfer-linux-centos8_x86_64-7.2.0.tar.gz using 6098b166fee8644f44f9ec88f3ffe88d05f2bc033cca60443e99e3e56f2e166b failed. 
```
I guess you should update the checksum for centos8 too.
https://github.com/easybuilders/easybuild-easyconfigs/pull/14491

**Comment by robert-mijakovic** [comment]
```
$ sha256sum freesurfer-linux-centos8_x86_64-7.2.0.tar.gz
1eecbe0f027b95ee9ec7cce4c0846e14e7bf623fa1937ac57911a26f8f23d3e6  freesurfer-linux-centos8_x86_64-7.2.0.tar.gz
```

**Comment by robert-mijakovic** [comment]
Test report by @robert-mijakovic
**FAILED**
Build succeeded for 2 out of 3 (3 easyconfigs in total)
mel0429 - Linux centos linux 8.4.2105, x86_64, AMD EPYC 7H12 64-Core Processor (zen2), Python 3.6.8
See https://gist.github.com/f0d634fcbdf0076bca4ddf4ab78c31df for a full test report.

**Comment by sassy-crick** [comment]
I have corrected the checksums for `FreeSurfer-7.2.0-centos8_x86_64.eb`. Apologies for that, this slipped through.

**Comment by smoors** [comment]
@boegelbot: please test @ generoso

**Comment by smoors** [comment]
Test report by @smoors
**SUCCESS**
Build succeeded for 3 out of 3 (3 easyconfigs in total)
node301.hydra.os - Linux centos linux 7.9.2009, x86_64, Intel(R) Xeon(R) Gold 6148 CPU @ 2.40GHz (skylake_avx512), Python 2.7.5
See https://gist.github.com/e4883543086d0d2f9ddeca6ec663b96d for a full test report.

**Review by smoors — APPROVED** [review]
lgtm

**Comment by smoors** [comment]
Going in, thanks @sassy-crick!

**Pull request merged**
