### PR TITLE
{chem}[foss/2020a] pyobjcryst v2.1.0.post2, libobjcryst v2017.2.2 w/ Python 3.8.2 (WIP)

### PR DESCRIPTION
**Pull request by boegel**
(created using `eb --new-pr`)

This is WIP because `libobjcryst` isn't using the correct compiler flags...

### CODE REVIEW

**Comment by lexming** [comment]
Test report by @lexming
**SUCCESS**
Build succeeded for 3 out of 3 (2 easyconfigs in this PR)
node364.hydra.os - Linux centos linux 7.7.1908, x86_64, Intel(R) Xeon(R) Gold 6148 CPU @ 2.40GHz, Python 2.7.5
See https://gist.github.com/d84df1b48d64bcf1d0fa58aa78933b7b for a full test report.

**Comment by verdurin** [comment]
Test report by @verdurin
**SUCCESS**
Build succeeded for 4 out of 4 (2 easyconfigs in total)
nuc.lan - Linux Fedora 32, x86_64, Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz, Python 3.8.6
See https://gist.github.com/ecd6c24f403748b1180d8b28290cac0d for a full test report.

**Comment by verdurin** [comment]
@boegel any progress on the compiler flags?

**Comment by branfosj** [comment]
As this PR is WIP or draft and has not been updated in over a year I have closed it. If you work on this again then please reopen the PR.

**Pull request closed without merging**
