### PR TITLE
{lang}[intel/2018a] R v3.4.4

### PR DESCRIPTION
**Pull request by boegel**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by smoors** [comment]
@boegel is there a reason why several extensions in the 3.4.3 version are not present anymore?

**Comment by smoors** [comment]
missing extensions are:
feather
tidyverse
dummies
SimSeq
uniqueAtomMat
PoissonSeq
aod
cghFLasso

**Comment by boegel** [comment]
I suspect this was done unintentionally by @edmondac in #5974 (for `iomkl/2018a`)... Can you clarify @edmondac?

**Comment by edmondac** [comment]
@boegel @smoors I guess I must have started working on the R 3.4.3 iomkl before Jan 22, and for some reason didn't notice the updates to the intel one made afterwards. See https://github.com/easybuilders/easybuild-easyconfigs/commits/master/easybuild/easyconfigs/r/R/R-3.4.3-intel-2017b-X11-20171023.eb

I'd be pleased if those extensions were added to the R 3.4.4 easyconfigs.

**Comment by boegel** [comment]
OK, I'll make sure they're included consistently for R 3.4.4, thanks for clarifying @edmondac!

**Comment by boegel** [comment]
Missing extensions added back to R 3.4.4 built with `iomkl/2018a` in #6096, I'll add them back in this PR too.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in this PR)
node2495.golett.os - Linux centos linux 7.4.1708, Intel(R) Xeon(R) CPU E5-2680 v3 @ 2.50GHz, Python 2.7.5
See https://gist.github.com/8cb3b7b3f3c1001fc1df13da18c62950 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in this PR)
node2047.delcatty.os - Linux centos linux 7.4.1708, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.7.5
See https://gist.github.com/0ae847af48d51320f8a0386f46b44c07 for a full test report.

**Comment by boegel** [comment]
@vanzod Same problem here as in #6096: `caught illegal operation` when building `rgl`... Any idea what is causing this?

**Comment by verdurin** [comment]
Test report by @verdurin
**SUCCESS**
Build succeeded for 1 out of 1 (2 easyconfigs in this PR)
rescomp2 - Linux centos 6.8, Intel(R) Xeon(R) CPU E5-2650 v2 @ 2.60GHz, Python 2.7.11
See https://gist.github.com/20d58d79d6c70770723592889af00c9c for a full test report.

**Comment by reedts** [comment]
I just tried to build from this PR but had a checksum mismatch for the extensions `clValid` and `penalized`.
@verdurin For you this obviously build fine?

**Comment by boegel** [comment]
@reedts Is that for fresh downloads, or copies of the tarball you already had?

**Comment by reedts** [comment]
@boegel This time, it obviously affects the tarballs that I already downloaded two weeks ago and reside in the easybuild source directory since then. I manually made fresh downloads to check the checksums of the tarballs and they are identical to the ones of the tarballs downloaded by easybuild. They differ however from the checksums used in this easyconfig. I also have the same issue, though for 10 or so extensions, with `R-3.4.3-intel-2017b-X11-20171023.eb` which is already merged.

**Comment by iancost** [comment]
I tried the same build against , and found a number of checksums that differ, here is a list:

**Comment by boegel** [comment]
I just ran `eb --inject-checksums` again from scratch on `R-3.4.3-foss-2017b-X11-20171023.eb`, which resulted in the diff below.

@iancost Any idea why you weren't hitting faulty checksums for `cluster` & `Hmisc`? Which SHA256 checksums do you have for `cluster_2.0.6.tar.gz` & `Hmisc_4.0-3.tar.gz`?

```diff
diff --git a/easybuild/easyconfigs/r/R/R-3.4.3-foss-2017b-X11-20171023.eb b/easybuild/easyconfigs/r/R/R-3.4.3-foss-2017b-X11-20171023.eb
index 31016118f..8993492b5 100644
--- a/easybuild/easyconfigs/r/R/R-3.4.3-foss-2017b-X11-20171023.eb
+++ b/easybuild/easyconfigs/r/R/R-3.4.3-foss-2017b-X11-20171023.eb
@@ -254,7 +254,7 @@ exts_list = [
         'checksums': ['acd3b00a4a3c8d61681620f11eb5d3b266ca911c0df09470bdcfeae1fcbddec8'],
     }),
     ('subplex', '1.4-1', {
-        'checksums': ['d5caec949f62a51e4e6d706e80ca714a537e68213151439cdd214c7c293b91cc'],
+        'checksums': ['94b7b961aaa229a6f025151191ed50272af1394be69f1c41146b9e8c786caec6'],
     }),
     ('stringi', '1.1.6', {
         'checksums': ['9590360b96627b18d7bed273deedabda4283dbae7d41c0a0ba78a58e6aa95188'],
@@ -308,7 +308,7 @@ exts_list = [
         'checksums': ['780695323dfadac108fb27000011c734e2927b1e0f069f247d65d27994c67ec2'],
     }),
     ('Matrix', '1.2-12', {
-        'checksums': ['16e51aef69dca94dc4fcba8aa35a0039d9d0e6abd9cc017c095e954e1e2ca4f2'],
+        'checksums': ['0d0e36e9742ea86355b2611ed94552946093b027e5eca2b8656abb4401838291'],
     }),
     ('png', '0.1-7', {
         'checksums': ['e269ff968f04384fc9421d17cfc7c10cf7756b11c2d6d126e9776f5aca65553c'],
@@ -413,7 +413,7 @@ exts_list = [
         'checksums': ['04f6fe7452ea63d1f2a77960934666132d2f90f139529515e795e35fed73af2e'],
     }),
     ('mgcv', '1.8-22', {
-        'checksums': ['5a3bb235cc798f617392ef4996f2d502233998b041db2a68377f3cea94b98694'],
+        'checksums': ['d4af7767e097ebde91c61d5ab4c62975dcb6b4ed6f545c09f5276a44ebc585cf'],
     }),
     ('robustbase', '0.92-8', {
         'checksums': ['bcbf894c7d3916fc92064f0f9152f6347560c9b98ec81d57b5705f8421b31e20'],
@@ -464,7 +464,7 @@ exts_list = [
         'checksums': ['543fd8d8dc8d4b6079ebf491cf97f27d6225e1a6e65d8fd48553ada23ba88d8f'],
     }),
     ('cluster', '2.0.6', {
-        'checksums': ['f424b87f10595ed358b1ac80471b520ab9c767a4d203663c25b177c8ce5f8ffc'],
+        'checksums': ['b53bb0eed64b79767a6e0d203fdc82f9fdb5c9692f30316fbe1c5b196a62fd81'],
     }),
     ('gclus', '1.3.1', {
         'checksums': ['d6994ee264b464503db005450153973d75eba502e4caaaa6ff99cb95e4376a09'],
@@ -677,7 +677,7 @@ exts_list = [
         'checksums': ['8ef7cc5c641a8424400d9767475ca9b745f190122d800425fae5bd68facf1874'],
     }),
     ('Hmisc', '4.0-3', {
-        'checksums': ['1c612a72eeb618e624f131475f15d4a15b7e2044ad2045d56bf49aa7be3af1a8'],
+        'checksums': ['5d395286d699bcabb6460c91798019d84b1cfa7a033841aa3ac5a02f4407e4fd'],
     }),
     ('fastcluster', '1.1.24', {
         'checksums': ['82c939b79dbaf00c79b01f19b09a8fadb9a949397b8f65bc861c552e0485b995'],
@@ -698,7 +698,7 @@ exts_list = [
         'checksums': ['be8718d24cd10f6e323dce91b15fc40ed88bccaa26acf3192d5e38fe33e15f26'],
     }),
     ('NMF', '0.20.6', {
-        'checksums': ['dfccd4b4d6ec90cd7628fd128d2456d792f406cee4d32b13448dcb0ffe4ab056'],
+        'checksums': ['a6539149d7f912057e2f87a78c0fa62dc44109609b3cf6180359c888db70cb7e'],
     }),
     ('irlba', '2.3.1', {
         'checksums': ['6082f8b5e32e9541747f0ac7d59f9e5a708b291492e9a21a5e4b9753e7ff94b5'],
@@ -1016,7 +1016,7 @@ exts_list = [
         'checksums': ['49da299139a47171c5b4ccdea79ffbbc152894e05d552e676f135147c0c9b372'],
     }),
     ('clValid', '0.6-6', {
-        'checksums': ['bcf781238a2a831a7ec8909d27251731e3115a0541a9ea9795e5ec4d903938d1'],
+        'checksums': ['c13ef1b6258e34ba53615b78f39dbe4d8ba47b976b3c24a3eedaecf5ffba19ed'],
     }),
     ('matrixStats', '0.52.2', {
         'checksums': ['39da6aa6b109f89a141dab8913d981abc4fbd3f8be9e206f92e382cc5270d2a5'],
@@ -1329,7 +1329,7 @@ exts_list = [
         'checksums': ['c007d6eaf6335a15c1912b0804276ff39abce27b7a61539a91b8fda653629252'],
     }),
     ('penalized', '0.9-50', {
-        'checksums': ['66ed84b967f70fd49702318e43e129c2ff60bb0631b81fe2617671d1ebbbc060'],
+        'checksums': ['c12b3259e019f91c7bd02827ea3a27f842d9c15950fa6cc114dff23c89c297d1'],
     }),
     ('clusterRepro', '0.5-1.1', {
         'checksums': ['b7fcb9db0c762a2e6e22a0a0689affd73504c56f13c13b04272a946630334e6f'],
```

**Comment by iancost** [comment]
Hi Kenneth,

I missed those when I pasted the contents in to the list, FWIW here are my 
other 2 entries:

    ('cluster', '2.0.6', {
        #'checksums': 
['f424b87f10595ed358b1ac80471b520ab9c767a4d203663c25b177c8ce5f8ffc'],
        'checksums': 
['b53bb0eed64b79767a6e0d203fdc82f9fdb5c9692f30316fbe1c5b196a62fd81'],
    }),

    ('Hmisc', '4.0-3', {
        #'checksums': 
['1c612a72eeb618e624f131475f15d4a15b7e2044ad2045d56bf49aa7be3af1a8'],
        'checksums': 
['5d395286d699bcabb6460c91798019d84b1cfa7a033841aa3ac5a02f4407e4fd'],
    }),

Thanks,
Ian Costello

Senior Advanced Scientific Computing Specialist |  Agricultural Research
Department of Economic Development, Jobs, Transport and Resources
AgriBio,  Centre for AgriBioscience
5 Ring Road,  Bundoora   VIC  3083
Ph:   +61 3 9032 7018  |  Mb:  0417 508 522

**Comment by reedts** [comment]
@boegel Seems to work for me now!

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 16 out of 16 (2 easyconfigs in this PR)
node2463.golett.os - Linux centos linux 7.4.1708, Intel(R) Xeon(R) CPU E5-2680 v3 @ 2.50GHz, Python 2.7.5
See https://gist.github.com/94b1dfdf9c74fef3f943bb9497a4f7f4 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in this PR)
node2012.delcatty.os - Linux centos linux 7.4.1708, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.7.5
See https://gist.github.com/11d0abcc1d9f5eb9e53697b9a6ed1021 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in this PR)
node2462.golett.os - Linux centos linux 7.4.1708, Intel(R) Xeon(R) CPU E5-2680 v3 @ 2.50GHz, Python 2.7.5
See https://gist.github.com/9c975a24f173ebca7485e377163be47b for a full test report.

**Comment by vanzod** [comment]
Test report by @vanzod
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in this PR)
cermis - Linux debian 9.4, Intel(R) Xeon(R) CPU           E5620  @ 2.40GHz, Python 2.7.13
See https://gist.github.com/867ee182aba24e1f5d07f67b78c06103 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in this PR)
node2095.delcatty.os - Linux centos linux 7.4.1708, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.7.5
See https://gist.github.com/a5b88380351bf0e3b704277d15f74f97 for a full test report.

**Comment by vanzod** [comment]
Going in, thanks @boegel!

**Pull request merged**
