### PR TITLE
{lang}[GCCcore/8.3.0] move intervaltree and sortedcontainers to main Python easyconfigs

### PR DESCRIPTION
**Pull request by lexming**
(created using `eb --new-pr`)

We have several packages bundling `sortedcontainers` and `intervaltree`. It would be useful to have those in the main easyconfigs for Python.

PR #10970 has these changes for more recent packages in `GCCcore/9.3.0`

### CODE REVIEW

**Comment by lexming** [comment]
Test report by @lexming
**SUCCESS**
Build succeeded for 7 out of 7 (7 easyconfigs in this PR)
node320.hydra.os - Linux centos linux 7.7.1908, x86_64, Intel(R) Xeon(R) Gold 6148 CPU @ 2.40GHz, Python 2.7.5
See https://gist.github.com/1c3c68e2a25899b9e6471d35c887475e for a full test report.

**Comment by lexming** [comment]
@verdurin follow up to #10943, this one is ready for tests

**Comment by verdurin** [comment]
Test report by @verdurin
**FAILED**
Build succeeded for 8 out of 9 (7 easyconfigs in this PR)
easybuild.novalocal - Linux centos linux 7.8.2003, x86_64, Intel Xeon Processor (Skylake, IBRS), Python 2.7.5
See https://gist.github.com/5ff12786772def76cf34ecd7fb6219d0 for a full test report.

**Comment by verdurin** [comment]
@lexming thanks. I see this error with `FLAIR` when testing with `--skip`:
```
== 2020-07-13 14:03:45,320 build_log.py:169 ERROR EasyBuild crashed with an error (at easybuild/base/exceptions.py:124 in __init__): Skipping of extensions, but no exts_filter set in easyconfig (at easybuild/framework/easyblock.py:1549 in skip_extensions)
```

**Comment by lexming** [comment]
@verdurin fixed :+1: since the easyconfig of `FLAIR` is a tarball with extensions it needs to explicitly define `exts_filter`

**Comment by smoors** [comment]
Test report by @smoors
**SUCCESS**
Build succeeded for 10 out of 10 (7 easyconfigs in this PR)
node381.hydra.os - Linux centos linux 7.7.1908, x86_64, Intel(R) Xeon(R) Gold 6148 CPU @ 2.40GHz (skylake_avx512), Python 2.7.5
See https://gist.github.com/cfaf75818011d11976814279d62ec3bc for a full test report.

**Pull request merged**
