### PR TITLE
{vis}[fosscuda/2018b] wxPython v4.0.4

### PR DESCRIPTION
**Pull request by akesandgren**
(created using `eb --new-pr`)
Requires https://github.com/easybuilders/easybuild-easyblocks/pull/1635
Depends on https://github.com/easybuilders/easybuild-easyconfigs/pull/7678

### CODE REVIEW

**Comment by akesandgren** [comment]
Test report by @akesandgren
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
b-an03.hpc2n.umu.se - Linux ubuntu 16.04, Intel(R) Xeon(R) CPU E5-2690 v4 @ 2.60GHz, Python 2.7.12
See https://gist.github.com/8520c2464d8a602e50c39ea0f6bd815f for a full test report.

**Comment by akesandgren** [comment]
Test report by @akesandgren
**SUCCESS**
Build succeeded for 2 out of 2 (1 easyconfigs in this PR)
b-an03.hpc2n.umu.se - Linux ubuntu 16.04, Intel(R) Xeon(R) CPU E5-2690 v4 @ 2.60GHz, Python 2.7.12
See https://gist.github.com/61912388171be4dc39f99e655c27ab5b for a full test report.

**Comment by akesandgren** [comment]
Ignore this for the time being, it should be moved down to GCC or perhaps GCCcore level.

**Comment by boegel** [comment]
closing due to deprecated toolchain and PRs that provide dependencies (like #7678) being closed already

we also already have PRs merged for more recent versions of wxPython (like #10778)

**Pull request closed without merging**
