### PR TITLE
{devel}[GCCcore/10.2.0] flatbuffers v1.12.0

### PR DESCRIPTION
**Pull request by Micket**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by Micket** [comment]
Test report by @Micket
**FAILED**
Build succeeded for 0 out of 1 (1 easyconfigs in total)
vera-c1 - Linux centos linux 7.8.2003, x86_64, Intel Xeon Processor (Skylake), Python 2.7.5
See https://gist.github.com/9011d29001bc80d96003f680e5316d07 for a full test report.

**Comment by Micket** [comment]
Test report by @Micket
**FAILED**
Build succeeded for 0 out of 1 (1 easyconfigs in total)
vera-c1 - Linux centos linux 7.8.2003, x86_64, Intel Xeon Processor (Skylake), Python 2.7.5
See https://gist.github.com/f493951784cf6cb7e953d21c18e87819 for a full test report.

**Comment by Micket** [comment]
I'm considering the option of just waiting for this until we're ready for new tensorflow and maybe they will just make a release with the fix in instead of trying to patch this mess.

**Comment by branfosj** [comment]
@Micket We've merged #12148 which includes `flatbuffers-1.12.0-GCCcore-10.2.0.eb` so I've closed this PR.

**Pull request closed without merging**
