### PR TITLE
{bio}[foss/2021a] CellBender v0.2.1 w/ Python 3.9.5

### PR DESCRIPTION
**Pull request by sassy-crick**
(created using `eb --new-pr`)

Requires:
-  [x] PR #16521

### CODE REVIEW

**Comment by sassy-crick** [comment]
@boegelbot please test @ generoso

**Comment by sassy-crick** [comment]
It looks like some changes were done of the original tarball, namely:
```
diff --git a/CellBender-0.2.1.old/docs/source/conf.py b/CellBender-0.2.1/docs/source/conf.py
index d00a3a4..f41e45d 100644
--- a/CellBender-0.2.1.old/docs/source/conf.py
+++ b/CellBender-0.2.1/docs/source/conf.py
@@ -64,8 +64,6 @@ html_theme = 'sphinx_rtd_theme'
 # so a file named "default.css" will overwrite the builtin "default.css".
 html_static_path = ['_static']
 html_favicon = '_static/design/favicon.ico'
-html_context = {
-    'css_files': [
-        '_static/theme_overrides.css',  # override wide tables in RTD theme
-        ],
-     }
+html_css_files = [
+    'theme_overrides.css',  # override wide tables in RTD theme
+]
diff --git a/CellBender-0.2.1.old/docs/source/installation/index.rst b/CellBender-0.2.1/docs/source/installation/index.rst
index 5ee2870..86beb63 100644
--- a/CellBender-0.2.1.old/docs/source/installation/index.rst
+++ b/CellBender-0.2.1/docs/source/installation/index.rst
@@ -11,7 +11,7 @@ The recommended installation is as follows. Create a conda environment and activ
 .. code-block:: console
 
   $ conda create -n CellBender python=3.7
-  $ source activate CellBender
+  $ conda activate CellBender
 
 Install the `pytables <https://www.pytables.org>`_ module:
 
diff --git a/CellBender-0.2.1.old/setup.py b/CellBender-0.2.1/setup.py
index f942692..88cdd20 100644
--- a/CellBender-0.2.1.old/setup.py
+++ b/CellBender-0.2.1/setup.py
@@ -24,7 +24,7 @@ install_requires = [
 
 setuptools.setup(
     name='cellbender',
-    version='0.2.0',
+    version='0.2.1',
     description='A software package for eliminating technical artifacts from '
                 'high-throughput single-cell RNA sequencing (scRNA-seq) data',
     long_description=readme(),
```
Thus the checksum was wrong.

**Comment by sassy-crick** [comment]
@boegelbot please test @ generoso

**Comment by sassy-crick** [comment]
@boegelbot please test @ generoso

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
node3309.joltik.os - Linux RHEL 8.8, x86_64, Intel(R) Xeon(R) Gold 6242 CPU @ 2.80GHz (cascadelake), 1 x NVIDIA Tesla V100-SXM2-32GB, 535.154.05, Python 3.6.8
See https://gist.github.com/boegel/d6fea5c13d7d5f6c5c74a911e257f4dc for a full test report.

**Review by boegel — APPROVED** [review]
lgtm

**Comment by boegel** [comment]
Going in, thanks @sassy-crick!

**Pull request merged**
