### PR TITLE
{lib}[gompi/2022a] mpi4py v3.1.4

### PR DESCRIPTION
**Pull request by sassy-crick**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by sassy-crick** [comment]
@boegelbot please test @ generoso

**Comment by bedroge** [comment]
Happy to review/merge this, but do note that for this toolchain `mpi4py` was still included with `SciPy-bundle`, and it's almost the same version:
https://github.com/easybuilders/easybuild-easyconfigs/blob/develop/easybuild/easyconfigs/s/SciPy-bundle/SciPy-bundle-2022.05-foss-2022a.eb#L62

**Comment by sassy-crick** [comment]
My wrong. Apologies. I did not suspect it to be in the `SciPy-bundle` so I never checked. I found some previous versions, including `mpi4py-3.1.4-gompi-2023a.eb` so I simply used that as a starting point. As I need  `SciPy-bundle`  anyway, we can close that PR. 
Thanks for looking into that so quickly, much appreciated.

**Comment by bedroge** [comment]
No problem!

In `2022b` this was removed from `SciPy-bundle` and moved to a separate easyconfig.

**Pull request closed without merging**
