### PR TITLE
add RISC-V support to UCX 1.15.0

### PR DESCRIPTION
**Pull request by bedroge**
Support for RISC-V has been added in 1.16.0, but I backported this to 1.15.0 using https://github.com/openucx/ucx/pull/9168.

~Requires #20428 as well.~
@SebastianAchilles let me know me that this worked without #20428 for him. I originally ran into the issue solved in #20428, so I assumed this was still necessary. However, it seems that it's indeed not really necessary, as the `autoreconf` command from this PR will apparently update the `config.guess` script to a newer version that does recognize RISC-V:
```
# before running autoreconf
$ grep timestamp config.guess
timestamp='2013-06-10'
$ grep riscv config.guess
$

# after running autoreconf
$ grep timestamp config.guess
timestamp='2021-06-03'
$ grep riscv config.guess 
    riscv32:Linux:*:* | riscv32be:Linux:*:* | riscv64:Linux:*:* | riscv64be:Linux:*:*)
```

### CODE REVIEW

**Comment by SebastianAchilles** [comment]
Test report by @sebastianachilles
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
arriesgado-5 - Linux Ubuntu 22.04, RISC-V-64, UNKNOWN (u74mc), Python 3.10.12
See https://gist.github.com/SebastianAchilles/42269c177e29c087e5ccb603ae29ed77 for a full test report.

**Comment by bedroge** [comment]
Test report by @bedroge
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
starfive - Linux Debian GNU/Linux n/a, RISC-V-64, UNKNOWN, Python 3.10.9
See https://gist.github.com/bedroge/f0d36c054c314f1725ede1cf17835ccd for a full test report.

**Comment by bedroge** [comment]
@boegelbot please test @ generoso

**Comment by bedroge** [comment]
Test report by @bedroge
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
starfive - Linux Debian GNU/Linux n/a, RISC-V-64, UNKNOWN, Python 3.10.9
See https://gist.github.com/bedroge/ce8aa4b8afe2924ef20ad9f4f6f88b8a for a full test report.

**Review by SebastianAchilles — APPROVED** [review]
lgtm

**Comment by SebastianAchilles** [comment]
Going in, thanks @bedroge!

**Pull request merged**
