### PR TITLE
{numlib}[foss/2023a] PETSc v3.19.4, Hypre v2.28.0, MUMPS v5.5.1, mpi4py v3.1.4, SuiteSparse v5.13.0, SuperLU_DIST v8.1.2, ParMETIS v4.0.3

### PR DESCRIPTION
**Pull request by maxim-masterov**
PETSc is not compatible with the latest releases of MUMPS, SuiteSparse and Hyper. So, I had to use older versions.

### CODE REVIEW

**Comment by boegel** [comment]
@boegelbot please test @ generoso

**Comment by boegel** [comment]
@maxim-masterov Do you have more information on the incompatibilities with latest versions of MUMPS, SuiteSparse, and Hypre?
In particular for Hypre, since we already have an easyconfig for Hypre 2.29.0 with `foss/2023a`

**Comment by maxim-masterov** [comment]
@boegel The supported versions used by PETSc are listed in the following files:
- [SuiteSparse.py](https://gitlab.com/petsc/petsc/-/blob/v3.19.4/config/BuildSystem/config/packages/SuiteSparse.py?ref_type=tags#L7)
- [MUMPS](https://gitlab.com/petsc/petsc/-/blob/v3.19.4/config/BuildSystem/config/packages/MUMPS.py?ref_type=tags#L6)
- [Hypre](https://gitlab.com/petsc/petsc/-/blob/v3.19.4/config/BuildSystem/config/packages/hypre.py?ref_type=tags#L7)

I tried to build PETSc with the most recent versions of these dependencies, but it failed badly. I don't remember exactly what the problem was with MUMPS and Hypre, but with SuiteSparse-7 it was something about changed/replaced/removed packages

**Comment by boegel** [comment]
Seems like this got superseded by:
* #19686

So I'll go ahead and close it...

**Pull request closed without merging**
