### PR TITLE
use `libidn2/2.3.7` as dependency for `GnuTLS/3.7.8` and delete `libidn2/2.3.2` (`GCCcore/12.3.0`)

### PR DESCRIPTION
**Pull request by branfosj**
(created using `eb --new-pr`)

fix the CI failure seen in https://github.com/easybuilders/easybuild-easyconfigs/actions/runs/9415898231/job/25937858835?pr=20769#step:8:147

### CODE REVIEW

**Comment by boegel** [comment]
@boegelbot please test @ generoso

**Comment by branfosj** [comment]
Test report by @branfosj
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
bear-pg0105u03a - Linux RHEL 8.6, x86_64, Intel(R) Xeon(R) Platinum 8360Y CPU @ 2.40GHz (icelake), Python 3.6.8
See https://gist.github.com/branfosj/da1b7b304d57802a4fdd868bfcdcebc0 for a full test report.

**Comment by boegel** [comment]
@boegelbot please test @ jsc-zen3

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
node3120.skitty.os - Linux RHEL 8.8, x86_64, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz, Python 3.6.8
See https://gist.github.com/boegel/4a81a5bff73af9ad7fcd9d361f9cb5eb for a full test report.

**Comment by boegel** [comment]
@boegelbot please test @ jsc-zen3

**Review by boegel — APPROVED** [review]
lgtm

**Pull request merged**
