### PR TITLE
update Hypre git location for PETSc 3.11.0 using downloaded dependencies

### PR DESCRIPTION
**Pull request by branfosj**
(created using `eb --new-pr`)

`PETSc-3.11.0-foss-2018b-downloaded-deps.eb` downloads various items during the install (as the name suggests). The Hypre github has moved, so the download fails.

edit (@boegel): requires ~~https://github.com/easybuilders/easybuild-easyblocks/pull/2299~~

### CODE REVIEW

**Comment by boegel** [comment]
@boegelbot please test @ generoso

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
node3104.skitty.os - Linux centos linux 7.9.2009, x86_64, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz, Python 3.6.8
See https://gist.github.com/51335caaa0b501de8ee039b17db00fd3 for a full test report.

**Comment by boegel** [comment]
@branfosj Looks like we have a missing `Python` (build?) dep too:

```
/usr/bin/env: python: No such file or directory
```

**Comment by branfosj** [comment]
> @branfosj Looks like we have a missing `Python` (build?) dep too:
> 
> ```
> /usr/bin/env: python: No such file or directory
> ```

So, this is annoying. If we have Python as a dep (build or standard) then we add `--with-numpy=1  --with-mpi4py=1` to the `configure`, which are not there otherwise (see https://gist.github.com/boegelbot/fb04fd99bd60660248693e8f644d0c0e#file-petsc-3-11-0-foss-2018b-downloaded-deps_partial-log-L489). This is happening at https://github.com/easybuilders/easybuild-easyblocks/blob/develop/easybuild/easyblocks/p/petsc.py#L157

**Comment by boegel** [comment]
> > @branfosj Looks like we have a missing `Python` (build?) dep too:
> > ```
> > /usr/bin/env: python: No such file or directory
> > ```
> 
> So, this is annoying. If we have Python as a dep (build or standard) then we add `--with-numpy=1 --with-mpi4py=1` to the `configure`, which are not there otherwise (see https://gist.github.com/boegelbot/fb04fd99bd60660248693e8f644d0c0e#file-petsc-3-11-0-foss-2018b-downloaded-deps_partial-log-L489). This is happening at https://github.com/easybuilders/easybuild-easyblocks/blob/develop/easybuild/easyblocks/p/petsc.py#L157

@branfosj So we should enhance the `PETSc` easyblock to check whether `import numpy` and `import mpi4py` work before enabling those configure options, rather than assuming they come with `Python`?

**Comment by branfosj** [comment]
@boegel There is two different issues:
1. The current easyblock assumes that `numpy` and `mpi4py` will be there if Python is found and enables those options.
2. If we want to use the Python as a build dependency - to make the minimal change possible here - that enables numpy / mpi4py meaning that we then need Python as a dependency.

Your suggested fix solves issue 1, but does not solve 2 in this case. This is because Python in 2018b has numpy and mpi4py included. So to fix PETSc here, we would need to move it to have a Python dep and then alter any other easyconfigs that require this version of PETSc. This seems like an overly complicated solution to the problem.

Should we instead add an option to the easyblock to disable building Python support? (Or an option to enable building with Python support that defaults to True.)

**Comment by boegel** [comment]
@branfosj see https://github.com/easybuilders/easybuild-easyblocks/pull/2299

**Comment by boegel** [comment]
@boegelbot please test @ generoso
EB_ARGS="--include-easyblocks-from-pr 2299"

**Comment by boegel** [comment]
Test report by @boegel
Using easyblocks from PR(s) https://github.com/easybuilders/easybuild-easyblocks/pull/2299
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
node3104.skitty.os - Linux centos linux 7.9.2009, x86_64, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz, Python 3.6.8
See https://gist.github.com/c4796a4fe45fd1f0b58b246afa49af3b for a full test report.

**Comment by branfosj** [comment]
Test report by @branfosj
Using easyblocks from PR(s) https://github.com/easybuilders/easybuild-easyblocks/pull/2299
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
bear-pg0211u12a.bear.cluster - Linux centos linux 7.8.2003, x86_64, Intel(R) Xeon(R) Gold 6248 CPU @ 2.50GHz (cascadelake), Python 3.6.8
See https://gist.github.com/1923204e7239175ab8cf71f9834f422f for a full test report.

**Comment by boegel** [comment]
@boegelbot please test @ generoso
EB_ARGS="--include-easyblocks-from-pr 2299"

**Comment by boegel** [comment]
Test report by @boegel
Using easyblocks from PR(s) https://github.com/easybuilders/easybuild-easyblocks/pull/2299
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
node3104.skitty.os - Linux centos linux 7.9.2009, x86_64, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz, Python 3.6.8
See https://gist.github.com/ceed4ba5067a327bd24c72e8a498ddd1 for a full test report.

**Comment by branfosj** [comment]
Test report by @branfosj
Using easyblocks from PR(s) https://github.com/easybuilders/easybuild-easyblocks/pull/2299
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
bear-pg0211u03a.bear.cluster - Linux centos linux 7.8.2003, x86_64, Intel(R) Xeon(R) Gold 6248 CPU @ 2.50GHz (cascadelake), Python 3.6.8
See https://gist.github.com/ac2acb231d049b666c559751c701e525 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
Using easyblocks from PR(s) https://github.com/easybuilders/easybuild-easyblocks/pull/2299
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
node2624.swalot.os - Linux centos linux 7.9.2009, x86_64, Intel(R) Xeon(R) CPU E5-2660 v3 @ 2.60GHz (haswell), Python 3.6.8
See https://gist.github.com/7e5f39c39cacf9ec51fcf56d4bddff39 for a full test report.

**Review by boegel — APPROVED** [review]
lgtm

**Comment by boegel** [comment]
Going in, thanks @branfosj!

**Pull request merged**
