### PR TITLE
correct the version, fix spelling of a name, and add an extra sanity check command in pangolin

### PR DESCRIPTION
**Pull request by branfosj**
(created using `eb --new-pr`)

* Address @SethosII comments from https://github.com/easybuilders/easybuild-easyconfigs/pull/13733#pullrequestreview-741006281
* The original was labelled as 3.1.10 but installed 3.1.11

### CODE REVIEW

**Comment by branfosj** [comment]
@boegelbot please test @ generoso

**Comment by branfosj** [comment]
Test report by @branfosj
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
bear-pg0211u03a.bear.cluster - Linux RHEL 8.3, x86_64, Intel(R) Xeon(R) Gold 6248 CPU @ 2.50GHz (cascadelake), Python 3.6.8
See https://gist.github.com/70008acac15a50dfc846501410fd69f7 for a full test report.

**Comment by sassy-crick** [comment]
Apologies for the wrong spelling of the name and the different versions. Well spotted @branfosj !

**Review by Micket — APPROVED** [review]
lgtm

**Comment by Micket** [comment]
Test report by @Micket
**SUCCESS**
Build succeeded for 4 out of 4 (1 easyconfigs in total)
alvis-c1 - Linux centos linux 7.9.2009, x86_64, Intel Xeon Processor (Skylake), Python 3.6.8
See https://gist.github.com/6dcfe759d792d320d201fa517c610e8c for a full test report.

**Comment by Micket** [comment]
Going in, thanks @branfosj!

**Review by Debulknor — APPROVED** [review]

**Comment by boegel** [comment]
Totally overlooked this, thanks for the fix @branfosj!

**Pull request merged**
