### PR TITLE
{bio}[gompi/2020a] Kraken2 v2.0.9-beta

### PR DESCRIPTION
**Pull request by FokkeDijkstra**
(created using `eb --new-pr`)
requires #10794 (wget)
requires  ~~#10796~~ (BLAST+)

### CODE REVIEW

**Comment by FokkeDijkstra** [comment]
Requires #10794

**Comment by Micket** [comment]
kick test suite

**Comment by Micket** [comment]
Test report by @Micket
**SUCCESS**
Build succeeded for 3 out of 3 (1 easyconfigs in this PR)
hebbe-c1 - Linux centos linux 7.8.2003, x86_64, Intel Core Processor (Haswell, no TSX), Python 2.7.5
See https://gist.github.com/ed97a251dd0e075d3e6503270de978df for a full test report.

**Comment by Micket** [comment]
Going in, thanks @FokkeDijkstra!

**Pull request merged**
