### PR TITLE
{tools}[intel/2015b] Babel 1.4.0 & 2.0.0 (WIP)

### PR DESCRIPTION
**Pull request by boegel**

### CODE REVIEW

**Comment by boegel** [comment]
@wpoely86: please review?

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
Linux SL 6.7, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.6.6
See https://gist.github.com/3e951dd6c0e203d22200 for a full test report.

**Comment by wpoely86** [comment]
lgtm

**Comment by boegel** [comment]
Test report by @boegel
**FAILED**
Build succeeded for 1 out of 2 (2 easyconfigs in this PR)
Linux centos linux 7.1.1503, Intel(R) Xeon(R) CPU E5-2680 v3 @ 2.50GHz, Python 2.7.5
See https://gist.github.com/d2a7e812894440485db0 for a full test report.

**Comment by boegel** [comment]
Hmm, for some reason the patch gets undone with 1.4.0...

**Comment by migueldiascosta** [comment]
@boegel ping?

**Comment by boegel** [comment]
no longer relevant imho...

**Pull request closed without merging**
