### PR TITLE
{lang}[dummy/dummy] Java v1.8.0_202

### PR DESCRIPTION
**Pull request by sassy-crick**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by sassy-crick** [comment]
Test report by @sassy-crick
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
login002.camp.thecrick.org - Linux RHEL 7.3, Intel(R) Xeon(R) CPU E5-2640 v3 @ 2.60GHz, Python 2.7.5
See https://gist.github.com/f741c0c62f017ca946f79fb9d0c506c1 for a full test report.

**Comment by HPC-UniOldenburg** [comment]
Test report by @HPC-UniOldenburg
**SUCCESS**
Build succeeded for 0 out of 0 (1 easyconfigs in this PR)
hpcl002 - Linux RHEL 7.2, Intel(R) Xeon(R) CPU E5-2650 v4 @ 2.20GHz, Python 2.7.5
See https://gist.github.com/31e62fba7c81ffd04796daf8d4ab4112 for a full test report.

**Comment by HPC-UniOldenburg** [comment]
Test report by @HPC-UniOldenburg
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
hpcl002 - Linux RHEL 7.2, Intel(R) Xeon(R) CPU E5-2650 v4 @ 2.20GHz, Python 2.7.5
See https://gist.github.com/5d558984a78671a04eaf5e6c311433ed for a full test report.

**Comment by boegel** [comment]
@sassy-crick Please update `Java-1.8.eb` accordingly so the wrapper uses the latest `Java` 1.8.x version

**Comment by boegel** [comment]
@HPC-UniOldenburg Anyone can review/test incoming pull requests, we certainly appreciate that, it'll help the team of maintainers (see https://easybuild.readthedocs.io/en/latest/Maintainers.html) to get the PR merged

**Comment by sassy-crick** [comment]
> @sassy-crick Please update `Java-1.8.eb` accordingly so the wrapper uses the latest `Java` 1.8.x version

@boegel I am confused. This *is* the module for Java version 1.8.0_202. I am not sure how the wrapper would make sense here but the, you know Easybuild much better than I do!

**Comment by boegel** [comment]
@sassy-crick The existing `Java-1.8.eb` easyconfig file specifies which version is being wrapped by `Java/1.8`; if you add an easyconfig for a newer (specific) version of `Java` 1.8.x, you should also change `Java-1.8.eb` accordingly

See also https://github.com/easybuilders/easybuild-easyconfigs/pull/7097/files#diff-8c875f096a9a2a9a6c24c2bec49e4913, for example.

**Comment by sassy-crick** [comment]
@boegel Java1.8 EB script changed and uploaded: 7635. I hope all of that is OK now

**Comment by boegel** [comment]
@sassy-crick It would have been fine to make that change in this same PR, but it's OK as is, we'll get both merged ASAP. Thanks!

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
node3118.skitty.os - Linux centos linux 7.6.1810, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz, Python 2.7.5
See https://gist.github.com/91d79fbcd3d7dbe1d68382b3d68de603 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
node2431.golett.os - Linux centos linux 7.6.1810, Intel(R) Xeon(R) CPU E5-2680 v3 @ 2.50GHz, Python 2.7.5
See https://gist.github.com/af486fb552ff2454e93175b807180810 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
node2016.delcatty.os - Linux centos linux 7.6.1810, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.7.5
See https://gist.github.com/a6d0e6ca63e9abf5a23bb6809c1902e8 for a full test report.

**Comment by boegel** [comment]
Going in, thanks @sassy-crick!

**Comment by sassy-crick** [comment]
@boegel thanks for doing it and sorry I did not do it here. I am still learning how to use GitHub.

**Pull request merged**
