### PR TITLE
{bio}[GCCcore/12.2.0] preseq 3.2.0

### PR DESCRIPTION
**Pull request by VictorGoitea**

### CODE REVIEW

**Comment by kErica** [comment]
Hi @VictorGoitea, 
thank you for your contribution.

Please, change the name of the PR with the following format 

```
{$moduleclass}[$toolchain] $name $version
```
Here a couple of examples:
{geo}[foss/2023a] PALM v23.10
{phys}[foss/2023a] CORSIKA v77550

**Comment by boegel** [comment]
@boegelbot please test @ generoso

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
node3117.skitty.os - Linux RHEL 8.8, x86_64, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz, Python 3.6.8
See https://gist.github.com/boegel/628cbad122a2eea922222648e23317ea for a full test report.

**Comment by boegel** [comment]
@boegelbot please test @ jsc-zen3

**Review by boegel — APPROVED** [review]
lgtm

**Comment by boegel** [comment]
Going in, thanks @VictorGoitea!

**Pull request merged**
