### PR TITLE
{math}[intel/2022a] sympy v1.10.1 w/ Python 3.10.4

### PR DESCRIPTION
**Pull request by ItIsI-Orient**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by ItIsI-Orient** [comment]
Test report by @ItIsI-Orient
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
node3702.slaking.os - Linux RHEL 8.6, x86_64, Intel(R) Xeon(R) CPU E5-2680 v3 @ 2.50GHz, Python 3.6.8
See https://gist.github.com/69695b70367a9e08a33fa82ca751f786 for a full test report.

**Comment by casparvl** [comment]
@boegelbot please test @ jsc-zen2

**Comment by casparvl** [comment]
Test report by @casparvl
**FAILED**
Build succeeded for 1 out of 2 (1 easyconfigs in total)
tcn446.local.snellius.surf.nl - Linux Rocky Linux 8.7, x86_64, AMD EPYC 7H12 64-Core Processor, Python 3.6.8
See https://gist.github.com/0e75fb67abe17348db12be1cf88c6c4b for a full test report.

**Comment by casparvl** [comment]
I needed to search a bit in the output, but this seems to be the failure:

```
sympy/utilities/tests/test_lambdify.py[116] ....................INTEL MKL ERROR: /sw/arch/RHEL8/EB_production/2022/software/imkl/2022.1.0/mkl/2022.1.0/lib/intel64/libmkl_vml_def.so.2: undefined symbol: mkl_lapack_dspevd.
Intel MKL FATAL ERROR: cannot load libmkl_vml_def.so.2.
```

**Comment by casparvl** [comment]
Ah... https://github.com/easybuilders/easybuild-easyblocks/pull/2897

**Comment by casparvl** [comment]
Test report by @casparvl
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
tcn1.local.snellius.surf.nl - Linux Rocky Linux 8.7, x86_64, AMD EPYC 7H12 64-Core Processor, Python 3.6.8
See https://gist.github.com/1a9cf64b5f4ca180b42fe020aaf4157f for a full test report.

**Review by boegel — APPROVED** [review]
lgtm

**Comment by boegel** [comment]
Going in, thanks @ItIsI-Orient!

**Pull request merged**
