### PR TITLE
{toolchain} intelcuda/2020a

### PR DESCRIPTION
**Pull request by bartoldeman**

### CODE REVIEW

**Comment by bartoldeman** [comment]
@boegelbot please test @ generoso

**Comment by bartoldeman** [comment]
Test report by @bartoldeman
**FAILED**
Build succeeded for 1 out of 5 (5 easyconfigs in this PR)
build-node.computecanada.ca - Linux centos linux 7.8.2003, x86_64, Intel Xeon Processor (Skylake, IBRS), Python 3.7.7
See https://gist.github.com/808e3196009104277e88033ec9ad15e1 for a full test report.

**Comment by bartoldeman** [comment]
Test report by @bartoldeman
**SUCCESS**
Build succeeded for 5 out of 5 (5 easyconfigs in this PR)
build-node.computecanada.ca - Linux centos linux 7.8.2003, x86_64, Intel Xeon Processor (Skylake, IBRS), Python 3.7.7
See https://gist.github.com/880a9764f15373663bbbcfcb5e1261c1 for a full test report.

**Comment by zao** [comment]
Test report by @zao
**SUCCESS**
Build succeeded for 5 out of 5 (5 easyconfigs in this PR)
freja - Linux Ubuntu 20.04, x86_64, Intel(R) Core(TM) i7-8700K CPU @ 3.70GHz, Python 3.8.2
See https://gist.github.com/e6bbaf8b03ff3b5484f8bc4900cc3584 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 8 out of 8 (5 easyconfigs in this PR)
node3170.skitty.os - Linux centos linux 7.8.2003, x86_64, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz, Python 3.6.8
See https://gist.github.com/9478782fecb31157a6632a4253d596ae for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 5 out of 5 (5 easyconfigs in this PR)
node3502.doduo.os - Linux RHEL 8.2, x86_64, AMD EPYC 7302P 16-Core Processor (zen2), Python 3.6.8
See https://gist.github.com/4edfd8f1d7d81c3747493f80c602cb8c for a full test report.

**Comment by boegel** [comment]
@boegelbot please test @ generoso

Problem that occurred before during `impi` sanity check:

```
== 2020-10-02 18:43:02,405 build_log.py:169 ERROR EasyBuild crashed with an error (at easybuild/easybuild-framework/easybuild/base/exceptions.py:124 in __init__): Sanity check failed: sanity check command mpirun -n 16 /tmp/boegelbot/impi/2019.7.217/iccifortcuda-2020a/mpi_test exited with code 255 (output: [mpiexec@generoso-x-3] check_exit_codes (../../../../../src/pm/i_hydra/libhydra/demux/hydra_demux_poll.c:117): unable to run bstrap_proxy on generoso-x-3 (pid 3603662, exit code 65280)
[mpiexec@generoso-x-3] poll_for_event (../../../../../src/pm/i_hydra/libhydra/demux/hydra_demux_poll.c:159): check exit codes error
[mpiexec@generoso-x-3] HYD_dmx_poll_wait_for_proxy_event (../../../../../src/pm/i_hydra/libhydra/demux/hydra_demux_poll.c:212): poll for event error
[mpiexec@generoso-x-3] HYD_bstrap_setup (../../../../../src/pm/i_hydra/libhydra/bstrap/src/intel/i_hydra_bstrap.c:770): error waiting for event
[mpiexec@generoso-x-3] main (../../../../../src/pm/i_hydra/mpiexec/mpiexec.c:1956): error setting up the boostrap proxies
) (at easybuild/easybuild-framework/easybuild/framework/easyblock.py:2771 in _sanity_check_step)
```

Should now be fixed after changing the job script used to test PRs to use a login shell (`#!/bin/bash -l`), to ensure that `srun` which is installed in a non-default location is available via `$PATH` (path is added via a profile script `/etc/profile.d/slurm.sh` which is only sourced for login shells).

**Review by boegel — APPROVED** [review]
lgtm

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 5 out of 5 (5 easyconfigs in this PR)
node3404.kirlia.os - Linux centos linux 7.8.2003, x86_64, Intel(R) Xeon(R) Gold 6240 CPU @ 2.60GHz (cascadelake), Python 2.7.5
See https://gist.github.com/2bf8c128ab8e3591c8593a4ca2250386 for a full test report.

**Comment by boegel** [comment]
Going in, thanks @bartoldeman!

**Pull request merged**
