### PR TITLE
{vis}[GCCcore/12.3.0] cairo v1.17.8, pixman v0.42.2

### PR DESCRIPTION
**Pull request by stefan-wolfsheimer**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by verdurin** [comment]
@boegelbot please test @ generoso

**Comment by verdurin** [comment]
@boegelbot please test @ jsc-zen2

**Comment by verdurin** [comment]
My local test build will fail owing to https://github.com/easybuilders/easybuild-easyconfigs/issues/18519

**Comment by verdurin** [comment]
Test report by @verdurin
**FAILED**
Build succeeded for 13 out of 18 (2 easyconfigs in total)
easybuild-c7.novalocal - Linux CentOS Linux 7.9.2009, x86_64, Intel Xeon Processor (Skylake, IBRS), Python 3.6.8
See https://gist.github.com/verdurin/633c74482723cc2857f1b1564221b8cd for a full test report.

**Comment by branfosj** [comment]
Test report by @branfosj
**SUCCESS**
Build succeeded for 8 out of 8 (2 easyconfigs in total)
bear-pg0105u03a.bear.cluster - Linux RHEL 8.6, x86_64, Intel(R) Xeon(R) Platinum 8360Y CPU @ 2.40GHz (icelake), Python 3.6.8
See https://gist.github.com/branfosj/ef34c50d357d38b9cf8511b99142cd57 for a full test report.

**Comment by branfosj** [comment]
> My local test build will fail owing to #18519

As the failure is not for an easyconfig in this PR, I'll go ahead and approve and merge this one.

**Review by branfosj — APPROVED** [review]

**Pull request merged**
