### PR TITLE
{chem}[intel/2017a] yaff v1.1.3

### PR DESCRIPTION
**Pull request by boegel**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
node2402.golett.os - Linux centos linux 7.3.1611, Intel(R) Xeon(R) CPU E5-2680 v3 @ 2.50GHz, Python 2.7.5
See https://gist.github.com/649965a4ba60d448b0dac9ea44951458 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
node2104.delcatty.os - Linux centos linux 7.3.1611, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.7.5
See https://gist.github.com/323b8bf95ae183817cdc48d14dd97f1f for a full test report.

**Comment by boegel** [comment]
@easybuilders/easybuild-easyconfigs-maintainers Good to go

**Comment by migueldiascosta** [comment]
Going in. Thanks @boegel!

**Pull request merged**
