### PR TITLE
{toolchain} foss/2021.04

### PR DESCRIPTION
**Pull request by boegel**
(created using `eb --new-pr`)
candidate for `foss/2021a`
requires:
* [x] ~https://github.com/easybuilders/easybuild-framework/pull/3679~ (OpenBLAS -> FlexiBLAS for `foss`)
* [x] ~https://github.com/easybuilders/easybuild-easyblocks/pull/2427~ (ScaLAPACK easyblock)
* [x] ~#12476~ (FlexiBLAS)
* [x] ~~#12571~~ (gompi/2021.04)

### CODE REVIEW

**Comment by boegel** [comment]
@boegelbot please test @ generoso
EB_ARGS="--include-easyblocks-from-pr 2427"

**Comment by boegel** [comment]
Test report by @boegel
**FAILED**
Build succeeded for 1 out of 4 (4 easyconfigs in total)
easybuild2.novalocal - Linux centos linux 8.3.2011, POWER, IBM pSeries (emulated by qemu) (power9le), Python 3.6.8
See https://gist.github.com/0bc75d6e094d55065bb74872e7df4175 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 4 out of 4 (4 easyconfigs in total)
select-pika-c6gd-2xlarge-0001 - Linux centos linux 8.3.2011, AArch64, ARM UNKNOWN (graviton2), Python 3.6.8
See https://gist.github.com/0186ee57f09fe76b6768ce0517a443ca for a full test report.

**Comment by branfosj** [comment]
Test report by @branfosj
Using easyblocks from PR(s) https://github.com/easybuilders/easybuild-easyblocks/pull/2427
**FAILED**
Build succeeded for 2 out of 5 (4 easyconfigs in total)
bear-pg0211u03a.bear.cluster - Linux RHEL 8.3, x86_64, Intel(R) Xeon(R) Gold 6248 CPU @ 2.50GHz (cascadelake), Python 3.6.8
See https://gist.github.com/3b449eb2d89ec092e03b10c81243c237 for a full test report.

**Comment by boegel** [comment]
@branfosj A fix was needed in https://github.com/easybuilders/easybuild-easyblocks/pull/2427, that's done now, please try again :)

**Comment by boegel** [comment]
@boegelbot please test @ generoso
CORE_CNT=16
EB_ARGS="--include-easyblocks-from-pr 2427"

**Comment by boegel** [comment]
Test report by @boegel
Using easyblocks from PR(s) https://github.com/easybuilders/easybuild-easyblocks/pull/2427
**SUCCESS**
Build succeeded for 4 out of 4 (4 easyconfigs in total)
select-pika-c6gd-2xlarge-0001 - Linux centos linux 8.3.2011, AArch64, ARM UNKNOWN (graviton2), Python 3.6.8
See https://gist.github.com/0c574307c712b81d4dc7ee7dff37109c for a full test report.

**Comment by branfosj** [comment]
Test report by @branfosj
Using easyblocks from PR(s) https://github.com/easybuilders/easybuild-easyblocks/pull/2427
**SUCCESS**
Build succeeded for 4 out of 4 (4 easyconfigs in total)
bear-pg0211u03a.bear.cluster - Linux RHEL 8.3, x86_64, Intel(R) Xeon(R) Gold 6248 CPU @ 2.50GHz (cascadelake), Python 3.6.8
See https://gist.github.com/a2f370cc954a4f221964cea6b861b1f8 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
Using easyblocks from PR(s) https://github.com/easybuilders/easybuild-easyblocks/pull/2427, https://github.com/easybuilders/easybuild-easyblocks/pull/2437
**SUCCESS**
Build succeeded for 4 out of 4 (4 easyconfigs in total)
easybuild2.novalocal - Linux centos linux 8.3.2011, POWER, IBM pSeries (emulated by qemu) (power9le), Python 3.6.8
See https://gist.github.com/54378ecb479e6552f53c175db8674079 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
Using easyblocks from PR(s) https://github.com/easybuilders/easybuild-easyblocks/pull/2427
**SUCCESS**
Build succeeded for 4 out of 4 (4 easyconfigs in total)
node3128.skitty.os - Linux centos linux 7.9.2009, x86_64, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz, Python 3.6.8
See https://gist.github.com/5052972303207ecc6ec2946760007cdb for a full test report.

**Review by branfosj — APPROVED** [review]
lgtm

**Comment by branfosj** [comment]
Going in, thanks @boegel!

**Comment by boegel** [comment]
Test report by @boegel
Using easyblocks from PR(s) https://github.com/easybuilders/easybuild-easyblocks/pull/2427
**SUCCESS**
Build succeeded for 4 out of 4 (4 easyconfigs in total)
node3587.doduo.os - Linux RHEL 8.2, x86_64, AMD EPYC 7552 48-Core Processor (zen2), Python 3.6.8
See https://gist.github.com/c4abf5c7f5ec186d4ac14a477531952b for a full test report.

**Comment by branfosj** [comment]
Test report by @branfosj
**SUCCESS**
Build succeeded for 4 out of 4 (4 easyconfigs in total)
bask-pg0308u11a - Linux RHEL 8.3, x86_64, Intel(R) Xeon(R) Platinum 8358P CPU @ 2.60GHz (icelake), Python 3.6.8
See https://gist.github.com/0985dac0919ffb3652bab26bf9343f79 for a full test report.

**Pull request merged**
