### PR TITLE
{bio}[GCCcore/11.3.0] PAML v4.10.5

### PR DESCRIPTION
**Pull request by smoors**
(created using `eb --new-pr`)

PAML v4.10.6 did not pass the sanity_check_commands test, so I'm sticking with v4.10.5 for now.

in case anyone interested,
<details>
<summary>here is the error log for 4.10.6</summary>

```
CODONML in paml version 4.10.0, September 2020

----------------------------------------------
Phe F TTT | Ser S TCT | Tyr Y TAT | Cys C TGT
      TTC |       TCC |       TAC |       TGC
Leu L TTA |       TCA | *** * TAA | *** * TGA
      TTG |       TCG |       TAG | Trp W TGG
----------------------------------------------
Leu L CTT | Pro P CCT | His H CAT | Arg R CGT
      CTC |       CCC |       CAC |       CGC
      CTA |       CCA | Gln Q CAA |       CGA
      CTG |       CCG |       CAG |       CGG
----------------------------------------------
Ile I ATT | Thr T ACT | Asn N AAT | Ser S AGT
      ATC |       ACC |       AAC |       AGC
      ATA |       ACA | Lys K AAA | Arg R AGA
Met M ATG |       ACG |       AAG |       AGG
----------------------------------------------
Val V GTT | Ala A GCT | Asp D GAT | Gly G GGT
      GTC |       GCC |       GAC |       GGC
      GTA |       GCA | Glu E GAA |       GGA
      GTG |       GCG |       GAG |       GGG
----------------------------------------------
Nice code, uuh?
NSsites batch run (ncatG as in YNGP2000):   0  1  2
ns = 13         ls = 273
Reading sequences, sequential format..
Reading seq #13: U68508
Sequences read..
Counting site patterns..  0:00
Compressing,     79 patterns at     91 /     91 sites (100.0%),  0:00   
Collecting fpatt[] & pose[],     79 patterns at     91 /     91 sites (100.0%),  0:00
Counting codons..

      624 bytes for distance
    77104 bytes for conP
     6952 bytes for fhK
  5000000 bytes for space


Model 0: one-ratio

TREE #  1
(1, 2, ((3, (4, 5)), (6, (7, (8, ((((9, 11), 10), 12), 13))))));   MP score: 136
   424072 bytes for conP, adjusted

    0.010002    0.021074    0.086308    0.027998    0.100288    0.098984    0.048701    0.057594    0.098219    0.028578    0.073880    0.036921    0.034668    0.023617    0.028302    0.088449    0.081652    0.037947    0.071811    0.049398    0.104353    0.053089    0.018597    0.300000    1.300000

ntime & nrate & np:    23     2    25

Bounds (np=25):
   0.000004   0.000004   0.000004   0.000004   0.000004   0.000004   0.000004   0.000004   0.000004   0.000004   0.000004   0.000004   0.000004   0.000004   0.000004   0.000004   0.000004   0.000004   0.000004   0.000004   0.000004   0.000004   0.000004   0.000100   0.000100
  50.000000  50.000000  50.000000  50.000000  50.000000  50.000000  50.000000  50.000000  50.000000  50.000000  50.000000  50.000000  50.000000  50.000000  50.000000  50.000000  50.000000  50.000000  50.000000  50.000000  50.000000  50.000000  50.000000 999.000000 999.000000

np =    25
lnL0 = -1282.160444

Iterating by ming2
Initial: fx=  1282.160444
x=  0.01000  0.02107  0.08631  0.02800  0.10029  0.09898  0.04870  0.05759  0.09822  0.02858  0.07388  0.03692  0.03467  0.02362  0.02830  0.08845  0.08165  0.03795  0.07181  0.04940  0.10435  0.05309  0.01860  0.30000  1.30000

  1 h-m-p  0.0000 0.0012 988.3300 +++YCYCCCC  1206.415001  6 0.0004    43 | 0/25
  2 h-m-p  0.0002 0.0009 194.8498 +YYCYCCC  1185.362461  6 0.0008    81 | 0/25
  3 h-m-p  0.0000 0.0002 632.6623 +YYCCCC  1179.826509  5 0.0001   118 | 0/25
  4 h-m-p  0.0001 0.0006 340.8037 +YYCCC  1171.740134  4 0.0004   153 | 0/25
  5 h-m-p  0.0001 0.0007 565.9837 YCCC   1166.561635  3 0.0003   186 | 0/25
  6 h-m-p  0.0006 0.0077 290.1768 YYCCC  1159.082751  4 0.0008   220 | 0/25
  7 h-m-p  0.0007 0.0034  68.7749 YCCC   1156.951453  3 0.0013   253 | 0/25
  8 h-m-p  0.0014 0.0071  38.9905 YCYC   1156.418200  3 0.0011   285 | 0/25
  9 h-m-p  0.0013 0.0063  25.1932 CC     1156.150106  1 0.0013   315 | 0/25
 10 h-m-p  0.0024 0.0118  11.0353 YYC    1156.057565  2 0.0018   345 | 0/25
 11 h-m-p  0.0015 0.0368  13.3999 YC     1155.900791  1 0.0033   374 | 0/25
 12 h-m-p  0.0019 0.0172  22.8174 YCCC   1155.535811  3 0.0048   407 | 0/25
 13 h-m-p  0.0010 0.0103 105.4179 +YCYCC  1154.400471  4 0.0029   442 | 0/25
 14 h-m-p  0.0026 0.0131  43.7818 YCCC   1154.242713  3 0.0011   475 | 0/25
 15 h-m-p  0.0078 0.0392   4.0306 CC     1154.222153  1 0.0018   505 | 0/25
 16 h-m-p  0.0023 0.0548   3.1150 YC     1154.151820  1 0.0051   534 | 0/25
 17 h-m-p  0.0019 0.0593   8.2869 YCCC   1153.985670  3 0.0031   567 | 0/25
 18 h-m-p  0.0025 0.0235  10.3874 YCCC   1153.392238  3 0.0051   600 | 0/25
 19 h-m-p  0.0029 0.0169  18.0835 +YYCCC  1150.205474  4 0.0091   635 | 0/25
 20 h-m-p  0.0006 0.0030  98.2138 +CYC   1144.764225  2 0.0026   667 | 0/25
 21 h-m-p  0.0004 0.0018 134.1382 YCCC   1143.017782  3 0.0008   700 | 0/25
 22 h-m-p  0.0004 0.0022  73.0201 CCCC   1142.317515  3 0.0007   734 | 0/25
 23 h-m-p  0.0014 0.0069  15.2515 YC     1142.244224  1 0.0008   763 | 0/25
 24 h-m-p  0.0017 0.0150   7.1347 YC     1142.225558  1 0.0008   792 | 0/25
 25 h-m-p  0.0078 0.1346   0.7525 CC     1142.191911  1 0.0108   822 | 0/25
 26 h-m-p  0.0021 0.1628   3.8730 ++CCCC  1140.579965  3 0.0444   883 | 0/25
 27 h-m-p  0.0017 0.0085  60.2349 YCCC   1140.051520  3 0.0011   916 | 0/25
 28 h-m-p  0.4114 3.0966   0.1558 YC     1139.059733  1 0.9357   945 | 0/25
 29 h-m-p  0.8426 6.2096   0.1730 CYC    1138.418912  2 0.9696  1001 | 0/25
 30 h-m-p  1.4027 8.0000   0.1196 CCC    1138.086180  2 1.1974  1058 | 0/25
 31 h-m-p  1.6000 8.0000   0.0739 CCC    1137.896336  2 1.6174  1115 | 0/25
 32 h-m-p  1.6000 8.0000   0.0458 CCC    1137.744614  2 2.1776  1172 | 0/25
 33 h-m-p  1.6000 8.0000   0.0202 YC     1137.698309  1 1.2214  1226 | 0/25
 34 h-m-p  1.6000 8.0000   0.0084 YC     1137.689327  1 1.0785  1280 | 0/25
 35 h-m-p  1.6000 8.0000   0.0032 YC     1137.688342  1 1.2584  1334 | 0/25
 36 h-m-p  1.6000 8.0000   0.0005 C      1137.688208  0 1.3937  1387 | 0/25
 37 h-m-p  1.6000 8.0000   0.0003 Y      1137.688192  0 1.2529  1440 | 0/25
 38 h-m-p  1.6000 8.0000   0.0001 C      1137.688190  0 1.4323  1493 | 0/25
 39 h-m-p  1.0578 8.0000   0.0001 C      1137.688190  0 1.3701  1546 | 0/25
 40 h-m-p  1.6000 8.0000   0.0000 Y      1137.688190  0 1.2306  1599 | 0/25
 41 h-m-p  1.6000 8.0000   0.0000 C      1137.688190  0 1.4320  1652 | 0/25
 42 h-m-p  1.0638 8.0000   0.0000 C      1137.688190  0 1.2544  1705 | 0/25
 43 h-m-p  1.6000 8.0000   0.0000 C      1137.688190  0 1.3524  1758 | 0/25
 44 h-m-p  1.2909 8.0000   0.0000 C      1137.688190  0 1.2259  1811 | 0/25
 45 h-m-p  1.6000 8.0000   0.0000 C      1137.688190  0 1.6000  1864 | 0/25
 46 h-m-p  1.6000 8.0000   0.0000 Y      1137.688190  0 1.6000  1917 | 0/25
 47 h-m-p  1.6000 8.0000   0.0000 ---Y   1137.688190  0 0.0063  1973
Out..
lnL  = -1137.688190
1974 lfun, 1974 eigenQcodon, 45402 P(t)

Time used:  0:10


Model 1: NearlyNeutral

# seqs in tree file does not match.  Read as the nexus format.
```
</details>

### CODE REVIEW

**Comment by branfosj** [comment]
@boegelbot please test @ jsc-zen2

**Comment by smoors** [comment]
@boegelbot: please test @ generoso

**Comment by branfosj** [comment]
Test report by @branfosj
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
bear-pg0105u36b.bear.cluster - Linux RHEL 8.6, x86_64, Intel(R) Xeon(R) Platinum 8360Y CPU @ 2.40GHz (icelake), Python 3.6.8
See https://gist.github.com/dcda094e72df2ac0925eb805227bfb6e for a full test report.

**Review by branfosj — APPROVED** [review]

**Comment by branfosj** [comment]
Going in, thanks @smoors!

**Pull request merged**
