### PR TITLE
{compiler} [NVHPC/20.9] Added new multi arch version

### PR DESCRIPTION
**Pull request by nordmoen**
Added new multi-arch version of NVHPC, this requires `easyblock` PR
easybuilders/easybuild-easyblocks#2233.

### CODE REVIEW

**Comment by Micket** [comment]
So, this looks very much like, the previous version, but, I have some concerns;
```
dependencies = [
    ('GCCcore', local_gccver),
    ('binutils', '2.34', '', ('GCCcore', local_gccver)),
    # This is necessary to avoid cases where just libnuma.so.1 is present in the system and -lnuma fails
    ('numactl', '2.0.13', '', ('GCCcore', local_gccver))
]
```
Rather than all this, why not put it under GCCcore and depend on these modules normally? You'd end up with this anyway. I'm also not sure
```
    ('numactl', '2.0.13', '', ('GCCcore', local_gccver))
```
works at all on HMNS, so seeing this is a big code-smell to me.

Also, why not actually depend on the `CUDAcore` are are using for the toolchain anyway?

**Comment by akesandgren** [comment]
@Micket This is a a compiler toolchain and as such can't be under another toolchain.
Look at how the iccifort definitions look, this is the same thing.

**Comment by boegel** [comment]
Test report by @boegel
**FAILED**
Build succeeded for 0 out of 1 (1 easyconfigs in total)
node3154.skitty.os - Linux centos linux 7.9.2009, x86_64, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz, Python 3.6.8
See https://gist.github.com/bc89bf2b59be001e7125bab2c459b687 for a full test report.

**Comment by boegel** [comment]
@boegelbot please test @ generoso
EB_ARGS="--cuda-compute-capabilities=7.0"

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
node3154.skitty.os - Linux centos linux 7.9.2009, x86_64, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz, Python 3.6.8
See https://gist.github.com/461c328407eb39279c1fc5612495cf51 for a full test report.

**Review by boegel — APPROVED** [review]
lgtm

**Comment by boegel** [comment]
Going in, thanks @nordmoen!

**Pull request merged**
