### PR TITLE
{lib}[GCCcore/11.2.0] snappy v1.1.8

### PR DESCRIPTION
**Pull request by SebastianAchilles**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by SebastianAchilles** [comment]
Test report by @sebastianachilles
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
rocky8-eb - Linux rocky linux 8.4, x86_64, Intel(R) Core(TM) i7-6900K CPU @ 3.20GHz (broadwell), Python 3.6.8
See https://gist.github.com/e2b34067c6a2259345ca5d428cd5bc62 for a full test report.

**Comment by SebastianAchilles** [comment]
Test report by @sebastianachilles
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
centos8-eb - Linux centos linux 8.3.2011, x86_64, Intel(R) Core(TM) i7-8700 CPU @ 3.20GHz (skylake), Python 3.6.8
See https://gist.github.com/387bbe97200ce6067c8c1b7a799a85e8 for a full test report.

**Comment by SebastianAchilles** [comment]
@boegelbot please test @ generoso

**Comment by branfosj** [comment]
Test report by @branfosj
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
bear-pg0211u08b.bear.cluster - Linux Ubuntu 20.04, x86_64, Intel(R) Xeon(R) Gold 6248 CPU @ 2.50GHz (cascadelake), Python 3.8.5
See https://gist.github.com/ce233b45bf0cfcd5f9afcae09d3f0903 for a full test report.

**Comment by branfosj** [comment]
Test report by @branfosj
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
bear-pg0211u03a.bear.cluster - Linux RHEL 8.3, x86_64, Intel(R) Xeon(R) Gold 6248 CPU @ 2.50GHz (cascadelake), Python 3.6.8
See https://gist.github.com/2457bb27f5e6d2b24e80946b111cf875 for a full test report.

**Review by branfosj — APPROVED** [review]
lgtm

**Comment by branfosj** [comment]
@SebastianAchilles Why not use the more recent snappy 1.1.9?

**Comment by SebastianAchilles** [comment]
> @SebastianAchilles Why not use the more recent snappy 1.1.9?

snappy v1.1.9 didn't work for me. That is why I wanted to check if v1.1.8 still works with GCC/11.2.0. What do you prefer: Do we want to use the old v1.1.8 or try to fix the installation of v1.1.9?

**Comment by boegel** [comment]
> > @SebastianAchilles Why not use the more recent snappy 1.1.9?
> 
> snappy v1.1.9 didn't work for me. That is why I wanted to check if v1.1.8 still works with GCC/11.2.0. What do you prefer: Do we want to use the old v1.1.8 or try to fix the installation of v1.1.9?

Depends on how broken it is, I guess. What trouble did you run into?

**Comment by branfosj** [comment]
See #13631

**Comment by SebastianAchilles** [comment]
Closing in favor of https://github.com/easybuilders/easybuild-easyconfigs/pull/13631

**Pull request closed without merging**
