### PR TITLE
remove executable flag from easyconfigs

### PR DESCRIPTION
**Pull request by Flamefire**
I found a bunch of ECs that were marked executable which they clearly should not. Might even be bad for security

I fixed that and added a test, that (changed) ECs are readable, owner-writable and non-executable, i.e. at least 0644 without any executable flag.

An example failure I forced to test the test:
`AssertionError: CFITSIO-3.34-ictce-5.5.0.eb must be readable (owner, group, other), not executable, at least owner writable, is: 0o100511`

As some of the ECs (mostly/only? in `__archive__`) didn't parse correctly anymore making the test fail I did the minimal changes to fix them.

### CODE REVIEW

**Comment by Flamefire** [comment]
Lot's of issues with existing ECs in test_pr_sanity_check_paths, test_pr_sha256_checksums & test_pr_python_packages

How do you want to proceed?

**Comment by Flamefire** [comment]
@smoors Rebased after merge of #18647 
The files tab shows that only permissions got changed (except for the commit attempting to fix CI by addressing the parse failures)

Would be great to get this merged as there were 4 new files with wrong permissions (likely C&P) but getting all the tests to pass is more work than it's worth

**Comment by boegel** [comment]
this should be a significant help here:

* #18753

**Comment by Flamefire** [comment]
Rebased to include #18753, let's see if that fixes CI

**Comment by Flamefire** [comment]
@boegel How to proceed here?

**Comment by boegel** [comment]
@Flamefire It's probably better to re-do this exercises in the `5.0.x` branch (which will soon-ish become `develop` once the last EasyBuild 4.x release has been published), since a lot of easyconfigs have been archived there already

**Comment by Flamefire** [comment]
Agree to do that in addition but I'd expect users to still use the (next) 4.x release to copy ECs from and submit PRs so fleshing out those issues is IMO cheap enough to do here once in bulk

**Comment by boegel** [comment]
> Agree to do that in addition but I'd expect users to still use the (next) 4.x release to copy ECs from and submit PRs so fleshing out those issues is IMO cheap enough to do here once in bulk

OK, but the failing CI is making that a really painful merge...

Do we have a test in place to verify that easyconfigs touched in a PR don't have exec permissions?

**Comment by Flamefire** [comment]
> OK, but the failing CI is making that a really painful merge...

Can't you ignore the failing CI and still merge that? Other PRs should succeed then (There already was one where the exec permissions led to failures unrelated to the changes in that PR)
Also the CI running on the branch (i.e. after merge) doesn't take those changed ECs into account and hence wouldn't fail either, would it?

Hence I think it is less painful to do that straight-forward merge here once and ignore CI than to have contributors have to deal with the possible many times in the future.

> Do we have a test in place to verify that easyconfigs touched in a PR don't have exec permissions?

Yes, since https://github.com/easybuilders/easybuild-easyconfigs/pull/18647

**Comment by Flamefire** [comment]
Maybe we can merge this and #11148 when collapsing develop and 5.0x? I guess we'll need to ignore CI for that step anyway and a few failures (like "no `use_pip`) will already go away with the new defaults and checks

**Comment by Flamefire** [comment]
Closing after https://github.com/easybuilders/easybuild-easyconfigs/pull/19059 for 5.x

**Pull request closed without merging**
