### PR TITLE
{bio}[foss/2022a] velocyto v0.17.17 w/ Python 3.10.4

### PR DESCRIPTION
**Pull request by boegel**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by boegel** [comment]
@boegelbot please test @ generoso

**Comment by boegel** [comment]
@boegelbot please test @ jsc-zen2

**Review by casparvl — APPROVED** [review]
Standard update, no surprises. Lgtm!

**Comment by casparvl** [comment]
Test report by @casparvl
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
tcn260.local.snellius.surf.nl - Linux Rocky Linux 8.7, x86_64, AMD EPYC 7H12 64-Core Processor, Python 3.6.8
See https://gist.github.com/819b662e9bc112b156a7ad89fbc0e254 for a full test report.

**Comment by casparvl** [comment]
Going in, thanks @boegel!

**Pull request merged**
