### PR TITLE
add wrapper for Julia with linking safeguards and delegate environment setup to JuliaPackage

### PR DESCRIPTION
**Pull request by lexming**
(created using `eb --new-pr`)

Fixes https://github.com/easybuilders/easybuild-easyconfigs/issues/17692
Alternative fix for https://github.com/easybuilders/easybuild-easyconfigs/pull/19650

Depends on:
* [ ] https://github.com/easybuilders/easybuild-easyblocks/pull/3239

Changelog:
* remove `modextravars`, the depot path will be set by the JuliaPackage easyblock with https://github.com/easybuilders/easybuild-easyblocks/pull/3239
* execute `julia` through a wrapper to ensure that the libraries bundled in Julia have precedence

### CODE REVIEW

**Comment by lexming** [comment]
@boegelbot: please test @ generoso

**Comment by lexming** [comment]
@boegelbot: please test @ generoso
EB_ARGS="Julia-1.10.0-linux-x86_64.eb Julia-1.6.5-linux-x86_64.eb Julia-1.6.6-linux-x86_64.eb Julia-1.6.7-linux-x86_64.eb Julia-1.7.0-linux-x86_64.eb Julia-1.7.1-linux-x86_64.eb Julia-1.7.2-linux-x86_64.eb Julia-1.7.3-linux-x86_64.eb Julia-1.8.0-linux-x86_64.eb Julia-1.8.2-linux-x86_64.eb Julia-1.8.5-linux-x86_64.eb Julia-1.9.0-linux-x86_64.eb Julia-1.9.2-linux-x86_64.eb Julia-1.9.3-linux-x86_64.eb"

**Comment by jfgrimm** [comment]
an alternative solution would be to replace the RUNPATH sections of all binaries/libraries in the Julia install dir with RPATH instead (so it takes precedence over LD_LIBRARY_PATH)

I played around with this, and something like this would do the trick:
```
find . -type f -exec sh -c "readelf -d {} | grep -Po1 '(?<=Library runpath: \[).*(?=\])' | xargs -r -I rpth patchelf --set-rpath \'rpth\' --force-rpath {}" \;
```

**Comment by jfgrimm** [comment]
an alternative solution would be to replace the RUNPATH sections of all binaries/libraries in the Julia install dir with RPATH instead (so it takes precedence over LD_LIBRARY_PATH)

I played around with this, and something like this would do the trick:
```
find . -type f -exec sh -c "readelf -d {} | grep -Po1 '(?<=Library runpath: \[).*(?=\])' | xargs -r -I rpth patchelf --set-rpath \'rpth\' --force-rpath {}" \;
```

**Comment by lexming** [comment]
@boegelbot: please test @ generoso
EB_ARGS="Julia-1.10.0-linux-x86_64.eb Julia-1.6.5-linux-x86_64.eb Julia-1.6.6-linux-x86_64.eb Julia-1.6.7-linux-x86_64.eb Julia-1.7.0-linux-x86_64.eb Julia-1.7.1-linux-x86_64.eb Julia-1.7.2-linux-x86_64.eb Julia-1.7.3-linux-x86_64.eb Julia-1.8.0-linux-x86_64.eb Julia-1.8.2-linux-x86_64.eb Julia-1.8.5-linux-x86_64.eb Julia-1.9.0-linux-x86_64.eb Julia-1.9.2-linux-x86_64.eb Julia-1.9.3-linux-x86_64.eb"

**Comment by branfosj** [comment]
Test report by @branfosj
**SUCCESS**
Build succeeded for 14 out of 14 (14 easyconfigs in total)
bear-pg0105u03a - Linux RHEL 8.6, x86_64, Intel(R) Xeon(R) Platinum 8360Y CPU @ 2.40GHz (icelake), Python 3.6.8
See https://gist.github.com/branfosj/ce0202cec3746c5093b9a991f0e087e6 for a full test report.

**Review by branfosj — APPROVED** [review]

**Comment by branfosj** [comment]
Going in, thanks @lexming!

**Pull request merged**
