### PR TITLE
{tools}[dummy/dummy] EasyBuild v4.5.3

### PR DESCRIPTION
**Pull request by migueldiascosta**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by migueldiascosta** [comment]
@boegelbot please test @ generoso

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
node3517.doduo.os - Linux RHEL 8.2, x86_64, AMD EPYC 7552 48-Core Processor (zen2), Python 3.6.8
See https://gist.github.com/cae3f357f73e9999cd061719186d660f for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
node2620.swalot.os - Linux CentOS Linux 7.9.2009, x86_64, Intel(R) Xeon(R) CPU E5-2660 v3 @ 2.60GHz (haswell), Python 3.6.8
See https://gist.github.com/8caa20159566f49616f46dcb006f99db for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
easybuild2.novalocal - Linux UNKNOWN UNKNOWN, POWER, IBM pSeries (emulated by qemu) (power9le), Python 3.6.8
See https://gist.github.com/b5e99cf2368d8031773978e2cd2a855b for a full test report.

**Comment by boegel** [comment]
Also tested on Piz Daint @ CSCS (but uploading test report from there is problematic):

```
kehoste@daint106:~> eb --version
This is EasyBuild 4.5.3 (framework: 4.5.3, easyblocks: 4.5.3) on host daint106.

kehoste@daint106:~> eb --show-system-info
System information (daint106):

* OS:
  -> name: SLES
  -> type: Linux
  -> version: 15-SP1
  -> platform name: x86_64-unknown-linux

* CPU:
  -> vendor: Intel
  -> architecture: x86_64
  -> family: Intel
  -> arch name: broadwell
  -> model: Intel(R) Xeon(R) CPU E5-2650 v4 @ 2.20GHz
  -> speed: 2900.0
  -> cores: 24
  -> features: 3dnowprefetch,abm,acpi,adx,aes,aperfmperf,apic,arat,arch_perfmon,avx,avx2,bmi1,bmi2,bts,cat_l3,cdp_l3,clflush,cmov,constant_tsc,cpuid,cpuid_fault,cqm,cqm_llc,cqm_mbm_local,cqm_mbm_total,cqm_occup_llc,cx16,cx8,dca,de,ds_cpl,dtes64,dtherm,dts,epb,ept,erms,est,f16c,flexpriority,flush_l1d,fma,fpu,fsgsbase,fxsr,hle,ht,ibpb,ibrs,ida,intel_pt,invpcid,invpcid_single,lahf_lm,lm,mca,mce,md_clear,mmx,monitor,movbe,msr,mtrr,nonstop_tsc,nopl,nx,pae,pat,pbe,pcid,pclmulqdq,pdcm,pdpe1gb,pebs,pge,pln,pni,popcnt,pse,pse36,pti,pts,rdrand,rdseed,rdt_a,rdtscp,rep_good,rtm,sdbg,sep,smap,smep,smx,ss,ssbd,sse,sse2,sse4_1,sse4_2,ssse3,stibp,syscall,tm,tm2,tpr_shadow,tsc,tsc_adjust,tsc_deadline_timer,vme,vmx,vnmi,vpid,x2apic,xsave,xsaveopt,xtopology,xtpr

* software:
  -> glibc version: 2.26
  -> Python binary: /usr/bin/python3
  -> Python version: 3.6.12
  ```

**Review by boegel — APPROVED** [review]
lgtm

**Pull request merged**
