### PR TITLE
Unison

### PR DESCRIPTION
**Pull request by hajgato**

### CODE REVIEW

**Comment by boegel** [comment]
Jenkins: test this please

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 3 out of 3 (3 easyconfigs in this PR)
Linux SL 6.6, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.6.6
See https://gist.github.com/0c7fe9606307f37037dd for a full test report.

**Comment by boegel** [comment]
@hajgato: the OCaml easyconfig in here should be synced with the one in #1056, since we're adding extensions in there; #1056 is still WIP though, I hope to finish it soon

**Comment by hajgato** [comment]
@boegel: I will update this when #1056 is done.

**Comment by boegel** [comment]
@hajgato: test failed due to problem on Jenkins, we're working on it

**Comment by boegel** [comment]
Jenkins: test this please

**Comment by boegel** [comment]
Jenkins: test this please

**Comment by boegel** [comment]
Jenkins: test this please

**Comment by boegel** [comment]
@hajgato: needs a sync with `develop`?

**Comment by migueldiascosta** [comment]
@hajgato, this PR is being closed for the following reason(s): no activity for > 6 months.
Please don't hesitate to reopen this PR or add a comment if you feel this contribution is still relevant.
For more information on our policy w.r.t. closing PRs, see https://easybuild.readthedocs.io/en/latest/Contributing.html#why-a-pull-request-may-be-closed-by-a-maintainer

**Pull request closed without merging**
