### PR TITLE
{lib}[intel/2017a] XGBoost v0.6a2

### PR DESCRIPTION
**Pull request by boegel**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
node2573.golett.os - Linux centos linux 7.3.1611, Intel(R) Xeon(R) CPU E5-2680 v3 @ 2.50GHz, Python 2.7.5
See https://gist.github.com/165e901eff203d234c12a49df377668d for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 3 out of 3 (3 easyconfigs in this PR)
node2070.delcatty.os - Linux centos linux 7.3.1611, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.7.5
See https://gist.github.com/63290c06d7f213728e7b5db64c94f6a9 for a full test report.

**Comment by verdurin** [comment]
Test report by @verdurin
**FAILED**
Build succeeded for 7 out of 13 (3 easyconfigs in this PR)
ca005.camp.thecrick.org - Linux centos linux 7.3.1611, Intel(R) Xeon(R) CPU E5-2640 v3 @ 2.60GHz, Python 2.7.5
See https://gist.github.com/1edd4c90879aecdab2a5c8f4f72a10b8 for a full test report.

**Comment by boegel** [comment]
@verdurin Hmm, installation of `Python-3.5.2-intel-2016b.eb` failed due to a segfault, while `SQLite-3.17.0-intel-2017a.eb` fails with `sqlite3.c:(.text+0x2f6b5): undefined reference to `__builtin_add_overflow'`, I'm seeing neither of these problems...

**Comment by wpoely86** [comment]
Test report by @wpoely86
**SUCCESS**
Build succeeded for 3 out of 3 (3 easyconfigs in this PR)
nic66 - Linux centos linux 7.3.1611, Intel(R) Xeon(R) CPU E5-2680 v4 @ 2.40GHz, Python 2.7.5
See https://gist.github.com/425c810fc2cf216951b94d3987e8b816 for a full test report.

**Comment by verdurin** [comment]
@boegel I wondered whether the `SQLite` problem was an instance of this:

http://sqlite.1065341.n5.nabble.com/cannot-compile-sqlite3-with-intel-compiler-ICC-log-and-hints-for-a-possible-solution-td96543.html#a96564

but clearly you're not suffering.

Might just be a problem with the separate tree I'm using for `EB` reviews.

**Comment by verdurin** [comment]
Merging, thanks @boegel

**Comment by boegel** [comment]
@verdurin In your case, it was picking up `/home/camp/huffmaa/src/github/verdurin-easyconfigs-devel/SQLite-3.17.0-intel-2017a.eb` rather than using the `SQLite-3.17.0-GCCcore-6.3.0.eb` that's in `develop`, making you hit https://github.com/rstats-db/RSQLite/issues/223...

**Pull request merged**
