### PR TITLE
{bio}[GCCcore/8.3.0] dcm2niix v1.0.20200331, dcm2niix v1.0.20201102

### PR DESCRIPTION
**Pull request by crubb**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by crubb** [comment]
Test report by @crubb
**SUCCESS**
Build succeeded for 3 out of 3 (3 easyconfigs in this PR)
hilbert51 - Linux centos linux 7.7.1908, x86_64, Intel(R) Xeon(R) CPU E5-2697 v2 @ 2.70GHz, Python 2.7.5
See https://gist.github.com/936c622e13179f4e88bc3af2ea1e1799 for a full test report.

**Comment by smoors** [comment]
Test report by @smoors
**SUCCESS**
Build succeeded for 3 out of 3 (3 easyconfigs in total)
node381.hydra.os - Linux centos linux 7.9.2009, x86_64, Intel(R) Xeon(R) Gold 6148 CPU @ 2.40GHz (skylake_avx512), Python 2.7.5
See https://gist.github.com/57af5b1b4735d286f4b3a8ca8848dbb5 for a full test report.

**Review by smoors — APPROVED** [review]
lgtm

**Comment by smoors** [comment]
Going in, thanks @crubb!

**Pull request merged**
