### PR TITLE
{bio}[foss/2016b] NextGenMap 0.5.5

### PR DESCRIPTION
**Pull request by SethosII**
This adds NextGenMap.

I can't think of a good `sanity_check_commands` line because printing the help message returns with non-zero exit code (says: `unrecognized option` :/ I opened an issue for this: https://github.com/Cibiv/NextGenMap/issues/29) and a real example would need additional data.

One other thing to note: by default the binaries are placed under `bin/ngm-<version>/` so I copy them with `installopts` one directory up. Is this ok?

### CODE REVIEW

**Comment by boegel** [comment]
@SethosII A sanity check command is a nice to have, it's not a huge issue if it's missing.

I wouldn't copy the binaries, just make sure they're available in that location via `$PATH`, by adding a line like this:

```python
modextrapaths = {'PATH': ['bin/ngm-%(version)s']}

**Comment by SethosII** [comment]
@boegel Ok.

A clarfification regarding the binaries: they aren't installed as usual but have to be copied.

> Please note that NextGenMap doesn’t follow the typical make/make install approach. Instead running make creates a directory called ngm-0.×.x in the bin folder that contains all files required to run NextGenMap.

**Comment by boegel** [comment]
@SethosII In that case we should be skipping the `install` step?

**Comment by SethosII** [comment]
@boegel Like so?

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
node2406.golett.os - Linux centos linux 7.4.1708, Intel(R) Xeon(R) CPU E5-2680 v3 @ 2.50GHz, Python 2.7.5
See https://gist.github.com/f17785ddbbfe098a4c0526f0acfaabed for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
node2066.delcatty.os - Linux centos linux 7.4.1708, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.7.5
See https://gist.github.com/1ab59b4dfd0221ff379910c195ee1c70 for a full test report.

**Comment by boegel** [comment]
Going in, thanks @SethosII!

**Pull request merged**
