### PR TITLE
{lib}[GCCcore/10.2.0,foss/2020b,fosscuda/2020b] tensorflow-probability v0.12.1, dm-tree v0.1.5 w/ Python 3.8.6

### PR DESCRIPTION
**Pull request by dithwick**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by dithwick** [comment]
That was weird, I removed the versionsuffix and used --update-pr to send the updated files and it uploaded them as separate files!

**Comment by dithwick** [comment]
Okay I get it, the version suffix was automatically added to the end of the file based on the contents of the easyconfig.

**Review by branfosj — APPROVED** [review]
lgtm

**Comment by branfosj** [comment]
@boegelbot please test @ generoso

**Comment by branfosj** [comment]
Test report by @branfosj
**SUCCESS**
Build succeeded for 3 out of 3 (3 easyconfigs in total)
bear-pg0210u09b.bear.cluster - Linux centos linux 8.2.2004, x86_64, Intel(R) Xeon(R) CPU E5-2640 v4 @ 2.40GHz (broadwell), Python 3.6.8
See https://gist.github.com/e11229b5a8c1847215d800f9cd262706 for a full test report.

**Comment by branfosj** [comment]
Going in, thanks @dithwick!

**Pull request merged**
