### PR TITLE
{math}[GCCcore/11.2.0] GLPK v5.0, GMP v6.2.1, ISL v0.24, ...

### PR DESCRIPTION
**Pull request by SebastianAchilles**
(created using `eb --new-pr`)
Depends on
- [x] `Autotools` https://github.com/easybuilders/easybuild-easyconfigs/pull/13576

### CODE REVIEW

**Comment by SebastianAchilles** [comment]
Test report by @sebastianachilles
**SUCCESS**
Build succeeded for 6 out of 6 (6 easyconfigs in total)
centos8-eb - Linux centos linux 8.3.2011, x86_64, Intel(R) Core(TM) i7-8700 CPU @ 3.20GHz (skylake), Python 3.6.8
See https://gist.github.com/5bd1ef4f923aaec9e2a38498f83124e1 for a full test report.

**Review by Micket — APPROVED** [review]
lgtm

**Comment by Micket** [comment]
Test report by @Micket
**SUCCESS**
Build succeeded for 6 out of 6 (6 easyconfigs in total)
alvis-c1 - Linux centos linux 7.9.2009, x86_64, Intel Xeon Processor (Skylake), Python 3.6.8
See https://gist.github.com/4d096df20aefb6f9f638de80a8f45720 for a full test report.

**Review by Micket — APPROVED** [review]
lgtm (wopps, duplicate approval :D that what happens when you try to multitask)

**Pull request merged**
