### PR TITLE
add patch to fix installation of TensorFlow 2.0.x

### PR DESCRIPTION
**Pull request by Flamefire**
(created using `eb --new-pr`)

### CODE REVIEW

**Review by Micket — DISMISSED** [review]
lgtm

**Review by Micket — DISMISSED** [review]
still lgtm

**Comment by Micket** [comment]
Test report by @Micket
Using easyblocks from PR(s) https://github.com/easybuilders/easybuild-easyblocks/pull/2469
**FAILED**
Build succeeded for 1 out of 2 (2 easyconfigs in total)
vera54-1 - Linux centos linux 7.9.2009, x86_64, Intel(R) Xeon(R) Gold 6130 CPU @ 2.10GHz, Python 3.6.8
See https://gist.github.com/ea866d263e437f2091846d20c2d4979c for a full test report.

**Comment by Micket** [comment]
No idea why the 2019a version failed. at least it installs, but then I hit
```
== 2021-06-23 22:14:49,811 run.py:226 INFO running cmd: python -c "import google.protobuf"
== 2021-06-23 22:14:50,002 extensioneasyblock.py:181 INFO Sanity check for protobuf successful!
...
== 2021-06-23 22:14:58,315 run.py:226 INFO running cmd: python -c "import tensorflow_estimator"
== 2021-06-23 22:14:58,590 extension.py:218 WARNING Sanity check for 'tensorflow-estimator' extension failed: command "python -c "import tensorflow_estimator"" failed; output:
Traceback (most recent call last):
  File "/apps/Vera/software/TensorFlow/2.0.0-foss-2019a-Python-3.7.2/lib/python3.7/site-packages/tensorflow_core/python/pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "/apps/Vera/software/TensorFlow/2.0.0-foss-2019a-Python-3.7.2/lib/python3.7/site-packages/tensorflow_core/python/pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "/apps/Vera/software/TensorFlow/2.0.0-foss-2019a-Python-3.7.2/lib/python3.7/site-packages/tensorflow_core/python/pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "/apps/Vera/software/Python/3.7.2-GCCcore-8.2.0/lib/python3.7/imp.py", line 242, in load_module
    return load_dynamic(name, filename, file)
  File "/apps/Vera/software/Python/3.7.2-GCCcore-8.2.0/lib/python3.7/imp.py", line 342, in load_dynamic
    return _load(spec)
ImportError: libprotobuf.so.3.7.1.0: cannot open shared object file: No such file or directory
```

**Comment by Flamefire** [comment]
Test report by @Flamefire
**FAILED**
Build succeeded for 3 out of 5 (4 easyconfigs in total)
taurusa4 - Linux centos linux 7.7.1908, x86_64, Intel(R) Xeon(R) CPU E5-2603 v4 @ 1.70GHz (broadwell), Python 2.7.5
See https://gist.github.com/6fe36ade96d4047e5a9fdaa959d4b8ca for a full test report.

**Comment by Flamefire** [comment]
Test report by @Flamefire
Using easyblocks from PR(s) https://github.com/easybuilders/easybuild-easyblocks/pull/2469
**FAILED**
Build succeeded for 3 out of 5 (4 easyconfigs in total)
taurusa5 - Linux centos linux 7.7.1908, x86_64, Intel(R) Xeon(R) CPU E5-2603 v4 @ 1.70GHz (broadwell), Python 2.7.5
See https://gist.github.com/e624e38473481e63c990c320f2c59013 for a full test report.

**Comment by boegel** [comment]
@boegelbot please test @ generoso
EB_ARGS="--include-easyblocks-from-pr 2469"
CORE_CNT=16

**Comment by Flamefire** [comment]
I'm not fully sure why this wasn't caught before but I think the TF_SYSTEM_LIB things were introduced AFTER 2.0.0 and all the tested ECs used protobuf-python as runtime dep which has protobuf as a dep so the issue was hidden.
Fixed. Reports coming up.
@boegel You might want to restart your tests

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 8 out of 8 (4 easyconfigs in total)
node3302.joltik.os - Linux centos linux 7.9.2009, x86_64, Intel(R) Xeon(R) Gold 6242 CPU @ 2.80GHz (cascadelake), Python 3.6.8
See https://gist.github.com/8ab91863cd850a7783a366cf10dbae58 for a full test report.

**Review by Micket — APPROVED** [review]
lgtm

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 11 out of 11 (4 easyconfigs in total)
node3120.skitty.os - Linux centos linux 7.9.2009, x86_64, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz, Python 3.6.8
See https://gist.github.com/acd414ad13ea034061c0a60e7e63098f for a full test report.

**Comment by boegel** [comment]
Going in, thanks @Flamefire!

**Pull request merged**
