### PR TITLE
update deepTools

### PR DESCRIPTION
**Pull request by fizwit**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by fizwit** [comment]
There are two versions of Pysam for 2021b.  The tests are failing because of this.  How do I resolve this?

**Comment by jfgrimm** [comment]
> There are two versions of Pysam for 2021b. The tests are failing because of this. How do I resolve this?

Most other easyconfigs in `2021b` use Pysam version `0.17.0`, so unless deepTools has a strong need for `0.18.0` I would suggest using that version. Otherwise, add an exception here https://github.com/easybuilders/easybuild-easyconfigs/blob/develop/test/easyconfigs/easyconfigs.py#L544

**Review by casparvl — APPROVED** [review]
Straightforward version update, no unexpected changes seen with `--review-pr`. LGTM!

**Comment by casparvl** [comment]
@boegelbot please test @ generoso

**Comment by casparvl** [comment]
Test report by @casparvl
**SUCCESS**
Build succeeded for 16 out of 16 (1 easyconfigs in total)
software2.lisa.surfsara.nl - Linux debian 10.11, x86_64, Intel(R) Xeon(R) Bronze 3104 CPU @ 1.70GHz, 4 x NVIDIA NVIDIA TITAN V, 470.103.01, Python 2.7.16
See https://gist.github.com/a1be4ad24e66a98b7ea56663a518b781 for a full test report.

**Comment by casparvl** [comment]
Going in, thanks @fizwit!

**Pull request merged**
