### PR TITLE
{bio}[system/system] IGV v2.17.4 w/ Java 17

### PR DESCRIPTION
**Pull request by verdurin**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by verdurin** [comment]
Test report by @verdurin
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
easybuild-c7.novalocal - Linux CentOS Linux 7.9.2009, x86_64, Intel Xeon Processor (Skylake, IBRS), Python 3.6.8
See https://gist.github.com/verdurin/4c81a7fc969a69b109866f4d2bbeeda7 for a full test report.

**Comment by verdurin** [comment]
@boegelbot please test @ generoso

**Review by Micket — DISMISSED** [review]
eb files must not be executable

**Comment by verdurin** [comment]
Odd - that came from the upstream file I copied. No idea why it was there...

**Comment by bedroge** [comment]
@boegelbot please test @ jsc-zen3

**Comment by bedroge** [comment]
Test report by @bedroge
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
bob-Latitude-5300 - Linux Ubuntu 22.04, x86_64, Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz, Python 3.10.12
See https://gist.github.com/bedroge/c0925ccfb2f812b7fd8375b255b4d490 for a full test report.

**Review by bedroge — APPROVED** [review]
Looks good to me

**Comment by bedroge** [comment]
Going in, thanks @verdurin!

**Pull request merged**
