### PR TITLE
{chem}[foss/2018a,intel/2018a] phono3py v1.12.7.55

### PR DESCRIPTION
**Pull request by migueldiascosta**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by migueldiascosta** [comment]
Test report by @migueldiascosta
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in this PR)
grc-cluster1 - Linux centos 6.9, Intel(R) Xeon(R) CPU E5-2640 0 @ 2.50GHz, Python 2.6.6
See https://gist.github.com/3ed6275de53830b71cba10389b550f4c for a full test report.

**Comment by migueldiascosta** [comment]
Test report by @migueldiascosta
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in this PR)
grc-cluster1 - Linux centos 6.9, Intel(R) Xeon(R) CPU E5-2640 0 @ 2.50GHz, Python 2.6.6
See https://gist.github.com/05d2c6f872ecaa195c7447f1d8799297 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in this PR)
node2009.delcatty.os - Linux centos linux 7.4.1708, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.7.5
See https://gist.github.com/da0eafb75bb5c6ac571f08d1d41e248f for a full test report.

**Comment by boegel** [comment]
@migueldiascosta The existing `phono3py` easyconfigs don't have a dependency on `phonopy`, is that new?

**Comment by migueldiascosta** [comment]
@boegel it used to be bundled but not anymore

**Comment by boegel** [comment]
Going in, thanks @migueldiascosta!

**Pull request merged**
