### PR TITLE
{lib}[GCCcore/12.3.0] Mesa v23.1.4, Mako v1.2.4, libdrm v2.4.115, libglvnd v1.6.0

### PR DESCRIPTION
**Pull request by boegel**
(created using `eb --new-pr`)
requires:
* https://github.com/easybuilders/easybuild-easyblocks/pull/2973
* https://github.com/easybuilders/easybuild-easyconfigs/pull/18433

### CODE REVIEW

**Comment by boegel** [comment]
@boegelbot please test @ generoso
EB_ARGS="--include-easyblocks-from-pr 2973"

**Comment by casparvl** [comment]
@boegelbot please test @ jsc-zen2
EB_ARGS="--include-easyblocks-from-pr 2973"

**Comment by casparvl** [comment]
Test report by @casparvl
**FAILED**
Build succeeded for 14 out of 15 (4 easyconfigs in total)
tcn240.local.snellius.surf.nl - Linux RHEL 8.6, x86_64, AMD EPYC 7H12 64-Core Processor, Python 3.6.8
See https://gist.github.com/casparvl/da497e85211932be81835f08a528c9da for a full test report.

**Comment by casparvl** [comment]
@boegelbot my failure is 
```
Sanity check failed: no file found at 'include/EGL/eglextchromium.h' in /scratch-nvme/1/casparl/generic/software/Mesa/23.1.4-GCCcore-12.3.0
```

I also don't see this file in the sources, so I'm not sure where it's supposed to come from. Just to be sure, I'll force a redownload of the sources, but any difference should have been caught by a checksum I suppose...

**Comment by casparvl** [comment]
Test report by @casparvl
**FAILED**
Build succeeded for 3 out of 4 (4 easyconfigs in total)
tcn240.local.snellius.surf.nl - Linux RHEL 8.6, x86_64, AMD EPYC 7H12 64-Core Processor, Python 3.6.8
See https://gist.github.com/casparvl/6ed40920a9c05184762a71b4c9b6eeec for a full test report.

**Comment by SebastianAchilles** [comment]
Test report by @sebastianachilles
Using easyblocks from PR(s) https://github.com/easybuilders/easybuild-easyblocks/pull/2973
**SUCCESS**
Build succeeded for 4 out of 4 (4 easyconfigs in total)
zen2-ubuntu-2304 - Linux Ubuntu 23.04 (Lunar Lobster), x86_64, AMD EPYC 7452 32-Core Processor (zen2), Python 3.11.2
See https://gist.github.com/SebastianAchilles/27174cdea27817bb8c418a115f3c1852 for a full test report.

**Comment by casparvl** [comment]
> @casparvl did you use the new easyblock from [easybuilders/easybuild-easyblocks#2973](https://github.com/easybuilders/easybuild-easyblocks/pull/2973) (e.g. with `--include-easyblocks-from-pr 2973`)? This MR adds `eglext_angle.h` to the sanity check for Mesa >= 22.3, which replaces `eglextchromium.h`.

Silly me, you're right, I forgot. Let me retry, but that must have been the issue.

**Comment by casparvl** [comment]
Test report by @casparvl
Using easyblocks from PR(s) https://github.com/easybuilders/easybuild-easyblocks/pull/2973
**SUCCESS**
Build succeeded for 4 out of 4 (4 easyconfigs in total)
tcn415.local.snellius.surf.nl - Linux RHEL 8.6, x86_64, AMD EPYC 7H12 64-Core Processor, Python 3.6.8
See https://gist.github.com/casparvl/1181211ee941c34ea7ba8362f3cd0b6e for a full test report.

**Review by casparvl — APPROVED** [review]
Lgtm!

**Comment by casparvl** [comment]
Going in, thanks @boegel!

**Pull request merged**
