### PR TITLE
add easyconfigs for BSgenome + deps with intel/2015a

### PR DESCRIPTION
**Pull request by boegel**
depends on #1289 for R easyconfig

### CODE REVIEW

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 6 out of 6 (6 easyconfigs in this PR)
Linux SL 6.6, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.6.6
See https://gist.github.com/a3954202c4bc39a396f4 for a full test report.

**Comment by boegel** [comment]
@wpoely86: please review

**Comment by wpoely86** [comment]
looks fine

**Comment by boegel** [comment]
also add an easyconfig for http://master.bioconductor.org/packages/release/data/annotation/html/BSgenome.Hsapiens.UCSC.hg19.html to make @pescobar happy?

**Comment by boegel** [comment]
we need a different solution for R extensions that pull in external dependencies, cfr. https://github.com/hpcugent/easybuild-easyconfigs/pull/1289#issuecomment-70821218

**Comment by migueldiascosta** [comment]
@boegel, this PR is being closed for the following reason(s): no activity for > 6 months.
Please don't hesitate to reopen this PR or add a comment if you feel this contribution is still relevant.
For more information on our policy w.r.t. closing PRs, see https://easybuild.readthedocs.io/en/latest/Contributing.html#why-a-pull-request-may-be-closed-by-a-maintainer

**Pull request closed without merging**
