### PR TITLE
{bio}[GCCcore/11.2.0] RNA-SeQC v1.1.8

### PR DESCRIPTION
**Pull request by SethosII**
(created using `eb --new-pr`)

I'm not sure about the Java version to use with the toolchain.

Also, I received this warning while building it:

```
WARNING: Suppressed adding the following path(s) to $CLASSPATH of the module as they were already added: ['RNA-SeQC_v1.1.8.jar']
```

Is this to be expected?

### CODE REVIEW

**Comment by jfgrimm** [comment]
@SethosII are you aware there are newer releases here: https://github.com/getzlab/rnaseqc

**Comment by SethosII** [comment]
@jfgrimm Yes, I also created a pull request for this, but we currently use both.

**Comment by branfosj** [comment]
Test report by @branfosj
**SUCCESS**
Build succeeded for 2 out of 2 (1 easyconfigs in total)
bear-pg0105u03a.bear.cluster - Linux RHEL 8.6, x86_64, Intel(R) Xeon(R) Platinum 8360Y CPU @ 2.40GHz (icelake), Python 3.6.8
See https://gist.github.com/branfosj/e7dc64929c4eaa14a83d5d360ab77891 for a full test report.

**Comment by branfosj** [comment]
@boegelbot please test @ generoso

**Review by branfosj — APPROVED** [review]

**Comment by branfosj** [comment]
Going in, thanks @SethosII!

**Pull request merged**
