### PR TITLE
{vis}[GCCcore/10.2.0,GCCcore/12.2.0] GLI v4.5.31

### PR DESCRIPTION
**Pull request by kosl**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by verdurin** [comment]
@boegelbot please test @ generoso

**Review by Micket — APPROVED** [review]
lgtm that fix should resolve the issue verdurin had on centos7.

**Comment by Micket** [comment]
@boegelbot please test @ generoso

**Comment by Micket** [comment]
Test report by @Micket
**SUCCESS**
Build succeeded for 3 out of 3 (2 easyconfigs in total)
vera-c1 - Linux Rocky Linux 8.6, x86_64, Intel Xeon Processor (Skylake), Python 3.6.8
See https://gist.github.com/Micket/9a23c553ba1ed715a95a365096cace86 for a full test report.

**Comment by Micket** [comment]
Going in, thanks @kosl!

**Pull request merged**
