### PR TITLE
{tools}[GCC/9.3.0] ecCodes v2.19.0

### PR DESCRIPTION
**Pull request by mboisson**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by verdurin** [comment]
@mboisson I guess `netCDF.Serial` is an internal easyconfig at CC?

Were you planning to submit that and the newer `JasPer`?

**Comment by verdurin** [comment]
For reference, the `netCDF.Serial` PR is #11574

**Comment by mboisson** [comment]
Yes, the netCDF.Serial is in the other PR. Didn't realize the newer JasPer was local to us. I can open a PR for it.

**Comment by mboisson** [comment]
PR for new JasPer is here : https://github.com/easybuilders/easybuild-easyconfigs/pull/11605

**Comment by boegel** [comment]
closing this since `GCC/9.3.0` is deprecated, see https://docs.easybuild.io/policies/toolchains

**Pull request closed without merging**
