### PR TITLE
{math}[foss/2018a] gmsh v4.8.4 w/ Python 3.6.4

### PR DESCRIPTION
**Pull request by boegel**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
node2619.swalot.os - Linux centos linux 7.9.2009, x86_64, Intel(R) Xeon(R) CPU E5-2660 v3 @ 2.60GHz (haswell), Python 3.6.8
See https://gist.github.com/dcd46798b8106f0c4e160566ce9ea1fc for a full test report.

**Comment by verdurin** [comment]
@boegelbot please test @ generoso

**Comment by verdurin** [comment]
Test report by @verdurin
**SUCCESS**
Build succeeded for 9 out of 9 (1 easyconfigs in total)
easybuild-c7.novalocal - Linux centos linux 7.9.2009, x86_64, Intel Xeon Processor (Skylake, IBRS), Python 3.6.8
See https://gist.github.com/7a203f78738cd8e0d4475e2ca78601a9 for a full test report.

**Comment by verdurin** [comment]
@boegel I'm guessing the `generoso` build failure is down to the age of the toolchain. Are you happy to merge anyway?

**Comment by Micket** [comment]
I'd say just merge it anyway. The errors aren't due to this PR, so, no downside to merging this.

**Review by verdurin — APPROVED** [review]
Looks fine.

**Comment by verdurin** [comment]
Going in, thanks @boegel!

**Pull request merged**
