### PR TITLE
{astro}[GCCcore/8.2.0] HEALPix v3.50

### PR DESCRIPTION
**Pull request by jose-d**
(created using `eb --new-pr`)

:warning: : requires ~~#8472~~

### CODE REVIEW

**Comment by jose-d** [comment]
Test report by @jose-d
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
koios1 - Linux centos linux 7.6.1810, Intel(R) Xeon(R) Gold 6130 CPU @ 2.10GHz, Python 2.7.5
See https://gist.github.com/2a7c3a4998e92010464260cd9ff45346 for a full test report.

**Comment by jose-d** [comment]
remaining TODO:

- [ ] remove `sanity_check_commands` as they were added into easyblock here: https://github.com/jose-d/easybuild-easyblocks/pull/2

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
node3102.skitty.os - Linux centos linux 7.6.1810, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz, Python 2.7.5
See https://gist.github.com/3927158899b655f9edf50d5568f8d3a8 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
node2633.swalot.os - Linux centos linux 7.6.1810, Intel(R) Xeon(R) CPU E5-2660 v3 @ 2.60GHz, Python 2.7.5
See https://gist.github.com/1dd1fe6706383d5b3cb10d689f6bfb77 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
node2045.delcatty.os - Linux centos linux 7.6.1810, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.7.5
See https://gist.github.com/74e772d45825f23d98a2ef69c46d1dc8 for a full test report.

**Comment by boegel** [comment]
Going in, thanks @jose-d!

**Pull request merged**
