### PR TITLE
{geo}[foss/2019b] RHESSysEastCoast v7.2.0

### PR DESCRIPTION
**Pull request by alexandermichels**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by alexandermichels** [comment]
Test report by @alexandermichels
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
8af8d10c46bf - Linux Ubuntu 20.04.3 LTS (Focal Fossa), x86_64, Intel(R) Xeon(R) CPU E5-2660 v3 @ 2.60GHz, Python 3.8.10
See https://gist.github.com/9bf0ba1c8f886fec2e704f8f92ee321b for a full test report.

**Comment by alexandermichels** [comment]
A bit of information on this: RHESSysEastCoast (https://github.com/laurencelin/RHESSysEastCoast) used in the Hydrological community. For example, see https://www.hydroshare.org/resource/631914af4b8344e5a78e647255cf1d13/ . The Easyconfig is currently being used on our Jupyter instance: https://go.illinois.edu/cybergis-jupyter-water/

**Comment by alexandermichels** [comment]
Test report by @alexandermichels
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
8af8d10c46bf - Linux Ubuntu 20.04.3 LTS (Focal Fossa), x86_64, Intel(R) Xeon(R) CPU E5-2660 v3 @ 2.60GHz, Python 3.8.10
See https://gist.github.com/5d3de06a4fd8b750ee72e286aef60418 for a full test report.

**Comment by boegel** [comment]
closing this since `foss/2019b` is no longer supported, see https://docs.easybuild.io/policies/toolchains

Sorry for not getting back on this @zdemat...

If `RHESSysEastCoast` is still relevant, please consider opening a new pull request with a more recent toolchain.

**Pull request closed without merging**
