### PR TITLE
{tools}[foss/2020b,intel/2020b] ToFu v1.5.0 w/ Python 3.8.6

### PR DESCRIPTION
**Pull request by kosl**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by kosl** [comment]
makedepend, g2clib, and g2lib are added by mistake and can be removed, See #15327

**Comment by migueldiascosta** [comment]
@boegelbot please test @ generoso

**Review by migueldiascosta — APPROVED** [review]
lgtm

**Comment by migueldiascosta** [comment]
Going in, thanks @kosl!

**Pull request merged**
