### PR TITLE
{chem}[intel/2023a] GPAW v24.1.0

### PR DESCRIPTION
**Pull request by schiotz**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by schiotz** [comment]
This version of GPAW fixes a rather serious bug, where GPAW in some rare circumstances would give the wrong result. See https://wiki.fysik.dtu.dk/gpaw/releasenotes.html#version-24-1-0

This PR is depending on SciPy-bundle from PR #18875 - unfortunately SciPy-bundle is not yet available for any recent intel toolchain.

**Comment by schiotz** [comment]
Closing and reopening to run test suite after https://github.com/easybuilders/easybuild-easyconfigs/pull/18875 was merged.

**Comment by schiotz** [comment]
Test report by @schiotz
**FAILED**
Build succeeded for 3 out of 4 (4 easyconfigs in total)
svol.fysik.dtu.dk - Linux CentOS Linux 7.9.2009, x86_64, Intel(R) Xeon(R) Gold 6148 CPU @ 2.40GHz, Python 3.6.8
See https://gist.github.com/schiotz/a81277c3c4da0518698050d1d4d5e7ee for a full test report.

**Comment by schiotz** [comment]
Test report by @schiotz
**FAILED**
Build succeeded for 3 out of 4 (4 easyconfigs in total)
slid.fysik.dtu.dk - Linux CentOS Linux 7.9.2009, x86_64, Intel(R) Xeon(R) CPU E5-2650 v4 @ 2.20GHz, Python 3.6.8
See https://gist.github.com/schiotz/741528f100ec2a4b9f744275008a9eb7 for a full test report.

**Comment by schiotz** [comment]
Test report by @schiotz
**SUCCESS**
Build succeeded for 5 out of 5 (4 easyconfigs in total)
svol.fysik.dtu.dk - Linux CentOS Linux 7.9.2009, x86_64, Intel(R) Xeon(R) Gold 6148 CPU @ 2.40GHz, Python 3.6.8
See https://gist.github.com/schiotz/80747b3ce3233fac42d7ead01e902702 for a full test report.

**Comment by schiotz** [comment]
Test report by @schiotz
**SUCCESS**
Build succeeded for 5 out of 5 (4 easyconfigs in total)
slid.fysik.dtu.dk - Linux CentOS Linux 7.9.2009, x86_64, Intel(R) Xeon(R) CPU E5-2650 v4 @ 2.20GHz, Python 3.6.8
See https://gist.github.com/schiotz/a0c25e1b6fac21eae5bcd01106b25d0b for a full test report.

**Comment by branfosj** [comment]
@boegelbot please test @ generoso

**Comment by branfosj** [comment]
@boegelbot please test @ jsc-zen3

**Comment by branfosj** [comment]
Test report by @branfosj
**SUCCESS**
Build succeeded for 14 out of 14 (4 easyconfigs in total)
bear-pg0207u28a.bear.cluster - Linux RHEL 8.6, x86_64, AMD EPYC 9554 64-Core Processor (zen4), Python 3.6.8
See https://gist.github.com/branfosj/28b3bd2e591b76a9282df041ecaabd83 for a full test report.

**Review by branfosj — APPROVED** [review]

**Comment by branfosj** [comment]
Test report by @branfosj
**SUCCESS**
Build succeeded for 14 out of 14 (4 easyconfigs in total)
bear-pg0207u20a - Linux RHEL 8.6, x86_64, Intel(R) Xeon(R) Platinum 8480CL (sapphirerapids), Python 3.6.8
See https://gist.github.com/branfosj/aff2c010d5d6d15106f81993964e79fe for a full test report.

**Comment by branfosj** [comment]
Going in, thanks @schiotz!

**Pull request merged**
