### PR TITLE
{chem}[foss/2021b] LAMMPS v23Jun2022, Voro++ v0.4.6 w/ Python 3.9.6

### PR DESCRIPTION
**Pull request by ocaisa**
(created using `eb --new-pr`)
Requires https://github.com/easybuilders/easybuild-easyblocks/pull/2213

### CODE REVIEW

**Comment by ocaisa** [comment]
Test report by @ocaisa
Using easyblocks from PR(s) https://github.com/easybuilders/easybuild-easyblocks/pull/2213
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
login1 - Linux Rocky Linux 8.5, x86_64, Intel(R) Xeon(R) CPU E5-2690 v3 @ 2.60GHz, Python 3.6.8
See https://gist.github.com/7a6a02735149c913408115458daec74e for a full test report.

**Comment by ocaisa** [comment]
Test report by @ocaisa
Using easyblocks from PR(s) https://github.com/easybuilders/easybuild-easyblocks/pull/2213
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
login1 - Linux Rocky Linux 8.5, x86_64, Intel(R) Xeon(R) CPU E5-2690 v3 @ 2.60GHz, Python 3.6.8
See https://gist.github.com/56b122ab522c5771d45701c170dc1515 for a full test report.

**Comment by branfosj** [comment]
Test report by @branfosj
Using easyblocks from PR(s) https://github.com/easybuilders/easybuild-easyblocks/pull/2213
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in total)
bear-pg0105u36b.bear.cluster - Linux RHEL 8.6, x86_64, Intel(R) Xeon(R) Platinum 8360Y CPU @ 2.40GHz (icelake), Python 3.6.8
See https://gist.github.com/1dc5ba660d7fafaa3fc6bf4eee759259 for a full test report.

**Comment by branfosj** [comment]
Test report by @branfosj
Using easyblocks from PR(s) https://github.com/easybuilders/easybuild-easyblocks/pull/2213
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in total)
bear-pg0105u36b.bear.cluster - Linux RHEL 8.6, x86_64, Intel(R) Xeon(R) Platinum 8360Y CPU @ 2.40GHz (icelake), Python 3.6.8
See https://gist.github.com/a9d0ab99f5d76dd41d01549997ef2a97 for a full test report.

**Comment by branfosj** [comment]
Test report by @branfosj
Using easyblocks from PR(s) https://github.com/easybuilders/easybuild-easyblocks/pull/2213
**FAILED**
Build succeeded for 1 out of 2 (2 easyconfigs in total)
bear-pg0105u36b.bear.cluster - Linux RHEL 8.6, x86_64, Intel(R) Xeon(R) Platinum 8360Y CPU @ 2.40GHz (icelake), Python 3.6.8
See https://gist.github.com/f7cf9cea243413042947b1709a5617e2 for a full test report.

**Comment by ocaisa** [comment]
Test report by @ocaisa
Using easyblocks from PR(s) https://github.com/easybuilders/easybuild-easyblocks/pull/2213
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
login1 - Linux Rocky Linux 8.5, x86_64, Intel(R) Xeon(R) CPU E5-2690 v3 @ 2.60GHz, Python 3.6.8
See https://gist.github.com/2ce3f7959adc4c359a6f261276c9ad1b for a full test report.

**Comment by branfosj** [comment]
Test report by @branfosj
Using easyblocks from PR(s) https://github.com/easybuilders/easybuild-easyblocks/pull/2213
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in total)
bear-pg0105u36b.bear.cluster - Linux RHEL 8.6, x86_64, Intel(R) Xeon(R) Platinum 8360Y CPU @ 2.40GHz (icelake), Python 3.6.8
See https://gist.github.com/e37d0f1358b92a470a359c8491247289 for a full test report.

**Comment by ocaisa** [comment]
Test report by @ocaisa
Using easyblocks from PR(s) https://github.com/easybuilders/easybuild-easyblocks/pull/2213
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in total)
login1 - Linux Rocky Linux 8.5, x86_64, Intel(R) Xeon(R) CPU E5-2690 v3 @ 2.60GHz, Python 3.6.8
See https://gist.github.com/6aeddead079a4ac5f70278edf1735866 for a full test report.

**Comment by branfosj** [comment]
Test report by @branfosj
Using easyblocks from PR(s) https://github.com/easybuilders/easybuild-easyblocks/pull/2213
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in total)
bear-pg0105u36b.bear.cluster - Linux RHEL 8.6, x86_64, Intel(R) Xeon(R) Platinum 8360Y CPU @ 2.40GHz (icelake), Python 3.6.8
See https://gist.github.com/72f7fed133e76b18bed5f71239195eee for a full test report.

**Comment by branfosj** [comment]
@boegelbot please test @ generoso

**Comment by branfosj** [comment]
@boegelbot please test @ jsc-zen2

**Review by branfosj — APPROVED** [review]
lgtm

**Comment by branfosj** [comment]
Going in, thanks @ocaisa!

**Pull request merged**
