### PR TITLE
{lib}[foss/2021a] eht-imaging v1.2.2 w/ Python 3.9.5

### PR DESCRIPTION
**Pull request by Micket**
(created using `eb --new-pr`)

- [x] #14232
- [x] #14234
- [ ] #14235

### CODE REVIEW

**Comment by verdurin** [comment]
Test report by @verdurin
**FAILED**
Build succeeded for 4 out of 5 (1 easyconfigs in total)
easybuild-c7.novalocal - Linux centos linux 7.9.2009, x86_64, Intel Xeon Processor (Skylake, IBRS), Python 3.6.8
See https://gist.github.com/def12d050086354b0b75e526dc82f259 for a full test report.

**Comment by Micket** [comment]
i missed the patch, sorry

**Comment by Micket** [comment]
and update-pr doesn't want to work for this patch
```
$ eb --update-pr 14239 pyNFFT-1.3.2_fix_nfft3util_header.patch --pr-commit-msg="Add missing patch file"
== Temporary log file in case of crash /local/EB/build/eb-zyw_vzx7/easybuild-eknxj0m_.log
== Determined branch name corresponding to easybuilders/easybuild-easyconfigs PR #14239: 20211029030148_new_pr_eht-imaging122
== fetching branch '20211029030148_new_pr_eht-imaging122' from https://github.com/Micket/easybuild-easyconfigs.git...
== copying files to /local/EB/build/eb-zyw_vzx7/git-working-dirmjizue42/easybuild-easyconfigs...
== determining software names for patch files...
Matching easyconfig for pyNFFT-1.3.2_fix_nfft3util_header.patch not found on the first try:
scanning all easyconfigs to determine where patch file belongs (this may take a while)...
== found valid index for /apps/Common/software/EasyBuild/4.4.2/easybuild/easyconfigs, so using it...
77 of 3525 easyconfigs checkedTraceback (most recent call last):
  File "/usr/lib64/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib64/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/apps/Common/software/EasyBuild/4.4.2/lib/python3.6/site-packages/easybuild/main.py", line 560, in <module>
    main()
  File "/apps/Common/software/EasyBuild/4.4.2/lib/python3.6/site-packages/easybuild/main.py", line 476, in main
    update_pr(options.update_pr, categorized_paths, ordered_ecs)
  File "/apps/Common/software/EasyBuild/4.4.2/lib/python3.6/site-packages/easybuild/tools/github.py", line 1904, in update_pr
    update_branch(branch_name, paths, ecs, github_account=github_account, commit_msg=commit_msg)
  File "/apps/Common/software/EasyBuild/4.4.2/lib/python3.6/site-packages/easybuild/tools/github.py", line 1876, in update_branch
    commit_msg=commit_msg)
  File "/apps/Common/software/EasyBuild/4.4.2/lib/python3.6/site-packages/easybuild/tools/github.py", line 862, in _easyconfigs_pr_common
    patch_specs = det_patch_specs(paths['patch_files'], file_info, [target_dir])
  File "/apps/Common/software/EasyBuild/4.4.2/lib/python3.6/site-packages/easybuild/tools/github.py", line 1058, in det_patch_specs
    soft_name = find_software_name_for_patch(patch_file, ec_dirs)
  File "/apps/Common/software/EasyBuild/4.4.2/lib/python3.6/site-packages/easybuild/tools/github.py", line 1119, in find_software_name_for_patch
    if is_patch_for(patch_name, ec['ec']):
  File "/apps/Common/software/EasyBuild/4.4.2/lib/python3.6/site-packages/easybuild/tools/github.py", line 1021, in is_patch_for
    for entry in itertools.chain(ec['exts_list'], ec.get('components', [])):
TypeError: 'NoneType' object is not iterable
```

sigh.. I'll have to update the branch manually

**Comment by branfosj** [comment]
@Micket Try: `eb --update-pr 14239 eht-imaging-1.2.2-foss-2021a.eb pyNFFT-1.3.2_fix_nfft3util_header.patch --pr-commit-msg="Add missing patch file"`

**Comment by verdurin** [comment]
@boegelbot please test @ generoso

**Comment by verdurin** [comment]
Test report by @verdurin
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
easybuild-c7.novalocal - Linux centos linux 7.9.2009, x86_64, Intel Xeon Processor (Skylake, IBRS), Python 3.6.8
See https://gist.github.com/a94533f0749e4f0082f7a49e52c09838 for a full test report.

**Review by verdurin — APPROVED** [review]
Looks fine.

**Comment by verdurin** [comment]
Going in, thanks @Micket!

**Pull request merged**
