### PR TITLE
+download URL for impi 2018.3

### PR DESCRIPTION
**Pull request by jose-d**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by jose-d** [comment]
Test report by @jose-d
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
koios1 - Linux centos linux 7.6.1810, Intel(R) Xeon(R) Gold 6130 CPU @ 2.10GHz, Python 2.7.5
See https://gist.github.com/e9c03806b3c2d81fa59d97819cfbcbf9 for a full test report.

**Comment by jose-d** [comment]
```
FAIL: test_dep_versions_per_toolchain_generation (test.easyconfigs.easyconfigs.EasyConfigTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/easybuilders/easybuild-easyconfigs/test/easyconfigs/easyconfigs.py", line 299, in test_dep_versions_per_toolchain_generation
    self.assertFalse(multi_dep_vars, error_msg)
AssertionError: No multi-variant deps found for '^.*-(?P<tc_gen>201[89][ab]).*\.eb$' easyconfigs:

found 2 variants of 'PyQt5' dependency in easyconfigs using '2018a' toolchain generation
* version: 5.10.1; versionsuffix: -Python-3.6.4 as dep for set(['AFNI-18.1.09-intel-2018a-Python-3.6.4.eb'])
* version: 5.9.2; versionsuffix: -Python-3.6.4 as dep for set(['Spyder-3.3.1-foss-2018a-Python-3.6.4.eb'])
```

not sure if this is bug in eb or in the travis test spec?

**Comment by jose-d** [comment]
> Please talk to my owner @boegel if you notice you me acting stupid
hi, @boegel , not sure if problem found by bot, related to `foss-2018a`, is related to this PR?

**Comment by bartoldeman** [comment]
The only issue with this PR (and #7287 #7288 #7291 #7292) is that the download URLs are not public but hidden behind a registration wall. While the security is easily defeated using a for loop that does wget, we surely don't want get sued by Intel.

**Comment by bartoldeman** [comment]
ah yes you are right, in https://github.com/easybuilders/easybuild-easyconfigs/commit/31e02b8436bbf34f4980ed54ef5eb43e98663f57#diff-b2f6a9faa07c24a9bac1b83b030085b2
as @boegel did this himself it should be ok, and in any case "the genie is out of the bottle". Sure we have some contacts at Intel too but they'd probably need to defer it to legal.

**Comment by boegel** [comment]
@bartoldeman As far as I can tell, there's no security protecting the downloads at all. A simply `wget` or `curl` works just fine, even when you're not logged in somehow.

And indeed, Spack does it too, and the URLs are also found in several other places.

**Comment by boegel** [comment]
Going in, thanks @jose-d!

**Comment by boegel** [comment]
@jose-d For future enhancements like this, feel free to pack them all in a single PR, since they're easy to review, that avoids a bit of the overhead involved with juggling multiple PRs.

In general, if a PR is limited to 10 easyconfigs or less, it should be OK, certainly if the changes included it in are related (easyconfigs that "collaborate" on a single software stack, similar changes, etc.)

**Pull request merged**
