### PR TITLE
{tools}[GCCcore/11.2.0] zstd v1.5.0, gzip v1.10, LZO v2.10, ...

### PR DESCRIPTION
**Pull request by SebastianAchilles**
(created using `eb --new-pr`)

- [x] #13564

### CODE REVIEW

**Comment by SebastianAchilles** [comment]
Test report by @sebastianachilles
**SUCCESS**
Build succeeded for 10 out of 10 (10 easyconfigs in total)
centos8-eb - Linux centos linux 8.3.2011, x86_64, Intel(R) Core(TM) i7-8700 CPU @ 3.20GHz (skylake), Python 3.6.8
See https://gist.github.com/e94fc0fb3c78bd9f93b1bfe14b5b0498 for a full test report.

**Review by Micket — APPROVED** [review]
LGTM

**Comment by Micket** [comment]
Test report by @Micket
**SUCCESS**
Build succeeded for 10 out of 10 (10 easyconfigs in total)
alvis-c1 - Linux centos linux 7.9.2009, x86_64, Intel Xeon Processor (Skylake), Python 3.6.8
See https://gist.github.com/78c1bbdaa65abd31614f0265a3850785 for a full test report.

**Comment by Micket** [comment]
@boegelbot please test @ generoso

**Pull request merged**
