### PR TITLE
{bio}[GCCcore/11.2.0] annovar v20191024

### PR DESCRIPTION
**Pull request by sassy-crick**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by sassy-crick** [comment]
This is basically the same EC as `annovar-20191024-GCCcore-8.2.0-Perl-5.28.1.eb` with only the toolchain and Perl being upgraded to the latest version. The downloaded tarball has the same checksum as the one in the version above.

**Comment by lexming** [comment]
@boegelbot: please test @ generoso

**Comment by lexming** [comment]
Test report by @lexming
**FAILED**
Build succeeded for 0 out of 1 (1 easyconfigs in total)
node302.hydra.os - Linux centos linux 7.9.2009, x86_64, Intel(R) Xeon(R) Gold 6148 CPU @ 2.40GHz, Python 2.7.5
See https://gist.github.com/64f7ec488b4cd564b48a615763e2dcc1 for a full test report.

**Review by lexming — APPROVED** [review]
LGTM

**Comment by lexming** [comment]
Going in, thanks @sassy-crick !

**Pull request merged**
