### PR TITLE
{bio}[intel/2017b] InterProScan v5.27-66.0

### PR DESCRIPTION
**Pull request by boegel**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
node2603.swalot.os - Linux centos linux 7.4.1708, Intel(R) Xeon(R) CPU E5-2660 v3 @ 2.60GHz, Python 2.7.5
See https://gist.github.com/20671e08b8cd2b82cc7fa1300b1be920 for a full test report.

**Comment by vanzod** [comment]
Test report by @vanzod
**FAILED**
Build succeeded for 0 out of 1 (1 easyconfigs in this PR)
cermis - Linux debian 9.3, Intel(R) Xeon(R) CPU           E5620  @ 2.40GHz, Python 2.7.13
See https://gist.github.com/d5fcff2e058b1306d8a7dfba2a5442cd for a full test report.

**Comment by boegel** [comment]
@vanzod 

```
tar: panther/12.0/panther.hmm.h3p: Wrote only 5120 of 10240 bytes
tar: panther/12.0/names.tab: Cannot write: No space left on device
tar: panther/12.0/panther.hmm: Cannot write: No space left on device
```

Told you the install was big. ;-)

**Comment by vanzod** [comment]
Test report by @vanzod
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
cermis - Linux debian 9.3, Intel(R) Xeon(R) CPU           E5620  @ 2.40GHz, Python 2.7.13
See https://gist.github.com/7834d7304d7e432d37a9adec157a36c8 for a full test report.

**Comment by vanzod** [comment]
Going in, thanks @boegel!

**Pull request merged**
