### PR TITLE
{math}[dummy/] MATLAB v2013b

### PR DESCRIPTION
**Pull request by boegel**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
node2049.delcatty.os - Linux centos linux 7.3.1611, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.7.5
See https://gist.github.com/0b1a0d2c8db25b23c4da8bd2b9d15b59 for a full test report.

**Comment by boegel** [comment]
This is an old version of MATLAB, but we had a user explicitly asking for this version because they had a compiled version of SPM for this particular version of MATLAB...

**Comment by vanzod** [comment]
Going in, thanks @boegel!

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
node2443.golett.os - Linux centos linux 7.3.1611, Intel(R) Xeon(R) CPU E5-2680 v3 @ 2.50GHz, Python 2.7.5
See https://gist.github.com/b9da958ce7cd17f702ca754f2a06ee72 for a full test report.

**Pull request merged**
