### PR TITLE
{bio}[foss/2020b] BUSCO v4.1.2 w/ Python 3.8.6

### PR DESCRIPTION
**Pull request by boegel**
(created using `eb --new-pr`)
requires:
* [x] #12188 (MetaEuk)
* [x] ~~#12189~~ (AUGUSTUS)
* [x] ~~#12186~~ (SEPP)
* [x] ~~#12191~~ (HMMER)
* [x] ~~#12192~~ (Biopython)
* [x] ~~#12194~~ (prodigal)

### CODE REVIEW

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
node3108.skitty.os - Linux centos linux 7.9.2009, x86_64, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz, Python 3.6.8
See https://gist.github.com/21c4ad88ba148dc0827c0b0688a485c3 for a full test report.

**Review by branfosj — APPROVED** [review]
lgtm

**Comment by branfosj** [comment]
@boegelbot please test @ generoso

**Comment by branfosj** [comment]
Test report by @branfosj
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
bear-pg0211u03a.bear.cluster - Linux centos linux 7.8.2003, x86_64, Intel(R) Xeon(R) Gold 6248 CPU @ 2.50GHz (cascadelake), Python 3.6.8
See https://gist.github.com/3be19509f506a1491617bf759f7f7126 for a full test report.

**Comment by branfosj** [comment]
With #12190 adding BUSCO 5.0.0 and with https://github.com/easybuilders/easybuild-easyconfigs/pull/12152#discussion_r594629722 suggesting a need for 4.06, is this version needed as well?

**Comment by boegel** [comment]
closing this since `foss/2020b` is deprecated, see https://docs.easybuild.io/policies/toolchains

**Pull request closed without merging**
