### PR TITLE
{bio}[foss/2019a] R-bundle-Bioconductor v3.9

### PR DESCRIPTION
**Pull request by boegel**
(created using `eb --new-pr`)

requires ~#8757~ (MariaDB-connector-c) + ~#8759~ (ncdf4)

### CODE REVIEW

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
node3102.skitty.os - Linux centos linux 7.6.1810, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz, Python 2.7.5
See https://gist.github.com/32290945d9ad03df0c1b1030561ad981 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
node2404.golett.os - Linux centos linux 7.6.1810, Intel(R) Xeon(R) CPU E5-2680 v3 @ 2.50GHz, Python 2.7.5
See https://gist.github.com/9c0181df8fa8644208956a23f930f35f for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
node2039.delcatty.os - Linux centos linux 7.6.1810, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.7.5
See https://gist.github.com/4c600a38f2bd5202aadf5733162fd86e for a full test report.

**Comment by vanzod** [comment]
Re-trigger Travis after all dependencies have been merged

**Comment by vanzod** [comment]
@boegel One of our users requested `GENESIS` [1] which is part of `BioConductor`. Maybe worth adding it now?

[1] https://www.bioconductor.org/packages/release/bioc/html/GENESIS.html

**Comment by boegel** [comment]
> @boegel One of our users requested `GENESIS` [1] which is part of `BioConductor`. Maybe worth adding it now?
> 
> [1] https://www.bioconductor.org/packages/release/bioc/html/GENESIS.html

Done in 988000b57b

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
node2683.swalot.os - Linux centos linux 7.6.1810, Intel(R) Xeon(R) CPU E5-2660 v3 @ 2.60GHz, Python 2.7.5
See https://gist.github.com/c4aa830b95820ae3a2c0e97c0f0a841c for a full test report.

**Comment by vanzod** [comment]
Test report by @vanzod
**FAILED**
Build succeeded for 0 out of 1 (1 easyconfigs in this PR)
cermis - Linux debian 9.9, Intel(R) Xeon(R) CPU           X5670  @ 2.93GHz, Python 2.7.13
See https://gist.github.com/1b070bd39e53e377a8ce21ab878850f2 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
node3138.skitty.os - Linux centos linux 7.6.1810, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz, Python 2.7.5
See https://gist.github.com/652d902fef8e6a5344b56c4283ad9590 for a full test report.

**Comment by vanzod** [comment]
Test report by @vanzod
**FAILED**
Build succeeded for 0 out of 1 (1 easyconfigs in this PR)
cermis - Linux debian 9.9, Intel(R) Xeon(R) CPU           X5670  @ 2.93GHz, Python 2.7.13
See https://gist.github.com/e522b031b8396844e3acba436a9f6f74 for a full test report.

**Comment by vanzod** [comment]
@boegel It looks like something is wrong with `Rgraphviz`. From the log it is building its own version of `graphviz`. It may be worth considering letting it use the one built by EB instead.

**Comment by boegel** [comment]
@vanzod Hmm, any idea how?

**Comment by vanzod** [comment]
@boegel To do that is sufficient to add `Graphviz` as runtime dependency, `pkg-config` as build dependency and add the following to the extension:
```
'installopts': '--configure-args="--with-graphviz"'
```
The configure will automatically pick up the external library.
According to the `RGraphviz` documentation it requires `Graphviz >= 2.16` and it ships with `Graphviz 2.28`, which it patches. I have tried with `Graphviz 2.40.1` (#8782), but apparently the API changed after version `2.30` and `Rgraphviz` cannot link against newer versions. Hence we are forced to use the version it is bundled with.
I am working now to figure out what went wrong during the test.

**Comment by vanzod** [comment]
According to [1], the `undefined symbol: _ZGVbN2vv___pow_finite` error arises when it is built with `GCC 8` and an aggressive `-O3` optimization level. However in our case everything is compiled with `-O2`. After some trial and error I found out that the issue relies in using `-ftree-vectorize` when the pakage builds the internal `Graphviz` library. The only way I have found (you may have a better one) to limit the changes to this package is to inject `-fno-tree-vectorize` directly in the `configure` after the content of `CFLAGS`. Here is the patch I used: https://gist.github.com/vanzod/bfab8bbb7b263535550696aebae98fa0

[1] https://support.bioconductor.org/p/115919

**Comment by boegel** [comment]
@vanzod It looks like the `CFLAGS` value is pretty much hardcoded, no easy way to override by passing an option to the configure command it seems...

If possible, I would prefer to avoid switching from `R CMD config CFLAGS` (which I assume means "use the `$CFLAGS` that `R` was built with" to using `$CFLAGS`, but in practice it shouldn't make much difference...

**Comment by vanzod** [comment]
@boegel You are correct about the hardcoding. Similarly to all R libraries, it pulls the `CFLAGS` values from `R` based on what was used to build it. Within the context of EB this is not a problem until you need to fiddle with some flags for a specific package. But even in this case I do not think it would be possible to change the toolchain options for just a specific extension.

**Comment by boegel** [comment]
Test report by @boegel
**FAILED**
Build succeeded for 0 out of 1 (1 easyconfigs in this PR)
node2022.delcatty.os - Linux centos linux 7.6.1810, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.7.5
See https://gist.github.com/a48cf00c9f5010dae4fb4bce8d058783 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
node3103.skitty.os - Linux centos linux 7.6.1810, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz, Python 2.7.5
See https://gist.github.com/dd37141e451541b16dc08fcacd146c95 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
node2022.delcatty.os - Linux centos linux 7.6.1810, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.7.5
See https://gist.github.com/39947945d5293d230ccea5fcea3f3266 for a full test report.

**Comment by vanzod** [comment]
Test report by @vanzod
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
cermis - Linux debian 9.9, Intel(R) Xeon(R) CPU           X5670  @ 2.93GHz, Python 2.7.13
See https://gist.github.com/635735677244b52666746223afacc317 for a full test report.

**Comment by vanzod** [comment]
Going in, thanks @boegel!

**Pull request merged**
