### PR TITLE
[magma] Use CMakeMake to avoid C++11 related failures on Power

### PR DESCRIPTION
**Pull request by Flamefire**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by Flamefire** [comment]
Test report by @Flamefire
**FAILED**
Build succeeded for 0 out of 2 (2 easyconfigs in this PR)
taurusi6201.taurus.hrsk.tu-dresden.de - Linux RHEL 7.8, x86_64, Intel(R) Xeon(R) CPU E5-2680 v3 @ 2.50GHz, Python 2.7.5
See https://gist.github.com/841c6bdfa034a48f8d4c061469d17b75 for a full test report.

**Comment by Flamefire** [comment]
Test report by @Flamefire
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in this PR)
taurusml6 - Linux RHEL 7.6, POWER, 8335-GTX, Python 2.7.5
See https://gist.github.com/4cd64601f1cefc56dedb19a6cad9fc92 for a full test report.

**Comment by Flamefire** [comment]
@boegel Can this be added to the next release as a bugfix please? It allows building it on power

**Comment by Flamefire** [comment]
Test report by @Flamefire
**FAILED**
Build succeeded for 0 out of 2 (2 easyconfigs in this PR)
taurusi6204.taurus.hrsk.tu-dresden.de - Linux RHEL 7.8, x86_64, Intel(R) Xeon(R) CPU E5-2680 v3 @ 2.50GHz, Python 2.7.5
See https://gist.github.com/2b0a0a6c2d4a59479f30d32faf46981b for a full test report.

**Comment by Flamefire** [comment]
Test report by @Flamefire
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in this PR)
taurusi4189.taurus.hrsk.tu-dresden.de - Linux RHEL 7.8, x86_64, Intel(R) Xeon(R) CPU E5-2680 v3 @ 2.50GHz, Python 2.7.5
See https://gist.github.com/3d5579ea46c533c41db96eec45f7ff95 for a full test report.

**Comment by migueldiascosta** [comment]
Test report by @migueldiascosta
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in this PR)
sms - Linux centos linux 7.6.1810, x86_64, AMD EPYC 7601 32-Core Processor (zen), Python 2.7.5
See https://gist.github.com/1b76bbafde3f138deba193c7656085d2 for a full test report.

**Comment by migueldiascosta** [comment]
lgtm, but since the tests pass on a system without GPUs, I suppose the testsuite is not being run (?) 

worth looking into running the testsuite?

**Comment by Flamefire** [comment]
As far as I can tell no tests were run before except compile tests due to lack of `runtest` in the EC. If those tests only succeed on GPU then they shouldn't be run as the build nodes might not have GPUs. I think this is done like this everywhere else

Anyway I checked the CMakeLists and there are no tests added that could be executed by `make test` or the like. I've seen `run_test: test\n cd testing && python ./run_tests.py` in the Makefile which might work. However it doesn't exit with an error code on failure so we'd need to grep the output -.- Not really keen on that and as mentioned: If they won't pass on non-GPU nodes I'd rather not do that.

**Comment by migueldiascosta** [comment]
I think in same cases (e.g. TensorFlow?), when particularly relevant (as it would be for magma, imho), we do run the GPU tests, but indeed I'm not sure, this is only based on occasionally not being able to build on non-GPU systems

but if it doesn't have a proper testsuite, my question is irrelevant :)

**Comment by migueldiascosta** [comment]
Going in, thanks @Flamefire!

**Pull request merged**
