### PR TITLE
move setuptools_scm from hatchling to Python easyconfig in develop

### PR DESCRIPTION
**Pull request by lexming**
(created using `eb --new-pr`)

Merge the changes from #19651 currently in `5.0.x` into `develop`

### CODE REVIEW

**Comment by lexming** [comment]
@boegelbot: please test @ generoso

**Review by branfosj — APPROVED** [review]

**Comment by branfosj** [comment]
Test report by @branfosj
**SUCCESS**
Build succeeded for 6 out of 6 (6 easyconfigs in total)
bear-pg0105u03b - Linux RHEL 8.6, x86_64, Intel(R) Xeon(R) Platinum 8360Y CPU @ 2.40GHz (icelake), Python 3.6.8
See https://gist.github.com/branfosj/cbc83ca392e9006ff65a7771f8b9cd0b for a full test report.

**Comment by branfosj** [comment]
@boegelbot please test @ jsc-zen3

**Comment by branfosj** [comment]
Going in, thanks @lexming!

**Comment by branfosj** [comment]
@boegelbot please test @ jsc-zen3
EB_ARGS="--installpath /tmp/$USER/pr19777"

**Comment by branfosj** [comment]
@boegelbot please test @ jsc-zen3
EB_ARGS="--installpath /tmp/$USER/pr19777"
EB_BRANCH=5.0.x

**Comment by verdurin** [comment]
Test report by @verdurin
**SUCCESS**
Build succeeded for 16 out of 16 (6 easyconfigs in total)
easybuild-c7.novalocal - Linux CentOS Linux 7.9.2009, x86_64, Intel Xeon Processor (Skylake, IBRS), Python 3.6.8
See https://gist.github.com/verdurin/1766a18eadfdd3f15a5edde45481e8da for a full test report.

**Pull request merged**
