### PR TITLE
{phys}[foss/2017b,intel/2017b] VASP v5.4.4

### PR DESCRIPTION
**Pull request by JackPerdue**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by terjekv** [comment]
Test report by @terjekv
**FAILED**
Build succeeded for 0 out of 33 (4 easyconfigs in this PR)
ninhursaga.uio.no - Linux RHEL 8.2, x86_64, Intel(R) Xeon(R) Silver 4216 CPU @ 2.10GHz (cascadelake), Python 3.6.8
See https://gist.github.com/9ca4374c62d2d8b583f3f08b060a99ec for a full test report.

**Comment by terjekv** [comment]
Download of `vasp.5.4.4.tar.gz` fails.

**Comment by terjekv** [comment]
@migueldiascosta Your name seems to be in the source of these. What is the state of this version of VASP? :)

**Comment by migueldiascosta** [comment]
@terjekv I think these were based on some of my easyconfigs in a personal repo (there are more recent ones at https://github.com/easybuilders/easybuild-easyconfigs/pull/7697 and https://github.com/easybuilders/easybuild-easyconfigs/pull/9839, but not with the TST tools)

VASP is not publicly available, so only people with a license can test these PRs. Even adding their patches seems to be problematic. Regarding this PR in particular, I also don't have vtstcode-174.tgz...

**Comment by terjekv** [comment]
Right, it sounds like that closing this PR then becomes the best option?

**Comment by boegel** [comment]
I agree that closing this PR makes most sense, it's not worth pursuing this due to the old toolchain imho.

Sorry for not following up on this more closely @JackPerdue, but licensing model of VASP doesn't exactly help here...

**Pull request closed without merging**
