### PR TITLE
Patch GCC lisanitizer for glibc 2.31

### PR DESCRIPTION
**Pull request by zao**
(created using `eb --new-pr`)
glibc 2.31 has changed some internal data structures that libsanitizer attempts to declare compatible structures for. The patches in this PR are sourced from a Gentoo issue on this and are cherrypicked from upstream: https://bugs.gentoo.org/708346#c4

### CODE REVIEW

**Comment by boegel** [comment]
@zao Why not combine both in a single patch file?

**Comment by zao** [comment]
I guess I could - they're separate mostly because I wanted to preserve the attribution.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 3 out of 3 (3 easyconfigs in this PR)
node3139.skitty.os - Linux centos linux 7.7.1908, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz, Python 3.6.8
See https://gist.github.com/b88534b8fbde42eb529146eba97bd633 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 3 out of 3 (3 easyconfigs in this PR)
node2402.golett.os - Linux centos linux 7.7.1908, Intel(R) Xeon(R) CPU E5-2680 v3 @ 2.50GHz, Python 2.7.5
See https://gist.github.com/0eeee272da916526ee5ba662138fa442 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 3 out of 3 (3 easyconfigs in this PR)
generoso-1 - Linux centos linux 7.6.1810, Intel(R) Xeon(R) CPU E5-2660 v4 @ 2.00GHz, Python 3.6.8
See https://gist.github.com/1748cc96f2e5dfa5ff1c9bf647fc62eb for a full test report.

**Comment by boegel** [comment]
Going in, thanks @zao!

**Pull request merged**
