### PR TITLE
{bio}[GCC/8.2.0-2.31.1,iccifort/2019.1.144-GCC-8.2.0-2.31.1] ConnectomeWorkbench v1.3.2

### PR DESCRIPTION
**Pull request by vanzod**
I choose to build it with `GCC`/`iccifort` instead of `GCCcore` since it also provides CLI image processing functionalities that may benefit from compiler-specific optimization.

Requires:
- ~~#8671~~ (Qwt)
- ~~#8672~~ (QuaZIP)

### CODE REVIEW

**Comment by vanzod** [comment]
Test report by @vanzod
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in this PR)
cermis - Linux debian 9.9, Intel(R) Xeon(R) CPU           X5670  @ 2.93GHz, Python 2.7.13
See https://gist.github.com/68a84af67414ab99815be7bf7b7a606f for a full test report.

**Comment by migueldiascosta** [comment]
closing and reopening to trigger travis

**Comment by boegel** [comment]
Test report by @boegel
**FAILED**
Build succeeded for 1 out of 2 (2 easyconfigs in this PR)
node3111.skitty.os - Linux centos linux 7.6.1810, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz, Python 2.7.5
See https://gist.github.com/f2c6467ab931664eb4e6db2393473a33 for a full test report.

**Comment by vanzod** [comment]
@boegel Any idea what went wrong now? I cannot understand from the CMake log

**Comment by zao** [comment]
Test report by @zao
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in this PR)
freja - Linux ubuntu 18.04, Intel(R) Core(TM) i7-8700K CPU @ 3.70GHz, Python 2.7.15+
See https://gist.github.com/a93f22acb1b7af8f054acd7e81e39e58 for a full test report.

**Comment by boegel** [comment]
@vanzod full log is available at https://gist.github.com/boegel/7a3d7ec845fb6879524db2f4d83eb87f

which includes:

```
/tmp/eb-riwbHH/icpceKookQas_.s: Assembler messages:
/tmp/eb-riwbHH/icpceKookQas_.s:9669: Error: unsupported instruction `vmovd'
/tmp/eb-riwbHH/icpceKookQas_.s:9672: Error: unsupported instruction `vmovd'
make[2]: *** [Nifti/CMakeFiles/Nifti.dir/Matrix4x4.cxx.o] Error 1
make[2]: Leaving directory `/tmp/vsc40023/easybuild_build/ConnectomeWorkbench/1.3.2/iccifort-2019.1.144-GCC-8.2.0-2.31.1/workbench-1.3.2/src'
make[1]: *** [Nifti/CMakeFiles/Nifti.dir/all] Error 2
```

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in total)
node2725.swalot.os - Linux CentOS Linux 7.9.2009, x86_64, Intel(R) Xeon(R) CPU E5-2660 v3 @ 2.60GHz (haswell), Python 3.6.8
See https://gist.github.com/538134528f6ee0d9ae9a463c35ad3823 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in total)
node3503.doduo.os - Linux RHEL 8.4, x86_64, AMD EPYC 7552 48-Core Processor (zen2), Python 3.6.8
See https://gist.github.com/30a38a82299c256d3732442e3edae4d5 for a full test report.

**Comment by boegel** [comment]
I think it's better to close this PR anyway, since 1) the problems with the Qt5 dependency persist (since the patch for `binutils` was never backported far enough), 2) this version of ConnectomeWorkbench is quite old now, and we have easyconfigs for newer versions already (cfr. #14845), and 3) there's a couple of additional tweaks needed for these easyconfigs, like not disabling `optarch` (the problem is with the `Qt5` dependency, not `ConnectomeWorkbench` itself).

**Pull request closed without merging**
