### PR TITLE
{chem}[foss/2022a] pycubescd v20220704

### PR DESCRIPTION
**Pull request by lexming**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by lexming** [comment]
@smoors thanks for fixing the tests :+1:

**Comment by lexming** [comment]
@boegelbot: please test @ generoso

**Comment by jfgrimm** [comment]
Test report by @jfgrimm
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
node040.viking2.yor.alces.network - Linux Rocky Linux 8.8, x86_64, AMD EPYC 7643 48-Core Processor, Python 3.6.8
See https://gist.github.com/jfgrimm/8b25804fbc62e20490d86c0d42a7aa8a for a full test report.

**Comment by jfgrimm** [comment]
@boegelbot: please test @ jsc-zen2

**Review by jfgrimm — APPROVED** [review]
lgtm

**Pull request merged**
