### PR TITLE
{compiler}[GCCcore/8.3.0] LLVM v9.0.0

### PR DESCRIPTION
**Pull request by boegel**
(created using `eb --new-pr`)
requires #8962 (CMake)

### CODE REVIEW

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
node2067.delcatty.os - Linux centos linux 7.6.1810, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.7.5
See https://gist.github.com/99027e8f056e0168e33727738fe67549 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
node3151.skitty.os - Linux centos linux 7.6.1810, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz, Python 3.6.8
See https://gist.github.com/3d556d1587332cc395469757a6f8270e for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
node2455.golett.os - Linux centos linux 7.6.1810, Intel(R) Xeon(R) CPU E5-2680 v3 @ 2.50GHz, Python 2.7.5
See https://gist.github.com/ddd15839023cab6f5ff6c5e52b4ddb1e for a full test report.

**Comment by Micket** [comment]
travis kicked

**Comment by Micket** [comment]
Do we not need llvm support in rust anymore (did they change it)?

**Comment by Micket** [comment]
Test report by @Micket
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
vera-c1 - Linux centos linux 7.6.1810, Intel Xeon Processor (Skylake), Python 2.7.5
See https://gist.github.com/5c4d078be39227ddda4a0cb09a026dfa for a full test report.

**Comment by Micket** [comment]
Going in, thanks @boegel!

**Pull request merged**
