### PR TITLE
{bio}[GCCcore/10.3.0] subset-bam v1.1.0

### PR DESCRIPTION
**Pull request by sassy-crick**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by casparvl** [comment]
@boegelbot please test @ generoso

**Comment by casparvl** [comment]
@boegelbot please test @ jsc-zen2

**Review by casparvl — CHANGES_REQUESTED** [review]
Failure on `jsc-zen2` is due to a bug in the EasyBlock of `Cargo`. I reported it here https://github.com/easybuilders/easybuild-easyblocks/issues/2946 . Imho, this EasyConfig doesn't need to wait for that, the bug is in the block.

The other failure, on `generoso` is a missing `bzip2` dependency. That will need to be fixed.

**Comment by casparvl** [comment]
@boegelbot please test @ generoso

**Comment by Micket** [comment]
@boegelbot please test @ jsc-zen2
EB_ARGS="--include-easyblocks-from-pr 2947"

**Comment by Micket** [comment]
Test report by @Micket
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
vera-c1 - Linux Rocky Linux 8.7, x86_64, Intel Xeon Processor (Skylake), Python 3.6.8
See https://gist.github.com/Micket/24efaa5998faf4aea2ec34e7cf2130b5 for a full test report.

**Review by casparvl — APPROVED** [review]
Lgtm!

**Pull request merged**
