### PR TITLE
{data}[GCCcore/12.3.0] HDF v4.2.16

### PR DESCRIPTION
**Pull request by bartoldeman**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by bartoldeman** [comment]
The Fortran interface is broken on 64 bit systems and disabled by default, so we no longer need to disable it.
see https://support.hdfgroup.org/ftp/HDF/releases/HDF4.2.16/src/hdf-4.2.16-RELEASE.txt

**Comment by bartoldeman** [comment]
@boegelbot please test @ generoso

**Review by Micket — DISMISSED** [review]
lgtm

**Comment by Micket** [comment]
Test report by @Micket
**FAILED**
Build succeeded for 0 out of 1 (1 easyconfigs in total)
alvis-c1 - Linux Rocky Linux 8.8, x86_64, Intel Xeon Processor (Skylake), Python 3.6.8
See https://gist.github.com/Micket/7870debd411dedc6851429b19111a356 for a full test report.

**Comment by Micket** [comment]
I'm seeing lots and lots of missing xdr_* symbols when linking

**Comment by bartoldeman** [comment]
yes for some reason the build picked up libtirpc locally, will check how this is best resolved.

**Comment by bartoldeman** [comment]
Reinstated `preconfigopts = "LIBS='-ltirpc' "`. The logic in its configure isn't quite correct.

**Comment by bartoldeman** [comment]
@boegelbot please test @ generoso

**Comment by Micket** [comment]
Test report by @Micket
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
alvis-c1 - Linux Rocky Linux 8.8, x86_64, Intel Xeon Processor (Skylake), Python 3.6.8
See https://gist.github.com/Micket/853321b6f179c48e013cdfc958612af1 for a full test report.

**Comment by Micket** [comment]
@boegelbot please test @ jsc-zen2

**Review by Micket — APPROVED** [review]
lgtm (apparently just made a comment last time)

**Comment by Micket** [comment]
Going in, thanks @bartoldeman!

**Pull request merged**
