### PR TITLE
Switch to GCCcore 9.3.0 for intel/2020a release.

### PR DESCRIPTION
**Pull request by akesandgren**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by akesandgren** [comment]
Test report by @akesandgren
**FAILED**
Build succeeded for 1 out of 5 (5 easyconfigs in this PR)
b-an04.hpc2n.umu.se - Linux ubuntu 16.04, Intel(R) Xeon(R) CPU E5-2690 v4 @ 2.60GHz, Python 2.7.12
See https://gist.github.com/434a8dd541802283a8b172020c620e3a for a full test report.

**Comment by akesandgren** [comment]
Hmmm, I wonder if this have to be done in the foss/2020a PR instead to avoid multi-variant deps...

**Comment by akesandgren** [comment]
Yes, this clearly have to be merged into the foss/2020a PR, closing this one.

**Comment by boegel** [comment]
follow-up in #10072...

**Pull request closed without merging**
