### PR TITLE
{lang}[fosscuda/2018b] SIP v4.19.13 w/ Python 2.7.15

### PR DESCRIPTION
**Pull request by akesandgren**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
node3118.skitty.os - Linux centos linux 7.6.1810, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz, Python 2.7.5
See https://gist.github.com/d3a11922487c133374fa2161eb9b847d for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
node2431.golett.os - Linux centos linux 7.6.1810, Intel(R) Xeon(R) CPU E5-2680 v3 @ 2.50GHz, Python 2.7.5
See https://gist.github.com/b2a7c58570da27343b8e012ce4d9ad98 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
node2016.delcatty.os - Linux centos linux 7.6.1810, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.7.5
See https://gist.github.com/2492979c4f5c0506bc76a7cf6b0a4581 for a full test report.

**Comment by boegel** [comment]
Going in, thanks @akesandgren!

**Comment by akesandgren** [comment]
Probably need to fix some things in here too... looking at the result it also points things to outside its install tree.

**Comment by akesandgren** [comment]
Never mind, this one is doing what it should.

**Pull request merged**
