### PR TITLE
{vis,math}[foss/2021a] FMPy v0.3.2, PyOpenGL v3.1.5, PyQtGraph v0.12.3 w/ Python 3.9.5

### PR DESCRIPTION
**Pull request by deniskristak**
adding easyconfigs: FMPy-0.3.2-foss-2021a.eb, PyOpenGL-3.1.5-GCCcore-10.3.0.eb, PyQtGraph-0.12.3-foss-2021a.eb, FMPy-0.3.2-foss-2021a.eb

requires:
* #14480
* #14528

### CODE REVIEW

**Comment by migueldiascosta** [comment]
@boegelbot please test @ generoso

**Comment by deniskristak** [comment]
@boegel would you please look at the weird test result?

**Comment by boegel** [comment]
I tried manually compiling the `QtCore` utility that isn't producing any output, and I ran into this:
```
$ ./QtCore
Illegal instruction (core dumped)
```

That's... interesting. It could have something to do with `generoso` being a VM environment, rather than bare metal...

**Comment by boegel** [comment]
More info obtained via `gdb`:

```
$ gdb QtCore
(gdb) run
...
Program received signal SIGILL, Illegal instruction.
0x00007ffff78ffe0a in qRandomCpu(void*, long long) () from /project/boegelbot/Rocky8/haswell/software/Qt5/5.15.2-GCCcore-10.3.0/lib/libQt5Core.so.5
(gdb) bt
#0  0x00007ffff78ffe0a in qRandomCpu(void*, long long) () from /project/boegelbot/Rocky8/haswell/software/Qt5/5.15.2-GCCcore-10.3.0/lib/libQt5Core.so.5
#1  0x00007ffff78bb6e0 in ?? () from /project/boegelbot/Rocky8/haswell/software/Qt5/5.15.2-GCCcore-10.3.0/lib/libQt5Core.so.5
#2  0x00007ffff78f7b3b in ?? () from /project/boegelbot/Rocky8/haswell/software/Qt5/5.15.2-GCCcore-10.3.0/lib/libQt5Core.so.5
#3  0x00007ffff78f84e9 in QHashData::detach_helper(void (*)(QHashData::Node*, void*), void (*)(QHashData::Node*), int, int) () from /project/boegelbot/Rocky8/haswell/software/Qt5/5.15.2-GCCcore-10.3.0/lib/libQt5Core.so.5
#4  0x00007ffff7adf4a4 in QTextCodec::codecForName(QByteArray const&) () from /project/boegelbot/Rocky8/haswell/software/Qt5/5.15.2-GCCcore-10.3.0/lib/libQt5Core.so.5
#5  0x00007ffff7adf7be in QTextCodec::codecForLocale() () from /project/boegelbot/Rocky8/haswell/software/Qt5/5.15.2-GCCcore-10.3.0/lib/libQt5Core.so.5
#6  0x00007ffff793eb26 in QString::fromLocal8Bit_helper(char const*, int) () from /project/boegelbot/Rocky8/haswell/software/Qt5/5.15.2-GCCcore-10.3.0/lib/libQt5Core.so.5
#7  0x00007ffff7a83717 in QCoreApplicationPrivate::appName() const () from /project/boegelbot/Rocky8/haswell/software/Qt5/5.15.2-GCCcore-10.3.0/lib/libQt5Core.so.5
#8  0x00007ffff7a8a686 in QCoreApplicationPrivate::init() () from /project/boegelbot/Rocky8/haswell/software/Qt5/5.15.2-GCCcore-10.3.0/lib/libQt5Core.so.5
#9  0x00007ffff7a8ad0c in QCoreApplication::QCoreApplication(int&, char**, int) () from /project/boegelbot/Rocky8/haswell/software/Qt5/5.15.2-GCCcore-10.3.0/lib/libQt5Core.so.5
#10 0x0000000000400b1d in main ()
```

Looks very similar to https://bugs.gentoo.org/707390

**Comment by boegel** [comment]
From the `Qt5` installation log (Aug 22nd 2021):
```
Checking for RDRAND instruction... yes
Checking for RDSEED instruction... yes
```

Perhaps we need to reinstall `Qt5`, it's possible that some update on `generoso` caused `rdseed` to no longer be available in the VM? I'll give that a try...

**Comment by boegel** [comment]
@boegelbot please test @ generoso
CORE_CNT=16
EB_ARGS="Qt5-5.15.2-GCCcore-10.3.0.eb FMPy-0.3.2-foss-2021a.eb"

**Comment by boegel** [comment]
Qt5 re-installation failed, probably due to lack of sufficient memory? I've restarted that re-installation manually on `generoso`...

**Comment by boegel** [comment]
@boegelbot please test @ generoso

**Comment by boegel** [comment]
@boegelbot please test @ generoso

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 3 out of 3 (3 easyconfigs in total)
node2601.swalot.os - Linux centos linux 7.9.2009, x86_64, Intel(R) Xeon(R) CPU E5-2660 v3 @ 2.60GHz (haswell), Python 3.6.8
See https://gist.github.com/08164c2ea5a8a99912f69561655a7e71 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 3 out of 3 (3 easyconfigs in total)
node3507.doduo.os - Linux RHEL 8.2, x86_64, AMD EPYC 7552 48-Core Processor (zen2), Python 3.6.8
See https://gist.github.com/3e3fbcc191fd81cec02ea38990e7e79c for a full test report.

**Review by boegel — APPROVED** [review]
lgtm

**Pull request merged**
