### PR TITLE
rename SNAP to SNAP-HMM and update easyconfig

### PR DESCRIPTION
**Pull request by smoors**
fixes https://github.com/easybuilders/easybuild-easyconfigs/issues/8946

~I had to create a new (slightly updated) version because the old sources are not available anymore.~

### CODE REVIEW

**Comment by smoors** [comment]
Test report by @smoors
**FAILED**
Build succeeded for 2 out of 4 (4 easyconfigs in total)
node379.hydra.os - Linux centos linux 7.9.2009, x86_64, Intel(R) Xeon(R) Gold 6148 CPU @ 2.40GHz (skylake_avx512), Python 2.7.5
See https://gist.github.com/4ba441b1433b56b254cd7fb4ac25bd87 for a full test report.

**Comment by smoors** [comment]
hm, apparently the old sources are still available after all.
they now have 2 homepages pointing to 2 different sources..

**Comment by smoors** [comment]
Test report by @smoors
**SUCCESS**
Build succeeded for 4 out of 4 (4 easyconfigs in total)
node379.hydra.os - Linux centos linux 7.9.2009, x86_64, Intel(R) Xeon(R) Gold 6148 CPU @ 2.40GHz (skylake_avx512), Python 2.7.5
See https://gist.github.com/42d06355e7c16a2f4b02bf7648f2c4b6 for a full test report.

**Comment by branfosj** [comment]
Test report by @branfosj
**SUCCESS**
Build succeeded for 3 out of 3 (3 easyconfigs in total)
bear-pg0211u03a.bear.cluster - Linux centos linux 7.8.2003, x86_64, Intel(R) Xeon(R) Gold 6248 CPU @ 2.50GHz (cascadelake), Python 3.6.8
See https://gist.github.com/ff9cc0fe1c98a0060d1e8e2ee6b7b980 for a full test report.

**Review by branfosj — APPROVED** [review]
lgtm

**Comment by branfosj** [comment]
Note: My test report does not include a test for `SNAP-HMM-2013-11-29-iccifort-2017.4.196-GCC-6.4.0-2.28.eb` as I do not have the relevant compiler. I'm happy to merge here as there is a successful test report for that easyconfig and the changes are consistent with the other changes here.

**Comment by branfosj** [comment]
Going in, thanks @smoors!

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 4 out of 4 (4 easyconfigs in total)
node2609.swalot.os - Linux centos linux 7.9.2009, x86_64, Intel(R) Xeon(R) CPU E5-2660 v3 @ 2.60GHz (haswell), Python 3.6.8
See https://gist.github.com/c6d29b85624c1f4e50eef1588fe810c3 for a full test report.

**Pull request merged**
