### PR TITLE
Add archive source_urls for Hadoop and Spark

### LINKED ISSUE #12217: sources of old Hadoop and Spark versions no longer available for download
Source files for Hadoop 2.10.0 are no longer available at source URL included in `Hadoop-2.10.0-GCCcore-8.3.0-native.eb`, same goes for `Spark-2.4.5-intel-2019b-Python-3.7.4-Java-1.8.eb`

### PR DESCRIPTION
**Pull request by branfosj**
(created using `eb --new-pr`)

fixes #12217

### CODE REVIEW

**Comment by branfosj** [comment]
Test report by @branfosj
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in total)
bb-pg-login02.bear.cluster - Linux centos linux 7.8.2003, x86_64, Intel(R) Xeon(R) CPU E5-2620 v4 @ 2.10GHz (broadwell), Python 3.6.8
See https://gist.github.com/9b609156c3277a874650f76c1e3f0654 for a full test report.

**Comment by verdurin** [comment]
@boegelbot please test @ generoso

**Comment by verdurin** [comment]
Test report by @verdurin
**FAILED**
Build succeeded for 3 out of 12 (2 easyconfigs in total)
easybuild-c7.novalocal - Linux centos linux 7.9.2009, x86_64, Intel Xeon Processor (Skylake, IBRS), Python 3.6.8
See https://gist.github.com/392cb983df28dda7b743c1e2c5717471 for a full test report.

**Comment by verdurin** [comment]
Those build failures were because the test node does not currently have Intel toolchains installed.

**Review by verdurin — APPROVED** [review]
Looks fine.

**Comment by verdurin** [comment]
Going in, thanks @branfosj!

**Pull request merged**
