### PR TITLE
{numlib}[foss/2017b] SLEPc v3.8.3

### PR DESCRIPTION
**Pull request by smoors**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by smoors** [comment]
@boegel can you please take a look at the error? Something seems wrong with:
NiBabel-2.2.1-intel-2018a-Python-3.6.4.eb
Nipype-1.0.2-intel-2018a-Python-3.6.4.eb

**Comment by boegel** [comment]
@smoors fixed in #6261, I'll re-trigger the tests for this PR once that is merged

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
node2411.golett.os - Linux centos linux 7.4.1708, Intel(R) Xeon(R) CPU E5-2680 v3 @ 2.50GHz, Python 2.7.5
See https://gist.github.com/2e826e18a15b7c08dce6991b2693a5d3 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
node2065.delcatty.os - Linux centos linux 7.4.1708, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.7.5
See https://gist.github.com/9d3e2e0c299aad25952a233c9dc90253 for a full test report.

**Comment by boegel** [comment]
Going in, thanks @smoors!

**Pull request merged**
