### PR TITLE
{bio}[foss/2020b] TFEA v1.1.4 w/ Python 3.8.6

### PR DESCRIPTION
**Pull request by sassy-crick**
(created using `eb --new-pr`)

Requires:
- [x] PR #16474

### CODE REVIEW

**Comment by sassy-crick** [comment]
I would need a bit of advice here. There seems to be a few versions of `matplotlib` in the `foss-2020b` toolchain (ignoring Python 2.x):
- `3.3.3`
- `3.5.1`

So I opted for the latest one. Which one shall I use?

**Comment by boegel** [comment]
> I would need a bit of advice here. There seems to be a few versions of `matplotlib` in the `foss-2020b` toolchain (ignoring Python 2.x):
> 
>     * `3.3.3`
> 
>     * `3.5.1`
> 
> 
> So I opted for the latest one. Which one shall I use?

@sassy-crick Stick to `matplotlib` 3.3.3 for easyconfigs of the `2020b` generation, to ensure this is compatible with existing modules that depend on `matplotlib` 3.3.3

**Comment by sassy-crick** [comment]
> @sassy-crick Stick to matplotlib 3.3.3 for easyconfigs of the 2020b generation, to ensure this is compatible with existing modules that depend on matplotlib 3.3.3

Done. Thanks for the information.

**Comment by smoors** [comment]
@boegelbot: please test @ generoso

**Review by smoors — APPROVED** [review]
lgtm

**Comment by smoors** [comment]
Going in, thanks @sassy-crick!

**Pull request merged**
