### PR TITLE
use FFTW provided via EasyBuild for ScaFaCoS

### LINKED ISSUE #10932: failing installations with intel toolchain on CentOS 8.2 because of system header files
The installation of `FFTW-3.3.8-intel-2019b.eb` is failing during `configure` on CentOS 8.2 with:
```
configure:16600: checking size of fftw_r2r_kind
configure:16605: icc -no-gcc -o conftest -O2 -xHost -ftz -fp-speculation=safe -fp-model source -fPIC -I/software/imkl/2019.5.281-iimpi-2019b/mkl/include -L/software/imkl/2019.5.281-iimpi-2019b/lib -L/software/imkl/2019.5.281-iimpi-2019b/lib -L/software/imkl/2019.5.281-iimpi-2019b/mkl/lib/intel64 -L/software/imkl/2019.5.281-iimpi-2019b/lib/intel64 -L/software/iccifort/2019.5.281/lib/intel64 conftest.c -liomp5 -lpthread >&5
In file included from /usr/include/stdio.h(33),
                 from conftest.c(52):
/software/iccifort/2019.5.281/compilers_and_libraries_2019.5.281/linux/compiler/include/stddef.h(47): error: duplicate specifier in declaration
  typedef __SIZE_TYPE__ size_t;
                        ^

In file included from /usr/include/bits/floatn.h(119),
                 from /usr/include/stdlib.h(55),
                 from conftest.c(53):
/usr/include/bits/floatn-common.h(214): error: invalid combination of type specifiers
  typedef float _Float32;
                ^

In file included from /usr/include/bits/floatn.h(119),
                 from /usr/include/stdlib.h(55),
                 from conftest.c(53):
/usr/include/bits/floatn-common.h(251): error: invalid combination of type specifiers
  typedef double _Float64;
                 ^

In file included from /usr/include/bits/floatn.h(119),
                 from /usr/include/stdlib.h(55),
                 from conftest.c(53):
/usr/include/bits/floatn-common.h(268): error: invalid combination of type specifiers
  typedef double _Float32x;
                 ^

In file included from /usr/include/bits/floatn.h(119),
                 from /usr/include/stdlib.h(55),
                 from conftest.c(53):
/usr/include/bits/floatn-common.h(285): error: invalid combination of type specifiers
  typedef long double _Float64x;
                      ^

compilation aborted for conftest.c (code 2)
configure:16605: $? = 2
configure: program exited with status 2
```

Similar issue with `ScaFaCoS-1.0.1-intel-2020a.eb`, from the `config.log` in `scafacos-1.0.1/lib/common/fftw-3.3/`:

```
configure:16453: checking size of fftw_r2r_kind
configure:16458: mpiicc -no-gcc -o conftest -O2 -xHost -ftz -fp-speculation=safe -fp-model source -I/users/kehoste/eb422_regtest/software/GSL/2.6-iccifort-2020.1.217/include -I/users/kehoste/eb422_regtest/software/GMP/6.2.0-GCCcore-9.3.0/include -I/users/kehoste/eb422_regtest/software/imkl/2020.1.217-iimpi-2020a/mkl/include -L/users/kehoste/eb422_regtest/software/GSL/2.6-iccifort-2020.1.217/lib -L/users/kehoste/eb422_regtest/software/GMP/6.2.0-GCCcore-9.3.0/lib -L/users/kehoste/eb422_regtest/software/imkl/2020.1.217-iimpi-2020a/lib -L/users/kehoste/eb422_regtest/software/imkl/2020.1.217-iimpi-2020a/lib -L/users/kehoste/eb422_regtest/software/imkl/2020.1.217-iimpi-2020a/mkl/lib/intel64 -L/users/kehoste/eb422_regtest/software/imkl/2020.1.217-iimpi-2020a/lib/intel64 -L/users/kehoste/eb422_regtest/software/iccifort/2020.1.217/lib/intel64 conftest.c -liomp5 -lpthread >&5
In file included from /usr/include/stdio.h(33),
                 from conftest.c(51):
/users/kehoste/eb422_regtest/software/iccifort/2020.1.217/compilers_and_libraries_2020.1.217/linux/compiler/include/icc/stddef.h(47): error: duplicate specifier in declaration
  typedef __SIZE_TYPE__ size_t;
                        ^

In file included from /usr/include/bits/floatn.h(119),
                 from /usr/include/stdlib.h(55),
                 from conftest.c(52):
/usr/include/bits/floatn-common.h(214): error: invalid combination of type specifiers
  typedef float _Float32;
                ^

In file included from /usr/include/bits/floatn.h(119),
                 from /usr/include/stdlib.h(55),
                 from conftest.c(52):
/usr/include/bits/floatn-common.h(251): error: invalid combination of type specifiers
  typedef double _Float64;
                 ^

In file included from /usr/include/bits/floatn.h(119),
                 from /usr/include/stdlib.h(55),
                 from conftest.c(52):
/usr/include/bits/floatn-common.h(268): error: invalid combination of type specifiers
  typedef double _Float32x;
                 ^

In file included from /usr/include/bits/floatn.h(119),
                 from /usr/include/stdlib.h(55),
                 from conftest.c(52):
/usr/include/bits/floatn-common.h(285): error: invalid combination of type specifiers
  typedef long double _Float64x;
                      ^

compilation aborted for conftest.c (code 2)
configure:16458: $? = 2
configure: program exited with status 2
```

### PR DESCRIPTION
**Pull request by boegel**
(created using `eb --new-pr`)

fixes #10932

### CODE REVIEW

**Comment by boegel** [comment]
@boegelbot please test @ generoso

**Comment by boegel** [comment]
Test report by @boegel
**FAILED**
Build succeeded for 1 out of 2 (2 easyconfigs in this PR)
node2556.golett.os - Linux centos linux 7.8.2003, x86_64, Intel(R) Xeon(R) CPU E5-2680 v3 @ 2.50GHz (haswell), Python 2.7.5
See https://gist.github.com/1a3b6404fd467a8e0169d5c1007f3d82 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in this PR)
node3135.skitty.os - Linux centos linux 7.8.2003, x86_64, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz (skylake_avx512), Python 3.6.8
See https://gist.github.com/a2f8d5899fe35bce93201270dca0a23f for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in this PR)
node3412.kirlia.os - Linux centos linux 7.8.2003, x86_64, Intel(R) Xeon(R) Gold 6240 CPU @ 2.60GHz (cascadelake), Python 2.7.5
See https://gist.github.com/52cb270521ea7b4aca9e624d0d0e154c for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in this PR)
node2491.golett.os - Linux centos linux 7.8.2003, x86_64, Intel(R) Xeon(R) CPU E5-2680 v3 @ 2.50GHz (haswell), Python 2.7.5
See https://gist.github.com/130cdeca90e3a823da95d34966aec51c for a full test report.

**Comment by smoors** [comment]
Test report by @smoors
**SUCCESS**
Build succeeded for 4 out of 4 (2 easyconfigs in this PR)
node253.hydra.os - Linux centos linux 7.7.1908, x86_64, Intel(R) Xeon(R) CPU E5-2650 v4 @ 2.20GHz (broadwell), Python 2.7.5
See https://gist.github.com/cfbb591aea35ebc094857ef481846189 for a full test report.

**Comment by smoors** [comment]
Going in, thanks @boegel!

**Pull request merged**
