### PR TITLE
{lib,mpi}[GCCcore/13.3.0,NVHPC/24.9] Add NCCL 2.22.3, UCC-CUDA 1.3.0, OpenMPI 5.0.3 w/CUDA 12.6.0

### PR DESCRIPTION
**Pull request by Thyre**
Add NCCL 2.22.3 & UCC-CUDA 1.3.0 for GCCcore 13.3.0.
Add OpenMPI 5.0.3 for NVHPC 24.9. 

NVHPC 24.9 requires some patches to work correctly with OpenMPI 5.0.3.

### CODE REVIEW

**Comment by SebastianAchilles** [comment]
Test report by @sebastianachilles
**SUCCESS**
Build succeeded for 3 out of 3 (3 easyconfigs in total)
skl-rockylinux-810 - Linux Rocky Linux 8.10, x86_64, Intel(R) Core(TM) i7-10700 CPU @ 2.90GHz (skylake), 1 x NVIDIA NVIDIA RTX A4000, 555.42.06, Python 3.6.8
See https://gist.github.com/SebastianAchilles/b85abb42f2523431c1e1acdb99a8c2f0 for a full test report.

**Comment by SebastianAchilles** [comment]
@boegelbot please test @ jsc-zen3-a100
CORE_CNT=16

**Comment by Thyre** [comment]
> Test report by @boegelbot **FAILED** Build succeeded for 2 out of 3 (3 easyconfigs in total) jsczen3g1.int.jsc-zen3.fz-juelich.de - Linux Rocky Linux 9.4, x86_64, AMD EPYC-Milan Processor (zen3), 1 x NVIDIA NVIDIA A100 80GB PCIe, 555.42.06, Python 3.9.18 See https://gist.github.com/boegelbot/b264a6ea5d8fe659647a51a1668af921 for a full test report.

Unfortunately its hard to say why that particular test `opal_path_nfs` failed. Looking that test up online, one can find several occurrences where this test fails but shouldn't [1][2][3][4].
It might be interesting to have the full log, since that might include the exit code. Trying a second run might also be interesting, just to see if this was a one-time failure or is related to something specific to that system.

I'm also trying to build this on a second system of mine to see if it fails there. This will take some time, as EasyBuild is not set up there.

[1] https://github.com/open-mpi/ompi/issues/10152
[2] https://github.com/open-mpi/ompi/issues/628#issuecomment-111700775
[3] https://www.mail-archive.com/users@lists.open-mpi.org/msg33810.html
[4] https://www.mail-archive.com/users@lists.open-mpi.org/msg35301.html

**Comment by Thyre** [comment]
Test report by @Thyre
**SUCCESS**
Build succeeded for 3 out of 3 (3 easyconfigs in total)
datenlager - Linux Ubuntu 24.04, x86_64, AMD Ryzen 7 3700X 8-Core Processor, Python 3.12.3
See https://gist.github.com/Thyre/0f30df76f9467fd9a84c608721c2614f for a full test report.

**Comment by sassy-crick** [comment]
Test report by @sassy-crick 
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
Full report for OpenMPI-5.0.3-NVHPC-24.9-CUDA-12.6.0.eb can be found [here](https://gist.github.com/sassy-crick/d4542cc28096ad4180f099530e305648)
I am building using EASYBUILD_CUDA_COMPUTE_CAPABILITIES=8.9 for our L40s is that helps.

**Comment by Thyre** [comment]
Test report by @Thyre
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
Linux - Linux EndeavourOS UNKNOWN, x86_64, AMD Ryzen 7 7800X3D 8-Core Processor, 1 x NVIDIA NVIDIA GeForce RTX 3070, 560.35.03, Python 3.12.7
See https://gist.github.com/Thyre/9305d3751fab2f7cee7c0d436a1dbf1f for a full test report.

**Comment by SebastianAchilles** [comment]
@boegelbot please test @ jsc-zen3-a100
CORE_CNT=16
EB_ARGS="--buildpath=/dev/shm"

**Comment by SebastianAchilles** [comment]
@boegelbot please test @ generoso
CORE_CNT=16

**Comment by Thyre** [comment]
`jsc-zen3` indeed uses NFS to mount some directories. This might explain the failures, if something goes wrong there during testing. @SebastianAchilles, should I try to disable the test with a patch, so that other users do not run into this issue?

**Comment by Thyre** [comment]
Will look into it

**Comment by Thyre** [comment]
@boegelbot please test @ jsc-zen3-a100
CORE_CNT=16

**Comment by SebastianAchilles** [comment]
Looks like the batch job 5321 on `jsc-zen3` finished successfully, but it had problems uploading the test report.

**Comment by SebastianAchilles** [comment]
@boegelbot please test @ jsc-zen3-a100
CORE_CNT=16

**Review by SebastianAchilles — APPROVED** [review]
lgtm

**Comment by SebastianAchilles** [comment]
Going in, thanks @Thyre!

**Pull request merged**
