### PR TITLE
{lang,lib,tools}[GCCcore/12.3.0] SciPy-bundle v2023.07, hypothesis v6.82.0, pybind11 v2.11.1

### PR DESCRIPTION
**Pull request by SebastianAchilles**
(created using `eb --new-pr`)

Depends on
- [ ] https://github.com/easybuilders/easybuild-easyblocks/pull/2971

### CODE REVIEW

**Comment by casparvl** [comment]
@boegelbot please test @ generoso
EB_ARGS="--include-easyblocks-from-pr=2971"

**Comment by casparvl** [comment]
@boegelbot please test @ jsc-zen2
EB_ARGS="--include-easyblocks-from-pr=2971"

**Comment by SebastianAchilles** [comment]
Test report by @sebastianachilles
Using easyblocks from PR(s) https://github.com/easybuilders/easybuild-easyblocks/pull/2971
**SUCCESS**
Build succeeded for 3 out of 3 (3 easyconfigs in total)
zen2-ubuntu-2304 - Linux Ubuntu 23.04 (Lunar Lobster), x86_64, AMD EPYC 7452 32-Core Processor (zen2), Python 3.11.2
See https://gist.github.com/SebastianAchilles/e05a0254872146b2a00c1165c8524eee for a full test report.

**Comment by SebastianAchilles** [comment]
Test report by @sebastianachilles
Using easyblocks from PR(s) https://github.com/easybuilders/easybuild-easyblocks/pull/2971
**SUCCESS**
Build succeeded for 3 out of 3 (3 easyconfigs in total)
bwd-rockylinux-92 - Linux Rocky Linux 9.2 (Blue Onyx), x86_64, Intel(R) Core(TM) i7-6900K CPU @ 3.20GHz (broadwell), 2 x NVIDIA NVIDIA GeForce GTX 1060 6GB, 535.54.03, Python 3.9.16
See https://gist.github.com/SebastianAchilles/cff282ca9418b78721499a50c35ddb5f for a full test report.

**Comment by SebastianAchilles** [comment]
Test report by @sebastianachilles
Using easyblocks from PR(s) https://github.com/easybuilders/easybuild-easyblocks/pull/2971
**SUCCESS**
Build succeeded for 3 out of 3 (3 easyconfigs in total)
skl-rockylinux-88 - Linux Rocky Linux 8.8, x86_64, Intel(R) Core(TM) i7-10700 CPU @ 2.90GHz (skylake), 1 x NVIDIA NVIDIA RTX A4000, 535.54.03, Python 3.6.8
See https://gist.github.com/SebastianAchilles/02f370cc8f00030dcb0c156c7c4f6dc1 for a full test report.

**Comment by SebastianAchilles** [comment]
Test report by @sebastianachilles
Using easyblocks from PR(s) https://github.com/easybuilders/easybuild-easyblocks/pull/2971
**SUCCESS**
Build succeeded for 3 out of 3 (3 easyconfigs in total)
skl-centos-79 - Linux CentOS Linux 7.9.2009, x86_64, Intel(R) Core(TM) i7-8700 CPU @ 3.20GHz (skylake), Python 3.6.8
See https://gist.github.com/SebastianAchilles/0e51536f2ef31f41efd00521e907888b for a full test report.

**Comment by SebastianAchilles** [comment]
Batch job 3064 on `jsc-zen2` was successful, but the upload of the test report got stuck. Let's ask the bot for another try.

**Comment by SebastianAchilles** [comment]
@boegelbot please test @ jsc-zen2
EB_ARGS="--include-easyblocks-from-pr=2971"

**Comment by casparvl** [comment]
Test report by @casparvl
Using easyblocks from PR(s) https://github.com/easybuilders/easybuild-easyblocks/pull/2971
**FAILED**
Build succeeded for 2 out of 3 (3 easyconfigs in total)
tcn30.local.snellius.surf.nl - Linux RHEL 8.6, x86_64, AMD EPYC 7H12 64-Core Processor, Python 3.6.8
See https://gist.github.com/casparvl/ed86885d63c4be938b0dd944b234d031 for a full test report.

**Comment by casparvl** [comment]
Test report by @casparvl
Using easyblocks from PR(s) https://github.com/easybuilders/easybuild-easyblocks/pull/2971
**SUCCESS**
Build succeeded for 3 out of 3 (3 easyconfigs in total)
tcn30.local.snellius.surf.nl - Linux RHEL 8.6, x86_64, AMD EPYC 7H12 64-Core Processor, Python 3.6.8
See https://gist.github.com/casparvl/526b88117048fc0966030a673b5ba19f for a full test report.

**Review by casparvl — APPROVED** [review]
Lgtm!

**Comment by casparvl** [comment]
Going in, thanks @SebastianAchilles!

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 3 out of 3 (3 easyconfigs in total)
fair-mastodon-c6g-2xlarge-0001 - Linux Rocky Linux 8.7, AArch64, ARM UNKNOWN (neoverse_n1), Python 3.6.8
See https://gist.github.com/boegel/105b4a458b22c521ea16f0b4e2884362 for a full test report.

**Pull request merged**
