### PR TITLE
{chem}[foss/2023b] LAMMPS v29Aug2024, MDI v1.4.29, PLUMED v2.9.2, ... w/ kokkos

### PR DESCRIPTION
**Pull request by laraPPr**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by laraPPr** [comment]
Test report by @laraPPr
**SUCCESS**
Build succeeded for 7 out of 7 (7 easyconfigs in total)
node3585.doduo.os - Linux RHEL 8.8, x86_64, AMD EPYC 7552 48-Core Processor, Python 3.11.3
See https://gist.github.com/laraPPr/842d2f987434d92197a4dcfc06eecac9 for a full test report.

**Comment by laraPPr** [comment]
Testing on Arm now see https://github.com/EESSI/software-layer/pull/725

**Comment by laraPPr** [comment]
Successfully build on all the Aarch64 targets in EESSI see: 
- https://github.com/EESSI/software-layer/pull/725#issuecomment-2360713387
- https://github.com/EESSI/software-layer/pull/725#issuecomment-2360713269
- https://github.com/EESSI/software-layer/pull/725#issuecomment-2360558159

**Comment by laraPPr** [comment]
@boegelbot please test @ generoso

**Comment by laraPPr** [comment]
@boegelbot please test @ jsc-zen3

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 7 out of 7 (7 easyconfigs in total)
node3123.skitty.os - Linux RHEL 8.8, x86_64, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz, Python 3.6.8
See https://gist.github.com/boegel/62943fe1241ba5b9a6ffcd3edaafbe2b for a full test report.

**Review by boegel — APPROVED** [review]
lgtm

**Comment by boegel** [comment]
Going in, thanks @laraPPr!

**Comment by casparvl** [comment]
Test report by @casparvl
Using easyblocks from PR(s) https://github.com/easybuilders/easybuild-easyblocks/pull/3321
**FAILED**
Build succeeded for 0 out of 1 (1 easyconfigs in total)
gcn6.local.snellius.surf.nl - Linux RHEL 9.4, x86_64, Intel(R) Xeon(R) Platinum 8360Y CPU @ 2.40GHz, 4 x NVIDIA NVIDIA A100-SXM4-40GB, 555.42.06, Python 3.9.18
See https://gist.github.com/casparvl/5abc88ac775bcca6acd8c0b8f08a75ab for a full test report.

**Pull request merged**
