### PR TITLE
add patch to fix Qt6 issues with ParaView v5.12.0, e.g. representation selection

### PR DESCRIPTION
**Pull request by furstj**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by furstj** [comment]
Added patch from https://gitlab.kitware.com/paraview/paraview/-/merge_requests/6836 which fixes:

- Fix sorting of table views in pqDataInformationWidget by clicking on the header
- Fixed representation selection combobox in the toolbar and properties panel
- Removed use of the obsolete signal QComboBox::currentIndexChanged(QString)
- Use the recommended QKeyCombination::| operator for concatenating keys

Moreover, VTK_PYTHON_OPTIONAL_LINK=OFF has been added in order to resolve issues with missing symbols when using Catalyst coprocessing, see e.g. https://discourse.paraview.org/t/advice-on-building-paraview-superbuild-for-openfoam-runtimepostprocessing/8707

**Comment by boegel** [comment]
@boegelbot please test @ generoso
CORE_CNT=16

**Comment by boegel** [comment]
@boegelbot please test @ jsc-zen3
CORE_CNT=16

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
node3116.skitty.os - Linux RHEL 8.8, x86_64, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz, Python 3.6.8
See https://gist.github.com/boegel/bf81e2b217bdf1e7473d2562e6e50c7c for a full test report.

**Review by boegel — APPROVED** [review]
lgtm

**Pull request merged**
