### PR TITLE
{astro}[intel/2022a] astropy v5.1.1, plc v3.10

### PR DESCRIPTION
**Pull request by jose-d**
(created using `eb --new-pr`)

planck likelihood code with astropy.

output of bundled test app: https://gist.github.com/jose-d/28be10c1c2c97c3467517b98a5dcc9e2

### CODE REVIEW

**Comment by jose-d** [comment]
Test report by @jose-d
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in total)
cvmfs1.koios.lan - Linux Rocky Linux 8.9 (Green Obsidian), x86_64, Intel(R) Xeon(R) Silver 4108 CPU @ 1.80GHz, Python 3.11.5
See https://gist.github.com/jose-d/688ee57f9e6c2806009c62b2b7032198 for a full test report.

**Comment by migueldiascosta** [comment]
@boegelbot please test @ generoso

**Comment by migueldiascosta** [comment]
@boegelbot please test @ jsc-zen3

**Review by migueldiascosta — APPROVED** [review]
lgtm

**Comment by migueldiascosta** [comment]
Going in, thanks @jose-d!

**Pull request merged**
