### PR TITLE
Fix TF 2.3.1 compilation with GLIBC 2.26 on POWER

### PR DESCRIPTION
**Pull request by Flamefire**
(created using `eb --new-pr`)

fixes https://github.com/easybuilders/easybuild-easyblocks/issues/2251

### CODE REVIEW

**Comment by Flamefire** [comment]
Test report by @Flamefire
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
taurusml7 - Linux RHEL 7.6, POWER, 8335-GTX, Python 2.7.5
See https://gist.github.com/992ebfc89f2ce2e0f96a39eb162dc3b0 for a full test report.

**Comment by branfosj** [comment]
Test report by @branfosj
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
bear-pg0306u19a - Linux RHEL 8.2, POWER, 8335-GTX (power9le), Python 3.6.8
See https://gist.github.com/b538bf6c5ea3d830582ea1177232ccc4 for a full test report.

**Comment by Flamefire** [comment]
Test report by @Flamefire
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
taurusa5 - Linux centos linux 7.7.1908, x86_64, Intel(R) Xeon(R) CPU E5-2603 v4 @ 1.70GHz, Python 2.7.5
See https://gist.github.com/102788f2536ee753b3cb431e31028fa3 for a full test report.

**Comment by terjekv** [comment]
Works for me, but I am currently unable to upload a test report from the RHEL8 Power system I have been building on.

**Review by terjekv — APPROVED** [review]

**Comment by terjekv** [comment]
Oh, and shouldn't we also do this for https://github.com/easybuilders/easybuild-easyconfigs/blob/develop/easybuild/easyconfigs/t/TensorFlow/TensorFlow-2.2.0-fosscuda-2019b-Python-3.7.4.eb ?

**Comment by Flamefire** [comment]
Feel free if you need it. Just wanted to make this a PR to not let you test patch after patch ;)

**Comment by boegel** [comment]
@boegelbot please test @ generoso

**Review by branfosj — APPROVED** [review]
lgtm

**Review by Micket — APPROVED** [review]
lgtm

**Comment by Micket** [comment]
Going in, thanks @Flamefire!

**Comment by Micket** [comment]
Test report by @Micket
**FAILED**
Build succeeded for 29 out of 33 (1 easyconfigs in this PR)
vera-c1 - Linux centos linux 7.9.2009, x86_64, Intel Xeon Processor (Skylake), Python 3.6.8
See https://gist.github.com/331006092043c590b5a25c27a97b6970 for a full test report.

**Pull request merged**
