### PR TITLE
{bio,vis}[foss/2022a] Xmipp v3.22.07-Helios, OpenCV v4.6.0 w/ Python 3.10.4

### PR DESCRIPTION
**Pull request by akesandgren**
(created using `eb --new-pr`)

Depends on: https://github.com/easybuilders/easybuild-easyblocks/pull/2831

### CODE REVIEW

**Comment by branfosj** [comment]
Test report by @branfosj
**FAILED**
Build succeeded for 1 out of 2 (2 easyconfigs in total)
bear-pg0212u17a.bear.cluster - Linux RHEL 8.7, x86_64, Intel(R) Xeon(R) CPU E5-2640 v4 @ 2.40GHz (broadwell), 1 x NVIDIA Tesla P100-PCIE-16GB, 470.57.02, Python 3.6.8
See https://gist.github.com/2af9ee43910c5a46520ebc5acd4255e5 for a full test report.

**Comment by branfosj** [comment]
@akesandgren `CUDA_CXX` is not set and that is causing a crash at https://github.com/easybuilders/easybuild-easyblocks/blob/4397ee3e482a38d62fec56a783bce6370e777541/easybuild/easyblocks/x/xmipp.py#L153

**Comment by akesandgren** [comment]
Ah I forgot that I have a new easyblock too...

**Comment by akesandgren** [comment]
Test report by @akesandgren
Using easyblocks from PR(s) https://github.com/easybuilders/easybuild-easyblocks/pull/2831
**FAILED**
Build succeeded for 0 out of 2 (2 easyconfigs in total)
b-an02.hpc2n.umu.se - Linux Ubuntu 20.04, x86_64, Intel(R) Xeon(R) CPU E5-2690 v4 @ 2.60GHz, Python 3.8.10
See https://gist.github.com/83c9677b38c3bc2febc8f0b5f8918f0e for a full test report.

**Comment by akesandgren** [comment]
Test report by @akesandgren
Using easyblocks from PR(s) https://github.com/easybuilders/easybuild-easyblocks/pull/2831
**FAILED**
Build succeeded for 4 out of 5 (2 easyconfigs in total)
b-an02.hpc2n.umu.se - Linux Ubuntu 20.04, x86_64, Intel(R) Xeon(R) CPU E5-2690 v4 @ 2.60GHz, Python 3.8.10
See https://gist.github.com/6ed548b96df6cc79ac8877edb47e18d3 for a full test report.

**Comment by akesandgren** [comment]
Test report by @akesandgren
Using easyblocks from PR(s) https://github.com/easybuilders/easybuild-easyblocks/pull/2831
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in total)
b-an02.hpc2n.umu.se - Linux Ubuntu 20.04, x86_64, Intel(R) Xeon(R) CPU E5-2690 v4 @ 2.60GHz, Python 3.8.10
See https://gist.github.com/3a45797a31f7e207c1274de1da508c90 for a full test report.

**Comment by lexming** [comment]
@boegelbot please test @ generoso
EB_ARGS="--include-easyblocks-from-pr 2831"

**Comment by branfosj** [comment]
Test report by @branfosj
Using easyblocks from PR(s) https://github.com/easybuilders/easybuild-easyblocks/pull/2831
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in total)
bear-pg0103u11a.bear.cluster - Linux RHEL 8.7, x86_64, Intel(R) Xeon(R) Gold 6330 CPU @ 2.00GHz (icelake), 2 x NVIDIA NVIDIA A100-PCIE-40GB, 470.57.02, Python 3.6.8
See https://gist.github.com/4b9998a637efd6344d16cc6f04822edd for a full test report.

**Review by branfosj — APPROVED** [review]

**Comment by branfosj** [comment]
Going in, thanks @akesandgren!

**Comment by smoors** [comment]
@boegelbot please test @ jsc-zen2 EB_ARGS='--optarch="" OpenCV-4.6.0-foss-2022a-CUDA-11.7.0-contrib.eb'

**Comment by smoors** [comment]
@boegelbot please test @ jsc-zen2 EB_ARGS='Xmipp-3.22.07-Helios-foss-2022a-CUDA-11.7.0.eb'

**Pull request merged**
