### PR TITLE
GCCcore-9.3.0: enable NVPTX offload

### PR DESCRIPTION
**Pull request by bartoldeman**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by Micket** [comment]
@boegelbot please test @ generoso

**Comment by Micket** [comment]
I'm waiting for a build of https://github.com/easybuilders/easybuild-easyconfigs/pull/11837  since it affects a bunch of GCC-versions, so it is preferable to rebase this PR when it's done instead.

**Comment by Micket** [comment]
Could you please rebase this on develop?

**Comment by bartoldeman** [comment]
I merged develop.

**Review by Micket — APPROVED** [review]
lgtm

**Comment by smoors** [comment]
Test report by @smoors
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
node377.hydra.os - Linux centos linux 7.9.2009, x86_64, Intel(R) Xeon(R) Gold 6148 CPU @ 2.40GHz (skylake_avx512), Python 2.7.5
See https://gist.github.com/c73862710dc45dc9ceeeff245c68d365 for a full test report.

**Comment by Micket** [comment]
@boegelbot please test @ generoso

**Comment by Micket** [comment]
Test report by @Micket
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
vera-c1 - Linux centos linux 7.9.2009, x86_64, Intel Xeon Processor (Skylake), Python 3.6.8
See https://gist.github.com/86a31313526b93d91cee9da37342b0aa for a full test report.

**Review by smoors — APPROVED** [review]
lgtm

**Comment by smoors** [comment]
Going in, thanks @bartoldeman!

**Pull request merged**
