### PR TITLE
fix one more buffer overrun in nab.c for Amber 18

### PR DESCRIPTION
**Pull request by akesandgren**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by boegel** [comment]
@vanzod @akesandgren Should we whitelist `Amber` w.r.t. the `-Python-` in `versionsuffix` requirement we have now?

**Comment by akesandgren** [comment]
Perhaps temporarily, until the next "major" EB release.
For at least 4.0 we should rename Amber to match version naming that ComputeCanada does (I think it's them at least).
Amber-18.x-AmberTools-19.y-Python-z
to make it easier to figure out which version it really is and to add python to it.
We do need the python stuff in the end since there are multiple other tools people want to use with amber as postprocessing.

I.e. if the next release is 3.8.x then add an exception in the mean time, and then for 3.9 and later we fix it.

**Comment by boegel** [comment]
@akesandgren Is it still worth pursuing this, or can it be closed?

**Comment by akesandgren** [comment]
I think we can close this one and concentrate on the newer versions.

**Pull request closed without merging**
