### PR TITLE
{lang}[foss/2018b] R v3.5.1 (bare)

### PR DESCRIPTION
**Pull request by jdemeul**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by boegel** [comment]
@jdemeul We generally don't include bare easyconfigs for `R` in the central repository.

In addition, we try to stick to one single `R` version per common toolchain (and we already have R 3.4.4 for `2018a`).

Can you clarify your need for this particular easyconfig?

Worth mentioning: I hope to get to adding an easyconfig for R 3.5.1 with updated extensions for `foss/2018b` next week.

**Comment by jdemeul** [comment]
@boegel I'm acting as sysadmin for a smallish research group (7 people) that is heavily reliant on R.
When launching new instances or clusters on our OpenStack cloud, I therefore always try to keep the very latest version on there.

Re the bare state, I think it makes more sense when providing for anything but very large and diverse groups or entire institutes. I estimate we only ever used 1–2% of the packages that come with the R and Bioconductor easyconfigs and often rely on additional packages from github. 
I now have users in our group maintain their own personal library, and the small amount of duplication this entails far outweighs the bulk of packages that would otherwise be pre-installed.
While it explicitly puts package version control in the users' hands, this was also the case before due to the amount of packages users install from other sources.

I personally would argue to provide both bare and full-featured easyconfigs for R that work out-of-the-box, that way sysadmins have the choice depending on the users/groups they provide for.

Let me know what you think. I'm equally happy to hang on to this easyconfig myself :)

**Comment by verdurin** [comment]
@jdemeul I've discussed this with @boegel. To avoid the clashing of `R` versions within a toolchain, would you mind updating it to `foss-2018b`? You can take some of the menial work out of that by running `eb --try-toolchain=foss,2018b ...`.

**Comment by jdemeul** [comment]
Would it make sense to update the X11 dependency as well then to X11-20180604?

**Comment by boegel** [comment]
@jdemeul Yes, and you may need to bump some other dependency versions as well, see also @fizwit's PR #6704 that is preparing for a full R 3.5.1 with `foss/2018b`

**Comment by jdemeul** [comment]
@boegel I think @fizwit and I've been preparing the files in parallel :)
I also focused on Python 3.7.0 though, rather than 3.6.6, so I'll hold off until #6704 goes in.

**Comment by boegel** [comment]
@jdemeul Ping on this?

**Comment by lexming** [comment]
@jdemeul as part of the merge sprint on old PRs, I reviewed and updated your PR for R v3.5.1 barebones. As discussed in the previous comments, this easyconfig has to use `foss/2018b` because we only support one version of each package per toolchain and R v3.5.1 lives in `2018b`. Therefore I updated your PR to fulfil this rule and be able to merge it in our repository.

**Comment by lexming** [comment]
Test report by @lexming
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
node101.hydra.os - Linux centos linux 7.7.1908, x86_64, Intel(R) Xeon(R) CPU E5-2680 v2 @ 2.80GHz, Python 2.7.5
See https://gist.github.com/22dd218ccd65383508eadf789ebbfa52 for a full test report.

**Comment by lexming** [comment]
Test report by @lexming
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
node101.hydra.os - Linux centos linux 7.7.1908, x86_64, Intel(R) Xeon(R) CPU E5-2680 v2 @ 2.80GHz, Python 2.7.5
See https://gist.github.com/c6097f66709f2990b31a6b3cc0f0fa93 for a full test report.

**Comment by boegel** [comment]
@boegelbot please test @ generoso

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
node2607.swalot.os - Linux centos linux 7.8.2003, x86_64, Intel(R) Xeon(R) CPU E5-2660 v3 @ 2.60GHz (haswell), Python 2.7.5
See https://gist.github.com/0f04583e81fec62b6a4c1c515471cd20 for a full test report.

**Review by boegel — APPROVED** [review]
lgtm

**Comment by boegel** [comment]
Going in, thanks @jdemeul!

**Pull request merged**
