### PR TITLE
{data}[fosscuda/2018b] dask v0.19.4 w/ Python 3.6.6

### PR DESCRIPTION
**Pull request by akesandgren**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in this PR)
node3118.skitty.os - Linux centos linux 7.6.1810, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz, Python 2.7.5
See https://gist.github.com/59b8537f7ac42a24df0e548b091de3ca for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 3 out of 3 (2 easyconfigs in this PR)
node2431.golett.os - Linux centos linux 7.6.1810, Intel(R) Xeon(R) CPU E5-2680 v3 @ 2.50GHz, Python 2.7.5
See https://gist.github.com/5b0ecf5a844da7f9d2d8692f7d915456 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 3 out of 3 (2 easyconfigs in this PR)
node2016.delcatty.os - Linux centos linux 7.6.1810, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.7.5
See https://gist.github.com/0d72334772ee485fb7d13603976d008d for a full test report.

**Comment by boegel** [comment]
Going in, thanks @akesandgren!

**Comment by ocaisa** [comment]
Not sure the software name is right here, it should really be `Dask` (see https://dask.org/) and if you are including `distributed` you are really providing `Dask.distributed` (see https://distributed.readthedocs.io/en/latest/) since Dask is a dep of this.

**Comment by akesandgren** [comment]
I just took the already existing dask-0.19.4-foss-2018b-Python-3.6.6.eb and converted into fosscuda.

But if we should change this then let me know asap.

**Comment by boegel** [comment]
Strictly speaking, we should change it, if we want to stick to our policy of using the official software name...

**Comment by akesandgren** [comment]
And what about the distributed part... should we split them or what? And perhaps only do this change for v1.0 of Dask? there is one 1.0 easyconfig already in develop but it doesn't seem to be used anywhere yet.

**Comment by ocaisa** [comment]
I don't have a problem with leaving as is but there is another subproject called `dask_jobqueue` which is also really useful (and requires both, I would actually bundle all these and consider calling it Dask, but then the version is out of whack

**Comment by boegel** [comment]
We have other instances where the "main" app (`Dask` in this case) determines the module name/version, and additional enhancements are pulled in under the same flag; sort of a "batteries included" installation.

If we fix the name, we should do it consistently I think (which is painful, which is why I'd stick to `dask` in this particular case).

**Pull request merged**
