### PR TITLE
Prefer gc GitHub site for source downloads

### PR DESCRIPTION
**Pull request by ocaisa**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by ocaisa** [comment]
Test report by @ocaisa
**SUCCESS**
Build succeeded for 7 out of 7 (7 easyconfigs in this PR)
alanc-VirtualBox - Linux Ubuntu 20.04, x86_64, Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz, Python 3.8.2
See https://gist.github.com/7c6dedd7d4ca878986a86b2650a0005c for a full test report.

**Comment by ocaisa** [comment]
The self-hosted site had incomplete certs, incorrect filenames and differing hashes (all fixed now though I think), see https://github.com/easybuilders/easybuild-easyblocks/issues/2157

**Comment by ocaisa** [comment]
Test report by @ocaisa
**SUCCESS**
Build succeeded for 7 out of 7 (7 easyconfigs in this PR)
alanc-VirtualBox - Linux Ubuntu 20.04, x86_64, Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz, Python 3.8.2
See https://gist.github.com/1ba7878056035d9e3b6441f9ed039f05 for a full test report.

**Comment by ocaisa** [comment]
Test report by @ocaisa
**SUCCESS**
Build succeeded for 7 out of 7 (7 easyconfigs in this PR)
alanc-VirtualBox - Linux Ubuntu 20.04, x86_64, Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz, Python 3.8.2
See https://gist.github.com/98680c39e07bf080e8fa8d91ce7ff664 for a full test report.

**Comment by ocaisa** [comment]
Test report by @ocaisa
**SUCCESS**
Build succeeded for 7 out of 7 (7 easyconfigs in this PR)
alanc-VirtualBox - Linux Ubuntu 20.04, x86_64, Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz, Python 3.8.2
See https://gist.github.com/2182c8d155771b3c85a30df36d1b5976 for a full test report.

**Comment by smoors** [comment]
Test report by @smoors
**SUCCESS**
Build succeeded for 7 out of 7 (7 easyconfigs in this PR)
node254.hydra.os - Linux centos linux 7.7.1908, x86_64, Intel(R) Xeon(R) CPU E5-2683 v4 @ 2.10GHz (broadwell), Python 2.7.5
See https://gist.github.com/425a1d16f74040c6f9d8ee570dad47cd for a full test report.

**Review by smoors — APPROVED** [review]
lgtm

**Comment by smoors** [comment]
Going in, thanks @ocaisa!

**Pull request merged**
