### PR TITLE
{bio}[foss/2020b] OrthoFinder v2.5.4 w/ Python 3.8.6

### PR DESCRIPTION
**Pull request by zarybnicky**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by zarybnicky** [comment]
Superseded by https://github.com/easybuilders/easybuild-easyconfigs/pull/12080

**Comment by boegel** [comment]
Since #12080 adds an older `OrthoFinder` version, this is still useful, so I'd like to re-open this...
@zarybnicky Is it possible to restore the branch you were using for this PR?

**Comment by boegel** [comment]
@boegelbot please test @ generoso

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
node2697.swalot.os - Linux centos linux 7.9.2009, x86_64, Intel(R) Xeon(R) CPU E5-2660 v3 @ 2.60GHz (haswell), Python 3.6.8
See https://gist.github.com/322ae07f30a7f2757dc8e5bb2c303f81 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
node3580.doduo.os - Linux RHEL 8.2, x86_64, AMD EPYC 7552 48-Core Processor (zen2), Python 3.6.8
See https://gist.github.com/f05df336544ca38d2440aba9e0a9a054 for a full test report.

**Review by boegel — APPROVED** [review]
lgtm

**Comment by boegel** [comment]
Going in, thanks @zarybnicky!

**Pull request merged**
