### PR TITLE
{math,numlib}[foss/2020a,intel/2020a] PETSc v3.12.4, MUMPS v5.2.1, SCOTCH v6.0.9, Hypre v2.18.2

### PR DESCRIPTION
**Pull request by boegel**
(created using `eb --new-pr`)
requires ~~#10528~~ (Boost), ~~#10530~~ (SuiteSparse)

### CODE REVIEW

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 8 out of 8 (8 easyconfigs in this PR)
node3406.kirlia.os - Linux centos linux 7.7.1908, x86_64, Intel(R) Xeon(R) Gold 6240 CPU @ 2.60GHz (cascadelake), Python 2.7.5
See https://gist.github.com/91b1fea0a759b71e2585014d922386a9 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 8 out of 8 (8 easyconfigs in this PR)
generoso-3 - Linux centos linux 7.6.1810, x86_64, Intel(R) Xeon(R) CPU E5-2660 v4 @ 2.00GHz, Python 3.6.8
See https://gist.github.com/0ab33d6b616f09c5a611719bec55eba9 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 8 out of 8 (8 easyconfigs in this PR)
node2452.golett.os - Linux centos linux 7.7.1908, x86_64, Intel(R) Xeon(R) CPU E5-2680 v3 @ 2.50GHz (haswell), Python 2.7.5
See https://gist.github.com/01b072c935c5872ff7a1793b06f31905 for a full test report.

**Comment by akesandgren** [comment]
Test report by @akesandgren
**SUCCESS**
Build succeeded for 8 out of 8 (8 easyconfigs in this PR)
b-an03.hpc2n.umu.se - Linux ubuntu 16.04, x86_64, Intel(R) Xeon(R) CPU E5-2690 v4 @ 2.60GHz, Python 2.7.12
See https://gist.github.com/1e5c9c48ac5699a06b467a2549f38206 for a full test report.

**Comment by zao** [comment]
Test report by @zao
**FAILED**
Build succeeded for 9 out of 11 (8 easyconfigs in this PR)
freja - Linux Ubuntu 20.04, x86_64, Intel(R) Core(TM) i7-8700K CPU @ 3.70GHz, Python 3.8.2
See https://gist.github.com/b0600bafbf2d6e0a304f77c86cfd5590 for a full test report.

**Comment by akesandgren** [comment]
PETSc has a build and runtime dep on Python

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 8 out of 8 (8 easyconfigs in this PR)
node3145.skitty.os - Linux centos linux 7.7.1908, x86_64, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz (skylake_avx512), Python 3.6.8
See https://gist.github.com/f5271da0cf66cdb28768138e14a5a680 for a full test report.

**Comment by boegel** [comment]
Even better, it also depends on `numpy`:

```
$ grep 'import numpy' /software/PETSc/3.12.4-foss-2020a/lib/petsc/bin/*py
/software/PETSc/3.12.4-foss-2020a/lib/petsc/bin/PetscBinaryIO.py:  >>> import numpy
/software/PETSc/3.12.4-foss-2020a/lib/petsc/bin/PetscBinaryIO.py:import numpy as np
/software/PETSc/3.12.4-foss-2020a/lib/petsc/bin/PetscBinaryIOTrajectory.py:import numpy as np
/software/PETSc/3.12.4-foss-2020a/lib/petsc/bin/petsc_gen_xdmf.py:import numpy as np
/software/PETSc/3.12.4-foss-2020a/lib/petsc/bin/petsc_tas_analysis.py:import numpy as np
```

**Comment by boegel** [comment]
@akesandgren @zao Python dep added, this now requires https://github.com/easybuilders/easybuild-easyblocks/pull/2048 (so `--include-easyblocks-from-pr 2048` is your friend to re-test this)

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 8 out of 8 (8 easyconfigs in this PR)
node3102.skitty.os - Linux centos linux 7.7.1908, x86_64, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz (skylake_avx512), Python 3.6.8
See https://gist.github.com/508564902b17ee8e75e77cd46dd3f714 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 8 out of 8 (8 easyconfigs in this PR)
node2630.swalot.os - Linux centos linux 7.7.1908, x86_64, Intel(R) Xeon(R) CPU E5-2660 v3 @ 2.60GHz (haswell), Python 2.7.5
See https://gist.github.com/f77c64d67a3983e052798e7786d580d3 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 8 out of 8 (8 easyconfigs in this PR)
generoso - Linux centos linux 7.6.1810, x86_64, Intel(R) Xeon(R) CPU E5-2660 v4 @ 2.00GHz, Python 3.6.8
See https://gist.github.com/ba16b1ccec6444b620935194fc98280c for a full test report.

**Comment by akesandgren** [comment]
Test report by @akesandgren
**SUCCESS**
Build succeeded for 8 out of 8 (8 easyconfigs in this PR)
b-an03.hpc2n.umu.se - Linux ubuntu 16.04, x86_64, Intel(R) Xeon(R) CPU E5-2690 v4 @ 2.60GHz, Python 2.7.12
See https://gist.github.com/528c32e823ba0eb411beb11710c9bd67 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 8 out of 8 (8 easyconfigs in this PR)
node3401.kirlia.os - Linux centos linux 7.7.1908, x86_64, Intel(R) Xeon(R) Gold 6240 CPU @ 2.60GHz (cascadelake), Python 2.7.5
See https://gist.github.com/d1082d48ce09de8354281c70c3fc6db2 for a full test report.

**Comment by zao** [comment]
Test report by @zao
**SUCCESS**
Build succeeded for 8 out of 8 (8 easyconfigs in this PR)
freja - Linux Ubuntu 20.04, x86_64, Intel(R) Core(TM) i7-8700K CPU @ 3.70GHz, Python 3.8.2
See https://gist.github.com/b15552b7237d68594ebb0dd26d7a7c8c for a full test report.

**Comment by akesandgren** [comment]
Going in, thanks @boegel!

**Pull request merged**
