### PR TITLE
{bio}[system/system] FusionCatcher v1.20, BBMap v38.79, BLAT v395, ... w/ Python 2.7.16

### PR DESCRIPTION
**Pull request by Darkless012**
(created using `eb --new-pr`)
requires https://github.com/easybuilders/easybuild-easyblocks/pull/2017

### CODE REVIEW

**Comment by lexming** [comment]
We already have a PR for FusionCatcher https://github.com/easybuilders/easybuild-easyconfigs/pull/10134 :slightly_smiling_face:

**Comment by Darkless012** [comment]
It will work with BBMap v38.76, I've run testsuite in test/test.sh with that.

**Comment by Darkless012** [comment]
As well as with the STAR for 2019b

**Comment by lexming** [comment]
Around line 2324 of `fusioncatcher.py` there is
```
    # check version                                                                                                                  
     os.system(_BP_+"bbmap.sh --version 2>&1 |head -2 |tail -1 > '%s'" % (outdir('bbmap_version.txt'),))
     last_line = file(outdir('bbmap_version.txt'),'r').readline().lower().rstrip("\r\n")
     correct_version = ('bbmap version 38.44',)
```

**Comment by Darkless012** [comment]
('Velvet', '1.2.10', '-mt-kmer_191') -  is now not used at all
('parallel', '20190922'), - is now not used at all

**Comment by Darkless012** [comment]
see https://github.com/easybuilders/easybuild-easyblocks/pull/2017/files# for hardcoding fix.

**Comment by Darkless012** [comment]
The only really hardcoded version is seqtk because it has additional CLI args in the forked version

**Comment by lexming** [comment]
I do not like changing version checks in software, if the devs are sticking to a certain version of the dependencies it might be for a reason. Moreover, that would make the version of FusionCatcher in Easybuild not comparable to any other FusionCatcher v1.20.

**Comment by Darkless012** [comment]
Closing in favor of https://github.com/easybuilders/easybuild-easyconfigs/pull/10134

**Pull request closed without merging**
