### PR TITLE
Add patch to fix GCC 10.2.0 rejecting valid code on PPC

### PR DESCRIPTION
**Pull request by Flamefire**
(created using `eb --new-pr`)

Found during compilation of TF 2.5.0.
See https://gitlab.com/libeigen/eigen/-/issues/2259

Reproducer:
```
$ cat vecParam.cpp 
void ploadRhsMMA(__vector_pair&){}
int main(){
  __vector_pair p;
  ploadRhsMMA(p);
}
```
Compile as `g++ vecParam.cpp`.
Prior to this patch it will show: "`error: invalid conversion from type '* __vector_pair'`"

### CODE REVIEW

**Comment by boegel** [comment]
@boegelbot please test @ generoso
CORE_CNT=16
EB_ARGS="--installpath /tmp/$USER"

**Comment by Flamefire** [comment]
Test report by @Flamefire
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
taurusml1 - Linux RHEL 7.6, POWER, 8335-GTX (power9le), Python 2.7.5
See https://gist.github.com/25810beabf40bfce7ae606e09ffc6c0a for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
select-pika-c6gd-2xlarge-0001 - Linux centos linux 8.3.2011, AArch64, ARM UNKNOWN (graviton2), Python 3.6.8
See https://gist.github.com/a2ed4a5499b5560878c8f452036a07e1 for a full test report.

**Review by boegel — APPROVED** [review]
lgtm

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
easybuild2.novalocal - Linux centos linux 8.3.2011, POWER, IBM pSeries (emulated by qemu) (power9le), Python 3.6.8
See https://gist.github.com/b6f5074948e261c3c4e6a9fb3c36d87a for a full test report.

**Comment by boegel** [comment]
Going in, thanks @Flamefire!

**Pull request merged**
