### PR TITLE
{bio}[foss/2022a] epiScanpy v0.4.0 w/ Python 3.10.4

### PR DESCRIPTION
**Pull request by boegel**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
node3170.skitty.os - Linux RHEL 8.6, x86_64, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz (skylake_avx512), Python 3.6.8
See https://gist.github.com/61af418db5aa51494310a2c85df2fa74 for a full test report.

**Comment by boegel** [comment]
@boegelbot please test @ generoso

**Comment by boegel** [comment]
@boegelbot please test @ jsc-zen2

**Review by casparvl — COMMENTED** [review]
Main changes are the `local_preinstallopts_kneed`, and the removal of [this comment](https://github.com/easybuilders/easybuild-easyconfigs/blob/b981d52f5834cfaaa99c11b0d1fc1759626de2b7/easybuild/easyconfigs/e/epiScanpy/epiScanpy-0.3.1-foss-2021a.eb#L48) in previous versions.

Based on the comment, I can understand the `local_preinstallopts_kneed`. Any reason to remove the explaination for the `episcanpy` `preinstallopts`? I think it's quite useful to keep that comment, as otherwise we might wonder down the line 'why was this here again?'. Did you remove the comment on purpose? If so, why?

**Comment by casparvl** [comment]
Test report by @casparvl
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
tcn260.local.snellius.surf.nl - Linux Rocky Linux 8.7, x86_64, AMD EPYC 7H12 64-Core Processor, Python 3.6.8
See https://gist.github.com/656bc4b19736da1e3ede1ceb3c9e9f7e for a full test report.

**Comment by boegel** [comment]
@casparvl Comment restored in a4d3c3f

**Review by casparvl — APPROVED** [review]
Lgtm

**Pull request merged**
