### PR TITLE
New EasyConfig for GLib 2.52.0 with the gimkl-2017a toolchain (plus dependency)

### PR DESCRIPTION
**Pull request by valtandor**

### CODE REVIEW

**Comment by boegel** [comment]
@valtandor Is the missing easyconfig for `Python` provide via another PR?

**Comment by valtandor** [comment]
Ah...On our system this is built against a "bare" Python, but I recalled what you said about not wanting specially decorated versions in the dependencies or builddependencies lists. So I took out the "-bare" suffix, and forgot that the resulting Python doesn't exist.

I will supply a Python easyconfig for gimkl-2017a, but haven't got to it quite yet.

**Comment by migueldiascosta** [comment]
@valtandor is this still relevant?

**Comment by boegel** [comment]
I'm closing this, since it's no longer worth the effort to get this merged given the old toolchains.

@valtandor My apologies for not following up on this closer at the time...

**Pull request closed without merging**
