### PR TITLE
{lib}[system/system] cuTENSOR v2.0.1.2 w/ CUDA 12.1.1

### PR DESCRIPTION
**Pull request by Micket**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by Micket** [comment]
Test report by @Micket
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
vera-skylake-build - Linux Rocky Linux 8.9, x86_64, Intel Xeon Processor (Skylake, IBRS, no TSX), Python 3.6.8
See https://gist.github.com/Micket/1facbfd6f494e4a63b82501a66bad011 for a full test report.

**Comment by Micket** [comment]
@boegelbot please test @ jsc-zen3

**Comment by Micket** [comment]
@boegelbot please test @ generoso

**Comment by casparvl** [comment]
Test report by @casparvl
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
tcn1.local.snellius.surf.nl - Linux RHEL 8.6, x86_64, AMD EPYC 7H12 64-Core Processor, Python 3.6.8
See https://gist.github.com/casparvl/40515f11e937dc1b7f95b60c12e28b58 for a full test report.

**Review by casparvl — APPROVED** [review]
Simple update, lgtm!

**Comment by casparvl** [comment]
Going in, thanks @Micket!

**Comment by ThomasHoffmann77** [comment]
Test report by @thomashoffmann77
**FAILED**
Build succeeded for 0 out of 2 (7 easyconfigs in total)
srv-mahamid-01.embl.de - Linux AlmaLinux 8.8, x86_64, AMD EPYC 7513 32-Core Processor, 2 x NVIDIA NVIDIA GeForce RTX 3090, 535.113.01, Python 3.6.8
See https://gist.github.com/ThomasHoffmann77/1ef026d81ffb48d4265e348c2321a22a for a full test report.

**Comment by Micket** [comment]
I verified the download again, checksum hasn't changed. It should be ededa12ca622baad706ea0a500a358ea51146535466afabd96e558265dc586a2

**Comment by ThomasHoffmann77** [comment]
Test report by @thomashoffmann77
**FAILED**
Build succeeded for 2 out of 3 (7 easyconfigs in total)
srv-mahamid-01.embl.de - Linux AlmaLinux 8.8, x86_64, AMD EPYC 7513 32-Core Processor, 2 x NVIDIA NVIDIA GeForce RTX 3090, 535.113.01, Python 3.6.8
See https://gist.github.com/ThomasHoffmann77/0885fe8e76a35d337f40b0230390a594 for a full test report.

**Comment by ThomasHoffmann77** [comment]
> I verified the download again, checksum hasn't changed. It should be ededa12ca622baad706ea0a500a358ea51146535466afabd96e558265dc586a2

My mistake, sorry. I had an incomplete download.

**Pull request merged**
