### PR TITLE
{chem}[foss/2020a,intel/2020a] NAMD v2.14

### PR DESCRIPTION
**Pull request by boegel**
(created using `eb --new-pr`)
requires ~~https://github.com/easybuilders/easybuild-easyblocks/pull/2118~~

### CODE REVIEW

**Comment by smoors** [comment]
@boegel @edmondac you have both submitted a PR for NAMD v2.14, see also #11090
there are some significant differences between the 2, so it would be good to agree on a common base.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in this PR)
node3411.kirlia.os - Linux centos linux 7.8.2003, x86_64, Intel(R) Xeon(R) Gold 6240 CPU @ 2.60GHz (cascadelake), Python 2.7.5
See https://gist.github.com/aae8c98d43495d3b8925f9d30674bdd8 for a full test report.

**Comment by migueldiascosta** [comment]
Test report by @migueldiascosta
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in this PR)
sms - Linux centos linux 7.6.1810, x86_64, AMD EPYC 7601 32-Core Processor (zen), Python 2.7.5
See https://gist.github.com/c5ad60f907706e156b5643da923547ce for a full test report.

**Comment by boegel** [comment]
> @boegel @edmondac you have both submitted a PR for NAMD v2.14, see also #11090
> there are some significant differences between the 2, so it would be good to agree on a common base.

Different toolchains, but you're right, @edmondac and me should sync up our PRs, we'll look into it!

**Comment by boegel** [comment]
@boegelbot please test @ generoso

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in this PR)
node3411.kirlia.os - Linux centos linux 7.8.2003, x86_64, Intel(R) Xeon(R) Gold 6240 CPU @ 2.60GHz (cascadelake), Python 2.7.5
See https://gist.github.com/7f777cdbe00c7d3d92a615d981650062 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in this PR)
node2426.golett.os - Linux centos linux 7.8.2003, x86_64, Intel(R) Xeon(R) CPU E5-2680 v3 @ 2.50GHz (haswell), Python 2.7.5
See https://gist.github.com/460128b5a33cf6c527c9aa462b8bdd04 for a full test report.

**Comment by boegel** [comment]
Hmm, that looks like a fluke failure... Let's try that again.

@boegelbot please test @ generoso

**Comment by boegel** [comment]
@smoors This should be good to go now?

**Comment by smoors** [comment]
@boegel in #11090 there's also `'openmp': False` in toolchainopts and this:
```
# Hard to make charm build the mpi version with gcc on POWER, so we don't currently try.
charm_arch = "mpi-linux-x86_64"
```
just to be sure, are these not needed/useful in the 202a toolchain versions?

**Comment by boegel** [comment]
@smoors fixed!

**Comment by lexming** [comment]
Test report by @lexming
**FAILED**
Build succeeded for 1 out of 3 (2 easyconfigs in this PR)
node373.hydra.os - Linux centos linux 7.7.1908, x86_64, Intel(R) Xeon(R) Gold 6148 CPU @ 2.40GHz, Python 2.7.5
See https://gist.github.com/d0de06db05ca1c346ac4b00ec6a508bb for a full test report.

**Comment by lexming** [comment]
Test report by @lexming
**FAILED**
Build succeeded for 1 out of 3 (2 easyconfigs in this PR)
node126.hydra.os - Linux centos linux 7.7.1908, x86_64, Intel(R) Xeon(R) CPU E5-2680 v2 @ 2.80GHz, Python 2.7.5
See https://gist.github.com/88284d17422fedf98b65b0dc0b22b5ef for a full test report.

**Comment by lexming** [comment]
Test report by @lexming
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in this PR)
node307.hydra.os - Linux centos linux 7.7.1908, x86_64, Intel(R) Xeon(R) Gold 6148 CPU @ 2.40GHz, Python 2.7.5
See https://gist.github.com/39ff6f627b5e0c9e3a48f1946a2a76b4 for a full test report.

**Comment by lexming** [comment]
Test report by @lexming
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in this PR)
node106.hydra.os - Linux centos linux 7.7.1908, x86_64, Intel(R) Xeon(R) CPU E5-2680 v2 @ 2.80GHz, Python 2.7.5
See https://gist.github.com/1f55da85db77e51eb4017705268e8ac3 for a full test report.

**Review by lexming — APPROVED** [review]
LGTM

**Comment by lexming** [comment]
Going in, thanks @boegel !

**Pull request merged**
