### PR TITLE
{toolchain}[system/system] iomkl v2021a, iompi v2021a, imkl v2021.2.0

### PR DESCRIPTION
**Pull request by bartoldeman**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by bartoldeman** [comment]
This needs https://github.com/easybuilders/easybuild-framework/pull/3785, other imkl-using-iompi fails.

**Comment by bartoldeman** [comment]
@boegelbot please test @ generoso

**Comment by bartoldeman** [comment]
Test report by @bartoldeman
**FAILED**
Build succeeded for 3 out of 4 (4 easyconfigs in total)
build-node.computecanada.ca - Linux centos linux 7.9.2009, x86_64, Intel Xeon Processor (Skylake, IBRS), Python 3.7.7
See https://gist.github.com/7a8956cc824f6e8e389b50a10cd9ce5a for a full test report.

**Comment by bartoldeman** [comment]
Test report by @bartoldeman
**SUCCESS**
Build succeeded for 4 out of 4 (4 easyconfigs in total)
build-node.computecanada.ca - Linux centos linux 7.9.2009, x86_64, Intel Xeon Processor (Skylake, IBRS), Python 3.7.7
See https://gist.github.com/3a862f1b24fb5ff03f87b4ba87481d2d for a full test report.

**Comment by lexming** [comment]
Test report by @lexming
**FAILED**
Build succeeded for 2 out of 4 (4 easyconfigs in total)
node368.hydra.os - Linux centos linux 7.9.2009, x86_64, Intel(R) Xeon(R) Gold 6148 CPU @ 2.40GHz, Python 2.7.5
See https://gist.github.com/0a0fa316698326898caa0ec6b6cd8388 for a full test report.

**Comment by lexming** [comment]
Test report by @lexming
**SUCCESS**
Build succeeded for 4 out of 4 (4 easyconfigs in total)
node368.hydra.os - Linux centos linux 7.9.2009, x86_64, Intel(R) Xeon(R) Gold 6148 CPU @ 2.40GHz, Python 2.7.5
See https://gist.github.com/f92dd54a2cc423d4c670fd7d5f2b0835 for a full test report.

**Review by lexming — APPROVED** [review]
I like the new description of `iomkl` :+1: 

LGTM

**Comment by lexming** [comment]
Going in, thanks @bartoldeman !

**Pull request merged**
