### PR TITLE
{devel}[GCCcore/10.2.0] texinfo v6.7

### PR DESCRIPTION
**Pull request by robert-mijakovic**
(created using `eb --new-pr`)

### CODE REVIEW

**Review by Micket — APPROVED** [review]
lgtm

**Comment by branfosj** [comment]
Test report by @branfosj
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
bear-pg0211u03a.bear.cluster - Linux centos linux 7.8.2003, x86_64, Intel(R) Xeon(R) Gold 6248 CPU @ 2.50GHz (cascadelake), Python 3.6.8
See https://gist.github.com/e691417a05e738221581308a5239f933 for a full test report.

**Comment by Micket** [comment]
Going in, thanks @robert-mijakovic!

**Comment by boegel** [comment]
@robert-mijakovic In what context did you need this? Note that we have a more lightweight easyconfig too now that just provides `makeinfo` (which is often the reason why we include `texinfo` as a build dep, but that requires substantial OS dependencies...)

**Comment by robert-mijakovic** [comment]
> @robert-mijakovic In what context did you need this? Note that we have a more lightweight easyconfig too now that just provides `makeinfo` (which is often the reason why we include `texinfo` as a build dep, but that requires substantial OS dependencies...)

You are right.
It was actually for GDB 10.1 I added sometime in our private repo. I see that a new one was added which is way simpler and uses texinfo as a build dep.
I will remove mine from the private repo.

**Pull request merged**
