### PR TITLE
{bio}[system/system] CellRanger-ARC v2.0.0

### PR DESCRIPTION
**Pull request by ysagon**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by ysagon** [comment]
Hi,

while creating this PR, I got the message: "This PR should be labelled update". I guess because it is a simple version update from an existing eb? So is it a good practice to create a new-pr for a new version of an existing eb?

**Comment by verdurin** [comment]
@ysagon that's to do with the `Label` on Github. We like to differentiate between e.g. `New` and `Update` easyconfigs. It makes no difference to how you create your PR.

**Comment by verdurin** [comment]
Test report by @verdurin
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
easybuild-c7.novalocal - Linux centos linux 7.9.2009, x86_64, Intel Xeon Processor (Skylake, IBRS), Python 3.6.8
See https://gist.github.com/8d50673fe8dd9424a9816e0eca55f4cc for a full test report.

**Comment by verdurin** [comment]
Test report by @verdurin
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
nuc.lan - Linux Fedora 33, x86_64, Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz, Python 3.9.5
See https://gist.github.com/bd1259fd9281e38c4a6fd44c7282f97f for a full test report.

**Review by verdurin — APPROVED** [review]
Looks fine.

**Comment by verdurin** [comment]
Going in, thanks @ysagon!

**Pull request merged**
