### PR TITLE
Add CMake to tbb 2020.03

### PR DESCRIPTION
**Pull request by Flamefire**
(created using `eb --new-pr`)

- [x]  easybuilders/easybuild-easyblocks#2539

### CODE REVIEW

**Review by Micket — APPROVED** [review]
lgtm

**Comment by Micket** [comment]
Test report by @Micket
Using easyblocks from PR(s) https://github.com/easybuilders/easybuild-easyblocks/pull/2539
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
alvis-c1 - Linux centos linux 7.9.2009, x86_64, Intel Xeon Processor (Skylake), Python 3.6.8
See https://gist.github.com/94fcdffb4924567d5ca08d69f9446521 for a full test report.

**Comment by Micket** [comment]
There is a problem i think: the installation for me (even prior to this new easyblock change) I end up with a different cmake-directory in the top level path:
```bash
# old easyblock
$ ls /apps/Test2/software/tbb/2020.1-GCCcore-9.3.0/cmake/
README.rst  TBBBuild.cmake  tbb_config_generator.cmake  tbb_config_installer.cmake  TBBGet.cmake  TBBInstallConfig.cmake  TBBMakeConfig.cmake  templates

# new easyblock
$ ls /apps/Test2/software/tbb/2020.3-GCCcore-10.2.0/cmake/
README.rst  TBBBuild.cmake  tbb_config_generator.cmake  tbb_config_installer.cmake  TBBGet.cmake  TBBInstallConfig.cmake  TBBMakeConfig.cmake  templates

$ ls /apps/Test2/software/tbb/2020.3-GCCcore-10.2.0/lib/cmake/TBB/
TBBConfig.cmake  TBBConfigVersion.cmake
```

But, now the CMAKE_PREFIX_PATH gets set to the first top level directory:
```
prepend_path("CMAKE_PREFIX_PATH","/apps/Test2/software/tbb/2020.3-GCCcore-10.2.0")
```

Perhaps we can put all those files in the same directory instead?

**Comment by Flamefire** [comment]
> I end up with a different cmake-directory in the top level path:

That is correct: TBB is build in the install dir and it has a cmake folder in the root: https://github.com/oneapi-src/oneTBB

> But, now the CMAKE_PREFIX_PATH gets set to the first top level directory:

That is also correct. "Prefix" path means what you pass to `configure --prefix` (in old terms) or CMAKE_INSTALL_PREFIX, i.e. the root folder. It will then search in `<prefix/lib/cmake/<name>` (and more): https://cmake.org/cmake/help/v3.21/command/find_package.html#id5

So no, combining those folders would neither be good nor required.

**Comment by Micket** [comment]
Alright, I'm hazy on the details of where cmake looks for stuff.

But something funny seems to be happening here when I try to use this new stuff:
```cmake
project(test)
find_package(TBB REQUIRED tbbmalloc tbbmalloc_proxy tbb)
```
results in
```
-- Missed required Intel TBB component: tbbmalloc
--   one or both of:
   /apps/Test2/software/tbb/lib/libtbbmalloc.so.2
    /apps/Test2/software/tbb/lib/libtbbmalloc_debug.so.2
   files must exist.
-- Missed required Intel TBB component: tbbmalloc_proxy
--   one or both of:
   /apps/Test2/software/tbb/lib/libtbbmalloc_proxy.so.2
    /apps/Test2/software/tbb/lib/libtbbmalloc_proxy_debug.so.2
   files must exist.
-- Missed required Intel TBB component: tbb
--   one or both of:
   /apps/Test2/software/tbb/lib/libtbb.so.2
    /apps/Test2/software/tbb/lib/libtbb_debug.so.2
   files must exist.
CMake Error at CMakeLists.txt:3 (find_package):
  Found package configuration file:

    /apps/Test2/software/tbb/2020.3-GCCcore-10.2.0/lib64/cmake/TBB/TBBConfig.cmake

  but it set TBB_FOUND to FALSE so package "TBB" is considered to be NOT
  FOUND.
```
From what I can tell, the error stems from the fact that TBBConfig.cmake is adding one to many `../` to its relative paths:
```
get_filename_component(_tbb_release_lib "${CMAKE_CURRENT_LIST_DIR}/../../../../lib/lib${_tbb_component}.so.2" ABSOLUTE)
get_filename_component(_tbb_include_dir "${_tbb_current_realpath}/../../../../include" ABSOLUTE)
```

Removing one layer everywhere and it works.

**Comment by Flamefire** [comment]
FFS. This is the problem with the symlink we create. The file gets initially put into `/lib/cmake/TBB/TBBConfig.cmake` where `/lib` is a symlink to `/build/*_release`
Now to get from the cmake file to the root folder you need 4 levels up because (resolving symlinks) the cmake file is in: `/build/*_release/cmake/TBB/TBBConfig.cmake`, even worse for the system builds.

However I'm not really sure why it doesn't work. For `/apps/Test2/software/tbb/2020.3-GCCcore-10.2.0/lib64/cmake/TBB/TBBConfig.cmake` with `lib64` being a symlink to `lib` shouldn't the same apply?

How about we do it the other way round? Move the `build/*_release` folder to `lib` and create a symlink where it used to be? No actual change but now the layout is more "regular" and and lib|lib64 are actually on the same level
Note that the tbb docs sound like that other (non-lib) folder isn't required and not even used in their binary prebuilts

**Comment by Flamefire** [comment]
Updated the easyblock

**Comment by Micket** [comment]
Test report by @Micket
Using easyblocks from PR(s) https://github.com/easybuilders/easybuild-easyblocks/pull/2539
**FAILED**
Build succeeded for 0 out of 1 (1 easyconfigs in total)
alvis-c1 - Linux centos linux 7.9.2009, x86_64, Intel Xeon Processor (Skylake), Python 3.6.8
See https://gist.github.com/7f6a4998d6a6d7a7526769a2c9067e00 for a full test report.

**Comment by Micket** [comment]
I'm currently getting
```
$ ls /apps/Test2/software/tbb/2020.3-GCCcore-10.2.0/build/linux_intel64_gcc_cc10.2.0_libc2.17_kernel3.10.0_release -l
lrwxrwxrwx. 1 c3-builder c3-staff 9 Aug 12 14:31 /apps/Test2/software/tbb/2020.3-GCCcore-10.2.0/build/linux_intel64_gcc_cc10.2.0_libc2.17_kernel3.10.0_release -> ../../lib
```
where the `../../lib` is nonexistent (one directory to high)

**Comment by Flamefire** [comment]
My bad still had the old folder in the cmake part

**Comment by Flamefire** [comment]
Test report by @Flamefire
Using easyblocks from PR(s) https://github.com/easybuilders/easybuild-easyblocks/pull/2539
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
taurusi8030 - Linux centos linux 7.9.2009, x86_64, AMD EPYC 7352 24-Core Processor (zen2), Python 2.7.5
See https://gist.github.com/5df2338f9c42dd78c74088630e6cfc41 for a full test report.

**Comment by Micket** [comment]
find_package with UShER also seems to work fine with this so I think it's good to go

**Comment by Micket** [comment]
Going in, thanks @Flamefire!

**Pull request merged**
