### PR TITLE
{bio}[foss/2022a] QIIME2 v2023.5.1, UniFrac v1.3.2

### PR DESCRIPTION
**Pull request by smoors**
(created using `eb --new-pr`)
depends on:
- #18408 

based on #16945 (@migueldiascosta )

### CODE REVIEW

**Comment by verdurin** [comment]
@boegelbot please test @ generoso

**Comment by verdurin** [comment]
@smoors ah, I missed the `Seaborn` dep. Is that in progress, or something you need to add?

**Comment by smoors** [comment]
> @smoors ah, I missed the `Seaborn` dep. Is that in progress, or something you need to add?

@verdurin my bad, we accidentally have a different version installed in our cluster.
fixed.

**Comment by casparvl** [comment]
@boegelbot please test @ generoso

**Comment by casparvl** [comment]
@boegelbot please test @ jsc-zen2

**Comment by casparvl** [comment]
Test report by @casparvl
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in total)
tcn222.local.snellius.surf.nl - Linux RHEL 8.6, x86_64, AMD EPYC 7H12 64-Core Processor, Python 3.6.8
See https://gist.github.com/casparvl/2158a8c8ce098731b5952773fd5cf26d for a full test report.

**Review by casparvl — APPROVED** [review]
Looks good to me. Just for future reference: this QIIME2 easyconfig is the first that isn't based on a conda easyblock (as previous versions where). That's why it is now at the foss level and dependent on a large quantity of dependencies.

I applaud the effort @smoors , this must have been quite a bit of work!

**Comment by casparvl** [comment]
Going in, thanks @smoors!

**Pull request merged**
