### PR TITLE
{bio}[GCC/10.3.0] fastp 0.23.2

### PR DESCRIPTION
**Pull request by pescobar**

### CODE REVIEW

**Comment by migueldiascosta** [comment]
@boegelbot please test @ generoso

**Comment by migueldiascosta** [comment]
@boegelbot please test @ jsc-zen2

**Comment by migueldiascosta** [comment]
@pescobar I suppose `libdeflate` does fit the criteria of being performance sensitive, but I wonder if anyone would actually want to build it with other compilers, which is the only real reason to use `GCC` instead of `GCCcore` (?)

but if that's the case (no strong feelings either way), then a) the `binutils` dependency is no longer necessary, since it's pulled by `GCC`, and b) should all of the existing easyconfigs be bumped to `GCC`?

**Comment by pescobar** [comment]
@migueldiascosta the only reason why I choosed `GCC` instead of `GCCcore` is because `GCCcore` is confusing for some of my users but you are probably right and it makes sense to use `GCCcore` for libdeflate. I will update the PR.

**Comment by migueldiascosta** [comment]
Test report by @migueldiascosta
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in total)
c2dhpc - Linux CentOS Linux 7.6.1810, x86_64, AMD EPYC 7601 32-Core Processor (zen), Python 2.7.5
See https://gist.github.com/6359e087ed72e1124e427f9478eb816b for a full test report.

**Review by migueldiascosta — APPROVED** [review]
lgtm

**Comment by migueldiascosta** [comment]
Going in, thanks @pescobar!

**Pull request merged**
