### PR TITLE
{foss/2017b} add Tkinter as dependency for ASE & matplotlib using Python 3.6.3

### PR DESCRIPTION
**Pull request by schiotz**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by schiotz** [comment]
This PR depends on https://github.com/easybuilders/easybuild-easyblocks/pull/1347 which fixes compilation of Tkinter for Python 3.X.

The removal of Tkinter from Python caused other packages to be built without Tkinter support.  For example, matplotlib loses its ability to show plots interactively and ASE loses its GUI.  The fix in both cases is to build Tkinter and depend on it.

The tkinter.py easyblock only worked for Python 2.7.  This PR adds Tkinter for 3.6 but depends on a fixed easyblock.  It also contains a 2.7 version of Tkinter built with foss/2017b; merely to verify that the modification to the easyblock did not break Python 2.7 compatibility.

**Comment by schiotz** [comment]
Test report by @schiotz
**SUCCESS**
Build succeeded for 14 out of 14 (4 easyconfigs in this PR)
thul.fysik.dtu.dk - Linux centos linux 7.4.1708, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.7.5
See https://gist.github.com/534c996b3c4afe203dbeead532507a0a for a full test report.

**Comment by schiotz** [comment]
Test report by @schiotz
**SUCCESS**
Build succeeded for 4 out of 4 (4 easyconfigs in this PR)
thul.fysik.dtu.dk - Linux centos linux 7.4.1708, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.7.5
See https://gist.github.com/2d4f4debdd3df1eeac1470ef532a5f5d for a full test report.

**Comment by schiotz** [comment]
Comment regarding tests:

Strangely, most Travis tests have passed and the one that failed looks like it is failing to set up the EasyBuild environment.  This is surprising since Tkinter on our machines only build with the patched EasyBlock.

I forced the use of the patched easyblock with --include-easyblocks=modules/tkinter.py in the tests above.  I had to repeat it as I forgot --rebuild and therefore did not test all four easyconfigs in the first run.

**Comment by boegel** [comment]
@schiotz The failing test in Travis was a fluke, I've retriggered the test.

Note that Travis only runs the easyconfigs unit test suite, which checks things like easyconfigs being available for all required dependencies, version conflicts within a dependency graph, etc.

It does not actually try to build the easyconfig files, which explains why the tests pass without having your easyblock PR merged.

**Comment by boegel** [comment]
@schiotz Is there a way to verify (in the sanity check) that the `ASE` GUI is available, and that `matplotlib` has support for interactive plots?

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 4 out of 4 (4 easyconfigs in this PR)
node2036.delcatty.os - Linux centos linux 7.4.1708, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.7.5
See https://gist.github.com/39096f0ad04ad726f23d64a18db0071b for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 4 out of 4 (4 easyconfigs in this PR)
node2428.golett.os - Linux centos linux 7.4.1708, Intel(R) Xeon(R) CPU E5-2680 v3 @ 2.50GHz, Python 2.7.5
See https://gist.github.com/67ee3897d22ab4129e381eafa64cf447 for a full test report.

**Comment by Micket** [comment]
@boegel Something like this may work
```bash
python -c "import matplotlib; matplotlib.use('XXX'); import matplotlib.pyplot"
```
where XXX is either TkAgg, Qt4Agg. Matplotlib wouldn't really depend on Tk specifically, but at least one of the backends is highly recommended.

For newer ASE-gui, it should work if Tkinter can be imported, so just
```bash
python -c "import Tkinter"
```
(older versions also used pygtk, but I believe this was dropped due to make the code python 3 compatible)

**Comment by mikstr** [comment]
Test report by @mikstr
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in this PR)
gamow.fysik.dtu.dk - Linux centos linux 7.4.1708, Intel(R) Core(TM) i5-6500 CPU @ 3.20GHz, Python 2.7.5
See https://gist.github.com/93ace56837de7c1e50aa37da91a376de for a full test report.

**Comment by boegel** [comment]
@Micket Thanks for the suggestions, the `matplotlib` one definitely seems like the right way to check this:

```
$ python -c "import matplotlib; matplotlib.use('TkAgg'); import matplotlib.pyplot"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/xxx/software/matplotlib/2.1.0-foss-2017b-Python-3.6.3/lib/python3.6/site-packages/matplotlib-2.1.0-py3.6-linux-x86_64.egg/matplotlib/pyplot.py", line 113, in <module>
    _backend_mod, new_figure_manager, draw_if_interactive, _show = pylab_setup()
  File "/xxx/software/matplotlib/2.1.0-foss-2017b-Python-3.6.3/lib/python3.6/site-packages/matplotlib-2.1.0-py3.6-linux-x86_64.egg/matplotlib/backends/__init__.py", line 60, in pylab_setup
    [backend_name], 0)
  File "/xxx/software/matplotlib/2.1.0-foss-2017b-Python-3.6.3/lib/python3.6/site-packages/matplotlib-2.1.0-py3.6-linux-x86_64.egg/matplotlib/backends/backend_tkagg.py", line 6, in <module>
    from six.moves import tkinter as Tk
  File "/xxx/software/Python/3.6.3-foss-2017b/lib/python3.6/site-packages/six-1.11.0-py3.6.egg/six.py", line 92, in __get__
    result = self._resolve()
  File "/xxx/software/Python/3.6.3-foss-2017b/lib/python3.6/site-packages/six-1.11.0-py3.6.egg/six.py", line 115, in _resolve
    return _import_module(self.mod)
  File "/xxx/software/Python/3.6.3-foss-2017b/lib/python3.6/site-packages/six-1.11.0-py3.6.egg/six.py", line 82, in _import_module
    __import__(name)
  File "/xxx/software/Python/3.6.3-foss-2017b/lib/python3.6/tkinter/__init__.py", line 36, in <module>
    import _tkinter # If this fails your Python may not be configured for Tk
ModuleNotFoundError: No module named '_tkinter'
```

@schiotz This should be included as a sanity check command in all `matplotlib` easyconfigs?

I'm hoping for a more direct way to check `ASE` though...

**Comment by schiotz** [comment]
@boegel 
I am afraid there is no better way to check the GUI in ASE.  It is installed no matter what, it just fails with an import error if Tkinter is not present.  Does it make sense to check if Tkinter can be imported in the ASE easyconfig if it already depends on Tkinter, and that one should have checked it already?  

It would be nice if one could start the gui in the sanity check, but I am sure that is a bad idea, one cannot asssume that $DISPLAY is set and that it is safe to pop up a window.

In matplotlib I guess it makes a lot of sense to test for the TkAgg backend. I am not sure how to add such a test to an easyconfig; I assume I just add the command to be run to some variable.

**Comment by Micket** [comment]
@boegel Well `ase gui` would fail if you don't have Tkinter, but as it is a interactive graphical application, it wouldn't close automatically upon success, and `ase` also catches the exception, and exits with 0 anyway, so that's not useful either way.

**Comment by boegel** [comment]
@schiotz Adding the check to the `matplotlib` easyconfig is as simple as including:

```python
sanity_check_commands = ["python -c 'import matplotlib; matplotlib.use('TkAgg'); import matplotlib.pyplot' "]
```

(although you may have to reformat that a bit to stay within the 120-character line length limit)

If we can't figure out a better way, including this in the `ASE` easyconfig makes sense:

```python
# make sure Tkinter is available, otherwise 'ase gui' will not work
sanity_check_commands = ["python -c 'import Tkinter' "]
```

Are you up for taking care of this? If so, please do so via separate PRs for `matplotlib` and `ASE` (except for the eaysconfigs you're modifying already in this PR).

**Comment by schiotz** [comment]
@boegel Yes, I can do this.  I will look at it next week.

Jakob

**Comment by schiotz** [comment]
@boegel I have added the sanity check.  

The Travis error is a single test crashing with what looks like a hardware error: `curl: (56) SSL read: error:00000000:lib(0):func(0):reason(0), errno 104`

**Comment by boegel** [comment]
@schiotz I've re-triggered the failing test (for future occurrences like this, you can trigger a re-test yourself by closing & re-opening the PR).

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 4 out of 4 (4 easyconfigs in this PR)
node2431.golett.os - Linux centos linux 7.4.1708, Intel(R) Xeon(R) CPU E5-2680 v3 @ 2.50GHz, Python 2.7.5
See https://gist.github.com/9f24895df87369132c87b6a607dfe438 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 4 out of 4 (4 easyconfigs in this PR)
gligar02.gligar.os - Linux centos linux 7.4.1708, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.7.5
See https://gist.github.com/d36b061ba76ded8b68a03c0f985f9092 for a full test report.

**Comment by boegel** [comment]
Going in, thanks @schiotz!

**Pull request merged**
