### PR TITLE
fix OpenBLAS 0.3.15 patch to correctly set the CPU core type for Tiger Lake

### PR DESCRIPTION
**Pull request by micaeljtoliveira**
(created using `eb --new-pr`)

### CODE REVIEW

**Review by akesandgren — APPROVED** [review]
LGTM, patch matches changes from 0.3.15 to 0.3.18

**Comment by akesandgren** [comment]
@boegelbot Please test @ generoso

**Comment by akesandgren** [comment]
The updated patch fails to apply to 0.3.12.
Please provide a working, separate, one for 0.3.12

**Comment by micaeljtoliveira** [comment]
@akesandgren Sorry for the long delay in addressing the problem with 0.3.12. I tried to fix the patch, but it seems that for it to actually work one would need to backport a lot more changes from later versions of OpenBLAS. So instead I just kept the current patch as it is for that version. Hope that's okay.

**Comment by akesandgren** [comment]
Test report by @akesandgren
**SUCCESS**
Build succeeded for 0 out of 0 (2 easyconfigs in total)
b-an02.hpc2n.umu.se - Linux Ubuntu 20.04, x86_64, Intel(R) Xeon(R) CPU E5-2690 v4 @ 2.60GHz, Python 3.8.10
See https://gist.github.com/aff690d93a364f796ae7042587dc8a31 for a full test report.

**Comment by akesandgren** [comment]
Test report by @akesandgren
**FAILED**
Build succeeded for 0 out of 2 (2 easyconfigs in total)
b-an02.hpc2n.umu.se - Linux Ubuntu 20.04, x86_64, Intel(R) Xeon(R) CPU E5-2690 v4 @ 2.60GHz, Python 3.8.10
See https://gist.github.com/43c51dc98e8e1e02c311e5d60be9ceb8 for a full test report.

**Comment by akesandgren** [comment]
@micaeljtoliveira Can you take a look at this, https://gist.github.com/sassy-crick/cc750a24bd1404c1c9a6f8a2c09c10aa ?

Built on a "11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz"

**Comment by micaeljtoliveira** [comment]
@akesandgren Not quite sure what to do about this. The issue with 0.3.12 is to be expected. As mentioned above, to fix it one would need to backport more fixes made in later versions of OpenBLAS. I tried to do that, but without much success: compilation what still broken even after including several more changes to the patch. Regarding the Lapack timing, that's a strange error, as I can't see any changes in the PR that could do that.

**Comment by akesandgren** [comment]
Just wanted you to verify that it's what you'd expect for the 0.3.12 build.
The timing error can be ignored, we don't use that part as far as I know.

**Review by akesandgren — APPROVED** [review]
LGTM

**Comment by akesandgren** [comment]
Going in, thanks @micaeljtoliveira!

**Pull request merged**
