### PR TITLE
{math}[foss/2021b] EGTtools v0.1.10.dev2 w/ Python 3.9.6

### PR DESCRIPTION
**Pull request by smoors**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by smoors** [comment]
Test report by @smoors
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
node304.hydra.os - Linux CentOS Linux 7.9.2009, x86_64, Intel(R) Xeon(R) Gold 6148 CPU @ 2.40GHz (skylake_avx512), Python 2.7.5
See https://gist.github.com/ea3cb365ab12c9d9d021ba3d64ffb441 for a full test report.

**Comment by smoors** [comment]
@boegelbot: please test @ generoso

**Review by lexming — APPROVED** [review]
LGTM

**Comment by lexming** [comment]
Going in, thanks @smoors !

**Pull request merged**
