### PR TITLE
use custom easyblock for recent sympy easyconfigs to prevent test failures

### PR DESCRIPTION
**Pull request by casparvl**
(created using `eb --new-pr`)

requires:
* https://github.com/easybuilders/easybuild-easyblocks/pull/2949

fixes https://github.com/easybuilders/easybuild-easyconfigs/issues/17593

### CODE REVIEW

**Comment by casparvl** [comment]
@boegelbot please test @ generoso
EB_ARGS="--include-easyblocks-from-pr=2929"

**Comment by casparvl** [comment]
@boegelbot please test @ jsc-zen2
EB_ARGS="--include-easyblocks-from-pr=2949"

**Comment by casparvl** [comment]
Test report by @casparvl
**FAILED**
Failed during parsing of the easyconfigs, so no ecs were built (5 easyconfigs in total)
int5 - Linux RHEL 8.6, x86_64, AMD EPYC 7F72 24-Core Processor, Python 3.6.8
See https://gist.github.com/casparvl/3ffa7abb3fa375ea45bd7fb640deb213 for a full test report.

**Comment by casparvl** [comment]
Test report by @casparvl
Using easyblocks from PR(s) https://github.com/easybuilders/easybuild-easyblocks/pull/2949
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
tcn1.local.snellius.surf.nl - Linux RHEL 8.6, x86_64, AMD EPYC 7H12 64-Core Processor, Python 3.6.8
See https://gist.github.com/casparvl/73c2a763d0e5141c6f27d47878e5f565 for a full test report.

**Comment by casparvl** [comment]
@boegelbot please test @ generoso
EB_ARGS="--include-easyblocks-from-pr=2949"

**Comment by casparvl** [comment]
@boegelbot please test @ jsc-zen2
EB_ARGS="--include-easyblocks-from-pr=2949"

**Comment by casparvl** [comment]
Test report by @casparvl
Using easyblocks from PR(s) https://github.com/easybuilders/easybuild-easyblocks/pull/2949
**FAILED**
Build succeeded for 6 out of 14 (7 easyconfigs in total)
tcn471.local.snellius.surf.nl - Linux RHEL 8.6, x86_64, AMD EPYC 7H12 64-Core Processor, Python 3.6.8
See https://gist.github.com/casparvl/35eec2cbcfe0ad8e2ee98e5bece18081 for a full test report.

**Comment by casparvl** [comment]
The failure above was due to missing the intel toolchain, and not passing the command line arg to accept the usage agreement. I'll do a rerun of the tests, but without `--rebuild`, so as to not wait for the foss-based builds (which were succesful).

**Comment by casparvl** [comment]
Test report by @casparvl
Using easyblocks from PR(s) https://github.com/easybuilders/easybuild-easyblocks/pull/2949
**SUCCESS**
Build succeeded for 7 out of 7 (7 easyconfigs in total)
tcn30.local.snellius.surf.nl - Linux RHEL 8.6, x86_64, AMD EPYC 7H12 64-Core Processor, Python 3.6.8
See https://gist.github.com/casparvl/f97580f4250f70f9ae9c8ca11d4620a1 for a full test report.

**Comment by boegel** [comment]
@boegelbot please test @ generoso
EB_ARGS="--include-easyblocks-from-pr=2949"

**Review by boegel — APPROVED** [review]
lgtm

**Comment by boegel** [comment]
@boegelbot please test @ jsc-zen2
EB_ARGS="--include-easyblocks-from-pr=2949"

**Comment by boegel** [comment]
Test report by @boegel
Using easyblocks from PR(s) https://github.com/easybuilders/easybuild-easyblocks/pull/2949
**SUCCESS**
Build succeeded for 5 out of 5 (5 easyconfigs in total)
node3106.skitty.os - Linux RHEL 8.6, x86_64, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz (skylake_avx512), Python 3.6.8
See https://gist.github.com/boegel/e7989a6559765c9840b6441f36f751bc for a full test report.

**Comment by boegel** [comment]
Going in, thanks @casparvl!

**Pull request merged**
