### PR TITLE
{phys}[foss/2020b] PyPSA v0.17.1 w/ Python 3.8.6

### PR DESCRIPTION
**Pull request by Micket**
(created using `eb --new-pr`)

- [x] #13672

### CODE REVIEW

**Comment by Micket** [comment]
Test report by @Micket
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
alvis-c1 - Linux centos linux 7.9.2009, x86_64, Intel Xeon Processor (Skylake), Python 3.6.8
See https://gist.github.com/92e4f46fb0678fba186c4ec3d6ab6b3b for a full test report.

**Comment by SebastianAchilles** [comment]
Test report by @sebastianachilles
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
rocky8-eb - Linux rocky linux 8.4, x86_64, Intel(R) Core(TM) i7-6900K CPU @ 3.20GHz (broadwell), Python 3.6.8
See https://gist.github.com/72cd1a268293272f2eb8e1fb33b5eab5 for a full test report.

**Review by SebastianAchilles — COMMENTED** [review]
Do we want to add `cartopy` as dependency?

And do we want to add the optional, but recommended dependencies:
- `iPython`
- `plotly`
- `py.test`

**Comment by Micket** [comment]
I didn't see any need for ipython. I added cartopy and it's dependencies. I opted opted out of plotly since it's just optional and users can just load that module if they plan to make interactive plots. pytest is already part of Python
I added some builddeps that where just used in the tests, which meant i had to move this to 2020b since pandapower doesn't support newest numpy.

One test fails, and there is no obvious way to fix it. The tests aren't unit tests, but whole problems, and it breaks due to pypsa dividing by zero, producing nan values everywhere. I just ignored this tests as the rest worked. I'm done with this software now, jesus christ that was a lot of ef'ing PRs :(

**Comment by SebastianAchilles** [comment]
@boegelbot please test @ generoso

**Comment by SebastianAchilles** [comment]
Test report by @sebastianachilles
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in total)
centos8-eb - Linux centos linux 8.3.2011, x86_64, Intel(R) Core(TM) i7-8700 CPU @ 3.20GHz (skylake), Python 3.6.8
See https://gist.github.com/b49d1d9704748d020a0ad4011934df52 for a full test report.

**Comment by Micket** [comment]
forgot about this PR being stuck as a draft

**Comment by SebastianAchilles** [comment]
Test report by @sebastianachilles
**FAILED**
Build succeeded for 4 out of 12 (2 easyconfigs in total)
rocky8-eb - Linux rocky linux 8.4, x86_64, Intel(R) Core(TM) i7-6900K CPU @ 3.20GHz (broadwell), Python 3.6.8
See https://gist.github.com/2cf238994848d49ad5ad410fccd4300c for a full test report.

**Comment by SebastianAchilles** [comment]
> Test report by @SebastianAchilles
> **FAILED**
> Build succeeded for 4 out of 12 (2 easyconfigs in total)
> rocky8-eb - Linux rocky linux 8.4, x86_64, Intel(R) Core(TM) i7-6900K CPU @ 3.20GHz (broadwell), Python 3.6.8
> See https://gist.github.com/2cf238994848d49ad5ad410fccd4300c for a full test report.

I run out of disk space...

**Review by SebastianAchilles — APPROVED** [review]
lgtm

**Comment by SebastianAchilles** [comment]
Test report by @sebastianachilles
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in total)
rocky8-eb - Linux rocky linux 8.4, x86_64, Intel(R) Core(TM) i7-6900K CPU @ 3.20GHz (broadwell), Python 3.6.8
See https://gist.github.com/397ffccb9c85e153b8ec42a81105cae5 for a full test report.

**Comment by SebastianAchilles** [comment]
Going in, thanks @Micket!

**Pull request merged**
