### PR TITLE
{compiler}[dummy/] PGI v19.1

### PR DESCRIPTION
**Pull request by boegel**
(created using `eb --new-pr`)

requires ~~https://github.com/easybuilders/easybuild-easyblocks/pull/1653~~

### CODE REVIEW

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
node3108.skitty.os - Linux centos linux 7.6.1810, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz, Python 2.7.5
See https://gist.github.com/db8f38a944566615b26ed9093d100fce for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
node2400.golett.os - Linux centos linux 7.6.1810, Intel(R) Xeon(R) CPU E5-2680 v3 @ 2.50GHz, Python 2.7.5
See https://gist.github.com/454ef5388bc49e008914af6d05fa7232 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
node2012.delcatty.os - Linux centos linux 7.6.1810, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.7.5
See https://gist.github.com/8b0fa31dd1c8ecdf62d1ae8530fef695 for a full test report.

**Comment by damianam** [comment]
I'd argue that it requires https://github.com/easybuilders/easybuild-framework/pull/2823 too

**Comment by boegel** [comment]
@damianam Well, only if you want to use this as a `toolchain`, not to install it. ;)

Anyway, https://github.com/easybuilders/easybuild-framework/pull/2823 is merged too now...

**Comment by damianam** [comment]
> @damianam Well, only if you want to use this as a `toolchain`, not to install it. ;)

You are technically correct. The best kind of correct. I guess.

lgtm, going in

**Pull request merged**
