### PR TITLE
{bio}[foss/2020b] GROMACS v2021

### PR DESCRIPTION
**Pull request by akesandgren**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by akesandgren** [comment]
Test report by @akesandgren
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
b-cn1522.hpc2n.umu.se - Linux UNKNOWN UNKNOWN, x86_64, Intel(R) Xeon(R) Gold 6132 CPU @ 2.60GHz, Python 3.8.5
See https://gist.github.com/3dd8205c6ed0ae16ae0b94e5b10e9b22 for a full test report.

**Comment by akesandgren** [comment]
@boegelbot Please test @ generoso

**Comment by akesandgren** [comment]
@boegelbot please test @ generoso

**Comment by verdurin** [comment]
Test report by @verdurin
**SUCCESS**
Build succeeded for 3 out of 3 (1 easyconfigs in total)
easybuild-c7.novalocal - Linux centos linux 7.9.2009, x86_64, Intel Xeon Processor (Skylake, IBRS), Python 3.6.8
See https://gist.github.com/6e479a30db6481f22e3d5f62f01d2352 for a full test report.

**Comment by verdurin** [comment]
Test report by @verdurin
**FAILED**
Build succeeded for 0 out of 1 (1 easyconfigs in total)
nuc.lan - Linux Fedora 32, x86_64, Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz, Python 3.8.7
See https://gist.github.com/106d670229572f850e6c223880520590 for a full test report.

**Comment by akesandgren** [comment]
I was expecting these failures in the FourCenter tests on non-skylake nodes. See https://gromacs.bioexcel.eu/t/test-failure-in-fourcenter-tests-in-gromacs-2021/1633

Still waiting for a reply on that.

**Comment by akesandgren** [comment]
@boegelbot please test @ generoso

**Comment by akesandgren** [comment]
Test report by @akesandgren
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
b-cn0909.hpc2n.umu.se - Linux UNKNOWN UNKNOWN, x86_64, Intel(R) Xeon(R) CPU E5-2690 v4 @ 2.60GHz, Python 3.8.5
See https://gist.github.com/afd041bbf67ac48285538a8a531ac5ca for a full test report.

**Comment by akesandgren** [comment]
Test report by @akesandgren
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
b-cn1522.hpc2n.umu.se - Linux UNKNOWN UNKNOWN, x86_64, Intel(R) Xeon(R) Gold 6132 CPU @ 2.60GHz, Python 3.8.5
See https://gist.github.com/5cba60b6c609f9fb8facd3610bc2e19f for a full test report.

**Comment by zao** [comment]
Test report by @zao
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
eb-u2004 - Linux Ubuntu 20.04, x86_64, Intel(R) Core(TM) i7-8700K CPU @ 3.70GHz, Python 3.8.5
See https://gist.github.com/9a9ebfe89a14471593d0f6178347a231 for a full test report.

**Review by verdurin — APPROVED** [review]
Looks fine.

**Comment by verdurin** [comment]
Going in, thanks @akesandgren!

**Comment by verdurin** [comment]
Test report by @verdurin
**SUCCESS**
Build succeeded for 3 out of 3 (1 easyconfigs in total)
easybuild-c7.novalocal - Linux centos linux 7.9.2009, x86_64, Intel Xeon Processor (Skylake, IBRS), Python 3.6.8
See https://gist.github.com/f4140c8fcb26027259867ff235e1e8e4 for a full test report.

**Pull request merged**
