### PR TITLE
{cae}[system/system] LS-PrePost v4.6.24, LS-PrePost v4.7.15

### PR DESCRIPTION
**Pull request by JackPerdue**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by verdurin** [comment]
Test report by @verdurin
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in this PR)
easybuild.novalocal - Linux centos linux 7.8.2003, x86_64, Intel Xeon Processor (Skylake, IBRS), Python 2.7.5
See https://gist.github.com/74a734fb4e84efd00fd86b7d670191d7 for a full test report.

**Comment by verdurin** [comment]
@JackPerdue any chance of a test report for this?

**Comment by JackPerdue** [comment]
Test report by @JackPerdue
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in this PR)
tlogin-0502.cluster - Linux centos linux 7.8.2003, x86_64, Intel(R) Xeon(R) CPU E5-2680 v4 @ 2.40GHz, Python 2.7.5
See https://gist.github.com/0639cc282ce83ac37313f746bf6dbcf4 for a full test report.

**Comment by verdurin** [comment]
Test report by @verdurin
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in this PR)
easybuild.novalocal - Linux centos linux 7.8.2003, x86_64, Intel Xeon Processor (Skylake, IBRS), Python 2.7.5
See https://gist.github.com/868db26b5efac7674cb5d9463b4090cc for a full test report.

**Comment by verdurin** [comment]
Going in, thanks @JackPerdue!

**Pull request merged**
