### PR TITLE
{ai}[foss/2022b] PyTorch v2.1.2

### PR DESCRIPTION
**Pull request by Flamefire**
(created using `eb --new-pr`)

Update over https://github.com/easybuilders/easybuild-easyconfigs/pull/19087

### CODE REVIEW

**Comment by casparvl** [comment]
Test report by @casparvl
**FAILED**
Build succeeded for 2 out of 3 (3 easyconfigs in total)
gcn6.local.snellius.surf.nl - Linux RHEL 8.6, x86_64, Intel(R) Xeon(R) Platinum 8360Y CPU @ 2.40GHz, 4 x NVIDIA NVIDIA A100-SXM4-40GB, 535.104.12, Python 3.6.8
See https://gist.github.com/casparvl/0c3cafe86d827f2919f25590d11fd4d0 for a full test report.

**Comment by Flamefire** [comment]
Test report by @Flamefire
**SUCCESS**
Build succeeded for 3 out of 3 (3 easyconfigs in total)
n1134 - Linux RHEL 8.7 (Ootpa), x86_64, Intel(R) Xeon(R) Platinum 8470 (icelake), Python 3.8.13
See https://gist.github.com/Flamefire/e5d44950d651eee8be354239eda26943 for a full test report.

**Comment by casparvl** [comment]
```
WARNING: 3 test failures, 0 test errors (out of 0):
test_jit 1/1 (1 failed, 2331 passed, 156 skipped, 12 xfailed, 2 rerun)
test_jit_legacy 1/1 (1 failed, 2336 passed, 151 skipped, 12 xfailed, 2 rerun)
test_jit_profiling 1/1 (1 failed, 2331 passed, 156 skipped, 12 xfailed, 2 rerun)
test_jit 1/1 (5452 passed, 135 skipped)
```

**Comment by Flamefire** [comment]
Test report by @Flamefire
**SUCCESS**
Build succeeded for 3 out of 3 (3 easyconfigs in total)
i8023 - Linux Rocky Linux 8.7, x86_64, AMD EPYC 7352 24-Core Processor (zen2), Python 3.6.8
See https://gist.github.com/Flamefire/d1255461853e69d1e977edd2b3a2e9b4 for a full test report.

**Comment by Flamefire** [comment]
Marking this as ready as it doesn't seem to fail more than 2.1.0 so this might be better than https://github.com/easybuilders/easybuild-easyconfigs/pull/19087

**Comment by SebastianAchilles** [comment]
@boegelbot please test @ generoso
CORE_CNT=16

**Comment by akesandgren** [comment]
Test report by @akesandgren
**SUCCESS**
Build succeeded for 1 out of 1 (3 easyconfigs in total)
b-cn1603.hpc2n.umu.se - Linux Ubuntu 22.04, x86_64, AMD EPYC 7313 16-Core Processor, 1 x NVIDIA NVIDIA A100 80GB PCIe, 525.147.05, Python 3.10.12
See https://gist.github.com/akesandgren/7cadb59b725790cb0cb0e3031126861e for a full test report.

**Comment by SebastianAchilles** [comment]
@boegelbot please test @ jsc-zen2
CORE_CNT=16

**Comment by SebastianAchilles** [comment]
Test report by @sebastianachilles
**SUCCESS**
Build succeeded for 3 out of 3 (3 easyconfigs in total)
zen2-rockylinux-89 - Linux Rocky Linux 8.9, x86_64, AMD EPYC 7452 32-Core Processor (zen2), Python 3.6.8
See https://gist.github.com/SebastianAchilles/65766fdcb1837744ab864dad4364b0e4 for a full test report.

**Comment by Flamefire** [comment]
> Note that the PyTorch-2.1.0_skip-float16-part-test_batchnorm_nhwc_cpu.patch isn't used here. Not sure it's needed (I didn't see any problems) but just in case...

Yes I intentionally removed that hoping this particular failure from 2.1.0 is fixed in 2.1.2  which is one of the main reasons I made those 2.1.2 PRs.

**Comment by SebastianAchilles** [comment]
Test report by @sebastianachilles
**SUCCESS**
Build succeeded for 3 out of 3 (3 easyconfigs in total)
jscclxc2.int.jsc-clx.fz-juelich.de - Linux Rocky Linux 9.3, x86_64, Intel Xeon Processor (Cascadelake) (cascadelake), Python 3.9.18
See https://gist.github.com/SebastianAchilles/10c958e84ac7d00d80a3852adb1e6fbc for a full test report.

**Comment by SebastianAchilles** [comment]
Test report by @sebastianachilles
**SUCCESS**
Build succeeded for 3 out of 3 (3 easyconfigs in total)
jsczen3c2.int.jsc-zen3.fz-juelich.de - Linux Rocky Linux 9.3, x86_64, AMD EPYC-Milan Processor (zen3), Python 3.9.18
See https://gist.github.com/SebastianAchilles/bbed22423e57b30675b2061e387c95c5 for a full test report.

**Review by SebastianAchilles — APPROVED** [review]
lgtm

**Comment by SebastianAchilles** [comment]
Going in, thanks @Flamefire!

**Pull request merged**
