### PR TITLE
{devel}[system/system] ReFrame v3.7.3

### PR DESCRIPTION
**Pull request by boegel**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
node2607.swalot.os - Linux centos linux 7.9.2009, x86_64, Intel(R) Xeon(R) CPU E5-2660 v3 @ 2.60GHz (haswell), Python 3.6.8
See https://gist.github.com/3137d51a377d135bae5130629a1243d5 for a full test report.

**Comment by boegel** [comment]
@boegelbot please test @ generoso

**Comment by verdurin** [comment]
Test report by @verdurin
**FAILED**
Build succeeded for 0 out of 1 (1 easyconfigs in total)
nuc.lan - Linux Fedora 33, x86_64, Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz, Python 3.9.5
See https://gist.github.com/dfc5390bfa606165e2c8acb98f87edda for a full test report.

**Comment by verdurin** [comment]
Test report by @verdurin
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
easybuild-c7.novalocal - Linux centos linux 7.9.2009, x86_64, Intel Xeon Processor (Skylake, IBRS), Python 3.6.8
See https://gist.github.com/6b993762bd2743895001d356c05001e8 for a full test report.

**Comment by verdurin** [comment]
@boegel our old friend: 
```
 The following Python packages were likely not installed correctly because they show a version of '0.0.0':
chrome-gnome-shell
This may be solved by using a *-none-any.whl file as the source instead. See e.g. the SOURCE*_WHL templates.
Otherwise you could check if the package provides a version at all (took 1 min 22 secs)
```
Appears to happen only on Fedora, so can probably be ignored.

**Comment by Micket** [comment]
Test report by @Micket
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
alvis-c1 - Linux centos linux 7.9.2009, x86_64, Intel Xeon Processor (Skylake), Python 3.6.8
See https://gist.github.com/57bea3eb602f45afa90b59c8ced51d9c for a full test report.

**Review by Micket — APPROVED** [review]
lgtm

**Comment by Micket** [comment]
Didn't see the comment until after i reviewed it. Shall we try to do something about that? I suspect it affects all reframe versions if so?

**Comment by boegel** [comment]
`chrome-gnome-shell` is not a dependency of ReFrame at all, so what @verdurin is seeing is a problem with a package he has installed in the OS...

**Comment by verdurin** [comment]
Going in, thanks @boegel!

**Pull request merged**
