### PR TITLE
{lib}[foss/2022a] TensorFlow v2.11.0 w/ Python 3.10.4 (+ CUDA 11.7.0)

### PR DESCRIPTION
**Pull request by Flamefire**
(created using `eb --new-pr`)

- ~[ ] Requires https://github.com/easybuilders/easybuild-easyconfigs/pull/17058~
- ~[ ] Requires https://github.com/easybuilders/easybuild-easyconfigs/pull/17092~
- [x] Requires new Easyblock https://github.com/easybuilders/easybuild-easyblocks/pull/2854
- [x] Requires https://github.com/easybuilders/easybuild-easyconfigs/pull/17114

### CODE REVIEW

**Comment by Flamefire** [comment]
Test report by @Flamefire
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in total)
taurusi8009 - Linux CentOS Linux 7.9.2009, x86_64, AMD EPYC 7352 24-Core Processor (zen2), 8 x NVIDIA NVIDIA A100-SXM4-40GB, 470.57.02, Python 2.7.5
See https://gist.github.com/4649cbf110f9f4aca503ad2185f11064 for a full test report.

**Comment by surak** [comment]
I hope I am wrong, but downloading this MR and checking it against `develop`, I don't see the following patches anywhere:

```
            '%(name)s-2.8.4_exclude-xnnpack-on-ppc.patch',
            '%(name)s-2.8.4_resolve-gcc-symlinks.patch',
            '%(name)s-2.9.1_remove-duplicate-gpu-tests.patch',
```

**Comment by Flamefire** [comment]
> I hope I am wrong, but downloading this MR and checking it against `develop`, I don't see the following patches anywhere:

You are right, they are from the other PRs and I forgot about them and the unmerged https://github.com/easybuilders/easybuild-easyconfigs/pull/17101 likely hides those missing files from the CI check/output by the bot.

See [all my TF PRs here](https://github.com/easybuilders/easybuild-easyconfigs/pulls?q=is%3Aopen+is%3Apr+author%3AFlamefire+tensorflow+) ;-)

**Comment by Flamefire** [comment]
Test report by @Flamefire
**FAILED**
Build succeeded for 1 out of 2 (2 easyconfigs in total)
taurusml3 - Linux RHEL 7.6, POWER, 8335-GTX (power9le), 6 x NVIDIA Tesla V100-SXM2-32GB, 440.64.00, Python 2.7.5
See https://gist.github.com/32062d089aa4a8c351608c9690de7068 for a full test report.

**Comment by Flamefire** [comment]
Test report by @Flamefire
**SUCCESS**
Build succeeded for 4 out of 4 (2 easyconfigs in total)
taurusa12 - Linux CentOS Linux 7.7.1908, x86_64, Intel(R) Xeon(R) CPU E5-2603 v4 @ 1.70GHz (broadwell), 3 x NVIDIA GeForce GTX 1080 Ti, 460.32.03, Python 2.7.5
See https://gist.github.com/f06ae9888ad12b6fd73b8b874e495e08 for a full test report.

**Comment by Flamefire** [comment]
Test report by @Flamefire
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
taurusml3 - Linux RHEL 7.6, POWER, 8335-GTX (power9le), 6 x NVIDIA Tesla V100-SXM2-32GB, 440.64.00, Python 2.7.5
See https://gist.github.com/a8fd86baf9a185e299d949837c4b8370 for a full test report.

**Comment by Flamefire** [comment]
Test report by @Flamefire
**FAILED**
Build succeeded for 1 out of 2 (2 easyconfigs in total)
taurusml3 - Linux RHEL 7.6, POWER, 8335-GTX (power9le), 6 x NVIDIA Tesla V100-SXM2-32GB, 440.64.00, Python 2.7.5
See https://gist.github.com/067bc95b9ca992cbcf7add1601b9d0b0 for a full test report.

**Comment by Flamefire** [comment]
@surak I added those patches to this PR. I hope that doesn't lead to conflicts when the others are merged

**Comment by Flamefire** [comment]
Test report by @Flamefire
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in total)
taurusml3 - Linux RHEL 7.6, POWER, 8335-GTX (power9le), 6 x NVIDIA Tesla V100-SXM2-32GB, 440.64.00, Python 2.7.5
See https://gist.github.com/258344e401ce05d7b0fa984c862fecc0 for a full test report.

**Comment by SebastianAchilles** [comment]
Test report by @sebastianachilles
Using easyblocks from PR(s) https://github.com/easybuilders/easybuild-easyblocks/pull/2854
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in total)
skl-rockylinux-87 - Linux Rocky Linux 8.7, x86_64, Intel(R) Core(TM) i7-10700 CPU @ 2.90GHz (skylake), 1 x NVIDIA NVIDIA RTX A4000, 525.85.12, Python 3.6.8
See https://gist.github.com/5f6f22a50b309756da09053949f5959c for a full test report.

**Comment by Flamefire** [comment]
After discussion with the developers of Eigen I'm testing a variation of the patch for PPC. --> Converted to draft in the meantime.

This only affects PPC, so any other architecture can test & use this already.

**Comment by Flamefire** [comment]
Test report by @Flamefire
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in total)
taurusml24 - Linux RHEL 7.6, POWER, 8335-GTX (power9le), 6 x NVIDIA Tesla V100-SXM2-32GB, 440.64.00, Python 2.7.5
See https://gist.github.com/4f0a8ce1acab5b728900d40b7aefef69 for a full test report.

**Comment by surak** [comment]
```
eb --from-pr=17241 

...
== 2023-02-13 13:08:43,750 robot.py:316 WARNING Missing dependencies (details): [{'full_mod_name': 'dill/0.3.6-foss-2022a', 'short_mod_name': 'dill/0.3.6-foss-2022a', 'name': 'dill', 'version': '0.3.6', 'versionsuffix': '', 'toolchain': {'name': 'foss', 'version': '2022a'}, 'toolchain_inherited': True, 'system': False, 'hidden': False, 'build_only': False, 'external_module': False, 'external_module_metadata': {}}, {'full_mod_name': 'flatbuffers/2.0.7-foss-2022a', 'short_mod_name': 'flatbuffers/2.0.7-foss-2022a', 'name': 'flatbuffers', 'version': '2.0.7', 'versionsuffix': '', 'toolchain': {'name': 'foss', 'version': '2022a'}, 'toolchain_inherited': True, 'system': False, 'hidden': False, 'build_only': False, 'external_module': False, 'external_module_metadata': {}}]
== 2023-02-13 13:08:43,750 robot.py:319 WARNING Missing dependencies (EasyBuild module names): dill/0.3.6-foss-2022a, flatbuffers/2.0.7-foss-2022a
== 2023-02-13 13:08:43,751 build_log.py:171 ERROR EasyBuild crashed with an error (at easybuild/2020/software/EasyBuild/4.7.0/lib/python3.8/site-packages/easybuild/base/exceptions.py:126 in __init__): Missing dependencies: dill/0.3.6-foss-2022a, flatbuffers/2.0.7-foss-2022a (no easyconfig file or existing module found) (at easybuild/2020/software/EasyBuild/4.7.0/lib/python3.8/site-packages/easybuild/tools/robot.py:326 in raise_error_missing_deps)
ERROR: Missing dependencies: dill/0.3.6-foss-2022a, flatbuffers/2.0.7-foss-2022a (no easyconfig file or existing module found)
```

**Comment by surak** [comment]
```
bazel-out/k8-opt-exec-50AE0418/bin/tensorflow/tsl/protobuf/error_codes.pb.h:10:10: fatal error: google/protobuf/port_def.inc: No such file or directory
   10 | #include <google/protobuf/port_def.inc>
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

I remember this problem when we were dealing with 2.9. Did you change something which I am missing?

**Comment by surak** [comment]
If I apply the patch above, I end up here: 

```bash
ERROR: /dev/shm/strube1/jusuf/TensorFlow/2.11.0/foss-2022a-CUDA-11.7/TensorFlow/tensorflow-2.11.0/tensorflow/cc/BUILD:824:11: Compiling tensorflow/cc/framework/cc_op_gen_main.cc failed: undeclared inclusion(s) in rule '//tensorflow/cc:cc_op_gen_main':
this rule is missing dependency declarations for the following files included by 'tensorflow/cc/framework/cc_op_gen_main.cc':
  'bazel-out/k8-opt/bin/external/com_google_protobuf/google/protobuf/io/coded_stream.h'
Target //tensorflow/tools/pip_package:build_pip_package failed to build
```

**Comment by Flamefire** [comment]
> bazel-out/k8-opt-exec-50AE0418/bin/tensorflow/tsl/protobuf/error_codes.pb.h:10:10: fatal error: google/protobuf/port_def.inc: No such file or directory
>    10 | #include <google/protobuf/port_def.inc>
>       |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Are you using the updated easyblock?

**Comment by surak** [comment]
> Are you using the updated easyblock?

I am using the one on the latest easybuild 4.7.0 - is there a newer one around?

**Comment by Flamefire** [comment]
> I am using the one on the latest easybuild 4.7.0 - is there a newer one around?

Yes, see the PR description: https://github.com/easybuilders/easybuild-easyblocks/pull/2854

**Comment by surak** [comment]
> > I am using the one on the latest easybuild 4.7.0 - is there a newer one around?
> 
> Yes, see the PR description: [easybuilders/easybuild-easyblocks#2854](https://github.com/easybuilders/easybuild-easyblocks/pull/2854)

Tested with this one, 

```
ERROR: /dev/shm/strube1/jusuf/TensorFlow/2.11.0/foss-2022a-CUDA-11.7/TensorFlow/tensorflow-2.11.0/tensorflow/cc/BUILD:824:11: Compiling tensorflow/cc/framework/cc_op_gen.cc failed: undeclared inclusion(s) in rule '//tensorflow/cc:cc_op_gen_main':
this rule is missing dependency declarations for the following files included by 'tensorflow/cc/framework/cc_op_gen.cc':
  'bazel-out/k8-opt/bin/external/com_google_protobuf/google/protobuf/io/coded_stream.h'
Target //tensorflow/tools/pip_package:build_pip_package failed to build
INFO: Elapsed time: 732.699s, Critical Path: 43.79s
```

**Comment by surak** [comment]
I see that flatbuffers is there, but it tells me this:

```
	/p/software/jusuf/stages/2023/software/Python/3.10.4-GCCcore-11.3.0/bin/python -m pip check
== 2023-02-16 19:44:27,913 run.py:236 INFO running cmd: /p/software/jusuf/stages/2023/software/Python/3.10.4-GCCcore-11.3.0/bin/python -m pip check 
tensorflow 2.11.0 requires flatbuffers, which is not installed.
  >> command completed: exit 1, ran in 00h00m02s
```

Can it be that we are missing the `flatbuffers-python` one?

**Comment by Flamefire** [comment]
> Can it be that we are missing the `flatbuffers-python` one?

I put that into the main flatbuffers which is referenced in the description: https://github.com/easybuilders/easybuild-easyconfigs/pull/17114

So it doesn't require 2 dependencies (anymore)

**Comment by surak** [comment]
It works for me, installed on Jülich's Juwels Booster, Jureca DC, Juwels Cluster, Jusuf and the HDFML machine.

**Comment by VRehnberg** [comment]
Test report by @VRehnberg
Using easyblocks from PR(s) https://github.com/easybuilders/easybuild-easyblocks/pull/2854
**FAILED**
Build succeeded for 1 out of 2 (1 easyconfigs in total)
alvis10-01 - Linux Rocky Linux 8.6, x86_64, Intel(R) Xeon(R) Gold 6338 CPU @ 2.00GHz, 4 x NVIDIA NVIDIA A40, 520.61.05, Python 3.6.8
See https://gist.github.com/eb5125f112eb4646ce1c02643eedf82f for a full test report.

**Comment by VRehnberg** [comment]
Test report by @VRehnberg
Using easyblocks from PR(s) https://github.com/easybuilders/easybuild-easyblocks/pull/2854
**FAILED**
Build succeeded for 1 out of 2 (1 easyconfigs in total)
alvis10-01 - Linux Rocky Linux 8.6, x86_64, Intel(R) Xeon(R) Gold 6338 CPU @ 2.00GHz, 4 x NVIDIA NVIDIA A40, 520.61.05, Python 3.6.8
See https://gist.github.com/cdcd66e1270467a4944f2978ea78c2fc for a full test report.

**Comment by VRehnberg** [comment]
Test report by @VRehnberg
Using easyblocks from PR(s) https://github.com/easybuilders/easybuild-easyblocks/pull/2854
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
alvis10-01 - Linux Rocky Linux 8.6, x86_64, Intel(R) Xeon(R) Gold 6338 CPU @ 2.00GHz, 4 x NVIDIA NVIDIA A40, 520.61.05, Python 3.6.8
See https://gist.github.com/7268e2407980ffcc78a4599df129231e for a full test report.

**Comment by VRehnberg** [comment]
Test report by @VRehnberg
Using easyblocks from PR(s) https://github.com/easybuilders/easybuild-easyblocks/pull/2854
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
alvis10-01 - Linux Rocky Linux 8.6, x86_64, Intel(R) Xeon(R) Gold 6338 CPU @ 2.00GHz, 4 x NVIDIA NVIDIA A40, 520.61.05, Python 3.6.8
See https://gist.github.com/5801037401d4e7c6341c26023dae0fc7 for a full test report.

**Comment by smoors** [comment]
Test report by @smoors
Using easyblocks from PR(s) https://github.com/easybuilders/easybuild-easyblocks/pull/2854
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
node407.hydra.os - Linux CentOS Linux 7.9.2009, x86_64, AMD EPYC 7282 16-Core Processor, 1 x NVIDIA NVIDIA A100-PCIE-40GB, 515.48.07, Python 3.6.8
See https://gist.github.com/571d6d8dbf550d7d9261c99b8b4b1cd3 for a full test report.

**Review by branfosj — APPROVED** [review]

**Comment by casparvl** [comment]
I'm running into

```
ERROR: /gpfs/nvme1/1/casparl/ebbuildpath/TensorFlow/2.11.0/foss-2022a-CUDA-11.7.0/TensorFlow/bazel-root/6b2d07a5bcce9224adb889dafb5acf77/external/llvm-project/llvm/BUILD.bazel:203:11: Compiling llvm/lib/Support/Watchdog.cpp failed: undeclared inclusion(s) in rule '@llvm-project//llvm:Support':
this rule is missing dependency declarations for the following files included by 'llvm/lib/Support/Watchdog.cpp':
  '/sw/arch/RHEL8/EB_production/2022/software/GCCcore/11.3.0/lib/gcc/x86_64-pc-linux-gnu/11.3.0/include/stddef.h'
Target //tensorflow/tools/pip_package:build_pip_package failed to build
```
which looks similar to https://github.com/bazelbuild/bazel/issues/15359 . Anyone seen that before?  Did I miss to rebuild something / include some patch / ...?

**Comment by branfosj** [comment]
Test report by @branfosj
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
bear-pg0105u03a.bear.cluster - Linux RHEL 8.6, x86_64, Intel(R) Xeon(R) Platinum 8360Y CPU @ 2.40GHz (icelake), Python 3.6.8
See https://gist.github.com/45f97e8b0f9fe03e3c643a8087633d7b for a full test report.

**Comment by branfosj** [comment]
Test report by @branfosj
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
bear-pg0103u11a.bear.cluster - Linux RHEL 8.6, x86_64, Intel(R) Xeon(R) Gold 6330 CPU @ 2.00GHz (icelake), 1 x NVIDIA NVIDIA A100-PCIE-40GB, 520.61.05, Python 3.6.8
See https://gist.github.com/3a48cec8074ec30cfcdbd12fa5c6b8e5 for a full test report.

**Comment by casparvl** [comment]
@boegelbot please test @ jsc-zen2

**Review by casparvl — APPROVED** [review]
Looks good to me. I'll give it one final test run just to make sure that the removal of `LLVM` as build dep doesn't affect anything. Once that completes, I'd consider this ready to be merged.

**Comment by casparvl** [comment]
@boegelbot please test @ generoso

**Comment by casparvl** [comment]
Test report by @casparvl
Using easyblocks from PR(s) https://github.com/easybuilders/easybuild-easyblocks/pull/2854
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in total)
gcn36.local.snellius.surf.nl - Linux Rocky Linux 8.7, x86_64, Intel(R) Xeon(R) Platinum 8360Y CPU @ 2.40GHz, 1 x NVIDIA NVIDIA A100-SXM4-40GB, 515.86.01, Python 3.6.8
See https://gist.github.com/58a87ab8b0764b4a0e5436fcb124dc8e for a full test report.

**Comment by casparvl** [comment]
Going in, thanks @Flamefire!

**Pull request merged**
