### PR TITLE
{bio}[foss/2023a] IsoQuant v3.5.0, gffutils v0.13

### PR DESCRIPTION
**Pull request by PetrKralCZ**
(created using `eb --new-pr`)

resolves https://github.com/vscentrum/vsc-software-stack/issues/388

### CODE REVIEW

**Comment by PetrKralCZ** [comment]
@boegelbot please test @ generoso

**Comment by PetrKralCZ** [comment]
@boegelbot please test @ jsc-zen3

**Review by boegel — APPROVED** [review]
lgtm

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in total)
node3116.skitty.os - Linux RHEL 8.8, x86_64, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz, Python 3.6.8
See https://gist.github.com/boegel/6b52726e46b96a59efd2383a17f3ceca for a full test report.

**Comment by boegel** [comment]
Going in, thanks @PetrKralCZ!

**Pull request merged**
