### PR TITLE
fix homepage in recent HDF5 easyconfigs

### PR DESCRIPTION
**Pull request by boegel**

### CODE REVIEW

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 13 out of 13 (13 easyconfigs in this PR)
gligar03.gligar.os - Linux centos linux 7.4.1708, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.7.5
See https://gist.github.com/5fa2099a9a2cdf34f3b27c2df6a8856e for a full test report.

**Comment by verdurin** [comment]
Test report by @verdurin
**FAILED**
Build succeeded for 5 out of 51 (13 easyconfigs in this PR)
easybuild.novalocal - Linux centos linux 7.5.1804, Intel Xeon E312xx (Sandy Bridge), Python 2.7.5
See https://gist.github.com/0fe4344e4ac519fedb71c02f36c0badf for a full test report.

**Comment by verdurin** [comment]
I think this change is trivial enough not to require two full sets of build tests.

**Comment by verdurin** [comment]
Going in, thanks @boegel!

**Pull request merged**
