### PR TITLE
{bio}[GCCcore/12.1.0] SAMtools v1.16.1, BCFtools v1.16, HTSlib v1.16

### PR DESCRIPTION
**Pull request by Poshi**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by verdurin** [comment]
@Poshi would you be able to add the missing deps for this one?

**Comment by Poshi** [comment]
I should be able, but I realized that these could be a lot. The GCCcore-12.1.0 is an entire tree of dependencies up to its roots. In any case, I can try. There's some way to get the list of dependencies for a specific easyconfig?
Should I add the dependencies to this PR? Or create new PR for each of the dependencies?

**Comment by verdurin** [comment]
You could always go for `GCCcore-11.3.0` instead? Unless there was a specific reason you wanted to be using `GCC 12`?

**Comment by Poshi** [comment]
I could, but then we are talking about something I have neither installed nor tested. In fact, we are talking about something that does not exist.
Either case, I'm pretty sure that just switching the versions in the scripts to GCCcore-11.3.0 and downgrading some dependencies will work, but it would have to be checked.

**Comment by verdurin** [comment]
@Poshi Understand you may not want to change this where you haven't tested yourself.
I think in the meantime I have submitted my own PR for the `1.17` releases, against `GCC/12.2.0` in #17435

**Comment by Poshi** [comment]
Looks fine. There's no easy way for me to put the missing dependencies, and it makes no sense to me to switch to another toolchain. This PR can be ignored, as it is a partial build block.

**Pull request closed without merging**
