### PR TITLE
{lang}[gfbf/2023.09] SciPy-bundle v2023.11

### PR DESCRIPTION
**Pull request by boegel**
(created using `eb --new-pr`)
requires:
* https://github.com/easybuilders/easybuild-easyblocks/pull/3041
* #19317

### CODE REVIEW

**Comment by boegel** [comment]
@boegelbot please test @ generoso
EB_ARGS="--include-easyblocks-from-pr 3041"

**Comment by boegel** [comment]
Test report by @boegel
Using easyblocks from PR(s) https://github.com/easybuilders/easybuild-easyblocks/pull/3041
**SUCCESS**
Build succeeded for 3 out of 3 (3 easyconfigs in total)
node3144.skitty.os - Linux RHEL 8.8, x86_64, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz (skylake_avx512), Python 3.6.8
See https://gist.github.com/boegel/fee3a250fa1ce4a3be673b4bdbc05eb0 for a full test report.

**Comment by boegel** [comment]
@boegelbot please test @ jsc-zen2
EB_ARGS="--include-easyblocks-from-pr 3041"

**Comment by branfosj** [comment]
Test report by @branfosj
Using easyblocks from PR(s) https://github.com/easybuilders/easybuild-easyblocks/pull/3041
**SUCCESS**
Build succeeded for 9 out of 9 (3 easyconfigs in total)
bear-pg0105u03a - Linux RHEL 8.6, x86_64, Intel(R) Xeon(R) Platinum 8360Y CPU @ 2.40GHz (icelake), Python 3.6.8
See https://gist.github.com/branfosj/89d420e9dd246d6d7f0026b5b39d0227 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
Using easyblocks from PR(s) https://github.com/easybuilders/easybuild-easyblocks/pull/3041
**FAILED**
Build succeeded for 2 out of 3 (3 easyconfigs in total)
aarch64-neoverse-v1-node2.int.aws-rocky88-202310.eessi.io - Linux Rocky Linux 8.8, AArch64, ARM UNKNOWN (neoverse_n1), Python 3.6.8
See https://gist.github.com/boegel/0be8e89a0149e5178c429296dce0a0e5 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
Using easyblocks from PR(s) https://github.com/easybuilders/easybuild-easyblocks/pull/3041
**FAILED**
Build succeeded for 2 out of 3 (3 easyconfigs in total)
aarch64-neoverse-v1-node2.int.aws-rocky88-202310.eessi.io - Linux Rocky Linux 8.8, AArch64, ARM UNKNOWN (neoverse_n1), Python 3.6.8
See https://gist.github.com/boegel/1ffbb5630cafecc6112744a3f4a579d3 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 3 out of 3 (3 easyconfigs in total)
node4203.shinx.os - Linux RHEL 8.8, x86_64, AMD EPYC 9654 96-Core Processor (x86_64_v4), Python 3.6.8
See https://gist.github.com/boegel/e8f99b8334081bb9d570a68cdf1ef2c0 for a full test report.

**Comment by bartoldeman** [comment]
Test report by @bartoldeman
Using easyblocks from PR(s) https://github.com/easybuilders/easybuild-easyblocks/pull/3041
**FAILED**
Failed during parsing of the easyconfigs, so no ecs were built (3 easyconfigs in total)
build-node2.computecanada.ca - Linux CentOS Linux 7 (Core), x86_64, Intel Xeon Processor (Skylake, IBRS) (skylake_avx512), Python 3.11.4
See https://gist.github.com/bartoldeman/f12b0656d407ef2910a15d4d08b81902 for a full test report.

**Comment by bartoldeman** [comment]
Test report by @bartoldeman
Using easyblocks from PR(s) https://github.com/easybuilders/easybuild-easyblocks/pull/3041
**FAILED**
Failed during parsing of the easyconfigs, so no ecs were built (3 easyconfigs in total)
build-node2.computecanada.ca - Linux CentOS Linux 7 (Core), x86_64, Intel Xeon Processor (Skylake, IBRS) (skylake_avx512), Python 3.11.4
See https://gist.github.com/bartoldeman/54db9d11fb4bd8df90364933e7e17fd6 for a full test report.

**Review by akesandgren — APPROVED** [review]
LGTM

**Comment by akesandgren** [comment]
Going in, thanks @boegel!

**Comment by SebastianAchilles** [comment]
Test report by @sebastianachilles
Using easyblocks from PR(s) https://github.com/easybuilders/easybuild-easyblocks/pull/3041
**FAILED**
Build succeeded for 2 out of 3 (3 easyconfigs in total)
jrc0880.jureca - Linux Rocky Linux 8.8, x86_64, Intel(R) Xeon(R) Platinum 8452Y (sapphirerapids), 4 x NVIDIA NVIDIA H100 PCIe, 535.104.12, Python 3.6.8
See https://gist.github.com/SebastianAchilles/eac5a313e6631a99349497bda4ad6c77 for a full test report.

**Comment by SebastianAchilles** [comment]
Test report by @sebastianachilles
Using easyblocks from PR(s) https://github.com/easybuilders/easybuild-easyblocks/pull/3041
**FAILED**
Build succeeded for 2 out of 3 (3 easyconfigs in total)
jrc0871.jureca - Linux Rocky Linux 8.8, AArch64, ARM UNKNOWN (neoverse_n1), 2 x NVIDIA NVIDIA A100-PCIE-40GB, 535.104.12, Python 3.6.8
See https://gist.github.com/SebastianAchilles/4a694a7e72c2b7435910fc630633145f for a full test report.

**Comment by branfosj** [comment]
Test report by @branfosj
**FAILED**
Build succeeded for 53 out of 54 (3 easyconfigs in total)
bear-pg0207u20a - Linux RHEL 8.6, x86_64, Intel(R) Xeon(R) Platinum 8480CL (icelake), Python 3.6.8
See https://gist.github.com/branfosj/3001cc3ba68e24f924ec7d0eb77468a2 for a full test report.

**Comment by branfosj** [comment]
Test report by @branfosj
**SUCCESS**
Build succeeded for 57 out of 57 (3 easyconfigs in total)
bear-pg0208u26a - Linux RHEL 8.6, x86_64, AMD EPYC 9554 64-Core Processor (x86_64_v4), Python 3.6.8
See https://gist.github.com/branfosj/3af518af26c7697ed9d0118d0eb49e95 for a full test report.

**Comment by branfosj** [comment]
```
/rds/projects/2017/branfosj-rse/easybuild/EL8-spr/software/binutils/2.40-GCCcore-13.2.0/bin/ld: build/temp.linux-x86_64-cpython-311/build/src.linux-x86_64-3.11/numpy/core/src/npysort/simd_qsort_16bit.dispatch.avx512_icl.o: in function `void avx512_qsort<_Float16>(_Float16*, long)':
/dev/shm/branfosj/build-up-EL8/SciPybundle/2023.11/gfbf-2023.09/numpy/numpy-1.26.2/numpy/core/src/npysort/x86-simd-sort/src/avx512fp16-16bit-qsort.hpp:161: multiple definition of `void avx512_qsort<_Float16>(_Float16*, long)'; build/temp.linux-x86_64-cpython-311/build/src.linux-x86_64-3.11/numpy/core/src/npysort/simd_qsort_16bit.dispatch.avx512_spr.o:/dev/shm/branfosj/build-up-EL8/SciPybundle/2023.11/gfbf-2023.09/numpy/numpy-1.26.2/numpy/core/src/npysort/x86-simd-sort/src/avx512fp16-16bit-qsort.hpp:161: first defined here                     
/rds/projects/2017/branfosj-rse/easybuild/EL8-spr/software/binutils/2.40-GCCcore-13.2.0/bin/ld: build/temp.linux-x86_64-cpython-311/build/src.linux-x86_64-3.11/numpy/core/src/npysort/simd_qsort_16bit.dispatch.avx512_icl.o: in function `void avx512_qselect<_Float16>(_Float16*, long, long)':
/dev/shm/branfosj/build-up-EL8/SciPybundle/2023.11/gfbf-2023.09/numpy/numpy-1.26.2/numpy/core/src/npysort/x86-simd-sort/src/avx512fp16-16bit-qsort.hpp:149: multiple definition of `void avx512_qselect<_Float16>(_Float16*, long, long)'; build/temp.linux-x86_64-cpython-311/build/src.linux-x86_64-3.11/numpy/core/src/npysort/simd_qsort_16bit.dispatch.avx512_spr.o:/dev/shm/branfosj/build-up-EL8/SciPybundle/2023.11/gfbf-2023.09/numpy/numpy-1.26.2/numpy/core/src/npysort/x86-simd-sort/src/avx512fp16-16bit-qsort.hpp:149: first defined here             
collect2: error: ld returned 1 exit status
```

**Pull request merged**
