### PR TITLE
{numlib}[GCC/13.2.0,gompi/2023.09] FFTW v3.3.10, FFTW.MPI v3.3.10

### PR DESCRIPTION
**Pull request by SebastianAchilles**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by SebastianAchilles** [comment]
@boegelbot please test @ jsc-zen2

**Comment by SebastianAchilles** [comment]
Test report by @sebastianachilles
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in total)
bwd-rockylinux-92 - Linux Rocky Linux 9.2 (Blue Onyx), x86_64, Intel(R) Core(TM) i7-6900K CPU @ 3.20GHz (broadwell), 2 x NVIDIA NVIDIA GeForce GTX 1060 6GB, 535.104.05, Python 3.9.16
See https://gist.github.com/SebastianAchilles/84e5e97f7cd5ab21b678c9ea6b77586b for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**FAILED**
Build succeeded for 1 out of 2 (2 easyconfigs in total)
fair-mastodon-c7g-4xlarge-0002 - Linux Rocky Linux 8.7, AArch64, ARM UNKNOWN (neoverse_n1), Python 3.6.8
See https://gist.github.com/boegel/d97b974b8780c93753f1bf7462367082 for a full test report.

**Comment by boegel** [comment]
The failing test on `aarch64/neoverse_v1` (Graviton 3) is what we're also seeing in EESSI, see https://github.com/EESSI/software-layer/issues/325 + https://github.com/FFTW/fftw3/issues/334 .

No reason to block this PR over this, we have a workaround in place in EESSI for this (and we haven't received *any* feedback from upstream on this until now).

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in total)
node3163.skitty.os - Linux RHEL 8.6, x86_64, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz (skylake_avx512), Python 3.6.8
See https://gist.github.com/boegel/0ac3fddeca91729799b9c6365dfbd7d9 for a full test report.

**Comment by SebastianAchilles** [comment]
@boegelbot please test @ jsc-zen2

**Review by boegel — APPROVED** [review]
lgtm

**Comment by boegel** [comment]
Going in, thanks @SebastianAchilles!

**Pull request merged**
