### PR TITLE
fix compilation of Qt5 v5.12.3 and v5.13.1 on Ubuntu 20.04

### PR DESCRIPTION
**Pull request by edmondac**
Compiling Qt5 on Ubuntu 20.04, or other OS with a similarly up to date kernel yields:

```
socketcanbackend.cpp: In member function ‘void SocketCanBackend::readSocket()’:
socketcanbackend.cpp:697:41: error: ‘SIOCGSTAMP’ was not declared in this scope
         if (Q_UNLIKELY(ioctl(canSocket, SIOCGSTAMP, &timeStamp) < 0)) {
                                         ^~~~~~~~~~
```

EL8.2 doesn't have this problem, but perhaps 8.3 will...?

### CODE REVIEW

**Comment by edmondac** [comment]
Test report by @bear-rsg
**FAILED**
Build succeeded for 0 out of 2 (2 easyconfigs in this PR)
bear-pg0211u03a.bear.cluster - Linux centos linux 7.8.2003, x86_64, Intel(R) Xeon(R) Gold 6248 CPU @ 2.50GHz, Python 3.6.8
See https://gist.github.com/712e56b928c3e03c2dc4d6a364f8f41a for a full test report.

**Comment by edmondac** [comment]
Test report by @bear-rsg
**FAILED**
Build succeeded for 0 out of 2 (2 easyconfigs in this PR)
bear-pg0211u03a.bear.cluster - Linux centos linux 7.8.2003, x86_64, Intel(R) Xeon(R) Gold 6248 CPU @ 2.50GHz, Python 3.6.8
See https://gist.github.com/2be9e47588627e9dc0ce0664dd6ed1e4 for a full test report.

**Comment by edmondac** [comment]
Test report by @bear-rsg
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in this PR)
bear-pg0211u03a.bear.cluster - Linux centos linux 7.8.2003, x86_64, Intel(R) Xeon(R) Gold 6248 CPU @ 2.50GHz, Python 3.6.8
See https://gist.github.com/93480fd47a29c4731a9cba9b863ebf8f for a full test report.

**Comment by edmondac** [comment]
A test report for Ubuntu 20.04 is on the way, but it'll take a few days (!) to complete

**Comment by zao** [comment]
Test report by @zao
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in this PR)
freja - Linux Ubuntu 20.04, x86_64, Intel(R) Core(TM) i7-8700K CPU @ 3.70GHz, Python 3.8.2
See https://gist.github.com/bee24989e698f6b26a35388a89550985 for a full test report.

**Comment by edmondac** [comment]
Test report by @bear-rsg
**FAILED**
Build succeeded for 113 out of 127 (2 easyconfigs in this PR)
ubuntu2004-apps-builder-its-rescomp-apps - Linux Ubuntu 20.04, x86_64, Intel Core Processor (Broadwell, no TSX), Python 3.8.2
See https://gist.github.com/99e3535a43a1863df3c95bc1a18ab715 for a full test report.

**Comment by edmondac** [comment]
Test report by @bear-rsg
**SUCCESS**
Build succeeded for 14 out of 14 (2 easyconfigs in this PR)
ubuntu2004-apps-builder-its-rescomp-apps - Linux Ubuntu 20.04, x86_64, Intel Core Processor (Broadwell, no TSX), Python 3.8.5
See https://gist.github.com/2518634d561380969fef428a66e99c93 for a full test report.

**Review by boegel — APPROVED** [review]
lgtm

**Comment by boegel** [comment]
@boegelbot please test @ generoso

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in total)
node3416.kirlia.os - Linux centos linux 7.8.2003, x86_64, Intel(R) Xeon(R) Gold 6240 CPU @ 2.60GHz (cascadelake), Python 2.7.5
See https://gist.github.com/d07375810676fe0f35d46dd7d87bf3a9 for a full test report.

**Comment by boegel** [comment]
@edmondac needs a sync with current `develop` to make the tests pass (see failing tests for latest commit)

**Comment by boegel** [comment]
Going in, thanks @edmondac!

**Pull request merged**
