### PR TITLE
{bio}[GCC/12.3.0] RNA-Bloom v2.0.1, Racon v1.5.0, ntCard v1.2.2

### PR DESCRIPTION
**Pull request by laraPPr**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by laraPPr** [comment]
@boegelbot please test @ generoso

**Comment by laraPPr** [comment]
@boegelbot please test @ jsc-zen3

**Comment by verdurin** [comment]
Test report by @verdurin
**SUCCESS**
Build succeeded for 3 out of 3 (3 easyconfigs in total)
easybuild-c7.novalocal - Linux CentOS Linux 7.9.2009, x86_64, Intel Xeon Processor (Skylake, IBRS), Python 3.6.8
See https://gist.github.com/verdurin/413469295e059a3aa90579fca0092149 for a full test report.

**Review by verdurin — APPROVED** [review]
Looks fine.

**Comment by verdurin** [comment]
Going in, thanks @laraPPr!

**Pull request merged**
