### PR TITLE
{devel}[fosscuda/2018b] Qt5 v5.9.8

### PR DESCRIPTION
**Pull request by dithwick**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by dithwick** [comment]
Test report by @dithwick
**FAILED**
Build succeeded for 0 out of 1 (1 easyconfigs in this PR)
login2 - Linux centos 6.10, Intel(R) Xeon(R) CPU E5-2630 v3 @ 2.40GHz, Python 2.6.6
See https://gist.github.com/d2f342705a669012f643c9f296e18f07 for a full test report.

**Comment by dithwick** [comment]
Test report by @dithwick
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
login2 - Linux centos 6.10, Intel(R) Xeon(R) CPU E5-2630 v3 @ 2.40GHz, Python 2.6.6
See https://gist.github.com/690eff021bab2aa8c7189602181e0611 for a full test report.

**Comment by smoors** [comment]
Test report by @smoors
**FAILED**
Build succeeded for 0 out of 1 (1 easyconfigs in this PR)
nic422 - Linux centos linux 7.5.1804, Intel(R) Xeon(R) Gold 6148 CPU @ 2.40GHz, Python 2.7.5
See https://gist.github.com/86667aacb205f8145fa6e5f82b8de2b3 for a full test report.

**Comment by dithwick** [comment]
> Test report by @smoors
> **FAILED**
> Build succeeded for 0 out of 1 (1 easyconfigs in this PR)
> nic422 - Linux centos linux 7.5.1804, Intel(R) Xeon(R) Gold 6148 CPU @ 2.40GHz, Python 2.7.5
> See https://gist.github.com/86667aacb205f8145fa6e5f82b8de2b3 for a full test report.

Seems odd that you go a



Test report by @smoors
FAILED
Build succeeded for 0 out of 1 (1 easyconfigs in this PR)
nic422 - Linux centos linux 7.5.1804, Intel(R) Xeon(R) Gold 6148 CPU @ 2.40GHz, Python 2.7.5
See https://gist.github.com/86667aacb205f8145fa6e5f82b8de2b3 for a full test report.


> Test report by @smoors
> **FAILED**
> Build succeeded for 0 out of 1 (1 easyconfigs in this PR)
> nic422 - Linux centos linux 7.5.1804, Intel(R) Xeon(R) Gold 6148 CPU @ 2.40GHz, Python 2.7.5
> See https://gist.github.com/86667aacb205f8145fa6e5f82b8de2b3 for a full test report.

Hi smoors,

Thanks for testing the easybuild. Seems odd that you got a whole load of 

```
g++: internal compiler error: Bus error (program cc1plus)
```
errors which I'm guessing is ultimately why it failed. I'll give it a go on our CentOS 7 system to see if I can replicate the error.

**Comment by smoors** [comment]
Test report by @smoors
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
nic402 - Linux centos linux 7.5.1804, Intel(R) Xeon(R) Gold 6148 CPU @ 2.40GHz, Python 2.7.5
See https://gist.github.com/062a0641ad7ac900aa2db0799be396d2 for a full test report.

**Comment by smoors** [comment]
@dithwick it failed the first time because I did not give it enough memory

**Comment by smoors** [comment]
Going in, thanks @dithwick!

**Comment by dithwick** [comment]
> @dithwick it failed the first time because I did not give it enough memory

Ah brilliant, I assumed I had done something wrong ;-)

**Pull request merged**
