### PR TITLE
{tools}[GCCcore/8.3.0] GDCM v3.0.5

### PR DESCRIPTION
**Pull request by crubb**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by verdurin** [comment]
Test report by @verdurin
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
easybuild.novalocal - Linux centos linux 7.7.1908, Intel Xeon Processor (Skylake, IBRS), Python 2.7.5
See https://gist.github.com/c686fdf2325433ef1eb5947dcfde6003 for a full test report.

**Comment by verdurin** [comment]
@crubb any chance of uploading a build report?

**Comment by crubb** [comment]
Test report by @crubb
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
radbert - Linux ubuntu 18.04, Intel(R) Xeon(R) CPU E5-2687W v4 @ 3.00GHz, Python 2.7.17
See https://gist.github.com/09cbd93ae5c800fd93e596d02b1c5225 for a full test report.

**Comment by crubb** [comment]
Test report by @crubb
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
radbert - Linux ubuntu 18.04, Intel(R) Xeon(R) CPU E5-2687W v4 @ 3.00GHz, Python 2.7.17
See https://gist.github.com/c2ce6c5a64dfe7a9fe7a58a994576104 for a full test report.

**Comment by crubb** [comment]
Test report by @crubb
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
radbert - Linux ubuntu 18.04, Intel(R) Xeon(R) CPU E5-2687W v4 @ 3.00GHz, Python 2.7.17
See https://gist.github.com/c0719cd85006816227d7d390e59b62a2 for a full test report.

**Comment by crubb** [comment]
@verdurin Here you go!

**Comment by verdurin** [comment]
Going in, thanks @crubb!

**Pull request merged**
