### PR TITLE
{tools}[GCCcore/11.2.0] x13as v1-1-b59

### PR DESCRIPTION
**Pull request by sassy-crick**
(created using `eb --new-pr`)

See also PR ##16213

### CODE REVIEW

**Comment by jfgrimm** [comment]
Test report by @jfgrimm
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
node025.pri.viking.alces.network - Linux CentOS Linux 7.9.2009, x86_64, Intel(R) Xeon(R) Gold 6138 CPU @ 2.00GHz (skylake_avx512), Python 3.6.8
See https://gist.github.com/c4c4e1183592034d3643b0f0f4594313 for a full test report.

**Comment by jfgrimm** [comment]
@boegelbot please test @ jsc-zen2

**Comment by sassy-crick** [comment]
@jfgrimm  I *might* need to upload the version for `GCCcore-10.2.0` as well. Shall I open a new PR for that or shall I add it to this one as well? Either is fine with me.

**Comment by boegel** [comment]
@boegelbot please test @ generoso

**Review by boegel — APPROVED** [review]
lgtm

**Comment by boegel** [comment]
Going in, thanks @sassy-crick!

**Pull request merged**
