### PR TITLE
{tools}[foss/2023a] s3fs v2023.12.2

### PR DESCRIPTION
**Pull request by pavelToman**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by pavelToman** [comment]
@boegelbot please test @ generoso

**Comment by smoors** [comment]
@boegelbot please test @ jsc-zen2

**Comment by smoors** [comment]
@boegelbot please test @ jsc-zen2

**Review by smoors — DISMISSED** [review]
lgtm

**Review by smoors — APPROVED** [review]

**Comment by smoors** [comment]
Going in, thanks @pavelToman!

**Pull request merged**
