### PR TITLE
hard disable UCX support in recent OpenMPI versions, to dance around bug in OpenMPI configure script

### PR DESCRIPTION
**Pull request by boegel**
fix for #5805

### CODE REVIEW

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 15 out of 15 (15 easyconfigs in this PR)
node2083.delcatty.os - Linux centos linux 7.4.1708, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.7.5
See https://gist.github.com/bb622054c897b9f947df12adc238c627 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 100 out of 100 (15 easyconfigs in this PR)
node2602.swalot.os - Linux centos linux 7.4.1708, Intel(R) Xeon(R) CPU E5-2660 v3 @ 2.60GHz, Python 2.7.5
See https://gist.github.com/a7e0ccd2a733329f2b78c12fba9b20dd for a full test report.

**Comment by OleHolmNielsen** [comment]
Thanks a lot!  This works for me:

$ eb --from-pr 5949 OpenMPI-2.1.2-iccifort-2018.1.163-GCC-6.4.0-2.28.eb 
== temporary log file in case of crash /tmp/eb-WgkLyV/easybuild-d11n9L.log
== processing EasyBuild easyconfig /tmp/eb-WgkLyV/files_pr5949/o/OpenMPI/OpenMPI-2.1.2-iccifort-2018.1.163-GCC-6.4.0-2.28.eb
== building and installing OpenMPI/2.1.2-iccifort-2018.1.163-GCC-6.4.0-2.28...
== fetching files...
== creating build dir, resetting environment...
== unpacking...
== patching...
== preparing...
== configuring...
== building...
== testing...
== installing...
== taking care of extensions...
== postprocessing...
== sanity checking...
== cleaning up...
== creating module...
== permissions...
== packaging...
== COMPLETED: Installation ended successfully
== Results of the build can be found in the log file(s) /home/modules/software/OpenMPI/2.1.2-iccifort-2018.1.163-GCC-6.4.0-2.28/easybuild/easybuild-OpenMPI-2.1.2-20180306.100945.log
== Build succeeded for 1 out of 1
== Temporary log file(s) /tmp/eb-WgkLyV/easybuild-d11n9L.log* have been removed.
== Temporary directory /tmp/eb-WgkLyV has been removed.

**Comment by hajgato** [comment]
I think adding `--without-ucx` is a good idea. Anyway, deleting `ucx-devel` has the same effect. (And as far as I know, we do not use UCX)

**Comment by vanzod** [comment]
Going in, thanks @boegel!

**Pull request merged**
