### PR TITLE
{bio}[foss/2022b] Seurat v5.0.1 w/ R 4.2.2

### PR DESCRIPTION
**Pull request by verdurin**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by verdurin** [comment]
@boegelbot please test @ generoso

**Comment by jfgrimm** [comment]
@boegelbot: please test @ jsc-zen3

**Comment by jfgrimm** [comment]
Test report by @jfgrimm
**FAILED**
Build succeeded for 33 out of 39 (1 easyconfigs in total)
gpu22.viking2.yor.alces.network - Linux Rocky Linux 8.8, x86_64, AMD EPYC 7413 24-Core Processor, 1 x NVIDIA NVIDIA H100 PCIe, 535.86.10, Python 3.6.8
See https://gist.github.com/jfgrimm/f836eedd6419b35c28a9e30cdbef7000 for a full test report.

**Comment by jfgrimm** [comment]
Test report by @jfgrimm
**SUCCESS**
Build succeeded for 6 out of 6 (1 easyconfigs in total)
login2.viking2.yor.alces.network - Linux Rocky Linux 8.8, x86_64, AMD EPYC 7643 48-Core Processor, Python 3.6.8
See https://gist.github.com/jfgrimm/da706a377fb64bee42dba7f1a25afdd9 for a full test report.

**Comment by verdurin** [comment]
@jfgrimm looks like that failure was a transient download problem or similar, not related to this PR?

**Comment by jfgrimm** [comment]
> @jfgrimm looks like that failure was a transient download problem or similar, not related to this PR?

@verdurin indeed

**Review by jfgrimm — APPROVED** [review]
lgtm

**Comment by jfgrimm** [comment]
Going in, thanks @verdurin!

**Pull request merged**
