### PR TITLE
{data}[gfbf/2022b] scikit-learn v1.2.1 w/ Python 3.10.8

### PR DESCRIPTION
**Pull request by VRehnberg**
(created using `eb --new-pr`)
requires:
 - [x] https://github.com/easybuilders/easybuild-easyblocks/issues/2901 to be solved

### CODE REVIEW

**Comment by VRehnberg** [comment]
Note that I've removed the sklearn==0.0 extension that was there in previous versions as I didn't see a reason for having that.

**Comment by boegel** [comment]
> Note that I've removed the sklearn==0.0 extension that was there in previous versions as I didn't see a reason for having that.

Please restore that, see #15613 for motivation

**Comment by branfosj** [comment]
Test report by @branfosj
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
bear-pg0105u03a.bear.cluster - Linux RHEL 8.6, x86_64, Intel(R) Xeon(R) Platinum 8360Y CPU @ 2.40GHz (icelake), Python 3.6.8
See https://gist.github.com/d1b5eb97c19166eeb1e86515666475be for a full test report.

**Comment by branfosj** [comment]
@boegelbot please test @ generoso

**Comment by schiotz** [comment]
Test report by @schiotz
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
slid.fysik.dtu.dk - Linux CentOS Linux 7.9.2009, x86_64, Intel(R) Xeon(R) CPU E5-2650 v4 @ 2.20GHz, Python 2.7.5
See https://gist.github.com/e5c35af3a6e79458e1b0117f437db30b for a full test report.

**Comment by branfosj** [comment]
@boegelbot please test @ jsc-zen2

**Review by branfosj — APPROVED** [review]

**Comment by branfosj** [comment]
Going in, thanks @VRehnberg!

**Pull request merged**
