### PR TITLE
{math}[GCCcore/11.3.0] GDB v12.1, ISL v0.24, MPC v1.2.1, ... w/ Python 3.10.4

### PR DESCRIPTION
**Pull request by Flamefire**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by Flamefire** [comment]
Test report by @Flamefire
**SUCCESS**
Build succeeded for 5 out of 5 (4 easyconfigs in total)
taurusml2 - Linux RHEL 7.6, POWER, 8335-GTX (power9le), 6 x NVIDIA Tesla V100-SXM2-32GB, 440.64.00, Python 2.7.5
See https://gist.github.com/35c467fcc71c5fa476e7d606c7a39fb1 for a full test report.

**Comment by jfgrimm** [comment]
@boegelbot please test @ generoso

**Review by jfgrimm — APPROVED** [review]
LGTM, just waiting on the bot test report

**Comment by jfgrimm** [comment]
Going in, thanks @Flamefire!

**Pull request merged**
