### PR TITLE
{bio}[foss/2022a] nichenetr v1.1.1-20230223

### PR DESCRIPTION
**Pull request by boegel**
(created using `eb --new-pr`)
requires:
* #17523

### CODE REVIEW

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
node3167.skitty.os - Linux RHEL 8.6, x86_64, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz (skylake_avx512), Python 3.6.8
See https://gist.github.com/dad77080940cd69c88d8f890f574e9bc for a full test report.

**Comment by boegel** [comment]
@boegelbot please test @ generoso

**Comment by casparvl** [comment]
@boegelbot please test @ jsc-zen2

**Review by casparvl — APPROVED** [review]
Looks good to me!

**Comment by casparvl** [comment]
Going in, thanks @boegel!

**Pull request merged**
