### PR TITLE
{tools}[GCCcore/13.2.0] IPython + deps (BeautifulSoup v4.12.2, jedi v0.19.1, lxml v4.9.3)

### PR DESCRIPTION
**Pull request by jose-d**
(created using `eb --new-pr`)

update for `IPython` and its dependencies `lxml`, `jedi` and `BeautifulSoup`.

### CODE REVIEW

**Comment by jose-d** [comment]
Test report by @jose-d
**SUCCESS**
Build succeeded for 4 out of 4 (4 easyconfigs in total)
login1.phoebe.lan - Linux Rocky Linux 8.8 (Green Obsidian), x86_64, AMD EPYC 73F3 16-Core Processor, Python 3.11.2
See https://gist.github.com/jose-d/166dee0209b6de86d1363925ec7bcbe3 for a full test report.

**Comment by SebastianAchilles** [comment]
@boegelbot please test @ generoso

**Comment by SebastianAchilles** [comment]
@boegelbot please test @ jsc-zen2

**Comment by SebastianAchilles** [comment]
Test report by @sebastianachilles
**SUCCESS**
Build succeeded for 4 out of 4 (4 easyconfigs in total)
jscclxc1.int.jsc-clx.fz-juelich.de - Linux Rocky Linux 9.3, x86_64, Intel Xeon Processor (Cascadelake) (cascadelake), Python 3.9.18
See https://gist.github.com/SebastianAchilles/86736bc906d92a8fa87f98a9da0354c0 for a full test report.

**Comment by SebastianAchilles** [comment]
Test report by @sebastianachilles
**SUCCESS**
Build succeeded for 4 out of 4 (4 easyconfigs in total)
jsczen3c1.int.jsc-zen3.fz-juelich.de - Linux Rocky Linux 9.3, x86_64, AMD EPYC-Milan Processor (zen3), Python 3.9.18
See https://gist.github.com/SebastianAchilles/354a7baad24246125e61d195978b5f10 for a full test report.

**Review by SebastianAchilles — APPROVED** [review]
lgtm

**Comment by SebastianAchilles** [comment]
Going in, thanks @jose-d!

**Pull request merged**
