### PR TITLE
Change BUSCO 1.22 Python dep 2 to 3 (REVIEW)

### PR DESCRIPTION
**Pull request by hajgato**

### CODE REVIEW

**Comment by boegel** [comment]
@hajgato Please explain the change? Is the existing easyconfig for BUSCO just broken?

Can we enhance the sanity check somehow to capture this?

**Comment by hajgato** [comment]
@boegel: The previous `BUSCO 1.22` with `Python 2` is broken. It seems that `BUSCO 1.22` requires `Python 3` (see http://busco.ezlab.org/v1/files/README.html), what I overlooked  when I made the previous easyconfig.

**Comment by hajgato** [comment]
@boegel I do not know how can we improve the sanity check, as you have to use the program to realize the problem, so you need to provide a testcase.

**Comment by boegel** [comment]
@hajgato What kind of errors did you run into?

BUSCO included some sample data to do a test run, which seems to work fine with Python 2?

```
module load BUSCO/2.0.1-intel-2017a-Python-2.7.13
cd $EBROOTBUSCO/sample_data
BUSCO.py -i target.fa -o SAMPLE -l example -m genome -f
```

**Comment by hajgato** [comment]
@boegel Sure, but that's `BUSCO` `2.0.1`, but this is `BUSCO` `1.22`

**Comment by boegel** [comment]
Urgh, well, OK, but I just tried with BUSCO 1.22 too (`BUSCO_v1.22.py -i target.fa -o SAMPLE -l example -m genome -f` in `$EBROOTBUSCO/sample_data`), and that doesn't spit out any blatently obvious errors too...

How did it fail for you on top of Python 2?

**Comment by hajgato** [comment]
@boegel: This is what I got from the user:
```
Command error: 'python3
/apps/brussel/CO7/magnycours-ib/software/BUSCO/1.22-intel-2017a-Python-2.7.13/BUSCO_v1.22.py
-in OUT.shannon.fasta -f -o OUT.shannon.fasta.metazoa.busco.results -l
/u/etwomey/.dammit/databases/buscodb/metazoa -m trans -c 1' returned 127
```

Surely, I am not bio-software expert.

**Comment by hajgato** [comment]
@boegel: As a matter of fact, it can be `dammit` error as well, because dammit calls `BUSCO`, but since `BUSCO` explicitly requests `Python3` I automatically assumed it needs `Python3`

**Comment by hajgato** [comment]
@boegel: I will put back the original `BUSCO` `Python2` config as well, OK?

**Comment by boegel** [comment]
@hajgato The error you are showing is by calling `python3` on an installation that was done for Python 2, that's never going to work. :)

As long as the BUSCO easyconfig on top of Python 3 works, this is fine by me now. Let's just include `SHA256` checksums for these new eayconfigs?

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 4 out of 4 (4 easyconfigs in this PR)
node2454.golett.os - Linux centos linux 7.4.1708, Intel(R) Xeon(R) CPU E5-2680 v3 @ 2.50GHz, Python 2.7.5
See https://gist.github.com/ddda9246125a934fd49d6b8a93a90ed4 for a full test report.

**Comment by hajgato** [comment]
@boegel I think I just modify `dammit` to call `python` command instead of `python3`

**Comment by hajgato** [comment]
@boegel: and I close this ticket.

**Comment by boegel** [comment]
@hajgato Well, I guess it depends if `dammit` supports Python 2...

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 4 out of 4 (4 easyconfigs in this PR)
node2054.delcatty.os - Linux centos linux 7.4.1708, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.7.5
See https://gist.github.com/adae9093d3806bdd76ea73d3d74f5ef6 for a full test report.

**Comment by hajgato** [comment]
@boegel It seems much easyer to handle the problem in `dammit`. I will close this PR. (This is when you try to quickly solving some problem without digging into the details....)

**Pull request closed without merging**
