### PR TITLE
{bio}[foss/2018b] FastQ_Screen v0.13.0

### PR DESCRIPTION
**Pull request by SethosII**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by vanzod** [comment]
@boegel Can you please clarify the need for the commit below and if it would also apply to this easyconfig file?
https://github.com/easybuilders/easybuild-easyconfigs/commit/25d4f92c85c557344625efc4997a4ce2215813e3

**Comment by boegel** [comment]
@vanzod I made that change because the user who requested `FastQ_Screen` reported a problem with it when it was using `GD` as a dep:

```
Perl module GD::Graph::bars not installed, skipping charts
```

So yes, I think this is relevant here as well.

**Comment by SethosII** [comment]
@boegel @vanzod I changed the dependency to GDGraph.

**Comment by vanzod** [comment]
Test report by @vanzod
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in this PR)
cermis - Linux debian 9.9, Intel(R) Xeon(R) CPU           X5670  @ 2.93GHz, Python 2.7.13
See https://gist.github.com/d9b26a4a1d47b8f26fd73cea93ac86b7 for a full test report.

**Comment by vanzod** [comment]
Going in, thanks @SethosII!

**Pull request merged**
