### PR TITLE
use Homebrew source mirror to auto-download sources for DB v18.1.25 and v18.1.32

### PR DESCRIPTION
**Pull request by boegel**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by boegel** [comment]
@boegelbot please test @ generoso
EB_ARGS="--force-download"

**Comment by boegel** [comment]
@boegelbot please test @ generoso
EB_ARGS="DB-18.1.32-GCCcore-9.3.0.eb DB-18.1.32-GCCcore-8.3.0.eb DB-18.1.32-GCCcore-8.2.0.eb"

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 4 out of 4 (4 easyconfigs in this PR)
node3404.kirlia.os - Linux centos linux 7.8.2003, x86_64, Intel(R) Xeon(R) Gold 6240 CPU @ 2.60GHz (cascadelake), Python 2.7.5
See https://gist.github.com/5fc03fb70a0143db35eb73d81be34a10 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 4 out of 4 (4 easyconfigs in this PR)
node3100.skitty.os - Linux centos linux 7.8.2003, x86_64, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz, Python 3.6.8
See https://gist.github.com/b7e698e745e5ff407e867ed1f3230a24 for a full test report.

**Comment by boegel** [comment]
@boegelbot please test @ generoso
EB_ARGS="--force-download DB-18.1.32-GCCcore-9.3.0.eb DB-18.1.32-GCCcore-8.3.0.eb DB-18.1.32-GCCcore-8.2.0.eb"

**Comment by boegel** [comment]
@boegelbot please test @ generoso
EB_ARGS="DB-18.1.32-GCCcore-9.3.0.eb DB-18.1.32-GCCcore-8.3.0.eb DB-18.1.32-GCCcore-8.2.0.eb --force-download "

**Comment by lexming** [comment]
Test report by @lexming
**SUCCESS**
Build succeeded for 4 out of 4 (4 easyconfigs in total)
node101.hydra.os - Linux centos linux 7.7.1908, x86_64, Intel(R) Xeon(R) CPU E5-2680 v2 @ 2.80GHz, Python 2.7.5
See https://gist.github.com/75f140c1361d20ef2bf4c2bbd2655a7c for a full test report.

**Comment by lexming** [comment]
Test report by @lexming
**SUCCESS**
Build succeeded for 4 out of 4 (4 easyconfigs in total)
node379.hydra.os - Linux centos linux 7.7.1908, x86_64, Intel(R) Xeon(R) Gold 6148 CPU @ 2.40GHz, Python 2.7.5
See https://gist.github.com/c870f7a69fb872576b90812c38114170 for a full test report.

**Review by lexming — APPROVED** [review]
LGTM

**Comment by lexming** [comment]
Going in, thanks @boegel !

**Pull request merged**
