### PR TITLE
{lang}[fosscuda/2020b] R v4.0.3

### PR DESCRIPTION
**Pull request by dithwick**
(created using `eb --new-pr`)

### CODE REVIEW

**Review by boegel — APPROVED** [review]
lgtm after visual review, test report coming up...

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
node3301.joltik.os - Linux centos linux 7.9.2009, x86_64, Intel(R) Xeon(R) Gold 6242 CPU @ 2.80GHz (cascadelake), Python 3.6.8
See https://gist.github.com/48f2c54cace776a1a66fd00f17f4d8a1 for a full test report.

**Comment by boegel** [comment]
Going in, thanks @dithwick!

**Comment by lexming** [comment]
Test report by @lexming
**SUCCESS**
Build succeeded for 5 out of 5 (1 easyconfigs in total)
node251.hydra.os - Linux centos linux 7.9.2009, x86_64, Intel(R) Xeon(R) CPU E5-2650 v4 @ 2.20GHz, Python 2.7.5
See https://gist.github.com/8baaf9ba2a1f3b258751b5195b5c2c53 for a full test report.

**Pull request merged**
