### PR TITLE
avoid that pygmo v2.18.0 installs stuff in Python installation directory + add custom sanity check paths to pygmo easyconfigs

### LINKED ISSUE #15631: pygmo tries to install stuff in Python install directory
When trying to install `pygmo` with EasyBuild configured with, it fails with:

```
-- Install configuration: "Release"
CMake Error at pygmo/plotting/cmake_install.cmake:54 (file):
  file cannot create directory:
  /software/Python/3.9.5-GCCcore-10.3.0/lib/python3.9/site-packages/pygmo/plotting.
  Maybe need administrative privileges.
```

Note that it's trying to create a directory in `$EBROOTPYTHON` here, it shouldn't...

cc @Louwrensth

### PR DESCRIPTION
**Pull request by boegel**
(created using `eb --new-pr`)
fixes #15631

### CODE REVIEW

**Comment by SebastianAchilles** [comment]
@boegelbot please test @ generoso

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in total)
node2608.swalot.os - Linux RHEL 8.4, x86_64, Intel(R) Xeon(R) CPU E5-2660 v3 @ 2.60GHz (haswell), Python 3.6.8
See https://gist.github.com/8d09650a0784fe0c937a6c06e1f42210 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in total)
node3101.skitty.os - Linux RHEL 8.4, x86_64, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz (skylake_avx512), Python 3.6.8
See https://gist.github.com/4572982372a8c309d5c0f7e2b08373d4 for a full test report.

**Comment by SebastianAchilles** [comment]
@boegelbot please test @ jsc-zen2

**Review by SebastianAchilles — APPROVED** [review]
lgtm

**Comment by SebastianAchilles** [comment]
Going in, thanks @boegel!

**Pull request merged**
