### PR TITLE
{math}[foss/2022a] biogeme v3.2.6 w/ Python 3.10.4

### PR DESCRIPTION
**Pull request by boegel**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by verdurin** [comment]
@boegel just confirming that this is a leaf package where multiple versions within a single toolchain is okay?

**Comment by verdurin** [comment]
Test report by @verdurin
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
easybuild-c7.novalocal - Linux CentOS Linux 7.9.2009, x86_64, Intel Xeon Processor (Skylake, IBRS), Python 3.6.8
See https://gist.github.com/77f9a3bf3fcd356a22f8b7e7df3c2dca for a full test report.

**Comment by verdurin** [comment]
@boegelbot please test @ generoso

**Comment by branfosj** [comment]
@boegelbot please test @ generoso

**Comment by branfosj** [comment]
Test report by @branfosj
**SUCCESS**
Build succeeded for 2 out of 2 (1 easyconfigs in total)
bear-pg0211u03a.bear.cluster - Linux Ubuntu 20.04.2 LTS (Focal Fossa), x86_64, Intel(R) Xeon(R) Gold 6248 CPU @ 2.50GHz (cascadelake), Python 3.8.5
See https://gist.github.com/3a665a86c33e2d0df370f01e0a26a4a6 for a full test report.

**Comment by branfosj** [comment]
Original generoso failure was caused by a missing OpenBLAS. This was caused by the rebuild for #16510.

```
Lmod has detected the following error: The following module(s) are unknown:
"OpenBLAS/0.3.20-GCC-11.3.0"
```

**Review by branfosj — APPROVED** [review]

**Comment by branfosj** [comment]
Going in, thanks @boegel!

**Pull request merged**
