### PR TITLE
{chem,tools}[GCCcore/13.3.0,foss/2024a] NAMD v3.0, tcsh v6.24.13 w/ mpi

### PR DESCRIPTION
**Pull request by maxim-masterov**
(created using `eb --new-pr`)

Depends on:
- namd.py easyblock from https://github.com/easybuilders/easybuild-easyblocks/pull/3494

### CODE REVIEW

**Comment by smoors** [comment]
@boegelbot please test @ jsc-zen3

**Comment by smoors** [comment]
>== 2024-11-06 08:11:03,872 filetools.py:834 WARNING URL https://www.ks.uiuc.edu/Research/namd/3.0/download/946183/NAMD_3.0_Source.tar.gz was not found (HTTP response code 404), not trying again

**Comment by maxim-masterov** [comment]
@smoors Can you try again? I added a new URL, but kept the old one.

**Comment by smoors** [comment]
@boegelbot please test @ jsc-zen3

**Comment by smoors** [comment]
@boegelbot: please test @ generoso

**Review by smoors — APPROVED** [review]
lgtm

**Comment by smoors** [comment]
Going in, thanks @maxim-masterov!

**Pull request merged**
