### PR TITLE
{toolchain}[system/system] gimkl v2020a

### PR DESCRIPTION
**Pull request by akesandgren**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by akesandgren** [comment]
Test report by @akesandgren
**SUCCESS**
Build succeeded for 4 out of 4 (4 easyconfigs in this PR)
skalman.hpc2n.umu.se - Linux ubuntu 18.04, Intel(R) Core(TM) i7-8565U CPU @ 1.80GHz, Python 2.7.17
See https://gist.github.com/d4f54f20a6b8d5616653118bd7772004 for a full test report.

**Comment by lexming** [comment]
Test report by @lexming
**SUCCESS**
Build succeeded for 4 out of 4 (4 easyconfigs in this PR)
login2.cerberus.os - Linux centos linux 7.7.1908, Intel(R) Xeon(R) Gold 6126 CPU @ 2.60GHz, Python 2.7.5
See https://gist.github.com/4dc9b3f882d20313d2c9648bc03f41ce for a full test report.

**Comment by zao** [comment]
Test report by @zao
**SUCCESS**
Build succeeded for 4 out of 4 (4 easyconfigs in this PR)
freja - Linux ubuntu 18.04, Intel(R) Core(TM) i7-8700K CPU @ 3.70GHz, Python 2.7.17
See https://gist.github.com/6e53385c2780a69f925478b82403bb9f for a full test report.

**Comment by zao** [comment]
Test report by @zao
**FAILED**
Build succeeded for 4 out of 5 (5 easyconfigs in this PR)
freja - Linux ubuntu 18.04, Intel(R) Core(TM) i7-8700K CPU @ 3.70GHz, Python 2.7.17
See https://gist.github.com/d4e69a061ed36abdb5a5645fc8301207 for a full test report.

**Comment by akesandgren** [comment]
Test report by @akesandgren
**SUCCESS**
Build succeeded for 5 out of 5 (5 easyconfigs in this PR)
b-an03.hpc2n.umu.se - Linux ubuntu 16.04, Intel(R) Xeon(R) CPU E5-2690 v4 @ 2.60GHz, Python 2.7.12
See https://gist.github.com/a7958db2c697c79820e23f72e6b473c8 for a full test report.

**Comment by bartoldeman** [comment]
Test report by @bartoldeman
**FAILED**
Build succeeded for 4 out of 5 (5 easyconfigs in this PR)
lg-1r17-n02 - Linux centos 6.6, Intel(R) Xeon(R) CPU E5-2650 0 @ 2.00GHz, Python 2.6.6
See https://gist.github.com/6218fd201671245602c17a9634eb7b70 for a full test report.

**Comment by bartoldeman** [comment]
The build complains about GOMP symbols but `-lgomp` is not specified:
```
mpicc -O2 -ftree-vectorize -march=native -fno-math-errno -L/localscratch/easybuild/software/imkl
/2020.0.166-gimpi-2020a/lib -L/localscratch/easybuild/software/imkl/2020.0.166-gimpi-2020a/lib -
L/localscratch/easybuild/software/imkl/2020.0.166-gimpi-2020a/mkl/lib/intel64 -L/localscratch/ea
sybuild/software/imkl/2020.0.166-gimpi-2020a/lib/intel64 -L/localscratch/easybuild/software/GCCc
ore/9.3.0/lib64 -L/localscratch/easybuild/software/GCCcore/9.3.0/lib -lm -lpthread -o /localscra
tch/easybuild/build/HPL/2.3/gimkl-2020a/hpl-2.3//bin/UNKNOWN/xhpl HPL_pddriver.o         HPL_pdi
nfo.o           HPL_pdtest.o /localscratch/easybuild/build/HPL/2.3/gimkl-2020a/hpl-2.3//lib/UNKN
OWN/libhpl.a  -Wl,--start-group -lmkl_gf_lp64 -lmkl_gnu_thread -lmkl_core -Wl,--end-group -lgfor
tran -lpthread 
/localscratch/easybuild/software/imkl/2020.0.166-gimpi-2020a/mkl/lib/intel64/libmkl_gnu_thread.so: error: undefined reference to 'GOMP_barrier'
```
I am not sure why it links ok for everyone else yet, will check tomorrow on a different system.

**Comment by migueldiascosta** [comment]
Test report by @migueldiascosta
**FAILED**
Build succeeded for 4 out of 5 (5 easyconfigs in this PR)
sms - Linux centos linux 7.6.1810, AMD EPYC 7601 32-Core Processor, Python 2.7.5
See https://gist.github.com/0ca6f3be44ab8219c55ef65497855483 for a full test report.

**Comment by akesandgren** [comment]
This works for me due to https://github.com/easybuilders/easybuild-easyblocks/pull/1471

**Comment by boegel** [comment]
@akesandgren Should we reopen this to target `develop`?

When we trash the `2020a` branch, this will be auto-closed...

**Comment by akesandgren** [comment]
I can close this and reopen yes.

**Pull request closed without merging**
