### PR TITLE
{lang}[system/system] Julia v1.5.1

### PR DESCRIPTION
**Pull request by dithwick**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by dithwick** [comment]
Sorry I just noticed pending PR for Julia 1.5.1 built from source. Should I withdraw this one?

**Comment by boegel** [comment]
> Sorry I just noticed pending PR for Julia 1.5.1 built from source. Should I withdraw this one?

@dithwick This may still be useful, for example to compare performance of our from-source build with binary installation.

**Comment by dithwick** [comment]
No worries, makes sense. Was that me that cancelled the tests (by adding the comment)?

**Comment by boegel** [comment]
> No worries, makes sense. Was that me that cancelled the tests (by adding the comment)?

No, I cancelled them to re-trigger them after https://github.com/easybuilders/easybuild-framework/pull/3427 got merged (easyconfigs PR testing was broken because of that bug)

**Review by boegel — APPROVED** [review]
lgtm

**Comment by boegel** [comment]
@boegelbot please test @ generoso

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
node3404.kirlia.os - Linux centos linux 7.8.2003, x86_64, Intel(R) Xeon(R) Gold 6240 CPU @ 2.60GHz (cascadelake), Python 2.7.5
See https://gist.github.com/57e70c23e97853c34ea888b1ce46a2a8 for a full test report.

**Comment by smoors** [comment]
Test report by @smoors
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
node254.hydra.os - Linux centos linux 7.7.1908, x86_64, Intel(R) Xeon(R) CPU E5-2683 v4 @ 2.10GHz (broadwell), Python 2.7.5
See https://gist.github.com/1e46da59c2ec6d663a16b6fa47f9f9b6 for a full test report.

**Comment by smoors** [comment]
Going in, thanks @dithwick!

**Pull request merged**
