### PR TITLE
{numlib}[foss/2020a] Hypre v2.18.2

### PR DESCRIPTION
**Pull request by MaximeMoge**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by akesandgren** [comment]
Test report by @akesandgren
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
b-an04.hpc2n.umu.se - Linux ubuntu 16.04, Intel(R) Xeon(R) CPU E5-2690 v4 @ 2.60GHz, Python 2.7.12
See https://gist.github.com/81662505ad97e79cc62498055158471b for a full test report.

**Comment by zao** [comment]
Test report by @zao
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
freja - Linux ubuntu 18.04, Intel(R) Core(TM) i7-8700K CPU @ 3.70GHz, Python 2.7.17
See https://gist.github.com/3f5a83d5b4107b4cd44baee276ac3697 for a full test report.

**Comment by akesandgren** [comment]
This one also builds its own BLAS. Why??

**Comment by MaximeMoge** [comment]
The path to OpenBLAS is passed correctly, but Hypre still builds its own blas/lapack.
It looks like a bug in Hypre.
I reported an issue on Hypre github

**Comment by MaximeMoge** [comment]
Hypre still build its internal blas/lapack but uses the external blas/lapack if specified (cf https://github.com/hypre-space/hypre/issues/41).
So there is no problem here.

**Comment by lexming** [comment]
Test report by @lexming
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
login2.cerberus.os - Linux centos linux 7.7.1908, Intel(R) Xeon(R) Gold 6126 CPU @ 2.60GHz, Python 2.7.5
See https://gist.github.com/b3f041672ef64230ce81677b74501f17 for a full test report.

**Comment by lexming** [comment]
Hypre seems to be completely hardcoded to link to internal BLAS and LAPACK during the whole build process, there is not a single reference to OpenBLAS from EB in the output of any `make` step. Looking at the `Makefiles`, the only case where the libraries provided by `--with-blas-libs` is in the final step of making the shared libraries, which this easyconfig is not using. However, static libs use the internal BLAS and LAPACK.

**Comment by lexming** [comment]
I can confirm this behaviour
* building Hypre with shared libraries does indeed use the libs passed through `--with-blas-libs`
* building the static libs use the internal BLAS and LAPACK in any case, no trace of using any of the libs from `configure`
This also fits the explanation given by the devs, saying that external BLAS and LAPACK are only being re-linked at the end of the build.

So I think that we have two options:
* move this easyconfig as it is to `gompi`, since the resulting static libs will be exactly the same
* stay in `foss` and add the shared libs to the build (this option needs an update of the hypre easyblock)

If you want to test the build with shared libs, configure command should be something like

> ./configure --prefix=/path/to/prefix/Hypre/2.18.2-foss-2020a --build=x86_64-pc-linux-gnu --host=x86_64-pc-linux-gnu --with-blas --with-lapack **--enable-shared** --with-MPI-include=$EBROOTOPENMPI/include  **--with-blas-libs="openblas gfortran"**  --with-blas-lib-dirs="$EBROOTOPENBLAS/lib"  **--with-lapack-libs="openblas gfortran"**  --with-lapack-lib-dirs="$EBROOTOPENBLAS/lib"

Attention that `--with-blas-libs` expects library references without preceding `-l`, lovely stuff.

**Comment by lexming** [comment]
I was wrong, the static libs of Hypre do use external BLAS/LAPACK as well.

As an example, this is the table in `libHYPRE.a` for `FGmres.o` where LAPACK symbols such as `daxpy` differ
* left: compiled removing `--with-blas-libs` and friends
* right: default compilation using this easyconfig in current EB
```
FGmres.o:                                                                       FGmres.o:
                                                                              >                  U daxpy_
                                                                              >                  U dcopy_
                                                                              >                  U ddot_
                                                                              >                  U dscal_
0000000000000070 T FGMRES_ParaSails                                             0000000000000070 T FGMRES_ParaSails
                 U free                                                                          U free
                 U _GLOBAL_OFFSET_TABLE_                                                         U _GLOBAL_OFFSET_TABLE_
                 U hypre_daxpy                                                <
                 U hypre_dcopy                                                <
                 U hypre_ddot                                                 <
                 U hypre_dscal                                                <
                 U hypre_MAlloc                                                                  U hypre_MAlloc
                 U hypre_MPI_Allreduce                                                           U hypre_MPI_Allreduce
                 U hypre_MPI_Comm_rank                                                           U hypre_MPI_Comm_rank
                 U hypre_printf                                                                  U hypre_printf
0000000000000000 t InnerProd                                                    0000000000000000 t InnerProd
0000000000000000 r .LC0                                                         0000000000000000 r .LC0
0000000000000008 r .LC2                                                         0000000000000008 r .LC2
0000000000000000 r .LC3                                                         0000000000000000 r .LC3
0000000000000010 r .LC4                                                         0000000000000010 r .LC4
0000000000000000 r .LC5                                                         0000000000000000 r .LC5
                 U MatrixMatvec                                                                  U MatrixMatvec
                 U ompi_mpi_double                                                               U ompi_mpi_double
                 U ompi_mpi_op_sum                                                               U ompi_mpi_op_sum
                 U ParaSailsApply                                                                U ParaSailsApply
```

So, this PR is good to go. Sorry for the noise.

**Comment by lexming** [comment]
Going in, thanks @MaximeMoge !

**Pull request merged**
