### PR TITLE
add missing Python build dep for SeqAn 2.4.0

### PR DESCRIPTION
**Pull request by boegel**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by boegel** [comment]
@boegelbot please test @ generoso
EB_ARGS="SeqAn-2.4.0-GCC-8.2.0-2.31.1.eb SeqAn-2.4.0-GCCcore-8.3.0.eb SeqAn-2.4.0-GCCcore-9.3.0.eb"

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 3 out of 3 (3 easyconfigs in total)
node3505.doduo.os - Linux RHEL 8.2, x86_64, AMD EPYC 7552 48-Core Processor (zen2), Python 3.6.8
See https://gist.github.com/1fdd119e919f7dbaf375c0fda7f7f8dd for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 3 out of 3 (3 easyconfigs in total)
node3505.doduo.os - Linux RHEL 8.2, x86_64, AMD EPYC 7552 48-Core Processor (zen2), Python 3.6.8
See https://gist.github.com/44600e7836d6f3cdbcf8925a3492b16d for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 6 out of 6 (5 easyconfigs in total)
node2693.swalot.os - Linux centos linux 7.9.2009, x86_64, Intel(R) Xeon(R) CPU E5-2660 v3 @ 2.60GHz (haswell), Python 3.6.8
See https://gist.github.com/a74415e880e6fcffa4d38460184b4c58 for a full test report.

**Review by Micket — APPROVED** [review]
lgtm

**Comment by Micket** [comment]
Test report by @Micket
**FAILED**
Build succeeded for 5 out of 7 (5 easyconfigs in total)
vera-c1 - Linux centos linux 7.9.2009, x86_64, Intel Xeon Processor (Skylake), Python 2.7.5
See https://gist.github.com/368b816e7152a14cd6ef0a72962856f6 for a full test report.

**Comment by boegel** [comment]
@Micket Test failed due to `No such file or directory: '/apps/c3se-easyconfigs/intel-2018b.eb'`, local temporary problem?

**Comment by Micket** [comment]
Yes, was cleaning up old stuff

**Comment by Micket** [comment]
Test report by @Micket
**SUCCESS**
Build succeeded for 6 out of 6 (5 easyconfigs in total)
vera-c1 - Linux centos linux 7.9.2009, x86_64, Intel Xeon Processor (Skylake), Python 2.7.5
See https://gist.github.com/a3397c90ab6c33c3ff024f00b00d2428 for a full test report.

**Comment by Micket** [comment]
Going in, thanks @boegel!

**Pull request merged**
