### PR TITLE
use GTK2 and GTK3 as dependencies rather than GTK+ for easyconfigs using GCC/10.3.0 toolchain

### PR DESCRIPTION
**Pull request by jfgrimm**
Update instances where GTK+ was used in the GCC 10.3.0 toolchain generation ECs to use GTK2 or GTK3 (requires #13893)

### CODE REVIEW

**Review by boegel — CHANGES_REQUESTED** [review]
@jfgrimm `GTK+-2.24.33-GCCcore-10.3.0.eb` was included in the EasyBuild v4.4.2 release, so we shouldn't remove that... Changing the `GIMP` dependency is fine though.

`GTK+-3.24.29-GCCcore-10.3.0.eb` can be removed, since that's not included with a release yet.

**Review by Micket — DISMISSED** [review]
lgtm (this was exactly the same changes as I was just preparing :+1:  )

**Comment by Micket** [comment]
@boegelbot please test @ generoso
CORE_CNT=16

**Comment by Micket** [comment]
Test report by @Micket
**SUCCESS**
Build succeeded for 3 out of 3 (3 easyconfigs in total)
alvis-c1 - Linux centos linux 7.9.2009, x86_64, Intel Xeon Processor (Skylake), Python 3.6.8
See https://gist.github.com/6dd052c5f6c4afe284f4157119aff926 for a full test report.

**Review by Micket — APPROVED** [review]
lgtm

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 4 out of 4 (4 easyconfigs in total)
node3129.skitty.os - Linux centos linux 7.9.2009, x86_64, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz, Python 3.6.8
See https://gist.github.com/6735294daa0c50c44a7e470bcc6cd5e8 for a full test report.

**Comment by Micket** [comment]
Test report by @Micket
**SUCCESS**
Build succeeded for 23 out of 23 (1 easyconfigs in total)
vera-c1 - Linux centos linux 7.9.2009, x86_64, Intel Xeon Processor (Skylake), Python 3.6.8
See https://gist.github.com/b812d5d90a4e2d0ed43fdf67371b2389 for a full test report.

**Comment by Micket** [comment]
Going in, thanks @jfgrimm!

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 6 out of 6 (4 easyconfigs in total)
node3570.doduo.os - Linux RHEL 8.2, x86_64, AMD EPYC 7552 48-Core Processor (zen2), Python 3.6.8
See https://gist.github.com/2174205df44c17960bba10eccefad286 for a full test report.

**Pull request merged**
