### PR TITLE
{lib}[foss/2017b,intel/2017b] ConnectomeWorkbench v1.3.2

### PR DESCRIPTION
**Pull request by vanzod**
Requires ~#8464~ (FTGL)

### CODE REVIEW

**Comment by vanzod** [comment]
Test report by @vanzod
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in this PR)
cermis - Linux debian 9.9, Intel(R) Xeon(R) CPU           X5670  @ 2.93GHz, Python 2.7.13
See https://gist.github.com/a979c53f71b72827cd10f196103df64f for a full test report.

**Comment by smoors** [comment]
closing and reopening to trigger travis

**Comment by smoors** [comment]
Test report by @smoors
**FAILED**
Build succeeded for 4 out of 5 (2 easyconfigs in this PR)
nic411 - Linux centos linux 7.5.1804, Intel(R) Xeon(R) Gold 6148 CPU @ 2.40GHz, Python 2.7.5
See https://gist.github.com/01675f7b1e03f1d3e01693b01efd2007 for a full test report.

**Comment by smoors** [comment]
@vanzod the foss version fails for me, problems with finding BLAS?:
```
../kloewe/dot/libdot.a(dot.c.o):dot.c:function dot_set_impl: error: undefined reference to 'sdot_avx'
../kloewe/dot/libdot.a(dot.c.o):dot.c:function dot_set_impl: error: undefined reference to 'ddot_avx'
../kloewe/dot/libdot.a(dot.c.o):dot.c:function dot_set_impl: error: undefined reference to 'dsdot_avx'
```

**Comment by vanzod** [comment]
@smoors Those functions are not part of BLAS. Their function prototypes are defined in `kloewe/dot/dot.h`. They are defined based on a set of include guards and added based on the processor architecture. I am wondering if there is something wrong in the architecture selection on Skylake.

**Comment by vanzod** [comment]
I tried to build it manually on a Skylake node but I could not replicate your issue.
@easybuilders/easybuild-easyconfigs-maintainers Could you please submit some more tests? Thanks!

**Comment by verdurin** [comment]
Test report by @verdurin
**FAILED**
Build succeeded for 4 out of 5 (2 easyconfigs in this PR)
rescomp2 - Linux centos linux 7.3.1611, Intel(R) Xeon(R) Gold 6126 CPU @ 2.60GHz, Python 2.7.5
See https://gist.github.com/17b4530d994b1e5b153070f13e3e468d for a full test report.

**Comment by verdurin** [comment]
This is the error, which looks like the same one above, again on a Skylake node:
```
[ 90%] Building CXX object GuiQt/CMakeFiles/GuiQt.dir/DisplayGroupAndTabItemTreeWidgetItem.cxx.o
cd /dev/shm/adamh/ConnectomeWorkbench/1.3.2/foss-2017b/workbench-1.3.2/src/GuiQt && /well/rescomp/eb/software/GCCcore/6.4.0/bin/g++  -DCARET_DOTFCN -DCARET_OS_LINUX -DHAVE_FREETYPE -DQT_CORE_LIB -DQT_NO_DEBUG -I/dev/shm/adamh/ConnectomeWorkbench/1.3.2/foss-2017b/workbench-1.3.2/src/kloewe/dot/src -I/well/rescomp/eb/software/Mesa/17.2.5-foss-2017b/include -I/well/rescomp/eb/software/zlib/1.2.11-GCCcore-6.4.0/include -isystem /well/rescomp/eb/software/Qt5/5.8.0-foss-2017b/include -isystem /well/rescomp/eb/software/Qt5/5.8.0-foss-2017b/include/QtCore -isystem /well/rescomp/eb/software/Qt5/5.8.0-foss-2017b/./mkspecs/linux-g++-64 -I/well/rescomp/eb/software/Qt5/5.8.0-foss-2017b/include/QtOpenGL -I/well/rescomp/eb/software/Qt5/5.8.0-foss-2017b/include/QtWidgets -I/well/rescomp/eb/software/Qt5/5.8.0-foss-2017b/include/QtGui -I/well/rescomp/eb/software/Qt5/5.8.0-foss-2017b/include/QtNetwork -I/dev/shm/adamh/ConnectomeWorkbench/1.3.2/foss-2017b/workbench-1.3.2/src/GuiQt -I/dev/shm/adamh/ConnectomeWorkbench/1.3.2/foss-2017b/workbench-1.3.2/src/Qwt -I/dev/shm/adamh/ConnectomeWorkbench/1.3.2/foss-2017b/workbench-1.3.2/src/Algorithms -I/dev/shm/adamh/ConnectomeWorkbench/1.3.2/foss-2017b/workbench-1.3.2/src/Annotations -I/dev/shm/adamh/ConnectomeWorkbench/1.3.2/foss-2017b/workbench-1.3.2/src/Brain -I/dev/shm/adamh/ConnectomeWorkbench/1.3.2/foss-2017b/workbench-1.3.2/src/Commands -I/dev/shm/adamh/ConnectomeWorkbench/1.3.2/foss-2017b/workbench-1.3.2/src/Charting -I/dev/shm/adamh/ConnectomeWorkbench/1.3.2/foss-2017b/workbench-1.3.2/src/FilesBase -I/dev/shm/adamh/ConnectomeWorkbench/1.3.2/foss-2017b/workbench-1.3.2/src/Files -I/dev/shm/adamh/ConnectomeWorkbench/1.3.2/foss-2017b/workbench-1.3.2/src/Cifti -I/dev/shm/adamh/ConnectomeWorkbench/1.3.2/foss-2017b/workbench-1.3.2/src/Gifti -I/dev/shm/adamh/ConnectomeWorkbench/1.3.2/foss-2017b/workbench-1.3.2/src/Graphics -I/dev/shm/adamh/ConnectomeWorkbench/1.3.2/foss-2017b/workbench-1.3.2/src/Nifti -I/dev/shm/adamh/ConnectomeWorkbench/1.3.2/foss-2017b/workbench-1.3.2/src/OSMesaDummy -I/dev/shm/adamh/ConnectomeWorkbench/1.3.2/foss-2017b/workbench-1.3.2/src/Operations -I/dev/shm/adamh/ConnectomeWorkbench/1.3.2/foss-2017b/workbench-1.3.2/src/OperationsBase -I/dev/shm/adamh/ConnectomeWorkbench/1.3.2/foss-2017b/workbench-1.3.2/src/Palette -I/dev/shm/adamh/ConnectomeWorkbench/1.3.2/foss-2017b/workbench-1.3.2/src/Scenes -I/dev/shm/adamh/ConnectomeWorkbench/1.3.2/foss-2017b/workbench-1.3.2/src/Xml -I/dev/shm/adamh/ConnectomeWorkbench/1.3.2/foss-2017b/workbench-1.3.2/src/Common  -fopenmp -O2 -ftree-vectorize -march=native -fno-math-errno -O3 -DNDEBUG -fPIC   -W -Wall -Werror=return-type -Werror=switch -Wunused-parameter -Wno-narrowing -Wno-unused-local-typedefs -fPIC -std=gnu++11 -o CMakeFiles/GuiQt.dir/DisplayGroupAndTabItemTreeWidgetItem.cxx.o -c /dev/shm/adamh/ConnectomeWorkbench/1.3.2/foss-2017b/workbench-1.3.2/src/GuiQt/DisplayGroupAndTabItemTreeWidgetItem.cxx
../kloewe/dot/libdot.a(dot.c.o):dot.c:function dot_set_impl: error: undefined reference to 'sdot_avx'
../kloewe/dot/libdot.a(dot.c.o):dot.c:function dot_set_impl: error: undefined reference to 'ddot_avx'
../kloewe/dot/libdot.a(dot.c.o):dot.c:function dot_set_impl: error: undefined reference to 'dsdot_avx'
collect2: error: ld returned 1 exit status
make[2]: *** [CommandLine/wb_command] Error 1
make[2]: Leaving directory `/dev/shm/adamh/ConnectomeWorkbench/1.3.2/foss-2017b/workbench-1.3.2/src'
make[1]: *** [CommandLine/CMakeFiles/wb_command.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
```

**Comment by wpoely86** [comment]
Test report by @wpoely86
**FAILED**
Build succeeded for 4 out of 5 (2 easyconfigs in this PR)
nic400 - Linux centos linux 7.5.1804, Intel(R) Xeon(R) Gold 6148 CPU @ 2.40GHz, Python 2.7.5
See https://gist.github.com/09c184fd8437a034fd5fc981b575fd7a for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**FAILED**
Build succeeded for 3 out of 4 (2 easyconfigs in this PR)
node2402.golett.os - Linux centos linux 7.6.1810, Intel(R) Xeon(R) CPU E5-2680 v3 @ 2.50GHz, Python 2.7.5
See https://gist.github.com/20b4ecef134aaa7c47712200311a656a for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 5 out of 5 (2 easyconfigs in this PR)
node2005.delcatty.os - Linux centos linux 7.6.1810, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.7.5
See https://gist.github.com/f77bf0f877057bcfdcd0e645efac7d87 for a full test report.

**Comment by vanzod** [comment]
Test report by @vanzod
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in this PR)
cermis - Linux debian 9.9, Intel(R) Xeon(R) CPU           X5670  @ 2.93GHz, Python 2.7.13
See https://gist.github.com/4269c476643091fb7155973ff2d2bd28 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in this PR)
node3109.skitty.os - Linux centos linux 7.6.1810, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz, Python 2.7.5
See https://gist.github.com/28724ff219dfbc7241d0c13b6590a57b for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in this PR)
node2419.golett.os - Linux centos linux 7.6.1810, Intel(R) Xeon(R) CPU E5-2680 v3 @ 2.50GHz, Python 2.7.5
See https://gist.github.com/f0eeb83133d1a1413fef739e07a7ca61 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**FAILED**
Build succeeded for 2 out of 3 (2 easyconfigs in this PR)
node2081.delcatty.os - Linux centos linux 7.6.1810, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.7.5
See https://gist.github.com/cfa067670953ec82d138cc514ae8201a for a full test report.

**Comment by wpoely86** [comment]
Test report by @wpoely86
**SUCCESS**
Build succeeded for 5 out of 5 (2 easyconfigs in this PR)
nic421 - Linux centos linux 7.5.1804, Intel(R) Xeon(R) Gold 6148 CPU @ 2.40GHz, Python 2.7.5
See https://gist.github.com/a92d76bb84d02b9118dfc50af02aa468 for a full test report.

**Comment by wpoely86** [comment]
Thanks @vanzod!

**Pull request merged**
