### PR TITLE
remove appending of `$__EGL_VENDOR_LIBRARY_DIRS` in recent Mesa easyconfigs, since Mesa easyblock now appends to it

### PR DESCRIPTION
**Pull request by lcniel**
(created using `eb --new-pr`)

Related to https://github.com/easybuilders/easybuild-easyblocks/pull/2985

### CODE REVIEW

**Comment by Micket** [comment]
For everyones information, @lcniel made these changes on my request as this improves EGL support using nvidia drivers from the OS.

**Comment by Micket** [comment]
Test report by @Micket
Using easyblocks from PR(s) https://github.com/easybuilders/easybuild-easyblocks/pull/2985
**SUCCESS**
Build succeeded for 6 out of 6 (6 easyconfigs in total)
vera-c1 - Linux Rocky Linux 8.7, x86_64, Intel Xeon Processor (Skylake), Python 3.6.8
See https://gist.github.com/Micket/d866ae9ac981e11e6337887e594506a5 for a full test report.

**Comment by Micket** [comment]
I think we would be ready to test this build on generoso and jcs-zen2 with
EB_ARGS="--include-easyblocks-from-pr 2985 Mesa-23.1.4-GCCcore-12.3.0.eb Mesa-22.2.4-GCCcore-12.2.0.eb Mesa-22.0.3-GCCcore-11.3.0.eb Mesa-21.1.7-GCCcore-11.2.0.eb Mesa-21.1.1-GCCcore-10.3.0.eb Mesa-20.2.1-GCCcore-10.2.0.eb"
If someone else consider this good to go.

**Comment by boegel** [comment]
@boegelbot please test @ generoso
EB_ARGS="--include-easyblocks-from-pr 2985"

**Review by boegel — APPROVED** [review]
lgtm

**Comment by boegel** [comment]
Test report by @boegel
Using easyblocks from PR(s) https://github.com/easybuilders/easybuild-easyblocks/pull/2985
**SUCCESS**
Build succeeded for 8 out of 8 (8 easyconfigs in total)
node3116.skitty.os - Linux RHEL 8.6, x86_64, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz (skylake_avx512), Python 3.6.8
See https://gist.github.com/boegel/2e9fee4de43b681a4b7a5246873492e9 for a full test report.

**Comment by boegel** [comment]
Going in, thanks @lcniel!

**Pull request merged**
