### PR TITLE
[goolfc-*] OpenCV *WITH* GPU support; more (REVIEW) needed

### PR DESCRIPTION
**Pull request by fgeorgatos**
Had finished this end of last year, it should be in working state;
I mostly supply it to avoid duplication of work by others, in case someone is interested.

### CODE REVIEW

**Comment by fgeorgatos** [comment]
the assumption here was that this shuold be followed up in a hackathon,
together with the other OpenCV effort. 
I recall it yielded at least one successful GPU build of OpenCV (ldd verified)

**Comment by thiell** [comment]
Hi,

Current OpenCV easyconfig still has WITH_CUDA=OFF, leading to lack of GPU support required by Torch OpenCV bindings:
```
CMake Warning at CMakeLists.txt:55 (MESSAGE):
  BUILD_CUDA is ON, but OpenCV CUDA interface wasn't found.  Won't build
  OpenCV-CUDA wrappers.
```
So FYI, if I take the OpenCV 3.1 easyconfig available and set:
```
configopts += '-DWITH_CUDA=ON -DWITH_CUBLAS=1 '
```
and add CUDA dep:
```
dependencies = [
   ...
    ('CUDA', '7.5.18', '', True),
```

Then it seems to work:
```
--   NVIDIA CUDA
--     Use CUFFT:                   YES
--     Use CUBLAS:                  YES
--     USE NVCUVID:                 NO
--     NVIDIA GPU arch:             20 21 30 35 37
--     NVIDIA PTX archs:            30
--     Use fast math:               NO
```
And torch-opencv is happy.

**Comment by boegel** [comment]
@thiell the OpenCV easyconfigs in this PR have `-DWITH_CUDA=ON`, and `CUDA` is a part of the toolchain in `goolfc`, so both are covered in this case, no?

**Comment by thiell** [comment]
@boegel I guess it is fine, though it may need a refresh (cuda 5). I didn't see this PR at first but still wanted to comment. It would be nice to have it merged. We have some renewest interest in OpenCV as being an optional dependency of ML software.

**Comment by fgeorgatos** [comment]
this has slipped through the cracks; it was done with much love back then,
and I thought it was alright when it was initially baked-off (at least 1 OpenCV in it). 
Then, if I recall there were ideas to touch it left and right, so I no longer know its current state.

**Comment by migueldiascosta** [comment]
@fgeorgatos, this PR is being closed for the following reason(s): inactive.
Please don't hesitate to reopen this PR or add a comment if you feel this contribution is still relevant.
For more information on our policy w.r.t. closing PRs, see https://easybuild.readthedocs.io/en/latest/Contributing.html#why-a-pull-request-may-be-closed-by-a-maintainer

**Pull request closed without merging**
