### PR TITLE
{astro}[GCCcore/8.2.0,foss/2019a] plc v3.0.1, astropy v2.0.14 w/ Python 2.7.15

### PR DESCRIPTION
**Pull request by jose-d**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by jose-d** [comment]
dedicated PR for easyconfig from #7774 .

**Comment by jose-d** [comment]
Test report by @jose-d
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in this PR)
koios1 - Linux centos linux 7.6.1810, Intel(R) Xeon(R) Gold 6130 CPU @ 2.10GHz, Python 2.7.5
See https://gist.github.com/877a1dee78bf49ac1ef3fd71970004d1 for a full test report.

**Comment by smoors** [comment]
Test report by @smoors
**SUCCESS**
Build succeeded for 3 out of 3 (2 easyconfigs in this PR)
nic422 - Linux centos linux 7.5.1804, Intel(R) Xeon(R) Gold 6148 CPU @ 2.40GHz, Python 2.7.5
See https://gist.github.com/bff522e7d51a5d2e9a8f826e211182e8 for a full test report.

**Comment by smoors** [comment]
Going in, thanks @jose-d!

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in this PR)
node3168.skitty.os - Linux centos linux 7.6.1810, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz, Python 2.7.5
See https://gist.github.com/35e3fd7db66b68230dcb09dc738bca69 for a full test report.

**Pull request merged**
