### PR TITLE
{tools}[fosscuda/2020b] cell2location v0.05-alpha, dill v0.3.3, Seaborn 0.10.0, ... w/ Python 3.8.6

### PR DESCRIPTION
**Pull request by deniskristak**
(created using `eb --new-pr`)

requires ~~#12446~~ (igraph  co) + ~~#12447~~ (PyMC3)

### CODE REVIEW

**Comment by deniskristak** [comment]
@boegel think previous 2 PRs connected to cell2location issue https://github.com/hpcugent/eb_inuits/issues/163 contain all required dependencies (thanks to which this PR's tests wont fail)

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 6 out of 6 (6 easyconfigs in total)
node3305.joltik.os - Linux centos linux 7.9.2009, x86_64, Intel(R) Xeon(R) Gold 6242 CPU @ 2.80GHz (cascadelake), Python 3.6.8
See https://gist.github.com/39b777dcc4cfbe01d750fae5b14b0cf5 for a full test report.

**Comment by boegel** [comment]
@boegelbot please test @ generoso

**Comment by boegel** [comment]
@boegelbot please test @ generoso

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 5 out of 5 (5 easyconfigs in total)
node3307.joltik.os - Linux centos linux 7.9.2009, x86_64, Intel(R) Xeon(R) Gold 6242 CPU @ 2.80GHz (cascadelake), Python 3.6.8
See https://gist.github.com/437e65439a070504a1acabfade56253f for a full test report.

**Comment by branfosj** [comment]
https://github.com/easybuilders/easybuild-framework/pull/3692 should fix
```
Traceback (most recent call last):
  File "test/easyconfigs/easyconfigs.py", line 990, in test_changed_files_pull_request
    self.check_python_packages(changed_ecs, added_ecs_filenames)
  File "test/easyconfigs/easyconfigs.py", line 802, in check_python_packages
    self.fail('\n'.join(failing_checks))
AssertionError: 'source_urls' should not be defined in exts_default_options when using the default value in cell2location-0.05-alpha-fosscuda-2020b.eb
```

**Review by boegel — APPROVED** [review]
lgtm

**Comment by boegel** [comment]
Going in, thanks @deniskristak!

**Pull request merged**
