### PR TITLE
{bio}[system/system] PAUP v4.0a168

### PR DESCRIPTION
**Pull request by tardigradus**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by tardigradus** [comment]
The package for the previous version (v4.0a166) is no longer available from the website.

**Comment by branfosj** [comment]
Test report by @branfosj
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
bber0501u03a.bb2.cluster - Linux RHEL 8.3, x86_64, Intel(R) Xeon(R) CPU E5-2690 v3 @ 2.60GHz (haswell), Python 3.6.8
See https://gist.github.com/056dc811a1a0c0752c02c5a6753638e4 for a full test report.

**Review by branfosj — APPROVED** [review]
lgtm

**Comment by branfosj** [comment]
Test report by @branfosj
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
bear-pg0211u03a.bear.cluster - Linux RHEL 8.3, x86_64, Intel(R) Xeon(R) Gold 6248 CPU @ 2.50GHz (cascadelake), Python 3.6.8
See https://gist.github.com/840197f3485da45025852b10b2cf68d4 for a full test report.

**Comment by branfosj** [comment]
@boegelbot please test @ generoso

**Comment by branfosj** [comment]
Going in, thanks @tardigradus!

**Pull request merged**
