### PR TITLE
{math} [GCC/6.4.0-2.28, iccifort/2018.1.163-GCC-6.4.0-2.28] SLATEC v4.1

### PR DESCRIPTION
**Pull request by SimonPinches**

### CODE REVIEW

**Comment by vanzod** [comment]
@SimonPinches The same software cannot be on both `GCCcore/6.4.0` and `intel/2018a` since the former is a sub-toolchain of the latter and this would create some obvious conflicts.
Since this library contains math routines, where performance and results might change depending on the compiler, and given that it does not seem to need anything at the `foss`/`intel` toolchain level, how about adding two easyconfig files for `GCC` and for `iccifort` instead?

**Comment by SimonPinches** [comment]
@vanzod I've made the changes you suggested to provide easyconfig files for `GCC` and for `iccifort` instead.  Please let me know if there are any other changes you'd like to see.

**Review by boegel — APPROVED** [review]
lgtm

**Comment by boegel** [comment]
Going in, thanks @SimonPinches!

**Pull request merged**
