### PR TITLE
{mpi}[GCC/10.3.0] MPICH v3.4.2

### PR DESCRIPTION
**Pull request by satishskamath**
(created using `eb --new-pr`)

### CODE REVIEW

**Review by Micket — CHANGES_REQUESTED** [review]
Update to version 3.4.2?

**Comment by satishskamath** [comment]
> Update to version 3.4.2?

Just updated the PR to 3.4.2 with commit 3e706cb1a006ece38415410dec392130d6d04f7f .

**Review by Micket — CHANGES_REQUESTED** [review]
This PR still contains the 3.3.2 version as well
You can use `:` to indicate removal of a file in a PR with `--new/update-pr` (it can also be combined with adding a new file)
```
eb --update-pr 13532  :MPICH-3.3.2-GCC-10.3.0.eb
```

**Comment by Micket** [comment]
Test report by @Micket
**FAILED**
Build succeeded for 0 out of 1 (1 easyconfigs in total)
alvis-c1 - Linux centos linux 7.9.2009, x86_64, Intel Xeon Processor (Skylake), Python 3.6.8
See https://gist.github.com/a8b2423aeb459621539fe4ba745650a4 for a full test report.

**Comment by satishskamath** [comment]
> Test report by @Micket
> **FAILED**
> Build succeeded for 0 out of 1 (1 easyconfigs in total)
> alvis-c1 - Linux centos linux 7.9.2009, x86_64, Intel Xeon Processor (Skylake), Python 3.6.8
> See https://gist.github.com/a8b2423aeb459621539fe4ba745650a4 for a full test report.

This is why the build failed:

https://github.com/pmodels/mpich/blob/main/CHANGES

# ch4 replaces ch3 as the default device configuration. If no network
  module is specified at configuration-time, MPICH will search the
  user environment in order to select one to build. The user will be
  prompted to choose if no preferred network library is detected.

So either: `--with-devices=ch4:ofi` or `--with-devices=ch4:ucx` has to be specified. Also if UCX is specified then shouldn't it be one of the dependencies within the easybuild config file?

**Comment by Micket** [comment]
Yes, UCX makes sense, and it should be added as a depencency as well

**Comment by satishskamath** [comment]
> Yes, UCX makes sense, and it should be added as a depencency as well

Build succeeds, even if I don't add UCX as a dependency. Is that weird?

**Comment by Micket** [comment]
No not very weird. It just means you accidentally used a OS installed variant of UCX that you happened to have installed.

It is unclear from their wording, but if we can enable both libfabric and UCX, we should probably do so, if not, then lets just go for UCX

**Comment by satishskamath** [comment]
> No not very weird. It just means you accidentally used a OS installed variant of UCX that you happened to have installed.
> 
> It is unclear from their wording, but if we can enable both libfabric and UCX, we should probably do so, if not, then lets just go for UCX

Wording is unclear to me as well, have added UCX as a dependency. Hoping for the best with the tests.

**Review by Micket — APPROVED** [review]
lgtm

**Comment by Micket** [comment]
Test report by @Micket
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
alvis-c1 - Linux centos linux 7.9.2009, x86_64, Intel Xeon Processor (Skylake), Python 3.6.8
See https://gist.github.com/62a97c183528d088678f991dce8ae787 for a full test report.

**Comment by Micket** [comment]
Going in, thanks @satishskamath!

**Comment by ocaisa** [comment]
For posterity, according to the `configure` script, you can't have `libfabric` and `UCX` support at the same time:
```
        if test $have_ucx = "yes" -a $have_libfabric = "no" ; then
        ch4_netmods=ucx
    elif test $have_ucx = "no" -a $have_libfabric = "yes" ; then
        ch4_netmods=ofi
    else
                as_fn_error $? "no ch4 netmod selected
```
(and testing showed this)

**Pull request merged**
