### PR TITLE
{vis}[foss/2019a,intel/2019a] Grace v5.1.25, motif v2.3.8

### PR DESCRIPTION
**Pull request by seb45tian**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by seb45tian** [comment]
Test report by @seb45tian
**SUCCESS**
Build succeeded for 4 out of 4 (4 easyconfigs in this PR)
r03n39.palma.wwu - Linux centos linux 7.7.1908, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz, Python 2.7.5
See https://gist.github.com/fd86598bd313832161209b210eafee43 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**FAILED**
Build succeeded for 2 out of 4 (4 easyconfigs in this PR)
generoso-1 - Linux centos linux 7.6.1810, Intel(R) Xeon(R) CPU E5-2660 v4 @ 2.00GHz, Python 3.6.8
See https://gist.github.com/e15c2a2faeb70f439b14182ab0c49fee for a full test report.

**Comment by lexming** [comment]
Test report by @lexming
**SUCCESS**
Build succeeded for 4 out of 4 (4 easyconfigs in this PR)
login2.cerberus.os - Linux centos linux 7.7.1908, Intel(R) Xeon(R) Gold 6126 CPU @ 2.60GHz, Python 2.7.5
See https://gist.github.com/c678ae10a1a7a335b83851f922b5fcf7 for a full test report.

**Comment by boegel** [comment]
Test report failed when using EasyBuild on top of Python 3.6.

I've opened a dedicated issue about this in https://github.com/easybuilders/easybuild-framework/issues/3190.

**Comment by boegel** [comment]
Problem fixed in https://github.com/easybuilders/easybuild-framework/pull/3191, which will be included in the next EasyBuild release.

Looking into new test reports now so we can go ahead and get this merged...

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 4 out of 4 (4 easyconfigs in this PR)
node3108.skitty.os - Linux centos linux 7.7.1908, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz, Python 3.6.8
See https://gist.github.com/fedb9bd7f837ebfd5b8e1823086c088a for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 4 out of 4 (4 easyconfigs in this PR)
generoso - Linux centos linux 7.6.1810, Intel(R) Xeon(R) CPU E5-2660 v4 @ 2.00GHz, Python 3.6.8
See https://gist.github.com/642b4aa0549c1a1ec38f82c4df02e854 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**FAILED**
Build succeeded for 0 out of 4 (4 easyconfigs in this PR)
node2314.phanpy.os - Linux centos linux 7.7.1908, Intel(R) Xeon(R) CPU E5-2680 v3 @ 2.50GHz, Python 2.7.5
See https://gist.github.com/029b15df7974f7d7edd06e1283457010 for a full test report.

**Comment by boegel** [comment]
Going in, thanks @seb45tian!

**Pull request merged**
