### PR TITLE
Skip NASA performance test in netCDF

### LINKED ISSUE #15959: test timeouts for netCDF 4.9.0
(I tried raising this by e-mailing easybuild-request@lists.ugent.be, but I received no responses.)  

I am getting a consistent build error when attempting to build netCDF-4.9.0-gompi-2022a.eb.  This is a dependency for the R 4.2.1 build.  I have tried this using both 10 CPUs and 20 CPUs on the build system, with the same result, which is a failure in the MPI tests.  I attach copies of the build logs.  Can anyone shed any light on what's going wrong here? 
[easybuild-FMwVd0.log](https://github.com/easybuilders/easybuild-easyconfigs/files/9249511/easybuild-FMwVd0.log)
[easybuild-netCDF-4.9.0-20220802.094732.cKaNQ.log](https://github.com/easybuilders/easybuild-easyconfigs/files/9249512/easybuild-netCDF-4.9.0-20220802.094732.cKaNQ.log)
[easybuild-netCDF-4.9.0-20220802.094732.cKaNQ_test_report.md](https://github.com/easybuilders/easybuild-easyconfigs/files/9249514/easybuild-netCDF-4.9.0-20220802.094732.cKaNQ_test_report.md)

### PR DESCRIPTION
**Pull request by Micket**
fixes #15959 
(hopefully!)

### CODE REVIEW

**Comment by Micket** [comment]
Test report by @Micket
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
alvis-c1 - Linux Rocky Linux 8.5, x86_64, Intel Xeon Processor (Skylake), Python 3.6.8
See https://gist.github.com/1abd25bd95c3d2149ac484d647d21de9 for a full test report.

**Comment by Micket** [comment]
@boegelbot please test @ generoso

**Comment by branfosj** [comment]
@boegelbot please test @ generoso

**Comment by Ghepardo** [comment]
Test report by @Ghepardo
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
rothhpc4-ezy.cluster.local - Linux CentOS Linux 7.9.2009, x86_64, Intel(R) Xeon(R) Gold 6130 CPU @ 2.10GHz, Python 2.7.5
See https://gist.github.com/3ea20c35b5affd939ba49fe7d96c9ba0 for a full test report.

**Review by branfosj — APPROVED** [review]
lgtm

**Comment by branfosj** [comment]
Test report by @branfosj
**FAILED**
Build succeeded for 0 out of 1 (1 easyconfigs in total)
bear-pg0105u36b.bear.cluster - Linux RHEL 8.6, x86_64, Intel(R) Xeon(R) Platinum 8360Y CPU @ 2.40GHz (icelake), Python 3.6.8
See https://gist.github.com/fe5cd700bc832a6636f8bc28d6161ccc for a full test report.

**Comment by branfosj** [comment]
Test report by @branfosj
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
bear-pg0211u03a.bear.cluster - Linux RHEL 8.6, x86_64, Intel(R) Xeon(R) Gold 6248 CPU @ 2.50GHz (cascadelake), Python 3.6.8
See https://gist.github.com/282d7fca5b63ddee996bb7abbea90c38 for a full test report.

**Comment by branfosj** [comment]
Going in, thanks @Micket!

**Pull request merged**
