### PR TITLE
{perf}[gompi/2023a] OSU-Micro-Benchmarks v7.2 w/ CUDA 12.1.1

### PR DESCRIPTION
**Pull request by Micket**
(created using `eb --new-pr`)

Getting compilation errors with nccl and osu microbenchmarks 7.1-1. Updating to 7.2 was the easiest option.

### CODE REVIEW

**Comment by Micket** [comment]
@boegelbot please test @ generoso

**Comment by Micket** [comment]
Test report by @Micket
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
alvis-c1 - Linux Rocky Linux 8.8, x86_64, Intel Xeon Processor (Skylake), Python 3.6.8
See https://gist.github.com/Micket/d2806f76c60090ebbfd5ce1f95f4f14a for a full test report.

**Comment by SebastianAchilles** [comment]
Test report by @sebastianachilles
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
skl-rockylinux-88 - Linux Rocky Linux 8.8, x86_64, Intel(R) Core(TM) i7-10700 CPU @ 2.90GHz (skylake), 1 x NVIDIA NVIDIA RTX A4000, 545.23.06, Python 3.6.8
See https://gist.github.com/SebastianAchilles/cf255e1d8870ea82cf78c20174dcae05 for a full test report.

**Review by SebastianAchilles — APPROVED** [review]
lgtm

**Comment by SebastianAchilles** [comment]
Going in, thanks @Micket!

**Pull request merged**
