### PR TITLE
{bio}[GCCcore/12.2.0] Hybpiper v2.1.6, DIAMOND v2.1.8, parallel v20230722, ...

### PR DESCRIPTION
**Pull request by PetrKralCZ**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by PetrKralCZ** [comment]
@boegelbot please test @ generoso

**Comment by PetrKralCZ** [comment]
Test report by @PetrKralCZ
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
node4003.donphan.os - Linux RHEL 8.6, x86_64, Intel(R) Xeon(R) Gold 6240 CPU @ 2.60GHz, 1 x NVIDIA NVIDIA A2, 530.30.02, Python 3.6.8
See https://gist.github.com/PetrKralCZ/8ae0768bdd0140167cfbbdcbf133e5bc for a full test report.

**Comment by casparvl** [comment]
@boegelbot please test @ jsc-zen2

**Review by casparvl — COMMENTED** [review]
EasyConfigs look good to me. Awaiting test build, if that succeeds, it can be merged.

**Comment by casparvl** [comment]
Test report by @casparvl
**SUCCESS**
Build succeeded for 13 out of 13 (4 easyconfigs in total)
tcn464.local.snellius.surf.nl - Linux RHEL 8.6, x86_64, AMD EPYC 7H12 64-Core Processor, Python 3.6.8
See https://gist.github.com/casparvl/0575563147bc12b690d00a5b9f728df2 for a full test report.

**Review by casparvl — APPROVED** [review]
Lgtm!

**Pull request merged**
