### PR TITLE
{chem}[intel/2017b] NBO v7.0

### PR DESCRIPTION
**Pull request by smoors**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by smoors** [comment]
Test report by @smoors
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
nic404 - Linux centos linux 7.5.1804, Intel(R) Xeon(R) Gold 6148 CPU @ 2.40GHz, Python 2.7.5
See https://gist.github.com/c69a2e2ba83de677d7926d0cfe9f49a9 for a full test report.

**Comment by vanzod** [comment]
Test report by @vanzod
**FAILED**
Build succeeded for 0 out of 1 (1 easyconfigs in this PR)
cermis - Linux debian 9.9, Intel(R) Xeon(R) CPU           X5670  @ 2.93GHz, Python 2.7.13
See https://gist.github.com/29fc9179493a89b62a8d4dd6cc1dcf34 for a full test report.

**Comment by boegel** [comment]
I don't have access to the source myself, but this looks OK, and there's a working test report, so good to go for me...

**Comment by boegel** [comment]
Going in, thanks @smoors!

**Pull request merged**
