### PR TITLE
{bio}[dummy/] Trimmomatic v0.38

### PR DESCRIPTION
**Pull request by boegel**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
node2562.golett.os - Linux centos linux 7.4.1708, Intel(R) Xeon(R) CPU E5-2680 v3 @ 2.50GHz, Python 2.7.5
See https://gist.github.com/0dcb0edda06dd98e790a1e4426ef4cd2 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
node2102.delcatty.os - Linux centos linux 7.4.1708, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.7.5
See https://gist.github.com/0c941a886bd37d0e502aa1facba3ef0e for a full test report.

**Comment by verdurin** [comment]
Test report by @verdurin
**SUCCESS**
Build succeeded for 2 out of 2 (1 easyconfigs in this PR)
dell.lan - Linux fedora 28, Intel(R) Core(TM) i7-4600U CPU @ 2.10GHz, Python 2.7.15
See https://gist.github.com/d6f308d2c1d119250866369310f0474f for a full test report.

**Comment by verdurin** [comment]
Test report by @verdurin
**SUCCESS**
Build succeeded for 0 out of 0 (1 easyconfigs in this PR)
dell.lan - Linux fedora 28, Intel(R) Core(TM) i7-4600U CPU @ 2.10GHz, Python 2.7.15
See https://gist.github.com/d319fa4704a146f93926c61667114316 for a full test report.

**Comment by verdurin** [comment]
Test report by @verdurin
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
dell.lan - Linux fedora 28, Intel(R) Core(TM) i7-4600U CPU @ 2.10GHz, Python 2.7.15
See https://gist.github.com/cb758ff4ef6f2306d6f90703e0e6df45 for a full test report.

**Comment by verdurin** [comment]
Going in, thanks @boegel!

**Pull request merged**
