### PR TITLE
Bazel (0.25.2, 0.26.1, 0.29.1, and 1.1.0) fix gettid nameclash with glibc 2.30

### PR DESCRIPTION
**Pull request by zemu-unile**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by Micket** [comment]
Do you know if this affects newer versions of Bazel as well?

**Review by Micket — APPROVED** [review]
lgtm

**Comment by Micket** [comment]
Test report by @Micket
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
alvis-c1 - Linux centos linux 7.9.2009, x86_64, Intel Xeon Processor (Skylake), Python 3.6.8
See https://gist.github.com/58f2aa46d3d7b8b646ede50286462ee1 for a full test report.

**Comment by boegel** [comment]
Also relevant for Bazel 0.29.1 (see https://github.com/bazelbuild/bazel/blob/0.29.1/third_party/grpc/src/core/lib/gpr/log_linux.cc#L43) and 1.1.0 (see https://github.com/bazelbuild/bazel/blob/1.1.0/third_party/grpc/src/core/lib/gpr/log_linux.cc#L43), not needed from Bazel 2.0.0 onwards (see https://github.com/bazelbuild/bazel/blob/2.0.0/third_party/grpc/src/core/lib/gpr/log_linux.cc#L43).

**Comment by Micket** [comment]
@zemu-unile would you mind adding the other versions to this PR as well and we can get them all fixed

**Comment by zemu-unile** [comment]
I Hope I did not miss anything.

**Comment by branfosj** [comment]
@boegelbot please test @ generoso

**Comment by branfosj** [comment]
Test report by @branfosj
**SUCCESS**
Build succeeded for 7 out of 7 (7 easyconfigs in total)
bear-pg0211u03a.bear.cluster - Linux RHEL 8.3, x86_64, Intel(R) Xeon(R) Gold 6248 CPU @ 2.50GHz (cascadelake), Python 3.6.8
See https://gist.github.com/00ca75d026eaf2241c208fd44589a0c4 for a full test report.

**Comment by branfosj** [comment]
Test report by @branfosj
**SUCCESS**
Build succeeded for 22 out of 22 (7 easyconfigs in total)
bear-pg0211u08b.bear.cluster - Linux Ubuntu 20.04, x86_64, Intel(R) Xeon(R) Gold 6248 CPU @ 2.50GHz (cascadelake), Python 3.8.5
See https://gist.github.com/b6be051a5f957f58e2874c3b1b8709a4 for a full test report.

**Comment by branfosj** [comment]
https://github.com/easybuilders/easybuild-easyconfigs/pull/14269#issuecomment-986018086 is 
```
$ ldd --version
ldd (GNU libc) 2.28
```

and https://github.com/easybuilders/easybuild-easyconfigs/pull/14269#issuecomment-986026071 is
```
$ ldd --version
ldd (Ubuntu GLIBC 2.31-0ubuntu9.2) 2.31
```

**Review by branfosj — APPROVED** [review]
lgtm

**Comment by branfosj** [comment]
Going in, thanks @zemu-unile!

**Pull request merged**
