### PR TITLE
{bio}[foss/2021a] deepTools v3.5.0 w/ Python 3.9.5

### PR DESCRIPTION
**Pull request by btlindert**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by lexming** [comment]
Test report by @lexming
**SUCCESS**
Build succeeded for 2 out of 2 (1 easyconfigs in total)
node300.hydra.os - Linux centos linux 7.9.2009, x86_64, Intel(R) Xeon(R) Gold 6148 CPU @ 2.40GHz, Python 2.7.5
See https://gist.github.com/72c0f422b7af3049817b7dd70f84457f for a full test report.

**Comment by lexming** [comment]
@boegelbot: please test @ generoso

**Comment by lexming** [comment]
Test report by @lexming
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
node300.hydra.os - Linux centos linux 7.9.2009, x86_64, Intel(R) Xeon(R) Gold 6148 CPU @ 2.40GHz, Python 2.7.5
See https://gist.github.com/220ae8be4dc7b39e906db0600c8bc83c for a full test report.

**Review by lexming — APPROVED** [review]
@btlindert thanks for this contribution. I made the following changes to be able to merge it:
* removed the `versionsuffix`: packages in 2021a toolchains and onwards do not need the suffix for Python
* used a dependency on pyBigWig instead of bundling it as an extension: since we already have an easyconfig for pyBigWig it is preferable to use it

I hope that you agree with these changes. If you have any comments or questions let me know.

LGTM

**Comment by lexming** [comment]
Going in, thanks @btlindert !

**Comment by btlindert** [comment]
@lexming, Thanks for the improvements, I'll consider them future PRs!

**Pull request merged**
