### PR TITLE
{bio}[gompi/2021b] UShER v0.5.0 w/ Python 3.9.6

### PR DESCRIPTION
**Pull request by sassy-crick**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by sassy-crick** [comment]
Requires:
- [ ] [tbb](https://github.com/easybuilders/easybuild-easyconfigs/pull/14304)
- [ ] [MAFFT](https://github.com/easybuilders/easybuild-easyconfigs/pull/14303)

**Comment by migueldiascosta** [comment]
@sassy-crick it sees you committed a new copy of `easyconfigs.py` at the top of the repo, it should be a change to `test/easyconfigs/easyconfigs.py` (otherwise, the changes look good to me)

**Comment by sassy-crick** [comment]
@migueldiascosta Thanks for your help. It does make more sense indeed. 
I am not sure if I made a mess of it as these two lines were also removed, but not by me:
```
  # Shasta requires spoa 3.x
            'spoa': [(r'3\.4\.0', [r'Shasta-0\.8\.0-'])],
```
From the commit message I saw I think @boegel done something here. I don't want accidentally introduce a bug!

**Comment by migueldiascosta** [comment]
@sassy-crick I suppose you started from a version of easyconfigs.py from before @boegel added those lines, so you are indeed inadvertently removing them here...

**Comment by sassy-crick** [comment]
@migueldiascosta yes, that is what happened. I thought it is better to ask what to do instead of making more of a mess. 
Thanks for helping here. 
However, I am lost why the checks are not working now. It looks like the lines @boegel added are the problem here but then I might be wrong. 
:-(

**Comment by migueldiascosta** [comment]
@sassy-crick https://github.com/sassy-crick/easybuild-easyconfigs/pull/7 should fix it

**Comment by migueldiascosta** [comment]
@boegelbot please test @ generoso

**Review by migueldiascosta — APPROVED** [review]
lgtm

**Comment by migueldiascosta** [comment]
Going in, thanks @sassy-crick!

**Pull request merged**
