### PR TITLE
{devel}[foss/2023a] Spark v3.5.1 w/ Java 17

### PR DESCRIPTION
**Pull request by laraPPr**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by laraPPr** [comment]
Test report by @laraPPr
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
node4013.donphan.os - Linux RHEL 8.8 (Ootpa), x86_64, Intel(R) Xeon(R) Gold 6240 CPU @ 2.60GHz, 1 x NVIDIA NVIDIA A2, 545.23.08, Python 3.11.3
See https://gist.github.com/laraPPr/402fa704c32b323bde79534fd07a096d for a full test report.

**Review by Micket — APPROVED** [review]
lgtm

**Comment by laraPPr** [comment]
@boegelbot please test @ generoso

**Comment by Micket** [comment]
Test report by @Micket
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
vera-skylake-build - Linux Rocky Linux 8.9, x86_64, Intel Xeon Processor (Skylake, IBRS, no TSX), Python 3.6.8
See https://gist.github.com/Micket/c6e944e4feae1d3e6424b00790e4df71 for a full test report.

**Comment by casparvl** [comment]
@boegelbot please test @ jsc-zen3

**Comment by casparvl** [comment]
Test report by @casparvl
**SUCCESS**
Build succeeded for 2 out of 2 (1 easyconfigs in total)
tcn1.local.snellius.surf.nl - Linux RHEL 8.6, x86_64, AMD EPYC 7H12 64-Core Processor, Python 3.6.8
See https://gist.github.com/casparvl/6217d1cfbf6514d79eeaa1e0a31860c6 for a full test report.

**Comment by Micket** [comment]
Going in, thanks @laraPPr!

**Pull request merged**
