### PR TITLE
add -fcommon to $CFLAGS for binutils 2.35 with GCCcore/10.2.0

### LINKED ISSUE #11988: "multiple definition" error in binutils-2.35-GCCcore-10.2.0.eb
I was trying to build `binutils-2.35-GCCcore-10.2.0.eb` and it was failing with
```
3524 /apps/easybuild/software/infer-skylake/binutils/2.35/bin/ld: ../libiberty/libiberty.a(concat.o): in function `concat_length':
3525 concat.c:(.text+0x0): multiple definition of `concat_length'; /apps/easybuild/software/infer-skylake/binutils/2.35/lib64/libiberty.a(concat.o):/dev/shm/jkrometi/build/binutils/2.35/system-system/binutils-2.35/libiberty/./concat.c:91: first defined here 
```
After debugging it with Kenneth Hoste (boegel), it appears that the issue was related to the default to `-fno-common` in gcc 10 (https://gcc.gnu.org/gcc-10/porting_to.html) and to our use of gcc/9.2 as our default gcc (rather than the CentOS default). We were able to get it to build successfully by adding the following to `binutils-2.35-GCCcore-10.2.0`:
```
# add -fcommon to $CFLAGS to avoid that build fails with "multiple definition" linking errors
prebuildopts = 'export CFLAGS="$CFLAGS -fcommon" && '
```

### PR DESCRIPTION
**Pull request by boegel**
(created using `eb --new-pr`)
fixes #11988

### CODE REVIEW

**Comment by boegel** [comment]
@boegelbot please test @ generoso

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
node2637.swalot.os - Linux centos linux 7.9.2009, x86_64, Intel(R) Xeon(R) CPU E5-2660 v3 @ 2.60GHz (haswell), Python 3.6.8
See https://gist.github.com/f482f656b4afc193422c2969c1579a1b for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
node3508.doduo.os - Linux RHEL 8.2, x86_64, AMD EPYC 7552 48-Core Processor (zen2), Python 3.6.8
See https://gist.github.com/630b86ca3f11c748f00fc69956d565ff for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
node3128.skitty.os - Linux centos linux 7.9.2009, x86_64, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz, Python 3.6.8
See https://gist.github.com/2c3e4667f612fd9a66280e8966820502 for a full test report.

**Comment by Flamefire** [comment]
just checked the GCC manual:
> This behavior is inconsistent with C++, and on many targets implies a speed and code size penalty on global variable references. It is mainly useful to enable legacy code to link without errors. 

So maybe we should check for other options? Checking the output in the log I see the following:
`libtool: link: gcc -W -Wall ... -fPIC -o .libs/as-new ... -L/dev/shm/easybuild-build/binutils/2.35/GCCcore-10.2.0/binutils-2.35/bfd/../libiberty/pic -liberty -lz ../libiberty/libiberty.a ...`

This looks suspicious: First the `-W` looks wrong (at least I'm not aware of it being valid) and second the use of a dynamic AND static liberty which likely is what leads to the problem.

So question: Is that something introduced by EB? A bug in binutils build?

**Comment by lexming** [comment]
Test report by @lexming
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
node379.hydra.os - Linux centos linux 7.9.2009, x86_64, Intel(R) Xeon(R) Gold 6148 CPU @ 2.40GHz, Python 2.7.5
See https://gist.github.com/a19a15c3f51d70281cbe5889882cbbee for a full test report.

**Comment by lexming** [comment]
Test report by @lexming
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
node104.hydra.os - Linux centos linux 7.9.2009, x86_64, Intel(R) Xeon(R) CPU E5-2680 v2 @ 2.80GHz, Python 2.7.5
See https://gist.github.com/1f30fd8c87895eed14a120812f3da24a for a full test report.

**Review by lexming — COMMENTED** [review]
@boegel what conditions trigger this issue? I cannot reproduce the error that this PR is fixing. `binutils` v2.35 builds just fine with `GCCcore/10.2.0` without `-fcommon` on my side. If that would be needed, I would expect `binutils` to always fail without it. I agree with @Flamefire, this does not seem to be the real cause of the reported issue.

Moreover, I can only see dynamic links to `libiberty` in my logs of `binutils` (`-liberty`) and not a single mention to `liberty.a`. So that can indeed explain the issues, but I did nothing special on my builds. I'm using the default easyconfigs.

**Comment by Flamefire** [comment]
@lexming Check your logs for `../libiberty/libiberty.a`, the library name is "iberty" which only with the `-l` options yields freedom. ;)

But still the issue stands: As we use an EB-build binutils and compiler to build the GCCcore binutils this issue should not occur or always occur. So something else is going on.
At least we should find out when and how to reproduce and where the duplicate symbols are coming from.

**Comment by Flamefire** [comment]
Superseded by https://github.com/easybuilders/easybuild-easyblocks/pull/2323 I'd say :)

**Comment by boegel** [comment]
Closing this, https://github.com/easybuilders/easybuild-easyblocks/pull/2323 is a much better fix, thanks @Flamefire!

**Pull request closed without merging**
