### PR TITLE
{vis}[fosscuda/2018b] gnuplot v5.2.6

### PR DESCRIPTION
**Pull request by akesandgren**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by akesandgren** [comment]
Test report by @akesandgren
**SUCCESS**
Build succeeded for 3 out of 3 (3 easyconfigs in this PR)
b-an03.hpc2n.umu.se - Linux ubuntu 16.04, Intel(R) Xeon(R) CPU E5-2690 v4 @ 2.60GHz, Python 2.7.12
See https://gist.github.com/83571f8ca7c133bfde7ad0555afb512c for a full test report.

**Comment by vanzod** [comment]
Test report by @vanzod
**FAILED**
Build succeeded for 5 out of 7 (3 easyconfigs in this PR)
cermis - Linux debian 9.9, Intel(R) Xeon(R) CPU           X5670  @ 2.93GHz, Python 2.7.13
See https://gist.github.com/993c3b03b773a0ee8b83f06e42075607 for a full test report.

**Comment by boegel** [comment]
@vanzod Download issue for `http://apps.jcns.fz-juelich.de/src/libcerf/old/libcerf-1.7.tgz`?

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 11 out of 11 (3 easyconfigs in this PR)
node2427.golett.os - Linux centos linux 7.6.1810, Intel(R) Xeon(R) CPU E5-2680 v3 @ 2.50GHz, Python 2.7.5
See https://gist.github.com/84a9ab4f2332cc0f6c79bb617ab35d2f for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 10 out of 10 (3 easyconfigs in this PR)
node3120.skitty.os - Linux centos linux 7.6.1810, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz, Python 2.7.5
See https://gist.github.com/c9a048b880823342ba824bd5781d8b9f for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 3 out of 3 (3 easyconfigs in this PR)
node2028.delcatty.os - Linux centos linux 7.6.1810, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.7.5
See https://gist.github.com/45d04e7cb43fe1aa41b00cb5b4b534e1 for a full test report.

**Comment by boegel** [comment]
@vanzod Issue with `libcerf` fixed in #8243

**Comment by boegel** [comment]
Going in, thanks @akesandgren!

**Pull request merged**
