### PR TITLE
{vis}[gfbf/2023b] imageio v2.34.1

### PR DESCRIPTION
**Pull request by tanmoy1989**
(created using `eb --new-pr`)

### CODE REVIEW

**Review by kErica — APPROVED** [review]
This PR should be labelled with 'update'

**Comment by verdurin** [comment]
@boegelbot please test @ generoso

**Comment by verdurin** [comment]
Test report by @verdurin
**SUCCESS**
Build succeeded for 54 out of 54 (1 easyconfigs in total)
easybuild-el8.cloud.in.bmrc.ox.ac.uk - Linux Rocky Linux 8.10, x86_64, Intel Xeon Processor (Skylake, IBRS), Python 3.6.8
See https://gist.github.com/verdurin/823f0084a96d868ac0d5067d314c5ed7 for a full test report.

**Comment by bedroge** [comment]
@boegelbot please test @ jsc-zen3

**Review by verdurin — APPROVED** [review]
Looks fine.

**Comment by verdurin** [comment]
Going in, thanks @tanmoy1989!

**Pull request merged**
