### PR TITLE
fix permissions for TRF

### PR DESCRIPTION
**Pull request by smoors**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by smoors** [comment]
Test report by @smoors
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
node360.hydra.os - Linux centos linux 7.6.1810, Intel(R) Xeon(R) Gold 6148 CPU @ 2.40GHz, Python 2.7.5
See https://gist.github.com/51b4e083e850d244a36b213cc75a31f8 for a full test report.

**Comment by migueldiascosta** [comment]
Test report by @migueldiascosta
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
generoso - Linux centos linux 7.6.1810, Intel(R) Xeon(R) CPU E5-2660 v4 @ 2.00GHz, Python 3.6.8
See https://gist.github.com/4a714ee2b300c58a46616a2c609ac25d for a full test report.

**Comment by migueldiascosta** [comment]
@smoors what about adding something like

```python
sanity_check_commands = ["trf --help 2>&1 | grep 'Please use: trf File'"]
```

(`trf --help` alone won't work because it returns a non-zero exit status)

**Comment by boegel** [comment]
+1 on the custom sanity check command (and you can drop `--help` if it's not a known option, just `trf | grep ...` is fine I think)

**Comment by smoors** [comment]
good idea, might as well do a real test.

**Comment by smoors** [comment]
Test report by @smoors
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
node320.hydra.os - Linux centos linux 7.6.1810, Intel(R) Xeon(R) Gold 6148 CPU @ 2.40GHz, Python 2.7.5
See https://gist.github.com/394b9137e7791d62c1355a49c8ddd21f for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
node2065.delcatty.os - Linux centos linux 7.6.1810, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.7.5
See https://gist.github.com/4c2b329373d4358f2cfa972b1ee8aea5 for a full test report.

**Comment by boegel** [comment]
Going in, thanks @smoors!

**Pull request merged**
