### PR TITLE
{data}[GCCcore/6.4.0] ](Yahoo) MDBM v4.13.0 {REVIEW}

### PR DESCRIPTION
**Pull request by SimonPinches**

### CODE REVIEW

**Comment by migueldiascosta** [comment]
@SimonPinches why not a more recent toolchain?

**Comment by smoors** [comment]
Test report by @smoors
**SUCCESS**
Build succeeded for 2 out of 2 (1 easyconfigs in this PR)
node321.hydra.os - Linux centos linux 7.6.1810, Intel(R) Xeon(R) Gold 6148 CPU @ 2.40GHz, Python 2.7.5
See https://gist.github.com/d9d7e7f0bcba919977bf8742a3e21895 for a full test report.

**Comment by smoors** [comment]
I agree with @migueldiascosta that we prefer more recent toolchains, but that should not prevent people to contribute easyconfigs with older toolchains.

**Review by smoors — APPROVED** [review]
lgtm

**Comment by smoors** [comment]
Going in, thanks @SimonPinches!

**Pull request merged**
