### PR TITLE
{bio}[foss/2021a] pftoolsV3 v3.2.11

### PR DESCRIPTION
**Pull request by SIB-software**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by SebastianAchilles** [comment]
@boegelbot please test @ generoso

**Comment by smoors** [comment]
Test report by @smoors
**FAILED**
Build succeeded for 1 out of 2 (1 easyconfigs in total)
node367.hydra.os - Linux centos linux 7.9.2009, x86_64, Intel(R) Xeon(R) Gold 6148 CPU @ 2.40GHz (skylake_avx512), Python 2.7.5
See https://gist.github.com/ee7dfd73cd13595f62d7aa31003bc455 for a full test report.

**Comment by smoors** [comment]
@SIB-software any idea what's causing the 3 failing tests?

**Comment by smoretti** [comment]
I will look at that.

At SIB we host the pftoolsV3 source code. I will disable the CPU affinity and commit the changes to see if tests pass.

**Comment by smoretti** [comment]
@smoors I have disabled CPU affinity for tests. Let's see if this fixes the problem.

**Comment by smoors** [comment]
@smoretti you changed the code in-place??? that's like swearing in the church :)
can you please create a new tag instead?

**Comment by smoretti** [comment]
@smoors You mean a new pftools version?
The pftools code itself has not changed. Only tests for V3 tools use the --no-affinity option now.

We have issues with affinity on some clusters/clouds.

In the end, users can use or not the --no-affinity option.

**Comment by smoretti** [comment]
In fact I have updated the v3.2.8 tag with the changes in tests

**Comment by smoors** [comment]
@boegelbot: please test @ generoso

**Comment by smoors** [comment]
@smoretti the new test failed *exactly* because you updated the tag in-place.
the sources were already downloaded before, with exactly the same name, so EB thinks it does not have to re-download them, checks the checksum and of course that fails because the checksum changed.

that's what I mean. even if you only made changes to the test, the sources as a whole have changed so you should create a new tag.

**Comment by smoors** [comment]
alternatively, if you don't want to create a tag yet, you could update the PR and provide a commit id as the source

**Comment by smoretti** [comment]
@smoors I have updated the tag, and retesting.

The name of the EB file (and the PR) will be different...

**Comment by smoors** [comment]
@smoretti thanks for doing this!

I've removed the stale version.
next time, if you want to do this yourself, the following command should work if you have github integration for EB setup (colon in front means remove):
`eb --update-pr 14057 --pr-commit-msg "remove stale easyconfig"  pftoolsV3-3.2.9-foss-2021a.eb :pftoolsV3-3.2.8-foss-2021a.eb`

**Comment by smoors** [comment]
@boegelbot: please test @ generoso

**Comment by smoretti** [comment]
So the --no-affinity option does not fix the issue.

I have to dig more into that. The main problem being I cannot reproduce the problem locally, and some pftoolsV3 users have the problem...

**Comment by smoretti** [comment]
@smoors I have removed the --no-affinity option, and compile now with affinity disabled.

Could you run the tests to see if this fixes the issue?

**Comment by smoors** [comment]
@boegelbot: please test @ generoso

**Comment by smoretti** [comment]
Ahhh! I don't see what could be the cause now.

Do you want I upload a test report from our build machine?

**Comment by smoors** [comment]
Test report by @smoors
**SUCCESS**
Build succeeded for 2 out of 2 (1 easyconfigs in total)
node300.hydra.os - Linux centos linux 7.9.2009, x86_64, Intel(R) Xeon(R) Gold 6148 CPU @ 2.40GHz (skylake_avx512), Python 2.7.5
See https://gist.github.com/0909459713ada22e90bea98f41ec0c2d for a full test report.

**Comment by smoors** [comment]
sure, I'll do the same, but we need a solution for the test server too.

**Comment by smoors** [comment]
at least disabling the affinity works on my machine (skylake)

**Comment by smoretti** [comment]
It looks to work better on recent CPUs

**Comment by smoors** [comment]
Test report by @smoors
**SUCCESS**
Build succeeded for 2 out of 2 (1 easyconfigs in total)
node200.hydra.os - Linux centos linux 7.9.2009, x86_64, Intel(R) Xeon(R) CPU E5-2680 v4 @ 2.40GHz (broadwell), Python 2.7.5
See https://gist.github.com/95d9387f06e5f7cc93ac3750557e7c53 for a full test report.

**Comment by smoors** [comment]
Test report by @smoors
**SUCCESS**
Build succeeded for 2 out of 2 (1 easyconfigs in total)
node100.hydra.os - Linux centos linux 7.9.2009, x86_64, Intel(R) Xeon(R) CPU E5-2680 v2 @ 2.80GHz (ivybridge), Python 2.7.5
See https://gist.github.com/1acfc0dd6b20465a45157c2a63dcec0e for a full test report.

**Comment by smoors** [comment]
@smoretti the test succeeds on skylake, broadwell, and ivybridge for me.
could it be related to the fact that the failing build is on Rocky Linux?

**Comment by smoretti** [comment]
@smoors I never used Rocky Linux. I don't know if there are some specificity, but it looks to be a C library issue.

**Comment by smoretti** [comment]
I can reproduce the error in a Docker container, but what does the error mean???

**Comment by SebastianAchilles** [comment]
@boegelbot please test @ generoso

**Comment by smoretti** [comment]
@SebastianAchilles with Rocky Linux 8 it looks to fail on "old" machines only when affinity is off

**Comment by smoretti** [comment]
@smoors @SebastianAchilles Hopefully the affinity issue when sets to OFF should be fixed.

Could you restart test reports?

**Comment by smoors** [comment]
@boegelbot: please test @ generoso

**Comment by SebastianAchilles** [comment]
Test report by @sebastianachilles
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
jsfc01.int.jusuf.sebastian.cluster - Linux rocky linux 8.4, x86_64, AMD EPYC 7742 64-Core Processor (zen2), 1 x NVIDIA GRID V100-4C, 460.73.01, Python 3.6.8
See https://gist.github.com/dd925d977a571981f55989d98a42e232 for a full test report.

**Comment by SebastianAchilles** [comment]
Test report by @sebastianachilles
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
rocky8-eb - Linux rocky linux 8.4, x86_64, Intel(R) Core(TM) i7-6900K CPU @ 3.20GHz (broadwell), Python 3.6.8
See https://gist.github.com/7a052440ec1b8ae2986126de667b7092 for a full test report.

**Comment by smoretti** [comment]
Hi
what's next to complete the PR?

**Comment by smoors** [comment]
Test report by @smoors
**SUCCESS**
Build succeeded for 2 out of 2 (1 easyconfigs in total)
node300.hydra.os - Linux CentOS Linux 7.9.2009, x86_64, Intel(R) Xeon(R) Gold 6148 CPU @ 2.40GHz (skylake_avx512), Python 2.7.5
See https://gist.github.com/68273f1b805a1f35796348bdc6b76183 for a full test report.

**Review by smoors — APPROVED** [review]
lgtm

**Comment by smoors** [comment]
Going in, thanks @SIB-software!

**Pull request merged**
