### PR TITLE
Add missing rgdal dep to R-INLA

### PR DESCRIPTION
**Pull request by verdurin**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by verdurin** [comment]
@boegelbot please test @ generoso

**Comment by verdurin** [comment]
Test report by @verdurin
**SUCCESS**
Build succeeded for 5 out of 5 (1 easyconfigs in total)
easybuild-c7.novalocal - Linux centos linux 7.9.2009, x86_64, Intel Xeon Processor (Skylake, IBRS), Python 3.6.8
See https://gist.github.com/08fd7ce2a1cc21948d0b7445e4a1a13a for a full test report.

**Comment by boegel** [comment]
Ouch, I wonder how this was overlooked earlier...

@verdurin Is there a sanity check command we can add to catch this?

**Comment by verdurin** [comment]
@boegel As Simon has noted, the dependency is in `Suggests` rather than `Depends`, but in reality that distinction doesn't always hold as you would want it to.

I can see the script that caused the error. It's pretty involved, though, and it's not immediately clear to me where the error occurs. It does use `INLA` in conjunction with `geoR`.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
node2612.swalot.os - Linux centos linux 7.9.2009, x86_64, Intel(R) Xeon(R) CPU E5-2660 v3 @ 2.60GHz (haswell), Python 3.6.8
See https://gist.github.com/5db1684af2159b6c642b612836e31609 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
node3510.doduo.os - Linux RHEL 8.2, x86_64, AMD EPYC 7552 48-Core Processor (zen2), Python 3.6.8
See https://gist.github.com/d03785abe2902ff20dae24ca265deec3 for a full test report.

**Review by boegel — APPROVED** [review]

**Comment by boegel** [comment]
Going in, thanks @verdurin!

**Pull request merged**
