### PR TITLE
specify source_urls inside exts_default_options to ensure correct name expansion for the archived packages

### LINKED ISSUE #17829: Matrix extension fails to load for Seurat
`Matrix` `1.5-1` is now in the Archive, and there needs to be a URL specific for it in the Archive, not for the main enclosing package i.e. `Seurat`.

### PR DESCRIPTION
**Pull request by branfosj**
(created using `eb --new-pr`)

closes #17829

### CODE REVIEW

**Comment by branfosj** [comment]
Test report by @branfosj
**SUCCESS**
Build succeeded for 5 out of 5 (5 easyconfigs in total)
bb-pg-login02.bb2.cluster - Linux RHEL 8.6, x86_64, Intel(R) Xeon(R) CPU E5-2620 v4 @ 2.10GHz (broadwell), Python 3.6.8
See https://gist.github.com/branfosj/8137ef8e98c02342ba5076b0fe4a2bdb for a full test report.

**Comment by verdurin** [comment]
Test report by @verdurin
**SUCCESS**
Build succeeded for 5 out of 5 (5 easyconfigs in total)
easybuild-c7.novalocal - Linux CentOS Linux 7.9.2009, x86_64, Intel Xeon Processor (Skylake, IBRS), Python 3.6.8
See https://gist.github.com/verdurin/ed201dcb4469cb0fb3471f2e216c761a for a full test report.

**Comment by verdurin** [comment]
@boegelbot please test @ generoso

**Comment by jfgrimm** [comment]
@boegelbot please test @ jsc-zen2

**Review by jfgrimm — APPROVED** [review]
lgtm

**Pull request merged**
