### PR TITLE
{math}[foss/2021.07] ELPA v2021.05.001

### PR DESCRIPTION
**Pull request by SebastianAchilles**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by SebastianAchilles** [comment]
@boegelbot please test @ generoso

**Review by Micket — APPROVED** [review]
lgtm

**Comment by Micket** [comment]
Test report by @Micket
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
vera-c1 - Linux centos linux 7.9.2009, x86_64, Intel Xeon Processor (Skylake), Python 3.6.8
See https://gist.github.com/04ddcf948f8a0f89e67f3c6bcbc78cb7 for a full test report.

**Comment by Micket** [comment]
Going in, thanks @SebastianAchilles!

**Pull request merged**
