### PR TITLE
{vis}[foss/2017b] gnuplot v5.2.2

### PR DESCRIPTION
**Pull request by Helios07**
(created using `eb --new-pr`)
Depends on ~~#5402~~

### CODE REVIEW

**Comment by boegel** [comment]
Test report by @boegel
**FAILED**
Build succeeded for 2 out of 3 (1 easyconfigs in this PR)
node2457.golett.os - Linux centos linux 7.4.1708, Intel(R) Xeon(R) CPU E5-2680 v3 @ 2.50GHz, Python 2.7.5
See https://gist.github.com/d1f3ac257b609512c6513b8b4ed4e3b4 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**FAILED**
Build succeeded for 0 out of 1 (1 easyconfigs in this PR)
node2011.delcatty.os - Linux centos linux 7.4.1708, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.7.5
See https://gist.github.com/0d1b236ad641638f8745ca1b3e6bddae for a full test report.

**Comment by boegel** [comment]
@Helios07 Hmm, didn't you run into this? Can we fix (or disable) this?

```
Making install in LaTeX
make[2]: Entering directory `/tmp/vsc40023/easybuild_build/gnuplot/5.2.2/foss-2017b/gnuplot-5.2.2/share/LaTeX'
make[3]: Entering directory `/tmp/vsc40023/easybuild_build/gnuplot/5.2.2/foss-2017b/gnuplot-5.2.2/share/LaTeX'
make[3]: Nothing to be done for `install-exec-am'.
 /usr/bin/mkdir -p '/usr/share/texlive/texmf-local///tex/latex/gnuplot'
/usr/bin/mkdir: cannot create directory ‘/usr/share/texlive/texmf-local///tex’: Permission denied
```

**Comment by Helios07** [comment]
I could reproduce this behavior on a system with texlive installed. I will search for a solution

**Comment by boegel** [comment]
Test report by @boegel
**FAILED**
Build succeeded for 0 out of 1 (1 easyconfigs in this PR)
node2548.golett.os - Linux centos linux 7.4.1708, Intel(R) Xeon(R) CPU E5-2680 v3 @ 2.50GHz, Python 2.7.5
See https://gist.github.com/9b3102184ebb23fe4d0c49ead46ad84b for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
node2548.golett.os - Linux centos linux 7.4.1708, Intel(R) Xeon(R) CPU E5-2680 v3 @ 2.50GHz, Python 2.7.5
See https://gist.github.com/98c26e6fdfd8a851f10e76f057c3b2de for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
gligar03.gligar.os - Linux centos linux 7.4.1708, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.7.5
See https://gist.github.com/dc8b1981af66feff2fb857d66b7e5ddd for a full test report.

**Comment by boegel** [comment]
Going in, thanks @Helios07!

**Pull request merged**
