### PR TITLE
{lib}[GCCcore/11.2.0] libedit v20210910

### PR DESCRIPTION
**Pull request by nicholascheng94**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by nicholascheng94** [comment]
Test report by @nicholascheng94
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
c2dhpc - Linux CentOS Linux 7.6.1810, x86_64, AMD EPYC 7601 32-Core Processor, Python 2.7.5
See https://gist.github.com/6fd0bc8fe121a63513e4026537aa09a3 for a full test report.

**Comment by nicholascheng94** [comment]
Test report by @nicholascheng94
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
c2dhpc - Linux CentOS Linux 7.6.1810, x86_64, AMD EPYC 7601 32-Core Processor, Python 2.7.5
See https://gist.github.com/f8a10aebd1dfffd0a146ed8b3ff2f7c6 for a full test report.

**Comment by migueldiascosta** [comment]
@boegelbot please test @ generoso

**Review by migueldiascosta — APPROVED** [review]
lgtm

**Comment by migueldiascosta** [comment]
Going in, thanks @nicholascheng94!

**Pull request merged**
