### PR TITLE
{chem}[intel/2018b] CP2K v6.1

### PR DESCRIPTION
**Pull request by boegel**
(created using `eb --new-pr`)
requires #7437 (libxsmm, PLUMED, Libint)

### CODE REVIEW

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
node2447.golett.os - Linux centos linux 7.6.1810, Intel(R) Xeon(R) CPU E5-2680 v3 @ 2.50GHz, Python 2.7.5
See https://gist.github.com/c45342bedc7d75e30e0596b3a7243929 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
node3100.skitty.os - Linux centos linux 7.6.1810, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz, Python 2.7.5
See https://gist.github.com/88205a2f549c8d6c294939ec7a9b06df for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
node2001.delcatty.os - Linux centos linux 7.6.1810, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.7.5
See https://gist.github.com/83a5229f386acecf8b4c6f9b1e9450cc for a full test report.

**Comment by akesandgren** [comment]
Kicking travis now that #7437 is merged

**Comment by akesandgren** [comment]
Travis kicked

**Comment by akesandgren** [comment]
Test report by @akesandgren
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
b-cn0315.hpc2n.umu.se - Linux ubuntu 16.04, Intel(R) Xeon(R) CPU E5-2690 v4 @ 2.60GHz, Python 2.7.12
See https://gist.github.com/1eb7f6cd7a31f233f154b6fb5dfc5cbd for a full test report.

**Comment by akesandgren** [comment]
Going in, thanks @boegel!

**Comment by boegel** [comment]
Note: the `CP2K` easyconfig included here was retracted in #7447

**Pull request merged**
