### PR TITLE
{bio}[foss/2020b] SRST2 v0.2.0-20210620 w/ Python 2.7.18

### PR DESCRIPTION
**Pull request by boegel**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by boegel** [comment]
@boegelbot please test @ generoso

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
node3117.skitty.os - Linux centos linux 7.9.2009, x86_64, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz (skylake_avx512), Python 3.6.8
See https://gist.github.com/e88227e9ba1f2ebe405c0535ac5529d5 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
node3519.doduo.os - Linux RHEL 8.2, x86_64, AMD EPYC 7552 48-Core Processor (zen2), Python 3.6.8
See https://gist.github.com/8bba564cefa7a6d0f5ae72de969e4c55 for a full test report.

**Comment by boegel** [comment]
Somehow the installation on `generoso` got done with Python 3.8.6, even though that's not specified as a dependency at all (not even indirect)... 🤔

**Comment by boegel** [comment]
Ah, apparently `Python` 3.8.6 is a dependency for `Bowtie2/2.4.2-GCC-10.2.0` for the installation on `generoso`, which happened via #14097, but those changes were rolled back in 2566ceda5b4bf153d84fd05b9db7925ca7bfe3c4 (see also https://github.com/easybuilders/easybuild-easyconfigs/pull/14097#issuecomment-933247964).

I'll trigger a forced re-install of those 3 `Bowtie2` modules...

**Comment by boegel** [comment]
@boegelbot please test @ generoso
EB_ARGS="--rebuild Bowtie2-2.4.1-GCC-9.3.0.eb Bowtie2-2.4.2-GCC-10.2.0.eb  Bowtie2-2.4.2-GCC-9.3.0.eb SRST2-0.2.0-20210620-foss-2020b-Python-2.7.18.eb"

**Comment by verdurin** [comment]
Test report by @verdurin
**SUCCESS**
Build succeeded for 6 out of 6 (1 easyconfigs in total)
centos7.lan - Linux centos linux 7.9.2009, x86_64, Intel Core Processor (Skylake, IBRS), Python 3.6.8
See https://gist.github.com/c609c43ff8799a9ac32946d9d87efe8b for a full test report.

**Comment by verdurin** [comment]
Test report by @verdurin
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
easybuild-c7.novalocal - Linux centos linux 7.9.2009, x86_64, Intel Xeon Processor (Skylake, IBRS), Python 3.6.8
See https://gist.github.com/4c3ece97b91740e59f6d019f2c93905f for a full test report.

**Review by verdurin — APPROVED** [review]
Looks fine.

**Comment by verdurin** [comment]
Going in, thanks @boegel!

**Pull request merged**
