### PR TITLE
{chem}[foss/2022a] NAMD v2.14

### PR DESCRIPTION
**Pull request by maxim-masterov**
(created using `eb --new-pr`)

### CODE REVIEW

**Review by Micket — DISMISSED** [review]
I happened to see https://www.ks.uiuc.edu/Research/namd/2.14/bugfixes.html
So, they don't release patch fix releases, but just the patch separate? I think we should include these perhaps? 

Not sure what we should make of the version number; perhaps some date "2022-Apr-patchset" in the suffix, or perhaps just mention it in the description.

**Comment by maxim-masterov** [comment]
@Micket IMO, better to keep the name as is. I've added patches to PR.

**Comment by boegel** [comment]
@boegelbot please test @ generoso

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
node3160.skitty.os - Linux RHEL 8.6, x86_64, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz (skylake_avx512), Python 3.6.8
See https://gist.github.com/boegel/b0ecc1122497664bc1786ecb9fa19de6 for a full test report.

**Review by boegel — APPROVED** [review]
lgtm

**Comment by boegel** [comment]
Going in, thanks @maxim-masterov!

**Pull request merged**
