### PR TITLE
{math}[system/system] MATLAB v2022b

### PR DESCRIPTION
**Pull request by boegel**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by casparvl** [comment]
Test report by @casparvl
**FAILED**
Build succeeded for 0 out of 1 (1 easyconfigs in total)
tcn502.local.snellius.surf.nl - Linux Rocky Linux 8.7, x86_64, AMD EPYC 7H12 64-Core Processor, Python 3.6.8
See https://gist.github.com/d990c352713a5240acf52f15dfd2081e for a full test report.

**Comment by casparvl** [comment]
Install time of 2 seconds... that doesn't sound like MATLAB, I don't think anything is _actually_ being installed
```
== 2023-03-16 01:48:39,464 matlab.py:172 INFO Installing MATLAB with key 1 of 1
== 2023-03-16 01:48:39,464 filetools.py:249 INFO Overwriting existing file /scratch-nvme/1/casparl/ebbuildpath/MATLAB/2022b/system-system-r5/my_installer_input.txt
== 2023-03-16 01:48:39,464 run.py:236 INFO running cmd: export _JAVA_OPTIONS="-Xmx2048m" &&  /gpfs/nvme1/1/casparl/ebbuildpath/MATLAB/2022b/system-system-r5/install -inputFile /scratch-nvme/1/casparl/ebbuildpath/MATLAB/2022b/system-system-r5/my_installer_input.txt
== 2023-03-16 01:48:41,752 run.py:648 INFO cmd "export _JAVA_OPTIONS="-Xmx2048m" &&  /gpfs/nvme1/1/casparl/ebbuildpath/MATLAB/2022b/system-system-r5/install -inputFile /scratch-nvme/1/casparl/ebbuildpath/MATLAB/2022b/system-system-r5/my_installer_input.txt " exited with exit code 0 and output:

== 2023-03-16 01:48:41,753 build_log.py:267 INFO ... (took 2 secs)
```

**Comment by casparvl** [comment]
Ah...
```
## By default, the installer installs all the products and
## documentation for which you are licensed. Products you are not licensed for
## are not installed, even if they are listed here.
```
Maybe it's just not reaching our license server correctly. I'll see if something is wrong with the license server coordinates...

**Comment by casparvl** [comment]
License coordinates seem ok, `lmutil lmstat -c /scratch-nvme/1/casparl/ebbuildpath/MATLAB/2022b/system-system-r5/matlab.lic -a` prints the right license, with the toolboxes we have a license for. It's at FlexLM license version 11.18.1. From the MATLAB site, that seems to be the newest, so I'm assuming it should work with 2022b, but maybe you can check what version you are using at UGent?

**Comment by branfosj** [comment]
> License coordinates seem ok, `lmutil lmstat -c /scratch-nvme/1/casparl/ebbuildpath/MATLAB/2022b/system-system-r5/matlab.lic -a` prints the right license, with the toolboxes we have a license for. It's at FlexLM license version 11.18.1. From the MATLAB site, that seems to be the newest, so I'm assuming it should work with 2022b, but maybe you can check what version you are using at UGent?

Have you set an install key for MATLAB? See the information at https://github.com/easybuilders/easybuild-easyconfigs/tree/develop/easybuild/easyconfigs/m/MATLAB#license

**Comment by branfosj** [comment]
And I wonder if we should change the easyblock to fail if the key is not set - rather than defaulting to `00000-00000-00000-00000-00000-00000-00000-00000-00000-00000`

**Comment by branfosj** [comment]
> And I wonder if we should change the easyblock to fail if the key is not set - [rather than defaulting](https://github.com/easybuilders/easybuild-easyblocks/blob/develop/easybuild/easyblocks/m/matlab.py#L162) to `00000-00000-00000-00000-00000-00000-00000-00000-00000-00000`

See https://github.com/easybuilders/easybuild-easyblocks/pull/2905 for that.

**Comment by casparvl** [comment]
> > License coordinates seem ok, `lmutil lmstat -c /scratch-nvme/1/casparl/ebbuildpath/MATLAB/2022b/system-system-r5/matlab.lic -a` prints the right license, with the toolboxes we have a license for. It's at FlexLM license version 11.18.1. From the MATLAB site, that seems to be the newest, so I'm assuming it should work with 2022b, but maybe you can check what version you are using at UGent?
> 
> Have you set an install key for MATLAB? See the information at https://github.com/easybuilders/easybuild-easyconfigs/tree/develop/easybuild/easyconfigs/m/MATLAB#license
> 
> ~You can check what the key is set to be searching for Installing MATLAB with key in the log file.~ Ah no, that info is how many keys there are, not what the keys are.

Yeah, my key is set, otherwise `lmutil lmstat -c /scratch-nvme/1/casparl/ebbuildpath/MATLAB/2022b/system-system-r5/matlab.lic` also wouldn't have printed the right license, as that is the matlab.lic that gets generated during the build (I'm setting it via the `EB_MATLAB_KEY` environment variable btw).

**Comment by migueldiascosta** [comment]
@casparvl you can add e.g. `installopts = '-outputFile install.out'` to the easyconfig (we should probably add something similar to the easyblock), the actual error should show up on that output file in that installation folder (it could be that the file installation key is invalid for this version)

**Comment by Micket** [comment]
> Yeah, my key is set, otherwise `lmutil lmstat -c /scratch-nvme/1/casparl/ebbuildpath/MATLAB/2022b/system-system-r5/matlab.lic`

I don't think this is correct; flexlm will happily report a working licenses regardless of what is done with the key (which is the extra thing they just add for matlab during the installation step).

> @casparvl you can add e.g. `installopts = '-outputFile install.out'` to the easyconfig (we should probably add something similar to the easyblock),

I agree with should do precisely that https://github.com/easybuilders/easybuild-easyblocks/issues/2880 :) 


I think this PR is good to merge, but i don't have the sources for this particular variant to test with.

**Review by Micket — APPROVED** [review]
lgtm

I don't have this version to test install on, but i dont believe anything has changed w.r.t. matlab installations so if the iso file is correct i see no reason to doubt this. The latest matlab easyblock changes also now display common errors that can occur in the installer output log.

**Comment by Micket** [comment]
Going in, thanks @boegel!

**Pull request merged**
