### PR TITLE
{tools}[fosscuda/2019b] Horovod v0.18.2 w/ Python 3.7.4

### PR DESCRIPTION
**Pull request by Flamefire**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by Flamefire** [comment]
@boegel How to fix that CI error? I don't fully understand it. What is wrong here?

> AssertionError: No multi-variant deps found for '^.*-(?P<tc_gen>201[89][ab]).*\.eb$' easyconfigs:
> found 2 variants of 'TensorFlow' dependency in easyconfigs using '2019b' toolchain generation
> * version: 1.15.0; versionsuffix: -Python-3.7.4 as dep for set(['Horovod-0.18.2-fosscuda-2019b-TensorFlow-1.15.0-Python-3.7.4.eb'])
> * version: 2.0.0; versionsuffix: -Python-3.7.4 as dep for set(['Horovod-0.18.2-fosscuda-2019b-TensorFlow-2.0.0-Python-3.7.4.eb'])

**Comment by migueldiascosta** [comment]
@Flamefire as a general rule, we try to stick to a single version of dependencies per common toolchain "generation", and in this case `fosscuda/2019b` is using `TensorFlow/2.0.0` (and the `Horovod` easyconfig using it also aready exists). Is there a particular reason to need `Horovod` with `TensorFlow/1.5.0` under `fosscuda/2019b`?

**Comment by Flamefire** [comment]
There are 2 answers:
- For machine learning they always want the latest and greatest of whatever framework they are using
- For TensorFlow: 1.x and 2.x are so different that they qualify easily as 2 different softwares not 2 different versions

So yes there is the latest TensorFlow 1.x and 2.x required and as Horovod is coupled to specific installations of the framework(s) used one need multiple ones.

**Comment by migueldiascosta** [comment]
@Flamefire in that case you have to add an exception for `TensorFlow` in `test.easyconfigs.easyconfigs.check_dep_vars` (used in `test_dep_versions_per_toolchain_generation`)

**Comment by boegel** [comment]
Since the `versionsuffix` already makes it clear that this `Horovod` easyconfig uses a different `TensorFlow` version, it's easy to add an exception in the tests for this, so done in 6a302c8...

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
generoso - Linux centos linux 7.6.1810, Intel(R) Xeon(R) CPU E5-2660 v4 @ 2.00GHz, Python 3.6.8
See https://gist.github.com/3734f2ea7658e3872d69233f15fa3463 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
node3159.skitty.os - Linux centos linux 7.7.1908, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz, Python 3.6.8
See https://gist.github.com/35154ae5bbe62cea06f8d9a24a4b93e7 for a full test report.

**Comment by boegel** [comment]
Going in, thanks @Flamefire!

**Pull request merged**
