### PR TITLE
Resolving some distribution-related dependency problems

### PR DESCRIPTION
**Pull request by sylmarien**
This is the pull request for the issue #1374 about some distribution-related dependencies.

### CODE REVIEW

**Comment by pescobar** [comment]
@sylmarien I think the os dependencies no longer require to specify the distribution (the IF sentences you include) since this PR was merged https://github.com/hpcugent/easybuild-framework/pull/1111

Now you just need to specify a list of tuples with the depencies and the framework will take care of it depending on the detected package management system. You can check an example here 
https://github.com/pescobar/easybuild-easyconfigs/blob/iomkl-2015.01/easybuild/easyconfigs/o/OpenMPI/OpenMPI-1.8.4-iccifort-2015.1.133-GCC-4.9.2.eb#L24

@boegel am I missing something which should also be remarked about this topic?

**Comment by boegel** [comment]
@pescobar is right, there's no reason to resort to using `if`/`else` in easyconfig files

although it does work, anything else than variable assignments should be avoided in easyconfig files

so, replace:

```python
if OS_NAME in ['debian', 'ubuntu']:
  osdependencies = ['libXmu-dev']
else:
  # OK for OS_NAME == redhat, fedora, RHEL, SL, centos
  osdependencies = ['libXmu-devel']
```

with

```python
osdependencies = [('libXmu-dev', 'libXmu-devel')]
```

In the latter version, EasyBuild will check both package names, and if either of both is available, it will be happy.

Note that this OS deps requirement can also be skipped using the `--ignore-osdeps` command line option (at your own risk of running into a failed build).

**Comment by boegel** [comment]
Jenkins: ok to test

**Comment by sylmarien** [comment]
Thanks for the feedbacks, I didn't know about this syntax.

I modified my changes to what I understand is what you want. Let me know if I missed something.

**Comment by migueldiascosta** [comment]
@sylmarien, this PR is being closed for the following reason(s): no activity for > 6 months, obsoleted by more recent PRs, uses an archived toolchain.
Please don't hesitate to reopen this PR or add a comment if you feel this contribution is still relevant.
For more information on our policy w.r.t. closing PRs, see https://easybuild.readthedocs.io/en/latest/Contributing.html#why-a-pull-request-may-be-closed-by-a-maintainer

**Pull request closed without merging**
