### PR TITLE
{math}[GCCcore/7.3.0] Osi v0.108.5

### PR DESCRIPTION
**Pull request by tstrempel**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by tstrempel** [comment]
Is it possible to specify multiple Easyconfigs in one command, which are dependend on one another e. g. CoinUtils --> Osi --> OpenMS

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
node3105.skitty.os - Linux centos linux 7.7.1908, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz, Python 3.6.8
See https://gist.github.com/8a4cb3b0b3faf12c709348f93155c0d5 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
generoso - Linux centos linux 7.6.1810, Intel(R) Xeon(R) CPU E5-2660 v4 @ 2.00GHz, Python 3.6.8
See https://gist.github.com/e14f235fb9fc1a69f03cf25541f8727b for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
node2428.golett.os - Linux centos linux 7.7.1908, Intel(R) Xeon(R) CPU E5-2680 v3 @ 2.50GHz, Python 2.7.5
See https://gist.github.com/800f40b5569cc7843b05da8e23195407 for a full test report.

**Comment by boegel** [comment]
> Is it possible to specify multiple Easyconfigs in one command, which are dependend on one another e. g. CoinUtils --> Osi --> OpenMS

@tstrempel Yes, you can run `eb CoinUtils.eb Osi.eb OpenMS.eb --robot`, and EasyBuild will make sure they're built in the right order, as long as they're using the same toolchain.

For easyconfigs with different (sub)toolchains (`GCCcore`, `gompi`, `foss` of the same generation), you can use `eb OpenMS.eb --robot .`, and then have the easyconfigs for `CoinUtils` and `Osi` in the same directory, with the correct filenames (since robot only checks for easyconfig files for dependencies using filenames, it won't parse all `*.eb` files it runs into).

**Comment by boegel** [comment]
Going in, thanks @tstrempel!

**Pull request merged**
