### PR TITLE
{bio}[foss/2020a] SplAdder v2.4.2 w/ Python 3.8.2

### PR DESCRIPTION
**Pull request by lexming**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by lexming** [comment]
Test report by @lexming
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
node381.hydra.os - Linux centos linux 7.7.1908, x86_64, Intel(R) Xeon(R) Gold 6148 CPU @ 2.40GHz, Python 2.7.5
See https://gist.github.com/b08a5970cfa537bc7799b2e025d11eff for a full test report.

**Comment by verdurin** [comment]
Test report by @verdurin
**FAILED**
Build succeeded for 4 out of 5 (1 easyconfigs in total)
nuc.lan - Linux Fedora 32, x86_64, Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz, Python 3.8.6
See https://gist.github.com/e4ab56e3f6dfacfd5883fcc6127023cf for a full test report.

**Comment by verdurin** [comment]
@lexming missing `intervaltree` - is that something I need to rebuild locally, or a genuine failure?

**Comment by lexming** [comment]
@verdurin `intervaltree` is included in the easyconfig of Python. Maybe you have to re-install Python v3.8.2.

**Comment by verdurin** [comment]
Test report by @verdurin
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
nuc.lan - Linux Fedora 32, x86_64, Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz, Python 3.8.6
See https://gist.github.com/1abb233f40bf34b57f241a8bde3c2730 for a full test report.

**Comment by verdurin** [comment]
@lexming yes, working fine now. Would have been unlike you to have made that kind of mistake...

**Comment by verdurin** [comment]
@boegelbot please test @ generoso

**Review by verdurin — APPROVED** [review]
Looks fine.

**Comment by verdurin** [comment]
Going in, thanks @lexming!

**Pull request merged**
