### PR TITLE
Remove duplicated PYTHONPATH module entries

### LINKED ISSUE #13432: Failing to build PyQt5-5.9.2-intel-2018a-Python-3.6.4
The PyQt5-5.9.2-intel-2018a-Python-3.6.4.eb fails to build due to the EasyBlock not finding IMKL

Checking the modules loaded:
```
module load intel/2018a
module load Python/3.6.4-iimkl-2018a
module load SIP/4.19.8-intel-2018a-Python-3.6.4
module load Qt5/5.10.1-intel-2018a
```

It turns out that loading SIP switches `Python/3.6.4-iimkl-2018a => Python/3.6.4-intel-2018a` which results (for unknown reason) to NO MKL module loaded anymore.

I think iimkl having a different imkl than intel while supposedly being a subtoolchain is simply wrong, isn't it?

### PR DESCRIPTION
**Pull request by Flamefire**
Those ECs set the PYTHONPATH again which is already done by the used easyblock leading to a slower module/python

Running into https://github.com/easybuilders/easybuild-easyconfigs/issues/13432 while testing this, hence fixed here

Fixes #13432

### CODE REVIEW

**Comment by Flamefire** [comment]
Test report by @Flamefire
**FAILED**
Build succeeded for 5 out of 24 (9 easyconfigs in total)
taurusa4 - Linux centos linux 7.7.1908, x86_64, Intel(R) Xeon(R) CPU E5-2603 v4 @ 1.70GHz (broadwell), Python 2.7.5
See https://gist.github.com/837bb3c8a366bd9e7abf90c80d429fb0 for a full test report.

**Comment by Flamefire** [comment]
Test report by @Flamefire
**FAILED**
Build succeeded for 14 out of 23 (9 easyconfigs in total)
taurusi4073.taurus.hrsk.tu-dresden.de - Linux RHEL 7.9, x86_64, Intel(R) Xeon(R) CPU E5-2680 v3 @ 2.50GHz (haswell), Python 2.7.5
See https://gist.github.com/47f2438939bfc857917a83d00fe7c509 for a full test report.

**Comment by Flamefire** [comment]
Test report by @Flamefire
**SUCCESS**
Build succeeded for 9 out of 9 (9 easyconfigs in total)
taurusi6606.taurus.hrsk.tu-dresden.de - Linux RHEL 7.9, x86_64, Intel(R) Xeon(R) CPU E5-2680 v3 @ 2.50GHz (haswell), Python 2.7.5
See https://gist.github.com/2d840b4654b1b42b376970cfcd5f8654 for a full test report.

**Comment by Flamefire** [comment]
@boegel Anything required here?

**Comment by Flamefire** [comment]
Test report by @Flamefire
**SUCCESS**
Build succeeded for 7 out of 7 (7 easyconfigs in total)
taurusi6403.taurus.hrsk.tu-dresden.de - Linux RHEL 7.9, x86_64, Intel(R) Xeon(R) CPU E5-2680 v3 @ 2.50GHz (haswell), Python 2.7.5
See https://gist.github.com/707a7b7b242d937161c72c27abe8d055 for a full test report.

**Comment by boegel** [comment]
@Flamefire All these easyconfigs have already been archived in the `5.0.x` branch because they're using deprecated or unsupported toolchains, see also https://docs.easybuild.io/policies/toolchains, so I'm not sure it's worth pursuing this (sorry).

Can we enhance the easyconfigs test suite so these duplicated `PYTHONPATH` entries can be avoided going forward?

**Comment by Flamefire** [comment]
> @Flamefire All these easyconfigs have already been archived in the `5.0.x` branch because they're using deprecated or unsupported toolchains, see also https://docs.easybuild.io/policies/toolchains, so I'm not sure it's worth pursuing this (sorry).

Hm, ok

> Can we enhance the easyconfigs test suite so these duplicated `PYTHONPATH` entries can be avoided going forward?

Maybe: https://github.com/easybuilders/easybuild-easyconfigs/pull/19061

**Comment by Flamefire** [comment]
Can this be merged? Fixed conflicts again

**Comment by Flamefire** [comment]
Closing for https://github.com/easybuilders/easybuild-easyconfigs/pull/20960

**Pull request closed without merging**
