### PR TITLE
{tools}[iimpi/2021b] ecCodes v2.24.2

### PR DESCRIPTION
**Pull request by rungitta**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by rungitta** [comment]
Test report by @rungitta
**SUCCESS**
Build succeeded for 0 out of 0 (1 easyconfigs in total)
login-2.fram.sigma2.no - Linux UNKNOWN UNKNOWN, x86_64, Intel(R) Xeon(R) CPU E5-2683 v4 @ 2.10GHz, Python 2.7.5
See https://gist.github.com/ac6ef0f721656c7e527177a6c74c8331 for a full test report.

**Comment by rungitta** [comment]
Test report by @rungitta
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
login-2.fram.sigma2.no - Linux UNKNOWN UNKNOWN, x86_64, Intel(R) Xeon(R) CPU E5-2683 v4 @ 2.10GHz, Python 2.7.5
See https://gist.github.com/9a378ecf0343ca2e286ced2841eadd2e for a full test report.

**Comment by lexming** [comment]
@boegelbot: please test @ generoso

**Review by lexming — APPROVED** [review]
LGTM

**Comment by lexming** [comment]
Going in, thanks @rungitta !

**Comment by lexming** [comment]
Test report by @lexming
**SUCCESS**
Build succeeded for 3 out of 3 (1 easyconfigs in total)
node301.hydra.os - Linux centos linux 7.9.2009, x86_64, Intel(R) Xeon(R) Gold 6148 CPU @ 2.40GHz, Python 2.7.5
See https://gist.github.com/f1200c7414038fcb1a5dab57d7e121ee for a full test report.

**Pull request merged**
