### PR TITLE
{tools}[gfbf/2023a] ipympl v0.9.3

### PR DESCRIPTION
**Pull request by jose-d**
(created using `eb --new-pr`)

only updated dependencies of 2022a to 2023a as there is no new version since 2022a..

### CODE REVIEW

**Comment by jose-d** [comment]
test report https://gist.github.com/jose-d/5b07f6dd937237ea1124b52fcbd3bc42

**Comment by SebastianAchilles** [comment]
@boegelbot please test @ jsc-zen2

**Comment by jose-d** [comment]
Test report by @jose-d
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
gpu1.phoebe.lan - Linux Rocky Linux 8.8 (Green Obsidian), x86_64, AMD EPYC 7543 32-Core Processor, 8 x NVIDIA NVIDIA A100-SXM4-80GB, 535.104.05, Python 3.11.2
See https://gist.github.com/jose-d/cf91c92af78e590f4293386331c54d23 for a full test report.

**Comment by SebastianAchilles** [comment]
@boegelbot please test @ generoso

**Comment by jose-d** [comment]
test with current `Jupyter-bundle/20230823-GCCcore-12.3.0` and `matplotlib/3.7.2-gfbf-2023a`: works.

Screenshot_20230922_121315-1

**Comment by SebastianAchilles** [comment]
@boegelbot please test @ jsc-zen2

**Comment by lexming** [comment]
@boegelbot: please test @ generoso

**Review by lexming — APPROVED** [review]
@jose-d thanks for the PR, it looks good! I made a few minor changes to adapt it to recent changes in `2023a`:
* toolchain can be downgraded to `gfbf`
* we now use a custom environment variable to control Jupyter configuration

LGTM

**Comment by lexming** [comment]
Merging, thanks @jose-d !

**Pull request merged**
