### PR TITLE
{tools}[foss/2019b] IRkernel v1.1 w/ Python 3.7.4

### PR DESCRIPTION
**Pull request by dquigley-warwick**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by dquigley-warwick** [comment]
Test report by @dquigley-warwick
**FAILED**
Build succeeded for 0 out of 1 (1 easyconfigs in this PR)
dedicated201.csc.warwick.ac.uk - Linux centos linux 7.7.1908, Intel(R) Xeon(R) CPU E5-2640 v3 @ 2.60GHz, Python 2.7.5
See https://gist.github.com/055ae6013390ab288904a9f65d679105 for a full test report.

**Comment by dquigley-warwick** [comment]
Test report by @dquigley-warwick
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
dedicated201.csc.warwick.ac.uk - Linux centos linux 7.7.1908, Intel(R) Xeon(R) CPU E5-2640 v3 @ 2.60GHz, Python 2.7.5
See https://gist.github.com/acf721da4af606e6faad3909fa4d38ce for a full test report.

**Comment by verdurin** [comment]
Test report by @verdurin
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
generoso - Linux centos linux 7.6.1810, Intel(R) Xeon(R) CPU E5-2660 v4 @ 2.00GHz, Python 3.6.8
See https://gist.github.com/46717668f8fba42a77ac6bb01e428937 for a full test report.

**Comment by verdurin** [comment]
Going in, thanks @dquigley-warwick!

**Pull request merged**
