### PR TITLE
{geo}[foss/2018b] CESM-deps v2 (REVIEW)

### PR DESCRIPTION
**Pull request by hajgato**
Needs PR #6654

### CODE REVIEW

**Comment by hajgato** [comment]
needs PR #6916

**Comment by hajgato** [comment]
@boegel Renamed to `CESM-deps`

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 3 out of 3 (3 easyconfigs in this PR)
node3146.skitty.os - Linux centos linux 7.6.1810, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz, Python 2.7.5
See https://gist.github.com/c50111c7adbf00ea40a3cfb3db91bc11 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 3 out of 3 (3 easyconfigs in this PR)
node2525.golett.os - Linux centos linux 7.6.1810, Intel(R) Xeon(R) CPU E5-2680 v3 @ 2.50GHz, Python 2.7.5
See https://gist.github.com/fb70bba830b56148c2b656f1e8393664 for a full test report.

**Comment by boegel** [comment]
Going in, thanks @hajgato!

**Pull request merged**
