### PR TITLE
just use cp to copy stereo_chemical_props.txt to AlphaFold installation directory

### PR DESCRIPTION
**Pull request by akesandgren**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by boegel** [comment]
@akesandgren Can you elaborate a bit why you need this, just for documentation sake?

**Comment by akesandgren** [comment]
The problem arises because our EB-sources tree is residing on a FS with ACLs enabled, thus the downloaded source file gets ACL's set, the first 'extract_cmd': "cp -a %s .", copies the file to /scratch including the ACLs, and then the second
```
"cp -a %%(builddir)s/stereo_chemical_props-%s.txt %%(installdir)s/stereo_chemical_props.txt" % local_scp_commit,
```
tries to copy the file including the ACLs onto a file system that doesn't have ACLs and we get "permission deined" as a result.

When copying a file there is no reason whatsoever to use cp -a, and the cp -a used for the scripts dir only need a standard cp -r in reality. But since that didn't cause problems I didn't bother changing that one.

**Comment by akesandgren** [comment]
To make matters worse, using cp -a might pull along ACLs that shouldn't be there in the installdir...

**Comment by boegel** [comment]
@boegelbot please test @ generoso

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in total)
node3301.joltik.os - Linux centos linux 7.9.2009, x86_64, Intel(R) Xeon(R) Gold 6242 CPU @ 2.80GHz (cascadelake), Python 3.6.8
See https://gist.github.com/8435047cb818b8fdedd73655f91068b5 for a full test report.

**Review by boegel — APPROVED** [review]
lgtm

**Comment by boegel** [comment]
Going in, thanks @akesandgren!

**Pull request merged**
