### PR TITLE
{lib}[foss/2021b] imgaug v0.4.0 w/ Python 3.9.6

### PR DESCRIPTION
**Pull request by sassy-crick**
(created using `eb --new-pr`)

Requires:
- [x] PR #16393

### CODE REVIEW

**Comment by casparvl** [comment]
Test report by @casparvl
**FAILED**
Build succeeded for 0 out of 1 (1 easyconfigs in total)
gcn2 - Linux RHEL 8.4, x86_64, Intel(R) Xeon(R) Platinum 8360Y CPU @ 2.40GHz, 4 x NVIDIA NVIDIA A100-SXM4-40GB, 515.43.04, Python 3.6.8
See https://gist.github.com/e32c2f96c70561a56b3a49ac890a161c for a full test report.

**Comment by casparvl** [comment]
Test report by @casparvl
**FAILED**
Build succeeded for 0 out of 1 (1 easyconfigs in total)
software2.lisa.surfsara.nl - Linux debian 10.13, x86_64, Intel(R) Xeon(R) Bronze 3104 CPU @ 1.70GHz, 4 x NVIDIA NVIDIA TITAN V, 470.103.01, Python 3.7.3
See https://gist.github.com/0aa0cb21a9a1ce0abeae9a228c76f86c for a full test report.

**Comment by casparvl** [comment]
@boegelbot please test @ generoso

**Comment by casparvl** [comment]
Test report by @casparvl
**SUCCESS**
Build succeeded for 7 out of 7 (1 easyconfigs in total)
software2.lisa.surfsara.nl - Linux debian 10.13, x86_64, Intel(R) Xeon(R) Bronze 3104 CPU @ 1.70GHz, 4 x NVIDIA NVIDIA TITAN V, 470.103.01, Python 3.7.3
See https://gist.github.com/dd18bed44a313433c8074cad458724ab for a full test report.

**Comment by casparvl** [comment]
@boegelbot please test @ generoso

**Comment by casparvl** [comment]
Hm, the failure on `jsc-zen2` is not specific to this PR, it's on the depending OpenCV. The OpenCV EasyBlock cannot handle the `optarch` set on `jsc-zen2`.

**Review by casparvl — APPROVED** [review]
Lgtm!

**Comment by casparvl** [comment]
Going in, thanks @sassy-crick!

**Comment by smoors** [comment]
> Hm, the failure on `jsc-zen2` is not specific to this PR, it's on the depending OpenCV. The OpenCV EasyBlock cannot handle the `optarch` set on `jsc-zen2`.

PR to allow empty string for optarch, to override the default setting in jsc-zen2: https://github.com/easybuilders/easybuild-easyblocks/pull/2804

**Comment by casparvl** [comment]
Even though this one is alreayd merged, let's see if we can now build on `jsc-zen2`. And let's see if I get the syntax right to instruct the bot to do this...

@boegelbot please test @ jsc-zen2
EB_ARGS=--optarch=''

**Comment by casparvl** [comment]
That was clearly not the right way to instruct it. Let's retry:

@boegelbot please test @ jsc-zen2
EB_ARGS='--optarch="" --include-easyblocks-from-pr 2804'

**Comment by casparvl** [comment]
@boegelbot please test @ jsc-zen2
EB_ARGS='--optarch="" --include-easyblocks-from-pr 2804'

**Pull request merged**
