### PR TITLE
{devel}[foss/2022b] radian v0.6.9

### PR DESCRIPTION
**Pull request by pavelToman**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by pavelToman** [comment]
@boegelbot please test @ generoso

**Comment by pavelToman** [comment]
@boegelbot please test @ jsc-zen2

**Review by boegel — CHANGES_REQUESTED** [review]
@pavelToman We can/should add a custom sanity check here, since it's more than just a Python package that is being installed, there's a command line tool as well.

This should work:

```python
sanity_check_paths = {
    'files': ['bin/radian'],
    'dirs': ['lib/python%(pyshortver)s/site-packages'],
}

sanity_check_commands = ["radian --help"]

**Comment by pavelToman** [comment]
@boegelbot please test @ generoso

**Comment by pavelToman** [comment]
@boegelbot please test @ jsc-zen2

**Review by boegel — APPROVED** [review]
lgtm

**Comment by boegel** [comment]
Going in, thanks @pavelToman!

**Pull request merged**
