### PR TITLE
{numlib}[GCC/13.2.0] GSL v2.7

### PR DESCRIPTION
**Pull request by SebastianAchilles**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by SebastianAchilles** [comment]
@boegelbot please test @ generoso

**Comment by boegel** [comment]
@boegelbot please test @ jsc-zen3
EB_BRANCH=5.0.x

**Comment by SebastianAchilles** [comment]
@boegelbot please test @ jsc-zen3
EB_BRANCH=5.0.x

**Comment by SebastianAchilles** [comment]
@boegelbot please test @ jsc-zen3
EB_BRANCH=5.0.x

**Comment by boegel** [comment]
@SebastianAchilles We probably want to hide the output produced by the `./easybuild_develop.sh` script :)

**Comment by SebastianAchilles** [comment]
> @SebastianAchilles We probably want to hide the output produced by the `./easybuild_develop.sh` script :)

Yes, that was a mistake. :see_no_evil:

**Comment by SebastianAchilles** [comment]
@boegelbot please test @ jsc-zen3
EB_BRANCH=5.0.x

**Comment by SebastianAchilles** [comment]
@boegelbot please test @ jsc-zen3

**Review by boegel — APPROVED** [review]
lgtm

**Comment by boegel** [comment]
Going in, thanks @SebastianAchilles!

**Pull request merged**
