### PR TITLE
{math}[intel/2020a] ELPA v2020.05.001

### PR DESCRIPTION
**Pull request by mboisson**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by lexming** [comment]
Test report by @lexming
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
node358.hydra.os - Linux centos linux 7.7.1908, x86_64, Intel(R) Xeon(R) Gold 6148 CPU @ 2.40GHz, Python 2.7.5
See https://gist.github.com/fb3fb650abcfbbba99fd3268e3259f6c for a full test report.

**Review by lexming — CHANGES_REQUESTED** [review]
`ELPA` v2020.05.001 needs Python at build time to execute `remove_xcompiler`. Please check previous easyconfig `ELPA-2019.11.001-intel-2019b.eb`

**Comment by mboisson** [comment]
Hmmmm, my version of `ELPA-2019.11.001-intel-2019b.eb` does not have a Python dependency...

**Comment by mboisson** [comment]
Oh, it's a recent change which haven't made its way to us yet.

**Comment by lexming** [comment]
Test report by @lexming
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
node111.hydra.os - Linux centos linux 7.7.1908, x86_64, Intel(R) Xeon(R) CPU E5-2680 v2 @ 2.80GHz, Python 2.7.5
See https://gist.github.com/6b5c05e99e5cbd3ee6dbe28af5696fc6 for a full test report.

**Comment by lexming** [comment]
Test report by @lexming
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
node365.hydra.os - Linux centos linux 7.7.1908, x86_64, Intel(R) Xeon(R) Gold 6148 CPU @ 2.40GHz, Python 2.7.5
See https://gist.github.com/ba7892d9243d332340a6dd631c7f3453 for a full test report.

**Comment by lexming** [comment]
Test report by @lexming
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
node124.hydra.os - Linux centos linux 7.7.1908, x86_64, Intel(R) Xeon(R) CPU E5-2680 v2 @ 2.80GHz, Python 2.7.5
See https://gist.github.com/be6dfe6d285f61559020f7d6722b7d7e for a full test report.

**Review by lexming — APPROVED** [review]
LGTM

**Comment by lexming** [comment]
Going in, thanks @mboisson !

**Pull request merged**
