### PR TITLE
{tools}[GCCcore/9.3.0] awscli v1.18.89 w/ Python 3.8.2

### PR DESCRIPTION
**Pull request by JackPerdue**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by zao** [comment]
Test report by @zao
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
dagur-fedora - Linux Fedora 32, x86_64, AMD Ryzen 9 3900X 12-Core Processor, Python 3.8.2
See https://gist.github.com/41083e7910ad0f4ce6c9f6adbc179126 for a full test report.

**Comment by lexming** [comment]
Test report by @lexming
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
node369.hydra.os - Linux centos linux 7.7.1908, x86_64, Intel(R) Xeon(R) Gold 6148 CPU @ 2.40GHz, Python 2.7.5
See https://gist.github.com/9f24b2b6e3833296ebc08fb0d8f9d76c for a full test report.

**Comment by lexming** [comment]
Test report by @lexming
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
node127.hydra.os - Linux centos linux 7.7.1908, x86_64, Intel(R) Xeon(R) CPU E5-2680 v2 @ 2.80GHz, Python 2.7.5
See https://gist.github.com/80e93cdf724e81b220a30cb9b64d7759 for a full test report.

**Comment by lexming** [comment]
Going in, thanks @JackPerdue !

**Pull request merged**
