### PR TITLE
replace HDF5 v1.13.1 with v1.12.1 as dependency, since we shouldn't use odd minor versions of HDF5 which are not stable releases

### PR DESCRIPTION
**Pull request by Micket**
(created using `eb --new-pr`)
Odd releases are just RCs apparently.

### CODE REVIEW

**Comment by Micket** [comment]
Test report by @Micket
**FAILED**
Build succeeded for 1 out of 5 (4 easyconfigs in total)
alvis-c1 - Linux Rocky Linux 8.5, x86_64, Intel Xeon Processor (Skylake), Python 3.6.8
See https://gist.github.com/0a89308d6ae0e5a3531cb0e85902a503 for a full test report.

**Comment by Micket** [comment]
I also dropped the dap4 tests for netCDF as they were previously failing for me while trying to access online resources. Even if that site is back, i don't think we want to rely on tests that access internet as I imagine it causes annoying failures for those building on internet-less nodes.

**Comment by Micket** [comment]
This is so inconveniently big, I'll do test reports in batches

**Comment by Micket** [comment]
@boegel asked me to merge the test issue with netCDF first, so #16158 

I'll rebase this PR once it's merged.

**Comment by Micket** [comment]
Test report by @Micket
**SUCCESS**
Build succeeded for 5 out of 5 (5 easyconfigs in total)
alvis-c1 - Linux Rocky Linux 8.5, x86_64, Intel Xeon Processor (Skylake), Python 3.6.8
See https://gist.github.com/78244561608cc83014401b1281037a65 for a full test report.

**Comment by Micket** [comment]
Test report by @Micket
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
alvis-c1 - Linux Rocky Linux 8.5, x86_64, Intel Xeon Processor (Skylake), Python 3.6.8
See https://gist.github.com/a3f2ac63488c6442e06dba0f75583f60 for a full test report.

**Comment by Micket** [comment]
Test report by @Micket
**SUCCESS**
Build succeeded for 6 out of 6 (2 easyconfigs in total)
alvis-c1 - Linux Rocky Linux 8.5, x86_64, Intel Xeon Processor (Skylake), Python 3.6.8
See https://gist.github.com/b8116014979ef017786a74bd00b857ec for a full test report.

**Comment by Micket** [comment]
Test report by @Micket
**FAILED**
Build succeeded for 0 out of 1 (1 easyconfigs in total)
alvis-c1 - Linux Rocky Linux 8.5, x86_64, Intel Xeon Processor (Skylake), Python 3.6.8
See https://gist.github.com/e58f956f4b1016fddc615335c4d2c338 for a full test report.

**Comment by Micket** [comment]
Test report by @Micket
**FAILED**
Build succeeded for 0 out of 2 (1 easyconfigs in total)
alvis-c1 - Linux Rocky Linux 8.5, x86_64, Intel Xeon Processor (Skylake), Python 3.6.8
See https://gist.github.com/54afa233daaf3f1c396d3d0bf52d04ff for a full test report.

**Comment by boegel** [comment]
@boegelbot please test @ generoso
CORE_CNT=16

**Review by boegel — APPROVED** [review]
lgtm

**Comment by branfosj** [comment]
Test report by @branfosj
**SUCCESS**
Build succeeded for 16 out of 16 (9 easyconfigs in total)
bear-pg0105u36b.bear.cluster - Linux RHEL 8.6, x86_64, Intel(R) Xeon(R) Platinum 8360Y CPU @ 2.40GHz (icelake), Python 3.6.8
See https://gist.github.com/02ab685f4f346ef73c4475ec830b8671 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 9 out of 9 (9 easyconfigs in total)
node3100.skitty.os - Linux RHEL 8.4, x86_64, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz (skylake_avx512), Python 3.6.8
See https://gist.github.com/c2cbfd9f774654bb8f69a8e7792b488e for a full test report.

**Comment by boegel** [comment]
Going in, thanks @Micket!

**Comment by jfgrimm** [comment]
for reference: https://www.hdfgroup.org/2021/12/hdf5-1-13-0-introducing-experimental-releases/

**Comment by smoors** [comment]
@boegelbot please test @ jsc-zen2

**Pull request merged**
