### PR TITLE
{phys}[foss/2018a] Kratos v6.0 w/ Python 3.6.4

### PR DESCRIPTION
**Pull request by boegel**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
node3133.skitty.os - Linux centos linux 7.5.1804, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz, Python 2.7.5
See https://gist.github.com/d4923ad7c167e8bd807c5448ba4185dc for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
node2558.golett.os - Linux centos linux 7.5.1804, Intel(R) Xeon(R) CPU E5-2680 v3 @ 2.50GHz, Python 2.7.5
See https://gist.github.com/1e15da33086b4e94460b45faf928725c for a full test report.

**Comment by bartoldeman** [comment]
Test report by @bartoldeman
**FAILED**
Build succeeded for 0 out of 1 (1 easyconfigs in this PR)
lg-1r17-n06 - Linux centos 6.6, Intel(R) Xeon(R) CPU E5-2650 0 @ 2.00GHz, Python 2.6.6
See https://gist.github.com/563beec1fa0b241df5e4d9ec340ed884 for a full test report.

**Comment by boegel** [comment]
@bartoldeman 
```
CMake Error at cmake_install.cmake:61 (file):
  file INSTALL cannot find
"/localscratch/easybuild/build/Kratos/6.0/foss-2018a-Python-3.6.4/Kratos-6.0/optimized".
```

Any hints in the full log that may explain this?

**Comment by bartoldeman** [comment]
it failed somewhat strangely
```
Install the project...
/localscratch/easybuild/software/CMake/3.12.1-GCCcore-6.4.0/bin/cmake -P cmake_install.cmake
-- Install configuration: "Release"
-- Installing: /localscratch/easybuild/software/Kratos/6.0-foss-2018a-Python-3.6.4/KratosMultiphysics/__init__.py
-- Installing: /localscratch/easybuild/software/Kratos/6.0-foss-2018a-Python-3.6.4/KratosMultiphysics/kratos_utilities.py
-- Installing: /localscratch/easybuild/software/Kratos/6.0-foss-2018a-Python-3.6.4/KratosMultiphysics/kratos_globals.py
-- Installing: /localscratch/easybuild/software/Kratos/6.0-foss-2018a-Python-3.6.4/KratosMultiphysics/application_importer.py
-- Installing: /localscratch/easybuild/software/Kratos/6.0-foss-2018a-Python-3.6.4/KratosMultiphysics/KratosUnittest.py
CMake Error at cmake_install.cmake:61 (file):
  file INSTALL cannot find
  "/localscratch/easybuild/build/Kratos/6.0/foss-2018a-Python-3.6.4/Kratos-6.0/optimized".
```
I am rebuilding using parallel=1 now to see if that makes a difference

**Comment by boegel** [comment]
@bartoldeman Any other references to that `optimized` "file" in the full log?

**Comment by bartoldeman** [comment]
```
$ grep optimized /tmp/eb-XZogOM/*.log
/tmp/eb-XZogOM/easybuild-aMojdX.log:description = "OpenBLAS is an optimized BLAS library based on GotoBLAS2 1.13 BSD version."
/tmp/eb-XZogOM/easybuild-aMojdX.log:== 2018-11-13 08:23:28,060 easyconfig.py:497 INFO setting config option description: value OpenBLAS is an optimized BLAS library based on GotoBLAS2 1.13 BSD version. (type: <type 'str'>)
/tmp/eb-XZogOM/easybuild-aMojdX.log:  "/localscratch/easybuild/build/Kratos/6.0/foss-2018a-Python-3.6.4/Kratos-6.0/optimized".
/tmp/eb-XZogOM/easybuild-Kratos-6.0-20181113.082328.itqqd.log:  "/localscratch/easybuild/build/Kratos/6.0/foss-2018a-Python-3.6.4/Kratos-6.0/optimized".
```

**Comment by bartoldeman** [comment]
(serial compilation takes forever)

**Comment by boegel** [comment]
@jcotela Any idea what the problem may be here in @bartoldeman's attempt to install Kratos?

**Comment by bartoldeman** [comment]
It's the old issue of the old boost-devel rpm installed on CentOS6:
boost-devel-1.41.0-25.el6.centos.x86_64

```
$ rpm -ql boost-devel-1.41.0-25.el6.centos.x86_64 | grep -i cmake
/usr/lib64/boost/Boost-relwithdebinfo.cmake
/usr/lib64/boost/Boost.cmake
/usr/lib64/boost/BoostConfig.cmake
/usr/lib64/boost/BoostConfigVersion.cmake
```
```
-- Boost  found.
Boost Include: /usr/include
Boost Linkdir: /usr/lib64
```

**Comment by bartoldeman** [comment]
so anything that combines cmake and boost gets confused by this as the EB boost does not include any cmake files.

Ran into this issue a few times in the past and the simplest solution is to 'rpm -e boost-devel' if you can use your superrootpowers.

Am trying without boost-devel now.

**Comment by bartoldeman** [comment]
Test report by @bartoldeman
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
lg-1r17-n06 - Linux centos 6.6, Intel(R) Xeon(R) CPU E5-2650 0 @ 2.00GHz, Python 2.6.6
See https://gist.github.com/061310d93c7067d690e453370143c8a5 for a full test report.

**Comment by boegel** [comment]
@bartoldeman Why does the `-DBOOST_ROOT=$EBROOTBOOST` doesn't prevent that problem from happening?

**Comment by bartoldeman** [comment]
@boegel I think somehow cmake gives preference to /usr/lib64/boost/Boost.cmake but I have never figured out why.

**Comment by bartoldeman** [comment]
`-DBoost_NO_SYSTEM_PATHS=TRUE` may do the trick (untested yet)

**Comment by bartoldeman** [comment]
It works with
`-DBoost_NO_SYSTEM_PATHS=ON -DBoost_NO_BOOST_CMAKE=ON `
actually only `-DBoost_NO_BOOST_CMAKE=ON` is sufficient, but I think `-DBoost_NO_SYSTEM_PATHS=ON` does not hurt so I suggest adding both.

ref:
https://github.com/Kitware/CMake/blob/master/Modules/FindBoost.cmake
(which shows that if it finds a Boost-cmake config file, it's game over)
https://cmake.org/cmake/help/v3.12/module/FindBoost.html

**Comment by bartoldeman** [comment]
Test report by @bartoldeman
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
lg-1r17-n06 - Linux centos 6.6, Intel(R) Xeon(R) CPU E5-2650 0 @ 2.00GHz, Python 2.6.6
See https://gist.github.com/b4a1d679aef140d9b53d4b5d80a16733 for a full test report.

**Comment by bartoldeman** [comment]
Going in, thanks @boegel!

**Comment by boegel** [comment]
Test report by @boegel
**FAILED**
Build succeeded for 0 out of 2 (1 easyconfigs in this PR)
node2726.swalot.os - Linux centos linux 7.5.1804, Intel(R) Xeon(R) CPU E5-2660 v3 @ 2.60GHz, Python 2.7.5
See https://gist.github.com/b13de010ec078fa7d138a120d998ff3b for a full test report.

**Pull request merged**
