### PR TITLE
{data}[GCCcore/8.3.0] Globus-CLI v1.11.0 w/ Python 2.7.16 + 3.7.4

### PR DESCRIPTION
**Pull request by branfosj**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by branfosj** [comment]
I have not `multi_deps` this, as if you do this to test the main Globus CLI tool:
```
module load Python/3.7.4-GCCcore-8.3.0
module load Globus-CLI/1.11.0-GCCcore-8.3.0
globus --help
```
you get an error of:
```
Traceback (most recent call last):
  File "/rds/bear-apps/devel/2019b/branfosj-eb-2/EL7/EL7-cascadelake/software/Globus-CLI/1.11.0-GCCcore-8.3.0/bin/globus", line 6, in <module>
    from globus_cli import main
  File "/rds/bear-apps/devel/2019b/branfosj-eb-2/EL7/EL7-cascadelake/software/Globus-CLI/1.11.0-GCCcore-8.3.0/lib/python2.7/site-packages/globus_cli/__init__.py", line 1, in <module>
    from globus_cli.commands import main
  File "/rds/bear-apps/devel/2019b/branfosj-eb-2/EL7/EL7-cascadelake/software/Globus-CLI/1.11.0-GCCcore-8.3.0/lib/python2.7/site-packages/globus_cli/commands/__init__.py", line 1, in <module>
    from globus_cli.commands.main import main
  File "/rds/bear-apps/devel/2019b/branfosj-eb-2/EL7/EL7-cascadelake/software/Globus-CLI/1.11.0-GCCcore-8.3.0/lib/python2.7/site-packages/globus_cli/commands/main.py", line 1, in <module>
    from globus_cli.commands.bookmark import bookmark_command
  File "/rds/bear-apps/devel/2019b/branfosj-eb-2/EL7/EL7-cascadelake/software/Globus-CLI/1.11.0-GCCcore-8.3.0/lib/python2.7/site-packages/globus_cli/commands/bookmark/__init__.py", line 1, in <module>
    from globus_cli.commands.bookmark.commands import bookmark_command
  File "/rds/bear-apps/devel/2019b/branfosj-eb-2/EL7/EL7-cascadelake/software/Globus-CLI/1.11.0-GCCcore-8.3.0/lib/python2.7/site-packages/globus_cli/commands/bookmark/commands.py", line 1, in <module>
    from globus_cli.commands.bookmark.create import bookmark_create
  File "/rds/bear-apps/devel/2019b/branfosj-eb-2/EL7/EL7-cascadelake/software/Globus-CLI/1.11.0-GCCcore-8.3.0/lib/python2.7/site-packages/globus_cli/commands/bookmark/create.py", line 1, in <module>
    import click
ImportError: No module named click
```

**Comment by branfosj** [comment]
Test report by @branfosj
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
bear-pg0305u15a.bear.cluster - Linux RHEL 7.6, 8335-GTX, Python 2.7.5
See https://gist.github.com/cbff2889e06349423f3bc91641f23901 for a full test report.

**Comment by branfosj** [comment]
Test report by @branfosj
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
bear-pg0211u03a.bear.cluster - Linux centos linux 7.7.1908, Intel(R) Xeon(R) Gold 6248 CPU @ 2.50GHz, Python 2.7.5
See https://gist.github.com/942f3197db493c31dea497d546c81561 for a full test report.

**Comment by branfosj** [comment]
Test report by @branfosj
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
bber0501u03a.bb2.cluster - Linux centos linux 7.7.1908, Intel(R) Xeon(R) CPU E5-2690 v3 @ 2.60GHz, Python 2.7.5
See https://gist.github.com/d7c468e9e003396ab8f8595eb840ce6c for a full test report.

**Comment by branfosj** [comment]
Test report by @branfosj
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
bb2c1a10.bb2.cluster - Linux centos linux 7.7.1908, Intel(R) Xeon(R) CPU E5-2660 0 @ 2.20GHz, Python 2.7.5
See https://gist.github.com/a4992314d2c39ec21ef1b8b5fada09cd for a full test report.

**Comment by branfosj** [comment]
I've rebuilt both Python 2.7.16 and 3.7.4 with the latest from the develop branch. I then tested:
+ If I change this easyconfig to Python 2.7.16 then it works fine
+ If I use `multi_deps` (Python 3.7.4 and 2.7.16) then it fails with the error message as above
+ If I use `multi_deps` (Python 3.7.4 and 2.7.16) and and a Click install in this easyconfig then it also fails, but on `ImportError: No module named cryptography`.

It seems that something about `multi_deps` and this do not agree.

**Comment by smoors** [comment]
@branfosj the problem is with the shebang in the python executable, which has the python version hardcoded. you can fix this with:
```
fix_python_shebang_for = ['bin/globus', 'bin/jp.py', 'bin/pyjwt']
```
please also add:
```
sanity_check_commands = ['globus --help']
```

**Comment by branfosj** [comment]
Ah yes. Thanks for the pointer. I've updated the file as requested and test reports will show up soon.

**Comment by branfosj** [comment]
Test report by @branfosj
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
bb-pg-login02 - Linux centos linux 7.7.1908, Intel(R) Xeon(R) CPU E5-2620 v4 @ 2.10GHz, Python 2.7.5
See https://gist.github.com/c71509119deafedc580fee4f24344d59 for a full test report.

**Comment by branfosj** [comment]
Test report by @branfosj
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
bear-pg0211u03a.bear.cluster - Linux centos linux 7.7.1908, Intel(R) Xeon(R) Gold 6248 CPU @ 2.50GHz, Python 2.7.5
See https://gist.github.com/9986cf7d1d8d6426c46633a7100f4b49 for a full test report.

**Comment by branfosj** [comment]
Test report by @branfosj
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
bear-pg0305u05a.bear.cluster - Linux RHEL 7.6, 8335-GTX, Python 2.7.5
See https://gist.github.com/9c4b3d2eb13e82c3a3c182c448e59703 for a full test report.

**Comment by branfosj** [comment]
Test report by @branfosj
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
bb2c1a09.bb2.cluster - Linux centos linux 7.7.1908, Intel(R) Xeon(R) CPU E5-2660 0 @ 2.20GHz, Python 2.7.5
See https://gist.github.com/8c9cca47abc65e06a0487698d59cda01 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
node2405.golett.os - Linux centos linux 7.7.1908, Intel(R) Xeon(R) CPU E5-2680 v3 @ 2.50GHz, Python 2.7.5
See https://gist.github.com/ce96ac037012205086c822a1302ad4d1 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
generoso - Linux centos linux 7.6.1810, Intel(R) Xeon(R) CPU E5-2660 v4 @ 2.00GHz, Python 3.6.8
See https://gist.github.com/83b25c0e1aaf9bd17cf8fdebb8d8377b for a full test report.

**Comment by boegel** [comment]
Going in, thanks @branfosj!

**Comment by boegel** [comment]
Going in, thanks @branfosj!

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
node3100.skitty.os - Linux centos linux 7.7.1908, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz, Python 3.6.8
See https://gist.github.com/1be2ce989570c5fb84b66f8c0dd7b94d for a full test report.

**Pull request merged**
