### PR TITLE
{math}[GCC/13.2.0,GCCcore/13.2.0,gfbf/2023b] Singular v4.4.0, cddlib v0.94m, 4ti2 v1.6.10

### PR DESCRIPTION
**Pull request by PetrKralCZ**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by PetrKralCZ** [comment]
@boegelbot please test @ generoso

**Comment by PetrKralCZ** [comment]
@boegelbot please test @ jsc-zen2

**Review by migueldiascosta — APPROVED** [review]
lgtm

**Comment by migueldiascosta** [comment]
Going in, thanks @PetrKralCZ!

**Pull request merged**
