### PR TITLE
{data}[foss/2022b] ANTs v2.5.0

### PR DESCRIPTION
**Pull request by Neves-P**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by Neves-P** [comment]
Test report by @Neves-P
**FAILED**
Build succeeded for 0 out of 1 (1 easyconfigs in total)
WKS058930 - Linux Ubuntu 22.04, x86_64, 12th Gen Intel(R) Core(TM) i7-1260P, Python 3.10.12
See https://gist.github.com/Neves-P/8ae4dc9053f6e650f8cc7d973edcddd6 for a full test report.

**Comment by Neves-P** [comment]
Test report by @Neves-P
**FAILED**
Build succeeded for 0 out of 1 (1 easyconfigs in total)
WKS058930 - Linux Ubuntu 22.04, x86_64, 12th Gen Intel(R) Core(TM) i7-1260P, Python 3.10.12
See https://gist.github.com/Neves-P/ee3d90c7fdaa9f69056924193fbb4b4d for a full test report.

**Comment by Neves-P** [comment]
Test report by @Neves-P
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
WKS058930 - Linux Ubuntu 22.04, x86_64, 12th Gen Intel(R) Core(TM) i7-1260P, Python 3.10.12
See https://gist.github.com/Neves-P/4222843a01be13ac9578151ae8bd24f8 for a full test report.

**Comment by Neves-P** [comment]
The two failed tests were due to a lack of available memory on my side.

**Comment by verdurin** [comment]
@boegelbot please test @ generoso

**Comment by verdurin** [comment]
@boegelbot please test @ jsc-zen2

**Review by verdurin — APPROVED** [review]
Looks fine.

**Comment by verdurin** [comment]
Going in, thanks @Neves-P!

**Comment by Neves-P** [comment]
> Thanks @Neves-P for the contribution, and welcome to EasyBuild.

Thank you!

**Pull request merged**
