### PR TITLE
Update Boost to use multi_deps

### PR DESCRIPTION
**Pull request by ocaisa**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by ocaisa** [comment]
Requires https://github.com/easybuilders/easybuild-easyblocks/pull/1718

**Comment by ocaisa** [comment]
The only downside of this is that it unnecessarily leaves a dep on Python in the final module which is not strictly required.

**Comment by smoors** [comment]
@ocaisa why don't you use the `Boost.Python` easyconfigs for this?

**Comment by boegel** [comment]
I agree with @smoors that the approach of using a separate `Boost.Python` is better here, exactly to avoid introducing a `Python` dependency for `Boost`.

A `Boost.Python` for 1.70.0 was merged via #8415, so I suggest we close this one @ocaisa?

**Pull request closed without merging**
