### PR TITLE
{math}[dummy/] MCR vR2019a

### PR DESCRIPTION
**Pull request by smoors**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by smoors** [comment]
Test report by @smoors
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
nic424 - Linux centos linux 7.5.1804, Intel(R) Xeon(R) Gold 6148 CPU @ 2.40GHz, Python 2.7.5
See https://gist.github.com/74dd76da2513ff658c4cf954ce5abad1 for a full test report.

**Comment by boegel** [comment]
@smoors No more `Java` dependency?

**Comment by verdurin** [comment]
Test report by @verdurin
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
rescomp2 - Linux centos linux 7.3.1611, Intel(R) Xeon(R) Gold 6126 CPU @ 2.60GHz, Python 2.7.5
See https://gist.github.com/d2581f8ca54e6b69f61b2f3e23f59df9 for a full test report.

**Comment by verdurin** [comment]
Going in, thanks @smoors!

**Comment by verdurin** [comment]
Hmm. Missed the `Java` issue. @smoors probably worth submitting an amended PR to fix that?

**Comment by smoors** [comment]
MCR does not need an external Java to run. Just like MATLAB it ships with its own version of Java, see also https://github.com/easybuilders/easybuild-easyconfigs/issues/7574
On the other hand, it seems like matlab compiled scripts cannot use Java, not the Java included in MCR and not the external Java that is loaded as a dep, even when setting MATLAB_JAVA.
To illustrate consider this example script:
```
function checkjavaversion
    version -java
```
If compiled and run with MCR, I get this output:
```
ans =

    'Java is not enabled'
```

It could also be that I am doing something stupid of course, so it would be great if a MATLAB expert could chime in.

**Comment by boegel** [comment]
@smoors To be clear, that didn't work before either, right? Is there actually a use case for that?

**Comment by smoors** [comment]
question1: indeed, the example above did not work with version R2017a either.
question2: no idea.

**Pull request merged**
