### PR TITLE
skip mkl_fused_batch_norm_op_test test for TensorFlow 2.5.0 (broken on AMD EPYC systems)

### PR DESCRIPTION
**Pull request by boegel**
(created using `eb --new-pr`)

cfr. https://github.com/easybuilders/easybuild-easyblocks/pull/2583

### CODE REVIEW

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 3 out of 3 (3 easyconfigs in total)
node3302.joltik.os - Linux centos linux 7.9.2009, x86_64, Intel(R) Xeon(R) Gold 6242 CPU @ 2.80GHz (cascadelake), 4 x NVIDIA NVIDIA Tesla V100-SXM2-32GB, 465.19.01, Python 3.6.8
See https://gist.github.com/931bf7abaa198132a1b9226a5910f243 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
Using easyblocks from PR(s) https://github.com/easybuilders/easybuild-easyblocks/pull/2583
**SUCCESS**
Build succeeded for 3 out of 3 (3 easyconfigs in total)
node3309.joltik.os - Linux centos linux 7.9.2009, x86_64, Intel(R) Xeon(R) Gold 6242 CPU @ 2.80GHz (cascadelake), 1 x NVIDIA NVIDIA Tesla V100-SXM2-32GB, 465.19.01, Python 3.6.8
See https://gist.github.com/9d06455e3306adf24baf66c5ffc51d13 for a full test report.

**Comment by lexming** [comment]
Test report by @lexming
**FAILED**
Build succeeded for 2 out of 3 (3 easyconfigs in total)
node401.hydra.os - Linux centos linux 7.9.2009, x86_64, AMD EPYC 7282 16-Core Processor, 1 x NVIDIA A100-PCIE-40GB, 460.73.01, Python 2.7.5
See https://gist.github.com/2017b2a3f2012a3ccb85c1011a4152af for a full test report.

**Comment by boegel** [comment]
@lexming Ping on getting this merged?

**Comment by lexming** [comment]
Test report by @lexming
Using easyblocks from PR(s) https://github.com/easybuilders/easybuild-easyblocks/pull/2583
**FAILED**
Build succeeded for 0 out of 1 (1 easyconfigs in total)
node402.hydra.os - Linux centos linux 7.9.2009, x86_64, AMD EPYC 7282 16-Core Processor, 1 x NVIDIA A100-PCIE-40GB, 460.73.01, Python 2.7.5
See https://gist.github.com/0b6e859d4620dba0bab6cd733a172d35 for a full test report.

**Comment by lexming** [comment]
Test report by @lexming
Using easyblocks from PR(s) https://github.com/easybuilders/easybuild-easyblocks/pull/2583
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
node401.hydra.os - Linux centos linux 7.9.2009, x86_64, AMD EPYC 7282 16-Core Processor, 1 x NVIDIA A100-PCIE-40GB, 460.73.01, Python 2.7.5
See https://gist.github.com/2b72da0a9f4ea29ef64dc7062379a3b2 for a full test report.

**Comment by lexming** [comment]
Test report by @lexming
Using easyblocks from PR(s) https://github.com/easybuilders/easybuild-easyblocks/pull/2583
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
node401.hydra.os - Linux centos linux 7.9.2009, x86_64, AMD EPYC 7282 16-Core Processor, 1 x NVIDIA A100-PCIE-40GB, 460.73.01, Python 2.7.5
See https://gist.github.com/b5d1b0168f98feb4a0ad0dc9c095f2bc for a full test report.

**Pull request merged**
