### PR TITLE
{data,tools}[GCCcore/13.3.0,iimpi/2024a] HDF5 v1.14.5, Szip v2.1.1

### PR DESCRIPTION
**Pull request by sassy-crick**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by sassy-crick** [comment]
@boegelbot please test @ generoso

**Review by Micket — APPROVED** [review]
lgtm

**Comment by Micket** [comment]
@boegelbot please test @ jsc-zen3

**Comment by Micket** [comment]
Test report by @Micket
**SUCCESS**
Build succeeded for 5 out of 5 (2 easyconfigs in total)
vera-skylake-build - Linux Rocky Linux 8.9, x86_64, Intel Xeon Processor (Skylake, IBRS, no TSX), Python 3.6.8
See https://gist.github.com/Micket/98c7e066c9f4cc79fde6c399d8cad789 for a full test report.

**Comment by smoors** [comment]
Going in, thanks @sassy-crick!

**Pull request merged**
