### PR TITLE
Add finalfit and gtsummary to R >= 4.0.4

### PR DESCRIPTION
**Pull request by verdurin**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by verdurin** [comment]
@boegelbot please test @ generoso
EB_ARGS="--skip"

**Comment by verdurin** [comment]
Test report by @verdurin
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
nuc.lan - Linux Fedora 33, x86_64, Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz, Python 3.9.5
See https://gist.github.com/7bf8982cd43b399492c48ef83ef31644 for a full test report.

**Review by boegel — CHANGES_REQUESTED** [review]
@verdurin For consistency, please also add these to the other R 4.0.x easyconfigs using `foss/2020b`, as well as R 4.1.0.

I can take care of a full test report.

**Comment by verdurin** [comment]
@boegel I was waiting for your admonitory message...
Doesn't make sense to go earlier than `4.0.4` owing to the dependency versions. I will add it to the others.

**Comment by boegel** [comment]
> @boegel I was waiting for your admonitory message...
> Doesn't make sense to go earlier than `4.0.4` owing to the dependency versions. I will add it to the others.

This requires newer versions of R packages than included with the older R 4.0.x easyconfigs you mean?
Can you elaborate on which ones (just for future reference)?

**Comment by verdurin** [comment]
> > @boegel I was waiting for your admonitory message...
> > Doesn't make sense to go earlier than `4.0.4` owing to the dependency versions. I will add it to the others.
> 
> This requires newer versions of R packages than included with the older R 4.0.x easyconfigs you mean?
> Can you elaborate on which ones (just for future reference)?

I think `dplyr` was the main one.

**Comment by branfosj** [comment]
@boegelbot please test @ generoso
EB_ARGS="--skip"

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 5 out of 5 (5 easyconfigs in total)
node3302.joltik.os - Linux centos linux 7.9.2009, x86_64, Intel(R) Xeon(R) Gold 6242 CPU @ 2.80GHz (cascadelake), Python 3.6.8
See https://gist.github.com/dda3b96b12a70b0913b78b7cf587c0b8 for a full test report.

**Review by boegel — APPROVED** [review]

**Comment by boegel** [comment]
Going in, thanks @verdurin!

**Comment by boegel** [comment]
Going in, thanks @verdurin!

**Comment by boegel** [comment]
Going in, thanks @verdurin!

**Comment by boegel** [comment]
Going in, thanks @verdurin!

**Comment by boegel** [comment]
Going in, thanks @verdurin!

**Comment by boegel** [comment]
Going in, thanks @verdurin!

**Pull request merged**
