### PR TITLE
{bio}[foss/2018b] FSL v5.0.11 w/ Python 3.6.6

### PR DESCRIPTION
**Pull request by boegel**
(created using `eb --new-pr`)
requires ~~#6997~~ (VTK)

### CODE REVIEW

**Comment by vanzod** [comment]
Trigger test after merge of #6997

**Comment by vanzod** [comment]
Test report by @vanzod
**FAILED**
Build succeeded for 0 out of 1 (1 easyconfigs in this PR)
cermis - Linux debian 9.5, Intel(R) Xeon(R) CPU           E5620  @ 2.40GHz, Python 2.7.13
See https://gist.github.com/3e39d54128c558a4248e53de264f157c for a full test report.

**Comment by vanzod** [comment]
`fslio` failed with:
```
/bin/sh: 10: tclsh: not found
```
`Tcl` is needed to provide `tclsh` in systems without it.

**Comment by boegel** [comment]
@vanzod `Tk` is already listed as a dependency, which in turns depends on `Tcl`, so that should be covered already?

Maybe your `Tcl` installation doesn't have the `tclsh` symlink (cfr. #6915)?

**Comment by vanzod** [comment]
Test report by @vanzod
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
cermis - Linux debian 9.5, Intel(R) Xeon(R) CPU           E5620  @ 2.40GHz, Python 2.7.13
See https://gist.github.com/8fbca73ed75095428521ad876bba1660 for a full test report.

**Comment by vanzod** [comment]
Going in, thanks @boegel!

**Pull request merged**
