### PR TITLE
{base}[foss/2023a] PennyLane v0.37.0 w/ CUDA 12.1.1

### PR DESCRIPTION
**Pull request by lcniel**
(created using `eb --new-pr`)

Depends on:
- #21354
- #21355

### CODE REVIEW

**Comment by lcniel** [comment]
Test report by @lcniel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
alvis4-28 - Linux Rocky Linux 8.9, x86_64, Intel(R) Xeon(R) Gold 6338 CPU @ 2.00GHz, 1 x NVIDIA NVIDIA A100-SXM4-40GB, 545.23.08, Python 3.6.8
See https://gist.github.com/lcniel/91e4130f2f9dd9d85a68e4f36a5abb54 for a full test report.

**Comment by lcniel** [comment]
Test report by @lcniel
**SUCCESS**
Build succeeded for 2 out of 2 (1 easyconfigs in total)
alvis3-04 - Linux Rocky Linux 8.9, x86_64, Intel(R) Xeon(R) Gold 6338 CPU @ 2.00GHz, 1 x NVIDIA NVIDIA A100-SXM4-40GB, 545.23.08, Python 3.6.8
See https://gist.github.com/lcniel/0c7690c9dfc44883f217466b19636800 for a full test report.

**Comment by lcniel** [comment]
Test report by @lcniel
**SUCCESS**
Build succeeded for 3 out of 3 (1 easyconfigs in total)
alvis2-18 - Linux Rocky Linux 8.9, x86_64, Intel(R) Xeon(R) Gold 6226R CPU @ 2.90GHz, 8 x NVIDIA Tesla T4, 560.35.03, Python 3.6.8
See https://gist.github.com/lcniel/4d83cbdd50f607f97e8655aba7982144 for a full test report.

**Comment by Micket** [comment]
@boegelbot please test @ jsc-zen3

**Review by Micket — APPROVED** [review]
lgtm

**Comment by Micket** [comment]
Going in, thanks @lcniel!

**Pull request merged**
