### PR TITLE
{bio}[GCCcore/8.3.0] Varlociraptor v1.5.0

### PR DESCRIPTION
**Pull request by cmeesters**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by cmeesters** [comment]
What is going on, here? Why should a contributor consider something like https://packages.microsoft.com/repos/microsoft-ubuntu-bionic-prod and the respective setups? And if so, how?

**Comment by boegel** [comment]
@cmeesters That was an issue in GitHub itself, fixed with https://github.com/easybuilders/easybuild-easyconfigs/pull/9492 (will be merged soon).

Once it is merged, `eb --sync-pr-with-develop 9491` is an easy way to fix the issue in this PR (or just fix the style issues once #9492 is merged).

**Comment by cmeesters** [comment]
not sure how to satisfy dependencies with futures and current easyconfigs overlapping, see PR 9523

**Comment by boegel** [comment]
I'm closing this PR, since this easyconfig should be redone using the new `Cargo` easyblock, so we have full control over the installation.
If not, the installation will break over time, as was the case with `bamtofastq` (cfr. #15636) before it changed to use the `Cargo` easyblock (see #17595 + https://github.com/easybuilders/easybuild-easyblocks/pull/2902)

**Pull request closed without merging**
