### PR TITLE
{bio}[GCCcore/13.3.0] tbl2asn v20230713

### PR DESCRIPTION
**Pull request by laraPPr**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by laraPPr** [comment]
Test report by @laraPPr
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
node4006.donphan.os - Linux RHEL 8.8, x86_64, Intel(R) Xeon(R) Gold 6240 CPU @ 2.60GHz, 1 x NVIDIA NVIDIA A2, 545.23.08, Python 3.6.8
See https://gist.github.com/laraPPr/968bcf22e579684b56142313fda1e0c8 for a full test report.

**Comment by boegel** [comment]
@boegelbot please test @ generoso

**Review by boegel — APPROVED** [review]
lgtm

**Comment by boegel** [comment]
@boegelbot please test @ generoso

**Comment by laraPPr** [comment]
Test report by @laraPPr
**FAILED**
Build succeeded for 0 out of 1 (1 easyconfigs in total)
node3108.skitty.os - Linux RHEL 9.4, x86_64, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz, Python 3.11.3
See https://gist.github.com/laraPPr/6c0fc38e9e787dd9d8a4963f5b0f6147 for a full test report.

**Comment by laraPPr** [comment]
Test report by @laraPPr
**FAILED**
Build succeeded for 0 out of 1 (1 easyconfigs in total)
node3108.skitty.os - Linux RHEL 9.4 (Plow), x86_64, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz, Python 3.9.18
See https://gist.github.com/laraPPr/4bf9cc6687e9b427a4257e92572c5d53 for a full test report.

**Comment by laraPPr** [comment]
> Test report by @laraPPr **FAILED** Build succeeded for 0 out of 1 (1 easyconfigs in total) node3108.skitty.os - Linux RHEL 9.4, x86_64, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz, Python 3.11.3 See https://gist.github.com/laraPPr/6c0fc38e9e787dd9d8a4963f5b0f6147 for a full test report.

Need to use develop of the easybuild framework. I've just retriggered the build.

**Comment by boegel** [comment]
@boegelbot please test @ jsc-zen3

**Comment by boegel** [comment]
@laraPPr Hmm, this looks like a missing dependency, perhaps?
```
tbl2asn: error while loading shared libraries: libidn.so.11: cannot open shared object file: No such file or directory
```

**Comment by laraPPr** [comment]
I picked a newer version of libidn and now it has this library `libidn.so.12` Not sure though what it is looking for the `libidn.so.11` if it is tbl2asn than I'll fall back to the older version

**Comment by laraPPr** [comment]
Test report by @laraPPr
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
node3163.skitty.os - Linux RHEL 9.4 (Plow), x86_64, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz, Python 3.9.18
See https://gist.github.com/laraPPr/c3f8a58adb87e332f3bde0093727fe55 for a full test report.

**Comment by laraPPr** [comment]
Test report by @laraPPr
**FAILED**
Build succeeded for 0 out of 1 (1 easyconfigs in total)
node4012.donphan.os - Linux RHEL 8.8, x86_64, Intel(R) Xeon(R) Gold 6240 CPU @ 2.60GHz, 1 x NVIDIA NVIDIA A2, 545.23.08, Python 3.11.3
See https://gist.github.com/laraPPr/fd289648613ad66e574a8ee5aca84e03 for a full test report.

**Comment by laraPPr** [comment]
@boegelbot please test @ jsc-zen3

**Comment by laraPPr** [comment]
@boegelbot please test @ generoso

**Comment by verdurin** [comment]
Test report by @verdurin
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
easybuild-el8.cloud.in.bmrc.ox.ac.uk - Linux Rocky Linux 8.10, x86_64, Intel Xeon Processor (Skylake, IBRS), Python 3.6.8
See https://gist.github.com/verdurin/be2bc6fb794565d5b646bb3760c13b83 for a full test report.

**Review by verdurin — APPROVED** [review]
Looks fine.

**Comment by verdurin** [comment]
Going in, thanks @laraPPr!

**Pull request merged**
