### PR TITLE
{toolchain}[gmpolf-2017.10]

### PR DESCRIPTION
**Pull request by rubendibattista**

### CODE REVIEW

**Comment by boegel** [comment]
@rubendibattista Missing easyconfig:

```
ScaLAPACK/2.0.2-gmpich-2017.08-OpenBLAS-0.2.20
```

**Comment by rubendibattista** [comment]
Ping

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 8 out of 8 (5 easyconfigs in this PR)
node2465.golett.os - Linux centos linux 7.4.1708, Intel(R) Xeon(R) CPU E5-2680 v3 @ 2.50GHz, Python 2.7.5
See https://gist.github.com/1f0cb8e69593bc502df73460f88c4c71 for a full test report.

**Comment by boegel** [comment]
Going in, thanks @rubendibattista!

**Pull request merged**
