### PR TITLE
{data}[fosscuda/2019b] GDAL v3.0.2 w/ Python 3.7.4

### PR DESCRIPTION
**Pull request by lexming**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by Micket** [comment]
Test report by @Micket
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
hebbe-c1 - Linux centos linux 7.8.2003, x86_64, Intel Core Processor (Haswell, no TSX), Python 2.7.5
See https://gist.github.com/5276b7ea2f951b2a8db592f6dac321f2 for a full test report.

**Comment by Micket** [comment]
Going in, thanks @lexming!

**Comment by lexming** [comment]
Test report by @lexming
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
node152.hydra.os - Linux centos linux 7.7.1908, x86_64, Intel(R) Xeon(R) CPU E5-2680 v2 @ 2.80GHz, Python 2.7.5
See https://gist.github.com/4f30bb7082dbdcd28a52f7bf3bce44b7 for a full test report.

**Comment by lexming** [comment]
@Micket that was quick! thanks :+1:

**Pull request merged**
