### PR TITLE
{cae} [intel/2016a] OpenFOAM 3.0+

### PR DESCRIPTION
**Pull request by wpoely86**
~~Currently without paraview (working on it).~~

### CODE REVIEW

**Comment by boegel** [comment]
@wpoely86: please use the `libX` stack in `develop` that doesn't have the Python dep anymore (done by @hajgato)

**Comment by wpoely86** [comment]
Test report by @wpoely86
**FAILED**
Build succeeded for 2 out of 4 (1 easyconfigs in this PR)
node2604.swalot.os - Linux centos linux 7.2.1511, Intel(R) Xeon(R) CPU E5-2660 v3 @ 2.60GHz, Python 2.7.5
See https://gist.github.com/355384e7a96b6c940f06 for a full test report.

**Comment by wpoely86** [comment]
Test report by @wpoely86
**FAILED**
Build succeeded for 0 out of 2 (1 easyconfigs in this PR)
node2604.swalot.os - Linux centos linux 7.2.1511, Intel(R) Xeon(R) CPU E5-2660 v3 @ 2.60GHz, Python 2.7.5
See https://gist.github.com/d8647089f3c15c876280 for a full test report.

**Comment by hajgato** [comment]
@wpoely86 I would drop the `-Mesa-11.1.2` suffix from everywhere (no other version with `2016a` toolchains, use the existing `libGLU-9.0.0-intel-2016a.eb` easyconfig, I think the `-GMP-6.1.0` suffix is not necessary for `MPFR` (as we have only one version), normally you do not need the `xcb-proto` python version, use the dummy `xcb-proto-1.11.eb`, but only as a buildep, if it is needed.

**Comment by boegel** [comment]
@wpoely86 status?

**Comment by boegel** [comment]
@wpoely86 ping?

**Comment by wpoely86** [comment]
Lets close this one and redo it on top of 2016b.

**Comment by boegel** [comment]
Closing, no longer relevant (as discussed with @wpoely86 already)

**Pull request closed without merging**
