### PR TITLE
find correct Python for MDI

### PR DESCRIPTION
**Pull request by branfosj**
(created using `eb --new-pr`)

### CODE REVIEW

**Review by Micket — DISMISSED** [review]
lgtm

**Comment by Micket** [comment]
Test report by @Micket
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in total)
vera-gpu1 - Linux Rocky Linux 8.9, x86_64, Intel(R) Xeon(R) Gold 6130 CPU @ 2.10GHz, 1 x NVIDIA Tesla V100-SXM2-32GB, 545.23.08, Python 3.6.8
See https://gist.github.com/Micket/ba7705f0f72840c4ad9cdda870d2cdc6 for a full test report.

**Comment by branfosj** [comment]
Test report by @branfosj
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in total)
bear-pg0105u03a - Linux RHEL 8.6, x86_64, Intel(R) Xeon(R) Platinum 8360Y CPU @ 2.40GHz (icelake), Python 3.6.8
See https://gist.github.com/branfosj/2aea65e4d95c34ebc336fd335cf55af4 for a full test report.

**Review by Micket — APPROVED** [review]
lgtm

**Comment by Micket** [comment]
Test report by @Micket
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in total)
vera-gpu1 - Linux Rocky Linux 8.9, x86_64, Intel(R) Xeon(R) Gold 6130 CPU @ 2.10GHz, 1 x NVIDIA Tesla V100-SXM2-32GB, 545.23.08, Python 3.6.8
See https://gist.github.com/Micket/31667f71e3d1ab69de058e019b774fcc for a full test report.

**Comment by verdurin** [comment]
Test report by @verdurin
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in total)
easybuild-c7.novalocal - Linux CentOS Linux 7.9.2009, x86_64, Intel Xeon Processor (Skylake, IBRS), Python 3.6.8
See https://gist.github.com/verdurin/d3cd1fc271af3f77078bd6e6a3c733e6 for a full test report.

**Comment by verdurin** [comment]
Going in, thanks @branfosj!

**Comment by boegel** [comment]
@branfosj Does this mean that https://github.com/easybuilders/easybuild-easyblocks/pull/3088 isn't working as intended?

**Comment by branfosj** [comment]
> @branfosj Does this mean that [easybuilders/easybuild-easyblocks#3088](https://github.com/easybuilders/easybuild-easyblocks/pull/3088) isn't working as intended?

It is not picking the newest for me and it is not picking the first in the path. Based on the below tests, https://github.com/easybuilders/easybuild-easyblocks/pull/3088 has broken this for me.

Correct Python:
* Without this PR and without https://github.com/easybuilders/easybuild-easyblocks/pull/3088
* With this PR and without https://github.com/easybuilders/easybuild-easyblocks/pull/3088
* With this PR and with https://github.com/easybuilders/easybuild-easyblocks/pull/3088
```
-- Found Python: /rds/projects/2017/branfosj-rse/easybuild/EL8-ice/software/Python/3.11.3-GCCcore-12.3.0/bin/python3.11 (found version "3.11.3") found components: Interpreter Development Development.Module Development.Embed
```

Incorrect Python:
* Without this PR and with https://github.com/easybuilders/easybuild-easyblocks/pull/3088
```
-- Found Python: /rds/projects/2017/branfosj-rse/easybuild/venv-dev-EL8/bin/python3 (found version "3.6.8") found components: Interpreter Development Development.Module Development.Embed
```

**Comment by boegel** [comment]
@branfosj Can you open an issue on this? Keeping track of things in a merged PR is something we should avoid...

**Pull request merged**
