### PR TITLE
fix location of lock file in mujoco-py v2.1.2.14

### PR DESCRIPTION
**Pull request by lexming**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by lexming** [comment]
@boegelbot: please test @ generoso

**Comment by lexming** [comment]
Test report by @lexming
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
node300.hydra.os - Linux centos linux 7.9.2009, x86_64, Intel(R) Xeon(R) Gold 6148 CPU @ 2.40GHz, Python 2.7.5
See https://gist.github.com/22b870dc2ca2ab45c2ff3a110438f7f0 for a full test report.

**Comment by migueldiascosta** [comment]
@lexming is it possible to add a `sanity_check_command` that makes sure this is working?

**Comment by lexming** [comment]
@migueldiascosta the issue in https://github.com/easybuilders/easybuild-easyconfigs/pull/14779#issuecomment-1031184094 was triggered by just running `import mujoco_py`. So the default sanity check is ok. The real sanity check is @boegel and his weird systems with read-only installation dirs.

**Comment by boegel** [comment]
> The real sanity check is @boegel and his weird systems with read-only installation dirs.

@lexming That's actually a specific configuration that I use to catch trouble like this... ;)

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
node3106.skitty.os - Linux CentOS Linux 7.9.2009, x86_64, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz, Python 3.6.8
See https://gist.github.com/6dad1cca7e6f1fc1a7eb103c29258b81 for a full test report.

**Comment by boegel** [comment]
Going in, thanks @lexming!

**Pull request merged**
