### PR TITLE
{vis}[GCCcore/6.4.0] X11 v20170314

### PR DESCRIPTION
**Pull request by reedts**
(created using `eb --new-pr`)
depends on #5287

### CODE REVIEW

**Comment by boegel** [comment]
@reedts Did you check whether new versions are available for any of the components?

**Comment by reedts** [comment]
@boegel I did not. The idea behind this was, to just build the X11 with GCC 6.4.0 in order to make it available in the toolchain. I'm currently working on an updated version but have to check each component for updates, so this will take time. You can of course close this, if you don't want the "old" version in this toolchain an wait for my newer version.

**Comment by boegel** [comment]
@reedts I'd prefer updating to the most recent components while also bumping it to `GCCcore/6.4.0` (otherwise bumping the component versions is going to be keep being postponed...).

I know this is a painful process, I'm working on a new feature to let `eb` report all available versions and even to update them automagically for a given easyconfig...

**Comment by reedts** [comment]
@boegel That is imo a killer feature that would make things much much easier. Nevertheless, I will investigate further for new versions of the components and post a new pr when ready.

**Comment by boegel** [comment]
@reedts I went through the trouble of putting together an updated `X11` bundle for `GCCcore/6.4.0`, so this can be closed imho...

**Comment by reedts** [comment]
@boegel Thank you for your efforts! Let's close this.

**Pull request closed without merging**
