### PR TITLE
{bio}[fosscuda/2019b] Bonito v0.3.5 w/ Python 3.7.4

### PR DESCRIPTION
**Pull request by boegel**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
node3309.joltik.os - Linux centos linux 7.9.2009, x86_64, Intel(R) Xeon(R) Gold 6242 CPU @ 2.80GHz (cascadelake), Python 3.6.8
See https://gist.github.com/f84f78505d87761728c7741b12980e43 for a full test report.

**Comment by smoors** [comment]
@boegelbot: please test @ generoso

**Comment by boegel** [comment]
@smoors I suspect that'll end in tears, because of existing lock files, but we'll see...

I can retrigger it when deps (like `magma`) are installed (there's jobs already running for that).

**Comment by boegel** [comment]
@smoors Testing this on `generoso` won't work, the `CuPy` dependency basically requires a GPU system (or at least one with CUDA drivers installed), otherwise you run into:

```
ImportError: libcuda.so.1: cannot open shared object file: No such file or directory
```

**Comment by smoors** [comment]
ok, I've submitted a test job on our cluster but that's gonna take a while as our gpu nodes are in heavy use atm.

**Comment by smoors** [comment]
Test report by @smoors
**SUCCESS**
Build succeeded for 6 out of 6 (1 easyconfigs in total)
node253.hydra.os - Linux centos linux 7.9.2009, x86_64, Intel(R) Xeon(R) CPU E5-2650 v4 @ 2.20GHz (broadwell), Python 2.7.5
See https://gist.github.com/e947990b99eac922b77d757ef80bfe44 for a full test report.

**Review by smoors — APPROVED** [review]
lgtm

**Comment by smoors** [comment]
Going in, thanks @boegel!

**Pull request merged**
