### PR TITLE
Fix Clang 9.0.1 patch

### PR DESCRIPTION
**Pull request by Flamefire**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by Flamefire** [comment]
Test report by @Flamefire
**SUCCESS**
Build succeeded for 3 out of 3 (3 easyconfigs in total)
n1427 - Linux RHEL 8.7 (Ootpa), x86_64, Intel(R) Xeon(R) Platinum 8470 (icelake), Python 3.8.13
See https://gist.github.com/Flamefire/b120741c6225427daa28825e95920871 for a full test report.

**Review by ocaisa — APPROVED** [review]

**Comment by ocaisa** [comment]
This is a patch for Power, but the build report is for Intel...does it still work on Power?

**Comment by ocaisa** [comment]
@boegelbot please test @ generoso

**Review by ocaisa — APPROVED** [review]

**Comment by ocaisa** [comment]
Going in, thanks @Flamefire

**Pull request merged**
