### PR TITLE
add missing OpenSSL dependency to Rust 1.52.1

### PR DESCRIPTION
**Pull request by boegel**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by boegel** [comment]
I've enhanced `boegelbot` so that it checks for direct linking to the system OpenSSL libraries using the new `banned_linked_shared_libs` feature, see https://github.com/boegel/boegelbot/commit/dbd3e88fc867e2d9b981ba89c22f080e22e520a9...

**Comment by boegel** [comment]
@boegelbot please test @ generoso
CORE_CNT=16

**Review by Micket — APPROVED** [review]
lgtm

**Comment by verdurin** [comment]
Test report by @verdurin
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
easybuild-c7.novalocal - Linux centos linux 7.9.2009, x86_64, Intel Xeon Processor (Skylake, IBRS), Python 3.6.8
See https://gist.github.com/6683452d0b3a449e30a763a423222ef1 for a full test report.

**Comment by Micket** [comment]
Going in, thanks @boegel!

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
select-pika-c6gd-2xlarge-0002 - Linux centos linux 8.3.2011, AArch64, ARM UNKNOWN (graviton2), Python 3.6.8
See https://gist.github.com/c47231fe050f98d57ecb6988f3d6ff4f for a full test report.

**Pull request merged**
