### PR TITLE
{bio}[fosscuda/2020b] ctffind v4.1.14

### PR DESCRIPTION
**Pull request by akesandgren**
(created using `eb --new-pr`)

Depends on ~~#12585~~

### CODE REVIEW

**Review by boegel — APPROVED** [review]
lgtm

**Comment by akesandgren** [comment]
@boegelbot Please test @ generoso

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
node3505.doduo.os - Linux RHEL 8.2, x86_64, AMD EPYC 7552 48-Core Processor (zen2), Python 3.6.8
See https://gist.github.com/890949457e00d554f286297308ce3d64 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 6 out of 6 (1 easyconfigs in total)
node3304.joltik.os - Linux centos linux 7.9.2009, x86_64, Intel(R) Xeon(R) Gold 6242 CPU @ 2.80GHz (cascadelake), Python 3.6.8
See https://gist.github.com/6e90f29bc647e3e9ac0af9d3c7f1079e for a full test report.

**Comment by boegel** [comment]
Going in, thanks @akesandgren!

**Pull request merged**
