### PR TITLE
Enable EGL in recent libepoxy ECs

### PR DESCRIPTION
**Pull request by jfgrimm**
(created using `eb --new-pr`)
Fixes issue #11197. libepoxy already loads Mesa, which depends on libglvnd and provides libEGL.

### CODE REVIEW

**Comment by Micket** [comment]
My only worry, was there *any* good reason to ever disable this? I mean normally we enable anything we, and EGL is good stuff, so, why..?

**Comment by Micket** [comment]
Test report by @Micket
**SUCCESS**
Build succeeded for 4 out of 4 (4 easyconfigs in total)
alvis-c1 - Linux centos linux 7.9.2009, x86_64, Intel Xeon Processor (Skylake), Python 3.6.8
See https://gist.github.com/3ffbf1cab4fc1e6a5bba0ecd0a864ea2 for a full test report.

**Review by Micket — CHANGES_REQUESTED** [review]
Actually, please add in `egl.h` and `egl_generated.h` in the sanity check as well for consistency.

**Comment by jfgrimm** [comment]
@Micket It looks like `libglvnd` was only added to the Mesa easyconfigs as a dependency from GCCcore-9.3.0 onwards, and older versions built without EGL.

**Review by Micket — APPROVED** [review]
lgtm

**Comment by Micket** [comment]
@bogelbot please test @ generoso

**Comment by Micket** [comment]
Test report by @Micket
**SUCCESS**
Build succeeded for 3 out of 3 (3 easyconfigs in total)
alvis-c1 - Linux centos linux 7.9.2009, x86_64, Intel Xeon Processor (Skylake), Python 3.6.8
See https://gist.github.com/9f8fd5b96d8229c615a46bc1ebe0649c for a full test report.

**Review by Micket — CHANGES_REQUESTED** [review]
You accidentally removed `libepoxy-1.5.4-GCCcore-8.3.0.eb` completely, (and I somehow missed that when reviewing first)

**Comment by jfgrimm** [comment]
> You accidentally removed `libepoxy-1.5.4-GCCcore-8.3.0.eb` completely, (and I somehow missed that when reviewing first)

Sorry! I only meant to remove it from this PR (since the Mesa it depends on was built without EGL), not delete it. Should be fixed now

**Review by Micket — APPROVED** [review]
lgtm

**Comment by Micket** [comment]
@boegelbot please test @ generoso

**Comment by Micket** [comment]
Test report by @Micket
**SUCCESS**
Build succeeded for 3 out of 3 (3 easyconfigs in total)
alvis-c1 - Linux centos linux 7.9.2009, x86_64, Intel Xeon Processor (Skylake), Python 3.6.8
See https://gist.github.com/771c9f13ef75f5186a14240482b6401b for a full test report.

**Comment by Micket** [comment]
Going in, thanks @jfgrimm!

**Pull request merged**
