### PR TITLE
{bio}[foss/2021a] CheckM v1.1.3 w/ Python 3.9.5

### PR DESCRIPTION
**Pull request by bedroge**
(created using `eb --new-pr`)

Depends on:
- [x] #14473

### CODE REVIEW

**Comment by bedroge** [comment]
Test report by @bedroge
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
pg-interactive.hpc.rug.nl - Linux centos linux 7.9.2009, x86_64, Intel(R) Xeon(R) CPU E5-2680 v3 @ 2.50GHz, Python 3.6.8
See https://gist.github.com/43879fc914670d9daf7208f6f7c0f782 for a full test report.

**Comment by migueldiascosta** [comment]
@boegelbot please test @ generoso

**Review by migueldiascosta — APPROVED** [review]
lgtm

**Comment by migueldiascosta** [comment]
Going in, thanks @bedroge!

**Pull request merged**
