### PR TITLE
remove PYPI_SOURCE source URL from easyconfigs using 2020a toolchain

### PR DESCRIPTION
**Pull request by Flamefire**
This is no longer required as it became the default with easybuilders/easybuild-easyblocks#2364

Tests should (and mine were) be done with e.g. `eb --from-pr 12452 --rebuild --fetch --force-download --sourcepath=/dev/shm/sources --upload-test-report` to only test the download and of course with latest develop easyblocks

### CODE REVIEW

**Comment by Flamefire** [comment]
Test report by @Flamefire
**FAILED**
Build succeeded for 118 out of 121 (121 easyconfigs in total)
taurusa9 - Linux centos linux 7.7.1908, x86_64, Intel(R) Xeon(R) CPU E5-2603 v4 @ 1.70GHz (broadwell), Python 2.7.5
See https://gist.github.com/00d6bd70ef36109d6e204239e66275a6 for a full test report.

**Comment by Flamefire** [comment]
Test report by @Flamefire
**SUCCESS**
Build succeeded for 121 out of 121 (121 easyconfigs in total)
taurusa9 - Linux centos linux 7.7.1908, x86_64, Intel(R) Xeon(R) CPU E5-2603 v4 @ 1.70GHz (broadwell), Python 2.7.5
See https://gist.github.com/2b130fe3b2dd9a5dbd60f6c04facacde for a full test report.

**Comment by verdurin** [comment]
Test report by @verdurin
**FAILED**
Build succeeded for 401 out of 406 (121 easyconfigs in total)
easybuild-c7.novalocal - Linux centos linux 7.9.2009, x86_64, Intel Xeon Processor (Skylake, IBRS), Python 3.6.8
See https://gist.github.com/eccf0a90027d6d150658bad45f05bbcb for a full test report.

**Comment by verdurin** [comment]
The build failures were unrelated to this PR.

**Comment by verdurin** [comment]
Going in, thanks @Flamefire!

**Pull request merged**
