### PR TITLE
{bio}[foss/2020a] Trycycler v0.3.3, edlib v1.3.8.post1 w/ Python 3.8.2

### PR DESCRIPTION
**Pull request by boegel**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by verdurin** [comment]
@boegelbot please test @ generoso

**Comment by verdurin** [comment]
@boegel any change of test reports from your side?

**Review by smoors — DISMISSED** [review]
@boegel since you also have `edlib` with intel toolchain (I asked to move it to `iccifort` after the merge https://github.com/easybuilders/easybuild-easyconfigs/pull/10470#issuecomment-687109681), can you move this version to `GCC`?

**Comment by verdurin** [comment]
@boegel any thoughts on the comments by @smoors ?

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in this PR)
node3404.kirlia.os - Linux centos linux 7.8.2003, x86_64, Intel(R) Xeon(R) Gold 6240 CPU @ 2.60GHz (cascadelake), Python 2.7.5
See https://gist.github.com/501eb652f45e20013060b6b038746186 for a full test report.

**Comment by boegel** [comment]
@verdurin Should be good to go now...

**Comment by verdurin** [comment]
Test report by @verdurin
**SUCCESS**
Build succeeded for 1 out of 1 (2 easyconfigs in this PR)
nuc.lan - Linux Fedora 32, x86_64, Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz, Python 3.8.5
See https://gist.github.com/97725e521ffe786292a9e0e04e5794f8 for a full test report.

**Comment by verdurin** [comment]
Going in, thanks @boegel!

**Pull request merged**
