### PR TITLE
{ai}[foss/2023a] accelerate v0.33.0 w/ CUDA 12.1.1

### PR DESCRIPTION
**Pull request by pavelToman**
(created using `eb --new-pr`)
resolves https://github.com/vscentrum/vsc-software-stack/issues/370

### CODE REVIEW

**Comment by pavelToman** [comment]
@boegelbot please test @ generoso

**Comment by pavelToman** [comment]
@boegelbot please test @ jsc-zen3

**Review by smoors — APPROVED** [review]
lgtm

**Comment by smoors** [comment]
Going in, thanks @pavelToman!

**Comment by pavelToman** [comment]
@boegelbot please test @ jsc-zen3-a100

**Pull request merged**
