### PR TITLE
fix broken patch file for recent GPAW versions

### LINKED ISSUE #14598: Mistake in GPAW-20.1.0-Add-Easybuild-configuration-files.patch
Hi,

We've spotted a mistake in GPAW-20.1.0-Add-Easybuild-configuration-files.patch which is only apparent if you are doing a foss build of GPAW and add ELPA. Line 27 of https://github.com/easybuilders/easybuild-easyconfigs/blob/develop/easybuild/easyconfigs/g/GPAW/GPAW-20.1.0-Add-Easybuild-configuration-files.patch has:

`@@ -0,0 +1,49 @@
`

However this results in a truncated patch that ends at:

```
+    library_dirs.append(os.path.join(elpa, 'lib'))
+    extra_link_args += ['-Wl,-rpath={}/lib'.format(elpa)]
```

and doesn't add the modified include paths. There is a quick fix of changing the line to 

`@@ -0,0 +1,53 @@
`

and adjusting the checksum accordingly (worked for me) but wasn't sure if there's a quick way of updating the patch and the checksums in the easyconfig repo.

### PR DESCRIPTION
**Pull request by boegel**
(created using `eb --new-pr`)
fixes #14598

### CODE REVIEW

**Comment by boegel** [comment]
@boegelbot please test @ generoso
CORE_CNT=16

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 11 out of 11 (11 easyconfigs in total)
node3104.skitty.os - Linux centos linux 7.9.2009, x86_64, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz (skylake_avx512), Python 3.6.8
See https://gist.github.com/2de8cd2ccb5a10671cd630aed395f4d8 for a full test report.

**Review by bedroge — APPROVED** [review]
lgtm

**Comment by bedroge** [comment]
Going in, thanks @boegel!

**Pull request merged**
