### PR TITLE
{lib}[GCCcore/10.3.0] libxslt v1.1.34

### PR DESCRIPTION
**Pull request by maxim-masterov**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by verdurin** [comment]
@boegelbot please test @ generoso

**Comment by Micket** [comment]
F.y.i. this already got merged in another PR a short while ago

**Comment by maxim-masterov** [comment]
> F.y.i. this already got merged in another PR a short while ago

didn't find it

**Comment by Micket** [comment]
It was part of a bundle, I just wanted to let @verdurin know that this will fail to merge since there since he already merged a libxslt shortly before. I think we can only close this one.

**Pull request closed without merging**
