### PR TITLE
set JULIA_DEPOT_PATH in Julia easyconfigs with default value

### LINKED ISSUE #17961: Remove user directory from JULIA_DEPOT_PATH during installation
The easyconfig of Julia adds `~/.julia` to `JULIA_DEPOT_PATH` to allow users to add their own stuff on top of the installation. This is picked during installation though, which might lead to issues if the user has custom environments. See https://github.com/easybuilders/easybuild-easyconfigs/pull/16720#issuecomment-1558838707

Solution: strip down  `JULIA_DEPOT_PATH` during installation.

Note: this still applies after the switch to `JULIA_LOAD_PATH` proposed in https://github.com/easybuilders/easybuild-easyconfigs/issues/17455

### PR DESCRIPTION
**Pull request by lexming**
(created using `eb --new-pr`)

As reported in #17455, user depot should be the top entry in `JULIA_DEPOT_PATH`. This PR fixes that issue by simply setting `JULIA_DEPOT_PATH` to `:`, which is the default value with user's depot as top entry.

Having `JULIA_DEPOT_PATH` defined in the base Julia easyconfigs is needed for the changes in https://github.com/easybuilders/easybuild-easyblocks/pull/2935 to fix #17961

### CODE REVIEW

**Comment by lexming** [comment]
@boegelbot: please test @ generoso

**Comment by lexming** [comment]
@boegelbot please test @ jsc-zen2

**Comment by exaexa** [comment]
Hi all,
I just created https://github.com/easybuilders/easybuild-easyconfigs/pull/17995 which might be similar or straight out duplicated of this (didn't check the list properly, sorry).

One point to discuss: do we _really_ want to point to the "shared" julia depots? Since 1.9.0 Julia will actually recompile much of the base packages anyway (depending on dependency updates etc), so I'd say that any attempts to push a package directory to it might be completely vain. The other concern is that the `..../share/julia` directory that EB now points the depots to **is not a proper julia depot** and can't really be used for anything (at least on all Julia versions I tried).

And one note: I'm not sure if ~ in the configs here works as intended (especially for the history dir -- see the other PR).

Thanks!

**Comment by lexming** [comment]
@exaexa I checked your PR #17995 and as I commented there, entirely unsetting `JULIA_DEPOT_PATH` is not an option because then any other `JuliaPackage` loaded on top of Julia will reset the `DEPOT_PATH` and disable the user's depot.

I agree with you that using `~` is dangerous, so I simplified my approach by just setting `JULIA_DEPOT_PATH` to `:`. This is equivalent to use the default `DEPOT_PATH` and is compatible with loading `JuliaPackages` distributed with EasyBuild.

Let me know if this approach works for you.

**Comment by lexming** [comment]
@boegelbot: please test @ generoso

**Comment by lexming** [comment]
@boegelbot: please test @ generoso

**Comment by lexming** [comment]
@boegelbot please test @ jsc-zen2

**Review by branfosj — APPROVED** [review]

**Comment by branfosj** [comment]
Test report by @branfosj
**SUCCESS**
Build succeeded for 12 out of 12 (12 easyconfigs in total)
bear-pg0105u03a.bear.cluster - Linux RHEL 8.6, x86_64, Intel(R) Xeon(R) Platinum 8360Y CPU @ 2.40GHz (icelake), Python 3.6.8
See https://gist.github.com/branfosj/5ce7226cec7a9240b112197fbc33dd99 for a full test report.

**Comment by branfosj** [comment]
Going in, thanks @lexming!

**Pull request merged**
