### PR TITLE
{devel}[GCCcore/8.3.0] Bazel v3.4.1

### PR DESCRIPTION
**Pull request by Flamefire**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
generoso-x-1 - Linux centos linux 8.2.2004, x86_64, Intel(R) Xeon(R) CPU E5-2667 v3 @ 3.20GHz (haswell), Python 3.6.8
See https://gist.github.com/b2feaa23147206a014448525f37ad060 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
node3411.kirlia.os - Linux centos linux 7.8.2003, x86_64, Intel(R) Xeon(R) Gold 6240 CPU @ 2.60GHz (cascadelake), Python 2.7.5
See https://gist.github.com/030319e08ae925f37913fc377f28ea48 for a full test report.

**Comment by Flamefire** [comment]
Erm, WTF is this?

> ERROR: Build of /home/runner/work/easybuild-easyconfigs/easybuild-easyconfigs/easybuild/easyconfigs/m/M4/M4-1.4.18.eb failed (err: 'build failed (first 300 chars): SSL issues with urllib2. If you are using RHEL/CentOS 6.x please install the python-requests and pyOpenSSL RPM packages and try again.')

**Comment by boegel** [comment]
@Flamefire Download issue when trying to do an `M4` test install. Where are you seeing this pop up?

**Comment by Flamefire** [comment]
On the failed CI here: https://github.com/easybuilders/easybuild-easyconfigs/pull/11086/checks?check_run_id=970050330

**Comment by boegel** [comment]
@Flamefire Looks like a consistent problems in recent PRs, but only for one particular configuration (which doesn't make much sense). I'm looking into it.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
node2481.golett.os - Linux centos linux 7.8.2003, x86_64, Intel(R) Xeon(R) CPU E5-2680 v3 @ 2.50GHz (haswell), Python 2.7.5
See https://gist.github.com/12dafb3fe9fe5ac2ecfba4d8e8ff98fc for a full test report.

**Comment by boegel** [comment]
Going in, thanks @Flamefire!

**Pull request merged**
