### PR TITLE
{bio}[foss/2022a] dRep v3.4.2 w/ Python 3.10.4

### PR DESCRIPTION
**Pull request by bedroge**
(created using `eb --new-pr`)

Requires:

- [x] #17500 
- [x] #17501 
- [x] #17502

### CODE REVIEW

**Comment by bedroge** [comment]
Test report by @bedroge
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
bob-Latitude-5300 - Linux Ubuntu 22.04, x86_64, Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz, Python 3.10.6
See https://gist.github.com/b3f09b9eaa4b0db4d5c205f61a4c5c19 for a full test report.

**Comment by bedroge** [comment]
@boegelbot please test @ generoso

**Comment by bedroge** [comment]
@boegelbot please test @ jsc-zen2

**Comment by bedroge** [comment]
@boegelbot please test @ generoso

**Comment by casparvl** [comment]
Test report by @casparvl
**FAILED**
Build succeeded for 4 out of 6 (1 easyconfigs in total)
tcn375.local.snellius.surf.nl - Linux Rocky Linux 8.7, x86_64, AMD EPYC 7H12 64-Core Processor, Python 3.6.8
See https://gist.github.com/1db7beb6d6f0f3552cd8be1c2662c7c1 for a full test report.

**Comment by casparvl** [comment]
So, I normally wouldn't complain about dependencies that don't build, except that this is from [your own PR](https://github.com/easybuilders/easybuild-easyconfigs/pull/17502) that was merged three days ago...

It doesn't build with `RPATH`, since it users `MakeCp`. I think you used it since it makes it convenient to list the files you want to copy. However, I'm wondering if you can use `binary` (or something derived from `binary`), as this is essentially a binary installation. `binary` skips the `RPATH` sanity check, as it knows that `RPATH` can not, and will not be set on these installations ([see here](https://github.com/easybuilders/easybuild-easyblocks/blob/fce1775ad011a9ccc3ad6963cbd6f350af6c3301/easybuild/easyblocks/generic/binary.py#L135))

Either that, or we'd have to make more fundamental changes to [easyblock](https://github.com/easybuilders/easybuild-framework/blob/9b480c8b7d4e7981feddd842efbb867dc053f388/easybuild/framework/easyblock.py#L3062) and create a keyword that allows skipping the `sanity_check_rpath(self, rpath_dirs=None):` - but that's a pretty fundamental change and I'm not sure if I'm in favour of that.

**Comment by bedroge** [comment]
Nice catch @casparvl, thanks! Actually I do need the RPATH support for our new software stack, but I hadn't built it that way yet. I made a PR to fix this: #17536.

**Comment by casparvl** [comment]
Test report by @casparvl
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
tcn1.local.snellius.surf.nl - Linux Rocky Linux 8.7, x86_64, AMD EPYC 7H12 64-Core Processor, Python 3.6.8
See https://gist.github.com/6d70fbd9b5de5cc1f7adf59c1b62e816 for a full test report.

**Review by casparvl — APPROVED** [review]
Standard update, no surprises. Lgtm!

**Comment by casparvl** [comment]
Going in, thanks @bedroge!

**Pull request merged**
