### PR TITLE
{bio}[foss/2018b] HMMER 3.1b2

### PR DESCRIPTION
**Pull request by oneilsh**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by boegel** [comment]
@oneilsh I'm sorry for not picking up on this earlier, it seems like this one slipped under our radar...

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
node2668.swalot.os - Linux centos linux 7.5.1804, Intel(R) Xeon(R) CPU E5-2660 v3 @ 2.60GHz, Python 2.7.5
See https://gist.github.com/ff3649537ecb5dda108cd6236e5400ba for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
node3102.skitty.os - Linux centos linux 7.5.1804, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz, Python 2.7.5
See https://gist.github.com/a32bcd565d34d991d6aa29a149345cb7 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
node2107.delcatty.os - Linux centos linux 7.5.1804, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.7.5
See https://gist.github.com/98d25a7d6ff0ea5efe61c457ef204fb2 for a full test report.

**Comment by boegel** [comment]
Going in, thanks @oneilsh!

**Comment by oneilsh** [comment]
Yay! Thanks :D

**Pull request merged**
