### PR TITLE
{geo}[foss/2020b] WPS v4.2, WRF v4.2.2

### PR DESCRIPTION
**Pull request by akesandgren**
(created using `eb --new-pr`)

Depends on ~~#12592~~ and time/1.9 from ~~#11675~~

### CODE REVIEW

**Comment by akesandgren** [comment]
@boegelbot Please test @ generoso

**Comment by akesandgren** [comment]
Test report by @akesandgren
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in total)
b-cn0235.hpc2n.umu.se - Linux Ubuntu 20.04, x86_64, Intel(R) Xeon(R) CPU E5-2690 v4 @ 2.60GHz, Python 3.8.5
See https://gist.github.com/c52e5bd846f61e9fae971b17bfc9c501 for a full test report.

**Review by Micket — APPROVED** [review]
lgtm

**Comment by Micket** [comment]
Going in, thanks @akesandgren!

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in total)
node3601.doduo.os - Linux RHEL 8.2, x86_64, AMD EPYC 7552 48-Core Processor (zen2), Python 3.6.8
See https://gist.github.com/87d822113d9937f2af63a203b5fd7706 for a full test report.

**Pull request merged**
