### PR TITLE
{bio,lib}[GCCcore/12.2.0,gompi/2022b] BLAST+ v2.14.0, LMDB v0.9.29

### PR DESCRIPTION
**Pull request by eylenth**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by eylenth** [comment]
Test report by @eylenth
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in total)
by0owl.eu.seeds.basf.net - Linux RHEL 7.9, x86_64, Intel(R) Xeon(R) CPU E5-2620 v4 @ 2.10GHz (broadwell), Python 3.6.8
See https://gist.github.com/eylenth/8359c3a94796dca99c981cede6510a53 for a full test report.

**Comment by verdurin** [comment]
@boegelbot please test @ generoso

**Comment by verdurin** [comment]
@boegelbot please test @ jsc-zen2

**Comment by verdurin** [comment]
Going in, thanks @eylenth!

**Pull request merged**
