### PR TITLE
use more EasyBuild installed dependencies for TensorFlow 2.2.0

### PR DESCRIPTION
**Pull request by Flamefire**
Similar to #11109 this updates the TensorFlow 2.2.0 ECs to use more dependencies provided by EB

### CODE REVIEW

**Comment by Flamefire** [comment]
Test report by @Flamefire
**FAILED**
Build succeeded for 1 out of 2 (2 easyconfigs in this PR)
taurusml24 - Linux RHEL 7.6, POWER, 8335-GTX, Python 2.7.5
See https://gist.github.com/21727daba1de82bb19da2db5c8499279 for a full test report.

**Comment by Flamefire** [comment]
Test report by @Flamefire
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in this PR)
taurusml4 - Linux RHEL 7.6, POWER, 8335-GTX, Python 2.7.5
See https://gist.github.com/4181e3504a2cf1957e4a6afd6a10c33b for a full test report.

**Comment by Flamefire** [comment]
Test report by @Flamefire
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in this PR)
taurusa6 - Linux centos linux 7.7.1908, x86_64, Intel(R) Xeon(R) CPU E5-2603 v4 @ 1.70GHz, Python 2.7.5
See https://gist.github.com/4bfcf5e175bea5737da20f82855f9af4 for a full test report.

**Comment by Flamefire** [comment]
@boegel Might make sense to include these too in the 4.3.0

**Comment by Flamefire** [comment]
Test report by @Flamefire
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in this PR)
taurusml17 - Linux RHEL 7.6, POWER, 8335-GTX, Python 2.7.5
See https://gist.github.com/baaf1357b3f221f2b5a317f4461e43de for a full test report.

**Review by boegel — DISMISSED** [review]
lgtm

**Comment by boegel** [comment]
@boegelbot please test @ generoso

**Comment by boegel** [comment]
@Flamefire Your last commit reverts what I did in #11105 

Even though `Keras-Applications` is not required for TensorFlow itself, applications on top of TensorFlow often still expect it to be there...

**Comment by Flamefire** [comment]
Applications on top of TF should use `import tf.keras.applications` not `import keras_applications` as the latter seems to be an implementation detail so they could share this module between their repos (which they now no longer do).

I'd argue that this doesn't belong here because it is not a dependency of TF (anymore)

**Comment by boegel** [comment]
@Flamefire Point taken, agreed. This was done for [DeepGalaxy](https://github.com/maxwelltsai/DeepGalaxy) btw.

**Comment by Flamefire** [comment]
Test report by @Flamefire
**FAILED**
Build succeeded for 0 out of 2 (2 easyconfigs in this PR)
taurusml3 - Linux RHEL 7.6, POWER, 8335-GTX, Python 2.7.5
See https://gist.github.com/91a8dc6b026fd5e3a721a05bc8dfcc9a for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in this PR)
node3407.kirlia.os - Linux centos linux 7.8.2003, x86_64, Intel(R) Xeon(R) Gold 6240 CPU @ 2.60GHz (cascadelake), Python 2.7.5
See https://gist.github.com/7ff6cc31293aad52fdf5f6f0e7d11a34 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in this PR)
node2657.swalot.os - Linux centos linux 7.8.2003, x86_64, Intel(R) Xeon(R) CPU E5-2660 v3 @ 2.60GHz (haswell), Python 2.7.5
See https://gist.github.com/41fa276f7fd0eea584d9771ee1de68b9 for a full test report.

**Comment by boegel** [comment]
@Flamefire Trouble on POWER?

**Comment by Flamefire** [comment]
Test report by @Flamefire
**SUCCESS**
Build succeeded for 3 out of 3 (2 easyconfigs in this PR)
taurusi5196.taurus.hrsk.tu-dresden.de - Linux RHEL 7.8, x86_64, Intel(R) Xeon(R) CPU E5-2680 v3 @ 2.50GHz, Python 2.7.5
See https://gist.github.com/d4443285ae329d1909f7f1b3bb31b187 for a full test report.

**Comment by Flamefire** [comment]
@boegel ICU again, can be ignored

**Comment by Flamefire** [comment]
Test report by @Flamefire
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in this PR)
taurusml13 - Linux RHEL 7.6, POWER, 8335-GTX, Python 2.7.5
See https://gist.github.com/f4a2729e3839ec2e67c2d76aad25a7fb for a full test report.

**Review by boegel — APPROVED** [review]
lgtm

**Comment by boegel** [comment]
Going in, thanks @Flamefire!

**Pull request merged**
