### PR TITLE
{vis}[GCCcore/12.2.0] Tk v8.6.12

### PR DESCRIPTION
**Pull request by jfgrimm**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by boegel** [comment]
@jfgrimm Any particular use case you have for Tcl/Tk 8.6.13, given we already have easyconfigs for Tcl/Tk with `GCCcore/12.2.0`?

**Comment by jfgrimm** [comment]
> @jfgrimm Any particular use case you have for Tcl/Tk 8.6.13, given we already have easyconfigs for Tcl/Tk with `GCCcore/12.2.0`?

Oversight, we don't have `Tk` for this Toolchain generation yet so I assumed `Tcl` hadn't been done

**Comment by boegel** [comment]
@jfgrimm How do you want to proceed here?

**Comment by jfgrimm** [comment]
> @jfgrimm How do you want to proceed here?

force merge?

just kidding, I'll kick `Tcl` from the PR and drop `TK` to 8.6.12

**Comment by verdurin** [comment]
Test report by @verdurin
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
easybuild-c7.novalocal - Linux CentOS Linux 7.9.2009, x86_64, Intel Xeon Processor (Skylake, IBRS), Python 3.6.8
See https://gist.github.com/c22dea23e69325d59c842124c01e8f1a for a full test report.

**Comment by verdurin** [comment]
@boegelbot please test @ generoso

**Comment by verdurin** [comment]
@boegelbot please test @ jsc-zen2

**Review by verdurin — APPROVED** [review]
Looks fine.

**Comment by verdurin** [comment]
Going in, thanks @jfgrimm!

**Pull request merged**
