### PR TITLE
{ai}[foss/2022a] PyTorch v2.1.0

### PR DESCRIPTION
**Pull request by Flamefire**
(created using `eb --new-pr`)

Requires:
- #19354
- #19414

### CODE REVIEW

**Comment by branfosj** [comment]
Test report by @branfosj
**FAILED**
Build succeeded for 0 out of 1 (1 easyconfigs in total)
bear-pg0104u04a - Linux RHEL 8.6, x86_64, Intel(R) Xeon(R) Platinum 8360Y CPU @ 2.40GHz (icelake), Python 3.6.8
See https://gist.github.com/branfosj/a7ddd63b5f1446a511b69d5083d56d6b for a full test report.

**Comment by branfosj** [comment]
@boegelbot please test @ jsc-zen2
CORE_CNT=16

**Comment by branfosj** [comment]
@boegelbot please test @ generoso
CORE_CNT=16

**Comment by branfosj** [comment]
Test report by @branfosj
**FAILED**
Build succeeded for 0 out of 1 (1 easyconfigs in total)
bear-pg0104u08b - Linux RHEL 8.6, x86_64, Intel(R) Xeon(R) Platinum 8360Y CPU @ 2.40GHz (icelake), Python 3.6.8
See https://gist.github.com/branfosj/ca580982cb2310c2948b6fc86e63e22e for a full test report.

**Comment by branfosj** [comment]
`test_datapipe` (only seen in the 2022a build)
```
Traceback (most recent call last):
  File "/dev/shm/branfosj/build-up-EL8/PyTorch/2.1.0/foss-2022a/pytorch-v2.1.0/test/test_datapipe.py", line 31, in <module>
    from typing_extensions import NamedTuple
ImportError: cannot import name 'NamedTuple' from 'typing_extensions'
```

The remaining are seen for both the 2022a and 2022b builds:
```
FAILED [0.0706s] dynamo/test_dynamic_shapes.py::DynamicShapesExportTests::test_predispatch_with_for_out_dtype_nested_dynamic_shapes - torch._subclasses.fake_tensor.DataDependentOutputException: aten.allc...
FAILED [0.2210s] functorch/test_ops.py::TestOperatorsCPU::test_vmapvjpvjp_linalg_tensorsolve_cpu_float32 - AssertionError: Tensor-likes are not close!                                
FAILED [0.0884s] inductor/test_compiled_autograd.py::EagerAutogradTests::test_indexing_duplicates - AssertionError: Tensor-likes are not close!                                       
FAILED [0.0974s] inductor/test_mkldnn_pattern_matcher.py::TestPatternMatcher::test_linear_fp32 - AssertionError: Scalars are not equal!                                               
FAILED [0.0005s] test_proxy_tensor.py::TestSymbolicTracing::test_constant_specialization - AssertionError: translation validation requires Z3 package. Please, either install z3-solver or disable translat...
FAILED [0.0014s] distributed/elastic/multiprocessing/api_test.py::StartProcessesNotCITest::test_wrap_bad - io.UnsupportedOperation: fileno                                            
FAILED [0.0132s] test_nn.py::TestNN::test_batchnorm_nhwc_cpu - AssertionError: Tensor-likes are not close!                                                                            
FAILED [31.7476s] test_sparse_csr.py::TestSparseCompressedCPU::test_invalid_input_csr_large_cpu - AssertionError: "32-bit integer overflow in nnz" does not match "value cannot be converted to type int32 ...
```

`test_vmapvjpvjp_linalg_tensorsolve_cpu_float32` and `test_sparse_csr.py::TestSparseCompressedCPU::test_invalid_input_csr_large_cpu` are both listed in https://github.com/pytorch/pytorch/issues/102673

**Comment by Flamefire** [comment]
Test report by @Flamefire
**FAILED**
Build succeeded for 2 out of 3 (1 easyconfigs in total)
taurusml7 - Linux RHEL 7.6, POWER, 8335-GTX, 6 x NVIDIA Tesla V100-SXM2-32GB, 440.64.00, Python 2.7.5
See https://gist.github.com/Flamefire/cf1285da02442e482b490c57aedb1836 for a full test report.

**Comment by Flamefire** [comment]
Test report by @Flamefire
**FAILED**
Build succeeded for 2 out of 3 (1 easyconfigs in total)
taurusi8030 - Linux CentOS Linux 7.9.2009, x86_64, AMD EPYC 7352 24-Core Processor, 8 x NVIDIA NVIDIA A100-SXM4-40GB, 470.57.02, Python 2.7.5
See https://gist.github.com/Flamefire/040baceefcd604ee00646c35b65dc689 for a full test report.

**Comment by VRehnberg** [comment]
Test report by @VRehnberg
**FAILED**
Build succeeded for 1 out of 2 (1 easyconfigs in total)
alvis-s1 - Linux Rocky Linux 8.8, x86_64, Intel(R) Xeon(R) Silver 4314 CPU @ 2.40GHz, Python 3.6.8
See https://gist.github.com/VRehnberg/ea84f52c8e269c7299332c7bfebaaf2d for a full test report.

**Comment by VRehnberg** [comment]
Test report by @VRehnberg
**FAILED**
Build succeeded for 1 out of 2 (1 easyconfigs in total)
alvis-c1 - Linux Rocky Linux 8.8, x86_64, Intel Xeon Processor (Skylake), Python 3.6.8
See https://gist.github.com/VRehnberg/d3c5b28ba3fa0d864c79112b0e7682f6 for a full test report.

**Comment by Flamefire** [comment]
Test report by @Flamefire
**FAILED**
Build succeeded for 1 out of 2 (2 easyconfigs in total)
n1484 - Linux RHEL 8.7 (Ootpa), x86_64, Intel(R) Xeon(R) Platinum 8470 (icelake), Python 3.8.13
See https://gist.github.com/Flamefire/52da42ad5439e76d20bc9d1aae78ce3f for a full test report.

**Comment by Flamefire** [comment]
Test report by @Flamefire
**FAILED**
Build succeeded for 6 out of 7 (2 easyconfigs in total)
i8029 - Linux Rocky Linux 8.7, x86_64, AMD EPYC 7352 24-Core Processor (zen2), 8 x NVIDIA NVIDIA A100-SXM4-40GB, 545.23.08, Python 3.6.8
See https://gist.github.com/Flamefire/a0809b32f9e02eee2ebb4dcceb5f9770 for a full test report.

**Comment by Flamefire** [comment]
Test report by @Flamefire
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in total)
n1452 - Linux RHEL 8.7 (Ootpa), x86_64, Intel(R) Xeon(R) Platinum 8470 (icelake), Python 3.8.13
See https://gist.github.com/Flamefire/e59e953e7327a72da56967105ee06e65 for a full test report.

**Comment by Flamefire** [comment]
Test report by @Flamefire
**FAILED**
Build succeeded for 1 out of 2 (2 easyconfigs in total)
i8016 - Linux Rocky Linux 8.7, x86_64, AMD EPYC 7352 24-Core Processor (zen2), 8 x NVIDIA NVIDIA A100-SXM4-40GB, 545.23.08, Python 3.6.8
See https://gist.github.com/Flamefire/e2646046b7029dffb663b746b3ad6fd5 for a full test report.

**Comment by Flamefire** [comment]
Test report by @Flamefire
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in total)
i8023 - Linux Rocky Linux 8.7, x86_64, AMD EPYC 7352 24-Core Processor (zen2), Python 3.6.8
See https://gist.github.com/Flamefire/30a230d2d2269b3b6d2838da3ab70737 for a full test report.

**Comment by Flamefire** [comment]
Test report by @Flamefire
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in total)
n1173 - Linux RHEL 8.7 (Ootpa), x86_64, Intel(R) Xeon(R) Platinum 8470 (icelake), Python 3.8.13
See https://gist.github.com/Flamefire/52e3afade2e472a5444fe46b7fe7e3ed for a full test report.

**Comment by branfosj** [comment]
@boegelbot please test @ generoso
CORE_CNT=16

**Comment by branfosj** [comment]
@boegelbot please test @ jsc-zen2
CORE_CNT=16

**Comment by branfosj** [comment]
Test report by @branfosj
**FAILED**
Build succeeded for 1 out of 2 (2 easyconfigs in total)
bear-pg0105u03b - Linux RHEL 8.6, x86_64, Intel(R) Xeon(R) Platinum 8360Y CPU @ 2.40GHz (icelake), Python 3.6.8
See https://gist.github.com/branfosj/b3394aa92df096d10e16542fcc22f673 for a full test report.

**Comment by Flamefire** [comment]
@branfosj

- test_sympy_utils Requires rebuild with https://github.com/easybuilders/easybuild-easyconfigs/pull/19414
- test_nn seemingly fails on some machines, can't reproduce this but @schiotz also skipped that in #19184 so adding that patch to skip it
- inductor/test_compiled_autograd Similar. Can you check the log for this? I suppose it is `test_indexing_duplicates` which @schiotz has also seen (and patched to skip).

For the last point: Is it the same as:
```
AssertionError: Tensor-likes are not close!

Mismatched elements: 4 / 16 (25.0%)
Greatest absolute difference: 1.0 at index (1, 0) (up to 1e-05 allowed)
Greatest relative difference: 0.3333333432674408 at index (1, 0) (up to 1.3e-06 allowed)

To execute this test, run the following from the base repo dir:
     python test/inductor/test_compiled_autograd.py -k test_indexing_duplicates
```

BTW: Does your easyblock include https://github.com/easybuilders/easybuild-easyblocks/pull/3033? Because I would expect the inductor failure to show up in the line "Found <n> individual tests with failed assertions" so that we know it is `test_indexing_duplicates`

**Comment by branfosj** [comment]
Yes, it is the same test failure (`test_indexing_duplicates`).

Thanks for the information.

**Comment by Flamefire** [comment]
> Yes, it is the same test failure (`test_indexing_duplicates`).

I've seen that they released 2 bugfix releases for 2.1 and opened a PR for 2.1.2: https://github.com/easybuilders/easybuild-easyconfigs/pull/19444   
Can you check if you see the same failures on the same machine with that? If not IMO it makes more sense to get the 2.1.2 version in which hopefully doesn't produce new failures compared to 2.1.0 (hence the draft status)

**Comment by Flamefire** [comment]
Closing this as 2.1.2 in #19444 has been merged which supposedly fixes known failures.

**Pull request closed without merging**
