### PR TITLE
{bio} URL for king-2.2.4 fixed, new king-2.2.7

### PR DESCRIPTION
**Pull request by sassy-crick**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by sassy-crick** [comment]
Fixed the URL of the homepage and the download one for king-2.2.4.eb, added latest king-2.2.7.eb

**Comment by migueldiascosta** [comment]
@boegelbot please test @ generoso

**Review by migueldiascosta — APPROVED** [review]
lgtm

**Comment by migueldiascosta** [comment]
Going in, thanks @sassy-crick!

**Pull request merged**
