### PR TITLE
{math}[fosscuda/2018b] Keras v2.2.4 w/ Python 3.6.6

### PR DESCRIPTION
**Pull request by arielzn**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by akesandgren** [comment]
We already have Keras 2.2.4 for fosscuda/2019a (with Python 3.7.2)
Is there a special reason you need 2.2.4 for fosscuda/2018b?

**Comment by arielzn** [comment]
>  Is there a special reason you need 2.2.4 for fosscuda/2018b?

Not really, we just needed to install it on the 2018b toolchain which is the one being used by default in that site. i didn't see there was one for 2019a, but we are not going to rebuild the stack on that now.

feel free to dismiss this PR, if the policy is to avoid having repeated things upstream

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
node253.hydra.os - Linux centos linux 7.6.1810, Intel(R) Xeon(R) CPU E5-2650 v4 @ 2.20GHz, Python 2.7.5
See https://gist.github.com/6d14aa8646854d23ead1ff43d4703181 for a full test report.

**Comment by boegel** [comment]
Going in, thanks @arielzn!

**Pull request merged**
