### PR TITLE
{chem}[foss/2021a] PySCF v1.7.6, libcint v4.4.0 w/ Python 3.9.5, XCFun v2.1.1

### PR DESCRIPTION
**Pull request by Micket**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by Micket** [comment]
Test report by @Micket
**SUCCESS**
Build succeeded for 9 out of 9 (2 easyconfigs in total)
alvis-c1 - Linux centos linux 7.9.2009, x86_64, Intel Xeon Processor (Skylake), Python 3.6.8
See https://gist.github.com/66647c8fcf36a21826c469416bf4e77c for a full test report.

**Review by boegel — DISMISSED** [review]
@Micket easyconfig for `XCFun/2.1.1-foss-2021a` is missing?

**Comment by Micket** [comment]
Test report by @Micket
**SUCCESS**
Build succeeded for 0 out of 0 (3 easyconfigs in total)
alvis-c1 - Linux centos linux 7.9.2009, x86_64, Intel Xeon Processor (Skylake), Python 3.6.8
See https://gist.github.com/f721f6dbf8d37abe24d74ef913d8a379 for a full test report.

**Comment by Micket** [comment]
Test report by @Micket
**SUCCESS**
Build succeeded for 3 out of 3 (3 easyconfigs in total)
alvis-c1 - Linux centos linux 7.9.2009, x86_64, Intel Xeon Processor (Skylake), Python 3.6.8
See https://gist.github.com/20c7a0156665cc8e35139ce9c8754a95 for a full test report.

**Comment by SebastianAchilles** [comment]
Test report by @sebastianachilles
**SUCCESS**
Build succeeded for 3 out of 3 (3 easyconfigs in total)
rocky8-eb - Linux rocky linux 8.4, x86_64, Intel(R) Core(TM) i7-6900K CPU @ 3.20GHz (broadwell), Python 3.6.8
See https://gist.github.com/221dcc3aaff326092acf1d1dd5833ef0 for a full test report.

**Comment by SebastianAchilles** [comment]
Test report by @sebastianachilles
**SUCCESS**
Build succeeded for 3 out of 3 (3 easyconfigs in total)
centos8-eb - Linux centos linux 8.3.2011, x86_64, Intel(R) Core(TM) i7-8700 CPU @ 3.20GHz (skylake), Python 3.6.8
See https://gist.github.com/aec0915e6aaaaa7282ce70a05082530f for a full test report.

**Comment by SebastianAchilles** [comment]
@boegelbot please test @ generoso

**Review by SebastianAchilles — APPROVED** [review]
lgtm

**Comment by verdurin** [comment]
Test report by @verdurin
**SUCCESS**
Build succeeded for 6 out of 6 (3 easyconfigs in total)
easybuild-c7.novalocal - Linux centos linux 7.9.2009, x86_64, Intel Xeon Processor (Skylake, IBRS), Python 3.6.8
See https://gist.github.com/955abd71baab0668e075c61b4c26334d for a full test report.

**Comment by verdurin** [comment]
Going in, thanks @Micket!

**Pull request merged**
