### PR TITLE
{bio,lib,vis}[foss/2022a] deepfold v20240308, dm-haiku v0.0.9, ml-collections v0.1.1 w/ CUDA 11.7.0

### PR DESCRIPTION
**Pull request by WilleBell**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by WilleBell** [comment]
Test report by @WilleBell
**SUCCESS**
Build succeeded for 3 out of 3 (3 easyconfigs in total)
node401.hydra.os - Linux Rocky Linux 8.8, x86_64, AMD EPYC 7282 16-Core Processor, Python 3.6.8
See https://gist.github.com/WilleBell/0d8bcd9989f2d1f18ede5742032d6b58 for a full test report.

**Review by Micket — DISMISSED** [review]
lgtm

**Comment by Micket** [comment]
@boegelbot please test @ jsc-zen3

**Comment by Micket** [comment]
Test report by @Micket
**FAILED**
Build succeeded for 3 out of 4 (3 easyconfigs in total)
alvis2-04 - Linux Rocky Linux 8.9, x86_64, Intel(R) Xeon(R) Gold 6226R CPU @ 2.90GHz, 8 x NVIDIA Tesla T4, 550.54.14, Python 3.6.8
See https://gist.github.com/Micket/1d639f71827a6ecab9df99e41a75b450 for a full test report.

**Comment by Micket** [comment]
Test report by @Micket
**FAILED**
Build succeeded for 0 out of 1 (1 easyconfigs in total)
vera40-1 - Linux Rocky Linux 8.9, x86_64, Intel(R) Xeon(R) Gold 6130 CPU @ 2.10GHz, 1 x NVIDIA Tesla T4, 550.54.14, Python 3.6.8
See https://gist.github.com/Micket/39aae28dd0b18720d3bbc3e3cff2163f for a full test report.

**Comment by smoors** [comment]
@boegelbot: please test @ generoso

**Comment by smoors** [comment]
@boegelbot: please test @ generoso

**Review by smoors — APPROVED** [review]
lgtm

**Comment by smoors** [comment]
Going in, thanks @WilleBell!

**Pull request merged**
