### PR TITLE
{bio}[GCCcore/10.3.0] MUMmer v3.23

### PR DESCRIPTION
**Pull request by bedroge**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by bedroge** [comment]
Test report by @bedroge
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
bob-Latitude-5300 - Linux Ubuntu 20.04, x86_64, Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz, Python 3.8.10
See https://gist.github.com/3cb6374e41dc9056ad7a9cc0121bfe4a for a full test report.

**Comment by bedroge** [comment]
Test report by @bedroge
**FAILED**
Build succeeded for 0 out of 1 (1 easyconfigs in total)
pg-interactive.hpc.rug.nl - Linux centos linux 7.9.2009, x86_64, Intel(R) Xeon(R) CPU E5-2680 v3 @ 2.50GHz, Python 3.6.8
See https://gist.github.com/63e4f0db1908d1764e97555e27b11455 for a full test report.

**Comment by bedroge** [comment]
Test report by @bedroge
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
pg-interactive.hpc.rug.nl - Linux centos linux 7.9.2009, x86_64, Intel(R) Xeon(R) CPU E5-2680 v3 @ 2.50GHz, Python 3.6.8
See https://gist.github.com/b14cc9c9fc35bb27451cfe2e0c595db0 for a full test report.

**Comment by bedroge** [comment]
@boegelbot please test @ generoso

**Comment by migueldiascosta** [comment]
I'm seeing 

`WARNING: Suppressed adding the following path(s) to $PATH of the module as they were already added: ['bin']`

the `bin` folder is added to `$PATH` by the easyblock (https://github.com/easybuilders/easybuild-easyblocks/blob/0f670734870df82eb14df0ec0a3087f4623a8c7d/easybuild/easyblocks/m/mummer.py#L99)

should that line be removed or is there a reason to add it unconditionally, similarly to https://github.com/easybuilders/easybuild-easyconfigs/pull/14415#discussion_r757755708

**Comment by bedroge** [comment]
I'm getting the same warnings, but I'm not sure why the easyblock explicitly adds `bin` to `$PATH`. @boegel do you know?

**Comment by bedroge** [comment]
The test on generoso actually failed due to:
```
== 2021-12-01 09:25:52,697 build_log.py:169 ERROR EasyBuild crashed with an error (at easybuild/easybuild-framework/easybuild/base/exceptions.py:124 in __init__): cmd "file /project/boegelbot/Rocky8/haswell/software/MUMmer/3.23-GCCcore-10.3.0/bin/mummer" exited with exit code 1 and output:
/project/boegelbot/Rocky8/haswell/software/MUMmer/3.23-GCCcore-10.3.0/bin/mummer: ERROR: ELF 64-bit LSB executable, x86-64, version 1 (SYSV), statically linked error reading (Invalid argument)
```
Any idea what's wrong?

**Comment by boegel** [comment]
> I'm getting the same warnings, but I'm not sure why the easyblock explicitly adds `bin` to `$PATH`. @boegel do you know?

If `bin` is non-empty when the module file is created, then the corresponding `prepend_path` statement in the custom easyblock for `MUMmer` can be removed.

**Comment by boegel** [comment]
@boegelbot please test @ generoso
EB_ARGS="--include-easyblocks-from-pr 2630"

**Comment by bedroge** [comment]
Test report by @bedroge
Using easyblocks from PR(s) https://github.com/easybuilders/easybuild-easyblocks/pull/2630
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
bob-Latitude-5300 - Linux Ubuntu 20.04, x86_64, Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz, Python 3.8.10
See https://gist.github.com/1281714f3f495ac07f8697ca72780818 for a full test report.

**Comment by bedroge** [comment]
Test report by @bedroge
Using easyblocks from PR(s) https://github.com/easybuilders/easybuild-easyblocks/pull/2630
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
pg-interactive.hpc.rug.nl - Linux centos linux 7.9.2009, x86_64, Intel(R) Xeon(R) CPU E5-2680 v3 @ 2.50GHz, Python 3.6.8
See https://gist.github.com/baa115b73d92340badb6ef690acdd39d for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
Using easyblocks from PR(s) https://github.com/easybuilders/easybuild-easyblocks/pull/2630
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
node2613.swalot.os - Linux centos linux 7.9.2009, x86_64, Intel(R) Xeon(R) CPU E5-2660 v3 @ 2.60GHz (haswell), Python 3.6.8
See https://gist.github.com/3f3a6f82d049e87999149279c5d87d6c for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
Using easyblocks from PR(s) https://github.com/easybuilders/easybuild-easyblocks/pull/2630
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
node3543.doduo.os - Linux RHEL 8.2, x86_64, AMD EPYC 7552 48-Core Processor (zen2), Python 3.6.8
See https://gist.github.com/65e1bff333c048a5705a004e001aa63d for a full test report.

**Review by boegel — APPROVED** [review]
lgtm

**Comment by boegel** [comment]
Going in, thanks @bedroge!

**Pull request merged**
