### PR TITLE
Add internal CUDA header patch for PSM2

### PR DESCRIPTION
**Pull request by bartoldeman**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by bartoldeman** [comment]
This eliminates the CUDA builddependency by adding a minimal internal `cuda.h` header, exactly like we already did for Open MPI.

See https://github.com/easybuilders/easybuild-easyconfigs/pull/20794 and https://github.com/easybuilders/easybuild-framework/issues/4560 for more info.

**Comment by bartoldeman** [comment]
@boegelbot please test @ jsc-zen3

**Comment by bartoldeman** [comment]
@boegelbot please test @ generoso

**Comment by jfgrimm** [comment]
Test report by @jfgrimm
**SUCCESS**
Build succeeded for 13 out of 13 (7 easyconfigs in total)
node026.viking2.yor.alces.network - Linux Rocky Linux 8.9, x86_64, AMD EPYC 7643 48-Core Processor, Python 3.6.8
See https://gist.github.com/jfgrimm/945a6b8d5f4f7d0c95c07533f91317fc for a full test report.

**Review by jfgrimm — APPROVED** [review]
LGTM, thanks for the patch :)

**Comment by jfgrimm** [comment]
Going in, thanks @bartoldeman!

**Pull request merged**
