### PR TITLE
{vis}[foss/2021a] Detectron2 v0.6 w/ Python 3.9.5

### PR DESCRIPTION
**Pull request by lexming**
(created using `eb --new-pr`)

Depends on:
- [x] #15034 
- [x] #15025 
- [x] #15023

### CODE REVIEW

**Comment by smoors** [comment]
@boegelbot: please test @ generoso

**Comment by lexming** [comment]
Test report by @lexming
**FAILED**
Build succeeded for 2 out of 6 (4 easyconfigs in total)
node253.hydra.os - Linux CentOS Linux 7.9.2009, x86_64, Intel(R) Xeon(R) CPU E5-2650 v4 @ 2.20GHz, 1 x NVIDIA Tesla P100-PCIE-16GB, 470.82.01, Python 2.7.5
See https://gist.github.com/ab6b6d92c289c72e761a18ca909e0c76 for a full test report.

**Comment by lexming** [comment]
Test report by @lexming
**FAILED**
Build succeeded for 4 out of 6 (4 easyconfigs in total)
node250.hydra.os - Linux CentOS Linux 7.9.2009, x86_64, Intel(R) Xeon(R) CPU E5-2650 v4 @ 2.20GHz, 1 x NVIDIA Tesla P100-PCIE-16GB, 470.82.01, Python 2.7.5
See https://gist.github.com/c921bd500f9d85ac96d2beee8d0720c0 for a full test report.

**Comment by lexming** [comment]
Test report by @lexming
**SUCCESS**
Build succeeded for 4 out of 4 (4 easyconfigs in total)
node252.hydra.os - Linux CentOS Linux 7.9.2009, x86_64, Intel(R) Xeon(R) CPU E5-2650 v4 @ 2.20GHz, 1 x NVIDIA Tesla P100-PCIE-16GB, 470.82.01, Python 2.7.5
See https://gist.github.com/cfd84ace3cac62f07a5ab5bd2a107747 for a full test report.

**Comment by lexming** [comment]
The test in generoso failed because the easyconfig of Detectron2 with CUDA needs a system with an actual GPU.

**Comment by lexming** [comment]
@boegelbot: please test @ generoso
EB_ARGS="Detectron2-0.6-foss-2021a.eb pydot-1.4.2-GCCcore-10.3.0.eb torchvision-0.11.3-foss-2021a-CUDA-11.3.1.eb"

**Comment by jfgrimm** [comment]
Test report by @jfgrimm
**SUCCESS**
Build succeeded for 13 out of 13 (4 easyconfigs in total)
gpu01.pri.viking.alces.network - Linux CentOS Linux 7.9.2009, x86_64, Intel(R) Xeon(R) Gold 6138 CPU @ 2.00GHz (skylake_avx512), 1 x NVIDIA Tesla V100-SXM2-32GB, 510.47.03, Python 3.6.8
See https://gist.github.com/25b3b8b79fda93f78c94ad8c3139071a for a full test report.

**Review by jfgrimm — CHANGES_REQUESTED** [review]
@lexming  `detectron2` with CUDA (and `pydot`) were merged in #15442, with some differences in dependency versions and extensions

**Comment by lexming** [comment]
@jfgrimm thanks for the review, I missed that merge. I have updated this PR to adapt to the existing easyconfig of `detectron2`. However, the easyconfig of `detectron2` has several issues that need addressing, so I made a merge of the best things on both sides.

Updates made to this PR taken from existing `detectron2`:
* removed dependency on TensorFlow in favor of directly depending on `tensorboard` and `termcolor
* added an explicit dependency on `PyTorch`
* updated the version of all extensions to match the existing easyconfig

Changes needed in `detectron2`:
* name should be `Detectron2` instead of `detectron2`, that is what is used in their homepage
* add dependencies on `boto3` and `PyYAML` which are needed by extensions `iopath` and `fvcore` respectively
* remove extensions in base Python easyconfig: packaging, poetry-core, poetry, pytest, pluggy, CacheControl
* remove extensions that were added as dependencies of `black`, but which do not apply to version 21.4b2: platformdirs, hatch-vcs, setuptools-scm, hatchling, editables, tomli
* add `preinstallopts: "FORCE_CUDA=1"`, otherwise the build will probably not use CUDA

Bonus:
This is independent to this PR, but tests are failing because we have merged in the same toolchain an easyconfig for `topaz` depending on torchvision 0.11.1 and `smooth-topk` depending on v0.11.3. So this PR fixes the collision by always using  torchvision 0.11.3

**Comment by jfgrimm** [comment]
Test report by @jfgrimm
**SUCCESS**
Build succeeded for 4 out of 4 (3 easyconfigs in total)
node110.pri.viking.alces.network - Linux CentOS Linux 7.9.2009, x86_64, Intel(R) Xeon(R) Gold 6138 CPU @ 2.00GHz (skylake_avx512), Python 3.6.8
See https://gist.github.com/fa8942e8b1d5795e236d2be19f654be7 for a full test report.

**Comment by lexming** [comment]
Failed tests in jsc-zen2 are unrelated to this PR, they are caused by issue https://github.com/easybuilders/easybuild-easyblocks/issues/2759

**Pull request merged**
