### PR TITLE
{base,chem,lib}[foss/2022a] chemprop v1.5.2, RDKit v2022.09.4 w/ Python 3.10.4

### PR DESCRIPTION
**Pull request by ItIsI-Orient**
(created using `eb --new-pr`)
Required by:
* #17282

### CODE REVIEW

**Comment by ItIsI-Orient** [comment]
Test report by @ItIsI-Orient
**FAILED**
Build succeeded for 2 out of 3 (3 easyconfigs in total)
node3704.slaking.os - Linux RHEL 8.6, x86_64, Intel(R) Xeon(R) CPU E5-2680 v3 @ 2.50GHz, Python 3.6.8
See https://gist.github.com/c450f8c68fa19ef8aac783593ddba61d for a full test report.

**Comment by ItIsI-Orient** [comment]
Test report by @ItIsI-Orient
**SUCCESS**
Build succeeded for 3 out of 3 (3 easyconfigs in total)
node3704.slaking.os - Linux RHEL 8.6, x86_64, Intel(R) Xeon(R) CPU E5-2680 v3 @ 2.50GHz, Python 3.6.8
See https://gist.github.com/546ef259aa56706783ba1c013a025767 for a full test report.

**Comment by ItIsI-Orient** [comment]
@boegelbot please test @ jsc-zen2

**Review by boegel — APPROVED** [review]
lgtm

**Comment by boegel** [comment]
Going in, thanks @ItIsI-Orient!

**Pull request merged**
