### PR TITLE
{geo}[intel/2017b] PCRaster 4.1.0 (REVIEW)

### PR DESCRIPTION
**Pull request by hajgato**

### CODE REVIEW

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
node2452.golett.os - Linux centos linux 7.4.1708, Intel(R) Xeon(R) CPU E5-2680 v3 @ 2.50GHz, Python 2.7.5
See https://gist.github.com/e902aa58beaeff91b1bbabec38b86332 for a full test report.

**Comment by boegel** [comment]
@hajgato Any particular reason you're using the binary release rather than building from source?

**Comment by hajgato** [comment]
@boegel I did not find the source.

**Comment by boegel** [comment]
@hajgato https://github.com/pcraster/pcraster/ (granted, there are no proper releases, it seems...)

**Comment by hajgato** [comment]
@boegel Suggestions? User asked specifically version `4.1.0`.

**Comment by boegel** [comment]
@hajgato Hmm, then I guess the binary version is your best option, since there's a total lack of tags/releases in the source repository...

Maybe open an issue to ask them about that?

**Comment by boegel** [comment]
Going in, thanks @hajgato!

**Pull request merged**
