### PR TITLE
{vis}[foss/2021b,foss/2022a,foss/2023a] fix napari v0.4.1{5,8} shebang

### PR DESCRIPTION
**Pull request by ThomasHoffmann77**
(created using `eb --new-pr`)

see #19664

### CODE REVIEW

**Review by Micket — APPROVED** [review]
lgtm

**Comment by Micket** [comment]
@boegelbot please test @ generoso

**Comment by Micket** [comment]
@boegelbot please test @ jsc-zen3

**Comment by Micket** [comment]
was someone rebuilding GCCcore on generoso during my test? I don't understand the failure

**Comment by akesandgren** [comment]
Going in, thanks @ThomasHoffmann77!

**Pull request merged**
