### PR TITLE
add jupyter_nbextensions_configurator extension to IPython 7.7.0 easyconfigs

### PR DESCRIPTION
**Pull request by boegel**

### CODE REVIEW

**Comment by boegel** [comment]
Test report by @boegel
**FAILED**
Build succeeded for 0 out of 2 (2 easyconfigs in this PR)
node3152.skitty.os - Linux centos linux 7.6.1810, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz, Python 3.6.8
See https://gist.github.com/dce72a1e90dcc3921e6eaaf63d2de048 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**FAILED**
Build succeeded for 1 out of 2 (2 easyconfigs in this PR)
node3152.skitty.os - Linux centos linux 7.6.1810, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz, Python 3.6.8
See https://gist.github.com/07c6fa1323597df7f865c6e9dce324fc for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in this PR)
node2412.golett.os - Linux centos linux 7.7.1908, Intel(R) Xeon(R) CPU E5-2680 v3 @ 2.50GHz, Python 2.7.5
See https://gist.github.com/635678d8760624391cd43f841cb7b9e3 for a full test report.

**Comment by smoors** [comment]
Test report by @smoors
**FAILED**
Build succeeded for 2 out of 3 (2 easyconfigs in this PR)
node377.hydra.os - Linux centos linux 7.6.1810, Intel(R) Xeon(R) Gold 6148 CPU @ 2.40GHz, Python 2.7.5
See https://gist.github.com/1502dffba3bd5c6bb6a1cd91f5be453e for a full test report.

**Comment by boegel** [comment]
@smoors Hmm, `iptest` failed with `pexpect.exceptions.TIMEOUT: Timeout exceeded.`.

Any ideas?

**Comment by smoors** [comment]
@boegel no clue. I also see this, not sure if that is related:
```
Test group: core
/tmp/smoors/ebinstall/9133/software/IPython/7.7.0-foss-2019a-Python-3.7.2/lib/python3.7/site-packages/IPython/core/inputsplitter.py:22: DeprecationWarning: IPython.core.inputsplitter is deprecated since IPython 7 in favor of `IPython.core.inputtransformer2`
  DeprecationWarning)
......................................SSSS.........................................................................................................................................................S.........................................................................................................................................Alarm clock
.....................................................Alarm clock
..
KeyboardInterrupt

....Alarm clock
................................UsageError: Line magic function `%doesntexist` not found.
.UsageError: Cell magic `%%doesntexist` not found.

```

**Comment by smoors** [comment]
Test report by @smoors
**SUCCESS**
Build succeeded for 3 out of 3 (2 easyconfigs in this PR)
node376.hydra.os - Linux centos linux 7.6.1810, Intel(R) Xeon(R) Gold 6148 CPU @ 2.40GHz, Python 2.7.5
See https://gist.github.com/f298a29fbad0288af6afb9573f1e53e5 for a full test report.

**Comment by smoors** [comment]
Going in, thanks @boegel!

**Pull request merged**
