### PR TITLE
{vis}[foss/2023a] VTK v9.3.0

### PR DESCRIPTION
**Pull request by lexming**
(created using `eb --new-pr`)

Only change is the CMahe flags for Python, `ROOT_DIR` is no longer recognized and I had to define the 3 extra vars.

### CODE REVIEW

**Comment by lexming** [comment]
@boegelbot: please test @ generoso

**Comment by lexming** [comment]
@boegelbot please test @ jsc-zen2

**Comment by casparvl** [comment]
Test report by @casparvl
**FAILED**
Build succeeded for 0 out of 1 (1 easyconfigs in total)
tcn1.local.snellius.surf.nl - Linux RHEL 8.6, x86_64, AMD EPYC 7H12 64-Core Processor, Python 3.6.8
See https://gist.github.com/casparvl/f1dc8aee2b99a540177f31890e9bd715 for a full test report.

**Review by casparvl — COMMENTED** [review]
EasyConfig looks good to me. Testing on my system now, will upload test report from there.

**Comment by casparvl** [comment]
Test report by @casparvl
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
tcn1.local.snellius.surf.nl - Linux RHEL 8.6, x86_64, AMD EPYC 7H12 64-Core Processor, Python 3.6.8
See https://gist.github.com/casparvl/85e039ed469966333577c3cb1c5db3cd for a full test report.

**Review by casparvl — APPROVED** [review]
Lgtm!

**Comment by casparvl** [comment]
Going in, thanks @lexming!

**Comment by smoors** [comment]
@boegelbot please test @ jsc-zen3

**Pull request merged**
