### PR TITLE
restore Travis configuration to test with both Python 2.6 & 2.7 with Lmod/Tmod

### PR DESCRIPTION
**Pull request by boegel**
After the merge sprint on May 8th 2019, we should restore the Travis configuration to what it was before the changes made in #8251 .

(this will show an empty diff until #8251 is effectively merged, may need a close/re-open to see correct diff)

@vanzod Please merge at the end of the merge sprint?

### CODE REVIEW

**Comment by boegel** [comment]
parsing issue with `FlexiDot` is fixed with #8275 (checked via https://travis-ci.org/boegel/easybuild-easyconfigs/builds/530150722)

**Comment by akesandgren** [comment]
Kicking travis

**Comment by akesandgren** [comment]
Travis kicked

**Comment by akesandgren** [comment]
Going in, thanks @boegel!

**Pull request merged**
