### PR TITLE
{tools}[fosscuda/2019b] IRkernel v1.1 w/ Python 3.7.4

### PR DESCRIPTION
**Pull request by branfosj**
(created using `eb --new-pr`)

Requires:
* [x] #9751 `IPython-7.9.0-fosscuda-2019b-Python-3.7.4.eb`

### CODE REVIEW

**Comment by branfosj** [comment]
Test report by @branfosj
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
bear-pg0212u15b.bear.cluster - Linux centos linux 7.7.1908, Intel(R) Xeon(R) CPU E5-2640 v4 @ 2.40GHz, Python 2.7.5
See https://gist.github.com/ea05cbde9a5a1586f56528300871832c for a full test report.

**Comment by verdurin** [comment]
Test report by @verdurin
**FAILED**
Build succeeded for 22 out of 26 (1 easyconfigs in this PR)
easybuild.novalocal - Linux centos linux 7.7.1908, Intel Xeon Processor (Skylake, IBRS), Python 2.7.5
See https://gist.github.com/be34a6132cd2b76c95b742d816a0f363 for a full test report.

**Comment by lexming** [comment]
Test report by @lexming
**SUCCESS**
Build succeeded for 5 out of 5 (1 easyconfigs in this PR)
node150.hydra.os - Linux centos linux 7.7.1908, Intel(R) Xeon(R) CPU E5-2680 v2 @ 2.80GHz, Python 2.7.5
See https://gist.github.com/20870b1786835e36b7dafcc91a0a71f9 for a full test report.

**Comment by lexming** [comment]
Since the failed test from @verdurin is related to matplotlib, which is not part of this PR, I'll proceed with its merging.
Thanks @branfosj !

**Pull request merged**
