### PR TITLE
{math}[foss/2019b] ArviZ v0.7.0 w/ Python 3.7.4

### PR DESCRIPTION
**Pull request by boegel**
(created using `eb --new-pr`)

requires ~~#10399~~ (`netcdf4-python`)

### CODE REVIEW

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
generoso - Linux centos linux 7.6.1810, Intel(R) Xeon(R) CPU E5-2660 v4 @ 2.00GHz, Python 3.6.8
See https://gist.github.com/1fc988e7bd9d18ee532df7c3c974e8b4 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
node3409.kirlia.os - Linux centos linux 7.7.1908, Intel(R) Xeon(R) Gold 6240 CPU @ 2.60GHz (cascadelake), Python 2.7.5
See https://gist.github.com/d0ee73d7ba609af9ea64582ef1a11a22 for a full test report.

**Comment by verdurin** [comment]
Test report by @verdurin
**SUCCESS**
Build succeeded for 2 out of 2 (1 easyconfigs in this PR)
easybuild.novalocal - Linux centos linux 7.7.1908, Intel Xeon Processor (Skylake, IBRS), Python 2.7.5
See https://gist.github.com/e00982466c6fd13297f3cbc9eeaff7ff for a full test report.

**Comment by boegel** [comment]
@verdurin So, good to merge then?

**Comment by verdurin** [comment]
Going in, thanks @boegel!

**Comment by verdurin** [comment]
Going in, thanks @boegel!

**Comment by verdurin** [comment]
@boegel Not

**Comment by verdurin** [comment]
Going in, thanks @boegel!

**Pull request merged**
