### PR TITLE
Adding new easyconfig for MAGeCK

### PR DESCRIPTION
**Pull request by markgyver**
One easyconfig with no toolchain and another with foss/2016a toolchain

### CODE REVIEW

**Comment by boegel** [comment]
@markgyver there's a syntax error in one these, see failing Travis tests?

**Comment by markgyver** [comment]
Sorry, this is my first contribution and I´m new ussing EasyBuild. I´ll take a look

**Comment by boegel** [comment]
@markgyver No worries, Travis is there to help, not punish you. ;-)

Let us know if you need any help. You can update this PR by pushing a new commit to your `contrib_lunarc_bio` branch, and Travis should be triggered to rerun the tests automagically.

**Comment by migueldiascosta** [comment]
@markgyver, this PR is being closed for the following reason(s): no activity for > 6 months.
Please don't hesitate to reopen this PR or add a comment if you feel this contribution is still relevant.
For more information on our policy w.r.t. closing PRs, see https://easybuild.readthedocs.io/en/latest/Contributing.html#why-a-pull-request-may-be-closed-by-a-maintainer

**Pull request closed without merging**
