### PR TITLE
set $JULIA_DEPOT_PATH and $JULIA_HISTORY in Julia easyconfigs

### PR DESCRIPTION
**Pull request by lexming**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by terjekv** [comment]
Test report by @terjekv
**SUCCESS**
Build succeeded for 10 out of 10 (10 easyconfigs in total)
ninhursaga.uio.no - Linux RHEL 9.1 (Plow), x86_64, Intel(R) Xeon(R) Silver 4216 CPU @ 2.10GHz, 1 x NVIDIA Tesla T4, 525.60.13, Python 3.9.14
See https://gist.github.com/06b2a570b494662d3795b26db42348aa for a full test report.

**Comment by lexming** [comment]
@boegelbot: please test @ generoso

**Comment by lexming** [comment]
@boegelbot please test @ jsc-zen2

**Review by boegel — APPROVED** [review]
lgtm

**Comment by boegel** [comment]
Going in, thanks @lexming!

**Pull request merged**
