### PR TITLE
{devel}[foss/2021a] PyTorch v1.10.0 w/ Python 3.9.5 (CPU-only)

### PR DESCRIPTION
**Pull request by boegel**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by boegel** [comment]
@boegelbot please test @ generoso
CORE_CNT=16

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
node3505.doduo.os - Linux RHEL 8.2, x86_64, AMD EPYC 7552 48-Core Processor (zen2), Python 3.6.8
See https://gist.github.com/c1f5704e3926e68a8a8d7e817f6aff43 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**FAILED**
Build succeeded for 0 out of 1 (1 easyconfigs in total)
node2621.swalot.os - Linux centos linux 7.9.2009, x86_64, Intel(R) Xeon(R) CPU E5-2660 v3 @ 2.60GHz (haswell), Python 3.6.8
See https://gist.github.com/4684366f47765379cfb65b75bdab135f for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**FAILED**
Build succeeded for 0 out of 1 (1 easyconfigs in total)
node3112.skitty.os - Linux centos linux 7.9.2009, x86_64, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz (skylake_avx512), Python 3.6.8
See https://gist.github.com/4defbecaf0e907f8ae053fdcc5926354 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
node2621.swalot.os - Linux centos linux 7.9.2009, x86_64, Intel(R) Xeon(R) CPU E5-2660 v3 @ 2.60GHz (haswell), Python 3.6.8
See https://gist.github.com/f816c43472899874b726b4bb079bb66e for a full test report.

**Comment by migueldiascosta** [comment]
so, a couple of tests fail on skylake? or was there another reason for that failed test report?

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
node3136.skitty.os - Linux centos linux 7.9.2009, x86_64, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz (skylake_avx512), Python 3.6.8
See https://gist.github.com/e0d7721680046c6d8d83ddc15cc104de for a full test report.

**Comment by migueldiascosta** [comment]
I guess that answers my question, even though I'm sure there's no causal relation there :)

what happened in the failed test then?

**Comment by SebastianAchilles** [comment]
Test report by @sebastianachilles
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
jsfc01.int.jusuf.sebastian.cluster - Linux rocky linux 8.4, x86_64, AMD EPYC 7742 64-Core Processor (zen2), 1 x NVIDIA GRID V100-4C, 460.73.01, Python 3.6.8
See https://gist.github.com/671c3911fa8da49d1408b58e98384df0 for a full test report.

**Comment by boegel** [comment]
> I guess that answers my question, even though I'm sure there's no causal relation there :)
> 
> what happened in the failed test then?

I'm not sure, I didn't make any changes, I just resubmitted the test with the same resources requested.
It's not the first time that the PyTorch test suite doesn't seem 100% stable...

For future reference (I don't have the details on how these tests failed anymore)

```
distributed/algorithms/test_join failed!
distributed/rpc/test_tensorpipe_agent failed!
```

@migueldiascosta Since the tests have passed fine on a variety of other systems, I think we can assume it was some fluke, and go ahead and merge?

**Review by migueldiascosta — APPROVED** [review]
lgtm

**Comment by migueldiascosta** [comment]
Going in, thanks @boegel!

**Pull request merged**
