### PR TITLE
{numlib}[foss/2022b] preCICE v2.5.0

### PR DESCRIPTION
**Pull request by branfosj**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by branfosj** [comment]
Test report by @branfosj
**SUCCESS**
Build succeeded for 2 out of 2 (1 easyconfigs in total)
bear-pg0105u03b - Linux RHEL 8.6, x86_64, Intel(R) Xeon(R) Platinum 8360Y CPU @ 2.40GHz (icelake), Python 3.6.8
See https://gist.github.com/branfosj/5a2959fd9340e59856ec5447e4e5449f for a full test report.

**Comment by verdurin** [comment]
@boegelbot please test @ generoso

**Comment by verdurin** [comment]
Test report by @verdurin
**FAILED**
Build succeeded for 2 out of 3 (1 easyconfigs in total)
easybuild-c7.novalocal - Linux CentOS Linux 7.9.2009, x86_64, Intel Xeon Processor (Skylake, IBRS), Python 3.6.8
See https://gist.github.com/verdurin/7737f58fdf0da99e7c4d2b77c72b9a1b for a full test report.

**Comment by furstj** [comment]
This is (almost) duplicate of PR #18802. There is -DPRECICE_PythonActions=ON in my version whereas yours has better sanity checking...

**Comment by branfosj** [comment]
closing in favour of #18802

**Pull request closed without merging**
