### PR TITLE
{math}[fosscuda/2017b,intelcuda/2017b] magma v2.3.0

### PR DESCRIPTION
**Pull request by vanzod**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by akesandgren** [comment]
Test report by @akesandgren
**SUCCESS**
Build succeeded for 3 out of 3 (2 easyconfigs in this PR)
b-an03.hpc2n.umu.se - Linux ubuntu 16.04, Intel(R) Xeon(R) CPU E5-2690 v4 @ 2.60GHz, Python 2.7.12
See https://gist.github.com/13953a89a4b17ea2483b31a598d6030c for a full test report.

**Comment by akesandgren** [comment]
Btw, why 2.3.0 when 2.4.0 has been out since June?

**Comment by vanzod** [comment]
A user asked for this specific version. I will add 2.4.0 to the 2018b toolchain.

**Comment by akesandgren** [comment]
intel 2018(a|b) is not compatible with CUDA9.x for that we probably need CUDA 10, at least I hope Nvidia has gotten that far then.

**Comment by akesandgren** [comment]
Going in, thanks @vanzod

**Pull request merged**
