### PR TITLE
fix test step for libxc 4.3.4 and 5.1.x when using RPATH linking

### LINKED ISSUE #11900: libxc regression test fails when using RPATH
this is because the regression test is done before the install step, so the library is not there yet

RPATH in `xc-regression` does include `$ORIGIN:$ORIGIN/../lib:$ORIGIN/../lib64` (I suppose CMAKE is adding these?), but the library in this particular case is at `$ORIGIN/../`

more generically, easybuild could either not use RPATH with test binaries, or run a sanity check on the any test binaries and make sure all required libraries can be found with the relative `$ORIGIN` paths?

### PR DESCRIPTION
**Pull request by boegel**
(created using `eb --new-pr`)

fixes #11900

### CODE REVIEW

**Comment by boegel** [comment]
@boegelbot please test @ generoso

**Comment by migueldiascosta** [comment]
fixes https://github.com/easybuilders/easybuild-easyconfigs/issues/11900 for `libxc`, but isn't there a more generic fix? It seems this will happen for other stuff...

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 10 out of 10 (10 easyconfigs in total)
node2619.swalot.os - Linux centos linux 7.9.2009, x86_64, Intel(R) Xeon(R) CPU E5-2660 v3 @ 2.60GHz (haswell), Python 3.6.8
See https://gist.github.com/79bce1a44f76b1edbc17453935863e54 for a full test report.

**Comment by branfosj** [comment]
Test report by @branfosj
**SUCCESS**
Build succeeded for 10 out of 10 (10 easyconfigs in total)
bear-pg0211u08b.bear.cluster - Linux RHEL 8.3, x86_64, Intel(R) Xeon(R) Gold 6248 CPU @ 2.50GHz (cascadelake), Python 3.6.8
See https://gist.github.com/a54ccced57c0504e30e7ec201f36f6d0 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 10 out of 10 (10 easyconfigs in total)
node3563.doduo.os - Linux RHEL 8.2, x86_64, AMD EPYC 7552 48-Core Processor (zen2), Python 3.6.8
See https://gist.github.com/e4d5068caaff5c4880ea98c71e097bad for a full test report.

**Comment by boegel** [comment]
> fixes #11900 for `libxc`, but isn't there a more generic fix? It seems this will happen for other stuff...

We also ran into this with FlexiBLAS (see #12476). The problem is that we explicitly filter out the build directory from the RPATH section in our wrapper, because it doesn't make sense to have that path there in the final installation.

Maybe we need a way of not doing that during the test step?

It's not a disaster if path to the build directory leak into binaries/libraries that get installed, but it's not clean.

**Comment by migueldiascosta** [comment]
I think we can merge this, but either keep #11900 open or create a new issue about RPATH and test binaries in general

**Comment by boegel** [comment]
I opened a dedicated issue, so we can go ahead and merge this PR: https://github.com/easybuilders/easybuild-framework/issues/3694

**Review by migueldiascosta — APPROVED** [review]
lgtm

**Comment by migueldiascosta** [comment]
Going in, thanks @boegel!

**Pull request merged**
