### PR TITLE
{bio}[foss/2018a] fatslim v0.2.1 w/ Python 3.6.4

### PR DESCRIPTION
**Pull request by arielzn**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by verdurin** [comment]
Test report by @verdurin
**FAILED**
Build succeeded for 0 out of 3 (1 easyconfigs in this PR)
rescomp2 - Linux centos linux 7.3.1611, Intel(R) Xeon(R) Gold 6126 CPU @ 2.60GHz, Python 2.7.5
See https://gist.github.com/cd0987976027f18e5b95a5126415bfcc for a full test report.

**Comment by boegel** [comment]
@verdurin Failing test report looks like a local issue? There's no easyconfig for `ncurses/6.0-golf-2018a` in the central repository...

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
node2494.golett.os - Linux centos linux 7.6.1810, Intel(R) Xeon(R) CPU E5-2680 v3 @ 2.50GHz, Python 2.7.5
See https://gist.github.com/6566cfdc32b360a98ee3e361e51dd9a9 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
node3133.skitty.os - Linux centos linux 7.6.1810, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz, Python 3.6.8
See https://gist.github.com/d1b05fdef293a3ed3f603006683e4864 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
generoso - Linux centos linux 7.6.1810, Intel(R) Xeon(R) CPU E5-2660 v4 @ 2.00GHz, Python 3.6.8
See https://gist.github.com/882647cb0e0cd186c68a1e7b45b708e1 for a full test report.

**Comment by verdurin** [comment]
Test report by @verdurin
**SUCCESS**
Build succeeded for 22 out of 22 (1 easyconfigs in this PR)
easybuild.novalocal - Linux centos linux 7.7.1908, Intel Xeon Processor (Skylake, IBRS), Python 2.7.5
See https://gist.github.com/fc09b9d20e456ceb6b3a2e0b3e30d734 for a full test report.

**Comment by verdurin** [comment]
> lgtm
> 
> @verdurin Let me know what to do with your failing test report

@boegel ignore it - build fine for me elsewhere.

**Comment by verdurin** [comment]
Going in, thanks @arielzn!

**Pull request merged**
