### PR TITLE
Add UCX and PMIx to OpenMPI-3.1.4-gcccuda-2019b

### PR DESCRIPTION
**Pull request by Flamefire**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by Flamefire** [comment]
Test report by @Flamefire
**SUCCESS**
Build succeeded for 6 out of 6 (5 easyconfigs in total)
taurusa5 - Linux centos linux 7.7.1908, x86_64, Intel(R) Xeon(R) CPU E5-2603 v4 @ 1.70GHz, Python 3.6.8
See https://gist.github.com/f5d3bdbe290877ae5f3e5edaa0ca3722 for a full test report.

**Comment by Flamefire** [comment]
Test report by @Flamefire
**SUCCESS**
Build succeeded for 7 out of 7 (5 easyconfigs in total)
taurusml16 - Linux RHEL 7.6, POWER, 8335-GTX, Python 2.7.5
See https://gist.github.com/5438374e63fb79e8fa76dcc1455b7412 for a full test report.

**Comment by boegel** [comment]
closing this since `gcccuda/2019b` is no longer supported, see https://docs.easybuild.io/policies/toolchains

**Comment by Flamefire** [comment]
Yeah I guess after 3 years this is no longer relevant. But does it hurt merging though given it works and brings stuff inline with the similar ECs we have? So just in case someone has to use this to test something or uses this as the base or just wonders why it is different.

**Comment by boegel** [comment]
@Flamefire Easyconfigs with an unsupported toolchain are archived for the upcoming EasyBuild 5.x release anyway, so it's not worth the effort imho.
Let's focus our efforts on recent toolchains...

**Pull request closed without merging**
