### PR TITLE
{system}[dummy/dummy] CUDA v9.2.148.1

### PR DESCRIPTION
**Pull request by wpoely86**
(created using `eb --new-pr`)

This needs easybuilders/easybuild-easyblocks#1481

### CODE REVIEW

**Comment by wpoely86** [comment]
Test report by @wpoely86
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
nic170 - Linux centos linux 7.5.1804, Intel(R) Xeon(R) CPU E5-2683 v4 @ 2.10GHz, Python 2.7.5
See https://gist.github.com/6d2310cc3078526c6dfc8bc07253d25d for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
node2594.golett.os - Linux centos linux 7.4.1708, Intel(R) Xeon(R) CPU E5-2680 v3 @ 2.50GHz, Python 2.7.5
See https://gist.github.com/85eb5c4ec154d7a8e1f2931a1cb26ec3 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
gligar03.gligar.os - Linux centos linux 7.5.1804, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.7.5
See https://gist.github.com/2939abbfa32fc4bdfee95bc0f40c2b2e for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
node3110.skitty.os - Linux centos linux 7.4.1708, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz, Python 2.7.5
See https://gist.github.com/3f32b7b7a824e0588b079083abf9caaa for a full test report.

**Comment by boegel** [comment]
@wpoely86 Hmm, these test reports were successful without me using the updated `CUDA` easyblock from https://github.com/easybuilders/easybuild-easyblocks/pull/1481 ...

Can we add something to the sanity check to verify the patch version or something like that to catch that?

**Comment by wpoely86** [comment]
There seems to be a file `version.txt` in the root with as contents:

```
CUDA Version 9.2.148
CUDA Patch Version 9.2.148.1
```

I can add a grep to the sanity check

**Comment by boegel** [comment]
@wpoely86 Better handle it properly in `sanity_check_step` in the easyblock?

```python
re.search("Version %s" % self.version, ...)
```

**Comment by wpoely86** [comment]
Test report by @wpoely86
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
nic170 - Linux centos linux 7.5.1804, Intel(R) Xeon(R) CPU E5-2683 v4 @ 2.10GHz, Python 2.7.5
See https://gist.github.com/b1c7a58cec778765a5b6bcbf6c7af5d5 for a full test report.

**Comment by wpoely86** [comment]
@boegel easyblock updated

**Comment by boegel** [comment]
@wpoely86 I don't see any changes in https://github.com/easybuilders/easybuild-easyblocks/pull/1481?

**Comment by wpoely86** [comment]
Test report by @wpoely86
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
nic158 - Linux centos linux 7.5.1804, Intel(R) Xeon(R) CPU E5-2680 v2 @ 2.80GHz, Python 2.7.5
See https://gist.github.com/b5bf50a407e67d1049e20bb5726c4909 for a full test report.

**Comment by boegel** [comment]
Going in, thanks @wpoely86!

**Pull request merged**
