### PR TITLE
make sure Python dependency included for ESPResSo is actually used by specifying `-DPYTHON_EXECUTABLE`

### PR DESCRIPTION
**Pull request by maxim-masterov**
Specify python in ESPResSo. See comment [here](https://github.com/EESSI/software-layer/pull/331#issuecomment-1743480608).

### CODE REVIEW

**Comment by boegel** [comment]
Worth clarifying: this is required in EESSI because there we have a very recent "system" Python (3.11) in the compat layer, which CMake happily prefers over the specific Python dependency we're providing.

We saw the same problem with VTK (cfr. #16741), which suggests we should be automatically setting `-DPython3_EXECUTABLE` in the `CMakeMake` easyblock when Python is included as a dependency...

**Comment by boegel** [comment]
@boegelbot please test @ generoso

**Comment by boegel** [comment]
From CMake output, which shows that Python 3.11 from compat layer is picked up, instead of the provided dependency...

```
-- Found PythonInterp: /cvmfs/pilot.eessi-hpc.org/versions/2023.06/compat/linux/aarch64/usr/bin/python3 (found suitable version "3.11.4", minimum required is "3.8")
-- Found Cython: /cvmfs/pilot.eessi-hpc.org/versions/2023.06/compat/linux/aarch64/usr/bin/python3;-m;cython (found suitable version "0.29.35", minimum required is "0.29.14")
-- Found PythonHeaders: /cvmfs/pilot.eessi-hpc.org/versions/2023.06/compat/linux/aarch64/usr/include/python3.11
Traceback (most recent call last):
  File "/cvmfs/pilot.eessi-hpc.org/versions/2023.06/software/linux/aarch64/neoverse_v1/software/SciPy-bundle/2022.05-foss-2022a/lib/python3.10/site-packages/numpy/core/__init__.py", line 23, in <module>
    from . import multiarray
  File "/cvmfs/pilot.eessi-hpc.org/versions/2023.06/software/linux/aarch64/neoverse_v1/software/SciPy-bundle/2022.05-foss-2022a/lib/python3.10/site-packages/numpy/core/multiarray.py", line 10, in <module>
    from . import overrides
  File "/cvmfs/pilot.eessi-hpc.org/versions/2023.06/software/linux/aarch64/neoverse_v1/software/SciPy-bundle/2022.05-foss-2022a/lib/python3.10/site-packages/numpy/core/overrides.py", line 6, in <module>
    from numpy.core._multiarray_umath import (
ModuleNotFoundError: No module named 'numpy.core._multiarray_umath'
```

Looks like we also need to use `-DPython3_FIND_STRATEGY=LOCATION` (the default is `VERSION`, which means preferring the most recent Python version that can be found), or by using `-DCMAKE_POLICY_DEFAULT_CMP_0094=NEW` (cfr. https://cmake.org/cmake/help/latest/policy/CMP0094.html).

It probably doesn't hurt to also specify `-DPython3_ROOT_DIR=$EBROOTPYTHON`, along with `-DPython3_EXECUTABLE` (I think it depends on the `CMakeLists.txt` with `Python3_EXECUTABLE` is actually honored at all).

See also https://cmake.org/cmake/help/latest/module/FindPython3.html

**Comment by boegel** [comment]
Since ESPResSo 4.2.1 uses `find_package(PythonInterp 3.8 REQUIRED)` (see [here](https://github.com/espressomd/espresso/blob/4.2.1/CMakeLists.txt#L177)), apparently the magic keyword is `-DPython_EXECUTABLE=...` (cfr. https://cmake.org/cmake/help/latest/module/FindPython.html), which is not the same as `-DPython3_EXECUTABLE=...`.

Yaay CMake!

**Comment by boegel** [comment]
Wait, `-DPython_EXECUTABLE=...` actually doesn't work, but `-DPYTHON_EXECUTABLE=$EBROOTPYTHON/bin/python` *does* work.

What...

**Comment by boegel** [comment]
Switched to `-DPYTHON_EXECUTABLE` in 66cf178f84 ...

**Comment by branfosj** [comment]
> Wait, `-DPython_EXECUTABLE=...` actually doesn't work, but `-DPYTHON_EXECUTABLE=$EBROOTPYTHON/bin/python` _does_ work.
> 
> What...

CMake [`find_package(PackageName)`](https://cmake.org/cmake/help/v3.27/command/find_package.html#id6) looks for a `Find<PackageName>.cmake` (first inside `CMAKE_MODULE_PATH` and then in the CMake install).

ESPResSo 4.2 uses `find_package(PythonInterp 3.8 REQUIRED)`. So that means [`FindPythonInterp`](https://cmake.org/cmake/help/v3.27/module/FindPythonInterp.html) and so `PYTHON_EXECUTABLE`.

The latest ESPResSO code uses `find_package(Python 3.9 REQUIRED COMPONENTS Interpreter Development NumPy)`. So that means [`FindPython`](https://cmake.org/cmake/help/v3.27/module/FindPython.html) and so `Python_EXECUTABLE`.

**Comment by boegel** [comment]
@boegelbot please test @ generoso

**Review by boegel — APPROVED** [review]
tests in https://github.com/EESSI/software-layer/pull/331 show that fix is working as intended (failure for `aarch64/neoverse_v1` is due to known flaky tests in ESPResSo test suite)

**Comment by boegel** [comment]
Test report by @boegel
**FAILED**
Build succeeded for 3 out of 4 (4 easyconfigs in total)
node3301.joltik.os - Linux RHEL 8.8, x86_64, Intel(R) Xeon(R) Gold 6242 CPU @ 2.80GHz (cascadelake), 1 x NVIDIA Tesla V100-SXM2-32GB, 535.104.12, Python 3.6.8
See https://gist.github.com/boegel/558e77e2b8f86d070df2a714dc540ef0 for a full test report.

**Comment by maxim-masterov** [comment]
Last build failed due to existing lock
```
/user/gent/400/vsc40023/eb_scratch/RHEL8/cascadelake-volta-ib/software/.locks/_user_gent_400_vsc40023_eb_scratch_RHEL8_cascadelake-volta-ib_software_ESPResSo_4.2.1-foss-2022a.lock already exists, aborting!
```

**Comment by boegel** [comment]
Going in, thanks @maxim-masterov!

**Pull request merged**
