### PR TITLE
add support for JupyterHub to TensorBoard

### PR DESCRIPTION
**Pull request by lexming**
Changelog:

* fix issue https://github.com/tensorflow/tensorboard/pull/3142 in `tensorboard-2.10.0-foss-2022a.eb` and `tensorboard-2.15.1-gfbf-2023a.eb`
* `tensorboard-2.15.1-gfbf-2023a.eb`: replace extension on `grpcio` with regular dependency
* `tensorboard-2.15.1-gfbf-2023a.eb`: remove deprecated `tensorboard_plugin_wit` and add `tensorboard-plugin-profile` to be on par with TensorFlow v2.15.1

### CODE REVIEW

**Comment by lexming** [comment]
@boegelbot: please test @ generoso

**Comment by lexming** [comment]
@boegelbot please test @ jsc-zen3

**Review by Micket — APPROVED** [review]
lgtm

**Comment by Micket** [comment]
Test report by @Micket
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in total)
alvis-skylake-build - Linux Rocky Linux 8.9, x86_64, Intel Xeon Processor (Skylake, IBRS, no TSX), Python 3.6.8
See https://gist.github.com/Micket/29ee860170fd69c41cc15363feb11066 for a full test report.

**Pull request merged**
