### PR TITLE
Add Array::Transpose to Perl

### PR DESCRIPTION
**Pull request by verdurin**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by verdurin** [comment]
Test report by @verdurin
**FAILED**
Build succeeded for 2 out of 3 (3 easyconfigs in this PR)
easybuild.novalocal - Linux centos linux 7.8.2003, x86_64, Intel Xeon Processor (Skylake, IBRS), Python 2.7.5
See https://gist.github.com/dfbba313ff9d694fa349d1d5c0c59b70 for a full test report.

**Comment by verdurin** [comment]
Kick Travis.

**Comment by lexming** [comment]
Test report by @lexming
**SUCCESS**
Build succeeded for 3 out of 3 (3 easyconfigs in this PR)
node369.hydra.os - Linux centos linux 7.7.1908, x86_64, Intel(R) Xeon(R) Gold 6148 CPU @ 2.40GHz, Python 2.7.5
See https://gist.github.com/3154af57ae86a57ab905787f1d4bd563 for a full test report.

**Comment by lexming** [comment]
@verdurin should I wait for your test report before merging this PR?

**Comment by verdurin** [comment]
@lexming the local error is:
```
== 2020-06-29 16:00:43,548 build_log.py:169 ERROR EasyBuild crashed with an error (at easybuild/base/exceptions.py:124 in __init__): cmd " perl Makefile.PL PREFIX=/eb/maint/software/Perl/5.30.0-GCCcore-8.3.0 " exited with exit code 1 and output:
Could not find neither libtermcap, libtinfo, libncurses, or libcurses.
 (at easybuild/tools/run.py:533 in parse_cmd_output)
```
so I don't think it's related to this PR.

**Comment by lexming** [comment]
Going in then, thanks @verdurin !

**Pull request merged**
