### PR TITLE
add patch for M4 1.4.17 to fix installation on top of glibc 2.28

### PR DESCRIPTION
**Pull request by boegel**
cfr. #8501 and #8633

applies fix that was already applied for M4 1.4.18 in #7384 to version 1.14.17

M4 1.4.17 easyconfigs that have been archived in #8557, #8564, #8585 were left untouched

### CODE REVIEW

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
node2624.swalot.os - Linux centos linux 7.6.1810, Intel(R) Xeon(R) CPU E5-2660 v3 @ 2.60GHz, Python 2.7.5
See https://gist.github.com/14d2232879da46df243468d1ad3a4237 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 30 out of 30 (30 easyconfigs in this PR)
node2112.delcatty.os - Linux centos linux 7.6.1810, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.7.5
See https://gist.github.com/6b7b43a526fc7a89b1a5e9c8c4aac248 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 0 out of 0 (1 easyconfigs in this PR)
gligar04.gastly.os - Linux fedora 30, Intel(R) Xeon(R) Gold 6130 CPU @ 2.10GHz, Python 2.7.16
See https://gist.github.com/21bba0b7c34aad26db3fb6509f7aab43 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
gligar04.gastly.os - Linux fedora 30, Intel(R) Xeon(R) Gold 6130 CPU @ 2.10GHz, Python 2.7.16
See https://gist.github.com/00d569ff86e2a4c1a9fbd9c9e0908585 for a full test report.

**Comment by vanzod** [comment]
Test report by @vanzod
**SUCCESS**
Build succeeded for 3 out of 3 (3 easyconfigs in this PR)
cermis - Linux debian 9.9, Intel(R) Xeon(R) CPU           X5670  @ 2.93GHz, Python 2.7.13
See https://gist.github.com/1ae79df8cbcbfa9c0254ae724d9ca245 for a full test report.

**Comment by vanzod** [comment]
Going in, thanks @boegel!

**Pull request merged**
