### PR TITLE
WIP: Xvfb: Adding missing dependencies as components

### PR DESCRIPTION
**Pull request by edmondac**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by edmondac** [comment]
This also needs an Autoconf build dep, and possibly a Python dep or build dep...

**Comment by smoors** [comment]
@edmondac if it needs Autoconf as builddep, why don't you add it to the easyconfig? `Autoconf/2.69-GCCcore-8.3.0`
can you please also explain what you mean with 'and possibly a Python dep or build dep'?

**Comment by edmondac** [comment]
Hi @smoors that comment was meant to be a note for me to come back to later. Sorry for the confusion!

**Comment by smoors** [comment]
ok, so this PR is not finished yet? can you update the title with WIP then?

**Comment by edmondac** [comment]
Sure - I thought making it draft would suffice.

**Pull request closed without merging**
