### PR TITLE
libxslt-1.1.34-GCCcore-11.3.0.eb: Adding pkgconf as a dependency to get out of XZ lib issues.

### PR DESCRIPTION
**Pull request by terjekv**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by terjekv** [comment]
Core cause (from @zao):

````
[easybuild@eb-rocky9-mim ~]$ pkg-config --atleast-pkgconfig-version 0.9.0; echo $?
rpm: symbol lookup error: /lib64/librpmio.so.9: undefined symbol: lzma_stream_encoder_mt, version XZ_5.2
/usr/bin/pkg-config: line 8: /usr/bin/-pkg-config: No such file or directory
127
````

@ocaisa pointed out that the XZ patch has a proper patch from the developer: https://github.com/easybuilders/easybuild-easyconfigs/issues/14991#issuecomment-1247353981

**Comment by jfgrimm** [comment]
Test report by @jfgrimm
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
node109.pri.viking.alces.network - Linux CentOS Linux 7.9.2009, x86_64, Intel(R) Xeon(R) Gold 6138 CPU @ 2.00GHz (skylake_avx512), Python 3.6.8
See https://gist.github.com/74a1d937bc7320e73f6272f8d458b181 for a full test report.

**Comment by branfosj** [comment]
> @ocaisa pointed out that the XZ patch has a proper patch from the developer: https://github.com/easybuilders/easybuild-easyconfigs/issues/14991#issuecomment-1247353981

See fix for the XZ issue in #18250

**Comment by branfosj** [comment]
#18250 should fix the underlying issue, so I'll close this PR. If it does not, then please reopen.

**Pull request closed without merging**
