### PR TITLE
{cae}[foss/2019b] OpenFOAM v1912

### PR DESCRIPTION
**Pull request by branfosj**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by branfosj** [comment]
Test report by @branfosj
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
bear-pg0211u03a.bear.cluster - Linux centos linux 7.7.1908, Intel(R) Xeon(R) Gold 6248 CPU @ 2.50GHz, Python 2.7.5
See https://gist.github.com/b3516ead5edecdfa1b293faba48eb5a5 for a full test report.

**Comment by branfosj** [comment]
Test report by @branfosj
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
bb2c1a10.bb2.cluster - Linux centos linux 7.7.1908, Intel(R) Xeon(R) CPU E5-2660 0 @ 2.20GHz, Python 2.7.5
See https://gist.github.com/a1417fef99718479e919cc6cd6bc276c for a full test report.

**Comment by furstj** [comment]
Test report by @furstj
**FAILED**
Build succeeded for 0 out of 1 (1 easyconfigs in this PR)
pc-12101-fuji - Linux UNKNOWN UNKNOWN, Intel(R) Xeon(R) CPU E3-1241 v3 @ 3.50GHz, Python 3.6.9
See https://gist.github.com/2bdd4e9666f053a7b7251dd837d29fda for a full test report.

**Comment by furstj** [comment]
Test report by @furstj
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
pc-12101-fuji - Linux UNKNOWN UNKNOWN, Intel(R) Xeon(R) CPU E3-1241 v3 @ 3.50GHz, Python 3.6.9
See https://gist.github.com/87429663e2558385abe071c0aa17ca79 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
generoso-1 - Linux centos linux 7.6.1810, Intel(R) Xeon(R) CPU E5-2660 v4 @ 2.00GHz, Python 3.6.8
See https://gist.github.com/dc3cddcba90b451a2b468d26f8692510 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
node3147.skitty.os - Linux centos linux 7.7.1908, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz, Python 3.6.8
See https://gist.github.com/f3fceac9bdbe2ebaf37421546f72c604 for a full test report.

**Comment by boegel** [comment]
Going in, thanks @branfosj!

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
node2414.golett.os - Linux centos linux 7.7.1908, Intel(R) Xeon(R) CPU E5-2680 v3 @ 2.50GHz, Python 2.7.5
See https://gist.github.com/b15a48288914294342f835479a4d4704 for a full test report.

**Pull request merged**
