### PR TITLE
Add Tkinter sanity check to matplotlib (foss toolchains)

### PR DESCRIPTION
**Pull request by schiotz**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by schiotz** [comment]
I have added Tkinter sanity checks to matplotlib as discussed in PR #5658 

@boegel I have only done it for foss toolchains 2016b and 2017b, as there is no Tk for foss-2017a and those are the only three toolchains I can test locally.  I will do the same for newer Intel toolchains in a separate PR.

**Comment by schiotz** [comment]
Test report by @schiotz
**SUCCESS**
Build succeeded for 10 out of 10 (6 easyconfigs in this PR)
thul.fysik.dtu.dk - Linux centos linux 7.4.1708, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.7.5
See https://gist.github.com/996c1608249f952583bbfc214982d58d for a full test report.

**Comment by boegel** [comment]
@schiotz Please make the same changes to the two `matplotlib` easyconfigs using `foss/2017a`, since otherwise it's a bit inconsistent, just add the required `Tk` easyconfig as well.

Not doing so for `matplotlib` easyconfigs that use a toolchain older than `foss/2016b` makes sense though.

**Comment by schiotz** [comment]
@boegel I finally found time to add the configs for the foss/2017a toolchain.

**Comment by schiotz** [comment]
@boegel Is there anything more I should do regarding this PR?

**Comment by boegel** [comment]
Sorry for not getting back to this earlier @schiotz, your last update drowned in my inbox...

I'll get this merged ASAP, and then issue a PR on top of this myself to make this consistent in the recent `matplotlib` easyconfigs that built with `intel`.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 11 out of 11 (11 easyconfigs in this PR)
node2428.golett.os - Linux centos linux 7.4.1708, Intel(R) Xeon(R) CPU E5-2680 v3 @ 2.50GHz, Python 2.7.5
See https://gist.github.com/61de737edab59ba049cd81978f04b727 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 11 out of 11 (11 easyconfigs in this PR)
gligar03.gligar.os - Linux centos linux 7.4.1708, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.7.5
See https://gist.github.com/00ca653ae753a3fa50ec39895c507910 for a full test report.

**Comment by boegel** [comment]
Going in, thanks @schiotz!

**Pull request merged**
