### PR TITLE
{bio}[foss/2020a] PhyloPhlAn v3.0 w/ Python 3.8.2

### PR DESCRIPTION
**Pull request by manifestoso**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by manifestoso** [comment]
Test report by @robqiao
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
hpc-head01 - Linux UNKNOWN UNKNOWN, x86_64, Intel(R) Xeon(R) Gold 6130 CPU @ 2.10GHz, Python 3.9.6
See https://gist.github.com/945563f42c1cd59aa4c2beca305a47aa for a full test report.

**Review by lexming — COMMENTED** [review]
Thanks for your contribution. I see that you already added all the dependencies of PhyloPhlAn, but apparently it also needs some external tools to work (see https://github.com/biobakery/phylophlan/wiki#external-tools). I have no experience with PhyloPhlAn, should we also include a minimum set of those externals tools as dependencies here to be able to use PhyloPhlAn, or does it provide some functionality without them?
We already have easyconfigs for most of those external tools, so adding a minimum set here should be easy.

**Comment by manifestoso** [comment]
> Thanks for your contribution. I see that you already added all the dependencies of PhyloPhlAn, but apparently it also needs some external tools to work (see https://github.com/biobakery/phylophlan/wiki#external-tools). I have no experience with PhyloPhlAn, should we also include a minimum set of those externals tools as dependencies here to be able to use PhyloPhlAn, or does it provide some functionality without them? We already have easyconfigs for most of those external tools, so adding a minimum set here should be easy.

@lexming `phylophlan` is a collection of pipelines and methods. For the completeness and improving reproducibility, I think we should include those ext tools. 👍

**Comment by manifestoso** [comment]
Test report by @robqiao
**FAILED**
Build succeeded for 2 out of 3 (3 easyconfigs in total)
hpc-head01 - Linux UNKNOWN UNKNOWN, x86_64, Intel(R) Xeon(R) Gold 6130 CPU @ 2.10GHz, Python 3.9.6
See https://gist.github.com/ac67a2920c3c4e2fe29338dcc22dabf0 for a full test report.

**Comment by manifestoso** [comment]
> > Thanks for your contribution. I see that you already added all the dependencies of PhyloPhlAn, but apparently it also needs some external tools to work (see https://github.com/biobakery/phylophlan/wiki#external-tools). I have no experience with PhyloPhlAn, should we also include a minimum set of those externals tools as dependencies here to be able to use PhyloPhlAn, or does it provide some functionality without them? We already have easyconfigs for most of those external tools, so adding a minimum set here should be easy.
> 
> @lexming `phylophlan` is a collection of pipelines and methods. For the completeness and improving reproducibility, I think we should include those ext tools. 👍 I will update this PR.

@lexming done.

**Comment by manifestoso** [comment]
Test report by @robqiao
**FAILED**
Build succeeded for 2 out of 3 (3 easyconfigs in total)
hpc-head01 - Linux UNKNOWN UNKNOWN, x86_64, Intel(R) Xeon(R) Gold 6130 CPU @ 2.10GHz, Python 3.9.6
See https://gist.github.com/e10b43f82617405d7006d586d616039a for a full test report.

**Comment by manifestoso** [comment]
Test report by @robqiao
**SUCCESS**
Build succeeded for 3 out of 3 (3 easyconfigs in total)
hpc-head01 - Linux UNKNOWN UNKNOWN, x86_64, Intel(R) Xeon(R) Gold 6130 CPU @ 2.10GHz, Python 3.9.6
See https://gist.github.com/41bff7f05e636b4123a1450685b606d3 for a full test report.

**Comment by lexming** [comment]
@boegelbot: please test @ generoso

**Comment by lexming** [comment]
Test report by @lexming
**SUCCESS**
Build succeeded for 12 out of 12 (3 easyconfigs in total)
node308.hydra.os - Linux centos linux 7.9.2009, x86_64, Intel(R) Xeon(R) Gold 6148 CPU @ 2.40GHz, Python 2.7.5
See https://gist.github.com/ae868a909cbbc95aabe0f7794dbcc063 for a full test report.

**Review by lexming — APPROVED** [review]
Thanks for the update @manifestoso 

LGTM

**Comment by lexming** [comment]
Going in, thanks @manifestoso !

**Pull request merged**
