### PR TITLE
{lib}[fosscuda/2019b] TensorFlow v1.15.2, TensorFlow v2.0.1 w/ Python 3.7.2 + 3.7.4

### PR DESCRIPTION
**Pull request by Flamefire**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by Flamefire** [comment]
Test report by @Flamefire
**FAILED**
Build succeeded for 0 out of 5 (5 easyconfigs in this PR)
taurusi6011.taurus.hrsk.tu-dresden.de - Linux RHEL 7.7, Intel(R) Xeon(R) CPU E5-2680 v3 @ 2.50GHz, Python 2.7.5
See https://gist.github.com/e02e30a7b2cc88d2b9fd6fd979677c7c for a full test report.

**Comment by Flamefire** [comment]
Test report by @Flamefire
**FAILED**
Build succeeded for 1 out of 5 (5 easyconfigs in this PR)
taurusi6037.taurus.hrsk.tu-dresden.de - Linux RHEL 7.7, Intel(R) Xeon(R) CPU E5-2680 v3 @ 2.50GHz, Python 2.7.5
See https://gist.github.com/18edc648cd251b8ff708a58613172636 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**FAILED**
Build succeeded for 1 out of 2 (2 easyconfigs in this PR)
node3105.skitty.os - Linux centos linux 7.7.1908, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz, Python 3.6.8
See https://gist.github.com/316d592f8711945b7f2aec7b0bf342af for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**FAILED**
Build succeeded for 7 out of 9 (5 easyconfigs in this PR)
node3300.joltik.os - Linux centos linux 7.7.1908, Intel(R) Xeon(R) Gold 6242 CPU @ 2.80GHz, Python 3.6.8
See https://gist.github.com/84876aa7df83d0e54d55d86ca323b9fa for a full test report.

**Comment by Flamefire** [comment]
Test report by @Flamefire
**FAILED**
Build succeeded for 4 out of 5 (5 easyconfigs in this PR)
taurusi6459.taurus.hrsk.tu-dresden.de - Linux RHEL 7.7, Intel(R) Xeon(R) CPU E5-2680 v3 @ 2.50GHz, Python 2.7.5
See https://gist.github.com/299ca90bf31da01fba8076df3bb026d8 for a full test report.

**Comment by boegel** [comment]
@Flamefire What's going wrong here?

**Comment by Flamefire** [comment]
Guess I forgot to add `-r` when submitting the job (I moved most of my Install tree but some got lost in the process).
Previously somehow my checksum update was not committed for the main source although I used `--update-checksums`. Done that manually now due to lack of time to investigate deeper what went wrong. It should build now

**Comment by Flamefire** [comment]
Test report by @Flamefire
**FAILED**
Build succeeded for 2 out of 6 (5 easyconfigs in this PR)
taurusi6412.taurus.hrsk.tu-dresden.de - Linux RHEL 7.7, Intel(R) Xeon(R) CPU E5-2680 v3 @ 2.50GHz, Python 2.7.5
See https://gist.github.com/eb622a0418112c88ca780b9dfa27e0bc for a full test report.

**Comment by Flamefire** [comment]
Test report by @Flamefire
**FAILED**
Build succeeded for 5 out of 6 (5 easyconfigs in this PR)
taurusi6234.taurus.hrsk.tu-dresden.de - Linux RHEL 7.7, Intel(R) Xeon(R) CPU E5-2680 v3 @ 2.50GHz, Python 2.7.5
See https://gist.github.com/adb50e827599ae5c153c2d09045409d0 for a full test report.

**Comment by boegel** [comment]
@Flamefire Computer still says no ;)

**Comment by Flamefire** [comment]
Computer is stupid -.- google.protobuf not found? This rings a bell, but thought this is fixed

**Comment by Flamefire** [comment]
This is driving me nuts. Just tried this again interactively and I get:

```
ERROR: /dev/shm/s3248973-EasyBuild/TensorFlow/2.0.1/foss-2019a-Python-3.7.2/TensorFlow/tensorflow-2.0.1/tensorflow/python/keras/api/BUILD:13:1: Executing genrule //tensorflow/python/keras/api:keras_python_api_gen failed (Exit 1): bash fai
led: error executing command 
  (cd /tmp/easybuild-tmp/eb-8rafXa/tmpOJXbMW-bazel-build/execroot/org_tensorflow && \
  exec env - \
    EBPYTHONPREFIXES=/sw/installed/h5py/2.9.0-foss-2019a:/sw/installed/SciPy-bundle/2019.03-foss-2019a \
    LD_LIBRARY_PATH=/sw/installed/HDF5/1.10.5-gompi-2019a/lib:/sw/installed/Szip/2.1.1-GCCcore-8.2.0/lib:/sw/installed/SciPy-bundle/2019.03-foss-2019a/lib/python2.7/site-packages/numpy/core/lib:/sw/installed/SciPy-bundle/2019.03-foss-2019
a/lib/python3.7/site-packages/numpy/core/lib:/sw/installed/SciPy-bundle/2019.03-foss-2019a/lib:/sw/installed/Python/3.7.2-GCCcore-8.2.0/lib:/sw/installed/libffi/3.2.1-GCCcore-8.2.0/lib64:/sw/installed/libffi/3.2.1-GCCcore-8.2.0/lib:/sw/in
stalled/GMP/6.1.2-GCCcore-8.2.0/lib:/sw/installed/SQLite/3.27.2-GCCcore-8.2.0/lib:/sw/installed/Tcl/8.6.9-GCCcore-8.2.0/lib:/sw/installed/libreadline/8.0-GCCcore-8.2.0/lib:/sw/installed/bzip2/1.0.6-GCCcore-8.2.0/lib:/sw/installed/ScaLAPAC
K/2.0.2-gompi-2019a-OpenBLAS-0.3.5/lib:/sw/installed/FFTW/3.3.8-gompi-2019a/lib:/sw/installed/OpenBLAS/0.3.5-GCC-8.2.0-2.31.1/lib:/sw/installed/OpenMPI/3.1.3-GCC-8.2.0-2.31.1/lib:/sw/installed/hwloc/1.11.11-GCCcore-8.2.0/lib:/sw/installed
/libpciaccess/0.14-GCCcore-8.2.0/lib:/sw/installed/numactl/2.0.12-GCCcore-8.2.0/lib:/sw/installed/binutils/2.31.1-GCCcore-8.2.0/lib:/sw/installed/Perl/5.28.1-GCCcore-8.2.0/lib:/sw/installed/gettext/0.19.8.1-GCCcore-8.2.0/lib:/sw/installed
/ncurses/6.1-GCCcore-8.2.0/lib:/sw/installed/libxml2/2.9.8-GCCcore-8.2.0/lib:/sw/installed/XZ/5.2.4-GCCcore-8.2.0/lib:/sw/installed/expat/2.2.6-GCCcore-8.2.0/lib:/sw/installed/cURL/7.63.0-GCCcore-8.2.0/lib:/sw/installed/zlib/1.2.11-GCCcor
e-8.2.0/lib:/lustre/ssd/ws/s3248973-EasyBuild/easybuild-haswell/software/protobuf/3.7.1-GCCcore-8.2.0/lib64:/sw/installed/Java/11.0.2/lib:/sw/installed/GCCcore/8.2.0/lib/gcc/x86_64-pc-linux-gnu/8.2.0:/sw/installed/GCCcore/8.2.0/lib64:/sw/
installed/GCCcore/8.2.0/lib \
    PATH=/sw/installed/h5py/2.9.0-foss-2019a/bin:/sw/installed/HDF5/1.10.5-gompi-2019a/bin:/sw/installed/SciPy-bundle/2019.03-foss-2019a/bin:/sw/installed/Python/3.7.2-GCCcore-8.2.0/bin:/sw/installed/SQLite/3.27.2-GCCcore-8.2.0/bin:/sw/installed/Tcl/8.6.9-GCCcore-8.2.0/bin:/sw/installed/libreadline/8.0-GCCcore-8.2.0/bin:/sw/installed/bzip2/1.0.6-GCCcore-8.2.0/bin:/sw/installed/FFTW/3.3.8-gompi-2019a/bin:/sw/installed/OpenBLAS/0.3.5-GCC-8.2.0-2.31.1/bin:/sw/installed/OpenMPI/3.1.3-GCC-8.2.0-2.31.1/bin:/sw/installed/hwloc/1.11.11-GCCcore-8.2.0/sbin:/sw/installed/hwloc/1.11.11-GCCcore-8.2.0/bin:/sw/installed/numactl/2.0.12-GCCcore-8.2.0/bin:/sw/installed/binutils/2.31.1-GCCcore-8.2.0/bin:/sw/installed/git/2.21.0-GCCcore-8.2.0-nodocs/bin:/sw/installed/Perl/5.28.1-GCCcore-8.2.0/bin:/sw/installed/gettext/0.19.8.1-GCCcore-8.2.0/bin:/sw/installed/ncurses/6.1-GCCcore-8.2.0/bin:/sw/installed/libxml2/2.9.8-GCCcore-8.2.0/bin:/sw/installed/XZ/5.2.4-GCCcore-8.2.0/bin:/sw/installed/expat/2.2.6-GCCcore-8.2.0/bin:/sw/installed/cURL/7.63.0-GCCcore-8.2.0/bin:/lustre/ssd/ws/s3248973-EasyBuild/easybuild-haswell/software/protobuf/3.7.1-GCCcore-8.2.0/bin:/sw/installed/Bazel/0.26.1-GCCcore-8.2.0/bin:/sw/installed/Java/11.0.2:/sw/installed/Java/11.0.2/bin:/sw/installed/GCCcore/8.2.0/bin:/home/s3248973/.local/EasyBuildDev/easybuild-framework:/home/s3248973/.local/bin:/usr/lib64/qt-3.3/bin:/sw/taurus/tools/slurmtools/default/bin:/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/opt/ibutils/bin:/opt/puppetlabs/bin \
    PYTHONPATH=/lustre/ssd/ws/s3248973-EasyBuild/easybuild-haswell/software/TensorFlow/2.0.1-foss-2019a-Python-3.7.2/lib/python3.7/site-packages:/lustre/ssd/ws/s3248973-EasyBuild/easybuild-haswell/software/TensorFlow/2.0.1-foss-2019a-Python-3.7.2/lib/python3.7/site-packages:/sw/installed/Python/3.7.2-GCCcore-8.2.0/easybuild/python \
    PYTHON_BIN_PATH=/sw/installed/Python/3.7.2-GCCcore-8.2.0/bin/python \
    PYTHON_LIB_PATH=/lustre/ssd/ws/s3248973-EasyBuild/easybuild-haswell/software/TensorFlow/2.0.1-foss-2019a-Python-3.7.2/lib/python3.7/site-packages \
    TF2_BEHAVIOR=1 \
    TF_CONFIGURE_IOS=0 \
  /bin/bash -c 'source external/bazel_tools/tools/genrule/genrule-setup.sh; bazel-out/k8-opt/bin/tensorflow/python/keras/api/create_tensorflow.python_api_1_keras_python_api_gen  --apidir=bazel-out/k8-py2-opt/bin/tensorflow/python/keras/api --apiname=keras --apiversion=1  --loading=default --package=tensorflow.python,tensorflow.python.keras --output_package=tensorflow.python.keras.api --use_relative_imports=True bazel-out/k8-py2-opt/bin/tensorflow/python/keras/api/__init__.py bazel-out/k8-py2-opt/bin/tensorflow/python/keras/api/keras/__init__.py bazel-out/k8-py2-[...]
Traceback (most recent call last):
  File "/tmp/easybuild-tmp/eb-8rafXa/tmpOJXbMW-bazel-build/execroot/org_tensorflow/bazel-out/k8-opt/bin/tensorflow/python/keras/api/create_tensorflow.python_api_1_keras_python_api_gen.runfiles/org_tensorflow/tensorflow/python/tools/api/generator/create_python_api.py", line 27, in <module>
    from tensorflow.python.tools.api.generator import doc_srcs
  File "/tmp/easybuild-tmp/eb-8rafXa/tmpOJXbMW-bazel-build/execroot/org_tensorflow/bazel-out/k8-opt/bin/tensorflow/python/keras/api/create_tensorflow.python_api_1_keras_python_api_gen.runfiles/org_tensorflow/tensorflow/python/__init__.py", line 52, in <module>
    from tensorflow.core.framework.graph_pb2 import *
  File "/tmp/easybuild-tmp/eb-8rafXa/tmpOJXbMW-bazel-build/execroot/org_tensorflow/bazel-out/k8-opt/bin/tensorflow/python/keras/api/create_tensorflow.python_api_1_keras_python_api_gen.runfiles/org_tensorflow/tensorflow/core/framework/graph_pb2.py", line 7, in <module>
    from google.protobuf import descriptor as _descriptor
ModuleNotFoundError: No module named 'google.protobuf'
```

To break that down: `python -c 'import google.protobuf'` seems to fail although ` PYTHONPATH=/lustre/ssd/ws/s3248973-EasyBuild/easybuild-haswell/software/TensorFlow/2.0.1-foss-2019a-Python-3.7.2/lib/python3.7/site-packages:/lustre/ssd/ws/s3248973-EasyBuild/easybuild-haswell/software/TensorFlow/2.0.1-foss-2019a-Python-3.7.2/lib/python3.7/site-packages:/sw/installed/Python/3.7.2-GCCcore-8.2.0/easybuild/python` is set. If I manually do `PYTHONPATH=/lustre/ssd/ws/s3248973-EasyBuild/easybuild-haswell/software/TensorFlow/2.0.1-foss-2019a-Python-3.7.2/lib/python3.7/site-packages:/lustre/ssd/ws/s3248973-EasyBuild/easybuild-haswell/software/TensorFlow/2.0.1-foss-2019a-Python-3.7.2/lib/python3.7/site-packages:/sw/installed/Python/3.7.2-GCCcore-8.2.0/easybuild/python python -c 'import google.protobuf'` I don't get an error

**Comment by Flamefire** [comment]
Ok found the issue: We need `PYTHONNOUSERSITE=1` set for TF. I had another google folder in my local site-packages.

**Comment by Flamefire** [comment]
Test report by @Flamefire
**SUCCESS**
Build succeeded for 5 out of 5 (5 easyconfigs in this PR)
taurusi6283.taurus.hrsk.tu-dresden.de - Linux RHEL 7.7, Intel(R) Xeon(R) CPU E5-2680 v3 @ 2.50GHz, Python 2.7.5
See https://gist.github.com/a94171abb2bb3147d17a637466a156ff for a full test report.

**Comment by Flamefire** [comment]
@boegel Finally done. I'm using an updated EasyBlock for that though to fix the user python path issue: https://github.com/easybuilders/easybuild-easyblocks/pull/2002

**Comment by lexming** [comment]
Test report by @lexming
**SUCCESS**
Build succeeded for 5 out of 5 (5 easyconfigs in this PR)
node252.hydra.os - Linux centos linux 7.7.1908, Intel(R) Xeon(R) CPU E5-2650 v4 @ 2.20GHz, Python 2.7.5
See https://gist.github.com/99f9690b4c6a03784373231140934873 for a full test report.

**Comment by lexming** [comment]
Going in, thanks @Flamefire !

**Comment by boegel** [comment]
Test report by @boegel
**FAILED**
Build succeeded for 0 out of 5 (5 easyconfigs in this PR)
node3100.skitty.os - Linux centos linux 7.7.1908, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz (skylake_avx512), Python 3.6.8
See https://gist.github.com/8cd9f4a1bfad54801dba0ec0e8388634 for a full test report.

**Pull request merged**
