### PR TITLE
add patch to improve CUDA 11 compatibility of `GCCcore/12.2.0` and `GCCcore/12.3.0`

### PR DESCRIPTION
**Pull request by Flamefire**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by Flamefire** [comment]
Test report by @Flamefire
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
taurusml3 - Linux RHEL 7.6, POWER, 8335-GTX, 6 x NVIDIA Tesla V100-SXM2-32GB, 440.64.00, Python 2.7.5
See https://gist.github.com/Flamefire/10e05632966712c7387566bf1015c953 for a full test report.

**Comment by Flamefire** [comment]
Test report by @Flamefire
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
taurusi8016 - Linux CentOS Linux 7.9.2009, x86_64, AMD EPYC 7352 24-Core Processor, 8 x NVIDIA NVIDIA A100-SXM4-40GB, 470.57.02, Python 2.7.5
See https://gist.github.com/Flamefire/24520e3f258c065e8d17eed9e5c14d2c for a full test report.

**Comment by boegel** [comment]
@Flamefire It seems like this same patch could/should be applied to `GCCcore/12.3.0` as well?

```
$ sed -n '1466,1470p' gcc-12.3.0/libstdc++-v3/include/bits/locale_facets_nonio.tcc
      __err = ios_base::goodbit;
      bool __use_state = false;
#if __GNUC__ >= 5 && !defined(__clang__)
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wpmf-conversions"
```

**Comment by Flamefire** [comment]
Yes very likely. However I wanted to get PyTorch working with GCC 12.2 & CUDA 11.7 first to have a proof this works. But takes longer than I thought due to issues with UCX on PPC and new failures in PyTorch on x86/A100

Feel free to add this patch to GCC 12.3 though as it doesn't seem those issues are caused by this patch

**Comment by boegel** [comment]
@boegelbot please test @ generoso
CORE_CNT=16

**Comment by boegel** [comment]
@boegelbot please test @ jsc-zen2
CORE_CNT=16

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in total)
node3159.skitty.os - Linux RHEL 8.8, x86_64, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz (skylake_avx512), Python 3.6.8
See https://gist.github.com/boegel/f1fb1b85ffbf8bbb0fe7b39729a242a9 for a full test report.

**Review by boegel — APPROVED** [review]
lgtm

**Comment by boegel** [comment]
Going in, thanks @Flamefire!

**Pull request merged**
