### PR TITLE
{system}[GCCcore/6.4.0] hwloc v1.11.7

### PR DESCRIPTION
**Pull request by JackPerdue**
(created using `eb --new-pr`)
depends on PR #4942

### CODE REVIEW

**Comment by verdurin** [comment]
Test report by @verdurin
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in this PR)
ca005.camp.thecrick.org - Linux centos linux 7.3.1611, Intel(R) Xeon(R) CPU E5-2640 v3 @ 2.60GHz, Python 2.7.5
See https://gist.github.com/c1617087a052c589b8a4e04925aed20d for a full test report.

**Comment by verdurin** [comment]
@JackPerdue can probably remove `hwloc` from this now?

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in this PR)
node2573.golett.os - Linux centos linux 7.3.1611, Intel(R) Xeon(R) CPU E5-2680 v3 @ 2.50GHz, Python 2.7.5
See https://gist.github.com/7b079bddbc341571b362efb1281fd12f for a full test report.

**Comment by boegel** [comment]
@verdurin I don't see the point in removing the `numactl` easyconfig, since `eb --review-pr` tells us it is no different than the one currently in `develop` (which got merged via #4942)?

It'll only result in adding an extra (basically empty) commit...

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in this PR)
node2070.delcatty.os - Linux centos linux 7.3.1611, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.7.5
See https://gist.github.com/11cbf055ed5482925d25b7dd0ead3063 for a full test report.

**Comment by verdurin** [comment]
Merging, thanks @JackPerdue and @boegel for the review

**Pull request merged**
