### PR TITLE
{cae}[system/system] STAR-CCM+ v17.02.008, STAR-CCM+ v17.04.008

### PR DESCRIPTION
**Pull request by Micket**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by Micket** [comment]
I know the old version we had didn't do this, but i provide but my users frequently request both the normal and -r8 variants, so i introduced the -r8 suffix for the latter.

**Comment by Micket** [comment]
Test report by @Micket
**SUCCESS**
Build succeeded for 3 out of 3 (3 easyconfigs in total)
vera-c2 - Linux Rocky Linux 8.4, x86_64, Intel Xeon Processor (Skylake), Python 3.6.8
See https://gist.github.com/a5acffa5121f6e53325f709491e92083 for a full test report.

**Comment by Micket** [comment]
@boegel since you made the easyblock, perhaps you have access to star-ccm+ to test this PR?

**Comment by Micket** [comment]
Test report by @Micket
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
vera-c2 - Linux Rocky Linux 8.4, x86_64, Intel Xeon Processor (Skylake), Python 3.6.8
See https://gist.github.com/7fcc7a6407c05f27e52065938a90b2f6 for a full test report.

**Review by boegel — APPROVED** [review]
lgtm

**Comment by boegel** [comment]
Going in, thanks @Micket!

**Pull request merged**
