### PR TITLE
{vis}[GCCcore/13.3.0]  Graphviz v12.2.0

### PR DESCRIPTION
**Pull request by stefan-wolfsheimer**
Depends on:
- PR #18527

### CODE REVIEW

**Comment by smoors** [comment]
@stefan-wolfsheimer can you explain why `..._skip-install-data-hook.patch` was removed in this easyconfig?

**Comment by stefan-wolfsheimer** [comment]
> @stefan-wolfsheimer can you explain why `..._skip-install-data-hook.patch` was removed in this easyconfig?
I added the patch to the eb-file. The patch for version 8.1.0 still works for 12.2.0:

`patch -p1 -d graphviz-12.2.0 < Graphviz-8.1.0_skip-install-data-hook.patch
patching file tclpkg/Makefile.am
Hunk #1 succeeded at 30 (offset -2 lines).`

**Comment by stefan-wolfsheimer** [comment]
> > easybuild.tools.build_log.EasyBuildError: 'Missing dependencies: Qt5/5.15.15-GCCcore-13.3.0 (no easyconfig file or existing module found)'

There is a pending PR including Qt5: #21575

Graphviz also works with Qt6. The eb config file has been updated.

**Comment by smoors** [comment]
@boegelbot: please test @ generoso

**Comment by smoors** [comment]
@boegelbot please test @ jsc-zen3

**Review by smoors — APPROVED** [review]
lgtm

**Comment by smoors** [comment]
Going in, thanks @stefan-wolfsheimer!

**Pull request merged**
