### PR TITLE
Draft: Trilinos 13.0.1

### PR DESCRIPTION
**Pull request by robert-mijakovic**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by robert-mijakovic** [comment]
@boegelbot please test @ generoso

**Comment by akesandgren** [comment]
@boegelbot please test @ generoso

**Comment by stefan-wolfsheimer** [comment]
Good afternoon,

is there any update on this PR?

**Comment by boegel** [comment]
@robert-mijakovic Are you planning to follow up on this soon? If not, maybe someone else can take it over...

First step is definitely to sync with `develop` and fix the merge conflicts

**Comment by robert-mijakovic** [comment]
@boegel Somebody else can take it over.

**Comment by branfosj** [comment]
As this PR is WIP or draft and has not been updated in over a year I have closed it. If you work on this again then please reopen the PR.

**Pull request closed without merging**
