### PR TITLE
{debugger,lib}[GCCcore/9.3.0] LLDB v11.0.0, libedit v20191231 w/ Python 3.8

### PR DESCRIPTION
**Pull request by bartoldeman**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by bartoldeman** [comment]
This supersedes part of #11814, by building lldb standalone.
Nicely there is no runtime dependency on LLVM or clang, though I did add one on libedit so to enable command line editing.

**Comment by bartoldeman** [comment]
@boegelbot please test @ generoso

**Review by Micket — APPROVED** [review]
lgtm

**Comment by Micket** [comment]
Test report by @Micket
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in total)
vera-c1 - Linux centos linux 7.9.2009, x86_64, Intel Xeon Processor (Skylake), Python 2.7.5
See https://gist.github.com/f52995dacba4e90813d5727a91959333 for a full test report.

**Comment by Micket** [comment]
Going in, thanks @bartoldeman!

**Pull request merged**
