### PR TITLE
add/reorder missing/misplaced extensions in Python 2.7.15 and 3.6.6 easyconfigs

### PR DESCRIPTION
**Pull request by migueldiascosta**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by migueldiascosta** [comment]
I needed these changes when installing in nodes without access to PyPI, after using `--fetch` on a node with access, but the main question is why doesn't `exts_download_dep_fail = True` catch these downloads on systems with access?

**Comment by boegel** [comment]
@migueldiascosta Can you post a debug log for the problem? Maybe it's specific to CentOS 6?

**Comment by boegel** [comment]
It looks like we missed this because dependencies that are specified via `setup_requires` are being pulled down silently, while dependencies specified via `install_requires` are easily detectable because of the `Downloading ...` message that is printed.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 11 out of 11 (8 easyconfigs in this PR)
node3110.skitty.os - Linux centos linux 7.6.1810, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz, Python 2.7.5
See https://gist.github.com/65f2e24542dbec75b817e2270a019bad for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 11 out of 11 (8 easyconfigs in this PR)
node2412.golett.os - Linux centos linux 7.6.1810, Intel(R) Xeon(R) CPU E5-2680 v3 @ 2.50GHz, Python 2.7.5
See https://gist.github.com/a6148b33e781f225121d45578a82cc9b for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 8 out of 8 (8 easyconfigs in this PR)
node2046.delcatty.os - Linux centos linux 7.6.1810, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.7.5
See https://gist.github.com/79f0a245beedcda9d71dda68b36d7705 for a full test report.

**Comment by boegel** [comment]
Going in, thanks @migueldiascosta!

**Pull request merged**
