### PR TITLE
use 'import deap.base' in sanity check for deap extension in SciPy-bundle 2022.05

### PR DESCRIPTION
**Pull request by boegel**
(created using `eb --new-pr`)

to catch problem being fixed with updating from `deap` 1.3.1 to 1.3.3 in #17413

### CODE REVIEW

**Comment by boegel** [comment]
@boegelbot please test @ generoso
EB_ARGS="--skip"

**Review by Micket — APPROVED** [review]
lgtm

**Comment by Micket** [comment]
Test report by @Micket
**SUCCESS**
Build succeeded for 7 out of 7 (4 easyconfigs in total)
vera-c2 - Linux Rocky Linux 8.6, x86_64, Intel Xeon Processor (Skylake), Python 3.6.8
See https://gist.github.com/e7b3b5027e3374fdec656be341d37ab6 for a full test report.

**Comment by Micket** [comment]
@boegelbot please test @ jsc-zen2
EB_ARGS="--skip"

**Comment by Micket** [comment]
Going in, thanks @boegel!

**Pull request merged**
