### PR TITLE
{data,devel}[GCCcore/12.2.0,foss/2022b] h5py v3.8.0, pkgconfig v1.5.5 w/ Python 3.10.8

### PR DESCRIPTION
**Pull request by VRehnberg**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by VRehnberg** [comment]
Test report by @VRehnberg
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in total)
alvis-c1 - Linux Rocky Linux 8.6, x86_64, Intel Xeon Processor (Skylake), Python 3.6.8
See https://gist.github.com/6ab5333cf1824a38da87104ef25902ff for a full test report.

**Comment by verdurin** [comment]
@boegelbot please test @ generoso

**Comment by verdurin** [comment]
Test report by @verdurin
**FAILED**
Build succeeded for 13 out of 15 (2 easyconfigs in total)
easybuild-c7.novalocal - Linux CentOS Linux 7.9.2009, x86_64, Intel Xeon Processor (Skylake, IBRS), Python 3.6.8
See https://gist.github.com/e9618216f6c7d632a94520b966998e75 for a full test report.

**Comment by VRehnberg** [comment]
@verdurin you need the easyblock from https://github.com/easybuilders/easybuild-easyblocks/pull/2862 to build SciPy-bundle. With that it should hopefully work.

**Comment by verdurin** [comment]
Test report by @verdurin
Using easyblocks from PR(s) https://github.com/easybuilders/easybuild-easyblocks/pull/2862
**FAILED**
Build succeeded for 1 out of 3 (2 easyconfigs in total)
easybuild-c7.novalocal - Linux CentOS Linux 7.9.2009, x86_64, Intel Xeon Processor (Skylake, IBRS), Python 3.6.8
See https://gist.github.com/52b450beb468e151f0512d9f6bc00562 for a full test report.

**Comment by VRehnberg** [comment]
Strange. But the problem still seems to originate from SciPy-bundle so I don't yet see anything I will need to fix in this PR.

**Comment by verdurin** [comment]
Test report by @verdurin
Using easyblocks from PR(s) https://github.com/easybuilders/easybuild-easyblocks/pull/2862
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in total)
easybuild-c7.novalocal - Linux CentOS Linux 7.9.2009, x86_64, Intel Xeon Processor (Skylake, IBRS), Python 3.6.8
See https://gist.github.com/d42b83b2994ae9aa6b32c1e568b93c6f for a full test report.

**Review by verdurin — APPROVED** [review]
Looks fine.

**Comment by verdurin** [comment]
Going in, thanks @VRehnberg!

**Pull request merged**
