### PR TITLE
{lang}[GCCcore/11.3.0] nodejs v16.15.1

### PR DESCRIPTION
**Pull request by branfosj**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by branfosj** [comment]
@boegelbot please test @ jsc-zen2

**Comment by branfosj** [comment]
Test report by @branfosj
**FAILED**
Build succeeded for 0 out of 1 (1 easyconfigs in total)
bear-pg0211u03a.bear.cluster - Linux Ubuntu 20.04.2 LTS (Focal Fossa), x86_64, Intel(R) Xeon(R) Gold 6248 CPU @ 2.50GHz (cascadelake), Python 3.8.5
See https://gist.github.com/0ad192429dae09bf8e12a503c6f32ccd for a full test report.

**Comment by branfosj** [comment]
Test report by @branfosj
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
bear-pg0211u08b.bear.cluster - Linux RHEL 8.6, x86_64, Intel(R) Xeon(R) Gold 6248 CPU @ 2.50GHz (cascadelake), Python 3.6.8
See https://gist.github.com/377624fe0b423b277bfd5469806c6fb4 for a full test report.

**Comment by branfosj** [comment]
@boegelbot please test @ generoso

**Comment by jfgrimm** [comment]
Test report by @jfgrimm
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
node117.pri.viking.alces.network - Linux CentOS Linux 7.9.2009, x86_64, Intel(R) Xeon(R) Gold 6138 CPU @ 2.00GHz (skylake_avx512), Python 3.6.8
See https://gist.github.com/230d2368cfffe2e006c2a516b65a09ee for a full test report.

**Comment by branfosj** [comment]
```
== 2022-06-12 17:56:04,833 build_log.py:169 ERROR EasyBuild crashed with an error (at easybuild/easybuild-framework/easybuild/base/exceptions.py:124 in __init__): cmd "ldd /project/60006/boegelbot/Rocky8/zen2/software/nodejs/16.15.1-GCCcore-11.3.0/bin/node" exited with exit code 1 and output:
	not a dynamic executable
```

This looks like https://bugzilla.redhat.com/show_bug.cgi?id=1817111 - i.e. `ldd` exits with a failure if the item being checked is too big and this results in a false positive.

**Comment by boegel** [comment]
> ```
> == 2022-06-12 17:56:04,833 build_log.py:169 ERROR EasyBuild crashed with an error (at easybuild/easybuild-framework/easybuild/base/exceptions.py:124 in __init__): cmd "ldd /project/60006/boegelbot/Rocky8/zen2/software/nodejs/16.15.1-GCCcore-11.3.0/bin/node" exited with exit code 1 and output:
> 	not a dynamic executable
> ```
> 
> This looks like https://bugzilla.redhat.com/show_bug.cgi?id=1817111 - i.e. `ldd` exits with a failure if the item being checked is too big and this results in a false positive.

That tells me we should relax things a bit in framework, and take into account that `ldd` may fail on some binaries, which is essentially beyond our control...
See https://github.com/easybuilders/easybuild-framework/pull/4033

**Comment by branfosj** [comment]
@boegelbot please test @ generoso

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
node3138.skitty.os - Linux RHEL 8.4, x86_64, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz (skylake_avx512), Python 3.6.8
See https://gist.github.com/e1a840599f0073814fe552a92b337c53 for a full test report.

**Comment by boegel** [comment]
@boegelbot please test @ jsc-zen2

**Review by boegel — APPROVED** [review]
lgtm

**Pull request merged**
