### PR TITLE
{data}[foss/2017b] netCDF v4.5.0

### PR DESCRIPTION
**Pull request by Helios07**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
node2457.golett.os - Linux centos linux 7.4.1708, Intel(R) Xeon(R) CPU E5-2680 v3 @ 2.50GHz, Python 2.7.5
See https://gist.github.com/b0152e446bb463cefd0d2df2db41ba03 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
node2011.delcatty.os - Linux centos linux 7.4.1708, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.7.5
See https://gist.github.com/2f7203cb78bd6abe0c027d6ee2f992ee for a full test report.

**Comment by boegel** [comment]
Going in, thanks @Helios07!

**Comment by Helios07** [comment]
@boegel I'm sorry, but is there a possibility to change the cURL dependency to 7.56.1? There are conflicts at the moment when building R.

**Comment by boegel** [comment]
@Helios07 This is included in EasyBuild v3.5.0, so I'm afraid that ship has sailed...

Why not change the `cURL` version used in R?

**Comment by Helios07** [comment]
Ok, I will try that

**Pull request merged**
