### PR TITLE
rename hyperopt to Hyperopt, to be consistent with existing Hyperopt easyconfigs

### PR DESCRIPTION
**Pull request by lexming**
We have easyconfigs for Hyperopt with both names `Hyperopt` and `hyperopt`. Consolidate names on Hyperopt.

### CODE REVIEW

**Comment by lexming** [comment]
@boegelbot: please test @ generoso

**Comment by lexming** [comment]
Test report by @lexming
**FAILED**
Build succeeded for 23 out of 27 (3 easyconfigs in total)
node200.hydra.os - Linux CentOS Linux 7.9.2009, x86_64, Intel(R) Xeon(R) CPU E5-2680 v4 @ 2.40GHz, Python 3.6.8
See https://gist.github.com/31ac30ad042c52d026f2e0bf6a4b9cba for a full test report.

**Comment by lexming** [comment]
Test report by @lexming
**FAILED**
Build succeeded for 2 out of 6 (3 easyconfigs in total)
node200.hydra.os - Linux CentOS Linux 7.9.2009, x86_64, Intel(R) Xeon(R) CPU E5-2680 v4 @ 2.40GHz, Python 3.6.8
See https://gist.github.com/45bb69bfcbdee0aaec6e8b2d49976720 for a full test report.

**Comment by boegel** [comment]
@lexming Tests failed, looks like we have a missing `CMake` build dep?
```
Please install CMake and all required dependencies first
```

**Comment by lexming** [comment]
@boegelbot: please test @ generoso

**Comment by lexming** [comment]
@boegel thanks for the input, this is ready now

**Review by boegel — APPROVED** [review]
lgtm

**Comment by boegel** [comment]
Going in, thanks @lexming!

**Pull request merged**
