### PR TITLE
{vis}[GCCcore/10.3.0] Pango v1.48.0

### PR DESCRIPTION
**Pull request by robert-mijakovic**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by SebastianAchilles** [comment]
@boegelbot please test @ generoso

**Comment by SebastianAchilles** [comment]
Test report by @sebastianachilles
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
centos8-eb - Linux centos linux 8.3.2011, x86_64, Intel(R) Core(TM) i7-8700 CPU @ 3.20GHz (skylake), Python 3.6.8
See https://gist.github.com/2afdb8248cdd54a9462c0ea7d70e7118 for a full test report.

**Comment by SebastianAchilles** [comment]
Test report by @sebastianachilles
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
rocky8-eb - Linux rocky linux 8.4, x86_64, Intel(R) Core(TM) i7-6900K CPU @ 3.20GHz (broadwell), Python 3.6.8
See https://gist.github.com/7cb0e4eee25696a0054b643dd16d0dae for a full test report.

**Review by SebastianAchilles — APPROVED** [review]
lgtm

**Comment by SebastianAchilles** [comment]
Going in, thanks @robert-mijakovic!

**Comment by boegel** [comment]
@robert-mijakovic Is there any reason you didn't use Pango 1.48.5 (see also #13202)?

**Comment by robert-mijakovic** [comment]
Hm, I have probably overlooked its existence.

**Comment by boegel** [comment]
@robert-mijakovic OK, no worries, just making sure we've not overlooking something.
Just to be clear, we've replaced it with an easyconfig for Pango 1.48.5 in #13202

**Pull request merged**
