### PR TITLE
{perf}[iimpic/2019b,iimpic/2020a] IMB v2019.6

### PR DESCRIPTION
**Pull request by Micket**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by Micket** [comment]
Test report by @Micket
**SUCCESS**
Build succeeded for 3 out of 3 (3 easyconfigs in total)
alvis-c1 - Linux centos linux 7.8.2003, x86_64, Intel Xeon Processor (Skylake), Python 3.6.8
See https://gist.github.com/ba5bcde64dc05dabf5eee2ec8751d79a for a full test report.

**Comment by Micket** [comment]
Test report by @Micket
**SUCCESS**
Build succeeded for 10 out of 10 (8 easyconfigs in total)
vera-c1 - Linux centos linux 7.8.2003, x86_64, Intel Xeon Processor (Skylake), Python 2.7.5
See https://gist.github.com/f2f927808cd87b342d05adb9ce253562 for a full test report.

**Comment by Micket** [comment]
@boegelbot please test @ generoso

**Comment by smoors** [comment]
Test report by @smoors
**FAILED**
Build succeeded for 12 out of 16 (8 easyconfigs in total)
node381.hydra.os - Linux centos linux 7.7.1908, x86_64, Intel(R) Xeon(R) Gold 6148 CPU @ 2.40GHz (skylake_avx512), Python 2.7.5
See https://gist.github.com/4c6523cd42c1fc8fe910896fafab2cf8 for a full test report.

**Comment by smoors** [comment]
ignore the errors, I was testing on a node that does not fully support CUDA.

@Micket in the future, can you split your PRs between CUDA and non-cuda easyconfigs? that would make it easier to test on different architectures.

**Comment by Micket** [comment]
to old to care

**Pull request closed without merging**
