### PR TITLE
{tools}[GCCcore/11.3.0] enchant-2 v2.3.3

### PR DESCRIPTION
**Pull request by iotaka**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by iotaka** [comment]
requires:
* #16998

**Comment by bedroge** [comment]
@boegelbot please test @ generoso

**Comment by bedroge** [comment]
@boegelbot please test @ jsc-zen2

**Comment by bedroge** [comment]
Test report by @bedroge
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
bob-Latitude-5300 - Linux Ubuntu 22.04, x86_64, Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz, Python 3.10.6
See https://gist.github.com/784d3532dad67f29b1b303f66b1c1872 for a full test report.

**Review by bedroge — APPROVED** [review]
lgtm

**Pull request merged**
