### PR TITLE
{bio}[GCCcore/8.3.0] GATK v4.1.7.0 w/ Python 2.7.16 + 3.7.4

### PR DESCRIPTION
**Pull request by verdurin**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by verdurin** [comment]
Test report by @verdurin
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
easybuild.novalocal - Linux centos linux 7.8.2003, x86_64, Intel Xeon Processor (Skylake, IBRS), Python 2.7.5
See https://gist.github.com/a32f00dce6f0ab88f3e124e98218fea9 for a full test report.

**Comment by lexming** [comment]
@verdurin I got crash reports with GATK v4.1.7.0 and Java 11. I suggest to add an easyconfig depending on Java 1.8 and including a warning to this one. In the same way that I've done in #10933

**Review by jfgrimm — COMMENTED** [review]
As decided in issue #16330, we have deprecated the use of `True` to signify a system-toolchain dependency (#16384), in favour of the more intuitive `SYSTEM` template constant. Due to the change in the test suite, please run `eb --sync-pr-with-develop 10741` and update the PR to use `SYSTEM` instead.

**Comment by verdurin** [comment]
Closing because this is obsolete.

**Pull request closed without merging**
