### PR TITLE
use NO_AFFINITY=1 to disable affinity being set by OpenBLAS itself by default

### PR DESCRIPTION
**Pull request by boegel**
This should fix (part of) the problem reported in #605.

### CODE REVIEW

**Comment by boegel** [comment]
Hmm, we never followed up on this...

@fgeorgatos, @pforai: should we still consider using `NO_AFFINITY=1` for all OpenBLAS versions?

@xianyi were any bugs/problems related to the OpenBLAS affinity solved recently, that may explain what we were seeing?

**Comment by xianyi** [comment]
@boegel , we already disable affinity in OpenBLAS by default.

**Comment by boegel** [comment]
@xianyi wait, so passing `NO_AFFINITY=1` doesn't make any difference? regardless of the OpenBLAS version?

**Comment by xianyi** [comment]
For some old version (2 years old), you need pass `NO_AFFINITY=1`

**Comment by ocaisa** [comment]
We ran into a similar issue with `cp2k.popt` in `CP2K`, with the current (default) settings of `OpenBLAS` in EB, OpenBLAS forks NCPU threads per MPI process that flood the node and kill performance.

@damianam configured OpenBLAS with `USE_OPENMP=1` and that seemed to fix the issue. That hint came from https://github.com/xianyi/OpenBLAS/issues/905

**Comment by boegel** [comment]
follow up in #4524, I'm closing this PR since it's not worth fixing these ancient OpenBLAS easyconfigs imho

**Pull request closed without merging**
