### PR TITLE
detect the correct Python for vcflib

### PR DESCRIPTION
**Pull request by branfosj**
(created using `eb --new-pr`)

Before
```
-- Found PythonInterp: /rds/projects/2017/branfosj-rse/easybuild/venv-dev-EL8/bin/python (found version "3.6.8")
-- Found PythonLibs: /usr/lib64/libpython3.6m.so
```

After
```
-- Found PythonInterp: /rds/projects/2017/branfosj-rse/easybuild/EL8-ice/software/Python/3.10.4-GCCcore-11.3.0/bin/python (found version "3.10.4")
-- Found PythonLibs: /rds/projects/2017/branfosj-rse/easybuild/EL8-ice/software/Python/3.10.4-GCCcore-11.3.0/lib/libpython3.10.so
```

### CODE REVIEW

**Comment by branfosj** [comment]
Test report by @branfosj
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
bear-pg0104u19b.bear.cluster - Linux RHEL 8.6, x86_64, Intel(R) Xeon(R) Platinum 8360Y CPU @ 2.40GHz (icelake), Python 3.6.8
See https://gist.github.com/branfosj/1b603042fd340271c6e4194f6960f3c1 for a full test report.

**Comment by branfosj** [comment]
@boegelbot please test @ generoso

**Comment by branfosj** [comment]
@boegelbot please test @ jsc-zen2

**Review by smoors — APPROVED** [review]
lgtm

**Comment by smoors** [comment]
Going in, thanks @branfosj!

**Pull request merged**
