### PR TITLE
add patch for OpenMPI 3.1.4 adding device parameters for ConnectX-6

### PR DESCRIPTION
**Pull request by boegel**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by boegel** [comment]
@boegelbot please test @ generoso

**Comment by boegel** [comment]
This fixes warnings on recent systems with a ConnectX-6 IB card:

```
WARNING: No preset parameters were found for the device that Open MPI
detected:
 
  Local host:            node1234
  Device name:           mlx5_0
  Device vendor ID:      0x02c9
  Device vendor part ID: 4123
 
Default device parameters will be used, which may result in lower
performance.  You can edit any of the files specified by the
btl_openib_device_param_files MCA parameter to set values for your
device.
 
NOTE: You can turn off this warning by setting the MCA parameter
      btl_openib_warn_no_device_params_found to 0.
```

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 3 out of 3 (3 easyconfigs in total)
node3403.kirlia.os - Linux centos linux 7.8.2003, x86_64, Intel(R) Xeon(R) Gold 6240 CPU @ 2.60GHz (cascadelake), Python 2.7.5
See https://gist.github.com/33e088904d500f3c28260b70fac40357 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 3 out of 3 (3 easyconfigs in total)
node3120.skitty.os - Linux centos linux 7.8.2003, x86_64, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz, Python 3.6.8
See https://gist.github.com/9e585737487d59ecef0e8fab19dd1961 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 3 out of 3 (3 easyconfigs in total)
node3628.doduo.os - Linux RHEL 8.2, x86_64, AMD EPYC 7552 48-Core Processor (zen2), Python 3.6.8
See https://gist.github.com/c845554cffc06fa9d1bdeab27c48b193 for a full test report.

**Review by Micket — APPROVED** [review]
lgtm (I don't have connectx6 hardware, so I'll trust your builds)

**Comment by Micket** [comment]
Going in, thanks @boegel!

**Pull request merged**
