### PR TITLE
{vis}[foss/2019a] OpenCV v3.4.7 w/ Python 2.7.15 + 3.7.2

### PR DESCRIPTION
**Pull request by akesandgren**
(created using `eb --new-pr`)

Depends on #9189

### CODE REVIEW

**Comment by akesandgren** [comment]
Test report by @akesandgren
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in this PR)
b-an03.hpc2n.umu.se - Linux ubuntu 16.04, Intel(R) Xeon(R) CPU E5-2690 v4 @ 2.60GHz, Python 2.7.12
See https://gist.github.com/95419c74cbea1603f5dac1b88641e060 for a full test report.

**Comment by Micket** [comment]
kick travis

**Comment by Micket** [comment]
Test report by @Micket
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in this PR)
vera-c1 - Linux centos linux 7.7.1908, Intel Xeon Processor (Skylake), Python 2.7.5
See https://gist.github.com/4ba191cc54dd805018b3e62e82ab8a54 for a full test report.

**Comment by Micket** [comment]
Going in, thanks @akesandgren!

**Pull request merged**
