### PR TITLE
add TorchRL to PyTorch-bundle v2.1.2

### PR DESCRIPTION
**Pull request by lexming**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by lexming** [comment]
@boegelbot please test @ jsc-zen3

**Comment by lexming** [comment]
@boegelbot please test @ generoso
EB_ARGS="PyTorch-bundle-2.1.2-foss-2023a.eb"
CORE_CNT=16

**Review by smoors — APPROVED** [review]
lgtm

**Comment by smoors** [comment]
Going in, thanks @lexming!

**Pull request merged**
