### PR TITLE
{math}[intel/2018a] sympy v1.3 w/ Python 3.6.4

### PR DESCRIPTION
**Pull request by boegel**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
node3133.skitty.os - Linux centos linux 7.5.1804, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz, Python 2.7.5
See https://gist.github.com/00ddad3f11606ca253bfff4423c7782c for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**FAILED**
Build succeeded for 0 out of 1 (1 easyconfigs in this PR)
node2558.golett.os - Linux centos linux 7.5.1804, Intel(R) Xeon(R) CPU E5-2680 v3 @ 2.50GHz, Python 2.7.5
See https://gist.github.com/0e8b97e899ccb2c65f3811499bb442bb for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**FAILED**
Build succeeded for 0 out of 1 (1 easyconfigs in this PR)
node2003.delcatty.os - Linux centos linux 7.5.1804, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.7.5
See https://gist.github.com/9d1ca891de24f4d3b3cc7ddd007fb924 for a full test report.

**Comment by boegel** [comment]
@hajgato I'm running into similar failures like we did in #6896 because `$TMPDIR` points to a temporary directory that is a symlink...

Any idea how that's possible, since the patch you added is being used? The only difference really is that Python 3.x is being used here.

**Comment by hajgato** [comment]
@boegel Its hard to say. I do not see the exact error message, but I do not have a clue. (we thought that maybe the name of `TMPDIR` was too long?)

**Comment by boegel** [comment]
see also discussion in #7425

**Comment by jose-d** [comment]
> Any idea how that's possible, since the patch you added is being used? The only difference really is that Python 3.x is being used here.

@boegel : The patch @hajgato did is relevant for Python2 as the patch applies inside of conditional statement, looking like:
```
if python2 then:
  ${patched code with the tweak for symlinks and tmpdirs}
else: # (=python3)
  ${some new fancy python3-ish way, unpatched}
```

**Comment by boegel** [comment]
@jose-d Oh, that could explain it... So do you think the patch can be generalized easily to cover both Python 2 & 3?

**Comment by jose-d** [comment]
@boegel  IMO yes, I did it in  #7405 and I added your easyconfig from this case there too. So now the CI build is in progress and please, feel free to test it on some of yours _home-with-symlink_, :), systems.

**Pull request closed without merging**
