### PR TITLE
Update Java-8 wrapper to 8.402

### PR DESCRIPTION
**Pull request by Micket**
(created using `eb --new-pr`)

I already merged the updated version, so we should fix the wrapper before next release as well.

### CODE REVIEW

**Comment by Micket** [comment]
@boegelbot please test @ generoso

**Comment by Micket** [comment]
Test report by @Micket
**SUCCESS**
Build succeeded for 2 out of 2 (1 easyconfigs in total)
vera-skylake-build - Linux Rocky Linux 8.9, x86_64, Intel Xeon Processor (Skylake, IBRS, no TSX), Python 3.6.8
See https://gist.github.com/Micket/e424643ca0df2ec26027035d40b47d00 for a full test report.

**Comment by Micket** [comment]
@boegelbot please test @ jsc-zen3

**Review by migueldiascosta — APPROVED** [review]
lgtm

**Comment by migueldiascosta** [comment]
Going in, thanks @Micket!

**Pull request merged**
