### PR TITLE
include NLopt as a dependency in R easyconfigs that include nloptr as extension

### PR DESCRIPTION
**Pull request by boegel**
Same fix as in #4481, applied consistently in all R easyconfigs that include `nloptr` extension.

Without this, the installation of the R easyconfigs that don't include `NLopt` as a dependency go into some kind of infinite loop when installing the `nloptr` extension...

### CODE REVIEW

**Comment by akesandgren** [comment]
Looks good visually at least.

**Comment by boegel** [comment]
Test report by @boegel
**FAILED**
Build succeeded for 25 out of 26 (26 easyconfigs in this PR)
node2012.delcatty.os - Linux centos linux 7.4.1708, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.7.5
See https://gist.github.com/928660d305629dcd393c6d316c917c6d for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**FAILED**
Build succeeded for 25 out of 26 (26 easyconfigs in this PR)
node2012.delcatty.os - Linux centos linux 7.4.1708, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.7.5
See https://gist.github.com/568628cead071da73d69dbfd5d747502 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 26 out of 26 (26 easyconfigs in this PR)
node2123.delcatty.os - Linux centos linux 7.4.1708, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.7.5
See https://gist.github.com/13a410ab56d2dd01a8bbda405b0932cc for a full test report.

**Pull request merged**
