### PR TITLE
{compiler}[system/system] Go v1.21.1

### PR DESCRIPTION
**Pull request by jose-d**
(created using `eb --new-pr`)

just version number increase to current $release.

### CODE REVIEW

**Comment by jose-d** [comment]
Test report by @jose-d
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
cvmfs1.koios.lan - Linux Rocky Linux 8.8 (Green Obsidian), x86_64, Intel(R) Xeon(R) Gold 6130 CPU @ 2.10GHz, Python 3.11.2
See https://gist.github.com/jose-d/2351b81bf7011d556afb6c6f66c14883 for a full test report.

**Comment by jose-d** [comment]
Test report by @jose-d
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
gpu2.phoebe.lan - Linux Rocky Linux 8.8 (Green Obsidian), x86_64, AMD EPYC 7543 32-Core Processor, 8 x NVIDIA NVIDIA A100-SXM4-80GB, 535.104.12, Python 3.11.2
See https://gist.github.com/jose-d/7018df07fbbed9fef5b33c87a2b7184f for a full test report.

**Review by branfosj — APPROVED** [review]

**Comment by branfosj** [comment]
@boegelbot please test @ generoso

**Comment by branfosj** [comment]
@boegelbot please test @ jsc-zen2

**Comment by branfosj** [comment]
@boegelbot please test @ generoso

**Comment by branfosj** [comment]
@boegelbot please test @ generoso

**Comment by branfosj** [comment]
Going in, thanks @jose-d!

**Pull request merged**
