### PR TITLE
{bio}[foss/2020a] OPERA-MS v0.9.0

### PR DESCRIPTION
**Pull request by zarybnicky**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by zarybnicky** [comment]
Instead of `perl <install dir>/OPERA-MS.pl --help` as per instructions, you can use `OPERA-MS --help`, a wrapper script.

**Review by boegel — CHANGES_REQUESTED** [review]

**Comment by smoors** [comment]
@boegelbot please test @ generoso

**Comment by smoors** [comment]
Test report by @smoors
**SUCCESS**
Build succeeded for 2 out of 2 (1 easyconfigs in this PR)
node375.hydra.os - Linux centos linux 7.7.1908, x86_64, Intel(R) Xeon(R) Gold 6148 CPU @ 2.40GHz (skylake_avx512), Python 2.7.5
See https://gist.github.com/8a2f083404f99ff68a9dc847d074571d for a full test report.

**Comment by boegel** [comment]
@zarybnicky The test command you're running via `postinstallcmds` requires `python` to be available.

There's no `python` command available on the CentOS8 test system used in the failing test report, which explains the failure.
This is included in the `gap_filling.err` output file:

```
python /software/OPERA-MS/0.9.0-foss-2020a//OPERA-LG/bin//Remap.py /tmp/eb-hi1cjvya/intermediate_files/opera_long_read/GAPFILLING/TILLING/first_tilling.paf /tmp/eb-hi1cjvya/intermediate_files/opera_long_read/GAPFILLING/TILLING/consensus.fa /tmp/eb-hi1cjvya/intermediate_files/opera_long_read/GAPFILLING/TILLING/first_tilling_contig.fa > /tmp/eb-hi1cjvya/intermediate_files/opera_long_read/GAPFILLING/TILLING/tilling_1_remap.out
sh: python: command not found
```

So `Python` should be included as a dependency (probably runtime, since the `OPERA-MS` installation includes Python scripts?

**Review by boegel — CHANGES_REQUESTED** [review]
@zarybnicky The test command you're running via `postinstallcmds` requires `python` to be available.

There's no `python` command available on the CentOS8 test system used in the failing test report, which explains the failure.
This is included in the `gap_filling.err` output file:

```
python /software/OPERA-MS/0.9.0-foss-2020a//OPERA-LG/bin//Remap.py /tmp/eb-hi1cjvya/intermediate_files/opera_long_read/GAPFILLING/TILLING/first_tilling.paf /tmp/eb-hi1cjvya/intermediate_files/opera_long_read/GAPFILLING/TILLING/consensus.fa /tmp/eb-hi1cjvya/intermediate_files/opera_long_read/GAPFILLING/TILLING/first_tilling_contig.fa > /tmp/eb-hi1cjvya/intermediate_files/opera_long_read/GAPFILLING/TILLING/tilling_1_remap.out
sh: python: command not found
```

So `Python` should be included as a dependency (probably runtime, since the `OPERA-MS` installation includes Python scripts?

**Comment by zarybnicky** [comment]
@boegel Ah, thanks for that. I've seen that log and wanted to ask you today for that log file, as the gist only says `Please see /tmp/eb-zsnq4q7g/intermediate_files/opera_long_read/GAPFILLING/gap_filling.err for details.`

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
node3401.kirlia.os - Linux centos linux 7.8.2003, x86_64, Intel(R) Xeon(R) Gold 6240 CPU @ 2.60GHz (cascadelake), Python 2.7.5
See https://gist.github.com/88b9966228dacd6777d65933029992a0 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 2 out of 2 (1 easyconfigs in this PR)
node3108.skitty.os - Linux centos linux 7.8.2003, x86_64, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz, Python 3.6.8
See https://gist.github.com/ed3a51111250c22fad5aafeef94bbb6d for a full test report.

**Review by boegel — APPROVED** [review]

**Comment by boegel** [comment]
Going in, thanks @zarybnicky!

**Pull request merged**
