### PR TITLE
{math}[GCC/13.2.0,gfbf/2023b] sympy v1.12, gmpy2 v2.1.5

### PR DESCRIPTION
**Pull request by Flamefire**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by Flamefire** [comment]
Test report by @Flamefire
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in total)
n1285 - Linux RHEL 8.7 (Ootpa), x86_64, Intel(R) Xeon(R) Platinum 8470 (icelake), Python 3.8.13
See https://gist.github.com/Flamefire/f8bc5b283edfdbaee3db6cde808e8228 for a full test report.

**Review by Micket — APPROVED** [review]
lgtm

**Comment by casparvl** [comment]
@boegelbot please test @ generoso

**Comment by Micket** [comment]
@boegelbot please test @ generoso

**Comment by Micket** [comment]
Test report by @Micket
**FAILED**
Build succeeded for 7 out of 13 (2 easyconfigs in total)
alvis-icelake-build - Linux Rocky Linux 8.9, x86_64, Intel(R) Xeon(R) Silver 4316 CPU @ 2.30GHz, Python 3.6.8
See https://gist.github.com/Micket/a6cad9190060dff61149ae3b299b2f66 for a full test report.

**Comment by casparvl** [comment]
Test report by @casparvl
**SUCCESS**
Build succeeded for 4 out of 4 (2 easyconfigs in total)
tcn1.local.snellius.surf.nl - Linux RHEL 8.6, x86_64, AMD EPYC 7H12 64-Core Processor, Python 3.6.8
See https://gist.github.com/casparvl/8b2451ff8b1b5886d502e8655ffc96c7 for a full test report.

**Comment by Micket** [comment]
Going in, thanks @Flamefire!

**Pull request merged**
