### PR TITLE
replace LibUUID dependencies with util-linux (cfr. #6963)

### PR DESCRIPTION
**Pull request by boegel**

### CODE REVIEW

**Comment by boegel** [comment]
Submitting a test report for this is likely going to be painful due to the old toolchain versions involved, so I'll look into a full test report (on our oldest cluster).

Maybe others should only submit a partial test report using `eb --from-pr 8258 libdap-3.20.3-GCCcore-7.3.0.eb libdap-3.19.1-GCCcore-6.4.0.eb` for example...

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 7 out of 7 (7 easyconfigs in this PR)
node2024.delcatty.os - Linux centos linux 7.6.1810, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.7.5
See https://gist.github.com/4db00956ebfe885b9441db974b61cd96 for a full test report.

**Comment by smoors** [comment]
Test report by @smoors
**FAILED**
Build succeeded for 1 out of 6 (5 easyconfigs in this PR)
nic31 - Linux centos linux 7.5.1804, Intel(R) Xeon(R) Gold 6148 CPU @ 2.40GHz, Python 2.7.5
See https://gist.github.com/30383482a534d7252568299d4ce5ef99 for a full test report.

**Comment by smoors** [comment]
Test report by @smoors
**SUCCESS**
Build succeeded for 6 out of 6 (5 easyconfigs in this PR)
nic425 - Linux centos linux 7.5.1804, Intel(R) Xeon(R) Gold 6148 CPU @ 2.40GHz, Python 2.7.5
See https://gist.github.com/bdff08c7ee3c68da7b597d7ac5163685 for a full test report.

**Comment by smoors** [comment]
Going in, thanks @boegel!

**Pull request merged**
