### PR TITLE
{chem}[foss/2019b,intel/2019b] QuantumESPRESSO v6.7

### PR DESCRIPTION
**Pull request by akesandgren**
(created using `eb --new-pr`)
Depends on https://github.com/easybuilders/easybuild-easyblocks/pull/2319

### CODE REVIEW

**Comment by akesandgren** [comment]
Test report by @akesandgren
Using easyblocks from PR(s) https://github.com/easybuilders/easybuild-easyblocks/pull/2319
**SUCCESS**
Build succeeded for 1 out of 1 (2 easyconfigs in total)
b-an02.hpc2n.umu.se - Linux ubuntu 16.04, x86_64, Intel(R) Xeon(R) CPU E5-2690 v4 @ 2.60GHz, Python 2.7.12
See https://gist.github.com/b3201cdc657025d9ba13294a9944fd48 for a full test report.

**Comment by akesandgren** [comment]
Test report by @akesandgren
Using easyblocks from PR(s) https://github.com/easybuilders/easybuild-easyblocks/pull/2319
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in total)
b-an02.hpc2n.umu.se - Linux ubuntu 16.04, x86_64, Intel(R) Xeon(R) CPU E5-2690 v4 @ 2.60GHz, Python 2.7.12
See https://gist.github.com/54c4e4aaea02db792630234329374251 for a full test report.

**Comment by migueldiascosta** [comment]
@boegelbot please test @ generoso EB_ARGS="-include-easyblocks-from-pr 2319"

**Comment by migueldiascosta** [comment]
Test report by @migueldiascosta
Using easyblocks from PR(s) https://github.com/easybuilders/easybuild-easyblocks/pull/2319
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in total)
sms - Linux centos linux 7.6.1810, x86_64, AMD EPYC 7601 32-Core Processor (zen), Python 2.7.5
See https://gist.github.com/2c76316196bd2e541bd3f7ab1488eacb for a full test report.

**Review by migueldiascosta — APPROVED** [review]
lgtm

**Comment by migueldiascosta** [comment]
running the testsuite manually, there's one big failure (see below), but it happens for both toolchains and in different architectures, and all other tests pass...

```
Running PH ...
ph_Ni_nc_spinorbit_mag - Ni.ph.in (arg(s): 2): **FAILED**.
phfreq
    ERROR: absolute error 2.75e+03 greater than 2.00e+00. (Test: 2893.999573.  Benchmark: 148.254793.)
phfreq
    ERROR: absolute error 2.74e+03 greater than 2.00e+00. (Test: 2894.077163.  Benchmark: 150.33794.)
phfreq
    ERROR: absolute error 2.69e+03 greater than 2.00e+00. (Test: 2912.492736.  Benchmark: 218.610399.)
```

**Comment by migueldiascosta** [comment]
Going in, thanks @akesandgren!

**Pull request merged**
