### PR TITLE
{vis}[GCCcore/9.3.0] jbigkit v2.1

### PR DESCRIPTION
**Pull request by JackPerdue**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by verdurin** [comment]
Test report by @verdurin
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
easybuild.novalocal - Linux centos linux 7.8.2003, x86_64, Intel Xeon Processor (Skylake, IBRS), Python 2.7.5
See https://gist.github.com/b39799b4fc671494c651e2a2c71f7fbf for a full test report.

**Comment by verdurin** [comment]
@JackPerdue could we have a test report for this one too please?

**Comment by JackPerdue** [comment]
Test report by @JackPerdue
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
tlogin-0502.cluster - Linux centos linux 7.8.2003, x86_64, Intel(R) Xeon(R) CPU E5-2680 v4 @ 2.40GHz, Python 2.7.5
See https://gist.github.com/210c1feb8de686d6e1d09bfbe56b539c for a full test report.

**Comment by verdurin** [comment]
Going in, thanks @JackPerdue!

**Pull request merged**
