### PR TITLE
add missing xxd build dependency for recent PLUMED versions (2.6.2, 2.7.x)

### LINKED ISSUE #11209: missing xxd requirement for PLUMED
On a Centos-7 system this failed with 

```
checking for xxd... no
configure: error: xxd should be installed for PLUMED to compile properly
```

in the logfile.

The terminal output was not very helpful:

```
== FAILED: Installation ended unsuccessfully (build directory: /mnt/nfs/centos/easybuild/build/PLUMED/2.5.1/foss-2019a): build failed (first 300 chars): cmd "env FC=$MPIF90 LIBS="$LIBLAPACK $LIBS"  ./configure --prefix=/mnt/nfs/centos/easybuild/software/PLUMED/2.5.1-foss-2019a  --build=x86_64-pc-linux-gnu  --host=x86_64-pc-linux-gnu  --exec-prefix=/mnt/nfs/centos/easybuild/software/PLUMED/2.5.1-foss-2019a --enable-gsl --enable-modules=all" exited wi (took 22 sec)
== Results of the build can be found in the log file(s) /tmp/eb-mzwwxyip/easybuild-PLUMED-2.5.1-20200903.094415.jjyqr.log
ERROR: Build of /mnt/nfs/centos/easybuild/software/EasyBuild/4.2.2/easybuild/easyconfigs/p/PLUMED/PLUMED-2.5.1-foss-2019a.eb failed (err: 'build failed (first 300 chars): cmd "env FC=$MPIF90 LIBS="$LIBLAPACK $LIBS"  ./configure --prefix=/mnt/nfs/centos/easybuild/software/PLUMED/2.5.1-foss-2019a  --build=x86_64-pc-linux-gnu  --host=x86_64-pc-linux-gnu  --exec-prefix=/mnt/nfs/centos/easybuild/software/PLUMED/2.5.1-foss-2019a --enable-gsl --enable-modules=all" exited wi')
```

There doesn't appear to be an EasyConfig for `xxd` so I had to install via yum:

`sudo yum install -y vim-common`

### PR DESCRIPTION
**Pull request by sassy-crick**
(created using `eb --new-pr`)
Dependencies:
- [x] Requires #14846

fixes #11209

### CODE REVIEW

**Comment by boegel** [comment]
@boegelbot please test @ generoso

**Comment by boegel** [comment]
@boegelbot please test @ jsc-zen2

**Comment by boegel** [comment]
Hmm, test on `jsc-zen2` failed with `Check for banned/required shared libraries failed`, have to check what's going on there... Any ideas @SebastianAchilles ?

**Comment by sassy-crick** [comment]
Unfortunately I lost all my access to any build machines, and the ones I have at home are too old. So I cannot assist here much I am afraid. 😕

**Comment by SebastianAchilles** [comment]
Test report by @sebastianachilles
**SUCCESS**
Build succeeded for 3 out of 3 (3 easyconfigs in total)
jsfc01.int.jusuf.sebastian.cluster - Linux Rocky Linux 8.4, x86_64, AMD EPYC 7742 64-Core Processor (zen2), 1 x NVIDIA GRID V100-4C, 460.73.01, Python 3.6.8
See https://gist.github.com/da3a148ec20aac56b6969c58f442f3d3 for a full test report.

**Comment by SebastianAchilles** [comment]
> Hmm, test on `jsc-zen2` failed with `Check for banned/required shared libraries failed`, have to check what's going on there... Any ideas @SebastianAchilles ?

It works on my account on `jsc-zen2`. I have to check tomorrow what is different on @boegelbot's account.

**Comment by smoors** [comment]
@sassy-crick what about PLUMED-2.7.2 and PLUMED-2.7.3? Should `xxd` be added to those too?

**Comment by sassy-crick** [comment]
@smoors You are right of course! I have added them to the files you mentioned and some others I found reasonable to add. I should have covered the recent versions now. Let me know if I missed out something. Thanks for your help!

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 6 out of 6 (6 easyconfigs in total)
node3112.skitty.os - Linux CentOS Linux 7.9.2009, x86_64, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz, Python 3.6.8
See https://gist.github.com/7861a4643a3b495e5d2988d490fd9191 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 6 out of 6 (6 easyconfigs in total)
node3575.doduo.os - Linux RHEL 8.4, x86_64, AMD EPYC 7552 48-Core Processor (zen2), Python 3.6.8
See https://gist.github.com/b43972e162c3db4d626b24bce5bf38db for a full test report.

**Review by boegel — APPROVED** [review]
lgtm

**Comment by boegel** [comment]
Going in, thanks @sassy-crick!

**Pull request merged**
