### PR TITLE
Move new GlobalArrays configs to 2019b

### PR DESCRIPTION
**Pull request by Micket**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by Micket** [comment]
@lexming I made a mistake in #10422, i meant to put them into 2019b with some other stuff I have been preparing.

**Comment by Micket** [comment]
Test report by @Micket
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in this PR)
vera-c1 - Linux centos linux 7.7.1908, Intel Xeon Processor (Skylake), Python 2.7.5
See https://gist.github.com/accfe4fd8c1509f9c7c61ac37a18a982 for a full test report.

**Comment by lexming** [comment]
Test report by @lexming
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in this PR)
node150.hydra.os - Linux centos linux 7.7.1908, x86_64, Intel(R) Xeon(R) CPU E5-2680 v2 @ 2.80GHz, Python 2.7.5
See https://gist.github.com/2b5062b1e0d85be90cef1dfe5b763999 for a full test report.

**Comment by lexming** [comment]
Going in, thanks @Micket !

**Pull request merged**
