### PR TITLE
GLib: Update PCRE version to 8.44

### PR DESCRIPTION
**Pull request by akesandgren**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by akesandgren** [comment]
Test report by @akesandgren
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
generoso - Linux centos linux 7.6.1810, Intel(R) Xeon(R) CPU E5-2660 v4 @ 2.00GHz, Python 3.6.8
See https://gist.github.com/74577e43e6c097cde9fb989f7afbcb4f for a full test report.

**Comment by lexming** [comment]
Test report by @lexming
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
login2.cerberus.os - Linux centos linux 7.7.1908, Intel(R) Xeon(R) Gold 6126 CPU @ 2.60GHz, Python 2.7.5
See https://gist.github.com/c78e9bc1b9ab541be02b3da2bac3e971 for a full test report.

**Comment by akesandgren** [comment]
Need to make a single PR for the PCRE 8.43 -> 8.44 update, closing

**Comment by akesandgren** [comment]
Replaced with #10169

**Pull request closed without merging**
