### PR TITLE
{bio}[foss/2019a] FSL v6.0.1

### PR DESCRIPTION
**Pull request by vanzod**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by vanzod** [comment]
Test report by @vanzod
**SUCCESS**
Build succeeded for 5 out of 5 (5 easyconfigs in this PR)
cermis - Linux debian 9.9, Intel(R) Xeon(R) CPU           X5670  @ 2.93GHz, Python 2.7.13
See https://gist.github.com/7b84b37aa61b256199f4a21b50fa7abd for a full test report.

**Comment by verdurin** [comment]
Test report by @verdurin
**FAILED**
Build succeeded for 18 out of 22 (5 easyconfigs in this PR)
easybuild.novalocal - Linux centos linux 7.6.1810, Intel Xeon Processor (Skylake, IBRS), Python 2.7.5
See https://gist.github.com/452d364111bb9102b3fd592df161416b for a full test report.

**Comment by verdurin** [comment]
@vanzod Does this have fixes for https://github.com/easybuilders/easybuild-easyconfigs/issues/7899 ?

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 6 out of 6 (5 easyconfigs in this PR)
node3110.skitty.os - Linux centos linux 7.6.1810, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz, Python 2.7.5
See https://gist.github.com/5e6ff40c92456ee09b8a27a52b111bbe for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 7 out of 7 (5 easyconfigs in this PR)
node2419.golett.os - Linux centos linux 7.6.1810, Intel(R) Xeon(R) CPU E5-2680 v3 @ 2.50GHz, Python 2.7.5
See https://gist.github.com/e821199826f2bfdfe4f3023a49c9060f for a full test report.

**Comment by boegel** [comment]
> @vanzod Does this have fixes for #7899 ?

@verdurin Should that block this PR?

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 9 out of 9 (5 easyconfigs in this PR)
node2128.delcatty.os - Linux centos linux 7.6.1810, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.7.5
See https://gist.github.com/09b6be0b31b1db8dd3aaaeb3b2757200 for a full test report.

**Comment by verdurin** [comment]
@boegel It would seem a shame not to fix the problem when we have the opportunity.

**Comment by boegel** [comment]
@verdurin It doesn't seem like an easy fix though... Let's see what @vanzod thinks, since he has spent quite a bit of time with `FSL` recently.

**Comment by vanzod** [comment]
@verdurin No, it does not. As Maxime pointed out in the issue, for some of those tools FSL relies on a local installation of Miniconda and the creation of a virtual environment. It is pretty messy in my opinion and I would have needed more time than I actually have to figure out a potential way around it.
The main changes here are the addition of few more external dependencies and the setting of some environment variables in the module. This mimics what the required sourcing of `fsl.sh` sets.

**Comment by verdurin** [comment]
@vanzod Certainly I wasn't doing the work myself, and agree it's very messy. I keep meaning to contact the developers, who are pretty close to me geographically. Anyway, happy for this to be merged. Perhaps worth adding a comment in the easyconfig about the `fslpython` situation?

**Comment by boegel** [comment]
Going in, thanks @vanzod!

**Comment by boegel** [comment]
Test report by @boegel
**FAILED**
Build succeeded for 4 out of 5 (5 easyconfigs in this PR)
generoso - Linux centos linux 7.6.1810, Intel(R) Xeon(R) CPU E5-2660 v4 @ 2.00GHz, Python 3.6.8
See https://gist.github.com/be9a8c0d73cb33f52ed28e44a0a2d98f for a full test report.

**Pull request merged**
