### PR TITLE
use `CargoPythonBundle` generic easyblock for timm to install required Rust packages in a controlled way

### PR DESCRIPTION
**Pull request by Micket**
(created using `eb --new-pr`)

- [x] https://github.com/easybuilders/easybuild-easyblocks/pull/2964

### CODE REVIEW

**Comment by Micket** [comment]
Test report by @Micket
Using easyblocks from PR(s) https://github.com/easybuilders/easybuild-easyblocks/pull/2964
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
vera-c1 - Linux Rocky Linux 8.7, x86_64, Intel Xeon Processor (Skylake), Python 3.6.8
See https://gist.github.com/Micket/1d91a2784d53141146f103cd42280b04 for a full test report.

**Comment by Micket** [comment]
Test report by @Micket
Using easyblocks from PR(s) https://github.com/easybuilders/easybuild-easyblocks/pull/2964
**FAILED**
Build succeeded for 0 out of 1 (1 easyconfigs in total)
vera-c1 - Linux Rocky Linux 8.7, x86_64, Intel Xeon Processor (Skylake), Python 3.6.8
See https://gist.github.com/Micket/ffd6bb8747b152c3edbf83bb362178bc for a full test report.

**Comment by Micket** [comment]
Test report by @Micket
Using easyblocks from PR(s) https://github.com/easybuilders/easybuild-easyblocks/pull/2964
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
vera-skylake-build - Linux Rocky Linux 8.8, x86_64, Intel Xeon Processor (Skylake, IBRS, no TSX), Python 3.6.8
See https://gist.github.com/Micket/e79685dee872963f82616a827ca96c24 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
Using easyblocks from PR(s) https://github.com/easybuilders/easybuild-easyblocks/pull/2964
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
node3308.joltik.os - Linux RHEL 8.8, x86_64, Intel(R) Xeon(R) Gold 6242 CPU @ 2.80GHz (cascadelake), 1 x NVIDIA Tesla V100-SXM2-32GB, 535.129.03, Python 3.6.8
See https://gist.github.com/boegel/03b3f815709612ea7439fe4ee806701d for a full test report.

**Comment by boegel** [comment]
@boegelbot please test @ jsc-zen2
EB_ARGS="--include-easyblocks-from-pr 2964"

**Comment by boegel** [comment]
@boegelbot please test @ generoso
EB_ARGS="--include-easyblocks-from-pr 2964"

**Comment by Micket** [comment]
Inject checksums doesn't work here. I think it should be reworked to always produce a list at the top level scope, instead of doing this per-extension stuff, which would also solve this issue and the issue with X11 checksum injection not working.

**Review by boegel — APPROVED** [review]

**Comment by boegel** [comment]
Going in, thanks @Micket!

**Pull request merged**
