### PR TITLE
{bio}[foss/2018b] MaxQuant v1.6.10.43

### PR DESCRIPTION
**Pull request by SethosII**
This PR uses https://github.com/easybuilders/easybuild-easyconfigs/pull/9102.

I could need some guidance on this one. Is `modaliases` the way to go here? ~Is a `sanity_check_commands` with `maxquantcmd --help` helpful?~ (I tried this but the alias doesn't seem to be known during the sanity check) Should `source_urls`  be removed because you need to register and get a link with some hash and an expiration date so a normal download will fail due to error 403?

### CODE REVIEW

**Comment by smoors** [comment]
@SethosII `modaliases` is indeed fine here.
modaliases are only added to the module file, so if you want `sanity_check_commands` you need to specify the full command (you could define a local_* variable to avoid having to type it twice).
`source_urls` should indeed be removed.

**Comment by SethosII** [comment]
@smoors I removed `source_urls`. `--help` and `--version` don't return 0 but 1 so there is no easy `sanity_check_commands`.

**Comment by smoors** [comment]
@SethosII as a workaround, you could grep the output of the --help output, like is done in `ACT-18.0.3-Java-11.eb` (not saying that you should).

**Comment by smoors** [comment]
Test report by @smoors
**SUCCESS**
Build succeeded for 2 out of 2 (1 easyconfigs in this PR)
node353.hydra.os - Linux centos linux 7.6.1810, Intel(R) Xeon(R) Gold 6148 CPU @ 2.40GHz, Python 2.7.5
See https://gist.github.com/d29da23d61aef2902eee4a71fcc6ff0a for a full test report.

**Comment by smoors** [comment]
Going in, thanks @SethosII!

**Pull request merged**
