### PR TITLE
add patch to GCC 11.x + 12.x to fix vectorizer bug

### PR DESCRIPTION
**Pull request by bartoldeman**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by bartoldeman** [comment]
Test report by @bartoldeman
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
build-node.computecanada.ca - Linux CentOS Linux 7.9.2009, x86_64, Intel Xeon Processor (Skylake, IBRS), Python 3.7.7
See https://gist.github.com/826c539bde1bb905513c13cecc5dcb49 for a full test report.

**Comment by boegel** [comment]
@bartoldeman Shouldn't this patch also be applied to `GCCcore` 11.2.0 (and 11.1.0)?

**Comment by boegel** [comment]
@boegelbot please test @ generoso
CORE_CNT=16

**Comment by boegel** [comment]
> @bartoldeman Shouldn't this patch also be applied to `GCCcore` 11.2.0 (and 11.1.0)?

@bartoldeman Current patch `GCCcore-11.3.0_fix-vectorizer.patch` applies cleanly to GCC 11.1.0 and 11.2.0, so let's add it there too?

**Comment by boegel** [comment]
@boegelbot please test @ generoso

**Comment by boegel** [comment]
> @bartoldeman Shouldn't this patch also be applied to `GCCcore` 11.2.0 (and 11.1.0)?

Fixed this myself in 0f74df6 + e30aeac

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 5 out of 5 (5 easyconfigs in total)
node3145.skitty.os - Linux RHEL 8.4, x86_64, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz (skylake_avx512), Python 3.6.8
See https://gist.github.com/2354b61dbdd870165b012f720b0a63a3 for a full test report.

**Comment by bartoldeman** [comment]
Thanks for doing the other GCC's too! LGTM

**Review by boegel — APPROVED** [review]
lgtm

**Comment by boegel** [comment]
Going in, thanks @bartoldeman!

**Comment by boegel** [comment]
@boegelbot please test @ jsc-zen2
CORE_CNT=16

**Pull request merged**
