### PR TITLE
{lang}[foss/2022a] numba v0.56.4 w/ Python 3.10.4

### PR DESCRIPTION
**Pull request by surak**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by SebastianAchilles** [comment]
Test report by @sebastianachilles
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
zen2-ubuntu-2210 - Linux Ubuntu 22.10 (Kinetic Kudu), x86_64, AMD EPYC 7452 32-Core Processor (zen2), Python 3.10.7
See https://gist.github.com/e15d389c12f28f539fc13fd74e256861 for a full test report.

**Comment by SebastianAchilles** [comment]
Test report by @sebastianachilles
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
bwd-rockylinux-91 - Linux Rocky Linux 9.1 (Blue Onyx), x86_64, Intel(R) Core(TM) i7-6900K CPU @ 3.20GHz (broadwell), 2 x NVIDIA NVIDIA GeForce GTX 1060 6GB, 515.86.01, Python 3.9.14
See https://gist.github.com/3e0f42f9a0fb81c59d122c612246ba78 for a full test report.

**Comment by Micket** [comment]
> @Micket was not happy with the patches separately, but I prefer this way.

No comments in the patches, no references, no description of the patches and just named a single word that doesn't reflect *what* they do.
compared to the pattern so far;
llvmlite-0.36.0_fix-LLVM-11.patch
llvmlite-0.37.0_fix-LLVM-12.patch
or, even better, just compared to using what looks to be what will be merged upstream; https://github.com/numba/llvmlite/pull/830.patch


I also note that llvmlite really asks for a special build of LLVM as well.  https://github.com/numba/llvmlite/pull/830#issuecomment-1291025024

**Comment by boegel** [comment]
@surak Can you look into adding the missing descriptions and checksums for the patches?

I would also prefer a single patch rather than a bunch of small ones, I don't see the benefit of the latter.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
node3154.skitty.os - Linux RHEL 8.6, x86_64, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz (skylake_avx512), Python 3.6.8
See https://gist.github.com/9db95eaefc361d6323d3fc189b5776a9 for a full test report.

**Comment by boegel** [comment]
Going in, thanks @surak!

**Comment by smoors** [comment]
@boegelbot please test @ jsc-zen2

**Pull request merged**
