### PR TITLE
{compiler,devel}[GCCcore/12.3.0,foss/2023a] Triton v2.1.0, Clang v17.0.0_20230515 w/ CUDA 12.1.1

### PR DESCRIPTION
**Pull request by WilleBell**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by VRehnberg** [comment]
Test report by @VRehnberg
**FAILED**
Build succeeded for 0 out of 2 (2 easyconfigs in total)
alvis2-13 - Linux Rocky Linux 8.9, x86_64, Intel(R) Xeon(R) Gold 6226R CPU @ 2.90GHz, 1 x NVIDIA Tesla T4, 550.54.14, Python 3.6.8
See https://gist.github.com/VRehnberg/d93779f5ff8f705904edc59cc45f35b4 for a full test report.

**Comment by VRehnberg** [comment]
Checksum failure for llvm-project, but when manually checking the checksum it looks correct.
```
6f371f9ac208b8e9dc57fc117b1a9c8565d7ea2bbb49a2768cb9c3c0fee0291d  /apps/sources/c/Clang/llvm-project-17.0.0_20230515.tar.gz
```

**Comment by WilleBell** [comment]
Test report by @WilleBell
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in total)
node400.hydra.os - Linux Rocky Linux 8.10, x86_64, AMD EPYC 7282 16-Core Processor, 1 x NVIDIA NVIDIA A100-PCIE-40GB, 550.90.07, Python 3.6.8
See https://gist.github.com/WilleBell/ab16c8123ea68f445559f8f02ec1aceb for a full test report.

**Comment by VRehnberg** [comment]
Haven't been able to reproduce it. Rerunning now and should come a report in an hour or two.

**Comment by VRehnberg** [comment]
Test report by @VRehnberg
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
alvis1-02 - Linux Rocky Linux 8.9, x86_64, Intel(R) Xeon(R) Gold 6244 CPU @ 3.60GHz, 1 x NVIDIA Tesla V100-SXM2-32GB, 560.35.03, Python 3.6.8
See https://gist.github.com/VRehnberg/462e8827ae638b8256ea31f338fe6d2b for a full test report.

**Comment by VRehnberg** [comment]
Test report by @VRehnberg
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
alvis1-02 - Linux Rocky Linux 8.9, x86_64, Intel(R) Xeon(R) Gold 6244 CPU @ 3.60GHz, 1 x NVIDIA Tesla V100-SXM2-32GB, 560.35.03, Python 3.6.8
See https://gist.github.com/VRehnberg/87f0c15fcf627fd374c01b499d0ec312 for a full test report.

**Comment by smoors** [comment]
@boegelbot: please test @ generoso

**Comment by smoors** [comment]
@boegelbot please test @ jsc-zen3

**Review by smoors — APPROVED** [review]
lgtm

**Comment by smoors** [comment]
Going in, thanks @WilleBell!

**Pull request merged**
