### PR TITLE
fix build of manta 1.6.0 on top of Boost 1.74.0

### LINKED ISSUE #13337: build step fails for manta-1.6.0-GCC-10.2.0-Python-2.7.18.eb
```
In file included from /software/Boost/1.74.0-GCC-10.2.0/include/boost/detail/workaround.hpp:8,
                 from /software/Boost/1.74.0-GCC-10.2.0/include/boost/serialization/level.hpp:20,
                 from /software/Boost/1.74.0-GCC-10.2.0/include/boost/serialization/nvp.hpp:33,
                 from /tmp/easybuild_build/manta/1.6.0/GCC-10.2.0-Python-2.7.18/manta-1.6.0/src/c++/lib/appstats/SVFinderStats.hpp:26,
                 from /tmp/easybuild_build/manta/1.6.0/GCC-10.2.0-Python-2.7.18/manta-1.6.0/src/c++/lib/appstats/SVFinderStats.cpp:24:
/software/Boost/1.74.0-GCC-10.2.0/include/boost/type_traits/detail/config.hpp:85:69: error: "__clang_major___WORKAROUND_GUARD" is not defined, evaluates to 0 [-Werror=undef]
   85 |       && !BOOST_WORKAROUND(BOOST_MSVC, < 1900) && !BOOST_WORKAROUND(__clang_major__, <= 4)
      |                                                                     ^~~~~~~~~~~~~~~
```

`manta-1.6.0-GCC-10.2.0-Python-2.7.18.eb` installs fine with EasyBuild, even on top of a Boost that was installed with the enhanced easyblock from https://github.com/easybuilders/easybuild-easyblocks/pull/2456.

It looks like this issue could be related to the changes in https://github.com/easybuilders/easybuild-easyblocks/pull/2461...

### PR DESCRIPTION
**Pull request by boegel**
(created using `eb --new-pr`)

fixes #13337

### CODE REVIEW

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
node3502.doduo.os - Linux RHEL 8.2, x86_64, AMD EPYC 7552 48-Core Processor (zen2), Python 3.6.8
See https://gist.github.com/c1b85cfeb91646d330a774e641c8a0bb for a full test report.

**Comment by boegel** [comment]
@boegelbot please test @ generoso

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
node2679.swalot.os - Linux centos linux 7.9.2009, x86_64, Intel(R) Xeon(R) CPU E5-2660 v3 @ 2.60GHz (haswell), Python 3.6.8
See https://gist.github.com/30354e52866046b34aecd8b4cc421758 for a full test report.

**Comment by zao** [comment]
Test report by @zao
**FAILED**
Build succeeded for 0 out of 1 (1 easyconfigs in total)
eb-u2004 - Linux Ubuntu 20.04, x86_64, Intel(R) Core(TM) i7-8700K CPU @ 3.70GHz, Python 3.8.10
See https://gist.github.com/45daa4e75c2de7d346bcc98480cd9d65 for a full test report.

**Comment by zao** [comment]
Test report by @zao
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
eb-rocky8 - Linux UNKNOWN UNKNOWN, x86_64, Intel(R) Core(TM) i7-8700K CPU @ 3.70GHz, Python 3.9.2
See https://gist.github.com/51f1ec31aaaf97033abab5507d756b75 for a full test report.

**Comment by zao** [comment]
Disregard my failed test report, Boost needed a rebuild for a missing patch.

**Review by zao — APPROVED** [review]
LGTM

**Comment by zao** [comment]
Going in, thanks @boegel!

**Comment by Flamefire** [comment]
Better fix: Use the actual release sources https://github.com/Illumina/manta/releases/download/v1.6.0/manta-1.6.0.release_src.tar.bz2

**Pull request merged**
