### PR TITLE
{devel}[GCCcore/10.2.0] libdwarf v20201201, libelf v0.8.13

### PR DESCRIPTION
**Pull request by robert-mijakovic**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by branfosj** [comment]
@boegelbot please test @ generoso

**Comment by robert-mijakovic** [comment]
Can somebody approve it as I have Extrae which depends on this easyconfig?
Maybe I should have included it with Extrae directly,

**Review by Micket — APPROVED** [review]
lgtm

**Comment by Micket** [comment]
Test report by @Micket
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in total)
vera-c1 - Linux centos linux 7.9.2009, x86_64, Intel Xeon Processor (Skylake), Python 2.7.5
See https://gist.github.com/4c539772b3abe17ea7226940a024c25c for a full test report.

**Comment by Micket** [comment]
Going in, thanks @robert-mijakovic!

**Pull request merged**
