### PR TITLE
{tools} YAXT: URL updated to fallback as original URL for source code is broken right now

### PR DESCRIPTION
**Pull request by sassy-crick**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by smoors** [comment]
@sassy-crick thanks for the updated URLS.
I've removed the parentheses, as they are not needed.

**Comment by smoors** [comment]
@boegelbot: please test @ generoso

**Comment by sassy-crick** [comment]
> @sassy-crick thanks for the updated URLs. I've removed the parentheses, as they are not needed.

@smoors Many thanks for doing this! I suggested to the maintainers of the program to come back to me/us once their GitLab installation is no longer beta and a production use one. 
I also have PR [15318](https://github.com/easybuilders/easybuild-easyconfigs/pull/15318) open where I am using the GitLab source. Does it make sense to move that over to the URL used here as well? At the time when I opened that PR I did not know about the URL used here and now I got a bit better understanding thanks to a very helpful maintainer from YAXT. 
What is your suggestion?

**Comment by smoors** [comment]
> I also have PR [15318](https://github.com/easybuilders/easybuild-easyconfigs/pull/15318) open where I am using the GitLab source. Does it make sense to move that over to the URL used here as well?

I think so, yes.

**Comment by smoors** [comment]
@boegelbot: please test @ generoso EB_ARGS="--force-download"

**Comment by smoors** [comment]
Test report by @smoors
**SUCCESS**
Build succeeded for 3 out of 3 (3 easyconfigs in total)
node373.hydra.os - Linux CentOS Linux 7.9.2009, x86_64, Intel(R) Xeon(R) Gold 6148 CPU @ 2.40GHz (skylake_avx512), Python 2.7.5
See https://gist.github.com/ffdf57905aedff22931cdc4286fb39d3 for a full test report.

**Review by smoors — APPROVED** [review]
lgtm

**Comment by smoors** [comment]
Going in, thanks @sassy-crick!

**Pull request merged**
