### PR TITLE
{lib}[GCCcore/13.2.0] add hatchling to tqdm 0.66.2

### PR DESCRIPTION
**Pull request by fizwit**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by verdurin** [comment]
@boegelbot please test @ generoso

**Comment by verdurin** [comment]
Test report by @verdurin
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
easybuild-c7.novalocal - Linux CentOS Linux 7.9.2009, x86_64, Intel Xeon Processor (Skylake, IBRS), Python 3.6.8
See https://gist.github.com/verdurin/0a557f7ed9f510456f695e65fa188ea1 for a full test report.

**Comment by migueldiascosta** [comment]
@boegelbot please test @ jsc-zen3

**Comment by boegel** [comment]
There should be no need for this PR, it's probably fallout because we added `setuptools_scm` to `Python` in #19777, so closing this PR.

To fix the problems with `tdqm`, you should add the missing extensions to `Python` by running `eb Python-3.11.5-GCCcore-13.2.0.eb --rebuild --skip` with EasyBuild v4.9.1 (or newer)

**Pull request closed without merging**
