### PR TITLE
{bio}[foss/2018b,fosscuda/2018b] GROMACS v2018.3

### PR DESCRIPTION
**Pull request by akesandgren**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by boegel** [comment]
Test report by @boegel
**FAILED**
Build succeeded for 0 out of 1 (1 easyconfigs in this PR)
node3120.skitty.os - Linux centos linux 7.5.1804, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz, Python 2.7.5
See https://gist.github.com/6c8c8869b9ad0d4b644281fd62884567 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**FAILED**
Build succeeded for 0 out of 1 (1 easyconfigs in this PR)
node3120.skitty.os - Linux centos linux 7.5.1804, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz, Python 2.7.5
See https://gist.github.com/74606b5052322b0ef7b8e320d7a5dbc3 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
node2523.golett.os - Linux centos linux 7.5.1804, Intel(R) Xeon(R) CPU E5-2680 v3 @ 2.50GHz, Python 2.7.5
See https://gist.github.com/c51f431505a617d150f15410d5294447 for a full test report.

**Comment by akesandgren** [comment]
Going to add a fosscuda .eb to this one, so don't merge just yet.

**Comment by akesandgren** [comment]
Test report by @akesandgren
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in this PR)
b-cn1517.hpc2n.umu.se - Linux ubuntu 16.04, Intel(R) Xeon(R) Gold 6132 CPU @ 2.60GHz, Python 2.7.12
See https://gist.github.com/ca42ce7e4e771bfc6cdf548d3265cf4e for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in this PR)
node2063.delcatty.os - Linux centos linux 7.5.1804, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.7.5
See https://gist.github.com/66a75c9bbbdfda0020d6236eba3d157a for a full test report.

**Comment by boegel** [comment]
@akesandgren Any idea about the failing test report in a SLURM job environment? Is that to be expected with `GROMACS`?

**Comment by akesandgren** [comment]
Unrelated to GROMACS i think, there was a discussion on the OpenMPI list about that exact error, today actually.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in this PR)
node3155.skitty.os - Linux centos linux 7.5.1804, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz, Python 2.7.5
See https://gist.github.com/24e5555d7b4c49cd8adae544da72bf00 for a full test report.

**Comment by boegel** [comment]
Reran the test outside of a SLURM job environment, works fine, so good to go.

@akesandgren Any pointers to the OpenMPI thread?

**Comment by boegel** [comment]
Going in, thanks @akesandgren!

**Comment by akesandgren** [comment]
No, I don't have it around, but it was mailed yesterday. Should be easy to find in their archive.

**Comment by boegel** [comment]
@akesandgren Can't seem to spot anything related to SLURM at https://www.mail-archive.com/users@lists.open-mpi.org//maillist.html?

**Comment by akesandgren** [comment]
I didn't say slurm I said OpenMPI. This one, https://www.mail-archive.com/users@lists.open-mpi.org//msg32681.html

**Pull request merged**
