### PR TITLE
{bio}[foss/2019b] FSL v6.0.5.1 w/ Python 3.7.4

### PR DESCRIPTION
**Pull request by verdurin**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by verdurin** [comment]
If this one works, I will create equivalents for newer toolchains.

**Comment by orbsmiv** [comment]
@verdurin is this building against 2019b? I'm trying the same version on 2021a (the user requires it in order to run the `fslr` R-package with R 4.1.0) but with limited success.

**Comment by orbsmiv** [comment]
@verdurin - you may have spotted this already but there's a Python version bake-in issue in the `build` script:

```sh
169 # Create the site-packages directory for fslpy
170 mkdir -p lib/python3.7/site-packages
171 ln -s lib lib64
```

**Comment by branfosj** [comment]
As this PR is WIP or draft and has not been updated in over a year I have closed it. If you work on this again then please reopen the PR.

**Pull request closed without merging**
