### PR TITLE
{bio}[foss/2021b,intel/2021b] MDAnalysis v2.0.0 w/ Python 3.9.6

### PR DESCRIPTION
**Pull request by SebastianAchilles**
(created using `eb --new-pr`)

Depends on:
- [x] https://github.com/easybuilders/easybuild-easyconfigs/pull/14766
- [x] https://github.com/easybuilders/easybuild-easyconfigs/pull/14767

### CODE REVIEW

**Comment by SebastianAchilles** [comment]
Test report by @sebastianachilles
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in total)
jsfc01.int.jusuf.sebastian.cluster - Linux rocky linux 8.4, x86_64, AMD EPYC 7742 64-Core Processor (zen2), 1 x NVIDIA GRID V100-4C, 460.73.01, Python 3.6.8
See https://gist.github.com/842c26ce4f9c6f591f956a2f44903523 for a full test report.

**Comment by migueldiascosta** [comment]
@boegelbot please test @ generoso

**Comment by SebastianAchilles** [comment]
Test report by @sebastianachilles
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in total)
jscskxl1.int.jsc-skx.easybuild-test.cluster - Linux Rocky Linux 8.5, x86_64, Intel Xeon Processor (Skylake, IBRS) (skylake_avx512), Python 3.6.8
See https://gist.github.com/bdd1ccaa80d6543525bbc305e8924e62 for a full test report.

**Comment by SebastianAchilles** [comment]
@boegelbot please test @ generoso

**Review by migueldiascosta — APPROVED** [review]
lgtm

**Comment by migueldiascosta** [comment]
Going in, thanks @SebastianAchilles!

**Pull request merged**
