### PR TITLE
{chem}[intel/2017a] NWChem v6.6.revision27746

### PR DESCRIPTION
**Pull request by boegel**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by boegel** [comment]
This NWChem easyconfig is slightly different from the existing `NWChem-6.6.revision27746-iomkl-2017a-2015-10-20-Python-2.7.12.eb` contributed by @akesandgren (#4231) since it also downloads and applies all available patches (cfr. http://www.nwchem-sw.org/index.php/Download#Patches_for_the_27746_revision_of_NWChem_6.6).

All patches apply cleanly without effort, and test cases work as expected; according to @hajgato who is familiar with NWChem, this is the right way to go.

Thoughts @akesandgren, should we also include these patches in the easyconfig you contributed in #4231?

Test reports coming up...

**Comment by akesandgren** [comment]
Downloading patches makes the code diverge from the version given in the module and is thus not a good idea.
The eb file and the resulting version MUST clearly show that this is a heavily patched version, not just one with the minor fixes included at the moment.

Basically, it's usually much better from a user and result repeatability perspective to have the upstream version unpatched, unless the patch is vital to make it work in the first place.

**Comment by boegel** [comment]
@akesandgren I haven't checked all of the patches, but I'd expect some of them deal with important bugs in NWChem 6.6, e.g. faulty results being generated. The patches are official though, they're not just pulled from any random source.
I do wish they'd just do more frequent bugfix releases, we're actually fixing their problem here...

I agree there's a concern about reproducibility of results, but what good are reproducible results if they're wrong?

I guess we make it clear somehow that this is a patched version of NWChem, by adding (yet another) tag in the `versionsuffix`? It's already pretty bloated there though...

**Comment by akesandgren** [comment]
Yes, that's what I mean. The version must show that this is NOT pure v6.6.revision27746

If for no other reason then being able to report bugs to NWChem with a relevant version number.

**Comment by boegel** [comment]
Any better suggestions than including something like `patches-20170829` in the `versionsuffix` as well? I can't think of something better...

**Comment by akesandgren** [comment]
Not really. Could perhaps be made better if there is a correlation to the patches listed, but i haven't checked the nwchem pages in a while...
Maybe the date should reflect the date of the latest of the patches if that can be retrieved.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
node2125.delcatty.os - Linux centos linux 7.3.1611, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.7.5
See https://gist.github.com/eb85482d0c58fb407d32b16659727e46 for a full test report.

**Comment by boegel** [comment]
@akesandgren Please re-review?

**Comment by boegel** [comment]
@akesandgren It does, see test reports.

**Comment by akesandgren** [comment]
I know, thats why i said "approved" :-)

**Pull request merged**
