### PR TITLE
[libxc] Update URLs to new location

### PR DESCRIPTION
**Pull request by Flamefire**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by boegel** [comment]
Test report by @boegel
**FAILED**
Build succeeded for 30 out of 32 (32 easyconfigs in this PR)
generoso - Linux centos linux 7.6.1810, Intel(R) Xeon(R) CPU E5-2660 v4 @ 2.00GHz, Python 3.6.8
See https://gist.github.com/60a4bb82a9137ce703bf42631c8486ae for a full test report.

**Comment by Flamefire** [comment]
Sorry I missed those 2. This repo is so big searching takes forever so they must be found after I gave up waiting ;)

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 32 out of 32 (32 easyconfigs in this PR)
gligar04.gastly.os - Linux centos linux 7.7.1908, Intel(R) Xeon(R) Gold 6130 CPU @ 2.10GHz, Python 2.7.5
See https://gist.github.com/c94d6666890742000fbb942aed486b9d for a full test report.

**Comment by boegel** [comment]
Going in, thanks @Flamefire!

**Pull request merged**
