### PR TITLE
Add OpenEXR to POV-Ray

### PR DESCRIPTION
**Pull request by Micket**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by Micket** [comment]
Test report by @Micket
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in total)
vera-c2 - Linux Rocky Linux 8.5, x86_64, Intel Xeon Processor (Skylake), Python 3.6.8
See https://gist.github.com/eb76110efd0aca565004d20853a96b3b for a full test report.

**Comment by jfgrimm** [comment]
Test report by @jfgrimm
**SUCCESS**
Build succeeded for 3 out of 3 (2 easyconfigs in total)
node133.pri.viking.alces.network - Linux CentOS Linux 7.9.2009, x86_64, Intel(R) Xeon(R) Gold 6138 CPU @ 2.00GHz (skylake_avx512), Python 3.6.8
See https://gist.github.com/f87ec411654200344bde22178728fa4c for a full test report.

**Comment by jfgrimm** [comment]
@Micket judging by https://github.com/AcademySoftwareFoundation/openexr/blob/main/INSTALL.md#prerequisites we're going to need zlib as a dep in OpenEXR. It also auto-downloads and installs `Imath` if not provided as a dependency

**Comment by casparvl** [comment]
See https://github.com/easybuilders/easybuild-easyconfigs/pull/16276/files for how to split-off `Imath`. It's preferable that way, since the auto-downloaded otherwise causes `OpenEXR` to not be installeable on offline systems.

**Comment by Micket** [comment]
Test report by @Micket
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
alvis-c1 - Linux Rocky Linux 8.5, x86_64, Intel Xeon Processor (Skylake), Python 3.6.8
See https://gist.github.com/a6c457be56f06515e3b25f13b6d724c9 for a full test report.

**Comment by casparvl** [comment]
Test report by @casparvl
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
tcn1.local.snellius.surf.nl - Linux RHEL 8.4, x86_64, AMD EPYC 7H12 64-Core Processor, Python 3.6.8
See https://gist.github.com/4ffa8dcf6757c24f6b881bea2ced09a6 for a full test report.

**Review by casparvl — APPROVED** [review]
Lgtm!

**Comment by casparvl** [comment]
Test report by @casparvl
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
software1.lisa.surfsara.nl - Linux debian 10.13, x86_64, Intel(R) Xeon(R) Silver 4110 CPU @ 2.10GHz, Python 3.7.3
See https://gist.github.com/f447f1b0f1830dc1ad886623cab4a92b for a full test report.

**Comment by casparvl** [comment]
Going in, thanks @Micket!

**Pull request merged**
