### PR TITLE
Ghostscript fails to build on aarch64/arm without pkg-config as a build dependency

### LINKED ISSUE #11193: Ghostscript-9.52-GCCcore-9.3.0.eb fails on arm/aarch64 without png-config as a builddependency
This is a bit of an odd one. Without pkg-config, Ghostscript uses some in-house checking for supported versions of FreeType, which leads to this:

```
[...]
checking for FT_Init_FreeType in -lfreetype... yes
checking for system freetype2 library >= 2.4.2... no
[...]
```

The config.log says:

```
configure:7390: checking for system freetype2 library >= 2.4.2
configure:7415: gcc -c -O2 -ftree-vectorize -mcpu=native -fno-math-errno -fPIC -DHAVE_RESTRICT=1 -I/home/terjekv/.local/easybuild/software/LibTIFF/4.1.0-GCCcore-9.3.0/include
 -I/home/terjekv/.local/easybuild/software/cairo/1.16.0-GCCcore-9.3.0/include -I/home/terjekv/.local/easybuild/software/GLib/2.64.1-GCCcore-9.3.0/include -I/home/terjekv/.loc
al/easybuild/software/expat/2.2.9-GCCcore-9.3.0/include -I/home/terjekv/.local/easybuild/software/libjpeg-turbo/2.0.4-GCCcore-9.3.0/include -I/home/terjekv/.local/easybuild/s
oftware/freetype/2.10.1-GCCcore-9.3.0/include -I/home/terjekv/.local/easybuild/software/libpng/1.6.37-GCCcore-9.3.0/include -I/home/terjekv/.local/easybuild/software/zlib/1.2
.11-GCCcore-9.3.0/include -I/home/terjekv/.local/easybuild/software/binutils/2.34-GCCcore-9.3.0/include conftest.c >&5
conftest.c: In function 'main':
conftest.c:60:20: error: 'FAIL' undeclared (first use in this function)
   60 |                    FAIL
      |                    ^~~~
conftest.c:60:20: note: each undeclared identifier is reported only once for each function it appears in
conftest.c:60:24: error: expected ';' before 'return'
   60 |                    FAIL
      |                        ^
      |                        ;
   61 |                  #endif
   62 |                  return(0);
      |                  ~~~~~~
configure:7415: $? = 1
configure: failed program was:
| /* confdefs.h */
| #define PACKAGE_NAME ""
| #define PACKAGE_TARNAME ""
| #define PACKAGE_VERSION ""
| #define PACKAGE_STRING ""
| #define PACKAGE_BUGREPORT ""
| #define PACKAGE_URL ""
| #define STDC_HEADERS 1
| #define HAVE_SYS_TYPES_H 1
| #define HAVE_SYS_STAT_H 1
| #define HAVE_STDLIB_H 1
| #define HAVE_STRING_H 1
| #define HAVE_MEMORY_H 1
| #define HAVE_STRINGS_H 1
| #define HAVE_INTTYPES_H 1
| #define HAVE_STDINT_H 1
| #define HAVE_UNISTD_H 1
| #define HAVE_DIRENT_H 1
| #define STDC_HEADERS 1
| #define HAVE_ERRNO_H 1
| #define HAVE_FCNTL_H 1
| #define HAVE_LIMITS_H 1
| #define HAVE_MALLOC_H 1
| #define HAVE_MEMORY_H 1
| #define HAVE_STDLIB_H 1
| #define HAVE_STRING_H 1
| #define HAVE_STRINGS_H 1
| #define HAVE_SYS_IOCTL_H 1
| #define HAVE_SYS_PARAM_H 1
| #define HAVE_SYS_TIME_H 1
| #define HAVE_SYS_TIMES_H 1
| #define HAVE_SYSLOG_H 1
| #define HAVE_UNISTD_H 1
| #define HAVE_DIRENT_H 1
| #define HAVE_SYS_DIR_H 1
| #define HAVE_INTTYPES_H 1
| #define HAVE_STRUCT_STAT_ST_BLOCKS 1
| #define HAVE_ST_BLOCKS 1
| #define TIME_WITH_SYS_TIME 1
| #define SIZEOF_UNSIGNED_LONG_LONG 8
| #define HAVE_LIBM 1
| #define HAVE_PREAD 1
| #define HAVE_PWRITE 1
| #define HAVE_DECL_PWRITE 1
| #define HAVE_DECL_PREAD 1
| /* end confdefs.h.  */
| #include "ft2build.h"
|               #include FT_FREETYPE_H
| int
| main ()
| {
|
|                  #if FREETYPE_MAJOR < 2
|                    FAIL
|                  #endif
|                  #if FREETYPE_MINOR < 4
|                    FAIL
|                  #endif
|                  #if FREETYPE_PATCH < 2
|                    FAIL
|                  #endif
|                  return(0);
|
|   ;
|   return 0;
| }
configure:7419: result: no
configure:7432: error: No usable Freetype source or library found
```

With pkg-config as a build dependency, Ghostscript installs fine.

### PR DESCRIPTION
**Pull request by terjekv**
(created using `eb --new-pr`)

fixes #11193

### CODE REVIEW

**Comment by migueldiascosta** [comment]
Test report by @migueldiascosta
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
sms - Linux centos linux 7.6.1810, x86_64, AMD EPYC 7601 32-Core Processor (zen), Python 2.7.5
See https://gist.github.com/0db03613da5743439d12d337d96c4ed6 for a full test report.

**Review by migueldiascosta — APPROVED** [review]
looks harmless to me

**Comment by boegel** [comment]
@boegelbot please test @ generoso

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
node3152.skitty.os - Linux centos linux 7.8.2003, x86_64, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz (skylake_avx512), Python 3.6.8
See https://gist.github.com/9a3ab7d9fe3293e9bc1ac0aabf801495 for a full test report.

**Comment by boegel** [comment]
Going in, thanks @terjekv!

**Pull request merged**
