### PR TITLE
{math}[foss/2017b] SCOTCH v6.0.4 64bit int

### PR DESCRIPTION
**Pull request by smoors**

### CODE REVIEW

**Comment by boegel** [comment]
@smoors Can you clarify the need for this? Isn't this exactly the same as the existing `SCOTCH-6.0.4-foss-2017b.eb`, other than the `versionsuffix`?

**Comment by smoors** [comment]
The i8 toolchain option was added to generate a 64bit integer version.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
node2477.golett.os - Linux centos linux 7.4.1708, Intel(R) Xeon(R) CPU E5-2680 v3 @ 2.50GHz, Python 2.7.5
See https://gist.github.com/f7891b730ac5a597b2561f2778198184 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
node2016.delcatty.os - Linux centos linux 7.4.1708, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.7.5
See https://gist.github.com/9902a4449b1d73e2871981702ed53efd for a full test report.

**Comment by boegel** [comment]
Going in, thanks @smoors!

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
node2016.delcatty.os - Linux centos linux 7.4.1708, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.7.5
See https://gist.github.com/da68d4691291de349c50e21720f655ff for a full test report.

**Pull request merged**
