### PR TITLE
{bio}[goolf/1.7.20] SPAdes v3.9.1

### PR DESCRIPTION
**Pull request by pescobar**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by boegel** [comment]
@pescobar missing dep: `Irresolvable dependencies encountered: CMake/3.4.3-goolf-1.7.20`

**Comment by boegel** [comment]
@pescobar existing recent easyconfigs for `SPAdes` also include this to avoid picking up Boost from the OS:

```python
 configopts = ' -DBoost_NO_BOOST_CMAKE=ON'
```

**Comment by boegel** [comment]
@pescobar ping on the remark?

**Comment by boegel** [comment]
@pescobar re-ping?

**Comment by migueldiascosta** [comment]
@pescobar, this PR is being closed for the following reason(s): uses a deprecated toolchain.
For more information on deprecated toolchains, see https://easybuild.readthedocs.io/en/latest/Deprecated-easyconfigs.html#deprecated-toolchains.
Please consider reopening or submitting a new PR using a supported toolchain.
For more information on our policy w.r.t. closing PRs, see https://easybuild.readthedocs.io/en/latest/Contributing.html#why-a-pull-request-may-be-closed-by-a-maintainer

**Pull request closed without merging**
