### PR TITLE
Create tmux-3.2-GCCcore-10.2.0.eb

### PR DESCRIPTION
**Pull request by Ghepardo**
New easyconfig for tmux 3.2.

### CODE REVIEW

**Comment by Ghepardo** [comment]
I'd previously submitted pull request #12637 for this, but I think I got the branch wrong - I tried to get it merged into 'main'.  Trying again for 'develop'.

**Comment by Micket** [comment]
@boegelbot please test @ generoso

**Comment by Micket** [comment]
Test report by @Micket
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
vera-c1 - Linux centos linux 7.9.2009, x86_64, Intel Xeon Processor (Skylake), Python 2.7.5
See https://gist.github.com/817d7f2dc538b7e5a449c14e87567fd4 for a full test report.

**Review by Micket — APPROVED** [review]
lgtm (looked through the build log, also looks alright)

**Pull request merged**
