### PR TITLE
{vis}[GCC/8.2.0-2.31.1] wxPython v4.0.4

### PR DESCRIPTION
**Pull request by akesandgren**
(created using `eb --new-pr`)
Depends on ~~#8273 #8125~~

### CODE REVIEW

**Comment by akesandgren** [comment]
Test report by @akesandgren
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in this PR)
b-an03.hpc2n.umu.se - Linux ubuntu 16.04, Intel(R) Xeon(R) CPU E5-2690 v4 @ 2.60GHz, Python 2.7.12
See https://gist.github.com/a30f718131d14a96b62091e4cb49da56 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in this PR)
node3101.skitty.os - Linux centos linux 7.6.1810, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz, Python 2.7.5
See https://gist.github.com/a5ffcf12c51ebe8a1b1410264564e93c for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in this PR)
node2727.swalot.os - Linux centos linux 7.6.1810, Intel(R) Xeon(R) CPU E5-2660 v3 @ 2.60GHz, Python 2.7.5
See https://gist.github.com/785fc7bb6e8e0fd7c4b7bedd8164f6f7 for a full test report.

**Comment by boegel** [comment]
@akesandgren 

```
eb --check-style --from-pr 8132
== temporary log file in case of crash /tmp/eb-x5oOMO/easybuild-qJTrQ1.log

Running style check on 2 easyconfig(s)...

/tmp/eb-x5oOMO/files_pr8132/w/wxPython/wxPython-4.0.4-GCC-8.2.0-2.31.1-Python-2.7.15.eb:45:121: E501 line too long (125 > 120 characters)
[FAIL] /tmp/eb-x5oOMO/files_pr8132/w/wxPython/wxPython-4.0.4-GCC-8.2.0-2.31.1-Python-2.7.15.eb
/tmp/eb-x5oOMO/files_pr8132/w/wxPython/wxPython-4.0.4-GCC-8.2.0-2.31.1-Python-3.7.2.eb:45:121: E501 line too long (125 > 120 characters)
[FAIL] /tmp/eb-x5oOMO/files_pr8132/w/wxPython/wxPython-4.0.4-GCC-8.2.0-2.31.1-Python-3.7.2.eb

ERROR: One or more style checks FAILED!
```

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in this PR)
node2006.delcatty.os - Linux centos linux 7.6.1810, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.7.5
See https://gist.github.com/fc5886aafd34f4ec26f141b846fa4b9d for a full test report.

**Comment by akesandgren** [comment]
Test report by @akesandgren
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in this PR)
b-an03.hpc2n.umu.se - Linux ubuntu 16.04, Intel(R) Xeon(R) CPU E5-2690 v4 @ 2.60GHz, Python 2.7.12
See https://gist.github.com/dd25a87ff5c71842793c34e507456c41 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in this PR)
node2447.golett.os - Linux centos linux 7.6.1810, Intel(R) Xeon(R) CPU E5-2680 v3 @ 2.50GHz, Python 2.7.5
See https://gist.github.com/0434b96834dd8ca408c481dea53422a7 for a full test report.

**Comment by boegel** [comment]
Going in, thanks @akesandgren!

**Pull request merged**
