### PR TITLE
{vis}[GCCcore/8.2.0,intel/2019a] bwidget v1.9.13, XCrySDen v1.5.60

### PR DESCRIPTION
**Pull request by Micket**
(created using `eb --new-pr`)

Depends on https://github.com/easybuilders/easybuild-easyblocks/pull/1749

Only intel version, newer gfortran fails to compile some parts of the code.

### CODE REVIEW

**Comment by Micket** [comment]
kicking travis

**Comment by Micket** [comment]
Travis kicked

**Comment by vanzod** [comment]
Test report by @vanzod
**FAILED**
Build succeeded for 1 out of 2 (2 easyconfigs in this PR)
cermis - Linux debian 9.9, Intel(R) Xeon(R) CPU           X5670  @ 2.93GHz, Python 2.7.13
See https://gist.github.com/0f751ab904b92183e82805b5d6609561 for a full test report.

**Comment by vanzod** [comment]
@Micket It looks like `libGLU/9.0.0` is also needed as dependency for `XCrySDen`

**Comment by smoors** [comment]
Test report by @smoors
**FAILED**
Build succeeded for 1 out of 2 (2 easyconfigs in this PR)
nic426 - Linux centos linux 7.5.1804, Intel(R) Xeon(R) Gold 6148 CPU @ 2.40GHz, Python 2.7.5
See https://gist.github.com/192610701b72fa2c37bba2b65783000a for a full test report.

**Comment by smoors** [comment]
Test report by @smoors
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in this PR)
nic426 - Linux centos linux 7.5.1804, Intel(R) Xeon(R) Gold 6148 CPU @ 2.40GHz, Python 2.7.5
See https://gist.github.com/a9866d0cc5789fcf15db79c51f87ffbb for a full test report.

**Comment by smoors** [comment]
Going in, thanks @Micket!

**Pull request merged**
