### PR TITLE
add patch for OpenMPI 4.0.x to fix building against (system) UCX version > 1.7

### PR DESCRIPTION
**Pull request by Flamefire**
(created using `eb --new-pr`)

This fixes errors like seen at https://github.com/easybuilders/easybuild-easyblocks/pull/2444#issuecomment-857548759

Backported from 4.0.3

### CODE REVIEW

**Comment by boegel** [comment]
@boegelbot please test @ generoso
CORE_CNT=16

**Comment by Flamefire** [comment]
Test report by @Flamefire
Using easyblocks from PR(s) https://github.com/easybuilders/easybuild-easyblocks/pull/2501
**SUCCESS**
Build succeeded for 3 out of 3 (3 easyconfigs in total)
taurusi6197.taurus.hrsk.tu-dresden.de - Linux RHEL 7.9, x86_64, Intel(R) Xeon(R) CPU E5-2680 v3 @ 2.50GHz (haswell), Python 2.7.5
See https://gist.github.com/dd94f8b15bd964c63ecd243f8069cbdf for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in total)
node3142.skitty.os - Linux centos linux 7.9.2009, x86_64, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz, Python 3.6.8
See https://gist.github.com/f21f4fee67bb19f0e1d9a0e29725fe71 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 3 out of 3 (3 easyconfigs in total)
node3599.doduo.os - Linux RHEL 8.2, x86_64, AMD EPYC 7552 48-Core Processor (zen2), Python 3.6.8
See https://gist.github.com/88ed03df72c675fa7ad4737f64d91354 for a full test report.

**Review by boegel — APPROVED** [review]
lgtm

**Comment by boegel** [comment]
Going in, thanks @Flamefire!

**Pull request merged**
