### PR TITLE
{tools}[GCCcore/12.3.0] Vim v9.1.0004

### PR DESCRIPTION
**Pull request by cgross95**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by cgross95** [comment]
Test report by @cgross95
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
lac-353 - Linux Ubuntu 22.04.3 LTS (Jammy Jellyfish), x86_64, Intel(R) Xeon(R) CPU E5-2680 v4 @ 2.40GHz (broadwell), Python 3.11.4
See https://gist.github.com/cgross95/024b119222ef72e6d2b0ba0fbeedef66 for a full test report.

**Comment by Micket** [comment]
@boegelbot please test @ generoso

**Comment by Micket** [comment]
Test report by @Micket
**SUCCESS**
Build succeeded for 2 out of 2 (1 easyconfigs in total)
vera-skylake-build - Linux Rocky Linux 8.9, x86_64, Intel Xeon Processor (Skylake, IBRS, no TSX), Python 3.6.8
See https://gist.github.com/Micket/65f4d6c4e2c138011b02332b2c647c49 for a full test report.

**Comment by Micket** [comment]
@boegelbot please test @ jsc-zen3

**Comment by verdurin** [comment]
Test report by @verdurin
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
easybuild-c7.novalocal - Linux CentOS Linux 7.9.2009, x86_64, Intel Xeon Processor (Skylake, IBRS), Python 3.6.8
See https://gist.github.com/verdurin/bf3e2fea3057b4e86cb5630f08be0714 for a full test report.

**Review by verdurin — APPROVED** [review]
Looks fine.

**Comment by verdurin** [comment]
@cgross95 thanks for the contribution and welcome to EasyBuild.

**Comment by verdurin** [comment]
Going in, thanks @cgross95!

**Pull request merged**
