### PR TITLE
{tools}[dummy/dummy] EasyBuild v3.6.0

### PR DESCRIPTION
**Pull request by boegel**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
boegel.ugent.be - Darwin UNKNOWN UNKNOWN, Intel(R) Core(TM) i5-7360U CPU @ 2.30GHz, Python 2.7.10
See https://gist.github.com/c6f82497711bfb29e83210380ba858dc for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
node2691.swalot.os - Linux centos linux 7.4.1708, Intel(R) Xeon(R) CPU E5-2660 v3 @ 2.60GHz, Python 2.7.5
See https://gist.github.com/3b47f09875e35d6160e072d91657c983 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
node2069.delcatty.os - Linux centos linux 7.4.1708, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.7.5
See https://gist.github.com/f73b25cd2c7cd352de0ff00cb4054095 for a full test report.

**Comment by vanzod** [comment]
Test report by @vanzod
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
cermis - Linux debian 9.4, Intel(R) Xeon(R) CPU           E5620  @ 2.40GHz, Python 2.7.13
See https://gist.github.com/bc9a9750128e245d4f6f487fd0eb95ac for a full test report.

**Comment by vanzod** [comment]
Going in, thanks @boegel!

**Pull request merged**
