### PR TITLE
{bio}[foss-2020b,fosscuda-2020b] OpenMM v7.5.1

### PR DESCRIPTION
**Pull request by sassy-crick**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by sassy-crick** [comment]
Do we need a Python version as well? Please let me know and I will do that too.

**Review by Micket — CHANGES_REQUESTED** [review]
No need to duplicate the patch, just refer to the 7.5.0 version

**Comment by Micket** [comment]
> Do we need a Python version as well? Please let me know and I will do that too.

I don't understand what you mean

**Comment by sassy-crick** [comment]
> No need to duplicate the patch, just refer to the 7.5.0 version
I agree. I was not sure if that is the accepted solution for the patch:
`patches = ['%(name)s-7.5.0_fix_path_to_nvcc.patch']`
as I basically hard-code the patch in there. If you are happy with this, I shall be too.

Python: I meant similar to this EC:
`OpenMM-7.5.0-fosscuda-2020a-Python-3.8.2.eb`
With all the recent discussions about how to handle CUDA and Python, I am a bit confused.

**Comment by sassy-crick** [comment]
> No need to duplicate the patch, just refer to the 7.5.0 version

I have set the version of the patch fix to 7.5.0 in the EC file. Let me know if there is a better way of doing that.

**Review by Micket — APPROVED** [review]
LGTM

**Comment by Micket** [comment]
Test report by @Micket
**FAILED**
Build succeeded for 2 out of 3 (2 easyconfigs in total)
alvis-c1 - Linux centos linux 7.9.2009, x86_64, Intel Xeon Processor (Skylake), Python 3.6.8
See https://gist.github.com/4b953a8a5b4d972f52da89bede8dfa60 for a full test report.

**Comment by Micket** [comment]
I'm going to have a bit of a hard time with the test reports since they require a GPU (and my test-build machine doesn't have one)

**Comment by branfosj** [comment]
> I'm going to have a bit of a hard time with the test reports since they require a GPU (and my test-build machine doesn't have one)

I've set off test reports from our GPU systems.

**Comment by branfosj** [comment]
Test report by @branfosj
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
bask-pg0309u05a - Linux RHEL 8.4, x86_64, Intel(R) Xeon(R) Platinum 8360Y CPU @ 2.40GHz (icelake), Python 3.6.8
See https://gist.github.com/a29e7cfcf5e162d9ef039cd920eff949 for a full test report.

**Comment by branfosj** [comment]
Test report by @branfosj
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in total)
bear-pg0305u15a.bear.cluster - Linux RHEL 8.4, POWER, 8335-GTX (power9le), Python 3.6.8
See https://gist.github.com/292d0fa2d0ae02ab360844d5de3d11a0 for a full test report.

**Comment by branfosj** [comment]
Test report by @branfosj
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
bask-pg0309u04a - Linux RHEL 8.4, x86_64, Intel(R) Xeon(R) Platinum 8360Y CPU @ 2.40GHz (icelake), Python 3.6.8
See https://gist.github.com/e46ed2426a844f145c266e3000e2b6c3 for a full test report.

**Review by boegel — APPROVED** [review]
lgtm

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in total)
node3301.joltik.os - Linux centos linux 7.9.2009, x86_64, Intel(R) Xeon(R) Gold 6242 CPU @ 2.80GHz (cascadelake), Python 3.6.8
See https://gist.github.com/574837b5f5eddd43a22f74be46e30a23 for a full test report.

**Comment by boegel** [comment]
Going in, thanks @sassy-crick!

**Pull request merged**
