### PR TITLE
{devel}[GCCcore/9.3.0] Qt5 v5.14.1

### PR DESCRIPTION
**Pull request by branfosj**
(created using `eb --new-pr`)

EasyBlock change: https://github.com/easybuilders/easybuild-easyblocks/pull/2000

Deps:
* snappy (1.1.8) ~~#10219~~
* DBus (1.13.12) ~~#10218~~ 
* double-conversion (3.1.5) ~~#10217~~ 
* libevent (2.1.11) ~~#10078~~ 
* PCRE2 (10.34) ~~#10221~~
* re2c (1.3) ~~#10133~~ 
* libGLU (9.0.1) ~~#10176~~ 
* NSS (3.47) ~~#10243~~ 
* NSPR (4.25) ~~#10243~~

### CODE REVIEW

**Comment by branfosj** [comment]
Test report by @branfosj
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
bear-pg0305u03a.bear.cluster - Linux RHEL 7.6, 8335-GTX, Python 2.7.5
See https://gist.github.com/185fa0a873ef1b69a5693d06be9192b4 for a full test report.

**Comment by branfosj** [comment]
Test report by @branfosj
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
bear-pg0211u03a.bear.cluster - Linux centos linux 7.7.1908, Intel(R) Xeon(R) Gold 6248 CPU @ 2.50GHz, Python 2.7.5
See https://gist.github.com/77ee37b383110528eb8b82e62383a179 for a full test report.

**Comment by branfosj** [comment]
Test report by @branfosj
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
bber0501u03a.bb2.cluster - Linux centos linux 7.7.1908, Intel(R) Xeon(R) CPU E5-2690 v3 @ 2.60GHz, Python 2.7.5
See https://gist.github.com/f8545d0eaaf58d961f4d78cf492faa9a for a full test report.

**Comment by boegel** [comment]
close/re-open to wake up Travis...

**Comment by branfosj** [comment]
Test report by @branfosj
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
bb2c1a10.bb2.cluster - Linux centos linux 7.7.1908, Intel(R) Xeon(R) CPU E5-2660 0 @ 2.20GHz, Python 2.7.5
See https://gist.github.com/06f189c44c859e43c967316c5103e9bf for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 10 out of 10 (1 easyconfigs in this PR)
node3117.skitty.os - Linux centos linux 7.7.1908, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz, Python 3.6.8
See https://gist.github.com/cd1b5432b42c5a9c890bfaa0be73d981 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 10 out of 10 (1 easyconfigs in this PR)
node2415.golett.os - Linux centos linux 7.7.1908, Intel(R) Xeon(R) CPU E5-2680 v3 @ 2.50GHz, Python 2.7.5
See https://gist.github.com/5293eb3745d5bd0c3546e6a27a1bbdfa for a full test report.

**Comment by branfosj** [comment]
The previous changes were to kick Travis into life. Now GitHub actions is failing with:
```
Could not connect to azure.archive.ubuntu.com:80 (52.177.174.250), connection timed out
```

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
generoso - Linux centos linux 7.6.1810, Intel(R) Xeon(R) CPU E5-2660 v4 @ 2.00GHz, Python 3.6.8
See https://gist.github.com/9f0c3745db5c9d182409d3f50b3652d6 for a full test report.

**Comment by boegel** [comment]
Going in, thanks @branfosj!

**Pull request merged**
