### PR TITLE
{bio}[foss/2020a] deepTools v3.3.1 w/ Python 3.8.2

### PR DESCRIPTION
**Pull request by FokkeDijkstra**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by verdurin** [comment]
Test report by @verdurin
**SUCCESS**
Build succeeded for 3 out of 3 (1 easyconfigs in this PR)
easybuild.novalocal - Linux centos linux 7.8.2003, x86_64, Intel Xeon Processor (Skylake, IBRS), Python 2.7.5
See https://gist.github.com/9108bae9af849d7f93eb11044442e4f5 for a full test report.

**Comment by verdurin** [comment]
@FokkeDijkstra Could you attach a test report?

**Comment by FokkeDijkstra** [comment]
Test report by @FokkeDijkstra
**SUCCESS**
Build succeeded for 0 out of 0 (1 easyconfigs in this PR)
pg-interactive.hpc.rug.nl - Linux centos linux 7.7.1908, x86_64, Intel(R) Xeon(R) CPU E5-2680 v3 @ 2.50GHz, Python 2.7.5
See https://gist.github.com/a5e0ed632b1e796e4352a9d6fc3d13d8 for a full test report.

**Comment by smoors** [comment]
Test report by @smoors
**SUCCESS**
Build succeeded for 3 out of 3 (1 easyconfigs in this PR)
node366.hydra.os - Linux centos linux 7.7.1908, x86_64, Intel(R) Xeon(R) Gold 6148 CPU @ 2.40GHz (skylake_avx512), Python 2.7.5
See https://gist.github.com/b5995d7f425b58b19c9600362defc3bd for a full test report.

**Comment by verdurin** [comment]
Going in, thanks @FokkeDijkstra!

**Pull request merged**
