### PR TITLE
fix wget dependency: use libidn2 rather than libidn

### LINKED ISSUE #12663: wget: Starting 1.19 libidn2 is required instead of libidn(1).
Current ECs are using libidn(1), however, the wget configure requires libidn2.
```
$ ./configure --help
...
  --with-libidn=DIR       Support IDN2008/IRIs (needs GNU libidn2 +
                          libunicode)
...
```
Also, wget installation log shows:
```
checking for library containing idn2_lookup_u8... no
configure: WARNING: *** LIBIDN2 was not found. You will not be able to use IDN2008 support
```

### PR DESCRIPTION
**Pull request by robert-mijakovic**
(created using `eb --new-pr`)

fixes #12663

### CODE REVIEW

**Comment by verdurin** [comment]
@boegelbot please test @ generoso

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 12 out of 12 (12 easyconfigs in total)
node2629.swalot.os - Linux centos linux 7.9.2009, x86_64, Intel(R) Xeon(R) CPU E5-2660 v3 @ 2.60GHz (haswell), Python 3.6.8
See https://gist.github.com/200f41e8d4bdbb2adda98fa7a71fb39e for a full test report.

**Review by boegel — APPROVED** [review]
lgtm

**Comment by boegel** [comment]
Tests on `generoso` failed due to old toolchains which don't work on CentOS 8, so I'll ignore those...

**Comment by boegel** [comment]
Going in, thanks @robert-mijakovic!

**Pull request merged**
