### PR TITLE
{cae}[foss/2022a] PALM v22.04.1

### PR DESCRIPTION
**Pull request by VRehnberg**
(created using `eb --new-pr`)
requires:
 - https://github.com/easybuilders/easybuild-easyblocks/pull/3020

### CODE REVIEW

**Comment by VRehnberg** [comment]
This should basically be working, but I made this a long time ago and am not planning to fix anything that doesn't work anytime soon.

However, figured that I'd make life easier for anyone else (or me) wanting to build PALM in the future.

**Comment by VRehnberg** [comment]
Oh, and this needs the `palm.py` easyblock, here based on STAR-CCM+:
```
##
# Copyright 2018-2019 Ghent University
#
# This file is part of EasyBuild,
# originally created by the HPC team of Ghent University (http://ugent.be/hpc/en),
# with support of Ghent University (http://ugent.be/hpc),
# the Flemish Supercomputer Centre (VSC) (https://www.vscentrum.be),
# Flemish Research Foundation (FWO) (http://www.fwo.be/en)
# and the Department of Economy, Science and Innovation (EWI) (http://www.ewi-vlaanderen.be/en).
#
# https://github.com/easybuilders/easybuild
#
# EasyBuild is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation v2.
#
# EasyBuild is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with EasyBuild.  If not, see <http://www.gnu.org/licenses/>.
##
"""
EasyBuild support for building and installing PALM, implemented as an easyblock

@author: Viktor Rehnberg (Chalmers University of Technology)
"""
import os
import tempfile

import easybuild.tools.environment as env
from easybuild.framework.easyblock import EasyBlock
from easybuild.tools.config import build_option
from easybuild.tools.filetools import find_glob_pattern
from easybuild.tools.run import run_cmd


class EB_PALM(EasyBlock):
    """Support for building/installing PALM."""

    def __init__(self, *args, **kwargs):
        """Initialise PALM easyblock."""
        super().__init__(*args, **kwargs)

    def configure_step(self):
        """No configuration procedure for PALM."""
        pass

    def build_step(self):
        """No build procedure for PALM."""
        pass

    def install_step(self):
        """Custom install procedure for PALM."""

        install_script_pattern = "install"
        if self.dry_run:
            install_script = install_script_pattern
        else:
            install_script = find_glob_pattern(install_script_pattern)

        cmd = ' '.join([
            self.cfg['preinstallopts'],
            "bash",
            install_script,
            "-p %s" % self.installdir,
            self.cfg['installopts'],
        ])
        run_cmd(cmd, log_all=True, simple=True)

    def sanity_check_step(self):
        """Custom sanity check for PALM."""
        custom_paths = {
            'files': [os.path.join(self.installdir, 'bin', 'palmrun')],
            'dirs': [],
        }
        super().sanity_check_step(custom_paths=custom_paths)

    def make_module_extra(self):
        """Extra statements specific to PALM to include in generated module file."""
        txt = super().make_module_extra()

        bin_dirs = [
            os.path.join(self.installdir, 'bin'),
        ]
        txt += self.module_generator.prepend_paths('PATH', bin_dirs)

        return txt
```

**Comment by migueldiascosta** [comment]
@VRehnberg can you open a PR for the easyblock in the easybuild-easyblocks repo?

**Comment by VRehnberg** [comment]
> @VRehnberg can you open a PR for the easyblock in the easybuild-easyblocks repo?

Done https://github.com/easybuilders/easybuild-easyblocks/pull/3020

**Comment by akesandgren** [comment]
Test report by @akesandgren
Using easyblocks from PR(s) https://github.com/easybuilders/easybuild-easyblocks/pull/3020
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
b-an02.hpc2n.umu.se - Linux Ubuntu 20.04, x86_64, Intel(R) Xeon(R) CPU E5-2690 v4 @ 2.60GHz, Python 3.8.10
See https://gist.github.com/akesandgren/f86aa2c0fb05adfe4d26e231f4ac8aa5 for a full test report.

**Comment by akesandgren** [comment]
Test report by @akesandgren
Using easyblocks from PR(s) https://github.com/easybuilders/easybuild-easyblocks/pull/3020
**SUCCESS**
Build succeeded for 0 out of 0 (1 easyconfigs in total)
b-an02.hpc2n.umu.se - Linux Ubuntu 20.04, x86_64, Intel(R) Xeon(R) CPU E5-2690 v4 @ 2.60GHz, Python 3.8.10
See https://gist.github.com/akesandgren/e34291d0b289107850daaf911efb17ec for a full test report.

**Comment by akesandgren** [comment]
Test report by @akesandgren
Using easyblocks from PR(s) https://github.com/easybuilders/easybuild-easyblocks/pull/3020
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
b-an02.hpc2n.umu.se - Linux Ubuntu 20.04, x86_64, Intel(R) Xeon(R) CPU E5-2690 v4 @ 2.60GHz, Python 3.8.10
See https://gist.github.com/akesandgren/f12876b20bbf90bb78dccdbe3d24fbfc for a full test report.

**Comment by boegel** [comment]
@VRehnberg Is there a particular reason why this is still a draft PR?

Looks good to go to me, since the easyblock PR https://github.com/easybuilders/easybuild-easyblocks/pull/3020 is already merged?

**Comment by VRehnberg** [comment]
> @VRehnberg Is there a particular reason why this is still a draft PR?
> 
> Looks good to go to me, since the easyblock PR [easybuilders/easybuild-easyblocks#3020](https://github.com/easybuilders/easybuild-easyblocks/pull/3020) is already merged?

The reason is that I forgot about it ^^'

**Comment by boegel** [comment]
@VRehnberg I propose we close this in favor of:
* #20684

That easyconfig doesn't use the custom easyblock for PALM that was introduced in https://github.com/easybuilders/easybuild-easyblocks/pull/3020, so we should remove it imho...

**Pull request closed without merging**
