### PR TITLE
{phys}[foss/2023a] CORSIKA v77550

### PR DESCRIPTION
**Pull request by lexming**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by lexming** [comment]
Test report by @lexming
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
node601.hydra.os - Linux Rocky Linux 8.9, x86_64, AMD EPYC 9384X 32-Core Processor (x86_64_v4), Python 3.6.8
See https://gist.github.com/lexming/52b4f55dbac03d0c70155900652432f8 for a full test report.

**Comment by smoors** [comment]
Test report by @smoors
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
node300.hydra.os - Linux Rocky Linux 8.10, x86_64, Intel(R) Xeon(R) Gold 6148 CPU @ 2.40GHz (skylake_avx512), Python 3.6.8
See https://gist.github.com/smoors/030ea58b1724156e67f32ee6658f3446 for a full test report.

**Review by lexming — COMMENTED** [review]
LGTM

**Review by smoors — APPROVED** [review]
lgtm too!

**Comment by smoors** [comment]
Going in, thanks @lexming!

**Pull request merged**
