### PR TITLE
{numlib}[GCC/13.2.0] OpenBLAS v0.3.24

### PR DESCRIPTION
**Pull request by boegel**
(created using `eb --new-pr`)
requires:
* #18879

### CODE REVIEW

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in total)
fair-mastodon-c7g-4xlarge-0001 - Linux Rocky Linux 8.7, AArch64, ARM UNKNOWN (neoverse_n1), Python 3.6.8
See https://gist.github.com/boegel/13dab3824c34735d649c55328bdc2244 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in total)
node3157.skitty.os - Linux RHEL 8.6, x86_64, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz (skylake_avx512), Python 3.6.8
See https://gist.github.com/boegel/82454b5222ece0b6abe32e57a2799a0c for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**FAILED**
Build succeeded for 1 out of 2 (2 easyconfigs in total)
easybuild2.novalocal - Linux CentOS Stream 8, POWER, IBM pSeries (emulated by qemu) (power9le), Python 3.6.8
See https://gist.github.com/boegel/2da6d00f54c85c6e3ca7691efda723e3 for a full test report.

**Comment by boegel** [comment]
@boegelbot please test @ generoso

**Comment by boegel** [comment]
There's a hard failing OpenBLAS test (not a numerical problem) on POWER9:

```
Testing DOUBLE PRECISION Nonsymmetric-Generalized-Eigenvalue-Problem-driver-EIG/xeigtstd < dgd.in > dgd.out  DDRGES: DGGES returned INFO=     9.
  DGS drivers:      1 out of   1555 tests failed to pass the threshold
 passed: 8922
failing to pass the threshold: 1
Info Error: 1
```

Looks like a segfault, very similar to https://github.com/OpenMathLib/OpenBLAS/issues/4032

Since we're only seeing this on POWER9, I don't consider this a blocker for this PR.

cc @Flamefire who may care more about this...

**Comment by boegel** [comment]
@boegelbot please test @ generoso

**Comment by boegel** [comment]
@boegelbot please test @ jsc-zen2

**Comment by SebastianAchilles** [comment]
Test report by @sebastianachilles
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in total)
bwd-rockylinux-92 - Linux Rocky Linux 9.2 (Blue Onyx), x86_64, Intel(R) Core(TM) i7-6900K CPU @ 3.20GHz (broadwell), 2 x NVIDIA NVIDIA GeForce GTX 1060 6GB, 535.104.05, Python 3.9.16
See https://gist.github.com/SebastianAchilles/2c8289b82740a95ba95a49a428066aba for a full test report.

**Review by SebastianAchilles — APPROVED** [review]
lgtm

**Comment by SebastianAchilles** [comment]
Going in, thanks @boegel!

**Pull request merged**
