### PR TITLE
{vis}[intel/2017a] plotly 4.7.1 w/ R 3.4.0

### PR DESCRIPTION
**Pull request by boegel**
(created using `eb --new-pr`)

requires #5007

### CODE REVIEW

**Comment by boegel** [comment]
This could have been included in the R easyconfig, but since it requires a more recent version of `htmlwidgets` (0.9 vs the 0.8 included in `R-3.4.0-intel-2017a-X11-20170314.eb`), I opted for installing it as a separate module for now (to stick to the policy of not bumping extension versions in existing easyconfigs).

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
node2498.golett.os - Linux centos linux 7.3.1611, Intel(R) Xeon(R) CPU E5-2680 v3 @ 2.50GHz, Python 2.7.5
See https://gist.github.com/6570e339dd285dc2384ba8bc9e7e486e for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
node2140.delcatty.os - Linux centos linux 7.3.1611, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.7.5
See https://gist.github.com/06eb431fa5bc85242391394d710badea for a full test report.

**Comment by verdurin** [comment]
Merging, thanks @boegel

**Pull request merged**
