### PR TITLE
Fix installation of packages in Python for GCCcore 8.2.0

### PR DESCRIPTION
**Pull request by Flamefire**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by Flamefire** [comment]
Test report by @Flamefire
**FAILED**
Build succeeded for 1 out of 2 (2 easyconfigs in total)
n1218 - Linux RHEL 8.7 (Ootpa), x86_64, Intel(R) Xeon(R) Platinum 8470 (icelake), Python 3.8.13
See https://gist.github.com/Flamefire/6f7b41bb7f6d755b8265f7be5247cbbe for a full test report.

**Comment by Flamefire** [comment]
Test report by @Flamefire
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in total)
n1530 - Linux RHEL 8.7 (Ootpa), x86_64, Intel(R) Xeon(R) Platinum 8470 (icelake), Python 3.8.13
See https://gist.github.com/Flamefire/ee9919f4cabf2bee26b3e19ac985f5cd for a full test report.

**Comment by boegel** [comment]
@Flamefire While this is a valuable fix, you're only touching easyconfigs here that are using a toolchain that is no longer supported, see our [toolchain support policy](https://docs.easybuild.io/policies/toolchains/#current-situation), so we'll close this PR (mainly because it interferes with efforts in the `5.0.x` branch, like moving all archived easyconfigs to a dedicated `easybuild-easyconfigs-archive` repo, see #20006)

**Comment by Flamefire** [comment]
Sure. I just think this is a regression we introduced some time ago when switching everything to pip and not being able to install those might at least interfere with large-scale tests (currently doing one for the unknown configure option change)

This change can easily be copied to the archived ECs in 5.0 and the conflict that might arise in merging this develop to 5.0 is trivial to resolve: Just accept the "deleted" part in 5.0

Just wanted to point this out. If this should still be left as-is I'm fine with that and will delete my branch for good

**Pull request closed without merging**
