### PR TITLE
{data}[GCCcore/10.3.0] DB_File v1.856

### PR DESCRIPTION
**Pull request by smoretti**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by lexming** [comment]
Test report by @lexming
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
node381.hydra.os - Linux centos linux 7.9.2009, x86_64, Intel(R) Xeon(R) Gold 6148 CPU @ 2.40GHz, Python 2.7.5
See https://gist.github.com/9296de2fd407a976a3dc22aaaa0fcc75 for a full test report.

**Review by lexming — APPROVED** [review]
LGTM

**Comment by lexming** [comment]
Going in, thanks @smoretti !

**Comment by boegel** [comment]
@boegelbot please test @ generoso

**Pull request merged**
