### PR TITLE
{tools}[fosscuda/2019b] JupyterLab v1.2.5 w/ Python 3.7.4

### PR DESCRIPTION
**Pull request by branfosj**
(created using `eb --new-pr`)

Requires:
* [x] #9750 `matplotlib-3.1.1-fosscuda-2019b-Python-3.7.4.eb`
* [x] #9751 `IPython-7.9.0-fosscuda-2019b-Python-3.7.4.eb`
* [x] #9746 `JupyterLab-1.2.5_set-app-path-for-easybuild.patch`

### CODE REVIEW

**Comment by branfosj** [comment]
Test report by @branfosj
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
bear-pg0305u11a.bear.cluster - Linux RHEL 7.6, 8335-GTX, Python 2.7.5
See https://gist.github.com/d88c5fa436ecc3553d3669e3a10dba8c for a full test report.

**Comment by branfosj** [comment]
Test report by @branfosj
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
bear-pg0210u18a.bear.cluster - Linux centos linux 7.7.1908, Intel(R) Xeon(R) CPU E5-2640 v4 @ 2.40GHz, Python 2.7.5
See https://gist.github.com/ae03c78b933583cbf0f7a3a2a27457d1 for a full test report.

**Comment by migueldiascosta** [comment]
Test report by @migueldiascosta
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
generoso - Linux centos linux 7.6.1810, Intel(R) Xeon(R) CPU E5-2660 v4 @ 2.00GHz, Python 3.6.8
See https://gist.github.com/65a058863a8d9a07878dd2cdffdb5c0c for a full test report.

**Comment by migueldiascosta** [comment]
Going in, thanks @branfosj!

**Pull request merged**
