### PR TITLE
update Arrow to use EB versions of some dependencies and enable all compression codecs

### PR DESCRIPTION
**Pull request by akesandgren**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by akesandgren** [comment]
Test report by @akesandgren
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in total)
b-an02.hpc2n.umu.se - Linux Ubuntu 20.04, x86_64, Intel(R) Xeon(R) CPU E5-2690 v4 @ 2.60GHz, Python 3.8.10
See https://gist.github.com/27805cb6f2ee63f79f2a4a6dc669674f for a full test report.

**Comment by akesandgren** [comment]
@boegelbot Please test @ generoso

**Comment by jfgrimm** [comment]
Test report by @jfgrimm
**SUCCESS**
Build succeeded for 4 out of 4 (2 easyconfigs in total)
node109.pri.viking.alces.network - Linux CentOS Linux 7.9.2009, x86_64, Intel(R) Xeon(R) Gold 6138 CPU @ 2.00GHz (skylake_avx512), Python 3.6.8
See https://gist.github.com/069ee91ece8b1abe91879d70c4ee59d5 for a full test report.

**Comment by jfgrimm** [comment]
@akesandgren we should probably do this for `Arrow-6.0.0-foss-2021a.eb` and `Arrow-6.0.1-foss-2021a.eb` as well?

**Comment by akesandgren** [comment]
Yes, we should, I'll add them in a while.

**Comment by akesandgren** [comment]
@boegelbot Please test @ generoso

**Comment by akesandgren** [comment]
Test report by @akesandgren
**SUCCESS**
Build succeeded for 7 out of 7 (5 easyconfigs in total)
b-an02.hpc2n.umu.se - Linux Ubuntu 20.04, x86_64, Intel(R) Xeon(R) CPU E5-2690 v4 @ 2.60GHz, Python 3.8.10
See https://gist.github.com/d5de7d12f25337c56eadbc6ae9485a86 for a full test report.

**Comment by casparvl** [comment]
Test report by @casparvl
**SUCCESS**
Build succeeded for 5 out of 5 (5 easyconfigs in total)
tcn1.local.snellius.surf.nl - Linux RHEL 8.4, x86_64, AMD EPYC 7H12 64-Core Processor, Python 3.6.8
See https://gist.github.com/6c3989328f518bff317d9725b0b6bb73 for a full test report.

**Comment by casparvl** [comment]
Test report by @casparvl
**SUCCESS**
Build succeeded for 6 out of 6 (5 easyconfigs in total)
software1.lisa.surfsara.nl - Linux debian 10.12, x86_64, Intel(R) Xeon(R) Silver 4110 CPU @ 2.10GHz, Python 2.7.16
See https://gist.github.com/6567ee092f3f2ab275e0748ce0504eef for a full test report.

**Review by casparvl — APPROVED** [review]
LGTM! Builds work, and a review-pr shows only expected changes.

**Comment by casparvl** [comment]
Going in, thanks @akesandgren!

**Pull request merged**
