### PR TITLE
{vis}[foss/2022b] OpenCV v4.8.0 w/ contrib

### PR DESCRIPTION
**Pull request by branfosj**
(created using `eb --new-pr`)

* [x] #18378
* [x] #18380

### CODE REVIEW

**Comment by branfosj** [comment]
Test report by @branfosj
**SUCCESS**
Build succeeded for 8 out of 8 (1 easyconfigs in total)
bear-pg0105u03a.bear.cluster - Linux RHEL 8.6, x86_64, Intel(R) Xeon(R) Platinum 8360Y CPU @ 2.40GHz (icelake), Python 3.6.8
See https://gist.github.com/branfosj/d271b9f8dfb127e7ffdf186a3beec38b for a full test report.

**Comment by branfosj** [comment]
@boegelbot please test @ generoso

**Comment by verdurin** [comment]
Test report by @verdurin
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
easybuild-c7.novalocal - Linux CentOS Linux 7.9.2009, x86_64, Intel Xeon Processor (Skylake, IBRS), Python 3.6.8
See https://gist.github.com/verdurin/79fe2e483c8886e0e531b04226645d96 for a full test report.

**Comment by verdurin** [comment]
@boegelbot please test @ jsc-zen2

**Comment by branfosj** [comment]
@boegelbot please test @ jsc-zen2
EB_ARGS='--optarch=""'

**Comment by verdurin** [comment]
Going in, thanks @branfosj!

**Pull request merged**
