### PR TITLE
{bio}[foss/2020a] HH-suite v3.3.0

### PR DESCRIPTION
**Pull request by dithwick**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by Mormacill** [comment]
Test report by @Mormacill
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
eb-testenv - Linux ubuntu 18.04, x86_64, Intel(R) Xeon(R) CPU           E5405  @ 2.00GHz, Python 3.6.9
See https://gist.github.com/552cc5f452a8e12510e20286bfba4ff9 for a full test report.

**Comment by verdurin** [comment]
Test report by @verdurin
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
nuc.lan - Linux Fedora 32, x86_64, Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz, Python 3.8.7
See https://gist.github.com/f372abdf8b267eb1d3ca0e1016c596dc for a full test report.

**Comment by verdurin** [comment]
@boegelbot please test @ generoso

**Review by migueldiascosta — APPROVED** [review]
lgtm

**Comment by migueldiascosta** [comment]
Going in, thanks @dithwick!

**Pull request merged**
