### PR TITLE
Remove redundant sanity check from jedi easyconfigs

### PR DESCRIPTION
**Pull request by Micket**
(created using `eb --new-pr`)

Also changed the description to align with #21650

### CODE REVIEW

**Comment by Micket** [comment]
@boegelbot please test @ generoso

**Comment by Micket** [comment]
Test report by @Micket
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in total)
vera-skylake-build - Linux Rocky Linux 8.9, x86_64, Intel Xeon Processor (Skylake, IBRS, no TSX), Python 3.6.8
See https://gist.github.com/Micket/c4c2cf82fd1e6c40a1e987e78c66da16 for a full test report.

**Comment by Micket** [comment]
@boegelbot please test @ jsc-zen3

**Review by jfgrimm — APPROVED** [review]
lgtm

**Pull request merged**
