### PR TITLE
{tools}[GCCcore/11.3.0] Z3 v4.10.2, Z3 v4.8.16, Z3 v4.8.12, ... w/ Python 3.10.4 + 3.9.6 + 3.9.5 + 3.8.6

### PR DESCRIPTION
**Pull request by lexming**
(created using `eb --new-pr`)

Same installations of Z3 as the existing Z3 easyconfigs plus Python bindings.
Updating unit tests to allow Z3 have a versionsuffix on Python.

### CODE REVIEW

**Comment by lexming** [comment]
@boegelbot: please test @ generoso

**Comment by branfosj** [comment]
@boegelbot please test @ jsc-zen2

**Comment by branfosj** [comment]
Test report by @branfosj
**SUCCESS**
Build succeeded for 5 out of 5 (5 easyconfigs in total)
bear-pg0104u25b.bear.cluster - Linux RHEL 8.6, x86_64, Intel(R) Xeon(R) Platinum 8360Y CPU @ 2.40GHz (icelake), Python 3.6.8
See https://gist.github.com/branfosj/452dafdf7d0714c35359cd3595ef34a9 for a full test report.

**Comment by verdurin** [comment]
Test report by @verdurin
**SUCCESS**
Build succeeded for 5 out of 5 (5 easyconfigs in total)
easybuild-c7.novalocal - Linux CentOS Linux 7.9.2009, x86_64, Intel Xeon Processor (Skylake, IBRS), Python 3.6.8
See https://gist.github.com/verdurin/8e53762da12c7657f4eaabba39899f28 for a full test report.

**Comment by verdurin** [comment]
@boegelbot please test @ jsc-zen2

**Comment by branfosj** [comment]
Going in, thanks @lexming!

**Pull request merged**
