### PR TITLE
{tools}[GCCcore/12.3.0] poetry v1.7.1

### PR DESCRIPTION
**Pull request by jfgrimm**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by verdurin** [comment]
@jfgrimm please appease the bot by fixing the permissions...

**Comment by jfgrimm** [comment]
@verdurin done

**Comment by jfgrimm** [comment]
Test report by @jfgrimm
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
himem02.viking2.yor.alces.network - Linux Rocky Linux 8.8, x86_64, AMD EPYC 7643 48-Core Processor, Python 3.6.8
See https://gist.github.com/jfgrimm/1b0bfa7eb984aadb382e985e2aeb03ca for a full test report.

**Comment by jfgrimm** [comment]
@boegelbot: please test @ jsc-zen3

**Comment by ocaisa** [comment]
@boegelbot please test @ generoso

**Comment by bedroge** [comment]
Test report by @bedroge
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
interactive1 - Linux Rocky Linux 8.9, x86_64, AMD EPYC-Milan Processor (zen2), Python 3.6.8
See https://gist.github.com/bedroge/e9591957932014c9d74c49904282f296 for a full test report.

**Comment by bedroge** [comment]
Going in, thanks @jfgrimm!

**Pull request merged**
