### PR TITLE
{vis}[intelcuda/2020b] scikit-image v0.18.1 w/ Python 3.8.6

### PR DESCRIPTION
**Pull request by zdemat**
Adding scikit-image for intelcuda-2020b and few related dependencies.

### CODE REVIEW

**Comment by zdemat** [comment]
ping on this issue. Is anything wrong? It got stuck.

**Comment by boegel** [comment]
failed with:
```
    icpc -shared -L/project/boegelbot/Rocky8/haswell/software/imkl/2020.4.304-iimpic-2020b/lib64 -L/project/boegelbot/Rocky8/haswell/software/imkl/2020.4.304-iimpic-2020b/lib -L/project/boegelbot/Rocky8/haswell/software/imkl/2020.4.304-iimpic-2020b/lib64 -L/project/boegelbot/Rocky8/haswell/software/imkl/2020.4.304-iimpic-2020b/lib -L/project/boegelbot/Rocky8/haswell/software/imkl/2020.4.304-iimpic-2020b/mkl/lib/intel64 -L/project/boegelbot/Rocky8/haswell/software/imkl/2020.4.304-iimpic-2020b/lib/intel64 -L/project/boegelbot/Rocky8/haswell/software/iccifort/2020.4.304/lib/intel64 -L/project/boegelbot/Rocky8/haswell/software/CUDAcore/11.1.1/lib64 -L/project/boegelbot/Rocky8/haswell/software/CUDAcore/11.1.1/lib -O2 -xHost -ftz -fp-speculation=safe -fp-model source -I/project/boegelbot/Rocky8/haswell/software/imkl/2020.4.304-iimpic-2020b/mkl/include build/temp.linux-x86_64-3.8/imread/_imread.o build/temp.linux-x86_64-3.8/imread/lib/formats.o build/temp.linux-x86_64-3.8/imread/lib/numpy.o build/temp.linux-x86_64-3.8/imread/lib/_bmp.o build/temp.linux-x86_64-3.8/imread/lib/_jpeg.o build/temp.linux-x86_64-3.8/imread/lib/_lsm.o build/temp.linux-x86_64-3.8/imread/lib/_png.o build/temp.linux-x86_64-3.8/imread/lib/_tiff.o -L/usr/local/lib -L/project/boegelbot/Rocky8/haswell/software/Python/3.8.6-GCCcore-10.2.0/lib -lpng -ljpeg -ltiff -o build/lib.linux-x86_64-3.8/imread/_imread.cpython-38-x86_64-linux-gnu.so
    ld: /project/boegelbot/Rocky8/haswell/software/LibTIFF/4.1.0-GCCcore-10.2.0/lib/libtiff.so:(*IND*+0x0): multiple definition of `_end'
    ld: /project/boegelbot/Rocky8/haswell/software/LibTIFF/4.1.0-GCCcore-10.2.0/lib/libtiff.so:(*IND*+0x0): multiple definition of `_edata'
    ld: /project/boegelbot/Rocky8/haswell/software/LibTIFF/4.1.0-GCCcore-10.2.0/lib/libtiff.so:(*IND*+0x0): multiple definition of `__bss_start'
    error: command 'icpc' failed with exit status 1
    Running setup.py install for imread: finished with status 'error'
```

Looks like the same problem as in #14219?

**Comment by zdemat** [comment]
Confirmed it is the same problem as discussed in #14219, i.e. related to updated `LibTIFF-4.1.0-GCCcore-10.2.0.eb`.

**Comment by zdemat** [comment]
Hi @boegel

I added a very simple patch fixing the build issue #14219 in `imread` with updated `LibTIFF`.

**Comment by zdemat** [comment]
Hi @boegel and @smoors 

thanks for the recent patch #15054 fixing issue with `jpeg` and `tiff` library dependency order in `imread` in `scikit-image`. Please note there is this `scikit-image` eb-config for intelcuda/2020b waiting for review and patched already some time ago. It is still open. The patch is actually same only the version is different.

Thanks.

**Comment by smoors** [comment]
@boegelbot: please test @ generoso

**Review by smoors — APPROVED** [review]
lgtm

**Comment by smoors** [comment]
Going in, thanks @zdemat!

**Pull request merged**
