### PR TITLE
{tools}[intel/2017a] cadaver v0.23.3

### PR DESCRIPTION
**Pull request by boegel**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
node2570.golett.os - Linux centos linux 7.3.1611, Intel(R) Xeon(R) CPU E5-2680 v3 @ 2.50GHz, Python 2.7.5
See https://gist.github.com/3d79482b5a261f2bb974387c35ebd772 for a full test report.

**Comment by verdurin** [comment]
Test report by @verdurin
**FAILED**
Build succeeded for 0 out of 8 (1 easyconfigs in this PR)
ca024.camp.thecrick.org - Linux centos linux 7.3.1611, Intel(R) Xeon(R) CPU E5-2640 v3 @ 2.60GHz, Python 2.7.5
See https://gist.github.com/7196efe14f592030fbe9e8a90eab3fb0 for a full test report.

**Comment by verdurin** [comment]
Test report by @verdurin
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
ca024.camp.thecrick.org - Linux centos linux 7.3.1611, Intel(R) Xeon(R) CPU E5-2640 v3 @ 2.60GHz, Python 2.7.5
See https://gist.github.com/ad77b63bc313a9ab762d4c0841232a2a for a full test report.

**Comment by verdurin** [comment]
Merged.

**Comment by boegel** [comment]
@verdurin Psst, this was still missing a SHA256 checksum (granted, not strictly required yet, but we should start aiming for it).

**Comment by boegel** [comment]
Also, missing milestone! ;)

**Comment by verdurin** [comment]
@boegel - yes, I was full of checksum zeal last night, after @vanzod picked that up on one of mine...

We should really add these informal expectations to tests as soon as possible.

**Pull request merged**
