### PR TITLE
Fix several typos in GlobalArrays 5.8 configure step

### LINKED ISSUE #19845: GlobalArrays configopts
Hi,

I noticed for https://github.com/easybuilders/easybuild-easyconfigs/blob/264fbbe263aeb5fc0eba8023dc7e7d4e25152450/easybuild/easyconfigs/g/GlobalArrays/GlobalArrays-5.8-intel-2021a.eb#L17-L18 and all following `.eb` files:

1. L17: `$MKLROOT` is written wrong.
2. L18: The dash `-` is missing in front of the `L/$MKLROOT`

Additionally, though I'm not sure if it just isn't mentioned in the README file of GlobalArray.

`--with-scalapack=ARG    Use external ScaLAPACK library.`

Is the only entry I found for `scalapack`, no `8` at the end of it, as can be seen in L18.

### PR DESCRIPTION
**Pull request by Micket**
fixes #19845

### CODE REVIEW

**Comment by Micket** [comment]
@boegelbot please test @ generoso

**Comment by Micket** [comment]
@boegelbot please test @ jsc-zen3

**Comment by casparvl** [comment]
Test report by @casparvl
**FAILED**
Build succeeded for 5 out of 8 (4 easyconfigs in total)
tcn1.local.snellius.surf.nl - Linux RHEL 8.6, x86_64, AMD EPYC 7H12 64-Core Processor, Python 3.6.8
See https://gist.github.com/casparvl/010e25e916984d0b1465b32493222b5e for a full test report.

**Comment by casparvl** [comment]
Ignore that, it's a checksum error in the intel toolchain... I'll fix it and retry.

**Comment by casparvl** [comment]
Test report by @casparvl
**SUCCESS**
Build succeeded for 4 out of 4 (4 easyconfigs in total)
tcn1.local.snellius.surf.nl - Linux RHEL 8.6, x86_64, AMD EPYC 7H12 64-Core Processor, Python 3.6.8
See https://gist.github.com/casparvl/c91759ce43971910ac442442df1ca1a5 for a full test report.

**Review by casparvl — APPROVED** [review]
Lgtm!

**Comment by casparvl** [comment]
Going in, thanks @Micket!

**Pull request merged**
