### PR TITLE
add patch for rhdf5filters extension in Bioconductor 3.12 bundle to fix installation on aarch64

### LINKED ISSUE #12817: rhdf5filters (R-bundle-Bioconductor-3.12-foss-2020b-R-4.0.3.eb) fails to install on aarch64
Installing extension rhdf5filters 1.2.0 (in R-bundle-Bioconductor-3.12-foss-2020b-R-4.0.3.eb) fails on aarch64 with the error:
```
configure: error: Need GCC to support X86 CPU features tests
```

Workaround is to use the following
```
    ('rhdf5filters', '1.2.0', {
        'checksums': ['58df019a2c8626cc236ebe19d44b830a6c3b5f787ea4090d5b57454a88d676cb'],
        'installopts': '--configure-args="ax_cv_gcc_check_x86_cpu_init=yes ax_cv_gcc_x86_cpu_supports_sse2=no"',
    }),
```
but this will not be wanted on x86_64. Instead some patching of the configure file should be used.

(From a report on slack - I did not see this issue when installing on POWER.)

### PR DESCRIPTION
**Pull request by boegel**
(created using `eb --new-pr`)
fixes #12817

### CODE REVIEW

**Review by Micket — APPROVED** [review]
lgtm

**Comment by Micket** [comment]
@boegelbot please test @ generoso

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
node2665.swalot.os - Linux centos linux 7.9.2009, x86_64, Intel(R) Xeon(R) CPU E5-2660 v3 @ 2.60GHz (haswell), Python 3.6.8
See https://gist.github.com/0ba81dc90adf5903b2e6647d01de8545 for a full test report.

**Comment by Micket** [comment]
Going in, thanks @boegel!

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
select-pika-c6gd-2xlarge-0001 - Linux centos linux 8.3.2011, AArch64, ARM UNKNOWN (graviton2), Python 3.6.8
See https://gist.github.com/fc80f7138c1ddd62ec8c482bb00442d7 for a full test report.

**Pull request merged**
