### PR TITLE
avoid use of hardcoded paths for Pillow by using `--disable-platform-guessing` option

### PR DESCRIPTION
**Pull request by laraPPr**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by laraPPr** [comment]
Test report by @laraPPr
**FAILED**
Build succeeded for 12 out of 13 (13 easyconfigs in total)
node3518.doduo.os - Linux RHEL 8.6, x86_64, AMD EPYC 7552 48-Core Processor, Python 3.6.8
See https://gist.github.com/laraPPr/b7ebdd7346c5b3417569339488e32bc0 for a full test report.

**Comment by laraPPr** [comment]
Test report by @laraPPr
**SUCCESS**
Build succeeded for 13 out of 13 (13 easyconfigs in total)
node3518.doduo.os - Linux RHEL 8.6, x86_64, AMD EPYC 7552 48-Core Processor, Python 3.6.8
See https://gist.github.com/laraPPr/83a559011ed96391939a0e2a91083ad8 for a full test report.

**Comment by laraPPr** [comment]
@boegelbot please test @ generoso

**Comment by laraPPr** [comment]
@boegelbot please test @ jsc-zen2

**Review by branfosj — APPROVED** [review]

**Comment by branfosj** [comment]
@boegelbot please test @ generoso

**Comment by branfosj** [comment]
Test report by @branfosj
**SUCCESS**
Build succeeded for 8 out of 8 (8 easyconfigs in total)
bear-pg0105u03a.bear.cluster - Linux RHEL 8.6, x86_64, Intel(R) Xeon(R) Platinum 8360Y CPU @ 2.40GHz (icelake), Python 3.6.8
See https://gist.github.com/branfosj/9580e2a996044fe6cb0f4d7e7add82b7 for a full test report.

**Comment by branfosj** [comment]
Going in, thanks @laraPPr!

**Pull request merged**
