### PR TITLE
{vis}[GCC/9.3.0] BioPP v2.4.1

### PR DESCRIPTION
**Pull request by mboisson**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by mboisson** [comment]
This replaces
https://github.com/easybuilders/easybuild-easyconfigs/tree/develop/easybuild/easyconfigs/b/bpp-core
https://github.com/easybuilders/easybuild-easyconfigs/tree/develop/easybuild/easyconfigs/b/bpp-phyl
https://github.com/easybuilders/easybuild-easyconfigs/tree/develop/easybuild/easyconfigs/b/bpp-seq

and more. My understanding is that this is all a suite, so I install all of the parts within a single bundle.

**Comment by smoors** [comment]
Test report by @smoors
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
node254.hydra.os - Linux centos linux 7.7.1908, x86_64, Intel(R) Xeon(R) CPU E5-2683 v4 @ 2.10GHz (broadwell), Python 2.7.5
See https://gist.github.com/fa40064066e5b0e7b55f6204c9cf9dc3 for a full test report.

**Comment by smoors** [comment]
@boegelbot please test @ generoso

**Comment by mboisson** [comment]
What should be done with the existing `bpp-core`, `bpp-phyl`, `bpp-seq` ?

**Comment by smoors** [comment]
Going in, thanks @mboisson!

**Comment by smoors** [comment]
> What should be done with the existing `bpp-core`, `bpp-phyl`, `bpp-seq` ?

since no other software depends on them, I think we should remove them?

**Comment by smoors** [comment]
@boegel ^

**Comment by boegel** [comment]
Different toolchain, so unless we add a bundle using `GCC-8.2.0-2.31` as a toolchain, we shouldn't remove those just yet.

**Comment by mboisson** [comment]
I can create a PR for that toolchain, but I can't test it as we don't have it installed. Let me know if you want me to do so. @boegel

**Comment by boegel** [comment]
@mboisson Cleaning that up makes sense to me, we can take care of the test report(s)

**Pull request merged**
