### PR TITLE
{numlib}[GCC/7.3.0-2.30] BLIS v0.3.2

### PR DESCRIPTION
**Pull request by bartoldeman**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by bartoldeman** [comment]
This is closely modelled to the OpenBLAS easyconfig, in that it allows OpenMP threading, auto-detects the CPU on the build host, and enables shared libraries.

BLIS is relevant esp as an open source solution on Skylake since OpenBLAS is still about 2-3 times slower than MKL on large matrix multiplications -- apparently BLIS is much closer.

It does not include LAPACK however, so that will need  a seperate easyconfig.

**Comment by pescobar** [comment]
Test report by @pescobar
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
worker01.cluster.bc2.ch - Linux centos linux 7.3.1611, Intel(R) Xeon(R) CPU E5-2630 v4 @ 2.20GHz, Python 2.7.5
See https://gist.github.com/1c524c431bfc2d73328c2aca7876868a for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 2 out of 2 (1 easyconfigs in this PR)
node2565.golett.os - Linux centos linux 7.4.1708, Intel(R) Xeon(R) CPU E5-2680 v3 @ 2.50GHz, Python 2.7.5
See https://gist.github.com/79a1ebbb008ec824023357d4fee1a3b6 for a full test report.

**Comment by boegel** [comment]
Going in, thanks @bartoldeman!

**Pull request merged**
