### PR TITLE
{tools}[GCCcore/13.2.0] JupyterLab v4.2.0, JupyterNotebook v7.2.0, jupyter-server v2.14.0, hatch-jupyter-builder v0.9.1

### PR DESCRIPTION
**Pull request by lexming**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by lexming** [comment]
@boegelbot: please test @ generoso

**Comment by lexming** [comment]
@boegelbot please test @ jsc-zen3

**Review by migueldiascosta — APPROVED** [review]
lgtm

**Comment by migueldiascosta** [comment]
Going in, thanks @lexming!

**Pull request merged**
