### PR TITLE
{tools}[system/system] ccache v4.2.1

### PR DESCRIPTION
**Pull request by Flamefire**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by Micket** [comment]
Test report by @Micket
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
vera-c1 - Linux centos linux 7.9.2009, x86_64, Intel Xeon Processor (Skylake), Python 2.7.5
See https://gist.github.com/e40d35952b1014b8e3512ec9a53911f9 for a full test report.

**Review by Micket — APPROVED** [review]
lgtm

**Comment by Micket** [comment]
Going in, thanks @Flamefire!

**Comment by boegel** [comment]
Hmm, this doesn't seem to work on RHEL8...

Let's see if I can reproduce the issue on `generoso` (CentOS 8).

**Comment by boegel** [comment]
@boegelbot please test @ generoso

**Comment by Flamefire** [comment]
@boegel Looks like a binutils issue with the gold linker: https://bugzilla.redhat.com/show_bug.cgi?id=1639969

Can you try to disable it in the EC?

**Pull request merged**
