### PR TITLE
{chem}[foss-2023a] CP2K 2023.1

### PR DESCRIPTION
**Pull request by hajgato**
for zen4

### CODE REVIEW

**Comment by smoors** [comment]
@boegelbot: please test @ generoso

**Comment by boegel** [comment]
Test install on `generoso` is taking it's sweet time, but it's still spinning (and making progress)

Current status:

```
boegelb+ 2691549  0.0  0.0 224868  3064 ?        S    Nov18   0:00  \_ /bin/bash -l /var/spool/slurmd/job12184/slurm_script
boegelb+ 2691591  0.0  0.5 562756 90552 ?        Sl   Nov18   3:22      \_ python3 -m easybuild.main --from-pr 19257 --debug --rebuild --robot --upload-test-report --download-timeout=1000
boegelb+ 2820832  0.4  0.0 227620  5104 ?        S    Nov18  17:35          \_ /bin/bash /tmp/boegelbot/CP2K/2023.1/foss-2023a/cp2k-2023.1/tools/regtesting/do_regtest -nobuild -config cp2k_regtest.cfg
boegelb+ 1133205  0.0  0.0 227620  3340 ?        S    10:33   0:00              \_ /bin/bash /tmp/boegelbot/CP2K/2023.1/foss-2023a/cp2k-2023.1/tools/regtesting/do_regtest -nobuild -config cp2k_regtest.cfg
boegelb+ 1134298  0.0  0.0 227620  2852 ?        S    10:34   0:00              |   \_ /bin/bash /tmp/boegelbot/CP2K/2023.1/foss-2023a/cp2k-2023.1/tools/regtesting/do_regtest -nobuild -config cp2k_regtest.cfg
boegelb+ 1134299  1.0  0.1 180968 19488 ?        Sl   10:34   0:00              |       \_ mpirun -n 4 /tmp/boegelbot/CP2K/2023.1/foss-2023a/cp2k-2023.1/exe/Linux-x86-64-foss/cp2k.psmp H2O_tddfpt-t-1.inp
boegelb+ 1134306 98.0  1.2 1273704 197828 ?      RLl  10:34   0:05              |           \_ /tmp/boegelbot/CP2K/2023.1/foss-2023a/cp2k-2023.1/exe/Linux-x86-64-foss/cp2k.psmp H2O_tddfpt-t-1.inp
boegelb+ 1134307 95.8  1.1 1142512 195356 ?      RLl  10:34   0:05              |           \_ /tmp/boegelbot/CP2K/2023.1/foss-2023a/cp2k-2023.1/exe/Linux-x86-64-foss/cp2k.psmp H2O_tddfpt-t-1.inp
boegelb+ 1134308 93.1  1.1 1142540 195828 ?      RLl  10:34   0:05              |           \_ /tmp/boegelbot/CP2K/2023.1/foss-2023a/cp2k-2023.1/exe/Linux-x86-64-foss/cp2k.psmp H2O_tddfpt-t-1.inp
boegelb+ 1134310 96.3  1.1 1273588 195528 ?      RLl  10:34   0:05              |           \_ /tmp/boegelbot/CP2K/2023.1/foss-2023a/cp2k-2023.1/exe/Linux-x86-64-foss/cp2k.psmp H2O_tddfpt-t-1.inp
```

**Comment by boegel** [comment]
Progress so far:
```
[boegelbot@cns2 ~]$ cat /tmp/boegelbot/CP2K/2023.1/foss-2023a/TEST-Linux-x86-64-foss-psmp-2023-11-18_11-05-57/timings.txt|wc -l
2700
```

Not sure how far it has progressed, but it has been running the test suite since 18 Nov'23 17:51, so ~2.5 days, that seems a bit excessive? 😅

**Comment by boegel** [comment]
@boegelbot please test @ jsc-zen2
CORE_CNT=16

**Comment by boegel** [comment]
I've canceled job 12184 on `generoso`, let's try this again with more cores...

**Comment by boegel** [comment]
@boegelbot please test @ generoso
CORE_CNT=16

**Comment by boegel** [comment]
@boegelbot please test @ generoso
CORE_CNT=16

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 6 out of 6 (6 easyconfigs in total)
node3144.skitty.os - Linux RHEL 8.8, x86_64, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz (skylake_avx512), Python 3.6.8
See https://gist.github.com/boegel/473aac190f289d40894d613b01efc3b8 for a full test report.

**Review by boegel — APPROVED** [review]
lgtm

**Comment by boegel** [comment]
Going in, thanks @hajgato!

**Comment by grvlbit** [comment]
@hajgato , @boegel  Did you test this on any Rocky 9 machine as well? I'm currently seeing problems during the testing step of the Libint-2.7.2-GCC-11.3.0-lmax-6-cp2k.eb dependency:

```
== processing EasyBuild easyconfig /software.9/software/EasyBuild/4.8.2/easybuild/easyconfigs/l/Libint/Libint-2.7.2-GCC-11.3.0-lmax-6-cp2k.eb
== building and installing Libint/2.7.2-GCC-11.3.0-lmax-6-cp2k...
== fetching files...
== creating build dir, resetting environment...
== unpacking...
== patching...
== preparing...
== ... (took 1 secs)
== configuring...
== configuring Libint compiler...
== generating Libint library...
== ... (took 31 mins 56 secs)
== building...
== ... (took 17 mins 22 secs)
== testing...
== ... (took 6 mins 45 secs)
== FAILED: Installation ended unsuccessfully (build directory: /tmp/Libint/2.7.2/GCC-11.3.0-lmax-6-cp2k): build failed (first 300 chars): cmd "make check" exited with exit code 2 and output:
```

*/tmp/eb-mzu94e1y/easybuild-Libint-2.7.2-20231201.081425.UjisS.log*
```
CMakeFiles/fortran_test-libint2.dir/fortran/test.cc.o -c /dev/shm/Libint/2.7.2/GCC-11.3.0-lmax-6-cp2k/libint-2.7.2/libint-2.7.2/fortran/test.cc
15: In file included from /usr/include/signal.h:328,
15:                  from /dev/shm/Libint/2.7.2/GCC-11.3.0-lmax-6-cp2k/libint-2.7.2/libint-2.7.2/fortran/../tests/unit/catch.hpp:8034,
15:                  from /dev/shm/Libint/2.7.2/GCC-11.3.0-lmax-6-cp2k/libint-2.7.2/libint-2.7.2/fortran/test.cc:23:
15: /dev/shm/Libint/2.7.2/GCC-11.3.0-lmax-6-cp2k/libint-2.7.2/libint-2.7.2/fortran/../tests/unit/catch.hpp:10822:58: error: call to non-constexpr function long int sysconf(i
nt)
15: 10822 |     static constexpr std::size_t sigStackSize = 32768 >= MINSIGSTKSZ ? 32768 : MINSIGSTKSZ;
15:       | ^~~~~~~~~~~
```

This should be [due to a change in `glibc (>= 2.34)`](https://sourceware.org/git?p=glibc.git;a=blob;f=NEWS;h=85e84fe53699fe9e392edffa993612ce08b2954a;hb=HEAD#l12):

```
 * Add _SC_MINSIGSTKSZ and _SC_SIGSTKSZ. When _SC_SIGSTKSZ_SOURCE or
 _GNU_SOURCE are defined, MINSIGSTKSZ and SIGSTKSZ are no longer
 constant on Linux. MINSIGSTKSZ is redefined to sysconf(_SC_MINSIGSTKSZ)
 and SIGSTKSZ is redefined to sysconf (_SC_SIGSTKSZ).
 ```
 
If this is the case, I case EasyBuild can't do much about this and the issue should be raised at Libint, correct?

**Comment by boegel** [comment]
@grvlbit We can't follow up on things in merged PRs, please open an issue for this

**Comment by boegel** [comment]
@grvlbit I've figured out a fix for that issue you mentioned, see:
* #20396

**Pull request merged**
