### PR TITLE
{tools}[GCCcore/8.2.0] DB v18.1.32

### PR DESCRIPTION
**Pull request by lexming**
(created using `eb --new-pr`)
Minor update of Berkeley DB to version 18.1.32

### CODE REVIEW

**Comment by Micket** [comment]
Could you supply a build report?

**Comment by vanzod** [comment]
Test report by @vanzod
**FAILED**
Build succeeded for 0 out of 1 (1 easyconfigs in this PR)
cermis - Linux debian 9.9, Intel(R) Xeon(R) CPU           X5670  @ 2.93GHz, Python 2.7.13
See https://gist.github.com/f18541b426b9a3d5ce97a5bfbf920c7c for a full test report.

**Comment by vanzod** [comment]
Test report by @vanzod
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
cermis - Linux debian 9.9, Intel(R) Xeon(R) CPU           X5670  @ 2.93GHz, Python 2.7.13
See https://gist.github.com/7a84bdd06ca622e4a561c65b5b6bae39 for a full test report.

**Comment by lexming** [comment]
@vanzod Sorry to have messed up your commit. I was trying to upload a test report.

**Comment by vanzod** [comment]
@lexming No problem. I fixed it again ;)

**Comment by vanzod** [comment]
Going in, thanks @lexming!

**Pull request merged**
