### PR TITLE
{system}[system/system] CUDA v12.3.0

### PR DESCRIPTION
**Pull request by Micket**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by Micket** [comment]
@boegelbot please test @ generoso

**Comment by Micket** [comment]
Test report by @Micket
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
vera-c1 - Linux Rocky Linux 8.8, x86_64, Intel Xeon Processor (Skylake), Python 3.6.8
See https://gist.github.com/Micket/a4bd4735a1362bb0343839cf8c4bc583 for a full test report.

**Comment by Micket** [comment]
@boegelbot please test @ jsc-zen2

**Review by bedroge — APPROVED** [review]
Lgtm

**Comment by bedroge** [comment]
Test report by @bedroge
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
interactive1 - Linux Rocky Linux 8.8, x86_64, AMD EPYC-Milan Processor (zen2), Python 3.6.8
See https://gist.github.com/bedroge/ad425dccb4cf51a28c1604f3334e940c for a full test report.

**Comment by bedroge** [comment]
Going in, thanks @Micket!

**Pull request merged**
