### PR TITLE
{lib}[GCCcore/13.2.0,gompi/2023b,iimpi/2023b] SPRNG v5.0, TestU01 v1.2.3

### PR DESCRIPTION
**Pull request by SimonPinches**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by Louwrensth** [comment]
@boegelbot please test @ jsc-zen3

**Comment by branfosj** [comment]
@boegelbot please test @ jsc-zen3

**Comment by smoors** [comment]
@boegelbot: please test @ generoso

**Review by smoors — APPROVED** [review]
lgtm

**Comment by smoors** [comment]
Going in, thanks @SimonPinches!

**Pull request merged**
