### PR TITLE
use system architecture template in DB_File

### PR DESCRIPTION
**Pull request by SebastianAchilles**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by SebastianAchilles** [comment]
Test report by @sebastianachilles
**SUCCESS**
Build succeeded for 4 out of 4 (4 easyconfigs in total)
jrc0870.jureca - Linux Rocky Linux 8.9, AArch64, ARM UNKNOWN (neoverse_n1), 2 x NVIDIA NVIDIA A100-PCIE-40GB, 535.154.05, Python 3.6.8
See https://gist.github.com/SebastianAchilles/99d95dc61ec522358cbe2dd578705c97 for a full test report.

**Review by Micket — APPROVED** [review]
lgtm

**Comment by Micket** [comment]
Test report by @Micket
**SUCCESS**
Build succeeded for 2 out of 2 (1 easyconfigs in total)
alvis-skylake-build - Linux Rocky Linux 8.9, x86_64, Intel Xeon Processor (Skylake, IBRS, no TSX), Python 3.6.8
See https://gist.github.com/Micket/8f2c9eccbb2e14b1afca0890badb0c2f for a full test report.

**Comment by Micket** [comment]
@boegelbot please test @ generoso
EB_ARGS="DB_File-1.859-GCCcore-12.3.0.eb"

**Comment by Micket** [comment]
Going in, thanks @SebastianAchilles!

**Pull request merged**
