### PR TITLE
{ai}[foss/2022a] PyTorch-bundle v1.13.1

### PR DESCRIPTION
**Pull request by VRehnberg**
(created using `eb --new-pr`)

### CODE REVIEW

**Review by Micket — APPROVED** [review]
lgtm

**Comment by Micket** [comment]
@boegelbot please test @ jsc-zen2

**Comment by Micket** [comment]
I thought jsc-zen2 had a GPU, seems like it doesn't. Not sure how PyTorch installation went through.
```
  File "/project/def-maintainers/boegelbot/Rocky8/zen2/software/PyTorch/1.13.1-foss-2022a-CUDA-11.7.0/lib/python3.10/site-packages/torch/cuda/__init__.py", line 229, in _lazy_init
    torch._C._cuda_init()
RuntimeError: Found no NVIDIA driver on your system. Please check that you have an NVIDIA GPU and installed a driver from http://www.nvidia.com/Download/index.aspx
```

**Comment by jose-d** [comment]
as I think we have good use for this PR, I'm building with `eb -r --from=19015 --upload-test-report`..

**Comment by jose-d** [comment]
Test report by @jose-d
**FAILED**
Build succeeded for 2 out of 4 (1 easyconfigs in total)
gpu1.phoebe.lan - Linux Rocky Linux 8.8 (Green Obsidian), x86_64, AMD EPYC 7543 32-Core Processor, 8 x NVIDIA NVIDIA A100-SXM4-80GB, 535.104.12, Python 3.11.2
See https://gist.github.com/jose-d/72fa8bdb32a2abd74c7e25ad19a9c122 for a full test report.

**Comment by Micket** [comment]
Test report by @Micket
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
alvis1-07 - Linux Rocky Linux 8.8, x86_64, Intel(R) Xeon(R) Gold 6244 CPU @ 3.60GHz, 2 x NVIDIA Tesla V100-SXM2-32GB, 535.104.05, Python 3.6.8
See https://gist.github.com/Micket/5a042b92bce8b7fe739111c77a9f10b7 for a full test report.

**Comment by Micket** [comment]
Test report by @Micket
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
alvis6-08 - Linux Rocky Linux 8.8, x86_64, Intel(R) Xeon(R) Gold 6338 CPU @ 2.00GHz, 4 x NVIDIA NVIDIA A40, 535.104.05, Python 3.6.8
See https://gist.github.com/Micket/ed098634c166a448502f126970e79256 for a full test report.

**Comment by Micket** [comment]
Going in, thanks @VRehnberg!

**Pull request merged**
