### PR TITLE
add patch for Rust 1.52.2 and 1.54.0 to fix build when using alternate sysroot

### PR DESCRIPTION
**Pull request by boegel**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by boegel** [comment]
@boegelbot please test @ generoso
CORE_CNT=16

**Review by lexming — COMMENTED** [review]
In our CentOS 7, `file -b /bin/bash` does not output anything about the interpreter:
```
ELF 64-bit LSB executable, x86-64, version 1 (SYSV), dynamically linked (uses shared libs), for GNU/Linux 2.6.32, BuildID[sha1]=94b20c7f7a0529512f63bae145b524890ceae5a5, stripped
```

Using `readelf -l /bin/bash` might be more reliable, it prints several things including a line of the form
```
[Requesting program interpreter: /lib64/ld-linux-x86-64.so.2]
```

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 3 out of 3 (3 easyconfigs in total)
node3122.skitty.os - Linux centos linux 7.9.2009, x86_64, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz (skylake_avx512), Python 3.6.8
See https://gist.github.com/7d3e9e3309202806864812f77a620126 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 3 out of 3 (3 easyconfigs in total)
fair-mastodon-c5a-16xlarge-0001 - Linux UNKNOWN UNKNOWN, x86_64, AMD EPYC 7R32 (zen2), Python 3.9.9
See https://gist.github.com/8eef313f8461305c1574977ee59ae470 for a full test report.

**Comment by boegel** [comment]
> In our CentOS 7, `file -b /bin/bash` does not output anything about the interpreter
> 
> Using `readelf -l /bin/bash` might be more reliable

@lexming Great feedback, thanks a lot! `readelf -l /bin/bash` seems more robust, indeed.

Also works fine on the different target architectures:

* `x86_64` (`python2`, CentOS 7):
```
>>> import re, subprocess
>>> readelf_out = subprocess.check_output(['readelf', '-l', '/bin/bash']).decode('ascii', 'ignore').strip()
>>> regex = re.compile('.*program interpreter: ([^\]]+)', re.M)
>>> res = regex.search(readelf_out)
>>> res.group(1)
u'/lib64/ld-linux-x86-64.so.2'
```
* `aarch64` (`python3`, CentOS 8):
```
>>> import re, subprocess
>>> readelf_out = subprocess.check_output(['readelf', '-l', '/bin/bash']).decode('ascii', 'ignore').strip()
>>> regex = re.compile('.*program interpreter: ([^\]]+)', re.M)
>>> res = regex.search(readelf_out)
>>> res.group(1)
'/lib/ld-linux-aarch64.so.1'
```
* `ppc64le` (`python3`, CentOS 8):
```
>>> import re, subprocess
>>> readelf_out = subprocess.check_output(['readelf', '-l', '/bin/bash']).decode('ascii', 'ignore').strip()
>>> regex = re.compile('.*program interpreter: ([^\]]+)', re.M)
>>> res = regex.search(readelf_out)
>>> res.group(1)
'/lib64/ld64.so.2'
```

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 3 out of 3 (3 easyconfigs in total)
fair-mastodon-c5a-16xlarge-0001 - Linux UNKNOWN UNKNOWN, x86_64, AMD EPYC 7R32 (zen2), Python 3.9.9
See https://gist.github.com/f29843c1cabd8cbdc6ace4c5365b6249 for a full test report.

**Review by lexming — APPROVED** [review]
LGTM

**Comment by lexming** [comment]
@boegelbot please test @ generoso
CORE_CNT=16

**Comment by boegel** [comment]
Test report by @boegel
Using easyblocks from PR(s) https://github.com/easybuilders/easybuild-easyblocks/pull/2248
**SUCCESS**
Build succeeded for 3 out of 3 (3 easyconfigs in total)
fair-mastodon-c6g-2xlarge-0001 - Linux UNKNOWN UNKNOWN, AArch64, ARM UNKNOWN (graviton2), Python 3.9.9
See https://gist.github.com/94ea134b5c7d14efdabf468b6813bf04 for a full test report.

**Comment by lexming** [comment]
Going in, thanks @boegel !

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 3 out of 3 (3 easyconfigs in total)
easybuild2.novalocal - Linux UNKNOWN UNKNOWN, POWER, IBM pSeries (emulated by qemu) (power9le), Python 3.9.9
See https://gist.github.com/5a5d5af8d4c0659c3067c5910cb7b924 for a full test report.

**Pull request merged**
