### PR TITLE
{lib,vis}[GCC/11.3.0,GCCcore/11.3.0] SDL2 v2.0.22, wxWidgets v3.2.1

### PR DESCRIPTION
**Pull request by maxim-masterov**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by smoors** [comment]
@boegelbot: please test @ generoso

**Comment by smoors** [comment]
@boegelbot please test @ jsc-zen2

**Review by smoors — APPROVED** [review]
lgtm

**Comment by mboisson** [comment]
@smoors, @maxim-masterov , I just stumbled onto this. The wxWidgets release page explicitly states: 

If you intend to build wxWidgets from sources (which is recommended), please do NOT download the files using the "Source code" links just above, which are automatically generated by GitHub and don't contain the submodules sources which are necessary for building wxWidgets.

*Instead, download one of [wxWidgets-3.2.1.zip](https://github.com/wxWidgets/wxWidgets/releases/download/v3.2.1/wxWidgets-3.2.1.zip) or [wxWidgets-3.2.1.7z](https://github.com/wxWidgets/wxWidgets/releases/download/v3.2.1/wxWidgets-3.2.1.7z), for much smaller size, for Microsoft Windows systems or [wxWidgets-3.2.1.tar.bz2](https://github.com/wxWidgets/wxWidgets/releases/download/v3.2.1/wxWidgets-3.2.1.tar.bz2) for Unix ones, including macOS.* These archives have exactly the same contents, but use the line endings appropriate for the corresponding platform.


Any reason why we are using a git checkout instead of downloading these complete tarballs ?

**Comment by smoors** [comment]
good point, I guess we just looked over it?

**Comment by maxim-masterov** [comment]
@mboisson no, no reason. I think I just overlooked it.
I've just successfully reinstalled wxWidgets using the "wxWidgets-3.2.1.tar.bz2" tarball. I will open a new PR with the fix a bit later.

**Comment by maxim-masterov** [comment]
@mboisson @smoors new PR is ready: #17167

**Pull request merged**
