### PR TITLE
remove extentions from R-bundle-Bioconductor 3.11 easyconfigs that are also included in R 4.0.0

### PR DESCRIPTION
**Pull request by branfosj**
All of these are in https://github.com/easybuilders/easybuild-easyconfigs/blob/develop/easybuild/easyconfigs/r/R/R-4.0.0-foss-2020a.eb so we can remove them from here.

* fs: https://github.com/easybuilders/easybuild-easyconfigs/blob/develop/easybuild/easyconfigs/r/R/R-4.0.0-foss-2020a.eb#L1485
* sys: https://github.com/easybuilders/easybuild-easyconfigs/blob/develop/easybuild/easyconfigs/r/R/R-4.0.0-foss-2020a.eb#L786
* askpass: https://github.com/easybuilders/easybuild-easyconfigs/blob/develop/easybuild/easyconfigs/r/R/R-4.0.0-foss-2020a.eb#L789
* clue: https://github.com/easybuilders/easybuild-easyconfigs/blob/develop/easybuild/easyconfigs/r/R/R-4.0.0-foss-2020a.eb#L2224
* ggplot2: https://github.com/easybuilders/easybuild-easyconfigs/blob/develop/easybuild/easyconfigs/r/R/R-4.0.0-foss-2020a.eb#L477

### CODE REVIEW

**Comment by branfosj** [comment]
Test report by @branfosj
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
bear-pg0211u03a.bear.cluster - Linux centos linux 7.8.2003, x86_64, Intel(R) Xeon(R) Gold 6248 CPU @ 2.50GHz (cascadelake), Python 3.6.8
See https://gist.github.com/21eaa37d2f83a3e19360e5bfdb4bb3ca for a full test report.

**Comment by verdurin** [comment]
@boegelbot please test @ generoso

**Comment by branfosj** [comment]
> Test report by @boegelbot
> **FAILED**
> Build succeeded for 0 out of 1 (1 easyconfigs in this PR)
> generoso-x-3 - Linux centos linux 8.2.2004, x86_64, Intel(R) Xeon(R) CPU E5-2667 v3 @ 3.20GHz (haswell), Python 3.6.8
> See https://gist.github.com/75e134b20a5c505589d048df610a865b for a full test report.

https://gist.github.com/boegelbot/b5050c4c3fbea8db49c8f301b86191a3 shows the issue to be

> ERROR: dependency JADE is not available for package 

JADE is in `R-4.0.0-foss-2020a.eb`: https://github.com/easybuilders/easybuild-easyconfigs/blob/develop/easybuild/easyconfigs/r/R/R-4.0.0-foss-2020a.eb

@boegelbot was also building tha R ec at the same time (https://github.com/easybuilders/easybuild-easyconfigs/pull/11428#issuecomment-703626237) which may have caused this issue.

**Comment by boegel** [comment]
@boegelbot please test @ generoso

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
node3404.kirlia.os - Linux centos linux 7.8.2003, x86_64, Intel(R) Xeon(R) Gold 6240 CPU @ 2.60GHz (cascadelake), Python 2.7.5
See https://gist.github.com/00f5d45e4177221d83a2f60467d1c5c3 for a full test report.

**Review by boegel — APPROVED** [review]
lgtm

**Comment by boegel** [comment]
Going in, thanks @branfosj!

**Pull request merged**
