### PR TITLE
{lang}[iomkl/2018b] Python 2.7.15, 3.7.0 (REVIEW)

### PR DESCRIPTION
**Pull request by hajgato**

### CODE REVIEW

**Comment by hajgato** [comment]
needs PR #6661

**Comment by hajgato** [comment]
Travis most probably fails because `iomkl/2018b` is not yet merged (so EB does not know what is the minimal tollchain) [ answer gotten via Slack by @akesandgren ]

**Comment by akesandgren** [comment]
Test report by @akesandgren
**FAILED**
Build succeeded for 0 out of 1 (2 easyconfigs in this PR)
janson.hpc2n.umu.se - Linux ubuntu 16.04, Intel(R) Core(TM) i7-5600U CPU @ 2.60GHz, Python 2.7.12
See https://gist.github.com/739d231121d1a33deafebc789f65018c for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in this PR)
node2594.golett.os - Linux centos linux 7.4.1708, Intel(R) Xeon(R) CPU E5-2680 v3 @ 2.50GHz, Python 2.7.5
See https://gist.github.com/17b48156cda1ee578fb66e25530c2e75 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in this PR)
node2003.delcatty.os - Linux centos linux 7.4.1708, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.7.5
See https://gist.github.com/df2589684f4b85ebd2ed0b4fa34f3ce4 for a full test report.

**Comment by boegel** [comment]
Going in, thanks @hajgato!

**Pull request merged**
