### PR TITLE
{lib,tools}[GCC/12.3.0] pyvips v2.2.3, libvips v8.15.2

### PR DESCRIPTION
**Pull request by lcniel**
(created using `eb --new-pr`)

(Requires #20853)

### CODE REVIEW

**Comment by lcniel** [comment]
Test report by @lcniel
**SUCCESS**
Build succeeded for 20 out of 20 (2 easyconfigs in total)
alvis10-11 - Linux Rocky Linux 8.9, x86_64, Intel(R) Xeon(R) Gold 6338 CPU @ 2.00GHz, Python 3.6.8
See https://gist.github.com/lcniel/5a97a39e3cf9a3522956b58b1eaa057f for a full test report.

**Comment by lcniel** [comment]
Test report by @lcniel
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in total)
vera14-4 - Linux Rocky Linux 8.9, x86_64, Intel(R) Xeon(R) Gold 6130 CPU @ 2.10GHz, Python 3.6.8
See https://gist.github.com/lcniel/b46f4388ff32bf49c5b79e816ec2b9e5 for a full test report.

**Comment by zao** [comment]
Test report by @zao
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in total)
eb-mix.zao.se - Linux Ubuntu 24.04 LTS (Noble Numbat), x86_64, AMD Ryzen 9 3900X 12-Core Processor (zen2), Python 3.12.3
See https://gist.github.com/zao/44af9e9e622de2b6271040e1358956b9 for a full test report.

**Review by Micket — APPROVED** [review]
lgtm

**Pull request merged**
