### PR TITLE
{math}[system/system] MATLAB v2020a, MATLAB v2020b, MATLAB v2021a

### PR DESCRIPTION
**Pull request by Micket**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by Micket** [comment]
I think we can use checksums now since we can use the iso files directly. Good if someone else with matlab could confirm.

**Comment by bedroge** [comment]
I've just used the one for MATLAB 2020b: I did get an error about `7z` not being found and had to install `p7zip-plugins` (`p7zip` was already installed on our node, but only provided `7za`, which doesn't seem to be capable of extracting iso files), but other than that it worked fine.

**Comment by bedroge** [comment]
Oh, and I don't know if this is expected, but it did somehow try to install it again after it completed (?):

```
eb ~/MATLAB-2020b.eb 
== Temporary log file in case of crash /dev/shm/user/easybuild-wx679s9b.log
== processing EasyBuild easyconfig /home/user/MATLAB-2020b.eb
== building and installing MATLAB/2020b...
== fetching files...
== creating build dir, resetting environment...
== unpacking...
== patching...
== preparing...
== configuring...
== Running pre-configure hook...
== building...
== testing...
== installing...
== taking care of extensions...
== restore after iterating...
== postprocessing...
== sanity checking...
== cleaning up...
== creating module...
== permissions...
== packaging...
== COMPLETED: Installation ended successfully (took 35 min 26 sec)
== Results of the build can be found in the log file(s) /software/software/MATLAB/2020b/easybuild/easybuild-MATLAB-2020b-20210408.114923.log
== Build succeeded for 1 out of 1
== Temporary log file(s) /dev/shm/user/easybuild-wx679s9b.log* have been removed.
== Temporary directory /dev/shm/user/eb-vibsxrv5 has been removed.
== Temporary log file in case of crash /dev/shm/user/easybuild-e2p5bea7.log
== MATLAB/2020b is already installed (module found), skipping
== No easyconfigs left to be built.
== Build succeeded for 0 out of 0
== Temporary log file(s) /dev/shm/user/easybuild-e2p5bea7.log* have been removed.
== Temporary directory /dev/shm/user/eb-1u_csf0x has been removed.
```

**Comment by Micket** [comment]
Test report by @Micket
**FAILED**
Build succeeded for 0 out of 1 (1 easyconfigs in total)
vera-c1 - Linux centos linux 7.9.2009, x86_64, Intel Xeon Processor (Skylake), Python 2.7.5
See https://gist.github.com/f6feab3e3bc5a0106bfb7bd8abc664ad for a full test report.

**Comment by Micket** [comment]
Test report by @Micket
**FAILED**
Build succeeded for 0 out of 1 (1 easyconfigs in total)
vera-c1 - Linux centos linux 7.9.2009, x86_64, Intel Xeon Processor (Skylake), Python 2.7.5
See https://gist.github.com/233389d0bde62d4027939ef050f06eda for a full test report.

**Comment by Micket** [comment]
Test report by @Micket
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
vera-c1 - Linux centos linux 7.9.2009, x86_64, Intel Xeon Processor (Skylake), Python 2.7.5
See https://gist.github.com/06e9203bee9e0e28e0b79fe2c4ebc441 for a full test report.

**Comment by Micket** [comment]
I think this is good to go now. I have successfully built the other versions as well (and I kind of don't want to rebuild this as it's so big).

**Comment by ocaisa** [comment]
@Micket Can we update the `README.md` to reflect the use of the iso's directly for latest versions?

**Comment by rungitta** [comment]
I can confirm that this worked for me and that p7zip-plugins had to be installed on our rhel8 host for it to work.

**Comment by Micket** [comment]
@ocaisa Can I do that in a separate PR? That readme contains other wrong information as well I think. I don't want to have to rebuild this PR again.

**Review by ocaisa — APPROVED** [review]

**Pull request merged**
