### PR TITLE
add elfutils as build dependency for Clang 8.0.x and 9.0.1 easyconfigs that have a CUDA dependency

### LINKED ISSUE #13006: Building Clang with gcccuda requires elfutils
When building `Clang/11.0.1-gcccuda-2020b` on our cluster it was never able to properly offload to our Nvidia GPUs, however, the compiler never failed to compile and OpenMP still worked, it was just not able to detect any GPUs on the system. After a bit of digging I found the following in the build log of `Clang`:

```bash
-- LIBOMPTARGET: Building offloading runtime library libomptarget.                        
-- LIBOMPTARGET: Not building aarch64 offloading plugin: machine not found in the system. 
-- LIBOMPTARGET: Not building CUDA offloading plugin: libelf dependency not found.        
-- LIBOMPTARGET: Not building PPC64 offloading plugin: machine not found in the system.   
-- LIBOMPTARGET: Not building PPC64le offloading plugin: machine not found in the system. 
-- LIBOMPTARGET: Not building nec-aurora plugin: libveo or libveosinfo not found.         
-- LIBOMPTARGET: Not building x86_64 offloading plugin: libelf dependency not found.      
-- LIBOMPTARGET: Building CUDA offloading device RTL.                                     
```

Which shows that it is build some part of the offloading support, but since `-- LIBOMPTARGET: Not building CUDA offloading plugin: libelf dependency not found.` I guess it was never able to properly generate the offload code.

Adding `elfutils/0.183` to the build dependencies of `Clang` solved the problem and a very simple offloading program, that did not work before adding `elfutils`, was able to detect and offload to the Nvidia GPU.

### PR DESCRIPTION
**Pull request by boegel**
(created using `eb --new-pr`)
cfr. #13008, fixes #13006

### CODE REVIEW

**Comment by boegel** [comment]
Test report by @boegel
Using easyblocks from PR(s) https://github.com/easybuilders/easybuild-easyblocks/pull/2454
**FAILED**
Build succeeded for 5 out of 9 (9 easyconfigs in total)
node2617.swalot.os - Linux centos linux 7.9.2009, x86_64, Intel(R) Xeon(R) CPU E5-2660 v3 @ 2.60GHz (haswell), Python 3.6.8
See https://gist.github.com/314bc7411503a7dafc4e2d4cf395063a for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
Using easyblocks from PR(s) https://github.com/easybuilders/easybuild-easyblocks/pull/2454
**FAILED**
Build succeeded for 7 out of 11 (9 easyconfigs in total)
node3505.doduo.os - Linux RHEL 8.2, x86_64, AMD EPYC 7552 48-Core Processor (zen2), Python 3.6.8
See https://gist.github.com/0fadbf5ded6eca2e76e85832acb213b4 for a full test report.

**Comment by boegel** [comment]
@boegelbot please test @ generoso
EB_ARGS="--include-easyblocks-from-pr 2454 --cuda-compute-capabilities 7.0"
CORE_CNT=16

**Comment by boegel** [comment]
Test report by @boegel
Using easyblocks from PR(s) https://github.com/easybuilders/easybuild-easyblocks/pull/2454
**SUCCESS**
Build succeeded for 9 out of 9 (9 easyconfigs in total)
node3505.doduo.os - Linux RHEL 8.2, x86_64, AMD EPYC 7552 48-Core Processor (zen2), Python 3.6.8
See https://gist.github.com/ea1730e1705dbe314de5ac26f917b3e7 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
Using easyblocks from PR(s) https://github.com/easybuilders/easybuild-easyblocks/pull/2454
**SUCCESS**
Build succeeded for 9 out of 9 (9 easyconfigs in total)
node2617.swalot.os - Linux centos linux 7.9.2009, x86_64, Intel(R) Xeon(R) CPU E5-2660 v3 @ 2.60GHz (haswell), Python 3.6.8
See https://gist.github.com/d355dc717830b01d7e8435d9e0048ff8 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
Using easyblocks from PR(s) https://github.com/easybuilders/easybuild-easyblocks/pull/2454
**FAILED**
Build succeeded for 5 out of 9 (9 easyconfigs in total)
node2617.swalot.os - Linux centos linux 7.9.2009, x86_64, Intel(R) Xeon(R) CPU E5-2660 v3 @ 2.60GHz (haswell), Python 3.6.8
See https://gist.github.com/73e5304d933359bba18c3de5590442a4 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
Using easyblocks from PR(s) https://github.com/easybuilders/easybuild-easyblocks/pull/2454
**SUCCESS**
Build succeeded for 9 out of 9 (9 easyconfigs in total)
node2617.swalot.os - Linux centos linux 7.9.2009, x86_64, Intel(R) Xeon(R) CPU E5-2660 v3 @ 2.60GHz (haswell), Python 3.6.8
See https://gist.github.com/abd9965ea084c94e2b88d34291c6cfbc for a full test report.

**Review by lexming — COMMENTED** [review]
@boegel Reviewing this PR I realised that our builds of elfutils are rather bloated with `libmicrohttpd`, `SQLite` and `cURL`. What do you think about #13034 ?

**Comment by boegel** [comment]
@boegelbot please test @ generoso
EB_ARGS="--cuda-compute-capabilities 7.0"
CORE_CNT=16

**Comment by boegel** [comment]
> @boegel Reviewing this PR I realised that our builds of elfutils are rather bloated with `libmicrohttpd`, `SQLite` and `cURL`. What do you think about #13034 ?

@lexming #13034 merged, updated this one accordingly...

**Comment by lexming** [comment]
Test report by @lexming
**FAILED**
Build succeeded for 7 out of 11 (9 easyconfigs in total)
node302.hydra.os - Linux centos linux 7.9.2009, x86_64, Intel(R) Xeon(R) Gold 6148 CPU @ 2.40GHz, Python 2.7.5
See https://gist.github.com/928a128a2354820ad4ecfe629e55fba5 for a full test report.

**Review by verdurin — APPROVED** [review]
Looks fine.

**Comment by verdurin** [comment]
Going in, thanks @boegel!

**Comment by lexming** [comment]
Test report by @lexming
**SUCCESS**
Build succeeded for 11 out of 11 (9 easyconfigs in total)
node226.hydra.os - Linux centos linux 7.9.2009, x86_64, Intel(R) Xeon(R) CPU E5-2680 v4 @ 2.40GHz, Python 2.7.5
See https://gist.github.com/fc0d71a6a3cd28fd3e38a5e37f908b3e for a full test report.

**Pull request merged**
