### PR TITLE
{compiler}[GCCcore/10.2.0] AOCC v2.3.0

### PR DESCRIPTION
**Pull request by robert-mijakovic**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by migueldiascosta** [comment]
@boegelbot please test @ generoso

**Comment by migueldiascosta** [comment]
@boegelbot please test @ generoso EB_ARGS="--accept-eula=AOCC"

**Review by migueldiascosta — APPROVED** [review]
lgtm

**Comment by migueldiascosta** [comment]
@robert-mijakovic note, if you are not already aware, that both this and the existing AOCC-2.3.0-GCCcore-9.3.0.eb will by default use the system's GCC (see e.g. `clang -v`)

In order to actually use GCCcore one needs to pass `--gcc-toolchain=$EBROOTGCCCORE` to `clang`, `flang`, etc.

@boegel the easyblock should create compiler wrappers to add the `--gcc-toolchain` option?

**Comment by boegel** [comment]
@migueldiascosta Yes, that sounds like a good idea to me, please open an issue on that in the easyblocks repo.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
node3507.doduo.os - Linux RHEL 8.2, x86_64, AMD EPYC 7552 48-Core Processor (zen2), Python 3.6.8
See https://gist.github.com/8a95b2224c2f575699ead7730d9ad27b for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
node3131.skitty.os - Linux centos linux 7.9.2009, x86_64, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz, Python 3.6.8
See https://gist.github.com/509230ae66f38f1792d1cdf620fd1f66 for a full test report.

**Comment by boegel** [comment]
Going in, thanks @robert-mijakovic!

**Pull request merged**
