### PR TITLE
{bio}[intel/2018b] bcgTree v1.1.0, RAxML v8.2.12, Gblocks 0.91b

### PR DESCRIPTION
**Pull request by boegel**
(created using `eb --new-pr`)
requires ~~#7262~~ (HMMER)

### CODE REVIEW

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 3 out of 3 (3 easyconfigs in this PR)
node3102.skitty.os - Linux centos linux 7.5.1804, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz, Python 2.7.5
See https://gist.github.com/846faee560acff46c8a5635fcb63adde for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 3 out of 3 (3 easyconfigs in this PR)
node2668.swalot.os - Linux centos linux 7.5.1804, Intel(R) Xeon(R) CPU E5-2660 v3 @ 2.60GHz, Python 2.7.5
See https://gist.github.com/b59c0d38b50bb7758d1193e20ac60a27 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 3 out of 3 (3 easyconfigs in this PR)
node2107.delcatty.os - Linux centos linux 7.5.1804, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.7.5
See https://gist.github.com/5b5ecd4957b0e2b6faf5fe4621a5414c for a full test report.

**Comment by casparvl** [comment]
Test report by @casparvl
**FAILED**
Build succeeded for 0 out of 2 (1 easyconfigs in total)
tcn900.bullx - Linux RHEL 7.8, x86_64, Intel(R) Xeon(R) CPU E5-2690 v3 @ 2.60GHz, Python 2.7.5
See https://gist.github.com/5add34a4d895d5571bd9d1ab79abbf7d for a full test report.

**Comment by casparvl** [comment]
Test report by @casparvl
**FAILED**
Build succeeded for 0 out of 2 (1 easyconfigs in total)
tcn900.bullx - Linux RHEL 7.8, x86_64, Intel(R) Xeon(R) CPU E5-2690 v3 @ 2.60GHz, Python 2.7.5
See https://gist.github.com/70faf85ca5fe208c86c46924dc541b0d for a full test report.

**Comment by casparvl** [comment]
Test report by @casparvl
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
tcn900.bullx - Linux RHEL 7.8, x86_64, Intel(R) Xeon(R) CPU E5-2690 v3 @ 2.60GHz, Python 2.7.5
See https://gist.github.com/e467403a8b8fa6cfc1f65d9cb26102c5 for a full test report.

**Comment by casparvl** [comment]
Test report by @casparvl
**SUCCESS**
Build succeeded for 0 out of 0 (1 easyconfigs in total)
tcn900.bullx - Linux RHEL 7.8, x86_64, Intel(R) Xeon(R) CPU E5-2690 v3 @ 2.60GHz, Python 2.7.5
See https://gist.github.com/812b6d143cbc5405a7a605a9c30cd10c for a full test report.

**Comment by casparvl** [comment]
Test report by @casparvl
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
tcn900.bullx - Linux RHEL 7.8, x86_64, Intel(R) Xeon(R) CPU E5-2690 v3 @ 2.60GHz, Python 2.7.5
See https://gist.github.com/24f0fb9bc7f300180054c09e0f1fff07 for a full test report.

**Review by casparvl — APPROVED** [review]
LGTM

**Comment by casparvl** [comment]
Going in, thanks @boegel

**Comment by casparvl** [comment]
Going in, thanks @boegel!

**Comment by casparvl** [comment]
Going in, thanks @boegel!

**Comment by casparvl** [comment]
Going in, thanks @boegel!

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 3 out of 3 (3 easyconfigs in total)
node3409.kirlia.os - Linux centos linux 7.9.2009, x86_64, Intel(R) Xeon(R) Gold 6240 CPU @ 2.60GHz (cascadelake), Python 3.6.8
See https://gist.github.com/6f7bd7031d67dfa6811372a4c85e787b for a full test report.

**Pull request merged**
