### PR TITLE
{chem}[foss/2018b,fosscuda/2018b,intel/2018b] Amber v16.15 AmberTools v17.10

### PR DESCRIPTION
**Pull request by akesandgren**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by akesandgren** [comment]
Test report by @akesandgren
**SUCCESS**
Build succeeded for 5 out of 5 (5 easyconfigs in this PR)
b-an03.hpc2n.umu.se - Linux ubuntu 16.04, Intel(R) Xeon(R) CPU E5-2690 v4 @ 2.60GHz, Python 2.7.12
See https://gist.github.com/c9074d28493d1567df7da4202d1b3714 for a full test report.

**Comment by migueldiascosta** [comment]
Test report by @migueldiascosta
**FAILED**
Build succeeded for 5 out of 7 (5 easyconfigs in this PR)
grc-cluster1 - Linux centos 6.10, Intel(R) Xeon(R) CPU E5-2640 0 @ 2.50GHz, Python 2.7.14
See https://gist.github.com/1470df23c9e45079fcbbd6bca6b0a2a2 for a full test report.

**Comment by migueldiascosta** [comment]
@akesandgren ignore one of the failed easyconfigs failed again in the `update_amber`, that must be a network issue, but the `fosscuda` one shows a real issue, that also happens with `foss` when `update_amber` doesn't fail:

```
mpicxx -o cpptraj ActionFrameCounter.o ActionList.o Action_Align.o Action_Angle.o Action_AreaPerMol.o Action_AtomMap.o Action_AtomicCorr.o Action_AtomicFluct.o Action_AutoImage.o Action_Average.o Action_Bounds.o Action_Box.o Action_Center.o Action_Channel.o Action_CheckChirality.o Action_CheckStructure.o Action_Closest.o Action_ClusterDihedral.o Action_Contacts.o Action_CreateCrd.o Action_CreateReservoir.o Action_DNAionTracker.o Action_DSSP.o Action_Density.o Action_Diffusion.o Action_Dihedral.o Action_Dipole.o Action_Distance.o Action_DistRmsd.o Action_Energy.o Action_FilterByData.o Action_FixAtomOrder.o Action_GIST.o Action_Grid.o Action_GridFreeEnergy.o Action_Hbond.o Action_Image.o Action_Jcoupling.o Action_LESsplit.o Action_LIE.o Action_MakeStructure.o Action_Mask.o Action_Matrix.o Action_MinImage.o Action_Molsurf.o Action_MultiDihedral.o Action_MultiVector.o Action_NAstruct.o Action_NativeContacts.o Action_NMRrst.o Action_OrderParameter.o Action_Outtraj.o Action_PairDist.o Action_Pairwise.o Action_Principal.o Action_Projection.o Action_Pucker.o Action_Radgyr.o Action_Radial.o Action_RandomizeIons.o Action_Remap.o Action_ReplicateCell.o Action_Rmsd.o Action_Rotate.o Action_RunningAvg.o Action_STFC_Diffusion.o Action_Scale.o Action_SetVelocity.o Action_Spam.o Action_Strip.o Action_Surf.o Action_SymmetricRmsd.o Action_Temperature.o Action_Translate.o Action_Unstrip.o Action_Unwrap.o Action_Vector.o Action_VelocityAutoCorr.o Action_Volmap.o Action_Volume.o Action_Watershell.o AnalysisList.o Analysis_AmdBias.o Analysis_AutoCorr.o Analysis_Average.o Analysis_Clustering.o Analysis_Corr.o Analysis_CrankShaft.o Analysis_CrdFluct.o Analysis_CrossCorr.o Analysis_CurveFit.o Analysis_Divergence.o Analysis_FFT.o Analysis_Hist.o Analysis_Integrate.o Analysis_IRED.o Analysis_KDE.o Analysis_Lifetime.o Analysis_LowestCurve.o Analysis_Matrix.o Analysis_MeltCurve.o Analysis_Modes.o Analysis_Multicurve.o Analysis_MultiHist.o Analysis_Overlap.o Analysis_PhiPsi.o Analysis_Regression.o Analysis_RemLog.o Analysis_Rms2d.o Analysis_RmsAvgCorr.o Analysis_Rotdif.o Analysis_RunningAvg.o Analysis_Spline.o Analysis_State.o Analysis_Statistics.o Analysis_TI.o Analysis_Timecorr.o Analysis_VectorMath.o Analysis_Wavelet.o ArgList.o Array1D.o AssociatedData.o Atom.o AtomMap.o AtomMask.o AxisType.o BondSearch.o Box.o BufferedFrame.o BufferedLine.o ByteRoutines.o CharMask.o CIFfile.o ClusterDist.o ClusterList.o ClusterMap.o ClusterMatrix.o ClusterNode.o ClusterSieve.o Cluster_DBSCAN.o Cluster_DPeaks.o Cluster_HierAgglo.o Cluster_Kmeans.o Cluster_ReadInfo.o Cmd.o CmdInput.o CmdList.o ComplexArray.o CoordinateInfo.o Corr.o CpptrajFile.o CpptrajState.o CpptrajStdio.o CurveFit.o DataFile.o DataFileList.o DataIO.o DataIO_CCP4.o DataIO_Cmatrix.o DataIO_Evecs.o DataIO_Gnuplot.o DataIO_Grace.o DataIO_OpenDx.o DataIO_Mdout.o DataIO_NC_Cmatrix.o DataIO_RemLog.o DataIO_Std.o DataIO_VecTraj.o DataIO_Xplor.o DataIO_XVG.o DataSet.o DataSetList.o DataSet_1D.o DataSet_3D.o DataSet_Cmatrix.o DataSet_Cmatrix_DISK.o DataSet_Cmatrix_MEM.o DataSet_Cmatrix_NOMEM.o DataSet_Coords.o DataSet_Coords_CRD.o DataSet_Coords_REF.o DataSet_Coords_TRJ.o DataSet_GridDbl.o DataSet_GridFlt.o DataSet_Mat3x3.o DataSet_MatrixDbl.o DataSet_MatrixFlt.o DataSet_Mesh.o DataSet_Modes.o DataSet_RemLog.o DataSet_Topology.o DataSet_Vector.o DataSet_double.o DataSet_float.o DataSet_integer.o DataSet_string.o Deprecated.o DihedralSearch.o DispatchObject.o DistRoutines.o Energy.o EnsembleIn.o EnsembleIn_Multi.o EnsembleIn_Single.o EnsembleNavigator.o EnsembleOut.o EnsembleOut_Multi.o EnsembleOut_Single.o EnsembleOutList.o Ewald.o Exec_Analyze.o Exec_Calc.o Exec_ClusterMap.o Exec_CombineCoords.o Exec_Commands.o Exec_CompareTop.o Exec_CrdAction.o Exec_CrdOut.o Exec_DataFile.o Exec_DataFilter.o Exec_DataSetCmd.o Exec_GenerateAmberRst.o Exec_Help.o Exec_LoadCrd.o Exec_LoadTraj.o Exec_ParmBox.o Exec_ParmSolvent.o Exec_ParmStrip.o Exec_ParmWrite.o Exec_PermuteDihedrals.o Exec_Precision.o Exec_PrintData.o Exec_ReadData.o Exec_ReadInput.o Exec_RotateDihedral.o Exec_RunAnalysis.o Exec_ScaleDihedralK.o Exec_SequenceAlign.o Exec_System.o Exec_Top.o Exec_Traj.o Exec_ViewRst.o FileIO_Bzip2.o FileIO_Gzip.o FileIO_Mpi.o FileIO_Std.o FileName.o FileTypes.o Frame.o GridAction.o HistBin.o Hungarian.o ImageRoutines.o InputTrajCommon.o KDE.o MapAtom.o MaskToken.o Matrix_3x3.o MetaData.o Mol2File.o NameType.o NC_Cmatrix.o NC_Routines.o NetcdfFile.o OutputTrajCommon.o PDBfile.o PairList.o Parallel.o ParallelNetcdf.o ParmFile.o Parm_Amber.o Parm_CharmmPsf.o Parm_CIF.o Parm_Gromacs.o Parm_Mol2.o Parm_PDB.o Parm_SDF.o Parm_Tinker.o ProgressBar.o ProgressTimer.o PubFFT.o Random.o Range.o RPNcalc.o ReferenceAction.o Residue.o SDFfile.o SimplexMin.o Spline.o StringRoutines.o StructureMapper.o SymmetricRmsdCalc.o TextFormat.o Timer.o TinkerFile.o TopInfo.o Topology.o TorsionRoutines.o Traj_AmberCoord.o Traj_AmberNetcdf.o Traj_AmberRestart.o Traj_AmberRestartNC.o Traj_Binpos.o Traj_CharmmCor.o Traj_CharmmDcd.o Traj_CIF.o Traj_Conflib.o Traj_GmxTrX.o Traj_GmxXtc.o Traj_Gro.o Traj_Mol2File.o Traj_NcEnsemble.o Traj_PDBfile.o Traj_SDF.o Traj_SQM.o Traj_Tinker.o TrajectoryFile.o TrajectoryIO.o TrajFrameCounter.o TrajinList.o Trajin_Multi.o Trajin_Single.o TrajIOarray.o Trajout_Single.o TrajoutList.o Vec3.o ViewRst.o Action_Esander.o Command.o Cpptraj.o Energy_Sander.o ReadLine.o main.o molsurf.o readline/libreadline.a  pub_fft.o -L/opt/apps/util/easybuild/software/Amber/16-fosscuda-2018b-AmberTools-17-patchlevel-10-15/lib -larpack -L/opt/apps/util/easybuild/software/Amber/16-fosscuda-2018b-AmberTools-17-patchlevel-10-15/lib -llapack -L/opt/apps/util/easybuild/software/Amber/16-fosscuda-2018b-AmberTools-17-patchlevel-10-15/lib -lblas   -lgfortran  -w -L/opt/apps/util/easybuild/software/Amber/16-fosscuda-2018b-AmberTools-17-patchlevel-10-15/lib -lsander -L/opt/apps/util/easybuild/software/netCDF/4.6.1-fosscuda-2018b/lib -lnetcdf  -lbz2 -lz xdrfile/libxdrfile.a 
FileIO_Gzip.o:FileIO_Gzip.cpp:function FileIO_Gzip::Seek(long): error: undefined reference to 'gzseek64'
FileIO_Gzip.o:FileIO_Gzip.cpp:function FileIO_Gzip::Open(char const*, char const*): error: undefined reference to 'gzopen64'
FileIO_Gzip.o:FileIO_Gzip.cpp:function FileIO_Gzip::Tell(): error: undefined reference to 'gztell64'
```
it looks like the `cpptraj` configure/Makefile needs to be patched in order to include `-L${EBROOTZLIB}/lib` and `-L${EBROOTBZIP2}/lib`, to make sure the correct versions are picked up, although I'm not sure why this issue doesn't show up in the `intel` toolchains...

**Comment by akesandgren** [comment]
I'll take a look at it.

**Comment by akesandgren** [comment]
Strange, in my case it does pick up the correct zlib and bzip2, as evident from the ldd output of cpptraj
And during this build there is no system zlib/bzip2 dev package installed, as there where the previous time i built it.

So now I've test both with and without system installed zlib/bzip2 dev package installed.
Doesn't see any problems in either case.

Which libz/bzip2 is it picking up in your case?

**Comment by migueldiascosta** [comment]
@akesandgren it was picking up zlib 1.2.3-29 and bzip2 1.0.5-7 from the system (I shouldn't be using CentOS 6, I know... :) )

without the devel packages installed it seems to be ok, test report will eventually show up here (and let's hope `update_amber` doesn't fail again)

(but in any case, explicitly adding the `-L$EBROOT...` flags would make it more robust, no?)

**Comment by akesandgren** [comment]
It probably would be more robust. But why is it failing to do the right thing here??? There aren't any /usr/lib /usr/include thingies in your CPATH/LD_LIBRARY_PATH are there?

**Comment by migueldiascosta** [comment]
Test report by @migueldiascosta
**SUCCESS**
Build succeeded for 5 out of 5 (5 easyconfigs in this PR)
grc-cluster1 - Linux centos 6.10, Intel(R) Xeon(R) CPU E5-2640 0 @ 2.50GHz, Python 2.7.14
See https://gist.github.com/112b3c94a1959cc2d27c73c477f00ec9 for a full test report.

**Comment by migueldiascosta** [comment]
@akesandgren no, it doesn't seem to come from the environment. I suppose they could have been picked up via the ldconfig cache? 

What I find stranger is there was no issue when using the `intel` toolchain, even when the underlying `GCCcore` and `binutils` were the same versions

This also happens in another CentOS 6 system where I don't have root access, which is precisely the one with GPUs where I could test the cuda version

**Comment by akesandgren** [comment]
@migueldiascosta @boegel 
Anything else I should do on this one, or could it get merged?

**Comment by boegel** [comment]
Wouldn't it be better to sort out why the system deps were being picked up?

**Comment by akesandgren** [comment]
@migueldiascosta Please try again now.

**Comment by akesandgren** [comment]
Hmmm, too very empty (null) travis reports. What happened?

**Comment by boegel** [comment]
(close/re-open to re-trigger Travis)

**Comment by akesandgren** [comment]
Should we drop this or not?? Would probably be good to get it in for anyone stuck at Amber 16

**Comment by migueldiascosta** [comment]
@akesandgren sorry, my bad, will try again

**Comment by akesandgren** [comment]
This one might lack some of the fixes that are now in the Amber 18 PR. I probvably need to go over that and update this one...

**Comment by akesandgren** [comment]
Didn't find anything else missing at the moment.

Please try to build again.

**Comment by migueldiascosta** [comment]
Test report by @migueldiascosta
**SUCCESS**
Build succeeded for 5 out of 5 (5 easyconfigs in this PR)
grc-cluster1 - Linux centos 6.10, Intel(R) Xeon(R) CPU E5-2640 0 @ 2.50GHz, Python 2.7.14
See https://gist.github.com/55a4438ded77307ad666fa8764cbdca7 for a full test report.

**Comment by migueldiascosta** [comment]
Going in, thanks @akesandgren!

**Pull request merged**
