### PR TITLE
{compiler}[system/system] Go v1.18.3

### PR DESCRIPTION
**Pull request by Poshi**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by Micket** [comment]
Test report by @Micket
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
alvis-c1 - Linux Rocky Linux 8.5, x86_64, Intel Xeon Processor (Skylake), Python 3.6.8
See https://gist.github.com/6bb9fb9339096053ffb8e90bfcaf898d for a full test report.

**Comment by Poshi** [comment]
Test report by @Poshi
**SUCCESS**
Build succeeded for 0 out of 0 (1 easyconfigs in total)
login6 - Linux CentOS Linux 7.9.2009, x86_64, AMD EPYC 7H12 64-Core Processor, Python 3.6.8
See https://gist.github.com/039b1f4b697f827caf4a13c303f2d454 for a full test report.

**Comment by boegel** [comment]
@boegelbot please test @ generoso

**Comment by Micket** [comment]
Test report by @Micket
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
alvis-c1 - Linux Rocky Linux 8.5, x86_64, Intel Xeon Processor (Skylake), Python 3.6.8
See https://gist.github.com/aa95db5c59c681d8728eca48a86b4859 for a full test report.

**Review by Micket — APPROVED** [review]
lgtm

**Comment by Micket** [comment]
Going in, thanks @Poshi!

**Pull request merged**
