### PR TITLE
{bio}[foss/2022a] PALEOMIX v1.3.7, seqtk v1.3, mapDamage v2.2.1 w/ Python 3.10.4

### PR DESCRIPTION
**Pull request by bedroge**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by bedroge** [comment]
Test report by @bedroge
**SUCCESS**
Build succeeded for 3 out of 3 (3 easyconfigs in total)
node1 - Linux Rocky Linux 8.7, x86_64, AMD EPYC 7763 64-Core Processor, Python 3.6.8
See https://gist.github.com/bedroge/fdcccb57ede89441b96bf0f202d773b5 for a full test report.

**Comment by bedroge** [comment]
@boegelbot please test @ generoso

**Comment by bedroge** [comment]
@boegelbot please test @ jsc-zen2

**Comment by verdurin** [comment]
Test report by @verdurin
**SUCCESS**
Build succeeded for 6 out of 6 (3 easyconfigs in total)
easybuild-c7.novalocal - Linux CentOS Linux 7.9.2009, x86_64, Intel Xeon Processor (Skylake, IBRS), Python 3.6.8
See https://gist.github.com/verdurin/b4325d5a05da9ad2bf19dcacbdec8a70 for a full test report.

**Review by verdurin — APPROVED** [review]
Looks fine.

**Comment by verdurin** [comment]
Going in, thanks @bedroge!

**Pull request merged**
