### PR TITLE
{bio}[GCCcore/12.3.0,foss/2023a,gompi/2023a] RepeatMasker v4.1.7-p1, RMBlast v2.14.1, TRF v4.09.1

### PR DESCRIPTION
**Pull request by PetrKralCZ**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by PetrKralCZ** [comment]
@boegelbot please test @ generoso

**Comment by PetrKralCZ** [comment]
@boegelbot please test @ jsc-zen3

**Comment by boegel** [comment]
CI failure has nothing to do with this PR, it's fixed with #21419

**Review by boegel — APPROVED** [review]
lgtm

**Comment by boegel** [comment]
Going in, thanks @PetrKralCZ!

**Pull request merged**
