### PR TITLE
deprecate use of `True` in favour of `SYSTEM` for system-toolchain dependencies

### PR DESCRIPTION
**Pull request by jfgrimm**
adds a CI check as suggested in https://github.com/easybuilders/easybuild-easyconfigs/issues/16330
part 2 (updating existing easyconfigs to use `SYSTEM`) coming soon

### CODE REVIEW

**Comment by jfgrimm** [comment]
> @jfgrimm Wouldn't it be easier if this change is also part of #16386 ? _Together_ they should create a CI that passes successfully, right? That's not easy to verify when they are in two different PRs.

I was thinking merge the updates to easyconfigs first, and then the CI after. The switch from `True` to `SYSTEM` is already supported, so I'd consider that distinct from the CI enhancement. In any case, any oversights should be caught in this PR

**Comment by jfgrimm** [comment]
@casparvl besides, the other PR is already so big that it's easier to see the actual CI change when it's separated out

**Comment by casparvl** [comment]
> > @jfgrimm Wouldn't it be easier if this change is also part of #16386 ? _Together_ they should create a CI that passes successfully, right? That's not easy to verify when they are in two different PRs.
> 
> I was thinking merge the updates to easyconfigs first, and then the CI after. The switch from `True` to `SYSTEM` is already supported, so I'd consider that distinct from the CI enhancement. In any case, any oversights should be caught in this PR

Ah you're right, I didn't realize that that one should just pass already with the current develop. Then, indeed, this is the sane way to do it :)

**Review by casparvl — APPROVED** [review]
Looks good to me! The CI passes, which is the most important check here. Just as a sanity check, I've also confirmed that the regex indeed correctly matches e.g. 

```
gompi-2016.04.eb
 gompi-2016.06.eb
 gompi-2016.07.eb
 gompi-2016.09.eb
 gompi-2016a.eb
 gompi-2016b.eb
 gompi-2017a.eb
 gompi-2017b.eb
 gompi-2018.08.eb
 gompi-2018a.eb
 gompi-2018b.eb
 gompi-2019a.eb
 gompi-2019b.eb
 ``` 
 but not
 ```
 gompi-2020a.eb
 gompi-2020b.eb
 gompi-2021a.eb
 gompi-2021b.eb
 gompi-2022.05.eb
 gompi-2022a.eb
```
as intended.

**Comment by casparvl** [comment]
Thanks @jfgrimm for going through this effort! :)

**Pull request merged**
