### PR TITLE
{devel}[foss/2022b] ONNX-Runtime v1.16.3, ONNX v1.15.0

### PR DESCRIPTION
**Pull request by boegel**
(created using `eb --new-pr`)
requires:
* #19510

### CODE REVIEW

**Comment by boegel** [comment]
@boegelbot please test @ generoso

**Comment by boegel** [comment]
@boegelbot please test @ jsc-zen2

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in total)
node3123.skitty.os - Linux RHEL 8.8, x86_64, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz (skylake_avx512), Python 3.6.8
See https://gist.github.com/boegel/23ead9d825ad66f2658e4bbfd9eea80b for a full test report.

**Comment by akesandgren** [comment]
@boegelbot Please test @ generoso

**Comment by boegel** [comment]
Hmm, job failed in `generoso` with:
```
ERROR: Failed to get data for PR #19511 from easybuilders/easybuild-easyconfigs (HTTP Error 403: Forbidden)
Please check PR #, account and repo.
```

GitHub token used by bot is still valid, so I'll just trigger it again...

**Comment by boegel** [comment]
@boegelbot please test @ generoso

**Review by smoors — APPROVED** [review]
lgtm

**Comment by smoors** [comment]
Going in, thanks @boegel!

**Pull request merged**
