### PR TITLE
Switch to GCC 9.3.0 for foss/2020a and intel/2020a release

### PR DESCRIPTION
**Pull request by akesandgren**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by boegel** [comment]
@akesandgren You'll need to move a couple deps from `GCCcore/9.2.0` to `GCCcore/9.3.0`:

```
EasyBuildError: 'Missing dependencies: bzip2/1.0.8-gompi-2020a-rc3, Python/3.8.2-foss-2020a-rc3, zlib/1.2.11-gompi-2020a-rc3, pybind11/2.4.3-foss-2020a-rc3-Python-3.8.2, foss/2020a-rc3, XZ/5.2.4-gompi-2020a-rc3, gompi/2020a-rc3 (no easyconfig file or existing module found)'
```

**Comment by zao** [comment]
Test report by @zao
**SUCCESS**
Build succeeded for 6 out of 6 (6 easyconfigs in this PR)
freja - Linux ubuntu 18.04, Intel(R) Core(TM) i7-8700K CPU @ 3.70GHz, Python 2.7.17
See https://gist.github.com/d53568ab69c08ea0f9fe857e394d6c2b for a full test report.

**Comment by akesandgren** [comment]
Test report by @akesandgren
**SUCCESS**
Build succeeded for 6 out of 6 (6 easyconfigs in this PR)
b-an04.hpc2n.umu.se - Linux ubuntu 16.04, Intel(R) Xeon(R) CPU E5-2690 v4 @ 2.60GHz, Python 2.7.12
See https://gist.github.com/550e12f192974d4671265602555f56f1 for a full test report.

**Comment by akesandgren** [comment]
Test report by @akesandgren
**SUCCESS**
Build succeeded for 6 out of 6 (6 easyconfigs in this PR)
skalman.hpc2n.umu.se - Linux ubuntu 18.04, Intel(R) Core(TM) i7-8565U CPU @ 1.80GHz, Python 2.7.17
See https://gist.github.com/16e3d0d822eef8b28e74710d6e209007 for a full test report.

**Comment by migueldiascosta** [comment]
Test report by @migueldiascosta
**SUCCESS**
Build succeeded for 16 out of 16 (15 easyconfigs in this PR)
sms - Linux centos linux 7.6.1810, AMD EPYC 7601 32-Core Processor, Python 2.7.5
See https://gist.github.com/734ae078f4b1ac61343f3683e22dc116 for a full test report.

**Comment by branfosj** [comment]
Test report by @branfosj
**SUCCESS**
Build succeeded for 10 out of 10 (10 easyconfigs in this PR)
bear-pg0211u03a.bear.cluster - Linux centos linux 7.7.1908, Intel(R) Xeon(R) Gold 6248 CPU @ 2.50GHz, Python 2.7.5
See https://gist.github.com/51b4861187e7e2a907dc40bf4f38e3be for a full test report.

**Comment by branfosj** [comment]
Test report by @branfosj
**SUCCESS**
Build succeeded for 10 out of 10 (10 easyconfigs in this PR)
bber0501u03a.bb2.cluster - Linux centos linux 7.7.1908, Intel(R) Xeon(R) CPU E5-2690 v3 @ 2.60GHz, Python 2.7.5
See https://gist.github.com/29f37947407161ce41539bd5dbe493dd for a full test report.

**Comment by branfosj** [comment]
Test report by @branfosj
**SUCCESS**
Build succeeded for 10 out of 10 (10 easyconfigs in this PR)
bear-pg0306u03a.bear.cluster - Linux RHEL 7.6, 8335-GTX, Python 2.7.5
See https://gist.github.com/83f6c2e2d0d5fa80a05ff76a7cf0b493 for a full test report.

**Comment by akesandgren** [comment]
@branfosj It looks like you didn't do --rebuild on those test reports, there are 16 ECs in this PR not 10...

**Comment by akesandgren** [comment]
And somethings odd with the report from @migueldiascosta too, it says 15 EC in the PR

**Comment by branfosj** [comment]
@akesandgren In the test rerports above I've built the non-Intel items. There'll be a further couple of test reports to follow that will just do the Intel items.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 16 out of 16 (16 easyconfigs in this PR)
node2491.golett.os - Linux centos linux 7.7.1908, Intel(R) Xeon(R) CPU E5-2680 v3 @ 2.50GHz, Python 2.7.5
See https://gist.github.com/227f97b198809797f81dec258eb26406 for a full test report.

**Comment by branfosj** [comment]
Test report by @branfosj
**SUCCESS**
Build succeeded for 6 out of 6 (16 easyconfigs in this PR)
bber0501u03a.bb2.cluster - Linux centos linux 7.7.1908, Intel(R) Xeon(R) CPU E5-2690 v3 @ 2.60GHz, Python 2.7.5
See https://gist.github.com/5e84d78e0cfef85c8026d2ca17c59870 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 16 out of 16 (16 easyconfigs in this PR)
generoso - Linux centos linux 7.6.1810, Intel(R) Xeon(R) CPU E5-2660 v4 @ 2.00GHz, Python 3.6.8
See https://gist.github.com/56b676771bdd358e7d8b5c93127b7ed2 for a full test report.

**Comment by branfosj** [comment]
Test report by @branfosj
**FAILED**
Build succeeded for 8 out of 10 (10 easyconfigs in this PR)
bb2c1a09.bb2.cluster - Linux centos linux 7.7.1908, Intel(R) Xeon(R) CPU E5-2660 0 @ 2.20GHz, Python 2.7.5
See https://gist.github.com/006af422f78e8a8f17c10f0f00ad81a8 for a full test report.

**Comment by branfosj** [comment]
> 
> 
> Test report by @branfosj
> **FAILED**
> Build succeeded for 8 out of 10 (10 easyconfigs in this PR)
> bb2c1a09.bb2.cluster - Linux centos linux 7.7.1908, Intel(R) Xeon(R) CPU E5-2660 0 @ 2.20GHz, Python 2.7.5
> See https://gist.github.com/006af422f78e8a8f17c10f0f00ad81a8 for a full test report.

This faliure can be ignored. Someone set off two builds of the same item at the same time ...

**Comment by boegel** [comment]
Going in, thanks @akesandgren!

**Comment by akesandgren** [comment]
Test report by @akesandgren
**FAILED**
Build succeeded for 15 out of 21 (16 easyconfigs in this PR)
skalman.hpc2n.umu.se - Linux ubuntu 18.04, Intel(R) Core(TM) i7-8565U CPU @ 1.80GHz, Python 2.7.17
See https://gist.github.com/2da78969746b0af622d6ed8033a712ea for a full test report.

**Comment by zao** [comment]
Test report by @zao
**FAILED**
Build succeeded for 13 out of 16 (16 easyconfigs in this PR)
freja - Linux ubuntu 18.04, Intel(R) Core(TM) i7-8700K CPU @ 3.70GHz, Python 2.7.17
See https://gist.github.com/bafc256f2236453a464b123b86ff1c59 for a full test report.

**Comment by lexming** [comment]
Test report by @lexming
**SUCCESS**
Build succeeded for 16 out of 16 (16 easyconfigs in this PR)
login2.cerberus.os - Linux centos linux 7.7.1908, Intel(R) Xeon(R) Gold 6126 CPU @ 2.60GHz, Python 2.7.5
See https://gist.github.com/760b5a600714765130788f371cdf0fd6 for a full test report.

**Comment by akesandgren** [comment]
Test report by @akesandgren
**SUCCESS**
Build succeeded for 16 out of 16 (16 easyconfigs in this PR)
b-an04.hpc2n.umu.se - Linux ubuntu 16.04, Intel(R) Xeon(R) CPU E5-2690 v4 @ 2.60GHz, Python 2.7.12
See https://gist.github.com/e31ab19df6e04a391186ceb104f51c68 for a full test report.

**Comment by branfosj** [comment]
Test report by @branfosj
**FAILED**
Build succeeded for 12 out of 16 (16 easyconfigs in this PR)
bb2c1a09.bb2.cluster - Linux centos linux 7.7.1908, Intel(R) Xeon(R) CPU E5-2660 0 @ 2.20GHz, Python 2.7.5
See https://gist.github.com/ccceb81b8afe6d826e29a6ce34227c9a for a full test report.

**Comment by branfosj** [comment]
> Test report by @branfosj
> **FAILED**
> Build succeeded for 12 out of 16 (16 easyconfigs in this PR)
> bb2c1a09.bb2.cluster - Linux centos linux 7.7.1908, Intel(R) Xeon(R) CPU E5-2660 0 @ 2.20GHz, Python 2.7.5
> See https://gist.github.com/ccceb81b8afe6d826e29a6ce34227c9a for a full test report.

Argh... That is a filesystem related error. I.e. it can also be ignored.

**Comment by branfosj** [comment]
Test report by @branfosj
**SUCCESS**
Build succeeded for 16 out of 16 (16 easyconfigs in this PR)
bb2c1a09.bb2.cluster - Linux centos linux 7.7.1908, Intel(R) Xeon(R) CPU E5-2660 0 @ 2.20GHz, Python 2.7.5
See https://gist.github.com/86f204c539a6f65cf779ebda6848916d for a full test report.

**Comment by migueldiascosta** [comment]
Test report by @migueldiascosta
**SUCCESS**
Build succeeded for 16 out of 16 (16 easyconfigs in this PR)
sms - Linux centos linux 7.6.1810, AMD EPYC 7601 32-Core Processor, Python 2.7.5
See https://gist.github.com/cb3dc82320de8c9407fabe84176405d2 for a full test report.

**Pull request merged**
