### PR TITLE
{bio}[foss/2023b] Biopython v1.84

### PR DESCRIPTION
**Pull request by fizwit**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by migueldiascosta** [comment]
@fizwit just to explain why I changed the title, since you do seem to be using `--new-pr` and specified a `--pr-commit-message` (that's only necessary when an easyconfig is being changed, which is not the case), the reason is that the automatic titles help us somewhat when filtering through the PRs in order to compose the release notes at each release,  It's not a very big deal since we do cross check those assumptions, but sticking to the defaults does make it easier. Just FYI.

**Comment by migueldiascosta** [comment]
@boegelbot please test @ generoso

**Comment by migueldiascosta** [comment]
@boegelbot please test @ jsc-zen3

**Comment by migueldiascosta** [comment]
Test report by @migueldiascosta
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
gracehopper - Linux Rocky Linux 9.3, AArch64, ARM UNKNOWN (neoverse_v2), 1 x NVIDIA NVIDIA GH200 480GB, 550.54.15, Python 3.9.18
See https://gist.github.com/migueldiascosta/aabf561759dd705a9667c0fddfd31e82 for a full test report.

**Review by migueldiascosta — APPROVED** [review]
lgtm

**Comment by migueldiascosta** [comment]
Going in, thanks @fizwit!

**Comment by fizwit** [comment]
> @fizwit just to explain why I changed the title, since you do seem to be using `--new-pr` and specified a `--pr-commit-message` (that's only necessary when an existing easyconfig is being changed, which is not the case here), the reason is that the automatic titles help us somewhat when filtering through the PRs in order to compose the release notes at each release. It's not a very big deal since we do cross check those assumptions, but sticking to the defaults does make it easier. Just FYI.

Should I be using `--pr-title`

**Comment by migueldiascosta** [comment]
> Should I be using `--pr-title`

for PRs that only add easyconfigs, there's no need to use neither `--pr-commit-message` nor `--pr-title`, the title will be automatically generated. You can check with `--preview-pr`

**Pull request merged**
