### PR TITLE
{vis}[GCCcore/13.3.0] Ghostscript v10.03.1, HarfBuzz v9.0.0, ImageMagick v7.1.1-38, ...

### PR DESCRIPTION
**Pull request by Flamefire**
(created using `eb --new-pr`)

Requires
- [x] #21385

### CODE REVIEW

**Comment by Flamefire** [comment]
Test report by @Flamefire
**SUCCESS**
Build succeeded for 5 out of 5 (5 easyconfigs in total)
i7087 - Linux Rocky Linux 8.9 (Green Obsidian), x86_64, AMD EPYC 7702 64-Core Processor (zen2), Python 3.8.17
See https://gist.github.com/Flamefire/77a17ece17da8cb59fbe6d9f4bcf3a5a for a full test report.

**Comment by SebastianAchilles** [comment]
@boegelbot please test @ jsc-zen3

**Review by smoors — APPROVED** [review]
lgtm

**Comment by smoors** [comment]
Going in, thanks @Flamefire!

**Pull request merged**
