### PR TITLE
{bio}[foss/2022a] dorado v0.5.3 w/ CUDA 11.7.0

### PR DESCRIPTION
**Pull request by WilleBell**
(created using `eb --new-pr`)

### CODE REVIEW

**Review by verdurin — APPROVED** [review]
Looks fine.

**Comment by verdurin** [comment]
Test report by @verdurin
**SUCCESS**
Build succeeded for 3 out of 3 (1 easyconfigs in total)
easybuild-c7.novalocal - Linux CentOS Linux 7.9.2009, x86_64, Intel Xeon Processor (Skylake, IBRS), Python 3.6.8
See https://gist.github.com/verdurin/ee09f03d592996e214dac25a76b0ec75 for a full test report.

**Comment by verdurin** [comment]
@boegelbot please test @ jsc-zen3

**Comment by akesandgren** [comment]
Test report by @akesandgren
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
b-cn1603.hpc2n.umu.se - Linux Ubuntu 22.04, x86_64, AMD EPYC 7313 16-Core Processor, 1 x NVIDIA NVIDIA A100 80GB PCIe, 545.29.06, Python 3.10.12
See https://gist.github.com/akesandgren/99c2d09d0ddf0fafd7cf5c075c2f5202 for a full test report.

**Review by akesandgren — APPROVED** [review]
LGTM

**Pull request merged**
