### PR TITLE
add libwebp and OpenEXR dependencies for OpenCV 4.2.0 easyconfig with foss/2020a

### PR DESCRIPTION
**Pull request by lexming**
(created using `eb --new-pr`)

OpenCV is currently building bundled versions of `libwebp` and `openexr`. This PR switches the build to external deps from EB.

Depends on ~~#12225~~ and ~~https://github.com/easybuilders/easybuild-easyblocks/pull/2346~~

### CODE REVIEW

**Comment by verdurin** [comment]
Test report by @verdurin
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
easybuild-c7.novalocal - Linux centos linux 7.9.2009, x86_64, Intel Xeon Processor (Skylake, IBRS), Python 3.6.8
See https://gist.github.com/911ba28abd87104c4b31c7ddd4125195 for a full test report.

**Comment by verdurin** [comment]
Test report by @verdurin
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
nuc.lan - Linux Fedora 32, x86_64, Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz, Python 3.8.7
See https://gist.github.com/100f977b8900927c3a3718c92fbcbd39 for a full test report.

**Comment by verdurin** [comment]
@lexming in my build log it has this during `configure`:
```
--   Media I/O:
--     ZLib:                        /mnt/ds918plus/eb/nuc-fedora32/software/zlib/1.2.11-GCCcore-9.3.0/lib/libz.so (ver 1.2.11)
--     JPEG:                        /mnt/ds918plus/eb/nuc-fedora32/software/libjpeg-turbo/2.0.4-GCCcore-9.3.0/lib64/libjpeg.so (ver 80)
--     WEBP:                        /mnt/ds918plus/eb/nuc-fedora32/software/libwebp/1.1.0-GCCcore-9.3.0/lib/libwebp.so (ver encoder: 0x020f)
--     PNG:                         /mnt/ds918plus/eb/nuc-fedora32/software/libpng/1.6.37-GCCcore-9.3.0/lib/libpng.so (ver 1.6.37)
--     TIFF:                        /mnt/ds918plus/eb/nuc-fedora32/software/LibTIFF/4.1.0-GCCcore-9.3.0/lib/libtiff.so (ver 42 / 4.1.0)
--     JPEG 2000:                   /mnt/ds918plus/eb/nuc-fedora32/software/JasPer/2.0.14-GCCcore-9.3.0/lib64/libjasper.so (ver 2.0.14)
--     OpenEXR:                     build (ver 2.3.0)
```
Looks like it isn't picking up the EB `OpenEXR`?

**Comment by lexming** [comment]
@verdurin good catch, I made a PR (https://github.com/easybuilders/easybuild-easyblocks/pull/2346) to force the use of the external libraries in OpenCV

**Comment by boegel** [comment]
Crap, I was looking into this too: https://github.com/easybuilders/easybuild-easyblocks/pull/2347 :D

**Comment by boegel** [comment]
Test report by @boegel
Using easyblocks from PR(s) https://github.com/easybuilders/easybuild-easyblocks/pull/2346
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
node2637.swalot.os - Linux centos linux 7.9.2009, x86_64, Intel(R) Xeon(R) CPU E5-2660 v3 @ 2.60GHz (haswell), Python 3.6.8
See https://gist.github.com/b5b32c15477319e369d91a694530e104 for a full test report.

**Comment by lexming** [comment]
Test report by @lexming
Using easyblocks from PR(s) https://github.com/easybuilders/easybuild-easyblocks/pull/2346
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
node376.hydra.os - Linux centos linux 7.9.2009, x86_64, Intel(R) Xeon(R) Gold 6148 CPU @ 2.40GHz, Python 2.7.5
See https://gist.github.com/54b02c8434d4ef7179595886ec87500c for a full test report.

**Comment by verdurin** [comment]
Test report by @verdurin
Using easyblocks from PR(s) https://github.com/easybuilders/easybuild-easyblocks/pull/2346
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
nuc.lan - Linux Fedora 32, x86_64, Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz, Python 3.8.7
See https://gist.github.com/aacd5fe65f848f7e4c666e8d71f0dc92 for a full test report.

**Comment by verdurin** [comment]
@boegelbot please test @ generoso
EB_ARGS = "--include-easyblocks-from-pr=2346"

**Review by boegel — APPROVED** [review]
lgtm

**Comment by verdurin** [comment]
Going in, thanks @lexming!

**Pull request merged**
