### PR TITLE
{phys}[foss/2022b] TOPAS v3.9, CLHEP v2.4.6.4, GDCM v3.0.21

### PR DESCRIPTION
**Pull request by boegel**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by boegel** [comment]
@boegelbot please test @ generoso

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 3 out of 3 (3 easyconfigs in total)
node3163.skitty.os - Linux RHEL 8.6, x86_64, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz (skylake_avx512), Python 3.6.8
See https://gist.github.com/6039eb1b11ada60835290e704062ad33 for a full test report.

**Comment by casparvl** [comment]
Like `jsc-zen2`, a local build fails with a source not found for me.

**Comment by casparvl** [comment]
Test report by @casparvl
**FAILED**
Build succeeded for 0 out of 1 (3 easyconfigs in total)
tcn251.local.snellius.surf.nl - Linux Rocky Linux 8.7, x86_64, AMD EPYC 7H12 64-Core Processor, Python 3.6.8
See https://gist.github.com/69f8f9ada79f4df4b862a1a6f996d6d6 for a full test report.

**Comment by casparvl** [comment]
As @boegel pointed out to me, there are `download_instructions` in the EasyConfig for a manual download... I've downloaded them now, new test report should be coming up in a bit...

**Comment by casparvl** [comment]
Test report by @casparvl
**SUCCESS**
Build succeeded for 3 out of 3 (3 easyconfigs in total)
tcn349.local.snellius.surf.nl - Linux Rocky Linux 8.7, x86_64, AMD EPYC 7H12 64-Core Processor, Python 3.6.8
See https://gist.github.com/casparvl/c0fce56a87ba00ab216437c224aa7048 for a full test report.

**Comment by smoors** [comment]
Going in, thanks @boegel!

**Pull request merged**
