### PR TITLE
$XDG_DATA_DIRS must be set for GTK+

### PR DESCRIPTION
**Pull request by akesandgren**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by vanzod** [comment]
If this is also required by the version `2.24.x` available in the older toolchains, it may be worth fixing them all in this PR.

**Comment by akesandgren** [comment]
@boegel what do you say? How far back should we fix this?

**Comment by boegel** [comment]
@akesandgren Why not fix all of them, or at least the ones using a non-deprecated toolchain?

The change is quite trivial (it can be tested with `--module-only`).

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 12 out of 12 (12 easyconfigs in this PR)
node2003.delcatty.os - Linux centos linux 7.6.1810, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.7.5
See https://gist.github.com/774aced72edff9c3f6e07dfda21b62b0 for a full test report.

**Comment by boegel** [comment]
@akesandgren You'll need to add the missing checksums too for the older `GTK+` easyconfigs...

**Comment by boegel** [comment]
@akesandgren And now you're being bitten by #8101... :)

**Comment by akesandgren** [comment]
Test report by @akesandgren
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
b-an03.hpc2n.umu.se - Linux ubuntu 16.04, Intel(R) Xeon(R) CPU E5-2690 v4 @ 2.60GHz, Python 2.7.12
See https://gist.github.com/89c734774eaf2d1dd77ff0062fea7774 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 13 out of 13 (13 easyconfigs in this PR)
node2003.delcatty.os - Linux centos linux 7.6.1810, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.7.5
See https://gist.github.com/104c3c351e22a57116d43c4579cb80fc for a full test report.

**Comment by boegel** [comment]
Going in, thanks @akesandgren!

**Pull request merged**
