### PR TITLE
{devel}[GCCcore/10.3.0] Extrae v3.8.3, libdwarf v20210305, libelf v0.8.13

### PR DESCRIPTION
**Pull request by robert-mijakovic**
(created using `eb --new-pr`)
Depends on ~#12977~

### CODE REVIEW

**Comment by robert-mijakovic** [comment]
@boegelbot please test @ generoso EB_ARGS="--from-pr 12977"

**Comment by robert-mijakovic** [comment]
@boegelbot please test @ generoso

**Comment by maxim-masterov** [comment]
Hi! Any updates on this PR?

**Comment by boegel** [comment]
It seems like there was a sneaky re-release of Extrae 3.8.3 on 2021-11-15 (see https://ftp.tools.bsc.es/extrae/), so I fixed the SHA256 checksum in 7ac359f ...

@robert-mijakovic Do you still have the original source tarball for Extrae (with checksum 32a3d6b01da2c9b8d177d91307d4c04c6db0923ca1d63bfb32768a172af7943b), so we can check what has changed?

**Comment by boegel** [comment]
@boegelbot please test @ generoso

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 3 out of 3 (3 easyconfigs in total)
node3518.doduo.os - Linux RHEL 8.2, x86_64, AMD EPYC 7552 48-Core Processor (zen2), Python 3.6.8
See https://gist.github.com/95746ce397d34b2b7a4dc0305e11a187 for a full test report.

**Comment by boegel** [comment]
The original source tarball is available on `generoso` (that's why the test report failed).

Although the SHA256 checksum is indeed different, there's no difference in the contents after unpacking, so I'll list both SHA256 checksums as valid in the `Extra` easyconfig...

**Comment by boegel** [comment]
@boegelbot please test @ generoso

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 3 out of 3 (3 easyconfigs in total)
node3148.skitty.os - Linux centos linux 7.9.2009, x86_64, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz (skylake_avx512), Python 3.6.8
See https://gist.github.com/b5d0008e05954b3b501ef9c76ecdfea5 for a full test report.

**Review by boegel — APPROVED** [review]
lgtm

**Comment by boegel** [comment]
Going in, thanks @robert-mijakovic!

**Pull request merged**
