### PR TITLE
switch to GitHub sources for ScientificPython 2.9.4

### PR DESCRIPTION
**Pull request by boegel**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in this PR)
node2405.golett.os - Linux centos linux 7.8.2003, x86_64, Intel(R) Xeon(R) CPU E5-2680 v3 @ 2.50GHz (haswell), Python 2.7.5
See https://gist.github.com/465e92182bad1041c1020ab14f82db20 for a full test report.

**Comment by boegel** [comment]
I'll need to allow using `sanity_pip_check = False` here too, so waiting until #10873 gets merged to avoid introducing conflicts...

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in this PR)
node2405.golett.os - Linux centos linux 7.8.2003, x86_64, Intel(R) Xeon(R) CPU E5-2680 v3 @ 2.50GHz (haswell), Python 2.7.5
See https://gist.github.com/9bd43e9b1fe66cad9b3b9b08dc78659c for a full test report.

**Comment by zao** [comment]
Going in, thanks @boegel!

**Pull request merged**
