### PR TITLE
{bio}[foss/2021a,gompi/2021a] RMBlast v2.14.0, RepeatMasker v4.1.5 w/ Python 3.9.5

### PR DESCRIPTION
**Pull request by SIB-software**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by verdurin** [comment]
Test report by @verdurin
**SUCCESS**
Build succeeded for 4 out of 4 (2 easyconfigs in total)
easybuild-c7.novalocal - Linux CentOS Linux 7.9.2009, x86_64, Intel Xeon Processor (Skylake, IBRS), Python 3.6.8
See https://gist.github.com/verdurin/21069a07a4ead3d251fdbdde1e9942e2 for a full test report.

**Comment by verdurin** [comment]
@boegelbot please test @ generoso

**Review by verdurin — APPROVED** [review]
Looks fine.

**Comment by smoretti** [comment]
Hi
@verdurin what else is missing for this PR?

**Comment by smoretti** [comment]
Hi @verdurin
What else is missing here?

**Comment by verdurin** [comment]
Going in, thanks @SIB-software!

**Pull request merged**
