### PR TITLE
Adding faulthandler patches to Python 3.7.0 easyconfigs

### PR DESCRIPTION
**Pull request by justbennet**
This request simply adds the patch file that was approved for

    add patch to Python 3.7.2 easyconfig to fix faulthandler segfault #8781

to the three Python 3.7.0 easyconfigs.

### CODE REVIEW

**Comment by smoors** [comment]
Test report by @smoors
**SUCCESS**
Build succeeded for 3 out of 3 (3 easyconfigs in this PR)
node375.hydra.os - Linux centos linux 7.6.1810, Intel(R) Xeon(R) Gold 6148 CPU @ 2.40GHz, Python 2.7.5
See https://gist.github.com/043887c2a92c9112042db3d8a1026428 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 3 out of 3 (3 easyconfigs in this PR)
node2106.delcatty.os - Linux centos linux 7.6.1810, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.7.5
See https://gist.github.com/89888ca780597197b7e62f5e1de37d29 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 3 out of 3 (3 easyconfigs in this PR)
node2712.swalot.os - Linux centos linux 7.6.1810, Intel(R) Xeon(R) CPU E5-2660 v3 @ 2.60GHz, Python 2.7.5
See https://gist.github.com/8bec189bc2687655b2aae2a6832c00ba for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 3 out of 3 (3 easyconfigs in this PR)
gligar05.gastly.os - Linux centos linux 7.6.1810, Intel(R) Xeon(R) Gold 6130 CPU @ 2.10GHz, Python 3.6.8
See https://gist.github.com/3f01de5cf7cc03cdfdba1a56d5832aaa for a full test report.

**Comment by boegel** [comment]
Going in, thanks @justbennet!

**Pull request merged**
