### PR TITLE
{bio}[iccifort/2019.5.281] BRAKER v2.1.5, spaln v2.4.03, Exonerate v2.4.0, ...

### PR DESCRIPTION
**Pull request by boegel**
(created using `eb --new-pr`)
requires ~~#10451~~ (AUGUSTUS)

### CODE REVIEW

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 5 out of 5 (5 easyconfigs in this PR)
node3401.kirlia.os - Linux centos linux 7.7.1908, x86_64, Intel(R) Xeon(R) Gold 6240 CPU @ 2.60GHz (cascadelake), Python 2.7.5
See https://gist.github.com/fb649fc5b12134af1f6a9befe98a7b94 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 5 out of 5 (5 easyconfigs in this PR)
node2401.golett.os - Linux centos linux 7.7.1908, x86_64, Intel(R) Xeon(R) CPU E5-2680 v3 @ 2.50GHz (haswell), Python 2.7.5
See https://gist.github.com/2f38f87fb9741198acb7872eece01c50 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 6 out of 6 (5 easyconfigs in this PR)
node3129.skitty.os - Linux centos linux 7.7.1908, x86_64, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz (skylake_avx512), Python 3.6.8
See https://gist.github.com/9faecd58152a9ce571437429026c0b09 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 5 out of 5 (5 easyconfigs in this PR)
generoso - Linux centos linux 7.6.1810, x86_64, Intel(R) Xeon(R) CPU E5-2660 v4 @ 2.00GHz, Python 3.6.8
See https://gist.github.com/6ba2ca41346eadb1026e547e5e1fee63 for a full test report.

**Comment by Micket** [comment]
Test report by @Micket
**FAILED**
Build succeeded for 10 out of 12 (5 easyconfigs in this PR)
vera-c1 - Linux centos linux 7.7.1908, Intel Xeon Processor (Skylake), Python 2.7.5
See https://gist.github.com/fdacebb6be669ebe2ae42549d61ae758 for a full test report.

**Comment by Micket** [comment]
`--from-pr` (nor `--review`)  can manage to find GeneMark-ET dependency from within the  isn't picking up internal paths

**Comment by Micket** [comment]
Going in, thanks @boegel!

**Pull request merged**
