### PR TITLE
{lang}[foss/2018b,intel/2018b] numba v0.43.1

### PR DESCRIPTION
**Pull request by jose-d**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by jose-d** [comment]
patch has to be added manually. TBD later.

**Comment by jose-d** [comment]
## Numba benchmarks:

### foss Python 2.7.15

```
jose@koios1:~/temp/numba/benchmarks$ module load vis/matplotlib/2.2.3-foss-2018b-Python-2.7.15
jose@koios1:~/temp/numba/benchmarks$ module load lang/numba/0.43.1-foss-2018b-Python-2.7.15
jose@koios1:~/temp/numba/benchmarks$ python ./runall.py
running laplace2d ...
        python 11.746003150939941 seconds
        numba 0.016614198684692383 seconds
        speedup 706.9858362631843
running euler ...
        python 26.07061791419983 seconds
        numba 1.808439016342163 seconds
        speedup 14.416089057253107
jose@koios1:~/temp/numba/benchmarks$
```
### foss Python 3.6.6
```
jose@koios1:~/temp/numba/benchmarks$ module load lang/numba/0.43.1-foss-2018b-Python-3.6.6
jose@koios1:~/temp/numba/benchmarks$ module load vis/matplotlib/3.0.2-foss-2018b-Python-3.6.6
jose@koios1:~/temp/numba/benchmarks$ python ./runall.py
running laplace2d ...
        python 14.847144678991754 seconds
        numba 0.047272914700442925 seconds
        speedup 314.07296912142044
running euler ...
        python 30.078568661992904 seconds
        numba 1.8490769990021363 seconds
        speedup 16.26680158707558
jose@koios1:~/temp/numba/benchmarks$
```

### intel Python 2.7.15
```
jose@koios1:~/temp/numba/benchmarks$ module load lang/numba/0.43.1-intel-2018b-Python-2.7.15
jose@koios1:~/temp/numba/benchmarks$ module load vis/matplotlib/2.2.3-intel-2018b-Python-2.7.15
jose@koios1:~/temp/numba/benchmarks$ python ./runall.py
running laplace2d ...
        python 13.106981992721558 seconds
        numba 0.01682779788970947 seconds
        speedup 778.8887220196966
running euler ...
        python 26.546169996261597 seconds
        numba 2.500429153442383 seconds
        speedup 10.616645530514248
jose@koios1:~/temp/numba/benchmarks$
```
### intel Python 3.6.6
```
jose@koios1:~/temp/numba/benchmarks$ module load lang/numba/0.43.1-intel-2018b-Python-3.6.6
jose@koios1:~/temp/numba/benchmarks$ module load vis/matplotlib/3.0.0-intel-2018b-Python-3.6.6
jose@koios1:~/temp/numba/benchmarks$ python ./runall.py 
running laplace2d ...
        python 15.119397685979493 seconds
        numba 0.0454468195035588 seconds
        speedup 332.6832955779346
running euler ...
        python 27.31767955602845 seconds
        numba 1.821166339039337 seconds
        speedup 15.000101292470898
/home/users/jose/.local/easybuild/software/vis/matplotlib/3.0.0-intel-2018b-Python-3.6.6/lib/python3.6/site-packages/matplotlib/figure.py:448: UserWarning: Matplotlib is currently using agg, which is a non-GUI backend, so cannot show the figure.
  % get_backend())
jose@koios1:~/temp/numba/benchmarks$
```

**Comment by jose-d** [comment]
> found 2 variants of 'LLVM' dependency in easyconfigs using '2018b' toolchain generation
ok let's stick to LLVM 6.0.0.

**Comment by jose-d** [comment]
..and  LLVM < 6.0.1 is not building well with `llvmlite`, so IMO there is no way to go upstream with this combo. I'll keep this site-specific and perhaps make it upstream for `2019a`.

**Comment by boegel** [comment]
@jose-d Using an older version of `llvmlite` is not an option?

**Comment by jose-d** [comment]
@boegel yup, one has to use =< `0.26.0`, ([llvmlite compatibility table](https://pypi.org/project/llvmlite/0.28.0/).)

But even with the _compatible_ llvmlite the attempt to ~use~ import the lib will fail with

```
sanity check command python -c "import numba; numba.__version__" exited with code 1 (output: Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/users/jose/.local/easybuild/software/lang/numba/0.43.1-foss-2018b-Python-2.7.15/lib/python2.7/site-packages/numba/__init__.py", line 11, in <module>
    from . import config, errors, _runtests as runtests, types
  File "/home/users/jose/.local/easybuild/software/lang/numba/0.43.1-foss-2018b-Python-2.7.15/lib/python2.7/site-packages/numba/config.py", line 19, in <module>
    import llvmlite.binding as ll
  File "/home/users/jose/.local/easybuild/software/lang/numba/0.43.1-foss-2018b-Python-2.7.15/lib/python2.7/site-packages/llvmlite/binding/__init__.py", line 6, in <module>
    from .dylib import *
  File "/home/users/jose/.local/easybuild/software/lang/numba/0.43.1-foss-2018b-Python-2.7.15/lib/python2.7/site-packages/llvmlite/binding/dylib.py", line 4, in <module>
    from . import ffi
  File "/home/users/jose/.local/easybuild/software/lang/numba/0.43.1-foss-2018b-Python-2.7.15/lib/python2.7/site-packages/llvmlite/binding/ffi.py", line 128, in <module>
    raise e
OSError: /home/users/jose/.local/easybuild/software/lang/numba/0.43.1-foss-2018b-Python-2.7.15/lib/python2.7/site-packages/llvmlite/binding/libllvmlite.so: undefined symbol: LLVMInitializeInstCombine
)
```

and that's imo this bug: https://reviews.llvm.org/D44140 :

> LLVMInitializeInstCombine is declared extern "C" in the LLVM-C header Initialization.h, but not declared extern "C" surrounding the definition for the function in lib/Transforms/InstCombine/InstructionCombining.cpp.

yes, one could extract the bugfix from the 6.0.1 and apply it as a easybuild patch ... but I don't think we should invest too much time into fixing already fixed problems..

**Pull request closed without merging**
