### PR TITLE
Move all libavifs to GCCcore only, fix deps

### PR DESCRIPTION
**Pull request by Micket**
(created using `eb --new-pr`)
foss-2022a is just removed since there was already a matching gcccore version, so nothing is lost.

(I intentionally ignored the oldest one since it's gone in 5.0.x anyway)

### CODE REVIEW

**Comment by Micket** [comment]
Test report by @Micket
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in total)
alvis-skylake-build - Linux Rocky Linux 8.9, x86_64, Intel Xeon Processor (Skylake, IBRS, no TSX), Python 3.6.8
See https://gist.github.com/Micket/08a134fc9e28f1450ef2f0486b809401 for a full test report.

**Comment by Micket** [comment]
@boegelbot please test @ generoso

**Comment by verdurin** [comment]
Test report by @verdurin
**SUCCESS**
Build succeeded for 3 out of 3 (3 easyconfigs in total)
easybuild-c7.novalocal - Linux CentOS Linux 7.9.2009, x86_64, Intel Xeon Processor (Skylake, IBRS), Python 3.6.8
See https://gist.github.com/verdurin/c5589c090ce8bab90a7c10162fe1794b for a full test report.

**Review by verdurin — APPROVED** [review]
Looks fine.

**Comment by verdurin** [comment]
Going in, thanks @Micket!

**Pull request merged**
