### PR TITLE
{bio}[foss/2018b] cytosim v20190117

### PR DESCRIPTION
**Pull request by sassy-crick**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by sassy-crick** [comment]
@boegel I done the renaming of the patch files and included the `cytosim-%(version)s` changes inside the build files for the name of the patches. I did leave the comments behind the checksum though as it would get too long I feared. 
These were basically all the permutations the user requested so I thought I might as well make them available. Before I upload all of them, we could merge all of that in one file and let users comment out the features they want to use. However, I am not sure if people would understand that correctly. Let me know please.

**Comment by sassy-crick** [comment]
@boegel I done the renaming of the patch files and included the `cytosim-%(version)s` changes inside the build files for the name of the patches. I did leave the comments behind the checksum though as it would get too long I feared. 
These were basically all the permutations the user requested so I thought I might as well make them available. I merge all of them in one file and let users comment out the features they want to use.  Let me know what you think of that please.

**Comment by migueldiascosta** [comment]
@sassy-crick your last commit simply removed all the eb files

**Comment by sassy-crick** [comment]
I have uploaded the EB build file and the patch files again. I am not sure how that happened. I have slightly updated the EB build file by replacing the full name of the patch file, instead of a shorter version.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
node2400.golett.os - Linux centos linux 7.6.1810, Intel(R) Xeon(R) CPU E5-2680 v3 @ 2.50GHz, Python 2.7.5
See https://gist.github.com/fcd0303035b7c1d6a97e7e6dcc360ea0 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
node3110.skitty.os - Linux centos linux 7.6.1810, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz, Python 2.7.5
See https://gist.github.com/935c97e72afbceac5256ea180b8bc25a for a full test report.

**Comment by boegel** [comment]
Going in, thanks @sassy-crick!

**Pull request merged**
