### PR TITLE
{bio}[foss/2016a] TEToolkit v1.5.1 w/ Python 2.7.11

### PR DESCRIPTION
**Pull request by ebirn**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by verdurin** [comment]
Test report by @verdurin
**FAILED**
Build succeeded for 0 out of 20 (1 easyconfigs in this PR)
easybuild.novalocal - Linux centos linux 7.4.1708, Intel Xeon E312xx (Sandy Bridge), Python 2.7.5
See https://gist.github.com/25d62191abcb5f5ffb53e77d3d959d5f for a full test report.

**Comment by boegel** [comment]
@verdurin Hmm, the issues you're seeing don't seem related to this PR at all? The `OpenMPI` build is failing with:

```
make[2]: Entering directory `/home/centos/.local/easybuild/build/OpenMPI/1.10.2/GCC-4.9.3-2.25/openmpi-1.10.2/ompi/mca/common/verbs_usnic'
  CC       libmca_common_verbs_usnic_la-common_verbs_usnic_fake.lo
common_verbs_usnic_fake.c:72:5: error: unknown field 'ops' specified in initializer
     .ops = {
     ^
common_verbs_usnic_fake.c:73:9: error: unknown field 'alloc_context' specified in initializer
         .alloc_context = fake_alloc_context,
         ^
common_verbs_usnic_fake.c:74:9: error: unknown field 'free_context' specified in initializer
         .free_context = fake_free_context
```

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
node2025.delcatty.os - Linux centos linux 7.4.1708, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.7.5
See https://gist.github.com/f5487487466e323e3cf6ab46d3a12197 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
node2672.swalot.os - Linux centos linux 7.4.1708, Intel(R) Xeon(R) CPU E5-2660 v3 @ 2.60GHz, Python 2.7.5
See https://gist.github.com/73e8407e26d09fbe6bbf2a65682b3771 for a full test report.

**Comment by vanzod** [comment]
Going in, thanks @ebirn!

**Pull request merged**
