### PR TITLE
fix numpy tests for recent SciPy-bundle easyconfig on POWER

### PR DESCRIPTION
**Pull request by Flamefire**
(created using `eb --new-pr`)

Fixes https://github.com/easybuilders/easybuild-easyconfigs/issues/12351

### CODE REVIEW

**Comment by verdurin** [comment]
Test build works for me with `SciPy-bundle-2019.10-fosscuda-2019b-Python-3.7.4.eb`, just not able to upload a report from that node currently.

**Comment by Flamefire** [comment]
Test report by @Flamefire
**FAILED**
Build succeeded for 9 out of 11 (11 easyconfigs in total)
taurusa6 - Linux centos linux 7.7.1908, x86_64, Intel(R) Xeon(R) CPU E5-2603 v4 @ 1.70GHz (broadwell), Python 2.7.5
See https://gist.github.com/639cd1aa179edf0d04756c9a3d35c01e for a full test report.

**Comment by Flamefire** [comment]
Test report by @Flamefire
**FAILED**
Build succeeded for 16 out of 28 (11 easyconfigs in total)
taurusml24 - Linux RHEL 7.6, POWER, 8335-GTX (power9le), Python 2.7.5
See https://gist.github.com/642ab70a106eaa87b2e384f12d28db13 for a full test report.

**Comment by smoors** [comment]
@boegelbot: please test @ generoso

**Review by boegel — APPROVED** [review]
lgtm

**Comment by Flamefire** [comment]
FYI: Tests are being rerun now after fixing the patch and getting GDRcopy installed via the CUDA easyblock change. There might be a semi-expected failure on POWER and 2019a due to know issues with OpenBLAS, but lets see

**Comment by boegel** [comment]
Test reports from CentOS 7 (Haswell) and RHEL8 (Rome) coming up from my side too...

**Comment by Flamefire** [comment]
Test report by @Flamefire
**FAILED**
Build succeeded for 8 out of 11 (11 easyconfigs in total)
taurusml6 - Linux RHEL 7.6, POWER, 8335-GTX (power9le), Python 2.7.5
See https://gist.github.com/c86966bf73a709420aac13476429dedd for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**FAILED**
Build succeeded for 10 out of 11 (11 easyconfigs in total)
node3501.doduo.os - Linux RHEL 8.2, x86_64, AMD EPYC 7552 48-Core Processor (zen2), Python 3.6.8
See https://gist.github.com/80878612c4a7c57455de42a4e2cef362 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 11 out of 11 (11 easyconfigs in total)
node2609.swalot.os - Linux centos linux 7.9.2009, x86_64, Intel(R) Xeon(R) CPU E5-2660 v3 @ 2.60GHz (haswell), Python 3.6.8
See https://gist.github.com/7318a5e375377de355708dd7d99c9b6b for a full test report.

**Comment by boegel** [comment]
@boegelbot please test @ generoso
EB_ARGS="SciPy-bundle-2019.10-fosscuda-2019b-Python-2.7.16.eb"

**Comment by Flamefire** [comment]
@boegel Your `CUDA/10.1.105-GCC-8.2.0-2.31.1` might be broken.
As mentioned, the 2019a failures are kinda expected. I'd even vote to bump the OpenBLAS version for PPC for that TC
The fail with Python 2 2020a is related to https://github.com/numpy/numpy/issues/7601#issuecomment-218704015 where gcc with `-O1 -mcpu=power9` miscompiles a loop

**Comment by branfosj** [comment]
> As mentioned, the 2019a failures are kinda expected. I'd even vote to bump the OpenBLAS version for PPC for that TC
> The fail with Python 2 2020a is related to [numpy/numpy#7601 (comment)](https://github.com/numpy/numpy/issues/7601#issuecomment-218704015) where gcc with `-O1 -mcpu=power9` miscompiles a loop
> Edit: Our ECs have a patch for that issue. So this can be merged from my side (not rerunning the lengthy test for this)

We bumped our OpenBLAS version for 2019a. I think it would be sensible to do so - though I'd be fine with that being a separate PR if we are all in agreement with doing it.

I've set off test reports from our P9 of the 2019b, 2020a, and 2020b Python 3 versions.

**Comment by branfosj** [comment]
Test report by @branfosj
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in total)
bear-pg0306u07a.bear.cluster - Linux RHEL 8.3, POWER, 8335-GTX (power9le), Python 3.6.8
See https://gist.github.com/214223a13bd2ad1d620f02c87662ccba for a full test report.

**Comment by branfosj** [comment]
Test report by @branfosj
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in total)
bear-pg0306u07a.bear.cluster - Linux RHEL 8.3, POWER, 8335-GTX (power9le), Python 3.6.8
See https://gist.github.com/13da25a0c1e6b60516b5512bf697ab65 for a full test report.

**Comment by boegel** [comment]
Going in, thanks @Flamefire!

**Pull request merged**
