### PR TITLE
{bio}[GCC/10.3.0] gappa v0.7.1

### PR DESCRIPTION
**Pull request by Ghepardo**
First easyconfig for gappa.

### CODE REVIEW

**Comment by Ghepardo** [comment]
Hi, this commit has failed with:

FAIL: test_style_conformance (test.easyconfigs.styletests.StyleTest)
Check the easyconfigs for style
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test/easyconfigs/styletests.py", line 57, in test_style_conformance
    self.assertEqual(result, 0, "Found code style errors (and/or warnings): %s" % result)
AssertionError: Found code style errors (and/or warnings): 1

----------------------------------------------------------------------

However, it gives no clues as to what the style errors were!  I am at a loss to know.  Can you shed any light on this please?  It would help if this check gave a little information about the location in the file and the nature of the style errors it has found.

**Comment by boegel** [comment]
@Ghepardo The output of that check can be improved significantly, indeed...

You can check yourself using `eb --check-contrib --from-pr 13186`, here the output:

```
$ eb --check-contrib --from-pr 13186
== Temporary log file in case of crash /tmp/eb-ip1ac7r3/easybuild-uzuz62sc.log

Running style check on 1 easyconfig(s)...

/tmp/eb-ip1ac7r3/files_pr13186/g/gappa/gappa-0.7.1-GCC-10.3.0.eb:21:3: E121 continuation line under-indented for hanging indent
[FAIL] /tmp/eb-ip1ac7r3/files_pr13186/g/gappa/gappa-0.7.1-GCC-10.3.0.eb

>> One or more style checks FAILED!

Checking for SHA256 checksums in 1 easyconfig(s)...

[PASS] /tmp/eb-ip1ac7r3/files_pr13186/g/gappa/gappa-0.7.1-GCC-10.3.0.eb

>> All SHA256 checksums checks PASSed!

ERROR: One or more contribution checks FAILED!
```

**Comment by Ghepardo** [comment]
Thanks @boegel , that helps.

**Comment by verdurin** [comment]
Test report by @verdurin
**SUCCESS**
Build succeeded for 2 out of 2 (1 easyconfigs in total)
easybuild-c7.novalocal - Linux centos linux 7.9.2009, x86_64, Intel Xeon Processor (Skylake, IBRS), Python 3.6.8
See https://gist.github.com/71c853fd234c3b6e46400e61e48fcfe3 for a full test report.

**Review by verdurin — APPROVED** [review]
Looks fine.

**Comment by verdurin** [comment]
@boegelbot please test @ generoso

**Review by verdurin — APPROVED** [review]
Looks fine.

**Comment by verdurin** [comment]
Going in, thanks @Ghepardo!

**Pull request merged**
