### PR TITLE
Add poetry to builddeps to fix pyarrow version

### PR DESCRIPTION
**Pull request by pavelToman**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by pavelToman** [comment]
@boegelbot please test @ generoso

**Comment by jfgrimm** [comment]
@pavelToman is this really needed?
If you were hitting the `0.0.0` version issue, the you need to rebuild your `Python` with https://github.com/easybuilders/easybuild-easyconfigs/pull/19777, which moves `setuptools_scm` from `hatchling` to `Python`

**Comment by jfgrimm** [comment]
for more details, see also: https://github.com/easybuilders/easybuild-easyconfigs/pull/19758#issuecomment-1922078643

**Review by jfgrimm — CHANGES_REQUESTED** [review]
see comments

**Comment by pavelToman** [comment]
@boegelbot please test @ jsc-zen3

**Comment by pavelToman** [comment]
> @pavelToman is this really needed? If you were hitting the `0.0.0` version issue, the you need to rebuild your `Python` with #19777, which moves `setuptools_scm` from `hatchling` to `Python`

Ah, ok, thank you! Seems poetry helps because it has  setuptools_scm either in deps. So could you hint me please how to rebuild this Python 3.11.3 on Donphan?

**Pull request closed without merging**
