### PR TITLE
{phys}[intel/2018a] CHERAB v1.2.0 and Raysect v0.6.0 for Python/3.6.6

### PR DESCRIPTION
**Pull request by SimonPinches**
Raysect is a ray-tracing code and CHERAB is a plasma spectroscopy code built upon it.

### CODE REVIEW

**Comment by lexming** [comment]
@SimonPinches as part of the merge spring I have reviewed this PR for `Raysect` and `CHERAB`. To be able to merge it, I proceeded with the following changes:
* removed the three pairs of versions of `Raysect/CHERAB` as it is only allowed to have a single dependency per package per toolchain. I favoured the last version of CHERAB v1.2.0 depending on Raysect v0.6.0.
* moved to `intel/2018b` to fulfil the requirement on Cython >= 0.28
* fixed sanity checks and added the new parameters needed by PythonPackages in EB
I hope that you agree with this changes

**Comment by lexming** [comment]
Test report by @lexming
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in total)
node367.hydra.os - Linux centos linux 7.9.2009, x86_64, Intel(R) Xeon(R) Gold 6148 CPU @ 2.40GHz, Python 2.7.5
See https://gist.github.com/786f782649c16d6e49d1b8e380bff9c8 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in total)
node2707.swalot.os - Linux centos linux 7.9.2009, x86_64, Intel(R) Xeon(R) CPU E5-2660 v3 @ 2.60GHz (haswell), Python 3.6.8
See https://gist.github.com/a98c368d1431f1c98a4319d6efbc371d for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in total)
node3409.kirlia.os - Linux centos linux 7.9.2009, x86_64, Intel(R) Xeon(R) Gold 6240 CPU @ 2.60GHz (cascadelake), Python 3.6.8
See https://gist.github.com/42876a28c1a94b95cf230d17e67dfd96 for a full test report.

**Review by boegel — COMMENTED** [review]
lgtm

**Review by boegel — APPROVED** [review]

**Comment by boegel** [comment]
Going in, thanks @SimonPinches!

**Pull request merged**
