### PR TITLE
{lib}[fosscuda/2019a] TensorFlow v1.13.1 w/ Python 3.7.2

### PR DESCRIPTION
**Pull request by akesandgren**
(created using `eb --new-pr`)
Depends on ~~#8135~~, ~~#8190, #8189~~, ~~#8161~~, ~~#8160~~

### CODE REVIEW

**Comment by akesandgren** [comment]
Test report by @akesandgren
**SUCCESS**
Build succeeded for 3 out of 3 (1 easyconfigs in this PR)
b-an03.hpc2n.umu.se - Linux ubuntu 16.04, Intel(R) Xeon(R) CPU E5-2690 v4 @ 2.60GHz, Python 2.7.12
See https://gist.github.com/da8ee5a5a0bb8ac409e4fb4d09fe2564 for a full test report.

**Comment by akesandgren** [comment]
Can probably make this multi_deps

**Comment by akesandgren** [comment]
Can't do multi_deps of this one at the moment, we need some more features in framework first.

So time to get this merged i think

**Comment by vanzod** [comment]
Test report by @vanzod
**SUCCESS**
Build succeeded for 7 out of 7 (1 easyconfigs in this PR)
cermis - Linux debian 9.9, Intel(R) Xeon(R) CPU           X5670  @ 2.93GHz, Python 2.7.13
See https://gist.github.com/800992790486f7600caa404d08e74e97 for a full test report.

**Comment by vanzod** [comment]
Going in, thanks @akesandgren!

**Pull request merged**
