### PR TITLE
fix download URL in UDUNITS v2.2.28 easyconfigs

### PR DESCRIPTION
**Pull request by crubb**
(created using `eb --new-pr`)
Fix download URL, which now contains the version. The older versions are not on the server (anymore?)

### CODE REVIEW

**Comment by migueldiascosta** [comment]
@boegelbot please test @ generoso

**Comment by migueldiascosta** [comment]
@boegelbot please test @ jsc-zen2
EB_ARGS="--force-download"

**Comment by migueldiascosta** [comment]
Test report by @migueldiascosta
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in total)
c2dhpc - Linux CentOS Linux 7.6.1810, x86_64, AMD EPYC 7601 32-Core Processor (zen), Python 2.7.5
See https://gist.github.com/28d34fe82185fbb24f17dedeb3248bc7 for a full test report.

**Review by migueldiascosta — APPROVED** [review]
lgtm

**Comment by migueldiascosta** [comment]
@crubb so, their policy is that only the last patch version of each minor version is available? (https://artifacts.unidata.ucar.edu/service/rest/repository/browse/downloads-udunits/)

if that's the case, this patch version can also disappear in the future, so (@boegel) might as well add it now to https://sources.easybuild.io/u/UDUNITS/?

**Review by boegel — APPROVED** [review]
lgtm

**Comment by boegel** [comment]
> @crubb so, their policy is that only the last patch version of each minor version is available? (https://artifacts.unidata.ucar.edu/service/rest/repository/browse/downloads-udunits/)
> 
> if that's the case, this patch version can also disappear in the future, so (@boegel) might as well add it now to https://sources.easybuild.io/u/UDUNITS/?

Done!

**Comment by boegel** [comment]
Going in, thanks @crubb!

**Pull request merged**
