### PR TITLE
{tools}[foss/2021b] snakemake v6.10.0 w/ Python 3.9.6

### PR DESCRIPTION
**Pull request by sassy-crick**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by sassy-crick** [comment]
Requires:
- [ ] [GitPython](https://github.com/easybuilders/easybuild-easyconfigs/pull/14302)

**Comment by migueldiascosta** [comment]
@boegelbot please test @ generoso

**Review by migueldiascosta — APPROVED** [review]
lgtm

**Comment by migueldiascosta** [comment]
Going in, thanks @sassy-crick!

**Pull request merged**
