### PR TITLE
{math}[foss/2022b] Pyomo v6.5.0 w/ Python 3.10.8

### PR DESCRIPTION
**Pull request by sassy-crick**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by sassy-crick** [comment]
@boegelbot please test @ generoso

**Review by Micket — CHANGES_REQUESTED** [review]
I think this needs mpi4py dependency (now that scipy-bundle split off into gfbf land)

**Comment by sassy-crick** [comment]
> mpi4py

Done. How did you spot that?

**Comment by Micket** [comment]
Test report by @Micket
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
vera-c1 - Linux Rocky Linux 8.6, x86_64, Intel Xeon Processor (Skylake), Python 3.6.8
See https://gist.github.com/Micket/2763a499a19e7661c7083e974d21b64b for a full test report.

**Comment by Micket** [comment]
Going in, thanks @sassy-crick!

**Pull request merged**
