### PR TITLE
fix linker errors when linking with libths.a for MetaBAT 2.12.1

### LINKED ISSUE #8933: MetaBAT installation failure because libhts.a required -lcurl (which requires -lssl)
The installation of `MetaBAT-2.12.1-foss-2018b-Python-2.7.15.eb` got broken due to adding `cURL` as dependency to `SAMtools` (cfr. #8131), since `libhts.a` (provided by `SAMtools`) now required also linking with `-lcurl`, which in turns requires additional libraries to be linked in (`-lopenssl` & co).

Problem manifests as `undefined reference` error for `samtools/lib/libhts.a`:

```
samtools/lib/libhts.a(hfile_libcurl.o):hfile_libcurl.c:function easy_errno: error: undefined reference to 'curl_easy_getinfo'
samtools/lib/libhts.a(hfile_libcurl.o):hfile_libcurl.c:function easy_errno: error: undefined reference to 'curl_easy_getinfo'
samtools/lib/libhts.a(hfile_libcurl.o):hfile_libcurl.c:function wait_perform: error: undefined reference to 'curl_multi_fdset'
```

It's not a simple as just adding `curl` to the list of libraries included in the patch file, since:

```
$ pkg-config --libs --static libcurl
-L/user/gent/400/vsc40023/eb_scratch/CO7/haswell-ib/software/cURL/7.60.0-GCCcore-7.3.0/lib -lcurl -lssl -lcrypto -lssl -lcrypto -lz -lm -lpthread
```

@SethosII Any idea if we can do a better job with `libhts.a`, by "baking in" the libraries it requires (and moving `cURL` and maybe more to `builddependencies` for SAMtools)?

### PR DESCRIPTION
**Pull request by boegel**
fixes #8933

### CODE REVIEW

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
generoso - Linux centos linux 7.6.1810, Intel(R) Xeon(R) CPU E5-2660 v4 @ 2.00GHz, Python 3.6.8
See https://gist.github.com/a8fd47148ca898406d3fd7aa37147fb5 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
node2419.golett.os - Linux centos linux 7.7.1908, Intel(R) Xeon(R) CPU E5-2680 v3 @ 2.50GHz, Python 2.7.5
See https://gist.github.com/6dd0d5651833a3b5b84522965a34cd77 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
node3158.skitty.os - Linux centos linux 7.7.1908, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz, Python 3.6.8
See https://gist.github.com/b25bdc39518d194ef56d96936e2c84a7 for a full test report.

**Comment by verdurin** [comment]
Test report by @verdurin
**SUCCESS**
Build succeeded for 3 out of 3 (1 easyconfigs in this PR)
easybuild.novalocal - Linux centos linux 7.7.1908, Intel Xeon Processor (Skylake, IBRS), Python 2.7.5
See https://gist.github.com/1c378e8cc4def5853f85f9d2a216903e for a full test report.

**Comment by boegel** [comment]
(close + re-open to re-trigger Travis test, seems like notification didn't make it back to GitHub)

**Comment by verdurin** [comment]
Going in, thanks @boegel!

**Pull request merged**
