### PR TITLE
{devel}[fosscuda/2018b] GConf v3.2.6

### PR DESCRIPTION
**Pull request by akesandgren**
(created using `eb --new-pr`)
Depends on ~~https://github.com/easybuilders/easybuild-easyconfigs/pull/7658~~

### CODE REVIEW

**Comment by akesandgren** [comment]
Test report by @akesandgren
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
b-an03.hpc2n.umu.se - Linux ubuntu 16.04, Intel(R) Xeon(R) CPU E5-2690 v4 @ 2.60GHz, Python 2.7.12
See https://gist.github.com/edbee4a947637d90c5a15cfbb1f1bf5b for a full test report.

**Comment by boegel** [comment]
kicking Travis...

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 2 out of 2 (1 easyconfigs in this PR)
node3116.skitty.os - Linux centos linux 7.6.1810, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz, Python 2.7.5
See https://gist.github.com/f6b566ba1976ff7ab7078318063788e4 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
node2402.golett.os - Linux centos linux 7.6.1810, Intel(R) Xeon(R) CPU E5-2680 v3 @ 2.50GHz, Python 2.7.5
See https://gist.github.com/ba40c2229a8a9bc405bc61b80a24de61 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 2 out of 2 (1 easyconfigs in this PR)
node2098.delcatty.os - Linux centos linux 7.6.1810, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.7.5
See https://gist.github.com/87cb2de3d27d3d8c29cdc8c5ec8a5aa1 for a full test report.

**Comment by akesandgren** [comment]
Ignore this for the time being, it should be moved down to GCC or GCCcore level.

**Comment by boegel** [comment]
deprecated toolchain, and we already have `GConf` easyconfigs merged that use `GCCcore` as toolchain, so closing this...

**Pull request closed without merging**
