### PR TITLE
{data}[intel/2018b] NCL v6.6.2 + deps

### PR DESCRIPTION
**Pull request by smoors**
(created using `eb --new-pr`)

depends on ~~#7968~~

### CODE REVIEW

**Comment by migueldiascosta** [comment]
closing and reopening to trigger travis

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 7 out of 7 (6 easyconfigs in this PR)
node3103.skitty.os - Linux centos linux 7.6.1810, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz, Python 2.7.5
See https://gist.github.com/f196e0b86dab2b4ef587589422cc8db5 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 9 out of 9 (6 easyconfigs in this PR)
node2046.delcatty.os - Linux centos linux 7.6.1810, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.7.5
See https://gist.github.com/9425d001d2384e89d03a4e6d085ac994 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 6 out of 6 (6 easyconfigs in this PR)
node2406.golett.os - Linux centos linux 7.6.1810, Intel(R) Xeon(R) CPU E5-2680 v3 @ 2.50GHz, Python 2.7.5
See https://gist.github.com/f7cf833caf3527387ab5a405c2c4c703 for a full test report.

**Comment by boegel** [comment]
Going in, thanks @smoors!

**Pull request merged**
