### PR TITLE
Change 'rstudio' name to 'RStudio-Server' to agree with official name and better reflect what it provides

### PR DESCRIPTION
**Pull request by ocaisa**
This more accurately reflects what is actually being installed

### CODE REVIEW

**Comment by ocaisa** [comment]
Test reports on the way

**Comment by ocaisa** [comment]
Test report by @ocaisa
**FAILED**
Build succeeded for 3 out of 7 (4 easyconfigs in total)
generoso - Linux centos linux 8.2.2004, x86_64, Intel(R) Xeon(R) CPU E5-2667 v3 @ 3.20GHz, Python 3.6.8
See https://gist.github.com/86d321259e706f481caaee477134585b for a full test report.

**Comment by ocaisa** [comment]
Test report by @ocaisa
**FAILED**
Build succeeded for 2 out of 4 (4 easyconfigs in total)
generoso - Linux centos linux 8.2.2004, x86_64, Intel(R) Xeon(R) CPU E5-2667 v3 @ 3.20GHz, Python 3.6.8
See https://gist.github.com/eb56195ec169b48d623bd234b86549fb for a full test report.

**Comment by ocaisa** [comment]
Test report by @ocaisa
**SUCCESS**
Build succeeded for 3 out of 3 (3 easyconfigs in total)
generoso - Linux centos linux 8.2.2004, x86_64, Intel(R) Xeon(R) CPU E5-2667 v3 @ 3.20GHz, Python 3.6.8
See https://gist.github.com/7ab7df101a3926b44f06f637aea3ff3f for a full test report.

**Comment by ocaisa** [comment]
I can't do the test for fosscuda because R requires `libcuda.so` to be available during the build (and it's not on generoso) but the changes there are identical to the foss version anyway

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
node3307.joltik.os - Linux centos linux 7.8.2003, x86_64, Intel(R) Xeon(R) Gold 6242 CPU @ 2.80GHz (cascadelake), Python 3.6.8
See https://gist.github.com/00afb8dccff41df3429d61e156d3b27c for a full test report.

**Review by boegel — APPROVED** [review]
lgtm

**Comment by boegel** [comment]
Going in, thanks @ocaisa!

**Pull request merged**
