### PR TITLE
add missMDA extension to R-bundle-CRAN 2023.12

### PR DESCRIPTION
**Pull request by pavelToman**
resolves https://github.com/vscentrum/vsc-software-stack/issues/374

### CODE REVIEW

**Comment by pavelToman** [comment]
@boegelbot please test @ generoso

**Comment by boegel** [comment]
@boegelbot please test @ jsc-zen3
EB_ARGS="--skip"

**Comment by boegel** [comment]
More info on failing sanity check for `renv` (which, at first sight, has nothing to do with the changes being made here, but maybe there's a side effect of some sort):
```
== 2024-08-13 11:06:53,549 build_log.py:171 ERROR EasyBuild crashed with an error (at easybuild/easybuild-framework/easybuild/base/exceptions.py:126 in __init__): Sanity check failed: extensions sanity check failed for 1 extensions: renv
failing sanity check for 'renv' extension: command "R -q --no-save" (stdin: "pkgver = packageVersion('renv'); if (pkgver != '1.0.3')  { stop('renv 1.0.3 not installed, found ', pkgver, ' instead') }") failed; output:
> pkgver = packageVersion('renv'); if (pkgver != '1.0.3')  { stop('renv 1.0.3 not installed, found ', pkgver, ' instead') }
Error: renv 1.0.3 not installed, found 1.0.7.9000 instead
```

**Comment by branfosj** [comment]
`renv` `1.07.900` is the latest development version - so not a released version?!

**Comment by boegel** [comment]
Somehow it got installed in the home directory of the bot:
```
[boegelbot@jsczen3l1 ~]$ grep Version /home/boegelbot/R/x86_64-pc-linux-gnu-library/4.3/renv/DESCRIPTION
Version: 1.0.7.9000
```

It looks like this was triggered somehow on 31 July 2024 (so I know it wasn't me):
```
[boegelbot@jsczen3l1 ~]$ ls -ld /home/boegelbot/R/x86_64-pc-linux-gnu-library/*/*
drwxr-xr-x. 11 boegelbot boegelbot  179 Jul 31 11:11 /home/boegelbot/R/x86_64-pc-linux-gnu-library/4.3/digest
drwxr-xr-x.  8 boegelbot boegelbot  153 Jul 31 11:11 /home/boegelbot/R/x86_64-pc-linux-gnu-library/4.3/purrr
drwxr-xr-x. 12 boegelbot boegelbot 4096 May 27 21:42 /home/boegelbot/R/x86_64-pc-linux-gnu-library/4.3/renv
drwxr-xr-x. 10 boegelbot boegelbot 4096 Jul 31 11:11 /home/boegelbot/R/x86_64-pc-linux-gnu-library/4.3/rmarkdown
drwxr-xr-x. 11 boegelbot boegelbot 4096 Jul 31 11:11 /home/boegelbot/R/x86_64-pc-linux-gnu-library/4.3/testthat
drwxr-xr-x. 10 boegelbot boegelbot  183 Jul 31 11:11 /home/boegelbot/R/x86_64-pc-linux-gnu-library/4.3/xml2
drwxr-xr-x.  8 boegelbot boegelbot  190 Jul 31 11:11 /home/boegelbot/R/x86_64-pc-linux-gnu-library/4.3/yaml
````

I've removed all of these, and did a `chmod 000` on `/home/boegelbot/R/x86_64-pc-linux-gnu-library`.

**Comment by boegel** [comment]
@boegelbot please test @ jsc-zen3
EB_ARGS="--skip"

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
node3103.skitty.os - Linux RHEL 8.8, x86_64, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz, Python 3.6.8
See https://gist.github.com/boegel/94847818104502c23fa564151da8bc4e for a full test report.

**Comment by branfosj** [comment]
> Somehow it got installed in the home directory of the bot:
> 
> ```
> [boegelbot@jsczen3l1 ~]$ grep Version /home/boegelbot/R/x86_64-pc-linux-gnu-library/4.3/renv/DESCRIPTION
> Version: 1.0.7.9000
> ```
> 
> It looks like this was triggered somehow on 31 July 2024 (so I know it wasn't me):
> 
> ```
> [boegelbot@jsczen3l1 ~]$ ls -ld /home/boegelbot/R/x86_64-pc-linux-gnu-library/*/*
> drwxr-xr-x. 11 boegelbot boegelbot  179 Jul 31 11:11 /home/boegelbot/R/x86_64-pc-linux-gnu-library/4.3/digest
> drwxr-xr-x.  8 boegelbot boegelbot  153 Jul 31 11:11 /home/boegelbot/R/x86_64-pc-linux-gnu-library/4.3/purrr
> drwxr-xr-x. 12 boegelbot boegelbot 4096 May 27 21:42 /home/boegelbot/R/x86_64-pc-linux-gnu-library/4.3/renv
> drwxr-xr-x. 10 boegelbot boegelbot 4096 Jul 31 11:11 /home/boegelbot/R/x86_64-pc-linux-gnu-library/4.3/rmarkdown
> drwxr-xr-x. 11 boegelbot boegelbot 4096 Jul 31 11:11 /home/boegelbot/R/x86_64-pc-linux-gnu-library/4.3/testthat
> drwxr-xr-x. 10 boegelbot boegelbot  183 Jul 31 11:11 /home/boegelbot/R/x86_64-pc-linux-gnu-library/4.3/xml2
> drwxr-xr-x.  8 boegelbot boegelbot  190 Jul 31 11:11 /home/boegelbot/R/x86_64-pc-linux-gnu-library/4.3/yaml
> ```
> 
> I've removed all of these, and did a `chmod 000` on `/home/boegelbot/R/x86_64-pc-linux-gnu-library`.
> 
> edit: very similar situation also on `generoso`, also cleaned it up:
> 
> ```
> [boegelbot@login1 ~]$ ls -lrtd R/x86_64-pc-linux-gnu-library/*/*
> drwxrwxr-x. 12 boegelbot boegelbot 4.0K May 27 16:23 R/x86_64-pc-linux-gnu-library/4.3/renv
> drwxrwxr-x. 11 boegelbot boegelbot 4.0K Jul 29 14:18 R/x86_64-pc-linux-gnu-library/4.3/digest
> drwxrwxr-x.  8 boegelbot boegelbot 4.0K Jul 29 14:18 R/x86_64-pc-linux-gnu-library/4.3/purrr
> drwxrwxr-x.  8 boegelbot boegelbot 4.0K Jul 29 14:18 R/x86_64-pc-linux-gnu-library/4.3/yaml
> drwxrwxr-x. 10 boegelbot boegelbot 4.0K Jul 29 14:18 R/x86_64-pc-linux-gnu-library/4.3/rmarkdown
> drwxrwxr-x. 11 boegelbot boegelbot 4.0K Jul 29 14:19 R/x86_64-pc-linux-gnu-library/4.3/testthat
> drwxrwxr-x. 10 boegelbot boegelbot 4.0K Jul 29 14:19 R/x86_64-pc-linux-gnu-library/4.3/xml2
> [boegelbot@login1 ~]$ grep Version R/x86_64-pc-linux-gnu-library/4.3/renv/DESCRIPTION
> Version: 1.0.7.9000
> ```

RStudio-Server installs. Specifically #21086 and #20060

In those we have `./install-packages` and the [packages installed](https://github.com/rstudio/rstudio/blob/main/dependencies/common/install-packages#L23) are: 
```
  digest
  purrr
  rmarkdown
  testthat
  xml2
  yaml
```
and further down that we see `renv` being installed.

**Comment by boegel** [comment]
@boegelbot please test @ generoso
EB_ARGS="--skip"

**Review by boegel — APPROVED** [review]
lgtm

**Comment by boegel** [comment]
Going in, thanks @pavelToman!

**Pull request merged**
