### PR TITLE
{devel}[GCCcore/12.2.0] pydantic v2.5.3, Rust v1.75.0, maturin v1.4.0 w/ Rust 1.75.0

### PR DESCRIPTION
**Pull request by boegel**
(created using `eb --new-pr`)
requires:
* #19510

I tried to avoid introducing another `Rust` version with `GCCcore/12.2.0`, but that proved pretty much impossible due to the crates required by `pydantic-core` requiring a very recent Rust version.
I tried going back to old `pydantic-core` versions, and gave up when I was hitting `0.x` versions...

Since `Rust` & `maturin` are only a build dependency, that shouldn't be too much of a problem.

### CODE REVIEW

**Comment by boegel** [comment]
@boegelbot please test @ generoso
CORE_CNT16

**Comment by boegel** [comment]
@boegelbot please test @ jsc-zen2
CORE_CNT=16

**Comment by boegel** [comment]
@boegelbot please test @ jsc-zen2

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 3 out of 3 (3 easyconfigs in total)
node3123.skitty.os - Linux RHEL 8.8, x86_64, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz (skylake_avx512), Python 3.6.8
See https://gist.github.com/boegel/233ef3da5afea9e474172bc59d60dda3 for a full test report.

**Comment by boegel** [comment]
@akesandgren Should be ready to merge now...

**Review by smoors — APPROVED** [review]
lgtm

**Comment by smoors** [comment]
Going in, thanks @boegel!

**Pull request merged**
