### PR TITLE
{base}[foss/2017b] Gerris v20131206, GTS v20121130

### PR DESCRIPTION
**Pull request by dquigley-warwick**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by dquigley-warwick** [comment]
Test report by @dquigley-warwick
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in this PR)
cedar.theory.warwick.ac.uk - Linux centos linux 7.5.1804, Intel(R) Core(TM)2 Quad CPU    Q8400  @ 2.66GHz, Python 2.7.5
See https://gist.github.com/65379e4384e54572d96819d6433077cc for a full test report.

**Comment by verdurin** [comment]
Test report by @verdurin
**SUCCESS**
Build succeeded for 8 out of 8 (2 easyconfigs in this PR)
rescomp2 - Linux centos linux 7.3.1611, Intel(R) Xeon(R) Gold 6126 CPU @ 2.60GHz, Python 2.7.11
See https://gist.github.com/ba734b84aa2b8a1d38964296b393e93b for a full test report.

**Comment by verdurin** [comment]
@dquigley-warwick thanks for the PR. 

Could you explain why you have removed the `GLib` dependency?

Thanks,
Adam

**Comment by dquigley-warwick** [comment]
@verdurin - that may not have been entirely deliberate. Presumably including that dependency would allow building on older systems? I've only tested on CentOS 7.3 as above.

David

**Comment by verdurin** [comment]
@dquigley-warwick - the concern would be that when you built it locally, it picked up a system package that might not be installed by everyone.

**Comment by dquigley-warwick** [comment]
Test report by @dquigley-warwick
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in this PR)
cedar.theory.warwick.ac.uk - Linux centos linux 7.5.1804, Intel(R) Core(TM)2 Quad CPU    Q8400  @ 2.66GHz, Python 2.7.5
See https://gist.github.com/16dab3ae75a9c55d412afc8741eda082 for a full test report.

**Comment by verdurin** [comment]
Test report by @verdurin
**SUCCESS**
Build succeeded for 0 out of 0 (2 easyconfigs in this PR)
rescomp2 - Linux centos linux 7.3.1611, Intel(R) Xeon(R) Gold 6126 CPU @ 2.60GHz, Python 2.7.11
See https://gist.github.com/541129b263f62af7e00fa9628fa511f8 for a full test report.

**Comment by verdurin** [comment]
Test report by @verdurin
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in this PR)
easybuild.novalocal - Linux centos linux 7.5.1804, Intel Xeon E312xx (Sandy Bridge), Python 2.7.5
See https://gist.github.com/6fd71b1854717bbbebc8a7956ccc74d8 for a full test report.

**Comment by verdurin** [comment]
Going in, thanks @dquigley-warwick!

**Pull request merged**
