### PR TITLE
Update R-4.1.2-foss-2021b.eb: update checksum of external packages - MASS, class, nnet, spatial

### PR DESCRIPTION
**Pull request by SIB-software**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by robinengler** [comment]
Note: this is the same fix as in https://github.com/easybuilders/easybuild-easyconfigs/pull/14873

**Comment by lexming** [comment]
@boegelbot: please test @ generoso
EB_ARGS="--stop=fetch"

**Comment by lexming** [comment]
Test report by @lexming
**SUCCESS**
Build succeeded for 26 out of 26 (1 easyconfigs in total)
node300.hydra.os - Linux centos linux 7.9.2009, x86_64, Intel(R) Xeon(R) Gold 6148 CPU @ 2.40GHz, Python 2.7.5
See https://gist.github.com/844883e48c94a8125dd021781536d85e for a full test report.

**Review by lexming — APPROVED** [review]
My test re-downloaded all sources.

LGTM

**Comment by lexming** [comment]
Going in, thanks @SIB-software !

**Pull request merged**
