### PR TITLE
remove etc/turbovncserver-security.conf from TurboVNC installation to avoid errors w.r.t. ownership of that file

### PR DESCRIPTION
**Pull request by boegel**

### CODE REVIEW

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
node3111.skitty.os - Linux centos linux 7.6.1810, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz, Python 3.6.8
See https://gist.github.com/3b42863c912de79f0fd09bd79590a4c9 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
node2655.swalot.os - Linux centos linux 7.6.1810, Intel(R) Xeon(R) CPU E5-2660 v3 @ 2.60GHz, Python 2.7.5
See https://gist.github.com/2e7d75f773afd6d8f371384f555b934f for a full test report.

**Comment by migueldiascosta** [comment]
Test report by @migueldiascosta
**FAILED**
Build succeeded for 0 out of 1 (1 easyconfigs in this PR)
generoso - Linux centos linux 7.6.1810, Intel(R) Xeon(R) CPU E5-2660 v4 @ 2.00GHz, Python 3.6.8
See https://gist.github.com/02c2cf882318353f9a9b9a4c11832106 for a full test report.

**Comment by boegel** [comment]
@migueldiascosta Do you have `pam-devel` installed?

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
node2070.delcatty.os - Linux centos linux 7.6.1810, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.7.5
See https://gist.github.com/fbc3c64652ab2f0ebc0f0fe46d35ad75 for a full test report.

**Comment by migueldiascosta** [comment]
@boegel yep (the test report is from `generoso`)

seems to be graphics related:

```
fatal error: GL/internal/dri_interface.h: No such file or directory
```

**Comment by boegel** [comment]
@migueldiascosta Hmm, looks like something is missing in `Mesa` perhaps: http://lists.openembedded.org/pipermail/openembedded-core/2011-October/050150.html

**Comment by boegel** [comment]
@migueldiascosta The issue with the missing `dri_interface.h` header file is fixed with the changes to `Mesa` made in #9129

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
generoso - Linux centos linux 7.6.1810, Intel(R) Xeon(R) CPU E5-2660 v4 @ 2.00GHz, Python 3.6.8
See https://gist.github.com/e2e3b3de3ad17b4067e3928ae7e47894 for a full test report.

**Comment by migueldiascosta** [comment]
Test report by @migueldiascosta
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
generoso - Linux centos linux 7.6.1810, Intel(R) Xeon(R) CPU E5-2660 v4 @ 2.00GHz, Python 3.6.8
See https://gist.github.com/3aa44c03abd87a491abb298e44bfafa8 for a full test report.

**Comment by migueldiascosta** [comment]
test report is on top of #9129

**Pull request merged**
