### PR TITLE
{lib}[GCCcore/13.3.0] utf8proc v2.9.0

### PR DESCRIPTION
**Pull request by lcniel**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by lcniel** [comment]
Test report by @lcniel
**FAILED**
Failed during parsing of the easyconfigs, so no ecs were built (1 easyconfigs in total)
vera10-1 - Linux Rocky Linux 8.9, x86_64, Intel(R) Xeon(R) Gold 6130 CPU @ 2.10GHz, Python 3.6.8
See https://gist.github.com/lcniel/d2748389dae186a3db9bbdff58ec2f74 for a full test report.

**Comment by lcniel** [comment]
Test report by @lcniel
**FAILED**
Failed during parsing of the easyconfigs, so no ecs were built (1 easyconfigs in total)
vera32-4 - Linux Rocky Linux 8.9, x86_64, Intel(R) Xeon(R) Gold 6130 CPU @ 2.10GHz, Python 3.6.8
See https://gist.github.com/lcniel/ad807fbb43b7333e16650ae6e8608683 for a full test report.

**Comment by lcniel** [comment]
Test report by @lcniel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
vera20-1 - Linux Rocky Linux 8.9, x86_64, Intel(R) Xeon(R) Gold 6130 CPU @ 2.10GHz, Python 3.6.8
See https://gist.github.com/lcniel/46181beffd159ddc346cbd81ef89f6e9 for a full test report.

**Comment by jfgrimm** [comment]
@boegelbot: please test @ generoso

**Comment by jfgrimm** [comment]
Test report by @jfgrimm
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
node099.viking2.yor.alces.network - Linux Rocky Linux 8.9, x86_64, AMD EPYC 7643 48-Core Processor, Python 3.6.8
See https://gist.github.com/jfgrimm/da9dd1995ecd31e3d3c1462421363806 for a full test report.

**Comment by jfgrimm** [comment]
@boegelbot: please test @ jsc-zen3

**Review by jfgrimm — APPROVED** [review]

**Comment by jfgrimm** [comment]
Going in, thanks @lcniel!

**Pull request merged**
