### PR TITLE
{phys}[intel/2020a] Siesta v4.1.5

### PR DESCRIPTION
**Pull request by dithwick**
(created using `eb --new-pr`)

depends on ~easybuilders/easybuild-easyblocks#2553~

### CODE REVIEW

**Comment by SebastianAchilles** [comment]
@boegelbot please test @ generoso
EB_ARGS="--include-easyblocks-from-pr 2553"

**Comment by migueldiascosta** [comment]
@boegelbot please test @ generoso
EB_ARGS="--include-easyblocks-from-pr 2553"

**Comment by migueldiascosta** [comment]
@boegelbot please test @ generoso
EB_ARGS="--include-easyblocks-from-pr 2553"

**Comment by SebastianAchilles** [comment]
@boegelbot please test @ generoso

**Review by SebastianAchilles — APPROVED** [review]
lgtm

**Comment by SebastianAchilles** [comment]
@boegelbot please test @ generoso

**Comment by SebastianAchilles** [comment]
Test report by @sebastianachilles
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
skylake-alma8-eb - Linux AlmaLinux 8.5, x86_64, Intel(R) Core(TM) i7-8700 CPU @ 3.20GHz (skylake), Python 3.6.8
See https://gist.github.com/2ea3bc5fc7a2dfbfa5aeb818cc2c195c for a full test report.

**Comment by SebastianAchilles** [comment]
@boegelbot please test @ generoso
CORE_CNT=16

**Comment by SebastianAchilles** [comment]
@boegelbot: please test @ generoso
EB_ARGS="--ignore-locks"
CORE_CNT=16

**Comment by SebastianAchilles** [comment]
The test on `generoso` hangs in `make check` and runs into the wall time limit of the job.

**Comment by akesandgren** [comment]
Test report by @akesandgren
**FAILED**
Build succeeded for 0 out of 2 (1 easyconfigs in total)
b-an02.hpc2n.umu.se - Linux Ubuntu 20.04, x86_64, Intel(R) Xeon(R) CPU E5-2690 v4 @ 2.60GHz, Python 3.8.10
See https://gist.github.com/e40402670f8ae758ff6375591a04b3af for a full test report.

**Comment by akesandgren** [comment]
I can't even build the ELPA it depends on for some reason....

**Comment by akesandgren** [comment]
Test report by @akesandgren
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
b-an02.hpc2n.umu.se - Linux Ubuntu 20.04, x86_64, Intel(R) Xeon(R) CPU E5-2690 v4 @ 2.60GHz, Python 3.8.10
See https://gist.github.com/c08112982028e1dcd8820602f18f2777 for a full test report.

**Comment by migueldiascosta** [comment]
Test report by @migueldiascosta
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
c2dhpc - Linux CentOS Linux 7.6.1810, x86_64, AMD EPYC 7601 32-Core Processor (zen), Python 2.7.5
See https://gist.github.com/43a75773f7dfb21e022ee4983d099fbc for a full test report.

**Comment by akesandgren** [comment]
@boegelbot: please test @ generoso
EB_ARGS="--ignore-locks"
CORE_CNT=2

**Review by akesandgren — APPROVED** [review]
LGTM

**Comment by akesandgren** [comment]
Going in, thanks @dithwick!

**Pull request merged**
