### PR TITLE
Stripy-2.1.0-foss-2021a

### PR DESCRIPTION
**Pull request by ysagon**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by ysagon** [comment]
Hi, @jfgrimm I'm not sure what to do next. The issue seems to be in netcdf4-python-1.5.7-foss-2021a.eb, already merged.

**Comment by jfgrimm** [comment]
@boegelbot please test @ generoso

**Comment by jfgrimm** [comment]
Test report by @jfgrimm
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
node029.pri.viking.alces.network - Linux CentOS Linux 7.9.2009, x86_64, Intel(R) Xeon(R) Gold 6138 CPU @ 2.00GHz (skylake_avx512), Python 3.6.8
See https://gist.github.com/b6991886250836b4884e54e7407da0f1 for a full test report.

**Comment by jfgrimm** [comment]
@boegelbot please test @ jsc-zen2

**Review by jfgrimm — APPROVED** [review]
LGTM

**Comment by jfgrimm** [comment]
Going in, thanks @ysagon!

**Pull request merged**
