### PR TITLE
{lang}[GCCcore/13.2.0] Perl-bundle-CPAN v5.38.0

### PR DESCRIPTION
**Pull request by Micket**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by Micket** [comment]
@boegelbot please test @ generoso

**Comment by Micket** [comment]
Test report by @Micket
**FAILED**
Build succeeded for 0 out of 1 (1 easyconfigs in total)
alvis-c1 - Linux Rocky Linux 8.8, x86_64, Intel Xeon Processor (Skylake), Python 3.6.8
See https://gist.github.com/Micket/f7424c749715b10dce4d7c78cd94fb19 for a full test report.

**Comment by Micket** [comment]
Well at least it made it through 146 extensions before another cryptic mess.. it actually fails the test suite for Test:Differences
```
#   Failed test 'sanity check: 1 and !!1 are Data::Dumper-ly different on this perl'
#   at t/bools.t line 32.
#          got: '1
# '
#     expected: anything else
```
uh..
I hate perl.

**Comment by boegel** [comment]
@Micket https://github.com/DrHyde/perl-modules-Test-Differences/issues/21 looks related (maybe?)

Seems like we can ask about these failing tests there, in any case...

**Comment by Micket** [comment]
> @Micket [DrHyde/perl-modules-Test-Differences#21](https://github.com/DrHyde/perl-modules-Test-Differences/issues/21) looks related (maybe?)
> 
> Seems like we can ask about these failing tests there, in any case...

I just skipped that test suite for now at least

**Comment by Micket** [comment]
@boegelbot please test @ generoso

**Comment by Micket** [comment]
Test report by @Micket
**FAILED**
Build succeeded for 0 out of 1 (1 easyconfigs in total)
alvis-c1 - Linux Rocky Linux 8.8, x86_64, Intel Xeon Processor (Skylake), Python 3.6.8
See https://gist.github.com/Micket/b9763fd1efb161227b2300fe646d7774 for a full test report.

**Comment by Micket** [comment]
@boegelbot please test @ generoso
EB_ARGS="--skip"

**Comment by Micket** [comment]
Test report by @Micket
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
alvis-c1 - Linux Rocky Linux 8.8, x86_64, Intel Xeon Processor (Skylake), Python 3.6.8
See https://gist.github.com/Micket/c17095ba4094a6ed382694a5cb2037b9 for a full test report.

**Comment by Micket** [comment]
@boegelbot please test @ jsc-zen2

**Review by boegel — APPROVED** [review]
lgtm

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
node3100.skitty.os - Linux RHEL 8.8, x86_64, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz (skylake_avx512), Python 3.6.8
See https://gist.github.com/boegel/39b580b8ab0946ff01d225794e644f04 for a full test report.

**Comment by SebastianAchilles** [comment]
Test report by @sebastianachilles
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
zen2-ubuntu-2310 - Linux Ubuntu 23.10 (Mantic Minotaur), x86_64, AMD EPYC 7452 32-Core Processor (zen2), Python 3.11.6
See https://gist.github.com/SebastianAchilles/f34d05637dea4d4ba0e744b4991dcb1b for a full test report.

**Comment by boegel** [comment]
Going in, thanks @Micket!

**Pull request merged**
