### PR TITLE
use system architecture template in GD

### PR DESCRIPTION
**Pull request by SebastianAchilles**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by SebastianAchilles** [comment]
Test report by @sebastianachilles
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
jrc0870.jureca - Linux Rocky Linux 8.9, AArch64, ARM UNKNOWN (neoverse_n1), 2 x NVIDIA NVIDIA A100-PCIE-40GB, 535.154.05, Python 3.6.8
See https://gist.github.com/SebastianAchilles/727b397fd5a861549e477dbfcf396d3e for a full test report.

**Comment by Micket** [comment]
@boegelbot please test @ generoso
EB_ARGS="GD-2.75-GCCcore-11.3.0.eb"

**Review by Micket — APPROVED** [review]
lgtm

**Comment by Micket** [comment]
Going in, thanks @SebastianAchilles!

**Pull request merged**
