### PR TITLE
{phys}[foss/2021b,foss/2022a] BerkeleyGW v3.0.1 w/ Python 3.10.4 + 3.9.6 (WIP)

### PR DESCRIPTION
**Pull request by migueldiascosta**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by migueldiascosta** [comment]
@boegelbot please test @ generoso EB_ARGS="--include-easyblocks-from-pr 2836"

**Comment by migueldiascosta** [comment]
@boegelbot please test @ jsc-zen2 EB_ARGS="--include-easyblocks-from-pr 2836"

**Review by lexming — COMMENTED** [review]
@migueldiascosta the download link is not working. I can manually download the sources from https://berkeleygw.org/download/ though

**Comment by migueldiascosta** [comment]
@lexming yeah, they keep changing it and the direct link is not always clear

@boegel can we add the sources to `sources.easybuild.io`, as previously discussed? License should allow it

**Comment by migueldiascosta** [comment]
@boegelbot please test @ jsc-zen2

**Comment by migueldiascosta** [comment]
@boegelbot please test @ jsc-zen2

**Comment by migueldiascosta** [comment]
@boegelbot please test @ generoso

**Comment by migueldiascosta** [comment]
@boegelbot please test @ jsc-zen2 CORE_CNT=16 EB_ARGS="--parallel=8"

**Comment by migueldiascosta** [comment]
@boegelbot please test @ jsc-zen2 CORE_CNT=16 EB_ARGS="--include-easyblocks-from-pr=2950"

**Comment by migueldiascosta** [comment]
@boegelbot please test @ generoso EB_ARGS="--include-easyblocks-from-pr=2950"

**Comment by migueldiascosta** [comment]
had forgotten to document this: from the full logs collected by @boegel, 2 or 3 tests are failing on `jsc-zen2` with 

```
[jsczen2c1:678012:0:678012] Caught signal 11 (Segmentation fault: invalid permissions for mapped object at address 0x15211eb67ae0)
==== backtrace (tid: 678012) ====
 0 0x0000000000012c20 __funlockfile()  :0
 1 0x00000000003dfcc0 zgemv_n()  ???:0
 2 0x00000000000cfc68 zgemv_()  ???:0
 3 0x000000000099e46b zlatrd_()  ???:0
 4 0x000000000091e5a7 zhetrd_()  ???:0
 5 0x000000000091670d zheevx_()  ???:0
 6 0x0000000000516e76 __diagonalize_m_MOD_diagonalize()  ???:0
 7 0x000000000051021d __diag_m_MOD_diag()  ???:0
 8 0x000000000040be83 main()  ???:0
 9 0x0000000000023493 __libc_start_main()  ???:0
10 0x000000000040c05e _start()  ???:0
=================================

Program received signal SIGSEGV: Segmentation fault - invalid memory reference.
```

but I can't seem to reproduce it elsewhere nor get around it on `jsc-zen2`... 

would appreciate test reports from other systems, to see if the `jsc-zen2` is the exception or the rule

(tests from `generoso` never seem to come back...)

**Comment by migueldiascosta** [comment]
closing in favour of #19478

**Pull request closed without merging**
