### PR TITLE
{bio}[system/system] CellRanger v5.0.0

### PR DESCRIPTION
**Pull request by verdurin**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by Micket** [comment]
@verdurin Please supply build report

**Review by Micket — APPROVED** [review]
lgtm

**Comment by verdurin** [comment]
@Micket build report underway. The first time it took 33 hours to run the sanity check on my home test box...

**Comment by verdurin** [comment]
Wonder whether we can change or remove the sanity check command here, given it's taking many days to run...

**Comment by boegel** [comment]
@verdurin The `tiny` test suite takes days?!

**Comment by boegel** [comment]
@boegelbot please test @ generoso

**Comment by boegel** [comment]
> @verdurin The `tiny` test suite takes days?!

@verdurin The [website](https://support.10xgenomics.com/single-cell-gene-expression/software/pipelines/latest/installation) says this:

```
To ensure that the cellranger pipeline is installed correctly, use cellranger testrun. This test can take up to 60 minutes on a sixteen-core workstation.
```

So days sounds very wrong to me?

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
node3401.kirlia.os - Linux centos linux 7.9.2009, x86_64, Intel(R) Xeon(R) Gold 6240 CPU @ 2.60GHz (cascadelake), Python 3.6.8
See https://gist.github.com/f97e7cb0350a2a65b7233fe260d3e82d for a full test report.

**Comment by verdurin** [comment]
> > @verdurin The `tiny` test suite takes days?!
> 
> @verdurin The [website](https://support.10xgenomics.com/single-cell-gene-expression/software/pipelines/latest/installation) says this:
> 
> ```
> To ensure that the cellranger pipeline is installed correctly, use cellranger testrun. This test can take up to 60 minutes on a sixteen-core workstation.
> ```
> 
> So days sounds very wrong to me?

I agree. Nevertheless, that's what I've seen.

It's just a version update from me, I didn't write the original easyconfig.

**Comment by boegel** [comment]
@verdurin It only took 7 minutes on the `generoso` VM (with just 4 cores), so something is very wrong on your end?

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
node3589.doduo.os - Linux RHEL 8.2, x86_64, AMD EPYC 7552 48-Core Processor (zen2), Python 3.6.8
See https://gist.github.com/138eb48c41c181409ad542f8e81e6915 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
node2720.swalot.os - Linux centos linux 7.9.2009, x86_64, Intel(R) Xeon(R) CPU E5-2660 v3 @ 2.60GHz (haswell), Python 3.6.8
See https://gist.github.com/04b73871c71726cbe2dc7a45cb0ab1a8 for a full test report.

**Comment by boegel** [comment]
Going in, thanks @verdurin!

**Pull request merged**
