### PR TITLE
{vis}[foss/2021a] wxPython v4.1.0 w/ Python 3.9.5

### PR DESCRIPTION
**Pull request by sassy-crick**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by sassy-crick** [comment]
@boegelbot please test @ generoso

**Comment by boegel** [comment]
@boegelbot please test @ jsc-zen2

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
node3100.skitty.os - Linux RHEL 8.8, x86_64, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz (skylake_avx512), Python 3.6.8
See https://gist.github.com/boegel/e2185af3ec7356f2393789d539fe38ab for a full test report.

**Review by boegel — APPROVED** [review]
lgtm

**Comment by boegel** [comment]
@sassy-crick Ah, just noticed we already have `wxPython-4.1.1-foss-2021a.eb` now, see #15046, so we should close this and update #16524 to use `wxPython` 4.1.1 instead I guess?

**Comment by sassy-crick** [comment]
@boegel Sounds like a good idea. I guess that is the problem with so many PRs open: you are risking to have duplicates. I will close that PR in favour of https://github.com/easybuilders/easybuild-easyconfigs/pull/15046,

**Pull request closed without merging**
