### PR TITLE
{bio}[intel-compilers/2023.1.0] bwa-mem2 v2.2.1

### PR DESCRIPTION
**Pull request by smoors**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by smoors** [comment]
Test report by @smoors
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
node303.hydra.os - Linux Rocky Linux 8.8, x86_64, Intel(R) Xeon(R) Gold 6148 CPU @ 2.40GHz (skylake_avx512), Python 3.6.8
See https://gist.github.com/smoors/d1b395109e1f767d504cca70c9020eed for a full test report.

**Comment by smoors** [comment]
@boegelbot: please test @ generoso

**Comment by smoors** [comment]
@boegelbot please test @ jsc-zen3

**Comment by akesandgren** [comment]
Test report by @akesandgren
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
b-cn1603.hpc2n.umu.se - Linux Ubuntu 22.04, x86_64, AMD EPYC 7313 16-Core Processor, 1 x NVIDIA NVIDIA A100 80GB PCIe, 545.29.06, Python 3.10.12
See https://gist.github.com/akesandgren/21b8b2008079cd74135436b2d79afb53 for a full test report.

**Comment by akesandgren** [comment]
It would be better to pull out the safestringlib (the gitmodule it uses) as a standalone library, there is likely other codes that are going to be picking that up in the future.

Could you try to do that?

**Comment by akesandgren** [comment]
Test report by @akesandgren
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in total)
b-cn1603.hpc2n.umu.se - Linux Ubuntu 22.04, x86_64, AMD EPYC 7313 16-Core Processor, 1 x NVIDIA NVIDIA A100 80GB PCIe, 545.29.06, Python 3.10.12
See https://gist.github.com/akesandgren/33b0a98872d522cd333d6ae17036dcbd for a full test report.

**Review by akesandgren — APPROVED** [review]
LGTM

**Comment by akesandgren** [comment]
Going in, thanks @smoors!

**Comment by smoors** [comment]
> It would be better to pull out the safestringlib (the gitmodule it uses) as a standalone library, there is likely other codes that are going to be picking that up in the future.
> 
> Could you try to do that?

done in https://github.com/easybuilders/easybuild-easyconfigs/pull/20217/commits/d49fff23a9e522bfe16cf9c2255311da3321af50

**Pull request merged**
