### PR TITLE
{chem}[intel/2022a] spglib-python v2.0.0 w/ Python 3.10.4

### PR DESCRIPTION
**Pull request by schiotz**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by schiotz** [comment]
This is a trivial port from foss/2022a to intel/2022a.

**Comment by smoors** [comment]
@boegelbot please test @ jsc-zen2

**Comment by smoors** [comment]
@boegelbot: please test @ generoso

**Review by smoors — APPROVED** [review]
lgtm

**Comment by smoors** [comment]
Going in, thanks @schiotz!

**Pull request merged**
