### PR TITLE
{bio}[foss/2022a] Jellyfish v2.3.0, Trinity v2.15.1 w/ Python 3.10.4

### PR DESCRIPTION
**Pull request by lexming**
(created using `eb --new-pr`)

Added some missing dependencies. For reference the full list is in the [Dockerfile](https://github.com/trinityrnaseq/trinityrnaseq/blob/master/Docker/Dockerfile).

Depends on:
* [x] #17403
* [x] #17387
* [x] #17383
* [x] #17378

### CODE REVIEW

**Comment by bedroge** [comment]
@lexming looks like you forgot to include the patch?

**Comment by lexming** [comment]
@bedroge very true, oops... :slightly_smiling_face:

**Comment by lexming** [comment]
@boegelbot: please test @ generoso

**Comment by lexming** [comment]
@boegelbot please test @ jsc-zen2

**Comment by branfosj** [comment]
Test report by @branfosj
**SUCCESS**
Build succeeded for 21 out of 21 (2 easyconfigs in total)
bear-pg0104u03a.bear.cluster - Linux RHEL 8.6, x86_64, Intel(R) Xeon(R) Platinum 8360Y CPU @ 2.40GHz (icelake), Python 3.6.8
See https://gist.github.com/01fa1909f4d9f0726ee12deb789c5e49 for a full test report.

**Review by branfosj — APPROVED** [review]

**Comment by branfosj** [comment]
Test report by @branfosj
**FAILED**
Build succeeded for 24 out of 25 (2 easyconfigs in total)
bear-pg0211u03a.bear.cluster - Linux Ubuntu 20.04.2 LTS (Focal Fossa), x86_64, Intel(R) Xeon(R) Gold 6248 CPU @ 2.50GHz (cascadelake), Python 3.8.5
See https://gist.github.com/0831a2881dcf3f91228ab5fd75762c65 for a full test report.

**Comment by branfosj** [comment]
Test report by @branfosj
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in total)
bear-pg0206u03a.bear.cluster - Linux Ubuntu 20.04.2 LTS (Focal Fossa), x86_64, Intel(R) Xeon(R) Gold 6248 CPU @ 2.50GHz (cascadelake), Python 3.8.5
See https://gist.github.com/d3a559deb0f26e7fd5197559c30855ad for a full test report.

**Comment by branfosj** [comment]
Going in, thanks @lexming!

**Pull request merged**
