### PR TITLE
{vis}[foss/2018b] poppler v0.70.1

### PR DESCRIPTION
**Pull request by fizwit**
(created using `eb --new-pr`)

edit by @boegel: requires ~~#7068~~ (`OpenJPEG`)

### CODE REVIEW

**Comment by boegel** [comment]
Test report by @boegel
**FAILED**
Build succeeded for 1 out of 2 (1 easyconfigs in this PR)
node3100.skitty.os - Linux centos linux 7.5.1804, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz, Python 2.7.5
See https://gist.github.com/117d1824a0119140a4617a36e52e58eb for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**FAILED**
Build succeeded for 1 out of 2 (1 easyconfigs in this PR)
node2508.golett.os - Linux centos linux 7.5.1804, Intel(R) Xeon(R) CPU E5-2680 v3 @ 2.50GHz, Python 2.7.5
See https://gist.github.com/7ceac9c0870e680fc79ea2d03bdd003e for a full test report.

**Comment by boegel** [comment]
@fizwit Sanity check fails because libraries are being installed in `lib64` rather than `lib` for me.

It looks like the automatic fallback for `lib` to `lib64` in the EasyBuild framework (cfr. https://github.com/easybuilders/easybuild-framework/pull/2477) doesn't work for a `lib` entry in `dirs`, we'll need to fix that...

For now, just dropping `lib` from `dirs` makes sense though, since we're already checking for particular files under `lib/` anyway?

**Comment by boegel** [comment]
Test report by @boegel
**FAILED**
Build succeeded for 0 out of 2 (1 easyconfigs in this PR)
node2120.delcatty.os - Linux centos linux 7.5.1804, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.7.5
See https://gist.github.com/d1eb0831d3ae68e5602fa378ccad65b2 for a full test report.

**Comment by boegel** [comment]
@fizwit The fix for the failing fallback for `lib` to `lib64` in the sanity check is done in https://github.com/easybuilders/easybuild-framework/pull/2649, which will be part of the next EasyBuild release.

Regardless, it still makes sense to simply drop the `'lib'` entry in `sanity_check_paths` here, since we're already checking for particular files in `lib/` (and in that case the fallback to checking for files in `lib64/` instead *does* work).

**Comment by boegel** [comment]
@fizwit The automated style check is tripping over trailing whitespace on lines 31 & 38:

```
$ eb --from-pr 7069 --check-style
== temporary log file in case of crash /tmp/eb-z6ZAD4/easybuild-a_rGiW.log

Running style check on 1 easyconfig(s)...

/tmp/eb-z6ZAD4/files_pr7069/p/poppler/poppler-0.70.1-foss-2018b.eb:31:26: W299 trailing whitespace
/tmp/eb-z6ZAD4/files_pr7069/p/poppler/poppler-0.70.1-foss-2018b.eb:38:76: W299 trailing whitespace
[FAIL] /tmp/eb-z6ZAD4/files_pr7069/p/poppler/poppler-0.70.1-foss-2018b.eb

ERROR: One or more style checks FAILED!
```

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
node2634.swalot.os - Linux centos linux 7.5.1804, Intel(R) Xeon(R) CPU E5-2660 v3 @ 2.60GHz, Python 2.7.5
See https://gist.github.com/3602164d19edf590ee87fefd02411352 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
node3100.skitty.os - Linux centos linux 7.5.1804, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz, Python 2.7.5
See https://gist.github.com/6aeb6119a86318af33ca28ce25fcadcd for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
gligar03.gligar.os - Linux centos linux 7.5.1804, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.7.5
See https://gist.github.com/87fedf0fcb9d47a5f1e76c1051f84d81 for a full test report.

**Comment by boegel** [comment]
Going in, thanks @fizwit!

**Comment by wpoely86** [comment]
@fizwit I'm a bit puzzled by this easyconfig. All dependencies are build dependencies. That cannot be correct? poppler needs libjpeg etc at runtime?

**Pull request merged**
