### PR TITLE
{perf}[intel-compilers/2024.2.0] STREAM v5.10

### PR DESCRIPTION
**Pull request by Micket**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by Micket** [comment]
@boegelbot please test @ generoso

**Comment by Micket** [comment]
Test report by @Micket
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
alvis-skylake-build - Linux Rocky Linux 8.9, x86_64, Intel Xeon Processor (Skylake, IBRS, no TSX), Python 3.6.8
See https://gist.github.com/Micket/53a47971a164dafe7544742b4ab8f51b for a full test report.

**Comment by Micket** [comment]
@boegelbot please test @ jsc-zen3

**Comment by bartoldeman** [comment]
Test report by @bartoldeman
**FAILED**
Build succeeded for 0 out of 1 (1 easyconfigs in total)
login1.int.archimedes.c3.ca - Linux AlmaLinux 9.4 (Seafoam Ocelot), x86_64, Intel Xeon Processor (Skylake, IBRS) (cascadelake), Python 3.11.4
See https://gist.github.com/bartoldeman/22f9bc6d96d2d55808f8949b5ed57dce for a full test report.

**Comment by bartoldeman** [comment]
Test report by @bartoldeman
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
login1.int.archimedes.c3.ca - Linux AlmaLinux 9.4 (Seafoam Ocelot), x86_64, Intel Xeon Processor (Skylake, IBRS) (cascadelake), Python 3.11.4
See https://gist.github.com/bartoldeman/5d4e48f8345f3b85d302fca68b4cfa80 for a full test report.

**Review by bartoldeman — APPROVED** [review]
LGTM

**Comment by bartoldeman** [comment]
Going in, thanks @Micket!

**Pull request merged**
