### PR TITLE
{data}[GCCcore/11.2.0] SortMeRNA v4.3.6, RocksDB v7.9.2, liburing v2.3, ...

### PR DESCRIPTION
**Pull request by branfosj**
(created using `eb --new-pr`)

I've run the example at https://sortmerna.readthedocs.io/en/latest/ with this and it was fine. Not that there is no database for 4.3.6 and one should use 4.3.4 instead.

### CODE REVIEW

**Comment by branfosj** [comment]
Test report by @branfosj
**SUCCESS**
Build succeeded for 4 out of 4 (4 easyconfigs in total)
bear-pg0105u03a.bear.cluster - Linux RHEL 8.6, x86_64, Intel(R) Xeon(R) Platinum 8360Y CPU @ 2.40GHz (icelake), Python 3.6.8
See https://gist.github.com/a970e4079c2677564f826c8cbbd4e7d9 for a full test report.

**Comment by branfosj** [comment]
Test report by @branfosj
**SUCCESS**
Build succeeded for 4 out of 4 (4 easyconfigs in total)
bear-pg0211u03a.bear.cluster - Linux Ubuntu 20.04.2 LTS (Focal Fossa), x86_64, Intel(R) Xeon(R) Gold 6248 CPU @ 2.50GHz (cascadelake), Python 3.8.5
See https://gist.github.com/3a90f46b8a302c34449c93e6f608e52b for a full test report.

**Comment by verdurin** [comment]
Test report by @verdurin
**FAILED**
Build succeeded for 3 out of 6 (4 easyconfigs in total)
easybuild-c7.novalocal - Linux CentOS Linux 7.9.2009, x86_64, Intel Xeon Processor (Skylake, IBRS), Python 3.6.8
See https://gist.github.com/df33f9c2c5c4a7ab4858bbb3b043cecc for a full test report.

**Comment by verdurin** [comment]
Build error for `liburing`:
```
     CC send-zerocopy.t
In file included from send-zerocopy.c:17:
/usr/include/linux/ipv6.h:19:8: error: redefinition of struct in6_pktinfo
   19 | struct in6_pktinfo {
      |        ^~~~~~~~~~~
In file included from /usr/include/arpa/inet.h:22,
                 from send-zerocopy.c:14:
/usr/include/netinet/in.h:538:8: note: originally defined here
  538 | struct in6_pktinfo
      |        ^~~~~~~~~~~
In file included from send-zerocopy.c:17:
/usr/include/linux/ipv6.h:24:8: error: redefinition of struct ip6_mtuinfo
   24 | struct ip6_mtuinfo {
      |        ^~~~~~~~~~~
In file included from /usr/include/arpa/inet.h:22,
                 from send-zerocopy.c:14:
/usr/include/netinet/in.h:545:8: note: originally defined here
  545 | struct ip6_mtuinfo
      |        ^~~~~~~~~~~
send-zerocopy.c: In function create_socketpair_ip:
send-zerocopy.c:241:58: error: SO_ZEROCOPY undeclared (first use in this function)
  241 |                 if (setsockopt(*sock_client, SOL_SOCKET, SO_ZEROCOPY, &val, sizeof(val))) {
      |                                                          ^~~~~~~~~~~
send-zerocopy.c:241:58: note: each undeclared identifier is reported only once for each function it appears in
make[1]: *** [send-zerocopy.t] Error 1
make[1]: *** Waiting for unfinished jobs....
make[1]: Leaving directory `/dev/shm/liburing/2.3/GCCcore-11.2.0/liburing-liburing-2.3/test'
make: *** [all] Error 2
```

**Comment by Micket** [comment]
@verdurin this looks like there are system headers that conflict with each other, not anything from liburing itself.
Possible workarounds are
`-D__USE_KERNEL_IPV6_DEFS`
which should make it use the /usr/include/linux/ipv6.h headers only for this definition
or
`-D__UAPI_DEF_IN6_PKTINFO`
but for the other way around (but that isn't availble in rhel7)

or just skip the tests

> send-zerocopy.c: In function create_socketpair_ip:
> send-zerocopy.c:241:58: error: SO_ZEROCOPY undeclared (first use in this function)
>   241 |                 if (setsockopt(*sock_client, SOL_SOCKET, SO_ZEROCOPY, &val, sizeof(val))) {

zero copy isn't available in centos7.
We can include the commit 
https://github.com/axboe/liburing/commit/eb71ed37235d941d5a279c7828090a5ec351fd44
as a patch, which should fix that.

**Comment by branfosj** [comment]
I had to modify the patch to get it to apply. This still builds for me, but will need someone with CentOS 7 to check it actually fixes the issue.

**Comment by branfosj** [comment]
Test report by @branfosj
**SUCCESS**
Build succeeded for 4 out of 4 (4 easyconfigs in total)
bear-pg0105u03a.bear.cluster - Linux RHEL 8.6, x86_64, Intel(R) Xeon(R) Platinum 8360Y CPU @ 2.40GHz (icelake), Python 3.6.8
See https://gist.github.com/b58efaf1dc4a514d1693ee7735e9fb35 for a full test report.

**Comment by bedroge** [comment]
Test report by @bedroge
**FAILED**
Build succeeded for 3 out of 6 (4 easyconfigs in total)
pg-interactive.hpc.rug.nl - Linux CentOS Linux 7.9.2009, x86_64, Intel(R) Xeon(R) CPU E5-2680 v3 @ 2.50GHz, Python 3.6.8
See https://gist.github.com/2ab0208279227b8a49859ed880d64867 for a full test report.

**Comment by Micket** [comment]
Sorry if i was unclear. There are 2 issues here. The duplicate definition is still present with this patch. We could probably patch that out with an extra define as specified in my previous post.

**Comment by verdurin** [comment]
Test report by @verdurin
**FAILED**
Build succeeded for 1 out of 4 (4 easyconfigs in total)
easybuild-c7.novalocal - Linux CentOS Linux 7.9.2009, x86_64, Intel Xeon Processor (Skylake, IBRS), Python 3.6.8
See https://gist.github.com/d0e4e6036180fc310a1962ec6755d594 for a full test report.

**Comment by branfosj** [comment]
I'll not be fixing this issue, so closing PR.

**Pull request closed without merging**
