### PR TITLE
{ai,lib,math}[gfbf/2023b] Safetensors v0.4.4, tokenizers v0.19.1, Transformers v4.44.0

### PR DESCRIPTION
**Pull request by appolloford**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by appolloford** [comment]
Test report by @appolloford
**SUCCESS**
Build succeeded for 3 out of 3 (3 easyconfigs in total)
alvis-skylake-build - Linux Rocky Linux 8.9, x86_64, Intel Xeon Processor (Skylake, IBRS, no TSX), Python 3.6.8
See https://gist.github.com/appolloford/f1437edf699a76ed1efd3596cd562d5c for a full test report.

**Comment by pavelToman** [comment]
@boegelbot please test @ generoso

**Comment by pavelToman** [comment]
@boegelbot please test @ jsc-zen3

**Review by boegel — APPROVED** [review]
lgtm

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 6 out of 6 (3 easyconfigs in total)
node3124.skitty.os - Linux RHEL 9.4, x86_64, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz (skylake_avx512), Python 3.9.18
See https://gist.github.com/boegel/7d355ca30c5b3c091fbabbf7a4d6f695 for a full test report.

**Comment by boegel** [comment]
Going in, thanks @appolloford!

**Pull request merged**
