### PR TITLE
{math}[intel/2020b] PyMC3 v3.11.0, Theano v1.1.2 (PyMC fork) + mkl-service 2.3.0 + dependencies

### PR DESCRIPTION
**Pull request by boegel**
(created using `eb --new-pr`)

~~edit: marked as WIP because I want to check on a warning like "`WARNING (theano.tensor.blas): Using NumPy C-API based implementation for BLAS functions`" that was reported for earlier versions of PyMC3...~~
fixed in Theano easyconfigs + caught via custom sanity check command

### CODE REVIEW

**Comment by boegel** [comment]
@boegelbot please test @ generoso

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 6 out of 6 (6 easyconfigs in total)
node3501.doduo.os - Linux RHEL 8.2, x86_64, AMD EPYC 7552 48-Core Processor (zen2), Python 3.6.8
See https://gist.github.com/02d86ce4ed4c2a2fb099cf7608caf3c0 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 6 out of 6 (6 easyconfigs in total)
node3103.skitty.os - Linux centos linux 7.9.2009, x86_64, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz, Python 3.6.8
See https://gist.github.com/2302d3f894726d7a0f70f8e3b47a1081 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 7 out of 7 (6 easyconfigs in total)
node2713.swalot.os - Linux centos linux 7.9.2009, x86_64, Intel(R) Xeon(R) CPU E5-2660 v3 @ 2.60GHz (haswell), Python 3.6.8
See https://gist.github.com/f2efbb0b13f35456c91292322e8eed0c for a full test report.

**Review by branfosj — APPROVED** [review]
lgtm

**Comment by branfosj** [comment]
Test report by @branfosj
**SUCCESS**
Build succeeded for 6 out of 6 (6 easyconfigs in total)
bear-pg0211u03a.bear.cluster - Linux centos linux 7.8.2003, x86_64, Intel(R) Xeon(R) Gold 6248 CPU @ 2.50GHz (cascadelake), Python 3.6.8
See https://gist.github.com/1a408d0cc942c342eb6dff6c1cab1e16 for a full test report.

**Comment by branfosj** [comment]
Going in, thanks @boegel!

**Pull request merged**
