### PR TITLE
Add lassosum extension to R v4.0.3 and v4.0.4

### PR DESCRIPTION
**Pull request by verdurin**
(created using `eb --new-pr`)

### CODE REVIEW

**Review by Micket — DISMISSED** [review]

**Comment by boegel** [comment]
@boegelbot please test @ generoso
EB_ARGS="R-4.0.3-foss-2020b.eb R-4.0.4-foss-2020b.eb"

**Review by boegel — APPROVED** [review]
lgtm

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in total)
node2601.swalot.os - Linux centos linux 7.9.2009, x86_64, Intel(R) Xeon(R) CPU E5-2660 v3 @ 2.60GHz (haswell), Python 3.6.8
See https://gist.github.com/2704b6ff1ee332a1ee4e84314d05c99e for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**FAILED**
Build succeeded for 0 out of 4 (4 easyconfigs in total)
node3306.joltik.os - Linux centos linux 7.9.2009, x86_64, Intel(R) Xeon(R) Gold 6242 CPU @ 2.80GHz (cascadelake), Python 3.6.8
See https://gist.github.com/615da2d6c6b3134c3f47dd1a88b17080 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 4 out of 4 (4 easyconfigs in total)
node3306.joltik.os - Linux centos linux 7.9.2009, x86_64, Intel(R) Xeon(R) Gold 6242 CPU @ 2.80GHz (cascadelake), Python 3.6.8
See https://gist.github.com/10b58db35cc685bbf5d3e2ae60d86c5a for a full test report.

**Comment by boegel** [comment]
Going in, thanks @verdurin!

**Pull request merged**
