### PR TITLE
{lang}[GCCcore/10.3.0] Python v3.11.4

### PR DESCRIPTION
**Pull request by pberthier**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by Micket** [comment]
So, there is a lot of PRs here, all to backport software into old toolchains.

We really strive to keep 1 version of dependencies in all toolchains in order to keep all the software within a particular foss/GCCcore/intel toolchain interoperable, and this would completely break that.
So even just providing more version of python, sqlite, bzip, etc. just causes fragmentation that is worse then not having them.  We even provide continuous integration tests to ensure we don't accept PRs that do this without explcitly adding exceptions so we really only stray for this design when we absolutely are forced to for something very important, and even then we add things like versionsuffixes and such to indicate that this is an offshoot variant that isn't compatible with the rest. 

You are of course free to backport and build these yourself, but the upstreams standard easyconfigs repo is more carefully chosen to work together. 

If newer versions are required for something, especially so for core dependencies, the expectation is to move towards the newer toolchains.

I've glanced through all the PRs you opened today, and this applies to all of them.

**Comment by pberthier** [comment]
Thanks, I understand that very well.  Sorry for the mess, I'm rather new to easybuild.  I need to stick with that old toolchain though and I will cleanup my PRs so they fit your requirements.  Should I update them or submit new ones?

**Comment by Micket** [comment]
> Should I update them or submit new ones?

Really not sure what you mean here since these were backports of packages which have a version in all toolchains already

**Comment by pberthier** [comment]
I've removed them all.  Now I've got two that I believe should be OK #18360 and #18337

**Pull request closed without merging**
