### PR TITLE
use new custom easyblock in torchvision easyconfigs

### PR DESCRIPTION
**Pull request by Flamefire**
(created using `eb --new-pr`)

- [x] For use with ~https://github.com/easybuilders/easybuild-easyblocks/pull/2467~

### CODE REVIEW

**Comment by Flamefire** [comment]
Test report by @Flamefire
Using easyblocks from PR(s) https://github.com/easybuilders/easybuild-easyblocks/pull/2467
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
taurusa8 - Linux centos linux 7.7.1908, x86_64, Intel(R) Xeon(R) CPU E5-2603 v4 @ 1.70GHz (broadwell), Python 2.7.5
See https://gist.github.com/50a162c88021f3c916366d2c6a352329 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 9 out of 9 (9 easyconfigs in total)
node3301.joltik.os - Linux centos linux 7.9.2009, x86_64, Intel(R) Xeon(R) Gold 6242 CPU @ 2.80GHz (cascadelake), Python 3.6.8
See https://gist.github.com/8f00337c3cda6c17dc341919c575bd99 for a full test report.

**Comment by boegel** [comment]
@boegelbot please test @ generoso

**Review by boegel — APPROVED** [review]
lgtm

**Comment by boegel** [comment]
Going in, thanks @Flamefire!

**Pull request merged**
