### PR TITLE
{bio}[foss/2020a] MetaPhlAn v3.0.9 w/ Python 3.8.2

### PR DESCRIPTION
**Pull request by manifestoso**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by robqiao** [comment]
Build success dep on #12913, #12915 #12916

**Comment by robqiao** [comment]
@branfosj can we rebuild this one. Thx

**Comment by branfosj** [comment]
> @branfosj can we rebuild this one. Thx

Can you run `eb --sync-pr 12917`, which will update the branch in this PR with the dependencies that have now been merged.

**Comment by robqiao** [comment]
> 
> 
> > @branfosj can we rebuild this one. Thx
> 
> Can you run `eb --sync-pr 12917`, which will update the branch in this PR with the dependencies that have now been merged.

No worries, done. Thx

**Comment by verdurin** [comment]
@robqiao could you address the test failures and see if it can use the slightly order version of `MAFFT`?

**Comment by robqiao** [comment]
> 
> 
> @robqiao could you address the test failures and see if it can use the slightly order version of `MAFFT`?

@verdurin @branfosj  No worries, fixed now.

**Comment by robqiao** [comment]
@verdurin @branfosj merge this PR? Thx

**Comment by boegel** [comment]
Test report by @boegel
**FAILED**
Build succeeded for 0 out of 1 (1 easyconfigs in total)
node2617.swalot.os - Linux centos linux 7.9.2009, x86_64, Intel(R) Xeon(R) CPU E5-2660 v3 @ 2.60GHz (haswell), Python 3.6.8
See https://gist.github.com/b833b817999a3bf277106df397ea1821 for a full test report.

**Comment by boegel** [comment]
@robqiao `pip check` fails in sanity check because several dependencies are missing? See test report...

**Comment by robqiao** [comment]
> 
> 
> @robqiao `pip check` fails in sanity check because several dependencies are missing? See test report...

Hmm,  those failed checks were included in the dependency stack. Does `use_pip` tag has to be set for PythonPackage block?   @boegel 

> 
> 
> @robqiao `pip check` fails in sanity check because several dependencies are missing? See test report...

@boegel  run another test?

**Comment by manifestoso** [comment]
deps on #14326

**Comment by manifestoso** [comment]
@verdurin @branfosj merge this PR? Thx

**Comment by manifestoso** [comment]
Test report by @robqiao
**SUCCESS**
Build succeeded for 0 out of 0 (1 easyconfigs in total)
hpc-head01 - Linux UNKNOWN UNKNOWN, x86_64, Intel(R) Xeon(R) Gold 6130 CPU @ 2.10GHz, Python 3.9.6
See https://gist.github.com/a2bd0fd9afa212b051bf751dc39966e4 for a full test report.

**Comment by manifestoso** [comment]
Test report by @robqiao
**FAILED**
Build succeeded for 0 out of 1 (1 easyconfigs in total)
hpc-head01 - Linux UNKNOWN UNKNOWN, x86_64, Intel(R) Xeon(R) Gold 6130 CPU @ 2.10GHz, Python 3.9.6
See https://gist.github.com/b77b318fa5f76308287095c8c483c445 for a full test report.

**Comment by manifestoso** [comment]
Test report by @robqiao
**FAILED**
Build succeeded for 4 out of 36 (1 easyconfigs in total)
hpc-head01 - Linux UNKNOWN UNKNOWN, x86_64, Intel(R) Xeon(R) Gold 6130 CPU @ 2.10GHz, Python 3.9.6
See https://gist.github.com/5d466f40f28edc870a68d53dcb1e0502 for a full test report.

**Comment by manifestoso** [comment]
deps on PR #14526

**Comment by manifestoso** [comment]
> deps on ~~#14326~~

**Comment by manifestoso** [comment]
Test report by @robqiao
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
hpc-head01 - Linux UNKNOWN UNKNOWN, x86_64, Intel(R) Xeon(R) Gold 6130 CPU @ 2.10GHz, Python 3.9.6
See https://gist.github.com/1c6988178874c312b58c523c517cd117 for a full test report.

**Comment by lexming** [comment]
@boegelbot: please test @ generoso

**Comment by lexming** [comment]
Test report by @lexming
**SUCCESS**
Build succeeded for 4 out of 4 (1 easyconfigs in total)
node301.hydra.os - Linux centos linux 7.9.2009, x86_64, Intel(R) Xeon(R) Gold 6148 CPU @ 2.40GHz, Python 2.7.5
See https://gist.github.com/8042807adb2b0677c2fb854e33271d59 for a full test report.

**Comment by lexming** [comment]
@boegelbot: please test @ generoso

**Review by lexming — APPROVED** [review]
Thanks for the update @manifestoso . I just made a little fix to the sanity checks, as long as you already check for files inside `bin` and `lib` ther is no need to explicitly check for those folders. In this case, you already check for the executables inside `bin` and since MetaPhlAn is a Python package we must have a `site-packages` inside `lib`.

LGTM

**Comment by lexming** [comment]
Going in, thanks @manifestoso !

**Pull request merged**
