### PR TITLE
Switch libxc sources to gitlab

### PR DESCRIPTION
**Pull request by Micket**
(created using `eb --new-pr`)
Old homepage is dead.

### CODE REVIEW

**Comment by jfgrimm** [comment]
(forgot to add `--force-download`...)

**Comment by casparvl** [comment]
@boegelbot please test @ jsc-zen3
EB_ARGS="libxc-6.2.2-GCC-12.3.0.eb libxc-5.1.6-GCC-11.2.0.eb libxc-4.3.4-GCC-10.3.0.eb --force-download"

**Comment by Micket** [comment]
Test report by @Micket
**SUCCESS**
Build succeeded for 3 out of 3 (3 easyconfigs in total)
alvis-skylake-build - Linux Rocky Linux 8.9, x86_64, Intel Xeon Processor (Skylake, IBRS, no TSX), Python 3.6.8
See https://gist.github.com/Micket/1f1b8ad8a7c7068117a13403008af846 for a full test report.

**Comment by casparvl** [comment]
Test report by @casparvl
**SUCCESS**
Build succeeded for 3 out of 3 (3 easyconfigs in total)
tcn1.local.snellius.surf.nl - Linux RHEL 8.6, x86_64, AMD EPYC 7H12 64-Core Processor, Python 3.6.8
See https://gist.github.com/casparvl/c71f0c700fe8ee671052d296824c8c6f for a full test report.

**Pull request merged**
