### PR TITLE
{lib}[system/system] cuQuantum v24.08.0.5 w/ CUDA 12.1.1

### PR DESCRIPTION
**Pull request by lcniel**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by lcniel** [comment]
Test report by @lcniel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
alvis4-28 - Linux Rocky Linux 8.9, x86_64, Intel(R) Xeon(R) Gold 6338 CPU @ 2.00GHz, 1 x NVIDIA NVIDIA A100-SXM4-40GB, 545.23.08, Python 3.6.8
See https://gist.github.com/lcniel/c892cdc8be6b9a9df2c2c5c011646bd0 for a full test report.

**Comment by lcniel** [comment]
Test report by @lcniel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
alvis4-28 - Linux Rocky Linux 8.9, x86_64, Intel(R) Xeon(R) Gold 6338 CPU @ 2.00GHz, 1 x NVIDIA NVIDIA A100-SXM4-40GB, 545.23.08, Python 3.6.8
See https://gist.github.com/lcniel/b76fed0b9ea430b02bb83ffb9ddcf359 for a full test report.

**Review by Micket — APPROVED** [review]
lgtm

**Review by Micket — APPROVED** [review]
lgtm

**Review by Micket — APPROVED** [review]
lgtm

**Comment by Micket** [comment]
Laggy train wifi keeps disconnecting me, sorry for the spam

**Comment by Micket** [comment]
@boegelbot please test @ jsc-zen3

**Pull request merged**
