### PR TITLE
{bio}[foss/2021a] MicrobeAnnotator v2.0.5 w/ Python 3.9.5

### PR DESCRIPTION
**Pull request by zarybnicky**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by zarybnicky** [comment]
I would like to test it more, but that requires downloading like 250GBs of data

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
node2675.swalot.os - Linux centos linux 7.9.2009, x86_64, Intel(R) Xeon(R) CPU E5-2660 v3 @ 2.60GHz (haswell), Python 3.6.8
See https://gist.github.com/ca1f9205b5d867449ab94f4e77f9cf63 for a full test report.

**Comment by boegel** [comment]
@boegelbot please test @ generoso

**Review by boegel — APPROVED** [review]

**Comment by boegel** [comment]
Going in, thanks @zarybnicky!

**Pull request merged**
