### PR TITLE
Add --with-versioned-syms to ncurses 6.2 and 6.3

### LINKED ISSUE #16014: Build failure for libreadline-8.1-GCCcore-11.2.0
EasyBuild 4.6.0 fails to build [`libreadline-8.1-GCCcore-11.2.0.eb`](https://github.com/easybuilders/easybuild-easyconfigs/blob/easybuild-easyconfigs-v4.6.0/easybuild/easyconfigs/l/libreadline/libreadline-8.1-GCCcore-11.2.0.eb):
```
== FAILED: Installation ended unsuccessfully
(build directory: /tmp/easybuild/libreadline/8.1/GCCcore-11.2.0): build failed (first 300 chars):
cmd "/opt/easybuild/sources/generic/eb_v4.6.0/ConfigureMake/config.guess" exited with exit code 1 and output:
/bin/bash: /opt/easybuild/software/ncurses/6.2-GCCcore-11.2.0/lib/libncursesw.so.6:
version `NCURSES6_TINFO_5.0.19991023' not found (required by /usr/lib/libreadline.so.8)
```
(Line breaks have been added for legibility.)

On this system, `/bin/sh` is provided by `bash`, which is configured using `--with-curses`, so it requires both `libreadline.so` and `libncursesw.so`:
```
$ ldd /bin/sh
        [...]
        libreadline.so.8 => /usr/lib/libreadline.so.8
        libncursesw.so.6 => /usr/lib/libncursesw.so.6
```
Since `config.guess` is a shell script, it can't be executed when the EasyBuild `libncursesw.so` is used together with the system `libreadline.so`:
```
$ head -n1 /opt/easybuild/sources/generic/eb_v4.6.0/ConfigureMake/config.guess
#! /bin/sh
$ LD_LIBRARY_PATH=/opt/easybuild/software/ncurses/6.2-GCCcore-11.2.0/lib /bin/sh
/bin/sh: /opt/easybuild/software/ncurses/6.2-GCCcore-11.2.0/lib/libncursesw.so.6:
version `NCURSES6_TINFO_5.0.19991023' not found (required by /usr/lib/libreadline.so.8)
```

### PR DESCRIPTION
**Pull request by Micket**
(created using `eb --new-pr`)

edit: fixes #16014

### CODE REVIEW

**Comment by Micket** [comment]
Test report by @Micket
**SUCCESS**
Build succeeded for 6 out of 6 (6 easyconfigs in total)
alvis-c1 - Linux Rocky Linux 8.5, x86_64, Intel Xeon Processor (Skylake), Python 3.6.8
See https://gist.github.com/b023279acd48a4b7780aae3ce11182ea for a full test report.

**Comment by SebastianAchilles** [comment]
@boegelbot please test @ generoso
EB_ARGS="ncurses-6.2-GCCcore-10.2.0.eb ncurses-6.2-GCCcore-10.3.0.eb ncurses-6.2-GCCcore-11.2.0.eb ncurses-6.2-GCCcore-9.3.0.eb ncurses-6.3-GCCcore-11.3.0.eb ncurses-6.3-GCCcore-12.1.0.eb"

**Comment by SebastianAchilles** [comment]
@boegelbot please test @ jsc-zen2
EB_ARGS="ncurses-6.2-GCCcore-10.2.0.eb ncurses-6.2-GCCcore-10.3.0.eb ncurses-6.2-GCCcore-11.2.0.eb ncurses-6.2-GCCcore-9.3.0.eb ncurses-6.3-GCCcore-11.3.0.eb"

**Comment by SebastianAchilles** [comment]
Test report by @sebastianachilles
**SUCCESS**
Build succeeded for 4 out of 4 (4 easyconfigs in total)
bdw-opensuse-154 - Linux openSUSE Leap 15.4, x86_64, Intel(R) Core(TM) i7-6900K CPU @ 3.20GHz (broadwell), 2 x NVIDIA NVIDIA GeForce GTX 1060 6GB, 510.85.02, Python 3.6.15
See https://gist.github.com/de0be8a20c79dce722d83e2cc94af12e for a full test report.

**Comment by brentwg-recursion** [comment]
Test report by @brentwg-recursion
**SUCCESS**
Build succeeded for 28 out of 28 (4 easyconfigs in total)
bright1 - Linux Ubuntu 20.04, x86_64, AMD EPYC 7352 24-Core Processor, Python 3.8.10
See https://gist.github.com/2469964ceb93eb358402764e877ed84b for a full test report.

**Review by boegel — APPROVED** [review]
lgtm

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 5 out of 5 (5 easyconfigs in total)
node3171.skitty.os - Linux RHEL 8.4, x86_64, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz (skylake_avx512), Python 3.6.8
See https://gist.github.com/c594130f0a953484c1950cfc17a7d3dc for a full test report.

**Comment by boegel** [comment]
Going in, thanks @Micket!

**Pull request merged**
