### PR TITLE
Fix "source_urls" for mawk.

### PR DESCRIPTION
**Pull request by ghuls**
The "source_urls" for mawk changed from:
    "ftp://ftp.invisible-island.net/mawk/"
To:
    "ftp://ftp.invisible-island.net/mawk/"

but "ftp://ftp.invisible-island.net/mawk/" is a symlink,
so easybuild is unable to retreive the source archive.

cURL has problems with it too:

    $ curl -v ftp://ftp.invisible-island.net/mawk/
    * About to connect() to ftp.invisible-island.net port 21 (#0)
    *   Trying 216.194.196.78...
    * Connected to ftp.invisible-island.net (216.194.196.78) port 21 (#0)
    < 220 ProFTPD Server (ftp.invisible-island.net) [216.194.196.78]
    > USER anonymous
    < 331 Anonymous login ok, send your complete email address as your password
    > PASS ftp@example.com
    < 230 Anonymous access granted, restrictions apply
    > PWD
    < 257 "/" is the current directory
    * Entry path is '/'
    > CWD mawk
    * ftp_perform ends with SECONDARY: 0
    < 550 mawk: No such file or directory
    * Server denied you to change to the given directory
    * Connection #0 to host ftp.invisible-island.net left intact
    curl: (9) Server denied you to change to the given directory

Giving the real path without symlinks works:
    "ftp://ftp.invisible-island.net/pub/mawk/"

Note: There are two (m|M)awk easyconfig.

### CODE REVIEW

**Comment by boegel** [comment]
(close/re-open to re-trigger Travis tests after fixing target branch to `develop`)

**Comment by boegel** [comment]
W.r.t. the `Mawk` misnomer: that issue will resolve itself soon when we archive all easyconfigs that use deprecated toolchains (see https://easybuild.readthedocs.io/en/latest/Deprecated-easyconfigs.html).

**Comment by ghuls** [comment]
@boegel I only realized later that there was a `develop` branch. I rebased my commits from `develop` and added checksums and configs for more toolchains.

**Comment by ghuls** [comment]
@boegel I can't get `eb --new-pr` to work as `keyring` does not want to install, so I can't add my github token with `eb --github-user example --install-github-token`. Is there a way to provide the token in another way (e.g. passing it manually everytime)?

**Comment by boegel** [comment]
@ghuls Right now, there isn't an alternative, but the `keyring` thing has been bothering me as well, I'm not very happy with it...

Do you mind opening an issue in https://github.com/easybuilders/easybuild-framework/issues to describe the issues you're running into?

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 6 out of 6 (6 easyconfigs in this PR)
node3135.skitty.os - Linux centos linux 7.6.1810, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz, Python 2.7.5
See https://gist.github.com/c3d2caed76541b9c0142f71e8c282c8e for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 8 out of 8 (8 easyconfigs in this PR)
node2120.delcatty.os - Linux centos linux 7.6.1810, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.7.5
See https://gist.github.com/6266ef4ceedf0e04b0d682698ebf030a for a full test report.

**Comment by boegel** [comment]
Going in, thanks @ghuls!

**Pull request merged**
