### PR TITLE
Remove CMake Arrow flag as there is no Arrow dependency in recent GDAL easyconfigs

### PR DESCRIPTION
**Pull request by branfosj**
(created using `eb --new-pr`)

I tried adding Arrow as a dependency in #20901, but that went badly. So I am instead proposing the code cleanup option.

### CODE REVIEW

**Comment by boegel** [comment]
What's the implication of not (correctly) specifying `-DArrow_DIR`? Does GDAL then use an internal Arrow, or does it not support certain features?

**Comment by branfosj** [comment]
> What's the implication of not (correctly) specifying `-DArrow_DIR`? Does GDAL then use an internal Arrow, or does it not support certain features?

I'm seeing the same output from CMake with and without this:
```
-- Could NOT find Arrow (missing: Arrow_DIR)
```

```
-- The following features have been disabled:
[snip]
 * ogr_ARROW, Arrow
```

```
-- The following OPTIONAL packages have not been found:
[ship]
 * Arrow
   Apache Arrow C++ library
```

So I am saying there is no internal Arrow fallback and our GDAL does not contain support for Arrow - either before or after this PR.

**Comment by branfosj** [comment]
Test report by @branfosj
**SUCCESS**
Build succeeded for 3 out of 3 (3 easyconfigs in total)
bear-pg0105u03a - Linux RHEL 8.6, x86_64, Intel(R) Xeon(R) Platinum 8360Y CPU @ 2.40GHz (icelake), Python 3.6.8
See https://gist.github.com/branfosj/70f01e64738d397a511eb05836965655 for a full test report.

**Review by boegel — APPROVED** [review]
lgtm

**Comment by boegel** [comment]
@boegelbot please test @ generoso

**Comment by boegel** [comment]
@boegelbot please test @ jsc-zen3

**Comment by boegel** [comment]
Test report by @boegel
**FAILED**
Build succeeded for 0 out of 3 (3 easyconfigs in total)
node3121.skitty.os - Linux RHEL 8.8, x86_64, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz, Python 3.6.8
See https://gist.github.com/boegel/cc6583dce4587212308b1d19e7e54792 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 3 out of 3 (3 easyconfigs in total)
node3121.skitty.os - Linux RHEL 8.8, x86_64, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz, Python 3.6.8
See https://gist.github.com/boegel/27d62dd023824e76fe14678adebe572c for a full test report.

**Comment by boegel** [comment]
Going in, thanks @branfosj!

**Pull request merged**
