### PR TITLE
use custom easyblock for OpenBLAS in OpenBLAS 0.3.x easyconfigs

### PR DESCRIPTION
**Pull request by edmondac**
New easyblock from here https://github.com/easybuilders/easybuild-easyblocks/pull/1697 - so the eb files can be much shorter. This now builds on POWER systems too.

### CODE REVIEW

**Comment by edmondac** [comment]
Test report by @bear-software
**FAILED**
Build succeeded for 0 out of 1 (1 easyconfigs in this PR)
bear-pg0305u15a.bear.cluster - Linux RHEL 7.6, 8335-GTX, Python 2.7.5
See https://gist.github.com/be724dfa29c4246cac61222288889c92 for a full test report.

**Comment by edmondac** [comment]
Test report by @bear-software
**SUCCESS**
Build succeeded for 0 out of 0 (1 easyconfigs in this PR)
bear-pg0305u15a.bear.cluster - Linux RHEL 7.6, 8335-GTX, Python 2.7.5
See https://gist.github.com/28ab92a84c645315ccaac4164e94a857 for a full test report.

**Comment by edmondac** [comment]
Test report by @bear-software
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
bear-pg0305u15a.bear.cluster - Linux RHEL 7.6, 8335-GTX, Python 2.7.5
See https://gist.github.com/d8f1b22f5f04fd9ae1ab566c62cbe8f8 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 6 out of 6 (6 easyconfigs in this PR)
node3104.skitty.os - Linux centos linux 7.6.1810, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz, Python 2.7.5
See https://gist.github.com/7304774fb35fa1cd4cffa261236e316d for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 6 out of 6 (6 easyconfigs in this PR)
node2065.delcatty.os - Linux centos linux 7.6.1810, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.7.5
See https://gist.github.com/09dcfcb8bbffeb687d3590a017f2f760 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 6 out of 6 (6 easyconfigs in this PR)
node2471.golett.os - Linux centos linux 7.6.1810, Intel(R) Xeon(R) CPU E5-2680 v3 @ 2.50GHz, Python 2.7.5
See https://gist.github.com/3029f8e22f58214c1321cea9898aeab9 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 6 out of 6 (6 easyconfigs in this PR)
node2034.delcatty.os - Linux centos linux 7.6.1810, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.7.5
See https://gist.github.com/9ae1ac07b00ae4f10dcd9588290abb5a for a full test report.

**Comment by akesandgren** [comment]
Test report by @akesandgren
**SUCCESS**
Build succeeded for 6 out of 6 (6 easyconfigs in this PR)
b-an03.hpc2n.umu.se - Linux ubuntu 16.04, Intel(R) Xeon(R) CPU E5-2690 v4 @ 2.60GHz, Python 2.7.12
See https://gist.github.com/ff57fe77c095c510b5ec84bc6956966e for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 6 out of 6 (6 easyconfigs in this PR)
node2578.golett.os - Linux centos linux 7.6.1810, Intel(R) Xeon(R) CPU E5-2680 v3 @ 2.50GHz, Python 2.7.5
See https://gist.github.com/fef6cbd61ebb78e6914181df1c46e7bb for a full test report.

**Comment by boegel** [comment]
Going in, thanks @edmondac!

**Pull request merged**
