### PR TITLE
Use -D_GNU_SOURCE for flex-2.6.4-GCCcore-7.3.0 as well

### PR DESCRIPTION
**Pull request by crubb**
Now that I built Doxygen, which depends on flex, I found that we need to add `-D_GNU_SOURCE` to `preconfigopts` not only for the dummy flex, but also the `GCCcore-7.3.0` flex. Otherwise, flex will segfault when building Doxygen.

Please refer to #5792.

Should we add the `preconfigopts` to the other `flex-2.6.4-GCCcore-*.eb` as well?

### CODE REVIEW

**Comment by boegel** [comment]
@crubb Yes, let's make this consistent in the other flex 2.6.4 easyconfigs please.

**Comment by crubb** [comment]
Done!

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 7 out of 7 (7 easyconfigs in this PR)
node2062.delcatty.os - Linux centos linux 7.5.1804, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.7.5
See https://gist.github.com/fad84b94f8dc2a02b7672d4ff5ece340 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 7 out of 7 (7 easyconfigs in this PR)
node2426.golett.os - Linux centos linux 7.4.1708, Intel(R) Xeon(R) CPU E5-2680 v3 @ 2.50GHz, Python 2.7.5
See https://gist.github.com/f566115733576cf58abfee65e13e1558 for a full test report.

**Comment by boegel** [comment]
Going in, thanks @crubb!

**Pull request merged**
