### PR TITLE
{vis}[intel/2018a] gnuplot v5.2.2

### PR DESCRIPTION
**Pull request by boegel**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 5 out of 5 (5 easyconfigs in this PR)
node2530.golett.os - Linux centos linux 7.4.1708, Intel(R) Xeon(R) CPU E5-2680 v3 @ 2.50GHz, Python 2.7.5
See https://gist.github.com/6b6400cb8c01832998fed157127c2483 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 5 out of 5 (5 easyconfigs in this PR)
gligar03.gligar.os - Linux centos linux 7.4.1708, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.7.5
See https://gist.github.com/65982265875b8b7a87a3aa12fa6bf1af for a full test report.

**Comment by verdurin** [comment]
@boegel A bit surprised to see so many dependency updates in the change from `foss` to `intel`?:
```
27 -     ('cairo', '1.14.10'), (1/1)
27 +     ('cairo', '1.14.12'), (1/1)
28 -     ('libjpeg-turbo', '1.5.2'), (1/1)
28 +     ('libjpeg-turbo', '1.5.3'), (1/1)
29 -     ('libpng', '1.6.32'), (1/1)
29 +     ('libpng', '1.6.34'), (1/1)
30 -     ('libgd', '2.2.4'), (1/1)
30 +     ('libgd', '2.2.5'), (1/1)
31 -     ('Pango', '1.40.14'), (1/1)
31 +     ('Pango', '1.41.1'), (1/1)
 
-----
 
33 -     ('Qt5', '5.8.0'), (1/1)
33 +     ('Qt5', '5.10.1'), (1/1)
```

**Comment by boegel** [comment]
@verdurin I think you were looking at the diff with the `intel/2017b` easyconfig, since this is what I'm seeing when comparing with the `foss/2018a` easyconfig:

```diff
diff -u easybuild/easyconfigs/g/gnuplot/gnuplot-5.2.2-foss-2018a.eb  easybuild/easyconfigs/g/gnuplot/gnuplot-5.2.2-intel-2018a.eb
--- easybuild/easyconfigs/g/gnuplot/gnuplot-5.2.2-foss-2018a.eb	2018-05-23 14:45:09.000000000 +0200
+++ easybuild/easyconfigs/g/gnuplot/gnuplot-5.2.2-intel-2018a.eb	2018-06-11 08:56:20.000000000 +0200
@@ -17,7 +17,7 @@
 homepage = 'http://gnuplot.sourceforge.net/'
 description = """Portable interactive, function plotting utility"""

-toolchain = {'name': 'foss', 'version': '2018a'}
+toolchain = {'name': 'intel', 'version': '2018a'}

 source_urls = [('https://sourceforge.net/projects/gnuplot/files/gnuplot/%(version)s', 'download')]
 sources = [SOURCE_TAR_GZ]
```

Also, the dependency variant check would fail if we were using different dependency versions for `foss/2018a` vs `intel/2018a`

**Comment by boegel** [comment]
@verdurin ping?

**Comment by verdurin** [comment]
@boegel - yes, it's a brain error. Looking at the `review-pr` output more carefully, it all appears okay.

**Comment by verdurin** [comment]
Going in, thanks @boegel!

**Pull request merged**
