### PR TITLE
{devel}[fosscuda/2020b] PyTorch v1.10.0, CMake v3.20.1, expecttest v0.1.3 w/ Python 3.8.6

### PR DESCRIPTION
**Pull request by schiotz**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by schiotz** [comment]
Note that this version of PyTorch requires CMake 3.20 or later to build.

**Comment by boegel** [comment]
@boegelbot please test @ generoso
CORE_CNT=16

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 3 out of 3 (3 easyconfigs in total)
node3904.accelgor.os - Linux RHEL 8.4, x86_64, AMD EPYC 7413 24-Core Processor (zen2), 1 x NVIDIA NVIDIA A100-SXM4-80GB, 470.82.01, Python 3.6.8
See https://gist.github.com/51e4691d9d14f473f33ca0f6c33e72b2 for a full test report.

**Review by boegel — APPROVED** [review]
lgtm

**Comment by boegel** [comment]
Going in, thanks @schiotz!

**Pull request merged**
