### PR TITLE
{lib}[intel/2018a] FUSE v3.2.6

### PR DESCRIPTION
**Pull request by boegel**
(created using `eb --new-pr`)
requires ~~https://github.com/easybuilders/easybuild-easyblocks/pull/1561~~ + ~~#7077~~ (Meson, Ninja)

### CODE REVIEW

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
node2447.golett.os - Linux centos linux 7.5.1804, Intel(R) Xeon(R) CPU E5-2680 v3 @ 2.50GHz, Python 2.7.5
See https://gist.github.com/00fcd42cb2746927c91808ed553aa8c7 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
node2070.delcatty.os - Linux centos linux 7.5.1804, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.7.5
See https://gist.github.com/c3c6f9751b2f44089517f4de9ba05488 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
node3101.skitty.os - Linux centos linux 7.5.1804, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz, Python 2.7.5
See https://gist.github.com/dd92fe01c4b4128dbd175e7405aa0f39 for a full test report.

**Comment by migueldiascosta** [comment]
closing/reopening to trigger travis now that #7077 is merged

**Comment by migueldiascosta** [comment]
Test report by @migueldiascosta
**FAILED**
Build succeeded for 0 out of 1 (1 easyconfigs in this PR)
grc-cluster1 - Linux centos 6.10, Intel(R) Xeon(R) CPU E5-2640 0 @ 2.50GHz, Python 2.7.14
See https://gist.github.com/5b0ff0e718658ae74ec1c258b2f15dc4 for a full test report.

**Comment by migueldiascosta** [comment]
I suppose my failed test report is CentOS6/old glibc specific (?)

**Comment by boegel** [comment]
@migueldiascosta So, how do we proceed with this?

**Comment by migueldiascosta** [comment]
@boegel yeah, I don't see any fuse3 anywhere for RHEL/CentOS 6, so I suppose it's not possible

is there a way to require minimum versions of osdependencies? If not, shouldn't there be?

(I suppose it can be done indirectly with package names, e.g. systemd or grub2, but it's distro-dependent, less transparent and less reliable...)

**Comment by boegel** [comment]
@migueldiascosta We don't have support for checking versions of OS dependencies... I guess that could be useful, but it may not be that easy to implement.

We could implement support for checking the minimal kernel version though, that seems more relevant here?

**Comment by verdurin** [comment]
We're on CentOS 7 now, as you can see from the report.

**Comment by boegel** [comment]
@migueldiascosta How shall we proceed with this PR? Should we look into a good way to signal that this can't be built on an older OS?

**Comment by boegel** [comment]
@migueldiascosta ping on this one?

**Comment by migueldiascosta** [comment]
@boegel it probably shouldn't hold off this PR, but in general I think having a way of specifying minimum versions of both kernel and glibc would be useful, so that eb fails with a meaningful message

**Comment by boegel** [comment]
@migueldiascosta Let's get this PR merged, and open an issue in the framework repo to track adding support for minimal `glibc` and/or kernel versions?

**Comment by migueldiascosta** [comment]
Going in, thanks @boegel!

**Pull request merged**
