### PR TITLE
add patch to fix detection of newer Intel CPUs in OpenBLAS 0.3.20-0.3.23

### PR DESCRIPTION
**Pull request by Flamefire**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by branfosj** [comment]
Test report by @branfosj
**SUCCESS**
Build succeeded for 5 out of 5 (5 easyconfigs in total)
bear-pg0105u03a - Linux RHEL 8.6, x86_64, Intel(R) Xeon(R) Platinum 8360Y CPU @ 2.40GHz (icelake), Python 3.6.8
See https://gist.github.com/branfosj/25272be6f5629a74bb04879833a1d889 for a full test report.

**Comment by Flamefire** [comment]
Test report by @Flamefire
**FAILED**
Build succeeded for 16 out of 18 (5 easyconfigs in total)
taurusi6605.taurus.hrsk.tu-dresden.de - Linux RHEL 7.9, x86_64, Intel(R) Xeon(R) CPU E5-2680 v3 @ 2.50GHz, Python 2.7.5
See https://gist.github.com/Flamefire/c250c48c585a6f60358671fb0ef90cbd for a full test report.

**Comment by Flamefire** [comment]
Test report by @Flamefire
**FAILED**
Build succeeded for 12 out of 16 (5 easyconfigs in total)
n1604 - Linux RHEL 8.7 (Ootpa), x86_64, Intel(R) Xeon(R) Platinum 8470, Python 3.8.13
See https://gist.github.com/Flamefire/9204352d66e3e56e0e7a2263e073c639 for a full test report.

**Comment by Flamefire** [comment]
This might be failing on actual SapphireRapids (for which I made that change) due to https://github.com/easybuilders/easybuild-easyconfigs/issues/19021 -.-

**Comment by Flamefire** [comment]
Test report by @Flamefire
**FAILED**
Build succeeded for 4 out of 6 (5 easyconfigs in total)
taurusi6605.taurus.hrsk.tu-dresden.de - Linux RHEL 7.9, x86_64, Intel(R) Xeon(R) CPU E5-2680 v3 @ 2.50GHz, Python 2.7.5
See https://gist.github.com/Flamefire/331884e2404cdfe028426865db592c4f for a full test report.

**Comment by Flamefire** [comment]
Test report by @Flamefire
**FAILED**
Build succeeded for 1 out of 5 (5 easyconfigs in total)
n1604 - Linux RHEL 8.7 (Ootpa), x86_64, Intel(R) Xeon(R) Platinum 8470 (icelake), Python 3.8.13
See https://gist.github.com/Flamefire/b20a2f2d0dbef6718eb9fb25a4e6b9ba for a full test report.

**Comment by Flamefire** [comment]
Test report by @Flamefire
**SUCCESS**
Build succeeded for 6 out of 6 (5 easyconfigs in total)
taurusi6605.taurus.hrsk.tu-dresden.de - Linux RHEL 7.9, x86_64, Intel(R) Xeon(R) CPU E5-2680 v3 @ 2.50GHz (haswell), Python 2.7.5
See https://gist.github.com/Flamefire/ae25715fdf050f2d0e802dd1207d8dde for a full test report.

**Comment by boegel** [comment]
@boegelbot please test @ generoso

**Review by boegel — APPROVED** [review]
lgtm

**Comment by boegel** [comment]
@boegelbot please test @ jsc-zen2

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 35 out of 35 (5 easyconfigs in total)
node3153.skitty.os - Linux RHEL 8.8, x86_64, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz (skylake_avx512), Python 3.6.8
See https://gist.github.com/boegel/c1f17ba4444fc8b58b8c916501bc500e for a full test report.

**Comment by boegel** [comment]
Going in, thanks @Flamefire!

**Comment by Flamefire** [comment]
PR to fix the failures on Sapphire Rapids (still reported as "icelake" by archspec [above](https://github.com/easybuilders/easybuild-easyconfigs/pull/19141#issuecomment-1790851823)) and Cooperlake CPUs at #19159

**Pull request merged**
