### PR TITLE
Fix uniq operation in TensorFlow 2.4.1

### PR DESCRIPTION
**Pull request by Flamefire**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by Micket** [comment]
I think the patch is missing. 

Any comments on the patch that was removed?

**Comment by Flamefire** [comment]
Thanks, added. The new patch fixes the actual bug, the old patch did only disable the tests which ran into the bug

**Comment by Flamefire** [comment]
Test report by @Flamefire
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
taurussmp8 - Linux RHEL 7.7, x86_64, Intel(R) Xeon(R) Platinum 8276M CPU @ 2.20GHz (cascadelake), Python 2.7.5
See https://gist.github.com/31fb22ef0876f80cfade644662706c3b for a full test report.

**Review by Micket — APPROVED** [review]
lgtm

**Review by Micket — APPROVED** [review]
lgtm

**Comment by Micket** [comment]
Just to check, was this unique to 2019b?

**Comment by Micket** [comment]
@boegelbot please test @ generoso
CORE_CNT=16

**Comment by Flamefire** [comment]
> Just to check, was this unique to 2019b?

This was the only one where it occured before. With GCC 9+  the issue at least disappeared. I added the same patch to TF 2.5 (new) though.

**Comment by Micket** [comment]
Going in, thanks @Flamefire!

**Pull request merged**
