### PR TITLE
stick to http download URL in fetchMG easyconfig (https doesn't work)

### PR DESCRIPTION
**Pull request by boegel**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by boegel** [comment]
@boegelbot please test @ generoso

**Comment by migueldiascosta** [comment]
@boegel why doesn't this need to be whitelisted in `check_https`?

**Comment by boegel** [comment]
@migueldiascosta Because that check only complain when the https URL actually works (and it doesn in this case)

**Comment by migueldiascosta** [comment]
@boegel smart test :)

**Review by migueldiascosta — APPROVED** [review]
lgtm

**Comment by migueldiascosta** [comment]
Going in, thanks @boegel!

**Pull request merged**
