### PR TITLE
{math,tools}[GCCcore/11.3.0] jupyter-matlab-proxy v0.5.0, jupyter-contrib-nbextensions v0.7.0, jupyter-server-proxy v3.2.2 w/ Python 3.10.4

### PR DESCRIPTION
**Pull request by lexming**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by lexming** [comment]
@boegelbot: please test @ generoso

**Comment by lexming** [comment]
@boegelbot: please test @ generoso

**Comment by lexming** [comment]
@boegelbot please test @ jsc-zen2

**Comment by Micket** [comment]
How do you actually use this? Do you get to launch the matlab kernel from within jupyter notebook (and if so, does it just open a full window with just the standard matlab-proxy?)

**Comment by lexming** [comment]
@Micket both actually, this version revamps the integration with Jupyter, it provides the usual launcher of the MATLAB web interface in a new window *and* also a kernel to run notebooks with MATLAB code.

It looks like this in JupyterLab
MATLAB launchers in Jupyter Lab

**Review by Micket — APPROVED** [review]
neat. lgtm

**Comment by Micket** [comment]
Test report by @Micket
**SUCCESS**
Build succeeded for 3 out of 3 (3 easyconfigs in total)
vera-c2 - Linux Rocky Linux 8.6, x86_64, Intel Xeon Processor (Skylake), Python 3.6.8
See https://gist.github.com/e25ff842e782a63d1944dfa4262a0b79 for a full test report.

**Comment by Micket** [comment]
Going in, thanks @lexming!

**Pull request merged**
