### PR TITLE
{math}[GCCcore/10.3.0] Gurobi v9.1.2 w/ Python 3.9.5

### PR DESCRIPTION
**Pull request by SIB-software**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by verdurin** [comment]
Test report by @verdurin
**FAILED**
Build succeeded for 0 out of 1 (1 easyconfigs in total)
nuc.lan - Linux Fedora 33, x86_64, Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz, Python 3.9.6
See https://gist.github.com/93ced75c969925165210f3ed10acbc62 for a full test report.

**Comment by verdurin** [comment]
@SIB-software given that this requires a license, could you provide a build test report?

**Comment by Micket** [comment]
Test report by @Micket
**FAILED**
Build succeeded for 0 out of 1 (1 easyconfigs in total)
vera-c1 - Linux centos linux 7.9.2009, x86_64, Intel Xeon Processor (Skylake), Python 3.6.8
See https://gist.github.com/28207fea014c888eefcb342d038ac24f for a full test report.

**Comment by Micket** [comment]
Test report by @Micket
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
vera-c1 - Linux centos linux 7.9.2009, x86_64, Intel Xeon Processor (Skylake), Python 3.6.8
See https://gist.github.com/992932ca65df1ea94f06ae89c4f1d9d7 for a full test report.

**Comment by Micket** [comment]
I have a license, but, I don't store them in that directory, so the hardcoded license_file isn't good.

We should add support for the somewhat-standard 
```
EB_GUROBI_LICENSE_FILE
EB_GUROBI_LICENSE_SERVER
EB_GUROBI_LICENSE_PORT
```
instead. But, that's not related to this specific easyconfig.  In fact, I would like the installer to not copy the license file at all since I normally store them all centrally under a `/apps/licenses/...` path.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
node3119.skitty.os - Linux centos linux 7.9.2009, x86_64, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz (skylake_avx512), Python 3.6.8
See https://gist.github.com/0dc89554873645b6d831976bab208011 for a full test report.

**Comment by boegel** [comment]
@Micket Let's open an issue on that in the easyblocks repository? I agree it shouldn't block this PR...

**Review by boegel — APPROVED** [review]
lgtm

**Comment by boegel** [comment]
Going in, thanks @SIB-software!

**Comment by smoretti** [comment]
I agree @boegel and @Micket 
Gurobi should not be built with a license file in the package, and does not require one at the installation step I guess.

**Pull request merged**
