### PR TITLE
{bio}[GCCcore/13.2.0,foss/2023b] COBRApy v0.29.0, python-libsbml v5.20.2, Check v0.15.2, ...

### PR DESCRIPTION
**Pull request by pavelToman**
(created using `eb --new-pr`)

- [x] depends on #20170

### CODE REVIEW

**Comment by pavelToman** [comment]
@boegelbot please test @ generoso

**Comment by casparvl** [comment]
Test report by @casparvl
**SUCCESS**
Build succeeded for 7 out of 7 (5 easyconfigs in total)
tcn1.local.snellius.surf.nl - Linux RHEL 8.6, x86_64, AMD EPYC 7H12 64-Core Processor, Python 3.6.8
See https://gist.github.com/casparvl/7fbe8a58a9c58e0cddba4783e29db89a for a full test report.

**Comment by casparvl** [comment]
@boegelbot please test @ generoso

**Comment by casparvl** [comment]
@boegelbot please test @ jsc-zen3

**Review by Micket — APPROVED** [review]
lgtm

**Comment by Micket** [comment]
Test report by @Micket
**SUCCESS**
Build succeeded for 9 out of 9 (5 easyconfigs in total)
vera-skylake-build - Linux Rocky Linux 8.9, x86_64, Intel Xeon Processor (Skylake, IBRS, no TSX), Python 3.6.8
See https://gist.github.com/Micket/505b07cd9b7401d7ae971808cc8f4897 for a full test report.

**Comment by casparvl** [comment]
Going in, thanks @pavelToman!

**Pull request merged**
