### PR TITLE
move most recent BLIS and libFLAME easyconfigs from GCC to GCCcore

### PR DESCRIPTION
**Pull request by boegel**
Building BLIS with Intel compilers is problematic (see https://github.com/flame/blis/issues/371), and doesn't make much sense either (no performance benefit in case of BLIS), so let's move these to `GCCcore`...

For the easyconfigs using `GCC/10.2.0` that's not a problem, since they're only in `develop` currently.

requires ~~#12166~~

### CODE REVIEW

**Comment by boegel** [comment]
@boegelbot please test @ generoso

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 6 out of 6 (6 easyconfigs in total)
node3501.doduo.os - Linux RHEL 8.2, x86_64, AMD EPYC 7552 48-Core Processor (zen2), Python 3.6.8
See https://gist.github.com/e075b50ee8f677bbbf59bb5064ab33e3 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 6 out of 6 (6 easyconfigs in total)
node2713.swalot.os - Linux centos linux 7.9.2009, x86_64, Intel(R) Xeon(R) CPU E5-2660 v3 @ 2.60GHz (haswell), Python 3.6.8
See https://gist.github.com/533088b5af36bde18fae5e5185a76c23 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**FAILED**
Build succeeded for 6 out of 9 (9 easyconfigs in total)
node2713.swalot.os - Linux centos linux 7.9.2009, x86_64, Intel(R) Xeon(R) CPU E5-2660 v3 @ 2.60GHz (haswell), Python 3.6.8
See https://gist.github.com/5430b0a4a7faa991765ce3cbd73e2d31 for a full test report.

**Comment by boegel** [comment]
@boegelbot please test @ generoso
EB_ARGS="gobff-2020.06-amd.eb gobff-2020.11.eb gobff-2020b.eb ScaLAPACK-2.1.0-gompi-2020a-bf.eb ScaLAPACK-2.1.0-gompi-2020b-bf.eb ScaLAPACK-2.2-gompi-2020a-amd.eb BLIS-0.8.0-GCCcore-10.2.0.eb BLIS-0.8.0-GCCcore-9.3.0.eb BLIS-2.2-GCCcore-9.3.0-amd.eb libFLAME-2.2-GCCcore-9.3.0-amd.eb libFLAME-5.2.0-GCCcore-10.2.0.eb libFLAME-5.2.0-GCCcore-9.3.0.eb"

**Comment by boegel** [comment]
Test report by @boegel
**FAILED**
Build succeeded for 9 out of 12 (12 easyconfigs in total)
node2713.swalot.os - Linux centos linux 7.9.2009, x86_64, Intel(R) Xeon(R) CPU E5-2660 v3 @ 2.60GHz (haswell), Python 3.6.8
See https://gist.github.com/5b1a2c46d0abdc71e1761cd84f5d4e43 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**FAILED**
Build succeeded for 15 out of 18 (12 easyconfigs in total)
node2713.swalot.os - Linux centos linux 7.9.2009, x86_64, Intel(R) Xeon(R) CPU E5-2660 v3 @ 2.60GHz (haswell), Python 3.6.8
See https://gist.github.com/658be817c271103da31eacc2b141fabd for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 12 out of 12 (12 easyconfigs in total)
node2713.swalot.os - Linux centos linux 7.9.2009, x86_64, Intel(R) Xeon(R) CPU E5-2660 v3 @ 2.60GHz (haswell), Python 3.6.8
See https://gist.github.com/ee904c4b8e053d7e18a8e6115b1d447b for a full test report.

**Comment by bartoldeman** [comment]
Test report by @bartoldeman
**SUCCESS**
Build succeeded for 13 out of 13 (9 easyconfigs in total)
build-node.computecanada.ca - Linux centos linux 7.9.2009, x86_64, Intel Xeon Processor (Skylake, IBRS), Python 3.7.7
See https://gist.github.com/4977f52a98428829861e022688bc8b8b for a full test report.

**Review by bartoldeman — APPROVED** [review]
lgtm

**Pull request merged**
