### PR TITLE
Added support for pkg-config via pkgconfig/bzip2.pc

### PR DESCRIPTION
**Pull request by furstj**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by boegel** [comment]
@furstj Did you write the `bzip2.pc` file yourself, or was it inspired by sources online?

**Comment by furstj** [comment]
The bzip2.pc was inspired by the /usr/lib64/pkgconfig/bzip2.pc from OpenSUSE Leap 15 distribution. Nevertheless OpenSUSE uses several more complicated patches which make the package compatible with autotools and change the source . On the other hand my patch does not change the source code and just adds the bzip2.pc. 

The bzip2.pc file simplifies greatly compilations on OpenSUSE Leap and SLES. Without it, the compilation of e.g. fontconfig fails.

**Comment by boegel** [comment]
@furstj In that case, we should mention (in the patch file) that it was inspired by OpenSUSE, preferably with a URL included that shows where you got it from. No need to pull in the other parts if they're not really needed.

**Comment by furstj** [comment]
I made a notice in the patch file mentioning the original work of S. Brabec from SUSE.

**Comment by boegel** [comment]
@furstj You'll need to fix the checksum accordingly...

Do you mind making this same change (adding the patch file) to all `bzip2` easyconfigs that use `GCCcore` as a toolchain, for consistency sake?

**Comment by furstj** [comment]
Sorry, I forgot to update the checksums. I will make also the same change to all bzip2 easyconfigs (both for GCCcore and Intel toolchains) in a moment.

**Comment by boegel** [comment]
@furstj If you do more than just the `GCCcore` ones, please do *all* for `bzip2` 1.0.6...

**Comment by furstj** [comment]
Ok :). Should I put it in this PR via update-pr or should I make a new PR?

**Comment by boegel** [comment]
@furstj Updating this PR is fine, no need to open a new one.

**Comment by furstj** [comment]
Ok, the mega update is on the way ...

**Comment by akesandgren** [comment]
Can remember... do we autoadd PKG_CONFIG_PATH for simple stuff like this or do the bzip easyconfigs need it added manually?

**Comment by furstj** [comment]
I don't know. Anyway, the patch works fine on SuSE. The module generated for bzip2 automatically sets the PKG_CONFIG_PATH to 

/opt/easybuild/software/bzip2/1.0.6-GCCcore-8.2.0/lib/pkgconfig

**Comment by boegel** [comment]
@furstj You overlooked `bzip2-1.0.6.eb`, let's patch that one too? :)

**Comment by boegel** [comment]
@akesandgren Updating `$PKG_CONFIG_PATH` is done automagically for standard locations, cfr. https://github.com/easybuilders/easybuild-framework/blob/master/easybuild/framework/easyblock.py#L1323

**Comment by furstj** [comment]
Ops, I forgot to include the bzip2-1.0.6.eb in --update-pr. It is included now.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 40 out of 40 (40 easyconfigs in this PR)
node2016.delcatty.os - Linux centos linux 7.6.1810, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.7.5
See https://gist.github.com/a4d2bea80c7806f94f6d5af1eb8a685c for a full test report.

**Comment by boegel** [comment]
Going in, thanks @furstj!

**Pull request merged**
