### PR TITLE
add alternative checksum for Siesta-4.1-MaX-1.0

### PR DESCRIPTION
**Pull request by smoors**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by boegel** [comment]
Diff between old and new source tarball:

```
$ diff -r  siesta-MaX-1.0.old siesta-MaX-1.0
Only in siesta-MaX-1.0.old/Docs: release.sh
Only in siesta-MaX-1.0.old: .gitlab
Only in siesta-MaX-1.0.old/Obj: .gitignore
Only in siesta-MaX-1.0.old/Src/MatrixSwitch: .gitignore
Only in siesta-MaX-1.0.old/Src/ncdf: .gitignore
```

So agreed that both original and current tarball can be considered valid.

**Comment by verdurin** [comment]
@boegelbot please test @ generoso

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in total)
node2630.swalot.os - Linux centos linux 7.9.2009, x86_64, Intel(R) Xeon(R) CPU E5-2660 v3 @ 2.60GHz (haswell), Python 3.6.8
See https://gist.github.com/4a451b0c06ebae6a13c15a879e7d54a2 for a full test report.

**Review by boegel — APPROVED** [review]
lgtm

**Comment by boegel** [comment]
Going in, thanks @smoors!

**Pull request merged**
