### PR TITLE
{lib}[GCCcore/11.3.0] UCC v1.0.0

### PR DESCRIPTION
**Pull request by bartoldeman**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by bartoldeman** [comment]
UCC is supported newly by Open MPI 4.1.4

Note that UCC like UCX can optionally depend on CUDA (and NCCL for UCC only), and uses dynamically loaded components for that.

But fortunately unlike for UCX no special patch is needed, since UCC_COMPONENT_PATH is sufficient and `glob(3)` does the rest.

**Comment by bartoldeman** [comment]
@boegelbot please test @ generoso

**Comment by Micket** [comment]
> Note that UCC like UCX can optionally depend on CUDA (and NCCL for UCC only), and uses dynamically loaded components for that.

so we'll make a `UCC-CUDA` much like `UCX-CUDA` later (once we decide on CUDA version)

**Comment by Micket** [comment]
Test report by @Micket
**SUCCESS**
Build succeeded for 8 out of 8 (1 easyconfigs in total)
alvis-c1 - Linux Rocky Linux 8.5, x86_64, Intel Xeon Processor (Skylake), Python 3.6.8
See https://gist.github.com/4cbd0e63415253f25ee9ee08f0142ab4 for a full test report.

**Comment by jfgrimm** [comment]
Test report by @jfgrimm
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
himem03.pri.viking.alces.network - Linux CentOS Linux 7.9.2009, x86_64, Intel(R) Xeon(R) Gold 6130 CPU @ 2.10GHz (skylake_avx512), Python 3.6.8
See https://gist.github.com/624d01e180ffe2a9ecb7f04b73ee8237 for a full test report.

**Comment by jfgrimm** [comment]
@boegelbot please test @ jsc-zen2

**Review by jfgrimm — APPROVED** [review]
LGTM

**Comment by jfgrimm** [comment]
Going in, thanks @bartoldeman!

**Pull request merged**
