### PR TITLE
{bio}[GCC/9.3.0] SRA-Toolkit v2.10.8

### PR DESCRIPTION
**Pull request by mboisson**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by mboisson** [comment]
This is a version of SRA-Toolkit which uses `HDF5.Serial`, since there really is nothing MPI about this software.

**Comment by mboisson** [comment]
It requires this PR https://github.com/easybuilders/easybuild-easyconfigs/pull/11155

**Comment by zao** [comment]
Test report by @zao
**FAILED**
Build succeeded for 0 out of 1 (1 easyconfigs in this PR)
freja - Linux Ubuntu 20.04, x86_64, Intel(R) Core(TM) i7-8700K CPU @ 3.70GHz, Python 3.8.2
See https://gist.github.com/a775ad61161a2a8b8dbfef74637c0bc5 for a full test report.

**Comment by zao** [comment]
Environment variable for HDF5.Serial is `EBROOTHDF5SERIAL`, `--with-hdf5-prefix=$EBROOTHDF5 ` is erroneous.

**Comment by verdurin** [comment]
@mboisson any thoughts on the most recent comment from @zao ?

**Comment by mboisson** [comment]
@zao good catch.I missed that because we rename the HDF5.Serial -> HDF5, and HDF5 -> HDF5-mpi. locally. Will fix the PR and adjust our hooks accordingly.

**Comment by boegel** [comment]
closing this since `GCC/9.3.0` is deprecated, see https://docs.easybuild.io/policies/toolchains

**Pull request closed without merging**
