### PR TITLE
add TrajectoryUtils + slingshot extensions to R-bundle-Bioconductor 3.16

### PR DESCRIPTION
**Pull request by boegel**
(created using `eb --new-pr`)
requires:
* #18195

### CODE REVIEW

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
node3106.skitty.os - Linux RHEL 8.6, x86_64, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz (skylake_avx512), Python 3.6.8
See https://gist.github.com/boegel/de99fdcb4ce01c438ce068a430272b9a for a full test report.

**Comment by boegel** [comment]
@boegelbot please test @ jsc-zen2
EB_ARGS="--skip"

**Comment by boegel** [comment]
@boegelbot please test @ generoso

**Comment by verdurin** [comment]
Test report by @verdurin
**FAILED**
Build succeeded for 0 out of 1 (1 easyconfigs in total)
easybuild-c7.novalocal - Linux CentOS Linux 7.9.2009, x86_64, Intel Xeon Processor (Skylake, IBRS), Python 3.6.8
See https://gist.github.com/verdurin/333b041377e739b1623f526282b2fd3d for a full test report.

**Comment by jfgrimm** [comment]
Test report by @jfgrimm
**FAILED**
Build succeeded for 0 out of 1 (1 easyconfigs in total)
himem06.pri.viking.alces.network - Linux CentOS Linux 7.9.2009, x86_64, Intel(R) Xeon(R) Platinum 8160 CPU @ 2.10GHz (skylake_avx512), Python 3.6.8
See https://gist.github.com/jfgrimm/71e68d801851fcdfa87ed93962489e57 for a full test report.

**Comment by branfosj** [comment]
> For me it's: `ERROR: dependency princurve is not available for package slingshot`

Added in #18195

**Comment by boegel** [comment]
@boegelbot please test @ generoso
EB_ARGS="--skip"

**Comment by jfgrimm** [comment]
for some reason i get 
```
569288 == 2023-06-28 10:26:49,963 rpackage.py:257 INFO Required dependencies for BiocGenerics: ['methods', 'utils', 'graphics', 'stats', 'methods', 'utils', 'graphics', 'stats']
569289 == 2023-06-28 10:26:49,964 easyblock.py:2004 INFO Required dependencies for BiocGenerics: methods, utils, graphics, stats, methods, utils, graphics, stats
569290 == 2023-06-28 10:26:49,964 easyblock.py:2006 INFO Missing required dependencies for BiocGenerics: methods, utils, graphics, stats, methods, utils, graphics, stats
```

**Comment by boegel** [comment]
> for some reason i get
> 
> ```
> 569288 == 2023-06-28 10:26:49,963 rpackage.py:257 INFO Required dependencies for BiocGenerics: ['methods', 'utils', 'graphics', 'stats', 'methods', 'utils', 'graphics', 'stats']
> 569289 == 2023-06-28 10:26:49,964 easyblock.py:2004 INFO Required dependencies for BiocGenerics: methods, utils, graphics, stats, methods, utils, graphics, stats
> 569290 == 2023-06-28 10:26:49,964 easyblock.py:2006 INFO Missing required dependencies for BiocGenerics: methods, utils, graphics, stats, methods, utils, graphics, stats
> ```

Does `--sanity-check-only` on your R installation pass?

**Comment by jfgrimm** [comment]
@boegel running it now, but I had a successful report yesterday when I tested #18195

**Comment by verdurin** [comment]
Test report by @verdurin
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
easybuild-c7.novalocal - Linux CentOS Linux 7.9.2009, x86_64, Intel Xeon Processor (Skylake, IBRS), Python 3.6.8
See https://gist.github.com/verdurin/eec492f2d4526a0bbfdda5239947cd7a for a full test report.

**Comment by jfgrimm** [comment]
Test report by @jfgrimm
**FAILED**
Build succeeded for 0 out of 1 (1 easyconfigs in total)
himem06.pri.viking.alces.network - Linux CentOS Linux 7.9.2009, x86_64, Intel(R) Xeon(R) Platinum 8160 CPU @ 2.10GHz (skylake_avx512), Python 3.6.8
See https://gist.github.com/jfgrimm/8d93ff244116c12afa3fef33da27ece0 for a full test report.

**Comment by jfgrimm** [comment]
Test report by @jfgrimm
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
himem06.pri.viking.alces.network - Linux CentOS Linux 7.9.2009, x86_64, Intel(R) Xeon(R) Platinum 8160 CPU @ 2.10GHz (skylake_avx512), Python 3.6.8
See https://gist.github.com/jfgrimm/1af9359a92f253b1e5faa007887e619c for a full test report.

**Review by branfosj — APPROVED** [review]

**Comment by branfosj** [comment]
Test report by @branfosj
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
bear-pg0105u03a.bear.cluster - Linux RHEL 8.6, x86_64, Intel(R) Xeon(R) Platinum 8360Y CPU @ 2.40GHz (icelake), Python 3.6.8
See https://gist.github.com/branfosj/a2e3653db6682527d18eb94a783b62f5 for a full test report.

**Comment by branfosj** [comment]
Going in, thanks @boegel!

**Pull request merged**
