### PR TITLE
{bio}[foss/2018b,fosscuda/2018b] GROMACS 2019

### PR DESCRIPTION
**Pull request by akesandgren**
(created using `eb --new-pr`)
In celebration of the new year, here is: GROMACS 2019 with patches

### CODE REVIEW

**Comment by akesandgren** [comment]
Test report by @akesandgren
**SUCCESS**
Build succeeded for 3 out of 3 (3 easyconfigs in this PR)
b-an03.hpc2n.umu.se - Linux ubuntu 16.04, Intel(R) Xeon(R) CPU E5-2690 v4 @ 2.60GHz, Python 2.7.12
See https://gist.github.com/f57a60fa8993937742e25825df605fc4 for a full test report.

**Comment by boegel** [comment]
@akesandgren `make check` fails for me with `GROMACS-2019-intel-2018b.eb` on Intel Skylake, test report coming up...

**Comment by boegel** [comment]
Test report by @boegel
**FAILED**
Build succeeded for 0 out of 1 (1 easyconfigs in this PR)
node3132.skitty.os - Linux centos linux 7.5.1804, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz, Python 2.7.5
See https://gist.github.com/378349af55e4872b97f236c5588d42f6 for a full test report.

**Comment by akesandgren** [comment]
Ok, didn't see that on my build (on skylake). I'll check again. Can you check again too?

**Comment by boegel** [comment]
New test report coming up, but the issue was pretty consistent on my end...

**Comment by boegel** [comment]
Test report by @boegel
**FAILED**
Build succeeded for 0 out of 1 (1 easyconfigs in this PR)
node3131.skitty.os - Linux centos linux 7.6.1810, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz, Python 2.7.5
See https://gist.github.com/adf2b80f9c945e54ff563e64d7edc517 for a full test report.

**Comment by akesandgren** [comment]
Test report by @akesandgren
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
b-cn1501.hpc2n.umu.se - Linux ubuntu 16.04, Intel(R) Xeon(R) Gold 6132 CPU @ 2.60GHz, Python 2.7.12
See https://gist.github.com/93d5e0168632230564145120d34cc1e6 for a full test report.

**Comment by akesandgren** [comment]
Any ideas on how to proceed with this?

**Comment by boegel** [comment]
@akesandgren Looks like very similar issues have been reported in the recent past.

Maybe it's worth reaching out to the GROMACS developers about this to get more info about the possible underlying cause?

**Comment by boegel** [comment]
@akesandgren see https://www.mail-archive.com/gromacs.org_gmx-users@maillist.sys.kth.se/msg31817.html

**Comment by akesandgren** [comment]
Ah, I'll chase them a bit...

**Comment by akesandgren** [comment]
BTW, did you ever test the GROMACS-2019-foss-2018b.eb build?
Would be good to know if it is unrelated to the intel compiler.

**Comment by boegel** [comment]
@akesandgren That works fine I think, test report coming up...

**Comment by boegel** [comment]
Test report by @boegel
**FAILED**
Build succeeded for 1 out of 2 (2 easyconfigs in this PR)
node3100.skitty.os - Linux centos linux 7.6.1810, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz, Python 2.7.5
See https://gist.github.com/54cf204e812eeca2d367f5fb4673eb3f for a full test report.

**Comment by akesandgren** [comment]
Not seen by Gromacs devs, i.e., the intel 2018b problem.

**Comment by boegel** [comment]
@akesandgren Maybe we should split this up so we can at least merge the `foss*` easyconfigs?

**Comment by boegel** [comment]
Test report by @boegel
**FAILED**
Build succeeded for 0 out of 1 (1 easyconfigs in this PR)
node3102.skitty.os - Linux centos linux 7.6.1810, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz, Python 2.7.5
See https://gist.github.com/6bcd1e83309c07123cba63497f849fd9 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
node3102.skitty.os - Linux centos linux 7.6.1810, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz, Python 2.7.5
See https://gist.github.com/6c582779d68555047886368c15e6b768 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
nic155 - Linux centos linux 7.5.1804, Intel(R) Xeon(R) CPU E5-2680 v2 @ 2.80GHz, Python 2.7.5
See https://gist.github.com/4a9bd4e80f03bdedc29efad1a8196bd3 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
node2308.phanpy.os - Linux centos linux 7.6.1810, Intel(R) Xeon(R) CPU E5-2680 v3 @ 2.50GHz, Python 2.7.5
See https://gist.github.com/d1c436e17407e48ac201fd701bc3326a for a full test report.

**Comment by boegel** [comment]
Going in, thanks @akesandgren!

**Pull request merged**
