### PR TITLE
{numlib}[foss/2023a] PETSc v3.20.3, SuperLU_DIST v8.1.2, ParMETIS v4.0.3

### PR DESCRIPTION
**Pull request by furstj**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by furstj** [comment]
Requires easyblock from #3086

**Comment by boegel** [comment]
@boegelbot please test @ generoso
EB_ARGS="--include-easyblocks-from-pr 3086"

**Comment by boegel** [comment]
@boegelbot please test @ jsc-zen3
EB_ARGS="--include-easyblocks-from-pr 3086"

**Review by boegel — APPROVED** [review]
lgtm

**Comment by maxim-masterov** [comment]
PETSc 3.20.3 is not tested against SuiteSparse 7.1.0. Is it a good idea to build against it?

**Comment by boegel** [comment]
> PETSc 3.20.3 is not tested against SuiteSparse 7.1.0. Is it a good idea to build against it?

We're running the PETSc test suite (`make test`) as a part of the installation, and that didn't reveal any problems...

Where do you get the info that PETSc is not tested against SuiteSparse 7.1.0?

**Comment by furstj** [comment]
As far as I remember, my first version was with SuiteSparse 5.13. But boegelbot complained that there is SuiteSparse 7.1.0 already in the dependencies.

In any case, the easybuild runs "make tests" and these tests call also SuiteSparse (try to look for the word "_umfpack" in build log).

**Comment by boegel** [comment]
Going in, thanks @furstj!

**Comment by casparvl** [comment]
Test report by @casparvl
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
tcn1.local.snellius.surf.nl - Linux RHEL 8.6, x86_64, AMD EPYC 7H12 64-Core Processor, Python 3.6.8
See https://gist.github.com/casparvl/7ebb3e18936bb5818f9e6c60f4930f39 for a full test report.

**Pull request merged**
