### PR TITLE
{math}[dummy] Maple 17/18 (REVIEW)

### PR DESCRIPTION
**Pull request by boegel**
requires https://github.com/hpcugent/easybuild-easyblocks/pull/539

@wpoely86: please review?

### CODE REVIEW

**Comment by wpoely86** [comment]
Looks fine but add version 18 while you're at it.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
Linux SL 6.6, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.6.6
See https://gist.github.com/b15e9f1ca45c374ea360 for a full test report.

**Comment by boegel** [comment]
@wpoely86: easyconfig for Maple 18 added

**Comment by boegel** [comment]
Test report by @boegel
**FAILED**
Build succeeded for 2 out of 3 (3 easyconfigs in this PR)
Linux SL 6.6, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.6.6
See https://gist.github.com/eba09c1d20a1df8199ba for a full test report.

**Comment by boegel** [comment]
easyconfig for Maple 18 should now also work, after enhancements to the Maple easyblock in https://github.com/hpcugent/easybuild-easyblocks/pull/539, test report is on it's way...

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 3 out of 3 (3 easyconfigs in this PR)
Linux SL 6.6, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.6.6
See https://gist.github.com/86375e448a484b125bfa for a full test report.

**Comment by boegel** [comment]
@wpoely86: up for testing this on top of https://github.com/hpcugent/easybuild-easyblocks/pull/539 before I merge these in?

**Comment by wpoely86** [comment]
Test report by @wpoely86
**FAILED**
Build succeeded for 0 out of 3 (3 easyconfigs in this PR)
Linux debian 7.8, Intel(R) Xeon(R) CPU            5130  @ 2.00GHz, Python 2.7.3
See https://gist.github.com/c98de4a7f597854d7b70 for a full test report.

**Comment by wpoely86** [comment]
@boegel when `DISPLAY` is set, it launches the gui installer

**Comment by wpoely86** [comment]
Test report by @wpoely86
**FAILED**
Build succeeded for 2 out of 3 (3 easyconfigs in this PR)
Linux debian 7.8, Intel(R) Xeon(R) CPU            5130  @ 2.00GHz, Python 2.7.3
See https://gist.github.com/8907709157f4c532a40d for a full test report.

**Comment by wpoely86** [comment]
Test report by @wpoely86
**FAILED**
Build succeeded for 2 out of 3 (3 easyconfigs in this PR)
Linux debian 7.8, Intel(R) Xeon(R) CPU            5130  @ 2.00GHz, Python 2.7.3
See https://gist.github.com/8fd81d388fe8eef140be for a full test report.

**Comment by migueldiascosta** [comment]
@boegel, this PR is being closed for the following reason(s): no activity for > 6 months.
Please don't hesitate to reopen this PR or add a comment if you feel this contribution is still relevant.
For more information on our policy w.r.t. closing PRs, see https://easybuild.readthedocs.io/en/latest/Contributing.html#why-a-pull-request-may-be-closed-by-a-maintainer

**Pull request closed without merging**
