### PR TITLE
fix using system qhull and freetype for matplotlib

### PR DESCRIPTION
**Pull request by smoors**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by smoors** [comment]
@boegelbot: please test @ generoso

**Comment by smoors** [comment]
Test report by @smoors
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
node301.hydra.os - Linux CentOS Linux 7.9.2009, x86_64, Intel(R) Xeon(R) Gold 6148 CPU @ 2.40GHz (skylake_avx512), Python 2.7.5
See https://gist.github.com/0d8b80a5473c4576ef96ac32190c49aa for a full test report.

**Comment by branfosj** [comment]
This also needs changing in [`matplotlib-3.5.2-intel-2022a.eb`](https://github.com/easybuilders/easybuild-easyconfigs/blob/develop/easybuild/easyconfigs/m/matplotlib/matplotlib-3.5.2-intel-2022a.eb#L33)?

**Comment by smoors** [comment]
@boegelbot: please test @ generoso

**Review by branfosj — APPROVED** [review]
lgtm

**Comment by branfosj** [comment]
Test report by @branfosj
**SUCCESS**
Build succeeded for 6 out of 6 (2 easyconfigs in total)
bear-pg0105u36b.bear.cluster - Linux RHEL 8.6, x86_64, Intel(R) Xeon(R) Platinum 8360Y CPU @ 2.40GHz (icelake), Python 3.6.8
See https://gist.github.com/f15c262983a8dc26b0868b5cdc28e397 for a full test report.

**Comment by branfosj** [comment]
Going in, thanks @smoors!

**Pull request merged**
