### PR TITLE
GTS - Add pkg-config build dependency

### PR DESCRIPTION
**Pull request by vanzod**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by boegel** [comment]
@vanzod Any reason you skipped `GTS-0.7.6-intel-2014b.eb`?

**Comment by vanzod** [comment]
@boegel Actually, three reasons:
1. I'm lazy
2. intel-2014b or corresponding minimal toolchains do not have a `pkg-config` easyconfig
3. The toolchain is old enough that I deemed the effort of creating a new `pkg-config` (see point #1)

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 6 out of 6 (6 easyconfigs in this PR)
node2002.delcatty.os - Linux centos linux 7.5.1804, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.7.5
See https://gist.github.com/da15ec4e04344daf6c4e6a50cdda02f1 for a full test report.

**Comment by boegel** [comment]
@vanzod I agree it's not worth the trouble...

**Comment by boegel** [comment]
Going in, thanks @vanzod!

**Pull request merged**
