### PR TITLE
Add preinstallopts for minimap2 to fix installation on aarch64

### PR DESCRIPTION
**Pull request by rungitta**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
select-pika-c6gd-2xlarge-0001 - Linux centos linux 8.3.2011, AArch64, ARM UNKNOWN (graviton2), Python 3.6.8
See https://gist.github.com/3dfc69d2a499a3a81386f395249c8438 for a full test report.

**Comment by boegel** [comment]
@boegelbot please test @ generoso

**Review by boegel — APPROVED** [review]
lgtm

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
node3119.skitty.os - Linux centos linux 7.9.2009, x86_64, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz, Python 3.6.8
See https://gist.github.com/13e02bcee00b581ca749b0174ff418f9 for a full test report.

**Comment by rungitta** [comment]
@boegel Are these failed tests expected behaviour?
 
And why is this being tested?
 `XGBoost-20171120-intel-2017b-Java-1.8.0_152.eb`

**Comment by boegel** [comment]
> @boegel Are these failed tests expected behaviour?
> 
> And why is this being tested?
> `XGBoost-20171120-intel-2017b-Java-1.8.0_152.eb`

That's a problem somewhere else, I'll get that fixed...

**Comment by verdurin** [comment]
Going in, thanks @rungitta!

**Pull request merged**
