### PR TITLE
{bio}[foss/2018b] MEGAHIT v1.2.9 w/ Python 2.7.15 + 3.6.6

### PR DESCRIPTION
**Pull request by SethosII**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by SethosII** [comment]
Test report by @SethosII
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
ribnode015 - Linux ubuntu 18.04, x86_64, Intel(R) Xeon(R) CPU           E5645  @ 2.40GHz, Python 2.7.17
See https://gist.github.com/57094e2cdaba4bf92c362618ed2511cd for a full test report.

**Comment by smoors** [comment]
Test report by @smoors
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
node381.hydra.os - Linux centos linux 7.9.2009, x86_64, Intel(R) Xeon(R) Gold 6148 CPU @ 2.40GHz (skylake_avx512), Python 2.7.5
See https://gist.github.com/8c33d903cdce4b393ced41a494c46ac6 for a full test report.

**Review by smoors — APPROVED** [review]
lgtm

**Comment by smoors** [comment]
Going in, thanks @SethosII!

**Pull request merged**
