### PR TITLE
{numlib}[intel/2021a] FFTW v3.3.9

### PR DESCRIPTION
**Pull request by stevenvdb**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by stevenvdb** [comment]
I assume the patch for the previous FFTW version (https://github.com/easybuilders/easybuild-easyconfigs/pull/11050) is no longer necessary (fixed in https://github.com/FFTW/fftw3/commit/10e2040af822a08ed49d2f6a1db45a7a3ad50582), but I have not actually tested it on CentOS 8.

**Comment by Micket** [comment]
@boegelbot please test @ generoso

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
node3168.skitty.os - Linux centos linux 7.9.2009, x86_64, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz, Python 3.6.8
See https://gist.github.com/26352e9f9e4a91029014bb59bb5e577c for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
node2618.swalot.os - Linux centos linux 7.9.2009, x86_64, Intel(R) Xeon(R) CPU E5-2660 v3 @ 2.60GHz (haswell), Python 3.6.8
See https://gist.github.com/6da1db12b207e550f8a1f6785eac0eaf for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
node3600.doduo.os - Linux RHEL 8.2, x86_64, AMD EPYC 7552 48-Core Processor (zen2), Python 3.6.8
See https://gist.github.com/58e6a8b9d6e53922523154b962787f83 for a full test report.

**Comment by boegel** [comment]
Going in, thanks @stevenvdb!

**Pull request merged**
