### PR TITLE
add --without-systemdsystemunitdir configure option to recent DBus easyconfigs

### PR DESCRIPTION
**Pull request by jose-d**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by jose-d** [comment]
Dbus is by default trying install systemd unit files, and if EB has no rights, it'll fail:

```
/usr/bin/install: cannot remove ‘/usr/lib/systemd/system/dbus.service’: Permission denied
/usr/bin/install: cannot remove ‘/usr/lib/systemd/system/dbus.socket’: Permission denied
make[2]: *** [install-systemdsystemunitDATA] Error 1
make[2]: Leaving directory `/home/users/jose/.local/easybuild/build/DBus/1.13.6/GCCcore-7.3.0/dbus-1.13.6/bus'
make[1]: *** [install-am] Error 2
make[1]: Leaving directory `/home/users/jose/.local/easybuild/build/DBus/1.13.6/GCCcore-7.3.0/dbus-1.13.6/bus'
make: *** [install-recursive] Error 1
```

In most of the cases, EasyBuild has no rights to do so, so I believe we should include `--without-systemdsystemunitdir`. But anyway, I am surprised that I am first one who found this - isn't there anything I missed?

**Comment by jose-d** [comment]
Test report by @jose-d
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
koios2 - Linux centos linux 7.3.1611, Intel(R) Xeon(R) Gold 6130 CPU @ 2.10GHz, Python 2.7.5
See https://gist.github.com/c0265293b7051682b3fd3af4e4d75489 for a full test report.

**Comment by boegel** [comment]
Adding that configure option makes sense obviously, but it should be done consistently in the recent `DBus` easyconfig, can you make it so?

I'm also a bit surprised that this hasn't popped up before... In the `configure` output in the log I'm seeing this though:

```
checking for SYSTEMD... no
```

Even though the test system *is* using systemd (CentOS 7.5)...

I suspect you have something different?

**Comment by jose-d** [comment]
> it should be done consistently in the recent `DBus` easyconfig, can you make it so?

yep. I just wanted to have second opinion before I'll spent more time on this.
This case occurred on bare-metal so I'll try it once again in container on more _fresh_ OS installation to be sure, and then I'll patch all DBus ecs.

> Even though the test system _is_ using systemd (CentOS 7.5)...

Isn't testsystem in it some kind of containers? 
I know that at least Centos7 Docker one can see some systemd tweaks.

> I suspect you have something different?

just checked rpms and I'm on latest centos7 with _not so latest_ kernel and its deps.

**Comment by jose-d** [comment]
IMO we can try to blame containerization:

**configure**:

container (Singularity):

```
...
checking for launchctl... no
checking for SYSTEMD... no
checking for SYSTEMD... no
checking for systemctl... /bin/systemctl
...
Building systemd support: no
...
```

on real server (centos7 mentioned above):

```
...
checking for launchctl... no
checking for SYSTEMD... yes
checking for systemctl... /usr/bin/systemctl
...
Building systemd support: yes
...
```

so let's fix it.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 4 out of 4 (4 easyconfigs in this PR)
node2001.delcatty.os - Linux centos linux 7.6.1810, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.7.5
See https://gist.github.com/59c581cf253e2de676e36d7bb7535d8c for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 4 out of 4 (4 easyconfigs in this PR)
node2617.swalot.os - Linux centos linux 7.6.1810, Intel(R) Xeon(R) CPU E5-2660 v3 @ 2.60GHz, Python 2.7.5
See https://gist.github.com/5ac41934557d3e5b758547559d19c966 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 4 out of 4 (4 easyconfigs in this PR)
node3111.skitty.os - Linux centos linux 7.6.1810, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz, Python 2.7.5
See https://gist.github.com/40ebec10e0100d4eeb931cf5cef5fa61 for a full test report.

**Comment by boegel** [comment]
Going in, thanks @jose-d!

**Pull request merged**
