### PR TITLE
{vis, data, tools, lib}[GCCcore/13.3.0] at-spi2-atk-2.38.0, at-spi2-core-2.54.0, exiv2-0.28.3, GraphicsMagick-1.3.45, HDF-4.3.0, IPython-8.27.0, inih-58, libgeotiff-1.7.3

### PR DESCRIPTION
**Pull request by ankekreuzer**
A few more packages from the JSC SW stack in GCCcore-13.3.0

This PR needs:
- `Szip` from #21417 
- `PROJ` from #21372 
- `libtirpc` from #21282

### CODE REVIEW

**Comment by ankekreuzer** [comment]
Test report by @ankekreuzer
**SUCCESS**
Build succeeded for 9 out of 9 (9 easyconfigs in total)
zam329 - Linux Rocky Linux 9.4 (Blue Onyx), x86_64, Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz, Python 3.9.18
See https://gist.github.com/ankekreuzer/559e4b7cb22ca7870914fc5b779eddff for a full test report.

**Comment by SebastianAchilles** [comment]
jedi 0.19.1 was merged in https://github.com/easybuilders/easybuild-easyconfigs/pull/21685 The content is the same, so I would suggest we remove it from this PR.

**Comment by SebastianAchilles** [comment]
Test report by @sebastianachilles
**SUCCESS**
Build succeeded for 9 out of 9 (9 easyconfigs in total)
bwd-rockylinux-94 - Linux Rocky Linux 9.4 (Blue Onyx), x86_64, Intel(R) Core(TM) i7-6900K CPU @ 3.20GHz (broadwell), 2 x NVIDIA NVIDIA GeForce GTX 1060 6GB, 535.183.06, Python 3.9.18
See https://gist.github.com/SebastianAchilles/c1d8c53b71b4285b4057915f1e1959cc for a full test report.

**Comment by SebastianAchilles** [comment]
@boegelbot please test @ jsc-zen3

**Comment by SebastianAchilles** [comment]
@boegelbot please test @ generoso

**Review by SebastianAchilles — APPROVED** [review]
lgtm

**Comment by SebastianAchilles** [comment]
Going in, thanks @ankekreuzer!

**Pull request merged**
