### PR TITLE
[MathGL] Don't use MPI cxx during build

### PR DESCRIPTION
**Pull request by Flamefire**
Fixes https://github.com/easybuilders/easybuild-easyconfigs/issues/9640

### CODE REVIEW

**Comment by migueldiascosta** [comment]
Test report by @migueldiascosta
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
generoso - Linux centos linux 7.6.1810, Intel(R) Xeon(R) CPU E5-2660 v4 @ 2.00GHz, Python 3.6.8
See https://gist.github.com/d4c7a2cd239f5950ceebc19eac9e3a45 for a full test report.

**Comment by Flamefire** [comment]
Test report by @Flamefire
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
taurusi6258.taurus.hrsk.tu-dresden.de - Linux RHEL 7.7, Intel(R) Xeon(R) CPU E5-2680 v3 @ 2.50GHz, Python 2.7.5
See https://gist.github.com/d51258fa330229bda60c229e9f4da3a6 for a full test report.

**Comment by verdurin** [comment]
Test report by @verdurin
**SUCCESS**
Build succeeded for 41 out of 41 (1 easyconfigs in this PR)
easybuild.novalocal - Linux centos linux 7.7.1908, Intel Xeon Processor (Skylake, IBRS), Python 2.7.5
See https://gist.github.com/de07873addf88172547457117bba5986 for a full test report.

**Comment by verdurin** [comment]
Going in, thanks @Flamefire!

**Pull request merged**
