### PR TITLE
{vis}[foss/2017b,intel/2017b] Graphviz v2.40.1

### PR DESCRIPTION
**Pull request by vanzod**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by vanzod** [comment]
Test report by @vanzod
**SUCCESS**
Build succeeded for 4 out of 4 (4 easyconfigs in this PR)
cermis - Linux debian 9.5, Intel(R) Xeon(R) CPU           E5620  @ 2.40GHz, Python 2.7.13
See https://gist.github.com/efb777595da744092c157fd9b540db2c for a full test report.

**Comment by vanzod** [comment]
@boegel We are in conflict hell again... What do you want to do?

**Comment by boegel** [comment]
@vanzod No way to fix the conflicts?

**Comment by vanzod** [comment]
Closing this PR due to unsolvable dependencies version conflicts arising from the 2017b and 2018a common toolchains sharing `GCCcore/6.4.0`.

**Pull request closed without merging**
