### PR TITLE
{phys}[intel/2021a] Yambo v5.0.4

### PR DESCRIPTION
**Pull request by dithwick**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by migueldiascosta** [comment]
@dithwick looking at the install log locally, this is downloading a few extra packages (`https://codeload.github.com/yambo-code/yambo-libraries/tar.gz/0.0.2`, `https://github.com/yambo-code/yambo/files/783150/libxc-2.2.3.tar.gz`, `https://github.com/yambo-code/yambo/files/962173/iotk-y1.2.2.tar.gz`) - if it's possible to add them to the `sources` and skip the download, it would make it easier for people using `--fetch`, in particular when preparing to install in nodes without internet access

**Comment by dithwick** [comment]
@migueldiascosta I'll take a look and see how straightforward it is.

**Comment by dithwick** [comment]
@migueldiascosta can you try this new version? Thanks

**Comment by SebastianAchilles** [comment]
@boegelbot please test @ generoso

**Comment by SebastianAchilles** [comment]
Test report by @sebastianachilles
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
jsfc01.int.jusuf.sebastian.cluster - Linux rocky linux 8.4, x86_64, AMD EPYC 7742 64-Core Processor (zen2), 1 x NVIDIA GRID V100-4C, 460.73.01, Python 3.6.8
See https://gist.github.com/c6d067436f561aecd7ae74984706f239 for a full test report.

**Review by migueldiascosta — APPROVED** [review]
lgtm

**Comment by migueldiascosta** [comment]
Going in, thanks @dithwick!

**Pull request merged**
