### PR TITLE
{devel}[GCCcore/11.2.0] GConf v3.2.6

### PR DESCRIPTION
**Pull request by sassy-crick**
(created using `eb --new-pr`)

Requires:
- [x] PR #16081

### CODE REVIEW

**Comment by zao** [comment]
Test report by @zao
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
eb-u2204 - Linux Ubuntu 22.04, x86_64, AMD Ryzen 9 3900X 12-Core Processor, Python 3.10.4
See https://gist.github.com/2e2a53092769fd9cba7ee8698ab56509 for a full test report.

**Comment by fizwit** [comment]
Please add pkg-config to builddependenccies.

```
configure: error: in `/build/GConf/3.2.6/GCCcore-11.2.0/GConf-3.2.6':
configure: error: The pkg-config script could not be found or is too old.  Make sure it
is in your PATH or set the PKG_CONFIG environment variable to the full
path to pkg-config.

--- GConf-3.2.6-GCCcore-11.2.0.eb       2022-09-27 09:21:14.854314823 -0700
+++ GConf-3.2.6-GCCcore-11.2.0.eb.1     2022-09-27 09:23:15.179048127 -0700
@@ -34,7 +34,6 @@
 builddependencies = [
     ('binutils', '2.37'),
     ('GObject-Introspection', '1.68.0'),
+    ('pkg-config', '0.29.2'),
 ]

 dependencies = [
 ```

**Comment by sassy-crick** [comment]
Thanks for pointing that out. I have added `('pkgconf', '1.8.0')` instead of the suggested `pkg-config` as the former is more modern compared to the latter. I think that is also in line with some recent discussions.

**Comment by boegel** [comment]
@boegelbot please test @ generoso

**Review by boegel — APPROVED** [review]
lgtm

**Comment by boegel** [comment]
Going in, thanks @sassy-crick!

**Pull request merged**
