### PR TITLE
{numlib}[GCCcore/10.3.0] BLIS v3.0.1

### PR DESCRIPTION
**Pull request by robert-mijakovic**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by robert-mijakovic** [comment]
@boegelbot please test @ generoso

**Comment by verdurin** [comment]
@robert-mijakovic I'm half-wondering whether we should change even the minor version of this during one toolchain release? Don't think we would do that with e.g. `OpenBLAS`. Perhaps @Micket and @ocaisa have thoughts?

**Comment by lexming** [comment]
Test report by @lexming
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
node226.hydra.os - Linux centos linux 7.9.2009, x86_64, Intel(R) Xeon(R) CPU E5-2680 v4 @ 2.40GHz, Python 2.7.5
See https://gist.github.com/18e46ac61d39ce390681e482a09d3cf1 for a full test report.

**Comment by lexming** [comment]
@verdurin I think that it's ok to add new software updates in existing toolchains. We just have to stick to existing toolchain definitions and the dependencies allowed in those toolchains. So this version of BLIS can live standalone. It's similar to the addition of `GCC/9.4.0`, which is available for users but cannot be used in major toolchains.

**Comment by lexming** [comment]
Going in, thanks @robert-mijakovic !

**Review by lexming — APPROVED** [review]
LGTM

**Comment by lexming** [comment]
Going in, thanks @robert-mijakovic !

**Pull request merged**
