### PR TITLE
fix installation of fmesher within R-INLA

### PR DESCRIPTION
**Pull request by lexming**
Changelog:

* add link to `bin/fmesher` into `INLA/bin/linux/64bit/`, in the same way that we already do for `bin/inla`
* patch out hardcoded paths from `fmesher.run`, in the same way that we already do for `inla.run`
* improve sanity checks

### CODE REVIEW

**Review by boegel — APPROVED** [review]
lgtm

**Comment by boegel** [comment]
@boegelbot please test @ generoso

**Comment by boegel** [comment]
@lexming This will need a sync with `develop` and some more love, now that ~#12927~ is merged...

**Comment by boegel** [comment]
@lexming The checksum for the patch file will need fixing too, since it was tweaked in ~#12927~?

**Comment by lexming** [comment]
@boegel I'm touching a different patch than the one updated in #12927

**Comment by boegel** [comment]
> @boegel I'm touching a different patch than the one updated in #12927

Ah, I overlooked that :D
Then this should be good to go, indeed.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
node3595.doduo.os - Linux RHEL 8.2, x86_64, AMD EPYC 7552 48-Core Processor (zen2), Python 3.6.8
See https://gist.github.com/c2faf50d51a6fcec47f870087b087b9a for a full test report.

**Review by boegel — APPROVED** [review]
lgtm

**Comment by boegel** [comment]
Going in, thanks @lexming!

**Pull request merged**
