### PR TITLE
{bio}[GCC/8.2.0] Unicycler v0.4.7, Bowtie2 v2.3.5.1, SAMtools v1.9, SPAdes v3.13.1 w/ Python 3.7.2

### PR DESCRIPTION
**Pull request by smoors**
(created using `eb --new-pr`)
depends on ~~#8375~~

### CODE REVIEW

**Comment by smoors** [comment]
closing and reopening to trigger travis

**Comment by smoors** [comment]
Test report by @smoors
**SUCCESS**
Build succeeded for 4 out of 4 (4 easyconfigs in this PR)
nic412 - Linux centos linux 7.5.1804, Intel(R) Xeon(R) Gold 6148 CPU @ 2.40GHz, Python 2.7.5
See https://gist.github.com/d897c68e9566f6ff1e915d75f321516d for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 4 out of 4 (4 easyconfigs in this PR)
node2658.swalot.os - Linux centos linux 7.6.1810, Intel(R) Xeon(R) CPU E5-2660 v3 @ 2.60GHz, Python 2.7.5
See https://gist.github.com/107cdfa75a007f0a50d83526555952f8 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 4 out of 4 (4 easyconfigs in this PR)
node2053.delcatty.os - Linux centos linux 7.6.1810, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.7.5
See https://gist.github.com/32543e33e8de18c38441f2226072282c for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 8 out of 8 (4 easyconfigs in this PR)
node3124.skitty.os - Linux centos linux 7.6.1810, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz, Python 2.7.5
See https://gist.github.com/b8eb655ab89439d3365627033a134bc6 for a full test report.

**Comment by boegel** [comment]
Going in, thanks @smoors!

**Pull request merged**
