### PR TITLE
add missing Perl and Autotools build dependencies in recent WRF easyconfigs

### LINKED ISSUE #12271: Missing M4 and Perl build dependency in WRF-3.9.1.1
Issues:

- When building on a minimal OS, the `WRF-3.9.1.1-foss-2020a-dmpar` build fails at configure because of missing `M4`.

- The configure script also requires Perl which is taken from the system if not added to the build dependencies list.

Other versions might likely be affected.

```
$ ./configure
checking for perl5... no
checking for perl... found /usr/bin/perl (perl)
Will use NETCDF in dir: /cvmfs/hc44rs.azure/centos/7.7/software/netCDF/4.7.4-gompi-2020a
Will use HDF5 in dir: /cvmfs/hc44rs.azure/centos/7.7/software/HDF5/1.10.6-gompi-2020a
Will use PHDF5 in dir: /cvmfs/hc44rs.azure/centos/7.7/software/HDF5/1.10.6-gompi-2020a
./configure: line 621: type: m4: not found

ERROR ERROR ERROR ERROR ERROR ERROR ERROR
'm4' utility not found! Can not configure.

If on an Ubuntu machine, use the command
         sudo apt-get install m4        
To download and install the 'm4' utility
```

### PR DESCRIPTION
**Pull request by boegel**
(created using `eb --new-pr`)

fixes #12271

### CODE REVIEW

**Review by Micket — DISMISSED** [review]
lgtm

**Comment by boegel** [comment]
I'll work on a (single) full test report for this, will take a while...

**Comment by boegel** [comment]
@boegelbot please test @ generoso
EB_ARGS="WRF-3.9.1.1-foss-2020a-dmpar.eb WRF-3.9.1.1-intel-2020a-dmpar.eb WRF-4.1.3-foss-2019b-dmpar.eb WRF-4.1.3-intel-2019b-dm+sm.eb WRF-4.1.3-intel-2019b-dmpar.eb"
CORE_CNT=16

**Comment by verdurin** [comment]
Test report by @verdurin
**SUCCESS**
Build succeeded for 7 out of 7 (2 easyconfigs in total)
nuc.lan - Linux Fedora 32, x86_64, Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz, Python 3.8.7
See https://gist.github.com/5ca78d5eb0d470d9038c9e21e8f70bb4 for a full test report.

**Review by branfosj — APPROVED** [review]
lgtm

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 7 out of 7 (7 easyconfigs in total)
node2719.swalot.os - Linux centos linux 7.9.2009, x86_64, Intel(R) Xeon(R) CPU E5-2660 v3 @ 2.60GHz (haswell), Python 3.6.8
See https://gist.github.com/d1aac3b0eb420f5574aaa295ae416ade for a full test report.

**Comment by branfosj** [comment]
Going in, thanks @boegel!

**Pull request merged**
