### PR TITLE
fix checksum for Stacks v2.62 (due to silent re-release without version bump)

### PR DESCRIPTION
**Pull request by boegel**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by boegel** [comment]
Diff between old source tarball (downloaded on 2022-08-08 when testing #15997) and new source tarball (downloaded today, 2022-08-26):

```diff
$ diff -ru stacks-2.62.old stacks-2.62.new
diff -ru stacks-2.62.old/ChangeLog stacks-2.62.new/ChangeLog
--- stacks-2.62.old/ChangeLog	2022-06-28 20:09:25.000000000 +0000
+++ stacks-2.62.new/ChangeLog	2022-07-26 19:23:17.000000000 +0000
@@ -6,6 +6,9 @@
     Feature: improved ustacks logging to include final number of assembled
              loci; modified denovo_map.pl to include this in its logging output.
              Improved logging in populations program.
+    Feature: Added variant of PstI cutsite to process_radtags: pstishi only
+             leaves "GCAG" as the cutsite remnant, published in:
+	     Shirasawa, Hirakawa, and Isobe, 2016, DNA Research; doi: 10.1093/dnares/dsw004
     Bugfix: fixed assert() failure in populations when no population map was
             specified.
     Bugfix: updated stacks-dist-extract --pretty print to better handle
Binary files stacks-2.62.old/libcore.a and stacks-2.62.new/libcore.a differ
diff -ru stacks-2.62.old/scripts/denovo_map.pl stacks-2.62.new/scripts/denovo_map.pl
--- stacks-2.62.old/scripts/denovo_map.pl	2022-06-20 15:33:24.000000000 +0000
+++ stacks-2.62.new/scripts/denovo_map.pl	2022-08-08 18:32:59.000000000 +0000
@@ -894,7 +894,7 @@

   Stack assembly options:
     -M: number of mismatches allowed between stacks within individuals (for ustacks).
-    -n: number of mismatches allowed between stacks between individuals (for cstacks; default 1; suggested: set to ustacks -M).
+    -n: number of mismatches allowed between stacks between individuals (for cstacks; default: set to ustacks -M).

   SNP model options:
     --var-alpha: significance level at which to call variant sites (for gstacks; default: 0.05).
diff -ru stacks-2.62.old/src/renz.cc stacks-2.62.new/src/renz.cc
--- stacks-2.62.old/src/renz.cc	2021-11-16 19:16:06.000000000 +0000
+++ stacks-2.62.new/src/renz.cc	2022-07-26 19:20:29.000000000 +0000
@@ -112,6 +112,9 @@
                          "GCTCGA", "CCTCGA", "ACTCGA"};
 const char *pstI[]    = {"TGCAG",             // CTGCA/G, PstI
                          "CTGCA"};
+const char *pstIshi[] = {"GCAG",              // CTGCA/G, PstI;
+                         "CTGC"};             //   Modified so that "CT" is part of the Illumina sequencing primer and not in the final sequence.
+                                              //   As published in Shirasawa, Hirakawa, and Isobe, 2016, DNA Research; doi: 10.1093/dnares/dsw004
 const char *rsaI[]    = {"AC",                // GT/AC, RsaI
                          "GT"};
 const char *sacI[]    = {"AGCTC",             // GAGCT/C, SacI
@@ -140,6 +143,7 @@

     renz["sbfI"]    = sbfI;    // CCTGCA/GG, SbfI
     renz["pstI"]    = pstI;    // CTGCA/G, PstI
+    renz["pstIshi"] = pstIshi; // CTGCA/G, PstI-SHI
     renz["notI"]    = notI;    // GC/GGCCGC, NotI
     renz["ecoRI"]   = ecoRI;   // G/AATTC, EcoRI
     renz["nspI"]    = nspI;
@@ -199,6 +203,7 @@

     renz_cnt["sbfI"]    = 1;
     renz_cnt["pstI"]    = 1;
+    renz_cnt["pstIshi"] = 1;
     renz_cnt["notI"]    = 1;
     renz_cnt["ecoRI"]   = 1;
     renz_cnt["nspI"]    = 2;
@@ -258,6 +263,7 @@

     renz_len["sbfI"]    = 6;
     renz_len["pstI"]    = 5;
+    renz_len["pstIshi"] = 4;
     renz_len["notI"]    = 6;
     renz_len["ecoRI"]   = 5;
     renz_len["nspI"]    = 5;
```

**Comment by boegel** [comment]
@boegelbot please test @ jsc-zen2
EB_ARGS="--force-download"

**Comment by boegel** [comment]
@boegelbot please test @ generoso

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
node3127.skitty.os - Linux RHEL 8.4, x86_64, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz (skylake_avx512), Python 3.6.8
See https://gist.github.com/04b7648e5b7cb07bae9b75170472c4b5 for a full test report.

**Comment by sassy-crick** [comment]
Test report by @sassy-crick
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
hp - Linux Debian GNU/Linux 11, x86_64, 11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz, Python 3.9.2
See https://gist.github.com/7f797a33534b974f586aba043b7281ec for a full test report.

**Comment by akesandgren** [comment]
I think this should really get a separate version....

**Comment by boegel** [comment]
> I think this should really get a separate version....

Like what?
We can't help it that the source tarball was changed upstream, and since the old source tarball is no longer available, this seems like the right way to fix this imho.

By changing the checksum people should notice that something is wrong if they try to install without re-downloading

**Comment by boegel** [comment]
@akesandgren As discussed, since this version of Stacks was only merged into `develop` very recently (see #15997), and not included in an EasyBuild release yet, this is good to be merged?

**Comment by akesandgren** [comment]
Yes good to merge, processing.

**Review by akesandgren — APPROVED** [review]
LGTM

**Comment by akesandgren** [comment]
Going in, thanks @boegel!

**Pull request merged**
