### PR TITLE
{numlib}[system/system] cuDNN v8.0.4.30

### PR DESCRIPTION
**Pull request by branfosj**
(created using `eb --new-pr`)

Based on the discussion in #11542, I think this is what is wanted for cuDNN for 2020a.

### CODE REVIEW

**Comment by branfosj** [comment]
Test report by @branfosj
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
bear-pg0306u19a.bear.cluster - Linux RHEL 8.2, POWER, 8335-GTX (power9le), Python 3.6.8
See https://gist.github.com/8a8e5e3433a9ebc609a8cb527e174480 for a full test report.

**Comment by branfosj** [comment]
Test report by @branfosj
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
bear-pg0212u15b.bear.cluster - Linux centos linux 8.2.2004, x86_64, Intel(R) Xeon(R) CPU E5-2640 v4 @ 2.40GHz (broadwell), Python 3.6.8
See https://gist.github.com/b0798c4fc6a1af851d43943d3183e0d3 for a full test report.

**Review by Micket — APPROVED** [review]
Yes this is absolutely the way we should do it I.M.O.
(i'll test build once i get around to fetching the sources)

**Comment by Micket** [comment]
Test report by @Micket
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
vera-c1 - Linux centos linux 7.8.2003, x86_64, Intel Xeon Processor (Skylake), Python 2.7.5
See https://gist.github.com/b52d771b2160b213487ec1e656a85d05 for a full test report.

**Comment by Micket** [comment]
Going in, thanks @branfosj!

**Pull request merged**
