### PR TITLE
{lib}[GCCcore/11.3.0] libmad v0.15.1b

### PR DESCRIPTION
**Pull request by anselmicz**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by anselmicz** [comment]
Test report by @anselmicz
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
debian-L14 - Linux Debian GNU/Linux 11, x86_64, AMD Ryzen 7 PRO 4750U with Radeon Graphics (zen2), Python 3.9.2
See https://gist.github.com/a222367b52a322aa0ecf9f9ec9130ef3 for a full test report.

**Comment by anselmicz** [comment]
Test report by @anselmicz
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
login2.karolina.it4i.cz - Linux CentOS Linux 7 (Core), x86_64, AMD EPYC 7452 32-Core Processor, Python 3.10.4
See https://gist.github.com/639376684b1170edba071b1846f0da7c for a full test report.

**Comment by boegel** [comment]
@boegelbot please test @ generoso

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
node3107.skitty.os - Linux RHEL 8.4, x86_64, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz (skylake_avx512), Python 3.6.8
See https://gist.github.com/ff633abec13cdf077e32a5d1e013b448 for a full test report.

**Review by boegel — APPROVED** [review]
lgtm

**Comment by boegel** [comment]
Going in, thanks @anselmicz!

**Pull request merged**
