### PR TITLE
{data}[foss/2020b] PYPOWER v5.1.15 w/ Python 3.8.6

### PR DESCRIPTION
**Pull request by Micket**
(created using `eb --new-pr`)
I tried to run pytest, but it doesn't seem like the test suite had been maintained for many years, and was very broken.

### CODE REVIEW

**Comment by Micket** [comment]
Test report by @Micket
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
alvis-c1 - Linux centos linux 7.9.2009, x86_64, Intel Xeon Processor (Skylake), Python 3.6.8
See https://gist.github.com/7874cf581ad2532edc108f5cbc495775 for a full test report.

**Comment by Micket** [comment]
@boegelbot please test @ generoso

**Comment by verdurin** [comment]
Test report by @verdurin
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
nuc.lan - Linux Fedora 33, x86_64, Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz, Python 3.9.5
See https://gist.github.com/0db6a20b3d400e23cc5e5fdc6316dd88 for a full test report.

**Review by verdurin — APPROVED** [review]
Looks fine.

**Pull request merged**
