### PR TITLE
{devel,vis}[fosscuda/2019b] PyTorch v1.6.0, torchvision v0.7.0 w/ Python 3.7.4, with MKL

### PR DESCRIPTION
**Pull request by terjekv**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by verdurin** [comment]
@terjekv any update on the style error?

**Comment by terjekv** [comment]
Sorry, I'm still trying to clear the tables at work. I'll see if I can find my way back to this soon(ish).

**Comment by terjekv** [comment]
Heh, I had just checked out the branch. Oh well. Thanks!

**Comment by boegel** [comment]
> Heh, I had just checked out the branch. Oh well. Thanks!

Was too easy to fix once `eb --check-style --from-pr 11785` made it clear what the issue was :)

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 3 out of 3 (3 easyconfigs in total)
node3306.joltik.os - Linux centos linux 7.9.2009, x86_64, Intel(R) Xeon(R) Gold 6242 CPU @ 2.80GHz (cascadelake), Python 3.6.8
See https://gist.github.com/0694d4bf7a8dbb0233fe6e1a238f0c63 for a full test report.

**Review by boegel — APPROVED** [review]
lgtm

**Comment by boegel** [comment]
Going in, thanks @terjekv!

**Pull request merged**
