### PR TITLE
{tools}[foss/2021a] jax v0.2.20 w/ Python 3.9.5

### PR DESCRIPTION
**Pull request by boegel**
(created using `eb --new-pr`)
WIP because doesn't work yet, see also https://github.com/google/jax/issues/7842

### CODE REVIEW

**Comment by boegel** [comment]
@boegelbot please test @ generoso

**Comment by SebastianAchilles** [comment]
Test report by @sebastianachilles
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
jsfc060 - Linux centos linux 7.9.2009, x86_64, AMD EPYC 7742 64-Core Processor, Python 3.6.8
See https://gist.github.com/bae3a2bfb95e1c06c698f94cae8971bb for a full test report.

**Comment by SebastianAchilles** [comment]
Test report by @sebastianachilles
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
rocky8-eb - Linux rocky linux 8.4, x86_64, Intel(R) Core(TM) i7-6900K CPU @ 3.20GHz (broadwell), Python 3.6.8
See https://gist.github.com/b85ee44acfb2503707ceb25192aab725 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 2 out of 2 (1 easyconfigs in total)
node2668.swalot.os - Linux centos linux 7.9.2009, x86_64, Intel(R) Xeon(R) CPU E5-2660 v3 @ 2.60GHz (haswell), Python 3.6.8
See https://gist.github.com/8d06c2263524457f4a2001afa37c9c89 for a full test report.

**Review by SebastianAchilles — APPROVED** [review]
lgtm

**Comment by SebastianAchilles** [comment]
Going in, thanks @boegel!

**Comment by Flamefire** [comment]
@boegel Can you add the patch from https://github.com/easybuilders/easybuild-easyconfigs/pull/14067 to this EC (either in a new PR or that PR)

**Comment by boegel** [comment]
> @boegel Can you add the patch from #14067 to this EC (either in a new PR or that PR)

@Flamefire done in #14070

**Pull request merged**
