### PR TITLE
{bio}[foss/2022a] GROMACS v2023.1 w/ Python 3.10.4

### PR DESCRIPTION
**Pull request by bedroge**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by bedroge** [comment]
Test report by @bedroge
**FAILED**
Build succeeded for 0 out of 1 (1 easyconfigs in total)
node1 - Linux Rocky Linux 8.7, x86_64, AMD EPYC 7763 64-Core Processor, Python 3.6.8
See https://gist.github.com/bedroge/38b7f14cdffa1f87da21fa9fe055b920 for a full test report.

**Comment by bedroge** [comment]
Test report by @bedroge
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
node1 - Linux Rocky Linux 8.7, x86_64, AMD EPYC 7763 64-Core Processor, Python 3.6.8
See https://gist.github.com/bedroge/edcedc7b7f0db0517c24e69666ef4d6b for a full test report.

**Comment by branfosj** [comment]
Test report by @branfosj
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
bear-pg0203u31a.bear.cluster - Linux RHEL 8.6, x86_64, Intel(R) Xeon(R) Platinum 8360Y CPU @ 2.40GHz (icelake), Python 3.6.8
See https://gist.github.com/branfosj/c8ab1205c0d0adbaa16ff97dea379174 for a full test report.

**Comment by bedroge** [comment]
> @bedroge Have you built this on a node with a GPU? The difference between my two builds is that one had a GPU available ([tests failed](https://github.com/easybuilders/easybuild-easyconfigs/pull/17906#issuecomment-1549217222)) and the other did not ([test passed](https://github.com/easybuilders/easybuild-easyconfigs/pull/17906#issuecomment-1549235430)).

I hadn't tested that yet, as I didn't have a GPU node available yesterday. I'll give it a try now.

**Comment by verdurin** [comment]
Test report by @verdurin
**FAILED**
Build succeeded for 0 out of 1 (1 easyconfigs in total)
easybuild-c7.novalocal - Linux CentOS Linux 7.9.2009, x86_64, Intel Xeon Processor (Skylake, IBRS), Python 3.6.8
See https://gist.github.com/verdurin/6cac9f7711e6a46bed4c87c4142876ce for a full test report.

**Comment by branfosj** [comment]
```
Fatal error:
When using GPUs, setting the number of OpenMP threads without specifying the
number of ranks can lead to conflicting demands. Please specify the number of
thread-MPI ranks as well (option -ntmpi).
```

It took me a while to find out how to get that!

Steps:
1. In GROMACS code `python_packaging/gmxapi/test/CMakeLists.txt` and `python_packaging/sample_restraint/tests/CMakeGROMACS.txt` change `--log-cli-level ERROR` to be `--log-cli-level DEBUG`
2. In easyblocks, `easybuild/easyblocks/g/gromacs.py` change `self.cfg.update('runtest', "-j %s" % self.cfg['parallel'])` to be `self.cfg.update('runtest', "-j 1")`
3. Build.

Step 1 changes to debug output - lots and lots of information. Step 2 changes the tests to run sequentially, so you can follow the test output.

**Comment by branfosj** [comment]
> If I change `env.setvar('OMP_NUM_THREADS', '1')` to be `env.unset_env_vars(['OMP_NUM_THREADS'])` in the GROMACS easyblock then all is fine for me here. That line comes from when the original GROMACS easyblock: [easybuilders/easybuild-easyblocks#335](https://github.com/easybuilders/easybuild-easyblocks/pull/335) (specifically [easybuilders/easybuild-easyblocks@24e2e74](https://github.com/easybuilders/easybuild-easyblocks/commit/24e2e749cc8adf10d865726b65730e873949e570)).

Though making that change more generally does cause build failures (i.e. `GROMACS-2021.3-foss-2021a.eb` failed).

This makes me think that https://github.com/easybuilders/easybuild-easyconfigs/pull/17906/files#diff-8a5d2e5c6303acbef223fcac4c8798202613f31ca998515e252463af5df379b8 is either not working or not complete.

**Comment by akesandgren** [comment]
Please checkout #18171 it should be complete and working with all tests passing (at least it does for me)

**Comment by branfosj** [comment]
closing and using #18171

**Comment by bedroge** [comment]
> @bedroge @branfosj Please checkout #18171 it should be complete and working with all tests passing (at least it does for me)

Thanks! Just tried your version and that worked fine for me as well.

**Pull request closed without merging**
