### PR TITLE
{bio}[GCCcore/10.3.0,foss/2021a] SyRI v1.4, longestrunsubsequence v1.0.1 w/ Python 3.9.5

### PR DESCRIPTION
**Pull request by jfgrimm**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by verdurin** [comment]
@boegelbot please test @ generoso

**Comment by verdurin** [comment]
Test report by @verdurin
**SUCCESS**
Build succeeded for 4 out of 4 (2 easyconfigs in total)
easybuild-c7.novalocal - Linux centos linux 7.9.2009, x86_64, Intel Xeon Processor (Skylake, IBRS), Python 3.6.8
See https://gist.github.com/16e3b2e5f4e7d05371f362a8f982643f for a full test report.

**Comment by verdurin** [comment]
Test report by @verdurin
**FAILED**
Build succeeded for 2 out of 5 (2 easyconfigs in total)
nuc.lan - Linux Fedora 33, x86_64, Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz, Python 3.9.6
See https://gist.github.com/9727dc02b230b3a63a108973b2edb892 for a full test report.

**Comment by jfgrimm** [comment]
@verdurin regarding the Clang failure - might want to double-check your easyblocks are up-to-date ([see #2540](https://github.com/easybuilders/easybuild-easyblocks/pull/2540) )

**Comment by verdurin** [comment]
Yes, building that now.

**Comment by Micket** [comment]
Test report by @Micket
**SUCCESS**
Build succeeded for 6 out of 6 (2 easyconfigs in total)
vera-c1 - Linux centos linux 7.9.2009, x86_64, Intel Xeon Processor (Skylake), Python 3.6.8
See https://gist.github.com/ee43b4bfdb658d72f1be198f79f5c2db for a full test report.

**Comment by verdurin** [comment]
Test report by @verdurin
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in total)
nuc.lan - Linux Fedora 33, x86_64, Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz, Python 3.9.6
See https://gist.github.com/a26db5d2bc393051eaefd6dd88e5b333 for a full test report.

**Review by verdurin — APPROVED** [review]
Looks fine.

**Comment by verdurin** [comment]
Going in, thanks @jfgrimm!

**Pull request merged**
