### PR TITLE
{lib}[foss/2020b] TensorFlow v2.4.1 w/ Python 3.8.6

### PR DESCRIPTION
**Pull request by branfosj**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by boegel** [comment]
@boegelbot please test @ generoso

**Comment by branfosj** [comment]
Test report by @branfosj
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
bear-pg0211u12a.bear.cluster - Linux centos linux 7.8.2003, x86_64, Intel(R) Xeon(R) Gold 6248 CPU @ 2.50GHz (cascadelake), Python 3.6.8
See https://gist.github.com/bb5607eab0132ea4d9282b280eb1f201 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
node3551.doduo.os - Linux RHEL 8.2, x86_64, AMD EPYC 7552 48-Core Processor (zen2), Python 3.6.8
See https://gist.github.com/d828e52ce6f357a385e9883b54330dc0 for a full test report.

**Comment by verdurin** [comment]
Test report by @verdurin
**FAILED**
Build succeeded for 7 out of 9 (1 easyconfigs in total)
nuc.lan - Linux Fedora 32, x86_64, Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz, Python 3.8.7
See https://gist.github.com/995d2aa946315ed438aa6a062a902710 for a full test report.

**Comment by verdurin** [comment]
Test report by @verdurin
**FAILED**
Build succeeded for 20 out of 22 (1 easyconfigs in total)
easybuild-c7.novalocal - Linux centos linux 7.9.2009, x86_64, Intel Xeon Processor (Skylake, IBRS), Python 3.6.8
See https://gist.github.com/4310dd2c28f4227a839968ceac914ebd for a full test report.

**Comment by verdurin** [comment]
Both failures are similar:
```
Build successful! Binary is here: /mnt/ds918plus/eb/nuc-fedora32/build/Bazel/3.7.2/GCCcore-10.2.0/output/bazel

== 2021-02-22 12:30:28,949 run.py:574 DEBUG Using default regular expression: (?<![(,-]|\w)(?:error|segmentation fault|failed)(?![(,-]|\.?\w)
== 2021-02-22 12:30:28,967 easyblock.py:3049 DEBUG Not skipping test step (skippable: True, skip: None, skipsteps: [], module_only: False, force: False
== 2021-02-22 12:30:28,967 build_log.py:265 INFO testing...
== 2021-02-22 12:30:28,967 easyblock.py:3058 INFO Starting test step
== 2021-02-22 12:30:28,967 easyconfig.py:1610 INFO Generating template values...
== 2021-02-22 12:30:28,967 templates.py:165 DEBUG config: <easybuild.framework.easyconfig.easyconfig.EasyConfig object at 0x7f25cdf97670>
== 2021-02-22 12:30:28,967 templates.py:192 DEBUG version found in easyconfig is 3.7.2
== 2021-02-22 12:30:28,967 systemtools.py:916 DEBUG Version is already a string ('11'), OK
== 2021-02-22 12:30:28,968 systemtools.py:916 DEBUG Version is already a string ('3.8.6'), OK
== 2021-02-22 12:30:28,968 templates.py:281 DEBUG name: bitbucket_account, config: %(namelower)s
== 2021-02-22 12:30:28,968 templates.py:281 DEBUG name: github_account, config: %(namelower)s
== 2021-02-22 12:30:28,968 templates.py:281 DEBUG name: name, config: Bazel
== 2021-02-22 12:30:28,968 templates.py:281 DEBUG name: parallel, config: 8
== 2021-02-22 12:30:28,968 templates.py:281 DEBUG name: version, config: 3.7.2
== 2021-02-22 12:30:28,968 templates.py:281 DEBUG name: versionsuffix, config:
== 2021-02-22 12:30:28,968 templates.py:281 DEBUG name: versionprefix, config:
== 2021-02-22 12:30:28,968 easyconfig.py:1629 INFO Template values: arch='x86_64', bitbucket_account='bazel', builddir='/mnt/ds918plus/eb/nuc-fedora32/build/Bazel/3.7.2/GCCcore-10.2.0', github_account='bazel', installdir='/mnt/ds918plus/eb/nuc-fedora32/software/Bazel/3.7.2-GCCcore-10.2.0', javamajver='11', javashortver='11', javaver='11', module_name='Bazel/3.7.2-GCCcore-10.2.0', name='Bazel', nameletter='B', nameletterlower='b', namelower='bazel', parallel='8', pymajver='3', pyminver='8', pyshortver='3.8', pyver='3.8.6', toolchain_name='GCCcore', toolchain_version='10.2.0', version='3.7.2', version_major='3', version_major_minor='3.7', version_minor='7', versionprefix='', versionsuffix=''
== 2021-02-22 12:30:28,968 easyblock.py:3064 INFO Running method test_step part of step test
== 2021-02-22 12:30:28,968 easyblock.py:2145 DEBUG Trying to execute True as a command for running unit tests...
== 2021-02-22 12:30:28,974 build_log.py:169 ERROR EasyBuild crashed with an error (at easybuild/base/exceptions.py:124 in __init__): Unknown command type ('<class 'bool'>'): True (at easybuild/tools/run.py:152 in run_cmd)
== 2021-02-22 12:30:28,975 config.py:581 DEBUG software install path as specified by 'installpath' and 'subdir_software': /mnt/ds918plus/eb/nuc-fedora32/software
== 2021-02-22 12:30:28,975 filetools.py:1684 INFO Removing lock /mnt/ds918plus/eb/nuc-fedora32/software/.locks/_mnt_ds918plus_eb_nuc-fedora32_software_Bazel_3.7.2-GCCcore-10.2.0.lock...
== 2021-02-22 12:30:28,977 filetools.py:330 INFO Path /mnt/ds918plus/eb/nuc-fedora32/software/.locks/_mnt_ds918plus_eb_nuc-fedora32_software_Bazel_3.7.2-GCCcore-10.2.0.lock successfully removed.
== 2021-02-22 12:30:28,977 filetools.py:1688 INFO Lock removed: /mnt/ds918plus/eb/nuc-fedora32/software/.locks/_mnt_ds918plus_eb_nuc-fedora32_software_Bazel_3.7.2-GCCcore-10.2.0.lock
== 2021-02-22 12:30:28,977 easyblock.py:3340 WARNING build failed (first 300 chars): Unknown command type ('<class 'bool'>'): True
== 2021-02-22 12:30:28,977 easyblock.py:295 INFO Closing log for application name Bazel version 3.7.2
```

**Comment by branfosj** [comment]
```
== 2021-02-22 12:30:28,968 easyblock.py:2145 DEBUG Trying to execute True as a command for running unit tests...
== 2021-02-22 12:30:28,974 build_log.py:169 ERROR EasyBuild crashed with an error (at easybuild/base/exceptions.py:124 in __init__): Unknown command type ('<class 'bool'>'): True (at easybuild/tools/run.py:152 in run_cmd)
```

@verdurin Can you try with the updated Bazel easyblock from https://github.com/easybuilders/easybuild-easyblocks/pull/2285

See also #12212

**Comment by branfosj** [comment]
Test report by @branfosj
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
bear-pg0211u38b.bear.cluster - Linux centos linux 8.2.2004, x86_64, Intel(R) Xeon(R) Gold 6248 CPU @ 2.50GHz (cascadelake), Python 3.6.8
See https://gist.github.com/41d42ece03b65cbd93b324277f923f35 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
node3100.skitty.os - Linux centos linux 7.9.2009, x86_64, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz, Python 3.6.8
See https://gist.github.com/9bc0c4963d8a9341ac6e44ff409c48d2 for a full test report.

**Comment by verdurin** [comment]
Test report by @verdurin
Using easyblocks from PR(s) https://github.com/easybuilders/easybuild-easyblocks/pull/2285
**SUCCESS**
Build succeeded for 2 out of 2 (1 easyconfigs in total)
easybuild-c7.novalocal - Linux centos linux 7.9.2009, x86_64, Intel Xeon Processor (Skylake, IBRS), Python 3.6.8
See https://gist.github.com/bbbcd3180da3de5681d716b98d6172d3 for a full test report.

**Comment by verdurin** [comment]
Test report by @verdurin
Using easyblocks from PR(s) https://github.com/easybuilders/easybuild-easyblocks/pull/2285
**SUCCESS**
Build succeeded for 2 out of 2 (1 easyconfigs in total)
nuc.lan - Linux Fedora 32, x86_64, Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz, Python 3.8.7
See https://gist.github.com/a3c35048ae6d7bcc653b36ab1b88696d for a full test report.

**Review by boegel — APPROVED** [review]
lgtm

**Comment by boegel** [comment]
Going in, thanks @branfosj!

**Comment by branfosj** [comment]
Test report by @branfosj
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
bear-pg0305u05a.bear.cluster - Linux RHEL 8.2, POWER, 8335-GTX (power9le), Python 3.6.8
See https://gist.github.com/14052b05c349a5873b6796460005ce4b for a full test report.

**Pull request merged**
