### PR TITLE
{math}[foss/2022b] Platypus-Opt v1.2.0

### PR DESCRIPTION
**Pull request by branfosj**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by branfosj** [comment]
Test report by @branfosj
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
bear-pg0105u03a - Linux RHEL 8.6, x86_64, Intel(R) Xeon(R) Platinum 8360Y CPU @ 2.40GHz (icelake), Python 3.6.8
See https://gist.github.com/branfosj/8d3f25d991a6f40e36cada9be4bf9469 for a full test report.

**Comment by migueldiascosta** [comment]
@boegelbot please test @ generoso

**Comment by migueldiascosta** [comment]
@boegelbot please test @ jsc-zen3

**Comment by migueldiascosta** [comment]
Test report by @migueldiascosta
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
gracehopper - Linux Rocky Linux 9.3, AArch64, ARM UNKNOWN (neoverse_v2), 1 x NVIDIA NVIDIA GH200 480GB, 550.54.15, Python 3.9.18
See https://gist.github.com/migueldiascosta/56db70052ea0e2003dbaa1d22ba0e24d for a full test report.

**Comment by migueldiascosta** [comment]
@branfosj I was going to ask if this couldn't be moved down to `gfbf`, noticed that it does support MPI (https://github.com/search?q=repo%3AProject-Platypus%2FPlatypus%20mpi4py&type=code), but in that case shouldn't `mpi4py` be added to the `dependencies`? It's not in `SciPy-bundle` anymore, since that was moved down to `gfbf`

**Comment by branfosj** [comment]
> @branfosj I was going to ask if this couldn't be moved down to `gfbf`, noticed that it does support MPI (https://github.com/search?q=repo%3AProject-Platypus%2FPlatypus%20mpi4py&type=code), but in that case shouldn't `mpi4py` be added to the `dependencies`? It's not in `SciPy-bundle` anymore, since that was moved down to `gfbf`

Thanks. I'd missed that. I've added `mpi4py` as a dependency.

**Review by migueldiascosta — APPROVED** [review]
lgtm

**Comment by migueldiascosta** [comment]
rebuilding on generoso and jsc-zen3 more to keep the modules there up to date

**Comment by migueldiascosta** [comment]
@boegelbot please test @ generoso

**Comment by branfosj** [comment]
Test report by @branfosj
**SUCCESS**
Build succeeded for 2 out of 2 (1 easyconfigs in total)
bear-pg0105u03a - Linux RHEL 8.6, x86_64, Intel(R) Xeon(R) Platinum 8360Y CPU @ 2.40GHz (icelake), Python 3.6.8
See https://gist.github.com/branfosj/29da6d3d2efcd75320dc7a505bc23e31 for a full test report.

**Comment by migueldiascosta** [comment]
@boegelbot please test @ jsc-zen3

**Comment by migueldiascosta** [comment]
Test report by @migueldiascosta
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
gracehopper - Linux Rocky Linux 9.3, AArch64, ARM UNKNOWN (neoverse_v2), 1 x NVIDIA NVIDIA GH200 480GB, 550.54.15, Python 3.9.18
See https://gist.github.com/migueldiascosta/396b8b645fc768b42ec03d1d7cf896e2 for a full test report.

**Comment by migueldiascosta** [comment]
Going in, thanks @branfosj!

**Pull request merged**
