### PR TITLE
{ai}[foss/2022a] PyTorch v2.1.2

### PR DESCRIPTION
**Pull request by Flamefire**
(created using `eb --new-pr`)

Update over https://github.com/easybuilders/easybuild-easyconfigs/pull/19086

`test_sympy_utils` failure requires rebuilding with https://github.com/easybuilders/easybuild-easyconfigs/pull/19414

### CODE REVIEW

**Comment by Flamefire** [comment]
Test report by @Flamefire
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
i8023 - Linux Rocky Linux 8.7, x86_64, AMD EPYC 7352 24-Core Processor (zen2), Python 3.6.8
See https://gist.github.com/Flamefire/cb55407b7d0cefa033c8cf016488af43 for a full test report.

**Comment by Flamefire** [comment]
Test report by @Flamefire
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
n1099 - Linux RHEL 8.7 (Ootpa), x86_64, Intel(R) Xeon(R) Platinum 8470 (icelake), Python 3.8.13
See https://gist.github.com/Flamefire/e49db6dd7c419a682fba7ba11cf1245b for a full test report.

**Comment by casparvl** [comment]
Test report by @casparvl
**FAILED**
Build succeeded for 4 out of 5 (1 easyconfigs in total)
gcn6.local.snellius.surf.nl - Linux RHEL 8.6, x86_64, Intel(R) Xeon(R) Platinum 8360Y CPU @ 2.40GHz, 4 x NVIDIA NVIDIA A100-SXM4-40GB, 535.104.12, Python 3.6.8
See https://gist.github.com/casparvl/ca999bc0ff3db36bdf4cba2a8016595b for a full test report.

**Comment by Flamefire** [comment]
@casparvl I assume the failures are the same as in https://github.com/easybuilders/easybuild-easyconfigs/pull/19445#issuecomment-1864912428 ?

Except for test_sympy_utils which requires rebuilding #19414

Do you see the same failures in #19086 / #19087 or are those test_jit failures new in 2.1.2?

**Comment by Flamefire** [comment]
Marking this as ready as it doesn't seem to fail more than 2.1.0 so this might be better than #19086

**Comment by SebastianAchilles** [comment]
@boegelbot please test @ generoso
CORE_CNT=16

**Comment by casparvl** [comment]
> @casparvl I assume the failures are the same as in [#19445 (comment)](https://github.com/easybuilders/easybuild-easyconfigs/pull/19445#issuecomment-1864912428) ?
> 
> Except for test_sympy_utils which requires rebuilding #19414
> 
> Do you see the same failures in #19086 / #19087 or are those test_jit failures new in 2.1.2?

Yeah, sorry, little time to follow up from my side. Test failures where indeed the same, except the `test_sympy_utils`. I missed your instruction in the opening post to rebuild #19414, sorry.

I'll try to upload a test report for #19086 and #19087. I'll be going on holiday after today, so I'll just turn on those builds, and hope for the best... I'm afraid I can't look into the build failures and report more specifically then, but at least you should be able to see the summary of failures in the gist.

**Comment by SebastianAchilles** [comment]
Test report by @sebastianachilles
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
zen2-rockylinux-89 - Linux Rocky Linux 8.9, x86_64, AMD EPYC 7452 32-Core Processor (zen2), Python 3.6.8
See https://gist.github.com/SebastianAchilles/64bdb54f7560e7806c2265a47ca4bc26 for a full test report.

**Comment by SebastianAchilles** [comment]
@boegelbot please test @ jsc-zen2
CORE_CNT=16

**Comment by bedroge** [comment]
Test report by @bedroge
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
v100gpu26 - Linux Rocky Linux 8.9, x86_64, Intel(R) Xeon(R) Gold 6150 CPU @ 2.70GHz (skylake_avx512), 1 x NVIDIA GRID V100D-32Q, 535.104.05, Python 3.6.8
See https://gist.github.com/bedroge/31fa6679fdcae36dc5eddca8c5aa8112 for a full test report.

**Comment by SebastianAchilles** [comment]
Test report by @sebastianachilles
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
jscclxc1.int.jsc-clx.fz-juelich.de - Linux Rocky Linux 9.3, x86_64, Intel Xeon Processor (Cascadelake) (cascadelake), Python 3.9.18
See https://gist.github.com/SebastianAchilles/33cab1423a36db1925ca9e797fe07aa1 for a full test report.

**Comment by SebastianAchilles** [comment]
Test report by @sebastianachilles
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
jsczen3c1.int.jsc-zen3.fz-juelich.de - Linux Rocky Linux 9.3, x86_64, AMD EPYC-Milan Processor (zen3), Python 3.9.18
See https://gist.github.com/SebastianAchilles/4b0be8e363477f529813d6346299150f for a full test report.

**Review by SebastianAchilles — APPROVED** [review]
lgtm

**Comment by SebastianAchilles** [comment]
Going in, thanks @Flamefire!

**Comment by robogast** [comment]
legend 🎉

**Pull request merged**
