### PR TITLE
{math}[gfbf/2024a] Shapely v2.0.6

### PR DESCRIPTION
**Pull request by maxim-masterov**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by SebastianAchilles** [comment]
GEOS v3.12.2 for 13.3.0 was merge in this PR: https://github.com/easybuilders/easybuild-easyconfigs/pull/21282

**Comment by maxim-masterov** [comment]
@SebastianAchilles I removed the GEOS easyconfig from this PR and updated the corresponding version in Shapely

**Comment by SebastianAchilles** [comment]
@boegelbot please test @ jsc-zen3

**Comment by SebastianAchilles** [comment]
@boegelbot please test @ generoso

**Review by SebastianAchilles — APPROVED** [review]
lgtm

**Comment by SebastianAchilles** [comment]
Going in, thanks @maxim-masterov!

**Pull request merged**
