### PR TITLE
{chem}[foss/2020a,foss/2020b,foss/2021a,foss/2021b] TAMkin v1.2.6 w/ Python 3.8.2

### PR DESCRIPTION
**Pull request by Flamefire**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by ocaisa** [comment]
@boegelbot please test @ generoso

**Comment by verdurin** [comment]
Test report by @verdurin
**SUCCESS**
Build succeeded for 7 out of 7 (4 easyconfigs in total)
easybuild-c7.novalocal - Linux CentOS Linux 7.9.2009, x86_64, Intel Xeon Processor (Skylake, IBRS), Python 3.6.8
See https://gist.github.com/verdurin/c1d90fc0b4593f26c77ed4bad19cc208 for a full test report.

**Comment by verdurin** [comment]
@boegelbot please test @ jsc-zen3

**Comment by Flamefire** [comment]
It fails to build CMake and Python?

**Comment by Flamefire** [comment]
Test report by @Flamefire
**FAILED**
Build succeeded for 72 out of 85 (4 easyconfigs in total)
n1234 - Linux RHEL 8.7 (Ootpa), x86_64, Intel(R) Xeon(R) Platinum 8470 (icelake), Python 3.8.13
See https://gist.github.com/Flamefire/b19e5ed1344c2d9a7b2cdafd88d097a8 for a full test report.

**Comment by Flamefire** [comment]
Test report by @Flamefire
**SUCCESS**
Build succeeded for 6 out of 6 (4 easyconfigs in total)
n1170 - Linux RHEL 8.7 (Ootpa), x86_64, Intel(R) Xeon(R) Platinum 8470 (icelake), Python 3.8.13
See https://gist.github.com/Flamefire/a6d01fc248455601ac4ec1493c596b9b for a full test report.

**Comment by ocaisa** [comment]
@boegelbot please test @ generoso

**Comment by ocaisa** [comment]
@boegelbot please test @ jsc-zen3
EB_ARGS="TAMkin-1.2.6-foss-2021a.eb TAMkin-1.2.6-foss-2021b.eb"

**Comment by Flamefire** [comment]
> Test report by @boegelbot **FAILED** Build succeeded for 0 out of 4 (4 easyconfigs in total) cns1 - Linux Rocky Linux 8.9, x86_64, Intel(R) Xeon(R) CPU E5-2667 v3 @ 3.20GHz (haswell), Python 3.6.8 See https://gist.github.com/boegelbot/9c51d114d0150f96ea245b30f517d763 for a full test report.

This is https://github.com/molmod/tamkin/issues/43

**Comment by Flamefire** [comment]
Test report by @Flamefire
**SUCCESS**
Build succeeded for 8 out of 8 (4 easyconfigs in total)
i8014 - Linux Rocky Linux 8.7, x86_64, AMD EPYC 7352 24-Core Processor (zen2), 8 x NVIDIA NVIDIA A100-SXM4-40GB, 545.23.08, Python 3.6.8
See https://gist.github.com/Flamefire/e908d8a766112f4d6e243379bdd45674 for a full test report.

**Comment by Flamefire** [comment]
Test report by @Flamefire
**SUCCESS**
Build succeeded for 4 out of 4 (4 easyconfigs in total)
n1358 - Linux RHEL 8.7 (Ootpa), x86_64, Intel(R) Xeon(R) Platinum 8470 (icelake), Python 3.8.13
See https://gist.github.com/Flamefire/849f4970003291e2e9c3aeebc6d5a46c for a full test report.

**Comment by Flamefire** [comment]
@ocaisa This should now pass can can be merged.

**Comment by ocaisa** [comment]
@boegelbot please test @ jsc-zen3
EB_ARGS="TAMkin-1.2.6-foss-2021a.eb TAMkin-1.2.6-foss-2021b.eb"

**Review by ocaisa — APPROVED** [review]

**Comment by ocaisa** [comment]
Going in, thanks @Flamefire

**Pull request merged**
