### PR TITLE
{lang}[system/system] Julia v1.9.3 w/ linux x86_64

### PR DESCRIPTION
**Pull request by laraPPr**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by laraPPr** [comment]
Test report by @laraPPr
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
node3627.doduo.os - Linux RHEL 8.6 (Ootpa), x86_64, AMD EPYC 7552 48-Core Processor (zen2), Python 3.10.8
See https://gist.github.com/laraPPr/956126211f80c7f5a7455972ea0d4bda for a full test report.

**Comment by laraPPr** [comment]
@boegelbot please test @ jsc-zen2

**Review by smoors — APPROVED** [review]
lgtm

**Comment by smoors** [comment]
Going in, thanks @laraPPr!

**Pull request merged**
