### PR TITLE
{tools}[GCCcore/11.3.0] memtester v4.5.1

### PR DESCRIPTION
**Pull request by Micket**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by Micket** [comment]
I don't know what to do with this one. urllib seems to be having issues verifying the certificate due to the trailing dot in the domain name. 
Every url combination i try, https or http , just redirects to this and it fails with the same
```
ERROR: Unexpected error occurred when trying to download https://pyropus.ca/./software/memtester/old-versions/memtester-4.5.1.tar.gz to
 /apps/sources/m/memtester/memtester-4.5.1.tar.gz: hostname 'pyropus.ca.' doesn't match either of 'detritus.pyropus.ca', 'pyropus.ca',
 'www.pyropus.ca'
 ```
 
 The error actually stems from 
 ``
 ssl.CertificateError: hostname 'pyropus.ca.' doesn't match either of 'detritus.pyropus.ca', 'pyropus.ca', 'www.pyropus.ca'
 ```
 but EB catches all leftover exceptions and hides the real exception type with just "ERROR"
 
  Browsers don't seem to have a problem with the extra dot.

**Comment by Micket** [comment]
Test report by @Micket
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
alvis-c1 - Linux Rocky Linux 8.5, x86_64, Intel Xeon Processor (Skylake), Python 3.6.8
See https://gist.github.com/3db4967c1222add58198646fb6f2d041 for a full test report.

**Comment by branfosj** [comment]
Test report by @branfosj
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
bear-pg0105u36b.bear.cluster - Linux RHEL 8.5, x86_64, Intel(R) Xeon(R) Platinum 8360Y CPU @ 2.40GHz (icelake), Python 3.6.8
See https://gist.github.com/95a69da4ccfacd8ad97679c2ca6e936b for a full test report.

**Comment by branfosj** [comment]
Test report by @branfosj
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
bear-pg0211u03a.bear.cluster - Linux Ubuntu 20.04.2 LTS (Focal Fossa), x86_64, Intel(R) Xeon(R) Gold 6248 CPU @ 2.50GHz (cascadelake), Python 3.8.5
See https://gist.github.com/a571565eb9d1059a6a3959de458122ae for a full test report.

**Review by branfosj — APPROVED** [review]

**Comment by branfosj** [comment]
Going in, thanks @Micket!

**Pull request merged**
