### PR TITLE
{chem}[system/system] PlotMS v6.0.1

### PR DESCRIPTION
**Pull request by SebastianAchilles**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by SebastianAchilles** [comment]
Test report by @sebastianachilles
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
jsfc01.int.jusuf.sebastian.cluster - Linux rocky linux 8.4, x86_64, AMD EPYC 7742 64-Core Processor (zen2), 1 x NVIDIA GRID V100-4C, 460.73.01, Python 3.6.8
See https://gist.github.com/3ed1c28bc2fc33e67c6d4db7258ae5ad for a full test report.

**Comment by SebastianAchilles** [comment]
@boegelbot please test @ generoso

**Comment by bedroge** [comment]
@SebastianAchilles wouldn't it be possible to use the source tarball from https://github.com/qcxms/PlotMS/releases/tag/v.6.0.1, and build it using the `MesonNinja` easyblock?

**Comment by SebastianAchilles** [comment]
Closing, since I didn't found time to improve the PR.

**Pull request closed without merging**
