### PR TITLE
exclude `cdp*` CUDA samples that fail to build on aarch64 in CUDA-Samples v12.1

### PR DESCRIPTION
**Pull request by boegel**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by boegel** [comment]
@boegelbot please test @ generoso

**Comment by boegel** [comment]
Test report by @boegel
**FAILED**
Build succeeded for 0 out of 1 (1 easyconfigs in total)
aarch64-neoverse-n1-node1.int.aws-rocky88-202310.eessi.io - Linux Rocky Linux 8.8, AArch64, ARM UNKNOWN (neoverse_n1), Python 3.6.8
See https://gist.github.com/boegel/df7c69255741bf12789dad35d68b3925 for a full test report.

**Comment by ocaisa** [comment]
Well, that's positive, it actually built but the location from which to install the binaries is wrong

**Comment by boegel** [comment]
> Well, that's positive, it actually built but the location from which to install the binaries is wrong

should be fixed in f81bca0

**Comment by boegel** [comment]
@boegelbot please test @ jsc-zen2

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
aarch64-neoverse-n1-node1.int.aws-rocky88-202310.eessi.io - Linux Rocky Linux 8.8, AArch64, ARM UNKNOWN (neoverse_n1), Python 3.6.8
See https://gist.github.com/boegel/bec88d9528c9e2c1b5885de22471bf05 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
node3109.skitty.os - Linux RHEL 8.8, x86_64, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz (skylake_avx512), Python 3.6.8
See https://gist.github.com/boegel/146386da514e38f8df94cf08e71be67b for a full test report.

**Review by casparvl — APPROVED** [review]
Lgtm! Running a build test on our cluster too, but I don't think we really need to wait for that - plenty of successful results already.

**Comment by casparvl** [comment]
Test report by @casparvl
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
tcn1.local.snellius.surf.nl - Linux RHEL 8.6, x86_64, AMD EPYC 7H12 64-Core Processor, Python 3.6.8
See https://gist.github.com/casparvl/45dcb3771df50015b2756c5c41208a56 for a full test report.

**Comment by casparvl** [comment]
Going in, thanks @boegel!

**Pull request merged**
