### PR TITLE
{lang}[system/system] Julia v1.10.4 w/ linux x86_64

### PR DESCRIPTION
**Pull request by pavelToman**
(created using `eb --new-pr`)
resolves https://github.com/vscentrum/vsc-software-stack/issues/378

### CODE REVIEW

**Comment by pavelToman** [comment]
@boegelbot please test @ generoso

**Comment by boegel** [comment]
@pavelToman Tiny style issue to fix:
```
Julia-1.10.4-linux-x86_64.eb:37:1: W391 blank line at end of file
```

**Comment by pavelToman** [comment]
@boegelbot please test @ jsc-zen3

**Review by smoors — APPROVED** [review]
lgtm

**Comment by smoors** [comment]
Going in, thanks @pavelToman!

**Pull request merged**
