### PR TITLE
remove incorrect '-Dgallium-drivers=swrast' configure option in ROOT easyconfigs

### PR DESCRIPTION
**Pull request by boegel**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by boegel** [comment]
@boegelbot please test @ generoso
CORE_CNT=16

**Comment by boegel** [comment]
Test report by @boegel
**FAILED**
Build succeeded for 0 out of 3 (3 easyconfigs in total)
node3108.skitty.os - Linux RHEL 8.6, x86_64, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz (skylake_avx512), Python 3.6.8
See https://gist.github.com/boegel/329235e1f556b3df9c715aa3c67e4eb0 for a full test report.

**Comment by boegel** [comment]
test build on `generoso` worked, but test report didn't make it back into the PR due to https://github.com/easybuilders/easybuild-framework/issues/3934

**Comment by boegel** [comment]
@boegelbot please test @ jsc-zen2
CORE_CNT=16

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 3 out of 3 (3 easyconfigs in total)
node3108.skitty.os - Linux RHEL 8.6, x86_64, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz (skylake_avx512), Python 3.6.8
See https://gist.github.com/boegel/7fe8d3da73fb9dacee46d1e113c8511a for a full test report.

**Review by Micket — APPROVED** [review]
lgtm

**Pull request merged**
