### PR TITLE
{vis}[GCCcore/11.2.0] jbigkit v2.1 + add missing header file to older versions

### PR DESCRIPTION
**Pull request by SebastianAchilles**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by SebastianAchilles** [comment]
Test report by @sebastianachilles
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
rocky8-eb - Linux rocky linux 8.4, x86_64, Intel(R) Core(TM) i7-6900K CPU @ 3.20GHz (broadwell), Python 3.6.8
See https://gist.github.com/f718084c440339d479e69a0a29a67ce0 for a full test report.

**Comment by SebastianAchilles** [comment]
@boegelbot: please test @ generoso

**Comment by smoors** [comment]
@SebastianAchilles there is an issue with all jbigkit-2.1installations, discovered while testing libtiff PR #14079.
LibTIFF does not pick up jbigkit because of a missing header file 'libjbig/jbig_ar.h', that is not copied to the installdir.
Can you fix this for all versions from GCCcore-8.3.0 ?

**Comment by smoors** [comment]
@boegelbot: please test @ generoso

**Review by smoors — APPROVED** [review]
lgtm

**Comment by smoors** [comment]
Going in, thanks @SebastianAchilles!

**Pull request merged**
