### PR TITLE
{bio}[GCC/6.4.0-2.28] SAMtools v1.9 + HTSlib v1.9

### PR DESCRIPTION
**Pull request by jdemeul**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by vanzod** [comment]
@jdemeul I think both easyconfig files could be lowered to the `GCC-6.4.0-2.28` toolchain

**Comment by jdemeul** [comment]
@vanzod excellent, they can indeed, just updated the PR

**Comment by jdemeul** [comment]
Actually, probably easier for you if I make a separate PR for the easyconfigs with `GCC-6.4.0-2.28`toolchain?

**Comment by akesandgren** [comment]
See also https://github.com/easybuilders/easybuild-easyconfigs/pull/6652

**Comment by boegel** [comment]
@vanzod For end-user stuff that is performance critical we usually go with top-level toolchains, no?

**Comment by boegel** [comment]
@vanzod No, and you're right, as long as we're using `GCC` not `GCCcore` (the latter would imply that the `GCCcore` easyconfig can be used to resolve dependencies when building with an `intel` compiler, which was actually my concern).

@jdemeul To go forward, let's remove the easyconfigs using `foss/2018a`? This should do the trick:

```
$ eb --update-pr 6664 :easybuild/easyconfigs/h/HTSlib/HTSlib-1.9-foss-2018a.eb : easybuild/easyconfigs/s/SAMtools/SAMtools-1.9-foss-2018a.eb
```

**Comment by jdemeul** [comment]
Done, thanks for the input @vanzod @boegel !

**Comment by vanzod** [comment]
Test report by @vanzod
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in this PR)
cermis - Linux debian 9.4, Intel(R) Xeon(R) CPU           E5620  @ 2.40GHz, Python 2.7.13
See https://gist.github.com/35edd67ff8b32d2701d5356f39b942b0 for a full test report.

**Comment by vanzod** [comment]
Going in, thanks @jdemeul!

**Pull request merged**
