### PR TITLE
{bio}[foss/2020b] BEDOPS v2.4.40

### PR DESCRIPTION
**Pull request by levlafayette**
New version, new toolchain

### CODE REVIEW

**Comment by verdurin** [comment]
@boegelbot please test @ generoso

**Comment by verdurin** [comment]
Test report by @verdurin
**FAILED**
Build succeeded for 0 out of 1 (1 easyconfigs in total)
nuc.lan - Linux Fedora 33, x86_64, Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz, Python 3.9.5
See https://gist.github.com/5a64ed872741a410749425bc7ef5d64d for a full test report.

**Comment by verdurin** [comment]
Test report by @verdurin
**FAILED**
Build succeeded for 0 out of 1 (1 easyconfigs in total)
easybuild-c7.novalocal - Linux centos linux 7.9.2009, x86_64, Intel Xeon Processor (Skylake, IBRS), Python 3.6.8
See https://gist.github.com/dabf0f075868d78732f3f6387e3d405b for a full test report.

**Comment by verdurin** [comment]
Lots of linking errors:
```
mkdir -p ../bin && g++ -o ../bin/bedextract-typical -O2 -ftree-vectorize -march=native -fno-math-errno -fPIC -static  -s -Wall -pedantic -O3 -std=c++11 objects_typical/NaN.o objects_typical/starchConstants.o objects_typical/starchFileHelpers.o objects_typical/starchH
elpers.o objects_typical/starchMetadataHelpers.o objects_typical/unstarchHelpers.o objects_typical/starchSha1Digest.o objects_typical/starchBase64Coding.o -L/dev/shm/BEDOPS/2.4.40/foss-2020b/bedops-2.4.40/applications/bed/bedextract/src/../../../../third-party/jansso
n/lib -L/dev/shm/BEDOPS/2.4.40/foss-2020b/bedops-2.4.40/applications/bed/bedextract/src/../../../../third-party/bzip2 -L/dev/shm/BEDOPS/2.4.40/foss-2020b/bedops-2.4.40/applications/bed/bedextract/src/../../../../third-party/zlib -iquote../../../../interfaces/general-
headers -I/dev/shm/BEDOPS/2.4.40/foss-2020b/bedops-2.4.40/applications/bed/bedextract/src/../../../../third-party/jansson/include -I/dev/shm/BEDOPS/2.4.40/foss-2020b/bedops-2.4.40/applications/bed/bedextract/src/../../../../third-party/bzip2 -I/dev/shm/BEDOPS/2.4.40/
foss-2020b/bedops-2.4.40/applications/bed/bedextract/src/../../../../third-party/zlib /dev/shm/BEDOPS/2.4.40/foss-2020b/bedops-2.4.40/applications/bed/bedextract/src/../../../../third-party/jansson/lib/libjansson.a /dev/shm/BEDOPS/2.4.40/foss-2020b/bedops-2.4.40/appl
ications/bed/bedextract/src/../../../../third-party/bzip2/libbz2.a /dev/shm/BEDOPS/2.4.40/foss-2020b/bedops-2.4.40/applications/bed/bedextract/src/../../../../third-party/zlib/libz.a ExtractRows.cpp
../../../../interfaces/src/data/starch/starchMetadataHelpers.c: In function int starch::STARCH_updateMetadataForChromosome(starch::Metadata**, char*, char*, uint64_t, Bed::LineCountType, Bed::BaseCountType, Bed::BaseCountType, starch::Boolean, starch::Boolean, char*,
 Bed::LineLengthType):
../../../../interfaces/src/data/starch/starchMetadataHelpers.c:311:20: warning: char* strncpy(char*, const char*, size_t) specified bound depends on the length of the source argument [-Wstringop-overflow=]
  311 |             strncpy(iter->filename, fn, strlen(fn) + 1);
      |             ~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../../../../interfaces/src/data/starch/starchMetadataHelpers.c:311:47: note: length computed here
  311 |             strncpy(iter->filename, fn, strlen(fn) + 1);
      |                                         ~~~~~~^~~~
../../../../interfaces/src/data/starch/starchMetadataHelpers.c:330:24: warning: char* strncpy(char*, const char*, size_t) specified bound depends on the length of the source argument [-Wstringop-overflow=]
  330 |                 strncpy(iter->signature, signature, strlen(signature) + 1);
      |                 ~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../../../../interfaces/src/data/starch/starchMetadataHelpers.c:330:59: note: length computed here
  330 |                 strncpy(iter->signature, signature, strlen(signature) + 1);
      |                                                     ~~~~~~^~~~~~~~~~~
../../../../interfaces/src/data/starch/unstarchHelpers.c: In function int starch::UNSTARCH_extractDataWithGzip(FILE**, FILE*, const char*, const Metadata*, uint64_t, starch::Boolean):
../../../../interfaces/src/data/starch/unstarchHelpers.c:200:32: warning: char* strncpy(char*, const char*, size_t) output truncated before terminating nul copying as many bytes from a string as its length [-Wstringop-truncation]
  200 |                         strncpy(reinterpret_cast<char *>( zLineBuf ), reinterpret_cast<const char *>( zRemainderBuf ), strlen(reinterpret_cast<const char *>( zRemainderBuf )));
      |                         ~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../../../../interfaces/src/data/starch/starchMetadataHelpers.c: In function int starch::STARCH_readLegacyMetadata(const char*, starch::Metadata**, starch::CompressionType*, starch::ArchiveVersion**, uint64_t*, starch::Boolean*, starch::Boolean):
../../../../interfaces/src/data/starch/starchMetadataHelpers.c:2221:32: warning: char* strncpy(char*, const char*, size_t) specified bound depends on the length of the source argument [-Wstringop-overflow=]
 2221 |                         strncpy(recTokBuf, token, strlen(token) + 1);
      |                         ~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../../../../interfaces/src/data/starch/starchMetadataHelpers.c:2221:57: note: length computed here
 2221 |                         strncpy(recTokBuf, token, strlen(token) + 1);
      |                                                   ~~~~~~^~~~~~~
../../../../interfaces/src/data/starch/starchMetadataHelpers.c:2237:32: warning: char* strncpy(char*, const char*, size_t) specified bound depends on the length of the source argument [-Wstringop-overflow=]
 2237 |                         strncpy(recChromosome, recTokBuf, strlen(recTokBuf) + 1);
      |                         ~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../../../../interfaces/src/data/starch/starchMetadataHelpers.c:2237:65: note: length computed here
 2237 |                         strncpy(recChromosome, recTokBuf, strlen(recTokBuf) + 1);
      |                                                           ~~~~~~^~~~~~~~~~~
../../../../interfaces/src/data/starch/starchMetadataHelpers.c:2249:32: warning: char* strncpy(char*, const char*, size_t) specified bound depends on the length of the source argument [-Wstringop-overflow=]
 2249 |                         strncpy(recFilename, token, strlen(token) + 1);
      |                         ~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../../../../interfaces/src/data/starch/starchMetadataHelpers.c:2249:59: note: length computed here
 2249 |                         strncpy(recFilename, token, strlen(token) + 1);
      |                                                     ~~~~~~^~~~~~~
/eb/maint/software/binutils/2.35-GCCcore-10.2.0/bin/ld.gold: error: cannot find -lc
/eb/maint/software/binutils/2.35-GCCcore-10.2.0/bin/ld.gold: error: cannot find -lpthread
/lib/../lib64/crt1.o(.text+0x12): error: undefined reference to '__libc_csu_fini'
/lib/../lib64/crt1.o(.text+0x19): error: undefined reference to '__libc_csu_init'
/lib/../lib64/crt1.o(.text+0x25): error: undefined reference to '__libc_start_main'
/tmp/eb-1vd577n_/ccDWSrs1.o:convert2bed.c:function c2b_print_format_usage: error: undefined reference to 'fprintf'
/tmp/eb-1vd577n_/ccDWSrs1.o:convert2bed.c:function c2b_print_usage: error: undefined reference to 'fprintf'
/tmp/eb-1vd577n_/ccDWSrs1.o:convert2bed.c:function c2b_gff_init_element: error: undefined reference to 'malloc'
/tmp/eb-1vd577n_/ccDWSrs1.o:convert2bed.c:function c2b_gff_init_element: error: undefined reference to 'malloc'
/tmp/eb-1vd577n_/ccDWSrs1.o:convert2bed.c:function c2b_gff_init_element: error: undefined reference to 'malloc'
/tmp/eb-1vd577n_/ccDWSrs1.o:convert2bed.c:function c2b_gff_init_element: error: undefined reference to 'malloc'
/tmp/eb-1vd577n_/ccDWSrs1.o:convert2bed.c:function c2b_gff_init_element: error: undefined reference to 'stderr'
/tmp/eb-1vd577n_/ccDWSrs1.o:convert2bed.c:function c2b_gff_init_element: error: undefined reference to 'fwrite'
/tmp/eb-1vd577n_/ccDWSrs1.o:convert2bed.c:function c2b_gff_init_element: error: undefined reference to 'exit'
/tmp/eb-1vd577n_/ccDWSrs1.o:convert2bed.c:function c2b_gff_init_element: error: undefined reference to 'stderr'
/tmp/eb-1vd577n_/ccDWSrs1.o:convert2bed.c:function c2b_gff_init_element: error: undefined reference to 'stderr'
/tmp/eb-1vd577n_/ccDWSrs1.o:convert2bed.c:function c2b_gff_init_element: error: undefined reference to 'stderr'
/tmp/eb-1vd577n_/ccDWSrs1.o:convert2bed.c:function c2b_gtf_init_element: error: undefined reference to 'fwrite'
/tmp/eb-1vd577n_/ccDWSrs1.o:convert2bed.c:function c2b_gtf_init_element: error: undefined reference to 'exit'
```
etc.

**Comment by boegel** [comment]
@verdurin Missing `glibc-static`?

**Comment by boegel** [comment]
closing this since `foss/2020b` is deprecated, see https://docs.easybuild.io/policies/toolchains

see also:
* #16904

**Pull request closed without merging**
