### PR TITLE
{bio}[GCCcore/10.3.0] GD v2.73

### PR DESCRIPTION
**Pull request by SIB-software**
(created using `eb --new-pr`)

### CODE REVIEW

**Review by boegel — DISMISSED** [review]
lgtm

**Comment by boegel** [comment]
@boegelbot please test @ generoso

**Comment by boegel** [comment]
Test report by @boegel
**FAILED**
Build succeeded for 1 out of 2 (1 easyconfigs in total)
node2605.swalot.os - Linux centos linux 7.9.2009, x86_64, Intel(R) Xeon(R) CPU E5-2660 v3 @ 2.60GHz (haswell), Python 3.6.8
See https://gist.github.com/7cc3bffd5fff4a15ffe46e22ab481961 for a full test report.

**Comment by boegel** [comment]
@SIB-software Looks like `libXpm` needs to be added as dependency too, which we have as a part of the `X11` bundle:


```
Package xpm was not found in the pkg-config search path.
Perhaps you should add the directory containing `xpm.pc'
to the PKG_CONFIG_PATH environment variable
Package 'xpm', required by 'gdlib', not found
 at Makefile.PL line 451.
*** can not find package gdlib
*** check that it is properly installed and available in PKG_CONFIG_PATH
 at Makefile.PL line 451.
 (at easybuild/tools/run.py:577 in parse_cmd_output)
```

```
$ rpm -qf /usr/lib64/pkgconfig/xpm.pc
libXpm-devel-3.5.12-1.el7.x86_64
```

**Comment by smoretti** [comment]
I will look at that, but this is weird. Previous versions and EB files don't need xpm

**Comment by smoretti** [comment]
So @boegel you think adding `('X11', '20210518')` dependency should be enough?

**Comment by verdurin** [comment]
@smoretti yes, that should be sufficient.

**Comment by smoretti** [comment]
Added

**Comment by verdurin** [comment]
Test report by @verdurin
**SUCCESS**
Build succeeded for 2 out of 2 (1 easyconfigs in total)
nuc.lan - Linux Fedora 33, x86_64, Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz, Python 3.9.6
See https://gist.github.com/11974462a57be438d89fd57b4556591f for a full test report.

**Comment by verdurin** [comment]
Test report by @verdurin
**SUCCESS**
Build succeeded for 2 out of 2 (1 easyconfigs in total)
easybuild-c7.novalocal - Linux centos linux 7.9.2009, x86_64, Intel Xeon Processor (Skylake, IBRS), Python 3.6.8
See https://gist.github.com/546df9b7a23143d705d6d1fe48a75f4a for a full test report.

**Review by verdurin — APPROVED** [review]
Looks fine.

**Comment by verdurin** [comment]
Going in, thanks @SIB-software!

**Pull request merged**
