### PR TITLE
{data}[gompi/2022a] netCDF-C++4 v4.3.1, PnetCDF v1.12.3

### PR DESCRIPTION
**Pull request by maxim-masterov**
(created using `eb --new-pr`)

### CODE REVIEW

**Review by Micket — APPROVED** [review]
lgtm

**Comment by maxim-masterov** [comment]
I see that netCDF-Fortran v4.6.0 is already accepted and merged (see PR #15990). Should I remove it from this PR to simplify merge?

**Review by Micket — CHANGES_REQUESTED** [review]
i see another netCDF-Fortran was merged already, which also adds a missing dep. Could you drop yours from your PR?

**Comment by maxim-masterov** [comment]
@Micket done

**Review by Micket — APPROVED** [review]
lgtm

**Comment by Micket** [comment]
Test report by @Micket
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in total)
alvis-c1 - Linux Rocky Linux 8.5, x86_64, Intel Xeon Processor (Skylake), Python 3.6.8
See https://gist.github.com/ffef9be44c839ade127f3d615affe5a6 for a full test report.

**Comment by Micket** [comment]
Going in, thanks @maxim-masterov!

**Pull request merged**
