### PR TITLE
{devel}[system] ReFrame v3.4.1

### PR DESCRIPTION
**Pull request by teojgo**
Fixes https://github.com/eth-cscs/reframe/issues/1749

### CODE REVIEW

**Comment by akesandgren** [comment]
Should probably use 3.4.1 instead since that is already out.

**Comment by boegel** [comment]
@boegelbot please test @ generoso

**Review by boegel — APPROVED** [review]
lgtm

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
node2604.swalot.os - Linux centos linux 7.9.2009, x86_64, Intel(R) Xeon(R) CPU E5-2660 v3 @ 2.60GHz (haswell), Python 3.6.8
See https://gist.github.com/1b04e62a65fce371597becc6d97b158b for a full test report.

**Comment by boegel** [comment]
> Should probably use 3.4.1 instead since that is already out.

Done in 188595d

**Comment by migueldiascosta** [comment]
Test report by @migueldiascosta
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in total)
sms - Linux centos linux 7.6.1810, x86_64, AMD EPYC 7601 32-Core Processor (zen), Python 2.7.5
See https://gist.github.com/a8267061708e053aa892926ee7bac3a3 for a full test report.

**Pull request merged**
