### PR TITLE
disable default EULA acceptance in n/NVHPC/NVHPC-21.5.eb

### PR DESCRIPTION
**Pull request by lexming**
(created using `eb --new-pr`)

This PR brings `NVHPC-21.5.eb` in agreement with the other easyconfigs of NVHPC.
Fixes unintended change in https://github.com/easybuilders/easybuild-easyconfigs/pull/13028

### CODE REVIEW

**Comment by lexming** [comment]
Test report by @lexming
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
node226.hydra.os - Linux centos linux 7.9.2009, x86_64, Intel(R) Xeon(R) CPU E5-2680 v4 @ 2.40GHz, Python 2.7.5
See https://gist.github.com/ed8d38b27289307ad739f6fcb0c8d21b for a full test report.

**Review by Micket — APPROVED** [review]
lgtm

**Comment by Micket** [comment]
Test suite seems stuck, syncing with develop again

**Comment by Micket** [comment]
Going in, thanks @lexming!

**Pull request merged**
