### PR TITLE
{data}[foss/2019b] HDBSCAN v0.8.24 w/ Python 3.7.4

### PR DESCRIPTION
**Pull request by seb45tian**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by seb45tian** [comment]
Test report by @seb45tian
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
r10n47.palma.wwu - Linux centos linux 7.9.2009, x86_64, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz, Python 3.6.8
See https://gist.github.com/2ffa55a66b41c28fac278d63c3e4bebd for a full test report.

**Comment by verdurin** [comment]
@boegelbot please test @ generoso

**Comment by verdurin** [comment]
Test report by @verdurin
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
easybuild-c7.novalocal - Linux centos linux 7.9.2009, x86_64, Intel Xeon Processor (Skylake, IBRS), Python 3.6.8
See https://gist.github.com/25a289684be194d114d39a899cc2d54e for a full test report.

**Comment by verdurin** [comment]
Test report by @verdurin
**SUCCESS**
Build succeeded for 41 out of 41 (1 easyconfigs in total)
centos7.lan - Linux centos linux 7.9.2009, x86_64, Intel Core Processor (Skylake, IBRS), Python 3.6.8
See https://gist.github.com/4895aef5041e6ae6bbcb53b5fd4b0dd2 for a full test report.

**Review by verdurin — APPROVED** [review]
Looks fine.

**Comment by verdurin** [comment]
Going in, thanks @seb45tian!

**Pull request merged**
