### PR TITLE
{math}[intel/2019b] SUNDIALS v5.1.0

### PR DESCRIPTION
**Pull request by JackPerdue**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by JackPerdue** [comment]
The local_variables check should also be added to --check-contrib (like the https check)... rather frustrating to try to make an easyconfig conform only to find out that there were other checks not run yet.

In fact, I go a step further and say "You may not add a conformance test to Travis without adding a corresponding test to --check-contrib".  (I'd add a "DAMMIT" given my locale)

I guess I get to do another --update-pr (PITA).

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
generoso - Linux centos linux 7.6.1810, Intel(R) Xeon(R) CPU E5-2660 v4 @ 2.00GHz, Python 3.6.8
See https://gist.github.com/7d48f439111143fbd19795eaaa5e8b06 for a full test report.

**Comment by boegel** [comment]
@JackPerdue What we need to do is make both the test suite and `--check-contrib` use the same code. It's on our TODO list...

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
node3108.skitty.os - Linux centos linux 7.7.1908, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz, Python 3.6.8
See https://gist.github.com/bc1c48edc7c45337d3ac032a6dfcb9b8 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
node2401.golett.os - Linux centos linux 7.7.1908, Intel(R) Xeon(R) CPU E5-2680 v3 @ 2.50GHz, Python 2.7.5
See https://gist.github.com/2757e4b73d2536f1dc09dbaeb5e47535 for a full test report.

**Comment by boegel** [comment]
Going in, thanks @JackPerdue!

**Pull request merged**
