### PR TITLE
{cae}[system/system] STAR-CCM+ v18.06.006 w/ r8

### PR DESCRIPTION
**Pull request by Micket**
(created using `eb --new-pr`)

- [x] requires https://github.com/easybuilders/easybuild-easyblocks/pull/3028

### CODE REVIEW

**Comment by Micket** [comment]
Test report by @Micket
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in total)
alvis-c1 - Linux Rocky Linux 8.8, x86_64, Intel Xeon Processor (Skylake), Python 3.6.8
See https://gist.github.com/Micket/529c0e24f6cfca47f61f895047844ddb for a full test report.

**Comment by Micket** [comment]
Test report by @Micket
**FAILED**
Build succeeded for 0 out of 2 (2 easyconfigs in total)
alvis-c1 - Linux Rocky Linux 8.8, x86_64, Intel Xeon Processor (Skylake), Python 3.6.8
See https://gist.github.com/Micket/be359314bc55e0a2c841941b3cd2647d for a full test report.

**Comment by Micket** [comment]
So, EB incorrectly insists on not allowing modulerc configs there the version mapping isn't a prefix of the full version string. 

But, by manually adding this myself:
```
$ cat /apps/Common/fmodules/all/STAR-CCM+/.modulerc.lua 
module_version("STAR-CCM+/18.06.006", "2310")
```
and  just trying it, it works just fine
```
$ ml STAR-CCM+/2310
$ ml

Currently Loaded Modules:
  1) EasyBuild/4.8.1   2) STAR-CCM+/2310 -> STAR-CCM+/18.06.006
```

**Comment by Micket** [comment]
Test report by @Micket
Using easyblocks from PR(s) https://github.com/easybuilders/easybuild-easyblocks/pull/3028
**FAILED**
Build succeeded for 0 out of 2 (2 easyconfigs in total)
alvis-c1 - Linux Rocky Linux 8.8, x86_64, Intel Xeon Processor (Skylake), Python 3.6.8
See https://gist.github.com/Micket/d688e2aa3a0778bca21379b12fa7bda5 for a full test report.

**Comment by Micket** [comment]
Test report by @Micket
Using easyblocks from PR(s) https://github.com/easybuilders/easybuild-easyblocks/pull/3028
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in total)
alvis-c1 - Linux Rocky Linux 8.8, x86_64, Intel Xeon Processor (Skylake), Python 3.6.8
See https://gist.github.com/Micket/ebfe56b5f268e2d73088574c07926039 for a full test report.

**Review by zao — APPROVED** [review]
Looks good now with the easyblock update in place.

**Pull request merged**
