### PR TITLE
{bio}[foss/2020b] MDAnalysis v1.1.1 w/ Python 3.8.6

### PR DESCRIPTION
**Pull request by robert-mijakovic**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by verdurin** [comment]
@robert-mijakovic please take a look at the test failures, relating to multi-variant deps and the specific `tqdm` version.

**Comment by robert-mijakovic** [comment]
> @robert-mijakovic please take a look at the test failures, relating to multi-variant deps and the specific `tqdm` version.

Solved!

**Comment by robert-mijakovic** [comment]
@boegelbot: please test @ generoso

**Comment by robert-mijakovic** [comment]
Test report by @robert-mijakovic
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
login01.meluxina.lxp.lu - Linux RHEL 8.3, x86_64, AMD EPYC 7452 32-Core Processor (zen2), Python 3.6.8
See https://gist.github.com/aed6abe9b68e2064fd6dfd3247a1ad86 for a full test report.

**Comment by SebastianAchilles** [comment]
Going in, thanks @robert-mijakovic!

**Pull request merged**
