### PR TITLE
fix version and source for Seurat, add extensions required by Seurat in R 3.4.0 easyconfig

### PR DESCRIPTION
**Pull request by boegel**
Loading Seurat in R results in the following error:

```
> library(Seurat)
Error: package ‘Seurat’ was built for x86_64-apple-darwin13.4.0
```

This went undetected because of a bug in the EasyBuild framework where the `library(...)` import checks for R extensions were basically being skipped, see https://github.com/easybuilders/easybuild-framework/pull/2276.

The problem was the we were using the binary release of Seurat, rather than the source tarball...

As it turns out, several R extensions were also missing as dependencies.

### CODE REVIEW

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in this PR)
node2541.golett.os - Linux centos linux 7.3.1611, Intel(R) Xeon(R) CPU E5-2680 v3 @ 2.50GHz, Python 2.7.5
See https://gist.github.com/a611caa8da1570cab125e718c7ffe8f0 for a full test report.

**Comment by boegel** [comment]
Tested on top of https://github.com/easybuilders/easybuild-framework/pull/2276.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in this PR)
node2035.delcatty.os - Linux centos linux 7.3.1611, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.7.5
See https://gist.github.com/9ff590bac89bcd5680f08c005486424c for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in this PR)
node2011.delcatty.os - Linux centos linux 7.3.1611, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.7.5
See https://gist.github.com/cf3a6d7e8a59fe287c8be0f0d18bb746 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in this PR)
node2510.golett.os - Linux centos linux 7.3.1611, Intel(R) Xeon(R) CPU E5-2680 v3 @ 2.50GHz, Python 2.7.5
See https://gist.github.com/7f3f8f95f91cce149d6edd18bcd6ffc3 for a full test report.

**Comment by boegel** [comment]
@vanzod Good to go now?

**Comment by vanzod** [comment]
Going in, thanks @boegel!

**Pull request merged**
