### PR TITLE
{devel}[GCCcore/8.3.0] SWIG v4.0.1

### PR DESCRIPTION
**Pull request by boegel**
(created using `eb --new-pr`)

requires https://github.com/easybuilders/easybuild-easyblocks/pull/1894

### CODE REVIEW

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
node2407.golett.os - Linux centos linux 7.7.1908, Intel(R) Xeon(R) CPU E5-2680 v3 @ 2.50GHz, Python 2.7.5
See https://gist.github.com/f12cc4fb7a0ffbf4379fb0015eefa03f for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
node3152.skitty.os - Linux centos linux 7.7.1908, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz, Python 3.6.8
See https://gist.github.com/470fd85f13729dc7ec862a477cead379 for a full test report.

**Comment by akesandgren** [comment]
See https://github.com/easybuilders/easybuild-easyconfigs/pull/9443 and https://github.com/jose-d/easybuild-easyconfigs/pull/2

I.e., you're missing the configopts, and the move to CMakeMake for SWIG.

**Comment by smoors** [comment]
@boegel this version seems to still support Python 2, no?

**Comment by boegel** [comment]
@smoors Yes, but using `multi_deps` for SWIG causes problems because it's a build-only dep (and Python usually is not), and `builddependencies` are loaded before `dependencies` (so loading SWIG loads Python 3.x by default, which then causes problems when Python 2.x is loaded as dependency).

Best way forward is to just drop the `Python` dep in SWIG, see also recent discussion we had with @akesandgren

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
generoso - Linux centos linux 7.6.1810, Intel(R) Xeon(R) CPU E5-2660 v4 @ 2.00GHz, Python 3.6.8
See https://gist.github.com/fba1409f06e68037048861cecb6d9c12 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
node2454.golett.os - Linux centos linux 7.7.1908, Intel(R) Xeon(R) CPU E5-2680 v3 @ 2.50GHz, Python 2.7.5
See https://gist.github.com/19e4b75cd177a87d705da81306e60a9c for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
node3124.skitty.os - Linux centos linux 7.7.1908, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz, Python 3.6.8
See https://gist.github.com/21aa7917a3d95d4c38fd6a6aa71f1102 for a full test report.

**Comment by bartoldeman** [comment]
Test report by @bartoldeman
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
build-node.computecanada.ca - Linux centos linux 7.7.1908, Intel Xeon Processor (Skylake, IBRS), Python 2.7.13
See https://gist.github.com/043042a197b7c9b819e93cd52dd3f26a for a full test report.

**Comment by bartoldeman** [comment]
Going in, thanks @boegel!

**Pull request merged**
