### PR TITLE
{lib,vis}[GCC/13.3.0] pocl v6.0, VirtualGL v3.1.1

### PR DESCRIPTION
**Pull request by paulmelis**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by paulmelis** [comment]
Needs https://github.com/easybuilders/easybuild-easyconfigs/pull/21380 for libGLU

**Comment by smoors** [comment]
@boegelbot: please test @ generoso

**Comment by smoors** [comment]
@boegelbot please test @ jsc-zen3

**Review by smoors — APPROVED** [review]
lgtm

**Comment by smoors** [comment]
Going in, thanks @paulmelis!

**Pull request merged**
