### PR TITLE
+download URL for imkl 2018.3

### PR DESCRIPTION
**Pull request by jose-d**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by jose-d** [comment]
Test report by @jose-d
**FAILED**
Build succeeded for 0 out of 1 (1 easyconfigs in this PR)
koios1 - Linux centos linux 7.3.1611, Intel(R) Xeon(R) Gold 6130 CPU @ 2.10GHz, Python 2.7.5
See https://gist.github.com/fe687be1034109f522f76cc731c2127b for a full test report.

**Comment by jose-d** [comment]
> Test report by @jose-d
> **FAILED**
`Another instance of the installation program has been detected. Please quit the other instance and try again.` ^^, ok, parallel building is not good.

**Comment by jose-d** [comment]
Test report by @jose-d
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
koios1 - Linux centos linux 7.3.1611, Intel(R) Xeon(R) Gold 6130 CPU @ 2.10GHz, Python 2.7.5
See https://gist.github.com/2b2677ed5b6976456f5af7fd74d920f9 for a full test report.

**Comment by jose-d** [comment]
```found 2 variants of 'PyQt5' dependency in easyconfigs using '2018a' toolchain generation
* version: 5.10.1; versionsuffix: -Python-3.6.4 as dep for set(['AFNI-18.1.09-intel-2018a-Python-3.6.4.eb'])
* version: 5.9.2; versionsuffix: -Python-3.6.4 as dep for set(['Spyder-3.3.1-foss-2018a-Python-3.6.4.eb'])```

IMO CI bug.

**Comment by boegel** [comment]
Going in, thanks @jose-d!

**Pull request merged**
