### PR TITLE
fix toolchain for pytest-xdist v2.1.0 w/ Python 3.8.6, should be GCCcore

### PR DESCRIPTION
**Pull request by schiotz**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by schiotz** [comment]
This is a bug fix to PR #11883 which was merged earlier today by @boegel .  I do not know why the system thinks it is a new file.

I made a serious error in PR #11883 :  The file name indicated toolchain GCCcore/10.2.0  but the content of the file specified foss/2020b, resulting in a module being built with a too specific toolchain and that does not match the filename.  I thought the test system would catch something like that, but maybe it falls through the cracks because one is a subchain of the other.

In any case, this PR fixed the toolchain so it is consistent.  Sorry about the mess.

**Comment by smoors** [comment]
@schiotz I removed the original file for you, using (note the colon before the easyconfig to be removed)
```
eb --update-pr 11893 --commit-msg msg pytest-xdist-2.1.0-GCCcore-10.2.0.eb :pytest-xdist-2.1.0-foss-2020b.eb
```

**Comment by smoors** [comment]
Test report by @smoors
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
node372.hydra.os - Linux centos linux 7.9.2009, x86_64, Intel(R) Xeon(R) Gold 6148 CPU @ 2.40GHz (skylake_avx512), Python 2.7.5
See https://gist.github.com/efdd3b142a679d2f299074e5c0152fde for a full test report.

**Comment by boegel** [comment]
@schiotz The file name in the PR itself is actually correct, it matches with the toolchain used in the the file (otherwise the tests would've definitely failed).

Your local file may be named `-*GCCcore-10.2.0.eb`, but `eb --new-pr` basically ignores the filename, and derives the correct filename from the contents of the file (which is why it's correct in PR #11883).

Anyway, no big problem, I should have spotted that `pytest-xdist` doesn't need a full `foss` toolchain...

Thanks a lot for following up quickly with a fix!

**Comment by boegel** [comment]
@boegelbot please test @ generoso

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
node3501.doduo.os - Linux RHEL 8.2, x86_64, AMD EPYC 7552 48-Core Processor (zen2), Python 3.6.8
See https://gist.github.com/cb3fa2a4185c65d0f1a5c258fa089295 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
node3151.skitty.os - Linux centos linux 7.9.2009, x86_64, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz, Python 3.6.8
See https://gist.github.com/7bb1916180e30c08d84a07d3e47d2653 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
node2676.swalot.os - Linux centos linux 7.9.2009, x86_64, Intel(R) Xeon(R) CPU E5-2660 v3 @ 2.60GHz (haswell), Python 3.6.8
See https://gist.github.com/167da806184d85e89056a8ee623bd355 for a full test report.

**Review by boegel — APPROVED** [review]

**Comment by boegel** [comment]
Going in, thanks @schiotz!

**Pull request merged**
