### PR TITLE
{bio}[fosscuda/2018b] MRtrix v3.0_RC3 w/ Python 3.6.6

### PR DESCRIPTION
**Pull request by dithwick**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by dithwick** [comment]
Test report by @dithwick
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
login2 - Linux centos 6.10, Intel(R) Xeon(R) CPU E5-2630 v3 @ 2.40GHz, Python 2.6.6
See https://gist.github.com/8c0056418391523fda22f5344fef9e05 for a full test report.

**Comment by dithwick** [comment]
I'm not sure how to work around this 

```
found 2 variants of 'Qt5' dependency in easyconfigs using '2018b' toolchain generation
```

issue. It looked like it was working through the foss rather than fosscuda toolchain but regardless, the 5.10.1 version of QT5 won't build on CentOS 6 hence 5.9.8.

Any ideas?

**Comment by migueldiascosta** [comment]
@dithwick you can get Qt5 5.10.x to install in CentOS 6 if you manually set `check_qtwebengine = False`

https://github.com/easybuilders/easybuild-easyblocks/pull/1771 will do that automatically based on the `glibc` version

**Comment by dithwick** [comment]
Completely forgot about this pull-request (sorry). Might as well close it as it's been superseded.

**Pull request closed without merging**
