### PR TITLE
only use ScaFaCos as dependency for LAMMPS 23Jun2022 on `x86_64`

### PR DESCRIPTION
**Pull request by laraPPr**
(created using `eb --new-pr`)

~~requires:~~
* ~~#19163~~

### CODE REVIEW

**Comment by laraPPr** [comment]
Test report by @laraPPr
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
node3605.doduo.os - Linux RHEL 8.8, x86_64, AMD EPYC 7552 48-Core Processor, Python 3.6.8
See https://gist.github.com/laraPPr/68470904fac26057a013b2c55136b5ec for a full test report.

**Comment by boegel** [comment]
@boegelbot please test @ generoso

**Comment by boegel** [comment]
@boegelbot please test @ jsc-zen2

**Review by boegel — APPROVED** [review]

**Comment by boegel** [comment]
Going in, thanks @laraPPr!

**Pull request merged**
