### PR TITLE
{bio}[system/system] modeltest-ng v0.1.6

### PR DESCRIPTION
**Pull request by robqiao**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by pescobar** [comment]
Test report by @pescobar
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
generoso - Linux centos linux 8.2.2004, x86_64, Intel(R) Xeon(R) CPU E5-2667 v3 @ 3.20GHz, Python 3.6.8
See https://gist.github.com/ec5e2e67e1057f2e3f7a23a1bda174bf for a full test report.

**Comment by pescobar** [comment]
Test report by @pescobar
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
generoso-c1-s-1 - Linux centos linux 8.2.2004, x86_64, Intel(R) Xeon(R) CPU E5-2667 v3 @ 3.20GHz, Python 3.6.8
See https://gist.github.com/060ce1cf4fb19bd6126c1ef3075ac38b for a full test report.

**Comment by boegel** [comment]
@robqiao Any specific reason for using the binary version? It *looks* like a pretty straightforward installation with `cmake` and `make`?

**Comment by robqiao** [comment]
> 
> 
> @robqiao Any specific reason for using the binary version? It _looks_ like a pretty straightforward installation with `cmake` and `make`?

Hmm, it has a moving dependencies `pll` [here](https://github.com/ddarriba/pll-modules/tree/82959854129c05a18741ecb93a6ba5c00b9eb667) and has been quite old, I can only compile successfully with `gcc` upto `7`. I thought it just more robust with binary at this stage.

**Pull request closed without merging**
