### PR TITLE
Make Pillow easyconfigs aware of sysroot

### PR DESCRIPTION
**Pull request by ocaisa**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by ocaisa** [comment]
@boegelbot please test @ jsc-zen2

**Comment by ocaisa** [comment]
@boegelbot please test @ generoso

**Comment by verdurin** [comment]
Test report by @verdurin
**SUCCESS**
Build succeeded for 14 out of 14 (13 easyconfigs in total)
easybuild-c7.novalocal - Linux CentOS Linux 7.9.2009, x86_64, Intel Xeon Processor (Skylake, IBRS), Python 3.6.8
See https://gist.github.com/verdurin/d6ec8432c7ee073ee5be40c3a02514a7 for a full test report.

**Review by verdurin — APPROVED** [review]
Looks fine.

**Comment by verdurin** [comment]
Going in, thanks @ocaisa!

**Comment by boegel** [comment]
@ocaisa Wouldn't it be better to try and patch the hardcoded paths in Pillow's `setup.py` via `sed` & `%(sysroot)s`, rather than always adding `<sysroot>/usr/include` to `$CPATH` (and likewise for `$LD_LIBRARY_PATH`), so we're really only changing something when `%(sysroot)s` is not an empty string (now we're always adding `/usr/include` to `$CPATH`, I'm not sure that's wise).

**Comment by boegel** [comment]
> @ocaisa Wouldn't it be better to try and patch the hardcoded paths in Pillow's `setup.py` via `sed` & `%(sysroot)s`, rather than always adding `<sysroot>/usr/include` to `$CPATH` (and likewise for `$LD_LIBRARY_PATH`), so we're really only changing something when `%(sysroot)s` is not an empty string (now we're always adding `/usr/include` to `$CPATH`, I'm not sure that's wise).

implemented in #19267

**Pull request merged**
