### PR TITLE
{tools}[foss/2018b] ncdu v1.14

### PR DESCRIPTION
**Pull request by SethosII**
(created using `eb --new-pr`)

The `large-file-count` patch is now already included.

### CODE REVIEW

**Comment by SethosII** [comment]
Test report by @SethosII
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
ribnode015 - Linux ubuntu 18.04, Intel(R) Xeon(R) CPU           E5645  @ 2.40GHz, Python 2.7.15rc1
See https://gist.github.com/9a02d09435579e8f802536b93c2217be for a full test report.

**Comment by SethosII** [comment]
Test report by @SethosII
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
ribnode015 - Linux ubuntu 18.04, Intel(R) Xeon(R) CPU           E5645  @ 2.40GHz, Python 2.7.15rc1
See https://gist.github.com/f96835ab790489046f0afbcc36833ed3 for a full test report.

**Comment by vanzod** [comment]
@SethosII Can you use the `GCCcore` toolchain instead of `foss`?

**Comment by boegel** [comment]
Agreed, especially since the existing `ncdu` easyconfig is already using `GCCcore`

**Comment by SethosII** [comment]
Ups, missed that. I changed the toolchain to `GCcore`.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
node2006.delcatty.os - Linux centos linux 7.6.1810, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.7.5
See https://gist.github.com/0c82069d5ba6c87e85cac93126b9357c for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
node3102.skitty.os - Linux centos linux 7.6.1810, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz, Python 2.7.5
See https://gist.github.com/a440a450fb024de47ac8e1d225667d25 for a full test report.

**Comment by boegel** [comment]
Going in, thanks @SethosII!

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
node2434.golett.os - Linux centos linux 7.6.1810, Intel(R) Xeon(R) CPU E5-2680 v3 @ 2.50GHz, Python 2.7.5
See https://gist.github.com/b8fd5fdd4ae496f97c590bbaa4e0ab91 for a full test report.

**Pull request merged**
