### PR TITLE
{perf}[GCCcore/13.2.0] Score-P v8.4, CubeLib v4.8.2, CubeWriter v4.8.2, OPARI2 v2.0.8, ... tools

### PR DESCRIPTION
**Pull request by Flamefire**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by Flamefire** [comment]
Test report by @Flamefire
**FAILED**
Build succeeded for 9 out of 12 (9 easyconfigs in total)
n1577 - Linux RHEL 8.7 (Ootpa), x86_64, Intel(R) Xeon(R) Platinum 8470 (icelake), Python 3.8.13
See https://gist.github.com/Flamefire/bcd7eadaee4c22279c2efdd59b99eb01 for a full test report.

**Comment by Flamefire** [comment]
Test report by @Flamefire
**FAILED**
Build succeeded for 8 out of 9 (9 easyconfigs in total)
n1577 - Linux RHEL 8.7 (Ootpa), x86_64, Intel(R) Xeon(R) Platinum 8470 (icelake), Python 3.8.13
See https://gist.github.com/Flamefire/3a49f27e390145480edeacb36abd5159 for a full test report.

**Comment by Flamefire** [comment]
Test report by @Flamefire
**FAILED**
Build succeeded for 7 out of 8 (8 easyconfigs in total)
n1539 - Linux RHEL 8.7 (Ootpa), x86_64, Intel(R) Xeon(R) Platinum 8470 (icelake), Python 3.8.13
See https://gist.github.com/Flamefire/2c0e5b0b4f5b3ecd02a2a9cf715ca998 for a full test report.

**Comment by Flamefire** [comment]
Test report by @Flamefire
**SUCCESS**
Build succeeded for 8 out of 8 (8 easyconfigs in total)
n1539 - Linux RHEL 8.7 (Ootpa), x86_64, Intel(R) Xeon(R) Platinum 8470 (icelake), Python 3.8.13
See https://gist.github.com/Flamefire/e87dd334746ad8cdf6dc33179abff51c for a full test report.

**Comment by Flamefire** [comment]
Test report by @Flamefire
**FAILED**
Build succeeded for 6 out of 8 (8 easyconfigs in total)
i8032 - Linux Rocky Linux 8.7, x86_64, AMD EPYC 7352 24-Core Processor (zen2), 8 x NVIDIA NVIDIA A100-SXM4-40GB, 545.23.08, Python 3.6.8
See https://gist.github.com/Flamefire/2facacd330865c15caebe3fae7337519 for a full test report.

**Comment by Flamefire** [comment]
Test report by @Flamefire
**FAILED**
Build succeeded for 6 out of 8 (8 easyconfigs in total)
i8032 - Linux Rocky Linux 8.7, x86_64, AMD EPYC 7352 24-Core Processor (zen2), 8 x NVIDIA NVIDIA A100-SXM4-40GB, 545.23.08, Python 3.6.8
See https://gist.github.com/Flamefire/1af46451970f148c1f6632aaf97e56b3 for a full test report.

**Comment by Thyre** [comment]
As mentioned in https://github.com/easybuilders/easybuild-easyconfigs/pull/20146#issuecomment-2006494847, we may want to update the Score-P version to v8.4, as it has released just last Friday. Might be nice for users to have the latest bug fixes as well :smile:

**Comment by Flamefire** [comment]
Test report by @Flamefire
**FAILED**
Build succeeded for 6 out of 8 (8 easyconfigs in total)
i8001 - Linux Rocky Linux 8.7 (Green Obsidian), x86_64, AMD EPYC 7352 24-Core Processor (zen2), 8 x NVIDIA NVIDIA A100-SXM4-40GB, 545.23.08, Python 3.8.13
See https://gist.github.com/Flamefire/3a6018aa7a9dbc99001011c586c1295f for a full test report.

**Comment by Flamefire** [comment]
Test report by @Flamefire
**SUCCESS**
Build succeeded (with --ignore-test-failure) for 8 out of 8 (8 easyconfigs in total)
i8001 - Linux Rocky Linux 8.7 (Green Obsidian), x86_64, AMD EPYC 7352 24-Core Processor (zen2), 8 x NVIDIA NVIDIA A100-SXM4-40GB, 545.23.08, Python 3.8.13
See https://gist.github.com/Flamefire/c88cf88db8773b1b220ec2c0d8233928 for a full test report.

**Comment by casparvl** [comment]
@boegelbot please test @ generoso

**Comment by casparvl** [comment]
Test report by @casparvl
**FAILED**
Build succeeded for 7 out of 9 (8 easyconfigs in total)
tcn1.local.snellius.surf.nl - Linux RHEL 8.6, x86_64, AMD EPYC 7H12 64-Core Processor, Python 3.6.8
See https://gist.github.com/casparvl/f422e883b5b3f63d5e59bdee91ce64d0 for a full test report.

**Comment by casparvl** [comment]
Weird...
```
== FAILED: Installation ended unsuccessfully (build directory: /scratch-nvme/1/casparl/ebbuildpath/ScoreP/8.4/gompi-2023b): build failed (first 300 chars): Missing modules for dependencies (use --robot?): PDT/3.25.2-GCCcore-13.2.0 (took 3 secs)
== Results of the build can be found in the log file(s) /scratch-nvme/1/casparl/ebtmpdir/eb-e7ie6t8h/easybuild-Score-P-8.4-20240319.173619.RfhhN.log
```
That is included in your PR, and I ran with `--robot`... not sure what went wrong there. Let me retry...

**Comment by casparvl** [comment]
Test report by @casparvl
**FAILED**
Build succeeded for 6 out of 8 (8 easyconfigs in total)
tcn1.local.snellius.surf.nl - Linux RHEL 8.6, x86_64, AMD EPYC 7H12 64-Core Processor, Python 3.6.8
See https://gist.github.com/casparvl/8f5b93d753b684ec1931b538825ab725 for a full test report.

**Comment by casparvl** [comment]
Test report by @casparvl
**SUCCESS**
Build succeeded for 8 out of 8 (8 easyconfigs in total)
tcn1.local.snellius.surf.nl - Linux RHEL 8.6, x86_64, AMD EPYC 7H12 64-Core Processor, Python 3.6.8
See https://gist.github.com/casparvl/ce67db664e5c2f5f3dd359439788be64 for a full test report.

**Review by casparvl — APPROVED** [review]
Lgtm!

**Comment by casparvl** [comment]
Going in, thanks @Flamefire!

**Pull request merged**
