### PR TITLE
Updating cuDNN 8.8 easyconfig to fetch live sources

### PR DESCRIPTION
**Pull request by robogast**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by robogast** [comment]
Test report by @robogast
**FAILED**
Build succeeded for 0 out of 1 (1 easyconfigs in total)
gcn3.local.snellius.surf.nl - Linux Rocky Linux 8.7, x86_64, Intel(R) Xeon(R) Platinum 8360Y CPU @ 2.40GHz, 4 x NVIDIA NVIDIA A100-SXM4-40GB, 515.86.01, Python 3.6.8
See https://gist.github.com/443d8360fa27c3e7c6219a2c2ffd5fcf for a full test report.

**Comment by robogast** [comment]
Test report by @robogast
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
gcn3.local.snellius.surf.nl - Linux Rocky Linux 8.7, x86_64, Intel(R) Xeon(R) Platinum 8360Y CPU @ 2.40GHz, 4 x NVIDIA NVIDIA A100-SXM4-40GB, 515.86.01, Python 3.6.8
See https://gist.github.com/37fc24beb0863eeaae5873857cb7dc99 for a full test report.

**Comment by robogast** [comment]
re-ordered the checksum order to match the order on the cuDNN redist website (i.e. alphabetical)

**Comment by robogast** [comment]
@Micket @SebastianAchilles

**Comment by SebastianAchilles** [comment]
@boegelbot please test @ generoso

**Review by Micket — DISMISSED** [review]
lgtm

**Comment by Micket** [comment]
Test report by @Micket
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
vera-c2 - Linux Rocky Linux 8.6, x86_64, Intel Xeon Processor (Skylake), Python 3.6.8
See https://gist.github.com/8cde57865f01cb1d6f76f52ff0e4aa94 for a full test report.

**Comment by SebastianAchilles** [comment]
Test report by @sebastianachilles
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
skl-rockylinux-87 - Linux Rocky Linux 8.7, x86_64, Intel(R) Core(TM) i7-10700 CPU @ 2.90GHz (skylake), 1 x NVIDIA NVIDIA RTX A4000, 525.85.12, Python 3.6.8
See https://gist.github.com/55995d9242dc809ac2c5244a2fc9632f for a full test report.

**Comment by robogast** [comment]
Sorry, I just noticed that the last part of the source URL was unnecessary, so I thought it would still be nice to remove it :)

**Comment by robogast** [comment]
Test report by @robogast
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
gcn3.local.snellius.surf.nl - Linux Rocky Linux 8.7, x86_64, Intel(R) Xeon(R) Platinum 8360Y CPU @ 2.40GHz, 4 x NVIDIA NVIDIA A100-SXM4-40GB, 515.86.01, Python 3.6.8
See https://gist.github.com/401a18cb695266583d1ee5fdcff092f9 for a full test report.

**Comment by SebastianAchilles** [comment]
@boegelbot please test @ jsc-zen2

**Comment by SebastianAchilles** [comment]
Thanks a lot for updating the `source_urls` @robogast :+1:

**Review by SebastianAchilles — APPROVED** [review]
lgtm

**Comment by SebastianAchilles** [comment]
Going in, thanks @robogast!

**Pull request merged**
