### PR TITLE
{debugger}[GCCcore/9.3.0] GDB v9.1 w/ Python 3.8.2

### PR DESCRIPTION
**Pull request by Falkor**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by jfgrimm** [comment]
@boegelbot: please test @ generoso

**Comment by jfgrimm** [comment]
Test report by @jfgrimm
**FAILED**
Build succeeded for 1 out of 2 (1 easyconfigs in total)
node130.pri.viking.alces.network - Linux CentOS Linux 7.9.2009, x86_64, Intel(R) Xeon(R) Gold 6138 CPU @ 2.00GHz (skylake_avx512), Python 3.6.8
See https://gist.github.com/b9cf0b79852f7f83a33f071e146e7384 for a full test report.

**Comment by jfgrimm** [comment]
@Falkor did this easyconfig build for you?

**Comment by Falkor** [comment]
Oups my bad I was confused with a previous eb for GDB-9.1-GCCcore-8.3.0 which worked -- sorry for the confusion, I just tested and indeed GDB-9.1-GCCcore-9.3.0 against 2020a does not work. 
Sorry for making you loosing time guys

**Pull request closed without merging**
