### PR TITLE
switch bamtofastq to Cargo easyblock

### PR DESCRIPTION
**Pull request by Micket**
(created using `eb --new-pr`)

Requires:
* [x] new cargo easyblock https://github.com/easybuilders/easybuild-easyblocks/pull/2902
* [x] https://github.com/easybuilders/easybuild-easyblocks/pull/2934

but apparently, it needs more work first, it's not finding the vendored sources for some reason

### CODE REVIEW

**Comment by Micket** [comment]
So, i cheated a bit, renamed the github source tarball so that my checksum json thing in cargo easyblock will work. Not very robust strategy though.

**Comment by Micket** [comment]
@boegelbot please test @ generoso
EB_ARGS="--include-easyblocks-from-pr 2902"

**Comment by Micket** [comment]
Test report by @Micket
Using easyblocks from PR(s) https://github.com/easybuilders/easybuild-easyblocks/pull/2902
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
vera-c1 - Linux Rocky Linux 8.6, x86_64, Intel Xeon Processor (Skylake), Python 3.6.8
See https://gist.github.com/Micket/b728ecd040d396c3e6e46647493539f3 for a full test report.

**Comment by Micket** [comment]
Test report by @Micket
Using easyblocks from PR(s) https://github.com/easybuilders/easybuild-easyblocks/pull/2902
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
vera-c1 - Linux Rocky Linux 8.7, x86_64, Intel Xeon Processor (Skylake), Python 3.6.8
See https://gist.github.com/Micket/c610e966822dc14c8a29486c4911f048 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
Using easyblocks from PR(s) https://github.com/easybuilders/easybuild-easyblocks/pull/2902
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
node3165.skitty.os - Linux RHEL 8.6, x86_64, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz (skylake_avx512), Python 3.6.8
See https://gist.github.com/boegel/6e80af569ada1983b47564f8f793121e for a full test report.

**Comment by boegel** [comment]
@boegelbot please test @ generoso
EB_ARGS="--include-easyblocks-from-pr 2902"

**Review by boegel — APPROVED** [review]
lgtm

**Comment by boegel** [comment]
Going in, thanks @Micket!

**Pull request merged**
