### PR TITLE
bundle LAPACKE with FlexiBLAS 3.0.4

### PR DESCRIPTION
**Pull request by jfgrimm**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by jfgrimm** [comment]
note - switching to using `Bundle` means that the extra sanity checks defined in `flexiblas.py` are currently not run

**Comment by smoors** [comment]
@jfgrimm this is still marked as Draft, any updates on it?

**Comment by jfgrimm** [comment]
@smoors was waiting until I'd figured out the bundle easyblock enhancement r.e. sanity checks.
Latest commit requires the updated easyblock https://github.com/easybuilders/easybuild-easyblocks/pull/2649

**Comment by boegel** [comment]
@boegelbot please test @ generoso
EB_ARGS="--include-easyblocks-from-pr 2649 --installpath /tmp/$USER/"

**Comment by boegel** [comment]
@boegelbot please test @ generoso
EB_ARGS="--include-easyblocks-from-pr 2649 --installpath /tmp/$USER/"

**Comment by jfgrimm** [comment]
> @jfgrimm Can you apply the same changes to `FlexiBLAS-3.0.4-GCC-11.2.0.eb`, to make it consistent?

done

**Comment by boegel** [comment]
@boegelbot please test @ generoso

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in total)
node2605.swalot.os - Linux centos linux 7.9.2009, x86_64, Intel(R) Xeon(R) CPU E5-2660 v3 @ 2.60GHz (haswell), Python 3.6.8
See https://gist.github.com/3c22fb14e26e9e7fae0d326f627006c3 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in total)
node3533.doduo.os - Linux RHEL 8.2, x86_64, AMD EPYC 7552 48-Core Processor (zen2), Python 3.6.8
See https://gist.github.com/84e584bc64c5e4e26387a68d3ae570ae for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in total)
fair-mastodon-c6g-2xlarge-0001 - Linux rocky linux 8.5, AArch64, ARM UNKNOWN (graviton2), Python 3.6.8
See https://gist.github.com/561079c33c2b69c4f4f828a484ee7c61 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in total)
easybuild2.novalocal - Linux centos stream 8, POWER, IBM pSeries (emulated by qemu) (power9le), Python 3.6.8
See https://gist.github.com/05d32872c1e087f79be09f33c4fe070a for a full test report.

**Review by boegel — APPROVED** [review]
lgtm

**Comment by boegel** [comment]
Going in, thanks @jfgrimm!

**Comment by boegel** [comment]
@boegelbot please test @ jsc-zen2

**Pull request merged**
