### PR TITLE
{bio}(foss/2015b) Swarm 2.1.13 (WIP)

### PR DESCRIPTION
**Pull request by nathanhaigh**
Swarm comes with a couple of Python helper scripts. I'm not sure how the dependencies in these should be specified in the easyconfig file.

### CODE REVIEW

**Comment by wpoely86** [comment]
@nathanhaigh New dependencies that are not in the `Python` easyconfig yet?

**Comment by nathanhaigh** [comment]
@wpoely86 That's right, one of the scripts requires `igraph` and `optparse`:

```
from igraph import Graph, plot
from optparse import OptionParser
```

**Comment by wpoely86** [comment]
Than you can either add them in this easyconfig as PythonExtensions or add a dependency on them?

**Comment by boegel** [comment]
@nathanhaigh +1 on listing the required non-standard Python packages as additional extensions, see for example https://github.com/hpcugent/easybuild-easyconfigs/blob/master/easybuild/easyconfigs/m/matplotlib/matplotlib-2.0.0-intel-2016b-Python-2.7.12.eb (which `easyblock` is used for the parent installation is irrelevant).

**Comment by nathanhaigh** [comment]
Thanks @boegel. Turns out that `python-igraph` requires the `igraph` C library to be installed. There is an easyconfig for the latter. Should i create a separate easyconfig "bundle" for `python-igraph` which depends on Python and igraph, then add that as a dependency here?

**Comment by boegel** [comment]
@nathanhaigh either that, or just also include `igraph` as a dependency to Swarm, and include `python-igraph` as an extension

the downside of including `python-igraph` as a dependency here is that you'll end up with another module for `python-igraph`

**Comment by boegel** [comment]
@nathanhaigh Is this still WIP?

**Comment by migueldiascosta** [comment]
@nathanhaigh, this PR is being closed for the following reason(s): no activity for > 6 months.
Please don't hesitate to reopen this PR or add a comment if you feel this contribution is still relevant.
For more information on our policy w.r.t. closing PRs, see https://easybuild.readthedocs.io/en/latest/Contributing.html#why-a-pull-request-may-be-closed-by-a-maintainer

**Pull request closed without merging**
