### PR TITLE
Add config for MDTraj-1.9.7-foss-2021b

### PR DESCRIPTION
**Pull request by jkuhl-uni**

### CODE REVIEW

**Comment by jkuhl-uni** [comment]
Hey @verdurin,
if it is not too much before Christmas, could you also have a look at this PR in order to merge #19428?
Thank you in advance :)

**Comment by casparvl** [comment]
@boegelbot please test @ generoso

**Comment by casparvl** [comment]
@boegelbot please test @ jsc-zen2

**Comment by casparvl** [comment]
@boegelbot please test @ jsc-zen2

**Comment by casparvl** [comment]
Test report by @casparvl
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
tcn1.local.snellius.surf.nl - Linux RHEL 8.6, x86_64, AMD EPYC 7H12 64-Core Processor, Python 3.6.8
See https://gist.github.com/casparvl/f7870ac804ce3ef94431d2d3845d558b for a full test report.

**Comment by casparvl** [comment]
Going in, thanks @jkuhl-uni!

**Pull request merged**
