### PR TITLE
Add ownCloud-2.4.3 and QtKeychain-0.9.1

### PR DESCRIPTION
**Pull request by crubb**
Add [ownCloud](https://github.com/owncloud/client) 2.4.3

> The ownCloud Desktop Client is a tool to synchronize files from ownCloud Server with your computer.

and it's dependency [QtKeychain](https://github.com/frankosterfeld/qtkeychain) 0.9.1

> Platform-independent Qt API for storing passwords securely.

Also update dependencies:

- g/GLib/GLib-2.54.3-foss-2018b-Python-3.6.6.eb
- q/Qt5/Qt5-5.11.1-foss-2018b.eb

### CODE REVIEW

**Comment by crubb** [comment]
@boegel: Could you please clarify this error for me? Thank you!

**Comment by boegel** [comment]
@crubb We have a check in place so that only one dependency variant (equivalent with the dep version in this case) in is used per toolchain generation (`2018b` in this case).

That helps significantly in making sure that modules built with the same toolchain generation can be loaded together, i.e. that no version conflicts occur between dependencies.

So, use the existing `Qt5-5.10.1-foss-2018b.eb` (which is already used as a dependency for `OpenFOAM` built with `foss/2018b`) rather than adding a new easyconfig for `Qt5` `5.11.1`.

Concretely:

* remove the `GLib` & `Qt5` easyconfigs
* change `5.11.1` to `5.10.1` in the others

**Comment by akesandgren** [comment]
Rekicking travis due to changes in EasyBuild testing

**Comment by akesandgren** [comment]
Travis kicked

**Comment by akesandgren** [comment]
Test report by @akesandgren
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in this PR)
b-an03.hpc2n.umu.se - Linux ubuntu 16.04, Intel(R) Xeon(R) CPU E5-2690 v4 @ 2.60GHz, Python 2.7.12
See https://gist.github.com/d4f2e08f4e8ea979c91be291cae1dd35 for a full test report.

**Comment by akesandgren** [comment]
Going in, thanks @crubb!

**Pull request merged**
