### PR TITLE
{chem,phys}[intel-compilers/2023.1.0] ASAP3 v3.13.3, kim-api v2.3.0, openkim-models v20210811

### PR DESCRIPTION
**Pull request by schiotz**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by schiotz** [comment]
This provides ASAP3 for the intel/2023a toolchain.  It also updated the foss version from 3.13.2 to 3.13.3 for consistency, although the only real difference between the two versions is that a dubious C++ construction has been removed.  It caused incorrect optimization with the Intel OneAPI compilers.

Compiler flags have been set for the Intel compiler.  This was necessary to restore the very significant performance gain of using Intel compilers which was present with older compilers (for some applications more than a factor two).

**Review by branfosj — APPROVED** [review]

**Comment by branfosj** [comment]
@boegelbot please test @ generoso

**Comment by branfosj** [comment]
@boegelbot please test @ jsc-zen3

**Comment by branfosj** [comment]
Test report by @branfosj
**SUCCESS**
Build succeeded for 7 out of 7 (4 easyconfigs in total)
bear-pg0105u03a - Linux RHEL 8.6, x86_64, Intel(R) Xeon(R) Platinum 8360Y CPU @ 2.40GHz (icelake), Python 3.6.8
See https://gist.github.com/branfosj/2d72f9fdc7ab319e95367b0592c32aae for a full test report.

**Comment by branfosj** [comment]
Going in, thanks @schiotz!

**Pull request merged**
