### PR TITLE
patch so that MaxBin2 uses the EB provided Perl and not the system Perl

### PR DESCRIPTION
**Pull request by tstrempel**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by tstrempel** [comment]
just changes the shebang from `/usr/bin/perl` to `/usr/bin/env perl`

**Comment by branfosj** [comment]
> just changes the shebang from `/usr/bin/perl` to `/usr/bin/env perl`

We have a function for this:
```python
fix_perl_shebang_for = ['run_MaxBin.pl']
```

**Comment by tstrempel** [comment]
now that is awesome. I will rewrite it then

**Comment by tstrempel** [comment]
done

**Comment by branfosj** [comment]
@boegelbot please test @ generoso

**Comment by branfosj** [comment]
Test report by @branfosj
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
bear-pg0211u08b.bear.cluster - Linux Ubuntu 20.04, x86_64, Intel(R) Xeon(R) Gold 6248 CPU @ 2.50GHz (cascadelake), Python 3.8.5
See https://gist.github.com/0fd513fc6f79e657963fd4ab99e52630 for a full test report.

**Comment by branfosj** [comment]
Test report by @branfosj
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
bear-pg0211u03a.bear.cluster - Linux RHEL 8.3, x86_64, Intel(R) Xeon(R) Gold 6248 CPU @ 2.50GHz (cascadelake), Python 3.6.8
See https://gist.github.com/75294f720890595733da1c4435d4a26e for a full test report.

**Review by branfosj — APPROVED** [review]
lgtm

**Pull request merged**
