### PR TITLE
{cae}[intel/2020b] OpenFOAM v8, ParaView v5.8.1, CGAL v5.2

### PR DESCRIPTION
**Pull request by boegel**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by boegel** [comment]
@boegelbot please test @ generoso

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 3 out of 3 (3 easyconfigs in total)
node3148.skitty.os - Linux centos linux 7.9.2009, x86_64, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz, Python 3.6.8
See https://gist.github.com/d4edbdb4c30c1fbaa6605dab7111d52b for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 3 out of 3 (3 easyconfigs in total)
node3528.doduo.os - Linux RHEL 8.2, x86_64, AMD EPYC 7552 48-Core Processor (zen2), Python 3.6.8
See https://gist.github.com/1a4f7dd6ca7d23bc268cac29a99e4276 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 3 out of 3 (3 easyconfigs in total)
node2634.swalot.os - Linux centos linux 7.9.2009, x86_64, Intel(R) Xeon(R) CPU E5-2660 v3 @ 2.60GHz (haswell), Python 3.6.8
See https://gist.github.com/926522f744c347bd751dac32380d1b29 for a full test report.

**Comment by furstj** [comment]
Test report by @furstj
**FAILED**
Build succeeded for 5 out of 8 (3 easyconfigs in total)
pc-12101-fuji - Linux UNKNOWN UNKNOWN, x86_64, Intel(R) Xeon(R) CPU E3-1241 v3 @ 3.50GHz, Python 3.6.12
See https://gist.github.com/f44c8ebe7189394c643aea8e8cc84af1 for a full test report.

**Comment by furstj** [comment]
Test report by @furstj
**FAILED**
Build succeeded for 21 out of 22 (3 easyconfigs in total)
pc-12101-fuji - Linux UNKNOWN UNKNOWN, x86_64, Intel(R) Xeon(R) CPU E3-1241 v3 @ 3.50GHz, Python 3.6.12
See https://gist.github.com/029849d9dac94c825de84c15e268e977 for a full test report.

**Comment by branfosj** [comment]
Test report by @branfosj
Using easyblocks from PR(s) https://github.com/easybuilders/easybuild-easyblocks/pull/2256
**SUCCESS**
Build succeeded for 3 out of 3 (3 easyconfigs in total)
bear-pg0211u03a.bear.cluster - Linux centos linux 7.8.2003, x86_64, Intel(R) Xeon(R) Gold 6248 CPU @ 2.50GHz (cascadelake), Python 3.6.8
See https://gist.github.com/368ac68c344a0d8582e948c66fed0446 for a full test report.

**Comment by branfosj** [comment]
@boegelbot please test @ generoso

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 3 out of 3 (3 easyconfigs in total)
node2629.swalot.os - Linux centos linux 7.9.2009, x86_64, Intel(R) Xeon(R) CPU E5-2660 v3 @ 2.60GHz (haswell), Python 3.6.8
See https://gist.github.com/b2e5b4e5ca5c6f908a66723dc8ba0bef for a full test report.

**Comment by boegel** [comment]
closing this since `intel/2020b` is deprecated, see https://docs.easybuild.io/policies/toolchains

**Pull request closed without merging**
