### PR TITLE
{tools}[GCC/6.3.0-2.27] Singularity v2.3.1

### PR DESCRIPTION
**Pull request by verdurin**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by shahzebsiddiqui** [comment]
I have also tried to build singularity 2.3.1, I ran into an issue after I installed the package with RPM generated with --package support. I think we need to fix the permission but I am not sure which one. 

Please see https://github.com/shahzebsiddiqui/easybuild-easyconfigs/commit/7752690f83bb5b3507e59588bf40d39ce75192a0#diff-5d9c823638a2dba9552c7de4c67e54fb

The error I am getting is the following.

I think there are few extra checks in sanity_check for libexec/singularity that can be taken in account. I don;t see that in your easyconfig

```
[siddis14@amrndhl1157 ~]$ singularity pull docker://shahzebsiddiqui/easybuild
Initializing Singularity image subsystem
Opening image file: easybuild.img
Creating 1529MiB image
Binding image to loop
ERROR  : The feature you are requesting requires privilege you do not have
ABORT  : Retval = 255
```

**Comment by shahzebsiddiqui** [comment]
Also I would change the github url, you are still pointing to greg repo that doesn't exist anymore. This would fail now.

**Comment by jhein32** [comment]
May I ask why this is stalled?  The problem report referenced above is closed.  

I was about to try a config for the latest 2.4.2 in GCC 6.4.0 (e.g foss/2018a) when I found this one.

**Comment by boegel** [comment]
Since we have an easyconfig merged for `Singularity` 2.4.2 already, I don't think this is relevant anymore...

**Pull request closed without merging**
