### PR TITLE
{lib}[GCCcore/11.3.0] intervaltree v0.1

### PR DESCRIPTION
**Pull request by PetrKralCZ**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by PetrKralCZ** [comment]
Test report by @PetrKralCZ
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
node4002.donphan.os - Linux RHEL 8.6, x86_64, Intel(R) Xeon(R) Gold 6240 CPU @ 2.60GHz, 1 x NVIDIA NVIDIA A2, 530.30.02, Python 3.6.8
See https://gist.github.com/PetrKralCZ/d6b2eac4a229b66152d01cc614da1da4 for a full test report.

**Comment by PetrKralCZ** [comment]
@boegelbot please test @ generoso

**Review by Micket — COMMENTED** [review]
lgtm

**Comment by Micket** [comment]
@boegelbot please test @ jsc-zen2

**Comment by Micket** [comment]
Test report by @Micket
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
vera-c1 - Linux Rocky Linux 8.7, x86_64, Intel Xeon Processor (Skylake), Python 3.6.8
See https://gist.github.com/Micket/613c1f6ffd0cef1ba5f77170febc786f for a full test report.

**Review by Micket — APPROVED** [review]
lgtm again (missed approving)

**Comment by Micket** [comment]
Going in, thanks @PetrKralCZ!

**Pull request merged**
