### PR TITLE
fix remote launch of broker and workers for SCOOP

### PR DESCRIPTION
**Pull request by smoors**
(created using `eb --new-pr`)

this change allows SCOOP to run on multiple nodes

### CODE REVIEW

**Comment by smoors** [comment]
Test report by @smoors
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
node375.hydra.os - Linux centos linux 7.6.1810, Intel(R) Xeon(R) Gold 6148 CPU @ 2.40GHz, Python 2.7.5
See https://gist.github.com/0035e5346aae50bf6060b6e17d63d8ed for a full test report.

**Comment by smoors** [comment]
Test report by @smoors
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
node373.hydra.os - Linux centos linux 7.6.1810, Intel(R) Xeon(R) Gold 6148 CPU @ 2.40GHz, Python 2.7.5
See https://gist.github.com/11c0b878d2c87aae2b7c9f333e62df81 for a full test report.

**Comment by migueldiascosta** [comment]
Test report by @migueldiascosta
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
generoso - Linux centos linux 7.6.1810, Intel(R) Xeon(R) CPU E5-2660 v4 @ 2.00GHz, Python 3.6.8
See https://gist.github.com/2741c315bdca9ca8c36a06b463bd0f07 for a full test report.

**Comment by migueldiascosta** [comment]
Going in, thanks @smoors!

**Pull request merged**
