### PR TITLE
{bio}[GCC/12.2.0] BBMap v39.01

### PR DESCRIPTION
**Pull request by eylenth**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by eylenth** [comment]
Test report by @eylenth
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
by0owl.eu.seeds.basf.net - Linux RHEL 7.9, x86_64, Intel(R) Xeon(R) CPU E5-2620 v4 @ 2.10GHz (broadwell), Python 3.6.8
See https://gist.github.com/eylenth/41eae878b65e75d94e0a1e5b8c72d163 for a full test report.

**Comment by jfgrimm** [comment]
Test report by @jfgrimm
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
himem04.pri.viking.alces.network - Linux CentOS Linux 7.9.2009, x86_64, Intel(R) Xeon(R) Gold 6230 CPU @ 2.10GHz (cascadelake), Python 3.6.8
See https://gist.github.com/jfgrimm/d7aba92d8fb66117d43a99e48029d3a3 for a full test report.

**Review by jfgrimm — APPROVED** [review]
lgtm

**Comment by jfgrimm** [comment]
@boegelbot please test @ generoso

**Comment by jfgrimm** [comment]
@boegelbot please test @ jsc-zen2

**Comment by jfgrimm** [comment]
Going in, thanks @eylenth!

**Pull request merged**
