### PR TITLE
{chem}[foss/2022b,intel/2022b,intel/2022b 64bits] DIRAC v23.0

### PR DESCRIPTION
**Pull request by agustinaucar**
DIRAC code, release 23.0

Both, intel and foss compilations are given. In addition, a 64bits intel compilation is also provided.

### CODE REVIEW

**Comment by agustinaucar** [comment]
@boegelbot please test @ generoso

**Comment by agustinaucar** [comment]
Hi @boegel ! I tried to call your bot to simplify the process of testing this MR. I hope you do not find this intrusive, as now I see that it is an option only available to owners.
Best regards, Agustín

**Comment by smoors** [comment]
@boegelbot: please test @ generoso

**Comment by smoors** [comment]
@boegelbot: please test @ generoso

**Comment by agustinaucar** [comment]
Thank you @smoors ! I would like to ask you for some help, please.

The error found in the compilation procedure is referred to HDF5.

First, I see that HDF5 is correctly detecte:

`-- Found HDF5: /project/boegelbot/Rocky8/haswell/software/HDF5/1.14.0-gompi-2022b/lib/libhdf5.so;/usr/lib64/libpthread.so;/project/boegelbot/Rocky8/haswell/software/Szip/2.1.1-GCCcore-12.2.0/lib/libsz.so;/project/boegelbot/Rocky8/haswell/software/zlib/1.2.12-GCCcore-12.2.0/lib/libz.so;/usr/lib64/libdl.so;/usr/lib64/libm.so;/usr/lib64/libm.so;/usr/lib64/libpthread.so (found version "1.14.0") found components: C HL `

but then this error appears

```
CMake Error in CMakeLists.txt:
  Imported target "HDF5::HDF5" includes non-existent path

    "/tmp/boegelbot/HDF5/1.14.0/gompi-2022b/hdf5-1.14.0/src/H5FDsubfiling"

  in its INTERFACE_INCLUDE_DIRECTORIES.  Possible reasons include:

  * The path was deleted, renamed, or moved to another location.

  * An install or uninstall procedure did not complete successfully.

  * The installation package was faulty and references files it does not
  provide.
```

May I ask you how should I fix it?

Thank you in advance!

**Comment by agustinaucar** [comment]
Probably, in line 119 of [this file](https://gitlab.com/dirac/dirac/-/blob/master/cmake/custom/core.cmake) we should use [according to the [cmake website](https://cmake.org/cmake/help/latest/module/FindHDF5.html)]

`        target_link_libraries(${_executable} hdf5::hdf5)
`

instead of the current

`        target_link_libraries(${_executable} HDF5::HDF5)
`

The previous DIRAC release (22.0) compiles without problems. There we used

`        target_link_libraries(${_executable} ${HDF5_C_LIBRARIES})`


Any clue is very welcome. Thank you!

**Comment by smoors** [comment]
@agustinaucar this is due to a change in HDF5
fix: https://github.com/easybuilders/easybuild-easyconfigs/pull/17469

**Comment by smoors** [comment]
@boegelbot: please test @ generoso EB_ARGS="--from-pr=17469"

**Comment by agustinaucar** [comment]
Great, thanks @smoors !

**Comment by agustinaucar** [comment]
Dear @smoors :  I hope your fix for HDF5 corrects the foss build of DIRAC-23.0.

On the other hand, [MPI seems to be missing from Intel builds](https://gist.github.com/boegelbot/5f4812783b2831fe4b9043ed7538bcc7#file-dirac-23-0-intel-2022b_partial-log-L478). I used the same arguments that I used in the EB build of DIRAC-22.0. Has anything changed in the MPI builds?
```
-- Could NOT find MPI_C (missing: MPI_C_WORKS) 
-- Could NOT find MPI_CXX (missing: MPI_CXX_WORKS) 
-- Found MPI_Fortran: /project/boegelbot/Rocky8/haswell/software/impi/2021.7.1-intel-compilers-2022.2.1/mpi/2021.7.1/bin/mpiifort (found version "3.1") 
-- Could NOT find MPI (missing: MPI_C_FOUND MPI_CXX_FOUND) (found version "3.1")
CMake Error at cmake/downloaded/autocmake_mpi.cmake:43 (message):
  -- You asked for MPI, but CMake could not find any MPI installation, check
  $PATH
Call Stack (most recent call first):
  CMakeLists.txt:83 (include)
```

**Comment by agustinaucar** [comment]
Hi @smoors, I see that the HDF5 issues seem to be solved, then we can test if the foss build runs smoothly now

**Comment by smoors** [comment]
fix for the intel version of HDF5 is here: https://github.com/easybuilders/easybuild-easyconfigs/pull/17488
not sure about your MPI errors though.

**Comment by smoors** [comment]
@boegelbot: please test @ generoso EB_ARGS="--from-pr=17488"

**Comment by smoors** [comment]
@boegelbot please test @ jsc-zen2

**Comment by agustinaucar** [comment]
Thanks a lot, @smoors! The foss build is now Ok. I don't know why MPI is
not found in the Intel compilation, since the *.eb file I created here is
almost the same as that for DIRAC 21.

**Comment by smoors** [comment]
@agustinaucar the problem with the intel versions is that DIRAC uses the compiler flag `-mkl`, but that is not valid in the `intel/2022b` toolchain because there the onapi compilers are used by default, which use `-qmkl`.

you can work around it by using the classic intel compilers like this:
```
toolchainopts = {'usempi': True, 'oneapi': False}
```

```
icx: error: unknown argument '-mkl=sequential'; did you mean '-qmkl=sequential'?
gmake[1]: *** [cmTC_172ad] Error 1
gmake[1]: Leaving directory `/tmp/DIRAC/23.0/intel-2022b/easybuild_obj/CMakeFiles/CMakeScratch/TryCompile-jHM0gt'
gmake: *** [cmTC_172ad/fast] Error 2
```

**Comment by agustinaucar** [comment]
Thank you @smoors !

**Comment by smoors** [comment]
@boegelbot: please test @ generoso

**Comment by smoors** [comment]
@boegelbot please test @ jsc-zen2

**Review by smoors — APPROVED** [review]
lgtm

**Comment by agustinaucar** [comment]
Thank you very much, @smoors !

**Pull request merged**
