### PR TITLE
{vis}[GCCcore/12.2.0] matplotlib v3.7.0, cppy v1.2.1, Tkinter v3.10.8, ... w/ Python 3.10.8

### PR DESCRIPTION
**Pull request by VRehnberg**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by VRehnberg** [comment]
Test report by @VRehnberg
**SUCCESS**
Build succeeded for 4 out of 4 (4 easyconfigs in total)
alvis-c1 - Linux Rocky Linux 8.6, x86_64, Intel Xeon Processor (Skylake), Python 3.6.8
See https://gist.github.com/60c1468925e9487a7d0d8f329837a600 for a full test report.

**Comment by schiotz** [comment]
Test report by @schiotz
**SUCCESS**
Build succeeded for 22 out of 22 (4 easyconfigs in total)
slid.fysik.dtu.dk - Linux CentOS Linux 7.9.2009, x86_64, Intel(R) Xeon(R) CPU E5-2650 v4 @ 2.20GHz, Python 2.7.5
See https://gist.github.com/fe33281c772e836640eee89cd0456573 for a full test report.

**Comment by verdurin** [comment]
Test report by @verdurin
**SUCCESS**
Build succeeded for 5 out of 5 (4 easyconfigs in total)
easybuild-c7.novalocal - Linux CentOS Linux 7.9.2009, x86_64, Intel Xeon Processor (Skylake, IBRS), Python 3.6.8
See https://gist.github.com/568f5198070cfadae2a24b667ad948af for a full test report.

**Comment by verdurin** [comment]
@boegelbot please test @ generoso

**Comment by jfgrimm** [comment]
@boegelbot please test @ jsc-zen2

**Comment by jfgrimm** [comment]
Test report by @jfgrimm
**FAILED**
Build succeeded for 3 out of 4 (4 easyconfigs in total)
node078.pri.viking.alces.network - Linux CentOS Linux 7.9.2009, x86_64, Intel(R) Xeon(R) Gold 6138 CPU @ 2.00GHz (skylake_avx512), Python 3.6.8
See https://gist.github.com/25e9e8174b75304d93ea95642a41ebd5 for a full test report.

**Comment by jfgrimm** [comment]
Test report by @jfgrimm
**SUCCESS**
Build succeeded for 4 out of 4 (4 easyconfigs in total)
node078.pri.viking.alces.network - Linux CentOS Linux 7.9.2009, x86_64, Intel(R) Xeon(R) Gold 6138 CPU @ 2.00GHz (skylake_avx512), Python 3.6.8
See https://gist.github.com/38eaafb2f71fd99c4354d2a1a5c8ac1f for a full test report.

**Review by jfgrimm — APPROVED** [review]
lgtm

**Pull request merged**
