### PR TITLE
R 4.0.3 foss-2020b

### PR DESCRIPTION
**Pull request by fizwit**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by fizwit** [comment]
HWxtest has been removed, it was pulled from CRAN and no longer buildable with GCC 10.2
libgit2 has been added as a dependency from gert. Everything needs git.
easy_update delta from 4.0.2 [gist](https://gist.github.com/fizwit/8f6b45189160de885f0561d87b4f78ee)

Library additions
```                     brio : 1.1.0 from testthat              (add) [768, 141]
                  diffobj : 0.3.2 from waldo                 (add) [768, 143]
                    waldo : 0.2.3 from testthat              (add) [768, 145]
                  conquer : 1.0.2 from quantreg              (add) [768, 165]
                    cpp11 : 0.2.4 from tidyr                 (add) [768, 181]
           operator.tools : 1.6.3 from formula.tools         (add) [768, 205]
            formula.tools : 1.7.1 from logistf               (add) [768, 206]
                 mathjaxr : 1.0-1 from rgl                   (add) [768, 356]
                rbibutils : 2.0 from Rdpack                  (add) [768, 388]
                 gitcreds : 0.1.1 from gh                    (add) [768, 497]
              credentials : 1.3.0 from gert                  (add) [768, 499]
                     gert : 1.0.2 from usethis               (add) [768, 500]
                      rle : 0.9.2 from statnet.common        (add) [768, 538]
                     pamr : 1.56.1 from mpath                (add) [768, 600]
                WeightSVM : 1.7-5 from mpath                 (add) [768, 601]
               parallelly : 1.22.0 from future               (add) [768, 622]
                       V8 : 3.4.0 from rstan                 (add) [768, 780]
```

**Comment by boegel** [comment]
@fizwit There's a lot of changes being made here, including removing a whole bunch of extensions (compared to #11663), which doesn't make much sense to me...

**Comment by fizwit** [comment]
Did not realize that R-4.0.3 was already submitted. I need to search PR's
and not issues. I believe that I am just updating from the previous
version. Which version of R did you start with?  I do not see R-4.0.2 in
the repo. ade4 added one required package which resulted in re-ordering 11
libraries. easy_update re-orders the list based on required packages. I
report 33 new packages but real "net new" is 17 libraries. I think this is
the most new libraries I have seen. But I have not built R since April
2020. (or when R-4.0.2 was released)

testthat : 2.3.2 -> 3.0.1 testthat did a major update which required 5 new
packages.

I supplied a gist with the updates. I also considered patching HWxtest but
once I noticed that it had been removed from CRAN I did not see a reason
for fixing it.

Running easy_update within an 8 hour day will produce two different
versions. Libraries are changing that fast. If I wait at least 2 weeks
after a release I will see changes in almost every library. Updated
Packages: 239


John Dey
john@fuzzdog.com

**Comment by fizwit** [comment]
just starting to look at a diff now, your file is 332 lines longer than my
submission. And I can see that yours has been accepted, bummer. I am 8 days
too late. I'll remove my PR.

John Dey
john@fuzzdog.com

**Pull request closed without merging**
