### PR TITLE
{toolchain} iomkl v2021b

### PR DESCRIPTION
**Pull request by orbsmiv**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by orbsmiv** [comment]
Test report by @orbsmiv
**SUCCESS**
Build succeeded for 4 out of 4 (4 easyconfigs in total)
bear-pg0105u36b.bear.cluster - Linux RHEL 8.6, x86_64, Intel(R) Xeon(R) Platinum 8360Y CPU @ 2.40GHz (icelake), Python 3.6.8
See https://gist.github.com/82ba3105953810921a2b58881e0a89f6 for a full test report.

**Review by boegel — DISMISSED** [review]
@orbsmiv Please include an HPL easyconfig using `iomkl/2021b`, which can serve as a test case for building something with this toolchain.

**Comment by orbsmiv** [comment]
Test report by @orbsmiv
**SUCCESS**
Build succeeded for 5 out of 5 (5 easyconfigs in total)
bear-pg0105u36b.bear.cluster - Linux RHEL 8.6, x86_64, Intel(R) Xeon(R) Platinum 8360Y CPU @ 2.40GHz (icelake), Python 3.6.8
See https://gist.github.com/ad87cd3808bedd08b45d64d82e5a6833 for a full test report.

**Comment by jfgrimm** [comment]
Test report by @jfgrimm
**SUCCESS**
Build succeeded for 5 out of 5 (5 easyconfigs in total)
node087.pri.viking.alces.network - Linux CentOS Linux 7.9.2009, x86_64, Intel(R) Xeon(R) Gold 6138 CPU @ 2.00GHz (skylake_avx512), Python 3.6.8
See https://gist.github.com/b741bd8fd29ca6ebf5e25e1f2d87724b for a full test report.

**Comment by jfgrimm** [comment]
@boegelbot please test @ generoso

**Comment by jfgrimm** [comment]
@boegelbot please test @ jsc-zen2

**Review by jfgrimm — APPROVED** [review]

**Comment by jfgrimm** [comment]
Going in, thanks @orbsmiv!

**Pull request merged**
