### PR TITLE
don't add include/node to $CPATH in nodejs easyconfigs + tweak V8 easyconfigs accordingly

### PR DESCRIPTION
**Pull request by boegel**
Because nodejs installations include OpenSSL header files, which causes trouble (see #11663 + https://github.com/jeroen/openssl/issues/84).

Other easyconfigs that depend on `nodejs` don't need to be fixed because of these changes (I'll confirm that in the test report).

### CODE REVIEW

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 14 out of 14 (14 easyconfigs in total)
node3159.skitty.os - Linux centos linux 7.9.2009, x86_64, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz, Python 3.6.8
See https://gist.github.com/dbce9f81a593cd2cd8f2a2a1ce238582 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 14 out of 14 (14 easyconfigs in total)
node2610.swalot.os - Linux centos linux 7.9.2009, x86_64, Intel(R) Xeon(R) CPU E5-2660 v3 @ 2.60GHz (haswell), Python 3.6.8
See https://gist.github.com/148e1dda2ac8b1de73bd929dc204331c for a full test report.

**Review by Micket — APPROVED** [review]
lgtm

**Comment by Micket** [comment]
Test report by @Micket
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
vera-c1 - Linux centos linux 7.9.2009, x86_64, Intel Xeon Processor (Skylake), Python 2.7.5
See https://gist.github.com/ed31ed111710a92ddfd24623adb0b0a4 for a full test report.

**Comment by lexming** [comment]
Test report by @lexming
**FAILED**
Build succeeded for 8 out of 10 (10 easyconfigs in total)
node379.hydra.os - Linux centos linux 7.9.2009, x86_64, Intel(R) Xeon(R) Gold 6148 CPU @ 2.40GHz, Python 2.7.5
See https://gist.github.com/e163b1dbd47aadb35ac1116d2cadf574 for a full test report.

**Review by lexming — CHANGES_REQUESTED** [review]
My failed test with `V8-3.2.0-foss-2019b-R-3.6.2.eb` is due to yet another checksum change in CRAN

```
checksums = [
    ('f575e07c6fefbc53a96e90bbb41ffdf67794cca797661eb97a6f52348ae20d7c',
     'd2e9b8eb0e9cec76a5c3a8725f7cd50a53ac0d98d0c1ec69d2a943132a2d3eb6'),
]
```

**Comment by lexming** [comment]
Test report by @lexming
**FAILED**
Build succeeded for 0 out of 1 (1 easyconfigs in total)
node379.hydra.os - Linux centos linux 7.9.2009, x86_64, Intel(R) Xeon(R) Gold 6148 CPU @ 2.40GHz, Python 2.7.5
See https://gist.github.com/696d6c37576a375f7e93b9890f50b75e for a full test report.

**Comment by lexming** [comment]
Test report by @lexming
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
node379.hydra.os - Linux centos linux 7.9.2009, x86_64, Intel(R) Xeon(R) Gold 6148 CPU @ 2.40GHz, Python 2.7.5
See https://gist.github.com/26452fbb819f495c9b1a742dd779bff8 for a full test report.

**Comment by boegel** [comment]
@boegelbot please test @ generoso
EB_ARGS="nodejs-10.15.1-foss-2018b.eb nodejs-10.15.3-GCCcore-8.2.0.eb nodejs-12.16.1-GCCcore-7.3.0.eb nodejs-12.16.1-GCCcore-8.3.0.eb nodejs-12.16.1-GCCcore-9.3.0.eb nodejs-12.19.0-GCCcore-10.2.0.eb V8-2.3-foss-2019a-R-3.6.0.eb  V8-3.2.0-foss-2019b-R-3.6.2.eb"
CORE_CNT=16

**Comment by boegel** [comment]
@boegelbot please test @ generoso
EB_ARGS="V8-3.2.0-foss-2019b-R-3.6.2.eb"

**Comment by lexming** [comment]
Test report by @lexming
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
node379.hydra.os - Linux centos linux 7.9.2009, x86_64, Intel(R) Xeon(R) Gold 6148 CPU @ 2.40GHz, Python 2.7.5
See https://gist.github.com/6a7d496ac831d9237ff8ccc796fabc2d for a full test report.

**Review by lexming — APPROVED** [review]
LGTM

**Comment by lexming** [comment]
Going in, thanks @boegel !

**Pull request merged**
