### PR TITLE
{bio}[foss/2016a] GAT v1.2.2

### PR DESCRIPTION
**Pull request by timeu**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by migueldiascosta** [comment]
Test report by @migueldiascosta
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
grc-cluster1 - Linux centos 6.10, Intel(R) Xeon(R) CPU E5-2640 0 @ 2.50GHz, Python 2.7.14
See https://gist.github.com/e1e456194709db51fc01ea4f690cc741 for a full test report.

**Comment by timeu** [comment]
Ping ?

**Comment by migueldiascosta** [comment]
@timeu, this PR is being closed for the following reason(s): closing and reopening to trigger tests.

**Comment by migueldiascosta** [comment]
Going in, thanks @timeu!

**Pull request merged**
