### PR TITLE
{phys}[GCC/11.2.0,intel-compilers/2021.2.0,intel-compilers/2021.4.0] libpspio v0.2.4

### PR DESCRIPTION
**Pull request by micaeljtoliveira**
(created using `eb --new-pr`)

### CODE REVIEW

**Review by boegel — DISMISSED** [review]

**Comment by branfosj** [comment]
@boegelbot please test @ generoso

**Review by branfosj — APPROVED** [review]

**Comment by branfosj** [comment]
Test report by @branfosj
**SUCCESS**
Build succeeded for 5 out of 5 (3 easyconfigs in total)
bear-pg0105u03a.bear.cluster - Linux RHEL 8.6, x86_64, Intel(R) Xeon(R) Platinum 8360Y CPU @ 2.40GHz (icelake), Python 3.6.8
See https://gist.github.com/branfosj/f35d1f50c27e030fe9690048c22ab5b6 for a full test report.

**Comment by branfosj** [comment]
@boegelbot please test @ jsc-zen2

**Comment by branfosj** [comment]
Going in, thanks @micaeljtoliveira!

**Comment by branfosj** [comment]
Going in, thanks @micaeljtoliveira!

**Pull request merged**
