### PR TITLE
{lib}[foss/2021a] dm-haiku v0.0.9 w/ Python 3.9.5

### PR DESCRIPTION
**Pull request by boegel**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by casparvl** [comment]
@boegelbot please test @ generoso

**Comment by casparvl** [comment]
Test report by @casparvl
**SUCCESS**
Build succeeded for 0 out of 0 (1 easyconfigs in total)
tcn331.local.snellius.surf.nl - Linux Rocky Linux 8.7, x86_64, AMD EPYC 7H12 64-Core Processor, Python 3.6.8
See https://gist.github.com/casparvl/6c268dd8686c3e1d080c0ecf54ffe778 for a full test report.

**Comment by casparvl** [comment]
@boegelbot please test @ jsc-zen2

**Comment by casparvl** [comment]
Test report by @casparvl
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
tcn331.local.snellius.surf.nl - Linux Rocky Linux 8.7, x86_64, AMD EPYC 7H12 64-Core Processor, Python 3.6.8
See https://gist.github.com/casparvl/6c36fe977dd0e9132584b67e0ed21546 for a full test report.

**Review by casparvl — APPROVED** [review]
Lgtm! As soon as the test report from `jsc-zen2` comes back succesful, this can be merged imho

**Comment by casparvl** [comment]
@boegel ok, what now... it fails on Jax, not your `dm-haiku`. Still, unfortunate though. How about this: you make a ticket out of it for the Jax failure, and I will accept merging this PR, since dm-haiku itself seems fine? :)

**Comment by boegel** [comment]
> @boegel ok, what now... it fails on Jax, not your `dm-haiku`. Still, unfortunate though. How about this: you make a ticket out of it for the Jax failure, and I will accept merging this PR, since dm-haiku itself seems fine? :)

@casparvl issue opened at #18078

**Review by casparvl — APPROVED** [review]
Lgtm!

**Comment by casparvl** [comment]
Going in, thanks @boegel!

**Pull request merged**
