### PR TITLE
add alternative source_url for MariaDB > 10.4

### PR DESCRIPTION
**Pull request by branfosj**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by branfosj** [comment]
@boegelbot please test @ generoso
EB_ARGS="--sourcepath /tmp/$USER/pr17250 --force-download --stop source"

**Review by smoors — APPROVED** [review]
lgtm

**Comment by smoors** [comment]
Going in, thanks @branfosj!

**Comment by smoors** [comment]
@boegelbot please test @ jsc-zen2

**Pull request merged**
