### PR TITLE
include required stereo_chemical_props.txt for OpenFold 1.0.1

### PR DESCRIPTION
**Pull request by boegel**
(created using `eb --new-pr`)

follow-up for #17206

### CODE REVIEW

**Review by smoors — APPROVED** [review]
lgtm

**Comment by smoors** [comment]
Test report by @smoors
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
node400.hydra.os - Linux CentOS Linux 7.9.2009, x86_64, AMD EPYC 7282 16-Core Processor, 1 x NVIDIA NVIDIA A100-PCIE-40GB, 515.48.07, Python 3.6.8
See https://gist.github.com/ccadd2d310043e615dc78e35eb3e727e for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
node3300.joltik.os - Linux RHEL 8.6, x86_64, Intel(R) Xeon(R) Gold 6242 CPU @ 2.80GHz (cascadelake), 1 x NVIDIA Tesla V100-SXM2-32GB, 525.60.13, Python 3.6.8
See https://gist.github.com/3d37a513b5249a35d9853f3ab1bf3b5e for a full test report.

**Comment by smoors** [comment]
Going in, thanks @boegel!

**Pull request merged**
