### PR TITLE
{math}[foss/2022a] gap v4.12.2

### PR DESCRIPTION
**Pull request by migueldiascosta**
(created using `eb --new-pr`)

requires:
- [x] #19192
- [x] #19193
- [x] #19196
- [x] #19199
- [x] #19206

### CODE REVIEW

**Comment by migueldiascosta** [comment]
@boegelbot please test @ generoso

**Comment by migueldiascosta** [comment]
@boegelbot please test @ jsc-zen2

**Comment by migueldiascosta** [comment]
@boegelbot please test @ jsc-zen2 CORE_CNT=16

**Comment by jfgrimm** [comment]
Test report by @jfgrimm
**SUCCESS**
Build succeeded for 4 out of 4 (1 easyconfigs in total)
node041.viking2.yor.alces.network - Linux Rocky Linux 8.8, x86_64, AMD EPYC 7643 48-Core Processor, Python 3.6.8
See https://gist.github.com/jfgrimm/49966837c66f69d8b3db5cee2e64b805 for a full test report.

**Review by jfgrimm — APPROVED** [review]
lgtm

**Pull request merged**
