### PR TITLE
{math}[foss/2022a,GCCcore/11.3.0] sagemath v10.1 and dependencies

### PR DESCRIPTION
**Pull request by migueldiascosta**
(created using `eb --new-pr`)

requires:
- [x] #19198
- [x] #19202
- [x] #19207
- [x] #19208
- [x] #19209
- [x] #19210 
- [x] #19211
- [x] #19323
- [x] #19328
- [x] #19329
- [x] #19349 
- [x] #19370
- [x] #19371

This installation method for `sagemath` is based on https://github.com/sagemath/sage#alternative-installation-using-pypi, but providing the mandatory dependencies via eb instead of downloading and building all the dependencies via `sage_conf` (which of course turned out to be a rabbit hole...)

For those with an itch to scratch, an easyconfig which lets `sage_conf` download and build all the deps is in #19213

### CODE REVIEW

**Comment by migueldiascosta** [comment]
@boegelbot please test @ generoso

**Comment by jfgrimm** [comment]
Test report by @jfgrimm
**FAILED**
Build succeeded for 13 out of 14 (6 easyconfigs in total)
node040.viking2.yor.alces.network - Linux Rocky Linux 8.8, x86_64, AMD EPYC 7643 48-Core Processor, Python 3.6.8
See https://gist.github.com/jfgrimm/308548204c1f478961198c34a705d3c4 for a full test report.

**Comment by migueldiascosta** [comment]
@jfgrimm I think that particular failure is because the `lcalc` dependency is missing from the `sagemath` easyconfig in this PR, I'll add it, but even then this is still a draft, not quite ready yet

I could flesh out a few more easyconfigs (e.g. `libbraiding`, `libhomfly`, `planarity` and `rankwidth`) into separate PRs though, if you're willing to review them separately, to simplify reviewing this PR later

**Comment by migueldiascosta** [comment]
Test report by @migueldiascosta
**FAILED**
Build succeeded for 9 out of 10 (10 easyconfigs in total)
sms - Linux CentOS Linux 7.6.1810, x86_64, AMD EPYC 7601 32-Core Processor, Python 3.6.8
See https://gist.github.com/migueldiascosta/d7d852b86a7b7ef5a6342c15507a2575 for a full test report.

**Comment by migueldiascosta** [comment]
`sanity check command python -c 'from sage.all import *' exited with code -11`

this works for https://github.com/easybuilders/easybuild-easyconfigs/pull/19213 though, so something here is still not right

**Comment by boegel** [comment]
@boegelbot please test @ generoso

**Comment by boegel** [comment]
Just so you know: @PetrKralCZ is making a big effort on SageMath with `foss/2023b` currently, and he's getting close it seems, see https://github.com/vscentrum/vsc-software-stack/issues/253 + https://github.com/vscentrum/vsc-software-stack/tree/wip/253_Sagemath_plantri. PR coming soon, hopefully...

**Comment by boegel** [comment]
@migueldiascosta Can be closed imho, superseded by:
* #21365

**Pull request closed without merging**
