### PR TITLE
{tools,vis}[fosscuda/2020b] Horovod v0.22.0, torchvision v0.9.1 w/ Python 3.8.6

### PR DESCRIPTION
**Pull request by Flamefire**
(created using `eb --new-pr`)

### CODE REVIEW

**Review by Micket — APPROVED** [review]
lgtm

**Comment by Micket** [comment]
Test report by @Micket
**FAILED**
Build succeeded for 0 out of 2 (2 easyconfigs in total)
alvis-c1 - Linux centos linux 7.9.2009, x86_64, Intel Xeon Processor (Skylake), Python 3.6.8
See https://gist.github.com/d7c7cfb473bb5bbd3a15ab35c79d220e for a full test report.

**Comment by Micket** [comment]
Test report by @Micket
**FAILED**
Build succeeded for 2 out of 5 (2 easyconfigs in total)
alvis-c1 - Linux centos linux 7.9.2009, x86_64, Intel Xeon Processor (Skylake), Python 3.6.8
See https://gist.github.com/dca9288e69c4b7d65b4a65564347c16a for a full test report.

**Comment by Flamefire** [comment]
@Micket Your PyTorch install failed. Did you use the latest ECs? And maybe you still need a GPU node although the PT tests should catch that.
>           _set_and_start_rpc_agent(agent)
> E           RuntimeError: In create at ../third_party/tensorpipe/tensorpipe/common/cuda_lib.h:105 "lib.init(0)(1

**Comment by Flamefire** [comment]
Test report by @Flamefire
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in total)
taurusi8022 - Linux centos linux 7.9.2009, x86_64, AMD EPYC 7352 24-Core Processor (zen2), Python 2.7.5
See https://gist.github.com/5f289ad2552221a1122bbc042dffa6c3 for a full test report.

**Comment by branfosj** [comment]
Test report by @branfosj
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in total)
bask-pg0309u35a - Linux RHEL 8.4, x86_64, Intel(R) Xeon(R) Platinum 8360Y CPU @ 2.40GHz (icelake), Python 3.6.8
See https://gist.github.com/50212f54e15bf45ae9096f585ee17b31 for a full test report.

**Comment by verdurin** [comment]
Going in, thanks @Flamefire!

**Pull request merged**
