### PR TITLE
{math}[foss/2021b,intel/2021b] statsmodels v0.13.1 w/ Python 3.9.6

### PR DESCRIPTION
**Pull request by boegel**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by boegel** [comment]
@boegelbot please test @ generoso

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in total)
node3605.doduo.os - Linux RHEL 8.2, x86_64, AMD EPYC 7552 48-Core Processor (zen2), Python 3.6.8
See https://gist.github.com/c11102033f824c3a1a95c282de38679e for a full test report.

**Review by hajgato — APPROVED** [review]

**Comment by hajgato** [comment]
Test report by @hajgato
**SUCCESS**
Build succeeded for 0 out of 0 (2 easyconfigs in total)
node3402.kirlia.os - Linux centos linux 7.9.2009, x86_64, Intel(R) Xeon(R) Gold 6240 CPU @ 2.60GHz, Python 3.6.8
See https://gist.github.com/091655e92248e68bf51aeab60c73407f for a full test report.

**Comment by hajgato** [comment]
Test report by @hajgato
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in total)
node3402.kirlia.os - Linux centos linux 7.9.2009, x86_64, Intel(R) Xeon(R) Gold 6240 CPU @ 2.60GHz, Python 3.6.8
See https://gist.github.com/212118cc6d55b26649ba26d2c1a1d730 for a full test report.

**Comment by hajgato** [comment]
Going in, thanks @boegel!

**Pull request merged**
