### PR TITLE
{bio}[intel/2018a] poretools v0.6.0, Seaborn v0.8.1 w/ Python 2.7.14

### PR DESCRIPTION
**Pull request by boegel**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in this PR)
node2490.golett.os - Linux centos linux 7.4.1708, Intel(R) Xeon(R) CPU E5-2680 v3 @ 2.50GHz, Python 2.7.5
See https://gist.github.com/4d3f1fbd3182d6fe0c8fd976e578d426 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in this PR)
gligar01.gligar.os - Linux centos linux 7.4.1708, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.7.5
See https://gist.github.com/4f2756b87c930bcb05620717c1e1ea5e for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in this PR)
node3100.skitty.os - Linux centos linux 7.4.1708, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz, Python 2.7.5
See https://gist.github.com/2ac6b86cff033d4cc9ab80f0d7ea99b4 for a full test report.

**Comment by verdurin** [comment]
Test report by @verdurin
**FAILED**
Build succeeded for 0 out of 4 (2 easyconfigs in this PR)
rescomp2 - Linux centos 6.8, Intel(R) Xeon(R) CPU E5-2650 v2 @ 2.60GHz, Python 2.7.14
See https://gist.github.com/b686bb13ec580d15846d7a65a1b54dac for a full test report.

**Comment by verdurin** [comment]
Test build error:
```
== 2018-06-18 19:49:41,293 build_log.py:158 ERROR EasyBuild crashed with an error (at ?:124 in __init__): Sanity check failed: sanity check command python -c 'import Tkinter' exited with code 1 (output: Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/well/rescomp/eb/software/Python/2.7.14-intel-2018a/lib/python2.7/lib-tk/Tkinter.py", line 39, in <module>
    import _tkinter # If this fails your Python may not be configured for Tk
ImportError: /well/rescomp/eb/software/Tkinter/2.7.14-intel-2018a-Python-2.7.14/lib/python2.7/_tkinter.so: undefined symbol: PyUnicodeUCS4_DecodeUTF8
) (at easybuild/framework/easyblock.py:2290 in _sanity_check_step)
```

**Comment by boegel** [comment]
@verdurin Same issue as with https://github.com/easybuilders/easybuild-easyconfigs/pull/6439#issuecomment-396142663, we should dive in and figure out what's going on there...

**Comment by verdurin** [comment]
Test report by @verdurin
**SUCCESS**
Build succeeded for 4 out of 4 (2 easyconfigs in this PR)
rescomp2 - Linux centos 6.8, Intel(R) Xeon(R) CPU E5-2650 v2 @ 2.60GHz, Python 2.7.10
See https://gist.github.com/05fe210036cec30fa99fe6933023e568 for a full test report.

**Comment by verdurin** [comment]
The build failures were the result of some irrelevant local weirdness.

**Comment by verdurin** [comment]
Going in, thanks @boegel!

**Pull request merged**
