### PR TITLE
{bio}[foss/2023a] CellOracle v0.18.0, velocyto v0.17.17, genomepy v0.16.1, ...

### PR DESCRIPTION
**Pull request by pavelToman**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by pavelToman** [comment]
@boegelbot please test @ generoso

**Comment by pavelToman** [comment]
@boegelbot please test @ jsc-zen3

**Review by verdurin — APPROVED** [review]
Looks fine.

**Comment by verdurin** [comment]
Going in, thanks @pavelToman!

**Pull request merged**
