### PR TITLE
{tools}[GCC/10.3.0] AutoDock v4.2.6

### PR DESCRIPTION
**Pull request by lexming**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by lexming** [comment]
Test report by @lexming
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
node309.hydra.os - Linux centos linux 7.9.2009, x86_64, Intel(R) Xeon(R) Gold 6148 CPU @ 2.40GHz, Python 2.7.5
See https://gist.github.com/728c4caacd398d4a6a030a586a35a6be for a full test report.

**Comment by branfosj** [comment]
Test report by @branfosj
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
bear-pg0211u03a.bear.cluster - Linux RHEL 8.5, x86_64, Intel(R) Xeon(R) Gold 6248 CPU @ 2.50GHz (cascadelake), Python 3.6.8
See https://gist.github.com/51f2651a6d0c57e927082ddc2af62ff4 for a full test report.

**Comment by branfosj** [comment]
@boegelbot please test @ generoso

**Comment by branfosj** [comment]
Test report by @branfosj
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
bear-pg0211u12b.bear.cluster - Linux Ubuntu 20.04, x86_64, Intel(R) Xeon(R) Gold 6248 CPU @ 2.50GHz (cascadelake), Python 3.8.5
See https://gist.github.com/749dcde51297c0bb2a053c500ba59f62 for a full test report.

**Comment by branfosj** [comment]
```
== 2022-01-05 18:10:36,749 filetools.py:838 WARNING IOError occurred while trying to download https://autodock.scripps.edu/wp-content/uploads/sites/56/2021/10/autodocksuite-4.2.6-src.tar.gz to /project/boegelbot/sources/a/AutoDock/autodocksuite-4.2.6-src.tar.gz: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:897)>
== 2022-01-05 18:10:36,751 filetools.py:847 INFO Attempt 1 of downloading https://autodock.scripps.edu/wp-content/uploads/sites/56/2021/10/autodocksuite-4.2.6-src.tar.gz to /project/boegelbot/sources/a/AutoDock/autodocksuite-4.2.6-src.tar.gz failed, trying again...
== 2022-01-05 18:10:37,066 filetools.py:838 WARNING IOError occurred while trying to download https://autodock.scripps.edu/wp-content/uploads/sites/56/2021/10/autodocksuite-4.2.6-src.tar.gz to /project/boegelbot/sources/a/AutoDock/autodocksuite-4.2.6-src.tar.gz: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:897)>
== 2022-01-05 18:10:37,067 filetools.py:847 INFO Attempt 2 of downloading https://autodock.scripps.edu/wp-content/uploads/sites/56/2021/10/autodocksuite-4.2.6-src.tar.gz to /project/boegelbot/sources/a/AutoDock/autodocksuite-4.2.6-src.tar.gz failed, trying again...
== 2022-01-05 18:10:37,379 filetools.py:838 WARNING IOError occurred while trying to download https://autodock.scripps.edu/wp-content/uploads/sites/56/2021/10/autodocksuite-4.2.6-src.tar.gz to /project/boegelbot/sources/a/AutoDock/autodocksuite-4.2.6-src.tar.gz: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:897)>
== 2022-01-05 18:10:37,381 filetools.py:859 WARNING Download of https://autodock.scripps.edu/wp-content/uploads/sites/56/2021/10/autodocksuite-4.2.6-src.tar.gz to /project/boegelbot/sources/a/AutoDock/autodocksuite-4.2.6-src.tar.gz failed, done trying
```

That download is also failing for me when I run inside EB (`.eb --fetch --force-download --sourcepath /tmp/sjb --from-pr 14661`) My successful build reports were using an existing download.

**Comment by lexming** [comment]
@branfosj it's a certificate issue with their download server, nothing we can do about it. Try with `eb --insecure-download`

**Comment by branfosj** [comment]
@boegelbot please test @ generoso
EB_ARGS="--insecure-download"

**Comment by branfosj** [comment]
> @branfosj it's a certificate issue with their download server, nothing we can do about it. Try with `eb --insecure-download`

OK.

**Review by branfosj — APPROVED** [review]
lgtm

**Comment by branfosj** [comment]
Going in, thanks @lexming!

**Pull request merged**
