### PR TITLE
{chem}[foss/2016b] Amber v16

### PR DESCRIPTION
**Pull request by SethosII**
This is my attempt for Amber built with the `foss` toolchain.

It's currenty not working and crashes with `/easybuild/test/software/binutils/2.26-GCCcore-5.4.0/bin/ld.gold: error: cannot find -lmpi` which is rather strange? I can provide the full log if needed. Any tips or hints are highly appreciated.

### CODE REVIEW

**Comment by vanzod** [comment]
@SethosII I stumbled across the same problem when building it with `fosscuda`. It is related to the fact that the `amber` easyblock injects `-static` in the configure options. Since `OpenMPI` does not have static libraries, it fails. I opened an issue on this to get feedback from users/developers about removing it. See https://github.com/easybuilders/easybuild-easyblocks/issues/1461

**Comment by SethosII** [comment]
@vanzod Thank you for the information. I build it successfully after removing `-static` from the easyblock. I removed `-static-intel` from the patch because this is the [default for the intel compiler](https://software.intel.com/en-us/cpp-compiler-18.0-developer-guide-and-reference-static-intel) and only valid for it. The URLs for the patches description have changed from http://ambermd.org/bugfixes16.html and http://ambermd.org/bugfixesat.html to http://ambermd.org/ATPatches.php and http://ambermd.org/AmberPatches.php. Should I update this in the existing easyconfigs?

**Comment by migueldiascosta** [comment]
@SethosII the Amber easyblock now allows disabling static linking from the easyconfig (see https://github.com/easybuilders/easybuild-easyblocks/issues/1461 and https://github.com/easybuilders/easybuild-easyblocks/issues/1468) 

Also, #6618, for the intel toolchain, includes additional patches that should also be relevant for `foss`. I suppose it would make more sense to work on a `foss` easyconfig on top of it? (adding `cuda` and changing patchlevels seems trivial)

**Comment by akesandgren** [comment]
And I will be doing foss and fosscuda/intelcuda builds once #6618 is merged.

**Comment by SethosII** [comment]
Ok, so I guess we can close this one. I looked into @akesandgren's pull request and it seems much more elaborate than this.

**Pull request closed without merging**
