### PR TITLE
{data}[gfbf/2023a] sktime v0.25.0

### PR DESCRIPTION
**Pull request by garadar**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by garadar** [comment]
@boegelbot please test @ generoso

**Comment by bedroge** [comment]
@boegelbot please test @ jsc-zen3

**Comment by bedroge** [comment]
Test report by @bedroge
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
interactive1 - Linux Rocky Linux 8.9, x86_64, AMD EPYC-Milan Processor (zen2), Python 3.6.8
See https://gist.github.com/bedroge/d1c863780f12957dc556ea2720399a08 for a full test report.

**Review by bedroge — APPROVED** [review]
Looks good to me.

**Pull request merged**
