### PR TITLE
use orca easyblock in easyconfigs of ORCA v4.x

### PR DESCRIPTION
**Pull request by lexming**
(created using `eb --new-pr`)

~~Depends on https://github.com/easybuilders/easybuild-easyblocks/pull/2504~~

### CODE REVIEW

**Comment by lexming** [comment]
Test report by @lexming
Using easyblocks from PR(s) https://github.com/easybuilders/easybuild-easyblocks/pull/2504
**SUCCESS**
Build succeeded for 5 out of 5 (5 easyconfigs in total)
node373.hydra.os - Linux centos linux 7.9.2009, x86_64, Intel(R) Xeon(R) Gold 6148 CPU @ 2.40GHz, Python 2.7.5
See https://gist.github.com/11d6e932f5dd574c9d3afcea68e6e4f8 for a full test report.

**Comment by lexming** [comment]
Test report by @lexming
Using easyblocks from PR(s) https://github.com/easybuilders/easybuild-easyblocks/pull/2504
**SUCCESS**
Build succeeded for 5 out of 5 (5 easyconfigs in total)
node365.hydra.os - Linux centos linux 7.9.2009, x86_64, Intel(R) Xeon(R) Gold 6148 CPU @ 2.40GHz, Python 2.7.5
See https://gist.github.com/c0a98a2bf740f28eb132b505e7e79670 for a full test report.

**Comment by lexming** [comment]
Test report by @lexming
**SUCCESS**
Build succeeded for 5 out of 5 (5 easyconfigs in total)
node371.hydra.os - Linux centos linux 7.9.2009, x86_64, Intel(R) Xeon(R) Gold 6148 CPU @ 2.40GHz, Python 2.7.5
See https://gist.github.com/8d5e91d142da70d84bbad09c30af0526 for a full test report.

**Review by branfosj — APPROVED** [review]
lgtm

**Comment by branfosj** [comment]
Test report by @branfosj
**SUCCESS**
Build succeeded for 3 out of 3 (3 easyconfigs in total)
bear-pg0211u03a.bear.cluster - Linux RHEL 8.3, x86_64, Intel(R) Xeon(R) Gold 6248 CPU @ 2.50GHz (cascadelake), Python 3.6.8
See https://gist.github.com/9d80c81aeed9aedb5f6352b76b65bea1 for a full test report.

**Comment by branfosj** [comment]
Going in, thanks @lexming!

**Pull request merged**
