### PR TITLE
HDF5 1.12.2 with nvompi

### PR DESCRIPTION
**Pull request by hattom**
Comments welcome regarding keeping keeping only 1 of the 2 versions or also making a `-serial` version.

### CODE REVIEW

**Comment by jfgrimm** [comment]
Test report by @jfgrimm
**FAILED**
Build succeeded for 1 out of 6 (2 easyconfigs in total)
node087.pri.viking.alces.network - Linux CentOS Linux 7.9.2009, x86_64, Intel(R) Xeon(R) Gold 6138 CPU @ 2.00GHz (skylake_avx512), Python 3.6.8
See https://gist.github.com/c0ece097756c157488a7514cadc11398 for a full test report.

**Comment by jfgrimm** [comment]
Test report by @jfgrimm
**SUCCESS**
Build succeeded for 5 out of 5 (2 easyconfigs in total)
node087.pri.viking.alces.network - Linux CentOS Linux 7.9.2009, x86_64, Intel(R) Xeon(R) Gold 6138 CPU @ 2.00GHz (skylake_avx512), Python 3.6.8
See https://gist.github.com/0f12ea71ac9151d113b2e4bb7b46c5e0 for a full test report.

**Comment by hattom** [comment]
Line length check fails, but I copied the recipe from gompi. Should I fix or keep consistent with the gompi one?

**Comment by jfgrimm** [comment]
> Line length check fails, but I copied the recipe from gompi. Should I fix or keep consistent with the gompi one?

it looks like you templating for `%(name)s` and `%(namelower)s` which is what took it over the line length limit? In any case, it should be fixed so that the CI passes

**Comment by hattom** [comment]
Will fix. I think I did it all with --copy-ec and --try-toolchain, so I don't know if that changed the name or if I just misremember what I did.

**Comment by Micket** [comment]
I.M.H.O. having multiple options for a dependency is in general, just bad. It creates so many headaches that we just keep hitting over and over. I would prefer if only one version exists per toolchain unless it's really really REALLY really necessary to introduce another.

**Comment by hattom** [comment]
I understand. I would say that 1.12 makes sense.
But since we now start to see PRs open up for 1.14 with other compiler toolchains, I included it as well, but I can throw it out.

A counterpoint is that there are API changes introduced, and being tied to a particular version downstream because of the choice of library for a given toolchain is also, IMHO, really annoying.

**Comment by jfgrimm** [comment]
> EDIT: it looks like the 1.14 PR was for a newer GCC version. So maybe we do this for nvompi at the next toolchain update?

that would be preferable. We generally try to avoid multiple software versions in the same toolchain (particular ones used as dependencies elsewhere), since it results in incompatible modules within the same toolchain.

**Comment by Micket** [comment]
Yes just keeping this aligned with what the other toolchains with the same GCCcore does is the best way.

> A counterpoint is that there are API changes introduced, and being tied to a particular version downstream because of the choice of library for a given toolchain is also, IMHO, really annoying.

But do this for LLVM, HDF5, Java, and some other library and you have  2^4 different mutually incompatible branches of easyconfigs within the same toolchain.

**Comment by hattom** [comment]
Done.

**Comment by jfgrimm** [comment]
@boegelbot please test @ generoso

**Comment by jfgrimm** [comment]
@boegelbot please test @ jsc-zen2

**Comment by hattom** [comment]
I have also made a `-serial` with `NVHPC-22.7-CUDA-11.7.0`. Should I add to this PR?

**Comment by Micket** [comment]
Test report by @Micket
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in total)
alvis-c1 - Linux Rocky Linux 8.6, x86_64, Intel Xeon Processor (Skylake), Python 3.6.8
See https://gist.github.com/Micket/88a6db100f9279af56f59a6573510d4e for a full test report.

**Comment by Micket** [comment]
Test report by @Micket
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in total)
alvis-s1 - Linux Rocky Linux 8.6, x86_64, Intel(R) Xeon(R) Silver 4314 CPU @ 2.40GHz, Python 3.6.8
See https://gist.github.com/Micket/94dbd2d4a2e13d81c8fd8d1cea37409e for a full test report.

**Comment by Micket** [comment]
Going in, thanks @hattom!

**Pull request merged**
