### PR TITLE
{perf}[GCCcore/7.3.0,GCCcore/8.2.0] STREAM v5.10

### PR DESCRIPTION
**Pull request by jose-d**
(created using `eb --new-pr`)

it's nice to have _non-intel_ stream.

### CODE REVIEW

**Comment by jose-d** [comment]
Test report by @jose-d
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in this PR)
koios1 - Linux centos linux 7.6.1810, Intel(R) Xeon(R) Gold 6130 CPU @ 2.10GHz, Python 2.7.5
See https://gist.github.com/60f1198efd885ba98a0036e199e5509a for a full test report.

**Comment by boegel** [comment]
@jose-d It's better to remove the easyconfigs still using `GCCcore`?

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in this PR)
node3110.skitty.os - Linux centos linux 7.6.1810, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz, Python 2.7.5
See https://gist.github.com/004b18cf1a5946532092cd1b038e0108 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in this PR)
node2400.golett.os - Linux centos linux 7.6.1810, Intel(R) Xeon(R) CPU E5-2680 v3 @ 2.50GHz, Python 2.7.5
See https://gist.github.com/df37e65f7066ede48e410bee33a8b5c7 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in this PR)
node2082.delcatty.os - Linux centos linux 7.6.1810, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.7.5
See https://gist.github.com/82ccd85cadcef3cfae68d77b66efaca0 for a full test report.

**Comment by boegel** [comment]
Going in, thanks @jose-d!

**Pull request merged**
