### PR TITLE
{numlib}[foss/2019a,intel/2019a] PETSc v3.11.1

### PR DESCRIPTION
**Pull request by Micket**
(created using `eb --new-pr`)

Depends on #8204 #8205

### CODE REVIEW

**Comment by Micket** [comment]
travis kicking time

**Comment by Micket** [comment]
and go

**Comment by vanzod** [comment]
Test report by @vanzod
**SUCCESS**
Build succeeded for 13 out of 13 (2 easyconfigs in this PR)
cermis - Linux debian 9.9, Intel(R) Xeon(R) CPU           X5670  @ 2.93GHz, Python 2.7.13
See https://gist.github.com/1116470ca1cb144ecce0af8ed6beacd9 for a full test report.

**Comment by vanzod** [comment]
Going in, thanks @Micket!

**Pull request merged**
