### PR TITLE
{perf}[foss/2020b] MUST v1.7.1 w/ Python 3.8.6

### PR DESCRIPTION
**Pull request by DirectorSloan**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by DirectorSloan** [comment]
Can this go into develop or can I do anything to improve?

**Review by boegel — APPROVED** [review]
lgtm

**Comment by boegel** [comment]
@boegelbot please test @ generoso

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 2 out of 2 (1 easyconfigs in total)
node3160.skitty.os - Linux RHEL 8.6, x86_64, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz (skylake_avx512), Python 3.6.8
See https://gist.github.com/boegel/6d371efcba98cb5439a709f4960196ce for a full test report.

**Comment by boegel** [comment]
Going in, thanks @DirectorSloan!

**Pull request merged**
