### PR TITLE
avoid 0.0.0 install version for various Python apps

### PR DESCRIPTION
**Pull request by boegel**
(created using `eb --new-pr`)

required because of https://github.com/easybuilders/easybuild-easyblocks/pull/2367

### CODE REVIEW

**Comment by boegel** [comment]
@boegelbot please test @ generoso

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 8 out of 8 (8 easyconfigs in total)
node3107.skitty.os - Linux centos linux 7.9.2009, x86_64, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz, Python 3.6.8
See https://gist.github.com/afd01f5323fc9ca1e16698db349e5023 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 8 out of 8 (8 easyconfigs in total)
node3131.skitty.os - Linux centos linux 7.9.2009, x86_64, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz, Python 3.6.8
See https://gist.github.com/6bc0e5b089006259866b73d782ddc44c for a full test report.

**Review by akesandgren — APPROVED** [review]
LGTM

**Comment by akesandgren** [comment]
Going in, thanks @boegel!

**Comment by Flamefire** [comment]
Just FTR: This could have also been fixed by using the WHL files instead (which is one of the reasons I wanted to enhance support for those)

**Pull request merged**
