### PR TITLE
{lib}[GCCcore/13.2.0,GCCcore/13.3.0] alsa-lib v1.2.11

### PR DESCRIPTION
**Pull request by Micket**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by Micket** [comment]
@boegelbot please test @ generoso

**Comment by Micket** [comment]
@boegelbot please test @ jsc-zen3

**Comment by SebastianAchilles** [comment]
Test report by @sebastianachilles
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in total)
bwd-rockylinux-94 - Linux Rocky Linux 9.4 (Blue Onyx), x86_64, Intel(R) Core(TM) i7-6900K CPU @ 3.20GHz (broadwell), Python 3.9.18
See https://gist.github.com/SebastianAchilles/d6d20aabfa65e9d74343125d4d5dd5e6 for a full test report.

**Comment by SebastianAchilles** [comment]
I think it makes sense to close this PR in favor of https://github.com/easybuilders/easybuild-easyconfigs/pull/21119 which builds static and shared libraries for `alsa-lib`.

**Pull request closed without merging**
