### PR TITLE
{devel,tools}[GCCcore/11.3.0] Bazel v5.1.1, Zip v3.0

### PR DESCRIPTION
**Pull request by jfgrimm**
Tried using `Java 17` (latest LTS), but `Bazel` crashes during the build. Settled for `Java 13`, but happy to drop to `11` if preferred

(created using `eb --new-pr`)

### CODE REVIEW

**Comment by jfgrimm** [comment]
@boegelbot please test @ generoso

**Comment by jfgrimm** [comment]
Test report by @jfgrimm
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in total)
himem03.pri.viking.alces.network - Linux CentOS Linux 7.9.2009, x86_64, Intel(R) Xeon(R) Gold 6130 CPU @ 2.10GHz (skylake_avx512), Python 3.6.8
See https://gist.github.com/8a4e107368b9f044d8ce05931b350caf for a full test report.

**Comment by jfgrimm** [comment]
@boegelbot please test @ jsc-zen2

**Comment by branfosj** [comment]
Test report by @branfosj
**FAILED**
Build succeeded for 3 out of 4 (2 easyconfigs in total)
bear-pg0305u15a.bear.cluster - Linux RHEL 8.5, POWER, 8335-GTX (power9le), 4 x NVIDIA Tesla V100-SXM2-16GB, 470.57.02, Python 3.6.8
See https://gist.github.com/c75fffae9189823bf9a2aaccd92fddf3 for a full test report.

**Review by branfosj — APPROVED** [review]
lgtm

As Bazel is usually a build dependency I am happy to go with Java 13. Doing so does not fix us to that Java version in the same way it would if this was usually used as a dependency.

**Comment by branfosj** [comment]
Test report by @branfosj
**SUCCESS**
Build succeeded for 4 out of 4 (2 easyconfigs in total)
bear-pg0105u36b.bear.cluster - Linux RHEL 8.6, x86_64, Intel(R) Xeon(R) Platinum 8360Y CPU @ 2.40GHz (icelake), Python 3.6.8
See https://gist.github.com/e3bb9c5a357d32975562dcdab5680d47 for a full test report.

**Comment by branfosj** [comment]
Test report by @branfosj
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in total)
bear-pg0211u08b.bear.cluster - Linux Ubuntu 20.04, x86_64, Intel(R) Xeon(R) Gold 6248 CPU @ 2.50GHz (cascadelake), Python 3.8.5
See https://gist.github.com/fc226ddd1c5655d64dc0fff8b376257e for a full test report.

**Comment by branfosj** [comment]
Test report by @branfosj
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in total)
bear-pg0211u03a.bear.cluster - Linux RHEL 8.6, x86_64, Intel(R) Xeon(R) Gold 6248 CPU @ 2.50GHz (cascadelake), Python 3.6.8
See https://gist.github.com/da8375a9ebeed5c22397979b334c277f for a full test report.

**Comment by branfosj** [comment]
Going in, thanks @jfgrimm!

**Comment by boegel** [comment]
> lgtm
> 
> As Bazel is usually a build dependency I am happy to go with Java 13. Doing so does not fix us to that Java version in the same way it would if this was usually used as a dependency.

That's true, but it does mean we'll need to add an exception to the easyconfigs test suite as soon as we want to add another easyconfig using `GCCcore/11.3.0` as toolchain.

If Java 13 a good choice going forward as a general dependency?

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in total)
node3539.doduo.os - Linux RHEL 8.4, x86_64, AMD EPYC 7552 48-Core Processor (zen2), Python 3.6.8
See https://gist.github.com/d2d0051f9cac1a4c3df8d5e7c4e067ac for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 4 out of 4 (2 easyconfigs in total)
node3141.skitty.os - Linux RHEL 8.4, x86_64, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz, Python 3.6.8
See https://gist.github.com/7372e0d314428475a441837da034b90b for a full test report.

**Pull request merged**
