### PR TITLE
{numlib}[GCCcore/10.3.0] BLIS v0.8.1

### PR DESCRIPTION
**Pull request by SebastianAchilles**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by SebastianAchilles** [comment]
Test report by @sebastianachilles
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
jrlogin11.jureca - Linux centos linux 8.3.2011, x86_64, AMD EPYC 7742 64-Core Processor, Python 3.6.8
See https://gist.github.com/34325e85a69a18f374ec793a1040e20f for a full test report.

**Comment by branfosj** [comment]
@boegelbot please test @ generoso

**Comment by branfosj** [comment]
Test report by @branfosj
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
bear-pg0211u03a.bear.cluster - Linux RHEL 8.3, x86_64, Intel(R) Xeon(R) Gold 6248 CPU @ 2.50GHz (cascadelake), Python 3.6.8
See https://gist.github.com/3dce84f6d8428c4e0c65af4048692042 for a full test report.

**Comment by branfosj** [comment]
Test report by @branfosj
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
bear-pg0211u08b.bear.cluster - Linux Ubuntu 20.04, x86_64, Intel(R) Xeon(R) Gold 6248 CPU @ 2.50GHz (cascadelake), Python 3.8.5
See https://gist.github.com/ccd8ecc3af2c41dec8b863c462d6ad7d for a full test report.

**Comment by branfosj** [comment]
Test report by @branfosj
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
bask-pg0308u11a - Linux RHEL 8.3, x86_64, Intel(R) Xeon(R) Platinum 8358P CPU @ 2.60GHz (icelake), Python 3.6.8
See https://gist.github.com/0240db0c5f1408ae802c7e9853faf58a for a full test report.

**Review by branfosj — APPROVED** [review]
lgtm

**Comment by branfosj** [comment]
Going in, thanks @SebastianAchilles!

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
select-pika-c6gd-2xlarge-0001 - Linux centos linux 8.3.2011, AArch64, ARM UNKNOWN (graviton2), Python 3.6.8
See https://gist.github.com/e032dbfbb8d2e65e5aa8bc22e0e41590 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**FAILED**
Build succeeded for 0 out of 1 (1 easyconfigs in total)
easybuild2.novalocal - Linux centos linux 8.3.2011, POWER, IBM pSeries (emulated by qemu) (power9le), Python 3.6.8
See https://gist.github.com/9195e20af1602be1546017561bd0d092 for a full test report.

**Comment by boegel** [comment]
Hmm, this isn't working at all on POWER9 for me (see last test report).

Looks like a bug to me in the auto-detection that the BLIS configure script does, reported it upstream via https://github.com/flame/blis/issues/501.

Installing `BLIS` 0.8.1 does seem to work when replacing `auto` with `power9` in `configopts`:

```python
configopts = '--enable-cblas --enable-threading=openmp --enable-shared CC="$CC" power9'
```

cc @branfosj

**Comment by branfosj** [comment]
I remember that error from when BLIS was suggested (#9354), but at that point there were bigger problems on POWER9 (https://github.com/easybuilders/easybuild-easyconfigs/issues/9354#issuecomment-559748278). I've not tried it again.

**Pull request merged**
