### PR TITLE
OpenBabel-3.1.1 still uses 3.1.0 for the name of a couple directories, so symlink from them to 3.1.1 in postinstallcmds so BABEL_LIBDIR and BABEL_DATADIR work properly.

### PR DESCRIPTION
**Pull request by adiemu5**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by adiemu5** [comment]
Test report by @adiemu5
**FAILED**
Build succeeded for 0 out of 1 (1 easyconfigs in this PR)
login1.wave.scu.edu - Linux centos linux 7.8.2003, x86_64, Intel(R) Xeon(R) Gold 5115 CPU @ 2.40GHz, Python 2.7.5
See https://gist.github.com/7b0bb652b1db8570971ed3ddc9c6c5b3 for a full test report.

**Comment by adiemu5** [comment]
Test report by @adiemu5
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
login1.wave.scu.edu - Linux centos linux 7.8.2003, x86_64, Intel(R) Xeon(R) Gold 5115 CPU @ 2.40GHz, Python 2.7.5
See https://gist.github.com/4e1d05986b79a1bda16168cae96d2138 for a full test report.

**Comment by smoors** [comment]
Test report by @smoors
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
node373.hydra.os - Linux centos linux 7.7.1908, x86_64, Intel(R) Xeon(R) Gold 6148 CPU @ 2.40GHz (skylake_avx512), Python 2.7.5
See https://gist.github.com/8734179021c82d632ce1b97ca6915f47 for a full test report.

**Comment by smoors** [comment]
Going in, thanks @adiemu5!

**Pull request merged**
