### PR TITLE
{vis}[foss/2018b] PyQt5 v5.11.3 (+ SIP v4.19.13) w/ Python 3.6.6

### PR DESCRIPTION
**Pull request by boegel**
(created using `eb --new-pr`)

edit: now requires https://github.com/easybuilders/easybuild-easyblocks/pull/1598

### CODE REVIEW

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in this PR)
node2601.swalot.os - Linux centos linux 7.5.1804, Intel(R) Xeon(R) CPU E5-2660 v3 @ 2.60GHz, Python 2.7.5
See https://gist.github.com/c81b50b5e5ddd8de291e7bae125d7293 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in this PR)
node2023.delcatty.os - Linux centos linux 7.5.1804, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.7.5
See https://gist.github.com/418aebd54d84e53e5fb594d8fc548d5f for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
node2601.swalot.os - Linux centos linux 7.5.1804, Intel(R) Xeon(R) CPU E5-2660 v3 @ 2.60GHz, Python 2.7.5
See https://gist.github.com/0066dd18d80b3da30d8e7b526e09f0a5 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
node2086.delcatty.os - Linux centos linux 7.5.1804, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.7.5
See https://gist.github.com/0a12944db70d3a144b86e7f3e6574902 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
node3120.skitty.os - Linux centos linux 7.5.1804, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz, Python 2.7.5
See https://gist.github.com/15eb72c0da7a764dd6d3f88d3f77a9cd for a full test report.

**Comment by migueldiascosta** [comment]
Test report by @migueldiascosta
**FAILED**
Build succeeded for 0 out of 2 (1 easyconfigs in this PR)
grc-cluster1 - Linux centos 6.10, Intel(R) Xeon(R) CPU E5-2640 0 @ 2.50GHz, Python 2.7.14
See https://gist.github.com/41af46bb8ea0ed6858f0e64805f67f64 for a full test report.

**Comment by boegel** [comment]
@migueldiascosta Can you double check you're using the updating `Qt5` easyconfig from #7005?

**Comment by migueldiascosta** [comment]
@boegel yes, I was. The problem was 

```
A suitable version of python2 could not be found.
QtWebEngine will not be built.
```

it needs Python 2.7.5 or later and it was finding my system python (due to a missing `python2` link in my `/usr/local/bin`), but regardless of my setup, shouldn't Python be a dependency then?

**Comment by boegel** [comment]
@migueldiascosta I guess `Python` should be listed as a build dep for `Qt5` then, indeed... But that's orthogonal to this PR.

W.r.t. building `Qt5` on CentOS 6, any suggestions on how we deal with that? Selectively allowing that `QtWebEngine` doesn't get built (as opposed to enforcing that it gets installed, like we're doing now).

As far as I know, the `QtWebEngine` component is only really need when building `Spyder` on top of `Qt5`...

**Comment by vanzod** [comment]
Test report by @vanzod
**FAILED**
Build succeeded for 2 out of 5 (1 easyconfigs in this PR)
cermis - Linux debian 9.5, Intel(R) Xeon(R) CPU           E5620  @ 2.40GHz, Python 2.7.13
See https://gist.github.com/e634f932d26c2598637eaad68c613a66 for a full test report.

**Comment by vanzod** [comment]
Test report by @vanzod
**FAILED**
Build succeeded for 0 out of 2 (1 easyconfigs in this PR)
cermis - Linux debian 9.5, Intel(R) Xeon(R) CPU           E5620  @ 2.40GHz, Python 2.7.13
See https://gist.github.com/490e4ddb09d7667a9ce859699d3348fb for a full test report.

**Comment by vanzod** [comment]
It looks like some dependencies are missing in `Qt5` that prevent `WebEngine` to be built:
```
Note: Dropped compiler flags '-pthread' when detecting library 'glib'.
Note: Disabling X11 Accessibility Bridge: D-Bus or AT-SPI is missing.
Note: No wayland-egl support detected. Cross-toolkit compatibility disabled.
WARNING: bison is required to build QtWebEngine.
WARNING: flex is required to build QtWebEngine.
```

**Comment by vanzod** [comment]
Test report by @vanzod
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
cermis - Linux debian 9.5, Intel(R) Xeon(R) CPU           E5620  @ 2.40GHz, Python 2.7.13
See https://gist.github.com/ca6896dba00d0273686b56ae122d9a28 for a full test report.

**Comment by vanzod** [comment]
Going in, thanks @boegel!

**Pull request merged**
