### PR TITLE
{chem}[foss/2022b] LAMMPS v2Aug2023 w/ update1 kokkos WIP

### PR DESCRIPTION
**Pull request by sassy-crick**
(created using `eb --new-pr`)

Requires:
- [x] PR #19393
- [x] PR #19394
- [x] PR #19395
- [x] PR #19417

I marked that as WIP as I cannot get the Python module installed in the right location, i.e. `/foo/baa/lib/python3.10/site-packages`.  I seem to be unable to work out the difference in installation between this version and the previous one in EasyBuild. I have tried the `install_cmd = 'make install install-python'` as used in PR #18633 but that did not do the trick as well. If anybody has a good idea, feel free to jump in. Thanks.

### CODE REVIEW

**Comment by migueldiascosta** [comment]
@boegelbot please test @ generoso

**Comment by sassy-crick** [comment]
@boegelbot please test @ generoso

**Comment by ocaisa** [comment]
Update 2 for this version of LAMMPS was released yesterday

**Comment by ocaisa** [comment]
Also, this shouldn't really be merged yet as we need to update the easyblock to support the latest architectures available with Kokkos: https://docs.lammps.org/Build_extras.html#available-architecture-settings

**Comment by ocaisa** [comment]
Which is a WIP in https://github.com/easybuilders/easybuild-easyblocks/pull/3036

**Comment by laraPPr** [comment]
The reason for the failing sanity_check is that the `make install` command no longer installs the LAMMPS python module. an extra command is needed.

https://github.com/easybuilders/easybuild-easyconfigs/pull/19471#issuecomment-1926849307

**Comment by akesandgren** [comment]
This one fails --module-only with easyblock from 3036
At least in the EESSI stack

**Comment by sassy-crick** [comment]
Closed in favour of the already merged LAMMPS-2Aug2023_update2-foss-2023a-kokkos.eb

**Pull request closed without merging**
