### PR TITLE
{lib}[GCCcore/12.2.0] PostgreSQL v15.2, libaio v0.3.113, LZO v2.10, ...

### PR DESCRIPTION
**Pull request by anselmicz**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by anselmicz** [comment]
Test report by @anselmicz
**SUCCESS**
Build succeeded for 7 out of 7 (7 easyconfigs in total)
torrent - Linux Debian GNU/Linux 12, x86_64, AMD Ryzen 5 3600 6-Core Processor (zen2), 1 x NVIDIA NVIDIA GeForce RTX 3070, 525.89.02, Python 3.11.2
See https://gist.github.com/anselmicz/8c816a627d159a71824f453e28a07fc1 for a full test report.

**Comment by smoors** [comment]
@boegelbot: please test @ generoso

**Comment by smoors** [comment]
@boegelbot please test @ jsc-zen2

**Comment by smoors** [comment]
@anselmicz error for sysbench means you probably have to add `Autotools` to its `builddependencies`:
> automake 1.10.x (aclocal) wasn't found, exiting

**Comment by anselmicz** [comment]
Test report by @anselmicz
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
torrent - Linux Debian GNU/Linux 12, x86_64, AMD Ryzen 5 3600 6-Core Processor (zen2), 1 x NVIDIA NVIDIA GeForce RTX 3070, 525.105.17, Python 3.11.2
See https://gist.github.com/anselmicz/ddebe831215b13ec2c97794a402eda7c for a full test report.

**Comment by smoors** [comment]
@boegelbot please test @ jsc-zen2

**Review by smoors — APPROVED** [review]
lgtm

**Comment by smoors** [comment]
Going in, thanks @anselmicz!

**Pull request merged**
