### PR TITLE
{bio}[intel/2017a] AUGUSTUS v3.3.2

### PR DESCRIPTION
**Pull request by mboisson**
This is an updated patch in the same format as what was used for AUGUSTUS 3.2.3, but adapted for AUGUSTUS 3.3.2. 

@boegel, as mentioned, I have not tested this because we don't use the same toolchains, but I figured it would be useful for others to have the patch nevertheless.

### CODE REVIEW

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
node2118.delcatty.os - Linux centos linux 7.6.1810, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.7.5
See https://gist.github.com/9878a2dc06f8a51c1c61822bc8e86943 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**FAILED**
Build succeeded for 0 out of 1 (1 easyconfigs in this PR)
node2027.delcatty.os - Linux centos linux 7.6.1810, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.7.5
See https://gist.github.com/9993a681bb4fea2a13f59ade10db3106 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**FAILED**
Build succeeded for 0 out of 1 (1 easyconfigs in this PR)
node2524.golett.os - Linux centos linux 7.6.1810, Intel(R) Xeon(R) CPU E5-2680 v3 @ 2.50GHz, Python 2.7.5
See https://gist.github.com/702f85f9bf49d5aefcc1dee7c7ef61f0 for a full test report.

**Comment by mboisson** [comment]
Ah, right, there's a new dependency needed. I pushed the new dependency based on what I found for intel-2017a

**Comment by boegel** [comment]
Test report by @boegel
**FAILED**
Build succeeded for 0 out of 1 (1 easyconfigs in this PR)
node2524.golett.os - Linux centos linux 7.6.1810, Intel(R) Xeon(R) CPU E5-2680 v3 @ 2.50GHz, Python 2.7.5
See https://gist.github.com/f44efa28db0e8fce5de51ba6ba84c159 for a full test report.

**Comment by boegel** [comment]
@mboisson Is `bin/aln2wig` still supposed to be there?

**Comment by mboisson** [comment]
It is not there in my version. That sanity_check is inherited from the 3.2.3 version from which I copied the recipe.

**Comment by boegel** [comment]
Oh look, a fluke in Travis my bot doesn't know about yet.

Let me see if I can get it recognized so it'll re-trigger the broken test in Travis...

**Comment by boegel** [comment]
worked like a charm ^_^

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
node2562.golett.os - Linux centos linux 7.6.1810, Intel(R) Xeon(R) CPU E5-2680 v3 @ 2.50GHz, Python 2.7.5
See https://gist.github.com/f062fedd8acde3193af441cb42a59573 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
node2025.delcatty.os - Linux centos linux 7.6.1810, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.7.5
See https://gist.github.com/e42c4c61c446dcf654441da747d21d46 for a full test report.

**Comment by boegel** [comment]
Going in, thanks @mboisson!

**Pull request merged**
