### PR TITLE
{bio}[fosscuda/2019a] Dynamo v1.1.401

### PR DESCRIPTION
**Pull request by smoors**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by smoors** [comment]
Test report by @smoors
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
node377.hydra.os - Linux centos linux 7.6.1810, Intel(R) Xeon(R) Gold 6148 CPU @ 2.40GHz, Python 2.7.5
See https://gist.github.com/f37dbf92265d48a980ca9c6d96168c74 for a full test report.

**Comment by boegel** [comment]
(close & re-open to re-trigger tests after fix in #9041 got merged)

**Comment by zao** [comment]
Test report by @zao
**FAILED**
Build succeeded for 1 out of 2 (1 easyconfigs in this PR)
freja - Linux ubuntu 18.04, Intel(R) Core(TM) i7-8700K CPU @ 3.70GHz, Python 2.7.15+
See https://gist.github.com/e3d45738b106e73df9b75d56cc28f5d1 for a full test report.

**Comment by zao** [comment]
@smoors I picked this PR at random to see if I could build it, no go.
Upstream source package is a 404, they seem to purge them from the Google Drive as they update.

**Comment by smoors** [comment]
@zao ugh bummer. I opened a question on their forum, but don't have high hopes for it as the sources are 5GB.
not sure how to proceed here as they seem to regularly update the sources.

**Comment by boegel** [comment]
@smoors Is it worth pursuing this, or shall we close it?

**Review by jfgrimm — COMMENTED** [review]
As decided in issue #16330, we have deprecated the use of `True` to signify a system-toolchain dependency (#16384), in favour of the more intuitive `SYSTEM` template constant. Due to the change in the test suite, please run `eb --sync-pr-with-develop ${pr}` and update the PR to use `SYSTEM` instead.

**Comment by smoors** [comment]
> @smoors Is it worth pursuing this, or shall we close it?

let's close it for now.
we can pick it up again if/when there is a new version request.

**Pull request closed without merging**
