### PR TITLE
{bio}[GCC/10.3.0,GCC/11.2.0] PLINK v2.00a2.3

### PR DESCRIPTION
**Pull request by jfgrimm**
(created using `eb --new-pr`)

the GCC 10.3.0 version requires:
* #14833

### CODE REVIEW

**Review by verdurin — APPROVED** [review]
Looks fine.

**Comment by verdurin** [comment]
Test report by @verdurin
**SUCCESS**
Build succeeded for 3 out of 3 (2 easyconfigs in total)
easybuild-c7.novalocal - Linux UNKNOWN UNKNOWN, x86_64, Intel Xeon Processor (Skylake, IBRS), Python 3.6.8
See https://gist.github.com/2f0e942b3e76a0860bf46501ee468130 for a full test report.

**Comment by verdurin** [comment]
@boegelbot please test @ generoso

**Comment by verdurin** [comment]
Test report by @verdurin
**SUCCESS**
Build succeeded for 3 out of 3 (2 easyconfigs in total)
centos7.lan - Linux UNKNOWN UNKNOWN, x86_64, Intel Core Processor (Skylake, IBRS), Python 3.6.8
See https://gist.github.com/cbb9a93ae6b3ff0d4dc872716c0ebc58 for a full test report.

**Comment by verdurin** [comment]
This is one of these I've not been able to merge, because it claims there is a failing test report.

**Comment by branfosj** [comment]
Test report by @branfosj
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in total)
bear-pg0211u03a.bear.cluster - Linux RHEL 8.5, x86_64, Intel(R) Xeon(R) Gold 6248 CPU @ 2.50GHz (cascadelake), Python 3.6.8
See https://gist.github.com/4174e6830b0dddbb65c5f5ab983890c7 for a full test report.

**Comment by branfosj** [comment]
Going in, thanks @jfgrimm!

**Pull request merged**
