### PR TITLE
{math}[GCCcore/6.4.0] mpmath v0.19

### PR DESCRIPTION
**Pull request by JackPerdue**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by verdurin** [comment]
Test report by @verdurin
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
ca005.camp.thecrick.org - Linux centos linux 7.3.1611, Intel(R) Xeon(R) CPU E5-2640 v3 @ 2.60GHz, Python 2.7.5
See https://gist.github.com/054b2fa0ba0bc8a1c36d8ed4926f2eaf for a full test report.

**Comment by boegel** [comment]
@JackPerdue Is this meant to be a stand-alone module to be used by users, or is it a build dep for something else?

**Comment by JackPerdue** [comment]
It' for sympy, which is for FIAT, which is for PetSc

**Comment by boegel** [comment]
(close/open to retrigger Travis, not ready to go since required Python dep has been removed in #5075)

**Comment by migueldiascosta** [comment]
@JackPerdue, this PR is being closed for the following reason(s): no activity for > 6 months.
Please don't hesitate to reopen this PR or add a comment if you feel this contribution is still relevant.
For more information on our policy w.r.t. closing PRs, see https://easybuild.readthedocs.io/en/latest/Contributing.html#why-a-pull-request-may-be-closed-by-a-maintainer

**Pull request closed without merging**
