### PR TITLE
add additional extensions for R 3.4.0 and Bioconductor 3.5 bundle

### PR DESCRIPTION
**Pull request by boegel**
required for other R packages that are being installed as stand-alone modules (PRs coming up)

### CODE REVIEW

**Comment by boegel** [comment]
Test report by @boegel
**FAILED**
Build succeeded for 1 out of 2 (2 easyconfigs in this PR)
node2073.delcatty.os - Linux centos linux 7.3.1611, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.7.5
See https://gist.github.com/508de691bc072f2ee73e631b8e10d8e9 for a full test report.

**Comment by boegel** [comment]
Hmm, more packages need to be added:

```
ERROR: dependencies ‘scater’, ‘dynamicTreeCut’, ‘DT’ are not available for package ‘scran’
```

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in this PR)
node2498.golett.os - Linux centos linux 7.3.1611, Intel(R) Xeon(R) CPU E5-2680 v3 @ 2.50GHz, Python 2.7.5
See https://gist.github.com/d0eedb705bfd923ce08fbbeeee674f21 for a full test report.

**Comment by verdurin** [comment]
Test report by @verdurin
**SUCCESS**
Build succeeded for 0 out of 0 (2 easyconfigs in this PR)
ca184.camp.thecrick.org - Linux centos linux 7.2.1511, Intel(R) Xeon(R) CPU E5-2640 v3 @ 2.60GHz, Python 2.7.5
See https://gist.github.com/ba80e4c900923ae0d811a2e0faf9b78e for a full test report.

**Comment by verdurin** [comment]
Test report by @verdurin
**SUCCESS**
Build succeeded for 0 out of 0 (2 easyconfigs in this PR)
ca184.camp.thecrick.org - Linux centos linux 7.2.1511, Intel(R) Xeon(R) CPU E5-2640 v3 @ 2.60GHz, Python 2.7.5
See https://gist.github.com/a073bfb6bd333ecf7ac52d56d4995fbf for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in this PR)
node2140.delcatty.os - Linux centos linux 7.3.1611, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.7.5
See https://gist.github.com/befe9c6d94618788f235ba2a751d6ae7 for a full test report.

**Comment by verdurin** [comment]
Merging, thanks @boegel

**Pull request merged**
