### PR TITLE
{tools}[foss/2021b] worker v1.6.12

### PR DESCRIPTION
**Pull request by boegel**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by boegel** [comment]
@boegelbot please test @ generoso

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
node3144.skitty.os - Linux centos linux 7.9.2009, x86_64, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz (skylake_avx512), Python 3.6.8
See https://gist.github.com/2c6db2eb31099002a24a37157b3a0136 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
node3605.doduo.os - Linux RHEL 8.2, x86_64, AMD EPYC 7552 48-Core Processor (zen2), Python 3.6.8
See https://gist.github.com/edd2c9ae9114ada624340378a8f23040 for a full test report.

**Comment by hajgato** [comment]
Test report by @hajgato
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
node3402.kirlia.os - Linux centos linux 7.9.2009, x86_64, Intel(R) Xeon(R) Gold 6240 CPU @ 2.60GHz, Python 3.6.8
See https://gist.github.com/a55be5b66c29903f921a08064e61f976 for a full test report.

**Comment by hajgato** [comment]
lgtm

**Review by hajgato — APPROVED** [review]

**Comment by hajgato** [comment]
Going in, thanks @boegel!

**Pull request merged**
