### PR TITLE
{tools}[fosscuda/2020b] Horovod v0.22.1 w/ Python 3.8.6

### PR DESCRIPTION
**Pull request by branfosj**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by branfosj** [comment]
Test report by @branfosj
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
bask-pg0309u06a - Linux RHEL 8.4, x86_64, Intel(R) Xeon(R) Platinum 8360Y CPU @ 2.40GHz (icelake), Python 3.6.8
See https://gist.github.com/3212c8314e5ec8b5c67cba1741ff6c34 for a full test report.

**Comment by Flamefire** [comment]
Test report by @Flamefire
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
taurusi8008 - Linux centos linux 7.9.2009, x86_64, AMD EPYC 7352 24-Core Processor (zen2), Python 2.7.5
See https://gist.github.com/f2dd05671cecfc8c590272ec25f29f54 for a full test report.

**Comment by SebastianAchilles** [comment]
@branfosj Unfortunately I overlooked this PR. Last week I merged https://github.com/easybuilders/easybuild-easyconfigs/pull/14065 which added `Horovod-0.22.1-fosscuda-2020b-TensorFlow-2.5.0.eb`.
I suggest to close this PR.

**Comment by branfosj** [comment]
No worries :)

**Pull request closed without merging**
