### PR TITLE
{vis}[foss/2018b] Graphviz v2.40.1 w/ Python 2.7.15

### PR DESCRIPTION
**Pull request by lexming**
(created using `eb --new-pr`)
Main changes from previous easyconfig of `Graphviz-2.40.1`
* added missing dependencies `flex`, `libtool`, `FriBidi`, `Gdk-Pixbuf` and `libgd`
* fixed `configopts` to ensure using `libtool` and `Java` from EB
* fixes for the `dot` executable

### CODE REVIEW

**Comment by lexming** [comment]
Depends on #9785, otherwise it fails to link with `Ghostscript`.

**Comment by lexming** [comment]
Test report by @lexming
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in this PR)
login2.cerberus.os - Linux centos linux 7.7.1908, Intel(R) Xeon(R) Gold 6126 CPU @ 2.60GHz, Python 2.7.5
See https://gist.github.com/765d2bf4cf9659bd091aa482636f9ca2 for a full test report.

**Comment by migueldiascosta** [comment]
Test report by @migueldiascosta
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in this PR)
generoso - Linux centos linux 7.6.1810, Intel(R) Xeon(R) CPU E5-2660 v4 @ 2.00GHz, Python 3.6.8
See https://gist.github.com/398074f6ff0bcc6eae73d5f692950729 for a full test report.

**Comment by lexming** [comment]
Minor (but important) fix to properly set the `CLASSPATH` variable. Fortunately the tests on #9793 failed due to the deprecated Java dependency, which made me re-test the java plugin in Graphviz.

**Comment by migueldiascosta** [comment]
Going in, thanks @lexming!

**Pull request merged**
