### PR TITLE
{perf}[foss/2018a] Score-P 4.0 + Scalasca 2.4 + deps (WIP)

### PR DESCRIPTION
**Pull request by geimer**
Full-toolchain versions (flat MNS) for foss/2018a.

### CODE REVIEW

**Comment by vanzod** [comment]
@geimer Unless I am missing something, the title does not match the easyconfig...

**Comment by geimer** [comment]
@vanzod The title clearly states "WIP" ;-)  I know that it is still incomplete.  I opened this PR early to inform people that someone is working on this stuff, but then noticed that it could leverage a lot from #6328. Thus, I'm focusing on #6328 first and will come back to this PR later. Sorry for the confusion.

**Comment by vanzod** [comment]
@geier Damn, I stopped reading the title at the first line. My bad.

**Comment by boegel** [comment]
@geimer Indeed, recent versions of EasyBuild will (by default) pick up dependencies built with a subtoolchain of the toolchain being used (regardless of the MNS being used).

So, let's close this and focus on getting #6328 merged? Looking into that right now...

**Comment by geimer** [comment]
@boegel I'm absolutely in favor of maintaining only a single set of configs :wink:, thus closing this PR as suggested.

**Pull request closed without merging**
