### PR TITLE
adding easyconfigs: ParaView-5.12.0-foss-2023b.eb and Qt6-6.6.3-GCCcore

### PR DESCRIPTION
**Pull request by Louwrensth**
adding easyconfigs: 

- ParaView-5.12.0-foss-2023b.eb (without building docs that aren't supported with Qt6)
- Qt6-6.6.3-GCCcore-13.2.0.eb
- assimp-5.3.1-GCCcore-13.2.0.eb

and patches: 

- Qt6-6.6.3_fix_OF-Gentoo.patch (updated file path)

### CODE REVIEW

**Review by Micket — APPROVED** [review]
lgtm

**Comment by Micket** [comment]
@boegelbot please test @ generoso

**Comment by Micket** [comment]
Test report by @Micket
**FAILED**
Build succeeded for 2 out of 4 (3 easyconfigs in total)
alvis-skylake-build - Linux Rocky Linux 8.9, x86_64, Intel Xeon Processor (Skylake, IBRS, no TSX), Python 3.6.8
See https://gist.github.com/Micket/1bf1a7eb7bcac43b6584310c5d836b6e for a full test report.

**Comment by Micket** [comment]
@boegelbot please test @ jsc-zen3

**Comment by Micket** [comment]
Test report by @Micket
**SUCCESS**
Build succeeded for 3 out of 3 (3 easyconfigs in total)
alvis2-02 - Linux Rocky Linux 8.9, x86_64, Intel(R) Xeon(R) Gold 6226R CPU @ 2.90GHz, 8 x NVIDIA Tesla T4, 550.54.14, Python 3.6.8
See https://gist.github.com/Micket/b4e844839f166057a56627f5387bea1c for a full test report.

**Comment by Micket** [comment]
Going in, thanks @Louwrensth!

**Comment by Louwrensth** [comment]
Thanks for the review!

**Pull request merged**
