### PR TITLE
dask needs sortedcontainers to pass sanity checking

### PR DESCRIPTION
**Pull request by SimonPinches**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by boegel** [comment]
@SimonPinches `sortedcontainers` was removed from the `dask` easyconfig in #10970, because it was moved to the Python easyconfig.

You should update your Python installation with `eb Python-3.8.2-GCCcore-9.3.0.eb --skip --rebuild` to add the missing extensions.

We've learned (the hard way) that this was not a good move, because people who already had `Python` installed before suddenly hit `pip check` failures like you're seeing. Lesson learned...

**Comment by SimonPinches** [comment]
@boegel I did `eb Python-3.8.2-GCCcore-9.3.0.eb --skip --rebuild` as suggested and confirm that `sortedcontainers` does not need to be added to `dask`.  I guess this PR can be rejected/closed.

**Comment by lexming** [comment]
@SimonPinches thanks for the feedback. Closing.

**Comment by boegel** [comment]
@SimonPinches We'll work on clearer release notes that clearly highlight which existing installations should be updated, and going forward also an automated mechanism for this...

**Pull request closed without merging**
