### PR TITLE
{lib}[foss/2023a] imagecodecs v2024.1.1

### PR DESCRIPTION
**Pull request by WilleBell**
(created using `eb --new-pr`)
Depends on:

* [x] #20660 
* [x] #20661

### CODE REVIEW

**Comment by verdurin** [comment]
Test report by @verdurin
**FAILED**
Build succeeded for 11 out of 13 (1 easyconfigs in total)
easybuild-c7.novalocal - Linux CentOS Linux 7.9.2009, x86_64, Intel Xeon Processor (Skylake, IBRS), Python 3.6.8
See https://gist.github.com/verdurin/69fe3527f475bd60790be82354f6ce68 for a full test report.

**Comment by verdurin** [comment]
My build failure is down to `libjxl` not `imagecodecs`:

```
[100%] Linking CXX executable benchmark_xl
cd /dev/shm/libjxl/0.8.2/GCCcore-12.3.0/easybuild_obj/tools && /eb/maint/software/CMake/3.26.3-GCCcore-12.3.0/bin/cmake -E cmake_link_script CMakeFiles/benchmark_xl.dir/link.txt --verbose=1
/eb/maint/software/GCCcore/12.3.0/bin/g++ -O2 -ftree-vectorize -march=native -fno-math-errno -fno-rtti -funwind-tables -fno-omit-frame-pointer -O3 -DNDEBUG -O2 -L/eb/maint/software/gperftools/2.12-GCCcore-12.3.0/lib64 -L/eb/maint/software/gperftools/2.12-GCCcore-12.3.0/lib -L/eb/maint/software/OpenEXR/3.1.7-GCCcore-12.3.0/lib64 -L/eb/maint/software/OpenEXR/3.1.7-GCCcore-12.3.0/lib -L/eb/maint/software/libwebp/1.3.1-GCCcore-12.3.0/lib64 -L/eb/maint/software/libwebp/1.3.1-GCCcore-12.3.0/lib -L/eb/maint/software/giflib/5.2.1-GCCcore-12.3.0/lib64 -L/eb/maint/software/giflib/5.2.1-GCCcore-12.3.0/lib -L/eb/maint/software/zlib/1.2.13-GCCcore-12.3.0/lib64 -L/eb/maint/software/zlib/1.2.13-GCCcore-12.3.0/lib -L/eb/maint/software/libpng/1.6.39-GCCcore-12.3.0/lib64 -L/eb/maint/software/libpng/1.6.39-GCCcore-12.3.0/lib -L/eb/maint/software/libjpeg-turbo/2.1.5.1-GCCcore-12.3.0/lib64 -L/eb/maint/software/libjpeg-turbo/2.1.5.1-GCCcore-12.3.0/lib -L/eb/maint/software/Brotli/1.0.9-GCCcore-12.3.0/lib64 -L/eb/maint/software/Brotli/1.0.9-GCCcore-12.3.0/lib -L/eb/maint/software/LittleCMS/2.15-GCCcore-12.3.0/lib64 -L/eb/maint/software/LittleCMS/2.15-GCCcore-12.3.0/lib -L/eb/maint/software/Highway/1.0.4-GCCcore-12.3.0/lib64 -L/eb/maint/software/Highway/1.0.4-GCCcore-12.3.0/lib -L/eb/maint/software/pkgconf/1.9.5-GCCcore-12.3.0/lib64 -L/eb/maint/software/pkgconf/1.9.5-GCCcore-12.3.0/lib -L/eb/maint/software/googletest/1.13.0-GCCcore-12.3.0/lib64 -L/eb/maint/software/googletest/1.13.0-GCCcore-12.3.0/lib -L/eb/maint/software/binutils/2.40-GCCcore-12.3.0/lib64 -L/eb/maint/software/binutils/2.40-GCCcore-12.3.0/lib -L/eb/maint/software/GCCcore/12.3.0/lib64 -L/eb/maint/software/GCCcore/12.3.0/lib -fPIE -pie CMakeFiles/benchmark_xl.dir/benchmark/benchmark_xl.cc.o CMakeFiles/benchmark_xl.dir/benchmark/benchmark_args.cc.o CMakeFiles/benchmark_xl.dir/benchmark/benchmark_codec.cc.o CMakeFiles/benchmark_xl.dir/benchmark/benchmark_file_io.cc.o CMakeFiles/benchmark_xl.dir/benchmark/benchmark_stats.cc.o CMakeFiles/benchmark_xl.dir/benchmark/benchmark_utils.cc.o CMakeFiles/benchmark_xl.dir/benchmark/benchmark_codec_custom.cc.o CMakeFiles/benchmark_xl.dir/benchmark/benchmark_codec_jxl.cc.o CMakeFiles/benchmark_xl.dir/ssimulacra2.cc.o CMakeFiles/benchmark_xl.dir/__/third_party/dirent.cc.o CMakeFiles/benchmark_xl.dir/benchmark/benchmark_codec_jpeg.cc.o CMakeFiles/benchmark_xl.dir/benchmark/benchmark_codec_png.cc.o CMakeFiles/benchmark_xl.dir/benchmark/benchmark_codec_webp.cc.o -o benchmark_xl  /eb/maint/software/libwebp/1.3.1-GCCcore-12.3.0/lib/libwebp.a /eb/maint/software/libwebp/1.3.1-GCCcore-12.3.0/lib/libsharpyuv.a ../lib/libjxl_extras-static.a libjxl_tool.a ../lib/libjxl_threads.a /eb/maint/software/libjpeg-turbo/2.1.5.1-GCCcore-12.3.0/lib/libjpeg.so ../lib/libjpegli-static.a ../lib/libjxl.a -pthread /eb/maint/software/Brotli/1.0.9-GCCcore-12.3.0/lib/libbrotlidec.so /eb/maint/software/Brotli/1.0.9-GCCcore-12.3.0/lib/libbrotlicommon.so /eb/maint/software/Brotli/1.0.9-GCCcore-12.3.0/lib/libbrotlienc.so /eb/maint/software/LittleCMS/2.15-GCCcore-12.3.0/lib/liblcms2.so /eb/maint/software/gperftools/2.12-GCCcore-12.3.0/lib/libtcmalloc_minimal.so /eb/maint/software/libpng/1.6.39-GCCcore-12.3.0/lib/libpng.so /eb/maint/software/zlib/1.2.13-GCCcore-12.3.0/lib/libz.so /eb/maint/software/OpenEXR/3.1.7-GCCcore-12.3.0/lib64/libOpenEXR-3_1.so /eb/maint/software/OpenEXR/3.1.7-GCCcore-12.3.0/lib64/libOpenEXRUtil-3_1.so /eb/maint/software/OpenEXR/3.1.7-GCCcore-12.3.0/lib64/libOpenEXRCore-3_1.so /eb/maint/software/OpenEXR/3.1.7-GCCcore-12.3.0/lib64/libIex-3_1.so /eb/maint/software/OpenEXR/3.1.7-GCCcore-12.3.0/lib64/libIlmThread-3_1.so /eb/maint/software/Imath/3.1.7-GCCcore-12.3.0/lib64/libImath-3_1.so /eb/maint/software/Highway/1.0.4-GCCcore-12.3.0/lib/libhwy.a
/eb/maint/software/binutils/2.40-GCCcore-12.3.0/bin/ld: /eb/maint/software/libwebp/1.3.1-GCCcore-12.3.0/lib/libsharpyuv.a(libsharpyuv_la-sharpyuv_csp.o): relocation R_X86_64_32S against `.rodata' can not be used when making a PIE object; recompile with -fPIE
/eb/maint/software/binutils/2.40-GCCcore-12.3.0/bin/ld: failed to set dynamic section sizes: bad value
collect2: error: ld returned 1 exit status
make[2]: *** [tools/benchmark_xl] Error 1
make[2]: Leaving directory `/dev/shm/libjxl/0.8.2/GCCcore-12.3.0/easybuild_obj'
make[1]: *** [tools/CMakeFiles/benchmark_xl.dir/all] Error 2
make[1]: Leaving directory `/dev/shm/libjxl/0.8.2/GCCcore-12.3.0/easybuild_obj'
make: *** [all] Error 2
```

**Comment by WilleBell** [comment]
> My build failure is down to `libjxl` not `imagecodecs`:
> 
> ```
> [100%] Linking CXX executable benchmark_xl
> cd /dev/shm/libjxl/0.8.2/GCCcore-12.3.0/easybuild_obj/tools && /eb/maint/software/CMake/3.26.3-GCCcore-12.3.0/bin/cmake -E cmake_link_script CMakeFiles/benchmark_xl.dir/link.txt --verbose=1
> /eb/maint/software/GCCcore/12.3.0/bin/g++ -O2 -ftree-vectorize -march=native -fno-math-errno -fno-rtti -funwind-tables -fno-omit-frame-pointer -O3 -DNDEBUG -O2 -L/eb/maint/software/gperftools/2.12-GCCcore-12.3.0/lib64 -L/eb/maint/software/gperftools/2.12-GCCcore-12.3.0/lib -L/eb/maint/software/OpenEXR/3.1.7-GCCcore-12.3.0/lib64 -L/eb/maint/software/OpenEXR/3.1.7-GCCcore-12.3.0/lib -L/eb/maint/software/libwebp/1.3.1-GCCcore-12.3.0/lib64 -L/eb/maint/software/libwebp/1.3.1-GCCcore-12.3.0/lib -L/eb/maint/software/giflib/5.2.1-GCCcore-12.3.0/lib64 -L/eb/maint/software/giflib/5.2.1-GCCcore-12.3.0/lib -L/eb/maint/software/zlib/1.2.13-GCCcore-12.3.0/lib64 -L/eb/maint/software/zlib/1.2.13-GCCcore-12.3.0/lib -L/eb/maint/software/libpng/1.6.39-GCCcore-12.3.0/lib64 -L/eb/maint/software/libpng/1.6.39-GCCcore-12.3.0/lib -L/eb/maint/software/libjpeg-turbo/2.1.5.1-GCCcore-12.3.0/lib64 -L/eb/maint/software/libjpeg-turbo/2.1.5.1-GCCcore-12.3.0/lib -L/eb/maint/software/Brotli/1.0.9-GCCcore-12.3.0/lib64 -L/eb/maint/software/Brotli/1.0.9-GCCcore-12.3.0/lib -L/eb/maint/software/LittleCMS/2.15-GCCcore-12.3.0/lib64 -L/eb/maint/software/LittleCMS/2.15-GCCcore-12.3.0/lib -L/eb/maint/software/Highway/1.0.4-GCCcore-12.3.0/lib64 -L/eb/maint/software/Highway/1.0.4-GCCcore-12.3.0/lib -L/eb/maint/software/pkgconf/1.9.5-GCCcore-12.3.0/lib64 -L/eb/maint/software/pkgconf/1.9.5-GCCcore-12.3.0/lib -L/eb/maint/software/googletest/1.13.0-GCCcore-12.3.0/lib64 -L/eb/maint/software/googletest/1.13.0-GCCcore-12.3.0/lib -L/eb/maint/software/binutils/2.40-GCCcore-12.3.0/lib64 -L/eb/maint/software/binutils/2.40-GCCcore-12.3.0/lib -L/eb/maint/software/GCCcore/12.3.0/lib64 -L/eb/maint/software/GCCcore/12.3.0/lib -fPIE -pie CMakeFiles/benchmark_xl.dir/benchmark/benchmark_xl.cc.o CMakeFiles/benchmark_xl.dir/benchmark/benchmark_args.cc.o CMakeFiles/benchmark_xl.dir/benchmark/benchmark_codec.cc.o CMakeFiles/benchmark_xl.dir/benchmark/benchmark_file_io.cc.o CMakeFiles/benchmark_xl.dir/benchmark/benchmark_stats.cc.o CMakeFiles/benchmark_xl.dir/benchmark/benchmark_utils.cc.o CMakeFiles/benchmark_xl.dir/benchmark/benchmark_codec_custom.cc.o CMakeFiles/benchmark_xl.dir/benchmark/benchmark_codec_jxl.cc.o CMakeFiles/benchmark_xl.dir/ssimulacra2.cc.o CMakeFiles/benchmark_xl.dir/__/third_party/dirent.cc.o CMakeFiles/benchmark_xl.dir/benchmark/benchmark_codec_jpeg.cc.o CMakeFiles/benchmark_xl.dir/benchmark/benchmark_codec_png.cc.o CMakeFiles/benchmark_xl.dir/benchmark/benchmark_codec_webp.cc.o -o benchmark_xl  /eb/maint/software/libwebp/1.3.1-GCCcore-12.3.0/lib/libwebp.a /eb/maint/software/libwebp/1.3.1-GCCcore-12.3.0/lib/libsharpyuv.a ../lib/libjxl_extras-static.a libjxl_tool.a ../lib/libjxl_threads.a /eb/maint/software/libjpeg-turbo/2.1.5.1-GCCcore-12.3.0/lib/libjpeg.so ../lib/libjpegli-static.a ../lib/libjxl.a -pthread /eb/maint/software/Brotli/1.0.9-GCCcore-12.3.0/lib/libbrotlidec.so /eb/maint/software/Brotli/1.0.9-GCCcore-12.3.0/lib/libbrotlicommon.so /eb/maint/software/Brotli/1.0.9-GCCcore-12.3.0/lib/libbrotlienc.so /eb/maint/software/LittleCMS/2.15-GCCcore-12.3.0/lib/liblcms2.so /eb/maint/software/gperftools/2.12-GCCcore-12.3.0/lib/libtcmalloc_minimal.so /eb/maint/software/libpng/1.6.39-GCCcore-12.3.0/lib/libpng.so /eb/maint/software/zlib/1.2.13-GCCcore-12.3.0/lib/libz.so /eb/maint/software/OpenEXR/3.1.7-GCCcore-12.3.0/lib64/libOpenEXR-3_1.so /eb/maint/software/OpenEXR/3.1.7-GCCcore-12.3.0/lib64/libOpenEXRUtil-3_1.so /eb/maint/software/OpenEXR/3.1.7-GCCcore-12.3.0/lib64/libOpenEXRCore-3_1.so /eb/maint/software/OpenEXR/3.1.7-GCCcore-12.3.0/lib64/libIex-3_1.so /eb/maint/software/OpenEXR/3.1.7-GCCcore-12.3.0/lib64/libIlmThread-3_1.so /eb/maint/software/Imath/3.1.7-GCCcore-12.3.0/lib64/libImath-3_1.so /eb/maint/software/Highway/1.0.4-GCCcore-12.3.0/lib/libhwy.a
> /eb/maint/software/binutils/2.40-GCCcore-12.3.0/bin/ld: /eb/maint/software/libwebp/1.3.1-GCCcore-12.3.0/lib/libsharpyuv.a(libsharpyuv_la-sharpyuv_csp.o): relocation R_X86_64_32S against `.rodata' can not be used when making a PIE object; recompile with -fPIE
> /eb/maint/software/binutils/2.40-GCCcore-12.3.0/bin/ld: failed to set dynamic section sizes: bad value
> collect2: error: ld returned 1 exit status
> make[2]: *** [tools/benchmark_xl] Error 1
> make[2]: Leaving directory `/dev/shm/libjxl/0.8.2/GCCcore-12.3.0/easybuild_obj'
> make[1]: *** [tools/CMakeFiles/benchmark_xl.dir/all] Error 2
> make[1]: Leaving directory `/dev/shm/libjxl/0.8.2/GCCcore-12.3.0/easybuild_obj'
> make: *** [all] Error 2
> ```

I believe the error is due to libwebp that needs 'pic' set to True (as in PR #20660  ) could that be why this build is failing?

**Comment by bedroge** [comment]
> My build failure is down to `libjxl` not `imagecodecs`:
> 
> ```
> [100%] Linking CXX executable benchmark_xl
> cd /dev/shm/libjxl/0.8.2/GCCcore-12.3.0/easybuild_obj/tools && /eb/maint/software/CMake/3.26.3-GCCcore-12.3.0/bin/cmake -E cmake_link_script CMakeFiles/benchmark_xl.dir/link.txt --verbose=1
> /eb/maint/software/GCCcore/12.3.0/bin/g++ -O2 -ftree-vectorize -march=native -fno-math-errno -fno-rtti -funwind-tables -fno-omit-frame-pointer -O3 -DNDEBUG -O2 -L/eb/maint/software/gperftools/2.12-GCCcore-12.3.0/lib64 -L/eb/maint/software/gperftools/2.12-GCCcore-12.3.0/lib -L/eb/maint/software/OpenEXR/3.1.7-GCCcore-12.3.0/lib64 -L/eb/maint/software/OpenEXR/3.1.7-GCCcore-12.3.0/lib -L/eb/maint/software/libwebp/1.3.1-GCCcore-12.3.0/lib64 -L/eb/maint/software/libwebp/1.3.1-GCCcore-12.3.0/lib -L/eb/maint/software/giflib/5.2.1-GCCcore-12.3.0/lib64 -L/eb/maint/software/giflib/5.2.1-GCCcore-12.3.0/lib -L/eb/maint/software/zlib/1.2.13-GCCcore-12.3.0/lib64 -L/eb/maint/software/zlib/1.2.13-GCCcore-12.3.0/lib -L/eb/maint/software/libpng/1.6.39-GCCcore-12.3.0/lib64 -L/eb/maint/software/libpng/1.6.39-GCCcore-12.3.0/lib -L/eb/maint/software/libjpeg-turbo/2.1.5.1-GCCcore-12.3.0/lib64 -L/eb/maint/software/libjpeg-turbo/2.1.5.1-GCCcore-12.3.0/lib -L/eb/maint/software/Brotli/1.0.9-GCCcore-12.3.0/lib64 -L/eb/maint/software/Brotli/1.0.9-GCCcore-12.3.0/lib -L/eb/maint/software/LittleCMS/2.15-GCCcore-12.3.0/lib64 -L/eb/maint/software/LittleCMS/2.15-GCCcore-12.3.0/lib -L/eb/maint/software/Highway/1.0.4-GCCcore-12.3.0/lib64 -L/eb/maint/software/Highway/1.0.4-GCCcore-12.3.0/lib -L/eb/maint/software/pkgconf/1.9.5-GCCcore-12.3.0/lib64 -L/eb/maint/software/pkgconf/1.9.5-GCCcore-12.3.0/lib -L/eb/maint/software/googletest/1.13.0-GCCcore-12.3.0/lib64 -L/eb/maint/software/googletest/1.13.0-GCCcore-12.3.0/lib -L/eb/maint/software/binutils/2.40-GCCcore-12.3.0/lib64 -L/eb/maint/software/binutils/2.40-GCCcore-12.3.0/lib -L/eb/maint/software/GCCcore/12.3.0/lib64 -L/eb/maint/software/GCCcore/12.3.0/lib -fPIE -pie CMakeFiles/benchmark_xl.dir/benchmark/benchmark_xl.cc.o CMakeFiles/benchmark_xl.dir/benchmark/benchmark_args.cc.o CMakeFiles/benchmark_xl.dir/benchmark/benchmark_codec.cc.o CMakeFiles/benchmark_xl.dir/benchmark/benchmark_file_io.cc.o CMakeFiles/benchmark_xl.dir/benchmark/benchmark_stats.cc.o CMakeFiles/benchmark_xl.dir/benchmark/benchmark_utils.cc.o CMakeFiles/benchmark_xl.dir/benchmark/benchmark_codec_custom.cc.o CMakeFiles/benchmark_xl.dir/benchmark/benchmark_codec_jxl.cc.o CMakeFiles/benchmark_xl.dir/ssimulacra2.cc.o CMakeFiles/benchmark_xl.dir/__/third_party/dirent.cc.o CMakeFiles/benchmark_xl.dir/benchmark/benchmark_codec_jpeg.cc.o CMakeFiles/benchmark_xl.dir/benchmark/benchmark_codec_png.cc.o CMakeFiles/benchmark_xl.dir/benchmark/benchmark_codec_webp.cc.o -o benchmark_xl  /eb/maint/software/libwebp/1.3.1-GCCcore-12.3.0/lib/libwebp.a /eb/maint/software/libwebp/1.3.1-GCCcore-12.3.0/lib/libsharpyuv.a ../lib/libjxl_extras-static.a libjxl_tool.a ../lib/libjxl_threads.a /eb/maint/software/libjpeg-turbo/2.1.5.1-GCCcore-12.3.0/lib/libjpeg.so ../lib/libjpegli-static.a ../lib/libjxl.a -pthread /eb/maint/software/Brotli/1.0.9-GCCcore-12.3.0/lib/libbrotlidec.so /eb/maint/software/Brotli/1.0.9-GCCcore-12.3.0/lib/libbrotlicommon.so /eb/maint/software/Brotli/1.0.9-GCCcore-12.3.0/lib/libbrotlienc.so /eb/maint/software/LittleCMS/2.15-GCCcore-12.3.0/lib/liblcms2.so /eb/maint/software/gperftools/2.12-GCCcore-12.3.0/lib/libtcmalloc_minimal.so /eb/maint/software/libpng/1.6.39-GCCcore-12.3.0/lib/libpng.so /eb/maint/software/zlib/1.2.13-GCCcore-12.3.0/lib/libz.so /eb/maint/software/OpenEXR/3.1.7-GCCcore-12.3.0/lib64/libOpenEXR-3_1.so /eb/maint/software/OpenEXR/3.1.7-GCCcore-12.3.0/lib64/libOpenEXRUtil-3_1.so /eb/maint/software/OpenEXR/3.1.7-GCCcore-12.3.0/lib64/libOpenEXRCore-3_1.so /eb/maint/software/OpenEXR/3.1.7-GCCcore-12.3.0/lib64/libIex-3_1.so /eb/maint/software/OpenEXR/3.1.7-GCCcore-12.3.0/lib64/libIlmThread-3_1.so /eb/maint/software/Imath/3.1.7-GCCcore-12.3.0/lib64/libImath-3_1.so /eb/maint/software/Highway/1.0.4-GCCcore-12.3.0/lib/libhwy.a
> /eb/maint/software/binutils/2.40-GCCcore-12.3.0/bin/ld: /eb/maint/software/libwebp/1.3.1-GCCcore-12.3.0/lib/libsharpyuv.a(libsharpyuv_la-sharpyuv_csp.o): relocation R_X86_64_32S against `.rodata' can not be used when making a PIE object; recompile with -fPIE
> /eb/maint/software/binutils/2.40-GCCcore-12.3.0/bin/ld: failed to set dynamic section sizes: bad value
> collect2: error: ld returned 1 exit status
> make[2]: *** [tools/benchmark_xl] Error 1
> make[2]: Leaving directory `/dev/shm/libjxl/0.8.2/GCCcore-12.3.0/easybuild_obj'
> make[1]: *** [tools/CMakeFiles/benchmark_xl.dir/all] Error 2
> make[1]: Leaving directory `/dev/shm/libjxl/0.8.2/GCCcore-12.3.0/easybuild_obj'
> make: *** [all] Error 2
> ```

@verdurin I got the same thing in https://github.com/easybuilders/easybuild-easyconfigs/pull/20660, but @WilleBell fixed it in that PR.

**Comment by bedroge** [comment]
Test report by @bedroge
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
bob-Latitude-5300 - Linux Ubuntu 22.04, x86_64, Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz, Python 3.10.12
See https://gist.github.com/bedroge/2ac2338d4e2ef5c68cd1e9da8778fd20 for a full test report.

**Comment by verdurin** [comment]
Test report by @verdurin
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
easybuild-c7.novalocal - Linux CentOS Linux 7.9.2009, x86_64, Intel Xeon Processor (Skylake, IBRS), Python 3.6.8
See https://gist.github.com/verdurin/d708cd44863793f77a59a691dcc5af85 for a full test report.

**Comment by verdurin** [comment]
Yes, working now after a rebuild, thanks.

**Comment by verdurin** [comment]
@boegelbot please test @ generoso

**Comment by verdurin** [comment]
@boegelbot please test @ jsc-zen2

**Comment by verdurin** [comment]
@boegelbot please test @ jsc-zen3

**Comment by verdurin** [comment]
Going in, thanks @WilleBell!

**Pull request merged**
