### PR TITLE
downgrade dependency on nodejs + use jupyter-server-proxy in jupyter-matlab-proxy and configurable-http-proxy easyconfigs using GCCcore/10.3.0 toolchain

### PR DESCRIPTION
**Pull request by lexming**
(created using `eb --new-pr`)
Depends on
- [x]  #14844 

Changelog:
* simplify `jupyter-matlab-proxy` by depending on the new `jupyter-server-proxy`
* change the version of nodejs in `jupyter-matlab-proxy` and `configurable-http-proxy` to be in agreement  with other easyconfigs in this toolchain (*eg* `R`)

### CODE REVIEW

**Comment by lexming** [comment]
@boegelbot: please test @ generoso

**Comment by lexming** [comment]
Test report by @lexming
**SUCCESS**
Build succeeded for 3 out of 3 (2 easyconfigs in total)
node301.hydra.os - Linux CentOS Linux 7.9.2009, x86_64, Intel(R) Xeon(R) Gold 6148 CPU @ 2.40GHz, Python 2.7.5
See https://gist.github.com/f72b02ac03207d6be6945cb9676632f8 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 3 out of 3 (2 easyconfigs in total)
node2682.swalot.os - Linux CentOS Linux 7.9.2009, x86_64, Intel(R) Xeon(R) CPU E5-2660 v3 @ 2.60GHz (haswell), Python 3.6.8
See https://gist.github.com/98440c1d831644725bbc114071a58d3d for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 3 out of 3 (2 easyconfigs in total)
node3502.doduo.os - Linux RHEL 8.4, x86_64, AMD EPYC 7552 48-Core Processor (zen2), Python 3.6.8
See https://gist.github.com/2b7aba2465edce90ecd2314cc26f20f1 for a full test report.

**Review by boegel — APPROVED** [review]
lgtm

**Pull request merged**
