### PR TITLE
{bio}[intel/2020b] CAMPARI v4.0

### PR DESCRIPTION
**Pull request by smoors**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by smoors** [comment]
Test report by @smoors
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
node354.hydra.os - Linux centos linux 7.9.2009, x86_64, Intel(R) Xeon(R) Gold 6148 CPU @ 2.40GHz (skylake_avx512), Python 2.7.5
See https://gist.github.com/50e806991a24e6b36614dc8e2c39f950 for a full test report.

**Comment by smoors** [comment]
@boegelbot: please test @ generoso

**Comment by branfosj** [comment]
@boegelbot please test @ generoso

**Comment by verdurin** [comment]
@smoors any ideas here? Error is:
```
make -C /tmp/boegelbot/CAMPARI/4.0/intel-2020b/campari/source/xdr /tmp/boegelbot/CAMPARI/4.0/intel-2020b/campari/lib/x86_64/libxdrf.a
      
      
        make[1]: Entering directory '/tmp/boegelbot/CAMPARI/4.0/intel-2020b/campari/source/xdr'
      
      
        m4 conf/lnx.m4 libxdrf.m4 &gt; libxdrf.c
      
      
        icc  -c libxdrf.c -o /tmp/boegelbot/CAMPARI/4.0/intel-2020b/campari/lib/x86_64/libxdrf.o
      
      
        libxdrf.c(155): catastrophic error: cannot open source file "rpc/rpc.h"
      
      
          #include &lt;rpc/rpc.h&gt;
      
      
                              ^
      
      
        

      
      
        compilation aborted for libxdrf.c (code 4)
      
      
        make[1]: *** [Makefile:53: /tmp/boegelbot/CAMPARI/4.0/intel-2020b/campari/lib/x86_64/libxdrf.o] Error 4
      
      
        make[1]: Leaving directory '/tmp/boegelbot/CAMPARI/4.0/intel-2020b/campari/source/xdr'
      
      
        make: *** [Makefile:215: /tmp/boegelbot/CAMPARI/4.0/intel-2020b/campari/lib/x86_64/libxdrf.a] Error 2
      
      
        make: *** Waiting for unfinished jobs....
```

**Comment by smoors** [comment]
@verdurin looks like it needs rpc, which is available in CentOS 7 but not 8.
I've added libtirpc as a dep, which has rpc, but not tested if it will work, so let's just let boegelbot try it and hope for the best :)

**Comment by smoors** [comment]
@boegelbot: please test @ generoso

**Comment by smoors** [comment]
@boegelbot: please test @ generoso

**Review by verdurin — APPROVED** [review]
Looks fine.

**Comment by verdurin** [comment]
Going in, thanks @smoors!

**Pull request merged**
