### PR TITLE
matplotlib: Set CPLUS_INCLUDE_PATH for older matplotlib versions, newer already have it

### PR DESCRIPTION
**Pull request by akesandgren**
matplotlib uses CPLUS_INCLUDE_PATH to search for include files, make sure it can find freetype.

### CODE REVIEW

**Comment by Micket** [comment]
I'm going to have a hard time supplying a test report for this

**Comment by boegel** [comment]
Test report by @boegel
**FAILED**
Build succeeded for 10 out of 12 (12 easyconfigs in this PR)
node2071.delcatty.os - Linux centos linux 7.6.1810, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.7.5
See https://gist.github.com/c440ba7f53ad44fab7c56abcbc102df0 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**FAILED**
Build succeeded for 10 out of 12 (12 easyconfigs in this PR)
node2018.delcatty.os - Linux centos linux 7.6.1810, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.7.5
See https://gist.github.com/c31e0031820c8c639eb673afbbfd637e for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 12 out of 12 (12 easyconfigs in this PR)
node2018.delcatty.os - Linux centos linux 7.6.1810, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.7.5
See https://gist.github.com/f01d854af3611f17a81b7d63a8d37f79 for a full test report.

**Comment by boegel** [comment]
Going in, thanks @akesandgren!

**Pull request merged**
