### PR TITLE
include Autotools as build dep for netCDF

### PR DESCRIPTION
**Pull request by boegel**
cfr. https://github.com/easybuilders/easybuild-easyblocks/issues/1233

### CODE REVIEW

**Comment by boegel** [comment]
Test report by @boegel
**FAILED**
Build succeeded for 19 out of 20 (20 easyconfigs in this PR)
node2037.delcatty.os - Linux centos linux 7.3.1611, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.7.5
See https://gist.github.com/eed0d5e06c80b55ce265f13e7afa4a75 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**FAILED**
Build succeeded for 19 out of 20 (20 easyconfigs in this PR)
node2049.delcatty.os - Linux centos linux 7.3.1611, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.7.5
See https://gist.github.com/e9b2badfb4a863821d4a283c7b917fcc for a full test report.

**Comment by boegel** [comment]
Apparently the `ncurses` and `zlib` modules required as indirect dependencies for `netCDF-4.3.3.1-foss-2015b.eb` had disappeared, while the direct dependencies were still there...

Fixed now, new test report coming up.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 20 out of 20 (20 easyconfigs in this PR)
node2049.delcatty.os - Linux centos linux 7.3.1611, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.7.5
See https://gist.github.com/082eaa50d41502b139e6cea6ca6523ae for a full test report.

**Comment by boegel** [comment]
Third time is a charm ^_^

**Comment by vanzod** [comment]
Going in, thanks @boegel!

**Pull request merged**
