### PR TITLE
Contrib OpenMPI 1.6.3 with iccifort 2013.5.192

### PR DESCRIPTION
**Pull request by tloizou**
Contributing OpenMPI 1.6.3 with iccifort 2013.5.192
Contributing also iccifort config file and hwloc as dependencies

depends on #1000

### CODE REVIEW

**Comment by boegel** [comment]
Jenkins: ok to test

**Comment by boegel** [comment]
@tloizou: this needs a sync with `develop` too, to fix the unit tests and resolve the conflicts

**Comment by fgeorgatos** [comment]
fyi. In order to evade a performance compromise around this issue:
https://github.com/hpcugent/easybuild-easyconfigs/pull/1785
I suggest to consider a relatively recent openmpi version (or juts call the PR historic and move on)

**Comment by boegel** [comment]
@fgeorgatos: it doesn't hurt to get this in, of course using a more recent OpenMPI is recommended

**Comment by boegel** [comment]
Jenkins: ok to test

**Comment by boegel** [comment]
Jenkins: test this please

**Comment by boegel** [comment]
Jenkins: test this please

**Comment by boegel** [comment]
Jenkins: test this please

**Comment by migueldiascosta** [comment]
@tloizou, this PR is being closed for the following reason(s): no activity for > 6 months.
Please don't hesitate to reopen this PR or add a comment if you feel this contribution is still relevant.
For more information on our policy w.r.t. closing PRs, see https://easybuild.readthedocs.io/en/latest/Contributing.html#why-a-pull-request-may-be-closed-by-a-maintainer

**Pull request closed without merging**
