### PR TITLE
downgrade SPAdes dependency to v3.13.1 for Unicycler 0.4.9 since v3.15.3 is too new

### PR DESCRIPTION
**Pull request by ysagon**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by ysagon** [comment]
```
Dependencies:
  Program         Version   Status  
  spades.py       3.15.3    too new 
  racon           1.4.21    good    
  makeblastdb     2.11.0+   good    
  tblastn         2.11.0+   good    
  bowtie2-build   2.4.4     good    
  bowtie2         2.4.4     good    
  samtools        1.13      good    
  java            11.0.2    good    
  pilon           1.23      good    
  bcftools                  not used

Error: Unicycler requires SPAdes v3.6.2 - v3.13.0
```

**Comment by jfgrimm** [comment]
Test report by @jfgrimm
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in total)
node006.pri.viking.alces.network - Linux CentOS Linux 7.9.2009, x86_64, Intel(R) Xeon(R) Gold 6138 CPU @ 2.00GHz (skylake_avx512), Python 3.6.8
See https://gist.github.com/9c4f8f887b549785e317b9289084ff7f for a full test report.

**Comment by jfgrimm** [comment]
@ysagon it would be good to add a test that catches issues like this. Could you update the PR to add something like this?
```
_test_cmd = 'unicycler -t %(parallel)s -1 short_reads_1.fastq.gz -2 short_reads_2.fastq.gz -o outdir'
postinstallcmds = [
    ' '.join([
        "cd %(builddir)s/%(name)s-%(version)s/sample_data &&",
        "PYTHONPATH=%(installdir)s/lib/python%(pyshortver)s/site-packages:$PYTHONPATH",
        "PATH=%(installdir)s/bin:$PATH",
        _test_cmd,
    ]),
]
```

**Comment by jfgrimm** [comment]
@boegelbot please test @ generoso

**Comment by jfgrimm** [comment]
Going in, thanks @ysagon!

**Pull request merged**
