### PR TITLE
add direct Pango dependency in recent ImageMagick easyconfigs

### LINKED ISSUE #16236: link command for ImageMagick 7.1.0-37 with GCCcore/11.3.0 fails
The `ImageMagick` easyconfig file that was merged as a part of #15670 fails for me currently, with:

```
/software/binutils/2.38-GCCcore-11.3.0/bin/ld: cannot find -lpangocairo-1.0: No such file or directory
/software/binutils/2.38-GCCcore-11.3.0/bin/ld: cannot find -lpango-1.0: No such file or directory
collect2: error: ld returned 1 exit status
make[1]: *** [Makefile:7133: MagickCore/libMagickCore-7.Q16HDRI.la] Error 1
```

I'm puzzled what's wrong here, since:
* This easyconfig did work for various others, see test reports in #15670, and it also did work for me a while ago
* The missing Pango libraries being mentioned as there in the `lib` subdirectory of the `Pango/1.50.7-GCCcore-11.3.0` installation directory, and `Pango` is being loaded as a dependency (although indirectly)

The problem occurred for me during the regression test for EasyBuild v4.6.1, when starting to build the whole software tree from scratch...

### PR DESCRIPTION
**Pull request by boegel**
(created using `eb --new-pr`)

fixes #16236

### CODE REVIEW

**Comment by boegel** [comment]
@boegelbot please test @ generoso

**Comment by boegel** [comment]
Test report by @boegel
**FAILED**
Build succeeded for 16 out of 17 (7 easyconfigs in total)
node3106.skitty.os - Linux RHEL 8.4, x86_64, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz (skylake_avx512), Python 3.6.8
See https://gist.github.com/cef260f090c02b1000470b2b8966d3cf for a full test report.

**Comment by boegel** [comment]
@boegelbot please test @ generoso

**Review by Micket — APPROVED** [review]
lgtm

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 6 out of 6 (6 easyconfigs in total)
node3106.skitty.os - Linux RHEL 8.4, x86_64, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz (skylake_avx512), Python 3.6.8
See https://gist.github.com/7aba19da4528c8593f7f7d854a48d23e for a full test report.

**Comment by Micket** [comment]
Test report by @Micket
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
alvis-c1 - Linux Rocky Linux 8.5, x86_64, Intel Xeon Processor (Skylake), Python 3.6.8
See https://gist.github.com/76e68f714507b8b3dd2975bbd4ead3c9 for a full test report.

**Comment by Micket** [comment]
Going in, thanks @boegel!

**Pull request merged**
