### PR TITLE
{bio}[foss/2020b] CNVkit v0.9.8 w/ Python 3.8.6

### PR DESCRIPTION
**Pull request by smoors**
(created using `eb --new-pr`)

~depends on easyblock PR easybuilders/easybuild-easyblocks#2381~

### CODE REVIEW

**Comment by smoors** [comment]
Test report by @smoors
Using easyblocks from PR(s) https://github.com/easybuilders/easybuild-easyblocks/pull/2381
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
node351.hydra.os - Linux centos linux 7.9.2009, x86_64, Intel(R) Xeon(R) Gold 6148 CPU @ 2.40GHz (skylake_avx512), Python 2.7.5
See https://gist.github.com/55aecea1228136ead1738eeea21019a0 for a full test report.

**Comment by smoors** [comment]
@boegelbot: please test @ generoso

**Comment by lexming** [comment]
Test report by @lexming
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
node372.hydra.os - Linux centos linux 7.9.2009, x86_64, Intel(R) Xeon(R) Gold 6148 CPU @ 2.40GHz, Python 2.7.5
See https://gist.github.com/8120e1531d4bc8fa7ea61394dca26fbf for a full test report.

**Review by lexming — APPROVED** [review]
LGTM

**Comment by lexming** [comment]
Going in, thanks @smoors !

**Pull request merged**
