### PR TITLE
fix checksums for R extensions that were updated in place in easyconfigs for R versions 3.4.3 & 3.4.4

### PR DESCRIPTION
**Pull request by boegel**
cc @reedts, @iancost

### CODE REVIEW

**Comment by boegel** [comment]
Test report by @boegel
**FAILED**
Build succeeded for 1 out of 3 (3 easyconfigs in this PR)
node2056.delcatty.os - Linux centos linux 7.4.1708, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.7.5
See https://gist.github.com/5b48fd7888cf5bf21c5f868f432e2b56 for a full test report.

**Comment by iancost** [comment]
Fix looks good to me thanks Kenneth.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 3 out of 3 (3 easyconfigs in this PR)
node2008.delcatty.os - Linux centos linux 7.4.1708, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.7.5
See https://gist.github.com/cae4ebd073a23403f5ac00fccf4de967 for a full test report.

**Comment by vanzod** [comment]
Going in, thanks @boegel!

**Pull request merged**
