### PR TITLE
{lib}[foss/2022a] pygmo v2.18.0, pagmo v2.18.0 w/ Python 3.10.4

### PR DESCRIPTION
**Pull request by jantur3k**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by smoors** [comment]
@boegelbot: please test @ generoso

**Comment by jantur3k** [comment]
Test report by @jantur3k
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in total)
node300.hydra.os - Linux CentOS Linux 7.9.2009, x86_64, Intel(R) Xeon(R) Gold 6148 CPU @ 2.40GHz, Python 3.6.8
See https://gist.github.com/jantur3k/eddfb341049e1f71685b2a2cd6426019 for a full test report.

**Comment by smoors** [comment]
@boegelbot please test @ jsc-zen2

**Review by smoors — APPROVED** [review]
lgtm

**Comment by smoors** [comment]
Going in, thanks @jantur3k!

**Pull request merged**
