### PR TITLE
{bio}[foss/2022b] MDAnalysis v2.4.2, Biopython v1.81, networkx v3.0 w/ Python 3.10.8

### PR DESCRIPTION
**Pull request by boegel**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 3 out of 3 (3 easyconfigs in total)
node3163.skitty.os - Linux RHEL 8.6, x86_64, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz (skylake_avx512), Python 3.6.8
See https://gist.github.com/1b571e37671799ad189fc86f7197aa28 for a full test report.

**Comment by boegel** [comment]
@boegelbot please test @ generoso

**Comment by casparvl** [comment]
@boegelbot please test @ jsc-zen2

**Review by casparvl — APPROVED** [review]
No surprises in this update, lgtm! Just waiting for a test build on our systems... :)

**Comment by casparvl** [comment]
Test report by @casparvl
**SUCCESS**
Build succeeded for 31 out of 31 (3 easyconfigs in total)
tcn67.local.snellius.surf.nl - Linux Rocky Linux 8.7, x86_64, AMD EPYC 7H12 64-Core Processor, Python 3.6.8
See https://gist.github.com/c782c5eadd3ae3909a6ca16f9767c76e for a full test report.

**Comment by casparvl** [comment]
Going in, thanks @boegel!

**Pull request merged**
