### PR TITLE
{bio}[foss/2021b] CLEAR v20210117, StringTie v2.2.1 w/ Python 2.7.18

### PR DESCRIPTION
**Pull request by ItIsI-Orient**
(created using `eb --new-pr`)

Requires:
* https://github.com/easybuilders/easybuild-easyconfigs/pull/16356

### CODE REVIEW

**Comment by boegel** [comment]
@boegelbot please test @ generoso

**Comment by boegel** [comment]
@boegelbot please test @ jsc-zen2

**Comment by boegel** [comment]
@boegelbot please test @ generoso

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in total)
node3144.skitty.os - Linux RHEL 8.6, x86_64, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz (skylake_avx512), Python 3.6.8
See https://gist.github.com/boegel/aaad609edf86530fb5578bdfdf63e9c0 for a full test report.

**Comment by ItIsI-Orient** [comment]
Test report by @ItIsI-Orient
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in total)
node4006.donphan.os - Linux RHEL 8.6, x86_64, Intel(R) Xeon(R) Gold 6240 CPU @ 2.60GHz, 1 x NVIDIA NVIDIA A2, 530.30.02, Python 3.6.8
See https://gist.github.com/ItIsI-Orient/467a0ae68bd90a326c777b0779cd9e6f for a full test report.

**Review by boegel — APPROVED** [review]

**Comment by boegel** [comment]
Going in, thanks @ItIsI-Orient!

**Pull request merged**
