### PR TITLE
{bio}[foss/2023a] dorado v0.6.1, kineto v0.4.0 w/ CUDA 12.1.1

### PR DESCRIPTION
**Pull request by boegel**
(created using `eb --new-pr`)

resolves https://github.com/vscentrum/vsc-software-stack/issues/360

### CODE REVIEW

**Comment by boegel** [comment]
@boegelbot please test @ jsc-zen3

**Comment by boegel** [comment]
@boegelbot please test @ generoso

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in total)
node4015.donphan.os - Linux RHEL 8.8, x86_64, Intel(R) Xeon(R) Gold 6240 CPU @ 2.60GHz (cascadelake), 1 x NVIDIA NVIDIA A2, 545.23.08, Python 3.6.8
See https://gist.github.com/boegel/f79e75cdce42d707473db8155c15b7d3 for a full test report.

**Comment by verdurin** [comment]
Test report by @verdurin
**FAILED**
Build succeeded for 2 out of 3 (2 easyconfigs in total)
easybuild-c7.novalocal - Linux CentOS Linux 7.9.2009, x86_64, Intel Xeon Processor (Skylake, IBRS), Python 3.6.8
See https://gist.github.com/verdurin/66f5416e8217e50466a41c79cbb1c5d3 for a full test report.

**Comment by verdurin** [comment]
Test report by @verdurin
**FAILED**
Build succeeded for 1 out of 2 (2 easyconfigs in total)
easybuild-c7.novalocal - Linux CentOS Linux 7.9.2009, x86_64, Intel Xeon Processor (Skylake, IBRS), Python 3.6.8
See https://gist.github.com/verdurin/473780dcfbceaaa9f8d1564871bd1ae8 for a full test report.

**Comment by verdurin** [comment]
```
Cloning into 'dorado/3rdparty/zstd'...
Submodule path 'dorado/3rdparty/zstd': checked out '97a3da1df009d4dc67251de0c4b1c9d7fe286fc1'
Unable to checkout '88544847c51397004a31cf2817c334624c6350cf' in submodule path 'dorado/3rdparty/indicators'
 (at easybuild/tools/run.py:682 in parse_cmd_output)
== 2024-05-24 14:57:28,384 build_log.py:267 INFO ... (took 39 secs)
== 2024-05-24 14:57:28,388 config.py:699 DEBUG software install path as specified by 'installpath' and 'subdir_software': /eb/maint/software
== 2024-05-24 14:57:28,388 filetools.py:2013 INFO Removing lock /eb/maint/software/.locks/_eb_maint_software_dorado_0.6.1-foss-2023a-CUDA-12.1.1.lock...
== 2024-05-24 14:57:28,388 filetools.py:383 INFO Path /eb/maint/software/.locks/_eb_maint_software_dorado_0.6.1-foss-2023a-CUDA-12.1.1.lock successfully removed.
== 2024-05-24 14:57:28,388 filetools.py:2017 INFO Lock removed: /eb/maint/software/.locks/_eb_maint_software_dorado_0.6.1-foss-2023a-CUDA-12.1.1.lock
== 2024-05-24 14:57:28,388 easyblock.py:4291 WARNING build failed (first 300 chars): cmd "git clone --depth 1 --branch v0.6.1 --recursive https://github.com/nanoporetech/dorado.git" exited with exit code 1 and output:
Cloning into 'dorado'...
Note: checking out '79b5da50f86cdd59f24aedfeb48fd97fd9149233'.

You are in 'detached HEAD' state. You can look around, make experimental
chang
```

**Comment by boegel** [comment]
Looks like the actual error is:
```
Unable to checkout '88544847c51397004a31cf2817c334624c6350cf' in submodule path 'dorado/3rdparty/indicators'
```

Is anyone else seeing this?

**Comment by boegel** [comment]
`eb --from-pr 20444 --fetch --sourcepath /tmp` (still) works fine for me...

@verdurin Is this a consistent problem for you?

**Comment by Micket** [comment]
Test report by @Micket
**SUCCESS**
Build succeeded for 3 out of 3 (2 easyconfigs in total)
vera-skylake-build - Linux Rocky Linux 8.9, x86_64, Intel Xeon Processor (Skylake, IBRS, no TSX), Python 3.6.8
See https://gist.github.com/Micket/63d93f8fd17aaca4fb2decb6eec9eea5 for a full test report.

**Comment by zao** [comment]
Test report by @zao
**FAILED**
Build succeeded for 1 out of 2 (2 easyconfigs in total)
eb-mix.zao.se - Linux Ubuntu 24.04 LTS (Noble Numbat), x86_64, AMD Ryzen 9 3900X 12-Core Processor (zen2), Python 3.12.3
See https://gist.github.com/zao/f233c125bb235fd539601aac71c55cf0 for a full test report.

**Comment by bedroge** [comment]
Test report by @bedroge
**FAILED**
Build succeeded for 3 out of 4 (2 easyconfigs in total)
gpu1 - Linux Rocky Linux 8.9, x86_64, Intel(R) Xeon(R) Gold 6150 CPU @ 2.70GHz (skylake_avx512), 1 x NVIDIA GRID V100D-32Q, 535.161.07, Python 3.6.8
See https://gist.github.com/bedroge/f180ed2652af0b0af2a7a4dce956eee5 for a full test report.

**Comment by Micket** [comment]
i think
1. @verdurin needs to ditch centos7 which is now past eol
2. @zao needs to get a GPU
3. @bedroge probably needs more RAM (g++: fatal error: Killed signal terminated program cc1plus)

**Comment by bedroge** [comment]
Test report by @bedroge
**FAILED**
Build succeeded for 1 out of 2 (2 easyconfigs in total)
v100gpu31 - Linux Rocky Linux 8.9, x86_64, Intel(R) Xeon(R) Gold 6150 CPU @ 2.70GHz (skylake_avx512), 1 x NVIDIA GRID V100D-32Q, 535.161.07, Python 3.6.8
See https://gist.github.com/bedroge/7bb286c9fab3cbb939eb94ea11e65b2b for a full test report.

**Comment by bedroge** [comment]
Test report by @bedroge
**FAILED**
Build succeeded for 1 out of 2 (2 easyconfigs in total)
v100gpu31 - Linux Rocky Linux 8.9, x86_64, Intel(R) Xeon(R) Gold 6150 CPU @ 2.70GHz (skylake_avx512), 1 x NVIDIA GRID V100D-32Q, 535.161.07, Python 3.6.8
See https://gist.github.com/bedroge/6facbc0a8f894eb5ab75f364a54f5e53 for a full test report.

**Comment by bedroge** [comment]
Test report by @bedroge
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in total)
v100gpu31 - Linux Rocky Linux 8.9, x86_64, Intel(R) Xeon(R) Gold 6150 CPU @ 2.70GHz (skylake_avx512), 1 x NVIDIA GRID V100D-32Q, 535.161.07, Python 3.6.8
See https://gist.github.com/bedroge/6bd962cbe9e499feac29998d55f9ef0d for a full test report.

**Comment by branfosj** [comment]
> So, apparently this doesn't work with RPATH enabled.

Those are nvidia libraries that are failing the rpath. What is being pulled in our packaged inside the install?

**Comment by zao** [comment]
@Micket Seems like I don't quite need a GPU. Build passed in a Centos7 container sans rpaths, failure seen on Ubuntu 24.04 was with rpaths.

@boegel I can repro that CentOS 7 fails fetching the dorado sources, while Rocky8 succeeds.
My C7 git version is 1.8.3.1 while the R8 git version is 2.39.3.

**Comment by zao** [comment]
I would reckon that there's some fancy Git/GitHub features at play here where ancient Git doesn't manage to understand enough features to obtain the object at population time.
If I load an EB-built `git/2.28.0-nodocs` I can successfully check out the repo on CentOS 7 so the OS itself is "fine".

**Comment by verdurin** [comment]
Test report by @verdurin
**FAILED**
Build succeeded for 130 out of 132 (2 easyconfigs in total)
easybuild-el8.cloud.in.bmrc.ox.ac.uk - Linux Rocky Linux 8.10, x86_64, Intel Xeon Processor (Skylake, IBRS), Python 3.6.8
See https://gist.github.com/verdurin/4a60e3c76ccb8f08ee52e822f7fa8b46 for a full test report.

**Comment by verdurin** [comment]
Ugh, will re-try.

**Comment by boegel** [comment]
> Ugh, will re-try.

@verdurin Any updates?

**Comment by verdurin** [comment]
Test report by @verdurin
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in total)
easybuild-el8.cloud.in.bmrc.ox.ac.uk - Linux Rocky Linux 8.10, x86_64, Intel Xeon Processor (Skylake, IBRS), Python 3.6.8
See https://gist.github.com/verdurin/fc5d17a8f0cff13ec0f229017d5322e1 for a full test report.

**Comment by verdurin** [comment]
I'm happy for this to be merged now - depends whether you want to look further into these Git oddities and the complication with RPATH.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 4 out of 4 (2 easyconfigs in total)
node3304.joltik.os - Linux RHEL 8.8, x86_64, Intel(R) Xeon(R) Gold 6242 CPU @ 2.80GHz, 1 x NVIDIA Tesla V100-SXM2-32GB, 545.23.08, Python 3.6.8
See https://gist.github.com/boegel/1ea9e299a325496456086729f59ff088 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in total)
node3900.accelgor.os - Linux RHEL 8.8, x86_64, AMD EPYC 7413 24-Core Processor, 1 x NVIDIA NVIDIA A100-SXM4-80GB, 545.23.08, Python 3.6.8
See https://gist.github.com/boegel/407561432446815bb59989f61fea320b for a full test report.

**Comment by boegel** [comment]
@laraPPr please review/merge?

**Review by laraPPr — APPROVED** [review]
lgtm

**Pull request merged**
