### PR TITLE
use standard 'postinstallcmds' rather than custom 'ext_postinstallcmds' easyconfig parameter in DROP and CNVkit easyconfigs

### PR DESCRIPTION
**Pull request by boegel**
(created using `eb --new-pr`)
requires https://github.com/easybuilders/easybuild-framework/pull/3696

### CODE REVIEW

**Comment by smoors** [comment]
Test report by @smoors
**SUCCESS**
Build succeeded for 3 out of 3 (2 easyconfigs in total)
node381.hydra.os - Linux centos linux 7.9.2009, x86_64, Intel(R) Xeon(R) Gold 6148 CPU @ 2.40GHz (skylake_avx512), Python 2.7.5
See https://gist.github.com/1e1f4e4e9c6bdc00b7bf65c74c64ba7c for a full test report.

**Review by smoors — APPROVED** [review]
lgtm

**Comment by smoors** [comment]
Going in, thanks @boegel!

**Comment by boegel** [comment]
@boegelbot please test @ generoso

**Pull request merged**
