### PR TITLE
add easyconfigs for QIIME and dependencies

### PR DESCRIPTION
**Pull request by boegel**
depends on ~~#908~~, ~~#909~~, ~~#1056~~, and also https://github.com/hpcugent/easybuild-easyblocks/pull/468

dependency graph: http://users.ugent.be/~kehoste/QIIME.pdf

### CODE REVIEW

**Comment by fgeorgatos** [comment]
@boegel:

just had a cursory look through this and it is impressive box much close are your version numbers to `biodeps`. Only exception are Java & Perl minor versions, which should be a trivial change.
I'm not too surprised that your Python had to be confined to 2.7.3, yet what was your cause?

Food for thought: is there a sane way to control a multi-dependency stack of software components, as regards these common deps? (zlib, gzip, deadline, ncurses, P*, J* etc). Ah, maybe dreadful Boost, too!

**Comment by fgeorgatos** [comment]
btw. here's the biodeps reference if you care at all about it:
https://github.com/hpcugent/easybuild-easyconfigs/blob/master/easybuild/easyconfigs/b/biodeps/biodeps-1.6-goolf-1.4.10-extended.eb

**Comment by fgeorgatos** [comment]
another push for this? btw. #1056 has been merged recently.

**Comment by boegel** [comment]
(close/open to trigger Travis)

**Comment by migueldiascosta** [comment]
@boegel, this PR is being closed for the following reason(s): no activity for > 6 months, obsoleted by more recent PRs for newer versions.
Please don't hesitate to reopen this PR or add a comment if you feel this contribution is still relevant.
For more information on our policy w.r.t. closing PRs, see https://easybuild.readthedocs.io/en/latest/Contributing.html#why-a-pull-request-may-be-closed-by-a-maintainer

**Pull request closed without merging**
