### PR TITLE
{data}[foss/2020a,fosscuda/2020a] pycocotools v2.0.2 w/ Python 3.8.2

### PR DESCRIPTION
**Pull request by lexming**
(created using `eb --new-pr`)

 Depends on ~~https://github.com/easybuilders/easybuild-easyconfigs/pull/11692~~, ~~https://github.com/easybuilders/easybuild-easyconfigs/pull/11707~~

### CODE REVIEW

**Comment by lexming** [comment]
Test report by @lexming
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in total)
node155.hydra.os - Linux centos linux 7.8.2003, x86_64, Intel(R) Xeon(R) CPU E5-2680 v2 @ 2.80GHz, Python 2.7.5
See https://gist.github.com/db72bb72c7b940eb019513e9ac2a0e24 for a full test report.

**Review by Micket — APPROVED** [review]
lgtm

**Comment by Micket** [comment]
Test report by @Micket
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in total)
vera-c1 - Linux centos linux 7.8.2003, x86_64, Intel Xeon Processor (Skylake), Python 2.7.5
See https://gist.github.com/dc34ce6af9fbb609e1ca7394623b858f for a full test report.

**Comment by Micket** [comment]
Going in, thanks @lexming!

**Pull request merged**
