### PR TITLE
{cae}[system/system] Neo4j v4.2.5

### PR DESCRIPTION
**Pull request by Micket**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by Micket** [comment]
Test report by @Micket
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
vera-c1 - Linux centos linux 7.9.2009, x86_64, Intel Xeon Processor (Skylake), Python 2.7.5
See https://gist.github.com/fc230615406049a9846fbede45047cc4 for a full test report.

**Comment by Micket** [comment]
This isn't working well. It tries to use the install path for log and run directories when you launch it. So stupid. Trying to see if it can be configured with environment variables.

**Comment by jfgrimm** [comment]
not very pretty, but we installed neo4j by setting `dbms.directories.lib=%(installdir)s/lib` in `conf/neo4j.conf`, setting the env var `NEO4J_CONF` to `%(installdir)s/conf` and (ab)using `modluafooter`:
`setenv("NEO4J_HOME",pathJoin(os.getenv("HOME"),"/.neo4j_home/")`

**Comment by Micket** [comment]
Thank for the suggestion, but my concerns are
1. I suspect users *might* want to customize other things in the configuration, which complicates things a bit for them
2. I didn't want to hardcode it into any particular directory, as many of my users have separate storage projects for their bulk data, so I don't want to push them to store it in their limited home directory.
According to documentation it looks like I'm supposed to be able to defined things like `NEO4J_dbms_directories_logs` environment variables, but, i never got neo4j to care about them.

**Comment by jfgrimm** [comment]
@Micket Understandable; we ended up going with it since we only have a few users of the module and having something installed was better than nothing.
User customisation is possible with our setup, since the env vars (`NEO4J_CONF`, `NEO4J_HOME`) that we set are just the defaults. Either or both can be overridden after loading the module, we just shunt the default out of a directory they don't have write access to. 
The `NEO4J_dbms_directories_logs`-style vars are mentioned in the docker documentation for neo4j; might be worth looking at whether the docker image does anything different to handle them

**Comment by Micket** [comment]
@jfgrimm Good idea, but I can't see them doing anything special at all here https://github.com/neo4j/docker-neo4j-publish/blob/d22293f2e465b63ee5a63f0a2b8f817717a64a8b/4.2.5/community/Dockerfile 

I can't get these expand commands to work either (not does it seems like the docker version uses that trick either)
https://neo4j.com/docs/operations-manual/current/configuration/neo4j-conf/#neo4j-conf-expand-commands

**Comment by Micket** [comment]
I stpped caring about this software.

**Pull request closed without merging**
