### PR TITLE
fix SHA256 checksum for Kent_tools v422

### PR DESCRIPTION
**Pull request by sassy-crick**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by sassy-crick** [comment]
Checksum for source code updated as tarball has changed

**Comment by boegel** [comment]
@boegelbot please test @ generoso

**Comment by boegel** [comment]
@sassy-crick Can you provide some more context here? Did they re-release under the same version?

Do you still have the previous source tarball? If so, can you check what's different (by using `diff -ru old new`, where `old` is the unpacked old source tarball, and `new` is the current one?

**Comment by boegel** [comment]
@boegelbot please test @ generoso
EB_ARGS="--force-download"

**Comment by sassy-crick** [comment]
@boegel I have and I done that before i done the PR:
```
diff --git a/new/userApps/kent/src/lib/https.c b/old/userApps/kent/src/lib/https.c
index 0be0daa..c23254f 100644
--- a/new/userApps/kent/src/lib/https.c
+++ b/old/userApps/kent/src/lib/https.c
@@ -113,25 +113,17 @@ fd_set writefds;
 int err;
 struct timeval tv;
 
+// Set TRUSTED_FIRST for openssl 1.0
+// Fixes common issue openssl 1.0 had with with LetsEncrypt certs in the Fall of 2021.
+X509_STORE_set_flags(SSL_CTX_get_cert_store(ctx), X509_V_FLAG_TRUSTED_FIRST);
 
-/* TODO checking certificates 
-
-char *certFile = NULL;
-char *certPath = NULL;
-if (certFile || certPath)
+// verify peer cert of the server.
+SSL_CTX_set_verify(ctx, SSL_VERIFY_PEER, NULL);
+if (!SSL_CTX_set_default_verify_paths(ctx)) 
     {
-    SSL_CTX_load_verify_locations(ctx,certFile,certPath);
-#if (OPENSSL_VERSION_NUMBER < 0x0090600fL)
-    SSL_CTX_set_verify_depth(ctx,1);
-#endif
+    xerr("SSL set default verify paths failed");
     }
 
-// verify paths and mode.
-
-*/
-
-
-
 // Don't want any retries since we are non-blocking bio now
 // This is available on newer versions of openssl
 //SSL_set_mode(ssl, SSL_MODE_AUTO_RETRY);
@@ -281,14 +273,6 @@ while (1)
     }
 
 
-/* TODO checking certificates 
-
-if (certFile || certPath)
-    if (!check_cert(ssl, host))
-       return -1;
-
-*/
-
 /* we need to wait on both the user's socket and the BIO SSL socket 
  * to see if we need to ferry data from one to the other */
```

**Comment by boegel** [comment]
Great, so an actual case of suddenly shipping different code without bumping the version 🤦‍♂️

**Comment by sassy-crick** [comment]
Yes. Which is why I was so confused, specially as I done the EC just a few days ago.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
node2613.swalot.os - Linux centos linux 7.9.2009, x86_64, Intel(R) Xeon(R) CPU E5-2660 v3 @ 2.60GHz (haswell), Python 3.6.8
See https://gist.github.com/a5efb4742723d60165fce7f0b13e8e76 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
node3518.doduo.os - Linux RHEL 8.2, x86_64, AMD EPYC 7552 48-Core Processor (zen2), Python 3.6.8
See https://gist.github.com/80247335848458266dc718ae92f65025 for a full test report.

**Review by boegel — APPROVED** [review]
lgtm

**Comment by boegel** [comment]
Going in, thanks @sassy-crick!

**Pull request merged**
