### PR TITLE
{tools}[system/system] Jmol v16.1.41

### PR DESCRIPTION
**Pull request by jonroddom**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by jonroddom** [comment]
Hi Sam,

Thanks for the feedback. I'm still learning the ropes! Changes made accordingly.

Cheers,

Jon

**Comment by smoors** [comment]
@boegelbot: please test @ generoso

**Comment by smoors** [comment]
@boegelbot please test @ jsc-zen2

**Review by smoors — APPROVED** [review]
lgtm

**Comment by smoors** [comment]
Going in, thanks @jonroddom!

**Pull request merged**
