### PR TITLE
{bio}[foss/2022b] RegTools v1.0.0

### PR DESCRIPTION
**Pull request by laraPPr**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by laraPPr** [comment]
Test report by @laraPPr
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
node3503.doduo.os - Linux RHEL 8.6 (Ootpa), x86_64, AMD EPYC 7552 48-Core Processor (zen2), Python 3.10.8
See https://gist.github.com/laraPPr/3fc750e4af70a094d11690e16024a20a for a full test report.

**Comment by laraPPr** [comment]
@boegelbot please test @ generoso

**Comment by laraPPr** [comment]
@boegelbot please test @ jsc-zen2

**Comment by casparvl** [comment]
Test report by @casparvl
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
tcn1.local.snellius.surf.nl - Linux RHEL 8.6, x86_64, AMD EPYC 7H12 64-Core Processor, Python 3.6.8
See https://gist.github.com/casparvl/4eac965463fa517b0f236c95f523afc9 for a full test report.

**Comment by casparvl** [comment]
Going in, thanks @laraPPr!

**Pull request merged**
