### PR TITLE
{lib}[GCCcore/12.2.0] Xvfb v21.1.6, nettle v3.8.1, libxslt v1.1.37

### PR DESCRIPTION
**Pull request by jfgrimm**
(created using `eb --new-pr`)

### CODE REVIEW

**Review by boegel — DISMISSED** [review]
lgtm

**Comment by boegel** [comment]
@boegelbot please test @ generoso

**Comment by boegel** [comment]
Test report by @boegel
**FAILED**
Build succeeded for 2 out of 3 (3 easyconfigs in total)
node3162.skitty.os - Linux RHEL 8.6, x86_64, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz (skylake_avx512), Python 3.6.8
See https://gist.github.com/cc97fef7a19734e93e6ade5f244bccf9 for a full test report.

**Comment by verdurin** [comment]
@boegel any ideas about those build failures?
I've set a local build going, but it's going to take a while.

**Comment by verdurin** [comment]
Test report by @verdurin
**FAILED**
Build succeeded for 60 out of 61 (3 easyconfigs in total)
easybuild-c7.novalocal - Linux CentOS Linux 7.9.2009, x86_64, Intel Xeon Processor (Skylake, IBRS), Python 3.6.8
See https://gist.github.com/2020097151077d180b85cba1271e0015 for a full test report.

**Comment by branfosj** [comment]
> @verdurin @boegel checksum failures, for some reason `--inject-checksums --force` doesn't seem to update checksums in `Bundle` `components` for me? It calculates the correct checksums, but doesn't actually write those.

See https://github.com/easybuilders/easybuild-framework/issues/3403

**Comment by jfgrimm** [comment]
@boegelbot please test @ generoso

**Comment by boegel** [comment]
@boegelbot please test @ jsc-zen2

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 3 out of 3 (3 easyconfigs in total)
node3155.skitty.os - Linux RHEL 8.6, x86_64, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz (skylake_avx512), Python 3.6.8
See https://gist.github.com/d6ac2b1b960e21bfd06bf50077730a93 for a full test report.

**Comment by boegel** [comment]
Going in, thanks @jfgrimm!

**Comment by verdurin** [comment]
Test report by @verdurin
**SUCCESS**
Build succeeded for 1 out of 1 (3 easyconfigs in total)
easybuild-c7.novalocal - Linux CentOS Linux 7.9.2009, x86_64, Intel Xeon Processor (Skylake, IBRS), Python 3.6.8
See https://gist.github.com/c736cfc0c8ab38899d25197159119c94 for a full test report.

**Pull request merged**
