### PR TITLE
{bio}[foss/2023a] pySCENIC v0.12.1-20240311

### PR DESCRIPTION
**Pull request by pavelToman**
(created using `eb --new-pr`)

- [x] depends on #20002

### CODE REVIEW

**Comment by pavelToman** [comment]
@boegelbot please test @ generoso

**Comment by pavelToman** [comment]
@boegelbot please test @ jsc-zen3

**Comment by pavelToman** [comment]
> Test report by @boegelbot **FAILED** Build succeeded for 0 out of 1 (1 easyconfigs in total) cns3 - Linux Rocky Linux 8.9, x86_64, Intel(R) Xeon(R) CPU E5-2667 v3 @ 3.20GHz (haswell), Python 3.6.8 See https://gist.github.com/boegelbot/fc557b336ebef18d165e3b600380a305 for a full test report.

There is a problem with already downloaded /project/boegelbot/sources/p/pySCENIC/extensions/pyscenic-0.12.1.tar.gz -> needs to download again to get version from a commit

**Comment by pavelToman** [comment]
@boegelbot please test @ generoso

**Comment by pavelToman** [comment]
Waiting for loompy from PR - https://github.com/easybuilders/easybuild-easyconfigs/pull/20002

**Comment by pavelToman** [comment]
@boegelbot please test @ jsc-zen3

**Comment by pavelToman** [comment]
@boegelbot please test @ generoso

**Comment by pavelToman** [comment]
@boegelbot please test @ jsc-zen3

**Comment by verdurin** [comment]
Test report by @verdurin
**FAILED**
Build succeeded for 2 out of 3 (1 easyconfigs in total)
easybuild-c7.novalocal - Linux CentOS Linux 7.9.2009, x86_64, Intel Xeon Processor (Skylake, IBRS), Python 3.6.8
See https://gist.github.com/verdurin/0f6f8cd49532b0502ba177e33e062c93 for a full test report.

**Comment by verdurin** [comment]
```
Found 2 variants of 'dask' dependency in easyconfigs using '2023a' toolchain generation
* version: 2023.12.1; versionsuffix:  as dep for {'pySCENIC-0.12.1-20240311-foss-2023a.eb'}
  * version: 2023.9.2; versionsuffix:  as dep for {'napari-0.4.18-foss-2023a.eb', 'scikit-image-0.22.0-foss-2023a.eb', 'MONAI-1.3.0-foss-2023a.eb'}
```

**Comment by pavelToman** [comment]
@boegelbot please test @ generoso

**Comment by pavelToman** [comment]
@boegelbot please test @ jsc-zen3

**Review by boegel — APPROVED** [review]
lgtm

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
node3125.skitty.os - Linux RHEL 8.8, x86_64, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz, Python 3.6.8
See https://gist.github.com/boegel/a832dfd3de32aef6f7d2f5c548a779f1 for a full test report.

**Pull request merged**
