### PR TITLE
PnetCDF requires Perl as builddep

### PR DESCRIPTION
**Pull request by akesandgren**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by akesandgren** [comment]
@boegelbot Please test @ generoso

**Review by branfosj — APPROVED** [review]
lgtm

**Comment by branfosj** [comment]
Test report by @branfosj
**SUCCESS**
Build succeeded for 0 out of 0 (2 easyconfigs in total)
bear-pg0211u14b.bear.cluster - Linux RHEL 8.3, x86_64, Intel(R) Xeon(R) Gold 6248 CPU @ 2.50GHz (cascadelake), Python 3.6.8
See https://gist.github.com/b43da7605943503fe38b89a2aee681af for a full test report.

**Comment by branfosj** [comment]
Test report by @branfosj
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in total)
bear-pg0211u14b.bear.cluster - Linux RHEL 8.3, x86_64, Intel(R) Xeon(R) Gold 6248 CPU @ 2.50GHz (cascadelake), Python 3.6.8
See https://gist.github.com/dd9cb62f73b386203515f7338ef89d04 for a full test report.

**Comment by Micket** [comment]
I only now saw that boegelbot had problem

```
        checking for mpiicc... /users/boegelbot/CentOS8/haswell/software/impi/2019.7.217-iccifort-2020.1.217/intel64/bin/mpiicc
        checking for x86_64-pc-linux-gnu-gcc... /users/boegelbot/CentOS8/haswell/software/impi/2019.7.217-iccifort-2020.1.217/intel64/bin/mpiicc 
        checking whether the C compiler works... no
        configure: error: in `/tmp/boegelbot/PnetCDF/1.12.1/iimpi-2020a/pnetcdf-1.12.1':
        configure: error: C compiler cannot create executables
        See `config.log' for more details
```

Not sure what to make of that

**Comment by branfosj** [comment]
Test report by @branfosj
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in total)
bear-pg0305u19a.bear.cluster - Linux RHEL 8.4, POWER, 8335-GTX (power9le), Python 3.6.8
See https://gist.github.com/1835e7b35580a869b7ff868808b034eb for a full test report.

**Comment by branfosj** [comment]
@boegelbot please test @ generoso
EB_ARGS="PnetCDF-1.12.1-iimpi-2020a.eb"

**Comment by branfosj** [comment]
@boegelbot please test @ generoso

**Comment by branfosj** [comment]
Going in, thanks @akesandgren!

**Pull request merged**
