### PR TITLE
Update wkhtmltopdf-0.12.3-Linux-x86_64.eb

### PR DESCRIPTION
**Pull request by danielnavarrogomez**
Updating the source url

### CODE REVIEW

**Comment by pescobar** [comment]
Test report by @pescobar
**SUCCESS**
Build succeeded for 0 out of 0 (1 easyconfigs in this PR)
worker01.cluster.bc2.ch - Linux centos linux 7.3.1611, Intel(R) Xeon(R) CPU E5-2630 v4 @ 2.20GHz, Python 2.7.5
See https://gist.github.com/9fc573f06284e643dbcfd7e6761226a5 for a full test report.

**Comment by danielnavarrogomez** [comment]
I added a second commit with the checksum

**Comment by boegel** [comment]
Test report by @boegel
**FAILED**
Build succeeded for 0 out of 1 (1 easyconfigs in this PR)
gligar03.gligar.os - Linux centos linux 7.4.1708, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.7.5
See https://gist.github.com/69b7cafc026f2e334735872c71685823 for a full test report.

**Comment by boegel** [comment]
Hmm, checksum changed with new source URL?

**Comment by danielnavarrogomez** [comment]
I had different versions downloaded, looks like I copied the wrong sum.... the right one is:
40bc014d0754ea44bb90e733f03e7c92862f7445ef581e3599ecc00711dddcaa 

Should I create a new patch?

**Comment by boegel** [comment]
@danielnavarrogomez Thanks for the follow-up PR, we'll get that merged ASAP.

For future PRs: `eb --inject-checksums` is your friend. ;)

**Comment by pescobar** [comment]
ups, my fault. I forgot to try again the build

**Pull request merged**
