### PR TITLE
move cxxopts, termcolor and ELFIO header only libraries to SYSTEM toolchain

### PR DESCRIPTION
**Pull request by migueldiascosta**
follow up from #14487, #14488, #14489, cc @robert-mijakovic

### CODE REVIEW

**Comment by migueldiascosta** [comment]
@boegelbot please test @ generoso

**Review by branfosj — APPROVED** [review]
lgtm

**Comment by branfosj** [comment]
Test report by @branfosj
**SUCCESS**
Build succeeded for 3 out of 3 (3 easyconfigs in total)
bear-pg0211u08b.bear.cluster - Linux RHEL 8.3, x86_64, Intel(R) Xeon(R) Gold 6248 CPU @ 2.50GHz (cascadelake), Python 3.6.8
See https://gist.github.com/5807b69088dcb22398f0987f00a28ece for a full test report.

**Comment by branfosj** [comment]
Going in, thanks @migueldiascosta!

**Pull request merged**
