### PR TITLE
{bio}(foss/2015b) genometools 1.5.3,  genometools 1.5.8 plus dependency chain (WIP)

### PR DESCRIPTION
**Pull request by nathanhaigh**
Unlike PR #2283, this is `genometools` with the `cairo` and `pango` dependency chains included.

### CODE REVIEW

**Comment by nathanhaigh** [comment]
Test report by @nathanhaigh
**FAILED**
Build succeeded for 31 out of 32 (32 easyconfigs in this PR)
Linux ubuntu 14.04, Intel(R) Xeon(R) CPU E5-2699 v3 @ 2.30GHz, Python 2.7.6
See https://gist.github.com/81fa8b83b9251a0e0b67 for a full test report.

**Comment by nathanhaigh** [comment]
@boegel is there an easy way to determine if all the easyconfigs of a PR fall into a single connected dependency graph?

I'd like to know if I ended up commiting only those easyconfigs which were dependencies (directly or indirectly) to the main easyconfig for this PR (i.e. `genometools`) or if I inadvertantly added unrelated easyconfigs.

**Comment by boegel** [comment]
@nathanhaigh: see if this works and provides the info you need:

eb --from-pr 2314 --dep-graph pr2314.dot -r

You'll need a tool that can open .dot files, and you'll need to have pygraph installed (eb will tell you what's missing).

**Comment by boegel** [comment]
@nathanhaigh: this is a big PR (lots of easyconfigs), which makes it a nightmare to review/test/merge

Are you up for breaking this up, e.g. by splitting of `cairo` and deps in a separate PR?

**Comment by boegel** [comment]
Jenkins: ok to test

**Comment by nathanhaigh** [comment]
Yeah, once I got most of the dependency chain in there I did feel sorry for you! 

Would you prefer a PR for cairo and a PR for Pango? Pango was the one which blew out the dependency graph so might be worth splitting again. But we could cross that bridge when we get to it.

**Comment by boegel** [comment]
@nathanhaigh: looking at the dep graph, having dedicated PRs for cairo and Pango would seem like a nice split, indeed.

**Comment by migueldiascosta** [comment]
@nathanhaigh, this PR is being closed for the following reason(s): no activity for > 6 months.
Please don't hesitate to reopen this PR or add a comment if you feel this contribution is still relevant.
For more information on our policy w.r.t. closing PRs, see https://easybuild.readthedocs.io/en/latest/Contributing.html#why-a-pull-request-may-be-closed-by-a-maintainer

**Pull request closed without merging**
