### PR TITLE
fix missing required Python packages in ASE 3.16.2 easyconfigs

### PR DESCRIPTION
**Pull request by boegel**
~~WIP since this change should be made consistent across all ASE 3.16.2 easyconfigs, and `PythonBundle` should be used~~

### CODE REVIEW

**Comment by schiotz** [comment]
+1 for this way to make the ASE .eb files.

ASE version 3.17.0 has just been released.  I will make the .eb files in this style.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 5 out of 5 (5 easyconfigs in this PR)
node2006.delcatty.os - Linux centos linux 7.5.1804, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.7.5
See https://gist.github.com/2793fa96b7a009dd721fd129d4bfebae for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 12 out of 12 (5 easyconfigs in this PR)
node2598.golett.os - Linux centos linux 7.5.1804, Intel(R) Xeon(R) CPU E5-2680 v3 @ 2.50GHz, Python 2.7.5
See https://gist.github.com/35f572ce699322a6d48618201a44b356 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 15 out of 15 (5 easyconfigs in this PR)
node3102.skitty.os - Linux centos linux 7.5.1804, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz, Python 2.7.5
See https://gist.github.com/a8d2480c517b18c97bef75c406869086 for a full test report.

**Comment by migueldiascosta** [comment]
Test report by @migueldiascosta
**SUCCESS**
Build succeeded for 5 out of 5 (5 easyconfigs in this PR)
grc-cluster1 - Linux centos 6.10, Intel(R) Xeon(R) CPU E5-2640 0 @ 2.50GHz, Python 2.7.14
See https://gist.github.com/13f62500b01feaff51f4d39df149898e for a full test report.

**Comment by migueldiascosta** [comment]
Going in, thanks @boegel!

**Pull request merged**
