### PR TITLE
create libtinfo symlinks in easyconfigs for ncurses 6.1

### LINKED ISSUE #10663: Building Perl-5.30.0-GCCcore-8.3.0: cannot find compatible libtinfo
My setup: Centos 7.8 and EasyBuild 4.2.1

Tried to build `Perl-5.30.0-GCCcore-8.3.0` to complement my `foss-2019b` toolchain and got:

```console
$ grep tinfo Perl-5.30.0-GCCcore-8.3.0-1168025.out 
/usr/local/packages/staging/eb/binutils/2.32-GCCcore-8.3.0/bin/ld.gold: warning: skipping incompatible //lib/libtinfo.so while searching for tinfo
/usr/local/packages/staging/eb/binutils/2.32-GCCcore-8.3.0/bin/ld.gold: warning: skipping incompatible //usr/lib/libtinfo.so while searching for tinfo
/usr/local/packages/staging/eb/binutils/2.32-GCCcore-8.3.0/bin/ld.gold: error: cannot find -ltinfo
```

`libtinfo` is one of the ncurses libs.

In the `ncurses*.eb` easyconfigs that use the `SYSTEM` toolchain relevant symlinks are created: 

```python
# Symlink libtinfo to libncurses (since it can handle the API) so it doesn't get picked up from the OS
postinstallcmds = [
    "ln -s %(installdir)s/lib/libncurses.so %(installdir)s/lib/libtinfo.so",
    "ln -s %(installdir)s/lib/libncurses.a %(installdir)s/lib/libtinfo.a"
]
```

but no symlinks are created by the `ncurses` easyconfigs for non-`SYSTEM` toolchains (e.g. the `GCCcore-8.3.0` toolchain that I want to use).  There is apparently a good reason for symlinks not being created by those non-`SYSTEM` easyconfigs this but nobody seems to remember why (see https://github.com/easybuilders/easybuild-easyconfigs/pull/5863).

A possible workaround is to add the symlinks to ncurses-6.1-GCCcore-8.3.0.eb (provided it does not break other software of course) but I've created this issue as it seems surprising that others haven't encountered this.

### PR DESCRIPTION
**Pull request by branfosj**
(created using `eb --new-pr`)

same as #13660

edit (by @boegel): fixes #10663

### CODE REVIEW

**Comment by branfosj** [comment]
Test report by @branfosj
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in total)
bear-pg0211u08b.bear.cluster - Linux Ubuntu 20.04, x86_64, Intel(R) Xeon(R) Gold 6248 CPU @ 2.50GHz (cascadelake), Python 3.8.5
See https://gist.github.com/824ae5789cf4088ba4a781ac791e5595 for a full test report.

**Comment by branfosj** [comment]
Test report by @branfosj
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in total)
bear-pg0305u19a.bear.cluster - Linux RHEL 8.4, POWER, 8335-GTX (power9le), Python 3.6.8
See https://gist.github.com/7e18d67a20b4337150920c9804e9d681 for a full test report.

**Comment by branfosj** [comment]
Test report by @branfosj
**SUCCESS**
Build succeeded for 3 out of 3 (3 easyconfigs in total)
bear-pg0211u03a.bear.cluster - Linux RHEL 8.3, x86_64, Intel(R) Xeon(R) Gold 6248 CPU @ 2.50GHz (cascadelake), Python 3.6.8
See https://gist.github.com/a99a26ec40c82067dd51dab416168a7a for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 23 out of 23 (5 easyconfigs in total)
node2684.swalot.os - Linux centos linux 7.9.2009, x86_64, Intel(R) Xeon(R) CPU E5-2660 v3 @ 2.60GHz (haswell), Python 3.6.8
See https://gist.github.com/efce82ad4164bda115266047fcb25e59 for a full test report.

**Review by boegel — APPROVED** [review]
lgtm

**Comment by boegel** [comment]
Going in, thanks @branfosj!

**Pull request merged**
