### PR TITLE
{math}[foss/2023a] R-INLA v24.01.18, muParser v2.3.4, Rmath v4.3.2

### PR DESCRIPTION
**Pull request by boegel**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by boegel** [comment]
@boegelbot please test @ generoso

**Comment by boegel** [comment]
@boegelbot please test @ jsc-zen3

**Comment by terjekv** [comment]
Huh. 
```
/.../rhel8/easybuild/software/R-INLA/24.01.18-foss-2023a/INLA/bin/linux/64bit/inla.mkl.run: line 52: /.../rhel8/easybuild/software/R-INLA/24.01.18-foss-2023a/INLA/bin/linux/64bit/inla.mkl: No such file or directory
/.../rhel8/easybuild/software/R-INLA/24.01.18-foss-2023a/INLA/bin/linux/64bit/inla.mkl.run: line 58: /.../rhel8/easybuild/software/R-INLA/24.01.18-foss-2023a/INLA/bin/linux/64bit/inla.mkl: No such file or directory

 *** inla.core.safe:  The inla program failed, but will rerun in case better initial values may help. try=1/1 
/.../rhel8/easybuild/software/R-INLA/24.01.18-foss-2023a/INLA/bin/linux/64bit/inla.mkl.run: line 52: /.../rhel8/easybuild/software/R-INLA/24.01.18-foss-2023a/INLA/bin/linux/64bit/inla.mkl: No such file or directory
/.../rhel8/easybuild/software/R-INLA/24.01.18-foss-2023a/INLA/bin/linux/64bit/inla.mkl.run: line 58: /.../rhel8/easybuild/software/R-INLA/24.01.18-foss-2023a/INLA/bin/linux/64bit/inla.mkl: No such file or directory
Error in inla.core.safe(formula = formula, family = family, contrasts = contrasts,  : 
  The inla-program exited with an error. Unless you interupted it yourself, please rerun with verbose=TRUE and check the output carefully.
  If this does not help, please contact the developers at <[help@r-inla.org](mailto:help@r-inla.org)>.
The inla program failed and the maximum number of tries has been reached.
```

`/.../rhel8/easybuild/software/R-INLA/24.01.18-foss-2023a/INLA/bin/linux/64bit/inla.mkl` certainly doesn't exist. Any idea what can cause this?

**Comment by zao** [comment]
While trying to build this R-INLA I noticed that `fmesher` has a hard dependency on the `rsync` command in its installation step, halting the build.
As we don't have any rsync easyconfigs I assume that this is an implied OS dependency. Can that be documented somehow or do we expect most systems that EB installs on to have rsync?

**Review by laraPPr — APPROVED** [review]
lgtm

**Comment by laraPPr** [comment]
Going in, thanks @boegel!

**Comment by laraPPr** [comment]
Going in, thanks @boegel!

**Comment by laraPPr** [comment]
Going in, thanks @boegel!

**Comment by laraPPr** [comment]
Going in, thanks @boegel!

**Pull request merged**
