### PR TITLE
{numlib}[GCC/12.2.0] FlexiBLAS v3.2.1, BLIS v0.9.0, OpenBLAS v0.3.21

### PR DESCRIPTION
**Pull request by boegel**
(created using `eb --new-pr`)
requires:
* #16598
* #16601

### CODE REVIEW

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 3 out of 3 (3 easyconfigs in total)
node3135.skitty.os - Linux RHEL 8.4, x86_64, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz (skylake_avx512), Python 3.6.8
See https://gist.github.com/ec71922a9a3838ee5b8110939c456201 for a full test report.

**Comment by boegel** [comment]
@boegelbot please test @ jsc-zen2

**Comment by branfosj** [comment]
Test report by @branfosj
**SUCCESS**
Build succeeded for 4 out of 4 (3 easyconfigs in total)
bear-pg0211u03a.bear.cluster - Linux Ubuntu 20.04.2 LTS (Focal Fossa), x86_64, Intel(R) Xeon(R) Gold 6248 CPU @ 2.50GHz (cascadelake), Python 3.8.5
See https://gist.github.com/5817753b642b309a3e064d66f9105d48 for a full test report.

**Comment by boegel** [comment]
Hmm, I need to check whether the patch from #16406 is also required here...

**Comment by branfosj** [comment]
Test report by @branfosj
**FAILED**
Build succeeded for 8 out of 10 (3 easyconfigs in total)
bear-pg0210u06a.bear.cluster - Linux RHEL 8.6, x86_64, Intel(R) Xeon(R) CPU E5-2640 v4 @ 2.40GHz (broadwell), Python 3.6.8
See https://gist.github.com/5b24b879588401a2eb45da93a1930281 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**FAILED**
Build succeeded for 29 out of 31 (3 easyconfigs in total)
node2672.swalot.os - Linux RHEL 8.4, x86_64, Intel(R) Xeon(R) CPU E5-2660 v3 @ 2.60GHz (haswell), Python 3.6.8
See https://gist.github.com/bf649421627bb232fd20e95beb08ef85 for a full test report.

**Comment by bartoldeman** [comment]
A few of these tests are failing due to picky LAPACK tests.
There are a few ways around this:
1. Increase threshold (duh)
2. Patch LAPACK a bit more with some brackets, see https://github.com/Reference-LAPACK/lapack/issues/732 (two of the files are already patched but a few more changes were needed with the updated LAPACK in OpenBLAS 0.3.21)
3. Disable FMA (`-ffp-contract=off`) or vectorization for LAPACK (FMA is cheaper to disable here, since vectorization can give more speedup).
I looked a bit more into the why and it's really about complex multiplication:
```(a+bi)*(c+di)=(a*c-b*d)+i*(a*d+b*c)```
without FMA this always gives the same answer numerically, and for complex conjugates `(a+bi)*(a-bi)` the resulting imaginary part is exactly zero.

But with FMAs there are 4 permutations possible (e.g. `a*d+b*c -> FMA(a,d,b*c) or FMA(b,c,a*d)`) and GCC sometimes uses one variation in the vectorized loop and another one in the unvectorized loop (used for the tail ends).

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 3 out of 3 (3 easyconfigs in total)
fair-mastodon-c6g-2xlarge-0001 - Linux Rocky Linux 8.5, AArch64, ARM UNKNOWN (graviton2), Python 3.6.8
See https://gist.github.com/2cedb0f54950219e8f9b1f87a0fa5353 for a full test report.

**Comment by SebastianAchilles** [comment]
Test report by @sebastianachilles
**SUCCESS**
Build succeeded for 3 out of 3 (3 easyconfigs in total)
jrc0871.jureca - Linux Rocky Linux 8.6, AArch64, ARM UNKNOWN (graviton2), 2 x NVIDIA NVIDIA A100-PCIE-40GB, 515.65.01, Python 3.6.8
See https://gist.github.com/f278dc857456da4b99886b89a9dc0636 for a full test report.

**Comment by boegel** [comment]
@boegelbot please test @ generoso

**Comment by bartoldeman** [comment]
The OpenBLAS FMA patch was adjusted because of a new issue with GCC 12 (not present in 11.3)
https://gcc.gnu.org/bugzilla/show_bug.cgi?id=107647
https://godbolt.org/z/aWh6d1E4E

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 4 out of 4 (3 easyconfigs in total)
node3508.doduo.os - Linux RHEL 8.4, x86_64, AMD EPYC 7552 48-Core Processor (zen2), Python 3.6.8
See https://gist.github.com/87205938d1f05d7ad3f23c0b6980f20d for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 3 out of 3 (3 easyconfigs in total)
fair-mastodon-c6g-2xlarge-0001 - Linux Rocky Linux 8.5, AArch64, ARM UNKNOWN (graviton2), Python 3.6.8
See https://gist.github.com/1d49696db11b04030f75b594729a52a9 for a full test report.

**Comment by boegel** [comment]
@boegelbot please test @ jsc-zen2

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 3 out of 3 (3 easyconfigs in total)
easybuild2.novalocal - Linux CentOS Stream 8, POWER, IBM pSeries (emulated by qemu) (power9le), Python 3.6.8
See https://gist.github.com/57c0340c1ecd73329326c973738b2858 for a full test report.

**Comment by branfosj** [comment]
Test report by @branfosj
**SUCCESS**
Build succeeded for 3 out of 3 (3 easyconfigs in total)
bear-pg0105u36b.bear.cluster - Linux RHEL 8.7, x86_64, Intel(R) Xeon(R) Platinum 8360Y CPU @ 2.40GHz (icelake), Python 3.6.8
See https://gist.github.com/fe7d5404f42a1e6a318ee58ffb0f07d3 for a full test report.

**Review by branfosj — APPROVED** [review]
lgtm

**Comment by branfosj** [comment]
Test report by @branfosj
**SUCCESS**
Build succeeded for 3 out of 3 (3 easyconfigs in total)
bear-pg0211u08b.bear.cluster - Linux Ubuntu 20.04.2 LTS (Focal Fossa), x86_64, Intel(R) Xeon(R) Gold 6248 CPU @ 2.50GHz (cascadelake), Python 3.8.5
See https://gist.github.com/53b7cb28697ce3cfffff2bfcbee974d2 for a full test report.

**Comment by branfosj** [comment]
Going in, thanks @boegel!

**Pull request merged**
