### PR TITLE
{cae}[system/system] ABAQUS v2022

### PR DESCRIPTION
**Pull request by boegel**
(created using `eb --new-pr`)
requires:
* https://github.com/easybuilders/easybuild-easyblocks/pull/2716

### CODE REVIEW

**Comment by boegel** [comment]
Test report by @boegel
Using easyblocks from PR(s) https://github.com/easybuilders/easybuild-easyblocks/pull/2716
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
node3511.doduo.os - Linux RHEL 8.4, x86_64, AMD EPYC 7552 48-Core Processor (zen2), Python 3.6.8
See https://gist.github.com/24937ac4412505c2f491a07f37bb5042 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
Using easyblocks from PR(s) https://github.com/easybuilders/easybuild-easyblocks/pull/2716
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
node2602.swalot.os - Linux CentOS Linux 7.9.2009, x86_64, Intel(R) Xeon(R) CPU E5-2660 v3 @ 2.60GHz (haswell), Python 3.6.8
See https://gist.github.com/87e34e18996bc4e813b40402fceca8a2 for a full test report.

**Review by Micket — APPROVED** [review]
lgtm

**Comment by Micket** [comment]
Going in, thanks @boegel!

**Pull request merged**
