### PR TITLE
{lib}[gcccuda/2020a,gcccuda/2020b] NCCL v2.8.3

### PR DESCRIPTION
**Pull request by lexming**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by lexming** [comment]
Test report by @lexming
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in total)
node154.hydra.os - Linux centos linux 7.9.2009, x86_64, Intel(R) Xeon(R) CPU E5-2680 v2 @ 2.80GHz, Python 2.7.5
See https://gist.github.com/dcc692350def6491d0fc8c0d77351ebe for a full test report.

**Comment by Micket** [comment]
Just like cuDNN, this shouldn't exist; everything should be able to use the system level module instead. I just added PR #11907 as an example.

**Comment by lexming** [comment]
Same for `cuDNN`, I made this because packages in `fosscuda/2020a` and `fosscuda/2020b` were failing to find this dependencies. So the plan is having to add the versionsuffix for these dependencies?

**Comment by lexming** [comment]
Closing in favour of the easyconfigs already existing in `SYSTEM`

**Pull request closed without merging**
