### PR TITLE
{lib}[GCCcore/10.2.0] OpenMPI v4.0.5, libevent v2.1.12, libfabric v1.11.0, PMIx 3.1.5

### PR DESCRIPTION
**Pull request by boegel**
(created using `eb --new-pr`)
requires ~~https://github.com/easybuilders/easybuild-easyblocks/pull/2184~~ + ~~#11320~~ (UCX) + ~~#11332~~ (hwloc)

### CODE REVIEW

**Comment by boegel** [comment]
@boegelbot please test @ generoso

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 4 out of 4 (4 easyconfigs in this PR)
node3406.kirlia.os - Linux centos linux 7.8.2003, x86_64, Intel(R) Xeon(R) Gold 6240 CPU @ 2.60GHz (cascadelake), Python 2.7.5
See https://gist.github.com/ba213ae6dbf1b2f33bf35108c19d1e84 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 4 out of 4 (4 easyconfigs in this PR)
node3149.skitty.os - Linux centos linux 7.8.2003, x86_64, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz, Python 3.6.8
See https://gist.github.com/b1a7fec7331b23b529b5f01a34bb735b for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 4 out of 4 (4 easyconfigs in this PR)
node2609.swalot.os - Linux centos linux 7.8.2003, x86_64, Intel(R) Xeon(R) CPU E5-2660 v3 @ 2.60GHz (haswell), Python 2.7.5
See https://gist.github.com/54e0c16b41bdeb8e18cf5527a0ea4afd for a full test report.

**Comment by lexming** [comment]
Test report by @lexming
**SUCCESS**
Build succeeded for 5 out of 5 (4 easyconfigs in this PR)
node127.hydra.os - Linux centos linux 7.7.1908, x86_64, Intel(R) Xeon(R) CPU E5-2680 v2 @ 2.80GHz, Python 2.7.5
See https://gist.github.com/e6d314163c5aedf8d32de7f0f9056d9f for a full test report.

**Comment by lexming** [comment]
Test report by @lexming
**SUCCESS**
Build succeeded for 5 out of 5 (4 easyconfigs in this PR)
node376.hydra.os - Linux centos linux 7.7.1908, x86_64, Intel(R) Xeon(R) Gold 6148 CPU @ 2.40GHz, Python 2.7.5
See https://gist.github.com/07f7fa869c7e57849c243ebc26b6175d for a full test report.

**Review by lexming — COMMENTED** [review]
This OpenMPI is not working well on my side. A simple MPI hello world program fails to initialise OpenFabrics 

```
$ mpirun ./test
[node379.hydra.os:24944] [[51950,0],0] ORTE_ERROR_LOG: Out of resource in file util/show_help.c at line 501
--------------------------------------------------------------------------
WARNING: There was an error initializing an OpenFabrics device.

  Local host:   node378
  Local device: mlx5_0
--------------------------------------------------------------------------
Hello world from processor node379.hydra.os, rank 0 out of 2 processors
Hello world from processor node378.hydra.os, rank 1 out of 2 processors
```

OSU-Micro-benchmarks has the same issue

```
# OSU MPI Latency Test v5.6.3
# Size          Latency (us)
1024                    2.08
2048                    2.83
4096                    3.72
8192                    5.46
16384                   7.56
32768                   9.83
65536                  14.34
131072                 22.34
262144                 32.28
524288                 54.46
1048576                97.91
2097152               181.33
4194304               354.37
--------------------------------------------------------------------------
WARNING: There was an error initializing an OpenFabrics device.

  Local host:   node378
  Local device: mlx5_0
--------------------------------------------------------------------------
[node379.hydra.os:15539] [[38701,0],0] ORTE_ERROR_LOG: Data unpack would read past end of buffer in file util/show_help.c at line 501
```

The execution completes in both cases, but those errors are not good.

**Comment by terjekv** [comment]
Started a test build on a "clean" arm box. It'll take a bit. It started building M4... The box has no toolchains. :)

**Comment by terjekv** [comment]
Test report by @terjekv
**SUCCESS**
Build succeeded for 37 out of 37 (4 easyconfigs in this PR)
arm2 - Linux ubuntu 18.04, AArch64, UNKNOWN, Python 3.6.9
See https://gist.github.com/3f3bd7ad22e365787aba06bd717bc751 for a full test report.

**Comment by boegel** [comment]
> This OpenMPI is not working well on my side. A simple MPI hello world program fails to initialise OpenFabrics

The problem here is that we should be configuring OpenMPI with `--without-verbs` when we're using UCX.
That certainly fixes the problem for me (and it's a known issue, see https://www.open-mpi.org/faq/?category=all#ofa-device-error.

Please try again with the updated OpenMPI easyblock from https://github.com/easybuilders/easybuild-easyblocks/pull/2188 .

**Comment by lexming** [comment]
Test report by @lexming
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
node128.hydra.os - Linux centos linux 7.7.1908, x86_64, Intel(R) Xeon(R) CPU E5-2680 v2 @ 2.80GHz, Python 2.7.5
See https://gist.github.com/96567ab27531f1376f4b0764aa6edc36 for a full test report.

**Comment by lexming** [comment]
Test report by @lexming
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
node378.hydra.os - Linux centos linux 7.7.1908, x86_64, Intel(R) Xeon(R) Gold 6148 CPU @ 2.40GHz, Python 2.7.5
See https://gist.github.com/6314f78e9edcc6d1e3dfd75fe5257922 for a full test report.

**Comment by lexming** [comment]
@boegel thanks a lot, that was indeed the issue. We have been already disabling verbs in our production system, but I was totally misled by the `ORTE_ERROR_LOG: Data unpack would read past...` error.

**Review by lexming — APPROVED** [review]
LGTM

**Comment by boegel** [comment]
@lexming So let's merge? Or do you want to see more tests?

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 4 out of 4 (4 easyconfigs in this PR)
node3502.doduo.os - Linux RHEL 8.2, x86_64, AMD EPYC 7302P 16-Core Processor (zen2), Python 3.6.8
See https://gist.github.com/bb1df99da5e1cdd18ba1f4d58c1b7d14 for a full test report.

**Comment by lexming** [comment]
Going in, thanks @boegel !

**Pull request merged**
