### PR TITLE
{bio}[GCCcore/6.4.0] Pisces v5.2.7.47

### PR DESCRIPTION
**Pull request by boegel**
(created using `eb --new-pr`)
depends on #6345 (dotNET-Core-Runtime)

### CODE REVIEW

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
node2435.golett.os - Linux centos linux 7.4.1708, Intel(R) Xeon(R) CPU E5-2680 v3 @ 2.50GHz, Python 2.7.5
See https://gist.github.com/afc183551481f53ecc26c1eb386c40d9 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
node2065.delcatty.os - Linux centos linux 7.4.1708, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.7.5
See https://gist.github.com/1b8353602d755d45d60e8e4671ed82a4 for a full test report.

**Comment by migueldiascosta** [comment]
fails on CentOS 6.x because #6345 requires `GLIBC_2.14`

(also, uploading the test report from this one fails due to an encoding problem, see https://gist.github.com/migueldiascosta/16deb3166076fbac3e18e8e3dacd5d56)

**Comment by boegel** [comment]
@migueldiascosta Using our own `glibc` is also a nice can of worms in practice, since it will likely result in problems elsewhere...

For now, I think a comment to clarify the implicit dependency on a recent `glibc` is sufficient (who still uses CentOS 6.x anyway ;-)).

**Comment by migueldiascosta** [comment]
@boegel touché :)

**Comment by migueldiascosta** [comment]
Going in, thanks @boegel!

**Pull request merged**
