### PR TITLE
add Set::Object and Heap::Fibonacci extensions to Perl 5.32.1

### PR DESCRIPTION
**Pull request by verdurin**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by boegel** [comment]
@boegelbot please test @ generoso
EB_ARGS="--skip"

**Comment by verdurin** [comment]
@boegel yes, makes sense. Now added for `5.34.0` too.

**Comment by boegel** [comment]
@boegelbot please test @ generoso
EB_ARGS="--skip"

**Review by boegel — APPROVED** [review]

**Comment by boegel** [comment]
Going in, thanks @verdurin!

**Pull request merged**
