### PR TITLE
also install Python bindings for Brotli

### PR DESCRIPTION
**Pull request by deniskristak**
adding python wrapping to Brotli easyconfig

### CODE REVIEW

**Comment by boegel** [comment]
@deniskristak Tests are failing because you introduced a conflict in the dependencies of `fontconfig` (via `freetype`, which depends on `Brotli`):

```
$ eb --check-conflicts fontconfig-2.13.93-GCCcore-10.3.0.eb
== Temporary log file in case of crash /tmp/eb-ah33m30h/easybuild-psfr7v5m.log
Conflict found for dependencies of fontconfig-2.13.93-GCCcore-10.3.0: Python-3.9.5-GCCcore-10.3.0-bare vs Python-3.9.5-GCCcore-10.3.0
	Python-3.9.5-GCCcore-10.3.0-bare as dep of: Rust-1.52.1-GCCcore-10.3.0, fontconfig-2.13.93-GCCcore-10.3.0
	Python-3.9.5-GCCcore-10.3.0 as dep of: Brotli-1.0.9-GCCcore-10.3.0, fontconfig-2.13.93-GCCcore-10.3.0, freetype-2.10.4-GCCcore-10.3.0
```

To fix that, we should simply remove the `-bare` from the `Python` build dependency in `fontconfig-2.13.93-GCCcore-10.3.0.eb`, and add a comment to explain why we're not using the bare Python:

```python
builddependencies = [
    # can't use bare Python, because non-bare Python is required via freetype which depends on Brotli
    ('Python', '3.9.5'),
]

**Review by boegel — CHANGES_REQUESTED** [review]
@deniskristak Please make the same changes to `Brotli` (and `fontconfig`) easyconfigs that are using `GCCcore/10.2.0` or `GCCcore/11.2.0` as toolchain (since there you can add `Python` as a runtime dependency without having to introduce a `-Python-*` versionsuffix)

**Comment by boegel** [comment]
@boegelbot please test @ generoso

**Comment by deniskristak** [comment]
@boegel ready for review, im not sure if I should have added `Python` to `fontconfig-2.13.92-GCCcore-10.2.0.eb` since it wasn't there before...

**Comment by boegel** [comment]
@deniskristak The failing tests show that adding a `Python` dependency to `Brotli` isn't going to work out, since it introduces conflicts (two different Python versions that need to be loaded at the same time) in various places...

Basically, `Brotli` is as a dependency of `fontconfig`, way too deep in the stack to get away with this.

So we'll need to resort to a separate easyconfig file for the Brotli Python bindings after all...

**Comment by deniskristak** [comment]
closing, here's new PR https://github.com/easybuilders/easybuild-easyconfigs/pull/14528

**Pull request closed without merging**
