### PR TITLE
{devel}[GCCcore/10.3.0] FoBiS v3.0.5 w/ Python 3.9.5

### PR DESCRIPTION
**Pull request by akesandgren**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by akesandgren** [comment]
@boegelbot Please test @ generoso

**Comment by akesandgren** [comment]
Test report by @akesandgren
**SUCCESS**
Build succeeded for 3 out of 3 (3 easyconfigs in total)
b-an02.hpc2n.umu.se - Linux Ubuntu 20.04, x86_64, Intel(R) Xeon(R) CPU E5-2690 v4 @ 2.60GHz, Python 3.8.10
See https://gist.github.com/83b43413be0c354fb1d70d00d620dc53 for a full test report.

**Comment by migueldiascosta** [comment]
@akesandgren have you considered adding `sanity_check_commands = ["FoBiS.py -h"]`?

**Comment by akesandgren** [comment]
I knew there was something I forgot...

**Comment by migueldiascosta** [comment]
Test report by @migueldiascosta
**SUCCESS**
Build succeeded for 3 out of 3 (3 easyconfigs in total)
c2dhpc - Linux CentOS Linux 7.6.1810, x86_64, AMD EPYC 7601 32-Core Processor (zen), Python 2.7.5
See https://gist.github.com/c4a8b33aa2a53298f246d7c0f28e9e26 for a full test report.

**Review by migueldiascosta — APPROVED** [review]
lgtm

**Comment by migueldiascosta** [comment]
Going in, thanks @akesandgren!

**Pull request merged**
