### PR TITLE
override Makefile with hardcoded CC=cc in UnZip easyconfigs

### PR DESCRIPTION
**Pull request by migueldiascosta**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by migueldiascosta** [comment]
actually, nevermind :p

**Comment by boegel** [comment]
This fix made sense, why did you close it?

**Comment by migueldiascosta** [comment]
well, I hit this in the `Fujitsu` toolchain and there it needs to be overridden, it doesn't hurt in general, but in `GCCcore` the correct `cc` will be picked up anyway, no? 

I'll reopen it if you think it's worth it anyway

**Comment by boegel** [comment]
Our `GCCcore` installations provide a `cc` symlink to `gcc`, so it's indeed not a real problem, but anything that default to using `cc` is worth being forced into submission imho. ;)

**Comment by migueldiascosta** [comment]
:)

**Comment by migueldiascosta** [comment]
@boegelbot please test @ generoso

**Comment by branfosj** [comment]
Test report by @branfosj
**SUCCESS**
Build succeeded for 6 out of 6 (6 easyconfigs in total)
bear-pg0211u08b.bear.cluster - Linux RHEL 8.3, x86_64, Intel(R) Xeon(R) Gold 6248 CPU @ 2.50GHz (cascadelake), Python 3.6.8
See https://gist.github.com/5bb06536d873bd0ba858289a1effc99e for a full test report.

**Comment by branfosj** [comment]
Test report by @branfosj
**SUCCESS**
Build succeeded for 6 out of 6 (5 easyconfigs in total)
bear-pg0211u08b.bear.cluster - Linux Ubuntu 20.04, x86_64, Intel(R) Xeon(R) Gold 6248 CPU @ 2.50GHz (cascadelake), Python 3.8.5
See https://gist.github.com/46b4f07c6b82384cc9b2f7bc7727850b for a full test report.

**Comment by branfosj** [comment]
Test report by @branfosj
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in total)
bber0501u03a.bb2.cluster - Linux centos linux 7.8.2003, x86_64, Intel(R) Xeon(R) CPU E5-2690 v3 @ 2.60GHz (haswell), Python 3.6.8
See https://gist.github.com/dfa7f78d94b36dc3f9745dd9b3862595 for a full test report.

**Comment by branfosj** [comment]
> 
> 
> Test report by @boegelbot
> **FAILED**
> Build succeeded for 6 out of 16 (7 easyconfigs in total)
> generoso-c1-s-1 - Linux centos linux 8.2.2004, x86_64, Intel(R) Xeon(R) CPU E5-2667 v3 @ 3.20GHz (haswell), Python 3.6.8
> See https://gist.github.com/0a32a056b79b7151d3d3f4249b91101c for a full test report.

The failure here was that `GCCcore-6.4.0.eb` does not build on CentOS 8.

**Review by branfosj — APPROVED** [review]
lgtm

**Comment by branfosj** [comment]
Going in, thanks @migueldiascosta!

**Pull request merged**
