### PR TITLE
{chem}[foss/2019a] CP2K v6.1

### PR DESCRIPTION
**Pull request by Micket**
(created using `eb --new-pr`)

edit: depends on ~#8187~ (libxsmm), ~#8185~ (libxc), ~#8183~ (LibInt)

### CODE REVIEW

**Comment by Micket** [comment]
travis kicking time

**Comment by Micket** [comment]
go

**Comment by vanzod** [comment]
Test report by @vanzod
**SUCCESS**
Build succeeded for 10 out of 10 (1 easyconfigs in this PR)
cermis - Linux debian 9.9, Intel(R) Xeon(R) CPU           X5670  @ 2.93GHz, Python 2.7.13
See https://gist.github.com/cffe709f4ab5ccbd43b677b14390234e for a full test report.

**Comment by vanzod** [comment]
Going in, thanks @Micket!

**Comment by akesandgren** [comment]
Test report by @akesandgren
**SUCCESS**
Build succeeded for 9 out of 9 (1 easyconfigs in this PR)
b-an03.hpc2n.umu.se - Linux ubuntu 16.04, Intel(R) Xeon(R) CPU E5-2690 v4 @ 2.60GHz, Python 2.7.12
See https://gist.github.com/65144d401198d1c533748997cc303a6e for a full test report.

**Pull request merged**
