### PR TITLE
{devel}[foss/2023a] NLTK v3.8.1

### PR DESCRIPTION
**Pull request by Micket**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by Micket** [comment]
@boegelbot please test @ jsc-zen3

**Comment by casparvl** [comment]
Test report by @casparvl
**SUCCESS**
Build succeeded for 2 out of 2 (1 easyconfigs in total)
tcn1.local.snellius.surf.nl - Linux RHEL 8.6, x86_64, AMD EPYC 7H12 64-Core Processor, Python 3.6.8
See https://gist.github.com/casparvl/67e003730004b24e9e8883759eedb65e for a full test report.

**Review by casparvl — APPROVED** [review]
Lgtm, simple update, no surprises.

**Comment by casparvl** [comment]
Going in, thanks @Micket!

**Pull request merged**
