### PR TITLE
{lib}[GCCcore/10.3.0] Qt5 v5.15.2, libGLU v9.0.1, NSS v3.65, ...

### PR DESCRIPTION
**Pull request by boegel**
(created using `eb --new-pr`)
requires ~#12939~ (X11), ~#12940~ (GLib), ~#12943~ (Mesa), ~#12954~ (Python 2)

### CODE REVIEW

**Comment by boegel** [comment]
Test report by @boegel
**FAILED**
Build succeeded for 4 out of 5 (5 easyconfigs in total)
node3595.doduo.os - Linux RHEL 8.2, x86_64, AMD EPYC 7552 48-Core Processor (zen2), Python 3.6.8
See https://gist.github.com/f5914b4be3727dca09cf3650d28a2aac for a full test report.

**Comment by branfosj** [comment]
I hit the same error:
> Sanity check failed: no file found at 'lib/libQt5WebEngine.so'

Further up in my log:
> WARNING: Python version 2 (2.7.5 or later) is required to build QtWebengine.

**Comment by branfosj** [comment]
Further testing, on a system with OS `python2.7`, but where there is no `python2` symlinked to it. If I add
```
preconfigopts = 'mkdir pybin && cd pybin && ln -s /usr/bin/python2.7 python2 && cd .. && export PATH=$PATH:`pwd`/pybin && '
```
to the Qt ec then the configure log says that it will build QtWebEngine.

So, we'll need a Python 2 to use as a build dependency here.

**Comment by boegel** [comment]
@branfosj Easyconfig for bare Python 2 added in #12954, I'll add that as a build dep here once that one is merged.

**Comment by boegel** [comment]
@boegelbot please test @ generoso
CORE_CNT=16

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 5 out of 5 (5 easyconfigs in total)
node3506.doduo.os - Linux RHEL 8.2, x86_64, AMD EPYC 7552 48-Core Processor (zen2), Python 3.6.8
See https://gist.github.com/45393ae39cb8dd90091f157f60f5f5dd for a full test report.

**Review by branfosj — APPROVED** [review]
lgtm

**Comment by branfosj** [comment]
Going in, thanks @boegel!

**Comment by branfosj** [comment]
Test report by @branfosj
Using easyblocks from PR(s) https://github.com/easybuilders/easybuild-easyblocks/pull/2338
**SUCCESS**
Build succeeded for 5 out of 5 (5 easyconfigs in total)
bear-pg0211u03a.bear.cluster - Linux Ubuntu 20.04, x86_64, Intel(R) Xeon(R) Gold 6248 CPU @ 2.50GHz (cascadelake), Python 3.8.5
See https://gist.github.com/5b49cfde64c059d99cf09ea3361f08f7 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**FAILED**
Build succeeded for 5 out of 6 (5 easyconfigs in total)
select-pika-c6gd-2xlarge-0001 - Linux centos linux 8.3.2011, AArch64, ARM UNKNOWN (graviton2), Python 3.6.8
See https://gist.github.com/02d2b6c60f052d8abe3cb111d0eafd0b for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 5 out of 5 (5 easyconfigs in total)
easybuild2.novalocal - Linux centos linux 8.3.2011, POWER, IBM pSeries (emulated by qemu) (power9le), Python 3.6.8
See https://gist.github.com/c34b681ef12354fc799b8b949b0f13c7 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 5 out of 5 (5 easyconfigs in total)
select-pika-c6gd-4xlarge-0001 - Linux centos linux 8.3.2011, AArch64, ARM UNKNOWN (graviton2), Python 3.6.8
See https://gist.github.com/ed2d1649376d9931a4ae8ff6a6263403 for a full test report.

**Pull request merged**
