### PR TITLE
add twang + xgboost extensions to recent R easyconfigs

### PR DESCRIPTION
**Pull request by boegel**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by boegel** [comment]
@boegelbot please test @ generoso
EB_ARGS="R-4.0.3-foss-2020b.eb R-4.0.4-foss-2020b.eb R-4.0.5-foss-2020b.eb R-4.1.0-foss-2021a.eb --skip"

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 7 out of 7 (7 easyconfigs in total)
node3301.joltik.os - Linux centos linux 7.9.2009, x86_64, Intel(R) Xeon(R) Gold 6242 CPU @ 2.80GHz (cascadelake), Python 3.6.8
See https://gist.github.com/32cc8611e324581e2a19f7c4b24a5293 for a full test report.

**Comment by branfosj** [comment]
An older version of `xgboost` is in `R-bundle-Bioconductor-3.12-foss-2020b-R-4.0.3.eb`. I'm unsure what will happen if we load that module as well.

**Comment by boegel** [comment]
> An older version of `xgboost` is in `R-bundle-Bioconductor-3.12-foss-2020b-R-4.0.3.eb`. I'm unsure what will happen if we load that module as well.

First "hit" wins probably, so if `R-bundle-Bioconductor` is loaded, then the `xgboost` included there will be picked up.

**Comment by branfosj** [comment]
> 
> 
> > An older version of `xgboost` is in `R-bundle-Bioconductor-3.12-foss-2020b-R-4.0.3.eb`. I'm unsure what will happen if we load that module as well.
> 
> First "hit" wins probably, so if `R-bundle-Bioconductor` is loaded, then the `xgboost` included there will be picked up.

The twang cran page (https://cran.r-project.org/web/packages/twang/index.html) does not suggest there is a version requirement on xgboost - so we will likely be fine if someone has both loaded at the same time.

**Review by branfosj — APPROVED** [review]
lgtm

**Comment by branfosj** [comment]
Going in, thanks @boegel!

**Pull request merged**
