### PR TITLE
{bio}[GCC/12.2.0] Exonerate v2.4.0

### PR DESCRIPTION
**Pull request by eylenth**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by eylenth** [comment]
Test report by @eylenth
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
by0owl.eu.seeds.basf.net - Linux RHEL 7.9, x86_64, Intel(R) Xeon(R) CPU E5-2620 v4 @ 2.10GHz (broadwell), Python 3.6.8
See https://gist.github.com/eylenth/ecd49ceb00ae9b806e4b7f60e826ae27 for a full test report.

**Review by Micket — APPROVED** [review]
lgtm

**Comment by Micket** [comment]
@boegelbot please test @ generoso

**Comment by Micket** [comment]
Test report by @Micket
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
vera-c1 - Linux Rocky Linux 8.7, x86_64, Intel Xeon Processor (Skylake), Python 3.6.8
See https://gist.github.com/Micket/b5a05f8853a9122cca0c99e1020b1739 for a full test report.

**Pull request merged**
