### PR TITLE
[R 3.6.0] Add missing pocl dependency

### PR DESCRIPTION
**Pull request by Flamefire**
(created using `eb --new-pr`)

- [x]  Requires #11166

### CODE REVIEW

**Review by lexming — CHANGES_REQUESTED** [review]
I suggest to add a new easyconfig for `Clang-8.0.0-GCC-8.2.0-2.31.1-CUDA-10.1.105.eb` to fix the tests and follow the same approach used in `2019b`. We already have `Clang-8.0.0-GCCcore-8.2.0-CUDA-10.1.105.eb`, which can be used as reference.

On the other hand, is there any reason to specifically upgrade to `pocl` v1.5 in `2019a`? I prefer to keep version parity between the CUDA and non-CUDA `pocl` easyconfigs in `2019a`. Version 1.5 of `pocl` seems a better fit for `2020a`.

**Comment by Flamefire** [comment]
Re pocl: just availability. Existing r used 1.4 and gcc 8.2 (non Cuda) uses 1.3. So given that I rather went with the newer version to avoid problems. Especially if it's something opencl where I guess new versions just have better compatibility. Can change if wanted.

**Comment by Flamefire** [comment]
@lexming Added the Clang EC in https://github.com/easybuilders/easybuild-easyconfigs/pull/11166. It will "shadow" the current Clang EC which might be considered a problem, but I guess as it is an improvement it doesn't matter.

**Comment by Flamefire** [comment]
@lexming Updated pocl to use Clang 8.0.1 and rebased so CI can find it. `eb -Dr` looks good now: No double CUDA

**Comment by Flamefire** [comment]
Test report by @Flamefire
**FAILED**
Build succeeded for 0 out of 2 (2 easyconfigs in this PR)
taurusi5096.taurus.hrsk.tu-dresden.de - Linux RHEL 7.8, x86_64, Intel(R) Xeon(R) CPU E5-2680 v3 @ 2.50GHz, Python 2.7.5
See https://gist.github.com/5b956cfc596405482e4be33346fb4c0a for a full test report.

**Comment by Flamefire** [comment]
Test report by @Flamefire
**FAILED**
Build succeeded for 0 out of 2 (2 easyconfigs in this PR)
taurusml24 - Linux RHEL 7.6, POWER, 8335-GTX, Python 2.7.5
See https://gist.github.com/2357d404630deb592da752fac612e1ae for a full test report.

**Comment by Flamefire** [comment]
Test report by @Flamefire
**FAILED**
Build succeeded for 0 out of 2 (2 easyconfigs in this PR)
taurusml21 - Linux RHEL 7.6, POWER, 8335-GTX, Python 2.7.5
See https://gist.github.com/892925158fe147a733e920ed901ee74a for a full test report.

**Comment by Flamefire** [comment]
Test report by @Flamefire
**FAILED**
Build succeeded for 0 out of 2 (2 easyconfigs in this PR)
taurusi5397.taurus.hrsk.tu-dresden.de - Linux RHEL 7.8, x86_64, Intel(R) Xeon(R) CPU E5-2680 v3 @ 2.50GHz, Python 2.7.5
See https://gist.github.com/055be1dbfb8d8c06a8e2c4664cb4b358 for a full test report.

**Comment by lexming** [comment]
@Flamefire thanks for the update, I started the tests :+1:

**Comment by Flamefire** [comment]
I did too on Power and x86

**Comment by Flamefire** [comment]
Test report by @Flamefire
**FAILED**
Build succeeded for 1 out of 2 (2 easyconfigs in this PR)
taurusi5575.taurus.hrsk.tu-dresden.de - Linux RHEL 7.8, x86_64, Intel(R) Xeon(R) CPU E5-2680 v3 @ 2.50GHz, Python 2.7.5
See https://gist.github.com/5418a09515a385a9cf78d58f3a9ac4ef for a full test report.

**Comment by Flamefire** [comment]
Test report by @Flamefire
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in this PR)
taurusml21 - Linux RHEL 7.6, POWER, 8335-GTX, Python 2.7.5
See https://gist.github.com/d563567bd0939bfc12aa7536b3d871f1 for a full test report.

**Comment by lexming** [comment]
Test report by @lexming
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in this PR)
node157.hydra.os - Linux centos linux 7.7.1908, x86_64, Intel(R) Xeon(R) CPU E5-2680 v2 @ 2.80GHz, Python 2.7.5
See https://gist.github.com/aae6422fccaefd2b4c4c13077e101357 for a full test report.

**Comment by Flamefire** [comment]
Test report by @Flamefire
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in this PR)
taurusa8 - Linux centos linux 7.7.1908, x86_64, Intel(R) Xeon(R) CPU E5-2603 v4 @ 1.70GHz, Python 2.7.5
See https://gist.github.com/79848c709bbb887edf8ee57ad29212cb for a full test report.

**Review by lexming — APPROVED** [review]
LGTM

**Comment by lexming** [comment]
Going in, thanks @Flamefire !

**Pull request merged**
