### PR TITLE
{bio}[foss/2018b] MAGeCK v0.5.9 w/ Python 3.6.6

### PR DESCRIPTION
**Pull request by pescobar**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by verdurin** [comment]
Test report by @verdurin
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
rescomp2 - Linux centos linux 7.3.1611, Intel(R) Xeon(R) Gold 6126 CPU @ 2.60GHz, Python 2.7.5
See https://gist.github.com/d8d18d80d55411f98f94520421f1c714 for a full test report.

**Comment by verdurin** [comment]
@pescobar please add the settings for `pip` and `deps` as mentioned by Travis.

**Comment by verdurin** [comment]
@pescobar If you're around, please attend to the Travis errors.

**Comment by verdurin** [comment]
@pescobar nudge?

**Comment by pescobar** [comment]
Test report by @pescobar
**SUCCESS**
Build succeeded for 0 out of 0 (1 easyconfigs in this PR)
worker01.cluster.bc2.ch - Linux centos linux 7.5.1804, Intel(R) Xeon(R) CPU E5-2630 v4 @ 2.20GHz, Python 2.7.5
See https://gist.github.com/2ec26239cb8fa09724fbc591f687d021 for a full test report.

**Comment by pescobar** [comment]
Test report by @pescobar
**FAILED**
Build succeeded for 0 out of 1 (1 easyconfigs in this PR)
worker01.cluster.bc2.ch - Linux centos linux 7.5.1804, Intel(R) Xeon(R) CPU E5-2630 v4 @ 2.20GHz, Python 2.7.5
See https://gist.github.com/2e941be9943735d5171690ab5e74b4f4 for a full test report.

**Comment by verdurin** [comment]
Test report by @verdurin
**SUCCESS**
Build succeeded for 0 out of 0 (1 easyconfigs in this PR)
rescomp2 - Linux centos linux 7.3.1611, Intel(R) Xeon(R) Gold 6126 CPU @ 2.60GHz, Python 2.7.5
See https://gist.github.com/88d3fce26d6304468a8223063f87082b for a full test report.

**Comment by verdurin** [comment]
Test report by @verdurin
**FAILED**
Build succeeded for 0 out of 1 (1 easyconfigs in this PR)
rescomp2 - Linux centos linux 7.3.1611, Intel(R) Xeon(R) Gold 6126 CPU @ 2.60GHz, Python 2.7.5
See https://gist.github.com/d20a13880c09a70ca73b43b09ba71472 for a full test report.

**Comment by verdurin** [comment]
@pescobar this is the failure in my test:
```
== 2019-08-16 10:19:07,193 run.py:173 DEBUG run_cmd: running cmd  pip install --prefix=/well/rescomp/eb/software/MAGeCK/0.5.9-foss-2018b-Python-3.6.6  --no-deps  --ignore-installed  --no-build-isolation  . (in /dev/shm/adamh/MAGeCK/0.5.9/foss-2018b-Python-3.6.6/mageck-0.5.9)
== 2019-08-16 10:19:07,193 run.py:192 INFO running cmd:  pip install --prefix=/well/rescomp/eb/software/MAGeCK/0.5.9-foss-2018b-Python-3.6.6  --no-deps  --ignore-installed  --no-build-isolation  .
== 2019-08-16 10:19:14,701 build_log.py:163 ERROR EasyBuild crashed with an error (at ?:124 in __init__): cmd " pip install --prefix=/well/rescomp/eb/software/MAGeCK/0.5.9-foss-2018b-Python-3.6.6  --no-deps  --ignore-installed  --no-build-isolation  ." exited with exit code 1 and output:
Processing /dev/shm/adamh/MAGeCK/0.5.9/foss-2018b-Python-3.6.6/mageck-0.5.9
Installing collected packages: mageck
  Running setup.py install for mageck: started
    Running setup.py install for mageck: finished with status 'error'
    Complete output from command /well/rescomp/eb/software/Python/3.6.6-foss-2018b/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/eb-jzZ_Rc/pip-req-build-ln2wlwgf/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/eb-jzZ_Rc/pip-record-94inih44/install-record.txt --single-version-externally-managed --prefix /well/rescomp/eb/software/MAGeCK/0.5.9-foss-2018b-Python-3.6.6 --compile:
    usage: -c [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
       or: -c --help [cmd1 cmd2 ...]
       or: -c --help-commands
       or: -c cmd --help

    error: option --single-version-externally-managed not recognized
```

**Comment by boegel** [comment]
@verdurin Can you verify whether it's picking up the right `pip`? Using `which pip && pip --version &&` in `preinstallopts` for example?

**Comment by boegel** [comment]
Test report by @boegel
**FAILED**
Build succeeded for 0 out of 1 (1 easyconfigs in this PR)
node2608.swalot.os - Linux centos linux 7.6.1810, Intel(R) Xeon(R) CPU E5-2660 v3 @ 2.60GHz, Python 2.7.5
See https://gist.github.com/052c837c4abd97b949a4d9e31c780a11 for a full test report.

**Comment by verdurin** [comment]
@boegel just added those in a local test and it is picking up `pip` `18.0` from the `Python` module.

**Comment by boegel** [comment]
closing this, since `foss/2018b` is now a deprecated toolchain (see https://docs.easybuild.io/en/latest/Deprecated-easyconfigs.html#deprecated-toolchains)

**Pull request closed without merging**
