### PR TITLE
{math}[fosscuda/2018a] Keras v2.1.5

### PR DESCRIPTION
**Pull request by akesandgren**
(created using `eb --new-pr`)
New Keras 2.1.5 version for fosscuda/2018a with TensorFlow/1.8.0 and Theano/1.0.1

This PR uses easyconfigs from PR #6412

### CODE REVIEW

**Comment by boegel** [comment]
@akesandgren The `Pysam` issue in the failing tests is because of an issue introduced in `develop` with #5983, will be fixed with #6491

**Comment by akesandgren** [comment]
@boegel Should we just drop this one now that we just merge Keras 2.2.2?

**Comment by boegel** [comment]
@akesandgren Up to you, since this is a different toolchain. You'll need to downgrade the `Theano` version to make the tests pass here if you still want to pursue this...

**Comment by akesandgren** [comment]
I assume you mean upgrade Theano, but I'll just  close it.

**Comment by boegel** [comment]
Yes, upgrade, sorry (needs more coffee)

**Pull request closed without merging**
