### PR TITLE
Fix Tombo to work with rpy2 v3 when creating DataFrames

### PR DESCRIPTION
**Pull request by branfosj**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by branfosj** [comment]
With `module load rpy2/3.2.6-foss-2019b-Python-3.7.4`:

```
$ python
Python 3.7.4 (default, Nov 20 2019, 14:37:06)
[GCC 8.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from rpy2 import robjects as r
>>> _R_DF = r.DataFrame(())
Traceback (most recent call last):
  File "/rds/bear-apps/2019b/EL7-haswell/software/rpy2/3.2.6-foss-2019b-Python-3.7.4/lib/python3.7/site-packages/rpy2/robjects/vectors.py", line 1204, in __init__
    kv = [(str(k), conversion.py2rpy(v)) for k, v in obj.items()]
AttributeError: 'tuple' object has no attribute 'items'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/rds/bear-apps/2019b/EL7-haswell/software/rpy2/3.2.6-foss-2019b-Python-3.7.4/lib/python3.7/site-packages/rpy2/robjects/vectors.py", line 1207, in __init__
    'obj can only be'
ValueError: obj can only bean instance of rpy2.rinterface.ListSexpVector, an instance of TaggedList, or an objects with a methods items() that returns (key, value) pairs (such a Python dict, rpy2.rlike.container OrdDict).
>>> _R_DF = r.DataFrame({})
```

**Comment by branfosj** [comment]
Test report by @branfosj
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
bear-pg0211u03a.bear.cluster - Linux centos linux 7.8.2003, x86_64, Intel(R) Xeon(R) Gold 6248 CPU @ 2.50GHz (cascadelake), Python 3.6.8
See https://gist.github.com/eaff0972316e4fd4adfa66a9fa40cfea for a full test report.

**Comment by branfosj** [comment]
Test report by @branfosj
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
bear-pg0211u38b.bear.cluster - Linux centos linux 8.2.2004, x86_64, Intel(R) Xeon(R) Gold 6248 CPU @ 2.50GHz (cascadelake), Python 3.6.8
See https://gist.github.com/1d0558772c5ed68b015f96d10aef7237 for a full test report.

**Comment by smoors** [comment]
@boegelbot please test @ generoso

**Comment by boegel** [comment]
@branfosj Don't hesitate to tag bug fix PRs for the "next release" milestone, so we don't overlook them for the next EasyBuild release...

**Review by smoors — APPROVED** [review]
lgtm

**Comment by smoors** [comment]
Going in, thanks @branfosj!

**Comment by boegel** [comment]
Test report by @boegel
**FAILED**
Build succeeded for 9 out of 12 (1 easyconfigs in total)
node3501.doduo.os - Linux RHEL 8.2, x86_64, AMD EPYC 7552 48-Core Processor (zen2), Python 3.6.8
See https://gist.github.com/680fd864a82558dc54b3c78b9218d59c for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 3 out of 3 (1 easyconfigs in total)
node3575.doduo.os - Linux RHEL 8.2, x86_64, AMD EPYC 7552 48-Core Processor (zen2), Python 3.6.8
See https://gist.github.com/7eab3bba0518943986d0feffa1ba79fd for a full test report.

**Pull request merged**
