### PR TITLE
{lang}[system/system] Anaconda3 v2020.11

### PR DESCRIPTION
**Pull request by jhein32**
Version push to latest version 2020.11.  Also supporting PowerPC.

### CODE REVIEW

**Comment by jhein32** [comment]
We have no means of testing the ppc version.

**Review by boegel — APPROVED** [review]
lgtm

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
node3504.doduo.os - Linux RHEL 8.2, x86_64, AMD EPYC 7552 48-Core Processor (zen2), Python 3.6.8
See https://gist.github.com/1067d4f314c9d7901e3d96eb650da763 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
easybuild2.novalocal - Linux centos linux 8.3.2011, POWER, IBM pSeries (emulated by qemu) (power9le), Python 3.6.8
See https://gist.github.com/2ebb5c0352bb8233f877e1f357fc9905 for a full test report.

**Comment by boegel** [comment]
@boegelbot please test @ generoso

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
node3134.skitty.os - Linux centos linux 7.9.2009, x86_64, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz, Python 3.6.8
See https://gist.github.com/5665452a8a98feeaf2d447b5e8c7777a for a full test report.

**Comment by boegel** [comment]
Going in, thanks @jhein32!

**Pull request merged**
