### PR TITLE
install scikit-learn 0.23.1 as a bundle and include required threadpoolctl extension

### PR DESCRIPTION
**Pull request by boegel**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
node2583.golett.os - Linux centos linux 7.8.2003, x86_64, Intel(R) Xeon(R) CPU E5-2680 v3 @ 2.50GHz (haswell), Python 2.7.5
See https://gist.github.com/c30becffa4c5b255d5e3d87670010112 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
generoso - Linux centos linux 8.2.2004, x86_64, Intel(R) Xeon(R) CPU E5-2667 v3 @ 3.20GHz (haswell), Python 3.6.8
See https://gist.github.com/e670062b47807e1aa57078f4eb1076ca for a full test report.

**Comment by boegel** [comment]
I noticed that `threadpoolctl` was missing when `pip check` was failing when installing `pySCENIC` (which depends on `scikit-learn`, PR coming soon).

It's unclear to me why `pip check` doesn't barf when installing `scikit-learn` itself, but I'm guessing that has something to do with not properly registering the dependency (they're using some how grown approach it seems, see https://github.com/scikit-learn/scikit-learn/blob/master/sklearn/_build_utils/min_dependencies.py).

**Comment by boegel** [comment]
Turns out this was overlooked due to a bug in `PythonPackage`, see https://github.com/easybuilders/easybuild-easyblocks/pull/2114...

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
node3411.kirlia.os - Linux centos linux 7.8.2003, x86_64, Intel(R) Xeon(R) Gold 6240 CPU @ 2.60GHz (cascadelake), Python 2.7.5
See https://gist.github.com/821e922fb686bb1b3a3dd86c9f78f095 for a full test report.

**Comment by boegel** [comment]
Last test report was on top of the fixed `PythonPackage` easyblock rom #2114 (but this PR doesn't require that one).

**Comment by boegel** [comment]
This is not an issue for previous scikit-learn versions (`scikit-learn-0.21.3-foss-2019b-Python-3.7.4.eb` for example), because `threadpoolctl` is a new dependency.

**Comment by smoors** [comment]
Test report by @smoors
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
node254.hydra.os - Linux centos linux 7.7.1908, x86_64, Intel(R) Xeon(R) CPU E5-2683 v4 @ 2.10GHz (broadwell), Python 2.7.5
See https://gist.github.com/6f7ee46afaa346debb3beec31e069254 for a full test report.

**Comment by migueldiascosta** [comment]
Test report by @migueldiascosta
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
sms - Linux centos linux 7.6.1810, x86_64, AMD EPYC 7601 32-Core Processor (zen), Python 2.7.5
See https://gist.github.com/dad76c08cfdd83ef125375ab12044688 for a full test report.

**Comment by smoors** [comment]
Going in, thanks @boegel!

**Pull request merged**
