### PR TITLE
{chem}[foss/2023a] Critic2 v1.2

### PR DESCRIPTION
**Pull request by appolloford**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by appolloford** [comment]
Test report by @appolloford
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
vera-skylake-build - Linux Rocky Linux 8.9, x86_64, Intel Xeon Processor (Skylake, IBRS, no TSX), Python 3.6.8
See https://gist.github.com/appolloford/18449362e763bae23d0ad5f9ede88930 for a full test report.

**Comment by Micket** [comment]
@boegelbot please test @ generoso

**Review by Micket — APPROVED** [review]
lgtm

**Comment by Micket** [comment]
@boegelbot please test @ jsc-zen3

**Comment by Micket** [comment]
Going in, thanks @appolloford!

**Pull request merged**
