### PR TITLE
{lib}[GCC/11.2.0] nghttp2 v1.48.0 w/ Python 3.9.6

### PR DESCRIPTION
**Pull request by sassy-crick**
(created using `eb --new-pr`)

Requires:
- [x] PR #16086
- [x] PR #16097
- [x] PR #16098
- [x] PR #16053

### CODE REVIEW

**Comment by zao** [comment]
@sassy-crick This PR seems to depend on the wrong version of Jansson, there's `Jansson-2.13.1-GCC-11.2.0.eb` for this toolchain and `Jansson-2.14-GCC-11.3.0.eb` for the next one.

**Comment by sassy-crick** [comment]
> @sassy-crick This PR seems to depend on the wrong version of Jansson, there's `Jansson-2.13.1-GCC-11.2.0.eb` for this toolchain and `Jansson-2.14-GCC-11.3.0.eb` for the next one.

@zao That was my wrong: whilst building all of that rather large software tree, I also created on EC file for the version I was using here. I have corrected that. Apologies for that.

**Comment by zao** [comment]
Test report by @zao
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
eb-u2204 - Linux Ubuntu 22.04, x86_64, AMD Ryzen 9 3900X 12-Core Processor, Python 3.10.4
See https://gist.github.com/6188ad3f5ef6c7e3b35e6b4ffd85a35c for a full test report.

**Comment by boegel** [comment]
@boegelbot please test @ generoso

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 2 out of 2 (1 easyconfigs in total)
node3144.skitty.os - Linux RHEL 8.4, x86_64, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz (skylake_avx512), Python 3.6.8
See https://gist.github.com/4e2723b7efc68d1c8d1930b1a59cd54c for a full test report.

**Review by boegel — APPROVED** [review]
lgtm

**Comment by boegel** [comment]
Going in, thanks @sassy-crick!

**Pull request merged**
