### PR TITLE
{bio}[GCCcore 10.3.0] InterProScan 5.52-86.0

### PR DESCRIPTION
**Pull request by hajgato**

### CODE REVIEW

**Comment by verdurin** [comment]
@boegelbot please test @ generoso

**Comment by hajgato** [comment]
The source is quite big (as well as the finally installed stuff):
```
-rw-r--r-- 1 vsc40023 geasybuild  15G Jul  7 14:51 panther-data-15.0.tar.gz
-rw-r----- 1 vsc40023 geasybuild 7.4G Jul  7 14:51 interproscan-5.52-86.0-64-bit.tar.gz
```

**Comment by hajgato** [comment]
from https://interproscan-docs.readthedocs.io/en/latest/UserDocs.html

```
Panther models

Previous versions of InterProScan required a separate installation of Panther data.
Starting with interproscan-5.52-86.0 onwards, this is not necessary.
Panther data is bundled together with the rest of the application data.
```

**Comment by boegel** [comment]
@hajgato You told me there was a problem with this version of InterProScan, can you briefly explain what that was?

The installation problem by the bot was because `/tmp` isn't large enough which is used for the build directory, that's fixed by using `eb --buildpath $HOME/build` for example.

**Comment by hajgato** [comment]
The user reported that `pfsearchV3` and `pfscanV3` stops with error message:
```
Error setting affinity!
```

Despite the patch (use `--no-affinity` , the problem persists)
```
[vsc43020@gligar05 ~]$ $EBROOTINTERPROSCAN/bin/prosite/pfsearchV3 --help | grep no.affinity
   --no-affinity                           : disable CPU affinity file
[vsc43020@gligar05 ~]$ $EBROOTINTERPROSCAN/bin/prosite/pfscanV3 --help | grep no.affinity
   --no-affinity                           : disable CPU affinity file
```

`pfscanV3` and `pfsearchV3` provided as binary, maybe compiling them locally (and maybe patching) could solve this problem, but right now I do not have interest to try it. (The user was working in slurm environment, it might also affect the result)

**Comment by hajgato** [comment]
problem and solution for it described: https://github.com/ebi-pf-team/interproscan/issues/231#issuecomment-1042869512

**Comment by boegel** [comment]
@boegelbot please test @ generoso

**Review by boegel — APPROVED** [review]

**Pull request merged**
