### PR TITLE
{bio}[intel/2018a] Bowtie v1.1.2

### PR DESCRIPTION
**Pull request by boegel**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
node2404.golett.os - Linux centos linux 7.4.1708, Intel(R) Xeon(R) CPU E5-2680 v3 @ 2.50GHz, Python 2.7.5
See https://gist.github.com/9ff164735f6db7e831fa6f5e114ac12f for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
gligar03.gligar.os - Linux centos linux 7.4.1708, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.7.5
See https://gist.github.com/7958ad5c787070f62b235dae06ea9040 for a full test report.

**Comment by vanzod** [comment]
@boegel In `intel/2018a` there is already `Bowtie/1.2.2`. 
Is there a specific reason we need an older version?

**Comment by boegel** [comment]
@vanzod A user ran into problems when combining TopHat with Bowtie 1.2.2, while the combo with 1.1.2 does work. See also https://github.com/infphilo/tophat/issues/51

**Comment by vanzod** [comment]
Test report by @vanzod
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
cermis - Linux debian 9.4, Intel(R) Xeon(R) CPU           E5620  @ 2.40GHz, Python 2.7.13
See https://gist.github.com/63a2f61eb7790bf228a273a69370df4e for a full test report.

**Comment by vanzod** [comment]
Going in, thanks @boegel!

**Pull request merged**
