### PR TITLE
Add Tkinter sanity check to ASE (foss toolchain).

### PR DESCRIPTION
**Pull request by schiotz**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by schiotz** [comment]
Added sanity check for the GUI: Tkinter should be present, as discussed in PR #5658 
One of the easyconfigs in this PR will only build if PR #5689 has been merged/installed.

**Comment by schiotz** [comment]
Test report by @schiotz
**SUCCESS**
Build succeeded for 4 out of 4 (4 easyconfigs in this PR)
thul.fysik.dtu.dk - Linux centos linux 7.4.1708, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.7.5
See https://gist.github.com/ef6a1df375dcf6f662b6ccc1d10fe1ac for a full test report.

**Comment by schiotz** [comment]
Closing and reopening to rerun the checks.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 4 out of 4 (4 easyconfigs in this PR)
node2316.phanpy.os - Linux centos linux 7.4.1708, Intel(R) Xeon(R) CPU E5-2680 v3 @ 2.50GHz, Python 2.7.5
See https://gist.github.com/a0fb38827825307e129da44f6f1f3499 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 4 out of 4 (4 easyconfigs in this PR)
node2111.delcatty.os - Linux centos linux 7.4.1708, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.7.5
See https://gist.github.com/ac1257de6abc52cf70b74a364a986359 for a full test report.

**Comment by boegel** [comment]
Going in, thanks @schiotz!

**Pull request merged**
