### PR TITLE
{lang}[GCCcore/6.4.0] Perl v5.26.0

### PR DESCRIPTION
**Pull request by boegel**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
node2109.delcatty.os - Linux centos linux 7.3.1611, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.7.5
See https://gist.github.com/d8d4b9868365e351aafec8a383633c28 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
node2470.golett.os - Linux centos linux 7.3.1611, Intel(R) Xeon(R) CPU E5-2680 v3 @ 2.50GHz, Python 2.7.5
See https://gist.github.com/2752497bf33b25667d094d23141d709e for a full test report.

**Comment by verdurin** [comment]
Could be related to the ongoing network problems here, but I'm seeing problems with source download for this:
```
eb --from-pr=5126 --prefix=/camp/apps/eb/review  -d --robot=./ --buildpath=/dev/shm --upload-test-report
Please enter password for encrypted keyring:
== temporary log file in case of crash /home/camp/huffmaa/tmp/eb-2oYncp/easybuild-k6CRi5.log

*** WARNING: Using easyconfigs from unstable (pending/failed tests or merge conflict) PR #5126 ***

== resolving dependencies ...
== processing EasyBuild easyconfig /home/camp/huffmaa/tmp/eb-2oYncp/files_pr5126/p/Perl/Perl-5.26.0-GCCcore-6.4.0.eb
== building and installing Perl/5.26.0-GCCcore-6.4.0...
== fetching files...
== FAILED: Installation ended unsuccessfully (build directory: /dev/shm/Perl/5.26.0/GCCcore-6.4.0): build failed (first 300 chars): Checksum for ext source Config-General-2.63.tar.gz failed
== Results of the build can be found in the log file(s) /home/camp/huffmaa/tmp/eb-2oYncp/easybuild-Perl-5.26.0-20170918.151135.zlIuj.log
Traceback (most recent call last):
  File "/usr/lib64/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib64/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/camp/apps/eb/software/EasyBuild/3.2.1/lib/python2.7/site-packages/easybuild_framework-3.2.1-py2.7.egg/easybuild/main.py", line 475, in <module>
    main()
  File "/camp/apps/eb/software/EasyBuild/3.2.1/lib/python2.7/site-packages/easybuild_framework-3.2.1-py2.7.egg/easybuild/main.py", line 456, in main
    test_report_msg = overall_test_report(ecs_with_res, len(paths), overall_success, success_msg, init_session_state)
  File "/camp/apps/eb/software/EasyBuild/3.2.1/lib/python2.7/site-packages/easybuild_framework-3.2.1-py2.7.egg/easybuild/tools/testing.py", line 298, in overall_test_report
    txt = post_easyconfigs_pr_test_report(pr_nr, test_report, msg, init_session_state, success)
  File "/camp/apps/eb/software/EasyBuild/3.2.1/lib/python2.7/site-packages/easybuild_framework-3.2.1-py2.7.egg/easybuild/tools/testing.py", line 274, in post_easyconfigs_pr_test_report
    post_comment_in_issue(pr_nr, comment, github_user=user)
  File "/camp/apps/eb/software/EasyBuild/3.2.1/lib/python2.7/site-packages/easybuild_framework-3.2.1-py2.7.egg/easybuild/tools/github.py", line 451, in post_comment_in_issue
    status, data = pr_url.comments.post(body={'body': txt})
  File "/camp/apps/eb/software/EasyBuild/3.2.1/lib/python2.7/site-packages/vsc_base-2.5.8-py2.7.egg/vsc/utils/rest.py", line 144, in post
    return self.request(self.POST, url, json.dumps(body), headers, content_type='application/json')
  File "/camp/apps/eb/software/EasyBuild/3.2.1/lib/python2.7/site-packages/vsc_base-2.5.8-py2.7.egg/vsc/utils/rest.py", line 175, in request
    conn = self.get_connection(method, url, body, headers)
  File "/camp/apps/eb/software/EasyBuild/3.2.1/lib/python2.7/site-packages/vsc_base-2.5.8-py2.7.egg/vsc/utils/rest.py", line 206, in get_connection
    connection = self.opener.open(request)
  File "/usr/lib64/python2.7/urllib2.py", line 437, in open
    response = meth(req, response)
  File "/usr/lib64/python2.7/urllib2.py", line 550, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib64/python2.7/urllib2.py", line 469, in error
    result = self._call_chain(*args)
  File "/usr/lib64/python2.7/urllib2.py", line 409, in _call_chain
    result = func(*args)
  File "/usr/lib64/python2.7/urllib2.py", line 635, in http_error_302
    new = self.redirect_request(req, fp, code, msg, headers, newurl)
  File "/usr/lib64/python2.7/urllib2.py", line 596, in redirect_request
    raise HTTPError(req.get_full_url(), code, msg, headers, fp)
urllib2.HTTPError: HTTP Error 307: Temporary Redirect
```

**Comment by wpoely86** [comment]
Test report by @wpoely86
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
nic68 - Linux centos linux 7.3.1611, Intel(R) Xeon(R) CPU E5-2680 v4 @ 2.40GHz, Python 2.7.5
See https://gist.github.com/cef51a840441aba8f8cc4b6c231ca322 for a full test report.

**Comment by boegel** [comment]
@verdurin Please retry when connectivity issues on your end have been fixed?

**Comment by verdurin** [comment]
@boegel - problem fixed and another test build running now.

**Comment by verdurin** [comment]
Test report by @verdurin
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
ca021.camp.thecrick.org - Linux centos linux 7.3.1611, Intel(R) Xeon(R) CPU E5-2640 v3 @ 2.60GHz, Python 2.7.5
See https://gist.github.com/0077daca6ce6a4a5d12d1f2648a5836d for a full test report.

**Comment by verdurin** [comment]
Going in, thanks @boegel!

**Pull request merged**
