### PR TITLE
{chem}[GCC/11.3.0] TRAVIS-Analyzer v220729

### PR DESCRIPTION
**Pull request by lexming**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by lexming** [comment]
@boegelbot: please test @ generoso

**Comment by lexming** [comment]
@boegelbot please test @ jsc-zen2

**Review by casparvl — COMMENTED** [review]
Looks good, the only thing I'm wondering is: why is this at the level of the `GCC` toolchain, and not at `GCCcore`?

(see https://github.com/easybuilders/easybuild/wiki/Review-process-for-contributions#toolchain)

**Comment by casparvl** [comment]
Test report by @casparvl
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
tcn1.local.snellius.surf.nl - Linux RHEL 8.6, x86_64, AMD EPYC 7H12 64-Core Processor, Python 3.6.8
See https://gist.github.com/casparvl/6c687d9c59623d8238bc5c90bff31ca9 for a full test report.

**Comment by lexming** [comment]
@casparvl there is no Fortran in this code, just C++, but my thought was that this is still an application where performance is important so maybe somebody wants to run this with intel compilers. I have no strong opinion on it though, if you prefer it at GCCcore level, let me know and I'll move it down.

**Comment by casparvl** [comment]
Well, I don't have very strong feelings about it either. But: at least you seem to have put it at GCC level by conscious choice. That's enough for me. Let's merge it like this. Future maintainers are welcome to disagree with us and change things, but I'm fine with it ;-)

**Review by casparvl — APPROVED** [review]
Lgtm!

**Comment by casparvl** [comment]
Going in, thanks @lexming!

**Pull request merged**
