### PR TITLE
{bio}[foss/2020b] BRAKER v2.1.6

### PR DESCRIPTION
**Pull request by boegel**
(created using `eb --new-pr`)
requires:
* #16155
* #17468

### CODE REVIEW

**Comment by boegel** [comment]
@boegelbot please test @ generoso

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
node3127.skitty.os - Linux RHEL 8.4, x86_64, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz (skylake_avx512), Python 3.6.8
See https://gist.github.com/53eefa0fdc06a2a10d14ff7419dca6aa for a full test report.

**Comment by jfgrimm** [comment]
@boegel trying to run `example/tests/test1.sh` I'm running into several issues.

- it wants a [writeable AUGUSTUS config](https://github.com/Gaius-Augustus/BRAKER#augustus). we should perhaps add a `modloadmsg` asking the user to copy `$EBROOTAUGUSTUS/config` to some local directory, and set `AUGUSTUS_CONFIG_PATH=/path/to/local/config`
- we're missing some dependencies: 
    - optional: `cdbtools` (`cdbfasta`, `cdbyank`), `GUSHR`
    - mandatory: `ProtHint`
- `[GenomeThreader](https://github.com/Gaius-Augustus/BRAKER#genomethreader)` and `[Exonerate](https://github.com/Gaius-Augustus/BRAKER#exonerate)` support is depracated

**Comment by boegel** [comment]
There's actually another problem: `BRAKER` assumes that `Math::Utils` is available, and we currently don't install that with our Perl yet (that's being fixed in #17466)

**Comment by boegel** [comment]
PR for ProtHint opened @ #17468

**Comment by boegel** [comment]
closing this since `foss/2020b` is deprecated, see https://docs.easybuild.io/policies/toolchains

**Pull request closed without merging**
