### PR TITLE
{mpi}[GCC/10.2.0] OpenMPI v4.1.0

### PR DESCRIPTION
**Pull request by boegel**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by boegel** [comment]
@boegelbot please test @ generoso

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
node3501.doduo.os - Linux RHEL 8.2, x86_64, AMD EPYC 7552 48-Core Processor (zen2), Python 3.6.8
See https://gist.github.com/3eeade0a6db55b1504f7d283a5c9858e for a full test report.

**Review by bartoldeman — APPROVED** [review]
lgtm

**Comment by bartoldeman** [comment]
Test report by @bartoldeman
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
build-node.computecanada.ca - Linux centos linux 7.9.2009, x86_64, Intel Xeon Processor (Skylake, IBRS), Python 3.7.7
See https://gist.github.com/b6468f0503772daa0691b42f745aa65f for a full test report.

**Comment by bartoldeman** [comment]
Going in, thanks @boegel!

**Pull request merged**
