### PR TITLE
[foss/2023a] dependencies for RoseTTAFold-All-Atom

### PR DESCRIPTION
**Pull request by pavelToman**
(created using `eb --new-pr`)

For RoseTTAFold-All-Atom: 
- https://github.com/vscentrum/vsc-software-stack/issues/327

### CODE REVIEW

**Comment by pavelToman** [comment]
@boegelbot please test @ generoso

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 22 out of 22 (22 easyconfigs in total)
node3120.skitty.os - Linux RHEL 8.8, x86_64, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz, Python 3.6.8
See https://gist.github.com/boegel/31908ad06c785df1c82186e0992df447 for a full test report.

**Review by boegel — APPROVED** [review]
lgtm

**Comment by branfosj** [comment]
This introduced a second `libidn2` in `GCCcore/12.3.0`. See #20771 for removing it and updating `GnuTLS`.

**Pull request merged**
