### PR TITLE
{bio}[foss/2020a] MRtrix v3.0.0 w/ Python 3.8.2

### PR DESCRIPTION
**Pull request by bedroge**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by bedroge** [comment]
Test report by @bedroge
**FAILED**
Build succeeded for 0 out of 1 (1 easyconfigs in this PR)
build.hpc.rug.nl - Linux centos linux 7.4.1708, Intel(R) Xeon(R) CPU E5-2660 0 @ 2.20GHz, Python 2.7.5
See https://gist.github.com/4ed789ae5fc640b0cf9568b029b35088 for a full test report.

**Comment by bedroge** [comment]
Hmmm... so it did pass all the checks here, and it also built without issues on three types of compute nodes. It just failed on the build host that I used to make the PR and send a test report.

**Comment by bedroge** [comment]
Test report by @bedroge
**FAILED**
Build succeeded for 0 out of 1 (1 easyconfigs in this PR)
build.hpc.rug.nl - Linux centos linux 7.7.1908, Intel(R) Xeon(R) CPU E5-2660 0 @ 2.20GHz, Python 2.7.5
See https://gist.github.com/a4d3b0ee22b6846b327169ecacf9e3dd for a full test report.

**Comment by bedroge** [comment]
Test report by @bedroge
**FAILED**
Build succeeded for 0 out of 1 (1 easyconfigs in this PR)
build.hpc.rug.nl - Linux centos linux 7.7.1908, Intel(R) Xeon(R) CPU E5-2660 0 @ 2.20GHz, Python 2.7.5
See https://gist.github.com/48ed64fea49af12278c6342483d260de for a full test report.

**Comment by Micket** [comment]
Hm, well doesn't looks like it has anything to do with the software building itself:
```
== 2020-05-27 13:08:21,175 easyblock.py:3187 WARNING build failed (first 300 chars): Lock /software/software/.locks/_software_software_MRtrix_3.0.0-foss-2020a-Python-3.8.2.lock already exists, aborting!
```

**Comment by bedroge** [comment]
Yes, sorry, ignore those last two attempts. Tried to do it again, but they failed for other reasons. I'm now rebuilding it again, hope it works this time.

**Comment by Micket** [comment]
Test report by @Micket
**FAILED**
Build succeeded for 11 out of 13 (1 easyconfigs in this PR)
hebbe-c1 - Linux centos linux 7.7.1908, x86_64, Intel Core Processor (Haswell, no TSX), Python 2.7.5
See https://gist.github.com/4e3b02955e90501cd2e5315c2887f9da for a full test report.

**Comment by bedroge** [comment]
Test report by @bedroge
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
build.hpc.rug.nl - Linux centos linux 7.7.1908, Intel(R) Xeon(R) CPU E5-2660 0 @ 2.20GHz, Python 2.7.5
See https://gist.github.com/fc266898c8f31858ffa47867722c993a for a full test report.

**Comment by bedroge** [comment]
Tried it again on the same build host, but this time in a clean/minimal Singularity container. That worked, so I guess some OS library was interfering in the other attempt.

**Comment by Micket** [comment]
My Qt5 build failed, might have run out of diskspace or ram or something. I will check back on this later

**Comment by Micket** [comment]
Test report by @Micket
**FAILED**
Build succeeded for 0 out of 2 (1 easyconfigs in this PR)
hebbe-c1 - Linux centos linux 7.7.1908, x86_64, Intel Core Processor (Haswell, no TSX), Python 2.7.5
See https://gist.github.com/82dcef12942786ad08881f76a1fb373c for a full test report.

**Comment by verdurin** [comment]
Test report by @verdurin
**SUCCESS**
Build succeeded for 2 out of 2 (1 easyconfigs in this PR)
easybuild.novalocal - Linux centos linux 7.8.2003, x86_64, Intel Xeon Processor (Skylake, IBRS), Python 2.7.5
See https://gist.github.com/8135f350c0ad71277207cc3e04f478fa for a full test report.

**Comment by Micket** [comment]
Going in, thanks @bedroge!

**Pull request merged**
