### PR TITLE
Remove GLog and GFlags from PyTorch 1.4.0

### PR DESCRIPTION
**Pull request by Flamefire**
As discussed in Slack and confirmed in https://github.com/pytorch/pytorch/issues/44948 using those 2 is not officially tested and known to cause problems at least on POWER architectures

Hence the removal

### CODE REVIEW

**Comment by Flamefire** [comment]
Test report by @Flamefire
**FAILED**
Build succeeded for 1 out of 2 (2 easyconfigs in this PR)
taurusml17 - Linux RHEL 7.6, POWER, 8335-GTX, Python 2.7.5
See https://gist.github.com/cc479cd44db9416b8832c041685e239b for a full test report.

**Comment by Flamefire** [comment]
Test report by @Flamefire
**SUCCESS**
Build succeeded for 3 out of 3 (2 easyconfigs in this PR)
taurusi5532.taurus.hrsk.tu-dresden.de - Linux RHEL 7.8, x86_64, Intel(R) Xeon(R) CPU E5-2680 v3 @ 2.50GHz, Python 2.7.5
See https://gist.github.com/6b03133c380c7f31b4b015c1403c5fbc for a full test report.

**Review by boegel — APPROVED** [review]
lgtm

**Comment by boegel** [comment]
@boegelbot please test @ generoso

**Comment by Flamefire** [comment]
The failures on Power seems to be cause by OpenMP using code and go away with reducing OMP_NUM_THREADS but I already do that... Strange, so I guess still a bit flaky even with only 4 OMP threads

**Comment by boegel** [comment]
@Flamefire failing test on POWER?

**Comment by Flamefire** [comment]
Test report by @Flamefire
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in this PR)
taurusml21 - Linux RHEL 7.6, POWER, 8335-GTX, Python 2.7.5
See https://gist.github.com/994335e389ecd40f77bacc15f9bc10f5 for a full test report.

**Comment by Flamefire** [comment]
:shrug: Seems to work

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in this PR)
node2561.golett.os - Linux centos linux 7.8.2003, x86_64, Intel(R) Xeon(R) CPU E5-2680 v3 @ 2.50GHz (haswell), Python 2.7.5
See https://gist.github.com/31c91f40257783cfd7846f84a12239ef for a full test report.

**Comment by boegel** [comment]
Going in, thanks @Flamefire!

**Comment by lexming** [comment]
Test report by @lexming
**FAILED**
Build succeeded for 1 out of 2 (2 easyconfigs in this PR)
node157.hydra.os - Linux centos linux 7.7.1908, x86_64, Intel(R) Xeon(R) CPU E5-2680 v2 @ 2.80GHz, Python 2.7.5
See https://gist.github.com/b9948bc5cd09fea992185c79272343b2 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in this PR)
node3404.kirlia.os - Linux centos linux 7.8.2003, x86_64, Intel(R) Xeon(R) Gold 6240 CPU @ 2.60GHz (cascadelake), Python 2.7.5
See https://gist.github.com/1107eccdbb2d86e9b2f647a8f6eace59 for a full test report.

**Pull request merged**
