### PR TITLE
{bio}[gompi/2022b] HISAT2 v2.2.1, SRA-Toolkit v3.0.5, file v5.43

### PR DESCRIPTION
**Pull request by verdurin**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by verdurin** [comment]
@boegelbot please test @ generoso

**Comment by verdurin** [comment]
@boegelbot please test @ jsc-zen3

**Review by migueldiascosta — APPROVED** [review]
lgtm

**Comment by migueldiascosta** [comment]
Going in, thanks @verdurin!

**Pull request merged**
