### PR TITLE
{chem}[system/system] ADF v2019.303

### PR DESCRIPTION
**Pull request by mvsurf**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by boegel** [comment]
I don't have access to the sources for this, so I'd like to see a test report from you @mvsurf...

Also, why is this targeting the `2020a` branch, there's no need?

**Comment by mvsurf** [comment]
Test report by @mvsurf
**FAILED**
Build succeeded for 0 out of 1 (1 easyconfigs in this PR)
tcn900.bullx - Linux RHEL 7.7, x86_64, Intel(R) Xeon(R) CPU E5-2690 v3 @ 2.60GHz, Python 2.7.5
See https://gist.github.com/25be03a6d20c7eb94a8cc5a394decce2 for a full test report.

**Comment by mvsurf** [comment]
Test report by @mvsurf
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
tcn900.bullx - Linux RHEL 7.7, x86_64, Intel(R) Xeon(R) CPU E5-2690 v3 @ 2.60GHz, Python 2.7.5
See https://gist.github.com/287cdea62186d337af8881ea9395473f for a full test report.

**Comment by mvsurf** [comment]
Test report uploaded. 
@boegel I did target the 2020a branch  since ADF was in the wishlist for the 2020a no other reason. Should I change it to develop?

**Comment by boegel** [comment]
close/re-open to wake up Travis...

**Comment by boegel** [comment]
I doesn't make much sense to target the `2020a` branch for this, that was mostly for easyconfigs using the `2020a` toolchains (which were still a bit in flux when we started this effort).

I'm happy to merge it, but we'll need a new PR to `develop` anyway specifically for ADF (since the sources are no freely available we'll need a test report from you for it).

**Comment by mvsurf** [comment]
I'm opened a new PR in the develop branch: https://github.com/easybuilders/easybuild-easyconfigs/pull/10647

Closing this one.

**Pull request closed without merging**
