### PR TITLE
{data}[intel/2018a] BDBag v1.4.1 w/ Python 3.6.4

### PR DESCRIPTION
**Pull request by boegel**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
node2599.golett.os - Linux centos linux 7.5.1804, Intel(R) Xeon(R) CPU E5-2680 v3 @ 2.50GHz, Python 2.7.5
See https://gist.github.com/a258acebe7df4640c90bd253d20a9523 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
node3221.victini.os - Linux centos linux 7.5.1804, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz, Python 2.7.5
See https://gist.github.com/2d1815f8ca0e632b815613c4799fa547 for a full test report.

**Comment by tovrstra** [comment]
LGTM

**Comment by verdurin** [comment]
Test report by @verdurin
**FAILED**
Build succeeded for 7 out of 9 (1 easyconfigs in this PR)
rescomp2 - Linux centos linux 7.3.1611, Intel(R) Xeon(R) Gold 6126 CPU @ 2.60GHz, Python 2.7.11
See https://gist.github.com/3029f939551ee8418fbbbf03db604ddc for a full test report.

**Comment by boegel** [comment]
@verdurin fixed in #6892

**Comment by verdurin** [comment]
Test report by @verdurin
**FAILED**
Build succeeded for 1 out of 2 (1 easyconfigs in this PR)
rescomp2 - Linux centos linux 7.3.1611, Intel(R) Xeon(R) Gold 6126 CPU @ 2.60GHz, Python 2.7.11
See https://gist.github.com/3454bb596af8d75f774590ddbdcf4a10 for a full test report.

**Comment by verdurin** [comment]
Test report by @verdurin
**FAILED**
Build succeeded for 0 out of 1 (1 easyconfigs in this PR)
rescomp2 - Linux centos linux 7.3.1611, Intel(R) Xeon(R) Gold 6126 CPU @ 2.60GHz, Python 2.7.11
See https://gist.github.com/dec7229f0d259f31ceb794c1acd6a709 for a full test report.

**Comment by verdurin** [comment]
```
== 2018-09-30 08:33:11,098 run.py:542 DEBUG Using default regular expression: (?<![(,-]|\w)(?:error|segmentation fault|failed)(?![(,-]|\.?\w)
== 2018-09-30 08:33:11,099 run.py:173 DEBUG run_cmd: running cmd  /well/rescomp/eb/software/Python/3.6.4-intel-2018a/bin/python setup.py build  (in /dev/shm/BDBag/1.4.1/intel-2018a-Python-3.6.4/tzlocal/tzlocal-2.0.0b1)
== 2018-09-30 08:33:11,099 run.py:192 INFO running cmd:  /well/rescomp/eb/software/Python/3.6.4-intel-2018a/bin/python setup.py build  
== 2018-09-30 08:33:13,223 build_log.py:158 ERROR EasyBuild crashed with an error (at ?:124 in __init__): cmd " /well/rescomp/eb/software/Python/3.6.4-intel-2018a/bin/python setup.py build " exited with exit code 1 and output:
Traceback (most recent call last):
  File "setup.py", line 8, in <module>
    long_description=open('README.rst', 'rt').read() + '\n\n' + open('CHANGES.txt', 'rt').read(),
  File "/well/rescomp/eb/software/Python/3.6.4-intel-2018a/lib/python3.6/encodings/ascii.py", line 26, in decode
    return codecs.ascii_decode(input, self.errors)[0]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 2873: ordinal not in range(128)
 (at easybuild/tools/run.py:501 in parse_cmd_output)
== 2018-09-30 08:33:13,223 easyblock.py:2776 WARNING build failed (first 300 chars): cmd " /well/rescomp/eb/software/Python/3.6.4-intel-2018a/bin/python setup.py build " exited with exit code 1 and output:
Traceback (most recent call last):
  File "setup.py", line 8, in <module>
    long_description=open('README.rst', 'rt').read() + '\n\n' + open('CHANGES.txt', 'rt').read(),
  File 
```

**Comment by tovrstra** [comment]
@verdurin I had similar issues at some point. Ironically, the problem is that the `README.rst` file contains an UTF-8 character, causing the trouble you see. By clearing the `LANG` and `LC_ALL` variables this was fixed.

**Comment by akesandgren** [comment]
Kicking Travis due to changes in EasyBuild testing

**Comment by akesandgren** [comment]
Travis kicked

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
node2065.delcatty.os - Linux centos linux 7.6.1810, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.7.5
See https://gist.github.com/56e436db1a6dec2b0dac57c814df3294 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
node2700.swalot.os - Linux centos linux 7.6.1810, Intel(R) Xeon(R) CPU E5-2660 v3 @ 2.60GHz, Python 2.7.5
See https://gist.github.com/08a1aef3cf5b23a6ef679347e8e082b5 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
node3108.skitty.os - Linux centos linux 7.8.2003, x86_64, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz, Python 3.6.8
See https://gist.github.com/9601839454dadbbc8e200055ca92e370 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
node3108.skitty.os - Linux centos linux 7.8.2003, x86_64, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz, Python 3.6.8
See https://gist.github.com/9b538211d7c3d2047f965ab5e719a1d0 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
node2603.swalot.os - Linux centos linux 7.8.2003, x86_64, Intel(R) Xeon(R) CPU E5-2660 v3 @ 2.60GHz (haswell), Python 2.7.5
See https://gist.github.com/a91e594b5663dfbff57a039be84e928c for a full test report.

**Comment by akesandgren** [comment]
Test report by @akesandgren
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
b-an03.hpc2n.umu.se - Linux ubuntu 16.04, x86_64, Intel(R) Xeon(R) CPU E5-2690 v4 @ 2.60GHz, Python 2.7.12
See https://gist.github.com/d0cdabd2d696c7f72c8f039f76579326 for a full test report.

**Review by Micket — APPROVED** [review]
lgtm

**Comment by Micket** [comment]
Going in, thanks @boegel!

**Pull request merged**
