### PR TITLE
make sure that VTK 9.0.1 links to libpython by configuring with -DVTK_PYTHON_OPTIONAL_LINK=OFF

### PR DESCRIPTION
**Pull request by boegel**
(created using `eb --new-pr`)

Fixes on top of #12461

@branfosj Since you merged that PR, can you take a look at this one too?

### CODE REVIEW

**Comment by boegel** [comment]
@boegelbot please test @ generoso
CORE_COUNT=16

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
node3121.skitty.os - Linux centos linux 7.9.2009, x86_64, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz, Python 3.6.8
See https://gist.github.com/38cef2a89e6cd60774fbda47bd16d426 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
node3570.doduo.os - Linux RHEL 8.2, x86_64, AMD EPYC 7552 48-Core Processor (zen2), Python 3.6.8
See https://gist.github.com/ffca13267f100229432f9d7a0e01b6a0 for a full test report.

**Comment by branfosj** [comment]
Test report by @branfosj
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
bear-pg0306u07a.bear.cluster - Linux RHEL 8.3, POWER, 8335-GTX (power9le), Python 3.6.8
See https://gist.github.com/7ab630f3c6921661f330a7c7d07ee4b8 for a full test report.

**Comment by smoors** [comment]
Test report by @smoors
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
node351.hydra.os - Linux centos linux 7.9.2009, x86_64, Intel(R) Xeon(R) Gold 6148 CPU @ 2.40GHz (skylake_avx512), Python 2.7.5
See https://gist.github.com/8351b975af64f2fc0dd608d59d6a2aa3 for a full test report.

**Review by smoors — APPROVED** [review]
lgtm

**Comment by smoors** [comment]
Going in, thanks @boegel!

**Pull request merged**
