### PR TITLE
use xorg-macros as dependency in X11 easyconfigs (rather than installing it as a bundle component)

### PR DESCRIPTION
**Pull request by Flamefire**
(created using `eb --new-pr`)

- [x] requires ~~#9477~~ -> ~~#9578~~ (fixed `xorg-macros` easyconfigs)
- [x] requires ~~https://github.com/easybuilders/easybuild-easyblocks/pull/1897~~ (`Bundle` fix)

I updated all X11 ECs which have a corresponding xorg-macros EC (as far as I could tell), the other should maybe be archived as most are quite old (e.g. GCC 5)

### CODE REVIEW

**Comment by Flamefire** [comment]
@boegel The unit tests seems to not be able to find the patch for libxcb in e.g. X11-20170129-GCCcore-6.3.0.eb and hence fails the test O.o

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
node2405.golett.os - Linux centos linux 7.7.1908, Intel(R) Xeon(R) CPU E5-2680 v3 @ 2.50GHz, Python 2.7.5
See https://gist.github.com/7d8f4c7758f7384093380fcbe7f772da for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 8 out of 8 (8 easyconfigs in this PR)
node2599.golett.os - Linux centos linux 7.7.1908, Intel(R) Xeon(R) CPU E5-2680 v3 @ 2.50GHz, Python 2.7.5
See https://gist.github.com/08d27661bb74cd1c7969c08cd09a013d for a full test report.

**Comment by boegel** [comment]
Going in, thanks @Flamefire!

**Pull request merged**
