### PR TITLE
fix download url for UDUNITS 2.2.26

### PR DESCRIPTION
**Pull request by pescobar**

### CODE REVIEW

**Comment by verdurin** [comment]
Test report by @verdurin
**SUCCESS**
Build succeeded for 0 out of 0 (3 easyconfigs in total)
nuc.lan - Linux Fedora 32, x86_64, Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz, Python 3.8.7
See https://gist.github.com/6805c3b244ab9bb50c3afa4b875735c5 for a full test report.

**Comment by verdurin** [comment]
Test report by @verdurin
**SUCCESS**
Build succeeded for 3 out of 3 (3 easyconfigs in total)
nuc.lan - Linux Fedora 32, x86_64, Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz, Python 3.8.7
See https://gist.github.com/8cfa94c1f525b4c3af9c4fa4950a46fa for a full test report.

**Comment by verdurin** [comment]
@boegelbot please test @ generoso

**Review by migueldiascosta — APPROVED** [review]
lgtm, according to `eb --from-pr 12020 --fetch --force-download`

**Comment by migueldiascosta** [comment]
@boegelbot please test @ generoso EB_ARGS="--fetch --force-download"

**Comment by migueldiascosta** [comment]
Test report by @migueldiascosta
**SUCCESS**
Build succeeded for 11 out of 11 (11 easyconfigs in total)
sms - Linux centos linux 7.6.1810, x86_64, AMD EPYC 7601 32-Core Processor (zen), Python 2.7.5
See https://gist.github.com/f8212478e4219e4b2d9a7d7f3c5797c0 for a full test report.

**Review by migueldiascosta — APPROVED** [review]
lgtm

**Comment by migueldiascosta** [comment]
Going in, thanks @pescobar!

**Comment by SethosII** [comment]
The new URL seems to be broken again? At least I can't find anything related to `UDUNITS` here: https://fossies.org/linux/privat/legacy/?

**Comment by boegel** [comment]
@SethosII Indeed, let's follow up on that via #11951...

**Pull request merged**
