### PR TITLE
{lib}[fosscuda/2018b] psutil v5.6.1 w/ Python 2.7.15

### PR DESCRIPTION
**Pull request by adiemu5**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by adiemu5** [comment]
Test report by @adiemu5
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
gpu01.wave.scu.edu - Linux centos linux 7.6.1810, Intel(R) Xeon(R) Gold 6148 CPU @ 2.40GHz, Python 2.7.5
See https://gist.github.com/f00095d8ea53a81fa939209f0025fdf8 for a full test report.

**Comment by adiemu5** [comment]
Test report by @adiemu5
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
gpu01.wave.scu.edu - Linux centos linux 7.6.1810, Intel(R) Xeon(R) Gold 6148 CPU @ 2.40GHz, Python 2.7.5
See https://gist.github.com/84f47a9bb63322229d400fdd0c17c0b5 for a full test report.

**Comment by adiemu5** [comment]
Test report by @adiemu5
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
gpu01.wave.scu.edu - Linux centos linux 7.6.1810, Intel(R) Xeon(R) Gold 6148 CPU @ 2.40GHz, Python 2.7.5
See https://gist.github.com/59d6fd8f4fe754a2b93131297f4f2dce for a full test report.

**Comment by migueldiascosta** [comment]
@adiemu5 you do need to define `download_dep_fail` (it isn't necessary in #8025 because that's using a `PythonBundle` and `download_dep_fail` is set by default, not (yet) for `PythonPackage`)

**Comment by adiemu5** [comment]
Test report by @adiemu5
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
gpu01.wave.scu.edu - Linux centos linux 7.6.1810, Intel(R) Xeon(R) Gold 6148 CPU @ 2.40GHz, Python 2.7.5
See https://gist.github.com/4fb0821c54267e2c2b5711bda7c94908 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
node2102.delcatty.os - Linux centos linux 7.6.1810, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.7.5
See https://gist.github.com/b422fa5371f7336632cb1a0e68d4e5d4 for a full test report.

**Comment by boegel** [comment]
Going in, thanks @adiemu5!

**Pull request merged**
