### PR TITLE
add patch for adding a write memory barrier to all OpenMPI 4.1.x easyconfigs

### PR DESCRIPTION
**Pull request by bedroge**
This solves a bug in the `smcuda` btl that causes MPI applications to crash or hang on Neoverse V1 CPUs, see https://github.com/open-mpi/ompi/issues/12270. The issue was fixed in https://github.com/open-mpi/ompi/pull/12344 for OpenMPI 4.1.x (4.1.7 should include the fix).

### CODE REVIEW

**Comment by bedroge** [comment]
@boegelbot please test @ generoso

**Comment by bedroge** [comment]
@boegelbot please test @ jsc-zen3

**Comment by bedroge** [comment]
> Test report by @boegelbot
> **FAILED**
> Build succeeded for 15 out of 16 (14 easyconfigs in total)
> jsczen3c1.int.jsc-zen3.fz-juelich.de - Linux Rocky Linux 9.3, x86_64, AMD EPYC-Milan Processor (zen3), Python 3.9.18
> See https://gist.github.com/boegelbot/7b076361a2cf4873b7486a6b07a4ed4a for a full test report.

They all succeeded except `OpenMPI-4.1.1-intel-compilers-2021.4.0.eb`:

```
============================================================================
== Configuring Open MPI
============================================================================

*** Startup tests
checking build system type... x86_64-pc-linux-gnu
checking host system type... x86_64-pc-linux-gnu
checking target system type... x86_64-pc-linux-gnu
checking for x86_64-pc-linux-gnu-gcc... icc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... configure: error: in `/tmp/boegelbot/OpenMPI/4.1.1/intel-compilers-2021.4.0/openmpi-4.1.1':
configure: error: cannot run C compiled programs.
If you meant to cross compile, use `--host'.
See `config.log' for more details
 (at easybuild/easybuild-framework/easybuild/tools/run.py:682 in parse_cmd_output)
```

Not sure what's wrong here...

**Comment by boegel** [comment]
> > Test report by @boegelbot
> > **FAILED**
> > Build succeeded for 15 out of 16 (14 easyconfigs in total)
> > jsczen3c1.int.jsc-zen3.fz-juelich.de - Linux Rocky Linux 9.3, x86_64, AMD EPYC-Milan Processor (zen3), Python 3.9.18
> > See https://gist.github.com/boegelbot/7b076361a2cf4873b7486a6b07a4ed4a for a full test report.
> 
> They all succeeded except `OpenMPI-4.1.1-intel-compilers-2021.4.0.eb`:
> 
> ```
> ============================================================================
> == Configuring Open MPI
> ============================================================================
> 
> *** Startup tests
> checking build system type... x86_64-pc-linux-gnu
> checking host system type... x86_64-pc-linux-gnu
> checking target system type... x86_64-pc-linux-gnu
> checking for x86_64-pc-linux-gnu-gcc... icc
> checking whether the C compiler works... yes
> checking for C compiler default output file name... a.out
> checking for suffix of executables... 
> checking whether we are cross compiling... configure: error: in `/tmp/boegelbot/OpenMPI/4.1.1/intel-compilers-2021.4.0/openmpi-4.1.1':
> configure: error: cannot run C compiled programs.
> If you meant to cross compile, use `--host'.
> See `config.log' for more details
>  (at easybuild/easybuild-framework/easybuild/tools/run.py:682 in parse_cmd_output)
> ```
> 
> Not sure what's wrong here...

It's related to RHEL9 and the newer glibc:

```
In file included from conftest.c(10):
/usr/include/stdio.h(824): error: attribute "__malloc__" does not take arguments
    __attribute_malloc__ __attr_dealloc (pclose, 1) __wur;
                         ^

compilation aborted for conftest.c (code 2)
configure:6725: $? = 2
configure:6732: ./conftest
./configure: line 6734: ./conftest: No such file or directory
```

It seems like that Intel compilers version is basically not compatible with RHEL 9.

I won't let that block this PR, the problem is not caused by the patch being added.

**Review by boegel — APPROVED** [review]
lgtm

**Comment by boegel** [comment]
Going in, thanks @bedroge!

**Pull request merged**
