### PR TITLE
{astro,lib}[GCCcore/8.3.0,foss/2019b] OpenJPEG v2.3.1, SunPy v1.1.3 w/ Python 3.7.4

### PR DESCRIPTION
**Pull request by branfosj**
(created using `eb --new-pr`)

astropy is in #10675

### CODE REVIEW

**Comment by branfosj** [comment]
Test report by @branfosj
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in this PR)
bear-pg0211u03a.bear.cluster - Linux centos linux 7.7.1908, x86_64, Intel(R) Xeon(R) Gold 6248 CPU @ 2.50GHz (cascadelake), Python 3.6.8
See https://gist.github.com/75200b7a26b3838b6af466273ed84afc for a full test report.

**Comment by branfosj** [comment]
Test report by @branfosj
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in this PR)
bber0501u03b.bb2.cluster - Linux centos linux 7.7.1908, x86_64, Intel(R) Xeon(R) CPU E5-2690 v3 @ 2.60GHz (haswell), Python 3.6.8
See https://gist.github.com/2a24d7d7d8aa16d72f69c8a2c94028a5 for a full test report.

**Comment by branfosj** [comment]
Test report by @branfosj
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in this PR)
bear-pg0305u15a.bear.cluster - Linux RHEL 7.6, POWER, 8335-GTX (power9le), Python 3.6.8
See https://gist.github.com/2fa5013338ad6c38dfef576995f9d972 for a full test report.

**Comment by branfosj** [comment]
close / open to retrigger tests now that #10675 is merged

**Comment by Micket** [comment]
Test report by @Micket
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in this PR)
hebbe-c1 - Linux centos linux 7.7.1908, x86_64, Intel Core Processor (Haswell, no TSX), Python 2.7.5
See https://gist.github.com/d3cf1c4c1456cc3ab8f4806d75ce0ca1 for a full test report.

**Comment by Micket** [comment]
Travis is stuck again

**Comment by Micket** [comment]
Going in, thanks @branfosj!

**Pull request merged**
