### PR TITLE
{ai}[foss/2023a] skorch v0.15.0, Braindecode v0.8.1 w/ PyTorch 2.1.2 CUDA 12.1.1

### PR DESCRIPTION
**Pull request by lexming**
(created using `eb --new-pr`)

Depends on:
* [x] #19877 
* [x] #19666

### CODE REVIEW

**Comment by lexming** [comment]
@boegelbot please test @ jsc-zen3

**Comment by lexming** [comment]
@boegelbot please test @ jsc-zen3

**Comment by lexming** [comment]
@boegelbot: please test @ generoso

**Review by Micket — APPROVED** [review]
lgtm

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in total)
node3303.joltik.os - Linux RHEL 8.8, x86_64, Intel(R) Xeon(R) Gold 6242 CPU @ 2.80GHz (cascadelake), 1 x NVIDIA Tesla V100-SXM2-32GB, 545.23.08, Python 3.6.8
See https://gist.github.com/boegel/d9a1997ff0743daecb8951da2e04409d for a full test report.

**Comment by boegel** [comment]
Going in, thanks @lexming!

**Pull request merged**
