### PR TITLE
{lib}[system/system] GitPython v2.1.15

### PR DESCRIPTION
**Pull request by boegel**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
boegel.ugent.be - Darwin UNKNOWN UNKNOWN, x86_64, Intel(R) Core(TM) i5-7360U CPU @ 2.30GHz (skylake), Python 3.8.5
See https://gist.github.com/51598d146d9a087b5dcd31ab80772c49 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
node3135.skitty.os - Linux centos linux 7.8.2003, x86_64, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz, Python 3.6.8
See https://gist.github.com/0bae6d018ab0c385edcae43babd60da1 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
node3415.kirlia.os - Linux centos linux 7.8.2003, x86_64, Intel(R) Xeon(R) Gold 6240 CPU @ 2.60GHz (cascadelake), Python 2.7.5
See https://gist.github.com/8f56186a62dda5c90a84222609b33496 for a full test report.

**Comment by boegel** [comment]
@boegelbot please test @ generoso

**Comment by bartoldeman** [comment]
Test report by @bartoldeman
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
build-node.computecanada.ca - Linux centos linux 7.8.2003, x86_64, Intel Xeon Processor (Skylake, IBRS), Python 3.7.7
See https://gist.github.com/17c2ef35ef055f9a0ab7f6ad1e2f3a04 for a full test report.

**Review by bartoldeman — APPROVED** [review]
LGTM

**Comment by bartoldeman** [comment]
Going in, thanks @boegel!

**Pull request merged**
