### PR TITLE
{lib}[GCCcore/7.3.0] libjpeg-turbo v2.0.1

### PR DESCRIPTION
**Pull request by jose-d**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by jose-d** [comment]
Test report by @jose-d
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
koios2 - Linux centos linux 7.3.1611, Intel(R) Xeon(R) Gold 6130 CPU @ 2.10GHz, Python 2.7.5
See https://gist.github.com/40422f786091874087ba01a3b9c79f8c for a full test report.

**Comment by jose-d** [comment]
based on `libjpeg-turbo-2.0.0-GCCcore-7.3.0.eb` version++, cmake version++.

**Comment by boegel** [comment]
@jose-d This looks good to go, but I suspect you're adding this easyconfig so you can use it as a dependency for easyconfigs using a `2018b` toolchain?

If so, you should stick to `libjpeg-turbo` 2.0.0 for the `2018b` "generation" of easyconfigs, to ensure that easyconfigs using a `2018b` toolchain are compatible with each other.

We will update to the latest `libjpeg-turbo` for the upcoming `2019a` common toolchains, which will be defined soon.

**Comment by jose-d** [comment]
@boegel, yes, it's from the same project as #7354.. 
(Py3.7 + foss2018b) So → let's keep it out of the upstream ec tree.

**Pull request closed without merging**
