### PR TITLE
{devel,lib,tools}[GCCcore/13.3.0] pytest-workflow v2.1.0, tqdm v4.66.5, typing-extensions v4.11.0

### PR DESCRIPTION
**Pull request by Flamefire**
(created using `eb --new-pr`)

Requires
- [ ] #21424

### CODE REVIEW

**Comment by Flamefire** [comment]
Test report by @Flamefire
**SUCCESS**
Build succeeded for 3 out of 3 (3 easyconfigs in total)
i7119 - Linux Rocky Linux 8.9 (Green Obsidian), x86_64, AMD EPYC 7702 64-Core Processor (zen2), Python 3.8.17
See https://gist.github.com/Flamefire/8a5c42629e3a4bfa57353de28012ec78 for a full test report.

**Comment by SebastianAchilles** [comment]
@boegelbot please test @ jsc-zen3

**Comment by SebastianAchilles** [comment]
@boegelbot please test @ jsc-zen3

**Comment by SebastianAchilles** [comment]
@boegelbot please test @ generoso

**Review by SebastianAchilles — APPROVED** [review]
lgtm

**Comment by SebastianAchilles** [comment]
Going in, thanks @Flamefire!

**Pull request merged**
